### ISSUE TITLE
How can I use webcam as input?

### ISSUE THREAD

**Issue by RealBBakGosu** [google/mediapipe#10]
Do you support the use of a webcam as an input tool?

**Comment by mgyong** [comment]
@RealBBakGosu As of July 2019, we support only camera for mobile android through Android cameraX api. See all the mobile android examples particularly hello android
https://mediapipe.readthedocs.io/en/latest/hello_world_android.html

For webcam, this is something we will be looking into. If you like to contribute a calculator to use OpenCV functionality to import the video through a webcam you can write a calculator and import the below header files into your opencv_videolivecapature_calculator.cc

https://github.com/google/mediapipe/blob/master/mediapipe/framework/port/opencv_core_inc.h
https://github.com/google/mediapipe/blob/master/mediapipe/framework/port/opencv_highgui_inc.h
https://github.com/google/mediapipe/blob/master/mediapipe/framework/port/opencv_video_inc.h

**Comment by Zumbalamambo** [comment]
@mgyong but is there any example or documentation to write a custom calculator?

**Comment by mcclanahoochie** [comment]
Please find our desktop + webcam examples [here](https://mediapipe.readthedocs.io/en/latest/examples.html#desktop)

**Comment by eknight7** [comment]
Also this: https://mediapipe.readthedocs.io/en/latest/calculator.html.

**Comment by Alex-Beh** [comment]
> Please find our desktop + webcam examples [here](https://mediapipe.readthedocs.io/en/latest/examples.html#desktop)

Hello, the link is broken. Do you mind to update the link? Thanks
