### ISSUE TITLE
Availability of attention mesh

### ISSUE THREAD

**Issue by thekirankumar** [google/mediapipe#1000]
In the paper https://arxiv.org/pdf/2006.10962v1.pdf , accuracy of lip and eye landmarks can be improved by having sub models.
Are there any plans to open source these models (attention mesh) and demos as part of mediapipe soon ? 
Thanks in advance for the great work you guys are doing.

**Comment by fanzhanggoogle** [comment]
Hi, thank you for your interest. Unfortunately we currently don't have plan to release the attention mesh model in the near future.

**Comment by seungwonpark** [comment]
@fanzhanggoogle Sorry for asking again, but are there any updates on releasing attention mesh model?

**Comment by kruysh** [comment]
Sorry for asking again, but are there any updates on releasing attention mesh model?

**Comment by sgowroji** [comment]
Hi @seungwonpark & @kruysh, Currently we don't have any plans as of now. But i would request you to subscribe our page and  to get the latest updates.

**Comment by sgowroji** [comment]
Hi All, We are glad to update that we have the added [attention model](https://google.github.io/mediapipe/solutions/face_mesh#attention-mesh-model) in our face mesh.
