### ISSUE TITLE
OpenCV: FFMPEG: tag 0x31637661/'avc1' is not supported with codec id 28 and format 'mp4 / MP4 (MPEG-4 Part 14)'

### ISSUE THREAD

**Issue by Owen1234560** [google/mediapipe#1001]
when I run 
"GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip --calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt --input_side_packets=input_video_path=/home/owen/桌面/snowboarding.mp4,output_video_path=/home/owen/桌面/1.mp4,aspect_ratio=3:4", 

output:
OpenCV: FFMPEG: tag 0x31637661/'avc1' is not supported with codec id 28 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x00000021/'!???'

How to solve this problem?

**Comment by jiuqiant** [comment]
That means your machine doesn't have x264 decoder.

Solution 1. Install x264 decoder support to your local machine.

Solution 2. Modify the output file to be mkv.
a) Modify https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt#L198 to be 

```
codec: "MPEG"
video_format: "mkv
```

b) Change the output file path from "/home/owen/桌面/1.mp4" to be "/home/owen/桌面/1.mkv" in the run command.

**Comment by Owen1234560** [comment]
> That means your machine doesn't have x264 decoder.
> 
> Solution 1. Install x264 decoder support to your local machine.
> 
> Solution 2. Modify the output file to be mkv.
> a) Modify https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt#L198 to be
> 
> ```
> codec: "MPEG"
> video_format: "mkv
> ```
> 
> b) Change the output file path from "/home/owen/桌面/1.mp4" to be "/home/owen/桌面/1.mkv" in the run command.

Thank you very much. I solve the problem.

**Comment by jiuqiant** [comment]
Glad to hear that.
