### ISSUE TITLE
How to use object tracking in my own android project

### ISSUE THREAD

**Issue by namtpham** [google/mediapipe#1002]
Hi there,

In my project, I use TFL to detect objects. Then I have detected objects with IDs. How can I use mediapipe object tracking to track my detected objects?

I built a mediapipe object tracking AAR using the following manual but I have no idea how to do next https://google.github.io/mediapipe/getting_started/android_archive_library.html

Could you guys please suggest me a solution.
Thank you very much.

**Comment by dolmens** [comment]
See the code in mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java. The key point is to construct a FrameProcessor. you just need to specify the graph, input and output.
