### ISSUE TITLE
Lip sub model availability

### ISSUE THREAD

**Issue by thekirankumar** [google/mediapipe#1003]
The work mentioned in https://arxiv.org/pdf/2006.10962v1.pdf is amazing, any plans to open source the Lip submodel mentioned in it ?
Thanks in advance

**Comment by mgyong** [comment]
This is something we are working on and maybe in end 2020

**Comment by thekirankumar** [comment]
Thanks a lot, waiting eagerly for this release

**Comment by LarryBrinzo** [comment]
@mgyong By when will the Lip submodel will be open-sourced. Thanks in advance.

**Comment by mgyong** [comment]
@LarryBrinzo No plans to open source. What is your use case?

**Comment by LarryBrinzo** [comment]
@mgyong I am working on Virtual try-on of lipstick. And as mentioned in this [paper](https://arxiv.org/pdf/2006.10962v1.pdf), that the FaceMesh model doesn't work in this use case because of accuracy. Eye and iris submodel from this paper is already been open-sourced. Any plans to open source lips submodel. Thanks in advance.

**Comment by thekirankumar** [comment]
> This is something we are working on and maybe in end 2020. We will update this thread when it is announced!

Hi @mgyong, I was really looking forward to the release in December.

**Comment by thekirankumar** [comment]
@mgyong I am also looking at your new lip submodel as a way to achieve virtual try-on of lipstick. Please do let me know if the plan for end of 2020 release has changed. I was really counting on this until now. Would have to look elsewhere if there is no plan to release this. Thanks in advance.

**Comment by mgyong** [comment]
Sorry for the early respond that is incorrect. We do not have plans to open source the lip model

**Comment by sgowroji** [comment]
We are closing this issue w.r.t the above [comment](https://github.com/google/mediapipe/issues/1003#issuecomment-736223931).
