### ISSUE TITLE
How can I use upperbody pose tracking in browser in my own project?

### ISSUE THREAD

**Issue by saurabh1043** [google/mediapipe#1004]
Is there any way I can use blazepose in my webapp before the release of the official API ?

**Comment by cheoljunlee** [comment]
I think latest version has problem related with UpperBodyPoseTracker.
@chuoling, please check the last commit.

**Comment by saurabh1043** [comment]
I was able to convert and load the model in Tensorflow.js. But I've no idea on how to post-process the outputs I am getting. 
I'm getting 3 tensors as output. Any idea on how I can convert these to keypoint co-ordinates in javascript ?.

when I print 'model.outputs'in python, I get - 
[<tf.Tensor 'output_segmentation/BiasAdd_1:0' shape=(None, 128, 128, 1) dtype=float32>,
 <tf.Tensor 'tf_op_layer_Sigmoid/Sigmoid_1:0' shape=(None, 1, 1, 1) dtype=float32>,
 <tf.Tensor 'tf_op_layer_ld_3d/ld_3d_1:0' shape=(1, 124) dtype=float32>]
![Screenshot (71)](https://user-images.githubusercontent.com/23092285/90327992-70ef6300-dfb6-11ea-87d2-b079fdbb59ea.png)

**Comment by saurabh1043** [comment]
Any Progress or timelines ??

**Comment by mgyong** [comment]
@saurabh1043 We are working on open sourcing a MediaPipe Javascript solution API for popular MediaPipe models like BlazePose. We plan to release something in 2H2020 and will update this thread when released. Also keep an eye on our latest releases

**Comment by s-kav** [comment]
> 
> 
> Any Progress or timelines for the tfjs API for BlazePose??

You can try these:
https://terryky.github.io/tfjs_webgl_app/#blazepose-fullbody
https://github.com/terryky/tfjs_webgl_app

**Comment by chuoling** [comment]
Just to close this issue: We released first round of MediaPipe JavaScript Solution APIs (including Pose, Face Mesh, Hands, and Holistic) in Dec 2020, and since then have made improvements and released more solutions. Please find more information in https://google.github.io/mediapipe/getting_started/javascript.html.
