### ISSUE TITLE
Build Error on Windows

### ISSUE THREAD

**Issue by boger57** [google/mediapipe#1007]
when I run hello world by the command `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//Administrator//AppData//Local//Programs//Python//Python38-32//python.exe" mediapipe/examples/desktop/hello_world`, I came across a build error.
![1](https://user-images.githubusercontent.com/41398766/90228847-87c47700-de49-11ea-9fb5-b60efbfb03c7.PNG)
Can you help me to figure it out? Thank you so much!!!

**Comment by jiuqiant** [comment]
Please git checkout v0.7.5 to use an older version of MediaPipe. 
See https://github.com/google/mediapipe/issues/908#issuecomment-663800716

**Comment by dgrnd4** [comment]
@boger57  did the change of the version of mediapipe solve your problem?

**Comment by boger57** [comment]
> Please git checkout v0.7.5 to use an older version of MediaPipe.
> See [#908 (comment)](https://github.com/google/mediapipe/issues/908#issuecomment-663800716)

Thank you so much!! I have figured it out!

**Comment by boger57** [comment]
> @boger57 did the change of the version of mediapipe solve your problem?

Yes, it did help. You can refer to #908 . Good Luck!

**Comment by dgrnd4** [comment]
@boger57 I've Tried to change the version of mediapipe but still doesn't work. The problem with that command:
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//Administrator//AppData//Local//Programs//Python//Python38-32//python.exe" mediapipe/examples/desktop/hello_world`

is still this one: 

**INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 210
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linesep);f.write(\"try:\" + linesep);f.write(\"  library_paths =(...)): Impossibile trovare il file specificato.
 (error: 2)
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Traceback (most recent call last):
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 210
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linesep);f.write(\"try:\" + linesep);f.write(\"  library_paths =(...)): Impossibile trovare il file specificato.
 (error: 2)
INFO: Elapsed time: 0.240s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 11 targets configured)**
