### ISSUE TITLE
Why my aar file so large more than 100 MB ? 

### ISSUE THREAD

**Issue by aidenpearce001** [google/mediapipe#1008]
i had follow this post : https://google.github.io/mediapipe/getting_started/android_archive_library and my aar file is about 120 mb , whereas this git https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example/ only 52.7 MB , how can i reduce the size of my aar file(i build for only one hand tracking)

**Comment by AbhisKmr** [comment]
I also want to know the answer

**Comment by AbhisKmr** [comment]
add this `--linkopt="-s"` to the command
like: `bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a --linkopt="-s"  //path/to/the/aar/build/file:aar_name`

**Comment by jiuqiant** [comment]
> add this `--linkopt="-s"` to the command
> like: `bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a --linkopt="-s" //path/to/the/aar/build/file:aar_name`

Yes, stripping symbols can reduce the aar size drastically.
