### ISSUE TITLE
Landmarks to Recolor Calculator

### ISSUE THREAD

**Issue by LarryBrinzo** [google/mediapipe#1009]
Is there any calculator that draw a path from the given coordinates (Curve Fitting) and recolors that path. Required for Facemesh.

**Comment by mgyong** [comment]
There isn't one currently. We welcome contributions

**Comment by LarryBrinzo** [comment]
Sure. Thank you for your reply. Can you suggest any OpenGL tutorial for MediaPipe?

**Comment by mcclanahoochie** [comment]
The MediaPipe documentation has a nice overview of [using the GPU](https://google.github.io/mediapipe/framework_concepts/gpu.html) within the framework. 
For writing your own GPU code compatible with MediaPipe (note that Metal is preferred on iOS), any online tutorial on [OpenGL ES](https://www.google.com/search?q=learning+OpenGL+ES&oq=learning+OpenGL+ES&aqs=chrome..69i57j0i22i30j0i433j69i65j69i61j69i65j69i60j69i61.1790j1j7&sourceid=chrome&ie=UTF-8) will be a great starting point, as well as looking at existing calculators ([grayscale calculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/image/luminance_calculator.cc) being one of the simplest).
