### ISSUE TITLE
Output numbers of regressors in pose detection of BlazePose

### ISSUE THREAD

**Issue by ChongMingWei** [google/mediapipe#1010]
So, in BlazePose we have detector and tracker.
I just download the detector part [tflite model](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection.tflite) and try to figure out the parameters inside.
However, there is 1 question here:
1. At the end of the detection network, there are classificators and regressors as outputs. The size of classificators (1x896x1) is mentioned in the BlazeFace paper and seems reasonable. However, the size of regressors (1x896x12) doesn't match the size in BlazeFace (which is 1x896x16). I know there are some changes in BlazePose. 
My assumptions of the size of regressors are as below:
a. The corners of the face bounding box (x and y of the left-top and right-down)
b. The midpoint of hips (x , y)
c. The size of the circle circumscribing the whole person
d. The angle between the lines connecting the two mid-shoulder and mid-hip points
Totally 4+2+1+1 = 8 
Maybe there are something mentioned in the paper or the [Google AI Blog](https://ai.googleblog.com/2020/08/on-device-real-time-body-pose-tracking.html) and I just miss it.
Please help me, Thx!!

**Comment by vbazarevsky** [comment]
Hello, please consider related MediaPipe graph. All the needed configuration for this model can be found here: https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection_cpu.pbtxt#L85

The default path would be to use this model with MediaPipe.

**Comment by alessioanghileri** [comment]
Hi, this is not clear to me; 
could you please explain the meaning of the regressor output (1, 896, 12) and the classifier output (1, 896, 12)?
How could I extract the 33 keypoints coordinates?

Thanks in advance

**Comment by vbazarevsky** [comment]
BlazePose is a two stage pipeline. (1, 896, 12) - is a regressor output for the first detector stage. 
It contains 896 anchors, each anchor(or prior) contains:
SSD standard:
 - dx, dy for face bounding box center
 - width, height for face bounding box 
Additional keypoints:
 - dx, dy for upper-body center
 - dx, dy for upper-body rotation point
 - dx, dy for full-body center
 - dx, dy for full-body rotation point

Then depending on the pipeline (upper-body vs full-body) we estimate appropriate ROI on the basis of center and rotation point, and pass it to the tracker model, which produce either 25 kp (for upper-body model, which is released in MediaPipe) or 33 kp for Full-Body.

More information on BlazePose can be found here: https://arxiv.org/abs/2006.10204

**Comment by alessioanghileri** [comment]
Thanks, but it's still not clear to me how to extract keypoints coordinates from the (1,896,1) output.
Reading from the paper, it seems that the model should return 35x3 (with X,Y,visibility) for each keypoint (33 kp plus 2 more kp)

**Comment by Laubeee** [comment]
@alessioanghileri did you solve this?

**Comment by alessioanghileri** [comment]
@Laubeee No, because in the meantime Mediapipe released the Python APIs that were enough for me.

API Here: https://google.github.io/mediapipe/solutions/pose.html

**Comment by Laubeee** [comment]
Pity, I'd still like to infer the models directly..

@vbazarevsky the paper does not state how the 896 anchors are mingled into the ROI...
I studied the [pose graph](https://viz.mediapipe.dev/demo/pose_tracking) for a while and I'd be glad if you could confirm or deny whether following assumptions are correct:
1. the 896x1 output states how likely the anchor contains a face (or pose..)
2. those who are above a certain threshold (e.g. 0.5) are considered and further reduced using non-max suppression
3. out of all remaining anchors center+rotation points one single ROI is calculated (that one is quite a wild guess... is it possible to have multiple ROI instead, that are then fed to the tracker? It would make more sense especially since the tracker only predicts one person and adjusts the ROI based on that center+rotation point)

**Comment by ashutoshsoni891** [comment]
Hi @Laubeee !
Is it necessary to run both the models one after other ( blazepose detection + blazepose keypoints ) ?

**Comment by Laubeee** [comment]
yes and no
From what I understood the detection gives you the ROI and the keypoint detection expects only this ROI

But as said, I have only roughly experimented with blaze pose at this moment

**Comment by mlizhardy** [comment]
does anyone have these (896) anchors hard coded similar to https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/testdata/anchor_golden_file_0.txt ?

**Comment by Laubeee** [comment]
@mlizhardy you mean the default anchor-boxes?
I'm note sure to what the ones you linked refer, 2944lines seem a bit much. But the default boxes can be generated, see for example: https://github.com/terryky/tfjs_webgl_app/blob/master/blazepose_fullbody/tfjs_blazepose.js#L22

it seems to be the js-version of https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/ssd_anchors_calculator.cc

and gives 896 anchors

**Comment by sgowroji** [comment]
Hi @ChongMingWei, Could you please respond if you still looking answer for the above queries. Thanks!
