### ISSUE TITLE
_framework_bindings

### ISSUE THREAD

**Issue by zhangatao** [google/mediapipe#1011]
Excuse me, what I clone is the latest version of the project. When I execute this command python -m mediapipe.examples.desktop.youtube8m.generate_vggish_frozen_graph, the following error ModuleNotFoundError: No module named'mediapipe.python._framework_bindings' appears, Excuse me, what is the reason? I didn't find the py file _framework_bindings in the project.

**Comment by tomkolron** [comment]
i have the same probelm on the rpi-4 cant find a solution anywhere
