### ISSUE TITLE
yt8m python scripts are not working after v0.7.9

### ISSUE THREAD

**Issue by zhangatao** [google/mediapipe#1012]
Excuse me, what I clone is the latest version of the project. When I execute this command: python -m mediapipe.examples.desktop.youtube8m.generate_vggish_frozen_graph, the following error ModuleNotFoundError: No module named'mediapipe.python._framework_bindings' appears, Excuse me, what is the reason? I didn't find the py file _framework_bindings in the project.

**Comment by jiuqiant** [comment]
Whoops, we add some python binding code for the framework and it seems like that breaks the yt8m example.  The temporarily workaround is to remove 3 lines from "mediapipe/\_\_init\_\_.py" like the following:

```
diff --git a/mediapipe/__init__.py b/mediapipe/__init__.py
index c0a2758..69d7dfc 100644
--- a/mediapipe/__init__.py
+++ b/mediapipe/__init__.py
@@ -12,7 +12,3 @@ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 """
-
-import mediapipe.examples.python as examples
-from mediapipe.python import *
-import mediapipe.util as util
```
