### ISSUE TITLE
Android device upbody-pose result get error!

### ISSUE THREAD

**Issue by lovehuanhuan** [google/mediapipe#1013]
in“protected void onCreate(Bundle savedInstanceState) {” I got exceptions!

 com.google.protobuf.InvalidProtocolBufferException: Message type does not match the expected type. Expected: null Got: mediapipe.NormalizedLandmarkList
08-17 08:59:42.640  4270  4328 E zzp     :      at com.google.mediapipe.framework.PacketUtil.unpack(PacketUtil.java:59)
08-17 08:59:42.640  4270  4328 E zzp     :      at com.google.mediapipe.framework.PacketGetter.getProto(PacketGetter.java:126)
08-17 08:59:42.640  4270  4328 E zzp     :      at com.google.mediapipe.apps.upperbodyposetrackinggpu.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:46)
08-17 08:59:42.640  4270  4328 E zzp     :      at com.google.mediapipe.apps.upperbodyposetrackinggpu.MainActivity$$Lambda$0.process(Unknown Source:0)

**Comment by mgyong** [comment]
More info needed. Phone model, OS version number?

**Comment by umezy** [comment]
I got same Error below.

Phone model: HUAWEI nova lite 3
Android version: 10

> 09-22 10:03:34.633 27096 27175 E MainActivity: com.google.protobuf.InvalidProtocolBufferException: Message type does not match the expected type. Expected: null Got: mediapipe.NormalizedLandmarkList
> 09-22 10:03:34.633 27096 27175 E MainActivity: 	at com.google.mediapipe.framework.ProtoUtil.unpack(ProtoUtil.java:61)
> 09-22 10:03:34.633 27096 27175 E MainActivity: 	at com.google.mediapipe.framework.PacketGetter.getProto(PacketGetter.java:126)
> 09-22 10:03:34.633 27096 27175 E MainActivity: 	at com.google.mediapipe.apps.upperbodyposetrackinggpu.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:43)
> 09-22 10:03:34.633 27096 27175 E MainActivity: 	at com.google.mediapipe.apps.upperbodyposetrackinggpu.MainActivity$$Lambda$0.process(Unknown Source:0)

**Comment by shehramjamil** [comment]
Got the same error.
Phone : Redmi 8 
Android version 10.

**Comment by lupries** [comment]
Also got this error. Quick workaround (as done in handtrackinggpu):

replace [this](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/upperbodyposetrackinggpu/MainActivity.java#L42-L43) by
```
byte[] landmarksRaw = PacketGetter.getProtoBytes(packet);
NormalizedLandmarkList poseLandmarks = NormalizedLandmarkList.parseFrom(landmarksRaw);
```
Then it worked.

**Comment by H1Gdev** [comment]
Another solution is to do the following with `onCreate`:

```java
ProtoUtil.registerTypeName(NormalizedLandmarkList.class, "mediapipe.NormalizedLandmarkList");
```

**Comment by bugmany** [comment]
I've got same Error as below.

> in“protected void onCreate(Bundle savedInstanceState) {” I got exceptions!
> 
> com.google.protobuf.InvalidProtocolBufferException: Message type does not match the expected type. Expected: null Got: mediapipe.NormalizedLandmarkList
> 08-17 08:59:42.640 4270 4328 E zzp : at com.google.mediapipe.framework.PacketUtil.unpack(PacketUtil.java:59)
> 08-17 08:59:42.640 4270 4328 E zzp : at com.google.mediapipe.framework.PacketGetter.getProto(PacketGetter.java:126)
> 08-17 08:59:42.640 4270 4328 E zzp : at com.google.mediapipe.apps.upperbodyposetrackinggpu.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:46)
> 08-17 08:59:42.640 4270 4328 E zzp : at com.google.mediapipe.apps.upperbodyposetrackinggpu.MainActivity$$Lambda$0.process(Unknown Source:0)

then, I have tried two ways that @H1Gdev's way and @lupries's way solved it, but I got different results with two ways.
so I did not know which method is right, could someone tell me?

**Comment by H1Gdev** [comment]
Which one did you expect ?

Strictly speaking, `parseFrom` method to call is different.
`PacketGetter.getProto(packet, ormalizedLandmarkList.class)` will calls `public static com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmarkList parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)`

**Comment by sgowroji** [comment]
Hi @lovehuanhuan, Could you please test the above with the latest release and let us know if you still see the error. Thanks!
