### ISSUE TITLE
performance of gray image is not so good

### ISSUE THREAD

**Issue by zhenxingcc** [google/mediapipe#1014]
Hi, I tested hand tracking on gray images ,but the performance is not so good compared to rgb images, So are there any plans to improve performance of gray frames?

Thanks.

**Comment by mgyong** [comment]
Can you share videos or pictures of your claim abt poor performance of gray images?

**Comment by zhenxingNreal** [comment]
> Can you share videos or pictures of your claim abt poor performance of gray images?

hi, here is a video record, I used a gray camera with 640x480 image format from an eyeware glasses. In some cases that some fingers is not visible, performance is poor.

https://drive.google.com/file/d/1lrmC01tHvZtIH0dTBJHOaRDrfJjqqRUe/view?usp=sharing

**Comment by mcclanahoochie** [comment]
there is a lot of rectilinear lens distortion here (things are stretched towards edge of image) compared to a smartphone front facing camera. 
do you have an rgb version of that same wide-angle lens type? 
if not, then I would guess that the lens distortion in your gray camera is also playing a role in accuracy loss.
the center of the image has the least distortion, and i would expect decent results there, but as your hand moves to the side, it gets stretched, thus a possible loss in accuracy.
i would compare accuracy of a smartphone camera converted to grayscale vs smartphone camera rgb -- that would show the impact of grayscale images -- your test is also adding in distortion + grayscale.
do you have an rgb eyeware glasses camera to compare?

**Comment by zhenxingNreal** [comment]
> there is a lot of rectilinear lens distortion here (things are stretched towards edge of image) compared to a smartphone front facing camera.
> do you have an rgb version of that same wide-angle lens type?
> if not, then I would guess that the lens distortion in your gray camera is also playing a role in accuracy loss.
> the center of the image has the least distortion, and i would expect decent results there, but as your hand moves to the side, it gets stretched, thus a possible loss in accuracy.
> i would compare accuracy of a smartphone camera converted to grayscale vs smartphone camera rgb -- that would show the impact of grayscale images -- your test is also adding in distortion + grayscale.
> do you have an rgb eyeware glasses camera to compare?

Sorry, I have no rgb version cameras with the same lens type, I will try to undistort the gray images first and check the performance. Then I will give a video record later. 

Thanks for helpling  me figure out the problems.

**Comment by zhenxingNreal** [comment]
hi, I made some tests on undistorted images and found no significant improvement. By the way, In the previous distorted  images, performance was also not good when hand is in the middle part of image,where camera distortion is small.

**Comment by mcclanahoochie** [comment]
thanks for the updates and testing undistorted images.

i was not involved in model training, but i do believe the model was trained on primarily rgb data in the context of "selfie" use-case (not egocentric), and also likely not much was done on strictly grayscale data.

@fanzhanggoogle any thoughts or insights here?

**Comment by youzhenxing** [comment]
> thanks for the updates and testing undistorted images.
> 
> i was not involved in model training, but i do believe the model was trained on primarily rgb data in the context of "selfie" use-case (not egocentric), and also likely not much was done on strictly grayscale data.
> 
> @fanzhanggoogle any thoughts or insights here?

thanks for your response.

will there be any model optimization plans for gray camera and egocentric scenarios in the future? I mean, this is also a very typical application scenario,especially for headset AR/VR devices.

**Comment by zhenxingNreal** [comment]
> thanks for the updates and testing undistorted images.
> 
> i was not involved in model training, but i do believe the model was trained on primarily rgb data in the context of "selfie" use-case (not egocentric), and also likely not much was done on strictly grayscale data.
> 
> @fanzhanggoogle any thoughts or insights here?

thanks for your response.

will there be any model optimization plans for gray camera and egocentric scenarios in the future? I mean, this is also a very typical application case,especially for headset AR/VR devices.

**Comment by fanzhanggoogle** [comment]
Hi, thank you for reporting the quality issue. We don't have gray images in our training dataset, but we do have a lot of data augmentation to compensate for gray image. Also we do lack of first-person view training data in the model as well, I guess that's why the model works poorly on gray image + some distortion + first-person view. We are considering building a version specifically for first-person view as you mentioned for AR/VR use case. But currently don't have an exact date for it.

**Comment by Ammar-Fasih** [comment]
I'm running mediapipe library to extract the face landmakrs using the grayscale frames but it is showing me following error,

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "g:\My Drive\JP\JP\Tasks\SODEC - DS3\DetectionCV\faceMeshVideo copy.py", line 39, in <module>
    results = face_mesh.process(image)
  File "C:\Users\CC\AppData\Local\Programs\Python\Python310\lib\site-packages\mediapipe\python\solutions\face_mesh.py", line 124, in process
    return super().process(input_data={'image': image})
  File "C:\Users\CC\AppData\Local\Programs\Python\Python310\lib\site-packages\mediapipe\python\solution_base.py", line 354, in process
    if data.shape[2] != RGB_CHANNELS:
IndexError: tuple index out of range
```

Can anyone explain me why? or the mediapipe do not support grayscale at all?
