### ISSUE TITLE
how to get the raw landmarks projected on the image

### ISSUE THREAD

**Issue by xiezhongzhao** [google/mediapipe#1015]
The image resolution is 960*1280, and the landmarks are normalized. My question is how to get the raw landmarks projected on the image. 
![image](https://user-images.githubusercontent.com/21272179/90462315-3531d600-e13b-11ea-8b0b-0e461ffb9cdb.png)

**Comment by Gauraviiitian** [comment]
Hii @xiezhongzhao can you explain, how did you get it to work, I'm trying to do something similar.
