### ISSUE TITLE
iOS FaceMeshGpuApp example app displays mis-aligned face mesh

### ISSUE THREAD

**Issue by kapsyst** [google/mediapipe#1017]
I have noticed this issue on my iPhone X test device. The created face mesh seems rather squished, and doesn't line up with the camera image very well. The problem is especially apparent when opening my mouth - the lower chin vertices of the mesh are off by 2-3 cm.

Is this a problem caused by the example project? I would like to use MediaPipe for our project but if this is an issue inherent in the framework it won't be possible

ARCore Augmented Faces (which as far as I understand uses MediaPipe) doesn't exhibit this issue (leaving me thinking it's an issue with the sample).

Can provide screen shots if needed. I haven't modified the sample in any way. I'm using Xcode Version 11.6 (11E708).

**Comment by kapsyst** [comment]
Here are the examples. With the iOS Augmented Faces example you can clearly see the mouth and chin are lined up, and with the MediaPipe FaceMeshGpuApp example they are not.
The Augmented Faces example has been modified to display `canonical_face_texture.png` instead of the fox textures. 
![IMG_0471](https://user-images.githubusercontent.com/37162976/90580967-1730a800-e205-11ea-865b-ee1ef403f0ae.PNG)
![IMG_0470](https://user-images.githubusercontent.com/37162976/90581026-34657680-e205-11ea-9e7e-1fd4ce6a6c50.PNG)

**Comment by kapsyst** [comment]
![android_facemeshgpu](https://user-images.githubusercontent.com/37162976/90591743-d180d900-e21e-11ea-868b-90ca009a4412.jpg)
I have just tried the Android `facemeshgpu.apk`, and it appears to exhibit the same issues.

Is anyone able to help with why it does this? As the same problem occurs on both Android and iOS I'm starting to think that it's not an example application implementation issue.

**Comment by VenanEmre** [comment]
same problem

**Comment by VenanEmre** [comment]
@kapsyst , did you find a solution

**Comment by kapsyst** [comment]
@VenanEmre Sorry just saw your comment. Nothing yet, decided to go with GAR despite crashes and other issues.

**Comment by seghier** [comment]
Hello, i have the same problem with python and ths problem is because the script give points based on square 
to fix this we need to width, height of the image.
the point coordinate (x,y,z)
proportion = height/width
new y point = proportion * old y point
----
this work fine in python but i don't know about android or ios

**Comment by sgowroji** [comment]
Hi @seghier, Could you please test the above with the latest [facemesh](https://google.github.io/mediapipe/solutions/face_mesh#face-landmark-example) 
IOS build and let us know if you experience the same. Thanks!
