### ISSUE TITLE
Extract the landmarks of pose tracker in python

### ISSUE THREAD

**Issue by martiniblack** [google/mediapipe#1020]
I run the python interpreter of mediapipe for pose estimation by following https://google.github.io/mediapipe/solutions/pose.html#python

`pose_landmarks, annotated_image = pose_tracker.run(input_file='..')`

I can print the pose_landmarks and see the results:

```
landmark {
  x: 0.21143554151058197
  y: 0.38574913144111633
  z: -1.4804680859015207e-06
  visibility: 18.393444061279297
}
landmark {
  x: 0.17173771560192108
  y: 0.20884688198566437
  z: 1.4749808769920492e-06
  visibility: 18.401046752929688
}
landmark {
  x: 0.25402435660362244
  y: 0.47103995084762573
  z: -7.617963149186835e-09
  visibility: 5.351391315460205
}
landmark {
  x: 0.24858616292476654
  y: 0.46068453788757324
  z: -2.170341559804001e-07
  visibility: 6.021092891693115
}
landmark {
  x: 0.23653149604797363
  y: 0.528248131275177
  z: 9.051044913555018e-10
  visibility: 4.122689723968506
}
landmark {
  x: 0.22942595183849335
  y: 0.5136697888374329
  z: -8.629959324935044e-07
  visibility: 4.733832359313965
}
...
```

But the output of pose_landmarks is a <class 'mediapipe.framework.formats.landmark_pb2.NormalizedLandmarkList'>, I would like to use directly by converting it to a python list of dict but I don't know how.

Can anyone help me?
Many thanks.

**Comment by jiuqiant** [comment]
You can simply do the following to get each data point in the pose landmark list.
```
[
    print('x is', data_point.x, 'y is', data_point.y, 'z is', data_point.z)
    for data_point in pose_landmarks.landmark
]
```

Will update the pose tracker example to make the landmark data more accessible.

**Comment by jiuqiant** [comment]
You can simply do the following to get each data point in the pose landmark list.
```
[
    print('x is', data_point.x, 'y is', data_point.y, 'z is', data_point.z,
          'visibility is', data_point.visibility)
    for data_point in pose_landmarks.landmark
]
```

Will update the documentation to show how to retrieve the landmark data points from the landmark list.

**Comment by martiniblack** [comment]
jiuqiant, Thank you for your reply!
This works well I can define a list of dict with the idea
```
keypoints = []
for data_point in pose_landmarks.landmark:
    data_point.x
    keypoints.append({
                         'X': data_point.x,
                         'Y': data_point.y,
                         'Z': data_point.z,
                         'Visibility': data_point.visibility,
                         })
```

`[{'X': 0.22941510379314423, 'Y': 0.3362969160079956, 'Z': 0.00036452049971558154, 'Visibility': 7.158523082733154}, {'X': 0.2248845398426056, 'Y': 0.3288716673851013, 'Z': 0.0003398503758944571, 'Visibility': 6.53940486907959}, {'X': 0.22419394552707672, 'Y': 0.3290863037109375, 'Z': -0.0013778306310996413, 'Visibility': 6.5734052658081055}, {'X': 0.22357606887817383, 'Y': 0.3293464183807373, 'Z': 0.00047738433931954205, 'Visibility': 6.8802289962768555}, {'X': 0.22432096302509308, 'Y': 0.32969987392425537, 'Z': -0.0008961611310951412, 'Visibility': 7.292812824249268}, {'X': 0.22290897369384766, 'Y': 0.33005285263061523, 'Z': -0.00027306360425427556, 'Visibility': 8.049725532531738}, {'X': 0.22149835526943207, 'Y': 0.330348402261734, 'Z': 0.001738354447297752, 'Visibility': 8.718132019042969}, {'X': 0.21599923074245453, 'Y': 0.3352816104888916, 'Z': 0.0007447042153216898, 'Visibility': 8.168705940246582}, {'X': 0.2131650745868683, 'Y': 0.33602795004844666, 'Z': 0.0006085750064812601, 'Visibility': 9.590447425842285}, {'X': 0.22653266787528992, 'Y': 0.3470503091812134, 'Z': 6.458567077061161e-05, 'Visibility': 8.901251792907715}, {'X': 0.2251604050397873, 'Y': 0.34731805324554443, 'Z': 0.0018908820347860456, 'Visibility': 9.572975158691406}, {'X': 0.22312860190868378, 'Y': 0.37499237060546875, 'Z': 0.015017705969512463, 'Visibility': 8.1065034866333}, {'X': 0.20063789188861847, 'Y': 0.39548638463020325, 'Z': -0.018212972208857536, 'Visibility': 8.205290794372559}, {'X': 0.23315922915935516, 'Y': 0.42901355028152466, 'Z': 0.006132934708148241, 'Visibility': 6.994071960449219}, {'X': 0.20903190970420837, 'Y': 0.4670613706111908, 'Z': 0.006986796855926514, 'Visibility': 4.814481735229492}, {'X': 0.24870403110980988, 'Y': 0.4606689512729645, 'Z': 0.03467315435409546, 'Visibility': 5.79559850692749}, {'X': 0.229664146900177, 'Y': 0.5150744915008545, 'Z': -0.002222581999376416, 'Visibility': 4.5876665115356445}, {'X': 0.2553863525390625, 'Y': 0.4712091386318207, 'Z': -0.0012559948954731226, 'Visibility': 5.036598205566406}, {'X': 0.23253664374351501, 'Y': 0.5335666537284851, 'Z': -0.0008883491391316056, 'Visibility': 3.8042361736297607}, {'X': 0.25375494360923767, 'Y': 0.47055649757385254, 'Z': -0.0018278396455571055, 'Visibility': 5.04033899307251}, {'X': 0.23877401649951935, 'Y': 0.527604877948761, 'Z': 0.0008347983239218593, 'Visibility': 4.038757801055908}, {'X': 0.2510611116886139, 'Y': 0.46950027346611023, 'Z': 0.00031364907044917345, 'Visibility': 5.325376510620117}, {'X': 0.23850774765014648, 'Y': 0.5219038128852844, 'Z': -0.0004820673493668437, 'Visibility': 4.279197692871094}, {'X': 0.24704612791538239, 'Y': 0.49019908905029297, 'Z': 0.08008850365877151, 'Visibility': 6.993941307067871}, {'X': 0.2289113998413086, 'Y': 0.5110218524932861, 'Z': 0.02991626411676407, 'Visibility': 6.03526496887207}, {'X': 0.21143554151058197, 'Y': 0.38574913144111633, 'Z': -1.4804680859015207e-06, 'Visibility': 18.393444061279297}, {'X': 0.17173771560192108, 'Y': 0.20884688198566437, 'Z': 1.4749808769920492e-06, 'Visibility': 18.401046752929688}, {'X': 0.25402435660362244, 'Y': 0.47103995084762573, 'Z': -7.617963149186835e-09, 'Visibility': 5.351391315460205}, {'X': 0.24858616292476654, 'Y': 0.46068453788757324, 'Z': -2.170341559804001e-07, 'Visibility': 6.021092891693115}, {'X': 0.23653149604797363, 'Y': 0.528248131275177, 'Z': 9.051044913555018e-10, 'Visibility': 4.122689723968506}, {'X': 0.22942595183849335, 'Y': 0.5136697888374329, 'Z': -8.629959324935044e-07, 'Visibility': 4.733832359313965}]
`
In the same time, I found another way by using protobuf_to_dict library :
```
from protobuf_to_dict import protobuf_to_dict
...
keypoints = protobuf_to_dict(pose_landmarks)
```
it gives a similar result:

`{'landmark': [{'x': 0.22941510379314423, 'y': 0.3362969160079956, 'z': 0.00036452049971558154, 'visibility': 7.158523082733154}, {'x': 0.2248845398426056, 'y': 0.3288716673851013, 'z': 0.0003398503758944571, 'visibility': 6.53940486907959}, {'x': 0.22419394552707672, 'y': 0.3290863037109375, 'z': -0.0013778306310996413, 'visibility': 6.5734052658081055}, {'x': 0.22357606887817383, 'y': 0.3293464183807373, 'z': 0.00047738433931954205, 'visibility': 6.8802289962768555}, {'x': 0.22432096302509308, 'y': 0.32969987392425537, 'z': -0.0008961611310951412, 'visibility': 7.292812824249268}, {'x': 0.22290897369384766, 'y': 0.33005285263061523, 'z': -0.00027306360425427556, 'visibility': 8.049725532531738}, {'x': 0.22149835526943207, 'y': 0.330348402261734, 'z': 0.001738354447297752, 'visibility': 8.718132019042969}, {'x': 0.21599923074245453, 'y': 0.3352816104888916, 'z': 0.0007447042153216898, 'visibility': 8.168705940246582}, {'x': 0.2131650745868683, 'y': 0.33602795004844666, 'z': 0.0006085750064812601, 'visibility': 9.590447425842285}, {'x': 0.22653266787528992, 'y': 0.3470503091812134, 'z': 6.458567077061161e-05, 'visibility': 8.901251792907715}, {'x': 0.2251604050397873, 'y': 0.34731805324554443, 'z': 0.0018908820347860456, 'visibility': 9.572975158691406}, {'x': 0.22312860190868378, 'y': 0.37499237060546875, 'z': 0.015017705969512463, 'visibility': 8.1065034866333}, {'x': 0.20063789188861847, 'y': 0.39548638463020325, 'z': -0.018212972208857536, 'visibility': 8.205290794372559}, {'x': 0.23315922915935516, 'y': 0.42901355028152466, 'z': 0.006132934708148241, 'visibility': 6.994071960449219}, {'x': 0.20903190970420837, 'y': 0.4670613706111908, 'z': 0.006986796855926514, 'visibility': 4.814481735229492}, {'x': 0.24870403110980988, 'y': 0.4606689512729645, 'z': 0.03467315435409546, 'visibility': 5.79559850692749}, {'x': 0.229664146900177, 'y': 0.5150744915008545, 'z': -0.002222581999376416, 'visibility': 4.5876665115356445}, {'x': 0.2553863525390625, 'y': 0.4712091386318207, 'z': -0.0012559948954731226, 'visibility': 5.036598205566406}, {'x': 0.23253664374351501, 'y': 0.5335666537284851, 'z': -0.0008883491391316056, 'visibility': 3.8042361736297607}, {'x': 0.25375494360923767, 'y': 0.47055649757385254, 'z': -0.0018278396455571055, 'visibility': 5.04033899307251}, {'x': 0.23877401649951935, 'y': 0.527604877948761, 'z': 0.0008347983239218593, 'visibility': 4.038757801055908}, {'x': 0.2510611116886139, 'y': 0.46950027346611023, 'z': 0.00031364907044917345, 'visibility': 5.325376510620117}, {'x': 0.23850774765014648, 'y': 0.5219038128852844, 'z': -0.0004820673493668437, 'visibility': 4.279197692871094}, {'x': 0.24704612791538239, 'y': 0.49019908905029297, 'z': 0.08008850365877151, 'visibility': 6.993941307067871}, {'x': 0.2289113998413086, 'y': 0.5110218524932861, 'z': 0.02991626411676407, 'visibility': 6.03526496887207}, {'x': 0.21143554151058197, 'y': 0.38574913144111633, 'z': -1.4804680859015207e-06, 'visibility': 18.393444061279297}, {'x': 0.17173771560192108, 'y': 0.20884688198566437, 'z': 1.4749808769920492e-06, 'visibility': 18.401046752929688}, {'x': 0.25402435660362244, 'y': 0.47103995084762573, 'z': -7.617963149186835e-09, 'visibility': 5.351391315460205}, {'x': 0.24858616292476654, 'y': 0.46068453788757324, 'z': -2.170341559804001e-07, 'visibility': 6.021092891693115}, {'x': 0.23653149604797363, 'y': 0.528248131275177, 'z': 9.051044913555018e-10, 'visibility': 4.122689723968506}, {'x': 0.22942595183849335, 'y': 0.5136697888374329, 'z': -8.629959324935044e-07, 'visibility': 4.733832359313965}]}`

**Comment by jiuqiant** [comment]
Glad to see that you are able to use those data points.

**Comment by JayantGoel001** [comment]
> You can simply do the following to get each data point in the pose landmark list.
> 
> ```
> [
>     print('x is', data_point.x, 'y is', data_point.y, 'z is', data_point.z,
>           'visibility is', data_point.visibility)
>     for data_point in pose_landmarks.landmark
> ]
> ```
> 
> Will update the documentation to show how to retrieve the landmark data points from the landmark list.

Hello @jiuqiant ,
Can You tell how to convert list of dictionary to NormalizedLandmarklist?

**Comment by Ambroza888** [comment]
```
       try:
            landmarks = result.pose_landmarks.landmark
            print(landmarks)
            tog.isLeft = True
        except:
            pass
```

**Comment by sparshgarg23** [comment]
@martiniblack  thanks for the protobuf_to_dict suggestion,it's really helpful

**Comment by paul-shuvo** [comment]
> ```
> keypoints = protobuf_to_dict(pose_landmarks)
> ```

If you come across [Use of long causes issues with newer python versions](Use of long causes issues with newer python versions), refer to this [comment](https://github.com/benhodgson/protobuf-to-dict/issues/15#issuecomment-368152202)

**Comment by nisarnabeel** [comment]
how to convert lets say from dict or array back tomediapipe.framework.formats.landmark_pb2.NormalizedLandmark
