### ISSUE TITLE
ios framework so large

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#1021]
Used this command `bazel build --config=ios_fat --copt=-fembed-bitcode mediapipe/examples/ios/frameworks:HedEdgeDetection_Framework --linkopt="-s"` to build ios dynamic framework but so large than android, It has around 60M. 
![image](https://user-images.githubusercontent.com/17869361/90584043-3f6bd700-e204-11ea-85ee-98ed8b754781.png)
![image](https://user-images.githubusercontent.com/17869361/90584044-40046d80-e204-11ea-9379-cd7ab71c54a9.png)
How to reduce the framework size? 

```
MIN_IOS_VERSION = "10.0"

load("@build_bazel_rules_apple//apple:ios.bzl", "ios_framework")

objc_library(
    name = "HedEdgeDetectionLibrary",
    visibility = ["//visibility:public"],
    srcs = ["CameraApi.mm", "HedEdgeDetectApi.mm", "MMOpenCVHelper.mm", "UIImage+PictureOrientation.m"],
    hdrs = ["CameraApi.h", "HedEdgeDetectApi.h", "MMOpenCVHelper.h", "UIImage+PictureOrientation.h"],
    data = [
        "//mediapipe/graphs/hed_edge_detection:mobile_gpu_binary_graph",
        "//mediapipe/models:hed_graph.tflite",
    ],
    sdk_frameworks = [
        "AVFoundation",
        "CoreGraphics",
        "CoreMedia",
        "UIKit",
    ],
    deps = [
        "//mediapipe/objc:mediapipe_framework_ios",
        "//mediapipe/objc:mediapipe_input_sources_ios",
        "//mediapipe/objc:mediapipe_layer_renderer",
        "//mediapipe/inference:hed_edge_detection",
    ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            "//mediapipe/graphs/hed_edge_detection:mobile_calculators",
        ],
    }),
)

# bazel build --config=ios_fat --copt=-fembed-bitcode mediapipe/examples/ios/frameworks:HedEdgeDetect --linkopt="-s"
ios_framework(
    name = "HedEdgeDetect",
    # If `hdrs` isn't set Headers and Modules folders won't get generated
    hdrs = ["CameraApi.h", "HedEdgeDetectApi.h", "UIImage+PictureOrientation.h"],
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = ["info.plist"],
    bundle_id = "com.ctsmed.edgedetection",
    minimum_os_version = MIN_IOS_VERSION,
    deps = [
        "@ios_opencv//:OpencvFramework",
        "HedEdgeDetectionLibrary"
    ]
)
```

**Comment by weinixuehao** [comment]
It will be more than 200 megabytes in size if add --apple_bitcode=embedded

**Comment by sgowroji** [comment]
Hi @weinixuehao, Could you please test the above with the latest release in IOS and let us know if you still have any queries on it. Thanks!

**Comment by skydragon1115** [comment]
Hi, I am using mediapipe(20210914).

When I build without ```--apple_bitcode=embedded```, the size of the framework is 15MB.
bazel build --copt=-fembed-bitcode --config=ios_fat mediapipe/examples/ios/selfiesegmentaion:SelfieSegmentation --linkopt="-s"

But if I add ```--apple_bitcode=embedded```, the size is 200MB.
bazel build --copt=-fembed-bitcode --config=ios_arm64 --apple_bitcode=embedded mediapipe/examples/ios/selfiesegmentation:SelfieSegmentation --linkopt="-s"

How to reduce the framework size?
