### ISSUE TITLE
Will the lower body model be released?

### ISSUE THREAD

**Issue by Source666** [google/mediapipe#1022]
In the current BlazePose, only the upper body model is seen. Is there any plan to release the lower body or full body model? If so, when will it be?

**Comment by mgyong** [comment]
We currently have not confirmed if we will release the lower body model. However, you can apply for access to full body model = upper + lower using Android MLKit EAP program. Apply here https://developers.google.com/ml-kit/early-access/pose-detection

**Comment by Source666** [comment]
> We currently have not confirmed if we will release the lower body model. However, you can apply for access to full body model = upper + lower using Android MLKit EAP program. Apply here https://developers.google.com/ml-kit/early-access/pose-detection

Thanks
