### ISSUE TITLE
BlazePose point count

### ISSUE THREAD

**Issue by ljmkimqx** [google/mediapipe#1024]
When I use BlazePose, the number of points I recognize is 31, but the number of points in the web page "https://google.github.io/mediapipe/solutions/pose" is 25. Why is this?

And what does "New timestamp is equal or less than the last one" mean? Can you not prompt this content in the log, because the number of times this prompt is too many.(iOS)

**Comment by heybai** [comment]
As for the first part of your question. Last 6 points are technical and are used to get accurate pose crop from the previous frame for the next one. Normally you don't want to use them.

**Comment by ljmkimqx** [comment]
Thank!
