### ISSUE TITLE
desktop hand tracking example does not work. 

### ISSUE THREAD

**Issue by CassieHo-98** [google/mediapipe#1028]
When I give these two commands

bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu 

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt --input_video_path=/disk2/data/rgb1.mp4

I got the following output:
I20200820 13:10:49.676206 14951 demo_run_graph_main.cc:53] Initialize the calculator graph.
I20200820 13:10:49.681268 14951 demo_run_graph_main.cc:57] Initialize the camera or load the video.
E20200820 13:10:49.782353 14951 demo_run_graph_main.cc:146] Failed to run the graph: ; capture.isOpened()(mediapipe/examples/desktop/demo_run_graph_main.cc:65)

seems that the video cannot be loaded.

I have checked the opencv and ffmpeg library, they are both well installed.
And I have also modified the project configurations to point Mediapipe to the right path following the official instructions.
But there is still always this problem. I feel very confused...

And I modified the demo_run_graph_main.cc file to print something for testing, after rebuild and run, the output didn't change, was always remaining the same. So I am wondering whether the project didn't build properly?

**Comment by CassieHo-98** [comment]
when I build the project, it had the following output:

root@0f7754199d8e:/mediapipe# bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu                                                              WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "2a34fa56d923f774409d23720e60ddf6536e88622d000e6925f7cebbad65e281"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /mediapipe/WORKSPACE:33:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/5cb16e7ace0fcdcab164af01620a606ba828a3be.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/Maratyszcza/FP16/archive/3c54eacb74f6f5e39077300c5564156c424d77ba.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu up-to-date:
  bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu
INFO: Elapsed time: 0.301s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

**Comment by Amearul** [comment]
Pada Kha, 20 Ogo 2020 pada pukul 9:28 PTG, Cassie <notifications@github.com>
menulis:

**Comment by jiuqiant** [comment]
"E20200820 13:10:49.782353 14951 demo_run_graph_main.cc:146] Failed to run the graph: ; capture.isOpened()" means opencv's video capture can't open your video file. See the source code at https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/examples/desktop/demo_run_graph_main.cc#L61.

I think your MediaPipe OpenCV configuration is correct. Otherwise, you should see undefined opencv symbols when you compile it. Feel like the current issue is more about your local opencv library. Maybe you can use it without MediaPipe first to see if it can load the video file or not?

**Comment by dgrnd4** [comment]
@CassieHo-98 hi, how did you solve it? i am having the same equal problem!!!!

**Comment by dgrnd4** [comment]
@Amearul @jiuqiant  are you able to give me an advice as solution?
Many thanks, i am stuck on it

**Comment by WangXuan2401** [comment]
Well，I met the same problem when running hand_tracking_cpu on Linux server. And I found that the “Load Error” is mainly because the incompletence of the command.

I solved the problem successfully by using the commands below:

for building the project
```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
```

for running the hand_tracking_cpu demo 
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt --input_video_path=/home/3DHandReconstruction1/Mediapipe/mediapipe/mediapipe/examples/desktop/start.mp4 --output_video_path=/home/3DHandReconstruction1/Mediapipe/mediapipe/mediapipe/examples/desktop/result/annotated.mp4
```

Please make sure that the **'--output_video_path'** is with given **'file_name.mp4'** at the end.

**Comment by Eliastoomme** [comment]
Hi, I have followed your steps and managed to build it successfully, but when running, I'm getting the following error:
I20230507 18:03:34.086709  4586 demo_run_graph_main.cc:54] Initialize the calculator graph.
E20230507 18:03:34.088487  4586 demo_run_graph_main.cc:154] Failed to run the graph: ValidatedGraphConfig Initialization failed.
No registered object with name: RendererSubgraph; Unable to find Calculator "RendererSubgraph"

any ideas?
