### ISSUE TITLE
Doc for iris

### ISSUE THREAD

**Issue by sgu-fai** [google/mediapipe#1032]
Hello,

I have run the example of iris depth on my iPhone. I would like to try to integrate it in my swift project.
I am already using a pose estimation model so the interpreter is set up for that model
 but I can't find any documentation how to integrate/use the model: 
-how to set up tf interpreter, input, output,...

**Comment by shortcipher3** [comment]
I have modified [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/python/label_image.py) example to work with the iris landmarks tflite model.  To use iOS/Swift you probably could start with one of these examples for iOS:
* [simple](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/ios/simple)
* [camera](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/ios/camera)

However the output I'm getting doesn't match the [model card](https://mediapipe.page.link/iris-mc), so you would still need to interpret the results correctly.

Good luck integrating with your app!

**Comment by sgowroji** [comment]
Hi @sgu-fai, Now we have a clear documentation on IOS and IRIS solution. Please go through it and let us know and reopen, if you still looking for any relevant query. Thanks!
