### ISSUE TITLE
Integrating glog 0.4.0 with wasm

### ISSUE THREAD

**Issue by prantoran** [google/mediapipe#1036]
I tried building and integrating [GLog](https://github.com/google/glog) [v0.4.0](https://github.com/google/glog/releases/tag/v0.4.0) release using `third_party/glog.BUILD` but unable to do so. Specifically, I am stuck at the command `cmd = "$(location :configure)"`. I guess the GLog version used in MediaPipe is [`v0.3.5`](https://github.com/google/glog/releases/tag/v0.3.5). The GLog version `v.0.4.0` solves some issues regarding imports.

**Comment by jiuqiant** [comment]
MediaPipe supports glog 0.4.0 on desktop platforms (linux, macos, and Windows) and is on glog 0.3.5 on Android and iOS. Which platform are you targeting to? Do you meet any problem of using glog 0.3.5 with MediaPipe?

**Comment by prantoran** [comment]
Okay, I guess glog 0.4.0 for desktop platforms are defined in `third_party/BUILD`. I was trying to build with `-cpu=wasm` in `.bazelrc` and use bazel toolchain config similar to that in TensorflowJS, but then I got some errors related to `syscall` and `SYS_gettid`.

I am trying to make a web version of the Multihand desktop example for online user studies  for an university project and collect various usage metrics.

**Comment by jiuqiant** [comment]
In the MediaPipe glog build rule (https://github.com/google/mediapipe/blob/master/third_party/BUILD#L22), only Android and iOS will hit glog 0.3.5. By default (L50), you will use glog 0.4.0. Can you confirm which version of glog you use?

**Comment by prantoran** [comment]
I got an idea, I will try setting the following in `third_party/BUILD` and see what happens: 
```
        "//mediapipe:wasm": [
            "@com_github_glog_glog//:glog",
        ],
```

I guess if an entry is not found in here then bazel uses glog 0.3.5 by default.

**Comment by prantoran** [comment]
In the following section of `third_party/BUILD`,
```

cc_library(
    name = "glog",
    visibility = ["//visibility:public"],
    deps = select({
     ...
```
I added the following:
```
        "//mediapipe:wasm": [
            "@com_github_glog_glog//:glog",
        ],
```

And in `mediapipe/BUILD`, I added the folling config setting:
```

config_setting(
    name = "wasm",
    values = {"cpu": "wasm"},
    visibility = ["//visibility:public"],
)
```

Then I ran the build:
```
bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11   mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu --config=wasm
```

And then got this error, I am gussing it is using glog0.3.5:

```
.cache/bazel/_bazel_prantoran/61d351cebd958c62bdd749dd8160658a/external/com_github_glog_glog/BUILD:5:13: C++ compilation of rule '@com_github_glog_glog//:glog' failed (Exit 1)
external/com_github_glog_glog/src/raw_logging.cc:139:3: error: use of undeclared identifier 'syscall'
  safe_write(STDERR_FILENO, buffer, strlen(buffer));
  ^
external/com_github_glog_glog/src/raw_logging.cc:63:34: note: expanded from macro 'safe_write'
# define safe_write(fd, s, len)  syscall(SYS_write, fd, s, len)
```

Btw the desktop version works, I am trying to target wasm as cpu.

**Comment by jiuqiant** [comment]
Unfortunately, MediaPipe wasm support is not released and we don't have a concrete plan for that.
I feel sorry that I don't have a good answer for you.

**Comment by prantoran** [comment]
No worries, my project is also using the desktop version. I did learn a good deal about Bazel setup and Webassembly, so it is a win.

**Comment by langhuihui** [comment]
@prantoran  I got an error when I build examples
`
bazel-out/wasm-opt/bin/external/com_github_glog_glog_no_gflags/_virtual_includes/glog/glog/platform.h:55:2: error: Platform not supported by glog. Please consider to contribute platform information by submitting a pull request on Github.
`

then I use `#define GLOG_OS_LINUX` 

I got `external/com_github_glog_glog/src/utilities.cc:267:2: error: "Must define __NR_gettid for non-x86 platforms"`

**Comment by prantoran** [comment]
@langhuihui Not sure, I have not seen the errors before.  Can you try experimenting with adding a platform selection here: https://github.com/google/mediapipe/blob/master/third_party/BUILD#L28-L57

**Comment by langhuihui** [comment]
I add following to the `/home/vscode/.cache/bazel/_bazel_vscode/3e0f1b658d37cb6e3ab8049c737ca188/external/com_github_glog_glog/src/utilities.cc` to solve the problem.
```
#ifdef __EMSCRIPTEN__
pid_t GetTID() {
  return -1;
}
#else
pid_t GetTID() {
...

#endif
```

**Comment by langhuihui** [comment]
@prantoran another problem  `graph.StartRun({})` will block js main thread. How do you use it.

**Comment by prantoran** [comment]
@langhuihui I think MP runs on a single thread per graph instance, so probably starting the graph in a worker thread might be a solution.

But I think I did not use any workers, so probably I tweaked the Emscripten linkopts here: https://github.com/prantoran/mediapipe/blob/latest_wasm/hello-world/BUILD#L15-L23

**Comment by langhuihui** [comment]
@prantoran I find out that `poller.Next(&packet)` (which in PrintHelloWorld ) cause block not `graph.StartRun({})`

**Comment by prantoran** [comment]
I checked that the [patch](https://github.com/google/glog/pull/846) for this error was merged in the release [google-glog v0.6.0](https://github.com/google/glog/releases/tag/v0.6.0) which is used in the [workspace](https://github.com/google/mediapipe/blob/master/WORKSPACE#L155-L169). I added a similar config selection mentioned earlier in this issue and got the same error, so I think I am missing something.

**Comment by Algomorph** [comment]
It works out if you use glog 0.7.0 (which has emscripten support).
In my `mediapipe/BUILD`:
```Starlark
# at the top:
load("@bazel_skylib//lib:selects.bzl", "selects")

# other stuff...

# Emscripten.
config_setting(
    name = "emscripten",
    values = {"crosstool_top": "@emsdk//emscripten_toolchain:everything"},
)

# Emscripten + WASM.
config_setting(
    name = "emscripten_wasm",
    values = {
        "crosstool_top": "@emsdk//emscripten_toolchain:everything",
        "cpu": "wasm",
    },
)

# Emscripten + WASM w/ SIMD support.
config_setting(
    name = "emscripten_wasm_simd",
    values = {
        "crosstool_top": "@emsdk//emscripten_toolchain:everything",
        "cpu": "wasm",
        "copt": "-msimd128",
    },
)
# ...
```

In my `WORKSPACE`:
```Starlark
# ...
# 2020-08-21 -- this is the default version in MP 0.10.11
http_archive(
    name = "com_github_glog_glog",
    sha256 = "8a83bf982f37bb70825df71a9709fa90ea9f4447fb3c099e1d720a439d88bad6",
    strip_prefix = "glog-0.6.0",
    urls = [
        "https://github.com/google/glog/archive/v0.6.0.tar.gz",
    ],
)

# 2024-02-17 -- the new version, just for emscripten (playing it safe)
http_archive(
    name = "com_github_glog_glog_emscripten",
    sha256 = "375106b5976231b92e66879c1a92ce062923b9ae573c42b56ba28b112ee4cc11",
    strip_prefix = "glog-0.7.0",
    urls = [
        "https://github.com/google/glog/archive/v0.7.0.tar.gz",
    ],
)

# other... stuff...
http_archive(
    name = "com_github_glog_glog_no_gflags",
    build_file = "@//third_party:glog_no_gflags.BUILD",
```

Finally, in my `third_party/BUILD`, the modified `glog`:
```Starlark
cc_library(
    name = "glog",
    visibility = ["//visibility:public"],
    deps = select({
        "//mediapipe:android_x86": [
            "@com_github_glog_glog_no_gflags//:glog",
        ],
        "//mediapipe:android_x86_64": [
            "@com_github_glog_glog_no_gflags//:glog",
        ],
        "//mediapipe:android_armeabi": [
            "@com_github_glog_glog_no_gflags//:glog",
        ],
        "//mediapipe:android_arm": [
            "@com_github_glog_glog_no_gflags//:glog",
        ],
        "//mediapipe:android_arm64": [
            "@com_github_glog_glog_no_gflags//:glog",
        ],
        "//mediapipe:ios": [
            "@com_github_glog_glog_no_gflags//:glog",
        ],
        "//mediapipe:macos": [
            "@com_github_glog_glog//:glog",
        ],
        "//mediapipe:windows": [
            "@com_github_glog_glog//:glog",
        ],
        "//conditions:default": [
            "@com_github_glog_glog//:glog",
        ],
    }),
)
```

**Comment by Algomorph** [comment]
P.S. ended up using a patch after all to fix the `GetTID` issue, but a bit differently. There was also a minor thing with the output of `write`, the patch covers it.
[com_github_glog_glog_emscripten_gettid_and_write_fix.diff.txt](https://github.com/google/mediapipe/files/15067401/com_github_glog_glog_emscripten_gettid_and_write_fix.diff.txt)
