### ISSUE TITLE
How can I find the size of the iris with iris tracking?

### ISSUE THREAD

**Issue by s8sun** [google/mediapipe#1037]
The input will be a video, I'm currently digging into the source codes but it's hard to find what I'm looking for.
I wanted the output to be the size of the iris(pixel or mm), and the position (x,y) of the iris.

Any ideas? Thoughts are appreciated.

**Comment by mcclanahoochie** [comment]
I would start by reviewing what happens in the renderer graph, specifically the [IrisToDepthCalculator](https://github.com/google/mediapipe/blob/2f86a459b6f255018536a6d7b708e352bbc65d0c/mediapipe/graphs/iris_tracking/subgraphs/iris_and_depth_renderer_gpu.pbtxt#L220) and [IrisToRenderDataCalculator](https://github.com/google/mediapipe/blob/2f86a459b6f255018536a6d7b708e352bbc65d0c/mediapipe/graphs/iris_tracking/subgraphs/iris_and_depth_renderer_gpu.pbtxt#L229)
and how the blue oval and green landmarks colors are drawn (which come from the "iris_landmarks" stream).

**Comment by nitin26gupta** [comment]
was looking for this, thanks for you answer.
However, how do i see the values of these points and where could i see that. Sorry id haven't worked with such a graph before .

**Comment by fahadhaq** [comment]
@nitin26gupta were you able to figure out how to get the size and the position?

**Comment by sgowroji** [comment]
The above [resolution](https://github.com/google/mediapipe/issues/1037#issuecomment-679438287) resolved this query. We are closing this issue now.
