### ISSUE TITLE
[pose_tracking]   Compilation fails on ubuntu

### ISSUE THREAD

**Issue by chenti2x** [google/mediapipe#1038]
compile command:
bazel build -c dbg mediapipe/examples/desktop/upper_body_pose_tracking:upper_body_pose_tracking_gpu -
-copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11

problems:
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:41:15: error: expected unqualified-id before '[' token
   const auto& [lm_min_x, lm_max_x] = absl::c_minmax_element(
               ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:41:15: error: expected initializer before '[' token
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:43:65: error: expected primary-expression before ')' token
       [](const auto& a, const auto& b) { return a.x() < b.x(); });
                                                                 ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:44:23: error: 'lm_min_x' was not declared in this scope
   const float x_min = lm_min_x->x();
                       ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:45:23: error: 'lm_max_x' was not declared in this scope
   const float x_max = lm_max_x->x();
                       ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:47:15: error: expected unqualified-id before '[' token
   const auto& [lm_min_y, lm_max_y] = absl::c_minmax_element(
               ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:47:15: error: expected initializer before '[' token
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:49:65: error: expected primary-expression before ')' token
       [](const auto& a, const auto& b) { return a.y() < b.y(); });
                                                                 ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:50:23: error: 'lm_min_y' was not declared in this scope
   const float y_min = lm_min_y->y();
                       ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:51:23: error: 'lm_max_y' was not declared in this scope
   const float y_max = lm_max_y->y();

**Comment by sourabh03agr** [comment]
What was the resolution on this? Facing the same error

**Comment by chenti2x** [comment]
I change a compute, the problem disappear. So I don't know the reason.
