### ISSUE TITLE
[Exynos/Mali] Hand tracking apk crashes right after launching it.

### ISSUE THREAD

**Issue by tmnbhat** [google/mediapipe#104]
Both the regular and 3d versions of the hand tracking apk seem to be crashing on my phone. (Galaxy S10 - exynos 9910 processor).
Haven't built the app myself yet but seems like it might be specific to my phone model.

**Comment by mgyong** [comment]
Same as #41 
Closing here as TF bug

**Comment by chuoling** [comment]
We (MediaPipe) will follow up with TensorFlow team and provide an update in #41.

**Comment by mgyong** [comment]
@JimWest @tmnbhat @yurymalkov Fixed bug in [v0.6.5 release](https://github.com/google/mediapipe/releases/tag/v0.6.5) Can you guys checkout the v0.6.5 release and try?

**Comment by JimWest** [comment]
> @JimWest @tmnbhat @yurymalkov Fixed bug in [v0.6.5 release](https://github.com/google/mediapipe/releases/tag/v0.6.5) Can you guys checkout the v0.6.5 release and try?

@mgyong Yes, I can confirm that it's working now withouth crashing for me.

**Comment by tmnbhat** [comment]
> @JimWest @tmnbhat @yurymalkov Fixed bug in [v0.6.5 release](https://github.com/google/mediapipe/releases/tag/v0.6.5) Can you guys checkout the v0.6.5 release and try?

Works now. Thanks! Might want to update the apk in the google drive link though.

**Comment by krullgit** [comment]
For the Samsung S20+ with Mali-G77 MP11 it is not working :(
