### ISSUE TITLE
package deps into bzl files

### ISSUE THREAD

**Issue by rrtaylor** [google/mediapipe#1047]
I would like to create a new project that references google/mediapipe as a third party dependency through bazel's `git_repository` function. Currently, I will have to copy all of mediapipe's dependencies in its WORKSPACE to accomplish this, which is a lot of copying. Is there anything preventing there to be a deps bzl file that could encapsulate this work like is done for [protobuf](https://github.com/protocolbuffers/protobuf/blob/a104dffcb6b1958a424f5fa6f9e6bdc0ab9b6f9e/protobuf_deps.bzl)?

**Comment by sgowroji** [comment]
Hi @rrtaylor, Could you please respond, Whether  your looking answer to the above query. Thanks!
