### ISSUE TITLE
How to fill colour inside the landmark points from FaceMesh? 

### ISSUE THREAD

**Issue by LarryBrinzo** [google/mediapipe#1049]
I am using the face_renderer_gpu graph. It draws an annotation of all the landmark points and connections of those points. How can we fill a colour inside a landmark region? Like if I want to fill the colours inside the lips points (applying lipstick).

**Comment by fenollp** [comment]
Replying to Ansh Gupta as well as others:
The quickest (albeit less pretty) way I think would be to
1. create a `LipsToRenderDataCalculator` similar to https://github.com/google/mediapipe/blob/a7225b938a5aff536dcdc4d48d7125964480f413/mediapipe/calculators/util/landmarks_to_render_data_calculator.cc that does not create `RenderAnnotation::GradientLine` but instead a polygon (let's call it `RenderAnnotation::FilledConvexPolygon`) that comprises only the landmarks for the lips
1. then adapt https://github.com/google/mediapipe/blob/a7225b938a5aff536dcdc4d48d7125964480f413/mediapipe/util/annotation_renderer.cc to add our `RenderAnnotation::FilledConvexPolygon` (and to the .proto as well) by introducing `void AnnotationRenderer::FilledConvexPolygon(const RenderAnnotation& annotation);` which would call [https://docs.opencv.org/2.4/modules/core/doc/drawing_functions.html#fillconvexpoly](fillConvexPoly) and handling our proto enum value in `void AnnotationRenderer::RenderDataOnImage(const RenderData& render_data);`
1. finally, in your version of https://github.com/google/mediapipe/blob/a7225b938a5aff536dcdc4d48d7125964480f413/mediapipe/graphs/face_mesh/subgraphs/face_renderer_gpu.pbtxt replace the `LandmarksToRenderDataCalculator` by your `LipsToRenderDataCalculator` 

This solution does not perform any shading however, but that's a start :)

**Comment by LarryBrinzo** [comment]
Thank you so much for your input.

**Comment by fenollp** [comment]
So I just took a look at the hair-colouring example (as its effect is quite stunning) and I believe it is a much better approach:
* it uses a segmentation mask as input (one can probably be constructed from the facial landmarks)
* it blends the original image's luminance with the colouring color

I invite you to take a look at it https://github.com/google/mediapipe/blob/c0124fb83c667917c7bf6a84f442a0136e8f2cf7/mediapipe/calculators/image/recolor_calculator.cc
and the way it is used https://github.com/google/mediapipe/blob/c0124fb83c667917c7bf6a84f442a0136e8f2cf7/mediapipe/graphs/hair_segmentation/hair_segmentation_desktop_live.pbtxt#L142

**Comment by LarryBrinzo** [comment]
Thank you so much. I am not sure how we can create a masked image from landmark points. OpenGL is new tech for me. Are we trying to create a canvas? Found this Google's paper for Virtual Lipstick (How they are rendering the overlay). https://drive.google.com/file/d/1ErUPg3-kOSFymZx_XmGwJFhRqKseDuzO/view

**Comment by Nvelu048** [comment]
Hi how to extract Lips connection from landmark connection

**Comment by LarryBrinzo** [comment]
You can just include the lips connection from all of the landmark connection vector. 

Can take help from this: 

- UV coordinate visualization (https://github.com/tensorflow/tfjs-models/blob/master/facemesh/mesh_map.jpg)
- Contour keypoints (https://github.com/tensorflow/tfjs-models/blob/master/facemesh/src/keypoints.ts)

**Comment by Nvelu048** [comment]
@LarryBrinzo, 

I have updated [LandMarkRenderer](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/landmarks_to_render_data_calculator.cc) to 

`
     std::vector<int> lipsOuter{
        // lipsUpperOuter
        61, 185, 40, 39, 37, 0, 267, 269, 270, 409, 291,
        // lipsLowerOuter in reverse order
        375, 321, 405, 314, 17, 84, 181, 91, 146, 61
    };
    
    std::vector<int> lipsInner{
        // lipsUpperInner
        78, 191, 80, 81, 82, 13, 312, 311, 310, 415, 308,
        // lipsLowerOuter in reverse order
        324, 318, 402, 317, 14, 87, 178, 88, 95, 78
    };
    
    for(int i=0;i<lipsInner.size()-1;i++){
        const auto& ld0 = landmarks.landmark(lipsInner[i]);
        const auto& ld1 = landmarks.landmark(lipsInner[i + 1]);
        if (utilize_visibility && (ld0.visibility() < visibility_threshold ||
                                   ld1.visibility() < visibility_threshold)) {
            continue;
        }
        AddConnectionToRenderData<LandmarkType>(ld0, ld1, connection_color,
                                                thickness, normalized, render_data);
    }
    for(int i=0;i<lipsOuter.size()-1;i++){
        const auto& ld0 = landmarks.landmark(lipsOuter[i]);
        const auto& ld1 = landmarks.landmark(lipsOuter[i + 1]);
        if (utilize_visibility && (ld0.visibility() < visibility_threshold ||
                                   ld1.visibility() < visibility_threshold)) {
            continue;
        }
        AddConnectionToRenderData<LandmarkType>(ld0, ld1, connection_color,
                                                thickness, normalized, render_data);
    }`

and able to achieve expected result.  

Thanks for the support

**Comment by Nvelu048** [comment]
@LarryBrinzo 

Have you figured out how to create masked image using OpenGL

**Comment by milad-4274** [comment]
did anyone write calculator for creating mask from landmarks? any guide?

**Comment by sgowroji** [comment]
Hi @LarryBrinzo and others, Could you please respond if you are looking answer for the above query still and  let us know if you have any observations. Thanks!

**Comment by milad-4274** [comment]
I wrote custom calculator to generate binary mask from landmarks and then recolor it using recolor calculator.

**Comment by cv-hirtihk** [comment]
@milad-4274 do you mind sharing the code that you used to generate the masks? btw, did you use opengl or opencv?

**Comment by salmanhiro** [comment]
okay now is there a way to use calculator on the JavaScript API? or I just don't get it?

**Comment by salmanhiro** [comment]
> okay now is there a way to use calculator on the JavaScript API? or I just don't get it?

I mean similar to fillPoly() in Python's OpenCV
