### ISSUE TITLE
How to Convert LandmarkProto.NormalizedLandmark into android screen pixel ..?

### ISSUE THREAD

**Issue by ni3-sharma** [google/mediapipe#1050]
I want to know that how to convert LandmarkProto.NormalizedLandmark convert into android screen pixel, like now x and y landmark in coming in the range of [0..1]  but i want to convert it according to my screen size...?.
.
.

**Comment by sgowroji** [comment]
Hi @ni3-sharma, Could you please elaborate your issue with complete details. Thanks!

**Comment by sgowroji** [comment]
Hi @ni3-sharma, Could you please respond to my above comment. Thanks!

**Comment by ni3-sharma** [comment]
hello @sgowroji 
sorry for the delay,

my point is that i am using this mediapipe hand tracking code in my android app and i got the points for the tracker that is in between 0 to 1 i just want to know about how to convert this normalize points according to android phone screen size.  
Thanks!

**Comment by sgowroji** [comment]
Hi @ni3-sharma, You can make the changes from both android platform side and graph as you have coordinates with you (you get coordinates by multiplying the normalized landmark value with the height and width of the image). 
If you are looking at graphs then you can refer [here](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.pbtxt#:~:text=%7D-,%23%20Converts%20normalized%20rects%20to%20drawing%20primitives%20for%20annotation%20overlay.,%7D,-%23%20Outputs%20each%20element) graph changes which you need to change as per  your requirement. Reach us back if you still have any quries on top of it. Thanks!
