### ISSUE TITLE
Front Face Detection lack of information 

### ISSUE THREAD

**Issue by SocialKitLtd** [google/mediapipe#1051]
Hey there,

I'm integrating Front Face Detection (https://google.github.io/mediapipe/solutions/face_detection) (https://drive.google.com/file/d/1f39lSzU5Oq-j_OXgS67KfN5wNsoeAZ4V/view) model within my app.
I'm trying to understand what is the input that the model is expecting. Looking at the docs, it says that it's expecting a 128x128 square input image. But my camera ratio is 9:16 (vertical), and I need to detect faces inside each frame.

What am I expected to do? Should I crop the center-square of the image? If so, I can't detect faces properly as the face could be in the upper/lower bounds of the box. Usually, for face detection, you use the whole image as input, then you get faces. What is the recommend approach for source image which is not square? 

Sample input from the camera:
![sample](https://user-images.githubusercontent.com/41643229/91289007-5f6a4000-e79a-11ea-8042-53420c33e28c.jpg)

**Comment by fanzhanggoogle** [comment]
You need to pad the image to make it a square input.

**Comment by sgowroji** [comment]
We are closing this issue now as we did not find any relevant update from the reporter.
