### ISSUE TITLE
How can I get an object detection example

### ISSUE THREAD

**Issue by ZZZhaowendao** [google/mediapipe#1053]
Hello,I have followed the guides [MediaPipe Android Archive](https://google.github.io/mediapipe/getting_started/android_archive_library.html).
In the final step,I am asked to follow your Android app examples to use Mediapipe in Android Studio for my use case.But I can't find an object detection example,more accurately,I need to know the content in MainActivity.java and activity_main.xml.
If anyone could give me some advice, I would be very grateful.

**Comment by PrinceP** [comment]
You can directly take the example from [face](https://github.com/jiuqiant/mediapipe_face_detection_aar_example),  [hand](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example) and [upperbody](https://github.com/PrinceP/CountDracula) activity. Copy the same layout xml. You have to follow the same tutorial for building appropriate files.

**Comment by ZZZhaowendao** [comment]
> You can directly take the example from [face](https://github.com/jiuqiant/mediapipe_face_detection_aar_example), [hand](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example) and [upperbody](https://github.com/PrinceP/CountDracula) activity. Copy the same layout xml. You have to follow the same tutorial for building appropriate files.

Thank you for your reply.I want to get the object detection example. Are face detection's MainActivity.java and obeject detection's MainActivity.java the same?

**Comment by PrinceP** [comment]
Object detection parameters has to added. Like [upperbody example]( https://github.com/PrinceP/CountDracula/blob/master/app/src/main/java/com/prince/countdracula/MainActivity.java#L34)

**Comment by ZZZhaowendao** [comment]
> Object detection parameters has to added. Like [upperbody example](https://github.com/PrinceP/CountDracula/blob/master/app/src/main/java/com/prince/countdracula/MainActivity.java#L34)

Thanks! I'll have a try : )

**Comment by sgowroji** [comment]
From the above resolved comments. We are closing this issue now.
