### ISSUE TITLE
Face Detection Bounding Box + Key-points  Output doesn't adds up

### ISSUE THREAD

**Issue by SocialKitLtd** [google/mediapipe#1054]
Looking at the Front Face Detection model (using Netron) shows that we get two output from the model:

<img width="1136" alt="Screen Shot 2020-08-27 at 13 48 11" src="https://user-images.githubusercontent.com/41643229/91433443-f6eb9380-e86b-11ea-9adb-124067e8b3d1.png">

And when looking at the model card (https://drive.google.com/file/d/1f39lSzU5Oq-j_OXgS67KfN5wNsoeAZ4V/view) it says:
_Returns a bounding box and 6 keypoints for each face (left eye from the observer’s point of view, right
eye, nose tip, mouth, left eye tragion, right eye tragion)._

I'm trying to understand:

1. Why there are two outputs in the model where the model description only speaks about one?
2. Why is the _regressors_ is `float32[1,896,16]`? 6 Landmarks point are 12 values (x,y), and face-bounding-box is 4 points (8 values), so 12 + 8 = 20. Unless I didn't understand the model (which probably the case).

Would love an elaboration, been stuck on this for days now.

**Comment by PrinceP** [comment]
Hi,

[Source1](https://github.com/hollance/BlazeFace-PyTorch/blob/master/blazeface.py)
[Source2](https://www.kaggle.com/humananalog/starter-blazeface-pytorch)
 
**The first 4 numbers describe the bounding box corners:**
        ymin, xmin, ymax, xmax
        These are normalized coordinates (between 0 and 1).
        Note that y comes before x here!
**The next 12 numbers are the x,y-coordinates of the 6 facial landmark keypoints:**
        right_eye_x, right_eye_y
        left_eye_x, left_eye_y
        nose_x, nose_y
        mouth_x, mouth_y
        right_ear_x, right_ear_y
        left_ear_x, left_ear_y
Tip: these labeled as seen from the perspective of the person, so their right is your left.
**The final number is the confidence score that this detection really is a face.**

If no faces are found, the tensor has shape (0, 17).

**Comment by fanzhanggoogle** [comment]
@SocialKitLtd has this issue been resolved? Thank you @PrinceP for providing help.

**Comment by farhadsh1992** [comment]
I don't understand it is float32[1,896,16]. ones of them your mean are ymin, xmin, ymax, xmax?

**Comment by sgowroji** [comment]
Assuming the above issue was answered your query, We are closing this now.
