### ISSUE TITLE
Can mediapipe be used with acclerated inference frameworks such as openvino?

### ISSUE THREAD

**Issue by rahulunair** [google/mediapipe#1055]
Out of curiosity, can mediapipe be used with `openvino` as one of its pipeline components, if so are there any examples to do so, we build optimized stacks for media analytics,  today we use `gstreamer` analytics framework: https://github.com/opencv/gst-video-analytics, but it would be very interesting to try `mediapipe` especially because of its flexibility.

**Comment by TheBricktop** [comment]
im also interested in this particular matter

**Comment by mcclanahoochie** [comment]
MediaPipe currently does not offer any calculators that integrate with openvino or gstreamer, but we welcome community contributions! 

There are other projects that have done similiar integrations, such as [NNStreamer](https://github.com/nnstreamer/nnstreamer/blob/main/ext/nnstreamer/tensor_filter/tensor_filter_mediapipe.cc)

**Comment by sgowroji** [comment]
As the above [comment](https://github.com/google/mediapipe/issues/1055#issuecomment-782369659) addressing your request. We are closing this issue now. Please feel free to reach us back if you still have any further queries.
