### ISSUE TITLE
calculators:landmarks_smoothing_calculator' failed (Exit 1) gcc failed: error

### ISSUE THREAD

**Issue by ElectricSquirrel** [google/mediapipe#1057]
When I'm running **python setup.py**  The errors found during install are as follows:
My configuration is
ubuntu ==16LTS
gcc ==5.4
python==3.7
I have run successfully on C + + hello:world Is the failure of autoflip and python media the cause of GCC version?
——————————————————————————————————————————————————-

INFO: Found 1 target...
ERROR: /home/ck/python_src/mediapipe/mediapipe/graphs/pose_tracking/calculators/BUILD:71:1: C++ compilation of rule '//mediapipe/graphs/pose_tracking/calculators:landmarks_smoothing_calculator' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 55 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc: In function 'float mediapipe::{anonymous}::GetObjectScale(const mediapipe::NormalizedLandmarkList&, int, int)':
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:41:15: error: expected unqualified-id before '[' token
   const auto& [lm_min_x, lm_max_x] = absl::c_minmax_element(
               ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:41:15: error: expected initializer before '[' token
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:43:65: error: expected primary-expression before ')' token
       [](const auto& a, const auto& b) { return a.x() < b.x(); });
                                                                 ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:44:23: error: 'lm_min_x' was not declared in this scope
   const float x_min = lm_min_x->x();
                       ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:45:23: error: 'lm_max_x' was not declared in this scope
   const float x_max = lm_max_x->x();
                       ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:47:15: error: expected unqualified-id before '[' token
   const auto& [lm_min_y, lm_max_y] = absl::c_minmax_element(
               ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:47:15: error: expected initializer before '[' token
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:49:65: error: expected primary-expression before ')' token
       [](const auto& a, const auto& b) { return a.y() < b.y(); });
                                                                 ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:50:23: error: 'lm_min_y' was not declared in this scope
   const float y_min = lm_min_y->y();
                       ^
mediapipe/graphs/pose_tracking/calculators/landmarks_smoothing_calculator.cc:51:23: error: 'lm_max_y' was not declared in this scope

**Comment by sgowroji** [comment]
Hi @ElectricSquirrel, Could you please check the above with latest version and reach us/ reopen if you see the same. Thanks!
