### ISSUE TITLE
Hello World - error: use of undeclared identifier 'posix_fadvise'

### ISSUE THREAD

**Issue by tracetidwell** [google/mediapipe#106]
I am trying to run the Hello World! in MediaPipe on Android example. I am able to get MediaPipe installed and can run the HelloWorld! Desktop example, but when I try to build the app, I keep getting the following error:

`ERROR: /home/trace/.cache/bazel/_bazel_trace/eaf828d0bc74efd5fd78acbebb35e0d4/external/com_github_glog_glog/BUILD.bazel:68:1: C++ compilation of rule '@com_github_glog_glog//:glog' failed (Exit 1) clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target ... (remaining 53 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_github_glog_glog/src/logging.cc:1123:9: error: use of undeclared identifier 'posix_fadvise'
        posix_fadvise(fileno(file_), 0, len, POSIX_FADV_DONTNEED);
`
As best I can tell, posix_fadvise() is defined in fcntl.h, and the logging.cc file has #include <fcntl.h>. I'm using Ubuntu 18.04. I'm new to Android Apps, so please let me know what additional information you need. Thank you.

**Comment by jiuqiant** [comment]
Can you provide the NDK version and the Bazel build you use to build the app?

**Comment by tracetidwell** [comment]
SDK Platform: Android 10.0, API Level 29, Revision 3
Android SDK Build Tools: 29.0.2
NDK: 20.0.5594570
Android SDK Tools: 26.1.1
Android SDK Platform Tools: 29.0.4
Bazel: 0.29.1

I think that's everything I installed (per the instructions). Thanks.

**Comment by tracetidwell** [comment]
Hello, any update on this? My professor, Thad Starner at Georgia Tech, wanted me to mention that we are hoping to use MediaPipe for sign language recognition. I believe Google has an internal project going on, and I believe there will be some collaboration between the two groups. We'd love to get this up and running. Thanks.

**Comment by jiuqiant** [comment]
Can you use another machine or a docker container to reproduce the issue? Unfortunately, I can't reproduce this issue locally with your settings. If you can reproduce the issue somewhere else, that means this issue is a general issue that we should fix. Otherwise, it might be a specific issue related to your machine.

**Comment by weinixuehao** [comment]
`1 warning generated.
[496 / 773] [Sched] Desugaring external/maven/_aar/androidx_asynclayoutinflater_asynclayoutinflater/classes_and_libs_merged.jar for Android; 455s ... (128 actions, 4 running)
[540 / 808] [Sched] Desugaring external/maven/v1/https/maven.google.com/androidx/concurrent/concurrent-futures/1.0.0-alpha03/concurrent-futures-1.0.0-alpha03.jar for Android; 529s ... (128 actions, 4 running)
[593 / 845] [Sched] Desugaring external/maven/v1/https/jcenter.bintray.com/org/checkerframework/checker-compat-qual/2.5.2/checker-compat-qual-2.5.2.jar for Android; 614s ... (128 actions, 4 running)
[642 / 845] [Sched] Desugaring external/maven/_aar/androidx_documentfile_documentfile/classes_and_libs_merged.jar for Android; 710s ... (116 actions, 4 running)
ERROR: /private/var/tmp/_bazel_chenlong/46cfe12d82525b8b2b43cf38d2da2eb7/external/com_github_glog_glog/BUILD.bazel:68:1: C++ compilation of rule '@com_github_glog_glog//:glog' failed (Exit 1) sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_chenlong/46cfe12d82525b8b2b43cf38d2da2eb7/sandbox/darwin-sandbox/974/execroot/mediapipe && \
  exec env - \
    PATH='/usr/local/opt/binutils/bin:/usr/local/include:/Users/user/Library/Android/sdk/platform-tools:/Users/user/Library/Android/sdk/ndk/android_ndk_r20b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Applications/Wireshark.app/Contents/MacOS' \
    PWD=/proc/self/cwd \
    TMPDIR=/var/folders/5x/0fyz2rrd14v8jg5g6fr2h2n00000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_chenlong/46cfe12d82525b8b2b43cf38d2da2eb7/sandbox/darwin-sandbox/974/sandbox.sb /var/tmp/_bazel_chenlong/install/141b384b5c92ce6d44f56e59ae444f56/process-wrapper '--timeout=0' '--kill_delay=15' external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 -target aarch64-none-linux-android -fpic -isystemexternal/androidndk/ndk/sysroot/usr/include/aarch64-linux-android '-D__ANDROID_API__=16' -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -funwind-tables -fstack-protector-strong -fno-addrsig '-Werror=return-type' '-Werror=int-to-pointer-cast' '-Werror=pointer-to-int-cast' '-Werror=implicit-function-declaration' -O2 -g -DNDEBUG -MD -MF bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/_objs/glog/logging.pic.d '-frandom-seed=bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/_objs/glog/logging.pic.o' -fPIC -iquote external/com_github_glog_glog -iquote bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog -isystem external/com_github_glog_glog/src -isystem bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/src -Wno-sign-compare -Wno-unused-function -Wno-uninitialized -Wno-unused-result -Wno-comment -Wno-return-type -Wno-unused-local-typedefs -Wno-ignored-attributes '-std=c++14' -Wno-sign-compare -U_XOPEN_SOURCE '--sysroot=external/androidndk/ndk/platforms/android-28/arch-arm64' -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c external/com_github_glog_glog/src/logging.cc -o bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/_objs/glog/logging.pic.o)
external/com_github_glog_glog/src/logging.cc:1127:9: error: use of undeclared identifier 'posix_fadvise'
        posix_fadvise(fileno(file_), 0, len, POSIX_FADV_DONTNEED);
        ^
1 error generated.
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu:edgedetectiongpu failed to build
Use --verbose_failures to see the command lines of failed build steps.`

I meet the same question which using android studio to compile.

**Comment by weinixuehao** [comment]
@jiuqiant @tracetidwell 
I have built success! posix_fadvise only working in android_api 21,  please try to change  android_ndk_repository(
    name = "androidndk",
    path = "/Users/user/Library/Android/sdk/ndk/android_ndk_r20b",
    api_level = 21
)
more details in https://stackoverflow.com/questions/29347531/undefined-reference-to-posix-fadvise

`INFO: From Installing //mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu:edgedetectiongpu:
I0424 19:32:50.289311 4654837184 incremental_install.py:441] Updating 1 dex...
I0424 19:32:50.582242 4654837184 incremental_install.py:504] Updating application resources...
I0424 19:32:51.263939 4654837184 incremental_install.py:601] Updating 2 native libs...
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu:edgedetectiongpu up-to-date:
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu/edgedetectiongpu_files/full_deploy_marker
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu/edgedetectiongpu_files/deploy_info_incremental.deployinfo.pb
INFO: Elapsed time: 945.478s, Critical Path: 923.52s
INFO: 571 processes: 452 darwin-sandbox, 1 local, 118 worker.
INFO: Build completed successfully, 573 total actions
INFO: Build completed successfully, 573 total actions
INFO: Build Event Protocol files produced successfully.
INFO: Build completed successfully, 573 total actions
Reading deployment information...`

**Comment by mapleyuan** [comment]
@jiuqiant @tracetidwell @weinixuehao I found it is a glog issus, and it had been solved. just need to patched the change.https://github.com/google/glog/commit/1227cf4dab20ea7b1770822c9db8c99498ba0f37#diff-8b7c2e002f1814c322f81e0c0ecb3e7c
