### ISSUE TITLE
How to Use  Hand gesture detection, Mideapipe model  to detect, in Flutter Application

### ISSUE THREAD

**Issue by dilipxp** [google/mediapipe#1062]
I'm building a app  in Flutter for hand gesture  detection, So what are the steps to do this in my project
and where i can found  good documentation to do this

**Comment by dilipxp** [comment]
And can I used my own gestures for this

**Comment by mgyong** [comment]
#1046 #17

**Comment by zhouzaihang** [comment]
you can see it.
[](https://github.com/zhouzaihang/flutter_hand_tracking_plugin)

**Comment by zhouzaihang** [comment]
https://github.com/zhouzaihang/flutter_hand_tracking_plugin
