### ISSUE TITLE
Iris depth estimation in python

### ISSUE THREAD

**Issue by Mudasar-Makandar** [google/mediapipe#1063]
I want to build python web app to find distance between webcam and iris. Is there anyway i can build this using tensorflow?

**Comment by jiuqiant** [comment]
Hi there. we will release Python support for more MediaPipe solutions in early Q4, e.g., Oct.  Will keep you posted.

**Comment by robertodaza** [comment]
Hello:

I would like to know when iris detection will be supported in python?

Thank you very much for the help you give to the scientific  community.

**Comment by robertodaza** [comment]
> Hi there. we will release Python support for more MediaPipe solutions in early Q4, e.g., Oct. Will keep you posted.

Hello:

I would like to know when iris detection will be supported in python?

Thank you very much for the help you give to the scientific community.

**Comment by alexandre01** [comment]
Dear @jiuqiant ,
Any updates on Python support for the Iris solution? Would be awesome!

**Comment by DimIsaev** [comment]
and when?
