### ISSUE TITLE
Build a Real-time Iris Depth Estimation Demo

### ISSUE THREAD

**Issue by boger57** [google/mediapipe#1064]
Hi~I want to know how to build a real-time iris depth estimation demo in this blog [https://ai.googleblog.com/2020/08/mediapipe-iris-real-time-iris-tracking.html](url) . I have tried to refer to the iris_tracking_cpu demo and iris_depth_from_image_desktop to build a real-time iris depth estimation demo. But the depth calculator seems to can not deal with the image frame without exif info. what should I do next?

**Comment by fanzhanggoogle** [comment]
To clarify, you are working on real time application on desktop right? Otherwise there's already [mobile demo](https://google.github.io/mediapipe/solutions/iris#mobile).
For real time application on desktop you must have the focal length of the camera you're using to enable it.

**Comment by andy380743909** [comment]
> To clarify, you are working on real time application on desktop right? Otherwise there's already [mobile demo](https://google.github.io/mediapipe/solutions/iris#mobile). For real time application on desktop you must have the focal length of the camera you're using to enable it.

hi @fanzhanggoogle , can you tell me how to get facal length of the webcamera from the video stream captured from the camera?
