### ISSUE TITLE
Build MediaPipe hands example on Ubuntu failed

### ISSUE THREAD

**Issue by chenluochuan** [google/mediapipe#1065]
### While building hands examples on Ubuntu, i use the command:
`bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
  mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
`

### but i got the error:

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/KhronosGroup/OpenCL-Headers/archive/0d5f18c6e7196863bc1557a693f1509adfcee056.tar.gz failed: class java.io.IOException connect timed out
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/s01/chz/mediapipe-master/mediapipe/calculators/image/BUILD:303:11: C++ compilation of rule '//mediapipe/calculators/image:image_transformation_calculator' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 63 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/image/image_transformation_calculator.cc: In member function 'mediapipe::Status mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*)':
mediapipe/calculators/image/image_transformation_calculator.cc:455:9: error: 'rotate' is not a member of 'cv'
         cv::rotate(input_mat, rotated_mat, cv::ROTATE_90_COUNTERCLOCKWISE);
         ^
mediapipe/calculators/image/image_transformation_calculator.cc:455:9: note: suggested alternatives:
In file included from /usr/include/c++/5/algorithm:62:0,
                 from external/com_google_protobuf/src/google/protobuf/stubs/common.h:38,
                 from external/com_google_protobuf/src/google/protobuf/io/coded_stream.h:141,
                 from bazel-out/k8-opt/bin/mediapipe/calculators/image/image_transformation_calculator.pb.h:23,
                 from mediapipe/calculators/image/image_transformation_calculator.cc:15:
/usr/include/c++/5/bits/stl_algo.h:1431:5: note:   'std::_V2::rotate'
     rotate(_ForwardIterator __first, _ForwardIterator __middle,
     ^
/usr/include/c++/5/bits/stl_algo.h:1431:5: note:   'std::_V2::rotate'
In file included from external/com_google_absl/absl/algorithm/container.h:53:0,
                 from external/com_google_absl/absl/container/flat_hash_set.h:35,
                 from ./mediapipe/framework/deps/registration.h:29,
                 from ./mediapipe/framework/packet.h:31,
                 from ./mediapipe/framework/calculator_state.h:30,
                 from ./mediapipe/framework/calculator_context.h:23,
                 from ./mediapipe/framework/calculator_base.h:22,
                 from ./mediapipe/framework/calculator_framework.h:54,
                 from mediapipe/calculators/image/image_transformation_calculator.cc:16:
external/com_google_absl/absl/algorithm/algorithm.h:148:17: note:   'absl::lts_2020_02_25::rotate'
 ForwardIterator rotate(ForwardIterator first, ForwardIterator middle,
                 ^
external/com_google_absl/absl/algorithm/algorithm.h:148:17: note:   'absl::lts_2020_02_25::rotate'
mediapipe/calculators/image/image_transformation_calculator.cc:455:44: error: 'ROTATE_90_COUNTERCLOCKWISE' is not a member of 'cv'
         cv::rotate(input_mat, rotated_mat, cv::ROTATE_90_COUNTERCLOCKWISE);
                                            ^
mediapipe/calculators/image/image_transformation_calculator.cc:458:9: error: 'rotate' is not a member of 'cv'
         cv::rotate(input_mat, rotated_mat, cv::ROTATE_180);
         ^
mediapipe/calculators/image/image_transformation_calculator.cc:458:9: note: suggested alternatives:
In file included from /usr/include/c++/5/algorithm:62:0,
                 from external/com_google_protobuf/src/google/protobuf/stubs/common.h:38,
                 from external/com_google_protobuf/src/google/protobuf/io/coded_stream.h:141,
                 from bazel-out/k8-opt/bin/mediapipe/calculators/image/image_transformation_calculator.pb.h:23,
                 from mediapipe/calculators/image/image_transformation_calculator.cc:15:
/usr/include/c++/5/bits/stl_algo.h:1431:5: note:   'std::_V2::rotate'
     rotate(_ForwardIterator __first, _ForwardIterator __middle,
     ^
/usr/include/c++/5/bits/stl_algo.h:1431:5: note:   'std::_V2::rotate'
In file included from external/com_google_absl/absl/algorithm/container.h:53:0,
                 from external/com_google_absl/absl/container/flat_hash_set.h:35,
                 from ./mediapipe/framework/deps/registration.h:29,
                 from ./mediapipe/framework/packet.h:31,
                 from ./mediapipe/framework/calculator_state.h:30,
                 from ./mediapipe/framework/calculator_context.h:23,
                 from ./mediapipe/framework/calculator_base.h:22,
                 from ./mediapipe/framework/calculator_framework.h:54,
                 from mediapipe/calculators/image/image_transformation_calculator.cc:16:
external/com_google_absl/absl/algorithm/algorithm.h:148:17: note:   'absl::lts_2020_02_25::rotate'
 ForwardIterator rotate(ForwardIterator first, ForwardIterator middle,
                 ^
external/com_google_absl/absl/algorithm/algorithm.h:148:17: note:   'absl::lts_2020_02_25::rotate'
mediapipe/calculators/image/image_transformation_calculator.cc:458:44: error: 'ROTATE_180' is not a member of 'cv'
         cv::rotate(input_mat, rotated_mat, cv::ROTATE_180);
                                            ^
mediapipe/calculators/image/image_transformation_calculator.cc:461:9: error: 'rotate' is not a member of 'cv'
         cv::rotate(input_mat, rotated_mat, cv::ROTATE_90_CLOCKWISE);
         ^
mediapipe/calculators/image/image_transformation_calculator.cc:461:9: note: suggested alternatives:
In file included from /usr/include/c++/5/algorithm:62:0,
                 from external/com_google_protobuf/src/google/protobuf/stubs/common.h:38,
                 from external/com_google_protobuf/src/google/protobuf/io/coded_stream.h:141,
                 from bazel-out/k8-opt/bin/mediapipe/calculators/image/image_transformation_calculator.pb.h:23,
                 from mediapipe/calculators/image/image_transformation_calculator.cc:15:
/usr/include/c++/5/bits/stl_algo.h:1431:5: note:   'std::_V2::rotate'
     rotate(_ForwardIterator __first, _ForwardIterator __middle,
     ^
/usr/include/c++/5/bits/stl_algo.h:1431:5: note:   'std::_V2::rotate'
In file included from external/com_google_absl/absl/algorithm/container.h:53:0,
                 from external/com_google_absl/absl/container/flat_hash_set.h:35,
                 from ./mediapipe/framework/deps/registration.h:29,
                 from ./mediapipe/framework/packet.h:31,
                 from ./mediapipe/framework/calculator_state.h:30,
                 from ./mediapipe/framework/calculator_context.h:23,
                 from ./mediapipe/framework/calculator_base.h:22,
                 from ./mediapipe/framework/calculator_framework.h:54,
                 from mediapipe/calculators/image/image_transformation_calculator.cc:16:
external/com_google_absl/absl/algorithm/algorithm.h:148:17: note:   'absl::lts_2020_02_25::rotate'
 ForwardIterator rotate(ForwardIterator first, ForwardIterator middle,
                 ^
external/com_google_absl/absl/algorithm/algorithm.h:148:17: note:   'absl::lts_2020_02_25::rotate'
mediapipe/calculators/image/image_transformation_calculator.cc:461:44: error: 'ROTATE_90_CLOCKWISE' is not a member of 'cv'
         cv::rotate(input_mat, rotated_mat, cv::ROTATE_90_CLOCKWISE);
                                            ^
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.133s, Critical Path: 3.90s
INFO: 21 processes: 21 linux-sandbox.
FAILED: Build did NOT complete successfully**

**Comment by jiuqiant** [comment]
What's you opencv version?

For example, cv:: ROTATE_90_CLOCKWISE exist in OpenCV 3.4: https://docs.opencv.org/3.4/d2/de8/group__core__array.html

**Comment by jiuqiant** [comment]
What's you opencv version? Can you also report how you config your opencv for MediaPipe?  The third step of https://google.github.io/mediapipe/getting_started/install#installing-on-debian-and-ubuntu can be useful.

The error message says `mediapipe/calculators/image/image_transformation_calculator.cc:461:44: error: 'ROTATE_90_CLOCKWISE' is not a member of 'cv'`. But, we can find that cv:: ROTATE_90_CLOCKWISE exists in OpenCV 3.4: https://docs.opencv.org/3.4/d2/de8/group__core__array.html. If you use opencv3.4, the error should go away.

**Comment by chenluochuan** [comment]
Thanks for your reply! I followed the the Option 1 of the third step in [https://google.github.io/mediapipe/getting_started/install#installing-on-debian-and-ubuntu ](url). 
And use the command `sudo apt-get install libopencv-core-dev libopencv-highgui-dev \
                       libopencv-calib3d-dev libopencv-features2d-dev \
                       libopencv-imgproc-dev libopencv-video-dev`

Maybe I should choose Option 2 or 3 to install the opencv3?

**Comment by jiuqiant** [comment]
Can you report your opencv version or your OS version (we can find out the opencv version from the OS version)? 

Moreover, can you find where your opencv headers and libraries are? Then, you can follow [this instruction](https://github.com/google/mediapipe/issues/666#issuecomment-620908524) to modify the config.

If it still doesn't work, you can try option 2.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
