### ISSUE TITLE
Tests fail with an error in VerifyVersion of ProtocolBuffers.

### ISSUE THREAD

**Issue by H1Gdev** [google/mediapipe#1067]
# Test

For example, run the following test.

## Run

```sh
$ bazel test -c opt //mediapipe/calculators/core:add_header_calculator_test`
```

## Log

```txt
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //mediapipe/calculators/core:add_header_calculator_test
-----------------------------------------------------------------------------
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/stubs/common.cc:87] This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.11.4).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-O8_xaj/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.11.4).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-O8_xaj/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
external/bazel_tools/tools/test/test-setup.sh: line 310:    14 Aborted                 (core dumped) "${TEST_PATH}" "$@" 2>&1
```

## Version

v0.7.9

## OS

Ubunt 16.04 LTS

**Comment by H1Gdev** [comment]
Each values in `VerifyVersion` are as follows.

- `headerVersion` is `2.6.1`
- `minLibraryVersion` is `2.6.0`
- `filename` is `/build/mir-O8_xaj/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc`
- `kMinHeaderVersionForLibrary` is `3.11.0`
- `GOOGLE_PROTOBUF_VERSION` is `3.11.4`

Library using old version ProtocolBuffers is as follows.

`/usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3`

This library is dependent on the following.

[4 For running desktop examples on Linux only (not on OS X) with GPU acceleration.](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu)
```sh
sudo apt-get install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev
```

**Comment by sgowroji** [comment]
Hi @H1Gdev, Could you please confirm if you are still looking resolution for the above query. Thanks!

**Comment by H1Gdev** [comment]
I couldn't find solution...
The latest version has build error...

**Comment by kuaashish** [comment]
Hello @H1Gdev,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
