### ISSUE TITLE
Using mediapipe.dev 

### ISSUE THREAD

**Issue by dgrnd4** [google/mediapipe#1069]
Hi there, i had problem using mediapipe on desktop so i start now using viz.mediapipe.dev, is it the same of the mediapipe used on desktop, right?
However i am trying to upload two file in viz.mediapipe.dev going to UPLOAD -> UPLOAD GRAPH but the running man is transparent and do not make me able to run the graph.
How can i solve the problem?
Many thanks

**Comment by mgyong** [comment]
Can you share the files you are uploading so that we can replicate the error? What is the error?

**Comment by dgrnd4** [comment]
Those are my steps:
- open viz.mediapipe.dev/ so without files
- UPLOAD -> UPLOAD GRAPH -> ADD "_runner_demos_hand_detection_files_cpu_oss_handdetect.pbtxt"
- UPLOAD -> UPLOAD GRAPH -> ADD "_runner_demos_hand_detection_files_cpu_oss_handdetect_subgraph.pbtxt"
Those two file are from the demo example: https://viz.mediapipe.dev/demo/hand_detection where both work and where is possible run the program. 

As feedback in the bottom of the page i have:
Loaded graph '/runner/demos/blank_files/blank.pbtxt'.
Loaded graph '_runner_demos_hand_detection_files_cpu_oss_handdetect.pbtxt'.
Uploaded graph '_runner_demos_hand_detection_files_cpu_oss_handdetect.pbtxt'
Loaded graph '_runner_demos_hand_detection_files_cpu_oss_handdetect_subgraph.pbtxt'.
Uploaded graph '_runner_demos_hand_detection_files_cpu_oss_handdetect_subgraph.pbtxt'

So there are not error. 

Could you please tell me how can i even run files made by me or taken online and modified with extention .pbtxt, in general?

**Comment by mhays-google** [comment]
Running graphs is still very much an experimental feature -- we haven't yet agreed on a good way to make calculators generically available.  So, regrettably, the only recourse at the moment is to edit the existing graphs.

I know that this is a desirable feature, and we'll hopefully have this in the near future, but no commitment has been made yet.
