### ISSUE TITLE
/usr/bin/env: 'python': No such file or directory

### ISSUE THREAD

**Issue by calvin422** [google/mediapipe#107]
When I am building objectdetectioncpu
`
`skss@skss-VirtualBox:~/mediapipe$ bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu``

Error message as followed:

> ```
> WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
> INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu:objectdetectioncpu (2 packages loaded, 19 targets configured).
> INFO: Found 1 target...
> ERROR: /home/skss/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:34:1: Validating proguard configuration failed (Exit 127) proguard_whitelister failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/jdk/proguard_whitelister --path mediapipe/java/com/google/mediapipe/framework/proguard.pgcfg --output ... (remaining 1 argument(s) skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox
> /usr/bin/env: 'python': No such file or directory
> Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu:objectdetectioncpu failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> ```
> 
> 

and i check that i can run python in this directory 
```
(cv) skss@skss-VirtualBox:~$ /usr/bin/env python --version
Python 3.6.8
```

How can I solve it ?

Thank you

**Comment by jiuqiant** [comment]
Hi, we haven't tested MediaPipe on VirtualBox. As far as I can tell, it seems to be a Bazel python3 issue. Tensorflow also gets a similar issue: https://github.com/tensorflow/tensorflow/issues/15618#issuecomment-376009820. You probably can try python2 instead. For example, you can install python2 and linking python to python2 by `sudo ln -s /usr/bin/python2.7 /usr/bin/python`.

**Comment by jiuqiant** [comment]
Closing due to lack of recent activity.

**Comment by heirro** [comment]
> Hi, we haven't tested MediaPipe on VirtualBox. As far as I can tell, it seems to be a Bazel python3 issue. Tensorflow also gets a similar issue: [tensorflow/tensorflow#15618 (comment)](https://github.com/tensorflow/tensorflow/issues/15618#issuecomment-376009820). You probably can try python2 instead. For example, you can install python2 and linking python to python2 by `sudo ln -s /usr/bin/python2.7 /usr/bin/python`.

Thank you!
