### ISSUE TITLE
Bazel tulsi xcode project creator is crashing on my machine giving this error how can I fix this?

### ISSUE THREAD

**Issue by Zulqurnain24** [google/mediapipe#1071]
Bazel tulsi xcode project creator is crashing on my machine giving this error how can I fix this? Please help. Thanks in advance.
https://github.com/bazelbuild/tulsi/issues/142

**Comment by sgowroji** [comment]
Hi @Zulqurnain24, Could you please test the above with the latest release and reach us if you have any queries.
