### ISSUE TITLE
can't compile face_mesh:face_mesh_cpu on Windows...

### ISSUE THREAD

**Issue by drhalftone** [google/mediapipe#1072]
I successfully compiled and ran the Hello World desktop app, but no luck on any other project.  Here is my output

C:\Users\dllau\mediapipe_repo\mediapipe>bazel clean --expunge
Starting local Bazel server and connecting to it...
INFO: Starting clean.

C:\Users\dllau\mediapipe_repo\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//dllau//AppData//Local//Programs//Python//Python38//python.exe" mediapipe/examples/desktop/object_detection:object_detection_tflite
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = 2a34fa56d923f774409d23720e60ddf6536e88622d000e6925f7cebbad65e281
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "2a34fa56d923f774409d23720e60ddf6536e88622d000e6925f7cebbad65e281"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  C:/users/dllau/_bazel_dllau/3ky6mj3u/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe/examples/desktop/object_detection:object_detection_tflite (104 packages loaded, 3856 targets configured).
INFO: Found 1 target...
ERROR: C:/users/dllau/_bazel_dllau/3ky6mj3u/external/com_github_gflags_gflags/BUILD:16:30: Executing genrule @com_github_gflags_gflags//:gflags_google_h failed (Exit -1073741819)
      1 [main] bash (14172) C:\msys64\usr\bin\bash.exe: *** fatal error - add_item ("\??\C:\msys64", "/", ...) failed, errno 1
Stack trace:
Frame        Function    Args
000FFFFCCE0  00180062FFE (0018028EFBA, 00180269FC1, 00800000000, 000FFFF8B50)
000FFFFCCE0  0018004973A (00000000000, 000FFFFCCE0, 00180020010, 000FFFFABEA)
000FFFFCCE0  00180049772 (000FFFF9BD0, 00000000001, 00800000000, 6D5C3A435C3F3F5C)
000FFFFCCE0  001800E9A6F (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCCE0  0018013C565 (001800D4B1A, 00000000000, 00000000000, 00000000000)
000FFFFCCE0  00180049D95 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180048846 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  001800488F4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
Target //mediapipe/examples/desktop/object_detection:object_detection_tflite failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 146.842s, Critical Path: 20.05s
INFO: 14 processes: 14 local.
FAILED: Build did NOT complete successfully

**Comment by jiuqiant** [comment]
Have you run into [this issue](https://github.com/google/mediapipe/issues/908#issuecomment-659565309)?

**Comment by drhalftone** [comment]
I’ll did downgrade to 0.7.5 and that fixed hello world.

**Comment by jiuqiant** [comment]
Then, you got the issue with v0.7.5?

**Comment by drhalftone** [comment]
Yes. I used 0.7.5.  I did run into an error that the project was looking for Opencv 3.4.1.  So I downloaded the binaries from opencv’s website.  I did not build those libraries from scratch.  That fixed the compiling issue raised, and then I got this issue.





On Sep 1, 2020, at 12:48 PM, Jiuqiang Tang <notifications@github.com> wrote:


Then, you got the issue with v0.7.5?

**Comment by jiuqiant** [comment]
FYI, the compilation error is fixed in https://github.com/google/mediapipe/commit/c828392681bc343a90e188c5ad5f295bada1eefb.
