### ISSUE TITLE
[Doubt-Hand-Python] Is it possible to use provided tflite models with TensorFlow?

### ISSUE THREAD

**Issue by Sreerag-ibtl** [google/mediapipe#1073]
Found that hand landmark detection is not possible with the Python API. But the hand landmark detection model provided is [dot]tflite. I was wondering whether it is possible to use the model with TensorFlow.

**Comment by jiuqiant** [comment]
Hi, we will release Python support for more MediaPipe solutions in early Q4, e.g., Oct.

tflite models can work with tflite inference engine. See https://www.tensorflow.org/lite for more details.
