### ISSUE TITLE
BatchSequentialCalculator missing

### ISSUE THREAD

**Issue by jinuhwang** [google/mediapipe#1076]
Hi, I found this new comment from tensorflow_inference_calculator.proto:80.
> If turned on, the Calculator expects a vector of batched packages as input.
> This will make sure that you can turn on max_in_flight for batch_size
> greater than 1. Otherwise it results in problems of none-monotonically
> increasing timestamps.
> Use BatchSequentialCalculator to create the batches. The batch_size
> should agree for both calculators. All the data in a batch is processed
> together. The BatchSequentialCalculator can't run with max_in_flight. 

But I couldn't find the `BatchSequentialCalculator` anywhere in the v0.7.10.

 Will it be available in the future releases?

**Comment by jiuqiant** [comment]
Apologize for the confusion. Currently, we don't have a plan to release that calculator. 
Do you have a use case for this?

**Comment by jinuhwang** [comment]
Hi @jiuqiant. Thank you for the follow-up.
Yes, I do. The object detection algorithms were showing very low GPU utilization so I was hoping I could batch several frames and run the inference at once.

**Comment by jiuqiant** [comment]
Then, you can just set https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/graphs/object_detection/object_detection_desktop_tensorflow_graph.pbtxt#L52 to be a large number to enable batching. Usually people set batch_size to 32.

The batch size is defined at https://github.com/google/mediapipe/blob/c0124fb83c667917c7bf6a84f442a0136e8f2cf7/mediapipe/calculators/tensorflow/tensorflow_inference_calculator.proto#L39.

**Comment by jinuhwang** [comment]
I tried using the option earlier but it seemed I needed to change the model itself to support the batch input.
```
Invalid argument: Input shape axis 0 must equal 1, got shape [32,1080,1920,3]
         [[{{node Preprocessor/unstack}}]]
```
So I was looking around to see if there is a way to achieve batching without changing the model and came across this comment.

**Comment by jiuqiant** [comment]
I see. Basically your model doesn't support batch input. However, the batch mode requires tensors with different timestamp to be concatenated and then the calculator sends one tensor to the tensorflow session object. See https://github.com/google/mediapipe/blob/c0124fb83c667917c7bf6a84f442a0136e8f2cf7/mediapipe/calculators/tensorflow/tensorflow_inference_calculator.cc#L504

**Comment by jiuqiant** [comment]
I see. Basically your model doesn't support batch input. However, the batch mode requires tensors (with different timestamps) to be concatenated and then the calculator sends one tensor to the tensorflow session object for inference. See https://github.com/google/mediapipe/blob/c0124fb83c667917c7bf6a84f442a0136e8f2cf7/mediapipe/calculators/tensorflow/tensorflow_inference_calculator.cc#L504

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
