### ISSUE TITLE
How can I get Mediapipe Example's source code?

### ISSUE THREAD

**Issue by ZZZhaowendao** [google/mediapipe#1079]
I have built the mediapipe example(object detection),but in the folder I can only find the apk file.
How can I get the mediapipe example's source code?

**Comment by dgrnd4** [comment]
Follow!!!!!

**Comment by jiuqiant** [comment]
If I understand your question correctly, you want to build the apps for source? 

For Android, please read https://google.github.io/mediapipe/getting_started/building_examples#android or try https://github.com/google/mediapipe/blob/master/build_android_examples.sh.
For iOS, please read https://google.github.io/mediapipe/getting_started/building_examples#ios or try https://github.com/google/mediapipe/blob/master/build_ios_examples.sh.
For Linux or macOS desktop demos, please read https://google.github.io/mediapipe/getting_started/building_examples#desktop.

Thanks.

**Comment by dgrnd4** [comment]
No, the point is: which are files that should be modified to be able to modify things?

**Comment by jiuqiant** [comment]
> No, the point is: which are files that should be modified to be able to modify things?

Already clarified. Thanks.
