### ISSUE TITLE
How can I get the MainActivity.java in the Mediapipe example file that has been built?

### ISSUE THREAD

**Issue by ZZZhaowendao** [google/mediapipe#1082]
I'm sorry I asked the question again, maybe I didn't make it clear in #1079 last time.
I have built the mediapipe example(objectdetectiongpu),and get the following file directory:
```
.idea
_dx
_merged
objectdetectiongpu_files
objectdetectiongpu_processed_manifest
objectdetectiongpu_symbols
proguard
objectdetectiongpu.ap_
objectdetectiongpu.apk
objectdetectiongpu.srcjar
objectdetectiongpu_deploy.jar
objectdetectiongpu_deploy.jar-0.params
objectdetectiongpu_resources.jar
objectdetectiongpu_resources.jar.dex
objectdetectiongpu_resources.jar.dex.zip-0.params
objectdetectiongpu_resources.jar_desugared.jar
objectdetectiongpu_resources.jar_desugared.jar-0.params
objectdetectiongpu_unsigned.apk
```
I want to know how can I get the MainActivity.java in these files or the Android Project code : )

**Comment by jiuqiant** [comment]
All MediaPipe android examples are on top on a template app: https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java. 

The MainActivity.java is shared across all the android examples. For example, the object detection gpu depends on mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic at https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu/BUILD#L58
