### ISSUE TITLE
Why the performance of Face_Landmark model is varying with different solutions?

### ISSUE THREAD

**Issue by LarryBrinzo** [google/mediapipe#1087]
According to [this](https://google.github.io/mediapipe/solutions/face_mesh.html#overview) post, ARCore, Firebase MLKit face detection API and youtube try-on uses MediaPipe as a core solution. I have tried all of the solutions, but each of them performs very differently in terms of mesh detection.

ARCore and MediaPipe do not perform very well for lips detection. Firebase MLKit is better and youtube try-on is the best. 

Please suggest me a way with which I can make MediaPipe solution better in terms of detection. 

[Link to the outputs from different solutions](https://drive.google.com/drive/folders/1J6B9DvG-rkO3YxkgfRvpK2vD8nCkGdQA?usp=sharing)

**Comment by mgyong** [comment]
Models used in each of the solution are different.

**Comment by LarryBrinzo** [comment]
Thank you so much for your reply. Are there any plans to improve the FaceLandmark model that is being used in MediaPipe?
