### ISSUE TITLE
Req Android / IOS project source code 

### ISSUE THREAD

**Issue by samsgates** [google/mediapipe#109]
i have run bazel mobile build generation, but it's generated IPA, APK files as final output, it's not provide xcode or android studio project source code. 
can you please provide complete project source code for IOS and Android..!

**Comment by jiuqiant** [comment]
Glad to hear that you can successfully build the IPAs and APKs. 

For the source code, we do provide the source code of our Android and iOS examples in https://github.com/google/mediapipe/tree/master/mediapipe/examples.
Please follow https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#setting-up-android-studio-with-mediapipe and https://github.com/google/mediapipe/blob/master/mediapipe/docs/mediapipe_ios_setup.md#creating-an-xcode-project to see how to set up mediapipe with android studio and xcode.

**Comment by jiuqiant** [comment]
Closing due to lack of recent activity.
