### ISSUE TITLE
TfLiteWebGlInferenceCalculator cannot find implementation

### ISSUE THREAD

**Issue by studentdeng** [google/mediapipe#1092]
[hand_tracking demo](https://viz.mediapipe.dev/demo/hand_tracking )  is running really fast.   I cannot find TfLiteWebGlInferenceCalculator implementation. It is running on cpu backend or webgl backend. Does Mediapipe is going to support webgl backend in the future?

**Comment by mgyong** [comment]
@studentdeng Yes the hand tracking web demo is running webgl backend and we have plans to support webgl backend

**Comment by studentdeng** [comment]
@mgyong  thanks for response. I am delighted to hear that !

**Comment by AlexMemomi** [comment]
@mgyong Hi, any news about webgl backend support? Maybe as separate repository. Can you share just a related part of webgl backend? We really need it to build our own binary for web (link with our project). Like:
InferenceCalculatorMlDriftWebGl
MlDriftCalculator

Thank's
