### ISSUE TITLE
interpreter_->Invoke()   sometimes don't return.

### ISSUE THREAD

**Issue by lovehuanhuan** [google/mediapipe#1093]
On  rk3399 with android system,  I use this "upbodyposetracking " example, after about 2 hours, the data flow stops, the function " interpreter_->Invoke()" int file "tflite_inference_calculator.cc " doesn't return.

**Comment by mgyong** [comment]
@lovehuanhuan We need more info on the error to debug. Unfortunately we don't have rk3399. It might be a bug with Rockchip? We do have a support engineering contact at Rockchip. Can you send me an email mgyong@google.com and also rough description of your use case

**Comment by sgowroji** [comment]
Hi @lovehuanhuan, Could you please respond whether you see the same error with the latest release and  let us know on it. Thanks!
