### ISSUE TITLE
There is only one example of running MediaPipe on an image, and this is hard.

### ISSUE THREAD

**Issue by algal** [google/mediapipe#1095]
Hello! This is not a bug, but a (heartfelt!) request for more examples or documentation, please.

Specifically, it would be wonderful to be able, out of the box:

1. to install MediaPipe as a Python library.
2.  so you can easily run MediaPipe on single image

Why? Well, Mediapipe has so many cool and impressive models in it. That's great! But to assess what you can use in your research or your application, you will almost always want to start by doing the simplest possible thing -- namely, *just running MediaPipe on a JPEG file*. This lets you experiment and also lets you run MediaPipe over batches of images to assess performance for your application.

I may be missing something, but this seems ... quite hard to do?

The documentation describes how to install dependencies, build MediaPipe, build cpp example applications, and then invoke those applications to use the realtime webcam or a movie file -- but not how to just *process a single image*.

It feels to me like this _should be_ as easy as doing `pip install mediapipe`, selecting your model, and passing it an image. 

This is possible now but only with the pose-tracking Python example. But it's not completely trivial (meaning, "I have failed so far") to extend that example to the other models. Although the Python code for that pose-tracking example model is specific to pose-tracking in only three places (the path to the compiled protobuf file, and the names of the input and output streams), the mediapipe pip package does not contain compiled protobuf files for all the other models MediaPipe supports.

I get it. I do understand that the intended focus of MediaPipe may be realtime continuous execution as a native library. But I'm suggesting it would still be very helpful if the library also supported being installed as a python package (like the rest of the data science ecosystem) and easily used for processing individual files. This is a better starting point than installing Bazel, figuring out cpp code, figuring ou how to feed an image into a stream interface, etc..

**Comment by jiuqiant** [comment]
MediaPipe Python package is available at https://pypi.org/project/mediapipe/. As you said, it now only supports the upper body pose tracking and the other models are not available. We are going to release more solution APIs in Q4. Will keep you updated.

**Comment by jiuqiant** [comment]
MediaPipe Python package is available at https://pypi.org/project/mediapipe/. As you said, it now only has upper body pose tracking and the other examples are not available. We are going to release more solution APIs in Q4. Will keep you updated.

**Comment by algal** [comment]
Thanks, I am delighted to hear this!

**Comment by iPsych** [comment]
@jiuqiant Hello, is there any way to run facemesh in python now?

**Comment by jiuqiant** [comment]
> @jiuqiant Hello, is there any way to run facemesh in python now?

Facemesh Python API is not released yet. We are going to release more solution APIs in Q4. Will keep you updated.

**Comment by jiuqiant** [comment]
Released more solution apis in v0.8.0. See https://github.com/google/mediapipe#mediapipe-in-python and https://pypi.org/project/mediapipe/.
