### ISSUE TITLE
Questions about ComputeHistogram in autoflip

### ISSUE THREAD

**Issue by YaqiLYU** [google/mediapipe#1097]
[https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/calculators/shot_boundary_calculator.cc](url)

`void ShotBoundaryCalculator::ComputeHistogram(const cv::Mat& image,
                                              cv::Mat* image_histogram) {
  cv::Mat equalized_image;
  cv::cvtColor(image.clone(), equalized_image, cv::COLOR_RGB2GRAY);

  double min, max;
  cv::minMaxLoc(equalized_image, &min, &max);

  if (options_.equalize_histogram()) {
    cv::equalizeHist(equalized_image, equalized_image);
  }

  cv::calcHist(&image, 1, kHistogramChannels, cv::Mat(), *image_histogram, 2,
               kHistogramBinNum, kHistogramRange, true, false);
}`

1. Three funcs, i.e. cvtColor, minMaxLoc and equalizeHist, seem no work in this function. Isn't as expected?
2. The kHistogramChannels of calcHist is set to {0, 1, 2}, but the dims of calcHist is 2. Why? Should the dims be set to 3?

**Comment by ndimension** [comment]
Hi @YaqiLYU, I'd recommend you switch to the shot boundary detection calculator that uses the TransNetV2 model as shown here:
https://github.com/googleinterns/intern-for-design/tree/master/autoflip_integrated_calculators

This deep model based shot boundary detector has improved performance over the color histogram method linked above.

-Nathan Frey

**Comment by sgowroji** [comment]
Hi @YaqiLYU, Please go through the above [comment](https://github.com/google/mediapipe/issues/1097#issuecomment-849194620).  Now we are closing this issue, Feel free to reopen if your query is relevant. Thanks!
