### ISSUE TITLE
BlazePose 3D points?

### ISSUE THREAD

**Issue by vpenades** [google/mediapipe#1099]
I've been using BlazePose for a while now...  and I've noticed the model outputs 4 float values per landmark.

At first I used to think that the first 2 floats where the XY coordinates....  but by plotting the XYZ coordinates using the first three values, I'n noticed there's some kind of 3Dish support, at lest with the joints that represent the torso and limbs.

Does it mean that BlazePose outputs (limited) 3D landmarks?

**Comment by BetaPundit** [comment]
In my opinion, the 3rd value is the confidence score of each key point.
Not sure though.

**Comment by mgyong** [comment]
Yes there are 4 float values per landmark (x, y, z, visibility). As of 9 Sept 2020, z value is not accurate and should not be used in production.

**Comment by vpenades** [comment]
@mgyong That's very good to know.

Although you recomend not to use it for production, I need to know, in a broad way, the general direction the body is poiting at. Specially, to know if the body is looking to the right or to the left, so most probably, with the current accuracy I can work something.

Thanks a lot, great work!
