### ISSUE TITLE
will original model model be public?

### ISSUE THREAD

**Issue by gungui98** [google/mediapipe#11]
Hi, I wonder if the original model (before converted to tflite to inference on mobile devices) along with it's training code will be open source or not?

**Comment by mgyong** [comment]
@gungui98 We are releasing only the tflite models . The object detection example training code is open sourced at https://github.com/tensorflow/models/tree/master/research/object_detection

All the other examples with models (eg. Hand segmentation, face detection) will not be open sourced. However, you can use the existing models with the current MediaPipe calculators and graphs. We hope the examples allow you to understand how to create calculators and graphs with your own models.
