### ISSUE TITLE
Segfault from libjpeg_turbo

### ISSUE THREAD

**Issue by jinuhwang** [google/mediapipe#1100]
Hi, I was trying out the `opencv_image_encoder_calculator` on Linux and experienced SEGFALUT while encoding the `cv::mat` frames to jpeg image.

I spent some time debugging, and it seems the `JPEG_LIB_VERSION` of the `libjpeg_turbo` is set to 6.2 instead of 8.0.
Which part of the code is responsible for generating the `Build.bazel` under `bazel-bin/external/libjpeg_turbo` in the first place? 

FYI, the `mediapipe/calculators/image:opencv_image_encoder_calculator_test` passes without any errors.

**Comment by jiuqiant** [comment]
MediaPipe gets libjpeg from tensorflow. It's set in the tensorflow repo:
https://github.com/tensorflow/tensorflow/blob/c03674d99ba8b7d38c6c92b2eee66b3d1221d627/third_party/jpeg/BUILD.bazel#L516

**Comment by jinuhwang** [comment]
I see. Thank you for your help. I'll look into it more.
