### ISSUE TITLE
Pose landmarks type from mediapipe python package

### ISSUE THREAD

**Issue by HamedehJ** [google/mediapipe#1101]
Hello,
I'm using the the pose estimation in mediapipe python package and I would like to get other outputs as the confidence score and  the types of landmarks instead of the ids (like nose, left shoulder, right shoulder, ...). But I can't figure it out where these output are defined and how to change the code to get them.

Thanks a lot,
Hamedeh

**Comment by jiuqiant** [comment]
After getting the pose landmark list, you can manually convert those 25 landmarks to joint points by index for now. See https://github.com/google/mediapipe/blob/c0124fb83c667917c7bf6a84f442a0136e8f2cf7/docs/images/mobile/pose_tracking_upper_body_landmarks.png for details.

The pose graph doesn't output the confidence score. To achieve this, the graph config needs to be modified. 
https://github.com/google/mediapipe/blob/c0124fb83c667917c7bf6a84f442a0136e8f2cf7/mediapipe/graphs/pose_tracking/upper_body_pose_tracking_cpu.pbtxt#L6

**Comment by HamedehJ** [comment]
Thanks a lot! 
However the left and right landmarks that I get are swapped comparing to your image.
Also could you please help me find what corresponds exactly to the "_InFrameLikelihood_"  to add in the graph? I can't find it in the package. I checked also this file "_pose_landmark_upper_body_cpu.pbtxt_" but nothing there.

Thanks for your help.

**Comment by jiuqiant** [comment]
Whoops. We need to flip the input image. The graph is for front camera only, and without it, the image looks reversed (opposite of looking into a mirror).

To fix this, go to your site-packages/mediapipe/examples/python/upper_body_pose_tracker.py and do the following changes:

```
--- a/mediapipe/examples/python/upper_body_pose_tracker.py
+++ b/mediapipe/examples/python/upper_body_pose_tracker.py
@@ -123,7 +123,7 @@ class UpperBodyPoseTracker:
       else:
         input_frame = cv2.imread(input_file)[:, :, ::-1]

-    pose_landmarks, annotated_image = self._run_graph(input_frame)
+    pose_landmarks, annotated_image = self._run_graph(cv2.flip(input_frame, 1))
     if output_file:
       cv2.imwrite(output_file, annotated_image[:, :, ::-1])
     return pose_landmarks, annotated_image
@@ -150,7 +150,7 @@ class UpperBodyPoseTracker:
       success, input_frame = cap.read()
       if not success:
         break
-      input_frame = cv2.cvtColor(input_frame, cv2.COLOR_BGR2RGB)
+      input_frame = cv2.cvtColor(cv2.flip(input_frame, 1), cv2.COLOR_BGR2RGB)
       input_frame.flags.writeable = False
       _, output_frame = self._run_graph(input_frame)
       cv2.imshow('MediaPipe upper body pose tracker',
```

**Comment by jiuqiant** [comment]
> Thanks a lot!
> However the left and right landmarks that I get are swapped comparing to your image.
> Also could you please help me find what corresponds exactly to the "_InFrameLikelihood_" to add in the graph? I can't find it in the package. I checked also this file "_pose_landmark_upper_body_cpu.pbtxt_" but nothing there.

Note that the landmarks are marked from the perspective of the person in the image rather than the viewer of the image. I think that's why you think the left and right landmarks are swapped.
