### ISSUE TITLE
compile error: GLES3/gl32.h: No such file or directory

### ISSUE THREAD

**Issue by piaomiaoju** [google/mediapipe#1105]
ubuntu 16.04
./mediapipe/gpu/gl_base.h:69:24: fatal error: GLES3/gl32.h: No such file or directory

**Comment by jiuqiant** [comment]
How do you install mediapipe? What's your build command?

Seems like you use GPU, do you follow https://google.github.io/mediapipe/getting_started/gpu_support.html#opengl-es-setup-on-linux-desktop to setup opengl on your local machine?

**Comment by sgowroji** [comment]
Closing this issue as there was not significant update from the reporter.
