### ISSUE TITLE
Face Filters using Mediapipe Face Mesh

### ISSUE THREAD

**Issue by Gauraviiitian** [google/mediapipe#1106]
Currently I'm trying to implement a Facial filter (snapchat like) using mediapipe facemesh. I thought of doing it in two steps - 
1. Get the coordinates of concerned landmark for the specific filter (e.g. to Augment a crown we'll need forehead's landmarks).
2. Write a calculator to superimpose the filter using the coordinates from previous step.

Now I could see the coordinates of landmarks, facemesh example's subgraph FaceRendererGpu and trying to modify it for superimposing the filter, But it's getting quite hard to implement.

Is there a better way of implementing these kinds of filters? How can I divide the second step in terms of coding, since I'm not expert in C++?

**Comment by mgyong** [comment]
We will be releasing in end Sept a 3D face system to Face Mesh that will help with (2). Pls just wait for that

**Comment by Gauraviiitian** [comment]
Thanks @mgyong I'll be looking forward to that.

**Comment by mgyong** [comment]
MediaPipe Face Transform https://github.com/google/mediapipe/releases/tag/v0.7.11

**Comment by rakoo04** [comment]
Great release indeed @mgyong . But I want to make a similar solution for web. is there any plans to release for this?

**Comment by Gauraviiitian** [comment]
Nice one @mgyong , I'm right on it, although I thought I got pretty much control over the keypoint's coordinates. I'll try it and hopefully get it done. Thanks a lot!

**Comment by Gauraviiitian** [comment]
Hey @mgyong the Face Effect is rendered for a single face, Is there a quick modification to make it work for multiple faces?

**Comment by MyChocer** [comment]
@Gauraviiitian Have you find some solutions for rendering multiple faces in the Face Effect application?

**Comment by Gauraviiitian** [comment]
I didn't use their face effect application for my use case, you can take face mesh for multiple faces and then implement your calculator for rendering face effects... I did the same.

**Comment by MyChocer** [comment]
@Gauraviiitian Would you mind sharing the graph and calculator? I would like to do a quick test on it.

**Comment by Gauraviiitian** [comment]
Hii @MyChocer, I cannot share the calculator due to confidentiality policy with my company since the project is affiliated for them. Although I can share some key notes for the same - 
Break down the project into two parts - 

1. Finding the landmark points (for face detection or facemesh) ie their absolute coordiantes.
2. Now rendering any image or filter with the help of landmarks detected.

First one is quite simple using calculations since we already have normalized landmarks, you just need to know which landmark index corresponds to which point on facemesh or face landmark.
Second one is a bit tricky as we need to render the filter using landmark points and there are two ways of doing this - 
1. Using OpenGL which uses GPU buffer Image form, I didn't use it since it was quite complex.
2. Using OpenCV which uses CPU Image form, I used this one effectively for my project.

To use opencv first convert input stream to CPU using GpuBufferToImageFrameCalculator and then you can easily load and use opencv for rendering and performing any kind of filter.
you can also traverse through all of the pixels and set values as per your filter (the naive method).

Hope this helps! I'm still to learn a lot things about mediapipe framework.
