### ISSUE TITLE
Can we run mediapipe on mobile browser?

### ISSUE THREAD

**Issue by hidenny** [google/mediapipe#1107]
Is it possible to run mediapipe on safari on iOS or chrome on Android?

**Comment by mhays-google** [comment]
I'm doing only a limited amount of testing on mobile devices, but in general I'm not thwarting its use on iOS or Android, and we have demoed these things on these devices.  I've also specifically made viz.mediapipe.dev responsive to take advantage of the mobile footprint.

**Comment by bfalchuk** [comment]
Hi @mhays-google ; similar question to you all ; i'd also like to build a mediapipe hand tracking webapp and access it from the mobile browser (as opposed to building native iOS or Android app).
Are there examples where this kind of access works? I'm not seeing them. When i test the codepen webapps (notably https://codepen.io/mediapipe/pen/RwGWYJw ) via Chrome on Android it does not seem to work. (the spinner never resolves).

**Comment by hyperparameters** [comment]
i would also like to know the development of mediapipe models on mobile webbrowser. 
@bfalchuk did you had any progress on this? TIA

**Comment by mhays-google** [comment]
It should work on Chrome mobile.  We're looking to make it workable on iOS,
and that work lands later this year.  There may be some configurations
which are problematic, and we're always looking for specific configurations
that do not work.

**Comment by basicvisual** [comment]
Hi @mhays-google , i tried to run `code-pen` on chrome app in ios . As mentioned above , the spinner never resolves. I was wondering if there are some additional settings that need to be done or changed

**Comment by Matokosp** [comment]
The demo on codepen is running on Safari, Mozilla and Chrome on my iPhone, but I can't make it work with my code. Is there something about the permissions that prevents media pipe from rendering the video ?

**Comment by Atem1995** [comment]
> The demo on codepen is running on Safari, Mozilla and Chrome on my iPhone, but I can't make it work with my code. Is there something about the permissions that prevents media pipe from rendering the video ?

@Matokosp I got the same problem.
