### ISSUE TITLE
Get buffer from TextureFrame

### ISSUE THREAD

**Issue by quarriedstone** [google/mediapipe#1111]
Hello. My idea is the following. I have built AAR library for FaceMesh. Then, I have added CutomeTextureConsumer that overrides onNewFrame. On each new frame, I want to get buffer from TextureFrame. How can I achieve this? 
Thanks!

**Comment by eknight7** [comment]
Hi @quarriedstone, sorry for the delayed response.
The FrameProcessor class is a good example of how to use textures https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/FrameProcessor.java.

Also, this may be helpful for you: https://github.com/google/mediapipe/issues/475#issuecomment-593785593

Closing this issue for now. Please feel free to re-open if the question is still relevant. Thank you.
