### ISSUE TITLE
Problem with camera running hand tracking CPU

### ISSUE THREAD

**Issue by dgrnd4** [google/mediapipe#1114]
I20200912 20:10:17.567543 17949 demo_run_graph_main.cc:53] Initialize the calculator graph.
I20200912 20:10:17.571471 17949 demo_run_graph_main.cc:57] Initialize the camera or load the video.
E20200912 20:10:17.637492 17949 demo_run_graph_main.cc:146] Failed to run the graph: ; capture.isOpened()(mediapipe/examples/desktop/demo_run_graph_main.cc:65) 

Read about a lot of people who had this problem but i didn't find the solution. I want that my webcam start, doing
the hand tracking: i want to use as input video the live video of course

**Comment by jiuqiant** [comment]
As I mentioned in https://github.com/google/mediapipe/issues/1028#issuecomment-677769601, MediaPipe relies on OpenCV VideoCapture for getting webcam inputs. If `capture.isOpened()` fails, you probably can try OpenCV without MediaPipe to verify whether it's an OpenCV issue or not. Moreover, if you use it in WSL, it's very likely that WSL doesn't support webcam. See https://github.com/google/mediapipe/issues/149.

**Comment by dgrnd4** [comment]
@jiuqiant many thanks. i am now trying to do another thing. 

I have a video an i want to do handtracking in this video. Could you please tell me which variable should i change with the path of the video, to start the video insteand of the camera?
I think that the file is **demo_run_graph_main.cc** right? The variable should be the array kInputStream[]="input_video"; 
is it right? should i change "input_video" with the path of the video that i want to check?

**Comment by jiuqiant** [comment]
See https://github.com/google/mediapipe/issues/707#issuecomment-625945596

**Comment by jiuqiant** [comment]
No graph change is needed. See https://github.com/google/mediapipe/issues/707#issuecomment-625945596

**Comment by dgrnd4** [comment]
many thanks, i am trying with :
**GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_cpu     --calculator_graph_config_file=mediapipe/graphs/hand_tracking/multi_hand_tracking_desktop_live.pbtxt     --input_video_path=/home/diego/Scrivania/tesi/videoTesi/IMG_1632.mp4     --output_video_path=/home/diego/Scrivania/tesi/videoTesi/output.mp4    
**
but i still have this error:
**I20200916 10:42:31.744997  9271 demo_run_graph_main.cc:53] Initialize the calculator graph.
I20200916 10:42:31.748589  9271 demo_run_graph_main.cc:57] Initialize the camera or load the video.
E20200916 10:42:31.810920  9271 demo_run_graph_main.cc:146] Failed to run the graph: ; capture.isOpened()(mediapipe/examples/desktop/demo_run_graph_main.cc:65)**

**Comment by dgrnd4** [comment]
seems like it is not taking the input_video_path because still showing the camera error i think in line 65.

However please really please let me know if you have a solution. 
Many thanks, i really need it!!!

**Comment by jiuqiant** [comment]
As I mentioned in https://github.com/google/mediapipe/issues/1114#issuecomment-692173177, it's more like an OpenCV issue. Can you write some cpp code to reproduce it without MediaPipe?

**Comment by dgrnd4** [comment]
Honestly it's crazy, because if i run those two files (PYTHON) : 

[inputvideo.txt](https://github.com/google/mediapipe/files/5242286/inputvideo.txt)
[livestream.txt](https://github.com/google/mediapipe/files/5242287/livestream.txt)

(of course changing the format, ".py" instead of ".txt" becasue of problem with the uploading) those two python files work well.

Now, if i try with those 2 file (C++) (i'm uploading as ".txt" but they are actually ".cpp"):
[aa.txt](https://github.com/google/mediapipe/files/5242293/aa.txt)
[a.txt](https://github.com/google/mediapipe/files/5242294/a.txt)

i have this problem for both (for camera as input, and for video as input):
**/tmp/ccmCNTAW.o: nella funzione "main":
a.cpp:(.text+0x38): riferimento non definito a "cv::VideoCapture::VideoCapture(int)"
a.cpp:(.text+0x47): riferimento non definito a "cv::VideoCapture::isOpened() const"
a.cpp:(.text+0xa0): riferimento non definito a "cv::VideoCapture::get(int) const"
a.cpp:(.text+0xc0): riferimento non definito a "cv::VideoCapture::get(int) const"
a.cpp:(.text+0x1ad): riferimento non definito a "cv::namedWindow(cv::String const&, int)"
a.cpp:(.text+0x1f7): riferimento non definito a "cv::VideoCapture::read(cv::_OutputArray const&)"
a.cpp:(.text+0x2a0): riferimento non definito a "cv::imshow(cv::String const&, cv::_InputArray const&)"
a.cpp:(.text+0x2c8): riferimento non definito a "cv::waitKey(int)"
a.cpp:(.text+0x340): riferimento non definito a "cv::VideoCapture::~VideoCapture()"
a.cpp:(.text+0x3f5): riferimento non definito a "cv::VideoCapture::~VideoCapture()"
/tmp/ccmCNTAW.o: nella funzione "cv::String::~String()":
a.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x14): riferimento non definito a "cv::String::deallocate()"
/tmp/ccmCNTAW.o: nella funzione "cv::String::operator=(cv::String const&)":
a.cpp:(.text._ZN2cv6StringaSERKS0_[_ZN2cv6StringaSERKS0_]+0x28): riferimento non definito a "cv::String::deallocate()"
/tmp/ccmCNTAW.o: nella funzione "cv::Mat::~Mat()":
a.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x39): riferimento non definito a "cv::fastFree(void*)"
/tmp/ccmCNTAW.o: nella funzione "cv::Mat::release()":
a.cpp:(.text._ZN2cv3Mat7releaseEv[_ZN2cv3Mat7releaseEv]+0x4b): riferimento non definito a "cv::Mat::deallocate()"
/tmp/ccmCNTAW.o: nella funzione "cv::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)":
a.cpp:(.text._ZN2cv6StringC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN2cv6StringC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x69): riferimento non definito a "cv::String::allocate(unsigned long)"
collect2: error: ld returned 1 exit status**


I think that is a problem of reference about the library cv when i do the #include of libraries. 
Do you know something about this error? I was looking on internet but nothing appear...

**Comment by dgrnd4** [comment]
But i'm still having the problem using docker and trying to start the multi_hand_tracking so my problem is not solved but i find out that isn't a openCV problem

**Comment by dgrnd4** [comment]
I am not finding the solution...honestly i don't know how to solve it.

@jiuqiant if you have any ideas please let me know

**Comment by jiuqiant** [comment]
Hi, when you run multi_hand_tracking in docker, do you try live input or file input. I guess the live input may not work in docker.

**Comment by dgrnd4** [comment]
what do you mean with "do you try live input or file input" ?
Till now is what he have tried to do: try live input or multi hand tracking with a file video in input

Do you think that it doesn't work with Docker?

**Comment by dgrnd4** [comment]
i had different problems but at the end i find out how to start the multi_hand_tracking (not using docker, but from terminal, using ubuntu)

i build the multi_hand_tracking and runned it, giving input and having output

The commands used are:

- export GLOG_logtostderr=1
- bazel-3.4.0 run --define MEDIAPIPE_DISABLE_GPU=1  mediapipe/examples/desktop/hello_world:hello_world
- bazel-3.4.0 build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu
- GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_cpu     --calculator_graph_config_file=mediapipe/graphs/hand_tracking/multi_hand_tracking_desktop_live.pbtxt     --input_video_path=/home/diego/Scrivania/tesi/videoTesi/IMG_1635.MOV     --output_video_path=/home/diego/Scrivania/tesi/videoTesi/output.MOV

Many thanks


P.S. the hello_world doesn't work using bazel 3.5.0 but it's a must use the 3.4.0 and maybe other, but was the only one that i tried
