### ISSUE TITLE
Python API for Upper Body Pose Tracking - Strange Behavior

### ISSUE THREAD

**Issue by sourabh03agr** [google/mediapipe#1117]
Hi,

I am trying out the python API for upper body pose tracking, and seeing some strange behaviours where 
1. Inference fails for some images but if done again, it gives reasonable results
2. See a failure on some images resulting in program abortion

Please find the images and code below:
[error_repo.zip](https://github.com/google/mediapipe/files/5217786/error_repo.zip)

    try:
        pose_landmarks, _ = pose_tracker.run(input_frame=im_array)

        # For image named retry.jpg, it fails here but passes when the same computation is done again in Except block
        # Error msg: *** AttributeError: 'NoneType' object has no attribute 'landmark'

    except:
        pose_landmarks, _ = pose_tracker.run(input_frame=im_array)

        # For image named fail.jpg, it fails here too with below error message. 
        # terminate called after throwing an instance of 'cv::Exception'
        # what():  OpenCV(3.4.11-dev) /tmp/bazel_build/opencv/modules/imgproc/src/drawing.cpp:1783: error: (-215:Assertion failed) 
        # 0 < thickness && thickness <= MAX_THICKNESS in function 'line'
        # Aborted (core dumped)

**Comment by kelvinqin** [comment]
I found the same error:

**Comment by kelvinqin** [comment]
Found the same error in some case:
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.11-dev) /tmp/bazel_bterminate called after throwing an instance of 'cv::Exception'

**Comment by sourabh03agr** [comment]
I guess I figured what's happening. Since the inferences are done sequentially without re-initializing the pose tracker, it is using bounding box infered from keypoints as the crop for next image. Now, these images are from different video sequences, invalidating the implicitly assumed tracking hypothesis, resulting in strange behaviors. 

Although, the openCV error indicates we potentially have division by 0 somewhere?

**Comment by jiuqiant** [comment]
It should be fixed in the v0.8, where we support both static image mode and video mode.
