### ISSUE TITLE
Android c++ interface

### ISSUE THREAD

**Issue by Source666** [google/mediapipe#1119]
Thank you very much for the open source of the mediapipe series of algorithms by the Google team. I wonder if BlazePose will provide the Android ndk c++ interface, similar to the calling method of the desktop version of the python interface. The coordinate information can be obtained by calling the interface. For example, so libraries and header files.

**Comment by iseeit777** [comment]
What does that all mean

**Comment by sgowroji** [comment]
Hi @Source666, We have very clear documentation of MediaPipe solutions with [Android platform ](https://google.github.io/mediapipe/getting_started/android.html#mediapipe-on-android). Have a look at here and let us know if your use case is different.
