### ISSUE TITLE
Ubuntu helloword failure

### ISSUE THREAD

**Issue by harry19902002** [google/mediapipe#112]
Ubuntu 18.04 
run this step:
`$ bazel run --define MEDIAPIPE_IDSABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world`

ERROR: /home/harry/project/mediapipe/mediapipe/gpu/BUILD:228:1: C++ compilation of rule '//mediapipe/gpu:gpu_buffer_format' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 59 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./mediapipe/gpu/gpu_buffer_format.h:23:0,
                 from mediapipe/gpu/gpu_buffer_format.cc:15:
./mediapipe/gpu/gl_base.h:57:10: fatal error: EGL/egl.h: No such file or directory
 #include <EGL/egl.h>
          ^~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 77.959s, Critical Path: 48.24s
INFO: 401 processes: 401 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by jiuqiant** [comment]
Hi you have a typo in your bazel command. Please try `MEDIAPIPE_DISABLE_GPU` rather than `MEDIAPIPE_IDSABLE_GPU`. The right command is 
```
bazel run --define MEDIAPIPE_DISABLE_GPU =1 mediapipe/examples/desktop/hello_world:hello_world
```

**Comment by harry19902002** [comment]
That is the problem. Thanks a lot!
