### ISSUE TITLE
[Android] How can I read model(.tflite file) in storage?

### ISSUE THREAD

**Issue by thkim0118** [google/mediapipe#1120]
I'm currently decreasing the size of the app. 
So I'm going to use the model file instead of putting it in the assets folder.
I think I need to run it after I import the file from the internal storage, but I don't know where to modify it.

**I'd appreciate any help thanks!**

**Comment by thkim0118** [comment]
I solved it!

**Comment by ReqWrecker** [comment]
Can you please elaborate, how did you solve this one.
Thanks:)
