### ISSUE TITLE
Using 'MaskOverlayCalculator' for alpha blending(mixing) two frames in android

### ISSUE THREAD

**Issue by anilsathyan7** [google/mediapipe#1123]
The hair_segmentation demo in the mediapipe demonstrates the basic pipeline for video segmentation using tflite. Now, how can we  load a **single image** from assets to gpu memory inside the graph and perform alpha blending with the image as background on the video stream. It looks like '**MaskOverlayCalculator**' node can accomplish this task; but it's documentation does not seem to have a 'usage example' like 'RecolorCalculator'.  Also it seems that there is no demo application showing how it works in android(neither combining an  image with video).

Should we create multiple inputs or just load the image once as a side packet?
How should we **modify the basic demo application** so that it loads the background image once from assets into gpu memory and carries out the alpha blending using the mask continously? 
(I would like to avoid explicit java code or cpu memory for the sake of performance)

I hope to achieve the results in this [demo app](https://towardsdatascience.com/custom-calculators-in-mediapipe-5a245901d595). But since my model is large i want to reduce most of the memory copies between cpu and gpu for real-time performance.

**Comment by mcclanahoochie** [comment]
the mask overlay calculator is a good way to blend two images.
the inputs are either a MASK (image) or a CONST_MASK (float). 
a typical use case is as follows:
```

**Comment by anilsathyan7** [comment]
I figured out that part myself; but can we load additional image or video besides the main video stream into the pipeliene, without using additonal c++ code  i.e within gpu itself?? If so, can you direct me to an example for the same??

**Comment by mcclanahoochie** [comment]
Additional streams can be added to any graph, it just needs to be specified at the top of the graph.
```
input_stream: "input_video"
input_stream: "input_video_2"
```
 Then use something like 
```
graph->AddPacketToInputStream("input_video", data_packet1)...
graph->AddPacketToInputStream("input_video_2", data_packet2)...
``` 
to send in data to each stream.

If "input_video" is the camera,  "input_video_2" is your static image, then you could duplicate the image packet like this
```
node {
  calculator: "PacketClonerCalculator"
  input_stream: "input_video_2"
  input_stream: "input_video"  # Current frame drives output.
  output_stream: "input_video_2_cloned"
  input_stream_handler {
    input_stream_handler: "ImmediateInputStreamHandler"
  }
}
```

**Comment by sgowroji** [comment]
Assuming the above comments resolved your query. We are closing this issue now. Please feel free to reach us back if you still have any relevant query from the above.
