### ISSUE TITLE
App Build Successful but App crashes on Mobile while opening

### ISSUE THREAD

**Issue by Gauraviiitian** [google/mediapipe#1124]
I tried building a greyscale filter for mobile. The application build successfully but doesn't even open and crashes straightaway.
My graph is
`node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "throttled_input_video"
  output_stream: "input_video_cpu"
}

node {
  calculator: "CustomCalculator"
  input_stream: "IMAGE:input_video_cpu"
  output_stream: "IMAGE:output_video_cpu"
}

node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "output_video_cpu"
  output_stream: "output_video"
}`

And My Calculator

`#include "absl/strings/str_cat.h"
#include "mediapipe/framework/calculator_framework.h"
#include "mediapipe/framework/deps/file_path.h"
#include "mediapipe/framework/formats/image_frame.h"
#include "mediapipe/framework/formats/image_frame_opencv.h"
#include "mediapipe/framework/formats/matrix.h"
#include "mediapipe/framework/port/opencv_core_inc.h"
#include "mediapipe/framework/port/opencv_imgproc_inc.h"
#include "mediapipe/framework/port/opencv_imgcodecs_inc.h"
#include "mediapipe/framework/port/ret_check.h"
#include "mediapipe/framework/port/status.h"
#include "mediapipe/util/resource_util.h"
#include <iostream>
#include <vector>

//calculator CustomCalculator
namespace mediapipe {

class CustomCalculator : public CalculatorBase {
public:

    CustomCalculator() = default;
    ~CustomCalculator() override = default;
    //CustomCalculator() : initialized_(false){}

  static ::mediapipe::Status GetContract(CalculatorContract* cc);

  ::mediapipe::Status Open(CalculatorContext* cc) override;
  ::mediapipe::Status Process(CalculatorContext* cc) override;
  };

  REGISTER_CALCULATOR(CustomCalculator);

::mediapipe::Status CustomCalculator::GetContract (CalculatorContract *cc){

    cc->Inputs().Tag("IMAGE").Set<ImageFrame>();
    cc->Outputs().Tag("IMAGE").Set<ImageFrame>();

    return ::mediapipe::OkStatus();

}

::mediapipe::Status CustomCalculator::Open(CalculatorContext* cc) {

    return ::mediapipe::OkStatus();
}

::mediapipe::Status CustomCalculator::Process(CalculatorContext* cc) {

    const auto& input_img = cc->Inputs().Tag("IMAGE").Get<ImageFrame>();
    cv::Mat input_mat = formats::MatView(&input_img);

    // Changing channels of background from BGR to RGBA using opencv
    // The default color format in OpenCV is often referred to as as RGB but actually 
    // it is actually BGR ( the bytes are reserved ), Hence we need to convert it to RGBA.
    cv::cvtColor(background, background, cv::COLOR_BGR2RGB);
    cv::cvtColor(background, background, cv::COLOR_RGB2RGBA);
    cv::resize(background, background, input_mat.size());

    // Let's tweak the input stream to Grayscale
    cv::cvtColor(input_mat, input_mat, cv::COLOR_BGR2GRAY);

    std::unique_ptr<ImageFrame> output_frame(
        new ImageFrame(input_img.Format(), input_img.Width(), input_img.Height()));

    cv::Mat output_mat = formats::MatView(output_frame.get());

    // Just passing the input_mat in GRAYscale to see if it works
    input_mat.copyTo(output_mat);
    cc->Outputs().Tag("IMAGE").Add(output_frame.release(), cc->InputTimestamp());

    return ::mediapipe::OkStatus();

    }

// after defining calculator class, we need to register it with a macro invocation 
// REGISTER_CALCULATOR(calculator_class_name).
REGISTER_CALCULATOR(::mediapipe::CustomCalculator);
}
 //end namespace`

**Comment by Gauraviiitian** [comment]
Actually the error was occuring because I was trying to build it on GPU, in fact we can't perform opencv operations on GPU and seemingly it was absolutely fine with CPU version. I'm closing the issue.

**Comment by Nvelu048** [comment]
@Gauraviiitian 

Did your custom calculator worked ? 

Can you share the working calculator code
