### ISSUE TITLE
Using BlazePose in browser

### ISSUE THREAD

**Issue by visionari-labs** [google/mediapipe#1125]
Hi, I'd like to build a physical training web application using BlazePose since it says its supported on Mediapipe's main page. I also read the official API is still under construction.. Is there any way to start building the web app using BlazePose currently? 

I'm learning more about pose estimation at the moment. Would ml5 posenet be a good option to use for the web app while waiting for the Mediapipe web API to be ready?

**Comment by mgyong** [comment]
@visionari-labs We will be releasing in sept-oct a MP javascript solution API for Upper body BlazePose. I would advise to wait for it

**Comment by mhays-google** [comment]
That's correct.  I'm actually the author.  Soon!

**Comment by aspdev91** [comment]
Thanks for the update @mgyong and @mhays-google! 

Out of curiosity, is there an ETA on full body BlazePose javascript API? Super stoked to try it out!

**Comment by jjeon5** [comment]
@mgyong @mhays-google Was the API released for BlazePose? I could find some introduction materials on the MediaPipe website but wasn't able to find any detailed API as to interfacing with the model. The examples used on the website interfaces with the minified file: https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js. Without a documentation or source code it's quite difficult to use it. To give you some context, I'm trying to use the pose detection solution inside a Web Worker and am encountering errors. Do you suggest I wait for the documentation?
