### ISSUE TITLE
How to use MediaPipe graphs for static images?

### ISSUE THREAD

**Issue by LarryBrinzo** [google/mediapipe#1126]
How can I use MediaPipe facemesh graph for static images? Instead of passing video_input, we will be passing a bitmap and getting an output bitmap.

**Comment by mcclanahoochie** [comment]
the [iris example](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/iris_tracking/iris_depth_from_image_desktop.cc) shows how to run mediapipe on desktop with a single image.

at a higher level, the difference between processing a video and a frame basically just calling `graph->AddPacketToInputStream` once for an image, instead of each frame for a video

**Comment by LarryBrinzo** [comment]
Thank you so much @mcclanahoochie

**Comment by LarryBrinzo** [comment]
@mcclanahoochie Is there any example for this in Android.

**Comment by mcclanahoochie** [comment]
Sorry there is no example of this, you will need to write custom code, most likely in https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/FrameProcessor.java

**Comment by abiemann** [comment]
> Sorry there is no example of this, you will need to write custom code, most likely in https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/FrameProcessor.java
> 
> This looks somewhat related
> https://github.com/afsaredrisy/MediapipeHandtracking_GPU_Bitmap_Input/tree/master/handtrackinggpu

it looks like FrameProcessor.onNewFrame() is used in that sample code to get an image into the MediaPipe.
There's even a convenient onNewFrame(Bitmap, timestamp) method, that triggers mediapipeGraph.addConsumablePacketToInputStream()

**Comment by Nvelu048** [comment]
@mcclanahoochie 

How to specify the path 

i have an image named face.jpg and it is in Downloads Directory

but while running it throws Can't Find the file

```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_depth_from_image_desktop \
  --input_image_path=~/Downloads/face.jpg  --output_image_path=~/Downloads
```

```
Failed to run the graph: ; Can't find file: Downloads/face.jpg
```

What to do? Need help

**Comment by mcclanahoochie** [comment]
Please try using the full image path:
`--input_image_path=/full/path/to/Downaloads/face.jpg`
`--output_image_path=/full/path/to/Downaloads`

**Comment by Nvelu048** [comment]
@mcclanahoochie 

I tried and received following log:

```
I20210202 22:42:05.893826 432823744 iris_depth_from_image_desktop.cc:136] Initialize the calculator graph.
I20210202 22:42:05.900424 432823744 iris_depth_from_image_desktop.cc:59] Load the image.
I20210202 22:42:05.901604 432823744 iris_depth_from_image_desktop.cc:63] Start running the calculator graph.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
E20210202 22:42:06.016189 432823744 iris_depth_from_image_desktop.cc:156] Failed to run the graph: Failed to get packet from output stream 'left_iris_depth_mm'.
```

What to do
