### ISSUE TITLE
what is '-nolaunch_app' ??

### ISSUE THREAD

**Issue by e99** [google/mediapipe#1127]
i didn't change any code in mediapipe except escape sequence with python ( \ -> \\\ ). 

but i meet some errors about bazel command.

Waiting for target device...
Invoking mobile-install...
Command: bazel mobile-install --tool_tag=ijwb:AndroidStudio --device R3CM80NGW2E:tcp:5037 "--adb_arg=-s " --adb_arg=R3CM80NGW2E --adb C:\Users\e99\AppData\Local\Android\Sdk\platform-tools\adb.exe --curses=no --color=yes --progress_in_terminal_title=no -c opt --config=android_arm64 --build_event_binary_file=C:\Users\e99\AppData\Local\Temp\intellij-bep-541aeb0b-64ea-4453-b644-1930e4a46879 --nobuild_event_binary_file_path_conversion -- //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu:objecttrackinggpu --nolaunch_app

Loading: 
Loading: 0 packages loaded
ERROR: Skipping '-nolaunch_app': no such target '//:-nolaunch_app': target '-nolaunch_app' not declared in package '' defined by C:/code/aipro-android-project/mediapipe/BUILD.bazel
WARNING: Target pattern parsing failed.
ERROR: no such target '//:-nolaunch_app': target '-nolaunch_app' not declared in package '' defined by C:/code/aipro-android-project/mediapipe/BUILD.bazel
INFO: Elapsed time: 0.358s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)

================================================================================

ERROR: C:/users/e99/_bazel_e99/ins3axxc/external/ruy/ruy/BUILD:156:11: C++ compilation of rule '@ruy//ruy:tune' failed (Exit 1)
clang: error: no such file or directory: '/w'
clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
clang: error: no such file or directory: '/std:c++14'
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu:objecttrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 199.649s, Critical Path: 42.13s
INFO: 316 processes: 316 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

================================================================================

AndroidStudio: 4.0.1
Platform: Windows 10 10.0
Bazel plugin: 2020.06.25.0.3
Bazel: 3.5.0
Android SDK: 28
NDK: r20

**Comment by jiuqiant** [comment]
As we mentioned in https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows, building MediaPipe Android apps is still not possible on native Windows. We apologize for the inconvenience.
