### ISSUE TITLE
Android example helloworld fails

### ISSUE THREAD

**Issue by akssieg** [google/mediapipe#1128]
I tried bazel command `bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld` but it is giving the following errors: 

`NFO: Build options --cpu, --crosstool_top, --define, and 3 more have changed, discarding analysis cache.
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 21. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]. Bazel will attempt to treat the NDK as if it was r20. This may cause compilation and linkage problems. Please download a supported NDK version.
WARNING: API level 30 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld (31 packages loaded, 9629 targets configured).
INFO: Found 1 target...
INFO: From Generating JavaLite proto_library //mediapipe/framework:mediapipe_options_proto:
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/compiler/java/java_file.cc:230] mediapipe/framework/mediapipe_options.proto: The file's outer class name, "MediapipeOptions", matches the name of one of the types declared inside it when case is ignored. This can cause compilation issues on Windows / MacOS. Please either rename the type or use the java_outer_classname option to specify a different outer class name for the .proto file to be safe.
INFO: From ProtoCompile mediapipe/gpu/gl_surface_sink_calculator.pb.h:
bazel-out/android-arm64-v8a-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/framework/calculator_profile.pb.h:
bazel-out/android-arm64-v8a-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/framework/calculator.pb.h:
bazel-out/android-arm64-v8a-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/framework/tool/calculator_graph_template.pb.h:
bazel-out/android-arm64-v8a-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/gpu/gl_context_options.pb.h:
bazel-out/android-arm64-v8a-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/internal/callback_packet_calculator.pb.h:
bazel-out/android-arm64-v8a-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
ERROR: /home/aks/Documents/Reading/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:24:16: Validating proguard configuration failed (Exit 127) proguard_whitelister failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/jdk/proguard_whitelister --path mediapipe/java/com/google/mediapipe/framework/proguard.pgcfg --output ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/env: 'python': No such file or directory
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.606s, Critical Path: 3.06s
INFO: 92 processes: 89 linux-sandbox, 3 worker.
FAILED: Build did NOT complete successfully`

I have the python already available in the /usr/bin/env.

Any help would be greatly appreciated.

**Comment by jiuqiant** [comment]
You also can specify directly the PYTHON_BIN_PATH variable in the build command. See https://google.github.io/mediapipe/getting_started/troubleshooting.html#missing-python-binary-path

**Comment by AhmedEmadEldinHussin** [comment]
still the problem is exist

**Comment by wingdi** [comment]
> You also can specify directly the PYTHON_BIN_PATH variable in the build command. See https://google.github.io/mediapipe/getting_started/troubleshooting.html#missing-python-binary-path

I have same problem, but this solution not work for me.
