### ISSUE TITLE
Some Questions about  BlazePose

### ISSUE THREAD

**Issue by Allwillcome** [google/mediapipe#1129]
1.    I can easily move my results and algorithms from my computer to an Android app, right? I'm not familiar with the operation of the android
2.    how to implement the statistical fitness movement，how to count squat？
![推出 BlazePose：实现设备端实时人体姿态追踪](https://user-images.githubusercontent.com/35840764/93693119-1786d080-fb2e-11ea-877b-0e35af3b5cdd.gif)

3.    BlazePose whether can obtain the length of the height of the distance information or the Angle. In the gym, symmetry is more important. we need not only to identify the purpose of action, but we also need to according to the distance Angle to judge whether the movement is correct.

**Comment by ashrvstv** [comment]
hello @Allwillcome are you able to create an android app for the pose tracking ?

**Comment by mgyong** [comment]
@Allwillcome 1) MediaPipe is cross platform and we have many [examples](https://google.github.io/mediapipe/solutions/face_detection) showing you how to use single graph that can run on iOS and android. See this [blog post example](https://developers.googleblog.com/2020/03/alfred-camera-smart-camera-features-using-mediapipe.html) from Alfred company who started to prototype their own graph on desktop and ported it to android fairly quickly

As for (2), this is currently not released by MLKIt yet. It likely will be shortly

**Comment by Allwillcome** [comment]
> hello @Allwillcome are you able to create an android app for the pose tracking?

No，I have not created an android.

**Comment by Allwillcome** [comment]
> @Allwillcome 1) MediaPipe is cross platform and we have many [examples](https://google.github.io/mediapipe/solutions/face_detection) showing you how to use single graph that can run on iOS and android. See this [blog post example](https://developers.googleblog.com/2020/03/alfred-camera-smart-camera-features-using-mediapipe.html) from Alfred company who started to prototype their own graph on desktop and ported it to android fairly quickly
> 
> As for (2), this is currently not released by MLKIt yet. It likely will be shortly

ok, Thanks a lot. But Can the BlazePose get the distance and angle in reality by calibre？

**Comment by sgowroji** [comment]
Hi @Allwillcome, We have updated our documentation and that will help you answer your queries [here](https://google.github.io/mediapipe/solutions/pose.html#pose_world_landmarks). Please go through them and let us know if you still have any specific query from the above context. Thanks!
