### ISSUE TITLE
Bazel Sync failed

### ISSUE THREAD

**Issue by albus-maker** [google/mediapipe#113]
I tried to open new bazel project but it gives sync error. I'm not sure how to deal with it.
I think I read the contents of install.md and followed it correctly.
![temp](https://user-images.githubusercontent.com/55405026/64977016-3249b800-d8d0-11e9-853e-3634006aca37.png)

**Comment by jiuqiant** [comment]
I am wondering if you installed Bazel or not. You need to install Bazel separately and then follow the step 6 of [the instruction](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#setting-up-android-sdk-and-ndk) to tell Android Studio where your Bazel is.

If you do install Bazel, can you give more detailed error message?

**Comment by albus-maker** [comment]
![temp2](https://user-images.githubusercontent.com/55405026/64979715-e568e000-d8d5-11e9-82ad-61b9b2f3812e.png)
i think bazel binary location not found and how to find it.
![temp1](https://user-images.githubusercontent.com/55405026/64979785-0df0da00-d8d6-11e9-82c1-aa7974a64402.png)

**Comment by jiuqiant** [comment]
Do you run this on Windows or Windows Subsystem for Linux (WSL)? Unfortunately, MediaPipe doesn't have Windows support yet. But, if you do it on WSL, you can install Bazel by `$ apt install bazel` and use `$ which bazel` to find the Bazel binary. See [this instruction](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows-subsystem-for-linux-wsl) for more details.

**Comment by albus-maker** [comment]
$ apt install bazel 
give something like that...
 
![temp4](https://user-images.githubusercontent.com/55405026/65013121-63a99e80-d937-11e9-9a5d-4dd88ca634df.png)

$ which bazel 
is not give anything

**Comment by trojan03** [comment]
@albus-maker just type "sudo apt install bazel" instead. This will give you the admin rights

**Comment by albus-maker** [comment]
![temp5](https://user-images.githubusercontent.com/55405026/65038959-c5392f80-d96e-11e9-83a8-ed662b6231c7.png)

**Comment by trojan03** [comment]
@albus-maker sorry, I've forgotten that bazel is not available under apt-get. You have to actually follow the instructions from https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows-subsystem-for-linux-wsl

**Comment by JimReno** [comment]
@albus-maker  simply install bazel on its [realease page](https://github.com/bazelbuild/bazel/releases/tag/0.25.0)(Here is 0.25.0 version, you can switch to other versions.) Download  the `bazel_0.25.0-linux-x86_64.deb` package. Go to the bazel package folder and use command`sudo dpkg -i bazel_0.25.0-linux-x86_64.deb` to install bazel. Then you are ready to go. :)

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
