### ISSUE TITLE
BlazePose and Mediapipe-Hands models/configurations used in the papers

### ISSUE THREAD

**Issue by ThiruSS** [google/mediapipe#1130]
I have been looking for the models corresponding to the features reported in the papers for the implementation of BlazePose and Medipipe Hands to replicate the reported results.

**Papers:**
 * BlazePose: https://arxiv.org/pdf/2006.10204.pdf
 * Mediapipe Hands: https://arxiv.org/pdf/2006.10214.pdf

**BlazePose**
In the section of squeezes are compared two models "BlazePose Full" and "BlazePose Lite" against OpenPose. I have also located two "_model cards_" that describe both models:
 + BlazePose Lite: https://developers.google.com/ml-kit/images/vision/pose-detection/fast-modelcard.pdf
 + BlazePose Full (Accurate model): Fhttps://developers.google.com/ml-kit/images/vision/pose-detection/accurate-modelcard.pdf

 But in the repository you provide I do not locate such models, I only locate the following models used in the example application:
	+ mediapipe/modules/pose_detection/pose_detection.tflite
	+ mediapipe/modules/pose_landmark/pose_landmark_upper_body.tflite

**MediaPipe Hands**
In the section of results it includes in table 3 different models:
 + Light (1M Params)
 + Full (1.98M Params)
 + Heavy (4.02M Params)

In this case in the repository I only locate for use in this application the models:
 + mediapipe/models/palm_detection.tflite
 + mediapipe/models/hand_landmark.tflite

**Questions:**
1. If these models are present in this repository, can you tell me where specifically? And if not, could you tell me in each case which model/configuration corresponds to the results presented in the papers? 
2. In the case that not all the models are available, could you tell me if at any time all the models or configurations generated and used to generate these papers will be available and accessible for evaluation and use?

Thank you very much for your time.

**Comment by fanzhanggoogle** [comment]
We only released full models which are the models you listed. We don't have particular plan to release different versions of the models yet, but had thought about it if it's beneficial to developers. Could you elaborate a bit more use case so that we may rethink what's the best to release?

**Comment by ThiruSS** [comment]
I'm in the initial stages of a research project and I'm studying the state of the art, as opposed to other current implementations or proposals, as a starting point for development.
When I read the papers I was not sure about the correlation between the configuration/models available in this repository and the models reported in the tables of each of these papers.
So you tell me then, the available models correspond with respect to the configurations reported in these papers are:
 * BlazePose Full (Accurate model) ?
 * MediaPipe Hands Full (1.98M Params) or Heavy (4.02M Params) ???
Am I right ?

In my project the samples are being captured at 60fps because of the fast movements and to reduce the blurring effect, so apart from the quality it would also be interesting to evaluate the models with a high inference speed.

In my modest opinion it would be interesting to have each of the models trained and used in these papers, in order to improve the documentation, replicate the results and have more options when applying each model in each moment.

**Comment by fanzhanggoogle** [comment]
Thank you for the suggestion. We have been considering releasing different variation of the models, however due to internal release procedure and limitation of the support for configurable graphs, we don't have plan to do that yet. But we do have that in mind as we are working on making switching models with the same pipeline much easier.
