### ISSUE TITLE
One question about the function "::mediapipe::Status ImageCroppingCalculator::RenderGpu"

### ISSUE THREAD

**Issue by lovehuanhuan** [google/mediapipe#1131]
In this function,what's the purpose of these codes?
glActiveTexture(GL_TEXTURE2);
glBindTexture(GL_TEXTURE_2D, 0);

I found that without these codes,  My app works fine.

**Comment by mcclanahoochie** [comment]
There is limited context here, but those two lines are unbinding one of the textures used in a shader. 
Depending on the GPU driver and the order of GPU operations in your app, it may work OK without, but this is common texture cleanup after running a GL shader, to ensure textures are handled properly between different shaders.
