### ISSUE TITLE
Android studio Sync Error : no such target '//:-nolaunch_app'

### ISSUE THREAD

**Issue by downeydowney** [google/mediapipe#1132]
Hello! I'm downeydowney!

i'm on learning mediapipe.

So.. some errors are presented that i couldn't catch it. 
please give me advise!

it is error in bazel console on android studio.
i'm on building my graphs which i made

i don't have idea how to fix it.  Thank you for your attention.

Error:Blaze build failed. See Blaze Console for details.

ERROR: Skipping '-nolaunch_app': no such target '//:-nolaunch_app': target '-nolaunch_app' not declared in package '' defined by /data/src/mediapipe/BUILD.bazel
WARNING: Target pattern parsing failed.
ERROR: no such target '//:-nolaunch_app': target '-nolaunch_app' not declared in package '' defined by /data/src/mediapipe/BUILD.bazel
INFO: Elapsed time: 0.084s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by jiuqiant** [comment]
Can you provide more information such as your Bazel version and your OS info?

Could you try building the helloworld app in your terminal? See https://google.github.io/mediapipe/getting_started/building_examples.html#option-1-build-with-bazel-in-command-line for how to do this. Thanks.

**Comment by downeydowney** [comment]
> Can you provide more information such as your Bazel version and your OS info?
> 
> Could you try building the helloworld app in your terminal? See https://google.github.io/mediapipe/getting_started/building_examples.html#option-1-build-with-bazel-in-command-line for how to do this. Thanks.

thank you for rapid replying!!

i already do that helloworld! and basic solutions!
hand  face pose and so on.

i’m on trying to make new graph using basic solutions!

my os is Linux(ubuntu 18.04)
and bazel version 3.6.? 

i have never used android studio.
so.. i lost my way haha
if you need more information, i will reply as soon as possible! thank you
my country time is dawn!
maybe i will reply  6 hour later.. thank you!

**Comment by jiuqiant** [comment]
It might be a MediaPipe/Android Studio integration issue. My gut feeling is that's a new "feature" of Bazel 3.6.0. You probably can downgrade to use Bazel 3.0.0 to see if it happens again. In the meantime, I can reproduce this issue on my machine.

In fact, we now prefer users to use MediaPipe in Android Studio as an AAR: https://github.com/google/mediapipe/blob/master/docs/getting_started/android_archive_library.md.

**Comment by chriswallenwein** [comment]
I have the same problem with Android Studio, Ubuntu 20.04 and Bazel 3.0.0

**Comment by emirhanylmzz** [comment]
Same problem!!

**Comment by downeydowney** [comment]
> It might be a MediaPipe/Android Studio integration issue. My gut feeling is that's a new "feature" of Bazel 3.6.0. You probably can downgrade to use Bazel 3.0.0 to see if it happens again. In the meantime, I can reproduce this issue on my machine.
> 
> In fact, we now prefer users to use MediaPipe in Android Studio as an AAR: https://github.com/google/mediapipe/blob/master/docs/getting_started/android_archive_library.md.

Thank you i will try! downgrade of bazel! Thanks!
if it's getting better, i'll share my result!

**Comment by senpo** [comment]
This might be caused by https://github.com/bazelbuild/intellij/issues/2084

**Comment by zxf2871** [comment]
it happended after bazel sync. if not sync it will not be error.

**Comment by engineer1109** [comment]
Same with Linux Android Studio Bazel 3.7

**Comment by c1139676919** [comment]
bazel 3.7.2   macOS catalina 10.15.5
I have also encountered this problem
Here is my log

Waiting for target device...
Invoking mobile-install...
Command: /Users/mac/.bazel/bin/bazel mobile-install --tool_tag=ijwb:AndroidStudio --device c016900d:tcp:5037 "--adb_arg=-s " --adb_arg=c016900d --adb /Users/mac/Library/Android/sdk/platform-tools/adb --curses=no --color=yes --progress_in_terminal_title=no -c opt --config=android_arm64 --build_event_binary_file=/var/folders/81/zyx3b9z17jb880v9_w95tr140000gn/T/intellij-bep-99f14cf7-2921-4263-b7f9-a476a4f40a92 --nobuild_event_binary_file_path_conversion -- //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu --nolaunch_app

Loading: 
Loading: 0 packages loaded
ERROR: Skipping '-nolaunch_app': no such target '//:-nolaunch_app': target '-nolaunch_app' not declared in package '' defined by /Users/mac/AndroidStudioProjects/mediapipe/BUILD.bazel
WARNING: Target pattern parsing failed.
ERROR: no such target '//:-nolaunch_app': target '-nolaunch_app' not declared in package '' defined by /Users/mac/AndroidStudioProjects/mediapipe/BUILD.bazel
INFO: Elapsed time: 0.308s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (0 packages loaded)

@jiuqiant jiu

**Comment by c1139676919** [comment]
> bazel 3.7.2 macOS catalina 10.15.5
> 我也遇到了这个问题，
> 这是我的日志
> 
> 等待目标设备...正在
> 调用移动安装...
> 命令：/Users/mac/.bazel/bin/bazel mobile-install --tool_tag = ijwb：AndroidStudio --device c016900d：tcp：5037“ --adb_arg = -s“ --adb_arg = c016900d --adb / Users / mac / Library / Android / sdk / platform-tools / adb --curses = no --color = yes --progress_in_terminal_title = no -c opt --config = android_arm64 --build_event_binary_file = / var / folders / 81 / zyx3b9z17jb880v9_w95tr140000gn / T / intellij-bep-99f14cf7-2921-4263-b7f9-a476a4f40a92 --nobuild_event_binary_file_pathrc_conversion-// mediapipe / examples / android / com / / apps / handtrackinggpu：handtrackinggpu --nolaunch_app
> 
> 正在加载：
> 正在加载：已加载0个程序包
> 错误：正在跳过“ -nolaunch_app”：没有在/ Users / mac / AndroidStudioProjects / mediapipe / BUILD定义的“程序包”中声明的目标“ //：-nolaunch_app”：未声明目标“ -nolaunch_app”。 bazel
> 警告：目标模式分析失败。
> 错误：没有这样的目标'//：-nolaunch_app'：未在/ Users / mac / AndroidStudioProjects / mediapipe / BUILD定义的程序包``中声明目标'-nolaunch_app'.bazel
> INFO：经过的时间：0.308s
> INFO：0个进程。
> 失败：构建未成功完成（已加载0个软件包）
> 失败：构建未成功完成（已加载0个软件包）
> 信息：构建成功生成了事件协议文件。
> 失败：
> 
> @久久九

**I downgraded bazel to 3.4.0 , and this problem still occurs after clicking run**
```
Waiting for target device...
Invoking mobile-install...
Command: /Users/mac/bin/bazel mobile-install --tool_tag=ijwb:AndroidStudio --device c016900d:tcp:5037 "--adb_arg=-s " --adb_arg=c016900d --adb /Users/mac/Library/Android/sdk/platform-tools/adb --curses=no --color=yes --progress_in_terminal_title=no -c opt --config=android_arm64 --build_event_binary_file=/var/folders/81/zyx3b9z17jb880v9_w95tr140000gn/T/intellij-bep-7db9a6e8-27be-4ae7-920b-1d8032226c4f --nobuild_event_binary_file_path_conversion -- //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu --nolaunch_app

Loading: 
Loading: 0 packages loaded
ERROR: Skipping '-nolaunch_app': no such target '//:-nolaunch_app': target '-nolaunch_app' not declared in package '' defined by /Users/mac/AndroidStudioProjects/mediapipe/BUILD.bazel
WARNING: Target pattern parsing failed.
ERROR: no such target '//:-nolaunch_app': target '-nolaunch_app' not declared in package '' defined by /Users/mac/AndroidStudioProjects/mediapipe/BUILD.bazel
INFO: Elapsed time: 0.099s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (0 packages loaded)

```

**Comment by mohammed-safwan** [comment]
Meanwhile, [Build with Bazel in Command Line](https://google.github.io/mediapipe/getting_started/android.html#option-1-build-with-bazel-in-command-line) can be used for deploying the apps.

**Comment by sgowroji** [comment]
Hi @downeydowney, I would request you to check the above with the latest release and let us know if you still see the same.

**Comment by vblemberg** [comment]
I experience the same issue. Most likely it's because of extra space added by I would guess AS bazel plugin.
Check this line in output:
`Command: /Users/mac/bin/bazel mobile-install --tool_tag=ijwb:AndroidStudio --device c016900d:tcp:5037 "--adb_arg=-s " --adb_arg=c016900d --adb /Users/mac/Library/Android/sdk/platform-tools/adb --curses=no --color=yes --progress_in_terminal_title=no -c opt --config=android_arm64 --build_event_binary_file=/var/folders/81/zyx3b9z17jb880v9_w95tr140000gn/T/intellij-bep-7db9a6e8-27be-4ae7-920b-1d8032226c4f --nobuild_event_binary_file_path_conversion -- //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu --nolaunch_app
`
Note that there is a space between `--` and `//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu`
and probably that is why `--nolaunch_app` is treated as a target.

Any ideas? Seems like a bug in bazel plugin or so
