### ISSUE TITLE
Unable to get the iris depth fro the camera - what changes do I need to make?

### ISSUE THREAD

**Issue by nitin26gupta** [google/mediapipe#1133]
This is how my class in MainActivity looks like:

```
public class MainActivity extends com.google.mediapipe.apps.basic.MainActivity {
  private static final String TAG = "MainActivity";

  private static final String FOCAL_LENGTH_STREAM_NAME = "focal_length_pixel";
private static final String LEFT_IRIS_DEPTH_MM = "left_iris_depth_mm";
  @Override

  
  protected void onCameraStarted(SurfaceTexture surfaceTexture) {
    super.onCameraStarted(surfaceTexture);
    Log.v(TAG,"inside onCameraStarted");
    float focalLength = cameraHelper.getFocalLengthPixels();
    if (focalLength != Float.MIN_VALUE) {
      Log.v(TAG,"inside focalLength != Float.MIN_VALUE : " + focalLength);
      Packet focalLengthSidePacket = processor.getPacketCreator().createFloat32(focalLength);
      Map<String, Packet> inputSidePackets = new HashMap<>();
      inputSidePackets.put(FOCAL_LENGTH_STREAM_NAME, focalLengthSidePacket);
      processor.setInputSidePackets(inputSidePackets);

      processor.addPacketCallback(
                LEFT_IRIS_DEPTH_MM,
                (packet) -> {
                    float depth = PacketGetter.getFloat32(packet);
                    Log.v(TAG,"depth is: " + depth);
                });
    }
  }
}

```
after this my app is crashing every time.
I haven't made any other change anywhere else.

Without the depth related changes in the code, the app works well.

Please suggest what more I need to do to get the depth?
I am really stuck at this for 3 days now.

Appreciate any kind of help here. 
Thanks.

**Comment by mgyong** [comment]
@nitin26gupta Pls provide log cat on the crash

**Comment by nitin26gupta** [comment]
Thanks for responding.

Error in logcat:

020-09-23 14:27:15.407 24135-24159/? E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.google.mediapipe.apps.iristrackinggpu, PID: 24135
    com.google.mediapipe.framework.MediaPipeException: unknown: ; Input Stream "left_iris_depth_mm" for node with sorted index 2 does not have a corresponding output stream.

so how can i have left_iris_depth_mm in the output stream in the graph?
What changes do i need to make?

**Comment by nitin26gupta** [comment]
I was able to solve this:

for anyone looking for the answer, here are the changes i did:

**Step 1:
Created this subgraph for Depth:**

# MediaPipe iris tracking rendering subgraph.

type: "IrisDepthGpu"

input_stream: "IMAGE:input_image"
input_stream: "IRIS_LANDMARKS_LEFT:left_iris_landmarks"
input_stream: "IRIS_LANDMARKS_RIGHT:right_iris_landmarks"
input_side_packet: "FOCAL_LENGTH:focal_length_pixel"

output_stream: "LEFT_IRIS_DEPTH_MM:left_iris_depth_mm"
output_stream: "RIGHT_IRIS_DEPTH_MM:right_iris_depth_mm"

# Concatenate iris landmarks from both eyes.
node {
  calculator: "ConcatenateNormalizedLandmarkListCalculator"
  input_stream: "left_iris_landmarks"
  input_stream: "right_iris_landmarks"
  output_stream: "iris_landmarks"
}

node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE_GPU:input_image"
  output_stream: "SIZE:image_size"
}

node {
  calculator: "IrisToDepthCalculator"
  input_stream: "IRIS:iris_landmarks"
  input_stream: "IMAGE_SIZE:image_size"
  input_side_packet: "FOCAL_LENGTH:focal_length_pixel"
  output_stream: "LEFT_IRIS_DEPTH_MM:left_iris_depth_mm"
  output_stream: "RIGHT_IRIS_DEPTH_MM:right_iris_depth_mm"
}

**Step 2:
Added this subgraph** as 'mediapipe_simple_subgraph' in the BUILD file of the Subgraphs:

mediapipe_simple_subgraph(
    name = "iris_depth_gpu",
    graph = "iris_depth_gpu.pbtxt",
    register_as = "IrisDepthGpu",
    deps = [
        ":renderer_calculators",
        "//mediapipe/graphs/iris_tracking/calculators:iris_to_depth_calculator",
        "//mediapipe/graphs/iris_tracking/calculators:iris_to_render_data_calculator",
    ],
)

**Step 3:
Added this subgraph** in the 'iris_tracking_gpu_deps' cc_library in the main BUILD file:
 "//mediapipe/graphs/iris_tracking/subgraphs:iris_depth_gpu",

**step 4:
added new node in the graph: 'iris_tracking_gpu.pbtxt' graph:**

# Renders annotations and overlays them on top of the input images.
node {
  calculator: "IrisDepthGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "IRIS_LANDMARKS_LEFT:left_iris_landmarks"
  input_stream: "IRIS_LANDMARKS_RIGHT:right_iris_landmarks"
  input_side_packet: "FOCAL_LENGTH:focal_length_pixel"
  output_stream: "LEFT_IRIS_DEPTH_MM:left_iris_depth_mm"
  output_stream: "RIGHT_IRIS_DEPTH_MM:right_iris_depth_mm"
}

**Step 5 in the Mainactivity.java file for iris tracking example:**

added these:
  
private static final String OUTPUT_LANDMARKS_STREAM_NAME = "iris_landmarks";
      
processor.addPacketCallback(
                RIGHT_IRIS_DEPTH_MM,
                (packet) -> {
                    float right_depth = PacketGetter.getFloat32(packet);
                    Log.v(TAG,"right depth in cm is: " + right_depth/10);
                });

**Comment by Misby** [comment]
@nitin26gupta Hi, I want to confirm which item name in the main BUILD file did you use to gain the android ‘.arr’ file，before you modify any files .Thank you.
I made a BUILD file like:
mediapipe_aar(
    name = "iris_tracking_gpu_deps",
    calculators = ["//mediapipe/graphs/iris_tracking:iris_tracking_gpu_deps"],
)
and run:
 bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:iris_tracking_gpu_deps

but the iris_tracking_gpu_deps.aar I got seems to be ineffective in my android project.

 look forward to your reply

**Comment by eknight7** [comment]
@nitin26gupta Since you were able to resolve this (great!) we are closing this issue.

Please reopen if you have further comments. Thank you.

**Comment by MikeDean2367** [comment]
> I was able to solve this:
> 
> for anyone looking for the answer, here are the changes i did:
> 
> **Step 1: Created this subgraph for Depth:**
> 
> # MediaPipe iris tracking rendering subgraph.
> type: "IrisDepthGpu"
> 
> input_stream: "IMAGE:input_image"
> input_stream: "IRIS_LANDMARKS_LEFT:left_iris_landmarks"
> input_stream: "IRIS_LANDMARKS_RIGHT:right_iris_landmarks"
> input_side_packet: "FOCAL_LENGTH:focal_length_pixel"
> 
> output_stream: "LEFT_IRIS_DEPTH_MM:left_iris_depth_mm"
> output_stream: "RIGHT_IRIS_DEPTH_MM:right_iris_depth_mm"
> 
> # Concatenate iris landmarks from both eyes.
> node {
> calculator: "ConcatenateNormalizedLandmarkListCalculator"
> input_stream: "left_iris_landmarks"
> input_stream: "right_iris_landmarks"
> output_stream: "iris_landmarks"
> }
> 
> node {
> calculator: "ImagePropertiesCalculator"
> input_stream: "IMAGE_GPU:input_image"
> output_stream: "SIZE:image_size"
> }
> 
> node {
> calculator: "IrisToDepthCalculator"
> input_stream: "IRIS:iris_landmarks"
> input_stream: "IMAGE_SIZE:image_size"
> input_side_packet: "FOCAL_LENGTH:focal_length_pixel"
> output_stream: "LEFT_IRIS_DEPTH_MM:left_iris_depth_mm"
> output_stream: "RIGHT_IRIS_DEPTH_MM:right_iris_depth_mm"
> }
> 
> **Step 2: Added this subgraph** as 'mediapipe_simple_subgraph' in the BUILD file of the Subgraphs:
> 
> mediapipe_simple_subgraph(
> name = "iris_depth_gpu",
> graph = "iris_depth_gpu.pbtxt",
> register_as = "IrisDepthGpu",
> deps = [
> ":renderer_calculators",
> "//mediapipe/graphs/iris_tracking/calculators:iris_to_depth_calculator",
> "//mediapipe/graphs/iris_tracking/calculators:iris_to_render_data_calculator",
> ],
> )
> 
> **Step 3: Added this subgraph** in the 'iris_tracking_gpu_deps' cc_library in the main BUILD file:
> "//mediapipe/graphs/iris_tracking/subgraphs:iris_depth_gpu",
> 
> **step 4: added new node in the graph: 'iris_tracking_gpu.pbtxt' graph:**
> 
> # Renders annotations and overlays them on top of the input images.
> node {
> calculator: "IrisDepthGpu"
> input_stream: "IMAGE:throttled_input_video"
> input_stream: "IRIS_LANDMARKS_LEFT:left_iris_landmarks"
> input_stream: "IRIS_LANDMARKS_RIGHT:right_iris_landmarks"
> input_side_packet: "FOCAL_LENGTH:focal_length_pixel"
> output_stream: "LEFT_IRIS_DEPTH_MM:left_iris_depth_mm"
> output_stream: "RIGHT_IRIS_DEPTH_MM:right_iris_depth_mm"
> }
> 
> **Step 5 in the Mainactivity.java file for iris tracking example:**
> 
> added these:
> 
> private static final String OUTPUT_LANDMARKS_STREAM_NAME = "iris_landmarks";
> 
> processor.addPacketCallback(
> RIGHT_IRIS_DEPTH_MM,
> (packet) -> {
> float right_depth = PacketGetter.getFloat32(packet);
> Log.v(TAG,"right depth in cm is: " + right_depth/10);
> });

I have the same problem as you. Follow your steps to try or report an error. Can you provide your code below？
