### ISSUE TITLE
Hand and face tracking with a single camera on web

### ISSUE THREAD

**Issue by JudeOsborn** [google/mediapipe#1135]
What are the chances of getting a single camera to track both the face and a hand at the same time on web? I saw another post about how to get it done on native mobile but do you think web is a possibility?

**Comment by sgowroji** [comment]
Hi @JudeOsborn, Could you please elaborate your use case if you're still looking answer for the above query.  Thanks!

**Comment by JudeOsborn** [comment]
No, all good thanks. We have Holistic now, which does the trick.
