### ISSUE TITLE
how to debug the code 

### ISSUE THREAD

**Issue by CaichaoGitHub** [google/mediapipe#1137]
i build autoclip successfully  with command below
**bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/autoflip:run_autoflip**
and i could run the demo  

but , how could i debug it ? 

VSCode or any other IDE avaliable ?

**Comment by jiuqiant** [comment]
"bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip" is a binary. So, you can do debugging with gdb, valgrind, and so on.
Moreover, for debugging, you'd better to rebuild "run_autoflip" with the debug mode by replacing `-c opt` with `-c debug`. So the build command should be the following:

```
bazel build -c debug --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/autoflip:run_autoflip
```

**Comment by CaichaoGitHub** [comment]
> "bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip" is a binary. So, you can do debugging with gdb, valgrind, and so on.
> Moreover, for debugging, you'd better to rebuild "run_autoflip" with the debug mode by replacing `-c opt` with `-c debug`. So the build command should be the following:
> 
> ```
> bazel build -c debug --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/autoflip:run_autoflip
> ```

is there a ide for debug ?  command looks like inefficient

**Comment by aaaron7** [comment]
You can generate Xcode project from Mediapipe.tulsi, and import all source files into the project(By default the project only contains subset of source files). Then you can debug it as normal ios project, breakpoints, step by step execute, etc.

**Comment by CaichaoGitHub** [comment]
> You can generate Xcode project from Mediapipe.tulsi, and import all source files into the project(By default the project only contains subset of source files). Then you can debug it as normal ios project, breakpoints, step by step execute, etc.

@aaaron7  hxg?

**Comment by jiuqiant** [comment]
You probably can use gdb to debug the code. I am sorry that there is no ide debugging support yet.
