### ISSUE TITLE
Get position of the hands as array (coordinates) in multi_hand_tracking

### ISSUE THREAD

**Issue by dgrnd4** [google/mediapipe#1138]
Hi there, i want to extract, from a video where multi hand detection is already done, the position of the hands and put all those array, frame per frame, in a .txt file. Does mediapipe give something already developed for it?

I think that the position would be given as an array, am i right? Could you please tell me how can i do it?

**Comment by Aprameyah** [comment]
@dgrnd4 Were you able to get the coordinates of the hands ?

**Comment by dgrnd4** [comment]
@Aprameyah yes I did, check my last comment in #1192 post!! Let me know if u get it
