### ISSUE TITLE
Unable to run Iris Tracking Desktop Version (CPU)

### ISSUE THREAD

**Issue by Gul11** [google/mediapipe#1139]
Hi,

I'm trying to run Iris Tracking Desktop Version (CPU) on unix server. I was able to complete the build ,however, while running the below command :

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_cpu \
  --calculator_graph_config_file=mediapipe/graphs/iris_tracking/iris_tracking_desktop_live.pbtxt

I'm getting this error : 

bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_cpu: error while loading shared libraries: libjpeg.so.9: cannot open shared object file: No such file or directory

**Comment by jiuqiant** [comment]
Do the answers of https://askubuntu.com/questions/149048/libjpeg-so-62-cannot-open-shared-object-file-no-such-file-or-directory help?

**Comment by Gul11** [comment]
It helped, but now I am getting the below error and I tried using the above solution for this, but it didn't work:

bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_cpu: error while loading shared libraries: libjasper.so.4: cannot open shared object file: No such file or directory

**Comment by Gul11** [comment]
Also, is it possible to access webcam while using the Desktop version on Ubuntu server?

**Comment by jiuqiant** [comment]
> It helped, but now I am getting the below error and I tried using the above solution for this, but it didn't work:
> 
> bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_cpu: error while loading shared libraries: libjasper.so.4: cannot open shared object file: No such file or directory

Can you try `sudo apt-get install libjasper-dev`? I feel like such issues are liking caused by missing local dependencies.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
