### ISSUE TITLE
Bazel build failed in Hello World example (Initial minimal application setup)

### ISSUE THREAD

**Issue by RicoSuaveGuapo** [google/mediapipe#114]
Install packages version:
-  build-tools;29.0.2        | 29.0.2             | Android SDK Build-Tools 29.0.2 | build-tools/29.0.2/
-  ndk-bundle                 | 20.0.5594570 | NDK                                            | ndk-bundle/
-  patcher;v4                   | 1                    | SDK Patch Applier v4                  | patcher/v4/
-  platform-tools            | 29.0.3             | Android SDK Platform-Tools      | platform-tools/
-  platforms;android-29 | 3                     | Android SDK Platform 29           | platforms/android-29/
-  tools                           | 26.1.1              | Android SDK Tools 26.1.1           | tools/

After setting up all the files ``activity_main.xml``,  ``MainActivity.java``,  ``AndroidManifest.xml``, ``strings.xml``, ``colors.xml``, ``styles.xml``, ``BUILD`` to their respective locations, where I have changed to my own paths (also the paths inside the files).

$APPLICATION_PATH = usr/local/bazel/mediapipe
$PACKAGE_PATH = usr.local.bazel.mediapipe

Using the build command
````
bazel build -c opt --config=android_arm64 $APPLICATION_PATH
````

I have the following errors
```
DEBUG: Rule 'build_bazel_rules_apple' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "6c9fcae7a3597aabd43f28be89466afe0eab18de", shallow_since = "1565379803 -0700" and dropping ["tag"]
DEBUG: Call stack for the definition of repository 'build_bazel_rules_apple' which is a git_repository (rule definition at /home/liunix/.cache/bazel/_bazel_liunix/591e813fae3a0decb4095e2d0c18ac5a/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /usr/local/bazel/mediapipe/WORKSPACE:253:1
ERROR: Skipping '//usr/local/bazel/mediapipe': no such package 'usr/local/bazel/mediapipe': BUILD file not found in any of the following directories.
 - /usr/local/bazel/mediapipe/usr/local/bazel/mediapipe
WARNING: Target pattern parsing failed.
ERROR: no such package 'usr/local/bazel/mediapipe': BUILD file not found in any of the following directories.
 - /usr/local/bazel/mediapipe/usr/local/bazel/mediapipe
INFO: Elapsed time: 185.707s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Note that I use the Windows Pro 10 with WSL Ubuntu 18.04, and using MediaPipe without Android Studio. Instead, I run ``setup_android_sdk_and_ndk.sh`` to download and setup Android SDK and NDK.

I have seen a similiar issue in the forum [#38](https://github.com/google/mediapipe/issues/38), but the solution is not work for me.

Any suggestion?

**Comment by jiuqiant** [comment]
RicoSuaveGuapo@, I am a little bit confused about your situation.
- Where is your local mediapipe repo? Is that in /usr/local/bazel/mediapipe?
- Where are your own files? Do you also put them in /usr/local/bazel/mediapipe?
- Where do you run the Bazel build command? Do you run the command in /usr/local/bazel/mediapipe?

**Comment by RicoSuaveGuapo** [comment]
- Where is your local mediapipe repo? Is that in /usr/local/bazel/mediapipe?
Yes.
- Where are your own files? Do you also put them in /usr/local/bazel/mediapipe?
In /usr/local/bazel/mediapipe/LiFirstApp
- Where do you run the Bazel build command? Do you run the command in /usr/local/bazel/mediapipe?
I run in /usr/local/bazel/mediapipe/LiFirstApp

**Comment by jiuqiant** [comment]
> * Where is your local mediapipe repo? Is that in /usr/local/bazel/mediapipe?
>   Yes.
> * Where are your own files? Do you also put them in /usr/local/bazel/mediapipe?
>   In /usr/local/bazel/mediapipe/LiFirstApp
> * Where do you run the Bazel build command? Do you run the command in /usr/local/bazel/mediapipe?
>   I run in /usr/local/bazel/mediapipe/LiFirstApp

Ok, if you run `bazel build -c opt --config=android_arm64 usr/local/bazel/mediapipe` in  `/usr/local/bazel/mediapipe`, Bazel is asked to build something in `/usr/local/bazel/mediapipe/usr/local/bazel/mediapipe` because your $APPLICATION_PATH is **a relative path to the current directory**. That's why your see the error message 
`ERROR: no such package 'usr/local/bazel/mediapipe': BUILD file not found in any of the following directories. /usr/local/bazel/mediapipe/usr/local/bazel/mediapipe`

I guess you can  run `bazel build -c opt --config=android_arm64 LiFirstApp/...:all` in  `/usr/local/bazel/mediapipe` to build your app.

**Comment by RicoSuaveGuapo** [comment]
It WORKS!!
Thanks for the tip of **$APPLICATION_PATH is a relative path to the current directory**.
Btw, the BUILD file provided in the manual may need to change to no tab indentation, if one copies directly from the code snippet may occur this small problem. 

Thanks again!
