### ISSUE TITLE
file_helper failed in helloworld

### ISSUE THREAD

**Issue by e99** [google/mediapipe#1140]
I have a problem about file_helper in window hello world.

ERROR: C:/users/e99/mediapipe/mediapipe/framework/deps/BUILD:90:11: C++ compilation of rule '//mediapipe/framework/deps:file_helpers' failed (Exit 2)

mediapipe/framework/deps/file_helpers.cc(234): error C3861: '_mkdir': identifier is not defined.

or
C:/users/e99/mediapipe/mediapipe/framework/BUILD:824:11: C++ compilation of rule '//mediapipe/framework:packet' failed (Exit 2)

.\mediapipe/framework/packet.h(448): error C2672: 'absl::lts_2020_02_25::make_unique':
.\mediapipe/framework/packet.h(448): error C2783: 'void std::make_unique(_Types &&...)':

bazel version : 3.5
visual studio vc 14.27.29110
winSDK : 10.0.19041.0

**Comment by jiuqiant** [comment]
Duplicate https://github.com/google/mediapipe/issues/908. 
See a temporary solution at https://github.com/google/mediapipe/issues/908#issuecomment-663800716.
