### ISSUE TITLE
What does   use_advanced_gpu_api_ mean in tflite_inference_calculator.cc?

### ISSUE THREAD

**Issue by lovehuanhuan** [google/mediapipe#1144]
use_advanced_gpu_api_ = MEDIAPIPE_TFLITE_GL_INFERENCE &&
                          options.has_delegate() &&
                          options.delegate().has_gpu() &&
                          options.delegate().gpu().use_advanced_gpu_api

I found that  use_advanced_gpu_api_  is 0,  so tflite_gpu_runner_->Invoke()  will not be called, it falls to interpreter_->Invoke()
And what's the difference between these two  invokes()?

**Comment by lovehuanhuan** [comment]
I think all the pb.txt of gpu inference instances shoule have option  "delegate { gpu {} }"
for example,
"
node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS_GPU:input_tensors"
  # TODO: we can use TENSORS_GPU here and in the downstream calculator
  output_stream: "TENSORS:detection_tensors"
  options: {
    [mediapipe.TfLiteInferenceCalculatorOptions.ext] {
      model_path: "mediapipe/modules/pose_detection/pose_detection.tflite"
    }
  }
}
"


shoule be 

node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS_GPU:input_tensors"
  # TODO: we can use TENSORS_GPU here and in the downstream calculator
  output_stream: "TENSORS:detection_tensors"
  options: {
    [mediapipe.TfLiteInferenceCalculatorOptions.ext] {
      model_path: "mediapipe/modules/pose_detection/pose_detection.tflite"
       delegate { gpu {} }
    }
  }
}

**Comment by jiuqiant** [comment]
It's a new gpu inference acceleration feature we haven't released.
