### ISSUE TITLE
How to use recolor calculator(recolor_calculator.cc) for iris recoloring?

### ISSUE THREAD

**Issue by breathim** [google/mediapipe#1145]
Recolor Calculator takes image_GPU & mask_gpu as input . 
Which  output from iris_tracking_gpu.pbtxt has to be given as the input for mask_gpu?

I tried in the following way but it doesnt work . 

node {
  calculator: "RecolorCalculator"
  input_stream: "IMAGE_GPU:input_frames_gpu"
  input_stream: "MASK_GPU:iris_landmarks"
  output_stream: "IMAGE:output_frames_gpu"
  node_options: {
    [type.googleapis.com/mediapipe.RecolorCalculatorOptions]: {
      color { r: 0 g: 0 b: 255 }
      mask_channel: RED
    }
  }
}

Kindly confirm whether recolor calculator can be used for eye re-coloring or is there any other way ?

**Comment by mcclanahoochie** [comment]
MASK_GPU is expected to be an image of type GpuBuffer. The mask image should be value 1 where coloring should take place, and 0 otherwise. To color only the eyes, you would need to create a mask image where the value is 1 only where the eyes are.
