### ISSUE TITLE
calculate face landmark

### ISSUE THREAD

**Issue by ahmedAlmasri** [google/mediapipe#1147]
Hello,

I use `face_landmark.tflite` to draw mesh on the face but the result is not a match on face position 

model result 

output 0 https://shrib.com/#Elias6ZMxkg2

x = `[75.22108, 75.44666, 75.338844, 70.50628, 75.34214, 75.21904, 74.78789, 36.55866, 74.59668, 74.4791, 74.03826, 75.21483, 75.19828, 75.09715, 75.19964, 75.22692, 75.26977, 75.39092, 75.66242, 75.49277, 69.80041, 17.364883, 52.818623, 47.651745, 42.3323, 34.65921, 56.770382, 44.250996, 50.25167, 38.486603, 34.6276, 31.253576, 57.455505, 34.241203, 17.201937, 25.650854, 47.87557, 67.93789, 68.84854, 60.40113, 55.732563, 63.236652, 59.069313, 49.671707, 71.07742, 70.26749, 27.951298, 58.643814, 57.79309, 57.259426, 32.726128, 70.274216, 39.901382, 32.722687, 22.438688, 62.50153, 55.166756, 45.389965, 23.23297, 61.588985, 65.97263, 50.527157, 53.16698, 30.050108, 57.415184, 49.38657, 48.59952, 43.488777, 26.486248, 46.781628, 24.852505, 21.328827, 68.34787, 61.94954, 57.3827, 62.833977, 51.90044, 54.42024, 53.896473, 64.615875, 60.074924, 64.276794, 69.31818, 68.366554, 68.14566, 68.4281, 68.78719, 69.26655, 59.785305, 58.95522, 57.60101, 56.441513, 51.358627, 17.616634, 75.376305, 57.069286, 55.826473, 67.85937, 58.8009, 66.90227, 53.287544, 44.90783, 56.374157, 30.681671, 34.64127, 38.023438, 54.71108, 61.009243, 59.640823, 57.470043, 37.493626, 26.268648, 59.208225, 30.038048, 62.367462, 61.18527, 20.887318, 29.66538, 36.063354, 46.16286, 53.362827, 58.40015, 69.66796, 21.23421, 26.249376, 72.72564, 58.893436, 15.417508, 62.3183, 55.631386, 32.246166, 60.742718, 19.482475, 58.637295, 65.492645, 34.309277, 34.90679, 17.138733, 27.51103, 18.870935, 56.577618, 73.10547, 54.20917, 21.722479, 42.59634, 47.497307, 52.864662, 21.98413, 65.80578, 50.036057, 43.106167, 74.30922, 76.45688, 51.830196, 55.60356, 57.783493, 22.83879, 54.51796, 50.12911, 45.468124, 40.59747, 37.50988, 15.19559, 39.17338, 75.28392, 55.93441, 61.652767, 67.33069, 74.700714, 41.815807, 49.042023, 65.75938, 28.673512, 57.311172, 66.163635, 76.42223, 57.40966, 18.624517, 64.19816, 63.339344, 62.39231, 61.790833, 60.85824, 55.409298, 53.73163, 52.07792, 47.463623, 28.867355, 66.07694, 62.72009, 59.608295, 56.625828, 28.701029, 67.41275, 59.14254, 75.01295, 70.01796, 74.929634, 62.163525, 76.37007, 76.01224, 67.63371, 45.988297, 51.098392, 52.00045, 39.9924, 46.62676, 35.79464, 66.49085, 58.81025, 42.555965, 50.07285, 41.300766, 23.549845, 35.303753, 21.694221, 42.891956, 62.472454, 63.024376, 59.46246, 65.525696, 58.2859, 49.885345, 42.420162, 36.098843, 31.832699, 29.668531, 16.657366, 33.943302, 39.579056, 46.693718, 53.248688, 57.89656, 61.061047, 16.765045, 59.486923, 66.16201, 67.079796, 69.75417, 66.887344, 60.690258, 70.9047, 71.16719, 60.72605, 63.556458, 65.28949, 35.688927, 32.358154, 79.72033, 112.841064, 80.85018, 129.36404, 97.300964, 102.3023, 107.38677, 114.64486, 93.31869, 105.31183, 99.36226, 111.05195, 114.67071, 117.951355, 94.56256, 115.06409, 130.3375, 122.890465, 102.59868, 82.301834, 81.28935, 89.65182, 93.95263, 86.594475, 90.48696, 100.139885, 79.86959, 80.50245, 120.65662, 91.74163, 92.99138, 93.36674, 117.374054, 80.17979, 109.04626, 116.02095, 124.627106, 86.763054, 94.43178, 103.99152, 125.44379, 89.03759, 84.7211, 98.59523, 95.72936, 118.25407, 93.10462, 99.7336, 100.428406, 104.27288, 121.27219, 101.61107, 123.329, 126.20964, 81.91917, 88.072, 92.25137, 87.765015, 97.151436, 94.838776, 95.029076, 86.140594, 89.25379, 85.49959, 80.67955, 82.93815, 82.48923, 82.09166, 81.43938, 80.86017, 89.63634, 90.5393, 92.07348, 93.2719, 98.64391, 129.94627, 92.141174, 93.31721, 82.72445, 91.67928, 83.6342, 97.09501, 105.43344, 94.17985, 116.65832, 113.37809, 110.71363, 95.59173, 88.08969, 88.88929, 90.498116, 111.97711, 122.62125, 90.81769, 118.88766, 87.807526, 89.71914, 127.77397, 119.72023, 113.71685, 104.052444, 96.986404, 91.78895, 80.07586, 127.98673, 122.19191, 78.19528, 91.557144, 131.24446, 87.73997, 94.80272, 116.86193, 89.98888, 128.58502, 91.192245, 85.10631, 115.83014, 115.33992, 131.26352, 122.10299, 128.52922, 95.63704, 77.66223, 96.31153, 126.344505, 107.07721, 102.41093, 96.47993, 127.32892, 86.983536, 101.80006, 107.98086, 98.260765, 94.50904, 92.23175, 125.19162, 95.42711, 99.832245, 104.50505, 109.267845, 112.13203, 131.37701, 110.33487, 94.44805, 88.991806, 83.13381, 108.998474, 102.47671, 87.12982, 120.86073, 92.531235, 84.02239, 95.06577, 130.04294, 85.67372, 86.62003, 87.654175, 88.499725, 90.15536, 93.694916, 95.51949, 97.2069, 102.08845, 120.963875, 83.8579, 86.839005, 90.0935, 92.29653, 120.95403, 82.012726, 92.40699, 79.98107, 88.33156, 84.438385, 104.28178, 99.25513, 98.97866, 110.32792, 103.59082, 114.28784, 86.158165, 91.76239, 107.9822, 101.17906, 108.57047, 125.83117, 114.63464, 127.29477, 106.99405, 87.81912, 87.7943, 91.272835, 85.36734, 91.00076, 99.38168, 106.853004, 113.09364, 117.19373, 119.24897, 131.3893, 115.47494, 110.11787, 103.271805, 96.981346, 92.226, 88.88844, 130.37682, 91.1183, 84.199165, 83.82405, 81.076645, 83.94735, 89.86891, 80.00623, 79.523384, 89.11948, 86.19586, 84.42737, 113.772095, 116.84256]
`

y =  ` [125.64607, 110.994896, 115.80429, 94.61881, 106.02371, 99.627396, 82.885956, 79.96903, 68.13384, 61.071793, 37.39088, 127.94686, 130.2609, 131.48856, 134.11911, 136.18266, 138.88574, 141.64455, 146.08673, 113.72086, 113.683334, 57.138454, 83.91175, 84.32372, 84.1948, 81.17082, 82.851715, 69.17913, 69.85675, 69.83544, 71.857506, 83.90886, 151.84962, 78.43947, 79.39446, 79.5773, 104.78552, 124.870605, 130.40668, 126.59561, 128.28499, 130.69582, 131.23703, 135.69629, 110.88591, 106.003075, 66.232635, 92.754074, 108.959206, 106.06571, 103.245995, 99.93099, 61.233223, 62.72564, 48.724728, 66.427505, 72.10556, 130.90282, 126.89092, 111.970375, 113.82212, 131.67157, 131.76591, 59.20372, 110.91818, 61.93166, 57.803535, 38.64505, 54.050243, 48.278408, 63.533127, 60.850018, 127.91292, 128.93466, 129.71454, 112.97081, 131.66234, 133.15892, 131.52304, 110.851135, 131.15157, 131.25877, 131.33684, 145.54993, 141.08932, 138.28745, 135.69894, 133.96248, 133.06334, 133.7133, 134.9166, 136.43147, 122.76176, 100.86891, 114.88573, 132.56354, 132.73064, 115.77047, 113.82777, 114.85619, 95.19815, 98.040184, 108.046776, 42.478783, 49.730637, 57.12155, 139.54938, 59.93137, 48.809402, 37.228817, 83.14884, 86.920135, 81.51313, 73.72957, 89.88019, 107.495575, 89.93868, 90.76861, 93.00132, 92.531845, 90.77946, 88.74532, 83.898476, 100.61773, 72.37903, 113.54727, 98.02322, 77.80908, 86.36939, 108.14535, 77.863266, 104.01317, 113.42045, 79.93086, 101.41172, 140.66579, 146.3132, 101.21104, 133.45032, 69.356514, 157.12459, 114.62456, 101.30838, 80.10529, 81.57981, 81.79343, 133.8232, 110.83073, 164.58878, 157.64464, 153.11783, 49.46908, 165.54427, 81.45044, 80.6615, 80.199005, 70.89621, 77.41667, 76.26106, 75.908165, 76.202095, 77.10019, 66.26572, 80.891365, 118.84978, 120.403366, 111.3146, 119.246, 75.34913, 147.21814, 152.24113, 160.74026, 138.03993, 78.980705, 92.00449, 161.77013, 161.60896, 112.586464, 133.54514, 134.72495, 136.67888, 139.23134, 143.12904, 131.50264, 130.87767, 129.84343, 126.37811, 113.90881, 86.55429, 75.89111, 76.38938, 131.06331, 126.196594, 75.91466, 147.16312, 94.108475, 89.647316, 88.87015, 99.48996, 156.5201, 150.79445, 150.14746, 137.45251, 111.627846, 142.91617, 110.30505, 116.1987, 118.093445, 155.60406, 102.010414, 141.46646, 146.97224, 131.22493, 119.63598, 132.06581, 123.364365, 122.28842, 94.961685, 109.99618, 110.7624, 106.57765, 70.36651, 66.82071, 66.02458, 66.954094, 69.51836, 78.74934, 90.16637, 86.28477, 87.92818, 88.04737, 87.09309, 85.59361, 84.15769, 89.14524, 111.91698, 96.60317, 110.40813, 112.92485, 111.212265, 113.436005, 113.33239, 114.362465, 79.91088, 81.495285, 82.650894, 77.87179, 74.40904, 94.74668, 80.0706, 113.74937, 57.93427, 83.93441, 84.2954, 84.29161, 81.23963, 82.79801, 69.36362, 70.11051, 69.99009, 71.97674, 84.231346, 151.5335, 78.50267, 79.7323, 79.93348, 105.097786, 124.968605, 130.42627, 126.56324, 128.2933, 130.65443, 131.20532, 135.75267, 110.968315, 106.070435, 66.38705, 92.9445, 109.146034, 106.29742, 103.62839, 100.088104, 61.254852, 62.789642, 49.803986, 66.47337, 72.247055, 131.07481, 126.2288, 112.132675, 113.90675, 131.78558, 131.89536, 59.371674, 111.13331, 61.99735, 57.949062, 39.660484, 54.75619, 48.9108, 63.884754, 61.45829, 127.93874, 128.94077, 129.76604, 113.099014, 131.9396, 133.33687, 131.6452, 111.04432, 131.1625, 131.21596, 131.37161, 145.45596, 141.07379, 138.26611, 135.57306, 133.96664, 133.12694, 133.80374, 135.01808, 136.52817, 122.9034, 100.655075, 132.62227, 132.84935, 115.82929, 114.01626, 114.99701, 95.459564, 98.37699, 108.314064, 43.648357, 50.386417, 57.34058, 139.48363, 59.997185, 49.219505, 37.881104, 83.2942, 87.42525, 81.524216, 73.901, 90.03925, 107.684654, 90.328186, 91.236145, 93.40492, 92.806244, 90.99905, 88.93576, 83.92774, 100.88445, 72.55989, 113.63982, 98.170815, 78.16447, 86.580666, 108.38578, 77.90839, 104.12836, 113.01028, 79.86056, 101.59, 139.75063, 145.21555, 101.18118, 132.58899, 69.96128, 156.65637, 114.72627, 101.60074, 80.500534, 81.573006, 81.74685, 134.0136, 110.78043, 164.23315, 156.88441, 152.08958, 81.416214, 80.66946, 80.12231, 71.19168, 77.4563, 76.42943, 76.07281, 76.38511, 77.23476, 66.9064, 80.97779, 120.46153, 111.50829, 119.31055, 146.31163, 151.49123, 160.48157, 137.12297, 78.975975, 92.13081, 161.11212, 112.33151, 133.54646, 134.7835, 136.75288, 139.23006, 142.9879, 131.57799, 130.9401, 129.98447, 126.51808, 113.93861, 86.71333, 75.86538, 76.51803, 131.0954, 125.67357, 75.952835, 146.84407, 89.773994, 99.72357, 150.00986, 137.27945, 111.89504, 142.66347, 110.62201, 116.52571, 118.20619, 155.42973, 102.188065, 140.90866, 146.49849, 131.14395, 119.260445, 131.66716, 122.86372, 122.517006, 95.14122, 110.15138, 110.91522, 106.74163, 70.43622, 66.92441, 66.117065, 67.01305, 69.56107, 78.96306, 90.38563, 86.63456, 88.24901, 88.233826, 87.18878, 85.70878, 84.29345, 89.133026, 112.066605, 96.75356, 110.44891, 113.0289, 111.36569, 113.58642, 113.41479, 114.48104, 79.90144, 81.54787, 82.760994, 77.989586, 74.43687]`

​Face flag = `[-10.33867]` this is value always between -8 to -12 but on the document `Face probability threshold is set at
0.5 by default` 

this is the camera result,  view Always on this site, whether there is a face or not

![Image from iOS](https://user-images.githubusercontent.com/14888785/94336205-f3256b00-ffe9-11ea-8550-4c476a53a793.png)

**Comment by mgyong** [comment]
are u using the MediaPipe example for face mesh or are u directly calling tflite?

**Comment by ahmedAlmasri** [comment]
@mgyong  Thank you for the replay 

I've tried both this result from using tflite directly. 
and when using the mediapipe example mouth motion not accurate

**Comment by sgowroji** [comment]
Hi @ahmedAlmasri, Could you please try  [face mesh solution](https://google.github.io/mediapipe/solutions/face_mesh) from the latest release. It is updated with lot of improvements, Please reach us if you still have any queries specific to the above request.
