### ISSUE TITLE
iOS Mediapipe static library or framework

### ISSUE THREAD

**Issue by Eriie** [google/mediapipe#115]
Hi,
I try build a static library for iOS app, I tried build with bazel target HandTrackingGpuAppLibrary in handtrackinggpu example, but it built archive with sources of example code. I also tried build apple_binary and apple_static_library with bazel handtrackinggpu, but it built only source code of example.

How  can I build library with all dependencies?

**Comment by mgyong** [comment]
@Eriie pls provide iOS build environment details
xcode version?
tulsi used? if yes, what version
bazel version?
Any other environment details

**Comment by Eriie** [comment]
@mgyong 
xcode version 10.3
without tulsi
bazel 0.29.1

Mac OS 10.14.6

**Comment by mgyong** [comment]
@Eriie Pls share the commands you have tried to run to build the static libraries

**Comment by Eriie** [comment]
This is my build file in mediapipe/examples/ios/handtrackingpu  [BUILD.txt](https://github.com/google/mediapipe/files/3624515/BUILD.txt), I tried this commands:

`bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuAppLib`


As result in  first I got [.a archive](https://github.com/google/mediapipe/files/3624582/libHandTrackingGpuAppLibrary.a.zip)
 with binaries from example sources.

I recently tried command:
`bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuMediapipeLib` 
and got binaries in archive, but I stuck on how to use it, it seems small (203 bytes)
[HandTrackingGpuMediapipeLib_lipo.a.zip](https://github.com/google/mediapipe/files/3624579/HandTrackingGpuMediapipeLib_lipo.a.zip), and seems it doesn't include third party dependencies

**Comment by Eriie** [comment]
I have built it, and its run in another app and i didn't notice that output was a link and its actual library size with 203 mb
There is issue in static library graph doesn't see calculators so they should be added manually,

**Comment by lcycoding** [comment]
@Eriie 
`graph doesn't see calculators`
I've encountered this problem too, could you please share how you resolve this issue?

**Comment by Eriie** [comment]
@lcycoding 
I just put calculators files with library in project

**Comment by AndreyMirzoyan** [comment]
> I have built it

Hi! Can you please share your final BUILD file?
I'm trying to do the same, but still getting errors like
`+[NSError gus_errorWithStatus:]: unrecognized selector sent to class 0x1dbc92e98`
It seems that not all dependencies are included, even though they are in the deps section

**Comment by HebaMohamed** [comment]
@Eriie can you please share more data about how you generated the library with steps?

**Comment by HebaMohamed** [comment]
@Eriie I got this
```
Target //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuMediapipeLib up-to-date:
  bazel-bin/mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuMediapipeLib_lipo.a
```

Is this what you mean ? but the size is 20.3 only

**Comment by lcycoding** [comment]
If anyone who has encountered this issue,
Just add `linkopts = ["-force_load"]` to build script to make it work

**Comment by Zulqurnain24** [comment]
> If anyone who has encountered this issue,
> Just add `linkopts = ["-force_load"]` to build script to make it work

Is there some framework available that I can use for using object_detection_3d for ios?

**Comment by mingt86** [comment]
> > 我已经建好了
> 
> 嗨！您能否分享您的最终BUILD文件？
> 我正在尝试做同样的事情，但仍然会收到类似错误的
> `+[NSError gus_errorWithStatus:]: unrecognized selector sent to class 0x1dbc92e98`
> 提示，即使它们在deps部分中，似乎也不包括所有依赖项



> 嗨，
> 我尝试为iOS应用程序构建一个静态库，我尝试在handtrackinggpu示例中使用bazel目标HandTrackingGpuAppLibrary进行构建，但是它使用示例代码的源构建了存档。我还尝试使用bazel handtrackinggpu构建apple_binary和apple_static_library，但它仅构建了示例的源代码。
> 
> 如何建立具有所有依赖关系的库？



> 嗨，
> 我尝试为iOS应用程序构建一个静态库，我尝试在handtrackinggpu示例中使用bazel目标HandTrackingGpuAppLibrary进行构建，但是它使用示例代码的源构建了存档。我还尝试使用bazel handtrackinggpu构建apple_binary和apple_static_library，但它仅构建了示例的源代码。
> 
> 如何建立具有所有依赖关系的库？

Hello, is the ios_static_Framework set in your last build file? The framework I exported crashed at runtime,
+[NSError gus_errorWithStatus:]: Unrecognized selector sent to class 0x1dbC92e98

**Comment by lbouis** [comment]
Hi, I ran into the same issue trying to build an ios framework (that I use in an unity ios plugin). 
My ios apps using unity crashes with +[NSError gus_errorWithStatus:]: Unrecognized selector sent to class.
I tried to add linkopts = ["-force_load"] to my build file as follow but that did not help. Where do you add the linkopts option exactly?
My buiild process is basically:
a-build an ios framework with bazel
b-add this framework to my unity project in the Plugins/iOS folder
c-build with unity, run the app from the generted xcode project. App crashes when I try to start the mediapipe graph.

ios_static_framework(
 name = "Mediapipefm",
    minimum_os_version = MIN_IOS_VERSION,
 families = ["iphone", "ipad"],
 hdrs = glob(["**/*.h"]),
 deps = [
  ":HandsDetectionGpuLibrary",
  "@ios_opencv//:OpencvFramework"
 ],
 linkopts = **["-force_load"]**
)


objc_library(
    name = "HandsDetectionGpuLibrary",
    srcs = [
        "UnityBridgeHandsTracker.mm",
    ],
    hdrs = [
        "UnityBridgeHandsTracker.h",
    ],
    data = [
        "Base.lproj/LaunchScreen.storyboard",
        "Base.lproj/Main.storyboard",
        "//mediapipe/graphs/hand_tracking:multi_hand_tracking_mobile_gpu_binary_graph",
        "//mediapipe/models:hand_landmark.tflite",
        "//mediapipe/models:handedness.txt",
        "//mediapipe/models:palm_detection.tflite",
        "//mediapipe/models:palm_detection_labelmap.txt"
    ],
    sdk_frameworks = [
        "UIKit",
        "AVFoundation",
        "CoreGraphics",
        "CoreMedia",
        "Accelerate",
    ],
    deps = ["//mediapipe/objc:mediapipe_framework_ios",
    "//mediapipe/objc:mediapipe_input_sources_ios",
    "//mediapipe/objc:mediapipe_layer_renderer",
        ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            "//mediapipe/graphs/hand_tracking:multi_hand_mobile_calculators",
            "//mediapipe/framework/formats:landmark_cc_proto",
        ],
    }),
        
)

**Comment by lbouis** [comment]
I found this interesting article explaining why force_load is needed for ios categories [https://github.com/Cocoanetics/DTCoreText/issues/169] , so I am probably not using that flag in the right place...investigating further.
