### ISSUE TITLE
hand_tracking webpackage: uanable to pass the required video

### ISSUE THREAD

**Issue by vasanthhr** [google/mediapipe#1150]
Hello ALL, thanks for nice hand tracking package.

Can you guide us how to pass the required video and get the hand-landmark output by using this below web package link:

https://viz.mediapipe.dev/demo/hand_tracking

Is this webpackage has any functions to recive the video element and give the output of hand landmark? is there any function avaible in this package as like `await handModel.estimateHands(video)` ?

**Comment by vasanthhr** [comment]
@mhays-google @jiuqiant , Hope you are doing well.

could you please update me on this above request?.

**Comment by vasanthhr** [comment]
@mgyong @mhays-google 

I have seen your comments on the javascript API for handpose-mediapipe .  Could you please update when it can be releases?

Please find the link as you suggested:

https://github.com/google/mediapipe/issues/1163#issuecomment-706309879

**Comment by sgowroji** [comment]
Hi @vasanthhr, you can try this [codepen](mediapipe.dev/demo/hands) hands sample and can make necessary changes as your requirement. Reach us if you still have any queries specific to it.
