### ISSUE TITLE
How to get device view size or aspect ratio in calculator?

### ISSUE THREAD

**Issue by zespyx** [google/mediapipe#1152]
Hello, I got a problem in using mediapipe calculator.
The aspect ratio is different depending on the device,  and this affects some logic.
So, I need to know how to get the aspect ratio or display resolution information.
Please, explain me how to get this values.

**Comment by mcclanahoochie** [comment]
On android, you can see getOptimalViewSize  https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/CameraXPreviewHelper.java#L236 
and even set to prefer a different resolution.

**Comment by sgowroji** [comment]
Hi @zespyx, You can try this as below.  For more details see [here](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d/MainActivity.java#:~:text=float%20aspectRatio%20%3D%20(float)%20cameraTextureWidth%20/%20(float)%20cameraTextureHeight%3B)

[float aspectRatio = (float) cameraTextureWidth / (float) cameraTextureHeight;](url)
