### ISSUE TITLE
Error while trying to build the mediapipe basic example

### ISSUE THREAD

**Issue by shehramjamil** [google/mediapipe#1154]
C:/users/sjamil/_bazel_sjamil/wzpzhqus/external/bazel_tools/tools/android/BUILD:144:8: Executing genrule @bazel_tools//tools/android:gen_java_base_extras_jar failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\Program Files (x86)\Java\jre1.8.0_261\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; 
    external/remote_java_tools_windows/java_tools/src/tools/singlejar/singlejar_local.exe         --exclude_build_data         --dont_change_compression         --sources  bazel-out/host/bin/external/bazel_tools/tools/jdk/platformclasspath.jar         --include_prefixes \"java/lang/invoke/\"         --include_prefixes \"java/lang/annotation/\"         --normalize         --ou(...)): The system cannot find the file specified.
 (error: 2)

**Comment by jiuqiant** [comment]
As we mentioned in https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows, building MediaPipe Android apps is still not possible on native Windows. We apologize for the inconvenience.
