### ISSUE TITLE
interrupt when runing the hello_world.

### ISSUE THREAD

**Issue by wow-now** [google/mediapipe#1158]
Hi, after installing the mediapipe and trying to test the first program in mediapipe, the power failure hit my computer. When I reboot the computer and running the hello_world again, I got the following notification:

>  bazel run --define MEDIAPIPE_DISABLE_GPU=1  --action_env 

> PYTHON_BIN_PATH="/home/fang/.conda/envs/TF2/lib/python3.6" mediapipe/examples/desktop/hello_world:hello_world
> DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "f358144776d3dfc5a928ef32a0e4fbe93c99b55772d70cca77a6478e34d96aa7"
> DEBUG: Repository rules_foreign_cc instantiated at:
>   no stack (--record_rule_instantiation_callstack not enabled)
> Repository rule http_archive defined at:
>   /home/fang/.cache/bazel/_bazel_fang/e9f658bb1839ff2a3050fefc8e1ff3fc/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
> WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.IOException Read timed out
> INFO: Build option --action_env has changed, discarding analysis cache.
> DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "49c1a79d64d04f3fa6f98e5738906265943db094c9b6e66dbe844dd576f6faf7"
> DEBUG: Repository rules_cc instantiated at:
>   no stack (--record_rule_instantiation_callstack not enabled)
> Repository rule http_archive defined at:
>   /home/fang/.cache/bazel/_bazel_fang/e9f658bb1839ff2a3050fefc8e1ff3fc/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
> ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Either the path attribute of android_sdk_repository or the ANDROID_HOME environment variable must be set.
> INFO: Elapsed time: 0.295s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded, 11 targets configured)
> FAILED: Build did NOT complete successfully (0 packages loaded, 11 targets configured)
>     currently loading: @rules_foreign_cc//tools/build_defs/shell_toolchain/toolchains
>     Fetching @local_config_cc_toolchains; fetching
>     Fetching @commands_overloads; Restarting.
>     Fetching @local_execution_config_python; Restarting.

How could I fix this?

**Comment by jiuqiant** [comment]
Seems like you use Bazel 3.5.0 and hit the issue mentioned in https://github.com/google/mediapipe/issues/1094. You can either upgrade to Bazel 3.6.0 or downgrade to Bazel 3.4.0 to solve this issue.
