### ISSUE TITLE
Will windows be fully supported?

### ISSUE THREAD

**Issue by delebash** [google/mediapipe#1159]
I don't understand why windows is not supported.  I think this is something that we really should have.

**Comment by jiuqiant** [comment]
MediaPipe supports Windows at v0.7.5. After v0.7.5, we hit https://github.com/google/mediapipe/issues/908. 
Unfortunately, We don't have enough time and resources to solve it and any community contribution is welcomed.

**Comment by jiuqiant** [comment]
FYI, https://github.com/google/mediapipe/issues/908 is fixed in https://github.com/google/mediapipe/commit/c828392681bc343a90e188c5ad5f295bada1eefb.
