### ISSUE TITLE
Does Mediapipe on Android support 60fps?

### ISSUE THREAD

**Issue by at-duymai** [google/mediapipe#1160]
I have a device that supports 60fps recording with the back camera.
I experimented with "helloworld" example. I noticed that there is no big difference in FPS between the front camera (only supports 30fps) and the back camera.
Does the mediapipe limit the input frame rate or not? Thank you.

**Comment by sgowroji** [comment]
Hi @at-duymai, Could you please respond whether your looking answer for the above query. Thanks!

**Comment by duy-maimanh** [comment]
Hi @sgowroji I still don't have an answer.

**Comment by mcclanahoochie** [comment]
MediaPipe graphs will queue/drop frames when the input is faster than the system can handle. 
The more powerful the device (or more simple the graph), the less frames dropped/queued, the higher fps can be achieved.

**Comment by duy-maimanh** [comment]
> MediaPipe graphs will queue/drop frames when the input is faster than the system can handle.
> The more powerful the device (or more simple the graph), the less frames dropped/queued, the higher fps can be achieved.

Thank you for your answer.
