### ISSUE TITLE
How to access to bounding boxes coordinates in multi_hand_tracking

### ISSUE THREAD

**Issue by dgrnd4** [google/mediapipe#1166]
i already print the x,y,z coordinates for every landmarks detected, for every hand.
Now i need even the position for every bounding boxes found in the video.

**Comment by YongLD** [comment]
I have the same question, How did you get the hand coordinates?

**Comment by dgrnd4** [comment]
@YongLD if you find solutions please let me know here. The same if i will find one

**Comment by ctippur** [comment]
+1

**Comment by dgrnd4** [comment]
for who is looking for the solution, you can find it at comment #1192
