### ISSUE TITLE
Can i adapt the example for 3d objects to any other object?

### ISSUE THREAD

**Issue by dayerdl** [google/mediapipe#1168]
How could i reuse the example for 3d object detection for different objects?

Thanks and congrats for the amazing work.

**Comment by ahmadyan** [comment]
The models are trained for a specific categories such as shoes or chairs. For using them on different categories you have to re-train them with more data. Over time, we will release models for more categories. Stay tuned.

**Comment by wanghaichuan941221** [comment]
Hey, where can I find the trained model for shoe?

**Comment by ahmadyan** [comment]
all of the trained models are saved in [this folder](https://github.com/google/mediapipe/tree/master/mediapipe/models). 

[Single stage shoe detector](https://github.com/google/mediapipe/blob/master/mediapipe/models/object_detection_3d_sneakers_1stage.tflite), and [two-stage shoe detector](https://github.com/google/mediapipe/blob/master/mediapipe/models/object_detection_3d_sneakers.tflite).
