### ISSUE TITLE
How to access image and draw/overlay on the 'dest_mat' in the annotation_renderer.cc?

### ISSUE THREAD

**Issue by Avinash-M23** [google/mediapipe#117]
Hi, I'm trying to access an image bundled inside ios build in c++ code. I've done the following steps - 
1. Add the image inside the "mediapipe/examples/ios/handtrackinggpu" folder.
2. Done the following changes in the BUILD file for the objc_library section
`data = [
        "Base.lproj/LaunchScreen.storyboard",
        "Base.lproj/Main.storyboard",
        ":model",
        **":my_image.png",**
        "//mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu_binary_graph",
        "//mediapipe/models:palm_detection.tflite",
        "//mediapipe/models:palm_detection_labelmap.txt",
    ],`
3. In the 'annotation_renderer.cc' file, created a function and tried the following codes:
`mediapipe::StatusOr<std::string> status = ::mediapipe::PathToResourceAsFile("my_image.png"); //Using resource_util.h

    if (status.ok()){         
        cv::Mat image = cv::imread(status.ValueOrDie(), 1);
  }
`
and also this code:

`std::string image_output;
::mediapipe::Status status =  ::mediapipe::GetResourceContents("my_image.png", &image_output); // Using resource_util.h

if (status == ::mediapipe::OkStatus()) {
        std::vector<unsigned char> vectordata(image_output.begin(), image_output.end());
        cv::Mat data_mat(vectordata, true);
        cv::Mat image(cv::imdecode(data_mat, 1));
}
`
In both cases, the Mat image gives rows & cols as 0. Hence when I'm trying to overlay the image on 'dest_mat' using copyTo() function, the app crashes.

Ques.1: Is this the standard way to get the image? If no, how do I access the image in the c++ code?
Ques.2: How do I overlay this image on the mediapipe output ('dest_mat' object in the annotation_renderer.cc file) at specific coordinates?

Any help is appreciated.

**Comment by camillol** [comment]
When you say it's not working for PNG, what results are you getting? In your initial question, it seems like you were having issues decoding your image with OpenCV, which is really out of scope for this tracker.

Coordinates should not depend on the number of channels in the image.

**Comment by vkrytpo** [comment]
@Avinash-M23 

Hi Avinash, I also want to do the same thing but not good at CPP. so can you send me your annotation_overlay_caculatoer.cc  (the file you changed)?

by the way, you are saying annotation_render.cc , if it is correct then please location of file also because I am not able to find that file.

**Comment by pkoppise** [comment]
hi @AvinashM-Prorigo 

I am also trying to do the same thing ....could you please provide any hints?

Thanks in advance
