### ISSUE TITLE
Setting Visibility Option in Calculator

### ISSUE THREAD

**Issue by nschoenwetter** [google/mediapipe#1173]
I am trying to output the visibility of each landmark on the hand using the demo_run_graph_gpu and tflite_tensors_to_landmarks_calculator.cc . However, I am unsure where to change the calculator options to include the visibility dimension. Any help would be greatly appreciated.

**Comment by sgowroji** [comment]
Hi @nschoenwetter, You can check it [here](https://github.com/google/mediapipe/blob/b544a314b3c4818a4d6c56964b020c5be945377a/mediapipe/calculators/tflite/tflite_tensors_to_landmarks_calculator.cc#L249) in the latest release.
