### ISSUE TITLE
How to get Iris coordinates using Iris desktop version

### ISSUE THREAD

**Issue by Gul11** [google/mediapipe#1177]
Hi,

I'm using Iris model (Desktop version) to get iris landmarks for an input video.
However, on running the below command 

bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_cpu_video_input \
  --calculator_graph_config_file=mediapipe/graphs/iris_tracking/iris_tracking_cpu_video_input.pbtxt \
  --input_side_packets=input_video_path=<input video path>,output_video_path=<output video path>

I'm getting facial and in depth iris landmarks as well (refer the below screenshot)

![image](https://user-images.githubusercontent.com/31441117/95071646-a2b7b700-0727-11eb-8a64-d9a6b7f3adf0.png)

And I'm expecting an output as the below screenshot: 

![image](https://user-images.githubusercontent.com/31441117/95071729-c2e77600-0727-11eb-933c-d09b09bfba55.png)

I have 3 queries here :
 
1. How can I get the above expected output video?
2. How exactly I can get the coordinates of left and right iris using Desktop version?
3. Can I get the iris coordinates for an image instead of a video?

**Comment by mroussak** [comment]
any updates on this?

**Comment by EladAssia** [comment]
I found a solution based on https://github.com/google/mediapipe/issues/200
I modified the hand tracking file to match the iris tracking. See [here](https://gist.github.com/EladAssia/a4dc674e52f3e689b0e268851243f6b2).
You need to add these lines to the BUILD file under mediepipe/examples/desktop
```
cc_library(
    name = "demo_run_graph_main_out",
    srcs = ["demo_run_graph_main_out.cc"],
    deps = [
        "//mediapipe/calculators/util:landmarks_to_render_data_calculator",
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/formats:image_frame",
        "//mediapipe/framework/formats:image_frame_opencv",
        "//mediapipe/framework/formats:landmark_cc_proto",
        "//mediapipe/framework/port:commandlineflags",
        "//mediapipe/framework/port:file_helpers",
        "//mediapipe/framework/port:opencv_highgui",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:opencv_video",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
    ],
)
```
You these lines to the BUILD file under mediepipe/examples/desktop/iris_tracking
```
cc_binary(
    name = "iris_tracking_out_cpu",
    deps = [
        "//mediapipe/examples/desktop:demo_run_graph_main_out",
        "//mediapipe/graphs/iris_tracking:iris_tracking_cpu_deps",
    ],
)
```
Run:
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/iris_tracking:iris_tracking_out_cpu`
Then: 
`bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_out_cpu --calculator_graph_config_file=mediapipe/graphs/iris_tracking/iris_tracking_cpu.pbtxt`

To save the output into a text file, add `> filename.text` when running the application.

Note that this modification outputs only the iris markers and not the facial markers.

**Comment by Gul11** [comment]
Hi, 
I followed the steps you mentioned, I'm getting below error :

Linking of rule '//mediapipe/examples/desktop/iris_tracking:iris_tracking_out_cpu' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_out_cpu-2.params

**Comment by EladAssia** [comment]
Hi,
Can you share the bazel build and bazel bin commands?
Also, can you share the full error message?

**Comment by Gul11** [comment]
I ran this bazel build command - bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/iris_tracking:iris_tracking_out_cpu

Below is the error I got : 

ERROR: /mediapipe/mediapipe/examples/desktop/iris_trac
king/BUILD:62:1: Linking of rule '//mediapipe/examples/desktop/iris_tracking:iris_tracking_out_cpu' failed (Exit 1) gcc fai
led: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_out_
cpu-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o:function _start: error: undefined reference to 'main'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/nnapi/_objs/nnapi_implementation/nnapi_implementation.o:nnapi_
implementation.cc:function (anonymous namespace)::ASharedMemory_create(char const*, unsigned long): warning: the use of `tm
pnam' is dangerous, better use `mkstemp'
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/iris_tracking:iris_tracking_out_cpu failed to build

**Comment by Gul11** [comment]
Hi, I was able to complete the build part, where exactly do I need to add the > filename.text while running the application?
right now I'm using the below command to run the application : 

bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_cpu_video_input \
  --calculator_graph_config_file=mediapipe/graphs/iris_tracking/iris_tracking_cpu_video_input.pbtxt \
  --input_side_packets=input_video_path=<input video path>,output_video_path=<output video path>

**Comment by EladAssia** [comment]
Hi, sorry for not answering the previous comment, probably missed it.
To output a text file just add the "< filename.txt" at the end of the run command:
`bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_out_cpu --calculator_graph_config_file=mediapipe/graphs/iris_tracking/iris_tracking_cpu.pbtxt < filename.txt`
The output file will be in mediapipe folder.

**Comment by Gul11** [comment]
Hi, this build is not working in the case where I am using an input video from my local, for this I think they are using simple_run_graph_main instead of demo_run_graph_main. Is there any way to make the build command you mentioned run for input video instead of webcam?

**Comment by Gul11** [comment]
Hi, this build is not working in the case where I am using an input video from my local, for this I think they are using simple_run_graph_main instead of demo_run_graph_main. Is there any way to make the build command you mentioned run for input video instead of webcam?

**Comment by EladAssia** [comment]
Hi, you can use demo_run_graph_main using local videos, instead of writing: 
"--input_side_packets=input_video_path=,output_video_path="
just use: "--input_video_path=PATH_TO_YOUR_VIDEO" for using video from your drive 
and: "--output_video_path=PATH_TO_YOUR_VIDEO" to write the video file. 
Say my input video is in mediapipe folder and I want to output the video and the landmarks to this folder as well. 
The build command is as before:
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/iris_tracking:iris_tracking_out_cpu`
To run the program:
`bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_out_cpu --calculator_graph_config_file=mediapipe/graphs/iris_tracking/iris_tracking_cpu.pbtxt --input_video_path=input.mp4 --output_video_path=output.mp4 > landmarks.txt`

**Comment by Gul11** [comment]
Thanks! It worked, but when I'm annotating the image with the coordinates, they are not in place .
Is there any conversion factor?

**Comment by Gul11** [comment]
Hi, just one question, is there a way to input a static image instead of a video here? and would should be the ideal image size in that case?

**Comment by Gul11** [comment]
Hi, just one question, is there a way to input a static image instead of a video here? and what should be the ideal image size in that case?

**Comment by EladAssia** [comment]
Hi, glad it works :)
Regarding the conversion factor - I think there is some conversion since the values are between 0 to 1. I would start with the size of the image or the size of your screen and multiply the coordinates based on it.
For your image question, I don't have any experience with it but on mediapipe website there is an [example](https://google.github.io/mediapipe/solutions/iris.html#single-image-depth-estimation) how to do it.

**Comment by ctippur** [comment]
@EladAssia tried running `bazel build` but got an error:

```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/iris_tracking:iris_tracking_out_cpu
INFO: Analyzed target //mediapipe/examples/desktop/iris_tracking:iris_tracking_out_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/cttippur/plaground/mediapipe/mediapipe/examples/desktop/BUILD:54:11: //mediapipe/examples/desktop:demo_run_graph_main_out: missing input file '//mediapipe/examples/desktop:demo_run_graph_main_out.cc'
Target //mediapipe/examples/desktop/iris_tracking:iris_tracking_out_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/cttippur/plaground/mediapipe/mediapipe/examples/desktop/BUILD:54:11 1 input file(s) do not exist
INFO: Elapsed time: 0.661s, Critical Path: 0.38s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully

```

**Comment by ctippur** [comment]
Found the source code here: https://gist.github.com/mgyong/7353474eb3e57ba95621632af274911a
next set of error:
`mediapipe/examples/desktop/demo_run_graph_main_out.cc:28:10: fatal error: 'mediapipe/calculators/util/detections_to_render_data_calculator.pb.h' file not found
`

**Comment by EladAssia** [comment]
@ctippur you didn't create the "demo_run_graph_main_out.cc" file or is misplaced. Please see my first comment to this issue how to create this file and where to save it.

**Comment by ctippur** [comment]
Apologies and thank you for pointing me in the right direction. I do see the landmarks. Can you please help me understand the landmarks.

I see output like these. I want to be able to get the pupil coordinates of both the eyes.

```
landmark {
  x: 0.611678839
  y: 0.392118603
  z: -0.0238272324
  visibility: 0
  presence: 0
}
```

**Comment by ctippur** [comment]
@EladAssia - any visibility on how to interpret the landmarks?

**Comment by radisc** [comment]
@ctippur 
I believe x and y coordinates are the pixel coordinates normalized on the image resolution so if , for example, the image is 640x480 and the landmark is in x = 0.5 , y= 0.5 the corresponding pixel is x=320 / y= 240.

I arrived at this point too, but now everytime the face is not clearly visible ( like when in the vanilla code a green rectangle with very few landmark apppeared ) the cycle just halts without errors and must be closed and restarted.

**Comment by ctippur** [comment]
@radisc Thanks for getting back. That makes sense.
I was looking to see if some metadata can be added to the landmarks. I seem to get 10 landmarks for each frame and I can see that 1/2 of them are from left part of the face and other half from the right. I am struggling to understand the coordinates represent what part of the face. Appreciate any pointers.

**Comment by Misby** [comment]
@ctippur Hi may I ask , is there a way to input a static image instead of a video here?

**Comment by Misby** [comment]
Thanks I'v already slove static image type.

**Comment by gongchunye** [comment]
> Found the source code here: https://gist.github.com/mgyong/7353474eb3e57ba95621632af274911a

I am sorry that I can not open the source code.

**Comment by Shounak-Ghosh** [comment]
> @ctippur
> I believe x and y coordinates are the pixel coordinates normalized on the image resolution so if , for example, the image is 640x480 and the landmark is in x = 0.5 , y= 0.5 the corresponding pixel is x=320 / y= 240.
> 
> I arrived at this point too, but now everytime the face is not clearly visible ( like when in the vanilla code a green rectangle with very few landmark apppeared ) the cycle just halts without errors and must be closed and restarted.

I am in the same situation. I have pinpointed "if (!poller_landmark.Next(&landmark_packet)) break;" as the issue but don't know where to go from there. When there is no face to be detected, there are obviously no coordinates that can be printed, and this causes problems for the poller_landmarks stream. Not sure how to proceed and would appreciate any insight.

**Comment by sgowroji** [comment]
Hi @Gul11, Could you please respond, if you're still looking resolution for the above query. Thanks!

**Comment by Shounak-Ghosh** [comment]
> Hi @Gul11, Could you please respond, if you're still looking resolution for the above query. Thanks!

I have gotten [#867](https://github.com/google/mediapipe/pull/867) to work; It is essentially the same issue but for the FaceMesh desktop version. However, I'm not sure if it will transfer due to differences in the iris and FaceMesh graphs.

**Comment by sgowroji** [comment]
Hi @Shounak-Ghosh, Could you please raise a new issue with complete details of your query. Thanks!

**Comment by Hrituraj202** [comment]
`if (!poller_landmark.Next(&landmark_packet)) break;
    auto& output_landmarks = landmark_packet.Get<mediapipe::NormalizedLandmarkList>();`

after adding these lines no output screen is received.. where as after commenting it out gives the output screen.. something is not working.. please help
