### ISSUE TITLE
How to get logs from a calculator file?

### ISSUE THREAD

**Issue by tmnbhat** [google/mediapipe#118]
I am trying to debug a calculator file I modified for hand detection but am unable to get the prints to show on the logcat console on android studio. Any help greatly appreciated!

**Comment by jiuqiant** [comment]
We already prepared a glog patch that can help us print the native code log messages. We plan to release it early next week. If you want to have it now, you can include `<android/log.h>` and use `__android_log_write()` in the C++ code to make it happen.

**Comment by tmnbhat** [comment]
Thanks! works like a charm.

**Comment by sohail-jogo** [comment]
@tmnbhat do u remember how you did this? 
i added ` __android_log_print(ANDROID_LOG_INFO, "MYTAG" ,"iAmHere");` into the process function of FlowLimiterCalculator.cc. 
And i also added the header `<android/log.h>` as well. but I cant see the log in logcat : AndroidStudio.
