### ISSUE TITLE
How to reshape Iris Landmark when Iris is half open.

### ISSUE THREAD

**Issue by Nvelu048** [google/mediapipe#1181]
I have implemented Iris Recoloring.  

Now when eye is half open, Landmark seems to overlap with Eye lid How to reshape it.  

I expect to have

![image13](https://user-images.githubusercontent.com/24509341/95171015-ea474d00-07d2-11eb-9eac-85b391bf13d1.gif)

like this.

I am getting like this :  Iris Landmark overlapping Eye Lid

![WhatsApp Image 2020-10-06 at 13 35 52](https://user-images.githubusercontent.com/24509341/95175452-22518e80-07d9-11eb-9da2-f3dc51cb0233.jpeg)

What to do

**Comment by sgowroji** [comment]
Hi @Nvelu048, Could you please confirm, if you are able to reproduce the above with the latest release. Thanks!

**Comment by Nvelu048** [comment]
Hi @sgowroji,  currently i don't have necessary setup to check this. 

You can close the issue.  If you can
