### ISSUE TITLE
Android example on static image on any mediapipe solution

### ISSUE THREAD

**Issue by nitin26gupta** [google/mediapipe#1182]
for different mediapipe solutions, the different android app examples shared are all on live cam video.

however, i need to work it on a static image - which could be an image clicked by the user from front camera or it could be an image uploaded by the user.

I am not able to work out the solution for the same.

I understand we need to call : AddPacketToInputStream with image
But how do we open front camera and ask to click an image and then pass that image to AddPacketToInputStream?

Any example or detailed steps would be of great help.

**Comment by midhulavijayan** [comment]
Hi @nitin26gupta, Have you resolved the issue?..

**Comment by sgowroji** [comment]
We dont have any examples for it. But you can try this [link](https://github.com/Cubbee/mediapipe) if you still looking for resolution.
