### ISSUE TITLE
Error running Hello_world desktop example on Docker 

### ISSUE THREAD

**Issue by Aprameyah** [google/mediapipe#1186]
I have used the [Installing using Docker ](https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker) link to run MediaPipe.I tried running Hello World desktop example and got the following errors

ERROR: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/rules_cc/cc/private/rules_impl/cc_flags_supplier.bzl:28:21: rule() got unexpected keyword argument 'incompatible_use_toolchain_transition'
ERROR: While resolving toolchains for target //mediapipe/examples/desktop/hello_world:hello_world: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors

I was not able to find this error on the [Troubleshooting ](https://google.github.io/mediapipe/getting_started/troubleshooting.html) link. 

Please provide a solution for the above errors.

**Comment by jiuqiant** [comment]
See the solution at https://github.com/google/mediapipe/issues/1175#issuecomment-704524129.

**Comment by kokhengvettons** [comment]
I have the same issue and the solutions at [#1175 (comment](https://github.com/google/mediapipe/issues/1175#issuecomment-704524129)) which able to solve my issue. 

Please make sure you rebuild the docker image with the new changes bazel version and run it again.

**Comment by Aprameyah** [comment]
> See the solution at [#1175 (comment)](https://github.com/google/mediapipe/issues/1175#issuecomment-704524129).

The solution worked.Thanks
