### ISSUE TITLE
How to use tflite model saved in Android file system not in static asset folder or (mediapipe model directory in bazel) in android?

### ISSUE THREAD

**Issue by usernexme** [google/mediapipe#1187]
In TfLiteInferenceCalculator we are required to pass tflite file reference which must be the in mediapipe/models directory and in case of gradle build tflite file must be in the assets folder. These tflite files are static and we can not change them once the application has installed on a phone. I want to download a tflite model to the phone's local storage after the app is installed and want to use that model in the mediapipe graph. Is it possible? 
Can we use tflite model saved in phone storage instead of keeping them in assets?

**Comment by mcclanahoochie** [comment]
There is some extra logic on Android to determine where a file is based on the path provided in the graph , see PathToResourceAsFile https://github.com/google/mediapipe/blob/master/mediapipe/util/resource_util_android.cc#L33

You could put a full path (starting with '/') to some other folder, but it would have to exist (with correct app permissions) before starting the graph. Or, you could edit the resource_util_android.cc to fit your needs.

**Comment by sgowroji** [comment]
Above [comment](https://github.com/google/mediapipe/issues/1187#issuecomment-727121954) answered your query we are closing this issue now.
