### ISSUE TITLE
Building Mediapipe AAR for Android App

### ISSUE THREAD

**Issue by PLHieu** [google/mediapipe#1189]
Hello guys, I'm building mediapipe AAR in Ubuntu 18.04 LTS. If anyone knows how to fix this problem, please show  me how to fix, I sincerely thank

**This is my command:** 
bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_hand_tracking_aar

**This is ouput:** 
...
...
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_hand_tracking_aar (116 packages loaded, 16471 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/plh/.cache/bazel/_bazel_plh/10cf9176fe9665f6e255a36fbc530b0a/sandbox
ERROR: /home/plh/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: Executing genrule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_hand_tracking_aar_aar_manifest_generator failed (Exit 127) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: $'\r': command not found
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_hand_tracking_aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 41.537s, Critical Path: 16.21s
INFO: 126 processes: 126 internal.
FAILED: Build did NOT complete successfully

**Comment by jiuqiant** [comment]
Would you like to show us your mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD file to help us reproduce this issue?

**Comment by PLHieu** [comment]
Here it is:
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_hand_tracking_aar",
    calculators = ["//mediapipe/graphs/hand_tracking:multi_hand_mobile_calculators"],
)

**Comment by salvadorld0** [comment]
I think I did have the same issue while trying to compile the aar file with WSL. It has to do with the `mediapipe_aar.bzl` file. That file has bash code and in my case the EOL configuration was preventing it to run correctly. It was `CRLF` and it has to be `LF` to be parse correctly.

**Comment by realapril** [comment]
> I think I did have the same issue while trying to compile the aar file with WSL. It has to do with the `mediapipe_aar.bzl` file. That file has bash code and in my case the EOL configuration was preventing it to run correctly. It was `CRLF` and it has to be `LF` to be parse correctly.

THANKYOU it finally WORKS
I used ```dos2unix``` to change CRLF to LF

**Comment by artifutechharbhajan** [comment]
Hi @PLHieu  , I'm facing the same issues. Have you solved your problem? @realapril , @salvadorld0 , @cdibona or anyone who have the solution, please share here.
Thanks

**Comment by sgowroji** [comment]
We have very clear documentation on building the Android AAr [here](https://google.github.io/mediapipe/getting_started/android_archive_library.html#mediapipe-android-archive). Please reach us if you still have any further queries on the above or reopen.
