### ISSUE TITLE
How to show the x,y,z coordinate text on handtracking for ios app?

### ISSUE THREAD

**Issue by Zouken** [google/mediapipe#1191]
I finally installed the handtracking app on my ios devices. 
And I wanna see the x,y,z coordinate of each landmark on my screen.
Should I edit the viewcontroller.mm file in /mediapipe/mediapipe/examples/ios/handtrackinggpu?
How can I do? Please help me...

**Comment by sgowroji** [comment]
Hi @Zouken, For coordinates you can have a look at [this](https://github.com/google/mediapipe/blob/master/mediapipe/examples/ios/handtrackinggpu/HandTrackingViewController.mm#L43-L48).  And display them according as per your component like UITextView. Please reach us if you still have any queries. Thanks!
