### ISSUE TITLE
Running objectdetection android app error

### ISSUE THREAD

**Issue by AbdElhamidNabeel** [google/mediapipe#1194]
I have successfully build and sync the application but while i run the application from the android studio i get this error
I'm using ubuntu 20.04
Android-sdk version 28
Android-ndk-bundle r18b

Waiting for target device...
Invoking mobile-install...
Command: /usr/bin/bazel mobile-install --tool_tag=ijwb:AndroidStudio --device GBT4C19117003514:tcp:5037 "--adb_arg=-s " --adb_arg=GBT4C19117003514 --adb /home/abd-elhamid/Android/Sdk/platform-tools/adb --curses=no --color=yes --progress_in_terminal_title=no -c opt --config=android_arm64 --build_event_binary_file=/tmp/intellij-bep-d0a77d7c-c1bb-40f1-b515-75588c1c7607 --nobuild_event_binary_file_path_conversion -- //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu:objecttrackinggpu -c opt --config=android_arm64 --nolaunch_app

Loading: 
Loading: 0 packages loaded
ERROR: Skipping 'opt': no such target '//:opt': target 'opt' not declared in package '' defined by /home/abd-elhamid/mediapipe/BUILD.bazel
ERROR: no such target '//:opt': target 'opt' not declared in package '' defined by /home/abd-elhamid/mediapipe/BUILD.bazel
INFO: Elapsed time: 0.221s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)

**Comment by sgowroji** [comment]
Hi @AbdElhamidNabeel, Could you please test the above installation with the latest release and let us know if you still face the same error. Thanks!
