### ISSUE TITLE
How to Extract the Object's Name from a Graph in ObjectDetectionGPU(Android)

### ISSUE THREAD

**Issue by ZZZhaowendao** [google/mediapipe#1199]
Hi,enthusiastic mediapipe guys,
I have successfully run the **objectdetectiongpu example by AAR**.Now I need to **extract the name of the object detected**,so it can be used in the MainActivity.java.
In particular, the keyboard is recognized in front of the camera.At the same time,I wonder how can I **get the String "keyboard" and the recognition rate in the code**? I need to apply these two pieces of data to my own program.
How can I do this correctly please : )

**Comment by sgowroji** [comment]
Hi @ZZZhaowendao, I request you to do the above use case with [KNIFT](https://google.github.io/mediapipe/solutions/knift#mediapipe-knift) solution, Which exactly suits your requirement. Thanks!

**Comment by sgowroji** [comment]
Hi @ZZZhaowendao, Did you get a chance to go through the above comment. Thanks!
