### ISSUE TITLE
how can i use single image as input

### ISSUE THREAD

**Issue by Nicol-Bolas** [google/mediapipe#12]
i want to test your BlazeFace on a single image, which calculator should i use? or take an opencv Mat as input of ImageTransformationCalculator?

**Comment by chuoling** [comment]
You could try modifying the desktop TFLite object detection example in https://github.com/google/mediapipe/blob/master/mediapipe/docs/object_detection_desktop.md#tensorflow-lite-object-detection-demo to take a single image as input, e.g., replacing OpenCvVideoDecoderCalculator with https://github.com/google/mediapipe/blob/master/mediapipe/calculators/image/opencv_encoded_image_to_image_frame_calculator.cc.

**Comment by mgyong** [comment]
@Nicol-Bolas  Thanks for using MediaPipe. My team would love to get feedback from you about your use of MediaPipe

It would be great if you could answer the below questions

What is your use case for MediaPipe?
Any feedback about how easy or difficult it is to use MediaPipe?
Thanks
Ming
