### ISSUE TITLE
How do I access the landmark points in the java layer?

### ISSUE THREAD

**Issue by tmnbhat** [google/mediapipe#120]
I am trying to send POST requests to a server based on gestures (hand tracking example) recognized through the landmark points. I saw that the landmark points are available in most calculators but transferring them to the java layer (specifically MainActivity.java) seems tricky. Any suggestions would be great!

**Comment by lcycoding** [comment]
Try to revise calculator itself sending out vector<float>(or any other compatible forms) represents landmark points
Then adding PacketCallback like this to get the data from graph
At least this works for me

```
processor.getGraph().addPacketCallback("output_vector", new PacketCallback() {
       @Override
       public void process(Packet packet) {
              float[] dest = PacketGetter.getFloat32Vector(packet);
              // Do something with the landmark point
       }
});
```

**Comment by liyuming1978** [comment]
@lcycoding   how to add "output_vector" in graph?  would you please share more detail?  thx very much!!!

**Comment by liyuming1978** [comment]
I do know how to get face detector result too...

**Comment by lcycoding** [comment]
@liyuming1978 in your node.cc
How about just adding outputs in GetContract()
```
  if (cc->Outputs().HasTag("OUT_VEC")) {
    cc->Outputs().Tag("OUT_VEC").Set<std::vector<float>>();
  }
```

And in process()
```
 cc->Outputs().Tag("OUT_VEC").Add(output_vecs.release(),
                                         cc->InputTimestamp());
```

The other part is pure c code part, just code it...

**Comment by liyuming1978** [comment]
@lcycoding  thx so much!  that works,  simple and rough.:)

**Comment by hejing-maker** [comment]
> @lcycoding  thx so much!  that works,  simple and rough.:)

      Have you implemented it? Can you share how do access the landmark points in the java layer?
