### ISSUE TITLE
AnnotationOverlayCalculator render slow

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#1202]
![image](https://user-images.githubusercontent.com/17869361/96096718-b7a00180-0f02-11eb-9d3b-4261d3d511c4.png)
![image](https://user-images.githubusercontent.com/17869361/96096814-d30b0c80-0f02-11eb-9257-65c486134b9a.png)

Why glDrawArrays in the AnnotationOverlayCalculator file need 30ms to complete? This code run in android is faster than ios which only needs less than 1ms to complete, I am really confused why this is the case.

**Comment by mcclanahoochie** [comment]
It would really depend on the device and GPU. Is the code compiled with `-c opt` ? 
There is an option to try that should speed things up: 
`gpu_scale_factor: 0.5` 
https://github.com/google/mediapipe/blob/c0124fb83c667917c7bf6a84f442a0136e8f2cf7/mediapipe/graphs/iris_tracking/subgraphs/iris_and_depth_renderer_gpu.pbtxt#L267
This will render at a lower res, and transfer less memory around.

**Comment by sgowroji** [comment]
Assuming the above [comment](https://github.com/google/mediapipe/issues/1202#issuecomment-727122752) resolved your query, We are closing this issue now.
