### ISSUE TITLE
Error running hello_world example on Ubuntu 20.04

### ISSUE THREAD

**Issue by Aprameyah** [google/mediapipe#1204]
I have installed mediapipe as per instructions in the [link](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu) and tried running the hello_world example and Im getting the following error :

> ERROR: /home/sreehari/.cache/bazel/_bazel_sreehari/e592586123a00fe9b5f3e9dfb0d66d90/external/zlib/BUILD.bazel:5:11: undeclared inclusion(s) in rule '@zlib//:zlib':
> this rule is missing dependency declarations for the following files included by 'external/zlib/infback.c':
>   '/usr/lib/gcc/x86_64-linux-gnu/9/include/stddef.h'
>   '/usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h'
>   '/usr/lib/gcc/x86_64-linux-gnu/9/include/syslimits.h'
>   '/usr/lib/gcc/x86_64-linux-gnu/9/include/stdarg.h'

Please provide solution to the above error.
Also It would be a lot of help If the versions of the supporting softwares compatible with Ubuntu 20.04 are provided.

**Comment by jiuqiant** [comment]
Seems like you don't have those gcc header files in `/usr/lib/gcc/x86_64-linux-gnu/9` but zlib assumes this. Probably you need to (re)install gcc9 and make sure you have those header files in `/usr/lib/gcc/x86_64-linux-gnu/9`.

**Comment by Aprameyah** [comment]
@jiuqiant I had checked the location  
> /usr/lib/gcc/x86_64-linux-gnu/9/include/

the files do exist. Do I need to re-install gcc9?

**Comment by Aprameyah** [comment]
Re-installing did the trick, but had to reinstall bazel and python too.

**Comment by S3od22** [comment]
> I have installed mediapipe as per instructions in the [link](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu) and tried running the hello_world example and Im getting the following error :
> 
> 
> 
> > ERROR: /home/sreehari/.cache/bazel/_bazel_sreehari/e592586123a00fe9b5f3e9dfb0d66d90/external/zlib/BUILD.bazel:5:11: undeclared inclusion(s) in rule '@zlib//:zlib':
> 
> > this rule is missing dependency declarations for the following files included by 'external/zlib/infback.c':
> 
> >   '/usr/lib/gcc/x86_64-linux-gnu/9/include/stddef.h'
> 
> >   '/usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h'
> 
> >   '/usr/lib/gcc/x86_64-linux-gnu/9/include/syslimits.h'
> 
> >   '/usr/lib/gcc/x86_64-linux-gnu/9/include/stdarg.h'
> 
> 
> 
> Please provide solution to the above error.
> 
> Also It would be a lot of help If the versions of the supporting softwares compatible with Ubuntu 20.04 are provided.
> 
>

**Comment by sufyan-info** [comment]
I upgraded ubuntu 20.04 to 20.10, and got similar errors.
Reinstalling gcc-9, gcc-10, python, python3, bazel didn't work from me. 
Also did run the opencv setup script again, but that didn't fix the error.

Only fixed my error by deleting the folder:
/home/sufian/.cache/bazel/_bazel_sufian/c06b588acb06bba948443b5f74e53ec2

**Comment by rbtcollins** [comment]
Experienced a failure like this today. The C header files did exist.

I tried:
`bazel clean --discard_analysis_cache` - no result
`rm -rf <cachepath>` - worked

My project .bazelrc:
```
# Show us information about failures.
build --verbose_failures
test --test_output=errors

# Use the disk cache to avoid rebuilding things across bazel server shutdowns
build --remote_download_toplevel

# Include git version info
build --workspace_status_command build/print-workspace-status.sh

try-import %workspace%/user.bazelrc
```

<details>

<summary>Bazel output</summary>

```
bazel run @cargo_raze//:raze -- --manifest-path=/home/robertc/Documents/src/path/to/Cargo.toml
INFO: Invocation ID: f01ceefd-692f-4054-a77c-b1216b3a43cf
INFO: Analyzed target @cargo_raze//:raze (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/robertc/.cache/bazel/_bazel_robertc/f20de9f8c3e7e22bf5b27c5279379703/external/cargo_raze__zlib/BUILD.bazel:33:11: Compiling gzclose.c failed: undeclared inclusion(s) in rule '@cargo_raze__zlib//:zlib':
this rule is missing dependency declarations for the following files included by 'gzclose.c':
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h'
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/limits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/syslimits.h'
Target @cargo_raze//tools:raze failed to build
INFO: Elapsed time: 0.610s, Critical Path: 0.24s
INFO: 8 processes: 8 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

</details>
