### ISSUE TITLE
Local bezel server connection issue on bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

### ISSUE THREAD

**Issue by atulkumarpccs** [google/mediapipe#1205]
![image](https://user-images.githubusercontent.com/13286642/96200257-33eb2100-0fa5-11eb-96b1-8d6bef098484.png)

Facing the above issue, in my opinion, it should build automatically when running through container image

**Comment by Kheiden** [comment]
I have also experienced this issue when attempting to use the [Dockerfile ](https://github.com/google/mediapipe/blob/master/Dockerfile).

I was able to successfully build with bazel by performing the following:

1) Change the bazel version from 3.0.0 to 3.4.0 in the Dockerfile
2) Add the `--batch` flag to the `bazel run` command.

Hopefully this resolves your issue.

**Comment by sgowroji** [comment]
Hi @atulkumarpccs, Let us know if you still facing the above error with the latest release. Thanks!
