### ISSUE TITLE
Enabling tracing and profiling

### ISSUE THREAD

**Issue by shehramjamil** [google/mediapipe#1212]
Can you provide more detail for enabling the tracing and profiling like how to enable the tracing in calculator.proto file ? 
I know the profiler config message is already there in calculator.proto file but I am unable to find the information on how to make the boolean true.

**Comment by shehramjamil** [comment]
I thought , I have to add the configuration in the calculator.proto but I was wrong. 
I have to put the profiler_config{} in the graph file to generate the traces.

**Comment by XinJiang1994** [comment]
Have you solved the problem? I'm also confused about where we should put the profiler_config{}. I tried to put it in the CalculatorGraphConfig (in /mediapipe/framework/calculator.proto) , but it failed to compile. Then I put it in the root of graph file. This time the compile is success, but nothing happened. I still cannot get the trace files. Do you find the solution?

**Comment by shehramjamil** [comment]
Hi,
I have stopped working on this for a long time but here is a tip.
1. Put the profiler config in your main graph on which you are currently working.
2. Double check your mobile device for enabling the writing permissions. Sometimes, our phone is blocking the writing from the app. So check for permissions properly.
