### ISSUE TITLE
Can you specify which camera to use for IOS?

### ISSUE THREAD

**Issue by tonywang531** [google/mediapipe#1214]
I tried a few examples for the IOS, they all work great but all seem to use the front camera. I could not locate a way to flip the camera. Is there a way to specify which camera to use in the code?

**Comment by mgyong** [comment]
@eknight7 any comments on how to modify the hello world code samples for iOS

**Comment by tonywang531** [comment]
<img width="564" alt="Screen Shot 2020-10-21 at 17 11 00" src="https://user-images.githubusercontent.com/51065728/96691986-802ccb80-13c0-11eb-9734-8e1f56a4434d.png">
I have found where to specify the camera position in info.plist (just need to change from front to back). Is there a way to specify which camera to use in real time? For example implement a button and be able to flip the camera when the button is pressed.

**Comment by eknight7** [comment]
Hi, apologies for the delayed response.
To implement a button that switches the camera in real time, you would have to close the existing camera object and video stream, stop the MediaPipe graph. Then, open the alternate camera video stream, restart the MediaPipe graph with this video stream.
The button press will be an event that triggers the app to make the switch. You may find an example of how to implement such a button online, for example: https://stackoverflow.com/questions/53995076/how-to-switch-camera-using-avfoundation

**Comment by eknight7** [comment]
Closing this issue for now. Please reopen if you have further questions. Thank you.
