### ISSUE TITLE
target 'camera2' not declared in package

### ISSUE THREAD

**Issue by thkim0118** [google/mediapipe#1215]
When I updated to 0.7.12, the following issue has occurred in the terminal while generating Android aar.

`no such target '//third_party:camera2': target 'camera2' not declared in package 'third_party'`

Modifying a 'BUILD' file in a 'third_party' folder will build it, but the class associated with the camera will not be available.

Version 0.7.11 works well.

How do we handle this?

**Comment by jiuqiant** [comment]
Try replacing `//third_party:camera2` with `//third_party:camerax_camera2 `

**Comment by thkim0118** [comment]
Thanks for reply.

Every part is declared as follows.
`'//third_party:camerax_camera2'`

Except for one.

Inside the file mediapipe_aar.bzl, `'//third_party:camera2'` is declared.
This is path. `//mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl`

I want to modify the file, how can I change it?

**Comment by jiuqiant** [comment]
Can you try the following:

```
--- a/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
+++ b/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
@@ -145,7 +145,7 @@ cat > $(OUTS) <<EOF
             "//third_party:androidx_core",
             "//third_party:androidx_legacy_support_v4",
             "//third_party:camerax_core",
-            "//third_party:camera2",
+            "//third_party:camerax_camera2",
             "@maven//:com_google_code_findbugs_jsr305",
             "@maven//:com_google_flogger_flogger",
             "@maven//:com_google_flogger_flogger_system_backend",
```

**Comment by thkim0118** [comment]
It's working good with your advice.

Thank you :)

**Comment by thkim0118** [comment]
After the modification, I proceeded with the build, and the following issue was found again.

```
Compiling Java headers mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_portrait/libaar_portrait_android_lib-hjar.jar (49 source files) failed (Exit 1) java failed: error executing command external/remotejdk11_macos/bin/java -Xverify:none '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' ... (remaining 112 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/java/com/google/mediapipe/components/CameraXPreviewHelper.java:38: error: symbol not found androidx.camera.lifecycle.ProcessCameraProvider
import androidx.camera.lifecycle.ProcessCameraProvider;
       ^
mediapipe/java/com/google/mediapipe/components/CameraXPreviewHelper.java:103: error: could not resolve ProcessCameraProvider
  private ProcessCameraProvider cameraProvider;
          ^

```

**Comment by jiuqiant** [comment]
> After the modification, I proceeded with the build, and the following issue was found again.
> 
> ```
> Compiling Java headers mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_portrait/libaar_portrait_android_lib-hjar.jar (49 source files) failed (Exit 1) java failed: error executing command external/remotejdk11_macos/bin/java -Xverify:none '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' ... (remaining 112 argument(s) skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox
> mediapipe/java/com/google/mediapipe/components/CameraXPreviewHelper.java:38: error: symbol not found androidx.camera.lifecycle.ProcessCameraProvider
> import androidx.camera.lifecycle.ProcessCameraProvider;
>        ^
> mediapipe/java/com/google/mediapipe/components/CameraXPreviewHelper.java:103: error: could not resolve ProcessCameraProvider
>   private ProcessCameraProvider cameraProvider;
>           ^
> ```

There is one more thing needed. I tested it by myself and updated https://github.com/google/mediapipe/issues/1215#issuecomment-713247150 yesterday. Please take a look at that comment again.

**Comment by jiuqiant** [comment]
Fixed in https://github.com/google/mediapipe/commit/a8d6ce95c4945087dc060760bad6258a7876c76e. You can just do a `git pull` to avoid fixing it manually.

**Comment by thkim0118** [comment]
Thanks 👍 
It's working.
