### ISSUE TITLE
How to reshape Iris Landmark when Iris is half open

### ISSUE THREAD

**Issue by Nvelu048** [google/mediapipe#1216]
I have implemented Iris Recoloring.  

Now when eye is half open, Landmark seems to overlap with Eye lid How to reshape it.  

I expect to have

![image13](https://user-images.githubusercontent.com/24509341/95171015-ea474d00-07d2-11eb-9eac-85b391bf13d1.gif)

like this.

I am getting Iris Landmark overlapping Eye Lid

**Comment by sgowroji** [comment]
Hi @Nvelu048, Could you please respond whether you're looking answer for the above query. Thanks!

**Comment by Nvelu048** [comment]
@sgowroji, One of my colleague implemented this feature.  

And if possible you can solution

**Comment by Nvelu048** [comment]
Duplicate of below issue

https://github.com/google/mediapipe/issues/1181
