### ISSUE TITLE
Examples not working on phone with Mali-G77 GPU

### ISSUE THREAD

**Issue by atiselsts** [google/mediapipe#1218]
I'm trying to run mediapipe on Samsung Galaxy S20 FE phone. According to the specs, it has Mali-G77 MP11 GPU. All examples I tried build fine and the examples that only use CPU work fine, while examples that use GPU show only a black screen.

For example the `facedetectioncpu` example works fine, while `facedetectiongpu` does not.

The GPU[ according to ARM ](https://developer.arm.com/ip-products/graphics-and-multimedia/mali-gpus/mali-g77-gpu)has support for all these API:

> OpenGL® ES 1.1, 2.0, 3.1, 3.2
> Vulkan 1.1
> OpenCL™ 1.1, 1.2, 2.0 Full Profile

**Comment by atiselsts** [comment]
Update: I tried to create a hand tracking app that uses only CPU calculators. Still no luck. (Both variants work on an older phone). 

Is there a way to check whether an app uses GPU? Assuming that I did successfully remove all refs to GPU usage I think this means that GPU is not to blame. Perhaps something to with Android version or toolchain version?

Bazel has version 3.6.0.

Android NDK has version 21.3.6528147

The phone has Android version 10, with latest updates installed.


Here is the excerpt from the BUILD file where I define a new binary graph for CPU based hand tracking.

```
cc_library(
    name = "mobile_calculators_cpu",
    deps = [
        "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/calculators/core:gate_calculator",
        "//mediapipe/calculators/core:merge_calculator",
        "//mediapipe/calculators/core:previous_loopback_calculator",
        "//mediapipe/graphs/hand_tracking/subgraphs:hand_detection_cpu",
        "//mediapipe/graphs/hand_tracking/subgraphs:hand_landmark_cpu",
        "//mediapipe/graphs/hand_tracking/subgraphs:renderer_cpu",
    ],
)

mediapipe_binary_graph(
    name = "hand_tracking_mobile_cpu_binary_graph",
    graph = "hand_tracking_mobile.pbtxt",
    output_name = "hand_tracking_mobile_cpu.binarypb",
    deps = [":mobile_calculators_cpu"],
)

```

**Comment by bboettcher3** [comment]
Same results with an app I'm working on. Our custom graph works fine with all previous phones, but returns no packet callbacks on the S20, and the app freezes when the graph is closed. The demo handtracking app gives a black screen as well on the device.

Device is S20 Ultra 5G (Model # SM-G988B/DS)

No packet callbacks for custom gpu graphs using hand tracking, face detection, face mesh, and iris tracking.

**Comment by bboettcher3** [comment]
@atiselsts Update for you:
Updating mediapipe to 0.8.0 fixes this bug for all graphs except for iris tracking :)
S20 works with hand tracking, face detection and face mesh now with v0.8.0.

**Comment by atiselsts** [comment]
Thanks bboettcher3, seems to be working.
