### ISSUE TITLE
Custom nodes for MediaPipe

### ISSUE THREAD

**Issue by peacheym** [google/mediapipe#1219]
Hi everyone,

I am wondering if there is existing resources demonstrating how to build custom nodes for the MediaPipe graph pipeline.  I would like to have a simple node that simply pushed landmark data out via some (undecided) method. I am not 100% the proper way of doing this in terms of the MediaPipe project.

Thanks!

**Comment by sgowroji** [comment]
Hi @peacheym, Could you please elaborate your use case with complete details. Thanks!
