### ISSUE TITLE
Internal gcc compiler error when run the Hello World desktop example

### ISSUE THREAD

**Issue by Earl-chen** [google/mediapipe#122]
I followed the installation tutorial to install on ubuntu16.04. When the last step was executed, the following error occurred. May I ask the boss, what is the problem?

`Starting local Bazel server and connecting to it...
DEBUG: Rule 'build_bazel_rules_apple' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "6c9fcae7a3597aabd43f28be89466afe0eab18de", shallow_since = "1565379803 -0700" and dropping ["tag"]
DEBUG: Call stack for the definition of repository 'build_bazel_rules_apple' which is a git_repository (rule definition at /home/chengx/.cache/bazel/_bazel_chengx/03075537009721f8d1bae0d873205506/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /home/chengx/CM/HeiHei/mediapipe/WORKSPACE:251:1
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = f977d49a6fb605964661d65c73b930a595f55f1be63d637535e52263a8a5159c
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "f977d49a6fb605964661d65c73b930a595f55f1be63d637535e52263a8a5159c"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/chengx/.cache/bazel/_bazel_chengx/03075537009721f8d1bae0d873205506/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/chengx/CM/HeiHei/mediapipe/WORKSPACE:28:1
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (44 packages loaded, 1181 targets configured).
INFO: Found 1 target...
ERROR: /home/chengx/.cache/bazel/_bazel_chengx/03075537009721f8d1bae0d873205506/external/com_google_protobuf/BUILD:148:1: C++ compilation of rule '@com_google_protobuf//:protobuf' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 39 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from external/com_google_protobuf/src/google/protobuf/stubs/common.h:38,
                 from external/com_google_protobuf/src/google/protobuf/any.h:36,
                 from external/com_google_protobuf/src/google/protobuf/any.cc:31:
/usr/include/c++/5/cmath:1282:3: internal compiler error: Segmentation fault
   copysign(long double __x, long double __y)
   ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 35.050s, Critical Path: 12.41s
INFO: 54 processes: 54 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
`

**Comment by jiuqiant** [comment]
Your error ```/usr/include/c++/5/cmath:1282:3: internal compiler error: Segmentation fault
copysign(long double __x, long double __y)`` seems to be a compiler error. The easiest solution could be either using MediaPipe Docker (an isolated environment) or switching to another gcc compiler, e.g., gcc8.
