### ISSUE TITLE
TfLiteWebGlInferenceCalculator (MediaPipe half-body pose web demo) breaks on some newer iPhones

### ISSUE THREAD

**Issue by yousefamar** [google/mediapipe#1227]
There seems to be something wrong with TfLiteWebGlInferenceCalculator, in that on some devices shader compilation fails. Please see below for the failing shader. Since it's probably all in the wasm, I can't really get to the bottom of it. I would try maybe changing `#version 100` to `#version 300 es`, but [this](https://github.com/google/mediapipe/blob/master/mediapipe/framework/port.h#L45-L51) makes me think that it's probably not that simple and there may be some compile-time considerations.

So far, I can reproduce this on an iPhone 11 Pro Max and an iPhone 12 Pro. Have you guys come across this at all? Do you plan to have different builds for different devices? Not to mention where there's no WebGL support.

```
type.googleapis.com/mediapipe.StatusList='
\xd1\x14\x08\r\x12\xcc\x14\x43\x61lculator::Open() for node \"posetrackingsubgraph__posedetectionsubgraph__TfLiteWebGlInferenceCalculator\" failed: Shader compilation failed: ERROR: 0:52: \'2.0f\' : Floating-point suffix unsupported prior to GLSL ES 3.00
ERROR: 0:52: \'2.0f\' : syntax error
\x00
Problem shader is:
#version 100
#extension GL_EXT_draw_buffers : require
uniform highp sampler2D src_tensor_tex2d0;
uniform highp ivec4 shared_int4s[1];
precision highp int;
#define MOD_MACRO(a, b) ((a) - (b) * ((a) / (b)))
#define ABS_MACRO(a) ((a) >= 0 ? (a) : -(a))
#define MAX_MACRO(a, b) ((a) > (b) ? (a) : (b))
#define MIN_MACRO(a, b) ((a) < (b) ? (a) : (b))
#define TANH_MACRO(a) (exp(2.0 * (a) - 1.0) / exp(2.0 * (a) + 1.0))
#define INIT_FLOAT4(value) vec4(value)
#define INIT_FLOAT(value) float(value)
#define FLOAT4 mediump vec4
#define FLOAT mediump float
#define INIT_ACCUM_FLOAT4(value) vec4(value)
#define INIT_ACCUM_FLOAT(value) float(value)
#define ACCUM_FLOAT4 mediump vec4
#define ACCUM_FLOAT mediump float
#define float4_32b highp vec4
#define float_32b highp float
#define init_float4_32b(value) vec4(value)
#define init_float_32b(value) float(value)
#define int4_32b highp ivec4
#define int_32b highp int
#define init_int4_32b(value) ivec4(value)
#define init_int_32b(value) int(value)
void main() {

        int dst_c[3];
        {
  int temp_var;
  int linear_x = int(gl_FragCoord.x);
  int linear_y = int(gl_FragCoord.y);
  temp_var = linear_x;
  dst_c[2] = MOD_MACRO(temp_var, shared_int4s[0].x);
  dst_c[0] = temp_var / shared_int4s[0].x;
  dst_c[1] = linear_y;
}
;
        int xc_0 = dst_c[0] * 2 + 0; 
        int xc_1 = dst_c[0] * 2 + 1; 
        int yc_0 = dst_c[1] * 2 + 0; 
        int yc_1 = dst_c[1] * 2 + 1; 
        float_32b xf_0 = float(xc_0) / float(shared_int4s[0].y); 
        float_32b xf_1 = float(xc_1) / float(shared_int4s[0].y); 
        float_32b yf_0 = float(yc_0) / float(shared_int4s[0].z); 
        float_32b yf_1 = float(yc_1) / float(shared_int4s[0].z); 
        FLOAT4 res_00 = texture2D(src_tensor_tex2d0, vec2(xf_0, yf_0)); 
        FLOAT4 res_01 = texture2D(src_tensor_tex2d0, vec2(xf_1, yf_0)); 
        FLOAT4 res_10 = texture2D(src_tensor_tex2d0, vec2(xf_0, yf_1)); 
        FLOAT4 res_11 = texture2D(src_tensor_tex2d0, vec2(xf_1, yf_1)); 
        res_00 = 2.0f * res_00 - 1.0f; 
        res_01 = 2.0f * res_01 - 1.0f; 
        res_10 = 2.0f * res_10 - 1.0f; 
        res_11 = 2.0f * res_11 - 1.0f; 

        res_00.w = 0.0; 
        res_01.w = 0.0; 
        res_10.w = 0.0; 
        res_11.w = 0.0; 
  gl_FragData[0] = res_00;
;
  gl_FragData[2] = res_01;
;
  gl_FragData[1] = res_10;
;
  gl_FragData[3] = res_11;
;
}

'])
```

**Comment by yousefamar** [comment]
On that note, do you have plans for cross-browser support anyway? Or is this another case of Chrome or bust? I ask since this is not the only thing — you use some WebGL functions that e.g. aren't supported by latest Safari, e.g. [this](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/texStorage2D) and [this](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/fenceSync), with no fallback. As much as I'm sure we all hate supporting Safari, it's the new IE for any acceptable coverage for a commercial use case (this is one thing PoseNet over tfjs is better at for example). So it would be really great to hear you guys' thoughts/plans on cross-device/browser support.

**Comment by mcclanahoochie** [comment]
The issue appears to be the "f" in the 4 lines `res_00 = 2.0f * res_00 - 1.0f;` (the f should be removed). 

The TfLiteWebGlInferenceCalculator (in general) was verified working on safari for mac desktop, but it appears not much  safari testing was done since this shader was added. The other examples that doesn't use this particular shader do work (like hair segmentation) on safari.

The web addition to mediapipe is still in its early stages, but cross browser/platform support is definitely high on the TODO list, though chrome does sit at the top. There are plans to expand the web integration, and to have the web graph editor be more powerful and be the preferred place for prototyping, but we aren't quite there yet. 

An internal fix for this is coming, and should propagate to the web in the upcoming releases.

Thanks for the feedback.

**Comment by yousefamar** [comment]
That's great, thanks! If you ever need any extra muscle testing on any range of browsers/devices/OSs/GPUs, just let me know

**Comment by yousefamar** [comment]
I noticed that a while ago you added a method for checking if the browser supports WebGL2 with some instructions for enabling it Safari on iOS and MacOS — even with WebGL2, that backend simply won't work on those I don't think, because of other unsupported functions:

https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/fenceSync
https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/texStorage2D

I don't know what the solution to this could be (pure WASM fallback with TensorFlow.js rather than WebGL?) but seeing that method, I wanted to ask if this is something you guys are looking at? Or if support for Safari is in the books for this month's API release that @mgyong has been hinting at (fingers crossed)?

Also, if you haven't heard, support for getUserMedia is currently in WKWebView for iOS 14.3 Beta. Which means soon Chrome and Firefox on iOS will also be a target, so that's even more environments with different quirks to support!

**Comment by yousefamar** [comment]
I saw that a while ago you added a method that checks if the browser supports WebGL2, with instructions for Safari on iOS and Mac on how to enable it if not. I don't think this will make a difference though, as other functions being used aren't supported by Safari:

https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/texStorage2D
https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/fenceSync

I don't know what the solution to this is (tensorflow.js wasm fallback instead of WebGL?) but wanted to ask if this is something you guys are looking at, potentially even before the API release this month that @mgyong hinted at (fingers crossed)?
