### ISSUE TITLE
"thread-local storage is not supported for the current target"error on mac

### ISSUE THREAD

**Issue by jiqimaogou** [google/mediapipe#123]
./mediapipe/framework/legacy_calculator_support.h:87:28: error: thread-local storage is not supported for the current target
    ABSL_CONST_INIT static thread_local C* current_;  // NOLINT
                           ^
./mediapipe/framework/legacy_calculator_support.h:112:1: error: thread-local storage is not supported for the current target
thread_local CalculatorContext*
^
./mediapipe/framework/legacy_calculator_support.h:115:1: error: thread-local storage is not supported for the current target
thread_local CalculatorContract*

mac :10.14.6
xcode:Version 10.3 (10G8)

**Comment by jiuqiant** [comment]
Hi, I just git cloned the latest MediaPipe repo and run `bazel test -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/framework:calculator_graph_test ` on my mac 10.14.6. It works as expected. I guess it's a problem specific to MediaPipe. Here are some similar issues you can find in WebAssembly and TensorFlow repo:
https://github.com/WebAssembly/binaryen/issues/1035
https://github.com/tensorflow/tensorflow/issues/18356
