### ISSUE TITLE
Failed to get package when run Iris-desktop with single image as input. 

### ISSUE THREAD

**Issue by peterjzhou** [google/mediapipe#1230]
I'm trying to run the Iris desktop solution with single image as input: **iris_depth_from_image_desktop**
The input image I used is a grayscale image lena.jpg
![lena](https://user-images.githubusercontent.com/62259166/97136196-b5625200-170f-11eb-9af3-35a91ef34c9e.jpg)

It failed to run the graph. And it also said 'Failed to get packet from output stream 'output_image'. 
The log information is:
```
I20201025 19:24:12.142110 175115712 iris_depth_from_image_desktop.cc:136] Initialize the calculator graph.
I20201025 19:24:12.150590 175115712 iris_depth_from_image_desktop.cc:59] Load the image.
I20201025 19:24:12.152050 175115712 iris_depth_from_image_desktop.cc:63] Start running the calculator graph.
E20201025 19:24:12.155272 175115712 iris_depth_from_image_desktop.cc:156] Failed to run the graph: Failed to get packet from output stream 'output_image'.
```

The command I used to run the solution is:
```
GLOG_logtostderr=1 ./bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_depth_from_image_desktop \
  --input_image_path=./mediapipe/calculators/image/testdata/lena.jpg \
  --output_image_path=./output_images/lena.jpg
```

I also tried with different input images (RGB, with and without human faces), the outputs were the same. 

So does anyone have a similar problem or what can I provide to further locate the problem?

**Comment by mcclanahoochie** [comment]
Hi,

In general, one way to debug graph errors is to enable verbose logging, via adding   `_GLOG_v=2_`   (in addition to, and in the same way as, _GLOG_logtostderr=1_). 

Try: 
```
GLOG_v=2 GLOG_logtostderr=1 ./bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_depth_from_image_desktop \
  --input_image_path=./mediapipe/calculators/image/testdata/lena.jpg \
  --output_image_path=./output_images/lena.jpg
```

For your question,

Using the lena image you linked here, with verbose logging, I get:
```
I20201026 13:04:35.291677 239919104 calculator_graph.cc:936] RecordError called with INTERNAL: Calculator::Process() for node "ImageFilePropertiesCalculator" failed: Error parsing EXIF, code: 1983
```

Note, the all the depth from image demos do require valid exif data for focal length. So if you run 
`exftool lena.jpg` and don't find any field about focal lengths, then it wont work.

I have a sample image from my phone, and this is what mediapipe expects
```
exiftool ~/Downloads/IMG_20200904_133311.jpg  | grep -i focal
Focal Length                    : 4.5 mm
Focal Length In 35mm Format     : 27 mm
Focal Length                    : 4.5 mm (35 mm equivalent: 27.0 mm)
Hyperfocal Distance             : 2.23 m
```
(not all those fields are required, but at least one of "Focal Lengh" or  "Focal Length In 35mm Format" should be there)

Hope that helps.

**Comment by peterjzhou** [comment]
Thank you, problem solved. I succeed with the image taken form my phone.
Btw it seems that some pictures in the mediapipe/calculators/image/testdata/ don't have complete EXIF either.

**Comment by peterjzhou** [comment]
> Hi,
> 
> In general, one way to debug graph errors is to enable verbose logging, via adding `_GLOG_v=2_` (in addition to, and in the same way as, _GLOG_logtostderr=1_).
> 
> Try:
> 
> ```
> GLOG_v=2 GLOG_logtostderr=1 ./bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_depth_from_image_desktop \
>   --input_image_path=./mediapipe/calculators/image/testdata/lena.jpg \
>   --output_image_path=./output_images/lena.jpg
> ```
> 
> For your question,
> 
> Using the lena image you linked here, with verbose logging, I get:
> 
> ```
> I20201026 13:04:35.291677 239919104 calculator_graph.cc:936] RecordError called with INTERNAL: Calculator::Process() for node "ImageFilePropertiesCalculator" failed: Error parsing EXIF, code: 1983
> ```
> 
> Note, the all the depth from image demos do require valid exif data for focal length. So if you run
> `exftool lena.jpg` and don't find any field about focal lengths, then it wont work.
> 
> I have a sample image from my phone, and this is what mediapipe expects
> 
> ```
> exiftool ~/Downloads/IMG_20200904_133311.jpg  | grep -i focal
> Focal Length                    : 4.5 mm
> Focal Length In 35mm Format     : 27 mm
> Focal Length                    : 4.5 mm (35 mm equivalent: 27.0 mm)
> Hyperfocal Distance             : 2.23 m
> ```
> 
> (not all those fields are required, but at least one of "Focal Lengh" or "Focal Length In 35mm Format" should be there)
> 
> Hope that helps.

Thank you, problem solved. I succeed with the image taken form my phone.
Btw it seems that some pictures in the mediapipe/calculators/image/testdata/ don't have complete EXIF either.

**Comment by mcclanahoochie** [comment]
Great! Thanks for the feedback; I've noted this and we will address this to make the examples better

**Comment by Misby** [comment]
I also find this problem,just need the Focal Length In 35mm Format message of EXFI in the image

**Comment by sgowroji** [comment]
As we see the above issue resolved from the [comments](https://github.com/google/mediapipe/issues/1230#issuecomment-716938373). We are closing it now.
