### ISSUE TITLE
Can't get timestamp info in subclass of GlSimpleCalculator

### ISSUE THREAD

**Issue by aaaron7** [google/mediapipe#1231]
Timestamp is a necessary information for most of render system, seems currently there is no way to get timestamp in subclass of GlSimpleCalculator? 

Maybe we can expose CalculatorContext pointer to subclass?  like modify the GlRender to following version :

```
  virtual ::upipe::Status GlRender(const GlTexture& src, const GlTexture& dst, CalculatorContext* cc)= 0;
```

> background: I want to do render by a third party render library in subclass of GlSimpleCalculator, the render library need timestamp to control the render process.

**Comment by sgowroji** [comment]
Hi @aaaron7, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by aaaron7** [comment]
> Hi @aaaron7, Could you please provide the steps to reproduce the above error. Thanks!

It's a design suggestion, not a bug.

**Comment by kuaashish** [comment]
Hello @aaaron7,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
