### ISSUE TITLE
No matching toolchains found for types @bazel_tools

### ISSUE THREAD

**Issue by bannani** [google/mediapipe#1239]
Hi guys. So I followed the instructions from [https://google.github.io/mediapipe/getting_started/building_examples.html#android]([](MediaPipe) Examples)  to build an example of hand tracking with mediapipe. I reinstalled  g++ and it still shows the same error. The installation process was difficult, I had a lot of errors that I fixed them until the last step (run) where I got stuck. i tried also to build with Bazel in Command Line but it was the same error. So here's what the error showed:

`bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip) = 3e6b0691fc57db8217d535393dcc2cf7c1d39fc87e9adb6e7d7bab1483915110
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3e6b0691fc57db8217d535393dcc2cf7c1d39fc87e9adb6e7d7bab1483915110"
DEBUG: Repository rules_foreign_cc instantiated at:
  /home/bigbooss/Desktop/mediapipe/WORKSPACE:39:13: in <toplevel>
Repository rule http_archive defined at:
  /home/bigbooss/.cache/bazel/_bazel_bigbooss/b94c3a95826560b855bc249f7b0d01ea/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = d7c8150cfe290009d7a0a747022380d2a83ace702a6ad2548521f92fb88fe7e0
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "d7c8150cfe290009d7a0a747022380d2a83ace702a6ad2548521f92fb88fe7e0"
DEBUG: Repository rules_cc instantiated at:
  /home/bigbooss/Desktop/mediapipe/WORKSPACE:33:13: in <toplevel>
Repository rule http_archive defined at:
  /home/bigbooss/.cache/bazel/_bazel_bigbooss/b94c3a95826560b855bc249f7b0d01ea/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: While resolving toolchains for target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
INFO: Elapsed time: 5.126s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 40 targets co\
nfigured)`

g++        9.3.0
bazel      3.7.0
Android Studio  4.1.

**Comment by shehramjamil** [comment]
Did you install the sdk and ndk properly and did you set up sdk and ndk paths in workspace properly?

**Comment by bannani** [comment]
thanks for answer me.
Yes, I think I installed them all.

![ndk-sdk](https://user-images.githubusercontent.com/32345105/97789804-c5f44b80-1b99-11eb-81f6-b9ad43c7257c.png)

then i set up the path : 
export ANDROID_HOME=/home/bigbooss/Android/Sdk
export ANDROID_NDK_HOME=/home/bigbooss/Android/Sdk/ndk/21.3.6528147/

**Comment by shehramjamil** [comment]
@bannani 
you can try to solve it by downgrading your ndk version. I experienced the same so I did this.
Try to run the given file in the mediapipe folder 
bash  setup_android_sdk_and_ndk.sh , It will do the rest and setup the paths in the workspace file.

**Comment by Andrec-Dxs** [comment]
@bannani did you manage to get this fixed?

**Comment by Samuel-wei** [comment]
@bannani Did you resolved the problems above what you encounter to? 
I has the same problems.
Could you give some advise, thank you !

**Comment by spoorthysangineni** [comment]
Hi @bannani I am facing the same errors. Did you manage to fix them?

**Comment by NeoLc** [comment]
i have the some problems in **linux**,  i **solved it** by taking the following steps :

```sh
#step1:
./setup_android_sdk_and_ndk.sh

#step2:
vi ~/.bashrc
export ANDROID_HOME=$PATH:$HOME/Android/Sdk
export ANDROID_NDK_HOME=$PATH:$HOME/Android/Sdk/ndk-bundle/android-ndk-r18b

#step3:
bazel  build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu:facemeshgpu

#### INFO: Build completed successfully, 3983 total actions
```

**Comment by sgowroji** [comment]
Hi @bannani and others, Could you please test the above with the latest release of MediaPipe and reach us back if you still see the same error. Thanks!

**Comment by istillloveyourass** [comment]
eRROR: While resolving toolchains for target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu:facemeshgpu: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu:facemeshgpu' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
> 
![2022-02-05 18-41-40 的螢幕擷圖](https://user-images.githubusercontent.com/49576105/152639017-81e56861-b1dc-42b2-a580-4fbb55acb10b.png)

some quesiotn the toolchains have problem,how could I solve this?

**Comment by doitandbedone** [comment]
Seems this is still an issue, the NDK directory tree changed and the scripts need to be updated to reflect this. You can work around it this by using an older version.
Follow these steps:
1.  Open Android Studio and launch the SDK Manager. 
2. Go to "SDK Tools" Tab. 
3. Check the tick mark for "Show Packages",  located at the bottom right, above the buttons.
4. Look for "NDK (Side by Side)" 
5. Install version "21.4.7075529". Seems to be the last version with the expected directory tree.
6. Modify your $ANDROID_NDK_HOME variable to point to the newly installed location either in your terminal or profile. Should be: 
`export $ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.4.7075529`

Hope this helps!

**Comment by TopWork0ut** [comment]
try to use these commands, it helped me,
`echo "android_sdk_repository(name = \"androidsdk\")" >> WORKSPACE`
`echo "android_ndk_repository(name = \"androidndk\", api_level=21)" >> WORKSPACE`

firslty i had skiped this but than i had the same problem as you. So I have written these lines and all now works fine.
More detail here [](https://google.github.io/mediapipe/getting_started/android.html)

**Comment by cancan101** [comment]
Any reason that these lines:
```bazel
android_sdk_repository(name = "androidsdk")
android_ndk_repository(name = "androidndk", api_level=21)
```
aren't just committed to git? i.e. are there cases where you would not want those lines in the `WORKSPACE` file?
