### ISSUE TITLE
provisioning profile ExpirationDate 

### ISSUE THREAD

**Issue by QingyueMeng** [google/mediapipe#124]
When I run the project, I got the error :
`ERROR: /Users/mmm/work/code/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:43:1: ProcessEntitlementsFiles mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp_entitlements.entitlements failed (Exit 1) plisttool failed: error executing command 
  (cd /private/var/tmp/_bazel_mengqingyue/79ee339736a13ca7a780ebfb519ea47f/sandbox/darwin-sandbox/364/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=12.2 \
    XCODE_VERSION_OVERRIDE=10.2.1.10E1001 \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/plisttool/plisttool bazel-out/ios_arm64-dbg/bin/mediapipe/examples/ios/handtrackinggpu/entitlements/HandTrackingGpuApp_entitlementsplisttool-control)
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox
ERROR: On target "//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp_entitlements", provisioning profile ExpirationDate ("2019-09-16T16:58:07") is in the past.`

When I run the project, I got the error :
`ERROR: /Users/mmm/work/code/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:43:1: ProcessEntitlementsFiles mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp_entitlements.entitlements failed (Exit 1) plisttool failed: error executing command 
  (cd /private/var/tmp/_bazel_mengqingyue/79ee339736a13ca7a780ebfb519ea47f/sandbox/darwin-sandbox/364/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=12.2 \
    XCODE_VERSION_OVERRIDE=10.2.1.10E1001 \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/plisttool/plisttool bazel-out/ios_arm64-dbg/bin/mediapipe/examples/ios/handtrackinggpu/entitlements/HandTrackingGpuApp_entitlementsplisttool-control)
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox
ERROR: On target "//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp_entitlements", provisioning profile ExpirationDate ("2019-09-16T16:58:07") is in the past.`

![image](https://user-images.githubusercontent.com/33691506/65390277-1cd10400-dd90-11e9-9f00-51d6e78e5a4c.png)

What should I do? 

What should I do?

**Comment by jiuqiant** [comment]
It seems like your provisioning file is expired on Sep 16, 2019. Can you check if the provisioning file you provide is still valid?

**Comment by QingyueMeng** [comment]
I was confused about it. Because I just run the project successfully on the afternoon in Sep 22, and then it suddently reported the error.

 The provisioning file was generated by another project, and that project is still can be run successfully.

**Comment by jiuqiant** [comment]
You can do `bazel clean --expunge` and retry the build command to see if it solves the problem.
Invalid provisioning file isn't a MediaPipe issue. It's the build tool, Bazel, that throws this error. Since it explicitly tells us that the expiration date is Sep 16, 2019, I recommend double checking your provisioning file again.
