### ISSUE TITLE
Python API additions

### ISSUE THREAD

**Issue by ksanjeevan** [google/mediapipe#1242]
Hi,

I was wondering if someone could share a timeline for the Python API to support additional solutions on top of the `UpperBodyPoseTracking`. For example, I need to use hand tracking for my application and it would be very helpful to know when that might be available.

Thanks!

**Comment by jiuqiant** [comment]
In a few days.

**Comment by mgyong** [comment]
MediaPipe v0.8 - Python solutions APIs for Face Mesh, Hands and Upper body pose released! https://github.com/google/mediapipe/releases/tag/0.8.0 Try the colab https://google.github.io/mediapipe/#mediapipe-in-python
