### ISSUE TITLE
How to retrieve left or right hand data in IOS?

### ISSUE THREAD

**Issue by tonywang531** [google/mediapipe#1245]
I know mediapipe can detect left or right hand in the app because it displays it in the landmark square. However, I could not find such information in the ViewController in both common or the handtrackinggpu folder. Also I believe mediapipe has a confidence interval or probability of hand as well. How to access the hand probability and left or right hand property?

**Comment by aaaron7** [comment]
Haven't carefully investigated, but I think you can get what you want by take a look TfLiteTensorsToClassificationCalculator class implementation and its usage in graphs/hand_tracking/subgraphs/hand_landmark_gpu.pbtxt

**Comment by sgowroji** [comment]
Hi @tonywang531, This is how you can try to get the difference https://google.github.io/mediapipe/solutions/hands.html#multi_handedness
