### ISSUE TITLE
How to Extract the Content of the Object detected from a Graph in ObjectDetectionGPU by AAR 

### ISSUE THREAD

**Issue by ZZZhaowendao** [google/mediapipe#1246]
Hi,enthusiastic mediapipe guys,
I am developing an APP for public welfare，I need help.Now I want to extract **the name** and **the coordinate of the bounding box** of the object detected,so those can be used in the MainActivity.java.
In particular, the keyboard is recognized in front of the camera.At the same time,I wonder how can I get the String **"keyboard"**, **the recognition rate** and **the coordinate of the bounding box** in the code? I need to apply these pieces of data to my own program.
How can I do this correctly please : )
                                                         2020.11.01

**Comment by sgowroji** [comment]
Hi @ZZZhaowendao, Please go through this  [KNIFT solution ](https://google.github.io/mediapipe/solutions/knift#mediapipe-knift) as per your requirement. Thanks!
