### ISSUE TITLE
error: package R does not exist

### ISSUE THREAD

**Issue by JimReno** [google/mediapipe#125]
My bazel , android sdk version and os are:
- bazel version：0.25.0
- android sdk version 29
- android ndk version r17c(I used 20 but got hint that 17 is recommed)
- os: linux ubuntu16.04

When I compile mediapipe on Android Studio, this error occurred:
`ERROR: /mediapipe/mediapipe/examples/android/src/java/google/mediapipe/apps/handtrackinggpu/BUILD:64:1: Couldn't build file mediapipe/examples/android/src/java/google/mediapipe/apps/handtrackinggpu/libmediapipe_lib.jar: Building mediapipe/examples/android/src/java/google/mediapipe/apps/handtrackinggpu/libmediapipe_lib.jar (1 source file) failed (Exit 1)
mediapipe/examples/android/src/java/google/mediapipe/apps/handtrackinggpu/MainActivity.java:74: error: package R does not exist
    setContentView(R.layout.activity_main);`

I followed the [instruction](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md). This issue came out when I was on the step 7.
 
Some warnings occurred are listed below:
- during the Sync: `INFO: From ProtoCompile mediapipe/calculators/util/thresholding_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.`
- After the Sync:  `Updating in-memory state...
Could not read from manifest file: /home/nd/workspace/zjc/mediapipe/AndroidManifest.xml
Sync finished`

**Comment by jiuqiant** [comment]
We never encountered such issue before. Here are my thoughts:
- Can you do a `bazel clean --expunge` and retry?
- Can you delete `/home/nd/workspace/zjc/mediapipe/AndroidManifest.xml` to see if that helps?
- Can you add `import android.R.layout;` to handtrackinggpu/MainActivity.java to see if that solves the problem?

**Comment by jiuqiant** [comment]
Closing due to lack of recent activity.

**Comment by Codeskiin** [comment]
Hey, @jiuqiant , I am still facing this issue can you help me to resolve this, even after importing android.R.layout?

**Comment by GoComputing** [comment]
Hello @khushmanvar, I know I'm two years later, but for people that issued the same problem.

I just discovered that your application (for example, com/google/mediapipe/basic) must be inside a 'java' folder (for the example, the directory looks like java/com/google/mediapipe/basic).

I hope it helps.
