### ISSUE TITLE
Face mesh (desktop live cpu) hangs when adding landmarks to the output stream

### ISSUE THREAD

**Issue by xiao668** [google/mediapipe#1252]
**System information**
Have I written custom code: YES
OS Platform and Distribution: Mac OS Catalina 10.15.7
Bazel version: 3.4.0

**Describe the problem**
Hi, I'm working on the example "**face_mesh_cpu**" **desktop version** with live cam as input. I wanted to output landmark coordinates information, so I added face landmarks to the output stream (I notice there's already an output_stream called "multi_face_landmarks" that is defined in "face_mesh_desktop_live.pbtxt"). However, after I added the **multi_face_landmarks** to the output stream poller in the "**demo_run_graph_main.cc**", the program hangs at **.Next()** function. Below is the detailed steps I did. 

**Source code / logs**
In "demo_run_graph_main.cc":

I first included: `#include "mediapipe/framework/formats/landmark.pb.h".`

Then, I added an output stream poller:
`ASSIGN_OR_RETURN(::mediapipe::OutputStreamPoller output_landmark_poller, graph.AddOutputStreamPoller("multi_face_landmarks"));`

On every frame, check if a packet is available in the output stream:
```
::mediapipe::Packet multi_face_landmarks_packet;
      if (!output_landmark_poller.Next(&multi_face_landmarks_packet)) {
        return ::mediapipe::UnknownError(
            "Failed to get packet from output stream 'multi_face_landmarks'.");
      }
      const auto& multi_face_landmarks = multi_face_landmarks_packet.Get<std::vector<::mediapipe::NormalizedLandmarkList>>();
```

And then print out the landmark information:
```
LOG(INFO) << "Number of face instances with landmarks: " << multi_face_landmarks.size();
      for (int face_index = 0; face_index < multi_face_landmarks.size(); ++face_index) {
        const auto& landmarks = multi_face_landmarks[face_index];
          LOG(INFO) << "Number of landmarks for face" << face_index << ": " << landmarks.landmark_size();
        for (int i = 0; i < landmarks.landmark_size(); ++i) {
            LOG(INFO) << "Landmark" << i << ": " << landmarks.landmark(i).x() << ", " <<
                landmarks.landmark(i).y() << ", " << landmarks.landmark(i).z();
        }
      }
```
The problem is: when I run the code, the program hangs at `output_landmark_poller.Next(&multi_face_landmarks_packet)`

Below is the log from the cmd:
```
I20201104 18:06:07.891413 150449600 face_mesh_desktop_live.cc:61] Initialize the calculator graph.
I20201104 18:06:08.836783 150449600 face_mesh_desktop_live.cc:79] Set up live cam window size.
I20201104 18:06:09.947937 150449600 face_mesh_desktop_live.cc:88] Start running the calculator graph.
I20201104 18:06:09.948626 150449600 face_mesh_desktop_live.cc:99] Start grabbing and processing frames.
...[hanging here]
```
It doesn't produce any errors, just hangs there. I'm not sure what the problem is. It's really hard to trace down since the code is built and run in cmd. But I guess the problem might be because the face landmark detector failed on that frame, and the landmark output stream poller is waiting to get the results, but there's no landmark points returned. I have also worked on some iOS samples, such as **FaceMeshGPUApp** and **FaceEffectApp**, they have no problem of outputting landmark coordinates and wouldn't hang on some frames where the landmark detection fails.

**Comment by bryn-m-hughes** [comment]
I believe your understanding of the problem is correct - Next() works synchronously, and so will wait for the landmarks output. If you look at mediapipe/modules/face_landmark/face_landmark_front_cpu.pbtxt you'll see the following comment:
`# NOTE: there will not be an output packet in the LANDMARKS stream for this
# particular timestamp if none of faces detected. However, the MediaPipe
# framework will internally inform the downstream calculators of the absence of
# this packet so that they don't wait for it unnecessarily.`
This is likely the cause of your problem. I believe this is the same problem as #850 so you might want to look there for solutions.

**Comment by sureshdagooglecom** [comment]
Hi @xiao668 ,
Could you please reproduce the above error with the latest release and let us know if the issue still exists. Thanks!
