### ISSUE TITLE
Do you have python binding for the NVIDIA Jetson Nano?

### ISSUE THREAD

**Issue by lernem** [google/mediapipe#1257]
Are you going to release a python binding which can run on arm64(aarch), for example, the NVIDIA Jetson Nano?

PS: Your latest python module works very well on amd64, it's amazing.

**Comment by jiuqiant** [comment]
We currently don't have a plan to make pypi poackages for arm64.  But, you can follow the instruction (https://google.github.io/mediapipe/getting_started/building_examples#python) to build the python package on Jetson.

**Comment by yockgen** [comment]
I've made it run on Jetson nano after few days of trial and error, take a look on the README:

https://github.com/yockgen/mediapipe_jetson_nano

**Comment by jiuqiant** [comment]
> I've made it run on Jetson nano after few days of trial and error, take a look on the README:
> 
> https://github.com/yockgen/mediapipe_jetson_nano

JFYI, in https://google.github.io/mediapipe/getting_started/python.html#building-mediapipe-python-package,  there is a section about building mediapipe python on aarch64 linux, which links to https://github.com/jiuqiant/mediapipe-python-aarch64 that provide the prebuilt python wheel files and detailed instructions.
