### ISSUE TITLE
mediapipe android build in win10 failed

### ISSUE THREAD

**Issue by menghaocheng** [google/mediapipe#126]
I'm trying to build mediapepe android demo but failed:

(base) D:\doc.bazel\hello\mediapipe>bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28Analyzing: target //meAnINFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu:objectdetectiongpu (127 packages loaded, 11185 targets configured).
INFO: Found 1 target...
Slow read: a 18345904-byte read from C:/users/administrator/_bazel_administrator/6xe6qcvh/external/android_opencv/sdk/native/libs/arm64-v8a/libopencv_java4.so took 5014 ms.
Slow read: a 57251970-byte read from C:/users/administrator/_bazel_administrator/6xe6qcvh/external/remotejdk11_win/lib/src.zip took 8592 ms.
INFO: From Executing genrule @com_github_glog_glog//:logging_h:
select bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/src/glog/logging.h.arm to be the glog logging.h file.
ERROR: C:/users/administrator/_bazel_administrator/6xe6qcvh/external/com_github_gflags_gflags/BUILD:12:1: C++ compilation of rule '@com_github_gflags_gflags//:gflags' failed (Exit 2)
c:\users\administrator\_bazel_administrator\6xe6qcvh\execroot\mediapipe\external\com_github_gflags_gflags\src\util.h(255): error C3861: 'GetTempPathA': identifier not found
Slow read: a 11877669-byte read from C:/users/administrator/_bazel_administrator/6xe6qcvh/external/android_tools/all_android_tools_deploy.jar took 5173 ms.
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu:objectdetectiongpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 713.572s, Critical Path: 57.74s
INFO: 26 processes: 26 local.
FAILED: Build did NOT complete successfully

(base) D:\doc.bazel\hello\mediapipe>

**Comment by jiuqiant** [comment]
Similar to https://github.com/google/mediapipe/issues/91. Unfortunately, MediaPipe doesn't support Windows. If you are only interested in Windows, we support Windows Subsystem for Linux. You can find how to set up MediaPipe in WSL [here](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows-subsystem-for-linux-wsl).

**Comment by menghaocheng** [comment]
I have figured it out in Virtual Box, Thank you!
