### ISSUE TITLE
Making sense of Palm Detector model

### ISSUE THREAD

**Issue by djthegr8** [google/mediapipe#1267]
I have downloaded the Hand Detector model (in tfjs format) from [TFHub](https://tfhub.dev/mediapipe/tfjs-model/handdetector/1/default/1). It outputs an array of `(1,2944,19)`. How do I parse this into predictions and bounding boxes??

**Comment by mgyong** [comment]
Please ask your question in the tfjs repo issues https://github.com/tensorflow/tfjs/issues . Thanks
