### ISSUE TITLE
Extracting hand detection landmarks 

### ISSUE THREAD

**Issue by rohabimbesat** [google/mediapipe#1269]
Hi , 
I just wanted to know if there is a way to extract the hand landmarks of an input video per frame and how I can go about doing that.

**Comment by AIdeveloper-oz** [comment]
Hi rohabimbesat, were you able to extract the coordinates of the hand landmarks? I m stuck with the same issue. Can you suggest me any solutions to extract the finger coordinates in any formats like json, list, dict, etc?

**Comment by rohabimbesat** [comment]
yes i used an API for python, you can find instructions here
https://github.com/google/mediapipe/releases/tag/0.8.0
personally, i used json as my file format
