### ISSUE TITLE
Python Face Landmark Example mistaken.

### ISSUE THREAD

**Issue by sca-shota-sato** [google/mediapipe#1270]
I found a mistake in the [Python Face Landmark Example](https://google.github.io/mediapipe/solutions/face_mesh#python).

Now
```
cv2.imwrite('/tmp/annotated_image' + str(idx) + '.png', image)
```
Correctly
```
cv2.imwrite('/tmp/annotated_image' + str(idx) + '.png', annotated_image)
```

**Comment by mgyong** [comment]
Thanks will be updating the documentation
