### ISSUE TITLE
How to Extract the Content of the Object detected from a Graph

### ISSUE THREAD

**Issue by ZZZhaowendao** [google/mediapipe#1272]
Hi,enthusiastic mediapipe guys,
I want to extract **the name** and the coordinate of the bounding box of the object detected,so those can be used in the MainActivity.java.
In particular, the keyboard is recognized in front of the camera.At the same time,I wonder how can I get the String **"keyboard"**, the recognition rate and the coordinate of the bounding box in the code? I need to apply these pieces of data to my own program.
How can I do this correctly please : )
11.9

**Comment by sgowroji** [comment]
Hi @ZZZhaowendao, Did you get a chance to go through this  [KNIFT](https://google.github.io/mediapipe/solutions/knift.html). Thanks!
