### ISSUE TITLE
Python hand landmark tracking fails with GPU 

### ISSUE THREAD

**Issue by dimkastan** [google/mediapipe#1273]
Dear all
I am trying to modify the python landmark demo to work with GPU acceleration.
The platform I am working is a jetson nano.

Following the steps proposed [here](https://github.com/google/mediapipe/issues/1042) I modified the `setup.py` to include the gpu version of the hand_landmark_tracking in the binary graphs as follows:
```
class BuildBinaryGraphs(build.build):
  """Build binary graphs for Python examples."""

  def run(self):
    _check_bazel()
    binary_graphs = [
        'face_landmark/face_landmark_front_cpu',
        'hand_landmark/hand_landmark_tracking_gpu', 
        'pose_landmark/pose_landmark_upper_body_smoothed_cpu'
    ]
```

Also, I added the required arguments in bazel command:

```
bazel_command = [
        'bazel',
        'build',
        '--compilation_mode=opt',
        '--copt=-DMESA_EGL_NO_X11_HEADERS',
        '--copt=-DEGL_NO_X11',
        '--action_env=PYTHON_BIN_PATH=' + sys.executable,
        os.path.join('mediapipe/modules/', graph_path),
    ]
```

Finally I modified the /python/BUILD to include some calculators to allow GPU related operations by adding the following two lines:

```
   "//mediapipe/gpu:gpu_buffer_to_image_frame_calculator",
        "//mediapipe/gpu:image_frame_to_gpu_buffer_calculator"

```
Also, in `mediapipe/python/solutions/hands.py` I added the GPU version of the hand_landmark_tracking as follows:
`BINARYPB_FILE_PATH = 'mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu.binarypb'`

Additionally I followed [this](https://github.com/google/mediapipe/issues/1042) discussion and I switched from CPU to GPU at
`./mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu.pbtxt`
resulting into the attached file 
[hand_landmark_tracking_gpu.pbtxt.txt](https://github.com/google/mediapipe/files/5510583/hand_landmark_tracking_gpu.pbtxt.txt)

I tried to run the following code snippet:

```
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands

# For static images:
hands = mp_hands.Hands(static_image_mode=True, max_num_hands=2,   min_detection_confidence=0.7)

cap = cv2.VideoCapture("video.avi")
status, frame = cap.read()
results = hands.process(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
```

Then I got the following error when trying to process a single image frame:

```
E20201109 15:22:03.518505  6691 calculator_graph.cc:770] INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "palmdetectiongpu__ImageToTensorCalculator" failed: Only BGRA/RGBA textures are supported, passed format: 24
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/hands.py", line 228, in process
    return super().process(input_data={'image': image})
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solution_base.py", line 292, in process
    self._graph.wait_until_idle()
ValueError: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "palmdetectiongpu__ImageToTensorCalculator" failed: Only BGRA/RGBA textures are supported, passed format: 24
```

If I convert the input image to BGRA, then I am getting another error as `mediapipe/python/solution_base.py` is waiting for RGB (three channel image)

```
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/hands.py", line 228, in process
    return super().process(input_data={'image': image})
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solution_base.py", line 280, in process
    raise ValueError('Input image must contain three channel rgb data.')
ValueError: Input image must contain three channel rgb data
```

Do you have any suggestions on how to cope with the formats required by the graph?
Ideally this should be fixed directly from the graph without any modification (e.g. adding a conversion from RGB to RGBA ? )

**Comment by jiuqiant** [comment]
hand_landmark_tracking_gpu now takes gpu buffer as input. For taking an image frame, you need to add an [ImageFrameToGpuBufferCalculator](https://github.com/google/mediapipe/blob/61bc4556af586bb3837f17187568d1345b3ee8f5/mediapipe/gpu/image_frame_to_gpu_buffer_calculator.cc) to the hand_landmark_tracking_gpu graph to do the conversion.

Try something like the following:
```
--- a/mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu.pbtxt
+++ b/mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu.pbtxt
@@ -8,7 +8,7 @@

 type: "HandLandmarkTrackingGpu"

-# GPU image. (GpuBuffer)
+# CPU image.
 input_stream: "IMAGE:image"

 # Max number of hands to detect/track. (int)
@@ -51,6 +51,12 @@ node {
   output_stream: "prev_has_enough_hands"
 }

+node: {
+  calculator: "ImageFrameToGpuBufferCalculator"
+  input_stream: "image"
+  output_stream: "gpu_buffer"
+}
+
 # Drops the incoming image if the previous image had at least N hands.
 # and skipping palm detection is enabled.
 # Otherwise, passes the incoming image through to trigger a new round of palm
@@ -66,7 +72,7 @@ node {
 }
 node {
   calculator: "GateCalculator"
-  input_stream: "image"
+  input_stream: "gpu_buffer"
   input_stream: "DISALLOW:skip_detection"
   output_stream: "palm_detection_image"
   options: {
@@ -156,7 +162,7 @@ node {
 # Extracts image size.
 node {
   calculator: "ImagePropertiesCalculator"
-  input_stream: "IMAGE_GPU:image"
+  input_stream: "IMAGE_GPU:gpu_buffer"
   output_stream: "SIZE:image_size"
 }

@@ -168,7 +174,7 @@ node {
 node {
   calculator: "BeginLoopNormalizedRectCalculator"
   input_stream: "ITERABLE:hand_rects"
-  input_stream: "CLONE:0:image"
+  input_stream: "CLONE:0:gpu_buffer"
   input_stream: "CLONE:1:image_size"
   output_stream: "ITEM:single_hand_rect"
   output_stream: "CLONE:0:image_for_landmarks"
@@ -231,7 +237,7 @@ node {
 # timestamp bound update occurs to jump start the feedback loop.
 node {
   calculator: "PreviousLoopbackCalculator"
-  input_stream: "MAIN:image"
+  input_stream: "MAIN:gpu_buffer"
   input_stream: "LOOP:hand_rects_from_landmarks"
   input_stream_info: {
     tag_index: "LOOP"
```

Disclaimer: I didn't test this change by myself.

**Comment by dimkastan** [comment]
Hi @jiuqiant and thanks for your reply.
I tried your patch which allowed me to pass a CPU image from python however, I am getting the following error.

```
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2


>>> import mediapipe as mp
>>> mp_drawing = mp.solutions.drawing_utils
>>> mp_hands = mp.solutions.hands
>>> 
>>> # For static images:
... hands = mp_hands.Hands(static_image_mode=True, max_num_hands=2,   min_detection_confidence=0.7)
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:324] Warning parsing text-format mediapipe.CalculatorGraphConfig: 96:5: text format contains deprecated field "use_gpu"
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20201110 08:58:52.798225  8481 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 5
I20201110 08:58:52.845643  8500 gl_context.cc:324] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 32.4.3)
I20201110 08:58:52.845952  8481 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 5
I20201110 08:58:52.858404  8501 gl_context.cc:324] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 32.4.3)
>>> 
>>> cap = cv2.VideoCapture("video.avi")
>>> status, frame = cap.read()
INFO: Created TensorFlow Lite delegate for GPU.
>>> results = hands.process(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))

E20201110 08:59:02.349592  8481 calculator_graph.cc:770] INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "palmdetectiongpu__ImageToTensorCalculator" failed: Only BGRA/RGBA textures are supported, passed format: 24
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/hands.py", line 228, in process
    return super().process(input_data={'image': image})
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solution_base.py", line 292, in process
    self._graph.wait_until_idle()
ValueError: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "palmdetectiongpu__ImageToTensorCalculator" failed: Only BGRA/RGBA textures are supported, passed format: 2
```

It seems that now the CPU image is successfully passed to to graph however the format in palmdetectiongpu__ImageToTensorCalculator is not BGRA/RGBA.

**Comment by cmfcm** [comment]
Hi, I think the possible reason is, when converting image frame to gpu buffer,  [gpu_buffer_format.cc](https://github.com/google/mediapipe/blob/61bc4556af586bb3837f17187568d1345b3ee8f5/mediapipe/gpu/gpu_buffer_format.cc) will check like this:  
```
case ImageFormat::SRGB:
      return GpuBufferFormat::kRGB24;
case ImageFormat::SRGBA:
      // TODO: verify we are handling order of channels correctly.
      return GpuBufferFormat::kBGRA32;
```
Therefore, maybe writing a new calculator to convert the image to RGBA will help? But I haven't tried it yet.

**Comment by dimkastan** [comment]
Couldn't this be solved by changing the way that python is passing the image to the graph or by using existing calculators? 
@jiuqiant do you have any suggestion?

**Comment by jiuqiant** [comment]
You can modify solution_base.py to accept rgba data and make an image frame with SRGBA format (you can do ImageFormat.SBGRA as well). Then, in your own code, send a RGBA image to the API.

```
--- a/mediapipe/python/solution_base.py
+++ b/mediapipe/python/solution_base.py
@@ -276,8 +276,8 @@ class SolutionBase:
     self._simulated_timestamp += 33333
     for stream_name, data in input_dict.items():
       if self._input_stream_type_info[stream_name] == _PacketDataType.IMAGE:
-        if data.shape[2] != RGB_CHANNELS:
-          raise ValueError('Input image must contain three channel rgb data.')
+        if data.shape[2] != 4:
+          raise ValueError('Input image must contain three channel rgba data.')
         self._graph.add_packet_to_input_stream(
             stream=stream_name,
             packet=self._make_packet(_PacketDataType.IMAGE,
@@ -457,7 +457,7 @@ class SolutionBase:
                    data: Any) -> packet.Packet:
     if packet_data_type == _PacketDataType.IMAGE:
       return packet_creator.create_image_frame(
-          data, image_format=image_frame.ImageFormat.SRGB)
+          data, image_format=image_frame.ImageFormat.SRGBA)
     else:
       return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
```


If it doesn't work, there is a calculator (https://github.com/google/mediapipe/blob/a2a63e387680c090f76072864a107647e874d390/mediapipe/calculators/image/set_alpha_calculator.cc) to set the alpha channel in the graph. However, adding this calculator to graph needs some additional changes in the source code.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by TannerYork** [comment]
Hi @jiuqiant, it seems you're the person to ask for jetson GPU support.

I've successfully built and ran mediapipe with the CPU on my Jetson Xavier but I've failed to get the hand tracking to work using GPU through the python [example](https://google.github.io/mediapipe/solutions/hands.html). I've followed issues #1042, #1651, #1344, and everything works up until I need to modify the .pbtxt file to work with GPU because all of those issues are related to other graphs and not the hand tracking graph.

I was hoping this issue would finally be the solution but it appears like it was close to a solution but was never found. Is there another issue that has the changes needed to make to the hand_landmark_tracking_gpu.pbtxt to work in the pymediapipe2 python build that I'm not finding? Also, It seems like the other modules didn't need to change to a GPU buffer so I'm also wondering why the hand tracking is different and doesn't use input_video like graphs for other solutions like the body pose?

I commented first because I didn't think there was a need for another issue but I can create one if there is.

**Comment by AndreV84** [comment]
was there any solution figured out?

**Comment by AndreV84** [comment]
@sgowroji  What exactly is the solution?

**Comment by lukeaparker** [comment]
Hello, we followed the [tutorial](https://github.com/jiuqiant/mediapipe_python_aarch64) and successfully got the mediapipe python API working on arch64. Now we are trying to get GPU support working, and to do so we followed the comments above. We've gotten to the point where we are trying to modify the graph file, but the diff patch provided fails to execute. We are using version 0.8.1 of mediapipe, would this be causing the issue? What version are you using?

**Comment by TannerYork** [comment]
I'm having the same issue as above. I'm also using version 0.8.1 of mediapipe on arch64.

**Comment by TannerYork** [comment]
Looks there's a working diff file found [here](https://github.com/google/mediapipe/issues/1042#issuecomment-829267239) in the original issue. I haven't tried it but it seems like it's working for others.

**Comment by jhoecker** [comment]
Hi all,
just for the record: Using the [patch](https://github.com/google/mediapipe/issues/1042#issuecomment-829267239) from @VLorin as linked by @TannerYork and the [patch](https://github.com/google/mediapipe/issues/1273#issuecomment-724857226) from @jiuqiant works with a jetson nano with JetPack 4.5.1 (cuda-10.2) and mediapipe at commit ae05ad0. Just convert your images to RGBA before passing it to mediapipe. For the python interface setup I used the changes posted in #2041 and the notes from https://github.com/jiuqiant/mediapipe_python_aarch64 for the adaptions for the Jetson.

Btw: I would like to thank the mediapipe authors for this great piece of software and everybody in this friendly community!
