### ISSUE TITLE
YouTube8M install doc missed

### ISSUE THREAD

**Issue by gaoruiyang** [google/mediapipe#1274]
In README doc https://github.com/google/mediapipe/tree/master/mediapipe/examples/desktop/youtube8m ,
the install doc https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md missed.
Could you plz update this one?

**Comment by jiuqiant** [comment]
Will do. It is moved to https://github.com/google/mediapipe/blob/master/docs/getting_started/install.md.
