### ISSUE TITLE
How can I get the "detection_confidence" and the "tracking_confidence" per each frame?

### ISSUE THREAD

**Issue by AntonioDomenech** [google/mediapipe#1277]
I'm using the Python hand tracking solution in Ubuntu.

I would like to know how can I get the information of "detection_confidence" and "tracking_confidence" per each frame of the webcam. The idea is to get this information to later be able to set the "min_detection_confidence" and the "min_tracking_confidence" depending on the webcam of the user.

Thank you very much!

**Comment by sgowroji** [comment]
Hi @AntonioDomenech, Could you please respond whether you still looking for the above query. Thanks!

**Comment by AntonioDomenech** [comment]
I never solved it but I don't need it anymore.

**Comment by sgowroji** [comment]
Thank you for the update. We are closing this now.
