### ISSUE TITLE
Hello World working, but all other examples not running on osx macbook pro with webcam

### ISSUE THREAD

**Issue by kiprock** [google/mediapipe#1278]
Hello, 

Installed all dependencies as listed on the webpage. Hello World works, but when I run any other app that accesses the camera, I am seeing the following:

I20201109 21:10:23.914692 219340224 demo_run_graph_main.cc:78] Start running the calculator graph.
I20201109 21:10:23.914885 219340224 demo_run_graph_main.cc:83] Start grabbing and processing frames.
2020-11-09 21:10:24.905 face_detection_cpu[1443:30218] Can't find surface
2020-11-09 21:10:24.905 face_detection_cpu[1443:30218] Trying to get Surface
2020-11-09 21:10:24.905 face_detection_cpu[1443:30218] Unable to lookup surface
2020-11-09 21:10:24.905 face_detection_cpu[1443:30218] Surface is 0x0
I20201109 21:10:24.910406 219340224 demo_run_graph_main.cc:135] Shutting down.

This is a macbook Pro with internal webcam

Any ideas for debugging?

**Comment by mcclanahoochie** [comment]
you can try enabling verbose logging:
`$ GLOG_v=2  GLOG_logtostderr=1 ./bazel-bin/mediapipe/....`

does Photobooth work?

if you have a newer model, you may be running into this issue https://github.com/google/mediapipe/issues/477#issuecomment-695921839

**Comment by sgowroji** [comment]
Hi @kiprock, Did u try the above comment. Thanks!
