### ISSUE TITLE
Issue while testing

### ISSUE THREAD

**Issue by PushpakChulet** [google/mediapipe#1282]
Exception: Field currentActivity or type signature  not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223>:0)
UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223>:0)
UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223>:0)
UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223>:0)
UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223>:0)
UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223>:0)

**Comment by sgowroji** [comment]
Hi @PushpakChulet, Could you please test the above with the latest release and let us know, whether the above issue still exists. If persists, Please share us the complete steps to reproduce it. Thanks!
