### ISSUE TITLE
YouTube8M inference error

### ISSUE THREAD

**Issue by gaoruiyang** [google/mediapipe#1283]
When I run command:
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/youtube8m/model_inference \
  --calculator_graph_config_file=mediapipe/graphs/youtube8m/yt8m_dataset_model_inference.pbtxt \
  --input_side_packets=tfrecord_path=/tmp/mediapipe/trainpj.tfrecord,record_index=0,desired_segment_size=5 \
  --output_stream=annotation_summary \
  --output_stream_file=/tmp/summary \
  --output_side_packets=yt8m_id \
  --output_side_packets_file=/tmp/yt8m_id

I got this error:
I20201111 15:38:47.212157 19783 simple_run_graph_main.cc:124] Initialize the calculator graph.
E20201111 15:38:47.212530 19783 simple_run_graph_main.cc:149] Failed to run the graph: Input side packet "lapped_tensor_buffer_calculator_options" of Calculator "[LappedTensorBufferCalculator, input stream: feature_tensor, and output stream: lapped_feature_tensor]" expected a packet of type "mediapipe::LappedTensorBufferCalculator" but the connected output side packet will be of type "mediapipe::LappedTensorBufferCalculatorOptions"

Could you help me solve this case plz?

**Comment by jiuqiant** [comment]
Whoops, the following fix should work. Will release this in the coming release.

```
--- a/mediapipe/calculators/tensorflow/lapped_tensor_buffer_calculator.cc
+++ b/mediapipe/calculators/tensorflow/lapped_tensor_buffer_calculator.cc
@@ -132,7 +132,7 @@ REGISTER_CALCULATOR(LappedTensorBufferCalculator);
   if (cc->InputSidePackets().HasTag(kCalculatorOptions)) {
     cc->InputSidePackets()
         .Tag(kCalculatorOptions)
-        .Set<LappedTensorBufferCalculator>();
+        .Set<LappedTensorBufferCalculatorOptions>();
   }
   cc->Outputs().Index(0).Set<tf::Tensor>(
       // Output tensorflow::Tensor stream with possibly overlapping steps.
```

**Comment by gaoruiyang** [comment]
> Whoops, the following fix should work. Will release this in the coming release.
> 
> ```
> --- a/mediapipe/calculators/tensorflow/lapped_tensor_buffer_calculator.cc
> +++ b/mediapipe/calculators/tensorflow/lapped_tensor_buffer_calculator.cc
> @@ -132,7 +132,7 @@ REGISTER_CALCULATOR(LappedTensorBufferCalculator);
>    if (cc->InputSidePackets().HasTag(kCalculatorOptions)) {
>      cc->InputSidePackets()
>          .Tag(kCalculatorOptions)
> -        .Set<LappedTensorBufferCalculator>();
> +        .Set<LappedTensorBufferCalculatorOptions>();
>    }
>    cc->Outputs().Index(0).Set<tf::Tensor>(
>        // Output tensorflow::Tensor stream with possibly overlapping steps.
> ```

Case solved.
Thank you so much!
