### ISSUE TITLE
Error occurs if use hexadecimal in Visualizer.

### ISSUE THREAD

**Issue by H1Gdev** [google/mediapipe#1284]
# Graph

Create the following graph based on this [Example](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/constant_side_packet_calculator.cc#L33)

```protobuf
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:packet"
  options: {
    [mediapipe.ConstantSidePacketCalculatorOptions.ext]: {
      packet { int_value: 0x02 }
    }
  }
}
```

# Error

```txt
Editor Parse error at line 6 column 32: Expected ':' or '{'.
```

**Comment by sgowroji** [comment]
Hi @H1Gdev, Could you please respond if you still looking resolution for the above query. Thanks!

**Comment by H1Gdev** [comment]
I hope this issue will be fixed as soon as possible...

**Comment by mhays-google** [comment]
Fix is complete.  Will stage by EOD today (Aug 3)

**Comment by H1Gdev** [comment]
Thanks !
Fixed this issue.

![a](https://user-images.githubusercontent.com/11144112/128102832-4d0649e1-9fb0-4d2f-9dc1-523dcef17929.png)
Is colors correct ? (white and blue)

**Comment by mhays-google** [comment]
I did a once over... there's a bit of an ordering issue and I'll circle
back around and troubleshoot.  I have a few other parser things to work on.

**Comment by mhays-google** [comment]
Hex numbers should syntax-color correctly now
