### ISSUE TITLE
[low priority] [documentation] Correction required for hyperlink for Awesome Mediapipe?

### ISSUE THREAD

**Issue by inspire99** [google/mediapipe#1285]
![awesome](https://user-images.githubusercontent.com/18457700/98812179-04b2bd00-2448-11eb-9e70-367de829e30a.png)
In the above image, we can see that, at 3 places, the links to awesome mediapipe - point to home page of mediapipe.dev, instead of https://github.com/mgyong/awesome-mediapipe.

If my understanding is correct, it should be corrected to point to https://github.com/mgyong/awesome-mediapipe.
Thank you for reading.

**Comment by mgyong** [comment]
mediapipe.org points to -> https://github.com/mgyong/awesome-mediapipe
