### ISSUE TITLE
Request for abstracting graphics api

### ISSUE THREAD

**Issue by ashikns** [google/mediapipe#1286]
Currently mediapipe uses Opengl ES for most of the gpu work. Can this be abstracted such that graphics api is a platform specific implementation. Currently I run mediapipe on windows using Angle as the intermediate layer. Essentially I want to replace that with DirectX. 

I realize this probably makes it not work with the tflite calculators, but that's okay for me. I intend to replace them with DirectML calculators. This is just a feature request for future. Thanks for the awesome work you guys have done so far :)

**Comment by sgowroji** [comment]
Hi @ashikns, Could you please respond whether you still looking for the above query. Thanks!

**Comment by ashikns** [comment]
Not actively seeking for this no. I ended up going with a onnx ported model and WinML.

**Comment by sgowroji** [comment]
Thank you for the update.We are closing this issue now.
