### ISSUE TITLE
build hello_world success, but build aar failed 

### ISSUE THREAD

**Issue by fanfuhuang** [google/mediapipe#1287]
ERROR: C:/users/ubtech/_bazel_frank/ibh5rbfd/external/org_tensorflow/tensorflow/lite/kernels/internal/BUILD:723:11: C++ compilation of rule '@org_tensorflow//tensorflow/lite/kernels/internal:audio_utils' failed (Exit 1): clang failed: error executing command
  cd C:/users/ubtech/_bazel_frank/ibh5rbfd/execroot/mediapipe
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Kingdee\K3ERP\KDSYSTEM;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\Java\jdk1.8.0_202\bin;C:\Program Files\TortoiseSVN\bin;C:\Users\ubtech\AppData\Local\Android\Sdk\tools;C:\Users\ubtech\AppData\Local\Android\Sdk\tools\bin\;C:\Program Files\nodejs\;C:\bazel\;C:\msys64\usr\bin;E:\software\platform-tools_r26.0.1-windows\platform-tools;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\ubtech\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\ubtech\AppData\Local\Programs\Python\Python39\;C:\Users\ubtech\AppData\Local\Microsoft\WindowsApps;c:\program files\esafenet\cobra docguard client;E:\workspace\flutter\bin;C:\Users\ubtech\AppData\Roaming\npm;C:\bazel\;
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C://Users//ubtech//AppData//Local//Programs//Python//Python39//python.exe
    SET RUNFILES_MANIFEST_ONLY=1
  external/androidndk/ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/clang -D__ANDROID_API__=29 -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fpic -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -funwind-tables -fstack-protector-strong -fno-addrsig -Werror=return-type -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=implicit-function-declaration -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/android-armeabi-v7a-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/audio_utils/spectrogram.pic.d -frandom-seed=bazel-out/android-armeabi-v7a-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/audio_utils/spectrogram.pic.o -fPIC -iquote external/org_tensorflow -iquote bazel-out/android-armeabi-v7a-opt/bin/external/org_tensorflow -iquote external/fft2d -iquote bazel-out/android-armeabi-v7a-opt/bin/external/fft2d /w /D_USE_MATH_DEFINES /std:c++14 -DFARMHASH_NO_CXX_STRING -mfpu=neon -O3 -ffunction-sections -fdata-sections -fno-exceptions --sysroot=external/androidndk/ndk/platforms/android-29/arch-arm -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c external/org_tensorflow/tensorflow/lite/kernels/internal/spectrogram.cc -o bazel-out/android-armeabi-v7a-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/audio_utils/spectrogram.pic.o
Execution platform: @local_execution_config_platform//:platform
clang: error: no such file or directory: '/w'
clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
clang: error: no such file or directory: '/std:c++14'
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar failed to build
INFO: Elapsed time: 77.962s, Critical Path: 48.05s
INFO: 237 processes: 125 internal, 108 local, 4 worker.
FAILED: Build did NOT complete successfully

**Comment by jiuqiant** [comment]
In https://google.github.io/mediapipe/getting_started/install#installing-on-windows, we mention that "Note: building MediaPipe Android apps is still not possible on native Windows. Please do this in WSL instead and see the WSL setup instruction in the next section.".

You need to use WSL to build AARs. See how to setup WSL for MediaPipe at https://google.github.io/mediapipe/getting_started/install#installing-on-windows-subsystem-for-linux-wsl.
