### ISSUE TITLE
About packet's timestamp issues

### ISSUE THREAD

**Issue by toandrew** [google/mediapipe#129]
It seems that the Timestamp of a packet is only the sequence number of the packet. Is it possible to get the packet's REAL times(for example, CMTime in ios) for different scenes?

**Comment by eknight7** [comment]
Yes.

MPPGraph.h has an API method:
```
- (BOOL)sendPixelBuffer:(CVPixelBufferRef)pixelBuffer
             intoStream:(const std::string&)inputName
             packetType:(MPPPacketType)packetType
              timestamp:(const mediapipe::Timestamp&)timestamp;
```

You can use this to send packets at a specific timestamp.
For example, presently in the app for [edgedetectiongpu](https://github.com/google/mediapipe/blob/master/mediapipe/examples/ios/edgedetectiongpu/ViewController.mm), we have
```
- (void)processVideoFrame:(CVPixelBufferRef)imageBuffer
                timestamp:(CMTime)timestamp
               fromSource:(MPPInputSource*)source {
  if (source != _cameraSource) {
    NSLog(@"Unknown source: %@", source);
    return;
  }
  [self.mediapipeGraph sendPixelBuffer:imageBuffer
                            intoStream:kInputStream
                            packetType:MPPPacketTypePixelBuffer];
}
```
there, we can use the specific timestamp, i.e. `(CMTime)timestamp` that is provided as an input to the method, and replace the `sendPixelBuffer` call with:
```
[self.mediapipeGraph sendPixelBuffer:imageBuffer
                            intoStream:kInputStream
                            packetType:MPPPacketTypePixelBuffer
                            timestamp:timestamp];
```

**Comment by toandrew** [comment]
Thanks for your quick reply. 
But it does not work properly. 

error messages:

``
"Domain=GoogleUtilStatusErrorDomain Code=3 "Graph has errors: 
; Packet timestamp mismatch on a calculator receiving from stream "input_video". Current minimum expected timestamp is 318266015745 but received 318266015744. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment."
``

**Comment by eknight7** [comment]
Can you share the code you are using? Which calculator is this and what does the graph look like?
Also, can you share the .mm file you are using?

**Comment by toandrew** [comment]
@eknight7
 it works. 

Sorry for the wrong info.

**Comment by eknight7** [comment]
No problem, glad to hear it works for you!

**Comment by BroderickHigby** [comment]
Hey @eknight7, is it possible to get the real timestamp number for AutoFlip as well. I'd like to know when scenes change in realValue seconds.
