### ISSUE TITLE
Is there any way to run MediaPipe in my own web app today?

### ISSUE THREAD

**Issue by senshin998** [google/mediapipe#1291]
Many people really looking forward to this,

**Comment by mgyong** [comment]
@senshin998 We are looking for folks interested in using Full body pose on the web for use cases like online fitness. We are releasing MediaPipe JS solutions API shortly and like to get folks to try it out.

**Comment by marcato15** [comment]
I have interest in using MediaPipe on the web for some video applications we have. Not sure it's the exact use case you are looking for or not.

**Comment by shadowboxingskills** [comment]
> @senshin998 We are looking for folks interested in using Full body pose on the web for use cases like online fitness. We are releasing MediaPipe JS solutions API shortly and like to get folks to try it out.

Wrote an AI-based real-time yoga improvement web app. Embedded the TensorFlow.js API but current PoseNet full-body model implementation has significant limitations for fitness. I will definitely switch to the latest MediaPipe JS model as soon as you release it.

**Comment by jrouet** [comment]
I'm waiting the release too...

**Comment by Nikkhil16** [comment]
Are there any updates on this? :)

Are there any plans to include this with the PaaS offerings on the GCP?

**Comment by sgowroji** [comment]
Thank you all for sharing the interest in MediaPipe. Please go through the [Js platform  ](https://google.github.io/mediapipe/getting_started/javascript) of different solutions.  We are closing this issue as of now, Please reach us back if you have any relevant update on the above context.
