### ISSUE TITLE
Feature Request:  Full demo application that can be used for 3D character animation.

### ISSUE THREAD

**Issue by delebash** [google/mediapipe#1293]
By combining your existing 3D body  motion capture applications into one application that can stream real-time data for use in a 3D character animation program such as Maya or Blender.  I think this would be a wonderful showcase application of what mediapipe can do.

**Comment by sgowroji** [comment]
Hi @delebash, Thank you sharing your interest on MediaPipe.  Could you please elaborate your use case with more details and who will benefit with this future. Are you willing to contribute it. Thanks!

**Comment by delebash** [comment]
Sure, anyone wanting to do 3D motion capture in say Unreal for video games or movies would find it extremely useful.  Not just Unreal but any 3D animation software, Maya, Blender, iClone.  Here is a test I did with iClone but because of mediapipe still having jitter problems it is just not feasible yet.  https://www.youtube.com/watch?v=j6JboJIlpfM.  There are commercial companies doing this now and it would be nice to have an open source solution for those of us who cannot afford it.  See https://getrad.co/ or https://www.deepmotion.com/.  Nvidia is using Wrnch AI for their motion capture application that is part of a 3D suite of apps https://developer.nvidia.com/blog/nvidia-omniverse-machinima-now-available-in-open-beta/.  Unreal has a free iPhone app for facial motion capture but you must have a depth sensing camera Iphone 11> and only face is tracked.  Being able to do full body motion capture from a web camera would help solo developers and small companies who cannot afford the expensive motion capture body suits and other equipment be able to compete in creating AAA games and CGI Movies.  As far as contributing I am not a really good coder but I can test the product and give feedback that is certainly not a problem.

**Comment by francoisbonnard** [comment]
Hi @sgowroji . Following the idea of Daniel @delebash I would like to help if needed for Maya. My concern is more about facial meshing and how to import data inside Maya so we can adjust 3D models on an image sequence (or real time)

**Comment by sgowroji** [comment]
Hi @francoisbonnard, This https://github.com/google/mediapipe/issues/1155#issuecomment-721889436 will  guide you better on your use case. Thanks!
