### ISSUE TITLE
Convert Existing 2D TF Object Detection API Model into 2-stage Objectron Graph

### ISSUE THREAD

**Issue by kells1986** [google/mediapipe#1295]
I have an object detection model trained on custom classes using the tensorflow object detection api.

Is there any way to convert that model into the 2-stage objectron format? or is further training needed specifically for the 3d fitting?

It seems to me that those two things are distinct processes, and I wondered if there was a tool that could create a 2-stage TFLite file using a custom TFLite / frozen inference graph 2d object detection model?

**Comment by matteo-filippini** [comment]
I'm also interested in some documentation about that. I guess this is not so straightforward. Browsing the objectron example folders you can find some obj.uuu files and textures. These are 3d models of sneakers/cups/cameras etc, maybe they are used to fit the 2d image to 3d model and infer the volume of the object?
would be great get some advices from developers!

**Comment by sgowroji** [comment]
Hi @kells1986, Could you please go through our latest [documentation](https://google.github.io/mediapipe/solutions/object_detection) regarding your above query and let us know, if you  have a different use case.
