### ISSUE TITLE
Hello_world example build file not found

### ISSUE THREAD

**Issue by mariamshah** [google/mediapipe#1297]
The build file already exists yet i get the following errors when i run: bazel run --define MEDIAPIPE_DISABLE_GPU=1 \ mediapipe/examples/desktop/hello_world:hello_world
ERRORS:

DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3e6b0691fc57db8217d535393dcc2cf7c1d39fc87e9adb6e7d7bab1483915110"
DEBUG: Repository rules_foreign_cc instantiated at:
  /home/mariam/mediapipe/WORKSPACE:39:13: in <toplevel>
Repository rule http_archive defined at:
  /home/mariam/.cache/bazel/_bazel_mariam/f12c27a7cc48470739f2ada61411ed0a/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: Skipping ' mediapipe/examples/desktop/hello_world:hello_world': no such package ' mediapipe/examples/desktop/hello_world': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/mariam/mediapipe/ mediapipe/examples/desktop/hello_world
WARNING: Target pattern parsing failed.
ERROR: no such package ' mediapipe/examples/desktop/hello_world': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/mariam/mediapipe/ mediapipe/examples/desktop/hello_world
INFO: Elapsed time: 0.200s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by mariamshah** [comment]
@jiuqiant please help
i have bazel 3.7 installed, working on linux mint 18.3

**Comment by MaRauder111** [comment]
Can you try running with this command :
```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
```
as he mention in #1288

**Comment by MaRauder111** [comment]
Have you run this command :
```
export GLOG_logtostderr=1
``` 
before running :
```
run --define MEDIAPIPE_DISABLE_GPU=1 \ mediapipe/examples/desktop/hello_world:hello_world
```
Running the hello world example. [Hello_world_example](https://google.github.io/mediapipe/getting_started/hello_world_desktop.html)

**Comment by jiuqiant** [comment]
My observation is there is an extra space between "/home/mariam/mediapipe/" and "mediapipe/examples/desktop/hello_world" in your error message: 
```
extra space -----------
                       |
                       v
/home/mariam/mediapipe/ mediapipe/examples/desktop/hello_world
WARNING: Target pattern parsing failed.
ERROR: no such package ' mediapipe/examples/desktop/hello_world': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
```

It might be a Bazel bug on linux mint when it parses your build command. You may try the following to get rid of the extra space (I am not sure this approach works):

```
export GLOG_logtostderr=1 && bazel run --define MEDIAPIPE_DISABLE_GPU=1 //mediapipe/examples/desktop/hello_world:hello_world
```

**Comment by mariamshah** [comment]
> My observation is there is an extra space between "/home/mariam/mediapipe/" and "mediapipe/examples/desktop/hello_world" in your error message:
> 
> ```
> extra space -----------
>                        |
>                        v
> /home/mariam/mediapipe/ mediapipe/examples/desktop/hello_world
> WARNING: Target pattern parsing failed.
> ERROR: no such package ' mediapipe/examples/desktop/hello_world': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
> ```
> 
> It might be a Bazel bug on linux mint when it parses your build command. You may try the following to get rid of the extra space (I am not sure this approach works):
> 
> ```
> export GLOG_logtostderr=1 && bazel run --define MEDIAPIPE_DISABLE_GPU=1 //mediapipe/examples/desktop/hello_world:hello_world
> ```

Thank you! I somehow fixed the issue after the following:
`sudo apt update
sudo apt install build-essential
sudo apt-get install manages-dev`
