### ISSUE TITLE
tensorflow issue while installing using Docker

### ISSUE THREAD

**Issue by cg3dland** [google/mediapipe#1298]
When run "docker build --tag=mediapipe ." which according to the MediaPipe installation, an error happens as below:

ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1)
ERROR: No matching distribution found for tensorflow==1.14.0

It seems the tensorflow v1.14.0 is depreciated, and could not find an tensorflow v1.14.0 installaztion package, so, the installing using Docker aborts.

How to resolve this issue? Is the tensorflow necessary for mediapipe? Could the latest tensorflow (e.g., v2.3.0) be used for installing MediaPipe using Docker?

Thanks,

**Comment by jiuqiant** [comment]
You can remove tensorflow python package from the mp Dockerfile file if you don't care about the yt8m example.
Actually, according to https://pypi.org/project/tensorflow/1.14.0/, tensorflow 1.14.0 should still be available.

**Comment by jiuqiant** [comment]
MediaPipe itself uses TensorFlow C++ and should not be affected by its python API changes. YT8M and MediaSequence example may not be TF 2.x compatible. If those examples work, we can do the switch.

**Comment by cg3dland** [comment]
Thanks, this issue is resolved: the tensorflow python package is removed from the mp Dockerfile file

**Comment by Samuel-wei** [comment]
I have the same problem showed it below while I run the "docker build --tag=mediapipe ." command:
...
.
.
.
Could not find a version that satisfies the requirement tensorflow==1.14.0 (from versions: )
  No matching distribution found for tensorflow==1.14.0
  The command '/bin/sh -c pip3 install tensorflow==1.14.0' returned a non-zero code: 1
...
my solve method:
Usage the Nvidia NGC tensorflow image of nvcr.io/nvidia/l4t-tensorflow:r32.4.4-tf1.15-py3 as the Dockerfile basis Imags.

the  walkthrough:
FROM nvcr.io/nvidia/l4t-tensorflow:r32.4.4-tf1.15-py3

MAINTAINER <mediapipe@google.com>

WORKDIR /io
WORKDIR /mediapipe

ENV DEBIAN_FRONTEND=noninteractive
...
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        ffmpeg \
        git \
        wget \
        unzip \
        python3-dev \
        python3-opencv \
        python3-pip \
        libopencv-core-dev \
        libopencv-highgui-dev \
        libopencv-imgproc-dev \
        libopencv-video-dev \
        libopencv-calib3d-dev \
        libopencv-features2d-dev \
        software-properties-common && \
    add-apt-repository -y ppa:openjdk-r/ppa && \
    apt-get update && apt-get install -y openjdk-8-jdk && \
    apt-get clean && \
    apt-get install -y build-essential zip unzip && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade setuptools
RUN pip3 install wheel
RUN pip3 install future
RUN pip3 install six==1.14.0
#RUN pip install tensorflow==1.14.0
RUN pip3 install tf_slim

#RUN ln -s /usr/bin/python3 /usr/bin/python

# Install bazel
COPY bazel-3.4.1-dist.zip bazel-3.4.1-dist.zip
ARG BAZEL_VERSION=3.4.1
RUN mkdir /bazel && \
    mv bazel-3.4.1-dist.zip /bazel && \
    cd /bazel && \
    unzip bazel-3.4.1-dist.zip && \
    env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh && \
    cp output/bazel /usr/local/bin/ && \
    rm -f /bazel/bazel-3.4.1-dist.zip


COPY . /mediapipe/
...

**Comment by Samuel-wei** [comment]
I have the same problem showed it below while I run the "docker build --tag=mediapipe ." command:
...
.
.
.
Could not find a version that satisfies the requirement tensorflow==1.14.0 (from versions: )
No matching distribution found for tensorflow==1.14.0
The command '/bin/sh -c pip3 install tensorflow==1.14.0' returned a non-zero code: 1
...
my solve method:
Usage the Nvidia NGC tensorflow image of nvcr.io/nvidia/l4t-tensorflow:r32.4.4-tf1.15-py3 as the Dockerfile basis Imags.

the walkthrough:
FROM nvcr.io/nvidia/l4t-tensorflow:r32.4.4-tf1.15-py3

MAINTAINER mediapipe@google.com

WORKDIR /io
WORKDIR /mediapipe

ENV DEBIAN_FRONTEND=noninteractive
...
RUN apt-get update && apt-get install -y --no-install-recommends
build-essential
ca-certificates
curl
ffmpeg
git
wget
unzip
python3-dev
python3-opencv
python3-pip
libopencv-core-dev
libopencv-highgui-dev
libopencv-imgproc-dev
libopencv-video-dev
libopencv-calib3d-dev
libopencv-features2d-dev
software-properties-common &&
add-apt-repository -y ppa:openjdk-r/ppa &&
apt-get update && apt-get install -y openjdk-8-jdk &&
apt-get clean &&
apt-get install -y build-essential zip unzip &&
rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade setuptools
RUN pip3 install wheel
RUN pip3 install future
RUN pip3 install six==1.14.0
#RUN pip install tensorflow==1.14.0
RUN pip3 install tf_slim

#RUN ln -s /usr/bin/python3 /usr/bin/python

#Install bazel
COPY bazel-3.4.1-dist.zip bazel-3.4.1-dist.zip
ARG BAZEL_VERSION=3.4.1
RUN mkdir /bazel &&
mv bazel-3.4.1-dist.zip /bazel &&
cd /bazel &&
unzip bazel-3.4.1-dist.zip &&
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh &&
cp output/bazel /usr/local/bin/ &&
rm -f /bazel/bazel-3.4.1-dist.zip

COPY . /mediapipe/
...
