### ISSUE TITLE
[YouTube8M] How to extract the pb file by python

### ISSUE THREAD

**Issue by gaoruiyang** [google/mediapipe#1299]
Since I ran code in https://github.com/tensorflow/models/tree/master/research/audioset/vggish and got a different result from this code, I want to check the following pb file to see if the params are the same.

curl -O http://data.yt8m.org/pca_matrix_data/inception3_mean_matrix_data.pb
curl -O http://data.yt8m.org/pca_matrix_data/inception3_projection_matrix_data.pb
curl -O http://data.yt8m.org/pca_matrix_data/vggish_mean_matrix_data.pb
curl -O http://data.yt8m.org/pca_matrix_data/vggish_projection_matrix_data.pb

The decoding code is written by C++, so I wonder if there are some ways to extract thest pb file by python simply.
Could you plz release a example py file to do this?
C++ is too hard to read for me :(

**Comment by gaoruiyang** [comment]
Can anyone answer this question plz?

**Comment by sgowroji** [comment]
Hi @gaoruiyang, Could you please respond whether you are still looking for the above query. And share us more your observation with the MediaPipe Youtube8M solution.
