### ISSUE TITLE
dataset for face segmentation

### ISSUE THREAD

**Issue by capilano** [google/mediapipe#13]
Is it possible to make the face segmentation dataset public? I would like to contribute to the project,but I do not have access to quality annotations for this task

**Comment by mgyong** [comment]
@capilano There are no plans to release the face segmentation dataset public due to user privacy issues.

**Comment by capilano** [comment]
@mgyong Would it be possible to share it privately? Thanks

**Comment by jiuqiant** [comment]
@capilano I believe we are not allowed to share any PII dataset in any way due to privacy concerns. Sorry about that.

**Comment by capilano** [comment]
@jiuqiant I see. So this dataset cannot be licensed through GCP/GCS either?
