### ISSUE TITLE
stdout: stderr: xcodebuild: error: SDK "macosx10.10" cannot be located.

### ISSUE THREAD

**Issue by soham24** [google/mediapipe#130]
'@com_google_protobuf_javalite//:protobuf_lite' failed: I/O exception during sandboxed execution: xcrun failed with code 1.
This most likely indicates that SDK version [10.10] for platform [MacOSX] is unsupported for the target version of xcode.
Process exited with status 1
stdout: stderr: xcodebuild: error: SDK "macosx10.10" cannot be located.

**Comment by Momohanfeng** [comment]
I think you can try the command with sdk version:
` bazel build -c opt --macos_sdk_version=10.14 --config=...your_path/edgedetectiongpu`

**Comment by jiuqiant** [comment]
Let us know if the problem is solved. Thanks!

**Comment by soham24** [comment]
@jiuqiant @Momohanfeng  solved. Thanks

**Comment by soham24** [comment]
I just want pipeline that will get texture from textureview to tflite model, and pass output buffer back to textureview.. everything on GPU. I see that is there , but deep inside level of abstractions.
