### ISSUE TITLE
Building Android HelloWorld error

### ISSUE THREAD

**Issue by Andrec-Dxs** [google/mediapipe#1301]
Following the tutorial for the generation of the project on Android I'm having this error:

ERROR:  /Users/andre/Downloads/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/BUILD:18:16: in resource_files attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:basic_lib: 'mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/res/.DS_Store' is not in the expected resource directory structure of <resource directory>/{anim,animator,color,drawable,font,interpolator,layout,menu,mipmap,navigation,raw,transition,values,xml}/<file>

ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld' failed; build aborted: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:basic_lib' failed

**Comment by Andrec-Dxs** [comment]
If anyone gets this issue, access BUILD file on helloworld project and replace resource_files line for 
"resource_files = glob(["res/**"], exclude=["res/.DS_Store"]),". Project now builds

**Comment by rayala3892** [comment]
Thank you very much, it was very useful with the same problem :)
