### ISSUE TITLE
Examples don't work with PowerVR

### ISSUE THREAD

**Issue by YuHayakawa** [google/mediapipe#1303]
Dear mediapipe team,
I tried to run iristrackinggpu and facedetectiongpu on Lenovo M10 FHD Plus under the following conditions.
But i get black screen.

Mediapipe:
- Version: 0.8

Lenovo M10 FHD Plus:
- GPU: IMG PowerVR GE8320 650MHz
  - API Support: 
    - OpenGL ES 3.2
    - Vulkan 1.1
    - OpenCL 1.2
    - Android NN HAL

Thank you and Best regards,

**Comment by YuHayakawa** [comment]
I try some step, and find running pattern.

1. Install iristrackinggpu
2. Start app
3. Black screen never
4. Sleep Tablet
5. Start up tablet
6. App run as expected

**Comment by sgowroji** [comment]
Hi @YuHayakawa, Could you please try the above with the latest release. And if you still see the same black screen,  please share us the video with complete reproduction steps and error logs to investigate further. Thanks!
