### ISSUE TITLE
Black screen on Samsung Galaxy Tab Active 2 [Android AAR]

### ISSUE THREAD

**Issue by MarcinKornacki** [google/mediapipe#1304]
Hi!
While running the [example for gpu hand tracking](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java) using AAR I encounter a problem in which the preview view stays black.
On Samsung Galaxy Tab Active 2(really slow device) the problem occurs most of the time(9/10 attempts)
On Xiaomi Mi A2(much faster device) the problem occurs rarely(1/10 attempts)
But when I run the same code integrated with my other app which runs under some load the problem occurs even more frequently than on the Samsung tablet.

The only thing that I found meaningful to me in the logs is that loading .tflite models are not being invoked when the problem occurs.

[Samsung logs when screen is black](https://github.com/google/mediapipe/files/5555001/samsung_mediapipe_black_screen.txt)
[Samsung logs when everything works fine](https://github.com/google/mediapipe/files/5555004/samsung_mediapipe_working_fine.txt)

**Comment by gittitov** [comment]
i have the same problems with RK3399 & Android 9.0.
Nothing changes if I run even with a simple graph:

input_stream: "input_video"
output_stream: "output_video"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
 }
 output_stream: "output_video"
}

**Comment by DandyLorenz** [comment]
On low-end performance mobile phones, there will be a greater probability of starting a black screen phenomenon，How to solve it

**Comment by sgowroji** [comment]
Hi @MarcinKornacki, Could you please test the above with the latest release and let us know if you still see the same observation. And share the video to understand the issue. Thanks!
