### ISSUE TITLE
How to build the MediaPipe into C/C++ JNI interfaces for Android?

### ISSUE THREAD

**Issue by SunAriesCN** [google/mediapipe#1307]
Hi，mediapipe team 
I’m so glad to hear that MediaPipe has released more new AR features and solutions, and we want to integrate lots of them from MediaPipe into our robot product for more funny experience. However, I do not know how to build the JNI interfaces with the C++ API, because our framework is in C/C++ language to support various platforms e.g. Android, IOS and so on. Also, I have run some your solutions on our framework by my manual codings to imitate them, but it’s may not enough efficiency as well as MediaPipe running on Android, and there are lots of works for me to transplant this great project into our product. So, is there any docs or tutorials help me build your solutions into the C++ JNI interfaces and I could call them in C++ on Android, or other better ways for me to go?

**Comment by SunAriesCN** [comment]
( T.T )||| Hi, is there anyone would like to give me some help?

**Comment by sgowroji** [comment]
Hi @SunAriesCN, You can create any [Android AAR using any solution ](https://google.github.io/mediapipe/getting_started/android_archive_library.html#mediapipe-android-archive)which you can add in your Android project and build. Could you please elaborate if you are looking for any other use case in the above. Thanks!

**Comment by SunAriesCN** [comment]
@sgowroji Thanks for your reply. Your AAR may be not well enough for our problem, because most of our code are in C/C++ language, and we should support iOS and others not Android platform. So, an Android package solution is still not enough for us, an I'm still looking for an compilation methods/solutions that can build a static library for iOS and a dynamics library for Android. If you have other better solution, please let me know that, thanks!

**Comment by SunAriesCN** [comment]
> @sgowroji Thanks for your reply. Your AAR may be not well enough for our problem, because most of our code are in C/C++ language, and we should support iOS and others not Android platform. So, an Android package solution is still not enough for us, an I'm still looking for an compilation methods/solutions that can build a static library for iOS and a dynamics library for Android. If you have other better solution, please let me know that, thanks!

I think it should be a C/C++ library cross-compile problem for platforms.
