### ISSUE TITLE
Mediapipe (handtrackinggpu) + Android_x86 not working

### ISSUE THREAD

**Issue by elkercavina** [google/mediapipe#1309]
Compiled android handtrackinggpu example with Android_x86 target (.bazelrc target from Tensorflow) with api_level=22 (lollipop). 

Application starts correctly but does not detect hands and does not add any annotation in the preview frame (only the camera image displayed).

Handtrackinggpu  example works correctly with Android_arm64
Basic/Helloworld example works correctly on Android_x86 + lollipop
FaceDetectionCpu seems to work partially on Android_x86 + lollipop: something is detected but with very low accuracy compared to Android_arm64 where it works perfectly.

Target device for x86: Moverio BT300; android 5.1 lollipop. 
Opengl ES v3.2

Is there any trick to make it work?

**Comment by sgowroji** [comment]
Hi @elkercavina, Could you please verify the above with the latest MediaPipe release. If you encounter similar observation, please share us the complete details.  Thanks!
