### ISSUE TITLE
How to generate a Reshape TFLite model with the new shape as attributes?

### ISSUE THREAD

**Issue by jackwish** [google/mediapipe#1310]
Greetings! May I know the details of how the TFLite models are generated, in particular, the code path to produce the TFLite models? **Should be irrelevant to the model detail**.

We are working on [`tflite2onnx`](https://github.com/jackwish/tflite2onnx) which can convert TFLite models to ONNX. When converting the [palm_detection](https://github.com/google/mediapipe/blob/master/mediapipe/modules/palm_detection/palm_detection.tflite) model, we noticed that the `Reshape` of it accepts **only one input** - the output shape is as the attribute of `Reshape` as the figure below.

<img width="528" alt="palm-detect" src="https://user-images.githubusercontent.com/4936589/99535493-ee76a500-29e3-11eb-829f-30239911b9fd.png">

We tried to build a standalone case for `Reshape` (a model which contains `Reshape` only), but there are **always two inputs** in our model with either Keras API or TensorFlow API. We are curious about how to generate a Reshape TFLite model with the new shape as attributes?

```py
import tensorflow as tf  # tf 2.3.0
import numpy as np

ISHAPE = (1, 2, 3, 4)
OSHAPE = (int(np.product(ISHAPE)),)


def genWithKeras():
  data = tf.keras.Input(dtype='float32', name='input', batch_size=ISHAPE[0], shape=ISHAPE[1:])
  reshape = tf.keras.layers.Reshape(OSHAPE, name='reshaped')(data)
  model = tf.keras.Model(inputs=[data], outputs=[reshape])
  return tf.lite.TFLiteConverter.from_keras_model(model)


def genWithTFModel():
  class ReshapeModule(tf.Module):
    def __init__(self):
      super(ReshapeModule, self).__init__()

    @tf.function(input_signature=[tf.TensorSpec(ISHAPE, tf.float32)])
    def __call__(self, data):
      return tf.reshape(data, OSHAPE)

  module = ReshapeModule()
  tf.saved_model.save(module, 'reshape.saved_model')
  return tf.lite.TFLiteConverter.from_saved_model('reshape.saved_model')

converter = genWithKeras()
# converter = genWithTFModel()
tflite_model = converter.convert()
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)
```

<img width="519" alt="reshape" src="https://user-images.githubusercontent.com/4936589/99535868-78bf0900-29e4-11eb-86e9-8482d57e5a4b.png">

The source issue we have is: https://github.com/jackwish/tflite2onnx/issues/23#issuecomment-725070754

**Comment by jackwish** [comment]
@erizmr Please comment some if your generating script is different from mine :)
And cc @Laubeee FYI.

**Comment by SunAriesCN** [comment]
Well, it seem that you can try the `interpreter.resize_tensor_input` interface before `allocate_tensor()` and `invoke()`...

**Comment by jackwish** [comment]
> Well, it seem that you can try the `interpreter.resize_tensor_input` interface before `allocate_tensor()` and `invoke()`...

@SunAriesCN Thanks for your reply! It seems to me that the interfaces you refer to are TFLite interpreter interfaces, and the issue we have is TFLite converter which happens before invokes the interpreter. Do I get anything wrong?

**Comment by SunAriesCN** [comment]
> > Well, it seem that you can try the `interpreter.resize_tensor_input` interface before `allocate_tensor()` and `invoke()`...
> 
> @SunAriesCN Thanks for your reply! It seems to me that the interfaces you refer to are TFLite interpreter interfaces, and the issue we have is TFLite converter which happens before invokes the interpreter. Do I get anything wrong?

@jackwish Well, you are right, the `resize_tensor_input` does happen after model conversion. However, as far as I know, it seem that the design to input a multi-batches tensor in TFLite only support on inference stage now. And I heard that there are some tricks in MLIR may reach what you want, but I'm sorry that I am not familiar with that. BTW, I think this issue can redirect to [TFLite](https://github.com/tensorflow/tensorflow) origin repo, although I feel it was an old problem for a long time, which is difficult to handle. So, I have a workaround for you that do something on ONNX runtime before inference. Best wish...hhhhahhaa~

**Comment by jackwish** [comment]
@SunAriesCN Thanks for your suggestion, move to TFLite repo sounds fair. We are good with inferencing on ONNXRuntime or TFLite, just want to have a tiny model to test our tool `tflite2onnx`. Maybe it's too tricky to hack into the MLIR stack for us...

**Comment by jackwish** [comment]
Close the issue here as moved to https://github.com/tensorflow/tensorflow/issues/45150
