### ISSUE TITLE
Is there a plan to make the python package binary available for Raspberry Pi and other arm devices?

### ISSUE THREAD

**Issue by ivelin** [google/mediapipe#1312]
MediaPipe team,

First of all, thank you for creating and maintaining this awesome project.

To the issue at hand:

Currently the [pypi mediapipe package](https://pypi.org/project/mediapipe/) is not available for arm devices. Is there a plan to publish an arm version?

According to the docs, running media pipe on arm linux [requires](https://google.github.io/mediapipe/getting_started/install.html) building Bazel from source in order to then build mediapipe. That's quite an adventure for ML app developers.

**Comment by jiuqiant** [comment]
MediaPipe currently has no plan to officially release aarch64 wheels.
Personally, I managed to build and run MediaPipe Python on Ubuntu for Raspberry Pi. See the details at https://github.com/jiuqiant/mediapipe-python-aarch64.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
