### ISSUE TITLE
error C7555: ... requires at least '/std:c++latest' when build in Win10.

### ISSUE THREAD

**Issue by LeoYinTw** [google/mediapipe#1313]
I followed the desktop installation instructions and succeed to run project 'hello world', but keeping failing in build any other project (face_mesh, pose, hands, etc). Below is the error message I got.
**error C7555: use of designated initializers requires at least '/std:c++latest'**

Tried add '--cxxopt="/std:c++latest' or '--cxxopt="/std:c++14' after bazel build command.
Tried set 'BAZEL_CXXOPTS="-std=c++14"'
But no luck   :(

Below is my build command.
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --verbose_failures --cxxopt="/std:c++latest --action_env PYTHON_BIN_PATH="C://Python37//python.exe" mediapipe/examples/desktop/face_mesh:face_mesh_cpu
`

Is anyone have any clue how to solve this?
Many thanks!

**Comment by jiuqiant** [comment]
Hi, we already fixed this issue internally and haven't released it to GitHub. The root issue is the way the RotatedRect struct is initialized in mediapipe/calculators/tensor/image_to_tensor_utils.cc.

For a quick fix, you can modify https://github.com/google/mediapipe/blob/master/.bazelrc#L17 and
https://github.com/google/mediapipe/blob/master/.bazelrc#L18
to be
```
build:windows --cxxopt=/std:c++latest
build:windows --host_cxxopt=/std:c++latest
```
and then rerun the bazel command.

Note that this is a temporary workaround and we will have the right fix in the coming release.

**Comment by JunyuanYang** [comment]
Hi, @jiuqiant 

I have met the error C7555: use of designated initializers requires at least '/std:c++latest' as well. However, things would not be better since another error related with C++ compliation occurs after I modifed the ``build:windows --cxxopt=/std:c++latest`` and ``build:windows --host_cxxopt=/std:c++latest`` in .bazelrc file.

The error stated that
**ERROR:C:/users/wwwsi/_bazel_wwwsi/3qnoacdc/external/com_google_absl/absl/flags/BUILD.bazel:177:11: C++ compilation of rule '@com_google_absl//absl/flags:flag' failed (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 42 argument(s) skipped)**

Another thing frustrated is that when https://github.com/google/mediapipe/blob/master/.bazelrc#L17 remains to be 
``build:macos --cxxopt=-std=c++14`` the error above would disappear and I could complete building my HelloWorld demo. But when it comes to iris_tracking, alas, error C7555 occurs one more time.

Thank you for your patience.

**Comment by LeoYinTw** [comment]
> 
> 
> Hi, we already fixed this issue internally and haven't released it to GitHub. The root issue is the way the RotatedRect struct is initialized in mediapipe/calculators/tensor/image_to_tensor_utils.cc.
> 
> For a quick fix, you can modify https://github.com/google/mediapipe/blob/master/.bazelrc#L17 and
> https://github.com/google/mediapipe/blob/master/.bazelrc#L18
> to be
> 
> ```
> build:windows --cxxopt=/std:c++latest
> build:windows --host_cxxopt=/std:c++latest
> ```
> 
> and then rerun the bazel command.
> 
> Note that this is a temporary workaround and we will have the right fix in the coming release.

Thank you, this fix the "at least '/std:c++latest'" error.

But an new error pop-up.
external/com_google_absl\absl/meta/type_traits.h(620): error C2039: 'result_of': is not a member of 'std'

any clue or workaround can help.
Thanks for reply.   :D

**Comment by jiuqiant** [comment]
Please try the following changes:

```
--- a/.bazelrc
+++ b/.bazelrc
@@ -14,8 +14,8 @@ build:linux --host_cxxopt=-std=c++14
 build:linux --copt=-w

 # windows
-build:windows --cxxopt=/std:c++14
-build:windows --host_cxxopt=/std:c++14
+build:windows --cxxopt=/std:c++17
+build:windows --host_cxxopt=/std:c++17
 build:windows --copt=/w
 # For using M_* math constants on Windows with MSVC.
 build:windows --copt=/D_USE_MATH_DEFINES
diff --git a/mediapipe/calculators/tensor/image_to_tensor_utils.cc b/mediapipe/calculators/tensor/image_to_tensor_utils.cc
index c2bfc0f..dc59467 100644
--- a/mediapipe/calculators/tensor/image_to_tensor_utils.cc
+++ b/mediapipe/calculators/tensor/image_to_tensor_utils.cc
@@ -25,23 +25,23 @@ namespace mediapipe {
 RotatedRect GetRoi(int input_width, int input_height,
                    absl::optional<mediapipe::NormalizedRect> norm_rect) {
   if (norm_rect) {
-    return {.center_x = norm_rect->x_center() * input_width,
-            .center_y = norm_rect->y_center() * input_height,
-            .width = norm_rect->width() * input_width,
-            .height = norm_rect->height() * input_height,
-            .rotation = norm_rect->rotation()};
+    return {/*center_x=*/norm_rect->x_center() * input_width,
+            /*center_y =*/norm_rect->y_center() * input_height,
+            /*width =*/norm_rect->width() * input_width,
+            /*height =*/norm_rect->height() * input_height,
+            /*rotation =*/norm_rect->rotation()};
+            /*rotation =*/norm_rect->rotation()};
   }
-  return {.center_x = 0.5f * input_width,
-          .center_y = 0.5f * input_height,
-          .width = static_cast<float>(input_width),
-          .height = static_cast<float>(input_height),
-          .rotation = 0};
+  return {/*center_x=*/0.5f * input_width,
+          /*center_y =*/0.5f * input_height,
+          /*width =*/static_cast<float>(input_width),
+          /*height =*/static_cast<float>(input_height),
+          /*rotation =*/0};
 }
```

**Comment by LeoYinTw** [comment]
> Please try the following changes:
> 
> ```
> --- a/.bazelrc
> +++ b/.bazelrc
> @@ -14,8 +14,8 @@ build:linux --host_cxxopt=-std=c++14
>  build:linux --copt=-w
> 
>  # windows
> -build:windows --cxxopt=/std:c++14
> -build:windows --host_cxxopt=/std:c++14
> +build:windows --cxxopt=/std:c++17
> +build:windows --host_cxxopt=/std:c++17
>  build:windows --copt=/w
>  # For using M_* math constants on Windows with MSVC.
>  build:windows --copt=/D_USE_MATH_DEFINES
> diff --git a/mediapipe/calculators/tensor/image_to_tensor_utils.cc b/mediapipe/calculators/tensor/image_to_tensor_utils.cc
> index c2bfc0f..dc59467 100644
> --- a/mediapipe/calculators/tensor/image_to_tensor_utils.cc
> +++ b/mediapipe/calculators/tensor/image_to_tensor_utils.cc
> @@ -25,23 +25,23 @@ namespace mediapipe {
>  RotatedRect GetRoi(int input_width, int input_height,
>                     absl::optional<mediapipe::NormalizedRect> norm_rect) {
>    if (norm_rect) {
> -    return {.center_x = norm_rect->x_center() * input_width,
> -            .center_y = norm_rect->y_center() * input_height,
> -            .width = norm_rect->width() * input_width,
> -            .height = norm_rect->height() * input_height,
> -            .rotation = norm_rect->rotation()};
> +    return {/*center_x=*/norm_rect->x_center() * input_width,
> +            /*center_y =*/norm_rect->y_center() * input_height,
> +            /*width =*/norm_rect->width() * input_width,
> +            /*height =*/norm_rect->height() * input_height,
> +            /*rotation =*/norm_rect->rotation()};
> +            /*rotation =*/norm_rect->rotation()};
>    }
> -  return {.center_x = 0.5f * input_width,
> -          .center_y = 0.5f * input_height,
> -          .width = static_cast<float>(input_width),
> -          .height = static_cast<float>(input_height),
> -          .rotation = 0};
> +  return {/*center_x=*/0.5f * input_width,
> +          /*center_y =*/0.5f * input_height,
> +          /*width =*/static_cast<float>(input_width),
> +          /*height =*/static_cast<float>(input_height),
> +          /*rotation =*/0};
>  }
> ```

this WORKS ! Thank you very much!

there is an compile error, but it's easy to fix. Just need to delete the duplicated line, see below.     :)
`+            /*rotation =*/norm_rect->rotation()};
+            /*rotation =*/norm_rect->rotation()};`

Build and run these examples successfully.
face_mesh & hands & pose & iris

**Comment by jiuqiant** [comment]
Glad to hear that! We will release this fix soon.
