### ISSUE TITLE
unreachable code

### ISSUE THREAD

**Issue by maddin200** [google/mediapipe#1314]
/mediapipe/framework/formats/location.cc: line 567

switch (location_data_.format()) {
    case LocationData::GLOBAL: {
      return Rectangle_f(0.0f, 0.0f, 1.0f, 1.0f);
      break;   // <-- unreachable
    }

**Comment by jiuqiant** [comment]
Whoops. Will remove this in the next release. Thanks for reporting this issue.

**Comment by jiuqiant** [comment]
This is solved in https://github.com/google/mediapipe/commit/2b58cceec9953f0d97059934f0de85dd60adbe9b. Closing it now.
