### ISSUE TITLE
How can i get pixel coordinates of iris and face from "iris_tracking" example?

### ISSUE THREAD

**Issue by radisc** [google/mediapipe#1317]
Hello, 

i was exerimenting with the "iris_tracking" example, i already modified the example code in demo_run_graph_main_gpu to run on a jetson nano (gstreamer pipeline).

However, i need the pixel coordinates of the landmarks for both eyes and iris, what modifications should i make and where to get the pixel coordinates of the landmarks?

Thanks in advance

**Comment by radisc** [comment]
Nevermind, i found a good starting point in #200, i'm able to read the landmark list, but now, everytime the face is not visible the cycle just halt never to resume again until the program is relaunched

**Comment by Misby** [comment]
I fix it,to run all the dataset even part of the face frame is not visible

**Comment by radisc** [comment]
How did you do that?

**Comment by Misby** [comment]
There has a function "bool OutputStreamPollerImpl::Next(Packet* packet)",in this function has a line "handler_condvar.Wait(&mutex);" . After the thread obtains the lock, the single image can not be awakened without face information.

**Comment by sgowroji** [comment]
Hi @radisc, Could you please respond if you still looking answer for the above query. 
Thanks!
