### ISSUE TITLE
The target you are compiling requires Visual C++ build tools.

### ISSUE THREAD

**Issue by zmxhhh** [google/mediapipe#1318]
Error is as follows：
The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.

Visual C++ build tools seems to be installed at D:\Microsoft Visual Studio\2019\BuildTools\VC
But Bazel can't find the following tools:
    cl.exe, link.exe, lib.exe, ml64.exe
for x64 target architecture
![image](https://user-images.githubusercontent.com/70617352/99899394-0d2ab380-2ce4-11eb-8da1-d7a7cc7ac3aa.png)

The image is C++ that I installed. But the program is still unable to recognize C++, is it my installation problem or other problems?

**Comment by mgyong** [comment]
Take a look at this issue filed in bazel repo https://github.com/bazelbuild/bazel/issues/8028

**Comment by etudemin** [comment]
I also encounter the same issue and the problem is solved by specifying the correct local VC version "BAZEL_VC_FULL_VERSION"
The VC version could be found in the folder {BAZEL_VC}/Auxiliary/Build/Microsoft.VCToolsVersion.default.txt but not in {BAZEL_VC}/Auxiliary/Build/Microsoft.VCRedistVersion.default.txt

**Comment by CepbluKot** [comment]
Go to Start Menu > Settings.

Find the setting "Edit environment variables for your account"

Look at the list on the top ("User variables for <username>"), and click the "New..." button below it.

For "Variable name", enter BAZEL_VC

Click "Browse Directory..."

Navigate to the VC directory of Visual Studio.

For example, this might be C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC on your system.

Select the VC folder and click OK

The "Variable value" field now has the path to VC. Click OK to close the window.

Done.
