### ISSUE TITLE
Hand visibility and presence (python)

### ISSUE THREAD

**Issue by guanming001** [google/mediapipe#1320]
Hi

When I tried to run the python example for mediapipe hands, the output of visibility and presence for the results.multi_hand_landmarks seem to be always zero, is this expected?

And are there any difference between visibility and presence?

Thank you!

**Comment by jiuqiant** [comment]
Please ignore the visibility and presence fields. What you see are just the default values.
For MediaPipe hands, they should be unset in the landmark proto.
