### ISSUE TITLE
Re-training model for Hand detection

### ISSUE THREAD

**Issue by RakshaRamkumar** [google/mediapipe#1322]
Hey,

I want to retrain the Palm Detector model, on custom images. Is there a way to use the existing palm_detector.tflite for this purpose?

I am stuck since there is no config file or a .pb model, using which I could have retrained.

Thanks in advance

**Comment by mgyong** [comment]
We don't release the original model so there is no way to do training on custom images. What is your use case?

**Comment by lzcchl** [comment]
@mgyong emmm, we test hand model which named "palm_detection.tflite" on android, there are some false detection.

I think mediapipe is a great frame for use AI model in android system, but it seems not easy to change to ours user own model, for a frame, it is not good for a rookie just like me. 

Even more, I think retrain is necessary! APP user don't know CNN or DL, they only pay attention to results what detection, it is dangerous if we can't improve accuracy, the APP may failed when compared with other APP which with higher accuracy.

**Comment by lzcchl** [comment]
In principle, when training a NN model, negative sample be collected in images from our datasets. for a specific scene, use images collected in the scene can improve the performance.

**Comment by sgowroji** [comment]
Hi @lzcchl, Could you please raise your request as a new issue adding this present issue as a reference to it. And add your use case with complete details in it. Thanks!

**Comment by thao-ftech** [comment]
They just said that they didn't wanna share original dataset or full/heavy model. I tried on several other datasets (like Cambridge or EgoGesture), this model really sucked!. I don't expected such as bad works from Google like this. Maybe Opensource still opensource.
