### ISSUE TITLE
Trakcing algorithm.

### ISSUE THREAD

**Issue by noneUmbrella** [google/mediapipe#1323]
Thank you for excellent work! I wonder where can I get the detailed introduction of instance tracking algorithm. I would like to study it. Which paper or website should I refer to?

**Comment by mgyong** [comment]
https://google.github.io/mediapipe/solutions/instant_motion_tracking
https://developers.googleblog.com/2020/08/instant-motion-tracking-with-mediapipe.html

**Comment by noneUmbrella** [comment]
Thanks for your reply. I think these two website are only rough introductions to the tracking framework. They are not able to guide me to reproduce the tracker. Would you like to provide more detail materials which like for example a paper that we can follow it to write my own tracker code.@mgyong

**Comment by sgowroji** [comment]
Hi @noneUmbrella, We have very clear documentation with example apps  [here](https://google.github.io/mediapipe/solutions/instant_motion_tracking).
