### ISSUE TITLE
Coordinates for different gesture in real-time hand detection

### ISSUE THREAD

**Issue by shreyanshsatvik** [google/mediapipe#1327]
Hello Mediapipe team,
 I am working on hand gesture recognition using mediapipe in a real-time video in python although I was able to extract all the co-ordinates of each frame but I am unable to identify the range required for each (x,y&z) coordinates for different gestures like numbers(1,2,3..) or when palm is closed how the co-ordinates are changing. 
Any help in how to understand and read co-ordinates for different gestures is valuable.

Thanks :)

**Comment by sgowroji** [comment]
Hi @shreyanshsatvik, Hand detection is clearly described [here](https://arxiv.org/pdf/2006.10214.pdf). Please go through it and reach us if you have any relevant request. Thanks!
