### ISSUE TITLE
Iris tracking sample in Python

### ISSUE THREAD

**Issue by JustDoIt9** [google/mediapipe#1330]
Is there any way to use Iris-tracking sample app in Python project?

**Comment by JustDoIt9** [comment]
Hey guys, 

To use mediapipe in Python project, I just created pipes between python and c++ (eg. iris_tracking sample) to transmit output of graph including raw frame, face rect, iris position, and so on.

And it works like charm. :100: 

Please refer this link to create pipes. (https://claytonrichey.com/post/c-cpp-python-pipe/)

**Comment by ksyao2002** [comment]
Thanks for your solution! Could you share the code you used to incorporate it into python?

**Comment by JustDoIt9** [comment]
https://github.com/JustDoIt9/MediaPipe-Samples-For-Python.git

I just created a new repository for sample code and  there might be unused codes.

**Comment by lukaszog** [comment]
@JustDoIt9 thanks for port, but how to build it? :)
