### ISSUE TITLE
how to get iris_tracking's iris depth?

### ISSUE THREAD

**Issue by bugmany** [google/mediapipe#1334]
iris tracking's android demo, how to get iris_tracking's iris depth(included left depth and right depth)?

**Comment by bugmany** [comment]
got it.

**Comment by fahadhaq** [comment]
@bugmany how did you manage to find the depth? Any help would be greatly appreciated.

**Comment by bugmany** [comment]
hi @fahadhaq, 
you can refer to the file:
/mediapipe/graphs/iris_tracking/calculators/iris_to_render_data_calculator.cc
IrisToRenderDataCalculator::Process(CalculatorContext* cc) {
...
}
herein, i got it.
