### ISSUE TITLE
Object detection demo during Coral Dev Board Setup

### ISSUE THREAD

**Issue by fabbro8** [google/mediapipe#1335]
I'm trying to follow the guide for running MediaPipe on Coral here: https://github.com/google/mediapipe/tree/master/mediapipe/examples/coral but when I do the "bazel build" for Object detection I have the following issues:

ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121
		patch(ctx)
	File "/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 135, in patch
		ctx.patch(patchfile, strip)
com.google.devtools.build.lib.syntax.EvalException: Error applying patch /mediapipe/third_party/org_tensorflow_compatibility_fixes.diff: Incorrect Chunk: the chunk content doesn't match the target
Original Position: 29

Original Content:
void PercentileSamplerCell::Add(double sample) {
  uint64 nstime = EnvTime::NowNanos();
  mutex_lock l(mu_);
  samples_[next_position_] = {nstime, sample};
  ++next_position_;
  if (TF_PREDICT_FALSE(next_position_ >= samples_.size())) {
    next_position_ = 0;

Revised Content:
void PercentileSamplerCell::Add(double sample) {
  uint64 nstime = EnvTime::NowNanos();
  mutex_lock l(mu_);
  samples_[next_position_].nstime = nstime;
  samples_[next_position_].value = sample;
  ++next_position_;
  if (TF_PREDICT_FALSE(next_position_ >= samples_.size())) {
    next_position_ = 0;
ERROR: no such package '@org_tensorflow//tensorflow': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121
		patch(ctx)
	File "/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 135, in patch
		ctx.patch(patchfile, strip)
com.google.devtools.build.lib.syntax.EvalException: Error applying patch /mediapipe/third_party/org_tensorflow_compatibility_fixes.diff: Incorrect Chunk: the chunk content doesn't match the target
Original Position: 29

Original Content:
void PercentileSamplerCell::Add(double sample) {
  uint64 nstime = EnvTime::NowNanos();
  mutex_lock l(mu_);
  samples_[next_position_] = {nstime, sample};
  ++next_position_;
  if (TF_PREDICT_FALSE(next_position_ >= samples_.size())) {
    next_position_ = 0;

Revised Content:
void PercentileSamplerCell::Add(double sample) {
  uint64 nstime = EnvTime::NowNanos();
  mutex_lock l(mu_);
  samples_[next_position_].nstime = nstime;
  samples_[next_position_].value = sample;
  ++next_position_;
  if (TF_PREDICT_FALSE(next_position_ >= samples_.size())) {
    next_position_ = 0;
INFO: Elapsed time: 6.262s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

P.S. In the previous instructions in WORKSPACE I'd to comment all "new_local_repository" except the first because I had the issue "Cannot redefine repository after any load statement in the WORKSPACE (from edgetpu):
EdgeTPU
new_local_repository(
name = "edgetpu",
path = "/edgetpu/libedgetpu",
build_file = "/edgetpu/libedgetpu/BUILD"
)
new_local_repository(
name = "libedgetpu",
path = "/usr/lib/aarch64-linux-gnu",
build_file = "/edgetpu/libedgetpu/BUILD"
)

**Comment by fabbro8** [comment]
> I'm trying to follow the guide for running MediaPipe on Coral here: https://github.com/google/mediapipe/tree/master/mediapipe/examples/coral but when I do the "bazel build" for Object detection I have the following issues:
> 
> ERROR: An error occurred during the fetch of repository 'org_tensorflow':
> Traceback (most recent call last):
> File "/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121
> patch(ctx)
> File "/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 135, in patch
> ctx.patch(patchfile, strip)
> com.google.devtools.build.lib.syntax.EvalException: Error applying patch /mediapipe/third_party/org_tensorflow_compatibility_fixes.diff: Incorrect Chunk: the chunk content doesn't match the target
> **Original Position**: 29
> 
> **Original Content**:
> void PercentileSamplerCell::Add(double sample) {
> uint64 nstime = EnvTime::NowNanos();
> mutex_lock l(mu_);
> samples_[next_position_] = {nstime, sample};
> ++next_position_;
> if (TF_PREDICT_FALSE(next_position_ >= samples_.size())) {
> next_position_ = 0;
> 
> **Revised Content**:
> void PercentileSamplerCell::Add(double sample) {
> uint64 nstime = EnvTime::NowNanos();
> mutex_lock l(mu_);
> samples_[next_position_].nstime = nstime;
> samples_[next_position_].value = sample;
> ++next_position_;
> if (TF_PREDICT_FALSE(next_position_ >= samples_.size())) {
> next_position_ = 0;
> ERROR: no such package '@org_tensorflow//tensorflow': Traceback (most recent call last):
> File "/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121
> patch(ctx)
> File "/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 135, in patch
> ctx.patch(patchfile, strip)
> com.google.devtools.build.lib.syntax.EvalException: Error applying patch /mediapipe/third_party/org_tensorflow_compatibility_fixes.diff: Incorrect Chunk: the chunk content doesn't match the target
> **Original Position**: 29
> 
> **Original Content**:
> void PercentileSamplerCell::Add(double sample) {
> uint64 nstime = EnvTime::NowNanos();
> mutex_lock l(mu_);
> samples_[next_position_] = {nstime, sample};
> ++next_position_;
> if (TF_PREDICT_FALSE(next_position_ >= samples_.size())) {
> next_position_ = 0;
> 
> **Revised Content**:
> void PercentileSamplerCell::Add(double sample) {
> uint64 nstime = EnvTime::NowNanos();
> mutex_lock l(mu_);
> samples_[next_position_].nstime = nstime;
> samples_[next_position_].value = sample;
> ++next_position_;
> if (TF_PREDICT_FALSE(next_position_ >= samples_.size())) {
> next_position_ = 0;
> INFO: Elapsed time: 6.262s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded)
> 
> P.S. In the previous instructions in WORKSPACE I'd to comment all "new_local_repository" except the first because I had the issue "Cannot redefine repository after any load statement in the WORKSPACE (from edgetpu):
> # EdgeTPU
> 
> #new_local_repository(
> # name = "edgetpu",
> # path = "/edgetpu/libedgetpu",
> # build_file = "/edgetpu/libedgetpu/BUILD"
> 
> #)
> #new_local_repository(
> # name = "libedgetpu",
> # path = "/usr/lib/aarch64-linux-gnu",
> # build_file = "/edgetpu/libedgetpu/BUILD"
> 
> #)
>

**Comment by mcclanahoochie** [comment]
Hi,

Does a clean install of mediapipe work for the regular desktop hello world example? 

The error seems to reference a patch file https://github.com/google/mediapipe/blob/master/WORKSPACE#L376 

Can you please try from a clean build?
`bazel clean --expunge`
Then follow the coral instrucitons again.

**Comment by sgowroji** [comment]
Hi @fabbro8, Could you please respond whether the above comment resolved your issue. Thanks!
