### ISSUE TITLE
Error building HelloWorld using bazel 3.7.1 with Ubuntu 20.04

### ISSUE THREAD

**Issue by victornain** [google/mediapipe#1336]
I already modified the WORKSPACE, opencv_linux.BUILD and ffmpeg_linux.BUILD files accordingly. Still, I'm getting this error while building. I'm not sure how to declare the execution platform target.

<pre><font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
<font color="#C4A000">DEBUG: </font>/home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
<font color="#CC0000"><b>ERROR: </b></font>Analysis of target &apos;//mediapipe/examples/desktop/hello_world:hello_world&apos; failed; build aborted: invalid registered execution platform &apos;//:default_host_platform&apos;: no such target &apos;//:default_host_platform&apos;: target &apos;default_host_platform&apos; not declared in package &apos;&apos; defined by /home/victor/mediapipe/BUILD.bazel
<font color="#4E9A06">INFO: </font>Elapsed time: 0.151s
<font color="#4E9A06">INFO: </font>0 processes.
<font color="#CC0000"><b>FAILED:</b></font> Build did NOT complete successfully (0 packages loaded, 0 targets \
<font color="#CC0000"><b>FAILED:</b></font> Build did NOT complete successfully (0 packages loaded, 0 targets \
configured)
</pre>

**Comment by jiuqiant** [comment]
Found a similar issue: https://github.com/bazelbuild/rules_go/issues/1698 and the solution is https://releases.bazel.build/bazel-toolchains.html.

However, MediaPipe doesn't specify bazel_toolchains in the WORKSPACE. So, Bazel should pull the latest bazel toolchains by itself. Maybe it's an issue caused by Bazel 3.7 and RBE?

**Comment by victornain** [comment]
> I already modified the WORKSPACE, opencv_linux.BUILD and ffmpeg_linux.BUILD files accordingly. Still, I'm getting this error while building. I'm not sure how to declare the execution platform target.
> 
> DEBUG: /home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
> Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
> DEBUG: /home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
> DEBUG: /home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
> Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
> DEBUG: /home/victor/.cache/bazel/_bazel_victor/10816f194b7351c27a3090d179a5bc7b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
> ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: invalid registered execution platform '//:default_host_platform': no such target '//:default_host_platform': target 'default_host_platform' not declared in package '' defined by /home/victor/mediapipe/BUILD.bazel
> INFO: Elapsed time: 0.151s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets \
> FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets \
> configured)

**Comment by victornain** [comment]
sorry, I closed it by error

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
