### ISSUE TITLE
python and android inference of palm model

### ISSUE THREAD

**Issue by xuchengggg** [google/mediapipe#1339]
Hi, I found that /mediapipe/modules/palm_detection/palm_detection.tflite model outputs different results from python interpreter and Android. I use same float[128*128*3] as input in two ways, while the results are quite different.  And the tensorflow version of python is 1.14/2.1.0, tflite version of android is 2.3.0. Why would this happen?

**Comment by jiuqiant** [comment]
Android is running the graph including the preprocessing, the inference, and the postprocessing on GPU whereas Python is running the CPU version of the graph.
