### ISSUE TITLE
error while running mp_face_mesh demo python file using the github repo

### ISSUE THREAD

**Issue by prasadkevin** [google/mediapipe#1340]
runfile('F:/projects/media_pipe/mediapipe-master/test.py', wdir='F:/projects/media_pipe/mediapipe-master')
Reloaded modules: mediapipe
Traceback (most recent call last):

  File "F:\projects\media_pipe\mediapipe-master\test.py", line 12, in <module>
    from mediapipe.python.solutions import drawing_utils as mp_drawing

  File "F:\projects\media_pipe\mediapipe-master\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util

ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

**Comment by prasadkevin** [comment]
i am running it on windows 10

**Comment by jiuqiant** [comment]
How do you install mediapipe? Can you show the details of your python site-packages/mediapipe/python dir?

**Comment by jiuqiant** [comment]
Also, I realize that some users launch the python runtime under the mediapipe repo, which might cause this issue.

If you clone the repo, please leave your local mediapipe repo directory and launch your python runtime under some other directory such as the root directory. Otherwise, python will read the mediapipe source directory and can't find the binary binding library.

**Comment by prasadkevin** [comment]
okay got it . Thanks for the response

**Comment by vbartle** [comment]
@prasadkevin did running from another directory fix this for you? Running this on RPI4 and the error persists.

**Comment by Zeller-zf** [comment]
![image](https://user-images.githubusercontent.com/78690324/126349304-c12071ae-9226-4a77-80ed-53f5dbcb31f0.png)

**Comment by Zeller-zf** [comment]
> did running from another directory fix this for you? Running this on RPI4 and the error persists.



> @prasadkevin did running from another directory fix this for you? Running this on RPI4 and the error persists.

I also have this problem.

**Comment by vbartle** [comment]
> > did running from another directory fix this for you? Running this on RPI4 and the error persists.
> 
> > @prasadkevin did running from another directory fix this for you? Running this on RPI4 and the error persists.
> 
> I also have this problem.

Please refer to: 
https://github.com/google/mediapipe/issues/1346#issuecomment-852391743

and https://pypi.org/project/mediapipe-rpi4/ 

I believe this at least avoid the above errors.

**Comment by Zeller-zf** [comment]
> d runni

actually,I follow the step. However, I still got a problem.
Traceback (most recent call last):
  File "/home/pi/Desktop/hands.py", line 2, in <module>
    import mediapipe as mp
  File "/usr/local/lib/python3.7/dist-packages/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/usr/local/lib/python3.7/dist-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

**Comment by rajeshrimal516** [comment]
> > d runni
> 
> actually,I follow the step. However, I still got a problem. Traceback (most recent call last): File "/home/pi/Desktop/hands.py", line 2, in import mediapipe as mp File "/usr/local/lib/python3.7/dist-packages/mediapipe/**init**.py", line 16, in from mediapipe.python import * File "/usr/local/lib/python3.7/dist-packages/mediapipe/python/**init**.py", line 17, in from mediapipe.python._framework_bindings import resource_util ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

Did you figure it out the problem? I am also stuck in this error.
