### ISSUE TITLE
Inaccurate hand classification

### ISSUE THREAD

**Issue by TigerHix** [google/mediapipe#1341]
First, thanks for creating this awesome project. I am using MediaPipe's hand tracking to animate VR avatars, and MediaPipe's over-the-top performance on mobile devices is exactly what I have been looking for.

The only issue I have encountered with MediaPipe so far: the hand classification is often inaccurate.

https://giphy.com/gifs/OgQrdmXfhODBxZPmIa

(Green dots mean the hand is classified as right hand, while blue dots mean the hand is classified as left hand.)

This is unrelated to the confidence—I set both detection and tracking confidence threshold to 0.9, but the incorrect classification often scores 0.99+.

Even more confusingly, both of these can happen:
- I raise my right hand; MediaPipe detects a left hand.
- I raise my right hand; MediaPipe detects both hands at the same position.

I am wondering if there is a workaround for this, or this is a limitation with the model?

This is using the Python runtime.

**Comment by TigerHix** [comment]
Kind of solved this with a dumb algorithm to prevent erroneous handedness detection that is very specific to my use case. Hope this issue can get resolved officially!

**Comment by j-void** [comment]
Slightly related issues:
![Screenshot 2020-12-11 at 14 33 01](https://user-images.githubusercontent.com/59042741/101884062-25447300-3bbe-11eb-8aff-66b97da51bbd.png)

Detecting both hands as left or both right for certain frames.

**Comment by fanzhanggoogle** [comment]
Hi, thank you for reporting! Yes, indeed the handedness classification is not perfect due to previously limited supervision in the training. We have been adding significantly more data for this output. Though currently we don't have an exactly release date yet, hopefully we can release the updated version soon.
