### ISSUE TITLE
Objectdetection3d normalized box landmarks on Android

### ISSUE THREAD

**Issue by johannes-mauthe** [google/mediapipe#1342]
I extracted the normalized _box_landmarks_ from the BoxLandmarkSubgraph in order to get the pixel coordinates of each bounding box point on my Android screen.

For the conversion i used the formula
`double x_px = Math.min(Math.floor(landmark.getX() * w), w - 1);`
`  double y_px = Math.min(Math.floor(landmark.getY() * h), h - 1);`

where h and w are the height and width of the root FrameLayout of the activity (In my case 2011 and 1080).

Then i draw debug points for each coordinate to see if they fit to the detected box.
For every angle the coordinates have some kind of offset which you can see in the screenshot.

Do you think the conversion of the normalized values is incorrect or does somebody have an idea why the coordinates are that inaccurate? 

![Screenshot_20201126-101742](https://user-images.githubusercontent.com/36003717/100338458-e49f0400-2fd8-11eb-9f8e-66b53599910f.jpg)

**Comment by shadow111** [comment]
> I extracted the normalized _box_landmarks_ from the BoxLandmarkSubgraph in order to get the pixel coordinates of each bounding box point on my Android screen.
> 
> For the conversion i used the formula
> `double x_px = Math.min(Math.floor(landmark.getX() * w), w - 1);`
> ` double y_px = Math.min(Math.floor(landmark.getY() * h), h - 1);`
> 
> where h and w are the height and width of the root FrameLayout of the activity (In my case 2011 and 1080).
> 
> Then i draw debug points for each coordinate to see if they fit to the detected box.
> For every angle the coordinates have some kind of offset which you can see in the screenshot.
> 
> Do you think the conversion of the normalized values is incorrect or does somebody have an idea why the coordinates are that inaccurate?
> 
> ![Screenshot_20201126-101742](https://user-images.githubusercontent.com/36003717/100338458-e49f0400-2fd8-11eb-9f8e-66b53599910f.jpg)

Helllo @johannes-mauthe  can you please share how you draw your debug points? i'm facing the same issue and i already have developed some helper function to convert the Normalized key points to the camera view coordinates but i can't draw them! it would be helpful if you share your code snippet

**Comment by sgowroji** [comment]
Hi @johannes-mauthe, Could you please try the above steps with the latest release and let us know if you still see the same errors. Thanks!
