### ISSUE TITLE
Objectron crashing on Android - E/tflite: Following operations are not supported by GPU delegate: DEQUANTIZE

### ISSUE THREAD

**Issue by thomsan** [google/mediapipe#1343]
Hi all, I’m trying to run [Objectron](https://google.github.io/mediapipe/solutions/objectron.html) on Android (**Galaxy S20+**) but the app is always crashing.
I was following the [Getting started guide to install MediaPipe on Mac](https://google.github.io/mediapipe/getting_started/install#installing-on-macos). The [HelloWorld desktop example](https://google.github.io/mediapipe/getting_started/hello_world_desktop.html) works fine. Also the [HelloWorld! on Android](https://google.github.io/mediapipe/getting_started/hello_world_android.html) & handtrackinggpu works fine on my Galaxy S20+. I can build and install the [objectdetection3d](https://google.github.io/mediapipe/solutions/objectron.html) example but the app is crashing after I grant the Camera permission.
Does it not run on Galaxy S20+ or what do I need to change in order for it to work?

My logcat outputs a TFlite error (See [logcat.txt](https://github.com/google/mediapipe/files/5602404/logcat.txt) for full logcat): `E/tflite: Following operations are not supported by GPU delegate:
  DEQUANTIZE`

**Comment by sgowroji** [comment]
Hi @thomsan, If you still looking resolution for the above issue,  Try increasing [NUM_BUFFERS](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java#L55) to 3 or 4

**Comment by sgowroji** [comment]
Hi @thomsan, Could you please respond to my above [comment](https://github.com/google/mediapipe/issues/1343#issuecomment-862031578). Thanks!

**Comment by sgowroji** [comment]
Assuming your resolved with the above comment, We are closing this issue now.
