### ISSUE TITLE
problems when using python to build examples

### ISSUE THREAD

**Issue by JihangGao** [google/mediapipe#1349]
I tried to use python ways to build examples at first by simpling pip install mediapipe, which is shown in the installation document ,but it seems to have some problems. It shows that mediapipe has no attributes 'solutions'.
Another question is when I was trying to build bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu, it failed all the time and returned the following messages:
/.cache/bazel/_bazel_gaojihang12704/d2f69a69c48a55432be71e7dbcb0a4be/external/org_tensorflow/tensorflow/core/util/BUILD:374:24: error executing shell command: '/bin/bash -c bazel-out/k8-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}  external/local_config_git/gen...' failed (Exit 127): bash failed: error executing command /bin/bash -c 'bazel-out/k8-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' ... (remaining 4 argument(s) skipped)
I succeeded in building the hello wordl! example, but failed in building handtracking examples.

**Comment by jiuqiant** [comment]
After installing mediapipe, how do you use mediapipe in python? Can you copy and paste your code here? Our Colab examples mentioned in https://github.com/google/mediapipe#mediapipe-in-python use the mediapipe pypi packages. You can try those as well.

**Comment by JihangGao** [comment]
I setup by following the instructions in https://google.github.io/mediapipe/solutions/hands#python, and copied the python code below in the website. I did't change any part of the example code, and tried the example code in the virtual environment.
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands
problems occurred at the third line where it shows that mediapipe has no attributes solutions

**Comment by jiuqiant** [comment]
Can you report your os info and the python version? 
Can you show what your `site-packages/mediapipe/python` has?

**Comment by puparas** [comment]
Hey. I have a problem too
  module 'mediapipe' has no attribute 'solutions'
can you help me please.
```
ubuntu
Python 3.8.5
```
in / mediapipe / python I have
```
BUILD __init__.py
calculator_graph_test.py
framework_bindings.cc
image_frame_test.py
packet_creator.py
packet_getter.py
packet_test.py
pybind
solution_base.py
solution_base_test.py
solutions
timestamp_test.py
```

**Comment by jiuqiant** [comment]
That's the source code directory? We expect that you use `pip install mediapipe` and get mediapipe in your python site-packages dir. If you also clone the repo, please **leave** the repo directory and launch your python runtime. Otherwise, python is reading the mediapipe source directory and can't find the solution dir.

**Comment by jiuqiant** [comment]
@puparas, that's the source code directory? We expect that you use `pip install mediapipe` and get mediapipe in your python site-packages dir. For Ubuntu, the location of site-packages dir might be `/usr/local/lib/python3.6/site-packages`. If you clone the repo, please **leave** your local mediapipe repo directory and launch your python runtime under some other directory such as the root directory. Otherwise, python will read the mediapipe source directory and can't find the solution module. 

Cloning the source code is for building the python package locally and you probably can't use the source code directly because the binding binary doesn't exist in the source code.

**Comment by JihangGao** [comment]
> @puparas, that's the source code directory? We expect that you use `pip install mediapipe` and get mediapipe in your python site-packages dir. For Ubuntu, the location of site-packages dir might be `/usr/local/lib/python3.6/site-packages`. If you clone the repo, please **leave** your local mediapipe repo directory and launch your python runtime under some other directory such as the root directory. Otherwise, python will read the mediapipe source directory and can't find the solution module.

Thanks!!! When I left the previous repo, I succeeded in buildiing the examples. 
By the way, If I just want to get the certain position of fingers, can I manage to do this by simply using pip install mediapipe without bazel building? I wonder if there are some functions which can return certain x,y pos of the critical points drawn on the image?

**Comment by NagarajOpenCV** [comment]
Hi, I have problem with build example project in Android Studio. The following error getting when android project sync,
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "C:/users/nagaraj/_bazel_nagaraj/2deidrcg/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 22, in _create_local_python_repository
		_check_python_bin(repository_ctx, python_bin)
	File "C:/users/nagaraj/_bazel_nagaraj/2deidrcg/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
		auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
	File "C:/users/nagaraj/_bazel_nagaraj/2deidrcg/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
		fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:\Users\nagaraj\AppData\Local\Programs\Python\Python37\' is not executable. Is it the python binary?

I have set python bin path in environment variables on system.

Can you please anyone sort out this issue.

System info:
Windows 10
Android Studio 4.1.1
Python 3.7

Thanks in advance.

**Comment by jiuqiant** [comment]
> > @puparas, that's the source code directory? We expect that you use `pip install mediapipe` and get mediapipe in your python site-packages dir. For Ubuntu, the location of site-packages dir might be `/usr/local/lib/python3.6/site-packages`. If you clone the repo, please **leave** your local mediapipe repo directory and launch your python runtime under some other directory such as the root directory. Otherwise, python will read the mediapipe source directory and can't find the solution module.
> 
> Thanks!!! When I left the previous repo, I succeeded in buildiing the examples.
> By the way, If I just want to get the certain position of fingers, can I manage to do this by simply using pip install mediapipe without bazel building? I wonder if there are some functions which can return certain x,y pos of the critical points drawn on the image?

Yes, you can. 
For getting the coordinates of a certain position of the finger, you can use [the HandLandmark enum](https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/hands.py#L42).


```
image_hight, image_width, _ = image.shape
for hand_landmarks in results.multi_hand_landmarks:
  print('index finger tip x coordinate:', 
        hand_landmarks[mp_hands.HandLandmark.INDEX_FINGER_TIP].x * image_width)
  print('index finger tip y coordinate:',
        hand_landmarks[mp_hands.HandLandmark.INDEX_FINGER_TIP].y * image_hight)

```

**Comment by jiuqiant** [comment]
> Hi, I have problem with build example project in Android Studio. The following error getting when android project sync,
> ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
> Traceback (most recent call last):
> File "C:/users/nagaraj/_bazel_nagaraj/2deidrcg/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 22, in _create_local_python_repository
> _check_python_bin(repository_ctx, python_bin)
> File "C:/users/nagaraj/_bazel_nagaraj/2deidrcg/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
> auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
> File "C:/users/nagaraj/_bazel_nagaraj/2deidrcg/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
> fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
> Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:\Users\nagaraj\AppData\Local\Programs\Python\Python37' is not executable. Is it the python binary?
> 
> I have set python bin path in environment variables on system.
> 
> Can you please anyone sort out this issue.
> 
> System info:
> Windows 10
> Android Studio 4.1.1
> Python 3.7
> 
> Thanks in advance.

As we mentioned in https://google.github.io/mediapipe/getting_started/install#installing-on-windows, MediaPipe doesn't support building its Android apps on native Windows because of the limited bazel support for Android on native Windows. Please try WSL instead. You can find the instructions at https://google.github.io/mediapipe/getting_started/install#installing-on-windows-subsystem-for-linux-wsl.

**Comment by jiuqiant** [comment]
I believe the original issue is solved. Going to mark this issue solved.

**Comment by ZodiacFRA** [comment]
> Yes, you can.
> For getting the coordinates of a certain position of the finger, you can use [the HandLandmark enum](https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/hands.py#L42).
> 
> ```
> image_hight, image_width, _ = image.shape
> for hand_landmarks in results.multi_hand_landmarks:
>   print('index finger tip x coordinate:', 
>         hand_landmarks[mp_hands.HandLandmark.INDEX_FINGER_TIP].x * image_width)
>   print('index finger tip y coordinate:',
>         hand_landmarks[mp_hands.HandLandmark.INDEX_FINGER_TIP].y * image_hight)
> ```
Hi :) 
Unfortunately I get a `TypeError: 'NormalizedLandmarkList' object is not subscriptable` when I try this with the [example code](https://google.github.io/mediapipe/solutions/hands#python)

Any idea on what could cause this?

**Comment by NagarajOpenCV** [comment]
Thanks for responding. Unfortunately, Mediapipe installation guide page is
not opening snapshot attached in this email.

Can you share me any video tutorial for android development?


Thanks & Regards,
Nagaraj S

**Comment by jiuqiant** [comment]
> image_hight, image_width, _ = image.shape
> for hand_landmarks in results.multi_hand_landmarks:
>   print('index finger tip x coordinate:', 
>         hand_landmarks[mp_hands.HandLandmark.INDEX_FINGER_TIP].x * image_width)
>   print('index finger tip y coordinate:',
>         hand_landmarks[mp_hands.HandLandmark.INDEX_FINGER_TIP].y * image_hight)

My mistake.
It should be 
```
print('index finger tip x coordinate:',
      hand_landmarks.landmark[mp_hands.HandLandmark.INDEX_FINGER_TIP].x * image_width)
print('index finger tip y coordinate:',
      hand_landmarks.landmark[mp_hands.HandLandmark.INDEX_FINGER_TIP].y * image_hight)
```

**Comment by orkebel** [comment]
HI ! 
i try to link mediapipe with touchdesigner. 
When i try to run this simple code in touchdesigner :
"import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils"

i got this message : 

"Traceback (most recent call last):
  File "</base_mediapipe/text_template:op('/base_mediapipe/text_template').run()>", line 1
td.Error: File "/base_mediapipe/text_template", line 7
AttributeError: module 'mediapipe' has no attribute 'solutions'
Results of run operation resulted in exception."

i copy paste mediapipe into the directory where i got my .toe
i let mediapipe into the depo where i first install it --> /usr/"myname"/mediapipe
i copy paste mediapipe into the site-packages --> /usr/local/bin/pythonUsers/hugo/Library/Python/3.7/lib/python/site-packages
In Touchdesigner, the section "python 64 bit module path" is complete with this path --> Users/hugo/Library/Python/3.7/lib/python/site-packages

i'm on mac version 11.1 and i'm also a newbie :) 
can you light my path ? 
Thank you very much !

**Comment by andtauk** [comment]
I have this same problem:
AttributeError: module 'mediapipe' has no attribute 'solutions' using the IDE 

I follow all the steps for installing mediapipe (for windows 10)
But only works when a use this way:

(DL_tensorflow) C:\WINDOWS\system32>python
Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mediapipe as mp
>>> mp_drawing = mp.solutions.drawing_utils
>>> pose = mp.solutions.pose.Pose(static_image_mode=True, min_detection_confidence=0.5)
>>> INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
>>>

**Comment by shabelson** [comment]
Hi,

Had Similar Problem:

_mediapipe.python.solutions
AttributeError: module 'mediapipe' has no attribute 'python'_

System:
windows 10
python 3.7 

Mediapipe installation:
1. tried to "pip install mediapipe" but getting error: 
**ERROR: Could not find a version that satisfies the requirement mediapipe
ERROR: No matching distribution found for mediapipe**
2. Downloaded a .whl file, and installed manually.
3. Used the example files

-------------------------------------------------------------
import cv2
import mediapipe as mp
import time

cap = cv2.VideoCapture(0) # Webcam ID
# cap.set(3,320)
# cap.set(4,240)

mpHands=mp.solutions.hands
hands=mpHands.Hands() # Press Ctrl to call out hands.py
mpDraw=mp.solutions.drawing_utils

# # Set up Frame-rate
pTime=0 # Previous time is equal to Zero.
cTime=0 # Current time


# # Video is a sequence of images, so we need a while loop
while True:
    success,img = cap.read()
    imgRGB=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    results=hands.process(imgRGB)
    # print(results.multi_hand_landmarks) # Detect have hand or not

    if results.multi_hand_landmarks:
        for handLms in results.multi_hand_landmarks: # extract the information of each hand.
            for id, lm in enumerate(handLms.landmark):
                print(id,lm)
                # transfer the pixel ratio to position
                h,w,c=img.shape  # height,width,channel
                cx,cy =int(lm.x*w),int(lm.y*h) # position of center
                # print(id,cx,cy)
                # print(id, lm)
                if id==0:
                    cv2.circle(img,(cx,cy),25,(255,0,255),cv2.FILLED)

            mpDraw.draw_landmarks(img,handLms,mpHands.HAND_CONNECTIONS)

    cTime=time.time()
    fps=1/(cTime-pTime)
    pTime=cTime

    # Display FPS information
    cv2.putText(img,str(int(fps)),(10,70),cv2.FONT_HERSHEY_PLAIN,3,(255,0,255),3) # (img,FPS number,position,fonttype,size,color,thickness)

    cv2.imshow("Image",img)
    cv2.waitKey(1)
----------------------------------------------------------

**Comment by vbartle** [comment]
Getting the same attribute error: `AttributeError: module 'mediapipe' has no attribute 'solutions'`; python 3.8 on RPI4. Running python outside of local mediapipe directory returns same error. 

Where is solutions supposed to be located and how can I get it?

**Comment by H4ckerman666** [comment]
hello I have the same error
***
AttributeError: partially initialized module 'mediapipe' has no attribute 'solution_base' (most likely due to a circular import)
***
but I don't understand how they solved it, can you help me? @jiuqiant @JihangGao

**Comment by andtauk** [comment]
> hello I have the same error
> 
> AttributeError: partially initialized module 'mediapipe' has no attribute 'solution_base' (most likely due to a circular import)
> 
> but I don't understand how they solved it, can you help me? @jiuqiant @JihangGao

Maybe ou need to change your filename from "mediapipe.py" to another one.

**Comment by H4ckerman666** [comment]
What a shame @andtauk 
I have to sleep well 👍

**Comment by Sebski17** [comment]
> > hello I have the same error
> > AttributeError: partially initialized module 'mediapipe' has no attribute 'solution_base' (most likely due to a circular import)
> > but I don't understand how they solved it, can you help me? @jiuqiant @JihangGao
> 
> Maybe ou need to change your filename from "mediapipe.py" to another one.

I am having the same problem. I am outside mediapipe source folder and none of my files are called mediapipe.py.
Any ideas?

**Comment by tordvilz** [comment]
I have the same issue running in anaconda jupyter notebook
Python 3.9.5
macOS Catalina 10.15.7

**import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_holistic = mp.solutions.holistic

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9598eaa84d67> in <module>
----> 1 mp_drawing = mp.solutions.drawing_utils
      2 mp_holistic = mp.solutions.holistic

AttributeError: module 'mediapipe' has no attribute 'solutions'**

Any solution?

**Comment by RajarshiPrattipati** [comment]
Nothing works anywhere. Is there a fix?

[](url
![Screenshot from 2022-01-15 14-20-01](https://user-images.githubusercontent.com/20268648/149616110-f2c1d54b-b134-4e21-9366-4658c2970e66.png)
)
