### ISSUE TITLE
Using the visibility prediction

### ISSUE THREAD

**Issue by ksanjeevan** [google/mediapipe#1351]
Hi,

I'm trying to use the visibility prediction for each landmark to avoid false detection of movement but am having some trouble using it. I can see that the value is roughly in the -10, 10 range, but am not sure about:

- what does this quantity represent?
- what is negative visibility?
- how does it relate to the `presence` field? 
- what would be reasonable thresholds that a landmark is visible?

Really would appreciate any guidance with this, thanks.

**Comment by bazarevsky** [comment]
Hello,
As the model predicts the presence and visibility via the same output as x, y values, to get probabilities, you need to apply the sigmoid function on these values so you'll have values in the range [0, 1]. We do this in subsequent calculators just after the model inference in the graph.

So reasonable threshold will be 0.5 if you apply the sigmoid or 0.0 if you want to skip this step as sigmoid(0.0) = 0.5

Visibility - is a value indicating if the point is visible or hidden (occluded by another body part) on a frame.
Presence - is a value indicating if the point is present on a frame (or point is located outside the fame).

**Comment by ksanjeevan** [comment]
thanks for the definitions @bazarevsky
