### ISSUE TITLE
New face landmarks detection model in tflite (facemesh upgrade)

### ISSUE THREAD

**Issue by syke404** [google/mediapipe#1355]
I read in this link https://blog.tensorflow.org/2020/11/iris-landmark-tracking-in-browser-with-MediaPipe-and-TensorFlowJS.html that the facemesh model has been upgraded to the faceLandmarksDetection model. I could only find the tfjs model though. Where can I find the tflite model for this? The main models page still points to the older facemesh model (https://google.github.io/mediapipe/solutions/models)

**Comment by mgyong** [comment]
Pls post this issue in the tfjs repository
