### ISSUE TITLE
Is there a good way to know when a graph is done with a frame and there will be no further output stream packets?

### ISSUE THREAD

**Issue by danhd123** [google/mediapipe#1357]
I've got a modified version of the Iris graph, with output streams for face landmarks, left and right iris depth, plus the face detection and landmark tracking confidences. When there's a fully visible face, this is great. When there's no face, it's okay. When there's a partial face, or a barely detected face, I'm running into synchronization issues on the output end. Sometimes I only get a face detection confidence, and no landmarks, let alone irises. I'm not sure that I'll always have 2 irises visible. Etc. When this happens, it'd be good to know that I won't be getting a packet for those output streams, or alternatively, that I've received the last output stream packet for a given frame/timestamp. 

The first idea I had was to use a pass-through calculator; that should be the first subgraph to finish, almost instant, and use that as a sort of "end-of-output" sentinel for the previous frame. But that would also require me to limit the graph to only one frame in flight, which could hurt throughput and waste potential parallelism (unless I'm misunderstanding how output stream packets are delivered). I'll probably fall back to this if no one has any better ideas.

Then I took a look at some of the alternative stream handlers. Nothing seems to match what I want. 

Any better ideas?

**Comment by hadon** [comment]
I see.  We need to know when the landmarks output packet will not arrive.  MediaPipe calculators generally indicate no packets at a given timestamp by updating the output "timestamp bound" past that timestamp.  

I think it's true that the output API's currently don't offer a good solution to this issue.  The straightforward solution is for output API's to indicate timestamp bounds as well as non-empty packets.  Currently, only non-empty packets are reported.  This could be remedied by improving OutputStreamObserver and OutputStreamPoller.  We have added this functionality for calculator inputs with the setting "SetProcessTimestampBounds()", but not for the graph output API's.  Can you let us know where you are running MediaPipe?  There may be some minor differences in how stream timestamps are indicated between the Java, Objective-C, and C++ MediaPipe API's.  

One technique you can try is to pack all of the outputs together into a single packet, but this requires writing some new calculator(s).

**Comment by danhd123** [comment]
I'm running on iOS (and would like to run on macOS eventually, but that's a much lower priority). 

I tried packing the outputs together into a single packet, but it didn't work (hung on waiting for eg the landmarks output packet), but I was not watching the timestamp bound. Do you have any examples for this?

**Comment by hadon** [comment]
The fact that a calculator hangs waiting for the landmark output packet indicates that when detection fails, the landmark output is delivering neither packets nor timestamp bounds.  In that case, even if the output API delivers timestamp bounds, we will still get no hint about the missing packets.  

One approach for investigating this to define a calculator similar to "ProcessBoundToPacketCalculator" from "calculator_graph_bounds_test.cc".  Using such a calculator, you can get a packet for every timestamp bound update.  If the landmark output delivers a timestamp bound, you can observe it using the output packet from ProcessBoundToPacketCalculator.  If the landmark output fails to deliver timestamp bounds, you could investigate other output streams to see which ones deliver timestamp bounds successfully. 

The MediaPipe team is still working to make realtime synchronization work more smoothly.  Thanks for helping us improve the rough edge cases.

**Comment by hadon** [comment]
Closing this issue for now.  Feel free to re-open if it is still relevant to you.
