### ISSUE TITLE
Encrypting a model in Mediapipe

### ISSUE THREAD

**Issue by PoseAI** [google/mediapipe#1358]
Hi, Apple recently enabled the encryption of CoreML models during app development.  
[https://developer.apple.com/documentation/coreml/core_ml_api/encrypting_a_model_in_your_app](url)

We are currently inching toward deployment and protecting model IP is rather important to us.  Hopefully this can be done within Mediapipe!   While I haven't spent a lot of time on the internals, I believe within Mediapipe the model is packaged as a TFlite file rather than .mlmodelc, and the pipeline interfaces with coreml through the delegate, so I am not sure how to access Apple encryption. 

Can we encrypt models using the mediapipe platform?  If so how? Is there something similar for Android as well?

regards,
Martin

(note: I was encouraged to repost this from the group forum here. I will link if one gets answered!)

**Comment by chuoling** [comment]
Model encryption is currently not on MediaPipe roadmap. However, you could consider using a 3rd-party encryptor (e.g., see answers in https://github.com/tensorflow/tensorflow/issues/21501) to encrypt your TFLite model for distribution. You can then, for example, modify [TfLiteModelCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_model_calculator.cc) to incorporate the associated decryption library to restore the TFLite model file, before sending it out as a MODEL side packet to be consumed by [TfLiteInferenceCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_inference_calculator.cc).

**Comment by PoseAI** [comment]
Ok thanks for the swift reply.  
Encryption is well outside my realm of expertise but I suspect the suggestion would be considerably more vulnerable to cracking than using the OS encryption.

Need to contemplate how that impacts our pipeline, and whether writing a CoreMLInferenceCalculator for use on IOS might be easier!
Anyhow I will close the ticket. Thanks again for swiftness.
