### ISSUE TITLE
Problem when adding node to graph on Android studio.

### ISSUE THREAD

**Issue by duy-maimanh** [google/mediapipe#1359]
I'm getting an error:
`2020-12-02 10:54:36.207 15565-15582/? E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.google.mediapipe.apps.facesegmetationgpu, PID: 15565
    com.google.mediapipe.framework.MediaPipeException: not found: ValidatedGraphConfig Initialization failed.
    No registered object with name: LightCalculator; Unable to find Calculator "LightCalculator"`
This error occurs when I try to append node to a graph.

LightCalculator is just a copy of RecolorCalculator with a different name.
It also crashes with other files like BilateralFilterCalculator.

I imported a new project and the node worked, but the error would appear after a few builds if i add new node.
I think it's related to the cache. Do you have any advice?

**Comment by duy-maimanh** [comment]
Solved.
Import the wrong deps at BUILD in the example because I have 2 libraries with the same name.
Sorry for any inconvenience.

**Comment by DandyLorenz** [comment]
> 解决了。
> 在本例中，在构建时导入错误的�dep，因为我有两个同名的库。
> 抱歉给您带来不便。

Can you provide the BUILD file code for your hand tracking and building android AAR?thanks

**Comment by duy-maimanh** [comment]
Hey @DandyLorenz 
Sorry but i never build hand tracking example before. So i can't provide you BUILD file.
