### ISSUE TITLE
Needed help regarding Iris tflite model output interpretation

### ISSUE THREAD

**Issue by ViswanathaReddyGajjala** [google/mediapipe#1361]
When `iris_landmark.tflite` model is used as iris tracker I have got two outputs eye_contour((1, 213)) and iris(1, 15)). The output values are very large. I might be missing some image processing. Is there any preprocessing that needs to be done for the input image.

**Comment by ViswanathaReddyGajjala** [comment]
Sorry, I haven't properly normalized the image that leads to inaccurate values. Closing the issue.

**Comment by midhulavijayan** [comment]
I am getting inaccurate values. I have used the following steps as pre-processing

img = cv2.imread('eye.jpg') # reading eye image
inp = cv2.resize(img, (64, 64))
inp = cv2.cvtColor(inp, cv2.COLOR_BGR2RGB)
inp = inp.astype(np.float32)
inp = np.reshape(inp, (1, 64, 64, 3))
inp = (inp/255.0)

Where I am going wrong ?

**Comment by mcclanahoochie** [comment]
is `inp` a CV_32FC3 Mat? otherwise it would be all zeros (CV-8UC3)

**Comment by ViswanathaReddyGajjala** [comment]
@midhulavijayan  you have to resize the image based on aspect ratio. I have added the codes to my repo https://github.com/ViswanathaReddyGajjala/mediapipe_pytorch/tree/main/iris. You can look into the preprocessing codes. Hope this helps!

**Comment by Tord-Zhang** [comment]
@ViswanathaReddyGajjala Hi, the repository is unavialable now, could you please share the code?

**Comment by Monibsediqi** [comment]
hi @ViswanathaReddyGajjala, may I ask how did you figure out the iris_landmark.tflite large value output? 
I am using the iris_landmark.tflite directlt but I'm getting a very large output for iris landmarks.
