### ISSUE TITLE
Issue while using custom generated MediaPipe AAR

### ISSUE THREAD

**Issue by devvikas** [google/mediapipe#1362]
I have generated my custom MediaPipe AAR  using the steps defined here:
https://google.github.io/mediapipe/getting_started/android_archive_library.html

When I try to use it in my app, I am getting the following errors:
Build failed
:app:compileDebugJavaWithJavac
app/src/main/java/co/introtuce/mediapipesegmentationgradle/helper/CustomFrameProcessor.java
TAG has private access in FrameProcessor
TAG has private access in FrameProcessor
cannot find symbol method maybeAcceptNewFrame()
addFrameListener has private access in FrameProcessor
addFrameListener has private access in FrameProcessor
addFrameListener has private access in FrameProcessor
..
..
addFrameListener has private access in FrameProcessor
packetCreator has private access in FrameProcessor
packetCreator has private access in FrameProcessor
videoInputStream has private access in FrameProcessor
mediapipeGraph has private access in FrameProcessor
mediapipeGraph has private access in FrameProcessor
TAG has private access in FrameProcessor

**Comment by sgowroji** [comment]
Hi @devvikas, Could you please provide the complete steps to reproduce the above error. Thanks!

**Comment by sgowroji** [comment]
Due to lack of activity we are closing this issue now.
