### ISSUE TITLE
iOS App Crashes NSInvalidArgumentException

### ISSUE THREAD

**Issue by Nvelu048** [google/mediapipe#1363]
I am trying to have Hair Segmentation, Iris Tracking and FaceEffect in Single App.

I referred [this](https://github.com/noppefoxwolf/HandTracker) and created iOS Framework.

And added iOS Framework in SwiftUI XCode Project.

Individual examples are working fine.

Between switching examples i stop the graph with following code

```
- (void)stopGraph {
    self.mediapipeGraph.delegate = nil;
    [self.mediapipeGraph cancel];
    // Ignore errors since we're cleaning up.
    [self.mediapipeGraph closeAllInputStreamsWithError:nil];
    [self.mediapipeGraph waitUntilDoneWithError:nil];
    NSLog(@"Graph stopped successfully");
}
```

It executes as expected.  But when calling again startGraph i am getting following error

```

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSString stringWithUTF8String:]: NULL cString'

```

What to do? Need Help

**Comment by danhd123** [comment]
Got a stack trace?

**Comment by Nvelu048** [comment]
Yeah it pointed startGraph method

**Comment by Nvelu048** [comment]
Yeah it pointed startGraph method

**Comment by danhd123** [comment]
-startWithError: doesn't have ant calls to -stringWithUTF8String: Can you paste the whole stack trace?

**Comment by Nvelu048** [comment]
I used SwiftUI's Tab View, 

Then i changed to 

```
VStack{
  // Effect
 HStack{
  // Buttons to switch between effects
 }
}
```

Now Issue solved

@danhd123 thanks for the support

**Comment by guodi1991** [comment]
hello, I also encountered the same problem, may I ask if you have solved it now?

**Comment by trunghvbk** [comment]
Hi @Nvelu048
Can you explain the reason that caused this error? I see it's about the UI implementation and it seems not reasonable?
