### ISSUE TITLE
iOS framework: maxFramesInFlight is broken with more than one output stream (or no pixel buffer output streams)

### ISSUE THREAD

**Issue by danhd123** [google/mediapipe#1364]
While researching a solution for #1357, I was trying to figure out how `maxFramesInFlight` worked, I discovered that `_framesInFlight` is incremented on `-sendPixelBuffer:intoStream:packetType:` or `-sendPixelBuffer:intoStream:packetType:timestamp:`, (`MPPGraph.mm:358`) but unconditionally decremented on _every_ received output stream packet processed in `CallFrameDelegate` (`MPPGraph.mm:186`), which is called (up to) once for every output stream. The header notes that 
```
/// This works as long as frames are sent or received using these methods:
///  - sendPixelBuffer:intoStream:packetType:[timestamp:]
///  - addFrameOutputStream:outputPacketType:
```
It does not say "received using a single instance of `-addFrameOutputStream:outputPacketType:`" and if it did, that would make it quite useless for any nontrivial use of the framework. As it is, with any more than 1 output stream, the `_framesInFlight` counter will almost immediately go negative (and eventually underflow, but not for years, even at 60 fps and 8 output streams).

This also means that if you want to remove the pixel buffer output stream (such as if you want to do your own rendering, or care more about numerical outputs), any frames that don't have output won't cause `_framesInFlight` to decrement and Mediapipe appears to hang (really, drops all packets) after just a few frames. A workaround for this would be to set `maxFramesInFlight` to 0, but that's not good for realtime performance on some devices, especially if the graph and/or the rest of the app do a lot of realtime processing. 

Is `-setMaxQueueSize:forStream:error:` called with the input stream intended to replace `maxFramesInFlight` and is it still experimental? Only `MPPGraph.h` has a reference to it as such. Doesn't seem on the surface like it throttles except if the first node in the graph is still processing, although I haven't dug deep enough to say for sure. 

At any rate, `maxFramesInFlight` is basically completely broken for non-trivial graphs and outputs, and so is in desperate need of fixing or replacement.

**Comment by danhd123** [comment]
Please tell me that the change in 2b58ccee on staging to "fix" this is not final. It makes `maxFramesInFlight` completely useless for projects that want to do their own rendering or otherwise don't have a pixel buffer output stream. Useless (but documented as useful) is better than useless (but documented as useful) and broken, I guess, but I'd really rather it was as useful as documented instead.

**Comment by sgowroji** [comment]
Hi @danhd123, Could you please check the above issue with the latest IOS release and confirm you still see the same. Thanks!

**Comment by danhd123** [comment]
Yes, the issue is still present.

**Comment by kuaashish** [comment]
Hello @danhd123,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by danhd123** [comment]
The issue is not resolved. The `setMaxQueueSize` call looks promising, but the continued use of `_maxFramesInFlight` is broken.

**Comment by kuaashish** [comment]
Hello @danhd123,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by danhd123** [comment]
It's still a bug since there is no Mediapipe Solutions API for iOS.

**Comment by schmidt-sebastian** [comment]
Please transition to MP Tasks for iOS.
