### ISSUE TITLE
error in building hand_tracking in windows

### ISSUE THREAD

**Issue by loaysh2010** [google/mediapipe#1367]
C:/users/loay sharaky/_bazel_loay sharaky/hr7sucjp/external/org_tensorflow/tensorflow/lite/kernels/BUILD:634:11: C++ compilation of rule '@org_tensorflow//tensorflow/lite/kernels:builtin_op_kernels' failed (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 66 argument(s) skipped)
cl : Command line warning D9002 : ignoring unknown option '-O3'
external/org_tensorflow/tensorflow/lite/kernels/elementwise.cc(82): fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'msc1.cpp', line 1518)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe.  You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.958s, Critical Path: 5.56s
INFO: 28 processes: 28 internal.
FAILED: Build did NOT complete successfully

**Comment by jiuqiant** [comment]
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1001?view=msvc-160 suggests that you can often fix an optimization problem by removing one or more optimization options.

You may remove `-c opt` from the bazel build command to remove the optimization.

**Comment by jiuqiant** [comment]
Tensorflow requires Visual C++ 2019  and Build Tools 2019:https://www.tensorflow.org/install/source_windows. My guess is "ensorflow/lite/kernels:builtin_op_kernels" also requires this.
