### ISSUE TITLE
Build error / ERROR: no such package '@org_tensorflow//tensorflow': On-Device, Real-Time Hand Tracking with MediaPipe

### ISSUE THREAD

**Issue by Usama011** [google/mediapipe#137]
ERROR: no such package '@org_tensorflow//tensorflow':
using window and dockers 
want to build android sample app for hand detection

**Comment by jiuqiant** [comment]
Similar to https://github.com/google/mediapipe/issues/91, https://github.com/google/mediapipe/issues/113, and https://github.com/google/mediapipe/issues/126. Unfortunately, MediaPipe doesn't support Windows. If you are only interested in Windows, we support Windows Subsystem for Linux. You can find how to set up MediaPipe in WSL [here](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows-subsystem-for-linux-wsl).
