### ISSUE TITLE
Black Screen with Objectron and Instant Motion Tracking Examples on Xperia XZ3

### ISSUE THREAD

**Issue by ROBYER1** [google/mediapipe#1370]
Tried testing out the examples from the below links on my Sony Xperia XZ3, all produce black screens, have seen some other mentions of this around and some fix suggestions but will the examples be updated?

https://google.github.io/mediapipe/solutions/objectron.html

https://google.github.io/mediapipe/solutions/instant_motion_tracking

Device manufacturer, model, and O/S: Sony Xperia XZ3, Model: H8416, Android Version 10 UK unlocked phone with 02 Sim
Build number: 52.1.A.3.92
Output of adb shell getprop ro.build.fingerprint: Sony/H8416/H8416:10/52.1.A.3.92/052001A003009202006556692:user/release-keys

**Comment by mgyong** [comment]
Can you paste the error message into this issue?

**Comment by ROBYER1** [comment]
> Can you paste the error message into this issue?

I couldn't see anything in android logcat when I tried just now. I also found that the cup example would work if I minimised and maximised the app a lot. 

I would say that the black screen is intermittent in behaviour. Feel free to merge this issue with the intermittent black screen issue.

**Comment by TheBricktop** [comment]
Same issue on galaxy S8, instant motion tracking prebuild apk is just asking for camera and then black screen is shown instead of rendered ar frame.

**Comment by sgowroji** [comment]
Hi @ROBYER1, Could you please test the above with our latest MediaPipe release and let us know if you still see the same error. Thanks!
