### ISSUE TITLE
running upper body example failed in Run:  Calculator::Process()

### ISSUE THREAD

**Issue by chillcloud-dev** [google/mediapipe#1371]
Hello MediaPipe team

i was trying to run the example of upper body detection on Ubuntu 18 and I run into the following issue: 
(I am using the lastest version of mediapipe)

`
E20201204 12:21:02.177610  5583 demo_run_graph_main_gpu.cc:186] Failed to run the graph: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "poselandmarkupperbodygpu__posedetectiongpu__ImageToTensorCalculator" failed: Only BGRA/RGBA textures are supported, passed format: 24
`

I build this example with the following command:

`bazel-3.4.0 build -c opt \
    --copt -DBOOST_ERROR_CODE_HEADER_ONLY \
    --copt -DBOOST_SYSTEM_NO_DEPRECATED --copt -DMESA_EGL_NO_X11_HEADERS \
    --copt -DEGL_NO_X11 --cxxopt='-std=c++17' \
    mediapipe/examples/desktop/upper_body_pose_tracking:upper_body_pose_tracking_gpu`

and try to execute it with : 

`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/upper_body_pose_tracking/upper_body_pose_tracking_gpu \
    --calculator_graph_config_file=mediapipe/graphs/pose_tracking/upper_body_pose_tracking_gpu.pbtxt`

Could you please tell me how to fix this issue? 
Thanks

**Comment by chillcloud-dev** [comment]
its the same issue i encounter merging hand and pose tracking into a single graph 

[https://github.com/google/mediapipe/issues/1365#issue-756201678](url)

**Comment by lernem** [comment]
Hi @chillcloud-dev ,

I met this same issue, in the following file, basically adding a A to both COLOR_BGR2RGB and to SRGB can solve it.

"/home/jetpack/mediapipe/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc"

    cv::cvtColor(camera_frame_raw, camera_frame, cv::COLOR_BGR2RGBA);
    if (!load_video) {
      cv::flip(camera_frame, camera_frame, /*flipcode=HORIZONTAL*/ 1);
    }

    // Wrap Mat into an ImageFrame.
    auto input_frame = absl::make_unique<mediapipe::ImageFrame>(
        mediapipe::ImageFormat::SRGBA, camera_frame.cols, camera_frame.rows,
        mediapipe::ImageFrame::kGlDefaultAlignmentBoundary);
    cv::Mat input_frame_mat = mediapipe::formats::MatView(input_frame.get());
    camera_frame.copyTo(input_frame_mat);

**Comment by chillcloud-dev** [comment]
@lernem 
thanks 
it solved this issue 

but to make a small note to this 

if someone wants to use the same cc file for another example -> the Image format must be changed back from SRGBA to SRGB 
 otherwise you will get a black window and no output
