### ISSUE TITLE
Error with Hand tracking and Pose in Desktop

### ISSUE THREAD

**Issue by loaysh2010** [google/mediapipe#1372]
Hello All, I have an error when trying to run the hand tracking or pose desktop examples.

1) when I try :
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt 

from cmd I got this Error: 'GLOG_logtostderr' is not recognized as an internal or external command,
operable program or batch file.

2) when I try:

D:\mediapipe\bazel-bin\mediapipe\examples\desktop\hand_tracking>hand_tracking_cpu.exe
Also I got this Error:
E20201204 14:27:36.430857  3228 demo_run_graph_main.cc:146] Failed to run the graph: ; Can't find file:

Any one can let me know to run these examples ?

![cmdex](https://user-images.githubusercontent.com/24863268/101164070-43015d80-363d-11eb-8e39-15c0c3a0740e.png)

**Comment by jiuqiant** [comment]
1. Please run 
```
D:\mediapipe> set GLOG_logtostderr=1
D:\mediapipe> bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt
```
2. Please  go back to D:\mediapipe first. The calculator graph config file path is a relative path that assumes you are at the repo root directory.

**Comment by loaysh2010** [comment]
I did it also, and I got an error for bazel-bin not recognized

![image](https://user-images.githubusercontent.com/24863268/101216769-c09e8b00-3688-11eb-9e63-7ed83f0e8fe9.png)

**Comment by loaysh2010** [comment]
I solved It. 
as I am working with windows the path in the command line must be with " \" not "/" 
so, the below commands work well.

D:\mediapipe> set GLOG_logtostderr=1
D:\mediapipe> bazel-bin\mediapipe\examples\desktop\hand_tracking\hand_tracking_cpu --calculator_graph_config_file=mediapipe\graphs\hand_tracking\hand_tracking_desktop_live.pbtxt
