### ISSUE TITLE
Custom model with multiple input crashing at ModifyGraphWithDelegate. 

### ISSUE THREAD

**Issue by afsaredrisy** [google/mediapipe#1377]
I am trying to run multiple input model in mediapipe gpu pipeline. Using custom tflite model which accepts three input tensors and produces one output tensors. following is the graph I am using.
```
input_stream: "input_video"
output_stream: "output_video"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "IMAGE_GPU:transformed_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 224
      output_height: 224
    }
  }
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "IMAGE_GPU:transformed_bg_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 448
      output_height: 448
    }
  }
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "IMAGE_GPU:transformed_pl_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 448
      output_height: 448
    }
  }
}


node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE_GPU:transformed_input_video"
  input_stream: "BG_GPU:transformed_bg_input_video"
  input_stream: "PL_GPU:transformed_pl_input_video"
  output_stream: "TENSORS_GPU:image_tensor"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteConverterCalculatorOptions] {
      zero_center: false
      max_num_channels: 3
    }
  }
}


node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS_GPU:image_tensor"
  output_stream: "TENSORS_GPU:segmentation_tensor"
  #input_side_packet: "CUSTOM_OP_RESOLVER:op_resolver"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
      model_path: "mediapipe/models/my_model.tflite"
      use_gpu: true
    }
  }
}
node {
  calculator: "TfLiteTensorsToCompositionCalculator"
  input_stream: "TENSORS_GPU:segmentation_tensor"
  output_stream: "IMAGE_GPU:output_video"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteTensorsToCompositionCalculatorOptions] {
      tensor_width: 448
      tensor_height: 448
      tensor_channels: 3
      combine_with_previous_ratio: 0.9
      output_layer_index: 0
    }
 }
}

```

I modified TfLiteConverterCalculator to suite multiple input & pipeline is running with one tflite model. TfLiteTensorsToCompositionCalculator calculator is also working fine as I validated with other graph. Here is a sample model which I am trying to run. 
[sample-tflite-file](https://drive.google.com/file/d/1KQ3dq_yHPQtdL8KNlPVA7uR_-YOBb0hl/view?usp=sharing). Pipeline is crashing in TfLiteInferenceCalculator::open inside LoadDelegate()  at call `RET_CHECK_EQ(interpreter_->ModifyGraphWithDelegate(delegate_.get()),
               kTfLiteOk);` I verified all input & output tensors size by printing `gpu_data_in_[i]->elements`, Input buffer are seems to be correctly binding. Following is the error log I am getting. 
```
E/libc++abi: terminating with uncaught exception of type absl::lts_2020_02_25::bad_any_cast: Bad any cast
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 25841 (mediapipe_gl_ru), pid 24342 (segmentationgpu)
```
Any Idea what could be the issue? Or What does it means when ModifyGraphWithDelegate throws error?

**Comment by mcclanahoochie** [comment]
when you call interpreter->ModifyGraphWithDelegate, the GPU backend inspects your TFLite graph def and tells the TFLite framework which ops it can handle and which it can’t.

you can try adding a TfLiteCustomOpResolverCalculator node, like in https://github.com/google/mediapipe/blob/master/mediapipe/modules/palm_detection/palm_detection_gpu.pbtxt#L39  and see if that helps.

does your TfLiteConverterCalculator output a vector of tensors to match the order of your expected 3 model inputs?
id: fg_small_in:0
id: bg_in:1
id: fg_in:2

**Comment by afsaredrisy** [comment]
@mcclanahoochie  Thank you for response, I was able to fix it by changing to model architecture. It was some error in the model architecture when was running with GPU delegate
