### ISSUE TITLE
Location of the hand(s) in the frame

### ISSUE THREAD

**Issue by mtsatsev** [google/mediapipe#1378]
Hello, 
I want to use mediapipe together with a model which I built to detect hands and recognize gestures in my frames which I get from openCV. I am using python (because I want to use Keras and I am not very comfortable with C++) and I was looking for a way to get the x and y coordinates of a certain points from the hands.

1. For example I need the x and y coordinates of all the RINGS.
1. How would I do that?
 
 I see that there is an x and y coordinates in the land_marks however when I try to get only certain ones It tells me that it is not iterrable or subscriptable. Is there a way to achieve this functionality from python itself? 

Hence can I do something like this:

```python
  if results.multi_hand_landmarks:
      for hand_landmarks in results.multi_hand_landmarks:
          mp_drawing.draw_landmarks(image, hand_landmarks, mp_hands.HAND_CONNECTIONS)
    --> print(hand_landmarks[Index of the RINGS])
```
--> Line of interest.

**Comment by jiuqiant** [comment]
See https://github.com/google/mediapipe/issues/1349#issuecomment-736702707
