### ISSUE TITLE
Error synchronizing project with BUILD files

### ISSUE THREAD

**Issue by jonleinena** [google/mediapipe#1381]
Hello, I am getting the following erroor when synchronizing the project with BUILD files via the Bazel plugin

`ERROR: Error while parsing 'same_pkg_direct_rdeps(//mediapipe\examples\android\src\java\com\google\mediapipe\apps\basic:basic.iml+//mediapipe\examples\android\src\java\com\google\mediapipe\apps\upperbodyposetrackinggpu:upperbodyposetrackinggpu.iml+//:WORKSPACE)': syntax error at '\examples \android \src'`

I am a newbie to this, so any help would be highly appreciated :)

**Comment by fahim26** [comment]
do you find any solution @jonleinena ? if you find any solution ,please let me know

**Comment by hansonap** [comment]
> Hello, I am getting the following erroor when synchronizing the project with BUILD files via the Bazel plugin
> 
> `ERROR: Error while parsing 'same_pkg_direct_rdeps(//mediapipe\examples\android\src\java\com\google\mediapipe\apps\basic:basic.iml+//mediapipe\examples\android\src\java\com\google\mediapipe\apps\upperbodyposetrackinggpu:upperbodyposetrackinggpu.iml+//:WORKSPACE)': syntax error at '\examples \android \src'`
> 
> I am a newbie to this, so any help would be highly appreciated :)

@jonleinena I see that you closed this issue - did you manage to find a solution?
