### ISSUE TITLE
hand_benmark.tflite 

### ISSUE THREAD

**Issue by wm901115nwpu** [google/mediapipe#1382]
I clone the mediapipe project, but I find the hand_benmark.tflite is output name is name: model/model/tf.nn.relu6_1/Relu6;model/model/batch_normalization_1/FusedBatchNormV3;model/model/depthwise_conv2d/depthwise;model/model/conv2d_9/Conv2D. In general, output name is only one.

**Comment by sgowroji** [comment]
Hi @wm901115nwpu, Could you please verify the above issue with the latest release. If your query not answered, Please reach us with complete details to assist you better. Thanks!

**Comment by sgowroji** [comment]
Hi @wm901115nwpu, Could you please respond to my above [comment](https://github.com/google/mediapipe/issues/1382#issuecomment-861285954). Thanks!

**Comment by wm901115nwpu** [comment]
I'm sorry, I've just seen it. I try it. It is Ok. I want to know how to do it.

**Comment by sgowroji** [comment]
Thank you for the update. We are closing this issue now.
