### ISSUE TITLE
Differences between normalized face landmarks in python mediapipe versus scaledMesh in the browser with tensorflow.js

### ISSUE THREAD

**Issue by antornix** [google/mediapipe#1383]
Dear MediaPipe team,

I have just found this incredible technology of yours, MediaPipe is a game changer in many aspects, thank you very very much for developing and opensourcing this incredible technology.

I was able to very quickly prototype a working python-based mediapipe application which is ingests videos and then infers features derived from the face landmarks over time. All 468 landmarks there are based on normalized coordinates within the closed interval [0, 1], elegantly abstracting the points from the variety of dimensions of the videos.

However, at the client or frontend/MediaPipe/TensorFlow.js side I am not ingesting videos, instead I get real time video from the webcam and get the same landmarks of interest, however, their values are not equally normalized between 0 and 1. I found two different means for obtaining the landmarks, mesh and scaledMesh, of these two, the later, scaledMesh, is supposed to provide normalized landmarks. I believe those landmarks in tensorflow.js are in fact normalized, but in a different mathematical plane.

I imagine several ways of normalizing the values by myself, the problem is that I must match the numbers of the server, or at least, a very close approximation.

At python, for example, landmark 300, I obtain this:
Pt300(x,y,z)=[0.929972410202, 0.45059671998, -0.007927045226]

At the browser's javascript console, with scaledMesh, I get this:
Pt300(x,y,z)= [ 590.142333984375, 220.46336364746094, -0.957552433013916 ]

I wonder if the API provides some means for obtaining equally normalized landmarks from the browser or tensorflow.js as those I already have at the server, and if there isn't, may you suggest some procedure I could apply in order to convert the normalized values from MediaPipe/tensorflow.js to MediaPipe/Python?

Thank you very much for your help and time.

Best regards,
Antornix

**Comment by sgowroji** [comment]
Hi @antornix, Could you please go through the [reference](https://google.github.io/mediapipe/solutions/face_mesh.html#python-solution-api) for getting landmarks of facemesh in python platform with both video and webcam as input. If your query still not answered, Please reach us to assist you better on the above. Thanks!

**Comment by sgowroji** [comment]
Hi @antornix, Did you get a chance to go through my above comment. Thanks!

**Comment by sgowroji** [comment]
Assuming your resolved with the above comment, We are closing this issue now.
