### ISSUE TITLE
Issue with starting and stop of Graph Android

### ISSUE THREAD

**Issue by Arul2962** [google/mediapipe#1386]
Hi mediapipe team,
      I am able to **stop the graph** on button click in two ways,

   1)Using **processor.getGraph().closeAllPacketSources();** where all the packet sending is closed.
   
   2)Sending different packet on same stream in another class called by MainActivity class (which in the graph uses Gate Calculator)

Question 1: Which method I am trying to do it in correct way?

Question 2:Is there any way to check whether the **graph is running or not**?

 On packet callback I am getting **image frame** from graph and converted to **bitmap** to display it on screen,as the callback sends **stream of packets** ,

Question 3: Is there any way that I can get first frame and **stop the graph** and after button click need to get **currently** **rendered packet** 

  I am working with face effect to **apply different textures** and need to extract as image frame after applying different textures,
 
  I used to convert the output GpuBuffer to ImageFrame and extracted that packet through **packetcallback**,
am I doing it right or any other way is possible?

Need help!

**Comment by sgowroji** [comment]
Hi @Arul2962, Could you please share the issue status. If you're still looking for it, can you share the code changes. Thanks!
