### ISSUE TITLE
Suggestion: Palm Detection Mediapipe jS api

### ISSUE THREAD

**Issue by djthegr8** [google/mediapipe#1389]
Firstly, kudos on the jS API! Its enabled a lot of us to get higher perf than TFjS
I wanted to suggest also releasing a Palm Detector for web, as this would be greatly beneficial due to possible speed and otherwise increases in performance.
This shouldn't be too hard as its just removing a calculator from the hands version.

**Comment by asi9games** [comment]
yes please !

**Comment by djthegr8** [comment]
@mgyong can this be done?

**Comment by djthegr8** [comment]
@chuoling or @tyrmullen ?

**Comment by chuoling** [comment]
@djthegr8 Sorry for the late response. We've added palm-detection solution APIs as a feature request, and will update this issue with progress.

**Comment by djthegr8** [comment]
Amazing!

**Comment by djthegr8** [comment]
uhh @sgowroji could we keep this opened till its been added?

**Comment by 4thWallInt** [comment]
Has there been any movement on this particular issue?

**Comment by djthegr8** [comment]
@mgyong @chuoling could you update here?

**Comment by sureshdagooglecom** [comment]
Hi @djthegr8 ,
Plam detection is available in the latest MediaPipe version , please verify and close this issue.

**Comment by djthegr8** [comment]
Great!
