### ISSUE TITLE
do you mean Hair Segmentation?

### ISSUE THREAD

**Issue by lisbravo** [google/mediapipe#139]
https://github.com/google/mediapipe/blob/master/mediapipe/docs/hand_segmentation_desktop.md
in:
https://github.com/google/mediapipe/releases/tag/v0.6.2

**Comment by mgyong** [comment]
@lisbravo Thks for spotting error. Corrected.
It is https://github.com/google/mediapipe/blob/master/mediapipe/docs/hair_segmentation_desktop.md
