### ISSUE TITLE
Getting Bounding Box on Handtracking python

### ISSUE THREAD

**Issue by rubythalib33** [google/mediapipe#1390]
How to get bounding box of the handtracking using python code?

**Comment by jiuqiant** [comment]
The hands Python API doesn't return the palm bboxes. But, you can edit the source code to let the hands API output it:

```
--- a/mediapipe/python/solutions/hands.py
+++ b/mediapipe/python/solutions/hands.py
@@ -142,7 +142,7 @@ class Hands(SolutionBase):
             'handlandmarkcpu__ThresholdingCalculator.threshold':
                 min_tracking_confidence,
         },
-        outputs=['multi_hand_landmarks', 'multi_handedness'])
+        outputs=['multi_hand_landmarks', 'multi_handedness', 'palm_detections'])
 
   def process(self, image: np.ndarray) -> NamedTuple:
     """Processes an RGB image and returns the hand landmarks and handedness of each detected hand.
```

Then, you can get the palm detection by
```
for palm_detection in results.palm_detections:
      print(palm_detection.location_data.relative_bounding_box)
```

You will see the relative bbox data like the following:
```
xmin: 0.6212505102157593
ymin: 0.46138930320739746
width: 0.2514756917953491
height: 0.37721356749534607
```

**Comment by TigerHix** [comment]
> The hands Python API doesn't return the palm bboxes. But, you can edit the source code to let the hands API output it:
> 
> ```
> --- a/mediapipe/python/solutions/hands.py
> +++ b/mediapipe/python/solutions/hands.py
> @@ -142,7 +142,7 @@ class Hands(SolutionBase):
>              'handlandmarkcpu__ThresholdingCalculator.threshold':
>                  min_tracking_confidence,
>          },
> -        outputs=['multi_hand_landmarks', 'multi_handedness'])
> +        outputs=['multi_hand_landmarks', 'multi_handedness', 'palm_detections'])
>  
>    def process(self, image: np.ndarray) -> NamedTuple:
>      """Processes an RGB image and returns the hand landmarks and handedness of each detected hand.
> ```
> 
> Then, you can get the palm detection list by
> 
> ```
> for palm_detection in results.palm_detections:
>       print(palm_detection.location_data.relative_bounding_box)
> ```
> 
> You will see the relative bbox data like the following:
> 
> ```
> xmin: 0.6212505102157593
> ymin: 0.46138930320739746
> width: 0.2514756917953491
> height: 0.37721356749534607
> ```
> 
> Finally, you can multiple those values by image width or height to get the bbox coordinates.

 This sounds like a good parameter to add in future Python builds!

**Comment by rubythalib33** [comment]
wow thank you so much

**Comment by rubythalib33** [comment]
I got this type of error after adding that:
```
Traceback (most recent call last):
  File "camera_set.py", line 34, in <module>
    for palm_detection in results.palm_detections:
AttributeError: type object 'SolutionOutputs' has no attribute 'palm_detections'

```

**Comment by jiuqiant** [comment]
If you use `pip install mediapipe` to install mediapipe, you need to modify the mediapipe/python/solutions/hands.py file in your python3.x/site-packages/mediapipe dir. If you edit the repo code, you need to rebuild the python package by running setup.py.

**Comment by rubythalib33** [comment]
i see thank you then

**Comment by rubythalib33** [comment]
where the file of setup.py in mediapipe repo?

**Comment by rubythalib33** [comment]
I use this command instead to get the bounding box
```
for hand_landmark in results.multi_hand_landmarks:
            x = [landmark.x for landmark in hand_landmark.landmark]
            y = [landmark.y for landmark in hand_landmark.landmark]
            
            center = np.array([np.mean(x)*image_width, np.mean(y)*image_hight]).astype('int32')
            cv2.circle(image, tuple(center), 10, (255,0,0), 1)  #for checking the center 
            cv2.rectangle(image, (center[0]-200,center[1]-200), (center[0]+200,center[1]+200), (255,0,0), 1)
```

**Comment by thylm** [comment]
> The hands Python API doesn't return the palm bboxes. But, you can edit the source code to let the hands API output it:
> 
> ```
> --- a/mediapipe/python/solutions/hands.py
> +++ b/mediapipe/python/solutions/hands.py
> @@ -142,7 +142,7 @@ class Hands(SolutionBase):
>              'handlandmarkcpu__ThresholdingCalculator.threshold':
>                  min_tracking_confidence,
>          },
> -        outputs=['multi_hand_landmarks', 'multi_handedness'])
> +        outputs=['multi_hand_landmarks', 'multi_handedness', 'palm_detections'])
>  
>    def process(self, image: np.ndarray) -> NamedTuple:
>      """Processes an RGB image and returns the hand landmarks and handedness of each detected hand.
> ```
> 
> Then, you can get the palm detection list by
> 
> ```
> for palm_detection in results.palm_detections:
>       print(palm_detection.location_data.relative_bounding_box)
> ```
> 
> You will see the relative bbox data like the following:
> 
> ```
> xmin: 0.6212505102157593
> ymin: 0.46138930320739746
> width: 0.2514756917953491
> height: 0.37721356749534607
> ```
> 
> Finally, you can multiple those values by image width or height to get the bbox coordinates.

I have tried this but it is bbox for palm, not for hand?

**Comment by jiuqiant** [comment]
> > The hands Python API doesn't return the palm bboxes. But, you can edit the source code to let the hands API output it:
> > ```
> > --- a/mediapipe/python/solutions/hands.py
> > +++ b/mediapipe/python/solutions/hands.py
> > @@ -142,7 +142,7 @@ class Hands(SolutionBase):
> >              'handlandmarkcpu__ThresholdingCalculator.threshold':
> >                  min_tracking_confidence,
> >          },
> > -        outputs=['multi_hand_landmarks', 'multi_handedness'])
> > +        outputs=['multi_hand_landmarks', 'multi_handedness', 'palm_detections'])
> >  
> >    def process(self, image: np.ndarray) -> NamedTuple:
> >      """Processes an RGB image and returns the hand landmarks and handedness of each detected hand.
> > ```
> > 
> > 
> > Then, you can get the palm detection list by
> > ```
> > for palm_detection in results.palm_detections:
> >       print(palm_detection.location_data.relative_bounding_box)
> > ```
> > 
> > 
> > You will see the relative bbox data like the following:
> > ```
> > xmin: 0.6212505102157593
> > ymin: 0.46138930320739746
> > width: 0.2514756917953491
> > height: 0.37721356749534607
> > ```
> > 
> > 
> > Finally, you can multiple those values by image width or height to get the bbox coordinates.
> 
> I have tried this but it is bbox for palm, not for hand?

See https://github.com/google/mediapipe/issues/1507#issuecomment-761110587 for getting hand bbox.

**Comment by Haidy-Elnagdy** [comment]
I have installed mediapipe using  (pip install mediapip), and I do not know how to edit the source code or even where to find it.

**Comment by Haidy-Elnagdy** [comment]
Sorry for the question but where to type these commands?

**Comment by Haidy-Elnagdy** [comment]
Thanks, I did this step, what next?

**Comment by Haidy-Elnagdy** [comment]
> > I have installed mediapipe using (pip install mediapip), and I do not know how to edit the source code or even where to find it.
> 
> ```
> $ python3 -m pip install mediapipe
> ...
> $ python3 -m pip show mediapipe
> Name: mediapipe
> Version: 0.8.3.1
> Summary: MediaPipe is the simplest way for researchers and developers to build world-class ML solutions and applications for mobile, edge, cloud and the web.
> Home-page: https://github.com/google/mediapipe
> Author: MediaPipe Authors
> Author-email: mediapipe@google.com
> License: Apache 2.0
> Location: /usr/local/home/username/env/lib/python3.8/site-packages
> Requires: opencv-python, numpy, dataclasses, attrs, wheel, six, absl-py, protobuf
> Required-by:
> ```

Thanks a lot

**Comment by jiuqiant** [comment]
> I am getting this error, why?
> for palm_detection in result.palm_detections:
> TypeError: 'NoneType' object is not iterable

You need to check whether palm_detections is None first in case of no hands detected in the current frame.

```
if not results.palm_detections:
  for palm_detection in results.palm_detections:
        print(palm_detection.location_data.relative_bounding_box)
```

**Comment by bharath5673** [comment]
```
#ok for BBOX u can add this

      image_width , image_height , c = image.shape
      for hand_landmark in results.multi_hand_landmarks:
        landmark_array = np.empty((0, 2), int)

        for _, landmark in enumerate(hand_landmark.landmark):
          landmark_x = min(int(landmark.x * image_width), image_width - 1)
          landmark_y = min(int(landmark.y * image_height), image_height - 1)
          landmark_z = landmark.z

          landmark_point = [np.array((landmark_x, landmark_y))]
          landmark_array = np.append(landmark_array, landmark_point, axis=0)
        x, y, w, h = cv2.boundingRect(landmark_array)
        cv2.rectangle(image, (x+35,y-70), (x+w+160,y+h-100), (255,255,255), 2)
```

![Screenshot (161)](https://user-images.githubusercontent.com/33729709/130441548-d09101d7-3cdf-4bf9-a91a-a9ae052966b4.png)
