### ISSUE TITLE
Get depth coordinate in @mediapipe/hands API

### ISSUE THREAD

**Issue by yuccai** [google/mediapipe#1392]
Hi @mgyong
Great job for the @mediapipe/hands package :fireworks:  Performances are much higher than @tensorflow-models/handpose.
Just a few questions :

  - is it possible to retrieve the depth of each landmarks ? currently we only get 2d landmarks but we can get 2.5d landmarks
  - what is the visibility field ? does it states if the joint is occluded or not ? it is currently undefined

Thanks !

**Comment by delebash** [comment]
I am also looking for this answer as with tfjs we automatically got the z coordinate.  In mediapipe hands the docs say (we take Z-value from image depth map, if it exists per corresponding coordinate).

How is this map produced?

Thanks

**Comment by amgadserry** [comment]
+1

**Comment by delebash** [comment]
Fyi in the output docs it say it calculate that for you. https://google.github.io/mediapipe/solutions/hands#output

**Comment by Aprameyah** [comment]
+1

**Comment by sgowroji** [comment]
z represents the landmark depth with the depth at the wrist being the origin, and the smaller the value the closer the landmark is to the camera. The magnitude of z uses roughly the same scale as x.

World landmarks https://google.github.io/mediapipe/solutions/hands#multi_hand_landmarks  and  Hand landmarks https://google.github.io/mediapipe/solutions/hands#multi_hand_landmarks
