### ISSUE TITLE
MediaPipe Holistic error

### ISSUE THREAD

**Issue by AntonioDomenech** [google/mediapipe#1393]
First of all, thank you very much for the continuos releases. This is a great technology and one can clearly see there is a lot of efford behing it!

Here is one error I found:
Using the holistic option in python, if I set upper_body_only=True I get the following error:

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "Trial.py", line 63, in <module>
    image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS)
  File "/home/a/Documents/MediaPipe-0.8.1/venv/lib/python3.7/site-packages/mediapipe/python/solutions/drawing_utils.py", line 108, in draw_landmarks
    raise ValueError(f'Landmark index is out of range. Invalid connection '
ValueError: Landmark index is out of range. Invalid connection from landmark #30 to landmark #32.
```

I'm either doing something wrong or It seem it has problems to draw only the upper body

Here is the exact code I used:
```
import cv2
import time
import mediapipe as mp

mp_drawing = mp.solutions.drawing_utils
mp_holistic = mp.solutions.holistic

holistic = mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5, upper_body_only=True)
cap = cv2.VideoCapture(1)
while cap.isOpened():
  success, image = cap.read()
  if not success:
    print("Ignoring empty camera frame.")
    # If loading a video, use 'break' instead of 'continue'.
    continue

  # Flip the image horizontally for a later selfie-view display, and convert
  # the BGR image to RGB.
  image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)
  # To improve performance, optionally mark the image as not writeable to
  # pass by reference.
  image.flags.writeable = False
  results = holistic.process(image)

  # Draw landmark annotation on the image.
  image.flags.writeable = True
  image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
  mp_drawing.draw_landmarks(
      image, results.face_landmarks, mp_holistic.FACE_CONNECTIONS)
  mp_drawing.draw_landmarks(
      image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS)
  mp_drawing.draw_landmarks(
      image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS)
  mp_drawing.draw_landmarks(
      image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS)
  cv2.imshow('MediaPipe Holistic', image)
  if cv2.waitKey(5) & 0xFF == 27:
    break
holistic.close()
cap.release()
```

**Comment by jiuqiant** [comment]
When "upper_body_only" is set to True, results.pose_landmarks only has the first 25 upper body landmarks.
So, you probably  can do the following:

```
  mp_drawing.draw_landmarks(
      image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS[:25])
```

**Comment by AntonioDomenech** [comment]
@jiuqiant Thanks for the help. Unfortunatelly, I've tried this and it doesn't work. I get the following error:

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "Trial.py", line 63, in <module>
    image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS[:25])
TypeError: 'frozenset' object is not subscriptable
```

**Comment by jiuqiant** [comment]
Hi, you can fix this issue by converting POSE_CONNECTIONS to a list for now. In your `/home/a/Documents/MediaPipe-0.8.1/venv/lib/python3.7/site-packages/mediapipe/python/solutions/pose.py,` you need to apply the following changes:

```
diff --git a/mediapipe/python/solutions/pose.py b/mediapipe/python/solutions/pose.py
index 70fafc1..e541c0c 100644
--- a/mediapipe/python/solutions/pose.py
+++ b/mediapipe/python/solutions/pose.py
@@ -76,7 +76,7 @@ class PoseLandmark(enum.IntEnum):
   LEFT_FOOT_INDEX = 32

 BINARYPB_FILE_PATH = 'mediapipe/modules/pose_landmark/pose_landmark_cpu.binarypb'
-POSE_CONNECTIONS = frozenset([
+POSE_CONNECTIONS = [
     (PoseLandmark.NOSE, PoseLandmark.RIGHT_EYE_INNER),
     (PoseLandmark.RIGHT_EYE_INNER, PoseLandmark.RIGHT_EYE),
     (PoseLandmark.RIGHT_EYE, PoseLandmark.RIGHT_EYE_OUTER),
@@ -113,7 +113,7 @@ POSE_CONNECTIONS = frozenset([
     (PoseLandmark.LEFT_HEEL, PoseLandmark.LEFT_FOOT_INDEX),
     (PoseLandmark.RIGHT_ANKLE, PoseLandmark.RIGHT_FOOT_INDEX),
     (PoseLandmark.LEFT_ANKLE, PoseLandmark.LEFT_FOOT_INDEX),
-])
+]
```

We will  provide both UPPER_BODY_POSE_CONNECTIONS and POSE_CONNECTIONS in the next release. Then, drawing upper body landmarks will be

```
mp_drawing.draw_landmarks(
    image, results.pose_landmarks, mp_holistic.UPPER_BODY_POSE_CONNECTIONS)
```

**Comment by AntonioDomenech** [comment]
Excelent, thank you very much!

**Comment by jiuqiant** [comment]
Fixed: 

> Hi, you can fix this issue by converting POSE_CONNECTIONS to a list for now. In your `/home/a/Documents/MediaPipe-0.8.1/venv/lib/python3.7/site-packages/mediapipe/python/solutions/pose.py,` you need to apply the following changes:
> 
> ```
> diff --git a/mediapipe/python/solutions/pose.py b/mediapipe/python/solutions/pose.py
> index 70fafc1..e541c0c 100644
> --- a/mediapipe/python/solutions/pose.py
> +++ b/mediapipe/python/solutions/pose.py
> @@ -76,7 +76,7 @@ class PoseLandmark(enum.IntEnum):
>    LEFT_FOOT_INDEX = 32
> 
>  BINARYPB_FILE_PATH = 'mediapipe/modules/pose_landmark/pose_landmark_cpu.binarypb'
> -POSE_CONNECTIONS = frozenset([
> +POSE_CONNECTIONS = [
>      (PoseLandmark.NOSE, PoseLandmark.RIGHT_EYE_INNER),
>      (PoseLandmark.RIGHT_EYE_INNER, PoseLandmark.RIGHT_EYE),
>      (PoseLandmark.RIGHT_EYE, PoseLandmark.RIGHT_EYE_OUTER),
> @@ -113,7 +113,7 @@ POSE_CONNECTIONS = frozenset([
>      (PoseLandmark.LEFT_HEEL, PoseLandmark.LEFT_FOOT_INDEX),
>      (PoseLandmark.RIGHT_ANKLE, PoseLandmark.RIGHT_FOOT_INDEX),
>      (PoseLandmark.LEFT_ANKLE, PoseLandmark.LEFT_FOOT_INDEX),
> -])
> +]
> ```
> 
> We will provide both UPPER_BODY_POSE_CONNECTIONS and POSE_CONNECTIONS in the next release. Then, drawing upper body landmarks will be
> 
> ```
> mp_drawing.draw_landmarks(
>     image, results.pose_landmarks, mp_holistic.UPPER_BODY_POSE_CONNECTIONS)
> ```

pose.py has been updated: https://github.com/google/mediapipe/blob/a92cff7a60031f5c3097b06e74416732d85b5011/mediapipe/python/solutions/pose.py#L80

**Comment by alighofrani95** [comment]
It doesn't still fix my issue.

1. How can I draw specific landmarks by not all of them?
2. How can I draw every landmark with special attributes such as color and thickness?
