### ISSUE TITLE
Tried to get the data of fingers, but ended up with COMPILE ERROR

### ISSUE THREAD

**Issue by FubukiRandeZvous** [google/mediapipe#1396]
I've attempted to tag every point of my fingers. I followed the instruction of this guy:
https://www.deuxexsilicon.com/2020/04/07/2nd-static-gestures-gathering-data/
error: type 'const mediapipe::LandmarkList' does not provide a subscript operator
        const unsigned char lmIndex = &landmark - &landmarks[0];
                                                                             ~~~~~~~~~^~
Can everyone explain it? Thank you!

**Comment by danhd123** [comment]
It's exactly what it says. LandmarkList doesn't expose the underlying array (it may not even have one) or provide a subscript operator. It may have when that article was written, but it doesn't anymore.

**Comment by FubukiRandeZvous** [comment]
Thanks for replying me so rapidly.
I'm going to look for another way to get the landmark's data
