### ISSUE TITLE
Will you public pb or SavedModel of facedetector_front.tflite

### ISSUE THREAD

**Issue by tworuler** [google/mediapipe#14]
I want to use facedetector_front.tflite in tfjs, but I didn't find any way to convert .tflite to .pb. Do you have the .pb or SavedModel of facedetector_front.tflite?

**Comment by mgyong** [comment]
@tworuler Is your use case to run facedetector in a web browser? We are working on getting MediaPipe calculators & graphs to run on the web as well. That is coming likely later in the year. For now we don't have .pb or savedmodel of facedetector

**Comment by tworuler** [comment]
@mgyong Yes. I have converted the .tflite to .pb myself. Thank you for sharing such good face detector model.

**Comment by lbwang2006** [comment]
> @mgyong Yes. I have converted the .tflite to .pb myself. Thank you for sharing such good face detector model.

hi can you share the pb with me ? thank you~~

**Comment by nszjh** [comment]
@tworuler hi，could you tell me how the .tflite convert  to .pb?    I have tryed to use tensorflow's toco, but it didnot work

**Comment by jiuqiant** [comment]
@tworuler Seems like you already solved this issue by yourself ;) I am going to close this issue. Cheers.

**Comment by tworuler** [comment]
> @tworuler hi，could you tell me how the .tflite convert to .pb? I have tried to use tensorflow's toco, but it didnot work

First, I use [flatc](https://github.com/tensorflow/tensorflow/blob/release_1.14.0/tensorflow/lite/tools/visualize.py#L38) to convert tflite to json. Second, I parse the json and create tensorflow graph. Finally, I read model weights from .tflite, use them to initialize weights in tensorflow graph and save the graph as pb.

**Comment by Bluebie** [comment]
Very keen for a version that works on web! I'd love to use the hand landmarks detector to recognise handshapes from webcam input for a sign language search engine. Currently my project can search english and find auslan sign videos, but can't do the inverse. Looking forward to a version that runs on the web, whatever form that takes. 💙

**Comment by tworuler** [comment]
I received some emails to ask the details about converting .tflite to .pb. [Here is my code](https://gist.github.com/tworuler/bd7bd4c6cd9a8fbbeb060e7b64cfa008), hope this can help you.
