### ISSUE TITLE
Error while building Desktop version of Hand Tracking CPU/GPU

### ISSUE THREAD

**Issue by dipampatel18** [google/mediapipe#140]
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu`

Using the above command, when I build the hand tracking module after Hello World, I get the following error for both CPU/GPU versions. I have no idea how to solve it.

`INFO: Build options --copt and --define have changed, discarding analysis cache.`
`INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (1 packages loaded, 3259 targets configured).`
`INFO: Found 1 target...`
`ERROR: /home/dipam/mediapipe/mediapipe/calculators/image/BUILD:330:1: C++ compilation of rule '//mediapipe/calculators/image:image_cropping_calculator' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 72 argument(s) skipped)`

`Use --sandbox_debug to see verbose messages from the sandbox`
`mediapipe/calculators/image/image_cropping_calculator.cc: In member function 'mediapipe::Status mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*)':
mediapipe/calculators/image/image_cropping_calculator.cc:265:7: error: 'boxPoints' is not a member of 'cv'
   cv::boxPoints(min_rect, src_points);
       ^~~~~~~~~`
`mediapipe/calculators/image/image_cropping_calculator.cc:265:7: note: suggested alternative: 'Point'
   cv::boxPoints(min_rect, src_points);
       ^~~~~~~~~
       Point`
`Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build`
`Use --verbose_failures to see the command lines of failed build steps.`
`INFO: Elapsed time: 40.722s, Critical Path: 39.26s`
`INFO: 92 processes: 92 linux-sandbox.`
`FAILED: Build did NOT complete successfully`

**Comment by jiuqiant** [comment]
What's the version of your OpenCV library? It seems that OpenCV 2.x doesn't have `cv::boxPoint`.

**Comment by dipampatel18** [comment]
> What's the version of your OpenCV library? It seems that OpenCV 2.x doesn't have `cv::boxPoint`.

I'm using OpenCV 4.1.1 as it was recommended OpenCV 3.x and above. Should I downgrade? Also, the gcc and g++ version is 7.4.0.

**Comment by jiuqiant** [comment]
OpenCV 4.1.1 still has boxPoints() in the imgproc header file: [opencv2/imgproc.hpp](https://github.com/opencv/opencv/blob/4.1.1/modules/imgproc/include/opencv2/imgproc.hpp). 
Another possibility is that your local OpenCV BUILD file (either [third_party/opencv_macos.BUILD](https://github.com/google/mediapipe/blob/master/third_party/opencv_macos.BUILD) or [third_party/opencv_linux.BUILD](https://github.com/google/mediapipe/blob/master/third_party/opencv_linux.BUILD)) doesn't have the right configuration for OpenCV 4. By default, the OpenCV BUILD files are for OpenCV 3. You need to modify the BUILD file for OpenCV 4 because OpenCV 4 has a new location for the header files (they put the headers in opencv4/opencv2/ dir) . For example, if your OpenCV is installed in `/usr/local/opt/opencv` on mac, your `third_party/opencv_macos.BUILD` needs to be
```
cc_library(
    name = "opencv",
    srcs = glob(
        [
            "local/opt/opencv/lib/libopencv_core.dylib",
            "local/opt/opencv/lib/libopencv_highgui.dylib",
            "local/opt/opencv/lib/libopencv_imgcodecs.dylib",
            "local/opt/opencv/lib/libopencv_imgproc.dylib",
            "local/opt/opencv/lib/libopencv_optflow.dylib",
            "local/opt/opencv/lib/libopencv_video.dylib",
            "local/opt/opencv/lib/libopencv_videoio.dylib",
        ],
    ),
    hdrs = glob(["local/opt/opencv/include/opencv4/**/*.h*"]),
    includes = ["local/opt/opencv/include/opencv4/"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
```

If it doesn't work, let me know your platform and the location of your OpenCV libraries and headers. I can help you figure out the right configuration.

**Comment by dipampatel18** [comment]
> OpenCV 4.1.1 still has boxPoints() in the imgproc header file: [opencv2/imgproc.hpp](https://github.com/opencv/opencv/blob/4.1.1/modules/imgproc/include/opencv2/imgproc.hpp).
> Another possibility is that your local OpenCV BUILD file (either [third_party/opencv_macos.BUILD](https://github.com/google/mediapipe/blob/master/third_party/opencv_macos.BUILD) or [third_party/opencv_linux.BUILD](https://github.com/google/mediapipe/blob/master/third_party/opencv_linux.BUILD)) doesn't have the right configuration for OpenCV 4. By default, the OpenCV BUILD files are for OpenCV 3. You need to modify the BUILD file for OpenCV 4 because OpenCV 4 has a new location for the header files (they put the headers in opencv4/opencv2/ dir) . For example, if your OpenCV is installed in `/usr/local/opt/opencv` on mac, your `third_party/opencv_macos.BUILD` needs to be
> 
> ```
> cc_library(
>     name = "opencv",
>     srcs = glob(
>         [
>             "local/opt/opencv/lib/libopencv_core.dylib",
>             "local/opt/opencv/lib/libopencv_highgui.dylib",
>             "local/opt/opencv/lib/libopencv_imgcodecs.dylib",
>             "local/opt/opencv/lib/libopencv_imgproc.dylib",
>             "local/opt/opencv/lib/libopencv_optflow.dylib",
>             "local/opt/opencv/lib/libopencv_video.dylib",
>             "local/opt/opencv/lib/libopencv_videoio.dylib",
>         ],
>     ),
>     hdrs = glob(["local/opt/opencv/include/opencv4/**/*.h*"]),
>     includes = ["local/opt/opencv/include/opencv4/"],
>     linkstatic = 1,
>     visibility = ["//visibility:public"],
> )
> ```
> 
> If it doesn't work, let me know your platform and the location of your OpenCV libraries and headers. I can help you figure out the right configuration.

Hi @jiuqiant . I really appreciate your detailed response. My Linux has OpenCV 2 and 4. And because of that, it is giving me issues. I'll remove both of them, freshly install v4 and take care of the location of the OpenCV libraries. I will update you here soon. Thanks again!

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
