### ISSUE TITLE
How can I use mediapipe FACEMESH tflite model in a flutter applicaiton?

### ISSUE THREAD

**Issue by AryanSethi** [google/mediapipe#1401]
I tried running the mediapipe facemesh tflite model inside a jupyter notebook and I'm getting very weird results. For now I'm plotting only x and y. The plots do look like faces but don't respond to changes in my expressions (eg. me opening my mouth wide open) through the webcam

**Comment by PeterTF656** [comment]
Dear friend,

Have you had any luck with integrating facemesh with flutter?

Best,
Zelin

**Comment by AryanSethi** [comment]
@PeterTF656 
Couldn't find anything related to it bro  : /

**Comment by sgowroji** [comment]
You can refer this [code](https://github.com/zhouzaihang/flutter_hand_tracking_plugin) for flutter. But need to change in facemesh solution.

**Comment by AryanSethi** [comment]
Thanks @sgowroji 
I'll try the code and reopen the issue if I get struck somewhere.

**Comment by PeterTF656** [comment]
@AryanSethi Let's keep in touch as I am also trying to implement this model into flutter. Also, I found out that google ARCORE has facemesh included in argumented face, but that's a whole new story

**Comment by AryanSethi** [comment]
@PeterTF656 sure thing !!
I'll get back to you if I find anything and you do the same. 😄

**Comment by PeterTF656** [comment]
@AryanSethi I just found out a [repo](https://github.com/CariusLars/ar_flutter_plugin) that implement arcore as a package for both ios and android platform. I'm thinking maybe we can use the argumented face for the face mesh function. I tested both tflite facemesh model and argumented face, and clearly, argumented face is better in almost every aspect, especially in performance.

**Comment by AryanSethi** [comment]
Heyyy !!
Thanks for the information @PeterTF656 
I'll checkout this repo too. 😄

**Comment by JaeHeee** [comment]
@AryanSethi 

I hope this helps :)
https://github.com/JaeHeee/FlutterWithMediaPipe

**Comment by AryanSethi** [comment]
@JaeHeee my goodness, route to heaven.
Thanks alot !!

**Comment by AmrAbdelghany** [comment]
Hello everyone, I am trying to develop an app with flutter that applies face filters and wanted to use the face mesh from mediapipe, any ideas on how can I do so? really appreciate your help

**Comment by AryanSethi** [comment]
@AmrAbdelghany @prakashsrv you can use this 
https://github.com/JaeHeee/FlutterWithMediaPipe

**Comment by kuaashish** [comment]
@AryanSethi,

We will be supporting the flutter soon and work is in our roadmap. For now, We are towards available the support Asap possible from our end. Thank you
