### ISSUE TITLE
Problems with Ubuntu and HelloWorld Tutorial

### ISSUE THREAD

**Issue by GMCristiano** [google/mediapipe#1403]
After following the Installing on Debian and Ubuntu from here https://google.github.io/mediapipe/getting_started/install.html
1º Follow the official Bazel documentation to install Bazel 3.4 or higher.
2º Checkout git MediaPipe repository.
3. Run setup_opencv.sh to automatically build OpenCV from source and modify MediaPipe’s OpenCV config.
4. Run the Hello World! in C++ example.

Ubuntu 20.04 clean install
Bazel 3.7.2

After this error i tried to install python 3.7, six and numpy with Apt but i think something is still missing

cristiano@zzz:~/mediapipe$ bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
INFO: Repository local_execution_config_python instantiated at:
  /home/cristiano/mediapipe/WORKSPACE:387:13: in <toplevel>
  /home/cristiano/.cache/bazel/_bazel_cristiano/06516db6b1962d091238ba1c8aae2c74/external/org_tensorflow/tensorflow/workspace.bzl:74:20: in tf_workspace
  /home/cristiano/.cache/bazel/_bazel_cristiano/06516db6b1962d091238ba1c8aae2c74/external/org_tensorflow/tensorflow/workspace.bzl:90:27: in tf_repositories
  /home/cristiano/.cache/bazel/_bazel_cristiano/06516db6b1962d091238ba1c8aae2c74/external/org_tensorflow/third_party/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  /home/cristiano/.cache/bazel/_bazel_cristiano/06516db6b1962d091238ba1c8aae2c74/external/org_tensorflow/third_party/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  /home/cristiano/.cache/bazel/_bazel_cristiano/06516db6b1962d091238ba1c8aae2c74/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "/home/cristiano/.cache/bazel/_bazel_cristiano/06516db6b1962d091238ba1c8aae2c74/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 39, in _create_local_python_repository
		numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
	File "/home/cristiano/.cache/bazel/_bazel_cristiano/06516db6b1962d091238ba1c8aae2c74/external/org_tensorflow/third_party/py/python_configure.bzl", line 187, column 19, in _get_numpy_include
		return execute(
	File "/home/cristiano/.cache/bazel/_bazel_cristiano/06516db6b1962d091238ba1c8aae2c74/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
		fail(
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Elapsed time: 0.741s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)

**Comment by jiuqiant** [comment]
Please read https://github.com/google/mediapipe/blob/master/docs/getting_started/troubleshooting.md#missing-necessary-python-packages

**Comment by sgowroji** [comment]
Hi @GMCristiano, Did you followed the steps mentioned in this [comment](https://github.com/google/mediapipe/issues/1403#issuecomment-748289160).

**Comment by sgowroji** [comment]
Hi @GMCristiano, Could you please respond to my above [comment](https://github.com/google/mediapipe/issues/1403#issuecomment-849440659). Thanks

**Comment by GMCristiano** [comment]
> Hi @GMCristiano, Did you followed the steps mentioned in this [comment](https://github.com/google/mediapipe/issues/1403#issuecomment-748289160).

yes. it worked some while ago.

but you should updated all your tutorials or make something more develop friendly.

**Comment by sgowroji** [comment]
Thank you for your input  @GMCristiano, definitely we will add the  problems in our documentation.
