### ISSUE TITLE
MediaPipe in Python: Hands

### ISSUE THREAD

**Issue by LYKlyk** [google/mediapipe#1405]
from mediapipe.python._framework_bindings import resource_util
ImportError: DLL load failed: 找不到指定的模块。

**Comment by jiuqiant** [comment]
Can you provide more information:
- How do you get the mediapipe python package?
- How do you run it?
- Do you run it in the source dir of mediapipe?

**Comment by LYKlyk** [comment]
**OS: Window10  + Anaconda3 + python=3.6**
**command:** pip install numpy==1.19.3
                  pip install mediapipe
**run command:**  python demo.py  [https://github.com/nishanth6474/mediapipe]
**Error:**
Traceback (most recent call last):
  File "F:/Mediapipe/mediapipe-main/demo.py", line 2, in <module>
    import mediapipe as mp
  File "D:\Anaconda\envs\mediapipe\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "D:\Anaconda\envs\mediapipe\lib\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: DLL load failed: 找不到指定的模块。


Thank you for your support!!!

**Comment by jiuqiant** [comment]
I clone your repo and run demo.py in an Anaconda Powershell Prompt on Windows 10. I can pass the module loading stage. The following issue is caused by the hardcoded file path:

```
(base) PS C:\Users\T\test\mediapipe>  C://Users//T//AppData//Local//Programs//Python//Python36//python.exe demo.py

Traceback (most recent call last):
File "demo.py", line 19, in <module>                                                                                     
results = hands.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))                                                    
cv2.error: OpenCV(3.4.11) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-w3j3m7zq\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'                                                                                                                                                               
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.       
```

**Comment by jiuqiant** [comment]
I clone your repo and run demo.py in an Anaconda Powershell Prompt on Windows 10. I can pass the module loading stage. The following issue is caused by the hardcoded file path:

```
(base) C:\Users\T>python -m pip install mediapipe
Collecting mediapipe
  Downloading mediapipe-0.8.2-cp38-cp38-win_amd64.whl (51.1 MB)
     |████████████████████████████████| 51.1 MB 160 kB/s
Collecting opencv-python
  Downloading opencv_python-4.4.0.46-cp38-cp38-win_amd64.whl (33.5 MB)
     |████████████████████████████████| 33.5 MB 1.3 MB/s
Requirement already satisfied: six in c:\users\t\appdata\roaming\python\python38\site-packages (from mediapipe) (1.15.0)
Collecting absl-py
  Downloading absl_py-0.11.0-py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 2.2 MB/s
Collecting numpy==1.19.3
  Downloading numpy-1.19.3-cp38-cp38-win_amd64.whl (13.3 MB)
     |████████████████████████████████| 13.3 MB 1.1 MB/s
Requirement already satisfied: wheel in c:\users\t\anaconda3\lib\site-packages (from mediapipe) (0.35.1)
Collecting dataclasses
  Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting protobuf>=3.11.4
  Downloading protobuf-3.14.0-py2.py3-none-any.whl (173 kB)
     |████████████████████████████████| 173 kB 1.1 MB/s
Installing collected packages: numpy, opencv-python, absl-py, dataclasses, protobuf, mediapipe
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2
Successfully installed absl-py-0.11.0 dataclasses-0.6 mediapipe-0.8.2 numpy-1.19.3 opencv-python-4.4.0.46 protobuf-3.14.0

(base) C:\Users\T>cd test\mediapipe

(base) C:\Users\T\test\mediapipe>conda info --envs
# conda environments:
#
base                  *  C:\Users\T\anaconda3

(base) C:\Users\T\test\mediapipe>python demo.py
Traceback (most recent call last):
  File "demo.py", line 19, in <module>
    results = hands.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-h4wtvo23\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

**Comment by LYKlyk** [comment]
(MP) C:\Users\sd_li>pip install mediapipe
Collecting mediapipe
  Downloading mediapipe-0.8.2-cp38-cp38-win_amd64.whl (51.1 MB)
     |████████████████████████████████| 51.1 MB 6.4 MB/s
Requirement already satisfied: wheel in d:\anaconda\envs\mp\lib\site-packages (from mediapipe) (0.36.2)
Collecting numpy==1.19.3
  Downloading numpy-1.19.3-cp38-cp38-win_amd64.whl (13.3 MB)
     |████████████████████████████████| 13.3 MB 6.4 MB/s
Collecting protobuf>=3.11.4
  Downloading protobuf-3.14.0-py2.py3-none-any.whl (173 kB)
     |████████████████████████████████| 173 kB 6.4 MB/s
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting absl-py
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
Collecting dataclasses
  Using cached dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting opencv-python
  Downloading opencv_python-4.4.0.46-cp38-cp38-win_amd64.whl (33.5 MB)
     |████████████████████████████████| 33.5 MB 6.8 MB/s
Installing collected packages: six, numpy, protobuf, opencv-python, dataclasses, absl-py, mediapipe
Successfully installed absl-py-0.11.0 dataclasses-0.6 mediapipe-0.8.2 numpy-1.19.3 opencv-python-4.4.0.46 protobuf-3.14.0 six-1.15.0


(MP) F:\Mediapipe\mediapipe-main>python demo.py
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import mediapipe as mp
  File "D:\Anaconda\envs\MP\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "D:\Anaconda\envs\MP\lib\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: DLL load failed while importing _framework_bindings: 找不到指定的模块。

**Comment by RyanStark223232** [comment]
I ran into the same problem. I somehow solved it by installing the newest version of Miniconda and doing "conda update --all"

**Comment by gmt710** [comment]
Met the same problem, try updating but the error also occurred.

**Comment by gmt710** [comment]
Ubuntu is ok.

**Comment by JerryloveEmily** [comment]
> (MP) C:\Users\sd_li>pip install mediapipe
> Collecting mediapipe
> Downloading mediapipe-0.8.2-cp38-cp38-win_amd64.whl (51.1 MB)
> |████████████████████████████████| 51.1 MB 6.4 MB/s
> Requirement already satisfied: wheel in d:\anaconda\envs\mp\lib\site-packages (from mediapipe) (0.36.2)
> Collecting numpy==1.19.3
> Downloading numpy-1.19.3-cp38-cp38-win_amd64.whl (13.3 MB)
> |████████████████████████████████| 13.3 MB 6.4 MB/s
> Collecting protobuf>=3.11.4
> Downloading protobuf-3.14.0-py2.py3-none-any.whl (173 kB)
> |████████████████████████████████| 173 kB 6.4 MB/s
> Collecting six
> Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
> Collecting absl-py
> Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
> Collecting dataclasses
> Using cached dataclasses-0.6-py3-none-any.whl (14 kB)
> Collecting opencv-python
> Downloading opencv_python-4.4.0.46-cp38-cp38-win_amd64.whl (33.5 MB)
> |████████████████████████████████| 33.5 MB 6.8 MB/s
> Installing collected packages: six, numpy, protobuf, opencv-python, dataclasses, absl-py, mediapipe
> Successfully installed absl-py-0.11.0 dataclasses-0.6 mediapipe-0.8.2 numpy-1.19.3 opencv-python-4.4.0.46 protobuf-3.14.0 six-1.15.0
> 
> (MP) F:\Mediapipe\mediapipe-main>python demo.py
> Traceback (most recent call last):
> File "demo.py", line 2, in
> import mediapipe as mp
> File "D:\Anaconda\envs\MP\lib\site-packages\mediapipe__init__.py", line 16, in
> from mediapipe.python import *
> File "D:\Anaconda\envs\MP\lib\site-packages\mediapipe\python__init__.py", line 17, in
**> from mediapipe.python._framework_bindings import resource_util
> ImportError: DLL load failed while importing _framework_bindings: 找不到指定的模块。**

------------------------------------------------------------------------------------------------------------------------------
**Have you solved this problem and how? I've reinstalled mediapipe several times, and it's still the same for other versions.**

**Comment by jiuqiant** [comment]
Since I can't reproduce this issue, can you try http://www.dependencywalker.com/ to check which dlls the pyd tried to load?

**Comment by jiuqiant** [comment]
We are closing this issue as of now, Due to lack of activity on it.
