### ISSUE TITLE
why I can't run my code successfully if I enabled profiler?

### ISSUE THREAD

**Issue by carlwuuu** [google/mediapipe#1409]
I can run my code when there is no profiler config in my graph file(xx.pbtxt).But if I add 
profiler_config {
  trace_enabled: true
  enable_profiler: true
  trace_log_count:200
}
in the file,the code can not run successfully,it seems get stuck.The program saved only one trace log,I can only see graph view in this file,both chart-view and timeline-view is 0.
How can I solve the problem?

**Comment by sgowroji** [comment]
Hi @carlwuuu, Could you please share your issue status. If the issue still exists, Can you share the complete details of the issue with clear description. Thanks!

**Comment by sgowroji** [comment]
Hi @carlwuuu, Could you please respond to my above [comment](https://github.com/google/mediapipe/issues/1409#issuecomment-849435285). Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity on it.
