### ISSUE TITLE
Swift support for mediapipe

### ISSUE THREAD

**Issue by pzoltowski** [google/mediapipe#141]
I have been trying to figure out if it's possible to use mediapipe via Swift but noticed that in 

> https://github.com/google/mediapipe/blob/master/mediapipe/objc/MPPGraph.h

there is:

> #ifndef __cplusplus
> #error This header can only be included by an Objective-C++ file.
> #endif

so I guess currently the answer is no. Is there any particular technical reason why it's forbidden to load graph from swift, change some calculator parameters and start the graph execution? Swift would be great to do some mediapipe plumbing and UI related things while keeping ObjC++ for low-level calculator processing. AFAIK most simple data types as well as CVPixelBuffer are already bridged between Swift and ObjC. Just wanted to know your perspective before diving deep into the code base.

**Comment by alak** [comment]
Same here.

**Comment by mgyong** [comment]
@pzoltowski Sorry for late reply. MediaPipe native APIs C++ can support bindings to Swift
There is cpp interop which looks like:
https://github.com/pschuh/cpp_example/blob/master/Sources/CPPExample/include/example.h
This can be used like: https://github.com/pschuh/cpp_example/blob/master/Sources/Example/Basic.swift.
I expect that you'll need a swift wrapper over the c++ code for a while into the future.

**Comment by alak** [comment]
@mgyong can we expect an official wrapper ?

**Comment by mgyong** [comment]
@alak We don't have plans yet for official wrapper but if you do contributions for it. We are happy to do code reviews and consider your contributions

**Comment by szotp-lc** [comment]
I found some existing repo for MediaPipe Hands and with it, I wrote a wrapper around MPPGraph that can be used in Swift, Usage looks like this:
https://github.com/szotp-lc/HandTracker/blob/master/Example/Example/ViewController.swift#L21-L31

It only has bare minimum for hands detector, but could be customized for other applications.

**Comment by yujinnee** [comment]
> I found some existing repo for MediaPipe Hands and with it, I wrote a wrapper around MPPGraph that can be used in Swift, Usage looks like this: https://github.com/szotp-lc/HandTracker/blob/master/Example/Example/ViewController.swift#L21-L31
> 
> It only has bare minimum for hands detector, but could be customized for other applications.

hi @szotp-lc thank you for your contribution. I was really looking for swift handtracker framework with mediapipe 0.8.11. It seems your framework is recent version of MediaPipe, right? 
I used a framework from below link but it was low version of MediaPipe
 https://github.com/noppefoxwolf/HandTracker
 I really want to use your framework for my work and I already followed your readme, but there is a nil error on below line which get url in the setupGraph()
 let url = Bundle(for: MediaPipeGraph.self).url(forResource: "hand_tracking_mobile_gpu", withExtension: "binarypb")!
 Could you look it up for me??
I really need your help

**Comment by szotp-lc** [comment]
Yes it's using latest mediapipe. My project is configured to use [ hand_landmark_tracking_gpu](https://github.com/szotp-lc/HandTracker/blob/master/Sources/BUILD#L59) which is a more recent version of the graph (it seems).

You seem to be using hand_tracking_mobile_gpu, from older commit maybe?

Anyway, you can also open `MediaPipeHands.framework` to check which files have been included.

**Comment by yujinnee** [comment]
@szotp-lc I really appreciate with your answer!
I cloned your example again. There was syntax error in below statement in  ViewControllers.swift
      `  let graph = try MediaPipeGraph(binaryGraphConfig: Data(contentsOf: url)) `
and changed it to 
` let graph = try MediaPipeGraph(graphConfig: Data(contentsOf: url))`
So I could run the app successfully .
But when app start, there is only a white screen with toggle switch turned on.(no camera video, no hand detection line)
When I turn off switch, camera video appears (no hand detection line) and when I turn on switch again video stop and nothing happened.
I can't figure it out the solution.
Could you fix it for me?

**Comment by yujinnee** [comment]
And I also want to know how can I get 21 HandLandmarks from output.handmarks

**Comment by szotp-lc** [comment]
The sample does not display output with lines etc. because hand_landmark_tracking_gpu does not produce it. But it should print number of hands detected.

From your questions I can see you don't really understand how mediapipe works, please take some time to learn, it's just not possible to use mediapipe if you don't understand it's insides a bit.

**Comment by Danilog123** [comment]
Hello @yujinnee and @szotp-lc, since you had more luck with building the app: Have you had problems with the Dependencies? Somehow I get the Error 'Framework not found Pods_Example'. Did you get the same Error and if so, how were you able to fix it?

How am I able to get the dependency?

Thank you in advance!

**Comment by szotp-lc** [comment]
@Danilog123 please ask ChatGPT about this, it should be able to help.

**Comment by yujinnee** [comment]
@Danilog123 
For that error I just deleted the file 'Pods_Example' from the Xcode left file explorer. I think it was because the xcode was misreferenced but I'm not sure. I just deleted it and successfully built it

**Comment by Danilog123** [comment]
Thank you @szotp-lc and @yujinnee I really appreciate your help!

I deleted 'Pods_Example' from the Xcode file explorer but this just resulted in another error: "error build: Undefined symbol: _OBJC_CLASS_$_MediaPipeGraph" and "error build: Undefined symbol: _OBJC_CLASS_$_MediaPipePacket". Is there something wrong with my depenecies or what else could it be? Should I maybe include 'MediaPipeHands.framework' in the 'Framework, libraries and Embedded Content' Tab?

And for ChatGPT: It wasn't able to help me.

Thank you very much for helping me out!
