### ISSUE TITLE
FaceMesh Android

### ISSUE THREAD

**Issue by GulderBone** [google/mediapipe#1410]
Is there any chance to get an example project code for FaceMesh Android (can't open the bazel one on windows)

**Comment by eknight7** [comment]
Hi, please see: https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu/BUILD and https://google.github.io/mediapipe/solutions/face_mesh#solution-apis.
