### ISSUE TITLE
How can I use Holistic JavaScript Solution API from node.js?

### ISSUE THREAD

**Issue by champierre** [google/mediapipe#1411]
I followed the installation instruction described in https://google.github.io/mediapipe/getting_started/javascript.html#ready-to-use-javascript-solutions.

I ran

```
npm install @mediapipe/holistic
```

and added

```
const holistic = require('@mediapipe/holistic');
```

to my node.js code, but I got the following error.

```
Module not found: Error: Can't resolve '@mediapipe/holistic' in <file name>
```

I confirmed that there are several files under node_modules/@mediapipe/holistic folder.

How can I use Holistic JavaScript Solution API from node.js?

**Comment by syanenko** [comment]
Hi,
did you find a solution for this issue ?
I have the same experience with '@mediapipe/camera_utils' and '@mediapipe/hands' and completely stacked.

Anyone, any help please !
Thanks in advance.

**Comment by dottodot** [comment]
Seems to be a problem with the npm packages, trying to use in React and get Module not found: Can't resolve '@mediapipe/camera_utils'

**Comment by dottodot** [comment]
Actually got it to work just needed to get to import path right i.e

```
import {
  drawConnectors,
  drawLandmarks,
} from '@mediapipe/drawing_utils/drawing_utils';
import { Camera } from '@mediapipe/camera_utils/camera_utils';
import { Pose } from '@mediapipe/pose/pose';
```

**Comment by champierre** [comment]
I replaced

```
const holistic = require('@mediapipe/holistic');
```

with

```
import { holistic } from '@mediapipe/holistic/holistic';
```

Instead of

```
Module not found: Error: Can't resolve '@mediapipe/holistic' in <file name>
```

now I got another error in the console window.

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

**Comment by dottodot** [comment]
what about 

```
const { Holistic } = require('@mediapipe/holistic/holistic');
```

**Comment by dottodot** [comment]
or 

```
import { Holistic } from '@mediapipe/holistic/holistic';
```

**Comment by syanenko** [comment]
Thank you, dottodot !

```
import { Camera } from '@mediapipe/camera_utils/camera_utils';
import { Hands  } from '@mediapipe/hands/hands';

```

works for me.

**Comment by champierre** [comment]
```
import { Holistic } from '@mediapipe/holistic/holistic';
```

gave the same error:

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

Next, I tried

```
const { Holistic } = require('@mediapipe/holistic/holistic');
```

and now I got

```
Uncaught TypeError: Holistic.setOptions is not a function
```

at

```
        Holistic.setOptions({
          upperBodyOnly: false,
          smoothLandmarks: true,
          minDetectionConfidence: 0.5,
          minTrackingConfidence: 0.5
        });
```

**Comment by syanenko** [comment]
It's strange - I tryed 

`
import { Holistic } from '@mediapipe/holistic/holistic';
`

and it works as well. 

You can check it in my [repository ](https://github.com/syanenko/shaderplay/blob/main/src/materials.js)

**Comment by anubhab-parallel-reality** [comment]
> Holistic.setOptions({
>           upperBodyOnly: false,
>           smoothLandmarks: true,
>           minDetectionConfidence: 0.5,
>           minTrackingConfidence: 0.5
>         });

If you look into the `holistic.js` file, actually it is a function
So, try using:
```
let holistic = Holistic()
holistic.setOptions({
          upperBodyOnly: false,
          smoothLandmarks: true,
          minDetectionConfidence: 0.5,
          minTrackingConfidence: 0.5
        });
```

**Comment by dmnsgn** [comment]
The npm packages don't have their "main" field set which prevents us to import the package from its root. Is there anywhere we can send a PR to fix this?

**Comment by ben-xD** [comment]
@dmnsgn I guess we have to wait for the JS libraries to be open sourced https://github.com/google/mediapipe/issues/1408

**Comment by syanenko** [comment]
> @dmnsgn I guess we have to wait for the JS libraries to be open sourced #1408

I suppose it will be this way:
`
while(true)
{
  console.log("Wating for source code ...");
}
`

**Comment by keepitsimple** [comment]
Up

**Comment by palnikhil** [comment]
Hey Can someone just give me the solution to write mediapipe pose in Nodejs. I am not able to figure out like how.

**Comment by berkon** [comment]
Still no solution for this?

**Comment by gungui98** [comment]
I emulated browser environment and successful run the model, all thanks to the god ChatGPT 

``` js


const { JSDOM } = require('jsdom');

// Create a new jsdom instance
const dom = new JSDOM();

// Get a reference to the global window object
const window = dom.window;

// You can now use the window object to run browser-based code
// For example, you can create a new `navigator` object and
// use it to access information about the user's browser and device
const navigator = window.navigator;
global.navigator = navigator;
global.window = window;

// Load the MediaPipe library.
const mp = require('@mediapipe/pose');

// import fs library
const fs = require('fs');

// Load the video data.
// Replace 'path/to/video' with the actual path to your video file.
const videoData = fs.readFileSync('../data/videos/diff2.mp4');

// Create a MediaPipe Pose object.
const pose = new mp.Pose({
    locateFile: (file) => {
        return `https://cdn.jsdelivr.net/npm/@mediapipe/pose/${file}`;
    }
});
//
// // Set the options.
pose.setOptions({
    selfieMode: false,
    modelComplexity: 2,
    smoothLandmarks: true,
    enableSegmentation: false,
    smoothSegmentation: false,
    minDetectionConfidence: 0.5,
    minTrackingConfidence: 0.5,
    effect: 'background',
});

console.log("load model done");
```

**Comment by kuaashish** [comment]
Hello @champierre,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you!

**Comment by ZeroCho** [comment]
@vastava 
I can remove errors by adding
```
(global as any).document = dom.window.document;
(global as any).Element = dom.window.Element;
```
