### ISSUE TITLE
Background segmentation app using Deeplabv3 processing very slow

### ISSUE THREAD

**Issue by Gauraviiitian** [google/mediapipe#1415]
I've written custom preprocessing and postprocessing calculators to use deeplabv3 tflite model for background changing application and it's working but the problem is that the app is very slow even after using quantized tflite model. Can anyone suggest how can I work on speeding up the application? I'm using CPU inference, can this be cause of latency?

**Comment by eknight7** [comment]
Hi, Thank you for your question @Gauraviiitian .
To investigate latency, one way is to measure processing time per packet for each calculator. https://github.com/google/mediapipe/issues/460 discusses some ideas about this. Also you may use the tracing and profiling tools for the same: https://google.github.io/mediapipe/tools/tracing_and_profiling.html.

Please feel free to share your findings and ask more questions. However, it would be helpful if you could share your graph, platform on which you are building, and some measurements using the tools as mentioned above. Thank you!

**Comment by eknight7** [comment]
Hi @Gauraviiitian, since the issue has been inactive, we will close it. Please feel free to re-open this issue for further questions. Thank you!
