### ISSUE TITLE
Do you plan to mention "contributors" in future releases?

### ISSUE THREAD

**Issue by lisbravo** [google/mediapipe#142]
I noticed that many of the new features in the latest release are kind of the same there I have made public a few weeks before.  Even though you may have a different, cleaner implementation, the concepts are pretty much the same. 
Not  expecting to be paid or a parade :D, but a simple mention  will suffice, otherwise I don't feel to have any motivation to keep sharing the ideas there I'm working on
Off course I know you are working heavily on this framework and this kind of things may slip trough.

**Comment by lisbravo** [comment]
by the way, thanks a lot for the new GPU acceleration for desktop!!!

**Comment by mgyong** [comment]
@lisbravo We have a [contribution policy](https://github.com/google/mediapipe/blob/master/CONTRIBUTING.md) for the project. We welcome your contributions to our project based on the contribution policy as well as email feedback on the project. I don't recall getting an email from you to mgyong at google dot com based on our previous exchange on [issue 119](https://github.com/google/mediapipe/issues/119). A few other users have mentioned in the issue that it would be great to get your code example for showing desktop hand landmarks.  It would be great if you could clean up your code and maybe contribute that as an example to MediaPipe

**Comment by lisbravo** [comment]
So, I upload many desktop versions of previous mobile only examples to my fork, which I see you are following, and they coincidentally appear a few weeks latter into a release?

Its ok, I still think this is a good framework

**Comment by mgyong** [comment]
@lisbravo In this case, it is purely coincidental and not related to your desktop versions. We have not actually seen your fork. Could you share you link to the fork? Our desktop examples were planned 2 months ago given that we had quite a [few requests](https://github.com/google/mediapipe/issues/56) for desktop examples
