### ISSUE TITLE
Face Mesh - no z coordinate

### ISSUE THREAD

**Issue by LucaJunge** [google/mediapipe#1422]
Hello,

I got the javascript example for the face mesh to work, but inside of the landmarks are only x and y coordinates (and a visibility that is always "undefined")

How can i get the z coordinate for the landmarks?

**Comment by sunrisemoment** [comment]
Hello, Same problem here.
"multiFaceLandmarks" contains 2D coordinates array. There is no z coordinate value from onResults callback in FaceMesh javascript.

@mediapipe/face_mesh
0: {x: 0.6552373170852661, y: 0.7516689300537109, visibility: undefined}
1: {x: 0.6646785140037537, y: 0.6616325974464417, visibility: undefined}
2: {x: 0.6567336916923523, y: 0.698333203792572, visibility: undefined}

But @tensorflow-models/face-landmarks-detection@0.0.1/dist/face-landmarks-detection.js landmarks contains z coordinates.
How can I get z coordinate from mediapipe-facemesh?

**Comment by delebash** [comment]
I think this is a problem with the javascript version as mediapipe hands has the same problem. https://github.com/google/mediapipe/issues/1429.  The python version does produce the z axis.

**Comment by aarushi-mittal** [comment]
Any updates on the coordinate availability yet ?

**Comment by ivan-grishchenko** [comment]
Hi @LucaJunge,

You are right, Z coordinate is predicted by the model but need to be propagated to the API.
@mhays-google Could you please provide an estimation on that?

**Comment by lostfictions** [comment]
hey there, just saw [v0.8.6](https://github.com/google/mediapipe/releases/tag/v0.8.6) added 3D landmarks for Pose and Holistic -- any updates for this issue?

**Comment by mhays-google** [comment]
This should be a thing now.  I demo the 3d landmarks in Pose, but there are
some issues making the demo work well for holistic (namely, the face and
hands landmarks aren't real 3d coordinates).  But in both solutions, the
landmarks are there and are exposed in the results as poseWorldLandmarks.

**Comment by sgowroji** [comment]
Hi @LucaJunge, Did you get a chance to go through the above [comment](https://github.com/google/mediapipe/issues/1422#issuecomment-875889141). Thanks!
