### ISSUE TITLE
Can't include landmark.pb.h, trying to get face and iris landmarks

### ISSUE THREAD

**Issue by overdescriptive** [google/mediapipe#1428]
I want to create a small app that uses the direction of where the user is looking, for that I decided to use the iris demo and edit the main `demo_run_graph_main.cc`, I am trying to get `"face_landmarks_with_iris"` out.
I can't read the `mediapipe::NormalizedLandmarkList` without including the landmark.pb.h, however, it doesn't work even after adding `"//mediapipe/framework/formats:landmark_cc_proto",` to the BAZEL build, so I am pretty lost.

Also would love to just use python for that (streaming the video in and getting the iris and face landmarks out)
Would appreciate all the help.

```bazel build --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/iris_tracking:iris_tracking_cpu ```

```
mediapipe/examples/desktop/demo_run_graph_main.cc:28:10: error: expected "FILENAME" or <FILENAME>
#include "mediapipe/framework/formats/landmark.pb.h
         ^
1 error generated.
Target //mediapipe/examples/desktop/iris_tracking:iris_tracking_cpu failed to build
INFO: Elapsed time: 4.709s, Critical Path: 4.56s
INFO: 130 processes: 129 internal, 1 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

```
cc_library(
    name = "demo_run_graph_main",
    srcs = ["demo_run_graph_main.cc"],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/formats:landmark_cc_proto",
        "//mediapipe/framework/formats:image_frame",
        "//mediapipe/framework/formats:image_frame_opencv",
        "//mediapipe/framework/port:commandlineflags",
        "//mediapipe/framework/port:file_helpers",
        "//mediapipe/framework/port:opencv_highgui",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:opencv_video",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
    ],
)
```

**Comment by johnboiles** [comment]
Running into something similar. How did you solve it?
