### ISSUE TITLE
z-axis  is not coming as output in hand's 21 keypoints( wasm javascript API)

### ISSUE THREAD

**Issue by vasanthhr** [google/mediapipe#1429]
Can you please guide how we can get the z-axis along with X and Y in hand's 21 keypoints from wasm Javascript API.

Link: https://google.github.io/mediapipe/solutions/hands.html#javascript-solution-api

We can see only X and Y with visibility in 21 keypoints, please find the attached screenshot.

![image](https://user-images.githubusercontent.com/20619142/103076036-cf4ad480-459a-11eb-809a-8b11be3f3e5a.png)

**Comment by yuccai** [comment]
Also related to these similar issues : #1392 and #1417

**Comment by ivan-grishchenko** [comment]
Hi @vasanthhr 

You are right, it's not in the API yet, although the model predicts them.
@fanzhanggoogle @mhays-google Could you please provide some estimation on when it can be done?
In the meantime, @vasanthhr you can try Python API that returns Z to check how it looks like

**Comment by sgowroji** [comment]
Hi @vasanthhr, Have you tried with Python API as mentioned in the above [comment](https://github.com/google/mediapipe/issues/1429#issuecomment-797165324). Thanks

**Comment by sgowroji** [comment]
Hi @vasanthhr, Could you please respond to my above [comment](https://github.com/google/mediapipe/issues/1429#issuecomment-851844441).  Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity. Please feel free to reopen if you have any relevant update on the above. Thanks.
