### ISSUE TITLE
“CameraXPreviewHelper.startCamera” error:java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/camera/core/CameraX$LensFacing;

### ISSUE THREAD

**Issue by DandyLorenz** [google/mediapipe#1431]
when I use mediapipe version  0.8.2 ,build hand_tracking_aar for android,I used a demo that someone else can compile APK successfully.but If I replace it with my AAR, it will prompt error,Hope to get help :
 java.lang.NoClassDefFoundError: **Failed resolution of: Landroidx/camera/core/CameraX$LensFacing;**
        at com.google.mediapipe.components.**CameraXPreviewHelper.startCamera(CameraXPreviewHelper.java:47)**
        at com.ruggear.thirdhandtracking.**ThirdMainActivity.startCamera(ThirdMainActivity.java:211)**
        at com.ruggear.thirdhandtracking.**ThirdMainActivity.onResume(ThirdMainActivity.java:149)**.

**some code with this:**
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(getContentViewLayoutResId());

        try {
            applicationInfo =
                    getPackageManager().getApplicationInfo(getPackageName(), PackageManager.GET_META_DATA);
        } catch (PackageManager.NameNotFoundException e) {
            Log.e(TAG, "Cannot find application info: " + e);
        }

        previewDisplayView = new SurfaceView(this);
        setupPreviewDisplayView();

        // Initialize asset manager so that MediaPipe native libraries can access the app assets, e.g.,
        // binary graphs.
        AndroidAssetUtil.initializeNativeAssetManager(this);
        eglManager = new EglManager(null);
 
        processor =
                new FrameProcessor(
                        this,
                        eglManager.getNativeContext(),
                        “hand_tracking_mobile_gpu.binarypb”,
                        “input_video”,
                      “output_video”);
        processor
                .getVideoSurfaceOutput()
                .setFlipY(true);//applicationInfo.metaData.getBoolean("flipFramesVertically", FLIP_FRAMES_VERTICALLY)

        AndroidPacketCreator packetCreator = processor.getPacketCreator();
        Map<String, Packet> inputSidePackets = new HashMap<>();
        inputSidePackets.put(INPUT_NUM_HANDS_SIDE_PACKET_NAME, packetCreator.createInt32(NUM_HANDS));
        processor.setInputSidePackets(inputSidePackets);

      processor.addPacketCallback(
                "hand_presence",
                (packet) -> {
                    Boolean handPresence = PacketGetter.getBool(packet);
                    if (!handPresence) {
                        Log.d(
                                TAG,
                                "[TS:" + packet.getTimestamp() + "] Hand presence is false, no hands detected.");
                    }
                });

        processor.addPacketCallback(
                "hand_landmarks",
                (packet) -> {
                    byte[] landmarksRaw = PacketGetter.getProtoBytes(packet);
                    try {
                        LandmarkProto.NormalizedLandmarkList landmarks = LandmarkProto.NormalizedLandmarkList.parseFrom(landmarksRaw);
                        if (landmarks == null) {
                            Log.d(TAG, "[TS:" + packet.getTimestamp() + "] No hand landmarks.");
                            return;
                        }
                        // Note: If hand_presence is false, these landmarks are useless.
                        Log.d(
                                TAG,
                                "[TS:"
                                        + packet.getTimestamp()
                                        + "] #Landmarks for hand: "
                                        + landmarks.getLandmarkCount());
                        Log.d(TAG, getLandmarksDebugString(landmarks));
                    } catch (InvalidProtocolBufferException e) {
                        Log.e(TAG, "出错了Couldn't Exception received - " + e);
                        return;
                    }
                });

        PermissionHelper.checkAndRequestCameraPermissions(this);
    }

**Comment by duy-maimanh** [comment]
Hey @DandyLorenz 
Can you share gradle. May be you used older camerax_version.
Mediapipe support cameraX version 1.0.0-beta10 since 0.7.12. But AAR document example use 1.0.0-alpha06

**Comment by DandyLorenz** [comment]
> Hey @DandyLorenz
> Can you share gradle. Maybe you used older camerax_version.
> Mediapipe support cameraX version 1.0.0-beta10 since 0.7.12. But AAR document example use 1.0.0-alpha06

thanks.I use your config Solved the problem.good luck！

**Comment by DandyLorenz** [comment]
> Hey @DandyLorenz
> Can you share gradle. Maybe you used older camerax_version.
> Mediapipe support cameraX version 1.0.0-beta10 since 0.7.12. But AAR document example use 1.0.0-alpha06
Thank you again, let me feel the enthusiasm of open source.
This is the complete dependency that needs to be noted(camera-lifecycle):

    **implementation "androidx.camera:camera-lifecycle:$camerax_version"
    def camerax_version = "1.0.0-alpha10"
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"
    implementation "androidx.camera:camera-lifecycle:$camerax_version"**

**Comment by vvalerian** [comment]
> Hey @DandyLorenz
> Can you share gradle. Maybe you used older camerax_version.
> Mediapipe support cameraX version 1.0.0-beta10 since 0.7.12. But AAR document example use 1.0.0-alpha06

Hi duy-maimanh, do you have any code sample/snippet working with 1.0.0-betaXX

**Comment by DandyLorenz** [comment]
Yes, I have successfully compiled Android applications for edge detection and face detection.If you are experienced in this aspect, please help me solve this problem：https://github.com/google/mediapipe/issues/1450
Humor:where are you from？

**Comment by duy-maimanh** [comment]
> > Hey @DandyLorenz
> > Can you share gradle. Maybe you used older camerax_version.
> > Mediapipe support cameraX version 1.0.0-beta10 since 0.7.12. But AAR document example use 1.0.0-alpha06
> 
> Hi duy-maimanh, do you have any code sample/snippet working with 1.0.0-betaXX

Update your project to latest version. It has supported cameraX 1.0.0-beta 10.

**Comment by DandyLorenz** [comment]
Complete gradle：
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.ruggear.remotehandtracking"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar","*.aar",])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    // MediaPipe deps
    implementation 'com.google.flogger:flogger:0.3.1'
    implementation 'com.google.flogger:flogger-system-backend:0.3.1'
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
    implementation 'com.google.guava:guava:27.0.1-android'
    implementation 'com.google.guava:guava:27.0.1-android'
    //implementation 'com.google.protobuf:protobuf-lite:3.0.0'
    implementation 'com.google.protobuf:protobuf-java:3.11.4'

    def camerax_version = "1.0.0-rc01"//1.0.0-alpha06 1.0.0-alpha10 1.0.0-rc01
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"
```
    implementation "androidx.camera:camera-lifecycle:$camerax_version"
}
