### ISSUE TITLE
build aar for android,I can't find  Correct file（such as:face_detection_front.tflite or palm_detection.tflite ） in "mediapipe/models" path

### ISSUE THREAD

**Issue by DandyLorenz** [google/mediapipe#1432]
when I build mediapipe version 0.8.2 AAR for android,I can't find face_detection_front.tflite, face_detection_front_labelmap.txt and palm_detection.tflite .
The official link is as follows: https://google.github.io/mediapipe/getting_started/android_archive_library.html

The guidance in the document can be found in the following path:
mediapipe/models/face_detection_front.tflite 
mediapipe/models/face_detection_front_labelmap.txt 
mediapipe/models/palm_detection.tflite 

 I use this command build succeed AAR:
bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a \ //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar
bazel build -c opt mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu_binary_graph
**but,**when,I can't find Under the "/mediapipe/models/" path
Question 1：Are I missing some instructions when I build？It causes that the corresponding tflite file cannot be generated in the "models" path
Question 2：I can find files with the same name in the "/mediapipe/mediapipe/modules/face_detection" path and "/mediapipe/mediapipe/modules/palm_detection" path , but it is not an updated file or It's not the latest file, and the path is not under "models". Can I use them correctly in my project?

**Comment by duy-maimanh** [comment]
@DandyLorenz 
Put it into src/main/assets. Same folder with binarypb file.
Read more at here https://google.github.io/mediapipe/getting_started/android_archive_library.html

**Comment by DandyLorenz** [comment]
> @DandyLorenz
> Put it into src/main/assets. Same folder with binarypb file.
> Read more at here https://google.github.io/mediapipe/getting_started/android_archive_library.html

I have read your answer carefully, thank you. Can you help me solve another problem? He has troubled me for a long time. Thank you very much
