### ISSUE TITLE
Instant motion tracking camera pose retrival

### ISSUE THREAD

**Issue by TheBricktop** [google/mediapipe#1435]
Is there a way to retrieve pose of the camera from instant motion tracking?

**Comment by mcclanahoochie** [comment]
I think the [MotionAnalysisCalculator](https://github.com/google/mediapipe/blob/2b58cceec9953f0d97059934f0de85dd60adbe9b/mediapipe/calculators/video/motion_analysis_calculator.cc) has that info, used here https://github.com/google/mediapipe/blob/master/mediapipe/graphs/tracking/subgraphs/box_tracking_gpu.pbtxt

**Comment by atul109** [comment]
![Screenshot 2021-02-15 at 1 08 10 PM](https://user-images.githubusercontent.com/16425237/107919402-4300d080-6f91-11eb-9da1-9b84f4383b0b.png)

I am trying to extract Matrices data for the same purpose, I couldn't find which proto to add to parse the data correctly.
The calculator of instant tracking has the output in **TimedModelMatrixProtoList** but it is not defined anywhere in framework/formats
`processor.addPacketCallback(
                                        "tracked_anchor_data",
                                        (packet) -> {
                                               byte[] data = PacketGetter.getProtoBytes(packet); //Some data is receiving of length 70, so it might contain a 4x4 matrix of float
                                                //PacketGetter.getProtoVector(packet, MatrixDataProto.MatrixData.parser()); //crashes
                                                //PacketGetter.getMatrixData(packet); //crashes
                                        });`
