### ISSUE TITLE
Python bindings undefined symbol on Raspberry Pi 4

### ISSUE THREAD

**Issue by vdlluca** [google/mediapipe#1437]
Hello

I followed the installation guide on https://google.github.io/mediapipe/getting_started/python.html on my Raspberry Pi 4
After trying to import mediapipe in python I get the error:
```
>>> import mediapipe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/usr/local/lib/python3.7/dist-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: /usr/local/lib/python3.7/dist-packages/mediapipe/python/_framework_bindings.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: _ZN3ruy14Kernel8bitNeonERKNS_16KernelParams8bitILi4ELi2EEE
```
I found it's a function from ruy, a matrix multiplication library used by Tensorflow.
Anyone knows how to resolve this issue?

**Comment by jiuqiant** [comment]
https://google.github.io/mediapipe/getting_started/python.html points to https://github.com/jiuqiant/mediapipe_python_aarch64 for the raspberry pi users.

In https://github.com/jiuqiant/mediapipe_python_aarch64/blob/main/README.md, I bypass a similar issue by adding `"ENABLE_NEON": "OFF"`.

```
diff --git a/third_party/BUILD b/third_party/BUILD
index ef408e4..51e1104 100644
--- a/third_party/BUILD
+++ b/third_party/BUILD
@@ -110,6 +104,8 @@ cmake_external(
   "WITH_ITT": "OFF",
   "WITH_JASPER": "OFF",
   "WITH_WEBP": "OFF",
+   "ENABLE_NEON": "OFF",
+   "WITH_TENGINE": "OFF",
```

Do you try this as well?

**Comment by vdlluca** [comment]
I thought I did everything in the guide, but now I'm not sure if I remember doing this step. I don't have much time to try it, so I will close the issue. In a few weeks, I will have more time and I will reopen this issue in case it still persists. Thank you for your reply!

**Comment by Projudah** [comment]
Hey, i'm currently facing the same issue and I have `ENABLE_NEON: "OFF"` and I still have the same error, after I changed the third_party/BUILD , I re ran `gen_protos` and then `bdist_wheel` but I'm getting the same error

I'm not sure if I should just open a new issue, since this is so similar

**Comment by XMasterNinni** [comment]
Facing the same issue on a Raspberry Pi 4. I've compiled it using the aforementioned aarch64 guide and have `ENABLE_NEON: "OFF"` set

**Comment by svebert** [comment]
Hi I have the same problem.
System Odroid XU4. Ubuntu Mate 4.14
I used this ["manual"](https://github.com/jiuqiant/mediapipe_python_aarch64)
After having a lot of trouble, building bazel itsself for Odroid and afterwards protoc, I was able to run step 7 (build)
`~/mediapipe$ python3 setup.py gen_protos && python3 setup.py bdist_wheel`
But i am still not able to install and use mediapipe on odriod with python3.6

The state steps
```
~$ python3 -m pip install cython
~$ python3 -m pip install numpy
~$ python3 -m pip install pillow
~$ python3 -m pip install mediapipe/dist/mediapipe-0.8-cp38-cp38-linux_aarch64.whl
```
do not work as expected: numpy and pillow is ok. But cython fails. Don't even know, if I really need it?
the step to install the .whl-file also fails for me in the step of 
`building wheel for opencv-contrib-python`
So I did run `~$ python3 -m pip install mediapipe/dist/mediapipe-0.8-cp38-cp38-linux_aarch64.whl --no-deps`
This results in the error stated above, when trying to import mediapipe.

One hint: Building protoc was successful, but `make test` was not. Maybe there is still a problem?

**Comment by jiuqiant** [comment]
The issue "undefined symbol: _ZN3ruy23Pack8bitRowMajorForNeonEPKhiiiiiiPaiiPiii" is a TFLite issue. TFLite doesn't support ARM native build with Bazel: https://github.com/tensorflow/tensorflow/issues/42471#issuecomment-696529766. Feel like there is not too much we can do for this issue.

**Comment by johncblacker** [comment]
So, that begs the question: what do you use to build mediapipe?  Searching around the net, people have been able to build mediapipe on rPi that does not get the error.  In fact, I've used one of the images for rPi3 and it works, but it's an older image and I wanted to get the latest mediapipe version.  It would appear that somethings have changed in mediapipe since 0.8.4 that are causing this issue?  Some help would be greatly appreciated, since the rPi user community is growing.

**Comment by sgowroji** [comment]
Hi @johncblacker, Could you please open a new issue or a feature request w.r.t your above comment. As this [comment](https://github.com/google/mediapipe/issues/1437#issuecomment-847179027) address the above thread. Thanks!

**Comment by johncblacker** [comment]
I opened a feature request to officially support building mediapipe on raspberry pi 3 and 4

**Comment by yoyojacky** [comment]
I think that maybe caused by using 64bit OS ? seems like the 32bit version works fine~..
