### ISSUE TITLE
Multi Person?

### ISSUE THREAD

**Issue by HoiBunCa** [google/mediapipe#1442]
How to draw a skeleton on many people in a frame, do you support it?
Thanks very much

**Comment by jiuqiant** [comment]
I am sorry that it's not supported as-is. Detecting multiple persons requires modifying the graph.

**Comment by luminous33** [comment]
> I am sorry that it's not supported as-is. Detecting multiple persons requires modifying the graph.

How can i modify the graph??? I tried to change pose.py as hands.py(multi_hands). But the code is notworking. 
And also i did "Multi-Person Pose Estimation with Mediapipe" either.
