### ISSUE TITLE
Where is the "hand_present" now?

### ISSUE THREAD

**Issue by youto614** [google/mediapipe#1443]
It worked well in the old version when I used 
`        processor.addPacketCallback(
                OUTPUT_HAND_PRESENCE_STREAM_NAME,
                (packet) -> {
                    handPresence = PacketGetter.getBool(packet);
                    if (!handPresence) {
                        Log.d(TAG, "[TS:" + packet.getTimestamp() + "] Hand presence is false, no hands detected.");
                    }
                });`
but now it reports an error: 
`com.google.mediapipe.framework.MediaPipeException: unknown: ; Input Stream "hand_presence" for node with sorted index 1 does not have a corresponding output stream.`
Then I looked at the code in the file "hand_tracking_mobile.pbtxt".
`# Detects/tracks hand landmarks.
node {
  calculator: "HandLandmarkTrackingGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "NUM_HANDS:num_hands"
  output_stream: "LANDMARKS:hand_landmarks"
  output_stream: "HANDEDNESS:handedness"
  output_stream: "PALM_DETECTIONS:palm_detections"
  output_stream: "HAND_ROIS_FROM_LANDMARKS:hand_rects_from_landmarks"
  output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:hand_rects_from_palm_detections"
}`
Found that it seem there is no "hand_present" any more. So now how can I keep using this FLAG? 
Thanks for your help.

**Comment by DandyLorenz** [comment]
I have the same problem ，and I hope  help.I guess we used the latest version in 12 . 2020（December）.The official guidance document has not been updated。If anyone has solved the problem, please contact me and let me know. Thank you。my Email:1213126651@qq.com

**Comment by eknight7** [comment]
Hi, please see https://google.github.io/mediapipe/solutions/hands#output about the latest updates to the hand tracking API outputs.

**Comment by eknight7** [comment]
Hi @youto614 @DandyLorenz since this issue has been inactive, we will close it. Please feel free to reopen if you have further questions. Thank you!
