### ISSUE TITLE
Add iris to the holistic demo application for gaze tracking

### ISSUE THREAD

**Issue by delebash** [google/mediapipe#1444]
Since holistic tracks body pose, hand pose, and face mesh it would also be nice to be able to track a persons gaze.  Adding iris should do the trick.

**Comment by robzach** [comment]
[WebGazer.js](https://webgazer.cs.brown.edu/) may be of interest to you. (It uses some Media Pipe face tracking under the hood, I believe, though I don't think it uses Media Pipe's iris tracking.)

**Comment by delebash** [comment]
Thanks.  I saw that but it uses the tensoflow js version instead of the mediapipe js version and since iris would work I think it should be included.  If you look at https://ai.googleblog.com/2020/08/mediapipe-iris-real-time-iris-tracking.html.  The iris demo showcasing the animation of a character is exactly what I am looking for. In addition this demo is  using facemesh as well.  This is their statement

 
--
FaceMesh can be adopted to drive virtual avatars (middle). By additionally employing iris tracking (right), the avatar’s liveliness is significantly enhanced.

Thank you for checking.  Have a Happy New Year

**Comment by kostyaby** [comment]
+chuoling as an input for prioritizing this feature in future releases

**Comment by chuoling** [comment]
Update: We plan to improve the Face Mesh Solution API with an option to additionally compute and output iris landmarks, currently targeting a Q3 2021 release (likely Aug/Sept). We will make sure Holistic also gets the same improvement.

**Comment by sgowroji** [comment]
Hi @delebash, Please subscribe to our release notes for the new updates of Q3. Presently we are closing this issue now.
