### ISSUE TITLE
Error When Building Box Tracking on Windows

### ISSUE THREAD

**Issue by RitvikMandyam** [google/mediapipe#1445]
Hi!

I want to use the MediaPipe Box Tracking solution on Windows 10 Pro x64. I have VS 2019 and Bazel 3.7.2. I successfully built the Hello World and Iris examples. However, when I tried to build the Box Tracking example with
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://development//python.exe" mediapipe/examples/desktop/object_tracking:object_tracking_cpu`
I received this error:
`ERROR: C:/development/mediapipe/mediapipe/util/tracking/BUILD:603:11: C++ compilation of rule '//mediapipe/util/tracking:tracking' failed (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29333/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 53 argument(s) skipped)
mediapipe/util/tracking/tracking.cc(1656): error C3493: 'kSqProximity' cannot be implicitly captured because no default capture mode has been specified`

I will take a look at the code and see if I can work out how to fix this, but I would appreciate any help.
Thanks in advance.

**Comment by homuler** [comment]
I applied this patch and it worked.
```diff
diff --git a/mediapipe/util/tracking/box_tracker.cc b/mediapipe/util/tracking/box_tracker.cc
index 2111eac..7c5cd2b 100644
--- a/mediapipe/util/tracking/box_tracker.cc
+++ b/mediapipe/util/tracking/box_tracker.cc
@@ -667,7 +667,7 @@ bool BoxTracker::WaitForChunkFile(int id, int checkpoint,
       }
     }
 
-    usleep(wait_time_msec * 1000);
+    absl::SleepFor(absl::Milliseconds(wait_time_msec));
     total_wait_msec += wait_time_msec;
 
     struct stat tmp;
diff --git a/mediapipe/util/tracking/tracking.cc b/mediapipe/util/tracking/tracking.cc
index 72245c0..2a5d93f 100644
--- a/mediapipe/util/tracking/tracking.cc
+++ b/mediapipe/util/tracking/tracking.cc
@@ -1652,7 +1652,7 @@ bool MotionBox::GetVectorsAndWeights(
 
     vectors->push_back(&motion_vectors[k]);
 
-    auto is_close_to_test_vector = [test_vector](const Vector2_f v) -> bool {
+    auto is_close_to_test_vector = [test_vector, kSqProximity](const Vector2_f v) -> bool {
       return (v - test_vector.pos).Norm2() < kSqProximity;
     };
 ```

I created a PR( https://github.com/google/mediapipe/pull/1542 ) for the first diff.

**Comment by hadon** [comment]
Thanks for suggesting this patch.  It looks like perhaps we can improve portability for the Windows platform.  I'll mention contributor @jianingwei, who might have more insight.

**Comment by sgowroji** [comment]
As the PR fixed. We are closing this issue now.
