### ISSUE TITLE
sync project with BUILD files error

### ISSUE THREAD

**Issue by c1139676919** [google/mediapipe#1447]
**Here's the log after I clicked on ‘sync project with BUILD files’**

Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: /Users/mac/.bazel/bin/bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --

Command: git diff --name-status --no-renames 39309bedba255aee2a4f31b29b65609857698ada

Computing VCS working set...
  .aswb/.bazelproject (added)
  .aswb/.blaze/modules/.project-data-dir.iml (added)
  .aswb/.blaze/modules/.workspace.iml (added)
  .aswb/.idea/.gitignore (added)
  .aswb/.idea/.name (added)
  .aswb/.idea/codeStyles/Project.xml (added)
  .aswb/.idea/externalDependencies.xml (added)
  .aswb/.idea/libraries/java_compiler_362444fa.xml (added)
  .aswb/.idea/libraries/javac_9_181_r4173_1_362444fa.xml (added)
  .aswb/.idea/libraries/jdk_compiler_362444fa.xml (added)
  .aswb/.idea/libraries/libsticker_buffer_proto_lite_hjar_5795c596.xml (added)
  .aswb/.idea/misc.xml (added)
  .aswb/.idea/modules.xml (added)
  .aswb/.idea/runConfigurations.xml (added)
  .aswb/.idea/vcs.xml (added)
  WORKSPACE (modified)

Sync targets from working set:
  //:all

Sync targets from project view targets:
  //mediapipe/examples/android/...:all
  //mediapipe/java/...:all

Building Bazel targets...
Command: /Users/mac/.bazel/bin/bazel build --tool_tag=ijwb:AndroidStudio --keep_going --build_event_binary_file=/var/folders/81/zyx3b9z17jb880v9_w95tr140000gn/T/intellij-bep-6164ce6b-cd49-4aba-a358-a34e62a41c0c --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect "--override_repository=intellij_aspect=/Users/mac/Library/Application Support/AndroidStudio4.0/aswb/aspect" --output_groups=intellij-info-android,intellij-info-generic,intellij-info-java,intellij-resolve-android,intellij-resolve-java -- //:all //mediapipe/examples/android/...:all //mediapipe/java/...:all

Loading: 
Loading: 0 packages loaded
Analyzing: 82 targets (0 packages loaded, 0 targets configured)
Analyzing: 82 targets (5 packages loaded, 6646 targets configured)
Analyzing: 82 targets (5 packages loaded, 6646 targets configured)
Analyzing: 82 targets (6 packages loaded, 10928 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
Analyzing: 82 targets (6 packages loaded, 12038 targets configured)
INFO: Repository maven instantiated at:
  /Users/mac/AndroidStudioProjects/mediapipe/WORKSPACE:322:14: in <toplevel>
  /private/var/tmp/_bazel_mac/8a5b28cea5b7d9e65877ea407edc1f63/external/rules_jvm_external/defs.bzl:94:19: in maven_install
Repository rule coursier_fetch defined at:
  /private/var/tmp/_bazel_mac/8a5b28cea5b7d9e65877ea407edc1f63/external/rules_jvm_external/coursier.bzl:798:33: in <toplevel>
INFO: Repository 'maven' used the following cache hits instead of downloading the corresponding file.
 * Hash '6598d9277705ad8369a4f9c64217fbc31c19234f2cbcca9b1e5c4300a3abb317' for https://github.com/coursier/coursier/releases/download/v2.0.0-RC5-3/coursier.jar
If the definition of 'maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_mac/8a5b28cea5b7d9e65877ea407edc1f63/external/rules_jvm_external/coursier.bzl", line 544, column 13, in _coursier_fetch_impl
		fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/components/BUILD:65:16: //mediapipe/java/com/google/mediapipe/components:android_microphone_helper depends on @maven//:com_google_code_findbugs_jsr305 in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/components/BUILD:65:16: //mediapipe/java/com/google/mediapipe/components:android_microphone_helper depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:126:16: //mediapipe/java/com/google/mediapipe/framework:mediapipe_exception_android depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/third_party/BUILD:240:16: //third_party:androidx_legacy_support_v4 depends on @maven//:androidx_legacy_legacy_support_v4 in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/third_party/BUILD:226:16: //third_party:androidx_constraint_layout depends on @maven//:androidx_constraintlayout_constraintlayout in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/third_party/BUILD:268:16: //third_party:camerax_core depends on @maven//:androidx_camera_camera_core in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/third_party/BUILD:233:16: //third_party:androidx_core depends on @maven//:androidx_core_core in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/third_party/BUILD:212:16: //third_party:androidx_annotation depends on @maven//:androidx_annotation_annotation in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/third_party/BUILD:261:16: //third_party:camerax_camera2 depends on @maven//:androidx_camera_camera_camera2 in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/third_party/BUILD:219:16: //third_party:androidx_appcompat depends on @maven//:androidx_appcompat_appcompat in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/third_party/BUILD:275:16: //third_party:camerax_lifecycle depends on @maven//:androidx_camera_camera_lifecycle in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d/BUILD:111:16: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d:manifest_lib depends on @maven//:androidx_concurrent_concurrent_futures in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d/BUILD:111:16: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d:manifest_lib depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/third_party/BUILD:254:16: //third_party:androidx_recyclerview depends on @maven//:androidx_recyclerview_recyclerview in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:103:16: //mediapipe/java/com/google/mediapipe/framework:framework_proto_lite depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:73:16: //mediapipe/java/com/google/mediapipe/framework:android_core depends on @maven//:com_google_code_findbugs_jsr305 in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:73:16: //mediapipe/java/com/google/mediapipe/framework:android_core depends on @maven//:com_google_flogger_flogger in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:73:16: //mediapipe/java/com/google/mediapipe/framework:android_core depends on @maven//:com_google_flogger_flogger_system_backend in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:73:16: //mediapipe/java/com/google/mediapipe/framework:android_core depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:43:16: //mediapipe/java/com/google/mediapipe/framework:android_framework_no_proguard depends on @maven//:com_google_code_findbugs_jsr305 in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:43:16: //mediapipe/java/com/google/mediapipe/framework:android_framework_no_proguard depends on @maven//:com_google_flogger_flogger in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:43:16: //mediapipe/java/com/google/mediapipe/framework:android_framework_no_proguard depends on @maven//:com_google_flogger_flogger_system_backend in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:43:16: //mediapipe/java/com/google/mediapipe/framework:android_framework_no_proguard depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/glutil/BUILD:21:16: //mediapipe/java/com/google/mediapipe/glutil:glutil depends on @maven//:com_google_code_findbugs_jsr305 in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/glutil/BUILD:21:16: //mediapipe/java/com/google/mediapipe/glutil:glutil depends on @maven//:com_google_flogger_flogger in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/glutil/BUILD:21:16: //mediapipe/java/com/google/mediapipe/glutil:glutil depends on @maven//:com_google_flogger_flogger_system_backend in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/glutil/BUILD:21:16: //mediapipe/java/com/google/mediapipe/glutil:glutil depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/components/BUILD:42:16: //mediapipe/java/com/google/mediapipe/components:android_camerax_helper depends on @maven//:androidx_concurrent_concurrent_futures in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/components/BUILD:42:16: //mediapipe/java/com/google/mediapipe/components:android_camerax_helper depends on @maven//:androidx_lifecycle_lifecycle_common in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/components/BUILD:42:16: //mediapipe/java/com/google/mediapipe/components:android_camerax_helper depends on @maven//:com_google_code_findbugs_jsr305 in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/components/BUILD:42:16: //mediapipe/java/com/google/mediapipe/components:android_camerax_helper depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/components/BUILD:42:16: //mediapipe/java/com/google/mediapipe/components:android_camerax_helper depends on @maven//:com_google_guava_listenablefuture in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/components/BUILD:17:16: //mediapipe/java/com/google/mediapipe/components:android_components depends on @maven//:com_google_code_findbugs_jsr305 in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/java/com/google/mediapipe/components/BUILD:17:16: //mediapipe/java/com/google/mediapipe/components:android_components depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/BUILD:18:16: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:basic_lib depends on @maven//:androidx_concurrent_concurrent_futures in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/BUILD:18:16: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:basic_lib depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking/BUILD:24:16: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking_lib depends on @maven//:androidx_concurrent_concurrent_futures in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking/BUILD:24:16: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking_lib depends on @maven//:com_github_bumptech_glide_glide in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/mac/AndroidStudioProjects/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking/BUILD:24:16: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking_lib depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu:facemeshgpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:facedetectiongpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/java/com/google/mediapipe/components:android_camerax_helper': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d:manifest_lib': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:basic_lib': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/upperbodyposetrackinggpu:upperbodyposetrackinggpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/holistictrackinggpu:holistictrackinggpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/java/com/google/mediapipe/framework:android_framework_no_proguard': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/hairsegmentationgpu:hairsegmentationgpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/templatematchingcpu:templatematchingcpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu:objecttrackinggpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu:objectdetectioncpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/java/com/google/mediapipe/components:android_microphone_helper': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/java/com/google/mediapipe/framework:android_framework': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu:facedetectioncpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect:faceeffect': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/java/com/google/mediapipe/framework:mediapipe_exception_android': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/java/com/google/mediapipe/glutil:glutil': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/java/com/google/mediapipe/components:android_components': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d:objectdetection3d': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/iristrackinggpu:iristrackinggpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/java/com/google/mediapipe/framework:android_framework_no_mff': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/java/com/google/mediapipe/framework:framework_proto_lite': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu:objectdetectiongpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handdetectiongpu:handdetectiongpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu:posetrackinggpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking_lib': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/java/com/google/mediapipe/framework:android_core': it will not be built
INFO: Analysis succeeded for only 51 of 82 top-level targets
INFO: Analyzed 82 targets (6 packages loaded, 12070 targets configured).
INFO: Found 51 targets...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: command succeeded, but there were loading phase errors
INFO: Elapsed time: 602.317s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully
build invocation result: build_error
Sync was successful, but there were Bazel build errors. The project may not be fully updated or resolve until fixed. If the errors are from your working set, please uncheck 'Bazel > Sync > Expand Sync to Working Set' and try again.
Parsing build outputs...
Total rules: 13, new/changed: 0, removed: 0
Reading IDE info result...
Reading IDE info result...
Updating target map
Loaded 0 aspect files, total size 0kB
Target map size: 4
Prefetching output artifacts...
Reading jdeps files...
Loaded 0 jdeps files, total size 0kB
Reading package manifests...
Java content entry count: 1
Filtering empty jars...
Fetching JARs to track empty status..
Filtered 0 JARs, in 0ms
Updating Unpacked AAR libraries...
Updating Jar Cache...
Prefetching files...
Refreshing files
Computing directory structure...
Initializing project SDKs...
Committing project structure...
Workspace has 4 libraries
Android resource module count: 0, run config modules: 0, order entries: 0, generated resources: 0
Workspace has 2 modules
Updating in-memory state...
Sync finished

Timing summary:
BlazeInvocation: 602.4s, Prefetching: 2ms, Other: 29ms

**I am in China,use macOS catalina,I don't know if it's just me or the internet,Has anyone had this problem?thanks.**

**Comment by anandwana001** [comment]
Fetching a similar error -  https://github.com/oppia/oppia-android/issues/3157

**Comment by sgowroji** [comment]
Hi @c1139676919, You can try building the above with bazel commands like this, As we mentioned [here](https://github.com/google/mediapipe/issues/3#issuecomment-506926022)  

`$ bazel build -c opt --config=android_arm64 \ 
  --distdir=<your cache directory> \
  --repository_cache=<your cache directory> \
  --keep_going \
  mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu`
