### ISSUE TITLE
not able to allocate tensors to 'pose_detection.tflite'

### ISSUE THREAD

**Issue by AryanSethi** [google/mediapipe#1448]
Trying to use the function allocate_tensors() to allocate the tensors on 'pose_detection.tflite' but it is throwing an error:

```
tensorflow/lite/kernels/add.cc:86 NumInputs(node) != 2 (1 != 2)Node number 0 (ADD) failed to prepare.
```

**Comment by xzqjack** [comment]
same error. But The pose_upper_body_landmark.tflite is all right.

**Comment by eknight7** [comment]
@grishchenko-ivan, please take a look, thanks.

**Comment by heybai** [comment]
@NikolayChirkov Could you please help with this inference issue?

**Comment by AryanSethi** [comment]
No solution yet :/

**Comment by sgowroji** [comment]
Hi. @AryanSethi, Could you please respond if you still looking resolution for the above query. Thanks!

**Comment by AryanSethi** [comment]
I'm really sorry I've been very busy. I'll try it as soon as possible.
For now you can close the issue. I'll get back if there's something wrong.
