### ISSUE TITLE
what does 'pose_detection.tflite' output

### ISSUE THREAD

**Issue by AryanSethi** [google/mediapipe#1449]
On getting the output_information for the `pose_detection.tflite` model, I noticed that it is returning a  `(1 X 896 X  12)`  tensor along with one other output tensor.

What information does this `(1 X 896 X  12)`  tensor contain?

The total output details of the mentioned model are given below:

```


[
	{
		'name': 'regressors', 
		'index': 266, 
		'shape': array([  1, 896,  12]), 
		'shape_signature': array([  1, 896,  12]), 
		'dtype': <class 'numpy.float32'>, 
		'quantization': (0.0, 0), 
		'quantization_parameters': {
			'scales': array([], dtype=float32), 
			'zero_points': array([], dtype=int32), 
			'quantized_dimension': 0
			}, 
		'sparsity_parameters': {}
	}, 
	{
		'name': 'classificators', 
		'index': 265, 
		'shape': array([  1, 896,   1]), 
		'shape_signature': array([  1, 896,   1]), 
		'dtype': <class 'numpy.float32'>, 
		'quantization': (0.0, 0), 
		'quantization_parameters': {
			'scales': array([], dtype=float32), 
			'zero_points': array([], dtype=int32), 
			'quantized_dimension': 0
			}, 
		'sparsity_parameters': {}
	}
]
```

**Comment by nowaylv** [comment]
+1

**Comment by eknight7** [comment]
@grishchenko-ivan, please take a look, thanks.

**Comment by ivan-grishchenko** [comment]
Hi there!

896 is the number of anchors in SSD detector.
12 is the number of values predicted for each anchor: 4 values to define the location of the box and 8 values to define 4 key points (2 coordinates per each point) within this box (key points encode center and size of the crop later used by tracking model for upper-body and full-body cases).

Check how it is used in the graph: https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection_gpu.pbtxt#L104

And also check documentation for TensorsToDetectionsCalculator: https://github.com/google/mediapipe/blob/39309bedba255aee2a4f31b29b65609857698ada/mediapipe/calculators/tensor/tensors_to_detections_calculator.cc#L100

And the paper as well for details on we construct the crop: https://arxiv.org/pdf/2006.10204.pdf

**Comment by AryanSethi** [comment]
@ivan-grishchenko Thanks alot, that was helpful !
