### ISSUE TITLE
Error: !err Error creating pixel buffer: -6661 / handtrackinggpu

### ISSUE THREAD

**Issue by n-git** [google/mediapipe#145]
Checking the sample project for hand tracking makes it easier to generate errors under certain conditions (title errors).
Is there a solution?

[Device]
iPhoneX OS:12.0
iPhoneXR OS:12.1.4

[Build target project]
MediaPipe's hand tracking sample project
⁩ / ⁨mediapipe / ⁨examples / ⁨ios / ⁨handtrackinggpu⁩

[Steps that occurred]
1, Move your hand closer to the camera.
2, If the camera is close to the hand, the application will crash.
    When approaching to within 10cm.

[Error Log]
`019-10-04 17:24:30.569533+0900 HandTrackingGpuApp[1019:113245] [MC] Reading from public effective user settings.
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1004 17:24:30.594830 1873833984 gl_context.cc:233] GL version: 3.0 (OpenGL ES 3.0 Metal - 58.3)
2019-10-04 17:24:30.597188+0900 HandTrackingGpuApp[1019:113292] Initialized TensorFlow Lite runtime.
2019-10-04 17:24:30.597769+0900 HandTrackingGpuApp[1019:113292] Created TensorFlow Lite delegate for Metal.
W1004 17:24:30.598220 1878994944 tflite_inference_calculator.cc:539] Please ensure input GPU tensor is 4 channels.
W1004 17:24:30.694345 1880141824 tflite_inference_calculator.cc:539] Please ensure input GPU tensor is 4 channels.
F1004 17:24:35.053661 1880141824 gpu_buffer_multi_pool.cc:82] Check failed: !err Error creating pixel buffer: -6661`

**Comment by AndreyMirzoyan** [comment]
Same problem.
Handtrackinggpu⁩, iPhoneX, iOS 13.0
Unstable error. Most often occurs if the hands is leaving or entering the frame

Any solutions?

**Comment by camillol** [comment]
We'll attempt to reproduce.

**Comment by n-git** [comment]
> We'll attempt to reproduce.

Thank you for confirmation.
We look forward to your response.

**Comment by NikolayChirkov** [comment]
Fixed

**Comment by ljmkimqx** [comment]
I had the same problem, but I solved it. My project has integrated mediapipa framework, and then I use tensorflow_ lite.framework That's the mistake. My solution is to use tensorflow in "build phases > link binary with libraries". Put  tensorflow_ lite.framework under the framework related to mediapipa.

**Comment by ljmkimqx** [comment]
same error, I found that the error is from the “startwitherror” method of the MPPGraph object
