### ISSUE TITLE
An error occurred during the fetch of repository 'flatbuffers': This error occured while syncing bazel project in Android Studio

### ISSUE THREAD

**Issue by ParthP-7** [google/mediapipe#1451]
ERROR: An error occurred during the fetch of repository 'flatbuffers':
   Traceback (most recent call last):
        File "C:/users/parekh/_bazel_parekh/ity4giap/external/org_tensorflow/third_party/repo.bzl", line 193, column 26, in _third_party_http_archive
                _apply_delete(ctx, ctx.attr.delete)
        File "C:/users/parekh/_bazel_parekh/ity4giap/external/org_tensorflow/third_party/repo.bzl", line 74, column 32, in _apply_delete
                _execute_and_check_ret_code(ctx, cmd)
        File "C:/users/parekh/_bazel_parekh/ity4giap/external/org_tensorflow/third_party/repo.bzl", line 52, column 13, in _execute_and_check_ret_code
                fail(("Non-zero return code({1}) when executing '{0}':\n" + "Stdout: {2}\n" +
Error in fail: Non-zero return code(256) when executing 'C:\msys64\usr\bin -l -c "rm" "-rf" "C:/users/parekh/_bazel_parekh/ity4giap/external/flatbuffers/build_defs.bzl"':
Stdout:
Stderr: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\msys64\usr\bin" -l -c "\"rm\" \"-rf\" \"C:/users/parekh/_bazel_parekh/ity4giap/external/flatbuffers/build_defs.bzl\""): Access is denied.
 (error: 5)
INFO: Repository remotejdk11_win instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:193:6: in <toplevel>
  C:/users/parekh/_bazel_parekh/ity4giap/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  C:/users/parekh/_bazel_parekh/ity4giap/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository maven instantiated at:
  C:/users/parekh/mediaipe_repo/mediapipe/WORKSPACE:320:14: in <toplevel>
  C:/users/parekh/_bazel_parekh/ity4giap/external/rules_jvm_external/defs.bzl:94:19: in maven_install
Repository rule coursier_fetch defined at:
  C:/users/parekh/_bazel_parekh/ity4giap/external/rules_jvm_external/coursier.bzl:798:33: in <toplevel>
ERROR: C:/users/parekh/mediaipe_repo/mediapipe/mediapipe/calculators/core/BUILD:821:11: //mediapipe/calculators/core:split_vector_calculator depends on @org_tensorflow//tensorflow/lite/delegates/gpu/gl:gl_buffer in repository @org_tensorflow which failed to fetch. no such package '@flatbuffers//': Non-zero return code(256) when executing 'C:\msys64\usr\bin -l -c "rm" "-rf" "C:/users/parekh/_bazel_parekh/ity4giap/external/flatbuffers/build_defs.bzl"':
Stdout:
Stderr: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\msys64\usr\bin" -l -c "\"rm\" \"-rf\" \"C:/users/parekh/_bazel_parekh/ity4giap/external/flatbuffers/build_defs.bzl\""): Access is denied.
 (error: 5)
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: Analysis failed
INFO: Elapsed time: 60.124s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (47 packages loaded, 1007 targets configured)
    currently loading: @org_tensorflow//tensorflow/lite/delegates/gpu/gl
    Fetching @com_google_absl; fetching 31s
    Fetching ...e_absl; Extracting C:/users/parekh/_bazel_parekh/ity4giap/external/com_google_absl/temp103566193209280\
97763/20200923.tar.gz 24s

**Comment by jiuqiant** [comment]
As we mentioned in https://google.github.io/mediapipe/getting_started/install#installing-on-windows, MediaPipe doesn't support building its Android apps on native Windows because of the limited bazel support for Android on native Windows. Please try WSL instead. You can find the instructions at https://google.github.io/mediapipe/getting_started/install#installing-on-windows-subsystem-for-linux-wsl.
