### ISSUE TITLE
Getting the landmark data every frame for the new holistic model (Extracting Landmark Coordinate Data)

### ISSUE THREAD

**Issue by pkaske** [google/mediapipe#1452]
I figured out a way to get the (x,y,z) data points for each frame from one hand previously. but im not sure how to do that for the new holistic model that they released. I am trying to get the all landmark data points for both hands as well as parts of the chest and face. does anyone know how to extract the holistic landmark data/print it to a text file? or at least give me some directions as to how.

(please note i got this done successfully in python, but now want to do it in c++)

**Comment by eknight7** [comment]
Hi - definitely - extracting landmarks should be similar to extracting landmarks as shown in other MediaPipe solutions. Where are you trying to do this exactly?

**Comment by pkaske** [comment]
well last time i used the landmark_letterbox_removal_calculator.cc file (mediapipe/mediapipe/calculators/util/landmark_letterbox_removal_calculator.cc) and just printed the x,y,z coordinates for the 21 landmarks by manually creating a .txt that wrote them every frame. but I'm not sure how to do that for the new holistic. i need both the hands (21 points each) plus some of the pose coordinate landmarks as well.

**Comment by shadow111** [comment]
> Hi - definitely - extracting landmarks should be similar to extracting landmarks as shown in other MediaPipe solutions. Where are you trying to do this exactly?

can you please put me on the right track i want all the landmarks together but still can't figured it out

**Comment by pkaske** [comment]
> Hi - definitely - extracting landmarks should be similar to extracting landmarks as shown in other MediaPipe solutions. Where are you trying to do this exactly?

well last time i used the landmark_letterbox_removal_calculator.cc file (mediapipe/mediapipe/calculators/util/landmark_letterbox_removal_calculator.cc) and just printed the x,y,z coordinates for the 21 landmarks (one hand) by manually creating a .txt that wrote them every frame. but I'm not sure how to do that for the new holistic (how/where do i do that? what calculators,etc). I need both the hands now (21 points each) plus some of the pose coordinate landmarks as well. so how do i do that all at once

**Comment by SayedHamdiF** [comment]
@pkaske 
could you please share with me code i want to save all keypoints in csv files. untill now i ca't , please help

**Comment by Wansh619** [comment]
is this issue still open?

**Comment by yndue736** [comment]
Yes there are some level discussion still in process you can click on the link [Today telenor answer](https://pakstudy.net/)  where they have added the same procedure which is useful in this project.

**Comment by sureshdagooglecom** [comment]
Hi @pkaske ,
Are you still looking for the resolution on this issue.
