### ISSUE TITLE
When I was building the AAR file, it displayed Fetching @maven all the time

### ISSUE THREAD

**Issue by ljmkimqx** [google/mediapipe#1462]
I've tried many times and I've been stuck on this problem。After more than 600 seconds will automatically report an error, prompt timeout。

bazel: 3.7.2
Mac OS:  10.15.5
android sdk: api 30
android ndk: 21.3.6528147
android studio: 4.0.1

Is there anyone who can help? 

`
(base) ljm@LJM mediapipe-master % bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    //mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mp_face_detection_aar
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/a\
pps/buid_aar:mp_face_detection_aar (1 packages loaded, 6 targets configured)
    Fetching @maven; Resolving and fetching the transitive closure of 21 artif\
act(s).. 176s
`

**Comment by ljmkimqx** [comment]
Time Out Error

`
ljm@LJM mediapipe-master % bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    //mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mp_face_detection_aar
INFO: Repository maven instantiated at:
  /Users/ljm/Desktop/MyProjects/mediapipe-master/WORKSPACE:320:14: in <toplevel>
  /private/var/tmp/_bazel_ljm/c27ab7acff4bb8f7e4f4cf5b1a187c55/external/rules_jvm_external/defs.bzl:94:19: in maven_install
Repository rule coursier_fetch defined at:
  /private/var/tmp/_bazel_ljm/c27ab7acff4bb8f7e4f4cf5b1a187c55/external/rules_jvm_external/coursier.bzl:798:33: in <toplevel>
INFO: Repository 'maven' used the following cache hits instead of downloading the corresponding file.
 * Hash '6598d9277705ad8369a4f9c64217fbc31c19234f2cbcca9b1e5c4300a3abb317' for https://github.com/coursier/coursier/releases/download/v2.0.0-RC5-3/coursier.jar
If the definition of 'maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ljm/c27ab7acff4bb8f7e4f4cf5b1a187c55/external/rules_jvm_external/coursier.bzl", line 544, column 13, in _coursier_fetch_impl
		fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Timed out
ERROR: /Users/ljm/Desktop/MyProjects/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mp_face_detection_aar_android_lib depends on @maven//:com_google_code_findbugs_jsr305 in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/ljm/Desktop/MyProjects/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mp_face_detection_aar_android_lib depends on @maven//:com_google_flogger_flogger in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/ljm/Desktop/MyProjects/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mp_face_detection_aar_android_lib depends on @maven//:com_google_flogger_flogger_system_backend in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/ljm/Desktop/MyProjects/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mp_face_detection_aar_android_lib depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /Users/ljm/Desktop/MyProjects/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mp_face_detection_aar_android_lib depends on @maven//:androidx_lifecycle_lifecycle_common in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mp_face_detection_aar' failed; build aborted: Analysis failed
INFO: Elapsed time: 601.000s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 6 targets conf\
igured)
`

**Comment by DandyLorenz** [comment]
Your question is similar to the following. Can you solve it by comparing it？
https://github.com/google/mediapipe/issues/1450

**Comment by ljmkimqx** [comment]
thank @DandyLorenz ， I've seen it. Sorry, I don't think it's the same problem.

I think my question is related to this paragraph in the workspace file.
`
# Maven dependencies.

RULES_JVM_EXTERNAL_TAG = "3.2"
RULES_JVM_EXTERNAL_SHA = "82262ff4223c5fda6fb7ff8bd63db8131b51b413d26eb49e3131037e79e324af"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

# Important: there can only be one maven_install rule. Add new maven deps here.
maven_install(
    name = "maven",
    artifacts = [
        "androidx.concurrent:concurrent-futures:1.0.0-alpha03",
        "androidx.lifecycle:lifecycle-common:2.2.0",
        "androidx.annotation:annotation:aar:1.1.0",
        "androidx.appcompat:appcompat:aar:1.1.0-rc01",
        "androidx.camera:camera-core:1.0.0-beta10",
        "androidx.camera:camera-camera2:1.0.0-beta10",
        "androidx.camera:camera-lifecycle:1.0.0-beta10",
        "androidx.constraintlayout:constraintlayout:aar:1.1.3",
        "androidx.core:core:aar:1.1.0-rc03",
        "androidx.legacy:legacy-support-v4:aar:1.0.0",
        "androidx.recyclerview:recyclerview:aar:1.1.0-beta02",
        "androidx.test.espresso:espresso-core:3.1.1",
        "com.github.bumptech.glide:glide:4.11.0",
        "com.google.android.material:material:aar:1.0.0-rc01",
        "com.google.code.findbugs:jsr305:3.0.2",
        "com.google.flogger:flogger-system-backend:0.3.1",
        "com.google.flogger:flogger:0.3.1",
        "com.google.guava:guava:27.0.1-android",
        "com.google.guava:listenablefuture:1.0",
        "junit:junit:4.12",
        "org.hamcrest:hamcrest-library:1.3",
    ],
    repositories = [
        "https://jcenter.bintray.com",
        "https://maven.google.com",
        "https://dl.google.com/dl/android/maven2",
        "https://repo1.maven.org/maven2",
    ],
    fetch_sources = True,
    version_conflict_policy = "pinned",
)
`

But I have configured the Maven environment。like this
`
(base) ljm@LJM mediapipe-master % which mvn

/Users/ljm/Desktop/MyProjects/apache-maven-3.6.3/bin/mvn
`

And I have this file
`/private/var/tmp/_bazel_ljm/c27ab7acff4bb8f7e4f4cf5b1a187c55/external/rules_jvm_external-3.2`

I tried a lot, but it didn't work

**Comment by ljmkimqx** [comment]
I solved this problem, it is network problem, must use VPN

**Comment by yyqgood** [comment]
@ljmkimqx Is it convenient to talk about the specific details?

**Comment by ljmkimqx** [comment]
Open VPN and try to build AAR again. (VPN needs to be purchased or established by the server) @yyqgood

**Comment by mmiirroo** [comment]
another way is using mirrors of maven repositories
