### ISSUE TITLE
lift the 2D keypoints to 3D function in Objectron

### ISSUE THREAD

**Issue by benchun123** [google/mediapipe#1463]
Hi everyone, I'm interested in 3D object detection and find this paper, similar to the function, I have got 8 vertices of bbox in images, and I want to get 3d pose with EPnP. I just copy the function into my own code, but can not get a good result. Following the code and paper, I have questions: 

1) Is the [projection matrix ](https://github.com/google/mediapipe/blob/f15da632dec186f2c1d3c780f47086477e2286a9/mediapipe/graphs/object_detection_3d/calculators/decoder.cc#L195) defined as [[1.5731, 0, 0,  0,   0, 2.0975, 0, 0,      0, 0, -1.0002, -0.2,      0,  0, -1, 0;]  ]( https://github.com/google/mediapipe/blob/f15da632dec186f2c1d3c780f47086477e2286a9/mediapipe/graphs/object_detection_3d/calculators/lift_2d_frame_annotation_to_3d_calculator.cc#L95)? but I think fx, fy, cx, cy should come from intrinsic like [481.9, 0, 319.5, 0, 480.0, 239.5, 0, 0, 1;], I did not run the code, maybe I am wrong. 

2) in this function, after solving M, which is a 12x12 matrix, why do we just use the [first col](https://github.com/google/mediapipe/blob/f15da632dec186f2c1d3c780f47086477e2286a9/mediapipe/graphs/object_detection_3d/calculators/decoder.cc#L237), in original EPnP paper, we need to compute beta and get final result as x = beta(i,j) * vector(i).

3) for the final center[ keypoints and vertices](https://github.com/google/mediapipe/blob/f15da632dec186f2c1d3c780f47086477e2286a9/mediapipe/graphs/object_detection_3d/calculators/decoder.cc#L244), are they in camera coordinate or world coordinate? I notice the [alpha_epnp](https://github.com/google/mediapipe/blob/f15da632dec186f2c1d3c780f47086477e2286a9/mediapipe/graphs/object_detection_3d/calculators/decoder.h#L36) is defined, is the control points are also defined? 

in my case, the vertices in 2d image are
616 202 227 531 617 203 228 531
441 450 392 387 282 284 272 270
corresponding 3d corners are (just for verification, not for EPnP) 
  1.65684 -0.619926 -0.670542   1.60623   1.65684 -0.619926 -0.670542   1.60623
  2.67991   2.56059    3.5264   3.64572   2.67991   2.56059    3.5264   3.64572
        0         0         0         0  0.886234  0.886234  0.886234  0.886234
camera matrix: 481.9, 0, 319.5, 0, 480.0, 239.5, 0, 0, 1;
projection matrix: 1, 0, 0, 0,   0, 0, 1, 0,   0, -1, 0, 1.25,   0, 0, 0, 1;

after EPnP, the control matrix is 
-0.0711339 -0.0992085  -0.453414
 -0.237271 -0.0988417  -0.460921
-0.0674236 -0.0989933   -0.52393
-0.0715109 -0.0345479  -0.453697
finally, I get center points in 3d as: -0.0711339 -0.0992085  -0.453414
vertices  in 3d:
 -0.240604    0.09167  0.0990905  -0.233184  -0.241358  0.0909159  0.0983364  -0.233938
 -0.163718  -0.164451  -0.164021  -0.163287 -0.0343964 -0.0351299 -0.0346994 -0.0339659
 -0.390122  -0.375107   -0.51614  -0.531155  -0.390688  -0.375673  -0.516706  -0.531721
 which are totally different from ground truth. I do not know how to get the scale, ...

**Comment by benchun123** [comment]
Hi everyone, these days I debug the code again and find some explanation to above questions: 
1, the projection matrix should be like  [481.9, 0, 319.5, 0, 480.0, 239.5, 0, 0, 1;], but in Mediapipe, maybe it is different. 
2, from EPnP paper, when we just use the first col, we just set N=1 when calculating x in Mx=0 (or M*Cc = 0), we also can set N=2,3,4..., but it would be more complicate. 
3, the 4 control points are center and  3 points along the coordinate axes, such as [(0,0,0), (long,0,0), (0,width,0), (0,0,height)], I think the dimensions for shoes are saved, but not sure. 

Thanks for comment and conversation.

**Comment by rjean** [comment]
My guess is that "epnp_alpha_" might refer to coefficients that constraints the 8 corners of the bounding box in a bounding box shape, which are then used to build the homogeneous system of equation "M". Instead of solving with SVD for a specific static bounding box or set of points, I think they might solve for a generic bounding box equation. 

I'm also in the dark here on exactly how they build "M", I'm have not yet found the supplementary material of the paper that should explain exactly how "M" is built. However in the paper they state that they can recover the bounding box up to scale, which hints me that they found of clever way of doing that which is not typically done with EPnP.  

What do you think?

**Comment by benchun123** [comment]
Hi Rjean, 
yes, I think "epnp_alpha" is the coefficients, in my successful test, the alpha is defined as 
epnp_alpha <<  
-2, 1,  1, 1,   
0,  1, -1, 1,
2, -1, -1, 1,  
0, -1,  1, 1,
0,  1,  1, -1,   
2,  1, -1, -1,
4, -1, -1, -1,  
2, -1,  1, -1;
where we can find the in every line, the first element is the sum of other elements, and the other 3 elements indicates the direction of corner. (or the position if multiplied with dimension)

how to build M, well, I think it is the same as EPnP, you can find more details at official [EPnP code](https://github.com/cvlab-epfl/EPnP/blob/5abc3cfa76e8e92e5a8f4be0370bbe7da246065e/cpp/epnp.cpp#L154) or [modified code](https://github.com/jessecw/EPnP_Eigen/blob/2848932c06ddfd750c84dc2ff108bcffac8f92bb/epnp_eigen.cpp#L81)

Hope it is helpful.

**Comment by ahmadyan** [comment]
This is the [reference](https://www.iri.upc.edu/people/fmoreno/Publications/2009/pdf/Lepetit_ijcv2009.pdf) that we used for EPNP.You are correct, that the alpha matrix constraints the vertices of the bounding box. There are multiple alpha matrices that you can use (essentially will all do the same). Coefficient that we used can be [found here](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/modules/objectron/calculators/decoder.h#L35).

```
  def _get_pnp_a(self):
    """Gets coefficient matrix for solving pnp."""
    return np.array(
        [[4, -1, -1, -1], [2, -1, -1, 1], [2, -1, 1, -1], [0, -1, 1, 1],
         [2, 1, -1, -1], [0, 1, -1, 1], [0, 1, 1, -1], [-2, 1, 1, 1]],
        dtype=np.float32)

```

You can also see how we do the actual lifting in [this function](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/modules/objectron/calculators/decoder.cc#L192)

Also regarding the projection matrix, we assume focal in mm and the image in normalized [-1,1] space, so the central point should be around 0. There are other coordinate systems that would assume focal/image in pixel.

**Comment by yehDilBeparwah** [comment]
I read the Epnp paper and the lifting2Dto3D code, there are just a few things if someone could help me with.

Q. [code](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/modules/objectron/calculators/decoder.cc#L250), why is the alpha matrix multiplied with the solution(control matrix) to get to vertices.

Q. I am trying to reproduce the results (by running the function as a standalone c++  gtest). I am taking input (2d points/ expected 3d points) from 'objectron-geometry-tutorial.ipynb' notebook in Objectron repo. I can't reproduce the results. If we look at the code I posted above, the 3d point equivalent to centre of the box would be the first 3 values in control matrix.
I cycled through all the Eigen values/eigen vectors which would form the control matrix(in the code we take the first Eigen value) but none of the values match expected 3D point.
Do I need to use another alpha matrix or how can I find it.

**Comment by N-G17** [comment]
@benchun123 Hye... I came across the similar issue and I am not able to determine the cause for the same. 
Similar to the example shared by you, in my case: 
The 2d vertices of the cube in the image are: 
x: 299, 213, 301, 384, 285, 187, 292, 388
y: 499, 441, 388, 429, 236, 210, 188, 205
camera matrix: 529.5000, 0, 365.0000, 0, 529.5000, 265.0000, 0, 0, 1.0000;

After applying EPnP, I am getting 3D Cube Center as: (0.316922, 0.28584, -0.25422) 
and the 3D Cube vertices as: 
(0.291871, 0.335939, -0.232844) 
(0.294688, 0.359899, -0.269901) 
(0.397649, 0.389816, -0.316145) 
(0.394831, 0.365856, -0.279088) 
(0.236196, 0.181863, -0.192296) 
(0.239013, 0.205824, -0.229353) 
(0.341974, 0.23574, -0.275597) 
(0.339157, 0.21178, -0.23854)

which is completely different from the ground truth , i.e, 
(-0.220993, 1.41875, 0)
(-0.591383, 1.71872, 0)
(-0.290467, 2.09028, 0)
(0.079923, 1.79031, 0)
(-0.220993, 1.41875, 0.926058)
(-0.591383, 1.71872, 0.926058)
(-0.290467, 2.09028, 0.926058)
(0.079923, 1.79031, 0.926058)

The epnp_alpha I used is: 
epnp_alpha << 4.0f, -1.0f, -1.0f, -1.0f,
            2.0f, -1.0f, -1.0f,  1.0f,
            2.0f, -1.0f,  1.0f, -1.0f,
            0.0f, -1.0f,  1.0f,  1.0f,
            2.0f,  1.0f, -1.0f, -1.0f,
            0.0f,  1.0f, -1.0f,  1.0f,
            0.0f,  1.0f,  1.0f, -1.0f,
            -2.0f,  1.0f,  1.0f,  1.0f;

were you able to rectify the issue? I would really appreciate your help.
Thanks

**Comment by N-G17** [comment]
@benchun123 Hye... I came across the similar issue and I am not able to determine the cause for the same. 
Similar to the example shared by you, in my case: 
The 2d vertices of the cube in the image are: 
x: 299, 213, 301, 384, 285, 187, 292, 388
y: 499, 441, 388, 429, 236, 210, 188, 205
camera matrix: 529.5000, 0, 365.0000, 0, 529.5000, 265.0000, 0, 0, 1.0000;

After applying EPnP, I am getting 3D Cube Center as: (0.316922, 0.28584, -0.25422) 
and the 3D Cube vertices as: 
(0.291871, 0.335939, -0.232844) 
(0.294688, 0.359899, -0.269901) 
(0.397649, 0.389816, -0.316145) 
(0.394831, 0.365856, -0.279088) 
(0.236196, 0.181863, -0.192296) 
(0.239013, 0.205824, -0.229353) 
(0.341974, 0.23574, -0.275597) 
(0.339157, 0.21178, -0.23854)

which is completely different from the ground truth , i.e, 
(-0.220993, 1.41875, 0)
(-0.591383, 1.71872, 0)
(-0.290467, 2.09028, 0)
(0.079923, 1.79031, 0)
(-0.220993, 1.41875, 0.926058)
(-0.591383, 1.71872, 0.926058)
(-0.290467, 2.09028, 0.926058)
(0.079923, 1.79031, 0.926058)

The epnp_alpha I used is: 
epnp_alpha << 4.0f, -1.0f, -1.0f, -1.0f,
            2.0f, -1.0f, -1.0f,  1.0f,
            2.0f, -1.0f,  1.0f, -1.0f,
            0.0f, -1.0f,  1.0f,  1.0f,
            2.0f,  1.0f, -1.0f, -1.0f,
            0.0f,  1.0f, -1.0f,  1.0f,
            0.0f,  1.0f,  1.0f, -1.0f,
            -2.0f,  1.0f,  1.0f,  1.0f;

were you able to rectify the issue? I would really appreciate your help.
Thanks

**Comment by ahmadyan** [comment]
WHen lifting from a single image, you won't be able to calculate the scale of the cube correctly. So the cube's lifting would be correct up to a scale. You should not expect it to match the ground truth keypoints. 

P.S. Your GT also looks weird. for example, it only has 8 vertices (instead of 9) and the Z for the first 4 vertices are set to 0.

**Comment by N-G17** [comment]
@ahmadyan  Thanks for your reply.
I am facing the same problem as is mentioned by @benchun123 in the main question of the issue. I have got 8 vertices of the cube in an image, and I want to get 3D pose with EPnP for the same. The ground truth I am mentioning is the 3D vertices for the cube (similar to the one mentioned by @benchun123). 
That was the reason i directed my question to @benchun123 and see whether the problem was resolved and how did he move forward with the scale computation?

**Comment by benchun123** [comment]
@N-G17 as ahmadyan said, 1) we can not calculate the scale of the cube, 2) regarding the projection matrix, we assume focal in mm and the image in normalized [-1,1] space, so the central point should be around 0. There are other coordinate systems that would assume focal/image in pixel.

In my case, I suppose I know the scale of the cube, that is, the width, length and height are known. Another important thing is EPnP convert cube from image coordinates to camera coordinates, but your GT may be in world coordinates (z=0), without knowing camera pose, it is hard to know if it is correct or not.
