### ISSUE TITLE
Where is the hand detection tflite model?

### ISSUE THREAD

**Issue by TheBricktop** [google/mediapipe#1464]
In the models directory some of the models are missing, mainly the hand detection model, ive seen that it was available some time before.
Whats the reason for that?
Where i can find the .tflite model for hand tracking gpu?

**Comment by jiuqiant** [comment]
We reorganized the file structure. So the new location of the hand(palm) detection model is https://github.com/google/mediapipe/blob/master/mediapipe/modules/palm_detection/palm_detection.tflite
