### ISSUE TITLE
Where is the texcoord information used in the whole process?

### ISSUE THREAD

**Issue by Whisperd130** [google/mediapipe#1467]
The .uuu format I have known from gl_animation_overlay_calculator.cc with no texcoord indices.
The normal .obj file gets vertex indices, texcoord indices and triangle indices in the last part of file.
Which just like f 1/1/1 2/2/2 4/4/3 3/3/4 or f 1/1 2/2 3/3 4/4. 

Did .uuu format also got these information? Or just gets vertex indices?

**Comment by Whisperd130** [comment]
I don't understand how does the program know each point's uv information.
Once I change the .obj file which has uv information to .uuu format which doesn't has it, the uv information just gone since change happened.

**Comment by tyrmullen** [comment]
The .uuu format has all 3 pieces of information: vertex positions (3d), texcoord positions (2d), and triangle indices.  But they are grouped in a way that is easy for OpenGL rendering.  Will try to answer these questions in https://github.com/google/mediapipe/issues/1074, so closing this issue as duplicate for now.
