### ISSUE TITLE
Python API with GPU on Jetson Xavier NX

### ISSUE THREAD

**Issue by kelvinxuande** [google/mediapipe#1470]
I have diligently followed the instructions on a Jetson Xavier NX found [here](https://github.com/jiuqiant/mediapipe_python_aarch64) and managed to successfully use the python API (specifically .solutions) for pose estimation to query the keypoints in an image. I would like to ask - in such a scenario, is the GPU enabled and utilised? i.e. are there seperate bazel build procedure/ configurations to enable and utilise the GPU?

Thanks and best regards.

**Comment by jiuqiant** [comment]
The prebuilt MediaPipe Python wheels only have the cpu graphs and running those solutions doesn't require GPU. It's possible to modify the config and build a local gpu version of the Python package. See https://github.com/google/mediapipe/issues/1042. Note that that post assumes the version is v0.7.9 not the current version.

**Comment by kelvinxuande** [comment]
@jiuqiant thank you so much for your reply - will give the instructions found in #1042 a shot. I can't seem to find a v0.7.9, do the instructions still hold if I were to work on the master branch?

Also, would there still be a need to setup OpenCV (since OpenCV comes inbuilt with Jetsons) if I was solely using the Python API?

**Comment by jiuqiant** [comment]
"undefined symbol: _ZN2cv3MatC1Ev" means opencv is not linked correctly. Do you install opencv locally and build mediapipe python by `python3 setup.py gen_protos && python3 setup.py install --link-opencv`. If you plan to compile opencv with mediapipe, try `python3 setup.py gen_protos && python3 setup.py bdist_wheel`.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by only-tao** [comment]
I have got the cpu version mediapipe , but now I want to get the gpu version 
then
I follow the #1042 ,

add the 
`--copt=-DMESA_EGL_NO_X11_HEADERS --copt=-DEGL_NO_X11`
in two places,
but I get a error:
when I run the code:
`python3 setup.py gen_protos && python3 setup.py bdist_wheel
`

the error like this :
`nx@nx-desktop: -/mediapipe
／usr/bin/gcc-U_FORTIFY_SOURCE-fstack-protector-Wall-Wunused-but-set-parameter -Wno-free-nonh
－object-fno-omit-frame-pointer -gθ -02 '-D_FORTIFY_SOURCE=1' -DNDEBUG-ffunction-sections. . . (r
ining 69 argument (s) skipped)

Use--sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command
r/bin/gcc -U FORTIFY SOURCE -fstack-protector -Wall -Wunused-but-set-parameter-Wno-free-nonheap
ect-fno-omit-frame-pointer-g0-02 '-D_FORTIFY_SOURCE=1'-DNDEBUG -ffunction-sections. . . (remai
g 69 argument (s) skipped)

Use--sandbox_debug to see verbose messages fron the sandbox
mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc: In function 'absl: :lts_2020
23: : StatusOr <std: :unique_ptr <mediapipe: : ImageToTensorConverter> > mediapipe: : CreateImageToGLBuff
nsorConverter (mediapipe: : CalculatorContext*,bool,mediapipe: : BorderMode) ':
mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.ck: 342: 10:error:could not con
＇result' from 'std: :unique_ptr <nediapipe: : {anonymous}::GlProcessor,std::default_delete<mediapi
｛anonymous} : : GLProcessor> > 「to 'absl: :lts_2020_09_23: : Status0r <std: :unique_ptr <mediapipe: : Image
nsorConverter> >
return result;
Target//mediapipe/modules/face_detection:face_detection_short_range_cpu failed to build
ICes to see the command Lines of failed build steps.
`
How can I do next？
in jeton xavier ubuntu 18.04

**Comment by khanhnd0408** [comment]
> I have got the cpu version mediapipe , but now I want to get the gpu version
> then
> I follow the #1042 ,
> 
> add the
> `--copt=-DMESA_EGL_NO_X11_HEADERS --copt=-DEGL_NO_X11`
> in two places,
> but I get a error:
> when I run the code:
> `python3 setup.py gen_protos && python3 setup.py bdist_wheel `
> 
> the error like this :
> `nx@nx-desktop: -/mediapipe
> ／usr/bin/gcc-U_FORTIFY_SOURCE-fstack-protector-Wall-Wunused-but-set-parameter -Wno-free-nonh
> －object-fno-omit-frame-pointer -gθ -02 '-D_FORTIFY_SOURCE=1' -DNDEBUG-ffunction-sections. . . (r
> ining 69 argument (s) skipped)
> 
> Use--sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command
> r/bin/gcc -U FORTIFY SOURCE -fstack-protector -Wall -Wunused-but-set-parameter-Wno-free-nonheap
> ect-fno-omit-frame-pointer-g0-02 '-D_FORTIFY_SOURCE=1'-DNDEBUG -ffunction-sections. . . (remai
> g 69 argument (s) skipped)
> 
> Use--sandbox_debug to see verbose messages fron the sandbox
> mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc: In function 'absl: :lts_2020
> 23: : StatusOr <std: :unique_ptr <mediapipe: : ImageToTensorConverter> > mediapipe: : CreateImageToGLBuff
> nsorConverter (mediapipe: : CalculatorContext*,bool,mediapipe: : BorderMode) ':
> mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.ck: 342: 10:error:could not con
> ＇result' from 'std: :unique_ptr <nediapipe: : {anonymous}::GlProcessor,std::default_delete<mediapi
> ｛anonymous} : : GLProcessor> > 「to 'absl: :lts_2020_09_23: : Status0r <std: :unique_ptr <mediapipe: : Image
> nsorConverter> >
> return result;
> Target//mediapipe/modules/face_detection:face_detection_short_range_cpu failed to build
> ICes to see the command Lines of failed build steps.
> `
> How can I do next？
> in jeton xavier ubuntu 18.04

Hello, have you solve this?
I'm facing same problem with "return result;" in image_to_tensor_converter_gl_buffer.cc
