### ISSUE TITLE
Holistic fails to create threads

### ISSUE THREAD

**Issue by AmitMY** [google/mediapipe#1471]
I'm trying to run Holistic pose estimation on a large dataset.
My code manages to run for a couple of minutes, and then crashes with:
> F20210106 13:47:22.596382 178933 threadpool_pthread_impl.cc:51] Check failed: res == 0 (11 vs. 0) pthread_create failed

If I cache the results, and don't rerun what already ran, it continues safely, and finishes on the entire dataset if I run the bash command:
`until python pose.py`

My code looks roughly like this:
```python
for frames in videos:
    holistic = mp_holistic.Holistic(static_image_mode=False)

    results = [holistic.process(frame) for frame in frames]
     
    np_results = convert_holistic_to_tensor(results)
    np.save("demonsration.txt")
```

In my code there are no threads being opened, so I can only assume its holistic

**Comment by eknight7** [comment]
@grishchenko-ivan please take a look, thanks.

**Comment by ivan-grishchenko** [comment]
@jiuqiant Please help with the Python API

**Comment by jiuqiant** [comment]
The number 11 returned by `pthread_create` means "The system lacked the necessary resources to create another thread, or the system-imposed limit on the total number of threads in a process PTHREAD_THREADS_MAX would be exceeded."

For each frame, you create a new Holistic instance, which seems to be problematic... Any reason to do so?
You probably want to create one Holistic instance per a video instead?

**Comment by jiuqiant** [comment]
The number 11 returned by pthread_create means "The system lacked the necessary resources to create another thread, or the system-imposed limit on the total number of threads in a process PTHREAD_THREADS_MAX would be exceeded."

For each frame, you create a new Holistic instance, which seems to be problematic. Assume that the video is one minute long and each Holistic starts ~20 threads. You will get 20 threads/frame * 30 frames/second * 60 seconds * = 36000 threads... Any reason to do so? You probably want to create one Holistic instance per video instead?

**Comment by AmitMY** [comment]
@jiuqiant it is creating 1 holistic instance per video
`frames` in the code above is just a raw video.
and then `process` per frame.

maybe threads are not closed appropriately at every run of the loop?

**Comment by jiuqiant** [comment]
What if you call `holistic.close()` at the end of the for loop?

**Comment by AmitMY** [comment]
Since adding `.close` I do not longer encounter this issue. Thanks!

**Comment by DanielXu123** [comment]
Hey, @AmitMY May I ask how to adding the `.close` ?  I met the simliar kind of problem when calling the `mp.solutions.face_mesh` API.

**Comment by hassaanhameed786** [comment]
> The number 11 returned by pthread_create means "The system lacked the necessary resources to create another thread, or the system-imposed limit on the total number of threads in a process PTHREAD_THREADS_MAX would be exceeded."
> 
> For each frame, you create a new Holistic instance, which seems to be problematic. Assume that the video is one minute long and each Holistic starts ~20 threads. You will get 20 threads/frame * 30 frames/second * 60 seconds = 36000 threads. Any reason to do so? You probably want to create one Holistic instance per video instead?

thank you for well explain
