### ISSUE TITLE
Novel 3D Annotation Tool for AR Session Data

### ISSUE THREAD

**Issue by wilcobonestroo** [google/mediapipe#1472]
The blog article on https://ai.googleblog.com/2020/03/real-time-3d-object-detection-on-mobile.html describes a "novel annotation tool for use with AR session data" that was used to create the annotated dataset. Which tool is that? Is that tool also available, so that we can 3D annotate our own AR sessions on custom objects?

I read the description of the [dataset preparation tool](https://google.github.io/mediapipe/solutions/media_sequence.html), but it does not describe 3D annotation.

**Comment by wilcobonestroo** [comment]
Hi, I am still interested in knowing more about the annotation tool. Does anybody have some idea about the above question?

**Comment by guozhi** [comment]
I am  interested in knowing more about the annotation tool too.

**Comment by mgyong** [comment]
There are no plans to release the 3D Annotation tool. We have released the annotated objectron dataset

**Comment by sarimmehdi** [comment]
Why is this tool not being released? It can be useful for all of us

**Comment by SecretHippo1** [comment]
I would also like to vote for release of the annotation tool as I'm currently scouring the web endlessly for something of this nature.

**Comment by nrwiederhold** [comment]
This annotation tool could accelerate a lot of projects dealing with pose annotation. It seems like one of the best tools out there for this purpose. Why not release it?

**Comment by wale-icon** [comment]
Is there a way to train a custom object? If the 3D annotation tool is not released, does this mean we can only use the available models like cups, shoes, and others?
