### ISSUE TITLE
hand detection problem: tflite output param

### ISSUE THREAD

**Issue by sunzk2017** [google/mediapipe#1476]
Hi
I want to train the net and use the tensorflow lite file(palm_detection.tflite and hand_landmark.tflite )  in c++，but I do not understand the net output, there are two questions:
(1) palm_detection.tflite:  tensor output shape is 1* 896* 1 and 1* 896* 18.  I know dims 18 means each anchor has 3 boxes with class number and x1,y1,x2,y2.  but I do not know the output value range and parameter order. and the net input (some thing about image preprocess). could you give me some detail about the net parameters?
(2）hand_landmark.tflite: I know use use palm_detection first, then use hand_landmark, but the output tensor value is not in scope[0.0f, 1f]，some value larger than 100.. is something wrong with it? Normalize image scalar to[0,1] seem no use( I divide it  by 255)
thank you.....

**Comment by kinivi** [comment]
The same question, I am going to use the raw tflite model, but preprocessing and model outputs are too cumbersome. Even after framework investigation, it is hard to understand all preprocessing pipeline.

**Comment by sunzk2017** [comment]
After studying the ssd carefully, I retrain a palm_detection model and hand_landmark  model using my own data. performance is still under eval.  If there is other progress, I will come back to this post..

**Comment by kinivi** [comment]
@sunzk2017 I think this can help you https://github.com/junhwanjang/mediapipe-models/tree/main/palm_detection/mediapipe_models

**Comment by sunzk2017** [comment]
@kinivi  It is really helpfull to learn the output parameters. Thanks a lot

**Comment by eknight7** [comment]
@sunzk2017 is the issue resolved now? Thanks.
