### ISSUE TITLE
Get Face rotation from face landmarks 

### ISSUE THREAD

**Issue by davitgoder** [google/mediapipe#1477]
I've got the face tracking working using the following example, I am not sure how to capture the head rotation any solution for that? Thanks!
https://codepen.io/mediapipe/details/KKgVaPJ

**Comment by davircarvalho** [comment]
did you manage to extract head orientation from face landmarks? If so please share your code!

**Comment by mhays-google** [comment]
Exposing face rotation is a line item on my TODO, but there's no definite date we're releasing this. 

If you are really comfortable with vectors, then at a high level, the technique we employ is to iterate over the triangles of the face mesh, computing the tangents and normals of each and then merging those together to get a rotation matrix.

**Comment by davitgoder** [comment]
Thanks Michael,
could you please provide the math literature for that?
once you have normals how do you get the rotation matrix?
Davit.

**Comment by fahadhaq** [comment]
@davitgoder Have a look at face effect example for android. The Calculator uses FaceGeometry which converts it to a matrix which can be used to calculate Pitch, Roll and Yaw.

**Comment by showbit01** [comment]
can I assume landmarks points x,y,z as 3d for world coordinates and x,y from same landmarks as 2d image coordinates For calculation of rotation matrix then Euler angles for head pose estimation?
Please help!

**Comment by sureshdagooglecom** [comment]
Hi @davitgoder ,
Are you still looking for the resolution on this issue.
