### ISSUE TITLE
Python, printing left and right hand landmarks for the holistic model in colab.

### ISSUE THREAD

**Issue by pkaske** [google/mediapipe#1479]
print(
    f'Right Hand:\n'
    f'{results.right_hand_landmarks.landmark}'
    f'Left Hand:\n'
    f'{results.left_hand_landmarks.landmark}'
    )

when running the python holistic in colab. im printing out the hand landmark coordinates for the photo. when doing this it prints the landmarks x,y,z correctly for a SINGLE image. but it doesn't work when trying to use multiple images at once. it gives the error

AttributeError                            Traceback (most recent call last)
<ipython-input-158-402892b7d48c> in <module>()
     31 
     32   print(
---> 33     f'Right Hand:\n'
     34     f'{results.right_hand_landmarks.landmark}'
     35     f'Left Hand:\n'

AttributeError: 'NoneType' object has no attribute 'landmark' 

as soon as it gets to trying to print the right and left hand landmarks for the second image. does anyone know why it does this? and how to fix it? again, it works only for the first image until it gets to the second one

**Comment by pkaske** [comment]
nevermind, i got it

**Comment by vandics** [comment]
could you give me information to fix it? I face this problem too

**Comment by funnypig521** [comment]
I meet the same problem.Could you give me some information?

**Comment by vandics** [comment]
you can visit my solution here https://github.com/google/mediapipe/issues/1803
