### ISSUE TITLE
Hand Tracking Desktop GPU Build Error

### ISSUE THREAD

**Issue by yujie-tao** [google/mediapipe#148]
When I try to run the following command in docker
`bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS \
    mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
`

I got the following error
```  ERROR: /root/mediapipe/mediapipe/gpu/BUILD:626:1: C++ compilation of rule '//mediapipe/gpu:gl_simple_shaders' failed (Exit 1) gcc failed: 
error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame
-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 29 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./mediapipe/gpu/gl_simple_shaders.h:18:0,
                 from mediapipe/gpu/gl_simple_shaders.cc:15:
./mediapipe/gpu/gl_base.h:57:10: fatal error: EGL/egl.h: No such file or directory
 #include <EGL/egl.h>
          ^~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 118.767s, Critical Path: 82.66s
INFO: 48 processes: 48 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

What may potentially cause this error?

**Comment by mcclanahoochie** [comment]
Desktop GPU support requires that you install EGL drivers for your video card. Have you followed the [instructions](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-debian-and-ubuntu) to install mesa drivers ? 
Also, what GPU do you have? It needs to have driver support for [EGL](https://en.wikipedia.org/wiki/EGL_(API)) libraries (provided by AMD/Nvidia/Mesa/etc..).

**Comment by yujie-tao** [comment]
Yes, I have installed the mesa and successfully built the program with the command mentioned above. 

However, when I tried to run
`bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu \
    --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt`

I still met the error of
```
I1005 01:50:13.447350  9350 demo_run_graph_main_gpu.cc:56] Initialize the calculator graph.
I1005 01:50:13.449132  9350 demo_run_graph_main_gpu.cc:60] Initialize the GPU.
E1005 01:50:13.584123  9350 demo_run_graph_main_gpu.cc:181] Failed to run the graph: ; Unable to initialize EGLpipe/gpu/gl_context_egl.cc:157)
```

Does that mean my GPU doesn't have support for EGL libraries? I used NVIDIA Tesla P4. 

I am pretty new to the use of GPU. Thanks for your answering.

**Comment by mcclanahoochie** [comment]
Are you running inside a Docker container? If so please see https://github.com/google/mediapipe/issues/150#issuecomment-539120064

**Comment by kme2698** [comment]
Hi, I'm also getting the same error, "Unable to initialize EGLpipe/gpu/gl_context_egl.cc:157)" on Ubuntu 16.04 (not docker) with Titan XP GPU.

**Comment by mcclanahoochie** [comment]
i'm assuming you have the mesa drivers installed... what about the nvidia drivers? are you using ones pre-installed, or updated ones from https://www.nvidia.com/Download/index.aspx ? that may make a difference.

also this is a long shot, but also try running
`export DISPLAY=:0`
before running the mediapipe example

**Comment by yujie-tao** [comment]
Thanks! I fixed the problem as I found my mesa driver is not properly installed.

**Comment by lvaptx4869** [comment]
> Thanks! I fixed the problem as I found my mesa driver is not properly installed.

I have met the same build issue on Ubuntu 18.04. could you tell me the path of your mesa lib? Thanks.

**Comment by AlexYiningLiu** [comment]
> Thanks! I fixed the problem as I found my mesa driver is not properly installed.

@yujie-tao I have the same problem as you. How did you install the mesa driver? I installed the 2 things mentioned on the GPU support page of mediapipe docs. Can you let me know how you solved the problem? Thanks.

**Comment by AlexYiningLiu** [comment]
> i'm assuming you have the mesa drivers installed... what about the nvidia drivers? are you using ones pre-installed, or updated ones from https://www.nvidia.com/Download/index.aspx ? that may make a difference.
> 

I have been running the gpu desktop app perfectly fine outside of docker. But I am encountering the same problem as @yujie-tao  when I run it within a docker container. How do I check the nvidia drivers installed and update them? Although I don't think that is exactly the issue.
