### ISSUE TITLE
Mali-GPU run much slower than Adreno-GPU in GPU mode

### ISSUE THREAD

**Issue by RamsleyJunting** [google/mediapipe#1480]
Dear mediapipe team,
I found that the same example app (e.g. hair segmentation gpu)  with same code deploy in phones with different GPU(e.g. OnePlus 6 with SMD-845 inside and HuaWei Mate 30 with Mali-G76 inside). No matter running in OpenGL/OpenCL backend or whether use advance gpu or not, there performance are totally different, the one with Mali GPU is running much slower than the one with adreno, have you notice such phenomenon, if so,  did you have explaination to it or advices to fix it.
Thank you and Best regards,
Ramsley

**Comment by duy-maimanh** [comment]
I dont know exactly answer for this question. But in my opinion. Because Adreno GPU on OnePlus is better performance than Mali GPU.

**Comment by RamsleyJunting** [comment]
I don't think that is the reson, because I also make a comparison of GPU inference time between them using CPU IO mode and the performance is the same.

**Comment by brucechou1983** [comment]
I guess the difference is introduced by tflite inference time. You can try to [benchmark](https://www.tensorflow.org/lite/performance/measurement) the model.

**Comment by impjdi** [comment]
@RamsleyJunting This is a bug that should be probably more adequate for TFLite GPU.  Anyway, this is a known issue, and we didn't get to improve Mali performance too much due to missing tooling or extensions, compared to what Qualcomm offers for Adreno.  We have prioritized Mali GPU performance for 2021, so hopefully we can close some gaps there, but there's nothing we can do immediately to address this.

**Comment by brucechou1983** [comment]
@impjdi I think this is a good news for MediaPipe & TFLite users. I'd inspected the generated shaders and found that workgroup parameters for Mali aren't as useful as them for Adreno. Some flagship phones like Samsung S10 (in Asia region, Mali-G72) could't even run face mesh app constantly in realtime (FPS>30).  If this could be improved, developers can build serious applications for public users with various kind of phones. Could you share more information about how google plan to address this issue?

**Comment by impjdi** [comment]
@brucechou1983 There are a handful of internal requests to improve performance on Mali that we can't ignore, so there'll some progress one way or the other.  However, it's uncertain which direction we will go (again, this is on the TFLite GPU side).  Switch to Vulkan?  Employ extensions we haven't explored?  Optimize shaders?  We don't know the final picture yet and can't give you an answer for now.
