### ISSUE TITLE
Portrait Segmentation Mediapipe

### ISSUE THREAD

**Issue by Nvelu048** [google/mediapipe#1481]
@mcclanahoochie 

Hi,

Is there is any plan on Portrait Segmentation in Mediapipe

**Comment by mcclanahoochie** [comment]
I don't think there is any plans to release a portrait segmentation example, but the Hair segmentation example in mediapipe has all the right ingredients, you just need to swap the hair model for a portrait model.

This user [demonstrates](https://towardsdatascience.com/custom-calculators-in-mediapipe-5a245901d595) just that, so hopefully that points you in the right direction.
