### ISSUE TITLE
How can i find if there is two hand present in a frame? Distinguish between Left and Right hand, Mediapipe Python

### ISSUE THREAD

**Issue by DharwishRaj** [google/mediapipe#1482]
Hey, 
I have been using this module for a project, using MediaPipe Hands Python package 
How can i find if there is two hand present in a frame? is there any variable that stores info of number of hands, if there how to call it inside an condition ? 
is there any way to distinguish between Left and Right hand ?
Thanks!

**Comment by jiuqiant** [comment]
How can i find if there is two hand present in a frame? Is there any variable that stores info of number of hands
num_hands_detected = len(results.multi_hand_landmarks)

Is there any way to distinguish between Left and Right hand?https://google.github.io/mediapipe/solutions/hands#multi_handedness is what you need.

**Comment by DharwishRaj** [comment]
Quick response! Thanks!

**Comment by abod2017** [comment]
> Hey, 
> 
> I have been using this module for a project, using MediaPipe Hands Python package 
> 
> How can i find if there is two hand present in a frame? is there any variable that stores info of number of hands, if there how to call it inside an condition ? 
> 
> is there any way to distinguish between Left and Right hand ?
> 
> Thanks!

Sl
