### ISSUE TITLE
Performance issue on a React Native app using @mediapipe/handpose 

### ISSUE THREAD

**Issue by romildojuliano** [google/mediapipe#1484]
Hi everyone.
I'm trying to develop an app to process sign language using React Native, Expo and @mediapipe/handpose, but the performance I get is too slow for what we need. The smartphone I'm testing with is the **Samsung Galaxy S9**, which is not at all a bad phone, and the FPS I get is around 2 ~ 6 fps; 
The process is very simple: I load the handpose model -> Then with the CameraWithTensors from TensorFlow Js React Native I can create a loop to process the frames from the smartphone camera -> Inside this loop I'm able to call the model.estimateHands();

But when the estimatehands method is called, even not rendering the camera, the performance drops absurdly, making it almost useless for what we want because we need to apply another model to process the points generated; from the examples I've seen at the mediapipe website, the results I'm getting are very uncongruent. Do you think the problem is being caused by my code? 
Here's a video on how it's looking like:

https://user-images.githubusercontent.com/33132257/104114231-c2d7b300-52e0-11eb-8f5f-294029ede81d.mp4

Here's some sample code:
![20210110_013138.jpg](https://user-images.githubusercontent.com/33132257/104114553-81e19d80-52e4-11eb-9a1e-d34d1c81dfa2.jpg)
![20210110_013402.jpg](https://user-images.githubusercontent.com/33132257/104114519-15669e80-52e4-11eb-9d30-456917d64605.jpg)
![20210110_013304.jpg](https://user-images.githubusercontent.com/33132257/104114580-b6555980-52e4-11eb-8a73-09c949b1e42a.jpg)

(Sending photos because, as you can see at the edit history I couldn't manage to format it properly 🤭)

**Comment by DanielWFrancis** [comment]
This is interesting. 

You're the only person I see online doing this in React Native, which I hope to do as well. [This comment](https://github.com/google/mediapipe/issues/587#issuecomment-610585088) is often referenced when people ask about it but the author doesn't know anything about React and it just references the existence of AARs for Android, while questions about how to access this in the javascript aren't answered.

Your solution seems to rely on just using the javascript libraries, which are promising to me, but your performance might be from some kind of hardware utilization limit? Maybe the AARs get around that?

Anyway, if you have any follow up findings I'd love to see them. I'm going to implement what you have here in my app and see how it does.

**Comment by shivaylamba** [comment]
@DanielWFrancis are there any examples of MediaPipe integration with React Native or any blogs?

**Comment by mhays-google** [comment]
I don't know of any blogs using React, and we are't officially supporting any collaboration with React.  But I can say that any work done within this tight loop is going to adversely affect performance.   My suggestion is to remove everything but the basic loop, adding steps one by one to see where the frame rate drops.

I'm interested in what you find, but I do need to close this as it isn't an actionable bug on our part.

**Comment by ver0z** [comment]
I tried it with Tensorflow Js and the performance was the same, it did not reach more than 6 FPS, I guess because of Native App does not need a bridge like React need [You can see it](https://medium.com/devcnairobi/how-does-react-native-actually-its-work-538dd224e0dd). So it will afect the [FPS](https://medium.com/swlh/flutter-vs-native-vs-react-native-examining-performance-31338f081980) and like I said, now I'm using Java and is getting 16 FPS, better than a poke in the eye.
