### ISSUE TITLE
Mismatch at using Tfhub model handskeleton and TensorFlowJs-React-Native

### ISSUE THREAD

**Issue by romildojuliano** [google/mediapipe#1485]
Hi everyone, it's me again.
I tried using a model updated yesterday (09/01/2020) called **handskeleton**, but when I tried to inject the photos retrieved from TensorFlowJs-React-Native CameraWithTensors method this is what I got: 
![Screenshot_20210110-004032_Expo.jpg](https://user-images.githubusercontent.com/33132257/104114640-704cc580-52e5-11eb-91ed-ba57eb26df54.jpg)
Any hint on this?

**Comment by sgowroji** [comment]
Closing this issue as we don't support it in MediaPipe. Please reach us, your use case with complete details and MediaPipe usage on it. Thanks!
