### ISSUE TITLE
Multihand tracking CPU: getting landmarks

### ISSUE THREAD

**Issue by prantoran** [google/mediapipe#1486]
Hello, is there a way to get landmarks using CPU version for Desktop in Linux? I tried a lot but could not add output stream poller for landmarks when using the calculators for cpu multihand tracking. I am getting the following error:

```
Failed to run the graph: ; Unable to attach observer to output stream "multi_hand_landmarks" because it doesn't exist.
```

**Comment by mcclanahoochie** [comment]
Can you share the graphs?

`multi_hand_landmarks` is inside a subgraph, and would need to be propagated all the way to the Main graph (by adding the output stream at the top of the graph). The poller can only see into the top level graph.

**Comment by prantoran** [comment]
Ah I was able to get the landmarks using `hand_landmarks` instead after reviewing the currently used graph config file `mediapipe/graphs/hand_tracking/hand_tracking_desktop_live_gpu.pbtxt `.

**Comment by KanzaSheikh** [comment]
@prantoran hello, can you explain what did you edit in order to make it work? I am getting the same error

**Comment by prantoran** [comment]
@KanzaSheikh I modified the function ` OutputStreamPollerImpl::Next()` in `mediapipe/framework/graph_output_stream.cc`:

```
bool OutputStreamPollerImpl::Next(Packet* packet) {
  CHECK(packet);
  bool empty_queue = true;
  Timestamp min_timestamp = Timestamp::Unset();
  // mutex_.Lock();
  int _cnt = 5;

  // std::cerr << "entered mp/framework/graph_output_stream.cc pollarimpl::Next()\n";
  // bool _set = false;
  while (true) {
    min_timestamp = input_stream_->MinTimestampOrBound(&empty_queue);
    // std::cerr << "_cnt inside:" << _cnt <<  "\tempty_queue:" << empty_queue << "\n"; 
    if (empty_queue) _cnt --;
    if (!_cnt) break;

    if (graph_has_error_ || !empty_queue ||
        min_timestamp == Timestamp::Done()) {
        // _set = true;
      break;
    } else {
      // handler_condvar_.Wait(&mutex_);
    }
  }
  // std::cerr << "next() cnt:" << _cnt << "\n";
  if ((graph_has_error_ && empty_queue)) {
    // mutex_.Unlock();
    return false;
  }

  if (!_cnt) {
    // mutex_.Unlock();
    return false;
  }

  // mutex_.Unlock();
  if (min_timestamp == Timestamp::Done()) {
    return false;
  }
  int num_packets_dropped = 0;
  bool stream_is_done = false;
  *packet = input_stream_->PopPacketAtTimestamp(
      min_timestamp, &num_packets_dropped, &stream_is_done);
  CHECK_EQ(num_packets_dropped, 0)
      << absl::Substitute("Dropped $0 packet(s) on input stream \"$1\".",
                          num_packets_dropped, input_stream_->Name());
  return true;
}
```

**Comment by prantoran** [comment]
@KanzaSheikh There is a [gist](https://gist.github.com/eknight7/d4a57504c8f866fc80c0eb2c61ff6b4f#file-multi_hand_tracking_run_graph_cpu_main-cc-L67
) by @eknight7 for getting landmarks for CPU

You have to change `kMultiHandLandmarksOutputStream` from `multi_hand_landmarks` to `hand_landmarks` in line [38](https://gist.github.com/eknight7/d4a57504c8f866fc80c0eb2c61ff6b4f#file-multi_hand_tracking_run_graph_cpu_main-cc-L38).

**Comment by KanzaSheikh** [comment]
Alright, thank you for answering! @prantoran

**Comment by kodosexe** [comment]
> You have to change kMultiHandLandmarksOutputStream from multi_hand_landmarks to hand_landmarks in line [38](https://gist.github.com/eknight7/d4a57504c8f866fc80c0eb2c61ff6b4f#file-multi_hand_tracking_run_graph_cpu_main-cc-L38).

Note that `kMultiHandLandmarksOutputStream` now only needs to be `landmarks`.
