### ISSUE TITLE
android problem

### ISSUE THREAD

**Issue by chenti2x** [google/mediapipe#1492]
log:
java.lang.RuntimeException: Unable to get provider androidx.camera.camera2.impl.Camera2Initializer: java.lang.NumberFormatException: For input string: "/dev/video15"

Hello：
What is the problem with this log？

thank you very much！！！

**Comment by jiuqiant** [comment]
It seems that androidx.camera.camera2 doesn't work with your device. It seems that you use a dev board?

**Comment by chenti2x** [comment]
@jiuqiant
yes，use a dev board. May I  do this and how can I do?

**Comment by jiuqiant** [comment]
Sorry for the late reply. This is a compatibility issue between camerax and your dev board. I suggest reaching out to the camerax authors for such questions.
