### ISSUE TITLE
Overlaying 3d object using tensorflow "face-landmarks-detection" ML model

### ISSUE THREAD

**Issue by SKY378537** [google/mediapipe#1496]
We are trying to build a web AR application using Tensorflow.js by leveraging tensorflow  "face-landmarks-detection" machine learning model. We are able to get the 468 face landmark and trying to overlay 3d object on face like glasses but unable to render glasses on facemesh. We also looked into mediapipe but did not find appropriate solution for java script (web).
	
Any response will be highly appreciated.

**Comment by mahlm** [comment]
Also trying to figure this out, is it possible to get the face mesh data with the transformation matrix using the Javascript API?This will make it a lot easier to use in ThreeJS or BabylonJS.

**Comment by simon-lanf** [comment]
The javascript API for Mediapipe FaceMesh seems to currently only offer X and Y coordinates. The python version has the Z. Here is more information: https://google.github.io/mediapipe/solutions/face_mesh#javascript-solution-api

**Comment by sgowroji** [comment]
Hi @SKY378537, Have you tried looking with face detection [javascript](https://codepen.io/mediapipe/full/dyOzvZM) solutions. Please reach us if you still have any further queries. Thanks!
