### ISSUE TITLE
Support for guestures with hand back facing camera

### ISSUE THREAD

**Issue by Leffe108** [google/mediapipe#1497]
I read the hand model is using a palm detector to speed up detection. That explains why it is bad at detecting the hand when the back is facing the camera.

However ..

# Use case - Swedish Sign Language (SSL)
In Swedish sign language many letters in the alphabet have the back of the hand facing the camera (or at least what English language call the back of the hand). For example our [W](https://teckensprakslexikon.su.se/ord/11943) is the same as W in ASL but the hand reversed 180 degrees. When doing this gesture it is clear that the model perform much better on ASL W with the front facing camera than with SSL W. In ASL W I can move the hand back and forth and the tracking is very accurate, but with SSL W there are spots where it tracks the hand but many spots where it doesn't.

Another letter of trouble is [R](https://teckensprakslexikon.su.se/ord/11938) which in SSL is the same hand shape as an offensive sign but we usually sign it upside down as shown in the link)

A full list of alphabet signs in Swedish sign language can be found at [lexicon](https://teckensprakslexikon.su.se/kategori/handalfabetet?page=2).

# Problem
It is not that the tracking of the back completely malfunctions - it work to some extent, but one have to have annotation visible on webcam window and carefully position your hand to get it to register your hand correctly. Compared to when you show the front of the hand with a W for example and can move the hand around at the tracking solidly follows your hand.

# Suggestion
It would be useful if MediaPipe also supported tracking what in English is called the back of the hand which in some cultures/languages is regarded as the front.

**Comment by sgowroji** [comment]
Hi @Leffe108, Could you please respond if you still see the same observation,  even with the latest release. Thanks!

**Comment by Leffe108** [comment]
In the [release notes](https://github.com/google/mediapipe/releases) there is no improvements of the hand model mentioned from 0.8.2 to current 0.8.7. Especially no specific mention of improvement to back of hand detection in either hand or holistic model.

In version 0.8.4 there is however a mention that the holistic model has a new configuration `model_complexity` to make it more accurate (by loosing latency) which I haven't tried yet if that improve accuracy for back of hand facing camera. I'll report back when I have checked it out.

**Comment by Leffe108** [comment]
Wow, sorry if I was skeptical, but it has indeed improved a lot from 0.8.2 to 0.8.7. Thank you. :-) 

There are now mostly three letters of problem: P, Q and X. But letters like R, V and W that was a problem before has improved a lot.
