### ISSUE TITLE
how to make Face Beautification with facemash ? for example enlarge the lips

### ISSUE THREAD

**Issue by ShahmirJlavyan** [google/mediapipe#1498]

**Comment by eknight7** [comment]
@ablavatski, please take a look, thank you.

**Comment by kostyaby** [comment]
Hey @ShahmirJlavyan,

Virtual face enhancement is a fairly broad domain as well as an advanced one. Building even a basic filter might take up to a week and requires prior experience with image processing and/or graphics. Thus one Github comment is definitely not enough to cover the topic entirely, however I'll share some pointers for you to start with though :) Most of the techniques don't require a face mesh tech, although having the tech could help you to improve the quality (i.e. only apply the retouching filter inside a face contour, etc.). I'd recommend using OpenCV image processing functionality to first develop a face retouching filter in either Python or C++; it has all the basics covered to build a prototype pretty quickly. Once you have a filter working without face tracking - this is a good point for you to start integrating a face tracker to improve visual quality 

- Basic lip enlarging could be done with Liquify filter:
  - [Snap Studio visual tutorial](https://lensstudio.snapchat.com/templates/face/distort/)
  - [Blog about details of Liquify filter implementation in JS](https://geekofficedog.blogspot.com/2015/01/liquify-effect-hello-swirl-2.html)
  - [Github with JS code (would need to be ported to OpenCV)](https://github.com/higuaro/liquify-tool)
- Basic skin smoothing can be done with Bilateral filter:
  - [Relevant StackOverflow answer](https://stackoverflow.com/a/7113757)
  - [OpenCV API](https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#ga9d7064d478c95d60003cf839430737ed)

I'll be closing this issue as I don't see a concrete deliverable for the MediaPipe Team in the context of this broad domain / question other than sharing those initial pointers. If you have a question about OpenCV - please, reach out for help on that library's issue tracker / StackOverflow. Also feel free to re-open this issue if you believe we can help you with anything MediaPipe-related!

Have a great day! ☀️
