### ISSUE TITLE
plam_detection output 

### ISSUE THREAD

**Issue by u0251077** [google/mediapipe#1499]
![image](https://user-images.githubusercontent.com/17065425/104264842-5965c900-54c7-11eb-9fcc-ef3e6e6994e5.png)

I use the netron see the model
but I don't understand output meaning.
In regressors output is 1* 2944* 18 (2944 is anchor numbers )
(18 is coords in the doc.)
but coords why has 18 numbers?
x y w h ? only 4

**Comment by fanzhanggoogle** [comment]
Hi, each anchor has (x, y, w, h) offsets for the box and and (x, y) for 7 keypoints each, thus 4 + 2 * 7 = 18.

**Comment by jiuqiant** [comment]
If we read [the graph](https://github.com/google/mediapipe/blob/2b58cceec9953f0d97059934f0de85dd60adbe9b/mediapipe/modules/palm_detection/palm_detection_cpu.pbtxt#L85), we can find that the InferenceCalculator is followed by a TensorsToDetectionsCalculator. The tensors to detections decoding is done in this calculator. The tensors are converted to bbox and keypoints at https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tensor/tensors_to_detections_calculator.cc#L991 and https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tensor/tensors_to_detections_calculator.cc#L996.

**Comment by u0251077** [comment]
fanzhanggoogle and jiuqiant thank you.
I understand finally.

**classificators output** generate each hand probability with anchors, then we can find the compliant anchors.
Find the best **anchor index** using nms.
Use anchor.csv find corresponding **center x,y** for hand.
Use the best index **regressors output** find the corresponding x,y offset, plam bbox size and 7 keypoint offset in hand.

(If there is an error, please advise)
**Schematic diagram**
![image](https://user-images.githubusercontent.com/17065425/104674293-5a446800-571e-11eb-994d-59fb179d0a6c.png)

**Comment by 20XYSong** [comment]
@u0251077 Hallo, thanks for your explanation. I wonder how to get the anchor.csv file.

**Comment by u0251077** [comment]
@20XYSong I reference this
https://github.com/metalwhale/hand_tracking/blob/master/models/anchors.csv

**Comment by 20XYSong** [comment]
Thank you very much. I've already read this repo. But I want get the anchor.csv of recent palm detection model, where the output details show that output_shape becomes 'array([   1, 2016,   18])'. You can get this info by loading 'palm_detection_full.tflite' is mediapipe python package.

**Comment by VimalMollyn** [comment]
For people that are looking for a csv of new  SSD anchors, I've attached the file [here](https://github.com/VimalMollyn/GenMediaPipePalmDectionSSDAnchors), along with code to generate it. Thanks @saknarak for your snippets!

https://github.com/VimalMollyn/GenMediaPipePalmDectionSSDAnchors
