### ISSUE TITLE
develop procedure

### ISSUE THREAD

**Issue by milad-4274** [google/mediapipe#1500]
Hi, I'm new to mediapipe, I want to create a simple android application by changing mediapipe examples. I think there are 2 options:

1. Change graphs and calculators, then build android app with bazel.
2. Change graphs and calculators, then generate .binarypb file, then use it in android app and build with gradle.

Challenges:
1. for the first option, I have api_level problem! minimum supported api_level for building with bazel is 28 that is not compatible with my cell phone (api_level=27)
2. for the second option, as much as I change he graph and generate binarypb file, it wouldn't reflect in app that built by gradle, but when I build the same graph with bazel, it work.

is there any option for my purpose? or any solution for my challenges?
Thank you.

**Comment by yangcheng** [comment]
for 2, you need to build an aar, and import the aar file to gradle project, see https://google.github.io/mediapipe/getting_started/android_archive_library.html
