### ISSUE TITLE
Where is "landmark_java_proto_lite" defined?

### ISSUE THREAD

**Issue by Epitapher** [google/mediapipe#1502]
The pose tracking example depends on `"//mediapipe/framework/formats:landmark_java_proto_lite"` but I couldn't find it in `//mediapipe/framework/formats/BUILD`, only `landmark_proto` is there. So where is `landmark_java_proto_lite` defined? Is there a special rule? Thanks!

**Comment by jiuqiant** [comment]
The `landmark_proto` target at https://github.com/google/mediapipe/blob/master/mediapipe/framework/formats/BUILD#L251 is a `mediapipe_proto_library`, which will be expanded to multiple language specific targets. The Java Proto Lite is part of the  mediapipe_proto_library rule:
https://github.com/google/mediapipe/blob/master/mediapipe/framework/port/build_config.bzl#L110. Hope this explanation helps.
