### ISSUE TITLE
There is a question about model texture

### ISSUE THREAD

**Issue by z7212819** [google/mediapipe#1503]
Hello, I have a question now. I want to know the matching form between uuu model and model texture. I have been able to convert obj model into uuu model, but I don't know how texture is applied to the transformed uuu model. How do you apply texture to uuu model? After I convert obj to uuu, I can't see the UV information of the original obj model. This problem has been bothering me for a long time. Please help me to have a look. Thank you.

**Comment by tyrmullen** [comment]
The texture itself will just be passed separately throughout the graph as an "ImageFrame" object.  But the mapping of texture to model is part of the .uuu format.  Specifically, the .uuu format should have everything needed from the .obj: vertex positions (3d), texture coordinate positions (2d, normalized [0,1]), and then indices into those first two lists (3 at a time, to represent triangles).  Some more details can be found at https://github.com/google/mediapipe/issues/1074, where I hope to consolidate all information on this format, so closing this issue as duplicate.
