### ISSUE TITLE
Jetson NX build mediapipe python binding error

### ISSUE THREAD

**Issue by HelloWord2020** [google/mediapipe#1504]
Followed the instruction below to build mediapipe python binding on Jetson NX( Jetpack 4.4 Ubuntu 18.04).

https://google.github.io/mediapipe/getting_started/python.html

But on Step 6: (mp_env)mediapipe$ python3 setup.py bdist_wheel

I got this:

INFO: Analyzed target //mediapipe/python:_framework_bindings.so (121 packages loaded, 11697 targets configured).
INFO: Found 1 target...
ERROR: /home/h17/Desktop/mediapipe/mediapipe/python/BUILD:19:17: Linking of rule '//mediapipe/python:_framework_bindings.so' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/aarch64-opt/bin/mediapipe/python/_framework_bindings.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: error: cannot find -lImath
/usr/bin/ld.gold: error: cannot find -lIlmImf
/usr/bin/ld.gold: error: cannot find -lIex
/usr/bin/ld.gold: error: cannot find -lHalf
/usr/bin/ld.gold: error: cannot find -lIlmThread
/usr/bin/ld.gold: error: cannot find -lavresample
collect2: error: ld returned 1 exit status
Target //mediapipe/python:_framework_bindings.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 132.686s, Critical Path: 124.55s

what did i miss? Anyone meet this problem before? Thank you in advance!

**Comment by jiuqiant** [comment]
In [the official documentation](https://google.github.io/mediapipe/getting_started/python.html#building-mediapipe-python-package), we refer to https://github.com/jiuqiant/mediapipe_python_aarch64 for Nvidia Jetson and Raspberry Pi users. Do you follow [this instruction](https://github.com/jiuqiant/mediapipe_python_aarch64/blob/main/README.md) step by step?  You can try https://github.com/jiuqiant/mediapipe_python_aarch64/blob/main/mediapipe-0.8.1-cp38-cp38-linux_aarch64.whl first to save your time.

**Comment by HelloWord2020** [comment]
Thanks for your help! I have followed your  steps: https://github.com/jiuqiant/mediapipe_python_aarch64

The last step when i tried to install ' python3 -m pip install mediapipe-0.8.1-cp38-cp38-linux_aarch64.whl'. The xxxxx.whl was downloaded from the link above. 

Got ERROR: mediapipe-0.8.1-cp38-cp38-linux_aarch64.whl is not a supported wheel on this platform.

**Comment by HelloWord2020** [comment]
thank you! @jiuqiant  I followed your steps and succeed install python on Jetsson NX.

But i got another problem while  i ran the C++ demo **hand_tracking**: https://google.github.io/mediapipe/getting_started/cpp

Build and Running on CPU version works good. GPU version build succeed, but failed while running:

**error:**
I20210116 23:13:55.087340  2449 demo_run_graph_main_gpu.cc:51] Get calculator graph config contents: # MediaPipe graph that performs multi-hand tracking with TensorFlow Lite on GPU.
# Used in the examples in
# mediapipe/examples/android/src/java/com/mediapipe/apps/handtrackinggpu.

# GPU image. (GpuBuffer)
input_stream: "input_video"

# Max number of hands to detect/process. (int)
input_side_packet: "num_hands"

# GPU image. (GpuBuffer)
output_stream: "output_video"
# Collection of detected/predicted hands, each represented as a list of
# landmarks. (std::vector<NormalizedLandmarkList>)
output_stream: "hand_landmarks"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  #input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Detects/tracks hand landmarks.
node {
  calculator: "HandLandmarkTrackingGpu"
  input_stream: "IMAGE:throttled_input_video"
  #input_side_packet: "NUM_HANDS:num_hands"
  output_stream: "LANDMARKS:hand_landmarks"
  output_stream: "HANDEDNESS:handedness"
  output_stream: "PALM_DETECTIONS:palm_detections"
  output_stream: "HAND_ROIS_FROM_LANDMARKS:hand_rects_from_landmarks"
  output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:hand_rects_from_palm_detections"
}

# Subgraph that renders annotations and overlays them on top of the input
# images (see hand_renderer_gpu.pbtxt).
node {
  calculator: "HandRendererSubgraph"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "DETECTIONS:palm_detections"
  input_stream: "LANDMARKS:hand_landmarks"
  input_stream: "HANDEDNESS:handedness"
  input_stream: "NORM_RECTS:0:hand_rects_from_palm_detections"
  input_stream: "NORM_RECTS:1:hand_rects_from_landmarks"
  output_stream: "IMAGE:output_video"
}
I20210116 23:13:55.090817  2449 demo_run_graph_main_gpu.cc:57] Initialize the calculator graph.
E20210116 23:13:55.100675  2449 demo_run_graph_main_gpu.cc:186] Failed to run the graph: ValidatedGraphConfig Initialization failed.
FlowLimiterCalculator: ; (num_data_streams)>=(1)apipe/calculators/core/flow_limiter_calculator.cc:80)

**Comment by HelloWord2020** [comment]
Hi @jiuqiant ,

I reinstalled the mediapipe, two C++ demos and python binding both worked fine on the Jetson NX. I am not sure what i missed. But anyway, thanks very much for your help!

**Comment by jiuqiant** [comment]
Glad to hear that. I am going to close this issue.
