### ISSUE TITLE
Sometime showing black screen during starting of hand tracking

### ISSUE THREAD

**Issue by shivammaindola** [google/mediapipe#1508]
This is how I'm trying to start hand tracking, This is happening 1/3 times. Am I missing something in the code?

`  public void startHandTracking() {
        stopCameraX();
  
        cameraBinding.facePopUp.setVisibility(View.GONE);
        cameraBinding.mediapipePopup.setVisibility(View.VISIBLE);
        previewDisplayView = new SurfaceView(context);
        //startCamera();
        setupPreviewDisplayView();
        AndroidAssetUtil.initializeNativeAssetManager(context);

        converter = new ExternalTextureConverter(eglManager.getContext());
        converter.setFlipY(true);
        converter.setConsumer(processor);
        startCamera();

        eglManager = new EglManager(null);
        processor =
                new FrameProcessor(
                        context,
                        eglManager.getNativeContext(),
                        Constant.BINARY_GRAPH_NAME,
                        Constant.INPUT_VIDEO_STREAM_NAME,
                        Constant.OUTPUT_VIDEO_STREAM_NAME);
        processor.getVideoSurfaceOutput().setFlipY(Constant.FLIP_FRAMES_VERTICALLY);

        AndroidPacketCreator packetCreator = processor.getPacketCreator();
        Map<String, Packet> inputSidePackets = new HashMap<>();
        inputSidePackets.put(Constant.INPUT_NUM_HANDS_SIDE_PACKET_NAME, packetCreator.createInt32(Constant.NUM_HANDS));
        processor.setInputSidePackets(inputSidePackets);

        processor.addPacketCallback(
                Constant.OUTPUT_LANDMARKS_STREAM_NAME,
                (packet) -> {

                    Log.v("nklsdhg", "Received multi-hand landmarks packet.");
                    List<LandmarkProto.NormalizedLandmarkList> multiHandLandmarks =
                            PacketGetter.getProtoVector(packet, LandmarkProto.NormalizedLandmarkList.parser());
                    Log.v(
                            "nklsdhg",
                            "[TS:"
                                    + packet.getTimestamp()
                                    + "] "
                                    + getMultiHandLandmarksDebugString(multiHandLandmarks));
                     //   });
                   // }
                });

    }

    private void setupPreviewDisplayView() {

        previewDisplayView.setVisibility(View.VISIBLE);
        cameraBinding.previewDisplayLayout.addView(previewDisplayView);

        previewDisplayView
                .getHolder()
                .addCallback(
                        new SurfaceHolder.Callback() {

                            @Override
                            public void surfaceCreated(SurfaceHolder holder) {
                                processor.getVideoSurfaceOutput().setSurface(holder.getSurface());
                            }

                            @Override
                            public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {

                                Log.d("lvnsdbs", "surfaceChanged: "+holder);

                                    Size viewSize = new Size(width, height);
                                    displaySize = cameraHelper.computeDisplaySizeFromViewSize(viewSize);

                                    if(displaySize!=null&&previewFrameTexture!=null)
                                    converter.setSurfaceTextureAndAttachToGLContext(
                                            previewFrameTexture, displaySize.getWidth(), displaySize.getHeight());

                            }

                            @Override
                            public void surfaceDestroyed(SurfaceHolder holder) {
                                processor.getVideoSurfaceOutput().setSurface(null);
                                //cameraHelper.stopCameraX((Activity)context);
                            }
                        });
    }

 private void startCamera() {

        cameraHelper = new CameraXPreviewHelper();
        cameraHelper.setOnCameraStartedListener(
                surfaceTexture -> {
                    //ViewGroup viewGroup = (ViewGroup)previewDisplayView.getParent();
                    cameraBinding.previewDisplayLayout.removeView(previewDisplayView);
                    cameraBinding.previewDisplayLayout.addView(previewDisplayView);
                    previewFrameTexture = surfaceTexture;
                    // Make the display view visible to start showing the preview. This triggers the
                    // SurfaceHolder.Callback added to (the holder of) previewDisplayView.
                    previewDisplayView.setVisibility(View.VISIBLE);

                });
     
        cameraHelper.startCamera(fragmentActivity, Constant.CAMERA_FACING, /*surfaceTexture=*/ null);

    }
`

**Comment by ivan-grishchenko** [comment]
@gkarpiakt Seems like and Android question. Could you please take a look?

**Comment by ignacioberdinas** [comment]
Hi @ivan-grishchenko , I had the same problem and I arrived to a fix but I don't know if it is the correct solution.

To diagnose the issue I tried many things. At last what worked was enabling debug logs and comparing the logs for the runs where the tracking started as expected and the runs where the screen was black. I realized the log that indicates that the External Texture Converter created a frame was not getting emitted when the black screen was happening.

Line 275 ExternalTextureConverter.class is not getting executed
`Log.d("ExternalTextureConv", String.format("Created output texture: %d width: %d height: %d", destinationTextureId, this.destinationWidth, this.destinationHeight));`

Following the code backwards this means that the onFrameAvailable method is not executing (this is the notification from CameraXPreviewHelper that the frame is available).

So to confirm this theory on the startCamera I setted the OnFrameAvailableListener to the surfaceTexture provided by the camera to a simple function that logs the event. 
`
    private fun startCamera() {
        cameraHelper = CameraXPreviewHelper()
        cameraHelper!!.setOnCameraStartedListener { surfaceTexture: SurfaceTexture? ->
            previewFrameTexture = surfaceTexture
            if (surfaceTexture != null) {  
                surfaceTexture.setOnFrameAvailableListener { <------ Added code
                    Log.e(TAG, "Frame available") 
                }
            }
            // Make the display view visible to start showing the preview. This triggers the
            // SurfaceHolder.Callback added to (the holder of) previewDisplayView.
            previewDisplayView.visibility = View.VISIBLE
        }
        cameraHelper!!.startCamera(activity, CAMERA_FACING,  /*surfaceTexture=*/null)
    }
`

The expected output is that when calling `converter.setSurfaceTextureAndAttachToGLContext` the converter should replace my listener and the log should never be called. But what happened is that when the screen is black my "Frame available" log is executed, this means that the converter is failing to set the OnFrameAvailableListener. 

My interpretation is that the converter is not setting the listener fast enough and that it ¿looses? the onFrameAvailable call so it never initializes. (I'm not sure this is what is happening

My fix was to add a call to update the texture image to the most recent frame of the camera stream just after doing the  `converter.setSurfaceTextureAndAttachToGLContext` . I guess this calls again the onFrameAvailable so the rest of the process initializes correctly. There are some warnings that updateTexImage() has to be called from the same thread that contains the texture object so I'm not sure my fix is thread safe, but it is working.

`                        converter!!.setSurfaceTextureAndAttachToGLContext(
                            previewFrameTexture,
                            if (isCameraRotated) displaySize.height else displaySize.width,
                            if (isCameraRotated) displaySize.width else displaySize.height)
                        previewFrameTexture!!.updateTexImage()`



A bit of context from my project:
- It is running the full body pose detection model so I don't think this is related to the specific hand tracking solution
- My code is running in the context of a Flutter PlatformView, as I integrated mediapipe into my original flutter project. This may be the cause of the issue?
- Most of the code is copied from here https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java

**Comment by smooth-crescendo** [comment]
@ignacioberdinas, Thank you so much! I've been trying to fix this for sooo long

**Comment by ForLovelj** [comment]
Maybe it's better to call it here
```
public void setSurfaceTextureAndAttachToGLContext(
            SurfaceTexture texture, int width, int height) {
            setSurfaceTexture(texture, width, height);
            int[] textures = new int[1];
            GLES20.glGenTextures(1, textures, 0);
            surfaceTexture.attachToGLContext(textures[0]);
            // Update texture image
            surfaceTexture.updateTexImage();
        }
```

**Comment by mirwisek** [comment]
> Hi @ivan-grishchenko , I had the same problem and I arrived to a fix but I don't know if it is the correct solution.
> 
> To diagnose the issue I tried many things. At last what worked was enabling debug logs and comparing the logs for the runs where the tracking started as expected and the runs where the screen was black. I realized the log that indicates that the External Texture Converter created a frame was not getting emitted when the black screen was happening.
> 
> Line 275 ExternalTextureConverter.class is not getting executed
> `Log.d("ExternalTextureConv", String.format("Created output texture: %d width: %d height: %d", destinationTextureId, this.destinationWidth, this.destinationHeight));`
> 
> Following the code backwards this means that the onFrameAvailable method is not executing (this is the notification from CameraXPreviewHelper that the frame is available).
> 
> So to confirm this theory on the startCamera I setted the OnFrameAvailableListener to the surfaceTexture provided by the camera to a simple function that logs the event.
> 
> ```
>     private fun startCamera() {
>         cameraHelper = CameraXPreviewHelper()
>         cameraHelper!!.setOnCameraStartedListener { surfaceTexture: SurfaceTexture? ->
>             previewFrameTexture = surfaceTexture
>             if (surfaceTexture != null) {  
>                 surfaceTexture.setOnFrameAvailableListener { <------ Added code
>                     Log.e(TAG, "Frame available") 
>                 }
>             }
>             // Make the display view visible to start showing the preview. This triggers the
>             // SurfaceHolder.Callback added to (the holder of) previewDisplayView.
>             previewDisplayView.visibility = View.VISIBLE
>         }
>         cameraHelper!!.startCamera(activity, CAMERA_FACING,  /*surfaceTexture=*/null)
>     }
> ```
> 
> The expected output is that when calling `converter.setSurfaceTextureAndAttachToGLContext` the converter should replace my listener and the log should never be called. But what happened is that when the screen is black my "Frame available" log is executed, this means that the converter is failing to set the OnFrameAvailableListener.
> 
> My interpretation is that the converter is not setting the listener fast enough and that it ¿looses? the onFrameAvailable call so it never initializes. I'm not sure this is what is happening
> 
> My fix was to add a call to update the texture image to the most recent frame of the camera stream just after doing the `converter.setSurfaceTextureAndAttachToGLContext` . I guess this calls again the onFrameAvailable so the rest of the process initializes correctly. There are some warnings that updateTexImage() has to be called from the same thread that contains the texture object so I'm not sure my fix is thread safe, but it is working.
> 
> ```
>  converter!!.setSurfaceTextureAndAttachToGLContext(previewFrameTexture,
>                             if (isCameraRotated) displaySize.height else displaySize.width,
>                             if (isCameraRotated) displaySize.width else displaySize.height)
> previewFrameTexture!!.updateTexImage()
> ```
> 
> A bit of context from my project:
> 
> * It is running the full body pose detection model so I don't think this is related to the specific hand tracking solution
> * My code is running in the context of a Flutter PlatformView, as I integrated mediapipe into my original flutter project. This may be the cause of the issue?
> * Most of the code is copied from here https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java

I tried the same didn't work out for me. I added `previewFrameTexture!!.updateTexImage()` at the end of `onPreviewDisplaySurfaceChanged` so the complete method is:

```
protected fun onPreviewDisplaySurfaceChanged(
        holder: SurfaceHolder?, format: Int, width: Int, height: Int
    ) {
        // (Re-)Compute the ideal size of the camera-preview display (the area that the
        // camera-preview frames get rendered onto, potentially with scaling and rotation)
        // based on the size of the SurfaceView that contains the display.
        val viewSize = computeViewSize(width, height)
        val displaySize = cameraHelper!!.computeDisplaySizeFromViewSize(viewSize)
        val isCameraRotated = cameraHelper!!.isCameraRotated

        // Connect the converter to the camera-preview frames as its input (via
        // previewFrameTexture), and configure the output width and height as the computed
        // display size.
        converter!!.setSurfaceTextureAndAttachToGLContext(
            previewFrameTexture,
            if (isCameraRotated) displaySize.height else displaySize.width,
            if (isCameraRotated) displaySize.width else displaySize.height
        )
        // HERE
        previewFrameTexture!!.updateTexImage()
    }
```

In the logs I'm receiving 
```
I/native: I20210627 12:51:07.848115 17707 jni_util.cc:41] GetEnv: not attached
I/native: I20210627 12:51:07.878353 17710 jni_util.cc:41] GetEnv: not attached
I/native: I20210627 12:51:07.912703 17711 jni_util.cc:41] GetEnv: not attached
I/native: I20210627 12:51:08.145076 17708 jni_util.cc:41] GetEnv: not attached
I/native: I20210627 12:51:08.445899 17706 jni_util.cc:41] GetEnv: not attached
```

Not sure what am I doing wrong, here?

**Comment by ravikumar-ramamurthy** [comment]
I added in setSurfaceTextureAndAttachToGLContext as suggested in the above [comment](https://github.com/google/mediapipe/issues/1508#issuecomment-812390364) and it worked for me.

**Comment by sgowroji** [comment]
Hi @shivammaindola, Could you please respond if you still see the above error with the latest release. Thanks

**Comment by shivammaindola** [comment]
@sgowroji I stopped working on this. Thanks for your help.
