### ISSUE TITLE
JS Pose solution error inside Web Worker

### ISSUE THREAD

**Issue by jjeon5** [google/mediapipe#1509]
When working within a dedicated Web Worker, the pose.send function throws an error inside a minified function "Q" looking for a global window variable. Looking at the minified code, there seems to be Web Worker related code that handles the global context with the globalThis property, but maybe it handles it incorrectly. Any chance someone can confirm this error? 
(Tested on Safari)
<img width="469" alt="Screen Shot 2021-01-16 at 6 53 38 PM" src="https://user-images.githubusercontent.com/5896086/104808878-63235f80-582c-11eb-8032-c78e73703d7f.png">

**Comment by jjeon5** [comment]
Any updates? Would love to see it work inside a Web Worker!

**Comment by mhays-google** [comment]
Our code is written so that the graphs work in the main window, however, we can definitely rig a lot of this up so that it does not rely on the window object.  I'm distracted at the moment, but I want to at least tell you that I've seen this and that I will look at it.

**Comment by sgowroji** [comment]
Hi @jjeon5, Could you please test the above with the  latest release and let us know if you still see the same error. Thanks!
