### ISSUE TITLE
Hand Tracking Multiple Hands

### ISSUE THREAD

**Issue by pranay-agra** [google/mediapipe#151]
Hey,

In your blog, you released a hand-tracking model. In the blog, it mentioned scalability to multiple hands. How do you enable this on the software as it is currently only tracking one hand? I am not too well versed with Mediapipe / hand-tracking, so an in-depth explained answer would be perfect!

Thanks

**Comment by mgyong** [comment]
Duplicate of #32 We don't support this currently

**Comment by mgyong** [comment]
@eknight7 FYI
We will update this issue in the future once we have support

**Comment by mgyong** [comment]
@pranay-agra With the new release https://github.com/google/mediapipe/releases/tag/v0.6.4, we have multi-hand tracking examples:

https://github.com/google/mediapipe/blob/master/mediapipe/docs/multi_hand_tracking_mobile_gpu.md
https://github.com/google/mediapipe/blob/master/mediapipe/docs/multi_hand_tracking_desktop.md
