### ISSUE TITLE
how to read images in python version

### ISSUE THREAD

**Issue by Evelyn233** [google/mediapipe#1511]
in the python solution api
for idx, file in enumerate(file_list):  I have no idea about what the file_list is , what the format the file_list is and where can I access it.

**Comment by Leffe108** [comment]
It is a list of strings with file names/path.

Eg `["images/a.jpg", "images/b.jpg"]`

**Comment by jiuqiant** [comment]
> It is a list of strings with file names/path.
> 
> Eg `["images/a.jpg", "images/b.jpg"]`

Thank you for answering this!

**Comment by adarshx11** [comment]
how can i access folder of images 
file_list  = ['','','']????

**Comment by jiuqiant** [comment]
> how can i access folder of images
> file_list = ['','','']????

Not sure I fully understand your question. The file path is the file system location of an image file. You ask python to read files from the system locations.
