### ISSUE TITLE
Get 3d face mesh coordinates using JavaScript API

### ISSUE THREAD

**Issue by davitgoder** [google/mediapipe#1513]
Hello, I managed to get translation information from landmarks but I need rotation as well, how to go about it?
I think I need to either access [this](https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_geometry) API or manually recover rotation, which way you would suggest?
Thanks.

**Comment by simon-lanf** [comment]
Also, the documentation is currently not cleat and implies that the javascript SDK should get the z coordinates foe every points, just like the python one.

**Comment by mzwtjp** [comment]
Sorry to jump in:

I am currently trying holistic.js and its results.faceLandmarks array does not contain z coordinates (only x and y are available), and not it does not match what is described on the doc.

>FACE_LANDMARKS
>A list of 468 face landmarks. Each landmark consists of x, y and z. 

Is it just me trying out a bit old holistic.js (I downloaded this a few weeks ago), or is it still an issue to be fixed soon?

**Comment by MapleShaw** [comment]
any updates ?

**Comment by sgowroji** [comment]
Request to go through the useful reference https://github.com/google/mediapipe/issues/2673#issuecomment-946113076
