### ISSUE TITLE
Failed to run hand tracking gpu: Side packet "num_hands" is required but was not provided.

### ISSUE THREAD

**Issue by thunder95** [google/mediapipe#1518]
**Followed the tutorial, it worked quite well with cpu. But when I used GPU, it raised the error:**

**Build Info:**
bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
>   mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
INFO: Build options --copt and --define have changed, discarding analysis cache.
WARNING: Download from https://mirror.bazel.build/github.com/Maratyszcza/FP16/archive/4dfe081cf6bcd15db339cf2680b9281b8451eeb3.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/094e692629d57ddb932fcc993193626f60daa61b.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/Maratyszcza/pthreadpool/archive/77f9d3bcfabd1bdb910dd33b549d5290b968ef05.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/Maratyszcza/FXdiv/archive/63058eff77e11aa15bf531df5dd34395ec3017c8.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/Maratyszcza/psimd/archive/072586a71b55b7f8c584153d223e95687148a900.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu (0 packages loaded, 6497 targets configured).
INFO: Found 1 target...
INFO: From Compiling mediapipe/calculators/tensor/inference_calculator.cc:
In file included from external/opencl_headers/CL/cl.h:32:0,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:42,
                 from ./mediapipe/util/tflite/tflite_gpu_runner.h:25,
                 from mediapipe/calculators/tensor/inference_calculator.cc:47:
external/opencl_headers/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
INFO: From Executing genrule //mediapipe/modules/palm_detection:palm_detection_gpu_graph:
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:324] Warning parsing text-format mediapipe.CalculatorGraphConfig: 60:5: text format contains deprecated field "use_gpu"
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu up-to-date:
  bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu
INFO: Elapsed time: 150.262s, Critical Path: 57.54s
INFO: 2189 processes: 4 internal, 2185 linux-sandbox.
INFO: Build completed successfully, 2189 total actions

**ERROR INfO:**

> GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu \
> >   --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt
> I20210119 15:06:04.919020 25197 demo_run_graph_main_gpu.cc:51] Get calculator graph config contents: # MediaPipe graph that performs multi-hand tracking with TensorFlow Lite on GPU.
> # Used in the examples in
> # mediapipe/examples/android/src/java/com/mediapipe/apps/handtrackinggpu.
> 
> # GPU image. (GpuBuffer)
> input_stream: "input_video"
> 
> # Max number of hands to detect/process. (int)
> input_side_packet: "num_hands"
> 
> # GPU image. (GpuBuffer)
> output_stream: "output_video"
> # Collection of detected/predicted hands, each represented as a list of
> # landmarks. (std::vector<NormalizedLandmarkList>)
> output_stream: "hand_landmarks"
> 
> # Throttles the images flowing downstream for flow control. It passes through
> # the very first incoming image unaltered, and waits for downstream nodes
> # (calculators and subgraphs) in the graph to finish their tasks before it
> # passes through another image. All images that come in while waiting are
> # dropped, limiting the number of in-flight images in most part of the graph to
> # 1. This prevents the downstream nodes from queuing up incoming images and data
> # excessively, which leads to increased latency and memory usage, unwanted in
> # real-time mobile applications. It also eliminates unnecessarily computation,
> # e.g., the output produced by a node may get dropped downstream if the
> # subsequent nodes are still busy processing previous inputs.
> node {
>   calculator: "FlowLimiterCalculator"
>   input_stream: "input_video"
>   input_stream: "FINISHED:output_video"
>   input_stream_info: {
>     tag_index: "FINISHED"
>     back_edge: true
>   }
>   output_stream: "throttled_input_video"
> }
> 
> # Detects/tracks hand landmarks.
> node {
>   calculator: "HandLandmarkTrackingGpu"
>   input_stream: "IMAGE:throttled_input_video"
>   input_side_packet: "NUM_HANDS:num_hands"
>   output_stream: "LANDMARKS:hand_landmarks"
>   output_stream: "HANDEDNESS:handedness"
>   output_stream: "PALM_DETECTIONS:palm_detections"
>   output_stream: "HAND_ROIS_FROM_LANDMARKS:hand_rects_from_landmarks"
>   output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:hand_rects_from_palm_detections"
> }
> 
> # Subgraph that renders annotations and overlays them on top of the input
> # images (see hand_renderer_gpu.pbtxt).
> node {
>   calculator: "HandRendererSubgraph"
>   input_stream: "IMAGE:throttled_input_video"
>   input_stream: "DETECTIONS:palm_detections"
>   input_stream: "LANDMARKS:hand_landmarks"
>   input_stream: "HANDEDNESS:handedness"
>   input_stream: "NORM_RECTS:0:hand_rects_from_palm_detections"
>   input_stream: "NORM_RECTS:1:hand_rects_from_landmarks"
>   output_stream: "IMAGE:output_video"
> }
> I20210119 15:06:04.920377 25197 demo_run_graph_main_gpu.cc:57] Initialize the calculator graph.
> I20210119 15:06:04.924736 25197 demo_run_graph_main_gpu.cc:61] Initialize the GPU.
> I20210119 15:06:04.941694 25197 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
> I20210119 15:06:04.997416 25228 gl_context.cc:324] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 440.100)
> I20210119 15:06:04.997540 25197 demo_run_graph_main_gpu.cc:67] Initialize the camera or load the video.
> I20210119 15:06:05.337213 25197 demo_run_graph_main_gpu.cc:88] Start running the calculator graph.
> E20210119 15:06:05.351466 25197 demo_run_graph_main_gpu.cc:196] Failed to run the graph: ValidateRequiredSidePackets failed to validate: 
> ; Side packet "num_hands" is required but was not provided.

**Comment by thunder95** [comment]
I followed this guide (https://google.github.io/mediapipe/getting_started/cpp.html), where showed incorrect pbtx. solved!

**Comment by Daniel2193** [comment]
the graph config file has to be changed from 

`mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt`

to

`mediapipe/graphs/hand_tracking/hand_tracking_desktop_live_gpu.pbtxt`

The correct run command should be

`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu \
  --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live_gpu.pbtxt`
