### ISSUE TITLE
inference time for desktop hand tracking

### ISSUE THREAD

**Issue by loompa** [google/mediapipe#152]
I'd like to ask if somebody can share the inference time of desktop hand tracking, preferably on cpu :)

There was a demo https://github.com/wolterlw/hand_tracking by walterlw (also many thanks) before you released new desktop features, the speed was not very high because, I guess, tflite optimised for mobiles,
just curious if wolterlw's results approx. the same as mediapipe's

Btw, I really appreciate your project!

**Comment by mcclanahoochie** [comment]
```
bazel build --define='MEDIAPIPE_DISABLE_GPU=1' -c opt mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt
```
try the above commands.. what performance do you get? 
what performance does the example you link get?

mine is not too bad on cpu (pretty interactive), but is buttery smooth on gpu (hyper realtime).

the performance one gets depends **_highly_** on the hardware tested on (cpu/memory/os/etc...).

**Comment by loompa** [comment]
Thank you very much for your answer! 
I've met some mistakes trying to run mediapipe's examples both on ubuntu server (as I don't have gui and webcam access) and on mac (strange building errors), of course that's my problems :)) and could be solved, just want to know if inference time worth trying :)))

the mentioned example gave me around 4-5 FPS (AMD Ryzen Threadripper 2920X 12-Core)

**Comment by JECBello** [comment]
@mcclanahoochie Hello! I'm running the GPU desktop version of hand tracking however inference still seems very slow. I was hoping I could ask you what GPU you are using? I'm using an NVIDIA GPU and I'm concerned that there might be a compatibility issue with the Mesa drivers.

**Comment by loompa** [comment]
finally was able to run both mediapipe's cpu and gpu examples, cpu run also about 5 fps on my laptop, gpu pretty fast (GeForce 940MX)

the mentioned demo (in my first comment) doesn't have some postprocessing as mediapipe  :)
