### ISSUE TITLE
'pose_landmark_full_body.tflite' failed to load

### ISSUE THREAD

**Issue by erizmr** [google/mediapipe#1520]
- Description
The model [pose_landmark_full_body.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_full_body.tflite) provided in `mediapipe/mediapipe/modules/pose_landmark/pose_landmark_full_body.tflite` failed to load. The error messages are shown below:
![image](https://user-images.githubusercontent.com/33411325/105019802-6beb7f80-5a3e-11eb-854f-1bbdbadfd44c.png)

The model graph looks weird, there are only 'add' operations everywhere.  Hope anyone can help this. Thanks!
<img src="https://user-images.githubusercontent.com/33411325/105020294-077cf000-5a3f-11eb-98cd-8372ea887370.png" width="500" >

- To reproduce
```
import numpy as np
import tensorflow as tf

interp = tf.lite.Interpreter('./pose_landmark_full_body.tflite')
interp.allocate_tensors()

in_idx = interp.get_input_details()[0]['index']
interp.set_tensor(in_idx, np.random.sample([1,256,256,3]).astype('float32'))
interp.invoke()
```
- Others

The model [pose_landmark_upper_body.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_upper_body.tflite) works well using the same code above.

**Comment by xzqjack** [comment]
Same error. But The pose_upper_body_landmark.tflite is all right.

**Comment by impjdi** [comment]
Sorry for the belated response.  Is this still an issue with the latest MediaPipe release?  I bubbled this up a couple months back and should have been fixed.

**Comment by sgowroji** [comment]
Hi @erizmr, Could you please confirm whether you facing the above issue still  exists with the latest build. Thanks!

**Comment by erizmr** [comment]
Hi @sgowroji , thanks for getting back to me and sorry for the late reply. I have tested the model with the latest build and the issue has been well sorted I think.
