### ISSUE TITLE
Companion website minor security/accessibility issue

### ISSUE THREAD

**Issue by matanster** [google/mediapipe#1524]
It may seem like https://viz.mediapipe.dev/ is [not configured to serve a sufficiently complete chain of certificates for it's certificate](https://security.stackexchange.com/a/243550/102051) as per what I understand to be a best practice.

**Comment by MaRauder111** [comment]
I am also having the same issue with chrome. It works fine on other browser. I need to clean chrome and start again.

**Comment by sgowroji** [comment]
Hi @matanster, Could you please respond whether you facing the above error with the latest build. Thanks!

**Comment by matanster** [comment]
Looks fine now
