### ISSUE TITLE
handtrackinggpu does not work properly on Xiaomi 11

### ISSUE THREAD

**Issue by c1139676919** [google/mediapipe#1527]
https://user-images.githubusercontent.com/43144608/105150908-48a8f900-5b40-11eb-9dcd-2580bfeda373.mp4

When running the company project, switch to Xiaomi 11 can not operate properly, and then try the official Google demo also can not identify the hand, what is the problem? @jiuqiant

**Comment by c1139676919** [comment]
I tried hairsegmentationgpu, facedetectiongpu and faceeffect again and none of them worked.

**Comment by mcclanahoochie** [comment]
can you provide the logcat output?

**Comment by c1139676919** [comment]
> 您可以提供logcat输出吗？

Sorry to get back to you now, because the company's phone configuration is relatively low, so borrowed next to a colleague's Xiaomi 11 to test, only to find the problem, the camera captures the picture after no key points, so now there is no log to be able to give you.

**Comment by mcclanahoochie** [comment]
i'm not sure we can help much if there is no logcat to see :/ 

maybe try the latest version ? https://github.com/google/mediapipe/releases

i'm closing this for now, but you can re-open once you can provide some more logging info

thanks
