### ISSUE TITLE
Do you have a higher end more accurate model then tflight that you can release? Stability jitter remains in these models.

### ISSUE THREAD

**Issue by delebash** [google/mediapipe#1529]
Someone mentioned that you had a higher end models for mediapipe that tflite.  I am grateful for what you have release but the stability of these models are not good enough to use in production for my needs.  I would like to use mediappe hands.pose, face, and iris for motion capture animating a 3D character.  The results I can produce with your applications are not at a quality level that would be useful.  If not a better dataset do you have any other means to improve stability enough for quality motion capture.

The specific problem I am having is the jitter in the detection results.  The actual capturing of the hands works well enough it is that the data is not stable enough.  Please look at this video of an example of what I am trying to achieve and you notice the jitter.  I do not mean the detection problems but the small jitter you see in the fingers even in an open palm position.  Thanks

The left hand is not working yet so ignore that it is not moving the characters hand.

https://www.youtube.com/watch?v=j6JboJIlpfM

Thanks!

**Comment by simon-lanf** [comment]
Can you reproduce the issue outside of your app, on a demo example of mediapipe made by them ? just so we can exclude an implementation error.

**Comment by delebash** [comment]
Here is a link from the mediapipe site demonstrating the javascript version which has the same problem.  https://codepen.io/mediapipe/pen/RwGWYJw.  Thanks for looking into this.

**Comment by simon-lanf** [comment]
I get a similar result with FaceMesh as you do. It's like there is a rounding error or something.

**Comment by kuaashish** [comment]
Hello @delebash,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
