### ISSUE TITLE
handtrackinggpu build error

### ISSUE THREAD

**Issue by johniao** [google/mediapipe#153]
I got "404" error at Fetching @org_tensorflow when I run "bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handdetectiongpu" 
I tried many times...
Any help greatly appreciated!

**Comment by johniao** [comment]
sometimes the error maybe "no such package" or "Read timed out".
Any help? Thanks!

**Comment by mgyong** [comment]
@johniao I assume you are in china? This is likely a VPN networking issue

**Comment by johniao** [comment]
yes，It is vpn network problem！ Thank you!

**Comment by johniao** [comment]
It is vpn network problem！
