### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by chenj133** [google/mediapipe#1533]
OS:centos8
python vision:3.7.4

when I run "pip install mediapipe"

Collecting mediapipe
  Could not find a version that satisfies the requirement mediapipe (from versions: )
No matching distribution found for mediapipe
You are using pip version 19.0.3, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

how can I install mediapipe on centos with pip

**Comment by jiuqiant** [comment]
Is it x86_64 or arm64 centos? MeidaPipe Python doesn't provide arm64 wheels yet. You can build it locally by following https://google.github.io/mediapipe/getting_started/python#building-mediapipe-python-package.

I started a clean x86_64 centos8 instance on Google Cloud and the MediaPipe installation looks fine.

```
$ cat /etc/*-release
CentOS Linux release 8.3.2011
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
CentOS Linux release 8.3.2011
CentOS Linux release 8.3.2011

$ sudo python3 -m pip install --upgrade pip
WARNING: Running pip install with root privileges is generally not a good id
ea. Try `__main__.py install --user` instead.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/54/eb/4a3642e971f404d6
9d4f6fa3885559d67562801b99d7592487f1ecc4e017/pip-20.3.3-py2.py3-none-any.whl
 (1.5MB)
    100% |████████████████████████████████| 1.5MB 726kB/s 
Installing collected packages: pip
Successfully installed pip-20.3.3

$ sudo python3 -m pip install --upgrade pip
WARNING: Running pip install with root privileges is generally not a good id
ea. Try `__main__.py install --user` instead.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/54/eb/4a3642e971f404d6
9d4f6fa3885559d67562801b99d7592487f1ecc4e017/pip-20.3.3-py2.py3-none-any.whl
 (1.5MB)
    100% |████████████████████████████████| 1.5MB 726kB/s 
Installing collected packages: pip
Successfully installed pip-20.3.3
$ python3 -m pip install mediapipe
Defaulting to user installation because normal site-packages is not writeabl
e
Collecting mediapipe
  Downloading mediapipe-0.8.2-cp36-cp36m-manylinux2014_x86_64.whl (35.0 MB)
     |████████████████████████████████| 35.0 MB 1.0 MB/s 
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from
 mediapipe) (1.11.0)
```

**Comment by afogel** [comment]
I'm having the same issue -- I'm using Python3.9 on MacOS 10.15.5. I had installed it, but for some reason it's not working now.

**Comment by jiuqiant** [comment]
> I'm having the same issue -- I'm using Python3.9 on MacOS 10.15.5. I had installed it, but blew away my environment and when I tried to reinstall, it's not working now.
> 
> UPDATE: It works with 3.8, not 3.9

Yes, we currently don't have wheel for python 3.9 yet. We support python 3.6 to 3.8.
