### ISSUE TITLE
Closed eyes are not trackable in python API

### ISSUE THREAD

**Issue by fogside** [google/mediapipe#1538]
Hi!
I noticed that in .tflite version which goes with python API eyes on the predicted face mesh never seem to be closed if I close my eyes. In contrast, in the [tf.js demo](https://www.npmjs.com/package/@tensorflow-models/face-landmarks-detection) I see that closed eyes are captured quite well.
It would be nice to know if it's a known issue and maybe some tips on how to address it with .tflite version.
Example of closed eyes in tf.js demo.
![image](https://user-images.githubusercontent.com/6944359/105405057-5f7c4800-5c33-11eb-812a-5ae58d3492db.png)

**Comment by impjdi** [comment]
I'm not too familiar with the TF.js demo, but according to the description on the page you linked, it mentions something about `irisModelUrl` which might be integrated into the demo.  On MediaPipe's face landmark demo graph, I don't see any place where you could insert a refinement model like that.  So maybe that's the difference?

**Comment by fogside** [comment]
> I'm not too familiar with the TF.js demo, but according to the description on the page you linked, it mentions something about `irisModelUrl` which might be integrated into the demo. On MediaPipe's face landmark demo graph, I don't see any place where you could insert a refinement model like that. So maybe that's the difference?

Hey! I'm also not a js developer, but I found this in their code and I think this may be the possible reason for the difference:

https://github.com/tensorflow/tfjs-models/blob/1b3aaa72225baa58b87e24a6f8a9124a5bbda4cd/face-landmarks-detection/src/mediapipe-facemesh/pipeline.ts#L383

**Comment by sgowroji** [comment]
Hi @fogside, Could you please respond if you still looking any resolutions for the above query. Thanks!

**Comment by fogside** [comment]
Hi! @sgowroji! I think it's fine to close the issue.

**Comment by sahil-dhuri** [comment]
m too trying to detect close eyes and opened eyes as i have trained model for it in jupyter n its giving negative for close eyes and positive value for open but its for the image...video capture its only accepting positive value in python
