### ISSUE TITLE
error whten  bazel build

### ISSUE THREAD

**Issue by mrlihellohorld** [google/mediapipe#1539]
Hi, Thank you very much for your team to open this project, but I in execute the command: 
bazel build - c opt - define MEDIAPIPE_DISABLE_GPU = 1 mediapipe/examples/desktop/autoflip: run_autoflip, 
But i got some errors: 

WARNING: Download from https://github.com/tensorflow/tensorflow/archive/0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 180eac4d78eeed081d9e2c889ce473fa103e1838b205f152994208aac0ce3d0f but wanted b0861a19381fd15e128a5a1437acfe4a368b841738d63306fbeceedc220696e0
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz] to /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz: Checksum was 180eac4d78eeed081d9e2c889ce473fa103e1838b205f152994208aac0ce3d0f but wanted b0861a19381fd15e128a5a1437acfe4a368b841738d63306fbeceedc220696e0
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz] to /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz: Checksum was 180eac4d78eeed081d9e2c889ce473fa103e1838b205f152994208aac0ce3d0f but wanted b0861a19381fd15e128a5a1437acfe4a368b841738d63306fbeceedc220696e0

could u help me?thanks a lot

**Comment by NguyenLong-02** [comment]
You should try this method : https://github.com/google/mediapipe/issues/581

**Comment by mrlihellohorld** [comment]
I'm running in a Docker environment, so even if Ubuntu is using a VPN, Docker won't be able to access the Internet scientifically.I used the method of manually downloading the files in the workspace and then building the shared server of the LAN.
