### ISSUE TITLE
sync project

### ISSUE THREAD

**Issue by wxs19920926** [google/mediapipe#154]
Error:(127, 19) Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/f93a117bf26ccd1d4d6929188e887fc7/external/com_google_protobuf_javalite/protobuf.bzl", line 122
		rule(attrs = {"srcs": attr.label_list...()}, <2 more arguments>)
	File "/root/.cache/bazel/_bazel_root/f93a117bf26ccd1d4d6929188e887fc7/external/com_google_protobuf_javalite/protobuf.bzl", line 127, in rule
		attr.label(cfg = "host", executable = True, sin..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.

**Comment by jiuqiant** [comment]
Do you follow the [install.md](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#setting-up-android-studio-with-mediapipe) to set your project view?

The error message already gives the solution to solve this issue by saying that "You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.". If you set the project view correctly, Android Studio should read the [.bazelrc file](https://github.com/google/mediapipe/blob/master/.bazelrc#L16), which already set incompatible_disable_deprecated_attr_params=false.

If there is still a problem, please let us know your OS, bazel version, and the Android studio version.
