### ISSUE TITLE
how to get camera characteristic of the camera used in handtracking android app?

### ISSUE THREAD

**Issue by Aprameyah** [google/mediapipe#1541]
I need to get the focal length and sensor dimensions of the camera used in the android application, please provide a solution.
Can [MainActivity](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java) be edited to get the above mentioned characteristics ?

**Comment by eknight7** [comment]
You can see how we get these characteristics in https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/CameraXPreviewHelper.java#L391-L405.
Please see docs about https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics to get more data.
