### ISSUE TITLE
Error building file mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking/instantmotiontracking_symbols/R.txt: 

### ISSUE THREAD

**Issue by sunithapremjee** [google/mediapipe#1544]
#### System information

AndroidStudio: 4.1.2
Platform: Windows 10 10.0
Bazel plugin: 2021.01.06.0.1
Bazel: 3.7.2

#### Description of the issue. 
ERROR: C:/users/sunit/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking/BUILD:72:15: 
Couldn't build file mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking/instantmotiontracking_symbols/R.txt: 
Processing Android resources for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking failed (Exit 1):
 ResourceProcessorBusyBox.exe failed: error executing command bazel-out/x64_windows-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/
devtools/build/android/ResourceProcessorBusyBox.exe ... 
(remaining 1 argument(s) skipped)
Jan 24, 2021 5:19:53 PM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
SEVERE: Error during processing
java.lang.RuntimeException: Error during Linking C:\Users\sunit\AppData\Local\Temp\android_resources_tmp3771972670929820436\manifest-processed\AndroidManifest.xml:
Command: external\androidsdk\build-tools\30.0.3\aapt2.exe\
	link\
	--no-version-vectors\
	--no-static-lib-packages\
	--manifest\
	C:\Users\sunit\AppData\Local\Temp\android_resources_tmp3771972670929820436\manifest-processed\AndroidManifest.xml\
	--auto-add-overlay\
	--proto-format\
	--debug-mode\
	--custom-package\
	com.google.mediapipe.apps.instantmotiontracking\
	-A\
	bazel-out\x64_windows-fastbuild\bin\mediapipe\examples\android\src\java\com\google\mediapipe\apps\instantmotiontracking\
	-A\
	bazel-out\x64_windows-fastbuild\bin\mediapipe\graphs\instant_motion_tracking\
	-A\
	mediapipe\examples\android\src\java\com\google\mediapipe\apps\instantmotiontracking\assets\
	-A\
	mediapipe\examples\android\src\java\com\google\mediapipe\apps\instantmotiontracking\assets\
	-A\
	mediapipe\examples\android\src\java\com\google\mediapipe\apps\instantmotiontracking\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_loader_loader\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_customview_customview\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_savedstate_savedstate\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_activity_activity\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_viewpager_viewpager\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_interpolator_interpolator\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_legacy_legacy_support_core_utils\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_slidingpanelayout_slidingpanelayout\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_cursoradapter_cursoradapter\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_coordinatorlayout_coordinatorlayout\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_asynclayoutinflater_asynclayoutinflater\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_swiperefreshlayout_swiperefreshlayout\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_drawerlayout_drawerlayout\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_media_media\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_fragment_fragment\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_legacy_legacy_support_core_ui\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_vectordrawable_vectordrawable\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_vectordrawable_vectordrawable_animated\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_appcompat_appcompat_resources\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_annotation_annotation_experimental\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_exifinterface_exifinterface\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_camera_camera_core\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_legacy_legacy_support_v4\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_appcompat_appcompat\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_camera_camera_camera2\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_camera_camera_lifecycle\assets\
	-A\
	bazel-out\android-armeabi-v7a-fastbuild\bin\external\maven\_aar\unzipped\assets\androidx_recyclerview_recyclerview\assets\
	-A\

####

**Comment by homuler** [comment]
I think building apks on windows is not supported yet.

https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows

> Note: building MediaPipe Android apps is still not possible on native Windows. Please do this in WSL instead and see the WSL setup instruction in the next section.
