### ISSUE TITLE
doc error

### ISSUE THREAD

**Issue by antiviruser** [google/mediapipe#1547]
![image](https://user-images.githubusercontent.com/1140105/105812262-cc536180-5fe8-11eb-982c-b16fd05c629d.png)

**Comment by hadon** [comment]
Thanks antiviruser, this doc has been updated in the google repository and the update will appear in the next release of mediapipe on github.  The intro has been changed to:

"Calculators communicate by sending and receiving packets. Typically a single packet is sent along each input stream at each input timestamp. A packet can contain any kind of data, such as a single frame of video or a single integer detection count."
