### ISSUE TITLE
Request for tensorflow(not tflite) models with weights.

### ISSUE THREAD

**Issue by kulievvitaly** [google/mediapipe#155]
Could you please share initial tensorflow or keras models? 

It will allow the use of transfer learning. For example, gesture recognition or the use of a RGBD sensor for more accurate results.

**Comment by mgyong** [comment]
@kulievvitaly Pls see my comment in another related issue 
https://github.com/google/mediapipe/issues/13#issuecomment-514286492

**Comment by kulievvitaly** [comment]
The question is about tensorflow neural networks and weights, not about datasets.

**Comment by mgyong** [comment]
@kulievvitaly We released the tflite binary with weights. We do not release saved models for hand models
