### ISSUE TITLE
Mac OS build sample project gots error in run_shell: 'command' must be of type string.

### ISSUE THREAD

**Issue by Whisperd130** [google/mediapipe#1551]
I have followed the guide from [here](https://google.github.io/mediapipe/getting_started/ios.html).
And in step _Create an Xcode project_ I gots error when generate Xcode project in Tulsi.

`ERROR: /private/var/tmp/_bazel_WSS/341c7a1b1e6f92d91b86ac96639fb2bf/external/build_bazel_rules_apple/tools/realpath/BUILD:9:14: in _apple_genrule_inner rule @build_bazel_rules_apple//tools/realpath:realpath_genrule: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_WSS/341c7a1b1e6f92d91b86ac96639fb2bf/external/build_bazel_apple_support/rules/apple_genrule.bzl", line 78, column 28, in _apple_genrule_impl
		apple_support.run_shell(
	File "/private/var/tmp/_bazel_WSS/341c7a1b1e6f92d91b86ac96639fb2bf/external/build_bazel_apple_support/lib/apple_support.bzl", line 326, column 26, in _run_shell
		ctx.actions.run_shell(**_kwargs_for_apple_platform(ctx, **kwargs))
Error in run_shell: 'command' must be of type string. passing a sequence of strings as 'command' is deprecated. To temporarily disable this check, set --incompatible_run_shell_command_string=false.
ERROR: Analysis of target '//mediapipe/examples/ios/handdetectiongpu:HandDetectionGpuApp' failed; build aborted: Analysis of target '@build_bazel_rules_apple//tools/realpath:realpath_genrule' failed
General failure: Bazel aspects could not be built.`

Anyone gots Ideas? 
Thanks.

Edit: My bazel vesion is 4.0.0 and Xcode version is 12.4(12D4e).

**Comment by GuoLiuFang** [comment]
ERROR: /private/var/tmp/_bazel_guoliufang/1dc5e918fe6d75565b3f1dcef4b70a00/external/build_bazel_rules_apple/tools/realpath/BUILD:9:14: in _apple_genrule_inner rule @build_bazel_rules_apple//tools/realpath:realpath_genrule: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_guoliufang/1dc5e918fe6d75565b3f1dcef4b70a00/external/build_bazel_apple_support/rules/apple_genrule.bzl", line 78, column 28, in _apple_genrule_impl
		apple_support.run_shell(
	File "/private/var/tmp/_bazel_guoliufang/1dc5e918fe6d75565b3f1dcef4b70a00/external/build_bazel_apple_support/lib/apple_support.bzl", line 326, column 26, in _run_shell
		ctx.actions.run_shell(**_kwargs_for_apple_platform(ctx, **kwargs))
Error in run_shell: 'command' must be of type string. passing a sequence of strings as 'command' is deprecated. To temporarily disable this check, set --incompatible_run_shell_command_string=false.
ERROR: Analysis of target '//mediapipe/examples/ios/facedetectioncpu:FaceDetectionCpuApp' failed; build aborted: Analysis of target '@build_bazel_rules_apple//tools/realpath:realpath_genrule' failed
General failure: Bazel aspects could not be built.

++++++++++++++++++++++++++++++++
bazel --version
bazel 4.0.0-homebrew


same problem

**Comment by piyushtank** [comment]
Ran into the same problem, any workaround / solution for this problem?

```
ERROR: /private/var/tmp/_bazel_ptank/<PATH>/external/build_bazel_rules_apple/tools/realpath/BUILD:9:14: in _apple_genrule_inner rule @build_bazel_rules_apple//tools/realpath:realpath_genrule: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_ptank/<PATH>/external/build_bazel_apple_support/rules/apple_genrule.bzl", line 78, column 28, in _apple_genrule_impl
                apple_support.run_shell(
        File "/private/var/tmp/_bazel_ptank/<PATH>/external/build_bazel_apple_support/lib/apple_support.bzl", line 326, column 26, in _run_shell
                ctx.actions.run_shell(**_kwargs_for_apple_platform(ctx, **kwargs))
Error in run_shell: 'command' must be of type string. passing a sequence of strings as 'command' is deprecated. To temporarily disable this check, set --incompatible_run_shell_command_string=false.
ERROR: Analysis of aspect '@tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect of //mediapipe/examples/ios/helloworld:HelloWorldApp' failed; build aborted: Analysis of target '@build_bazel_rules_apple//tools/realpath:realpath_genrule' failed
General failure: Bazel aspects could not be built.
```

bazel --version
bazel 4.0.0-homebrew

I am running Xcode 12.4

**Comment by Neopallium** [comment]
Here is how I got MediaPipe to build on MacOS Catalina.

Add these lines to the `.bazelrc` file (in the root folder of the project):
```
# run_shell fix (maybe only needed for bazel 4.0?)
build --incompatible_run_shell_command_string=false

# Set python path.  Make sure to use the same python install as the pip used to instead the required modules (numpy, six)
build --action_env=PYTHON_BIN_PATH=/usr/local/bin/python3.9
```

Also I had to force the use of bazel 3.7.x instead of 4.0, because of bazel build errors with `proto_library` rules.  The easiest way is to use `bazelisk` and create a `.bazeliskrc` file in the root folder:
```
USE_BAZEL_VERSION=3.7.2
```

**Comment by jude253** [comment]
I am on MacOS Big Sur and I am not able to get MediaPipe to build.  I downloaded bazelisk, and I am going to try what you have said @Neopallium.

**Comment by akuehnert123** [comment]
For all asking themself how to downgrade the bazel homebrew version -> [Downgrade with brew](https://stackoverflow.com/questions/57759299/how-to-install-an-older-version-of-bazel-using-homebrew)

**Comment by pjbaron** [comment]
Thanks @Neopallium that worked for me using Big Sur.

brew unlink bazel
brew install bazelisk

Then your modifications to the two rc files

**Comment by sgowroji** [comment]
We are closing this issue as we don't see in the latest release.

**Comment by jude253** [comment]
Hey thanks for trying to help guys, I was not able to get bazel to build on my computer, and I went with a different technology.  Sorry, I did not update earlier.
