### ISSUE TITLE
Android crash when releasing resources

### ISSUE THREAD

**Issue by ForLovelj** [google/mediapipe#1555]
When I use the Pose demo, the call processor.close() app crash.Mabey The crash  happen in mediapipeGraph.tearDown()

**Comment by hadon** [comment]
If you can, please suggest a way for us to reproduce this crash.  Or if you can reproduce the crash, please capture the crash error message and describe any details of your programming environment that might be relevant to this crash.  Thanks.

**Comment by ForLovelj** [comment]
Device1:  MIUI12,Android10 ->crash.log
Device2:  EMUI11,Android10 ->crash2.log
[crash.txt](https://github.com/google/mediapipe/files/5897171/crash.txt)
[crash2.txt](https://github.com/google/mediapipe/files/5897172/crash2.txt)

I used the code in the pose demo and added an A page to jump to MainActivity.A crash occurs when you close MainActivity and return to A by calling processor.close() to release resources

**Comment by ForLovelj** [comment]
The error occurs when there are multiple instances of FrameProcessor in different Activities.
