### ISSUE TITLE
MediaPipe AAR File Generation

### ISSUE THREAD

**Issue by Neeraj1108Yadav** [google/mediapipe#1556]
Hello Developers

I am new to MediaPipe Framework. I went through their documentation setup and installation guide for **opencv@3, bazel, homebrew**. I did everything and I'm also able compile and execute their Hello World CPP file. 

Now I want to generate AAR file of **face_detection**. Again I followed each and every step mentioned in their guide, but now I am stuck at a point where **local repository of opencv@3 is not able to fetch**.

I am working in MacOS Catalina -v 10.15.7

Please help me on this.

ERROR: /Users/rajeevkumar/Desktop/Android/mediapipe/third_party/BUILD:178:6: //third_party:opencv_binary depends on @macos_opencv//:opencv in repository @macos_opencv which failed to fetch. no such package '@macos_opencv//': The repository's path is "/usr/local/opt/opencv@3" (absolute: "/usr/local/opt/opencv@3") but this directory does not exist.
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar' failed; build aborted: Analysis failed
<img width="818" alt="Screenshot 2021-01-29 at 2 17 34 PM" src="https://user-images.githubusercontent.com/34931349/106252867-c05fdd80-623c-11eb-843a-71e271b85151.png">

**Comment by jiuqiant** [comment]
Can you find where the opencv3 library is? The path is supposed to be "/usr/local/opt/opencv@3" if it's installed by homebrew. You can find something like the following:

```
$ ls /usr/local/opt/opencv@3
INSTALL_RECEIPT.json	README.md		include			share
LICENSE			bin			lib
$ ls /usr/local/opt/opencv@3/include
opencv	opencv2
```

**Comment by Neeraj1108Yadav** [comment]
@jiuqiant Thanks for your suggestion. I am able to generate the aar file.

**Comment by Neeraj1108Yadav** [comment]
Closing this one. Thanks
