### ISSUE TITLE
Media pipe with unity

### ISSUE THREAD

**Issue by dhanajik** [google/mediapipe#1557]
Hi

Thank you very much in advance.

I am trying to use media pipe with unity using AAR file and .so file but it is failing to load the classes into unity.

I want to use media pipe with unity in a single apk file.

Please provide some lead of document that will help me to achieve this.

Thanks,
Dk

**Comment by jsaon-L** [comment]
Maybe this project can help you
https://github.com/homuler/MediaPipeUnityPlugin
