### ISSUE TITLE
How can I add a new node option in graph?

### ISSUE THREAD

**Issue by MaRauder111** [google/mediapipe#1558]
I want to add new `node_options` in the [graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.pbtxt).

Example :
```
# Converts normalized rects to drawing primitives for annotation overlay.
node {
  calculator: "RectToRenderDataCalculator"
  input_stream: "NORM_RECTS:multi_palm_rects"
  output_stream: "RENDER_DATA:multi_palm_rects_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.RectToRenderDataCalculatorOptions] {
      filled: false
      color { r: 125 g: 0 b: 122 }
      thickness: 4.0
    }
  }
}
```
In the above graph snippet as an example like thickness option. I want to add a new option like min and max value for the new calculator I have written. I can successfully build the calculator when I add the new `node_option` it i giving me error 

What are the steps to achieve?

**Comment by eknight7** [comment]
Hi,
Could you please clarify the issue you are facing?
>  I can successfully build the calculator when I add the new node_option it i giving me erro
Where are you building the calculator? Can you share the build files please?

**Comment by MaRauder111** [comment]
I have added a new calculator [hand-gesture-recoginition-zoom-calculator.cc](https://github.com/MaRauder111/mediapipe/blob/zoom/hand-gesture-recognition-zoom/hand-gesture-recognition-zoom-calculator.cc) which use the rect and recognize the gesture zoom. It's working fine.

I want to add a new `node_option` in the [hand_renderer_cpu.pbtxt](https://github.com/MaRauder111/mediapipe/blob/zoom/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.pbtxt) in the node: `HandZoomGestureRecognitionCalculator`. I want to add min and max value which is define in the [hand-gesture-recoginition-zoom-calculator.cc](https://github.com/MaRauder111/mediapipe/blob/zoom/hand-gesture-recognition-zoom/hand-gesture-recognition-zoom-calculator.cc). When I add the node option in the graph:

```
  node_options: {
    [type.googleapis.com/mediapipe.HandZoomGestureRecognitionCalculatorOptions]: {
      minZoom: 0.505845
      maxZoom: 1.03777
    }
  }
```

It's giving me build error

```
ERROR: /mediapipe/mediapipe/graphs/hand_tracking/subgraphs/BUILD:24:26: Executing genrule //mediapipe/graphs/hand_tracking/subgraphs:hand_renderer_cpu_graph failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:309] Error parsing text-format mediapipe.CalculatorGraphConfig: 150:82: Could not find type "type.googleapis.com/mediapipe.HandZoomGestureRecognitionCalculatorOptions" stored in google.protobuf.Any.
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:309] Error parsing text-format mediapipe.CalculatorGraphConfig: 150:82: Could not find type "type.googleapis.com/mediapipe.HandZoomGestureRecognitionCalculatorOptions" stored in google.protobuf.Any.
E20210208 14:32:30.689415     3 text_to_binary_graph.cc:112] INTERNAL: ; could not parse text proto: mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.pbtxt
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.596s, Critical Path: 0.08s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

How can I add a new `node_option` in the graph?

**Comment by MaRauder111** [comment]
The new [calculator ](https://github.com/MaRauder111/mediapipe/blob/zoom/hand-gesture-recognition-zoom/hand-gesture-recognition-zoom-calculator.cc) and [build](https://github.com/MaRauder111/mediapipe/blob/zoom/hand-gesture-recognition-zoom/BUILD) committed in the [branch](https://github.com/MaRauder111/mediapipe/tree/zoom).

I want to add a new `node_option` in the [hand_renderer_cpu.pbtxt](https://github.com/MaRauder111/mediapipe/blob/zoom/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.pbtxt#L139). I want to add the min and max value which is define in the [calculator](https://github.com/MaRauder111/mediapipe/blob/zoom/hand-gesture-recognition-zoom/hand-gesture-recognition-zoom-calculator.cc#L29). When I add the ```node_option``` in the graph. It's giving me build error.

```
ERROR: /mediapipe/mediapipe/graphs/hand_tracking/subgraphs/BUILD:24:26: Executing genrule //mediapipe/graphs/hand_tracking/subgraphs:hand_renderer_cpu_graph failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:309] Error parsing text-format mediapipe.CalculatorGraphConfig: 150:82: Could not find type "type.googleapis.com/mediapipe.HandZoomGestureRecognitionCalculatorOptions" stored in google.protobuf.Any.
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:309] Error parsing text-format mediapipe.CalculatorGraphConfig: 150:82: Could not find type "type.googleapis.com/mediapipe.HandZoomGestureRecognitionCalculatorOptions" stored in google.protobuf.Any.
E20210208 14:32:30.689415     3 text_to_binary_graph.cc:112] INTERNAL: ; could not parse text proto: mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.pbtxt
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.596s, Critical Path: 0.08s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

How can I add a new `node_option` in a graph?

**Comment by MaRauder111** [comment]
New [calculator](https://github.com/MaRauder111/mediapipe/blob/zoom/hand-gesture-recognition-zoom/hand-gesture-recognition-zoom-calculator.cc) and [build](https://github.com/MaRauder111/mediapipe/blob/zoom/hand-gesture-recognition-zoom/BUILD) committed in the [branch](https://github.com/MaRauder111/mediapipe/tree/zoom).

I want to add the min and max value in [hand_renderer_cpu.pbtxt](https://github.com/MaRauder111/mediapipe/blob/zoom/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.pbtxt#L139) use in the [calculator](https://github.com/MaRauder111/mediapipe/blob/zoom/hand-gesture-recognition-zoom/hand-gesture-recognition-zoom-calculator.cc#L30). When I add the node option in the [hand_renderer_cpu.pbtxt](https://github.com/MaRauder111/mediapipe/blob/zoom/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.pbtxt#L139) and build.

It's giving me build error

```
ERROR: /mediapipe/mediapipe/graphs/hand_tracking/subgraphs/BUILD:24:26: Executing genrule //mediapipe/graphs/hand_tracking/subgraphs:hand_renderer_cpu_graph failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:309] Error parsing text-format mediapipe.CalculatorGraphConfig: 140:82: Could not find type "type.googleapis.com/mediapipe.HandZoomGestureRecognitionCalculatorOptions" stored in google.protobuf.Any.
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:309] Error parsing text-format mediapipe.CalculatorGraphConfig: 140:82: Could not find type "type.googleapis.com/mediapipe.HandZoomGestureRecognitionCalculatorOptions" stored in google.protobuf.Any.
E20210210 13:28:01.804160     3 text_to_binary_graph.cc:112] INTERNAL: ; could not parse text proto: mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.pbtxt
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
```

How can I add the ```node_option``` in the [hand_renderer_cpu.pbtxt](https://github.com/MaRauder111/mediapipe/blob/zoom/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.pbtxt#L139)?

**Comment by eknight7** [comment]
Yes @MaRauder111 you have to write a new proto file for the `HandZoomGestureRecognitionCalculatorOptions`. For example, please see [landmarks_to_floats_calculator.cc](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/landmarks_to_floats_calculator.cc) which uses a custom proto file [landmarks_to_floats_calculator.proto](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/landmarks_to_floats_calculator.proto). The proto declares what options can be set for the calculator and the calculator code shows how to get those options from the proto object and use it inside the calculator.

**Comment by sgowroji** [comment]
Assuming you are fixed with the above comments. We are closing this issue. Please feel free to reopen if the issue still exists. Thanks!
