### ISSUE TITLE
face orientation angles from face geometry

### ISSUE THREAD

**Issue by ianni67** [google/mediapipe#1561]
Hello,
I'm actively studying the mediapipe framework and having some issues with retrieving the actual orientation angles from face geometry. I need them for my application. I'm probably missing some obvious detail. Can you give me some hints?
Thank you

**Comment by kostyaby** [comment]
Hey @ianni67,

The trick is to take the rotation component of the face pose transformation matrix ([link](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/face_geometry.proto#L39-L50), the top-left 3x3 matrix is the rotation matrix as currently scale is 1) and use some method for converting that rotation matrix into the format you need

If you need Euler angles and have access to Eigen library, then [this](https://eigen.tuxfamily.org/dox/group__Geometry__Module.html#ga17994d2e81b723295f5bc3b1f862ed3b) method is helpful. In case you use some other geometry library, then just google "rotation matrix to euler angles [the name of the library]" and you should be able to find relevant info

**Comment by ianni67** [comment]
Thank you very much for your kind help. I will try this solution.

**Comment by ianni67** [comment]
Hello, while trying to get the face pose transformation matrix from face geometry, I got stuck because I'm not able to get geometry_pipeline_metadata.binarypb  to be built. It is not available anywhere. What can I do?

**Comment by douglas125** [comment]
I too would appreciate it if some method would be available to receive face data output and produce face orientation angles (DCM or Euler)

**Comment by qualityland27** [comment]
Anybody solved this issue? I am also interested in orientation angles from face geometry.
