### ISSUE TITLE
Issues setting up GPU inference with CUDA

### ISSUE THREAD

**Issue by mikeyin97** [google/mediapipe#1564]
Hello, I am having some trouble setting up CUDA support on Linux. I am following the documentation at https://google.github.io/mediapipe/getting_started/gpu_support.html. 

When I run
`ls /usr/local/cuda/extras/CUPTI/lib64`
I get
`libcupti.so            libcupti_static.a        libnvperf_target.so`
`libcupti.so.11.1      libnvperf_host.so`
`libcupti.so.2020.2.0  libnvperf_host_static.a
`

When I run
`ls /usr/local/cuda-11.1`
I get
`bin                extras   nsight-compute-2020.2.0  nvvm     src`
`compute-sanitizer  include  nsightee_plugins         README   targets`
`DOCS               lib64    nsight-systems-2020.3.4  samples  tools`
`EULA.txt           libnvvp  nvml                     share
`

When I run
`nvcc -V`
I get
`nvcc: NVIDIA (R) Cuda compiler driver`
`Copyright (c) 2005-2020 NVIDIA Corporation`
`Built on Tue_Sep_15_19:10:02_PDT_2020`
`Cuda compilation tools, release 11.1, V11.1.74`
`Build cuda_11.1.TC455_06.29069683_0
`

When I run
`ls /usr/lib/x86_64-linux-gnu/ | grep libcudnn.so`
I get
`libcudnn.so`
`libcudnn.so.8`
`libcudnn.so.8.0.5
`

Then I export the TF_CUDA_PATHS file with 
`export TF_CUDA_PATHS=/usr/local/cuda-11.1,/usr/lib/x86_64-linux-gnu,/usr/include`

and add these lines to the .bazelrc file in mediapipe 

`build:using_cuda --define=using_cuda=true`
`build:using_cuda --action_env TF_NEED_CUDA=1 `  
`build:using_cuda --crosstool_top=@local_config_cuda//crosstool:toolchain`
`build:cuda --config=using_cuda`
`build:cuda --define=using_cuda_nvcc=true`

I run bazel build with the cuda and spawn strategy tags as :
`bazel build -c opt --config=cuda --spawn_strategy=local 
    --define no_aws_support=true --copt -DMESA_EGL_NO_X11_HEADERS 
    mediapipe/examples/desktop/object_detection:object_detection_tensorflow`

After a few minutes of running actions, a error is returned.

`/home/mike/.cache/bazel/_bazel_mike/33fa973acbb87d76d64035569cb97c28/external/org_tensorflow/tensorflow/compiler/mlir/tools/kernel_gen/BUILD:89:13: Linking of rule '@org_tensorflow//tensorflow/compiler/mlir/tools/kernel_gen:tf_to_gpu_binary' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/host/bin/external/org_tensorflow/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary-2.params
/usr/bin/ld: bazel-out/host/bin/external/org_tensorflow/tensorflow/stream_executor/cuda/libcublas_plugin.lo(cuda_blas.o): undefined reference to symbol 'cublasLtMatmulPreferenceCreate@@libcublasLt.so.11'
/usr/bin/ld: /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcublasLt.so.11: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/object_detection:object_detection_tensorflow failed to build`

I note that the last error line has cuda-11.0 in the path, but I am running cuda-11.1. 

I am running Ubuntu 20.04. Mediapipe targets without inference work fine. Any ideas on this? I realize I am running different CUDA and ubuntu version than the example provided in the documentation.

**Comment by ianni67** [comment]
Everything works fine with my environment here. I run ubuntu 20.04 but purposely installed CUDA 10.1 instead of 11 because I read that CUDA 10.1 is the highest version supported by tensorflow.
I would rather suggest you to _very very carefully_ uninstall, and I mean, _fully uninstall_ CUDA 11 and install CUDA 10.1. I do know this is not the solution you are looking for but it is the only one guaranteed to work.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
