### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by Mushahid2521** [google/mediapipe#1565]
I am trying to install Mediapipe in Python. I have tried for a longer time but couldn't get rid of the following issue. 
I have created a new environment and then used "pip install mediapipe" then when I try to import, it gives the following error. 

`from google.protobuf.pyext import _message  
ImportError: DLL load failed: The specified procedure could not be found.
`

**Comment by jiuqiant** [comment]
Can you downgrade your local protobuf package to a lower version? For example, you can manually install protobuf v3.11.4 by doing `pip uninstall protobuf && pip install protobuf==3.11.4`.

How are some links that mention this issue: https://stackoverflow.com/questions/54154328/python-protobuf-from-google-protobuf-pyext-import-message-importerror-dll and https://github.com/tensorflow/tensorflow/issues/25072.

**Comment by Mushahid2521** [comment]
Thanks @jiuqiant. I tried to follow by uninstalling and then installing protobuf, but protobuf 3.11.4 is not found. 
Upgrading my Python 3.6 to Python 3.8 worked for me.
