### ISSUE TITLE
Build binary graph Mediapipe

### ISSUE THREAD

**Issue by Neeraj1108Yadav** [google/mediapipe#1566]
Hi Developers

Currently I am working with the framework of Mediapipe. Referring below link and issue #1556 I am able to generate **aar** file.

https://google.github.io/mediapipe/getting_started/android_archive_library.html#steps-to-use-a-mediapipe-aar-in-android-studio-with-gradle

Now I am facing another another problem of generating **Build Binary Graph** an **asset** for Android Studio. I am following exactly the same path mentioned in above link. But I always get error of **mobile_gpu_binary_graph is not declared in package**

I referred this link https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/BUILD my BUILD file is same. But still I am getting this error. 

<img width="592" alt="Screenshot 2021-02-01 at 2 21 25 PM" src="https://user-images.githubusercontent.com/34931349/106435390-d36ee980-6498-11eb-9188-08e1a53a2a08.png">

**Comment by jiuqiant** [comment]
Have you synced to head? It looks ok on my end.

```
$ bazel build mediapipe/graphs/face_detection:face_detection_mobile_gpu_binary_graph
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip) = 101f8b8aec09998b28ebc854e5ae8ec7c403fad21be1540add2689490ba19449
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "101f8b8aec09998b28ebc854e5ae8ec7c403fad21be1540add2689490ba19449"
...
Target //mediapipe/graphs/face_detection:face_detection_mobile_gpu_binary_graph up-to-date:
  bazel-bin/mediapipe/graphs/face_detection/face_detection_mobile_gpu.binarypb
INFO: Elapsed time: 126.526s, Critical Path: 89.85s
INFO: 386 processes: 386 darwin-sandbox.
INFO: Build completed successfully, 400 total action
```

**Comment by Neeraj1108Yadav** [comment]
Hi @jiuqiant Thanks for your reply.

I am able to generate the **binarypb** file. But I didn't understood, I just changed the name from **mobile_gpu_binary_graph** to **face_detection_mobile_gpu_binary_graph** and it generated. Any specific reason ??

**Comment by jiuqiant** [comment]
Because "face_detection_mobile_gpu_binary_graph" is the mediapipe_binary_graph  target name: https://github.com/google/mediapipe/blob/f96eadd6df64a5f9a31918d6319e51847497641a/mediapipe/graphs/face_detection/BUILD#L65
