### ISSUE TITLE
ERROR: protobuf.bzl

### ISSUE THREAD

**Issue by wxs19920926** [google/mediapipe#157]
ERROR: /path/to/mediapipe/mediapipe/framework/BUILD:79:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /path/to/mediapipe/mediapipe/framework/BUILD:52:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /root/.cache/bazel/_bazel_root/f93a117bf26ccd1d4d6929188e887fc7/external/com_google_protobuf/BUILD:283:2: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /path/to/mediapipe/mediapipe/framework/BUILD:85:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /path/to/mediapipe/mediapipe/framework/BUILD:73:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /path/to/mediapipe/mediapipe/framework/BUILD:107:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /path/to/mediapipe/mediapipe/framework/BUILD:100:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /path/to/mediapipe/mediapipe/framework/BUILD:37:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /path/to/mediapipe/mediapipe/framework/BUILD:280:1: every rule of type java_lite_proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /path/to/mediapipe/mediapipe/framework/BUILD:66:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /path/to/mediapipe/mediapipe/framework/BUILD:287:1: every rule of type java_lite_proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /path/to/mediapipe/mediapipe/framework/deps/BUILD:25:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /path/to/mediapipe/mediapipe/framework/tool/BUILD:47:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors
ERROR: /path/to/mediapipe/mediapipe/framework/tool/BUILD:64:1: every rule of type java_lite_proto_library implicitly depends upon the target '@com_google_protobuf_javalite//:javalite_toolchain', but this target could not be found because of: error loading package '@com_google_protobuf_javalite//': Extension file 'protobuf.bzl' has errors

**Comment by jiuqiant** [comment]
Please let us know your OS, bazel version, Android studio version, and the bazel build command. Otherwise, we can't reproduce the issue.

This can be a protobuf/bazel compatibility issue. Some other google repos also get similar issues:
[1] https://github.com/google/sentencepiece/issues/354
[2] https://github.com/protocolbuffers/protobuf/issues/5547
