### ISSUE TITLE
RetinaFace ported to MediaPipe 

### ISSUE THREAD

**Issue by yyqgood** [google/mediapipe#1571]
1. Hello, does mediapipe support a three-output (score, box, landmark) network like retinaface? 
Please check my model: [retinaface_detection.tflite]
![screenshot_1](https://user-images.githubusercontent.com/34564480/106570094-662e8780-6570-11eb-92a6-a5aa6e6471d5.png)
![screenshot_2](https://user-images.githubusercontent.com/34564480/106570117-6cbcff00-6570-11eb-9f7c-c767aa81038a.png)
![screenshot_3](https://user-images.githubusercontent.com/34564480/106570132-721a4980-6570-11eb-9fe5-a95e3bad2876.png)

2. I refer to face_detection_cpu to transplant retinaface, the output of score is always about 0.5? (Regardless of whether there is a face). 
Please check the log screenshot I printed 
![score](https://user-images.githubusercontent.com/34564480/106569702-da1c6000-656f-11eb-896e-c81ead142e7b.png)

Looking forward for your reply, thank you!

**Comment by sgowroji** [comment]
Hi @yyqgood, Could you please provide the steps to reproduce the above and elaborate your use case with complete details. Thanks!
