### ISSUE TITLE
Are there any examples of how to convert a MainActivity Android example from an Activity to a Fragment?

### ISSUE THREAD

**Issue by violetforest** [google/mediapipe#1573]
For example, when the activity is turned into a fragment, it loses the reference to "this", and thus losing reference to Context

`    private SurfaceView previewDisplayView = new SurfaceView(this);`

`
        if (PermissionHelper.cameraPermissionsGranted(this)) {
            startCamera();
        }
`

`
        cameraHelper.startCamera(
                this, cameraFacing, /*unusedSurfaceTexture=*/ null, cameraTargetResolution());
`

**Comment by vladimirhermand** [comment]
More specifically, when turning the Activity into a fragment, I am losing reference to "this".

For example:

**Comment by DandyLorenz** [comment]
yes,it can run fragment

**Comment by eknight7** [comment]
No we don't have such examples. But you can use https://developer.android.com/guide/fragments/create to write your own fragments.
