### ISSUE TITLE
iOS use UIImage instead of CVPixelBuffer

### ISSUE THREAD

**Issue by Nvelu048** [google/mediapipe#1574]
Hi @mcclanahoochie 

as per [this](https://google.github.io/mediapipe/getting_started/hello_world_ios.html)

Live Feed from camera is passed as type `MPPPacketTypePixelBuffer`

I need to pass an UIImage instead of pixelBuffer from camera source

What to do! Need Guidance

**Comment by PopovVadim** [comment]
I'm facing the same thing now on iOS. Need help here guys. 
What's the proper way to convert a static image to `CVPixelBuffer` for mediapipe?

My case 
✅ I've got to take a photo from photo library as `PHAsset `
✅ Get the image as either `UIImage` / `Data`
❔ Convert the image to pixel buffer (am I doing this right? The code below)
😞 No results from the face recognition model although there is a face on the image

## Code

### Getting image from photo library

```
PHImageManager.default().requestImageDataAndOrientation(
        for: myAsset,
        options: myOptions,
        resultHandler: { data, _, _, _ in
            if let data = data,
               let image = CIImage(data: data),
               let buffer = image.buffer { // The code below
                // Pass that buffer to mediapipe
            }
        })
```

### Making buffer with a `CIImage`

```
extension CIImage {
    
    var buffer: CVPixelBuffer? {
        var pixelBuffer: CVPixelBuffer?
        let attrs = [kCVPixelBufferCGImageCompatibilityKey: kCFBooleanTrue,
                     kCVPixelBufferCGBitmapContextCompatibilityKey: kCFBooleanTrue] as CFDictionary
        let width = Int(extent.width)
        let height = Int(extent.height)
        
        let status = CVPixelBufferCreate(kCFAllocatorDefault,
                            width,
                            height,
                            kCVPixelFormatType_32BGRA,
                            attrs,
                            &pixelBuffer)
        
        guard status == kCVReturnSuccess,
              let buffer = pixelBuffer else { return nil }
        
        let context = CIContext()
        context.render(self, to: buffer)
        return buffer
    }
}
```

**Comment by PopovVadim** [comment]
Found the answer that helped me. The thing is that when you create a CVPixelBuffer like I shown above, it is NOT backed by an IOSurface and therefore cannot be turned into a Metal texture later.

There is a handy helper for that - see `copyToMetalCompatible` function [here](https://github.com/hollance/CoreMLHelpers/blob/master/CoreMLHelpers/CVPixelBuffer%2BCreate.swift#L105)

**Comment by Nvelu048** [comment]
Hi @PopovVadim , 

Thanks for pointing this

As of now I don't have mediapipe setup to check this 

If possible kindly self assign this issue and close it

**Comment by sgowroji** [comment]
Thank you @PopovVadim, We are closing this issue now.
