### ISSUE TITLE
BlazePose Python API - Fast/Accurate Model 

### ISSUE THREAD

**Issue by KatchaVlad** [google/mediapipe#1577]
I couldn't find any information about the blazepose model used with the python package of MediaPipe. 
Is the package using the Fast or the Accurate model (I suppose the accurate), and do you know if there is a plan for making both the fast & accurate model available ?
Thanks

**Comment by ivan-grishchenko** [comment]
Hi @KatchaVlad 

You are right, we are providing the "accurate" model in graphs/demos/APIs.
We don't plan to open source the fast one. Do you have a particular use case in mind for it?

**Comment by sgowroji** [comment]
Resolution provided in this https://github.com/google/mediapipe/issues/1577#issuecomment-797168372 we are closing this issue.
