### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by wxs19920926** [google/mediapipe#158]
java.lang.UnsatisfiedLinkError: com.google.devtools.build.android.incrementaldeployment.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/local/tmp/incrementaldeployment/com.google.mediapipe.apps.facedetectioncpu/dex/incremental_classes1.dex"],nativeLibraryDirectories=[/data/user/0/com.google.mediapipe.apps.facedetectioncpu/lib, /vendor/lib, /system/lib]]] couldn't find "libmediapipe_jni.so"

**Comment by jiuqiant** [comment]
Mark as duplication of https://github.com/google/mediapipe/issues/162.
