### ISSUE TITLE
What is the depth multiplier for face mesh in Python solutions?

### ISSUE THREAD

**Issue by vaibhavgupta-hike** [google/mediapipe#1582]
By running mediapipe facemesh api on a frame, 

each landmark is of the form (fx, fy, fz) s.t. 
fx * frame_width corresponds to the x coordinate in frame
fy * frame_height corresponds to the y coordinate in frame

What is the multiplier to be used with fz?

**Comment by ablavatski** [comment]
For the `z` the same multiplier as for `fx` should be used. In your use case it is `fz * frame_width`. Please see the Section 2 in the [paper](https://arxiv.org/pdf/1907.06724.pdf) (page 2).
