### ISSUE TITLE
Invalid certificate for mediapipe.dev

### ISSUE THREAD

**Issue by stevestavropoulos** [google/mediapipe#1583]
Chrome can't connect to https://mediapipe.dev/ with error NET::ERR_CERT_AUTHORITY_INVALID
I see that the certificate chain file is not supplied.

Full error by Chrome is as follows:

Your connection is not private
Attackers might be trying to steal your information from mediapipe.dev (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID
Subject: mediapipe.dev

Issuer: GTS CA 1O1

Expires on: Mar 8, 2021

Current date: Feb 4, 2021

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIGHDCCBQSgAwIBAgIRAOt/4zMAntCTBQAAAACCDQEwDQYJKoZIhvcNAQELBQAw
QjELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFUdvb2dsZSBUcnVzdCBTZXJ2aWNlczET
MBEGA1UEAxMKR1RTIENBIDFPMTAeFw0yMDEyMDgwMjI1NThaFw0yMTAzMDgwMjI1
NTdaMGcxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
Ew1Nb3VudGFpbiBWaWV3MRMwEQYDVQQKEwpHb29nbGUgTExDMRYwFAYDVQQDEw1t
ZWRpYXBpcGUuZGV2MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu6nS
WE9mspb2l0zOPXorPw/YPmJtv39wNemMWjW7GxVyURHxwIdW3pzoGAaVX4JAR6mk
6T7BIfS6s4kWnP8A4pBFETr28XsMX5F5+Z7Hktrry8YTo2qb+yeEFekCIIC6PZF8
66R1KkkZ8tyvv9u3GzRAXG3aLG8wiWmUDQPtupdZBky/23AnPlZQTHila+y4U1UI
qTYiqy8tNfXaOAG1XR4hZFjL15etImpC44y9ZydFSHSt5SzH48RrlomXyG1df4U5
NgTR8b1/QqbvyrMUU8yFdAP2WFHkFhX0M54hiTzjVCCbtVk4+UODHEAYBYFGnAeQ
+fABOd+Uw5YqkRsJKwIDAQABo4IC5jCCAuIwDgYDVR0PAQH/BAQDAgWgMBMGA1Ud
JQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFBkRQdz5qmCr
iFnBtBTtUOQZFQCtMB8GA1UdIwQYMBaAFJjR+G4Q68+b7GCfGJAboOt9Cf0rMGQG
CCsGAQUFBwEBBFgwVjAnBggrBgEFBQcwAYYbaHR0cDovL29jc3AucGtpLmdvb2cv
Z3RzMW8xMCsGCCsGAQUFBzAChh9odHRwOi8vcGtpLmdvb2cvZ3NyMi9HVFMxTzEu
Y3J0MIGsBgNVHREEgaQwgaGCDW1lZGlhcGlwZS5kZXaCEmNvZGUubWVkaWFwaXBl
LmRldoIVY3Y0YXJ2ci5tZWRpYXBpcGUuZGV2ghJkb2NzLm1lZGlhcGlwZS5kZXaC
EmhhbmQubWVkaWFwaXBlLmRldoIXc29sdXRpb25zLm1lZGlhcGlwZS5kZXaCEXZp
ei5tZWRpYXBpcGUuZGV2ghF3d3cubWVkaWFwaXBlLmRldjAhBgNVHSAEGjAYMAgG
BmeBDAECAjAMBgorBgEEAdZ5AgUDMC8GA1UdHwQoMCYwJKAioCCGHmh0dHA6Ly9j
cmwucGtpLmdvb2cvR1RTMU8xLmNybDCCAQIGCisGAQQB1nkCBAIEgfMEgfAA7gB1
AH0+8viP/4hVaCTCwMqeUol5K8UOeAl/LmqXaJl+IvDXAAABdkBiZvIAAAQDAEYw
RAIgWjqE6o+Atnioww5J0v4qT+OGURRXsvG3gaNf4z2wp4YCIBnS0ROXtAJMkSH9
7jcp3/tsnerBa2pgAUNNob7ERthCAHUAlCC8Ho7VjWyIcx+CiyIsDdHaTV5sT5Q9
YdtOL1hNosIAAAF2QGJm2gAABAMARjBEAiARfxsg+XT38gyfhODXZLjy0laYmfTB
bbEINuTqkdWM8wIgexKH0gMWRKFK+FZjHb2YDs6LI8r69LEmuBZGR2ScBW8wDQYJ
KoZIhvcNAQELBQADggEBAHF6iRp//jWJulBIaVRSDWlyL8wpIFcYT9ttV7JcC7x2
Xm5S0klqCAHouUjZh53gKA7CUm4kGSvQufHL1lZht8RBZ1XGtxL/we1uNIoNPGAe
ytfsHKmWL0dbpusnL6bhRDb5iVbvn2zwbZi+ABimjY4qteXs8qPgRyW8DUlZTARE
Rb+wig8RD19uMKLSNZ6ToiED8X5T25Wrb18t3PbqNIYUQmIkDPf7diY/JmZXSMZH
ChNzx4FlthhDP3s+uHOAH11SIkSGjgz1sEVw9h0jBKJP3Wh5b9EvTVv02lWgF7qy
rS2Bay5F+KYwxu2nejNN5LVFG59H+p8VNgVyXRvBRBA=
-----END CERTIFICATE-----

To get Chrome’s highest level of security, turn on enhanced protection
mediapipe.dev normally uses encryption to protect your information. When Google Chrome tried to connect to mediapipe.dev this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be mediapipe.dev, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit mediapipe.dev right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by tyrmullen** [comment]
The cert was recently updated-- is this still an issue for you @stevestavropoulos?

**Comment by stevestavropoulos** [comment]
It's ok now. Problem is fixed.

**Comment by sgowroji** [comment]
Closing this as it is fixed . Thanks ! Adding the duplicate [here](https://github.com/google/mediapipe/issues/1717)
