### ISSUE TITLE
cannot get geometry_pipeline_metadata.binarypb to be built

### ISSUE THREAD

**Issue by ianni67** [google/mediapipe#1584]
Hello, I'm trying to use the face geometry model and cannot get geometry_pipeline_metadata.binarypb to be built in any way (nor is it available in the tree). What is the right way to use face geometry in a Linux (i.e., non-iOS) environment?

**Comment by ianni67** [comment]
Looks like I'm not the only one having this issue: see, for example, #1253
I've been bumping my head to the wall for two days,  is there any hints that you can provide?

**Comment by ianni67** [comment]
Ok, never mind... I eventually managed to build the file. 
Just in case, here is what I did, after tons of trials and errors:

`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=0 --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/modules/face_geometry`

The above command built a library but not the desired file. Then I ran:

` bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=0 --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/modules/face_geometry/data:geometry_pipeline_metadata`

And then desperately looked for the file: 

```
 cd bazel-out
find . -print | grep -i geometry_pipeline_metadata.binarypb
```

And eventually found it:

` cp ./k8-opt/bin/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata.binarypb ../mediapipe/modules/face_geometry/data/`

Hopefully this will help others.

**Comment by kostyaby** [comment]
Hey @ianni67,

When releasing Face Geometry module, I explicitly decided not to support desktop as a platform the same way I support Android / iOS cuz of the effect renderer targeting OpenGL ES, not desktop OpenGL - and I didn't have eng cycles to add that support. You could argue that the face geometry could still be executed on CPU, but without a renderer - I thought - it's like a releasing a half-baked solution on one of the platform isn't great. Having said that, you are right that the protobuf compile ended up outputting the generated `geometry_pipeline_metadata.binarypb` in some random place; I chose not put desktop as a platform on my radar for the module launch so I didn't end up learning sooner. I'm sorry for the suboptimal dev experience you had and also I'm glad you were able to finally find it :)

If that makes things easier, I'd compile `geometry_pipeline_metadata.binarypb` only once and then include the compiled file as an asset into desktop builds to ensure an easier and controllable file system location

**Comment by ianni67** [comment]
Dear @kostyaby, I fully understand your point about not focusing on desktop, however, please bear in mind that if the target of this repository encompasses also the research community and not only the app developers, most people will likely try your platform on their desktop, and will develop on desktops first. I love the effectiveness and the stability of mediapipe, however, I have to admit that I'm spending weeks just to get to the point where I was before I decided to port my research software to mediapipe. This is not the best foot for the first step, I would say. 
This said, the most important point is that the iPAD hardware platform supports hardware-based face orientation detection and eye tracking is easily done, while your face geometry module would mostly benefit those developers not working with Apple hardware. I'm one of them.
All the best,
Giancarlo

**Comment by kostyaby** [comment]
Hey Giancarlo, thanks for making a case as a desktop customer of Mediapipe! From our side, I believe there should be an expansion of Python API in particular to add support for Face Geometry in addition to Face Meshes in the following months to better enable research community (#1457 for context). Hopefully, over time we'll nail down better dev support on all platforms

**Comment by ianni67** [comment]
Thank you very much, @kostyaby, for your kind reply and understanding. I would also take into consideration the c++ version for desktop, as it is the foundation for embedded applications running, for example, on Raspberry Pi or (better) on nvidia jetson nano (just to name a couple of them). Python tends to be slower and some applications would not comply with the operational constraints.

**Comment by homuler** [comment]
I tested a desktop gpu version.
https://github.com/homuler/mediapipe/blob/feature/face-effect-desktop/mediapipe/examples/desktop/face_effect/BUILD

If someone is interested...
I specefied `resource_root_dir` and you don't have to copy .binarypbs and etc.

```sh
git clone https://github.com/homuler/mediapipe.git
cd mediapipe
git checkout feature/face-effect-desktop

bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 //mediapipe/examples/desktop/face_effect:face_effect_gpu
 
 GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_effect/face_effect_gpu --effect=facepaint
```

**Comment by ianni67** [comment]
Thank you very much @homuler, it is quite late here but tomorrow in the morning I will test your software. I hope to learn from your work.
