### ISSUE TITLE
Weird results.multiHandedness[0].index in JavaScript

### ISSUE THREAD

**Issue by takahirox** [google/mediapipe#1586]
Hello, thanks for the awesome project. I'm trying [WebXR Emulator Extension Hand input support](https://twitter.com/superhoge/status/1356083004754468864) with MediaPipe.

I use JavaScript - Wasm version and I sometime encounter weird index (maybe bug?) in the `results.multiHandedness`.

I set `maxNumHands` option to `2`. I get results that `results.multiHandLandmarks.length` is `1`, `results.multiHandedness.length` is `1`, and `results.multiHandedness[0].index` is `1` like the following JSON example.

```javascript
{
  multiHandLandmarks: [
    [{...}, {...}, ...]
  ],
  multiHandedness: [{
    index: 1,
    label: 'Right',
    ...
  }],
  ...
}
```

I couldn't find the document about the API but I speculate `results.multiHandedness[n].index` refers to the entry in `results.multiHandLandmarks`. So in my case `results.multiHandedness[0].index = 1` is over the length of `results.multiHandLandmarks`. Do you think this is a bug? Or intentional or my misunderstanding of the API?

How to reproduce: Sorry I don't have a simple example yet. A way you can try now is [manually download and install the WebXR Emulator Extension](https://github.com/MozillaReality/WebXR-emulator-extension/tree/HandWIP#how-to-install-the-newest-version) from the [WIP branch](https://github.com/MozillaReality/WebXR-emulator-extension/tree/HandWIP), follow [this video](https://twitter.com/superhoge/status/1356083004754468864) to enable hand tracking, and set break point at [this line](https://github.com/MozillaReality/WebXR-emulator-extension/blob/dc0a8a70f374f9347a0b20102ddb247fceef9ef5/src/extension/mediapipe/helper.js#L58) of the extension background script.

**Comment by sgowroji** [comment]
Hi @takahirox, Could you please respond if you still looking resolution for the above query. Thanks!

**Comment by takahirox** [comment]
Let me check if the problem is still reproducible with the latest lib later...
