### ISSUE TITLE
Option 1: Build with Bazel in Command Line： ERROR: An error occurred during the fetch of repository 'maven':

### ISSUE THREAD

**Issue by some2014** [google/mediapipe#1587]
Dear：
I am learning To build an Android example app:

`bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu`

Build did NOT complete successfully:

mr_oh@MrOH:~/mediapipe$ bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
INFO: Build options --compilation_mode, --cpu, --crosstool_top, and 3 more have changed, discarding analysis cache.
INFO: Repository maven instantiated at:
  /home/mr_oh/mediapipe/WORKSPACE:326:14: in <toplevel>
  /home/mr_oh/.cache/bazel/_bazel_mr_oh/3dec97f5c9b440e2453b93a29f6b2d78/external/rules_jvm_external/defs.bzl:94:19: in maven_install
Repository rule coursier_fetch defined at:
  /home/mr_oh/.cache/bazel/_bazel_mr_oh/3dec97f5c9b440e2453b93a29f6b2d78/external/rules_jvm_external/coursier.bzl:798:33: in <toplevel>
INFO: Repository 'maven' used the following cache hits instead of downloading the corresponding file.
 * Hash '6598d9277705ad8369a4f9c64217fbc31c19234f2cbcca9b1e5c4300a3abb317' for https://github.com/coursier/coursier/releases/download/v2.0.0-RC5-3/coursier.jar
If the definition of 'maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
        File "/home/mr_oh/.cache/bazel/_bazel_mr_oh/3dec97f5c9b440e2453b93a29f6b2d78/external/rules_jvm_external/coursier.bzl", line 544, column 13, in _coursier_fetch_impl
                fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Timed out
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/home/mr_oh/.cache/bazel/_bazel_mr_oh/3dec97f5c9b440e2453b93a29f6b2d78/external/rules_jvm_external/coursier.bzl", line 544, column 13, in _coursier_fetch_impl
                fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Timed out
ERROR: /home/mr_oh/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/BUILD:18:16: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:basic_lib depends on @maven//:androidx_concurrent_concurrent_futures in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /home/mr_oh/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/BUILD:18:16: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:basic_lib depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: Analysis failed

**Comment by jiuqiant** [comment]
That's a network issue that we can't help too much. Here is a possible solution: https://google.github.io/mediapipe/getting_started/troubleshooting.html#fail-to-fetch-remote-dependency-repositories and also please use vpn if possible. Thanks.

**Comment by 20gg** [comment]
try to modiy  file  /mediapipe/WORKSPACE
`    repositories = [
        "https://maven.google.com",
        "https://dl.google.com/dl/android/maven2",
        "https://repo1.maven.org/maven2",
        "https://jcenter.bintray.com",
    ],
`
change yours maven repositories

**Comment by lingwei098** [comment]
in the WROKSPACE file, do this:
```
RULES_JVM_EXTERNAL_TAG = "4.2"
RULES_JVM_EXTERNAL_SHA = "cd1a77b7b02e8e008439ca76fd34f5b07aecb8c752961f9640dea15e9e5ba1ca"
```
and build again.
