### ISSUE TITLE
ValueError: ssd_mobilenet_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

### ISSUE THREAD

**Issue by Neeraj1108Yadav** [google/mediapipe#1588]
Hi Folks

From last few days I'm working on generating model file for **Object Detection** using **Tensorflow 2.x**. I have gone through so many blogs and github repos etc. etc.

With help of them I am able to generate **xml -> csv file** then **test.record / train.record** files. 

Links which I had gone through are mentioned below
https://teyou21.medium.com/training-your-object-detection-model-on-tensorflow-part-2-e9e12714bdf
https://www.dlology.com/blog/how-to-train-an-object-detection-model-easy-for-free/
https://medium.com/@marklabinski/installing-tensorflow-object-detection-api-on-windows-10-7a4eb83e1e7b

Now I am at that step where I have to run command to train the **record files using label text file**.
**python train.py --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_quantized_300x300_coco.config**

But after running this command in PyCharm I am getting error

![ssd](https://user-images.githubusercontent.com/34931349/107047208-92a30780-67ed-11eb-8773-3faf2ad2778f.JPG)

I searched a lot to solve this issue but not able to find any solution

Operating System: **Windows 10 64 bit**
Python version: **3.7**
Tensorflow version : **2.4.1**

Please help me if anyone has any solution for this.

**Comment by jiuqiant** [comment]
This model training issue is not related to mediapipe. Please file this issue against tensorflow repo. Thanks.

**Comment by Neeraj1108Yadav** [comment]
@jiuqiant I am so sorry for that :)
