### ISSUE TITLE
What is preprocess for face detection model?

### ISSUE THREAD

**Issue by tucachmo2202** [google/mediapipe#1590]
Hi everyone,
I'm using face detection model tflite for back camera. In preprocessing step, I just resize image to (256, 256) (I try padding and not padding) and scale the image to [-1, 1] but I got negative results in both regressor and classificator. What wrong with me?
Thanks so much!

**Comment by rmothukuru** [comment]
@tucachmo2202,
Can you try scaling the image to [0,1] by dividing each pixel by 255.0 and let us know if the issue persists? Thanks!

**Comment by rmothukuru** [comment]
@tucachmo2202,
Can you please respond to the above comment? Thanks!

**Comment by sgowroji** [comment]
Closing this issue as there is a lack of activity on this issue.
