### ISSUE TITLE
Packet::Get() failed: Expected a Packet of type: std::pair<int, int>, but received an empty Packet.

### ISSUE THREAD

**Issue by milad-4274** [google/mediapipe#1592]
Hi, I'm modifying face_mesh_cpu desktop example. I added a simple calculator in face_render_cpu subgraph to observe image_size stream generated by "ImagePropertiesCalculator". In Open() function i wrote:
`cc->Inputs().Tag(kImageSize).Set<std::pair<int, int>>();`
in Process() function:
`absl::optional<std::pair<int, int>> image_size;`
`image_size = cc->Inputs().Tag(kImageSize).Get<std::pair<int, int>>();`

I got error that say image_size is empty:
`F20210207 10:06:27.402784 25167 packet.h:750] Packet::Get() failed: Expected a Packet of type: std::pair<int, int>, but received an empty Packet.
`
is there any problem in setting or getting data?

I tested input_image stream too and got a similar error.

**Comment by milad-4274** [comment]
I found out that the error occur when I use another input of type `NormalizedLandmarkList`.
if I remove input with type NormalizedLandmarkList everything works fine. any advise?

**Comment by sgowroji** [comment]
Hi @milad-4274, Can you share your code changes to understand the issue much better. Thanks!
