### ISSUE TITLE
Calculator::Open() for node "palmdetectioncpu__InferenceCalculator" failed: ; Failed to load model from path ...mediapipe/modules/palm_detection/palm_detection.tflite

### ISSUE THREAD

**Issue by stq054188** [google/mediapipe#1593]
My Environment: windows10, Python3.7.5, mediapipe0.8.2

pip install mediapipe --->0.8.2

my python code:
----------------------------------------------------------
import cv2
import mediapipe as mp
from os import listdir
mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands

hands = mp_hands.Hands(
    min_detection_confidence=0.5, min_tracking_confidence=0.5)
cap = cv2.VideoCapture(0)
while cap.isOpened():
  success, image = cap.read()
  if not success:
    print("Ignoring empty camera frame.")
    continue

  image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)
  image.flags.writeable = False
  results = hands.process(image)

  image.flags.writeable = True
  image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
  if results.multi_hand_landmarks:
    for hand_landmarks in results.multi_hand_landmarks:
      mp_drawing.draw_landmarks(
          image, hand_landmarks, mp_hands.HAND_CONNECTIONS)
  cv2.imshow('result', image)
  if cv2.waitKey(5) & 0xFF == 27:
    break
cv2.destroyAllWindows()
hands.close()
cap.release()
----------------------------------------------------------

when I use python file is ok, but I use pyinstaller to pack py to exe, it shows error like fllows:

File "mediapipe\python\solutions\hands.py", line 165, in process
File "mediapipe\python\solution_base.py", line 294, in process
RuntimeError: Graph has errors:
Calculator::Open() for node "palmdetectioncpu__InferenceCalculator" failed: ; Failed to load model from path C:\Users\stq054188\AppData\Local\Temp\_MEI169402/mediapipe/modules/palm_detection/palm_detection.tflite
[4744] Failed to execute script Video

**Comment by stq054188** [comment]
Is anyone meet same problem?

**Comment by jiuqiant** [comment]
From the log, I guess it might be a slash vs backslash issue. See where to find the model at https://github.com/google/mediapipe/issues/1594#issuecomment-775397805. The discussion can be continued here.

**Comment by stq054188** [comment]
> From the log, I guess it might be a slash vs backslash issue. See where to find the model at [#1594 (comment)](https://github.com/google/mediapipe/issues/1594#issuecomment-775397805). The discussion can be continued here.

Thanks for your reply. I mean i cant find where to use palm_detection.tflite in code，would you point out the place in code，thanks.

**Comment by stq054188** [comment]
@jiuqiant  In the place: 
D:\Python37\Lib\site-packages\mediapipe\python\solution_base.py 
D:\Python37\Lib\site-packages\mediapipe\python\solutions\hands.py 
I only found it use hand_landmark_tracking_cpu.binarypb but not use palm_detection.tflite.

**Comment by sgowroji** [comment]
Hi @stq054188, Could you please share the issue status. Thanks

**Comment by sgowroji** [comment]
Hi @stq054188, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.
