### ISSUE TITLE
I can't find where to use palm_detection.tflite model file.

### ISSUE THREAD

**Issue by stq054188** [google/mediapipe#1594]
My Environment: win10, python3.7.5, mediapipe 0.8.2(pip install mediapipe)

when I pack my python file to exe, it shows error message: can not load palm_detection.tflite
but I can not find where has used this file, can anyone help me to point out the path, thanks a lot.

**Comment by jiuqiant** [comment]
It's in the mediapipe python package: 

```
$ ls mp_env/lib/python3.7/site-packages/mediapipe/modules/palm_detection/
palm_detection.tflite
```

**Comment by jiuqiant** [comment]
Duplicate to https://github.com/google/mediapipe/issues/1593.

**Comment by fahmij8** [comment]
Hello, I'm facing the same trouble, but the difference is my environment is on Linux Ubuntu 18.04.5 LTS Jetson-nano 4.9.201-tegra aarch64. Mediapipe version is 0.8.5, i couldn't upgrade to the latest version because there's nothing new available for linux aarch64 (as far as I know). 
I believe the way to resolve this is to upgrade my mediapipe to the latest version, but could you enlight me ? 
Appreciate the help

**Comment by Andreslion** [comment]
> Hello, I'm facing the same trouble, but the difference is my environment is on Linux Ubuntu 18.04.5 LTS Jetson-nano 4.9.201-tegra aarch64. Mediapipe version is 0.8.5, i couldn't upgrade to the latest version because there's nothing new available for linux aarch64 (as far as I know).
> I believe the way to resolve this is to upgrade my mediapipe to the latest version, but could you enlight me ?
> Appreciate the help

Same here.....
Somebody please help

**Comment by Andreslion** [comment]
> It's in the mediapipe python package:
> 
> ```
> $ ls mp_env/lib/python3.7/site-packages/mediapipe/modules/palm_detection/
> palm_detection.tflite
> ```

I'm running on a Jetson Nano
Mine is in 
$ ls usr/local/lib/python3.6/dist-packages/mediapipe/modules/palm_detection/palm_detection.tflite
I'm running on a Jetson Nano.
How do I 'tell' python to go find it in this location?
I mean, it imports the mediapipe lib with no problem, but then it can't find the palm_detection.tflite
Please help

**Comment by noedev86** [comment]
I found a solution to that issue, what I did is changing the mediapipe package location. It is normally located under 
`mp_env/lib/python3.7/site-packages/mediapipe`
and I copied the `mediapipe` folder to `mp_env/mediapipe`. just copy the entire folder and it will find all the "missing" files.
If that doesn't work for you, **copy the mediapipe library one folder closer to the root env**
