### ISSUE TITLE
Face detection (CPU), blank screen on android device

### ISSUE THREAD

**Issue by midhulavijayan** [google/mediapipe#1595]
I have installed mediapipe face detection (CPU) using bazel. I am getting blank screen on the device.

**Comment by rmothukuru** [comment]
@midhulavijayan,
Can you please provide us the exact steps that you have followed to install MediaPipe Face Detection using Bazel. Also, can you please share the screenshot of the blank screen and the logs? Thanks!

**Comment by rmothukuru** [comment]
@midhulavijayan,
Can you please respond to the above comment? Thanks!

**Comment by midhulavijayan** [comment]
I have followed "https://google.github.io/mediapipe/getting_started/android.html#option-1-build-with-bazel-in-command-line" this link. Even i tried MediaPipe AAR (multihand detection) also [ "https://google.github.io/mediapipe/getting_started/android_archive_library.html"]. The aar based app is working in "oppo Reno 2f", but the same app is stopped working in "samsung galaxy J7" Is there any minimum h/w or android version requirements to run mediapipe?.

**Comment by jiuqiant** [comment]
Can you provide some adb log to help us know the issue better?

**Comment by sgowroji** [comment]
Hi @midhulavijayan Could you please share the adb logs as mentioned in the above comment.

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity!
