### ISSUE TITLE
handtrackinggpu build failure with provisioning profile

### ISSUE THREAD

**Issue by bugmany** [google/mediapipe#1596]
handtrackinggpu build failure with provisioning profile, 
before few days I build it success and run it ok, but when I upgrade mediapipe version 0.7 to 0.8, then rebuild handtrackinggpu failed, 

build error log as below:
mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:34:16: Processing and signing HandTrackingGpuApp failed (Exit 1): process-and-sign.sh failed: error executing command bazel-out/ios_arm64-opt/bin/mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp-intermediates/process-and-sign.sh
ERROR: Unable to find an identity on the system matching the ones in mediapipe/examples/ios/handtrackinggpu/provisioning_profile.mobileprovision
----------------
Note: The failure of target @build_bazel_rules_apple//tools/codesigningtool:codesigningtool (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------
Target //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.326s, Critical Path: 0.98s
INFO: 9 processes: 4 internal, 3 darwin-sandbox, 2 local.
FAILED: Build did NOT complete successfully
-----------------------------------------

1. I've re-checked provisioning profile is ok;
2. I've added --host_force_python=PY2 or --host_force_python=PY3, with the same error as above.

so I did not know why do it, could someone help me, thanks a lot.

**Comment by bugmany** [comment]
I've re-installed MACOS and re-built, then build successful, but this way is not optimal.

**Comment by bugmany** [comment]
the issue re-coming, I do not want re-installed MACOS, could someone give good advice?

**Comment by sgowroji** [comment]
Hi @bugmany, Could you please update if the still still exists. Thanks!

**Comment by bugmany** [comment]
hi @sgowroji, the issue still exists, but when i got the issue, i 'll re-installed MACOS, but the way is not good solution, now i can close the issue.

**Comment by WorldObserver-cli** [comment]
@dangkhoasdc  I checked it on macOS13 and Xcode14.1, it works. Thx.
