### ISSUE TITLE
Plans of releasing pretrained Objectron models for transfer learning?

### ISSUE THREAD

**Issue by d-lay** [google/mediapipe#1598]
Hallo,

I would like to train your 3D object detection to detect a custom object. Are there any plans of making the Objectron model open source? Do you plan on providing model checkpoints for transfer learning?

Thank you very much!

**Comment by sgowroji** [comment]
Hi @d-lay, Let us know if you're still looking for the above answer of your query. Thanks!

**Comment by selimbek** [comment]
Hi @sgowroji , i'm also very interested to have the objectron model with some checkpoints. :)

**Comment by sgowroji** [comment]
Hi @d-lay & @selimbek We have a very clear documentation for objectron model [here](https://google.github.io/mediapipe/solutions/objectron#mediapipe-objectron). For any Queries regarding please reach us. Thanks!

**Comment by sgowroji** [comment]
Hi @d-lay, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.

**Comment by selimbek** [comment]
Hi, 
I read the documentation provided once more, and i havent found any source code for the regression part describe shortly in the Single Stage pipeline. 
The general aspect is described and the dataset is available. But I haven't found any source code or documentation on how to launch a training process by our own, to repeat the result you found. 
Maybe it's on purpose to not provide the complete solution and only some parts to try to replicate by our own what you have described in your desciptions. If yes, i can clearly understand this position. But the question on "Are there any plans of making the Objectron model open source ?" remains unanswered.

Maybe I simply miss a file somewhere where everything is coded and explained. If that the case, i apologize.

Regards,
--Selim

**Comment by chillbert** [comment]
lame google. lame.
