### ISSUE TITLE
 error: 'boxPoints' is not a member of 'cv'

### ISSUE THREAD

**Issue by jingruhou** [google/mediapipe#160]
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/hjr/develop/projects/mediapipe/mediapipe/calculators/image/BUILD:330:1: C++ compilation of rule '//mediapipe/calculators/image:image_cropping_calculator' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 72 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/image/image_cropping_calculator.cc: In member function 'mediapipe::Status mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*)':
mediapipe/calculators/image/image_cropping_calculator.cc:265:3: error: 'boxPoints' is not a member of 'cv'
   cv::boxPoints(min_rect, src_points);
   ^
In file included from ./mediapipe/framework/calculator_base.h:24:0,
                 from ./mediapipe/framework/calculator_framework.h:54,
                 from mediapipe/calculators/image/image_cropping_calculator.cc:18:
mediapipe/calculators/image/image_cropping_calculator.cc: At global scope:
./mediapipe/framework/calculator_registry.h:24:39: warning: 'mediapipe::calculator_registration_111__' defined but not used [-Wunused-variable]
                                       calculator_registration, name,       \
                                       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:23:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(::mediapipe::CalculatorBaseRegistry, \
   ^
mediapipe/calculators/image/image_cropping_calculator.cc:111:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(ImageCroppingCalculator);
 ^
./mediapipe/framework/calculator_registry.h:28:7: warning: 'mediapipe::access_registration_111__' defined but not used [-Wunused-variable]
       access_registration, name,                                           \
       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:26:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(                                     \
   ^
mediapipe/calculators/image/image_cropping_calculator.cc:111:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(ImageCroppingCalculator);
 ^
cc1plus: warning: unrecognized command line option '-Wno-ignored-attributes'
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.510s, Critical Path: 3.21s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by jingruhou** [comment]
![image](https://user-images.githubusercontent.com/6825570/66533635-358a3980-eb46-11e9-9261-72ca51cf999e.png)

**Comment by mcclanahoochie** [comment]
this error is about cv::boxPoints not being found

which version of opencv do you have? can you upgrade to 3.x or 4.x ?

**Comment by jiuqiant** [comment]
You probably can take a look at https://github.com/google/mediapipe/issues/140 to see if the solution works for you or not.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
