### ISSUE TITLE
cannot able to run the holistic js demo in codepen.

### ISSUE THREAD

**Issue by seamanj** [google/mediapipe#1600]
when I run the holistic js demo (https://codepen.io/mediapipe/pen/LYRRYEw), I got errors like below. Is it possible to fix it?

Thanks

`E0209 06:18:00.916000       1 solutions_wasm.embind.cc:266] Calculator ConstantSidePacketCalculatorUpperBodyOnly not found. holistic_solution_wasm_bin.js:9:80637
E0209 06:18:00.918000       1 solutions_wasm.embind.cc:276] List of calculators holistic_solution_wasm_bin.js:9:80637
-------------------------- holistic_solution_wasm_bin.js:9:80637
 holistic_solution_wasm_bin.js:9:80637
 ConstantSidePacketCalculatorSmoothLandmarks holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__ConstantSidePacketCalculator holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__ImagePropertiesCalculator holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__PreviousLoopbackCalculator holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__GateCalculator_1 holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__PacketPresenceCalculator holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__GateCalculator_2 holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__facelandmarksfromposegpu__ImagePropertiesCalculator holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__posedetectiongpu__ImageToTensorCalculator holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__posedetectiongpu__InferenceCalculator holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__posedetectiongpu__SsdAnchorsCalculator holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__posedetectiongpu__TensorsToDetectionsCalculator holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__posedetectiongpu__NonMaxSuppressionCalculator holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__posedetectiongpu__DetectionLetterboxRemovalCalculator holistic_solution_wasm_bin.js:9:80637
 holisticlandmarkgpu__poselandmarkgpu__SplitDetectionVectorCalculator`

**Comment by afogel** [comment]
it's also broken on the mediapipe hosted demo: https://mediapipe.dev/demo/holistic

**Comment by afogel** [comment]
@eknight7 any updates on this?

**Comment by tyrmullen** [comment]
This should be fixed in the next update; will close issue at that time.

**Comment by afogel** [comment]
Thank you @tyrmullen!

**Comment by martincho0731** [comment]
> también está roto en la demostración alojada de mediapipe: https://mediapipe.dev/demo/holistic
> 
> Creo que ha estado roto durante al menos una semana, ya que tuve problemas similares al ejecutar la demostración web, pero no había profundizado demasiado hasta ahora.

**Comment by martincho0731** [comment]
hi, could the problem be in the chrome browser?  Does anyone know what is happening?  I need a solution for this please

**Comment by tyrmullen** [comment]
It should now be fixed with the latest push; see if it works for you now?  I left additional comments on #1621 .

**Comment by rmothukuru** [comment]
@seamanj,
Can you please respond to the above comment? Thanks!

**Comment by sgowroji** [comment]
Closing this as it is resolved
