### ISSUE TITLE
Debug build works fine but Release build on IOS hangs or crashes at gl rendering,

### ISSUE THREAD

**Issue by PoseAI** [google/mediapipe#1603]
I have an issue where the release build on IOS (using the bazel/tulsi/Xcode pipeline as per MediaPipe recommendation) regularly hangs.  Frustratingly the debug build version works fine which makes debugging challenging. 

IOS Version: 14.3
Bazel: 3.7.2
Xcode: 12.4
Mediapipe: latest (ea8d45731f5a052f79745e35bfd8240d6ac568d2)

I will explain our use case below and the suspected culprit but for potential reproducibility I can get a similar outright crash just using the demo holistic tracking app.  In release build, if I switch the MediaPipe app to the background and foreground a few times (say opening a safari page), the mediapipe release build eventually freezes and then crashes (sometimes this happens immediately, sometimes after a few switches).  The debug version works fine even if I switch back and forth a dozen times.  I can't be sure this is the exact same problem as the demo app is simpler, but hopefully it highlights something not WAI between debug and release.

My own issue is in our app which (i) launches an MPP graph with rendered output stream, (ii) at some point user returns to a menu screen (cancelling graph) and (iii) then the user relaunches.  In debug build everything works.  In release build the app usually hangs on step (iii), rendering one or two frames and then taking 10-30 seconds per frame (instead of 30+ frames per second!) and the UI becomes unresponsive (not completely, but tapping to go back to menu takes another 10-30 seconds).  Occasionally it resolves itself back to working smoothly after a minute, usually not.  Sometimes it completely hangs. Surprisingly it almost never outright crashes.   
 
The call in line  "MPPLayerRenderer.m" line 74 to [_glRenderer.glContext presentRenderbuffer:GL_RENDERBUFFER] seems to be where the app hangs.  If I comment it out in release build, it obviously disables rendering of the output on the phone, but the MPP graph performs as expected (I stream model results to the desktop which works fine) => I believe the rendering is the problem.   I have tried using a single render object and also creating a new one each time a new graph is launched.   I note that glContext and the mutex functionality used in MPP modules is deprecated by Apple since IOS 12.

Can anyone shed light on what the problem could be?

**Comment by sgowroji** [comment]
Hi @PoseAI, Could you please share your issue status ?

**Comment by PoseAI** [comment]
AFAIK it is still an issue. We moved forward by avoiding the mediapipe render pipeline and using native IOS rendering function calls if we want to show the camera feed (we don’t use any of the MP primitive drawing on the camera image).

**Comment by sgowroji** [comment]
Good to know you got some workaround. Closing this ticket.
