### ISSUE TITLE
Holistic and Pose tracking ARR build error

### ISSUE THREAD

**Issue by dhanajik** [google/mediapipe#1607]
Hi 
I have successfully build arr for hand tracking.

I am facing the below error while building arr for holistic tracking and pose tracking. Please advice
Environment - 
Ubuntu 20.04
Bazel - 4.0

--------- BUILD-----
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_holistic_tracking",
    calculators = ["//mediapipe/graphs/pose_tracking:mobile_calculators"],
)
-------- End --------------

-------- Error -----------
ERROR: /mnt/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/holistic_arr/BUILD:3:14: no such target '//mediapipe/graphs/pose_tracking:mobile_calculators': target 'mobile_calculators' not declared in package 'mediapipe/graphs/pose_tracking' defined by /mnt/mediapipe/mediapipe/graphs/pose_tracking/BUILD and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/holistic_arr:libmediapipe_jni.so'
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/holistic_arr:mp_holistic_tracking' failed; build aborted: Analysis failed

Thank you
Dhan

**Comment by jiuqiant** [comment]
Hi,

If you take a look at the example app's build file: https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu/BUILD#L24

It should be 

```
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
name = "mp_holistic_tracking",
calculators = ["//mediapipe/graphs/pose_tracking:mobile_calculators"],
)
```

**Comment by dhanajik** [comment]
Thank you very much.

I have using the arr file with Unity game engine. I hope this will be the right approach to implement Mediapipe with unity.

Thank you aganin for quick respone.

Thank you
Dhan
