### ISSUE TITLE
Error executing with bazel "/usr/bin/env:'python': No such file or directory"

### ISSUE THREAD

**Issue by dilipxp** [google/mediapipe#1608]
I'm using Ubuntu20.04 LTS
Android 4.1.2
NDK -version 19.2

while executing I getting error  /usr/bin/env: 'python': No such file or directory
I've python3.8 and python3.7 installed 
python3.7 as python
and python3.8 as python3   

INFO: Found 1 target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[1,279 / 3,584] Desugaring external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/incrementaldeployment/libincremental_stub_application.jar for Android; 0s worker ... (46 actions, 4 running)
[1,298 / 3,927] Desugaring external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/incrementaldeployment/libincremental_stub_application.jar for Android; 2s worker ... (128 actions, 4 running)
[1,298 / 3,927] Desugaring external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/incrementaldeployment/libincremental_stub_application.jar for Android; 4s worker ... (128 actions, 5 running)
[1,303 / 3,927] [Sched] Desugaring external/maven/_aar/androidx_annotation_annotation_experimental/classes_and_libs_merged.jar for Android; 5s ... (128 actions, 4 running)
[1,304 / 3,927] [Sched] Desugaring external/maven/_aar/androidx_annotation_annotation_experimental/classes_and_libs_merged.jar for Android; 7s ... (128 actions, 4 running)
ERROR: /home/dilipxp/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/BUILD:35:15: Injecting mobile install stub application failed: (Exit 127): stubify_manifest failed: error executing command bazel-out/k8-py2-opt-exec-50AE0418/bin/external/bazel_tools/tools/android/stubify_manifest '--mode=mobile_install' --input_manifest ... (remaining 7 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox stubify_manifest failed: error executing command bazel-out/k8-py2-opt-exec-50AE0418/bin/external/bazel_tools/tools/android/stubify_manifest '--mode=mobile_install' --input_manifest ... (remaining 7 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
**/usr/bin/env: 'python': No such file or directory**
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 16.769s, Critical Path: 9.36s
INFO: 138 processes: 127 internal, 1 linux-sandbox, 10 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by dilipxp** [comment]
I solved the previous issue but now i'm getting this in bazel console

-------------------------------------------------------------------------------------------
Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: /usr/bin/bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --

Command: git diff --name-status --no-renames 39309bedba255aee2a4f31b29b65609857698ada

Computing VCS working set...
  .aswb/.bazelproject (added)
  .aswb/.blaze/modules/.project-data-dir.iml (added)
  .aswb/.blaze/modules/.workspace.iml (added)
  .aswb/.idea/.gitignore (added)
  .aswb/.idea/.name (added)
  .aswb/.idea/misc.xml (added)
  .aswb/.idea/modules.xml (added)
  .aswb/.idea/runConfigurations.xml (added)
  .aswb/.idea/vcs.xml (added)
  WORKSPACE (modified)
  setup_opencv.sh (modified)
  third_party/opencv_linux.BUILD (modified)

Querying targets building source files...
Command: /usr/bin/bazel query --tool_tag=ijwb:AndroidStudio --output=label_kind --keep_going same_pkg_direct_rdeps(//:WORKSPACE+//:setup_opencv.sh+//third_party:opencv_linux.BUILD) --

Sync targets from project view targets:
  //mediapipe/examples/android/...:all
  //mediapipe/java/...:all

Building Bazel targets...
Command: /usr/bin/bazel build --tool_tag=ijwb:AndroidStudio --keep_going --build_event_binary_file=/tmp/intellij-bep-b3df5b5c-540b-49a1-a7b7-a7ca56b29fc4 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --noexperimental_run_validations --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/home/dilipxp/.local/share/Google/AndroidStudio4.1/aswb/aspect --output_groups=intellij-info-android,intellij-info-generic,intellij-info-java,intellij-render-resolve-android,intellij-resolve-android,intellij-resolve-java -- //mediapipe/examples/android/...:all //mediapipe/java/...:all

Loading: 
Loading: 0 packages loaded
Analyzing: 82 targets (0 packages loaded, 0 targets configured)
INFO: Analyzed 82 targets (0 packages loaded, 0 targets configured).
INFO: Found 82 targets...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: /home/dilipxp/.cache/bazel/_bazel_dilipxp/fa1bc363b497d559fab404c1ddfd8cbd/external/intellij_aspect/BUILD.bazel:23:12: Building external/intellij_aspect/PackageParser_bin.jar () [for host] failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/.cache/bazel/_bazel_dilipxp/fa1bc363b497d559fab404c1ddfd8cbd/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/BUILD:8:12: Building external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:35:16: Building mediapipe/java/com/google/mediapipe/framework/libandroid_framework_no_mff.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:268:16: Building third_party/libcamerax_core.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:275:16: Building third_party/libcamerax_lifecycle.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:226:16: Building third_party/libandroidx_constraint_layout.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:35:16: Building mediapipe/java/com/google/mediapipe/framework/libandroid_framework_no_mff.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:126:16: Building mediapipe/java/com/google/mediapipe/framework/libmediapipe_exception_android.jar (1 source file) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:212:16: Building third_party/libandroidx_annotation.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:233:16: Building third_party/libandroidx_core.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:219:16: Building third_party/libandroidx_appcompat.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/java/com/google/mediapipe/components/BUILD:65:16: Building mediapipe/java/com/google/mediapipe/components/libandroid_microphone_helper.jar (4 source files) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:254:16: Building third_party/libandroidx_recyclerview.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/.cache/bazel/_bazel_dilipxp/fa1bc363b497d559fab404c1ddfd8cbd/external/intellij_aspect/BUILD.bazel:35:12: Building external/intellij_aspect/CreateAar_bin.jar () [for host] failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:261:16: Building third_party/libcamerax_camera2.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:261:16: Building third_party/libcamerax_camera2.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:240:16: Building third_party/libandroidx_legacy_support_v4.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:240:16: Building third_party/libandroidx_legacy_support_v4.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:275:16: Building third_party/libcamerax_lifecycle.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:24:16: Building mediapipe/java/com/google/mediapipe/framework/libandroid_framework.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:233:16: Building third_party/libandroidx_core.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:126:16: Building mediapipe/java/com/google/mediapipe/framework/libmediapipe_exception_android.jar (1 source file) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:268:16: Building third_party/libcamerax_core.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:212:16: Building third_party/libandroidx_annotation.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:219:16: Building third_party/libandroidx_appcompat.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:254:16: Building third_party/libandroidx_recyclerview.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:24:16: Building mediapipe/java/com/google/mediapipe/framework/libandroid_framework.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/third_party/BUILD:226:16: Building third_party/libandroidx_constraint_layout.jar () failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/graphs/instant_motion_tracking/calculators/BUILD:21:14: Building mediapipe/graphs/instant_motion_tracking/calculators/libsticker_buffer_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:90:24: Building mediapipe/framework/libpacket_generator_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/graphs/instant_motion_tracking/calculators/BUILD:21:14: Building mediapipe/graphs/instant_motion_tracking/calculators/libsticker_buffer_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:103:16: Building mediapipe/java/com/google/mediapipe/framework/libframework_proto_lite.jar (3 source files) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/tool/BUILD:44:24: Building mediapipe/framework/tool/libcalculator_graph_template_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/formats/BUILD:251:24: Building mediapipe/framework/formats/liblandmark_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:78:24: Building mediapipe/framework/libmediapipe_options_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/deps/BUILD:24:14: Building mediapipe/framework/deps/libproto_descriptor_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/formats/BUILD:69:24: Building mediapipe/framework/formats/libmatrix_data_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:112:24: Building mediapipe/framework/libstream_handler_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:51:24: Building mediapipe/framework/libcalculator_options_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:105:24: Building mediapipe/framework/libstatus_handler_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:51:24: Building mediapipe/framework/libcalculator_options_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:84:24: Building mediapipe/framework/libpacket_factory_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/.cache/bazel/_bazel_dilipxp/fa1bc363b497d559fab404c1ddfd8cbd/external/com_google_protobuf/BUILD:313:15: Building external/com_google_protobuf/libany_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:36:24: Building mediapipe/framework/libcalculator_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:73:16: Building mediapipe/java/com/google/mediapipe/framework/libandroid_core.jar (16 source files) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:103:16: Building mediapipe/java/com/google/mediapipe/framework/libframework_proto_lite.jar (3 source files) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/modules/face_geometry/protos/BUILD:43:24: Building mediapipe/modules/face_geometry/protos/libmesh_3d_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:105:24: Building mediapipe/framework/libstatus_handler_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:84:24: Building mediapipe/framework/libpacket_factory_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:90:24: Building mediapipe/framework/libpacket_generator_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/.cache/bazel/_bazel_dilipxp/fa1bc363b497d559fab404c1ddfd8cbd/external/com_google_protobuf/BUILD:313:15: Building external/com_google_protobuf/libany_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:112:24: Building mediapipe/framework/libstream_handler_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/deps/BUILD:24:14: Building mediapipe/framework/deps/libproto_descriptor_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:36:24: Building mediapipe/framework/libcalculator_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/tool/BUILD:44:24: Building mediapipe/framework/tool/libcalculator_graph_template_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:78:24: Building mediapipe/framework/libmediapipe_options_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:73:16: Building mediapipe/java/com/google/mediapipe/framework/libandroid_core.jar (16 source files) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:68:24: Building mediapipe/framework/libcalculator_profile_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/framework/BUILD:68:24: Building mediapipe/framework/libcalculator_profile_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
ERROR: /home/dilipxp/mediapipe/mediapipe/modules/face_geometry/protos/BUILD:26:24: Building mediapipe/modules/face_geometry/protos/libface_geometry_proto-lite.jar (1 source jar) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
INFO: Elapsed time: 1.038s, Critical Path: 0.29s
INFO: 61 processes: 61 internal.
FAILED: Build did NOT complete successfully
---------------------------------------------------------------------------------------------------------------------------------------------------------
also getting this in bazel problem console

Error:/home/dilipxp/.cache/bazel/_bazel_dilipxp/fa1bc363b497d559fab404c1ddfd8cbd/external/intellij_aspect/BUILD.bazel:23:12: Building external/intellij_aspect/PackageParser_bin.jar () [for host] failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)

**Comment by dilipxp** [comment]
Also I'm getting this message 

INFO: From ProtoCompile mediapipe/calculators/util/detections_to_rects_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.

**Comment by sgowroji** [comment]
Hi @dilipxp, Could you please confirm whether the issue still exists?

**Comment by dilipxp** [comment]
Yes, Some how I able to solve it for some time but I run the  `bazel clean` command and It showing again.
I just want to know if this issue related to my environment or something else causing this error 

INFO: From ProtoCompile mediapipe/calculators/util/detections_to_rects_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.

**Comment by dilipxp** [comment]
It solved.
