### ISSUE TITLE
Failed to run the demo: Side packet "num_hands" is required but was not provided.

### ISSUE THREAD

**Issue by Nyohohoho** [google/mediapipe#1609]
Thank you for your great work and sharing.
I am trying to follow your instruction here: https://google.github.io/mediapipe/getting_started/cpp.html
I am hoping to try your solution on my own GPU, and test the runtime.

Enviroment:
* Desktop
* Ubuntu 20.04

However, the message below returned while building hand tracking. (CPU version is OK.)
The similar message also returned while building face mesh. (num_hands -> num_faces)

```
I20210212 16:33:36.260129 233026 demo_run_graph_main_gpu.cc:51] Get calculator graph config contents: # MediaPipe graph that performs multi-hand tracking with TensorFlow Lite on GPU.
# Used in the examples in
# mediapipe/examples/android/src/java/com/mediapipe/apps/handtrackinggpu.

# GPU image. (GpuBuffer)
input_stream: "input_video"

# Max number of hands to detect/process. (int)
input_side_packet: "num_hands"

# GPU image. (GpuBuffer)
output_stream: "output_video"
# Collection of detected/predicted hands, each represented as a list of
# landmarks. (std::vector<NormalizedLandmarkList>)
output_stream: "hand_landmarks"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Detects/tracks hand landmarks.
node {
  calculator: "HandLandmarkTrackingGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "NUM_HANDS:num_hands"
  output_stream: "LANDMARKS:hand_landmarks"
  output_stream: "HANDEDNESS:handedness"
  output_stream: "PALM_DETECTIONS:palm_detections"
  output_stream: "HAND_ROIS_FROM_LANDMARKS:hand_rects_from_landmarks"
  output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:hand_rects_from_palm_detections"
}

# Subgraph that renders annotations and overlays them on top of the input
# images (see hand_renderer_gpu.pbtxt).
node {
  calculator: "HandRendererSubgraph"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "DETECTIONS:palm_detections"
  input_stream: "LANDMARKS:hand_landmarks"
  input_stream: "HANDEDNESS:handedness"
  input_stream: "NORM_RECTS:0:hand_rects_from_palm_detections"
  input_stream: "NORM_RECTS:1:hand_rects_from_landmarks"
  output_stream: "IMAGE:output_video"
}
I20210212 16:33:36.260536 233026 demo_run_graph_main_gpu.cc:57] Initialize the calculator graph.
I20210212 16:33:36.263046 233026 demo_run_graph_main_gpu.cc:61] Initialize the GPU.
I20210212 16:33:36.268653 233026 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I20210212 16:33:36.302696 233059 gl_context.cc:324] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 460.32.03)
I20210212 16:33:36.302765 233026 demo_run_graph_main_gpu.cc:67] Initialize the camera or load the video.
Gtk-Message: 16:33:36.442: Failed to load module "canberra-gtk-module"
I20210212 16:33:36.449548 233026 demo_run_graph_main_gpu.cc:88] Start running the calculator graph.
E20210212 16:33:36.462474 233026 demo_run_graph_main_gpu.cc:196] Failed to run the graph: ValidateRequiredSidePackets failed to validate: 
; Side packet "num_hands" is required but was not provided.
```

I will appreciate if you can help me solve the problem.
By the way, on which file should I use to add some time measurement codes written by myself?

**Comment by milad-4274** [comment]
In your graph, it's expected to get num_hands as input_side packet.
I'm not sure but try to add `--num_hands=2` after command to run the graph.
`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu \
  --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt  --num_hands=1`

I think you can also change the graph, cause the `hand_tracking_mobile` graph designed to perform on mobile. try this command too:
`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu \
  --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live_gpu.pbtxt`
that does not expect `num_hands` as input and it defined in graph usong `ConstantSidePacketCalculator`.

**Comment by rmothukuru** [comment]
@Nyohohoho,
Can you please try the steps mentioned in the [above comment](https://github.com/google/mediapipe/issues/1609#issuecomment-778572223)  and let us know if the error still persists? Thanks!

**Comment by rmothukuru** [comment]
@Nyohohoho,
 Can you please respond to the above comment? Thanks!

**Comment by Nyohohoho** [comment]
> @Nyohohoho,
> Can you please respond to the above comment? Thanks!

I am really sorry for the late response.
The second one worked!

**Comment by sgowroji** [comment]
We are glad to see you resolved.

**Comment by darkthecross** [comment]
Can we also update related documents? https://google.github.io/mediapipe/getting_started/cpp.html#option-2-running-on-gpu

**Comment by roachsinai** [comment]
> @Nyohohoho, Can you please respond to the above comment? Thanks!

But the first solution not works, got below error:

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu \
  --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt --num_hands=2
ERROR: Unknown command line flag 'num_hands
