### ISSUE TITLE
rules_foreign_cc url seems incorrect in the WORKSPACE

### ISSUE THREAD

**Issue by sharif1093** [google/mediapipe#1610]
In `WORKSPACE`, shouldn't [the url](https://github.com/google/mediapipe/blob/39309bedba255aee2a4f31b29b65609857698ada/WORKSPACE#L42) to the rules_foreign_cc repository read as: `https://github.com/bazelbuild/rules_foreign_cc/archive/main.zip`? The current URL results in `404: Not found` error. I am using Bazel 4.0.0. I got the same error with Bazel `3.4.1`, too. It seems that the `master` branch has been renamed to `main` in `rules_foreign_cc`.

Also, the line above the URL needs to be `strip_prefix = "rules_foreign_cc-main",` for me to work.

Environment:
- Ubuntu 18.04 (docker)
- Bazel 3.4.1, 3.7.2, or 4.0.0

**Comment by amanjain7838** [comment]
I also faced this issue. I guessed they renamed the branch.

**Comment by jiuqiant** [comment]
Yes, they renamed the branch to main. However, they realize this is a problem for those projects that depend on the master branch. So, they add the master branch back. For now, it should work again. But, we will switch to its main branch in the coming release.
