### ISSUE TITLE
[Objectron] How to make custom model.obj.uuu

### ISSUE THREAD

**Issue by Nekokojpn** [google/mediapipe#1613]
Hello. I want to make virtual shoe app using mediapipe objectron.
I think rendering virtual shoe using model.obj.uuu and texture.jpg.
But, I can't understand format for model.obj.uuu.
Does anyone know how to replace this with my shoes?
Thanks.

**Comment by tyrmullen** [comment]
I think this will be covered in the responses https://github.com/google/mediapipe/issues/1074, so closing as duplicate.
