### ISSUE TITLE
Issues in extracting keypoints with face detection example

### ISSUE THREAD

**Issue by Noricks** [google/mediapipe#1616]
Hi, 

Thank you for taking the time to read this comment. Hope it is the correct place to put my questions.
The same problem as issue #488 occurs to me when I build my `face_detection` app.

### My Environment/Settings
Generally, I used the official (I guess) example provided to build my `face_detection` app: https://github.com/jiuqiant/mediapipe_face_detection_aar_example

I read the #454, #488 and then examed the Classes in the pre-built `mp_face_detection_aar.aar` in the example application.
Based on my own understanding, the pre-built `.AAR`  is correct to extract key points.

Note: The version is relatively old, **v0.7.5**

### Error Description
1. The original example works well.
2.  If I add the following codes, the code works well and will Log the address of the `Packet`
```java
        processor.addPacketCallback(
                OUTPUT_HAND_PRESENCE_STREAM_NAME,
                (packet) -> {
                    Log.d(
                            TAG,
                            "[TS:" + packet.getTimestamp() + "]" + packet.toString());
                });
```
3. However, when adding methods related to `PacketGetter`, an error will occur.

```java
        processor.addPacketCallback(
                "labeled_detections", // outputStream
                (packet) -> {
                    byte[] handPresence = PacketGetter.getProtoBytes(packet);
                    Log.d(
                            TAG,
                            "[TS:" + packet.getTimestamp() + "]" + packet.toString());
                });
```
The related error code from the Android Log is:  
```
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 5846 (Thread-5), pid 5671 (acedetectionapp)
```

4. Meanwhile, the `outputStream` named with `anchors`  could not be interpreted (i.e. an illegal name).  
The `anchors` is introduced as `output_side_packet: "anchors"` in  `face_detection_mobile_gpu.pbtxt`. This problem also confused me.

### Attempts for solving the problem
1. Try different `outputStream` based on the `face_detection_mobile_gpu.pbtxt`.
2. Try different methods in the `PacketGetter`
3. Add `implementation group: 'com.google.protobuf', name: 'protobuf-java', version: '3.10.0'` to the build file.

### Links
`face_detection_mobile_gpu.pbtxt` of **v0.7.5** for this ARR: https://github.com/google/mediapipe/blob/v0.7.5/mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt
(newer version has different naming)

### Thanks
Any help is appreciated.
Thank you again in the end!

**Comment by sgowroji** [comment]
Hi @Noricks, Could you please confirm whether the above issue still exists ?

**Comment by sgowroji** [comment]
Hi @Noricks, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this ticket due to lack of activity.

**Comment by Noricks** [comment]
> Hi @Noricks, Could you please respond to my above comment. Thanks!

Sorry for the late reply.

As I stated in the problem description, the prebuild **v0.7.5** .ARR package provided in the tutorial repository has some problems with the code. 

I rebuild the .arr package from scratch based on the latest official tutorial, everything works fine.  

In my view, I think this might because of the old prebuild **v0.7.5** .ARR package is incompatible with the code related to `PacketGetter` (copied from the latest official tutorial). It seems that the `PacketGetter` related code was not compiled to the **v0.7.5** .ARR package and the package might be relatively old for the new function.

Thank you for your attention and patience!
