### ISSUE TITLE
Canonical face model: how to get the landmarks (x,y,z) coordinates?

### ISSUE THREAD

**Issue by ianni67** [google/mediapipe#1618]
Hello, I'm trying to project a point, that is anchored to some face landmarks, from the canonical face model to the 2D face coordinates through the Face pose transformation matrix. 
I need to retrieve the 3D normalized coordinates of the landmarks from the canonical face model. Anyone may give me some hint?
Thank you!

**Comment by ianni67** [comment]
Ok, I found it. The landmarks are stored in the mesh structure from the FaceGeometry class.

**Comment by ianni67** [comment]
I'm still in trouble. After reading face_geometry.proto and mesh_3d.proto and doing some tests I feel I'm off-road.
How do I access the landmarks from the canonical face model? Currently I can easily access the updated landmarks but have no clear idea about how to access the 3D landmarks from the canonical model.

**Comment by kostyaby** [comment]
Hey @ianni67,

There are at least 3 ways to access the canonical face mesh landmarks:

1) Parse / pre-process landmarks from [canonical_face_mesh.obj](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model.obj)

2) Parse / pre-process landmarks from [geometry_pipeline_metadata.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata.pbtxt)

3) In runtime, parse the compiled `geometry_pipeline_metadata.binarypb` like it's done [here](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/geometry_pipeline_calculator.cc#L161-L172)

**Comment by ianni67** [comment]
Thank you very much @kostyaby for your suggestions. I did find the first one by myself yesterday, by carefully parsing the past issues in this github. Now I'm fighting with the next steps... :-) Sorry for forgetting to close the issue yesterday.
I'm convinced that your answers will help other people to save quite a bit of time.

**Comment by joeapiwit** [comment]
@kostyaby 
Could you please confirm that the unit of the coordinate x,y,z  of vertices that we get from the canonical face 
(Parse / pre-process landmarks from canonical_face_mesh.obj)
are in centimeters. For example, if I calculate Euclidean distance between any two points i.e. (x1,y1,z1) and (z2,y2,z2)
The distance I will get is in centimeters? Thank you very much in advance!

**Comment by kostyaby** [comment]
Hey @joeapiwit,

Yeah, those are centimeters. This, in turn, implies that all Face Geometry module outputs are in centimeters as well

**Comment by joeapiwit** [comment]
> Hey @joeapiwit,
> 
> Yeah, those are centimeters. This, in turn, implies that all Face Geometry module outputs are in centimeters as well

Thank you very much!
So, did you mean not only the unit of canonical face model is in centimeters but the unit I got when I ran `face_mesh.process(myPicture).multi_face_landmarks` (all the (x,y,z )I got) is also in centimeters as well?

**Comment by kostyaby** [comment]
Hey @joeapiwit,

Face Mesh module is different from Face Geometry module ([list of modules](https://github.com/google/mediapipe/tree/master/mediapipe/modules)). The Face Mesh module operates in relative screen coordinate space, so it's not centimeters
