### ISSUE TITLE
How to get Iris depth？

### ISSUE THREAD

**Issue by MikeDean2367** [google/mediapipe#1619]
I used the iris_tracking_gpu.pbtx to build my program (in Android Studio). The distance display can be seen in the generated program.  So What do I have to do to get that value？I looked up a lot of information but couldn't solve it. I'd appreciate if you could help me.  Thxs.

**Comment by fahadhaq** [comment]
@MikeDean2367 Did you manage to solve this issue?

**Comment by sgowroji** [comment]
Please go through this for your answer https://google.github.io/mediapipe/solutions/iris.html#depth-from-iris
