### ISSUE TITLE
Mediapipe Holistic js Does not start

### ISSUE THREAD

**Issue by martincho0731** [google/mediapipe#1621]
Because I can't run mediapipe holistic js, will it fix the error?  I have a project, and I am extremely concerned about this, as nothing works for me.  Can somebody help me?

**Comment by martincho0731** [comment]
> Como no puedo ejecutar js holístico de mediapipe, ¿solucionará el error? Tengo un proyecto y estoy muy preocupado por esto, ya que nada me funciona. ¿Puede alguien ayudarme?

@tyrmullen help me

**Comment by afogel** [comment]
@martincho0731 linked to #1600 
you can try a prior version of holistic from npm, like version: 0.1.1607486640

**Comment by martincho0731** [comment]
@afogel
 hi, i'm using cdn, i'm not using npm.  I am using the same example you have in the web demo.  What is happening ? https://codepen.io/mediapipe/pen/LYRRYEw

**Comment by martincho0731** [comment]
hi, could the problem be in the chrome browser?  Does anyone know what is happening?  I need a solution for this please

**Comment by afogel** [comment]
nope, the demo is broken cross browser rn.
To get it to work, the best situation I've found is to go through the minified version and figure out what you need in order to run it.
CDN does use npm.
Another option I'm currently exploring is setting up a backend service in python and pushing webcam images through a socket. There just isn't great support for the JS solution rn, to the best of my understanding.

**Comment by tyrmullen** [comment]
It should be fixed now for Desktop Chrome with latest push.  Try https://mediapipe.dev/demo/holistic and see if it works.

(To make sure your browser isn't caching a stale version, you can open the JS Console, check the "Disable cache" box under the "Network" tab, and then leave the JS Console open while loading the page).

**Comment by afogel** [comment]
Amazing! Thank you so much @tyrmullen ~~

**Comment by martincho0731** [comment]
> Debería arreglarse ahora para Desktop Chrome con el último empuje. Pruebe https://mediapipe.dev/demo/holistic y vea si funciona.
> 
> (Para asegurarse de que su navegador no almacena en caché una versión obsoleta, puede abrir JS Console, marcar la casilla "Deshabilitar caché" en la pestaña "Red" y luego dejar JS Console abierta mientras carga la página).



> Debería arreglarse ahora para Desktop Chrome con el último empuje. Pruebe https://mediapipe.dev/demo/holistic y vea si funciona.
> 
> (Para asegurarse de que su navegador no almacena en caché una versión obsoleta, puede abrir JS Console, marcar la casilla "Deshabilitar caché" en la pestaña "Red" y luego dejar JS Console abierta mientras carga la página).

**Comment by martincho0731** [comment]
many thanks !!!  thank you so much

**Comment by afogel** [comment]
@tyrmullen Again, thank you for the fast update, it definitely helps a lot. To keep it stable, I'm instantiating the Holistic constructor variable, I'm now setting it to the current version:
```javascript
Holistic({
	locateFile: (file) => {
		return `https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.1.1613603339/${file}`;
	}
})
```
That should be fine, right?

One final question for rn: As I'm perusing through the console logs and I see that it's using a discrete graphics card when possible -- is there a way to simulate running it exclusively using CPU? I'm curious to see how mileage will vary based on a client's hardware.
Thanks again!

**Comment by sgowroji** [comment]
Hi @martincho0731 , Closing it as the issue resolved. Thanks !

**Comment by tyrmullen** [comment]
@afogel To answer your last question: currently that decision is baked into the MediaPipe graph, but that would be an excellent option for us to add-- especially since that should also provide a workaround for issues like #1430.
