### ISSUE TITLE
pip install media-pipe does not work for any python version, MacOS Big Sur 11.2.1

### ISSUE THREAD

**Issue by chrisdoyleIE** [google/mediapipe#1622]
Hi, 

I've tried installing media pipe in various pyenv environments from 3.6.0 right through to 3.8.6. There is a previous issue #1466 that is fixed by using python 3.7.9, but this isn't helping me. The issue remains. Can you please help me?

macOS Big Sur 11.2.1

```bash
(xrc) cp@Christophers-MacBook-Pro ~ % pip install mediapipe
Collecting mediapipe
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

**Comment by chrisdoyleIE** [comment]
I've also tried downloading the binary wheel from [here](https://pypi.org/project/mediapipe/#files), and following the steps [here](https://google.github.io/mediapipe/getting_started/python#building-mediapipe-python-package) which haven't solved the issue.

**Comment by jiuqiant** [comment]
Is your macbook pro with the m1 chip? The wheels are for x86_64 only.

**Comment by chrisdoyleIE** [comment]
Nope, intel chip. I've completely nuked my hard drives after a messy Catalina install so it'll be a few hours / days before I can replicate

**Comment by jiuqiant** [comment]
It works on my end... Could you try what I did to see if there is still a  problem?

![Screen Shot 2021-02-18 at 10 22 06 AM](https://user-images.githubusercontent.com/3359144/108403224-5b602d80-71d3-11eb-8a5f-6f532f5d4c11.png)

**Comment by rtrjmishra** [comment]
@jiuqiant Could you please help me in installing MediaPipe on my macOS Big Sur 11.5.1 M1 and python=3.8.10
Thank you.

**Comment by saltfish13** [comment]
it seems M1 is not currently supported

**Comment by justin-f-perez** [comment]
@rtrjmishra @saltfish13 see: https://github.com/google/mediapipe/issues/2120#issuecomment-894796864
