### ISSUE TITLE
Training and deploying a gesture recognition model as a calculator from within MediaPipe

### ISSUE THREAD

**Issue by prantoran** [google/mediapipe#1623]
Hello, I am trying to train and deploy a simple model to detect simple dynamic gestures in real time, such as left and right swipes, by taking a sequence of landmarks of the right hand and flattening them into a 1D input array, and then train a classifier. I was wondering how to deploy a trained model in Tensorflow or PyTorch as a calculator within MediaPipe or in C++ built with Bazel. Also, looking forward to any tutorial links of others who have done so.

**Comment by rmothukuru** [comment]
@prantoran,
Can you please confirm if you have gone through [Hands/Gesture Tracking Solution](https://google.github.io/mediapipe/solutions/hands)? Thanks!

**Comment by rmothukuru** [comment]
@prantoran,
Can you please respond to the above comment? Thanks!

**Comment by prantoran** [comment]
Thank you for sharing the blog. I am sorry for the late reply, I am stuck in another feature. 

I read the blog which provide details for Python APIs to access the landmarks. I did the same in C++ to implement detection of static gestures. But in order to detect dynamic gestures, I would need to train a simple classifier using the sequence of landmarks. 

I guess one way is to collect landmarks data for different gestures and save them as datasets, then train and save a Tensorflow classifier in Python script, then load the saved model using loadSavedModel() from within MediaPipe workspace.
