### ISSUE TITLE
For more accuracy of Pose, how about ResNet?

### ISSUE THREAD

**Issue by kteriusghub** [google/mediapipe#1625]
When I ran Pose solution of Mediapipe, it showed the fast speed and light resource usage, however, its accuracy of the joint keypoints was sometimes not good.  From the demonstration video of Pose solution, some hidden keypoints looked like vibrating.
I experianced simmilar result when I applied MobilNet on PoseNet before, and I saw more stable result after applying ResNet50, though the speed performance was lower. 
Current Mediapipe uses MobileNet to detect the body pose to have the best speed performance.
Is there any plan to provide ResNet50 as alternative choice for Pose solution of MediaPipe like PoseNet?

**Comment by billhung** [comment]
I am interested in this discussion, so I subscribed to this issue. Currently looking at Mediapipe Pose and PoseNet. ResNet is interesting but seems to take too much resources so I am giving it a pass. But if ResNet works with Mediapipe, I will have a go.

**Comment by 124bit** [comment]
I’m interested in such thing too

**Comment by 124bit** [comment]
For example for my use-case (sports app) - the speed of Pose is multiple times more than enough, however, accuracy is not enough. In practice, I see that  Resnet base pose estimation networks work much better for me in terms of accuracy.

**Comment by sergeynsa** [comment]
I see all my community is interested in such thing.

**Comment by kteriusghub** [comment]
I try to apply the holistic feature of Mediapipe to my research.
The advantages of mediapipe are fast speed and low resource usage. Even if I suggest ResNet for the recognition accuracy, I also want to keep these advantages for the holistic feature.
So, I suggest the hybrid network to detect the joint points of the body pose, the face mesh and hands.  
 --- ResNet to extract the joint keypoints of the body pose (for the accuracy improvement)
 --- MobileNet to extract the face mesh and hands ( for fast performance and nice accuracy)

When I tested the current version of Mediapipe, the joint keypoints of the face mesh and hands were detected enough with MobilNet. From the document of Mediapipe, the holistic algorithm crops the face and hands after detecting the joint points of the body pose. So, I expect that the hybrid network can be applied to the holistic feature.

**Comment by sureshdagooglecom** [comment]
Hi @kteriusghub ,
Are you still looking for the resolution on this issue.

**Comment by 124bit** [comment]
I’m still interested

**Comment by kteriusghub** [comment]
> Hi @kteriusghub , Are you still looking for the resolution on this issue.

Hi @sureshdagooglecom , I don't look for this resolution on this issue more.
