### ISSUE TITLE
How to select proper Calculators for creating AAR files in android for specific models..

### ISSUE THREAD

**Issue by LegPro** [google/mediapipe#1626]
I followed the steps provided here "**https://google.github.io/mediapipe/getting_started/android_archive_library.html**" to create error.
I created all things successfully. They mention a graph file
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_face_detection_aar",
    calculators = ["//mediapipe/graphs/face_detection:**_mobile_calculators_**"],
)

Then I went to that location **_//mediapipe/graphs/face_detection_**  , In BUILD file i found cc_library mentioned in mediapipe_arr : **_mobile_calculators_**.

In above view, 

for hand tracking i seen above command :
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
name = "mp_multi_hand_aar",
calculators = ["//mediapipe/graphs/hand_tracking:_**multi_hand_mobile_calculators**_"],
)

Then i went to that location //mediapipe/graphs/hand_tracking and tried to find cc_library with name  **_multi_hand_mobile_calculators_** but I didnt find any. Can some one clear my doubt regarding this? how you guys know you have to use **_multi_hand_mobile_calculators_** ? I saw one BUILD in **"//mediapipe/graphs/hand_tracking:multi_hand_mobile_calculators"** directory which contain cc_library name ="mobile_calculators". Please help me understand this selection of calculators. 

**_Also if some one can help me creating holistic aar for android. I will be very thankful for you for your valuable advice advice._**

**Comment by eknight7** [comment]
Adding @gkarpiak to answer the question about missing `multi_hand_mobile_calculators` target.

**Comment by gkarpiak** [comment]
@LegPro could you please try to use `mobile_calculators` instead of `multi_hand_mobile_calculators` and see if it works. (Looks like mediapipe_arr target was not updated during a refactoring.)

**Comment by sgowroji** [comment]
Hi @LegPro Did you get a chance to go through the above comment. Please update.

**Comment by LegPro** [comment]
> Hi @LegPro Did you get a chance to go through the above comment. Please update.

Thanks All Worked Fine. :D

**Comment by LegPro** [comment]
> @LegPro could you please try to use `mobile_calculators` instead of `multi_hand_mobile_calculators` and see if it works. (Looks like mediapipe_arr target was not updated during a refactoring.)

Thanks Its Working and i know how to do it al lthings now :D

**Comment by lhalcyon** [comment]
> 
@LegPro  Have u succeeded on holistic aar build?   I followed the doc to build and crashed at launch .  

Here is my holistic BUILD file ,
```
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_holistic_tracking",
    calculators = ["//mediapipe/graphs/holistic_tracking:holistic_tracking_gpu_deps"],
)
```
Would you share urs?   thanks!
