### ISSUE TITLE
Hands - slow down to 1-3 fps with Chrome 88.0.4324.150

### ISSUE THREAD

**Issue by syanenko** [google/mediapipe#1627]
Found it today with version 0.1.1613506466
Check it: https://mediapipe.dev/demo/hands
Face works as usual fine: https://mediapipe.dev/demo/face_mesh

**Comment by mcclanahoochie** [comment]
Is this still an issue?
What device are you running on?
Can you try updating Chrome?

**Comment by syanenko** [comment]
With Chrome Version 90.0.4430.93 (Official Build) (64-bit) works fine now.

**Comment by sgowroji** [comment]
Thanks for sharing the update. We are closing this issue now.
