### ISSUE TITLE
mediapipe visualizer cannot parse array in values

### ISSUE THREAD

**Issue by honglh** [google/mediapipe#1630]
Load any pbtxt graph with array as values, and visualizer will complain.

For example loading `mediapipe/graphs/object_detection_3d/object_occlusion_tracking_1stage.pbtxt`

```
Parse error at line 79 column 21: Expected "#", ']' or '{'.
```
where line 79:
```
 78       # Re-scale the CAD model to the size of a unit box
 79       model_scale: [0.05, 0.05, 0.05]
```

chromium browser
```
Version 87.0.4280.88 (Official Build) (x86_64)
```

Tried other grpahs with array values `[...]` and have same error

**Comment by sgowroji** [comment]
Hi @honglh, Could you please provide your code changes to understand the issue much better. Thanks!

**Comment by mhays-google** [comment]
Right.  If you just give me the snippet from your graph that is not
parsing, I will make sure to make the necessary changes.

**Comment by mhays-google** [comment]
Never mind... I see your comment up at the top.  I will check this out.

**Comment by mhays-google** [comment]
Fix should be in.  Please verify with your particular graph.  Thank you for the patience.

**Comment by mhays-google** [comment]
This has been fixed and staged.
