### ISSUE TITLE
Using 2D keypoints for drawing 3D bounding box in flutter

### ISSUE THREAD

**Issue by nenenkosi** [google/mediapipe#1631]
I am currently running a tflite Mediapipe model which outputs 8 vertices and the center of 3D bounding boxes
that describe the detected objects 3D bounding box. So I would like to know how to draw a 3D bounding box in my Flutter App using the output below.

This is the current OutputTensor am receiving from my tflite model and I want use to draw the 3D bounding box

flutter: [120.87956237792969, 115.73860168457031, 138.97604370117188, 187.78915405273438, 137.4835205078125, 84.2886734008789, 151.32508850097656, 165.74168395996094, 146.28330993652344, 51.38185501098633, 95.4119873046875, 181.07603454589844, 97.72759246826172, 77.48689270019531, 100.90084838867188, 155.7063751220703, 101.90467071533203, 40.651939392089844]

**Comment by ahmadyan** [comment]
Flutter is not directly supported. However, we are working on running Mediapipe graphs through WebAssembly. Then you should be able to use it on Flutter (with Dart).  You can also refer to this [example](https://github.com/zhouzaihang/flutter_hand_tracking_plugin) on how to use Mediapipe with flutter.

Regarding your question, the output of the two stage model is a 9x2 array, xy position of the center + 8 vertices of the bounding box. In our graphs, we lift these 2D keypoints for 3D using EPNP algorithm.

**Comment by nenenkosi** [comment]
When do you think the Mediapipe graphs through WebAssembly will be released
so I can try and use it in my app
