### ISSUE TITLE
How to convert vector<float> to gpubuffer for render on iOS ?

### ISSUE THREAD

**Issue by tuan4192** [google/mediapipe#1632]
I have a grba image with type vector<float>
`std::vector<float> image_datas(width * height * 4);`
How can i convert to `mediapipe::GpuBuffer`?
Thanks for your help!

**Comment by sgowroji** [comment]
Can you please elaborate? Thanks!

**Comment by tuan4192** [comment]
`      

        #include <metal_stdlib>
        using namespace metal;
        kernel void decodeKernel(
        device float* data_out [[ buffer(0) ]],
        device float* out_buf [[ buffer(1) ]],
        device float* data_in [[ buffer(2) ]],
        texture2d<half, access::sample> in_tex  [[ texture(3) ]],`

I have a kernel function to process texture2d, output is `device float* out_buf [[ buffer(1) ]],` (rgba image data).

`[command_encoder setBuffer:gpu_data_->image_out
                            offset:0
                            atIndex:1];`
i want to output a Gpubuffer to tag `kTensorsGpuImage`   `cc->Outputs().Tag(kTensorsGpuImage).Set<mediapipe::GpuBuffer>();`
Do you have any slution? thank you  mutch!
Sorry for my english!

**Comment by hadon** [comment]
I think you can use the API functions:
  GlCalculatorHelper::CreateSourceTexture,
  GlTexture::GetFrame<GpuBuffer>,
as they are used in: ImageFrameToGpuBufferCalculator::Process.  

In ImageFrameToGpuBufferCalculator, the pixel data vector arrives in an ImageFrame, which is MediaPipe's usual image data structure.  In your use case, you can construct an ImageFrame from your pixel data vector, and then convert that to a GpuBuffer as in ImageFrameToGpuBufferCalculator.

**Comment by sgowroji** [comment]
Hi @tuan4192, Please go through  the above comment. Thanks!

**Comment by sgowroji** [comment]
Hi @tuan4192, Can you respond to my above comment. Thanks!

**Comment by tuan4192** [comment]
Hi @hadon, Thanks for your answer, I will try to do it.
Now, I changed the output of the MTLCompute to `MTLTexture`
`id<MTLTexture> out_texture`
 I want to convert out_texture to `CVPixelBufferRef`()
`GetFrame<GpuBuffer>()` can not use in  MTLTexture.
if you have any solution, please let me know, thank you so mutch!

**Comment by hadon** [comment]
I don't know many details about MediaPipe iOS.  I will defer to my colleague @NikolayChirkov to provide any hints about converting MTLTexture.

**Comment by sureshdagooglecom** [comment]
Hi @tuan4192 ,
Are you still looking for the resolution on this issue.
