### ISSUE TITLE
missing input file 'external/androidsdk/build-tools/28.0.3/aapt2

### ISSUE THREAD

**Issue by NguyenLong-02** [google/mediapipe#1633]
![image](https://user-images.githubusercontent.com/74131842/108455626-2b7f5b80-72a1-11eb-9d09-1c006fe3f46a.png)
![image](https://user-images.githubusercontent.com/74131842/108455722-52d62880-72a1-11eb-8ebd-d0aeb33d3a4c.png)
![image](https://user-images.githubusercontent.com/74131842/108455763-697c7f80-72a1-11eb-9bf9-586a22f0c84c.png)

So when i Build AAR file in WSL then it's give me error missing input file (in picture)  but when i check the directory /root/.cache/bazel/_bazel_root/0505f157c249bce4e2dbda8c7d819117/external/androidsdk/build-tools/28.0.3/aapt2 in linux it's already exist 
Here : 
![image](https://user-images.githubusercontent.com/74131842/108456000-e4459a80-72a1-11eb-9590-7dbf3a99dc97.png)
 
Please help me with this issue i have spend so much time for this.

Thanks a lot !!!

**Comment by ksyao2002** [comment]
I am getting the same issue

**Comment by sgowroji** [comment]
Hi @NguyenLong-02, Could you please check with the latest release and let us know if you still see the same error .

**Comment by subhadeepchakraborty** [comment]
Any solution?
