### ISSUE TITLE
face tracking ids?

### ISSUE THREAD

**Issue by mzwtjp** [google/mediapipe#1634]
When turning off STATIC_IMAGE_MODE of facemesh:

>>>
In subsequent images, once all max_num_faces faces are detected and the corresponding face landmarks are localized, it simply tracks those landmarks without invoking another detection until it loses track of any of the faces.
<<<

Assuming the pipeline keeps track of N bounding boxes at a time (until it reinvokes detection for the whole picture), anyway to obtain the unique tracking ids for each of the faces?

At least knowing how facemesh pipeline thinking which of the faces in two frames are the same (tracked) can be a great help for the app (of course such info may not be 100% accurate though.)

**Comment by sgowroji** [comment]
Hi @mzwtjp , Could you please provide more details regarding above issue. Thanks !

**Comment by mzwtjp** [comment]
Surveillance camera app, just an example.
It recognizes people in the video frame, perform further analysis (who is it? gender? emotion?) on each of the face.

But, I do not want to perform such heavy analysis on each frame.
If face detector knows a face in a frame is the same face (being tracked as same) in the next and succeeding frames, I want to know that so that I can reduce redundant analysis (only invoking it when necessary - say once in every 5 secs, when number of faces in a frame changed, etc.)

For this, I want to know with which face  (or person) in next frame I do not have to do a heavy analysis, and for this I need tracking ids (given by api for app convenience).  If I know face F in previous frame and same F appears in next frame, I can reduce codes for tracking.

**Comment by gkarpiak** [comment]
@mzwtjp face mesh solution doesn't provide such information. (Internally, it uses some basic algorithm to match faces which is based on IOU.)

So, for your use case, you could try to implement a postprocessing step (calculator/subgraph) that keeps track of previous landmarks and compares them with newly detected landmarks and identifies if there are same faces (you can use IOU calculation or maybe something more sophisticated).

**Comment by mzwtjp** [comment]
OK, thank you for your comment and explanation on how it is currently done in facemesh library.
I will try doing it on my side for now.
