### ISSUE TITLE
APP flash back while trying to create a subgraph with Android Framework 

### ISSUE THREAD

**Issue by weiyiferonia** [google/mediapipe#1635]
Respected to this awesome work. Recently,  In order to add eye blinking in face effect, I am trying to combine mediapipe face effect with iris. However, there was a problem in the combination.  

Here are the steps I tried:
**1.   Updated the face landmarks in subgraph**
- This graph is the flow chart for Face Effect：
![9](https://user-images.githubusercontent.com/41192085/108482502-85e5df80-72d4-11eb-85ab-3e2ef621e1fc.jpg)

- This graph is the module of SingleFaceSmoothLandmarkGpu：
![7](https://user-images.githubusercontent.com/41192085/108482365-5d5de580-72d4-11eb-8e59-a8c951051adc.jpg)

- I updated face landmarks with eye landmarks in the SingleFaceSmoothLandmarkGpu：
![8](https://user-images.githubusercontent.com/41192085/108482367-5d5de580-72d4-11eb-9934-fe54b16559fd.jpg)

**2.  Added the rules in BUILD files**
**- In 'mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect/BUILD':**
licenses(["notice"])
package(default_visibility = ["//visibility:private"])
cc_binary(
    name = "libmediapipe_jni.so",
    linkshared = 1,
    linkstatic = 1,
    deps = [
        "//mediapipe/graphs/face_effect:face_effect_gpu_deps",
        "//mediapipe/java/com/google/mediapipe/framework/jni:mediapipe_framework_jni",
    ],
)

cc_library(
    name = "mediapipe_jni_lib",
    srcs = [":libmediapipe_jni.so"],
    alwayslink = 1,
)
      
android_binary(
    name = "faceeffect",
    srcs = glob(["*.java"]),
    assets = [
        "//mediapipe/graphs/face_effect/data:facepaint.pngblob",
        "//mediapipe/graphs/face_effect/data:glasses.binarypb",
        "//mediapipe/graphs/face_effect/data:glasses.pngblob",
        "//mediapipe/graphs/face_effect:face_effect_gpu.binarypb",
        "//mediapipe/modules/face_detection:face_detection_front.tflite",
        "//mediapipe/modules/face_geometry/data:geometry_pipeline_metadata.binarypb",
        "//mediapipe/modules/face_landmark:face_landmark.tflite",  
        "//mediapipe/modules/iris_landmark:iris_landmark.tflite",   
    ],
    assets_dir = "",
    manifest = "//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:AndroidManifest.xml",
    manifest_values = {
        "applicationId": "com.google.mediapipe.apps.faceeffect",
        "appName": "Face Effect",
        "mainActivity": ".MainActivity",
        "cameraFacingFront": "True",
        "binaryGraphName": "face_effect_gpu.binarypb",
        "inputVideoStreamName": "input_video",
        "outputVideoStreamName": "output_video",
        "flipFramesVertically": "True",
        "converterNumBuffers": "2",
    },
    multidex = "native",
    deps = [
        ":mediapipe_jni_lib",
        "//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:basic_lib",
        "//mediapipe/framework/formats:matrix_data_java_proto_lite",
        "//mediapipe/framework/formats:landmark_java_proto_lite",
        "//mediapipe/java/com/google/mediapipe/framework:android_framework",
        "//mediapipe/modules/face_geometry/protos:face_geometry_java_proto_lite",
    ],
)

**- In 'mediapipe/graphs/face_effect/BUILD':**
load(
    "//mediapipe/framework/tool:mediapipe_graph.bzl",
    "mediapipe_binary_graph",
)

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "face_effect_gpu_deps",
    deps = [
        "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/calculators/core:gate_calculator",
        "//mediapipe/calculators/core:immediate_mux_calculator",
        "//mediapipe/calculators/image:image_properties_calculator",
        "//mediapipe/graphs/face_effect/subgraphs:single_face_smooth_landmark_gpu",
        "//mediapipe/modules/face_geometry",
        "//mediapipe/modules/face_geometry:effect_renderer_calculator",
        "//mediapipe/modules/face_geometry:env_generator_calculator",
    ],
)

mediapipe_binary_graph(
    name = "face_effect_gpu_binary_graph",
    graph = "face_effect_gpu.pbtxt",
    output_name = "face_effect_gpu.binarypb",
    deps = [":face_effect_gpu_deps"],
)

**- In 'mediapipe/graphs/face_effect/subgraphs/BUILD':**
load(
    "//mediapipe/framework/tool:mediapipe_graph.bzl",
    "mediapipe_simple_subgraph",
)
licenses(["notice"]) 
package(default_visibility = ["//visibility:public"])
mediapipe_simple_subgraph(
    name = "single_face_smooth_landmark_gpu",
    graph = "single_face_smooth_landmark_gpu.pbtxt",
    register_as = "SingleFaceSmoothLandmarkGpu",
    deps = [
        "//mediapipe/calculators/core:concatenate_vector_calculator",
        "//mediapipe/calculators/core:constant_side_packet_calculator",
        "//mediapipe/calculators/core:split_vector_calculator",
        "//mediapipe/calculators/image:image_properties_calculator",
        "//mediapipe/calculators/util:landmarks_smoothing_calculator",
        "//mediapipe/modules/face_landmark:face_landmark_front_gpu",
        "//mediapipe/modules/iris_landmark:iris_landmark_left_and_right_gpu",
        "//mediapipe/graphs/iris_tracking/calculators:update_face_landmarks_calculator",
    ],
)

**3.  Rebuilded the BUILD files with the follow commands:**

>  bazel clean --expunge
> bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect:faceeffect

Finally I got the faceeffect apk and installed into my phone, but it crashed. I can't understand what I'm doing wrong and need some help there. Thank you!

**Comment by sgowroji** [comment]
@weiyiferonia Could you please share the android exception logs.

**Comment by weiyiferonia** [comment]
> @weiyiferonia Could you please share the android exception logs.
Below you could see the android exception logs
[build_logs.txt](https://github.com/google/mediapipe/files/6013901/build_logs.txt)
:

**Comment by weiyiferonia** [comment]
> @weiyiferonia Build logs shared doesn't give any incidents of issues with the MediaPipe framework and gives successful build logs. Could you recheck your code and come back with code repo if that still exists.

Thanks for your attention. I have no idea to get the android exception logs and I am not change any code of that framework. I just update the 'SingleFaceSmoothLandmarkGpu' graph and modified the BUILD files as the above steps. Could you point out what's wrong with the steps or give some ideas to combine the iris model with the face effect model under the android framework?

**Comment by sgowroji** [comment]
@weiyiferonia  Did you try to check the graphs in any of the desktop platform. Usually i would recommend to test the combining of graphs working well with the desktop platforms. Once it worked with your combination you can test it on mobile applications. Let us know after you try.

**Comment by sgowroji** [comment]
@weiyiferonia  Did you get a chance to look at the above comment and share us the update. Thanks!

**Comment by sgowroji** [comment]
Lack of activity we are closing this issue. Please feel free to share your issue if it is still persisting.
