### ISSUE TITLE
How to ensure to accurately estimate hand keypoints whatever orientation of  hand is?

### ISSUE THREAD

**Issue by aqsc** [google/mediapipe#1636]
Why do we need to do palm detection with palm keypoints detection before we do the hand keypoints detection?
We use ssd to detection palm with the wrist keypoint , root keypoint of mid finger and some other keypoints in palm. Then we use the wrist keypoint and root keypoint of mid finger to rectify the hand pose, then we do hand keypoints detection. If we havent rectify the hand pose to make the root keypoint of mid finger above the wrist point, will it affect the hand keypoints estimation? When we design the project, how to maintain that the CNN network can accurately estimate the hand keypoints, especially whether the hand is downwards or finger to left or right?

**Comment by kuaashish** [comment]
Hello @aqsc,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
