### ISSUE TITLE
Did you compress the previous palm detection model? Model size change from 6.76MB to 3.69MB.

### ISSUE THREAD

**Issue by Wenshuo-Xiong** [google/mediapipe#1637]
Hi, I'm using your project recently,  however I found that the palm detection tflite model is not the same as before, previous output dim is (1, 2944, 18) and (1, 2944, 1), now is (1, 896, 18) and (1, 896, 1), and the model size is changed from 6.76MB to 3.69MB. Is there any other changes of the palm detection model? And where can I find a detailed comparison doc? Thanks!

**Comment by Wenshuo-Xiong** [comment]
And I also want to learn about the performance differences of these two models, including inference time and accuracy.

**Comment by mcclanahoochie** [comment]
The palm detection model was redesigned and retrained for faster performance, up to 10x faster on CPU and 2x on GPU in most cases. 
Unfortunately that is all the details I have, as this was internal work done by others.
