### ISSUE TITLE
Help understanding output format of palm_detector

### ISSUE THREAD

**Issue by esteimle** [google/mediapipe#1638]
I was trying to learn more about how the palm_detector tfilte model works (I am just a beginner in all things machine learning :).  I read the model card, and the blaze and mediapipe hands papers.  Then I took the model and put it in python where I feed it a 128x128x3 image of a hand (as float32s).  For my output I did get an array of  [0-896] elements and each element is 18 items long and at least there are floats in there and it is not zero!  I see numbers in the thousands, some negative and some very small.

My question is how does this physically relate back to my hand picture?  I thought maybe there were 18 landmarks and each element of the array aligned to a pixel somehow but those numbers don't add up.  I was interested in drawing what was detected over the image I picked. I think that would help me understand it. The papers mentioned there were 21 landmarks but my guess is there are only 18 in this implementation. But I don't understand yet how the 0-896 elements are mapped back to my 128x128 input image.

Any guidance is greatly appreciated.  Thank you!

**Comment by esteimle** [comment]
ohh assigned! :)

**Comment by eknight7** [comment]
Hi,
https://google.github.io/mediapipe/solutions/hands.html#hand-landmark-model contains a description of the hand landmarks.

**Comment by esteimle** [comment]
Hi eknight7 that's not the question I was asking :)  I fully understand how they are rendered, and that each landmark corresponds to a joint or hand feature.  

The question is about the model itself which is not defined well by the model card. What are the 0-896 elements output from ?  What are the 0-18 items for each of those elements and how does that translate back to the landmarks.  

Your model card is here: https://drive.google.com/file/d/1yiPfkhb4hSbXJZaSq9vDmhz24XVZmxpL/view

It says the palm_detector takes a 128x128x3 input image and outputs:

 • Palm detector: 
1) Predicted offset of predefined
anchors represented as a 1 x 896 x 18 tensor. 
2)Predicted detection confidence score of each anchor
represented as a 1 x 896 tensor.

please help me to understand both the 1x896x18 and the 1x896 tensor output and how it relates to the palm.  

Thank you!

**Comment by pixml27** [comment]
@esteimle Hey! Have you found the answer to your question?

**Comment by JoeyChuuichi** [comment]
Face the same issue with @esteimle,
@sgowroji @bazarevsky can you explain what does the 1x896x18 tensor means?

**Comment by bazarevsky** [comment]
Hello, palm detector model is not self contained and expects some post-processing logic, which is implemented via MediaPipe graph. 

For particular case, 1x896x18 tensor would contain relative per-anchor prediction with relative coordinates. To get familiar with anchor generation and tensor decoding, please have a look at https://github.com/google/mediapipe/blob/master/mediapipe/modules/palm_detection/palm_detection_cpu.pbtxt#L73

**Comment by denred0** [comment]
@zhongyi-zhou 
out_reg shape is [number of anchors, 18]
Second dimension 0 - 4 are bounding box offset, width and height: dx, dy, w ,h
Second dimension 4 - 18 are 7 hand keypoint x and y coordinates: x1,y1,x2,y2,...x7,y7

7 hand keypoints (knuckles, wrist base point, etc)
https://github.com/aashish2000/hand_tracking/blob/master/src/hand_tracker.py#L130
