### ISSUE TITLE
How to run multi-person pose estimation?

### ISSUE THREAD

**Issue by Sihan-Song** [google/mediapipe#1639]
When I run the python pose api, I find I can only get a single-person pose estimation, How can I get multi-person pose estimation?

**Comment by EconML** [comment]
Also wondering about multiperson, thanks.

**Comment by sgowroji** [comment]
Hi @EconML , @Sihan-Song  did you get a chance to look at this https://github.com/google/mediapipe/issues/1442#issuecomment-754821084.

**Comment by sgowroji** [comment]
Hi @Sihan-Song Have a look over on the above comments!!

**Comment by sgowroji** [comment]
Closing this ticket as there is a lack of activity on it.

**Comment by Azharuet09** [comment]
anyone have code for multi-pose estimation using mediapipe ??
