### ISSUE TITLE
How to correctly switch facingMode with camera_utils.js

### ISSUE THREAD

**Issue by Adolar13** [google/mediapipe#1646]
I'm trying to switch the camera facingMode with camera_utils.js but I can't quite figure it out from the minified code. 
I already found out how to set it with the Camera() constructor and thus tried just creating a new Camera object when switching, but this decreases performance significantly.
Is there currently a way to switch facingMode on an exisiting Camera object?

**Comment by sgowroji** [comment]
Could you please elaborate the issue with complete details.  Thanks!

**Comment by sgowroji** [comment]
@Adolar13 Lack of Activity on this issue from reporter, We are closing this issue.

**Comment by fourcolors** [comment]
is there a camera_utils api somewhere?
