### ISSUE TITLE
Build error with “com_google_protobuf”

### ISSUE THREAD

**Issue by johniao** [google/mediapipe#165]
Info：
If the definition of 'com_google_protobuf' was updated, verify that the hashes were also updated.
ERROR:
 An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "C:/users/administrator/_bazel_administrator/iexzezki/external/org_tensorflow/third_party/repo.bzl", line 104
                _apply_patch(ctx, <1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/iexzezki/external/org_tensorflow/third_party/repo.bzl", line 71, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "C:/users/administrator/_bazel_administrator/iexzezki/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(127) when executing 'D:\ProgramData\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/administrator/_bazel_administrator/iexzezki/external/com_google_protobuf" "-i" "C:/users/administrator/_bazel_administrator/iexzezki/external/org_tensorflow/third_party/protobuf/protobuf.patch"':
Stdout:
Stderr: /usr/bin/bash: patch: 鏈壘鍒板懡浠?

I can build "bazel build //src:bazel" with "com_google_protobuf" and return success, but failed 
 bazel  "bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu" 

Is the problem of my “com_google_protobuf” or my version of "bazel" or  my version of "tensorflow"
May any help? with greatly thanks!

**Comment by jiuqiant** [comment]
Similar to https://github.com/google/mediapipe/issues/137, https://github.com/google/mediapipe/issues/91, https://github.com/google/mediapipe/issues/113, and https://github.com/google/mediapipe/issues/126. Unfortunately, MediaPipe doesn't support Windows. If you are only interested in Windows, we support Windows Subsystem for Linux. You can find how to set up MediaPipe in WSL [here](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows-subsystem-for-linux-wsl).

**Comment by mgyong** [comment]
@johniao  We have released [MediaPipe on Windows](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows) with [v0.7.5](https://github.com/google/mediapipe/releases/tag/v0.7.5)
Please check it out and give us feedback
