### ISSUE TITLE
Build hello world success, but build autoflip in Ubuntu16.04 failed

### ISSUE THREAD

**Issue by tobymu** [google/mediapipe#1653]
ERROR: /home/liuxudong/chenyiyi/mediapipe/mediapipe/framework/api2/BUILD:129:11: Compiling mediapipe/framework/api2/packet.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 52 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 52 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./mediapipe/framework/api2/packet.h:16:0,
                 from mediapipe/framework/api2/packet.cc:1:
./mediapipe/framework/api2/tuple.h:19:30: error: 'tuple_size_v' is not a member of 'std'
     std::make_index_sequence<std::tuple_size_v<std::decay_t<Tuple>>>;
                              ^
./mediapipe/framework/api2/tuple.h:19:30: error: 'tuple_size_v' is not a member of 'std'
./mediapipe/framework/api2/tuple.h:19:66: error: template argument 1 is invalid
     std::make_index_sequence<std::tuple_size_v<std::decay_t<Tuple>>>;
                                                                  ^
./mediapipe/framework/api2/tuple.h: In function 'constexpr auto mediapipe::api2::internal::filtered_tuple_indices(Tuple&&)':
./mediapipe/framework/api2/tuple.h:49:44: error: 'tuple_index_sequence' was not declared in this scope
                                            tuple_index_sequence<Tuple>());
                                            ^
./mediapipe/framework/api2/tuple.h:49:70: error: expected primary-expression before '>' token
                                            tuple_index_sequence<Tuple>());
                                                                      ^
./mediapipe/framework/api2/tuple.h:49:72: error: expected primary-expression before ')' token
                                            tuple_index_sequence<Tuple>());
                                                                        ^
./mediapipe/framework/api2/tuple.h: In function 'constexpr auto mediapipe::api2::internal::filtered_tuple_indices(Tuple&&)':
./mediapipe/framework/api2/tuple.h:72:41: error: 'tuple_index_sequence' was not declared in this scope
                                         tuple_index_sequence<Tuple>());
                                         ^
./mediapipe/framework/api2/tuple.h:72:67: error: expected primary-expression before '>' token
                                         tuple_index_sequence<Tuple>());
                                                                   ^
./mediapipe/framework/api2/tuple.h:72:69: error: expected primary-expression before ')' token
                                         tuple_index_sequence<Tuple>());
                                                                     ^
./mediapipe/framework/api2/tuple.h: In function 'constexpr void mediapipe::api2::internal::tuple_for_each(F&&, Tuple&&)':
./mediapipe/framework/api2/tuple.h:128:30: error: 'tuple_index_sequence' was not declared in this scope
                              tuple_index_sequence<Tuple>());
                              ^
./mediapipe/framework/api2/tuple.h:128:56: error: expected primary-expression before '>' token
                              tuple_index_sequence<Tuple>());
                                                        ^
./mediapipe/framework/api2/tuple.h:128:58: error: expected primary-expression before ')' token
                              tuple_index_sequence<Tuple>());
                                                          ^
./mediapipe/framework/api2/tuple.h: In function 'constexpr auto mediapipe::api2::internal::map_tuple(F&&, Tuple&&)':
./mediapipe/framework/api2/tuple.h:141:25: error: 'tuple_index_sequence' was not declared in this scope
                         tuple_index_sequence<Tuple>());
                         ^
./mediapipe/framework/api2/tuple.h:141:51: error: expected primary-expression before '>' token
                         tuple_index_sequence<Tuple>());
                                                   ^
./mediapipe/framework/api2/tuple.h:141:53: error: expected primary-expression before ')' token
                         tuple_index_sequence<Tuple>());
                                                     ^
./mediapipe/framework/api2/tuple.h: In function 'constexpr auto mediapipe::api2::internal::tuple_apply(F&&, Tuple&&)':
./mediapipe/framework/api2/tuple.h:154:27: error: 'tuple_index_sequence' was not declared in this scope
                           tuple_index_sequence<Tuple>());
                           ^
./mediapipe/framework/api2/tuple.h:154:53: error: expected primary-expression before '>' token
                           tuple_index_sequence<Tuple>());
                                                     ^
./mediapipe/framework/api2/tuple.h:154:55: error: expected primary-expression before ')' token
                           tuple_index_sequence<Tuple>());
                                                       ^
./mediapipe/framework/api2/tuple.h: At global scope:
./mediapipe/framework/api2/tuple.h:160:33: error: 'tuple_size_v' is not a member of 'std'
 constexpr std::enable_if_t<i == std::tuple_size_v<std::decay_t<Tuple>>,
                                 ^
./mediapipe/framework/api2/tuple.h:160:69: error: template argument 1 is invalid
 constexpr std::enable_if_t<i == std::tuple_size_v<std::decay_t<Tuple>>,
                                                                     ^
./mediapipe/framework/api2/tuple.h:160:71: error: expected unqualified-id before ',' token
 constexpr std::enable_if_t<i == std::tuple_size_v<std::decay_t<Tuple>>,
                                                                       ^
./mediapipe/framework/api2/tuple.h:167:33: error: 'tuple_size_v' is not a member of 'std'
 constexpr std::enable_if_t<i != std::tuple_size_v<std::decay_t<Tuple>>,
                                 ^
./mediapipe/framework/api2/tuple.h:167:69: error: template argument 1 is invalid
 constexpr std::enable_if_t<i != std::tuple_size_v<std::decay_t<Tuple>>,
                                                                     ^
./mediapipe/framework/api2/tuple.h:167:71: error: expected unqualified-id before ',' token
 constexpr std::enable_if_t<i != std::tuple_size_v<std::decay_t<Tuple>>,
                                                                       ^
In file included from mediapipe/framework/api2/packet.cc:1:0:
./mediapipe/framework/api2/packet.h: In function 'void mediapipe::api2::internal::CheckCompatibleType(const HolderBase&, mediapipe::api2::internal::Wrap<mediapipe::api2::OneOf<T ...> >)':
./mediapipe/framework/api2/packet.h:122:40: error: expected primary-expression before '...' token
   bool compatible = (holder.As<T>() || ...);
                                        ^
./mediapipe/framework/api2/packet.h:122:40: error: expected ')' before '...' token
./mediapipe/framework/api2/packet.h:122:43: error: parameter packs not expanded with '...':
   bool compatible = (holder.As<T>() || ...);
                                           ^
./mediapipe/framework/api2/packet.h:122:43: note:         'T'
./mediapipe/framework/api2/packet.h: At global scope:
./mediapipe/framework/api2/packet.h:210:21: error: parameter packs not expanded with '...':
   using F::operator()...;
                     ^
./mediapipe/framework/api2/packet.h:210:21: note:         'F'
./mediapipe/framework/api2/packet.h:210:22: error: expected ';' before '...' token
   using F::operator()...;
                      ^
./mediapipe/framework/api2/packet.h:210:22: error: expected unqualified-id before '...' token
./mediapipe/framework/api2/packet.h:213:28: error: ISO C++ forbids declaration of 'Overload' with no type [-fpermissive]
 explicit Overload(F...) -> Overload<F...>;
                            ^
./mediapipe/framework/api2/packet.h:213:28: error: 'Overload' function with trailing return type not declared with 'auto' type specifier
./mediapipe/framework/api2/packet.h:227:41: error: 'is_same_v' is not a member of 'std'
   using AllowedType = std::enable_if_t<(std::is_same_v<U, T> || ...)>;
                                         ^
./mediapipe/framework/api2/packet.h:227:60: error: template argument 1 is invalid
   using AllowedType = std::enable_if_t<(std::is_same_v<U, T> || ...)>;
                                                            ^
./mediapipe/framework/api2/packet.h:229:30: error: 'AllowedType' does not name a type
   template <class U, class = AllowedType<U>>
                              ^
./mediapipe/framework/api2/packet.h:229:41: error: expected '>' before '<' token
   template <class U, class = AllowedType<U>>
                                         ^
./mediapipe/framework/api2/packet.h:231:30: error: 'AllowedType' does not name a type
   template <class U, class = AllowedType<U>>
                              ^
./mediapipe/framework/api2/packet.h:231:41: error: expected '>' before '<' token
   template <class U, class = AllowedType<U>>
                                         ^
./mediapipe/framework/api2/packet.h:237:30: error: 'AllowedType' does not name a type
   template <class U, class = AllowedType<U>>
                              ^
./mediapipe/framework/api2/packet.h:237:41: error: expected '>' before '<' token
   template <class U, class = AllowedType<U>>
                                         ^
./mediapipe/framework/api2/packet.h:239:30: error: 'AllowedType' does not name a type
   template <class U, class = AllowedType<U>>
                              ^
./mediapipe/framework/api2/packet.h:239:41: error: expected '>' before '<' token
   template <class U, class = AllowedType<U>>
                                         ^
./mediapipe/framework/api2/packet.h:253:30: error: 'AllowedType' does not name a type
   template <class U, class = AllowedType<U>>
                              ^
./mediapipe/framework/api2/packet.h:253:41: error: expected '>' before '<' token
   template <class U, class = AllowedType<U>>
                                         ^
./mediapipe/framework/api2/packet.h:261:30: error: 'AllowedType' does not name a type
   template <class U, class = AllowedType<U>>
                              ^
./mediapipe/framework/api2/packet.h:261:41: error: expected '>' before '<' token
   template <class U, class = AllowedType<U>>
                                         ^
./mediapipe/framework/api2/packet.h: In member function 'auto mediapipe::api2::Packet<mediapipe::api2::OneOf<T ...> >::Visit(const F& ...) const':
./mediapipe/framework/api2/packet.h:269:32: error: missing template arguments before '{' token
     auto f = internal::Overload{args...};
                                ^
./mediapipe/framework/api2/packet.h:271:68: error: template argument 1 is invalid
     using ResultType = absl::result_of_t<decltype(f)(const FirstT&)>;
                                                                    ^
./mediapipe/framework/api2/packet.h:273:10: error: 'is_same_v' is not a member of 'std'
         (std::is_same_v<ResultType, absl::result_of_t<decltype(f)(const T&)>> &&
          ^
./mediapipe/framework/api2/packet.h:273:25: error: 'ResultType' was not declared in this scope
         (std::is_same_v<ResultType, absl::result_of_t<decltype(f)(const T&)>> &&
                         ^
./mediapipe/framework/api2/packet.h:273:76: error: template argument 1 is invalid
         (std::is_same_v<ResultType, absl::result_of_t<decltype(f)(const T&)>> &&
                                                                            ^
./mediapipe/framework/api2/packet.h:274:10: error: expected primary-expression before '...' token
          ...),
          ^
./mediapipe/framework/api2/packet.h:274:10: error: expected ')' before '...' token
./mediapipe/framework/api2/packet.h:275:64: error: expected ',' before ';' token
         "All visitor overloads must have the same return type");
                                                                ^
./mediapipe/framework/api2/packet.h:275:64: error: expected string-literal before ';' token
./mediapipe/framework/api2/packet.h:275:64: error: expected ')' before ';' token
Target //mediapipe/examples/desktop/autoflip:run_autoflip failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 14.348s, Critical Path: 13.19s
INFO: 400 processes: 120 internal, 280 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

**Comment by rmothukuru** [comment]
@tobymu,
Can you please provide the steps you have followed and the platform where you are trying to build Autoflip? Thanks!

**Comment by tobymu** [comment]
@rmothukuru Thanks for replying.
I have followed the guide here: https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu
The platform is:
Linux version 3.10.0-1.3.2.el7.x86_64 (root@runner-2112860f-project-1457-concurrent-0stcvn) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Tue Mar 31 06:25:43 UTC 2020
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"

**Comment by tobymu** [comment]
@rmothukuru Could you please help to figure out this wired error? Thx so much!

**Comment by jiuqiant** [comment]
Your gcc version is too low to support c++17 standard. Please upgrade to a higher gcc version such as gcc 8. Then, please run `bazel clean --expunge` to get rid of the build cache and rerun the blaze build command.

**Comment by sgowroji** [comment]
Hi @tobymu, Did you get a chance to go through the above comment. Thanks!
