### ISSUE TITLE
Holistic model keypoints coordinates

### ISSUE THREAD

**Issue by shadow111** [google/mediapipe#1655]
Hello,
This actually not an issue its a question related 
am i the only one who is wondering on how to get the key points coordinates from holistic model, i tried to do the same as the hand tracking but i can't import those packages inside holistic main activity

`import com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmark;
import com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmarkList;`

any kind of help would be much appreciated

**Comment by jiuqiant** [comment]
@eknight7 implemented https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L65 and knows this better. I will hand it over to @eknight7.

**Comment by eknight7** [comment]
Hi @shadow111, can you please share your BUILD file? and your MainActivity code? thanks

**Comment by eknight7** [comment]
Hi @shadow111, can you please share the files mentioned above? Thank you.

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.
