### ISSUE TITLE
map knon ((deprecated) sRGB sRGB Full range)/(RenderIntent::COLORIMETRIC) to default color mode

### ISSUE THREAD

**Issue by wxk2008** [google/mediapipe#1657]
DisplayDevice: map unknow ((deprecated) sRGB sRGB Full range)/(RenderIntent::COLORIMETRIC) to default color mode" I have a issue like this

**Comment by rmothukuru** [comment]
@wxk2008,
Can you please provide the details mentioned below:

1. What is the MediaPipe Solution that you are trying
2. In which Platform are you trying the solution
3. Please provide the steps/code that lead you to this error

Thanks!

**Comment by rmothukuru** [comment]
@wxk2008,
Can you please respond to the above comment? Thanks!

**Comment by wxk2008** [comment]
> @wxk2008,
> Can you please respond to the above comment? Thanks!

Very sorry，thanks all the same，I know the reason！！
