### ISSUE TITLE
Hand tracking on GPU on Raspberry Pi 4b

### ISSUE THREAD

**Issue by toshiks** [google/mediapipe#1659]
Hi there! 

I suppose for GPU supporting framework uses pixel buffers from EGL. But I have problem with Raspberry Pi 4B.
When I run hand tracking example, program is closed on EGL_PBUFFER_BIT configuration.

There is small example with PixelBuffer configuration like these:
```c++
EGLint const config_attributes[] = {
	EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,
	EGL_CONFORMANT, EGL_OPENGL_ES2_BIT,
	EGL_SURFACE_TYPE, EGL_PBUFFER_BIT,
	EGL_NONE,
};
```

It can't to find any configuration. 

I try to run this script: https://github.com/pytorch/cpuinfo/blob/5916273f79a21551890fd3d56fc5375a78d1598d/tools/gpu-dump.c
And it fall on line: https://github.com/pytorch/cpuinfo/blob/5916273f79a21551890fd3d56fc5375a78d1598d/tools/gpu-dump.c#L387 (but if I delete EGL_PBUFFER_BIT — It will be Ok).

So, how can I use GPU on Raspberry Pi 4b?

My environment:
- Ubuntu Desktop 20.01 (released 2020-10-22)
- Raspberry Pi4 4B (4Gb RAM)

**Comment by TheBricktop** [comment]
Did you tried putting android on raspberry pi4? I know its not the best solution but android has gpu support so it might help.

**Comment by sgowroji** [comment]
Hi @toshiks, Could you please share the issue status. Thanks!

**Comment by sgowroji** [comment]
Hi @toshiks, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue as of now. Due to lack of activity. Thanks!
