### ISSUE TITLE
Set up iris landmark in python framework

### ISSUE THREAD

**Issue by weiyiferonia** [google/mediapipe#1661]
Hi, I'm trying to run iris tracking (mediapipe/graphs/iris_tracking/iris_tracking_cpu.pbtxt) as a python solution (copied face_mesh solution).
when instantiating IrisLandmark in Python, it throws the following error:
```
Traceback (most recent call last):
  File "F:/proj/MpExamples/iris_tracking.py", line 11, in <module>
    face_mesh = mp_face_mesh.FaceMesh(min_detection_confidence=0.5, min_tracking_confidence=0.5)
  File "F:\baidu\AP\miniconda\lib\site-packages\mediapipe\python\solutions\iris.py", line 221, in __init__
    outputs=['refined_face_landmarks'])
  File "F:\baidu\AP\miniconda\lib\site-packages\mediapipe\python\solution_base.py", line 225, in __init__
    graph_config=canonical_graph_config_proto)
RuntimeError: ValidatedGraphConfig Initialization failed.
TfLiteInferenceCalculator: ; Either model as side packet or model path in options is required.DEL")lator.cc:325) 
TfLiteInferenceCalculator: ; Either model as side packet or model path in options is required.DEL")lator.cc:325) 
```

**Comment by sgowroji** [comment]
Marking this issue to #1530  as a similar issue already exists

**Comment by weiyiferonia** [comment]
> Hi, I'm trying to run iris tracking (mediapipe/graphs/iris_tracking/iris_tracking_cpu.pbtxt) as a python solution (copied face_mesh solution).
> when instantiating IrisLandmark in Python, it throws the following error:
> 
> ```
> Traceback (most recent call last):
>   File "F:/proj/MpExamples/iris_tracking.py", line 11, in <module>
>     face_mesh = mp_face_mesh.FaceMesh(min_detection_confidence=0.5, min_tracking_confidence=0.5)
>   File "F:\baidu\AP\miniconda\lib\site-packages\mediapipe\python\solutions\iris.py", line 221, in __init__
>     outputs=['refined_face_landmarks'])
>   File "F:\baidu\AP\miniconda\lib\site-packages\mediapipe\python\solution_base.py", line 225, in __init__
>     graph_config=canonical_graph_config_proto)
> RuntimeError: ValidatedGraphConfig Initialization failed.
> TfLiteInferenceCalculator: ; Either model as side packet or model path in options is required.DEL")lator.cc:325) 
> TfLiteInferenceCalculator: ; Either model as side packet or model path in options is required.DEL")lator.cc:325) 
> ```

Solved this by ```from mediapipe.calculators.tflite import tflite_inference_calculator_pb2```

**Comment by Ronald77777** [comment]
and how can i use that library to convert
