### ISSUE TITLE
Sync failed but there's no error info at all!!

### ISSUE THREAD

**Issue by FubukiRandeZvous** [google/mediapipe#1662]
When I was trying to create a new project of mediapipe with android studio, I got sync failed but there's no error message in the console, can anyone help troubleshoot the problem?

Here's my console message:

>     Syncing project: Sync (incremental)...
>     Updating VCS...
>     Running Bazel info...
>     Command: /usr/bin/bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --
> 
>     Command: git diff --name-status --no-renames f15da632dec186f2c1d3c780f47086477e2286a9
> 
>     DEBUG: /home/shirakami/.cache/bazel/_bazel_shirakami/747afcf886d1ee55a82404ae9bab611f/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to main or choose a specific commit to pin in your workspace.
>     Computing VCS working set...
>     .aswb/.bazelproject (added)
>     .aswb/.blaze/modules/.project-data-dir.iml (added)
>     .aswb/.blaze/modules/.workspace.iml (added)
>     .aswb/.idea/.gitignore (added)
>     .aswb/.idea/.name (added)
>     .aswb/.idea/misc.xml (added)
>     .aswb/.idea/modules.xml (added)
>     .aswb/.idea/runConfigurations.xml (added)
>     .aswb/.idea/vcs.xml (added)
>     WORKSPACE (modified)
>     mediapipe/calculators/util/BUILD (modified)
>     mediapipe/calculators/util/simple_flow_calculator.cc (added)
>     mediapipe/examples/desktop/face_keypoint/BUILD (added)
>     mediapipe/graphs/face_keypoint/BUILD (added)
>     mediapipe/graphs/face_keypoint/face_keypoint_desktop_live.pbtxt (added)
> 
>     Sync targets from project view targets:
>     //mediapipe/examples/android/...:all
>     //mediapipe/java/...:all
> 
>     Building Bazel targets...
>     Command: /usr/bin/bazel build --tool_tag=ijwb:AndroidStudio --keep_going --build_event_binary_file=/tmp/intellij-bep-3fe812b4-c2a1-49de-9cee-2653639f7c07 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --noexperimental_run_validations --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/home/shirakami/.local/share/Google/AndroidStudio4.1/aswb/aspect --output_groups=intellij-info-android,intellij-info-generic,intellij-info-java,intellij-render-resolve-android,intellij-resolve-android,intellij-resolve-java -- //mediapipe/examples/android/...:all //mediapipe/java/...:all
> 
>     Loading:
>     Loading: 0 packages loaded
>     DEBUG: /home/shirakami/.cache/bazel/_bazel_shirakami/747afcf886d1ee55a82404ae9bab611f/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to main or choose a specific commit to pin in your workspace.
>     Analyzing: 76 targets (0 packages loaded, 0 targets configured)
>     INFO: Analyzed 76 targets (6 packages loaded, 4165 targets configured).
> 
>     INFO: Found 76 targets...
>     [0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
>     INFO: Elapsed time: 2.198s, Critical Path: 0.02s
>     INFO: 1 process: 1 internal.
>     INFO: Build completed successfully, 1 total action
>     INFO: Build completed successfully, 1 total action
>     INFO: Build Event Protocol files produced successfully.
>     INFO: Build completed successfully, 1 total action
>     build invocation result: success
>     Parsing build outputs...
>     Total rules: 233, new/changed: 233, removed: 0
>     Reading IDE info result...
>     Reading IDE info result...
>     Updating target map
>     Sync finished
> 
>     Timing summary:
>     BlazeInvocation: 2.3s, Prefetching: 1ms, Other: 87ms
>     Sync failed
> 

####Version information

Operating System: Ubuntu 20.04
AndroidStudio: 4.1.2
Platform: Linux 5.4.0-58-generic
Bazel plugin: 2021.01.06.0.1
Bazel: 4.0.0

I'll reply as soon as possible if needing more information, thanks!

p.s. I've posted this question on bazelbuild/intellij, too.

**Comment by yangcheng** [comment]
I have a very similar issue on Mac

Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true, dart.projects.without.pubspec=true
Non-Bundled Plugins: com.ankit.mahadik.json.dart.class, com.berzanmikaili.intellij.monokai_pro, idea.plugin.protoeditor, org.intellij.plugins.markdown, org.jetbrains.kotlin, com.samdark.intellij-visual-studio-code-dark-plus, com.thvardhan.gradianto, com.google.idea.bazel.aswb, Dart, io.flutter, silkworm


```
INFO: From Executing genrule //mediapipe/graphs/hair_segmentation:mobile_gpu_binary_graph:
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:324] Warning parsing text-format mediapipe.CalculatorGraphConfig: 116:5: text format contains deprecated field "use_gpu"
INFO: From Processing Android resources for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld:
[2,275 / 2,373] Processing Android resources for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking; 6s darwin-sandbox ... (23 actions, 17 running)
INFO: From Processing Android resources for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking:
INFO: From Processing Android resources for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu:
INFO: From Processing Android resources for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu:facemeshgpu:
INFO: From Processing Android resources for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu:posetrackinggpu:
INFO: From Processing Android resources for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackingcpu:posetrackingcpu:
INFO: From Processing Android resources for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect:faceeffect:
INFO: From Processing Android resources for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/iristrackinggpu:iristrackinggpu:
INFO: From Processing Android resources for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/upperbodyposetrackinggpu:upperbodyposetrackinggpu:
INFO: Elapsed time: 244.927s, Critical Path: 163.67s
INFO: 1760 processes: 28 internal, 1637 darwin-sandbox, 95 worker.
INFO: Build completed successfully, 1760 total actions
INFO: Build Event Protocol files produced successfully.
INFO: Build completed successfully, 1760 total actions
INFO: Build completed successfully, 1760 total actions
build invocation result: success
Parsing build outputs...
Total rules: 238, new/changed: 238, removed: 0
Reading IDE info result...
Reading IDE info result...
Updating target map
Sync finished

Timing summary:
BlazeInvocation: 245.5s, Prefetching: 0ms, Other: 30ms
Sync failed

```

**Comment by hangqiu** [comment]
Been experience exactly the same thing for both mediapipe project as well as tensorflow/lite/tools/benchmark/android:benchmark_model. Awaiting googlers

**Comment by yangcheng** [comment]
android studio 3.5 works. I hope the project can support new version of android studio and bazel

**Comment by sgowroji** [comment]
Hi @FubukiRandeZvous, Could you please try with the latest release and let us know if you still see the same. Thanks!

**Comment by FubukiRandeZvous** [comment]
OK! Thanks for your help! And sorry for not being active these time.

google-ml-butler[bot] ***@***.***> 於 2021年8月9日 週一 下午3:46寫道：

**Comment by jiuqiant** [comment]
Using MediaPipe in Android Studio with Bazel is deprecated. Please see the new gradle approach in https://github.com/google/mediapipe/blob/master/docs/getting_started/android_solutions.md.
