### ISSUE TITLE
Hand Detection Threshold Desktop

### ISSUE THREAD

**Issue by pablosilgorl** [google/mediapipe#1663]
Hello.
I've been trying to develop an app that uses multi hand detection solution in c++.
Sometimes the app detects hands where there aren't (neck,ear...) so I want to reduce False Positives.
I would like to know when is going to be available a score Threshold as It is not yet implemented. [TODO](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/detections_to_render_data_calculator.cc#L171) Also, when the hand tracking is tracking and not detecting the solution stops returning detection score. 
Maybe I'm missing something obvious so if there is a way around all these please tell me.
Thanks in advance.

**Comment by sgowroji** [comment]
Hi @pablosilgorl, Could you confirm, Are you are looking for this https://github.com/google/mediapipe/issues/1486#issuecomment-765808101

**Comment by pablosilgorl** [comment]
Hi, @sgowroji, not exactly, I just need to know the Confidence of a detected hand being a hand or set some kind of threshold to calibrate the model.

**Comment by eknight7** [comment]
@fanzhanggoogle could you please guide here as to how to reduce false positives? Thank you.
