### ISSUE TITLE
Error while executing python3 setup.py bdist_wheel: ld: library not found for -ljpeg

### ISSUE THREAD

**Issue by mayank10j** [google/mediapipe#1665]
While building python wheel packages for mediapipe python api from source
Using command:

> python3 setup.py bdist_wheel

Current Operating System: Macosx = 10.15.7 
Python version = 3.8.5
Bazel version = bazel 4.0.0-homebrew

Getting error:
_I am getting ld error: ld: library not found for -ljpeg_

Already tried 
_brew install jpeg
brew reinstall jpeg
pip install pillow_
among many other things.  Any clues will be much appreciated. 
Full stack trace for error: 

> running bdist_wheel
running build
running build_binary_graphs
generating binarypb: mediapipe/modules/face_landmark/face_landmark_front_cpu
DEBUG: /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to `main` or choose a specific commit to pin in your workspace.
DEBUG: Rule 'opencv' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "1ed6f5b02a7baf14daca04817566e7c98ec668cec381e0edf534fa49f10f58a2"
DEBUG: Repository opencv instantiated at:
  /Users/*******/Workspace/*******/mediapipe/WORKSPACE:184:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe/modules/face_landmark:face_landmark_front_cpu (1 packages loaded, 327 targets configured).
INFO: Found 1 target...
Target //mediapipe/modules/face_landmark:face_landmark_front_cpu up-to-date:
  bazel-bin/mediapipe/modules/face_landmark/libface_landmark_front_cpu.lo
  bazel-bin/mediapipe/modules/face_landmark/libface_landmark_front_cpu.so
INFO: Elapsed time: 0.663s, Critical Path: 0.05s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
generating binarypb: mediapipe/modules/hand_landmark/hand_landmark_tracking_cpu
DEBUG: /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to `main` or choose a specific commit to pin in your workspace.
DEBUG: Rule 'opencv' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "1ed6f5b02a7baf14daca04817566e7c98ec668cec381e0edf534fa49f10f58a2"
DEBUG: Repository opencv instantiated at:
  /Users/*******/Workspace/*******/mediapipe/WORKSPACE:184:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe/modules/hand_landmark:hand_landmark_tracking_cpu (4 packages loaded, 149 targets configured).
INFO: Found 1 target...
Target //mediapipe/modules/hand_landmark:hand_landmark_tracking_cpu up-to-date:
  bazel-bin/mediapipe/modules/hand_landmark/libhand_landmark_tracking_cpu.lo
  bazel-bin/mediapipe/modules/hand_landmark/libhand_landmark_tracking_cpu.so
INFO: Elapsed time: 0.347s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
generating binarypb: mediapipe/modules/holistic_landmark/holistic_landmark_cpu
DEBUG: /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to `main` or choose a specific commit to pin in your workspace.
DEBUG: Rule 'opencv' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "1ed6f5b02a7baf14daca04817566e7c98ec668cec381e0edf534fa49f10f58a2"
DEBUG: Repository opencv instantiated at:
  /Users/*******/Workspace/*******/mediapipe/WORKSPACE:184:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe/modules/holistic_landmark:holistic_landmark_cpu (5 packages loaded, 470 targets configured).
INFO: Found 1 target...
Target //mediapipe/modules/holistic_landmark:holistic_landmark_cpu up-to-date:
  bazel-bin/mediapipe/modules/holistic_landmark/libholistic_landmark_cpu.lo
  bazel-bin/mediapipe/modules/holistic_landmark/libholistic_landmark_cpu.so
INFO: Elapsed time: 0.397s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
generating binarypb: mediapipe/modules/pose_landmark/pose_landmark_cpu
DEBUG: /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to `main` or choose a specific commit to pin in your workspace.
DEBUG: Rule 'opencv' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "1ed6f5b02a7baf14daca04817566e7c98ec668cec381e0edf534fa49f10f58a2"
DEBUG: Repository opencv instantiated at:
  /Users/*******/Workspace/*******/mediapipe/WORKSPACE:184:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe/modules/pose_landmark:pose_landmark_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/modules/pose_landmark:pose_landmark_cpu up-to-date:
  bazel-bin/mediapipe/modules/pose_landmark/libpose_landmark_cpu.lo
  bazel-bin/mediapipe/modules/pose_landmark/libpose_landmark_cpu.so
INFO: Elapsed time: 0.207s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
generating binarypb: mediapipe/modules/pose_landmark/pose_landmark_cpu
DEBUG: /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to `main` or choose a specific commit to pin in your workspace.
DEBUG: Rule 'opencv' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "1ed6f5b02a7baf14daca04817566e7c98ec668cec381e0edf534fa49f10f58a2"
DEBUG: Repository opencv instantiated at:
  /Users/*******/Workspace/*******/mediapipe/WORKSPACE:184:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe/modules/pose_landmark:pose_landmark_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/modules/pose_landmark:pose_landmark_cpu up-to-date:
  bazel-bin/mediapipe/modules/pose_landmark/libpose_landmark_cpu.lo
  bazel-bin/mediapipe/modules/pose_landmark/libpose_landmark_cpu.so
INFO: Elapsed time: 0.240s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
running build_ext
bazel build --config=debug --compilation_mode=opt --define=MEDIAPIPE_DISABLE_GPU=1 --action_env=PYTHON_BIN_PATH=/Users/*******/.anaconda3/envs/testMediapipe/bin/python3 //mediapipe/python:_framework_bindings.so --define=OPENCV=source
DEBUG: /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to `main` or choose a specific commit to pin in your workspace.
DEBUG: Rule 'opencv' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "1ed6f5b02a7baf14daca04817566e7c98ec668cec381e0edf534fa49f10f58a2"
DEBUG: Repository opencv instantiated at:
  /Users/*******/Workspace/*******/mediapipe/WORKSPACE:184:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe/python:_framework_bindings.so (14 packages loaded, 886 targets configured).
INFO: Found 1 target...
ERROR: /Users/*******/Workspace/*******/mediapipe/mediapipe/python/BUILD:19:17: Linking mediapipe/python/_framework_bindings.so failed: (Exit 1): sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/sandbox/darwin-sandbox/3768/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
    PATH=/Users/*******/.anaconda3/envs/testMediapipe/bin:/Users/*******/.anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/*******/.rvm/bin:/usr/local/Cellar/jpeg/9d/lib/ \
    PYTHON_BIN_PATH=/Users/*******/.anaconda3/envs/testMediapipe/bin/python3 \
    SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk \
    TMPDIR=/var/folders/6s/zx1hvr3n1hg4bqc48tn83z54v7zm63/T/ \
    XCODE_VERSION_OVERRIDE=11.3.0.11C29 \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/sandbox/darwin-sandbox/3768/sandbox.sb /var/tmp/_bazel_*******/install/a2ea9e167f7aaf40a75d3b414510d683/process-wrapper '--timeout=0' '--kill_delay=15' external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt/bin/mediapipe/python/_framework_bindings.so-2.params) sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/sandbox/darwin-sandbox/3768/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
    PATH=/Users/*******/.anaconda3/envs/testMediapipe/bin:/Users/*******/.anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/*******/.rvm/bin:/usr/local/Cellar/jpeg/9d/lib/ \
    PYTHON_BIN_PATH=/Users/*******/.anaconda3/envs/testMediapipe/bin/python3 \
    SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk \
    TMPDIR=/var/folders/6s/zx1hvr3n1hg4bqc48tn83z54v7zm63/T/ \
    XCODE_VERSION_OVERRIDE=11.3.0.11C29 \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_*******/c432e5f90e843d563b964f3c60c2242b/sandbox/darwin-sandbox/3768/sandbox.sb /var/tmp/_bazel_*******/install/a2ea9e167f7aaf40a75d3b414510d683/process-wrapper '--timeout=0' '--kill_delay=15' external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt/bin/mediapipe/python/_framework_bindings.so-2.params)
ld: library not found for -ljpeg
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //mediapipe/python:_framework_bindings.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.647s, Critical Path: 0.19s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
error: command 'bazel' failed with exit status 1

**Comment by sgowroji** [comment]
Hi @mayank10j, Could you please share your issue status. Thanks!

**Comment by sgowroji** [comment]
Hi @mayank10j, Could you please respond to my above comment. Thanks!

**Comment by mayank10j** [comment]
@sgowroji  It was not working 2 weeks ago, will test again and get back to you.

**Comment by sgowroji** [comment]
Hi @mayank10j, Did you get a chance to test!

**Comment by sgowroji** [comment]
Assuming your issue resolved now. We are closing this ticket.

**Comment by aniketiq** [comment]
You need to link OpenCV while building from the source.

```
$ python3 setup.py gen_protos
$ python3 setup.py install --link-opencv
```

For some reason, `$ python3 setup.py bdist_wheel` doesn't link OpenCV for which the linker raises the exception:
` ld: library not found for -ljpeg`.

It should fix your issue. ✌︎

**Comment by brucechou1983** [comment]
@mayank10j @aniketiq I'm facing the same problem. How do you solve the opencv linking problem for running `bdist_wheel`?

**Comment by a-hurst** [comment]
@sgowroji I'm also getting this same issue trying to build a media pipe Python wheel (`python setup.py bdist_wheel`) from source:

```
[...]
INFO: Analyzed target //mediapipe/python:_framework_bindings.so (4 packages loaded, 95 targets configured).
INFO: Found 1 target...
ERROR: /Users/austinhurst/Documents/Programming/Misc/mediapipe_build/mediapipe/mediapipe/python/BUILD:19:17: Linking mediapipe/python/_framework_bindings.so failed: (Aborted): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin_arm64-opt/bin/mediapipe/python/_framework_bindings.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox
ld: library not found for -ljpeg
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
external/local_config_cc/cc_wrapper.sh: line 69: 28642 Abort trap: 6           "$(/usr/bin/dirname "$0")"/wrapped_clang "$@"
Target //mediapipe/python:_framework_bindings.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.693s, Critical Path: 2.48s
INFO: 21 processes: 5 internal, 16 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

Note that I'm compiling on an ARM64 Mac using the patches detailed in PR #2591, but the issue appears to be the same as @mayank10j's regardless. Out of curiosity, I went into the `third_party/BUILD` file and uncommented the `-ljpeg` flag in OpenCV's linkopts, and it fails on the next link option too with a "library not found", suggesting this isn't a libjpeg-specific problem but rather a problem with Bazel's CMake environment not being able to find system shared libraries. Any ideas on how to debug this further? I also noticed that the static OpenCV library that gets built builds its own libjpeg, libpng, libtiff, and zlib: could the issue be something about some conflict between the paths for those and the dynamic system versions of those libraries?

Is there something different about the build system for the official `mediapipe` macOS wheels on PyPi vs the build instructions in the documentation? This seems like it should affect them as well.
