### ISSUE TITLE
Batch processing for mediapipe pose

### ISSUE THREAD

**Issue by nyanmn** [google/mediapipe#1667]
Is it possible to process in batch (multiple frames) for [mediapipe pose](https://google.github.io/mediapipe/solutions/pose.html) estimation?

For other deep learning estimation, they can do in batch on GPU, so that a processor can interface to multiple cameras.

If I use mediapipe and in GPU desktop version, is it possible to process in batch?

**Comment by mcclanahoochie** [comment]
mediapipe does not currently support inference batch size >1.

one idea for multiple cameras would be to run multiple graphs in parallel

**Comment by sgowroji** [comment]
@nyanmn Did you get a chance to go through above comment!

**Comment by sgowroji** [comment]
Hi @nyanmn, Assuming you are issue addressed and closing this ticket.
