### ISSUE TITLE
Android Rendering

### ISSUE THREAD

**Issue by shadow111** [google/mediapipe#1668]
Hello Guys,
this is a question and maybe it would be a feature enhancements since it has been asked a lot .
after we get the Normalized key points for any models it would be possible to make a custom drawing with `android.graphics` 
Any idea on how to do that on the `preview`,? we can disable the `rendreing_calculators` and make a custom drawing on android parts .
Please can you guide on the needed steps 
Thank you so much

**Comment by eknight7** [comment]
Hi @shadow111, we presently don't have any support for `android.graphics`.
However, the rendering calculators draw the results on the image in C++ and then hand off the final image as a packet to the Java side. 

If you follow the [Hello World on Android tutorial for MediaPipe](https://google.github.io/mediapipe/getting_started/hello_world_android.html), there it [discusses](https://google.github.io/mediapipe/solutions/face_detection.html) how the [ExternalTextureConverter](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/ExternalTextureConverter.java) class is setup to pipe camera frames to the [FrameProcessor](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/FrameProcessor.java) which wraps the frame to a packet and sends it to the graph on C++ side.
After the graph computes the results, rendered video packets are handed back to the `FrameProcessor` [here](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/FrameProcessor.java#L193-L229). If you see the following line:
```
      videoSurfaceOutput = mediapipeGraph.addSurfaceOutput(videoOutputStream);
```
the `SurfaceOutput` object named `videoSurfaceOutput` is updated by the code defined in `Graph.java` [here](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/framework/Graph.java#L166-L174).

so you need to pipe your rendered frame to the `videoSurfaceOutput` used in the display.

**Comment by eknight7** [comment]
Hi @shadow111 , did you get a chance to try out the suggestions above? Please let us know if you have further questions, thanks!

**Comment by shadow111** [comment]
thank you for you response,
no i haven't been able to draw anything, i mean if we wanna to draw some text on the screen using android rendering not in c++ or add some button the main screen where the frame is displayed ? will that be possible?

**Comment by eknight7** [comment]
Hi ... sorry, I don't have an example of rendering on Java side.
But you can definitely get the packets containing landmarks on the Java side, and then try updating the `videoSurfaceOutput` as mentioned above: https://github.com/google/mediapipe/issues/1668#issuecomment-807851974

**Comment by shadow111** [comment]
okay thanks, i will try that and get back soon

**Comment by jpeltone** [comment]
+1

**Comment by sgowroji** [comment]
As we see the above query answered, We are closing this issue. Thanks!
