### ISSUE TITLE
Problem Web Cam Js

### ISSUE THREAD

**Issue by martincho0731** [google/mediapipe#1672]
@tyrmullen 
hello, can you help me how is it to configure in js, so that it only accesses the external webcam?  Since that stopped working for me ... it only takes the laptop, and it doesn't take the webcam.  Thanks a lot.  This is in js.  Holistic mediapipe.

**Comment by martincho0731** [comment]
@tyrmullen 
const camera = new Camera(videoElement, {
  onFrame: async () => {
    await holistic.send({image: videoElement});
  },
  width: 640,
  height: 360
});
camera.start();

**Comment by sgowroji** [comment]
@martincho0731  Could you please share the error logs or exceptions, While working with webcam.

**Comment by tyrmullen** [comment]
@martincho0731 Our pre-packaged camera utilities do not yet support external webcams.  But you should be able to use JavaScript/TypeScript to grab the camera stream of your choice and hook it to an HTMLVideoElement.  Once you've done that, requestAnimationFrame callbacks can be used to repeatedly send to holistic references to that HTMLVideoElement for processing.  This is definitely a feature we should look into adding in the future, though.

**Comment by tyrmullen** [comment]
(For reference on grabbing webcam streams: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia)
