### ISSUE TITLE
Could not find a version that satisfies the requirement mediapipe

### ISSUE THREAD

**Issue by nyanmn** [google/mediapipe#1674]
I have python version Python 3.6.9 on Xavier (Jetson with Ubuntu18.06).

When mediapipe is installed with `pip install mediapipe`, the error is 

```
Could not find a version that satisfies the requirement mediapipe (from versions: )
No matching distribution found for mediapipe
```

Why did pip installation fail?

**Comment by rmothukuru** [comment]
@nyanmn,
Can you please create a Virtual Environment and Install MediaPipe in that Environment, as shown in the [Python Documentation of MediaPipe](https://google.github.io/mediapipe/getting_started/python#ready-to-use-python-solutions)?  Thanks!

**Comment by nyanmn** [comment]
Yes I did. Please see in the [attached](https://www.dropbox.com/s/gjhzts9o6k1kgtc/Screenshot%20from%202021-03-01%2020-41-33.png?dl=0) file.

**Comment by jiuqiant** [comment]
Linux arm64 Python packages are not officially supported. You can either follow https://google.github.io/mediapipe/getting_started/python#building-mediapipe-python-package and https://github.com/jiuqiant/mediapipe_python_aarch64 to build it on your local machine or try https://github.com/jiuqiant/mediapipe_python_aarch64/blob/main/mediapipe-0.8.1-cp38-cp38-linux_aarch64.whl.

**Comment by nyanmn** [comment]
thanks. I can successfully install on intel cpu.

**Comment by sgowroji** [comment]
Hi @nyanmn, Closing this issue as you resolved from the above comments. Thanks !
