### ISSUE TITLE
SSD hand dectection

### ISSUE THREAD

**Issue by Flock1** [google/mediapipe#1677]
Hi,

I want to know if there's a way I can get the hand-detected bounding box from the hands module? I tried looking for the SSD code where it would return the bounding box coordinates but maybe I am missing something.

Do let me know.

**Comment by sgowroji** [comment]
Hi @Flock1 , Could you please elaborate the issue with complete details. Thanks!

**Comment by Flock1** [comment]
Hi,

I want to get the bounding box coordinates from the SSD model that is used by mediapipe to detect the hand finally output the hand landmarks. I read that mediapipe uses SSD object detector to detect the hand and finally output the landmarks. So is there some way I can get the hand coordinates detected by SSD?

**Comment by djthegr8** [comment]
As mediapipe detects the hand as follows, the box can easily be estimated by the 0 and 12 coordinate for vertical range and 4 and 20 for horizontal.
![image](https://user-images.githubusercontent.com/44142719/109790833-cd0a9380-7c37-11eb-87f4-82dcada61c5d.png)

**Comment by Flock1** [comment]
@djthegr8, thank you for the reply. Initially, I also thought of the same but I was wondering that since SSD is already detecting the hand, I'm sure somewhere it is giving the bounding box. So I want to bypass this extra processing and get the bb coordinates directly. Is there a way?

**Comment by djthegr8** [comment]
Ah, in that case you could close this and support #1389

**Comment by sgowroji** [comment]
@djthegr8 We will be closing this as per your update. Thank you !

**Comment by djthegr8** [comment]
Alright, but here's another request to all the maintainers to look at #1389 cuz it'll help a lot of us 👍
