### ISSUE TITLE
How we check when calculator down stream ?

### ISSUE THREAD

**Issue by duy-maimanh** [google/mediapipe#1683]
Hi. I try facemesh demo. And in FaceLandmarkFrontGpu graph. This calculator will downstream when no face detected.
```
# Collection of detected/predicted faces, each represented as a list of 468 face
# landmarks. (std::vector<NormalizedLandmarkList>)
# NOTE: there will not be an output packet in the LANDMARKS stream for this
# particular timestamp if none of faces detected. However, the MediaPipe
# framework will internally inform the downstream calculators of the absence of
# this packet so that they don't wait for it unnecessarily.
output_stream: "LANDMARKS:multi_face_landmarks"
```
So I need a call back or any solutions inform me when this calculator downstream. Because I have a view using multi_face_landmarks attributes and i need hide it when no face detected.

**Comment by gkarpiak** [comment]
@duy-maimanh I think you should be able to detect if `LANDMARKS:multi_face_landmarks` packet is present or not using [`PacketPresenceCalculator`](google3/third_party/mediapipe/calculators/core/packet_presence_calculator.cc) it will return you a packet containing `true` or `false` which you could use to hide/show your view.

**Comment by duy-maimanh** [comment]
@gkarpiak Thanks for your help. I found that func and it works fine.

**Comment by sgowroji** [comment]
@duy-maimanh Closing this issue as your resolved from the above comments. Thanks !!
