### ISSUE TITLE
Is mediapipe supported on Chrome OS,

### ISSUE THREAD

**Issue by rahulunair** [google/mediapipe#1686]
I had a question on availablilty of mediapipe, specifically if mediapipe is supported on chrome OS natively (C++). If so how to use it and add calculators from the chrome userspace ?

**Comment by sgowroji** [comment]
Hi @rahulunair, You can try installing [docker](https://dvillalobos.github.io/2020/How-to-install-and-run-Docker-on-a-Chromebook/) on your chromebook and  can install [mediapipe](https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker) on top of it
