### ISSUE TITLE
send result strings from HandGestureRecognitionCalculator to MainActivity.java in Main app

### ISSUE THREAD

**Issue by wxk2008** [google/mediapipe#1688]
My recognition is implemented in hand_gesture_recogniton_calculator.cc with class name HandGestureRecognitionCalculator.
How can I send result strings from HandGestureRecognitionCalculator to MainActivity.java in Main app

**Comment by sgowroji** [comment]
Hi @wxk2008  Can you elaborate it with complete details

**Comment by sgowroji** [comment]
Closing this issue as there is a lack of activity on it.
