### ISSUE TITLE
GPU support for MediaSequence (Preparing data sets for kinetics-i3d )

### ISSUE THREAD

**Issue by rogerbao** [google/mediapipe#169]
According to the docs ( [media_sequence.md](https://github.com/google/mediapipe/blob/master/mediapipe/docs/media_sequence.md) && [Readme in media_sequence](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/media_sequence/README.md) ), I successfully compiled the MediaSequence demo C++ binary and generated a dataset in the Kinetics format with my own videos (use [kinetics_dataset.py](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/media_sequence/kinetics_dataset.py) ). 

However, the speed of generation is too slow. It's about 30 videos per hour (100~200 frames per video).  Processing the entire datasets (~4000 videos) is very time consuming.

I notice that the code is running on Linux desktop with CPU (built with `bazel build -c opt mediapipe/examples/desktop/media_sequence:media_sequence_demo --define MEDIAPIPE_DISABLE_GPU=1`) and does not occupy any GPU. I try to replace `--define MEDIAPIPE_DISABLE_GPU=1` with `--copt -DMESA_EGL_NO_X11_HEADERS`. But it seems doesn't work.

Is there a way to process data using GPU? 
Thanks!

**Comment by mgyong** [comment]
@rogerbao For GPU to work, you need to install mesa drivers. See [step 4 of Linux installation instructions](https://mediapipe.readthedocs.io/en/latest/install.html#installing-on-debian-and-ubuntu) . If you need to use Docker containers, please see https://github.com/google/mediapipe/issues/150#issuecomment-539222209

**Comment by rogerbao** [comment]
> @rogerbao For GPU to work, you need to install mesa drivers. See [step 4 of Linux installation instructions](https://mediapipe.readthedocs.io/en/latest/install.html#installing-on-debian-and-ubuntu) . If you need to use Docker containers, please see [#150 (comment)](https://github.com/google/mediapipe/issues/150#issuecomment-539222209)

Thanks for reply！I have read the code again, it seems that the project has not yet implemented the cuda version of the optical flow calculation. 

The [file](https://github.com/google/mediapipe/blob/master/setup_opencv.sh) dose not build opencv with CUDA and use the CPU version opencv file `local/lib/libopencv_optflow.so*` (not libopencv_cudaoptflow.so) in [opencv_build_file](https://github.com/google/mediapipe/blob/master/third_party/opencv_linux.BUILD). And the [code ](https://github.com/google/mediapipe/blob/master/mediapipe/framework/port/opencv_video_inc.h)uses `include <opencv2/optflow.hpp>` instead of `include <opencv2/cudaoptflow.hpp>`.

I hope I have not made a mistake. If there is a cuda version of the code. Please let me know. Thanks a lot!

**Comment by jiuqiant** [comment]
That's correct, we don't have the CUDA optical flow implementation for now. However, it should be pretty easy to follow the way we implement [the TVL1OpticalFlowCalculator](https://github.com/google/mediapipe/blob/61bc4556af586bb3837f17187568d1345b3ee8f5/mediapipe/calculators/video/tvl1_optical_flow_calculator.cc) to make a CUDA optical flow calculator and use it in the kinetics-i3d feature extraction pipeline.

**Comment by rogerbao** [comment]
Thanks! I will try it.
