### ISSUE TITLE
Mediapipe's pose tracking tracks only one person?

### ISSUE THREAD

**Issue by nyanmn** [google/mediapipe#1691]
I tried a video clip using mediapipe's pose tracking. Is it only for one person, every frame, there is only one person detected.

How can I have multiple people detection in a frame, is it possible?
Then detection, needs to be close to camera. A bit further away person is not detected.

Compared to another model, another one better than pose track's performance.

Is there anyway to improve detection?

I can share video if needs to test.

**Comment by sgowroji** [comment]
Hi @nyanmn Can you provide more details regarding above issue.

**Comment by nyanmn** [comment]
So it detects only one person.

**Comment by sgowroji** [comment]
Yes, It is intended as of now.

**Comment by nyanmn** [comment]
Is there any suggestion how to change graph that detects multiple people?
Do I need to retrain?
Any tutorial mediapipe to change graph?

**Comment by bhavikapanara** [comment]
@sgowroji 

Did you run the TFLite model for pose key-point detection?
Actually, I want to run [pose_landmark_upper_body.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_upper_body.tflite) 

But I face difficulty to parse the output of the TFLite model. 

Can you please help me if you got key-points using this model.

Thanks,

**Comment by ivan-grishchenko** [comment]
Hi @nyanmn 

Pose landmarks model is intended to be used with an image of a single person for now.
We can't guarantee the same quality if there will be another person in the same model input image.
Hopefully, in the future, we'll extend the model's ability to work on this case. We are actively working on improving the model right now.

As for the detector, it detects all people in the frame. We pick the one with the highest confidence right now.
But you can create a graph that tracks several people. Take a look at how multi-hand tracking is implemented:
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt

As for the distance to the camera, the pose detector is trained for closeup cases (less than 4 meters).
No easy way to change that except retraining the model. But if you need that, you can try running a detection on several crops from the image (e.g., split it into a grid) and then combining results with non-maximum suppression.

**Comment by sgowroji** [comment]
Hi @nyanmn, Closing this issue as above comment  addressed your query.

**Comment by Thaina** [comment]
I think this issue should not be closed because

1. people would try to find open issue for the same problem, they will post the request or question repeatedly if this issue was closed
2. The solution is not really presented in this repo and it should. This should be marked as feature request that need to be added officially. We should have API to get multiple set of landmarks instead of making our own. In fact this library should always provide multi body result even it not really usable, and just has `num` variable set as 1 by default (and maybe explicitly state that 1 is only the stable number as of now)

**Comment by bharath5673** [comment]
![test vlcsnap-2022-07-18-16h16m27s337](https://user-images.githubusercontent.com/33729709/179499243-7e4048c5-8722-4487-ada8-aab784bc6447.png)

https://www.linkedin.com/posts/bharaths5673_yolo-mediapipe-cpu-activity-6954752592426004480-dHlP?utm_source=linkedin_share&utm_medium=member_desktop_web

**Comment by Thaina** [comment]
Are there any progress on this feature?

**Comment by Thaina** [comment]
Please reopen this issue
