### ISSUE TITLE
tensorflow/core/framework/types.proto: File not found. 

### ISSUE THREAD

**Issue by mejimaru** [google/mediapipe#1692]
Got errors when Building MediaPipe Python Package [https://google.github.io/mediapipe/getting_started/python.html](url) after this command :

`python setup.py gen_protos`

Errors:

`generating proto file: mediapipe/calculators\core\quantize_float_vector_calculator_pb2.py
generating proto file: mediapipe/calculators\core\sequence_shift_calculator_pb2.py
generating proto file: mediapipe/calculators\core\split_vector_calculator_pb2.py
generating proto file: mediapipe/calculators\image\bilateral_filter_calculator_pb2.py
generating proto file: mediapipe/calculators\image\feature_detector_calculator_pb2.py
generating proto file: mediapipe/calculators\image\image_cropping_calculator_pb2.py
generating proto file: mediapipe/calculators\image\image_transformation_calculator_pb2.py
generating proto file: mediapipe/calculators\image\mask_overlay_calculator_pb2.py
generating proto file: mediapipe/calculators\image\opencv_encoded_image_to_image_frame_calculator_pb2.py
generating proto file: mediapipe/calculators\image\opencv_image_encoder_calculator_pb2.py
generating proto file: mediapipe/calculators\image\recolor_calculator_pb2.py
generating proto file: mediapipe/calculators\image\scale_image_calculator_pb2.py
generating proto file: mediapipe/calculators\image\set_alpha_calculator_pb2.py
generating proto file: mediapipe/calculators\internal\callback_packet_calculator_pb2.py
generating proto file: mediapipe/calculators\tensor\image_to_tensor_calculator_pb2.py
generating proto file: mediapipe/calculators\tensor\inference_calculator_pb2.py
generating proto file: mediapipe/calculators\tensor\tensors_to_classification_calculator_pb2.py
generating proto file: mediapipe/calculators\tensor\tensors_to_detections_calculator_pb2.py
generating proto file: mediapipe/calculators\tensor\tensors_to_landmarks_calculator_pb2.py
generating proto file: mediapipe/calculators\tensor\tensor_converter_calculator_pb2.py
generating proto file: mediapipe/calculators\tensorflow\graph_tensors_packet_generator_pb2.py
generating proto file: mediapipe/calculators\tensorflow\image_frame_to_tensor_calculator_pb2.py
tensorflow/core/framework/types.proto: File not found.
mediapipe/calculators/tensorflow/image_frame_to_tensor_calculator.proto:20:1: Import "tensorflow/core/framework/types.proto" was not found or had errors.
mediapipe/calculators/tensorflow/image_frame_to_tensor_calculator.proto:30:12: "tensorflow.DataType" is not defined.`

Someone can help? Thank you.

**Comment by jiuqiant** [comment]
Hi, do you modify setup.py or use it as-is? I am asking because setup.py should bypass building any tensorflow protos at https://github.com/google/mediapipe/blob/master/setup.py#L187.

You can add the following code at line 193 of setup.py to see if it helps.:
```
if 'tensorflow' in proto_dir:
  continue
```

**Comment by mejimaru** [comment]
Hi Jiugiant, thank you for resolving this issue.

**Comment by jiuqiant** [comment]
Glad to help. Closing this issue now.
