### ISSUE TITLE
Static linking of graph and model files

### ISSUE THREAD

**Issue by izaharkin** [google/mediapipe#1693]
Hi,

Thank you for such a useful and cutting-edge tool! 

I managed to build the binary examples of MediaPipe and they work correctly. The point is, that when I am trying to move any of these to another place on my laptop it gives me an error that some`.pbtxt` graph or some `.tflite` model files are not found. 

Seems that they are expected to be placed near the executable at `mediapipe/modules/` folder.  I am wondering is there any way to integrate all these static files into the binary itself, maybe some kind of static linking? 

Unfortunately, I am not a Bazel guru, so please excuse me if this is a trivial question. Thank you!

**Comment by izaharkin** [comment]
Maybe at least any suggestions on what direction should I investigate, please?

**Comment by eknight7** [comment]
Since this is related to bazel build issues, reassigning to @jiuqiant for support.

**Comment by jiuqiant** [comment]
Unfortunately, MediaPipe Android reads models/files from assets dir. For example, https://github.com/google/mediapipe/blob/7c331ad58b2cca0dca468e342768900041d65adc/mediapipe/util/tflite/tflite_model_loader.cc#L22. So, it doesn't support putting model files into binary.

**Comment by izaharkin** [comment]
Thank you very much for your response. 

I understand now that MediaPipe does not support this "feature" out-of-the-box, thank you. Maybe one could do something to integrate all the asset files into binary while building, e.g. by using [xxd](https://stackoverflow.com/questions/28242813/how-to-convert-a-text-file-to-binary-file-using-linux-commands)? I had some experience in using it when it comes to several files, but there are just a lot of asset files related to graphs and it seems to be painful to do `xxd` for each of them manually.

Moreover, I found out that during the build process, Bazel creates `.binarypb`, `.inc` and `*_linked.cc` files for each graph following the rules from `mediapipe/framework/tool/mediapipe_graph.bzl`. I would be very glad to hear any thoughts on how this insight could be used (if it is related) to "truly link" the files to the binary built with Bazel. Thank you for your time 🙏

**Comment by sgowroji** [comment]
Hi @izaharkin, Thanks for your update. Initial query was answered so closing this ticket. If any new queries, please raise a new issue. Thanks.
