### ISSUE TITLE
 error: package com.google.mediapipe.formats.proto.RectProto does not exist import com.google.mediapipe.formats.proto.RectProto.NormalizedRect;

### ISSUE THREAD

**Issue by wxk2008** [google/mediapipe#1694]
when I do handtarcking, I want to obtain the detected bouding box  and scores of the palm.When I use the  com.google.mediapipe.formats.proto.RectProto.NormalizedRect to solve this problem, these has this issue?

"error: package com.google.mediapipe.formats.proto.RectProto does not exist import com.google.mediapipe.formats.proto.RectProto.NormalizedRect;"

**Comment by rmothukuru** [comment]
@wxk2008,
Can you please provide the exact steps that you have followed so that we can reproduce your error at our end? Also, please provide the platform (with version) in which you are trying to implement this solution. Thanks!

**Comment by wxk2008** [comment]
processor.addPacketCallback(
        OUTPUT_HAND_RECT,
        (packet) -> {
          Log.d("camera", "**********************************hand rect***************");
          //RectProto.NormalizedRect
          byte[] handRects = PacketGetter.getProtoBytes(packet);
          Log.d("CAMERA", "**********************" + packet.toString()+ "**********************");
          //if (!handPresence) {
            //Log.d(
                //TAG,
                //"[TS:" + packet.getTimestamp() + "] Hand presence is false, no hands detected.");
          //}
        });

**Comment by wxk2008** [comment]
android platform,I want to get the plam rectangle!!

**Comment by wxk2008** [comment]
I am very sorry to bother you, I have known the reason.The handtrack graph has no related configuration files
