### ISSUE TITLE
calculating FPS on android

### ISSUE THREAD

**Issue by milad-4274** [google/mediapipe#1696]
Hi, I want to calculate mediapipe graph FPS in android devices. I have tried to add different calculators to graph such as `ClockLatencyCalculator` or `PacketLatencyCalculator` but i got "Broken Pipe error" or some Irrelevant numbers as latency. is there any straightforward way to compute FPS for a specific graph on device?

**Comment by sgowroji** [comment]
Hi @milad-4274 , Could you provide complete details regarding the issue. 
e.g  what solution are you trying and what is the error your facing. Sharing the error logs will be beneficial.

**Comment by milad-4274** [comment]
Hi @sgowroji. I've solved my problem. I share my way and please tell me if there is simpler way.
 i got latency between two different packets by adding below node after `output_video` and similrly after `throttled_input_video`

> 
> node {
>   calculator: "ClockTimestampCalculator"
>   input_stream: "output_video"
>   output_stream: "output_video_clock"
> }
> 

then add below node to get latency:
(my problem was here in `REFERENCE_SIGNAL`. I had copied this tag from calculator  example but in `GetContract` method, it want `REFERENCE` tag )

> node {
>   calculator: "ClockLatencyCalculator"
>   input_stream: "output_video_clock"
>   input_stream: "REFERENCE:throttled_input_video_clock"
>   output_stream: "output_video_latency"
> }
.

**Comment by hadon** [comment]
Thanks milad-4274, your solution is a fine one.  To combine FPS data into the graph output streams, inserting a Calculator like ClockLatencyCalculator is a practical solution.  

There is also a profiling hook and API built in to MediaPipe.  You can see the profiling hook at mediapipe/framework/mediapipe_profiling.h, and the profiling library at mediapipe/framework/profiler.  The profiler is designed to write timing data periodically to a local file.
