### ISSUE TITLE
Is there any way to write front end in Flutter?

### ISSUE THREAD

**Issue by jinfagang** [google/mediapipe#17]
Is this able to inference in Flutter with Dart?

**Comment by mgyong** [comment]
We are looking to support running MediaPipe graphs and calculators on the web through WebAssembly towards end of the 2019. By then you will be able able to run MediaPipe graphs and calculators compiled into webassembly and have it run in flutter https://creativebracket.com/how-to-load-a-webassembly-file-in-dart-for-web/

**Comment by mgyong** [comment]
@jinfagang What use case are you looking at?

**Comment by jinfagang** [comment]
I don't quite understand what's MediaPipe graphs and calculators. Doesn't it simply tensorflow model? I thought if it can inference with flutter or not

**Comment by andredsnogueira** [comment]
Is there any news about this topic?

**Comment by bhack** [comment]
Take a look at https://github.com/zhouzaihang/flutter_hand_tracking_plugin

**Comment by saurabhchalke** [comment]
Any updates here? Are there any new Flutter projects out there that have integrated MediaPipe?

**Comment by lvilca-tekton** [comment]
Any updates?
