### ISSUE TITLE
Hair Segmentation - Training

### ISSUE THREAD

**Issue by SanthoshRajendiran** [google/mediapipe#170]
I posted this few days back in the forums. But still, there is no reply. So posting it in here too, so that I can get some suggestions.
Hey friends,

First of all, congratulations on this amazing work. I would like to train my own model similar to the hair segmentation model that you have used. The amazing things that interested me were, concept of using the previous frame's mask as an input to the model during inference again, in order to maintain the temporal information. I could not find out any information online, how to handle the temporal information in this case. I found that, you have used custom operators in this case and even with such a larger model with temporal information, the model to be less than 1MB and running fast. Could you provide any reference for the same to train own model, with temporal information?

**Comment by mgyong** [comment]
@SanthoshRajendiran Sorry for the late response. Can you look at the publication that the model is based on https://sites.google.com/corp/view/perception-cv4arvr/hair-segmentation?authuser=0 ?

**Comment by SanthoshRajendiran** [comment]
Hey @mgyong .. Thank you for the response. It was timely and helpful.. I got the required details. I will close this issue.
