### ISSUE TITLE
Help required to understand Palm detector output

### ISSUE THREAD

**Issue by aswin-datakalp** [google/mediapipe#1700]
Hi Team , 

I am using the TF-Lite palm detector as a first step to detect the hand keypoints. The model card says that palm detector gives 1) Predicted offset of predefined anchors represented as a 1 x 896 x 18 tensor. 2) Predicted detection confidence score of each anchor represented as a 1 x 896 tensor.

During inference all i get is a tensor of shape (1, 896, 18). Kindly help in how to handle this get meaningful box which can be fed into hand landmark detector for getting keypoints. Also why is that i am not getting the predicted detection confidence score tensor mentioned above.

The following is my piece of code :

### For preprocessing: 

```
def preprocess(image):
    
    image = cv2.resize(image , (128, 128))
    
    image = np.array(np.expand_dims(image, axis=0), dtype=np.float32)
    
#     print(image.shape, image.dtype)
    
    return image
```

### For inference :
```
def inference(input_data):
    
    # Set input 
    interpreter.set_tensor(input_details[0]['index'], input_data)
    
    # Invoke
    interpreter.invoke()
    
    # The function `get_tensor()` returns a copy of the tensor data.
    # Use `tensor()` in order to get a pointer to the tensor.
    output_data = interpreter.get_tensor(output_details[0]['index'])

    return output_data
```

### For model loading :

```
# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="./media-pipe-models/palm_detection.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
```
    

Any idea on how to post-process this tensor to achieve bounding box would be much helpful.

**Comment by sgowroji** [comment]
Hi @aswin-datakalp, Could you please check the latest documentation of Hands. We have been improving our models and documentation continuously. Please reach us back if you did not find answers to the above query.
