### ISSUE TITLE
How to get landmark coordinates using pose_landmark_upper_body.tflite model

### ISSUE THREAD

**Issue by bhavikapanara** [google/mediapipe#1701]
Hi Team,

I successfully run the [pose_landmark_upper_body.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_upper_body.tflite) using below code.

```
model_path = "model/pose_landmark_upper_body.tflite"
img_path = 'img/fall_img_1.png'

interpreter = tf.lite.Interpreter(model_path=model_path)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

height = input_details[0]['shape'][1]
width = input_details[0]['shape'][2]

input_details
```

```
[{'name': 'input_1',
  'index': 0,
  'shape': array([  1, 256, 256,   3], dtype=int32),
  'shape_signature': array([  1, 256, 256,   3], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]
```

`output_details`

```
[[{'name': 'ld_3d',
  'index': 587,
  'shape': array([  1, 155], dtype=int32),
  'shape_signature': array([  1, 155], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'output_poseflag',
  'index': 588,
  'shape': array([1, 1], dtype=int32),
  'shape_signature': array([1, 1], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'output_segmentation',
  'index': 582,
  'shape': array([  1, 128, 128,   1], dtype=int32),
  'shape_signature': array([  1, 128, 128,   1], dtype=int32),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]]
```

But it is very tough to interpret the model's output. The model return 3- output vectors with different shape (1, 155), (1, 1) and (1, 128, 128, 1). 

Can you please help me to parse the model output in order to get coordinates of the body key-points?

And more question regarding input pre-processing normalization. Does it like:

```
template_input = (np.float32(template_input) - 127.5) / 127.5
or
template_input = template_input/255.0

```
Can anyone please help me to resolve the above issues?

Thanks a lot,
Bhavika

**Comment by ivan-grishchenko** [comment]
Hi!

As for the model input we divide RGB image with [0, 255] values by 255.0 to get [0, 1] values. So the second formula.

As for the outputs, you are interested in first two:
* (1, 155) = (1, 31 * 5) - 33 landmarks, represented as (x, y, z, visibility, presence) each, in a flatten format. `presence` means landmark is within the frame bound, `visibility` means landmark is present and not occluded by other objects or body parts.
* (1, 1) - Pose presence flag as `x` from `sigmoid(x)`. Meaning if you apply `sigmoid` to it, you'll get value in [0, 1] range.

**Comment by ivan-grishchenko** [comment]
BTW, Why not using Python API that will do all that work for you as well as correct cropping of the input image?

**Comment by sgowroji** [comment]
Hi @bhavikapanara  , Please go through the above insights and let us know. Thanks !

**Comment by maokk** [comment]
Hi @ivan-grishchenko 
I  use the tflite file to get the pose landmark like below but the result is not good:( anything I missing? thanks

    img = cv2.imread("test-body1.jpg")
    img = img[:, :, (2, 1, 0)]
.....
    height = input_details[0]['shape'][1]
    width = input_details[0]['shape'][2]
    img_r = cv2.resize(img,(width,height))
    input_data = np.expand_dims(img_r, axis=0)
    #input_data = (np.float32(input_data) - args.input_mean) / args.input_std
    input_data = np.float32(input_data) / 255.0
.....
    output_data = interpreter.get_tensor(output_details[0]['index'])
    results = np.array(output_data[0])
    for i in range(25):
      #if (int(results[i*5+3]) > 0 and int(results[i*5+4]) > 0):
      cv2.circle(img_r, (int(results[i*5]),int(results[i*5+1])), 1, (0,0,255), 2)

**Comment by sgowroji** [comment]
Hi @maokk, Could you please raise your concern as new issue with all details. Thanks!

**Comment by sgowroji** [comment]
Hi @bhavikapanara, Assuming you are resolved, we are closing this issue now. Thanks!

**Comment by gioipv** [comment]
Thank you for your experiment. But I have a question about image pre-processing: do we need resize image with keeping the aspect ratio between the height and width of the images. ?
If we need keeping the aspect ratio, we will padding 0 into the image for achieve the size of the input model

**Comment by zztop123** [comment]
> 你好@ivan-grishchenko 我使用 tflite 文件来获取如下所示的姿势标志，但结果并不好 :( 我遗漏了什么吗？谢谢
> 
> ```
> img = cv2.imread("test-body1.jpg")
> img = img[:, :, (2, 1, 0)]
> ```
> 
> ..... 高度 = input_details[0]['shape'][1] 宽度 = input_details[0]['shape'][2] img_r = cv2.resize(img,(width,height)) input_data = np.expand_dims(img_r, axis=0) #input_data = (np.float32(input_data) - args.input_mean) / args.input_std input_data = np.float32(input_data) / 255.0 ..... 输出数据 = 解释器.get_tensor(输出数据[0]['index']) 结果 = np.array(输出数据[0]) 对于范围内的 i(25): #if (int(results[i _5+3]) > 0 和 int(results[i_ 5+4]) > 0): cv2.circle(img_r, (int(results[i _5]),int(results[i_ 5+1])),1,(0,0,255),2)

我也是直接加载pose_landmark_heavy.tflite文件，得出的结果不尽人意，你的问题解决了吗
