### ISSUE TITLE
Help with GPU with Python and Windows

### ISSUE THREAD

**Issue by simplo** [google/mediapipe#1702]
I just implented with success the hand tracking code in Python and it works very well.
Now I'd like to test it running on GPU.
I think I have to change the target reference from 
mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
to
mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu

I think I should build it in someway but cannot find any info about it.

Can you please help me?
Thanks for this incredible work!!!

**Comment by jiuqiant** [comment]
Unfortunately, MediaPipe Windows doesn't support GPU yet.

**Comment by simplo** [comment]
Thanks for your reply.
Does it works on MAC?
