### ISSUE TITLE
Mediapipe Face detection in Python

### ISSUE THREAD

**Issue by Santhanalakshmimano** [google/mediapipe#1703]
OS: Ubuntu 16.04

I created a virtual environment - python 3.7 . I installed python mediapipe with the command "pip install mediapipe". I am able to import mediapipe in python interpreter:
```
(pymediapipe) santhanalakshmi@santhanalakshmi:~/Documents/SG_pj$ python3
Python 3.7.2 (default, Feb 25 2021, 20:17:50) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mediapipe
>>>
```

But when I try to import mediapipe using .py file I get the following error: 
```
(pymediapipe) santhanalakshmi@santhanalakshmi:~/Documents/SG_pj$ python face_detection.py 
Traceback (most recent call last):
  File "face_detection.py", line 2, in <module>
    import mediapipe
ModuleNotFoundError: No module named 'mediapipe'
```
NOTE: I have mediapipe folder installed in /pymediapipe/lib/python3.7/site-packages/mediapipe/ 
What is the issue ? why am I getting the error. Please help to resolve the error.

**Comment by jiuqiant** [comment]
Do your `python` and `python3` point to the same thing? Note that you do `$ python face_detection.py` rather than `$ python3 face_detection.py`.

**Comment by Santhanalakshmimano** [comment]
Thanks for the response. Yes When I run with ```python3 face_detection.py``` it worked but when I run with ```python face_detection.py``` It failed.

**Comment by sgowroji** [comment]
@Santhanalakshmimano Closing this issue as your resolved from the above comments. Thanks !!
