### ISSUE TITLE
version_info.cc failed: (Exit 2): bash.exe failed: error executing command

### ISSUE THREAD

**Issue by NoMoreRoominHell** [google/mediapipe#1706]
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Python//Python36//python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
![QQ截图20210305113018](https://user-images.githubusercontent.com/14010726/110063510-42947200-7da6-11eb-87d9-41175df65fb8.jpg)

**Comment by NoMoreRoominHell** [comment]
BUILD:367:24: Action external/org_tensorflow/tensorflow/core/util/version_info.cc failed: (Exit 2): bash.exe failed:

**Comment by NoMoreRoominHell** [comment]
BUILD:367:24: Action external/org_tensorflow/tensorflow/core/util/version_info.cc failed: (Exit 2): bash.exe failed: error executing command

**Comment by sgowroji** [comment]
Please go through this issues seems u have similar like them. [1658](https://github.com/google/mediapipe/issues/1658)
[908](https://github.com/google/mediapipe/issues/908)

**Comment by sgowroji** [comment]
@NoMoreRoominHell  did you get a chance to go through above issues ?

**Comment by sgowroji** [comment]
Hi @NoMoreRoominHell, Closing this issue as we assume you resolved. Thanks!
