### ISSUE TITLE
Build issue windows  using msys

### ISSUE THREAD

**Issue by mayank10j** [google/mediapipe#1707]
After installing all dependencies for windows build including msys, build tools , opencv etc. 
On issuing hello world bazel build command: 

`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Anaconda3//python.exe" mediapipe/examples/desktop/hello_world`

I am getting following error: 
`Error: ERROR: C:/users/******/_bazel_******/mvh33bjd/external/com_github_gflags_gflags/BUILD:16:30: Executing genrule @com_github_gflags_gflags//:gflags_google_h failed: (Exit -1073741819): bash.exe failed: error executing command C:/msys64/usr/bin/bash.exe -c ... (remaining 1 argument(s) skipped)
      0 [main] bash (11160) C:\msys64\usr\bin\bash.exe: *** fatal error - add_item ("\??\C:\msys64", "/", ...) failed, errno 1
Stack trace:
Frame        Function    Args
000FFFF8630  00180063955 (0018028A102, 00180264FC1, 0000000003F, 000FFFF8B10)
000FFFF8B60  001800499D2 (000FFFFFFFF, 00180020010, 000FFFFABCA, 000FFFF9BB0)
000FFFF9B70  00180049A11 (000FFFF9BB0, 00000000001, 0000000003F, 00000000001)
000FFFF9C00  001800ED68D (00000000000, 00140000024, 00000000000, 000FFFFCC50)
000FFFFCC70  0018013FA45 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCCE0  0018004A055 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCDA0  00180048A2A (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFCE50  00180048AEC (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 20.169s, Critical Path: 19.76s
INFO: 215 processes: 161 internal, 54 local.
FAILED: Build did NOT complete successfully`

**Comment by sgowroji** [comment]
Hi @mayank10j , Did you get a chance to go through the below [steps](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows) . And have a look over [here](https://github.com/google/mediapipe/issues/1072#issuecomment-684183528) seems similar

**Comment by mayank10j** [comment]
Yes I have followed all [steps](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows). I took a look over [here](https://github.com/google/mediapipe/issues/1072#issuecomment-684183528) but linked issue is saying that it was fixed in this [commit](https://github.com/google/mediapipe/commit/c828392681bc343a90e188c5ad5f295bada1eefb)
I am running this on latest master, so it is not fixed.

**Comment by sureshdagooglecom** [comment]
Hi @mayank10j ,
This issue can be resolved in the latest version of MediaPipe , could you please check and close this issue.
