### ISSUE TITLE
Hard crash on Chrome 88

### ISSUE THREAD

**Issue by simon-lanf** [google/mediapipe#1708]
Here is the error:
Error:
{"name":"RuntimeError","message":"abort(undefined) at Error
 at jsStackTrace (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:68379)
 at stackTrace (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:68555)
 at abort (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:42200)
 at _abort (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:180304)
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8052]:0x3debd8
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8048]:0x3deb81
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8043]:0x3de6b4
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8040]:0x3de35f
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8055]:0x3dec31
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[508]:0xdecc
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[495]:0xcb4a
 at SolutionWasm$send [as send] (eval at new_ (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:160807), :9:1)
 at g.h (/js/chunk-vendors.5fcd654e.js:47:54530)
 at w (/js/chunk-vendors.5fcd654e.js:47:37885)
 at _.next (/js/chunk-vendors.5fcd654e.js:47:38177)
 at i (/js/chunk-vendors.5fcd654e.js:47:43321)","stack":"RuntimeError: abort(undefined) at Error
 at jsStackTrace (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:68379)
 at stackTrace (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:68555)
 at abort (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:42200)
 at _abort (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:180304)
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8052]:0x3debd8
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8048]:0x3deb81
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8043]:0x3de6b4
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8040]:0x3de35f
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8055]:0x3dec31
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[508]:0xdecc
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[495]:0xcb4a
 at SolutionWasm$send [as send] (eval at new_ (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:160807), :9:1)
 at g.h (/js/chunk-vendors.5fcd654e.js:47:54530)
 at w (/js/chunk-vendors.5fcd654e.js:47:37885)
 at _.next (/js/chunk-vendors.5fcd654e.js:47:38177)
 at i (/js/chunk-vendors.5fcd654e.js:47:43321)
 at abort (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:42231)
 at _abort (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:180304)
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8052]:0x3debd8
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8048]:0x3deb81
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8043]:0x3de6b4
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8040]:0x3de35f
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[8055]:0x3dec31
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[508]:0xdecc
 at /mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[495]:0xcb4a
 at SolutionWasm$send [as send] (eval at new_ (/mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:160807), :9:1)
 at g.h (/js/chunk-vendors.5fcd654e.js:47:54530)
 at w (/js/chunk-vendors.5fcd654e.js:47:37885)
 at _.next (/js/chunk-vendors.5fcd654e.js:47:38177)
 at i (/js/chunk-vendors.5fcd654e.js:47:43321)"}
 
And two warnings:

 Warn:
F0305 18:19:48.755000 1 solutions_wasm.embind.cc:653] Check failed: ::util::OkStatus() == (graph_->WaitUntilIdle()) (OK vs. INTERNAL: CalculatorGraph::Run() failed in Run:
Warn:
Calculator::Open() for node "facelandmarkfrontgpu__facedetectionfrontgpu__InferenceCalculator" failed: [GL_INVALID_FRAMEBUFFER_OPERATION]: The framebuffer object is not complete.: glCreateShader in third_party/tensorflow/lite/delegates/gpu/gl/gl_shader.cc:50 [type.googleapis.com/mediapipe.StatusList='
\x87\x02\x08\r\x12\x82\x02\x43\x61lculator::Open() for node \"facelandmarkfrontgpu__facedetectionfrontgpu__InferenceCalculator\" failed: [GL_INVALID_FRAMEBUFFER_OPERATION]: The framebuffer object is not complete.: glCreateShader in third_party/tensorflow/lite/delegates/gpu/gl/gl_shader.cc:50'])

**Comment by sgowroji** [comment]
Hi @simon-lanf Could you please elaborate the issue with complete details. Thanks !!

**Comment by simon-lanf** [comment]
@sgowroji it happens when mediapipe is running inside chrome mobile 88, on a factory reset phone. Everything downloaded from the play store. I get this error and I retry after a couple of seconds but I always get the same error.

**Comment by sgowroji** [comment]
Hi @simon-lanf , Did you get a chance to go through this [issue 1427](https://github.com/google/mediapipe/issues/1427)  [1459](https://github.com/google/mediapipe/issues/1459).

**Comment by simon-lanf** [comment]
> Hi @simon-lanf , Did you get a chance to go through this [issue 1427](https://github.com/google/mediapipe/issues/1427) [1459](https://github.com/google/mediapipe/issues/1459).

I didn't but I see that it seema like it is the same problem, but they say that facemesh works for them but not for me. 
Issues 1430 and 1436 are also the same problem it seems.

**Comment by tyrmullen** [comment]
Correct, these demos are not supported on mobile-web yet.  More details can be found in the comments on the other issues.

**Comment by sgowroji** [comment]
Hi @simon-lanf , Closing this issue as it is intended . Thanks !

**Comment by simon-lanf** [comment]
@sgowroji if it is intended, could it be written somewhere in the documentation ? Without global support, it is simply not ready, no website should limit themselves to desktop these days.

**Comment by tyrmullen** [comment]
@simon-lanf  I think this issue shouldn't be closed as "working-as-intended", but rather closed as a duplicate issue (of the issues mentioned above).  However, the information that the demo works on Android Chrome 89 on Android 12 on your device is new information, so that would be useful to have when consolidating to the other threads.  And if you don't mind, please also include the device details, since it is quite possible that those will make a difference for this (this particular error usually indicates a GPU-specific limit being hit).

**Comment by sgowroji** [comment]
Above i have really missed on a wrong note.  Comments shared are really valuable for others who are on same point. Reopening it and will monitor similar issues going forward to track and  address the similar scenarios going forward.

**Comment by simon-lanf** [comment]
> And if you don't mind, please also include the device details

@tyrmullen I have a Samsung S10+, Snapdragon, 8gb of RAM, original ROM, Android 11, Chrome 89.0.4389.86

**Comment by simon-lanf** [comment]
Ok I think I found the caus3, I think. It is related to 32bit vs 64bit. New phones with my specs (android10+, 8gb of ram) now have Chrome 64bit.

https://www.ghacks.net/2021/03/13/google-is-pushing-64-bit-chrome-on-android/

**Comment by sgowroji** [comment]
Good to see you resolved And thanks for sharing your inputs, which will be use full to other engineers. Present closing this ticket, but will use this for reference when any similar observations noticed. Thanks!

**Comment by simon-lanf** [comment]
Not sure why this was closed, the issue is still present, I just gave you more info about it.

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2328, https://github.com/google/mediapipe/issues/2188. 

@simon-lanf , Can you verify the above with the latest releases ?

**Comment by orenz** [comment]
I get this also
