### ISSUE TITLE
face detection model can not work wide angle or CCTV cameras, how can I adjust minimum face size for face detection

### ISSUE THREAD

**Issue by bharathCoitor** [google/mediapipe#1711]
path=" cctv names"
cap = VideoStream(src=path).start()
time.sleep(2.0)
with mp_face_detection.FaceDetection(
    min_detection_confidence=0.5) as face_detection:
    
  while(True):
##    success, image = cap.read()
    image = cap.read()
    image = imutils.resize(image, width=1000)
##      continue

    # Flip the image horizontally for a later selfie-view display, and convert
    # the BGR image to RGB.
##    image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)
    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    results = face_detection.process(image)

    # Draw the face detection annotations on the image.
    image.flags.writeable = True
##    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    if results.detections:
      for detection in results.detections:
        mp_drawing.draw_detection(image, detection)
    cv2.imshow('MediaPipe Face Detection', image)
    if cv2.waitKey(5) & 0xFF == 27:
      break
cap.release()

**Comment by sgowroji** [comment]
Hi @bharathCoitor, Can you share us in details,  what trouble are you seeing with wide angle or CCTV cameras.   Thanks !!

**Comment by sgowroji** [comment]
@bharathCoitor Could you provide details mentioned in the above comment. Thanks !

**Comment by sgowroji** [comment]
Hi @bharathCoitor, Closing this issue, assuming you are resolved. Thanks!
