### ISSUE TITLE
detect if person is laughing

### ISSUE THREAD

**Issue by manishiitg** [google/mediapipe#1713]
using the data points we get from face detect, is it possible to detect if a person is a laughing smiling ? 

does any one have code for this ?

thanks

**Comment by sgowroji** [comment]
Hi @manishiitg ,  What platform are you targeting for.

**Comment by manishiitg** [comment]
Browser so via js

**Comment by mgyong** [comment]
@manishiitg MP does not plan to support this. You can do ask in MP slack community https://mediapipe.page.link/joinslack whether someone has any recommendations
