### ISSUE TITLE
run the hand-tracking apk, it crashs 

### ISSUE THREAD

**Issue by wxk2008** [google/mediapipe#1715]
02-25 01:12:45.312  2350  2395 W System.err: java.lang.NullPointerException: Attempt to read from field 'android.os.MessageQueue android.os.Looper.mQueue' on a null object reference
02-25 01:12:45.312  2350  2395 W System.err: 	at android.os.Handler.<init>(Handler.java:234)
02-25 01:12:45.312  2350  2395 W System.err: 	at android.os.Handler.<init>(Handler.java:141)
02-25 01:12:45.312  2350  2395 W System.err: 	at com.living.pushservice.push.mqtt.WMMQTTPush.init(WMMQTTPush.java:47)
02-25 01:12:45.312  2350  2395 W System.err: 	at com.living.pushservice.handler.WMPushServiceController.init(WMPushServiceController.java:37)
02-25 01:12:45.312  2350  2395 W System.err: 	at com.living.pushservice.app.WMPushServiceApplication$1.onModuleReadyCallBack(WMPushServiceApplication.java:82)
02-25 01:12:45.312  2350  2395 W System.err: 	at com.living.secure.secloud.wmhttp.WMHttpTokenHelper.sendCallback(Unknown Source:15)
02-25 01:12:45.312  2350  2395 W System.err: 	at com.living.secure.secloud.wmhttp.WMHttpTokenHelper$2.connect(Unknown Source:39)
02-25 01:12:45.312  2350  2395 W System.err: 	at com.living.secure.seguard.SEGuardManager$1$1.run(SEGuardManager.java:74)
02-25 01:12:45.312  2350  2395 W System.err: 	at java.util.TimerThread.mainLoop(Timer.java:562)
02-25 01:12:45.312  2350  2395 W System.err: 	at java.util.TimerThread.run(Timer.java:512)

**Comment by wxk2008** [comment]
I found the error in this function
processor.addPacketCallback(
        OUTPUT_LANDMARKS_STREAM_NAME,
        (packet) -> {
          //Log.d("CAMERA", "**********************************information_5***************************");
          byte[] landmarksRaw = PacketGetter.getProtoBytes(packet);
          try {
            landmarks = NormalizedLandmarkList.parseFrom(landmarksRaw);
            if (landmarks == null) {
              Log.d(TAG, "[TS:" + packet.getTimestamp() + "] No hand landmarks.");
              return;
            }
          } catch (InvalidProtocolBufferException e) {
            Log.e(TAG, "Couldn't Exception received - " + e);
            return;
          }
        });

**Comment by sgowroji** [comment]
Hi @wxk2008 ,  I assume you are using hand tracking in android. May be you should change the above lines as below 
For reference see [here](https://github.com/google/mediapipe/blob/a92cff7a60031f5c3097b06e74416732d85b5011/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java)

```
   List<NormalizedLandmarkList> multiHandLandmarks =
                PacketGetter.getProtoVector(packet, NormalizedLandmarkList.parser());
        
```

**Comment by sgowroji** [comment]
@wxk2008  Could you confirm above solution did resolve your issue?

**Comment by sgowroji** [comment]
@wxk2008  Assuming the above solution resolved your issue, so closing this ticket. Thanks!
