### ISSUE TITLE
Heads up that mediapipe.dev has a SSL cert error

### ISSUE THREAD

**Issue by josephrocca** [google/mediapipe#1717]
![image](https://user-images.githubusercontent.com/1167575/110288569-310bce00-8023-11eb-8e21-d87478e2f1a7.png)

**Comment by Eunchan24** [comment]
me too..

**Comment by simon-lanf** [comment]
Still not working right now.

You can still use https://google.github.io/mediapipe/

**Comment by ocastan** [comment]
viz.mediapip.dev cert broken too

**Comment by sgowroji** [comment]
Resolved can you please check !!
