### ISSUE TITLE
Mediapipe doesn't work as npm package

### ISSUE THREAD

**Issue by esnho** [google/mediapipe#1719]
Hello,

I'm trying to use medipipe as dependency of my npm project.

You can find my project here: https://github.com/esnho/mediapipe-minimal-setup

@mediapipe dependencies can be installed with no issues, the problem is when I try to import Mediapipe in my source.

Visual Studio Code is complaining that the module can't be found, webpack is throwing the same error:

```
ERROR in ./Index.ts
Module not found: Error: Can't resolve '@mediapipe/camera_utils' in '/Users/lmoroni/code/mediapipe-minimal-setup/src'
 @ ./Index.ts 3:0-49 7:12-18
 @ multi ./Index.ts

ERROR in ./Index.ts
Module not found: Error: Can't resolve '@mediapipe/control_utils' in '/Users/lmoroni/code/mediapipe-minimal-setup/src'
 @ ./Index.ts 4:0-56 8:12-24
 @ multi ./Index.ts

ERROR in ./Index.ts
Module not found: Error: Can't resolve '@mediapipe/drawing_utils' in '/Users/lmoroni/code/mediapipe-minimal-setup/src'
 @ ./Index.ts 5:0-80 9:12-26 10:12-32
 @ multi ./Index.ts

ERROR in ./Index.ts
Module not found: Error: Can't resolve '@mediapipe/face_mesh' in '/Users/lmoroni/code/mediapipe-minimal-setup/src'
 @ ./Index.ts 2:0-48 6:12-20
 @ multi ./Index.ts
```

To reproduce clone above repository, and follow the README file.

Thanks.

**Comment by sgowroji** [comment]
Hi @esnho  Did you verify your import paths ? Have a look over similar [issue](https://github.com/google/mediapipe/issues/1411#issuecomment-754674105)

**Comment by esnho** [comment]
Thanks, with the right import resolved the error, I've updated above repository with the solution.
Do you plan to support "root imports"?

**Comment by sgowroji** [comment]
@esnho  We will let you know if there are any. Closing this issue as you resolved from the above comments.
