### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sufiaji** [google/mediapipe#1720]
Dear Team,

Thank you for this awesome library. However I got segmentation fault core dumped error when calling face_mesh.result. The program basically runs a facial landmarks detection from a video file by reading frame by frame. Any clue on this dump?
Thanks in advance.

![image](https://user-images.githubusercontent.com/7789546/110442114-1c940800-80ed-11eb-9599-a669990021e2.png)

**Comment by sgowroji** [comment]
Hi @sufiaji , Could you please provide complete details of the above issue for better understanding.  
Like  What did you try , Which solution & platform.

Thanks!

**Comment by sufiaji** [comment]
Hi @sgowroji 

Thanks for fast reply.
What I tried was actually to estimate the head pose based on facial landmarks provided by Mediapipe. I wrap my program in a Flask App so that it can be called as an API to detect a head pose. My code is actually reading an existing mp4 file (a video of a person moving his/her face) on a local dir using OpenCV (cv2.VideCapture(<filename>)) and estimate the facial landmark frame-by-frame using FaceMesh. Based on this facial landmark then I estimate the head pose of the person in the video. So each time I hit this API, the program will read existing mp4 file and return the estimated head pose value (roll, pitch and yaw).

So far I observe that this error raised only if I hit the API very fast from Postman (I simulate a stress test on my program; I immediately click Send button once the API return the value). But if I use dlib to get the landmark, no error raised.

Hope below snippet give an insight:

![image](https://user-images.githubusercontent.com/7789546/110481050-bbcef480-8119-11eb-844f-e5a8cfb436b1.png)

Solution: FaceMesh
Platform: Ubuntu 20.04
Python: 3.8.5

And the error captured using faulthandler.enable() related with face mesh:

![image](https://user-images.githubusercontent.com/7789546/110481269-f769be80-8119-11eb-965f-ac4822c30550.png)

Thank you!

**Comment by sufiaji** [comment]
Hi @sgowroji 
We don't have any problem running the program on Windows 10.
Thank you.

**Comment by sgowroji** [comment]
Welcome @sufiaji , Closing this issue as you resolved !!

**Comment by sufiaji** [comment]
Hi @sgowroji 

This issue is not resolved yet since we need to run the program on Ubuntu.
FYI this error doesn't happen on Windows and Mac.
So I need your advise about this error on Ubuntu.

Thanks

**Comment by sufiaji** [comment]
Hi @sgowroji ,

Just now I tried to run the routine in the loop so I don't need to hit from Postman, and at the first iteration, the program immediately return the error. 
Please advise.
Thanks
