### ISSUE TITLE
implementing wearing glasses app through face mesh

### ISSUE THREAD

**Issue by Bekzod1994** [google/mediapipe#1721]
How can i implement wearing glasses app through face mesh? i saw ur presentations, but i couldn't find any real life examples (necessary, sample codes), i couldn't find any handbooks, tutorials and etc... in terms of it, please share if u have anything related to this? For android

**Comment by mgyong** [comment]
We unfortunately don't have examples to do this and do not have plans to provide it. You can check out the [face effect renderer calculator](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/effect_renderer_calculator.cc) See fig 4 on https://google.github.io/mediapipe/solutions/face_mesh.html
