### ISSUE TITLE
why can't dectect faces at this case

### ISSUE THREAD

**Issue by hungtooc** [google/mediapipe#1723]
this is some test images i was tested but cant detect faces:
![frame_56](https://user-images.githubusercontent.com/24487114/110575629-c4631180-8191-11eb-91b8-b68b2b250aaf.jpg)
![frame_106](https://user-images.githubusercontent.com/24487114/110575634-c6c56b80-8191-11eb-9706-73c60ccd6a78.jpg)
![frame_134](https://user-images.githubusercontent.com/24487114/110575636-c7f69880-8191-11eb-8117-e07c34a3ab5a.jpg)
![frame_157](https://user-images.githubusercontent.com/24487114/110575642-c927c580-8191-11eb-8e5d-c1dbc6dd9695.jpg)
![frame_194](https://user-images.githubusercontent.com/24487114/110575643-ca58f280-8191-11eb-8c24-91c77267cdf8.jpg)
please, why?

**Comment by sgowroji** [comment]
Hi @hungtooc , Could you please share more details about the solutions and platform you are trying it. Thanks !

**Comment by hungtooc** [comment]
if i use the stock image from camera, it can't detect any faces. When i set ``` min_detection_confidence=0.3``` the result so wrong. But after croped the center of image (include faces), model work fine:
![frame_108](https://user-images.githubusercontent.com/24487114/110611301-aad9be00-81c1-11eb-9492-7827ff33e74a.jpg)
I hope a update for detect small face in big image resolution

**Comment by fanzhanggoogle** [comment]
Hi, which model are you using? If you are using the front facing model then it's worth trying the [back facing model ](https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_detection) which is bigger but intended to work for smaller and far way faces.

**Comment by hungtooc** [comment]
> Hi, which model are you using? If you are using the front facing model then it's worth trying the [back facing model ](https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_detection) which is bigger but intended to work for smaller and far way faces.

**Comment by hungtooc** [comment]
> Hi, which model are you using? If you are using the front facing model then it's worth trying the [back facing model ](https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_detection) which is bigger but intended to work for smaller and far way faces.
