### ISSUE TITLE
Capture left and right side of face

### ISSUE THREAD

**Issue by aarushi-mittal** [google/mediapipe#1724]
Hello,

I want to distinguish between the left side and right side of a face while turning ?
However, the coordinates derived from the facemesh for left and right corner of the eyes seem to be a hardcoded set.

Even when my right side of face occupies the screen, the left eye corner coordinates are captured.
How can I achieve this in preferably javascript or any other language ?

Any help would be highly appreciated.

Thank you,
Aarushi

**Comment by ivan-grishchenko** [comment]
Hi!

Could you clarify, what do you mean by "distinguish between the left side and right side"?

None of the predicted landmarks are hardcoded. They are always predicted for a given frame. And all 468 landmarks a re always predicted. In the case when part of the face is out of the frame, landmark coordinates for this part of the face will be out of image bounds.

As for Face Mesh topology, left and right sides are always the same (i.e. left and right sides are never flipped) and are defined from the perspective of object in frame.

Hope this comments will help, but if not - please clarify the task you want to solve.

**Comment by aarushi-mittal** [comment]
> Hi!
> 
> Could you clarify, what do you mean by "distinguish between the left side and right side"?
> 
> None of the predicted landmarks are hardcoded. They are always predicted for a given frame. And all 468 landmarks a re always predicted. In the case when part of the face is out of the frame, landmark coordinates for this part of the face will be out of image bounds.
> 
> As for Face Mesh topology, left and right sides are always the same (i.e. left and right sides are never flipped) and are defined from the perspective of object in frame.
> 
> Hope this comments will help, but if not - please clarify the task you want to solve.

Hello , 

I am trying to identify if a person is rotating their face and turning to their left or their right. 

So, for me there are 2 cases :
case 1 : a person has rotated their face, to face their left side
Case 2 : a person has rotated their face, to face their right side

I was trying to capture the coordinates for the right and left eye corners in such a case for a facemesh, hoping they would be different for both the cases, which is not the case.

Since the mechanism to capture Z coordinate does not exist for javascript API, I wanted to know if there is another way for this.

Thank you,
Aarushi

**Comment by sgowroji** [comment]
Hi @aarushi-mittal, We assume your query answered in the above comment. Please let us know the issue status. Thanks!

**Comment by sgowroji** [comment]
Could you please reply to my above comment. Thanks!

**Comment by hungtooc** [comment]
Hi @aarushi-mittal, this is my solution :
![Screenshot from 2021-04-20 16-53-15](https://user-images.githubusercontent.com/24487114/115377031-6ea27000-a1f9-11eb-9cb9-b2153aa13d98.png)

1. get the center point of the line created by two landmark point index **93th** and **323th** (in **face.face_landmarks**)
2. get the coordinate of noise landmark (index **4th**)
3. conpare the value of x axis **of center point of the line** in step 1 and noise point at step 2. if x value of **noise** point < **the center **  point -> face at left side elif ">": the face at right side. Note: set the theshold if you want 'center side'

**Comment by sgowroji** [comment]
Assuming your above query resolved, we are closing this issue.
