### ISSUE TITLE
Can effect_renderer_calculator be used in macOS?

### ISSUE THREAD

**Issue by 278156754** [google/mediapipe#1725]
hi all,
I have try to write a face effect demo in macOS like faceeffect in examples(mediapipe/examples/android/faceeffect. When i import effect_renderer_calculator in build file and compile the code, the result is compile error as follow
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/79309425/110598462-bd052d80-81bc-11eb-8a65-b4befbe18dab.png">
my build file is like that
cc_library(
    name = "desktop_live_calculators",
    deps = [
        "//mediapipe/calculators/core:pass_through_calculator",
        "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/calculators/core:gate_calculator",
        "//mediapipe/calculators/core:immediate_mux_calculator",
        "//mediapipe/calculators/image:image_properties_calculator",
        "//mediapipe/graphs/face_effect/subgraphs:single_face_smooth_landmark_cpu",
        "//mediapipe/modules/face_geometry",
        "//mediapipe/modules/face_geometry:effect_renderer_calculator",
        "//mediapipe/modules/face_geometry:env_generator_calculator"
    ],
)

Can effect_renderer_calculator be used in macOS(desktop)?

**Comment by jiuqiant** [comment]
Unfortunately, MediaPipe macOS doesn't provide gpu support. So, EffectRendererCalculator is not useable on macOS.
