### ISSUE TITLE
How to get hand tracking landmark actual z value in meters? 

### ISSUE THREAD

**Issue by yuchenz27** [google/mediapipe#1729]
We know that the x and y are normalized values in screen space, and the z is relative to the depth of the wrist landmark.

We have searched all the issues and didn't find a clear answer. 

Is there a way to get the actual z value of all landmarks relative to the camera in meters? Could any Google staff come and answer the question?

**Comment by sgowroji** [comment]
Hi @yuchenz27 Could you please elaborate the issue with complete details. Thanks !

**Comment by yuchenz27** [comment]
Hi @sgowroji , thanks for your help!

The mediapipe official page said "x and y are normalized to [0.0, 1.0] by the image width and height respectively. z represents the landmark depth with the depth at the wrist being the origin, and the smaller the value the closer the landmark is to the camera. The magnitude of z uses roughly the same scale as x."

From my understanding, it means that the depth of the wrist landmark should always be zero, and all landmarks whose depth values are smaller than the wrist (closer to the camera) will have negative z values and all landmarks whose depth values are greater than the wrist will have positive z values.

I think it means that we cannot get the wrist landmark depth value in meters to the camera, but we can get the relative depth of other landmarks to the wrist landmark. But the magnitude of the z values I got seems quite random to me, could you please explain the meaning of z values? And my ultimate goal is to get the actual depth values of all landmarks to the camera in meters, is there a way to do that?

In addition, I found some other problems:
1. From the official page, the x and y are normalized values and should be within [0 ,1] (x from left to right and y from top to bottom), but I got some negative x and y values, why did that happen?
2. Since the depth of the wrist landmark is the origin, the z value of it should always be 0, but in actual cases it fluctuated around 0 and never be 0, why?
Here are some wrist landmark coordinates I got
[0.346257, 0.649367 ,-0.000035]
[0.347485, 0.666504 ,-0.000029]
[0.346385, 0.678231 ,-0.000018]
[0.345328, 0.688071 ,0.000015]
[0.345179, 0.701831 ,-0.000005]
[0.341557, 0.718021 ,0.000023]
[0.338739, 0.728299 ,0.000004]
[0.336479, 0.739383 ,0.000016]

I am running mediapipe on iOS.

**Comment by sgowroji** [comment]
Hi @yuchenz27 , Please refer [1392](https://github.com/google/mediapipe/issues/1392), [1417](https://github.com/google/mediapipe/issues/1417) to understand the implementation of Z values.  And i would recomend you to try the above use case on desktop platform first, then you can try it on IOS.

**Comment by sgowroji** [comment]
Hi @yuchenz27  Did you get a chance to go through the above comment. Thanks!

**Comment by sgowroji** [comment]
Assuming you are resolved from the above comments. Hence closing this issue. Please feel free to open if the issue still persists. Thanks!
