### ISSUE TITLE
Model in "face_detection_front.tflite" is inconsistent with the model in the paper "BlazeFace"

### ISSUE THREAD

**Issue by liqiang311** [google/mediapipe#173]
Hi

I studied this paper `BlazeFace: Sub-millisecond Neural Face Detection on Mobile GPUs`, which led me to download `face_detection_front.tflite`.

But their model is completely different. I read tflite using tensorflow's `tf.lite.Interpreter`, but I didn't find the `double BlazeBlock` in the paper.

In addition, the paper mentions the use of 5x5 DepthWise to replace 3x3 Depthwise, but the tflite model uses 3x3 Depthwise.

Why is this?

Thank you.

**Comment by mgyong** [comment]
@liqiang311 See answer from bazarevsky in #21
