### ISSUE TITLE
couldn`t build mediapipe on windows : windows.h: No such file or directory 

### ISSUE THREAD

**Issue by vamsee-asu2019** [google/mediapipe#1730]
I am trying to build the mediapipe(c++ examples) in my Windows 10 PC .
I followed the steps given in the installation page.
I get the following error : `fatal error C1083: Cannot open include file: 'windows.h': No such file or directory`
Could anyone help me with this??

Command used :
` C:\Users\vamse\OneDrive\Desktop\EmbodyVR\mediapipe_latest>"C:/Program Files/Bazel/bazel.exe"  build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//vamse//Anaconda3//envs//FirstAid-master//python.exe" mediapipe/examples/desktop/face_mesh:face_mesh_cpu`

Command prompt output :
```
Starting local Bazel server and connecting to it...
INFO: Analyzed target //mediapipe/examples/desktop/face_mesh:face_mesh_cpu (118 packages loaded, 6067 targets configured).
INFO: Found 1 target...
ERROR: C:/users/vamse/_bazel_vamse/y53vhkjs/external/com_google_absl/absl/base/BUILD.bazel:200:11: Compiling absl/base/internal/sysinfo.cc [for host] failed: (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29910/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 40 argument(s) skipped)
external/com_google_absl/absl/base/internal/sysinfo.cc(20): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
Target //mediapipe/examples/desktop/face_mesh:face_mesh_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11.211s, Critical Path: 2.66s
INFO: 159 processes: 139 internal, 20 local.
FAILED: Build did NOT complete successfully 
```

**Comment by jiuqiant** [comment]
'windows.h' is from WinSDK. If you installed it, please check if you set `BAZEL_WINSDK_FULL_VERSION` to the WinSDK version you use. You also cake a look at https://docs.bazel.build/versions/master/windows.html#build-c-with-msvc for more details.

**Comment by vamsee-asu2019** [comment]
@jiuqiant I have mentioned correctly even then it was throwing the same error. Then I just checked the version of winsdk  , it was 10.0.18362.1. After which I tried with the newer version of the winsdk (10.0.19041.0). But in vain. To my surprise, the other day i tried with the newer version and it is working with the latest version of winsdk. But the older version(10.0.18362.1) still gives the same error.

**Comment by jiuqiant** [comment]
It seems more like a Bazel windows issue that mediapipe can help with. As Bazel documentation mentions, the latest Windows SDK installed will be used by default if you don't set BAZEL_WINSDK_FULL_VERSION. Maybe you can just remove this env variable. Moreover, do `bazel clean --expunge` to get rid of all caches before rebuilding.

As you mentioned, you tried with the newer version and it is working with the latest version of winsdk. Not sure if that means you successfully built mediapipe face mesh already? Also, that seems to match what Bazel documentation suggests.

**Comment by vamsee-asu2019** [comment]
@jiuqiant , Yes I am able to build media pipe successfully now.

**Comment by vamsee-asu2019** [comment]
@jiuqiant  Now I am facing another issue. I am trying to access the landmarks from the face mesh and followed #200 . I get the following error when I try to build it : 
`Compiling mediapipe/framework/formats/landmark.pb.cc [for host] failed: undeclared inclusion(s) in rule '//mediapipe/framework/formats:landmark_cc_proto':
this rule is missing dependency declarations for the following files included by 'mediapipe/framework/formats/landmark.pb.cc':
  'mediapipe/framework/formats/landmark.pb.h'`

I have created an issue for the same #1739 . 

Could you help me with this ?

**Comment by jiuqiant** [comment]
The issue reported here seems to be solved. Continue the discussion in https://github.com/google/mediapipe/issues/1739.

**Comment by Dingjie-A** [comment]
@jiuqiant Hi jiuqiant,

I am facing the same problem and don't know why it appears:
```
bazel build -c opt -j 2 --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//0904d//anaconda3//python" mediapipe/examples/desktop/hello_world:hello_world
```
and it reports:
```
ERROR: C:/users/0904d/_bazel_0904d/aphopi5v/external/com_google_protobuf/BUILD:420:11: Compiling src/google/protobuf/compiler/subprocess.cc [for tool] failed: (Exit 2): cl.exe failed: error executing command (from target @com_google_protobuf//:protoc_lib) C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 43 arguments skipped)
注意: 包含文件:  external/com_google_protobuf/src\google/protobuf/compiler/subprocess.h
external/com_google_protobuf/src\google/protobuf/compiler/subprocess.h(40): fatal error C1083: 无法打开包括文件: “windows.h”: No such file or directory  
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.                                                                                   
INFO: Elapsed time: 229.057s, Critical Path: 2.41s
INFO: 8 processes: 7 internal, 1 local.                                                                                                                  
FAILED: Build did NOT complete successfully
```

It can not find windows.h. I have tried to reset and remove the BAZEL_WINSDK_FULL_VERSION env variable and they do not works. Could you help me?

P.S. few days before it worked perfectly.

Thank you very much!

**Comment by yujie08144815** [comment]
i same problem new. how to do this?

**Comment by yujie08144815** [comment]
> @jiuqiant Hi jiuqiant,
> 
> I am facing the same problem and don't know why it appears:
> 
> ```
> bazel build -c opt -j 2 --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//0904d//anaconda3//python" mediapipe/examples/desktop/hello_world:hello_world
> ```
> 
> and it reports:
> 
> ```
> ERROR: C:/users/0904d/_bazel_0904d/aphopi5v/external/com_google_protobuf/BUILD:420:11: Compiling src/google/protobuf/compiler/subprocess.cc [for tool] failed: (Exit 2): cl.exe failed: error executing command (from target @com_google_protobuf//:protoc_lib) C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 43 arguments skipped)
> 注意: 包含文件:  external/com_google_protobuf/src\google/protobuf/compiler/subprocess.h
> external/com_google_protobuf/src\google/protobuf/compiler/subprocess.h(40): fatal error C1083: 无法打开包括文件: “windows.h”: No such file or directory  
> Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
> Use --verbose_failures to see the command lines of failed build steps.                                                                                   
> INFO: Elapsed time: 229.057s, Critical Path: 2.41s
> INFO: 8 processes: 7 internal, 1 local.                                                                                                                  
> FAILED: Build did NOT complete successfully
> ```
> 
> It can not find windows.h. I have tried to reset and remove the BAZEL_WINSDK_FULL_VERSION env variable and they do not works. Could you help me?
> 
> P.S. few days before it worked perfectly.
> 
> Thank you very much!

i same problem new. how to do this?
