### ISSUE TITLE
Mediapipe aar: error executing command external/remotejdk11_linux/bin/java on wsl

### ISSUE THREAD

**Issue by arsaz101** [google/mediapipe#1732]
im experiencing the following error when trying to build an aar file:

INFO: From Building external/com_google_protobuf/libprotobuf_javalite.jar (86 source files):
warning: -parameters is not supported for target value 1.7. Use 1.8 or later.
ERROR: /home/arsaz/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: Compiling Java headers mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/libmp_face_detection_aar_android_lib-hjar.jar (49 source files) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -Xverify:none -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 107 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox java failed: error executing command external/remotejdk11_linux/bin/java -Xverify:none -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 107 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/java/com/google/mediapipe/framework/PacketGetter.java:20: error: symbol not found com.google.protobuf.InvalidProtocolBufferException
import com.google.protobuf.InvalidProtocolBufferException;
       ^
mediapipe/java/com/google/mediapipe/framework/PacketGetter.java:123: error: could not resolve InvalidProtocolBufferException
      throws InvalidProtocolBufferException {
             ^
mediapipe/java/com/google/mediapipe/framework/PacketGetter.java:22: error: symbol not found com.google.protobuf.Parser
import com.google.protobuf.Parser;
       ^
mediapipe/java/com/google/mediapipe/framework/PacketGetter.java:149: error: could not resolve Parser
  public static <T> List<T> getProtoVector(final Packet packet, Parser<T> messageParser) {
                                                                ^
mediapipe/java/com/google/mediapipe/framework/ProtoUtil.java:17: error: symbol not found com.google.protobuf.ExtensionRegistryLite
import com.google.protobuf.ExtensionRegistryLite;
       ^
mediapipe/java/com/google/mediapipe/framework/ProtoUtil.java:36: error: could not resolve ExtensionRegistryLite
  public static ExtensionRegistryLite getExtensionRegistry() {
                ^
mediapipe/java/com/google/mediapipe/framework/ProtoUtil.java:19: error: symbol not found com.google.protobuf.InvalidProtocolBufferException
import com.google.protobuf.InvalidProtocolBufferException;

**Comment by sociallonewolf** [comment]
Hi, I'm have the exact same problem when trying to run the following command:

`bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a --strip=ALWAYS //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_hand_tracking_aar`

My setup is on Ubuntu 20.04 in WSL2 (Windows 10 OS Build 19042.867), Bazel 3.4.1, latest Mediapipe library, and jdk 11.0.10. I could successfully run the 'mediapipe/examples/desktop/hello_world:hello_world'. Now I'm trying to build the Hand Tracking AAR to be used in @jiuqiant example Android app at https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example

**Comment by arsaz101** [comment]
I'm using the exact same specs and am facing the same problem.

**Comment by jiuqiant** [comment]
See the solution at https://github.com/google/mediapipe/issues/1679#issuecomment-788323387.

**Comment by arsaz101** [comment]
Works perfectly now, Thank You!

**Comment by sgowroji** [comment]
@arsaz101 closing this issue as we see you resolved. Thanks !

**Comment by rahulsuxsena1** [comment]
can anyone plz help me , as mentioned in comment #1679 , where to paste that fix in which file and what if i am not using docker . plz help me
