### ISSUE TITLE
Holistic web demo not working

### ISSUE THREAD

**Issue by tetosuna** [google/mediapipe#1735]
Hi.
I access to Holistic Web demo(https://mediapipe.dev/demo/holistic) , and I get error dialog that "Failed to create webgl canvas context when passing video frame".
My video is visible top left on the page. But conflict to Control panel,  and still on the loading screen. 

Here is console error log 

~~~
Uncaught (in promise) TypeError: Cannot read property 'createTexture' of undefined
    at __glGenObject (cdn.jsdelivr.net/npm/@mediapipe/holistic@0.1/holistic_solution_wasm_bin.js:9)
    at _glGenTextures (cdn.jsdelivr.net/npm/@mediapipe/holistic@0.1/holistic_solution_wasm_bin.js:9)
    at cdn.jsdelivr.net/npm/@mediapipe/holistic@0.1/holistic_solution_wasm_bin.wasm:wasm-function[462]:0xc55f
    at cdn.jsdelivr.net/npm/@mediapipe/holistic@0.1/holistic_solution_wasm_bin.wasm:wasm-function[461]:0xc547
    at Object.createTexture (eval at new_ (cdn.jsdelivr.net/npm/@mediapipe/holistic@0.1/holistic_solution_wasm_bin.js:9), <anonymous>:7:10)
    at ja.h (holistic.js:34)
    at Q (holistic.js:10)
    at ma.next (holistic.js:11)
    at k (holistic.js:22)
~~~

- Environment:
  - OS: Windows 8.1 Enterprise
  - Browser: Google Chrome 88.0.4324.150(64bit)

thank you.

**Comment by sgowroji** [comment]
Hi @tetosuna, Refer this [1727](https://github.com/google/mediapipe/issues/1727#issuecomment-799844456) may resolve this issue.

**Comment by tyrmullen** [comment]
If you're simply browsing to the web demo and encountering this issue, then it sounds like a problem with your Chrome setup.  Specifically, it sounds like you're having a problem creating a WebGL2 context, which is necessary for all MediaPipe web rendering.  Google Chrome has had support for this on Windows Desktop machines for a while (https://caniuse.com/webgl2), so this makes me think something else is preventing you from accessing those resources.

Can you verify this by navigating to a simple test site which uses WebGL2 (like https://get.webgl.org/webgl2/) and seeing if this works for you or not?  (The particular one I linked to should show a spinning cube if successful).

If the test does not work for you, then that confirms that you have an issue with WebGL2, so then the next step would be to check if one of your chrome://flags settings has been changed to a nonstandard configuration-- especially any flags which relate to hardware(GPU) rendering support or WebGL.  And if nothing there looks suspicious, then it would be good to know what type of machine this is, to check if there's a known issue with the specific GPU of your computer.

**Comment by tetosuna** [comment]
Thanks for your advice.
I check my chrome setting, and find webGL is not working.
I try other computer, and web demo is work fine.
It is not mediapipe issue, sorry.
thank you.

**Comment by sgowroji** [comment]
Glad you are resolved. 
Closing this issue. Thanks!
