### ISSUE TITLE
accessing the pose landmarks in pose tracking

### ISSUE THREAD

**Issue by ShravanRai22** [google/mediapipe#1736]
I'm currently working on the pose tracker on Windows with C++. In the demo_run_graph_main.cc,
 `   mediapipe::Packet packet;
    if (!poller.Next(&packet)) break;
    auto& output_frame = packet.Get<mediapipe::ImageFrame>();` 
lines 119 - 121, outputs only the image packet and not the pose landmarks. The pose_tracking_cpu graph has two output streams namely: output_video and pose_landmarks. 

Could you share the functions and ways to access the pose_landmarks stream output.

**Comment by sgowroji** [comment]
@ShravanRai22 Could you please elaborate the issue with complete details. Thanks !

**Comment by ShravanRai22** [comment]
The outputs from pose_tracking_cpu.pbtxt graph is both output_video and pose_landmarks. But in the mediapipe/examples/desktop/demo_run_graph_main.cc which is used to build the pose_tracking_cpu solution, the code given is 
` mediapipe::Packet packet;
    if (!poller.Next(&packet)) break;
    auto& output_frame = packet.Get<mediapipe::ImageFrame>();
`
here only the ImageFrame is the output that is exposed to use by main. I want the pose_landmarks point array exposed as well to be accessed by main. 

Could you share how to expose the pose_landmark points vector to main and used by other function.

**Comment by mcclanahoochie** [comment]
To get another stream output, you need to define a poller for that stream.

Add another poller [here](https://github.com/google/mediapipe/blob/7c331ad58b2cca0dca468e342768900041d65adc/mediapipe/examples/desktop/demo_run_graph_main.cc#L80),  with something like this
```
ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller ladmarks_poller,
                   graph.AddOutputStreamPoller("pose_landmarks"));
```
then receive the packet in the same way:
```
landmarks_poller.Next(&landmarks_packet)
```

**Comment by RaiShra1** [comment]
The follow up question on this is the data structure to use. I wanted to know if Normalizedlandmark is the one to use in order to the landmarks packet data and if so, should I be using its proto file?

**Comment by ShravanRai22** [comment]
The follow up question on this is the data structure to use. I wanted to know if "Landmark" or "Normalized Landmark" is the data structure to collect the data received in the landmarks_packet. In that case could you kindly provide a landmark.h file and landmark.cc file for in mediapipe/framework/formats ?

**Comment by mcclanahoochie** [comment]
please have a look at this calculator to know how to use the landmark.proto [(landmark.pb.h)](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/landmarks_to_render_data_calculator.cc#L22)

**Comment by sgowroji** [comment]
Hi @ShravanRai22, Did you get a chance to go through the above comment. Thanks!

**Comment by RaiShra1** [comment]
Hi @sgowroji, I was able to get the landmarks values in my application. Currently, I'm getting the Normalized landmarks and working on converting it into actual pixel values. Thanks for the information and clearing my questions @mcclanahoochie

**Comment by sgowroji** [comment]
Thanks for sharing the update. We are glad to know you resolved.

**Comment by vinaypurushothamnaidu** [comment]
> Hi @sgowroji, I was able to get the landmarks values in my application. Currently, I'm getting the Normalized landmarks and working on converting it into actual pixel values. Thanks for the information and clearing my questions @mcclanahoochie

Can you please provide the steps/code you followed?

**Comment by Luan-Don-0609** [comment]
> Hi @sgowroji, I was able to get the landmarks values in my application. Currently, I'm getting the Normalized landmarks and working on converting it into actual pixel values. Thanks for the information and clearing my questions @mcclanahoochie

Can you explain how can you do it? I have the same problem when getting the pose_landmarks. 
After setting the poller for landmarks. I try to take the landmarks and print them out.
// Process pose landmarks.
    const auto& pose_landmarks = landmarks_packet.Get<mediapipe::NormalizedLandmarkList>();
    for (const auto& landmark : pose_landmarks.landmark()) {
      ABSL_LOG(INFO) << "Landmark: (" << landmark.x() << ", " << landmark.y() << ", " << landmark.z() << ")";
    }
ERR: no NormalizedLandmarkList
ERR: no "mediapipe/framework/formats/landmark.pb.h" can be found after I included it.
