### ISSUE TITLE
Crashes !

### ISSUE THREAD

**Issue by baocareos** [google/mediapipe#174]
Hello,
I download the code source and successfully compile to have all apk. Some of them work, some have crash !
Here is the report

Tested device: Tablet Huawei MediaPad M5
Android version: 9
CPU hisilicon Kirin 960s

edgedetectiongpu : OK
facedetectioncpu: OK
objectdetectioncpu: OK
objectdetectiongpu: OK
hairsegmentationgpu: OK

handdetectiongpu: Crash
handtrackinggpu: Crash
facedetectiongpu: Crash

So it is not a problem of GPU / CPU because some apk running with GPU are still ok.

The logs are below

[2019_10_handdetectiongpu.txt](https://github.com/google/mediapipe/files/3729713/2019_10_handdetectiongpu.txt)

[2019_10_handtrackinggpu.txt](https://github.com/google/mediapipe/files/3729714/2019_10_handtrackinggpu.txt)

[2019_10_facedetectiongpu.txt](https://github.com/google/mediapipe/files/3729715/2019_10_facedetectiongpu.txt)

Best regards,

Bao

**Comment by kulievvitaly** [comment]
I tested the compiled applications on android. 
handtrackingcpu - crashed
handtrackinggpu - crashed
On a few frames, a picture from the camera appears and the application crashes. Tested with Huawei mate 20 and huawei mate 20 pro.

**Comment by offbye** [comment]
few times I can run handtrackinggpu  on  huawei mate 20 pro.   
I  think these are some compatible problems.

**Comment by HebaMohamed** [comment]
yes it crashed on these devices too, it seems to be an issue with android 9 ?
- Samsung S8+
- Samsung A20

**Comment by mcclanahoochie** [comment]
Hi,
Thanks for the detailed notes @baocareos .
Based on the logcat, this seems to be related to https://github.com/google/mediapipe/issues/41 .
We will try to reproduce on our end also .

**Comment by mcclanahoochie** [comment]
Hi, The issue should be solved the [v0.6.5 release](https://github.com/google/mediapipe/releases/tag/v0.6.5) (or newer) . Please have a look and let us know
