### ISSUE TITLE
GPU version of Python interface doesn't work

### ISSUE THREAD

**Issue by mariamrahmaani** [google/mediapipe#1740]
Hi 

 I am creating a GPU version of Python interface and the 4 steps below run fine without any issue. However I don't see any load in GPU. (The Samplepatch below is from here: https://github.com/google/mediapipe/issues/1651 )

This is what I have done on my ubuntu 20.4 server with A100 GPU:

1. Download the mediapipe.v0.8.3.1 and cd to the directory
2. git apply Samplepatch.diff
3. python setup.py gen_protos
4. python setup.py install

This runs without any error, however when I run the holistic model I don't see any activity with nvidia-smi

How can I make sure that the GPU model is loaded? Am I doing the steps above correctly? Anything I am doing wrong?
Thanks so much,
Mariam

**Comment by jiuqiant** [comment]
@mcclanahoochie, can you verify if gpu is truly enabled?

**Comment by mariamrahmaani** [comment]
Other GPU-based models are working fine. I am using a transformer based model and the GPU is under load and it's showing 70-80% load in nvidia-smi. But I don't see any load if I use this mediapipe model.

**Comment by mariamrahmaani** [comment]
Any update?

**Comment by mcclanahoochie** [comment]
I can verify things in mediapipe are running on the gpu by inspecting the logs and adding debug prints to the inference_calculator_*cc files (notice "xxx cpu" from inference_calculator_cpu.cc did not print).

```
pixelcruncher.mediapipe{(0.8.3.1)} $ ~/.pyenv/versions/mediapipe-env-3.8.3/bin/python3.8 mediapipe/python/solutions/holistic-demo.py 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20210325 20:43:23.196137 3341168 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I20210325 20:43:23.204969 3341233 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 Mesa 20.3.4)
I20210325 20:43:23.205590 3341168 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I20210325 20:43:23.209374 3341234 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 Mesa 20.3.4)
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Following operations are not supported by GPU delegate:
DEQUANTIZE: 
577 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
W20210325 20:43:23.354154 3341233 inference_calculator_gl.cc:129] xxx gpu
ERROR: Following operations are not supported by GPU delegate:
DEQUANTIZE: 
164 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
W20210325 20:43:23.954829 3341233 inference_calculator_gl.cc:129] xxx gpu
W20210325 20:43:24.574306 3341233 inference_calculator_gl.cc:129] xxx gpu
W20210325 20:43:24.705494 3341233 inference_calculator_gl.cc:129] xxx gpu
W20210325 20:43:24.932015 3341233 inference_calculator_gl.cc:129] xxx gpu
W20210325 20:43:25.440307 3341233 inference_calculator_gl.cc:129] xxx gpu
...
```

Do the other gpu examples show up on nvidia-smi? 

I can open up Chrome and run intensive [webgl programs](https://webglsamples.org/aquarium/aquarium.html) and nvidia-smi doesn't show any gpu usage.

**Comment by mariamrahmaani** [comment]
Interesting that nvidia-gpu doesn't show anything, and media-pipe log show it does.
Thanks for checking.
Can you please also compare the CPU and GPU time? Generally people run the model on GPU to get a performance gain. However in my case the GPU model  is much slower than CPU and nvidia-smi doesn't show anything. Is it possible that mediapipe doesn't load GPU enough? Is there a way for you to compare the execution time between CPU and GPU in one system? If GPU model is running much slower then using media-pipe GPU models don't make sense.

**Comment by abdelrahmanzied** [comment]
@mariamrahmaani 
Check the usage of GPU using Task Manager >> Performance.

**Comment by sgowroji** [comment]
Hi @abdelrahmanzied , Glad for your suggestions. @mariamrahmaani  Assuming your above query resolved. We are closing this issue. Thanks!

**Comment by tankchenggeng** [comment]
How to get Samplepatch.diff?

**Comment by sureshdagooglecom** [comment]
MediaPipe Python package only contains CPU graphs. If you need to run any GPU graphs, see #1651 (comment).
