### ISSUE TITLE
Why mediapipe Js solution does not uses ImageTransformation

### ISSUE THREAD

**Issue by vkrytpo** [google/mediapipe#1742]
**About:** 
Mediapipe-Js, depends on size of input video stream, whereas other platforms(android) does not depends on size of input video stream.

**Issue:**
in Medipipe-Js version, output fps will be half, if you double input video resolution.

**Reference:**
In desktop, it  does'nt seems a problem, but in mobile output fps is near about (6-8 FPS), which we can increase using **ImageTransfarmation (converts any size stream into 256x256)** 

**Optional:**
this issue will be fixed automatically with [issues-1741](https://github.com/google/mediapipe/issues/1741)
we really need build config, setup for JS/WASM also.

**Comment by sgowroji** [comment]
Closing this issue as the duplicate is closed. https://github.com/google/mediapipe/issues/1741.

**Comment by tyrmullen** [comment]
FWIW, I suspect that halving resolution would not actually double speed here.  The ML models being used have a fixed input size and output size (i.e. there's an ImageTransformationCalculator/GlScalerCalculator inside the graph already), so the main speed gains would be your end rendering code, or what you get from not having to handle textures quite as large.  So I'd imagine you'd see an increase in performance, but probably a slight one (in general, the ML is the bottleneck)-- nowhere near doubling.  So to increase performance (at the cost of accuracy) by changing resolution on the critical path, an entirely different ML model would likely be necessary.
