### ISSUE TITLE
Creating a dll out of mediapipe`s demo_run_graph_main.cc

### ISSUE THREAD

**Issue by vamsee-asu2019** [google/mediapipe#1746]
Does anyone know how to create a dll out of the demo_run_graph_main.cc for face_mesh?

**Comment by sgowroji** [comment]
Adding this [Reference](https://github.com/google/mediapipe/issues/1162) as we see others expecting the similar!

**Comment by mgyong** [comment]
@jiuqiant  Can u help?

**Comment by vamsee-asu2019** [comment]
@jiuqiant @mgyong  Can you guys help me with this issue?

**Comment by vamsee-asu2019** [comment]
Is anyone looking into this?

**Comment by jiuqiant** [comment]
Due to limited resources, we are not actively working on this. You can follow https://stackoverflow.com/questions/49664449/can-bazel-build-dll to build dlls.

**Comment by sgowroji** [comment]
Hi @vamsee-asu2019  above comment resolved your query. So closing this issue. Thanks.
