### ISSUE TITLE
Is coordinate axis fixed for mediapipe facemesh ?

### ISSUE THREAD

**Issue by aarushi-mittal** [google/mediapipe#1750]
Hello,

I am trying to understand how coordinates are captured in mediapipe facemesh.

If my face is not stationary , but constantly moving with respect to my webcam , the coordinates keep changing.

I wanted to understand if the origin is static for the entire 2-D plan where my image is captured or the origin keeps on changing as my face orientation (or angle) changes.

Kindly suggest.

Thanks,
Aarushi

**Comment by sgowroji** [comment]
Adding @ ivan-grishchenko as he already addressed your similar issues here [1724](https://github.com/google/mediapipe/issues/1724#issuecomment-797140059)

**Comment by ablavatski** [comment]
Hey Aarushi! Yes, you are right that the coordinates origin is static for the entire 2D plane and located in the top left corner. In other words, the top left corner is always (0, 0) and the bottom right corner is (255, 255).
