### ISSUE TITLE
Building AAR failed with protobuf errors

### ISSUE THREAD

**Issue by Epitapher** [google/mediapipe#1751]
After checking out the master branch, I can't compile the aar example in https://google.github.io/mediapipe/getting_started/android_archive_library.html. I followed every step but a lot of errors regarding protobuf were generated. I modified `mediapipe_aar.bzl` and added `"@com_google_protobuf//:protobuf_javalite",` to `deps` of `android_library`, most errors disappeared but still couldn't get pass `CalculatorProto.java`, I got errors like: `could not resolve com.google.mediapipe.proto.StreamHandlerProto.InputStreamHandlerConfig`, etc.

I used to be able to compile the example with 0.8.2.

**Comment by jiuqiant** [comment]
See https://github.com/google/mediapipe/issues/1679#issuecomment-788323387
