### ISSUE TITLE
Wiki page on FaceMesh landmarks? 

### ISSUE THREAD

**Issue by AmritAmar** [google/mediapipe#1752]
Is there a wiki page or resource that outlines all the landmarks available in the geometry predicted in FaceMesh? [This already exists for pose.](https://google.github.io/mediapipe/images/mobile/pose_tracking_full_body_landmarks.png) I want to be able to get certain facial landmarks directly.

**Comment by sgowroji** [comment]
Hi @AmritAmar , You can find the complete details [here](https://google.github.io/mediapipe/solutions/face_mesh) but you need to deep dive in the links to get more details ,  Assuming you are expecting this  referenes [ref1](https://blog.tensorflow.org/2020/03/face-and-hand-tracking-in-browser-with-mediapipe-and-tensorflowjs.html) and [ref2](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png)

**Comment by sgowroji** [comment]
Hi @AmritAmar Did you get a chance to go through above comment. Thanks!

**Comment by AmritAmar** [comment]
Thanks a lot! ref2 helps!
