### ISSUE TITLE
Python Get angles like Android, missing Landmark info

### ISSUE THREAD

**Issue by airtablereddit** [google/mediapipe#1754]
Hi Google

I would like to calculate angles in Python but I noticed that Landmark Type info is missing in the API like it is possible in Android [here](https://developers.google.com/ml-kit/vision/pose-detection/classifying-poses#expandable-1)

In the Python [Pose.py I noticed that there is a Landmark class](https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/pose.py) but it's not used. 
Please help me get the angles. Thanks

**Comment by jiuqiant** [comment]
You can get landmark x and y coordinates from MediaPipe Pose by the following:

```
 image_height, image_width, _ = image.shape
 # Convert the BGR image to RGB before processing.
 results = pose.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
nose_x = results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].x * image_width
nose_y = results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].y * image_height
```

Then,  you can get angle by following MLKit's example.
