### ISSUE TITLE
how to get face Landmarks from faceGeometry?

### ISSUE THREAD

**Issue by bugmany** [google/mediapipe#1755]
from project faceeffect, i've get faceGeometry and Matrix, but cann't get face Landmarks, such as landmark 468's points, how to get it?

**Comment by sgowroji** [comment]
Hi @bugmany, Could you please elaborate the issue with complete details. Thanks!

**Comment by bugmany** [comment]
@sgowroji , from faceeffect project, with the callback as below, i can get faceGeometry and Matrix from the Packet,
- (void)mediapipeGraph:(MPPGraph*)graph
       didOutputPacket:(const ::mediapipe::Packet&)packet
            fromStream:(const std::string&)streamName {
const auto& faceGeometry = packet.Get<std::vector<::mediapipe::face_geometry::FaceGeometry>>();
},
so, i want get face NormalizedLandmark from the Packet, such as below, but i could not found how to do it.
const auto& face_landmarks = packet.Get<std::vector<::mediapipe::NormalizedLandmarkList>>();
thanks a lot.

**Comment by sgowroji** [comment]
@bugmany This  [issue](https://github.com/google/mediapipe/issues/1618#issuecomment-780184827) may help you . Thanks!

**Comment by bugmany** [comment]
@sgowroji, i'll try it, thanks a lot.
