### ISSUE TITLE
Face coord

### ISSUE THREAD

**Issue by RarDay** [google/mediapipe#1760]
Hello everyone, I use face recognition on python, how can I draw lines of faces in the likeness of Java?

What i have 
![image](https://user-images.githubusercontent.com/57527303/111459917-65227580-872c-11eb-9afa-5d836efe027c.png)

What i want
![image](https://user-images.githubusercontent.com/57527303/111459980-78354580-872c-11eb-9e99-0be1a0ebf35f.png)

Yes, I have access to the coordinates, but I don't want to manually iterate through the array
```
idx_to_coordinates = {}
for idx, landmark in enumerate(face_landmarks.landmark):

    landmark_px = _normalized_to_pixel_coordinates(landmark.x, landmark.y, image_cols, image_rows)
    if landmark_px:
        idx_to_coordinates[idx] = landmark_px

 opencv_coordinates.append(idx_to_coordinates)
 print(idx_to_coordinates)
 
 >> {0: (216, 322), 1: (220, 294), 2: (218, 305), <...> 466: (270, 266), 467: (273, 264)}
```

And another question, do you have any options for face recognition?

**Comment by gkarpiak** [comment]
Hi @RarDay, thanks for the interest in MediaPipe

You could reuse indexes available in [face_landmarks_to_render_data_calculator](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_mesh/calculators/face_landmarks_to_render_data_calculator.cc#L33-L60) to render contours you want.

Face recognition is not available in face detection or face mesh modules.

**Comment by RarDay** [comment]
@gkarpiak Hi again, maybe you have compatibility with Intel Real Sense? I want to find faces on a 3D point cloud
But after using your coordinates everything is exactly for some reason I slide down
![image](https://user-images.githubusercontent.com/57527303/112148964-89c89280-8bef-11eb-978f-dc91f5a6f84c.png)
![image](https://user-images.githubusercontent.com/57527303/112148985-8fbe7380-8bef-11eb-836b-6aa71727ab0f.png)

**Comment by gkarpiak** [comment]
Not sure I got the question correctly, but:
1. There's no compatibility with Intel Real Sense, and it was not considered.
2. If landmarks are shifted, maybe you could adjust that me (basically shift, so they fit the other detections)

**Comment by sgowroji** [comment]
Hi @RarDay, Did you get a chance to look above comment. Thanks!

**Comment by sgowroji** [comment]
Hi @RarDay, Please respond to the above comments. Thanks!
