### ISSUE TITLE
extract Hair segementation mask from mediapipe

### ISSUE THREAD

**Issue by shivSD** [google/mediapipe#1762]
Was able to get the mediapipe & Hair segmentation binary working. Now i need extract mask of the hair segmentation. Need some input on how to extract the mask data from mediapipe.

**Comment by sgowroji** [comment]
Hi @shivSD Could you please elaborate the issue with your references to understand it much better. Thanks.

**Comment by sgowroji** [comment]
Hi @shivSD , Can you address above comment.

**Comment by shivSD** [comment]
Basically i want to tap the predicted output from hair segmentation inference network. Please can you give me some clues which files i need to look for.  something like this [link](https://github.com/google/mediapipe/issues/64) but i need to extract the hair mask.

**Comment by kartynnik** [comment]
In the [corresponding graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hair_segmentation/hair_segmentation_desktop_live.pbtxt#L128), the `MASK:hair_mask` output stream of `TfLiteTensorsToSegmentationCalculator` is the OpenCV `Mat` containing the segmentation mask.

**Comment by sgowroji** [comment]
Hi @shivSD  Above comment resolved your query. So closing this issue . Thanks!

**Comment by dheeraj221b** [comment]
Hello guys, I am stuck with same problem, following way I am trying to get the mask data. but it is crashing while doing so.
processor.addPacketCallback("hair_mask", PacketCallback {
            PacketGetter.getProtoBytes(it)
})

Can you please help I can get the hair segmentation related data? My need is to validate hair part on the body for which I need some data related to hair?
