### ISSUE TITLE
how to open the local video(no-camera video)? could you give some suggestions, thanks!!!

### ISSUE THREAD

**Issue by wxk2008** [google/mediapipe#1763]

**Comment by wxk2008** [comment]
on the android platform

**Comment by sgowroji** [comment]
Hi @wxk2008, Could you explain a bit more about your issue. 

If attaching a video  from the gallery you can get in android using intents and there are many ways [ref](https://stackoverflow.com/questions/4922037/android-let-user-pick-image-or-video-from-gallery).

**Comment by sgowroji** [comment]
Hi @wxk2008 ,  Did you get a chance to go through the above comment. Thanks!

**Comment by sgowroji** [comment]
Hi @wxk2008  Assuming you are resolved, we are closing this issue. Thanks!
