### ISSUE TITLE
Mediapipe provides model in the format .pbtxt, how can I use it in my Python code to get inference?

### ISSUE THREAD

**Issue by waghts95** [google/mediapipe#1764]
With reference to your below documentation, 
Running on CPU
Graph: mediapipe/graphs/iris_tracking/iris_tracking_cpu.pbtxt
Target: mediapipe/examples/desktop/iris_tracking:iris_tracking_cpu
Running on GPU
Graph: mediapipe/graphs/iris_tracking/iris_tracking_gpu.pbtxt
Target: mediapipe/examples/desktop/iris_tracking:iris_tracking_gpu

How can I use iris_tracking_cpu.pbtxt or ris_tracking_cpu in my python code ?

**Comment by jiuqiant** [comment]
See the solution at https://github.com/google/mediapipe/issues/1530#issuecomment-790210796.
