### ISSUE TITLE
Observing latest pose@0.2 model is less stable than previous pose@0.1 model on java script.

### ISSUE THREAD

**Issue by Ashish-Balhara** [google/mediapipe#1765]
We are using mediapipe's pose model to detecting poses via web (html+javascript). A few days ago, we have found more fluctuation of joint points from the model. It seems you have been updated the new pose model (pose@0.2) recently. In our code, when we reverted back to the pose@0.1 model, joint points seem to more stable, and less fluctuate. 
is it a known issue (stablity issue in pose@0.2)?

**Comment by sgowroji** [comment]
Hi @Ashish-Balhara, Could you please help us with your error or issues with exception logs, warnings or a video with defects. Thanks.

**Comment by Ashish-Balhara** [comment]
@sgowroji , thanks for reply. 
There is no error, exception or warning as such. Its just an observation that we felt. we have  tried pose model on a hip abduction exercise, for which we counting the leg movement repetition. After having new model (pose@0.2), we started observing inconsistent repetition, and yesterday we decided to used back to pose@0.1 model in our code, then we found consistent repetition count. So its just an observation. If you think there is no stability issue in new model, and then just ignore my observation and close this issue.

**Comment by sgowroji** [comment]
Hi @Ashish-Balhara, Thank you so much for showing interest in MediaPipe. We are Open to know any inconsistent 
 Observations you find  in the MediaPipe model will be grateful.  You can share your inconsistent repetition observation with a screenshot or a video or your repo to understand much better.  Thank you!
