### ISSUE TITLE
Mediapipe fullscren

### ISSUE THREAD

**Issue by vandics** [google/mediapipe#1766]
How to use medipipe cv2.imshow on fullscreen?

**Comment by sgowroji** [comment]
Hi @vandics Its more specific to opencv, not belongs to media pipe.  You try in other forums for better solution.
I can share you the [reference](https://gist.github.com/ronekko/dc3747211543165108b11073f929b85e), but not sure about it.

**Comment by vandics** [comment]
Thank you for your answer, it's help me so much. One more questions again, as stated on mediapipe blog, landmark output consist of x, y and normalize between 0-1. If it not normalized, will x,y consitst of pixel instead on cm or metre?

**Comment by sgowroji** [comment]
Hi @vandics  could you please share where it was mentioned in the document and which solution are you referring .
And the Main question was resolved in this thread you can raise an anther question with clear description and complete details in a new one. Closing this ticket as the above query resolved. Thanks!
