### ISSUE TITLE
Segmentation fault (core dumped) on Ubuntu for python program only

### ISSUE THREAD

**Issue by sufiaji** [google/mediapipe#1767]
Hi Team,

Thanks for this awesome framework. However I encountered error when running the Python Face Mesh solution on Ubuntu 20.04. Instead of re-open the issue #1734  , I raised a new issue here and let me mention the detail problem.

Platform: Ubuntu 20.04
Python: 3.8.5
Solution: Face Mesh

Note that this error doesn't happen on MacOS and Windows 10, and only happen on Python program (so far we don't have any issue running the C++ face mesh sample on Ubuntu)

below is the code I try to run:

![image](https://user-images.githubusercontent.com/7789546/111642051-545b2800-8830-11eb-8c1a-5ea2b77644d3.png)

and the error raised as below:

![image](https://user-images.githubusercontent.com/7789546/111642129-663ccb00-8830-11eb-84d8-54e0780e49f5.png)

the mediapipe code that hits error:

![image](https://user-images.githubusercontent.com/7789546/111642188-7654aa80-8830-11eb-8691-044d459047e5.png)

Kindly advise since we need to run our program on Ubuntu.
Thank you

**Comment by sgowroji** [comment]
Hi @sufiaji, Apology for closing the previous issue on the wrong note. I have reopened it and added appropriate owner to take your issue to next steps. We can duplicate this present issue to [#1734](https://github.com/google/mediapipe/issues/1734) and Please follow on the previous with latest updates.

**Comment by sufiaji** [comment]
Hi @sgowroji 

Ok thank you!

**Comment by sgowroji** [comment]
Closing this issue as duplicate is closed https://github.com/google/mediapipe/issues/1734
