### ISSUE TITLE
On the android platform, when the handtracking application is pushed to the background, the SurfaceView is destroyed and the camera is turned off 

### ISSUE THREAD

**Issue by wxk2008** [google/mediapipe#1769]
On the android platform, when the handtracking application is pushed to the background, the SurfaceView is destroyed and the camera is turned off.When the handtracking application is brought to front, the camera remains closed.In order to solve this issue, I put the startCamer-function on the SurfaceCreated, but there is a new issue, the camera is opened, but the video does not appear to uploaded to the FrameProcessor.The changed code as follows:
@Override
  protected void onResume() {
    super.onResume();
    Log.d("camera", "onresume");
    converter = new ExternalTextureConverter(eglManager.getContext());
    converter.setFlipY(FLIP_FRAMES_VERTICALLY);
    converter.setConsumer(processor);
    cameraHelper = new CameraXPreviewHelper();
    cameraHelper.setOnCameraStartedListener(
        surfaceTexture -> {
          previewFrameTexture = surfaceTexture;
        });
    if (PermissionHelper.cameraPermissionsGranted(this)) {
      cameraIsOpen = true;
    }
  }

private void setupPreviewDisplayView() {
    previewDisplayView.setVisibility(View.VISIBLE);
    ViewGroup viewGroup = findViewById(R.id.preview_display_layout);
    viewGroup.addView(previewDisplayView);

    previewDisplayView
        .getHolder()
        .addCallback(
            new SurfaceHolder.Callback() {
              @Override
              public void surfaceCreated(SurfaceHolder holder) {
                //Log.d("camera", "openBool" + cameraIsOpen);
                if (cameraIsOpen) {
                   startCamera();
                }

                //startCamera();
                processor.getVideoSurfaceOutput().setSurface(holder.getSurface());
              }

 private void startCamera() {
    //cameraHelper = new CameraXPreviewHelper();
    //cameraHelper.setOnCameraStartedListener(
        //surfaceTexture -> {
          //previewFrameTexture = surfaceTexture;
          // Make the display view visible to start showing the preview. This triggers the
          // SurfaceHolder.Callback added to (the holder of) previewDisplayView.
          //previewDisplayView.setVisibility(View.VISIBLE);
        //});
    cameraHelper.startCamera(this, CAMERA_FACING, /*surfaceTexture=*/ null);
    //cameraHelper.startCamera(this, CAMERA_FACING, previewFrameTexture);
  }

could you give me some advice? thanks

**Comment by sgowroji** [comment]
@wxk2008  Did you encounter any warnings or error logs  while doing the above scenario. Please share if you have any  error console logs to understand the issue much better. Thanks!
