### ISSUE TITLE
Is there any way to get a detection output (image with landmarks) of  face mesh for every frame on android platform? 

### ISSUE THREAD

**Issue by midhulavijayan** [google/mediapipe#1770]

**Comment by sgowroji** [comment]
Hi @midhulavijayan we have a clear documentation for this. Please go [here](https://google.github.io/mediapipe/solutions/face_mesh#ml-pipeline) and let us know any further queries you have. Thanks!

**Comment by midhulavijayan** [comment]
My goal is to access each of the processed frame/raw input frame, and use it for further processing. Is there any way to extract the raw frame/processed frame from main activity?

Can i access the input raw frame/ processed frame using processor.addPacketCallback
processor.addPacketCallback(
                OUTPUT_LANDMARKS_STREAM_NAME,
                (packet) -> {
                    
}

**Comment by sgowroji** [comment]
Hi @midhulavijayan, Assuming this link will help you to understand better for you. https://github.com/google/mediapipe/issues/535#issuecomment-601492991, https://github.com/google/mediapipe/issues/1233

**Comment by midhulavijayan** [comment]
I am able to extract the landmark points using the following script,

if (Log.isLoggable(TAG, Log.VERBOSE)) {
            processor.addPacketCallback(
                    OUTPUT_LANDMARKS_STREAM_NAME,
                    (packet) -> {
                        Log.v(TAG, "Received multi-hand landmarks packet.");
                        List<NormalizedLandmarkList> multiHandLandmarks =
                                PacketGetter.getProtoVector(packet, NormalizedLandmarkList.parser());
                        Log.v(
                                TAG,
                                "[TS:"
                                        + packet.getTimestamp()
                                        + "] "
                                        + getMultiFaceLandmarksDebugString(multiHandLandmarks));
                    });
        }

My question is, how to access the processed frame/raw input frame?

**Comment by sgowroji** [comment]
Hi @midhulavijayan Could you able to elaborate your requirement.

**Comment by midhulavijayan** [comment]
I need to access the landmarks and also need to access the raw frames. Because i want to crop the eye region and eyebrow region from the input image based on the eye landmark co-ordinates and eye brow co-ordinates. I am referring the following link,

https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example

In the MainActivity i could able to extract the normalized landmark points. 

processor.addPacketCallback(
                OUTPUT_LANDMARKS_STREAM_NAME,
                (packet) -> {
                    List<NormalizedLandmarkList> multiHandLandmarks =
                            PacketGetter.getProtoVector(packet, NormalizedLandmarkList.parser());

My aim is to extract the landmark points and process the input image/raw image based on the normalized landmark points. Is there any way to access the input frame/raw frame from the MainActivity?. Thanks

**Comment by mcclanahoochie** [comment]
The stream for the input camera textures is [here](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example/blob/master/app/src/main/java/com/example/mediapipemultihandstrackingapp/MainActivity.java#L41). You can add a callback for that.

**Comment by mcclanahoochie** [comment]
The processor [gets frames](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example/blob/master/app/src/main/java/com/example/mediapipemultihandstrackingapp/MainActivity.java#L144) from the ExternalTextureConverter (which converts the raw camera surface/texture into GL_TEXTURE2D textures). You can create a [consumer](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/TextureFrameConsumer.java#L20:18) to add to the converter that receives the onNewFrame() input image

**Comment by sgowroji** [comment]
Hi @midhulavijayan Did you get a chance to go through the above comment. Thanks!

**Comment by midhulavijayan** [comment]
Hi @mcclanahoochie , Thanks for the reply. I tried it but unfortunately not working. I tried https://github.com/Cubbee/mediapipe this solution suggested by @cubbee and it worked.
