### ISSUE TITLE
[Built-from-code Python Interface] Several folders are missing in site-packages/mediapipe/framework/

### ISSUE THREAD

**Issue by prophett0527** [google/mediapipe#1772]
Hello, I am trying to build python interface from source code.
My environment is as below:
- Ubuntu 16.04
- Python 3.7
- GCC 8.4
- Mediapipe Code: 
  > git clone https://github.com/google/mediapipe.git
- OpenCV Setting:
  > ./setup_opencv.sh
- Build command: 
  > python3 setup.py gen_protos
  > python3 setup.py install --link-opencv
- Pre-build Pkg Install:
  > pip3 install mediapipe
-

The build is successful.
The following code has no problem for pre-build python interface:
> import mediapipe as mp
> mp_pose = mp.solutions.pose
- 
But when I run this code for built-from-code interface, I get the following error:
> import mediapipe as mp
> mp_pose = mp.solutions.pose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mediapipe' has no attribute 'solutions'
- 
So I compared the installed packages in `site-packages/mediapipe` for both pre-build and built-from-code packages.
I found that several folders are missing from `site-packages/mediapipe/framework/` for built-from-code package.
There are `./deps ./formats ./stream_handler ./tool` folders in `site-packages/mediapipe/framework/` for pre-build package.
But none of these folders exist in `site-packages/mediapipe/framework/` for built-from-code package.

Are there something wrong with my build?
**There are no build errors**, which is very difficult for me to know what's wrong.

**Comment by sgowroji** [comment]
@prophett0527 Go through this issues https://github.com/google/mediapipe/issues/1349,  [1466](https://github.com/google/mediapipe/issues/1466) and  [1515](https://github.com/google/mediapipe/issues/1515). This can help you.

**Comment by sgowroji** [comment]
Hi @prophett0527 Did you get a chance to go through the above comment. Thanks!

**Comment by sgowroji** [comment]
Hi @prophett0527  Assuming you are resolved from the above comments. Hence closing this issue. Thanks!
