### ISSUE TITLE
Error in fail: Repository command failed INFO: Could not find files for the given pattern(s). ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu' failed; build aborted: Repository command failed

### ISSUE THREAD

**Issue by sanaa-syed268** [google/mediapipe#1774]
I am trying to Bazel build the hello world c++ from mediapipe website, however, I keep getting errors in finding target file repeatedly. Even though the file system seems to be correct plz help.

![image](https://user-images.githubusercontent.com/50550249/111789740-7e235600-88e7-11eb-8bfb-c6a2270fe2e7.png)

**Comment by sgowroji** [comment]
Hi @sanaa-syed268, Could you please share more details about the build error, and what machine, OS are you trying to build and there are bazel and media pipe versions.

**Comment by sgowroji** [comment]
Lack of activity we are  closing this issue.
