### ISSUE TITLE
Error compiling java header when building aar

### ISSUE THREAD

**Issue by smooth-crescendo** [google/mediapipe#1777]
I'm trying to build face detection AAR file following official guide, but I'm getting this kind of error:

`ERROR: /home/vladislav/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example1/BUILD:3:14: Compiling Java headers mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example1/libmp_face_detection_aar_android_lib-hjar.jar (49 source files) failed (Exit 1) java failed: error executing command external/remotejdk11_linux/bin/java -Xverify:none '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' ... (remaining 105 argument(s) skipped)`
And then I get a lot of protobuf errors as in #1679 

Code in aar_example1/BUILD:
```
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_face_detection_aar",
    calculators = ["//mediapipe/graphs/face_detection:mobile_calculators"],
)
```

I have tried to build some android examples (including face detection) and they all built successfully.

I have also tried setting JAVA_HOME to `/usr/lib/jvm/java-11-openjdk-amd64/` and to `/usr/lib/jvm/java-8-openjdk-amd64/`. Nothing changed.

**Comment by smooth-crescendo** [comment]
Ok, I tried building with 0.8.2 version, and it worked...

**Comment by rahulsuxsena1** [comment]
Hi @smooth-crescendo , can you please help me what is 0.8.2, is it bazel version? plz help m facing the same issue

**Comment by smooth-crescendo** [comment]
> Hi @smooth-crescendo , can you please help me what is 0.8.2, is it bazel version? plz help m facing the same issue

It's a mediapipe version. You need to clone this repo again and then just do `git checkout tags/0.8.2` in mediapipe directory to switch to 0.8.2 version.

**Comment by tmsbyim01** [comment]
@smooth-vlad Thank you for sharing solution, it's work for me!
