### ISSUE TITLE
ValueError: while processing the input streams of subgraph node InferenceCalculator

### ISSUE THREAD

**Issue by hhakangull** [google/mediapipe#1778]
i got this error and i couldn't fixed ???

ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:facedetectionfrontcpu__Inferencecalculator__facedetectionfrontcpu__input_tensors" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").

**Comment by sgowroji** [comment]
Hi @hhakangull, To address the above error, we need more details of the platform, solution, OS, ALL Steps performed when the error occurred with clear and complete description.

**Comment by hhakangull** [comment]
when i was run mediapipe in ubuntu i got this error:
but if i can run my project on docker i don't take any error
Traceback (most recent call last):
  File "kiosk_docker.py", line 31, in <module>
    from Dosyadan_Resim_Okuma_Yazma import UserRegisterFromFile
  File "/home/hakan/Dosyalar/Face_Recognation_v2/app/Dosyadan_Resim_Okuma_Yazma.py", line 15, in <module>
    face_detector_mediapipe = MediaPipeFaceMesh()
  File "/home/hakan/Dosyalar/Face_Recognation_v2/app/mediapipe_class.py", line 62, in __init__
    self.face_mesh = self.mp_face_mesh.FaceMesh(static_image_mode=True, min_detection_confidence=0.7,
  File "/home/hakan/Dosyalar/Face_Recognation_v2/venv/lib/python3.8/site-packages/mediapipe/python/solutions/face_mesh.py", line 205, in __init__
    super().__init__(
  File "/home/hakan/Dosyalar/Face_Recognation_v2/venv/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 220, in __init__
    validated_graph.initialize(
ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:facedetectionfrontcpu__Inferencecalculator__facedetectionfrontcpu__input_tensors" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").

**Comment by sgowroji** [comment]
Hi @hhakangull, Could you please share the detail steps to reproduce the issue. And also the repo code to understand it much better. Thanks

**Comment by sgowroji** [comment]
Hi @hhakangull, Please respond to my above comments and provide the requested details. Thanks!

**Comment by sgowroji** [comment]
We are closing this ticket as of now due to lack of activity. Thanks!

**Comment by edib** [comment]
Same Problem, Ubuntu 20.04 
Mediapipe 0.8.6
python 3.8 
Code:

```
import cv2
import mediapipe as mp
import time

mpDraw = mp.solutions.drawing_utils
mpPose = mp.solutions.pose
pose = mpPose.Pose()

cap = cv2.VideoCapture(1)
pTime = 0
while True:
    success, img = cap.read()
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = pose.process(imgRGB)
    # print(results.pose_landmarks)
    if results.pose_landmarks:
        mpDraw.draw_landmarks(img, results.pose_landmarks, mpPose.POSE_CONNECTIONS)
        for id, lm in enumerate(results.pose_landmarks.landmark):
            h, w, c = img.shape
            print(id, lm)
            cx, cy = int(lm.x * w), int(lm.y * h)
            cv2.circle(img, (cx, cy), 5, (255, 0, 0), cv2.FILLED)

    cTime = time.time()
    fps = 1 / (cTime - pTime)
    pTime = cTime

    cv2.putText(img, str(int(fps)), (70, 50), cv2.FONT_HERSHEY_PLAIN, 3,
                (255, 0, 0), 3)

    cv2.imshow("Image", img)
    cv2.waitKey(1)

```
Last week this code is working. But now, produces below error:

```
Traceback (most recent call last):
  File "Basics.py", line 7, in <module>
    pose = mpPose.Pose()
  File "/home/user/.local/lib/python3.8/site-packages/mediapipe/python/solutions/pose.py", line 171, in __init__
    super().__init__(
  File "/home/user/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 229, in __init__
    validated_graph.initialize(
ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:posedetectioncpu__Inferencecalculator__posedetectioncpu__input_tensors" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").`

```

**Comment by kivancagaogluu** [comment]
Same here on Ubuntu 21.10. Does anyone have solution for this error? Whenever i use mediapipe code crashes immediately
