### ISSUE TITLE
python pose solution sample code produces attribute error

### ISSUE THREAD

**Issue by stevenwman** [google/mediapipe#1785]
used the exact code for the python pose solution [here](https://google.github.io/mediapipe/solutions/pose.html#python-solution-api) (deleted the single image recognition part of the code) and running in jupyter notebook where I received error of missing __enter__ attribute on mp.solution.pose.Pose: 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-4511d0ca00a1> in <module>
     31 # For webcam input:
     32 cap = cv2.VideoCapture(0)
---> 33 with mp_pose.Pose(upper_body_only=True,min_detection_confidence=0.5,min_tracking_confidence=0.5) as pose:
     34     while cap.isOpened():
     35         success, image = cap.read()

AttributeError: __enter__
-----------------------------------------------------------------------------
```
I suspect it's due to the use of with and the fact that mp.pose.Pose which is natively mp.solutions.pose.Pose does not have an enter attribute. 

Same issues with the holistic script for python
[mediapipe pose sample solutions.txt](https://github.com/google/mediapipe/files/6185164/mediapipe.pose.sample.solutions.txt)

**Comment by sgowroji** [comment]
Hi @stevenwman,  Yes it is the use of **with** statement  https://www.python.org/dev/peps/pep-0343/.  you can even check  the same on colab file.

**Comment by sgowroji** [comment]
Hi @stevenwman, Assuming your query resolved with above comments, we are closing this issue. Please feel free to open if the issue still exists. Thanks!
