### ISSUE TITLE
Wrong or misnamed landmark index in hand_landmarks_to_rect_calculator.cc

### ISSUE THREAD

**Issue by ocastan** [google/mediapipe#1787]
In mediapipe/modules/hand_landmark/calculators/hand_landmarks_to_rect_calculator.cc some landmarks are used to create a roi from finger landmarks, to be used in the next frame:
constexpr int kMiddleFingerPIPJoint = 6;
constexpr int kIndexFingerPIPJoint = 4;
constexpr int kRingFingerPIPJoint = 8;
As far as I understand these indexes are relative to a subset created in mediapipe/modules/hand_landmark/hand_landmark_landmarks_to_roi.pbtxt which correspond to original indexes 0, 1, 2, 3, 5, 6, 9, 10, 13, 14, 17, 18
Looking at landmarks names in https://google.github.io/mediapipe/solutions/hands these relative indexes should be 7, 5, 9 instead of 6, 4, 8 or should be renamed kMiddleFingerMCPJoint, kIndexFingerMCPJoint and kRingFingerMCPJoint respectively. Right now the roi orientation calculation use the palm and not the 1st phalanges, I can't say if it's on purpose.
Thanks

**Comment by sgowroji** [comment]
Hi @ocastan, can you illustrate the above wrong or misnamed landmark details a bit more and why?

**Comment by ocastan** [comment]
Hello
I'll do my best to reformulate to make it more clear: the landmarks named kMiddleFingerPIPJoint, kIndexFingerPIPJoint and kRingFingerPIPJoint in 
hand_landmarks_to_rect_calculator.cc correspond to landmarks named MIDDLE_FINGER_MCP, INDEX_FINGER_MCP and RING_FINGER_MCP in the model description figure https://google.github.io/mediapipe/images/mobile/hand_landmarks.png (the indexes are different because only a subset is kept in the graph by another calculator before calling hand_landmarks_to_rect_calculator.cc).
Since the variables are named after the PIP finger joint instead of the MCP joint, I can imagine 2 different cause: the variables have bad names, there's no real impact apart misunderstanding when reading the code, or the landmarks selected are not the intended ones and in this case the rect calculation might not be correct.

**Comment by eknight7** [comment]
Reassigning to @fanzhanggoogle since he knows about the [calculator](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/calculators/hand_landmarks_to_rect_calculator.cc) in question.
