### ISSUE TITLE
SSL certification error while downloading dependency libraries via Bazel

### ISSUE THREAD

**Issue by AkhilRaja** [google/mediapipe#179]
Attaching my logs here below. I am pretty sure this is not a network issue as I tried it on multiple networks. I am on Mac OS, please advice.
I also added github.com certificate to my keychain. I am missing something real simple, just cant see it.

`
WARNING: Download from https://github.com/bazelbuild/rules_cc/archive/master.zip failed: class javax.net.ssl.SSLHandshakeException sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: An error occurred during the fetch of repository 'rules_cc':
   java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_cc/archive/master.zip] to /private/var/tmp/_bazel_apappu/0a0698e16df88d194432fea25f9efb56/external/rules_cc/master.zip: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: While resolving toolchains for target //mediapipe/examples/desktop/hello_world:hello_world: com.google.devtools.build.lib.packages.RepositoryFetchException: no such package '@rules_cc//cc': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_cc/archive/master.zip] to /private/var/tmp/_bazel_apappu/0a0698e16df88d194432fea25f9efb56/external/rules_cc/master.zip: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: com.google.devtools.build.lib.packages.RepositoryFetchException: no such package '@rules_cc//cc': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_cc/archive/master.zip] to /private/var/tmp/_bazel_apappu/0a0698e16df88d194432fea25f9efb56/external/rules_cc/master.zip: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
INFO: Elapsed time: 14.451s
`

**Comment by jiuqiant** [comment]
This cert issue isn't a MediaPipe specific issue and we probably don't have the immediately solution as well. Here are some related links I find. Have you read them before?

[1] http://www.littlebigextra.com/how-to-fix-pkix-path-building-failed-sun-security-provider-certpath-suncertpathbuilderexception/
[2] http://magicmonster.com/kb/prg/java/ssl/pkix_path_building_failed.html
[3] https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
