### ISSUE TITLE
FPS drop when using GLSurfaceView

### ISSUE THREAD

**Issue by rohithsai45** [google/mediapipe#1791]
Hi, 
I am using mediapipe and custom tflite model to achieve portrait segmentation.
Here is the repo link for the same https://github.com/rohithsai45/Segmentation

When i use SurfaceView, i am getting 25-30fps, but when i replace it with GLSurfaceView and trying out new rendering pipeline then there is FPS drop( getting 15-20FPS). Help around this would be highly appreciated.

Device - Samsung Galaxy Note10
OS - Android11

PS: While compiling the repo, please download aar from here (https://gofile.io/d/8oLAQE) and place it in libs.

Thanks.

**Comment by mcclanahoochie** [comment]
Can you explain why you need GlSurfaceView? Typically it is [not needed](https://source.android.com/devices/graphics/arch-sv-glsv#glsurfaceview).
There may be some extra internal conversion going on between the mediapipe gl context and/or memory and the GlSurfaceView context/memory. Otherwise I'm not sure.

**Comment by rohithsai45** [comment]
my bad, fps drop is because of model we are using, not because of GLSurfaceView.

**Comment by fchen09** [comment]
@rohithsai45 May I ask how you get 25-30FPS? Since it only runs 15 fps with the official example. I use note 10 and Android 12.

**Comment by fchen09** [comment]
> @rohithsai45 May I ask how you get 25-30FPS? Since it only runs 15 fps with the official example. I use note 10 and Android 12.

 @rohithsai45 Is it because you used the pose_landmark_lite.tflite? Thanks!
