### ISSUE TITLE
Python wrapper for ObserveOutputStream does not acquire GIL when calling callback

### ISSUE THREAD

**Issue by vktec** [google/mediapipe#1793]
The Python wrapper function `CalculatorGraph.observe_output_stream` registers a callback, but when that callback calls the Python function it does not acquire the Global Interpreter Lock. This results in occasional failed assertions and/or segmentation faults when this callback is called.

**Comment by sgowroji** [comment]
Hi @vktec Could you please elaborate the issue with complete details. Like what solution are you trying and what is your Error and what did you try. Thanks!

**Comment by jiuqiant** [comment]
Probably can do the following change:

```
--- a/mediapipe/python/pybind/calculator_graph.cc
+++ b/mediapipe/python/pybind/calculator_graph.cc
@@ -399,7 +399,12 @@ void CalculatorGraphSubmodule(pybind11::module* module) {
             stream_name,
             [callback_fn, stream_name](const Packet& packet) {
               absl::MutexLock lock(&callback_mutex);
-              callback_fn(stream_name, packet);
+              py::gil_scoped_release gil_release;
+              {
+                // Acquires GIL before calling Python callback.
+                py::gil_scoped_acquire gil_acquire;
+                callback_fn(stream_name, packet);
+              }
               return absl::OkStatus();
             },
             observe_timestamp_bounds));
```
I made 0.8.4.2.1 and uploaded it to test pypi. You can try `pip install --index-url https://test.pypi.org/simple/ mediapipe==0.8.4.2.1` to see if this helps.

**Comment by sgowroji** [comment]
Hi @vktec, Could you please go through the above [comment](https://github.com/google/mediapipe/issues/1793#issuecomment-848268152).

**Comment by sgowroji** [comment]
Hi @vktec, Could you please respond to the above comment. Thanks!

**Comment by philipjhc** [comment]
thank you

**Comment by sgowroji** [comment]
Assuming your resolved, we are closing this issue now. Feel free to reach us if your issue is relevant to the above query.
