### ISSUE TITLE
Error occurred when build in jetson NX

### ISSUE THREAD

**Issue by Trout70** [google/mediapipe#1794]
Hi.
I build mediapipe Python  in jetson NX , error occurred like bellow
Follow the GitHub((https://github.com/jiuqiant/mediapipe_python_aarch64))
jetson NX : jetpack 4.4,  4.5,  4.5.1  All the same  error
os: ubuntu 18.04
python: 3.6
bazel: 3.4.1
code:  python3 setup.py gen_protos && python3 setup.py bdist_wheel

>generating binarypb: mediapipe/modules/face_detection/face_detection_front_cpu
Starting local Bazel server and connecting to it...
WARNING: ignoring LD_PRELOAD in environment.
DEBUG: /home/pipe/.cache/bazel/_bazel_pipe/0f78cad925707e6cce986cc5dbc6ac1e/external/rules_foreign_cc/workspace_definitions.bzl:6:6: `@rules_foreign_cc//:workspace_definitions.bzl` has been replaced by `@rules_foreign_cc//foreign_cc:repositories.bzl`. Please use the updated source location
DEBUG: /home/pipe/.cache/bazel/_bazel_pipe/0f78cad925707e6cce986cc5dbc6ac1e/external/rules_foreign_cc/tools/build_defs/deprecation.bzl:5:10: `@rules_foreign_cc//tools/build_defs/...` is deprecated, please find the relevant symbols in `@rules_foreign_cc//foreign_cc/...`. Note that the core rules can now be loaded from `@rules_foreign_cc//foreign_cc:defs.bzl`
ERROR: /home/pipe/.cache/bazel/_bazel_pipe/0f78cad925707e6cce986cc5dbc6ac1e/external/rules_foreign_cc/toolchains/BUILD.bazel:123:22: @platforms//os:windows is not a valid configuration key for @rules_foreign_cc//toolchains:built_ninja
ERROR: Analysis of target '//mediapipe/modules/face_detection:face_detection_front_cpu' failed; build aborted: Analysis failed
INFO: Elapsed time: 23.231s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (90 packages loaded, 2375 targets \
configured)

**Comment by sgowroji** [comment]
Hi  @Trout70 , This  https://github.com/google/mediapipe/issues/1674#issuecomment-788295898 will address your query. Thanks!

**Comment by sgowroji** [comment]
Hi @Trout70 Did you get a chance to go through the above comment?

**Comment by sgowroji** [comment]
Assuming you are resolved, we are closing this issue. Thanks!
