### ISSUE TITLE
Python packages build failed 

### ISSUE THREAD

**Issue by waiyc** [google/mediapipe#1795]
I followed the [installation steps to build the python package](https://google.github.io/mediapipe/getting_started/python.html#building-mediapipe-python-package) for Ubuntu 18.04 but encounter the following error
```
ERROR: /home/waiyc/catkin_cv_bridge/mediapipe/mediapipe/calculators/tensor/BUILD:594:11: C++ compilation of rule '//mediapipe/calculators/tensor:image_to_tensor_converter_opencv' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc: In member function 'virtual absl::lts_2020_09_23::StatusOr<mediapipe::Tensor> mediapipe::{anonymous}::OpenCvProcessor::Convert(const mediapipe::Image&, const mediapipe::RotatedRect&, const mediapipe::Size&, float, float)':
mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc:106:12: error: could not convert 'tensor' from 'mediapipe::Tensor' to 'absl::lts_2020_09_23::StatusOr<mediapipe::Tensor>'
     return tensor;
            ^~~~~~
Target //mediapipe/modules/face_detection:face_detection_front_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 149.724s, Critical Path: 114.67s
INFO: 1185 processes: 1185 linux-sandbox.
FAILED: Build did NOT complete successfully

```
The error is similar to the one mentioned [here](https://github.com/google/mediapipe/issues/1733#issuecomment-797794009)

**Comment by sgowroji** [comment]
Hi @waiyc Did you try this  https://github.com/google/mediapipe/issues/1733#issuecomment-797796499

**Comment by waiyc** [comment]
@sgowroji I am using version 0.8.0 previously which was built using the same steps. However, version 0.8.0 it does not support for iris detection and objectron detection and thats the reason why I need the latest version

**Comment by sgowroji** [comment]
@waiyc Can you elaborate your query  with complete details. Thanks!

**Comment by sgowroji** [comment]
Hi @waiyc, Can you share the above steps to reproduce the issue.

**Comment by waiyc** [comment]
Hi, @sgowroji  sorry for my late reply. I just found a workaround to install the v0.8.3.1 Mediapipe python package directly via :
> pip install mediapipe 

You can close this for now.

**Comment by sgowroji** [comment]
Glad to see you resolved. Thanks for the update.
