### ISSUE TITLE
Running MediaPipe without any preview on Android

### ISSUE THREAD

**Issue by terabithian007** [google/mediapipe#1797]
I am using MediaPipe to run a pose estimation network followed by an action classifier.
I want to turn off the rendering of the output video and just want to use the output of the classifier in my app.

Are there any examples available that explain how to use mediapipe without any preview rendering ?

TIA

**Comment by sgowroji** [comment]
Hi @terabithian007 Assuming this is similar to your query https://github.com/google/mediapipe/issues/1743. Go through it and let me know if more details needed. Thanks !

**Comment by sgowroji** [comment]
Hi @terabithian007, Did you get a chance to go through the above comment. Thanks!

**Comment by sgowroji** [comment]
Assuming your query is resolved, We are closing this issue. Thanks
