### ISSUE TITLE
modify node option in Android

### ISSUE THREAD

**Issue by weixinz1** [google/mediapipe#1800]
are there any Android API to modify the node option at run time?

**Comment by sgowroji** [comment]
Hi @weixinz1 Could you please elaborate the query with complete details. Thanks!

**Comment by weixinz1** [comment]
I want to change the RecolorCalculatorOptions in 'hair_segmentation_mobile_gpu.pbtxt' in the runtime

**Comment by weixinz1** [comment]
> Hi @weixinz1 Could you please elaborate the query with complete details. Thanks!

I want to change the hair color value of RecolorCalculatorOptions in 'hair_segmentation_mobile_gpu.pbtxt' in the runtime

**Comment by sgowroji** [comment]
Pls go through the doc for [harisegmentation](https://google.github.io/mediapipe/solutions/hair_segmentation) and choose the platform and examples in it.

**Comment by weixinz1** [comment]
@sgowroji I have already read this doc and get the Android project. Is there any method to change the hair color in the run time ?

**Comment by sgowroji** [comment]
Hi @weixinz1,  This can help you resolve your query https://github.com/google/mediapipe/issues/18

**Comment by sgowroji** [comment]
Hi @weixinz1, Did you get a chance to go through the above comment. Thanks!

**Comment by sgowroji** [comment]
Assuming you are resolved with above comment. We are closing this issue.  Feel free to reopen if you still face the same issue.
