### ISSUE TITLE
How to use tracking and profiling hook?

### ISSUE THREAD

**Issue by HyperScypion** [google/mediapipe#1802]
Hi, I don't understand how to you profiling hook, all the time I've got errors can someone explain to me how it should works?

**Comment by sgowroji** [comment]
Hi @HyperScypion Please elaborate  your query with complete details. Like what solution are you trying and where did you encounter the error. And finally, what are the errors. Thanks

**Comment by sgowroji** [comment]
Hi @HyperScypion Can you update on the above comment. Thanks!

**Comment by sgowroji** [comment]
As we see lack of activity on this issue. We are closing it. Thanks!
