### ISSUE TITLE
Can't save landmark list to csv file

### ISSUE THREAD

**Issue by vandics** [google/mediapipe#1803]
I'm trying to save landmark from pose landmark from holistic. When I trying it on image it will work properly, however when work on realtime (webcam) it's show an error like 'results.pose_landmarks' has type None and dont has attribute 'landmark'.Whats wrong with my code?
![image](https://user-images.githubusercontent.com/79313671/112635358-4c256d00-8e6e-11eb-83ed-641677343c76.png)
![image](https://user-images.githubusercontent.com/79313671/112635707-ba6a2f80-8e6e-11eb-9136-ba40374ff359.png)
![image](https://user-images.githubusercontent.com/79313671/112635751-c950e200-8e6e-11eb-94b8-f45d16caa1b8.png)

**Comment by Faiqzakii** [comment]
Because of min_detection_confidence and min_tracking_confidence you set is very high (0.7)
It means not every frame will detecting pose on the webcam

So you can add some condition before extracting the landmark coordinate
```python
if results.pose_landmarks:
    landmark_list_pose = results.pose_landmarks.landmark
```
You can do the same condition for hand landmark

**Comment by vandics** [comment]
Thanks for your advice. You are right that every frame detecting pose on the webcam so I just some condition. Therefore, I have another problem where landmark that are not detected on webcam still appear on the csv file, when it should be not appear on the csv or the value is zero. Do you know whats wrong?

**Comment by Faiqzakii** [comment]
Make sure to assign the value inside `if`, and maybe you can reset the variable for every frame while cap is opened just to make sure no data is added when pose is not detected

**Comment by SayedHamdiF** [comment]
i want to save key points coordinates in csv file for holistic model. could you please share code with me?

**Comment by sgowroji** [comment]
Hi @vandics , Could you please share your issues status. Thanks!

**Comment by sgowroji** [comment]
Hi @vandics, Can you respond to my above comments!

**Comment by vandics** [comment]
hi, sorry for late respond. It solved now. Thank you

**Comment by sgowroji** [comment]
Glad to know you resolved. We are closing this issue now.

**Comment by sgowroji** [comment]
Hi @vandics, Posting your solution will be helpful for other users.

**Comment by SamuelYuan2016** [comment]
Could you also share the code with me? Thank you.

**Comment by vandics** [comment]
maybe as an illustration, when you use the code in a video or in real-time with a duration of 3 minutes and get about 300 frames, then the code will save the file after you use it not when you get the frame. So the code collects all the coordinates of 300 frames and then saves it, not every time it gets a frame, and then it is saved.

**Comment by SamuelYuan2016** [comment]
Nice, it works.  I have not sure if we need put all the data into a database, are there any tips, thank you.

**Comment by vandics** [comment]
I think if you want to put all the data into a database you should change the data format from the code like if you use a database with JSON format. Maybe anyone here could give advice about that or you can open new issues @sgowroji.

**Comment by sgowroji** [comment]
That's fine. Thank you for the answer.
