### ISSUE TITLE
LoaderCould not load trace 'mediapipe_trace_0.binarypb'. UploaderCould not load trace 'mediapipe_trace_0.binarypb': c.h[F] is undefined

### ISSUE THREAD

**Issue by HyperScypion** [google/mediapipe#1804]
After pulling trace file viz says: LoaderCould not load trace 'mediapipe_trace_0.binarypb'.
UploaderCould not load trace 'mediapipe_trace_0.binarypb': c.h[F] is undefined

**Comment by sgowroji** [comment]
Hi @HyperScypion Please provide the clear and complete issue details to understand.

**Comment by sgowroji** [comment]
Hi @HyperScypion  Can you provide the above requested details.

**Comment by sgowroji** [comment]
Lack of activity on this issue. We are closing this ticket. Thanks!
