### ISSUE TITLE
BlazePose in Flutter app

### ISSUE THREAD

**Issue by Rizwan2613** [google/mediapipe#1808]
Hi,
I hope you are fine. I want to ask if there is any way to integrate blazepose model directly in Flutter app. I have found a solution which is implementing it natively. I want to add blazepose without native implemention. Any help will be benificial for me.

Thank you in advance.

**Comment by sgowroji** [comment]
Hi @Rizwan2613,  No plans for flutter package from MediaPipe team. However, there is community example in awesome-mediapipe repo.
