### ISSUE TITLE
Video exporting autocrop with fixed dimensions 

### ISSUE THREAD

**Issue by Tortoise17** [google/mediapipe#1810]
i want to autocrop video on desktop for mobile based dimensions !!! 
is there any way or example which can help ?

**Comment by sgowroji** [comment]
Hi @Tortoise17, Could you provide the solution and platform details. Thanks!

**Comment by Tortoise17** [comment]
I have video on CentOS and I would like to export it for dimensions of iphone frame and instagram dimensions. That is what my question if you have any example to export the autocropped video and also auto flip ?

**Comment by sgowroji** [comment]
At present we dont have any support of the above in IOS and standard examples. Please have a look at this [link](https://google.github.io/mediapipe/solutions/autoflip) we have clear documentation of it.
