### ISSUE TITLE
implement Holistic with React js, static/local import instead cdn.jsdelivr.net

### ISSUE THREAD

**Issue by kywq** [google/mediapipe#1812]
## Description

Hello everyone,

I am building Holistic model with react js, importing the model as seen below. 

`import {  Holistic } from '@mediapipe/holistic/holistic'`

However, when instancing the object Holistic, it takes very long time and I thought it may be fixed by importing the local files instead from pulling them from the CDN (code below).

**Current instancing code:**
`holistic = new Holistic({
      locateFile: (file) => {
        return `https://cdn.jsdelivr.net/npm/@mediapipe/holistic/${file}`;
      }
    });`

The files that we want to be able to import locally are the next:

![image](https://user-images.githubusercontent.com/56016611/112819588-07275380-9085-11eb-966b-a2d92b57c0c5.png)

## Questions

- How do I  change the `https://cdn.jsdelivr.net/npm/@mediapipe/holistic/${file}` for a local import from the files within node modules?
- Is the local import going to solve the problem of Holistic model taking to long to load?

Thanks

Qiu

**Comment by dlucio** [comment]
Hi @kywq.

I guess this solution can work for you.

For the Pose model, first I imported the model and all dependencies.
```js
import {
    drawConnectors,
    drawLandmarks,
} from '@mediapipe/drawing_utils/drawing_utils';

import {
    ControlPanel,
    FPS,
    StaticText,
    Slider,
    Toggle
} from '@mediapipe/control_utils/control_utils';

import { Camera } from '@mediapipe/camera_utils/camera_utils';
import { Pose, POSE_CONNECTIONS } from '@mediapipe/pose/pose';
```

Then I modified the _locateFile_ param to this
```js
const pose = new Pose({
    locateFile: (file) => {
        return `pose/${file}`;
    }
});
```
I hope that helps.

**Comment by mhays-google** [comment]
You should be able to `npm install` the packages locally and set up your locateFile (you probably won't even need to fill out that function, in this case).  However, the time to load the model onto the client really is a factor of internet speed and the size of those holistic models (which involves, I think, three large tensor models).

One thing to check, however, is that it's actually the transferring of these files that is taking some time.  Can you tell me if the speed is just as slow every time you reload the page?

**Comment by kywq** [comment]
@dlucio & @mhays-google 
I have all the packages installed and imported, the problem is the locateFile, it doesn't work without this. 
But code below only works with cdn import  

works
`return` ``https://cdn.jsdelivr.net/npm/@mediapipe/holistic/${file}``

doesn't work
```
const pose = new Pose({
    locateFile: (file) => {
        return `pose/${file}`; 
    }
});
or
const holistic= new Holistic({
    locateFile: (file) => {
        return `holistic/${file}`; 
    }
});
```

@mhays-google 
Especially the first time, it takes ~1:15min
and then it takes ~15secs

**Comment by kywq** [comment]
Here is my dir distribution

**Local mediapipe files**
![image](https://user-images.githubusercontent.com/56016611/113117163-7b413300-920e-11eb-8408-a6b05d22216a.png)
![image](https://user-images.githubusercontent.com/56016611/113117278-901dc680-920e-11eb-9fc5-20ebe7a553a0.png)

**File where I use them**
![image](https://user-images.githubusercontent.com/56016611/113117440-b80d2a00-920e-11eb-9e02-422c6f93e76c.png)
![image](https://user-images.githubusercontent.com/56016611/113117471-c22f2880-920e-11eb-9e4d-6142c1b6b398.png)

**Comment by dlucio** [comment]
@kywq, I assume that you are using the folder build to deploy you app.
So, you should copy the holistic folder to the build folder.
I did that using the webpack plugin **CopyWebpackPlugin** as you can see below.
```js
  new CopyWebpackPlugin({
      patterns: [
          {
              //Wildcard is specified hence will copy only css files
              from: 'src/css/', //Will resolve to RepoDir/src/css and all *.css files from this directory
              to: 'css' //Copies all matched css files from above dest to dist/css
          },
          {
              from: 'node_modules/@mediapipe/pose',
              to: 'pose'
          }
      ]
  })
```

This is the complete **webpack.config.js**
```js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const CopyWebpackPlugin = require("copy-webpack-plugin");

module.exports = {
    mode: 'development',
    entry: {
        'index': './src/index.js'
    },
    devtool: 'inline-source-map',
    plugins: [
        new CleanWebpackPlugin({ cleanStaleWebpackAssets: false }),
        new HtmlWebpackPlugin({
            title: 'MediaPipe Development',
            template: 'src/index.html'
        }),
        new CopyWebpackPlugin({
            patterns: [
                {
                    //Wildcard is specified hence will copy only css files
                    from: 'src/css/', //Will resolve to RepoDir/src/css and all *.css files from this directory
                    to: 'css' //Copies all matched css files from above dest to dist/css
                },
                {
                    from: 'node_modules/@mediapipe/pose',
                    to: 'pose'
                }
            ]
        }),
    ],
    devServer: {
        contentBase: path.join(__dirname, 'dist'),
    },
    output: {
        filename: '[name]_bundle.js',
        path: path.resolve(__dirname, 'dist'),
    },
    module: {
        rules: [{
                test: /\.css$/i,
                use: ['style-loader', 'css-loader'],
            },
            {
                test: /\.(png|svg|jpg|jpeg|gif)$/i,
                type: 'asset/resource',
            }
        ]
    }
};
```

**Comment by alpcapanoglu** [comment]
I'm having the same problem. Tried every approach here and none worked for me. 

Any updates? Any known causes?

**Comment by jaderxnet** [comment]
I'm having the same problem.  Any updates ?

**Comment by jaderxnet** [comment]
Work now. Inspirede by [1823](https://github.com/google/mediapipe/issues/1823 )

I used npm install to download the specific API files to node_modules and copied to local folder referenced in javascript calls.
Step 1 - NPM Install: 

`npm install @mediapipe/pose@0.1 `
`npm install @mediapipe/drawing_utils@0.1 `
`npm install @mediapipe/camera_utils@0.1 `

Step 2 - Copy to files of `node_modules/mediapipe` to `public/mediapipe`

Step 3 - Refereded local files in html:

`<script src="mediapipe/camera_utils/camera_utils.js" crossorigin="anonymous"></script>`
`<script src="mediapipe/drawing_utils/drawing_utils.js" crossorigin="anonymous"></script>`
 `<script src="mediapipe/pose/pose.js" crossorigin="anonymous"></script>`
 
Step 4 - Replace a new Pose pose file in javascript:

`const pose = new Pose({locateFile: (file) => {`
  `return `https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.1/${file}`;`
`}});`

By:

`const pose = new Pose({locateFile: (file) => {`
`return  './mediapipe/pose/${file}\';`
`}});`
 
 Step 5 - NPM uninstall: 

`npm uninstall @mediapipe/pose@0.1 `
`npm uninstall @mediapipe/drawing_utils@0.1 `
`npm uninstall @mediapipe/camera_utils@0.1 `

Thanks

**Comment by sgowroji** [comment]
Hi @kywq, Have you tried checking the above [comment](https://github.com/google/mediapipe/issues/1812#issuecomment-846459141).

**Comment by kywq** [comment]
Hi!! it is already solved, thanks a lot!!

**Comment by jackson-sandland** [comment]
I'm seeing this error when attempting to use CopyWebpackPlugin to locally load @mediapipe/holistic:

**Comment by jackson-sandland** [comment]
Any updates on this? Google doesn't seem to even have one search result for "HookWebpackError: Failed to determine content-type for file". I can't imagine no one else has run into this.
