### ISSUE TITLE
Build Aborted: Problem getting NumPy include path

### ISSUE THREAD

**Issue by b4017816** [google/mediapipe#1813]
Hi, I'm following the steps to create a Mediapipe .AAR but I can't get past an error with NumPy not being detected, 

NumPy was detected as missing after initial install (Ubuntu 20.04 via WSL on Windows 10) during the "hello world" test in the instructions, so I installed NumPy with pip, and the "hello world" test ran fine 

But I run into "Build Aborted: Problem getting NumPy include path" when running the below command from the instructions
'ben@TheRig:~/mediapipe$ sudo bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain     --fat_apk_cpu=arm64-v8a,armeabi-v7a --strip=ALWAYS     //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar'

pip3 list shows NumPy version 1.20.2 installed, I've tried uninstalling and reinstalling and looking for other solutions but none of them have helped me, I would really like to try integrating Iris Tracking into an android app for detecting gaze direction but I need to get the .aar build pipeline set up first so I would really appreciate any help with this, Thanks

Build and error log:

`DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  /home/ben/mediapipe/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
  
  
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

DEBUG: /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_cc' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  /home/ben/mediapipe/WORKSPACE:393:14: in <toplevel>
  /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/tensorflow/workspace2.bzl:1108:19: in workspace
  /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/tensorflow/workspace2.bzl:84:27: in _tf_toolchains
  /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
  
  
  
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 39, in _create_local_python_repository
                numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
        File "/root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/py/python_configure.bzl", line 187, column 19, in _get_numpy_include
                return execute(
        File "/root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/org_tensorflow/third_party/remote_config/common.bzl", line 219, column 13, in execute
                fail(
                
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "39530432fdce0eda8e78d179330ff454f6cbec8973ab7310aab335460a9f06f6"
DEBUG: Repository rules_cc instantiated at:
  /home/ben/mediapipe/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/3f845f2d6ae807198123f0feeae1c47b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar' failed; build aborted: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Elapsed time: 0.291s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)`

**Comment by jiuqiant** [comment]
https://google.github.io/mediapipe/getting_started/troubleshooting.html#missing-necessary-python-packages

**Comment by sgowroji** [comment]
Please go through this https://github.com/google/mediapipe/blob/master/docs/getting_started/troubleshooting.md#missing-necessary-python-packages

**Comment by b4017816** [comment]
Hi thanks for taking a look at my issue, I tried the relevant solutions from the troubleshooting but it hasn't worked, 
Is there anything else I can try or check? 
Thanks
