### ISSUE TITLE
face landmark documentation

### ISSUE THREAD

**Issue by pkaske** [google/mediapipe#1815]
![image7](https://user-images.githubusercontent.com/70996435/112918562-c6522d80-90ca-11eb-8eb4-05246985a6aa.jpg)
![hand_landmarks](https://user-images.githubusercontent.com/70996435/112918577-c9e5b480-90ca-11eb-8ede-a76d2b58ef52.png)

is there any face landmark documentation that documents all the 468 face landmark points like these images do with the pose and hands?

**Comment by Choons** [comment]
I think this is the right one. zoom way in

https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_geometry/data
 
![canonical_face_model_uv_visualization](https://user-images.githubusercontent.com/16409313/112925728-eb996880-90d7-11eb-9937-1d6188ab6b59.png)

**Comment by pkaske** [comment]
> I think this is the right one. zoom way in
> 
> https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_geometry/data
> 
> canonical_face_model_uv_visualization.png
> 
> ![canonical_face_model_uv_visualization](https://user-images.githubusercontent.com/16409313/112925728-eb996880-90d7-11eb-9937-1d6188ab6b59.png)

thats it! thanks
