### ISSUE TITLE
face_mesh solution in google colab 

### ISSUE THREAD

**Issue by rachid-bousaid** [google/mediapipe#1819]
Hello
I use face_mesh solution in google colab , i hope i have the triangulation  and UV texture coordinates. Is it possible to do this in colab?

**Comment by sgowroji** [comment]
Hi @rachid-bousaid go through this issues #1698, #1155.

**Comment by rachid-bousaid** [comment]
which method allows to generate a mesh like this one in colab 
![image](https://user-images.githubusercontent.com/57646269/113172808-b197a600-9240-11eb-9422-33879acf5955.png)

**Comment by jiuqiant** [comment]
MediaPipe face mesh solution API outputs face landmarks. Our simple drawing util is for showing the users how to parse and use the output face landmarks. For your request , you need to follow https://github.com/google/mediapipe/issues/1698#issuecomment-794814532 to implement a custom drawing method.

**Comment by sgowroji** [comment]
Hi @rachid-bousaid, Did you get a chance to go through the above comment. Thanks!

**Comment by sgowroji** [comment]
Hi @rachid-bousaid, Could you please respond to the above comment.  Thanks!
