### ISSUE TITLE
can't open download link both hand tracking and 3d

### ISSUE THREAD

**Issue by 1Adamyan** [google/mediapipe#182]

**Comment by jiuqiant** [comment]
I just tried https://drive.google.com/file/d/1qUlTtH7Ydg-wl_H6VVL8vueu2UCTu37E/view and successfully dowloaded handdetectiongpu.apk. Could you retry? If there is still an error, could you provide us some error details? Thanks!

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
