### ISSUE TITLE
Can you do single image pose detection?

### ISSUE THREAD

**Issue by danj96dev** [google/mediapipe#1820]
The demo detects poses with an input-stream, could that be done with just individual frames and would it be significantly slower?
For example I get a frame->detects keypoints-> wait for my next image->detect keypoints->etc

**Comment by RobinDeBaets** [comment]
This is definitely possible, but you should check the `STATIC_IMAGE_MODE` option on the [wiki](https://google.github.io/mediapipe/solutions/pose.html). If your frames are completely independent, this option should definitely be enabled.
Unfortunately it is not available in the Javascript version.

**Comment by danj96dev** [comment]
> 
> 
> Hi @danj96dev Could you elaborate your use case with complete details. thanks!

I'm using the android example built with bazel, I wanted to do something similar except just use the processor to recognize a pose in a single image. I wanted this as an android library(aar) and to change the sdk version but I don't see where I can generate a custom app, there's only Mainactivity.java

https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu
I'm trying to modify this

**Comment by Abhinavkriti** [comment]
Hey everyone , i have decided to take part in gsoc and i am a beginner. I want to contribute in this project . can you please guid me ?

**Comment by sgowroji** [comment]
Steps you can follow this https://github.com/google/mediapipe/issues/1134. If you encounter any issue, Please share the logs and  with the following steps.

**Comment by sgowroji** [comment]
Hi @danj96dev, Did you get a chance to go through the above   https://github.com/google/mediapipe/issues/1820#issuecomment-814662436. Thanks!

**Comment by danj96dev** [comment]
> 
> 
> Hi @danj96dev, Did you get a chance to go through the above [#1820 (comment)](https://github.com/google/mediapipe/issues/1820#issuecomment-814662436). Thanks!

Hello, unfortunately the speed of detection isn't any faster than Google's MLkit so I'm not continuing with that, but the comment was helpful thank you.

**Comment by sgowroji** [comment]
Hi @danj96dev, We are sorry to hear it from you. Could you please mention your use case  and what delay you found while working with the above solution with complete details so that we can get it review from performance experts. And your feedback will really help us to improve our solutions better for future releases.

**Comment by danj96dev** [comment]
> 
> 
> Hi @danj96dev, We are sorry to hear it from you. Could you please mention your use case and what delay you found while working with the above solution with complete details so that we can get it review from performance experts. And your feedback will really help us to improve our solutions better for future releases.

There's nothing too interesting about it. Google MLkit pose recognition runs using only the cpu so I tried using the gpu delegate  here and the fps was basically the same, I didn't get any noticeable improvement.  I tested this on a Rockchip RK3288 so that might have been the issue.

**Comment by fanurs** [comment]
> This is definitely possible, but you should check the `STATIC_IMAGE_MODE` option on the [wiki](https://google.github.io/mediapipe/solutions/pose.html). If your frames are completely independent, this option should definitely be enabled. Unfortunately it is not available in the Javascript version.

Does anyone know if `static_image_mode` will be supported in JavaScript anytime soon in the future?

**Comment by jadams777** [comment]
+1

This would be very useful. 

> > This is definitely possible, but you should check the `STATIC_IMAGE_MODE` option on the [wiki](https://google.github.io/mediapipe/solutions/pose.html). If your frames are completely independent, this option should definitely be enabled. Unfortunately it is not available in the Javascript version.
> 
> Does anyone know if `static_image_mode` will be supported in JavaScript anytime soon in the future?
