### ISSUE TITLE
About the object 3D AAR black screen and then flash back

### ISSUE THREAD

**Issue by z7212819** [google/mediapipe#1821]
Hello, now my program has a black screen and then crashes. The following is my problem report：
![截图](https://user-images.githubusercontent.com/75053001/113085605-bfcecd80-9212-11eb-9a31-a446144daf13.png)
The following is my project file structure：
![截图2](https://user-images.githubusercontent.com/75053001/113085653-d1b07080-9212-11eb-81f0-efdff80ed20d.png)
I suspect it is the problem with the AndroidManifest.xml file, the following is my file code：
![截图3](https://user-images.githubusercontent.com/75053001/113085725-f0af0280-9212-11eb-8b3d-2b077d35f49f.png)
And after the 3D update of the object, I feel that many things have changed, which makes it impossible to patrol the AAR program normally. If this problem can be solved, I would be very grateful.

**Comment by z7212819** [comment]
In addition, the latest version of mediapipe I use

**Comment by sgowroji** [comment]
Hi @z7212819 , Can you share the complete crash report. And which step the issue is occurring . Thanks!

**Comment by z7212819** [comment]
> Hi @z7212819 , Can you share the complete crash report. And which step the issue is occurring . Thanks!

Thank you very much for replying to me, this is my complete report. The program crashed after I allowed the camera permission
[log.txt](https://github.com/google/mediapipe/files/6234181/log.txt)

**Comment by z7212819** [comment]
@sgowroji In addition, I also doubt whether it is the problem with the AAR file and the tflite file. Since the content of the internal frame has changed after the object 3D update, I also want to ask if you need to use the object 3D AAR package at present, you need What tflite file? Thank you!

**Comment by sgowroji** [comment]
Hi @z7212819  What solution are you trying?  Facemesh or other?

**Comment by z7212819** [comment]
@sgowroji hello, I'm trying a solution for object detection3d
