### ISSUE TITLE
mediapipe: js current version(31st march ) required minor fix.

### ISSUE THREAD

**Issue by vKrypto** [google/mediapipe#1823]
I can see lot of people facing this issue in recent release,

even mediapipe-dev demo also not working.
[https://mediapipe.dev/demo/hands](https://mediapipe.dev/demo/hands)

****actual problem is :**** 
a function defined in [hands_solution_wasm_bin.wasm](https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm) was remapped from 393919 to 401815.

but developers forget to remap it  in [hands_solution_wasm_bin.js](https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.js) file.
### 
**Simple Solution:**
 1) if you are using staged files( locally not from CDN), ignore this step,
     replace 
     _const hands = new Hands({locateFile: (file) => {
          return `https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`;
      }});_
    
     _const hands = new Hands({locateFile: (file) => {
          return `./mediapipe/hands/${file}`; //your own custom path.( download all 6 files, and serves from local.)
      }});_
          

 
 2) replace: **ASM_CONSTS={393919**  var **ASM_CONSTS={401815:** in file hands_solution_wasm_bin.js
 
 
 
###  
 **_I Hope mediapipe will fix this bug soon_**

**Comment by vKrypto** [comment]
@mhays-google  please let internal know about this.

**Comment by RobinDeBaets** [comment]
I'm having a similar issue with `@mediapipe/pose`, even after upgrading to the newly released `0.2.1617147663`:

```
core.js:6140 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'apply' of undefined
TypeError: Cannot read property 'apply' of undefined
    at _emscripten_asm_const_int (pose_solution_wasm_bin.js:9)
    at cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[7064]:0x31551c
    at cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[7063]:0x3152e2
    at cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[7062]:0x31517c
    at cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6531]:0x2e244a
    at cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6278]:0x2d2f82
    at cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6275]:0x2d1537
    at cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6273]:0x2d105c
    at cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[514]:0xe647
    at cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[501]:0xd67c
    at resolvePromise (zone-evergreen.js:1213)
    at zone-evergreen.js:1120
    at e (pose.js:22)
    at ZoneDelegate.invoke (zone-evergreen.js:372)
    at Object.onInvoke (core.js:28513)
    at ZoneDelegate.invoke (zone-evergreen.js:371)
    at Zone.run (zone-evergreen.js:134)
    at zone-evergreen.js:1276
    at ZoneDelegate.invokeTask (zone-evergreen.js:406)
    at Object.onInvokeTask (core.js:28500)
```

**Comment by RobinDeBaets** [comment]
Simple solution is to change Mediapipe's suggested code for loading in the files to this:

```javascript
this.model = new blazepose.Pose({
      locateFile: (file: string) => {
        return `https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.2.1614787780/${file}`;
      },
    });
```

This explicitly loads in the `.wasm` files from the previous version of `@mediapipe/pose`, which is not broken.

**Comment by vKrypto** [comment]
> Simple solution is to change Mediapipe's suggested code for loading in the files to this (notice the hardcoded version number):
> 
> ```js
> this.model = new blazepose.Pose({
>       locateFile: (file: string) => {
>         return `https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.2.1614787780/${file}`;
>       },
>     });
> ```
> 
> This explicitly loads in the `.wasm` files from the previous version of `@mediapipe/pose`, which is not broken.

but this will switch your code to an old version of media-pipe. for latest version find **var ASM_CONSTS={** in the corresponding js file, and remap it.

**Comment by RobinDeBaets** [comment]
> > Simple solution is to change Mediapipe's suggested code for loading in the files to this (notice the hardcoded version number):
> > ```js
> > this.model = new blazepose.Pose({
> >       locateFile: (file: string) => {
> >         return `https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.2.1614787780/${file}`;
> >       },
> >     });
> > ```
> > 
> > 
> > This explicitly loads in the `.wasm` files from the previous version of `@mediapipe/pose`, which is not broken.
> 
> but this will switch your code to an old version of media-pipe. for latest version find **var ASM_CONSTS={** in the corresponding js file, and remap it.

It will indeed use the older files, I presented it more as a temporary solution for userss whose application bricked overnight due to Google deploying the new files.

**Comment by sgowroji** [comment]
Hi @vKrypto , It's just a  caching issue. Working fine for all of us. We will let you know soon about it with any fix.

**Comment by sgowroji** [comment]
Hi @vKrypto, Could you please check the above issue as it is resolved.

**Comment by sgowroji** [comment]
As we see lack of activity on this ticket from the reporter. We are closing it. Thanks!
