### ISSUE TITLE
Does face geometry pipeline contain nonlinear deformation?

### ISSUE THREAD

**Issue by Zju-George** [google/mediapipe#1826]
I wonder, is the output of face_geometry pipeline only a rigid transformation of the canonical face mesh, or it contains nonlinear deformation such as mouse open-close, eye blink motion, etc?

Thanks in advance.

**Comment by sgowroji** [comment]
Hi @Zju-George ,  We have a very clear documentation for the face geometry [here](https://google.github.io/mediapipe/solutions/face_mesh#face-geometry-module)  . 
Please go through the inner links to understand more about the each and every concept which is required for you.

If you still not found any needed let  us know. Thanks!

**Comment by sgowroji** [comment]
I think your query answered here https://github.com/google/mediapipe/issues/1678#issuecomment-811262438. Closing this  as per the comment.
