### ISSUE TITLE
What would be the best way to do posture feedback?

### ISSUE THREAD

**Issue by airtablereddit** [google/mediapipe#1827]
Hi @sgowroji 

What would be the best way to do realtime Posture feedback in python and android in Mediapipe Pose tracking with Blazepose?

@kostyaby your input also please

**Comment by sgowroji** [comment]
Hi @airtablereddit Could you please explain your usecase with more details. Thanks!

**Comment by airtablereddit** [comment]
Sure, I know we can count reps thanks to the code provided media pipe team, now I am interested to find out how to get real time posture feedback, lets say doing Push up exercise you open your elbows really wide which is a wrong posture, how you would go about calculating the angles and match them real time with the correct angles of the correct form

![image](https://user-images.githubusercontent.com/80802300/113275786-97b99a00-92f8-11eb-9de6-e7284af1ae05.png)


![image](https://user-images.githubusercontent.com/80802300/113275831-a3a55c00-92f8-11eb-8ac4-aa5dc0a1bf1d.png)

**Comment by airtablereddit** [comment]
More specifically how can I calculate the [simple joint pairwise distance lookup algorithm as specified here](https://ai.googleblog.com/2020/08/on-device-real-time-body-pose-tracking.html)

**Comment by airtablereddit** [comment]
@sgowroji appreciate your reply to this. I added more explanation

**Comment by kostyaby** [comment]
@ivan-grishchenko would be the best person to comment

**Comment by ivan-grishchenko** [comment]
Hi. We recently updated pose model to include output with world 3D landmarks. 3D landmarks are much more suitable for your task as they don't have perspective distortion as 2D landmarks and you can calculate real angles in 3D.

You can start by looking at the [API](https://google.github.io/mediapipe/solutions/pose#pose_world_landmarks) and at the [blog post](https://blog.tensorflow.org/2021/08/3d-pose-detection-with-mediapipe-blazepose-ghum-tfjs.html).
