### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'apply' of undefined in JS on Mac OS

### ISSUE THREAD

**Issue by Creativeguru97** [google/mediapipe#1828]
I've been using Hands of MediaPipe in JavaScript on Mac OS.
I combined mediapipe hands with p5.js to apply Creative Coding. Like detect my hands and give the coordinates to p5.js then draw something y p5.

But this morning(April 4, 2021), I suddenly got this error below and it doesn't work. Even though until yesterday it had no problem.

Even when I run the example code of hands on [Hands page](https://google.github.io/mediapipe/solutions/hands.html), it gives the same error.

`Uncaught (in promise) TypeError: Cannot read property 'apply' of undefined
    at _emscripten_asm_const_int (cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.js:9)
    at cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[7211]:0x3098a5
    at cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[7210]:0x3096b6
    at cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[7209]:0x309630
    at cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[6696]:0x2d9c16
    at cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[6443]:0x2cac55
    at cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[6440]:0x2c9288
    at cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[6438]:0x2c8ea7
    at cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[514]:0xe860
    at cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[501]:0xd895`

The code still work on my another windows pc, so I assume it's about my local environment.
But it seems the solution is depend on situation, and I'm noob around this sort of stuff.
Anybody got happened this and solved?

my code: https://github.com/Creativeguru97/YouTube_tutorial/tree/master/Play_with_APIs/hand_detection/mediapipe_hands/final

If this question is lack of information, please point out.

**Comment by tyrmullen** [comment]
I just tried the Hands CodePen on a MacBookPro, and it seemed to work just fine for me.  Perhaps the issue has already been resolved?  Or perhaps your browser is caching something stale-- try loading up the [MediaPipe JS Hands CodePen](https://codepen.io/mediapipe/pen/RwGWYJw) while the Chrome Developer Console is open (and the "disable cache" box is checked, under "Networking"), and seeing if that works for you.

**Comment by sgowroji** [comment]
Hi @Creativeguru97, Could you please try the fix mentioned in the above comment. Thanks

**Comment by tyrmullen** [comment]
This does sound like possibly a caching issue.  Or perhaps an asset fetching problem (you'd be able to see in your "Network" tab that files aren't loading if that's the case).  So in addition to the trick for disabling browser caching I mentioned above, here are some other things to potentially try, depending on where you're running the code:

- CodePen caching: if you're running on the CodePen, then try adding "?something=randomstringofletters" to the end of the URL to prevent caching... or better yet, just run the MediaPipe Hands demo [directly](https://mediapipe.dev/demo/hands), so you don't have to worry about CodePen caching at all (disabling browser caching is still recommended, as explained in my previous comment).

- You may be selecting the wrong version of the JS API from jsdelivr:
Actually, in your stack trace above, I see "cdn.jsdelivr.net/npm/@mediapipe/hands/...", but I think you want something like "cdn.jsdelivr.net/npm/@mediapipe/hands@0.3/...".  This will tell jsdelivr to give you some version of the API which is 0.3.x (it will decide what the x should be).  So far we have 0.1.x, 0.2.x, and 0.3.x, but this will continue to increase over time with new versions/fixes/features.

- Jsdelivr may be sending you an older version:
  Above I mention that if you ask for hands@0.3, jsdelivr will decide what version to give you which matches 0.3.x.  This is something we'll be fixing shortly (we should set it to always deliver the newest version which matches 0.3.x instead).  But to be totally sure you're testing against a specific version (perhaps the newest one), you can look up the full triplet (x.y.z) of the version you want (you can find these triplets [here](https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.3/) for hands@0.3). Then specify that instead, like "hands@0.3.1620248595" (the most recent as of this post).

Closing as fixed for now, but if none of the above fixes your issue, then please reopen!
