### ISSUE TITLE
Mediapipe 0.8.3.1 dose not run on GPU

### ISSUE THREAD

**Issue by abzargar** [google/mediapipe#1829]
I installed Mediapipe 0.8.3.1 through "pip install mediapipe==0.8.3.1" but it only works with CPU and cannot run on GPU. Could you please let me know how to run it on GPU as well.

**Comment by sgowroji** [comment]
Hi @abzargar, Could you please elaborate the issue with complete details. What error your facing and what steps you followed. Thanks!

**Comment by jiuqiant** [comment]
This is intended. MediaPipe Python package only contains CPU graphs. If you need to run any GPU graphs, see https://github.com/google/mediapipe/issues/1651#issuecomment-790176010.

**Comment by abzargar** [comment]
Thank you for your reply. I went over #1651 but I could not understand how
to add GPU graph and modifications to python package after installing it
using "pip install mediapipe". Any step by step instruction?

Thank for your time
