### ISSUE TITLE
Export keypoint data (x,y) coordinates from Holistic  MediaPipe Pose Python to csv file 

### ISSUE THREAD

**Issue by SayedHamdiF** [google/mediapipe#1830]
i want to save all keypoints coordinates of holistic model from mediapipe to csv file

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/1803

**Comment by vandics** [comment]
Hello, you could use code here  https://pastebin.com/BA4E1fAF. The output will save on .xlsx format instead of .csv but you could change it to .csv

**Comment by jiuqiant** [comment]
Thanks  @vandics for providing a solution. Closing this issue now.
