### ISSUE TITLE
MediaPipe dose not run on GPU after installing it using "pip install mediapipe"

### ISSUE THREAD

**Issue by abzargar** [google/mediapipe#1831]
I looked over #1651 but I could not understand how to add GPU graph and modifications to the python package after installing it using "pip install mediapipe". Any step-by-step instruction?

**Comment by Abhinavkriti** [comment]
yeah facing the same issue

**Comment by jiuqiant** [comment]
MediaPipe GPU support on macOS and Windows are not released yet. To keep the wheel pakcages on linux, macos,and windows in sync, MediaPipe only have CPU graphs in the wheel packages. You can follow https://github.com/google/mediapipe/issues/1651#issuecomment-790176010 to run the GPU graphs. Sorry for the inconvenience.
