### ISSUE TITLE
BlazePose 3D rig

### ISSUE THREAD

**Issue by jadams777** [google/mediapipe#1832]
ARkit comes with a robot rig that can be used for animating 3D characters, real-time motion capture, etc. For example: https://youtu.be/29uNziYYZZ0

Does BlazePose have a rig? If not, how can I make one?

**Comment by sgowroji** [comment]
MediaPipe has limited resources for new features. While this is a good idea, we don't foresee any debo area. We will let you know if there is any update specific to it.
