### ISSUE TITLE
how to create *.obj and *.png that relation with *.obj?

### ISSUE THREAD

**Issue by bugmany** [google/mediapipe#1833]
i have run face effect demo , it use OBJ file "canonical_face_model.obj", the demo effect is very well, 
but i have use Blender IDE create face model file (*.obj), then integrate the OBJ file into face effect project, the result is too bad not our expect's effect,
so could you tell me how to create OBJ file and PNG(pngblob), or tell me use what is develop studio (IDE)?

**Comment by rmothukuru** [comment]
@bugmany,
Can you please let us know the Solution and the platform you are using? Thanks!

**Comment by bugmany** [comment]
hi @rmothukuru, i run face effect on the platform Android and IOS.
thanks.

**Comment by bugmany** [comment]
hi @rmothukuru, maybe the issue is not resources files.
