### ISSUE TITLE
Add GPU graphs to python version to install it using pip

### ISSUE THREAD

**Issue by abzargar** [google/mediapipe#1834]
Hi

Could you please add GPU graphs as well to the python package on pypi.org to install it using "pip install mediapipe" and so run it on GPU in an anaconda environment?

thank you

**Comment by jiuqiant** [comment]
MediaPipe GPU support on macOS and Windows are not released yet. To keep the wheel pakcages on linux, macos,and windows in sync, MediaPipe only have CPU graphs in the wheel packages. You can follow https://github.com/google/mediapipe/issues/1651#issuecomment-790176010 to run the GPU graphs. Sorry for the inconvenience.
