### ISSUE TITLE
Javascript face effects example on Mobile, but not Desktop

### ISSUE THREAD

**Issue by DStoke** [google/mediapipe#1837]
Hello,

Are there any face effect examples for desktop that would be built with JavaScript? 

As of now, for desktop i only see Python/C++ examples, while on mobile there's JS example available.

**Comment by rmothukuru** [comment]
@DStoke,
Can you please share the references of the examples which you are specifying so that we can look into it? Thanks!

**Comment by sgowroji** [comment]
Hi @DStoke, Thanks for reaching us regarding your query. We have a very clear [documentation](https://google.github.io/mediapipe/getting_started/javascript.html).

**Comment by sgowroji** [comment]
We are closing this issue as we see lack of activity.
