### ISSUE TITLE
Use mediapipe in react Native?

### ISSUE THREAD

**Issue by jude253** [google/mediapipe#1838]
Hi,

I am working on a project right now using react-native.  I am doing lots of pose estimation.  I am wondering if it is possible to use mediapipe with react-native.  

Currently, I am using tflite poseNet in react native. I would like to use mediapipe though because it gives more pose information that will be very useful to us. 

So is it possible to import mediapipe into react native through like an npm package, and if so, is there some example I can follow?

Also I think that it is probably possible to import the ios mediapipe package into the ios part and mediapipe android package into the android part of the react native project, but I want to avoid this if possible.

I am new to using react native and I am having lots of difficulties getting project dependencies working together nicely, so a simple working example would be super super helpful.  Any help or recommendations is much appreciated.

All the best,
Jude253

**Comment by sgowroji** [comment]
Hi @jude253, Have a look over here https://github.com/google/mediapipe/issues/587#issuecomment-610585088

**Comment by sgowroji** [comment]
Hi @jude253, did you get a chance to look the above comment. Thanks!

**Comment by sgowroji** [comment]
As we see lack of activity on this issue we are closing it. Please feel free to reopen if it still exists. Thanks!

**Comment by farshid1** [comment]
@sgowroji so if I understood correctly, you are proposing that one should develop the feature in iOS and Android and import them into the RN project? Thanks for clarification

**Comment by philiprkk** [comment]
Hello! Any progress with this?

**Comment by coucoseth** [comment]
A request to create a react native package for the library

**Comment by akashkrshukla** [comment]
I am open to work on creating package for react-native. Open for suggestions.

**Comment by wired87** [comment]
> I am open to work on creating package for react-native. Open for suggestions.

Yeah lets do that! Open a repo and write me on discord:__wired__.

**Comment by radzio216** [comment]
Hey, has there been any news on this topic? Let me know if there is any react native implementation for Media Pipe or TF lite with Pose Detector model please 🙏
