### ISSUE TITLE
Cannot generate xcode project

### ISSUE THREAD

**Issue by HebaMohamed** [google/mediapipe#184]
I followed the instructions step by step but still unable to generate the xcode project with tulsi
This is the error I got each time I press "generate" with tulsi, any help please ?

`ERROR: /Users/hebamohamed/mediapipe/mediapipe/examples/ios/edgedetectiongpu/BUILD:24:1: in ios_application rule //mediapipe/examples/ios/edgedetectiongpu:EdgeDetectionGpuApp: Traceback (most recent call last):
	File "/Users/hebamohamed/mediapipe/mediapipe/examples/ios/edgedetectiongpu/BUILD", line 24
		ios_application(name = 'EdgeDetectionGpuApp')
	File "/private/var/tmp/_bazel_hebamohamed/90e5d7c4bc9f07629d7207ff133da7c0/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 160, in _ios_application_impl
		run_support.register_simulator_executable(ctx, executable)
	File "/private/var/tmp/_bazel_hebamohamed/90e5d7c4bc9f07629d7207ff133da7c0/external/build_bazel_rules_apple/apple/internal/run_support.bzl", line 28, in run_support.register_simulator_executable
		ctx.actions.expand_template(output = output, is_executable = T..., <2 more arguments>)
	File "/private/var/tmp/_bazel_hebamohamed/90e5d7c4bc9f07629d7207ff133da7c0/external/build_bazel_rules_apple/apple/internal/run_support.bzl", line 36, in ctx.actions.expand_template
		shell.quote(ctx.fragments.objc.ios_simulator...)
	File "/private/var/tmp/_bazel_hebamohamed/90e5d7c4bc9f07629d7207ff133da7c0/external/bazel_skylib/lib/shell.bzl", line 49, in shell.quote
		s.replace("'", "'\\''")
type 'NoneType' has no method replace()
ERROR: Analysis of aspect '@tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect of //mediapipe/examples/ios/edgedetectiongpu:EdgeDetectionGpuApp' failed; build aborted: Analysis of target '//mediapipe/examples/ios/edgedetectiongpu:EdgeDetectionGpuApp' failed; build aborted
General failure: Bazel aspects could not be built.`

**Comment by chad-green** [comment]
I'm stuck here as well. Initially, I was getting the same error when trying to build tulsi, but I made the changes to my WORKSPACE as recommended here:
https://github.com/bazelbuild/tulsi/pull/106/commits/aa98d4ca71281448cdb6878631ebdedc7813d2cc
Now tulsi is up and running, but hitting "generate" creates the same error as above.

**Comment by HebaMohamed** [comment]
Hello team @mgyong @camillol @jiuqiant 
Any updates on that issue please? Im really stuck here for a long time :(

Thanks in advance all

**Comment by lvkleist** [comment]
I also have the same issue.

**Comment by jiuqiant** [comment]
See https://github.com/google/mediapipe/issues/187#issuecomment-544723390

**Comment by HebaMohamed** [comment]
> See [#187 (comment)](https://github.com/google/mediapipe/issues/187#issuecomment-544723390)

Solved! thank you so much 🙏

**Comment by chad-green** [comment]
This may be a better solution. Instead of downgrading Bazel, you can update your apple rules in your mediapipe WORKSPACE file.  Apple has changed things recently and does not accept release tags anymore (see the comments at the top of their README). They want you to use a commit.  I changed my rules to match what's in the master repository for the iOS hello world example and that has worked well for Bazel 1.0.0.
https://github.com/bazelbuild/examples/blob/master/tutorial/WORKSPACE
