### ISSUE TITLE
Is it possible build under Mingw or Msys2?

### ISSUE THREAD

**Issue by 424778940z** [google/mediapipe#1844]
I'm trying to get GPU working under windows, I know someone has tried to mod files to add egl and replace pthread to get it working under VC.
I'm wondering if it's possible just build under Msys2 or at least able to use Mingw, since they already have all libraries.

**Comment by rmothukuru** [comment]
@424778940z,
Can you please elaborate more about your point. Please let us know the Solution and the Platform that you are using. Also, if possible, please share the reproducible code. Thanks!

**Comment by 424778940z** [comment]
Currently Mediapipe using VC, and there is no other option for building under Windows.
I'm trying get GPU support working on Windows since it's currently not supported, and may not be officially supported for a long time.
According to #617, seems he got it working by replace pthread with std::thread, then add GL headers.
I was hoping to build under Msys2 since Mingw under it already has pthread and GL headers.

**Comment by sgowroji** [comment]
Hi @424778940z, We have clear and complete documentation [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows)

**Comment by 424778940z** [comment]
> Hi @424778940z, We have clear and complete documentation [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows)

My question is if it's possible to build with mingw, the document still build with MSVC.

**Comment by jiuqiant** [comment]
According to https://docs.bazel.build/versions/master/install-windows.html, MSYS2 and MSVC are required. It explicitly says that you will need "Build Tools for Visual Studio" to build C++ code on Windows. So, the answer to your question is likely to be no.
