### ISSUE TITLE
Generate aar error run apk

### ISSUE THREAD

**Issue by nailshakurov** [google/mediapipe#1845]
I generated a file successfully, run the example from the database and use aar. At startup, the error is:
![image](https://user-images.githubusercontent.com/11345578/113576369-83470b80-9630-11eb-936b-cb53f8d8a906.png)

**Comment by rmothukuru** [comment]
@nailshakurov,
Can you please provide the steps to reproduce the issue? Thanks!

**Comment by sgowroji** [comment]
We are closing this issue as we see lack of activity. Thanks!
