### ISSUE TITLE
Is the VectorFloatToTensorCalculator calulcator available in Mediapipe graphs for Python? 

### ISSUE THREAD

**Issue by aylek** [google/mediapipe#1846]
Including the calculator in a graph results in the following error when run with the Mediapipe Python module:

```
RuntimeError: ValidatedGraphConfig Initialization failed.
No registered object with name: VectorFloatToTensorCalculator; Unable to find Calculator "VectorFloatToTensorCalculator"
```

What I'm trying to do is to read a list of floats from a file to serve as an input tensor (regressions and classifications) to the TensorsToDetections calculator.

**Comment by sgowroji** [comment]
Hi @aylek, Could you please provide complete details regarding above issue. Thanks!

**Comment by sgowroji** [comment]
Hi @aylek, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
Due to lack of activity on this issue. We are closing this ticket.
