### ISSUE TITLE
print out certain face_landmarks in google colab python holistic

### ISSUE THREAD

**Issue by pkaske** [google/mediapipe#1848]
i know 
f'{results.face_landmarks})' or f'{results.face_landmarks.landmark})'
prints out all 468 face landmarks. but what is the notation to only print out, say, the 30th face landmark only? (all 3 coordinates x,y,z)

**Comment by sgowroji** [comment]
Hi @pkaske, Could you please explain your usecase. We can get individual landmarks of the face, pose landmarks using the result object. Like this results.face_landmarks, results.pose_landmarks.

**Comment by pkaske** [comment]
> Hi @pkaske, Could you please explain your usecase. We can get individual landmarks of the face, pose landmarks using the result object. Like this results.face_landmarks, results.pose_landmarks.

yes, i've been doing that
an example of my code would be

 str(results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HIP].x)+","+str(results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_HIP].y)+","+
 
 what im doing is getting the x,y, and z landmarks printed separately, and only of the LEFT HIP. i want to do something similar with the face landmarks. but i cant find a way to do that

**Comment by pkaske** [comment]
nevermind, figured it out myself

**Comment by realAnish9** [comment]
> nevermind, figured it out myself

How??
