### ISSUE TITLE
How to drawing android view?

### ISSUE THREAD

**Issue by LeeJeongHwi** [google/mediapipe#1849]
Hi!
First of all, thank you for suggesting a really nice solution.
I have a question about android view.

I want to make a custom view on Android. For example, I would like to draw with custom, like marking a particular part with a red line in the pose.
So I want to know when it will be displayed on the Android screen. When the processor (FrameProcessor) receives the packet, does the rendering picture appear on the screen after executing the callback function?

Thank you!

**Comment by sgowroji** [comment]
Hi @LeeJeongHwi , This will help your query https://github.com/google/mediapipe/issues/1668#issuecomment-807851974

**Comment by LeeJeongHwi** [comment]
thank you for response,

that comment says, 

""the SurfaceOutput object named videoSurfaceOutput is updated by the code defined in Graph.java here. 
so you need to pipe your rendered frame to the videoSurfaceOutput used in the display.""

so, I need to setting custom `SurfaceOutput` and then `processor.getVideoSurfaceOutput.setSurface(custom_SurfaceOutput)` ??
Also, should I update this frame within addPacketCallback?

Thank you.

**Comment by shadow111** [comment]
Hello @LeeJeongHwi  i opened the same issue [here](https://github.com/google/mediapipe/issues/1668)  i still cannot solve it, i want to draw the detected key points or objects in the android view, if you have some useful code can you share it please, there is a lot of people here that are asking for the same things so if we can solve it , it will help the community a lot
Thanks in advance .

**Comment by badushaebrahim** [comment]
hai guys have u been able to get build a stuck at sync can you guys help

**Comment by eknight7** [comment]
Adding @suril for the Android view rendering questions here.

**Comment by eknight7** [comment]
> hai guys have u been able to get build a stuck at sync can you guys help

Hi @badushaebrahim, please open a separate issue to track for the build, thank you.  Please share more details about what is breaking there, thanks.

**Comment by suril** [comment]
Hi @LeeJeongHwi , if I understood your question correctly, there are 2 parts to it:
(1) You'd like a callback when a frame is done processing through MediaPipe and final output is rendered.
(2) You'd like to overlay some custom drawing on top of rendered preview based on the detected keypoints on the frame.

For (1), you can refer to https://github.com/google/mediapipe/issues/349#issuecomment-572928170 for how you can receive the callback for each frame with the detection results.

For (2), you can create your own custom View that overlays exactly on top of the view that MediaPipe renders its output to. You can add a method to your custom View class i.e. setDetectionResult(..) which you can call whenever you receive a callback as per (1) with the latest results. You can implement your custom drawing logic in the [onDraw(..)](https://developer.android.com/reference/android/view/View#onDraw(android.graphics.Canvas)) method of your custom View and you can call [postInvalidate()](https://developer.android.com/reference/android/view/View#postInvalidate()) to trigger the onDraw() call as well for each callback in (1).

Please feel free to reopen if my understanding of your question was incorrect or you need help further clarifying the solution.
