### ISSUE TITLE
run hand tracking example in ubuntu 18.04

### ISSUE THREAD

**Issue by davidakr** [google/mediapipe#185]
Hi,

I was successfully running the example for hand tracking on desktop using on ubuntu 16.04. I upgraded to 18.04 and the build still succeeds.
When I try to run: 

bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu \
    --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt

the following error message shows up:

bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu: error while loading shared libraries: libavcodec-ffmpeg.so.56: cannot open shared object file: No such file or directory

The file is now libavcodec-ffmpeg.so.57. What do I need to change to run it?

**Comment by jiuqiant** [comment]
It seems like the system upgrade did to the ffmpeg libraries. Can you clean the cache and rebuild the binary to see if that works?

Try
```
$ bazel clean --expunge
$ bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS \
    mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
```

**Comment by davidakr** [comment]
yes cleaning the cache helped. Thank you!
