### ISSUE TITLE
.bazelversion should be relaxed (only accepts bazel 3.7.2)

### ISSUE THREAD

**Issue by brgl** [google/mediapipe#1850]
Current bazel version is 4.0.0 and it works fine for mediapipe. The `.bazelversion` however specifies 3.7.2 as the only accepted version.  This should be relaxed to accept any later version.

**Comment by sgowroji** [comment]
Hi @brgl Could you please elaborate the above query with complete details. Thanks!

**Comment by brgl** [comment]
Hi @sgowroji there's not much more detail over what I already posted really. Mediapipe builds with bazel `3.7.2` exclusively and fails with bazel `4.0.0` in `setup.py`:

```
 86   try:
 87     bazel_version_info = subprocess.check_output(['bazel', '--version'])
 88   except subprocess.CalledProcessError:
 89     sys.stderr.write('fail to get bazel version by $ bazel --version.')
```

Line 87 raises an Exception because the bazel program reads `.bazelfile` and bails out because it's not 3.7.2 and so `setup.py` fails here.

The error message is confusing too in this case. I would normally submit a patch changing the `.bazelfile` to something like `3.7.2 <` or whatever the syntax is but I have no idea what's up with the git history of mediapipe being just some imports. I guess it's google stuff. :man_shrugging:

**Comment by brgl** [comment]
@sgowroji sorry I used the name `.bazelfile`, it should have been `.bazelversion`. I fixed it now in the description.

**Comment by sgowroji** [comment]
Glad your resolved. Closing this issue now. Thanks!
