### ISSUE TITLE
extract Hair segementation mask

### ISSUE THREAD

**Issue by zhaoqilong3031** [google/mediapipe#1853]
my android code
`processor.addPacketCallback(
                "hair_mask",
                (packet) -> {
                    try {
                        byte[] landmarksRaw = PacketGetter.getProtoBytes(packet);
                    } catch (Exception e) {
                        Log.e(TAG, "Couldn't Exception received - " , e);
                    }
                });`

app exit，
What should I do?

**Comment by sgowroji** [comment]
Hi @zhaoqilong3031, Please share your error logs. And also the code repo to understand it much better. Thanks!

**Comment by zhaoqilong3031** [comment]
android log 
`Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9920 (Thread-9), pid 9764 (acedetectionapp)`
[link](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hair_segmentation/hair_segmentation_desktop_live.pbtxt#L128)
Can I get the mask through this “output_stream: "MASK:hair_mask"”

**Comment by sgowroji** [comment]
Duplicate issue https://github.com/google/mediapipe/issues/18

**Comment by ZhAnGeek** [comment]
I have a same problem but related to my customized data
04-12 23:19:20.106 30201 30267 W MainActivity: Received anchor packet
04-12 23:19:20.108 30201 30267 E libc++abi: terminating with uncaught exception of type absl::lts_2020_09_23::BadStatusOrAccess: Bad StatusOr access
--------- beginning of crash
04-12 23:19:20.108 30201 30267 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 30267 (Thread-5), pid 30201 (tmotiontracking)

**Comment by zhaoqilong3031** [comment]
node {
   calculator: "GpuBufferToImageFrameCalculator"
   input_stream: "hair_mask"
   output_stream: "hair_mask_cpu"
}

**Comment by arijith96** [comment]
Hi @zhaoqilong3031 
Could you please elaborate more on your commend and how you resolved it? What went wrong in your approach?

Thanks in advance :)
