### ISSUE TITLE
How to modify geometry_pipeline_metadata_landmarks

### ISSUE THREAD

**Issue by milad-4274** [google/mediapipe#1854]
Hello and Thanks for your awesome framework.
I want to render different 3D effects. with mediapipe default configuration, effects which depend on eye position(such as eyelash) don't have good result. I updated [single_face_geometry_from_landmarks_gpu](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_effect/subgraphs/single_face_geometry_from_landmarks_gpu.pbtxt) subgraph to use updated iris landmarks for better accuracy around eyes. 
after some tries I found out that the graph use geometry_pipeline_metadata_landmarks file for building face_geometry. in this file there are some weights for specific landmark IDs. I plotted these landmarks to canonical face and this is result (black dots show mentioned landmarks):
![canonical_face_model_uv_visualization](https://user-images.githubusercontent.com/48384506/113843509-dfcd3680-97a8-11eb-8fd5-e16bf48a113b.png)

1. It seems sum of all weights should be one(is it true?). 
 
I added weights to landmarks around eye and got a bit better result(not satisfying). 
   2. I want to know how can I systematically generate [geometry_pipeline_metadata_landmarks.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt) for getting better result for eye based effects?

3. Did I choose right approach for mentioned problem?

**Comment by kostyaby** [comment]
Hey @milad-4274,

> It seems sum of all weights should be one(is it true?).

Actually, I don't think those weights add up to 1. When I was creating the weights, my objective was to make sure that the weighted center of mass is close to the center of mass for the entire face model (468 vertices), but only relies on "stable" landmarks (ones that are harder to change with mimics and one can only change them with head movement). The reason why getting the weighted center of mass right is important comes from the [Procrustes Solver](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/libs/procrustes_solver.h) algorithm we use to extract a single head pose transform matrix from face mesh vertices.

> I want to know how can I systematically generate geometry_pipeline_metadata_landmarks.pbtxt for getting better result for eye based effects?

I should mention that `geometry_pipeline_metadata_landmarks.pbtxt` itself is not generated through some well-understood procedure, but rather through an iterative trial-and-error approach. Ideally, I don't feel like changing `geometry_pipeline_metadata_landmarks` is what should be happening per-effect. A similar logic runs inside Google products driving hundreds of different AR effects and we never updated its config better suit a single effect. Which leads me to your next question...

> Did I choose right approach for mentioned problem?

If we are talking about AR eyelashes, then I don't think that having a single 3D transform is good enough to make such effect happen. What you probably want is a combination of (A) a single 3D head pose transform, (B) face mesh and (C) a rigged 3D eyelashes model

First, I'd create a rigged 3D eyelashes model where each column is attached to a bone, which in turn uses a corresponding eye landmark's XYZ positing as the bone position. In other words, you'll have a single bone per each eye landmark and that bone will be responsible for moving a segment of eyelashes up/down. When rendering each frame, you'd update the positions of those bones with runtime face mesh positions + use the head pose transform to align the 3D model with the face in the scene. If done correctly, there'll be no gaps between the eye contour & AR eyelashes. This is definitely not the easiest AR effect to implement, but hopefully this description can help you out if that's what you want to build :)

Having said that, `FaceGeometryEffectRendererCalculator` is totally missing critical features to make such rendering possible, so please consider just surfacing `FaceGeometry` data to the app level and then use some other rendering library to enable this effect (if you are seeking cross-platform solution, [Filament](https://github.com/google/filament) is a great choice; it already comes with `gltf-io` library that'd simplify your 3D asset loading / handling routine) 

Please, let me know if you have any questions!

**Comment by milad-4274** [comment]
thank you for awesome reply and guidance. It seems not straightforward. I close this issue for now.
