### ISSUE TITLE
Using video as input for Object Detection on mobile device.

### ISSUE THREAD

**Issue by 04633435** [google/mediapipe#1855]
Hi there, I am working with the object detection Android example, which uses the camera stream as input.
Is there any way that I can use the video as input instead of the Camera stream?

I really appreciate any help you can provide.

**Comment by sgowroji** [comment]
Hi @04633435, Please go through this https://github.com/google/mediapipe/issues/597#issuecomment-611905236, you will have an idea how doing the above.  But not for the same solution, you are looking for. We dont have examples as of now. Please try at your end and let us know if you have any queries.

**Comment by 04633435** [comment]
> Hi @04633435, Please go through this [#597 (comment)](https://github.com/google/mediapipe/issues/597#issuecomment-611905236), you will have an idea how doing the above. But not for the same solution, you are looking for. We dont have examples as of now. Please try at your end and let us know if you have any queries.

Thank you for your surpport@sgowroji. I'll look it up!

**Comment by sgowroji** [comment]
We are closing this issue now. Please feel free to reopen if you still blocked. Thanks!
