### ISSUE TITLE
How to track selected object

### ISSUE THREAD

**Issue by ZacharyTech** [google/mediapipe#1856]
Hello, I want to track the selected object on Android, such as 
[YouTube’s privacy blur](https://2.bp.blogspot.com/-joxj5pCwT-U/Vs5aL-KIpgI/AAAAAAAABsw/8L64dzBc0Ak/s1600/vid_5.gif), how can I To it?

**Comment by sgowroji** [comment]
Hi @ZacharyTech, We have very clear documentation here for your above requirement. Please go through [this](https://google.github.io/mediapipe/solutions/instant_motion_tracking.html#mediapipe-instant-motion-tracking)

**Comment by ZacharyTech** [comment]
Okay, let me check this example first. thank

**Comment by sgowroji** [comment]
We are closing this issue now. Feel free to reopen if your above query is not resolved. Thanks!
