### ISSUE TITLE
How to visualize optical flow?

### ISSUE THREAD

**Issue by KastusKalinovski** [google/mediapipe#1857]
Hello, I am struggling with optical flow visualization.
I am tying to reproduce this visualization.
![Screenshot from 2021-04-07 16-16-22](https://user-images.githubusercontent.com/41323462/113872543-a56d9480-97bc-11eb-88a3-747efb99acba.png)
Can you please share what graph did you use to create this tracking?

**Comment by sgowroji** [comment]
Hi @KastusKalinovski, Could you please elaborate your usecase with clear details. And we have very clear documentation with  different [solutions](https://google.github.io/mediapipe/solutions/solutions.html). And please let us know which solution are you referring to.

**Comment by KastusKalinovski** [comment]
Hi @sgowroji, thank you for your response. I have a fixed camera and some object moving from frame to frame. My task is to detect this movement and track it with a bounding box. Now I am looking towards your [box-tracking solution](https://developers.googleblog.com/2019/12/object-detection-and-tracking-using-mediapipe.html), and I am trying to reproduce motion detection part.
![Screenshot from 2021-04-08 14-21-24](https://user-images.githubusercontent.com/41323462/114023069-196e7200-987b-11eb-9c8d-813e65267692.png)

**Comment by KastusKalinovski** [comment]
Firstly, I am trying to visualize optical flow(see attached graph).
![Screenshot from 2021-04-08 14-11-09](https://user-images.githubusercontent.com/41323462/114017141-5420dc00-9874-11eb-92c9-0c1071e57122.png)
I get the following error: `Input stream "optical_flow" of calculator "[FlowToImageCalculator, input stream: optical_flow, and output stream: output_video]" expects packets of type "mediapipe::OpticalFlowField" but the connected output stream will contain packets of type "mediapipe::RegionFlowFeatureList"`

**Comment by yegenzhi** [comment]
Hi, @KastusKalinovski you may want to introduce the input image to BoxTrackerCalculator as an input stream and set the following boolean to true in the BoxTrackerCalculatorOptions. Then you can obtain an output stream of the annotated image.

visualize_tracking_data: false
visualize_state: true
visualize_internal_state: true

**Comment by sgowroji** [comment]
Hi @KastusKalinovski, Did you get a chance to go through the above comment. Thanks!

**Comment by KastusKalinovski** [comment]
Hello, @yegenzhi, thank you for your response. I've tried following graph:
![Screenshot from 2021-04-12 13-34-15](https://user-images.githubusercontent.com/41323462/114381503-dc182600-9b93-11eb-9f76-80891b0264ca.png)
Here is my code:
```cpp
input_stream: "VIDEO:input_video"
output_stream: "VIDEO:output_video"


node: {
  calculator: "BoxTrackerCalculator"
  input_stream: "VIDEO:input_video"
  input_stream: "TRACKING:input_video"
  output_stream: "VIZ:output_video"



  node_options: {
    [type.googleapis.com/mediapipe.BoxTrackerCalculatorOptions]: {
      tracker_options: {
        track_step_options {
          track_object_and_camera: true
          tracking_degrees: TRACKING_DEGREE_OBJECT_SCALE
          inlier_spring_force: 0.0
          static_motion_temporal_ratio: 3e-2
        }
      }
        visualize_tracking_data: true
        visualize_state: true
        visualize_internal_state: true
      streaming_track_data_cache_size: 100
    }
  }
}
```
I get the following error : `Failed to run the graph: Input stream "input_video" of calculator "[BoxTrackerCalculator, input streams: <VIDEO:input_video,TRACKING:input_video>, and output stream: VIZ:output_video]" expects packets of type "mediapipe::ImageFrame" but the connected output stream will contain packets of type "[Same Type As mediapipe::TrackingData]"`

**Comment by KastusKalinovski** [comment]
I've also tried this combined graph, with visualization booleans enabled, but it just returns the input video without any visualization.
![Screenshot from 2021-04-12 13-45-01](https://user-images.githubusercontent.com/41323462/114382678-4ed5d100-9b95-11eb-9d1d-8a6021e47493.png)
Code: 
```cpp
input_stream: "VIDEO:input_video"
output_stream: "VIDEO:output_video"

# Performs motion analysis on an incoming video stream.
node: {
  calculator: "MotionAnalysisCalculator"
  input_stream: "VIDEO:input_video"
  output_stream: "CAMERA:camera_motion"
  output_stream: "FLOW:region_flow"

  node_options: {
    [type.googleapis.com/mediapipe.MotionAnalysisCalculatorOptions]: {
      analysis_options {
        analysis_policy: ANALYSIS_POLICY_CAMERA_MOBILE
        flow_options {
          fast_estimation_min_block_size: 100
          top_inlier_sets: 1
          frac_inlier_error_threshold: 3e-3
          verification_distance: 5.0
          verify_long_feature_acceleration: true
          verify_long_feature_trigger_ratio: 0.1
          tracking_options {
            max_features: 500
            adaptive_extraction_levels: 2
            min_eig_val_settings {
              adaptive_lowest_quality_level: 2e-4
            }
            klt_tracker_implementation: KLT_OPENCV
          }
        }
      }
    }
  }
}

# Reads optical flow fields defined in
# mediapipe/framework/formats/motion/optical_flow_field.h,
# returns a VideoFrame with 2 channels (v_x and v_y), each channel is quantized
# to 0-255.
node: {
  calculator: "FlowPackagerCalculator"
  input_stream: "FLOW:region_flow"
  input_stream: "CAMERA:camera_motion"
  output_stream: "TRACKING:tracking_data"

  node_options: {
    [type.googleapis.com/mediapipe.FlowPackagerCalculatorOptions]: {
      flow_packager_options: {
        binary_tracking_data_support: false
      }
    }
  }
}

# Tracks box positions over time.
node: {
  calculator: "BoxTrackerCalculator"
  input_stream: "TRACKING:tracking_data"
  input_stream: "VIDEO:input_video"
  output_stream: "VIZ:output_video"



  node_options: {
    [type.googleapis.com/mediapipe.BoxTrackerCalculatorOptions]: {
      tracker_options: {
        track_step_options {
          track_object_and_camera: true
          tracking_degrees: TRACKING_DEGREE_OBJECT_SCALE
          inlier_spring_force: 0.0
          static_motion_temporal_ratio: 3e-2
        }
      }
        visualize_tracking_data: true
        visualize_state: true
        visualize_internal_state: true
      streaming_track_data_cache_size: 100
    }
  }
}
```

**Comment by KastusKalinovski** [comment]
@yegenzhi, @sgowroji Thank you for your help and provided flags, I've fixed the following error `E20210412 13:48:20.888913 25894 region_flow_computation.cc:2623] only cv tracking is supported.` by changing up CV_MAJOR_VERSION flag in region_flow_computation.cc. Now everything works!

**Comment by samlaf** [comment]
@KastusKalinovski what do you mean by "changing up CV_MAJOR_VERSION flag value in region_flow_computation.cc"?
In my case, CV_MAJOR_VERSION is 4, but region_flow_computation is set to only accept version 3... is this actually necessary? I tried changing all the `#if CV_MAJOR_VERSION == 3` to `#if CV_MAJOR_VERSION >= 3` and it seems to work so far. I'll start a new issue.

**Comment by laosanlyu** [comment]
> Hello, I am struggling with optical flow visualization. I am tying to reproduce this visualization. ![Screenshot from 2021-04-07 16-16-22](https://user-images.githubusercontent.com/41323462/113872543-a56d9480-97bc-11eb-88a3-747efb99acba.png) Can you please share what graph did you use to create this tracking?



> Hello, I am struggling with optical flow visualization. I am tying to reproduce this visualization. ![Screenshot from 2021-04-07 16-16-22](https://user-images.githubusercontent.com/41323462/113872543-a56d9480-97bc-11eb-88a3-747efb99acba.png) Can you please share what graph did you use to create this tracking?



> Hello, I am struggling with optical flow visualization. I am tying to reproduce this visualization. ![Screenshot from 2021-04-07 16-16-22](https://user-images.githubusercontent.com/41323462/113872543-a56d9480-97bc-11eb-88a3-747efb99acba.png) Can you please share what graph did you use to create this tracking?

Have you successfully visualize the state of tracking state for each box?

**Comment by zzmicer** [comment]
Hey, @laosanlyu!
Yes, I've extracted motion saliency points, and created a new bounding box around them.

**Comment by laosanlyu** [comment]
> 

could you please share the graph you made?
