### ISSUE TITLE
a typo in sample solutions

### ISSUE THREAD

**Issue by saadati944** [google/mediapipe#1858]
In the file `/docs/solutions/face_detection.md` in line 80 the `mp_face_detction` is misspelled but in the following lines it is correct

now :
```python
78: import cv2
79: import mediapipe as mp
80: mp_face_detction = mp.solutions.face_detection
81: mp_drawing = mp.solutions.drawing_utils
```

correct form :
```python
78: import cv2
79: import mediapipe as mp
80: mp_face_detection = mp.solutions.face_detection
81: mp_drawing = mp.solutions.drawing_utils
```

**Comment by sgowroji** [comment]
Hi @saadati944, Thanks for bringing to our notice. We make the corrections as early as possible. Thanks.

**Comment by sgowroji** [comment]
Hi @chuoling ,  Typo correction needed below this [code](https://github.com/google/mediapipe/blob/master/docs/solutions/face_detection.md#python-solution-api)

**Comment by chuoling** [comment]
Thank you for pointing it out. The typo has been fixed in our internal codebase upstream, and will be pushed to GitHub in the next release.
