### ISSUE TITLE
how to locate positions of obj and pngblob?

### ISSUE THREAD

**Issue by bugmany** [google/mediapipe#1861]
i 've create OBJ and PNGBLOB files, then render it such as below:
![IMG_20210408_142557](https://user-images.githubusercontent.com/6613590/113979952-803e5c00-9878-11eb-8d7c-e5f0bfc13a43.jpg)
below is face effect demo:
![IMG_20210408_142625](https://user-images.githubusercontent.com/6613590/113980023-98ae7680-9878-11eb-9023-b8d623df01f8.jpg)
so my customized OBJ render effection is not my expected, i think maybe there are mismatch location and position of OBJ or PNGBLOB or source code, how to locate and match OBJ coordination with realtime face coordination, could anyone give me help, thanks a lot.

**Comment by sgowroji** [comment]
Hi @bugmany, Could you please share your code and graph.  And also share your usecase details a bit more and also error details.

**Comment by bugmany** [comment]
hi @sgowroji, i've refered:

/mediapipe/graphs/face_effect/BUILD
encode_binary_proto(
    name = "glasses",
    input = "glasses.pbtxt",
    message_type = "mediapipe.face_geometry.Mesh3d",
    output = "glasses.binarypb",
    deps = [
        "//mediapipe/modules/face_geometry/protos:mesh_3d_proto",
    ],
)
then add:
encode_binary_proto(
    name = "facemask",
    input = "facemask.pbtxt",
    message_type = "mediapipe.face_geometry.Mesh3d",
    output = "facemask.binarypb",
    deps = [
        "//mediapipe/modules/face_geometry/protos:mesh_3d_proto",
    ],
)

exports_files([
    ...
    "facemask.pngblob",
])

/mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect/BUILD
add:
android_binary(
    name = "faceeffect",
    srcs = glob(["*.java"]),
    assets = [
        ...
        "//mediapipe/graphs/face_effect/data:fmask.binarypb",
        "//mediapipe/graphs/face_effect/data:fmask.pngblob",
        ...
    ],
...
)
PNGBLOB:
![facemask](https://user-images.githubusercontent.com/6613590/114002447-74aa5f80-988f-11eb-8b02-09463149bfb1.png)

**Comment by kostyaby** [comment]
Hey @bugmany,

One important difference to note between (A) the MP `facemask` example and (B) your `fmask` is that (A) uses runtime face mesh as geometry while (B) uses `fmask.binarypb` as geometry

By looking at the symptoms, I'd say that the way `fmask.binarypb` is aligned with canonical face mask needs to be changed a bit: please move the `fmask` model **closer to the camera** so that the canonical face mesh is **strictly behind** your 3D model. The reason for is that during runtime we use face mesh to "occlude" everything that goes behind the face. What I see on the screenshot that you shared looks like exactly a part of the mask being occluded by the face mesh

**Comment by bugmany** [comment]
hi @kostyaby, 
those my typing error, files name are  "facemark" in my project source code, as below:
"//mediapipe/graphs/face_effect/data:facemask.binarypb",
"//mediapipe/graphs/face_effect/data:facemask.pngblob",

thanks.

**Comment by bugmany** [comment]
hi @kostyaby, 
after i've moved camera position, now display OK.
Thanks.

**Comment by bugmany** [comment]
hi @kostyaby, @sgowroji:
now i've render obj and png, as below,

![IMG_20210413_141415](https://user-images.githubusercontent.com/6613590/114505609-3af8a080-9c63-11eb-8115-42fed62bc1fe.jpg)

but i found this display only static image, and in project demo "face effect", the face paint display is animation, so i want to make it animation, so could you give me advice, thanks a lot.

**Comment by kostyaby** [comment]
Hey @bugmany,

`FaceGeometryEffectRendererCalculator` is totally missing critical features to make such rendering possible, so please consider just surfacing FaceGeometry data to the app level and then use some other rendering library to enable this effect (if you are seeking cross-platform solution, [Filament](Filament) is a great choice; it already comes with gltf-io library that'd simplify your 3D asset loading / handling routine)

**Comment by bugmany** [comment]
hi @kostyaby ,
i'll try to using Filament, thanks.

**Comment by sgowroji** [comment]
Hi @bugmany, As we see your query answered. We are closing this issue. Thanks!
