### ISSUE TITLE
.bazelversion should be relaxed (only accepts bazel 3.7.2)

### ISSUE THREAD

**Issue by brgl** [google/mediapipe#1862]
@sgowroji I don't know why you closed my previous issue - it was not resolved, I only made a mistake in the problem's description. The issue is still there so reposting below.

-----

Current bazel version is `4.0.0` and it works fine for mediapipe. The .bazelversion in the mediapipe repository however specifies 3.7.2 as the only accepted version. This should be relaxed to accept any later version.

The problem triggers the following error in `setup.py`:

```python
 86   try:
 87     bazel_version_info = subprocess.check_output(['bazel', '--version'])
 88   except subprocess.CalledProcessError:
 89     sys.stderr.write('fail to get bazel version by $ bazel --version.')
```

Line 87 raises an Exception because the bazel program reads `.bazelversion` and bails out because it's not `3.7.2` and so `setup.py` fails here.

The error message is confusing too in this case. I would normally submit a patch changing the `.bazelversion` to something like `3.7.2 <` or whatever the syntax is but I have no idea what's up with the git history of mediapipe being just some imports. I guess it's google stuff. :man_shrugging:

**Comment by sgowroji** [comment]
Apology for my misunderstanding on the previous ticket. We are glad you bought this upto our notice. Could you please mention what infromation you needed in submitting  the patch. Am not sure about it, but i can assign it to @jiuqiant who can guide you on the above. Thanks!

**Comment by jiuqiant** [comment]
.bazelversion can only specify exactly one bazel version. Since bazel 4.0.0 has an issue on macOS with Xcode 11.3, we choose  Bazel 3.7.2.  From https://github.com/google/mediapipe/releases/tag/0.8.3.2, we recommend users using bazelisk instead of bazel. bazelisk will find the desired bazel version and install it automatically under the hood. 

I agree that the python setup.py script doesn't cover the bazel version check well and will work on a better version check process.

**Comment by brgl** [comment]
> .bazelversion can only specify exactly one bazel version. 

:confused: 

This is a strange limitation but I guess this is out of scope of this project then...

**Comment by sgowroji** [comment]
Hi @brgl,  From Above comment your query is answered. Please let us know if you still have any further queries.

**Comment by sgowroji** [comment]
Hi @brgl, Could you please respond to my above comment. Thanks!

**Comment by brgl** [comment]
No, I don't, thanks.
