### ISSUE TITLE
cannot install mediapipe

### ISSUE THREAD

**Issue by mayank6940** [google/mediapipe#1863]
**I have python 3.8.3 version but I can't install mediapipe it's shows me //Could not find a version that satisfies the requirement mediapipe//
![Screenshot (638)](https://user-images.githubusercontent.com/44741414/114032938-74639180-989a-11eb-8947-83632c77acab.png)
**

**Comment by jiuqiant** [comment]
Please verify your pip is for python3 or use `python3 -m pip` instead.

**Comment by sgowroji** [comment]
Hi @mayank6940, Could you please try the commands mentioned in the above comment and update. Thanks!

**Comment by mayank6940** [comment]
Thanks @jiuqiant  @sgowroji  problem is fixed now i read documentation of mediapipe they support only in 3.7 python versiom only
