### ISSUE TITLE
FaceMesh get Euler Angles

### ISSUE THREAD

**Issue by lilinxiong** [google/mediapipe#1864]
in Android use FaceMesh .aar. 
Can I get Euler Angles ?

**Comment by lilinxiong** [comment]
I find in [model.h](https://github.com/google/mediapipe/blob/0.8.3.2/mediapipe/modules/objectron/calculators/model.h) have **GetRotationAngles()**. But I found no place to use it. I want to confirm if it is available. If it can be used, what should I do. Otherwise how should I get Euler angle…
We are expecting a reply thanks～

**Comment by sgowroji** [comment]
Hi @lilinxiong, the model.h file which you are referring is from objectron solution. So are you expecting similar from FaceMesh calculators ? Could you please explain what is your usecase specific to  GetRotationAngles(). Thanks!

**Comment by lilinxiong** [comment]
@sgowroji thank you for your reply. Yes I want to use it in FaceMesh. I want to use FaceMesh to achieve a similar IOS Animoji features.
Collect facial expressions and map to virtual characters. so we need **Euler Angles** . I find **Model.h** have function to get Euler angle. so FaceMesh is it possible to integrate it ?

**Comment by nicoinn** [comment]
This is related to this https://github.com/google/mediapipe/issues/1379 

I believe the solution is in there already, albeit in a little convoluted form ;)

**Comment by lilinxiong** [comment]
@nicoinn thanks for your advice! But I think [#1642](https://github.com/google/mediapipe/issues/1642#issue-813295943) mentioned that it would be better to calculate Euler angles. It’s just that it’s better to officially support returning Euler Angles…

**Comment by ianni67** [comment]
@lilinxiong, before you spend time with your application, please read #1786 as that issue might affect your case as well. In brief, the whole set of landmarks is affected by small eyes and irises [motion](https://github.com/google/mediapipe/issues/1642#issuecomment-804362081), so the face transformation matrix is also affected and the Euler angles are affected as well. I'm still awaiting for any response by interested google experts in order to look for a solution, after more than two weeks.

**Comment by lilinxiong** [comment]
@ianni67 Yes i noticed too. But now we don’t think about eyeballs. Of course, if the eyeballs are handled well, it’s great. 
We are waiting for solutions from Google experts who are interested in this.

**Comment by lilinxiong** [comment]
Hi @sgowroji. Can I in [face_mesh_mobile.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_mesh/face_mesh_mobile.pbtxt) join in [AnnotationsToModelMatricesCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/object_detection_3d/calculators/annotations_to_model_matrices_calculator.cc) Calculator ? 
If I can, I can get the result I want...

**Comment by lilinxiong** [comment]
Hi @sgowroji I have solved my own problem. I will close with comment....

**Comment by bduvenhage** [comment]
Hi @lilinxiong 
May I ask how you solved the problem?
Thanks.

**Comment by lilinxiong** [comment]
Hi @bduvenhage First of all, let me talk about my usage scenario, if your scenario is the same as mine, then please ask me again. Of course, if it is different, you can talk about your usage scenario, and I can help you figure out a solution.

#### Background:
My original intention was to drive the head of an avatar to perform actions.So you need very precise Euler Angles(Otherwise it will jitter and the experience will be very bad).But when the roll rolls, it does not affect yaw, let alone pitch. In other words, the three angles are irrelevant, we just used the concept of Euler Angles. Use yaw, roll, and pitch to control the three movements of the head respectively.

------
If the problem you want to solve is the same as mine. I will tell you how I did it. If it is different, I can help you think about how to solve your problem.

**Comment by vinhnguyen21** [comment]
Hi @lilinxiong 
I have the same problem as you mentioned. Can you give me suggestion how to convert face mesh into euler angles?

**Comment by lilinxiong** [comment]
> Hi @bduvenhage First of all, let me talk about my usage scenario, if your scenario is the same as mine, then please ask me again. Of course, if it is different, you can talk about your usage scenario, and I can help you figure out a solution.
> 
> #### Background:
> My original intention was to drive the head of an avatar to perform actions.So you need very precise Euler Angles(Otherwise it will jitter and the experience will be very bad).But when the roll rolls, it does not affect yaw, let alone pitch. In other words, the three angles are irrelevant, we just used the concept of Euler Angles. Use yaw, roll, and pitch to control the three movements of the head respectively.
> 
> If the problem you want to solve is the same as mine. I will tell you how I did it. If it is different, I can help you think about how to solve your problem.

@vinhnguyen21 take a look? If it is the same, then I can advise you.

**Comment by vinhnguyen21** [comment]
Yes can you give me any suggestion/ @lilinxiong

**Comment by lilinxiong** [comment]
I have been busy recently, I will reply to you this weekend. @vinhnguyen21

**Comment by bduvenhage** [comment]
Thanks for replying @lilinxiong 

I need an accurate head pose transform to render a mask on the person in the video. It seems to work well, but when the person blinks many of the landmarks are affected which in turn affects the alignment of the mask.
