### ISSUE TITLE
Better android studio implementation documention 

### ISSUE THREAD

**Issue by badushaebrahim** [google/mediapipe#1865]
Most people who would like to get started in mediapipe in there android studios has may problem a little bit more explanation in the setup and generating building file for this and some lite video example for these would be a great help most

**Comment by badushaebrahim** [comment]
![image](https://user-images.githubusercontent.com/63869474/114305845-8130f100-9af7-11eb-8eda-d134a73ac508.png)

**Comment by badushaebrahim** [comment]
ANY IDEA HOW TO FIX THS

**Comment by badushaebrahim** [comment]
x-special/nautilus-clipboard
copy
file:///home/badushaebrahim/Downloads/log.txt

<h1>### my log<h1> i was following the given instruction in the mediapie.dev page 
os of dev :pop os
target :android (vivo u20)

**Comment by badushaebrahim** [comment]
[log.txt](https://github.com/google/mediapipe/files/6292010/log.txt)
log file is here

**Comment by LeeJeongHwi** [comment]
Hello @badushaebrahim , I build with Docker in Ubuntu and copy AAR , binarypb file, and then use it in Window Android Studio 

I tried all the Build in WSL2, Ubuntu, Window, and Android Studio.

Thank you

**Comment by sgowroji** [comment]
Hi @badushaebrahim, You can raise another issue for build and installation. I assume the above query is about documentation . Thanks!
