### ISSUE TITLE
Not able to convert output tensor to float

### ISSUE THREAD

**Issue by midhulavijayan** [google/mediapipe#1866]
Hi,
I am trying to implement simple binary classifier with custom tflite model. I am using model with one output node. If the output value is >threshold i am trying to make the class as outlier. Part of .pbxt file is shown below. The app is working till the TfLiteInferenceCalculator.

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "IMAGE_GPU:transformed_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 150
      output_height: 150
    }
  }
}

node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE_GPU:transformed_input_video"
  output_stream: "TENSORS_GPU:image_tensor"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteConverterCalculatorOptions] {
      zero_center: false
      max_num_channels: 1
    }
  }
}

node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS_GPU:image_tensor"
  output_stream: "TENSORS_GPU:output_tensor"
  #input_side_packet: "CUSTOM_OP_RESOLVER:op_resolver"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
      model_path: "mediapipe/models/finger_detection.tflite"
      use_gpu: true
    }
  }
}

App is getting crashed, when am trying to convert the output tensor to float using "TfLiteTensorsToFloatsCalculator"

node {
  calculator: "TfLiteTensorsToFloatsCalculator"
  input_stream: "TENSORS:output_tensor"
  output_stream: "FLOATS:float"
}

Can anyone help to build a basic image classifier using mediapipe pipeline?.. (any pretrained model is also fine).. I am facing problem with the tensor to float conversion :(.

**Comment by sgowroji** [comment]
calculator for converting TFLite tensors to to a float or a float vector.

```
Input:
  TENSORS - Vector of TfLiteTensor of type kTfLiteFloat32. Only the first tensor will be used.
Output:
 FLOAT(optional) - Converted single float number.
 FLOATS(optional) - Converted float vector.

Notes: To output FLOAT stream, the input TFLite tensor must have size 1, e.g.only 1 float number in the tensor.
```
```
 node {
   calculator: "TfLiteTensorsToFloatsCalculator"
  input_stream: "TENSORS:tensors"
  output_stream: "FLOATS:floats"
 }
```

**Comment by midhulavijayan** [comment]
I tried with this calculator, but app is getting crashed
node {
   calculator: "TfLiteTensorsToFloatsCalculator"
  input_stream: "TENSORS:tensors"
  output_stream: "FLOATS:floats"
 }

**Comment by sgowroji** [comment]
Hi @midhulavijayan, Could you please share your error logs to understand the issue much better. Thanks!

**Comment by midhulavijayan** [comment]
I tried to save the trace using "https://google.github.io/mediapipe/tools/tracing_and_profiling.html#tracing-on-android" tutorial. But the file is not getting saved. It would be really helpful if you can make a mediapipe pipeline (.pbtxt) file for image classification model (download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_0.25_224.tgz).

**Comment by ayushgdev** [comment]
@midhulavijayan We are revisiting older issues. Are you still looking for a resolution? If yes, we request you to attach error logs to understand the situation better.
