### ISSUE TITLE
Missing hand landmarks

### ISSUE THREAD

**Issue by LucaswasTaken** [google/mediapipe#1869]
Despite de High accuracy of the hand detector, sometimes there are missing landmarks between frames. Should it be interesting a interpolator to reconstruct this missing landmarks in real time?

**Comment by sgowroji** [comment]
Hi @LucaswasTaken, Could you please explain your use case with complete details. Can you illustrate more about the missing landmarks. Thanks

**Comment by sgowroji** [comment]
Hi @LucaswasTaken, Please respond to the above comment. Thanks!

**Comment by LucaswasTaken** [comment]
Sorry for the delay, I was thinking about a way to explain the problem. Because sometimes the position or the angle of the hands, between frames, the detection may fail and does not return the hand result (the body detection almost never happen). I think this could be solved by predicting the trajectory of the next hand position if the hand could not be detected in the next frame. In videos it was easy to reconstruct the few missing frames by interpolation, but in real time i thing that a trajectory prediction to replace the hand in case of no detection between two frames could level up the detection even more. What do you thing? This make a little sense?

**Comment by sgowroji** [comment]
Thank you for sharing your observation. It would be great if you can provide the error or failure screenshot. Thanks!

**Comment by sgowroji** [comment]
Hi @LucaswasTaken, Can you share the above mentioned details. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now, due to lack of activity. Feel free to reopen this if the above issue still exists.

**Comment by LucaswasTaken** [comment]
Sorry for the long delay. For instance, these three frames are part of a video. Between the first and last frame, the landmarks of the right hand are missing. In these cases, I usually interpolate between the landmarks before and after and reconstruct the missing frame. Do you think that this "interpolation" function that I use could be a good addition to make a pull request?

![before](https://user-images.githubusercontent.com/21283326/120938857-63dd6500-c6eb-11eb-8eb6-fbf6f149c28d.jpg)
![problem](https://user-images.githubusercontent.com/21283326/120938859-650e9200-c6eb-11eb-8ef6-451a841dbfaf.jpg)
![after](https://user-images.githubusercontent.com/21283326/120938858-6475fb80-c6eb-11eb-9535-476a578348e3.jpg)

**Comment by bazarevsky** [comment]
Hello, we are constantly improve our hand models by mining a new samples, where model tend to fail. And hopefully issue you are facing would be gone in a new release. 

We tried many different approaches and see that even sometimes for some particular cases they could improve the model quality, they also can decrease model quality for other cases, so we try to handle issues via neural network itself and the dataset, and not by adding complicated post-processing logic.
