### ISSUE TITLE
Using FaceGeometryPipelineCalculator in Python

### ISSUE THREAD

**Issue by alexrichardson21** [google/mediapipe#1872]
Is it possible to use FaceGeometryPipelineCalculator through mp.CalculatorGraph() in Python on face_mesh solution output landmarks?

**Comment by sgowroji** [comment]
Hi @alexrichardson21, Thanks for sharing your query. Could you please elaborate your use case to understand the query much better. Thanks!

**Comment by sgowroji** [comment]
Hi @alexrichardson21, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue as of now,  Due to lack of activity on it.
