### ISSUE TITLE
rapid hand motion causes shrinking/stretching of landmark positions

### ISSUE THREAD

**Issue by pjbaron** [google/mediapipe#1873]
I'm using mediapipe for handtracking in Unity via @homuler's excellent [MediaPipeUnityPlugin](https://github.com/homuler/MediapipeUnityPlugin) and I noticed that if the hand moves rapidly horizontally, the landmarks appear to either squash or stretch to a quite considerable degree, depending on the direction of motion.

I displayed the landmarks as spheres in 3D in front of the webcam display (with the Z distance scaled to match the X,Y scaling) and froze the demo when the effect was very strong.
![image](https://user-images.githubusercontent.com/614817/114487771-47312d80-9c64-11eb-9a40-1d0ddf8e3b34.png)
(Note: the webcam image here is delayed from a buffer but the landmark display in red and green is 'live', which is why it isn't aligned with the hand image)

When I move the camera around to view these points from other angles, I see that a considerable Z distance has been added (incorrectly) to the (nearly flat) palm's landmarks causing them to appear foreshortened when viewed from the front.
![image](https://user-images.githubusercontent.com/614817/114487990-a5f6a700-9c64-11eb-8583-579f5ba385a5.png)

I would speculate that this could be due to landmarks being gathered from several different camera frames with the motion between frames causing the points to be squashed together horizontally.  The Z depth might then be an attempt to retain the known geometry of the hand given the squashed 2d screen points.

If my guess is correct, is it possible to modify the graph so that all landmarks will be gathered from a single frame?

**Comment by pjbaron** [comment]
For comparison, this is what the spheres look like when the hand is at rest or moving at a more moderate velocity:
![image](https://user-images.githubusercontent.com/614817/114490753-801fd100-9c69-11eb-923a-dca5cc0c1bb4.png)

**Comment by eknight7** [comment]
Hi @pjbaron, thank you for your question.

> If my guess is correct, is it possible to modify the graph so that all landmarks will be gathered from a single frame?

You can modify the Hand tracking graph so that landmark extraction runs on every frame. Try changing the `bool_value` to `false` in the `ConstantSidePacketCalculator` that determines if the landmark detection for the current frame should use landmarks from the previous frame here: https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu.pbtxt#L41-L52

The logic in the next 3 nodes:
```
node {
  calculator: "GateCalculator"
  input_side_packet: "ALLOW:use_prev_landmarks"
  input_stream: "prev_hand_rects_from_landmarks"
  output_stream: "gated_prev_hand_rects_from_landmarks"
}

# Determines if an input vector of NormalizedRect has a size greater than or
# equal to the provided num_hands.
node {
  calculator: "NormalizedRectVectorHasMinSizeCalculator"
  input_stream: "ITERABLE:gated_prev_hand_rects_from_landmarks"
  input_side_packet: "num_hands"
  output_stream: "prev_has_enough_hands"
}

# Drops the incoming image if enough hands have already been identified from the
# previous image. Otherwise, passes the incoming image through to trigger a new
# round of palm detection.
node {
  calculator: "GateCalculator"
  input_stream: "image"
  input_stream: "DISALLOW:prev_has_enough_hands"
  output_stream: "palm_detection_image"
  options: {
    [mediapipe.GateCalculatorOptions.ext] {
      empty_packets_as_allow: true
    }
  }
}
```

will force the graph to run hand landmark extraction on every image when `use_prev_landmarks` is set to false.

**Comment by eknight7** [comment]
@fanzhanggoogle Can you please answer this part of the question:

> When I move the camera around to view these points from other angles, I see that a considerable Z distance has been added (incorrectly) to the (nearly flat) palm's landmarks causing them to appear foreshortened when viewed from the front.
I would speculate that this could be due to landmarks being gathered from several different camera frames with the motion between frames causing the points to be squashed together horizontally. The Z depth might then be an attempt to retain the known geometry of the hand given the squashed 2d screen points.

**Comment by sgowroji** [comment]
Hi @pjbaron, Could you please respond if you still looking resolution for the above queries. Thanks!

**Comment by pjbaron** [comment]
I've finished working on that project, however I may need to do accurate hand tracking at moderate motion speeds in the future... so it would be great if there is anything we can do about it.  I believe eknight7 suggestion to modify the hand tracking graph would help provided that the system is capable of doing all of the processing in a single frame.
I think a better solution would be to deliver the same data to be processed for every tracking point, rather than allowing multi-tasking or new images to be picked up before they are all processed. This would prevent the squashing effect entirely and deliver much more reliable 'hand shapes' at the cost of less fluid updates on weaker devices.

**Comment by kuaashish** [comment]
Hello @pjbaron,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
