### ISSUE TITLE
Try to get  anchor stream of instant motion tracking. 

### ISSUE THREAD

**Issue by ANK-VALUES** [google/mediapipe#1874]
The instant motion tracing effect is great， but I want to do more customize on it。what I need is the anchor data list， which is declared in 'instant_motion_tracking.pbtxt' as "tracked_anchor_data".

**instant_motion_tracking.pbtxt**

pbtxt

node {
  calculator: "RegionTrackingSubgraph"
  input_stream: "VIDEO:input_video"
  input_stream: "SENTINEL:sticker_sentinel"
  input_stream: "ANCHORS:initial_anchor_data"
  output_stream: "ANCHORS:tracked_anchor_data"
}

The code that I want to add in java side is as below.

**MainActivity**

processor.addPacketCallback("tracked_anchor_data", packet -> {
PacketGetter.getBytes(packet); // it crash here with 'signal 6' in c side
});

I have tried some methods .
* declare output_stream in head of that pbtxt file.
* define a proto named "MyAnchor", and convert the anchor data to  MyAnchor. output MyAnchor in calculator and try parse them in java side. the problem is the same (signal 6 , crash).
* use ' PacketGetter.getBytes(packet)' to get raw bytes. but the problem is the same (signal 6 , crash).

I can see the anchor data, which I print out in c side, but I am tired of trying to fetch them in java side.

I will be very grateful for your help。 🙏

**Comment by ANK-VALUES** [comment]
done.

**Comment by arijith96** [comment]
Hi @ANK-VALUES ,
Since you had closed this issue, I assume that you were able to get the tracked anchors on the java side too. :) 

Could you please explain how you proceeded? I am also trying to obtain the tracked anchor data..
