### ISSUE TITLE
android posetrackinggpu , PacketCallback is not called when no landmark is detected in a frame

### ISSUE THREAD

**Issue by yangcheng** [google/mediapipe#1875]
I want to know when a frame processing is finished even if there is no landmark detected, how can I do that? is there a way to tell mediapipe framework to invoke the [callback](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu/MainActivity.java#L37) with an empty result?
thanks

**Comment by sgowroji** [comment]
Hi @yangcheng, Can you provide your repo code to understand the issue much better with proper comments.

**Comment by yangcheng** [comment]
hi, there is no real code change.  I just added  ` ProtoUtil.registerTypeName(NormalizedLandmarkList.class, "mediapipe.NormalizedLandmarkList");` to  prevent a crash 

https://github.com/yangcheng/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu/MainActivity.java

to repo the case, 

run posetrackinggpu ,  make sure the callback is run by  set log level to verbose.

when the app is running, point camera to a scene without human. in this case, the callback is not called.

**Comment by yangcheng** [comment]
seems related to https://github.com/google/mediapipe/issues/1425#issuecomment-821738525 . Are there plans to add config options in graph?

**Comment by yangcheng** [comment]
@mcclanahoochie as you suggested, move the discussion here.  Is there a way to add another dummy output that will always be called when the process finish? so I can know the frame process is finished?

**Comment by mcclanahoochie** [comment]
Try registering an `ObserveOutputStream` callback, instead of the Poller.

examples here
https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/calculators/core/immediate_mux_calculator_test.cc#L343
and here 
https://github.com/google/mediapipe/issues/850#issuecomment-776447734
