### ISSUE TITLE
box tracking using Mediapipe in browser using js and wasm

### ISSUE THREAD

**Issue by constantvariable1** [google/mediapipe#1876]
Is there any way to implement the box tracking solution available in MP, in js and wasm so that it can run in the browser?
If yes then please tell me the steps required to do the same.
I studied the solutions available for cpp. Also the objectron solution in python. I wish to make something that can track objects  through the browser from a mobile device. 
Any tips are much appreciated.

**Comment by sgowroji** [comment]
Hi @constantvariable1, Present we don't have support for js, Have a look at [this](https://google.github.io/mediapipe/solutions/solutions).

**Comment by constantvariable1** [comment]
hi @sgowroji .Thanks for the reply. But I was wondering if there are any methods such as converting the existing box tracking calculators available to us in cpp into wasm using emscripten and make a js solution that communicates with it myself. I'm very new at this so I might be talking nonsense here.

**Comment by sgowroji** [comment]
Hi @constantvariable1, I have added Right Assignees for this issue. They can guide you well if there are any such methods.

**Comment by sgowroji** [comment]
Related issue https://github.com/google/mediapipe/issues/877

**Comment by sgowroji** [comment]
Hi @constantvariable1,  Your query answered in the above comment. We are closing this ticket. Thanks!
