### ISSUE TITLE
Question on box tracking 

### ISSUE THREAD

**Issue by youngkyungkim** [google/mediapipe#1880]
I have successfully built a box tracking part inside the docker container, using the code that was given, which is 

`bazel build -c opt \
--define MEDIAPIPE_DISABLE_GPU=1 \
--define no_aws_support=true \
--linkopt=-s \
mediapipe/examples/desktop/object_tracking:object_tracking_cpu
`

However, I was struggling to run the analysis, when my input is a video file not from a camera.
For running a code below, I get error message saying "ERROR: Unknown command line flag 'input_side_packets'": 

`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/object_tracking/object_tracking_cpu \
  --calculator_graph_config_file=mediapipe/graphs/tracking/object_detection_tracking_desktop_live.pbtxt \
  --input_side_packets=input_video_path=input/input.avi ,output_video_path=output/output.avi` 

I wasn't able to find any tutorial or document for this so I was stuck... Any tips or resources of using box tracking inside the docker would be appreciated, especially on what kind of parameters there are for me to extract some data into json or csv files! 

Lastly, I had a question on whether all this media pipe analysis is computed in local computer. It seems like it does from looking at documentation but I just wanted to double check since I am using clinical videos, which prevents me to move the video into other server except local machine. 

Thank you!

**Comment by sgowroji** [comment]
Hi @youngkyungkim, Could you please share your code, so that we can guide well. Thanks!

**Comment by youngkyungkim** [comment]
@sgowroji Hi! Thank you for helping me out! 

1. I used below code to create a container:
`docker run -it --name mediapipe \
    -v /diskA/data/food_adventure/raw/temp/input:/mediapipe/input \
    -v /diskA/data/food_adventure/raw/temp/output:/mediapipe/output \
    mediapipe:latest`
2. I used the below code to build for analysis:
`bazel build -c opt \
--define MEDIAPIPE_DISABLE_GPU=1 \
--define no_aws_support=true \
--linkopt=-s \
mediapipe/examples/desktop/object_tracking:object_tracking_cpu`
3. I used the below code to conduct analysis but it would give me error "ERROR: Unknown command line flag 'input_side_packets'":
`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/object_tracking/object_tracking_cpu \
  --calculator_graph_config_file=mediapipe/graphs/tracking/object_detection_tracking_desktop_live.pbtxt \
  --input_side_packets=input_video_path=input/input.avi ,output_video_path=output/output.avi`

It seems like the "input_side_packets" is not the right parameter when we use for box tracking. I was wondering where I could find place for all the parameters I could use for box tracking.

Also, I just wanted to ask you whether all this media pipe analysis is computed in local computer. It seems like it does from looking at documentation but I just wanted to double check since I am using clinical videos, which prevents me to move the video into other server except local machine.

Thank you in advance!

**Comment by jiuqiant** [comment]
I believe you need to do 
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/object_tracking/object_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/tracking/object_detection_tracking_desktop_live.pbtxt --input_video_path==input/input.avi --output_video_path=output/output.avi
```
