### ISSUE TITLE
Is it possible to get only the coordinates of the landmarks with original camera frame?

### ISSUE THREAD

**Issue by congnguyenthe** [google/mediapipe#1881]
Hi,

I am trying the Facemesh example, and I would like to ask if there is a way to get the coordinates of the landmarks with the original camera as output_stream only instead of the rendered one.
The reason for this is because I want to reuse my renderer without modifying the calculator code for the renderer in mediapipe.

Sorry if raising a new issue is not appropriate for the question.

**Comment by sgowroji** [comment]
Hi @congnguyenthe, Can you elaborate your use case with clear details like platform, what is current and expected behaviour?

**Comment by congnguyenthe** [comment]
Hi @sgowroji,
Thanks for your quick response!

Actually, I am trying with Mediapipe AAR:
https://google.github.io/mediapipe/getting_started/android_archive_library.html

I am able to run the Facemesh example, but I wanted to re-use the renderer as in:
https://github.com/google-ar/arcore-android-sdk/tree/master/samples/augmented_faces_java/app/src/main/java/com/google/ar/core/examples/java/common/rendering

So my question is that is there any way to get only the coordinates, or matrix of the face/landmark points from the mediapipe just like what ARCore returns in Pose? So that I can integrate the mediapipe with what we already had with ARCore since they are pretty much alike.

**Comment by sgowroji** [comment]
Duplicate issue https://github.com/google/mediapipe/issues/321.

**Comment by sgowroji** [comment]
Hi @congnguyenthe, Did you get a chance to go through the above comment.  Thanks!

**Comment by congnguyenthe** [comment]
Hi @sgowroji,

Thanks for your info, fortunately, I am able to get the camera frame without rendered object by comment out renderer section in the mediapipe code.
But I am still looking for how to integrate the result returned by mediapipe into the ARCore.

**Comment by congnguyenthe** [comment]
> @congnguyenthe do you have any news about the integration of Mediapipe and ARCore? Thank you

I don't have any information about the official one, but I do know how to get Mediapipe results and then show it with ARCore. You will have to build the AAR for Mediapipe, then use the callback function to get detection results for every frame then use that coordinates to display.
