### ISSUE TITLE
Can I get landmarks in Face Detection solution?

### ISSUE THREAD

**Issue by weixinz1** [google/mediapipe#1882]
Can I get landmarks in Face Detection solution in Android?

**Comment by sgowroji** [comment]
Hi @weixinz1, We have clear documentation for the query [here](https://google.github.io/mediapipe/solutions/face_detection#overview). Please go through it and let us know if you have any further queries. Thanks!

**Comment by weixinz1** [comment]
Hi @sgowroji I've read this article, but it's not very helpful, because it doesn't mention Android-related API. Moreover, I didn't find a way to get the landmarks in the java file in Git (https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu).

**Comment by mcclanahoochie** [comment]
You can capture the "face_detections" stream from the graph, in a similar way as the "hand_landmarks" from [here](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L49) , through 'addPacketCallback'.
See the [detections to render data calculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/detections_to_render_data_calculator.cc) (used in the face detection graph) on how to interpret the "face_detections" data

**Comment by sgowroji** [comment]
Hi @weixinz1, Could you please look into the above comment. Thanks!

**Comment by weixinz1** [comment]
@mcclanahoochie  @sgowroji thanks, I will try it

**Comment by sgowroji** [comment]
Thanks for the update. We are closing this issue now. Feel free to open if you have queries in the above comment. Thanks!
