### ISSUE TITLE
nailpaint try on 

### ISSUE THREAD

**Issue by rahulsuxsena1** [google/mediapipe#1883]
I want to make a nailpaint try on android app using hand tracking, i have used the hand tracking aar and is able to get the normalized points(landmarks) of the all top tips of the the five fingers. please suggest me how i can add or draw polygon on top of the camera screen? Please help

**Comment by sgowroji** [comment]
Hi @rahulsuxsena1, Did you get a chance to go through the [documentation](https://google.github.io/mediapipe/solutions/hands)
