### ISSUE TITLE
how can I enable/disable the red rectangle of face detection in android?

### ISSUE THREAD

**Issue by solmate-james** [google/mediapipe#1884]
I want to take a picture when detects the face, now I use screenshot to implement.
But the result contain the "face, 0.99" and some point and a rectangle.
It's possible to close it?

The camera will show like below.
![camera](https://user-images.githubusercontent.com/80659447/114674854-3ce16300-9d3a-11eb-94b9-4d90deeef9ea.png)

I need to get a picture like below.
![clean](https://user-images.githubusercontent.com/80659447/114674967-57b3d780-9d3a-11eb-88c4-6b775503b105.png)

**Comment by solmate-james** [comment]
@gkarpiak @mcclanahoochie 
Can anyone help me? thank you.

**Comment by mcclanahoochie** [comment]
the rendering happens in the AnnotationOverlayCalculator , you can _replace_ this node with a PassThroughCalculator like this:

```
node {
  calculator: "PassThroughCalculator"
  input_stream: "throttled_input_video"
  output_stream: "output_video"
}
```

or, you can edit the DetectionsToRenderDataCalculator to output empty RenderData packets.

**Comment by solmate-james** [comment]
Thanks for your help!! @mcclanahoochie @sgowroji 

Finally I resolve the problem, let me talk about my solution in detail!

1. Edit the following file and rebuild face detection aar.
    # /mediapipe/mediapipe/graphs/face_detection/BUILD
      `cc_library(
           name = "mobile_calculators",
           deps = [
               "//mediapipe/calculators/core:pass_through_calculator"    <- Add this line
           ],
       )`
        
    # /mediapipe/mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt
   `node {
         calculator: "PassThroughCalculator"
         input_stream: "throttled_input_video"
         output_stream: "output_video"
     }`

2. After rebuilding mobile_gpu.binarypb and changing the file mentioned above.
