### ISSUE TITLE
Getting landmarks for upper lips and chin, to apply beard filter Mediapipe in python?

### ISSUE THREAD

**Issue by MuhamaadUsman** [google/mediapipe#1886]
How can I get facial landmarks in python using Mediapipe face_mesh solution. I want to appy beard filter in python as i don't know C language so how can i do that?

**Comment by sgowroji** [comment]
Hi @MuhamaadUsman, You can have a look at this issue for some understanding https://github.com/google/mediapipe/issues/1498, https://github.com/google/mediapipe/issues/1106.

**Comment by ozett** [comment]
skeleton, not full code

```
with mp_face.FaceDetection(min_detection_confidence=0.5) as face_detection:

        results = face_detection.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

                h, w, c = image.shape
                # nose
                nx = int(mp_face.get_key_point(detection, mp_face.FaceKeyPoint.NOSE_TIP).x * w)
                ny = int(mp_face.get_key_point(detection, mp_face.FaceKeyPoint.NOSE_TIP).y * h)
                #print ('nx, ny: ', nx, ny)
                
                cv2.circle (image, (nx,ny), 5 ,(240,0,5), 3)
```

**Comment by ozett** [comment]
example skeletons:
https://github.com/google/mediapipe/issues/1798#issuecomment-812593547
https://github.com/google/mediapipe/issues/1798#issuecomment-815954201

**Comment by sgowroji** [comment]
Hi @MuhamaadUsman, Did you get a chance to go through above comments. Thanks!

**Comment by MuhamaadUsman** [comment]
Yes I did, I will implement them soon

**Comment by ozett** [comment]
Hey, cool. I will come here tomorrow again to check. Too early?

**Comment by sgowroji** [comment]
Thanks for your update. We will close this issue now. Please feel free to reopen above issue if you have any further queries in the same context.

**Comment by Leonnmarshall** [comment]
e como pode fazer isso com java scrip
