### ISSUE TITLE
[Strange problem] crash after add another calculator to dependency。

### ISSUE THREAD

**Issue by ANK-VALUES** [google/mediapipe#1887]
In the example of 'instantMotionTracking'，I want to combine the ability of 'handTracking'。 
The first step (also the only step) I did is adding the following line to BUILD file in 'examples/android/.../apps/instantmotiontracking'

        "//mediapipe/graphs/hand_tracking:mobile_calculators",

and the 'libmediapipe_jni.so' changed to the code as below.

cc_binary(
    name = "libmediapipe_jni.so",
    linkshared = 1,
    linkstatic = 1,
    deps = [
        "//mediapipe/graphs/hand_tracking:mobile_calculators", //  added line
        "//mediapipe/graphs/instant_motion_tracking:instant_motion_tracking_deps",
        "//mediapipe/java/com/google/mediapipe/framework/jni:mediapipe_framework_jni",
    ],
)

the App built out runs well until you click the '+' button for adding a new sticker. it will freeze for several seconds and crash with following hint.

04-14 19:15:03.406 26048 26107 E libc++abi: terminating with uncaught exception of type std::length_error: vector
--------- beginning of crash
04-14 19:15:03.406 26048 26107 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 26107 (Thread-7), pid 26048 (apps.twoability)

It is really strange, because I have not wrote any code except adding one line for dependency test.

**Comment by sgowroji** [comment]
Hi @ANK-VALUES, Could you please share the graphs, which you have changed. To understand it much better. Thanks!

**Comment by ANK-VALUES** [comment]
> Hi @ANK-VALUES, Could you please share the graphs, which you have changed. To understand it much better. Thanks!

Actually, I have not reached the step of modifying a graph. The only change now is adding one line in the BUILD file as mention above.

**Comment by ANK-VALUES** [comment]
This is really weird。 In the BUILD file,  If you change deps lines sequence， it will be OK。


*crash example* 

file: examples/android/.../app/instantmotiontracking/BUILD

cc_binary(
name = "libmediapipe_jni.so",
linkshared = 1,
linkstatic = 1,
deps = [
"//mediapipe/graphs/hand_tracking:mobile_calculators", // added line
"//mediapipe/graphs/instant_motion_tracking:instant_motion_tracking_deps",
"//mediapipe/java/com/google/mediapipe/framework/jni:mediapipe_framework_jni",
],
)


*normal example*

*crash example* 

file: examples/android/.../app/instantmotiontracking/BUILD

cc_binary(
name = "libmediapipe_jni.so",
linkshared = 1,
linkstatic = 1,
deps = [
"//mediapipe/graphs/instant_motion_tracking:instant_motion_tracking_deps",
"//mediapipe/graphs/hand_tracking:mobile_calculators", // added line， change from first line to second line。
"//mediapipe/java/com/google/mediapipe/framework/jni:mediapipe_framework_jni",
],
)

It seems that some symbols in 'hand_tracking:mobile_calculators' affect the 'instant_motion_tracking:instant_motion_tracking_deps' and linker build a wrong target if you put 'hand_tracking:mobile_calculators' in first line.

Changing sequence is not the  right solution, i want to know the really problem source of this weird situation.

**Comment by ZhAnGeek** [comment]
same problem, only adding hand tracking deps line to BUILD file of instant_motion_tracking. And I get built success however run crash immediately when add a sticker to the screen.

if it is a build link prolem or something, it should crash at the first moment, however it seems to be related with sticker adding.

**Comment by ANK-VALUES** [comment]
It is the problem of symbol conflict inside mediapipe。I have solved it by changing ton of deps。Thank you buddy。😁

**Comment by homuler** [comment]
I think #1617 is the same problem.
