### ISSUE TITLE
Pose Tracking Gpu with local video file 

### ISSUE THREAD

**Issue by alekhra** [google/mediapipe#1888]
Hello, 
I am a master student at TU Kaiserslautern, Germany. I am doing my research on Human Pose Estimation. I came across Mediapipe and was successfully able to use the examples of apps provided for Android.

I am building an Android app over mediapipe posetrackinggpu. I want to use "posetrackinggpu" on a video(.mp4) saved in my phone. 
So the steps are : load video from phone -> run pose tracking on video.

Please guide me to the correct way of doing it.

Thanks in advance

**Comment by sgowroji** [comment]
Have a look at this  issue https://github.com/google/mediapipe/issues/597#issuecomment-611905236. If not reach us back

**Comment by sgowroji** [comment]
Hi @alekhra, did you get a chance to go through the above comment. Thanks!

**Comment by alekhra** [comment]
Thanks @sgowroji for the reply. I am still working on it. Somehow the video is not becoming visible.
Things I did : 
1. I build MediaPipe AAR using Android(https://google.github.io/mediapipe/getting_started/android_archive_library.html)
2. I removed camera-related functions and added the media play method,  just like mentioned in #597 (comment). 
3. Then I set the surface texture to ExternalTextureConverter Object in setupPreviewDisplayView method under surface changed.
I think there is a small mistake I am doing during this and somehow the frames are not being rendered. May be 1 or 2 day more and I will fix it and will reply with the working code.
Thanks for your support.

**Comment by sgowroji** [comment]
Hi @alekhra, Could you please share your issue status.

**Comment by sgowroji** [comment]
Hi @alekhra, Can you please respond to my above comment. Thanks!

**Comment by alekhra** [comment]
Good Morning Sunil,

The issue is my whole setup of code was in-office system, and because of
corona, I cannot go to office for past 2 weeks.  If you want, you can close
the ticket, I will reopen it if I get into issue.
Thanks a lot for your support, sty safe and have a nice day ahead.

Best
Arpit Lekhra
Technische Universität Kaiserslautern
Indian Institute Of Information Technology Allahabad

01793836519

**Comment by sgowroji** [comment]
Thanks for the update, We are closing this issue now. Feel free to reopen if the above issue still exists and also reach if you have any further Query.
