### ISSUE TITLE
Unable to find an identity while building app for ios!

### ISSUE THREAD

**Issue by johniao** [google/mediapipe#189]
when I run "bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp" on my Mac, I copy and renamed  another
xxx.mobileprovision file to provisioning_profile.mobileprovision,and then got the error "ERROR: Unable to find an identity on the system matching the ones in mediapipe/provisioning_profile.mobileprovision".
May any help? With great appreciate!!!

**Comment by johniao** [comment]
It is the problem with my profile.mobileprovision , even though I tried several mobileprovision files before which are proved not valid for all. Finally I tried a valid mobileprovision file from my friend ,I got success!  Thank you all the same!

**Comment by Acimaz** [comment]
I do have the same issue atm. I created the profile myself but don't understand what's missing now to fix it.

**Comment by jiuqiant** [comment]
> I do have the same issue atm. I created the profile myself but don't understand what's missing now to fix it. What was the difference in your faulty and working profile?

Your mac needs to be configured as well to have the development certificate as well.
