### ISSUE TITLE
Calculating size from two landmark on users face

### ISSUE THREAD

**Issue by fahadhaq** [google/mediapipe#1891]
I am currently working on calculating actual distance based on face landmark, for example I have the following two landmarks for which I can get the landmark out put.

Landmark[6]: (0.36116672, 0.93204623, 0.0019629495)
Landmark[164]: (0.36148804, 0.99501055, -0.06169401)

How would I calculate the actual size based on the above information?

Failing that how would I get the actual size of  the iris?

Any help would be greatly appreciated

**Comment by sgowroji** [comment]
Hi @fahadhaq, Thanks for reaching us regarding your issue. Could you please explain your use case with more details and graph or code repo to understand much better. Thanks!

**Comment by fahadhaq** [comment]
@sgowroji I am using the iris detection along with facemash to try and calculate distance between two landmark on users face. Similar to the landmark example below. 

Landmark[6]: (0.36116672, 0.93204623, 0.0019629495)
Landmark[164]: (0.36148804, 0.99501055, -0.06169401)

So far I have tried using the iris top(x,y) and bottom(x,y) position to figure out the height of the iris and use the following formula to calculate the distance between two landmark. Not really sure if tis is even close to being correct.

x = (11.7 / irisDistance) * distanceBetweenLandmark


Thanks,

Fahad

**Comment by kostyaby** [comment]
Hey @fahadhaq,

The approach you described is a somewhat decent approximation of metric distance between two landmarks. You might observe that metric value jumps quite a lot as you are essentially trying to transfer the scale of a small object with a small error (iris) to a larger object (face / head) - this turns the small iris landmark error into a larger error. One way or another, this doesn't make this approach good or bad - so I'd recommend you to evaluate your approach for the use case you're trying to solve. If it's precise enough and/or you can cope with the metric "jitter" I described earlier through averaging scale across multiple frames (or, in general, filtering in some way) than I'd recommend you to go forward with it. If it's not satisfactory in terms of quality though, I'd recommend you seeking a solution outside of MediaPipe as I don't believe we provide any solutions that could be used for a more accurate landmark size estimation

**Comment by fahadhaq** [comment]
Hey @kostyaby Thanks for the reply. I am currently testing it with users to see if the solution would work in the long term for us. We have noticed some error but we are taking the avg of multiple scans. Thanks again for your help

**Comment by sgowroji** [comment]
Thanks for sharing your observations. We are closing this issue now as we see you got required help.

**Comment by dandingol03** [comment]
> Hey @kostyaby Thanks for the reply. I am currently testing it with users to see if the solution would work in the long term for us. We have noticed some error but we are taking the avg of multiple scans. Thanks again for your help

Hi, what's the going of your calculating method. Does it work?

**Comment by dandingol03** [comment]
> @sgowroji I am using the iris detection along with facemash to try and calculate the true distance between two landmark on users face. Similar to the landmark example below.
> 
> Landmark[6]: (0.36116672, 0.93204623, 0.0019629495) Landmark[164]: (0.36148804, 0.99501055, -0.06169401)
> 
> So far I have tried using the iris top(x,y) and bottom(x,y) position to figure out the height of the iris and use the following formula to calculate the distance between two landmark. Not really sure if tis is even close to being correct. For the landmark distance I calculate the distance between LandmarkA(x,y) and LandmarkB(x,y). 11.7 is the constant for iris size.
> 
> x = (11.7 / irisDistance) * distanceBetweenLandmark
> 
> For the iris landmark I am using the iris_to_depth_calculator.cc file
> 
> Thanks,
> 
> Fahad

Hi, i am also trying to compute the real-world eye distance. But i can't understand the formula you provide: ` x = (11.7 / irisDistance) * distanceBetweenLandmark`

**Comment by Jesuscc9** [comment]
any update? I am trying to measure the distance of the square drawn in the iris, to be able to calculate the distance than the user is far away from the camera, but specifically from the eyes, is there any other approach to this use case? 
@kostyaby 
Regards.
