### ISSUE TITLE
Crash with example using AAR face_detection_aar_example

### ISSUE THREAD

**Issue by cjl84914** [google/mediapipe#1892]
i used "mediapipe_face_detection_aar_example-master" example  build a face_effect_app,  the aar file was builded with mediapipe v0.8.3.2.

**android code:**
```
public class MainActivity extends AppCompatActivity {
    private static final String TAG = "MainActivity";

    private static final String BINARY_GRAPH_NAME = "pb/face_effect_gpu.binarypb";
    private static final String INPUT_VIDEO_STREAM_NAME = "input_video";
    private static final String OUTPUT_VIDEO_STREAM_NAME = "output_video";
    private static final CameraHelper.CameraFacing CAMERA_FACING = CameraHelper.CameraFacing.FRONT;

    // Flips the camera-preview frames vertically before sending them into FrameProcessor to be
    // processed in a MediaPipe graph, and flips the processed frames back when they are displayed.
    // This is needed because OpenGL represents images assuming the image origin is at the bottom-left
    // corner, whereas MediaPipe in general assumes the image origin is at top-left.
    private static final boolean FLIP_FRAMES_VERTICALLY = true;

    static {
        // Load all native libraries needed by the app.
        System.loadLibrary("mediapipe_jni");
        System.loadLibrary("opencv_java3");
    }

    // {@link SurfaceTexture} where the camera-preview frames can be accessed.
    private SurfaceTexture previewFrameTexture;
    // {@link SurfaceView} that displays the camera-preview frames processed by a MediaPipe graph.
    private SurfaceView previewDisplayView;

    // Creates and manages an {@link EGLContext}.
    private EglManager eglManager;
    // Sends camera-preview frames into a MediaPipe graph for processing, and displays the processed
    // frames onto a {@link Surface}.
    protected FrameProcessor processor;
    // Converts the GL_TEXTURE_EXTERNAL_OES texture from Android camera into a regular texture to be
    // consumed by {@link FrameProcessor} and the underlying MediaPipe graph.
    private ExternalTextureConverter converter;

    // Handles camera access via the {@link CameraX} Jetpack support library.
    private CameraXPreviewHelper cameraHelper;
    private static final String USE_FACE_DETECTION_INPUT_SOURCE_INPUT_SIDE_PACKET_NAME =
            "use_face_detection_input_source";
    private static final boolean USE_FACE_DETECTION_INPUT_SOURCE = false;

    private static final String SELECTED_EFFECT_ID_INPUT_STREAM_NAME = "selected_effect_id";
    private final Object effectSelectionLock = new Object();
    private int selectedEffectId = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        previewDisplayView = new SurfaceView(this);

        setupPreviewDisplayView();

        // Initialize asset manager so that MediaPipe native libraries can access the app assets, e.g.,
        // binary graphs.
        AndroidAssetUtil.initializeNativeAssetManager(this);
        eglManager = new EglManager(null);
        processor =
                new FrameProcessor(this,
                        eglManager.getNativeContext(),
                        BINARY_GRAPH_NAME, INPUT_VIDEO_STREAM_NAME,
                        OUTPUT_VIDEO_STREAM_NAME);
        processor.getVideoSurfaceOutput().setFlipY(FLIP_FRAMES_VERTICALLY);
        Map<String, Packet> inputSidePackets = new HashMap<>();
        inputSidePackets.put(
                USE_FACE_DETECTION_INPUT_SOURCE_INPUT_SIDE_PACKET_NAME,
                processor.getPacketCreator().createBool(USE_FACE_DETECTION_INPUT_SOURCE));
        processor.setInputSidePackets(inputSidePackets);
        processor.setOnWillAddFrameListener(
                (timestamp) -> {
                    Packet selectedEffectIdPacket = null;
                    try {
                        synchronized (effectSelectionLock) {
                            selectedEffectIdPacket = processor.getPacketCreator().createInt32(selectedEffectId);
                        }

                        processor
                                .getGraph()
                                .addPacketToInputStream(
                                        SELECTED_EFFECT_ID_INPUT_STREAM_NAME, selectedEffectIdPacket, timestamp);
                    } catch (RuntimeException e) {
                        Log.e(
                                TAG, "Exception while adding packet to input stream while switching effects: " + e);
                    } finally {
                        if (selectedEffectIdPacket != null) {
                            selectedEffectIdPacket.release();
                        }
                    }
                });
        PermissionHelper.checkAndRequestCameraPermissions(this);
    }

    @Override
    protected void onResume() {
        super.onResume();
        converter = new ExternalTextureConverter(eglManager.getContext());
        converter.setFlipY(FLIP_FRAMES_VERTICALLY);
        converter.setConsumer(processor);
        if (PermissionHelper.cameraPermissionsGranted(this)) {
            startCamera();
        }
    }

    @Override
    protected void onPause() {
        super.onPause();
        converter.close();
    }

    @Override
    public void onRequestPermissionsResult(
            int requestCode, String[] permissions, int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        PermissionHelper.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    private void setupPreviewDisplayView() {
        previewDisplayView.setVisibility(View.GONE);
        ViewGroup viewGroup = findViewById(R.id.preview_display_layout);
        viewGroup.addView(previewDisplayView);
        previewDisplayView
                .getHolder()
                .addCallback(
                        new SurfaceHolder.Callback() {
                            @Override
                            public void surfaceCreated(SurfaceHolder holder) {
                                processor.getVideoSurfaceOutput().setSurface(holder.getSurface());
                            }

                            @Override
                            public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
                                // (Re-)Compute the ideal size of the camera-preview display (the area that the
                                // camera-preview frames get rendered onto, potentially with scaling and rotation)
                                // based on the size of the SurfaceView that contains the display.
                                Size viewSize = new Size(width, height);
                                Size displaySize = cameraHelper.computeDisplaySizeFromViewSize(viewSize);

                                // Connect the converter to the camera-preview frames as its input (via
                                // previewFrameTexture), and configure the output width and height as the computed
                                // display size.
                                converter.setSurfaceTextureAndAttachToGLContext(
                                        previewFrameTexture, displaySize.getWidth(), displaySize.getHeight());
                            }

                            @Override
                            public void surfaceDestroyed(SurfaceHolder holder) {
                                processor.getVideoSurfaceOutput().setSurface(null);
                            }
                        });
    }

    private void startCamera() {
        cameraHelper = new CameraXPreviewHelper();
        cameraHelper.setOnCameraStartedListener(
                surfaceTexture -> {
                    previewFrameTexture = surfaceTexture;
                    // Make the display view visible to start showing the preview. This triggers the
                    // SurfaceHolder.Callback added to (the holder of) previewDisplayView.
                    previewDisplayView.setVisibility(View.VISIBLE);
                });
        cameraHelper.startCamera(this, CAMERA_FACING, /*surfaceTexture=*/ null,null);
    }
}
```

**console wrong:**
```
I/native: I20210416 11:38:21.461977 26260 resource_util_android.cc:87] Successfully loaded: face_detection_front.tflite
E/tflite: Following operations are not supported by GPU delegate:
    DEQUANTIZE: 
    164 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
```
**source uploaded github:**
https://github.com/cjl84914/face_effect_android

**download aar file url:**
 https://pan.baidu.com/s/1DyhMfzJK5FQswDz6LK6VdQ     code: 5kxp

**Comment by sgowroji** [comment]
Duplicate issue https://github.com/google/mediapipe/issues/1311

**Comment by cjl84914** [comment]
@sgowroji  thanks.   but this error about mediapipe 0.8.3.2,  not issue #1311, old version not have error.

**Comment by mcclanahoochie** [comment]
the DEQUANTIZE message can be ignored.

**Comment by cjl84914** [comment]
@mcclanahoochie  thank you, this demo error, how can i do better?

**Comment by sgowroji** [comment]
Hi @cjl84914, Can you share us the crash logs.

**Comment by cjl84914** [comment]
@sgowroji 
`04/27 15:19:28: Launching 'app' on Physical Device.
Install successfully finished in 8 s 271 ms.
$ adb shell am start -n "com.example.myfacedetectionapp/com.example.myfacedetectionapp.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 20706 on device 'huawei-oxf_an00-8UJDU19B22003185'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/acedetectionap: Late-enabling -Xcheck:jni
E/acedetectionap: Unknown bits set in runtime_flags: 0x8000
I/acedetectionap: Reinit property: dalvik.vm.checkjni= false
    ReInitProperties: persist.vm.debug.dumpapi= false
D/ActivityThread: Attach thread to application
I/ActivityThread: Init compatible state: true
D/HwFrameworkSecurityPartsFactory: HwFrameworkSecurityPartsFactory in.
I/HwFrameworkSecurityPartsFactory: add HwFrameworkSecurityPartsFactory to memory.
D/BehaviorCollectManager: hook process for AI virus second
I/BehaviorCollectManager: bindAnalyzerService: huawei.android.security.IAppBehaviorDataAnalyzer$Stub$Proxy@f18402e pid:20706
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.example.myfacedetectionapp#10160#256
    need clear apicache,because volumes changed,oldCnt=0 newCnt=1
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.example.myfacedetectionapp#10160#0
    need clear apicache,because volumes changed,oldCnt=1 newCnt=1
I/ActivityThread: finishPreloaded preloadStatus 0
D/OpenGLRenderer: disableOutlineDraw is true
I/HwPartIawareFactory: add android.common.HwPartIawareFactoryImpl to memory.
I/AwareBitmapCacher: init processName:com.example.myfacedetectionapp pid=20706 uid=10160
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@8c15065
V/ActivityThread: callActivityOnCreate
I/DecorView[]:  old windowMode:0 new windoMode:1
I/OverScrollerOptimization: start init SmartSlideOverScroller and get the overscroller config
    get the overscroller config
W/acedetectionap: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/acedetectionap: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/native: I20210427 15:20:08.654327 20706 asset_manager_util.cc:59] Created global reference to asset manager.
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
I/iGraphics: [0020080c] pn: com.example.myfacedetectionapp, p: 20706
    [0030080c] no spt app: com.example.myfacedetectionapp
I/: [CAF] out_sc_config: sc_enable=1, max_size=3670016 
    [CAF] sc_policy[0] = 0x0
    [CAF] sc_policy[1] = 0x0
    [CAF] sc_policy[2] = 0x0
    [CAF] sc_policy[3] = 0x0
I/: package[com.example.myfacedetectionapp] pid[20706] game[0]
E/libEGL: validate_display:103 error 3008 (EGL_BAD_DISPLAY)
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
I/native: I20210427 15:20:08.666584 20706 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 4
I/native: I20210427 15:20:08.671277 20931 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 v1.r18p0-01rel0.91256554b836fb72cce9d96d095364da)
D/PermissionHelper: checkAndRequestCameraPermissions
D/ActivityThread: add activity client record, r= ActivityRecord{c3319af token=android.os.BinderProxy@27587cf {com.example.myfacedetectionapp/com.example.myfacedetectionapp.MainActivity}} token= android.os.BinderProxy@27587cf
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
D/GlThread: Starting GL thread ExternalTextureConverter
I/HwPartMagicWindowFactory: add android.common.HwPartMagicWindowFactoryImpl to memory.
I/HwPartPowerOfficeFactory: add HwPartPowerOfficeFactoryImpl to memory.
D/InputEventReceiver: dispatchInputInterval 1000000
I/RmeSchedManager: init Rme, version is: v1.0
D/GlThread: Stopping GL thread ExternalTextureConverter
D/OpenGLRenderer: disableOutlineDraw is true
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/HiTouch_PressGestureDetector: onAttached, package=com.example.myfacedetectionapp, windowType=1, mHiTouchRestricted=false
D/HwForceDark: [SetDarkThemeInfo] enable = [0], appType = [0], winWidth = [1080]
W/Gralloc3: mapper 3.x is not supported
D/RtgSchedIpcFile: setCommandByIoctl failed ret:-1, cmdid:21, errno:101
I/HwViewRootImpl: removeInvalidNode jank list is null
D/RtgSched: resetRtgSchedHandle failed enable:1
D/RtgSched: resetRtgSchedHandle failed enable:0
D/ZrHung.AppEyeUiProbe: not watching, wait.
D/ActivityThread: Won't deliver top position change in state=4
D/PermissionHelper: onRequestPermissionsResult
    android.permission.CAMERA permission granted.
D/ZrHung.AppEyeUiProbe: restart watching
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
D/GlThread: Starting GL thread ExternalTextureConverter
D/DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
W/InputMethodManager: startInputReason = 1
W/InputMethodManager: startInputReason = 5
I/CameraManagerGlobal: Connecting to camera service
D/CameraRepository: Added camera: 0
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository: Added camera: 1
D/UseCaseAttachState: Active and attached use case: [] for camera: 0
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository: Added camera: 2
D/UseCaseAttachState: Active and attached use case: [] for camera: 1
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository: Added camera: 3
D/UseCaseAttachState: Active and attached use case: [] for camera: 2
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository: Added camera: 4
D/UseCaseAttachState: Active and attached use case: [] for camera: 3
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository: Added camera: 5
D/UseCaseAttachState: Active and attached use case: [] for camera: 4
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository: Added camera: 6
D/UseCaseAttachState: Active and attached use case: [] for camera: 5
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/UseCaseAttachState: Active and attached use case: [] for camera: 6
D/CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
D/DeferrableSurface: Surface created[total_surfaces=1, used_surfaces=0](androidx.camera.core.SurfaceRequest$2@56ddeba}
D/CameraXPreviewHelper: Received surface request for resolution 1280x720
D/CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
D/UseCaseAttachState: Active and attached use case: [] for camera: 1
D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-cf4ab4c5-1337-43b3-a84a-59596ab1b74e266497871] for camera: 1
D/UseCaseAttachState: Active and attached use case: [androidx.camera.core.Preview-cf4ab4c5-1337-43b3-a84a-59596ab1b74e266497871] for camera: 1
D/CameraStateRegistry: tryOpenCamera(Camera@37274b4[id=1]) [Available Cameras: 1, Already Open: false (Previous state: null)] --> SUCCESS
D/CameraXPreviewHelper: Providing surface
D/CameraStateRegistry: Recalculating open cameras:
    Camera                                       State                 
    -------------------------------------------------------------------
    Camera@f565e02[id=4]                         UNKNOWN               
    Camera@8cbcb9e[id=2]                         UNKNOWN               
    Camera@37274b4[id=1]                         OPENING               
    Camera@6cb3a7c[id=5]                         UNKNOWN               
    Camera@866681[id=6]                          UNKNOWN               
    Camera@952a7fa[id=0]                         UNKNOWN               
    Camera@852db38[id=3]                         UNKNOWN               
    -------------------------------------------------------------------
    Open count: 1 (Max allowed: 1)
D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-cf4ab4c5-1337-43b3-a84a-59596ab1b74e266497871] for camera: 1
I/CameraManager: open camera: 1, package name: com.example.myfacedetectionapp
D/UseCaseAttachState: Active and attached use case: [androidx.camera.core.Preview-cf4ab4c5-1337-43b3-a84a-59596ab1b74e266497871] for camera: 1
D/CameraStateRegistry: Recalculating open cameras:
    Camera                                       State                 
    -------------------------------------------------------------------
    Camera@f565e02[id=4]                         UNKNOWN               
    Camera@8cbcb9e[id=2]                         UNKNOWN               
    Camera@37274b4[id=1]                         OPEN                  
    Camera@6cb3a7c[id=5]                         UNKNOWN               
    Camera@866681[id=6]                          UNKNOWN               
    Camera@952a7fa[id=0]                         UNKNOWN               
    Camera@852db38[id=3]                         UNKNOWN               
    -------------------------------------------------------------------
    Open count: 1 (Max allowed: 1)
D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-cf4ab4c5-1337-43b3-a84a-59596ab1b74e266497871] for camera: 1
D/DeferrableSurface: New surface in use[total_surfaces=1, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@56ddeba}
    use count+1, useCount=1 androidx.camera.core.SurfaceRequest$2@56ddeba
D/CaptureSession: Opening capture session.
D/CaptureSession: Attempting to send capture request onConfigured
    Issuing request for session.
D/CaptureSession: CameraCaptureSession.onConfigured() mState=OPENED
D/CaptureSession: CameraCaptureSession.onReady() OPENED
W/Gralloc3: allocator 3.x is not supported
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
D/CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/ExternalTextureConv: Created output texture: 2 width: 720 height: 1280
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
I/native: I20210427 15:20:10.525943 21238 graph.cc:475] Start running the graph, waiting for inputs.
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
I/native: I20210427 15:20:10.526152 21238 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 4
I/native: I20210427 15:20:10.528470 21346 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 v1.r18p0-01rel0.91256554b836fb72cce9d96d095364da)
I/native: I20210427 15:20:10.532434 20931 resource_util_android.cc:87] Successfully loaded: face_detection_front.tflite
I/tflite: Initialized TensorFlow Lite runtime.
I/tflite: Created TensorFlow Lite delegate for GPU.
E/tflite: Following operations are not supported by GPU delegate:
    DEQUANTIZE: 
    164 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
D/ExternalTextureConv: Created output texture: 4 width: 720 height: 1280
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
I/native: I20210427 15:20:10.560541 21345 jni_util.cc:41] GetEnv: not attached
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
I/native: I20210427 15:20:10.597136 21341 jni_util.cc:41] GetEnv: not attached
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
I/native: I20210427 15:20:10.638722 21344 jni_util.cc:41] GetEnv: not attached
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
I/native: I20210427 15:20:10.751435 21340 jni_util.cc:41] GetEnv: not attached
I/native: I20210427 15:20:10.791033 21338 jni_util.cc:41] GetEnv: not attached
I/native: I20210427 15:20:10.830927 21343 jni_util.cc:41] GetEnv: not attached
I/native: I20210427 15:20:10.909360 21342 jni_util.cc:41] GetEnv: not attached
I/native: I20210427 15:20:11.119069 20931 resource_util_android.cc:87] Successfully loaded: face_detection_front.tflite
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 21341 (Thread-13), pid 20706 (acedetectionapp)
E/tflite: Following operations are not supported by GPU delegate:
    DEQUANTIZE: 
    164 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
I/native: I20210427 15:20:11.467945 21339 jni_util.cc:41] GetEnv: not attached
D/ExternalTextureConv: Created output texture: 6 width: 720 height: 1280
D/ExternalTextureConv: Created output texture: 6 width: 720 height: 1280
I/native: I20210427 15:20:11.626473 20931 resource_util_android.cc:87] Successfully loaded: face_landmark.tflite
D/ExternalTextureConv: Created output texture: 6 width: 720 height: 1280
D/ExternalTextureConv: Created output texture: 6 width: 720 height: 1280
D/ExternalTextureConv: Created output texture: 6 width: 720 height: 1280
D/ExternalTextureConv: Created output texture: 6 width: 720 height: 1280
D/ExternalTextureConv: Created output texture: 6 width: 720 height: 1280
D/ExternalTextureConv: Created output texture: 6 width: 720 height: 1280
D/ExternalTextureConv: Created output texture: 6 width: 720 height: 1280
D/ExternalTextureConv: Created output texture: 6 width: 720 height: 1280
E/RtgSchedManager: endActivityTransaction: margin state not match
D/GlThread: Stopping GL thread ExternalTextureConverter
`

**Comment by cjl84914** [comment]
@mcclanahoochie  @jiuqiant  @sgowroji  thank you very much!

**Comment by PeterTF656** [comment]
@cjl84914 Hi it seems I ran into a similar problem. What's your answer?

**Comment by sgowroji** [comment]
Hi @cjl84914, Could you please share your resolution, That will really help the community with similar errors. Thanks!

**Comment by cgowthamanmca** [comment]
@cjl84914 Can please share latest github link
