### ISSUE TITLE
Installation error Anaconda

### ISSUE THREAD

**Issue by Anonymous7code** [google/mediapipe#1894]
`PS E:\Github\Ml\OpenCV> conda install mediapipe
Collecting package metadata (current_repodata.json): done
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - mediapipe

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

**Comment by sgowroji** [comment]
Hi @Anonymous7code, Could you please elaborate your use case with complete details. And what are the steps to get the above error.

**Comment by Anonymous7code** [comment]
Hey @sgowroji, I tried installing mediapipe through `conda install mediapipe` in a virtual environment, but this threw an error mentioned below:

PS E:\Github\Ml\OpenCV> conda install mediapipe
Collecting package metadata (current_repodata.json): done
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

-mediapipe

Current channels:

-https://repo.anaconda.com/pkgs/main/win-64
-https://repo.anaconda.com/pkgs/main/noarch
-https://repo.anaconda.com/pkgs/r/win-64
-https://repo.anaconda.com/pkgs/r/noarch
-https://repo.anaconda.com/pkgs/msys2/win-64
-https://repo.anaconda.com/pkgs/msys2/noarch
To search for alternate channels that may provide the conda package you're
looking for, navigate to

https://anaconda.org
and use the search bar at the top of the page.

Though After trying this using `pip install mediapipe` it worked for me.

I tried fixing this in conda by creating different virtual environment but as usual it didn't worked for me.

**Comment by jiuqiant** [comment]
That's expected. MediaPipe Python packages are hosted by PyPI not Anaconda. So `conda install` can't find it from the Anaconda repo.

**Comment by Captain272** [comment]
I think the mediapipe is only available at python version 2.6 which the anaconda is working.
So. after opening the anaconda prompt then type.
pip install mediapipe
this worked fine for me in anaconda prompt. But not on my windows Command prompt.

**Comment by Randrita** [comment]
@belelaritra thanks!

**Comment by arnaublanco** [comment]
It didn't work for me...

<img width="583" alt="Screenshot 2022-01-05 at 00 19 26" src="https://user-images.githubusercontent.com/8408687/148137013-79ae7451-1fca-4335-aa67-d052c3762745.png">
