### ISSUE TITLE
open camera slowly on Android projects

### ISSUE THREAD

**Issue by bugmany** [google/mediapipe#1897]
when i run faceeffect app on android platform, i found open camera is slowly (about 2 ~ 3 seconds), and ios run quickly(within 1 second), then i download android app [face_mesh](https://google.github.io/mediapipe/solutions/face_mesh), the result still open camera slowly. 
could anyone tell me how to optimize it?
thanks.

**Comment by sgowroji** [comment]
Hi @bugmany, Could you provide a video and device details with configuration in which you are trying. 
If you added any changes on top of it, Please share the code repo. Thanks!

**Comment by bugmany** [comment]
hi @sgowroji ,
my android phone:
model: vivo S1(4+128G)
android version: 10
kernel: 4.14.141+

**Comment by sgowroji** [comment]
Hi @bugmany, Could you please attach a video as mentioned above. Thanks

**Comment by badushaebrahim** [comment]
@bugmany bro  we're u able to complete sync
Of bazel for buliding apk

**Comment by bugmany** [comment]
hi @sgowroji and @badushaebrahim ,
i'll retry and analyzing it, thanks.

**Comment by HMY314** [comment]
> hi @sgowroji and @badushaebrahim ,
> i'll retry and analyzing it, thanks.

Hello, I also encountered the same problem. How did you solve this problem?
