### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'bazel_skylib'

### ISSUE THREAD

**Issue by ansixwu** [google/mediapipe#19]
java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/archive/2169ae1c374aab4a09aa90e65efe1a3aad4e279b.tar.gz] to /home/dm/.cache/bazel/_bazel_dm/b9f01b7215a9069d20c31caab49bdce8/external/bazel_skylib/2169ae1c374aab4a09aa90e65efe1a3aad4e279b.tar.gz: GET returned 404 Not Found

Have someone met this situation when bazel the project?
I can't access some links in the build e.g.https://github.com/bazelbuild/bazel-skylib/archive/2169ae1c374aab4a09aa90e65efe1a3aad4e279b.tar.gz

**Comment by jiuqiant** [comment]
@ansixwu see https://github.com/google/mediapipe/issues/3
Some links may be temporarily unavailable. The problem probably can be solved by retrying the Bazel command. If you would like to cache the external dependencies, see https://github.com/google/mediapipe/issues/3#issuecomment-506926022

**Comment by ansixwu** [comment]
> @ansixwu see #3
> Some links may be temporarily unavailable. The problem probably can be solved by retrying the Bazel command. If you would like to cache the external dependencies, see [#3 (comment)](https://github.com/google/mediapipe/issues/3#issuecomment-506926022)

My ubuntu desktop has VPN but has the same probloms . I also follow the commands in your former workflows but I still solve it

**Comment by jiuqiant** [comment]
> > @ansixwu see #3
> > Some links may be temporarily unavailable. The problem probably can be solved by retrying the Bazel command. If you would like to cache the external dependencies, see [#3 (comment)](https://github.com/google/mediapipe/issues/3#issuecomment-506926022)
> 
> My ubuntu desktop has VPN but has the same probloms . I also follow the commands in your former workflows but I still solve it

It's weird. https://github.com/bazelbuild/bazel-skylib/archive/2169ae1c374aab4a09aa90e65efe1a3aad4e279b.tar.gz is hosted by GitHub and shouldn't be blocked by the Great FireWall. I believe it's temporarily network issue. Could you retry it later? Thanks!
