### ISSUE TITLE
Convolution2DTransposeBias - Explanation

### ISSUE THREAD

**Issue by SanthoshRajendiran** [google/mediapipe#190]
Hi,
With regards to the hair segmentation model being used in the repository, I would like to know about the [Convolution2DTransposeBias implementation](https://github.com/jingruhou/mediapipe-master/blob/master/mediapipe/util/tflite/operations/transpose_conv_bias.cc). 
The implementation as I read, you have mentioned that you did modifications to the transpose convolution used by tensorflow as it is, to support bias. What is the major difference between transpose convolution in Tensorflow, and Convolution2DTransposeBias of mediapipe, when Tensorflow as it is, allows bias with transpose convolution. If there are any major differences, could you share the python source of Convolution2DTransposeBias. And will there by any difference in using Transpose Convolution of Tensorflow in place of Convolution2DTransposeBias.

**Comment by SanthoshRajendiran** [comment]
Are there any updates about the operator and its usage??

**Comment by mcclanahoochie** [comment]
Hi, please see https://github.com/google/mediapipe/issues/245#issuecomment-555227438
