### ISSUE TITLE
Unable to create bounding box using hand_rects

### ISSUE THREAD

**Issue by Thurguild** [google/mediapipe#1900]
Hi, 

I've followed the instructions as per issue #1507 that alters the build file and outputs, however I am still getting an issue of 
  File "test-mediapipe-hands.py", line 37, in <module>
    for rect in results.hands_rects:
AttributeError: type object 'SolutionOutputs' has no attribute 'hands_rects'

This is running from a Conda 3.8 env and allows for the main examples to be run however runs into issues when the hand bounding boxes are attempted to be included.

**Comment by jiuqiant** [comment]
hand_rects or hands_rects?

**Comment by Thurguild** [comment]
I thought I might have made a rather major mistake so I checked but even using hand_rects it gives this error: 
 File "test-mediapipe-hands.py", line 37, in <module>
    for rect in results.hand_rects:
AttributeError: type object 'SolutionOutputs' has no attribute 'hand_rects'

**Comment by jiuqiant** [comment]
Other people reported back that is working. So I am not sure what's going wrong here. Can you go to python/site-packages/mediapipe/python/solutions/hands.py to verify if hand_rects is indeed added to the outputs list?

**Comment by Thurguild** [comment]
For the hands.py I've got the following code saved for the outputs
           min_tracking_confidence,
        },
	outputs=['multi_hand_landmarks', 'multi_handedness', 'hand_rects']
	)
and to display those results I have this code 

results = hands.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    for rect in results.hand_rects:
      print(rects)

**Comment by Thurguild** [comment]
Have also tried to reset the env but keep running into the issue of gen_protos not having permissions to alter the protoc directory which then stops the bdist wheel command being effective

**Comment by RyanPaulMcKenna** [comment]
is the hand_rects attribute from an earlier version perhaps? I cannot find any documentation on this.

**Comment by RyanPaulMcKenna** [comment]
> Have also tried to reset the env but keep running into the issue of gen_protos not having permissions to alter the protoc directory which then stops the bdist wheel command being effective

I have the exact same problem
