### ISSUE TITLE
How to use drawing utilities on pose landmarks from CSV

### ISSUE THREAD

**Issue by suarezjessie** [google/mediapipe#1901]
I saved the output keypoints of `mp_pose` to a CSV file. Currently, I want to use the `mp_drawing.draw_landmarks` on these extracted set of keypoints. I understand that the function for `mp_drawing.draw_landmarks` needs to have the `mediapipe.framework.formats.landmark_pb2.NormalizedLandmarkList` as an input. However, I don't know how I can invoke or use this class for my saved normalized coordinates. I'm using Python. Thanks!

**Comment by sgowroji** [comment]
Hi @suarezjessie, You can try using `mp_drawing = mp.solutions.drawing_utils` to work with drawing utilities. Thanks!
