### ISSUE TITLE
object detection with python possible with mediapipe? links to example-code?

### ISSUE THREAD

**Issue by ozett** [google/mediapipe#1903]
hi, 
can i do object detection with mediapipe in python?

there is no object-detection example here (but others):
https://github.com/google/mediapipe/tree/master/mediapipe/python/solutions

i am no professional coder, but i tried face- and pose-detection with python from the examples successfully.
there aren't any questions about python-code for object here in the issues. nobody uses python - or is it not possible?

thanks,
ozett

----edit: 
Does this means there is no object detection with mediapipe in python possible? Are there other ways?

https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/__init__.py#L15

```
import mediapipe.python.solutions.drawing_utils
import mediapipe.python.solutions.face_detection
import mediapipe.python.solutions.face_mesh
import mediapipe.python.solutions.hands
import mediapipe.python.solutions.holistic
import mediapipe.python.solutions.objectron
import mediapipe.python.solutions.pose
```

**Comment by chuoling** [comment]
> ----edit:
> Does this means there is no object detection with mediapipe in python possible? Are there other ways?
> 
> https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/__init__.py#L15
> 
> ```
> import mediapipe.python.solutions.drawing_utils
> import mediapipe.python.solutions.face_detection
> import mediapipe.python.solutions.face_mesh
> import mediapipe.python.solutions.hands
> import mediapipe.python.solutions.holistic
> import mediapipe.python.solutions.objectron
> import mediapipe.python.solutions.pose
> ```

This is simply because we have been focusing on other solutions (above), and haven't had a chance to revisit object detection, which is one of the earliest solutions we released. A Python solution API for object detection is certainly feasible, and we will mark this as a feature request.

**Comment by HungDuong1998** [comment]
+1
I am too interested in the python solution, would be nice if there is any update on it.

**Comment by ozett** [comment]
saved from getting closed after stalled-botting. thanks

**Comment by jiuqiant** [comment]
A Google Summer of Code student made an objection detection API in a sepreate repo. See https://blog.aniketiq.me/python-api-for-the-mediapipe-object-detection-solution and https://github.com/aniketiq/mediapipe/blob/ObjectDetectionSolution/mediapipe/python/solutions/object_detection.py for more details.

**Comment by HungDuong1998** [comment]
> A Google Summer of Code student made an objection detection API in a sepreate repo. See https://blog.aniketiq.me/python-api-for-the-mediapipe-object-detection-solution and https://github.com/aniketiq/mediapipe/blob/ObjectDetectionSolution/mediapipe/python/solutions/object_detection.py for more details.

Thanks, it works like a charm.
Have we got the tracking API yet? I see the detection only model inference in video is quite slow, would be great if it can be accelerated with the tracking solution

**Comment by ozett** [comment]
i have an old mediapipe 0.8.3.1 in virtual-env that dont know about object-detection.

my history told me i did it like this in february, hard to remember details, running fine since:
```
mkvirtualenv mp
pip install mediapipe
```

[The fork](https://blog.aniketiq.me/python-api-for-the-mediapipe-object-detection-solution) tells me to install normal media-pipe (seems 8.4) for use obj-det. (the fork has no isues to ask anything there...)

is that correct? 
or do i have to checkout the fork an build all by myself again?

**Comment by HungDuong1998** [comment]
Yes you will need to build your own wheel from source. 
Check the commits, copy the codes needed for your object detection (the last 3 commits are enough).

**Comment by HungDuong1998** [comment]
But without the object tracking, the detection alone performance is not too impressive, there are better models updated very fast by the community. 2014 SSD seems quite old in 2021 already. So I will need to find the mediapipe object tracking python API or build it my own somehow

**Comment by HungDuong1998** [comment]
This mediapipe repo is more like a tool, an API generator where you try and create your own pipeline, put your own model into the solutions. But it will take time to learn on how to do those as you skim through the documentations.

For the detection task, normally people come to Machine Learning starting with a more primitive and native models like the traditional HOG in combination with an SVM classification (there are native opencv apis for them, both in python and c++). But the more I dig into those traditional models the more I see deep learning models are much better and powerful in image processing. That's why I switch to deep learning models. (IMO)

You can try and google some opensource models out there. There are primarily 2 approaches in this detection task with deeplearning: 2 steps (RCNN) and 1 step (YOLO, SSD mobilenet). 

1 step approaches are faster as a trade off for accuracy. My go to is 1 step with the most popular YOLO or SSD mobilenet models trained on the popular COCO dataset.

**Comment by HungDuong1998** [comment]
But before accepting whatever I say, I am also a newbie in the field and is only a technology user started researching the field for only 1 month till now, not some PhD with deep knowledge so take it with a grain of salt. Good luck haha

**Comment by fgadaleta** [comment]
Why isn't this merged to main branch?

**Comment by ramthiagu10** [comment]
> > A Google Summer of Code student made an objection detection API in a sepreate repo. See https://blog.aniketiq.me/python-api-for-the-mediapipe-object-detection-solution and https://github.com/aniketiq/mediapipe/blob/ObjectDetectionSolution/mediapipe/python/solutions/object_detection.py for more details.
> 
> Thanks, it works like a charm. Have we got the tracking API yet? I see the detection only model inference in video is quite slow, would be great if it can be accelerated with the tracking solution

Please help me with the installation. I tried with pip installation but, it shows fatal error. 

pip install -e git+https://github.com/aniketiq/mediapipe/tree/ObjectDetectionSolution#egg=mediapipe

Obtaining mediapipe from git+https://github.com/aniketiq/mediapipe/tree/ObjectDetectionSolution#egg=mediapipe
  Cloning https://github.com/aniketiq/mediapipe/tree/ObjectDetectionSolution (to revision master) to ./new_env/src/mediapipe
  Running command git clone -q https://github.com/aniketiq/mediapipe/tree/ObjectDetectionSolution /home/ram/Music/obj_detect_latest/new_env/src/mediapipe
  remote: Not Found
  fatal: repository 'https://github.com/aniketiq/mediapipe/tree/ObjectDetectionSolution/' not found
ERROR: Command errored out with exit status 128: git clone -q https://github.com/aniketiq/mediapipe/tree/ObjectDetectionSolution /home/ram/Music/obj_detect_latest/new_env/src/mediapipe Check the logs for full command output.
