### ISSUE TITLE
MediaPipe on Android

### ISSUE THREAD

**Issue by mithunbabbira** [google/mediapipe#1904]
Is there any guide to use MediaPipe on android studio

**Comment by fahadhaq** [comment]
There is a section on the media pipe site.

https://google.github.io/mediapipe/getting_started/android.html#option-2-build-with-bazel-in-android-studio

**Comment by sgowroji** [comment]
Hi @mithunbabbira, We have clear documentation for Android [here](https://google.github.io/mediapipe/getting_started/android.html#mediapipe-on-android). And also an [Helloworld](https://google.github.io/mediapipe/getting_started/hello_world_android.html) Example in mediapipe.

**Comment by sgowroji** [comment]
Hi @mithunbabbira, Did you get a chance to go through the above comment. Thanks!

**Comment by mithunbabbira** [comment]
Yes, thank you..

**Comment by sgowroji** [comment]
Assuming you are question is answered. We are closing this ticket. Thanks!
