### ISSUE TITLE
Android Studio //i am noob

### ISSUE THREAD

**Issue by Jaguaribe21** [google/mediapipe#191]
Can it run with an API less than 28, for example API 25?

**Comment by jiuqiant** [comment]
Yes, you can set the api_level in android_ndk_repository and android_sdk_repository in [the WORKSPACE file](https://github.com/google/mediapipe/blob/master/WORKSPACE). For example, to make the cpu demos work on a Google Nexus 5 with Android 6,  we need to set the api_level of android_ndk_repository to be 21. See more details in https://github.com/google/mediapipe/issues/178#issuecomment-547619564.
