### ISSUE TITLE
[MediaPipeVisualizer] Cannot select multiple .pbtxt files at once

### ISSUE THREAD

**Issue by Takuro-Ito** [google/mediapipe#1910]
As described in https://google.github.io/mediapipe/tools/visualizer.html#visualizing-subgraphs, multiple files are supposed to be selected and uploaded at once. However, only a file could be selected.

I guess the cause is missing `multiple` attribute in `input` tag in https://viz.mediapipe.dev/app_bundle.js.

```diff
# https://viz.mediapipe.dev/app_bundle.js 

function dZ(a, b) {
    var c = document.createElement("input");
    c.setAttribute("type", "file");
    c.setAttribute("name", "file");
+   c.setAttribute("multiple", "");   # This should be added to support multiple file selection?
    c.setAttribute("accept", a);
    c.style.display = "none";
    c.addEventListener("input", function(d) {
        d = d.target.files;
        for (var e = [], f = 0; f < d.length; f++)
            e.push(d[f]);
        b(e)
    });
    document.body.appendChild(c);
    c.click();
    document.body.removeChild(c)
}
```

Any temporally solutions until it will be fixed?

**Comment by Takuro-Ito** [comment]
@mhays-google Any update or workaround to select multiple files at once on MacOS?

**Comment by kuaashish** [comment]
Hello @Takuro-Ito,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
