### ISSUE TITLE
Build hair_segmentation failed for ruy matrix on Raspberry.

### ISSUE THREAD

**Issue by kuangzy2011** [google/mediapipe#1911]
The hello world example works fine, while failed when building hair_segmentation, could any one help on this?

ERROR: /home/worker/workspace/download/mediapipe/mediapipe/examples/desktop/hair_segmentation/BUILD:28:10: Linking of rule '//mediapipe/examples/desktop/hair_segmentation:hair_segmentation_cpu' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/arm-opt/bin/mediapipe/examples/desktop/hair_segmentation/hair_segmentation_cpu-2.params

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc @bazel-out/arm-opt/bin/mediapipe/examples/desktop/hair_segmentation/hair_segmentation_cpu-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/arm-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/neon_tensor_utils/neon_tensor_utils.o:neon_tensor_utils.cc:function ruy::RunKernel<ruy::Kernel<(ruy::Path)16, signed char, signed char, int, int> >::Run(ruy::Tuning, ruy::SidePair<ruy::PEMat> const&, void const*, ruy::SidePair<int> const&, ruy::SidePair<int> const&, ruy::EMat*): error: undefined reference to 'ruy::Kernel8bitNeon(ruy::KernelParams8bit<4, 2> const&)'
bazel-out/arm-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/neon_tensor_utils/neon_tensor_utils.o:neon_tensor_utils.cc:function ruy::RunKernel<ruy::Kernel<(ruy::Path)16, signed char, signed char, int, int> >::Run(ruy::Tuning, ruy::SidePair<ruy::PEMat> const&, void const*, ruy::SidePair<int> const&, ruy::SidePair<int> const&, ruy::EMat*): error: undefined reference to 'ruy::Kernel8bitNeon1Col(ruy::KernelParams8bit<4, 2> const&)'
bazel-out/arm-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/neon_tensor_utils/neon_tensor_utils.o:neon_tensor_utils.cc:function void ruy::RunPack<(ruy::Path)16, ruy::FixedKernelLayout<(ruy::Order)0, 16, 2>, signed char, signed char>(ruy::Tuning, ruy::EMat const&, ruy::PEMat*, int, int): error: undefined reference to 'ruy::Pack8bitColMajorForNeon2Cols(ruy::PackParams8bit const&)'
bazel-out/arm-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/neon_tensor_utils/neon_tensor_utils.o:neon_tensor_utils.cc:function void ruy::RunPack<(ruy::Path)16, ruy::FixedKernelLayout<(ruy::Order)0, 16, 2>, signed char, signed char>(ruy::Tuning, ruy::EMat const&, ruy::PEMat*, int, int): error: undefined reference to 'ruy::Pack8bitRowMajorForNeon(unsigned char const*, int, int, int, int, int, int, signed char*, int, int, int*, int, int)'
bazel-out/arm-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/neon_tensor_utils/neon_tensor_utils.o:neon_tensor_utils.cc:function void ruy::RunPack<(ruy::Path)16, ruy::FixedKernelLayout<(ruy::Order)0, 16, 2>, signed char, signed char>(ruy::Tuning, ruy::EMat const&, ruy::PEMat*, int, int): error: undefined reference to 'ruy::Pack8bitColMajorForNeon2Cols(ruy::PackParams8bit const&)'
bazel-out/arm-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/neon_tensor_utils/neon_tensor_utils.o:neon_tensor_utils.cc:function void ruy::RunPack<(ruy::Path)16, ruy::FixedKernelLayout<(ruy::Order)0, 16, 2>, signed char, signed char>(ruy::Tuning, ruy::EMat const&, ruy::PEMat*, int, int): error: undefined reference to 'ruy::Pack8bitColMajorForNeon2Cols(ruy::PackParams8bit const&)'
bazel-out/arm-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/neon_tensor_utils/neon_tensor_utils.o:neon_tensor_utils.cc:function void ruy::RunPack<(ruy::Path)16, ruy::FixedKernelLayout<(ruy::Order)0, 16, 2>, signed char, signed char>(ruy::Tuning, ruy::EMat const&, ruy::PEMat*, int, int): error: undefined reference to 'ruy::Pack8bitColMajorForNeon2Cols(ruy::PackParams8bit const&)'
bazel-out/arm-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/neon_tensor_utils/neon_tensor_utils.o:neon_tensor_utils.cc:function void ruy::RunPack<(ruy::Path)16, ruy::FixedKernelLayout<(ruy::Order)0, 16, 4>, signed char, signed char>(ruy::Tuning, ruy::EMat const&, ruy::PEMat*, int, int): error: undefined reference to 'ruy::Pack8bitColMajorForNeon4Cols(ruy::PackParams8bit const&)'
bazel-out/arm-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/neon_tensor_utils/neon_tensor_utils.o:neon_tensor_utils.cc:function void ruy::RunPack<(ruy::Path)16, ruy::FixedKernelLayout<(ruy::Order)0, 16, 4>, signed char, signed char>(ruy::Tuning, ruy::EMat const&, ruy::PEMat*, int, int): error: undefined reference to 'ruy::Pack8bitRowMajorForNeon(unsigned char const*, int, int, int, int, int, int, signed char*, int, int, int*, int, int)'
bazel-out/arm-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/neon_tensor_utils/neon_tensor_utils.o:neon_tensor_utils.cc:function void ruy::RunPack<(ruy::Path)16, ruy::FixedKernelLayout<(ruy::Order)0, 16, 4>, signed char, signed char>(ruy::Tuning, ruy::EMat const&, ruy::PEMat*, int, int): error: undefined reference to 'ruy::Pack8bitColMajorForNeon4Cols(ruy::PackParams8bit const&)'
bazel-out/arm-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/neon_tensor_utils/neon_tensor_utils.o:neon_tensor_utils.cc:function void ruy::RunPack<(ruy::Path)16, ruy::FixedKernelLayout<(ruy::Order)0, 16, 4>, signed char, signed char>(ruy::Tuning, ruy::EMat const&, ruy::PEMat*, int, int): error: undefined reference to 'ruy::Pack8bitColMajorForNeon4Cols(ruy::PackParams8bit const&)'
bazel-out/arm-opt/bin/external/org_tensorflow/tensorflow/lite/kernels/internal/_objs/neon_tensor_utils/neon_tensor_utils.o:neon_tensor_utils.cc:function void ruy::RunPack<(ruy::Path)16, ruy::FixedKernelLayout<(ruy::Order)0, 16, 4>, signed char, signed char>(ruy::Tuning, ruy::EMat const&, ruy::PEMat*, int, int): error: undefined reference to 'ruy::Pack8bitColMajorForNeon4Cols(ruy::PackParams8bit const&)'
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/hair_segmentation:hair_segmentation_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5272.179s, Critical Path: 4622.22s
INFO: 2061 processes: 155 internal, 1906 linux-sandbox.
FAILED: Build did NOT complete successfully

###########################

worker@raspberrypi:~/workspace/download/mediapipe $ gcc --version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

worker@raspberrypi:~/workspace/download/mediapipe $ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
worker@raspberrypi:~/workspace/download/mediapipe $ bazel --version
bazel 3.7.2- (@non-git)
worker@raspberrypi:~/workspace/download/mediapipe $ uname -a
Linux raspberrypi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux
worker@raspberrypi:~/workspace/download/mediapipe $

**Comment by sgowroji** [comment]
Hi @kuangzy2011, Can you share the steps followed to reproduce the above issue. Thanks !

**Comment by kuangzy2011** [comment]
@sgowroji , Here is my building process.

#WORKSPACE

new_local_repository(
    name = "linux_opencv",
    build_file = "@//third_party:opencv_linux.BUILD",
>    path = "/usr/local",
)

#third_party/opencv_linux.BUILD

cc_library(
    name = "opencv",
    srcs = glob(
        [
            #"lib/x86_64-linux-gnu/libopencv_core.so",
            #"lib/x86_64-linux-gnu/libopencv_calib3d.so",
            #"lib/x86_64-linux-gnu/libopencv_features2d.so",
            #"lib/x86_64-linux-gnu/libopencv_highgui.so",
            #"lib/x86_64-linux-gnu/libopencv_imgcodecs.so",
            #"lib/x86_64-linux-gnu/libopencv_imgproc.so",
            #"lib/x86_64-linux-gnu/libopencv_video.so",
            #"lib/x86_64-linux-gnu/libopencv_videoio.so",

>            # For OpenCV 4.x
>            "lib/libopencv_aruco.so",
>            "lib/libopencv_bgsegm.so",
>            "lib/libopencv_bioinspired.so",
>            "lib/libopencv_calib3d.so",
>            "lib/libopencv_ccalib.so",
>            "lib/libopencv_core.so",
>            "lib/libopencv_datasets.so",
>            "lib/libopencv_dnn_objdetect.so",
>            "lib/libopencv_dnn.so",
>            "lib/libopencv_dnn_superres.so",
>            "lib/libopencv_dpm.so",
>            "lib/libopencv_face.so",
>            "lib/libopencv_features2d.so",
>            "lib/libopencv_flann.so",
>            "lib/libopencv_freetype.so",
>            "lib/libopencv_fuzzy.so",
>            "lib/libopencv_gapi.so",
>            "lib/libopencv_hfs.so",
>            "lib/libopencv_highgui.so",
>            "lib/libopencv_imgcodecs.so",
>            "lib/libopencv_img_hash.so",
>            "lib/libopencv_imgproc.so",
>            "lib/libopencv_intensity_transform.so",
>            "lib/libopencv_line_descriptor.so",
>            "lib/libopencv_mcc.so",
>            "lib/libopencv_ml.so",
>            "lib/libopencv_objdetect.so",
>            "lib/libopencv_optflow.so",
>            "lib/libopencv_phase_unwrapping.so",
>            "lib/libopencv_photo.so",
>            "lib/libopencv_plot.so",
>            "lib/libopencv_quality.so",
>            "lib/libopencv_rapid.so",
>            "lib/libopencv_reg.so",
>            "lib/libopencv_rgbd.so",
>            "lib/libopencv_saliency.so",
>            "lib/libopencv_shape.so",
>            "lib/libopencv_stereo.so",
>            "lib/libopencv_stitching.so",
>            "lib/libopencv_structured_light.so",
>            "lib/libopencv_superres.so",
>            "lib/libopencv_surface_matching.so",
>            "lib/libopencv_text.so",
>            "lib/libopencv_tracking.so",
>            "lib/libopencv_videoio.so",
>            "lib/libopencv_video.so",
>            "lib/libopencv_videostab.so",
>            "lib/libopencv_wechat_qrcode.so",
>            "lib/libopencv_xfeatures2d.so",
>            "lib/libopencv_ximgproc.so",
>            "lib/libopencv_xobjdetect.so",
>.            "lib/libopencv_xphoto.so"
        ],
    ),
    hdrs = glob([
        # For OpenCV 3.x
>     #"include/opencv2/**/*.h*",
        # For OpenCV 4.x
>      "include/opencv4/opencv2/**/*.h*",
    ]),
    includes = [
        # For OpenCV 3.x
>        #"include/",
        # For OpenCV 4.x
>        "include/opencv4/",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"],
>    linkopts = ["-latomic"],
)

#building completed 100%, and finally got above errors on Pi 3B
#I tried to build ruy matrix library, but there is nothing helpful.
#build command
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hair_segmentation:hair_segmentation_cpu

**Comment by jiuqiant** [comment]
This is an error occurred in TFLite. Unfortunately, TFLite doesn't support ARM native build with Bazel: https://github.com/tensorflow/tensorflow/issues/42471#issuecomment-696529766. Feel like there is not too much we can do with this issue.

**Comment by kuangzy2011** [comment]
Thanks.
