### ISSUE TITLE
get the angle of face in facemesh in python 

### ISSUE THREAD

**Issue by hungtooc** [google/mediapipe#1912]
Hi, i have installed sample app name "Face Effect" on android. The app using  facemesh to get face angle as you can see:
![Screenshot_20210420-163522](https://user-images.githubusercontent.com/24487114/115380934-474da200-a1fd-11eb-8f4e-9459d57552c5.png)
reference: Android target: ([ prebuilt ARM64 APK)](https://drive.google.com/file/d/1ccnaDnffEuIXriBZr2SK_Eu4FpO7K44s) mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect
how can i get & draw this result on python?

**Comment by sgowroji** [comment]
Hi @hungtooc, Could you provide  use case with complete details and code repo. Thanks!

**Comment by hungtooc** [comment]
> Hi @hungtooc, Could you provide use case with complete details and code repo. Thanks!

sorry i'm not an Android coder, i just install the prebuild file app "Face Effect". I dont know where is the code to get and draw 3 coordinate axis in the image in android project. But i know they can draw x,y,z axis to describe the rotation angle on android project. How can i get the values of face rotation angle on Python.

**Comment by jiuqiant** [comment]
> > Hi @hungtooc, Could you provide use case with complete details and code repo. Thanks!
> 
> sorry i'm not an Android coder, i just install the prebuild file app "Face Effect". I dont know where is the code to get and draw 3 coordinate axis in the image in android project. But i know they can draw x,y,z axis to describe the rotation angle on android project. How can i get the values of face rotation angle on Python.

We haven't integrated the face geometry data in the Python API. Will provide updates when it becomes available.

**Comment by hungtooc** [comment]
> > > Hi @hungtooc, Could you provide use case with complete details and code repo. Thanks!
> > 
> > 
> > sorry i'm not an Android coder, i just install the prebuild file app "Face Effect". I dont know where is the code to get and draw 3 coordinate axis in the image in android project. But i know they can draw x,y,z axis to describe the rotation angle on android project. How can i get the values of face rotation angle on Python.
> 
> We haven't integrated the face geometry data in the Python API. Will provide updates when it becomes available.

nice! thank you.

**Comment by AliDjango** [comment]
any updates?i need this as well

**Comment by HWiese1980** [comment]
Me too, any news here?

**Comment by hungtooc** [comment]
> Me too, any news here?

solved it!. but sorry i can't share because commerce. This is a part in my solution shttps://mathworld.wolfram.com/EulerAngles.html

**Comment by cansik** [comment]
@jiuqiant  This is still not solved, so would be great if you could reopen it.

Wouldn't it be sufficient to add the following lines to the python build and create a new solution for it?

```python
cc_library(
    name = "builtin_calculators",
    deps = [
        ...

        "//mediapipe/modules/face_geometry:face_geometry_from_landmarks",
        "//mediapipe/modules/face_geometry/data:geometry_pipeline_metadata_landmarks",

        "//mediapipe/modules/face_geometry:face_geometry_from_detection",
        "//mediapipe/modules/face_geometry/data:geometry_pipeline_metadata_detection",
    ],
)
```

**Comment by hungtooc** [comment]
something may helpful to solve this problem:
https://stackoverflow.com/questions/18789232/rotate-a-3d-object-in-python
https://mathworld.wolfram.com/EulerAngles.html

**Comment by cansik** [comment]
@hungtooc How did you get the transformation matrix in python? I know how to rotate in 3d space, the problem is to get the transformation matrix from the landmark detection.

**Comment by hungtooc** [comment]
> @hungtooc How did you get the transformation matrix in python? I know how to rotate in 3d space, the problem is to get the transformation matrix from the landmark detection.
>> ys, zs, xs = getaxis(face.face_landmarks.landmark)

```
def getaxis(landmarks):
    xs, ys, zs = [], [], []
    landmark = list(landmarks)
    for mark in landmark:
        xs.append(mark.x)
        ys.append(mark.y)
        zs.append(mark.z)
    return xs, ys, zs
```

**Comment by cancan101** [comment]
Take a look at:
- https://github.com/cansik/mediapipe-face-geometry
- https://github.com/cansik/mediapipe-extended
For a
