### ISSUE TITLE
Question about using pose_landmark_full_body.tflite

### ISSUE THREAD

**Issue by WayneLin015** [google/mediapipe#1914]
Different to the BlazePose paper, it outputs (ld_3d) with the shape of [1,195], in my opinion and previous issue, it should be flatten refer to x, y, z, visibility, presence, so the landmark result will be 39 outputs though its different to paper said that the model output 33 landmark

Another question is, I need to apply any other post or pre processing? Now the output seem there's some shifting
The result of 39 points
![tt (2)](https://user-images.githubusercontent.com/54903379/115498966-19ba3480-a2a1-11eb-914d-cbd161429778.jpg)
With python API
![result](https://user-images.githubusercontent.com/54903379/115499101-656cde00-a2a1-11eb-82b7-8577261be1b7.jpg)

**Comment by maokk** [comment]
I have the same problem on pose_landmark_upper_body.tflite file but works ok on python API, and  I find the tflite outputs value in ld_3d are not normalized to [0~1]

Python API
![annotated_image](https://user-images.githubusercontent.com/883336/115515412-af60be80-a2b7-11eb-8bb4-3280836fea0d.png)
tflite file output
![my_testimage](https://user-images.githubusercontent.com/883336/115515552-d4553180-a2b7-11eb-86d7-fe3f5c622992.png)

**Comment by maokk** [comment]
anything update? thanks

**Comment by chaowentao** [comment]
> I have the same problem on pose_landmark_upper_body.tflite file but works ok on python API, and I find the tflite outputs value in ld_3d are not normalized to [0~1]
> 
> Python API
> ![annotated_image](https://user-images.githubusercontent.com/883336/115515412-af60be80-a2b7-11eb-8bb4-3280836fea0d.png)
> tflite file output
> ![my_testimage](https://user-images.githubusercontent.com/883336/115515552-d4553180-a2b7-11eb-86d7-fe3f5c622992.png)

@maokk @WayneLin015  How do you test the tflite model ? Can you give me the `run.py`? Now I am solving this problem. Thank you ~

**Comment by chaowentao** [comment]
@WayneLin015 The results contain 39 points, 1-33 is the pose landmark, 34-39 is auxiliary points for tracking. My tflite result is bad. So can you share your inference code? Thank you~

**Comment by sgowroji** [comment]
Hi @WayneLin015, Could you please provide the steps to reproduce the above observation mentioned in the first comment. Thanks!
