### ISSUE TITLE
Hand orientation

### ISSUE THREAD

**Issue by titoasty** [google/mediapipe#1916]
I saw there is palm detection but I can't access it in python.
Is there any way? I only saw landmarks in the docs.
Thanks

(FYI, I'm trying to find the orientation of the hand)

**Comment by sgowroji** [comment]
Hi @titoasty, Could you please elaborate your Query with clear details. What is your error and what are the steps followed to reproduce it. Thanks

**Comment by sgowroji** [comment]
Hi @titoasty, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now, Due to lack of activity.
