### ISSUE TITLE
Browser hangs during model loading

### ISSUE THREAD

**Issue by INF800** [google/mediapipe#1918]
While initalizing `new Holistic(...)` model, browser hangs for 10+ seconds with following output

```
holistic_solution_wasm_bin.js:9 I0421 21:07:14.783000       1 gl_context_webgl.cc:149] Successfully created a WebGL context with major version 3 and handle 3
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 I0421 21:07:14.786000       1 gl_context.cc:348] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)))
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 W0421 21:07:14.790000       1 gl_context.cc:802] Drishti OpenGL error checking is disabled
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 ERROR: Following operations are not supported by GPU delegate:
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 DEQUANTIZE: 
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 577 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 ERROR: Following operations are not supported by GPU delegate:
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 DEQUANTIZE: 
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 164 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
```

Is there any way to load the model without making the browser hang?
I used js solution api from https://google.github.io/mediapipe/solutions/holistic.html with zero changes.

Thanks,
Rakesh

**Comment by AmitMY** [comment]
I'm having the same issue. I was considering moving the loading to a WebWorker but did not attempt that yet, perhaps it could help.

**Comment by rakesh4real** [comment]
@AmitMY can you please share a simple code snippet that does it?

**Comment by sgowroji** [comment]
Hi @rakesh4real, Could you please share the screenshot or a video of the error. And also the steps to reproduce the above error. Thanks!

**Comment by rakesh4real** [comment]
Unfortunately, I cannot share code/video without permission from my organisation. Specifically, while sending image for the first time i.e doing -

```
await holisticModel.send({ image: videoElement });
```

will cause the following output in browser console -
```
holistic_solution_wasm_bin.js:9 I0421 21:07:14.783000       1 gl_context_webgl.cc:149] Successfully created a WebGL context with major version 3 and handle 3
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 I0421 21:07:14.786000       1 gl_context.cc:348] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)))
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 W0421 21:07:14.790000       1 gl_context.cc:802] Drishti OpenGL error checking is disabled
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 ERROR: Following operations are not supported by GPU delegate:
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 DEQUANTIZE: 
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 577 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 ERROR: Following operations are not supported by GPU delegate:
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 DEQUANTIZE: 
put_char @ holistic_solution_wasm_bin.js:9
holistic_solution_wasm_bin.js:9 164 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
```

While displaying this output in browser console, whole UI hangs for 10 seconds. After these outputs are displayed, for subsequent `await holisticModel.send({ image: videoElement });` from second time onwards, browser does not hang

**Comment by AmitMY** [comment]
Demo to show hanging: https://sign-language-processing.github.io/playground/
While it says "Loading Pose Estimation" the browser thread hangs. Try to hover things in the menu, you see that they aren't responsive

**Comment by mhays-google** [comment]
Hi there, thank you for the patience. 

When .send() is called the first time, we potentially initialize the graph.  This means loading the models (which are in the packed assets) and starting up the wasm.  For holistic, the models are... a bit large... there are three of them, in fact, and each are several megabytes in size.

We are looking at way of addressing this speed, or at the very least, giving the user an idea of how long it will take, or even notifying them of what's happening at the moment.  I had originally shown the video with no decoration, so that you could at least see that the page wasn't hanging, but there's not a good internal consensus. 

Having said all of that, we should be able to download resources without the browser thread hanging.  I will look into this soon.

**Comment by rakesh4real** [comment]
Hey @mhays-google  thank you for the response. I have two questions -

> we should be able to download resources without the browser thread hanging. I will look into this soon.

One, can I know ETA for this or link to specific issues / PRs so that I can contribute in some way if possible?

> For holistic, the models are... a bit large... there are three of them, in fact, and each are several megabytes in size.

Two, it is true that the models are huge. Given that we have better models like https://blog.tensorflow.org/2021/05/next-generation-pose-detection-with-movenet-and-tensorflowjs.html what is the best way to create our own holistic model combining other models (face keypoints detector + body pose detector + hand keypoints detector)

**Comment by rakesh4real** [comment]
> Demo to show hanging: https://sign-language-processing.github.io/playground/
> While it says "Loading Pose Estimation" the browser thread hangs. Try to hover things in the menu, you see that they aren't responsive

Hey @AmitMY is the browser still hanging for you?

**Comment by AmitMY** [comment]
In version `0.3.1620694839` it still hangs.

**Comment by rakesh4real** [comment]
I am using `0.3.1620080860` and it hangs as well. @AmitMY saw that your web app doesn't hang.

1. what version(s)  are you using which does NOT hang?
2. are you using service worker?

Thank you for quick response

**Comment by rakesh4real** [comment]
Actually all these models hang - 

```
`https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.1.1613603339/${file}`;
`https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.3.1620248688/${file}`; 
`https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.3.1620246181/${file}`; 
`https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.3.1620080860/${file}`
```

**Comment by AmitMY** [comment]
@rakesh4real my web app *does* hang. just tested it now again.

**Comment by rakesh4real** [comment]
@mhays-google kindly let me know here if there are any interesting updates

**Comment by rakesh4real** [comment]
Interestingly, the movenet pose model and handpose model also hang the browser. Isn't there a way to not hang the browser while loading model into memory?

**Comment by AmitMY** [comment]
Loading holistic in a web worker does not hang the browser, however, has other issues at the moment
https://github.com/google/mediapipe/issues/2506

**Comment by Digitaldarwinlab** [comment]
@mhays-google @sgowroji We have used webworkers but the browser still hangs for a substantial amount of time for the first time. Even we are using the Blazepose model only for pose estimation.  
Any solution or update since your last update on September 6? 
 @INF800 Were you able to get a workaround?

**Comment by INF800** [comment]
> @mhays-google @sgowroji We have used webworkers but the browser still hangs for a substantial amount of time for the first time. Even we are using the Blazepose model only for pose estimation. Any solution or update since your last update on September 6? @INF800 Were you able to get a workaround?

With webworkers I could "reduce" the hanging issue but couldn't remove it completely

**Comment by Digitaldarwinlab** [comment]
Thanks @INF800 Asapanna.  
We are facing another issue in one of the use cases while loading media pipe which started coming up recently after we tried an upgrade for mediapipe. If we move to tfjs model, everything starts working. 
Look forward to your reply if you faced this or have a solution. @AmitMY @mhays-google 
![MediaPipe loading error](https://user-images.githubusercontent.com/79757248/143447179-3c7740bc-2f69-44d3-80ca-55d94317ba45.png)

**Comment by tu-nv** [comment]
We also faced the same issue. I think it is ok to take time loading model, but it should not hang the browser.

**Comment by AmitMY** [comment]
Until this issue is resolved - https://github.com/google/mediapipe/issues/2506
The browser hanging is still an issue
