### ISSUE TITLE
Face mesh model does not capture eye aperture

### ISSUE THREAD

**Issue by AmitMY** [google/mediapipe#1919]
This is the case both for closed eyes, and for bug eyes.
An example for closed eyes:
You can see the left image with closed eyes, the right with open, and the middle is one eye closed, one eye open.
The closed eye result isn't closed, its a bit squeezed, but not what I would expect.
![image](https://user-images.githubusercontent.com/5757359/115600872-6f143700-a2dd-11eb-9754-bc16d3ad84a2.png)
![image](https://user-images.githubusercontent.com/5757359/115600933-7d625300-a2dd-11eb-9a54-00fc6697a3e8.png)

For bug eyes, the situation is similar. Attached is half-and-half, so you can see the problem:
Her left eye is normal, her right is bug, but the pose doesn't span to it.
![half-bug-annotated](https://user-images.githubusercontent.com/5757359/115601367-0083a900-a2de-11eb-8117-06f0053a04fc.png)

**Comment by lilinxiong** [comment]
I also encountered the same problem....

**Comment by lilinxiong** [comment]
Hello @AmitMY I have solved this problem. In fact, there is a formula that can calculate the opening and closing of the human eye. That is to calculate the aspect ratio of the eyes (EAR). Take one of the eyes as an example.
![image](https://user-images.githubusercontent.com/24367027/115840787-a1917180-a44e-11eb-9494-722fc28eba58.png)
I'm sorry. I did not find the English document. I saw it in a Chinese blog. [link](https://blog.csdn.net/cungudafa/article/details/103477960) (If you are interested, you can click it).
java code is:
```java
List<LandmarkProto.NormalizedLandmark> landmarks;
int[] eyeUpperIdx = {466, 388, 387, 386, 385, 384, 398};
int[] eyeLowerIdx = {249, 390, 373, 374, 380, 381, 382};
int[] eyeCenterIdx = {263, 362};
double sumLowerY = 0.0f;
for (int idx = 0; idx < eyeLowerIdx.length; ++idx) {
    sumLowerY += landmarks.get(eyeLowerIdx[idx]).getY();
}
double sumUpperY = 0.0f;
for (int idx = 0; idx < eyeUpperIdx.length; ++idx) {
    sumUpperY += landmarks.get(eyeUpperIdx[idx]).getY();
}
double eyeOpenness = (sumLowerY - sumUpperY) / (landmarks.get(eyeCenterIdx[0]).getX() - landmarks.get(eyeCenterIdx[1]).getX());
```
In this way, you will get a value that better reflects the current eye shape. You can use the threshold to determine whether the eyes are currently open or closed.

**Comment by AmitMY** [comment]
Thanks @lilinxiong 
Unfortunately, it is very hard to decide on a threshold, as different races have different eye shapes. 
This is what I am actually trying to use machine learning to solve, as I have a vast dataset of various people with different eye apertures. Hopefully the face model improves soon.

**Comment by lilinxiong** [comment]
Yes, the threshold is difficult to determine, actually I want to mention the shape of the mouth(Y control open or close, X control shape).

**Comment by sgowroji** [comment]
Thank you for sharing your resolution, which will really help the other users.
