### ISSUE TITLE
NNAPI Support?

### ISSUE THREAD

**Issue by jessedaniels** [google/mediapipe#192]
Hello,

I see examples using the Android GPU delegate and CPU for tflite, but no examples or mention of using the NNAPI for Android. Is this supported and will examples be made available?

Thanks!

**Comment by mgyong** [comment]
@jessedaniels NNAPI is lower level API on android than TFlite. We do not have plans to support NNAPI inference for Android. What is the use case for this? If you like to support NNAPI in MediaPipe, we welcome contribution on this. You will have to do something similar to [TFLiteinference calculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_inference_calculator.cc)

**Comment by jessedaniels** [comment]
TFLite provides a [UseNNAPI(bool enable) ](https://www.tensorflow.org/lite/api_docs/cc/class/tflite/interpreter.html#classtflite_1_1_interpreter_1a6709c6951b7450b62582a832309ab54f) option on the interpreter class to use NNAPI from TFLite. From my understanding it can provide further optimized operator placement on the compute devices, e.g., use the DSP on a Qualcomm chip. It seems like this capability is getting more attention with the Android 10 release to optimize network performance. Android 10 is also supposed to provide additional control over operator placement.

Just curious if this TFLite feature was on a support roadmap as an execution option in addition to GPU/CPU. We've seen performance improvements using the NNAPI interface on some of the newer phones/tablets.

Thanks
