### ISSUE TITLE
draw landmarks just like video pose sample in python

### ISSUE THREAD

**Issue by alighofrani95** [google/mediapipe#1920]
![image](https://user-images.githubusercontent.com/14968123/115603818-db9b3000-a2f5-11eb-93e1-344b1d100708.png)

How can I darw landmarks and connection line similar to above sample in python

the drawing_utils.py just supports the thickness and color.

  Args:
    image: A three channel RGB image represented as numpy ndarray.
    detection: A detection proto message to be annotated on the image.
    keypoint_drawing_spec: A DrawingSpec object that specifies the keypoints'
      drawing settings such as color, line thickness, and circle radius.
    bbox_drawing_spec: A DrawingSpec object that specifies the bounding box's
      drawing settings such as color and line thickness.

**Comment by sgowroji** [comment]
Refer this issue for more understanding https://github.com/google/mediapipe/issues/1743

**Comment by alighofrani95** [comment]
I'm looking for python implementation, Is it related with drawing_utils_test.py??

**Comment by sgowroji** [comment]
Hi @alighofrani95, For drawing on pose you can try this https://github.com/google/mediapipe/issues/1393#issuecomment-746745775

**Comment by alighofrani95** [comment]
It doesn't still fix my issue.

How can I draw specific landmarks by not all of them?
How can I draw every landmark with special attributes such as color and thickness?

**Comment by jiuqiant** [comment]
You can get landmark coordinates by accessing the landmark by name. The landmark names are defined at https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/pose.py#L44. For example, you can get the nose landmark by 

```
nose_x = results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].x * image_width
noses_y = results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].y * image_height
```

MediaPipe's simple drawing_util is just for showing users how to parse the landmark outputs. Feel free to use your favorite drawing library to draw annotations after getting the coordinates .
