### ISSUE TITLE
Saving overlaid video ?

### ISSUE THREAD

**Issue by timtensor** [google/mediapipe#1921]
Hi i was wondering if there is a possibility to save pose estimation overlaid ouput on a input video saved as mp4. So basically using a local video instead of the webcam feed.

**Comment by sgowroji** [comment]
Hi @timtensor, Could you please share more details regarding the above issue and what platform are you looking for. Thanks

**Comment by timtensor** [comment]
So i am trying to save the detected keypoint videos as an mp4 file. I am not using the webcam as input but rather a video file. I run the inference on that. I want to save the infered video . I am using the python API . Is there a way to do that. Also where can i find details of all available functions ?

**Comment by jiuqiant** [comment]
We already use OpenCV to read webcam data. If you want to output results as a video, you can do this with OpenCV as well. You simply just need to initialize a cv2.VideoWriter and call `out.write(frame)` per annotated frame. See the tutorial at https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html#saving-a-video.

**Comment by sgowroji** [comment]
Hi @timtensor, Did you get a chance to go through the above comment. Thanks!

**Comment by timtensor** [comment]
yes ! i managed it thanks!
