### ISSUE TITLE
How to solve the problem of the smoothness of the shoe model

### ISSUE THREAD

**Issue by z7212819** [google/mediapipe#1925]
Hello, as shown in the picture, the official shoe model is very smooth, but my own shoes are not smooth. How did you convert the format to keep it smooth? Thank you!
![Screenshot_20210422-112002](https://user-images.githubusercontent.com/75053001/115651345-99bbbb00-a2f0-11eb-947d-ad479136ef22.jpg)
![Screenshot_20210418-203658](https://user-images.githubusercontent.com/75053001/115651356-9d4f4200-a2f0-11eb-8f07-767543214a15.jpg)

**Comment by z7212819** [comment]
By the way, what kind of 3D tools do you use to make obj files?

**Comment by sgowroji** [comment]
Hi @z7212819, Could you please share your code repo with your changes. Thanks!

**Comment by z7212819** [comment]
@sgowroji I'm glad you can reply to me. I only replaced the uuu file and the texture file. There is no modification in the code, so I would like to ask how to solve the smoothness problem.

**Comment by emreboyraz0** [comment]
how did you convert .obj file to .uuu file? 

I have tried `bazel run -c opt mediapipe/graphs/object_detection_3d/obj_parser:ObjParser -- input_dir=[INTERMEDIATE_OUTPUT_DIR] output_dir=[OUTPUT_DIR]`

But giving the error 

`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -81918 out of bounds for length 125532
	at SimpleObjParser.constructFinalCoordinatesFromMap(SimpleObjParser.java:260)
	at SimpleObjParser.parse(SimpleObjParser.java:364)
	at ObjParserMain.processFile(ObjParserMain.java:162)
	at ObjParserMain.run(ObjParserMain.java:111)
	at ObjParserMain.main(ObjParserMain.java:149)
`

**Comment by z7212819** [comment]
@emreboyraz0 
Hello, your model number is too high, it needs to be adjusted to less than 14000.

**Comment by emreboyraz0** [comment]
> @emreboyraz0
> Hello, your model number is too high, it needs to be adjusted to less than 14000.

Thank you very much for your reply. What is number mean? is it vertexes or polygon ?

**Comment by z7212819** [comment]
@emreboyraz0 model surface numbers

**Comment by emreboyraz0** [comment]
Thank you so much. Did you figure out how to change shoe model at runtime ?

**Comment by z7212819** [comment]
@emreboyraz0 I can't do that

**Comment by z7212819** [comment]
@emreboyraz0 I have no way to implement this feature

**Comment by UX3D-mazzini** [comment]
@emreboyraz0 @z7212819 
Hi. After all this time did you figure out how to change shoe model at runtime ?

**Comment by kuaashish** [comment]
Hello @z7212819,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
