### ISSUE TITLE
Missing input file 'external/windows_opencv/x64/vc15/lib/opencv_world3410.lib'

### ISSUE THREAD

**Issue by dauntless3** [google/mediapipe#1926]
**System information**

OS: Windows 10
Bazel version 3.7.2
Python version 3.7.6
VS Community 2019 16.9.4 

**Description**

Hello!

I tried to build the C++ examples on Windows. The hello_world example works, but the hand tracking example gave this error:

bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//ASUS//AppData//Local//Programs//Python//Python37//python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

DEBUG: C:/users/asus/_bazel_asus/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_cc' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/f75p3gig/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/asus/mediapipe_repo/mediapipe/mediapipe/examples/desktop/hand_tracking/BUILD:27:10: //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu: missing input file 'external/windows_opencv/x64/vc15/lib/opencv_world3410.lib', owner: '@windows_opencv//:x64/vc15/lib/opencv_world3410.lib'
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/users/asus/mediapipe_repo/mediapipe/mediapipe/examples/desktop/hand_tracking/BUILD:27:10 1 input file(s) do not exist
INFO: Elapsed time: 0.913s, Critical Path: 0.04s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

Out of curiosity, I checked this folder C:\Users\ASUS\_bazel_ASUS\f75p3gig\external\windows_opencv\x64\vc15\lib and found opencv_world3414.lib. There is no opencv_world3410.lib, which the Build was trying to find (referring to the error log above).

Would appreciate any advice on this - thank you!

**Comment by dauntless3** [comment]
Also, I did a search on my PC to ensure that opencv_world3410.lib doesn't exist on any folder.

**Comment by sgowroji** [comment]
Hi @dauntless3, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by dauntless3** [comment]
Hi @sgowroji, thanks for looking into this! The error came up when I ran the following on the command prompt. There were no other steps relating to this.

bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//ASUS//AppData//Local//Programs//Python//Python37//python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

The step before this was building the hello_world example, and before that the mediapipe installation process.

Hope this clarifies. Do let me know if I can provide further information.

**Comment by jiuqiant** [comment]
Where do you put the opencv windows executable locally? You need to modify https://github.com/google/mediapipe/blob/master/WORKSPACE#L222 to be `path = "C:\\path\\to\\opencv\\build",` if you don't install opencv at C:\opencv.

See the step 8 of https://google.github.io/mediapipe/getting_started/install#installing-on-windows for more details.

**Comment by rahulchaphalkar** [comment]
You need to modify the file `opencv_windows.BUILD` located at `mediapipe/third_party/opencv_windows.BUILD`
Here it assumes you're using opencv version 3.4.10
Change the version to `"3414"` (referring to 3.4.14) or whichever you have installed
Hello_world worked because it didn't use opencv.

**Comment by dauntless3** [comment]
> Where do you put the opencv windows executable locally? You need to modify https://github.com/google/mediapipe/blob/master/WORKSPACE#L222 to be `path = "C:\\path\\to\\opencv\\build",` if you don't install opencv at C:\opencv.
> 
> See the step 8 of https://google.github.io/mediapipe/getting_started/install#installing-on-windows for more details.

It is at c:\opencv.

Thanks

**Comment by dauntless3** [comment]
> You need to modify the file `opencv_windows.BUILD` located at `mediapipe/third_party/opencv_windows.BUILD`
> Here it assumes you're using opencv version 3.4.10
> Change the version to `"3414"` (referring to 3.4.14) or whichever you have installed
> Hello_world worked because it didn't use opencv.

Yes changing to 3414 has solved it - thank you!
