### ISSUE TITLE
How to access intermediate results of mediapipe from the main activity (android platform)

### ISSUE THREAD

**Issue by midhulavijayan** [google/mediapipe#1927]
I have created a classification (binary classification) app using mediapipe. I am rendering the class labels ( based on the prediction probability value) within mediapipe and able to display the results. As per my problem, i wanted to make decisions from android main based on the classification probability value, Is there any way to access the probability value from the android main?...

Thanks.

**Comment by sgowroji** [comment]
Hi @midhulavijayan, Could you please elaborate the use case with complete details and which MediaPipe solution are you referring. Thanks

**Comment by midhulavijayan** [comment]
input_stream: "input_video"
output_stream: "output_video"


node: {
calculator: "GpuBufferToImageFrameCalculator"
input_stream: "input_video"
output_stream: "input_video_cpu"
}


node {
calculator: "FlowLimiterCalculator"
input_stream: "input_video_cpu"
input_stream: "FINISHED:detection_tensors"
input_stream_info: {
tag_index: "FINISHED"
back_edge: true
}
output_stream: "throttled_input_video_cpu"
}

node: {
calculator: "ImageTransformationCalculator"
input_stream: "IMAGE:throttled_input_video_cpu"
output_stream: "IMAGE:transformed_input_video_cpu"
node_options: {
[type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
output_width: 150
output_height: 150
}
}
}


node {
calculator: "TfLiteConverterCalculator"
input_stream: "IMAGE:transformed_input_video_cpu"
output_stream: "TENSORS:image_tensor"
node_options: {
    [type.googleapis.com/mediapipe.TfLiteConverterCalculatorOptions] {
      zero_center: false
      max_num_channels: 1
    }
  }
}


node {
calculator: "TfLiteInferenceCalculator"
input_stream: "TENSORS:image_tensor"
output_stream: "TENSORS:detection_tensors"
node_options: {
[type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
model_path: "mediapipe/models/finger_detection.tflite"
}
}
}

node {
calculator: "TfLiteTensorsToClassificationCalculator"
input_stream: "TENSORS:detection_tensors"
output_stream: "CLASSIFICATIONS:classifications"
node_options: {
[type.googleapis.com/mediapipe.TfLiteTensorsToClassificationCalculatorOptions] {
#min_score_threshold: 0.5
#top_k: 1
#label_map_path: "labelmap.txt"
}
}
}

 
node {
  calculator: "AddText"
  #input_stream: "NORM_LANDMARKS_TEMP:multi_face_landmarks"
  input_stream: "IMAGE_CPU:throttled_input_video_cpu"
  input_stream: "LABEL:classifications"
  output_stream: "OUTPUT_VIDEO:output_video_cpu"
  }

node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "output_video_cpu"
  output_stream: "output_video"
}



This is the graph which  i'm using for the classification. i have edited "TfLiteTensorsToClassification" and it gives an output stream ( "CLASSIFICATIONS:classifications") of type float and ""Addtext"" is a custom calculator to render the class label. This is running on my android device. Now, i wanted to access the "CLASSIFICATIONS:classifications", (which is the output stream of "TfLiteTensorsToClassification" calculator) from the android main. How to access this value from the android main?

**Comment by midhulavijayan** [comment]
Finally, solved the issue.. :)

**Comment by sgowroji** [comment]
Glad to know you resolved. Posting your solution will help others when they encounter similar issue. Thanks!

**Comment by 04633435** [comment]
> Finally, solved the issue.. :)

Hi, I am struggling with a similar issue. How do you access what you want from the mediapipe on an android device?

**Comment by midhulavijayan** [comment]
Hi @04633435, I was trying to implement one binary classification model. Initially, i had a problem while accessing the classification probability value from the android main. 

Solution:
private static final String OUTPUT_CLASSIFICATION_STREAM = "classifications";
processor.addPacketCallback(
                OUTPUT_CLASSIFICATION_STREAM,
                (packet) -> {
                    float probability = PacketGetter.getFloat32(packet);
                });
