### ISSUE TITLE
AttributeError: module 'mediapipe' has no attribute 'solutions'

### ISSUE THREAD

**Issue by H4ckerman666** [google/mediapipe#1928]
Has anyone had this error when importing the mediapipe library?

AttributeError: partially initialized module 'mediapipe' has no attribute 'solutions'(most likely due to a circular import)

```
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_face_mesh = mp.solutions.face_mesh
```

**Comment by sgowroji** [comment]
Hi @H4ckerman666, What is your python version?. Refer this similar issues https://github.com/google/mediapipe/issues/1466, https://github.com/google/mediapipe/issues/1349

**Comment by xialuoke4062** [comment]
Hi, Thank you for opening this issue. 

Python 3.7.9
macOS 10.14.6

I ran into the same issue. Both #1466 and #1349 recommended to install using `pip install mediapipe`, but after trying with multiple python versions inside/outside different env it still failed with:
`ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)`
`ERROR: No matching distribution found for mediapipe`

So I built the package from source successfully. But the same error was raised when running the sample code:
`AttributeError: module 'mediapipe' has no attribute 'solutions'`

Any suggestions would be appreciated!

**Comment by H4ckerman666** [comment]
Resulta que como soy muy listo, mi archivo tenia el mismo nombre que la librería, ahora que lo cambie, funciona como debería

**Comment by bmox** [comment]
Just change your file name. Thanks .

**Comment by Himajin1** [comment]
May I ask which file I should change the name of?
(Sorry if this has an obvious answer)

**Comment by Sebski17** [comment]
I have run into the same issue after successfully building mediapipe on RPi4.
Has anyone managed to come up with a definite fix?

**Comment by H4ckerman666** [comment]
> May I ask which file I should change the name of?
> (Sorry if this has an obvious answer)

my file was named mediapipe.py, but that name is the same as the library, so I had to change the name to something else

**Comment by Sebski17** [comment]
> > I have run into the same issue after successfully building mediapipe on RPi4.
> > Has anyone managed to come up with a definite fix?
> 
> Change the python file name. Because python confused which file should take. Or maybe In that directory there is some file names that file name match with mediapipe inbuilt file.

None of my files are called mediapipe.py, also I am working from outside the source folder. Any ideas?

**Comment by hhajae** [comment]
@Sebski17 
I have same error in Rpi4 with Raspbian.
what is pi's os?

**Comment by Sebski17** [comment]
> @Sebski17
> I have same error in Rpi4 with Raspbian.
> what is pi's os?

Raspberry Pi OS (32-bit)
Released:2021-05-07

**Comment by chenzx** [comment]
i tried to play the python face mesh demo on mac, but hit by strange errors:

(1)if run script from base dir:
```
% python3 mp_demo.py
Traceback (most recent call last):
  File "mp_demo.py", line 3, in <module>
    mp_drawing = mp.solutions.drawing_utils
AttributeError: module 'mediapipe' has no attribute 'solutions'
```

(2)run from outside file path:
```
% python3 mp_demo.py
mp_face_mesh: <module 'mediapipe.python.solutions.face_mesh' from '/usr/local/lib/python3.8/site-packages/mediapipe/python/solutions/face_mesh.py'>
WARNING: Logging before InitGoogleLogging() is written to STDERR
W20210611 15:51:41.934258 50077696 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/face_detection/face_detection_front.tflite
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W20210611 15:51:41.937750 50077696 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/face_landmark/face_landmark.tflite
^C
```

**Comment by Hpal76832** [comment]
AttributeError: module 'mediapipe.python.solutions' has no attribute 'selfie_segmentation'........

Any solution for this error ??

**Comment by lghasemzadeh** [comment]
> > May I ask which file I should change the name of?
> > (Sorry if this has an obvious answer)
> 
> my file was named mediapipe.py, but that name is the same as the library, so I had to change the name to something else

It worked for me, thx

**Comment by H4ckerman666** [comment]
It no longer has the same functions, they have been updated, please, check the example on the mediapipe page

> AttributeError: module 'mediapipe.python.solutions.holistic' has no attribute 'FACE_CONNECTIONS'

**Comment by abhishetty71** [comment]
I tried renaming the file also the directory, but updating mediapipe to the latest version worked for me.

**Comment by eng-psycho** [comment]
I can't fix it:, 
```
  **File "c:\Users\engps\Desktop\Programming\Python\HandTrackingModule.py", line 30, in findHands
    self.mp_drawing.draw_landmarks(img, handLms, self.mp_hands.HAND_CONNECTIONS, self.drawing_styles.get_default_hand_landmark_style(),self.drawing_styles.get_default_hand_connection_style())
AttributeError: module 'mediapipe.python.solutions.drawing_styles' has no attribute 'get_default_hand_landmark_style'
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback**
```
could anyone help me?

**Comment by AngeMervaneJdev** [comment]
I have just intalled mediapipe on my environment but i get this error 

**AttributeError: partially initialized module 'mediapipe' has no attribute 'python' (most likely due to a circular import)**

i need your help please

**Comment by Hpal76832** [comment]
Change the name of your file in which you are using mediapipe

**Comment by twiceand** [comment]
it need init in hands.py
ctrl&click Hands in mpHands.Hands() it will turn to hands.py
![image](https://user-images.githubusercontent.com/64593919/143688012-fc6afa05-1b7a-4fa1-99f2-9450b42fa805.png)

**Comment by twiceand** [comment]
it need init in hands.py
ctrl&click Hands in mpHands.Hands() it will turn to hands.py

**Comment by lghasemzadeh** [comment]
> It turns out that as I am very smart, my file had the same name as the library, now that I change it, it works as it should

my file name was different, but I was getting this error again and again, then I figured out that in that directory I had a folder named mediapipe. I deleted it and the error resolved. so other than the file name be careful about any other file or folder with same name.

**Comment by Junesh9** [comment]
> > > May I ask which file I should change the name of?
> > > (Sorry if this has an obvious answer)
> > 
> > 
> > my file was named mediapipe.py, but that name is the same as the library, so I had to change the name to something else
> 
> It worked for me, thx

My file name is BalloonPwop.py, and same problem...

**Comment by Azharuet09** [comment]
May I ask which file I should change the name of?
(Sorry if this has an obvious answer)

my file was named mediapipe.py, but that name is the same as the library, so I had to change the name to something else

It worked for me, thx

**Comment by H4ckerman666** [comment]
> I can't fix it:,
> 
> ```
>   **File "c:\Users\engps\Desktop\Programming\Python\HandTrackingModule.py", line 30, in findHands
>     self.mp_drawing.draw_landmarks(img, handLms, self.mp_hands.HAND_CONNECTIONS, self.drawing_styles.get_default_hand_landmark_style(),self.drawing_styles.get_default_hand_connection_style())
> AttributeError: module 'mediapipe.python.solutions.drawing_styles' has no attribute 'get_default_hand_landmark_style'
> [ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1i5nllza\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback**
> ```
> 
> could anyone help me?

your object is wrong, check the doc pls https://google.github.io/mediapipe/solutions/face_mesh

**Comment by Azharuet09** [comment]
yes how can i help you

**Comment by veera20** [comment]
hi ,i have run the script setup_opencv.sh and currently mediapipe is importing fine but i am facing error for my test scrips for hand gesture recongintion like AttributeError: module 'mediapipe' has no attribute 'solutions

**Comment by veera20** [comment]
can anyone help wit this above error i am getting in riscv target .

**Comment by lomankuk** [comment]
Hello,

I am seeing the same error. AttributeError: module 'mediapipe' has no attribute 'solutions'

Double checked, no duplication of file/directory names.
My setting is ..
OS: Linux (a Debian offspring)
Opencv: 3.2.0
Python: 3.7.3

I just run three lines in python3 console ...
>>>import cv2 as cv
>>>import mediapipe as mp
>>>mp_drawing = mp.solutions.drawing_utils

then the above error pop up.

I have also checked this ...
>>> dir(mp)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

Any suggestions are highly appreciated.

**Comment by Tikoymamaw** [comment]
I got same issue 

I'm using pipenv in windows 11 
my python version is 3.9


Exception has occurred: AttributeError
partially initialized module 'mediapipe' has no attribute 'solutions' (most likely due to a circular import)

**Comment by HardikCoder45** [comment]
> Hi, Thank you for opening this issue.
> 
> Python 3.7.9 macOS 10.14.6
> 
> I ran into the same issue. Both #1466 and #1349 recommended to install using `pip install mediapipe`, but after trying with multiple python versions inside/outside different env it still failed with: `ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)` `ERROR: No matching distribution found for mediapipe`
> 
> So I built the package from source successfully. But the same error was raised when running the sample code: `AttributeError: module 'mediapipe' has no attribute 'solutions'`
> 
> Any suggestions would be appreciated!
same with me

**Comment by DevanshYadav07** [comment]
> It turns out that as I am very smart, my file had the same name as the library, now that I change it, it works as it should

which file name can you specify

**Comment by H4ckerman666** [comment]
@DevanshYadav07 the main file, where you import mediapipe

**Comment by dilliraj1987** [comment]
AttributeError: module 'mediapipe.python.solutions' has no attribute 'object_detection' kindly help me to fix this error

**Comment by AlecSkril** [comment]
> AttributeError: module 'mediapipe.python.solutions' has no attribute 'object_detection' kindly help me to fix this error

I am getting the same thing

**Comment by StratosphericD** [comment]
> Hi, Thank you for opening this issue.
> 
> Python 3.7.9 macOS 10.14.6
> 
> I ran into the same issue. Both #1466 and #1349 recommended to install using `pip install mediapipe`, but after trying with multiple python versions inside/outside different env it still failed with: `ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)` `ERROR: No matching distribution found for mediapipe`
> 
> So I built the package from source successfully. But the same error was raised when running the sample code: `AttributeError: module 'mediapipe' has no attribute 'solutions'`
> 
> Any suggestions would be appreciated!

Did you solve your problem? I am running into the same issue.

**Comment by AngeMervaneJdev** [comment]
Yes!
Just change your folder's name. Maybe you have a folder in your working
directory which has the same like the dependency (mediapipe)

Le ven. 14 avr. 2023 à 16:43, StratosphericD ***@***.***> a
écrit :

**Comment by abukhans** [comment]
in my case i installed cvzone, which installed mediapipe, however that gave the error discussed here.
I re-installed mediapipe and that worked.
Note: i had opencv-python but meidapipe installed opencv-contrib-python
Seems like package dependency issues. I have run into these issues with opencv in the past

**Comment by BYyakuphan** [comment]
use python 3.10

**Comment by rapzodo** [comment]
even the google colab example is throwing error:

<img width="1855" height="887" alt="Image" src="https://github.com/user-attachments/assets/63c2acc6-9bd1-4993-9c2f-cd7d7431ae7c" />

**Comment by hudazaan** [comment]
the example is outdated because the support for solutions is removed in the current Mediapipe versions.

**Comment by StileDev** [comment]
Bonjour à tous. Je pense avoir trouvé la solution aux problèmes de mediapipe.solutions. En fait, la classe solutions de mediapipe a été déprécié. Du coup ils ont enlevé solutions dans les nouvelles versions de mediapipe. Donc si vous voulez utiliser peut-être le modèle face_mesh par exemple, il est présent dans la classe mediapipe.tasks.python et le nom n'est plus face_mesh mais FaceLandmarker. Pour ceux qui auront la flemme de se documenter. Je pense que je ferai des vidéos youtube par la suite pour expliquer comment utiliser les nouvelles fonctionnalités du module. Pour les intéréssés, le nom de la chaîne est "Franc Stile".

**Comment by XmuFishToucher** [comment]
Guys，we now can use "from mediapipe.tasks.python.vision import" to import your template.

**Comment by 930pinhong** [comment]
### I have a same problem: 
AttributeError: module 'mediapipe' has no attribute 'solutions'
My file name is my_mediapipe, doesn't same as the mediapipe, how can i fix the problem?

**Comment by hudazaan** [comment]
solutions don't exist anymore. migrate to mediapipe tasks

**Comment by StileDev** [comment]
Si vous voulez toujours utiliser solutions de mediapipe, le mieux serait
d'installer python3.10 crée un environnement virtuel et installer mediapipe
0.10.9.
Ou si vous voulez garder la nouvelle version de mediapipe, vous utiliser le
module task en faisant un truc comme : mp.task.python.vision

**Comment by mariscalromeroalejandro** [comment]
Use **Python 3.11**, uninstall any existing MediaPipe, and install the stable version 0.10.9:

```powershell
python -m pip uninstall mediapipe -y
python -m pip install mediapipe==0.10.9
```

**Comment by StileDev** [comment]
Wesh. Il faut utiliser cette version de ython pour pouvoir utiliser
mediapipe.solutions

**Comment by HarikrishnanK9** [comment]
Python version 3.10.19 and mediapipe 0.10.9 resolved my issue. I had some issues with protobuf earlier. Attaching the working requirements.txt
````
absl-py==2.3.1
attrs==25.4.0
cffi==2.0.0
contourpy==1.3.2
cycler==0.12.1
flatbuffers==25.12.19
fonttools==4.61.1
kiwisolver==1.4.9
matplotlib==3.10.8
mediapipe==0.10.9
numpy==2.2.6
opencv-contrib-python==4.13.0.90
opencv-python==4.13.0.90
packaging==26.0
pillow==12.1.0
protobuf==3.20.3
pycparser==3.0
pyparsing==3.3.2
python-dateutil==2.9.0.post0
six==1.17.0
sounddevice==0.5.4

**Comment by Gitanjali28** [comment]
> Use **Python 3.11**, uninstall any existing MediaPipe, and install the stable version 0.10.9:
> 
> python -m pip uninstall mediapipe -y
> python -m pip install mediapipe==0.10.9

@mariscalromeroalejandro Thank you so much for the suggestion. I was facing this issue and was unable to solve it earlier. Your solution helped a lot.

**Comment by StileDev** [comment]
Super

Le ven. 23 janv. 2026, 16:42, Gitanjali28 ***@***.***> a
écrit :

**Comment by ysrazsingh** [comment]
Example solution: https://github.com/google-ai-edge/mediapipe-samples/blob/main/examples/face_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Face_Landmarker.ipynb

**Comment by WLTDSB** [comment]
> Python version 3.10.19 and mediapipe 0.10.9 resolved my issue. I had some issues with protobuf earlier. Attaching the working requirements.txt
> 
> ```
> absl-py==2.3.1
> attrs==25.4.0
> cffi==2.0.0
> contourpy==1.3.2
> cycler==0.12.1
> flatbuffers==25.12.19
> fonttools==4.61.1
> kiwisolver==1.4.9
> matplotlib==3.10.8
> mediapipe==0.10.9
> numpy==2.2.6
> opencv-contrib-python==4.13.0.90
> opencv-python==4.13.0.90
> packaging==26.0
> pillow==12.1.0
> protobuf==3.20.3
> pycparser==3.0
> pyparsing==3.3.2
> python-dateutil==2.9.0.post0
> six==1.17.0
> sounddevice==0.5.4
> ```

Thanks,it trully work

**Comment by NorberMV** [comment]
Any way to add support for Python 3.14?
