### ISSUE TITLE
Calculator::Open() failed: [GL_INVALID_NUM] an unacceptable value.

### ISSUE THREAD

**Issue by lvaptx4869** [google/mediapipe#193]
**Using the following command to execute the face_detection_gpu sample**
`bazel-bin/mediapipe/examples/desktop/face_detection/face_detection_gpu     --calculator_graph_config_file=mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt`
**Here is the result** 
`INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
E1023 15:54:01.241976  3521 demo_run_graph_main_gpu.cc:181] Failed to run the graph: Graph has errors:
Calculator::Open() for node "[TfLiteInferenceCalculator, TfLiteInferenceCalculator with output stream: detection_tensors]" failed: **[GL_INVALID_ENUM]**: An unacceptable value is specified for an enumerated argument.: glBufferData in external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_buffer.h:245`

Does anyone know why this is happening? Thanks

**Comment by AlexYiningLiu** [comment]
> **Using the following command to execute the face_detection_gpu sample**
> `bazel-bin/mediapipe/examples/desktop/face_detection/face_detection_gpu --calculator_graph_config_file=mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt`
> **Here is the result**
> `INFO: Initialized TensorFlow Lite runtime. INFO: Created TensorFlow Lite delegate for GPU. E1023 15:54:01.241976 3521 demo_run_graph_main_gpu.cc:181] Failed to run the graph: Graph has errors: Calculator::Open() for node "[TfLiteInferenceCalculator, TfLiteInferenceCalculator with output stream: detection_tensors]" failed: **[GL_INVALID_ENUM]**: An unacceptable value is specified for an enumerated argument.: glBufferData in external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_buffer.h:245`
> 
> Does anyone know why this is happening? Thanks

Is this error solved now? How did you manage to resolve it? Thanks.
