### ISSUE TITLE
custom graph  Unable to find Calculator for android 

### ISSUE THREAD

**Issue by zhaoqilong3031** [google/mediapipe#1930]
#> error
`google.mediapipe.framework.MediaPipeException: not found: ValidatedGraphConfig Initialization failed.
    No registered object with name: FaceMeshGpu; Unable to find Calculator "FaceMeshGpu"
    No registered object with name: HairSegmentationGpu; Unable to find Calculator "HairSegmentationGpu"`
[code]
> BUILD

 `load(
    "//mediapipe/framework/tool:mediapipe_graph.bzl",
    "mediapipe_binary_graph",
)

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mobile_calculators",
    deps = [
        "//mediapipe/graphs/face_hair/subgraphs:face_mesh_gpu",
        "//mediapipe/graphs/face_hair/subgraphs:hair_segmentation_gpu",
    ],
)
`

> face_hair_mobile.pbtxt

`

node {
  calculator: "FaceMeshGpu"
  input_stream: "NUM_FACES:num_faces"
  input_stream: "IMAGE:input_video"
  output_stream: "multi_face_landmarks"
  output_stream: "IMAGE:face_output_video"
}

node {
  calculator: "HairSegmentationGpu"
  input_stream: "IMAGE:face_output_video"
  input_stream: "red"
  input_stream: "green"
  input_stream: "blue"
  output_stream: "throttled_input_video_cpu"
  output_stream: "hair_mask_full_cpu"
  output_stream: "IMAGE:output_video"
}
`

> subgraphs BUILD 
  
`

mediapipe_simple_subgraph(
    name = "face_mesh_gpu",
    graph = "face_mesh_mobile.pbtxt",
    register_as = "FaceMeshGpu",
    deps = [
        ":face_mesh_calculators",
    ],
)
 
mediapipe_simple_subgraph(
    name = "hair_segmentation_gpu",
    graph = "hair_segmentation_mobile_gpu.pbtxt",
    register_as = "HairSegmentationGpu",
    deps = [
        ":hair_segmentation_calculators",
    ],
)`

> face_mesh_mobile.pbtxt

`
type: "FaceMeshGpu"

`

> hair_segmentation_mobile_gpu.pbtxt

`type: "HairSegmentationGpu"
`

**Comment by sgowroji** [comment]
Hi @zhaoqilong3031, Could you please explain more about your use case with complete details. Are you combining both FaceMesh and HairSegmentation?  And above are the only changes you have done?. Thanks

**Comment by zhaoqilong3031** [comment]
yes, Do I need to change anything ？

**Comment by mcclanahoochie** [comment]
your main graph `face_hair_mobile.pbtxt` needs to have a BUILD target also , like this 
https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/hair_segmentation/BUILD#L56

**Comment by sgowroji** [comment]
Hi @zhaoqilong3031, Could you please try the fix mentioned in the above comment. Thanks!

**Comment by sgowroji** [comment]
Assuming your issue fixed, we are closing this issue now. Thanks!
