### ISSUE TITLE
no matching toolchains found for types @bazel_tools while build for Android

### ISSUE THREAD

**Issue by kbtxwer** [google/mediapipe#1931]
It is ok when I run 
bazel build -c opt :encoder_main
or
bazel build -c opt :decoder_main

however, when it comes to build an Android APP, the error occurs.

I'm sure that I have add the path of sdk and ndk to ~/.bashrc and reload it, and I can't unserstand what the bazel is showing about.

/////////////////////////////////////////////
ERROR: While resolving toolchains for target //android_example:lyra_android_example: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//android_example:lyra_android_example' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
INFO: Elapsed time: 1.526s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (14 packages loaded, 24 targets configured)
//////////////////////////////////////////////

**Comment by daehwankim112** [comment]
I am having a same issue
