### ISSUE TITLE
Creating square and rectangular bounding boxes dependent on hand shape

### ISSUE THREAD

**Issue by Thurguild** [google/mediapipe#1932]
When trying to use bounding boxes, I can only get rectangles and not boxes that will change shape as the hand does, i.e. rectangles and squares. Is there a function within Mediapipe to be able to achieve this? The code I'm running to add rectangles to the image is as below: 
   size = image.shapeS
    print(size)
    if results.hand_rects:
      for rect in results.hand_rects:
        pt1 = (int(rect.x_center * size[1] - ((rect.width * size[1]) / 3)), int(rect.y_center * size[0] - ((rect.height * size[0]) / 3)))
        pt2 = (int(rect.x_center * size[1] + ((rect.width *r size[1]) / 3)), int(rect.y_center * size[0] + ((rect.height * size[0]) / 3))) 

        print("{0},{1}".format(pt1,pt2))

        cv2.rectangle(image, pt1, pt2, (255,0,0), 2)
        cv2.rectangle(image, (int(rect.x_center*size[1]), int(rect.y_center*size[0])), (int(rect.x_center*size[1]), int(rect.y_center*size[0])), (0,0,255), 5)

    #results = hands.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    #print(results)

This allows the bounding boxes to be drawn however doesn't allow for any shape change, if someone could advise it would be appreciated.

**Comment by sgowroji** [comment]
Hi @Thurguild, Could you please explain with complete details of your use case. Like what solution, Platform are you referring.  And can you share any screenshot of bounding box which you were describing in the above comment. Thanks

**Comment by Thurguild** [comment]
Hi @eknight7 and @jiuqiant is there any update on this issue?

**Comment by eknight7** [comment]
Hi,
Using code similar to https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/hands_test.py#L79-L84, you can get the landmark coordinates of the hand landmarks and use the outer finger tips and wrist to determine the bounds of the rectangle surrounding the hand. https://google.github.io/mediapipe/solutions/hands.html#hand-landmark-model shows a mapping of hand landmark indices to finger positions.

**Comment by Thurguild** [comment]
Hi, 
That's great I'll have a mess around with the code and see what I can do

**Comment by sgowroji** [comment]
Thank you for the update. We are closing this issue now.  Feel free to reopen the issue if your issue still exists.
