### ISSUE TITLE
Debug Build Issue - Opencv + Windows

### ISSUE THREAD

**Issue by rahulchaphalkar** [google/mediapipe#1933]
When building a debug build on windows platform, for example for face_mesh, build fails with several `unresolved symbol` errors
```
demo_run_graph_main.lib(demo_run_graph_main.obj) : error LNK2019: unresolved external symbol "void __cdecl cv::imshow(class cv::String const &,class cv::debug_build_guard::_InputArray const &)" (?imshow@cv@@YAXAEBVString@1@AEBV_InputArray@debug_build_guard@1@@Z) referenced in function "class absl::lts_2020_09_23::Status __cdecl RunMPPGraph(void)" (?RunMPPGraph@@YA?AVStatus@lts_2020_09_23@absl@@XZ)
bazel-out\x64_windows-dbg\bin\mediapipe\examples\desktop\face_mesh\face_mesh_cpu.exe : fatal error LNK1120: 14 unresolved externals
Target //mediapipe/examples/desktop/face_mesh:face_mesh_cpu failed to build
```
Conmand line for this was 
```
bazel build -c dbg --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//username//AppData//Local//Programs//Python//Python39//python.exe" mediapipe/examples/desktop/face_mesh:face_mesh_cpu
```
Build is successful for `-c opt`.

Reason for this is, in `mediapipe/third_party/opencv_windows.BUILD` file, the dll/lib files for opencv are not w/ debug symbols. Modifying this file to include following solves the problem -
```
srcs = [
        "x64/vc15/lib/opencv_world" + OPENCV_VERSION + ".lib",
	"x64/vc15/lib/opencv_world" + OPENCV_VERSION + "d"+".lib",
        "x64/vc15/bin/opencv_world" + OPENCV_VERSION + ".dll",
	"x64/vc15/bin/opencv_world" + OPENCV_VERSION + "d"+".dll",
    ],
```
where the `d` suffix points to the required files.

It wasn't too clear from the output error that this was required, hence creating this issue for future reference.

**Comment by sgowroji** [comment]
Hi @rahulchaphalkar, Could you please explain the steps followed to reproduce the above issue. Thanks!

**Comment by rahulchaphalkar** [comment]
I followed the steps for installation on windows listed [HERE](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows)
Downloaded opencv 3.4.10 from https://opencv.org/releases/ as recommended, modified `WORKSPACE` file to ensure it points to the opencv location.
`Hello world` ran as expected.
Built Mediapipe face_mesh model for cpu according to instructions [HERE](https://google.github.io/mediapipe/getting_started/cpp.html#option-1-running-on-cpu) ] 
(replaced hand_tracking with appropriate face_mesh parameters)
It builds and runs successfully with the flag `-c opt`, so installation and build is successful. However, since i needed debug symbols, i built it with bazel's debug flag i.e. `-c dbg`, that's when i encountered the above errors. 
They are resolved when I add the `d` suffix opencv library files to the `mediapipe/third_party/opencv_windows.BUILD` file.
I'm assuming the `d` suffix files, like `opencv_world3410d.dll` and `opencv_world3410d.pdb` are required for additional symbols for debug build.

**Comment by jiuqiant** [comment]
Does https://github.com/google/mediapipe/issues/1718#issuecomment-794353452 help?

**Comment by rahulchaphalkar** [comment]
@jiuqiant ah i believe it is the same issue, which already has a PR. I'll close this one. Thanks.
