### ISSUE TITLE
Conversion from skeleton to hand/body model?

### ISSUE THREAD

**Issue by Frank-Dz** [google/mediapipe#1935]
Thank you for your work!
Is there a way to convert the skeleton to a MANO/SMPL model?
That is compute the Hand mesh parameters according to the joint's position (suppose we do not need the skeleton length info)?

Thank you!

**Comment by sgowroji** [comment]
Please refer this link  https://github.com/google/mediapipe/issues/1743. Still any questions please let us know. Thanks!

**Comment by Frank-Dz** [comment]
> Please refer this link #1743. Still any questions please let us know. Thanks!
Thank you very much!
Yet, I am trying to convert the skeleton into a mesh:


![image](https://user-images.githubusercontent.com/55009565/116045337-8b7cee80-a6a4-11eb-8c2c-f51172550ccc.png)

This is the hand model: MANO.

Thanks!

**Comment by chuoling** [comment]
We don't have immediate plans to provide ways to generate a hand mesh from the 21 hand landmarks.

**Comment by matlab2017** [comment]
> > Please refer this link #1743. Still any questions please let us know. Thanks!
> > Thank you very much!
> > Yet, I am trying to convert the skeleton into a mesh:
> 
> ![image](https://user-images.githubusercontent.com/55009565/116045337-8b7cee80-a6a4-11eb-8c2c-f51172550ccc.png)
> 
> This is the hand model: MANO.
> 
> Thanks!

Have you solved this problem
