### ISSUE TITLE
hand landmark

### ISSUE THREAD

**Issue by warmsh** [google/mediapipe#1938]
Hello, I am currently studying the hand tracking module in mediapipe. I now want to understand the relevant information inside the hand landmark detection model. However, the document only writes about the detected hand area through regression (ie direct coordinate prediction) The 21 3D hand joint coordinates inside are used for precise key point positioning, and no more detailed related information is given. For example, there are several convolutional layers, pooling layers, activation functions and other information inside the model. Can you rely on help from related parties?

**Comment by eknight7** [comment]
Hi @warmsh, you may find some details in https://arxiv.org/pdf/2006.10214.pdf

**Comment by sgowroji** [comment]
Hi @warmsh, Please go through the above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.
