### ISSUE TITLE
MediaPipe feature extractor outputs a corrupted tfrecord 

### ISSUE THREAD

**Issue by divyag9** [google/mediapipe#194]
Hi,

I'm trying to extract the audio and video features from a mp4 video using the youtube-8m mediapipe extractor. I was able to generate the output.tfrecord but when I try to parse the tfrecord I get a DataLoss error.
There was no error produced when generating the  output.tfrecord.
Following is the code snippet used to look inside the output tfrecord and the error that is produced

extracted_tfrecord = "/tmp/mediapipe/output.tfrecord"
for example in tf.python_io.tf_record_iterator(extracted_tfrecord):
    print(tf.train.Example.FromString(example))

---------------------------------------------------------------------------
DataLossError                             Traceback (most recent call last)
<ipython-input-3-a8b0eb2542cb> in <module>
----> 1 for example in tf.python_io.tf_record_iterator(extracted_tfrecord):
      2     print(tf.train.Example.FromString(example))

~/.local/lib/python3.6/site-packages/tensorflow/python/lib/io/tf_record.py in tf_record_iterator(path, options)
    179     while True:
    180       try:
--> 181         reader.GetNext()
    182       except errors.OutOfRangeError:
    183         break

~/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in GetNext(self)
    795 
    796     def GetNext(self):
--> 797         return _pywrap_tensorflow_internal.PyRecordReader_GetNext(self)
    798 
    799     def record(self):

DataLossError: corrupted record at 0

Is there any specific format that is required for the input video? The document just says local video 
Can someone help me with fixing this error.
Thank you!

**Comment by bryanseybold** [comment]
Thank you for reporting this. I just want to make sure I'm understanding this right.
   You're running stage 5 here: https://mediapipe.readthedocs.io/en/latest/youtube_8m.html
   And seeing that the output is corrupt? Does the output file look like it's a reasonable size? Are you able to see anything in the logs from extract_yt8m_features?
   I'll try and reproduce this.

**Comment by divyag9** [comment]
Yes after running stage 5 the output tfrecord that is produced is corrupted. The output tfrecord file size is 48KB. I don't see any errors apart from the deprecated warnings. 
Following is the output after running the extract_yt8m_feature executable

2019-10-23 23:22:38.865072: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2019-10-23 23:22:40.943878: W external/org_tensorflow/tensorflow/core/framework/op_def_util.cc:357] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().


To be precise following are the commands I executed to get the tf record generated.
1.      git clone https://github.com/google/mediapipe.git
2.	mkdir /tmp/mediapipe
3.	cd /tmp/mediapipe
4.	curl -O http://data.yt8m.org/pca_matrix_data/inception3_mean_matrix_data.pb
5.	curl -O http://data.yt8m.org/pca_matrix_data/inception3_projection_matrix_data.pb
6.	curl -O http://data.yt8m.org/pca_matrix_data/vggish_mean_matrix_data.pb
7.	curl -O http://data.yt8m.org/pca_matrix_data/vggish_projection_matrix_data.pb
8.	curl -O http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
9.	tar -xvf /tmp/mediapipe/inception-2015-12-05.tgz
10.	cd mediapipe/
11.    python3 -m mediapipe.examples.desktop.youtube8m.generate_vggish_frozen_graph
12.	python3 -m mediapipe.examples.desktop.youtube8m.generate_input_sequence_example   --path_to_input_video=/home/ubuntu/sample_video.mp4
13. chmod +x ./setup_opencv.sh
14. bazel build -c opt \
  --define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true \
  mediapipe/examples/desktop/youtube8m:extract_yt8m_features
15. ./bazel-bin/mediapipe/examples/desktop/youtube8m/extract_yt8m_features --calculator_graph_config_file=mediapipe/graphs/youtube8m/feature_extraction.pbtxt --input_side_packets=input_sequence_example=/tmp/mediapipe/metadata.tfrecord --output_side_packets=output_sequence_example=/tmp/mediapipe/output.tfrecord

Side note: I tried running the deprecated extract_tfrecords_main.py to generate the video features with the same sample video I used above and it did generate the video features. The size of output tfrecord here was 251KB

**Comment by jiuqiant** [comment]
@divyag9, how long is your video? In generate_input_sequence_example.py, `--clip_end_time_sec` is set to 10 by default. Because of this, the extract_yt8m_features binary only extracts the feature for the first 10 seconds of the video. You can follow the step 4 of [the README.md](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/youtube8m/README.md) to set `--clip_end_time_sec` for your video.

If that doesn't solve your issue, would you mind sharing either the sample video or the output tfrecord file if they are ok to be shared? Thanks.

**Comment by divyag9** [comment]
I already tried using 100 seconds instead of 10 int he end_time, even in that case the output tfrecord was corrupted. The video is 1 minute 41 seconds long.
github won't let me add the mp4 file or the output tfrecord. I can email it if you provide me an address.

**Comment by bryanseybold** [comment]
Can you also try running with --stderrthreshold=0 (or --logtostderr) to get more logging information?

**Comment by bryanseybold** [comment]
Ah, may require `export GLOG_stderrthreshold=1` instead of a command line flag depending on your installation.

**Comment by sedEZ** [comment]
Same problem!
    Finally built it and ran 
``` ./bazel-bin/mediapipe/examples/desktop/youtube8m/extract_yt8m_features``` successfully , but the output.tfrecord still got DataLossError.
    Logs with --stderrthreshold=0 flag are as below.

``` 
$ ./bazel-bin/mediapipe/examples/desktop/youtube8m/extract_yt8m_features   \
--calculator_graph_config_file=mediapipe/graphs/youtube8m/feature_extraction.pbtxt   \
--input_side_packets=input_sequence_example=/tmp/mediapipe/metadata.tfrecord    \
--output_side_packets=output_sequence_example=/tmp/mediapipe/output.tfrecord    \
--stderrthreshold=0
I1026 00:00:25.333202 26899 extract_yt8m_features.cc:45] Get calculator graph config contents: input_side_packet: "input_sequence_example"
input_side_packet: "inception3_pca_mean_matrix"
input_side_packet: "inception3_pca_projection_matrix"
input_side_packet: "vggish_pca_mean_matrix"
input_side_packet: "vggish_pca_projection_matrix"
output_side_packet: "sequence_example_to_serialize"

node {
  calculator: "StringToSequenceExampleCalculator"
  input_side_packet: "STRING:input_sequence_example"
  output_side_packet: "SEQUENCE_EXAMPLE:parsed_sequence_example"
}

node {
  calculator: "UnpackMediaSequenceCalculator"
  input_side_packet: "SEQUENCE_EXAMPLE:parsed_sequence_example"
  output_side_packet: "DATA_PATH:input_file"
  output_side_packet: "RESAMPLER_OPTIONS:packet_resampler_options"
  output_side_packet: "AUDIO_DECODER_OPTIONS:audio_decoder_options"
  node_options: {
    [type.googleapis.com/mediapipe.UnpackMediaSequenceCalculatorOptions]: {
      base_packet_resampler_options {
        frame_rate: 1.0
        base_timestamp: 0
      }
      base_audio_decoder_options {
        audio_stream { stream_index: 0 }
      }
    }
  }
}

# Decode the entire video.
node {
  calculator: "OpenCvVideoDecoderCalculator"
  input_side_packet: "INPUT_FILE_PATH:input_file"
  output_stream: "VIDEO:decoded_frames"
}

# Extract the subset of frames we want to keep.
node {
  calculator: "PacketResamplerCalculator"
  input_stream: "decoded_frames"
  output_stream: "sampled_decoded_frames"
  input_side_packet: "OPTIONS:packet_resampler_options"
}

node {
  calculator: "ImageFrameToTensorCalculator"
  input_stream: "sampled_decoded_frames"
  output_stream: "tensor_frame"
}

node {
  calculator: "TensorFlowSessionFromFrozenGraphCalculator"
  output_side_packet: "SESSION:session"
  node_options: {
    [type.googleapis.com/mediapipe.TensorFlowSessionFromFrozenGraphCalculatorOptions]: {
      graph_proto_path: "/tmp/mediapipe/classify_image_graph_def.pb"
      tag_to_tensor_names {
        key: "IMG_UINT8"
        value: "DecodeJpeg:0"
      }
      tag_to_tensor_names {
        key: "INCEPTION_POOL3"
        value: "pool_3/_reshape:0"
      }
    }
  }
}

node {
  calculator: "TensorFlowInferenceCalculator"
  input_side_packet: "SESSION:session"
  input_stream: "IMG_UINT8:tensor_frame"
  output_stream: "INCEPTION_POOL3:inception3_hidden_activation_single_element_batch"
  node_options: {
    [type.googleapis.com/mediapipe.TensorFlowInferenceCalculatorOptions]: {
      signature_name: ""
      batch_size: 1
      add_batch_dim_to_tensors: false
    }
  }
}

# Remove the batch dimension.
node: {
  calculator: "TensorSqueezeDimensionsCalculator"
  input_stream: "inception3_hidden_activation_single_element_batch"
  output_stream: "inception3_hidden_activation"
  node_options: {
    [type.googleapis.com/mediapipe.TensorSqueezeDimensionsCalculatorOptions]: {
      dim: 0
    }
  }
}

node {
  calculator: "TensorToMatrixCalculator"
  input_stream: "TENSOR:inception3_hidden_activation"
  output_stream: "MATRIX:inception3_hidden_activation_matrix"
}

node {
  calculator: "MatrixSubtractCalculator"
  input_stream: "MINUEND:inception3_hidden_activation_matrix"
  input_side_packet: "SUBTRAHEND:inception3_pca_mean_matrix"
  output_stream: "mean_subtracted_inception3_matrix"
}
node {
  calculator: "MatrixMultiplyCalculator"
  input_stream: "mean_subtracted_inception3_matrix"
  input_side_packet: "inception3_pca_projection_matrix"
  output_stream: "pca_inception3_matrix"
}
node {
  calculator: "MatrixToVectorCalculator"
  input_stream: "pca_inception3_matrix"
  output_stream: "pca_inception3_vf"
}

######################## END OF VISUAL ###########################

######################## BEGIN OF AUDIO ##########################
node {
  calculator: "AudioDecoderCalculator"
  input_side_packet: "INPUT_FILE_PATH:input_file"
  input_side_packet: "OPTIONS:audio_decoder_options"
  output_stream: "AUDIO:audio"
  output_stream: "AUDIO_HEADER:audio_header"
}

node {
  calculator: "AddHeaderCalculator"
  input_stream: "DATA:audio"
  input_stream: "HEADER:audio_header"
  output_stream: "media_audio"
}

# Always convert the audio to mono.
node {
  calculator: "AverageTimeSeriesAcrossChannelsCalculator"
  input_stream: "media_audio"
  output_stream: "mono_waveform"
}

node {
  calculator: "RationalFactorResampleCalculator"
  input_stream: "mono_waveform"
  output_stream: "resampled_waveform"
  node_options: {
    [type.googleapis.com/mediapipe.RationalFactorResampleCalculatorOptions] {
      target_sample_rate: 16000.0
    }
  }
}
node {
  calculator: "SpectrogramCalculator"
  input_stream: "resampled_waveform"
  output_stream: "spectrogram_squared_magnitude"
  node_options: {
    [type.googleapis.com/mediapipe.SpectrogramCalculatorOptions] {
      frame_duration_seconds: 0.025
      frame_overlap_seconds: 0.015
      output_type: SQUARED_MAGNITUDE
    }
  }
}
node {
  calculator: "MelSpectrumCalculator"
  # MelSpectrumCalculator expects SQUARED_MAGNITUDE input, but its output is in
  # linear magnitude units.
  input_stream: "spectrogram_squared_magnitude"
  output_stream: "mel_spectrum_magnitude"
  node_options: {
    [type.googleapis.com/mediapipe.MelSpectrumCalculatorOptions] {
      # Follow the 'wideband' or '16kHz' speech convention.
      channel_count: 64
      min_frequency_hertz: 125.0
      max_frequency_hertz: 7500.0
    }
  }
}
node {
  calculator: "StabilizedLogCalculator"
  input_stream: "mel_spectrum_magnitude"
  output_stream: "log_mel_spectrum_magnitude"
  node_options: {
    [type.googleapis.com/mediapipe.StabilizedLogCalculatorOptions] {
      stabilizer: 0.01
    }
  }
}
node {
  calculator: "TimeSeriesFramerCalculator"
  input_stream: "log_mel_spectrum_magnitude"
  output_stream: "log_mel_spectrum_magnitude_with_context"
  node_options: {
    [type.googleapis.com/mediapipe.TimeSeriesFramerCalculatorOptions] {
      frame_duration_seconds: 0.96
      frame_overlap_seconds: -0.04
    }
  }
}
node {
  calculator: "MatrixToTensorCalculator"
  input_stream: "log_mel_spectrum_magnitude_with_context"
  output_stream: "log_mel_spectrum_magnitude_tensor"
  node_options: {
    [type.googleapis.com/mediapipe.MatrixToTensorCalculatorOptions] {
      transpose: true
    }
  }
}

node {
  calculator: "TensorFlowSessionFromFrozenGraphCalculator"
  output_side_packet: "SESSION:vggish_session"
  node_options: {
    [type.googleapis.com/mediapipe.TensorFlowSessionFromFrozenGraphCalculatorOptions]: {
      graph_proto_path: "/tmp/mediapipe/vggish_new.pb"
      tag_to_tensor_names {
        key: "INPUT"
        value: "vggish/input_features:0"
      }
      tag_to_tensor_names {
        key: "VGGISH"
        value: "vggish/fc2/BiasAdd:0"
      }
    }
  }
}

node {
  calculator: "TensorFlowInferenceCalculator"
  input_side_packet: "SESSION:vggish_session"
  input_stream: "INPUT:log_mel_spectrum_magnitude_tensor"
  output_stream: "VGGISH:vggish_tensor"
  node_options: {
    [type.googleapis.com/mediapipe.TensorFlowInferenceCalculatorOptions]: {
      signature_name: ""
      batch_size: 128
    }
  }
}

node {
  calculator: "TensorToMatrixCalculator"
  input_stream: "REFERENCE:log_mel_spectrum_magnitude_with_context"
  input_stream: "TENSOR:vggish_tensor"
  output_stream: "MATRIX:vggish_matrix"
  node_options: {
    [type.googleapis.com/mediapipe.TensorToMatrixCalculatorOptions] {
      time_series_header_overrides {
        num_channels: 128
        num_samples: 1
      }
    }
  }
}

node {
  calculator: "MatrixSubtractCalculator"
  input_stream: "MINUEND:vggish_matrix"
  input_side_packet: "SUBTRAHEND:vggish_pca_mean_matrix"
  output_stream: "mean_subtracted_vggish_matrix"
}
node {
  calculator: "MatrixMultiplyCalculator"
  input_stream: "mean_subtracted_vggish_matrix"
  input_side_packet: "vggish_pca_projection_matrix"
  output_stream: "pca_vggish_matrix"
}
node {
  calculator: "MatrixToVectorCalculator"
  input_stream: "pca_vggish_matrix"
  output_stream: "pca_vggish_vf"
}

# Store the features in the SequenceExample.
node {
  calculator: "PackMediaSequenceCalculator"
  input_side_packet: "SEQUENCE_EXAMPLE:parsed_sequence_example"
  output_side_packet: "SEQUENCE_EXAMPLE:sequence_example_to_serialize"
  input_stream: "FLOAT_FEATURE_RGB:pca_inception3_vf"
  input_stream: "FLOAT_FEATURE_AUDIO:pca_vggish_vf"
}

# Serialize the SequenceExample to a string for storage.
node {
  calculator: "StringToSequenceExampleCalculator"
  input_side_packet: "SEQUENCE_EXAMPLE:sequence_example_to_serialize"
  output_side_packet: "STRING:output_sequence_example"
}

I1026 00:00:25.356192 26899 extract_yt8m_features.cc:103] Initialize the calculator graph.
I1026 00:00:25.357188 26899 extract_yt8m_features.cc:106] Start running the calculator graph.
I1026 00:00:25.357421 26900 unpack_media_sequence_calculator.cc:298] Created AudioDecoderOptions:
audio_stream {
  stream_index: 0
}
start_time: 1
end_time: 100
I1026 00:00:25.357456 26900 unpack_media_sequence_calculator.cc:320] Created PacketResamplerOptions:
[mediapipe.PacketResamplerCalculatorOptions.ext] {
  frame_rate: 1
  base_timestamp: 0
  start_time: 1000000
  end_time: 100000000
}
2019-10-26 00:00:25.357518: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
I1026 00:00:25.372313 26906 audio_decoder.cc:648] Created audio processor 0x7fcff4022ba0 for file "/home/tl32rodan/Downloads/v1.mp4"
I1026 00:00:25.372673 26906 audio_decoder.cc:376] Opened audio stream (id: 1, channels: 2, sample rate: 44100, time base: 1/44100).
2019-10-26 00:00:26.479502: W external/org_tensorflow/tensorflow/core/framework/op_def_util.cc:357] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
W1026 00:01:20.199743 26905 opencv_video_decoder_calculator.cc:173] Not all the frames are decoded (total frames: 17501 vs decoded frames: 17500).
I1026 00:01:20.200832 26899 extract_yt8m_features.cc:108] Gathering output side packets.
I1026 00:01:20.239042 26899 extract_yt8m_features.cc:132] Success!
```

**Comment by jiuqiant** [comment]
OK, we found the issue: the feature extraction pipeline actually just writes the serialized sequence example to the output.tfrecord. Since that tfrecord file doesn't have necessary header and footer, the tfrecord reader can't read it for sure. Sorry about the inconvenience. we will fix this issue soon. For now, you can do the following to get the content of the sequence example:

```
import tensorflow as tf

extracted_tfrecord = "/tmp/mediapipe/output.tfrecord"
sequence_example = open(extracted_tfrecord, 'rb').read()                           
print(tf.train.SequenceExample.FromString(sequence_example))
```

**Comment by divyag9** [comment]
cool, thanks!
Just to add I had similar output like @sedEZ using the stderrthreshold

**Comment by jiuqiant** [comment]
Made the clarifications in https://github.com/google/mediapipe/commit/fce372d1530964cd6f33fe091f006a23f294a883.
