### ISSUE TITLE
Minimum configuration requirements to run Mediapipe

### ISSUE THREAD

**Issue by lilinxiong** [google/mediapipe#1941]
Android:
         For example, support the lowest CPU, support the lowest Android OS....
IOS: 
         Iphone 8 ? ipheon X ?.....
win desktop:
         CPU, GPU,RAM Size....

I did not find the corresponding instructions in the official documentation.....
Can you help me ?

**Comment by lilinxiong** [comment]
These are all SDK versions and do not indicate the configuration information of the phone. To be exaggerated, can I run it on iPhone 4s?
If it can’t work, do you want to give the minimum supported iPhone model? For example: iPhone 7, iPhone 8.
The same goes for Android.

**Comment by sgowroji** [comment]
Hi @lilinxiong,  We don't have much environment to test with different devices yet and it's one of the plan for our future road map. At present we can state that all the devices which support the  prerequisites while building with android sdk's and  similar for iOS.

**Comment by ksiv** [comment]
Okay. 
 Samsung J1 J120FXXU2ARK1 (2016) Android 5.1.1
successfully installed after building with NKD api_level = 22.
Upon starting all I see is a white screen looks pretty much like not enough resources.
Please make this thread as a poll so we can build sys req.

**Comment by lghasemzadeh** [comment]
> Hi @lilinxiong, We don't have much environment to test with different devices yet and it's one of the plan for our future road map. At present we can state that all the devices which support the prerequisites while building with android sdk's and similar for iOS.

This is a very important issue and providing such these information makes everything easier and faster from user's point of view.

**Comment by lilinxiong** [comment]
> > Hi @lilinxiong, We don't have much environment to test with different devices yet and it's one of the plan for our future road map. At present we can state that all the devices which support the prerequisites while building with android sdk's and similar for iOS.
> 
> This is a very important issue and providing such these information makes everything easier and faster from user's point of view.

Yes, I think so too, I look forward to your results, thank you for your reply, today is the second day of Chinese New Year, Happy Chinese New Year~
