### ISSUE TITLE
Commercial Use about learned model

### ISSUE THREAD

**Issue by name-era** [google/mediapipe#1945]
Shall I use this product as per Apache 2 license including learned model such as .tflite model ?

**Comment by sgowroji** [comment]
Hi @kuwarabbit, Could you please share your use case with complete details. Thanks!

**Comment by kuwarabbit** [comment]
Sorry for not explaining enough.
When we use this product with our SDK product for the purpose of 3d or 2d tracking, do we need to consider license for training data(may not be contained this repo) and learned model?

**Comment by sgowroji** [comment]
Hi @name-era, This https://github.com/google/mediapipe/issues/1290#issuecomment-727150276 will answer your query better.  Thanks!
