### ISSUE TITLE
Some question about face effect solution on Android

### ISSUE THREAD

**Issue by weixinz1** [google/mediapipe#1947]
1. Can I get face landmark in face effect solution on Android?
2. In the example java [file](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect/MainActivity.java#L109), the getPackedData() method can get 16 float numbers and what's the meaning of these numbers

**Comment by mcclanahoochie** [comment]
The pose transformation matrix is defined here https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/modules/face_geometry/protos/face_geometry.proto 

the format is similar to standard opengl transformation matrices http://www.songho.ca/opengl/gl_transform.html#matrix (in column major order)

**Comment by sgowroji** [comment]
Hi @weixinz1, Did you get a chance to go through the above comment. Thanks!

**Comment by sgowroji** [comment]
Hi @weixinz1, Please respond to the above comment. Thanks!

**Comment by weixinz1** [comment]
Problem solved. I'll close this issues @sgowroji
