### ISSUE TITLE
[hand tracker] size of feature map on palm detector

### ISSUE THREAD

**Issue by donguk-dev** [google/mediapipe#1948]
I used your hand tracker model and it worked very well.
I have a question using your palm detector model.

How can this model find big hand or small hand?
 - this model use only 8x8, 16x16 feature map. (original pyramid structure use 32x32, 16x16,8x8,4x4,2x2, 1x1)

Thank you :-)

**Comment by sgowroji** [comment]
Hi @donguk-dev, We have updated our [documentation](https://google.github.io/mediapipe/solutions/hands.html#models). Kindly have a look at reach us back if you still have any queries on it. Thanks!
