### ISSUE TITLE
org_tensorflow download error 

### ISSUE THREAD

**Issue by Lr-2002** [google/mediapipe#1949]
Hi,I'm trying to compile the android apk with bazel on my ubuntu pc.
Now ,i'm facing some problems while doing this.

Downloading org_tensorflow error:
 1. proxy : qv2ray in linux, (I'm i China mainland)
 2. Problem: not able to go throw org_tensorflow 's download 
 
 So ,I've tried  to download org_tensorflow.tar.gz via firefox by the url showed to me.
 And then ,I hope to copy it to the folder which was showed when bazel dumped.
 But things did not work still.
 the command line is just :
 ``` bazel -c opt ....(same to the command in turtial in andorid)  --keep_going``` 
 
 And I tried to put the tar.gz file to org_tensorflow folder .but things didn't changed.
 hoping for your help!

**Comment by Lr-2002** [comment]
Well ,the vpn is not very stable ,and its speed is low (~10kb/s)
While downloading the tar ,It's ~3MB/s

**Comment by sgowroji** [comment]
Hi @Lr-2002, Could you please mention the steps followed to reproduce the above error. Did you use mediapipe in the above for installation? If yes then share the error logs .

**Comment by Lr-2002** [comment]
Well,sorry ,the problem is not settled until now.I'm still seeking for solutions.
And now ,I'd better to state it more precise:

1. When did the problem happened?
    With bazel to build the android sample
    using command ```bazel build -c opt --config=android_arm64 --keep_going mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
```
    The error log:
    ```
    ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   Traceback (most recent call last):
	File "/home/lr-2002/.cache/bazel/_bazel_lr-2002/858766351c9bf1877743094e06ee32df/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/c67f68021824410ebe9f18513b8856ac1c6d4887.tar.gz] to /home/lr-2002/.cache/bazel/_bazel_lr-2002/858766351c9bf1877743094e06ee32df/external/org_tensorflow/temp172222072687291382/c67f68021824410ebe9f18513b8856ac1c6d4887.tar.gz: Premature EOF
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/c67f68021824410ebe9f18513b8856ac1c6d4887.tar.gz] to /home/lr-2002/.cache/bazel/_bazel_lr-2002/858766351c9bf1877743094e06ee32df/external/org_tensorflow/temp172222072687291382/c67f68021824410ebe9f18513b8856ac1c6d4887.tar.gz: Premature EOF
```

2. What things did i do?
    1. Download the tensorflow.tar.gz mentioned 
    2. copy it into the folder and replace the former tar.gz
    3. rerun the command mentioned.
    But things didn't changed .
    
3. What's my environment?
    1. bazel 3.7.2
    2. mediapipe updated.
    3. VPN via qv2ray in China (not very stable)
4. My problem:
    How to fix the problem ?

**Comment by Lr-2002** [comment]
Well ,upto now ,things has been better while new problem occured
1. The former problem was solved by 
     1. re-open a folder to re-do the process (indeed it fixed lots of problems which was not setlled former)
2. A new problem happend :
    ```ERROR: /home/lr-2002/code/test/mediapipe-master/mediapipe/WORKSPACE:246:23: //external:android/crosstool depends on @androidndk//:default_crosstool in repository @androidndk which failed to fetch. no such package '@androidndk//': Could not read RELEASE.TXT in Android NDK: /home/lr-2002/Android/Sdk/ndk-bundle/android-ndk-r18b/RELEASE.TXT (?????????) Unable to read the Android NDK at /home/lr-2002/Android/Sdk/ndk-bundle/android-ndk-r18b, the path may be invalid. Is the path in android_ndk_repository() or ANDROID_NDK_HOME set correctly? If the path is correct, the contents in the Android NDK directory may have been modified.
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: Analysis failed
```
The $ANDROID_NDK_HOME is ../Sdk/ndk/<version> while the bazel detected the ../Sdk/ndk-bundle which is not ok

And I deleted the ndk-bundle but noting changed.
I'm still seeking for a solution ,plz

**Comment by Lr-2002** [comment]
What's more :
The ndk and sdk are all installed by Android Studio 

And using the setup_android_sdk_ndk.sh ,it showed :
```Found existing $ANDROID_HOME=/home/lr-2002/Android/Sdk and $ANDROID_NDK_HOME=/home/lr-2002/Android/Sdk/ndk/20.0.5594570
Bazel will locate Android SDK and NDK automatically.```
It doesn't seem that ndk could be a problem?

**Comment by Lr-2002** [comment]
Well ,things have been better with close the terminal and reopen it

**Comment by Lr-2002** [comment]
Then I faced the problem ``` duplicate keyword argument: path ```
just turn to WORKSPACE and delete the path duplicated

**Comment by sgowroji** [comment]
Thanks for sharing the clear details. Could you please look at this [reference](https://github.com/google/mediapipe/issues/1531#issuecomment-764887222).

**Comment by Lr-2002** [comment]
Oh ,Yeah ,thanks a lot 
I'll try it latter 
BTW,sorry for being late to reply

**Comment by sgowroji** [comment]
As we see your query addressed,  We are closing this issue now. Feel free to reopen if the same issue exists. Thanks
