### ISSUE TITLE
the options of TfliteTensorsToClassificationCalculator miss a field 'num_classes'

### ISSUE THREAD

**Issue by menghaocheng** [google/mediapipe#195]
there is a 'num_classes' in the Usage example of TfLiteTensorsToClassificationCalculator (mediapipe\calculators\tflite\tflite_tensors_to_classification_calculator.cc):
`
// Usage example:
// node {
//   calculator: "TfLiteTensorsToClassificationCalculator"
//   input_stream: "TENSORS:tensors"
//   output_stream: "CLASSIFICATIONS:classifications"
//   options: {
//     [mediapipe.TfLiteTensorsToClassificationCalculatorOptions.ext] {
//       num_classes: 1024
//       min_score_threshold: 0.1
//       label_map_path: "labelmap.txt"
//     }
//   }
// }
`

But, there is no 'num_classes' in the message TfLiteTensorsToClassificationCalculatorOptions at all (mediapipe\calculators\tflite\tflite_tensors_to_classification_calculator.proto):
`
message TfLiteTensorsToClassificationCalculatorOptions {
  extend .mediapipe.CalculatorOptions {
    optional TfLiteTensorsToClassificationCalculatorOptions ext = 266399463;
  }

  // Score threshold for perserving the class.
  optional float min_score_threshold = 1;
  // Number of highest scoring labels to output.  If top_k is not positive then
  // all labels are used.
  optional int32 top_k = 2;
  // Path to a label map file for getting the actual name of class ids.
  optional string label_map_path = 3;
}
`

I think that maybe the TfLiteTensorsToClassificationCalculatorOptions miss the field of 'num_classes', Pls recheck it, Thk you.

**Comment by fenollp** [comment]
See #172
