### ISSUE TITLE
how to run solution samples for desktop on headless device? [no display connected] 

### ISSUE THREAD

**Issue by AndreV84** [google/mediapipe#1950]
I was trying to run webcam desktop gpu examples but it fails due to EGL errors
tried virtualGL but it did not get to work either
any ideas?

**Comment by sgowroji** [comment]
Hi @AndreV84, Can you share your issue reproduction steps and error logs. Thanks!

**Comment by AndreV84** [comment]
@sgowroji 
Hi, thank you for following up!
Could you extend if there is any way to run mediapipe solutions on headless device, please? using webcam desktop GPU solutions somwhow?

**Comment by sgowroji** [comment]
I believe @mcclanahoochie  will be the right person to guide you. But if you have already tried and facing some errors, It would be great if you can share it here .

**Comment by AndreV84** [comment]
there was no particular error as there are many diverse errors in accordance to the method tried
but in addition to attempt to run over SSH with -''X" I also tried with virtualGL

The specificity of the setup is that there is no display at all but remote access to the target device

Also there is a difference if to execute it on Screen 0 with headless Xorg versus on Screen 1 with remote VNC in headless mode;
 
the reference on how virtualgl was implemented is https://forums.developer.nvidia.com/t/tutorial-how-to-install-virtualgl-and-turbovnc-on-jetson-nano/ , but while CUDA etc examples would run remotely through VNC, the mediapipe samples won't work  failing with various error messages that would depend on execution parameters, but mostly eGL.

E.g. for ssh -X
```
 GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live_gpu.pbtxt
I20210429 07:42:39.245932  7483 demo_run_graph_main_gpu.cc:52] Get calculator graph config contents: # MediaPipe graph that performs multi-hand tracking with TensorFlow Lite on GPU.
# Used in the examples in
# mediapipe/examples/android/src/java/com/mediapipe/apps/handtrackinggpu.

# GPU image. (GpuBuffer)
input_stream: "input_video"

# GPU image. (GpuBuffer)
output_stream: "output_video"
# Collection of detected/predicted hands, each represented as a list of
# landmarks. (std::vector<NormalizedLandmarkList>)
output_stream: "hand_landmarks"

# Generates side packet cotaining max number of hands to detect/track.
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:num_hands"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet { int_value: 2 }
    }
  }
}

# Detects/tracks hand landmarks.
node {
  calculator: "HandLandmarkTrackingGpu"
  input_stream: "IMAGE:input_video"
  input_side_packet: "NUM_HANDS:num_hands"
  output_stream: "LANDMARKS:hand_landmarks"
  output_stream: "HANDEDNESS:handedness"
  output_stream: "PALM_DETECTIONS:palm_detections"
  output_stream: "HAND_ROIS_FROM_LANDMARKS:hand_rects_from_landmarks"
  output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:hand_rects_from_palm_detections"
}

# Subgraph that renders annotations and overlays them on top of the input
# images (see hand_renderer_gpu.pbtxt).
node {
  calculator: "HandRendererSubgraph"
  input_stream: "IMAGE:input_video"
  input_stream: "DETECTIONS:palm_detections"
  input_stream: "LANDMARKS:hand_landmarks"
  input_stream: "HANDEDNESS:handedness"
  input_stream: "NORM_RECTS:0:hand_rects_from_palm_detections"
  input_stream: "NORM_RECTS:1:hand_rects_from_landmarks"
  output_stream: "IMAGE:output_video"
}
I20210429 07:42:39.248008  7483 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
I20210429 07:42:39.257933  7483 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
E20210429 07:42:39.335443  7483 demo_run_graph_main_gpu.cc:198] Failed to run the graph: ; Unable to initialize EGLpipe/gpu/gl_context_egl.cc:162) 
```

**Comment by AndreV84** [comment]
```
glxinfo | grep -i opengl
```
on Display :1.0 would return:
```
 glxinfo | grep -i opengl
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 10.0.0, 128 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.0.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 20.0.8
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```
on DISPLAY=:0
```
glxinfo | grep -i opengl
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA Tegra X1 (nvgpu)/integrated
OpenGL core profile version string: 4.6.0 NVIDIA 32.5.1
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 32.5.1
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 32.5.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Comment by AndreV84** [comment]
I can run the sample on Display 0, but there are no outputs that I could see but text outputs

**Comment by AndreV84** [comment]
as there is no display on display 0/ Screen 0, but runnig Xorg session

**Comment by mcclanahoochie** [comment]
Everything should work on a remote machine, except for the visualization GUI. 
You'll need to modify the demo_run_graph_main_gpu.cc to save a video to disk you can view later (say, with [opencv video writer](https://docs.opencv.org/3.4/dd/d9e/classcv_1_1VideoWriter.html)) 



try running
`export DISPLAY=:0
` 
with various display numbers before running the mediapipe example 


you can find all the displays via:
`cd /tmp/.X11-unix && for x in X*; do echo ":${x#X}"; done ; cd -`

**Comment by sgowroji** [comment]
Hi @AndreV84, Did you try the above solution. Thanks!

**Comment by AndreV84** [comment]
It will take time to figure out how to adjust the code  using opencv imshow;
Iw illtry other proposed steps though

**Comment by sgowroji** [comment]
Thanks for sharing the update. We are closing this issue now. Please feel free to reopen the above issue if it is still persists.

**Comment by zwfcrazy** [comment]
@AndreV84 Hi, how do you enable headless xorg on DISPLAY 0? I can't even make this step work...

**Comment by AndreV84** [comment]
@zwfcrazy there is turbovnc thing
https://forums.developer.nvidia.com/t/tutorial-how-to-install-virtualgl-and-turbovnc-on-jetson-nano/175767

**Comment by zwfcrazy** [comment]
> @zwfcrazy there is turbovnc thing
> https://forums.developer.nvidia.com/t/tutorial-how-to-install-virtualgl-and-turbovnc-on-jetson-nano/175767

Is there any way that does not involve VNC?
I tried this https://chadrick-kwag.medium.com/configuring-x-server-on-headless-server-a8b5c3bc7d9
but it didn't work out for me, not sure what's wrong...
