### ISSUE TITLE
Iris tracking using video as input, but the output video gets shorter...

### ISSUE THREAD

**Issue by 04633435** [google/mediapipe#1952]
Hi there, I am working on the iris tracking graph using the video as input. But I encountered a strange problem, that I fed an 8k 15s clip into the pipeline,  but what I got is a 2s video output.

I tested it on other three clips with different duration and resolutions (1) 4k 15s, (2) FHD 11s, and (3) FHD 38s. The outputs are the same, a 2s video with 65 frames extracted by ffmpeg.

And then I modified the graph by just keeping the OpenCV decode and encode nodes and test it again with the 4K 15s clip. The output is still a 2s video.

The environment I am working on is AMD Ryzen Threadripper 2990WX and two GeForce RTX 2080 SUPER on Linux 18.04.

Is there anyone encounter this problem before?
If you need more information about the running environment, feel free to let me know!

Thanks in advance : )

**Comment by anvuong48** [comment]
Hi,

I also faced to this problem while tracking iris. Did you find solution for that?

thank you in advance

**Comment by 04633435** [comment]
> Hi,
> 
> I also faced to this problem while tracking iris. Did you find solution for that?
> 
> thank you in advance

Hi,

In my case, I found the problem is caused by the mismatching of the resolution saved in the prestream header information and the resolution of the output video stream at `OpenCVencodeCalculator` because my output video stream is cropped out of the input video stream. In the end, I used the `prestream calculator` to get the new header information including the modified resolution, and then sent it to the OpenCVencodeCalculator. The output video works well then.

**Comment by anvuong48** [comment]
Hi,

Thank you very much for your reply,

Could you tell me more details how you changed the _**prestream calculator**_ to get the new header information including the modified resolution please? And how could you send it to **_OpenCVencodeCalculator_**?

As following is my code with **_OpenCvVideoDecoderCalculator_**, **_VideoPreStreamCalculator_** **_OpenCvVideoEncoderCalculator_**
`node {
  calculator: "OpenCvVideoDecoderCalculator"
  input_side_packet: "INPUT_FILE_PATH:input_video_path"
  output_stream: "VIDEO:input_video"
  output_stream: "VIDEO_PRESTREAM:input_video_header"
}

# Create a new video stream header
# This step only has one node. VideoPreStreamCalculator
node {
  calculator: "VideoPreStreamCalculator"
  input_stream: "FRAME:cropped_right_eye_image"
  input_stream: "VIDEO_PRESTREAM:input_video_header"
  output_stream: "cropped_frames_video_header"
}

node {
  calculator: "OpenCvVideoEncoderCalculator"
  input_stream: "VIDEO:output_video"
  input_stream: "VIDEO_PRESTREAM:cropped_frames_video_header"
  input_side_packet: "OUTPUT_FILE_PATH:output_video_path"
  node_options: {
    [type.googleapis.com/mediapipe.OpenCvVideoEncoderCalculatorOptions]: {
      codec: "avc1"
      video_format: "mp4"
    }
  }
}
`
Thank you very much again and hope for your reply.
