### ISSUE TITLE
Error parsing text-format mediapipe.CalculatorGraphConfig could not find type in google.protobuf.Any.

### ISSUE THREAD

**Issue by aoxipo** [google/mediapipe#1953]
i try to run the face_mesh desktop .and i copy iris code and changed some configuration, It's working very well in ubuntu, but get error in windows10. here is error log:

`[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:309] Error parsing text-format mediapipe.CalculatorGraphConfig: 38:74: Could not find type `
```
"type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions" stored in google.protobuf.Any.
F20210429 16:30:01.449714  2212 parse_text_proto.h:32] Check failed: ParseTextProto(input, &result)
```
```
*** Check failure stack trace: ***
    @   00007FFDB04B598B  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FFDB04B4729  public: __cdecl google::LogMessageFatal::~LogMessageFatal(void) __ptr64
    @   00007FFDB0349E69  public: class std::basic_ostream<char,struct std::char_traits<char> > * __ptr64 __cdecl google::base::CheckOpMessageBuilder::ForVar1(void) __ptr64
   @   00007FFDB034A39D  public: class std::basic_ostream<char,struct std::char_traits<char> > * __ptr64 __cdecl google::base::CheckOpMessageBuilder::ForVar1(void) __ptr64
    @   00007FFDB034CC5B  public: void __cdecl google::LogMessage::LogStream::set_ctr(int) __ptr64
    @   00007FFDB034D6EE  test_process
    @   00007FF781A810F2  (unknown)
    @   00007FF781A81374  (unknown)
    @   00007FFDF34B7034  BaseThreadInitThunk
    @   00007FFDF4602651  RtlUserThreadStart

```
I don't understand what‘s wrong,i try to copy file under the path,but i noticed that is the lib not exist path,  ,plz help me.

**Comment by sgowroji** [comment]
Hi @aoxipo, Could you help with the steps performed to reproduce the above error in windows10.

**Comment by aoxipo** [comment]
> Hi @aoxipo, Could you help with the steps performed to reproduce the above error in windows10.

ok， here is my steps ：
I follow the tutorial https://github.com/bazelbuild/bazel/tree/master/examples/windows/dll to build a dll 
which can be used by  
load_dll_at_run_time.cpp
```
windows_dll_library(
    name = "MediapipeTest",
    srcs = ["face_mesh_out.cc"],
    hdrs = ["face_mesh_out.h"],
    # Define COMPILING_DLL to export symbols during compiling the DLL.
    # See hello-library.h
    copts = ["/DCOMPILING_DLL"],
    deps = [
        "//mediapipe/calculators/util:landmarks_to_render_data_calculator",
        "//mediapipe/framework/formats:landmark_cc_proto",
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/formats:image_frame",
        "//mediapipe/framework/formats:image_frame_opencv",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",            
        "//mediapipe/framework/port:file_helpers",
        "//mediapipe/framework/port:opencv_highgui",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:opencv_video",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
    ],
)
```
```

cc_binary(
    name = "load_dll_at_run_time",
    srcs = ["load_dll_at_run_time.cpp"],
    data = [":MediapipeTest.dll"],
)

```
i using command 
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D:\Anaconda3\envs\my_test_mp\python.exe" mediapipe/examples/desktop/face_mesh:load_dll_at_run_time`
and i  get  load_dll_at_run_time.exe 、MediapipeTest.dll 

i run load_dll_at_run_time.exe in the mediapipe root directory

and then  i get the error .
Thank you for your help！！！！！！！！！！！！
i try to sovle this question this few days but i fail a lot，i hope can get some constructive suggestion. 
by the way ， it work well when i just using cc_binary to build a face_mesh ,but error in build a dll,
and also work well in ubuntu whatever build binary or build so

**Comment by jiuqiant** [comment]
I never built mediapipe windows dll. However, I think you need to put all calculators in the deps field of the "MediapipeTest" windows_dll_library rule. Probably you need to add either https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/face_mesh/BUILD#L25 or https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/face_mesh/BUILD#L36 into the deps field.

**Comment by aoxipo** [comment]
> I never built mediapipe windows dll. However, I think you need to put all face mesh calculators in the deps field of the "MediapipeTest" windows_dll_library rule. Probably you need to add either
> 
> https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/face_mesh/BUILD#L25
> 
> or
> https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/face_mesh/BUILD#L36
> 
> into the deps field.

Think you！！！！！！！！！！！！！！
i really stupid ，i add this deps in Ubuntu and forget add it in win10，
whatever， think you very much！！！！！！！！
if you have interested about mediapipe to build dll in win10，please let me know， i can help you！！！！！！！！！
