### ISSUE TITLE
How to call USB camera ？

### ISSUE THREAD

**Issue by DandyLorenz** [google/mediapipe#1955]
The need to use a USB camera is important,whether it is to extend the method in the  CameraXPreviewHelper class or provide an additional interface.
My usb camera is Logitecch C270,I use Android version 8.1.Is there a plan to update the usb camera? Please guide me how to implement it how to call USB camera, thank you

**Comment by sgowroji** [comment]
Hi @DandyLorenz, Did you get a chance to go through this [documentation](https://google.github.io/mediapipe/getting_started/hello_world_android.html#using-the-camera-via-camerax). What is the error are you facing while connecting with USB camera. If you can see any logs please share us. Thanks

**Comment by sgowroji** [comment]
Hi @DandyLorenz, Could you please respond to my above comment. Thanks!

**Comment by DandyLorenz** [comment]
Yes, sir. I got the message two days ago.I've solved it for the time being. For a USB camera inserted into a large tablet device, you can use the rear camera parameters to set it. It works very well.Thank you, sir

**Comment by akash901** [comment]
Hello @DandyLorenz , I am working on similar problem of getting USB camera integrated with Mediapipe, check #2053 . Can you guide me with your integration steps. Thank you.

**Comment by CodeGather** [comment]
> 是的先生。前两天收到消息，暂时解决了。对于插入大型平板设备的 USB 摄像头，您可以使用后置摄像头参数进行设置。效果很好，谢谢楼主

Hello, how did you solve it? Can you share your code

**Comment by Sreerag-ibtl** [comment]
@DandyLorenz Can you elaborate a bit? Since mediapipe is using CameraX, I was having the hunch that the USB camera is not supported. Wondering how you did it?

**Comment by zhanghuaizhe** [comment]
Since mediapipe is using CameraX, I was having the hunch that the USB camera is not supported. Wondering how you did it?

**Comment by HOLDfoot** [comment]
I also encounter the question that official demo doesn't support usb camera. because of the CameraXPreviewHelper use camerax while camerax doesn't support usb camera. I am glad to find mediapipe's demo (https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example) can resolve our requirement. only because the demo use camerax but camera2 or camera1, I have to take a long time to research many mediapipe code to adapt out project

**Comment by HOLDfoot** [comment]
@sgowroji My issue reproduce need one android board with usb camera. when i use camera1 api, I can open camera by 
```java
Camera.open(0) // 0, 1, 2, 3
```
but now the demo use cameraX, only support front and back camera. You can use the above handware and this (https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example)  software to reproduce the issue.
