### ISSUE TITLE
Calculator facelandmarkfrontgpu__facedetectionfrontgpu__TensorsToDetectionsCalculator not found.

### ISSUE THREAD

**Issue by ben-xD** [google/mediapipe#1956]
This library, [@mediapipe/face_mesh](https://www.npmjs.com/package/@mediapipe/face_mesh) is not open sourced yet, and I am not able to see what is causing it to crash.

I unfortunately get an unhelpful error message, could someone help me diagnose this issue?

The app works fine for a few minutes, but suddenly, this error message occurs. The [repo](https://github.com/ben-xD/skelly) is here. I am using React, NextJS, and ThreeJS.
```
Uncaught (in promise) RuntimeError: abort(undefined) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:68161)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:68337)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:42224)
    at _abort (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:180941)
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[10184]:0x49cb92
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[2299]:0x73f5a
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[2301]:0x73fa7
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[845]:0x20b23
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[2302]:0x74028
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[1209]:0x36916
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[1547]:0x492b8
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7794]:0x3f11f1
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7640]:0x3e551e
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7637]:0x3e4a76
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7624]:0x3e3e67
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7535]:0x3de07f
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7549]:0x3df86a
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7444]:0x3d9f8f
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[514]:0xe9b2
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[501]:0xd6d1
    at SolutionWasm$send [as send] (eval at new_ (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:1:1), <anonymous>:9:1)
    at ja.eval [as h] (webpack-internal:///./node_modules/@mediapipe/face_mesh/face_mesh.js:39:468)
    at R (webpack-internal:///./node_modules/@mediapipe/face_mesh/face_mesh.js:10:296)
    at ma.next (webpack-internal:///./node_modules/@mediapipe/face_mesh/face_mesh.js:11:90)
    at k (webpack-internal:///./node_modules/@mediapipe/face_mesh/face_mesh.js:22:318)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:42255)
    at _abort (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:180941)
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[10184]:0x49cb92
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[2299]:0x73f5a
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[2301]:0x73fa7
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[845]:0x20b23
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[2302]:0x74028
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[1209]:0x36916
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[1547]:0x492b8
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7794]:0x3f11f1
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7640]:0x3e551e
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7637]:0x3e4a76
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7624]:0x3e3e67
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7535]:0x3de07f
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7549]:0x3df86a
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[7444]:0x3d9f8f
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[514]:0xe9b2
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.wasm:wasm-function[501]:0xd6d1
    at SolutionWasm$send [as send] (eval at new_ (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:1:1), <anonymous>:9:1)
    at ja.eval [as h] (webpack-internal:///./node_modules/@mediapipe/face_mesh/face_mesh.js:39:468)
    at R (webpack-internal:///./node_modules/@mediapipe/face_mesh/face_mesh.js:10:296)
    at ma.next (webpack-internal:///./node_modules/@mediapipe/face_mesh/face_mesh.js:11:90)
    at k (webpack-internal:///./node_modules/@mediapipe/face_mesh/face_mesh.js:22:318)
```

**Comment by ben-xD** [comment]
Perhaps the long list of warning could be a sign something is wrong?

For example, `Calculator facelandmarkfrontgpu__facedetectionfrontgpu__TensorsToDetectionsCalculator not found.`


![Screenshot 2021-04-29 at 17 19 50](https://user-images.githubusercontent.com/24711048/116584317-1fea8980-a90f-11eb-871c-b4815fc685b2.png)

**Comment by ben-xD** [comment]
Solved by calling `faceMesh.close()`, which I did not see documented, but autocomplete in my IDE helped me.

**Comment by tyrmullen** [comment]
That is an error on our side, and will be fixed in the next release.  But I think it's unrelated to your crash; even with the error reported, nothing seems to be crashing for me.  Does the MediaPipe FaceMesh CodePen demo crash for you as well?

**Comment by ben-xD** [comment]
Thanks for your message @tyrmullen, looking forward to the fix for the warnings

With regards to the crash, It does take a good few minutes without doing anything (10 minutes?) to happen, you could try https://call.orth.uk/video-room or see the screenshot which I've just generated from that page. The face mesh at this point of the screenshot is frozen, but the video footage still runs.

![Screenshot 2021-04-29 at 22 06 03](https://user-images.githubusercontent.com/24711048/116618540-18d77180-a937-11eb-8291-1167b9d79d96.png)

For privacy: The camera feed is not uploaded, but a websocket connection is made to make a connection to find other users (its a work in progress app), but this is a connection with a WebSocket service (Ably). The repo is [here](https://github.com/ben-xD/skelly), which was linked before.

I'd love to learn more about how the models are used in the browser, through wasm, but don't really know where to start.

**Comment by ben-xD** [comment]
I noticed:`Cannot enlarge memory, asked to go up to 2147487744 bytes, but the limit is 2147483648 bytes!`, which is 2GB. I've got 32GB memory on my machine, and lots of it is free.

**Comment by tyrmullen** [comment]
That definitely sounds like something is leaking memory in the WebAssembly module-- one way this can happen is if you hold on to references from one Solution when instantiating another (are you using multiple Solutions instances?).  If this OOM error is occurring in *just* the CodePen demo, then please let me know.  Otherwise, it sounds like this is the same issue as [#1937](https://github.com/google/mediapipe/issues/1937) in nature, so closing as duplicate to consolidate replies there.

**Comment by ben-xD** [comment]
Thanks @tyrmullen 

I'm not using multiple solutions, I am just instantiating one FaceMesh instance, and use this throughout the rest of the app. This is definitely not the same cause as https://github.com/google/mediapipe/issues/1937 where the author was " instantiating multiple copies of Holistic". To be extra careful, I placed a debugger where the FaceMesh is instantiated, and waited for the error again. The debugger only pauses once (when the app launches), and never again.

I also `close` the solution when needed. In my case, it's when the whole app is closed. This doesn't really matter because I only ever have 1 solution running and this happens right at the end.

I've tried to document my code quite well, I instantiate it once [here](https://github.com/ben-xD/Skelly/blob/main/web/public/ts/MediaPipeFaceMeshCalculator.ts). This is called in [here](https://github.com/ben-xD/Skelly/blob/main/web/public/ts/VideoRenderer.ts).

**Comment by ben-xD** [comment]
Update: Although the chrome performance tab doesn't show high usage, the **memory** tab does. I have a feeling its me not calling `.dispose` on the three.js resources, which keep hold of the Arrays which are showing up as ArrayBuffer (900MB retained size).

There are a bunch of words I need to learn now (retained, shallow, distance), as well as clearing three.js resources when I'm done with them. Thanks for your help.

 ![Screenshot 2021-05-01 at 01 28 00](https://user-images.githubusercontent.com/24711048/116765331-78f41380-aa1c-11eb-9974-82b7703e9341.png)

**Comment by ben-xD** [comment]
Update: its not three.js at all, it seems to be a memory leak in MediaPipe, very similar issue to https://github.com/google/mediapipe/issues/1937
