### ISSUE TITLE
Error while build extract_yt8m_features with CUDA support

### ISSUE THREAD

**Issue by qllb** [google/mediapipe#1957]
Hello
I'm building YouTube-8M feature extraction with GPU support by [this instruction](https://google.github.io/mediapipe/getting_started/gpu_support.html) 

`bazel build -c opt --verbose_failures --config=cuda --spawn_strategy=local --define no_aws_support=true --copt -DMESA_EGL_NO_X11_HEADERS mediapipe/examples/desktop/youtube8m:extract_yt8m_features
`

and getting an error

ERROR: /home/user/mediapipe/mediapipe/framework/formats/BUILD:158:11: C++ compilation of rule '//mediapipe/framework/formats:location' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/execroot/mediapipe && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda-11.3/targets/x86_64-linux/lib,/usr/local/cuda-11/lib64 \
    PATH=/usr/local/cuda-11/bin:/home/user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games \
    PWD=/proc/self/cwd \
    TF_NEED_CUDA=1 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/mediapipe/framework/formats/_objs/location/location.d '-frandom-seed=bazel-out/k8-opt/bin/mediapipe/framework/formats/_objs/location/location.o' -iquote . -iquote bazel-out/k8-opt/bin -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/com_github_glog_glog -iquote bazel-out/k8-opt/bin/external/com_github_glog_glog -iquote external/com_github_gflags_gflags -iquote bazel-out/k8-opt/bin/external/com_github_gflags_gflags -iquote external/linux_opencv -iquote bazel-out/k8-opt/bin/external/linux_opencv -Ibazel-out/k8-opt/bin/external/com_github_glog_glog/_virtual_includes/default_glog_headers -Ibazel-out/k8-opt/bin/external/com_github_gflags_gflags/_virtual_includes/gflags -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/k8-opt/bin/external/zlib -isystem external/linux_opencv/include -isystem bazel-out/k8-opt/bin/external/linux_opencv/include -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIE -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -w -DMESA_EGL_NO_X11_HEADERS '-std=c++17' -c mediapipe/framework/formats/location.cc -o bazel-out/k8-opt/bin/mediapipe/framework/formats/_objs/location/location.o)
Execution platform: @local_execution_config_platform//:platform
In file included from /usr/include/c++/8/ext/string_conversions.h:41,
                 from /usr/include/c++/8/bits/basic_string.h:6400,
                 from /usr/include/c++/8/string:52,
                 from /usr/include/c++/8/stdexcept:39,
                 from /usr/include/c++/8/array:39,
                 from /usr/include/c++/8/tuple:39,
                 from /usr/include/c++/8/bits/unique_ptr.h:37,
                 from /usr/include/c++/8/memory:80,
                 from ./mediapipe/framework/formats/location.h:26,
                 from mediapipe/framework/formats/location.cc:15:
/usr/include/c++/8/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/youtube8m:extract_yt8m_features failed to build

**Comment by sgowroji** [comment]
Hi @qllb, Can you try this [workaround](https://github.com/google/mediapipe/issues/1564#issuecomment-779391548). If still the error exists,  let us know. Thanks!

**Comment by qllb** [comment]
Repeated this with freshly installed ubuntu_18.04 and cuda-10-1
, got similar error 

ERROR: /home/user/mediapipe/mediapipe/util/BUILD:45:11: C++ compilation of rule '//mediapipe/util:audio_decoder' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/execroot/mediapipe && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.2/lib64 \
    PATH=/home/user/mediapipe/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
    TF_NEED_CUDA=1 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/mediapipe/util/_objs/audio_decoder/audio_decoder.d '-frandom-seed=bazel-out/k8-opt/bin/mediapipe/util/_objs/audio_decoder/audio_decoder.o' -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' -iquote . -iquote bazel-out/k8-opt/bin -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/com_github_glog_glog -iquote bazel-out/k8-opt/bin/external/com_github_glog_glog -iquote external/com_github_gflags_gflags -iquote bazel-out/k8-opt/bin/external/com_github_gflags_gflags -iquote external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/linux_ffmpeg -iquote bazel-out/k8-opt/bin/external/linux_ffmpeg -Ibazel-out/k8-opt/bin/external/com_github_glog_glog/_virtual_includes/default_glog_headers -Ibazel-out/k8-opt/bin/external/com_github_gflags_gflags/_virtual_includes/gflags -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/k8-opt/bin/external/zlib -isystem external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/linux_ffmpeg/include -isystem bazel-out/k8-opt/bin/external/linux_ffmpeg/include -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIE -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -w -DMESA_EGL_NO_X11_HEADERS '-std=c++17' -c mediapipe/util/audio_decoder.cc -o bazel-out/k8-opt/bin/mediapipe/util/_objs/audio_decoder/audio_decoder.o)
Execution platform: @local_execution_config_platform//:platform
In file included from /usr/include/c++/7/ext/string_conversions.h:41:0,
                 from /usr/include/c++/7/bits/basic_string.h:6361,
                 from /usr/include/c++/7/string:52,
                 from ./mediapipe/util/audio_decoder.h:20,
                 from mediapipe/util/audio_decoder.cc:15:
/usr/include/c++/7/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/youtube8m:extract_yt8m_features failed to build

**Comment by lottopotato** [comment]
Hi @qllb, I face same problem. Have you solved it?

**Comment by qllb** [comment]
@lottopotato, unfortunately no 
just processed everything with CPU

**Comment by sgowroji** [comment]
Did you try this https://github.com/google/mediapipe/issues/1983#issuecomment-833616888. Seems there was an issue in tensorflow_inference_calculator.cc file
