### ISSUE TITLE
Get landmarks and iris points in the Iris tracking project in javascript 

### ISSUE THREAD

**Issue by Sun1718** [google/mediapipe#1960]
Hello ,
I want to attach a new Listener to get landmarks and iris points (in https://viz.mediapipe.dev/demo/iris_tracking). I've added this line in the "default_demo_bin.js" in "module$contents$google3$third_party$mediapipe$web$default_demo_VideoController.prototype.populateDemoSelector" function, but it doesn't work.

this.api.attachListener("irisanddepthrenderergpu__right_eye_contour_landmarks", { onNumber: function (c) { console.log(c); } });
this.api.attachListener("irisanddepthrenderergpu__iris_landmarks", { onString: function (s) { console.log(s); } });

could you please help me how can I do this?

**Comment by mhays-google** [comment]
This is a closed source project, and we don't support any sort of editing.  But, as a fellow hacker:

populateDemoSelector fills out a drop down with different mp4 names... I don't even think this code is reachable in the public demo.  The function you are probably looking for is `module$contents$google3$third_party$mediapipe$web$default_demo_SingleFrameController.prototype.attachListeners`

I haven't checked to see if `irisanddepthrenderergpu__right_eye_contour_landmarks` or `irisanddepthrenderergpu__iris_landmarks` are legal stream names.  But if they are actually present in the graph, this should probably work.
