### ISSUE TITLE
can't install pip install mediapipe 

### ISSUE THREAD

**Issue by soumik2012** [google/mediapipe#1961]
This is error is showing me 
![image](https://user-images.githubusercontent.com/66599363/116663676-11ef4400-a9b5-11eb-9c38-f969ae941935.png)

**Comment by sgowroji** [comment]
Hi @soumik2012,  What is your python version. Please check this reference https://github.com/google/mediapipe/issues/1466#issue-779706556,

**Comment by soumik2012** [comment]
@sgowroji  Python 3.8.3 is my version

**Comment by sgowroji** [comment]
Linux arm64 Python packages are not officially supported. You can either follow https://google.github.io/mediapipe/getting_started/python#building-mediapipe-python-package and https://github.com/jiuqiant/mediapipe_python_aarch64 to build it on your local machine or try https://github.com/jiuqiant/mediapipe_python_aarch64/blob/main/mediapipe-0.8.1-cp38-cp38-linux_aarch64.whl.

**Comment by soumik2012** [comment]
> Linux arm64 Python packages are not officially supported. You can either follow https://google.github.io/mediapipe/getting_started/python#building-mediapipe-python-package and https://github.com/jiuqiant/mediapipe_python_aarch64 to build it on your local machine or try https://github.com/jiuqiant/mediapipe_python_aarch64/blob/main/mediapipe-0.8.1-cp38-cp38-linux_aarch64.whl.

My OS is window

**Comment by soumik2012** [comment]
still showing the error 
![image](https://user-images.githubusercontent.com/66599363/116691516-84255000-a9d8-11eb-8057-87e5c9baec7e.png)

I have already source still showing me the error 
![image](https://user-images.githubusercontent.com/66599363/116692316-c9964d00-a9d9-11eb-9d23-fd5a618146e2.png)

@sgowroji please help me

**Comment by jiuqiant** [comment]
Hi, "python38-32" probably means that you use the 32-bit version of Python3.8. MediaPipe Python currently doesn't provide support for 32-bit version of Python. Please install the 64-bit version of Python and try "python -m pip install mediapipe" instead.

**Comment by soumik2012** [comment]
@jiuqiant  is python 3.8 .8 is suitable or not

**Comment by jiuqiant** [comment]
Any 64-bit Python3.7+ should be fine.

**Comment by soumik2012** [comment]
It worked thank you so much @jiuqiant @sgowroji helping me 👍🏻 😄 🎊

**Comment by sgowroji** [comment]
Glad your issue resolved. We are closing this ticket now. Thanks!
