### ISSUE TITLE
MediaPipe use NNAPI

### ISSUE THREAD

**Issue by lilinxiong** [google/mediapipe#1962]
I saw in Tags that support for NNAPI has been added in ver0.6.6.
In the [#issue1425](https://github.com/google/mediapipe/issues/1425#issuecomment-782355649), I saw the changes to be made to support NNAPI.
My question now is:
 * Whether only ``TfLiteInferenceCalculator`` can set NNAPI ``delegate``, ``InferenceCalculator`` cannot be set ``NNAPI delegate``.
 * If ``InferenceCalculator`` cannot be set ``NNAPI delegate``, I can convert ``InferenceCalculator`` to ``TfLiteInferenceCalculator`` ？
 * What is the difference between ``InferenceCalculator`` and ``TfLiteInferenceCalculator``.

if ``InferenceCalculator`` can set ``NNAPI delegate``, you can ignore the second question.

I want to use NNAPI in [FaceMesh](https://github.com/google/mediapipe/blob/0.8.3.2/mediapipe/graphs/face_mesh/face_mesh_mobile.pbtxt).

Thanks.

**Comment by mcclanahoochie** [comment]
The `InferenceCalculator` is a newer and re-designed `TfLiteInferenceCalculator`, and will eventually replace it. 

Another difference is the tensor typed changed to `mediapipe::Tensor`, which you can get via the [ImageToTensorCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tensor/image_to_tensor_calculator.cc).
Just be sure to send in CPU images to the ImageToTensorCalculator to get CPU tensors that nnapi can use. 

The nnapi support is in both calculators, and should be triggered with the same delegate option as before.

**Comment by lilinxiong** [comment]
@mcclanahoochie Thank you for replying to me during the holiday season. Thanks again.
My other question is, if I use ``NNAPI delegate``, but the device does not support NNAPI, will it be automatically transferred to the CPU? Such as low-end Qualcomm CPUs and all Kirin CPUs. 
Today I will try to use NNAPI delegate on Qualcomm 865.
Happy Labor Day~~~

**Comment by mcclanahoochie** [comment]
I believe the NNAPI will fallback to CPU automatically if needed in most cases ([see this](https://developer.android.com/ndk/guides/neuralnetworks#cpu-fallback)).

**Comment by lilinxiong** [comment]
Ok,Thanks for your reply, I will verify it right away, thanks again.

**Comment by lilinxiong** [comment]
Hi @mcclanahoochie 
When I am making changes to **IrisLandmark**, because I don't know the parameters in  **ImageToTensorCalculator** ``options``, I refer to [IrisLandmarkCpu](https://github.com/google/mediapipe/blob/0.8.3.2/mediapipe/modules/iris_landmark/iris_landmark_cpu.pbtxt). But found **TfLiteInferenceCalculator** input is [TfLiteConverterCalculatort](https://github.com/google/mediapipe/blob/0.8.3.2/mediapipe/modules/iris_landmark/iris_landmark_cpu.pbtxt#L64-L73) output, Similarly, the **options** required by ``ImageToTensorCalculator`` are not found in ``IrisLandmarkGpu``.
Can I understand that ``TfLiteConverterCalculator`` implements the same function as ``ImageToTensorCalculator`` ?
Then send the output of ``TfLiteConverterCalculator`` to ``TfLiteInferenceCalculator`` and implement nnapi delegate...
And I did not find the corresponding implementation of TfLiteConverterCalculator.

**Comment by lilinxiong** [comment]
Today I did a test on Qualcomm 865 and Kirin 9000E.
Android OS: 11 and 10
Respectively for GPU mode, xnnpack and nnapi delegate to do tests.
But the result is not as expected.
* on OS 11 and Qualcomm Snapdragon 865
  NNAPI is the worst, xnnpack and GPU are on the same level.
  NNAPI FPS is less than 10, xnnpack and GPU FPS can be 25+, but xnnpack is not stable, but the lowest can also be 20.
* on OS 10 and Kirin 9000E
   NNAPI is not working, xnnpack FPS maintained at 10-15, GPU FPS is less than 10.

We expect the best is NNAPI, but this is not the case.
I found through consulting the information that Qualcomm 865 supports NNAPI, and the system also support it, but why does it run on the CPU? Is there a mechanism in mediapipe, if it runs on the CPU, then xnnpack delegation is used by default ?
```
Another difference is the tensor typed changed to mediapipe::Tensor, which you can get via the ImageToTensorCalculator.
Just be sure to send in CPU images to the ImageToTensorCalculator to get CPU tensors that nnapi can use.
```
Apart from this precaution, is there anything else?

**Comment by lilinxiong** [comment]
Hi @mcclanahoochie Let me add some more:
* The models I used are: ``face_detection_front.tflite`` ``face_landmark.tflite`` ``iris_landmark.tflite``.
* in [#229](https://github.com/google/mediapipe/pull/229#issue-338553204) I saw that ``NNAPI device(s) could run facedectioncpu and objectdectioncpu accelerated.`` But it is a long time ago.
* With the idea of giving it a try, I changed the delegate in **FaceDetection** to nnapi, and the others kept(FaceLandmark, irisLandmark) xnnpack unchanged.I got the following log:
![image](https://user-images.githubusercontent.com/24367027/117393794-7b2c0580-af27-11eb-93d8-58d7ff759eaa.png)
 as expected ``face_detection_front.tflite`` successfully used NNAPI, ``face_landmark.tflite`` used XNNPACK, ``iris_landmark.tflite`` there is no log output, so I don’t know if XNNPACK is used.
* When I changed the delegates of ``face_landmark.tflite`` and ``iris_landmark.tflite`` to NNAPI, unfortunately, there is no Log output of ``Created TensorFlow Lite delegate for NNAPI.`` The log is as follows:
![image](https://user-images.githubusercontent.com/24367027/117394575-f7731880-af28-11eb-835b-2a69f11ea3d4.png)

So now only **facedection** and **objectdection** support NNAPI ?

**Comment by lilinxiong** [comment]
emmmm, another point, when I tested on kirin9000E CPU, the following log was output(``ERROR STATUS: ANEURALNETWORKS_OP_FAILED``):
![image](https://user-images.githubusercontent.com/24367027/117395743-22f70280-af2b-11eb-8fb3-777a9a985f00.png)
By consulting the documentation, I see the following([this](https://developer.android.google.cn/ndk/guides/neuralnetworks#memory-domains)):

![image](https://user-images.githubusercontent.com/24367027/117396127-e8419a00-af2b-11eb-81c7-be6f031eb69f.png)

How should I achieve this ?

Sorry, I said too much, I hope you don’t mind, thank you again~

**Comment by mcclanahoochie** [comment]
The ANEURALNETWORKS_OP_FAILED is new to me. This must be an internal error from TfLite, and there may actually be[ many reasons](https://android.googlesource.com/platform/frameworks/ml/+/android-p-preview-4/nn/runtime/ExecutionPlan.cpp) why this error is returned.

The 2 detection networks are more simple than the landmark/tracking models, so it is possible that one of the OPs in the graph is [not supported](https://github.com/pytorch/pytorch/blob/master/caffe2/mobile/contrib/nnapi/nnapi.cc#L23), rather than memory.

It is also possible that on the other devices, NNAPI doesn't support the same OP, but instead of failing, it silently runs on CPU, which would hurt performance. For GPU delegate, there is a log warning about ops falling back to cpu, but i'm not certain about NNAPI (it should but I don't know). 

Yes,  `ImageToTensorCalculator` can replace both `ImageTransformation` and `TfLiteConverterCalculator` (it can do resize and transform in one).

You can place logs [here](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tensor/inference_calculator_cpu.cc#L176)
 to see if NNAPI is being used.

**Comment by lilinxiong** [comment]
Ok, thanks for your reply, but now I don't pay much attention to this matter anymore, what I am concerned about now is:The shared library compiled by MediaPipe is very large(>10MB). This is the biggest problem we currently encounter. And trying to solve it, but I still appreciate your reply. Thank you~

**Comment by mcclanahoochie** [comment]
you can try these Compiler flags to reduce size
        "--compilation_mode=opt",
        "--copt=-ffast-math",
        "--copt=-fvisibility=hidden",
        "--linkopt=-Wl,--exclude-libs,ALL",
        "--linkopt=-s",
        "--copt=-DABSL_MIN_LOG_LEVEL=3",

closing this issue for now

**Comment by fchen09** [comment]
> Today I did a test on Qualcomm 865 and Kirin 9000E. Android OS: 11 and 10 Respectively for GPU mode, xnnpack and nnapi delegate to do tests. But the result is not as expected.
> 
> * on OS 11 and Qualcomm Snapdragon 865
>   NNAPI is the worst, xnnpack and GPU are on the same level.
>   NNAPI FPS is less than 10, xnnpack and GPU FPS can be 25+, but xnnpack is not stable, but the lowest can also be 20.
> * on OS 10 and Kirin 9000E
>   NNAPI is not working, xnnpack FPS maintained at 10-15, GPU FPS is less than 10.
> 
> We expect the best is NNAPI, but this is not the case. I found through consulting the information that Qualcomm 865 supports NNAPI, and the system also support it, but why does it run on the CPU? Is there a mechanism in mediapipe, if it runs on the CPU, then xnnpack delegation is used by default ?
> 
> ```
> Another difference is the tensor typed changed to mediapipe::Tensor, which you can get via the ImageToTensorCalculator.
> Just be sure to send in CPU images to the ImageToTensorCalculator to get CPU tensors that nnapi can use.
> ```
> 
> Apart from this precaution, is there anything else?

@lilinxiong 
Hi, sir. when I run the sample code of pose tracking on Snapdragon855, it shows only 15 fps, and it is on GPU. Could you suggest me some ideas on how to improve the FPS?

**Comment by ralarcong** [comment]
Hello,

What do I need to do to enable the use of NPU inference through the Python API?

Thank you in advance.
