### ISSUE TITLE
How can I access to a calculator's output from javascript 

### ISSUE THREAD

**Issue by Sun1718** [google/mediapipe#1963]
How can I access to a output-stream of a node in javascript?
for example in this node:

Concatenate iris landmarks from both eyes.
node {
  calculator: "ConcatenateNormalizedLandmarkListCalculator"
  input_stream: "left_iris_landmarks"
  input_stream: "right_iris_landmarks"
  output_stream: "iris_landmarks"
}

the output-stream is iris_landmarks. How can I access it?

Any response will be highly appreciated.

**Comment by tyrmullen** [comment]
In general, that's not a feature we support-- only some calculators can have their outputs accessed directly from JavaScript/TypeScript.  But we are actively working on making the JS Solutions APIs more customizable and flexible, which should hopefully alleviate the need for this.

**Comment by Sun1718** [comment]
Sooooo many thanks for your response. I just want access to landmark points from javascript in iris tracking project (https://viz.mediapipe.dev/demo/iris_tracking)

Is there any way to access them? 

So thanks for your kindly help

**Comment by tyrmullen** [comment]
No; in that demo, the landmark computation as well as the rendering are both done inside the C++ MediaPipe graph, so nothing is ever brought back into JavaScript except the final image.  Our answer to this problem would be the MediaPipe JS Solutions APIs (e.g. [here](https://mediapipe.dev/demo/hands)), which open up our web demos for anyone to use the data directly, with JS and TypeScript entrypoints.  However, we don't yet have an iris-tracking API, although this is something we'd like to have fairly soon.  You can see [this chart](https://google.github.io/mediapipe/solutions/solutions) for tracking which solutions are available on which platforms so far.
