### ISSUE TITLE
Website wrong

### ISSUE THREAD

**Issue by Lr-2002** [google/mediapipe#1968]
Hi ,when viewing "https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows"
I found a problem 
the Visual Studio Website is 
``` ttps://visualstudio.microsoft.com/visual-cpp-build-tools/  ```
rather than 
``` https://visualstudio.microsoft.com/visual-cpp-build-tools/   ```

**Comment by sgowroji** [comment]
Fixed in the latest release. Please check
