### ISSUE TITLE
YouTube-8M feature extraction graph extract the features Error

### ISSUE THREAD

**Issue by Harryjun** [google/mediapipe#197]
I run this 
`./bazel-bin/mediapipe/examples/desktop/youtube8m/extract_yt8m_features \
  --calculator_graph_config_file=mediapipe/graphs/youtube8m/feature_extraction.pbtxt \
  --input_side_packets=input_sequence_example=/tmp/mediapipe/metadata.tfrecord  \
  --output_side_packets=output_sequence_example=/tmp/mediapipe/output.tfrecord`
get this problem
`2019-10-24 14:27:35.478046: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
E1024 14:27:39.661725  5320 extract_yt8m_features.cc:130] Failed to run the graph: CalculatorGraph::Run() failed in Run:
Calculator::Open() for node "[AudioDecoderCalculator, AudioDecoderCalculator with output stream: audio]" failed: Could not open file: ~/menglingjun/DSNNet/others/pytorch-vsumm-reinforce/utils/train.mp4
Calculator::Open() for node "[OpenCvVideoDecoderCalculator, OpenCvVideoDecoderCalculator with output stream: decoded_frames]" failed: ; Fail to open video file at ~/menglingjun/DSNNet/others/pytorch-vsumm-reinforce/utils/train.mp4`
can anyone help me?

**Comment by divyag9** [comment]
May be it's a permission issue. Can you try changing the file permission. 
chmod 700 <mp4 file>

**Comment by jiuqiant** [comment]
Seems like cv::VideoCapture doesn't understand tilde. You need to specify the full path to your video instead of using tilde in the path. For example, you need to run something like:

```
python -m mediapipe.examples.desktop.youtube8m.generate_input_sequence_example  \
  --path_to_input_video=/home/<youre_username>/menglingjun/DSNNet/others/pytorch-vsumm-reinforce/utils/train.mp4 \
  --clip_end_time_sec=120
```

**Comment by Harryjun** [comment]
> Seems like cv::VideoCapture doesn't understand tilde. You need to specify the full path to your video instead of using tilde in the path. For example, you need to run something like:
> 
> ```
> python -m mediapipe.examples.desktop.youtube8m.generate_input_sequence_example  \
>   --path_to_input_video=/home/<youre_username>/menglingjun/DSNNet/others/pytorch-vsumm-reinforce/utils/train.mp4 \
>   --clip_end_time_sec=120
> ```

Hi,I try this,but it has no effect.

**Comment by Harryjun** [comment]
> May be it's a permission issue. Can you try changing the file permission.
> chmod 700

This is my own file,I have the permission

**Comment by jiuqiant** [comment]
> > Seems like cv::VideoCapture doesn't understand tilde. You need to specify the full path to your video instead of using tilde in the path. For example, you need to run something like:
> > ```
> > python -m mediapipe.examples.desktop.youtube8m.generate_input_sequence_example  \
> >   --path_to_input_video=/home/<youre_username>/menglingjun/DSNNet/others/pytorch-vsumm-reinforce/utils/train.mp4 \
> >   --clip_end_time_sec=120
> > ```
> 
> Hi,I try this,but it has no effect.

Can you open your file with OpenCV3 directly? You can do something like the following in Python:
```
import cv2
cap = cv2.VideoCapture('<path_to_input_video>')
print(cap.isOpened())
```

As you already know, MediaPipe uses cv::VideoCapture to do video decoding. If you can do this with OpenCV3, it should work with MediaPipe as well.
