### ISSUE TITLE
Combining mediapipe holistic with iris

### ISSUE THREAD

**Issue by ivanmang** [google/mediapipe#1970]
I am trying to combine the mediapipe holistic with the iris.
I followed and implemented the calculators to detect iris landmarks from face landmarks #1559 
And added a node after the face prediction in holistic. The graph holistic_landmark_gpu.pbtxt looks like this now.
![Screenshot from 2021-05-03 11-14-22](https://user-images.githubusercontent.com/35868876/116838378-bb764580-ac00-11eb-8f68-94f93aee0db4.png)

However, when I try running the holistic again, it crashes after a few second on my Samsung S21 phone. I am not sure whats the problem here. Could anyone please help me with that?

Here is my code: 
https://github.com/ivanmang/-mediapipe

**Comment by sgowroji** [comment]
Hi @ivanmang, Could you please share the crash logs. Thanks!

**Comment by ivanmang** [comment]
@sgowroji 
Here you go, thanks so much!
`05-03 13:36:57.907  6467 11691 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 11691 (mediapipe_gl_ru), pid 6467 (stictrackinggpu)
05-03 13:36:58.016 12160 12160 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-03 13:36:58.017 12160 12160 F DEBUG   : Build fingerprint: 'samsung/o1qzhx/o1q:11/RP1A.200720.012/G9910ZHU2AUC9:user/release-keys'
05-03 13:36:58.017 12160 12160 F DEBUG   : Revision: '14'
05-03 13:36:58.017 12160 12160 F DEBUG   : ABI: 'arm64'
05-03 13:36:58.017 12160 12160 F DEBUG   : Timestamp: 2021-05-03 13:36:58+0800
05-03 13:36:58.017 12160 12160 F DEBUG   : pid: 6467, tid: 11691, name: mediapipe_gl_ru  >>> com.google.mediapipe.apps.holistictrackinggpu <<<
05-03 13:36:58.017 12160 12160 F DEBUG   : uid: 10424
05-03 13:36:58.017 12160 12160 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
05-03 13:36:58.017 12160 12160 F DEBUG   : Cause: null pointer dereference
05-03 13:36:58.017 12160 12160 F DEBUG   :     x0  0000000000000000  x1  00000076998adddc  x2  0000007339259448  x3  0000000000000028
05-03 13:36:58.017 12160 12160 F DEBUG   :     x4  0000000000000000  x5  00000073f7976517  x6  20646c756f63203b  x7  6461657220746f6e
05-03 13:36:58.017 12160 12160 F DEBUG   :     x8  0101010101010101  x9  0000007ff1830738  x10 000000000000000b  x11 000000000000000b
05-03 13:36:58.017 12160 12160 F DEBUG   :     x12 0000007ff1831fbb  x13 000000733c32280f  x14 000000000000000b  x15 0000000000000041
05-03 13:36:58.017 12160 12160 F DEBUG   :     x16 000000733c58fc58  x17 00000076998184f0  x18 0000000000000000  x19 0000007339259550
05-03 13:36:58.017 12160 12160 F DEBUG   :     x20 0000007339259570  x21 0000000000000000  x22 00000073392594a9  x23 ffffffffffffffff
05-03 13:36:58.017 12160 12160 F DEBUG   :     x24 000000733925a000  x25 0000007339259571  x26 0000000000000020  x27 00000073e79540e0
05-03 13:36:58.017 12160 12160 F DEBUG   :     x28 0000007339161000  x29 0000007339259530
05-03 13:36:58.017 12160 12160 F DEBUG   :     lr  000000733bbfa9d8  sp  0000007339259480  pc  0000007699818500  pst 0000000080001000
05-03 13:36:58.022 12160 12160 F DEBUG   : backtrace:
05-03 13:36:58.022 12160 12160 F DEBUG   :     NOTE: Function names and BuildId information is missing for some frames due
05-03 13:36:58.022 12160 12160 F DEBUG   :     NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
05-03 13:36:58.022 12160 12160 F DEBUG   :     NOTE: found under the lib/ directory are readable.
05-03 13:36:58.022 12160 12160 F DEBUG   :       #00 pc 000000000004b500  /apex/com.android.runtime/lib64/bionic/libc.so (strlen_default+16) (BuildId: 8a370288b0cee63bab5e0621406f623f)
05-03 13:36:58.022 12160 12160 F DEBUG   :       #01 pc 00000000006359d4  /data/user/0/com.google.mediapipe.apps.holistictrackinggpu/incrementallib/libmediapipe_jni.so
05-03 13:36:58.022 12160 12160 F DEBUG   :       #02 pc 0000000000634af8  /data/user/0/com.google.mediapipe.apps.holistictrackinggpu/incrementallib/libmediapipe_jni.so
05-03 13:36:58.022 12160 12160 F DEBUG   :       #03 pc 00000000005372a4  /data/user/0/com.google.mediapipe.apps.holistictrackinggpu/incrementallib/libmediapipe_jni.so
05-03 13:36:58.022 12160 12160 F DEBUG   :       #04 pc 0000000000532b9c  /data/user/0/com.google.mediapipe.apps.holistictrackinggpu/incrementallib/libmediapipe_jni.so
05-03 13:36:58.022 12160 12160 F DEBUG   :       #05 pc 0000000000532628  /data/user/0/com.google.mediapipe.apps.holistictrackinggpu/incrementallib/libmediapipe_jni.so
05-03 13:36:58.022 12160 12160 F DEBUG   :       #06 pc 0000000000a8d7fc  /data/user/0/com.google.mediapipe.apps.holistictrackinggpu/incrementallib/libmediapipe_jni.so
05-03 13:36:58.022 12160 12160 F DEBUG   :       #07 pc 0000000000a78c44  /data/user/0/com.google.mediapipe.apps.holistictrackinggpu/incrementallib/libmediapipe_jni.so
05-03 13:36:58.022 12160 12160 F DEBUG   :       #08 pc 0000000000a789d8  /data/user/0/com.google.mediapipe.apps.holistictrackinggpu/incrementallib/libmediapipe_jni.so
05-03 13:36:58.022 12160 12160 F DEBUG   :       #09 pc 0000000000aaaf70  /data/user/0/com.google.mediapipe.apps.holistictrackinggpu/incrementallib/libmediapipe_jni.so
05-03 13:36:58.022 12160 12160 F DEBUG   :       #10 pc 0000000000aa4e9c  /data/user/0/com.google.mediapipe.apps.holistictrackinggpu/incrementallib/libmediapipe_jni.so
05-03 13:36:58.022 12160 12160 F DEBUG   :       #11 pc 0000000000aa4818  /data/user/0/com.google.mediapipe.apps.holistictrackinggpu/incrementallib/libmediapipe_jni.so
05-03 13:36:58.022 12160 12160 F DEBUG   :       #12 pc 00000000000b6234  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 8a370288b0cee63bab5e0621406f623f)
05-03 13:36:58.022 12160 12160 F DEBUG   :       #13 pc 0000000000050e64  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 8a370288b0cee63bab5e0621406f623f)
`

**Comment by hadon** [comment]
Thanks Ivan for reporting the issue and including the crash logs.   I can't discern much from the crash log because it seems to lack the function names from the MediaPipe jni library

I imagine that the IrisLandmarkLeftAndRightCpu subgraph is probably receiving some IMAGE inputs without the corresponding FACE_LANDMARKS input.  It may be that this subgraph expects FACE_LANDMARKS for every frame.  If this is the problem, it may be possible to limit the IMAGE input stream to only the frames with FACE_LANDMARKS, or it may be possible to make IrisLandmarkLeftAndRightCpu more resilient to missing data.  

I will assign this issue also to Fan fanzhanggoogle@ in case he can provide any insight about limitations of "IrisLandmarkLeftAndRightCpu".

**Comment by sgowroji** [comment]
Hi @ivanmang, Could you respond if you are still looking update for the above query. Thanks!
