### ISSUE TITLE
Error importing mediaipipe on android studio

### ISSUE THREAD

**Issue by RubabTariq-dot** [google/mediapipe#1974]
I followed all the steps mentioned at https://github.com/google/mediapipe/blob/master/docs/getting_started/android_archive_library.md. I am doing this on Linux and i cannot seem to find the issue
![Capture](https://user-images.githubusercontent.com/54850445/116902604-c5299880-ac54-11eb-9caf-5a5ddd716419.PNG)

**Comment by sgowroji** [comment]
Hi @RubabTariq-dot, Could you please share the complete error logs. And at which step you encountered the error.  Are you able to build the AAR successfully? Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.
