### ISSUE TITLE
region_flow_computation is hardcoded to use opencv3 (4 doesn't work)

### ISSUE THREAD

**Issue by samlaf** [google/mediapipe#1975]
Hi,
`region_flow_computation.cc` is filled with `#if CV_MAJOR_VERSION == 3` sections.
When I run [object_tracking](https://google.github.io/mediapipe/solutions/box_tracking.html) on my desktop with opencv version 4, I get these warnings
![image](https://user-images.githubusercontent.com/9342524/116921881-9b577e00-ac22-11eb-86eb-fdcda42c8974.png)

I changed all of the `#if CV_MAJOR_VERSION == 3` to `#if CV_MAJOR_VERSION >= 3` and everything seems to work.
Is the dependency on version 3 really necessary?
If so, perhaps this should be mentioned in the [installation instructions](https://google.github.io/mediapipe/getting_started/install.html)?

**Comment by yegenzhi** [comment]
Thanks samlaf for mentioning this. You will see the changes in the next release.

**Comment by sgowroji** [comment]
We are closing this issue now. Please verify this in our next releases.
