### ISSUE TITLE
change input_side_packet at runtime

### ISSUE THREAD

**Issue by jiqimaogou** [google/mediapipe#198]
I create a node like：

```
node: {
  calculator: "PlusCalculator"
  input_side_packet: "A"
  input_stream: "X"
  output_stream: "Y"
}

```
which equals `Y = X + A`。

at sometimes I want to modify A values, How can I do this?

**Comment by jiqimaogou** [comment]
for examples, I create a node to render my hair with difference color, I want to change color at certain time, How can I do this. can you provide an more interactive example?

**Comment by fenollp** [comment]
You can create and add packets to an input stream with this call: https://github.com/google/mediapipe/blob/a2a63e387680c090f76072864a107647e874d390/mediapipe/examples/desktop/demo_run_graph_main.cc#L108

**Comment by jiqimaogou** [comment]
> You can create and add packets to an input stream with this call:
> 
> https://github.com/google/mediapipe/blob/a2a63e387680c090f76072864a107647e874d390/mediapipe/examples/desktop/demo_run_graph_main.cc#L108

But InputStream recepts series data, color is not series data, it just an attribute which can be changed in certain time.

**Comment by jiuqiant** [comment]
Hi, you can make a packet of a unique_ptr of the color object by using [AdoptAsUniquePtr()](https://github.com/google/mediapipe/blob/c6fea4c9d9f3bdf081c10387d2b42ed854199d06/mediapipe/framework/packet.h#L228). Then, you can modify the color object outside of the graph during runtime. Hope this helps.

**Comment by jiqimaogou** [comment]
> Hi, you can make a packet of a unique_ptr of the color object by using [AdoptAsUniquePtr()](https://github.com/google/mediapipe/blob/c6fea4c9d9f3bdf081c10387d2b42ed854199d06/mediapipe/framework/packet.h#L228). Then, you can modify the color object outside of the graph during runtime. Hope this helps.

Is this the best practice? What is the official practice?

**Comment by jiuqiant** [comment]
> > Hi, you can make a packet of a unique_ptr of the color object by using [AdoptAsUniquePtr()](https://github.com/google/mediapipe/blob/c6fea4c9d9f3bdf081c10387d2b42ed854199d06/mediapipe/framework/packet.h#L228). Then, you can modify the color object outside of the graph during runtime. Hope this helps.
> 
> Is this the best practice? What is the official practice?

If you want to change the content of an input side packet at runtime, making a packet of a pointer or a unique pointer is the the only solution. A packet of a pointer to an object is the best choice if you need to own that object. A packet of a unique pointer is suitable if you want MediaPipe to do the memory management for you. But, the object will be destroyed if the packet object goes out of scope. 

For your question, the best practice is to do the control via an input stream rather than an input side packet. First, a side packet doesn't have its timestamp and it's hard to make a setting change at a particular timestamp via an input side packet. Secondly, MediaPipe has input stream handlers that can help you apply different stream alignment strategy. Using control stream with different input stream handler can give you more freedom on how the settings affect different streams.

**Comment by hadon** [comment]
> > Hi, you can make a packet of a unique_ptr of the color object by using [AdoptAsUniquePtr()](https://github.com/google/mediapipe/blob/c6fea4c9d9f3bdf081c10387d2b42ed854199d06/mediapipe/framework/packet.h#L228). Then, you can modify the color object outside of the graph during runtime. Hope this helps.
> 
> Is this the best practice? What is the official practice?

Either a mutable side packet or an input stream would work for your use case.  For mutable options, we generally recommend input streams because MediaPipe normally represents changes over time as time-series data in packet streams.  Also, MediaPipe distinguishes between "presentation time" represented as mediapipe::Timestamp, and "processing time" represented by absl::Time from mediapipe::Clock.  Packet streams normally represent "presentation times", while side packets normally indicate "processing times".

**Comment by jiqimaogou** [comment]
> > > Hi, you can make a packet of a unique_ptr of the color object by using [AdoptAsUniquePtr()](https://github.com/google/mediapipe/blob/c6fea4c9d9f3bdf081c10387d2b42ed854199d06/mediapipe/framework/packet.h#L228). Then, you can modify the color object outside of the graph during runtime. Hope this helps.
> > 
> > 
> > Is this the best practice? What is the official practice?
> 
> Either a mutable side packet or an input stream would work for your use case. For mutable options, we generally recommend input streams because MediaPipe normally represents changes over time as time-series data in packet streams. Also, MediaPipe distinguishes between "presentation time" represented as mediapipe::Timestamp, and "processing time" represented by absl::Time from mediapipe::Clock. Packet streams normally represent "presentation times", while side packets normally indicate "processing times".

thank you, can you provide an example like this? input stream is the best choice, in this situation, option input stream is less frequent than  video input stream, how do I control this?

**Comment by hadon** [comment]
There are some special settings that are helpful for "options" input packets.  You can specify "SyncSetInputStreamHandler" to process packets that arrive at different frequencies or with different time bases.  In the options for "SyncSetInputStreamHandler", you can specify each "options" input stream as a separate "sync-set".  Then your calculator will receive each "options" input packet as soon as it arrives, independent of packets in other "sync-sets".  

It looks like "SyncSetInputStreamHandler" is not used in any of the published examples at the moment.  Below is a MediaPipe graph fragment showing how an "options" input packet named "RESTART_POS" can be accepted by a calculator.  

node: {
  calculator: "PigeonTrackerCalculator"

  input_side_packet: "OPTIONS:calculator_options"
  input_stream: "TRACKING:tracking_data"
  input_stream: "TRACK_TIME:track_time"
  input_stream: "RESTART_POS:restart_pos"
  output_stream: "BOXES:boxes"

  input_stream_handler {
    input_stream_handler: "SyncSetInputStreamHandler"
    options {
      [drishti.SyncSetInputStreamHandlerOptions.ext] {
        sync_set {
          tag_index: "TRACKING"
          tag_index: "TRACK_TIME"
        }
       sync_set {
          tag_index: "RESTART_POS"
        }
      }
    }
  }

**Comment by jiqimaogou** [comment]
if I have a calculator to render different image:
```
node: {
  calculator: "ImageRenderCalculator"
  input_stream: "image_path"
```

I want to change the image_path at runtime, but image_path just open once, how do I do this?

**Comment by jiqimaogou** [comment]
> There are some special settings that are helpful for "options" input packets. You can specify "SyncSetInputStreamHandler" to process packets that arrive at different frequencies or with different time bases. In the options for "SyncSetInputStreamHandler", you can specify each "options" input stream as a separate "sync-set". Then your calculator will receive each "options" input packet as soon as it arrives, independent of packets in other "sync-sets".
> 
> It looks like "SyncSetInputStreamHandler" is not used in any of the published examples at the moment. Below is a MediaPipe graph fragment showing how an "options" input packet named "RESTART_POS" can be accepted by a calculator.
> 
> ```
> node: {
>   calculator: "PigeonTrackerCalculator"
> 
>   input_side_packet: "OPTIONS:calculator_options"
>   input_stream: "TRACKING:tracking_data"
>   input_stream: "TRACK_TIME:track_time"
>   input_stream: "RESTART_POS:restart_pos"
>   output_stream: "BOXES:boxes"
> 
>   input_stream_handler {
>     input_stream_handler: "SyncSetInputStreamHandler"
>     options {
>       [drishti.SyncSetInputStreamHandlerOptions.ext] {
>         sync_set {
>           tag_index: "TRACKING"
>           tag_index: "TRACK_TIME"
>         }
>         sync_set {
>           tag_index: "RESTART_POS"
>         }
>       }
>     }
>   }
> ```

how about the chaning resources? like image, we should open the resources and close the resources if input stream is changed.

**Comment by eknight7** [comment]
@jiqimaogou Has this issue been resolved? Do you have any followup questions?
