### ISSUE TITLE
demo_run_graph_main_gpu: eglDestroyContext() returned error 0x3008

### ISSUE THREAD

**Issue by plafer** [google/mediapipe#1980]
Running the following command: `GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_detection/face_detection_gpu --calculator_graph_config_file=mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt --input_video_path=somevid.h264` gets the following output:

> ...
I20210504 16:06:37.680992 27513 demo_run_graph_main_gpu.cc:171] Prepare video writer.
I20210504 16:07:07.148627 27513 demo_run_graph_main_gpu.cc:105] Empty frame, end of video reached.
I20210504 16:07:07.148684 27513 demo_run_graph_main_gpu.cc:186] Shutting down.
I20210504 16:07:07.902504 27513 demo_run_graph_main_gpu.cc:200] Success!
E20210504 16:07:07.905253 27519 gl_context_egl.cc:230] eglDestroySurface() returned error 0x3000
E20210504 16:07:07.905655 27519 gl_context_egl.cc:237] eglDestroyContext() returned error 0x3008

Tested on ubuntu 20.04 x86_64, as well as on a Jetson Nano running their ubuntu 18.04. 

Additionally, on the Jetson Nano, the program hangs at the end after having created the output video *when no monitor is connected to it*.

**Comment by sgowroji** [comment]
Hi @plafer, Could you please share the steps to reproduce the above issue. Thanks!

**Comment by plafer** [comment]
On Ubuntu 20.04, build `face_detection_gpu` using `bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11   mediapipe/examples/desktop/face_detection:face_detection_gpu`. Then run

`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_detection/face_detection_gpu --calculator_graph_config_file=mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt --input_video_path=somevid.h264`

where `somevid.h264` is some video on your machine in h264 format (potentially wrapped in mp4).

**Comment by sgowroji** [comment]
Hi @plafer, Can you share the complete logs if you still see the above error. thanks!

**Comment by plafer** [comment]
Sorry I don't have them anymore

**Comment by sgowroji** [comment]
Thank you for the update. We are closing this issue now.
