### ISSUE TITLE
Question regarding legacy API

### ISSUE THREAD

**Issue by samlaf** [google/mediapipe#1981]
From my understanding reading the code, it seems that face_detection/tracking use the "modern" MediaPipe image datatypes whereas object_detection/tracking use the "legacy" MediaPipe image datatypes.

![image](https://user-images.githubusercontent.com/9342524/117092169-7c90de80-ad2b-11eb-97c7-d09bf0ffa2e1.png)

For example, `to_image_calculator.cc` reads:
```
// A calculator for converting from legacy MediaPipe datatypes into a
// unified image container.
//
// Inputs:
//   One of the following two tags:
//   IMAGE_CPU:  An ImageFrame containing input image.
//   IMAGE_GPU:  A GpuBuffer containing input image.
//
// Output:
//   IMAGE:  An Image containing output image.
```

My questions are: 
- should I assume that legacy mediapipe is going to eventually be dropped and replaced by the single unified image container datatype?
- is there a timeline for updating object_detection/tracking?
- Are there performance differences between these two versions?
- I need to use the [face_detection_back](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/face_detection_back_mobile_gpu.pbtxt) models in my project, but I noticed that these aren't built anywhere in bazel files, and they use the legacy version of MediaPipe. Can I just swap out the tflite_back model in the modern graph for front images?

Many thanks

**Comment by sureshdagooglecom** [comment]
Hi @samlaf ,
Are you still looking for the resolution on this issue.

**Comment by samlaf** [comment]
No, no longer working with mediapipe.

**Comment by sureshdagooglecom** [comment]
Hi @samlaf ,
Could you please close this issue.
