### ISSUE TITLE
Installing mediapipe w/ pip doesn't work on MacOS using python 3.7.9 (64-bit)

### ISSUE THREAD

**Issue by lyronctk** [google/mediapipe#1984]
**Overview**
Hello! Hope this reaches you well. Would love to start using mediapose with my work, but I'm having some trouble with my pip install. 

I'm running into the same `No matching distribution found` error as {[#1325](https://github.com/google/mediapipe/issues/1325), [#1466](https://github.com/google/mediapipe/issues/1466), [#1961](https://github.com/google/mediapipe/issues/1961)}. Their proposed solutions regarding python version and build unfortunately didn't work for me. 

**System Information**
  - python == 3.7.9 (64-bit)
  - pip == 21.0.1
  - OS: Mac 10.14.6 
 
**Screenshot**
![Screen Shot 2021-05-05 at 11 19 16 AM](https://user-images.githubusercontent.com/30359739/117190661-9286b980-ad94-11eb-92cc-266a8cef23ed.png)

**Comment by jiuqiant** [comment]
MediaPipe PyPI supports macOS 10.15 and above. See details at https://github.com/google/mediapipe/blob/master/docs/getting_started/troubleshooting.md#python-pip-install-failure

**Comment by lyronctk** [comment]
Updated to Big Sur and it worked. Many thanks!

**Comment by CZ0520** [comment]
I'm using macOS Monterey and I still have this error from terminal
<img width="570" alt="Screen Shot 2021-12-20 at 3 31 15 PM" src="https://user-images.githubusercontent.com/94819198/146729513-021ead01-9b8d-4a18-af58-28a54373fd7e.png">
:

**Comment by jiuqiant** [comment]
> I'm using macOS Monterey and I still have this error from terminal:
> 
> <img width="570" alt="Screen Shot 2021-12-20 at 3 31 15 PM" src="https://user-images.githubusercontent.com/94819198/146729513-021ead01-9b8d-4a18-af58-28a54373fd7e.png">

Please do verify that the python version is higher than 3.7 and run python3 -m pip install mediapipe.

**Comment by matanster** [comment]
Just wondering if anyone found a canonical way to handle or troubleshoot this, (installing on mac with pip), other than building from source .... We tried fiddling and upgrading versions like people have suggested on this thread, to no avail. 

We have some issues with M1 processor architecture on MacOS 11.2 where we can safely build from source, but we'd also like to have the ability to automatically fetch mediapipe in conda based installs which we have as part of our dev-ops routines.
