### ISSUE TITLE
Box Tracking

### ISSUE THREAD

**Issue by chrisError** [google/mediapipe#1985]
the docs state that Box Tracking can be used by Object Detection or defining an area. has anyone been able to track areas of the screen but not using Object Decection?

thanks

p.s. I am using Mediapipe inside Unity using https://github.com/homuler/MediaPipeUnityPlugin

**Comment by sgowroji** [comment]
Hi @chrisError, Could you please elaborate your use case with complete details  Thanks!

**Comment by RitvikMandyam** [comment]
Hi, I've been able to use the box tracking to track both face and person detections, you should be able to track pretty much anything. Fair warning though, if the object you're tracking takes up most of the image, the tracking tends to break down a little.

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.
