### ISSUE TITLE
Effect Renderer in python 

### ISSUE THREAD

**Issue by H4ckerman666** [google/mediapipe#1986]
hi, I wanted to implement this gif in python but I don't know where to start, I think they provide the obj of the 3d object in the documentation, do you know if someone has already done something like that?
https://google.github.io/mediapipe/images/face_geometry_renderer.gif

**Comment by sgowroji** [comment]
We unfortunately don't have examples to do this and do not have plans to provide it. You can check out the face effect renderer calculator See fig 4 on https://google.github.io/mediapipe/solutions/face_mesh.html

**Comment by TahaAnwar** [comment]
@sgowroji I also had the same issue, just to be clear, currently there is no support for overlaying 3d Objects or textures using the landmarks in python right?.

I tried to find an easy way to use the effect renderer in python to render 3d objects on faces but was unable to find any solution or docs. Can you confirm if this is not possible with python at the moment?

It's really unfortunate, I never see a good 3d AR effect render in python 🤔

**Comment by sgowroji** [comment]
Hi @TahaAnwar, From documentation [this](https://google.github.io/mediapipe/solutions/face_mesh.html#effect-renderer) is the latest.

**Comment by TahaAnwar** [comment]
> Hi @TahaAnwar, From documentation [this](https://google.github.io/mediapipe/solutions/face_mesh.html#effect-renderer) is the latest.

Yeah already gone over this. @sgowroji Can you tag an official mediapipe maintainer for some insight regarding this? Thanks.
