### ISSUE TITLE
Human pose detection and tracking (javascript) Error

### ISSUE THREAD

**Issue by AlexeiKaplenko** [google/mediapipe#1987]
Error after adding new functionality (models with complexity 0, 1, 2) to Human pose detection and tracking (javascript)
Full stack trace:
pose_solution_wasm_bin.js:9 Uncaught (in promise) RuntimeError: abort(No EM_ASM constant found at address 552800) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:64180)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:64432)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:37792)
    at _emscripten_asm_const_int (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:177754)
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6969]:0x36b934
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6968]:0x36b72e
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6967]:0x36b570
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6435]:0x33da38
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6183]:0x32e7ee
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6180]:0x32cf38
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:37823)
    at _emscripten_asm_const_int (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:177754)
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6969]:0x36b934
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6968]:0x36b72e
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6967]:0x36b570
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6435]:0x33da38
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6183]:0x32e7ee
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6180]:0x32cf38
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6178]:0x32cacb
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[254]:0xc847

**Comment by sgowroji** [comment]
Hi @AlexeiKaplenko, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by KristianDukov** [comment]
Hello, our app is experiencing exactly the same issue.
```No EM_ASM constant found at address 552800```
```
Uncaught (in promise) RuntimeError: abort(No EM_ASM constant found at address 552800) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:64180)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:64432)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:37792)
    at _emscripten_asm_const_int (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:177754)
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6969]:0x36b934
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6968]:0x36b72e
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6967]:0x36b570
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6435]:0x33da38
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6183]:0x32e7ee
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6180]:0x32cf38
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:37823)
    at _emscripten_asm_const_int (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:177754)
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6969]:0x36b934
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6968]:0x36b72e
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6967]:0x36b570
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6435]:0x33da38
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6183]:0x32e7ee
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6180]:0x32cf38
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6178]:0x32cacb
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[254]:0xc847

**Comment by AlexeiKaplenko** [comment]
I already figured out the solution. Correct version for cdn scripts should be specified
in .html
    <script
      src="https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils**@0.3**/camera_utils.js"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils**@0.3**/control_utils.js"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils**@0.3/**drawing_utils.js"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@mediapipe/pose**@0.3**/pose.js"
      crossorigin="anonymous"
    ></script>

and .js files
const pose = new Pose({
  locateFile: (file) => {
    return `https://cdn.jsdelivr.net/npm/@mediapipe/pose**@0.3**/${file}`;
  },

**Comment by sgowroji** [comment]
Glad to know your resolved. And also thanks for sharing your fix.

**Comment by KristianDukov** [comment]
Hello,
Does using an older version instead of the latest can be considered as a solution?

**Comment by vteodorescu** [comment]
@sgowroji @KristianDukov Hi, Sunil - we are experiencing the same problem and as Kristian said, the using of an older version as a solution is not really a solution. 

Is there a chance to re-open the issue and get a fix for it?

Many thanks

**Comment by vteodorescu** [comment]
We had a bug in a different part of our code, now it is all good and it is working for us.

**Comment by sgowroji** [comment]
Thank you for the update.
