### ISSUE TITLE
JS: Face detection stopped working after update

### ISSUE THREAD

**Issue by AdrianoW** [google/mediapipe#1989]
Hi team,

I have this project online (https://adrianow.github.io/very-kb/) that was working until these days and today I have detected that it stopped working. Looking at the developer console I am receiving the following error:
``` javascript
Uncaught (in promise) TypeError: Cannot read property 'get' of null
    at ka.h (face_detection.js:46)
    at T (face_detection.js:13)
    at ma.next (face_detection.js:14)
    at face_detection.js:23
    at new Promise (<anonymous>)
    at W (face_detection.js:23)
    at Object.onResults (face_detection.js:45)
    at methodCaller_void_$vector$ResultData$$ (eval at new_ (face_detection_solution_wasm_bin.js:9), <anonymous>:5:26)
    at __emval_call_void_method (face_detection_solution_wasm_bin.js:9)
    at cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.0/face_detection_solution_wasm_bin.wasm:wasm-function[516]:0x1b9f3
```

After some tests (and looking at the time of the last releases) I guess that we have a new version, that has broken the past code.  Using past versions, the problem is solved:
from  `https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.3/face_detection.js or https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/face_detection.js" ` to 

to  `https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.0/face_detection.js` solves the issue

**Comment by opsmith96** [comment]
I have a similar issue, different files 

pose_solution_packed_assets_loader.js
pose_solution_wasm_bin.js
pose_solution_packed_assets.data
pose_solution_wasm_bin.wasm
pose_web.binarypb

ended up with forcing version 0.2
`    const pose = new Pose({locateFile: (file) => {
      return `https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.2/${file}`;`

**Comment by sgowroji** [comment]
Hi @AdrianoW, Could you please test with the latest release and let us know if you still see the same error. Thanks!
