### ISSUE TITLE
It doesn't work after changing .tflite model

### ISSUE THREAD

**Issue by menghaocheng** [google/mediapipe#199]
Hi,
    I was trying to make my classification demo with MediaPipe but failed. My demo is copied from the object detections demo.  To debug it, I Deleted the detection part so that this demo can only preview the camera(the demo would make the inference with the .tflite model but ignores the result). now It works well. Then I change the .tflite model, anything goes wrong, It can't preview anymore. I simplified the graph as follow:
-----------------------------------------------------------------------------------------
The OK version:
`
input_stream: "input_video"
output_stream: "output_video"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for
# TfLiteTensorsToDetectionsCalculator downstream in the graph to finish
# generating the corresponding detections before it passes through another
# image. All images that come in while waiting are dropped, limiting the number
# of in-flight images between this calculator and
# TfLiteTensorsToDetectionsCalculator to 1. This prevents the nodes in between
# from queuing up incoming images and data excessively, which leads to increased
# latency and memory usage, unwanted in real-time mobile applications. It also
# eliminates unnecessarily computation, e.g., a transformed image produced by
# ImageTransformationCalculator may get dropped downstream if the subsequent
# TfLiteConverterCalculator or TfLiteInferenceCalculator is still busy
# processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:detection_tensors"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Transforms the input image on GPU to a 320x320 image. To scale the image, by
# default it uses the STRETCH scale mode that maps the entire input image to the
# entire transformed image. As a result, image aspect ratio may be changed and
# objects in the image may be deformed (stretched or squeezed), but the object
# detection model used in this graph is agnostic to that deformation.
node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "IMAGE_GPU:transformed_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 320
      output_height: 320
    }
  }
}

# Converts the transformed input image on GPU into an image tensor stored as a
# TfLiteTensor.
node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE_GPU:transformed_input_video"
  output_stream: "TENSORS_GPU:image_tensor"
}

# Runs a TensorFlow Lite model on GPU that takes an image tensor and outputs a
# vector of tensors representing, for instance, detection boxes/keypoints and
# scores.
node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS_GPU:image_tensor"
  output_stream: "TENSORS:detection_tensors"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
      model_path: "ssdlite_object_detection.tflite"
    }
  }
}

# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "INPUT_FRAME_GPU:throttled_input_video"
  #input_stream: "render_data"
  output_stream: "OUTPUT_FRAME_GPU:output_video"
}
`
-------------------------------------------------------------------------------------------
The failed version:
`
input_stream: "input_video"
output_stream: "output_video"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for
# TfLiteTensorsToDetectionsCalculator downstream in the graph to finish
# generating the corresponding detections before it passes through another
# image. All images that come in while waiting are dropped, limiting the number
# of in-flight images between this calculator and
# TfLiteTensorsToDetectionsCalculator to 1. This prevents the nodes in between
# from queuing up incoming images and data excessively, which leads to increased
# latency and memory usage, unwanted in real-time mobile applications. It also
# eliminates unnecessarily computation, e.g., a transformed image produced by
# ImageTransformationCalculator may get dropped downstream if the subsequent
# TfLiteConverterCalculator or TfLiteInferenceCalculator is still busy
# processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:detection_tensors"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Transforms the input image on GPU to a 320x320 image. To scale the image, by
# default it uses the STRETCH scale mode that maps the entire input image to the
# entire transformed image. As a result, image aspect ratio may be changed and
# objects in the image may be deformed (stretched or squeezed), but the object
# detection model used in this graph is agnostic to that deformation.
node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "IMAGE_GPU:transformed_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 150
      output_height: 150
    }
  }
}

# Converts the transformed input image on GPU into an image tensor stored as a
# TfLiteTensor.
node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE_GPU:transformed_input_video"
  output_stream: "TENSORS_GPU:image_tensor"
}

# Runs a TensorFlow Lite model on GPU that takes an image tensor and outputs a
# vector of tensors representing, for instance, detection boxes/keypoints and
# scores.
node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS_GPU:image_tensor"
  output_stream: "TENSORS:detection_tensors"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
      model_path: "rps.tflite"
    }
  }
}

# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "INPUT_FRAME_GPU:throttled_input_video"
  #input_stream: "render_data"
  output_stream: "OUTPUT_FRAME_GPU:output_video"
}
`
------------------------------------------------------------------------------------
Note: the only different is the model_path and the ImageTransformationCalculatorOptions's output size.

addition Info:
  1.my model "rps.tflite" is converted from Tf2.0 model with the TF API:
    converter=tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()
  2.this rps.tflite can work well in my another demo, but that demo does not use mediapipe.
  3.my model's source code address:
    https://colab.research.google.com/drive/1kD9dCvPy4XSmwV6T8HbtK_fRT2tEFbga
    which is base on:
    https://github.com/lmoroney/dlaicourse/blob/master/Course%202%20-%20Part%208%20-%20Lesson%202%20-%20Notebook%20(RockPaperScissors).ipynb

What I guess:
  1. Maybe I have got the wrong way to make my tflite model
  2. Maybe It is a compatibility issue of tflite

I don't know what to do next. Anyone can help me?

**Comment by lcycoding** [comment]
Did you capture any error log ?

I noticed that you use gpu mode to run the graph, there might be incompatible issues with your own model

Also, please make sure that your tflite input / output format fits the original one

**Comment by menghaocheng** [comment]
Tks Icycoding,

There no relative info in the log.

Indeed use gpu mode to run the graph, but I don't think It makes this trouble. because before I changing the tflite model it can work very well.

my .lite model's input shape is (150, 150, 3). On my understanding, the real input image's shape is determined by ImageTransformationCalculator's node_options:{ output_width: 150 output_height:150} . 
my .lite model's output is a (3, 1) tensor. the TfLiteInferenceCalculator whose output_stream is a TENSORS, too.
So, I think my tflite input/output shape is ok.

**Comment by lcycoding** [comment]
hmm...
I've looked into your network structure, that's indeed not a problem on gpu

I think there might be some initialization problem...

But it seems there's no log in your case, you need to wait for official staff

**Comment by menghaocheng** [comment]
The CPU version can work well unexpectedly!
my grpah file is:
`
# MediaPipe graph that performs object detection with TensorFlow Lite on CPU.
# Used in the examples in
# mediapipie/examples/android/src/java/com/mediapipe/apps/objectdetectioncpu and
# mediapipie/examples/ios/objectdetectioncpu.

# Images on GPU coming into and out of the graph.
input_stream: "input_video"
output_stream: "output_video"

# Transfers the input image from GPU to CPU memory for the purpose of
# demonstrating a CPU-based pipeline. Note that the input image on GPU has the
# origin defined at the bottom-left corner (OpenGL convention). As a result,
# the transferred image on CPU also shares the same representation.
node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "input_video"
  output_stream: "input_video_cpu"
}

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for
# TfLiteTensorsToDetectionsCalculator downstream in the graph to finish
# generating the corresponding detections before it passes through another
# image. All images that come in while waiting are dropped, limiting the number
# of in-flight images between this calculator and
# TfLiteTensorsToDetectionsCalculator to 1. This prevents the nodes in between
# from queuing up incoming images and data excessively, which leads to increased
# latency and memory usage, unwanted in real-time mobile applications. It also
# eliminates unnecessarily computation, e.g., a transformed image produced by
# ImageTransformationCalculator may get dropped downstream if the subsequent
# TfLiteConverterCalculator or TfLiteInferenceCalculator is still busy
# processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video_cpu"
  input_stream: "FINISHED:detection_tensors"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video_cpu"
}

# Transforms the input image on CPU to a 320x320 image. To scale the image, by
# default it uses the STRETCH scale mode that maps the entire input image to the
# entire transformed image. As a result, image aspect ratio may be changed and
# objects in the image may be deformed (stretched or squeezed), but the object
# detection model used in this graph is agnostic to that deformation.
node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:throttled_input_video_cpu"
  output_stream: "IMAGE:transformed_input_video_cpu"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 150
      output_height: 150
    }
  }
}

# Converts the transformed input image on CPU into an image tensor stored as a
# TfLiteTensor.
node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE:transformed_input_video_cpu"
  output_stream: "TENSORS:image_tensor"
}

# Runs a TensorFlow Lite model on CPU that takes an image tensor and outputs a
# vector of tensors representing, for instance, detection boxes/keypoints and
# scores.
node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS:image_tensor"
  output_stream: "TENSORS:detection_tensors"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
      model_path: "rps.tflite"
    }
  }
}


node {
  calculator: "TfLiteTensorsToClassificationCalculator"
  input_stream: "TENSORS:detection_tensors"
  output_stream: "CLASSIFICATIONS:classifications"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteTensorsToClassificationCalculatorOptions] {
      min_score_threshold: 0.0
      top_k: 1
      label_map_path: "rps_labelmap.txt"
    }
  }
}


node {
  calculator: "ClassificationsToRenderDataCalculator"
  input_stream: "CLASSIFICATIONS:classifications"
  output_stream: "RENDER_DATA:render_data"
  node_options: {
    [type.googleapis.com/mediapipe.ClassificationsToRenderDataCalculatorOptions] {
      text_delimiter: ":"
      thickness: 0.5
      color { r: 0 g: 0 b: 255}
      text: { 
        left: 0.0
        baseline: 0.5
        font_height: 0.4 
        normalized: true
      }
    }
  }
}

# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "INPUT_FRAME:throttled_input_video_cpu"
  input_stream: "render_data"
  output_stream: "OUTPUT_FRAME:output_video_cpu"
}

# Transfers the annotated image from CPU back to GPU memory, to be sent out of
# the graph.
node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "output_video_cpu"
  output_stream: "output_video"
}
`

(note: I've add a calculator named 'ClassificationToRenderDataCalculaor' by referencing https://github.com/google/mediapipe/pull/168. But  this has no business with my trouble)

How can this happen? What's wrong with GPU version's Calculators?

**Comment by lcycoding** [comment]
I think there are two possible causes
1. tflite gpu delegate initialization 
2. some gpu related error in process() or open()

If 1 is the problem, you will need to revise the network node to fit in gpu delegation

For 2, 
You could add 
#include<android/log.h>
#define LOGD(…)__android_log_print(ANDROID_LOG_DEBUG, “mediapipeDebug”, __VA_ARGS__)
to capture anything you would like to see in the calculator

Good luck

**Comment by eknight7** [comment]
Hi @menghaocheng ! Were you able to get any logs to help debug your issue?

**Comment by yxchng** [comment]
@lcycoding Unable to add <android/log.h> - Code cannot find it.

**Comment by lcycoding** [comment]
Weird...
What NDK version did you use and what build system were you using?

**Comment by yxchng** [comment]
@lcycoding I have no problem now. I was trying to compile using Desktop. Apparently this only works for Android compilation.

**Comment by PrinceP** [comment]
Hi @yxchng, I am receiving the following error in the logs. 
@mgyong 

`
2020-02-07 23:55:12.471 10236-10280/com.google.mediapipe.apps.handdetectiongpu I/tflite: Replacing 11 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
2020-02-07 23:55:14.521 10236-10280/com.google.mediapipe.apps.handdetectiongpu I/Adreno: ERROR: 0:6: 'unknown' : not a legal layout qualifier id 
    ERROR: 0:6: 'unknown' : Syntax error:  syntax error
    INTERNAL ERROR: no main() function!
    ERROR: 2 compilation errors.  No code generated.
2020-02-07 23:55:14.667 10236-10280/com.google.mediapipe.apps.handdetectiongpu E/tflite: TfLiteGpuDelegate Prepare: Shader compilation failed: ERROR: 0:6: 'unknown' : not a legal layout qualifier id 
    ERROR: 0:6: 'unknown' : Syntax error:  syntax error
    INTERNAL ERROR: no main() function!
    ERROR: 2 compilation errors.  No code generated.
2020-02-07 23:55:14.668 10236-10280/com.google.mediapipe.apps.handdetectiongpu E/tflite: Node number 11 (TfLiteGpuDelegate) failed to prepare.
2020-02-07 23:55:14.668 10236-10280/com.google.mediapipe.apps.handdetectiongpu E/tflite: Restored previous execution plan after delegate application failure.
`

**Comment by shehramjamil** [comment]
> I think there are two possible causes
> 
> 1. tflite gpu delegate initialization
> 2. some gpu related error in process() or open()
> 
> If 1 is the problem, you will need to revise the network node to fit in gpu delegation
> 
> For 2,
> You could add
> #include<android/log.h>
> #define LOGD(…)__android_log_print(ANDROID_LOG_DEBUG, “mediapipeDebug”, **VA_ARGS**)
> to capture anything you would like to see in the calculator
> 
> Good luck


Hi,
I got the same problem when using gpu but on cpu it works fine.
I got an error in the log which is  "Read buffer does not match write buffer size."
