### ISSUE TITLE
 How do I dynamically set the face_detection_front.tflite model path?

### ISSUE THREAD

**Issue by aoxipo** [google/mediapipe#1990]
hei, i am trying to using the face_mesh solution to do something ( C++) , and now i want to set the model path by Initialization function like set  `mediapipe/graphs/face_mesh/face_mesh_desktop_live.pbtxt` 
i try to add a new input_stream: "face_mode_path" in the` face_detection_front_cpu.pbtxt` and change 
```
node {
  calculator: "FaceLandmarkFrontCpu"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "FACE_MODEL_PATH:face_model_path"   #add to set the model path   dynamically
  input_side_packet: "NUM_FACES:num_faces"
  output_stream: "LANDMARKS:multi_face_landmarks"
  output_stream: "ROIS_FROM_LANDMARKS:face_rects_from_landmarks"
  output_stream: "DETECTIONS:face_detections"
  output_stream: "ROIS_FROM_DETECTIONS:face_rects_from_detections"
}
```
```
node {
  calculator: "InferenceCalculator"
  input_stream: "TENSORS:input_tensors"
  output_stream: "TENSORS:detection_tensors"
  options: {
    [mediapipe.InferenceCalculatorOptions.ext] {
      model_path: "FACE_MODEL_PATH:face_model_path" # "mediapipe/modules/face_detection/face_detection_front.tflite" this is the original path
      delegate { xnnpack {} }
    }
  }
}
```
then  using Packet to Initialization the path ,here is my code:

`graph.AddPacketToInputStream(kFaceModelInputStream, mediapipe::MakePacket<std::string>(face_model_path) );`

 i have failed, there a error message is can't open 'FACE_MODEL_PATH:face_model_path' It seems to read a string not variable 

What should I do? is there any way to get node InferenceCalculator and set path dynamically?

**Comment by hadon** [comment]
The way you have formulated the dynamic calculator option is exactly how we would like graph options to work eventually.  But for now, the "InferenceCalculatorOptions" can only be used for constant values.  A few calculators accept dynamic options separately through input-side-packets and/or input-streams.  For example, InferenceCalculator accepts an already loaded model through the "MODEL" input-side-packet, but does not accept a model-path through an input-stream.  

MediaPipe users usually resort to re-initializing the calculator-graph when a new model is selected dynamically.  Let me know if that approach could cover your use case.

**Comment by aoxipo** [comment]
think you for your help!!!!!!!!!!

**Comment by jinfagang** [comment]
@hadon Hello, but I need specific a customized path, does it not support?
