### ISSUE TITLE
mjpeg stream

### ISSUE THREAD

**Issue by crouse12** [google/mediapipe#1996]
Dear All,
Is it possible use mediapipe for mjpeg stream in javascript?

**Comment by sgowroji** [comment]
Hi @crouse12, Could you please share your use case with complete details. Thanks!

**Comment by crouse12** [comment]
I want to use for esp32cam.
The ESP32-CAM is a very small camera module with the ESP32-S chip that costs approximately $10. Besides the OV2640 camera, and several GPIOs to connect peripherals, it also features a microSD card slot that can be useful to store images taken with the camera or to store files to serve to clients.

https://www.instructables.com/ESP-32-Camera-Streaming-Video-Over-WiFi-Getting-St/

**Comment by crouse12** [comment]
> Hi @crouse12, Could you please share your use case with complete details. Thanks!

Dear sgowroji ,
I create a python program for esp32cam and mediapipe.
Test video:
https://www.youtube.com/watch?v=GGXMqVeCC7g
Python code:
https://github.com/crouse12/python_for_mediapipe_and_esp32cam

**Comment by sgowroji** [comment]
Hi @crouse12, We have not tried doing with it. But you can share your observation and let us know if you face any difficulty or errors while doing it. Thanks!

**Comment by crouse12** [comment]
I find there are many mediapipe examples for camera.
However, I need some mediapipe examples for an image.
If you can give me some examples like holistic, Hands etc.
I can use them for mjpeg stream.

**Comment by sgowroji** [comment]
Hi @crouse12, You can try the examples from [here](https://google.github.io/mediapipe/getting_started/javascript)

**Comment by mhays-google** [comment]
All of the examples use the SourcePicker control, which, at the very least,
allows you to upload images and videos.  We will be adding example images
and videos soon.
