### ISSUE TITLE
Missing Required Sections of Model Cards for Objectron and KNIFT

### ISSUE THREAD

**Issue by glnmzx888** [google/mediapipe#1999]
We would like to check in terms of the contents of the model cards for models like Objectron (https://drive.google.com/file/d/1CMhN7Npdq0Dt2j0_z69mai2-m7oUTRKF/view) and KNIFT(https://drive.google.com/file/d/1RCdA83a8JDV3ZPS-mtpsV8mTj3r0F9s-/view). For the model cards paper, Model Cards for Model Reporting (https://dl.acm.org/doi/10.1145/3287560.3287596), they require the following details: Model Details, Factors (Groups, Instrumentation, Environment), Metrics (Model performance measures, Decision thresholds, Approaches to uncertainty and variability) and Evaluation Data (Datasets, Motivation, Preprocessing). But Objectron and KNIFT models are missing the information of these sections (a.k.a., Instrumentation, Environment, Decision thresholds, Approaches to uncertainty and variability and preprocessing). Can you please include them?

**Comment by sgowroji** [comment]
Hi @glnmzx888, We have updated most of our model cards here https://google.github.io/mediapipe/solutions/models.html#mediapipe-models-and-model-cards. Could you please go through them and let us know if you are looking for anything more details. Thanks!
