### ISSUE TITLE
Demo app build issue with Bazel 0.27.0

### ISSUE THREAD

**Issue by chenloveheimei** [google/mediapipe#2]
Hello,My name is Long.
Description:
bazel:0.27.0
ubuntu:16.04
ndk:r16b

This is my Error:
**long@long:/media/long/data/android/mediapipe$ bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu**
DEBUG: Rule 'gmaven_rules' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "33027de68db6a49a352f83808fa9898c4930d39aa6fb0edc6bb3d3eec6e2bc7d"
DEBUG: Call stack for the definition of repository 'gmaven_rules' which is a http_archive (rule definition at /home/long/.cache/bazel/_bazel_long/2855d1951dc2684b853376a37e34b96b/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /media/long/data/android/mediapipe/WORKSPACE:124:1
INFO: Call stack for the definition of repository 'eigen_archive' which is a tf_http_archive (rule definition at /home/long/.cache/bazel/_bazel_long/2855d1951dc2684b853376a37e34b96b/external/org_tensorflow/third_party/repo.bzl:126:19):
 - /home/long/.cache/bazel/_bazel_long/2855d1951dc2684b853376a37e34b96b/external/org_tensorflow/tensorflow/workspace.bzl:148:5
 - /media/long/data/android/mediapipe/WORKSPACE:96:1
**ERROR**: /media/long/data/android/mediapipe/mediapipe/framework/BUILD:52:1: in //mediapipe/framework:transitive_protos.bzl%transitive_protos_aspect aspect on proto_library rule //mediapipe/framework:calculator_options_proto: 
Traceback (most recent call last):
	File "/media/long/data/android/mediapipe/mediapipe/framework/BUILD", line 52
		//mediapipe/framework:transitive_protos.bzl%transitive_protos_aspect(...)
	File "/media/long/data/android/mediapipe/mediapipe/framework/transitive_protos.bzl", line 97, in _transitive_protos_aspect_impl
		[f for f in target.files if (f.extension == "a")]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
WARNING: API level 27 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 26
**ERROR**: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:facedetectiongpu' failed; build aborted: Analysis of target '//mediapipe/framework:calculator_options_proto' failed; build aborted
INFO: Elapsed time: 3.800s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 12 targets configured)
    Fetching @com_google_common_flogger; fetching
    Fetching @com_google_common_flogger_system_backend; fetching

thx.

**Comment by jiuqiant** [comment]
Hi Long,

Thanks for reporting the issue! 
The problem is related to the latest version of Bazel (0.27.0), which is released on June 17. Bazel made several incompatible changes from 0.26.1 to 0.27.0. My apologies for not testing the code with Bazel 0.27.0 yet, and we will be working on a fix. Without the fix, you may try the following command line to build the demo app with Bazel 0.27.0:
$ bazel clean --expunge
$ bazel build -c opt --config=android_arm64 \
    mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu \
    --incompatible_depset_is_not_iterable=false \
    --incompatible_disable_deprecated_attr_params=false \
    --incompatible_no_support_tools_in_action_inputs=false

FYI, if you take a close look at the error message you pasted above, it also guides you how to add the incompatible flags. 

We will keep you posted. Thanks.

**Comment by jiuqiant** [comment]
https://github.com/google/mediapipe/commit/2aaf4693db5b0a5019cc20372ac791408c704dcf should fix the Bazel incompatiblity issue.

BTW, the minimum Android NDK version that MediaPipe requires is r17c. By using Android NDK r16b, you may encounter the following error soon:
```bash
external/org_tensorflow/tensorflow/lite/delegates/gpu/common/model_transformer.cc:69:53: error: no member named 'to_string' in namespace 'std'
        reporter_->AppliedTransformation(name, std::to_string(node_id),
                                               ~~~~~^
external/org_tensorflow/tensorflow/lite/delegates/gpu/common/model_transformer.cc:73:54: error: no member named 'to_string' in namespace 'std'
        reporter_->DeclinedTransformation(name, std::to_string(node_id),
                                                ~~~~~^
```

Please consider switching to a later Android NDK version. Let me know if you have more questions.

**Comment by mgyong** [comment]
@chenloveheimei Thanks for using MediaPipe. My team would love to get feedback from you about your use of MediaPipe

It would be great if you could answer the below questions
1) What is your use case for MediaPipe? 
2) Any feedback about how easy or difficult it is to use MediaPipe?

Thanks
Ming
