### ISSUE TITLE
APK for Hair Segmentation 

### ISSUE THREAD

**Issue by mabdullahrafique** [google/mediapipe#20]
Hello!
Can you provide the apk for hair segmentation, because I am not able to generate it from the commands.
Thanks

**Comment by mgyong** [comment]
Can you report the issues you are facing when you follow the instructions for building the [hair segmentation app](https://mediapipe.readthedocs.io/en/latest/hair_segmentation_mobile_gpu.html)?

**Comment by mabdullahrafique** [comment]
Yes, I tried it but bazel does not seem to work. It always gives error on androidsdk which I supplied correctly. I spend 5 to 6 days to correct this, but it did'nt seem to work.

**Comment by jiuqiant** [comment]
@mabdullahrafique , please pull our repo again and retry [the build commands](https://github.com/google/mediapipe/blob/master/mediapipe/docs/hair_segmentation_mobile_gpu.md) with Android SDK 29 and NDK 17c (or above). All the required SDK packages are listed in [install.md](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#setting-up-android-sdk-and-ndk), please double check you have those packages. If you still see an error, please copy and paste the error message here. It will benefit more users if we can solve the issue systematically!

**Comment by mabdullahrafique** [comment]
Okay, I will try it again.

**Comment by chuoling** [comment]
You could download the APK from https://drive.google.com/open?id=1mmLtyL8IRfCUbqqu0-E-Hgjr_e6P3XAy.
