### ISSUE TITLE
tensorrt engine instead of tflite for faster processing on Xavier Jetson

### ISSUE THREAD

**Issue by AndreV84** [google/mediapipe#2000]
```
ls /usr/lib/aarch64-linux-gnu/ | grep libcudnn.so
libcudnn.so
libcudnn.so.8
libcudnn.so.8.0.0
```

```
 nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_21:14:42_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

```

```
/usr/local/cuda-10.2/targets/aarch64-linux/lib/libcupti.so
/usr/local/cuda-10.2/targets/aarch64-linux/lib/libcupti.so.10.2
/usr/local/cuda-10.2/targets/aarch64-linux/lib/libcupti.so.10.2.75

```

```
/usr/local/cuda-10.2/targets/aarch64-linux/lib/libnvperf_host.so
/usr/local/cuda-10.2/targets/aarch64-linux/lib/libnvperf_target.so
```
that is the environment.
The question is how to add proper .bazelrc modifications as proposed in the post won't appear to match anything https://github.com/google/mediapipe/blob/master/docs/getting_started/gpu_support.md

**Comment by txf-** [comment]
Would this actually be faster than just using tensorflow cuda?

**Comment by mcclanahoochie** [comment]
mediapipe relies on the tensorflow library (not tflite) to leverage cuda devices.

i don't think tflite has cuda support, only opengl ES, which jetson has.

if you are just comparing performance of tensorrt and tensorflow cuda, that can be done independent of mediapipe. running either in mediapipe will be all CPU based except for the inference.

running tflite inference in opengl mediapipe on jeston will probably be faster

**Comment by sgowroji** [comment]
Hi @AndreV84, Did you get a chance to go through the above [comment](https://github.com/google/mediapipe/issues/2000#issuecomment-864301448). Thanks!

**Comment by AndreV84** [comment]
@sgowroji to be tried it needs to be extended with exact details for implementation, in my opinion

**Comment by kevinwhzou** [comment]
The mediapipe_plus project can help you use the tensorrt interface to accelerate mediapipe inference.
https://github.com/houmo-ai/mediapipe_plus

**Comment by AndreV84** [comment]
@kevinwhzou thank you fir sharing! I wil try to setup it on AGX

**Comment by sureshdagooglecom** [comment]
Hi @AndreV84 ,
Are you still looking for the resolution on this issue.

**Comment by AndreV84** [comment]
@sureshdagooglecom 
Thank you for following up
I wil have to try again
So do you [will you] support dockerized mediapipe [or not dockerized] implementation on nvidia jetson Orin device ?

**Comment by kuaashish** [comment]
Hi @AndreV84,
Currently, we haven't tested against the Jetson devices. However, You can keep track on this [guide](https://github.com/google/mediapipe/tree/master/mediapipe/examples/coral) to build MediaPipe on the Edge device. Thank you!

**Comment by kuaashish** [comment]
Hello @AndreV84,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
