### ISSUE TITLE
Error building handtracking example

### ISSUE THREAD

**Issue by ankitacoffee** [google/mediapipe#2001]
I get this error while trying to build. Looks like it is a linking error.

INFO: Build option --linkopt has changed, discarding analysis cache.
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu (0 packages loaded, 6861 targets configured).
INFO: Found 1 target...
ERROR: /home/ankita/Documents/test_docker/mediapipe/mediapipe/examples/desktop/hand_tracking/BUILD:36:10: Linking of rule '//mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu-2.params

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: error: cannot find -lGLESv2

**Comment by ankitacoffee** [comment]
I have tried reinstalling opencv. Still gives the same error. what could be the root cause. can someone point me there so I know what to look for?
I am using ubuntu 18.04

**Comment by RitvikMandyam** [comment]
Have you installed the GPU libraries? It looks to me like your linker is unable to find libgles2-mesa-dev. You can install it, along with the other GPU-related libraries, by running:
`
sudo apt-get install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev
`

**Comment by ankitacoffee** [comment]
yes I have all the three libraries installed.

**Comment by HaoyuWang00** [comment]
Same problem here, error code:
```
/home/haoyu/mediapipe/mediapipe/examples/desktop/hand_tracking/BUILD:36:10: 
Linking of rule '//mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu' failed (Exit 1): 
gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu-2.params
```
Using gcc 9.3.0, ubuntu 20.4

**Comment by HaoyuWang00** [comment]
> Same problem here, error code:
> 
> ```
> /home/haoyu/mediapipe/mediapipe/examples/desktop/hand_tracking/BUILD:36:10: 
> Linking of rule '//mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu' failed (Exit 1): 
> gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu-2.params
> ```
> 
> Using gcc 9.3.0, ubuntu 20.4

Just tried with the CPU version and got basically the same error. Could it be the problem with my gcc version?

**Comment by RitvikMandyam** [comment]
It could be your GCC version... Have you guys tried building the examples inside a Docker container? It's not really a fix, but it may help you get up and running, at least. The instructions for how to get the container up and running are here:
https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker

**Comment by mcclanahoochie** [comment]
please check gpu system compatibility via [these instructions](https://google.github.io/mediapipe/getting_started/gpu_support.html#opengl-es-setup-on-linux-desktop)

there are also extra build flags to set, mentioned in the doc link above

**Comment by HaoyuWang00** [comment]
Hi @mcclanahoochie , thank you for your reply! I will try the instruction and update soon.
