### ISSUE TITLE
Failed to run the graph: Failed to get packet from output stream 'left_iris_depth_mm'.

### ISSUE THREAD

**Issue by LiuyangNice** [google/mediapipe#2002]
when i run iris_depth_from_image_desktop on window,get this error "E20210508 16:35:51.339612 36632 iris_depth_from_image_desktop.cc:155] Failed to run the graph: Failed to get packet from output stream 'left_iris_depth_mm'."
how to do it

**Comment by noahchan** [comment]
image must have EXIF data

**Comment by rmothukuru** [comment]
@LiuyangNice,
Can you please let us know if the above comment helped in resolving your issue? Thanks!

**Comment by LiuyangNice** [comment]
yes,my pic is from videos without EXIF data,

**Comment by TakhirMamirov** [comment]
My image has metadata, but I'm still getting the same error (in Docker):

`Failed to run the graph: Failed to get packet from output stream 'left_iris_depth_mm'`
