### ISSUE TITLE
Some questions about compiling on windows 

### ISSUE THREAD

**Issue by lilinxiong** [google/mediapipe#2004]
Hi~ First of all thank you very much for opening up such a great MediaPipe. Now I have some problems and need your help.
I followed the document and compiled it successfully on windows. But there is still a long way to go before it is put into use, and now I have some questions.
### background: 
I need to embed MediaPipe into our current PC program. But our current program is 32bit. And the compiled MediaPipe is 64bit. So some changes need to be made, which is the root cause of my open issue. 

---------

I checked the relevant documents (bazel gflags glog...) and found that they all support 32bit, and I tried glog, 32bit can be compiled and passed. But the problem is that they all need the latest bazel, which is bazel 4.0.0.
I saw #1862 I very much agree with what you mentioned, but now I want to try to compile a 32bit dll or executable program under Windows. So, what should I do to use the latest bazel? That is version 4.0.0+.
And I saw that [TensorFlow_Lite also supports windows 32bit](https://github.com/tensorflow/tensorflow/issues/47166#issuecomment-803076764)(Although the 32bit release version is not compiled, I think this is not a problem. I want to try to solve it), so I think I should spend some time on it.

**Comment by jiuqiant** [comment]
You can change the value in https://github.com/google/mediapipe/blob/master/.bazelversion to be 4.0.0 locally. We fixed it to be 3.7.2 is for supporting all platforms smoothly and feel free to change it locally.

**Comment by lilinxiong** [comment]
Thanks, I will try it recently.

**Comment by lizhanping** [comment]
> Thanks, I will try it recently.

did you try it ? i have same case .

**Comment by lilinxiong** [comment]
of course. It is possible to build 32bit, but I only did half of it, because I have to do other things, and it will take a while before I can do the following.......

**Comment by lizhanping** [comment]
> of course. It is possible to build 32bit, but I only did half of it, because I have to do other things, and it will take a while before I can do the following.......

ok, can you share some keypoints or give some tips for building it?

**Comment by lilinxiong** [comment]
> > of course. It is possible to build 32bit, but I only did half of it, because I have to do other things, and it will take a while before I can do the following.......
> 
> ok, can you share some keypoints or give some tips for building it?

Bazel 4.0.0 can support build windows 32bit, but all MediaPipe dependencies (TensorFlow-Lite, XNNPACK....) build scripts (WORKSPACE, BUILD.bazel, BUILD) have not implemented compiling windows 32bit configuration information. In fact, they all support windows 32bit, In the dependency, add the windows 32bit configuration information, and then build it. Among them, TensorFlow-Lite will have an error when building the Release version. The reason is generated by the VS compiler. The solution is: changed to -O1.

For the configuration information of Windows 32bit build, you can refer to the current configuration item of windows 64bit. Since I am currently a Mac OS, I can't see the changes made on windows before. You need to come by yourself.

link: 
[bazel 4.0.0 support build windows 32bit](https://github.com/bazelbuild/bazel/pull/11938).
[TensorFlow-Lite build Windows 32bit](https://github.com/tensorflow/tensorflow/issues/47166#issuecomment-829780437).

**Comment by lizhanping** [comment]
> > > of course. It is possible to build 32bit, but I only did half of it, because I have to do other things, and it will take a while before I can do the following.......
> > 
> > 
> > ok, can you share some keypoints or give some tips for building it?
> 
> Bazel 4.0.0 can support build windows 32bit, but all MediaPipe dependencies (TensorFlow-Lite, XNNPACK....) build scripts (WORKSPACE, BUILD.bazel, BUILD) have not implemented compiling windows 32bit configuration information. In fact, they all support windows 32bit, In the dependency, add the windows 32bit configuration information, and then build it. Among them, TensorFlow-Lite will have an error when building the Release version. The reason is generated by the VS compiler. The solution is: changed to -O1.
> 
> For the configuration information of Windows 32bit build, you can refer to the current configuration item of windows 64bit. Since I am currently a Mac OS, I can't see the changes made on windows before. You need to come by yourself.
> 
> link:
> [bazel 4.0.0 support build windows 32bit](https://github.com/bazelbuild/bazel/pull/11938).
> [TensorFlow-Lite build Windows 32bit](https://github.com/tensorflow/tensorflow/issues/47166#issuecomment-829780437).

thanks,it sounds like that need a lot of changes ~

> changes

**Comment by sgowroji** [comment]
Hi @lilinxiong, Can we close this issue if you above query is answered?

**Comment by lilinxiong** [comment]
@sgowroji No, it cannot. Because I did other things and did not continue, I am not sure that my method can really solve it. thanks.I will find time to continue, but I have been too busy recently.

**Comment by lilinxiong** [comment]
Hi @sgowroji Are there any plans to open the project discussions tab? For example, this question is more like someone needs to discuss and get the correct answer, rather than an issue.
For example, [Discussions](https://github.com/google/oboe/discussions) like [Oboe’s](https://github.com/google/oboe)

**Comment by sgowroji** [comment]
Hi @lilinxiong, Thank you for suggesting the above. In discussions you can use our slack channel community, there are many MediaPipe users who are active and can guide you well if needed any suggestions. And to get the immediate response for higher priority issues github is the only way to get it done.

**Comment by lilinxiong** [comment]
ok thanks~

**Comment by lilinxiong** [comment]
emmmm, Although it has been closed for a long time, I want to synchronize my results. I have compiled a Windows 32bit program last week and compiled a windows 32bit dll this week. Mediapipe can run on windows 32bit.

**Comment by xfj81525** [comment]
hello @lilinxiong ,would you like to share your experience to compile win32 mediapipe
