### ISSUE TITLE
Mediapipe installation error

### ISSUE THREAD

**Issue by jackjack3006** [google/mediapipe#2005]
In the mediapipe installation, it is not running on python3.7 if there is not venv present. I had to run it on a venv for my project. And it is not very compatible with Ubuntu as Ubuntu 18.04 default uses python 3.6.9 causing problems. Also it is not available for python 3.8 as a colleague of mine tried to run the project I made. It would be helpful if these errors can be fixed as soon as possible for multi platform usage.

**Comment by jackjack3006** [comment]
![Screenshot from 2021-05-09 12-50-00](https://user-images.githubusercontent.com/74947682/117563703-3c33b680-b0c5-11eb-970e-f5ee853e4a7b.png)

**Comment by jiuqiant** [comment]
The latest version of mediapipe supports python 3.7 and above on x86_64 linux, x86_64 macos, and amd64 windows. Please see https://github.com/google/mediapipe/blob/master/docs/getting_started/troubleshooting.md#python-pip-install-failure for more details. If you use python 3.6, I think v0.8.3 still has the support: https://files.pythonhosted.org/packages/12/74/f55fc21266c08c304f05a409ba388c50f94fb52ef0f99100bb60287c4d91/mediapipe-0.8.3-cp36-cp36m-manylinux2014_x86_64.whl.

**Comment by jackjack3006** [comment]
I use pip3 when I install for the python3. Ubuntu 18.04 runs default python 3.7. So changing that is of no use. And I have verified that the python binary and pip binary are the 64-bit version. I do use the venv but when I ask people to check out my project for review they run into all sorts of issues. That is why I had posted this PR. 
Thanks for the help!

**Comment by jackjack3006** [comment]
Okk.
Well I ran uname -m and it sent back x86_64 which I understand as aarch64 Ubuntu. So I don't think that is the problem. And this is consistent with other machines too. Windows and Linux

**Comment by jiuqiant** [comment]
Sorry,  I don't have any new clue on how to solve your installation issue. 

We follow PyPI instructions to build Linux, macOS, and Windows wheels and put them at https://pypi.org/project/mediapipe/#files. I don't understand why `pip install mediapipe` doesn't work on any of those platforms on your side.

**Comment by jackjack3006** [comment]
Alright. Thanks for trying
