### ISSUE TITLE
how to support yolo model for object detect?

### ISSUE THREAD

**Issue by bugmany** [google/mediapipe#2009]
i 've trained yolo model for object detect, and i want to integrating the model into mediapipe, whether it support or not, if support integrating, how to do, could you give me advice, thanks a lot.

**Comment by gustavorps** [comment]
+1

**Comment by ibrandiay** [comment]
@bugmany do you have an answer in your request ? me too i am interest in this question.

**Comment by jiuqiant** [comment]
@sgowroji, please assign this to the owner of object detection.

**Comment by sgowroji** [comment]
Hi @bugmany, Which platform are you referring?

**Comment by bugmany** [comment]
android and iOS.

**Comment by ahmadyan** [comment]
We do not support Yolo, as it is quite out-dated, instead we recommend to use our SSD MobileNet object detection in Mediapipe.

Typically, if you have a tensorflow model you'll need to convert it to mobile version with [tflite_converter](https://www.tensorflow.org/lite/examples/object_detection/overview). Then use our inference calculator to run inference on device, our tflite inference calculators ensures that the model runs fine on different devices with different GPU backend such as Vulkan, OpenGL, cpu, etc. However, Yolo pre-dates all of this, and comes with its own darknet for inference, and the more recent quantized adoptions like xnornet are not supported.  So if you insist on adding this to Mediapipe, you'll need to write a C++ wrapper for Yolo and then directly call that code in Mediapipe, then you have to make sure models runs fine on different gpu backend, etc.

**Comment by sgowroji** [comment]
Hi @bugmany,  Could you please have a look at the [comment](https://github.com/google/mediapipe/issues/2009#issuecomment-892928601).

**Comment by bugmany** [comment]
ok, thanks, then how to "you'll need to write a C++ wrapper for Yolo and then directly call that code in Mediapipe", could you provide demo for information?

**Comment by ahmadyan** [comment]
You can take a look at [Mediapipe Object Detection Demo](https://google.github.io/mediapipe/solutions/object_detection.html), in particular the [ssd_anchors_calculator.cc](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/calculators/tflite/ssd_anchors_calculator.cc)

**Comment by ibrandiay** [comment]
@ahmadyan Thank you for your answers . So if I understood correctly, a yolo model converted to tflite should be able to run normally without needing a c ++ wrapper?

**Comment by ahmadyan** [comment]
If you use tflite you can use our c++ mediapipe wrapper around Yolo for inference. You'll still need to write code to decode the yolo's output and convert it to 2D bounding boxes.

**Comment by ibrandiay** [comment]
@ahmadyanBasically it was a yolo, but after converting to tflite, the output is fine in 2D. So with these conditions I imagine that it would be enough to run on mediapipe without implementing a c ++ wrapper. Tell me if I'm talking nonsense

**Comment by bugmany** [comment]
hi @ahmadyan, I'll try it, thanks a lot.

**Comment by ibrandiay** [comment]
@HungDuong1998 I finally gave up my yolo model to adapt a mobilenet ssd, I have no choice ... The power of google is essential. Yolo is better but he does not have the right support for mobile devices

**Comment by ibrandiay** [comment]
@HungDuong1998 yes

**Comment by HungDuong1998** [comment]
But not successful still? The yolo tflite is not compatible for google pipeline?

**Comment by HungDuong1998** [comment]
Do you have any git repo/blog on this? Why it doesn't work? Is it because of the image size input or what?

**Comment by ibrandiay** [comment]
this is because of the output of the yolo model, you have to write a c ++ wrapper to decode the yolo output. What I don't want to do, in addition you will have problems when you have to run it on GPU. To put it simply, yolo does not have real support for mobiles, unlike google

**Comment by HungDuong1998** [comment]
C++ wrapper is easier or modifying the tflite converter tool you used is easier?
I am newb to all of this really, would love to help but I don't think I can do much

**Comment by bharath5673** [comment]
![test vlcsnap-2022-07-18-16h16m27s337](https://user-images.githubusercontent.com/33729709/179499359-f6cf0855-7aa1-4c7f-8dc3-323b462098aa.png)


https://www.linkedin.com/posts/bharaths5673_yolo-mediapipe-cpu-activity-6954752592426004480-dHlP?utm_source=linkedin_share&utm_medium=member_desktop_web
