### ISSUE TITLE
Hand Tracking: Does the result of desktop example and using the hand_landmark_3d.tflite only be the same?

### ISSUE THREAD

**Issue by Sara533** [google/mediapipe#201]
Two ways:
1、get the hand landmarks by the desktop example of hand tracking;
2、run palm_detection.tflite, and hand_landmark_3d.tflite;
Are they same?

**Comment by mgyong** [comment]
@Sara533 1) pls see the same discussion and sample code (object detection as a starting point) for issue #200 
2) No palm detection.tflite is model for [detecting palm only with output of 7 keypoints](https://lh6.googleusercontent.com/eiAXkFzur-YRrtIYHpV0YTD2SZR_TAojq7K4GqBR9kzR5elW8T0JlAW6EKx2qGPwrW3W10Y1rWATgErf_xd4NlVzXSgT8C7y9cPtDRy8EQ-rc2R6Lhjp65ie1_usaE8ss05fJHA-) while hand_landmark_3d.lite is model for [output of 21 hand keypoints](https://mediapipe.page.link/handgoogleaiblog)
