### ISSUE TITLE
Pose estimation in the wild ?

### ISSUE THREAD

**Issue by timtensor** [google/mediapipe#2010]
Hi , I tried Blazepose estimation and media pipe holistic pose estimation to couple of videos in the wild. It seems to have quite bad tracking of keypoints . For example a rider riding a bike, on a horse back etc.  are there some limitations to it ? I am using single person detection on this .

**Comment by timtensor** [comment]
Hi @rmothukuru any updates on this ?

**Comment by sgowroji** [comment]
Hi @timtensor, We are not supporting for Animals as of now. Thanks!
