### ISSUE TITLE
Mediapipe hand tracking build error on Raspberry Pi 4

### ISSUE THREAD

**Issue by ttamas0713** [google/mediapipe#2011]
Hello!
I'm trying to build hand tracking on Raspberry Pi 4 with Ubuntu 21.04 64bit version but I get the following error:
```
ERROR: /home/tt/.cache/bazel/_bazel_tt/a4050360905611307687f2e9460a1f5b/external/org_tensorflow/tensorflow/core/util/BUILD:372:24: error executing shell command: '/bin/bash -c bazel-out/aarch64-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}  external/local_config_gi...' failed (Exit 127): bash failed: error executing command /bin/bash -c 'bazel-out/aarch64-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c 'bazel-out/aarch64-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/env: 'python': No such file or directory
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1844.734s, Critical Path: 1785.34s
INFO: 159 processes: 94 internal, 65 linux-sandbox.
FAILED: Build did NOT complete successfully
```
Do you have any idea why is this happening?
Python maybe? I have the version 3.9.4.

**Comment by ttamas0713** [comment]
> See https://github.com/google/mediapipe/blob/master/docs/getting_started/troubleshooting.md#missing-python-binary-path

Thanks for the response. I have tried this before but it didn't help. I installed Python 3.7.5 and 3.7.10 but I couldn't make it work because I can't install numpy on the older versions (pip fails on SSL verify or something). Unfortunately, I had to reinstall the OS so I can't tell you the exact error message right now.

**Comment by ttamas0713** [comment]
> > See https://github.com/google/mediapipe/blob/master/docs/getting_started/troubleshooting.md#missing-python-binary-path
> 
> Thanks for the response. I have tried this before but it didn't help. I installed Python 3.7.5 and 3.7.10 but I couldn't make it work because I can't install numpy on the older versions (pip fails on SSL verify or something). Unfortunately, I had to reinstall the OS so I can't tell you the exact error message right now.

I reinstalled everything and I get the following error with python bin path set to python3:

`ERROR: /home/tt/.cache/bazel/_bazel_tt/a4050360905611307687f2e9460a1f5b/external/org_tensorflow/tensorflow/core/util/BUILD:372:24: error executing shell command: '/bin/bash -c bazel-out/aarch64-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}  external/local_config_gi...' failed (Exit 127): bash failed: error executing command /bin/bash -c 'bazel-out/aarch64-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c 'bazel-out/aarch64-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/env: 'python': No such file or directory
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
` 
Any idea what am I missing?

**Comment by ttamas0713** [comment]
Is there any workaround for this error?
`/home/tt/.cache/bazel/_bazel_tt/a4050360905611307687f2e9460a1f5b/external/org_tensorflow/tensorflow/core/util/BUILD:372:24: error executing shell command: '/bin/bash -c bazel-out/aarch64-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-} external/local_config_gi...' failed (Exit 127): bash failed: error executing command /bin/bash -c 'bazel-out/aarch64-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c 'bazel-out/aarch64-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/env: 'python': No such file or directory
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build`

**Comment by sgowroji** [comment]
Hi @ttamas0713, Can you try this workaround https://github.com/google/mediapipe/issues/2298#issuecomment-884232799 Above error encountered for some for having multiple python versions and not linked to the latest.
