### ISSUE TITLE
Building EXE From PY file issue

### ISSUE THREAD

**Issue by Onkar-G** [google/mediapipe#2012]
I have py 3.8 and the latest version of PyPI(pip) installed. I installed mediapipe 3.8(lastest) using: pip install mediapipe I installed OpenCV + VC tools + setuptools + pyinstaller and all the other needed dependencies... I coded a simple python script that detects the hands and controls the pc cursor via webcam and it is working perfectly!

However, when I tried to compile it to exe using pyinstaller it has broken. (As I figured out that the problem is that mediapipe thing hasn't been converted to dlls or something like that)...

Is there any solution?
![NkztU](https://user-images.githubusercontent.com/59895118/117694046-4e544880-b1dc-11eb-8068-0011573a11c5.png)

**Comment by sgowroji** [comment]
Hi @Onkar-G, Have a look at this #1839 (comment).

**Comment by sgowroji** [comment]
Assuming your issue resolved, we are closing this ticket. Please feel free to reach us if the above issue still exists.
