### ISSUE TITLE
Objectron Crashing

### ISSUE THREAD

**Issue by spliko** [google/mediapipe#2017]
I want to create Objectron app from Kotlin but app is crashing.
When I give access to my camera I get black screen and after 2-3seconds app crash and get that error:
![image logcat](https://user-images.githubusercontent.com/84030746/117844443-fc64fe80-b27f-11eb-8f66-8e5d2cd4e476.png)

I have my project on github with my pal: https://github.com/spliko/ObjectronKotlin

**Comment by ahmadyan** [comment]
Duplicate of https://github.com/google/mediapipe/issues/1977

**Comment by rmothukuru** [comment]
@spliko,
Can you please let us know if we can close this issue as it is already being tracked in #1977? Thanks!
