### ISSUE TITLE
[pose] landmark presence is always 0

### ISSUE THREAD

**Issue by emredog** [google/mediapipe#2018]
According the model card: https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview (see last page)

> VISIBILITY Visibility denotes the probability that a keypoint is located within the frame and not occluded either by other body parts or other objects.

> PRESENCE Presence denotes the probability that a keypoint is located within the frame. It does not indicate whether the keypoint is occluded by another body part.

( This is probably related to #1790 , waiting a response since March 24 :disappointed: )

I tried with `mediapipe=0.8.4.2`, the `visibility` works as expected (as a confidence value), but `presence` is always 0, regardless of the input video.

**Comment by rmothukuru** [comment]
@emredog,
As you mentioned rightly, it is a duplicate of #1790. Can you please let us know if we can close this issue, as it is already being tracked there. Thanks!

**Comment by emredog** [comment]
@rmothukuru yes certainly, I wasn't sure if it deserved another issue because of the different version. Closing this then. Thank you for your attention!
