### ISSUE TITLE
How to fill face rectangle (in face mesh) with transparent color?

### ISSUE THREAD

**Issue by midhulavijayan** [google/mediapipe#2019]
Hello, I'm trying to fill the face rectangle with some transparency. I made the "filled" option as true to fill the color. Is there any way to give some transparency for the filled color (alpha blending)?
node {
  calculator: "RectToRenderDataCalculator"
  input_stream: "NORM_RECTS:rects"
  output_stream: "RENDER_DATA:rects_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.RectToRenderDataCalculatorOptions] {
      filled: true
      color { r: 255 g: 0 b: 0 }
      thickness: 4.0
    }
  }
}

**Comment by sgowroji** [comment]
Hi @midhulavijayan, For your understanding https://github.com/google/mediapipe/issues/1743#issuecomment-805334972.

**Comment by sgowroji** [comment]
Hi @midhulavijayan, Did you get a chance to go through the above https://github.com/google/mediapipe/issues/2019#issuecomment-848485339. Thanks

**Comment by midhulavijayan** [comment]
Hi @sgowroji, i have gone through it. i couldn't find any solution from the mentioned comment. Could you please elaborate the steps to fill transparent color?.

**Comment by brucechou1983** [comment]
Check **mediapipe/util/render_data.proto** and you'll find **FilledRectangle** there. Simply modify the calculator to replace Rectangle with FilledRectangle should work.

**Comment by sgowroji** [comment]
Assuming you are resolved with this [comment](https://github.com/google/mediapipe/issues/2019#issuecomment-864713068). We are closing this issue now.
