### ISSUE TITLE
Enabling 3D Version on Desktop GPU for Hand Tracking 

### ISSUE THREAD

**Issue by JECBello** [google/mediapipe#202]
I would like to retrieve the z-coordinates from the desktop implementation of hand tracking using a GPU. I am unsure about how to approach this. Is it possible to just include `--define 3D=true` within the bazel build command, similar to how it is done in the build commands of the mobile version? 

`bazel build -c opt --config=android_arm64`   **`--define 3D=true`** `mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu` 
 
I noticed that the same HandLandmark subgraph is used in both the mobile and desktop example, so I'm hoping that implementing a 3D version on the desktop should be possible. 

Thank you!

**Comment by mgyong** [comment]
@JECBello For the desktop example, you cannot just use the --define 3D=true as that definition is not available in the desktop BUILD file. The simplest way is just to change the tflite model path in the 
[/mediapipe/mediapipe/graphs/hand_tracking/subgraphs/hand_landmark_gpu.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/hand_landmark_gpu.pbtxt) from ``hand_landmark.pbtxt`` to ``hand_landmark_3d.pbtxt``
[See my gist](https://gist.github.com/mgyong/ef387feab3de99bbdbd3bc792a5f4c68#file-hand_landmark_gpu-pbtxt-L58)
![landmark3d](https://user-images.githubusercontent.com/2178001/68062677-1c018b00-fcc9-11e9-915a-c0c8fcdd353c.png)

**Comment by QingyueMeng** [comment]
@mgyong Hi, could you tell me what the commands for the desktop version and which platform you  run on ? Mac OS or Linux?

When I run `bazel run --define MEDIAPIPE_DISABLE_GPU=1     mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu` on Mac OS, It built completed successfully,  but got error like `E1104 20:33:52.379570 321127872 demo_run_graph_main.cc:141] Failed to run the graph: ; Can't find file:` finally.

**Comment by JECBello** [comment]
@mgyong It worked perfectly, thank you so much!

**Comment by QingyueMeng** [comment]
@JECBello I am confused about the 3D version on Desktop GPU for Hand Tracking, could you give me some instructions? I will be very appreciate if you can give me some help.

**Comment by shadowver** [comment]
@mgyong did you mean change the model_path: "mediapipe/models/hand_landmark.tflite" to model_path: "mediapipe/models/hand_landmark_3d.tflite"? Another question thou, I have printed out the z values of hand_landmarks, but the number looked strange to me e.g. -56 and etc. What is the absolute scale of the z value of the landmarks? thanks.

**Comment by romaindebraize** [comment]
> @mgyong did you mean change the model_path: "mediapipe/models/hand_landmark.tflite" to model_path: "mediapipe/models/hand_landmark_3d.tflite"? Another question thou, I have printed out the z values of hand_landmarks, but the number looked strange to me e.g. -56 and etc. What is the absolute scale of the z value of the landmarks? thanks.

the z values look strange for me too, it's between -1e-5 and 7e-5 ... Did you find an answer ?
