### ISSUE TITLE
mediapipe in raspberry pi 4

### ISSUE THREAD

**Issue by aliisaiid98** [google/mediapipe#2020]
i want to use mediapipe in raspberry pi 4 but i don't know how

**Comment by rmothukuru** [comment]
@aliisaiid98,
Please refer this [Github Repository](https://github.com/jiuqiant/mediapipe_python_aarch64) for the detailed information. Thanks!

**Comment by pattanaponny002** [comment]
> i want to use mediapipe in raspberry pi 4 but i don't know how

Same as ur situation, i cant execute any any code as "mediapipe" on pi4 and also it is still waiting any responding from developer whether it is possible

**Comment by aliisaiid98** [comment]
> @aliisaiid98,
> Please refer this [Github Repository](https://github.com/jiuqiant/mediapipe_python_aarch64) for the detailed information. Thanks! 


i did, but i'm stuck at 7th step which uses the "diff - - git" command and it gives me an error says "diff: unrecognized option '--git'"
although i did install git

**Comment by jiuqiant** [comment]
The "diff --git ... " is the content generated by `git diff` command (https://git-scm.com/docs/git-diff). Please modify your local files based on the contents.

**Comment by aliisaiid98** [comment]
> The "diff --git ... " is the content generated by `git diff` command (https://git-scm.com/docs/git-diff). Please modify your local files based on the git diff command output.

I did that but still got an error in 7th step:"python3 setup.py gen_protos && python3 setup.py bdist_wheel"

ERROR: /home/ali/mediapipe/mediapipe/framework/tool/BUILD:93:10: C++ compilation of rule '//mediapipe/framework/tool:encode_as_c_string' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 30 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 30 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc: error: mediapipe/framework/tool/encode_as_c_string.cc: Permission denied gcc: fatal error: no input files compilation terminated. Target //mediapipe/modules/face_detection:face_detection_front_cpu failed to build Use --verbose_failures to see the command lines of failed build steps. INFO: Elapsed time: 7.492s, Critical Path: 0.62s INFO: 75 processes: 75 internal. FAILED: Build did NOT complete successfully "

**Comment by kuaashish** [comment]
Hi @aliisaiid98, Could you please let us know if still looking for resolution or has been resolved as MediaPipe supports the Raspberry pi4 mentioned in the [documentation](https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/README.md). 
Attaching the relevant thread #1346 for your reference. Thank you!
