### ISSUE TITLE
What are the max versions of Android SDK and NDM that will work with the Android Examples?

### ISSUE THREAD

**Issue by kaisark** [google/mediapipe#2021]
What are the max versions of Android SDK and NDM that will work with the mediapipe Android Examples? I am currently using  Ubuntu 20/Android Studio 4.1.3/SDK API 30/NDK 22.

I was reading the installation [instructions](https://google.github.io/mediapipe/getting_started/android.html#option-2-build-with-bazel-in-android-studio) for Android and was wondering if I need to install additional Android SDK and NDM?

FYI: The Hello World C++ Example compiled successfully
\-------------------------------------------------------------------------------
INFO: From ProtoCompile mediapipe/framework/calculator_profile.pb.h:
bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src: warning: directory does not exist.
Target //mediapipe/examples/desktop/hello_world:hello_world up-to-date:
  bazel-bin/mediapipe/examples/desktop/hello_world/hello_world
INFO: Elapsed time: 482.361s, Critical Path: 287.29s
INFO: 484 processes: 16 internal, 468 linux-sandbox.
INFO: Build completed successfully, 484 total actions
INFO: Build completed successfully, 484 total actions
I20210512 14:04:47.450703  8057 hello_world.cc:57] Hello World!
I20210512 14:04:47.451359  8057 hello_world.cc:57] Hello World!
I20210512 14:04:47.451378  8057 hello_world.cc:57] Hello World!
I20210512 14:04:47.451397  8057 hello_world.cc:57] Hello World!
I20210512 14:04:47.451414  8057 hello_world.cc:57] Hello World!
I20210512 14:04:47.451431  8057 hello_world.cc:57] Hello World!
I20210512 14:04:47.451450  8057 hello_world.cc:57] Hello World!
I20210512 14:04:47.451468  8057 hello_world.cc:57] Hello World!
I20210512 14:04:47.451668  8057 hello_world.cc:57] Hello World!
I20210512 14:04:47.451838  8057 hello_world.cc:57] Hello World!

\-----------------------------------
FYI:
I was able to build and install the [handtracking](https://google.github.io/mediapipe/getting_started/android.html#option-2-build-with-bazel-in-android-studio) sample Android app using NDK 20. 
(py37dl) username@Ubuntu-ThinkPadX1C:~/mediapipe$ echo $ANDROID_NDK_HOME 
/home/username/Android/Sdk/ndk/20.0.5594570

(py37dl) username@Ubuntu-ThinkPadX1C:~/mediapipe$ bazel build -c opt --config=android_arm64 --action_env PYTHON_BIN_PATH=$(which python3) --verbose_failures  mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

![Screenshot_20210512-214754.png](https://user-images.githubusercontent.com/3580312/118066757-4841a180-b36d-11eb-8149-02c0201a4c12.png)

**Comment by jiuqiant** [comment]
I think there is minimum requirement of sdk and ndk. For maximum versions, Bazel may still just officially support ndk 21 and below and it sends a warning message if you use ndk 22 and above.

**Comment by sgowroji** [comment]
Hi @kaisark, Did you get a chance to go through the above [comment](https://github.com/google/mediapipe/issues/2021#issuecomment-840842281). Thanks!

**Comment by kaisark** [comment]
Hi @sgowroji. I did read the comment. I tried to use NDK 22, but the bazel build failed. I think the directory structure [changed](https://github.com/android/ndk/blob/master/Changelogs/Changelog-r21.md) between NDK 20 and 21/22. The build could not locate the "platforms" sub-directory.

Change log:
"The legacy toolchain install paths will be removed over the coming releases. These paths have been obsolete since NDK r19 and take up a considerable amount of space in the NDK. The paths being removed are:

platforms
sources/cxx-stl
sysroot
toolchains (with the exception of toolchains/llvm)
In general this change should only affect build system maintainers, or those using build systems that are not up to date. ndk-build and the CMake toolchain users are unaffected, and neither are make_standalone_toolchain.py users (though that script has been unnecessary since r19).

For information on migrating away from the legacy toolchain layout, see the Build System Maintainers Guide for the NDK version you're using."

We can close the issue since NDK 20 is working...

**Comment by sgowroji** [comment]
You can try with the prerequisite mentioned here https://google.github.io/mediapipe/getting_started/android.html#prerequisite. If you face any errors, please share them to investigate further. Thanks!

**Comment by sgowroji** [comment]
Hi @kaisark, Did you get a chance to go through the above [comment](https://github.com/google/mediapipe/issues/2021#issuecomment-849603720). Thanks

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity and assuming your resolved with above comments.
