### ISSUE TITLE
Raspbian Os on raspberry pi4 is possible to use??

### ISSUE THREAD

**Issue by pattanaponny002** [google/mediapipe#2023]
When i launch in the mu on programming i faced with no module name mediapipe

**Comment by rmothukuru** [comment]
@pattanaponny002,
Can you please elaborate your point? Please provide the reproducible code and the screenshots, if possible. Thanks!

**Comment by pattanaponny002** [comment]
Simple question, Mediapipe is be able to use in rpi4 as raspbian os if so pls answer directly thank!!

**Comment by sgowroji** [comment]
Hi @pattanaponny002, Have a look at this https://github.com/google/mediapipe/issues/1346#issuecomment-745715596.
