### ISSUE TITLE
Can not save settings,.aswb already exists

### ISSUE THREAD

**Issue by nitecm** [google/mediapipe#2025]
First time when I import project from Bazel, the Generate from BUILD file directory set wrongly and try to import project from Bazel again and set   the path again but can not save . What step should I take to rectify it

**Comment by sgowroji** [comment]
Hi @nitecm, Could you please respond to the above comment and provide the details mentioned in it. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.
