### ISSUE TITLE
face_mesh solution problem ---- the algorithm is not expressive enough in some scenarios

### ISSUE THREAD

**Issue by aoxipo** [google/mediapipe#2029]
Hello , i try to use `face_mesh `solution, and I found that the algorithm failed in some scenarios, I used `Python `and `Desktop `to verify the algorithm, here is the picture:

![微信图片_20210514093236](https://user-images.githubusercontent.com/32930325/118208170-dc5c5780-b498-11eb-958b-bc68daeb1931.png)
![微信图片_20210514093010](https://user-images.githubusercontent.com/32930325/118208493-72907d80-b499-11eb-8278-373ec757d1fd.png)

and i Try to load only the face_landmark model under tflite framework. and i found the algorithm you came up with,always tends to regression to a fixed face structure,This may be the reason why the accuracy of your algorithm fails in some scenarios. maybe your dataset is not feature-rich, and i also found the effect of nose landmark is also poor in some scenes,

![微信图片_20210514093241](https://user-images.githubusercontent.com/32930325/118209509-5097fa80-b49b-11eb-9b32-e0659523bf8e.png)

I am not malicious, just report some of the algorithm underperformance

**Comment by sgowroji** [comment]
Hi @aoxipo, We are improving our solutions in most of all the platforms. Can you test the above with the  latest release. Thanks!
