### ISSUE TITLE
Error compiling mediapipe-master examples with Android Studio on Windows 7

### ISSUE THREAD

**Issue by gitBitHubNet** [google/mediapipe#203]
I am trying to compile the mediapipe-master project with Android Studio 3.5.1 on Windows 7 SP1 64bit, but I am getting the error stated below.
I am using Bazel 0.29.1 version and followed all the installation steps regarding SDK, NDK versions needed.
It seems it lacks the Repository 'org_tensorflow', but is it because on Windows tar.gz cannot be handled, or is the file missing since if I copy-paste the link and also it returns an error saying there is no such file.

Any ideas what is missing in my installation?

_________________________________________
Syncing project: Sync (full)...
Updating VCS...
Running Bazel info...
Command: C:\bazel.exe info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --

INFO: Call stack for the definition of repository 'org_tensorflow' which is a http_archive (rule definition at C:/users/netronio/_bazel_netronio/ljt2zrv4/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - C:/users/netronio/desktop/mediapipe-master_1/mediapipe-master/WORKSPACE:110:1
INFO: Repository 'org_tensorflow' used the following cache hits instead of downloading the corresponding file.
 * Hash 'ddd4e3c056e7c0ff2ef29133b30fa62781dfbf8a903e99efb91a02d292fa9562' for https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz
If the definition of 'org_tensorflow' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   Traceback (most recent call last):
	File "C:/users/netronio/_bazel_netronio/ljt2zrv4/external/bazel_tools/tools/build_defs/repo/http.bzl", line 59
		patch(ctx)
	File "C:/users/netronio/_bazel_netronio/ljt2zrv4/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 100, in patch
		ctx.patch(patchfile, strip)
com.google.devtools.build.lib.syntax.EvalException: Error applying patch C:/users/netronio/desktop/mediapipe-master_1/mediapipe-master/third_party/tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("patch" -p1 -i C:/users/netronio/desktop/mediapipe-master_1/mediapipe-master/third_party/tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff): ??? ????? ?????? ? ?????? ??? ???????????? ??????? ??? ?? ???????.
 (error: 2)
ERROR: no such package '@org_tensorflow//tensorflow': Traceback (most recent call last):
	File "C:/users/netronio/_bazel_netronio/ljt2zrv4/external/bazel_tools/tools/build_defs/repo/http.bzl", line 59
		patch(ctx)
	File "C:/users/netronio/_bazel_netronio/ljt2zrv4/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 100, in patch
		ctx.patch(patchfile, strip)
com.google.devtools.build.lib.syntax.EvalException: Error applying patch C:/users/netronio/desktop/mediapipe-master_1/mediapipe-master/third_party/tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("patch" -p1 -i C:/users/netronio/desktop/mediapipe-master_1/mediapipe-master/third_party/tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff): ??? ????? ?????? ? ?????? ??? ???????????? ??????? ??? ?? ???????.
 (error: 2)
Sync finished
Sync failed

**Comment by jiuqiant** [comment]
Similar to https://github.com/google/mediapipe/issues/165, https://github.com/google/mediapipe/issues/137, https://github.com/google/mediapipe/issues/91, https://github.com/google/mediapipe/issues/113, and https://github.com/google/mediapipe/issues/126. Unfortunately, MediaPipe doesn't support Windows. If you are only interested in Windows, we support Windows Subsystem for Linux. You can find how to set up MediaPipe in WSL [here](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows-subsystem-for-linux-wsl).

**Comment by jiuqiant** [comment]
FYI, using MediaPipe in Android Studio with Bazel is deprecated. Please see the new gradle approach in https://github.com/google/mediapipe/blob/master/docs/getting_started/android_solutions.md.
