### ISSUE TITLE
Subset NormalizedLandmarkList from pose estimation (Python)

### ISSUE THREAD

**Issue by dstanner** [google/mediapipe#2031]
I want to draw only a subset of landmarks from a pose estimation run on an image.

In essence, I want to be able to subset a `NormalizedLandmarkList` to pass to `draw_landmarks`, but I am having difficulty figuring out how to subset the list object based either on landmark name or list index. When I try to call a list of indices on a `NormalizedLandmarkList` returned from a pose estimation run (e.g., `results.pose_landmarks[13, 14, 25, 26]`), I get `TypeError: 'NormalizedLandmarkList' object is not subscriptable`. I have tried other approaches based on `PoseLandmark` names, and they fail in other ways.

For example, in the stock image below, if I wanted to draw markers only for the two elbows and two knees (indices 13, 14, 25, 26), how could I amend the `NormalizedLandmarkList` to place markers at only those landmarks? 

![tracked](https://user-images.githubusercontent.com/34904658/118334987-80f38f00-b4c3-11eb-8602-139e24ed1733.JPG)

I found [this issue](https://github.com/google/mediapipe/issues/1020) which demonstrates how to return the coordinates for all landmarks as a list. One approach would be to extract the full list, then call the indices I want and draw them manually with cv2. But is there a direct way to subset the `NormalizedLandmarkList` to only the indices I want for drawing to pass to `draw_landmarks`?

**Comment by jiuqiant** [comment]
Sorry for the late reply. I don't have a good solution for this. Here is the ugly way I can think of to achieve this:

```
from mediapipe.framework.formats import landmark_pb2
landmark_subset = landmark_pb2.NormalizedLandmarkList(
      landmark = [
          results.pose_landmarks.landmark[13],
          results.pose_landmarks.landmark[14], 
          results.pose_landmarks.landmark[25],
          results.pose_landmarks.landmark[26], 
      ]
  )
  annotated_image = image.copy()
  mp_drawing.draw_landmarks(
      image=annotated_image,
      landmark_list=landmark_subset)
  cv2_imshow(annotated_image)
```

**Comment by jiuqiant** [comment]
Sorry for the late reply. I don't have a good solution for this. Here is the ugly way I can think of to achieve this:

```
from mediapipe.framework.formats import landmark_pb2
landmark_subset = landmark_pb2.NormalizedLandmarkList(
      landmark = [
          results.pose_landmarks.landmark[13],
          results.pose_landmarks.landmark[14], 
          results.pose_landmarks.landmark[25],
          results.pose_landmarks.landmark[26], 
      ]
)
annotated_image = image.copy()
mp_drawing.draw_landmarks(
    image=annotated_image,
    landmark_list=landmark_subset)
cv2_imshow(annotated_image)
```

**Comment by sgowroji** [comment]
Hi @dstanner, Did you get a chance to go through the above comment . Thanks !

**Comment by toz123** [comment]
Thank you, this is perfect!

**Comment by dstanner** [comment]
Sorry for the slow reply myself -- yes, this does work. Thank you!

**Comment by Ambroza888** [comment]
```
      try:
            landmarks = result.pose_landmarks.landmark
            print(landmarks)
            tog.isLeft = True
        except:
            pass
```

**Comment by SutirthaChakraborty** [comment]
face = np.array([[res.x, res.y, res.z] for res in face_landmarks.landmark]).flatten() if face_landmarks.landmark else np.zeros(468*3)

**Comment by 459zyt** [comment]
> 这么晚才回复很抱歉。我对此没有很好的解决方案。这是我能想到的实现这一目标的丑陋方式：
> 
> ```
> from mediapipe.framework.formats import landmark_pb2
> landmark_subset = landmark_pb2.NormalizedLandmarkList(
>       landmark = [
>           results.pose_landmarks.landmark[13],
>           results.pose_landmarks.landmark[14], 
>           results.pose_landmarks.landmark[25],
>           results.pose_landmarks.landmark[26], 
>       ]
> )
> annotated_image = image.copy()
> mp_drawing.draw_landmarks(
>     image=annotated_image,
>     landmark_list=landmark_subset)
> cv2_imshow(annotated_image)
> ```

How can I connect these points with wires

**Comment by 459zyt** [comment]
> 这么晚才回复很抱歉。我对此没有很好的解决方案。这是我能想到的实现这一目标的丑陋方式：
> 
> ```
> from mediapipe.framework.formats import landmark_pb2
> landmark_subset = landmark_pb2.NormalizedLandmarkList(
>       landmark = [
>           results.pose_landmarks.landmark[13],
>           results.pose_landmarks.landmark[14], 
>           results.pose_landmarks.landmark[25],
>           results.pose_landmarks.landmark[26], 
>       ]
> )
> annotated_image = image.copy()
> mp_drawing.draw_landmarks(
>     image=annotated_image,
>     landmark_list=landmark_subset)
> cv2_imshow(annotated_image)
> ```

How can I connect these points with wires,please?

**Comment by A7medAbdien** [comment]
@459zyt 

this the [MedeaPipe repository code](https://github.com/google/mediapipe/blob/340d7651af8caca795220b81124b2a3e557f4784/mediapipe/python/solutions/drawing_utils.py#L120) for `draw_landmarks` method

```py
if connections:
    num_landmarks = len(landmark_list.landmark)
    # Draws the connections if the start and end landmarks are both visible.
    for connection in connections:

        start_idx = connection[0]
        end_idx = connection[1]

        if not (0 <= start_idx < num_landmarks and 0 <= end_idx < num_landmarks):
            raise ValueError(f'Landmark index is out of range. Invalid connection '
                            f'from landmark #{start_idx} to landmark #{end_idx}.')

        if start_idx in idx_to_coordinates and end_idx in idx_to_coordinates:
            # I didn't try to deg in this line, but it seems to be used to get the global color and thickness
            drawing_spec = connection_drawing_spec[connection] if isinstance(connection_drawing_spec, Mapping) else connection_drawing_spec
            """
            idx_to_coordinates is list of landmark_px
            and let us say that landmark_px is kind of tubules of (landmark.x, landmark.y, image_cols, image_rows), so it has x and y
            then they used to draw the opencv line
            """
            # cv2.line(image, start_point, end_point, color, thickness)
            cv2.line(image, idx_to_coordinates[start_idx],idx_to_coordinates[end_idx], drawing_spec.color,drawing_spec.thickness)

```

so we can draw them manually using our landmark_subset

```py
# Adding drawable
landmark_subset = landmark_pb2.NormalizedLandmarkList(
    landmark=[
        # results.pose_landmarks.landmark[0],
        results.pose_landmarks.landmark[11],
        results.pose_landmarks.landmark[12],
        results.pose_landmarks.landmark[23],
        results.pose_landmarks.landmark[24],
    ]
)
# print(landmark_subset.landmark)
# print(landmark_subset)
mp_drawing.draw_landmarks(
    # frame, results.pose_landmarks, mp_pose.POSE_CONNECTIONS,)
    frame, landmark_list=landmark_subset)

poses = landmark_subset.landmark
for i in range(0, len(poses)-1, 2):
    start_idx = [
        poses[i].x,
        poses[i].y
    ]
    end_idx = [
        poses[i+1].x,
        poses[i+1].y
    ]
    IMG_HEIGHT, IMG_WIDTH = frame.shape[:2]
    # print(start_idx)


    cv2.line(frame,
                # here we change coordinates to fit to the camera feed
                tuple(np.multiply(start_idx[:2], [
                    IMG_WIDTH, IMG_HEIGHT]).astype(int)),
                tuple(np.multiply(end_idx[:2], [
                    IMG_WIDTH, IMG_HEIGHT]).astype(int)),
                (255, 0, 0), 9)
```
