### ISSUE TITLE
Unable to create shared library missing symbols

### ISSUE THREAD

**Issue by matthewn4444** [google/mediapipe#2032]
I am trying to create a shared_library with the following as an exported shared library for android as I prefer not to use any of the JNI and Java code and after compiling I get no symbols related to certain libraries like CalculatorGraph

```
cc_binary(
    name = "libmediapipe_framework.so",
    deps = [""//mediapipe/framework:calculator_framework",
        "//mediapipe/framework:calculator_graph",
        "//mediapipe/framework:calculator_profile_cc_proto",
        "//mediapipe/framework/tool:calculator_graph_template_cc_proto",
        "//mediapipe/framework/formats:image_format_cc_proto",
        "//mediapipe/framework/formats:matrix_data_cc_proto",
        "//mediapipe/framework/stream_handler:fixed_size_input_stream_handler",
        "//mediapipe/framework/tool:name_util",
        "//mediapipe/framework/tool:executor_util",
        "//mediapipe/framework/port:core_proto",
        "//mediapipe/framework/port:logging",
        "//mediapipe/framework/port:threadpool",
        "//mediapipe/framework/port:singleton",
        "//mediapipe/framework/port:status",

        "//mediapipe/framework/formats:classification_cc_proto",
        "//mediapipe/framework/formats:landmark_cc_proto",
        "//mediapipe/framework/formats:detection_cc_proto",
        "//mediapipe/framework/formats:rect_cc_proto",
                   "//mediapipe/graphs/hand_tracking:mobile_calculators",
                   "//mediapipe/graphs/object_detection:mobile_calculators"]
+ select({
        "//conditions:default": [
            "//mediapipe/gpu:gl_quad_renderer",
            "//mediapipe/gpu:gl_calculator_helper",
            "//mediapipe/gpu:gl_surface_sink_calculator",
            "//mediapipe/gpu:gpu_shared_data_internal",
            "//mediapipe/gpu:graph_support",
        ],
        "//mediapipe/gpu:disable_gpu": [
            "//mediapipe/gpu:gpu_shared_data_internal",
        ],
    }),
    linkshared = 1,
)
```

I am using the command 

`bazel build -c opt  --config=android_arm --cxxopt='-std=c++17'  mediapipe:libmediapipe_framework.so --linkopt="-s"`

I use the command 

`nm -D bazel-bin/mediapipe/native/android/libmediapipe_framework.so | grep WaitUntilDone`

And there is nothing. If i add a source file that uses CalculatorGraph then it would export the symbols. Is there some way I can include CalculatorGraph and other symbols into the shared library? I assume symbols like CalculatorGraph are being stripped out.

Also I am compiling on Macos using and using 0.8.3.1

**Comment by sgowroji** [comment]
Hi @matthewn4444, Could you please share your error logs and complete steps to reproduce the above issue. Thanks!

**Comment by matthewn4444** [comment]
You can close this, I realized my question was more for bazel, I have to use alwayslink=1 to each of the libraries I wanted to include into my shared library.
