### ISSUE TITLE
About shoe model switching

### ISSUE THREAD

**Issue by z7212819** [google/mediapipe#2034]
Hello, now I try shoes how software can click on the screen like face_effect change model, I found GlAnimationOverlayCalculator seems not support in the program direct switching model input stream, excuse me what method?

**Comment by z7212819** [comment]
I'm using the AAR package, in a Linux environment

**Comment by z7212819** [comment]
`package com.example.realtimefacemesh;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageManager;
import android.content.pm.PackageManager.NameNotFoundException;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.Bundle;
import android.util.Log;
import android.util.Size;
import android.view.GestureDetector;
import android.view.MotionEvent;
import android.view.SurfaceHolder;
import com.google.mediapipe.framework.AndroidAssetUtil;
import com.google.mediapipe.framework.AndroidPacketCreator;
import com.google.mediapipe.framework.Packet;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

/** Main activity of MediaPipe object detection 3D app. */
public class MainActivity extends BasicActivity {
    private static final String TAG = "MainActivity";



    private final Object effectSelectionLock = new Object();
    private int selectedEffectId;
    private static final String SELECTED_EFFECT_ID_INPUT_STREAM_NAME = "selected_effect_id";
    private GestureDetector tapGestureDetector;
    private static final int SELECTED_EFFECT_ID_AXIS = 0;
    private static final int SELECTED_EFFECT_ID_FACEPAINT = 1;
    private static final int SELECTED_EFFECT_ID_GLASSES = 2;

    String OBJ_TEXTURE = "texture2.jpg";
    String OBJ_FILE = "shoe2.uuu";
    String BOX_TEXTURE = "classic_colors.png";
    String BOX_FILE = "box.obj.uuu";
    String NEW_TEXTURE = "texture2.jpg";
    String NEW_FILE = "shoe2.uuu";

    // Assets.
    private Bitmap objTexture = null;
    private Bitmap boxTexture = null;
    private Bitmap newTexture = null;

    // ApplicationInfo for retrieving metadata defined in the manifest.
    private ApplicationInfo applicationInfo;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        selectedEffectId = SELECTED_EFFECT_ID_GLASSES;
        try {
            applicationInfo =
                    getPackageManager().getApplicationInfo(getPackageName(), PackageManager.GET_META_DATA);
        } catch (NameNotFoundException e) {
            Log.e(TAG, "Cannot find application info: " + e);
        }
        // Get allowed object category.
        String categoryName = applicationInfo.metaData.getString("categoryName");
        // Get maximum allowed number of objects.
        int maxNumObjects = applicationInfo.metaData.getInt("maxNumObjects");
        float[] modelScale = parseFloatArrayFromString(
                applicationInfo.metaData.getString("modelScale"));
        float[] modelTransform = parseFloatArrayFromString(
                applicationInfo.metaData.getString("modelTransformation"));
        prepareDemoAssets(OBJ_TEXTURE,BOX_TEXTURE,NEW_TEXTURE);
        AndroidPacketCreator packetCreator = processor.getPacketCreator();
        Map<String, Packet> inputSidePackets = new HashMap<>();
        inputSidePackets.put("obj_asset_name", packetCreator.createString(OBJ_FILE));
        inputSidePackets.put("box_asset_name", packetCreator.createString(BOX_FILE));
        inputSidePackets.put("new_asset_name", packetCreator.createString(NEW_FILE));
        inputSidePackets.put("obj_texture", packetCreator.createRgbaImageFrame(objTexture));
        inputSidePackets.put("new_texture", packetCreator.createRgbaImageFrame(newTexture));
        inputSidePackets.put("box_texture", packetCreator.createRgbaImageFrame(boxTexture));
        inputSidePackets.put("allowed_labels", packetCreator.createString(categoryName));
        inputSidePackets.put("max_num_objects", packetCreator.createInt32(maxNumObjects));
        inputSidePackets.put("model_scale", packetCreator.createFloat32Array(modelScale));
        inputSidePackets.put("model_transformation", packetCreator.createFloat32Array(modelTransform));
        processor.setInputSidePackets(inputSidePackets);
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        return tapGestureDetector.onTouchEvent(event);
    }

    @Override
    protected Size cameraTargetResolution() {
        return new Size(1280, 960); // Prefer 4:3 aspect ratio (camera size is in landscape).
    }

    @Override
    protected Size computeViewSize(int width, int height) {
        return new Size(height, height * 3 / 4); // Prefer 3:4 aspect ratio.
    }

    @Override
    protected void onPreviewDisplaySurfaceChanged(
            SurfaceHolder holder, int format, int width, int height) {
        super.onPreviewDisplaySurfaceChanged(holder, format, width, height);
        boolean isCameraRotated = cameraHelper.isCameraRotated();
        Size cameraImageSize = cameraHelper.getFrameSize();
        processor.setOnWillAddFrameListener(
                (timestamp) -> {
                    Packet selectedEffectIdPacket = null;
                    try {
                        int cameraTextureWidth =
                                isCameraRotated ? cameraImageSize.getHeight() : cameraImageSize.getWidth();
                        int cameraTextureHeight =
                                isCameraRotated ? cameraImageSize.getWidth() : cameraImageSize.getHeight();

                        // Find limiting side and scale to 3:4 aspect ratio
                        float aspectRatio = (float) cameraTextureWidth / (float) cameraTextureHeight;
                        if (aspectRatio > 3.0 / 4.0) {
                            // width too big
                            cameraTextureWidth = (int) ((float) cameraTextureHeight * 3.0 / 4.0);
                        } else {
                            // height too big
                            cameraTextureHeight = (int) ((float) cameraTextureWidth * 4.0 / 3.0);
                        }
                        Packet widthPacket = processor.getPacketCreator().createInt32(cameraTextureWidth);
                        Packet heightPacket = processor.getPacketCreator().createInt32(cameraTextureHeight);
                        synchronized (effectSelectionLock) {
                            selectedEffectIdPacket = processor.getPacketCreator().createInt32(selectedEffectId);
                        }

                        try {
                            processor.getGraph().addPacketToInputStream("input_width", widthPacket, timestamp);
                            processor.getGraph().addPacketToInputStream("input_height", heightPacket, timestamp);
                        } catch (RuntimeException e) {
                            Log.e(
                                    TAG,
                                    "MediaPipeException encountered adding packets to input_width and input_height"
                                            + " input streams.", e);
                        }
                        /*finally {
                            if (selectedEffectIdPacket != null) {
                                selectedEffectIdPacket.release();
                            }
                        }*/
                        widthPacket.release();
                        heightPacket.release();
                    } catch (IllegalStateException ise) {
                        Log.e(TAG, "Exception while adding packets to width and height input streams.");
                    }
                    tapGestureDetector =
                            new GestureDetector(
                                    this,
                                    new GestureDetector.SimpleOnGestureListener() {
                                        @Override
                                        public void onLongPress(MotionEvent event) {
                                            switchEffect();
                                        }

                                        @Override
                                        public boolean onSingleTapUp(MotionEvent event) {
                                            switchEffect();
                                            return true;
                                        }

                                        private void switchEffect() {
                                            // Looped effect order: glasses -> facepaint -> axis -> glasses -> ...
                                            synchronized (effectSelectionLock) {
                                                switch (selectedEffectId) {
                                                    case SELECTED_EFFECT_ID_AXIS:
                                                    {
                                                        selectedEffectId = SELECTED_EFFECT_ID_GLASSES;
                                                        Log.d(TAG, "1 " );
                                                        break;
                                                    }

                                                    case SELECTED_EFFECT_ID_FACEPAINT:
                                                    {
                                                        selectedEffectId = SELECTED_EFFECT_ID_AXIS;
                                                        Log.d(TAG, "2 " );
                                                        break;
                                                    }

                                                    case SELECTED_EFFECT_ID_GLASSES:
                                                    {
                                                        selectedEffectId = SELECTED_EFFECT_ID_FACEPAINT;
                                                        Log.d(TAG, "3 " );
                                                        break;
                                                    }

                                                    default:
                                                        break;
                                                }
                                            }
                                        }
                                    });

                });


    }

    private void prepareDemoAssets(String OBJ_TEXTURE,String BOX_TEXTURE,String NEW_TEXTURE) {
        AndroidAssetUtil.initializeNativeAssetManager(this);
        // We render from raw data with openGL, so disable decoding preprocessing
        BitmapFactory.Options decodeOptions = new BitmapFactory.Options();
        decodeOptions.inScaled = false;
        decodeOptions.inDither = false;
        decodeOptions.inPremultiplied = false;

        try {
            InputStream inputStream = getAssets().open(OBJ_TEXTURE);
            objTexture = BitmapFactory.decodeStream(inputStream, null /*outPadding*/, decodeOptions);
            inputStream.close();
        } catch (Exception e) {
            Log.e(TAG, "Error parsing object texture; error: " + e);
            throw new IllegalStateException(e);
        }

        try {
            InputStream inputStream = getAssets().open(NEW_TEXTURE);
            newTexture = BitmapFactory.decodeStream(inputStream, null /*outPadding*/, decodeOptions);
            inputStream.close();
        } catch (Exception e) {
            Log.e(TAG, "Error parsing object texture; error: " + e);
            throw new IllegalStateException(e);
        }

        try {
            InputStream inputStream = getAssets().open(BOX_TEXTURE);
            boxTexture = BitmapFactory.decodeStream(inputStream, null /*outPadding*/, decodeOptions);
            inputStream.close();
        } catch (Exception e) {
            Log.e(TAG, "Error parsing box texture; error: " + e);
            throw new RuntimeException(e);
        }
    }

    private static float[] parseFloatArrayFromString(String string) {
        String[] elements = string.split(",", -1);
        float[] array = new float[elements.length];
        for (int i = 0; i < elements.length; ++i) {
            array[i] = Float.parseFloat(elements[i]);
        }
        return array;
    }
}`
目前已经将SwitchContainer计算器进行了添加，一下是我的图表
`# MediaPipe graph that performs box tracking with TensorFlow Lite on GPU.

# Images coming into and out of the graph.
input_stream: "input_video"
input_stream: "WIDTH:input_width"
input_stream: "HEIGHT:input_height"
input_stream: "selected_effect_id"
input_side_packet: "LABELS_CSV:allowed_labels"
input_side_packet: "MODEL_SCALE:model_scale"
input_side_packet: "MODEL_TRANSFORMATION:model_transformation"
input_side_packet: "TEXTURE:box_texture"
input_side_packet: "MAX_NUM_OBJECTS:max_num_objects"
input_side_packet: "ANIMATION_ASSET:box_asset_name"
input_side_packet: "MASK_TEXTURE:obj_texture"
input_side_packet: "MASK_ASSET:obj_asset_name"
input_side_packet: "NEW_TEXTURE:new_texture"
input_side_packet: "NEW_ANIMATION_ASSET:new_asset_name"
output_stream: "output_video"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Crops the image from the center to the size WIDTHxHEIGHT.
node: {
  calculator: "ImageCroppingCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "IMAGE_GPU:throttled_input_video_3x4"
  input_stream: "WIDTH:input_width"
  input_stream: "HEIGHT:input_height"
  node_options: {
    [type.googleapis.com/mediapipe.ImageCroppingCalculatorOptions] {
      border_mode: BORDER_REPLICATE
    }
  }
}

node {
  calculator: "ObjectronGpuSubgraph"
  input_stream: "IMAGE_GPU:throttled_input_video_3x4"
  input_side_packet: "LABELS_CSV:allowed_labels"
  input_side_packet: "MAX_NUM_OBJECTS:max_num_objects"
  output_stream: "FRAME_ANNOTATION:lifted_objects"
}

# The rendering nodes:
# We are rendering two meshes: 1) a 3D bounding box, which we overlay directly
# on the texture, and 2) a virtual object, which we use as an occlusion mask.
# These models are designed using different tools, so we supply a transformation
# to bring both of them to the Objectron's coordinate system.

# Creates a model matrices for the tracked object given the lifted 3D points.
# This calculator does two things: 1) Estimates object's pose (orientation,
# translation, and scale) from the 3D vertices, and
# 2) bring the object from the objectron's coordinate system to the renderer
# (OpenGL) coordinate system. Since the final goal is to render a mesh file on
# top of the object, we also supply a transformation to bring the mesh to the
# objectron's coordinate system, and rescale mesh to the unit size.

node {
  calculator: "AnnotationsToModelMatricesCalculator"
  input_stream: "ANNOTATIONS:lifted_objects"
  output_stream: "MODEL_MATRICES:model_matrices"
  node_options: {
    [type.googleapis.com/mediapipe.AnnotationsToModelMatricesCalculatorOptions] {
      # Re-scale the CAD model to the size of a unit box
      model_scale: [0.45, 0.55, 0.15]
      # Bring the box CAD model to objectron's coordinate system. This
      # is equivalent of -pi/2 rotation along the y-axis (right-hand rule):
      # Eigen::AngleAxisf(-M_PI / 2., Eigen::Vector3f::UnitY())
      model_transformation: [1.0,  0.0,  0.0,  0.0]
      model_transformation: [0.0,  0.0,  1.0,  -0.9]
      model_transformation: [0.0,  -1.0,  0.0,  0.0]
      model_transformation: [0.0,  0.0,  0.0,  1.0]
    }
  }
}


# Compute the model matrices for the CAD model of the virtual object, to be used
# as an occlusion mask. The model will be rendered at the exact same location as
# the bounding box.
node {
  calculator: "AnnotationsToModelMatricesCalculator"
  input_stream: "ANNOTATIONS:lifted_objects"
  output_stream: "MODEL_MATRICES:mask_model_matrices"
  node_options: {
    [type.googleapis.com/mediapipe.AnnotationsToModelMatricesCalculatorOptions] {
      # Re-scale the CAD model to the size of a unit box
      model_scale: [0.45, 0.55, 0.15]
      # Bring the box CAD model to objectron's coordinate system. This
      # is equivalent of -pi/2 rotation along the y-axis (right-hand rule):
      # Eigen::AngleAxisf(-M_PI / 2., Eigen::Vector3f::UnitY())
      model_transformation: [1.0,  0.0,  0.0,  0.0]
      model_transformation: [0.0,  0.0,  1.0,  -0.9]
      model_transformation: [0.0,  -1.0,  0.0,  0.0]
      model_transformation: [0.0,  0.0,  0.0,  1.0]
    }
  }
}

# Renders the selected effect based on `selected_effect_id`.
node {
  calculator: "SwitchContainer"
  input_stream: "VIDEO:throttled_input_video_3x4"
  input_stream: "MODEL_MATRICES:model_matrices"
  input_stream: "MASK_MODEL_MATRICES:mask_model_matrices"
  input_side_packet: "TEXTURE:obj_texture"
  input_side_packet: "ANIMATION_ASSET:obj_asset_name"
  input_side_packet: "MASK_TEXTURE:box_texture"
  input_side_packet: "MASK_ASSET:box_asset_name"
  output_stream: "output_video"
  node_options: {
    [type.googleapis.com/mediapipe.SwitchContainerOptions] {
      contained_node: {
        calculator: "GlAnimationOverlayCalculator"
  	node_options: {
   	 [type.googleapis.com/mediapipe.GlAnimationOverlayCalculatorOptions] {
            aspect_ratio: 0.75
            vertical_fov_degrees: 70.
            animation_speed_fps: 25
   	  }
        }
      }
      contained_node: {
        calculator: "GlAnimationOverlayCalculator"
  	node_options: {
   	 [type.googleapis.com/mediapipe.GlAnimationOverlayCalculatorOptions] {
            aspect_ratio: 0.75
            vertical_fov_degrees: 70.
            animation_speed_fps: 25
   	  }
        }
      }
      contained_node: {
       calculator: "GlAnimationOverlayCalculator"
  	node_options: {
   	 [type.googleapis.com/mediapipe.GlAnimationOverlayCalculatorOptions] {
            aspect_ratio: 0.75
            vertical_fov_degrees: 70.
            animation_speed_fps: 25
   	  }
        }
      }
    }
  }
}`

**Comment by z7212819** [comment]
The switchcontainer calculator has been added now, and here is my code
`/** Main activity of MediaPipe object detection 3D app. */
public class MainActivity extends BasicActivity {
    private static final String TAG = "MainActivity";



    private final Object effectSelectionLock = new Object();
    private int selectedEffectId;
    private static final String SELECTED_EFFECT_ID_INPUT_STREAM_NAME = "selected_effect_id";
    private GestureDetector tapGestureDetector;
    private static final int SELECTED_EFFECT_ID_AXIS = 0;
    private static final int SELECTED_EFFECT_ID_FACEPAINT = 1;
    private static final int SELECTED_EFFECT_ID_GLASSES = 2;

    String OBJ_TEXTURE = "texture2.jpg";
    String OBJ_FILE = "shoe2.uuu";
    String BOX_TEXTURE = "classic_colors.png";
    String BOX_FILE = "box.obj.uuu";
    String NEW_TEXTURE = "texture2.jpg";
    String NEW_FILE = "shoe2.uuu";

    // Assets.
    private Bitmap objTexture = null;
    private Bitmap boxTexture = null;
    private Bitmap newTexture = null;

    // ApplicationInfo for retrieving metadata defined in the manifest.
    private ApplicationInfo applicationInfo;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        selectedEffectId = SELECTED_EFFECT_ID_GLASSES;
        try {
            applicationInfo =
                    getPackageManager().getApplicationInfo(getPackageName(), PackageManager.GET_META_DATA);
        } catch (NameNotFoundException e) {
            Log.e(TAG, "Cannot find application info: " + e);
        }
        // Get allowed object category.
        String categoryName = applicationInfo.metaData.getString("categoryName");
        // Get maximum allowed number of objects.
        int maxNumObjects = applicationInfo.metaData.getInt("maxNumObjects");
        float[] modelScale = parseFloatArrayFromString(
                applicationInfo.metaData.getString("modelScale"));
        float[] modelTransform = parseFloatArrayFromString(
                applicationInfo.metaData.getString("modelTransformation"));
        prepareDemoAssets(OBJ_TEXTURE,BOX_TEXTURE,NEW_TEXTURE);
        AndroidPacketCreator packetCreator = processor.getPacketCreator();
        Map<String, Packet> inputSidePackets = new HashMap<>();
        inputSidePackets.put("obj_asset_name", packetCreator.createString(OBJ_FILE));
        inputSidePackets.put("box_asset_name", packetCreator.createString(BOX_FILE));
        inputSidePackets.put("new_asset_name", packetCreator.createString(NEW_FILE));
        inputSidePackets.put("obj_texture", packetCreator.createRgbaImageFrame(objTexture));
        inputSidePackets.put("new_texture", packetCreator.createRgbaImageFrame(newTexture));
        inputSidePackets.put("box_texture", packetCreator.createRgbaImageFrame(boxTexture));
        inputSidePackets.put("allowed_labels", packetCreator.createString(categoryName));
        inputSidePackets.put("max_num_objects", packetCreator.createInt32(maxNumObjects));
        inputSidePackets.put("model_scale", packetCreator.createFloat32Array(modelScale));
        inputSidePackets.put("model_transformation", packetCreator.createFloat32Array(modelTransform));
        processor.setInputSidePackets(inputSidePackets);
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        return tapGestureDetector.onTouchEvent(event);
    }

    @Override
    protected Size cameraTargetResolution() {
        return new Size(1280, 960); // Prefer 4:3 aspect ratio (camera size is in landscape).
    }

    @Override
    protected Size computeViewSize(int width, int height) {
        return new Size(height, height * 3 / 4); // Prefer 3:4 aspect ratio.
    }

    @Override
    protected void onPreviewDisplaySurfaceChanged(
            SurfaceHolder holder, int format, int width, int height) {
        super.onPreviewDisplaySurfaceChanged(holder, format, width, height);
        boolean isCameraRotated = cameraHelper.isCameraRotated();
        Size cameraImageSize = cameraHelper.getFrameSize();
        processor.setOnWillAddFrameListener(
                (timestamp) -> {
                    Packet selectedEffectIdPacket = null;
                    try {
                        int cameraTextureWidth =
                                isCameraRotated ? cameraImageSize.getHeight() : cameraImageSize.getWidth();
                        int cameraTextureHeight =
                                isCameraRotated ? cameraImageSize.getWidth() : cameraImageSize.getHeight();

                        // Find limiting side and scale to 3:4 aspect ratio
                        float aspectRatio = (float) cameraTextureWidth / (float) cameraTextureHeight;
                        if (aspectRatio > 3.0 / 4.0) {
                            // width too big
                            cameraTextureWidth = (int) ((float) cameraTextureHeight * 3.0 / 4.0);
                        } else {
                            // height too big
                            cameraTextureHeight = (int) ((float) cameraTextureWidth * 4.0 / 3.0);
                        }
                        Packet widthPacket = processor.getPacketCreator().createInt32(cameraTextureWidth);
                        Packet heightPacket = processor.getPacketCreator().createInt32(cameraTextureHeight);
                        synchronized (effectSelectionLock) {
                            selectedEffectIdPacket = processor.getPacketCreator().createInt32(selectedEffectId);
                        }

                        try {
                            processor.getGraph().addPacketToInputStream("input_width", widthPacket, timestamp);
                            processor.getGraph().addPacketToInputStream("input_height", heightPacket, timestamp);
                        } catch (RuntimeException e) {
                            Log.e(
                                    TAG,
                                    "MediaPipeException encountered adding packets to input_width and input_height"
                                            + " input streams.", e);
                        }
                        /*finally {
                            if (selectedEffectIdPacket != null) {
                                selectedEffectIdPacket.release();
                            }
                        }*/
                        widthPacket.release();
                        heightPacket.release();
                    } catch (IllegalStateException ise) {
                        Log.e(TAG, "Exception while adding packets to width and height input streams.");
                    }
                    tapGestureDetector =
                            new GestureDetector(
                                    this,
                                    new GestureDetector.SimpleOnGestureListener() {
                                        @Override
                                        public void onLongPress(MotionEvent event) {
                                            switchEffect();
                                        }

                                        @Override
                                        public boolean onSingleTapUp(MotionEvent event) {
                                            switchEffect();
                                            return true;
                                        }

                                        private void switchEffect() {
                                            // Looped effect order: glasses -> facepaint -> axis -> glasses -> ...
                                            synchronized (effectSelectionLock) {
                                                switch (selectedEffectId) {
                                                    case SELECTED_EFFECT_ID_AXIS:
                                                    {
                                                        selectedEffectId = SELECTED_EFFECT_ID_GLASSES;
                                                        Log.d(TAG, "1 " );
                                                        break;
                                                    }

                                                    case SELECTED_EFFECT_ID_FACEPAINT:
                                                    {
                                                        selectedEffectId = SELECTED_EFFECT_ID_AXIS;
                                                        Log.d(TAG, "2 " );
                                                        break;
                                                    }

                                                    case SELECTED_EFFECT_ID_GLASSES:
                                                    {
                                                        selectedEffectId = SELECTED_EFFECT_ID_FACEPAINT;
                                                        Log.d(TAG, "3 " );
                                                        break;
                                                    }

                                                    default:
                                                        break;
                                                }
                                            }
                                        }
                                    });

                });


    }

    private void prepareDemoAssets(String OBJ_TEXTURE,String BOX_TEXTURE,String NEW_TEXTURE) {
        AndroidAssetUtil.initializeNativeAssetManager(this);
        // We render from raw data with openGL, so disable decoding preprocessing
        BitmapFactory.Options decodeOptions = new BitmapFactory.Options();
        decodeOptions.inScaled = false;
        decodeOptions.inDither = false;
        decodeOptions.inPremultiplied = false;

        try {
            InputStream inputStream = getAssets().open(OBJ_TEXTURE);
            objTexture = BitmapFactory.decodeStream(inputStream, null /*outPadding*/, decodeOptions);
            inputStream.close();
        } catch (Exception e) {
            Log.e(TAG, "Error parsing object texture; error: " + e);
            throw new IllegalStateException(e);
        }

        try {
            InputStream inputStream = getAssets().open(NEW_TEXTURE);
            newTexture = BitmapFactory.decodeStream(inputStream, null /*outPadding*/, decodeOptions);
            inputStream.close();
        } catch (Exception e) {
            Log.e(TAG, "Error parsing object texture; error: " + e);
            throw new IllegalStateException(e);
        }

        try {
            InputStream inputStream = getAssets().open(BOX_TEXTURE);
            boxTexture = BitmapFactory.decodeStream(inputStream, null /*outPadding*/, decodeOptions);
            inputStream.close();
        } catch (Exception e) {
            Log.e(TAG, "Error parsing box texture; error: " + e);
            throw new RuntimeException(e);
        }
    }

    private static float[] parseFloatArrayFromString(String string) {
        String[] elements = string.split(",", -1);
        float[] array = new float[elements.length];
        for (int i = 0; i < elements.length; ++i) {
            array[i] = Float.parseFloat(elements[i]);
        }
        return array;
    }
}`

**Comment by z7212819** [comment]
Here is my pbtxt

# Images coming into and out of the graph.
input_stream: "input_video"
input_stream: "WIDTH:input_width"
input_stream: "HEIGHT:input_height"
input_stream: "selected_effect_id"
input_side_packet: "LABELS_CSV:allowed_labels"
input_side_packet: "MODEL_SCALE:model_scale"
input_side_packet: "MODEL_TRANSFORMATION:model_transformation"
input_side_packet: "TEXTURE:box_texture"
input_side_packet: "MAX_NUM_OBJECTS:max_num_objects"
input_side_packet: "ANIMATION_ASSET:box_asset_name"
input_side_packet: "MASK_TEXTURE:obj_texture"
input_side_packet: "MASK_ASSET:obj_asset_name"
input_side_packet: "NEW_TEXTURE:new_texture"
input_side_packet: "NEW_ANIMATION_ASSET:new_asset_name"
output_stream: "output_video"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Crops the image from the center to the size WIDTHxHEIGHT.
node: {
  calculator: "ImageCroppingCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "IMAGE_GPU:throttled_input_video_3x4"
  input_stream: "WIDTH:input_width"
  input_stream: "HEIGHT:input_height"
  node_options: {
    [type.googleapis.com/mediapipe.ImageCroppingCalculatorOptions] {
      border_mode: BORDER_REPLICATE
    }
  }
}

node {
  calculator: "ObjectronGpuSubgraph"
  input_stream: "IMAGE_GPU:throttled_input_video_3x4"
  input_side_packet: "LABELS_CSV:allowed_labels"
  input_side_packet: "MAX_NUM_OBJECTS:max_num_objects"
  output_stream: "FRAME_ANNOTATION:lifted_objects"
}


node {
  calculator: "AnnotationsToModelMatricesCalculator"
  input_stream: "ANNOTATIONS:lifted_objects"
  output_stream: "MODEL_MATRICES:model_matrices"
  node_options: {
    [type.googleapis.com/mediapipe.AnnotationsToModelMatricesCalculatorOptions] {
      # Re-scale the CAD model to the size of a unit box
      model_scale: [0.45, 0.55, 0.15]
      # Bring the box CAD model to objectron's coordinate system. This
      # is equivalent of -pi/2 rotation along the y-axis (right-hand rule):
      # Eigen::AngleAxisf(-M_PI / 2., Eigen::Vector3f::UnitY())
      model_transformation: [1.0,  0.0,  0.0,  0.0]
      model_transformation: [0.0,  0.0,  1.0,  -0.9]
      model_transformation: [0.0,  -1.0,  0.0,  0.0]
      model_transformation: [0.0,  0.0,  0.0,  1.0]
    }
  }
}

node {
  calculator: "AnnotationsToModelMatricesCalculator"
  input_stream: "ANNOTATIONS:lifted_objects"
  output_stream: "MODEL_MATRICES:mask_model_matrices"
  node_options: {
    [type.googleapis.com/mediapipe.AnnotationsToModelMatricesCalculatorOptions] {
      # Re-scale the CAD model to the size of a unit box
      model_scale: [0.45, 0.55, 0.15]
      # Bring the box CAD model to objectron's coordinate system. This
      # is equivalent of -pi/2 rotation along the y-axis (right-hand rule):
      # Eigen::AngleAxisf(-M_PI / 2., Eigen::Vector3f::UnitY())
      model_transformation: [1.0,  0.0,  0.0,  0.0]
      model_transformation: [0.0,  0.0,  1.0,  -0.9]
      model_transformation: [0.0,  -1.0,  0.0,  0.0]
      model_transformation: [0.0,  0.0,  0.0,  1.0]
    }
  }
}

# Renders the selected effect based on `selected_effect_id`.
node {
  calculator: "SwitchContainer"
  input_stream: "VIDEO:throttled_input_video_3x4"
  input_stream: "MODEL_MATRICES:model_matrices"
  input_stream: "MASK_MODEL_MATRICES:mask_model_matrices"
  input_side_packet: "TEXTURE:obj_texture"
  input_side_packet: "ANIMATION_ASSET:obj_asset_name"
  input_side_packet: "MASK_TEXTURE:box_texture"
  input_side_packet: "MASK_ASSET:box_asset_name"
  output_stream: "output_video"
  node_options: {
    [type.googleapis.com/mediapipe.SwitchContainerOptions] {
      contained_node: {
        calculator: "GlAnimationOverlayCalculator"
  	node_options: {
   	 [type.googleapis.com/mediapipe.GlAnimationOverlayCalculatorOptions] {
            aspect_ratio: 0.75
            vertical_fov_degrees: 70.
            animation_speed_fps: 25
   	  }
        }
      }
      contained_node: {
        calculator: "GlAnimationOverlayCalculator"
  	node_options: {
   	 [type.googleapis.com/mediapipe.GlAnimationOverlayCalculatorOptions] {
            aspect_ratio: 0.75
            vertical_fov_degrees: 70.
            animation_speed_fps: 25
   	  }
        }
      }
      contained_node: {
       calculator: "GlAnimationOverlayCalculator"
  	node_options: {
   	 [type.googleapis.com/mediapipe.GlAnimationOverlayCalculatorOptions] {
            aspect_ratio: 0.75
            vertical_fov_degrees: 70.
            animation_speed_fps: 25
   	  }
        }
      }
    }
  }
}

**Comment by sgowroji** [comment]
Hi @z7212819, Thanks for sharing the above input. Could you please share your error. And steps to reproduce the above error. Thanks!

**Comment by sgowroji** [comment]
Hi @z7212819, Please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.

**Comment by UX3D-mazzini** [comment]
@z7212819  Would you like to explain me better what you did? I can share my email
