### ISSUE TITLE
Tracking freezes when using AnnotationOverlayCalculator without input image

### ISSUE THREAD

**Issue by feldim2425** [google/mediapipe#2035]
I'm tried to modify the face mesh example to render without the input image similar to issue #326 

In order to do that I modified the ``face_renderer_cpu.pbtxt`` an made the following modifications to the AnnotationOverlayCalculator: (removed input_image and added canvas size option)
```
node {
  calculator: "AnnotationOverlayCalculator"
 # input_stream: "IMAGE:input_image"
  input_stream: "detections_render_data"
  input_stream: "VECTOR:multi_face_landmarks_render_data"
  input_stream: "rects_render_data"
  output_stream: "IMAGE:output_image"
  node_options: {
    [type.googleapis.com/mediapipe.AnnotationOverlayCalculatorOptions] {
      canvas_width_px: 1600
      canvas_height_px: 1200
    }
  }
}
```
Entire changes can be viewed here:
https://gist.github.com/feldim2425/6b18846a1e64b26ca5e0a1e14df7ccf3
And the entire code can be found here: https://github.com/feldim2425/MediapipeTesting

The issue is that as soon as I look away from the camera (model loses tracking) the entire graph freezes (stream output poller neither fails nor returns any packages it just blocks forever) and won't unfreeze until I restart it, even if I look back into the camera.

If I add the input_image back everything works fine and tracking is resumed as soon as a face is detected again. 

The original issue was closed due to inactivity, however the last comment by @MaRauder111 ``The windows didn't pop up it got stuck`` suggests a similar issue.

**Comment by feldim2425** [comment]
PS:
The ``/mediapipe/modules/face_landmark/face_landmark_cpu.pbtxt`` file contains a comment saying:
```
# NOTE: if a face is not present within the given ROI, for this particular
# timestamp there will not be an output packet in the LANDMARKS stream. However,
# the MediaPipe framework will internally inform the downstream calculators of
# the absence of this packet so that they don't wait for it unnecessarily.
```

I don't know exactly how that information is passed downstream, however to me it seems like either the input_image takes a role in passing that information down or the AnnotationOverlayCalculator always required some kind of input and ignores that information.

**Comment by txf-** [comment]
Take a look at this #850 . The issue isn't the annotationoverlaycalculator. Rather as you correctly identified the poller blocks the complete execution of the program and graph without a packet.

If  you poll for the presence of a packet (using the packetpresencecalculator) then the loop can continue executing when packets are missing.

**Comment by sureshdagooglecom** [comment]
Hi @feldim2425 ,
Are you still looking for the resolution on this issue.
