### ISSUE TITLE
C++  API  solution?

### ISSUE THREAD

**Issue by lyfpeter** [google/mediapipe#2036]

**Comment by rmothukuru** [comment]
@lyfpeter,
Can you please elaborate about your point? Thanks!

**Comment by aoxipo** [comment]
try this.  examples/desktop demo , .

**Comment by lyfpeter** [comment]
> Can you please elaborate about your point? Thanks!

Only compile c + + code, encapsulate .so library

**Comment by sgowroji** [comment]
Hi @lyfpeter, Could you please elaborate your issue with complete details. Thanks!

**Comment by sgowroji** [comment]
Hi @lyfpeter, Can you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.
