### ISSUE TITLE
Can I recolor hair segmentation mask using LUTs ?

### ISSUE THREAD

**Issue by akokhlik** [google/mediapipe#2038]
Hi,can I recolor hair segmentation mask using LUTs as shown in this paper ?
https://arxiv.org/pdf/1907.06740.pdf

**Comment by aoxipo** [comment]
hello , may be you can try this:
change mediapipe/graphs/hair_segmentation/hair_segmentation_desktop_live.pbtxt in line:147
change the `color{ r:0 g:0 b:255 }`

**Comment by sgowroji** [comment]
Have a look at this reference https://github.com/google/mediapipe/issues/689

**Comment by sgowroji** [comment]
Hi @akokhlik, Did you get a chance to go through my above comment. Thanks!

**Comment by akokhlik** [comment]
Hi @sgowroji , thanks for reply. I cant do linear interpolation.

**Comment by mcclanahoochie** [comment]
As mentioned in https://github.com/google/mediapipe/issues/689#issuecomment-626835683 the recolor_calculator doesn't use a LUT, and instead uses a single color varied by image intensity.

The standard way to use re-color LUTs is via [HaldCLUT](http://www.quelsolaar.com/technology/clut.html), which the paper uses also. 

The best advice is to research HaldCLUT indexing and implement in the recolor_calculator.cc

**Comment by akokhlik** [comment]
Thanks @mcclanahoochie
