### ISSUE TITLE
dlopen failed: cannot locate symbol "aligned_alloc"

### ISSUE THREAD

**Issue by Asssssert** [google/mediapipe#2042]
![image](https://user-images.githubusercontent.com/20775530/118583900-69205180-b7c8-11eb-829f-8a3de10f81f7.png)
Why can I run on Android 10 and 9 and report an exception on 7.1.1? Is it an Android version problem？

**Comment by sgowroji** [comment]
Hi @Asssssert, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by Asssssert** [comment]
I refered to your official [documentation ](https://google.github.io/mediapipe/getting_started/android_archive_library.html)for step-by-step production, gesture recognition and pose recognition both have the same error. I downloaded the SDK as setup_android_sdk_and_ndk.sh script. I looked at my local SDK and saw that the platforms version was 29, I changed it to 25 and recompiled but the system reported other errors. My current development environment is：
ubuntu 20.04 for windows
python 3.8
bazel 3.7.2
I found a few [examples ](https://github.com/LeeJeongHwi/Mediapipe_pose_Tracking_AAR_example)of errors running on version 7.1 for some users.

**Comment by Asssssert** [comment]
Hi @jiuqiant I download your [example ](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example)and reported the same error on android version 7.1.1

**Comment by jiuqiant** [comment]
https://en.cppreference.com/w/cpp/memory/c/aligned_alloc is introduced in C++17. I guess Android 7 (released in 2016) is a little bit old?

**Comment by sgowroji** [comment]
Hi @Asssssert, Take a look at the above [comment](https://github.com/google/mediapipe/issues/2042#issuecomment-847194436)

**Comment by Asssssert** [comment]
Thanks, as I have a couple of demos that work on Android 7.1, I was wondering why there was a problem, so have you considered adapting to Android 7, which I feel is used by quite a lot of people.

**Comment by sgowroji** [comment]
We have Prerequisite [documentation](https://google.github.io/mediapipe/getting_started/android#prerequisite).

**Comment by sgowroji** [comment]
Hi Asssssert, Could you please respond to my above [comment](https://github.com/google/mediapipe/issues/2042#issuecomment-849348762). Thanks!

**Comment by Asssssert** [comment]
Hi @sgowroji  , Sorry I missed your message. When I was reading the prerequisites documentation, I didn't notice "Setup Android SDK release 28.0.3 and above".
I would recommend that you consider compatibility with lower versions.
