### ISSUE TITLE
Unable to compile for Android

### ISSUE THREAD

**Issue by RitvikMandyam** [google/mediapipe#2044]
Hi,
I'm trying to use the holistic tracking demo on Android. I got the example to compile, but then I modified mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java by adding these lines:
`
import com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmark;
import com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmarkList;
`

I wanted to do some additional processing on the landmarks. I saw that "//mediapipe/framework/formats:landmark_java_proto_lite" was already in the "deps" section of the android_binary in the BUILD file, so I assumed it was good to compile. However, attempting to compile gave me this error:

`
mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java:30: error: package com.google.mediapipe.formats.proto.LandmarkProto does not exist
import com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmark;
`
Any help fixing this would be appreciated.

**Comment by sgowroji** [comment]
Hi @RitvikMandyam, Could you please share your use case with code repo. Thanks!

**Comment by RitvikMandyam** [comment]
Sure. The BUILD file, modified MainActivity.java and modified .pbtxt files are here:
https://gist.github.com/RitvikMandyam/263d5422227a895cfc29ef6c7aec131a
I changed the .pbtxt files to remove the code related to face landmarks. I also changed MainActivity.java to have a PacketCallback which is supposed to get the pose landmarks.

**Comment by RitvikMandyam** [comment]
I figured it out, it looks like you can't import any of the protos into apps/basic/MainActivity.java. I copied the MainActivity.java from apps/facemeshgpu into apps/holistictrackinggpu, modified it to get the right output stream and pointed the BUILD file to it, everything works fine now.
