### ISSUE TITLE
Building pose keypoint aar platform:android solution:pose type:build/install 

### ISSUE THREAD

**Issue by NotSpooky** [google/mediapipe#2047]
I can build the Android example app with
`bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu:posetrackinggpu`

Is there a way to generate an AAR so I can import it from Flutter and use BlazePose from there?

**Comment by RitvikMandyam** [comment]
There are instructions about how to do this here:
https://github.com/google/mediapipe/blob/master/docs/getting_started/android_archive_library.md

**Comment by sgowroji** [comment]
Hi @NotSpooky, Please go through the [link](https://github.com/google/mediapipe/blob/master/docs/getting_started/android_archive_library.md) .And reach us if you still have any query. Thanks!

**Comment by NotSpooky** [comment]
Thanks, it works!
