### ISSUE TITLE
Mediapipe packetcreator error

### ISSUE THREAD

**Issue by JoseVidal17** [google/mediapipe#2048]
When I intend to use mediapipe in touchdesigner I get the following error

TypeError: Cannot cast array data from dtype('float32') to dtype('uint8') according to the rule 'safe'

the funny thing is that mediapipe says to support float but whenever it tells me that I need to cast it to uint8

I solved the error when I did this cast

                        img_RGB = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
			img_RGB=img_RGB/img_RGB.max()
			img_RGB=255*img_RGB
			img2 = img_RGB.astype(np.uint8)
			results =  hands.process(img_RGB)

but the quality of the precision is lost too much, does anyone know how I can configure the files to accept the float without having to cast?

**Comment by sgowroji** [comment]
Hi @JoseVidal17, Can you share the complete steps to  reproduce the above issue. And also details of the solutions you are referring. Thanks!

**Comment by JoseVidal17** [comment]
Well as I am working in touchdesigner I have to import everything in a specific folder as follows:
![image](https://user-images.githubusercontent.com/70071383/118820198-ab569b00-b87b-11eb-8213-3d699d57741f.png)

# me - this DAT
# scriptOp - the OP which is cooking


import cv2
import numpy as np
import mediapipe as mp


def onCook(scriptOp):
	mp_drawing = mp.solutions.drawing_utils
	mp_hands = mp.solutions.hands

	with mp_hands.Hands(
		static_image_mode=False,
		max_num_hands =2,
		min_detection_confidence=0.5) as hands:

		while(True):
			img = op('null1').numpyArray(delayed = True) #It's the equivalent of opencv in touchdesginer to grab the frame 

			heigth,width,_=img.shape
			
			img_RGB = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
			
			img_RGB=img_RGB/img_RGB.max()#it's the cadting of float32 to uint8
			img_RGB=255*img_RGB#it's the cadting of float32 to uint8
			img2 = img_RGB.astype(np.uint8)#it's the cadting of float32 to uint8
			results =  hands.process(img2)
			if results.multi_hand_landmarks is not None:
				for hand_landmarks in results.multi_hand_landmarks:
					x1= hand_landmarks.landmark[mp_hands.HandLandmark.MIDDLE_FINGER_MCP].x 
					y1= hand_landmarks.landmark[mp_hands.HandLandmark.MIDDLE_FINGER_MCP].y
					op('constant1').par.value0= x1
					op('constant2').par.value0= y1

			if (hand_landmarks.landmark[mp_hands.HandLandmark.THUMB_TIP].y >  hand_landmarks.landmark[mp_hands.HandLandmark.INDEX_FINGER_TIP].y and hand_landmarks.landmark[mp_hands.HandLandmark.THUMB_TIP].y >  hand_landmarks.landmark[mp_hands.HandLandmark.MIDDLE_FINGER_TIP].y and hand_landmarks.landmark[mp_hands.HandLandmark.THUMB_TIP].y >  hand_landmarks.landmark[mp_hands.HandLandmark.RING_FINGER_TIP].y and hand_landmarks.landmark[mp_hands.HandLandmark.THUMB_TIP].y >  hand_landmarks.landmark[mp_hands.HandLandmark.PINKY_TIP].y):
				op('force1').par.radial= 0.338
			else:
				op('force1').par.radial= 0
				op('constant1').par.value0= 10
				op('constant2').par.value0= 10
			scriptOp.copyNumpyArray(img)#It's the equivalent of touchdesigner to show the frame		
			return
			
	

without casting the error that comes out is

File "C:/Users/jvida/Desktop/ModelosVisionArtificial/ExtPy/Dep/python\mediapipe\python\packet_creator.py", line 147, in create_image_frame
    image_format, data, copy)
TypeError: Cannot cast array data from dtype('float32') to dtype('uint8') according to the rule 'safe'

and according to what I understand mediapipe also accepts floats, so I don't know why it always asks for it in uint8

**Comment by jiuqiant** [comment]
For floating type image data, the mediapipe image format needs to be either VEC32F1 or VEC32F2. See https://github.com/google/mediapipe/blob/master/mediapipe/python/pybind/packet_creator.cc#L65.

If you need this support, you can edit the solution_base.py file in your "C:/Users/jvida/Desktop/ModelosVisionArtificial/ExtPy/Dep/python\mediapipe\python" to give the packet creator either  VEC32F1 or VEC32F2 as the image format:

```
diff --git a/mediapipe/python/solution_base.py b/mediapipe/python/solution_base.
py
index 7b535c8..9afab6b 100644
--- a/mediapipe/python/solution_base.py
+++ b/mediapipe/python/solution_base.py
@@ -478,7 +478,7 @@ class SolutionBase:
                    data: Any) -> packet.Packet:
     if packet_data_type == _PacketDataType.IMAGE:
       return packet_creator.create_image_frame(
-          data, image_format=image_frame.ImageFormat.SRGB)
+          data, image_format=image_frame.ImageFormat.VEC32F1)
     else:
```

Here is the mapping from mediapipe image format to opencv mat type for your reference: https://github.com/google/mediapipe/blob/master/mediapipe/framework/formats/image_frame_opencv.cc#L23.

**Comment by JoseVidal17** [comment]
im gonna test it tomorrow, thank you, i'll tell you how work it

**Comment by sgowroji** [comment]
Hi @JoseVidal17, Did you try the above comment. Thanks!

**Comment by JoseVidal17** [comment]
Hello, I made the modification but it did not give results, then I continued testing things with the code and there is a configuration that is efficient in touch designer

# me - this DAT
# scriptOp - the OP which is cooking


import cv2
import numpy as np
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands



def onCook(scriptOp):
	with mp_hands.Hands(
	static_image_mode=False,
	max_num_hands =2,
	min_detection_confidence=0.7) as hands:

		while(True):
			img = op('null1').numpyArray(delayed=True)

			heigth,width,_ = img.shape
			img_RGB = cv2.cvtColor(img,cv2.COLOR_RGBA2RGB)
		
			img_RGB=img_RGB/img_RGB.max()#it's the cadting of float32 to uint8
			img_RGB=255*img_RGB#it's the cadting of float32 to uint8
			img2 = img_RGB.astype(np.uint8)#it's the cadting of float32 to uint8
			results =  hands.process(img2)

			if results.multi_hand_landmarks is not None:
				for hand_landmarks in results.multi_hand_landmarks:
					x1= hand_landmarks.landmark[mp_hands.HandLandmark.MIDDLE_FINGER_MCP].x 
					y1= hand_landmarks.landmark[mp_hands.HandLandmark.MIDDLE_FINGER_MCP].y
					op('constant1').par.value0= x1
					op('constant2').par.value0= y1
			else:
					op('constant1').par.value0= 10
					op('constant2').par.value0= 10
		
			scriptOp.copyNumpyArray(img)			
			return
			
	apparently the casting has to be done yes or yes in uint8 in touch designer
