### ISSUE TITLE
In example: instant motion tracking ,  can it track  any object or only specific objects (from object detection)?

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#2049]
In example: instant motion tracking ,  can it track  any object or only specific objects (from object detection)?

**Comment by sgowroji** [comment]
Hi @chensisi0730, Could you please share your complete use case. Did you get a chance to go through this [documentation](https://google.github.io/mediapipe/solutions/instant_motion_tracking#mediapipe-instant-motion-tracking). Thanks!

**Comment by chensisi0730** [comment]
> Hi @chensisi0730, Could you please share your complete use case. Did you get a chance to go through this [documentation](https://google.github.io/mediapipe/solutions/instant_motion_tracking#mediapipe-instant-motion-tracking). Thanks!

Usage scenario: draw a box on the screen. There may not be an object in the box, but it may only be a part of the object or even the background. How can we track it

**Comment by jianingwei** [comment]
Yes, it's able to track any object.

**Comment by chensisi0730** [comment]
> Yes, it's able to track any object.

in one word , i want to track a region

**Comment by jianingwei** [comment]
Yes, this tracker essentially tracks a region or image patch, as long as there is some texture inside the region.

**Comment by chensisi0730** [comment]
So how to replace the robot with the box drawn by the user   in example below
[https://google.github.io/mediapipe/solutions/instant_motion_tracking#mediapipe-instant-motion-tracking](url)

**Comment by jianingwei** [comment]
If you just want to draw bounding boxes, you can refer to this example https://google.github.io/mediapipe/solutions/box_tracking   It's using the same visual tracker. Instead of seeding the tracking from object detection, you can feed in user placed box. In other words, replace "ObjectDetectionSubgraphGpu" node in this graph mediapipe/mediapipe/graphs/tracking/object_detection_tracking_mobile_gpu.pbtxt  with your user drawing.

**Comment by sgowroji** [comment]
Hi @chensisi0730, Did you get a chance to go through the above comment. Thanks!

**Comment by chensisi0730** [comment]
> Hi @chensisi0730, Did you get a chance to go through the above comment. Thanks!

Can you describe how to realize it  . Thanks!

**Comment by jianingwei** [comment]
You can put user box in the detections proto with the right timestamps, then remove the "ObjectDetectionSubgraphGpu" node, and send the packet directly to "ObjectTrackingSubgraphGpu". See the graph I referred above mediapipe/mediapipe/graphs/tracking/object_detection_tracking_mobile_gpu.pbtxt

**Comment by chensisi0730** [comment]
> You can put user box in the detections proto with the right timestamps, then remove the "ObjectDetectionSubgraphGpu" node, and send the packet directly to "ObjectTrackingSubgraphGpu". See the graph I referred above mediapipe/mediapipe/graphs/tracking/object_detection_tracking_mobile_gpu.pbtxt

I am a beginner, can release a source code project? This kind of scene is very common,  thanks !

**Comment by jianingwei** [comment]
Releasing a new project will take some time and approvals. But if you have any questions during implementation, feel free to ask questions here, and we can help answering them. In particular, can you try the mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu/ example and mediapipe/graphs/tracking/object_detection_tracking_mobile_gpu.pbtxt graph, and start changing them from there?

**Comment by sgowroji** [comment]
Hi @chensisi0730, Let us know if you still have any questions specific to above [comment](https://github.com/google/mediapipe/issues/2049#issuecomment-856104230). Thanks!

**Comment by arijith96** [comment]
Hey @jianingwei, I think you could provide some insights in #2551. Looking forward to hearing from you :D
