### ISSUE TITLE
Memory leak of  facedetectioncpu example on Android (RK3399 specific)

### ISSUE THREAD

**Issue by zhouy1017** [google/mediapipe#205]
Hello,
We noticed a crash issue of facedetectioncpu example Android app directly built from repo after running hours on a 2G RAM platform.
We tested and monitored the memory usage of the application for over 12 hours on another device with 4G RAM and get a record of unusual growing memory usage.
The memory usage at the first minutes after application booted:

USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME                       
u0_a83        1963   399 **5623744 463512** 0                   0 S com.google.mediapipe.apps.facedetectioncpu
USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME                       
u0_a83        1963   399 **5623744 462452** 0                   0 S com.google.mediapipe.apps.facedetectioncpu

The memory usage after about 14 hours running:

USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME                       
u0_a83        1963   399 **14258664 2922496** 0                 0 S com.google.mediapipe.apps.facedetectioncpu
USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME                       
u0_a83        1963   399 **14430984 2925108** 0                 0 S com.google.mediapipe.apps.facedetectioncpu

(And we have the log by 30s interval indicating the growth by time).

We suspect there are some memory related issues in the application.

Here is our environment information:
Build OS: Ubuntu  18.04.3
Bazel Version: 0.29.1
Repo commit:c6fea4c9d9f3bdf081c10387d2b42ed854199d06
Testing Device: RK3399Pro
Android: 8.1.0 Kernel 4.4.167

**Comment by teleger** [comment]
> Hello,
> We noticed a crash issue of facedetectioncpu example Android app directly built from repo after running hours on a 2G RAM platform.
> We tested and monitored the memory usage of the application for over 12 hours on another device with 4G RAM and get a record of unusual growing memory usage.
> The memory usage at the first minutes after application booted:
> 
> USER PID PPID VSZ RSS WCHAN ADDR S NAME
> u0_a83 1963 399 **5623744 463512** 0 0 S com.google.mediapipe.apps.facedetectioncpu
> USER PID PPID VSZ RSS WCHAN ADDR S NAME
> u0_a83 1963 399 **5623744 462452** 0 0 S com.google.mediapipe.apps.facedetectioncpu
> 
> The memory usage after about 14 hours running:
> 
> USER PID PPID VSZ RSS WCHAN ADDR S NAME
> u0_a83 1963 399 **14258664 2922496** 0 0 S com.google.mediapipe.apps.facedetectioncpu
> USER PID PPID VSZ RSS WCHAN ADDR S NAME
> u0_a83 1963 399 **14430984 2925108** 0 0 S com.google.mediapipe.apps.facedetectioncpu
> 
> (And we have the log by 30s interval indicating the growth by time).
> 
> We suspect there are some memory related issues in the application.
> 
> Here is our environment information:
> Build OS: Ubuntu 18.04.3
> Bazel Version: 0.29.1
> Repo commit:c6fea4c9d9f3bdf081c10387d2b42ed854199d06
> Testing Device: RK3399Pro
> Android: 8.1.0 Kernel 4.4.167

My environment similar to you, is also in ubuntu for android development, hardware environment is rk3399. Want to know if you have some problems, such as building the app, the terminal was slow, but also download third-party libraries, for example opencv4.1, etc., those things are particularly large, slow download, do you have any solution? Also, are you building a new app? As for the 0.6 version of mediapipe, some new functions have been added, such as aar module can be built, there are still many problems, I look forward to discussing with you, ok? You are here, just reply me directly, thank you

**Comment by zhouy1017** [comment]
@teleger 
Currently we foucus on the memory leak issue on the original application provided as-it-is and no extended development is planned.  We are curious about your testing result on memory issues, do you have memory leak/abnormal usage on those examples?
Furthermore, for building issues, if you are in mainland China, be sure to set up correct source servers in Ubuntu to speed up dependecies downloading.

**Comment by mgyong** [comment]
@zhouy1017 @jiuqiant is doing facedetectioncpu testing on pixel 2 phone for past 2+ hours but currently it looks like there are no memory leak issues to date. We will report more.
A few questions
1) Did the memory leak gradually such that it takes 14 hours to see? or was there a sudden jump over time?
2) The memory leak could be something specific to RK3399Pro. It would be good if you could get another non-RK phone to test and see if this is something specific to Rockwell
3) What is your use case for MediaPipe? Curious your interest in getting MediaPipe working on Rockwell

**Comment by jiuqiant** [comment]
Hi, thanks for reporting this issue to us!

To reproduce this issue, I install the MediaPipe face detection cpu and gpu demo on a Google Pixel 2 XL and utilize Android Studio profiler to monitor the memory usage of each app for 2 hours. AFAICT, I don't see any significant memory leak on the Google Pixel 2 XL.

For the face detection cpu demo (in the debug mode), the memory usage of the app ranges from 380 MB to 395 MB. Here are two data points for your reference.
![face_detection_cpu_memory_profiling_start](https://user-images.githubusercontent.com/3359144/67908026-1e33e000-fb37-11e9-9b2c-151e3ca1d258.png)
![face_detection_cpu_memory_profiling_after_2_hrs](https://user-images.githubusercontent.com/3359144/67908028-1f650d00-fb37-11e9-9025-f357d96ab0d8.png)

For the face detection gpu demo, the memory footprint is between 260 MB to 275 MB. We provide two data points for your reference as well. You can build the face detection gpu demo in Android Studio by cloning [this repo](https://github.com/jiuqiant/mediapipe_aar_example) directly.
![face_detection_gpu_memory_profiling_after_start](https://user-images.githubusercontent.com/3359144/67908209-e6796800-fb37-11e9-9b66-87f03296e97a.png)
![face_detection_gpu_memory_profiling_after_2_hrs](https://user-images.githubusercontent.com/3359144/67908210-e711fe80-fb37-11e9-8be5-577ff28d62dc.png)

As the next step, we probably need to get a RK3399Pro to reproduce your issue. But, it may take longer time.

**Comment by teleger** [comment]
Good morning，Are you all so early?

**Comment by zhouy1017** [comment]
@mgyong @jiuqiant 
Thank you for paying atttention to this issue.

@mgyong 
For your questions:

> 1.Did the memory leak gradually such that it takes 14 hours to see? or was there a sudden jump over time?

The memory leaks gradually.  It becomes sensible after hours (crashed on a 2GB RK3288 in about 6 hours), and reaches unacceptable size after 14 hours.  

> 2.The memory leak could be something specific to RK3399Pro. It would be good if you could get another non-RK phone to test and see if this is something specific to Rockwell

Yes. After hours of testing, I could confirm this.  We tested on RK3399Pro and Samsung S7e.  And the result is that no memory leak on S7e while issue presists on RK3399.  You can check the results below.

> 3.What is your use case for MediaPipe? Curious your interest in getting MediaPipe working on Rockwell

We plan to use RK3399 to control an automatic door based on facedetection(just open the door for human faces, no face identity needed).

@jiuqiant 
Thanks for your test results.
We performed test on RK3399Pro and Samsung S7e for 2 hours.
On S7e, it's pretty similar to your result on Pixel.  No memory leak.
![S7e](https://user-images.githubusercontent.com/20305999/67922409-a7095500-fbe5-11e9-9d4f-e3414129c4f5.PNG)

On 3399, memory leak could be significant after 2 hours.
![3399](https://user-images.githubusercontent.com/20305999/67922143-d1a6de00-fbe4-11e9-8719-20fa5db1e1cc.PNG)

It is confirmed that the issue is RK3399 related.  
And by comparing 2 profiling result, we suspect that some memory release functions are not working normally and it might be opengl related.

**Comment by mgyong** [comment]
@zhouy1017 Curious why you are using RK3399? Is this the production board? We love to get more info on your use case. Pls email me mgyong at google dot com

**Comment by zhouy1017** [comment]
@jiuqiant  @mgyong 
We detected similar memory leak on Xiaomi Note3 cellphone with snapdragon 660 Soc.
The profiling is below:
![xiaomi](https://user-images.githubusercontent.com/20305999/68020830-aacad380-fcda-11e9-9c2b-bdae6a74bafb.PNG)

The memory allocated for NDK increased from around 100MB to 160MB during 1-2 hours.

**Comment by jiuqiant** [comment]
JFYI, we also tested the face detection cpu demo on a Xiaomi Redmi Note 5 for 2 hours and 20 minutes and I don't see significant memory leak. 
<img width="1680" alt=" xiaomi redmi note 5" src="https://user-images.githubusercontent.com/3359144/68337913-5044c500-0096-11ea-978a-71ecae76b26d.png">

**Comment by mgyong** [comment]
@zhouy1017 @jiuqiant tested on MIUI version 10.3.2 Stable, Android version 9 PKQ1.180 Redmi Note 5. Can you retest on your Note 3 (let us know what is the version?)? Thanks

**Comment by jiuqiant** [comment]
We worked with Rockchip (the manufacturer of RK3399) and got the issue solved by upgrading the mali drivers.

**Comment by ToNYLin66** [comment]
> We worked with Rockchip (the manufacturer of RK3399) and got the issue solved by upgrading the mali drivers.

I have Memory leak of handtrackinggpu now in RK3399 X99 TV Box, and my TV Box firmware system is the latest version.
How Can I solve this problem?

**Comment by zhouy1017** [comment]
Hello,
We received an system update from Rockchip and that fixed the issue we encountered.
I don’t know if Rockchip updates the update files listed on their website but maybe you can contact them directly to figure it out.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lovehuanhuan** [comment]
> Hello,
> We received an system update from Rockchip and that fixed the issue we encountered.
> I don’t know if Rockchip updates the update files listed on their website but maybe you can contact them directly to figure it out.
> 
> Get Outlook for iOS<https://aka.ms/o0ukef>
> …
> ________________________________
> From: Ting-Yu Lin <notifications@github.com>
> Sent: Thursday, March 26, 2020 1:47:53 PM
> To: google/mediapipe <mediapipe@noreply.github.com>
> Cc: zhouy1017 <chooow.yang@outlook.com>; Mention <mention@noreply.github.com>
> Subject: Re: [google/mediapipe] Memory leak of facedetectioncpu example on Android (RK3399 specific) (#205)
> 
> 
> We worked with Rockchip (the manufacturer of RK3399) and got the issue solved by upgrading the mali drivers.
> 
> I have Memory leak of handtrackinggpu now in RK3399 X99 TV Box, and my TV Box firmware system is the latest version.
> How Can I solve this problem?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgoogle%2Fmediapipe%2Fissues%2F205%23issuecomment-604242560&data=02%7C01%7C%7C07e80d4a6b0b4483c35c08d7d1493b62%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637207984760125304&sdata=mcMrjYeniaWekLfvKlKS4KAL2kDv7tR3CjFM%2FYM1hn0%3D&reserved=0>, or unsubscribe<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAE25QT6AIJJ4B5KBOBHBRKDRJLUATANCNFSM4JGSCT2A&data=02%7C01%7C%7C07e80d4a6b0b4483c35c08d7d1493b62%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637207984760125304&sdata=6WvMaQukq1F5yiwxEK9rxqJRAVhFbIzt1QHfz83Ji3Y%3D&reserved=0>.

能否把补丁私信我一份 81164785@qq.com

**Comment by lovehuanhuan** [comment]
I found that there is some problem with rk3399's  "GLES20.glDeleteTextures" , it doesn't work well,and will cause memory leak problem.  So, I created a texture pool to avoid calling GLES20.glGenTextures ererytime.
