### ISSUE TITLE
IOS mediapipe hand gesture recognition

### ISSUE THREAD

**Issue by borosabel** [google/mediapipe#2052]
Hello everybody!

I am a student at a Computer Science University, and I am writing my thesis work which is about the ASL language recognition. I trained a model which is recognize hands but I also need to find hands on the real-time video and write on the screen the particular letter. To find hands I am using mediapipe, but now I want to deploy this to IOS because that could be a good usage of this project, but the problem is that I don't really understand the IOS code or how to solve this issue.

Could somebody help me with a sophisticated explanation of what to do? I want to use mediapipe to locate a hand and feed that image to my trained model on IOS. The  @second part is already done, the problem is that I don't really know how to modify the mediapipe code to get the images and write a label on the screen. 

Many thanks!

**Comment by sgowroji** [comment]
Hi @borosabel, Glad to know you choose MediaPipe for your thesis. For IOS we have very clear documentation [here](https://google.github.io/mediapipe/getting_started/ios).  You can build an Hand tracking code from the above link and reach us if you still have any query. For ASL language recognition look at reference https://github.com/google/mediapipe/issues/450

**Comment by borosabel** [comment]
Hello @sgowroji! Thank you for your quick reply! So I have successfully deployed the example app to my phone, I just need a little bit of support to modify the given code to get an image from the hand in the bounding box, feed that image to my trained model and get a response. It would be a huge help if you could help me a little bit with this.

**Comment by borosabel** [comment]
@eknight7 Hello! I saw that you always have a solution to this kind of issue. Could you help me a little bit?

**Comment by sgowroji** [comment]
Hi @borosabel, Did you get chance to go through the above [comment](https://github.com/google/mediapipe/issues/2052#issuecomment-845397623). Thanks!

**Comment by cckv** [comment]
@borosabel How did you deploy mediapipe to iOS? I encountered a lot of errors。

**Comment by sgowroji** [comment]
Hi @borosabel, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
Hi @borosabel, Could you please share us the error logs to investigate it for further. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity. Please feel free to reopen if you have relevant update on the above query!
