### ISSUE TITLE
Strange behaviour of FaceMesh solution with max_num_faces parameter 

### ISSUE THREAD

**Issue by FedericoCozziVM** [google/mediapipe#2055]
Hello to everyone,

I noticed a strange behaviour of the python solution "FaceMesh" (mediapipe version 0.8.4.2). When processing some selected images containing faces, no faces are detected when setting up the FaceMesh object with parameter `max_num_faces=1`, but a single face is detected when I provide 2 or more as parameter. 

Img to reproduce:
![img](https://user-images.githubusercontent.com/41443775/118820379-82073080-b8b6-11eb-86ef-231191fc653e.jpg)

Code to reproduce:

```
import cv2
import matplotlib.pyplot as plt
import  mediapipe as mp
import  numpy as np

path = 'img.jpg'

def normalized_landmarks_to_image_coords(landmarks, img_shape):
    x_list = []
    y_list = []
    z_list = []
    for i, p in enumerate(landmarks.landmark):
        x_list.append(min(p.x*img_shape[1], img_shape[1]-1))
        y_list.append(min(p.y*img_shape[0], img_shape[0]-1))
        z_list.append(p.z)
    x_list = np.array(x_list)
    y_list = np.array(y_list)
    z_list = np.array(z_list)
    result = np.stack([x_list, y_list, z_list])
    return result


face_mesh = mp.solutions.face_mesh.FaceMesh(False, max_num_faces=1, min_detection_confidence=0.1)

img = cv2.imread(path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img)
result = face_mesh.process(img)
if result.multi_face_landmarks is not None:
    print(len(result.multi_face_landmarks), ' faces')
    landmarks = normalized_landmarks_to_image_coords(result.multi_face_landmarks[0], img.shape)
    landmarks = landmarks[:-1, :]
    landmarks = np.transpose(landmarks)
    plt.scatter(landmarks[:, 0], landmarks[:, 1], s=3.2)

else:
    print('No faces')
```

Output with `max_num_faces=1`:
```No faces```

![download](https://user-images.githubusercontent.com/41443775/118824172-e8418280-b8b9-11eb-8db7-119fcc55beb7.png)

Output with `max_num_faces=2` or more
```1 faces```
![download](https://user-images.githubusercontent.com/41443775/118822599-96e4c380-b8b8-11eb-996d-03ea4dae4c43.png)

It happens just a bunch of times over 25K+ images tested, so it's not a big problem, but this behaviour is still unclear to me and the parameter seems to be counterintuitive

**Comment by sgowroji** [comment]
Hi @FedericoCozziVM, Could you please try the above with the latests release. Thanks!

**Comment by FedericoCozziVM** [comment]
Hi @sgowroji, I tested it with mediapipe pip version 0.8.6.1, but the issue is not fixed yet.

Code: 

```
fig, ax = plt.subplots(1, 3, figsize=(20, 10))
for i in range(3):
    
    face_mesh = mp.solutions.face_mesh.FaceMesh(False, max_num_faces=i+1, min_detection_confidence=0.1)



    ax[i].imshow(img)
    result = face_mesh.process(img)
    if result.multi_face_landmarks is not None:
        for r in result.multi_face_landmarks:
            if r is not None:
                landmarks = normalized_landmarks_to_image_coords(r, img.shape)
                landmarks = landmarks[:-1, :]
                landmarks = np.transpose(landmarks)
                ax[i].scatter(landmarks[:, 0], landmarks[:, 1], s=3.2)
    ax[i].title.set_text(f'max {i+1} faces')
    
plt.show()
```

Result (result with max_num_faces [1, 2, 3]):
![image](https://user-images.githubusercontent.com/41443775/127338201-5eee74ae-013b-430e-a436-d0018faf081b.png)

**Comment by sureshdagooglecom** [comment]
Hi @FedericoCozziVM ,
Are you still looking for the resolution on this issue.

**Comment by FedericoCozziVM** [comment]
Hi @sureshdagooglecom, no I'm not actively looking for a solution, but I just tested on mediapipe 0.8.11 and it's still an issue

**Comment by kuaashish** [comment]
Hi @FedericoCozziVM, 
Our dataset for training face detection for the front camera is composed of mostly selfie images and we trained with rotation augmentation (+/- 45 degrees). So there are training examples up to 90 degrees rotation.
However, we don't have much flipped face in the dataset and the model is not expected to work in that case. Thank you!

**Comment by FedericoCozziVM** [comment]
Hi @kuaashish, 
thank you for answering. I know, I also read the paper about the training data of the backbone face detector model. The problem is not about not detecting the old man, who is in fact too much rotated. The problem is that if I set the parameter `max_num_faces` = 1, I would expect to detect the face of the old lady, which is frontal: instead, the face is detected only by setting `max_num_faces` = 1 or more.

**Comment by kuaashish** [comment]
Hi @FedericoCozziVM,
Could you please investigate with several different input images mostly the selfie images or the front facing images and adjust the parameter accordingly to detect the number of faces using the `max_num_faces`. Please report back if the issue still persists that will be helpful to investigate further. Thank you!

**Comment by kuaashish** [comment]
Hi @FedericoCozziVM,
Could you please go through the [above](https://github.com/google/mediapipe/issues/2055#issuecomment-1300684531) comment. Thank you!

**Comment by FedericoCozziVM** [comment]
Hi @kuaashish and @gkarpiak, thanks for your responses, and sorry if I answered late.

@gkarpiak that's a great idea! I just made some experiments in this [colab](https://colab.research.google.com/drive/1vWIjw2-9d9MxD768Ur3RRZOOEE2yMJvM?usp=sharing) recycling some code from @kuaashish ones.

`mp.solutions.face_detector` (blazeface) with `model_selection=0` finds 2 faces:
- right one (frontal old lady) with confidence 0.68
- left one (lateral old man) with confidence 0.57 (actually, that's a noisy detection and obviously bounding box and basic facial landmarks - eyes, mouth, nose -  can't be placed correctly)

So that's even stranger: face detector finds 2 faces and **ASSUMING** that the face detector model is the same in both mp solutions, as reported in documentation, when setting `max_num_faces=1` in FaceMesh it should keep and analyze the face of the old woman that has a higher confidence score... instead FaceMesh continues detecting the right face only when this parameter is 2 or higher.

It would be helpful to pass FaceDetector detections to FaceMesh "externally" or to set different `model_selection` values to the inner FaceMesh face detector, or again to access FaceMesh confidence score, but I couldn't find a way to do it

**Comment by kuaashish** [comment]
Hello @FedericoCozziVM,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
