### ISSUE TITLE
Running graph hand tracking cannot validate side packet input

### ISSUE THREAD

**Issue by matthewn4444** [google/mediapipe#2058]
Hello,

I am not sure why this is happening, I am new to mediapipe so i might be missing something. 

I copied the basic hand tracking example but removed the final rendering node, all I am interested is in the **hand_landmarks**. After compiling mediapipe to shared library for android, I am trying to do the basic run, parse configuration graph, set the output poller and then i need to input the **num_hands** integer side packet. I am having trouble getting the sidepacket to work with `StartRun`.

After i run this code on Android in C++ I get the following error after trying to `StartRun`.

```
 ValidateRequiredSidePackets failed to validate:
Side packet "num_hands" failed validation: The Packet stores "int", but "int" was requested.
Side packet "num_hands" failed validation: The Packet stores "int", but "int" was requested.
```

Why is the packet as an integer failing to verify as an integer? In the file **framework/packet.h** I can see the error message line 791. Seems as it is trying to get the integer from the packet it fails to get it. Is there a reason why this is happening? Am I missing something from the setup?

Code is below

```
# This is copied from the default hand tracking graph file but i removed the rendering final step

# GPU image. (GpuBuffer)
input_stream: "input_video"

# Max number of hands to detect/process. (int)
input_side_packet: "num_hands"

# Collection of detected/predicted hands, each represented as a list of
# landmarks. (std::vector<NormalizedLandmarkList>)
output_stream: "hand_landmarks"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:hand_landmarks"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Detects/tracks hand landmarks.
node {
  calculator: "HandLandmarkTrackingGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "NUM_HANDS:num_hands"
  output_stream: "LANDMARKS:hand_landmarks"
  output_stream: "HANDEDNESS:handedness"
  output_stream: "PALM_DETECTIONS:palm_detections"
  output_stream: "HAND_ROIS_FROM_LANDMARKS:hand_rects_from_landmarks"
  output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:hand_rects_from_palm_detections"
}
      )pb");

        mediapipe::CalculatorGraph graph;
        auto res = graph.Initialize(config);
        if (!res.ok()) {
            std::cout << res.message();
            return false;
        }   

        auto result = graph.AddOutputStreamPoller("hand_landmarks");
        if (!result.ok()) {
              std::cout  << result.status().message();
            return false;
        }
          auto poller = std::move(result.value());
        graph.SetGraphInputStreamAddMode(
                mediapipe::CalculatorGraph::GraphInputStreamAddMode::WAIT_TILL_NOT_FULL);

      std::map<std::string, mediapipe::Packet> extra_side_packets;
        extra_side_packets.insert({"num_hands", mediapipe::MakePacket<int>(2)});

       auto r = graph.StartRun(extra_side_packets);
        if (!r.ok()) {
        std::cout < r.message();
             // Fails here
            return false;
        }

// More code here

```

I am running 0.8.3.1 version with Android compiled as a shared library but running majority of the code in c++ only.

**Comment by eknight7** [comment]
Hi, to get the landmarks on Android, I would recommend using something like this [code in Java](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L65-L91).
`graph.AddOutputStreamPoller(..)` is an API for getting landmarks in C++ on desktop. See an example [gist for desktop](https://gist.github.com/eknight7/d4a57504c8f866fc80c0eb2c61ff6b4f).

**Comment by matthewn4444** [comment]
That's not the problem, I can't start the graph because I can't get passed `graph.StartRun` because I am trying to pass a int side packet and verification fails trying to verify that it is an int even thoiugh it is an int, the network hasn't even ran yet.

**Comment by eknight7** [comment]
```
mediapipe::CalculatorGraph graph;
        auto res = graph.Initialize(config);
        if (!res.ok()) {
            std::cout << res.message();
            return false;
        }   

        auto result = graph.AddOutputStreamPoller("hand_landmarks");
        if (!result.ok()) {
              std::cout  << result.status().message();
            return false;
        }
          auto poller = std::move(result.value());
        graph.SetGraphInputStreamAddMode(
                mediapipe::CalculatorGraph::GraphInputStreamAddMode::WAIT_TILL_NOT_FULL);

      std::map<std::string, mediapipe::Packet> extra_side_packets;
        extra_side_packets.insert({"num_hands", mediapipe::MakePacket<uint64>(1123)});

       auto r = graph.StartRun(extra_side_packets);
        if (!r.ok()) {
        std::cout < r.message();
             // Fails here
            return false;
        }
```
You said you are running this code on Android here:
> I am running 0.8.3.1 version with Android compiled as a shared library but running majority of the code in c++ only.

But this  C++ code is for running on desktop:
```
auto res = graph.Initialize(config)
if (!res.ok()) {
  std::cout << res.message();
  return false;
}   

auto result = graph.AddOutputStreamPoller("hand_landmarks");
```
To initialize  a graph on Android, use the [FrameProcessor](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/java/com/google/mediapipe/components/FrameProcessor.java#L50) as used in [MainActivity here](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java).

Here is [an example](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/calculators/core/side_packet_to_stream_calculator_test.cc#L194-L195) of how to send `int` side packets in C++ on desktop.

**Comment by matthewn4444** [comment]
I am doing this all in c++ and I did implement the side packet like that but it doesn't work. I am debugging the mediapipe code and so far I found that at the time I make the map and add the side packet (sorry I copied pasted int64 earlier, its actually int)

```
   std::map<std::string, mediapipe::Packet> extra_side_packets;
        extra_side_packets.insert({"num_hands", mediapipe::MakePacket<int>(2)});

// Test here
LOG(INFO) << "What is it here? " << map.find("num_hands")->second.ValidateAsType<int>().ok();

       auto r = graph.StartRun(extra_side_packets);
```

The log here returns true as expected. In the meediapipe code for calculator_graph.cc I added the same check to the StartRun function (framework/calculator_graph.cc line 500 ish).

```
absl::Status CalculatorGraph::StartRun(
    const std::map<std::string, Packet>& extra_side_packets,
    const std::map<std::string, Packet>& stream_headers) {
  RET_CHECK(initialized_).SetNoLogging()
      << "CalculatorGraph is not initialized.";
for (const auto& item : extra_side_packets) {
// Output here as well
      LOG(INFO) << "Testing inside mediapipe: " << item.first << " " << item.second.ValidateAsType<int>().ok() << "  " << item.second.DebugTypeName();
    }   

  MP_RETURN_IF_ERROR(PrepareForRun(extra_side_packets, stream_headers));
  MP_RETURN_IF_ERROR(profiler_->Start(executors_[""].get()));
  scheduler_.Start();
  return absl::OkStatus();
}

```

Here the validating the same side packet (since there is only one in the map) is false for some reason. The validation verifies the holder status except all I did was passing the map by value and I confirmed the packet address is the same before and after it enters this function but for some reason it is failing. Validation is checking the value type of address, why is the address value changed just by entering the `StartRun` function?

**Comment by matthewn4444** [comment]
So after debugging I realized what the problem is.

When I import the shared library in my cmake project, I create the packet using 

`mediapipe::MakePacket<int>(2)`

And this is compiled using the header since the class definition is all in the header file. When compiling the mediapipe shared library there is another copy of the Packet class. Because I create the packet in my project, it uses a different Packet address when trying to verify the packet because mediapipe internal validation compares to the internal packet. When my project builds the apk it has 2 definitions of the Packet class because the Packet class has all the code in the headers and comparing the class address to verify compares the wrong Packet class. And because the packet class is templated, you cant just have the code inside the packet.cc file. The only way I can think about fixing this is to wrap the packet class without templates to reference the internal mediapipe packet class to call from my code outside of mediapipe.

Is there a better way to deal with this?

**Comment by eknight7** [comment]
Adding @hadon to answer the question about `Packet` and `Holder` classes.

**Comment by hadon** [comment]
Thanks Matthew for investigating the problem.  

I think you attribute the problem to two definitions of the Packet class.  That sounds surprising to me.  I think that C++ routinely avoids duplicating class definitions from in headers.  

You noticed that the validation depends on tool::GetTypeHash<T>(), in this case tool::GetTypeHash<int>().  It seems that this function must be failing.  Could there somehow be two definitions of type "int"?  Or maybe tool::GetTypeHash is just malfunctioning somehow.  Does your testing show two different values for GetTypeHash<int>()?  If so, we may need to debug GetTypeHash.  

GetTypeHash is defined using class TypeInfo, and type_util.h has two definitions for TypeInfo, depending on the compiler flag "MEDIAPIPE_HAS_RTTI".  Let me know if I can help debugging GetTypeHash, especially if we can reproduce this problem.

**Comment by matthewn4444** [comment]
So in this case it is a bit strange. I am compiling mediapipe into a shared library and including it into my app with Cmake. I know there is a jni and java api but I need to do a lot of code in C++ so I prefer to compile the shared library and use it exclusively in c++. 

The reason why there are 2 instances of Packet is that one is compiled in the source of the shared library and there's one when I compile my NDK code since the holder class is templated so it makes a separated class instance that when you call tool::GetTypeHash() it points to the address of the Holder class compiled in my binary but all the verification internally in mediapipe is referencing the pointer address of Holder in the packet class.

I temporary tested this but created a new wrapper class inside the mediapipe codebase (there might be syntax issues because i am writing the code from memory). PacketWrapper is compiled with mediapipe so its inside shared library (built with bazel)

```
// in the header file
using mediapipe;

class PacketWrapper {
public:
     PacketWrapper(int value);

     Packet& Packet();
private:
     Packet packet_;
};

// In the cc file
PacketWrapper::PacketWrapper(int value) : packet_(MakePacket<int>(value)) {
}


// Then in my code
graph.StartRun({{ "num_hands", PacketWrapper(2).Packet() }});


```

This works now because I compiled PacketWrapper into mediapipe shared library so it reference the packet and holder inside the mediapipe shared library.

I wonder instead of using  tool::GetTypeHash() to verify the class type could you instead cast the pointer to Holder/ForeignHolder then see if the address after casting is the same address as the pointer, then this would representing if it is correct, I personally haven't tried it yet.

To reproduce it is sorta involved. I think if you compile mediapipe into library with cc_binary and then link the shared library possibly on desktop (I was doing it on android but it might be the same), then build an exec with CMake with just trying to start run with makepacket after including it might fail.

**Comment by hadon** [comment]
I see.  MediaPipe definitely can be confused by duplicate class definitions.  Another place is the CalculatorBaseRegistry, when duplicated it can partition the known calculator names.  We usually avoid this by compiling the framework and calculators into a single C++ binary and consuming it with Java, Python, Javascript, or ObjectiveC.  

Your use case is one we would like to support eventually, by offering C++ bindings to shared libraries for MediaPipe "solutions".  We will need to armor the API somehow, as you are starting to do, to prevent the API headers from producing duplicate classes.  I will be interested to see any workarounds you create.

**Comment by kuaashish** [comment]
Hello @matthewn4444,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
