### ISSUE TITLE
Can we assume the predicted hand's xyz is in a 1*1*1 box?

### ISSUE THREAD

**Issue by Frank-Dz** [google/mediapipe#2059]
Can we assume the predicted XYZ is in a 1*1*1 box?
Since I found in hand detection, the original xy is in 0-1. I want to project it to my image space. Can we assume the depth(z) is also in 0~1?

The reason I wanna the project is current result in 0-1 is a little different from the real view...
![image](https://user-images.githubusercontent.com/55009565/118942184-1213ab80-b985-11eb-84c2-48aaea27fd2f.png)
![image](https://user-images.githubusercontent.com/55009565/118942254-2192f480-b985-11eb-81a1-148ab5e4695d.png)
It is too 'thin' compared to my real hand...
Any suggestions?

**Comment by Frank-Dz** [comment]
I want to make it with the real width and height radio.

**Comment by AmitMY** [comment]
I have no documentation for it, but the way I do it which seems to be ok:
```
x *= width
y *= height
z *= width
```

**Comment by sgowroji** [comment]
Hi @Frank-Dz, Could you please share your code repo to understand your changes. Thanks!

**Comment by Frank-Dz** [comment]
hi! It works for me.

Thanks!

**Comment by sgowroji** [comment]
We are glad to know you resolved. so closing this issue now.
