### ISSUE TITLE
Error execute app Hand Detection 

### ISSUE THREAD

**Issue by Jaguaribe21** [google/mediapipe#206]
10/30 21:02:28: Launching 'handdetectiongpu'.
$ adb shell am start -n "com.google.mediapipe.apps.handdetectiongpu/com.google.mediapipe.apps.handdetectiongpu.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Waiting for process to come online...
Connected to process 6142 on device 'Nexus_5X_API_29_x86 [emulator-5554]'.
Process 6142 terminated.

hand tracking has stopped, hand detection not open!

**Comment by eknight7** [comment]
Are you able to launch the app directly from the mobile device (i.e. without using `adb shell`) ?
