### ISSUE TITLE
objectron desktop GPU exampple, bazel example

### ISSUE THREAD

**Issue by AndreV84** [google/mediapipe#2061]
Is there non-python webcam implementation of objectron?
bazel based solution?
CPU desktop implementation?
GPU Desktop implementation?

**Comment by sgowroji** [comment]
Hi @AndreV84, Sincere apology for the misunderstanding,  I have reopened the previous issue i.e. https://github.com/google/mediapipe/issues/1922 issue and marking this present issue as duplicate of it.  We can follow up the discussion on the previous issue itself. Thanks!
