### ISSUE TITLE
Sync project with build file

### ISSUE THREAD

**Issue by nitecm** [google/mediapipe#2063]
When I sync has the following error

Error:mediapipe/examples/android/src/javatests/com/google/mediapipe/apps/basic is included, but that contradicts mediapipe which was excluded

Anyone can help

**Comment by sgowroji** [comment]
Hi @nitecm, Could you please provide more details and complete steps to reproduce the above issue. Thanks!

**Comment by sgowroji** [comment]
Hi @nitecm, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.
