### ISSUE TITLE
The performance of the hand_landmark model is degraded after re-implementation.

### ISSUE THREAD

**Issue by GesilaA** [google/mediapipe#2064]
Environment:
Ubuntu20.04, i7-9700f, python3.7, onnxruntime==1.7.0

I convert palm_detection.tflite and hand_landmark.tflite to .onnx model, and re-implement a simple procedure:
1) Read RGB image and divide to 255. 
2) Send image to palm_detection.onnx and get output
3) Expand the palm box to hand box, and rotate box by wrist and middle_finger_MCP point, extract rotated hand image and divide to 255.
4) Send rotated hand image to hand_landmark.onnx  and get output
5) Visualize

And I use tflite2onnx to convert tflite model to onnx model. The model has been converted correctly.

Visualize: Left window is the re-implement, middle window is the rotated hand img, right middle is generate by mediapipe python api.
Am I missing something important for hand_landmark? How to preprocess the hand image feed to landmark model?

False predict:
![failure_detection](https://user-images.githubusercontent.com/19608156/119100704-d0e5cf00-ba4a-11eb-84e1-7fe86224c4be.png)

True predict:
![good_detection1](https://user-images.githubusercontent.com/19608156/119099905-faeac180-ba49-11eb-8d3f-aeffb0e4a9b7.png)
![good_detection2](https://user-images.githubusercontent.com/19608156/119100456-8a907000-ba4a-11eb-9251-131b936289d6.png)

**Comment by hadon** [comment]
It looks like your converted model gives results that are no better or worse than the original model in the mediapipe python API.  Are you concerned about the difference in the error in landmarks for the pointer finger and the little finger?  

I believe the preprocessing of input images is done by "ImageTransformationCalculator" from "hand_image" to "transformed_hand_image" in "hand_landmark_gpu.pbtxt" or "hand_landmark_cpu.pbtxt".  It looks like the ImageTransformationCalculator produces a 256x256 pixel image preserving the aspect ratio.  Then the pixels are converted to tensorflow scalars normalized to [0.f, 1.f].

**Comment by sgowroji** [comment]
Hi @GesilaA, Could you please respond to the above [comment](https://github.com/google/mediapipe/issues/2064#issuecomment-859906631). Thanks

**Comment by GesilaA** [comment]
Thank you for your comments @hadon & @sgowroji , I modified the expansion factor according to the mediapipe source code in step3, and this problem has been solved.

**Comment by sgowroji** [comment]
Thank you for the update. We are closing this issue now
