### ISSUE TITLE
Bazel fail executing command aar_native_libs_zip_creator.exe,aar_embedded_jars_extractor.exe, aar_resources_extractor.exe

### ISSUE THREAD

**Issue by newbie7991** [google/mediapipe#2065]
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_pose_tracking.aar (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/Username/_bazel_chai1/ojr2u6ty/external/maven/BUILD:62:11: Filtering AAR native libs by architecture failed: (Exit 2): aar_native_libs_zip_creator.exe failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/android/aar_native_libs_zip_creator.exe --input_aar ... (remaining 5 argument(s) skipped)
/usr/bin/python: can't open file '/c/users/chai1/_bazel_chai1/ojr2u6ty/execroot/mediapipe/C:\Users\Username\_bazel_chai1\ojr2u6ty\execroot\mediapipe\bazel-out\host\bin\external\bazel_tools\tools\android\aar_native_libs_zip_creator.zip': [Errno 2] No such file or directory
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_pose_tracking.aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.865s, Critical Path: 0.39s
INFO: 129 processes: 129 internal.
FAILED: Build did NOT complete successfully

Im trying to run mediapipe with android using this command 
"bazel build --action_env PYTHON_BIN_PATH=C:\Users\Username\AppData\Local\Programs\Python\Python38\python.exe -c opt --strip=ALWAYS --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_pose_tracking.aar"

but the error show that, it unable to run the .exe file inside the folder and after I manually extracted, another .exe file facing the same problem again.
Anyone can help me with this error?

**Comment by newbie7991** [comment]
Hi @sgowroji, thanks for replying, here's the step i went through
1.)I am using guide from [https://google.github.io/mediapipe/getting_started/android_archive_library.html](url) to create a Mediapipe AAR file. I run this on PowerShell 
2.) When running step 2 from the [given](https://google.github.io/mediapipe/getting_started/android_archive_library.html), 
i uses `bazel build --action_env PYTHON_BIN_PATH=C:\Users\Username\AppData\Local\Programs\Python\Python38\python.exe -c opt --strip=ALWAYS --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_pose_tracking.aar                                   ` 
3.) follow the step given to resolve error #724 [https://github.com/google/mediapipe/issues/724#issue-622686030](url)

Then this bazel fail command prompt.
Thanks for

**Comment by jiuqiant** [comment]
As we mentioned in https://google.github.io/mediapipe/getting_started/install#installing-on-windows, MediaPipe doesn't support building its Android apps on native Windows because of the limited bazel support for Android on native Windows. Please try WSL instead. You can find the instructions at https://google.github.io/mediapipe/getting_started/install#installing-on-windows-subsystem-for-linux-wsl.

**Comment by sgowroji** [comment]
Hi @newbie7991, Have a look at the [comment](https://github.com/google/mediapipe/issues/2065#issuecomment-847188247) .

**Comment by newbie7991** [comment]
> As we mentioned in https://google.github.io/mediapipe/getting_started/install#installing-on-windows, MediaPipe doesn't support building its Android apps on native Windows because of the limited bazel support for Android on native Windows. Please try WSL instead. You can find the instructions at https://google.github.io/mediapipe/getting_started/install#installing-on-windows-subsystem-for-linux-wsl.

thank you for the answer....

**Comment by newbie7991** [comment]
Thanks @sgowroji
