### ISSUE TITLE
Pass MediaStream or canvas instead of video element, Holistic-JS

### ISSUE THREAD

**Issue by pwhite77** [google/mediapipe#2066]
The [example code](https://google.github.io/mediapipe/solutions/holistic#javascript-solution-api) for MediaPipe Holistic (JavaScript) fails when trying to pass a `MediaStream` (or `canvas` HTML element) instead of a `video` element. 

Do you have any fix or plans to support this in the immediate future?

Thanks!

**Comment by sgowroji** [comment]
Hi @pwhite77, Could you please share the  above error and update code changes.

**Comment by pwhite77** [comment]
Thanks, @sgowroji ! The error I'm getting: 
```
Uncaught (in promise) TypeError: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': Overload resolution failed.
    at la.h (pose.js:43)
    at S (pose.js:13)
    at pa.next (pose.js:14)
    at k (pose.js:23)
```

If you need, here's the code I'm using:
```
const pose = new Pose({locateFile: (file) => {
        return `https://cdn.jsdelivr.net/npm/@mediapipe/pose/${file}`;
    }});
pose.onResults(onResults);

function startPoseEstimation(video) {
    async function poseDetectionFrame() {
        await pose.send({image: video});
        requestAnimationFrame(poseDetectionFrame);
    }
    poseDetectionFrame();
}
```
To start pose detection, I use:
```
startPoseEstimation(document.getElementById("myVideo"));
```
And this works, but changing this to:
```
startPoseEstimation(myMediaStream);
```
causes the error.

**Comment by mhays-google** [comment]
@pwhite77 You can, in fact, send an HTML Image element.  We support HTMLVideoElement, HTMLImageElement, HTMLCanvasElement, and ImageBitmap.

We are considering some sort of MediaStream in the future, but I don't have a date.  On Chrome, you can do this today by instantiating `ImageCapture` on top of your MediaStream track, and then using `ImageCapture.grabFrame()` which will return an `ImageBitmap`.
