### ISSUE TITLE
The primary Android example failed to run

### ISSUE THREAD

**Issue by lzcchl** [google/mediapipe#2067]
Hi, I'm a rookie in Mediapipe, I run primary Android example failed, the website is: https://google.github.io/mediapipe/getting_started/android.html

the error is: 

------------------------------------------------------------------------------------------------------------------------------
ERROR: /home/lzc/.cache/bazel/_bazel_lzc/6132f374fa0169e4ee8804a892485cde/external/local_jdk/BUILD.bazel:3:10: in fail_rule rule @local_jdk//:jdk: 
Traceback (most recent call last):
	File "/home/lzc/.cache/bazel/_bazel_lzc/6132f374fa0169e4ee8804a892485cde/external/bazel_tools/tools/jdk/fail_rule.bzl", line 19, column 13, in _fail_rule_impl
		fail("%s %s" % (ctx.attr.header, ctx.attr.message))
Error in fail: Auto-Configuration Error: Cannot find Java binary bin/java in /home/lzc/.cache/bazel/_bazel_lzc/install/46850c2a96e4b4b07623822a03209f74/embedded_tools/tools/jdk/nosystemjdk; either correct your JAVA_HOME, PATH or specify embedded Java (e.g. --javabase=@bazel_tools//tools/jdk:remote_jdk11)
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld' failed; build aborted: Analysis of target '@local_jdk//:jdk' failed
INFO: Elapsed time: 0.114s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 2 targets conf\
igured)
    Fetching @remotejdk11_linux; fetching
------------------------------------------------------------------------------------------------------------------------------

I have no idea about to solve it, would you help me, thanks a lot.

**Comment by thaiph99** [comment]
Do you have a solution for this error ?

**Comment by ahres6618** [comment]
does someone find the solution ??
I have the same issue
