### ISSUE TITLE
Video input for hand tracking

### ISSUE THREAD

**Issue by rabBit64** [google/mediapipe#207]
hello, is there any way I can use video input instead of a desktop webcam to use a hand tracking model? thank you for a great job!

**Comment by eknight7** [comment]
Hi! You can use OpenCV to read a video file and send each frame to the MediaPipe graph, similar to how the example app sends each frame of the live video from the webcam to the MediaPipe graph. In fact, this functionality exists in https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/demo_run_graph_main.cc. See https://mediapipe.readthedocs.io/en/latest/object_detection_desktop.html for an example of how to use this functionality by providing an input video path and an output video path.

**Comment by mgyong** [comment]
@rabBit64 `GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/object_detection/object_detection_tensorflow \
  --calculator_graph_config_file=mediapipe/graphs/object_detection/object_detection_desktop_tensorflow_graph.pbtxt \
  --input_side_packets=input_video_path=/tmp/inputvideofile.mp4 ,output_video_path=/tmp/outputvideofile.mp4`

**Comment by rabBit64** [comment]
@eknight7 @mgyong  Thank you! It helped a lot👏
