### ISSUE TITLE
Iris does not work on Android

### ISSUE THREAD

**Issue by some2014** [google/mediapipe#2070]
Dear developer：
there is a problem on Android 10 device ( Cpu：Dimensity 1000+)
Face detection, hand tracking and pose tracking are all Fine.
After Iris tracking runs, the screen stops and cannot be detected.

Log:

05-23 18:19:16.067  7126  7230 I native  : I20210523 18:19:16.067222  7230 graph.cc:474] Start running the graph, waiting for inputs.
05-23 18:19:16.067  7126  7230 I native  : I20210523 18:19:16.067373  7230 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 4
05-23 18:19:16.070  7126  7410 I native  : I20210523 18:19:16.070674  7410 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 v1.r21p0-01rel0.26e760f69b3971e4a90ae11639de2ad6)
05-23 18:19:16.075  7126  7222 I native  : I20210523 18:19:16.075589  7222 resource_util_android.cc:87] Successfully loaded: face_detection_front.tflite
05-23 18:19:16.079  7126  7222 I tflite  : Initialized TensorFlow Lite runtime.
05-23 18:19:16.079  7126  7222 I tflite  : Created TensorFlow Lite delegate for GPU.
05-23 18:19:16.082  7126  7222 I tflite  : Replacing 164 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
05-23 18:19:16.087  7126  7402 I native  : I20210523 18:19:16.087770  7402 jni_util.cc:41] GetEnv: not attached
05-23 18:19:16.114  7126  7406 I native  : I20210523 18:19:16.114655  7406 jni_util.cc:41] GetEnv: not attached
05-23 18:19:16.149  7126  7405 I native  : I20210523 18:19:16.148980  7405 jni_util.cc:41] GetEnv: not attached
05-23 18:19:16.186  7126  7408 I native  : I20210523 18:19:16.186630  7408 jni_util.cc:41] GetEnv: not attached
05-23 18:19:16.517  7126  7407 I native  : I20210523 18:19:16.517123  7407 jni_util.cc:41] GetEnv: not attached
05-23 18:19:16.749  7126  7222 I native  : I20210523 18:19:16.749878  7222 resource_util_android.cc:87] Successfully loaded: face_landmark.tflite
05-23 18:19:16.752  7126  7222 I tflite  : Replacing 97 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
05-23 18:19:16.817  7126  7409 I native  : I20210523 18:19:16.817726  7409 jni_util.cc:41] GetEnv: not attached
05-23 18:19:16.851  7126  7403 I native  : I20210523 18:19:16.851384  7403 jni_util.cc:41] GetEnv: not attached
05-23 18:19:17.456  7126  7222 I native  : I20210523 18:19:17.456423  7222 resource_util_android.cc:87] Successfully loaded: iris_landmark.tflite
05-23 18:19:17.457  7126  7222 I tflite  : Replacing 169 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
05-23 18:19:17.618  7126  7404 I native  : I20210523 18:19:17.618875  7404 jni_util.cc:41] GetEnv: not attached
05-23 18:19:18.771  7126  7222 I native  : I20210523 18:19:18.771340  7222 resource_util_android.cc:87] Successfully loaded: iris_landmark.tflite
05-23 18:19:18.772  7126  7222 I tflite  : Replacing 169 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
05-23 18:19:20.102  7126  7222 I native  : I20210523 18:19:20.102336  7222 jni_util.cc:41] GetEnv: not attached

Now the screen stoped.

**Comment by sgowroji** [comment]
Hi @some2014, Could you please provide the complete steps to reproduce the above error. Thanks!

**Comment by some2014** [comment]
> Hi @some2014, Could you please provide the complete steps to reproduce the above error. Thanks!

Hi @sgowroji , When I run the app of face mesh and pose, it is normal, and the speed can reach 60fps+.

When I run the iris app, the screen is black.

all log:

05-26 19:04:55.476  2061  2061 D Launcher.CellLayout: touch item:ShortcutInfo, id=245, itemType=0, user=UserHandle{0}, mIconType=0, pkgName=com.google.mediapipe.apps.iristrackinggpu, className=com.google.mediapipe.apps.iristrackinggpu.MainActivity, screenId=5, container=-100, cellX=2, cellY=1, spanX=1, spanY=1, isLandscapePos=false
05-26 19:07:18.436  2061  2231 D MiuiMultiWindowUtils: readFreeformTimestamps::str = ["{com.ss.android.ugc.aweme=[1612282639413, 1614730941363], tv.danmaku.bili=[1607173715685], com.tencent.mm=[1612074893600, 1614907778254], com.fenbi.android.zenglish=[1618924029106], com.google.mediapipe.apps.iristrackinggpu=[1621765055437]}"]
05-26 19:07:18.437  2061  2231 D MiuiMultiWindowUtils: readFreeformTimestamps::result = {com.ss.android.ugc.aweme=[1612282639413, 1614730941363], tv.danmaku.bili=[1607173715685], com.tencent.mm=[1612074893600, 1614907778254], com.fenbi.android.zenglish=[1618924029106], com.google.mediapipe.apps.iristrackinggpu=[1621765055437]}
05-26 19:07:18.636  2061  2160 D MiuiMultiWindowUtils: readFreeformTimestamps::str = ["{com.ss.android.ugc.aweme=[1612282639413, 1614730941363], tv.danmaku.bili=[1607173715685], com.tencent.mm=[1612074893600, 1614907778254], com.fenbi.android.zenglish=[1618924029106], com.google.mediapipe.apps.iristrackinggpu=[1621765055437]}"]
05-26 19:07:18.636  2061  2160 D MiuiMultiWindowUtils: readFreeformTimestamps::result = {com.ss.android.ugc.aweme=[1612282639413, 1614730941363], tv.danmaku.bili=[1607173715685], com.tencent.mm=[1612074893600, 1614907778254], com.fenbi.android.zenglish=[1618924029106], com.google.mediapipe.apps.iristrackinggpu=[1621765055437]}
05-26 19:07:25.351  2061  2061 D Launcher.CellLayout: touch item:ShortcutInfo, id=245, itemType=0, user=UserHandle{0}, mIconType=0, pkgName=com.google.mediapipe.apps.iristrackinggpu, className=com.google.mediapipe.apps.iristrackinggpu.MainActivity, screenId=5, container=-100, cellX=2, cellY=1, spanX=1, spanY=1, isLandscapePos=false
05-26 19:07:25.416  1345 12048 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.mediapipe.apps.iristrackinggpu/.MainActivity bnds=[586,440][754,608] (has extras)} from uid 10086
05-26 19:07:25.443  1345  1387 I PowerHalWrapper: amsBoostProcessCreate package:com.google.mediapipe.apps.iristrackinggpu
05-26 19:07:25.446   666  1411 I BufferQueueConsumer: [Splash Screen com.google.mediapipe.apps.iristrackinggpu#0](this:0x7b76986000,id:656,api:0,p:-1,c:666) setConsumerName: Splash Screen com.google.mediapipe.apps.iristrackinggpu#0
05-26 19:07:25.446   666  1411 I BufferQueueConsumer: [Splash Screen com.google.mediapipe.apps.iristrackinggpu#0](this:0x7b76986000,id:656,api:0,p:-1,c:666) setDefaultBufferSize: width=1 height=1
05-26 19:07:25.447   666  1411 I BufferQueueConsumer: [Splash Screen com.google.mediapipe.apps.iristrackinggpu#0](this:0x7b76986000,id:656,api:0,p:-1,c:666) setDefaultBufferSize: width=1080 height=2400
05-26 19:07:25.453   666  1411 I BufferQueueProducer: [Splash Screen com.google.mediapipe.apps.iristrackinggpu#0](this:0x7b76986000,id:656,api:2,p:1345,c:666) connect(P): api=2 producer=(1345:system_server) producerControlledByApp=false
05-26 19:07:25.460   586  1926 D OemNetd : setPidForPackage: packageName=com.google.mediapipe.apps.iristrackinggpu, pid=30163, pid=10313
05-26 19:07:25.460  1345  1398 I ActivityManager: Start proc 30163:com.google.mediapipe.apps.iristrackinggpu/u0a313 for activity {com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity} caller=com.miui.home
05-26 19:07:25.474  6575  6650 I GST     : forePkg: com.google.mediapipe.apps.iristrackinggpu, preForePkg: com.miui.home
05-26 19:07:25.474  3121 27960 I ProcessMonitor: onForegroundInfoChanged: ForegroundInfo{mForegroundPackageName='com.google.mediapipe.apps.iristrackinggpu', mForegroundUid=10313, mForegroundPid=30163, mLastForegroundPackageName='com.miui.home', mLastForegroundUid=10086, mLastForegroundPid=2061, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=1}
05-26 19:07:25.474  3121 27960 I GameBoosterService: onForegroundInfoChanged: Cur=com.google.mediapipe.apps.iristrackinggpu      last=com.miui.home
05-26 19:07:25.476   615   684 I libPowerHal: [perfNotifyAppState] pack:com.google.mediapipe.apps.iristrackinggpu, act:com.google.mediapipe.apps.iristrackinggpu.MainActivity, state:1
05-26 19:07:25.476   615   684 I libPowerHal: [perfNotifyAppState] foreground:com.google.mediapipe.apps.iristrackinggpu, pid:30163, uid:10313
05-26 19:07:25.476   615   684 I UxUtility: notifyForegroundApp pack:com.google.mediapipe.apps.iristrackinggpu, uid:10313
05-26 19:07:25.476   615   684 I libPowerHal: [perfNotifyAppState][activity updated] pack:com.google.mediapipe.apps.iristrackinggpu, act:com.google.mediapipe.apps.iristrackinggpu.MainActivity
05-26 19:07:25.476   615   684 I mtkpower@impl: [powerd_req] POWER_MSG_NOTIFY_STATE, pc:1, com.miui.home => com.google.mediapipe.apps.iristrackinggpu
05-26 19:07:25.477  3121 27960 D GameBoosterService: onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.google.mediapipe.apps.iristrackinggpu', mForegroundUid=10313, mForegroundPid=30163, mLastForegroundPackageName='com.miui.home', mLastForegroundUid=10086, mLastForegroundPid=2061, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=1}
05-26 19:07:25.588 30163 30188 D libMEOW : applied 0 plugin for [com.google.mediapipe.apps.iristrackinggpu].
05-26 19:07:25.604 30163 30163 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.google.mediapipe.apps.iristrackinggpu activity: com.google.mediapipe.apps.iristrackinggpu.MainActivity@fbd2918
05-26 19:07:25.605 30163 30163 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.google.mediapipe.apps.iristrackinggpu activity: com.google.mediapipe.apps.iristrackinggpu.MainActivity@fbd2918
05-26 19:07:25.611 30163 30163 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.google.mediapipe.apps.iristrackinggpu activity: com.google.mediapipe.apps.iristrackinggpu.MainActivity@fbd2918
05-26 19:07:25.612 30163 30163 I chatty  : uid=10313(com.google.mediapipe.apps.iristrackinggpu) identical 2 lines
05-26 19:07:25.613 30163 30163 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.google.mediapipe.apps.iristrackinggpu activity: com.google.mediapipe.apps.iristrackinggpu.MainActivity@fbd2918
05-26 19:07:25.614 30163 30163 D libMEOW : applied 0 plugin for [com.google.mediapipe.apps.iristrackinggpu].
05-26 19:07:25.631 30163 30202 D libMEOW : applied 0 plugin for [com.google.mediapipe.apps.iristrackinggpu].
05-26 19:07:25.637 30163 30203 D libMEOW : applied 0 plugin for [com.google.mediapipe.apps.iristrackinggpu].
05-26 19:07:25.656 30163 30206 I chatty  : uid=10313(com.google.mediapipe.apps.iristrackinggpu) CameraX-core_ca identical 1 line
05-26 19:07:25.662  2061  2061 D RecentsImpl: mActivityStateObserver com.google.mediapipe.apps.iristrackinggpu.MainActivity
05-26 19:07:25.662  2061  2061 W RecentsImpl: onResumed className=com.google.mediapipe.apps.iristrackinggpu.MainActivity   mIsInAnotherPro=false
05-26 19:07:25.664  1345  2905 I WindowManager: Relayout Window{990028a u0 com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity}: oldVis=4 newVis=0 focusMayChange = true
05-26 19:07:25.665   666  2149 I BufferQueueConsumer: [com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0](this:0x7b75a53800,id:658,api:0,p:-1,c:666) setConsumerName: com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0
05-26 19:07:25.665   666  2149 I BufferQueueConsumer: [com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0](this:0x7b75a53800,id:658,api:0,p:-1,c:666) setDefaultBufferSize: width=1 height=1
05-26 19:07:25.666   666  2149 I BufferQueueConsumer: [com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0](this:0x7b75a53800,id:658,api:0,p:-1,c:666) setDefaultBufferSize: width=1080 height=2400
05-26 19:07:25.669 30163 30186 D libMEOW : applied 0 plugin for [com.google.mediapipe.apps.iristrackinggpu].
05-26 19:07:25.673   666  2149 I BufferQueueProducer: [com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0](this:0x7b75a53800,id:658,api:1,p:30163,c:666) connect(P): api=1 producer=(30163:com.google.mediapipe.apps.iristrackinggpu) producerControlledByApp=false
05-26 19:07:25.699   666  2149 I BufferQueueProducer: [Splash Screen com.google.mediapipe.apps.iristrackinggpu#0](this:0x7b76986000,id:656,api:2,p:1345,c:666) disconnect(P): api 2
05-26 19:07:25.701  1345  1396 I ActivityTaskManager: Displayed com.google.mediapipe.apps.iristrackinggpu/.MainActivity: +283ms
05-26 19:07:25.708 30163 30204 D libMEOW : applied 0 plugin for [com.google.mediapipe.apps.iristrackinggpu].
05-26 19:07:25.711 30163 30204 I BufferQueue: [unnamed-30163-0](this:0x72ee84f800,id:0,api:0,p:-1,c:-1) BufferQueue core=(30163:com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:25.717   781  3306 I CameraService: CameraService::connect call (PID -1 "com.google.mediapipe.apps.iristrackinggpu", camera ID 1) for HAL version default and Camera API version 2
05-26 19:07:25.720 30163 30204 I BufferQueueConsumer: [unnamed-30163-0](this:0x72ee84f800,id:0,api:0,p:-1,c:30163) connect(C): consumer=(30163:com.google.mediapipe.apps.iristrackinggpu) controlledByApp=true
05-26 19:07:25.722   820 11612 D         : [HIDL][ATMs]Received factor(APP_NAME), factor_value(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:25.725   781  3306 I Camera2ClientBase: Camera 1: Opened. Client: com.google.mediapipe.apps.iristrackinggpu (PID 30163, UID 10313)
05-26 19:07:25.728  3121 27960 I BehaviorRecord-Monitor: com.google.mediapipe.apps.iristrackinggpu , perm: 4096 , active true , current size: 1 , foreground com.google.mediapipe.apps.iristrackinggpu
05-26 19:07:25.913   666   666 I SurfaceFlinger: screenshot (com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0)
05-26 19:07:25.913   666   666 I SurfaceFlinger: screenshot (Splash Screen com.google.mediapipe.apps.iristrackinggpu#0)
05-26 19:07:26.021  1345 12368 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{ff83091 u0 com.google.mediapipe.apps.iristrackinggpu/.MainActivity t73} time:19392161
05-26 19:07:26.027   666   666 I SurfaceFlinger: screenshot (com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0)
05-26 19:07:26.027   666   666 I SurfaceFlinger: screenshot (Splash Screen com.google.mediapipe.apps.iristrackinggpu#0)
05-26 19:07:26.041   666   666 I BufferQueue: [Splash Screen com.google.mediapipe.apps.iristrackinggpu#0](this:0x7b76986000,id:656,api:2,p:-1,c:-1) ~BufferQueueCore
05-26 19:07:26.136   666   666 I SurfaceFlinger: screenshot (com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0)
05-26 19:07:26.211   781  3306 I CameraService: CameraService::finishConnectLocked and PopupCameraManager (PID 30163 "com.google.mediapipe.apps.iristrackinggpu", camera ID 1)
05-26 19:07:26.251   666   666 I SurfaceFlinger: screenshot (com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0)
05-26 19:07:26.366   666   666 I SurfaceFlinger: screenshot (com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0)
05-26 19:07:26.447   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.447   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.481   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.481   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.482   666   666 I SurfaceFlinger: screenshot (com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0)
05-26 19:07:26.514   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.514   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.552   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.552   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.579   666  2149 I SurfaceFlinger: [SF client] NEW(0x7b93890500) for (30163:com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.580   666  1411 I BufferQueueConsumer: [Bounds for - com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0](this:0x7b76cb3000,id:660,api:0,p:-1,c:666) setConsumerName: Bounds for - com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0
05-26 19:07:26.581   666  2149 I SurfaceFlinger: [SF client] NEW(0x7b938908c0) for (30163:com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.581   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.581   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.581   666  2149 I BufferQueueConsumer: [SurfaceView - com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0](this:0x7b75a93000,id:661,api:0,p:-1,c:666) setConsumerName: SurfaceView - com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0
05-26 19:07:26.581   666  2149 I BufferQueueConsumer: [SurfaceView - com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0](this:0x7b75a93000,id:661,api:0,p:-1,c:666) setDefaultBufferSize: width=1080 height=2106
05-26 19:07:26.583   666  1411 I BufferQueueProducer: [SurfaceView - com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0](this:0x7b75a93000,id:661,api:1,p:30163,c:666) connect(P): api=1 producer=(30163:com.google.mediapipe.apps.iristrackinggpu) producerControlledByApp=false
05-26 19:07:26.598   666   666 I SurfaceFlinger: screenshot (com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0)
05-26 19:07:26.614   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.614   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.619 30163 30288 D libMEOW : applied 0 plugin for [com.google.mediapipe.apps.iristrackinggpu].
05-26 19:07:26.654   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.654   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.694   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.694   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.712   666   666 I SurfaceFlinger: screenshot (com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0)
05-26 19:07:26.734   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.734   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.774   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.774   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.814   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.814   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.826   666   666 I SurfaceFlinger: screenshot (com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0)
05-26 19:07:26.855   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.855   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.895   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.895   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.935   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.935   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:26.946   666   666 I SurfaceFlinger: screenshot (com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0)
05-26 19:07:26.975   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:26.975   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:27.015   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:27.015   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:27.055   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:27.055   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:27.068   666   666 I SurfaceFlinger: screenshot (com.google.mediapipe.apps.iristrackinggpu/com.google.mediapipe.apps.iristrackinggpu.MainActivity#0)
05-26 19:07:27.095   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:27.095   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:27.135   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:27.135   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:27.175   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:27.175   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:27.215   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:27.215   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:27.255   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:27.255   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)
05-26 19:07:27.296   820 30217 D isp_tuning_custom: pAppname = com.google.mediapipe.apps.iristrackinggpu AppName = MTKCam
05-26 19:07:27.296   820 30217 D isp_tuning_custom: Appname(com.google.mediapipe.apps.iristrackinggpu)

**Comment by mcclanahoochie** [comment]
since the other apps work, mediapipe seems Ok in general.

the iris tracking graph needs the focal length of the camera. can you verify that this is getting called at least once?
https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/iristrackinggpu/MainActivity.java#L48

**Comment by sgowroji** [comment]
Hi @some2014, Could you please respond to the above [comment](https://github.com/google/mediapipe/issues/2070#issuecomment-864314687). Thanks!
