### ISSUE TITLE
multi_hand_tracking

### ISSUE THREAD

**Issue by kbh1860** [google/mediapipe#2071]
I can't find a directory of mediapipe/examples/desktop/multi_hand_tracking. 

Is it destroyed? How Can I get it.... :D

**Comment by sgowroji** [comment]
Hi @kbh1860, you can get the multi hand landmarks from [here](https://g3doc.corp.google.com/third_party/mediapipe/g3doc/solutions/hands.md#multi-hand-landmarks).   Could you share your use case with complete details. Thanks!

**Comment by sgowroji** [comment]
Hi @kbh1860, Did you get a chance to go through my above [comment](https://github.com/google/mediapipe/issues/2071#issuecomment-846741627). Thanks!

**Comment by sgowroji** [comment]
Assuming your query resolved, We are closing this issue now.
