### ISSUE TITLE
Confidence level - python.solutions.hands

### ISSUE THREAD

**Issue by JanJan217** [google/mediapipe#2072]
Hi all, I am using Python for app where I detect objects (already defined by CNN) in combination with Hand detection by means of mediapipe.python.solutions.hands. I would like to calculate the overall confidence level (object detection and hand detection combined) and I am wondering whether it is possible to get the actual confidence level of hand detection only ... I have gone through the questions here but did not find answer for Python. I would appreciate any help or clue. Thx. J.

**Comment by sgowroji** [comment]
Hi @JanJan217, Have a look at this issue https://github.com/google/mediapipe/issues/428 for reference. Still, if your query not resolved. Please share your code or graph changes for a better understanding. Thanks

**Comment by JanJan217** [comment]
Hi sgowroji, thank you, I found out this info within Github and for anyone who is interested in, following the code from Nicholas Renotte it is possible to find out confidence level of particular hand point (in case I understand well). The issue is closed for me. Thx, J. 

https://github.com/nicknochnack/AdvancedHandPoseWithMediaPipe

**Comment by sgowroji** [comment]
Thank you @JanJan217 for sharing the information, this is really useful for other users in the community.
