### ISSUE TITLE
Unable to install mediapipe on jupyter notebook [python version: 3.7.1]

### ISSUE THREAD

**Issue by noviicee** [google/mediapipe#2073]
Overview
Hello! Hope this reaches you well.  I want to start using mediapipe with my work, but I'm having some trouble with my pip install.
I am doin this on a jupyter notebook though.

I'm running into *No matching distribution found* error as {#1325, #1466, #1961}. Their proposed solutions regarding python version and build unfortunately didn't work for me.

System Information

python == 3.7.1 (64-bit)

pip == 18.1

OS: Windows

Screenshot
![Untitled1](https://user-images.githubusercontent.com/72334601/119362393-44494400-bcca-11eb-862d-d6d34b2e7b0f.png)

**Comment by jiuqiant** [comment]
Can you upgrade your pip and do `python install -m pip` instead?
MediaPipe PyPI (https://pypi.org/project/mediapipe/#files ) has "mediapipe-0.8.4.2-cp37-cp37m-win_amd64.whl", which is for  64-bit windows with python3.7 binary. If you can't install it via pip, you can download the file and manually install it.

**Comment by sgowroji** [comment]
Hi @noviicee, Can you please try the information mentioned in the above [comment](https://github.com/google/mediapipe/issues/2073#issuecomment-847184400). Thanks!

**Comment by noviicee** [comment]
@jiuqiant thanks for the help!
I completed my code in a code-editor. But let me try with the notebook following the procedure as well!

**Comment by noviicee** [comment]
> @jiuqiant thanks for the help!
> I completed my code in a code-editor. But let me try with the notebook following the procedure as well!

It is not installing via pip. Guess I will have to do it manually 💁

**Comment by sgowroji** [comment]
2Hi @noviicee, Were you able to install MediaPipe. If still errors, please let us know the errors. Thanks

**Comment by noviicee** [comment]
> Hi @noviicee, Were you able to install MediaPipe. If still errors, please let us know the errors. Thanks

When I upgraded pip and did what is mentioned, it presented me with an error like so-

![image](https://user-images.githubusercontent.com/72334601/120465735-e8fb0e00-c3bb-11eb-8141-445c5a1e5757.png)

Any idea, as to why the pip is unable to upgrade..? Initially I thought there could be an error in the path, but the other installations are working fine with pip.

I am using python version 3.7.1 on jupyter.

**Comment by sgowroji** [comment]
Its working fine with 3.7.6 python version. I have tested the latest  [pose](https://google.github.io/mediapipe/solutions/pose.html#python-solution-api) sample code   in jupyter. After the installation you need to restart the kernal and try the above. Thanks!

**Comment by himanshu0195** [comment]
I am getting this error can someone help me out?
![Screenshot_20230224_034112](https://user-images.githubusercontent.com/81153365/221042360-a9471901-c22c-43d8-8c4c-9f0174c6a56d.png)

**Comment by KhoshalRam94** [comment]
**Error:** No Matching distribution found for Mediapipe.


![image](https://github.com/google/mediapipe/assets/130228791/b0d849df-5a80-4a8e-bf17-5247d57c7f1c)
