### ISSUE TITLE
Update glog to support stack trace on arm64

### ISSUE THREAD

**Issue by DeanIsMe** [google/mediapipe#2074]
I'm working with an arm64 processor on Linux.
When a graph aborts due to an error, the stack trace is not printed. E.g.
```
F20210523 21:24:28.664880 10807 packet.h:750] Packet::Get() failed: Expected a Packet of type: float, but received an empty Packet.
	*** Check failure stack trace: ***
Aborted (core dumped)
```

Or, if I run `google::InstallFailureSignalHandler();` in main(), I get
```
*** Check failure stack trace: ***
PC: @                0x0 (unknown)
Aborted (core dumped)
```

After some research, I found that arm64 stack trace is not supported on the glog version used in mediapipe, as indicated here:
https://github.com/google/glog/issues/531
Note that [this](https://github.com/google/glog/commit/0a2e5931bd5ff22fd3bf8999eb8ce776f159cda6) is the glog version referenced by the mediapipe WORKSPACE file.

arm64 stack trace is now supported in glog, as of [version 0.5.0](https://github.com/google/glog/releases/tag/v0.5.0).

**Are you able to update the glog dependency to 0.5.0 to enable stack trace on arm64 and hence ease development?**

**Comment by hadon** [comment]
Thanks for investigating the glog versions and limitations.  Maybe you can help me to validate MediaPipe with glog version 0.5.0.  Can you update the glog version in your mediapipe WORKSPACE file and verify that the newer version works ok and provides stack traces in your environment?  

I'm glad to start updating the mediapipe WORKSPACE file in the MediaPipe upstream repository.  I believe I will be updating target "com_github_google_glog" as follows:

# v0.5.0, 2021-05-07
http_archive(
    name = "com_github_google_glog",
    sha256 = "62efeb57ff70db9ea2129a16d0f908941e355d09d6d83c9f7b18557c0a7ab59e",
    strip_prefix = "glog-d516278b1cd33cd148e8989aec488b6049a4ca0b",
    urls = ["https://github.com/google/glog/archive/d516278b1cd33cd148e8989aec488b6049a4ca0b.zip"],
)

I will also need to update "com_github_glog_glog_no_gflags" and one patch to it, and have the update tested and reviewed.

**Comment by sgowroji** [comment]
Hi @DeanIsMe, Could you please check the above [comment](https://github.com/google/mediapipe/issues/2074#issuecomment-859962248). Thanks!

**Comment by sgowroji** [comment]
Hi @DeanIsMe, Could you please respond to the above comment. Thanks!

**Comment by DeanIsMe** [comment]
Sorry for the delay.
About a month ago I updated the glog version in my workspace file to:
http_archive(
    name = "com_github_google_glog",
    sha256 = "21bc744fb7f2fa701ee8db339ded7dce4f975d0d55837a97be7d46e8382dea5a",
    strip_prefix = "glog-0.5.0",
    urls = ["https://github.com/google/glog/archive/v0.5.0.zip"],
)
I then had huge problems compiling mediapipe examples. Even after reverting the glog version back to the mediapipe default, my mediapipe build process failed when linking OpenCV libs. I later had issues with the mediapipe examples opening the camera stream (which uses OpenCV).
I ended up spending about a day getting the mediapipe build & run process back to a functional state.

I could try this again and record more useful information about the failures, but I'll need to wait a week or 2 so that I have a free day again >_<

**Comment by DeanIsMe** [comment]
I changed the http_archive for com_github_glog_glog in WORKSPACE to the [comment above by hadon](https://github.com/google/mediapipe/issues/2074#issuecomment-859962248). When I tried to build a mediapipe project, this is the error that I received:

```
ERROR: /home/lounge/Lounge-client/Lounge_mediapipe/third_party/BUILD:22:11: no such package '@com_github_glog_glog//': The repository '@com_github_glog_glog' could not be resolved and referenced by '//third_party:glog'
ERROR: Analysis of target '//mediapipe/lounge:lounge_main' failed; build aborted: Analysis failed
INFO: Elapsed time: 3.628s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded, 5 targets configured)
```

**Comment by DkAhmRin** [comment]
I am facing a similar issue as @DeanIsMe 

When using mediapipe facemesh in a loop, first a warning about glog:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F20211111 12:28:54.792228 380909056 threadpool_pthread_impl.cc:51] Check failed: res == 0 (35 vs. 0) pthread_create failed
*** Check failure stack trace: ***
```

**Comment by sureshdagooglecom** [comment]
Hi @DeanIsMe ,
Are you still looking for the resolution on this issue.

**Comment by DeanIsMe** [comment]
Hi @sureshdagooglecom, I am not working with mediapipe for now. However, I think stack trace on ARM64 would be valuable to many users.

**Comment by kuaashish** [comment]
Hello @DeanIsMe,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
