### ISSUE TITLE
How can i extract keypoints into  json file ?

### ISSUE THREAD

**Issue by timtensor** [google/mediapipe#2077]
Hi I am using mediapipe holistic pose in python ? I was wondering if there is a flag or parameter that one can use to dump the 33 keypoints to a json file ?

**Comment by sgowroji** [comment]
Hi @timtensor, You can convert the landmarks into the dictionary and save them into a file using json.dump().

**Comment by timtensor** [comment]
@sgowroji thank you , is there an example that you might have used , that can be checked for reference ?

**Comment by sgowroji** [comment]
Hi @timtensor, Right i don't have any examples, But you can give a try with above comment and let me know if you face any error. Thanks!

**Comment by Atif-Anwer** [comment]
Followup .. ive made a small script that extracts the Mediapipe keypoints and exports them as OpenPose compatible JSON format.  
Hopefully this helps others aswell. 
[Mediapipe to Openpose JSON](https://github.com/Atif-Anwer/Mediapipe_to_OpenPose_JSON)
