### ISSUE TITLE
How to Improve The Performance by Shrink The Time on The Data Flow

### ISSUE THREAD

**Issue by joeshow79** [google/mediapipe#2078]
Hi There,

We plan to run MP on some low-end platform but we found that the performance degraded due to the  data flow in MP may take more time than the original implementation(not MP based). For the convinient, we tested the performance of HairSegmentation app on QC7350 platform, it showed that  the AddPacketToInputStreamInternal call took 1ms to 10ms (average 4ms).  Since it's the preview app, we plan to limit the processs time of each frame to 15ms, so it's critical to shrink the time spend on the data flow(AddPacketToInputStreamInternal call). Any idea to optimize it, thanks in advance!
![image](https://user-images.githubusercontent.com/15626897/119685972-73051d00-be78-11eb-8d84-310cc93791d3.png)

**Comment by mcclanahoochie** [comment]
Can you provide more details in profiling? 
- What tool did you use to measure? 
- Is this the performance of the first frame, or every single frame?
  -  (the first frame can be slower than the rest)
- Can you show more of the profiling results?
  -  (are there other long processes, or is AddPacketToInputStream the only one taking very long?)
- Can you verify that the app was built in `opt` mode ? ( `bazel build -c opt ...` )
- What is the overall FPS?

Mediapipe also provides ways to profile graphs (at a higher level) , [see here](https://google.github.io/mediapipe/tools/tracing_and_profiling.html) , and that may also be good to compare against.

**Comment by txf-** [comment]
> Mediapipe also provides ways to profile graphs (at a higher level) , [see here](https://google.github.io/mediapipe/tools/tracing_and_profiling.html) , and that may also be good to compare against.

Unfortunately Tracing seems to be broken at the moment.

**Comment by gunbuyidiu** [comment]
> Can you provide more details in profiling?
> 
> * What tool did you use to measure?
> * Is this the performance of the first frame, or every single frame?
>   
>   * (the first frame can be slower than the rest)
> * Can you show more of the profiling results?
>   
>   * (are there other long processes, or is AddPacketToInputStream the only one taking very long?)
> * Can you verify that the app was built in `opt` mode ? ( `bazel build -c opt ...` )
> * What is the overall FPS?
> 
> Mediapipe also provides ways to profile graphs (at a higher level) , [see here](https://google.github.io/mediapipe/tools/tracing_and_profiling.html) , and that may also be good to compare against.

hi mcclanahoochie, I'm a colleague of the author. In response to your question, my answer is as follows：

1.android systrace
2.every single frame
3.i'll upload a systrace file. [hairseggpu.zip](https://github.com/google/mediapipe/files/6637888/hairseggpu.zip)
4. use cmd like this: `bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/hairsegmentationgpu:hairsegmentationgpu`
5. less than 30fps, maybe 10fps...
6.We will try your suggestion

Hope this information is helpful to you.

**Comment by gunbuyidiu** [comment]
> > Mediapipe also provides ways to profile graphs (at a higher level) , [see here](https://google.github.io/mediapipe/tools/tracing_and_profiling.html) , and that may also be good to compare against.
> 
> Unfortunately Tracing seems to be broken at the moment, at least importing traces to the website.

i upoad a systrace file zip. look at my last comment, thx

**Comment by txf-** [comment]
> > > Mediapipe also provides ways to profile graphs (at a higher level) , [see here](https://google.github.io/mediapipe/tools/tracing_and_profiling.html) , and that may also be good to compare against.
> > 
> > 
> > Unfortunately Tracing seems to be broken at the moment, at least importing traces to the website.
> 
> i upoad a systrace file zip. look at my last comment, thx

I was referring to the built-in Mediapipe tracing tool. The one mentioned in that like.

**Comment by sgowroji** [comment]
Hi @joeshow79, Could you please respond to the above [comment](https://github.com/google/mediapipe/issues/2078#issuecomment-854951152). Thanks!
