### ISSUE TITLE
build failed,even the basic example hello world

### ISSUE THREAD

**Issue by Sara533** [google/mediapipe#208]
When I run the example on Ubuntu, it always failed.
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz, https://github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz] to /home/sunny/.cache/bazel/_bazel_sunny/cd8ad4f2794b178f6f1709ac05e5bf6e/external/org_tensorflow/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz: Read timed out
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz, https://github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz] to /home/sunny/.cache/bazel/_bazel_sunny/cd8ad4f2794b178f6f1709ac05e5bf6e/external/org_tensorflow/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz: Read timed out
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz, https://github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz] to /home/sunny/.cache/bazel/_bazel_sunny/cd8ad4f2794b178f6f1709ac05e5bf6e/external/org_tensorflow/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz: Read timed out
INFO: Elapsed time: 431.628s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by jiuqiant** [comment]
Can you do `bazel clean --expunge` to clean the cache first and retry the build command?

It seems like the actual error is "java.io.IOException: Error downloading". It might be temporarily network issue. If you are in mainland China, VPN probably can help you get ride of such issue caused by the firewall. See https://github.com/google/mediapipe/issues/3, https://github.com/google/mediapipe/issues/70, and https://github.com/google/mediapipe/issues/153

**Comment by Sara533** [comment]
@jiuqiant I have tried what you said above, but still failed with similar errors. I have used VPN.
An error occurred during the fetch of repository 'org_tensorflow':
   java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz, https://github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz] to /home/sunny/.cache/bazel/_bazel_sunny/e2409063e413b668f429c3bd336e2971/external/org_tensorflow/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz: Premature EOF

And I find many tools are http_archive defined in WORKSPACE file.Can I change to local_repository?
