### ISSUE TITLE
How to convert list of dictionaries to NormalizedLandmarklist

### ISSUE THREAD

**Issue by toz123** [google/mediapipe#2080]
I have run and collected data from tracked hands using MediaPipe Hands and stored the data in a separate csv file. I want to be able to play back the tracked data with a blank background. I was wondering if there is anyway in which the list of dictionaries could be converted back into a NormalizedLandmarklist so I can loop through them with MediaPipe to create a playback?

**Comment by sgowroji** [comment]
Hi @toz123, May be your are looking for [this](https://github.com/google/mediapipe/issues/2031#issuecomment-846123773). Try doing the same for Hands solution. Thanks

**Comment by sgowroji** [comment]
Hi @toz123, Could you please respond to my above [comment](https://github.com/google/mediapipe/issues/2080#issuecomment-849324102). Thanks!

**Comment by toz123** [comment]
Yes this solution worked, thank you!
