### ISSUE TITLE
Installing MediaPipe in PyCharm

### ISSUE THREAD

**Issue by Moronixo** [google/mediapipe#2081]
I'm using PyCharm for a project I'm working and I've been trying to install MediaPipe but I'm not sure how to go around it, could anyone possibly lend a hand on how to do it?

Any help is appreciated :)

**Comment by Rishikesh-Reddy** [comment]
Hello @Moronixo 

At the Bottom Left of a Pycharm Window you will find Python Packages
 click on it and in the search bar type **Mediapipe** 


![Screenshot 2021-05-27 041717](https://user-images.githubusercontent.com/76101044/119741009-83ca8880-bea2-11eb-8b5f-3d9c5235c50e.png)

**Comment by Moronixo** [comment]
Hi @Rishikesh-Reddy
Sorry if I'm being a pain and missing something obvious here but I can only see these:

![capure](https://user-images.githubusercontent.com/84026099/119743059-f4f94400-be80-11eb-97b3-c5e60df0a01f.PNG)
![capture2](https://user-images.githubusercontent.com/84026099/119743065-f62a7100-be80-11eb-88d4-ae6cb3fc7cb1.PNG)

**Comment by Moronixo** [comment]
Is this the same thing as looking at packages in the python interpreter? As there I cannot see MediaPipe in that

**Comment by Rishikesh-Reddy** [comment]
hello @Moronixo 

In pycharm enter `crtl+Alt+s` so that settings window is shown 

![Screenshot 2021-05-27 095330](https://user-images.githubusercontent.com/76101044/119765748-6f51b480-bed1-11eb-8fbb-6b8ac9300a66.png)

you can find the packages here you can add a package by clicking on the `+` and searching for the package and installing it


Glad if I could help 
Thank You

**Comment by Moronixo** [comment]
Sorry again but when I type MediaPipe into the search it comes up empty:
![image](https://user-images.githubusercontent.com/84026099/119835507-ccad2c00-bef8-11eb-8514-b36084c75516.png)

Could it be that I have a package installed already that is not supported with MediaPipe?

**Comment by Moronixo** [comment]
To point out I should have mentioned before is that I used Anaconda initially to download my packages.

**Comment by Moronixo** [comment]
I've managed to solve my issue, I realised it was using the Anaconda package manager while searching, unselecting I've managed to find it.

**Comment by younasm** [comment]
> 

i did the same but not working for me showing error.

```
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

I am using python version 3.10.6

**Comment by dubey2002** [comment]
Same issue i am also not able to install media pipe

**Comment by g-o-o-g-l-e** [comment]
I am having the same problem
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
I have the same error in #57,#58 and #59

**Comment by g-o-o-g-l-e** [comment]
I have version 3.12.1
