### ISSUE TITLE
How to use mediapipe on iOS?

### ISSUE THREAD

**Issue by cckv** [google/mediapipe#2084]
I have created an iOS project according to the tutorial, but I get an error when I run it:

Showing Recent Messages
1. /Users/apple/Desktop/Code/MediaPipe/mediapipe/mediapipe/examples/ios/facedetectioncpu/BUILD:34:16: //mediapipe/examples/ios/facedetectioncpu:FaceDetectionCpuApp_entitlements: missing input file'//mediapipe:provisioning_profile .mobileprovision'
2,
Showing Recent Messages
/Users/apple/Desktop/Code/MediaPipe/mediapipe/mediapipe/examples/ios/facedetectioncpu/BUILD:34:16 1 input file(s) do not exist
3. Showing Recent Messages
Build did NOT complete successfully
4.
Showing Recent Messages
/Users/apple/Desktop/Code/MediaPipe/mediePipe_ios/Mediapipe.xcodeproj/.tulsi/Scripts/bazel_build.py:581: Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.
This is my first question,

Another question is: How can I package it into a framework and use the ability of mediapipe in my project?

thanks！

**Comment by sgowroji** [comment]
Hi @cckv, For your first query look at [this](https://github.com/google/mediapipe/issues/995#issuecomment-672859117). And if you still not resolved, Please let us know at what step [here](https://google.github.io/mediapipe/getting_started/ios.html#mediapipe-on-ios) you are facing the error.

**Comment by cckv** [comment]
@sgowroji thanks, I will try it.

**Comment by cckv** [comment]
@sgowroji  i try it , but here is the error:
MacBook-Pro mediapipe % bazel build -c opt –config=ios_arm64 mediapipe/example/ios/handtrackinggpu:HandTrackingGpuApp
ERROR: Skipping '–config=ios_arm64': Bad target pattern '–config=ios_arm64': package names may contain A-Z, a-z, 0-9, or any of ' !"#$%&'()*+,-./;<=>?[]^_`{|}~' (most 7-bit ascii characters except 0-31, 127, ':', or '\')
ERROR: Bad target pattern '–config=ios_arm64': package names may contain A-Z, a-z, 0-9, or any of ' !"#$%&'()*+,-./;<=>?[]^_`{|}~' (most 7-bit ascii characters except 0-31, 127, ':', or '\')
INFO: Elapsed time: 0.281s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by cckv** [comment]
@sgowroji 
when i build, here has a error:
ERROR: /Users/apple/Desktop/cckv/Code/MediaPipe/mediapipe/mediapipe/examples/ios/iristrackinggpu/BUILD:34:16: in entitlements rule //mediapipe/examples/ios/iristrackinggpu:IrisTrackingGpuApp_entitlements: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_cckv/eb5acd1c8a9a78619e586b58525642aa/external/build_bazel_rules_apple/apple/internal/entitlement_rules.bzl", line 223, column 40, in _entitlements_impl
		bundling_support.validate_bundle_id(bundle_id)
	File "/private/var/tmp/_bazel_cckv/eb5acd1c8a9a78619e586b58525642aa/external/build_bazel_rules_apple/apple/internal/bundling_support.bzl", line 92, column 25, in _validate_bundle_id
		fail("Invalid character(s) in bundle_id: \"%s\"" % bundle_id)
Error in fail: Invalid character(s) in bundle_id: "*SEE_IOS_INSTRUCTIONS*.mediapipe.examples.IrisTrackingGpu"
ERROR: Analysis of aspect '@tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect of //mediapipe/examples/ios/iristrackinggpu:IrisTrackingGpuApp' failed; build aborted: Analysis of target '//mediapipe/examples/ios/iristrackinggpu:IrisTrackingGpuApp_entitlements' failed
General failure: Bazel aspects could not be built.

**Comment by sgowroji** [comment]
Hi @cckv, Could you please share your code repo or changes.

**Comment by cckv** [comment]
thank you for your reply，but code repo is too large.

**Comment by cckv** [comment]
@sgowroji here has a new error:
![image](https://user-images.githubusercontent.com/17642551/119823566-9509a880-bf27-11eb-9235-0fea0631331f.png)

**Comment by cckv** [comment]
@sgowroji Thank you very much, I have successfully run the demo, but how can I apply mediapipe to my own project? Are there related documents for reference?

**Comment by sgowroji** [comment]
Hi @cckv, Please check  [here](https://google.github.io/mediapipe/getting_started/hello_world_ios.html#hello-world-on-ios)

**Comment by sgowroji** [comment]
Hi @cckv, Did you able to build the code or still facing any error?

**Comment by cckv** [comment]
build a framework is so complex for a iOS developer, Gave up temporarily!

**Comment by IceFloe** [comment]
@cckv look at my example here. I did it base on an article. https://github.com/google/mediapipe/issues/2132

**Comment by sgowroji** [comment]
That's great for sharing with the community. We are closing this issue now. Thanks!

**Comment by CheungBH** [comment]
> @sgowroji Thank you very much, I have successfully run the demo, but how can I apply mediapipe to my own project? Are there related documents for reference?

What's your solution to this problem? I also encountered it
