### ISSUE TITLE
Hello , thank you for opening a thread on this.

### ISSUE THREAD

**Issue by ViWhiVN** [google/mediapipe#2087]
Hello , thank you for opening a thread on this.
Is https://github.com/tensorflow/tfjs-models/blob/master/facemesh/mesh_map.jpg also the index order in the landmark array that gets generated for plotting ?

I want to distinguish between the left side and right side of a face while turning ?
However, the coordinates derived from the facemesh for left and right corner of the eyes seem to be a hardcoded set.

Even when my right side of face occupies the screen, the left eye corner coordinates are captured.

Any help would be highly appreciated.

Thank you,
Aarushi

_Originally posted by @aarushi-mittal in https://github.com/google/mediapipe/issues/1615#issuecomment-789876709_

**Comment by kostyaby** [comment]
Hey @ViWhiVN,

> Is https://github.com/tensorflow/tfjs-models/blob/master/facemesh/mesh_map.jpg also the index order in the landmark array that gets generated for plotting?

Yes, it is. This image is a visualization of corresponding face landmarks UV coordinates.

> I want to distinguish between the left side and right side of a face while turning? However, the coordinates derived from the facemesh for left and right corner of the eyes seem to be a hardcoded set.

A face landmark at any given index (from 0 to 467) _always_ corresponds to the same semantic location on a face. Like, if face landmark no. 1 is the tip of the nose it'll always be the tip of the nose no matter how a user moves their face. The same is true for any other landmark

> Even when my right side of face occupies the screen, the left eye corner coordinates are captured.

It's important to distinguish two scenarios: 

1) Your definition of "left" is different from the [UV map](https://github.com/tensorflow/tfjs-models/blob/master/facemesh/mesh_map.jpg) definition of "left", but it's consistent over all tracked result (i.e. your "left side of the face" is always the UV map's "right side of the face"). In this case, I'd suggest you to account for this discrepancy once in your client code and it'll always be working for you from that moment

2) Your definition of "left" is different from the [UV map](https://github.com/tensorflow/tfjs-models/blob/master/facemesh/mesh_map.jpg) definition of "left", but only in certain images or video frames. In this case, our API is in a very big trouble as it'd mean it fails to provide guarantees it should be providing. I personally never observed this situation, so if that's what you observe then please provide a reproducible example so we can debug this further

Thanks!

**Comment by sgowroji** [comment]
Hi @ViWhiVN, Did you go through  the above comment. Thanks!
