### ISSUE TITLE
No matching distribution found for mediapipe

### ISSUE THREAD

**Issue by PapaPythonAndWeb** [google/mediapipe#2088]
I'm trying install mediapipe on conda terminal (python version = 3.7.3) and I'm receiving an error "No matching distribution found for mediapipe", is there any way from which I can fix this and I'd really appreciate if mediapipe supports python 2

**Comment by sgowroji** [comment]
Hi @PapaPythonAndWeb, Which OS are you trying the above installation. Thanks

**Comment by sgowroji** [comment]
Hi @PapaPythonAndWeb, Could you please respond to my above [comment](https://github.com/google/mediapipe/issues/2088#issuecomment-851137999). Thanks!

**Comment by PapaPythonAndWeb** [comment]
Windows 7

**Comment by sgowroji** [comment]
Hi @PapaPythonAndWeb, Any 64-bit Python3.7+ should be fine. Please refer [this](https://github.com/google/mediapipe/issues/2005#issuecomment-835846942) for more understanding
