### ISSUE TITLE
Other RGB Hand Pose Estimators

### ISSUE THREAD

**Issue by alexriedel1** [google/mediapipe#2089]
Hello, in your paragraph `Overview `https://google.github.io/mediapipe/solutions/hands.html#overview you state that there are other SOTA hand tracking solution, that rely on heavy GPUs. 

Can you give some informations about better achieving 21 3D hand keypoint from RGB models that are available and ready to use (on Desktop, eg. pytorch)?

Or are there any slower but more elaborate models for media pipe available to get hand keypoints? 

I'm working on a very precise gesture recognizer based on skeletal data so any more precise model would be welcome..

Thanks in advance!

**Comment by sgowroji** [comment]
Hi @alexriedel1, Could you please elaborate your use case with complete details. Thanks!

**Comment by alexriedel1** [comment]
I'm actually asking for other "out-of-the-box" solutions to track the 21 3D hand keypoints, that might be slower, but more accurate than mediapipe.

**Comment by sn1c3** [comment]
@alexriedel1 did you find any?

**Comment by alexriedel1** [comment]
@sn1c3 : let me share my findings:
https://github.com/CMU-Perceptual-Computing-Lab/openpose
-only 2D, full body poses -> very slow

https://github.com/NVIDIA-AI-IOT/trt_pose_hand
-only 2D

https://github.com/Elody-07/AWR-Adaptive-Weighting-Regression
-takes in depth images

https://github.com/3d-hand-shape/hand-graph-cnn
-might be suitable but pretrained models might be inaccurate due to low training set size (only optimized for benchmarking..)
