### ISSUE TITLE
new anchor file for new anchors (896)

### ISSUE THREAD

**Issue by mlizhardy** [google/mediapipe#2090]
Hi there, can you add a new anchor golden file for the new anchors (there are now 896 of them, not 2944), similar to https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/testdata/anchor_golden_file_0.txt ?

**Comment by sgowroji** [comment]
Hi @mlizhardy, Could you please provide more details for the above Request. Thanks!

**Comment by mlizhardy** [comment]
My understanding is the golden file is used to check that the ssd anchors generated in the pipeline are correct.  However with the current palm_detection.tflite file requires anchors of size 896.  None of the golden anchors files have 896 anchors.  I would like to check that the ssd anchors I have generated match the anchors palm_detection.tflite expects, so I'd like a golden file which has the up to date (896) ssd anchors so I can compare values.

**Comment by mlizhardy** [comment]
ah nevermind, if I use a 256 x 256 input instead of 128 x 128 there are 2944 anchors.
