### ISSUE TITLE
No file "landmark.pb.h"

### ISSUE THREAD

**Issue by kbh1860** [google/mediapipe#2091]
I run this script 
`sudo bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_gpu`

But I got this error
`fatal error: mediapipe/framework/formats/landmark.pb.h: No such file or directory
 #include "mediapipe/framework/formats/landmark.pb.h"`

There is no one having landmark.pb.h file?

Can I download that file? :D

**Comment by sgowroji** [comment]
Hi @kbh1860, Could you please provide the steps to reproduce the above error. And let us know if you have updated any of the code changes. Thanks!

**Comment by zcl912** [comment]
> Hi @kbh1860, Could you please provide the steps to reproduce the above error. And let us know if you have updated any of the code changes. Thanks!

yeah, i met the error too, i just add  #include "mediapipe/framework/formats/landmark.pb.h"  to demo_run_graph_mai.cc, and  modify the BUILD(in /desktop/pose_tracking/BUILD) like:
licenses(["notice"])

package(default_visibility = ["//mediapipe/examples:__subpackages__"])

cc_binary(
    name = "pose_tracking_cpu",
    # srcs = ["landmark.pb.cc","landmark.pb.h"],
    deps = [
        "//mediapipe/examples/desktop:demo_run_graph_main",
        "//mediapipe/graphs/pose_tracking:pose_tracking_cpu_deps",
         "//mediapipe/framework/formats:landmark_cc_proto",
    ],
)

# Linux only
cc_binary(
    name = "pose_tracking_gpu",
    deps = [
        "//mediapipe/examples/desktop:demo_run_graph_main_gpu",
        "//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps",
    ],
)

**Comment by zcl912** [comment]
> I run this script
> `sudo bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_gpu`
> 
> But I got this error
> `fatal error: mediapipe/framework/formats/landmark.pb.h: No such file or directory #include "mediapipe/framework/formats/landmark.pb.h"`
> 
> There is no one having landmark.pb.h file?
> 
> Can I download that file? :D

hi,  the error solved? can you tell me how to solve it
