### ISSUE TITLE
Extracting Handlandmarks in Android??

### ISSUE THREAD

**Issue by fulankun1412** [google/mediapipe#2092]
Hello, is there any way to extract handlandmarks from the Input video stream like what we can do in python? sorry i'm still new in Android development.

![Screenshot 2021-05-29 084032](https://user-images.githubusercontent.com/16248869/120054334-8fac7b00-c059-11eb-895a-18dd0e3d3b09.jpg)

**Comment by PrinceP** [comment]
This can help. 

https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java

**Comment by fulankun1412** [comment]
Thank you but which code do you point to for the handlandmarks extraction? and how we can do this per frame in android?

**Comment by PrinceP** [comment]
https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L53

processor.addPacketCallback will run for every frame

**Comment by fulankun1412** [comment]
Oh Right, i got the idea and able to extract the coordinates.
