### ISSUE TITLE
How to choose different pose landmark TF models?？such as  pose_landmark_lite.tflite,pose_landmark_heavy.tflite

### ISSUE THREAD

**Issue by DandyLorenz** [google/mediapipe#2093]
For example, the new version of pose tracking gpu supports the compilation of different weight models，Default TF model is pose_landmark_full.tflite，How can I choose pose_landmark_lite.tflite or pose_landmark_heavy.tflite？
I tried to change the file name of pose_landmark_lite.tflite to pose_landmark_full.tflite, this is not necessarily the correct way, please guide me where to modify

**Comment by sgowroji** [comment]
Hi @DandyLorenz, Could you please elaborate your use case with complete details. Thanks!

**Comment by bhaskar2728** [comment]
Hi @DandyLorenz , I don't know much about all the files present in mediapipe repository but this file https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_model_loader.pbtxt is used for selecting model, here by default you will see select:1 which means it's using the full model.If you are doing it in android using aar,I tried changing it to select:2 and then rebuilding the aar file and graph.After this,I added the heavy model's tflite file in the assets folder instead of the full one.And then it worked.
I think there is one parameter model_complexity which is passed somewhere,through that also we can change the model but I wasn't able to figure out that.
Hope it helps!

**Comment by SRDdev** [comment]
Hey @DandyLorenz, I would like to work on this issue, I might need some guidance as I am new at this.
So can I please work on this issue !!

**Comment by DandyLorenz** [comment]
> Hi @DandyLorenz , I don't know much about all the files present in mediapipe repository but this file https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_model_loader.pbtxt is used for selecting model, here by default you will see select:1 which means it's using the full model.If you are doing it in android using aar,I tried changing it to select:2 and then rebuilding the aar file and graph.After this,I added the heavy model's tflite file in the assets folder instead of the full one.And then it worked.
> I think there is one parameter model_complexity which is passed somewhere,through that also we can change the model but I wasn't able to figure out that.
> Hope it helps!

Thank you for your reply. I've seen it before. Your reply makes me sure that I can do it. I think it is most likely correct

**Comment by DandyLorenz** [comment]
> Hey @DandyLorenz, I would like to work on this issue, I might need some guidance as I am new at this.
> So can I please work on this issue !!

Yes, you can ask your question in time. I will close the current issue after a certain period of time

**Comment by MarioCavero** [comment]
When using mediapipe and pose detection, there is:
```
with mp_pose.Pose(
    static_image_mode=True,
    model_complexity=0,
	    enable_segmentation=False,
    min_detection_confidence=0.5) as pose:
```
 , being `model_complexity` the model it will use. Mediapipe goes to search the models in `/usr/local/lib/python3.7/dist-packages/mediapipe/modules/pose_landmark` and `/usr/local/lib/python3.7/dist-packages/mediapipe/modules/pose_detection`. 
 See:
```
mk@mk:/usr/local/lib/python3.7/dist-packages/mediapipe/modules/pose_landmark$ ls
pose_landmark_cpu.binarypb  pose_landmark_heavy.tflite
pose_landmark_full.tflite   pose_landmark_lite.tflite

```
You can either [download them manually](https://google.github.io/mediapipe/solutions/models.html#pose) and move them into the specific directory, OR they will automatically be downloaded if not found. **Care:** an old version was being used, pulling from github, and it was not working anymore. Make sure to update it ([Check this out](https://github.com/google/mediapipe/issues/3698#issuecomment-1247905371)). the file is [download_utils.py](https://github.com/google/mediapipe/blob/d3f98334bfe533a57ec2c2fa85294c21e25fe0af/mediapipe/python/solutions/download_utils.py) in `/usr/local/lib/python3.7/dist-packages/mediapipe/python/solutions/download_utils.py`
   
Depending on the value for model_complexity, it will use (previously download it if not found) one model or another. Hope it helps, sorry I'm late!
