### ISSUE TITLE
Is it possible to delete the console message of "INFO:"?

### ISSUE THREAD

**Issue by Hukasan** [google/mediapipe#2094]
Thank you for making a great library.
python3.9.0
mediapipe 0.8.4.2
windows 10 home

This now happens after updating the mediapipe version
When I run the code below, I get a lot of messages starting with "INFO:" like the console in the image, which is very annoying.
It may not be a problem that stays in this library, but please let me know if there is a solution.

```python
import mediapipe as mp
import cv2 as cv


holistic = mp.solutions.holistic.Holistic()

image = cv.imread("test.png")
holistic.process(image)
```
![image](https://user-images.githubusercontent.com/66109030/120058026-af0bce00-c082-11eb-8eee-0f36f85fdc41.png)

**Comment by brucechou1983** [comment]
The logging comes from [tflite](https://github.com/tensorflow/tensorflow/blob/48b171d0ab2a8f35a6d646fc59e44c188a1925e1/tensorflow/lite/core/subgraph.cc#L389)

If you want to mute this, you can create a custom git patch file like "org_tensorflow_mute_logging.diff" and add it to "patches" section of "org_tensorflow" repository.

**Comment by jiuqiant** [comment]
See https://github.com/google/mediapipe/issues/2119#issuecomment-860927310.

**Comment by sgowroji** [comment]
Hi @Hukasan, Could you please respond to the above comment. Thanks!
