### ISSUE TITLE
cannot run program bazel

### ISSUE THREAD

**Issue by salier** [google/mediapipe#2095]
![image](https://user-images.githubusercontent.com/28691601/120069145-f0b66c00-c0b6-11eb-9829-7b4a2b48d455.png)
I'm following the tutorial https://google.github.io/mediapipe/getting_started/android.html#option-2-build-with-bazel-in-android-studio
![image](https://user-images.githubusercontent.com/28691601/120069205-3d9a4280-c0b7-11eb-9a1f-fff197efe3cc.png)

The SDK and NDK problems are not shown. However, they are still unable to compile normally

**Comment by salier** [comment]
![image](https://user-images.githubusercontent.com/28691601/120133071-0c785a00-c1fe-11eb-845c-412622e8e5a3.png)

**Comment by salier** [comment]
![image](https://user-images.githubusercontent.com/28691601/120138333-dab8c080-c208-11eb-999e-ea803d009dda.png)
It seems that the import failed.Log means missing file. But I didn't find this file missing.

**Comment by sgowroji** [comment]
Hi @salier, Could you please provide the OS details, Bazel version  and Android studio version.

**Comment by salier** [comment]
Version information
AndroidStudio: 4.2.1
Platform: Windows 10 10.0
Bazel plugin: 2021.05.12.1.5

**Comment by salier** [comment]
I tried to use Android 28-29-30 SDK (but it didn't return to normal)
I also tried to download the code library directly or use git to synchronize the code base. However, this problem still occurred.
Maybe it's bazel's problem？

**Comment by sgowroji** [comment]
Hi @salier, As we mentioned in https://google.github.io/mediapipe/getting_started/install#installing-on-windows, MediaPipe doesn't support building its Android apps on native Windows because of the limited Bazel support for Android on native Windows. Please try WSL instead. You can find the instructions at https://google.github.io/mediapipe/getting_started/install#installing-on-windows-subsystem-for-linux-wsl.

**Comment by salier** [comment]
I understand. This means that mediapipe cannot be enabled on windows? Or can't I compile Android studio on windows? My understanding is that it can be used in Android devices compiled from Windows PC, but not on Windows PC

**Comment by sgowroji** [comment]
Hi @salier, MediaPipe doesn't support building its Android apps on native Windows because of the limited Bazel support for Android on native Windows. Please check above [comment](https://github.com/google/mediapipe/issues/2095#issuecomment-851229725) with WSL.
