### ISSUE TITLE
Inaccurate hand detection

### ISSUE THREAD

**Issue by hirashahid9** [google/mediapipe#2096]
I have used Google Mediapipe Hands for Multihand Tracking. However, when there is no hand in the frame or a single hand, it detects other objects(like print on T shirt or hair ) as hands and shows bounding box against it. I am afraid this will result in incorrect landmark extraction.

**Comment by sgowroji** [comment]
Hi @hirashahid9, Could you please provide a video for the above scenario and in which platform are you facing it. Thanks!

**Comment by hirashahid9** [comment]
![image](https://user-images.githubusercontent.com/55246052/120887493-a714d680-c60c-11eb-86ad-60b145bbc9ee.png)
@sgowroji You can see the problem in the image above. I am using Linux.

**Comment by sgowroji** [comment]
Hi @hirashahid9, We are continuously improving our solution models. Can you retest the same with the latest release and let us know if you still see the same above observation. If you are able to reproduce with the latest, Can you share the steps  to reproduce it . Thanks!
