### ISSUE TITLE
When there are many people, how to get the hand of the person in front ?

### ISSUE THREAD

**Issue by crf-git** [google/mediapipe#2099]

**Comment by sgowroji** [comment]
Hi @crf-git, Could you please elaborate your use case with more details  and  any screenshot or video. Thanks!

**Comment by crf-git** [comment]
When I set maxNumHands to 1, I want to get only the hand closest to the camera.

eg: 
![test_img](https://dphoto-qiniu.dface.cn/test_img.png)

**Comment by crf-git** [comment]
When I set maxNumHands to 1, I want to get only the hand closest to the camera.

eg: [test_img](https://dphoto-qiniu.dface.cn/test_img.png)

**Comment by crf-git** [comment]
> When I set maxNumHands to 1, I want to get only the hand closest to the camera.
> 
> eg: [test_img](https://dphoto-qiniu.dface.cn/test_img.png)

Because when there are many people in front of the camera, the hands behind will cause interference.

**Comment by sn1c3** [comment]
Assuming the depth perception of mediapipe works accurate:
1. Detect all hands in a picture with a bounding box
2. For each bounding box use mediapipe hand recognition
3. Only display the hand closest to the camera

It's a bit of a hustle, but could work for you

**Comment by eknight7** [comment]
Hi @crf-git,
This is an interesting problem. Here are a couple ideas:

1. Hands closer to the camera are generally larger in size. Using the 21 hand landmark coordinates, write a function to compute the surface area of the hand, and pick the one with the largest area.
2. As @sn1c3 [suggests](https://github.com/google/mediapipe/issues/2099#issuecomment-856572227), investigate the usefulness of the `z` coordinates in choosing the hand closest to the camera. There is a relevant discussion about Z coordinates here: https://github.com/google/mediapipe/issues/742#issuecomment-639104199

**Comment by sgowroji** [comment]
Hi @crf-git, Did you get a chance to go through the above comment. Thanks!

**Comment by sgowroji** [comment]
Hi @crf-git, Could you please respond to above [comment.](https://github.com/google/mediapipe/issues/2099#issuecomment-859738093)  Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity. Thanks!
