### ISSUE TITLE
question about the difference between paper and given model

### ISSUE THREAD

**Issue by flyingmrwang** [google/mediapipe#21]
I am learning the tricks of model designing in the papers of BlazeFace and HairSegment. It is described that large kernel like 5x5 is used to improve efficiency. And DenseNet layers are added to improve accuracy. While I failed to find these designs in your given tflite models under this repo. Can anyone explain it a little bit?

**Comment by bazarevsky** [comment]
Thanks for your interest in our models. 
You are correct in that the models provided do not exactly follow the architectures outlined in the corresponding papers. The architecture development has continued between the submission of the papers and the release of the models, but you can still refer to the original papers for the reference on the training pipeline and data sourcing perspectives which mostly remained the same.

We plan to continuously update our models with newer and better versions, so please stay on touch.

**Comment by jiuqiant** [comment]
@flyingmrwang Please let us know if you have more questions. The discussion can be continued at [MediaPipe's google group](https://groups.google.com/forum/#!topic/mediapipe/lIUNgK9RRFI).
