### ISSUE TITLE
Windows平台上AS上利用Baze导入工程文件，一直报错，编译不过

### ISSUE THREAD

**Issue by rockygao123** [google/mediapipe#210]
![image](https://user-images.githubusercontent.com/26377223/68000258-59025900-fc9a-11e9-8f3b-4465d1e52178.png)

**Comment by jiuqiant** [comment]
Similar to https://github.com/google/mediapipe/issues/165, https://github.com/google/mediapipe/issues/137, https://github.com/google/mediapipe/issues/91, https://github.com/google/mediapipe/issues/113, and https://github.com/google/mediapipe/issues/126. Unfortunately, MediaPipe doesn't support Windows. If you are only interested in Windows, we support Windows Subsystem for Linux. You can find how to set up MediaPipe in WSL [here](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows-subsystem-for-linux-wsl).

**Comment by mgyong** [comment]
@rockygao123 We have released [MediaPipe on Windows](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows) with [v0.7.5](https://github.com/google/mediapipe/releases/tag/v0.7.5)
Please check it out and give us feedback
