### ISSUE TITLE
invalid character when build through bazel in cmd for any example 

### ISSUE THREAD

**Issue by JamieGB92** [google/mediapipe#2100]
been trying to track down this issue for about 2 weeks and i cannot. i will say the choice by google to use bazel and not supply a static lib still baffles me. 

the reason i am using cmd is msys has trouble bashing with bazel 

 when ever i go to build any example i get these errors. 
i am not using rich text editors 

ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:21:9: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:21:32: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:22:10: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:22:36: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:24:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:24:3: syntax error at '//': expected expression
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:24:22: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:27:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:27:45: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:28:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:28:52: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:29:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:29:34: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:30:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:30:36: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:31:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:31:3: invalid character: '@'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:31:30: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:32:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:32:3: invalid character: '@'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:32:33: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:33:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:33:46: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:34:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:34:39: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:35:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:35:44: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:36:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:36:51: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:37:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:37:41: invalid character: 'ö'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:38:2: invalid character: 'ô'
ERROR: C:/mediapipe/mediapipe/mediapipe/calculators/util/BUILD:38:44: invalid character: 'ö'

**Comment by sgowroji** [comment]
Hi @JamieGB92, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by JamieGB92** [comment]
cmd: bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:/Python/Python39/python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu 

all files are unmodified other than the inital building of the hello world example

**Comment by JamieGB92** [comment]
hey does anyone have an update?

**Comment by sgowroji** [comment]
Hi @JamieGB92, Did you able to build and run the [helloworld](https://google.github.io/mediapipe/getting_started/cpp.html#building-c-command-line-example-apps) desktop ?

**Comment by JamieCopelandFikaeEnt** [comment]
yes i am able to build the hello world example but i cannot build the hand tracking example

**Comment by sureshdagooglecom** [comment]
Hi @JamieGB92 ,
This issue can be resolved in latest version of MediaPipe ,could you please check and close this issue.
