### ISSUE TITLE
.so files created from MediaPipe code crash with a protobuf error when loaded on Ubuntu 21.04 x86_64

### ISSUE THREAD

**Issue by LKay42** [google/mediapipe#2103]
I'm trying to build a standalone, `dlopen` loadable, GPU accelerated .so of pose estimation on Linux (Ubuntu 21.04 x86_64). However, the moment the .so is loaded using `dlopen`, I end up with a **protobuf** crash. It doesn't even get to my code.

I've had a similar problem with TensorFlow before, it happened because protobuf got linked multiple times. This time, I'm sure it's not coming from my code (because there's close to none), so it's probably happening somewhere inside MediaPipe. Or is what I'm doing not supported yet? I saw that AARs are supported, so desktop .so files should work, shouldn't they? 

Here's a snippet from GDB and the rest of the stuff needed to reproduce this bug.

GDB:
```
#0  0x00007ffff76ac9b7 in google::protobuf::internal::AddDescriptors(google::protobuf::internal::DescriptorTable const*) ()
    at /home/lkay/Programming/motion_tracking/mediapipe/bazel-bin/mediapipe/fnt/libfntmotion.so
#1  0x00007ffff7fda96e in  () at /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7fdaa58 in  () at /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7ca92e5 in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:182
#4  0x00007ffff7fdf11a in  () at /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff7ca9288 in __GI__dl_catch_exception (exception=0x7fffffffd4c0, operate=0x7ffff7fdece0, args=0x7fffffffd4e0) at dl-error-skeleton.c:208
#6  0x00007ffff7fde6ed in  () at /lib64/ld-linux-x86-64.so.2
#7  0x00007ffff7f9534c in dlopen_doit (a=a@entry=0x7fffffffd710) at dlopen.c:66
#8  0x00007ffff7ca9288 in __GI__dl_catch_exception (exception=exception@entry=0x7fffffffd6b0, operate=0x7ffff7f952f0 <dlopen_doit>, args=0x7fffffffd710) at dl-error-skeleton.c:208
#9  0x00007ffff7ca9353 in __GI__dl_catch_error (objname=0x55555566b2d0, errstring=0x55555566b2d8, mallocedp=0x55555566b2c8, operate=<optimized out>, args=<optimized out>)
    at dl-error-skeleton.c:227
#10 0x00007ffff7f95b89 in _dlerror_run (operate=operate@entry=0x7ffff7f952f0 <dlopen_doit>, args=args@entry=0x7fffffffd710) at dlerror.c:170
#11 0x00007ffff7f953d8 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#12 0x00005555555602d9 in main() () at ../src/motionController/main.cpp:25
```

This is the BUILD file that I use to build the so:
```
licenses(["notice"])

package(default_visibility = [
    "//visibility:public",
])

cc_binary(
    name = "libfntmotion.so",
    linkshared=True,
    deps = [
        "//mediapipe/fnt:fnt_motion_lib",
    ],
)

cc_library(
    name = "fnt_motion_lib",
    alwayslink=True,
    srcs = [
        "fnt_motion_lib.cc",
    ],
    hdrs = [
        "fnt_motion_lib.h",
    ],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/formats:image_frame",
        "//mediapipe/framework/formats:image_frame_opencv",
        "//mediapipe/framework/port:file_helpers",
        "//mediapipe/framework/port:opencv_highgui",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:opencv_video",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
        "//mediapipe/gpu:gl_calculator_helper",
        "//mediapipe/gpu:gpu_buffer",
        "//mediapipe/gpu:gpu_shared_data_internal",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps",
    ],
)
```
As you can see, I'm just reusing the dependencies that are used to build the mediapipe examples. Replacing the pose tracking stuff, with, say, hands or face mesh, causes the exact same problems.

The "library" code in `fnt_motion_lib` files is empty for now. Eventually, it will contain code based on `mediapipe/examples/desktop/demo_run_graph_main_gpu.cc`, however, none of that is needed to reproduce this bug.

fnt_motion_lib.h
```
#ifndef FNT_MOTION_LIB_HPP
#define FNT_MOTION_LIB_HPP

#ifdef __cplusplus
extern "C" {
#endif

// TODO the actual library code

#ifdef __cplusplus
}
#endif

#endif // FNT_MOTION_LIB_HPP
```

fnt_motion_lib.cc
```
#include "fnt_motion_lib.h"
```

This is the main.cpp of the program that attempts to load the so file. I build it with CMake. I can't use Bazel because the .so will be loaded by a project that uses CMake. I think that you can use whatever you want to build it. After all the crash will happen during the dlopen call.
```
#include <iostream>
#include <dlfcn.h>

int main() {
    std::cout << "HI, I start!\n";
    
    void* fntLib = dlopen("/home/lkay/Programming/motion_tracking/mediapipe/bazel-bin/mediapipe/fnt/libfntmotion.so", RTLD_NOW | RTLD_LOCAL);
    if (fntLib == nullptr) {
        std::cerr << "OOPS, .so load failed!!!\n";
        return 1;
    }
    
    std::cout << "YAY! .so loaded!";
    
    dlclose(fntLib);
    
    return 0;
}
```

**Comment by hadon** [comment]
I imagine this crash may occur whenever the MediaPipe protobufs are linked into a .so and opened with dlopen, at least with your toolchain and platform, and perhaps with any protobufs.  Does that sound plausible to you?  If you can, would you help me to narrow down this issue by building a .so with just a few protobufs and see if the protobuf initialization still fails.  If it does, I can try to reproduce that narrower problem and help to diagnose or work around it.

**Comment by sgowroji** [comment]
Hi @LKay42, Could you please respond to the above [comment](https://github.com/google/mediapipe/issues/2103#issuecomment-860367076). Thanks!
