### ISSUE TITLE
Capturing more forehead area with FaceMesh

### ISSUE THREAD

**Issue by dylandao99** [google/mediapipe#2104]
Hi,

My team is experimenting with Mediapipe FaceMesh for identifying face sub-regions (cheek, forehead, etc.). This works fairly well for the cheeks, but it tends to miss a lot of forehead area for people with larger foreheads.

I've skimmed over the FaceMesh paper, and my assumption is that additional landmarks on the forehead cannot be captured without retraining the model. Are there any Mediapipe models that cover a larger forehead area, or a coarse model of the full head? Otherwise, what techniques are generally used to extrapolate forehead area for full-face effects?

Thanks!
Dylan

![image](https://user-images.githubusercontent.com/13226295/120240699-30a05f00-c22f-11eb-97a7-71083629e80f.png)

**Comment by ldingemans** [comment]
I am also interested in this, is there by any chance an update on this issue?

**Comment by longerking** [comment]
I also look forward to the feedback of this issue.

**Comment by ivan-grishchenko** [comment]
Hi, unfortunately we don't have models that include more landmarks on the forehead.
One of the options would be to use a 3D model of a head that has forehead part you need, get mapping between this head model and Face Mesh from MediaPipe and the align 3D head with Face Mesh landmarks (using for example Procrustes analysis, check [face geometry module](https://google.github.io/mediapipe/solutions/face_mesh#face-geometry-module)).

**Comment by MoatazNoaman2001** [comment]
i would like to see if there is fore head land mark as it will help in more neural network studies
