### ISSUE TITLE
hi i want to know iris's real size

### ISSUE THREAD

**Issue by bwjoe** [google/mediapipe#2106]
hi. thank you for your works.

1. i make [iris_tracking aar] 
2. i build with [iris_tracking aar]  in new android studio project with "mediapipe\examples\android\src\java\com\google\mediapipe\apps\basic\MainActivity.java" and "mediapipe\examples\android\src\java\com\google\mediapipe\apps\iristrackinggpu\MainActivity.java" .

3. finally i can get the face landmarks data including iris from following code..("mediapipe\examples\android\src\java\com\google\mediapipe\apps\iristrackinggpu\MainActivity.java" )

byte[] landmarksRaw = PacketGetter.getProtoBytes(packet);
            try {
              NormalizedLandmarkList landmarks = NormalizedLandmarkList.parseFrom(landmarksRaw);
:
:

but that i really want is 
1. img's iris real size
2. img's iris pixel size

because if i know that , i can know really size per pixel . it's my goal

so.. how can i get that infomation? plz something commet..

**Comment by sgowroji** [comment]
Hi @bwjoe, You wanted the Iris size through android platform?

**Comment by bwjoe** [comment]
yes.
real size and ( pixel size or pixel coordinate?)

**Comment by jiuqiant** [comment]
Please assign this to the iris owners. Thanks.

**Comment by bwjoe** [comment]
hello thanks you for response

finally i found a following code in "iris_to_depth_calculator.cc"

[
// Avergae fixed iris size across human beings.
constexpr float kIrisSizeInMM = 11.8;
].
real iris's size is fixed by "11.8"


just i thought vaguely : "maybe i can get real iris size by tf.".  
i misundestand.

thank you for your all regards.
something i have any another questions. i will write other issue. thank you
