### ISSUE TITLE
"python3 setup.py bdist_wheel" error in RaspberryPi4 with Raspbian

### ISSUE THREAD

**Issue by hhajae** [google/mediapipe#2107]
help me. 
I am using "https://github.com/jiuqiant/mediapipe_python_aarch64" and "https://github.com/superuser789/MediaPipe-on-RaspberryPi#readme" guide to install mediapipe in Rasberrypi4 with Raspbian.

When I ran "python3 setup.py gen_protos && python3 setup.py bdist_wheel",
```

/home/pi/mediapipe-0.8.4/mediapipe/python/BUILD:19:17: Linking mediapipe/python/_framework_bindings.so failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/arm-opt/bin/mediapipe/python/_framework_bindings.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: error: cannot find -ljpeg
/usr/bin/ld.gold: error: cannot find -ltiff
collect2: error: ld returned 1 exit status
Target //mediapipe/python:_framework_bindings.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 220.849s, Critical Path: 214.27s
INFO: 32 processes: 10 internal, 22 linux-sandbox.
FAILED: Build did NOT complete successfully
error: command 'bazel' failed with exit status 1
```

help.
Thanks.

**Comment by sgowroji** [comment]
Hi @hhajae, Please go through this similar references [#2041 ](https://github.com/google/mediapipe/issues/2041#issuecomment-846759019), https://github.com/google/mediapipe/issues/1917#issuecomment-824243096.

**Comment by hhajae** [comment]
> Hi @hhajae, Please go through this similar references [#2041 ](https://github.com/google/mediapipe/issues/2041#issuecomment-846759019), [#1917 (comment)](https://github.com/google/mediapipe/issues/1917#issuecomment-824243096).

Hi @sgowroji,
I've had a hard week with this problem(mediapipe in python (Rasberrypi4 with Raspbian)).
However thanks to your comment (https://github.com/google/mediapipe/issues/2107#issuecomment-852012958) and your other comments, I finally succeeded.

Thank you very much for your help.
