### ISSUE TITLE
Some errors occurred in tflite_inference_calculator.cc when Running on the device（Qualcomm 835 - android 7.1）

### ISSUE THREAD

**Issue by hongzhaji** [google/mediapipe#211]
Device log
`/com.google.mediapipe.apps.handtrackinggpu A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7fc974ad2a in tid 11639 (mediapipe_gl_ru)
/? A/DEBUG: pid: 11615, tid: 11639, name: mediapipe_gl_ru  >>> com.google.mediapipe.apps.handtrackinggpu <<<
   #00 pc 0000000000537670  /data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm64/libmediapipe_jni.so (_ZN6tflite18InterpreterBuilder12ParseTensorsEPKN11flatbuffers6VectorINS1_6OffsetINS_6BufferEEEEEPKNS2_INS3_INS_6TensorEEEEEPNS_8SubgraphE+448)
  #01 pc 0000000000537f38  /data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm64/libmediapipe_jni.so (_ZN6tflite18InterpreterBuilderclEPNSt6__ndk110unique_ptrINS_11InterpreterENS1_14default_deleteIS3_EEEEi+1112)
  #02 pc 000000000035b268  /data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm64/libmediapipe_jni.so (_ZN9mediapipe25TfLiteInferenceCalculator9LoadModelEPNS_17CalculatorContextE+672)
   #03 pc 000000000035a920  /data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm64/libmediapipe_jni.so (_ZN9mediapipe25TfLiteInferenceCalculator4OpenEPNS_17CalculatorContextE+396)
  #04 pc 00000000006780d8  /data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm64/libmediapipe_jni.so (_ZN9mediapipe14CalculatorNode8OpenNodeEv+660)
  #05 pc 000000000065b768  /data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm64/libmediapipe_jni.so (_ZN9mediapipe8internal14SchedulerQueue18OpenCalculatorNodeEPNS_14CalculatorNodeE+276)
  #06 pc 000000000065b4fc  /data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm64/libmediapipe_jni.so (_ZN9mediapipe8internal14SchedulerQueue11RunNextTaskEv+236)
   #07 pc 0000000000693c24  /data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm64/libmediapipe_jni.so (_ZNSt6__ndk110__function6__funcIZN9mediapipe9GlContext17RunWithoutWaitingENS_8functionIFvvEEEE3$_6NS_9allocatorIS7_EES5_EclEv+52)
    #08 pc 000000000068ee40  /data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm64/libmediapipe_jni.so (_ZN9mediapipe9GlContext15DedicatedThread10ThreadBodyEv+264)
     #09 pc 000000000068e7bc  /data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm64/libmediapipe_jni.so (_ZN9mediapipe9GlContext15DedicatedThread10ThreadBodyEPv+8)`

Does anyone else have some ideas?
Is my phone or tflite  problem?

**Comment by mcclanahoochie** [comment]
Hi, 
Do any of the other gpu examples work? Do the CPU examples run? 
Can you provide more of the adb log?
Also, we recently fixed a GPU issue in the [v0.6.5 release](https://github.com/google/mediapipe/releases/tag/v0.6.5), can you give that a try?
Thanks,

**Comment by eknight7** [comment]
@hongzhaji Did you get a chance to try the latest commit? Were you able to resolve the issue?
