### ISSUE TITLE
[Question] Setting virtual camera parameters for the Face Mesh

### ISSUE THREAD

**Issue by AlexFridman** [google/mediapipe#2110]
Hello!

In the documentation of the face mesh module was mentioned that it is possible to set custom camera parameters:
```"The virtual camera parameters can be set freely, however for better results it is advised to set them as close to the real physical camera parameters as possible."```

Could you please suggest a way how to do it from Python if possible?

-----
Another question -- is it possible to find the complete list of vertices of face model?

Best Regards,
Alex

**Comment by ldingemans** [comment]
@AlexFridman did you get the virtual camera parameters to work in Python? I was wondering the same thing

**Comment by AlexFridman** [comment]
> @AlexFridman did you get the virtual camera parameters to work in Python? I was wondering the same thing

no, still waiting for the devs response

**Comment by jiuqiant** [comment]
The virtual camera is for face geometry: https://google.github.io/mediapipe/solutions/face_mesh.html#face-geometry-module. In Python, we released FaceMesh only and FaceGeometry is not available.
