### ISSUE TITLE
Is there a way to fine-tune media pipe pose estimation model with own dataset? 

### ISSUE THREAD

**Issue by 124bit** [google/mediapipe#2111]
I’m working not with the yoga and dancing, but with other sport activities. Is there a way to fine-tune mediapipe pose estimation models for my use case with my own dataset? Thanks

**Comment by sgowroji** [comment]
Hi @124bit, Could you please elaborate your use case with complete details. Thanks!

**Comment by 124bit** [comment]
Our startup is doing the analysis of rowing technique for top coaches and national teams. I wanted to try Mediapipe as 2d pose estimator in our pipeline for the simple use cases, where the footage quality is good and there is just one athlete in a strictly lateral position without occlusions (I can show details by zoom if you are interested). 
However, it happened that keypoints estimation was not accurate and stable enough for subsequent analysis. Therefore I assumed that it possibly can work after fine-tuning with our datasets and some postprocessing.

**Comment by sgowroji** [comment]
Hi @124bit, Please share us your complete observation with video and error logs if there are any. Thanks!
