### ISSUE TITLE
Transformation of the skeleton coordinates from fixed frame into a mobile frame linked to the skeleton

### ISSUE THREAD

**Issue by RayData1** [google/mediapipe#2113]
Hello,
I have a problem with the transformation of the coordinates expressed in a fixed reference frame linked to the camera. I want to express the coordinates in a reference linked to the skeleton as in the image. 
![image](https://user-images.githubusercontent.com/85239017/120494830-7179ae80-c3bc-11eb-8368-ac34b0d11111.png)

{ "pose": {"joint_0":[0.057,0.708,-2.237],"joint_1":[0.04,0.741,-2.232],"joint_2":[0.025,0.756,-2.271],"joint_3":[0.013,0.758,-2.276],"joint_4":[0.076,0.737,-2.227],"joint_5":[0.091,0.746,-2.256],"joint_6":[0.102,0.75,-2.276],"joint_7":[-0.004,0.744,-2.271],"joint_8":[0.11,0.741,-2.286],"joint_9":[0.03,0.677,-2.237],"joint_10":[0.071,0.669,-2.237],"joint_11":[-0.122,0.55,-2.307],"joint_12":[0.205,0.543,-2.354],"joint_13":[-0.172,0.273,-2.302],"joint_14":[0.248,0.266,-2.328],"joint_15":[-0.198,0.05,-2.291],"joint_16":[0.275,0.048,-2.317],"joint_17":[-0.226,-0.022,-2.291],"joint_18":[0.298,-0.02,-2.338],"joint_19":[-0.197,-0.027,-2.302],"joint_20":[0.281,-0.025,-2.322],"joint_21":[-0.178,-0.002,-2.291],"joint_22":[0.265,0.003,-2.322],"joint_23":[-0.046,0.025,-2.251],"joint_24":[0.144,0.03,-2.317],"joint_25":[-0.04,-0.375,-2.349],"joint_26":[0.152,-0.354,-2.328],"joint_27":[-0.028,-0.753,-2.421],"joint_28":[0.142,-0.741,-2.461],"joint_29":[-0.007,-0.755,-2.322],"joint_30":[0.123,-0.764,-2.398],"joint_31":[-0.012,-0.816,-2.261],"joint_32":[0.155,-0.805,-2.251]} }

"joint_i": [x, y, z] with i represents the number of the join.

I work with a skeleton of this type:
![image](https://user-images.githubusercontent.com/85239017/120495062-a38b1080-c3bc-11eb-8a52-122e4aec0153.png)

Thank you so much for your help

**Comment by sgowroji** [comment]
Hi @RayData1, Could you please explain your use case with more details. Thanks!

**Comment by RayData1** [comment]
Hello,
I have the coordinates [x, y, z] of the joints of the skeleton in a fixed frame R0 linked to the camera. I want to make a python script to transfer these coordinates from the fixed frame R0 linked to the camera, to express them in a mobile frame linked to the skeleton of origin the middle of the body. for example the middle of the segment Joint _24 and Joint _23 and an axis passing through the joint _0. the frame R1 must be stuck to the skeleton, that is to say it will follow the movements of the skeleton. I want my python script to provide in output the coordinates of the joints in the mobile frame R1.

**Comment by sureshdagooglecom** [comment]
Hi @RayData1 ,
Are you still looking for the resolution on this issue.
