### ISSUE TITLE
util must be added to path

### ISSUE THREAD

**Issue by vvasily** [google/mediapipe#2114]
https://github.com/google/mediapipe/blob/ae05ad04b3ae43d475ccb2868e23f1418fea8746/mediapipe/calculators/tensorflow/BUILD#L513

util must be added to "//mediapipe/android/file/base", -> "//mediapipe/util/android/file/base",

**Comment by sgowroji** [comment]
Hi @vvasily, Could you please elaborate your request with more details. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.
