### ISSUE TITLE
How to know if mediapipe javascript is completely loaded.

### ISSUE THREAD

**Issue by salvadorld0** [google/mediapipe#2115]
I need to execute one function after mediapipe is completely loaded, but I'm failing to do so. The function always executes before the canvas loads mediapipe. I hope someone can help me with this issue.

**Comment by sgowroji** [comment]
Hi @salvadorld0, Could you please share your code changes and which solution are you trying for the above. Thanks!

**Comment by salvadorld0** [comment]
Hi @sgowroji. Thanks for answering. Yes of course. In fact, I'm trying to solve this issue outside of the complexity of my project, so, I'm using the sample code you can find on the documentation in [here](https://google.github.io/mediapipe/solutions/hands#javascript-solution-api). Here I left a snipped of it:

```
const hands = new Hands({locateFile: (file) => {
  return `https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`;
}});
hands.setOptions({
  maxNumHands: 2,
  minDetectionConfidence: 0.5,
  minTrackingConfidence: 0.5
});
hands.onResults(onResults);

const camera = new Camera(videoElement, {
  onFrame: async () => {
    await hands.send({image: videoElement});
  },
  width: 1280,
  height: 720
});
camera.start();
```

What I want is to be able to know when Mediapipe is completely loaded. This would mean, to be more specific, to have a callback the exact moment before the API starts sending results. The things that I have tried are:

1. Putting a `console.log` before and after the definition of the model, what doesn't seems to work because it appears to be an `async` function.
2. I tried to use the promise of the `camera.start()` function, like this:
```
camera.start().then(()=>{
    console.log("Mediapipe loaded");
});
```
But the promise is fullfilled much before than the first result is sent.
3. I tried with the events of the `videoElement`, but they always execute before the first result.
4. And I also try figuring out the [hands](https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands.js) and [control_utils](https://cdn.jsdelivr.net/npm/@mediapipe/control_utils/control_utils.js) code, but it seems very compressed, and I couldn't find any documentation that explain how to use it.

**Comment by tyrmullen** [comment]
Quick hack: you could add some code which only executes once right before "await hands.send".  Actually, the first packet sent through ends up performing a lot of the initialization while it processes (I believe it might not even give you results), so it is likely even more beneficial for your purposes to have your callback called right before the *second* time that line is about to be executed.  So like:
```
var sendCounter = 0;
const camera = new Camera(videoElement, {
  onFrame: async () => {
    if (sendCounter == 1) doInitializationCallback();
    await hands.send({image: videoElement});
    sendCounter++;
  },
  width: 1280,
  height: 720
});
```

**Comment by sgowroji** [comment]
Hi @salvadorld0, Could you please check the above `https://github.com/google/mediapipe/issues/2115#issuecomment-858031639` and share us the update. Thanks!

**Comment by salvadorld0** [comment]
@tyrmullen @sgowroji Yes, I'm sorry. I checked it before but I forgot to answer. To be honest that was my first approach, and it worked really fine, but I thought of it more like a patch instead of a solution. But, it appears not to be any other solution, so I think I will be using this hack. Thanks for your help. I really appreciated it.

**Comment by tyrmullen** [comment]
Emscripten-created WebAssembly modules normally allow for additional overriding, for use cases exactly like yours (see [Module.preRun](https://emscripten.org/docs/api_reference/module.html#Module.preRun)).  However, I don't believe the Solutions API yet exposes the Module object itself for developer use in this fashion, but instead only allows developers to define the ["locateFile"](https://emscripten.org/docs/api_reference/module.html#Module.locateFile) function.  It might be worth filing a feature request specifically for that (allowing for Module-level customization for advanced users, or at least exposing a few other key overrides, like preRun/preInit/onRuntimeInitialized for your use case), but closing this particular issue as resolved since there exists a solution for the immediate problem.
