### ISSUE TITLE
Hand landmark detection only

### ISSUE THREAD

**Issue by zhangy76** [google/mediapipe#2116]
Hi, 

I am using the Python API "mp.solutions.hands" to detect palm and hand landmarks given an image. I wonder if I can directly call the landmark detection model given an hand image?

Thanks

**Comment by sgowroji** [comment]
Hi @zhangy76, Can you elaborate your query with more details.  For more details of hand landmark refer [here](https://arxiv.org/pdf/2006.10214.pdf).

**Comment by zhangy76** [comment]
The demo python code provide a way to (1) detect palm area; (2) detect hand landmark position given the palm area, using the "mp.solutions.hands" package. Now I am trying to directly obtain the hand landmarks from a hand image, where the palm detection is not required. Basically, I wonder if I can directly input an hand image to a hand landmark detection model in python?

**Comment by jiuqiant** [comment]
You can take the landmark model (https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark.tflite) and use the standard tflite api to run it without mediapipe.

**Comment by zhangy76** [comment]
Thanks for the reply!

Is the input have the same format as the one in the demo, i.e. the flipped images reading by CV2 in RGB ?

**Comment by zhangy76** [comment]
Solved the problems
