### ISSUE TITLE
Object detection demo about coral dev board setup

### ISSUE THREAD

**Issue by yishinhung** [google/mediapipe#2117]
Hi:
      I encounter some error about build the Object detection demo for coral dev board.
Please give me some suggestion for this. Thank a lot!

https://github.com/google/mediapipe/tree/master/mediapipe/examples/coral

**-- Issue 1:**
    if i add the following step, i would encounter the following error
```
==============================================================
Edit /edgetpu/WORKSPACE

update /mediapipe/WORKSPACE TENSORFLOW_* variables to match what /edgetpu/WORKSPACE has:

  grep TENSORFLOW_ /mediapipe/WORKSPACE
  grep TENSORFLOW_ /edgetpu/WORKSPACE

  #  Make sure the /mediapipe/WORKSPACE  _TENSORFLOW_GIT_COMMIT  and  _TENSORFLOW_SHA256
  #   match the /edgetpu/WORKSPACE  TENSORFLOW_COMMIT  and  TENSORFLOW_SHA256  respectively.

  # If they do not match, modify /mediapipe/WORKSPACE to match what /edgetpu/WORKSPACE has.
  # Also comment out the MediaPipe org_tensorflow patch section.
===============================================================
```
error:
```
===============================================================
DEBUG: Repository rules_foreign_cc instantiated at:
  /mediapipe/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: error loading package '': cannot load '@org_tensorflow//tensorflow:workspace3.bzl': no such file
INFO: Elapsed time: 6.157s
================================================================
```

**-- Issue 2:**
      If i don't modify issue-1 patches, i would encounter the following error.
error:
```
================================================================
Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/tflite/tflite_inference_calculator.cc: In member function 'absl::lts_2020_09_23::Status mediapipe::TfLiteInferenceCalculator::LoadModel(mediapipe::CalculatorContext*)':
mediapipe/calculators/tflite/tflite_inference_calculator.cc:809:77: error: invalid conversion from 'const tflite::ops::builtin::BuiltinOpResolver*' to 'tflite::ops::builtin::BuiltinOpResolver*' [-fpermissive]
       BuildEdgeTpuInterpreter(model, op_resolver_ptr, edgetpu_context_.get());
==================================================================
```

**Comment by yishinhung** [comment]
Hi 
    I bypass the above issue and then fix rules_python issue by 749. But, i still encounter the following eigen3 issue.
Could you give some suggestion for this. Thank a lot!

```
command:
root@7b1f65f0196d:/mediapipe# bazel build -c opt --crosstool_top=@crosstool//:toolchains --compiler=gcc --cpu=aarch64 --define MEDIAPIPE_DISABLE_GPU=1 --copt -DMEDIAPIPE_EDGE_TPU --copt=-flax-vector-conversions mediapipe/examples/coral:object_detection_tpu

Error:
DEBUG: Repository rules_cc instantiated at:
  /mediapipe/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /mediapipe/mediapipe/framework/formats/BUILD:105:11: no such target '@eigen_archive//:eigen3': target 'eigen3' not declared in package '' (did you mean 'eigen'?) defined by /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/eigen_archive/BUILD.bazel and referenced by '//mediapipe/framework/formats:matrix'
ERROR: Analysis of target '//mediapipe/examples/coral:object_detection_tpu' failed; build aborted: Analysis failed
```

**Comment by sgowroji** [comment]
Hi @yishinhung, Your [Issue1](https://github.com/google/mediapipe/issues/2117#issue-910204449) is similar to [this](https://github.com/google/mediapipe/issues/1335#issuecomment-754823586).   And for the error mentioned in the next [comment](https://github.com/google/mediapipe/issues/2117#issuecomment-853673343), Please have a look at [here](https://github.com/google/mediapipe/issues/911). Thanks!

**Comment by yishinhung** [comment]
Hi @sgowroji :
   The error maybe cause by the following steps because "comment out the MediaPipe org_tensorflow patch section" remove the section about alias eigen3 to eigen . I can't find the  eigen3 folder under the third_party.
Did you have any suggestion for this? Thank a lot!

- ./third_party/org_tensorflow_compatibility_fixes.diff
```
============================================================
diff --git a/third_party/eigen3/eigen_archive.BUILD b/third_party/eigen3/eigen_archive.BUILD
index dad592bec48..670017c2c0f 100644
--- a/third_party/eigen3/eigen_archive.BUILD
+++ b/third_party/eigen3/eigen_archive.BUILD
@@ -49,6 +49,13 @@ cc_library(
     visibility = ["//visibility:public"],
 )

+# For backward compatibility.
+alias(
+    name = "eigen",
+    actual=":eigen3",
+    visibility = ["//visibility:public"],
+)
+
===========================================================

```

Steps
==============================================================
Edit /edgetpu/WORKSPACE

update /mediapipe/WORKSPACE TENSORFLOW_* variables to match what /edgetpu/WORKSPACE has:

  grep TENSORFLOW_ /mediapipe/WORKSPACE
  grep TENSORFLOW_ /edgetpu/WORKSPACE

  #  Make sure the /mediapipe/WORKSPACE  _TENSORFLOW_GIT_COMMIT  and  _TENSORFLOW_SHA256
  #   match the /edgetpu/WORKSPACE  TENSORFLOW_COMMIT  and  TENSORFLOW_SHA256  respectively.

  # If they do not match, modify /mediapipe/WORKSPACE to match what /edgetpu/WORKSPACE has.
  # Also **comment out the MediaPipe org_tensorflow patch section**.
===============================================================

```
Error:
DEBUG: Repository rules_cc instantiated at:
  /mediapipe/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
**ERROR: /mediapipe/mediapipe/framework/formats/BUILD:105:11: no such target '@eigen_archive//:eigen3': target 'eigen3' not declared in package '' (did you mean 'eigen'?) defined by** /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/eigen_archive/BUILD.bazel and referenced by '//mediapipe/framework/formats:matrix'
ERROR: Analysis of target '//mediapipe/examples/coral:object_detection_tpu' failed; build aborted: Analysis failed
```

**Comment by yishinhung** [comment]
Hi @sgowroji :
     I modify the eigen3 to eigen to bypass the build fail but i still encounter the following error.
Could you have any idea and suggestion for this? Thank a lot!

```
Error:
mediapipe/calculators/tflite/tflite_inference_calculator.cc: In member function 'absl::lts_2020_09_23::Status mediapipe::TfLiteInferenceCalculator::LoadModel(mediapipe::CalculatorContext*)':
mediapipe/calculators/tflite/tflite_inference_calculator.cc:795:25: error: 'BuiltinOpResolverWithoutDefaultDelegates' is not a member of 'tflite::ops::builtin'
   tflite::ops::builtin::BuiltinOpResolverWithoutDefaultDelegates
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mediapipe/calculators/tflite/tflite_inference_calculator.cc:799:12: error: 'default_op_resolver' was not declared in this scope
           &default_op_resolver);
            ^~~~~~~~~~~~~~~~~~~
Target //mediapipe/examples/coral:object_detection_tpu failed to build
```

**Comment by yishinhung** [comment]
Hi @jiuqiant:
    Did you have any idea for the build fail? I build the sample for coral board.
Thank al ot!

 

> Hi @sgowroji :
> I modify the eigen3 to eigen to bypass the build fail but i still encounter the following error.
> Could you have any idea and suggestion for this? Thank a lot!
> 
> ```
> Error:
> mediapipe/calculators/tflite/tflite_inference_calculator.cc: In member function 'absl::lts_2020_09_23::Status mediapipe::TfLiteInferenceCalculator::LoadModel(mediapipe::CalculatorContext*)':
> mediapipe/calculators/tflite/tflite_inference_calculator.cc:795:25: error: 'BuiltinOpResolverWithoutDefaultDelegates' is not a member of 'tflite::ops::builtin'
>    tflite::ops::builtin::BuiltinOpResolverWithoutDefaultDelegates
>                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> mediapipe/calculators/tflite/tflite_inference_calculator.cc:799:12: error: 'default_op_resolver' was not declared in this scope
>            &default_op_resolver);
>             ^~~~~~~~~~~~~~~~~~~
> Target //mediapipe/examples/coral:object_detection_tpu failed to build
> ```

Hi @jiuqiant :
    Did you have any idea for the build fail ? I build the sample for coral board.
Thank a lot!

**Comment by jiuqiant** [comment]
@mcclanahoochie is the owner of coral examples. Reassign this issue to @mcclanahoochie.

**Comment by yishinhung** [comment]
> Hi @jiuqiant :
> Did you have any idea for the build fail ? I build the sample for coral board.
> Thank a lot!

Hi @mcclanahoochie 
    Did you have any idea for the build fail ? I build the sample for coral board.
Thank a lot!

**Comment by yishinhung** [comment]
Hi @jiuqiant :
    Did you have any idea for this issue?
Thank a lot!

**Comment by mcclanahoochie** [comment]
the coral example setup has recently been updated,  https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/README.md
please try the new version

**Comment by yishinhung** [comment]
Hi @mcclanahoochie :
   

> the coral example setup has recently been updated, https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/README.md
> please try the new version

The new version can compiler the mediapipe samples for coral devices.
Thank for your help!
