### ISSUE TITLE
How to disable logging from TfLiteXNNPackDelegate?

### ISSUE THREAD

**Issue by GokulNC** [google/mediapipe#2119]
Whenever I create a holistic model, the following is printed on my Terminal:

```
>>> import mediapipe as mp
>>> holistic = mp.solutions.holistic.Holistic(static_image_mode=False, model_complexity=2)
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Replacing 223 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 6 partitions.
INFO: Replacing 597 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 1 partitions.
INFO: Replacing 61 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 5 partitions.
INFO: Replacing 61 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 5 partitions.
INFO: Replacing 162 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 2 partitions.
INFO: Replacing 64 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 1 partitions.
INFO: Replacing 64 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 1 partitions.
INFO: Replacing 97 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 1 partitions.
```

For my use-case, I need to continuously create new `Holistic` objects since I am running on many videos (with `static_image_mode=False`)
So this logging really floods my stdout. Anyway to disable this?

FYI, I just installed using `pip install mediapipe`. Python version: 3.8.8 ([Ubuntu 18.04 on Azure VM](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft-dsvm.ubuntu-1804?tab=Overview))
MediaPipe version: 0.8.4.2

**Comment by kiranscaria** [comment]
Have you tried changing the log-level?
`os.environ["GLOG_minloglevel"] ="2"`

Levels
0 - debug
1 - info (still a LOT of outputs)
2 - warnings
3 - errors 

https://stackoverflow.com/questions/29788075/setting-glog-minloglevel-1-to-prevent-output-in-shell-from-caffe

**Comment by GokulNC** [comment]
Yes I did.

```
>>> import os
>>> os.environ["GLOG_minloglevel"] ="2"
>>> import mediapipe as mp
>>> holistic = mp.solutions.holistic.Holistic(static_image_mode=False, model_complexity=2)
>>> INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Replacing 223 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 6 partitions.
INFO: Replacing 597 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 1 partitions.
INFO: INFO: Replacing 61 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 5 partitions.
Replacing 61 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 5 partitions.
INFO: Replacing 162 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 2 partitions.
INFO: Replacing 64 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 1 partitions.
INFO: Replacing 64 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 1 partitions.
INFO: Replacing 97 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 1 partitions.
```

**Comment by sgowroji** [comment]
Hi @GokulNC, Have you tried with the latest build. This should be [fixed](https://github.com/google/mediapipe/issues/1695#issuecomment-794624067) in the latest release.

**Comment by jiuqiant** [comment]
Can be removed by adding "--copt=-DNDEBUG" and rebuilding the python package. Will have this improvement in the next release. 

```
diff --git a/setup.py b/setup.py
index 31e5195b..b23f26ad 100644
--- a/setup.py
+++ b/setup.py
@@ -241,6 +241,7 @@ class BuildBinaryGraphs(build.build):
         'bazel',
         'build',
         '--compilation_mode=opt',
+        '--copt=-DNDEBUG',
         '--define=MEDIAPIPE_DISABLE_GPU=1',
         '--action_env=PYTHON_BIN_PATH=' + _normalize_path(sys.executable),
         os.path.join('mediapipe/modules/', graph_path),
@@ -297,6 +298,7 @@ class BuildBazelExtension(build_ext.build_ext):
         'bazel',
         'build',
         '--compilation_mode=opt',
+        '--copt=-DNDEBUG',
         '--define=MEDIAPIPE_DISABLE_GPU=1',
         '--action_env=PYTHON_BIN_PATH=' + _normalize_path(sys.executable),
         str(ext.bazel_target + '.so'),
```

**Comment by GokulNC** [comment]
Thank you. Please feel free to close this issue if the above patch will fix the issue and will be released soon.
Currently I cannot rebuild MediaPipe and test it to let you know if it works.

**Comment by nam-hoang-le** [comment]
> Can be removed by adding "--copt=-DNDEBUG" and rebuilding the python package. Will have this improvement in the next release.
> 
> ```
> diff --git a/setup.py b/setup.py
> index 31e5195b..b23f26ad 100644
> --- a/setup.py
> +++ b/setup.py
> @@ -241,6 +241,7 @@ class BuildBinaryGraphs(build.build):
>          'bazel',
>          'build',
>          '--compilation_mode=opt',
> +        '--copt=-DNDEBUG',
>          '--define=MEDIAPIPE_DISABLE_GPU=1',
>          '--action_env=PYTHON_BIN_PATH=' + _normalize_path(sys.executable),
>          os.path.join('mediapipe/modules/', graph_path),
> @@ -297,6 +298,7 @@ class BuildBazelExtension(build_ext.build_ext):
>          'bazel',
>          'build',
>          '--compilation_mode=opt',
> +        '--copt=-DNDEBUG',
>          '--define=MEDIAPIPE_DISABLE_GPU=1',
>          '--action_env=PYTHON_BIN_PATH=' + _normalize_path(sys.executable),
>          str(ext.bazel_target + '.so'),
> ```

Hi, I met this problem while running the code: 
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

Please let me know what is the package file I need to find out. Thank you

**Comment by Dragod** [comment]
> > Can be removed by adding "--copt=-DNDEBUG" and rebuilding the python package. Will have this improvement in the next release.
> > ```
> > diff --git a/setup.py b/setup.py
> > index 31e5195b..b23f26ad 100644
> > --- a/setup.py
> > +++ b/setup.py
> > @@ -241,6 +241,7 @@ class BuildBinaryGraphs(build.build):
> >          'bazel',
> >          'build',
> >          '--compilation_mode=opt',
> > +        '--copt=-DNDEBUG',
> >          '--define=MEDIAPIPE_DISABLE_GPU=1',
> >          '--action_env=PYTHON_BIN_PATH=' + _normalize_path(sys.executable),
> >          os.path.join('mediapipe/modules/', graph_path),
> > @@ -297,6 +298,7 @@ class BuildBazelExtension(build_ext.build_ext):
> >          'bazel',
> >          'build',
> >          '--compilation_mode=opt',
> > +        '--copt=-DNDEBUG',
> >          '--define=MEDIAPIPE_DISABLE_GPU=1',
> >          '--action_env=PYTHON_BIN_PATH=' + _normalize_path(sys.executable),
> >          str(ext.bazel_target + '.so'),
> > ```
> 
> Hi, I met this problem while running the code: INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
> 
> Please let me know what is the package file I need to find out. Thank you

Having same issue. I don't want the "Created TensorFlow Lite XNNPACK delegate for CPU." to be printed
