### ISSUE TITLE
How to write a GpuTensorsToGpuBufferCalculator?

### ISSUE THREAD

**Issue by kiranscaria** [google/mediapipe#2121]
I have a .tflite model which outputs a GPU_TENSOR of shape 224x224x3. How can I write a simple calculator to convert the GPU_TENSOR to output.

Thanks.

**Comment by sgowroji** [comment]
Hi @kiranscaria, Could you please elaborate your use case with complete details. Thanks!

**Comment by kiranscaria** [comment]
I wanted to create a style-transfer pipeline; where the tflite model would take in an RGB image and gives out an RGB image (as Tensors). Is there any calculator where I convert this Tensor into Image?

**Comment by kiranscaria** [comment]
The steps I believe would be:
1. TENSOR -> IMAGE using TensortoImageCalculator
2. IMAGE -> GPUBuffer using FromImageCalculator

I couldn't find the TensortoImageCalculator.

**Comment by brucechou1983** [comment]
**TensorsToSegmentationCalculator** is also a pixel based conversion calculator. You could create TensorToImageCalculator base on that.

**Comment by kiranscaria** [comment]
> **TensorsToSegmentationCalculator** is also a pixel based conversion calculator. You could create TensorToImageCalculator base on that.

Thanks for the info. `TensorToImageCalculator` seems to be a good place to start with.

**Comment by sgowroji** [comment]
Hi @kiranscaria, Are you still looking resolution for the above query. Thanks!

**Comment by akdu12** [comment]
@kiranscaria I looking for the same thing but I'm not a c++ dev, did you figure out the implementation?
