### ISSUE TITLE
About remote control interface in Holistic

### ISSUE THREAD

**Issue by guoguoguilai** [google/mediapipe#2122]
The example on [Holistic Remote](https://mediapipe.dev/demo/holistic_remote/) is awsome! I was attracted by the gesture interaction. How to implement such a remote control interface?

**Comment by sgowroji** [comment]
Hi @guoguoguilai, Could you please elaborate your use case with clear details. Thanks!

**Comment by sgowroji** [comment]
Hi @guoguoguilai, Could you please respond to my above comment. Thanks!

**Comment by guoguoguilai** [comment]
Sorry for the late reply.
[Holistic Remote](https://mediapipe.dev/demo/holistic_remote/) contains a gesture control system to do oprations(e.g. mute microphone and open keyboard by a specific gesture ). This is awesome. How can I implement this?

**Comment by txf-** [comment]
It would be interesting to to have the source for that particular demo. Would it be possible to release it?

**Comment by ayushgdev** [comment]
Hello @guoguoguilai
The gesture recognition is available as a separate API now in MediaPipe. We would urge you to explore it. 
We are building a set of new, improved [MediaPipe Solutions](https://developers.google.com/mediapipe/solutions) to help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. And we request the MediaPipe developer community help us uncover the issues and make the APIs more resilient.
