### ISSUE TITLE
Hand landmark detection model finetuning 

### ISSUE THREAD

**Issue by zhangy76** [google/mediapipe#2123]
Hi,

Is that possible to finetune the landmark detection model on my own data? The platform I use is python. 

Thanks

**Comment by sgowroji** [comment]
Hi @zhangy76, Have you encountered any error while using hand solution? Please share us the complete details like error logs with steps performed  to reproduce it.

**Comment by zhangy76** [comment]
Thanks for the reply. The results do not look good when running on some challenging images. I am considering to retrain the model with my own image data.

**Comment by sgowroji** [comment]
May be you can share us your observation with some video or screenshot. That will really help us understand and make it better.

**Comment by zhangy76** [comment]
Sorry that the video can not be shared. But the model fails to provide good estimation under occlusion, e.g. only the five tips is visible.

**Comment by edybk** [comment]
I'm facing a similar issue. I'm trying to use the landmarks on a custom dataset but the results aren't satisfying. It would be amazing if you could provide a way to fine-tune the model on custom datasets.

**Comment by zhangy76** [comment]
Sorry to hear that. I failed to do any fine-tune and do not work on it any more.

**Comment by edybk** [comment]
@zhangy76 Thanks for the update.
