### ISSUE TITLE
Gaze Direction Estimation

### ISSUE THREAD

**Issue by Sun1718** [google/mediapipe#2125]
Hi,

Can you please guide me to find the gaze direction of the eyes using head rotation and translation values and iris points?

So thanks

**Comment by sgowroji** [comment]
Hi @Sun1718, Could you please provide more details regarding the above query. Thanks!

**Comment by sgowroji** [comment]
Hi @Sun1718, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.

**Comment by wwdok** [comment]
Hi, @sgowroji I guess he means something like this:
![image](https://user-images.githubusercontent.com/43233772/157001148-e5f0080b-534c-4af8-a95e-f8e9e4de8e7a.png)([source](https://docs.openvino.ai/latest/omz_models_model_gaze_estimation_adas_0002.html))

**Comment by sutyum** [comment]
@wwdok yes, i am looking for the same thing. Is there a way to get these vectors using mediapipe?

**Comment by monajalal** [comment]
any update on this?
