### ISSUE TITLE
Incorrect Hand Detection - MediaPipe Hands (Multihand Tracking)

### ISSUE THREAD

**Issue by hirashahid9** [google/mediapipe#2128]
Mediapipe hands is not tracking hands accurately. Kindly look into this issue. I have used these extracted landmarks for model training for sign language, But the resulting accuracy is very low. I think it is due to incorrect detection by mediapipe Kindly let me know what can I do now? 

![image](https://user-images.githubusercontent.com/55246052/120887688-bfd1bc00-c60d-11eb-9f3a-3f6e3c7125c1.png)

**Comment by sgowroji** [comment]
Hi @hirashahid9, Could you please provide the steps to reproduce the above error. Thanks!
