### ISSUE TITLE
want to use Pose Detection of mediapipe with Flutter, How can I handle that

### ISSUE THREAD

**Issue by sattyamjjain** [google/mediapipe#2129]

**Comment by sgowroji** [comment]
Hi @sattyamjjain, Have you tried any examples and noticing any errors. Please let us know. Thanks

**Comment by sgowroji** [comment]
Hi @sattyamjjain, Could you please respond to my above comment. Thanks!

**Comment by sattyamjjain** [comment]
Hello @sgowroji 
Since I haven't got proper documentation to use media pipe with Flutter
then I am trying to implement mlkit by creating a flutter plugin using android native.

Please let me know, Is there any way to implement media pipe with flutter (because I am not experienced to work with kotlin or java for android)

Thanks

**Comment by sgowroji** [comment]
Hi @sattyamjjain,  Please go through this  #1046 #17.
