### ISSUE TITLE
Epnp : lifting2DTo3D points : Objectron

### ISSUE THREAD

**Issue by yehDilBeparwah** [google/mediapipe#2130]
I read the Epnp paper and the lifting2Dto3D code, there are just a few things if someone could help me with.

Q1. [code](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/modules/objectron/calculators/decoder.cc#L250) why is the alpha matrix multiplied with the solution(control matrix) to get to 3d vertices.

Q2. I am trying to reproduce the results (by running the function as a standalone c++ gtest). I am taking input (2d points/ expected 3d points) from 'objectron-geometry-tutorial.ipynb' notebook in Objectron repo. I am using the points from frame grab (if that helps explain exactly what from the notebook I am using).
If we look at the code I posted above, the 3d point equivalent to centre of the box would be the first 3 values in control matrix.
I cycled through all the Eigen values/eigen vectors which would form the control matrix(in the code we take the first Eigen value) but none of the values match expected 3D point.

Do I need to use another alpha matrix or how can I find it.

**Comment by yehDilBeparwah** [comment]
@lzhang57 @ahmadyan  any word pls?
I think the answer for q1 is that the vertices are supposed to be a weighted combination of control points but then that begs the question, should I be using the hard-coded alpha matrix that is there in media pipe code?

**Comment by ahmadyan** [comment]
There is no guarantee that they would match. The EPNP will lift the 2D points to a 3D box with an arbitrary scale and not necessary the correct scale. You can think of it as there are many 3D bounding box whose projection will be the same 2D points.

**Comment by yehDilBeparwah** [comment]
thanks
