### ISSUE TITLE
Where to find and download the novel annotation tool for use with AR session data?

### ISSUE THREAD

**Issue by shero1111** [google/mediapipe#2131]
Hello,

I read here (https://ai.googleblog.com/2020/03/real-time-3d-object-detection-on-mobile.html) about the annotation tool for videos...where can I find and use or download it?

I could not find it anywhere on net. 

![image](https://user-images.githubusercontent.com/64836488/120929581-e1a07100-c6e9-11eb-810f-cf4e55f98944.png)

Thank you in advance!

**Comment by sgowroji** [comment]
Hi @shero1111, Please go through this for complete [documentation and code ](https://google.github.io/mediapipe/solutions/objectron.html)samples in different platforms.

**Comment by shero1111** [comment]
MODEL_NAME
Name of the model to use for predicting 3D bounding box landmarks. Currently supports {'Shoe', 'Chair', 'Cup', 'Camera'}.

Does that mean that we can not realize a delivery box objectron? Does the framework currently support just these and when providing a model for delivery boxes it would nevertheless not detect them because just 4 kinds of objects are supported for objectron?

**Comment by ahmadyan** [comment]
Hi Shero, 

1. We have not released our annotation tools. To visualize the dataset you you either browse [Objectron hub](https://app.activeloop.ai/dataset/google/chair) or use one of our Notebooks. 

2. We will release model for more categories (including all nine categories in the dataset) next week. Stay tuned.

**Comment by sgowroji** [comment]
Closing this  above request W.r.t https://github.com/google/mediapipe/issues/1472#issuecomment-788708081
