### ISSUE TITLE
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:309] Error parsing text-format mediapipe.CalculatorGraphConfig: 108:55: Expected "/", found "]".

### ISSUE THREAD

**Issue by PragadheeswaranDX** [google/mediapipe#2135]
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:309] Error parsing text-format mediapipe.CalculatorGraphConfig: 108:55: Expected "/", found "]".
E20210607 14:29:15.103349 18843 text_to_binary_graph.cc:112] INTERNAL: ; could not parse text proto: mediapipe/modules/pose_landmark/pose_landmark_gpu.pbtxt
Target //mediapipe/modules/pose_landmark:pose_landmark_gpu failed to build

Updating the below nodes to pose_landmark_gpu.pbtxt and updating the image input stream to image_gpu
node: {
  calculator: "ColorConvertCalculator"
  input_stream: "RGB_IN:image"
  output_stream: "RGBA_OUT:image_rgba"
}
node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "image_rgba"
  output_stream: "image_gpu"
}

node {
  name: "ConstantSidePacketCalculator"
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:use_prev_landmarks"
  node_options: {
    [mediapipe.ConstantSidePacketCalculatorOptions.ext]: {
      packet { bool_value: true }
    }
  }
}

when i remove this below nodes its working but in image buffer on CPU not on GPU
node: {
  calculator: "ColorConvertCalculator"
  input_stream: "RGB_IN:image"
  output_stream: "RGBA_OUT:image_rgba"
}
node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "image_rgba"
  output_stream: "image_gpu"
}

**Comment by sgowroji** [comment]
Hi @PragadheeswaranDX, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by PragadheeswaranDX** [comment]
Sir, Thankyou for the respose. I worked on the Build script and succesfully built it. You may close the issue.
