### ISSUE TITLE
Iris_landmark coordinate on the cropped eye image coordinate

### ISSUE THREAD

**Issue by Monibsediqi** [google/mediapipe#2137]
Hi, I need to get the iris landmarks coordinate in the cropped eye image. Any insights on how to get the iris landmark coordinate in the cropped eye image? 
Side note: I know how to get the landmark coordinate on the actual image. It's basically multiplying the normalized landmark value with the height and width of the image. However, I need to get the landmark coordinate in the eye cropped image. 
Thank you in advance,

**Comment by Monibsediqi** [comment]
Hi, any update on this issue?

**Comment by sgowroji** [comment]
Hi @Monibsediqi, What is the challenge you seeing when trying to get the coordinates from a cropped eye image coordinate?
