### ISSUE TITLE
GetResourceContents failed

### ISSUE THREAD

**Issue by maksymsur** [google/mediapipe#2138]
After upgrading from 0.8.4 to 0.8.5 face the following issue:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W20210607 13:55:22.764837 24128 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/palm_detection/palm_detection.tflite
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W20210607 13:55:22.808321 24128 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/hand_landmark/hand_landmark.tflite
```
When downgrading - all works just fine.

System info:
```
Linux 5.8.0-55-generic 20.04.1-Ubuntu x86_64 GNU/Linux
Python 3.8.10
```

**Comment by sgowroji** [comment]
Hi @maksymsur, Could you please provide the steps to reproduce the above error and also your code changes. Thanks!

**Comment by maksymsur** [comment]
Sure.
Here is my workflow:
```
(base) maksym@sur:~$ conda create -n test_env python=3.8.10
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/maksym/anaconda3/envs/test_env

  added / updated specs:
    - python=3.8.10


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2021.5.25-h06a4308_1
  certifi            pkgs/main/linux-64::certifi-2021.5.30-py38h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1k-h27cfd23_0
  pip                pkgs/main/linux-64::pip-21.1.1-py38h06a4308_0
  python             pkgs/main/linux-64::python-3.8.10-hdb3f193_7
  readline           pkgs/main/linux-64::readline-8.1-h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-52.0.0-py38h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.35.4-hdfb4753_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test_env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) maksym@sur:~$ conda activate test_env

(test_env) maksym@sur:~$ pip install -U mediapipe
Collecting mediapipe
  Using cached mediapipe-0.8.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
Collecting opencv-contrib-python
  Using cached opencv_contrib_python-4.5.2.52-cp38-cp38-manylinux2014_x86_64.whl (57.4 MB)
Collecting attrs>=19.1.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting absl-py
  Using cached absl_py-0.12.0-py3-none-any.whl (129 kB)
Collecting protobuf>=3.11.4
  Using cached protobuf-3.17.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Requirement already satisfied: wheel in ./anaconda3/envs/test_env/lib/python3.8/site-packages (from mediapipe) (0.36.2)
Collecting numpy
  Using cached numpy-1.20.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.4 MB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, numpy, protobuf, opencv-contrib-python, attrs, absl-py, mediapipe
Successfully installed absl-py-0.12.0 attrs-21.2.0 mediapipe-0.8.5 numpy-1.20.3 opencv-contrib-python-4.5.2.52 protobuf-3.17.2 six-1.16.0

(test_env) maksym@sur:~/Documents/test_e$ python main.py 
WARNING: Logging before InitGoogleLogging() is written to STDERR
W20210607 15:33:14.612668  4876 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/palm_detection/palm_detection.tflite
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W20210607 15:33:14.650885  4876 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/hand_landmark/hand_landmark.tflite
```
and that's the content of `main.py` --> as you may notice it's a simple hand-landmark solution suggested by the manual
```
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands

# For webcam input:
cap = cv2.VideoCapture(0)
with mp_hands.Hands(
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5) as hands:
  while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      continue

    # Flip the image horizontally for a later selfie-view display, and convert
    # the BGR image to RGB.
    image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)
    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    results = hands.process(image)

    # Draw the hand annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    if results.multi_hand_landmarks:
      for hand_landmarks in results.multi_hand_landmarks:
        mp_drawing.draw_landmarks(
            image, hand_landmarks, mp_hands.HAND_CONNECTIONS)
    cv2.imshow('MediaPipe Hands', image)
    if cv2.waitKey(5) & 0xFF == 27:
      break
cap.release()
```

**Comment by RikiXY** [comment]
I have the same problem
![Screenshot (26)](https://user-images.githubusercontent.com/85552026/121156138-bbddae00-c848-11eb-8664-98d881d69543.png)

**Comment by Myrrdin89** [comment]
Hi, just do add.
I have the same issue, with a slightly different code (while loop is different). However it still runs the detection and tracking of two hands under good conditions reasonable well.

**Comment by jiuqiant** [comment]
This is the warning message before entering the fallback logic: https://github.com/google/mediapipe/blob/master/mediapipe/util/tflite/tflite_model_loader.cc#L32. The fallback logic should get the right path of the model file and read contents from there. 

We can rephrase this warning. I am curious about what the actual problem you get? The solution is not running properly anymore?

**Comment by Myrrdin89** [comment]
So I'm not sure if the solution is correct but it seems like that.
Today, out of curiosity I set up a fresh branch and installed opencv and mediapipe. (Had some issues with opencv as well). I noticed that the opencv installations did mismatch between the one I used and the one installed by mediapipe. For me the error got away after I uninstalled and reinstalled the opencv-contrib-python for 4.5.2. Now it also seems to better track the hand(s). It seems that the installer for mediapipe (pip python) does not check for the contrib part of opencv?

**Comment by jiuqiant** [comment]
> So I'm not sure if the solution is correct but it seems like that.
> Today, out of curiosity I set up a fresh branch and installed opencv and mediapipe. (Had some issues with opencv as well). I noticed that the opencv installations did mismatch between the one I used and the one installed by mediapipe. For me the error got away after I uninstalled and reinstalled the opencv-contrib-python for 4.5.2. Now it also seems to better track the hand(s). Edit: I just rechecked the workflow above. But for me it did not update the contrib part of opencv but did use one before an API change in opencv

MediaPipe doesn't require a specific opencv version: https://github.com/google/mediapipe/blob/master/requirements.txt#L4. Is it possible that the opencv side does some optimization for image capturing?

**Comment by Myrrdin89** [comment]
I think in my case anyway there was a mismatch between the opencv version and the opencv-contrib part which restulted in the error. At least after I checked and made sure it is the same version, the warning got away.
It might be the same for the original issue opener.
For me it seems to work more stable now. I just need to solve the issue with gloves and tracking.
I would suggest to make clear that the code does actually fall back and loads the model, as the second part of the warning sounds like the model files could not be found and loaded. I assume this leads to some confussion.

**Comment by maksymsur** [comment]
Reinstalling opencv-contrib-python 4.5.2 didn't make any difference for me. The error's still there.
Closing the issue for now as there is no crash/decrease in mp performance.
Although, I'd suggest mp maintainers to solve/rephrase warnings about entering the fallback logic as it's somewhat confusing.

**Comment by ozerberdi** [comment]
Hello everybody;
I have asame problem. Application runs in pycharm  with this message:
 
![d](https://user-images.githubusercontent.com/36799185/122672129-9c446f00-d1d2-11eb-8620-b4ae6c5e5a99.png)

But when I compile with pyinstaller and try to run exe, it gives following mediapipe file not found error.

![d1](https://user-images.githubusercontent.com/36799185/122671947-a87bfc80-d1d1-11eb-81cb-80e33003064e.png)

Any help will be appreciated.

**Comment by lghasemzadeh** [comment]
> Hi, just to add. I have the same issue, with a slightly different code (while loop is different). However it still runs the detection and tracking of two hands under good conditions reasonable well.
Yes, actually that is not an error, that is only a warning, so it isn't important to debug or resolve it.
