### ISSUE TITLE
@local_config_cc//:cc-compiler-darwin_x86_64

### ISSUE THREAD

**Issue by Sanerly** [google/mediapipe#214]
Hello, I have been running the project with android studio on MAC, but there have been some mistakes. I don't know what caused them.

/usr/local/Cellar/bazel/0.29.1/bin/bazel mobile-install --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no -c opt --config=android_arm64 -- //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu:facedetectioncpu
Loading: 
Loading: 0 packages loaded
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu:facedetectioncpu (0 packages loaded, 0 targets configured)
ERROR: /private/var/tmp/_bazel_ej/327ee5afeaa68e27ac18988b38f1c8c6/external/local_config_cc/BUILD:64:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-darwin_x86_64: Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, verify that "xcode-select -p" is correct and then try: "bazel shutdown" to re-run Xcode configuration
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu:facedetectioncpu' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-darwin_x86_64' failed; build aborted
INFO: Elapsed time: 0.111s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by Sanerly** [comment]
Hello, I went through some difficulties and finally found a way to solve the problem. The aar file for gesture detection has been successfully packaged. Thank you for your efforts,
[This is the address](https://stackoverflow.com/questions/45276830/xcode-version-must-be-specified-to-use-an-apple-crosstool)

**Comment by jiuqiant** [comment]
Glad to hear that the problem is solved.
