### ISSUE TITLE
Some questions about the output of blazepose

### ISSUE THREAD

**Issue by kkzh2313** [google/mediapipe#2140]
Question1:  The regression output of pose_detection is 2254*12 in the lastest version 0.8.5.  The first 4 values correspond to the bounding ox of face, as shown in the red box in the figure.
      I'm not sure if this is the right answer, why is the red bounding box so big, why isn't it just tangent to the face ?

![image](https://user-images.githubusercontent.com/34201133/121120099-7e305380-c84f-11eb-9d73-3deed5313e27.png)

Question2:  There are five outputs of the Pose_Landmarks model. The first output dimension is 1*195, which corresponds to 39 key points.But only 33 key points in the whole body.
I see other explanations: Last 6 points are technical and are used to get accurate pose crop from the previous frame for the next one. Normally we don't want to use them.  Is it right?
 (https://github.com/google/mediapipe/issues/1024#issuecomment-676830983)
![image](https://user-images.githubusercontent.com/34201133/121120540-555c8e00-c850-11eb-8867-c43996a75f79.png)

Question3: What do the other four outputs mean?

**Comment by guker** [comment]
I have same question,  wait for your answer online!

**Comment by kuaashish** [comment]
Hello @kkzh2313,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
