### ISSUE TITLE
Mediapipe facemesh landmarks getting bad values in Chrome Mobile

### ISSUE THREAD

**Issue by Lpayaro** [google/mediapipe#2141]
Hello, this is my first time posting on github so if I am missing some details please let me know.

I am using testing this project from syed-ashraf123 `https://github.com/syed-ashraf123/mediapipe_face_mesh`

It runs smootly on a Chrome for Windows but it can't work properly on Chrome for Android. At the begging the mesh is shown but landmarks go away in 1 second. The reason is that the landmarks values get very low and they are draw outside the canvas and cannot be seen.

**Steps to reproduce:**

- Run the project from syed-ashraf123 `https://github.com/syed-ashraf123/mediapipe_face_mesh`

- Connect your android phone and allow usb debugging

- Access your pc direction and port where your app is running. You need the pc and phone in the sane WiFi network.

- Can use chrome developer tools `chrome://inspect/#devices` and use `chrome://flags/#unsafely-treat-insecure-origin-as-secure` for making available the camera because I am loading from react development server on my pc to Chrome Mobile on my phone through a non https connection. Reference: `https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339`

- Can place a console.log(result) on the onResults function. Select the tab with the react app and press f12 to see the landmarks.
![image](https://user-images.githubusercontent.com/50473570/121128436-64642180-c7f9-11eb-8ee2-b2100210c4f2.png)

The errors:
Just initializing
![image](https://user-images.githubusercontent.com/50473570/121125692-f61d6000-c7f4-11eb-81b2-e3d7c6feb1d3.png)

The first landmarks seems ok:
![image](https://user-images.githubusercontent.com/50473570/121126653-83ad7f80-c7f6-11eb-92ad-7d4ba907b302.png)

The third wave of landmarks, they start to get low and even negative values:
![image](https://user-images.githubusercontent.com/50473570/121126851-d9822780-c7f6-11eb-9394-b8276699c1f3.png)

5 seconds later:
![image](https://user-images.githubusercontent.com/50473570/121127050-3251c000-c7f7-11eb-804c-ea3d3fb1962e.png)

10 seconds later:
![image](https://user-images.githubusercontent.com/50473570/121127181-61683180-c7f7-11eb-827a-8a428083efa1.png)

Maybe the webpack preprocess is corrupting the wasm files as in here: https://github.com/rustwasm/wasm-bindgen/issues/753 ?? it shows the table index X out of bounds error

**Update**
I got the same error on a pure html page as the shown in the mediapipe codepen
![image](https://user-images.githubusercontent.com/50473570/121262310-e861ec00-c881-11eb-90b2-72306999a34a.png)

And also the proper codepen `https://codepen.io/mediapipe/details/KKgVaPJ` fails on chrome mobile

![image](https://user-images.githubusercontent.com/50473570/121263051-10058400-c883-11eb-85cf-8d45dc0195a5.png)

**Comment by tyrmullen** [comment]
We have not been actively supporting the JavaScript Solutions APIs on Android Chrome.  However, many users have been reporting that things run fine on 64-bit Android Chrome, while they fail for 32-bit Android Chrome (https://www.ghacks.net/2021/03/13/google-is-pushing-64-bit-chrome-on-android/).  Perhaps that's the issue you're running into?  navigating to "chrome://version/" in the phone's browser can tell you more details about what Android Chrome you're currently running.  Also, details about the make and model of the phone would be useful, for posterity.

In any case, the "table index is out of bounds" error is *not* normal, and is not an error I've ever seen before, so I imagine that's really the root of these issues.  I just added some code to make stack traces more useful to us in the future, so the next time there's a Solutions JS API update, if you could paste one more stack trace (along with the MediaPipe code version, as on jsdelivr), that will also let us better understand this issue.

In the meantime, we are actively working on growing our supported platforms, but unfortunately, it will likely be a while before we are able to track down issues like this for Android Chrome.

**Comment by Lpayaro** [comment]
Understood, 

This phone is a Redmi Note 8 pro 6GB RAM 128GB storage version and the chrome mobile version is as you say 32bit.
The mediapipe version is "@mediapipe/face_mesh": "^0.3.1620248508".

I am now using facemesh through @tensorflow-models/face-landmarks-detection and it works on both phone and desktop.
I hope that this information will be useful to mediapipe.

Thanks for your support, anyway mediapipe is an awesome project.

Details of chrome mobile:
![Screenshot_chrome_version](https://user-images.githubusercontent.com/50473570/122505876-33d77100-cfcb-11eb-9392-553b9e99bb2a.jpg)

**Comment by mhays-google** [comment]
This is on our radar.  We have a commitment to roll this out to more
devices, but at the moment, the order and timeline of that deliverable is
still being discussed.

**Comment by kvasss** [comment]
Hi. Confirming the problem.
Redmi note 7 
chrome 32 bit version 91.0.4472.120
Opera latest same problems 
Firefox latest works fine.
face-landmarks-detection solution works fine in all browsers
Problem: 
On each frame tick landmarks values grow like
frame 1
landmarks[0].x = 0.03;
landmarks[0].y = 0.03;
landmarks[0].z = 0.03;
frame 2
landmarks[0].x = 0.3;
landmarks[0].y = 0.3;
landmarks[0].z = 0.3;
frame 3
landmarks[0].x = 3;
landmarks[0].y = 3;
landmarks[0].z = 3;
frame 4
landmarks[0].x = 30;
landmarks[0].y = 30;
landmarks[0].z = 30;

etc.

**Comment by sureshdagooglecom** [comment]
Hi @Lpayaro ,
This can be reclosed as supports only 64-bit Chrome Android.
