### ISSUE TITLE
hi how can i use iris_tracking graphs with "not a camera, but an image."

### ISSUE THREAD

**Issue by bwjoe** [google/mediapipe#2143]
hello~
i appreciate your all supports

first, i success in making an "iristrakcinggpu arr"
next, i success in making an "test apk" with "libs/iristrakcinggpu arr" and "asset/face_detection_front.tflite" , "asset/iris_lanmark.tflite" , "asset/face_lanmark.tflite" ,  "asset/iris_tracking_gpu.binarypb".
"test apk" works well.

but my project already use "android.hardware.camera" so i have to use "iristrakcinggpu arr" with image , not camera
i tried finding a code and testing about that in few days. .

but i failed now

could you some comment or hint about that?

plz save me

**Comment by sgowroji** [comment]
Hi @bwjoe, Could you please respond to my above comment. Thanks!

**Comment by bwjoe** [comment]
hello
sorry about my late response.
i don't have enough time to find about this solution. ( my schedule is so busy..)
so i solve this problem with worng way , not correct way.

i just activate 2 camera objects. 
and just get iris landmarks from mediapipe module with set "output : inputstream,"

anyway so i just skip this problem not solving.
so i have no error reports that you request.
thank you for all consideration

**Comment by sgowroji** [comment]
Hi @bwjoe, Thank you so much for responding and sharing your fix and glad to know you resolved. We are closing this issue now, Feel free to reach us back if you still have any similar query. Thanks!
