### ISSUE TITLE
How to save image after detection

### ISSUE THREAD

**Issue by Monibsediqi** [google/mediapipe#2144]
Hi, How can I save the mediapipe processed image after iris/face detection on android?
As I went through the basic android example, I noticed that the output of the processor object is a SurfaceOutput. I can display the output on the screen, but I need to save the image (with facemesh) in the device. 
Looking forward to any insights on this query and thank you in advance,

**Comment by sgowroji** [comment]
Hi @Monibsediqi, We are using Camera X library in Android.  You can use [Image capture](https://developer.android.com/reference/androidx/camera/core/ImageCapture) to  capture the image and save.  You can try [this](https://medium.com/swlh/how-to-create-a-simple-camera-app-using-android-camerax-library-7367778498e0) if your usecase is similar. Please reach out, if you encounter any error. Thanks!

**Comment by Monibsediqi** [comment]
Thank you so much for the prompt reply, I will check it out. For now, I'm using Camera2 API. I mainly, need to save the output stream from the mediapipe graph produced by processor object of FrameProcessor. 
I will try the provided solution for now.

**Comment by sgowroji** [comment]
Thank you for the update. We are closing this issue now. Please feel free to reach us if you have any further queries relevant to the above context.

**Comment by NaveenPokhriyal** [comment]
@sgowroji  i'm using camera x, takePicture method.
however it's saving the image but without any effect, could you please explain how we can do it?
