### ISSUE TITLE
Errors to link absl. ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by yuxiaohui78** [google/mediapipe#2147]
I tried to build a framework for iOS. But I got the following link errors.
Could you give me some suggestions to fix this issue? Thanks!
============Link errors==========
Undefined symbols for architecture arm64:
  "absl::lts_2020_09_23::InternalError(absl::lts_2020_09_23::string_view)", referenced from:
      absl::lts_2020_09_23::Status mediapipe::Packet::ValidateAsType<mediapipe::NormalizedLandmarkList>() const in libHandTrackerLibrary.a(HandTracker.o)
  "absl::lts_2020_09_23::strings_internal::CatPieces(std::initializer_list<absl::lts_2020_09_23::string_view>)", referenced from:
      absl::lts_2020_09_23::Status mediapipe::Packet::ValidateAsType<mediapipe::NormalizedLandmarkList>() const in libHandTrackerLibrary.a(HandTracker.o)
  "absl::lts_2020_09_23::InvalidArgumentError(absl::lts_2020_09_23::string_view)", referenced from:
      absl::lts_2020_09_23::Status mediapipe::Packet::ValidateAsType<mediapipe::NormalizedLandmarkList>() const in libHandTrackerLibrary.a(HandTracker.o)
      absl::lts_2020_09_23::StatusOr<std::__1::vector<google::protobuf::MessageLite const*, std::__1::allocator<google::protobuf::MessageLite const*> > > mediapipe::packet_internal::ConvertToVectorOfProtoMessageLitePtrs<mediapipe::NormalizedLandmarkList>(mediapipe::NormalizedLandmarkList const*, std::__1::integral_constant<bool, false>) in libHandTrackerLibrary.a(HandTracker.o)
  "absl::lts_2020_09_23::ByString::ByString(absl::lts_2020_09_23::string_view)", referenced from:
      absl::lts_2020_09_23::strings_internal::Splitter<absl::lts_2020_09_23::strings_internal::SelectDelimiter<char const*>::type, absl::lts_2020_09_23::AllowEmpty> absl::lts_2020_09_23::StrSplit<char const*>(absl::lts_2020_09_23::strings_internal::ConvertibleToStringView, char const*) in libHandTrackerLibrary.a(HandTracker.o)
  "absl::lts_2020_09_23::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, absl::lts_2020_09_23::string_view)", referenced from:
      mediapipe::NormalizedLandmarkList const& mediapipe::Packet::Get<mediapipe::NormalizedLandmarkList>() const in libHandTrackerLibrary.a(HandTracker.o)
  "absl::lts_2020_09_23::ByString::Find(absl::lts_2020_09_23::string_view, unsigned long) const", referenced from:
      absl::lts_2020_09_23::strings_internal::SplitIterator<absl::lts_2020_09_23::strings_internal::Splitter<absl::lts_2020_09_23::ByString, absl::lts_2020_09_23::AllowEmpty> >::operator++() in libHandTrackerLibrary.a(HandTracker.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
Target //mediapipe/develop:HandTracker failed to build
INFO: Elapsed time: 7.163s, Critical Path: 5.87s
INFO: 4 processes: 2 internal, 2 darwin-sandbox.
FAILED: Build did NOT complete successfully

============The Bazel script==========
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_framework")

ios_framework(
    name = "HandTracker",
    hdrs = [
        "HandTracker.h",
    ],
    infoplists = ["Info.plist"],
    bundle_id = "dev.noppe.HandTracker",
    families = ["iphone", "ipad"],
    minimum_os_version = "10.0",
    deps = [
        ":HandTrackerLibrary",
        "@ios_opencv//:OpencvFramework",
    ],
)

objc_library(
    name = "HandTrackerLibrary",
    srcs = [
        "HandTracker.mm",
    ],
    hdrs = [
        "HandTracker.h",
    ],
    data = [
        "//mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu_binary_graph",
        "//mediapipe/modules/hand_landmark:hand_landmark.tflite",
        "//mediapipe/modules/hand_landmark:handedness.txt",
        "//mediapipe/modules/palm_detection:palm_detection.tflite",
        "//mediapipe/modules/palm_detection:palm_detection_labelmap.txt",
    ],
    sdk_frameworks = [
        "AVFoundation",
        "CoreGraphics",
        "CoreMedia",
        "UIKit"
    ],
    deps = [
        "//mediapipe/objc:mediapipe_framework_ios",
        "//mediapipe/objc:mediapipe_input_sources_ios",
        "//mediapipe/objc:mediapipe_layer_renderer",
    ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            "//mediapipe/graphs/hand_tracking:mobile_calculators",
            "//mediapipe/framework/formats:landmark_cc_proto",
        ],
    }),
)

========The command I ran======
bazel build -c opt --config=ios_arm64  --verbose_failures mediapipe/develop:HandTracker

**Comment by nakshatrasinghh** [comment]
Hi, can you tell me how you installed MediaPipe on m1 silicon Macs?

**Comment by ljmkimqx** [comment]
Is there a solution? @yuxiaohui78

**Comment by nswdewy** [comment]
Hi, bros!  @yuxiaohui78 @ljmkimqx 
I also get the similar error "'absl/memory/memory.h' file not found"
Have you got any solution?

**Comment by nswdewy** [comment]
Hi, bros!  @yuxiaohui78 @ljmkimqx 
I also get the similar error "'absl/memory/memory.h' file not found"
Have you got any solution?

**Comment by nswdewy** [comment]
Hi, bros!  @yuxiaohui78 @ljmkimqx 
I also get the similar error "'absl/memory/memory.h' file not found"
Have you got any solution?

**Comment by nswdewy** [comment]
Hi, bros!  @yuxiaohui78 @ljmkimqx 
I also get the similar error "'absl/memory/memory.h' file not found"
Have you got any solution?

**Comment by nswdewy** [comment]
Hi, bros!  @yuxiaohui78 @ljmkimqx 
I also get the similar error "'absl/memory/memory.h' file not found"
Have you got any solution?

**Comment by nswdewy** [comment]
Hi, bros!  @yuxiaohui78 @ljmkimqx 
I also get the similar error "'absl/memory/memory.h' file not found"
Have you got any solution?

**Comment by nswdewy** [comment]
Hi, bros!  @yuxiaohui78 @ljmkimqx 
I also get the similar error "'absl/memory/memory.h' file not found"
Have you got any solution?

**Comment by nswdewy** [comment]
> Hi, can you tell me how you installed MediaPipe on m1 silicon Macs?

According to the offical chapter "[Installtion](https://google.github.io/mediapipe/getting_started/install.html#installing-on-macos)" can install it, and pay attention to "Install Bazelisk" instead of "Install Bazel"

**Comment by ozgurshn** [comment]
I'm facing similar issue is there any solution? I'm not on M1 MAC though. https://github.com/google/mediapipe/issues/2275#issuecomment-877064885

**Comment by sgowroji** [comment]
Hi @yuxiaohui78, Could you please try this https://github.com/google/mediapipe/issues/2275#issuecomment-877145926. I see @ozgurshn has resolved his issue.
