### ISSUE TITLE
Difficulty in interpreting the output of iris_landmark.tflite model

### ISSUE THREAD

**Issue by Monibsediqi** [google/mediapipe#2148]
Hi, I used the iris_landmark tflite model directly to predict the iris landmark coordiante in the cropped eye region. I got the outputs for eye contours (1x213) and the iris (1x15). However, the output of the iris landmark is too huge. Any assistance on interpreting the iris_landmark value? 
Also, am I missing any preprocessing of the image before passing to the iris_landmark model? 
Here's the output from the android.
Iris Model : irisLandmark0 : 33622.66
MainActivity: Iris Model : irisLandmark1 : 40253.42
MainActivity: Iris Model : irisLandmark2 : -12502.074
MainActivity: Iris Model : irisLandmark3 : 35584.098
MainActivity: Iris Model : irisLandmark4 : 40448.63
MainActivity: Iris Model : irisLandmark5 : -12321.352
MainActivity: Iris Model : irisLandmark6 : 28991.113
MainActivity: Iris Model : irisLandmark7 : 36829.066
MainActivity: Iris Model : irisLandmark8 : -12942.238
MainActivity: Iris Model : irisLandmark9 : 36043.59
MainActivity: Iris Model : irisLandmark10 : 44448.516
MainActivity: Iris Model : irisLandmark11 : -14311.499
MainActivity: Iris Model : irisLandmark12 : 41065.805
MainActivity: Iris Model : irisLandmark13 : 42961.56
MainActivity: Iris Model : irisLandmark14 : -15212.4795

Any help/insights would be highly appreciated,

**Comment by sgowroji** [comment]
Hi @Monibsediqi, Could you please provide your code changes to understand it much better. Thanks

**Comment by Monibsediqi** [comment]
Thank you for the prompt response, 
I need to get the iris_landmark right in the cropped eye image coordinate, so I am trying to use the iris_landmark.tflite model directly. 

Here is part of the code to convert the bitmap into bytebuffer to feed into the tflite model. 
   private fun initInputArray(bitmap: Bitmap, inputChannelsImage: Int = 1): ByteBuffer {
        val bytesPerChannel = 4
        val inputChannels = inputChannelsImage
        val batchSize = 1
        val inputBuffer = ByteBuffer.allocateDirect(
                batchSize * bytesPerChannel * bitmap.height * bitmap.width * inputChannels
        )
        inputBuffer.order(ByteOrder.nativeOrder())
        inputBuffer.rewind()

        val mean = 0.0f
        val std = 1.0f
        val intValues = IntArray(bitmap.width * bitmap.height)
        bitmap.getPixels(intValues, 0, bitmap.width, 0, 0, bitmap.width, bitmap.height)
        for (pixelValue in intValues) {
            if (inputChannels == 1) {
                inputBuffer.putFloat(Color.red(pixelValue).toFloat())
                // inputBuffer.putFloat(pixelValue and 0xFF)   ?is it correct, may be correct :v
            } else {
                inputBuffer.putFloat(((pixelValue shr 16 and 0xFF) - mean) / std)
                inputBuffer.putFloat(((pixelValue shr 8 and 0xFF) - mean) / std)
                inputBuffer.putFloat(((pixelValue and 0xFF) - mean) / std)
            }
        }

        return inputBuffer
    }

As you can see, the image passed to the model without any preprocessing. 
One more questions, 
1. Does the input image needs to be processed between a certain range such as [0,1] or [-1,1]?

Thank you so much, looking forward

**Comment by sonfire186** [comment]
@sgowroji up

**Comment by jysung** [comment]
Did you figure out how to use the tflite file directly?

**Comment by ayushgdev** [comment]
Hello @Monibsediqi Thanks for this wonderful observation. The Iris solution model actually takes a normalized image of size 64x64x3 (between 0 and 1) as input and produces output landmark coordinates. So you need to normalize the image first as
```
img_norm = cv2.normalize(img, None, 0, 1.0, cv2.NORM_MINMAX)
```
Further, we would like to notify this model has been deprecated in favour of FaceMesh solution since it includes [two models](https://github.com/google/mediapipe/blob/215465bee0dc71a4cc971a5bd83cb0cf09833f31/docs/solutions/models.md#face-mesh)- one with attention and one without attention. The [one with attention](https://github.com/google/mediapipe/blob/master/docs/solutions/face_mesh.md#attention-mesh-model) provides iris landmarks as well.
