### ISSUE TITLE
Error using docker mode to run object_detection_tensorflow

### ISSUE THREAD

**Issue by lyleaf** [google/mediapipe#215]
**Error using docker mode to run object_detection_tensorflow.** 
```

docker run -it --name mediapipe mediapipe:latest

bazel build -c opt     --define MEDIAPIPE_DISABLE_GPU=1     --define no_aws_support=true mediapipe/examples/desktop/object_detection:object_detection_tensorflow --verbose_failures

```

WARNING: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/tensorflow/core/BUILD:2535:12: in srcs attribute of cc_library rule @org_tensorflow//tensorflow/core:gif_internal: please do not import '@org_tensorflow//tensorflow/core/platform:gif.h' directly. You should either move the file to this package or depend on an appropriate rule there
WARNING: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/tensorflow/core/BUILD:2555:12: in srcs attribute of cc_library rule @org_tensorflow//tensorflow/core:jpeg_internal: please do not import '@org_tensorflow//tensorflow/core/platform:jpeg.h' directly. You should either move the file to this package or depend on an appropriate rule there
INFO: Analyzed target //mediapipe/examples/desktop/object_detection:object_detection_tensorflow (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[10 / 143] 128 actions, 4 running
    Compiling external/org_tensorflow/.../core/kernels/bias_op.cc; 211s processwrapper-sandbox
    Compiling external/org_tensorflow/.../kernels/cwise_op_add_2.cc; 90s processwrapper-sandbox
    @org_tensorflow//tensorflow/core/kernels:cast_op; 85s processwrapper-sandbox
    @org_tensorflow//tensorflow/core:tpu_embedding_ops_op_lib; 84s processwrapper-sandbox
    [Sched] Compiling external/org_tensorflow/tensorflow/core/kernels/cwise_op_xdivy.cc; 210s
[10 / 143] 128 actions, 4 running
    Compiling external/org_tensorflow/.../core/kernels/bias_op.cc; 1006s processwrapper-sandbox
    @org_tensorflow//tensorflow/core/kernels:cwise_op; 886s processwrapper-sandbox
    @org_tensorflow//tensorflow/core/kernels:cast_op; 880s processwrapper-sandbox
    @org_tensorflow//tensorflow/core:tpu_embedding_ops_op_lib; 880s processwrapper-sandbox
    [Sched] Compiling external/org_tensorflow/tensorflow/core/kernels/cwise_op_xdivy.cc; 1006s
    [Sched] @org_tensorflow//tensorflow/core:framework_internal_impl; 1006s
    [Sched] Compiling external/org_tensorflow/tensorflow/core/util/bcast.cc [for host]; 1006s
ERROR: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/tensorflow/core/kernels/BUILD:4361:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:bias_op' failed (Exit 4) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 210 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
[138 / 144] @org_tensorflow//tensorflow/core/kernels:cwise_op; 12s processwrapper-sandbox

[138 / 144] @org_tensorflow//tensorflow/core/kernels:cwise_op; 13s processwrapper-sandbox
Target //mediapipe/examples/desktop/object_detection:object_detection_tensorflow failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1324.062s, Critical Path: 1115.40s
INFO: 11 processes: 11 processwrapper-sandbox.

**Comment by jiuqiant** [comment]
Hi, thanks for reporting this issue to us. May I know what os system you are using? Moreover, from the error message, it seems like a gcc compiler error. Could you report your gcc version as well? You can use `gcc --version`  to find it.

I was trying to reproduce this issue on Ubuntu and Debian. But, it seems ok.

```
root@7d14c42da169:/mediapipe# gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
root@7d14c42da169:/mediapipe# 
root@7d14c42da169:/mediapipe# bazel build -c opt     --define MEDIAPIPE_DISABLE_GPU=1     --define no_aws_support=true mediapipe/examples/desktop/object_detection:object_detection_tensorflow --verbose_failures
......
Target //mediapipe/examples/desktop/object_detection:object_detection_tensorflow up-to-date:
  bazel-bin/mediapipe/examples/desktop/object_detection/object_detection_tensorflow
INFO: Elapsed time: 209.746s, Critical Path: 145.82s
INFO: 2663 processes: 2 local, 2661 processwrapper-sandbox.
INFO: Build completed successfully, 2716 total actions
```

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
