### ISSUE TITLE
Android FrameProcessor method close() will crash

### ISSUE THREAD

**Issue by solmate-james** [google/mediapipe#2150]
I use face detection and hair segmentation, both of which work when used alone.
My situation is that face detection is turned on in Activity, and there is a Bottom Navigation Bar at the bottom of the screen. When you click on it will switch Fragment. 
After entering Fragment will turn on hair segmentation, but the App will crash. 

com.google.mediapipe.framework.MediaPipeException: not found ValidatedGraphConfig Initialization failed
![截圖 2021-06-09 下午3 17 13](https://user-images.githubusercontent.com/80659447/121323132-26264980-c942-11eb-94e4-dadea5965745.png)

I think the implementation of FrameProcessor is caused by singleton.
So I want to close the FrameProcessor before entering the Fragment
But it will crash directly when I call it. 

![截圖 2021-06-09 下午3 48 33](https://user-images.githubusercontent.com/80659447/121323384-5a9a0580-c942-11eb-8611-e0a883da1aeb.png)

How do I use FrameProcessor close() well?

#1555 #580 
I have confirmed the above two questions. It seems that they only use one model, so they can singleton FrameProcessor, but I have to set a different mobile_gpu.binarypb in new FrameProcessor(), the situation is different.

**Comment by sgowroji** [comment]
Assuming the above issue is often due to finding the calculator dependencies. Can you provide all the steps to reproduce the above error. With respective details like  android phone and its version.

**Comment by solmate-james** [comment]
@sgowroji 
I think #1450 has no way to help me solve it. He seems to be misplaced aar.

I use a simple example to replicate the processor.close() crash problem.
https://github.com/jiuqiant/mediapipe_face_detection_aar_example
I cloned the above code, and only added a button to the xml. When I click it, I call processor.close() and it will crash.

activity_main.xml
<Button
        android:id="@+id/button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="processor.close()"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

MainActvitiy.java
Button button = findViewById(R.id.button);
button.setOnClickListener(view -> {
    if (processor != null) processor.close();
});

My Android phone is Samsung (Galaxy A8+), and the Android version is 9.0.
Thanks for your reply!

**Comment by jiuqiant** [comment]
@camillol knows the FrameProcessor better than @mcclanahoochie and me. It's better to ask @camillol to take a look.

**Comment by solmate-james** [comment]
@camillol Could you help me~?

**Comment by ayushgdev** [comment]
@solmate-james Are you still looking for a resolution?
