### ISSUE TITLE
Support to reset Holistic solution's tracking for videos

### ISSUE THREAD

**Issue by GokulNC** [google/mediapipe#2152]
**Use-case:**

I am generating pose for multiple videos using Python.
So for each video, since I have `static_image_mode=False` for [tracking-based pose inference on Holistic](https://google.github.io/mediapipe/solutions/holistic.html#static_image_mode), I am forced to create new model instances so that the output is proper.

**Feature Request:**

A method in the holistic function (like `holistic_instance.reset_tracking()`) to reset the entire state of the object (just like creating a fresh object) so that I do not have to create and load models again-&-again for each video.

**Advantages:**

- Faster inference for multiple videos
- Workaround for the [memory leak issue currently in Holistic](https://github.com/google/mediapipe/issues/1937/#issuecomment-833780468) which is causing the RAM to explode after sometime for this use-case and the program crashes.
- Workaround for [this logs-flooding issue](https://github.com/google/mediapipe/issues/2119). (Prints the logs only once if only 1 object)

**Comment by afogel** [comment]
@sgowroji this would be great for JS too :)

**Comment by mhays-google** [comment]
The javascript api includes a "reset" method to do this.  Check that you
are using the latest version.

**Comment by sgowroji** [comment]
Hi @GokulNC, Did you get a chance to test the above?

**Comment by GokulNC** [comment]
Hi @sgowroji 

My request was for Python, and it is not yet implemented in that.
The comment by him was for JavaScript, to respond to another person.

**Comment by jiuqiant** [comment]
You can modify solution_base.py like the following to achieve this:

```
diff --git a/mediapipe/python/solution_base.py b/mediapipe/python/solution_base.py
index 215b531..d65f43a 100644
--- a/mediapipe/python/solution_base.py
+++ b/mediapipe/python/solution_base.py
@@ -254,11 +254,11 @@
     for stream_name in self._output_stream_type_info.keys():
       self._graph.observe_output_stream(stream_name, callback, True)
 
-    input_side_packets = {
+    self._input_side_packets = {
         name: self._make_packet(self._side_input_type_info[name], data)
         for name, data in (side_inputs or {}).items()
     }
-    self._graph.start_run(input_side_packets)
+    self._graph.start_run(self._input_side_packets)
 
   # TODO: Use "inspect.Parameter" to fetch the input argument names and
   # types from "_input_stream_type_info" and then auto generate the process
@@ -353,6 +353,12 @@
     self._input_stream_type_info = None
     self._output_stream_type_info = None
 
+  def reset(self) -> None:
+    """Resets the graph for another run."""
+    if self._graph:
+      self._graph.close()
+      self._graph.start_run(self._input_side_packets)
+
   def _initialize_graph_interface(
       self,
       validated_graph: validated_graph_config.ValidatedGraphConfig,
``

**Comment by GokulNC** [comment]
Thanks a lot, will apply the patch and test it.

Will this `reset()` method be there in the upcoming version?
Or am I supposed to modify like this even for next updates?

**Comment by GokulNC** [comment]
Thanks, works good. Looks like the patch is [already pushed](https://github.com/google/mediapipe/blob/b899d17f185f6bcbf3f5947d3e134f8ce1e69407/mediapipe/python/solution_base.py#L356), hence closing the issue.
