### ISSUE TITLE
Although we have partially solved the problem of Z-axis in hand's 21 keypoints (WEB + JavaScript) in another way, there is still a little inaccuracy. When will the z-axis obtained from the native model be released?

### ISSUE THREAD

**Issue by lowpair** [google/mediapipe#2155]
Although we have partially solved the problem of Z-axis in hand's 21 keypoints (WEB + JavaScript) in another way, there is still a little inaccuracy. When will the z-axis obtained from the native model be released?

Refer to other materials and share the ways I am temporarily dealing with:

<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/110/three.min.js"></script>

// Converting webcam coordinates to 3js 3D coordinates
function webcam2space(x,y,z){
  return new THREE.Vector3(
     (x-videoElement.videoWidth /2),
    -(y-videoElement.videoHeight/2), // in threejs, +y is up
    - z
  )
}

function onResults(results) {
  canvasCtx.save();
  canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
  canvasCtx.drawImage(
      results.image, 0, 0, canvasElement.width, canvasElement.height);
  if (results.multiHandLandmarks) {
    for (const landmarks of results.multiHandLandmarks) {
      drawConnectors(canvasCtx, landmarks, HAND_CONNECTIONS,
                     {color: '#00FF00', lineWidth: 5});
                     
      console.log(landmarks[2].x.toFixed(5) + " " +landmarks[2].y.toFixed(5) + " " +landmarks[2].z.toFixed(5) );
      
      tx = landmarks[2].x.toFixed(5);
      ty = 1-landmarks[2].y.toFixed(5);// 
      
      
      // Select 0 and 5 as the points to calculate the depth
      var p0 = webcam2space(landmarks[0].x,landmarks[0].y,landmarks[0].z);  // 
      var p1 = webcam2space(landmarks[5].x,landmarks[5].y,landmarks[5].z);  // 
      var z0 = (p0.distanceTo(p1)-0.15)*3;
      
      // Visual display
      xdata.data.push( tx );
      ydata.data.push( ty );
      zdata.data.push( z0 );
      
      //socket.emit('hand',{x:landmarks[2].x.toFixed(5),y:1-landmarks[2].y.toFixed(5),z:z0});
      
      sdata = [xdata,ydata,zdata];
      
      myChart.setOption({series:sdata});
      drawLandmarks(canvasCtx, landmarks, {color: '#FF0000', lineWidth: 2});
    }
  }
  canvasCtx.restore();
}

The above is shared with those who are troubled by z-axis, waiting for the latest official solution;

**Comment by lowpair** [comment]
<img width="616" alt="屏幕截图 2021-06-10 120404" src="https://user-images.githubusercontent.com/5057975/121464084-caad9780-c9e5-11eb-8695-9d312ee45153.png">

**Comment by sgowroji** [comment]
Hi @lowpair, Could you please elaborate your inaccuracy with any video or error logs to understand the issue much better. Thanks!

**Comment by mhays-google** [comment]
The z axis from the underlying model is a relative, non-scaled measurement,
meaning that while there is a relative depth, you would not be able to use
this to recreate the 3d position of the hand.  This is what we serve to the
javascript layer.  Is there something that suggests that there is more?
