### ISSUE TITLE
Building mediapipe package in python on Ubuntu 18.04

### ISSUE THREAD

**Issue by sahaashi** [google/mediapipe#2156]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 18.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc/g++ 8.4.0
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python version 3.6.7
- Installed using virtualenv? pip? Conda? (if python): virtualenv
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.3
- Bazel version: 4.1.0
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): 3.4

**Describe the problem**:
I am trying to build mediapipe on python on my ubuntu distribution 18.04. I have followed the steps from mediapipe webpage.
When running python3 setup.py gen_protos, I get some errors that I have copied below.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

1. git clone mediapipe from github
2. build opencv using option 2 from mediapipe page, that is, running the command ./setup_opencv.sh
3. sudo apt install python3-dev, python3-venv, -y protobuf-compiler, already had cmake installed.
3. created virtual environment, installed packages from requirement.txt
4. python3 setup.py gen_protos (resulted in error copied below)

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:
"""
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running gen_protos
generating proto file: mediapipe/framework/calculator_pb2.py
google/protobuf/any.proto: File not found.
mediapipe/framework/calculator.proto: Import "google/protobuf/any.proto" was not found or had errors.
mediapipe/framework/calculator.proto:273:14: "google.protobuf.Any" is not defined.
mediapipe/framework/calculator.proto:429:12: "google.protobuf.Any" is not defined.
"""

**Comment by sahaashi** [comment]
I upgraded the Ubuntu to the version 20.04. Then, I followed the same procedure to build the mediapipe package and it worked.

**Comment by sgowroji** [comment]
Glad to know you resolved. We are closing this issue.
