### ISSUE TITLE
'NoneType' object has no attribute 'landmark'

### ISSUE THREAD

**Issue by funnypig521** [google/mediapipe#2157]
When I use a = results.pose_landmarks.landmark[23].x,I meet this problem 'NoneType' object has no attribute 'landmark'.But  mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS) can work normally.Is anybody encounter the same problem?Thanks a lot!!!!!!!

**Comment by Vishwa-0216** [comment]
What os are you using?
Windows, mac or linux?

**Comment by funnypig521** [comment]
> 你用的是什么操作系统？
> Windows、Mac 还是 Li Windows

**Comment by funnypig521** [comment]
Both Windows and  Linux have the same problem!!!!

**Comment by sgowroji** [comment]
Hi @funnypig521, Could you Please provide the steps to reproduce the above error. Thanks!

**Comment by funnypig521** [comment]
`import cv2

import time
import multiprocessing as mp
import cv2
import mediapipe as mpp
mp_drawing = mpp.solutions.drawing_utils
mp_holistic = mpp.solutions.holistic

def image_put(q, name, pwd, ip, channel=1):
    cap = cv2.VideoCapture("rtsp://%s:%s@%s//Streaming/Channels/%d" % (name, pwd, ip, channel))
    while True:
        q.put(cap.read()[1])
        q.get() if q.qsize() > 1 else time.sleep(0.01)

def image_get(q, window_name):
    cv2.namedWindow(window_name, flags=cv2.WINDOW_FREERATIO)
    while True:
        image = q.get()
        with mp_holistic.Holistic(
                min_detection_confidence=0.5,
                min_tracking_confidence=0.5) as holistic:

            # Flip the image horizontally for a later selfie-view display, and convert
            # the BGR image to RGB.
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            # To improve performance, optionally mark the image as not writeable to
            # pass by reference.
            image.flags.writeable = False
            results = holistic.process(image)

            # Draw landmark annotation on the image.
            image.flags.writeable = True
            for i in range(0,11):
                results.pose_landmarks.landmark[i].x = 0
                results.pose_landmarks.landmark[i].y = 0
            image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
            mp_drawing.draw_landmarks(
                image, results.face_landmarks, mp_holistic.FACE_CONNECTIONS)
            mp_drawing.draw_landmarks(
                image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS)
            mp_drawing.draw_landmarks(
                image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS)
            mp_drawing.draw_landmarks(
                image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS)
            a = results.pose_landmarks.landmark[23].x
            b = results.pose_landmarks.landmark[32].x
            c = results.pose_landmarks.landmark[23].visibility
            cv2.imshow('MediaPipe Holistic', image)

    #cv2.imshow(window_name, frame)
    #cv2.waitKey(1)

def run_multi_camera():
    # user_name, user_pwd = "admin", "password"
    user_name, user_pwd = "admin", "password"
    camera_ip_l = [
        "192.168.1.11",
    ]

    mp.set_start_method(method='spawn')  # init
    queues = [mp.Queue(maxsize=4) for _ in camera_ip_l]
    print(queues)

    processes = []
    for queue, camera_ip in zip(queues, camera_ip_l):
        processes.append(mp.Process(target=image_put, args=(queue, user_name, user_pwd, camera_ip)))
        processes.append(mp.Process(target=image_get, args=(queue, camera_ip)))

    for process in processes:
        process.daemon = True
        process.start()
    for process in processes:
        process.join()

if __name__ == '__main__':
    run_multi_camera()`

**Comment by funnypig521** [comment]
`import cv2

import time
import multiprocessing as mp
import cv2
import mediapipe as mpp
mp_drawing = mpp.solutions.drawing_utils
mp_holistic = mpp.solutions.holistic

def image_put(q, name, pwd, ip, channel=1):
    cap = cv2.VideoCapture("rtsp://%s:%s@%s//Streaming/Channels/%d" % (name, pwd, ip, channel))
    while True:
        q.put(cap.read()[1])
        q.get() if q.qsize() > 1 else time.sleep(0.01)

def image_get(q, window_name):
    cv2.namedWindow(window_name, flags=cv2.WINDOW_FREERATIO)
    while True:
        image = q.get()
        with mp_holistic.Holistic(
                min_detection_confidence=0.5,
                min_tracking_confidence=0.5) as holistic:

            # Flip the image horizontally for a later selfie-view display, and convert
            # the BGR image to RGB.
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            # To improve performance, optionally mark the image as not writeable to
            # pass by reference.
            image.flags.writeable = False
            results = holistic.process(image)

            # Draw landmark annotation on the image.
            image.flags.writeable = True
            for i in range(0,11):
                results.pose_landmarks.landmark[i].x = 0
                results.pose_landmarks.landmark[i].y = 0
            image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
            mp_drawing.draw_landmarks(
                image, results.face_landmarks, mp_holistic.FACE_CONNECTIONS)
            mp_drawing.draw_landmarks(
                image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS)
            mp_drawing.draw_landmarks(
                image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS)
            mp_drawing.draw_landmarks(
                image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS)
            a = results.pose_landmarks.landmark[23].x
            b = results.pose_landmarks.landmark[32].x
            c = results.pose_landmarks.landmark[23].visibility
            cv2.imshow('MediaPipe Holistic', image)

    #cv2.imshow(window_name, frame)
    #cv2.waitKey(1)

def run_multi_camera():
    # user_name, user_pwd = "admin", "password"
    user_name, user_pwd = "admin", "password"
    camera_ip_l = [
        "192.168.1.11",
    ]

    mp.set_start_method(method='spawn')  # init
    queues = [mp.Queue(maxsize=4) for _ in camera_ip_l]
    print(queues)

    processes = []
    for queue, camera_ip in zip(queues, camera_ip_l):
        processes.append(mp.Process(target=image_put, args=(queue, user_name, user_pwd, camera_ip)))
        processes.append(mp.Process(target=image_get, args=(queue, camera_ip)))

    for process in processes:
        process.daemon = True
        process.start()
    for process in processes:
        process.join()

if __name__ == '__main__':
    run_multi_camera()`

**Comment by jiuqiant** [comment]
If no human pose is detected, the fields in the "results" object is set to None. Before accessing `results.pose_landmarks`, please check if it's None. See our example code at https://github.com/google/mediapipe/blob/master/docs/solutions/pose.md#python-solution-api.

**Comment by sgowroji** [comment]
Hi @funnypig521, Please take a look at the above [comment](https://github.com/google/mediapipe/issues/2157#issuecomment-861059183).

**Comment by funnypig521** [comment]
It works.Thank you very much!!!!!!
