### ISSUE TITLE
Unable to build the helloworld example

### ISSUE THREAD

**Issue by xizhang** [google/mediapipe#2158]
Build command:
`bazel build -c opt --config=android_arm64 :helloworld`

The error I got:
`ERROR: /Users/xizh/Workspace/mediapipe/mediapipe/framework/formats/BUILD:69:24: C++ compilation of rule '//mediapipe/framework/formats:matrix_data_cc_proto' failed (Exit 1): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 -target ... (remaining 52 argument(s) skipped)`

Each time I build, I get a different error but they all point to the ndk:

`ERROR: /private/var/tmp/_bazel_xizh/931f8d7aab34dcf49b08af66be788d69/external/com_google_absl/absl/hash/BUILD.bazel:98:11: C++ compilation of rule '@com_google_absl//absl/hash:city' failed (Exit 1): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 -target ... (remaining 52 argument(s) skipped)`

The NDK version is 18.xxx. It's an earlier version because the latest doesn't have the platform/ folder which also breaks.

**Comment by sgowroji** [comment]
Hi @xizhang, Did you followed the step mentioned at [here](https://google.github.io/mediapipe/getting_started/android.html#building-android-example-apps). Thanks!

**Comment by xizhang** [comment]
Following the instruction, I failed at building the handtracking GPU project:

`bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu`

This is the error. It seems bazel was unable to pull dependencies.

`FAILED: Build did NOT complete successfully (99 packages loaded, 8707 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//mediapipe/gpu:pixel_buffer_pool_util, config=BuildConfigurationValue.Key[5d8be7d3b63d22369e641ffa4417bfdc2125aa849a4e329efa43184a4871cf75]}' (requested by nodes 'ConfiguredTargetKey{label=//mediapipe/gpu:gpu_buffer_multi_pool, config=BuildConfigurationValue.Key[5d8be7d3b63d22369e641ffa4417bfdc2125aa849a4e329efa43184a4871cf75]}', 'ConfiguredTargetKey{label=//mediapipe/objc:mediapipe_framework_ios, config=BuildConfigurationValue.Key[5d8be7d3b63d22369e641ffa4417bfdc2125aa849a4e329efa43184a4871cf75]}')`

**Comment by xizhang** [comment]
After switching to ndk r19c, I am able to build the helloworld project. I will file a separate issue for not pulling dependencies.

**Comment by ArtanBerisha1** [comment]
how did you switch to idk rc19c ? , does this mean uninstalling the other versions ?
