### ISSUE TITLE
Hello, I want to get from the gesture detection, the customer's gesture is "OK", "Rock", and "Spiderman". What should we do?

### ISSUE THREAD

**Issue by Sanerly** [google/mediapipe#216]
Hello, I want to get from the gesture detection, the customer's gesture is "OK", "Rock", and "Spiderman". What should we do?

And the arr I packaged is 2d by default and I want to change it to 3d. I didn't find this function

**Comment by JECBello** [comment]
Are you using the desktop version? If so, you can reference the related issue #202 to change it to 3D.

**Comment by Sanerly** [comment]
> @Sanerly您使用的是桌面版本吗？如果是这样，您可以参考相关的问题[＃202](https://github.com/google/mediapipe/issues/202)将其更改为3D。

Hello,I'm using the mobile version, and I want to recognize the "ok" of the gesture

**Comment by psykid** [comment]
I think [#296 ](https://github.com/google/mediapipe/issues/296) can help you.

**Comment by laisuki1109** [comment]
Hey guys, I modify the TensorFlow demo app, so it can run the palm model and hand landmark model.
please go https://github.com/laisuki1109/handtracking-with-Mediapipe to explore more !
With **Java**
you can set custom hand pose by xy coordinate
Thank you!
