### ISSUE TITLE
Setting up iris in python

### ISSUE THREAD

**Issue by sahaashi** [google/mediapipe#2160]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 20.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): 8.4.0
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.8
- Installed using virtualenv? pip? Conda? (if python): virtualenv
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8
- Bazel version: 3.7.2
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): 3.4

**Describe the problem**:
I have followed the instruction mentioned in issue #1530  to setup iris solution in python. I managed to build the package however, when importing the library throws an error shown below.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
I have built the package with these steps:
- OpenCV installation first with `./setup_opencv.sh` and then with `sudo apt-get install libopencv...` as mentioned in option 1 getting started mediapipe github page.
- Installed the dependencies using the step 2 of this [link](https://google.github.io/mediapipe/getting_started/python.html#building-mediapipe-python-package)
- created and activated the virtual environment
- installed the packages listed in requirement.txt
- generated mediapipe package with `python3 setup.py gen_protos`
- installed the package with `python3 setup.py install --link-opencv`

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:
```
In [1]: import mediapipe as mp
---------------------------------------------------------------------------
ImportError   Traceback (most recent call last)
<ipython-input-1-02d7ea80336e> in <module>
----> 1 import mediapipe as mp
~/Documents/mediapipe_with_iris/mp_iris_env/lib/python3.8/site-packages/mediapipe/__init__.py in <module>
     14 """
     15 
---> 16 from mediapipe.python import *
     17 import mediapipe.python.solutions as solutions

~/Documents/mediapipe_with_iris/mp_iris_env/lib/python3.8/site-packages/mediapipe/python/__init__.py in <module>
     15 """MediaPipe Python API."""
     16 
---> 17 from mediapipe.python._framework_bindings import resource_util
     18 from mediapipe.python._framework_bindings.calculator_graph import CalculatorGraph
     19 from mediapipe.python._framework_bindings.calculator_graph import GraphInputStreamAddMode

ImportError: ~/Documents/mediapipe_with_iris/mp_iris_env/lib/python3.8/site-packages/mediapipe/python/_framework_bindings.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2cv3MatC1Eiii
```

**Comment by sgowroji** [comment]
Hi @sahaashi,  can you try [this](https://github.com/google/mediapipe/issues/2056#issuecomment-847187373) seems similar to your issue.

**Comment by sahaashi** [comment]
> Hi @sahaashi, can you try [this](https://github.com/google/mediapipe/issues/2056#issuecomment-847187373) seems similar to your issue.

Hi @sgowroji,
I see that this issue is meant for aarch64 architecture, whereas mine is amd64. Also, I have installed the package using `python3 setup.py install --link-opencv` and not via `python3 setup.py bdist_wheel`. I had also tried with bdist_wheel but some for reason, after installing the package, I could not see the mediapipe library in /python3/sitepackages/.

**Comment by sahaashi** [comment]
@jiuqiant Any suggestions?

**Comment by jiuqiant** [comment]
For some reason, OpenCV is not probably linked. See https://github.com/google/mediapipe/blob/master/docs/getting_started/troubleshooting.md#incorrect-mediapipe-opencv-config for suggestions. You also can try "python3 setup.py install" without "--link-opencv" to build opencv from source to get rid of this issue. Please note that this approach takes much longer time to build the python package.

**Comment by sahaashi** [comment]
Thanks for the reply. I have managed to install mediapipe package (one without the iris) using --link-opencv. I am just wondering why after making changes to include the iris implementation gives me this error. I can try doing it again without --link-opencv and see if it works.

**Comment by sahaashi** [comment]
Yess, running install without --link-opencv worked. Thanks a lot!

You can close this issue now!
