### ISSUE TITLE
Changing floating point precision of joints.

### ISSUE THREAD

**Issue by IgorZaton** [google/mediapipe#2164]
Hi, I want to as if there is possibility of changing floating point precision of joints that I get from Hands project. By default it is 'float64' and I'd like to change it to 'float32'.

Thanks for help.

System:
- Windows 10

Software:
- Python 3.7
- mediapipe 0.8.4.2; Hands project

**Comment by sgowroji** [comment]
Hi @IgorZaton, Have you tried doing it like [this](https://stackoverflow.com/questions/45955186/convert-numpy-array-type-and-values-from-float64-to-float32)

**Comment by sgowroji** [comment]
Hi @IgorZaton, Could you please respond to my above [comment](https://github.com/google/mediapipe/issues/2164#issuecomment-860341264). Thanks!

**Comment by IgorZaton** [comment]
Hi, I don't mean to convert those joints to ```float32``` but to set single precision as default so my computations would be faster.

**Comment by sureshdagooglecom** [comment]
Hi @IgorZaton ,
Are you still looking for the resolution on this issue.
