### ISSUE TITLE
FrameProcessor or Graph? 

### ISSUE THREAD

**Issue by sohail-jogo** [google/mediapipe#2165]
I have seen in most of the codes that FrameProcessor is used. Can we not directly use Graph class and use its methods like addPacketToInputStream() to supply a frame (bitmap) to a node, or addPacketCallback(OUTPUT_STREAM_NAME, packet -> {} ); 

I am talking specifically for Android. Whats the difference in using FrameProcessor vs Graphs? I dont see any proper documentation related to this. I am really lost. 

Thanks!

**Comment by sohail-jogo** [comment]
???

**Comment by chuoling** [comment]
You can certainly use Graph directly. FrameProcessor (which [owns a Graph internally](https://github.com/google/mediapipe/blob/374f5e2e7e818bde5289fb3cffa616705cec6f73/mediapipe/java/com/google/mediapipe/components/FrameProcessor.java#L57) ) is really a utility layer that handles some of the common interaction with Graph for the user, e.g., wrapping an image (CPU or GPU) into a corresponding MediaPipe Packet and sending the packet into the graph.

**Comment by sohail-jogo** [comment]
Okay, Thank you for the reply! 

And Its fine if I pass bitmaps into the graph (input stream) instead of raw frames right? 

I have been getting "Fatal signal 6 (SIGABRT)" crashes after I run the app for few minutes or sometimes even seconds. And there are no descriptive error logs or traces to debug the cause of the problem. So, I was wondering if either feeding bitmaps into Graph might be causing problems. 

Anyways, It would be great if you assist me on this provided that it's your domain. Otherwise, I will close this issue. 

Issue: 
https://github.com/google/mediapipe/issues/2234

**Comment by Moufdi96** [comment]
@sohail-jogo I am getting the same error  "Fatal signal 6 (SIGABRT)" when I try to do this :

>  processor.getGraph().addPacketCallback("output_video", new PacketCallback() {
                @Override
                public void process(Packet packet) {
                        //viewGroup.removeAllViews();
                        bmp = AndroidPacketGetter.getBitmapFromRgb(packet);
                }
            });

have you by any chance figured it out ?

**Comment by sohail-jogo** [comment]
No man. I have been stuck for a month now. No solution. 
Meanwhile, I am trying to work with Movenet, it seems promising.

**Comment by sohail-jogo** [comment]
If you find a solution, then please let me know here as well. I'd be grateful.

**Comment by sgowroji** [comment]
Hi @sohail-jogo, You above comment query is answered  here https://github.com/google/mediapipe/issues/2234#issuecomment-892835698
