### ISSUE TITLE
Passing Configuration Options in PoseLandmarkGpu Calculator 

### ISSUE THREAD

**Issue by sohail-jogo** [google/mediapipe#2166]
- OS Platform and Distribution : Windows 10 Home 64 Bit, Mobile - Samsung Galaxy S9+ , Android OS Version: 10. 
- Bazel version: 3.7.2
- Solution Pose Tracking GPU
- Programming Language and version : Java (Android) 

I have made a custom pose_tracking pbtxt file which is almost the same as pose_tracking_gpu.pbtxt file in (mediapipe/graphs/pose_tracking) , but with a few changes according to my need. 

**Custom_Pose_Tracking_GPU.pbtxt file:** 

MediaPipe graph that performs pose tracking with TensorFlow Lite on GPU.

CPU buffer. (CpuBuffer)
input_stream: "input_video"

Pose landmarks. (NormalizedLandmarkList)
output_stream: "pose_landmarks"

_ Throttles the images flowing downstream for flow control. It passes through
 the very first incoming image unaltered, and waits for downstream nodes
 (calculators and subgraphs) in the graph to finish their tasks before it
 passes through another image. All images that come in while waiting are
 dropped, limiting the number of in-flight images in most part of the graph to
 1. This prevents the downstream nodes from queuing up incoming images and data
 excessively, which leads to increased latency and memory usage, unwanted in
 real-time mobile applications. It also eliminates unnecessarily computation,
 e.g., the output produced by a node may get dropped downstream if the
 subsequent nodes are still busy processing previous inputs._

node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "input_video"
  output_stream: "input_video_gpu"
}

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video_gpu"
  input_stream: "FINISHED:pose_landmarks"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

Subgraph that detects poses and corresponding landmarks.
node {
  calculator: "PoseLandmarkGpu"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "LANDMARKS:pose_landmarks"
  output_stream: "DETECTION:pose_detection"
  output_stream: "ROI_FROM_LANDMARKS:roi_from_landmarks"
}

The problem here is that, I want to pass the different configuration options for example: MODEL_COMPLEXITY for the calculator: "PoseLandmarkGpu". How can I do that? 
I know that we have to pass the options using **node_options**, but I am not exactly sure how.
Can anyone help me out? 

Thanks!

**Comment by sohail-jogo** [comment]
in other words, i want to the change the model at run time or even at compile time by changing the modelComplexity! How do I go about doing this? any leads?

**Comment by zhangupkai** [comment]
> in other words, i want to the change the model at run time or even at compile time by changing the modelComplexity! How do I go about doing this? any leads?

Did you solve this problem? I have a similar need and would like to ask you.
