### ISSUE TITLE
Unable to compile Hello World. Build did NOT complete successfully. Have tried almost all solutions already posted

### ISSUE THREAD

**Issue by ajm133** [google/mediapipe#2167]
Hello! I just recently installed mediapipe using the instructions on https://g3doc.corp.google.com/third_party/mediapipe/g3doc/getting_started/install.md?cl=head

I ran Hello World using: bazel run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
    mediapipe/examples/desktop/hello_world:hello_world
However, when running "Hello World" and any other model, I get the following error: 

/usr/local/google/home/adiljmalik/mediapipe/mediapipe/calculators/core/BUILD:583:11: C++ compilation of rule '//mediapipe/calculators/core:pass_through_calculator' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 51 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 51 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from <command-line>:
/usr/include/stdc-predef.h: In substitution of 'template<class _Functor, class, class> std::function<std::unique_ptr<mediapipe::internal::CalculatorBaseFactory>()>::function(_Functor) [with _Functor = <missing>; <template-parameter-1-2> = <missing>; <template-parameter-1-3> = <missing>]':
mediapipe/calculators/core/pass_through_calculator.cc:96:1:   required from here
/usr/include/stdc-predef.h:32:94: internal compiler error: Segmentation fault
   32 |    whether the overall intent is to support these features; otherwise,
      |                                                                                              ^                         
0x7f5dc5067d5f ???
        ./signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7f5dc5052d09 __libc_start_main
        ../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.817s, Critical Path: 4.68s
INFO: 6 processes: 6 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

If someone could guide me, I would appreciate it!

**Comment by sgowroji** [comment]
Hi @ajm133, Could you please provide the steps to reproduce the above error and which platform are you trying the above. Thanks!

**Comment by ajm133** [comment]
Running on gcc (Debian 10.2.1-6+build2) 10.2.1

cd $HOME
git clone https://github.com/google/mediapipe.git

cd mediapipe


sh ./ setup_opencv.sh
sudo apt-get install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev
export GLOG_logtostderr=1
bazelisk run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
    mediapipe/examples/desktop/hello_world:hello_world

**Comment by sgowroji** [comment]
Hi @ajm133, Could you please confirm you are trying to install on GPU support Linux machine  (via mesa drivers). Thanks!

**Comment by ajm133** [comment]
I am. Also, i tried running it on the CPU but was getting the same error. Thus, I think it is not the cpu/gpu support problem, but rather something else.

**Comment by jiuqiant** [comment]
The error message tells us that's an internal compiler error. You probably can try some other version of gcc such as gcc9. See instructions at https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g-compiler-versions-on-ubuntu-20-04-lts-focal-fossa.
