### ISSUE TITLE
Web application clashes on standing up

### ISSUE THREAD

**Issue by nakshatrasinghh** [google/mediapipe#2169]
Hi there, I am trying to build a real time pose estimation web app using flask, the application seems to be working but I get this annoying recurring message in the console. 

![image](https://user-images.githubusercontent.com/72384969/121768139-2577f800-cb7a-11eb-832e-032bb13b064e.png)

The strange thing is when I stand up for looking at my pose estimations the application crashes and throws this error.

![image](https://user-images.githubusercontent.com/72384969/121768268-0ded3f00-cb7b-11eb-8fa6-28f67a6b54d2.png)
Any fixes?

**Comment by sgowroji** [comment]
Hi @nakshatrasinghh, You need to check whether face result is None first in case of no face results detected in the current frame. 

```
if result.face_landmarks.landmark:
      face= result.face_landmarks.landmark
```

**Comment by nakshatrasinghh** [comment]
Hi @sgowroji what do I put in the else block?

**Comment by sgowroji** [comment]
If no human pose is detected, the fields in the "results" object is set to None. Before accessing results.pose_landmarks, please check if it's None. See our example code at https://github.com/google/mediapipe/blob/master/docs/solutions/pose.md#python-solution-api.

**Comment by nakshatrasinghh** [comment]
@sgowroji tried everything possible for 3 days straight, the error only comes when i stand up from the sitting position and it only happens in web apps, in local environment is works fine. Can we connect for 10 mins and you can help me solve this issue

**Comment by jiuqiant** [comment]
> @sgowroji tried everything possible for 3 days straight, the error only comes when i stand up from the sitting position and it only happens in web apps, in local environment is works fine. Can we connect for 10 mins and you can help me solve this issue

Please try `pip install mediapipe==0.8.6` to install the latest version and also apply the suggestions mentioned in https://github.com/google/mediapipe/issues/1553.
