### ISSUE TITLE
Segmentation fault (core dumped) on Ubuntu 20.04 x64 + v0.8.5 + holistic_tracking_gpu. But on v0.8.4 - everything is fine 

### ISSUE THREAD

**Issue by gittitov** [google/mediapipe#2170]

**Comment by sgowroji** [comment]
Hi @gittitov, Could you please elaborate the above issue details with complete steps. Thanks!

**Comment by gittitov** [comment]
I have AMD + 2080TI
Hi I am sending the following commands:

bazel build -j 96 -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/holistic_tracking:holistic_tracking_gpu

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/holistic_tracking/holistic_tracking_gpu --calculator_graph_config_file=mediapipe/graphs/holistic_tracking/holistic_tracking_gpu.pbtxt

**Comment by gittitov** [comment]
**v0.8.4 (success)**
...
# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  input_stream: "VECTOR:render_data_vector"
  output_stream: "IMAGE_GPU:output_video"
}
I20210614 08:36:14.975838 315078 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
I20210614 08:36:14.987386 315078 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
I20210614 08:36:14.994705 315078 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I20210614 08:36:15.068107 315127 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 460.73.01)
I20210614 08:36:15.068250 315078 demo_run_graph_main_gpu.cc:68]уInitialize the camera or load the video.
I20210614 08:36:15.525940 315078 demo_run_graph_main_gpu.cc:89] Start running the calculator graph.
I20210614 08:36:15.530890 315078 demo_run_graph_main_gpu.cc:94] Start grabbing and processing frames.
INFO: Created TensorFlow Lite delegate for GPU.
INFO: Replacing 229 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
INFO: Replacing 318 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
INFO: Replacing 164 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
INFO: Replacing 63 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
INFO: Replacing 97 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
INFO: Replacing 64 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
INFO: Replacing 63 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
INFO: Replacing 64 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.


**v0.8.5 (failed)**
...
# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  input_stream: "VECTOR:render_data_vector"
  output_stream: "IMAGE_GPU:output_video"
}
I20210614 08:49:00.054448 342686 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
I20210614 08:49:00.066905 342686 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
I20210614 08:49:00.074877 342686 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I20210614 08:49:00.167829 342735 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 460.73.01)
I20210614 08:49:00.167974 342686 demo_run_graph_main_gpu.cc:68] Initialize the camera or load the video.
I20210614 08:49:00.624727 342686 demo_run_graph_main_gpu.cc:89] Start running the calculator graph.
I20210614 08:49:00.626252 342686 demo_run_graph_main_gpu.cc:94] Start grabbing and processing frames.
I20210614 08:49:00.659508 342735 tflite_gpu_runner.cc:142] OpenCL backend is used.
Segmentation fault (core dumped)

**Comment by sgowroji** [comment]
Hi @gittitov, Please have a look at this issue https://github.com/google/mediapipe/issues/1734

**Comment by gittitov** [comment]
but I don't use python examples..
 
$ pip install --index-url https://test.pypi.org/simple/ mediapipe==0.8.4.2.1
Looking in indexes: https://test.pypi.org/simple/
Collecting mediapipe==0.8.4.2.1
  Downloading https://test-files.pythonhosted.org/packages/bb/d4/611ef5135991cffd0671044fd854a9ae0a7c085311c83d7eac48064b5f2c/mediapipe-0.8.4.2.1-cp38-cp38-manylinux2014_x86_64.whl (37.3 MB)
     |████████████████████████████████| 37.3 MB 1.2 MB/s 
ERROR: Could not find a version that satisfies the requirement wheel (from mediapipe==0.8.4.2.1) (from versions: none)
ERROR: No matching distribution found for wheel (from mediapipe==0.8.4.2.1)

python --version
Python 3.8.9

**Comment by jiuqiant** [comment]
This is a C++ gpu related issue. Reassign this to @mcclanahoochie.

**Comment by gittitov** [comment]
**v0.8.6 the same problem**

I20210706 09:26:49.876307 436051 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.                                                                                                                              
I20210706 09:26:49.888597 436051 demo_run_graph_main_gpu.cc:62] Initialize the GPU.                                                                                                                                           
I20210706 09:26:49.895681 436051 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5                                                                                                                      
I20210706 09:26:49.930045 436101 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 460.73.01)                                                                                                                          
I20210706 09:26:49.930145 436051 demo_run_graph_main_gpu.cc:68] Initialize the camera or load the video.                                                                                                                      
I20210706 09:26:50.392477 436051 demo_run_graph_main_gpu.cc:89] Start running the calculator graph.                                                                                                                           
I20210706 09:26:50.397397 436051 demo_run_graph_main_gpu.cc:94] Start grabbing and processing frames.                                                                                                                         
I20210706 09:26:50.499687 436101 tflite_gpu_runner.cc:142] OpenCL backend is used.                                                                                                                                            
Segmentation fault (core dumped)

**Comment by homuler** [comment]
Probably this is the same issue as #2251 .
Here is a workaround.

```diff
diff --git a/mediapipe/util/tflite/tflite_gpu_runner.cc b/mediapipe/util/tflite/tflite_gpu_runner.cc
index 5445f02..78af4f6 100644
--- a/mediapipe/util/tflite/tflite_gpu_runner.cc
+++ b/mediapipe/util/tflite/tflite_gpu_runner.cc
@@ -214,7 +214,7 @@ absl::Status TFLiteGPURunner::InitializeOpenCL(
   MP_RETURN_IF_ERROR(cl_environment_->NewInferenceBuilder(
       cl_options, std::move(*graph_cl_), builder));
 #endif
-  return absl::OkStatus();
+  return mediapipe::UnimplementedError("Currently only Android is supported");
 }
 
 }  // namespace gpu
```

**Comment by dlvrydryvr** [comment]
0.8.6 Holistic gpu Segmentation fault

Pop!_OS 21.04
AMD Ryzen 7 5800H
NVIDIA GeForce RTX 3060
Python 3.9.5 
CUDA 11.4
gcc 10.3.0
OpenCV 3.4.15
TensorFlow 2.5.0 
Bazelisk 1.9.0

**Comment by sgowroji** [comment]
Hi @gittitov, Did you get a chance to go through this https://github.com/google/mediapipe/issues/2170#issuecomment-874497189

**Comment by micmelesse** [comment]
@homuler  Thank you. This helped me. Can you please make this a pr so that others can avoid the issue?

**Comment by homuler** [comment]
@sgowroji Is the above patch will be merged, or at least will this issue be fixed in another way?

**Comment by sgowroji** [comment]
Reopening the present issue as it still exists

**Comment by mcclanahoochie** [comment]
https://github.com/google/mediapipe/pull/2463 has been merged upstream, thanks
