### ISSUE TITLE
How to serialize a model

### ISSUE THREAD

**Issue by INF800** [google/mediapipe#2171]
How to serialize handpose or posenet or holistic model so that we can store and retirieve them efficiently from indexedb

**Comment by sgowroji** [comment]
Hi @rakesh4real, Could you please elaborate your issue with complete details and which platform are you referring the above. Thanks!

**Comment by sgowroji** [comment]
Hi @rakesh4real, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.
