### ISSUE TITLE
bazel build hand detection example failure: error executing shell command

### ISSUE THREAD

**Issue by HaoyuWang00** [google/mediapipe#2172]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution: Windows
- Programming Language and version: python3.9
- MediaPipe version: https://github.com/google/mediapipe.git
- Bazel version: 3.7.2
- OpenCV version (if running on desktop):  3.4.10

**Describe the problem**:
I was following the "installing on windows" instruction from (https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows), following the steps. I successfully build the "hello world" example but when build the hand detection example, I run into this problem.

**Complete Logs:**
ERROR: C:/users/haoyu/_bazel_haoyu/yd4jt743/external/org_tensorflow/tensorflow/core/util/BUILD:376:24: error executing shell command: 'C:/msys64/usr/bin/bash.exe -c bazel-out/x64_windows-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source.exe --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-} ...' failed (Exit 2): bash.exe failed: error executing command C:/msys64/usr/bin/bash.exe -c bazel-out/x64_windows-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source.exe --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}  ... (remaining 4 argument(s) skipped)
/usr/bin/python: can't open file '/c/users/haoyu/_bazel_haoyu/yd4jt743/execroot/mediapipe/C:\Users\Haoyu\_bazel_haoyu\yd4jt743\execroot\mediapipe\bazel-out\x64_windows-opt-ST-e0f78fafe98f\bin\external\org_tensorflow\tensorflow\tools\git\gen_git_source.zip': [Errno 2] No such file or directory
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 22.545s, Critical Path: 21.54s
INFO: 578 processes: 40 internal, 538 local.
FAILED: Build did NOT complete successfully

Obviously the path "/c/users/haoyu/_bazel_haoyu/yd4jt743/execroot/mediapipe/C:\Users\Haoyu\_bazel_haoyu\yd4jt743\execroot\mediapipe\bazel-out\x64_windows-opt-ST-e0f78fafe98f\bin\external\org_tensorflow\tensorflow\tools\git\gen_git_source.zip" is the problem but I really do not know how to solve this, as someone new to building using tool like bazel/msys64.

Thank you!

**Comment by sohail-jogo** [comment]
Windows usually cause a lot of problems. I would recommend installing mediapipe using Docker.

**Comment by HaoyuWang00** [comment]
> Windows usually cause a lot of problems. I would recommend installing mediapipe using Docker.

Thank you for you suggestion. Actually I am building a Web APP based on Django, making use of mediapipe. When doing the streaming, I find that under Linux (Ubuntu 20.4), when I run the streaming with detection on (with python mediapipe lib), it will die once a few minutes. When I switch to Windows, the stream runs smoothly and will not die like that. So that is basically why I want to contunue my work under Windows.

Another thing to note is I also fail to compile the C++ version of mediapipe under Linux, due to some gcc issue, which I never manage to solve. For more details, you'd like to refer to this [issue](https://github.com/google/mediapipe/issues/2001#issuecomment-846595687).

**Comment by sgowroji** [comment]
Hi @HaoyuWang00, Could you please provide the complete steps to reproduce the above error. Thanks!

**Comment by HaoyuWang00** [comment]
> Hi @HaoyuWang00, Could you please provide the complete steps to reproduce the above error. Thanks!

Hi @sgowroji , I try to recall what I have done in the time sequence:
1. Install MSYS2, and update as instructed
2. Install necessary packages running ```C:\> pacman -S git patch unzip```
3. Check my python executable path:  ```"C:\\Users\\Haoyu\\AppData\\Local\\Programs\\Python\\Python39\python.exe"```
4. Install Visual C++ Build Tools and WinSDK as instructed
5. Install Bazel 3.7.2
6. Set Bazel Variables like stated in the instruction
7. Install OpenCV 3.4.10: download the .exe file, extract it to ```C:\opencv``` (Note that, I downloaded 3.4.14 or something and resulted in error of missing .dll, at step 10, so I deleted the opencv folder and downloaded this required version again, and that error gone.)
8. Checkout MediaPipe by running ```git clone https://github.com/google/mediapipe.git```
9. Build the C++ example by running ```C:\Users\Haoyu\mediapipe_repo>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\\Users\\Haoyu\\AppData\\Local\\Programs\\Python\\Python39\python.exe" mediapipe/examples/desktop/hello_world```. This build was successful but when I run ```bazel-bin\mediapipe\examples\desktop\hello_world\hello_world.exe```, it did not print anything which confused me. And I proceeded to 10.
10. Run ```bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\\Users\\Haoyu\\AppData\\Local\\Programs\\Python\\Python39\python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu```, and resulted in the error above.

**Comment by jiuqiant** [comment]
This could be a downloading issue of "org_tensorflow\tensorflow\tools\git\gen_git_source.zip". Try `bazel clean --expunge` and rebuild it. Please use VPN if you have one. See more details at https://google.github.io/mediapipe/getting_started/troubleshooting.html#fail-to-fetch-remote-dependency-repositories.

**Comment by sgowroji** [comment]
Hi @HaoyuWang00, Could you please try the instructions mentioned in the above [comment](https://github.com/google/mediapipe/issues/2172#issuecomment-860850925). Thanks!

**Comment by HaoyuWang00** [comment]
Hi @sgowroji and @jiuqiant , thank you for your reply and I will try the method mentioned by @jiuqiant as soon as possible, and will update you here once done! ;)

**Comment by HaoyuWang00** [comment]
Hi @sgowroji and @jiuqiant , I have tried the method mentioned by @jiuqiant , without using a VPN. I rebuilt it after cleaning and the same error resists. I am currently staying in Singapore and may I know if it is neccessary to use a VPN and if so, what is its purpose?

The output of ```PS C:\Users\Haoyu\mediapipe_repo\mediapipe> bazel clean --expunge``` is:
```INFO: Starting clean.```

And the error, which is redundant to be shown:
```
ERROR: C:/users/haoyu/_bazel_haoyu/yd4jt743/external/org_tensorflow/tensorflow/core/util/BUILD:376:24: error executing shell command: 'C:/msys64/usr/bin/bash.exe -c bazel-out/x64_windows-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source.exe --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-} ...' failed (Exit 2): bash.exe failed: error executing command C:/msys64/usr/bin/bash.exe -c bazel-out/x64_windows-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source.exe --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}  ... (remaining 4 argument(s) skipped)
/usr/bin/python: can't open file '/c/users/haoyu/_bazel_haoyu/yd4jt743/execroot/mediapipe/C:\Users\Haoyu\_bazel_haoyu\yd4jt743\execroot\mediapipe\bazel-out\x64_windows-opt-ST-e0f78fafe98f\bin\external\org_tensorflow\tensorflow\tools\git\gen_git_source.zip': [Errno 2] No such file or directory
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 148.518s, Critical Path: 61.64s
INFO: 1007 processes: 332 internal, 675 local.
```

So I think the key here is with the path following ```can't open file``` but I really have no clue about it...

Thank you!

**Comment by Kangjik94** [comment]
i just success building face mesh :)
i got just the same problem as you commented.
"cannot open gen_~~.zip" bla bla

i guessed that the error occurs because of mixed bin path
then we can ask to ourselves "what path is mixed? or confusing?"  

i think cmd bin path and msys bin path is confusing

so i removed msys bin path and msys\mingw64 bin path.

and retry build again. it works in my case!!

hope my method help you to get out of error hole

**Comment by sgowroji** [comment]
Hi @HaoyuWang00, You can try the workaround mentioned in the above [comment](https://github.com/google/mediapipe/issues/2172#issuecomment-900161133). Thanks!
