### ISSUE TITLE
MediaPipe Hands Light, Full, Heavy Models

### ISSUE THREAD

**Issue by alexriedel1** [google/mediapipe#2173]
Hey, the paper https://arxiv.org/pdf/2006.10214.pdf states, that there were three types of models, light, full and heavy trainded for MediaPipe Hands. 

Are there information available on which one is the one implemented in the final solution?

Are the other two models also available for download?

Thanks, Alex

**Comment by sgowroji** [comment]
Hi @alexriedel1, Could you please explain your use case with three different trained hand models.Thanks!

**Comment by alexriedel1** [comment]
> Hi @alexriedel1, Could you please explain your use case with three different trained hand models.Thanks!

Hi! Especially I would like to use a hand model that might not be so super fast regarding inferencing time but a little bit more accurate instead. Just like you added heavy models to the pose and holistic solutions.

**Comment by doduythao** [comment]
Same for me, the 3.5M model is too oversimplified model for hand keyposes. I tried on Cambridge hand gesture and FreiHand dataset and the default model works terribly. (since all of them has hand but MediaPipe hand only detects less than 60%), many detected samples with terrible wrong key points. I'm really want looking for heavy model

**Comment by bazarevsky** [comment]
The paper you are referencing is quite old already. It still perfectly describes overall approach and high-level architecture for the solution, however as we try to regularly update MediaPipe with our latest hand models, right now we have only two options: Lite and Full. 

These two models differ from each other only by feature extractor capacity, so Full is more accurate and slower than Lite one. Based on our experience, model quality depend not only on model capacity, but also on training dataset and target domain. So, we are constantly working on extending our training dataset with underrepresented samples.
