### ISSUE TITLE
Run callback even when no landmarks are detected 

### ISSUE THREAD

**Issue by sohail-jogo** [google/mediapipe#2174]
OS Platform and Distribution : Windows 10 Home 64 Bit, Mobile - Samsung Galaxy S9+ , Android OS Version: 10.
Bazel version: 3.7.2
Solution Pose Tracking GPU
Programming Language and version : Java (Android)

I have made a custom pose_tracking pbtxt file which is almost the same as pose_tracking_gpu.pbtxt file in (mediapipe/graphs/pose_tracking) , but with a few changes according to my need.

**Custom_Pose_Tracking_GPU.pbtxt file:**

MediaPipe graph that performs pose tracking with TensorFlow Lite on GPU.

CPU buffer. (CpuBuffer)
input_stream: "input_video"

Pose landmarks. (NormalizedLandmarkList)
output_stream: "pose_landmarks"

_ Throttles the images flowing downstream for flow control. It passes through
the very first incoming image unaltered, and waits for downstream nodes
(calculators and subgraphs) in the graph to finish their tasks before it
passes through another image. All images that come in while waiting are
dropped, limiting the number of in-flight images in most part of the graph to

This prevents the downstream nodes from queuing up incoming images and data
excessively, which leads to increased latency and memory usage, unwanted in
real-time mobile applications. It also eliminates unnecessarily computation,
e.g., the output produced by a node may get dropped downstream if the
subsequent nodes are still busy processing previous inputs._
node: {
calculator: "ImageFrameToGpuBufferCalculator"
input_stream: "input_video"
output_stream: "input_video_gpu"
}

node {
calculator: "FlowLimiterCalculator"
input_stream: "input_video_gpu"
input_stream: "FINISHED:pose_landmarks"
input_stream_info: {
tag_index: "FINISHED"
back_edge: true
}
output_stream: "throttled_input_video"
}

Subgraph that detects poses and corresponding landmarks.
node {
calculator: "PoseLandmarkGpu"
input_stream: "IMAGE:throttled_input_video"
output_stream: "LANDMARKS:pose_landmarks"
output_stream: "DETECTION:pose_detection"
output_stream: "ROI_FROM_LANDMARKS:roi_from_landmarks"
}

**The android code looks like this:** 

```

private static final String OUTPUT_STREAM_NAME = "pose_landmarks";
private static final String INPUT_VIDEO_STREAM_NAME = "input_video";

void loadModel() {  // runs at the start, initialization method
graph = new Graph();


        if (new File(BINARY_GRAPH_NAME).isAbsolute()) {
            graph.loadBinaryGraph(BINARY_GRAPH_NAME);
        } else {
            graph.loadBinaryGraph(
                    AndroidAssetUtil.getAssetBytes(context.getAssets(), BINARY_GRAPH_NAME));
        }

graph.addPacketCallback(OUTPUT_STREAM_NAME, packet -> //whatever the code is ) ; 

} 


void supplyFrame(bitmap){ a callback to which a frame is supplied from camera as soon as they are available
long timestamp = System.currentTimeMillis(); 
graph.addPacketToInputStream(INPUT_VIDEO_STREAM_NAME,packet,timestamp);
}

```

**PROBLEM IS:** 
I want the graph->callback to run even when the person is not in the frame/image. I have read that the callbacks are designed in such a way that it will only process when there are landmarks available. 
So, i want to be able to get some information so that I can know for which frame there were no landmarks or any kind of detections.

**Comment by sohail-jogo** [comment]
the platform is anroid!  @sgowroji

**Comment by brucechou1983** [comment]
Another approach

1. Add a new output stream "is_pose_landmarks_presence" to specify whether the landmark is detected or not.
2. Add a PacketPresenceCalculator with input stream "pose_landmarks" and output stream "is_pose_landmarks_presence".
3. Add packet callback to the new output stream

**Comment by sohail-jogo** [comment]
> 2\. PacketPresenceCalculator

Thanks a lot! This is what I was looking for.

**Comment by sohail-jogo** [comment]
> Another approach
> 
> 1. Add a new output stream "is_pose_landmarks_presence" to specify whether the landmark is detected or not.
> 2. Add a PacketPresenceCalculator with input stream "pose_landmarks" and output stream "is_pose_landmarks_presence".
> 3. Add packet callback to the new output stream

Thanks a lot! This is what I was looking for.

**Comment by sohail-jogo** [comment]
problem solved, therefore closing it!
