### ISSUE TITLE
MediaPipe/Pose with react native

### ISSUE THREAD

**Issue by goodgood111** [google/mediapipe#2176]
Is it possible to use MediaPipe/Pose with react native?

If it is, anyone has any sample code or video?

**Comment by sgowroji** [comment]
Hi @goodgood111, Could you please go through the reference https://github.com/google/mediapipe/issues/587#issuecomment-610585088

**Comment by sgowroji** [comment]
Hi @goodgood111, Did you get a chance to go through my above comment. Thanks!

**Comment by sgowroji** [comment]
Assuming your resolved with the above comment, We are closing this issue now.
