### ISSUE TITLE
Android native api

### ISSUE THREAD

**Issue by whatisor** [google/mediapipe#2177]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using):
- Programming language : C++/typescript/Python/Objective C/Android Java
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state:**
Mediapipe already wrote by C++.
Why not we support Android C++ API for NDK? Which is better for performance, also better for integration for many Game, AR, XR platforms.

**Will this change the current api? How?**
Yes, create a new interface for android ndk( with a hello world)

**Who will benefit with this feature?**
Many developers

**Please specify the use cases for this feature:**
Many platforms prefers C++ library for Android which is easy to integrate to existing project.

**Any Other info:**

**Comment by kuaashish** [comment]
Hello @whatisor,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
