### ISSUE TITLE
Palm detection inference of tflight-model

### ISSUE THREAD

**Issue by pixml27** [google/mediapipe#2179]
Hey! Thank you very much for this awesome repository!
I want to use the palm detection model without using the repository itself. I download this model
"mediapipe/modules/palm_detection/palm_detection.tflite"
Then I write the following code

```
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

floating_model = input_details[0]['dtype'] == np.float32
print(f'is floating model: {floating_model}')

height = input_details[0]['shape'][1]
width = input_details[0]['shape'][2]

img = cv2.resize(image, (width, height))[np.newaxis, :, :, :]
img = (np.float32(img) - 0.0) / 255.0 

interpreter.set_tensor(input_details[0]['index'], img)

interpreter.invoke()

output_bboxes = interpreter.get_tensor(output_details[0]['index'])[0]
output_scores = interpreter.get_tensor(output_details[1]['index'])[0]
```
After doing this I get an output that I don't understand
<img width="651" alt="Снимок экрана 2021-06-15 в 20 53 22" src="https://user-images.githubusercontent.com/38530905/122100457-e2d54a80-ce1b-11eb-8137-42f3934d8025.png">
How can i transfer output_bboxes and output_scores to the usual form of coordinates in scale [0,128] and scores [0,1]?
Moreover, why is the boxed tensor length 18?
Is there anything else I am doing wrong?

**Comment by sgowroji** [comment]
Hi @pixml27, We like to encourage you to use MediaPipe python API for Hand solution instead of the tflite file directly as there are optimizations we do in the pipeline that you will need to reimplement.

**Comment by JoeyChuuichi** [comment]
@sgowroji Is there any instruction on MediaPipe python API that can output the palm detection result instead of the hand pose tracking result?

**Comment by aa12356jm** [comment]
@JoeyChuuichi  @pixml27   have you get the bbox  of the palm in python ?  thanks
