### ISSUE TITLE
Packet with same timestamp.

### ISSUE THREAD

**Issue by jiqimaogou** [google/mediapipe#218]
I have a calculator produces one array, like:
`ArrayCalculator` -> x1, x2, x3.

and another calculator process the array element.
x1 -> `MyCalculator`
x2 -> `MyCalculator`
x3 -> `MyCalculator`

how should I do this?
1. pack the whole array to MyCalculator, and foreach element in MyCalculator
x1, x2, x3 -> `MyCalculator`

2. pack the every element and send to MyCalculator，but every elemnt has the same timestamp.
x1 -> `MyCalculator`
x2 -> `MyCalculator`
x3 -> `MyCalculator`

x1, x2, x3 has the same timestamp!!!! how do i solve this?

which is the best practice?

**Comment by hadon** [comment]
Either scheme is acceptable.  If it is convenient for you to make MyCalculator accept an array of inputs, then scheme (1) will produce the most simple and clear graph.  If MyCalculator can only accept one input at a time, scheme (2) is possible using a calculator named "BeginLoopCalculator" to unpack the array input-packet into separate item input-packets.  The "BeginLoopCalculator" assigns a new unique timestamp to each of the input packets, and then "EndLoopCalculator" packs the results into a new array.  

"BeginLoopCalculator" and "EndLoopCalculator"  were recently added to mediapipe/calculators/core/ in support of a new MediaPipe example graph.  I believe that these classes have not been released by Google yet, and they will appear in a future release.  Let me know if you need them sooner, and I will release them asap.

**Comment by jiqimaogou** [comment]
> Either scheme is acceptable. If it is convenient for you to make MyCalculator accept an array of inputs, then scheme (1) will produce the most simple and clear graph. If MyCalculator can only accept one input at a time, scheme (2) is possible using a calculator named "BeginLoopCalculator" to unpack the array input-packet into separate item input-packets. The "BeginLoopCalculator" assigns a new unique timestamp to each of the input packets, and then "EndLoopCalculator" packs the results into a new array.
> 
> "BeginLoopCalculator" and "EndLoopCalculator" were recently added to mediapipe/calculators/core/ in support of a new MediaPipe example graph. I believe that these classes have not been released by Google yet, and they will appear in a future release. Let me know if you need them sooner, and I will release them asap.

yeah I need it! my app can detect many face at the same time, and we add a filter to each face.

**Comment by mgyong** [comment]
@eknight7 - FYI
@jiqimaogou Can you kindly send an email to mgyong at google dot com ? So that we can follow up with you about access

**Comment by jiqimaogou** [comment]
> @eknight7 - FYI
> @jiqimaogou Can you kindly send an email to mgyong at google dot com ? So that we can follow up with you about access

my email is fjjohnchen@gmail.com

**Comment by eknight7** [comment]
With the new release https://github.com/google/mediapipe/releases/tag/v0.6.4, the following are available:
1. `BeginLoopCalculator`: https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/begin_loop_calculator.h
2. `EndLoopCalculator`: https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/end_loop_calculator.h

See example usage in multi-hand tracking:
https://github.com/google/mediapipe/blob/master/mediapipe/docs/multi_hand_tracking_mobile_gpu.md
