### ISSUE TITLE
MediaPipe Hands landmarks can not be obtained by poller (GPU version) when use latest mediapipe code 

### ISSUE THREAD

**Issue by aiarcv** [google/mediapipe#2182]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Linux Ubuntu 18.04 or 20.04)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 18.04 or 20.04
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.4 or latest nightly build
- Bazel version:3.7.4
- Solution (e.g. FaceMesh, Pose, Holistic):hands 
- Programming Language and version ( e.g. C++, Python, Java):C++

**Describe the expected behavior:**
https://github.com/google/mediapipe/issues/1971
https://github.com/google/mediapipe/issues/1973
Use the procedure described  in  above two issues , we Can obtain landmarks XYZ by poller (NormalizedLandmarkList)  for CPU version,  when do exactly same  things for GPU , the procedure does not work and not able to get XYZ in GPU mode.  
**Standalone code you may have used to try to get what you need :**

**Other info / Complete Logs :**
Mediapipe by pass the landmarks can not  get landmark in following codes  ( the  poller   works and can get landmark in GPU mode when using 2020 Nov Mediapipe,   but can not work for latest mediapipe) 
if (!multi_hand_landmarks_poller.Next(&multi_hand_landmarks_packet)) {
LOG(INFO) << "landmarks cannot be polled\n";
break;
}

**Comment by sgowroji** [comment]
Hi @aiarcv,  Could you please provide the custom code changes performed on graphs with error logs.

**Comment by txf-** [comment]
@aiarcv 

The problem is that the calculators are not always emitting packets and the pollers block the graph, effectively making a deadlock.

See  #1532  

or #850 

Basically it involves editing the graphs and polling based on whether a packet is present

```
node {
  calculator: "PacketPresenceCalculator"
  input_stream: "PACKET:landmarks"
  output_stream: "PRESENCE:landmark_presence"
}
```

**Comment by hadon** [comment]
AddOutputStreamPoller() is designed for convenience by enabling synchronous graph input and output, all from a single application thread. However, because some MediaPipe calculators occasionally produce no output, AddOutputStreamPoller() is prone to deadlocks.  I usually change from AddOutputStreamPoller() to ObserveOutputStream(), which doesn't block any thread.  See related issue #1709.
