### ISSUE TITLE
original tflite model before quantization pose landmark?

### ISSUE THREAD

**Issue by chaowentao** [google/mediapipe#2183]
Hello, your human pose landmark model is very effective, and we want to apply it to other places, but the current ``tflite`` model after quantization. After converting it to ``onnx``, the model output is inconsistent. Can you provide a ``tflite`` model before quantization or an ``onnx`` model? Thank you very much.

**Comment by sgowroji** [comment]
Hi @chaowentao, Could you please elaborate your inconsistent model output in the form of errors or any video screenshot to understand it much better. And we would encourage to use python pose solution rather using the tflite model, If you're targeting  python platform.

**Comment by hongyaohongyao** [comment]
Have you solved your problem?

**Comment by noirmist** [comment]
Hi @chaowentao @hongyaohongyao, You can get the original weight at this link.

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/053_BlazePose/10_lite_full_heavy_version_May6_2021
