### ISSUE TITLE
use onnx format from pose_landmark

### ISSUE THREAD

**Issue by Daewon-Hwang** [google/mediapipe#2184]
Hi, 

I want to use pose_landmark in Unity Barracuda. Because it support ONNX format, I decided export ONNX from  pose_landmark_heavy.tflite.

``
! python -m tf2onnx.convert --tflite ./pose_landmark_heavy.tflite --output pose_landmark_heavy.onnx
``

After exporting ONNX format, I was able to check the model structure from the onnx viewer as shown in the figure below.

![image](https://user-images.githubusercontent.com/59599085/122404501-3f6e6c00-cfba-11eb-927d-0f516a4c5549.png)

The paper states that the model has key points + visibility of size 33x3. But pose_landmark_heavy.tflite have 5 outputs(Identity[1,195], Identity_1[1,1], Identity_2[1,128,128,1], Identity_3[1,64,64,39], Identity_4[1,117])

![image](https://user-images.githubusercontent.com/59599085/122403831-a4759200-cfb9-11eb-97cd-197bc59984c8.png)

Can you explain the five outputs of pose_landmark_heavy.tflite? And can you tell me how to take these outputs and convert them to 33x3 keypoints + visibility?

Thank you

**Comment by chaowentao** [comment]
https://github.com/google/mediapipe/issues/1701#issuecomment-797131246
As for the model input we divide RGB image with [0, 255] values by 255.0 to get [0, 1] values. So the second formula.

As for the outputs, you are interested in first two:

(1, 195) = (1, 33 * 5) - 33 landmarks, represented as (x, y, z, visibility, presence) each, in a flatten format. presence means landmark is within the frame bound, visibility means landmark is present and not occluded by other objects or body parts. Other points for the next frame box calcaulating.
(1, 1) - Pose presence flag as x from sigmoid(x). Meaning if you apply sigmoid to it, you'll get value in [0, 1] range.

**Comment by Daewon-Hwang** [comment]
Thank you. I have additional question. When extracting ONNX and using it in Unity barracuda, do I have to manually crop the input image and smooth the land mark?

**Comment by chaowentao** [comment]
If you want to have a better result for a video, you can follow mediapipe post-processing. If not, you can also get an acceptable result.

**Comment by Daewon-Hwang** [comment]
In my case, I need to use the ONNX file in Unity, so it seems to be necessary to manually crop the human area and then input it into the pose_landmark extraction model. What I'm curious about is how much margin should be placed when cropping the human area.

**Comment by chaowentao** [comment]
In my opinion, your box should be as close to the entire body as possible and leaving a little margin.

**Comment by Daewon-Hwang** [comment]
Thanks for the advice. I'll give it a try.

**Comment by hongyaohongyao** [comment]
> Thanks for the advice. I'll give it a try.

Do you make it?

**Comment by LGuilhermeRodrigues** [comment]
> [#1701 (comment)](https://github.com/google/mediapipe/issues/1701#issuecomment-797131246)
> As for the model input we divide RGB image with [0, 255] values by 255.0 to get [0, 1] values. So the second formula.
> 
> As for the outputs, you are interested in first two:
> 
> (1, 195) = (1, 33 * 5) - 33 landmarks, represented as (x, y, z, visibility, presence) each, in a flatten format. presence means landmark is within the frame bound, visibility means landmark is present and not occluded by other objects or body parts. Other points for the next frame box calcaulating.
> (1, 1) - Pose presence flag as x from sigmoid(x). Meaning if you apply sigmoid to it, you'll get value in [0, 1] range.

(1, 33 * 5) results in (1, 165), not 195

**Comment by hongyaohongyao** [comment]
> In my opinion, your box should be as close to the entire body as possible and leaving a little margin.
你好，请问你是否以及实现了在onnx上使用pose_landmarks? 我用tf2onnx将权重转换成onnx格式的，但是预测的时候并不能将关键点预测在正确的位置，而是随意的飘。

**Comment by hongyaohongyao** [comment]
> > In my opinion, your box should be as close to the entire body as possible and leaving a little margin.
> > 您好，请问您是否已经实现了在onnx上使用pose_landmarks? 我用tf2onnx将权重转换成onnx格式的，但是预测的时候并不能将关键点预测在正确的位置，而是随意的飘。

补充一下，我做的预处理是将rgb通道除255缩放到[0,1]，输出的时候直接把第一个195维的tensor进行reshape到[39, 5],然后把x,y的值直接作为在256x256的图像上的坐标。

**Comment by chaowentao** [comment]
> > In my opinion, your box should be as close to the entire body as possible and leaving a little margin.
> > 您好，请问您是否已经实现了在onnx上使用pose_landmarks? 我用tf2onnx将权重转换成onnx格式的，但是预测的时候并不能将关键点预测在正确的位置，而是随意的飘。
> 
> 补充一下，我的预处理是把rgb通道除255，输出结果我把第一个195维的tensor 进行 reshape到[39,5]，然后把x,y位置的值直接作为在输入图像上的坐标

你的输入没有问题，模型输入是[256,256], 它直接输出是0-255的值，需要先除以255进行归一化，然后再乘以对应的宽和高。你再试试。

**Comment by Jerryzhangzhao** [comment]
@chaowentao @hongyaohongyao 你好，我尝试将pose_landmark_full.tflite模型转为onnx:
python -m tf2onnx.convert --tflite ./pose_landmark_full.tflite --output pose_landmark_full.onnx
转换成功了
2021-10-14 13:56:34,543 - INFO - Using tensorflow=2.6.0, onnx=1.10.1, tf2onnx=1.9.2/0f28b7
2021-10-14 13:56:34,543 - INFO - Using opset <onnx, 9>
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2021-10-14 13:56:35,113 - INFO - Optimizing ONNX model
2021-10-14 13:56:37,380 - INFO - After optimization: Cast -195 (195->0), Const -48 (245->197), Identity -5 (5->0), Reshape -37 (41->4), Transpose -396 (398->2)
2021-10-14 13:56:37,425 - INFO -
2021-10-14 13:56:37,425 - INFO - Successfully converted TensorFlow model ./pose_landmark_full.tflite to ONNX
2021-10-14 13:56:37,426 - INFO - Model inputs: ['input_1']
2021-10-14 13:56:37,426 - INFO - Model outputs: ['Identity', 'Identity_1', 'Identity_2', 'Identity_3', 'Identity_4']
2021-10-14 13:56:37,426 - INFO - ONNX model is saved at pose_landmark_full_de.onnx
但是使用这个onnx模型进行 inference的时候，出来的结果明显不对，如下图：
![joint_visualization7](https://user-images.githubusercontent.com/10524773/137262676-0463792f-307c-428e-b673-beddab7b374b.jpg)
请问这个可能是什么原因呢？

**Comment by gioipv** [comment]
Thank you for your experiment. But I have a question about image pre-processing: do we need resize image with keeping the aspect ratio between the height and width of the images. ?

**Comment by TJZMT** [comment]
> @chaowentao @hongyaohongyao 你好，我尝试将pose_landmark_full.tflite模型转为onnx: python -m tf2onnx.convert --tflite ./pose_landmark_full.tflite --output pose_landmark_full.onnx 转换成功了 2021-10-14 13:56:34,543 - INFO - Using tensorflow=2.6.0, onnx=1.10.1, tf2onnx=1.9.2/0f28b7 2021-10-14 13:56:34,543 - INFO - Using opset <onnx, 9> INFO: Created TensorFlow Lite XNNPACK delegate for CPU. 2021-10-14 13:56:35,113 - INFO - Optimizing ONNX model 2021-10-14 13:56:37,380 - INFO - After optimization: Cast -195 (195->0), Const -48 (245->197), Identity -5 (5->0), Reshape -37 (41->4), Transpose -396 (398->2) 2021-10-14 13:56:37,425 - INFO - 2021-10-14 13:56:37,425 - INFO - Successfully converted TensorFlow model ./pose_landmark_full.tflite to ONNX 2021-10-14 13:56:37,426 - INFO - Model inputs: ['input_1'] 2021-10-14 13:56:37,426 - INFO - Model outputs: ['Identity', 'Identity_1', 'Identity_2', 'Identity_3', 'Identity_4'] 2021-10-14 13:56:37,426 - INFO - ONNX model is saved at pose_landmark_full_de.onnx 但是使用这个onnx模型进行 inference的时候，出来的结果明显不对，如下图： ![joint_visualization7](https://user-images.githubusercontent.com/10524773/137262676-0463792f-307c-428e-b673-beddab7b374b.jpg) 对输入的操作是：除以255归一化到[0,1]之间 对输出的操作是：Identity中的x,y 先除以255进行归一化，然后再乘以对应的宽和高 但是结果不对，请问这个可能是什么原因呢？

pose_landmark_full模型只能对任务位画面中央且没有旋转的目标进行标识，在mediapipe里这个模型前还有一个pose_detection模型来定位人体目标并通过计算得到roi、rotation等信息，然后再把frame的roi通过几何变换如裁剪、旋转等变为256*256送入pose_landmark_full模型

**Comment by anonymousz97** [comment]
> [#1701 (comment)](https://github.com/google/mediapipe/issues/1701#issuecomment-797131246) As for the model input we divide RGB image with [0, 255] values by 255.0 to get [0, 1] values. So the second formula.
> 
> As for the outputs, you are interested in first two:
> 
> (1, 195) = (1, 33 * 5) - 33 landmarks, represented as (x, y, z, visibility, presence) each, in a flatten format. presence means landmark is within the frame bound, visibility means landmark is present and not occluded by other objects or body parts. Other points for the next frame box calcaulating. (1, 1) - Pose presence flag as x from sigmoid(x). Meaning if you apply sigmoid to it, you'll get value in [0, 1] range.

Can you explain this? 33 * 5 is 165 not 195?

**Comment by JorgeRuizDev** [comment]
> > [#1701 (comment)](https://github.com/google/mediapipe/issues/1701#issuecomment-797131246) As for the model input we divide RGB image with [0, 255] values by 255.0 to get [0, 1] values. So the second formula.
> > As for the outputs, you are interested in first two:
> > (1, 195) = (1, 33 * 5) - 33 landmarks, represented as (x, y, z, visibility, presence) each, in a flatten format. presence means landmark is within the frame bound, visibility means landmark is present and not occluded by other objects or body parts. Other points for the next frame box calcaulating. (1, 1) - Pose presence flag as x from sigmoid(x). Meaning if you apply sigmoid to it, you'll get value in [0, 1] range.
> 
> Can you explain this? 33 * 5 is 165 not 195?

Reshaping the vector to (-1, 5) creates a (39, 5) tensor where just the first 33 elements correspond to real joints, the rest can be discarded.
