### ISSUE TITLE
Strange z-coordinates of pose face-landmarks

### ISSUE THREAD

**Issue by LucaswasTaken** [google/mediapipe#2185]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): MediaPipe Holistic
- Programming language : python
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state:**
The face landmarks from the pose are now different from when the option "--upper_body" was available. In 2d visualization it looks very good, but the 3d representation of the pose face-landmarks feels strange. Before, the face seemed closer to the body, and now it looks stretched.
**Will this change the current api? How?**
Yes. It will change the "z-coordinate" of the landmark extraction.
**Who will benefit with this feature?**
Users who depends of the 3-d representation.
**Please specify the use cases for this feature:**
To identify diferent movements that depends on the 3-d coordinates.
**Any Other info:**
Landmark extraction before using "upper_body_only":
![image](https://user-images.githubusercontent.com/21283326/122440082-9b150700-cf72-11eb-9196-b7fc7d06ad34.png)

Landmark extraction after:
![image](https://user-images.githubusercontent.com/21283326/122440232-bed84d00-cf72-11eb-85c6-0116fa4c8d6a.png)

**Comment by siisee11** [comment]
Are there any updates?

**Comment by sgowroji** [comment]
Hi @LucaswasTaken, This will answer your query https://github.com/google/mediapipe/issues/1611#issuecomment-974941821
