### ISSUE TITLE
Proposal: use select() in opencv_linux.BUILD to make cross-compiling easier

### ISSUE THREAD

**Issue by samlaf** [google/mediapipe#2186]
This is not an issue, so there is no bug to reproduced.

**Describe the setting**:

I am proposing a change to `opencv_linux.BUILD` so that building on aarch64 is easier.
Currently, the opencv cc_library in `opencv_linux.BUILD` reads:
```
cc_library(
    name = "opencv",
    srcs = glob([
                "lib/x86_64-linux-gnu/libopencv_core.so",
                "lib/x86_64-linux-gnu/libopencv_calib3d.so",
                "lib/x86_64-linux-gnu/libopencv_features2d.so",
                "lib/x86_64-linux-gnu/libopencv_highgui.so",
                "lib/x86_64-linux-gnu/libopencv_imgcodecs.so",
                "lib/x86_64-linux-gnu/libopencv_imgproc.so",
                "lib/x86_64-linux-gnu/libopencv_video.so",
                "lib/x86_64-linux-gnu/libopencv_videoio.so",
            ],
    }),
    hdrs = glob([
        # For OpenCV 3.x
        "include/opencv2/**/*.h*",
        # For OpenCV 4.x
        # "include/opencv4/opencv2/**/*.h*",
    ]),
    includes = [
        # For OpenCV 3.x
        "include/",
        # For OpenCV 4.x
        # "include/opencv4/",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
```
The [documentation](https://github.com/google/mediapipe/blob/master/third_party/opencv_linux.BUILD) says to update this file by using `sed -i "s/x86_64-linux-gnu/aarch64-linux-gnu/g" third_party/opencv_linux.BUILD` when building on aarch64. It also mentions the need to comment/uncomment the `hdrs` and `includes` variables to select between opencv 3 and 4.

**Describe the problem**:
I build mediapipe on my x86_64 laptop to debug, and then cross-compile it for my aarch64 jetson nano.
I do all of this within a docker container, which bind mounts the mediapipe directory. The problem with this is that I need to manually edit `opencv_linux.BUILD` when cross-compiling, and then re-edit it when I want to debug.

**Describe the proposed change**:
I am proposing to use the select() feature in bazel (as is used in [`opencv_windows.BUILD`](https://github.com/google/mediapipe/blob/b544a314b3c4818a4d6c56964b020c5be945377a/third_party/opencv_windows.BUILD#L25)).

The change would look something like
```
config_setting(
    name = "aarch64",
    values = {
        "cpu": "aarch64",
    },
    visibility = ["//visibility:public"],
)
cc_library(
    name = "opencv",
    srcs = select({
        ":aarch64":
            [
                "lib/aarch64-linux-gnu/libopencv_core.so",
                "lib/aarch64-linux-gnu/libopencv_calib3d.so",
                "lib/aarch64-linux-gnu/libopencv_features2d.so",
                "lib/aarch64-linux-gnu/libopencv_highgui.so",
                "lib/aarch64-linux-gnu/libopencv_imgcodecs.so",
                "lib/aarch64-linux-gnu/libopencv_imgproc.so",
                "lib/aarch64-linux-gnu/libopencv_video.so",
                "lib/aarch64-linux-gnu/libopencv_videoio.so",
            ],
        "//conditions:default":
            [
                "lib/x86_64-linux-gnu/libopencv_core.so",
                "lib/x86_64-linux-gnu/libopencv_calib3d.so",
                "lib/x86_64-linux-gnu/libopencv_features2d.so",
                "lib/x86_64-linux-gnu/libopencv_highgui.so",
                "lib/x86_64-linux-gnu/libopencv_imgcodecs.so",
                "lib/x86_64-linux-gnu/libopencv_imgproc.so",
                "lib/x86_64-linux-gnu/libopencv_video.so",
                "lib/x86_64-linux-gnu/libopencv_videoio.so",
            ],
    }),
    ....
)
```
This requires passing `--cpu=aarch64` as a flag to `bazel build`, which is something I do when cross-compiling.
This is still missing the case when the host architecture is aarch64, which shouldn't require the user passing `--cpu=aarch64` as input, but I am unsure how to solve this. Is there a way for bazel to query the underlying platform (eg. calling uname)? This could also be used to select on opencv4 or 3 for the hdrs and includes section!

**Comment by kuaashish** [comment]
@samlaf,

Would you to still need this proposal to be implemented? We will be good to accept the PR's and based on internal review will merge the request. Thanks!!

**Comment by samlaf** [comment]
> @samlaf,
> 
> Would you to still need this proposal to be implemented? We will be good to accept the PR's and based on internal review will merge the request. Thanks!!

Not working with mediapipe anymore, sorry.

**Comment by kuaashish** [comment]
@samlaf,

Thanks for the letting us know. Closing this is no longer issue from your end.
