### ISSUE TITLE
There's any update on the MALI issue with hand tracking? error #41

### ISSUE THREAD

**Issue by elblogbruno** [google/mediapipe#219]
There's any update on the MALI issue with hand tracking? I know this is based on error #41 but having no update on it, eagers me to ask!
Thanks,
Great job!

**Comment by elblogbruno** [comment]
I can confirm on the latest release of mediapipe, the problem #41  is still there.

**Comment by mgyong** [comment]
@elblogbruno Fixed bug in [v0.6.5 release](https://github.com/google/mediapipe/releases/tag/v0.6.5)

**Comment by elblogbruno** [comment]
@mgyong I did noticr! Awesome! Thanks for all. One question, can I access hand landmarks on android?

**Comment by mgyong** [comment]
@elblogbruno Fixed in [v0.6.6](https://github.com/google/mediapipe/releases/tag/v0.6.6) Pls check it out and let us know

**Comment by Xiaomao136** [comment]
the problem #41 is still there in v0.6.7.1
