### ISSUE TITLE
the new one if difficult to use vs YouTube8M Feature Extractor (DEPRECATED)

### ISSUE THREAD

**Issue by shuiyuejihua** [google/mediapipe#2190]
<em>Please make sure that this is a feature request.</em>
YES
**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using):YouTube8M Feature Extractor [(DEPRECATED)](https://github.com/google/youtube-8m/tree/e6f6bf682d20bb21904ea9c081c15e070809d914/feature_extractor)
- Programming language : Python
- Are you willing to contribute it (Yes/No):try

**Describe the feature and the current behavior/state:**
Difficult to use , vs the old one
**Will this change the current api? How?**
I don`t know
**Who will benefit with this feature?**
who use yt8m extract features
**Please specify the use cases for this feature:**
extract features, for lightgbm, xgb model , pytorch model
**Any Other info:**
please add the old one, which is more better and conviniet.

**Comment by sgowroji** [comment]
Hi @shuiyuejihua, Could you please elaborate with more details, Like what  made more difficult while working with YouTube8M  solution. And what is your use case with it.Thanks!
