### ISSUE TITLE
Face Rotation Angle/Pose

### ISSUE THREAD

**Issue by mufaawan** [google/mediapipe#2191]
Is there any way I can get the face rotation angles from camera? I want to know 3D angles. Roll, Yaw and Pitch. Will it be possible using MediPipe facemesh solution?

PS: I'm looking solution in Python.

**Comment by fahadhaq** [comment]
@mufaawan  Have a look at face effect example for android. The Calculator effect_renderer_calculator.cc uses FaceGeometry which converts it to a matrix which can be used to calculate Pitch, Roll and Yaw. Thats how I have worked out Pitch, yaw and roll. Hope this helps

**Comment by sgowroji** [comment]
Hi @mufaawan, Have a look at this https://github.com/google/mediapipe/issues/1561#issuecomment-771027016

**Comment by mufaawan** [comment]
> Hi @mufaawan, Have a look at this [#1561 (comment)](https://github.com/google/mediapipe/issues/1561#issuecomment-771027016)

yes I had look. I need a Pythonic solution. I am sorry I didn't find it helpful.

**Comment by qualityland27** [comment]
Did you solve this issue? I would be very interested in the solution.

**Comment by sgowroji** [comment]
Hi @mufaawan, There is already a thread w.r.t python https://github.com/google/mediapipe/issues/1912#issuecomment-824189260

**Comment by seel-channel** [comment]
```python
    eye = pose_results.pose_landmarks.landmark[mp_pose.PoseLandmark.LEFT_EAR]
    central_point = pose_results.pose_landmarks.landmark[mp_pose.PoseLandmark.NOSE]

    orient = look_at(np.array((eye.x, eye.y, eye.z)), np.array((central_point.x, central_point.y, central_point.z)))

    angle_x = np.arctan2(orient[2, 1], orient[2, 2])

    angle_y = np.arctan2(-orient[2, 0], np.sqrt(orient[2, 1] ** 2 + orient[2, 2] ** 2))

    angle_z = np.arctan2(orient[1, 0], orient[0, 0])

    
    # convert to degrees
    angle_x = angle_x * 180 / np.pi
    angle_y = angle_y * 180 / np.pi
    angle_z = angle_z * 180 / np.pi

    print(int(angle_x), int(angle_y), int(angle_z))
```
