### ISSUE TITLE
Expose XHR request data while loading models to allow for "progress bars"

### ISSUE THREAD

**Issue by ghost** [google/mediapipe#2192]
**System information:**

- MediaPipe Solution: MediaPipe Hands...but also any MediaPipe model
- Programming language : JavaScript
- Are you willing to contribute it (Yes/No): YES!

**Describe the feature and the current behavior/state:** For slow connections or environments with some overhead during setup (like MCU's) it would be helpful to know the percentage of the model that has been loaded. This would allow us to show a progress % indicator, instead of a generic "is loading" indicator. This is particularly useful for people with Attention Deficit Disorder like myself 😅

My personal use case is for the Hands model, but ideally this data would be exposed for all models. For example, I currently have 14Mbps download but it can still take 1min+ to load the model from a CDN. In this cases, it would be helpful to know percentage of bytes downloaded

**Will this change the current api? How?** No, we would only expose the XHR data

**Who will benefit with this feature?** Any user with slow network speeds

**Please specify the use cases for this feature:** To lessen "loading anxiety"

**Any Other info:**

This can be resolved by exposing `loaded` and `total` in `hands_solution_packed_assets_loader.js` on lines 50-51:

```js
        xhr.onprogress = function(event) {
          var url = packageName;
          var size = packageSize;
          if (event.total) size = event.total;
          if (event.loaded) {
            if (!xhr.addedTotal) {
              xhr.addedTotal = true;
              if (!Module.dataFileDownloads) Module.dataFileDownloads = {};
              Module.dataFileDownloads[url] = {
                loaded: event.loaded,
                total: size
              };
            } else {
              Module.dataFileDownloads[url].loaded = event.loaded;
            }
>>>>expose  var total = 0;
>>>>expose  var loaded = 0;
            var num = 0;
            for (var download in Module.dataFileDownloads) {
            var data = Module.dataFileDownloads[download];
              total += data.total;
              loaded += data.loaded;
              num++;
            }
            total = Math.ceil(total * Module.expectedDataFileDownloads/num);
            if (Module['setStatus']) Module['setStatus']('Downloading data... (' + loaded + '/' + total + ')');
          } else if (!Module.dataFileDownloads) {
            if (Module['setStatus']) Module['setStatus']('Downloading data...');
          }
        };
```

**Comment by mhays-google** [comment]
This is a good idea.  I can't promise a time frame, but I have that OCD you describe.  Will add to TODO list.

**Comment by kuaashish** [comment]
Hello @ghost,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
