### ISSUE TITLE
Confidence score in the Iris tracking solution

### ISSUE THREAD

**Issue by vovaani** [google/mediapipe#2196]
Hi,

I'm using the Iris tracking solution in Python (after applying the patch described [here](https://github.com/google/mediapipe/issues/1530#issuecomment-820129222)). I'm interested in identifying frames in which the Iris is not visible because of obstruction by a glasses frame / a hand or something else. 

I thought to use a confidence score for this purpose, however I've noticed that unlike face mesh, the Iris solution does not export any score of confidence (explored the [iris_landmark.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/iris_landmark/iris_landmark.tflite) file and it does not seem to have confidence tensors exported).

Is it possible to export a confidence score in the Iris solution?
Alternatively, is there another good solution in my case?

Thank you!
Vova

**Comment by sgowroji** [comment]
Hi @vovaani, [This](https://github.com/google/mediapipe/issues/644#issuecomment-619149060) could be helpful for youre use case. But it was in Palm and Try with Iris and let us know, if you have any difficulty. Thanks!

**Comment by vovaani** [comment]
Great, thanks for the super quick answer! I'll try that.

Just to make sure - I see [the face landmark detection output stream](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/iris_tracking/iris_tracking_cpu.pbtxt#L33) which contains the detection message that AFAIU covers all the landmarks, except the ones added [exclusively by Iris](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/iris_tracking/iris_tracking_cpu.pbtxt#L94). 

Am I missing something? If not, is there a detection message for the Iris landmarks as well?

Thank you!

**Comment by vovaani** [comment]
So I extracted the [face detections](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/iris_tracking/iris_tracking_cpu.pbtxt#L33) and here are a few findings:
1. There is a global score for the entire face detection (as opposed to a score per landmark as I thought previously).
2. The score seems to reflect major obstructions of the face. So for example if I put a hand in front of my eyes the score goes down from ~0.9 in this image -
![1](https://user-images.githubusercontent.com/84718338/122744505-b5135a00-d290-11eb-930b-87581c5a6cff.jpg)

to ~0.8 in this image -
![2](https://user-images.githubusercontent.com/84718338/122744522-b93f7780-d290-11eb-8d9f-d7d0f9a0de81.jpg)

3. The score does not seem to reflect small obstructions, like glasses that obstruct the eye with the frame. The score remains 0.9 in the following image - 
![3](https://user-images.githubusercontent.com/84718338/122744531-bba1d180-d290-11eb-89a8-d15e13cab820.jpg)

Given this findings it seems that I can probably solve part of my problem using the score from face detections, but not all of it. Is there something else I should consider? 

Thank you!

**Comment by vovaani** [comment]
Thank you! Will check and update here.

**Comment by vovani** [comment]
Following up - we were successful in using 'refine_landmarks' to extract the iris landmarks directly from face_mesh. This is very convinient, so thank you for that!! 

Howere, the issue described here still stands - the confidence score is a global score, and we did not find a reliable way to use it in order to understand if someone's eyes are visible or not.

**Comment by sgowroji** [comment]
Reopened the above issue as the second query still exist. @vovani we have assigned it to the engineer who will assist you better on the above. Thanks!

**Comment by ayushgdev** [comment]
Hello @vovani Are you still looking for a resolution on this issue?

**Comment by vovaani** [comment]
Hello @ayushgdev,

Yes, it would be nice to have a resolution for this issue!

Thank you,

**Comment by kuaashish** [comment]
Hello @vovani,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
