### ISSUE TITLE
Mediapipe debugging in VScode

### ISSUE THREAD

**Issue by zzmicer** [google/mediapipe#2197]
Is there any method/plugin to debug C++ mediapipe code in Visual Studio Code?

**Comment by sgowroji** [comment]
Hi @zzmicer,  Could you please share whether  you  are not able to debug using [this](https://code.visualstudio.com/docs/cpp/cpp-debug). And what is the error while trying with it. Thanks!

**Comment by zzmicer** [comment]
Hi @sgowroji, I try to debug Hand Tracking solution. I've already built it with `bazel build -c dbg --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu`

This is my configuration for `launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "LaunchDBG",
            "type": "cppdbg",
            "request": "launch",
            "program": "{my_path_to_mediapipe_repo}/bazel-out/k8-dbg/bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu",
            "args": [],
            "stopAtEntry": false,
            "cwd": "{my_path_to_mediapipe_repo}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```
When I launch debugging in VScode I get: `&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"`
And then: `E20210622 16:16:44.424080 13715 demo_run_graph_main.cc:154] Failed to run the graph: ; Can't find file: 
[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-umj2pouj.kvu" 1>"/tmp/Microsoft-MIEngine-Out-t565qo5v.ubg"`

**Comment by zzmicer** [comment]
Also, I get this error window in VScode
![Screenshot from 2021-06-22 16-38-52](https://user-images.githubusercontent.com/41323462/122934878-938d9d80-d378-11eb-938c-a8df14c4c405.png)

**Comment by sgowroji** [comment]
Hi @zzmicer, After investigating the above with my team. We general use terminal or command prompt to build and run the code. We are not sure with your error. Thanks!

**Comment by chendadon** [comment]
> Hi @zzmicer, After investigating the above with my team. We general use terminal or command prompt to build and run the code. We are not sure with your error. Thanks!

Hi, can you share the way you are debugging the code? even from cmd

**Comment by sgowroji** [comment]
Hi @chendadon, We don't recommend any as of now. but you can try doing with VScode from here https://docs.microsoft.com/en-us/visualstudio/debugger/quickstart-debug-with-cplusplus?view=vs-2019

**Comment by Soberii** [comment]
WARNING: Logging before InitGoogleLogging() is written to STDERR
F20230407 13:25:36.869844 27284 collection.h:55] Failed to get tag "C2__PACKET" index 0
*** Check failure stack trace: ***
F20230407 13:25:36.869844  8704 collection.h:55] Failed to get tag "C2__PACKET" index 0
