### ISSUE TITLE
Using KNIFT feature vectors with vector similarity search?

### ISSUE THREAD

**Issue by pablogranolabar** [google/mediapipe#2198]
**System information** 

Flutter / tflite front end which performs realtime KNIFT vector feature analysis, and streams discovered vectors to a vector similarity search engine such as [FAISS](https://github.com/facebookresearch/faiss). Target platform is Flutter / Dart with tflite KNIFT model inference.

I am curious if there are any implementation suggestions for a realtime KNIFT classifier running on mobile, and streaming via gRPC KNIFT feature vectors to a vector similarity search engine? The goal would be realtime 3D object detection using approximate nearest neighbor search via FAISS, and with FAISS populated with previously scanned 3D object feature vectors.

**Comment by kuaashish** [comment]
Hello @pablogranolabar,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
