### ISSUE TITLE
error: 'boxPoints' is not a member of 'cv'

### ISSUE THREAD

**Issue by Sara533** [google/mediapipe#220]
Does OpenCV 2.x currently works?
I got an error about opencv.
My opencv is 2.4.7.
So I must use a higher version???

**Comment by Sara533** [comment]
The error has been solved.

**Comment by jiuqiant** [comment]
Glad to hear that you solved the problem by yourself.

**Comment by soinipe** [comment]
Related cases #140 and #160, just in case some other newcomer hits this same problem: in my case I had both OpenCV 2.4.9  (at /usr) and OpenCV 3.4.7 (installed from sources to /usr/local). 

With default installation this caused that OpenCV 2 was used, and the compilation problem happened. I updated library configuration  in ./third_party/opencv_linux.BUILD:

```
# OpenCV installed to /usr/local
cc_library(
    name = "opencv",
    srcs = glob(
        [
            "local/lib/libopencv_core.so",
            "local/lib/libopencv_calib3d.so",
            "local/lib/libopencv_features2d.so",
            "local/lib/libopencv_highgui.so",
            "local/lib/libopencv_imgcodecs.so",
            "local/lib/libopencv_imgproc.so",
            "local/lib/libopencv_video.so",
            "local/lib/libopencv_videoio.so",
        ],
    ),
    hdrs = glob(["local/include/opencv2/**/*.h*"]),
    includes = ["local/include"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
```
I also cleaned my build with `bazel clean --expunge` just in case.
