### ISSUE TITLE
Handgesture Recognition with Gloves

### ISSUE THREAD

**Issue by lohith8099** [google/mediapipe#2200]
<em>We have been building mobile apps which helps motorcyclists and cyclists interact with their phones while riding wearing gloves . Can Mediapipe be used to detect hand gesuters when one is wearing gloves ?</em>

**Describe the feature and the current behavior/state:**

As of now mediapipe is able to detect hand gestures sucessfully. But it would be great it we have a way to detect handgestures while wearing gloves. I know it is not possible to detect finer details. But actions such as thumbsup, thumbs down swipe left, right should be possible ? This allows hands free interaction and also enhance safety rather than press traditional buttons on the device. And the riders can keep their eyes on the road.

**Will this change the current api? How?**

**Who will benefit with this feature?**
Any job or project in which people are not able to interact with the device using their hands. What if I can enter the device pin with my hand gestures. 4321 ? Or dial an emergency number with a gesture ? Or control music on my phone while riding with just a swipe ?

**Please specify the use cases for this feature:**

**Any Other info:**

**Comment by sgowroji** [comment]
Hi @lohith8099, Which platform are you looking the above feature request. Thanks!

**Comment by Swazir9449** [comment]
@lohith8099 Use object detection API. Feel free to DM me if you have any questions. My discord is KanyeWest#4519.

**Comment by crpistillo** [comment]
Hi @sgowroji can we reopen this? I'm also looking for a ML mdoel that scans glvoes. Is there any way to make it work tih Hand tracking of MediaPipe? It works sometimes but not always. Is there any way to set a skin color (glove color in my case)?

**Comment by EliaTolin** [comment]
News? Workaround?
