### ISSUE TITLE
straight facing the camera for pose estimation that the feet are slightly behind the hip and knees on the z-axis

### ISSUE THREAD

**Issue by gb2111** [google/mediapipe#2203]
When analyzing z-axis of pose detection seems that the pose is leaning forward, feet are behind the hip, and knees.

**Comment by sgowroji** [comment]
Hi @gb2111, Could you please provide a video or screenshot for the above issue with  error logs and complete steps to reproduce it.

**Comment by gb2111** [comment]
I am using this project
https://github.com/ntu-rris/google-mediapipe/blob/main/code/01_video.py
There is useful 2.5D view where you can compare depth of for example arms and feet and see it leaning forward.
There is also 3D plot and you can rotate it with mouse to see the pose from the side.
Let me know if you have additional questions

**Comment by sgowroji** [comment]
Hi @gb2111,  Recently we updated the released model to produced additional world 3D landmarks output with origin in hips center.
More details can be found in API: https://google.github.io/mediapipe/solutions/pose#pose_world_landmarks
And in the blog: https://blog.tensorflow.org/2021/08/3d-pose-detection-with-mediapipe-blazepose-ghum-tfjs.html

**Comment by gb2111** [comment]
Thanks
