### ISSUE TITLE
Does mediapipe support NTCHW input or 5 Dimension tensor in GPU ?

### ISSUE THREAD

**Issue by tianxiaguixin002** [google/mediapipe#2206]
Hi， everybody,
I have a tflite model which input is NTHWC and output is NHWC，it is a video model which need to process n frame and outout 1 frame ,just like video super-resoultion model. so can 
mediapipe support this type input from video streams?  
example:  throttled_input_video -> IMAGES_GPU(multi image in gpu buffer) -> TENSOR_GPU

Besides,  I create a Tensor, it's shape is (for example ,1,5,256,256,3) and copy  the opencv's DNN blob memory to tensor in linux with c++ (no gpu), use tflite graph to run the input , and the output image is correct,  so can I  convert a cpu tensor to tensor_gpu in mobile platform (linux demo has gpu version)? how to implement it ? thank for your answer！

**Comment by sgowroji** [comment]
Hi @tianxiaguixin002, Could you please respond which solution are you referring to the above query. If you are still looking resolution for this issue. Thanks!
