### ISSUE TITLE
Face detection

### ISSUE THREAD

**Issue by Monibsediqi** [google/mediapipe#2207]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** Android Galaxy Tab A 2016 
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 8
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.4
- Bazel version: NA
- Solution (e.g. FaceMesh, Pose, Holistic): Face detection
- Programming Language and version ( e.g. C++, Python, Java): Python and Java

**Describe the expected behavior:**
The output of face detection (bounding box and keypoints) is jittering (shaking). How can I reduce the jittering problem of face detection? 
I need to get the stable face detection bounding box. 
I know by using some average filter or 1 euro filter this jittering will be reduced. 
How would you reduce the jittering completely without applying any filter?? Any high definition model??

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/825
