### ISSUE TITLE
Hands tracking sample app shows blank screen on launch

### ISSUE THREAD

**Issue by ravikumar-ramamurthy** [google/mediapipe#2208]
<em>[Hands tracking](https://google.github.io/mediapipe/solutions/hands) issue.<em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution
Vuzix M400 Android smart glass
8 Core 2.52Ghz Qualcomm XR1
6GB LPDDR4 RAM
64GB internal flash memory
Android 9.0 OS
- MediaPipe version: v0.8.2
- Solution : Hands tracking gpu version
- Programming Language and version : Java

**Describe the expected behavior:**
The hands tracking sample code with AAR built, shows blank screen on launch without land mark callback on Vuzix device, but the same app works fine on other mobile device like Samsung A50. The behavior on Vuzix device is also not consistent that blank screen is shown... first time when app is installed and launched, sure a blank screen, then multiple attempts of closing, starting apps will show the camera stream.

**Standalone code you may have used to try to get what you need :**
No code was added, just the aar build sample from this link was used GitHub - jiuqiant/mediapipe_multi_hands_tracking_aar_example: MediaPipe multi-hand tracking gpu demo with MediaPipe's Android archive library along with the hand tracking sample from media pipe website.

After debugging and looking at the logs, it seems CameraXPreviewHelper class is not getting the input stream, but no clue why this does not work. Trying a sample app with just the Preview android class to stream the camera, works just fine. Seems there is there is something in the CamerXPreviewHelper class and any help in this is appreciated.

**Other info / Complete Logs :**
The is the log when the app is launched and shows up blank screen. The screenshot of the app on the device is also attached.
[blank_screen.txt](https://github.com/google/mediapipe/files/6706564/blank_screen.txt)
![blank_screen](https://user-images.githubusercontent.com/58554998/123209516-5a6f3d80-d4de-11eb-9998-9539d872134e.png)

Any help/clues is appreciated.

Thanks in advance

**Comment by ravikumar-ramamurthy** [comment]
Since this is smart glass and has only 1 camera, the sample code is changed to use BACK camera.. just a note.

**Comment by sgowroji** [comment]
Hi @ravikumar-ramamurthy, Did you change the code as below for back camera?

`private static final CameraHelper.CameraFacing CAMERA_FACING = CameraHelper.CameraFacing.FRONT;` to this
` private static final CameraHelper.CameraFacing CAMERA_FACING = CameraHelper.CameraFacing.BACK;`.

**Comment by ravikumar-ramamurthy** [comment]
Hi @sgowroji  Yes... i have changed this and works on mobile Samsung A50 and sometime also works on Vuzix device. We also tried on another smartglass device like Realwear HMT1 with similar hardware and s/w specs. Still the same result.

**Comment by mirwisek** [comment]
I have the same issue tested with Realme 5 Pro (Android 10.0). On first time launch the libraries are not loading and sending any video stream output to CameraX and it is blank. On restarting the app it works. Not sure what is causing the glitch.

**Comment by brucechou1983** [comment]
https://github.com/google/mediapipe/issues/1508 same issue?

**Comment by eknight7** [comment]
Thanks @brucechou1983 
Can @mirwisek and @ravikumar-ramamurthy please try if https://github.com/google/mediapipe/issues/1508#issuecomment-812390364 fixes the issue?
Thanks!

**Comment by ravikumar-ramamurthy** [comment]
Bingo...

Dear @eknight7 and @brucechou1983 

Thanks very much for this link... tested on Realwear and Vuzix device and this works as expected... camera opens up for first time and also getting callback.. I can proceed now... 

Before logging this issue, I searched here with "blank screen" text and did not find 1508 issue as title has text as "bla**c**k screen" !!!.

Should there be bug reported on mediapipe sample to be fixed in the master code?

Thanks again very much. The issue can be closed..

**Comment by mirwisek** [comment]
> Thanks @brucechou1983
> Can @mirwisek and @ravikumar-ramamurthy please try if [#1508 (comment)](https://github.com/google/mediapipe/issues/1508#issuecomment-812390364) fixes the issue?
> Thanks!

@eknight7 that didn't work for me I added comment back in the main issue [#1508].
