### ISSUE TITLE
Yoga, Dance, HIIT datasets available?

### ISSUE THREAD

**Issue by mgarbade** [google/mediapipe#2209]
I've noticed that you eval your pose models on specific datasets such as the above mentioned, for example
[here](https://google.github.io/mediapipe/solutions/pose).

Are these datasets publically available?

**Comment by sgowroji** [comment]
Hi @mgarbade, Could you please provide you're use case with respective above request. Thanks!

**Comment by mgarbade** [comment]
We could use such datasets for model evaluation in the context of a master thesis

**Comment by sgowroji** [comment]
Hi @mgarbade, We opensource only the  MediaPipe solutions. Thanks!
