### ISSUE TITLE
 Is there any way to assign a specific gpu device ID for mediapipe web(js api)?

### ISSUE THREAD

**Issue by senshin998** [google/mediapipe#2211]
such as "pose.gpu_device=1, pose.send(image) ", This is very necessary when there are multiple graphics cards on the machine

**Comment by sgowroji** [comment]
Hi @senshin998, Could you please elaborate your use case with complete details. Thanks!

**Comment by senshin998** [comment]
thanks for your reply, I'm  using  Body Pose Tracking with MediaPipe web api ,while  there are three graphics cards on my machine  and web pose api   alway chose Gpu 0 ,I want to  assign a specific gpu device ID  for it  such as only use gpu 2,Is this possible?   
 
os:windows 10
Browser:  chorme

**Comment by sgowroji** [comment]
Have a look at this https://github.com/google/mediapipe/issues/2472#issuecomment-962167806

**Comment by tyrmullen** [comment]
This is more of a question about your web browser and its APIs, and not something MediaPipe has any control over.  MediaPipe uses WebGL for its rendering, which provides no way to choose GPU device.  I don't even know of any way within the browser to choose GPU device.  However, there are external programs which will let you choose (like gSwitch on Mac, or driver-specific control panels on Windows [NVIDIA Control Panel, AMD Catalyst Control Center]).  If you have updated Windows 10, though, then it looks like you should be able to [assign GPUs to specific applications](https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/).

**Comment by sgowroji** [comment]
Hi @senshin998, Could you please go through  the above [comment](https://github.com/google/mediapipe/issues/2211#issuecomment-969283444)
