### ISSUE TITLE
tflite model loader not finding face_landmark.tflite and face_detection_front.tflite

### ISSUE THREAD

**Issue by YousefAttia-git** [google/mediapipe#2213]
**System information** Windows 10, 16GB ram, mediapipe v0.7

I am trying to make an application with the face mesh solution in python, however I noticed that my terminal fills up with this error:
>WARNING: Logging before InitGoogleLogging() is written to STDERR W20210620 20:04:23.755256 57220 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/face_detection/face_detection_front.tflite INFO: Created TensorFlow Lite XNNPACK delegate for CPU. W20210620 20:04:23.762224 58324 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/face_landmark/face_landmark.tflite

the code I wrote that caused this issue is very similar to that presented on the media pipe website, and it does generate the Facemesh as expected, however, this issue seems to be causing high memory usage since whenever I start creating the Face mesh ram usage increases with each frame

**Standalone code to reproduce the issue:**
```Python
def __init__(self,staticMode = False,maxFaces=1,detConfidence=0.5,trackConfidence=0.5):
        self.staticMode = staticMode
        self.maxFaces = maxFaces
        self.detConfidence = detConfidence
        self.trackConfidence = trackConfidence

        self.mpDraw = mp.solutions.drawing_utils
        self.mpFaceMesh = mp.solutions.face_mesh
        self.faceMesh = self.mpFaceMesh.FaceMesh(self.staticMode, self.maxFaces,
                                                 self.detConfidence, self.trackConfidence)
        self.drawSpec = self.mpDraw.DrawingSpec(thickness=1,circle_radius=2)

    def makeFaceMesh(self,img,draw=False):
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        results = self.faceMesh.process(imgRGB)
        if results.multi_face_landmarks:
            for face_landmarks in results.multi_face_landmarks:
                if draw:
                    self.mpDraw.draw_landmarks(
                        image= img,
                        landmark_list=face_landmarks,
                        landmark_drawing_spec=self.drawSpec,
                        connection_drawing_spec=self.drawSpec
                    )

def main():
    cap=cv2.VideoCapture(0)
    while cap.isOpened():
        reading,img = cap.read()
        if not reading:
            print("Ignoring empty frame")
            continue
        face_mesh = FindFaceMesh(
            staticMode=False,
            maxFaces=1,
            detConfidence=0.5,
            trackConfidence=0.5
        )
        face_mesh.makeFaceMesh(img,False)
        cv2.imshow('Webcam',img)
        cv2.waitKey(1)

```

**Other info / Complete Logs:**
graph of memory usage
![Memory usage](https://i.ibb.co/9T8pTX0/mess.jpg)

**Comment by YousefAttia-git** [comment]
that bit of memory before the ramp was from before I ran the program, it was probably from chrome, so I should only call FindFaceMesh() once?

**Comment by jiuqiant** [comment]
> that bit of memory before the ramp was from before I ran the program, it was probably from chrome, also, what could be causing those messages

That's a warning message not an error. See https://github.com/google/mediapipe/issues/2138. Also, if you git pull the latest version, the message is gone.

**Comment by YousefAttia-git** [comment]
oh, was the issue from me using pip install instead of a git pull?

**Comment by YousefAttia-git** [comment]
thanks
