### ISSUE TITLE
Face detection mobile output bitmap null

### ISSUE THREAD

**Issue by Monibsediqi** [google/mediapipe#2218]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 8.1.0
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Galaxy Tab A 2016
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: NA
- Programming Language and version ( e.g. C++, Python, Java): Kotlin 
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.4
- Bazel version (if compiling from source): 4.1.0
- Solution ( e.g. FaceMesh, Pose, Holistic ): Face Detection Mobile CPU
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): 
- Xcode & Tulsi version (if issue is related to building for iOS): NA

**Describe the current behavior:**
I slightly modified the out_stream in the graph. In order to get the output bitmap image I added:
out_stream:input_video_cpu
This input_video_cpu is received from the following calculator:
node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "throttled_input_video"
  output_stream: "input_video_cpu"
}
This is how I get the bitmap image from the graph:

processor!!.graph.addPacketCallback("input_video_cpu") { packet ->
            val frame = AndroidPacketGetter.getBitmapFromRgba(packet)
//            val rgbMapPut = Bitmap.createScaledBitmap(frame, 1920, 1080, false)

            rgbMap[packet.timestamp.toString()] = frame
}
Please note that If I try to createScaledBitmap as specified in the above commented out statement of the code, I get all null output. 
Right now I get the following output:
current Bitmap Width: 2069, Height: 1164
current Bitmap Width: null, Height: null
current Bitmap Width: null, Height: null
current Bitmap Width: null, Height: null
current Bitmap Width: null, Height: null
current Bitmap Width: null, Height: null
current Bitmap Width: null, Height: null
current Bitmap Width: 2069, Height: 1164
current Bitmap Width: 2069, Height: 1164
current Bitmap Width: 2069, Height: 1164
current Bitmap Width: null, Height: null
current Bitmap Width: null, Height: null
current Bitmap Width: null, Height: null

**Describe the expected behavior:**
The expected output behavior is a non-null (image).

Please let me know if you needed more details to better understand the problem
Anyone, please reply if you have faced a similar problem and solved it.

**Comment by sgowroji** [comment]
Hi @Monibsediqi, Could you please provide the below details to investigate it further. 

1. Complete Code changes of graph and MainActivity.java
3. Image tried for testing, which resulted null for the bitmap.
4. Tested on what version of Android studio?

Thanks!

**Comment by Monibsediqi** [comment]
I solved this issue. Thanks.
The problem was with the timestamp of the image.

**Comment by Moufdi96** [comment]
@Monibsediqi  I tried you approach to retrieve input frames but it keeps crashing showing this log 
"A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 18307 (Thread-20), pid 18097 (m.example.testApp)"
Do you by any chance know the reason ?
