### ISSUE TITLE
Pose Estimation leads to heavy RAM usage and low throughput

### ISSUE THREAD

**Issue by pranjalchanda08** [google/mediapipe#2220]
**System information:**
- OS Platform and Distribution: **Ubuntu 20.04, Windows 10**
- MediaPipe version: **0.8.5**
- Bazel version: N/A
- Solution: **Pose**
- Programming Language and version: **Python 3.7, 3.10**
- CPU: **Intel i7 8th Gen**
- RAM: **16GB**

**Expected behavior:**
Expected behavior is to use minimal resources for the prediction using the model as is being used by face detection or hand tracking solutions. 
When running pose estimation other applications starts to crash since the RAM usage is increased rapidly.

**Standalone code:**

Github: [https://github.com/pranjalchanda08/MediaPipe-Project/tree/master/utils](https://github.com/pranjalchanda08/MediaPipe-Project/tree/master/utils)

```py
python3 pose_estimation.py
```

We can see the RAM usage increases drastically and then crashes as reaches the limit of the system.

![image](https://user-images.githubusercontent.com/40349163/123623078-ae558b80-d82a-11eb-9a44-dd69b87151aa.png)

**PS**: Kindly, let me know if this issue can be solved by using GPU and the steps to use the same for both Win and Ubuntu.

**Comment by jiuqiant** [comment]
Like what I mentioned in https://github.com/google/mediapipe/issues/2213#issuecomment-869743712, it seems that you create a new mediapipe pose instance per frame at https://github.com/pranjalchanda08/MediaPipe-Project/blob/d5e84cdde73e995eece757a680b90d4b27a52cfc/utils/pose_estimation.py#L60. I would like to understand if there is a reason behind this?

**Comment by pranjalchanda08** [comment]
Hi @jiuqiant, 
Thanks for pointing the mistake. I would take care of that in my code.

**Comment by pranjalchanda08** [comment]
Hi Team,

Thanks for the suggestion. The issue is resolved by initializing the instance only once.
