### ISSUE TITLE
Hand tracking training 

### ISSUE THREAD

**Issue by Rakeshvcr** [google/mediapipe#2225]
I am trying to train a hand keypoint model with more than 21 key points. I build the model using the[ hand landmark tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark.tflite) model as a reference. Currently, I'm just trying to get only the landmarks as output from the model. For losses, I'm using mean squared error losses as defined in the [paper](https://arxiv.org/pdf/2006.10214.pdf) and using Adam as my optimizer function. 
I need some help with training the model, The losses are not decreasing after doing few changes. The results from the model are not good for few images,

These are the results from the model. Green points are ground truth and red points are predicted results.   

![Screenshot from 2021-06-25 14-54-37](https://user-images.githubusercontent.com/42342388/123754522-9ccabd00-d8d8-11eb-83f1-60b3884ac3b5.png)
![Screenshot from 2021-06-25 14-55-32](https://user-images.githubusercontent.com/42342388/123754524-9e948080-d8d8-11eb-863b-c020b48c3c32.png)
![Screenshot from 2021-06-25 14-55-58](https://user-images.githubusercontent.com/42342388/123754525-9f2d1700-d8d8-11eb-8b3c-fcafb98b681e.png)
 
Please provide any suggestion regarding training the model

**Comment by kuaashish** [comment]
Hello @Rakeshvcr,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
