### ISSUE TITLE
In C++ ,I can get mat result from demo_run_graph_main.cc, but how can I get output_stream: "render_data_vector"?

### ISSUE THREAD

**Issue by sewage1213** [google/mediapipe#2227]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):
- Programming Language and version ( e.g. C++, Python, Java):

**Describe the expected behavior:**

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

Like title，I try to get 'output_stream: "render_data_vector"' to use data for other calculatings, thanks!

**Comment by sgowroji** [comment]
Hi @sewage1213, Could you please elaborate your use case with complete details. Thanks!

**Comment by sewage1213** [comment]
Hi @sgowroji ,In /mediapipe/mediapipe/examples/desktop/demo_run_graph_main.cc, I can get result calculated by mediapipe, but it is a mat not a vector, I just want to get data but image. In demo_run_graph_main.cc, there are many functions of mediapipe but I cannot find where are them, the codes is too large, I try to find some ways to solve it.Thanks!

**Comment by sureshdagooglecom** [comment]
Hi @sewage1213 ,
Are you still looking for the resolution on this issue.
