### ISSUE TITLE
How to build Mediapipe from source with existing 3rd-party libraries installed from repo ?

### ISSUE THREAD

**Issue by jiapei100** [google/mediapipe#2228]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 20.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc (GCC) 10.3.1 
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.8.5
- Installed using virtualenv? pip? Conda? (if python): pip 21.1.3
- [MediaPipe version](https://github.com/google/mediapipe/releases): master branch, commit 374f5e2e7e818bde5289fb3cffa616705cec6f73 
- Bazel version: 4.1.0
- XCode and Tulsi versions (if iOS): N/A
- Android SDK and NDK versions (if android): N/A
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): N/A
- OpenCV version (if running on desktop): 4.5.2

**Describe the problem**: Just want to know, if there is a way to avoid downloading and building all required packages from source under folder **third_party** ?

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

```console
➜  mediapipe git:(master) ✗ bazel build -c opt --linkopt=-s \
  --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 --define no_aws_support=true \
  mediapipe/examples/desktop/youtube8m:extract_yt8m_features
```

It's seriously out of my expectation: the above command started rebuilding my manually installed tensorflow 2.6 ??? 

Sorry for my naive question. Is there a way to build mediapipe using existing (either from repo or manually built) third party libraries? 

Thank you

**Comment by brucechou1983** [comment]
If you're talking about Tensorflow, Mediapipe actually specify a [commit id](https://github.com/google/mediapipe/blob/master/WORKSPACE#L387) so it's probably not the version you install manually. Furthermore, there are [git patches](https://github.com/google/mediapipe/blob/master/WORKSPACE#L395) to make it work.

**Comment by sgowroji** [comment]
Hi @jiapei100, Did you face any error while installation? Could you please share the logs.
