### ISSUE TITLE
video input for hand tracking again :)

### ISSUE THREAD

**Issue by twoleggedeye** [google/mediapipe#223]
I've seen the issue #207 , but found out that there is file graph "hand_tracking_desktop.pbtxt" that supposed to take video as input, 
so I ran the following command (looking at the example for object detection)

`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu     --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop.pbtxt --input_video_path=/home/user/Desktop/videos/input.mov --output_video_path=/home/user/Desktop/videos/outputvideofile.mp4`

and got the following output:
`I1106 14:24:50.977983 11153 demo_run_graph_main.cc:52] Initialize the calculator graph.
I1106 14:24:50.979641 11153 demo_run_graph_main.cc:56] Initialize the camera or load the video.
I1106 14:24:50.987290 11153 demo_run_graph_main.cc:69] Prepare video writer.
I1106 14:24:50.995375 11153 demo_run_graph_main.cc:81] Start running the calculator graph.
E1106 14:24:50.996424 11153 demo_run_graph_main.cc:141] Failed to run the graph: ValidateRequiredSidePackets failed to validate: 
; Side packet "input_video_path" is required but was not provided.
; Side packet "output_video_path" is required but was not provided.`

But the file "outputvideofile.mp4" was created by this command

Am I doing something wrong or I can't use this graph file?

Thank you!

**Comment by wyuzyf** [comment]
can you solve this problem?

**Comment by loompa** [comment]
@wyuzyf 
`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu     --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt --input_video_path=input.mp4 --output_video_path=output.mp4`

**Comment by shehramjamil** [comment]
Unable to run the output video.
Any hint?

**Comment by atikrahman1** [comment]
facing same issue any update?

**Comment by atikrahman1** [comment]
`/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_cpu.exe --calculator_graph_config_file=mediapipe/graphs/hand_tracking/multi_hand_tracking_desktop.pbtxt --input_video_path=mediapipe/input/sample_improve.mp4 --output_video_path=mediapipe/output/sample_output.mp4`

Gives me the output of 

`E20201103 16:20:36.195762  3768 demo_run_graph_main.cc:146] Failed to run the graph: ; capture.isOpened()(mediapipe/examples/desktop/demo_run_graph_main.cc:65)`

**Comment by shehramjamil** [comment]
@atikrahman1  why are you using .exe ? Try removing it. 
And The problem is , your file is not found.
Try to give the full absolute path for the both input and output video like this : /home/usr/ . . . .  .

**Comment by atikrahman1** [comment]
> @atikrahman1 why are you using .exe ? Try removing it.
> And The problem is , your file is not found.
> Try to give the full absolute path for the both input and output video like this : /home/usr/ . . . . .

I have built it on a windows machine which gave .exe extension that's not the problem. How ever I solved it by changing OpenCV version to 3.4.12
