### ISSUE TITLE
Feature: Synchronization between iris and face landmarks

### ISSUE THREAD

**Issue by slajar** [google/mediapipe#2230]
<em>We need a feature that synchronizes the detected iris and face landmarks </em>

**System information**

- MediaPipe Solution (you are using): iOS (iris_tracking_gpu.pbtxt)
- Programming language : C++/Objective C/Swift
- Are you willing to contribute it (Yes/No): Yes

**current behavior/state:**
The iris landmarks are calculated with a lower frame rate due to the FlowLimiterCalculator.
The face landmarks are calculated with a higher frame rate

**Will this change the current api? **

No.

**Who will benefit with this feature?**

Anyone, who needs to have exact same values for iris and face landmarks

**Any Other info:**

I already tried to use the "updated_face_landmarks", but in this case "only" the iris landmarks are doubled. My expectation would be to have fewer facial landmarks only with the same frame rate as the iris landmarks.

**Comment by brucechou1983** [comment]
It seems to me that PacketClonerCalculator is all you need. Just set the iris landmarks stream as the tick signal.
 
BTW, you might want to move the FlowLimiterCalculator to the very top of the graph to make sure you don't waste any time for facial landmarks computation on the frame which will be dropped.

**Comment by lindemeier** [comment]
> It seems to me that PacketClonerCalculator is all you need. Just set the iris landmarks stream as the tick signal.
> 
> BTW, you might want to move the FlowLimiterCalculator to the very top of the graph to make sure you don't waste any time for facial landmarks computation on the frame which will be dropped.

@brucechou1983 Thank you for your info!

We are interested in the the exact version of facial landmarks that were used as input for the iris landmark detection so that we can process them together with the underlying video frames. 

From my understanding (according to the [documentation](https://google.github.io/mediapipe/framework_concepts/calculators.html) ) the `PacketClonerCalculator` will always output the most recent packet when it receives an input packet on its `TICK` stream.
This would mean in our case that it will output facial landmarks newer than the iris landmarks resulting in a similar problem as long as the iris detection is slower than the video frame rate. The facial landmarks would not match the iris landmarks.
Is that correct or I am confusing/misinterpreting something?

**Comment by brucechou1983** [comment]
@lindemeier 

By default (I mean using the DefaultInputStreamHandler), calculators will execute the **Process()** function if there is a settled timestamp at all input streams with at least one input packet. Therefore the timestamp with only a packet at the **TICK** stream will not even be processed.

If what you want is to make sure every frame is processed synchronously by iris & face module, and you don't care output FPS. You could just move the flow limiter calculator to the very top of the graph.

**Comment by lindemeier** [comment]
Thx @brucechou1983 for your comment.

We have assumed that the flow limiter does exactly what we need. As long as we connect to the `IMAGE:throttled_input_video` the following data should be synchronized:
- image data 
- facial landmarks
- iris landmarks

However, our swift app receives facial landmarks at a much higher rate. 
It could be an issue on our side with the app itself. We'll check again.

**Comment by sgowroji** [comment]
@brucechou1983 Thank you for guidance.  Will reopen the thread, if the issue still persists.

**Comment by brucechou1983** [comment]
@lindemeier did you solve the issue?

**Comment by slajar** [comment]
No it is not solved at all. We worked around this issue somehow. Even though we will probably remove mediapipe from our application because of this.

**Comment by brucechou1983** [comment]
I can look into the problem if you have a minimum example for this issue.

**Comment by slajar** [comment]
@brucechou1983 well an example is not easy/small/minimum since this is a conceptual problem.
The pipeline approach is like image --> mediapipe --> doing some fancy processing --> output

You will never see this image form the output again or even capturing parameters at that time. My proposal here would be to hand in a void * pointer along with the image, that I can reinterprete_cast on the output. That is why this was not a bug, but a feature request.

**Comment by kuaashish** [comment]
Hello @slajar,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
