### ISSUE TITLE
undesired zoom for different devices

### ISSUE THREAD

**Issue by milad-4274** [google/mediapipe#2231]
Hi, I've used mediapipe examples in different devices. the output video seems smaller or larger in different devices while distance to phone is same. 
I guess this problem is for different screen resolution and aspect ratio. but it's not desired in my project. is there any method to solve this problem?
![1](https://user-images.githubusercontent.com/48384506/123961842-08d71f00-d9c6-11eb-92e1-d7c7b5123602.jpeg)
![2](https://user-images.githubusercontent.com/48384506/123961863-0d9bd300-d9c6-11eb-9d51-423737f46bd4.jpeg)

**Comment by sgowroji** [comment]
Hi @milad-4274, Above implementation was programmed to  choose the best ratio according to the needs of different apps. It should be programmed with your own custom camera code as your requirement. Similar like [this](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d/MainActivity.java#:~:text=//%20Find%20limiting%20side,cameraTextureWidth%20/%20(float)%20cameraTextureHeight%3B) you can target the desired way.

**Comment by milad-4274** [comment]
Thank you @sgowroji. I will check it and inform here if any problem.
