### ISSUE TITLE
No rules_cc - master.zip file not found 404 error 

### ISSUE THREAD

**Issue by shivSD** [google/mediapipe#2232]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): **ubuntu~18.04**
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): **gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)** 
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): c++
- Installed using virtualenv? pip? Conda? (if python): **Pip**
- [MediaPipe version](https://github.com/google/mediapipe/releases): **v0.8.5**
- Bazel version: **bazel 3.7.2**
- OpenCV version (if running on desktop):  **4.5.2**

**_Command_**
 bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu

**_Error Message or log_**
**WARNING: Download from https://github.com/bazelbuild/rules_cc/archive/master.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'rules_cc':
   Traceback (most recent call last)**

**Comment by sohailziahh** [comment]
thats probably because you dont have the latest pull. 
They made few changes, including the WORKSPACE file. So, look at the commits and either make those changes to your local workspace file or just take a pull. 

and also, run this command as well. `bazel clean --expunge`

**Comment by shivSD** [comment]
Now i'm getting following error

ERROR: /home/Downloads/mediapipe/mediapipe/calculators/tensor/BUILD:627:11: C++ compilation of rule '//mediapipe/calculators/tensor:image_to_tensor_converter_gl_buffer' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 67 argument(s) skipped)


tried replacing https://github.com/google/mediapipe/issues/1673#issuecomment-797863638 same error.

**Comment by sohailziahh** [comment]
i am not sure about this error. it'd be better if u pull latest release, and then try again.

**Comment by shivSD** [comment]
i have tried latest version v0.8.5 , v0.8.4  and also master build, i see the same error from all the versions. Do you think i'm missing any installation that is missing in the install.md file.

**Comment by sgowroji** [comment]
Hi @shivSD, Its because your version of GCC is too old. Have a look at this  https://github.com/google/mediapipe/issues/1684#issuecomment-794590159

**Comment by zwfcrazy** [comment]
Because https://github.com/bazelbuild/rules_cc just changed its master branch name to **main**.
This problem literally made all the mediapipe versions before v0.8.5 (included) useless.
@sgowroji you need to lunch a new version ASAP.

**Comment by sgowroji** [comment]
@zwfcrazy, Thank you for the update. We will update you soon.

**Comment by shivSD** [comment]
Hi @sgowroji I'm working on GCC 7.5 version which is latest part of the ubuntu 18.04. Please can you recommend the gcc version.
Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by linyu0219** [comment]
modify the WORKSPACE under the mediapipe root folder.
urls = ["https://github.com/bazelbuild/rules_cc/archive/master.zip"], -> urls = ["https://github.com/bazelbuild/rules_cc/archive/main.zip"]
