### ISSUE TITLE
Best practices for accurate Landmarks Detection

### ISSUE THREAD

**Issue by mufaawan** [google/mediapipe#2233]
**FaceMesh**: What are the best practices for the  accurate Landmark Detection? 

I have used MediaPipe facemesh solution on Google Colab. I have attached 2 images, both images has detection p**roblem in the eye area**. Both images are pretty good images with good resolution, clear pixels and frontal face (no rotation). 

Please suggest me if there are any hidden techniques to get more precise results. 
![test1-labeled](https://user-images.githubusercontent.com/17979287/124006685-ff64ab80-d9f3-11eb-95b6-d1301e3325af.png)
![test3-labeled](https://user-images.githubusercontent.com/17979287/124006715-08ee1380-d9f4-11eb-94f2-381ffa8af3ad.png)

Thank you.

**Comment by sgowroji** [comment]
Hi @mufaawan, Could you please share your code changes performed on top of it. Thanks!

**Comment by mufaawan** [comment]
> Hi @mufaawan, Could you please share your code changes performed on top of it. Thanks!

I have not made any changes in the code. It's just the code provided in the Notebook on Colab.

**Comment by sgowroji** [comment]
Hi @mufaawan, Could you please refer https://github.com/google/mediapipe/issues/2104#issuecomment-974981124 for clear understanding.
