### ISSUE TITLE
Implemented Iris in Python

### ISSUE THREAD

**Issue by DimIsaev** [google/mediapipe#2235]
When will **Iris** be implemented in **Python**

**Comment by DimIsaev** [comment]
up

**Comment by Ujwal2910** [comment]
is it implemented now?

**Comment by DimIsaev** [comment]
up

**Comment by Rassibassi** [comment]
Check out my mediapipe demo repository, run python iris.py after installation of all the pip packages and don't forget to also download the tf_lite model for the iris detection as described in the readme. It's not a single iris depth module, but does the job. I reimplemented the depth calculations in numpy.

https://github.com/Rassibassi/mediapipeDemos

**Comment by SaadBazaz** [comment]
Much needed. Seems simple enough considering that CPP code can be easily ported to Python.

**Comment by DimIsaev** [comment]
> that CPP code can be easily ported to Python.

who can it be easy?

most ML researchers do not know
and shouldn't know C ++

**Comment by SaadBazaz** [comment]
The Iris portion is written in C++, from my experience creating an abstraction over a lower-level implementation is at least easier than the other way round.

**Comment by sgowroji** [comment]
Hi @DimIsaev,  Will  share if there is any update of roadmap regarding the above feature. You can go through  this https://github.com/google/mediapipe/issues/2235#issuecomment-880981281 as of now.

**Comment by DimIsaev** [comment]
> Hi @DimIsaev, Will share if there is any update of roadmap regarding the above feature. You can go through this [#2235 (comment)](https://github.com/google/mediapipe/issues/2235#issuecomment-880981281) as of now.

yes   i use  this repository 

you include this codes в  public  repository  Mediapipe ?

**Comment by sandesh1994199** [comment]
Hi @Rassibassi 

Check out my mediapipe demo repository, run python iris.py after installation of all the pip packages and don't forget to also download the tf_lite model for the iris detection as described in the readme. It's not a single iris depth module, but does the job. I reimplemented the depth calculations in numpy.

https://github.com/Rassibassi/mediapipeDemos

I am facing the error mentioned below 

 c:\Users\snagaraj\Documents\git_repos\git_iris1>python iris.py -i gA_1_s1_2019-03-08T09;31;15+01;00_rgb_face.mp4
2021-09-01 14:37:21.813652: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "iris.py", line 167, in <module>
    main(args.i)
  File "iris.py", line 69, in main
    ) = from_landmarks_to_depth(
  File "c:\Users\snagaraj\Documents\git_repos\git_iris1\custom\iris_lm_depth.py", line 27, in from_landmarks_to_depth
    eye_contours, iris_landmarks = detect_iris(
  File "c:\Users\snagaraj\Documents\git_repos\git_iris1\custom\iris_lm_depth.py", line 61, in detect_iris
    outputs = tflite_inference(eye_frame_low / 127.5 - 1.0, model_path)
  File "c:\Users\snagaraj\Documents\git_repos\git_iris1\custom\core.py", line 11, in tflite_inference
    interpreter = tf.lite.Interpreter(model_path=model_path)
  File "C:\Users\snagaraj\documents\git_repos\git_iris1\env_iris\lib\site-packages\tensorflow\lite\python\interpreter.py", line 348, in __init__
    _interpreter_wrapper.CreateWrapperFromFile(
ValueError: Could not open 'models/iris_landmark.tflite'.
