### ISSUE TITLE
Error bazel install of Docker install

### ISSUE THREAD

**Issue by DimIsaev** [google/mediapipe#2236]
<em>Error bazel install of Docker install.</em>

**
- Windows 10 and Docker  image

 **(specified in /mediapipe/.bazelversion), but it wasn't found in /usr/local/lib/bazel/bin** 

> root@15f20ffdba71:/mediapipe#  GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
>  (specified in /mediapipe/.bazelversion), but it wasn't found in /usr/local/lib/bazel/bin.
> 
> Bazel binaries for all official releases can be downloaded from here:
>   https://github.com/bazelbuild/bazel/releases
> 
> You can download the required version directly using this command:
> -linux-x86_64)&& chmod +x bazel-3.7.2url -fLO https://releases.bazel.build/3.7.2

**Comment by sohail-jogo** [comment]
remove that file. 

just run the following: 

`rm .bazelversion`

**Comment by DimIsaev** [comment]
> remove that file.
> 
> just run the following:
> 
> `rm .bazelversion`

It`s works !!

**Comment by sgowroji** [comment]
Hi @DimIsaev,  Glad to know you resolved. Thank you @sohail-jogo  for your resolution. We are closing this issue now.

**Comment by DimIsaev** [comment]
> Hi @DimIsaev, Glad to know you resolved. Thank you @sohail-jogo for your resolution. We are closing this issue now.

Will this be the correct decision?
Why is this not included in the Docker pipeline image?
