### ISSUE TITLE
Cannot initialize pose in Javascript 

### ISSUE THREAD

**Issue by DanielWFrancis** [google/mediapipe#2237]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): **OS X Big Sur, Expo 41**
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): **React 16.13, React Native Expo 41**
- [MediaPipe version](https://github.com/google/mediapipe/releases): **"@mediapipe/pose": "^0.4.1624666670"**

**Describe the problem**:
My attempts to import and initialize Pose do not work.

```
import { Pose } from '@mediapipe/pose'

const pose = new Pose({
  locateFile: (path, base) => {
    return `base/node_modules/@mediapipe/pose/${path}`;
  }
});
```

Produces:

```
TypeError: undefined is not a constructor (evaluating 'new _pose.Pose({
    locateFile: function locateFile(path, base) {
      return "base/node_modules/@mediapipe/pose/" + path;
    }
  })')
```

I've tried a variety of things, finding (I think) every issue related to these kinds of problems and nothing works. I don't see any examples of installing via package manager and using the script that way, if I'm missing something let me know. Huge fan of the library and praying I can get this to work.

**Comment by bwl** [comment]
I'm having the same issue.

Not sure what is going on here?
But it seems the proposed solution presently is to wait for it to be open sourced?

https://github.com/google/mediapipe/issues/1408

https://github.com/google/mediapipe/issues/1411
https://github.com/google/mediapipe/issues/1719

**Comment by eldog** [comment]
It looks like the Pose object is on `window` so you can use the following as a work around.

```
import '@mediapipe/pose';
import type { Pose as PoseType } from '@mediapipe/pose';

// @ts-expect-error
const Pose = window.Pose as InstanceType<PoseType>;

console.log(new Pose()); // Works!
```

**Comment by basicvisual** [comment]
Hi @eldog , i think the error still persists `pose is not a construtor` . Is there something else you are doing perhaps ? Currently using the normal `expo init' method for creating project and using `expo camera` to capture video stream

**Comment by sgowroji** [comment]
Hi @DanielWFrancis,  Could you please try the pose [codepen](mediapipe.dev/demo/pose) examples ?

**Comment by jayshah52** [comment]
> Hi @eldog , i think the error still persists `pose is not a construtor` . Is there something else you are doing perhaps ? Currently using the normal `expo init' method for creating project and using `expo camera` to capture video stream

Did you get it to work? I am facing the error that Pose object is undefined and therefore is not a constructor
