### ISSUE TITLE
cant setText of EditText inside MediaPipe addPacketCallback

### ISSUE THREAD

**Issue by arslaanzafar** [google/mediapipe#2239]
I am using MediaPipe in Android to get the output from the graph, and set that output as EditText's text. Following is the code:

```
editText.setText("hello world".toString());
 processor.addPacketCallback(
          OUTPUT_STREAM_NAME,
          (packet) -> {
              String output = PacketGetter.getString(packet);
                  editText.setText("hello world 1".toString());
                  //editText.setText(output.toString());
              Log.d(TAG,"[TS:" + packet.getTimestamp() + " : " + ouput);
          });
```
the setText outside the callback works fine, but inside the callback is never set and whenever i try to select the the EditText following exception occurs:

`java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
`

**Comment by sgowroji** [comment]
Hi @arslaanzafar, The Exception is because your code implementation with EditText  component in android. May be you can try clearing the values and selection before setting the text to it. Thanks!

**Comment by arslaanzafar** [comment]
it was throwing exception because the setText should be called inside runOnUiThread if we are using addPacketCallback.

**Comment by sgowroji** [comment]
Have you tried  using [this](https://stackoverflow.com/questions/7028185/android-thread-modify-edittext)
