### ISSUE TITLE
.NET Support

### ISSUE THREAD

**Issue by sr229** [google/mediapipe#2240]
In the same vein as GH-36, we should have a pure .NET port also of the library. I don't see anyone starting with it so I decided to take it on my own hands.

Current progress work is on [the vignette-project](https://github.com/vignette-project/Akihabara) repository, it's based off of UnityMediaPipePlugin but we'll take some liberties on how to integrate the native library on this.

**Comment by sgowroji** [comment]
Hi @sr229, Good to know your work with MediaPipe. Could you please elaborate your query to understand much better. Thanks!

**Comment by sr229** [comment]
> Hi @sr229, Good to know your work with MediaPipe. Could you please elaborate your query to understand much better. Thanks!

Currently there's no way to use Mediapipe in .NET without getting through the pain of writing your own wrapper for it, and Mediapipe is a very popular project for AR and object tracking, this was rather a big roadblock for us at Vignette, so we're now implementing our own wrapper by now to be used by us (and probably everyone).

**Comment by sgowroji** [comment]
Thank you for the update. Moving forward if there are any plans in our roadmap, we will let you know. Please subscribe to our channels
