### ISSUE TITLE
fail to build for iris_tracking_cpu_video_input

### ISSUE THREAD

**Issue by pkyadav73199** [google/mediapipe#2243]
OS Platform : Linux Ubuntu 16.04
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
Programming Language and version ; C++ 11
pip
OpenCV 3

**C++ compilation of rule '//mediapipe/util:annotation_renderer' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 60 argument(s) skipped)**

**Comment by sgowroji** [comment]
Hi @pkyadav73199, Could you please test the above with latest version. The above issue is resolved as of now. Thanks!

**Comment by pkyadav73199** [comment]
I just updated the version of gcc.
Now I am getting this error.

/home/edith/mediapipe/mediapipe/util/BUILD:127:11: undeclared inclusion(s) in rule '//mediapipe/util:annotation_renderer':
this rule is missing dependency declarations for the following files included by 'mediapipe/util/annotation_renderer.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/9/include/stdarg.h'
  '/usr/lib/gcc/x86_64-linux-gnu/9/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/9/include/emmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/9/include/xmmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/9/include/mmintrin.h'
  '/usr/lib/gcc/x86_64-linux-gnu/9/include/mm_malloc.h'
  '/usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/9/include/syslimits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/9/include/float.h'
Target //mediapipe/examples/desktop/iris_tracking:iris_tracking_cpu_video_input failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.907s, Critical Path: 3.77s
INFO: 130 processes: 130 internal.
FAILED: Build did NOT complete successfully

**Comment by sgowroji** [comment]
Did you install with latest release from [here](https://github.com/google/mediapipe/releases/tag/v0.8.6)
