### ISSUE TITLE
Access node outputs of a graph  

### ISSUE THREAD

**Issue by jameel-malik** [google/mediapipe#2244]
How to access the node outputs of a graph, for example, in the following graph 
https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_gpu.pbtxt
I want to access  output_stream: "FLOAT:hand_presence_score" of the node calculator: "TensorsToFloatsCalculator" 
as the output of this graph (similar to other outputs which are   output_stream: "HANDEDNESS:handedness"
and output_stream: "LANDMARKS:hand_landmarks").

**Comment by sgowroji** [comment]
Hi @jameel-malik, We have documented the calculators and graph implementation  here with complete details https://google.github.io/mediapipe/framework_concepts/calculators.html#identifying-inputs-and-outputs. Please have a look and reach us back if you still have any further queries on top of it.
