### ISSUE TITLE
pose detection - determine distance from camera / z in world coordinate

### ISSUE THREAD

**Issue by gb2111** [google/mediapipe#2246]
hello.
pose landmars provide x and y and also z coordinate. z is depth relative to hip joints.
x and y of hips can be used to calculate relative position of the human in world. but not z.
i'd appreciate mediapipe team to share if they have any formula to estimate distance from camera.
thank you.

**Comment by sgowroji** [comment]
For pose landmarks here we have very clear documentation. https://google.github.io/mediapipe/solutions/pose#output. Please go through it and reach us if you still have any further queries. Thanks!

**Comment by dantonioangela** [comment]
> 
Hi! Did you figured out how to do it?
