### ISSUE TITLE
Face Detection Integration issues from a Web React JS client.

### ISSUE THREAD

**Issue by eshajoshi** [google/mediapipe#2248]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
React JS, Typescript Template
Mac laptop with M1 chip
Chrome browser, Incognito

Context:
Currently, I have a simple React JS app with a TypeScript template. This is because the MediaPipe Face Detection CodePen demo is in TypeScript so I'm trying to simplify everything at the moment to emulate what they've done.

Problem:
I'm unable to properly hit the Face Detection APIs. I'm getting a lot of warnings and errors (see screenshot below) hitting the v0.4 endpoint (https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.4/${file}). I'm not sure how to proceed here.

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

![image](https://user-images.githubusercontent.com/5433044/124362329-0bfe2500-dbe9-11eb-9799-ae8bb57f66d4.png)

**Comment by sgowroji** [comment]
Hi @eshajoshi, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by eshajoshi** [comment]
Hey @sgowroji , thanks for taking a look at this!

I actually copied the CodePen code from the Face Detection demo onto a React JS app with a TypeScript template. I am running that code with 'npm start' which is casting the TypeScript file into a JS file so that it can be rendered in the browser. The warnings and errors above are from running `localhost: 3000`.

Here is the source code below if that'll help with debugging:

I had some issues with FPS and calling MediaPipe libraries, etc.

---

`import { FaceDetection, Results, Options } from '@mediapipe/face_detection'
import { drawRectangle, drawLandmarks } from '@mediapipe/drawing_utils'
import { ControlPanel, StaticText, Toggle, SourcePicker, InputImage, Rectangle, Slider } from '@mediapipe/control_utils'

/**
 * @fileoverview Demonstrates a minimal use case for MediaPipe face tracking.
 */

 const controls = window;
 const drawingUtils = window; 
 const mpFaceDetection = window;
 
 // Our input frames will come from here.
 const videoElement =
     document.getElementsByClassName('input_video')[0] as HTMLVideoElement;
 const canvasElement =
     document.getElementsByClassName('output_canvas')[0] as HTMLCanvasElement;
 const controlsElement =
     document.getElementsByClassName('control-panel')[0] as HTMLDivElement;
 const canvasCtx = canvasElement.getContext('2d')!;
 
 // We'll add this to our control panel later, but we'll save it here so we can
 // call tick() each time the graph runs.
 // @ts-ignore
//  const fpsControl = new FPS();
 
 // Optimization: Turn off animated spinner after its hiding animation is done.
 const spinner = document.querySelector('.loading')! as HTMLDivElement;
 spinner.ontransitionend = () => {
   spinner.style.display = 'none';
 };
 
 function onResults(results: Results): void {
   // Hide the spinner.
   document.body.classList.add('loaded');
 
   // Update the frame rate.
  //  fpsControl.tick();
 
   // Draw the overlays.
   canvasCtx.save();
   canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
   canvasCtx.drawImage(results.image, 0, 0, canvasElement.width, canvasElement.height);

   if (results.detections.length > 0) {
     drawRectangle(
         canvasCtx, results.detections[0].boundingBox,
         {color: 'blue', lineWidth: 4, fillColor: '#00000000'});
     drawLandmarks(canvasCtx, results.detections[0].landmarks, {
       color: 'red',
       radius: 5,
     });
   }
   canvasCtx.restore();
 }
 
 const faceDetection = new FaceDetection({locateFile: (file) => {
   return `https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.4/${file}`;
 }});
 faceDetection.onResults(onResults);
 
 // Present a control panel through which the user can manipulate the solution
 // options.
 new ControlPanel(controlsElement, {
       selfieMode: true,
       minDetectionConfidence: 0.5,
     })
     .add([
       new StaticText({title: 'MediaPipe Face Detection'}),
      //  fpsControl,
       new Toggle({title: 'Selfie Mode', field: 'selfieMode'}),
       new SourcePicker({
         onSourceChanged: () => {
           faceDetection.reset();
         },
         onFrame:
             async (input: InputImage, size: Rectangle) => {
               const aspect = size.height / size.width;
               let width: number, height: number;
               if (window.innerWidth > window.innerHeight) {
                 height = window.innerHeight;
                 width = height / aspect;
               } else {
                 width = window.innerWidth;
                 height = width * aspect;
               }
               canvasElement.width = width;
               canvasElement.height = height;
               await faceDetection.send({image: input});
             },
         examples: {
           videos: [],
           images: [],
         }
       }),
       new Slider({
         title: 'Min Detection Confidence',
         field: 'minDetectionConfidence',
         range: [0, 1],
         step: 0.01
       }),
     ])
     .on(x => {
       const options = x as Options;
       videoElement.classList.toggle('selfie', options.selfieMode);
       faceDetection.setOptions(options);
     })`

**Comment by eshajoshi** [comment]
Hey @tyrmullen - any thoughts on this? Thanks so much!

**Comment by tyrmullen** [comment]
Looking at the initial error, it seems like the file "face_detection_short_range.tflite" isn't being found, and this is causing the issues you're seeing.  Try the debugging steps and workarounds from issue #2181 , and let me know what those print out for you.

**Comment by sgowroji** [comment]
Hi @eshajoshi, Did you get a chance to go through the above [comment](https://github.com/google/mediapipe/issues/2248#issuecomment-875881905). Thanks!

**Comment by eshajoshi** [comment]
Thanks so much @sgowroji , I'll follow up with this soon! Appreciate the help here.

**Comment by lolz0r** [comment]
@sgowroji I saw the same issue. It looks like the code on the [main site](https://google.github.io/mediapipe/solutions/face_detection.html) is out of date. When setting the model options it should actually match the codepen-demo code: 
```
 faceDetectionModel.setOptions({
                        selfieMode: true,
                        model: 'short',
                        minDetectionConfidence: 0.5,
                    });
```

That being said, I could see the  CodePen code being hard to understand due to how the options are routed to the model.
