### ISSUE TITLE
 highly INACCURATE outputs - Release open Model source so users can improve/expand on it & share with community

### ISSUE THREAD

**Issue by yolo-1111** [google/mediapipe#2249]
Im having MASSIVE problems with  mediapipe's landmarks outputs. It is disasterously inaccurate if there is a small head turn (even at 30 degree) that landmarks output is simply useless.  What is the purpose of releasing mediapipe without releasing model source for custom training when its current outputs are just do bad and highly inaccurate that they are rendered useless? 

I agree with the user who pointed out two major points - 
1) outputs are more highly inaccurate than those shown in demo - STARK difference. Outputs im getting are useless
2)  "In deep learning, without model source, it is NOT an open source project. " especially if outputs are so highly inaccurate almost all the time.

Its not that it is only x% accurate....i mean it has problem with almost every output!!! We cant create meaningful visual content when these tracking outputs are just plain bad.  

So Let me ask - What is Google mediapipe trying to accomplish with what it has release the pretrained model without model source when it gives highly inaccurate outputs most of time. What do you want us to do with it? 

Im user upset because basically Google Mediapipe is wasting everyone's time. I have spent so much time trying to work with it and improve the output to no avail.  It has no respect for users' time and efforts. Why doesn't Mediapipe open Model source for fork and let users add more data, try to improve the model and  share the improve the outputs/model and knowledge with everyone else? Facebook and others do it all the time. They basically provide an ecosystem where developers will improve and expand on it. Otherwise it is simply a waste of time.
And i think you have gotten ENOUGHHHHH feedback from github users that mediapipe outputs HAVE SO MANY PROBLEMs that it simply isnt usable in the real world. Hope you don't ask me to describe use case - (working on making cool animation content and creation of digital characters)

We are not asking you to improve the model. We will do that. we will improve/expand on them and the share with the community. thank you

**Comment by kuaashish** [comment]
Hello @yolo-1111,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
