### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by DimIsaev** [google/mediapipe#2252]
1. Install bazelisk  
2.  App hello world   - bulid  OK

3, build app iris_tracking  Error
`!bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/iris_tracking:iris_tracking_cpu_video_input  `

```
mediapipe/mediapipe/calculators/tensor/BUILD:601:11: 
C++ compilation of rule '//mediapipe/calculators/tensor:image_to_tensor_converter_opencv' failed (Exit 1):
 gcc failed: error executing command
 /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections
 ... (remaining 61 argument(s) skipped)
```

what can you advise?

**Comment by sgowroji** [comment]
Hi @DimIsaev, Did you test the above in the latest  [release](https://github.com/google/mediapipe/releases/tag/v0.8.6).

**Comment by DimIsaev** [comment]
> Hi @DimIsaev, Did you try the above from the latest [release](https://github.com/google/mediapipe/releases/tag/v0.8.6).

```git clone --depth 1 --branch v0.8.6 --recurse-submodules https://github.com/google/mediapipe.git```

**Comment by DimIsaev** [comment]
Errro command

```!python setup.py install --link-opencv --user```

![1111](https://user-images.githubusercontent.com/11172642/124424893-f710c580-dd91-11eb-8681-d0f946fff19b.png)

**Comment by DimIsaev** [comment]
not solution

**Comment by sureshdagooglecom** [comment]
Hi @DimIsaev ,
Could you please reproduce the above error with the latest release and let us know if the issue still exists. Thanks!
