### ISSUE TITLE
How use Mediapipe API  for Python  Iris Depth ?

### ISSUE THREAD

**Issue by DimIsaev** [google/mediapipe#2254]
How use Mediapipe API   for  Iris Depth  Python solution?

Where can I find a similar example?
Thanks

**Comment by sgowroji** [comment]
Hi @DimIsaev, You can try [this](https://github.com/google/mediapipe/issues/1530#issuecomment-819552656).

**Comment by DimIsaev** [comment]
I could not run from the code from the link

**Comment by DimIsaev** [comment]
How long wait answer ?

**Comment by Rassibassi** [comment]
Or check out my mediapipe demo repository, run `python iris.py` after installation of all the pip packages and don't forget to also download the tf_lite model for the iris detection as described in the readme.

https://github.com/Rassibassi/mediapipeDemos

**Comment by DimIsaev** [comment]
> Or check out my mediapipe demo repository, run `python iris.py` after installation of all the pip packages and don't forget to also download the tf_lite model for the iris detection as described in the readme.
> 
> https://github.com/Rassibassi/mediapipeDemos

ok.  I go testing

**Comment by sgowroji** [comment]
Hi @Rassibassi, Thank you for your contribution the demo  really would help the community.

**Comment by Ammar-Fasih** [comment]
> Or check out my mediapipe demo repository, run `python iris.py` after installation of all the pip packages and don't forget to also download the tf_lite model for the iris detection as described in the readme.
> 
> https://github.com/Rassibassi/mediapipeDemos
[iris_landmark.zip](https://github.com/google/mediapipe/files/10012191/iris_landmark.zip)


if the above link for 'iris_landmark.tflite' is broken, you can download the file from below. :)
