### ISSUE TITLE
Can MediaPipe running both face mesh and hand detection at the same time on Android device?

### ISSUE THREAD

**Issue by LiHuaigu** [google/mediapipe#2256]
**Issue Description**
- Hi, I'm currently trying to build an Android App that can both detect hands and faces. Is this feasible?
- Thanks in advance.

**Comment by brucechou1983** [comment]
[holistic](https://google.github.io/mediapipe/solutions/holistic#mediapipe-holistic) = face + hand + pose

**Comment by LiHuaigu** [comment]
> [holistic](https://google.github.io/mediapipe/solutions/holistic#mediapipe-holistic) = face + hand + pose

Thank you very much!

**Comment by mellonSugar** [comment]
> [holistic](https://google.github.io/mediapipe/solutions/holistic#mediapipe-holistic) = face + hand + pose

Can somebody help me use Mp Holistics on android
I find it very tough to open and use the prebuilt APK example by google [here](https://google.github.io/mediapipe/solutions/holistic.html)

**Comment by yosun** [comment]
> holistic

page not found? @brucechou1983
