### ISSUE TITLE
iOS Framework Error: "'absl/memory/memory.h' file not found"

### ISSUE THREAD

**Issue by nswdewy** [google/mediapipe#2257]
Hi!

I'm attempting to compile a posetracking framework to my project.

@noppefoxwolf's demo can run successfully, but is not a framework for whole pose tracking.

I can build and run the application successfully by tulsi or command lines.

But when I use the complied framework to a project, it occurs error "'absl/memory/memory.h' file not found"
![image](https://user-images.githubusercontent.com/26194478/124540104-5255bd00-de51-11eb-8e75-1f082ca3662b.png)

I have been stuck with this problems for couple of days….

Dose anybody have the solution to this problem?  
I will be very grateful for your suggestions.

_Originally posted by @nswdewy in https://github.com/google/mediapipe/issues/364#issuecomment-874441936_

**Comment by nswdewy** [comment]
![image](https://user-images.githubusercontent.com/26194478/124580739-04f24380-de83-11eb-93d1-530dd47a7b82.png)

the [Uploading BUILD…]() in "common" directory
[common.zip](https://github.com/google/mediapipe/files/6769121/common.zip)

the [Uploading BUILD…]() in "posetrackinggpu"
[posetrackinggpu_.zip](https://github.com/google/mediapipe/files/6769104/posetrackinggpu_.zip)

**Comment by sgowroji** [comment]
Hi @nswdewy, Could you please provide steps to reproduce the above error. Thanks!

**Comment by nswdewy** [comment]
> Hi @nswdewy, Could you please provide steps to reproduce the above error. Thanks!

1. Open Tulsi by  "sh build_and_run.sh"
2. Open MediaPipe.tulsiproj which in "mediapipe/medipipe/" 
3. choose the target
![image](https://user-images.githubusercontent.com/26194478/124585577-01ad8680-de88-11eb-832d-c14aece38df2.png)
![image](https://user-images.githubusercontent.com/26194478/124585684-1ee25500-de88-11eb-8424-c130bf3076fb.png)

then generate the framework project:
![image](https://user-images.githubusercontent.com/26194478/124586254-cd869580-de88-11eb-9363-5dbe05ba2499.png)
![image](https://user-images.githubusercontent.com/26194478/124586669-4ab20a80-de89-11eb-8a73-23a86a700a7a.png)

4. Use the .framework
at first it occurs :
![sp20210706_184006_942](https://user-images.githubusercontent.com/26194478/124587176-e93e6b80-de89-11eb-855d-1970369ba966.png)
then I and the search paths:
![Uploading sp20210706_184041_672.png…]()

after that, it shows "'absl/memory/memory.h' file not found":
![image](https://user-images.githubusercontent.com/26194478/124587472-3a4e5f80-de8a-11eb-8bf2-eaeffb37054f.png)

**Comment by nswdewy** [comment]
The problem has been fixed, There is a detail "Do not set the import at the .h file while you produce the framework"
