### ISSUE TITLE
Mediapipe integration with OR-Tools 

### ISSUE THREAD

**Issue by VladYushchenko** [google/mediapipe#2258]
**System information** (Please provide as much relevant information as possible)

- OS: Ubuntu 18.04
- Programming Language and version: C++
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.0
- OR-Tools version: v9.0 / v8.0
- Bazel version (if compiling from source): 4.1.0

Hi, I have a problem with integration of both Mediapipe and [OR-Tools](https://github.com/google/or-tools) in the same repository.

Both are included in Bazel's BUILD as following:

```
git_repository(
    name = "com_google_ortools",
    commit = "8d19323", # release v8.0
    remote = "https://github.com/google/or-tools.git",
)

_MEDIAPIPE_VERSION = "0.8.0"

http_archive(
    name = "mediapipe",
    sha256 = "0b129a28864fd2cd2822948621645efb9d62b6d043d1c4da3cf2d01886bfd901",
    strip_prefix = "mediapipe-{}".format(_MEDIAPIPE_VERSION),
    url = "https://github.com/google/mediapipe/archive/{}.tar.gz".format(_MEDIAPIPE_VERSION),
)
```

Firstly, I have tried to use Mediapipe 0.8.0 with the recent OR-Tools v9.0, but the build fails with a Glog error [v9.0_GlogError.txt](https://github.com/google/mediapipe/files/6769438/v9.0_GlogError.txt)

As suggested by OR-Tools [here](https://github.com/google/or-tools/issues/2378), the latter can be only resolved by downgrading OR-Tools to v8.0

Consequently, switching to v8.0 induces various typedef errors between OR-Tools and Mediapipe [v8.0_TypeError.txt](https://github.com/google/mediapipe/files/6769512/v8.0_TypeError.txt).

**Expected behavior:**
I would expect that at least one configuration would work, but for me it seems to be a deadlock.

Thanks!

**Comment by sgowroji** [comment]
Hi @VladYushchenko, Could you please provide, your use case with complete details on integrating MediaPipe with OR-Tools.

**Comment by VladYushchenko** [comment]
Yes, sure @sgowroji 

I have C++ implementation of SORT Tracker https://arxiv.org/abs/1602.00763
which essentially is combination of a Kalman filter (OpenCV) and a matching algorithm (I use Hungarian algorithm from OR-Tools) 

Medipipe is used for model inference and subsequent video rendering with tracked objects.

Hope it helps you further.

**Comment by VladYushchenko** [comment]
Closing this issue, the problem seems to be on OR-Tools side.

See more details in https://github.com/google/or-tools/issues/2634
