### ISSUE TITLE
I want to get the image data after face detection. What should I do?

### ISSUE THREAD

**Issue by teleger** [google/mediapipe#226]
Can I output face detection image data after face detection, whether it can be similar to ImageCroppingCalculator operator, configured in face_detection_mobile_cpu(gpu).pbtxt

**Comment by eknight7** [comment]
Are you trying to capture the output of a calculator? Also, are you trying to do this on Android/iOS or desktop?

**Comment by teleger** [comment]
> Are you trying to capture the output of a calculator? Also, are you trying to do this on Android/iOS or desktop?

i want to get image data,in order to register or recongnize
