### ISSUE TITLE
Displaying poseWorldLandmarks in Javascript webclient.

### ISSUE THREAD

**Issue by basicvisual** [google/mediapipe#2261]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example: 
https://google.github.io/mediapipe/solutions/pose.html
## Description of issue (what needs changing):

Hi  I am using googles POSE model to run a web application in React Js. I am able to log out the `poseWorldLandmarks` but i am not able to vizualize it. It complains that `new landmarkGrid(landmarkContainer)` is not a constructor. What is the way to display the 3d pose landmarks ? 

### Parameters defined
Models parameters defined as shown in the code snippet 

### Usage example
Code snipped added here (of working web JS client) 
```
import { Pose, POSE_CONNECTIONS, LandmarkGrid, PoseConfig } from '@mediapipe/pose'
import * as cam from '@mediapipe/camera_utils'
import { drawConnectors, drawLandmarks} from '@mediapipe/drawing_utils'
import Webcam from 'react-webcam'
import React, { useRef, useEffect } from "react";
import "@tensorflow/tfjs-core";
import "@tensorflow/tfjs-converter";
import "@tensorflow/tfjs-backend-webgl";
//import {ControlPanel,FPS, StaticText, Slider,Toggle } from '@mediapipe/control_utils/control_utils';
function App() {
  const webcamRef = useRef(0)
  const canvasRef = useRef(0)
  var camera = null
  function onResults(results) {
    //console.log(results)
    //console.log(results.poseWorldLandmarks)
    // Define the canvas elements 
    canvasRef.current.width = webcamRef.current.video.videoWidth
    canvasRef.current.height = webcamRef.current.video.videoHeight
    // Check for useing the front camera 
    const canvasElement = canvasRef.current;
    const canvasCtx = canvasElement.getContext("2d")
    // Define the girods here 
    // End 
    canvasCtx.save();
    canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
    canvasCtx.drawImage(results.image,
      0,
      0,
      canvasElement.width,
      canvasElement.height
    )
    drawConnectors(canvasCtx,
      results.poseLandmarks, POSE_CONNECTIONS,
      { color: '#FFFFFF', lineWidth: 2 });
    // The dots are the landmarks 
    drawLandmarks(canvasCtx, results.poseLandmarks,
      { color: '#FFFFFF', lineWidth: 2, radius: 2 });
    drawLandmarks(canvasCtx, results.poseWorldLandmarks,
      { color: '#FFFFFF', lineWidth: 2, radius: 2 });
    canvasCtx.restore();
  }
  useEffect(() => {
    const pose = new Pose({
      locateFile: (file) => {
        return `https://cdn.jsdelivr.net/npm/@mediapipe/pose/${file}`;
      }
    });
    pose.setOptions({
      modelComplexity: 1,
      smoothLandmarks: true,
      minDetectionConfidence: 0.5,
      minTrackingConfidence: 0.5
    });
    pose.onResults(onResults)
    if (typeof webcamRef.current !== "undefined" && webcamRef.current !== null) {
      camera = new cam.Camera(webcamRef.current.video, {
        onFrame: async () => {
          await pose.send({ image: webcamRef.current.video })
        },
        width: 400,
        height: 400
      });
      camera.start()
    }
  })
  return (
    <div className="App">
      <Webcam
        ref={webcamRef}
        style={{
          position: "absolute",
          marginLeft: "0px",
          marginRight: "0px",
          left: 0,
          right: 0,
          textAlign: "center",
          zindex: 9,
          width: 400,
          height: 400,
          marginBottom: "0px",
        }} />
      <canvas
        ref={canvasRef}
        style={{
          position: "absolute",
          marginLeft: "0px",
          marginRight: "0px",
          left: 0,
          right: 0,
          textAlign: "center",
          zindex: 9,
          width: 400,
          height: 400,
          marginBottom: "0px"
        }}>
      </canvas>
    </div>
  );
}
export default App;
```

See the API guide:
Link to the API guide: [Link](https://google.github.io/mediapipe/solutions/pose#javascript-solution-api)

**Comment by sgowroji** [comment]
Hi @basicvisual, Could you please share your error logs to understand the issue with much better detail. Thanks!

**Comment by basicvisual** [comment]
Hi I am trying to import the 3D Landmark grid as follows 
`
import { Pose, POSE_CONNECTIONS, LandmarkGrid, PoseConfig, landmarkContainer} from '@mediapipe/pose'`
and defining in the above code snippet as follows 

```
const grid = new LandmarkGrid(landmarkContainer, {
      connectionColor: 0xCCCCCC,
      definedColors:
          [{name: 'LEFT', value: 0xffa500}, {name: 'RIGHT', value: 0x00ffff}],
      range: 2,
      fitToGrid: true,
      labelSuffix: 'm',
      landmarkSize: 2,
      numCellsPerAxis: 4,
      showHidden: false,
      centered: true,
    });
```
But it gives the following error message 
`Unhandled Rejection (TypeError): _mediapipe_pose__WEBPACK_IMPORTED_MODULE_2__.LandmarkGrid is not a constructor`

**Comment by Rassibassi** [comment]
Hi,
having similar problem.

Your problem is that `LandmarkGrid` is not part of `@mediapipe/pose`, see [here](https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.4.1624666670/index.d.ts) for its interface.

`LandmarkGrid` is part of `@mediapipe/control_utils_3d`, see [here](https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d@0.2.1625245254/index.d.ts)

However, with `import LandmarkGrid from '@mediapipe/control_utils_3d';` I get the following error:
```
TypeError: THREE is undefined

./node_modules/@mediapipe/control_utils_3d/control_utils_3d.js/</<
http://localhost:3000/vendors~main.07d7684c857ebf1e8138.hot-update.js:21891:18
./node_modules/@mediapipe/control_utils_3d/control_utils_3d.js/</goog.loadModule
http://localhost:3000/vendors~main.07d7684c857ebf1e8138.hot-update.js:18301:27
./node_modules/@mediapipe/control_utils_3d/control_utils_3d.js/<
http://localhost:3000/vendors~main.07d7684c857ebf1e8138.hot-update.js:21791:6
./node_modules/@mediapipe/control_utils_3d/control_utils_3d.js
http://localhost:3000/vendors~main.07d7684c857ebf1e8138.hot-update.js:23139:30
__webpack_require__
/data/projects/danceApp/danceapp/webpack/bootstrap:851
```

**Comment by mhays-google** [comment]
Interesting.  is code.mediapipe.dev/codepen/pose working for you?  Is it a
possible caching issue with control_utils_3d.js? Try

```
<script src="
***@***.******@***.***/control_utils_3d.js"
crossorigin="anonymous"></script>
```

If I can recreate this, I can help.

**Comment by Rassibassi** [comment]
Hi again,

I don't have a webcam on this machine, but will try with another machine later if that codepen works.

However, since we are using react, we are not including the `control_utils_3d.js` via a `script` tag, but through the package manager/npm.

Here is a minimal setup to recreate the error: https://github.com/Rassibassi/mediapipeReactPoseDebug

```
git clone https://github.com/Rassibassi/mediapipeReactPoseDebug.git
cd mediapipeReactPoseDebug
npm install
npm start
```

Thanks,
Rasmus

**Comment by mhays-google** [comment]
I think controls_3d is attractive, but it's really there to help us with
our own demos.  But I still want to make this easier for you.

I have an internal bug set for myself to validate our deployables through
npm.  I don't have a timeline at this moment.

**Comment by AHRealift** [comment]
status? Im getting same issue ...

import * as MPControlUtils3D from "@mediapipe/control_utils_3d"; // errs out

TypeError: Cannot read properties of undefined (reading 'Vector3')
(anonymous function)
http://localhost:3000/static/js/vendors~main.chunk.js:25917:28
push../node_modules/@mediapipe/control_utils_3d/control_utils_3d.js.goog.loadModule
http://localhost:3000/static/js/vendors~main.chunk.js:22152:27
(anonymous function)
http://localhost:3000/static/js/vendors~main.chunk.js:25858:6
./node_modules/@mediapipe/control_utils_3d/control_utils_3d.js
http://localhost:3000/static/js/vendors~main.chunk.js:27661:30

**Comment by sgowroji** [comment]
@AHRealift, Could you please provide more details with specific to error logs. When are the reproducing and steps to check internally. Or you can raise a new issue if the above issue content is not relevant to your query. Thanks!.

**Comment by nick-verida** [comment]
I'm trying rebuild the hands demo (or something similar) and I'm also getting the `Uncaught TypeError: THREE is undefined` error.

code is 

```
import * as THREE from "three";
import * as mpControls3d from "@mediapipe/control_utils_3d";

...
...

    const landmarkContainer = document.getElementsByClassName(
                              'landmark-grid-container')[0] as HTMLDivElement;
    const grid = new mpControls3d.LandmarkGrid(landmarkContainer, {
      connectionColor: 0xcccccc,
      definedColors: [
        { name: "Left", value: 0xffa500 },
        { name: "Right", value: 0x00ffff },
      ],
      range: 0.2,
      fitToGrid: false,
      labelSuffix: "m",
      landmarkSize: 2,
      numCellsPerAxis: 4,
      showHidden: false,
      centered: false,
    });
```

Error is

```
Uncaught TypeError: THREE is undefined
    <anonymous> control_utils_3d.js:4786
    loadModule control_utils_3d.js:1136
    <anonymous> control_utils_3d.js:4746
    <anonymous> control_utils_3d.js:5788
    node_modules chunk-vendors.js:1773
    __webpack_require__ index.js:854
```

I noticed that `control_utils_3d` doesn't declare a dependency on THREE. Maybe it should?


```
 "devDependencies": {
  },
  "dependencies": {
  },
```
