### ISSUE TITLE
iris tracking application for the full range face detection

### ISSUE THREAD

**Issue by SohilZidan** [google/mediapipe#2262]
- MediaPipe Solution (you are using): iris tracking
- Programming language: C++
- Are you willing to contribute it (Yes/No):

I would like to ask if you can provide an application for iris tracking full range. I am using the iris tracking applications with a video containing a person for which the face is not detected. when I realized that the iris tracking uses the short-range face detection module. is that possible?

**Comment by sgowroji** [comment]
Hi @SohilZidan, Could you please elaborate your use case with more details. Thanks!

**Comment by SohilZidan** [comment]
I am using the following command  to build an example application:
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/iris_tracking:iris_tracking_cpu_video_input`
an to run it on a video:
`bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_cpu_video_input     --calculator_graph_config_file=mediapipe/graphs/iris_tracking/iris_tracking_cpu_video_input.pbtxt     --input_side_packets=input_video_path=<inpupt_vid>,output_video_path=<output_vid>`
The videos contain children 6~10 years old, facing the camera or looking no more than 60 degree away from it, sitting on a chair. The children are of different colors.

The results in the case of irsi-tracking mentioned above are not satisfying, as the faces sometimes are not detected in very obvious cases when the children's faces are frontal, at the same time it detects awkward cases of the face.

However, As I dug in the code, I found out that [iris-tracking example application](https://github.com/google/mediapipe/blob/374f5e2e7e818bde5289fb3cffa616705cec6f73/mediapipe/examples/desktop/iris_tracking/BUILD#L50) uses as a [dependency](https://github.com/google/mediapipe/blob/374f5e2e7e818bde5289fb3cffa616705cec6f73/mediapipe/graphs/iris_tracking/BUILD#L35) the face-landmark module, which in turn uses the subgraph [face-detection-short-range-cpu](https://github.com/google/mediapipe/blob/374f5e2e7e818bde5289fb3cffa616705cec6f73/mediapipe/modules/face_landmark/BUILD#L73). As I tried to change this [line](https://github.com/google/mediapipe/blob/374f5e2e7e818bde5289fb3cffa616705cec6f73/mediapipe/modules/face_landmark/BUILD#L73):
`"//mediapipe/modules/face_detection:face_detection_short_range_cpu"`
into
`"//mediapipe/modules/face_detection:face_detection_short_full_cpu"`
build and run the application again:
```bash
# bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/iris_tracking:iris_tracking_cpu_video_input
...
INFO: Elapsed time: 206.534s, Critical Path: 96.66s
INFO: 2391 processes: 23 internal, 2368 linux-sandbox.
INFO: Build completed successfully, 2391 total actions
```
```bash
# bazel-bin/mediapipe/examples/desktop/iris_tracking/iris_tracking_cpu_video_input     --calculator_graph_config_file=mediapipe/graphs/iris_tracking/iris_tracking_cpu_video_input.pbtxt     --input_side_packets=input_video_path=<inpupt_vid>,output_video_path=<output_vid>
E20210707 09:34:32.144091 22489 simple_run_graph_main.cc:149] Failed to run the graph: ValidatedGraphConfig Initialization failed.
No registered object with name: FaceDetectionShortRangeCpu; Unable to find Calculator "FaceDetectionShortRangeCpu"
```
I tried this after I built the face-detection-full-range-cpu example and ran it to get excellent face detection results.

I hope this is a clear explanation

**Comment by sgowroji** [comment]
@SohilZidan, You should try with [back facing model ](https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_detection)which is bigger but intended to work for smaller and far way faces.

**Comment by eli-6over6** [comment]
what about this? are the facemesh/iris tracking can work with the full range face detector model?
