### ISSUE TITLE
error: [WinError 2] 系统找不到指定的文件。: 'C:\\mediapipe\\mediapi pe-master\\mediapipe/calculators/__init__.py'

### ISSUE THREAD

**Issue by philipjhc** [google/mediapipe#2263]
INFO: Analyzed target //mediapipe/modules/objectron:objectron_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/modules/objectron:objectron_cpu up-to-date:
  bazel-bin/mediapipe/modules/objectron/objectron_cpu.lo.lib
INFO: Elapsed time: 1.141s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
generating binarypb: mediapipe/modules/pose_landmark/pose_landmark_cpu
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  C:/users/philip/desktop/pingpangpose-mediapipe/mediapipe-master/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/philip/_bazel_philip/ysn7fczr/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to com
ply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "02413e4a077107711ecc21458432e7c9ba63e75e63f3fa84ae4da2d6b2c82700"
DEBUG: Repository rules_cc instantiated at:
  C:/users/philip/desktop/pingpangpose-mediapipe/mediapipe-master/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/philip/_bazel_philip/ysn7fczr/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe/modules/pose_landmark:pose_landmark_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/modules/pose_landmark:pose_landmark_cpu up-to-date:
  bazel-bin/mediapipe/modules/pose_landmark/pose_landmark_cpu.lo.lib
INFO: Elapsed time: 1.111s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
generating binarypb: mediapipe/modules/selfie_segmentation/selfie_segmentation_cpu
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  C:/users/philip/desktop/pingpangpose-mediapipe/mediapipe-master/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/philip/_bazel_philip/ysn7fczr/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to com
ply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "02413e4a077107711ecc21458432e7c9ba63e75e63f3fa84ae4da2d6b2c82700"
DEBUG: Repository rules_cc instantiated at:
  C:/users/philip/desktop/pingpangpose-mediapipe/mediapipe-master/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/philip/_bazel_philip/ysn7fczr/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe/modules/selfie_segmentation:selfie_segmentation_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/modules/selfie_segmentation:selfie_segmentation_cpu up-to-date:
  bazel-bin/mediapipe/modules/selfie_segmentation/selfie_segmentation_cpu.lo.lib
INFO: Elapsed time: 1.135s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
running build_ext
C:\software\bazel\bazel.exe build --compilation_mode=opt --copt=-DNDEBUG --define=MEDIAPIPE_DISABLE_GPU=1 --action_env=PYTHON_BIN_PATH=C:/Users/Philip/anaconda3/envs/pingpangpose/python.exe //mediapipe/python:_
framework_bindings.so
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  C:/users/philip/desktop/pingpangpose-mediapipe/mediapipe-master/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/philip/_bazel_philip/ysn7fczr/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/users/philip/_bazel_philip/ysn7fczr/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to com
ply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "02413e4a077107711ecc21458432e7c9ba63e75e63f3fa84ae4da2d6b2c82700"
DEBUG: Repository rules_cc instantiated at:
  C:/users/philip/desktop/pingpangpose-mediapipe/mediapipe-master/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/philip/_bazel_philip/ysn7fczr/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe/python:_framework_bindings.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/python:_framework_bindings.so up-to-date:
  bazel-bin/mediapipe/python/_framework_bindings.so
INFO: Elapsed time: 1.131s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
running modify_inits
running build_py
copying mediapipe\__init__.py -> build\lib.win-amd64-3.8\mediapipe
running egg_info
creating mediapipe.egg-info
writing mediapipe.egg-info\PKG-INFO
writing dependency_links to mediapipe.egg-info\dependency_links.txt
writing requirements to mediapipe.egg-info\requires.txt
writing top-level names to mediapipe.egg-info\top_level.txt
writing manifest file 'mediapipe.egg-info\SOURCES.txt'
reading manifest file 'mediapipe.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '.git*' found anywhere in distribution
writing manifest file 'mediapipe.egg-info\SOURCES.txt'
copying mediapipe\modules\face_detection\face_detection_full_range_cpu.binarypb -> build\lib.win-amd64-3.8\mediapipe\modules\face_detection
copying mediapipe\modules\face_detection\face_detection_short_range_cpu.binarypb -> build\lib.win-amd64-3.8\mediapipe\modules\face_detection
copying mediapipe\modules\face_landmark\face_landmark_front_cpu.binarypb -> build\lib.win-amd64-3.8\mediapipe\modules\face_landmark
copying mediapipe\modules\hand_landmark\hand_landmark_tracking_cpu.binarypb -> build\lib.win-amd64-3.8\mediapipe\modules\hand_landmark
copying mediapipe\modules\holistic_landmark\holistic_landmark_cpu.binarypb -> build\lib.win-amd64-3.8\mediapipe\modules\holistic_landmark
copying mediapipe\modules\objectron\objectron_cpu.binarypb -> build\lib.win-amd64-3.8\mediapipe\modules\objectron
copying mediapipe\modules\pose_landmark\pose_landmark_cpu.binarypb -> build\lib.win-amd64-3.8\mediapipe\modules\pose_landmark
copying mediapipe\modules\selfie_segmentation\selfie_segmentation_cpu.binarypb -> build\lib.win-amd64-3.8\mediapipe\modules\selfie_segmentation
running remove_generated
removing generated binary graphs: mediapipe/modules\face_detection\face_detection_full_range_cpu.binarypb
removing generated binary graphs: mediapipe/modules\face_detection\face_detection_short_range_cpu.binarypb
removing generated binary graphs: mediapipe/modules\face_detection\face_detection_short_range_cpu.binary
pb
removing generated binary graphs: mediapipe/modules\face_landmark\face_landmark_front_cpu.binarypb
removing generated binary graphs: mediapipe/modules\hand_landmark\hand_landmark_tracking_cpu.binarypb
removing generated binary graphs: mediapipe/modules\holistic_landmark\holistic_landmark_cpu.binarypb
removing generated binary graphs: mediapipe/modules\objectron\objectron_cpu.binarypb
removing generated binary graphs: mediapipe/modules\pose_landmark\pose_landmark_cpu.binarypb
removing generated binary graphs: mediapipe/modules\selfie_segmentation\selfie_segmentation_cpu.binarypb

error: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\Philip\\Desktop\\pingpangpose-mediapipe\\mediapi
pe-master\\mediapipe/calculators/__init__.py'
and
error: [Errno 13] Permission denied: 'build\\lib.win-amd64-3.8\\mediapipe\\python\\opencv_world3410.dll'
how to solve it?

**Comment by sgowroji** [comment]
Hi @philipjhc, Could you please provide steps to reproduce the above issue. Thanks!

**Comment by philipjhc** [comment]
> 嗨@philipjhc，您能否提供重现上述问题的步骤。谢谢！

I have solved this problem. I found that my workspace path is not right. Thank you. I can close this problem.

**Comment by YuhaoT** [comment]
> > 嗨@philipjhc，您能否提供重现上述问题的步骤。谢谢！
> 
> I have solved this problem. I found that my workspace path is not right. Thank you. I can close this problem.

Hi @philipjhc, I got the same error, could you tell me about how did you solve it? Thank you in advance!
