### ISSUE TITLE
How to understand the timestamp pipeline of PacketClonerCalculator in the official document

### ISSUE THREAD

**Issue by gunbuyidiu** [google/mediapipe#2265]
## Description of issue (what needs changing):

i can not understand  timestamp pipeline of PacketClonerCalculator in the official document

### Clear description

![image](https://user-images.githubusercontent.com/6594222/124759441-3726a280-df62-11eb-848f-999f7d3c97e1.png)

> 1、first process: when time is 4ms, the packets in the three streams are [**mic2**], [**NONE**], [**frame4**]， so output only **mic2** 

> 2、second process:  when time is 28ms,  PacketClonerCalculator has been executed once，so the remaining pakets in the stream should be   [**mic6**, **mic10**], [**light6**], [**frame28**], so  PacketClonerCalculator  output stream should be **mic6**, **light6**, because their timestamp is 2(if last packet is 1). But official document said result is **mic10**, **light6**

> 3、third procss: why **light6** still exists.  It should be popped when last process().

**Comment by brucechou1983** [comment]
I also found the diagram a little bit confusing when I tried to use **PacketClonerCalculator**. The diagram looks like the pipeline is using immediate input stream handler. I think it's just default input stream hander but ignored the timestamp bound. I recommend you to go through the [synchronization document](https://google.github.io/mediapipe/framework_concepts/synchronization.html#synchronization) and make sure you know the mechanism of input policies.

BTW, micX in the diagram actually means mic packet at timestamp Xms. So what happens in the **Process()** order by timestamp is:

[mic2, none, none] -> cache mic2
[none, none, frame4] -> output [mic2, none]
[mic6, light6, none] -> cache [mic6, light6]
[mic10, none, none] -> cache mic10
[none, none, fram28] -> output [mic10, light6]
[mic30, none, none] -> cache mic30
[mic42, none, none] -> cache mic42
[none, none, frame52] -> output [mic42, light6]

**Comment by gunbuyidiu** [comment]
@brucechou1983 
I have read the source code of the default input policy and timestamp pipeline.

If follow pipeline you said, it means that  PacketClonerCalculator::process() is called each time  a packet added to TICK input stream, and the packets queue in  **0** & **1**  stream only cache latest frame and only cache on frame ?

Is this a special input policy in the demo?

**Comment by brucechou1983** [comment]
@gunbuyidiu Like I said in the preview comment, I think it is default input policy, but the timestamp bound is ignored in the diagram. 

If you read the calculator source code, you'll find a variable named [current_](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/packet_cloner_calculator.cc#L81) storing the latest non empty packets for each stream. When **Process() is triggered and TICK is non empty**, the output stream will be assigned by **current_**. You can verify this by the time sequence in my preview comment with Process() function in the source code.

**Comment by gunbuyidiu** [comment]
@brucechou1983 

thx, I think I have understood this diagram. This  diagrame only shows the outputs corresponding to the process()  in timestamp **4**、**28**、**52** .

But in fact, the **2**、**6**ms ....... timestamp also calls process, but the logic inside the calculator source code is that as long as the TICK has no data, there is no output. only copy no-empty packets to current_ vector.

Is my understanding correct ?

**Comment by brucechou1983** [comment]
@gunbuyidiu exactly

**Comment by sgowroji** [comment]
@brucechou1983 Thank you for guiding the above comment. @gunbuyidiu  We are closing this issue now. Feel free to add if you still have any further queries on the above context. Thanks!
