### ISSUE TITLE
z value in pose_world_landmarks of Pose Solution

### ISSUE THREAD

**Issue by congnguyenthe** [google/mediapipe#2266]
Hi,

I have tried the latest mediapipe release with pose_world_landmarks for Pose Solution.
I would like to clarify the z value meaning. Is it the distance from the landmark point to the hip or is it the distance from the landmark point to the camera just like the z value from the Face Mesh solution?

**Comment by gb2111** [comment]
I am also interested in that.

**Comment by Vatsa0408** [comment]
I am also interested in this topic.

**Comment by sgowroji** [comment]
Hi @congnguyenthe, We have added clear documentation [here](https://google.github.io/mediapipe/solutions/pose#pose_landmarks) on the above request. Please go through them and let us know if you still have any specific query.  Thanks!
