### ISSUE TITLE
Callback in hand tracking when no hands are in the input frame

### ISSUE THREAD

**Issue by ravikumar-ramamurthy** [google/mediapipe#2268]
- OS Platform and Distribution Android 10
- Solution : Hand tracking solution from mediapipe
- Programming Language and version: Java

**Callback in hand tracking when no hands are in the input frame**

How to identify when there are no hands in the input frames. 

When the hands are in input frame the "hand_landmarks" callback is called with the proper data, but when the hand moves away from input frame there is no call back or any sort of information. Should some timer be implemented when there are no callbacks and assume no hands are in input frame or does mp has anything inbuilt? 

Tried "palm_detection" callback, but when there is no hand in the input frame, there is no way to know.

Seem such thing is possible in the python, but this is being tried in Java.

Any inputs is appreciated.

Thanks in advance.

**Comment by sgowroji** [comment]
Hi @ravikumar-ramamurthy, You can try this similar [approach](https://github.com/google/mediapipe/issues/2174#issuecomment-862152241) for hands.

**Comment by ravikumar-ramamurthy** [comment]
@sgowroji Thanks for this link. I tried the same approach and it worked.. 

Thanks again
