### ISSUE TITLE
Which dataset was used for hand detection/tracking?

### ISSUE THREAD

**Issue by Pikus16** [google/mediapipe#227]
Hello,

I was wondering what dataset was used for building the hand detection/tracking model and if it is publicly available.

Thank you!

**Comment by mgyong** [comment]
@Pikus16  The dataset is an internal google dataset. Unfortunately due to privacy reasons it will not be publicly available see #186 #13

**Comment by sunniehan** [comment]
I would like to inquire if there would be any issues related to dataset usage permission or copyright if I incorporate palm detection and pose landmark solutions into a product or app for commercial purposes.
