### ISSUE TITLE
Palm detection

### ISSUE THREAD

**Issue by Enmin** [google/mediapipe#2271]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic): handtracking
- Programming Language and version ( e.g. C++, Python, Java):

**Describe the expected behavior:**
I want to know how I can get palm detection data from the mp_hand_trakcing aar that I built. Currently, I only have handLandmarks class and locationData class in the framework.proto. I can only get landmarks data but I cannot get palm data such as x, y, width, height and rotation. How should I get the palm data (x, y, width, height, rotation)?

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by sgowroji** [comment]
Hi @Enmin, Assuming this [issue](https://github.com/google/mediapipe/issues/1927#issuecomment-829437449) as similar use case as yours.  Thanks!

**Comment by Enmin** [comment]
Hi @sgowroji Thanks for answering me. The review helps but I still have problems with palm data. This is my current code: 
![Screenshot from 2021-07-09 01-07-57](https://user-images.githubusercontent.com/23139990/125026265-310fef00-e052-11eb-8aec-113de231d462.png)
And this is my code for getting landmarks:
![Screenshot from 2021-07-09 01-09-10](https://user-images.githubusercontent.com/23139990/125026317-4b49cd00-e052-11eb-984d-2892d8630878.png)
In the second add packet call back function, I want to add packet for getting palm rect data. However, I currently only have locationData in the Android Archive (AAR) file I built from handtrackinggpu. In an Android Archive (AAR) file built from an older version (last year), I see there is an palm rect class like this:
![Screenshot from 2021-07-09 01-15-29](https://user-images.githubusercontent.com/23139990/125026747-3588d780-e053-11eb-9d65-c42ecdc5a11b.png)
I wonder where can I get this class to get palm rect data? Or should I build AAR in a specifc way in order to have both landmarks and rects?

**Comment by jiuqiant** [comment]
You can add rect proto into the aar rule by following https://github.com/google/mediapipe/issues/1624#issuecomment-782265180.
