### ISSUE TITLE
Android MIN_DETECTION_CONFIDENCE invalid

### ISSUE THREAD

**Issue by qichuangguo** [google/mediapipe#2272]
code: 
 Map<String, Packet> inputSidePackets = new HashMap<>();
        inputSidePackets.put(INPUT_NUM_HANDS_SIDE_PACKET_NAME, packetCreator.createInt32(NUM_HANDS));
        inputSidePackets.put("min_detection_confidence", packetCreator.createFloat32(0.9f));
 processor.setInputSidePackets(inputSidePackets);

This use does not work

**Comment by sgowroji** [comment]
Hi @qichuangguo, Could you please elaborate your use case and how do you verify the invalid. Thanks!

**Comment by qichuangguo** [comment]
I run mediapipe hands on Android device and set MIN_DETECTION_CONFIDENCE is 0.9, sometimes the face can be recognized with a confidence of 0.6

**Comment by sgowroji** [comment]
Could you please provide your code and graph changes on top of it. With a screenshot or video and device used for testing the above.
