### ISSUE TITLE
Is landmark position plot of face mesh available?

### ISSUE THREAD

**Issue by LiHuaigu** [google/mediapipe#2273]
I'm currently using MediaPipe to detect specific positions on faces(eyes, nose, mouth). That means I only need a few landmarks from the face mesh. However, I could not find the document indicate the id of each landmark. I was wondering if any document plots the id and position of each landmark on the face?

Thanks in advance.

**Comment by sgowroji** [comment]
Hi @LiHuaigu, Which platform are you referring the above. Thanks!

**Comment by LiHuaigu** [comment]
> Hi @LiHuaigu, Which platform are you referring the above. Thanks!

Thank you for your reply, sgowroji. I'm using the Android platform.

**Comment by sgowroji** [comment]
Check https://github.com/google/mediapipe/issues/1410 and  https://github.com/google/mediapipe/issues/1416
