### ISSUE TITLE
Is there a repository that shows the 3D pose that already exists?

### ISSUE THREAD

**Issue by connernam** [google/mediapipe#2274]
I want to implement 3D Pose on Python like Fig 5 on https://google.github.io/mediapipe/solutions/pose.

However, I would like to refer to a demo that has already been implemented. Please let me know if you have a repository or reference that can help.

**Comment by chuoling** [comment]
The MediaPipe Python Colab (https://colab.research.google.com/drive/1uCuA6We9T5r0WljspEHWPHXCT_2bMKUy) has an example that generates and visualizes world 3D pose landmarks.

**Comment by connernam** [comment]
@chuoling 
Thank you for your reply.
Colab's demo seems to cover only a single image.
What I want is 3d posture estimation in real time (on webcam).

**Comment by chuoling** [comment]
Have you tried using the code snippet in https://google.github.io/mediapipe/solutions/pose.html#python-solution-api under `# For webcam input`, and add the following for visualization the world 3D pose landmarks (like in the Colab with static images)?

```
mp_drawing.plot_landmarks(
        results.pose_world_landmarks, mp_pose.POSE_CONNECTIONS)
```

**Comment by connernam** [comment]
Yes, I tried the code snippet. 


The result is shown as a simple image plotted as shown below.
![image](https://user-images.githubusercontent.com/42915968/125231915-909e2100-e316-11eb-835a-50d1083b9380.png)
I want to implement a 3D plotter that moves the same as the input image in Python in real time like Fig 5.
![image](https://user-images.githubusercontent.com/42915968/125232320-57b27c00-e317-11eb-83af-3aa90635dc58.png)

Similar implementation examples can be seen in WebDemo, but no implementation examples or APIs can be found using Python.

If there were no examples and APIs, it would have to be implemented on its own, but if there were, it would have been easier to develop.

**Comment by Rassibassi** [comment]
Not exactly as in the picture, but check out my mediapipe demo repository. Almost all the solutions as python real-time applications applied on the webcam video signal.

https://github.com/Rassibassi/mediapipeDemos

**Comment by connernam** [comment]
@Rassibassi 
I will check your repo. Thank you for your reply.

**Comment by sn1c3** [comment]
@Rassibassi, your repo has some useful scripts, but a solution to the initial question is not provided, or am I missing something?

@connernam did you find something? I used for my visualizations [ipyvolume](https://ipyvolume.readthedocs.io/en/latest/#). It works quite good, but the repo is not maintained very actively.
