### ISSUE TITLE
404 for https://google.github.io/mediapipe/getting_started/install.md

### ISSUE THREAD

**Issue by sankarbha** [google/mediapipe#2276]
wanted to get started with mediapipe android solutions. Going through getting started and hello world setup in https://google.github.io/mediapipe/getting_started/hello_world_android.html and wanted to try step 1 of Setup and it landed in 404.

**Comment by djthegr8** [comment]
> wanted to get started with mediapipe android solutions. Going through getting started and hello world setup in https://google.github.io/mediapipe/getting_started/hello_world_android.html and wanted to try step 1 of Setup and it landed in 404.

the .md in the link is causing the 404, you can just go [here](https://google.github.io/mediapipe/getting_started/install)

**Comment by sgowroji** [comment]
Hi @sankarbha, Above error  is resolved, you can see the url working fine in the next release. We are closing this issue now. Thanks
