### ISSUE TITLE
Mediapipe Object Tracking GPU with custom TFLite Model

### ISSUE THREAD

**Issue by moezeus** [google/mediapipe#2286]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Linux Ubuntu 18.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): 
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): 
- Installed using virtualenv? pip? Conda? (if python): 
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.6
- Bazel version: latest (install using npm)
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android): (installed using bash setup_android_sdk_ndk
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:
I just want to modify the TFLite used on objecttrackinggpu (on example build) using my custom TFLite that has been built using this tutorial : https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#preparing-the-workspace 
i was using SSD_Mobilenet_V2 model on https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md, specifically on this model : http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz

Training and tflite generation process is run smoothly without problem, and i have implemented the model on Android using this template : https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android without problem.

but, when the custom tflite file is used to replace the default tflite model on mediapipe object detection, this error show (on android), and the camera wont open: 
'''
2021-07-13 17:38:36.500 8281-14914/? E/FrameProcessor: Mediapipe error: 
    com.google.mediapipe.framework.MediaPipeException: internal: Graph has errors: 
    Calculator::Open() for node "objectdetectionsubgraphgpu__TfLiteInferenceCalculator" failed: ; (interpreter_->ModifyGraphWithDelegate(delegate_.get()))==(kTfLiteOk)ulator.cc:977) 
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:395)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:458)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:364)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:309)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
'''

i've read some post on issues, and look at the answer here : https://github.com/google/mediapipe/issues/1235#issuecomment-729321698
the answer say that, the problem is caused by the tflite model, which cannot use GPU delegate. 
if my problem caused by the custom model cannot use GPU delegate, how can i check whether my model is support GPU or only CPU? try to workaround find the solution, but maybe im just stuck here. 

Thanks!

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
- i just edit the tflite and label_map part on object_tracking_gpu.pbtxt and BUILD file
- then just build the file using command:  bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu
- build process run without error and apk is succesfully generated

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by sgowroji** [comment]
Hi @moezeus, Seems duplicate of this https://github.com/google/mediapipe/issues/1731#issuecomment-844318727 can help you.

**Comment by moezeus** [comment]
Thanks for your repply, 
i have look at the thread, and doing some test using benchmark tools on android, especially using use_gpu flag, and get this output: 

---

command : 
```
adb shell am start -S -n org.tensorflow.lite.benchmark/.BenchmarkModelActivity --es args '"--graph=/data/local/tmp/(--model--).tflite"' 
```
1. from mediapipe model (ssdlite_object_detection.tflite) : 
output:
Average inference timings in us: Warmup: 68553.9, Init: 1157, Inference: 67842.9

2. from my custom generated model (model.tflite) : 
output:
Average inference timings in us: Warmup: 153474, Init: 1452, Inference: 151254

command : 
```
adb shell am start -S -n org.tensorflow.lite.benchmark/.BenchmarkModelActivity --es args '"--graph=/data/local/tmp/(--model--).tflite --use_gpu=true --num_threads=4"'
```
1. from mediapipe model (ssdlite_object_detection.tflite) : 
output:
Average inference timings in us: Warmup: 12263.4, Init: 1289260, Inference: 12419.3

2. from my custom generated model (model.tflite) : 
output:
Average inference timings in us: Warmup: 33980.4, Init: 877691, Inference: 32845.1

---
for now, i can see that, using gpu the process takes faster inference time, and looks like my model support the gpu delegate. is that correct? 
if so, is there any other parameter or suggestion that must be passed to the benchmark tools to make sure whats caused the error on opening mediapipe tflite calculator?

Thanks a lot,

**Comment by jianingwei** [comment]
Can you try adding "delegate { gpu {} }" to the options of TfLiteInferenceCalculator? If it still doesn't work, try adding "delegate { xnnpack {} }".

**Comment by gr4cza** [comment]
Hi @jianingwei, i am facing the same issue, what do you mean by adding "delegate { gpu {} }" ?

like this?
```node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS_GPU:image_tensor"
  output_stream: "TENSORS_GPU:detection_tensors"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
      model_path: "model-export_iod_tflite-test_model.tflite"
      delegate: { gpu {} }
    }
  }
} 
```

**Comment by ahmadyan** [comment]
Yes, delegate tells the inference calculator which backend to use. You can see [gpu example](https://github.com/google/mediapipe/blob/137e1cc7630524ea1c3a9b120985285fe43c8a3f/mediapipe/modules/objectron/box_landmark_gpu.pbtxt#L65) here and the [cpu version](https://github.com/google/mediapipe/blob/137e1cc7630524ea1c3a9b120985285fe43c8a3f/mediapipe/modules/objectron/box_landmark_cpu.pbtxt#L66) here.

**Comment by jianingwei** [comment]
So both "delegate { gpu {} }" and "delegate { xnnpack{} }" give you the same error?

**Comment by honggang0524** [comment]
I ran into the same problem,
Tried the two methods in the comments and added:delegate { gpu {} }”or“delegate { xnnpack{} },
Got the same wrong result

**Comment by 20gg** [comment]
open your  XX.pbtxt，and change num_boxes item；`    [type.googleapis.com/mediapipe.TfLiteTensorsToDetectionsCalculatorOptions] {
      num_classes: 2
      num_boxes: 1917
      num_coords: 4
      ignore_classes: 0
      sigmoid_score: true
      apply_exponential_on_box_size: true
      x_scale: 10.0
      y_scale: 10.0
      h_scale: 5.0
      w_scale: 5.0
      min_score_thresh: 0.6
    }`

**Comment by kuaashish** [comment]
Hello @moezeus,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
