### ISSUE TITLE
 face AR

### ISSUE THREAD

**Issue by NourOmran** [google/mediapipe#2287]
Hello, 
I want to use MediaPipe to integrate it with glasses or masks like this photo 
<img width="752" alt="Screenshot 2021-07-13 at 9 08 47 PM" src="https://user-images.githubusercontent.com/49115119/125511268-a06b1173-dacf-4c63-b8d9-7141d3af5a62.png">

How can I make this ? 

thanks

**Comment by sgowroji** [comment]
Hi @NourOmran, you should check this https://github.com/google/mediapipe/issues/1155
