### ISSUE TITLE
bazel build -c opt mediapipe/graphs/holistic_tracking:holistic_tracking_gpu_deps 

### ISSUE THREAD

**Issue by qichuangguo** [google/mediapipe#2289]
external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/BUILD:196:11: C++ compilation of rule '@org_tensorflow//tensorflow/lite/delegates/gpu/gl:gl_buffer' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 26 argument(s) skipped)

**Comment by sgowroji** [comment]
Hi @qichuangguo, Could you please provide complete steps to reproduce the above error. Thanks!
