### ISSUE TITLE
lots of issues during run the HelloWorld! on iOS

### ISSUE THREAD

**Issue by mstfabbstbr** [google/mediapipe#2293]
hey everyone
at first i installed mediapipe then installed python, after that installed all requirment tools such as tulsi, bazel, etc.

then i just follownig the instruction from: [HelloWorld! on iOS](https://google.github.io/mediapipe/getting_started/hello_world_ios.html#setup)
in the instruction, they said the project name should be "HelloWorld", i did it, but when i want to run the tulsi, it show me an error that it cannot find HelloWorld, and the project name must be "HelloWorldApp". i create a whole new project with name "HelloWorldApp".
after that, tulsi shows me an error that it cannot find BUILD document for something else, such as facedetectiongpu, facedetectioncpu and etc..
after that, in tulsi in the configs tab, i create a new config and just select the HelloWorldApp.. at the end, tulsi generated the xcode project. but it has lots of error.. the main and important error is xcode cannot find the library that we need to add.. and the other side, it cannot find some file that exist 😐 such as BUILD file, info.plist and etc...

this is the erros that xcode shows me:
<img width="529" alt="Screen Shot 1400-04-24 at 11 12 24" src="https://user-images.githubusercontent.com/54117642/125741165-c3304a8a-274a-4f9f-b547-ff2029daaf18.png">

this is the all files that tulsi generated and xcode shows me:
<img width="536" alt="Screen Shot 1400-04-24 at 11 14 24" src="https://user-images.githubusercontent.com/54117642/125741444-e9491dc5-ca2c-44a6-8da3-fae2a7dc220f.png">

**if somebody has worked with Mediapipe in iOS in real app, notice me please.**

**Comment by sgowroji** [comment]
Hi @mstfabbstbr, Could you please provide steps to reproduce the above error. Thanks!

**Comment by mstfabbstbr** [comment]
Hi @sgowroji,
I just followed everything in the documentation in that linked above 👆🏼
But, when i want to generate the mediapipe project (which said in the documentation), tulsi shows me an error that cannot find BUILD file for facedetectiongpu, facedetectioncpu, and etc.
So that’s why i choose another config in configs tab.. then i customized it for just select HelloWorldApp (which i want to generate) and generated complete.. after that the xcode, shows me this project and when i build project, and bomb, these errors…

**Comment by mstfabbstbr** [comment]
@sgowroji can't you help me for this?

**Comment by sgowroji** [comment]
Assigned owners who can guide you on the above.

**Comment by mstfabbstbr** [comment]
there is no answer??!!??

**Comment by mstfabbstbr** [comment]
i solved some of my problem by using bazel.. and now i realized that the tulsi has some problem.. it doesn't find the python_build_path..

i have installed numpy in python3 and python2..

**Comment by mstfabbstbr** [comment]
### SOLVED
i solved the my problem by checking these:

- XCode version must be 12.4
- reinstall MediaPipe
- reinstall python, and python version must be 3 and above
- reinstall tulsi
- generate the project by tulsi, and check the bundle id in `link_local_profiles.py` file by using this command line: `python3 mediapipe/examples/ios/link_local_profiles.py`

that's all, problem solved.
