### ISSUE TITLE
Can't instantiate binary graph for face_geometry_from_landmarks and face_geometry_from_detection

### ISSUE THREAD

**Issue by RafaelMiquelino** [google/mediapipe#2294]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): macOS Big Sur 11.4
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): 12
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.7
- Installed using virtualenv? pip? Conda? (if python): virtualenv
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.6
- Bazel version: 3.7.2
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): 3

**Describe the problem**:

I compiled `face_geometry_from_landmarks` and `face_geometry_from_detection` to get the binary graphs and call it from python with the `mp.CalculatorGraph` but I can't make it work. I always get the following errors:

For `face_geometry_from_landmarks.binarypb`:  
```
RuntimeError: ValidatedGraphConfig Initialization failed.
No registered object with name: FaceGeometryPipelineCalculator; Unable to find Calculator "FaceGeometryPipelineCalculator"
```

For `face_geometry_from_detection`:
```
RuntimeError: ValidatedGraphConfig Initialization failed.
No registered object with name: DetectionToLandmarksCalculator; Unable to find Calculator "DetectionToLandmarksCalculator"
No registered object with name: FaceGeometryPipelineCalculator; Unable to find Calculator "FaceGeometryPipelineCalculator"
```

I checked the dependencies on the `mediapipe/modules/face_geometry/BUILD` file and they seem to be there so I don't understand what is going wrong:

```
mediapipe_simple_subgraph(
    name = "face_geometry_from_detection",
    graph = "face_geometry_from_detection.pbtxt",
    register_as = "FaceGeometryFromDetection",
    deps = [
        ":geometry_pipeline_calculator",
        "//mediapipe/calculators/core:begin_loop_calculator",
        "//mediapipe/calculators/core:end_loop_calculator",
        "//mediapipe/calculators/util:detection_to_landmarks_calculator",
    ],
)

mediapipe_simple_subgraph(
    name = "face_geometry_from_landmarks",
    graph = "face_geometry_from_landmarks.pbtxt",
    register_as = "FaceGeometryFromLandmarks",
    deps = [
        ":geometry_pipeline_calculator",
    ],
)
```

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

Graphs compilation:  
- `bazel build mediapipe/modules/face_geometry:face_geometry_from_detection`
- `bazel build mediapipe/modules/face_geometry:face_geometry_from_landmarks`

Copied the binary graphs to the library resources inside the virtual env site-packages and tried to call that from Python:
```python
import mediapipe as mp

graph = mp.CalculatorGraph(
    binary_graph_path='/***/.virtualenvs/mediapipe/lib/python3.7/site-packages/mediapipe/modules/face_geometry/face_geometry_from_detection.binarypb')

graph = mp.CalculatorGraph(
    binary_graph_path='/***/.virtualenvs/mediapipe/lib/python3.7/site-packages/mediapipe/modules/face_geometry/face_geometry_from_landmarks.binarypb')
```

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/1578

**Comment by RafaelMiquelino** [comment]
Indeed. The related solution worked. Thanks!
