### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by gyuhui** [google/mediapipe#2295]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):
- Programming Language and version ( e.g. C++, Python, Java):

**Describe the expected behavior:**

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

I got an "Attributerror : can't set attribute"

Help me.
<img width="1035" alt="스크린샷 2021-07-16 오후 5 10 40" src="https://user-images.githubusercontent.com/74871921/125915001-7bf669fc-0588-47ae-a28f-13ab6bef9cec.png">

**Comment by sgowroji** [comment]
Hi @gyuhui, Could you please point out which colab you used from [here](https://google.github.io/mediapipe/solutions/pose) with your code changes on top of it.  And also share your use case for those code changes. Thanks!
