### ISSUE TITLE
Accessing hand landmarks on Android

### ISSUE THREAD

**Issue by aaaldo** [google/mediapipe#230]
Hello everyone,

I'm planning to use Mediapipe for a Hand control UI prototype on Android. So far, i'm taking inspiration on the advised method for desktop, discussed in this issue ([#200](https://github.com/google/mediapipe/issues/200)).

As a pure Android dev', seeing the time and effort needed to add some basic C++ code conversion for JNI makes me thinkg that it would be a real timesaver for Android dev' to have more native format converters  - Landmark, Detections, Location,etc - directly available in the PacketGetter java class. 

Can any of those been added on later release ?

**Comment by mgyong** [comment]
@aaaldo - Yes we are looking to add this shortly in an incoming release.
@eknight7 - FYI

**Comment by Sara533** [comment]
@mgyong 
Is there a plan to release a C++ version base on visual studio?
Or make it available for visual studio by a lib or other methods.
As a pure C++ dev', it is also a problem to use Android projects.

**Comment by eknight7** [comment]
Are you asking about how to access landmarks on C++ side @Sara533 ?

**Comment by Sara533** [comment]
@eknight7 
I can access landmarks on C++ side. But that is base on bazel build.
I wonder if it is possible to build a lib or dll that can use in visual studio C++ project, just like build an aar for android studio project.
It is difficult to debug via bazel.

**Comment by HebaMohamed** [comment]
@Sara533 Can you please illustrate more about accessing landmarks from c++ to android java? Im stuck with that for a long time

**Comment by Sara533** [comment]
@HebaMohamed 
Sorry, I have not got landmarks value from c++ to android java.
But via v0.6.3, you can use an aar lib in android studio project follow the instructions.
https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md
I hope that can help you.

**Comment by mgyong** [comment]
@HebaMohamed @Sara533 @aaaldo Fixed in [v0.6.6](https://github.com/google/mediapipe/releases/tag/v0.6.6) Pls check it out and let us know

**Comment by gongchunye** [comment]
@eknight7 How can I access landmarks on C++ in the demo_run_graph_main.cc?
Thank you very much!
