### ISSUE TITLE
CMake ??

### ISSUE THREAD

**Issue by dibet** [google/mediapipe#2300]
Can you have any way to generate one library and include files to use with cmake
Thanks

**Comment by sgowroji** [comment]
Hi @dibet, Could you please elaborate your use case with complete details. And mention the MediaPipe usability from the above request.

**Comment by dibet** [comment]
Hi, i would like to use mediapipe with cmake.
Any possibility to include a CMakeLists in the project?

**Comment by sgowroji** [comment]
Hi @dibet, Please have a look at this comment for the implementation https://github.com/google/mediapipe/issues/1162#issuecomment-897196714

**Comment by rajhlinux** [comment]
Yes, I also have same question as to OP, does media pipe have a way to be installed using CMake rather than bazel.

**Comment by zihaomu** [comment]
Hi @dibet @rajhlinux. I met the same issue. And I try to reproduce it to a project: [mediapipe_cmake](https://github.com/zihaomu/mediapipe_cmake). It's still under development.
