### ISSUE TITLE
 "onFrame"  may stop working  without throwing any exception In Mediapipe web api 

### ISSUE THREAD

**Issue by senshin998** [google/mediapipe#2301]
the function   "onFrame"  in"node_modules\@mediapipe\camera_utils\camera_utils.js"  may stop working  without throwing any exception after the program has been running for a while

         cameraPose = new Camera(videoElement, {
                onFrame: async () => {
     // may stop  
}
This is a frequently occurring bug, and it is worth paying attention to
version :  @mediapipe/pose 0.4.1624666670
 os:    windows10
blower: chrome
directX:12
card: gtx1080ti

**Comment by sgowroji** [comment]
Hi @senshin998, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by senshin998** [comment]
thanks for your Reply，sorry I can't ，it Appear  randomly  and  exception in  chrome console

**Comment by sgowroji** [comment]
Hi @senshin998, We can't debug, or troubleshoot the issue without any logs or video or screenshot of the error. I would request to reopen the issue once you find the error  logs and share it.
