### ISSUE TITLE
FaceEffectGpu has our prefix, but does not seem to match any of our examples

### ISSUE THREAD

**Issue by mstfabbstbr** [google/mediapipe#2303]
Hey there,

I'm using Mediapipe on iOS, and when i want to generate provisioning profiles for faceEffectApp, terminal shows me an error. I searched for it and i found that the app name and the name in the example list are different.

This the list of the name of all examples in Mediapipe.

<img width="888" alt="Screen Shot 1400-04-27 at 15 18 20" src="https://user-images.githubusercontent.com/54117642/126064452-a85be825-073a-40f7-a90c-b4a089aec8d6.png">

As you see in this pic, the faceEffectApp name is faceeffect.
but when i want to `python3 mediapipe/examples/ios/link_local_profiles.py` in terminal, shows me an error that it cannot find the exact name.

<img width="1195" alt="Screen Shot 1400-04-27 at 15 18 56" src="https://user-images.githubusercontent.com/54117642/126064508-3e6118eb-6465-445b-b1fd-c081f919effc.png">

**Comment by sgowroji** [comment]
Hi @mstfabbstbr, Could you please provide the steps to reproduce the above error and also point us to the github changes.

**Comment by mstfabbstbr** [comment]
i just following the [MediaPipe on iOS](https://google.github.io/mediapipe/getting_started/ios.html#custom-provisioning) to run a one of examples. which name is FaceEffect.
When i want to `python3 mediapipe/examples/ios/link_local_profiles.py` in terminal, the error shows me.
i found out the name in the `example_name` in the `link_local_profiles.py` is different with the `app_dir_name`.

### You have to change faceeffectgpu to faceeffect. which is in the example names list.

**Comment by mstfabbstbr** [comment]
### SOLVED

I solved my problem with these steps:

- first reinstall mediapipe (this step is for who changed the mediapipe libraries or examples)
- delete the generated xcode project (this step is for who has generate the mediapipe project with tulsi)
- open tulsi, generate the mediapipe project as you know [Here](https://google.github.io/mediapipe/getting_started/ios.html#create-an-xcode-project).
- then in tulsi, in the configs tab, select mediapipe, the in the middle of the tulsi window, after **+** and **-**, select **•••** and uncheck all, then select these:

> util

> FaceEffectApp

> FaceEffectAppLibrary

> FaceEffectViewController

> MPPGraphTestBase

> mediapipe_framework_ios

> mediapipe_gl_view_renderer

> mediapipe_input_sources_ios

- after that, click **_Next_**, then **_Next_** again, then **_Save_**
- and push **_Generate_** button, and select the folder that you want to save the _Mediapipe.xcodeproj_, then push **_Generate_** button to save that.
- xcode will open the project automatically, just set the for **_custom provisioning_** follow [This](https://google.github.io/mediapipe/getting_started/ios.html#custom-provisioning), and for **_automatic provisioning_** follow [This](https://google.github.io/mediapipe/getting_started/ios.html#automatic-provisioning)

and problem solved.
