### ISSUE TITLE
How to get Detected co-ordinates in java android?

### ISSUE THREAD

**Issue by Pawandeep-prog** [google/mediapipe#2305]
- Have I written custom code  - No
- Solution - Face Detection
- Programming Language- java

**I want to get the Detected co-ordinates instead of output frame.**
When we run FaceDetection , the FrameProcessor basically returns the processed Frame but what I want is to get the vector of detections which should contains the <start_x, start_y, h, w> I mean co-ordinates of rectangle.
Any Help will be really Appreciated.
Thanks in advance.

**Comment by sgowroji** [comment]
Hi @Pawandeep-prog, you can try this https://github.com/google/mediapipe/issues/2296#issuecomment-882234266

**Comment by Pawandeep-prog** [comment]
> Hi @Pawandeep-prog, you can try this [#2296 (comment)](https://github.com/google/mediapipe/issues/2296#issuecomment-882234266)

Thanks a lot for your quick support. I actually found out the solution and it was not difficult at all.

```
processor.addPacketCallback(
      OUTPUT_STREAM_NAME,
      (packet) -> {
        List output_list = PacketGetter.getProtoVector(packet, NormalizedLandmarkList.parser());
        tv.setText("got packet SUCCESS ! " + output_list.size());
      }
    );
```

by using above code I was able to solve that. Where OUTPUT_STREAM_NAME is the graph output such as face_detections.
and for using **NormalizedLandmarkList** you would have to add dependency :

`"//mediapipe/framework/formats:landmark_java_proto_lite",`

That's all to access values.
_If anyone reading this comment need any further help you may contact me with profile links._
THANKS.
