### ISSUE TITLE
hand_tracking: ERROR: unknown command line flag 'input_side_packet'

### ISSUE THREAD

**Issue by wyuzyf** [google/mediapipe#231]
i using : GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu \
--calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop.pbtxt \
--input_side_packet=input_video_path=/path/hand.mp4,output_video_path=path/output.mp4

please help me ,thank you ~

**Comment by mgyong** [comment]
You should use 
bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt --input_video_path=/Users/mgyong/Downloads/input.mp4 --output_video_path=/Users/mgyong/Downloads/output.mp4

Use the original ``mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt ``

**Comment by wyuzyf** [comment]
thanks for your answer,but there has another error.
like: OpenCV | GStreamer warning: your GStreamer installation is missing a required plugin

can you help me ,thank you ~
