### ISSUE TITLE
channel error when using bilateral_filter_calculator

### ISSUE THREAD

**Issue by carter54** [google/mediapipe#2310]
Hi there,

I tried to add the bilateral filter in my segmentation task. Following channel number error raise:
```
"CPU filtering supports only 1 or 3 channel input images."
```
I checked my input channel is 1 (output from selfie segmentation task)...

Then I found this line in bilateral_filter_calculator.cc
https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/calculators/image/bilateral_filter_calculator.cc#L243
It seems like a "!“ is missing in the code.

**Comment by mcclanahoochie** [comment]
Hi,
Thanks for bringing this to our attention. This is indeed a bug, and has now been fixed upstream. The next release of MediaPipe should contain the update. 
Cheers

**Comment by sgowroji** [comment]
Hi @carter54, From the above [comment](https://github.com/google/mediapipe/issues/2310#issuecomment-882964648) we are closing this issue as of now and I would request you to test the above once the new release roll out. Reach us back if you still face the same.
