### ISSUE TITLE
Getting  hand landmarks without rendering data to the screen.?

### ISSUE THREAD

**Issue by shreyas0906** [google/mediapipe#2311]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using):
- Programming language : C++/typescript/Python/Objective C/Android Java
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state:**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Please specify the use cases for this feature:**

**Any Other info:**
https://github.com/google/mediapipe/issues/348

**Comment by sgowroji** [comment]
For Hand landmarks https://github.com/google/mediapipe/issues/2092.

**Comment by Kiru3014** [comment]
Hi @sgowroji, I am looking for output with the below points

1) I'm able to run the media pipe on android and get the landmarks, however, I'd like to see the output without the SurfaceView.
2) I just want the landmarks(in like a List<>) without any rendering on to the screen.

In 1st Point, if I disable frame layout rendering from the screen from XML i'm not able to deduct any hand points on

**Comment by shreyas0906** [comment]
![mdp-1](https://user-images.githubusercontent.com/3739313/126272249-9a562131-ae52-4b32-8f44-35f3c065b29e.png)
![Screenshot_20210720-115434](https://user-images.githubusercontent.com/3739313/126272573-bebf4ca1-afbf-480b-9a86-1cb1b866fcfa.png)

When I run the MainAcitvity.java as is.. I'm able to get the landmarks without any problem in a List<> format. 

But when i comment the the preview (line 218 - 219), I;m not able to get any landmarks. 

![mdp-2](https://user-images.githubusercontent.com/3739313/126272424-58fdf26e-0771-4995-a284-9ba3cba1b0a1.png)
![Screenshot_20210720-115406](https://user-images.githubusercontent.com/3739313/126272593-641733c8-3c40-4d3c-8d03-3dc649947bd2.png)


I just need the handlandmarks without rendering them onto the screen.

Please help.

Thanks

**Comment by Kiru3014** [comment]
Hi @camillol any update on this

**Comment by Kiru3014** [comment]
@sgowroji Please help to resolve this issue?

**Comment by Kiru3014** [comment]
@sgowroji can u help to get any update on this I try all solution available on internet its not working

**Comment by sgowroji** [comment]
Hi @Kiru3014, Did you get a chance to check this https://github.com/google/mediapipe/issues/348#issuecomment-585614495

**Comment by Kiru3014** [comment]
Hi @sgowroji I check this #348 (comment) and try to change it according to that suggestion 
But Then no hands are deducted, if and only if the graph is there on the android activity then only I am able to get landmarks and process to do gestures action.

https://mediapipe.readthedocs.io/en/latest/hello_world_android.html#externaltextureconverter-setup
this ref link not working

**Comment by sgowroji** [comment]
Assigning to @eknight7, As you guided the similar issue on #348. Feel free to reassign if you are not the right owner for the above issue. Thanks!

**Comment by Monibsediqi** [comment]
Any update on this issue? In fact, I'm in a similar situation. I need to get the landmark value of the face without actually rendering the output of the graph (i.e., image with the face-landmark on it) on the screen.

**Comment by Kiru3014** [comment]
@Monibsediqi  so still we are looking at this not got any update

**Comment by sgowroji** [comment]
Hi @Monibsediqi,  You can try the landmarks in facemesh with our latest gradle android solutions from [here](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/solutions/facemesh/src/main/java/com/google/mediapipe/examples/facemesh/MainActivity.java#:~:text=NormalizedLandmark%20noseLandmark%20%3D%20result,noseLandmark) .

**Comment by Kiru3014** [comment]
@sgowroji any update without surface render to get handland markd

**Comment by sgowroji** [comment]
Hi @Kiru3014, Am not sure that will work without rendering on the camera screen. That's more how we try to implement in java code. @jiuqiant is it possible to show landmarks without rendering the screen?

**Comment by jiuqiant** [comment]
FaceMesh solution API outputs landmark protos directly. If the clients need to do custom rendering, it can be done in Java without MediaPipe by either an Android Canvas or OpenGL rendering. 

If you just need the landmarks, please write`setResultListener` like the following:
```java
facemesh.setResultListener(
    faceMeshResult -> {
       NormalizedLandmark noseLandmark = result.multiFaceLandmarks().get(0).getLandmarkList().get(1);
       // More landmark processing code.
    });
```

Please read more at https://google.github.io/mediapipe/solutions/face_mesh#android-solution-api.

**Comment by jiuqiant** [comment]
FaceMesh solution API outputs landmark protos directly. If the clients need to do custom rendering, it can be done in Java without MediaPipe by either an Android Canvas or OpenGL rendering. 

If you just need the landmarks, please add a `setResultListener` like the following:
```java
facemesh.setResultListener(
    faceMeshResult -> {
       NormalizedLandmark noseLandmark = faceMeshResult.multiFaceLandmarks().get(0).getLandmarkList().get(1);
       // More landmark processing code.
    });
```

**Comment by Monibsediqi** [comment]
@jiuqiant Thank you for the answer. In fact, I'm working with the iris solution of the mediapipe for android. Is there any similar solution for the iris API in android?
