### ISSUE TITLE
Feasibility of Objectron support on iOS

### ISSUE THREAD

**Issue by z7212819** [google/mediapipe#2316]
Hello, at present, my Objectron Android project has basically completed the required functions, but we need to use this function on the iOS side, so is there any way to provide the use scheme of Objectron on the iOS side, or to port the completed Android Studio project to the iOS side? Because I found that the most important part of Android project is the use of AAR package, but the iOS terminal does not have such function, so the iOS terminal cannot use this function. I would like to ask if you have any way to solve this problem, thank you.

**Comment by atursug** [comment]
Is there any planned roadmap for IOS support ?

**Comment by janeSmith99221** [comment]
> Hello, at present, my Objectron Android project has basically completed the required functions, but we need to use this function on the iOS side, so is there any way to provide the use scheme of Objectron on the iOS side, or to port the completed Android Studio project to the iOS side? Because I found that the most important part of Android project is the use of AAR package, but the iOS terminal does not have such function, so the iOS terminal cannot use this function. I would like to ask if you have any way to solve this problem, thank you.

I'm working on same. but I don't have any idea regarding this. if you have any ref regarding this, pls share.

**Comment by sureshdagooglecom** [comment]
Hi @z7212819 ,
This is issue can be resolved in the latest version of MediaPipe , could you please check and close this issue.
