### ISSUE TITLE
Also, I realize that some users launch the python runtime under the mediapipe repo, which might cause this issue.

### ISSUE THREAD

**Issue by Zeller-zf** [google/mediapipe#2318]
Traceback (most recent call last):
  File "/home/pi/Desktop/hands.py", line 2, in <module>
    import mediapipe as mp
  File "/usr/local/lib/python3.7/dist-packages/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/usr/local/lib/python3.7/dist-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

**Comment by Zeller-zf** [comment]
> Right, that's because the mediapipe repo has **init**.py files and the python interpreter reads them if you are launching the interpreter in the repo directory and the interpreter is confused by where the "_framework_bindings" dynamic library is.

how to slove this?

**Comment by jiuqiant** [comment]
You can leave the mediapipe repo and retry it in another directory such as the home directory. 
If you still get problem, please provide your system info and all the steps to reproduce this issue.

**Comment by Zeller-zf** [comment]
> You can leave the mediapipe repo and retry it in another directory such as the home directory.
> If you still get problem, please provide your system info and all the steps to reproduce this issue.

Thank you very much, I will try it later.
