### ISSUE TITLE
The number of detected hands is greater than max_num_hands

### ISSUE THREAD

**Issue by realfolkcode** [google/mediapipe#2319]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
- Programming Language and version ( e.g. C++, Python, Java): Python 3.7
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.6
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ): Hands
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
- Xcode & Tulsi version (if issue is related to building for iOS):

**Describe the current behavior:**
len(multi_hand_landmarks) can be sometimes equal to 3 even if max_num_hands is set 2.  So basically there are more hands being detected than it is expected.

**Describe the expected behavior:**
The number of the tracked hands should be less or equal than max_num_hands parameter.

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:
```python
import cv2
import mediapipe as mp
import numpy as np
import time


class HandDetector():
    def __init__(self, window_shape):
        self.mpHands = mp.solutions.hands
        self.hands = self.mpHands.Hands(max_num_hands=2)
        self.mpDraw = mp.solutions.drawing_utils
        self.center = {"pitch": (0, 0),
                       "dynamics": (0, 0)}
        self.height = window_shape[0]
        self.width = window_shape[1]

    def find_hands(self, img, draw=True):
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        imgRGB.flags.writeable = False
        self.results = self.hands.process(imgRGB)
        imgRGB.flags.writeable = True

        h, w, c = img.shape
        self.height, self.width = h, w

        center = [self.center["pitch"], self.center["dynamics"]]
        i = 0
        if self.results.multi_hand_landmarks:
            print(len(self.results.multi_hand_landmarks))
            for hand_lms in self.results.multi_hand_landmarks:
                center[i] = self.get_center(img, hand_lms)
                i += 1

        if center[0][0] > center[1][0]:
            center[0], center[1] = center[1], center[0]
        self.center["pitch"] = center[0]
        self.center["dynamics"] = center[1]

        if draw:
            cv2.circle(img, (self.center["pitch"][0],
                             self.center["pitch"][1]),
                       radius=20,
                       color=(0, 0, 255),
                       thickness=cv2.FILLED)
            cv2.circle(img, (self.center["dynamics"][0],
                             self.center["dynamics"][1]),
                       radius=20,
                       color=(255, 0, 0),
                       thickness=cv2.FILLED)
        return img

    def find_position(self, img, hand_lms):
        lm_list = []
        h, w, c = img.shape
        for id, lm in enumerate(hand_lms.landmark):
            cx, cy = lm.x * w, lm.y * h
            lm_list.append([cx, cy])
        return np.array(lm_list)

    def get_center(self, img, hand_lms):
        lm_list = self.find_position(img, hand_lms)
        if len(lm_list) > 0:
            center = np.mean(lm_list, axis=0)
        return (int(center[0]), int(center[1]))

pTime = 0
cTime = 0
cap = cv2.VideoCapture(0)
success, img = cap.read()
h, w, c = img.shape
detector = HandDetector(window_shape=(h, w))
cap = cv2.VideoCapture(0)

while True:
    success, img = cap.read()
    img = cv2.flip(img, 1)
    h, w, c = img.shape

    detector.find_hands(img, draw=True)

    cTime = time.time()
    fps = 1 / (cTime - pTime)
    pTime = cTime

    cv2.putText(img, str(int(fps)), (10, 70), cv2.FONT_ITALIC, 3, (255, 255, 0), 3)

    cv2.imshow("Image", img)

    if cv2.waitKey(5) & 0xFF == 27:
        break

cap.release()
```

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached
```
Traceback (most recent call last):
  File "D:/soundtest/test.py", line 79, in <module>
    detector.find_hands(img, draw=True)
  File "D:/soundtest/test.py", line 31, in find_hands
    center[i] = self.get_center(img, hand_lms)
IndexError: list assignment index out of range
```
Additionally, I provide a video (my captured screen) where this bug occurs: https://youtu.be/6AIPKLwb2ic
I printed the length of multi_hand_landmarks list (shown on my console in this video). It is clear, based on the output, that len(multi_hand_landmarks) is sometimes = 3 which contradicts the value 2 of max_num_hands parameter.

**Comment by sgowroji** [comment]
Hi @realfolkcode, May be you code  should append the values in your **get_center** function. It is raised when you try to assign an item to an index position that does not exist.

**Comment by realfolkcode** [comment]
> Hi @realfolkcode, May be you code should append the values in your **get_center** function. It is raised when you try to assign an item to an index position that does not exist.

Hi. Yes but what about len(multi_hand_landmarks) being equal to 3?

**Comment by simue** [comment]
+1
any updates yet?

**Comment by quadrathirsch** [comment]
+2 
Hi, I made the same experience... any updates?

**Comment by Shubham77saini** [comment]
Hello sir,  Can I take this issue

**Comment by sgowroji** [comment]
Hi @realfolkcode and all, Can you try the above with latest release https://google.github.io/mediapipe/solutions/hands.html#python-solution-api. Unable to reproduce in the latest version

**Comment by amayuelas** [comment]
I found the same issue, even if you set the max_num_hands=1, it keeps returning 2 hands. 
Is there anyway to force mediapipe to return just 1?
