### ISSUE TITLE
AAR example build takes too much time

### ISSUE THREAD

**Issue by Enmin** [google/mediapipe#2325]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:
I want to build an AAR example with hand landmarks and palm detection. I follow the steps in the documentation to build the AAR file. But it takes me more than 24 hours to build. Why it takes so long?

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by rrrfffrrr** [comment]
For me, It takes almost 30 minutes to build AAR in docker with Ryzen 3700X.

**Comment by Enmin** [comment]
Wow, which aar did you build? I built handdetection and handtracking. During compiling, it shows I need to compile around 7k files. My laptop was Lenovo legion r7000.

**Comment by rrrfffrrr** [comment]
I just following the document [android_archive_library](https://google.github.io/mediapipe/getting_started/android_archive_library.html) but change face_detection to hand_tracking.

**Comment by junnikokuki** [comment]
More than 10 hours too. I use docker with no limit, I9-9900K, 16G with 2080Ti.

**Comment by sgowroji** [comment]
Hi @Enmin, Have you encountered any error while building the AAR. Please share if there are any.

**Comment by Enmin** [comment]
I have not encounter any error but some warnings. My ndk version is r19c.

**Comment by sgowroji** [comment]
We are not sure what could be the problem unless if there are any error logs you encounter while building the AAR. By the way there are only two steps for doing this as stated in our [documentation](https://google.github.io/mediapipe/getting_started/android_archive_library.html#steps-to-build-a-mediapipe-aar). Let us kow if there are any addons or code changes on top of it.
