### ISSUE TITLE
Android AAR built with MEDIAPIPE_DISABLE_OPENCV ON running failed

### ISSUE THREAD

**Issue by junnikokuki** [google/mediapipe#2326]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:

I use this cmd to build face mesh android AAR:
bazel build -c opt --define MEDIAPIPE_DISABLE_OPENCV=1 --strip=ALWAYS --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a --linkopt="-s" //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar:mediapipe_face_mesh.aar

The compile process succeed and there is no opencv3 library inside the AAR. Then I use the AAR in an example project but it report libopencv3.so not found when I dlopen the libmediapipe_jni.so.

**Comment by sgowroji** [comment]
Hi @junnikokuki, Could you please provide the logs to understand the issue much better. Thanks!

**Comment by junnikokuki** [comment]
> Hi @junnikokuki, Could you please provide the logs to understand the issue much better. Thanks!

There is no log, sorry, but this is because the libmediapipe_jni.so is still linking with libopencv3.so even though MEDIAPIPE_DISABLE_OPENCV is set to 1. Maybe the MEDIAPIPE_DISABLE_OPENCV is not fully support the face mesh, lacking document.

**Comment by sgowroji** [comment]
Hi @junnikokuki, Could you please point us the documentation of the command you are trying and let us know your use case with disabling the opencv?

**Comment by jiuqiant** [comment]
This is for a new flag for reducing the package size when only gpu graphs are needed. We don't document this because it's currently for internal use.

**Comment by junnikokuki** [comment]
> This is for a new flag for reducing the package size when only gpu graphs are needed. We don't document this because it's currently for internal use.

OKey, when will this flag go public? Or any flag that can link the opencv static?

**Comment by jiuqiant** [comment]
> > This is for a new flag for reducing the package size when only gpu graphs are needed. We don't document this because it's currently for internal use.
> 
> OKey, when will this flag go public? Or any flag that can link the opencv static?

We plan to remove the opencv dependency. So, optimizing the way to link opencv is not on the roadmap.
