### ISSUE TITLE
Mediapipe Hand tracking is not working on Android Chrome 91 & 92

### ISSUE THREAD

**Issue by veetechh** [google/mediapipe#2328]
The hand tracking is not detecting hand on android chrome 91 version, it gives random points as shown in the screenshot below.

![processed](https://user-images.githubusercontent.com/19422397/126489589-0b248e7c-a807-4eb4-bfa2-ee2f151c2308.jpeg)

**Comment by sgowroji** [comment]
Hi @veetechh, Could you please share your code  and graph changes, if there are any. Thanks!

**Comment by veetechh** [comment]
I followed this example.

https://codepen.io/mediapipe/pen/RwGWYJw

**Comment by veetechh** [comment]
@sgowroji any solution for this?

Would be great if there is a working hand tracking web demo.

**Comment by veetechh** [comment]
https://codepen.io/mediapipe/pen/RwGWYJw

![WhatsApp Image 2021-07-24 at 16 03 28](https://user-images.githubusercontent.com/19422397/126865956-d7fd52c1-32da-48c2-a8dc-204f0ff8b303.jpeg)

**Comment by mhays-google** [comment]
Can you try a photo with your hand in frame?  The image does not actually look like a hand.  Try increasing the confidence slider -- by default it's sitting at 0.5, which may not be high enough for your needs.

**Comment by veetechh** [comment]
Ok, the problem occurs at random times. Not all the times. In the video below, points shown randomly even when hand is not visible. I will try increasing the detection confidence. 

https://user-images.githubusercontent.com/19422397/127032045-1df20c6f-d1f2-4ca4-affd-08ae71d3f861.mp4

**Comment by sgowroji** [comment]
This https://github.com/google/mediapipe/issues/2328#issuecomment-886829848 addresses your query. We are closing this issue now. Please reach us if you still have any relevant update in the above context.

**Comment by veetechh** [comment]
I still face this issue on android mobile even after setting confidence value to 0.75.

**Comment by mhays-google** [comment]
A 75% confidence is not great.  Try 99%.  But even still, the quality of a neural network is attributed in no small part to the training data that was used to make it.  The team continues to improve and refine their models, so hopefully the performance doesn't get worse with each new version.

**Comment by veetechh** [comment]
It doesn't detect hand on mobile if I keep 0.9 confidence.

**Comment by veetechh** [comment]
This issue still exists on android, may I know when will this get resolved?

**Comment by veetechh** [comment]
@mhays-google may I know if there is any solution for this issue on android?

**Comment by veetechh** [comment]
Hi, the issue is solved in new version js files. Thanks!

**Comment by sgowroji** [comment]
Thank you for verifying the above  confirming the fix.
