### ISSUE TITLE
About using another camera

### ISSUE THREAD

**Issue by lxz1104** [google/mediapipe#233]
Hi! Thanks for sharing this code.
I want to use another camera such as a camera connect by  Type-C,and I want to use this camera to get frames.
I don't know how to use it by this code.Can you give me some suggestion?

**Comment by eknight7** [comment]
Which platform do you want to use the different camera from? And are you asking about switching to another camera, or using more than one camera?

**Comment by lxz1104** [comment]
I want to use the realsence depth camera.I use the SDK called  [**librealsense**](https://github.com/IntelRealSense/librealsense). 
I only want to switch to another camera.

**Comment by lxz1104** [comment]
@eknight7

**Comment by eknight7** [comment]
You could have a look at https://github.com/IntelRealSense/librealsense/tree/master/examples for example source code of how to read frames from that camera.

**Comment by lxz1104** [comment]
Thanks
