### ISSUE TITLE
Error creating uuu file using ObjParser

### ISSUE THREAD

**Issue by miftahulbagusp** [google/mediapipe#2331]
I'm trying to create a uuu file in objectron (object_detection_3d) using ObjParser. I tried to follow the documentation by writing the command:

`bazel run -c opt mediapipe/graphs/object_detection_3d/obj_parser:ObjParser -- input_dir=[INTERMEDIATE_OUTPUT_DIR] output_dir=[OUTPUT_DIR]`

But I get an error:
`Error: Must provide input directory with --input_dir=`

And if I change the command to something like this (removing the space between -- and input_dir=),

`bazel run -c opt mediapipe/graphs/object_detection_3d/obj_parser:ObjParser --input_dir=[INTERMEDIATE_OUTPUT_DIR] output_dir=[OUTPUT_DIR]`

I get an error message like this:
`ERROR: --input_dir=/Users/bagus/mediapipe/output :: Unrecognized option: --input_dir=/Users/bagus/mediapipe/output
`

**Comment by sgowroji** [comment]
Hi @miftahulbagusp, Have you followed the steps mentioned over [here](https://google.github.io/mediapipe/solutions/objectron.html#assets)

**Comment by miftahulbagusp** [comment]
> here

Yes, I followed the documentation that was there.

**Comment by miftahulbagusp** [comment]
I tried to build from Java successfully, only error when build from bazel.

**Comment by Suraj520** [comment]
> I tried to build from Java successfully, only error when build from bazel.
@miftahulbagusp 
Can you list the command used for building directly via Java.

**Comment by miftahulbagusp** [comment]
> > I tried to build from Java successfully, only error when build from bazel.
> > @miftahulbagusp
> > Can you list the command used for building directly via Java.

`javac ObjParserMain.java`
`java ObjParserMain --input_dir=[INTERMEDIATE_OUTPUT_DIR] --output_dir=[OUTPUT_DIR]`

**Comment by ahmadyan** [comment]
If you use bazel run, which compiles then runs the app, you can pass the flags to the actual binary (not bazel) with --. 
So it would look like bazel run <app> -- --input_dir=...

**Comment by miftahulbagusp** [comment]
> If you use bazel run, which compiles then runs the app, you can pass the flags to the actual binary (not bazel) with --.
> So it would look like bazel run -- --input_dir=...

Thanks. It's worked well!
