### ISSUE TITLE
How to make sure the resources are laoded in javascript (Hand web demo)

### ISSUE THREAD

**Issue by vasanthhr** [google/mediapipe#2334]
How to get verify or any event listener to confirm whether all hand related resources are downloaded.

I want to get to know in javascript whether bin, wasm, sim_wasm, and .data files are downloaded and initialized.

Please let me know what is the way to check on javascript level:

javascript code: https://google.github.io/mediapipe/solutions/hands.html#javascript-solution-api
link: https://codepen.io/mediapipe/pen/RwGWYJw?editors=1000

```

  const hands = new Hands({ locateFile: (file) => {
          return `https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/${file}`;
      } });
  hands.onResults(onResults);
```

**Comment by sgowroji** [comment]
Have you checked (using Chrome's built-in "Network" tab, for example) that all fetches are succeeding and not returning 404 errors. Did you encounter any errors?

**Comment by tyrmullen** [comment]
@vasanthhr That is not a feature we currently support in any API call.  See issue #2115 for more details.
