### ISSUE TITLE
AttributeError: module 'mediapipe' has no attribute 'solution'

### ISSUE THREAD

**Issue by dariusvesa** [google/mediapipe#2336]
Greetings, 

I have a problem running the code below **demo.py** from desktop :

```
import mediapipe as mp
import cv2

mp_drawing=mp.solution.drawing_utils
mp_holistic=mp.solutions.holistic

cap=cv2.VideoCapture(0)

while cap.IsOpened():
    ret, frame=cap.read()
    cv2.imshow('Raw Webcam Feed', frame)

    if cv2.waitKey(10) & 0xFF ==ord('q'):
        break

cap.release()
cv2.destroyAllLWindows()
```

It gives me the following error:   

**Traceback (most recent call last):
File "C:\Users\\%user%\Desktop\demo.py", line 4, in <module>
mp_drawing=mp.solution.drawing_utils
AttributeError: module 'mediapipe' has no attribute 'solution'**   

I have downloaded python-3.7.9-x64 from [https://www.python.org/downloads/release/python-379/](https://www.python.org/downloads/release/python-379/) and installed it on my Local Drive(D:). During the custom installation i checked the box **Add Python to environment variable**
Then using cmd I wrote: **python -m pip install mediapipe**   -> The final line said **Successfully installed absl-py-0.13.0 attrs-21.2.0 cycler-0.10.0 kiwisolver-1.3.1 matplotlib-3.4.2 mediapipe-0.8.6 numpy-1.21.1 opencv-contrib-python-4.5.3.56 pillow-8.3.1 protobuf-3.17.3 pyparsing-2.4.7 python-dateutil-2.8.2 six-1.16.0 wheel-0.36.2**

My **D:\Programs\Python 3.7.9\Lib\site-packages\ contains the following folders**:  
\ _ _pycache__
\absl
\absl_py-0.13.0.dist-info
\attr
\attrs-21.2.0.dist-info
\cv2
\cycler-0.10.0.dist-info
\dateutil
\google
\kiwisolver-1.3.1.dist-info
\matplotlib
\matplotlib-3.4.2.dist-info
\mediapipe
\mediapipe-0.8.6.dist-info
\mpl_toolkits
\numpy
\numpy-1.21.1.dist-info
\opencv_contrib_python-4.5.3.56.dist-info
\PIL
\Pillow-8.3.1.dist-info
\pip
\pip-21.1.3.dist-info
\pkg_resources
\protobuf-3.17.3.dist-info
\pyparsing-2.4.7.dist-info
\python_dateutil-2.8.2.dist-info
\setuptools
\setuptools-56.0.0.dist-info
\six-1.16.0.dist-info
\wheel
\wheel-0.36.2.dist-info
...

I am using Windows 10 Pro 19042.1110

I really do not know what am I doing wrong. I'd be so grateful for any help/suggestion.

**Comment by sgowroji** [comment]
Hi @dariusvesa, Could you please check this https://github.com/google/mediapipe/issues/2005#issuecomment-835846942. And i would also request you to check if there are multiple versions of python installed could give you the above error.

**Comment by dariusvesa** [comment]
Greetings. First of all thank you for your reply and time. 

Second, you gave me an idea. I remembered that I have install Visual Studio Community so I checked if I installed there Python too. Apparently there is a package but there's no folder "Python" in "Microsoft Visual Shared". Check image below.

[https://i.imgur.com/G6IO9o3.png](https://i.imgur.com/G6IO9o3.png)

Then I check what Environment Path is Visual Studio using for the Python package. It's the same which I installed from [ https://www.python.org/downloads/release/python-379/ ]( https://www.python.org/downloads/release/python-379/ ). Check image below. 

[https://i.imgur.com/FlbnNQe.png](https://i.imgur.com/FlbnNQe.png)

Ultimately I check if other packages are working ( **_i.e matplotlib_** ). I wrote **demo2.py** and run it from Desktop

```
import numpy as np
import matplotlib.pyplot as plt

x1 = np.linspace(0.0, 5.0)
x2 = np.linspace(0.0, 2.0)
y1 = np.cos(2 * np.pi * x1) * np.exp(-x1)
y2 = np.cos(2 * np.pi * x2)

fig, (ax1, ax2) = plt.subplots(2, sharey=True)

ax1.plot(x1, y1, 'ko-')
ax1.set(title='A tale of 2 subplots', ylabel='Damped oscillation')

ax2.plot(x2, y2, 'r.-')
ax2.set(xlabel='time (s)', ylabel='Undamped')

plt.show()
```

It's working. Here's the results.

![image](https://user-images.githubusercontent.com/17565533/127028913-a846c5d9-0e84-4e03-a639-874363d7962f.png)


I really have no idea what could be the problem.
