### ISSUE TITLE
is this possible to get camera 3d pose (objectron)

### ISSUE THREAD

**Issue by gb2111** [google/mediapipe#2337]
hi.
i was looking through the api but could not find a reference.
i was looking on demo of objectron and there is one image where you show camera trace (Fig 3)
https://google.github.io/mediapipe/solutions/objectron.html
is this possible to get access in real time to camera position and rotation (relative to some specific objec or landmark of course).
is this possible to have access to each point in point cloud?
my primary goal is to get 3d pose of camera. secondary is to get pose of multiple cameras but I don't think that would be option for MP.
Thanks.

**Comment by sgowroji** [comment]
Hi @gb2111, Have you tried building any of the platforms and didn't you found it recognizing as Fig3. Which platform are you referring? Thanks!

**Comment by gb2111** [comment]
@sgowroji I build python samples and they work very well.

My point is to get position of camera, not the object. Is that possible?

**Comment by ahmadyan** [comment]
To get an accurate camera pose on device, you'll need to use [ARCore camera API](https://developers.google.com/ar/reference/java/com/google/ar/core/Camera#getPose()).
