### ISSUE TITLE
AAR video stream dies if timing varies

### ISSUE THREAD

**Issue by zigenz** [google/mediapipe#2338]
Hi all, I have observed (what is seemingly) an issue with MediaPipe.

**System information**

- Have I written custom code: Yes, but as close-as-possible to the Iris Tracking example
- OS Platform and Distribution: Linux Ubuntu 20.04
- Mobile device: Huawei Mate 20 Pro, OnePlus 6. Google Pixel 4
- Programming Language and version: C++ / Java (Android)
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.6
- Bazel version (if compiling from source): 4.1.0
- Solution ( e.g. FaceMesh, Pose, Holistic ): Iris Tracking GPU / AAR
- Android Studio, NDK, SDK versions: SDK 27, NDK 21.4.7075529

**Describe the expected behavior:**
I am observing an issue where I have built the MediaPipe Iris Tracking example into an AAR and integrated it into a tradtional Gradle application.  In my application, I create a fragment in the main activity, and retarget the preview output to a FrameLayout in the fragment.  The video only fires up (anecdotally) 10% of the time.

The AAR has been generated using the guidelines here: https://google.github.io/mediapipe/getting_started/android_archive_library.html.  The file generate_aar.sh in the mediapipe_aar folder in repo does this in an automated fashion.

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:

Please see repo: https://github.com/zigenz/mediapipe_issue.  This is not an exact analog of my architecture, but it reliably recreates the scenario.

Build and run it in Android Studio in debug mode, with a breakpoint on line 181 in MainActivityBase.java.  Once it hits the breakpoint, resume - there will be no video, and very little able to be gleaned from the logger output.  Running it without any breakpoint does not reveal any issue.

**Other info / Complete Logs :**
N/A

**Comment by sgowroji** [comment]
Hi @zigenz, Could you please provide a recording video while executing the APK on the device. And also share us, your use case  using iris solution and any exception logs
