### ISSUE TITLE
Hello, in the android gesture recognition, I want to use your own video YUV data is passed to the mediapipe, instead of using the data of mobile phone camera, I need how to modify com.google.mediapipe.com ponents package of files. Please help me, thank you.

### ISSUE THREAD

**Issue by Sanerly** [google/mediapipe#234]

**Comment by eknight7** [comment]
What is the source of the YUV data?

**Comment by afsaredrisy** [comment]
I am also looking for similar solution, Its looking they added support for YUV frames in ```flow_limiter_calculator.cc``` calculator but there is no method available in ```AndroidPacketCreator``` or in ```PacketCreator``` classes to create YUVBuffer. So I convert YUV2RGB using shader and render to ```FrameBuffer```. I used ```GL_TEXTURE_2D``` instead of ```GL_TEXTURE_EXTERNAL_OES``` in TextureRenderer, Now I can pass this texture to ```FrameProcessor.onNewFrame(final TextureFrame frame)``` method.
Other  things will be similar now.

**Comment by Sanerly** [comment]
> I am also looking for similar solution, Its looking they added support for YUV frames in `image_transformation_calculator.cc` calculator but there is no method available in `AndroidPacketCreator` or in `PacketCreator` classes to create YUVBuffer. So I convert YUV2RGB using shader and render to a texture of `FrameBuffer`. I used `GL_TEXTURE_2D` instead of `GL_TEXTURE_EXTERNAL_OES` in TextureRenderer, Now I can pass this texture to `FrameProcessor.onNewFrame(final TextureFrame frame)` method.
> Other things will be similar now.

Thanks for your help. I am busy with other things these days. I will try the way you said.

**Comment by Sanerly** [comment]
> What is the source of the YUV data? Is it from a different camera or a video file?

Hello, I used my own camera to transmit the data, which is currently in YUV format
