### ISSUE TITLE
How do you add filters ?

### ISSUE THREAD

**Issue by TTR-maniac** [google/mediapipe#2340]
Okay I wanted to use mediapipe to make a snapchat kind filter app
My os is windows
The programming language I'm using: **PYTHON**
I am trying to figure all ways to make it but
Mediapipe is not that popular!
I do not know why but every tutorial I see to make a filter like snapchat in mediapipe **Just doesn't work! **
I don't know why but they just put a video and use medipipe to put a filter on that!
I want it in real time!
Like using the webcam to add filter like the real snapchat app

**Comment by sgowroji** [comment]
Hi @TTR-maniac,  Could you please provide your observation with any of the solutions you tried and provide the issue  details faced while adding the filters.
