### ISSUE TITLE
 I want to use video tag instead of webcam in javascript

### ISSUE THREAD

**Issue by unizzang0907** [google/mediapipe#2341]
Hello
I'm using mediapipe in javascript/react.
I want to use video tag instead of webcam.
But I could only find examples using a webcam.
How can I apply holistic model to video tag instead of webcam?

`    
    const videoElement = document.getElementsByClassName('input_video')[0];
    const canvasElement = document.getElementsByClassName('output_canvas')[0];
    const canvasCtx = canvasElement.getContext('2d');

    function removeElements(landmarks, elements) {
        for (const element of elements) {
            delete landmarks[element];
        }
    }

    function removeLandmarks(results) {
        if (results.poseLandmarks) {
            removeElements(
                results.poseLandmarks, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 16, 17, 18, 19, 20, 21, 22]);
        }
    }

    function connect(ctx, connectors) {
        const canvas = ctx.canvas;
        for (const connector of connectors) {
            const from = connector[0];
            const to = connector[1];
            if (from && to) {
                if (from.visibility && to.visibility &&
                    (from.visibility < 0.1 || to.visibility < 0.1)) {
                    continue;
                }
                ctx.beginPath();
                ctx.moveTo(from.x * canvas.width, from.y * canvas.height);
                ctx.lineTo(to.x * canvas.width, to.y * canvas.height);
                ctx.stroke();
            }
        }
    }
    
    function onResults(results) {
        // Hide the spinner.
        document.body.classList.add('loaded');

        // Remove landmarks we don't want to draw.
        removeLandmarks(results);
        // Draw the overlays.
        canvasCtx.save();
        canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
        canvasCtx.drawImage(
            results.image, 0, 0, canvasElement.width, canvasElement.height);

        // Connect elbows to hands. Do this first so that the other graphics will draw
        // on top of these marks.
        canvasCtx.lineWidth = 5;
        if (results.poseLandmarks) {
            if (results.rightHandLandmarks) {
                canvasCtx.strokeStyle = '#00FF00';
                connect(canvasCtx, [
                    [
                        results.poseLandmarks[POSE_LANDMARKS.RIGHT_ELBOW],
                        results.rightHandLandmarks[0]
                    ]
                ]);
            }
            if (results.leftHandLandmarks) {
                canvasCtx.strokeStyle = '#FF0000';
                connect(canvasCtx, [
                    [
                        results.poseLandmarks[POSE_LANDMARKS.LEFT_ELBOW],
                        results.leftHandLandmarks[0]
                    ]
                ]);
            }
        }

        // Pose...
        drawConnectors(
            canvasCtx, results.poseLandmarks, POSE_CONNECTIONS, { color: '#00FF00' });
        drawLandmarks(
            canvasCtx, results.poseLandmarks, { color: '#00FF00', fillColor: '#FF0000' }); 

        // Hands...
        drawConnectors(
            canvasCtx, results.rightHandLandmarks, HAND_CONNECTIONS, { color: '#00FF00' }); 
        drawLandmarks(
            canvasCtx, results.rightHandLandmarks, {
                color: '#00FF00',
                fillColor: '#FF0000',
                lineWidth: 2,
                radius: (data) => {
                    return lerp(data.from.z, -0.15, .1, 10, 1);
                }
            });
        drawConnectors(
            canvasCtx, results.leftHandLandmarks, HAND_CONNECTIONS, { color: '#CC0000' })
        drawLandmarks(
            canvasCtx, results.leftHandLandmarks, {
                color: '#FF0000',
                fillColor: '#00FF00',
                lineWidth: 2,
                radius: (data) => {
                    return lerp(data.from.z, -0.15, .1, 10, 1);
                }
            });

        // Face...
        drawConnectors(
            canvasCtx, results.faceLandmarks, FACEMESH_TESSELATION, { color: '#C0C0C070', lineWidth: 1 });
        drawConnectors(
            canvasCtx, results.faceLandmarks, FACEMESH_RIGHT_EYE, { color: '#FF3030' });
        drawConnectors(
            canvasCtx, results.faceLandmarks, FACEMESH_RIGHT_EYEBROW, { color: '#FF3030' });
        drawConnectors(
            canvasCtx, results.faceLandmarks, FACEMESH_LEFT_EYE, { color: '#30FF30' }); 
        drawConnectors(
            canvasCtx, results.faceLandmarks, FACEMESH_LEFT_EYEBROW, { color: '#30FF30' });
        drawConnectors(
            canvasCtx, results.faceLandmarks, FACEMESH_FACE_OVAL, { color: '#E0E0E0' });
        drawConnectors(
            canvasCtx, results.faceLandmarks, FACEMESH_LIPS, { color: '#E0E0E0' });

        canvasCtx.restore();
    }
    
    const holistic = new Holistic({locateFile: (file) => {
      return `https://cdn.jsdelivr.net/npm/@mediapipe/holistic/${file}`;
    }});
    holistic.setOptions({
      modelComplexity: 1,
      smoothLandmarks: true,
      minDetectionConfidence: 0.5,
      minTrackingConfidence: 0.5
    });
    holistic.onResults(onResults);
    
    const camera = new Camera(videoElement, {
      onFrame: async () => {
        await holistic.send({image: videoElement});
      },
      width: 1280,
      height: 720
    });
    camera.start();`

**Comment by sgowroji** [comment]
Hi @unizzang0907, Did you get a chance to go through our Holistic [codepen](https://codepen.io/mediapipe/full/LYRRYEw) examples. You can input a video in it. Thanks!

**Comment by unizzang0907** [comment]
Oh, the codepen has been updated. It has been changed to typescript, but I'll try. Thanks!
