### ISSUE TITLE
How can i get a 3d axis and a fixed landmark? (Python)

### ISSUE THREAD

**Issue by Eunchan24** [google/mediapipe#2342]
Hello
I'd like to implement it as below gif in Python.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/71329051/127097467-8498508c-3efd-449a-9a40-1fd8037189d9.gif)

I made it like this. 
![녹화_2021_07_27_13_59_33_178](https://user-images.githubusercontent.com/71329051/127098416-80022bcf-5e73-4bd0-b2ad-57448afab5c9.gif)
I want to fix the facemesh and make a 3D axis as in tensorflow js.
Does Mediapipe-Python support this feature?
Is there a way to make it?

thank you sir.

**Comment by sgowroji** [comment]
Hi @Eunchan24, You should go through these issues to understand the  3D transformation and face geometry.
https://github.com/google/mediapipe/issues/1642#issuecomment-794572140
https://github.com/google/mediapipe/issues/1786#issuecomment-818211824
At present we don't have any python code which illustrates your use case. Reach us if you still have any queries regarding the above ask. Thanks!
