### ISSUE TITLE
How can I make a successful pose tracking aar file?

### ISSUE THREAD

**Issue by Haemin-Park** [google/mediapipe#2343]
Hi :)
I want to launch a pose tracking app with a `gradle`.
I only changed from the existing color(cyan, orange) to the new color in `mediapipe/graphs/pose_tracking/subgraphs/pose_renderer_gpu.pbtxt` and saved it.

`mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD`

**1**

```
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_pose_tracking",
    calculators = ["//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps"],
)

```
```
bazel build -c opt --strip=ALWAYS \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    --fat_apk_cpu=arm64-v8a,armeabi-v7a \ mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_pose_tracking.aar
```

I successfully made `mediapipe_pose_tracking.aar` through the command above.
I also successfully made `pose_tracking_gpu.binarypb` and put it together.

When I put the generated aar file into my Android project, the following error occurs.

**2021-07-28 01:11:33.564 16496-17170/com.example.posetest A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 17170 (mediapipe/17170), pid 16496 (xample.posetest)**
2021-07-28 01:11:33.577 16496-17129/com.example.posetest I/native: I20210728 01:11:33.577010 17129 resource_util_android.cc:89] Successfully loaded: pose_detection.tflite
2021-07-28 01:11:33.578 16496-17129/com.example.posetest I/tflite: Initialized TensorFlow Lite runtime.
2021-07-28 01:11:33.578 16496-17129/com.example.posetest I/tflite: Replacing 136 node(s) with delegate (unknown) node, yielding 1 partitions.
2021-07-28 01:11:33.581 16496-17129/com.example.posetest I/tflite: Replacing 136 node(s) with delegate (unknown) node, yielding 1 partitions.
<img width="242" alt="image" src="https://user-images.githubusercontent.com/54823396/127174384-966d65f9-e958-45e3-bb67-64c96cf8bebd.png">
This is inside my aar file.

**2**

```
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_pose_tracking",
    calculators = ["//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps",
        "//mediapipe/gpu:gpu_buffer_to_image_frame_calculator",
    ],
)
```
The same error occurs when creating an aar file as above.

How can I fix this?
How can I make a successful pose tracking aar file?

P.S.) Building and running with `bazel` in the above environment was successful.

**Comment by sgowroji** [comment]
Hi @Haemin-Park, Could you please provide your code changes to understand the issue much better. Thanks!

**Comment by Haemin-Park** [comment]
@sgowroji 

`mediapipe/graphs/pose_tracking/subgraphs/pose_renderer_gpu.pbtxt`
**Existing Code**
```
# Render pose left side joints as orange circles (inside white ones).
node {
  calculator: "LandmarksToRenderDataCalculator"
  input_stream: "NORM_LANDMARKS:landmarks_left_side"
  input_stream: "RENDER_SCALE:render_scale"
  output_stream: "RENDER_DATA:landmarks_left_joints_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.LandmarksToRenderDataCalculatorOptions] {
      **landmark_color { r: 255 g: 138 b: 0 }
      connection_color { r: 255 g: 138 b: 0 }**
      thickness: 3.0
      visualize_landmark_depth: false
      utilize_visibility: true
      visibility_threshold: 0.5
    }
  }
}

# Render pose right side joints as cyan circles (inside white ones).
node {
  calculator: "LandmarksToRenderDataCalculator"
  input_stream: "NORM_LANDMARKS:landmarks_right_side"
  input_stream: "RENDER_SCALE:render_scale"
  output_stream: "RENDER_DATA:landmarks_right_joints_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.LandmarksToRenderDataCalculatorOptions] {
      **landmark_color { r: 0 g: 217 b: 231 }
      connection_color { r: 0 g: 217 b: 231 }**
      thickness: 3.0
      visualize_landmark_depth: false
      utilize_visibility: true
      visibility_threshold: 0.5
    }
  }
}
```

**Change Code**
```
# Render pose left side joints as orange circles (inside white ones).
node {
  calculator: "LandmarksToRenderDataCalculator"
  input_stream: "NORM_LANDMARKS:landmarks_left_side"
  input_stream: "RENDER_SCALE:render_scale"
  output_stream: "RENDER_DATA:landmarks_left_joints_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.LandmarksToRenderDataCalculatorOptions] {
      **landmark_color { r: 255 g: 255 b: 255 }
      connection_color { r: 255 g: 255 b: 255 }**
      thickness: 3.0
      visualize_landmark_depth: false
      utilize_visibility: true
      visibility_threshold: 0.5
    }
  }
}

# Render pose right side joints as cyan circles (inside white ones).
node {
  calculator: "LandmarksToRenderDataCalculator"
  input_stream: "NORM_LANDMARKS:landmarks_right_side"
  input_stream: "RENDER_SCALE:render_scale"
  output_stream: "RENDER_DATA:landmarks_right_joints_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.LandmarksToRenderDataCalculatorOptions] {
      **landmark_color { r: 255 g: 255 b: 255 }
      connection_color { r: 255 g: 255 b: 255 }**
      thickness: 3.0
      visualize_landmark_depth: false
      utilize_visibility: true
      visibility_threshold: 0.5
    }
  }
}
```
I only modified the RGB code.
Also, there is the same issue in the code that has not been modified. Did I make a wrong aar file?
