### ISSUE TITLE
adding 3d objects such as spectacles to the head in the facemesh solution in browser

### ISSUE THREAD

**Issue by TheSlyOne996** [google/mediapipe#2345]
Exactly as the tiltle mentions, I would like to know if it is possible and if so what are best practice steps I should take to do it.
So far I have obtained the landmarks of various parts of the mesh and tried to use those to manipulate a 3d model in a babylonjs canvas. But I was wondering if there is a better way to do the same using some calculators available in mediapipe itself that will work on the browser. I have encountered while searching the forums, the effects rendering calculator that uses the openGL for android and IOS but I do not know how to make it work on the browser.

Thanks in advance.

**Comment by sgowroji** [comment]
We unfortunately don't have examples to do this and do not have plans to provide it. You can check out the [face effect renderer calculator](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/effect_renderer_calculator.cc) and https://google.github.io/mediapipe/solutions/face_mesh.html#face-effect-example
