### ISSUE TITLE
Missing drawing_styles.py from Python PIP installation

### ISSUE THREAD

**Issue by danielpatrascu02** [google/mediapipe#2348]
**System information**
- OS Platform: Windows 10
- Programming Language: Python 3.9.1
- Installed using venv: python -m venv .venv
- MediaPipe version: 0.8.3
- OpenCV version: 4.5.3.56

**The problem**:
After installing mediapipe with PIP, I tried running the [MediaPipe Hands](https://google.github.io/mediapipe/solutions/hands#python-solution-api) example. However, I found out that the drawing_styles.py files is missing from the installation.

**Sequence of commands / steps that Iexecuted before running into the problem:**
`python -m venv .venv`
`.venv\Sctipts\activate.bat`
`pip install opencv-python`
`pip install mediapipe`

**Complete Logs:**
`(.venv) C:\1.Daniel\Projects\MediaPipe>python main.py
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    main()
  File "main.py", line 8, in main
    drawing_styles = mp.solutions.drawing_styles
AttributeError: module 'mediapipe.python.solutions' has no attribute 'drawing_styles'`

![image](https://user-images.githubusercontent.com/58570711/127301153-f6fbe77e-a52a-41ad-b407-75cf9ab04d05.png)

Full code:
`
import cv2
import mediapipe as mp

def main():

    mp_drawing = mp.solutions.drawing_utils
    mp_hands = mp.solutions.hands
    drawing_styles = mp.solutions.drawing_styles
    
    cap = cv2.VideoCapture(0)
    with mp_hands.Hands(
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5) as hands:
        while cap.isOpened():
            success, image = cap.read()
            if not success:
                print("Ignoring empty camera frame.")
                # If loading a video, use 'break' instead of 'continue'.
                continue

            # Flip the image horizontally for a later selfie-view display, and convert
            # the BGR image to RGB.
            image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)
            # To improve performance, optionally mark the image as not writeable to
            # pass by reference.
            image.flags.writeable = False
            results = hands.process(image)

            # Draw the hand annotations on the image.
            image.flags.writeable = True
            image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
            if results.multi_hand_landmarks:
                for hand_landmarks in results.multi_hand_landmarks:
                    mp_drawing.draw_landmarks(
                        image, hand_landmarks, mp_hands.HAND_CONNECTIONS,
                        drawing_styles.get_default_hand_landmark_style(),
                        drawing_styles.get_default_hand_connection_style())
            cv2.imshow('MediaPipe Hands', image)
            if cv2.waitKey(5) & 0xFF == 27:
                break
    cap.release()

if __name__ == '__main__':
    main()
`

**Comment by sgowroji** [comment]
Hi @danielpatrascu02, Can you fetch the latest code and try. Thanks!

**Comment by danielpatrascu02** [comment]
HI @sgowroji . Can you please be more specific? I am installing mediapipe with PIP. Thanks!

**Comment by sgowroji** [comment]
Try this pip install mediapipe==0.8.6.1

**Comment by danielpatrascu02** [comment]
Indeed it was a problem with my .venv python version. I made a mistake and was using python 3.6.7 in the virtual env, which only allowed installation of mediapipe 0.8.3.

After upgrading to Python 3.9.1 I was able to install mediapipe 0.8.61 and everything is working now. Thank you!
