### ISSUE TITLE
Firefox createImageBitmap 2 arguments error with selfie segmentation

### ISSUE THREAD

**Issue by maxirozay** [google/mediapipe#2349]
**System information**
- You can reproduce the bug with the official [example](https://codepen.io/mediapipe/full/wvJyQpq)
- OS: Windows 10
- Browser: Firefox 90.0.2
- package: "@mediapipe/selfie_segmentation": "^0.1.1622680987"
- Solution: selfie segmentation
- Programming Language and version: JS

**Current behavior:**

When `selfieSegmentation.send({ image: video })` is called on firefox it crash before calling `selfieSegmentation.onresult`. Apparently `Window.createImageBitmap` is called with 2 arguments which throw an error on firefox.

**Describe the expected behavior:**

Sending an image to selfieSegmentation on firefox then getting the result as it does on chrome. It could be nice to have an error handler too.

**Standalone code you may have used to try to get what you need :**

https://codepen.io/mediapipe/full/wvJyQpq

**Other info / Complete Logs :**
Uncaught (in promise) TypeError: Window.createImageBitmap: 2 is not a valid argument count for any overload.
    ya https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation.js:26
    g selfie_segmentation.js:54
    U selfie_segmentation.js:13
    next selfie_segmentation.js:14
    X selfie_segmentation.js:23
    X selfie_segmentation.js:23
    Oa selfie_segmentation.js:53
    g selfie_segmentation.js:49
    U selfie_segmentation.js:13

**Comment by mhays-google** [comment]
We do not currently support FireFox.  It is on our roadmap.  I don't have a good timeframe for you yet.

**Comment by kuaashish** [comment]
Hello @maxirozay,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by maxirozay** [comment]
Hello @kuaashish,
Thanks for the update. I'll take a look and use the new solution.

If firefox is supported we can close this issue. I'll try and close if it's the case.

**Comment by maxirozay** [comment]
So now it works on firefox with the new version.

As a side note, for face detection, the model we have to download doesn't work because `StartGraph failed: NOT_FOUND: Input tensor has type float32: it requires specifying NormalizationOptions metadata to preprocess input images.; ` so I used the model https://storage.googleapis.com/mediapipe-assets/face_detection_short_range.tflite?generation=1677044301978921 instead.
