### ISSUE TITLE
Why the screen did not show the 'hello world'  since i have built it successfully?

### ISSUE THREAD

**Issue by 1187697147** [google/mediapipe#235]
The hello_world demo has been built successfully, but the screen did not show the 'hello world' as I expected.

**Comment by NickTaSpy** [comment]
Are you on windows?

**Comment by 1187697147** [comment]
No, I tried to run this demo on Ubuntu18.04.

**Comment by lorenzob** [comment]
Same problem here:

$ bazel run --copt -DMESA_EGL_NO_X11_HEADERS mediapipe/examples/desktop/hello_world:hello_world
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/examples/desktop/hello_world:hello_world up-to-date:
  bazel-bin/mediapipe/examples/desktop/hello_world/hello_world
INFO: Elapsed time: 0.109s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

Did you find a solution?

**Comment by lorenzob** [comment]
My mistake, I missed the 

export GLOG_logtostderr=1

line.
