### ISSUE TITLE
Bazel build Hello-world failed in windows

### ISSUE THREAD

**Issue by InvisibleLeVen** [google/mediapipe#2352]
I followed the steps of mediapipe install on Windows to install mediapipe.
when I input`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="G://python3.9//python.exe" mediapipe//examples//desktop//hello_world`
bazel build fail

`
DEBUG: G:/msys2/home/leven/_bazel_leven/3jraxhub/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Build option --action_env has changed, discarding analysis cache.
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (1 packages loaded, 0 targets configured)
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (12 packages loaded, 11 targets configured)
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (20 packages loaded, 11 targets configured)
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (28 packages loaded, 11 targets configured)
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (32 packages loaded, 11 targets configured)
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (33 packages loaded, 11 targets configured)
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (33 packages loaded, 11 targets configured)
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (33 packages loaded, 11 targets configured)
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (39 packages loaded, 135 targets configured)
ERROR: Traceback (most recent call last):
        File "G:/msys2/home/leven/_bazel_leven/3jraxhub/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 529, column 58, in <toplevel>
                ios_application = rule_factory.create_apple_bundling_rule(
        File "G:/msys2/home/leven/_bazel_leven/3jraxhub/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 950, column 55, in _create_apple_bundling_rule
                rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
        File "G:/msys2/home/leven/_bazel_leven/3jraxhub/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 228, column 21, in _common_binary_linking_attrs
                apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (50 packages loaded, 624 targets configured)
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (50 packages loaded, 624 targets configured)
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: error loading package 'mediapipe/gpu': at G:/msys2/home/leven/_bazel_leven/3jraxhub/external/build_bazel_rules_apple/apple/ios.bzl:37:5: initialization of module 'apple/internal/ios_rules.bzl' failed
INFO: Elapsed time: 27.745s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (50 packages loaded, 624 targets configured)
FAILED: Build did NOT complete successfully (50 packages loaded, 624 targets configured)

`

**Comment by InvisibleLeVen** [comment]
The error appears in a certain ios library, I don’t know why compiling a desktop hello world need to reference these libraries of Android and ios

**Comment by InvisibleLeVen** [comment]
@Jiuqiang Tang

**Comment by InvisibleLeVen** [comment]
@Jiuqiang\ Tang

**Comment by InvisibleLeVen** [comment]
@jiuqiant

**Comment by sgowroji** [comment]
Hi @InvisibleLeVen , Could you please try this` bazel clean --expunge` and rerun the above. Thanks!

**Comment by InvisibleLeVen** [comment]
> Hi @InvisibleLeVen , Could you please try this` bazel clean --expunge` and rerun the above. Thanks!
I solved this problem by lowering the version of bazel, the latest version of bazel may have problems
