### ISSUE TITLE
Disable "INFO: Created TensorFlow Lite XNNPACK delegate for CPU" message on pose python

### ISSUE THREAD

**Issue by ferranmartinezlleida** [google/mediapipe#2354]
I'm using mediapipe's pose in my project. I do video analytics and I periodically call mediapipe's pose on every person on the frame. I do that with multiprocessing with a process for each person. 

The thing is that when I call:

` with mp_pose.Pose(
            static_image_mode=True,
            upper_body_only=True) as pose:`

I get this message here down below: 

`INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
`

And it's really annoying to have to put up on the terminal with it every time I call the function that contains it. 

Is there any easy way to disable it? 

Thank you in advance.

**Comment by sgowroji** [comment]
Hi @ferranmartinezlleida, Can you try this https://github.com/google/mediapipe/issues/2119#issuecomment-860927310

**Comment by ferranmartinezlleida** [comment]
Hi I can't build from source and I tried upgrading to a newer version but the INFO Message still appears

**Comment by sgowroji** [comment]
Hi @ferranmartinezlleida, Did you try this https://github.com/google/mediapipe/issues/2354#issuecomment-888914573

**Comment by ferranmartinezlleida** [comment]
> Hi @ferranmartinezlleida, Did you try this [#2354 (comment)](https://github.com/google/mediapipe/issues/2354#issuecomment-888914573)

I read the post and tried to upgrade to last version. As I said I can't build from source.

**Comment by ThisIsIdrees** [comment]
@ferranmartinezlleida hey dude I think that you need to let your IDE to access the camera and you can do that if you are a windows user by switching on the camera privacy.
