### ISSUE TITLE
Unrecognized option: --calculator_graph_config_file

### ISSUE THREAD

**Issue by logixworx** [google/mediapipe#2355]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 10
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):  Visual Studio 19
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): C++ 14
- Installed using virtualenv? pip? Conda? (if python): no
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.6
- Bazel version: bazel 3.7.2
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): opencv-3.4.10-vc14_vc15

**Describe the problem**:

ERROR: --calculator_graph_config_file=mediapipe/graphs/pose_tracking/pose_tracking_cpu.pbtxt :: Unrecognized option: --calculator_graph_config_file=mediapipe/graphs/pose_tracking/pose_tracking_cpu.pbtxt

bazel help --calculator_graph_config_file
ERROR: --calculator_graph_config_file :: Unrecognized option: --calculator_graph_config_file

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//logixworx//AppData//Local//Programs//Python//Python39//python.exe" mediapipe/examples/desktop/pose_tracking:pose_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/pose_tracking/pose_tracking_cpu.pbtxt

bazel help --calculator_graph_config_file
ERROR: --calculator_graph_config_file :: Unrecognized option: --calculator_graph_config_file

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by sgowroji** [comment]
Hi @logixworx, Could you please elaborate your use case with complete details and can you point the exact step you are referring from installation guide. Thanks!

**Comment by logixworx** [comment]
I am trying to build the pose_tracking example.

**Comment by jiuqiant** [comment]
Please do 

```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//logixworx//AppData//Local//Programs//Python//Python39//python.exe" mediapipe/examples/desktop/pose_tracking:pose_tracking_cpu 
```

"-calculator_graph_config_file" is the mediapipe flag. It's not a bazel build flag.
