### ISSUE TITLE
dynamic/static library output

### ISSUE THREAD

**Issue by zjuturtle** [google/mediapipe#236]
I'm trying to integrate mediapipe to another CMake project. I found that there is not output for shared or static library output of Bazel. So I have to tried to modify BUILD file to get one. 
My ideal structure should be [mediapipe.so + some mediapipe headers]. So  I can build desktop hello world in CMake. 
Now I got meidiapipe.so by add this in Bazel

```
cc_binary(
    name = "libcore_calculators.so",
    linkshared=True,
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "pass_through_calculator"],
)
```

But soon I found that there are a lot headers I should copy to CMake build system(I'm still trying on this). What is the best practice  if I want to integrate mediapipe in some other project? I don't want to change cmake to Bazel build system...
Thank you!

**Comment by mgyong** [comment]
@zjuturtle We previously released in [v0.6.3](https://github.com/google/mediapipe/releases/tag/v0.6.3) the [AAR library gradle method for Android](https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md). It's not CMake but you can take a look as reference.
Can you describe your use case? Let us understand it better

**Comment by zjuturtle** [comment]
I write a cmake build on CentOS. And now I'm good to run hello world.  I build mediapipe static library by cmake. Also I got some problem in running hello world. [See here](https://github.com/google/mediapipe/issues/144#issuecomment-553762642)

I suggest mediapipe can provide .so/.a + .h library output, so other application can integrate quickly.

**Comment by mgyong** [comment]
Duplicate of #294

**Comment by YaaYang** [comment]
@zjuturtle  hello can you share `hello-world` project code
