### ISSUE TITLE
Unable to add or create a new ViewController in mediapipe faceEffect

### ISSUE THREAD

**Issue by mstfabbstbr** [google/mediapipe#2362]
Hey there,
I want to create a new VC to the `MediaPipe FaceEffect` project which already generated with `Tulsi`.
At first, i can't select the target membership when i want to create a VC. Then i realized that i have to add the new VC to Compile Sources. When i add VC to that, the xcode shows me this error:

> Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
<img width="833" alt="Screen Shot 1400-05-10 at 10 20 59" src="https://user-images.githubusercontent.com/54117642/127760838-0e8df488-0122-4fe8-b35f-7bd406e67573.png">

If i delete VC from the target membership, this error will gone.

### **Now, how can i add more VC to the mediapipe project?**

NOTE: The VC that i want to add is `.swift` file and when i want to create it xcode automatically add `Objc Bridging Header`

**Comment by tommypham** [comment]
You should add your own view controller via Bazel configuration.

**Comment by mstfabbstbr** [comment]
> You should add your own view controller via Bazel configuration.

Hey, can you show me any example? Cause i tried this, but it doesn’t work. Please show me how to do that

**Comment by sgowroji** [comment]
Hi @mstfabbstbr, Have you tried to clean your build and execute.  Run this `bazel clean --expunge` and also check again.

**Comment by mstfabbstbr** [comment]
> Hi @mstfabbstbr, Have you tried to clean your build and execute. Run this `bazel clean --expunge` and also check again.

@sgowroji  :) still not working. after your command line bazel show me an error that you don't have numpy.. but numpy installed successfull.

**Comment by tommypham** [comment]
@mstfabbstbr : please look at the instruction to set up Bazel for iOS app : https://docs.bazel.build/versions/main/tutorial/ios-app.html

**Comment by mstfabbstbr** [comment]
@tommypham 
thanks for reply. but still not working. actually the BUILD file, can't found the swift file that i created.
