### ISSUE TITLE
is there a GUI for configuration auto-generation of Bazel ?

### ISSUE THREAD

**Issue by tommypham** [google/mediapipe#2368]
Hello,
I wonder if there is a GUI for configuration auto-generation of Bazel instead of editing manually ?

**Comment by sgowroji** [comment]
Hi @tommypham, Could you please elaborate your query with complete details. Thanks!

**Comment by tommypham** [comment]
@sgowroji :
For ex: I 've already had iOS project in Xcode with more than 100.000 lines of source code and multiple kind of library : static & dynamic library, and I want to build this project with Bazel configuration. 
I 've just had a little knowledge with Bazel. If there is a tool have a GUI for me to load all of source code and library and automatically create files: WORKSPACE and BUILD according to **folder structure** and **file type**, it 's easier for developer like me at the first step.
Then, we can use tool Tulsi to create Xcode project.

**Comment by sgowroji** [comment]
Hi @tommypham, At present we don't have such GUI configuration as we depend to build the solutions using bazel. Where bazel doesn't have such provision at present. Let us know if you found any GUI configuration from bazel,  we can have a look at it. Thanks!
