### ISSUE TITLE
JavaScript - get frames from a video not camera

### ISSUE THREAD

**Issue by loaysh2010** [google/mediapipe#2369]
Hello all
I am trying to implement mediapipe javascript web-based face detection. The code below is to get the stream using the webcam and video element. 

I want to ask if there is any way to get the stream from the video element that plays an uploaded video not a webcam and pass it faceDetection class,  i.e. I don't want to use a Camera object. ???
```
const camera = new Camera(videoElement, {
  onFrame: async () => {await faceDetection.send({image: videoElement});
 },
width: 480,
height: 480
});
```

**Comment by sgowroji** [comment]
Hi @loaysh2010, Did you get a chance to use the  face detection [codepen](https://codepen.io/mediapipe/pen/dyOzvZM).  example where you can upload the video. Thanks!
