### ISSUE TITLE
Mediapipe not detecting poses correctly, needs a node that allows me to convert the image to a binary image

### ISSUE THREAD

**Issue by Mateo-Git** [google/mediapipe#2370]
Hi, I'm trying to develop an Android NDK app that detects sign language poses using Mediapipe and TensorFlow Lite. I have developed the model successfully and it's already integrated into the app it has about 90% accuracy.
The problem is that it is not detecting signals correctly, I do not know how it sends the image back to the model perhaps that is the problem and the image is being sent in a differently than expected, the image must 224x224 of 1 channel (same as Mediapipe), with a black background and silhouette in a frontal position, like this.
![image](https://user-images.githubusercontent.com/15305900/128071622-8981ac6d-f765-430d-8f21-d071999bb616.png)

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): Yes, however, it is only slightly modified from Mediapipe.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 10 with WSL and Ubuntu 20.04 LTS
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.6 
- Bazel version: 4.1.0
- Solution (e.g. FaceMesh, Pose, Holistic): Pose
- Programming Language and version ( e.g. C++, Python, Java): Android NDK languages (C++ and Python)

**Describe the expected behavior:**
The app should be detecting signal poses correctly

**Standalone code you may have used to try to get what you need:**
```
# MediaPipe graph to detect/predict hand landmarks on GPU.

type: "SlrDetectionGpu"

# GPU image. (GpuBuffer)
input_stream: "IMAGE:image"

# Handedness of the detected hand (i.e. is hand left or right).
# (ClassificationList)
output_stream: "MEANINGSIGNAL:slr_meaning_render_data"

# Transforms a region of image into a 224x224 tensor while keeping the aspect
# ratio, and therefore may result in potential letterboxing.
node {
  calculator: "ImageToTensorCalculator"
  input_stream: "IMAGE_GPU:image"
  output_stream: "TENSORS:input_tensor"
  options: {
    [mediapipe.ImageToTensorCalculatorOptions.ext] {
      output_tensor_width: 224
      output_tensor_height: 224
      keep_aspect_ratio: true
      output_tensor_float_range {
        min: 0.0
        max: 1.0
      }
      gpu_origin: TOP_LEFT
      model_name: "SLR"
    }
  }
}

# node {
#   calculator: "TfLiteConverterCalculator"
#   input_stream: "IMAGE:image"
#   output_stream: "TENSORS:input_tensor"
#   node_options: {
#     [type.googleapis.com/mediapipe.TfLiteConverterCalculatorOptions] {
#       zero_center: false
#       max_num_channels: 1
#       output_tensor_float_range {
#         min: 0.0
#         max: 1.0
#       }
#     }
#   }
# }

# Runs a TensorFlow Lite model on GPU that takes an image tensor and outputs a
# vector of tensors representing, for instance, detection boxes/keypoints and
# scores.
node {
  calculator: "InferenceCalculator"
  input_stream: "TENSORS:input_tensor"
  output_stream: "TENSORS:output_tensors"
  options: {
    [mediapipe.InferenceCalculatorOptions.ext] {
      model_path: "mediapipe/modules/slr_detection/slr_model.tflite"
    }
  }
}

# Splits a vector of tensors to multiple vectors according to the ranges
# specified in option.
# node {
#   calculator: "SplitTensorVectorCalculator"
#   input_stream: "output_tensors"
#   output_stream: "landmark_tensors"
#   output_stream: "hand_flag_tensor"
#   output_stream: "handedness_tensor"
#   options: {
#     [mediapipe.SplitVectorCalculatorOptions.ext] {
#       ranges: { begin: 0 end: 1 }
#       ranges: { begin: 1 end: 2 }
#       ranges: { begin: 2 end: 3 }
#     }
#   }
# }

# Converts the hand-flag tensor into a float that represents the confidence
# score of hand presence.
# node {
#   calculator: "TensorsToFloatsCalculator"
#   input_stream: "TENSORS:hand_flag_tensor"
#   output_stream: "FLOAT:hand_presence_score"
# }

# Applies a threshold to the confidence score to determine whether a hand is
# present.
# node {
#   calculator: "ThresholdingCalculator"
#   input_stream: "FLOAT:hand_presence_score"
#   output_stream: "FLAG:hand_presence"
#   options: {
#     [mediapipe.ThresholdingCalculatorOptions.ext] {
#       threshold: 0.5
#     }
#   }
# }

# Drops handedness tensor if hand is not present.
# node {
#   calculator: "GateCalculator"
#   input_stream: "handedness_tensor"
#   input_stream: "ALLOW:hand_presence"
#   output_stream: "ensured_handedness_tensor"
# }

# Converts the handedness tensor into a float that represents the classification
# score of handedness.
node {
  calculator: "TensorsToClassificationCalculator"
  input_stream: "TENSORS:output_tensors"
  output_stream: "CLASSIFICATIONS:handedness"
  options: {
    [mediapipe.TensorsToClassificationCalculatorOptions.ext] {
      top_k: 1
      label_map_path: "mediapipe/modules/slr_detection/slr_meaning.txt"
      binary_classification: false
    }
  }
}

# Drops landmarks tensors if hand is not present.
# node {
#   calculator: "GateCalculator"
#   input_stream: "landmark_tensors"
#   input_stream: "ALLOW:hand_presence"
#   output_stream: "ensured_landmark_tensors"
# }

# Decodes the landmark tensors into a list of landmarks, where the landmark
# coordinates are normalized by the size of the input image to the model.
 node {
   calculator: "TensorsToLandmarksCalculator"
   input_stream: "TENSORS:ensured_landmark_tensors"
   output_stream: "NORM_LANDMARKS:landmarks"
   options: {
     [mediapipe.TensorsToLandmarksCalculatorOptions.ext] {
       num_landmarks: 21
       input_image_width: 224
       input_image_height: 224
       # The additional scaling factor is used to account for the Z coordinate
       # distribution in the training data.
       normalize_z: 0.4
     }
   }
 }

# Adjusts landmarks (already normalized to [0.f, 1.f]) on the letterboxed hand
# image (after image transformation with the FIT scale mode) to the
# corresponding locations on the same image with the letterbox removed (hand
# image before image transformation).
# node {
#   calculator: "LandmarkLetterboxRemovalCalculator"
#   input_stream: "LANDMARKS:landmarks"
#   input_stream: "LETTERBOX_PADDING:letterbox_padding"
#   output_stream: "LANDMARKS:scaled_landmarks"
# }

# Projects the landmarks from the cropped hand image to the corresponding
# locations on the full image before cropping (input to the graph).
# node {
#   calculator: "LandmarkProjectionCalculator"
#   input_stream: "NORM_LANDMARKS:scaled_landmarks"
#   input_stream: "NORM_RECT:hand_rect"
#   output_stream: "NORM_LANDMARKS:hand_landmarks"
# }
#com.google.mediapipe.framework.MediaPipeException: invalid argument: while processing the input streams of subgraph node SlrDetectionGpu: ; Tag "VECTOR" does not exist in the subgraph config.
# Converts classification to drawing primitives for annotation overlay.
node {
  calculator: "LabelsToRenderDataCalculator"
  input_stream: "CLASSIFICATIONS:handedness"
  output_stream: "RENDER_DATA:slr_meaning_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.LabelsToRenderDataCalculatorOptions]: {
      color { r: 255 g: 255 b: 255 }
      thickness: 5.0
      font_height_px: 25
      horizontal_offset_px: 15
      vertical_offset_px: 25

      max_num_labels: 1
      location: TOP_LEFT
    }
  }
}

```
**If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:** 
https://github.com/kevinjoe2/mediapipe
https://github.com/kevinjoe2/mediapipe/blob/master/mediapipe/graphs/slr_tracking/slr_tracking_gpu.pbtxt

Any help would be greatly appreciated, please let me know if you need anything else. Thank you so much.

**Comment by sgowroji** [comment]
Hi @Mateo-Git, Could you please confirm your changes done on graph or MainActivity.java class?  And also need your confirmation on why the nodes are commented. Thanks!

**Comment by Mateo-Git** [comment]
Hi, I didn't make any changes to MainActivity.java. I created a new graph for my project, however upon further inspection I realized that the pose isn't the problem after all. As I said I'm trying to develop a sign language recognition app with static frames and I need a node that allows me to convert the image to a binary image (the other nodes are commented because I believe I don't need them for what I am developing). I believe the way it sends the image back to the model is the problem and the image is being sent in a differently than expected, the image must 224x224, 1 channel (same as Mediapipe), with a black background and silhouette in a frontal position.
![d523cbf2-a79e-451e-966f-991f99a1e228](https://user-images.githubusercontent.com/15305900/128125234-1df73c49-9bca-4133-9f6d-7aa8fa5acd21.jpg)
This is the node I have developed so far, perhaps this is why MediaPipe is not detecting the sign language signals correctly, could you please tell me if that's the case and if so what should I change to get it working? Thank you so much.

**Comment by kuaashish** [comment]
Hello @Mateo-Git,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
