### ISSUE TITLE
AttributeError: module 'mediapipe.python.solutions' has no attribute 'drawing_styles'

### ISSUE THREAD

**Issue by megh21** [google/mediapipe#2371]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): given example
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows python3.8.5
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic): Hands
- Programming Language and version ( e.g. C++, Python, Java): Python

**Describe the expected behavior:**

I tried to run given code on mediapipe page for hands implementation in python.

```
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands
drawing_styles = mp.solutions.drawing_styles
```

it gives such error
AttributeError: module 'mediapipe.python.solutions' has no attribute 'drawing_styles'

**Comment by sgowroji** [comment]
Hi @megh21, Can you try this https://github.com/google/mediapipe/issues/2348

**Comment by megh21** [comment]
got it, installed new version python version 3.9, it works!
