### ISSUE TITLE
How to use XNNPACK and NNAPI to accelerate the blaze-pose model? Can you provide an Android demo?

### ISSUE THREAD

**Issue by APeiZou** [google/mediapipe#2373]
Can the blaze-pose model be accelerated by XNNPACK and NNAPI at the same time? Can the blaze-pose model be accelerated by XNNPACK and NNAPI at the same time? Which of XNNPACK and NNAPI has better acceleration performance?

**Comment by APeiZou** [comment]
@google-admin

**Comment by APeiZou** [comment]
@google-admin

**Comment by APeiZou** [comment]
@sgowroji  I found the XNNPACK accelerated package when using the blaze-pose model, but I don’t know how to use it in the Android demo? Can you provide a demo of the balze-pose model accelerated by XNNPACK?

**Comment by APeiZou** [comment]
@chuoling Regarding the above issue, can you help me?

**Comment by sgowroji** [comment]
Hi @APeiZou, Adding this https://github.com/google/mediapipe/issues/1962 for your reference on NNAPI and XNNPACK. Thanks!
