### ISSUE TITLE
How to crop the human body area of interest in the current frame according to the posture detection result of the previous frame, so that the model keeps the same individual body posture recognition and tracking? It will not mistakenly identify the key points of other people's gestures.

### ISSUE THREAD

**Issue by APeiZou** [google/mediapipe#2374]
How to crop the human body area of interest in the current frame according to the posture detection result of the previous frame, so that the model keeps the same individual body posture recognition and tracking? It will not mistakenly identify the key points of other people's gestures.@google

**Comment by APeiZou** [comment]
@google

**Comment by APeiZou** [comment]
@ivan-grishchenko Regarding the above issue, can you help me?

**Comment by kuaashish** [comment]
Hello @APeiZou,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
