### ISSUE TITLE
Tool from Documentation Question

### ISSUE THREAD

**Issue by sn1c3** [google/mediapipe#2375]
I stumbled on a cool tool for visualization on your [documentation page](https://google.github.io/mediapipe/solutions/pose).

Specifically I mean [Figure 5](https://google.github.io/mediapipe/images/mobile/pose_world_landmarks.mp4)

May I ask what tool you used for this? Or can you recommend a tool for 3d visualization in python?

**Comment by sgowroji** [comment]
Hi @sn1c3, Have a look at this https://github.com/google/mediapipe/issues/2274#issuecomment-877498840
