### ISSUE TITLE
Set camera resolution and/or aspect ratio

### ISSUE THREAD

**Issue by dtbkk48** [google/mediapipe#238]
Hello,

I tried Mediapipe examples on Ubuntu and noticed that the input resolution into Mediapipe was always smaller than the maximum resolution of the cameras that were used:
- An integrated camera, max resolution 1280x720
- A USB camera, max resolution 1920x1080
In both cases, the camera aspect ratio was 16:9, but the input resolution into Mediapipe was 640x480 (aspect ratio 4:3).

Can we set the input resolution or aspect ratio into Mediapipe arbitrary? I've tried v4l2-ctl --set-fmt-video=width=1280,height=720 before running the desktop examples but the input resolution into Mediapipe did not change.

Many thanks for your help!

**Comment by mcclanahoochie** [comment]
Hi,
You can modify the [live demo example](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/demo_run_graph_main.cc#L78) to request opencv set different camera properties.

Find  
```
cvx::namedWindow(kWindowName, /*flags=WINDOW_AUTOSIZE*/ 1);
```
and insert these lines right after:
```
    capture.set(cvx::CAP_PROP_FRAME_WIDTH, 1280);
    capture.set(cvx::CAP_PROP_FRAME_HEIGHT, 720);
```


This relies on opencv honoring that request; there is nothing mediapipe can do to control the camera resolution.

One thing to note is, for any mediapipe example that uses TFLite/TensorFlow, the first thing mediapipe graph does is to downsize the image into whatever the model expects (regardless of input image size).

**Comment by dtbkk48** [comment]
Hi mcclanahoochie, it works - thank you so much!
