### ISSUE TITLE
where to draw 

### ISSUE THREAD

**Issue by zhoujingheng** [google/mediapipe#2380]
face mesh android  where to draw pot and line onview , i want to delete the ui

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2403#issuecomment-897326635

**Comment by sgowroji** [comment]
Hi @zhoujingheng, You can use Android facemesh api source code now https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions.  Please refer this https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/solutions/facemesh/src/main/java/com/google/mediapipe/examples/facemesh/FaceMeshResultGlRenderer.java class to explore and make changes as you need.
