### ISSUE TITLE
Selfie Segmentation triggers alert on failure: Failed to create WebGL canvas context when passing video frame

### ISSUE THREAD

**Issue by schontz** [google/mediapipe#2381]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Chrome
- Programming Language and version ( e.g. C++, Python, Java): JS
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.1.1628007100
- Bazel version (if compiling from source): -
- Solution ( e.g. FaceMesh, Pose, Holistic ): Selfie Segmentation
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): -
- Xcode & Tulsi version (if issue is related to building for iOS): -

**Describe the current behavior:**

If a certain failure occurs, the browser shows an alert. From [selfie_segmentation.js](https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1.1628007100/selfie_segmentation.js):
```
alert("Failed to create WebGL canvas context when passing video frame.")
```

**Describe the expected behavior:**

Errors should be returned via the API and not displayed via an alert.

**Comment by sgowroji** [comment]
Hi @schontz, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by schontz** [comment]
I haven't found the root cause, but the fact that there's an alert in the source code is the issue. 

Here's the relevant section from `selfie_segmentation.js` (pretty-printed):

```
          case 7:
            d.l = document.createElement('canvas');
            q = d.l.getContext('webgl2', {});
            if (!q && ((q = d.l.getContext('webgl', {})), !q))
              return (
                alert('Failed to create WebGL canvas context when passing video frame.'), l.return()
              );
            d.C = q;
            d.h.canvas = d.l;
            d.h.createContext(d.l, !0, !0, {});
```

There should be no alerts in public code. Logging an error and throwing it would make sense (if you cannot recover).

**Comment by mhays-google** [comment]
Agreed. Will probably remove the alert and throw.  No time frame at the moment.

**Comment by schontz** [comment]
Can you give any background on why this might occur? It seems to fail getting the context from the canvas. I'm not sure how that would fail.

**Comment by LuukOriginal** [comment]
I'm also running into the same issue rn, any way to fix it? (if more info is required just ask me)

**Comment by LuukOriginal** [comment]
Ok, so I did some experimenting, and found out it could have something to do with the browser, I mean, I use opera GX by default, and it does give me the `Failed to create WebGL canvas context when passing video frame` error, but when you open the website in chrome, it works all fine for me

**Comment by houcy** [comment]
> Ok, so I did some experimenting, and found out it could have something to do with the browser, I mean, I use opera GX by default, and it does give me the `Failed to create WebGL canvas context when passing video frame` error, but when you open the website in chrome, it works all fine for me. `Edit: I just restarted my computer, and it sudently works now on my opera GX now too`

In fact in Chrome latest version, the same error still exists.

**Comment by alokmahor** [comment]
I am using Selfie Segmentation in electron js application. I am also seeing alert **"failed to create webgl canvas context when passing video frame electron"** and error in console **"Uncaught (in promise) TypeError: Cannot read property "loadGraph" of undefined"**

Not able to figure out what is causing this error and alert.

**Comment by MMX777** [comment]
Any update?

**Comment by mmitou** [comment]
In my environment, this error stopped occurring after reinstalling the GPU device driver.

This error seems to occur when getContext('webgl2') fails.
And getContext('webgl2') fails if the browser cannot use webgl2.

Please open the following address in chrome.
- chrome://gpu

If you are seeing this error, WebGL2 may be disabled in your environment.
I do not know why WebGL is not enabled in your browser, but I recommend that you check your device driver installation and settings around graphics.

**Comment by kuaashish** [comment]
Hello @schontz,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by ShwetKhatri2001** [comment]
Hi, I'm getting this same error on Chrome when I'm using some custom shaders to render a 3D object on top of pose detection by Mediapipe. I tested it across browsers & devices and it is working fine on Firefox. 

- On the same device, when I try it multiple times on Chrome, it works sometimes & throws this alert the other times. 
- On many other devices, it works easily on Chrome as well.

@schontz @kuaashish Were you able to find a fix for this? 
I'm not using [new Mediapipe solutions](https://developers.google.com/mediapipe/solutions). Is it fixed there ?

**Comment by schontz** [comment]
The only solution I know is to override alert:

```
const realAlert = window.alert.bind(window);
window.alert = (message) => {
  if (message === "Failed to create WebGL canvas context when passing video frame.") return
  return realAlert(message);
}
```
