### ISSUE TITLE
android use solution facemesh error

### ISSUE THREAD

**Issue by zhoujingheng** [google/mediapipe#2382]
```
  FaceMeshOptions faceMeshOptions = FaceMeshOptions.builder()
                  .setMode(FaceMeshOptions.STREAMING_MODE)
                .build();
        faceMesh = new FaceMesh(mActivity, faceMeshOptions);
        faceMesh.setResultListener(new ResultListener<FaceMeshResult>() {
            @Override
            public void run(FaceMeshResult result) {
                FaceTrackParam faceTrackParam = FaceTrackParam.getInstance();
                if (faceTrackParam.trackerCallback != null) {
                    faceTrackParam.trackerCallback.onTrackingFinish();
                }
            }
        });
        faceMesh.setErrorListener(new ErrorListener() {
            @Override
            public void onError(String message, RuntimeException e) {
                System.out.println("message:" + e.getMessage()+Thread.currentThread().getName());
                FaceTrackParam faceTrackParam = FaceTrackParam.getInstance();
                if (faceTrackParam.trackerCallback != null) {
                    faceTrackParam.trackerCallback.onTrackingFinish();
                }
            }
        });
```

```
      public void onPreviewFrame(ImageProxy imageProxy) {
              faceMesh.send(toBitmap(imageProxy.getImage()), imageProxy.getImageInfo().getTimestamp());
              imageProxy.close();
      }
```

```
    private Bitmap toBitmap(Image image) {
            Image.Plane[] planes = image.getPlanes();
            ByteBuffer yBuffer = planes[0].getBuffer();
            ByteBuffer vuBuffer = planes[2].getBuffer();
            int ySize = yBuffer.remaining();
            int vuSize = vuBuffer.remaining();
    
            byte[] nv21 = new byte[ySize + vuSize];
            yBuffer.get(nv21, 0, ySize);
            vuBuffer.get(nv21, ySize, vuSize);
            YuvImage yuvImage = new YuvImage(nv21, ImageFormat.NV21, image.getWidth(), image.getHeight(), null);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            yuvImage.compressToJpeg(new Rect(0, 0, yuvImage.getWidth(), yuvImage.getHeight()), 50, out);
            byte[] imageBytes = out.toByteArray();
            return BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.length);
     }
```

error_message:
Graph is not started because of missing streams

**Comment by sgowroji** [comment]
Hi @zhoujingheng, Could you please provide the steps to reproduce the above error. Can you share us the complete error logs. Thanks!

**Comment by zhoujingheng** [comment]
step:
1.init FaceMesh

2.camerax callback analyze(ImageProxy image)

3.image convert to bitmap

4..facemesh.send(bitmap,timestamp)

result:
5.facemesh onError()，the exception:Graph is not started because of missing streams

**Comment by zhoujingheng** [comment]
can you give me FaceMesh use sample on android?

**Comment by sgowroji** [comment]
In Java framework This is the graph error thrown while [addpackettoBuffer](https://github.com/google/mediapipe/blob/a9b643e0f5978425d948050a2228398929733d05/mediapipe/java/com/google/mediapipe/framework/Graph.java#:~:text=%7D-,private%20boolean%20addPacketToBuffer(String%20streamName%2C%20Packet%20packet%2C%20long%20timestamp)%20%7B,%7D,-//%20Any%20previously-buffered)

**Comment by zhoujingheng** [comment]
ok，can you give me FaceMesh use sample on android with camerax

**Comment by sgowroji** [comment]
Right we don't provide any such code, but you can build one from https://google.github.io/mediapipe/getting_started/android_archive_library.html#mediapipe-android-archive and you can even try this https://github.com/jiuqiant/mediapipe_face_detection_aar_example using with facemesh aar.

**Comment by zhoujingheng** [comment]
![image](https://user-images.githubusercontent.com/12888787/128683377-4f8e25c0-cab8-49a9-903e-5d09e17e0a81.png)
i want to this use sample，not aar

**Comment by sgowroji** [comment]
Dupliacate https://github.com/google/mediapipe/issues/2403#issuecomment-897326635

**Comment by sgowroji** [comment]
Closing this issue w.r.t this  https://github.com/google/mediapipe/issues/2403#issuecomment-901596776. Please reach us if you still have any queries regarding the above.
