### ISSUE TITLE
Can I use wax hands with the same size and color as real hand for model training ?

### ISSUE THREAD

**Issue by tommypham** [google/mediapipe#2383]
Hello,
Can I use wax hands with the same size and color as real hand for model training ?
We can re-use wax hands for multiple view in 3D to train model.

**Comment by sgowroji** [comment]
Hi @tommypham, Could you please elaborate your use case with complete details. Thanks!

**Comment by tommypham** [comment]
I am not sure about training process. What I understood is If we can cover as much as possible the use case of reality , we can detect exactly when applying the framework of AI.
Wax hands can provide a flexible method to adapt to reality that sometimes we don't cover yet in training.
