### ISSUE TITLE
Allow to emit empty packet in pose_tracking

### ISSUE THREAD

**Issue by easyfittransfer** [google/mediapipe#2387]
I am making the app which track body
I use this function to recognize pose
```
 [self.mediapipeGraph sendPixelBuffer:imageBuffer
                                  intoStream:kInputStream
                                  packetType:MPPPacketTypePixelBuffer];
```

But it is not call the method below if pose are not recognized.
```
mediapipeGraph:(MPPGraph*)graph
       didOutputPacket:(const ::mediapipe::Packet&)packet
            fromStream:(const std::string&)streamName
```
Any ideas how to allow call delegate method in case body is not recognized?

**Comment by sgowroji** [comment]
Hi @easyfittransfer, Did you face any error while executing the above. Can you share the logs.
