### ISSUE TITLE
Uncaught ReferenceError: javascript is not defined     at control_utils_3d.min.js:65

### ISSUE THREAD

**Issue by AdrienVigne** [google/mediapipe#2388]
Hello, 
I have a problem when I want to use the landmark grid contained in the package control_utils_3d. 
I can't pass the loading of the script because it gives the error : 
Uncaught ReferenceError: javascript is not defined
    at control_utils_3d.min.js:65

Can you help me

Here are the git links to reproduce the problem: [https://github.com/AdrienVigne/Test_mediapipe_landmark](https://github.com/AdrienVigne/Test_mediapipe_landmark)

**Comment by sgowroji** [comment]
Hi @AdrienVigne, Could you please provide the steps to reproduce the above error. Thanks !

**Comment by AdrienVigne** [comment]
pour reproduire l'erreur il suffit de d'ouvrir le fichier le index.html dans le git du premier message.

**Comment by sgowroji** [comment]
Hi @AdrienVigne, this is  `control_utils_3d.min.js`  throwing the error. You can try  by updating  it  to`<script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/control_utils_3d.js" crossorigin="anonymous"></script>
 ` for [reference](https://google.github.io/mediapipe/solutions/pose.html#javascript-solution-api)

**Comment by AdrienVigne** [comment]
I tried following the reference but the resource is non-existent: 
GET https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/control_utils_3d.js net::ERR_ABORTED 404

**Comment by mhays-google** [comment]
@AdrienVigne 
The address is actually `https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d/control_utils_3d.js`

**Comment by AdrienVigne** [comment]
hello, even with this url I get the following errors
![image](https://user-images.githubusercontent.com/52231952/128746704-8b9c074d-4380-456f-944f-92d1838ce8f1.png)

**Comment by mhays-google** [comment]
Can you verify that `control_utils_3d.js` is actually loading into your script tag before you are trying to reference it?  On Chrome, you can go to your network tab in the developer console.  It looks like a required script is not being loaded.

```
 <script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d@0.2/control_utils_3d.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils@0.5/control_utils.js" crossorigin="anonymous"></script>
  <script src="your_script_here.js" crossorigin="anonymous"></script>
```

**Comment by sgowroji** [comment]
Hi @AdrienVigne, Can you please try to verify the script getting loaded as mentioned in the above [comment](https://github.com/google/mediapipe/issues/2388#issuecomment-895407600). Thanks!

**Comment by AdrienVigne** [comment]
Do you have any ideas on how to solve the problem?

**Comment by sgowroji** [comment]
Hi @AdrienVigne, Above issue is fixed and will be available in the next release. Please verify the same once the release is available. I will let you know the Release ETA soon. Thanks!

**Comment by ayoub-root** [comment]
import the file using <script src='.....'</script>
then in your react code use 
const LandMarkGrid =window.LandmarkGrid


grid = new LandmarGrid (divRef, ....)
 be careful to  components re-rendering (strictMode)
