### ISSUE TITLE
Duplicate class android.support.v4.app.RemoteActionCompatParcelizer found in modules core-1.1.0-runtime(androidx.core:core:1.1.0)and jetified-iristrackinggpu_deploy(iristrackinggpue_deploy.jar

### ISSUE THREAD

**Issue by zengalanshuo** [google/mediapipe#2389]
在尝试使用iristracking jar包时遇到不同jar包但相同类名无法解决，请各位大神帮我解决，小弟先谢谢了

**Comment by sgowroji** [comment]
Hi @zengalanshuo, Could you  please provide steps to reproduce the above error. Thanks!

**Comment by zengalanshuo** [comment]
hi sgowroji,tks,
First compile iristrackinggpu on Ubuntu to generate jar。
bazel build -c opt --strip=ALWAYS --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a mediapipe/examples/android/src/java/com/google/mediapipe/apps/iristrackinggpu:iristrackinggpu

second copy iristrackinggpu_deploy.jar from bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/iristrackinggpu/ to 4.1 version of android studio ide on windows

three,add jar to library and build apk ,this time ,the error will show

**Comment by zengalanshuo** [comment]
hi sgowroji,tks,
First compile iristrackinggpu on Ubuntu to generate jar。
bazel build -c opt --strip=ALWAYS --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a mediapipe/examples/android/src/java/com/google/mediapipe/apps/iristrackinggpu:iristrackinggpu

second copy iristrackinggpu_deploy.jar from bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/iristrackinggpu/ to 4.1 version of android studio ide on windows

three,add jar to library and build apk ,this time ,the error will show @sgowroji

**Comment by zengalanshuo** [comment]
Duplicate class org.checkerframework.checker.nullness.compatqual.NonNullType found in modules jetified-checker-compat-qual-2.5.2 (org.checkerframework:checker-compat-qual:2.5.2) and jetified-iristrackinggpu_deploy (iristrackinggpu_deploy.jar)
Duplicate class org.checkerframework.checker.nullness.compatqual.NullableDecl found in modules jetified-checker-compat-qual-2.5.2 (org.checkerframework:checker-compat-qual:2.5.2) and jetified-iristrackinggpu_deploy (iristrackinggpu_deploy.jar)
Duplicate class org.checkerframework.checker.nullness.compatqual.NullableType found in modules jetified-checker-compat-qual-2.5.2 (org.checkerframework:checker-compat-qual:2.5.2) and jetified-iristrackinggpu_deploy (iristrackinggpu_deploy.jar)
Duplicate class org.checkerframework.checker.nullness.compatqual.PolyNullDecl found in modules jetified-checker-compat-qual-2.5.2 (org.checkerframework:checker-compat-qual:2.5.2) and jetified-iristrackinggpu_deploy (iristrackinggpu_deploy.jar)
Duplicate class org.checkerframework.checker.nullness.compatqual.PolyNullType found in modules jetified-checker-compat-qual-2.5.2 (org.checkerframework:checker-compat-qual:2.5.2) and jetified-iristrackinggpu_deploy (iristrackinggpu_deploy.jar)
Duplicate class org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement found in modules jetified-animal-sniffer-annotations-1.17 (org.codehaus.mojo:animal-sniffer-annotations:1.17) and jetified-iristrackinggpu_deploy (iristrackinggpu_deploy.jar)

Go to the documentation to learn how to Fix dependency resolution errors.@ @sgowroji

**Comment by zengalanshuo** [comment]
@sgowroji  my code  https://github.com/zengalanshuo/mediapipe-iris is same error

**Comment by zengalanshuo** [comment]
my android studio ide :Android Studio 4.1
Build #AI-201.8743.12.41.6858069, built on September 23, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 6
Registry: ide.new.welcome.screen.force=true

**Comment by ayushgdev** [comment]
Hello @zengalanshuo 
Are you still looking for a resolution? If yes, would you please check if the issue persists in the new MediaPipe solutions?

We are building a set of new, improved [MediaPipe Solutions](https://developers.google.com/mediapipe/solutions) to help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. And we request the MediaPipe developer community help us uncover the issues and make the APIs more resilient.
