### ISSUE TITLE
有没有办法做多个功能组合使用，比如把手势和眼睛距离组合在一起？

### ISSUE THREAD

**Issue by zengalanshuo** [google/mediapipe#2390]

**Comment by ljmkimqx** [comment]
你不说明哪个平台，让别人怎么帮你，而且你还用中文问

**Comment by sgowroji** [comment]
Hi @zengalanshuo, Could you please elaborate your use case with complete details. And if possible can you share the description in English. Thanks!

**Comment by zengalanshuo** [comment]
hi @sgowroji tks,
I want to use two mediapipe capabilities, such as gesture recognition and eye distance, to combine them into a new function. What should I do?For example, when I am at a distance of 1 meter, I need to redraw the gesture within a fixed range. When the distance exceeds 3 meters, I need to fix the gesture within another range. At this time, I need to calculate the distance between the device and me to achieve such a function.
