### ISSUE TITLE
Can face mesh work on small faces or long-range faces?

### ISSUE THREAD

**Issue by jamesjianwang** [google/mediapipe#2396]
I want the face mesh to work on small faces. However, it seems that it can only work for large faces.

It is said that MediaPipe face mesh uses the same detection model as the MediaPipe face detection. But the face detection has a parameter called MODEL_SELECTION (Use 0 to select a short-range model that works best for faces within 2 meters from the camera, and 1 for a full-range model best for faces within 5 meters). 
It seems that face mesh uses face detector with short range.

Is there a parameter that I can set for face mesh to work on long-range faces?
Thanks!!

**Comment by sgowroji** [comment]
Hi @jamesjianwang, Have you encountered any issue while working on facemesh. Can you share a video or any observation to help us understand the issue much better. Thanks!

**Comment by eli-6over6** [comment]
what about this? can facemesh work with the full range model?
