### ISSUE TITLE
KNIFT aar on Android with Gradle using demo apps - java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNK2cv17DescriptorMatcher8knnMatchERKNS_11_InputArrayES3_RNSt6__ndk16vectorINS5

### ISSUE THREAD

**Issue by arijith96** [google/mediapipe#2397]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.6
- Bazel version:bazel 4.1.0
- Solution (e.g. FaceMesh, Pose, Holistic): KNIFT aar 
- Programming Language and version ( e.g. C++, Python, Java): Java

**Describe the expected behavior:**

My goal was to create an aar to extract the bounding box coordinates of my custom template (after having built and replacing the knift_index.pb file with my template image) using the KNIFT aar on Android Studio with gradle

When I replace the .aar file in the libs folder (from the face_detection and multi_hand_tracking demo/example projects) with the one that I generated following the steps in 
https://google.github.io/mediapipe/getting_started/android_archive_library.html

I get the following crash at 
        System.loadLibrary("mediapipe_jni");

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNK2cv17DescriptorMatcher8knnMatchERKNS_11_InputArrayES3_RNSt6__ndk16vectorINS5_INS_6DMatchENS4_9allocatorIS6_EEEENS7_IS9_EEEEiS3_b" referenced by "/data/app/~~IXWF_H6noRNss6OBiB8kZQ==/com.my.mediapipe.apps.myapplication-Eds2VNkZzhvjhYw-zhjNaw==/lib/arm64/libmediapipe_jni.so"...

Complete log:

08/10 08:36:35: Launching 'app' on Google Pixel 5.
$ adb shell am start -n "com.my.mediapipe.apps.myapplication/com.my.mediapipe.apps.myapplication.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.my.mediapipe.apps.myapplication | com.my.mediapipe.apps.myapplication.test
Waiting for application to come online: com.my.mediapipe.apps.myapplication | com.my.mediapipe.apps.myapplication.test
Connecting to com.my.mediapipe.apps.myapplication
Waiting for application to start debug server
Waiting for application to come online: com.my.mediapipe.apps.myapplication | com.my.mediapipe.apps.myapplication.test
Connecting to com.my.mediapipe.apps.myapplication
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/s.myapplicatio: Waiting for a blocking GC Instrumentation
I/s.myapplicatio: WaitForGcToComplete blocked Instrumentation on SystemWeakHolder for 13.305ms
Connected to the target VM, address: 'localhost:8600', transport: 'socket'
I/System.out: Debugger has connected
    waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10283(com.my.mediapipe.apps.myapplication) identical 1 line
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1439)
D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
W/s.myapplicatio: Got a deoptimization request on un-deoptimizable method java.lang.Object java.lang.Class.newInstance()
    Got a deoptimization request on un-deoptimizable method java.lang.Object java.lang.Class.newInstance()
W/s.myapplicatio: Got a deoptimization request on un-deoptimizable method java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])
W/s.myapplicatio: Got a deoptimization request on un-deoptimizable method java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])
W/s.myapplicatio: Got a deoptimization request on un-deoptimizable method void com.android.internal.os.ZygoteInit.main(java.lang.String[])
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my.mediapipe.apps.myapplication, PID: 15956
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNK2cv17DescriptorMatcher8knnMatchERKNS_11_InputArrayES3_RNSt6__ndk16vectorINS5_INS_6DMatchENS4_9allocatorIS6_EEEENS7_IS9_EEEEiS3_b" referenced by "/data/app/~~IXWF_H6noRNss6OBiB8kZQ==/com.my.mediapipe.apps.myapplication-Eds2VNkZzhvjhYw-zhjNaw==/lib/arm64/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.my.mediapipe.apps.myapplication.MainActivity.<clinit>(MainActivity.java:67)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3335)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 15956 SIG: 9
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'

**Comment by sgowroji** [comment]
Hi @arijith96, Can you try this https://github.com/google/mediapipe/issues/1224#issuecomment-745190852

**Comment by arijith96** [comment]
Hi @sgowroji,
Thanks for your response! 

I do not think that could help since I was able to run both the demo/example apps with the .aar. Will give it a try nonetheless.

Also, could it be because of [this](https://google.github.io/mediapipe/solutions/knift.html#:~:text=Note%3A%20MediaPipe%20uses%20OpenCV%203%20by%20default.%20However%2C%20because%20of%20issues%20between%20NDK%2017%2B%20and%20OpenCV%203%20when%20using%20knnMatch%2C%20for%20this%20example%20app%20please%20use%20the%20following%20commands%20to%20temporarily%20switch%20to%20OpenCV%204%2C%20and%20switch%20back%20to%20OpenCV%203%20afterwards.)

In this [this](https://github.com/google/mediapipe/issues/2389#issuecomment-895163181), I observed that the author had specified, [this](https://github.com/zengalanshuo/mediapipe-iris/blob/96975cf049daf61c21180f53f389d96bccc5e66e/app/src/main/java/com/example/iris/BaseActivity.java#L64) line
      System.loadLibrary("opencv_java4");

instead of the usual 

      System.loadLibrary("opencv_java3");

present in the example apps of face_detection and multi_hand_tracking

Is there some dependency on OpenCv4 that I need for DescriptorMatcherknnMatch? I was not able to find anything on the MediaPipe steps to build this library. 

How could I go about that if I need to build an aar of KNIFT to extract the x,y coordinates of the bounding box of the template that I find?

**Comment by arijith96** [comment]
Got to know what was going wrong :) 

Since there are issues with the knnMatch I needed to swtich the WORKSPACE to OpenCV4 and then build the aar. 
Also had to change the loadLibrary in Android Studio to "opencv_java4" instead of "opencv_java3" for it load properly.

Closing this issue now. Thanks!
