### ISSUE TITLE
Use only box_tracking_cpu.pbtxt

### ISSUE THREAD

**Issue by kingmacth** [google/mediapipe#2398]
I need a program to mark the frame on the video and then track it automatically. I have seen other demos. It should only be achieved by using Use only box_tracking_cpu.pbtxt. But I have not found the required input sub-graph.

**Comment by sgowroji** [comment]
Hi @kingmacth, Could you please elaborate your use case with complete details. Thanks!

**Comment by kingmacth** [comment]
Hi @sgowroji , I want to make a demo with only box_tracking and no detection

**Comment by sgowroji** [comment]
Have you tried checking this  https://google.github.io/mediapipe/solutions/instant_motion_tracking
