### ISSUE TITLE
Difference between hand_landmark.tflite and hand_landmark_sparse.tflite

### ISSUE THREAD

**Issue by Swapnil-gautam** [google/mediapipe#2399]
**System information** 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): LInux ubuntu 18.04.5 LTS
- Solution: Hand 
- Programming Language and version: Python
 
I wrote a script to test the tflite models available in Hand-Solution[](https://github.com/google/mediapipe/tree/master/mediapipe/modules/hand_landmark)  

Both the model works great (I found hand_landmark_sparse to be slightly better on my dateset).

I checked the the model architecture in Netron and they are quite different.

I wanted to understand why there are 2 different model (with almost same size and accuracy) and which one is better

`import numpy as np
import tensorflow as tf
import cv2
import numpy as np

interpreter = tf.lite.Interpreter(model_path="hand_landmark.tflite")
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

image = cv2.imread("583.jpg")
image = cv2.resize(image, (224,224))

img_tensor = np.asarray(image, np.float32)
img_tensor = np.expand_dims(img_tensor, axis=0)
img_tensor = img_tensor/256

input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)

interpreter.set_tensor(input_details[0]['index'], img_tensor)

interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])

print(type(output_data[0]))
landmarks = np.reshape(output_data[0], (21, 3))
for i in range(len(landmarks)):
    x = int(landmarks[i][0])
    y = int(landmarks[i][1])
    print(x,y)
    image = cv2.circle(image, (x,y), radius=2, color=(0, 0, 255), thickness=3)

cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()`

**Comment by sgowroji** [comment]
Hi @Swapnil-Gautam, Could you please provide, your use case regarding the tflite. And have you tried the Hands python solution directly instead of using the tflite. Thanks!

**Comment by sgowroji** [comment]
Hi @Swapnil-gautam, For difference you can refer this [blog](https://ai.googleblog.com/2021/03/accelerating-neural-networks-on-mobile.html). And also this two model cards  https://drive.google.com/file/d/1yiPfkhb4hSbXJZaSq9vDmhz24XVZmxpL/preview
https://drive.google.com/file/d/1YeTUJ7azHHPO5Bhu6OW3Rg0Ka6Z7Q6Y2/preview
