### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64 with sh build_and_run.sh            

### ISSUE THREAD

**Issue by WillBishop** [google/mediapipe#24]
Hey,

I'm trying to set up the 'Creating an Xcode Project' section in [MediaPipe iOS Setup](https://github.com/google/mediapipe/blob/master/mediapipe/docs/mediapipe_ios_setup.md).

I have bazel 0.28.1, and I symlinked my mobile provision to the directed directory.

Upon running sh build_and_run.sh, I got the error FAILED: Build did NOT complete successfully, with further details 

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //:tulsi failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 54.326s, Critical Path: 32.17s
INFO: 38 processes: 25 darwin-sandbox, 13 local.
FAILED: Build did NOT complete successfully

I tried it again with --verbose_failures and got this:

[Error was too big for Github, I hosted it on my own server](https://willbish.com/errors.txt)

**Comment by mgyong** [comment]
Adding relevant folks to the thread

**Comment by camillol** [comment]
This is actually an issue with bazelbuild/tulsi.

**Comment by mgyong** [comment]
@WillBishop We have gotten examples of users successfully building MediaPipe for iOS. https://twitter.com/2020cv_inc/status/1163971960285478912?s=21

**Comment by arizigler** [comment]
I guess you're using xcode 11 beta 4 or higher.
Apple moved swift libraries into "swift-5.0" directory, hence tulsi fails to build.
A workaround would be soft-linking the libraries from "swift-5.0" to the "swift" directory and then re-run the build process.
refer to https://forums.developer.apple.com/thread/120074.
