### ISSUE TITLE
Trace file not readable by viz.mediapipe.dev when uploading 

### ISSUE THREAD

**Issue by bschiett** [google/mediapipe#2401]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): No 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: N/A
- Programming Language and version ( e.g. C++, Python, Java): C++
- [MediaPipe version](https://github.com/google/mediapipe/releases): tag v0.8.6
- Bazel version (if compiling from source): 4.1.0
- Solution ( e.g. FaceMesh, Pose, Holistic ): 
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): N/A
- Xcode & Tulsi version (if issue is related to building for iOS): N/A 

**Describe the current behavior:**

Tried enabling tracing in one of the examples. Trace records succesfully but viz.mediapipe.dev says the file is invalid when I upload it. I have this at the root of the graph: 

profiler_config {
  trace_enabled: true
  enable_profiler: true
  trace_log_interval_count: 200
  trace_log_path: "/Temp/"
}

Feedback panel in viz.mediapipe.dev: 

Loader
Loaded graph '/runner/demos/blank_files/blank.pbtxt'.
Loader
Could not load trace '0.binarypb'.
Uploader
Could not load trace '0.binarypb': Unknown format

**Describe the expected behavior:**

I was hoping I would be able to upload and see the trace. 

**Standalone code to reproduce the issue:**

Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:

Insert the above block at the root of the top level graph for one of the examples. 

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

**Comment by sgowroji** [comment]
Hi @bschiett, Could you please attach/share your trace file. Thanks!

**Comment by chendadon** [comment]
Hi, im trying to profile the MPHolistic, can you please elaborate on where to put this code:
profiler_config {
trace_enabled: true
enable_profiler: true
trace_log_interval_count: 200
trace_log_path: "/Temp/"
}
?

Thx

**Comment by chendadon** [comment]
Any update?

**Comment by mhays-google** [comment]
Thanks for the patience.  I see this, no update yet.

**Comment by kuaashish** [comment]
Hello @bschiett,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
