### ISSUE TITLE
how build solution facemesh android

### ISSUE THREAD

**Issue by zhoujingheng** [google/mediapipe#2403]
![image](https://user-images.githubusercontent.com/12888787/129005212-2323c28f-d187-4874-aa4c-05776ddc07ae.png)

**Comment by sgowroji** [comment]
Hi @zhoujingheng, Could you please add the above required information to the exact reference issue. Otherwise, update the issue  with complete description.

**Comment by sgowroji** [comment]
Hi @zhoujingheng, We are working on it and will add the face mesh Android API solution in our GitHub repo in  next releases. At present we have updated the repo with only[ Hands solution ](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions)

**Comment by zhoujingheng** [comment]
> Hi @zhoujingheng, We are working on it and will add the face mesh Android API solution in our GitHub repo in next releases. At present we have updated the repo with only[ Hands solution ](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions)

Hi @sgowroji when release next repo about face mesh Android API solution

**Comment by sgowroji** [comment]
We will let you know with the ETA very soon.

**Comment by sgowroji** [comment]
Hi @zhoujingheng, FaceMesh Android solution are in Githubrepo at here **https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions** and please follow this [steps](https://google.github.io/mediapipe/getting_started/android_solutions.html) to work with it
