### ISSUE TITLE
KNIFT - Extracting boundbox locations in the image 

### ISSUE THREAD

**Issue by arijith96** [google/mediapipe#2406]
**System information** 

- OS Platform and Distribution : Linux Ubuntu 20.04.2 LTS to build aar and run on Android Studio with Gradle 
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.6
- Bazel version: bazel 4.1.0
- Solution (e.g. FaceMesh, Pose, Holistic): KNIFT
- Programming Language and version ( e.g. C++, Python, Java): Java

**GOAL:** 
As show in the multihands tracking demo/example app, I want to extract the pixel locations of the bounding box of the detected template.

For example if the 1 dollor note is detected - then I want to be able to get the float bounding box pixel locations - eg: 
x:50, y:50, w:600 ,h:200 for every frame that it is detected in.

**Work done until now:** 
I was able to make my own template and detect it on the video stream using the a build aar :) Just followed some [additional steps](https://github.com/google/mediapipe/issues/2397#issue-964654288) than the steps specified on [the MediaPipe website](https://google.github.io/mediapipe/getting_started/android_archive_library.html)

Next up, I made some changes to the template_matching.pbtxt to include an output_stream from the TimedBoxListToRenderDataCalculator as follows: (pasting the graph as a quote)

```
input_stream: "input_video"
output_stream: "output_video"

output_stream: "labeled_detections"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:detections"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "throttled_input_video"
  output_stream: "input_video_cpu"
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:input_video_cpu"
  output_stream: "IMAGE:transformed_input_video_cpu"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 640
      output_height: 640
      scale_mode: FILL_AND_CROP
    }
  }
}

node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE:transformed_input_video_cpu"
  output_stream: "SIZE:input_video_size"
}

node {
  calculator: "FeatureDetectorCalculator"
  input_stream: "IMAGE:transformed_input_video_cpu"
  output_stream: "FEATURES:features"
  output_stream: "LANDMARKS:landmarks"
  output_stream: "PATCHES:patches"
}


node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS:patches"
  output_stream: "TENSORS:knift_feature_tensors"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
      model_path: "mediapipe/models/knift_float.tflite"
      delegate { xnnpack {} }
    }
  }
}

node {
  calculator: "TfLiteTensorsToFloatsCalculator"
  input_stream: "TENSORS:knift_feature_tensors"
  output_stream: "FLOATS:knift_feature_floats"
}

node {
  calculator: "BoxDetectorCalculator"
  input_stream: "FEATURES:features"
  input_stream: "IMAGE_SIZE:input_video_size"
  input_stream: "DESCRIPTORS:knift_feature_floats"
  output_stream: "BOXES:detections"

  node_options: {
    [type.googleapis.com/mediapipe.BoxDetectorCalculatorOptions] {
      detector_options {
        index_type: OPENCV_BF
        detect_every_n_frame: 1
      }
      index_proto_filename: "mediapipe/models/knift_index.pb"
    }
  }
}

node {
  calculator: "TimedBoxListIdToLabelCalculator"
  input_stream: "detections"
  output_stream: "BOX_LIST:labeled_detections"

  node_options: {
    [type.googleapis.com/mediapipe.TimedBoxListIdToLabelCalculatorOptions] {
      label_map_path: "mediapipe/models/knift_labelmap.txt"
    }
  }
}

node {
  calculator: "TimedBoxListToRenderDataCalculator"
  input_stream: "BOX_LIST:labeled_detections"
  output_stream: "RENDER_DATA:box_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.TimedBoxListToRenderDataCalculatorOptions] {
      box_color { r: 255 g: 0 b: 0 }
      thickness: 5.0
    }
  }
}

node {
  calculator: "LandmarksToRenderDataCalculator"
  input_stream: "NORM_LANDMARKS:landmarks"
  output_stream: "RENDER_DATA:landmarks_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.LandmarksToRenderDataCalculatorOptions] {
      landmark_color { r: 0 g: 255 b: 0 }
      thickness: 2.0
    }
  }
}

node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  input_stream: "box_render_data"
  input_stream: "landmarks_render_data"
  output_stream: "IMAGE_GPU:output_video"
}

```

Basically creating an output_stream called _labeled_detections_ to be able to access the boundingbox packets.
Similar to how we are able to access the landmark packets from the output_stream in the demo/example applications.

I also changed some parts of the timed_box_list_id_to_label_calculator.cc to in-cooperate my changes:

-  TimedBoxListIdToLabelCalculator::GetContract 
`cc->Outputs().Tag("BOX_LIST").Set<TimedBoxProtoList>();
`

- TimedBoxListIdToLabelCalculator::Process
`cc->Outputs().Tag("BOX_LIST").Add(output_list.release(), cc->InputTimestamp());
`

Everything seems to be working, but I am stuck. Trying to access any data from the packet always leads to a crash.

`List<DetectionProto.DetectionList> detectionLists = PacketGetter.getProtoVector(packet, DetectionProto.DetectionList.parser());`

### Crash log:
```
2021-08-11 14:24:17.294 21000-32015/com.my.mediapipe.apps.myapplication E/libc++abi: terminating with uncaught exception of type absl::lts_2020_09_23::BadStatusOrAccess: Bad StatusOr access
    
    --------- beginning of crash
2021-08-11 14:24:17.294 21000-32015/com.my.mediapipe.apps.myapplication A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 32015 (Thread-6), pid 21000 (s.myapplication)
```

Would this be the correct approach to extract the bounding box locations when a template is matched? Please do guide me on the right track :)

**Comment by arijith96** [comment]
Closing this since I was able to make progress! :D Continuing in #2438

**Comment by thivux** [comment]
hey, I have the same problem, could you share your solution?
