### ISSUE TITLE
How not to rely on CDN for npm users (MediaPipe Pose solution)

### ISSUE THREAD

**Issue by TomHsiao1260** [google/mediapipe#2407]
I'm currently using the `MediaPipe Pose` solution to build a frontend Javascript application which use the `webpack` and `npm` to manage packages and build code. After following the [MediaPipe doc](https://google.github.io/mediapipe/solutions/pose), I successfully run an application. However, I believe there should be a better way to write the following lines of code for `npm` users because `npm` has already download the MediaPipe package in `node_modules` folder. It means that we don't need to access the MediaPipe CDN via http request.

```javascript
const pose = new Pose({locateFile: (file) => {
  return `https://cdn.jsdelivr.net/npm/@mediapipe/pose/${file}`;
}});
```

Question: For `npm` user, is there any better way to replace the code above?

**Comment by AmitMY** [comment]
With `webpack`, copy all files from `@mediapipe/pose` to some public directory, like `assets/pose` or something,

then, change the code to:
```js
const pose = new Pose({locateFile: (file) => `assets/pose/${file}`});
```

**Comment by sgowroji** [comment]
Thank you @AmitMY  for addressing the solution in the above [comment](https://github.com/google/mediapipe/issues/2407#issuecomment-899802882). @TomHsiao1260 Could you please try the above and let us know your observation.

**Comment by TomHsiao1260** [comment]
Yes, it works. Sorry for the late reply. Thanks @AmitMY, btw, the project you're working on looks great! I think I can close this issue now.
