### ISSUE TITLE
mediapipe/util/BUILD:67:1: C++ compilation of rule '//mediapipe/util:audio_decoder' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections

### ISSUE THREAD

**Issue by chen849157649** [google/mediapipe#241]
my OpenCV 4 is installed in “/usr/local/opencv4”, 
cc_library(
    name = "opencv",
    srcs = glob(
        [
            "local/opencv4/lib/libopencv_core.so",
            "local/opencv4/lib/libopencv_highgui.so",
            "local/opencv4/lib/libopencv_imgcodecs.so",
            "local/opencv4/lib/libopencv_imgproc.so",
            "local/opencv4/lib/libopencv_video.so",
            "local/opencv4/lib/libopencv_videoio.so",
        ],
    ),
   hdrs = glob(["local/opencv4/include/opencv4/**/*.h*"]),
   includes = ["local/opencv4/include/opencv4/"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
is ok? but error

**Comment by chen849157649** [comment]
and opencv install successfully, ipython can use

**Comment by jiuqiant** [comment]
For audio decoder, what you actually need is FFMpeg library. As a dependency of OpenCV3, FFMpeg is automatically installed by the package manager. You need to 1) find where the FFMpeg library is and 2) modify https://github.com/google/mediapipe/blob/master/third_party/ffmpeg_linux.BUILD accordingly.

**Comment by chen849157649** [comment]
@jiuqiant thank you, after modify ffmpeg_linux.BUILD, new error is bellow
/mediapipe/framework/formats/BUILD:163:1: C++ compilation of rule '//mediapipe/framework/formats:image_frame_opencv' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections 
could you help me? thank you

**Comment by chen849157649** [comment]
@jiuqiant thank you, new error is bellow
ERROR: /home/chengt1/mediapipe/mediapipe/framework/formats/BUILD:175:1: C++ compilation of rule '//mediapipe/framework/formats:location' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 70 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./mediapipe/framework/formats/location.h:39:0,
                 from mediapipe/framework/formats/location.cc:15:
./mediapipe/framework/port/opencv_core_inc.h:18:36: fatal error: opencv2/core/version.hpp: No such file or directory
compilation terminated.
but this version.hpp is exist,  /usr/local/opencv4/include/opencv4/opencv2/core/version.hpp,
when open ./mediapipe/framework/port/opencv_core_inc.h, this code is bellow, opencv version issue???
![微信截图_20191113135301](https://user-images.githubusercontent.com/32058220/68736935-03746780-061d-11ea-89fc-e4565e5c7a8f.png)
opencv_linux.BUILD 
![微信截图_20191113135445](https://user-images.githubusercontent.com/32058220/68737036-42a2b880-061d-11ea-9c59-1ede0d685c54.png)
ffmpeg_linux.BUILD 
![微信截图_20191113135510](https://user-images.githubusercontent.com/32058220/68737055-4f271100-061d-11ea-8256-517633f34302.png)
could you help me? thank you

**Comment by chen849157649** [comment]
@jiuqiant thank you very much, now successfully
