### ISSUE TITLE
Coral edgetpu Readme and support scripts outdated. 

### ISSUE THREAD

**Issue by mangodan2003** [google/mediapipe#2413]
Thank you for submitting a MediaPipe documentation issue.
The MediaPipe docs are open source! To get involved, read the documentation Contributor Guide
## URL(s) with the issue:

Please provide a link to the documentation entry, for example: 
https://github.com/google/mediapipe/tree/master/mediapipe/examples/coral

## Description of issue (what needs changing):

The above document and related scripts appear to be outdated.

**Comment by sgowroji** [comment]
Hi @mangodan2003, Could you please point us some observations which was felt like outdated. Thanks!

**Comment by mangodan2003** [comment]
Hi,
Certainly, to start with the docker file clones a repo (edgetpu) who's README implies it is deprecated:
https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/Dockerfile#L83

It seems that the repo to use is now https://github.com/google-coral/libedgetpu. But the structure of this repository is such that it can not just be used as a drop in replacement. I have tried adjusting the instructions but at this stage am not familiar enough with Bazel. Having updated the BUILD file to add 

```
"@edgetpu//:header",
  "@libedgetpu//:lib",
```
I have not yet managed to work out what needs to be added to the libedgetpu BUILD file to make it work. It appears I need to add a section for the headers but they are under a path (tflite/public) such that when I add the headers as tflite/public/edgetpu.h and tflite/public/edgetpu_c.h, Bazel outputs an error asking if I meant to include a colon in the name but I have not yet figured out quite what it means.

I also tried to carry on with the older repo (edgegpu) but I soon ran into the  problem that it seems to expect a file to exist that is no longer present in the (this) mediapipe one (I can't recall the exact filename but I think it was a bazel file with a suffix of 3).

Sorry this is mostly from memory as I was doing this last week. Please let me know if you want any more info.

**Comment by mangodan2003** [comment]
Additionally I wonder if some of the dependency information has changed. Prior to this I was able to build our mediapipe project that has been working with GPU and that I am adapting to use the TPU. It had been building but failing at runtime when using only the deps listed here : https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/BUILD#L54. I thought it strange as I expected it to need to link against the TPU library which initially build time was seemingly not trying to do. Having done some searches on the mediapipe repo tree I managed to figure out and added bunch of deps which then got it to try and use libedgedtpu library:

```
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/formats:image_frame",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
        "//mediapipe/graphs/face_detection:desktop_live_calculators",
        "//mediapipe/graphs/hand_tracking:mobile_calculators",
        "//mediapipe/calculators/image:image_transformation_calculator",
        "//mediapipe/calculators/tflite:tflite_converter_calculator",
        "//mediapipe/calculators/tflite:tflite_inference_calculator",
        "//mediapipe/calculators/tflite:ssd_anchors_calculator",
        "//mediapipe/calculators/tflite:tflite_tensors_to_detections_calculator",
        "//mediapipe/calculators/util:non_max_suppression_calculator",
```

and hence now I am stuck with the above build time errors.

**Comment by mangodan2003** [comment]
Thanks for the recent updates, we're up and running now.
