### ISSUE TITLE
What is the format of the output of pose landmarks?

### ISSUE THREAD

**Issue by methodistsmab** [google/mediapipe#2414]
I printed the output of the pose landmarks model.  Does anyone know what the format is? I checked the model card, which doesn't describe this format.  I think it is the output of Identity_4 type: float32[1,117] of the model.
It may be the format of (x, y, z). But how can I map these to the output frame. Why does the x,y be negative numbers sometimes?  Thanks!

Landmark[0]: (0.47486383, 0.25227875, -0.17895879)
Landmark[1]: (0.4604198, 0.24307497, -0.16582212)
Landmark[2]: (0.4582825, 0.24316975, -0.16596352)
Landmark[3]: (0.4559391, 0.24320316, -0.16606905)
Landmark[4]: (0.45820862, 0.24410447, -0.20432918)
Landmark[5]: (0.45454815, 0.24470194, -0.20423783)
Landmark[6]: (0.45060205, 0.2452729, -0.20422453)
Landmark[7]: (0.43832254, 0.252816, -0.051520564)
Landmark[8]: (0.4240227, 0.25566453, -0.22715442)
Landmark[9]: (0.47172514, 0.26616886, -0.13012235)
Landmark[10]: (0.46963263, 0.26610568, -0.18046837)
Landmark[11]: (0.51475626, 0.30781084, 0.0703094)
Landmark[12]: (0.34615046, 0.322188, -0.18687415)
Landmark[13]: (0.63332653, 0.3029296, 0.34561116)
Landmark[14]: (0.17944169, 0.3253369, -0.31346804)
Landmark[15]: (0.72120833, 0.29352397, 0.39342532)
Landmark[16]: (0.027733782, 0.33554405, -0.45015192)
Landmark[17]: (0.7635653, 0.29275042, 0.40283775)
Landmark[18]: (-0.015034198, 0.33914557, -0.46888113)
Landmark[19]: (0.7510496, 0.293271, 0.34849504)
Landmark[20]: (-0.019551842, 0.33862925, -0.52969223)
Landmark[21]: (0.7413893, 0.294527, 0.36567837)
Landmark[22]: (-3.144105E-4, 0.33802396, -0.4832858)
Landmark[23]: (0.52001196, 0.4947765, 0.091006756)
Landmark[24]: (0.4120663, 0.5014511, -0.09081388)
Landmark[25]: (0.73593396, 0.53762996, -0.13169469)
Landmark[26]: (0.27914077, 0.6254783, -0.18090267)
Landmark[27]: (0.7711724, 0.65827566, 0.12129098)
Landmark[28]: (0.15197755, 0.7387091, -0.027563829)
Landmark[29]: (0.7548465, 0.67911494, 0.14052708)
Landmark[30]: (0.14260848, 0.7498728, -0.023420937)
Landmark[31]: (0.8735644, 0.6782455, -0.04504627)
Landmark[32]: (0.13843806, 0.79158545, -0.28472036)

**Comment by sgowroji** [comment]
Hi @methodistsmab, We use those landmarks to get the valid  coordinates and draw the necessary part of the solution as per your requirement . Refer https://github.com/google/mediapipe/issues/1920#issuecomment-826954189 to understand more about it.

**Comment by methodistsmab** [comment]
Hi @sgowroji, thanks for your response. 
But I am still confused about that. According to #1920 , we can use the landmark to calculate the x, y. 
nose_x = results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].x * image_width
noses_y = results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].y * image_height

But sometimes, I got the landmark like Landmark[31] (1.8993026,0.3237356,-0.05541766), the x coordinate is greater than 1, which means the x coordinate is outside of the image.
However, sometimes, I got the landmark like Landmark[20]: (-0.019551842, 0.33862925, -0.52969223), the x coordinate is less than 0.
How to handle these kind of values of the landmarks?
Thanks!

**Comment by guker** [comment]
> Hi @sgowroji, thanks for your response.
> But I am still confused about that. According to #1920 , we can use the landmark to calculate the x, y.
> nose_x = results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].x * image_width
> noses_y = results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].y * image_height
> 
> But sometimes, I got the landmark like Landmark[31] (1.8993026,0.3237356,-0.05541766), the x coordinate is greater than 1, which means the x coordinate is outside of the image.
> However, sometimes, I got the landmark like Landmark[20]: (-0.019551842, 0.33862925, -0.52969223), the x coordinate is less than 0.
> How to handle these kind of values of the landmarks?
> Thanks!

no problem，because the input of blazepose is the affined image that centered on mid hip，so back to original image,  x or y may be greater than 1

**Comment by methodistsmab** [comment]
> > Hi @sgowroji, thanks for your response.
> > But I am still confused about that. According to #1920 , we can use the landmark to calculate the x, y.
> > nose_x = results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].x * image_width
> > noses_y = results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].y * image_height
> > But sometimes, I got the landmark like Landmark[31] (1.8993026,0.3237356,-0.05541766), the x coordinate is greater than 1, which means the x coordinate is outside of the image.
> > However, sometimes, I got the landmark like Landmark[20]: (-0.019551842, 0.33862925, -0.52969223), the x coordinate is less than 0.
> > How to handle these kind of values of the landmarks?
> > Thanks!
> 
> no problem，because the input of blazepose is the affined image that centered on mid hip，so back to original image, x or y may be greater than 1

Got it. Thank you so much!

**Comment by yogendra-yatnalkar** [comment]
> > Hi @sgowroji, thanks for your response.
> > But I am still confused about that. According to #1920 , we can use the landmark to calculate the x, y.
> > nose_x = results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].x * image_width
> > noses_y = results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].y * image_height
> > But sometimes, I got the landmark like Landmark[31] (1.8993026,0.3237356,-0.05541766), the x coordinate is greater than 1, which means the x coordinate is outside of the image.
> > However, sometimes, I got the landmark like Landmark[20]: (-0.019551842, 0.33862925, -0.52969223), the x coordinate is less than 0.
> > How to handle these kind of values of the landmarks?
> > Thanks!
> 
> no problem，because the input of blazepose is the affined image that centered on mid hip，so back to original image, x or y may be greater than 1

Hi, sorry but I did not understand this part. Can you please guide me on where I can read about this in more detail ?
