### ISSUE TITLE
Mediapipe installation problem

### ISSUE THREAD

**Issue by TAU20** [google/mediapipe#2415]
I have a problem installing Mediapipe from python (pip install mediapipe)

My Python version is: 3.7.9
I have installed cv2 in its version: 4.5.3

I hope you can help me, I am in trouble and I need urgent help, this depends on an institute job!
Write to the email if you cannot see the images: tomaslucero51@gmail.com

I am working on a hand detection program and my problem is the following, I will attach screenshots below:

![Imagendeerror](https://user-images.githubusercontent.com/88912841/129428738-2bdc048f-0093-4861-8b68-ca47dbf114fc.PNG)
![Imagendeerror2](https://user-images.githubusercontent.com/88912841/129429055-e9441066-bd36-44b0-9a38-b527311ae012.PNG)
![Imagendeerror3](https://user-images.githubusercontent.com/88912841/129429058-a6c329ec-58e1-4e45-bd7b-380b3d33c908.PNG)
![Imagendeerror4](https://user-images.githubusercontent.com/88912841/129429065-b15da934-30e1-4cd1-ac01-700fa0fc34d1.PNG)
![Imagendeerror5](https://user-images.githubusercontent.com/88912841/129429067-7dc07d6e-38f8-4730-a607-416f3b4f14ac.PNG)
![Imagendeerror6](https://user-images.githubusercontent.com/88912841/129429082-63734be7-0e16-4b93-bc39-b1ddce95b192.PNG)
![Imagendeerror7](https://user-images.githubusercontent.com/88912841/129429102-5d9fa2d4-de17-4dd2-9803-981c9b2d16a6.PNG)
![Imagendeerror8](https://user-images.githubusercontent.com/88912841/129429105-f20c4014-1480-42d7-970e-3484ed9067bd.PNG)
![Imagendeerror9](https://user-images.githubusercontent.com/88912841/129429112-9a58d760-7433-421b-b4a8-5434b0cca100.PNG)
![Imagendeerror10](https://user-images.githubusercontent.com/88912841/129429118-25e9ac5e-0d44-4b1f-af0e-7adedb402945.PNG)
![Imagendeerror11](https://user-images.githubusercontent.com/88912841/129429123-c7545951-c109-453c-8e6c-5d8e0649d7c1.PNG)
![Imagendeerror12](https://user-images.githubusercontent.com/88912841/129429132-b57fae41-ac80-4b61-9c7e-fda7686def6f.PNG)
![Imagendeerror13](https://user-images.githubusercontent.com/88912841/129429135-7123c26b-67c5-4fe5-b7af-ef0a1cf0f5fd.PNG)

Thanks a lot

**Comment by sgowroji** [comment]
Hi @TAU20, Could you please provide the steps to reproduce the above error and also share the machine configuration to try on it. Thanks!
