### ISSUE TITLE
a error:  recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/loadsave.cpp.o' failed

### ISSUE THREAD

**Issue by only-tao** [google/mediapipe#2416]
**System information** 
- OS Platform and Distribution :   Ubuntu 18.04, jetson xavier):
- Programming Language and version : python 3.8.10

- Bazel version: bazel 3.7.2

 when I install it, the problem occurs to me;

when I use   `python setup.py install`  , the return is build did not completed successfully

some of errors are as follows: 

`DEBUG: /home/nx/.cache/bazel/_bazel_nx/51a49d8cb6e40c6c7dc46859614a04eb/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Analyzed target //mediapipe/modules/face_detection:face_detection_short_range_cpu (116 packages loaded, 18004 targets configured).
INFO: Found 1 target...
ERROR: /home/nx/mambaforge/envs/pp/lib/python3.8/site-packages/mediapipe/third_party/BUILD:97:15: CcCmakeMakeRule third_party/opencv_cmake/include failed (Exit 2): CMake_wrapper_script.sh failed: error executing command bazel-out/aarch64-opt/bin/third_party/opencv_cmake_scripts/CMake_wrapper_script.sh

Use --sandbox_debug to see verbose messages from the sandbox CMake_wrapper_script.sh failed: error executing command bazel-out/aarch64-opt/bin/third_party/opencv_cmake_scripts/CMake_wrapper_script.sh

Use --sandbox_debug to see verbose messages from the sandbox
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:`

**and next**

`/usr/include/OpenEXR/ImathVec.h:444:37: error: ISO C++1z does not allow dynamic exception specifications
     Vec3<T>  normalizedExc () const throw (IEX_NAMESPACE::MathExc);`

**then**

`modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/build.make:81: recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/loadsave.cpp.o' failed
make[2]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/loadsave.cpp.o] Error 1
CMakeFiles/Makefile2:1772: recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all' failed
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
Makefile:181: recipe for target 'all' failed
make: *** [all] Error 2
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/aarch64-opt/bin/third_party/opencv_cmake_scripts/CMake_wrapper_script.sh
rules_foreign_cc: Build script location: bazel-out/aarch64-opt/bin/third_party/opencv_cmake_scripts/CMake_script.sh
rules_foreign_cc: Build log location: bazel-out/aarch64-opt/bin/third_party/opencv_cmake_logs/CMake.log

Target //mediapipe/modules/face_detection:face_detection_short_range_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.`

I don't know  how to solve it. Thanks for your help.

**Comment by sgowroji** [comment]
Hi @only-tao, Could you please provide the steps to reproduce the above error . Thanks!

**Comment by only-tao** [comment]
I success the installation
