### ISSUE TITLE
hi , I want to train the model to another part of the body , How can i label the raw material to retrain the model 

### ISSUE THREAD

**Issue by NourOmran** [google/mediapipe#2417]
Thank you for submitting a MediaPipe documentation issue.
The MediaPipe docs are open source! To get involved, read the documentation Contributor Guide
## URL(s) with the issue:

Please provide a link to the documentation entry, for example: https://github.com/google/mediapipe/blob/master/docs/solutions/face_mesh.md#models

## Description of issue (what needs changing):

Kinds of documentation problems:

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined
Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,

### Usage example

Is there a usage example?

See the API guide:
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
https://github.com/google/mediapipe/blob/master/CONTRIBUTING.md

**Comment by sgowroji** [comment]
Hi @NourOmran, Could you please provide complete details in the above issue to address your query. Thanks!
