### ISSUE TITLE
When will the iris be available for Python? Looking forward to it!

### ISSUE THREAD

**Issue by TommyZihao** [google/mediapipe#2418]
When will the iris be available for Python? Looking forward to it!

**Comment by sgowroji** [comment]
Hi @TommyZihao, We don't have any plans as of now, but there are many solutions shared in the community by different contributors. I will add some here where you can use as per your requirement. https://github.com/google/mediapipe/issues/2254#issuecomment-880980304
https://github.com/google/mediapipe/issues/1530#issuecomment-790210796
