### ISSUE TITLE
How to set SMOOTH_LANDMARKS 

### ISSUE THREAD

**Issue by InvisibleLeVen** [google/mediapipe#2419]
How to set STATIC_IMAGE_MODE, MODEL_COMPLEXITY, SMOOTH_LANDMARKS, MIN_DETECTION_CONFIDENCE, MIN_TRACKING_CONFIDENCE in the desktop c++ ​​program in pose_tracking demo

**Comment by sgowroji** [comment]
Hi @InvisibleLeVen,  Below points to the graph changes where you can set them in your graph and build for desktop. 
For [cpu](https://github.com/google/mediapipe/blob/a9b643e0f5978425d948050a2228398929733d05/mediapipe/modules/pose_detection/pose_detection_cpu.pbtxt#:~:text=%7D-,%23%20Decodes%20the%20detection%20tensors%20generated%20by%20the%20TensorFlow%20Lite%20model,%7D,-%23%20Performs%20non-max) and [gpu](https://github.com/google/mediapipe/blob/b544a314b3c4818a4d6c56964b020c5be945377a/mediapipe/modules/pose_detection/pose_detection_gpu.pbtxt#:~:text=%7D-,%23%20Decodes%20the%20detection%20tensors%20generated%20by%20the%20TensorFlow%20Lite%20model,%7D,-%23%20Performs%20non-max)

**Comment by InvisibleLeVen** [comment]
@sgowroji 
Just need to set it like the following in the configuration file?
`
# Whether to filter landmarks across different input images to reduce jitter.
# If unspecified, functions as set to true. (bool)
input_side_packet: "SMOOTH_LANDMARKS:false"

# Complexity of the pose landmark model: 0, 1 or 2. Landmark accuracy as well as
# inference latency generally go up with the model complexity. If unspecified,
# functions as set to 1. (int)
input_side_packet: "MODEL_COMPLEXITY:model_complexity"
`

**Comment by InvisibleLeVen** [comment]
> @sgowroji
> Just need to set it like the following in the configuration file?
> 
> ```
> # Whether to filter landmarks across different input images to reduce jitter.
> # If unspecified, functions as set to true. (bool)
> input_side_packet: "SMOOTH_LANDMARKS:false"
> 
> # Complexity of the pose landmark model: 0, 1 or 2. Landmark accuracy as well as
> # inference latency generally go up with the model complexity. If unspecified,
> # functions as set to 1. (int)
> input_side_packet: "MODEL_COMPLEXITY:0"
> ```

Get configuration file parsing error

**Comment by InvisibleLeVen** [comment]
https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_cpu.pbtxt
According to the example in the comment, model_complexity, smooth_landmarks, enable_segmentation, and smooth_segmentation can be set through input_side_packet. How to set the two parameters of MIN_DETECTION_CONFIDENCE and MIN_TRACKING_CONFIDENCE? Are these two parameters currently supported in C++ desktop applications?

**Comment by gb2111** [comment]
@sgowroji @hadon 
I am also curious how that can be set. This is possible in python so it should be also in C++ I guess. 
Let me know what's the status of that ?
Greg

**Comment by LQ921003** [comment]
How to set this value, is there an answer?

**Comment by JHshen0124** [comment]
I have the same problem

**Comment by shrey-rootally** [comment]
Is there any solution yet?

**Comment by sgowroji** [comment]
You can set similar configurations by this python platforms values. For GPU please see the appropriate calculators. 
          

[min_score_thresh](https://github.com/google/mediapipe/blob/d4bb35fe5a44b3419ca86e4c7ecbc931dded2122/mediapipe/modules/palm_detection/palm_detection_gpu.pbtxt#:~:text=min_score_thresh%3A%200.5)':
                min_detection_confidence,
           


 ThresholdingCalculator.[threshold](https://github.com/google/mediapipe/blob/6abec128edd6d037e1a988605a59957c22f1e967/mediapipe/modules/pose_landmark/tensors_to_pose_landmarks_and_segmentation.pbtxt#:~:text=%7D-,%23%20Applies%20a%20threshold%20to%20the%20confidence%20score%20to%20determine%20whether,%7D,-%23%20Drops%20input%20tensors)':
                min_tracking_confidence,

**Comment by shrey-rootally** [comment]
can these parameters accessed on iOS platforms?
