### ISSUE TITLE
Face mesh landmark points for nose when draw connections

### ISSUE THREAD

**Issue by junnikokuki** [google/mediapipe#2420]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):
- Programming Language and version ( e.g. C++, Python, Java):

**Describe the expected behavior:**

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

I want to draw the outer nose when using face mesh landmarks. There are points in face_landmarks_to_render_data_calculator.cc file that can connect lips, eyes and eyebrows, but no for nose. Are there nose points for the 468 face landmarks? Thank you.

**Comment by mhays-google** [comment]
I'll talk to the team about formally exposing a set of nose connections, but you can already use the points to define your own outline.  You'll see that I just record the points as a set of array pairs specifying starting point and ending point.
