### ISSUE TITLE
there is no "mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD." path as writen in documentation

### ISSUE THREAD

**Issue by arianatri** [google/mediapipe#2421]
## URL(s) with the issue:

https://google.github.io/mediapipe/getting_started/android_archive_library.html

## Description of issue (what needs changing):

there is not path : mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD.
as said in doc :
"In the MediaPipe directory, create a new mediapipe_aar() target in a BUILD file. You need to figure out what calculators are used in the graph and provide the calculator dependencies to the mediapipe_aar(). For example, to build an AAR for MediaPipe Face Detection, you can put the following code into mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD."

Am I wrong and I should create that directory and BUILD file on my own?

**Comment by jiuqiant** [comment]
You need to create a new directory.
