### ISSUE TITLE
Holistic v0.3 -> v0.4 breaking change

### ISSUE THREAD

**Issue by AmitMY** [google/mediapipe#2422]
**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): **Windows 10**
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: **Chrome**
- Programming Language and version ( e.g. C++, Python, Java): **Javascript**
- Solution ( e.g. FaceMesh, Pose, Holistic ): **Holistic** 

**Describe the current behavior:**
After upgrading from v0.3.1620694839 to any version v0.4+, the pose predicted just flies of-screen.

Here is the current behavior with v0.4+

https://user-images.githubusercontent.com/5757359/129485105-e9d13615-79e6-4369-bded-63c38841cee7.mp4

**Describe the expected behavior:**

The expected behavior, like v0.3:

https://user-images.githubusercontent.com/5757359/129485091-e601e2c7-a57b-495b-b6fe-2d8f9fe11822.mp4

**Standalone code to reproduce the issue:**

In this repository: https://github.com/sign-language-processing/playground
- Change the `@mediapipe/holistic` version from `^0.3.1620694839` to `0.4.1628005088`
- Run `npm start`
- Go to `localhost:4200/playground`

**Comment by mhays-google** [comment]
I'm not a fan of this policy, but our team has decided that the minor version denotes breaking changes, not the major version.

However, I don't remember anything that would cause poses to fly away like this.  There is a locateFile method you may have supplied during initialization.  Is it possible that this hasn't been updated to reflect the new version?

**Comment by mhays-google** [comment]
I'd like to figure out why your demo is behaving the way it is.  If it's a problem on our end, I'd like to fix it quickly.

Nice demo, btw.

**Comment by AmitMY** [comment]
> I'm not a fan of this policy, but our team has decided that the minor version denotes breaking changes, not the major version.
> 
> However, I don't remember anything that would cause poses to fly away like this. There is a locateFile method you may have supplied during initialization. Is it possible that this hasn't been updated to reflect the new version?

For `locateFile`, all files are actually located locally - 
https://github.com/sign-language-processing/playground/blob/master/src/app/modules/pose/pose.service.ts#L16
After they are copied during the build process - 
https://github.com/sign-language-processing/playground/blob/master/angular.json#L24

This is to make the app able to work completely offline using service workers etc...

With this local setting, there are no network issues, meaning, it loaded all files as expected.
![image](https://user-images.githubusercontent.com/5757359/129670171-792039ca-993b-4b9e-833a-6f735a53ada4.png)

I have changed it to `https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.4/`, but the behavior repeats.
(despite being the same `locateFile`, and network requests log as the codepen)


> I'd like to figure out why your demo is behaving the way it is. If it's a problem on our end, I'd like to fix it quickly.
> 
> Nice demo, btw.

Thanks!
I'm using your drawing utils, so I don't think it is a problem in the drawing itself. Not sure about anything else...

**Comment by mhays-google** [comment]
I tried the online holistic demo at code.mediapipe.dev/codepen/holistic,
and I replaced the version with 0.3 and with 0.4.  Both work pretty much
identically.

If it were not just a version number change, my initial reaction is that
there is a canvas scale happening without calls to canvas.save or
canvas.restore.  Can you verify this in your own drawing code?

**Comment by AmitMY** [comment]
Thanks.
The input video is not scaled or anything, it is just a video element, sent to holistic.
The output canvas is scaled using a css transform, but even after removing that, the problem persists.

(But because the input is a video, and no manipulation is done on the video, I see no reason why anything on the canvas will be an issue)

Here is a print of the location of the nose through each frame: (notice how it explodes)
![image](https://user-images.githubusercontent.com/5757359/129775509-36d3f07e-0676-43f6-8974-ca43a6602fd7.png)

**Comment by mhays-google** [comment]
I'm simply not able to recreate this with our own demo code, and I feel
like I'm guessing.  The positions returned in the solution are normalized
(0..1) though, so the values you are printing out have been multiplied by
something.  Can you check the results as they are returned?

**Comment by AmitMY** [comment]
Unfortunately, not only `[0, 1]` values are returned.
The reason is some kind of change in the way the `image` is returned, I think. 
I am storing that canvas reference in a store (using `ngxs`), and that is the additional factor...

My current fix:
https://github.com/sign-language-processing/playground/commit/f43dce163e71702793a4eec5fc47f98c939cd80c#diff-234795a41fd0cddbe6708c29494ba2caf76de81e3fc82c0294394dce2ec968dcR52-R59

I'm closing it, as it's most likely not a bug with holistic. most likely :)

**Comment by mhays-google** [comment]
Ok, good luck!
