### ISSUE TITLE
Can't run hair_segmentation default example due to a graph error.

### ISSUE THREAD

**Issue by betogaona7** [google/mediapipe#2427]
Hi, I followed the steps to install mediapipe successfully, compiled hair_sementation with the following command: 

```
bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
  mediapipe/examples/desktop/hair_segmentation:hair_segmentation_gpu
```

and there were no problems. Then I tried to run the example with the following command:

```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hair_segmentation/hair_segmentation_gpu \
  --calculator_graph_config_file=mediapipe/graphs/hair_segmentation/hair_segmentation_desktop_live.pbtxt
```

And I am getting the following error: 

```
pipe.CalculatorGraphConfig: 116:5: text format contains deprecated field "use_gpu"
I20210816 22:14:20.232578 146876 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
I20210816 22:14:20.233274 146876 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
I20210816 22:14:20.240236 146876 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I20210816 22:14:20.254871 146885 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 470.57.02)
I20210816 22:14:20.254938 146876 demo_run_graph_main_gpu.cc:68] Initialize the camera or load the video.
I20210816 22:14:25.383385 146876 demo_run_graph_main_gpu.cc:89] Start running the calculator graph.
I20210816 22:14:25.383548 146876 demo_run_graph_main_gpu.cc:94] Start grabbing and processing frames.
E20210816 22:14:26.000962 146876 demo_run_graph_main_gpu.cc:197] Failed to run the graph: Graph has errors: 
Packet type mismatch on calculator outputting to stream "input_video": The Packet stores "mediapipe::GpuBuffer", but "mediapipe::ImageFrame" was requested.
```
I haven't performed any changes to the graph neither to the code. I would like to be able to run the default example, so I can experiment with it to read an image instead of a video, but I haven't found useful information to solve it. Could someone please help to understand how to fix it? 

I have Ubuntu 20.04.2 LTS and trying to run the desktop example.

To reproduce the issue just install mediapipe ([link](https://google.github.io/mediapipe/getting_started/install.html)), compile hair segmentation, and try to run the default example.

**Comment by betogaona7** [comment]
Closing this issue since I found a solution. Thank you! :smile:

**Comment by matildao-pane** [comment]
Hi can you share your solution to this issue please?
