### ISSUE TITLE
How to set min_detection_confidence and min_tracking_confidence attribute

### ISSUE THREAD

**Issue by ljmkimqx** [google/mediapipe#2428]
How to set min_detection_confidence and min_tracking_confidence attribute values on the mobile terminal of gesture recognition? I can't find anything to change.

I've seen modules / hand_ landmark/hand_ landmark_ Gpu.pbtxt file and modules / hand_ landmark/hand_ landmark_ tracking_ Gpu.pbtxt file, but I still don't know how to modify it.

thanks

**Comment by ljmkimqx** [comment]
Is there any way to set it?

**Comment by LQ921003** [comment]
Hi @ljmkimqx , #2376
