### ISSUE TITLE
Android apk can not run. When I open Hand Tracking GPU app on my phone, I can only see the three words "Hand Tracking GPU" on the top, but the window is black.

### ISSUE THREAD

**Issue by Sara533** [google/mediapipe#243]
I build the android hand tracking example base on the instruction. And I get the handtrackinggpu.apk successfully. But after I install the apk into my phone, I can just see a black window just with the app name Hand Tracking GPU. I don't know why. Does anyone meet the same problem?
By the way, I have tried to install the open source hand tracking 2d and 3d apks. They are both OK.

**Comment by eknight7** [comment]
> By the way, I have tried to install the open source hand tracking 2d and 3d apks. They are both OK.
Which one does work for you and which one does not? Can you share details about which Android device your are using?
