### ISSUE TITLE
error:could not con ＇result' from 'std: :unique_ptr <nediapipe: : {anonymous}::GlProcessor,std::default_delete<mediapi ｛anonymous} : : GLProcessor> > 

### ISSUE THREAD

**Issue by only-tao** [google/mediapipe#2430]
I have got the cpu version mediapipe , but now I want to get the gpu version 
then
I follow the #1042 ,

add the 
`--copt=-DMESA_EGL_NO_X11_HEADERS --copt=-DEGL_NO_X11`
in two places,
but I get a error:
when I run the code:
`python3 setup.py gen_protos && python3 setup.py bdist_wheel
`

the error like this :
`nx@nx-desktop: -/mediapipe
／usr/bin/gcc-U_FORTIFY_SOURCE-fstack-protector-Wall-Wunused-but-set-parameter -Wno-free-nonh
－object-fno-omit-frame-pointer -gθ -02 '-D_FORTIFY_SOURCE=1' -DNDEBUG-ffunction-sections. . . (r
ining 69 argument (s) skipped)

Use--sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command
r/bin/gcc -U FORTIFY SOURCE -fstack-protector -Wall -Wunused-but-set-parameter-Wno-free-nonheap
ect-fno-omit-frame-pointer-g0-02 '-D_FORTIFY_SOURCE=1'-DNDEBUG -ffunction-sections. . . (remai
g 69 argument (s) skipped)

Use--sandbox_debug to see verbose messages fron the sandbox
mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc: In function 'absl: :lts_2020
23: : StatusOr <std: :unique_ptr <mediapipe: : ImageToTensorConverter> > mediapipe: : CreateImageToGLBuff
nsorConverter (mediapipe: : CalculatorContext*,bool,mediapipe: : BorderMode) ':
mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.ck: 342: 10:error:could not con
＇result' from 'std: :unique_ptr <nediapipe: : {anonymous}::GlProcessor,std::default_delete<mediapi
｛anonymous} : : GLProcessor> > 「to 'absl: :lts_2020_09_23: : Status0r <std: :unique_ptr <mediapipe: : Image
nsorConverter> >
return result;
Target//mediapipe/modules/face_detection:face_detection_short_range_cpu failed to build
ICes to see the command Lines of failed build steps.
`
How can I do next？

in jeton xavier ubuntu 18.04
bazel 4.0.0

**Comment by sgowroji** [comment]
Hi @only-tao, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by only-tao** [comment]
First, I follow the [Official Tutorials](https://github.com/jiuqiant/mediapipe_python_aarch64) get the cpu version .wheel file , and next I want to get the gpu version, so 
I just follow the [#1042 ](https://github.com/google/mediapipe/issues/1042), change the file -> mediapipe/setup.py,


then run 
`~/mediapipe $ python3 setup.py gen_protos && python3 setup.py bdist_wheel
 ` 
after a few minutes , I got the error above

**Comment by sgowroji** [comment]
Hi @only-tao, Can you try to  update GCC version and check the above. Have a look at this #1684 (comment)

**Comment by HahaOptimus2** [comment]
Hi @only-tao ，I met the same error，could you share how you fixed this problem?
