### ISSUE TITLE
Build aar file gives an error : clang: error: no such file or directory: '/w' clang: error: no such file or directory: '/D_USE_MATH_DEFINES'

### ISSUE THREAD

**Issue by arianatri** [google/mediapipe#2433]
I ran this command : 

`bazel build -c opt --strip=ALWAYS --incompatible_restrict_string_escapes=false --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aarexample:mediapipe_face_detection.aar
`
Error :

```
ERROR: C:/users/airan/_bazel_airan/q54j5q7i/external/XNNPACK/BUILD.bazel:3803:19: Compiling src/f32-dwconv2d-chw/gen/3x3p1-minmax-scalar-1x1-acc2.c failed: (Exit 1): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/clang -D__ANDROID_API__=29 -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target ... (remaining 95 argument(s) skipped)
clang: error: no such file or directory: '/w'
clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aarexample:mediapipe_face_detection.aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 129.535s, Critical Path: 63.41s
INFO: 294 processes: 135 internal, 150 local, 9 worker.
FAILED: Build did NOT complete successfully
```

**Comment by arianatri** [comment]
on second run i got this error! :
ERROR: C:/users/airan/_bazel_airan/q54j5q7i/external/ruy/ruy/BUILD:585:11: Compiling ruy/pack_arm.cc failed: (Exit 1): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/clang -D__ANDROID_API__=29 -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target ... (remaining 57 argument(s) skipped)
clang: error: no such file or directory: '/w'
clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
**clang: error: no such file or directory: '/std:c++17'**
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aarexample:mediapipe_face_detection.aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 15.118s, Critical Path: 12.77s
INFO: 143 processes: 129 internal, 14 local.
FAILED: Build did NOT complete successfully

**Comment by arianatri** [comment]
NVM... just found out that mediapipe is incompatible with windows... :(
can anyone give me the AAR file, graphs, and Tflite model of Face Mesh?
the models uploaded in GitHub are all outdated.

**Comment by sgowroji** [comment]
Hi @arianatri, We have recently released the [Android FaceMesh API](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions) solutions in our repo . This are [steps](https://google.github.io/mediapipe/getting_started/android_solutions.html) to work  with it. And if you still looking for AAR, have a look at this https://github.com/jiuqiant/mediapipe_face_detection_aar_example

**Comment by arianatri** [comment]
I used this and got a bunch of errors and performance failures(mentioned these on another issue).
