### ISSUE TITLE
Image with no Face causes the function to stuck forever

### ISSUE THREAD

**Issue by 201724468** [google/mediapipe#2434]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):  Linux Ubuntu
- Programming Language and version ( e.g. C++, Python, Java):  C++
- [MediaPipe version](https://github.com/google/mediapipe/releases): recent one
- Bazel version (if compiling from source): updated version
- Solution ( e.g. FaceMesh, Pose, Holistic ): IRIS

**Describe the current behavior:**
I'm using jpg to detect iris and when I put few images with faces, it detects iris really well.
however, when I put images without face(just a background or empty image), it stucks or hangs on Next() function where
it locates /mediapipe/mediapipe/framework/graph_output_stream.cc

**Describe the expected behavior:**
If there is no face, just pass it

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

`if (!poller_face_landmark.Next(&face_landmark_packet)) break ;`

this is the code I have and it stucks down below
 ```
while (true) {
    min_timestamp = input_stream_->MinTimestampOrBound(&empty_queue);
    std::cout << min_timestamp << "\n";
    if (graph_has_error_ || !empty_queue ||
        min_timestamp == Timestamp::Done()) {
      break;
    } else {
      handler_condvar_.Wait(&mutex_);
    }
  }
```

**Comment by kuaashish** [comment]
Hello @201724468,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
