### ISSUE TITLE
How to combine two or more functions in one android apk? Is there any example?

### ISSUE THREAD

**Issue by Ar4enal** [google/mediapipe#2435]
**System information** 
- OS Platform and Distribution:  Linux Ubuntu
- Solution: FaceMesh, FaceDetection, Iris
- Programming Language and version: Java Android

I am using aar to build the new apk but I do not konw how to code in MainActivity.java, such as processor part and display view part.

`processor =
                new FrameProcessor(
                        this,
                        eglManager.getNativeContext(),
                        BINARY_GRAPH_NAME,
                        INPUT_VIDEO_STREAM_NAME,
                        OUTPUT_VIDEO_STREAM_NAME);`

I need to get those landmarks using packetCallback function.
Is there any example I can read?

**Comment by sgowroji** [comment]
Hi @Ar4enal, You can have a look at our Android API [solutions](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions) which are released recently.  You can combine other solutions in it.

**Comment by Ar4enal** [comment]
> Hi @Ar4enal, You can have a look at our Android API [solutions](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions) which are released recently. You can combine other solutions in it.

Hi sgowroji, I want to know the data format of face detection.  Like face mesh landmarks, I can get them by landmark.getX() getY() getZ().  

_Collection of detected faces, where each face is represented as a detection proto message that contains a bounding box and 6 key points (right eye, left eye, nose tip, mouth center, right ear tragion, and left ear tragion)._ 

How can I get the nose tip landmark?  By using which function. Thank u~

**Comment by sgowroji** [comment]
Here we log the [nose landmarks ](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/solutions/facemesh/src/main/java/com/google/mediapipe/examples/facemesh/MainActivity.java#:~:text=%7D-,private%20void%20logNoseLandmark(FaceMeshResult%20result%2C%20boolean%20showPixelValues)%20%7B,%7D,-%C2%A9%202021%20GitHub%2C%20Inc).
