### ISSUE TITLE
Is it possible to set calculator options dynamically (run time)?

### ISSUE THREAD

**Issue by OleslavIntellias** [google/mediapipe#2436]
Hi,
I am new at Google Mediapipe technology and interesting in calculator properties. So in my project we need to change treshhold dynamicly depends on general video luminance. Could you explain is it possible is it possible to set calculator options dynamically (run time)? And how?

**Comment by sgowroji** [comment]
Hi @OleslavIntellias, Could you please elaborate your use case with more details. Thanks!

**Comment by OleslavIntellias** [comment]
Well, the main idea is to modify the treshhold for each frame in case the brigtness is weak enough or, on the contrary, too strong. If the brigtness is good, leave the threshhold high enough so that the mediapipe does not recognize foreign objects. My question is how it would be possible to dynamically change the threshhold (**min_score_thresh** parameter in the **TensorsToDetectionsCalculatorOptions** that are passed to the **TensorsToDetectionsCalculator**).

**P.S.** As I can see the TensorsToDetectionsCalculatorOptions class has setters and getters for each parameter.
```
  public:

  // optional float min_score_thresh = 19;
  bool has_min_score_thresh() const;
  private:
  bool _internal_has_min_score_thresh() const;
  public:
  void clear_min_score_thresh();
  float min_score_thresh() const;
  void set_min_score_thresh(float value);
  private:
  float _internal_min_score_thresh() const;
  void _internal_set_min_score_thresh(float value);
  ```
**P.S. P.S.** I found an explanation in the documentation that can be done. But I still have no practical idea of how it could be implemented. https://google.github.io/mediapipe/getting_started/faq.html#:~:text=Send%20new%20calculator%20options%20through%20packets%20on%20graph%20input-streams

**Comment by sgowroji** [comment]
Hi @OleslavIntellias,  You can do the changes in the [graph](https://github.com/google/mediapipe/blob/b544a314b3c4818a4d6c56964b020c5be945377a/mediapipe/modules/pose_detection/pose_detection_gpu.pbtxt#:~:text=%7D-,%23%20Decodes%20the%20detection%20tensors%20generated%20by%20the%20TensorFlow%20Lite%20model,%7D,-%23%20Performs%20non-max)  at min_score_thresh: 0.5 , Which sets the min_detection_confidence.

**Comment by OleslavIntellias** [comment]
Hi @sgowroji,
I

**Comment by OleslavIntellias** [comment]
Hi, @sgowroji, 
You're right so I can do it. I want to know if you can set this value dynamically.

**Comment by OleslavIntellias** [comment]
@hadon, @sgowroji, Could anybody help me with this issue?

**Comment by OleslavIntellias** [comment]
But as i can see in the TensorsToDetectionsCalculatorOptions class has setters and getters for each parameter.  Maybe is it possible to set new options in previous calculator for next one? 
```
  public:

  // optional float min_score_thresh = 19;
  bool has_min_score_thresh() const;
  private:
  bool _internal_has_min_score_thresh() const;
  public:
  void clear_min_score_thresh();
  float min_score_thresh() const;
  void set_min_score_thresh(float value);
  private:
  float _internal_min_score_thresh() const;
  void _internal_set_min_score_thresh(float value);
```

**Comment by kuaashish** [comment]
Hello @OleslavIntellias,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by fchen09** [comment]
@OleslavIntellias
I need to change the options at runtime as well. Have you found the way? Thanks.
