### ISSUE TITLE
How to create iOS FrameWork from mediapie

### ISSUE THREAD

**Issue by danSamSet** [google/mediapipe#2437]
I try to use Mediapipe in my ios project. 

I have run the sample app with bazel. Now I want to create file framework and add to my current project. 

I have try to find the solulution but all of them not work for me. 

I really want to be instructed how to create iOS Framework step by step. Thank you.

**Comment by sgowroji** [comment]
Here are the clear steps for IOS solutions https://google.github.io/mediapipe/getting_started/ios.html#mediapipe-on-ios. Please let me know, if you have any specific query. Thanks!
