### ISSUE TITLE
Building KNIFT knift_index.pb on mobile device

### ISSUE THREAD

**Issue by arijith96** [google/mediapipe#2438]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): Yes. #2406 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):  Ubuntu 20.02 Android 11 Android Studio with Gradle
- [MediaPipe version](https://github.com/google/mediapipe/releases):v0.8.6
- Bazel version:4.1.0
- Solution (e.g. FaceMesh, Pose, Holistic): KNIFT
- Programming Language and version ( e.g. C++, Python, Java): Java

**Describe the expected behavior:**
I made progress in regards to #2406 and am now able to extract the bounding box pixel locations. 

I wanted to know if there is a way to create the knift_index.pb on the mobile device itself. How could I go about doing this? 
The idea would be to take a picture on the mobile phone and then make the knift_index.pb file and the supply it to the KNIFT solution to perform detection. I would need some guidance to go about this.

Thank you in advance! :)

**Comment by arijith96** [comment]
Hi! @yegenzhi 
Any update on this?

**Comment by yegenzhi** [comment]
We don't have an official supported way to build index on mobile device yet.
However, you can try to build the binary and adb push both the binary and graph to you device, and test if you can run it there.
Hope it helps.

**Comment by arijith96** [comment]
Thank you for your quick response :) I will try this sometime in the upcoming weeks. I will keep my progress updated in this issue 👍

**Comment by arijith96** [comment]
Unfortunately, I could not work on this for the moment. If I do work on this and run into any issues, I will re-open :) 
Thanks! @sgowroji @yegenzhi
