### ISSUE TITLE
Mediapipe Hands (Android) : Does the scale of z value (relative depth) vary according to the depth from the hand to the camera?

### ISSUE THREAD

**Issue by caiyc2000** [google/mediapipe#2439]
Hi team, thanks for your great work!
I' m working on the hand tracking model on Android and a bit confused about the z value of the landmark.
In the documentation, z value means the relative depth with the depth at the wrist at the origin. So my question is, if my hand is at a different distance from the camera, but the distance from the fingertip of my index finger to the wrist is the same, is the z value of the fingertip of my index finger still the same? Or does the z value vary according to the depth from the hand to the camera?
Thanks in advance!

**Comment by sgowroji** [comment]
For Z value in Hands solutions https://github.com/google/mediapipe/issues/742#issuecomment-637162399

**Comment by caiyc2000** [comment]
@sgowroji Thanks for your response. But I think #742 hasn' t solved my problem.
I now assume two situations. 
If my hand movements are the same, but the absolute distance between the wrist and the camera is different, are the z-coordinates of other points the same except for the wrist in these two cases? 
In other words, does the absolute depth affect the relative depth?

**Comment by caiyc2000** [comment]
I know the z value stands for relative depth according to the wrist.

**Comment by bazarevsky** [comment]
Hello,
if the hand pose is the same, relative distance would not change if you move hand closer or further from the camera. So, absolute depth does influence on relative distance. However, of course due to the nature of machine learning, there might be some fluctuations in prediction.
