### ISSUE TITLE
youtube8m feature extractor speed with GPU

### ISSUE THREAD

**Issue by chen849157649** [google/mediapipe#244]
GPU with NVIDIA EGL driver support,  command is bellow:
sudo bazel run --copt -DMESA_EGL_NO_X11_HEADERS  mediapipe/examples/desktop/youtube8m:extract_yt8m_features
speed is slow, In fact, it's still CPU. Can I use GPU to extract video features? Can you give me some advice ? thank you

**Comment by mgyong** [comment]
@chen849157649 The machine learning inference for desktop is only CPU and we don't support GPU due to default dependency of MediaPipe on Tensorflow CPU version. You will need to setup MediaPipe for Tensorflow GPU runtime in order for YT8M pipeline to use GPU

**Comment by jiuqiant** [comment]
Some external users figured out [a quick solution](https://github.com/google/mediapipe/issues/301#issuecomment-562274156) to run TensorFlow GPU with MediaPipe. You probably can try it on your machine.
