### ISSUE TITLE
selfie_segmentation file missing in pip install

### ISSUE THREAD

**Issue by isaactian** [google/mediapipe#2445]
the pip install version of mediapipe is missing the selfie_segmentation file in the directory. It appears to be stuck on 0.8.3 instead of the latest version?

Traceback (most recent call last):
  File "selfiesegtest.py", line 7, in <module>
    mp_selfie_segmentation = mp.solutions.selfie_segmentation
AttributeError: module 'mediapipe.python.solutions' has no attribute 'selfie_segmentation'

**Comment by sgowroji** [comment]
Hi @isaactian,  Its working fine with the latest release  from [here](https://google.github.io/mediapipe/solutions/selfie_segmentation.html#python-solution-api). Upgrade to the latest mediapipe and python versions and check. And if you are still able to reproduce then please provide the steps.
