### ISSUE TITLE
FaceDetection doesn't accept model_selection parameter

### ISSUE THREAD

**Issue by johncblacker** [google/mediapipe#2447]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
Running mediapipe-rpi3 on raspberry pi 3b+
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- using example code on this github
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- Raspberry Pi ARM v7
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- mediapipe-rpi3
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):
- face detection
- Programming Language and version ( e.g. C++, Python, Java):
python
**Describe the expected behavior:**
I would expect the FaceDetection class would accept the model_selection=1 keyword but it fails and indicates
an unrecognize keyword.  I looked at source 0.8.4 and sure enough, no model_selection keyword for class.  So how
to use a different model?
**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:
Use example on this github for face detection, python example

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by sgowroji** [comment]
Hi @johncblacker, Could you please provide the above incomplete details to investigate the issue further. Thanks!

**Comment by jiuqiant** [comment]
FYI, mediapipe-rpi3 is not an official pypi package maintained by the mediapipe team. So, it may not have the latest features such as model selection.

**Comment by johncblacker** [comment]
IJiuqiant has the answer...apparently the mediapipe-rpi3/4 aren't "official" packages.  Since I have the source for the rpi3 version if I could find/see the source for the "official" version I could modify it.  Can you provide me link to source for "official" mediapipe version of the FaceDetection class?
