### ISSUE TITLE
AttributeError: module 'mediapipe.python.solutions.face_mesh' has no attribute 'FACE_CONNECTIONS'

### ISSUE THREAD

**Issue by HungDo2302** [google/mediapipe#2448]
Before i can run it. But now appear error :(( Can you help me fix it. Thanks you

My code:

import cv2
import mediapipe as mp
import time

cap = cv2.VideoCapture("video.mp4")
pTime = 0

mpDraw = mp.solutions.drawing_utils
mpFaceMesh = mp.solutions.face_mesh
faceMesh = mpFaceMesh.FaceMesh(max_num_faces=2)
drawSpec = mpDraw.DrawingSpec(thickness=1, circle_radius=2)

while True:
    success, img = cap.read()
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = faceMesh.process(imgRGB)
    if results.multi_face_landmarks:
        for faceLms in results.multi_face_landmarks:
            mpDraw.draw_landmarks(img, faceLms, mpFaceMesh.FACE_CONNECTIONS,drawSpec,drawSpec) #### Error
                                  
            for id,lm in enumerate(faceLms.landmark):
                #print(lm)
                ih, iw, ic = img.shape
                x,y = int(lm.x*iw), int(lm.y*ih)
                print(id,x,y)

    cTime = time.time()
    fps = 1 / (cTime - pTime)
    pTime = cTime
    cv2.putText(img, f'FPS: {int(fps)}', (20, 70), cv2.FONT_HERSHEY_PLAIN,
                3, (255, 0, 0), 3)
    cv2.imshow("Image", img)
    cv2.waitKey(1)

**Comment by sgowroji** [comment]
Hi @HungDo2302, Could you please update your python version. Its working fine with latest version. Thanks!

**Comment by jiuqiant** [comment]
Yes, FACE_CONNECTIONS is renamed to FACE_CONTOURS. Please see the new drawing example code at https://github.com/google/mediapipe/blob/master/docs/solutions/face_mesh.md#python-solution-api.

**Comment by HungDo2302** [comment]
I resolved my error. Thanks for your help.

Vào Th 2, 23 thg 8, 2021 lúc 12:53 google-ml-butler[bot] <
***@***.***> đã viết:

**Comment by HungDo2302** [comment]
I resolved my error. Thanks for your help.

Vào Th 2, 23 thg 8, 2021 lúc 12:53 Jiuqiang Tang ***@***.***>
đã viết:

**Comment by OlegQm** [comment]
If you have problems with FACE_CONTOURS also try FACEMESH_CONTOURS

**Comment by loicosquare** [comment]
> If you have problems with FACE_CONTOURS also try FACEMESH_CONTOURS

this work for me thanks.

**Comment by yugyesh** [comment]
> If you have problems with FACE_CONTOURS also try FACEMESH_CONTOURS

This one resolved my issue too

**Comment by ShahabAthar25** [comment]
> If you have problems with FACE_CONTOURS also try FACEMESH_CONTOURS

yes it solved my problem too

**Comment by markome** [comment]
Problem solved. Instead of using FACE_CONTOURS, generating error AttributeError: module 'mediapipe.python.solutions.face_mesh' has no attribute 'FACE_CONTOURS'  the code works when using FACEMESH_CONTOURS

**Comment by mnvaidya** [comment]
You can also use  ** FACEMESH_TESSELATION  ** to form connections. 
Refer this page - [https://google.github.io/mediapipe/solutions/face_mesh.html](url)

**Comment by mnvaidya** [comment]
You can also use -->    FACEMESH_TESSELATION         to form connection lines
Refer this page --->  [https://google.github.io/mediapipe/solutions/face_mesh.html](url)

**Comment by EasonQYS** [comment]
FACEMESH_CONTOURS works for me.  (mediapipe 0.8.9.1)

**Comment by SumbalZahra** [comment]
@fuwaraido did you find your answer?
