### ISSUE TITLE
File hands.py, solution_base.py missing, but they exist in my file manager.

### ISSUE THREAD

**Issue by Rego0116** [google/mediapipe#2449]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): I did not, I used  freeCodeCamp.org's hand tracking code.
- Programming Language and version ( e.g. C++, Python, Java): Python 3.9
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.6.2
- Solution ( e.g. FaceMesh, Pose, Holistic ): Hand

**Describe the current behavior:**
When i launch it with pycharm, it gives me this error:
`Traceback (most recent call last):
  File "C:\Users\Reiner Regő\PycharmProjects\HandTrackingProject\HandTrackingMin.py", line 8, in <module>
    hands = mpHands.Hands()
  File "C:\Users\Reiner Regő\PycharmProjects\HandTrackingProject\venv\lib\site-packages\mediapipe\python\solutions\hands.py", line 109, in __init__
    super().__init__(
  File "C:\Users\Reiner Regő\PycharmProjects\HandTrackingProject\venv\lib\site-packages\mediapipe\python\solution_base.py", line 237, in __init__
    validated_graph.initialize(
FileNotFoundError: The path does not exist.`
**Describe the expected behavior:**
Starts tracking my hand, and output coordinates
**Standalone code to reproduce the issue:**
Install opencv-python latest version using pip
Install mediapipe latest version using pip
Launch pycharm
Copy the code
Start the code
Get the error

**Other info / Complete Logs :**
The code that I'm using:
```
import cv2
import mediapipe as mp
import time

cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)

mpHands = mp.solutions.hands
hands = mpHands.Hands()
mpDraw = mp.solutions.drawing_utils

pTime = 0
cTime = 0

while True:
    success, img = cap.read()
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = hands.process(imgRGB)
    # print(results.multi_hand_landmarks)

    if results.multi_hand_landmarks:
        for handLms in results.multi_hand_landmarks:
            for id, lm in enumerate(handLms.landmark):
                # print(id, lm)
                h, w, c = img.shape
                cx, cy = int(lm.x * w), int(lm.y * h)
                print(id, cx, cy)
                # if id == 4:
                cv2.circle(img, (cx, cy), 15, (255, 0, 255), cv2.FILLED)

            mpDraw.draw_landmarks(img, handLms, mpHands.HAND_CONNECTIONS)

    cTime = time.time()
    fps = 1 / (cTime - pTime)
    pTime = cTime

    cv2.putText(img, str(int(fps)), (10, 70), cv2.FONT_HERSHEY_PLAIN, 3,
                (255, 0, 255), 3)

    cv2.imshow("Image", img)
    cv2.waitKey(1)
```

**Comment by sgowroji** [comment]
Hi @Rego0116, Can you try installing the latest `pip install mediapipe==0.8.7`.

**Comment by Rego0116** [comment]
Still doesn't work, gives me the same problem sadly.
```
Traceback (most recent call last):
  File "C:\Users\Reiner Regő\PycharmProjects\HandTrackingProject\HandTrackingMin.py", line 8, in <module>
    hands = mpHands.Hands()
  File "C:\Users\Reiner Regő\PycharmProjects\HandTrackingProject\venv\lib\site-packages\mediapipe\python\solutions\hands.py", line 109, in __init__
    super().__init__(
  File "C:\Users\Reiner Regő\PycharmProjects\HandTrackingProject\venv\lib\site-packages\mediapipe\python\solution_base.py", line 237, in __init__
    validated_graph.initialize(
FileNotFoundError: The path does not exist.
```

**Comment by Rego0116** [comment]
It seems like the line ```  validated_graph.initialize(
          binary_graph_path=os.path.join(root_path, binary_graph_path))```
is causing problems, by the path doesn't exist
