### ISSUE TITLE
Why use custom op Convolution2DTransposeBias in palm_detection.tflite?

### ISSUE THREAD

**Issue by apivovarov** [google/mediapipe#245]
I'm not sure why mediapipe uses custom op `Convolution2DTransposeBias` in `palm_detection.tflite`.
Can it be replaced with built-In ops `TRANSPOSE_CONV ` and `ADD`?  `TRANSPOSE_CONV ` op was added to TFLite in version [1.9](https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/contrib/lite/schema/schema.fbs)

I tried to create Keras model with `Conv2DTranspose` layer and I set `use_bias=True` and `bias_initializer='random_uniform'`.

https://keras.io/layers/convolutional/#conv2dtranspose

```
data = keras.layers.Input(shape=(32, 32, 3))
x = keras.layers.Conv2D(filters=10, kernel_size=(3, 3), strides=(2, 2), padding='same')(data)
x2 = keras.layers.Conv2DTranspose(filters=10, kernel_size=(3, 3), strides=(2, 2), padding='same', 
        use_bias=True,  bias_initializer='random_uniform')(x)
```

That Keras model can be converted to TFLite model. Keras `Conv2DTranspose` op was mapped to two built-in TFLite operators `TRANSPOSE_CONV` and `ADD`

Resulting TFLite model visualization: (download html and open it): https://www.dropbox.com/s/au39pvmw3fquhm1/conv2d_transpose_bias.tflite.htm?dl=0

**Comment by scm-ns** [comment]
@apivovarov I see their CPU implmentation. (Done in cpu_op_resolver) But I cannot find their GPU implementation. If you look at https://github.com/google/mediapipe/blob/731d2b95363d58f12acb29a6f8435ec33fe548d9/mediapipe/util/tflite/op_resolver.cc#L48, no functions are actually being registered to the custom op.

**Comment by mcclanahoochie** [comment]
The GPU implementation is here
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/gl/kernels/transpose_conv.cc
and gets registered in the graph here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/common/model_builder.cc#L887

A fused op such as this is more efficient on GPU than running two ops sequentially, and has identical result as the split version (tconv + add). The models are built with GPU use case as priority, and are back-ported to support CPU via a custom op.

**Comment by scm-ns** [comment]
@mcclanahoochie Thank you very much. That makes a lot of sense. Just a question. That seems like open gl implementation and not metal. So will that work on iOS? 

Another question if you can help me with this. I am trying to build a C++ static framework for iOS, so that I can add the custom ops. I am not using the C API, so cannot use the TensorflowLiteC/Swift/Objc pods. There is a TensorflowLite pod, but that is version 1.3, not 2. I can't find the bazel build file which generates the TensorflowLite pod, which has the C++ headers in them.

**Comment by apivovarov** [comment]
We converted `palm_detection.tflite` to use built-in `TRANSPOSE_CONV` + `ADD` ops instead of custom op `transpose_conv_bias`.
The output is absolutely the same. But CPU performance is 2.5 times faster for the model which uses built-it ops.
https://www.dropbox.com/s/hvl36tn1gojofg5/palm_detection_builtin.tflite?dl=0

**Comment by sebastijan94** [comment]
> We converted `palm_detection.tflite` to use built-in `TRANSPOSE_CONV` + `ADD` ops instead of custom op `transpose_conv_bias`.
> The outputs are absolutely the same. But CPU performance is 2.5x faster for the model which uses built-it ops [palm_detection_builtin.tflite](https://www.dropbox.com/s/hvl36tn1gojofg5/palm_detection_builtin.tflite?dl=0).
> 
> Model visualization [palm_detection_builtin.tflite.html](https://www.dropbox.com/s/l7fr8frb2nzxs0q/palm_detection_builtin.tflite.html?dl=0)

Can this model be used for multi hand detection?

**Comment by eknight7** [comment]
With release https://github.com/google/mediapipe/releases/tag/v0.6.4, see multi-hand tracking:
https://github.com/google/mediapipe/blob/master/mediapipe/docs/multi_hand_tracking_mobile_gpu.md

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by xuchengggg** [comment]
> 
> 
> We converted `palm_detection.tflite` to use built-in `TRANSPOSE_CONV` + `ADD` ops instead of custom op `transpose_conv_bias`.
> The outputs are absolutely the same. But CPU performance is 2.5x faster for the model which uses built-it ops [palm_detection_builtin.tflite](https://www.dropbox.com/s/hvl36tn1gojofg5/palm_detection_builtin.tflite?dl=0).
> 
> Model visualization [palm_detection_builtin.tflite.html](https://www.dropbox.com/s/l7fr8frb2nzxs0q/palm_detection_builtin.tflite.html?dl=0)

Hi, how could you change ops in tflite model?

**Comment by apivovarov** [comment]
download schema 
```
wget https://raw.githubusercontent.com/tensorflow/tensorflow/r1.15/tensorflow/lite/schema/schema.fbs
```
convert to json
```
flatc -t schema.fbs  -- mobilenet_v1_0.75_224.tflite
```
edit json
```
mobilenet_v1_0.75_224.json
```

I recommend to visualize tflite model to get tensor ids and buffer ids
```
python3 tensorflow/lite/tools/visualize.py \
$MODELS_DIR/mobilenet_v1_0.75_224.tflite \
$MODELS_DIR/mobilenet_v1_0.75_224.html
```

Convert edited json to tflite
```
flatc -b schema.fbs  mobilenet_v1_0.75_224_fixed.json
```

**Comment by xuchengggg** [comment]
Thank you!!

**Comment by anphunl** [comment]
> We converted `palm_detection.tflite` to use built-in `TRANSPOSE_CONV` + `ADD` ops instead of custom op `transpose_conv_bias`.
> The outputs are absolutely the same. But CPU performance is 2.5x faster for the model which uses built-it ops [palm_detection_builtin.tflite](https://www.dropbox.com/s/hvl36tn1gojofg5/palm_detection_builtin.tflite?dl=0).
> 
> Model visualization [palm_detection_builtin.tflite.html](https://www.dropbox.com/s/l7fr8frb2nzxs0q/palm_detection_builtin.tflite.html?dl=0)

Could you please share the files again? It's perfect if you share the edited JSON file. Thank you very much. 
I have same problem with another model that uses that operator and still stuck at it.

**Comment by kevinpl07** [comment]
> The GPU implementation is here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/gl/kernels/transpose_conv.cc and gets registered in the graph here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/common/model_builder.cc#L887
> 
> A fused op such as this is more efficient on GPU than running two ops sequentially, and has identical result as the split version (tconv + add). The models are built with GPU use case as priority, and are back-ported to support CPU via a custom op.

Is there any possibility to make a tflite model use those optimized ops when I convert from a regular keras model?
