### ISSUE TITLE
Facemesh to graph

### ISSUE THREAD

**Issue by aqibsaeed** [google/mediapipe#2452]
Hi,

Is there an option to extract graph from facemesh?

**Comment by sgowroji** [comment]
Hi @aqibsaeed, Could you please elaborate the above query with more details. Thanks!

**Comment by aqibsaeed** [comment]
Yes, I mean would it be possible to extract face landmarks and their corresponding points to create a graph. object in networkx library? What I am looking for is correspondence between `mp_face_mesh.FACEMESH_CONTOURS` and `face_landmarks.landmarks` here in this colab: https://colab.research.google.com/drive/1FCxIsJS9i58uAsgsLFqDwFmiPO14Z2Hd.

E.g., mp_face_mesh.FACEMESH_CONTOURS provides a list of points (124 in total) and face_landmarks.landmarks has a list of 468 landmarks. Is there a way to know which FACEMESH_CONTOURS belong to which landmark?

**Comment by aqibsaeed** [comment]
Got it. Nevermind.
