### ISSUE TITLE
providing video input to pose tracking solution for docker build

### ISSUE THREAD

**Issue by davitgoder** [google/mediapipe#2455]
I am using ubuntu 18.04 LST as a host system for the docker installation. 

I've successfully built the pose tracking solution, but when I try to run it using the following command: 
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/pose_tracking/pose_tracking_cpu   --calculator_graph_config_file=mediapipe/graphs/pose_tracking/pose_tracking_cpu.pbtxt
 
 I get the error:
 E20210823 13:40:43.800770 15187 demo_run_graph_main.cc:154] Failed to run the graph: ; capture.isOpened()(mediapipe/examples/desktop/demo_run_graph_main.cc:66)
 That's because the solution can not find the camera, my question is, how do I run it without providing access to the camera?
 Thanks.

**Comment by sgowroji** [comment]
Hi @davitgoder, It seems it is not detecting the camera of your desktop.

**Comment by jiuqiant** [comment]
You can follow the object detection demo to take video as input.
See https://google.github.io/mediapipe/solutions/object_detection#video-file-input and
https://github.com/google/mediapipe/tree/master/mediapipe/examples/desktop/object_detection
