### ISSUE TITLE
World Landmarks for Face and Hands 

### ISSUE THREAD

**Issue by drock577** [google/mediapipe#2457]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using):
- Programming language : Python

**Describe the feature and the current behavior/state:**
Currently Media Pipe has World Landmarks for pose.  There is no world landmark option for Holistic models which combine the hand, face and pose landmarks. 

**Will this change the current api? How?**
Yes it will add hand and face world landmark coordinates to the holistic model in addition to the individual hand and face models. 

**Who will benefit with this feature?**
Projects who see the world landmarks as a better option to the traditional landmark option currently offered.

Is there any plan to expand the the current world landmarks available in the pose_world_landmarks to support the holistic model of additional hand and face landmarks?

**Comment by sgowroji** [comment]
https://google.github.io/mediapipe/solutions/hands.html#multi_hand_world_landmarks World landmarks on Hands

**Comment by drock577** [comment]
Hello @sgowroji Thank you.
Is MediaPipe providing World Landmarks for Face as well?
