### ISSUE TITLE
Mediapipe compilation fails with OpenGL on Intel GPU

### ISSUE THREAD

**Issue by naveenkulkarni-movidius** [google/mediapipe#2458]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 20.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.7
- Installed using virtualenv? pip? Conda? (if python): Conda
- [MediaPipe version](https://github.com/google/mediapipe/releases):0.8.6.2
- Bazel version: bazel 4.2.0
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): OpenCV 4.5.3
- OpenGL version:
OpenGL details below:

OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.2.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.2.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
- 
**Describe the problem**:
Fails at "python setup.py install" stage when holistic module is modified to compile with GPU instead of CPU. The system does not have an external GPU, so it only has Intel iGPU(UHD Graphics 630, CFL GT2 )
Steps are described below in sequence of commands part.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

1. Modified changes and followed steps according to the ticket #1651:
    https://github.com/google/mediapipe/issues/1651
2. Made one additional change based on similar issue seen in issue #2041 in "mediapipe/framework/tool/BUILD" (linkopts = ["-lm"],)
3. It fails at "python setup.py install" step.  

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

Error logs::

Linking of rule '//mediapipe/python:_framework_bindings.so' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/python/_framework_bindings.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/python/_framework_bindings.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: error: cannot find -lImath
/usr/bin/ld.gold: error: cannot find -lIlmImf
/usr/bin/ld.gold: error: cannot find -lIex
/usr/bin/ld.gold: error: cannot find -lHalf
/usr/bin/ld.gold: error: cannot find -lIlmThread
/usr/bin/ld.gold: error: cannot find -lavresample
collect2: error: ld returned 1 exit status
Target //mediapipe/python:_framework_bindings.so failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by jiuqiant** [comment]
In https://google.github.io/mediapipe/getting_started/python#building-mediapipe-python-package, the command we provide to build the python wheels locally is `$ python3 setup.py install --link-opencv`.  Removing "--link-opencv" means that you want to build opencv from source instead of linking the local version. That's why you see those linker errors that are thrown during building opencv from source. If it's intended, please install those necessary 3p libraries beforehand.

**Comment by naveenkulkarni-movidius** [comment]
Thank you, using "--link-opencv" did resolve the issue and I am able to compile now . Now I can see the compiled binarypb in my conda mediapipe folder (holistic_landmark_gpu.binarypb). However when I run an example, I am getting OpenGL runtime errors. 
I tried removing EGL_WINDOW_BIT, based on #305(https://github.com/google/mediapipe/issues/305), but that did not resolve. I am using Python only application, how can OpenGL runtime issue be resolved within conda env setting? 



WARNING: Logging before InitGoogleLogging() is written to STDERR
I20210824 11:51:27.710808 1433580 gl_context_egl.cc:164] Successfully initialized EGL. Major : 1 Minor: 5
W20210824 11:51:27.710836 1433580 gl_context_egl.cc:169] Creating a context with OpenGL ES 3 failed: UNKNOWN: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES3 request. 
W20210824 11:51:27.710840 1433580 gl_context_egl.cc:170] Fall back on OpenGL ES 2.
Traceback (most recent call last):
  File "mediapipe_perf.py", line 17, in <module>
    holistic = mp_holistic.Holistic(static_image_mode=False,model_complexity=2,smooth_landmarks=True)
  File "/home/nk/anaconda3/envs/mpipe/lib/python3.7/site-packages/mediapipe/python/solutions/holistic.py", line 122, in __init__
    'right_hand_landmarks', 'face_landmarks'
  File "/home/nk/anaconda3/envs/mpipe/lib/python3.7/site-packages/mediapipe/python/solution_base.py", line 262, in __init__
    self._graph.start_run(self._input_side_packets)
RuntimeError: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES2 request.

**Comment by jiuqiant** [comment]
Reassign this to @mcclanahoochie for answering the OpenGL related issue.

**Comment by naveenkulkarni-movidius** [comment]
I also tried finding more details and solutions provided in #1483 . There is no external GPU in my system. Still see same error as above.

**Comment by naveenkulkarni-movidius** [comment]
Any updates or comments here would be great. Is there anything I can refer to get runtime issues with OpenGL resolved? Or if there are options to use OpenCL which improves performance on GPUs that would certainly be helpful.

**Comment by mcclanahoochie** [comment]
A related issue/workaround https://github.com/google/mediapipe/issues/2693#issuecomment-949457335
