### ISSUE TITLE
When compiling the media pipe package, why not use the AAR package of tflite directly and use the C + + version of tflite code directly

### ISSUE THREAD

**Issue by APeiZou** [google/mediapipe#2466]
When compiling the media pipe package, why not use the AAR package of tflite directly and use the C + + version of tflite code directly？
@google-admin 
当编译media-pipe包的时候为什么不直接使用tflite的aar包，而直接使用c++版本的tflite代码？

**Comment by sgowroji** [comment]
@APeiZou  Did you build Android source code with C++ and tflite?

**Comment by sgowroji** [comment]
@APeiZou: We have not tested the above use case. May be  you can try by checking the above with your observations. By the way, we have provided the Gradle solutions which will be use full to the community. Thanks!
