### ISSUE TITLE
hands tflite checkpoint in github repo does not match tflite checkpoint installed with pip

### ISSUE THREAD

**Issue by mlizhardy** [google/mediapipe#2467]
I spent a good amount of time inferencing directly with the tflite models for palm detection and hand landmarks.  

As stated in the title the tflite checkpoints for palm detection and hand landmark detection in this repo seem to be outdated.  They perform much worse when compared to the tflite checkpoints installed when I run "pip install mediapipe"

The checkpoints on this repo expect 2944 anchors, meaning the palm detection has an output of 2944 by 19, but from the pip install the checkpoint expects 896 anchors, meaning the palm detection output is 896 by 19.  Expected input image sizes also differ between the tflite checkpoints supplied in this repo and the tflite checkpoints installed by pip for both palm detection and hand landmarks.

Are they checkpoints purposefully different? If not, it would save a lot of headache to update the checkpoints in this repo.

**Comment by jiuqiant** [comment]
Thanks for reporting this. It might be a temporarily out of sync issue between the github repo and the pypi package push. We will try our best to keep them in sync per release.
