### ISSUE TITLE
ImageCroppingCalculator with multiple rects as input

### ISSUE THREAD

**Issue by yascov** [google/mediapipe#247]
Hello,

The documentation says that ImageCroppingCalculator accepts two inputs  the image to be cropped ( let's say IMAGE_GPU) and a RECT specifying the rectangle to be cropped (NORM_RECT for example). 

In my project I may have a vector of NORM_RECT( corresponding to multiple detections) and beacause of that I need to crop the image several times before genrerating a vector of croped images correspondingto each detection. 

My question is : is there a way to do it without modifying the ImageCroppingCalculator  unising only the exisiting calculators within mediapipe framework (call imageCroppingCalculator several times and group the outputs in one single packet for example)?

And by the way thank you for this great framework ( sorry for my english) 

Thank you

**Comment by eknight7** [comment]
Yes, coming soon! Also please see: https://github.com/google/mediapipe/issues/218.

**Comment by yascov** [comment]
Thank you.

**Comment by eknight7** [comment]
With the new release https://github.com/google/mediapipe/releases/tag/v0.6.4, the following are available:
1. `BeginLoopCalculator`: https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/begin_loop_calculator.h
2. `EndLoopCalculator`: https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/end_loop_calculator.h

See example usage in multi-hand tracking:
https://github.com/google/mediapipe/blob/master/mediapipe/docs/multi_hand_tracking_mobile_gpu.md
