### ISSUE TITLE
If I have my own pose detection model, how can I compile my own pose detection model into an AAR package?

### ISSUE THREAD

**Issue by APeiZou** [google/mediapipe#2470]
If I have my own pose detection model, how can I compile my own pose detection model into an AAR package?
如果我有一个自己的姿态检测模型，如何把自己的姿态检测的模型编译成AAR的包?

**Comment by sgowroji** [comment]
@APeiZou we don't provide any AAR. You can try creating using our [documentation](https://google.github.io/mediapipe/getting_started/android_archive_library.html). Reach us if you still have any queries.
