### ISSUE TITLE
How to select which GPU to run on?

### ISSUE THREAD

**Issue by HarryWindsor** [google/mediapipe#2472]
I successfully compiled MediaPipe for CUDA. I use a multi GPU setup and want to run the MediaPipe model on a specific GPU, but MediaPipe always just picks the first GPU. The `CUDA_VISIBLE_DEVICES=1` flag I normally use did not work.

How can I select the GPU MediaPipe should run on`

**Comment by mcclanahoochie** [comment]
Selecting a GPU involves choosing the correct 'EGLDisplay', currently in MediaPipe this is done [here](https://github.com/google/mediapipe/blob/master/mediapipe/gpu/gl_context_egl.cc#L155).
Notice the `eglGetDisplay()`, which defaults to device 0.

You will need to replace `eglGetDisplay` with something like `eglGetPlatformDisplayEXT`, then have that select device 1.

An example using `eglGetPlatformDisplayEXT` can be found [here ](https://github.com/NVIDIA-developer-blog/code-samples/blob/0754981b37b343474c45222ea487c9667551e854/posts/egl_OpenGl_without_Xserver/tinyegl.cc#L69) in the `#else` part.

There are not currently any plans to integrate this into MediaPipe [yet], but it can be considered in the future.
