### ISSUE TITLE
Is it possible to get list of proto bytes in Android Java?

### ISSUE THREAD

**Issue by j20001970** [google/mediapipe#2474]
Hello Mediapipe Team. I want to know if there are any ways to get list of proto bytes (when output packet is vector of proto type like hand_landmarks in hand tracking) because i would like to use the packet data in serialized form instead of parsing it directly in Java.

Currently the closest method i could find is getProtoVector in PacketGetter class, but that requires to pass a message parser (and I don't want to care what is the packet type in this case). Is the use case already achievable, or is there any plan to add such method (maybe called something like getProtoBytesVector)? Thanks.

**Comment by jiuqiant** [comment]
@sgowroji  please reassign this to the Android owners. Thanks.

**Comment by j20001970** [comment]
Hi, it's been several days since the issue, do you have any plans on adding such feature?

**Comment by sgowroji** [comment]
Hi @j20001970, we added the right owners for this issue and converted it to feature request. Please wait for the response. Thanks!

**Comment by mcclanahoochie** [comment]
Hi, are you familiar with the Android solutions API?
A [callback](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/solutions/hands/src/main/java/com/google/mediapipe/examples/hands/MainActivity.java#L339) can be custom written to process the result from the graph.  Alternatively you can create your own [HandsResult](https://github.com/google/mediapipe/blob/d4bb35fe5a44b3419ca86e4c7ecbc931dded2122/mediapipe/java/com/google/mediapipe/solutions/hands/HandsResult.java#L33) and process the packet as you wish.
For Packet parsing, here are the methods available in Java https://github.com/google/mediapipe/blob/d4bb35fe5a44b3419ca86e4c7ecbc931dded2122/mediapipe/java/com/google/mediapipe/framework/jni/packet_getter_jni.h

**Comment by j20001970** [comment]
Hi @mcclanahoochie thanks for your response. I took a look at [packet_getter_jni.h](https://github.com/google/mediapipe/blob/d4bb35fe5a44b3419ca86e4c7ecbc931dded2122/mediapipe/java/com/google/mediapipe/framework/jni/packet_getter_jni.h) and [packet_getter_jni.cc](https://github.com/google/mediapipe/blob/d4bb35fe5a44b3419ca86e4c7ecbc931dded2122/mediapipe/java/com/google/mediapipe/framework/jni/packet_getter_jni.cc), believe that exposing nativeGetProtoVector alone to Java class would be enough to achieve the use case, so that we can get vector of proto bytes without message parser specified:
```diff
diff --git a/mediapipe/java/com/google/mediapipe/framework/PacketGetter.java b/mediapipe/java/com/google/mediapipe/framework/PacketGetter.java
--- a/mediapipe/java/com/google/mediapipe/framework/PacketGetter.java
+++ b/mediapipe/java/com/google/mediapipe/framework/PacketGetter.java
@@ -146,6 +146,10 @@ public final class PacketGetter {
     return nativeGetFloat64Vector(packet.getNativeHandle());
   }
 
+  public static byte[][] getProtoBytesVector(final Packet packet) {
+    return nativeGetProtoVector(packet.getNativeHandle());
+  }
+
   public static <T> List<T> getProtoVector(final Packet packet, Parser<T> messageParser) {
     byte[][] protoVector = nativeGetProtoVector(packet.getNativeHandle());
     Preconditions.checkNotNull(
```
I wonder if we can get the change to upstream, as there could be other developers who also need such method on Java for transferring serialized data between modules or over network.

**Comment by j20001970** [comment]
@sgowroji Could you please update the label? Thanks.

**Comment by j20001970** [comment]
Since I no longer relying on such modification, I will close the issue.
