### ISSUE TITLE
MediaSequence: How to save additional video clips to the original video clips? 

### ISSUE THREAD

**Issue by Paniac** [google/mediapipe#2475]
**System information**
- Have I written custom code: I am using the kinetics_dataset.py example
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.6
- Solution: MediaSequence
- Programming Language and version: Python 3.6.9

**Describe the expected behavior:**
I have a dataset that contains the original video clips and the corresponding depth information (as grayscale images/videos).

I am using the [mediapipe/mediapipe/examples/desktop/media_sequence/kinetics_dataset.py](https://github.com/google/mediapipe/tree/master/mediapipe/examples/desktop/media_sequence/kinetics_dataset.py) example to get started with MediaSequence and got it running. So when I read the Kinetics dataset with `Kinetics(...).as_dataset(...)` I can access the single frames and optical flow frames with:

```python
dataset_output = dataset.make_one_shot_iterator().get_next()
images = dataset_output['images']
flow = dataset_output['flow']
```

But now I also want to have the depth information saved together with this. So that I am able to do: 
```python
depth = dataset_output['depth']
```

What is the best way to save these additional video clips (depth information) to the SequenceExamples?

**Comment by bryanseybold** [comment]
You'll have to make a few small changes to do this. I don't quite know how you want to encode the depth data, so here's one suggestion.

First, you'll need to store the depth images in the sequence examples. If you're able to encode the depth as a JPEG image, store the JPEG encoded image bytes in the key "DEPTH/image/encoded". If you are doing this in python, you can call `mediapipe.util.sequence.media_sequence.AddImageEncoded(image_bytes, sequence, prefix="DEPTH")` for each depth image. If you're adding images in C++ or using the MediaPipe graphs, I can add more suggestions.

Second, you'll need to modify kinetics_dataset.py to output the depth. Follow the pattern of what we do for the other image types:

Around line 169, request to also parse the depth by adding a line like: `"DEPTH/image/encoded": ms.get_image_encoded_default_parser(),` to the `sequence_features` dict.

Around line 191, you'll decode the depth from the images similar to how we decode the flow. (You may also need to dequantize the depth like we do for the flow on line 190.):
```
      depth = tf.image.convert_image_dtype(
          tf.map_fn(tf.image.decode_jpeg,
                    parsed_sequence["DEPTH/image/encoded"],
                    back_prop=False,
                    dtype=tf.uint8), tf.float32)
     # dequantize depth if needed.
```

Finally add the `depth` variable to the output dictionary and read it in your code.
