### ISSUE TITLE
Mediapipe pose web demo is broken

### ISSUE THREAD

**Issue by dewball345** [google/mediapipe#2476]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Chrome
- Programming Language and version ( e.g. C++, Python, Java): JS
- [MediaPipe version](https://github.com/google/mediapipe/releases):  Not sure by this(uses a window variable in the demo?)
- Bazel version (if compiling from source): N/A
- Solution ( e.g. FaceMesh, Pose, Holistic ): Pose
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): N/A
- Xcode & Tulsi version (if issue is related to building for iOS): N/A

**Describe the current behavior:**
Currently the web demo on codepen doesn't work, and I am getting this error:
![image](https://user-images.githubusercontent.com/30184788/131148218-04c6c6b0-e5e8-4254-bc6d-e16db20b189b.png)

The error(as text):
```
pose_solution_simd_wasm_bin.js:9 Uncaught (in promise) RuntimeError: abort(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)) at Error
    at jsStackTrace (pose_solution_simd_wasm_bin.js:9)
    at stackTrace (pose_solution_simd_wasm_bin.js:9)
    at abort (pose_solution_simd_wasm_bin.js:9)
    at Object.get (pose_solution_simd_wasm_bin.js:9)
    at pose_solution_simd_wasm_bin.js:9
    at qa.h (pose.js:formatted:1532)
    at ta (pose.js:formatted:245)
    at ua.next (pose.js:formatted:276)
    at pose.js:formatted:1199
    at new Promise (<anonymous>)
    at abort (pose_solution_simd_wasm_bin.js:9)
    at Object.get (pose_solution_simd_wasm_bin.js:9)
    at pose_solution_simd_wasm_bin.js:9
    at qa.h (pose.js:formatted:1532)
    at ta (pose.js:formatted:245)
    at ua.next (pose.js:formatted:276)
    at pose.js:formatted:1199
    at new Promise (<anonymous>)
    at Y (pose.js:formatted:1178)
    at pose.js:formatted:1526
```

**Describe the expected behavior:**
I was expecting it to show pose landmarks.

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:
The demo itself: https://codepen.io/mediapipe/pen/jOMbvxw?editors=1010

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2432

**Comment by sgowroji** [comment]
Hi @dewball345, Please check this for [supported platforms  ](https://google.github.io/mediapipe/getting_started/javascript#supported-plaforms)
