### ISSUE TITLE
Saving output of MediaPipe graph as Bitmap/Image

### ISSUE THREAD

**Issue by arijith96** [google/mediapipe#2477]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 20.02 Android 11 Android Studio with Gradle
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.6
- Bazel version: 4.1.0
- Solution (e.g. FaceMesh, Pose, Holistic): Object Detection, Box Tracking, KNIFT
- Programming Language and version ( e.g. C++, Python, Java): Java

**Describe the expected behaviour:**
I wanted to know how I could go about saving the output of any of MediaPipe's graphs in the form of a Bitmap or just as an image file.
We could just rewrite the same bitmap whenever the output frame is updated, but I am unclear how to go about this since the output of the graph is directly written onto the `SurfaceView` with the call 
`processor.getVideoSurfaceOutput().setSurface(holder.getSurface())`

Would I need another calculator like the [GpuBufferToImageFrame](https://github.com/google/mediapipe/blob/master/mediapipe/gpu/gpu_buffer_to_image_frame_calculator.cc)
before I send it to the `output_stream`?

Any help to guide me in the right direction would be highly appriciated! Amazing work with MediaPipe! :) Learning alot!

**Comment by arijith96** [comment]
Hi @sgowroji 
Any update on this? I saw that you had changed the label to `awaiting response`

**Comment by sgowroji** [comment]
If you are looking for [face mesh](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/solutions/facemesh/src/main/java/com/google/mediapipe/examples/facemesh/FaceMeshResultImageView.java) or [hands](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/solutions/hands/src/main/java/com/google/mediapipe/examples/hands/HandsResultImageView.java) refer those classes where we store the results of the image.

If you wanted for other solutions you can try this approach https://github.com/google/mediapipe/issues/2144 .

**Comment by arijith96** [comment]
Hi @sgowroji 

If I followed what was mentioned in #2144 correctly, the CameraX API would just provide us with the camera image. I was looking for something similar to the recently released Android Solutions, but not for face mesh and hands, rather for Object Detection, Box Tracking, KNIFT.
Do correct me if I am wrong here. Quite new to Mediapipe and Android

**Comment by sgowroji** [comment]
You should wait for some days to get the other gradle android  solutions (Object Detection, Box Tracking, KNIFT). You can try the #2144  approach by building AAR specific to your solution, Here you need to implement the logic in JAVA.

**Comment by arijith96** [comment]
Thank you for your reply! I will try to proceed as suggested.

In response to your comment, by when could we expect the other gradle android solutions to be released? Would all the android solutions be supported with gradle? Looking forward to trying them out! :D

**Comment by sgowroji** [comment]
@arijith96, We will let you know ETA soon. Thank you for the reply.

**Comment by ibrandiay** [comment]
@arijith96 Have found a solution? i need it so much

**Comment by ibrandiay** [comment]
@sgowroji Please, is there anything new about this?
