### ISSUE TITLE
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build Use --verbose_failures to see the command lines of failed build steps. INFO: Elapsed time: 10.026s, Critical Path: 8.93s INFO: 282 processes: 130 internal, 152 linux-sandbox. FAILED: Build did NOT complete successfully

### ISSUE THREAD

**Issue by APeiZou** [google/mediapipe#2479]
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build Use --verbose_failures to see the command lines of failed build steps. INFO: Elapsed time: 10.026s, Critical Path: 8.93s INFO: 282 processes: 130 internal, 152 linux-sandbox. FAILED: Build did NOT complete successfully.

**Comment by sgowroji** [comment]
Hi @APeiZou, Could you please share your system configuration  and steps to reproduce the above issue. Thanks!
