### ISSUE TITLE
When  I  build  an  AAR package    ERROR: An error occurred during the fetch of repository 'maven':

### ISSUE THREAD

**Issue by APeiZou** [google/mediapipe#2483]
INFO: Repository maven instantiated at:
  /home/vinbert/data/mediapipe/WORKSPACE:333:14: in <toplevel>
  /home/vinbert/.cache/bazel/_bazel_vinbert/bd12ffee51c720bff16284d608eb64ea/external/rules_jvm_external/defs.bzl:105:19: in maven_install
Repository rule coursier_fetch defined at:
  /home/vinbert/.cache/bazel/_bazel_vinbert/bd12ffee51c720bff16284d608eb64ea/external/rules_jvm_external/coursier.bzl:1009:33: in <toplevel>
INFO: Repository 'maven' used the following cache hits instead of downloading the corresponding file.
 * Hash 'af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
 * Hash 'babba8a144533f041a4de791d32de00552e31fa56231f241560a2ce6a7a72702' for https://github.com/coursier/coursier/releases/download/v2.0.7/coursier.jar
 * Hash '5c0a0a3ea600f302ee458b30317425dd9632d1ad8882259fcaf4e9b868b2b1ef' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
 * Hash 'a51d36968dcbdeabb3142c6f5cf9b401a65dc3a095f3144bd0c118d5bb192753' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe
If the definition of 'maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
	File "/home/vinbert/.cache/bazel/_bazel_vinbert/bd12ffee51c720bff16284d608eb64ea/external/rules_jvm_external/coursier.bzl", line 710, column 38, in _coursier_fetch_impl
		dep_tree = make_coursier_dep_tree(
	File "/home/vinbert/.cache/bazel/_bazel_vinbert/bd12ffee51c720bff16284d608eb64ea/external/rules_jvm_external/coursier.bzl", line 649, column 13, in make_coursier_dep_tree
		fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Timed out
ERROR: /home/vinbert/data/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar_android_lib depends on @maven//:com_google_code_findbugs_jsr305 in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /home/vinbert/data/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar_android_lib depends on @maven//:com_google_flogger_flogger in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /home/vinbert/data/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar_android_lib depends on @maven//:com_google_flogger_flogger_system_backend in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /home/vinbert/data/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar_android_lib depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: /home/vinbert/data/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar_android_lib depends on @maven//:androidx_lifecycle_lifecycle_common in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Timed out
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar' failed; build aborted: Analysis failed
INFO: Elapsed time: 600.783s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
@google-admin

**Comment by APeiZou** [comment]
bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a  \ //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar

**Comment by sgowroji** [comment]
Hi @APeiZou, Could you please go through it https://github.com/google/mediapipe/issues/1587#issuecomment-774341903
