### ISSUE TITLE
Run Mediapipe Hands as a service (Android)

### ISSUE THREAD

**Issue by caiyc2000** [google/mediapipe#2484]
I want to run Mediapipe even when I have put it to the background. I am thinking to convert Mediapipe Hands from an avtivity  to a service instead of an activity. 
Is it possible?  If yes, how should I change the code?
I read that a service cannot update UI directly because it works in the main thread.
I'm doing this on Pixel 4 with Android Studio.
Thanks in advance.

**Comment by sgowroji** [comment]
Hi @caiyc2000, Could you please elaborate your use case with more details. Why do you want to run a service when you execute the hands solution on a camera to see the graph?

**Comment by caiyc2000** [comment]
Thanks so much for your quick response.
The case is, I want to realize "virtual screen" through with the use of Mediapipe Hands. To be more specific, I intend to use my interact with my phone in the air instead of touching the physical screen. So when Mediapipe recognizes the hand landmarks, I will use the fingertip of my index finger as a mouse to "touch" the screen in the air. When my fingertip moves near toward the camera and then move away, I will determine it as a "click“, just as we normally touch the actual screen and leave.
Because I want to use this function on any interface of my phone, I have to convert the activity to a service in order to keep it running in the background.

**Comment by jiuqiant** [comment]
Probably you can use the Hands Android Solution: https://google.github.io/mediapipe/solutions/hands#android-solution-api, which can be used in background.

**Comment by caiyc2000** [comment]
> Probably you can use the Hands Android Solution: https://google.github.io/mediapipe/solutions/hands#android-solution-api, which can be used in background.

Thanks so much. @jiuqiant 
Previously I was using code from this repository: https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example. Could you tell me what' s the difference between this and the Hands Android Solution from https://google.github.io/mediapipe/solutions/hands#android-solution-api?
Also, is there any example of Mediapipe being used as a background service?

**Comment by sgowroji** [comment]
Hi @caiyc2000, [Android Hands solution ](https://google.github.io/mediapipe/solutions/hands.html#android-solution-api) is built using gradle api solutions, where  [mediapipe_multi_hands_tracking_aar_example](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example) is built using an AAR. You can explore the documentation to understand the api and building code from here https://google.github.io/mediapipe/getting_started/android_solutions.html

**Comment by caiyc2000** [comment]
Ok, I will try to use the Android Hands solution as a service.
If there is an example or demo of Mediapipe being used as a background service, please let me know. Thanks! @jiuqiant @sgowroji

**Comment by Asssssert** [comment]
@caiyc2000 
I have searched for a long time and finally found a way to do it. You can refer to the following page on how to start cameraX in service.  https://stackoverflow.com/questions/60630164/camerax-run-in-service-how-to-get-lifecycleowner-or-run-without-it-inside-a-fo  Also, I would like to ask if you know how to make the image appear without the data of the added coordinates, and how to make it mirror-flip.A demo can be included if possible.

**Comment by sgowroji** [comment]
@Asssssert May be you can create a new issue with your query as a feature request, As we don't have any such at present in our solutions. @caiyc2000 Hope you try the above use case with our latest android hands solution. Please reach us back if you still have any queries regarding the above. We are closing this issue now. Thanks!

**Comment by fiveshit** [comment]
@caiyc2000 
Hi , I would to know you have completed your project ? I want to do a function same as your.
