### ISSUE TITLE
Run javascript solution on a video and save the output

### ISSUE THREAD

**Issue by Shubham-Pachade** [google/mediapipe#2485]
Objective : To have the skeleton structure drawn over an input video

I am relatively new to this javascript env and I am still figuring out a lot of stuff. For the above-mentioned objective I recently stumbled upon mediapipe solution. I was interested in the python solution and implemented that but could not deploy it in the AWS lambda function. This was because the package size of the lambda function becomes too large owing to the dependencies such as OpenCV and Mediapipe itself.

So i wanted to implement this in the javascript env but I am not able to figure out how to replace the webcam input with the actual video and how to save the output in an external file. 

```
const pose = new Pose({locateFile: (file) => {
  return `https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.2/${file}`;
}});
pose.onResults(onResultsPose);

startPoseEstimation(document.getElementById("in_vid"));

function startPoseEstimation(video) {
    async function poseDetectionFrame() {
        await pose.send({image: video5});
		pose.onResults(onResultsPose);
    }
	width = 480, height = 480
}

```

This is the method I have been using. Could someone please let me know if I am on the right track?

**Comment by sgowroji** [comment]
Hi @Shubham-Pachade, You can have a look at our [codepen](https://codepen.io/mediapipe/full/jOMbvxw) pose code. Here you can even upload a video and excute pose on it.  Thanks!

**Comment by Shubham-Pachade** [comment]
@sgowroji Thank you for your prompt reply. I had gone through the typescript code available on codepen. I am also able to attach a video and then process it further. What I could not achieve was to get the pose estimation on the video which is present by default in the HTML <video> tag. I have used above-mentioned code for doing so. Do you see that code fit for the task?

**Comment by tyrmullen** [comment]
The MediaPipe JS API takes an HTMLVideoElement reference-- so once you start your video playing (let's say the reference in JavaScript is "myVideo"), you can just keep passing that reference to the API every frame: `await pose.send({image: myVideo});`. You should not need any of the extra code added in your example.

As for playing a video element in JS, there are numerous online tutorials for this (example: https://www.w3schools.com/tags/av_met_play.asp), and the same is true for saving the output externally (you'll likely want to look up the captureStream() function for this: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream).
