### ISSUE TITLE
I want to realize a multimedia task which contains the demuxer and decoder by using ffmpeg api, like gstavdemux.c and gstavviddec.c in gstreamer. How should I proceed

### ISSUE THREAD

**Issue by RTCFoundation** [google/mediapipe#2488]
|source|----> |demuxer| ---> |decoder|

**Comment by sgowroji** [comment]
Hi @RTCFoundation, Could you please elaborate your issue with complete details like which platform, which MediaPipe solution,  And last the steps to reproduce the above .

**Comment by RTCFoundation** [comment]
System information
MediaPipe version: master
Programming Language and version: C++
Describe the expected behavior:
I wanna that the mediapipe can support the demuxer and decoder by ffmpeg api,  just like gstreamer plugin

**Comment by kuaashish** [comment]
@RTCFoundation,

Closing this issue as we are not going to add this feature in the legacy solutions.
