### ISSUE TITLE
Memory grow & Crashed (HairSegmentation Android).

### ISSUE THREAD

**Issue by afsaredrisy** [google/mediapipe#249]
```hairsegmentationgpu``` is crashing after running few minutes on android device, What could be the reason. Do I need to look in ```calculators``` for memory leaks, Where could be the issue?.
I tried profile the app but could not find the leaked object.

**Comment by mgyong** [comment]
@afsaredrisy U need to adb log and also report version of android, phone model and type as well as opengl version running on the phone

**Comment by afsaredrisy** [comment]
I fixed it issue was this https://github.com/google/mediapipe/issues/252 already posted someone.

**Comment by eknight7** [comment]
Sharing your adb log and report would still be useful @afsaredrisy.
