### ISSUE TITLE
I want to use MediaPipe Pose on YUV frames in android. please help

### ISSUE THREAD

**Issue by Vignesh1-art** [google/mediapipe#2496]
Is there is way I can pass parameter to MediaPipe so that I can inform MediaPipe that I'm using YUV image. (Android's YUV_420_888)?

I want to use MediaPipe HandPose in android. In android I use camera2 , I can't use cameraX because I want to run camera in background also which is not possible in camerax so I use camera2 api. Android doesn't RGB output from camera device Android only garentees YUV_420_888 format. 
How to use this format directly with mediapipe? Is there any image format converter within MediaPipe?

**Comment by sgowroji** [comment]
Hi @Vignesh1-art, Could you please elaborate your usecase with more details . Thanks!

**Comment by Vignesh1-art** [comment]
> Hi @Vignesh1-art, Could you please elaborate your usecase with more details . Thanks!

done

**Comment by LMR2018** [comment]
@Vignesh1-art    Have you solved the problem yet? I also want to know how to solve

**Comment by Vignesh1-art** [comment]
I implemented my converter

**Comment by LMR2018** [comment]
> 我实现了自己的转换器

@Vignesh1-art    can you share with me?

**Comment by Vignesh1-art** [comment]
> > 我实现了自己的转换器
> 
> @Vignesh1-art    can you share with me?  

I would if I had. Unfortunately I don't have it now.  I refered this https://en.m.wikipedia.org/wiki/YUV to implement it.
