### ISSUE TITLE
Is it normal that mediapipe Pose tracking produce different results on different devices?

### ISSUE THREAD

**Issue by zwfcrazy** [google/mediapipe#2497]
**System information** (Please provide as much relevant information as possible)
Various devices and systems.

**Describe the expected behavior:**
We have tried to run mediapipe pose tracking on a variety of devices including Windows laptops, Ubuntu servers, Nvidia Jetson, and Android mobile phones. All of them produced different results (noticeable landmark difference) for the same input video.
In addition, the cpp compiled version and python compiled version also produce different results.
Have you experienced the same problem? What could be the possible cause?

**Comment by sgowroji** [comment]
Hi @zwfcrazy, We are glad to know you are using MediaPipe in different platforms. Could you please provide your observation and video which is tested for all the platforms to verify and investigate it at our end. Thanks!

**Comment by zwfcrazy** [comment]
> Hi @zwfcrazy, We are glad to know you are using MediaPipe in different platforms. Could you please provide your observation and video which is tested for all the platforms to verify and investigate it at our end. Thanks!

Please find some of our observations from the following link:
https://drive.google.com/drive/folders/1KRdN-uCRVKUE6WT1pOf0id-PXsv5geyJ?usp=sharing
The test video is also included, though we believe this problem is not video-specific, you can test with any video.

**Comment by zwfcrazy** [comment]
@sgowroji 
I have located two problems that may cause the difference. (but there are other problems to be located)

**Comment by zwfcrazy** [comment]
@sgowroji 
I have located two problems that may cause the difference. (but there are other problems to be located)

The first problem.
The LandmarksSmoothingCalculator requires packet timestamp as input in order to calculate some filtering parameters. Because different devices have different processing power, the frame rate of processing may be different, causing a different filtering result.
The python version does not have this problem because it uses fake timestamps.

The second problem.
This is a bug that I have mentioned in another issue of mine #2229 .
The python version has a problem of parsing graphs. Some nodes may lose their options field after parsing. For pose landmarks, it is the RefineLandmarksFromHeatmapCalculator.
In mediapipe/modules/pose_landmark/pose_landmark_by_roi_cpu.pbtxt, we have 
```
# Refines landmarks with the heatmap tensor.
node {
  calculator: "RefineLandmarksFromHeatmapCalculator"
  input_stream: "NORM_LANDMARKS:raw_landmarks"
  input_stream: "TENSORS:heatmap_tensor"
  output_stream: "NORM_LANDMARKS:refined_landmarks"
  options: {
    [mediapipe.RefineLandmarksFromHeatmapCalculatorOptions.ext] {
      kernel_size: 7
    }
  }
}
```
The kernel size is set to 7. However, since the options field is lost in the python version, this node will use the default kernel size which is 9. This will cause a difference between the python version and other versions.

I will write another issue regarding this bug.

**Comment by ivan-grishchenko** [comment]
@zwfcrazy You are right about the Smoothing calculator.

Another factor is the inference engine used on different platforms. We have implementations of model ops on CPU, XNNPack, Metal, OpenGL, WebGL which may vary because of platform specifics, using float16 or float32 or other factors.

As for the bug of parsing graph in Python API the best person to comment is @jiuqiant .

**Comment by jiuqiant** [comment]
tflite cpu inference and gpu inference may produce different results. For example, MediaPipe Python is with the CPU graphs and Android is normally with the GPU graphs. It might due to the different inference engine different devices use.
