### ISSUE TITLE
Accessing outputs (joint landmarks) for Coral Accelerator mediapipe demo using Bazel

### ISSUE THREAD

**Issue by henrypowell87** [google/mediapipe#2499]
I'm trying to run mediapipe on a raspi4 with a Coral accelerator for a task involving hand gesture recognition. I have a working module that runs medipipe but without Coral TPU acceleration. I also have a version of mediapipe built with Bazel that does run on the TPU but can only be run in Bazel. I'm trying to locate the (or any) python code that shows plainly how to either output the joint positions from the bazel module that I can then access and perform inference on or how to take a non TPU mediapipe script and get it running on the Coral TPU. Any ideas would be hugely appreciated! Have been tearing my hair out with this problem for almost a month now. Many thanks!

**Comment by sgowroji** [comment]
Hi @henrypowell87, What is the error you are facing when you are running on coral TPU acceleration?. And Which python code are you referring to run the above use case. Thanks!

**Comment by henrypowell87** [comment]
Hi @sgowroji. No error specifically as the TPU acceleration works with the bazel build of mediapipes hand tracking module found in mediapipe/examples/desktop/hand_tracking. The issue is getting a module that I have previously built to work with the TPU. This module runs mediapipes handtracking libraries but only on CPU. So the issue I'm having is how to bridge these two. It seems like mediapipe will not work with TPU integration without the relatively complex process of somehow integrating Bazel. My question is just related to whether this is true, i.e. how would I go about porting a non-bazel mediapipe script so that the hand inference is done on the TPU rather than the RasPi CPU? Is this possible? Cheers!

**Comment by mcclanahoochie** [comment]
Hi,
How did you create the non-bazel mediapipe app? I would image the same process applies to TPU (converting the bazel build rules into whatever alternative build system you use). 
The only difference for TPU is the TfLiteInferenceCalculator gets compiled with TPU libraries and uses TPU delegate specified in the graph. If you are already running MP hand tracking outside bazel, then you are likely already using the TfLiteInferenceCalculator (or InferenceCalculator), so then just the remaining TPU libraries need to be ported out of bazel.
Or, you can build mediapipe graph runner with bazel ([similar to this](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/demo_run_graph_main.cc)) as a cc_library with some header file exposing an interface, then link that into your custom build system.
