### ISSUE TITLE
SUPPORT MEDIAPIPE BUILD PROCESS ON RASPBERRY PI 3 AND 4

### ISSUE THREAD

**Issue by johncblacker** [google/mediapipe#2501]
<em>Please make sure that this is a feature request.</em>
<em> SUPPORT MEDIAPIPE BUILD PROCESS ON RASPBERRY PI 3 AND 4.</em>
**System information** (Please provide as much relevant information as possible)
Raspberry Pi 3b+
- MediaPipe Solution (you are using):
- latest sources
- Programming language : C++/typescript/Python/Objective C/Android Java
- Python
- Are you willing to contribute it (Yes/No):
- Yes

**Describe the feature and the current behavior/state:**
Currently, mediapipe is not officially supported on the Raspberry Pi 3b+ (or Raspberry Pi 4/b, either).  Apparently, according to mediapipe support, there are problems building mediapipe on rPi 3 that are the result of TFlite; but, TFlite seems to be supported on the Raspberry Pi so someone needs to look into what's going on with rPi builds (using Bazel) on the rPi - specifically the problem being encountered by numerous developers who are getting an error at runtime with undefined symbol resulting from the import of mediapipe.  It seems strange that support groups from the same parent company can't put their heads together and arrive at a solution.

**Will this change the current api? How?**
There should be no change whatsoever to the api

**Who will benefit with this feature?**
Raspberry Pi developers
**Please specify the use cases for this feature:**
Many developers are using their Raspberry Pi's to implement solutions involving machine learning, e.g. face-detection, etc. and in the end, Google, mediapipe and tensorflow groups will all benefit
**Any Other info:**
No

**Comment by kuaashish** [comment]
@johncblacker,

MP Tasks for Python will have Raspberry Pi support soon and will let you once becomes available.

**Comment by johncblacker** [comment]
I'm still waiting for notification of support for mediapipe on Raspberry Pi Bullseye.

**Comment by kuaashish** [comment]
@johncblacker,

This feature has been added in latest release [0.10.3](https://github.com/google/mediapipe/releases). Please build using the **Pip command** probably in **Raspberry Pi 4** And let us know if you encounter any error. Thank you

**Comment by johncblacker** [comment]
Installed 0.3.10 for python 3.9 on Raspberry Pi Bullseye - 64bit os.  Tried an example that I have, code below:
**** sample code below ***

import cv2
IMAGE_FILE = 'image.jpg'

window_name1 = '1image'
img = cv2.imread(IMAGE_FILE)
cv2.imshow(window_name1, img)

cv2.waitKey(0)

import numpy as np
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

base_options = python.BaseOptions(model_asset_path='efficientdet.tflite')
options = vision.ObjectDetectorOptions(base_options=base_options,                                                              
                 score_threshold=0.5)
detector = vision.ObjectDetector.create_from_options(options)
image = mp.Image.create_from_file(IMAGE_FILE)
detection_result = detector.detect(image)
image_copy = np.copy(image.numpy_view())
annotated_image = visualize(image_copy, detection_result)
rgb_annotated_image = cv2.cvtColor(annotated_image, cv2.COLOR_BGR2RGB)
window_name2 = '2image'
cv2.imshow(window_name2, rgb_annotated_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
*** end of sample code ***
Result of running was: 
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "/home/pi/mp-projects/mp-objdettest1.py", line 25, in <module>
    annotated_image = visualize(image_copy, detection_result)
NameError: name 'visualize' is not defined

Perhaps sample code is no longer valid?  By the way, it took over 30 seconds on pi 3b+ before the error showed up - that would be a show-stopper for me...would mediapipe support the Google Coral Accelerator for speed improvement?

**Comment by kuaashish** [comment]
@johncblacker,

We rolled out support for only Raspberry Pi 4. Please revert back if you encounter any error in Pi 4. Thank you
