### ISSUE TITLE
KNIFT ImageTransformationCalculator Output Image

### ISSUE THREAD

**Issue by arijith96** [google/mediapipe#2502]
## URL(s) with the issue:

https://github.com/google/mediapipe/blob/6abec128edd6d037e1a988605a59957c22f1e967/mediapipe/graphs/template_matching/template_matching_mobile_cpu.pbtxt#L28

https://github.com/google/mediapipe/blob/6abec128edd6d037e1a988605a59957c22f1e967/mediapipe/graphs/template_matching/template_matching_mobile_cpu.pbtxt#L35

## Description of issue (what needs changing):

As stated in the comment, the output of this calculator is 480x640. 
But in the option of the calculator, we have 
`output_width: 640`
`output_height: 640`

I just wanted to know if I misunderstood what this calculator does :)

**Comment by yegenzhi** [comment]
the FILL_AND_CROP option will make sure that the longer side of the image is scaled to 640, no matter if that is a horizontal or vertical image. we will change comment accordingly.

**Comment by sgowroji** [comment]
Hi @arijith96, Please go through the above [comments](https://github.com/google/mediapipe/issues/2502#issuecomment-916321958). We will update you with the latest comments very soon. Thanks!

**Comment by arijith96** [comment]
Hey @yegenzhi @sgowroji, 
Thanks for clearing that up :)
