### ISSUE TITLE
How to make an image appear without adding coordinate data and how to make it mirror-flip

### ISSUE THREAD

**Issue by Asssssert** [google/mediapipe#2504]
I need to display the images without the coordinate points marked instead of the ones with the points added, and rotate them

**Comment by sgowroji** [comment]
Hi @Asssssert, Can you elaborate your use case with more details. Thanks!

**Comment by Asssssert** [comment]
Hi @sgowroji,
I need to display the original image of the camera and be able to get the coordinate data via the "PacketCallback" method, instead of displaying the image data with the coordinates already marked. And I need to freely rotate the image angle

**Comment by sgowroji** [comment]
Thank you for the reply. So which MediPipe solution are you referring the above ( facemesh, hands or pose ).

**Comment by Asssssert** [comment]
It's mostly poses, but I think this should be a public API

**Comment by sureshdagooglecom** [comment]
Hi @Asssssert ,
Now  it is Public API , kindly check in the latest version.
