### ISSUE TITLE
USE MOBILENET-SSDLITE ON TRACKING

### ISSUE THREAD

**Issue by ibrandiay** [google/mediapipe#2505]
Hello, I want to use tracking to follow boxes. Can I use an ssdlite model without having to write my own c ++ wrapper?

**Comment by sgowroji** [comment]
Hi @ibrandiay, Could you please elaborate your request with complete details. Thanks!

**Comment by ibrandiay** [comment]
I want to use mediapipe box tacking with my own mobilenet ssdlite model for object detection. I want to know if the calculator given as an example on mediapipe will suffer me to make the inference, or that I should write my own c ++ wrapper for it?

**Comment by sgowroji** [comment]
Hi @ibrandiay, Did you get a chance to go through our documentation on [model cards  ](https://github.com/google/mediapipe/blob/master/mediapipe/models/object_detection_saved_model/README.md) and [models](https://google.github.io/mediapipe/solutions/models.html#object-detection).

**Comment by ibrandiay** [comment]
Thank you I see that it is possible to use ssd lite mobilenet. thank you so much
