### ISSUE TITLE
Performance when using iOS dynamic framework of HandTrackingGpuApp is slower than using it directly

### ISSUE THREAD

**Issue by tommypham** [google/mediapipe#2507]
When using HandTrackingGpuApp iOS app directly to track the finger moving , I saw it quite good and smooth like this video: [https://youtu.be/mIpa__UVXsk](https://youtu.be/mIpa__UVXsk) 
But after converting HandTrackingGpuApp app to dynamic framework, the performance 's slower like this video: [https://www.youtube.com/watch?v=Hnng4ymm_6k](https://www.youtube.com/watch?v=Hnng4ymm_6k)

Can anyone help me for better way please ?

**Comment by sgowroji** [comment]
Hi @tommypham, Could you please provide your code changes to understand and investigate the issue for further. Thanks!

**Comment by tommypham** [comment]
Hi @sgowroji ,
I think I 've found the issue because of the thread to open camera and keep tracking the hands:
```
static const char* kVideoQueueLabel = "com.google.mediapipe.example.videoQueue";

dispatch_queue_attr_t qosAttribute = dispatch_queue_attr_make_with_qos_class(
                                                                                 DISPATCH_QUEUE_SERIAL, QOS_CLASS_USER_INTERACTIVE, /*relative_priority=*/0);
self.videoQueue = dispatch_queue_create(kVideoQueueLabel, qosAttribute);
```
We can not interact as usual way during camera open. For ex: we can add a button to the view controller : HandTrackingViewController and touch the button to test.
When using the dynamic framework in my case to make OCR with tesseract (pod 'TesseractOCRiOS', '4.0.0') , the thread for process of OCR may affect to the thread of tracking hand camera. That 's why it seems slower. But without OCR process, it 's  still a little slower compare with run directly in HandTrackingGpuApp iOS app.

**Comment by IsaacCavalcante** [comment]
Hi @tommypham. Can you provide the BUILD file you used to build the dynamic framework?

**Comment by tommypham** [comment]
I copied the way to build iOS dynamic framework from here: [https://github.com/google/mediapipe/issues/364#issuecomment-575921420](https://github.com/google/mediapipe/issues/364#issuecomment-575921420)
and changed a little bit the Makefile:
```
framework:
	bazel build --config=ios_arm64 --cxxopt='-std=c++17' mediapipe/develop:MyFramework
	cd bazel-bin/mediapipe/develop/ &&\
	rm -rf MyFramework.framework &&\
	unzip MyFramework.zip &&\
	cd MyFramework.framework &&\
	ar -dv MyFramework  NSError+util_status_f64093ca561b3913726e4e3728906dd8.o
```
in /mediapipe/develop , I changed the BUILD like this:
```
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_framework")

ios_framework(
    name = "MyFramework",
    hdrs = [
        "ObjcClass.h",
    ],
    infoplists = ["Info.plist"],
    bundle_id = "com.noppelab.MyFramework",
    families = ["iphone", "ipad"],
    minimum_os_version = "10.0",
    deps = [
        ":HandTrackingGpuAppLibrary",
        "@ios_opencv//:OpencvFramework",
    ],
)

objc_library(
    name = "HandTrackingGpuAppLibrary",
    srcs = [
        "ObjcClass.mm",
    ],
    hdrs = [
        "ObjcClass.h",
    ],
    
    sdk_frameworks = [
        "AVFoundation",
        "CoreGraphics",
        "CoreMedia",
        "UIKit"
    ],
    copts = ["-std=c++17"],
    data = [
        "//mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu.binarypb",
        "//mediapipe/modules/hand_landmark:hand_landmark.tflite",
        "//mediapipe/modules/hand_landmark:handedness.txt",
        "//mediapipe/modules/palm_detection:palm_detection.tflite",
    ],
    deps = [
        "//mediapipe/examples/ios/common:CommonMediaPipeAppLibrary",
        "//mediapipe/util:annotation_renderer",
    ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            "//mediapipe/graphs/hand_tracking:mobile_calculators",
            "//mediapipe/framework/formats:landmark_cc_proto",
        ],
    }),
)
```
Final step, I ran command line in the same folder of Makefile : `make`  to build the framework and used.
@IsaacCavalcante : you can use the dynamic framework to test performance.

**Comment by sgowroji** [comment]
Thank you for sharing your resolution in the above [comments](https://github.com/google/mediapipe/issues/2507#issuecomment-914375603). We are closing this issue now. Please feel free to reopen if you still have any relevant queries from the above context.
