### ISSUE TITLE
Easy way to export framework of a module by xcode

### ISSUE THREAD

**Issue by sek790c** [google/mediapipe#2508]
It is easy to build and run iOS examples by Xcode.
I want to use handtrackingGpu in my app, I like to export this module as a framework instead of HandTrackingGpuApp.app,so I can import it to my Xcode project as a framework.
Is there a easy way?Or I can import Mediapipe iOS project by workspace?Or I had to add all files to my project by hand?

**Comment by sgowroji** [comment]
Hi @sek790c, This [link](https://stackoverflow.com/questions/51285220/converting-an-existing-project-into-customizable-framework) might be helpful to you.  Build an HandtrackingGPU from [here](https://google.github.io/mediapipe/getting_started/ios#mediapipe-on-ios)  and use the above steps.

**Comment by sek790c** [comment]
I found many issues of Mediapipe about createing framework by Xcode.Such as #364,#725,#1549,#2275
I think it is a good idea to publish an official document abou it.
Createing Framework is more useful than import projects by workspace, in my case ,I export a iOS Xcode project by Unity3d ,import a framework to it is a good way.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google/mediapipe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月7日(星期二) 中午12:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google/mediapipe] Easy way to export framework of a module by xcode (#2508)





 
Hi @sek790c, This link might be helpful to you.  Build an HandtrackingGPU from here  and use the above steps.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sgowroji** [comment]
Thank you for your request. I will mark this issue as a feature request and share it to the right owner.

**Comment by sureshdagooglecom** [comment]
Hi @sek790c ,
Could you please check this in the latest version of MediaPipe.
