### ISSUE TITLE
 When is it supported Audio?

### ISSUE THREAD

**Issue by rzyangKyle** [google/mediapipe#251]
I want to use mediapipe to dev audio model, but i can not find in examples.

**Comment by jiuqiant** [comment]
It's supported already. If you see [the youtube8m feature extraction graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/youtube8m/feature_extraction.pbtxt), it extracts both video and audio features. The audio subgraph starts at [line 124](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/youtube8m/feature_extraction.pbtxt#L124) and the model is [VGGish](https://github.com/tensorflow/models/tree/master/research/audioset/vggish)

**Comment by rzyangKyle** [comment]
Thank you，but audio can support on android or ios platform in mediapipe/example ?

**Comment by rzyangKyle** [comment]
> Audio feature extraction is already supported in MediaPipe. If you see [the youtube8m feature extraction graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/youtube8m/feature_extraction.pbtxt), it extracts both video and audio features. The audio subgraph starts at [line 124](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/youtube8m/feature_extraction.pbtxt#L124) and the model is [VGGish](https://github.com/tensorflow/models/tree/master/research/audioset/vggish)

Thank you，but audio can support on android or ios platform in mediapipe/example ?
