### ISSUE TITLE
MediaPipe Javascript Pose throws RuntimeError: abort(undefined) after running for a while 

### ISSUE THREAD

**Issue by iagotomas** [google/mediapipe#2510]
**System information** 

- IPhone SE 2 iOS 14.7
- Google Chrome 92.0.4515.131 + Linux Ubuntu 20.04
- Programming Language and version ( e.g. C++, Python, Java): Javascript
- [MediaPipe version](https://github.com/google/mediapipe/releases): JS version 0.4.1630009814 
-  Pose

**Describe the current behavior:**

After running and inferencing models for some minutes suddenly MediaPipe throws a RuntimeError.

**Describe the expected behavior:**

Previous version, at least 0.4.1627931336 didn't behave in this way and ran smoothly

**Standalone code to reproduce the issue:**

**Other info / Complete Logs :**

```
E0906 22:20:16.016000       1 inverse_matrix_calculator.cc:38] generic::internal: RET_CHECK failure (third_party/mediapipe/calculators/util/inverse_matrix_calculator.cc:38) inverse_check Inverse matrix cannot be calculated.

Stack trace:

E0906 22:20:16.017000       1 calculator_graph.cc:810] INTERNAL: CalculatorGraph::Run() failed in Run: 

Calculator::Process() for node "poselandmarkgpu__poselandmarkbyroigpu__poselandmarksandsegmentationinverseprojection__InverseMatrixCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/util/inverse_matrix_calculator.cc:38) inverse_check Inverse matrix cannot be calculated. [type.googleapis.com/mediapipe.StatusList='\n\xa9\x02\x08\r\x12\xa4\x02\x43\x61lculator::Process() for node \"poselandmarkgpu__poselandmarkbyroigpu__poselandmarksandsegmentationinverseprojection__InverseMatrixCalculator\" failed: RET_CHECK failure (third_party/mediapipe/calculators/util/inverse_matrix_calculator.cc:38) inverse_check Inverse matrix cannot be calculated.']

=== Source Location Trace: ===
third_party/mediapipe/framework/tool/status_util.cc:139

F0906 22:20:16.019000       1 solutions_wasm.embind.cc:674] Check failed: absl::OkStatus() == ::util::status_internal::AsStatus((graph_->WaitUntilIdle())) (OK vs. INTERNAL: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "poselandmarkgpu__poselandmarkbyroigpu__poselandmarksandsegmentationinverseprojection__InverseMatrixCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/util/inverse_matrix_calculator.cc:38) inverse_check Inverse matrix cannot be calculated. [type.googleapis.com/mediapipe.StatusList='\n\xa9\x02\x08\r\x12\xa4\x02\x43\x61lculator::Process() for node \"poselandmarkgpu__poselandmarkbyroigpu__poselandmarksandsegmentationinverseprojection__InverseMatrixCalculator\" failed: RET_CHECK failure (third_party/mediapipe/calculators/util/inverse_matrix_calculator.cc:38) inverse_check Inverse matrix cannot be calculated.']
=== Source Location Trace: ===
third_party/mediapipe/framework/tool/status_util.cc:139
)
*** Check failure stack trace: ***
undefined

Uncaught (in promise) RuntimeError: abort(undefined) at Error
    at jsStackTrace (pose_solution_simd_wasm_bin.js:9)
    at stackTrace (pose_solution_simd_wasm_bin.js:9)
    at abort (pose_solution_simd_wasm_bin.js:9)
    at _abort (pose_solution_simd_wasm_bin.js:9)
    at pose_solution_simd_wasm_bin.wasm:0x4fa421
    at pose_solution_simd_wasm_bin.wasm:0x4fa2d5
    at pose_solution_simd_wasm_bin.wasm:0x4fa43a
    at pose_solution_simd_wasm_bin.wasm:0x18bee
    at pose_solution_simd_wasm_bin.wasm:0x13c86
    at SolutionWasm$send [as send] (eval at new_ (pose_solution_simd_wasm_bin.js:9), <anonymous>:9:1)
    at qa.h (pose.js:65)
    at ta (pose.js:14)
    at ua.next (pose.js:15)
    at g (pose.js:41)
    at abort (pose_solution_simd_wasm_bin.js:9)
    at _abort (pose_solution_simd_wasm_bin.js:9)
    at pose_solution_simd_wasm_bin.wasm:0x4fa421
    at pose_solution_simd_wasm_bin.wasm:0x4fa2d5
    at pose_solution_simd_wasm_bin.wasm:0x4fa43a
    at pose_solution_simd_wasm_bin.wasm:0x18bee
    at pose_solution_simd_wasm_bin.wasm:0x13c86
    at SolutionWasm$send [as send] (eval at new_ (pose_solution_simd_wasm_bin.js:9), <anonymous>:9:1)
    at qa.h (pose.js:65)
    at ta (pose.js:14)
    at ua.next (pose.js:15)
    at g (pose.js:41)
```

**Comment by sgowroji** [comment]
Hi @iagotomas, Could you please perform the workaround mentioned in this https://github.com/google/mediapipe/issues/2432#issuecomment-901632553

**Comment by iagotomas** [comment]
Already tried cleaning up the cache but issue persists.
 
I forgot to mention I'm not using Codepen demo but our own solution which we built and pin to 0.4.1630009814, I can confirm that the assets are loading the right version and as pointed in #2432 it occurs intermitently. I left it open all night and didn't had an issue, and just reloaded and after a couple of min it gets stucked.

**Comment by cindyloo** [comment]
I also have this error with FaceMesh

**Comment by sgowroji** [comment]
Thank you all for your patience. We have shared your request with @mhays-google. He will address the above query once he is available.

**Comment by galaxxyz** [comment]
I have the same problem with Holistic. 
I tried to clear cache as mentioned in [#2432 comment](https://github.com/google/mediapipe/issues/2432#issuecomment-901632553) but the error still persists.

**Comment by kuaashish** [comment]
Hello @iagotomas,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
