### ISSUE TITLE
Hairsegmentation

### ISSUE THREAD

**Issue by akrutiJksol** [google/mediapipe#2512]
How can i do hair segmentation in image instead of live camera in android hairsegmentation module using mobile_gpu.binarypb and hair_segmentation.tflite files..

**Comment by sgowroji** [comment]
Hi @akrutiJksol, Present we don't have standard examples on Hair_Segmentation. But you can try building an [android code ](https://google.github.io/mediapipe/getting_started/android) with bazel or With An [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html#mediapipe-android-archive). Inputing an image is more a JAVA programming,  which you can start from [here](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java) .
