### ISSUE TITLE
How to get the visibility of pose landmarks?

### ISSUE THREAD

**Issue by Ar4enal** [google/mediapipe#2513]
Android platform

When I am building holistic app I know I can use _landmark.getX()_ to get the landmark coordinates. But what is the function of getting visibility of the landmark?

thanks for replying.

_POSE_LANDMARKS
A list of pose landmarks. Each landmark consists of the following:

x and y: Landmark coordinates normalized to [0.0, 1.0] by the image width and height respectively.
z: Should be discarded as currently the model is not fully trained to predict depth, but this is something on the roadmap.
visibility: A value in [0.0, 1.0] indicating the likelihood of the landmark being visible (present and not occluded) in the image._

**Comment by jkyleung** [comment]
you should be able to find the method you need in LandmarkProto.class:
`public boolean hasVisibility() {
            return (this.bitField0_ & 8) != 0;
        }

        public float getVisibility() {
            return this.visibility_;
        }

        private void setVisibility(float value) {
            this.bitField0_ |= 8;
            this.visibility_ = value;
        }

        private void clearVisibility() {
            this.bitField0_ &= -9;
            this.visibility_ = 0.0F;
        }`
