### ISSUE TITLE
"z" Normalisation

### ISSUE THREAD

**Issue by ZohrehKhosroebigi** [google/mediapipe#2514]

**Comment by ZohrehKhosroebigi** [comment]
Hi,
I am using Mediapipe Face Mesh to compute the Euclidean distance of the points. I normalized the "x", "y" ratio width and height. But, I don't know how to normalize the "Z". The distance is different since the face is going backwards or forward. That's why I need to use "Z". 
I would appreciate your response.

**Comment by sgowroji** [comment]
Hi @ZohrehKhosroebigi, This https://github.com/google/mediapipe/issues/742#issuecomment-639104199 guides you well. Thanks!

**Comment by ZohrehKhosroebigi** [comment]
> Hi @ZohrehKhosroebigi, This [#742 (comment)](https://github.com/google/mediapipe/issues/742#issuecomment-639104199) guides you well. Thanks!

Thank you very much.
