### ISSUE TITLE
Docker Installation Mediapipe.

### ISSUE THREAD

**Issue by khazamaa** [google/mediapipe#2517]
I was following the documentation given here: https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker

## Description of issue:
In the docker installation step the last line is
``` 
bazel build -c opt --config=android_arm64 
mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu:objectdetectiongpu
 ```
I ran this command and i got the results as given in the documentation. 
Since, i'm new to android can anyone tell me where the apk that was made is now?
I'm also not able to install adb in the docker container.
So, is their any way i can check the apk that has been built inside the container ?

**Comment by sgowroji** [comment]
Hi @khazamaa, you will find the apk at this path 
`
bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu/objectdetectiongpu.apk 
`
As logs printed in your console.
