### ISSUE TITLE
run AudioDecoderCalculator error

### ISSUE THREAD

**Issue by RTCFoundation** [google/mediapipe#2518]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
CentOS release 6.3
- Programming Language and version
 C++
- [MediaPipe version] 
0.6.8

I write a test based on AudioDecoderCalculator, And I expect it can run the process func of calculator serveral times.
But It happens errors, can u give me some help
the demo code is :
`::mediapipe::Status DecodeTest() {
  // Configures a simple graph, which concatenates 2 PassThroughCalculators.
  CalculatorGraphConfig config = ParseTextProtoOrDie<CalculatorGraphConfig>(R"(
    node {
      calculator: "AudioDecoderCalculator"
      input_side_packet: "INPUT_FILE_PATH:input_file_path"
      input_side_packet: "OPTIONS:options"
      output_stream: "AUDIO:audio"
      output_stream: "AUDIO_HEADER:audio_header"
    }
  )");

  std::map<std::string, Packet> input_side_packets;
  std::string url = "sine_wave_1k_48000_stereo_2_sec_wav.audio";
  input_side_packets["input_file_path"] = MakePacket<std::string>(url);

  mediapipe::AudioDecoderOptions options;
  options.add_audio_stream()->set_stream_index(0);
  input_side_packets["options"] = MakePacket<AudioDecoderOptions>(options);

  CalculatorGraph graph;
  MP_RETURN_IF_ERROR(graph.Initialize(config, input_side_packets));
  MP_RETURN_IF_ERROR(graph.StartRun({}));

  mediapipe::Packet packet;
  ASSIGN_OR_RETURN(OutputStreamPoller poller,
                   graph.AddOutputStreamPoller("audio"));
  while (poller.Next(&packet)) {
    LOG(INFO) << "obtain a packet";
  }

  return graph.WaitUntilDone();
}
int main(int argc, char** argv) {
  // Parse gflags. We recommend you to use gflags as well.
  google::ParseCommandLineFlags(&argc, &argv, true);

  google::InitGoogleLogging(argv[0]);

  CHECK(DecodeTest().ok());
  return 0;
}`

**Here's the log**
TRACE: 09-08 15:14:54:   * 0 baidu/third-party/mediapipe/mediapipe/util/audio_decoder.cc:646] Created audio processor 0x7fa944036970 for file "sine_wave_1k_48000_stereo_2_sec_wav.audio"
TRACE: 09-08 15:14:54:   * 0 baidu/third-party/mediapipe/mediapipe/util/audio_decoder.cc:374] Opened audio stream (id: 0, channels: 2, sample rate: 48000, time base: 1/48000).
FATAL: 09-08 15:14:54:   * 0 baidu/third-party/mediapipe/mediapipe/framework/input_stream_handler.cc:102] Check failed: unset_header_count_ > 0 (0 vs 0).
#0 0x00000150b9a2 mediapipe::InputStreamHandler::SetHeader()
#1 0x000001516e70 mediapipe::OutputStreamManager::PropagateHeader()
#2 0x00000151555d mediapipe::OutputStreamHandler::Open()
#3 0x0000014e4b96 mediapipe::CalculatorNode::OpenNode()
#4 0x00000153f7d6 mediapipe::internal::SchedulerQueue::OpenCalculatorNode()
#5 0x00000153eaaf mediapipe::internal::SchedulerQueue::RunNextTask()
#6 0x0000015075a7 _ZZN9mediapipe8Executor7AddTaskEPNS_9TaskQueueEENKUlvE_clEv
#7 0x000001507769 _ZNSt17_Function_handlerIFvvEZN9mediapipe8Executor7AddTaskEPNS1_9TaskQueueEEUlvE_E9_M_invokeERKSt9_Any_data
#8 0x0000004c5a72 std::function<>::operator()()
#9 0x000001569fc0 mediapipe::ThreadPool::RunWorker()
#10 0x0000015698ec mediapipe::ThreadPool::WorkerThread::ThreadBody()
#11 0x7fa949f8eda4 <unknown>
#12 0x7fa949bcd32d set_regs
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
Aborted

**Comment by sgowroji** [comment]
Hi @RTCFoundation, Could you please provide the steps to reproduce the above error. Thanks!
