### ISSUE TITLE
Build simple demo error : opencv2 deps not found

### ISSUE THREAD

**Issue by tomleader** [google/mediapipe#2519]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Mac OS Big Sur 11.4 (with M1 cpu)
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): clang-1205.0.22.11
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): C++
- Installed using virtualenv? pip? Conda? (if python): pyenv with Python 3.9.6
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.7
- Bazel version: 4.2.1
- XCode and Tulsi versions (if iOS): no Xcode but had installed commandLineTools
- Android SDK and NDK versions (if android): no
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): no
- OpenCV version (if running on desktop): 3.4.14

**Describe the problem**:
Can't build the simple object_tracking demo and the error shows 'opencv2 not found'

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/object_tracking:object_tracking_cpu --verbose_failure
```

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:
```
DEBUG: /private/var/tmp/_bazel_linktang/253fd62c8974832652625deefa71017b/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_linktang/253fd62c8974832652625deefa71017b/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_linktang/253fd62c8974832652625deefa71017b/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_linktang/253fd62c8974832652625deefa71017b/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_linktang/253fd62c8974832652625deefa71017b/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_linktang/253fd62c8974832652625deefa71017b/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_linktang/253fd62c8974832652625deefa71017b/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_linktang/253fd62c8974832652625deefa71017b/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /private/var/tmp/_bazel_linktang/253fd62c8974832652625deefa71017b/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Analyzed target //mediapipe/examples/desktop/object_tracking:object_tracking_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[36 / 1,155] 128 actions, 8 running
[39 / 1,155] 128 actions, 8 running
[41 / 1,155] 128 actions, 8 running
[42 / 1,155] 128 actions, 7 running
[43 / 1,155] 128 actions, 8 running
[44 / 1,155] 128 actions, 8 running
[44 / 1,155] 128 actions, 8 running
ERROR: /Users/linktang/workspace/mediapipe/mediapipe/examples/desktop/BUILD:38:11: Compiling mediapipe/examples/desktop/demo_run_graph_main.cc failed: (Exit 1): cc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_linktang/253fd62c8974832652625deefa71017b/sandbox/darwin-sandbox/1866/execroot/mediapipe && \
  exec env - \
    PATH=/Users/linktang/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-arm64/bin:/opt/homebrew/opt/opencv@3/bin:/Users/linktang/.pyenv/shims:/Users/linktang/workspace/emsdk:/Users/linktang/workspace/emsdk/upstream/emscripten:/Users/linktang/workspace/emsdk/node/14.15.5_64bit/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    PWD=/proc/self/cwd \
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/darwin_arm64-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.d '-frandom-seed=bazel-out/darwin_arm64-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o' -DMEDIAPIPE_PROFILER_AVAILABLE '-DMEDIAPIPE_DISABLE_GPU=1' -iquote . -iquote bazel-out/darwin_arm64-opt/bin -iquote external/com_github_glog_glog -iquote bazel-out/darwin_arm64-opt/bin/external/com_github_glog_glog -iquote external/com_github_gflags_gflags -iquote bazel-out/darwin_arm64-opt/bin/external/com_github_gflags_gflags -iquote external/com_google_absl -iquote bazel-out/darwin_arm64-opt/bin/external/com_google_absl -iquote external/com_google_protobuf -iquote bazel-out/darwin_arm64-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/darwin_arm64-opt/bin/external/zlib -iquote external/linux_opencv -iquote bazel-out/darwin_arm64-opt/bin/external/linux_opencv -Ibazel-out/darwin_arm64-opt/bin/external/com_github_glog_glog/_virtual_includes/default_glog_headers -Ibazel-out/darwin_arm64-opt/bin/external/com_github_gflags_gflags/_virtual_includes/gflags -isystem external/com_google_protobuf/src -isystem bazel-out/darwin_arm64-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/darwin_arm64-opt/bin/external/zlib -w '-std=c++17' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c mediapipe/examples/desktop/demo_run_graph_main.cc -o bazel-out/darwin_arm64-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o)
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
[45 / 1,155] 127 actions, 8 running
In file included from mediapipe/examples/desktop/demo_run_graph_main.cc:22:
In file included from ./mediapipe/framework/formats/image_frame_opencv.h:20:
./mediapipe/framework/port/opencv_core_inc.h:18:10: fatal error: 'opencv2/core/version.hpp' file not found
#include <opencv2/core/version.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[45 / 1,155] 127 actions, 8 running
Target //mediapipe/examples/desktop/object_tracking:object_tracking_cpu failed to build
INFO: Elapsed time: 2.290s, Critical Path: 2.06s
INFO: 139 processes: 129 internal, 10 darwin-sandbox.
FAILED: Build did NOT complete successfully

```

AND THE EXTRA INFO:
I had read the install-guide and install opencv by homebrew, but I try Not to modify the origin WORKSPACE file and the opencv BUILD file,
so I decide to make a soft-link to the specify location:
```
sudo ln -sf /opt/homebrew/Cellar/opencv@3/3.4.14_3 /usr/local/opt/opencv@3
```
so if I was right, the build process should find the right hpp file... but the upper error occur...
I also try to make the same soft-link to /usr/local/include but same error occur...
What should I do to make it work ?

**Comment by sgowroji** [comment]
Hi @tomleader, Could you point us which  steps from this link https://google.github.io/mediapipe/getting_started/install.html#installing-on-macos encountered the error. Did you try checking with upgrading your opencv and verify the above. Thanks!

**Comment by sgowroji** [comment]
Try checking this command https://github.com/google/mediapipe/issues/970#issuecomment-667219458

**Comment by tomleader** [comment]
> Thanks

I did follow the install guid and the install process is OK. The hello-world demo is OK.
I had only one opencv version(opencv@3) installed, since the upper comment also mention that 'mediapipe recommends opencv3' , so I think I should not upgrade the opencv now.

**Comment by tomleader** [comment]
And I make a simple cpp file to test if my env is right.
test.cpp:
```
#include <iostream>
#include <opencv2/core/version.hpp>

int main()
{
    return 0;
}
```
then run:
```
g++ test.cpp
./a.out
```
And  no error occur! 
So I think  my env is ok( since the cpp include CAN search the right place)
But the mediapipe demo build still cause error 'opencv2/core/version.hpp' file not found

**Comment by tomleader** [comment]
Updated:(xx hours pass)
I try to make a soft link from opencv2 folder to /usr/local/include and the opencv2 not found error had gone...
```
 sudo ln -sf /opt/homebrew/Cellar/opencv@3/3.4.14_3/include/opencv2 /usr/local/include/opencv2 
```
Anyone who met this error DO NOT copy the command directly.. try to understand the g++ include path first! 

But then I met a new error:

```
ERROR: /Users/linktang/workspace/mediapipe/mediapipe/examples/desktop/object_tracking/BUILD:19:10: Linking mediapipe/examples/desktop/object_tracking/object_tracking_cpu failed: (Exit 1): cc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_linktang/253fd62c8974832652625deefa71017b/sandbox/darwin-sandbox/3878/execroot/mediapipe && \
  exec env - \
    PATH=/Users/linktang/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-arm64/bin:/opt/homebrew/opt/opencv@3/bin:/Users/linktang/.pyenv/shims:/Users/linktang/workspace/emsdk:/Users/linktang/workspace/emsdk/upstream/emscripten:/Users/linktang/workspace/emsdk/node/14.15.5_64bit/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    PWD=/proc/self/cwd \
  external/local_config_cc/cc_wrapper.sh @bazel-out/darwin_arm64-opt/bin/mediapipe/examples/desktop/object_tracking/object_tracking_cpu-2.params)
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
ld: library not found for -l:libopencv_core.so
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //mediapipe/examples/desktop/object_tracking:object_tracking_cpu failed to build
INFO: Elapsed time: 136.538s, Critical Path: 92.95s
INFO: 2969 processes: 489 internal, 2480 darwin-sandbox.
FAILED: Build did NOT complete successfully

```

I'm trying to fix...ing

**Comment by tomleader** [comment]
> Updated:(xx hours pass)
> I try to make a soft link from opencv2 folder to /usr/local/include and the opencv2 not found error had gone...
> 
> ```
>  sudo ln -sf /opt/homebrew/Cellar/opencv@3/3.4.14_3/include/opencv2 /usr/local/include/opencv2 
> ```
> 
> Anyone who met this error DO NOT copy the command directly.. try to understand the g++ include path first!
> 
> But then I met a new error:
> 
> ```
> ERROR: /Users/linktang/workspace/mediapipe/mediapipe/examples/desktop/object_tracking/BUILD:19:10: Linking mediapipe/examples/desktop/object_tracking/object_tracking_cpu failed: (Exit 1): cc_wrapper.sh failed: error executing command 
>   (cd /private/var/tmp/_bazel_linktang/253fd62c8974832652625deefa71017b/sandbox/darwin-sandbox/3878/execroot/mediapipe && \
>   exec env - \
>     PATH=/Users/linktang/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-arm64/bin:/opt/homebrew/opt/opencv@3/bin:/Users/linktang/.pyenv/shims:/Users/linktang/workspace/emsdk:/Users/linktang/workspace/emsdk/upstream/emscripten:/Users/linktang/workspace/emsdk/node/14.15.5_64bit/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
>     PWD=/proc/self/cwd \
>   external/local_config_cc/cc_wrapper.sh @bazel-out/darwin_arm64-opt/bin/mediapipe/examples/desktop/object_tracking/object_tracking_cpu-2.params)
> Execution platform: @local_execution_config_platform//:platform
> 
> Use --sandbox_debug to see verbose messages from the sandbox
> ld: library not found for -l:libopencv_core.so
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> Target //mediapipe/examples/desktop/object_tracking:object_tracking_cpu failed to build
> INFO: Elapsed time: 136.538s, Critical Path: 92.95s
> INFO: 2969 processes: 489 internal, 2480 darwin-sandbox.
> FAILED: Build did NOT complete successfully
> ```
> 
> I'm trying to fix...ing

Seems that the BUILD file maybe find the wrong config....
the libopencv*.so can not be found in the opencv install folder
the libopencv*.dylib can be found
So I think the build process somehow use the opencv_linux.BUILD but in fact my computer is macos,
then I modify the opencv_linux.BUILD, copy the opencv_macos.BUILD then replace the opencv_linux.BUILD content...
then I run the build again and the build process is ok now.

**Comment by sgowroji** [comment]
Glad to know you resolved. And Thank you for updating your fix.

**Comment by brhenrique** [comment]
I had to change the path to `macos_opencv` in `WORKSPACE` from to this

```
new_local_repository(
    name = "macos_opencv",
    build_file = "@//third_party:opencv_macos.BUILD",
    # For local MacOS builds, the path should point to an opencv@3 installation.
    # If you edit the path here, you will also need to update the corresponding
    # prefix in "opencv_macos.BUILD".
    path = "/opt/homebrew",
)
```

`path` was set to `/usr/local` before that

**Comment by martin-etchart** [comment]
> I had to change the path to `macos_opencv` in `WORKSPACE` to:
> 
> ```
> new_local_repository(
>     name = "macos_opencv",
>     build_file = "@//third_party:opencv_macos.BUILD",
>     # For local MacOS builds, the path should point to an opencv@3 installation.
>     # If you edit the path here, you will also need to update the corresponding
>     # prefix in "opencv_macos.BUILD".
>     path = "/opt/homebrew",
> )
> ```
> 
> `path` was set to `/usr/local` before that

This alone worked for me. Seems to be the proper solution (in my case mediapipe build was already picking the correct opencv_macos.BUILD).

Thank you!

**Comment by Foaly** [comment]
I hade a similar error of opencv header that could not be found, when trying to compile on macOS 15.7 with OpenCV 4.

Following the instructions in https://github.com/google-ai-edge/mediapipe/blob/master/third_party/opencv_macos.BUILD
fixed to build error for me.
