### ISSUE TITLE
Locations of 468-d face mesh

### ISSUE THREAD

**Issue by abedicodes** [google/mediapipe#2520]
How can I find the corresponding locations of 468-d face mesh on the face? e.g., (x, y, z)_1 is on the nose, (x, y, z)_400 is on the left ear, etc.

**Comment by sgowroji** [comment]
Hi @abedicodes, You can find the coordinates on face mesh in this [image](https://raw.githubusercontent.com/google/mediapipe/master/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png).

**Comment by abedicodes** [comment]
Thank you for your answer. Do you know how I can find [facial action units](https://imotions.com/blog/facial-action-coding-system/) from this face mesh?

**Comment by kostyaby** [comment]
Hey @abedicodes,

This is not something MediaPipe provides publicly at the moment, so you'd have to build such system on top of the face mesh solution

**Comment by abedicodes** [comment]
Thanks
