### ISSUE TITLE
Using a simplified model for face mesh

### ISSUE THREAD

**Issue by abedicodes** [google/mediapipe#2521]
Is there any way to load and use a simpler model for face mesh? e.g., the model extracts 100-d face mesh from each frame instead of 468-d face mesh?

**Comment by sgowroji** [comment]
Hi @abedicodes, Could you please elaborate with more specific details. May be you can try understanding the model from [here](https://google.github.io/mediapipe/solutions/face_mesh) And choose the platform in which you are familiar and draw the mesh with limited coordinates.
