### ISSUE TITLE
A mediapipe model to extract head pose features (yaw, pitch, roll)

### ISSUE THREAD

**Issue by abedicodes** [google/mediapipe#2522]
Is there any mediapipe model to extract head pose (yaw, pitch, roll) features? Or is there any way to estimate head pose features from face mesh features?

**Comment by sgowroji** [comment]
Hi @abedicodes, There are lot you can try with [Gace Geometry API  ](https://google.github.io/mediapipe/solutions/face_mesh.html#face-geometry-module). Please have a look at our documentation and reach us back if you still have any specific queries w.r.t to it. Thanks!
