### ISSUE TITLE
Pose and Holistic cannot work on picture with more than one person?

### ISSUE THREAD

**Issue by sinoboy168** [google/mediapipe#2524]
It seems not work. Or what's wrong?

**Comment by sgowroji** [comment]
Hi @sinoboy168, Could you please provide the steps to reproduce the above issue. Thanks!

**Comment by sinoboy168** [comment]
![annotated_image0](https://user-images.githubusercontent.com/41009721/132642593-904b91c7-4a92-4179-91d2-7c39429b9f46.png)
![annotated_image1](https://user-images.githubusercontent.com/41009721/132642601-fb42bd2d-6873-4e4e-8842-8d8d812ab652.png)
Hello, thanks for you reply.
I use the demo code for holistic with python for static pictures. It seems work well on single man pictures, while failed in the other one with a few persons in it. So I doult that maybe it cannot work on pictures with more than one?

**Comment by sgowroji** [comment]
Hi @sinoboy168, Assuming [this](https://github.com/google/mediapipe/issues/1691#issuecomment-797159603) would answer your above query. Please reach us back if you still have any queries specific to the above context. Thanks!
