### ISSUE TITLE
How to configure the bazel BUILD file to create a dynamic framework for face detection cpu for iOS?

### ISSUE THREAD

**Issue by IsaacCavalcante** [google/mediapipe#2525]
**System information**
- OS Platform and Distribution (iOS 12.0):
- Programming Language and version (Swift 5.0):
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.7.1
- Bazel version: 4.2.1
- XCode and Tulsi versions (if iOS): XCode 12.5.1/ Tulsi 0.20210318.88

I already got to build FaceDetectionCpu App example for iOS, but I cant to configure the same BUILD file to create a dynamic framework.
Can anyone provide or help me to configure the BUILD file to create a dynamic framework for FaceDetectionCpu?

I know that exists the bazel rule ios_framework to setting this, but is quite confuse to setting them. Can anyone help me with this?

**Comment by sgowroji** [comment]
Hi @IsaacCavalcante, You may refer this issues for the above #364,#725,#1549,#2275. Thanks!
