### ISSUE TITLE
 Error while building graph of mediapipe

### ISSUE THREAD

**Issue by HieuNT1998** [google/mediapipe#2527]
I am integrating mediapipe facedetection into an exist android project. I followed guideline on the medipipe tutorial page. 
https://google.github.io/mediapipe/getting_started/android_archive_library.html

I built the aar library but having problems when building face detection graph.
There was no error during the build process. However, when integrated into Android, the app is killed after starting camera.
![Screenshot from 2021-09-09 22-51-14](https://user-images.githubusercontent.com/40411081/132724621-84a709e0-131e-4442-b460-212fe4487951.png)

I think my aar library has no problem because i used the graph file which is built available online. App works normally.

**Comment by sgowroji** [comment]
Hi @HieuNT1998, Can you try checking the workarounds mentioned in this https://github.com/google/mediapipe/issues/1407
