### ISSUE TITLE
Modify utilize_ Visibility: false, the tracking point still exists after compilation

### ISSUE THREAD

**Issue by sensen1010** [google/mediapipe#2529]
By modifying mediapipe/mediapipe/graphs/pose_tracking/subgraphs/pose_renderer_gpu.pbtxt.
Modify node information,utilize_visibility: false
After compilation, it is found that punctuation still exists in the video
Where do I need to modify to remove the tracking point？
> # Converts landmarks to drawing primitives for annotation overlay.
node {
  calculator: "LandmarksToRenderDataCalculator"
  input_stream: "NORM_LANDMARKS:pose_landmarks"
  input_stream: "RENDER_SCALE:render_scale"
  output_stream: "RENDER_DATA:landmarks_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.LandmarksToRenderDataCalculatorOptions] {
      landmark_connections: 0
      landmark_connections: 1
      ...
      landmark_color { r: 255 g: 255 b: 255 }
      connection_color { r: 255 g: 255 b: 255 }
      thickness: 3.0
      visualize_landmark_depth: false
      utilize_visibility: false
      visibility_threshold: 0.5
    }
  }
}

**Comment by sgowroji** [comment]
Hi @sensen1010, Could you please elaborate your use case. What do you mean by removing the tracking points on the pose gpu rendered graph?
