### ISSUE TITLE
Thank you，but audio can support on android or ios platform in mediapipe/example ?

### ISSUE THREAD

**Issue by rzyangKyle** [google/mediapipe#253]
Audio feature extraction is already supported in MediaPipe. If you see [the youtube8m feature extraction graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/youtube8m/feature_extraction.pbtxt), it extracts both video and audio features. The audio subgraph starts at [line 124](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/youtube8m/feature_extraction.pbtxt#L124) and the model is [VGGish](https://github.com/tensorflow/models/tree/master/research/audioset/vggish)

_Originally posted by @jiuqiant in https://github.com/google/mediapipe/issues/251#issuecomment-554474388_

**Comment by eknight7** [comment]
Hi! We are planning to release an example of live audio usage for Android/iOS as well.

**Comment by mgyong** [comment]
@eknight7

**Comment by quire7** [comment]
@eknight7 @mgyong any update about the audio demo app support two input streams(video and audio)?
