### ISSUE TITLE
GLOG_logtostderr=1 : permission error

### ISSUE THREAD

**Issue by brianknauss** [google/mediapipe#2532]
I am attempting to use an input video for the holistic example using the following command:

`GLOG_logtostderr=1 bazel-mediapipe/mediapipe/examples/desktop/holistic_tracking \
    --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt \
    --input_video_path=/path/to/input.mp4 \
    --output_video_path=/path/to/output.mp4`

When I run the command with correct paths, I receive:
`zsh: permission denied: bazel-mediapipe/mediapipe/examples/desktop/holistic_tracking`

Permissions have been enabled for the entire directory:
`-rwxrwxrwx  1 brianknauss  staff  1114 Sep  5 20:51 BUILD`

Other notes:
- I'm running MacOS 11.5.2
- IDE is Visual Studio, but I have the same issue in Terminal
- The Hello World example runs correctly
- I have been able to run the solution example files with webcam

Any help would be appreciated.  I have not been able to find this issue after an entire day of searching.

**Comment by sgowroji** [comment]
Hi @brianknauss, I dont think its MediaPipe issue. You can go through this documentation which will help you [guide](https://softwaretested.com/mac/how-to-fix-permission-denied-in-terminal-mac/) to resolve the  permission error.

**Comment by brianknauss** [comment]
Thank you for confirming @sgowroji.  I'll close the ticket.
