### ISSUE TITLE
Pose landmarks： How to set MIN_DETECTION_CONFIDENCE and MIN_TRACKING_CONFIDENCE？

### ISSUE THREAD

**Issue by InvisibleLeVen** [google/mediapipe#2534]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):Windows10
- [MediaPipe version](https://github.com/google/mediapipe/releases):latest
- Bazel version:default
- Solution (e.g. FaceMesh, Pose, Holistic):pose tracking
- Programming Language and version ( e.g. C++, Python, Java):C++

**Describe the expected behavior:**
https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_cpu.pbtxt
According to the example in the comment, model_complexity, smooth_landmarks, enable_segmentation, and smooth_segmentation can be set through input_side_packet. How to set the two parameters of MIN_DETECTION_CONFIDENCE and MIN_TRACKING_CONFIDENCE? Are these two settings currently supported? I tried to use input_side_packet to set it but a parsing error occurred

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2419. There is already an open issue assigned to our engineers.
