### ISSUE TITLE
iOS 15 has WebGL 2 support activated by default, so please use GPU side ML in MediaPipe JS solutions on iOS, e.g. Pose

### ISSUE THREAD

**Issue by jadams777** [google/mediapipe#2536]
iOS 15 has WebGL 2 support activated by default, so please use GPU side ML in MediaPipe JS solutions on iOS, e.g. Pose

![FE28B72F-4109-4F56-89FD-F118B12D729D](https://user-images.githubusercontent.com/71771407/132949004-625533cb-b4b4-412c-9b85-9926da42bb28.png)

**Comment by jadams777** [comment]
![Uploading 078DCAC5-B1E7-415F-A7C2-B0F76D7EA38B.png…]()

**Comment by jadams777** [comment]
![51037808-4CDB-4C07-960F-CB553A5038A0](https://user-images.githubusercontent.com/71771407/132949396-ec50b895-332c-475b-9fc3-77d9e1136bfe.png)

**Comment by tyrmullen** [comment]
Leaving issue open, as this would be nice to have as the default behavior.  However, for now, the boolean option 'useCpuInference' can be used to control whether inference is CPU-based or GPU-based, so you can develop your own tests/overrides using this option.

**Comment by tyrmullen** [comment]
It's not exposed in any of the type interfaces, as it's not part of the officially supported public API, but it can still be used all the same.  Just extend Options yourself to have that field (and make sure it's not compiled away by your TS compiler).

Taking pose as an example, if you look at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.4.1633558788/pose.js, you can see that 'useCpuInference' is used in unobfuscated plaintext, implying that this option should still be usable for that API.

**Comment by kuaashish** [comment]
Hello @jadams777,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
