### ISSUE TITLE
displaying the skeletal structure 

### ISSUE THREAD

**Issue by shivaprasadgh** [google/mediapipe#2537]
This template is for miscellaneous issues not covered by the other issue categories

For questions on how to work with MediaPipe, or support for problems that are not verified bugs in MediaPipe, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mediapipe) and [Slack](https://mediapipe.page.link/joinslack) communities.

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/google/mediapipe/security).

For high-level discussions about MediaPipe, please post to discuss@mediapipe.org, for questions about the development or internal workings of MediaPipe, or if you would like to know how to contribute to MediaPipe, please post to developers@mediapipe.org.

Is it possible to just display the skeletal structure of hand , after using hand detection algorithm given by Mediapipe?? I wanted to know if i send in an image through hand detection algorithm , will i get just the skeletal structure with various landmarks??

I am working with webcam to get images on laptop , I want to just display the skeletal structures of both hands ,without the captured  image from camera , in another window just the tip points . I am using python programming.

**Comment by sgowroji** [comment]
Hi @shivaprasadgh, You can try the  solutions mentioned in this https://github.com/google/mediapipe/issues/1743 for Hands solution graph.

**Comment by shivaprasadgh** [comment]
I was curious  if it would work with python programming , the reference which you sent me above is related to Android Platform .

**Comment by sgowroji** [comment]
Hi @shivaprasadgh, We dont have any direct examples to demonstrate your use case.  You can try something similar using this https://github.com/google/mediapipe/issues/1920#issuecomment-826954189
