### ISSUE TITLE
Is there an option of SMOOTH_LANDMARKS on the iOS platform？

### ISSUE THREAD

**Issue by MenThu** [google/mediapipe#2538]
I am experiencing the demo of posetrackingGPU（iPhoneX,iOS14.0.1）
i found that the landmarks of the posetracking are very jittery
I checked the [documentation](https://google.github.io/mediapipe/solutions/pose.html#smooth_landmarks) and found that smooth_landmarks is optional in the Python Solution API item
I want to know if there is a similar way to set it on the iOS platform?
thans you

**Comment by shrey-rootally** [comment]
Hey did find any solution?

**Comment by weihong-xuan** [comment]
Has anyone encountered this problem?

**Comment by roimulia2** [comment]
Did you find the solution? :)

**Comment by zhuzhuxingtianxia** [comment]
I have the same problem and don't know how to set the options？

**Comment by MenThu** [comment]
@zhuzhuxingtianxia @roimulia2 
Ensure that the timestamp of the input video frame is incremented, and there will be no jitter in the output landmarks

**Comment by zhuzhuxingtianxia** [comment]
So how to set it? No API found available

**Comment by EEWenbinWu** [comment]
Did you find the solution? :)

**Comment by kuaashish** [comment]
Hello @MenThu,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
