### ISSUE TITLE
How to run Hand_Tracking_demo in the 3D mode?

### ISSUE THREAD

**Issue by 1187697147** [google/mediapipe#254]
I have run the hand_tracking_demo succeddfully on the desktop(Ubuntu/GPU), but i really want to know how to run the 3D mode.

**Comment by eknight7** [comment]
You can replace the full model path in the desktop graph. For desktop GPU, you use: https://mediapipe.readthedocs.io/en/latest/hand_tracking_desktop.html#tensorflow-lite-hand-tracking-demo-with-webcam-gpu
The example says to use the following graph: https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt
which in turn uses the following `HandLandmark` subgraph:
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/hand_landmark_gpu.pbtxt

In the `HandLandmark` subgraph, replace `mediapipe/models/hand_landmark.tflite` with `mediapipe/models/hand_landmark_3d.tflite`.
Then run the app as before.
