### ISSUE TITLE
How to merge hand, face and pose landmark together in holistic？

### ISSUE THREAD

**Issue by KlickYang** [google/mediapipe#2540]
How to merge the hand, face and pose 3D landmark together in holistic?

**Comment by sgowroji** [comment]
Hi @KlickYang, Did you get a chance to go through our [documentation](https://google.github.io/mediapipe/solutions/holistic#overview). And can you elaborate your use case with complete details. Thanks!

**Comment by KlickYang** [comment]
Hello@sgowroji, thanks for answer. I have converted the tflite models (such as facemesh, hand landmark, pose landmark, hand detection...) into tensorrt and  reimplemented the holistic pipeline based on tensorrt. Now I have got the face, pose and hand 3D landmarks seperatedly. I want to drive avatar using theses landmarks.  So I want to know how to merge the landmarks together? I didn't find the solution in mediapipe or I missed it.

**Comment by Ram-Godavarthi** [comment]
> Hello @sgowroji , thanks for answer. I have converted the tflite models (such as facemesh, hand landmark, pose landmark, hand detection...) into tensorrt and reimplemented the holistic pipeline based on tensorrt. Now I have got the face, pose and hand 3D landmarks seperatedly. I want to drive avatar using theses landmarks. So I want to know how to merge the landmarks together? I didn't find the solution in mediapipe or I missed it.

Which version of TensorRT have you used ??
Could you share the details. 
Thank you

**Comment by sgowroji** [comment]
Hi @KlickYang, We will let you know if there are any update on your request. But present we don't have any  plans to open source as mentioned here https://github.com/google/mediapipe/issues/1678#issuecomment-794655361.
