### ISSUE TITLE
Will Core ML delegate get supported?

### ISSUE THREAD

**Issue by SunXuan90** [google/mediapipe#2543]
After TensorFlow Lite 2.4 there is a new [Core ML delegate](https://www.tensorflow.org/lite/performance/coreml_delegate) for iOS, will it be supported by MediaPipe? Thanks!

**Comment by sgowroji** [comment]
Hi @Epitapher, Could you please elaborate your use case with Core ML delegate on iOS. Thanks!

**Comment by SunXuan90** [comment]
> Hi @Epitapher, Could you please elaborate your use case with Core ML delegate on iOS. Thanks!

I've tried pose tracking gpu example on an Android phone with Snapdragon 765 and iPhone XS. The Android phone got around 30 fps which is pretty good, and I expected iPhone XS would outperform that by a large margin but it only got around 20fps. I see that MediaPipe currently uses metal gpu delegate, so I wonder if the new Core ML delegate would make a difference.

**Comment by fchen09** [comment]
> > Hi @Epitapher, Could you please elaborate your use case with Core ML delegate on iOS. Thanks!
> 
> I've tried pose tracking gpu example on an Android phone with Snapdragon 765 and iPhone XS. The Android phone got around 30 fps which is pretty good, and I expected iPhone XS would outperform that by a large margin but it only got around 20fps. I see that MediaPipe currently uses metal gpu delegate, so I wonder if the new Core ML delegate would make a difference.

@SunXuan90 
Hi, sir. How do you get 30 fps? because I only get 15 fps with snapdragon 855.

**Comment by kuaashish** [comment]
Hello @SunXuan90,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by SunXuan90** [comment]
@fchen09 It depends on the model you run. For blazepose light it's easy to get 30fps with gpu solution.

**Comment by SunXuan90** [comment]
@kuaashish I see that "new solutions" are not ready for pose estimation. But I'll close the issue for now.
