### ISSUE TITLE
Failed to build mediapipe package in python using bazel in Windows Linux Subsystem, ubuntu 18.04

### ISSUE THREAD

**Issue by sandesh1994199** [google/mediapipe#2545]
- OS Platform and Distribution :Windows linux subsystem, ubuntu 18.04
- Bazel version: 3.7.2

@sgowroji I am facing a error as mentioned below 

(mp2_env) snagaraj@-0:/mnt/c/users/snagaraj/Documents/git_repos/git_IRIS$ python3 setup.py install --link-opencv
running install
running build_binary_graphs
fail to get bazel version by $ bazel --version: b"\x1b[31mERROR: The project you're trying to build requires Bazel 3.7.2\r (specified in /mnt/c/users/snagaraj/Documents/git_repos/git_IRIS/.bazelversion), but it wasn't found in /usr/bin.\x1b[0m\n\nYou can install the required Bazel version via apt:\n  sudo apt update && sudo apt install bazel-3.7.2\r\n\nIf this doesn't work, check Bazel's installation instructions for help:\n  https://docs.bazel.build/versions/master/install-ubuntu.html\n"

1. if i check bazel version in the working directory 

(mp2_env) snagaraj@-0:/mnt/c/users/snagaraj/Documents/git_repos/git_IRIS$ bazel --version
 (specified in /mnt/c/users/snagaraj/Documents/git_repos/git_IRIS/.bazelversion), but it wasn't found in /usr/bin.

You can install the required Bazel version via apt:
  sudo apt update && sudo apt install bazel-3.7.2

2. but if i check in home directory 

snagaraj@-0:~$ bazel --version
bazel 3.7.2

**Comment by sgowroji** [comment]
Hi @sandesh1994199, Could you please share the complete error logs to understand the issue. Thanks!

**Comment by sandesh1994199** [comment]
@sgowroji  I have shared the complete error logs. I do not know what information is required apart from above.

**Comment by sgowroji** [comment]
if you are building the code in docker, try checking this https://github.com/google/mediapipe/issues/2236#issuecomment-871656205. Reach us back if you still have the above error. Thanks!

**Comment by sandesh1994199** [comment]
I am fallowing #1530 to implement iris in python in docker. But i run python3 setup.py bdist_wheel this command 

![image](https://user-images.githubusercontent.com/78213614/134153303-61ddba08-70a8-4bfc-a8d6-d0123889d8ec.png)

No progress

**Comment by jiuqiant** [comment]
"opencv_cmake" is expected to be slow.  Try "--link-opencv" if you can. 
For the bazel version issue, you can delete https://github.com/google/mediapipe/blob/master/.bazelversion to relax the version restriction.
