### ISSUE TITLE
why tensorflow protos in mediapipe/calculators/tensorflow IGNORE

### ISSUE THREAD

**Issue by Jwy-jump** [google/mediapipe#2548]
python questions:

the erro:
tensorflow/core/framework/types.proto: File not found.
mediapipe/calculators/tensorflow/vector_int_to_tensor_calculator_options.proto: Import "tensorflow/core/framework/types.proto" was not found or had errors.
mediapipe/calculators/tensorflow/vector_int_to_tensor_calculator_options.proto:42:12: "tensorflow.DataType" is not defined.
I find in setup.py:
      for proto_file in glob.glob(pattern, recursive=True):
        proto_dir = os.path.dirname(os.path.abspath(proto_file))
        # Ignore test protos.
        if proto_file.endswith('test.proto'):
          continue
        **# Ignore tensorflow protos in mediapipe/calculators/tensorflow.**
        if 'tensorflow' in proto_dir:
          continue
        # Ignore testdata dir.
        if proto_dir.endswith('testdata'):
          continue
        init_py = os.path.join(proto_dir, '__init__.py')
        if not os.path.exists(init_py):
          sys.stderr.write('adding __init__ file: %s\n' % init_py)
          open(init_py, 'w').close()
        self._generate_proto(proto_file)

-------------------------------------------------------------------------------------
we want to try to implement python solution  which depends on some calculators defined under tensorflow directory, but as currently it is commented, it reports error failing to find such proto in python,thanks a lot !

**Comment by sgowroji** [comment]
Hi @Jwy-jump, Could you please share the error logs and steps to reproduce the above error. Thanks!

**Comment by Jwy-jump** [comment]
@sgowroji yes ,I want to add  some calculators defined under tensorflow directory, when i run python3 setup.py gen_protos:
tensorflow/core/framework/types.proto: File not found.
mediapipe/calculators/tensorflow/vector_int_to_tensor_calculator_options.proto: Import "tensorflow/core/framework/types.proto" was not found or had errors.
mediapipe/calculators/tensorflow/vector_int_to_tensor_calculator_options.proto:42:12: "tensorflow.DataType" is not defined.

**Comment by Jwy-jump** [comment]
thanks a lot and wait for your reply!

**Comment by jiuqiant** [comment]
The `gen_protos` only generates mediapipe python protos from the mediapipe source code directly. "tensorflow/core/framework/types.proto"  is a tensorflow proto, which is in the external repo that mediapipe can't see until Bazel downloads it.

**Comment by Jwy-jump** [comment]
thanks,but TFLITE can generates mediapipe python protos,only except tensorflow@jiuqiant

**Comment by jiuqiant** [comment]
I don't think the "gen_protos" command generates tflite python protos... The tensor/tflite inference calculator proto is also defined in MediaPipe not in TensorFlow repo.

We generally make MediaPipe solutions with tflite models and haven't explored using it with a  tensorflow model.
