### ISSUE TITLE
Easy way to get the score for hand tracking from results.multi_handedness 

### ISSUE THREAD

**Issue by mathmax12** [google/mediapipe#2549]
When   print(results.multi_handedness):
I got :

```
[classification {
  index: 1
  score: 0.9999532699584961
  label: "Right"
}
]
```

Is there an easy way to get the score in python?

**Comment by sgowroji** [comment]
Hi @mathmax12, Yes you can use the results to check the score and label  mentioned above.

**Comment by mathmax12** [comment]
if I want to access the label only what's the right way to do it.
print(results.multi_handedness[0].classification["score"])

 ```
   print(results.multi_handedness[0].classification["score"])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by sgowroji** [comment]
Hi @mathmax12, You can try the solutions from this https://github.com/google/mediapipe/issues/1374 issue
