### ISSUE TITLE
awesome work. How to use your tflite model to achieve hand tracking with python

### ISSUE THREAD

**Issue by shoutOutYangJie** [google/mediapipe#255]
Is it possible that I just want to use hand tracking tflite models with python and tensorflow.
In fact, I just want to finish a python demo, which resorts to your tflite models, rather than Adroid demo. Please give me the way. Thanks!!

**Comment by shoutOutYangJie** [comment]
And next question. I notice that both of multiple hand tracking and single hand tracking use "palm_detection.tflite" and "hand_landmark.tflite", so why does same model have different behavior?
Thanks!!

**Comment by eknight7** [comment]
>I notice that both of multiple hand tracking and single hand tracking use "palm_detection.tflite" and "hand_landmark.tflite", so why does same model have different behavior?

The MediaPipe graphs for single-hand tracking and multi-hand tracking are different. The documentation explains the difference between them: https://mediapipe.readthedocs.io/en/latest/multi_hand_tracking_mobile_gpu.html

**Comment by shoutOutYangJie** [comment]
> > I notice that both of multiple hand tracking and single hand tracking use "palm_detection.tflite" and "hand_landmark.tflite", so why does same model have different behavior?
> 
> The MediaPipe graphs for single-hand tracking and multi-hand tracking are different. The documentation explains the difference between them: https://mediapipe.readthedocs.io/en/latest/multi_hand_tracking_mobile_gpu.html

Thanks. How about the first quesiont. If I just want to run the tflite models on python environment, how to import palm_detection.tflite model correctly? I meet a error which desrcribes The conv2dtransposbias not parpare.  Thanks !

**Comment by lcycoding** [comment]
@shoutOutYangJie 
It seems like python binding of tf-lite has not yet implemented the operator you mentioned.
But Android, iOS and C++ are supported.

Take a look at https://www.tensorflow.org/lite/guide/ops_select

**Comment by shoutOutYangJie** [comment]
Why do not these tflite models support GPU. I import the models, and find they don't use GPU. But I have installed Tensorflow-gpu

**Comment by lcycoding** [comment]
@shoutOutYangJie 
In tflite world, gpu mode will be enabled only with gpu delegate mode. (Only for Android / iOS)
Tensorflow-gpu just support graph and eager gpu mode.

Check out this page: https://www.tensorflow.org/lite/performance/gpu_advanced

**Comment by mgyong** [comment]
@shoutOutYangJie What is your use case for getting hand tracking tflite models running in python? Are you trying to train a new model using keypoints generated by the MediaPipe hand tracking tflite models? Getting MediaPipe graphs & calculators to run in python is something we are looking at. If you have interest, pls contact me at mgyong at google dot com

**Comment by wolterlw** [comment]
@shoutOutYangJie I've implemented a minimal Python wrapper for single-hand models. For now it only runs on CPU because I haven't figured out how to compile a desktop-gpu delegate for tflite yet.
@mgyong if you could point me in the general direction where to look for the mesa delegate implementation - that would be very useful. Also I'd be interested in developing a Python wrapper for mediapipe calculators. That would clearly help with prototyping.

**Comment by shoutOutYangJie** [comment]
@wolterlw so Must I build tensorflow with custom ops? I find a repo, and it just depend on official original tensorflow2.0.
[here](https://github.com/metalwhale/hand_tracking)

**Comment by wolterlw** [comment]
@shoutOutYangJie hah, thanks for sharing the repo. It looks like @metalwhale has rebuilt the palm detection model without custom operations.
So what you have to do - grab .tflite files from his repo and use them with my code. Should work like a charm.
And if it doesn't - let me know.

**Comment by shoutOutYangJie** [comment]
@wolterlw  Thanks for your rapid reply. I notice the tflite tutorials at official website, there are some demo about how to use tiflite. I have tried deeplabV3 tflite model.  Surprisingly, I found it can use GPU. My system is Win10 and tf version is 2.0  @lcycoding

**Comment by wolterlw** [comment]
@shoutOutYangJie could you share the link to deeplabV3 code you've used? Because I've just tried to invoke tf.lite.Interpreter, but it runs on CPU only.
Maybe I'm missing something

**Comment by shoutOutYangJie** [comment]
> @shoutOutYangJie could you share the link to deeplabV3 code you've used? I've just tried to invoke tf.lite.Interpreter, but it runs on CPU only.
> Maybe I'm missing something

https://tensorflow.google.cn/lite/models/segmentation/overview 
It is from chinese community. You can also find it at tensorflow official website

**Comment by wolterlw** [comment]
@shoutOutYangJie well I've tried it - runs on CPU.
This is how I test it:
```
>>> import tensorflow as tf
>>> tf.__version__
'2.0.0'
>>> model_path = "~/data/weights/deeplabv3_257_mv_gpu.tflite"
>>> interp = tf.lite.Interpreter(model_path)
INFO: Initialized TensorFlow Lite runtime.
>>> interp.allocate_tensors()
>>> while True:
...    interp.invoke()
...
```
When I check nvidia-smi - 0 bytes of GPU Mem are used and no processes running either.

**Comment by shoutOutYangJie** [comment]
![image](https://user-images.githubusercontent.com/46734514/69843175-51d26900-12a1-11ea-9e3f-b3e3f22d732b.png)

I test my code My gpu is uesd to this code.
probably, you need sent a image to model.

**Comment by wolterlw** [comment]
interesting, can you link the exact same code to reproduce it?

**Comment by shoutOutYangJie** [comment]
@wolterlw 

![1](https://user-images.githubusercontent.com/46734514/69843343-fc4a8c00-12a1-11ea-90ea-b1143a5bcede.jpg)

import tensorflow as tf
import matplotlib.pyplot as plt


interpreter = tf.lite.Interpreter(model_path='deeplabv3.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print(input_details)
print(output_details)

def load_img(path_to_img):
  img = tf.io.read_file(path_to_img)
  img = tf.image.decode_image(img, channels=3)
  img = tf.image.convert_image_dtype(img, tf.float32)
  img = img[tf.newaxis, :]

  return img

def preprocess_style_image(style_image):
  # Resize the image so that the shorter dimension becomes 256px.
  target_dim = 257
  shape = tf.cast(tf.shape(style_image)[1:-1], tf.float32)
  short_dim = min(shape)
  scale = target_dim / short_dim
  new_shape = tf.cast(shape * scale, tf.int32)
  style_image = tf.image.resize(style_image, new_shape)

  # Central crop the image.
  style_image = tf.image.resize_with_crop_or_pad(style_image, target_dim, target_dim)

  return style_image
img = load_img('./1.jpg')
img = preprocess_style_image(img)
print(img.shape)
interpreter.set_tensor(input_details[0]['index'], img)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
index = tf.squeeze(tf.argmax(output_data,3))
print(index.shape)
plt.subplot(2, 1, 1)
plt.imshow(index)
plt.subplot(2, 1, 2)
plt.imshow(tf.squeeze(img))
plt.show()

**Comment by wolterlw** [comment]
I'm afraid it might be big-boy tensorflow interfering. Would be really helpful if you could load the mediapipe models and tell me the fps you're getting. Detection model is the larger one so ever running it alone would give a decent estimate
