### ISSUE TITLE
question about bounding box of pose detection

### ISSUE THREAD

**Issue by guker** [google/mediapipe#2550]
Hello, I have some question about bounding box of pose detection
i test some images and plot as follow( green bounding box is the output of pose detection):
![image](https://user-images.githubusercontent.com/4830247/133563297-eb11f727-cdbc-492a-8e4c-152a47a8a1c1.png)
![image](https://user-images.githubusercontent.com/4830247/133563338-1feedf64-902f-48bb-8089-d613ccc01d20.png)
two question:
1.   why the bounding box is so big? 
2.   what is the bounding box annotation of pose detection?

**Comment by sgowroji** [comment]
Hi @guker,  There is already a duplicate issue with above query https://github.com/google/mediapipe/issues/2140.  is open. And will try to get the resolution from the concern engineer on that issue.

**Comment by wycathy** [comment]
> Hello, I have some question about bounding box of pose detection i test some images and plot as follow( green bounding box is the output of pose detection): ![image](https://user-images.githubusercontent.com/4830247/133563297-eb11f727-cdbc-492a-8e4c-152a47a8a1c1.png) ![image](https://user-images.githubusercontent.com/4830247/133563338-1feedf64-902f-48bb-8089-d613ccc01d20.png) two question:
> 
> 1. why the bounding box is so big?
> 2. what is the bounding box annotation of pose detection?

Hi ,I am curious how you get this result？ just extract the pose detection tflite models？

**Comment by guker** [comment]
> 
yes
