### ISSUE TITLE
Attaching attaching to moving objects permanently

### ISSUE THREAD

**Issue by arijith96** [google/mediapipe#2551]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 20.02 Android 11 Android Studio with Gradle AAR
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version: v0.8.6
- Solution (e.g. FaceMesh, Pose, Holistic): Instant Motion Tracking
- Programming Language and version ( e.g. C++, Python, Java): Java

**Describe the expected behavior:**

I would like to know how it would be possible to make the placement of the stickers more permanent. (attached to a specific object)

The current implementation is such that, if there is an occlusion or if any other object moves past an already placed sticker, then the sticker would move along with the object occluding it. This is also observed when, after we place a sticker and, we move the camera around. The sticker is no longer in the initially placed position but is rather moved to a different place.

I think that this is due to the `RegionTrackingSubgraph` and how to operates. Does that calculator divide the region into multiple boxes? Please do correct me if I am wrong here, that's what I could infer from [this line](https://google.github.io/mediapipe/solutions/instant_motion_tracking.html#:~:text=3D%20region%20tracking%20for%20sticker%20placement%20and%20rendering).
Could you explain more as to how the `RegionTrackingSubgraph` works?

Would tracking a user-defined region (let's say a bounding box around some custom object/region) perform better?

Feels like a good continuation to #2049  :)

I intend to use this along with ARCore, so would like to get some input from your side.

**Comment by jianingwei** [comment]
Tracker works when you define a custom object/region as the initial bounding box. It doesn't do object detection, and relies on the initial bounding box provided to see the tracking. Inside RegionTrackingSubgraph, it analyzes global and local motion and estimate motion of the defined region/box. Occlusion can be a problem since some of the local features are "take away" by the occluding object. Same with camera motion causing objects to be outside field of view. If you want to know more details, we have a paper here: https://arxiv.org/abs/1907.06796

**Comment by arijith96** [comment]
Hi @jianingwei,

many thanks for your reply. Understood many concepts by going through your paper :) 

Could you please guide me on how I could go about using the custom region tracker along with instant motion tracking? My use case would be: The user would draw a bounding box on the screen around an object (for example a laptop) of interest. This is the region that we would need to track (300x300 pixels). Next, when we perform a click on the screen, we place the robot (as given in the instantmotiontracking example) at the centre of the custom region and as this region moves the robot also would need to move with it. (the region can move towards and away from the camera - so the robot should also follow perspective projection and this become small as we move away)

Please correct me if I am wrong here, but I think the bounding box tracking could be achieved with the Box Tracking Solution. But, I am confused as to how to proceed from there.

Looking forward to hearing from you :D

**Comment by jianingwei** [comment]
Yes, you can check out the mediapipe/graphs/instant_motion_tracking/instant_motion_tracking.pbtxt graph and see how you can connect region tracking with actually doing the AR placement. This requires the IMU input. If you want to see how the IMU signal is piped through, you can checkout the app: mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking/

**Comment by jianingwei** [comment]
More reading on this subject: https://developers.googleblog.com/2020/08/instant-motion-tracking-with-mediapipe.html

**Comment by arijith96** [comment]
Hi @jianingwei , thanks for all the info! :D I'll check them out! And come back to you when I have more questions

**Comment by arijith96** [comment]
Hi @jianingwei,

I had some time to work on this. I am currently am able to extract the pixel locations of my region of interest in a video stream. 
I am now stuck in trying to place the AR robot in the middle of that region and move the robot as my region moves. Could you help me with how I can proceed? 

I am using an [OpenCV approach](https://github.com/michaeltroger/feature-matching-native-android) and the KNIFT solution to obtain the pixel locations of my region in the video stream.

**Comment by ngthlong1990** [comment]
> Tracker works when you define a custom object/region as the initial bounding box. It doesn't do object detection, and relies on the initial bounding box provided to see the tracking. Inside RegionTrackingSubgraph, it analyzes global and local motion and estimate motion of the defined region/box. Occlusion can be a problem since some of the local features are "take away" by the occluding object. Same with camera motion causing objects to be outside field of view. If you want to know more details, we have a paper here: https://arxiv.org/abs/1907.06796

Hi [jianingwei](https://github.com/jianingwei),
I have read your paper and found this in section 3.4:
To make the effect more robust, we also allow for limited region tracking outside the camera’s field of view–enabling a virtual object to reappear in approximately the same spot when panning away and back again. Combining visual information for 3D translation and IMU data for 3D rotation lets us track and render virtual content correctly in the viewfinder with 6DoF, with the initial object scale being set by the user. With this parallelization, the system is fast and efficient, can track moving or static regions, and furthermore requires no calibration–it works on any device with a gyroscope.
Does this mean that we can maintain a tracking region that is out of view for a while? Could you please tell me more about how to make this possible?
Or is there a way we could pause tracking when we are out of sight of that region, and resume when we come back?
Thanks for any help.
