### ISSUE TITLE
how we can reduce the tremble from the mediapipe hand detection

### ISSUE THREAD

**Issue by sujilal** [google/mediapipe#2552]

**Comment by sgowroji** [comment]
Hi @sujilal, Could you please elaborate your query with complete details. Thanks!

**Comment by sujilal** [comment]
@sgowroji:  The mediapipe hand detection model after taking the frame getting tremble, you can check the example which mediapipe published. if I load any image using the mediapipe model, the image starts to tremble

**Comment by sgowroji** [comment]
Hi @sujilal, On which platform are you facing the above error. Can you provide a video reference of the above observation and any error logs to investigate it for further. Thanks!

**Comment by LMR2018** [comment]
@sujilal     Have you solved the problem yet?
