### ISSUE TITLE
why i build the posetracking aar's size more than 120M? others download from internet is 10M?

### ISSUE THREAD

**Issue by LTYF** [google/mediapipe#2556]
is model different?
and how to choose model for mobile(android)？

**Comment by brucechou1983** [comment]
duplicate issue https://github.com/google/mediapipe/issues/1008

**Comment by sgowroji** [comment]
Hi @LTYF, Can you try the workaround mentioned in the above [comment](https://github.com/google/mediapipe/issues/2556#issuecomment-924525008)

**Comment by LTYF** [comment]
yes，it works！thx
