### ISSUE TITLE
Relative position for mediapipe Pose model

### ISSUE THREAD

**Issue by SutirthaChakraborty** [google/mediapipe#2558]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): Pose 3D
- Programming language : Python
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state:**
A argument, which will enable to create a 3D plane and generate the **_3D relative keypoints_** on that 3D plane, irrespective of the person changing its position like _moving left to right_ or _moving close or away from the camera_. 

**Will this change the current api? How?**
It will be an extra added feature. 

**Who will benefit with this feature?**
For further training and processing the 3D or the 2D  keypoint information, it will help a lot for developers who only want to work with the person's poses.

**Please specify the use cases for this feature:**
A person playing a _drum in the air_ while moving around. 

**Any Other info:**

**Comment by sgowroji** [comment]
Hi @SutirthaChakraborty, Thank you for reaching us regarding the above issue. Could you please share us more details relevant to your above query.  And did you get a chance to check our [pose landmarks in world coordinates ](https://google.github.io/mediapipe/solutions/pose#pose_world_landmarks) and its annotations to help you understand its  implementation.

**Comment by SutirthaChakraborty** [comment]
For example, if I run pose estimation on these 4 images, they will generate the scaled down points(x,y,z)  based on the person located in the image.
![image](https://user-images.githubusercontent.com/47362033/134596662-8e48d2ef-059e-45d9-9880-d3a9f4ebcd82.png)

Can a feature be added, where it will give us the referential distance irrespective of the person's position from the camera and distance from the camera so that we can use those points to create a virtual space around the person ?

Ideally, in this case, the result will be the same for all the images as they have the same pose. 
Thanks,
 Suti

**Comment by SutirthaChakraborty** [comment]
Hi, is it feasible?

**Comment by sgowroji** [comment]
May need to apply some optimizations for calculating the relative distance as mentioned here  https://github.com/google/mediapipe/issues/1611

**Comment by jinfagang** [comment]
@sgowroji Does it avaibable now in 2023??

**Comment by SutirthaChakraborty** [comment]
@jinfagang  use pose_world_landmarks
[pose_world_landmarks](https://google.github.io/mediapipe/solutions/pose#pose_world_landmarks)

**Comment by ayushgdev** [comment]
@jinfagang We do offer the `pose_world_landmarks` attribute in the Pose solution. This will give 3D landmarks output with origin in hips center.
It provides z-keypoint which is an "estimate" from the GHUM model using 2D projecctions. The z-keypoint represents the distance "relative" to the plane of the subject's hips, which is the origin of the Z axis. So you can imagine a vertical place at the hip joint of the subject and any value <0 represents distance between camera and person.
So you can filter out negative valued z-keypoints to know if a key-point is between camera and hip or beyond. However, as the distance is relative, it cannot be used to reliably estimate  metric distance of real world. For details, please refer the model card [here](https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview)

**Comment by jinfagang** [comment]
@SutirthaChakraborty  I don't know if you understand this question or not, but ops are asking about body translation......

3d world landmark are using hips as original fixed points!

**Comment by ayushgdev** [comment]
@jinfagang Let us reassign to @hadon to provide a better perspective and solution to your query.

**Comment by jinfagang** [comment]
@andrechen Stop thumb down issue unrelated with you. Am asking my own questions, if you don't know just ignore, stop such down voted on your personal.

**Comment by kuaashish** [comment]
Hello @SutirthaChakraborty,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by ralarcong** [comment]
> @SutirthaChakraborty I don't know if you understand this question or not, but op was asking about body translation......
> 
> 3d world landmark are using hips as original fixed points!
> 
> @ayushgdev I got 3d landmark, but this doesn't gives me body translation in space.....
> 
> I don't know what's z keypoint? I really don't understand, I want translation, not x y z, the x y z is all related to hips, it's movement all related to hips which means, it not real space translation.......
> 
> how can I get the translation ?
> 
> After read your explain 100 times, what I need is not only the distance between body and camera, but also x and y./.............
> 
> which means, I need an x y z translation, this can not calculated from currently 3d landmarks!!!

Hello, I'm having a similar issue. When I draw the world coordinates, the body is centered in the middle, but I want it to have a movement like I move in front of the camera (x,y and z). Did you manage to find a solution?

**Comment by mbird1258** [comment]
I’ve also encountered the same problem and think I’ve found a decent solution that uses the screen coordinates to position the world coordinates in 3D space, though it either requires you to calibrate the distance to the image plane of the camera or use the calibration system I made (which I’m not sure is accurate enough for some purposes). [GitHub](https://github.com/mbird1258/3D-Pose-Camera-to-Hip-Space)
