### ISSUE TITLE
Automated video length reduction based on content

### ISSUE THREAD

**Issue by Tortoise17** [google/mediapipe#2560]
I am using autoflip on CentOS for the videos and that tool works perfect. 
I want to ask that as this is intelligent engine which detects the important content for cropping. Is it possible to reduce the video length (by fixing maximum time) based on this content.

Apparently this is question of video summarization, but the normal summarization is based on nlp approach what is spoken in the video or subtitles. I am looking for solution based on content.

If you can guide me.

**Comment by Tortoise17** [comment]
@nathanfrey-google @sgowroji Please any helping solution? that the reduction of the duration of video based on time but also content wise when there is no audio inside or audio is ignored at all.

**Comment by Tortoise17** [comment]
@sgowroji Is there any update on this request?

**Comment by Tortoise17** [comment]
@nathanfrey-google @camillol @cdibona @sgowroji Good afternoon. Is there any update on this issue?

**Comment by Tortoise17** [comment]
@sgowroji Good morning. Is there any update?

**Comment by sureshdagooglecom** [comment]
Hi @Tortoise17 .
Are you still looking for the resolution on this issue.
