### ISSUE TITLE
ios_static_framework has some problem

### ISSUE THREAD

**Issue by sek790c** [google/mediapipe#2561]
Only static framework will not be refused by App Store,I read the doc and build ios_static_framework,import it to a Xcode project which is exported from unity 3d.
When I run the target，I got many mistakes such as: 

Showing Recent Messages
Undefined symbol: _glBindAttribLocation

Undefined symbol: _glValidateProgram

Undefined symbol: _glDeleteShader

Undefined symbol: _glLinkProgram

Undefined symbol: _glCreateShader

Undefined symbol: _glShaderSource

Undefined symbol: _glDeleteSync

Undefined symbol: _glFlush

It seems opengl is not linked;
Here is Build file:
load(
    "@build_bazel_rules_apple//apple:ios.bzl",
    "ios_static_framework",
)
load(
    "//mediapipe/examples/ios:bundle_id.bzl",
    "BUNDLE_ID_PREFIX",
    "example_provisioning",
)

licenses(["notice"])

MIN_IOS_VERSION = "10.0"

alias(
    name = "handtrackinggpu",
    actual = "HandTrackingGpuApp",
)

ios_static_framework(
    name = "HandTrackingGpuApp",
    hdrs = [
        "HandTrack.h",
    ],
    families = [
        "iphone",
        "ipad",
    ],
    minimum_os_version = MIN_IOS_VERSION,
    deps = [
        ":HandTrackingGpuAppLibrary",
        "@ios_opencv//:OpencvFramework",
    ]
)

objc_library(
    name = "HandTrackingGpuAppLibrary",
    srcs = [
        "HandTrackingViewController.mm",
 	"HandTrack.mm"
    ],
    hdrs = [
        "HandTrackingViewController.h",
 	"HandTrack.h"
    ],
    copts = ["-std=c++17"],
    data = [
        "//mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu.binarypb",
        "//mediapipe/modules/hand_landmark:hand_landmark.tflite",
        "//mediapipe/modules/hand_landmark:handedness.txt",
        "//mediapipe/modules/palm_detection:palm_detection.tflite",
    ],
    deps = [
        "//mediapipe/examples/ios/common:CommonMediaPipeAppLibrary",
    ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            "//mediapipe/graphs/hand_tracking:mobile_calculators",
            "//mediapipe/framework/formats:landmark_cc_proto",
        ],
    }),
)

**Comment by sek790c** [comment]
Build file of mediapipe/examples/iOS/common
licenses(["notice"])  # Apache 2.0

objc_library(
    name = "CommonMediaPipeAppLibrary",
    srcs = [
        "CommonViewController.mm",
    ],
    hdrs = [
        "CommonViewController.h",
    ],
    sdk_frameworks = [
        "AVFoundation",
        "CoreGraphics",
        "CoreMedia",
        "UIKit",
    ],
    visibility = ["//mediapipe:__subpackages__"],
    deps = [
        "//mediapipe/objc:mediapipe_framework_ios",
        "//mediapipe/objc:mediapipe_input_sources_ios",
        "//mediapipe/objc:mediapipe_layer_renderer",
    ],
)

exports_files(["Info.plist"])

**Comment by sgowroji** [comment]
Hi @sek790c, Could you please point us the code from where you have imported and steps to reproduce the above error. Thanks!

**Comment by sek790c** [comment]
Just add opengles.framework to the project will solve the question
