### ISSUE TITLE
This error showed up in Pose Estimation, Anyone plz help

### ISSUE THREAD

**Issue by 9Guru** [google/mediapipe#2562]
Traceback (most recent call last):
  File "c:\Users\Hp\Documents\Python Projects\Hand Tracking\test.py", line 62, in <module>
    main() 
  File "c:\Users\Hp\Documents\Python Projects\Hand Tracking\test.py", line 44, in main
    detector = PoseDetector()
  File "c:\Users\Hp\Documents\Python Projects\Hand Tracking\test.py", line 17, in __init__
    self.pose = self.mpPose.Pose(self.mode, self.upBody, self.smooth, self.detectionCon, self.trackCon)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\mediapipe\python\solutions\pose.py", line 146, in __init__
    super().__init__(
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\mediapipe\python\solution_base.py", line 258, in __init__ 
    self._input_side_packets = {
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\mediapipe\python\solution_base.py", line 259, in <dictcomp>
    name: self._make_packet(self._side_input_type_info[name], data)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\mediapipe\python\solution_base.py", line 513, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
TypeError: create_bool(): incompatible function arguments. The following argument types are supported:
    1. (arg0: bool) -> mediapipe.python._framework_bindings.packet.Packet

Invoked with: 0.5
PS C:\Users\Hp\Documents\Python Projects\Hand Tracking>

**Comment by sgowroji** [comment]
Hi @9Guru, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by 9Guru** [comment]
### This is the code for the Pose Estimation module when I run this I get this error please help





```
import cv2
import mediapipe as mp
import time

class poseDetector():
    
    def __init__(self, mode=False, upBody=False, smooth=True, detectionCon=0.5, trackCon = 0.5):

        self.mode = mode
        self.upBody = upBody
        self.smooth =  #smooth
        self.detectionCon = detectionCon
        self.trackCon = trackCon


        self.mpPose = mp.solutions.pose
        self.pose = self.mpPose.Pose(self.mode, self.upBody, self.smooth, self.detectionCon, self.trackCon)
        self.mpDraw = mp.solutions.drawing_utils

    def findPose(self, img, draw = True):
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        self.results = self.pose.process(imgRGB)  
        if self.results.pose_landmarks:
            if draw:
                self.mpDraw.draw_landmarks(img, self.results.pose_landmarks, self.mpPose.POSE_CONNECTIONS)    

        return img    

    def findPostion(self, img, draw=True):
        lmList = []
        if self.results.pose_landmarks:
            for id, lm in enumerate(self.results.pose_landmarks.landmark):
                h, w, c = img.shape
                #print(id, lm)
                cx, cy = int(lm.x * w), int(lm.y * h)
                lmList.append([id, cx, cy])
                if draw:
                    cv2.circle(img, (cx, cy), 10, (255, 0, 0), cv2.FILLED)


def main():
    cap = cv2.VideoCapture(0)
    pTime = 0
    detector = poseDetector()


    while True:
        success, img = cap.read()
        img = detector.findPose(img)
        lmList = detector.findPostion(img)
        print(lmList)

        cTime = time.time()
        fps = 1 / (cTime - pTime)
        pTime = cTime

        cv2.putText(img, f'FPS: {int(fps)}',(40, 60), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 0, 255), 2)

        cv2.imshow("image", img)
        cv2.waitKey(1)


if  __name__ == "__main__":
    main()
```

**Comment by 9Guru** [comment]
> Hi @9Guru, Could you please provide the steps to reproduce the above error. Thanks!
### This is the code for the Pose Estimation module when I run this I get this error please help

```
import cv2
import mediapipe as mp
import time

class poseDetector():
    
    def __init__(self, mode=False, upBody=False, smooth=True, detectionCon=0.5, trackCon = 0.5):

        self.mode = mode
        self.upBody = upBody
        self.smooth =  #smooth
        self.detectionCon = detectionCon
        self.trackCon = trackCon


        self.mpPose = mp.solutions.pose
        self.pose = self.mpPose.Pose(self.mode, self.upBody, self.smooth, self.detectionCon, self.trackCon)
        self.mpDraw = mp.solutions.drawing_utils

    def findPose(self, img, draw = True):
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        self.results = self.pose.process(imgRGB)  
        if self.results.pose_landmarks:
            if draw:
                self.mpDraw.draw_landmarks(img, self.results.pose_landmarks, self.mpPose.POSE_CONNECTIONS)    

        return img    

    def findPostion(self, img, draw=True):
        lmList = []
        if self.results.pose_landmarks:
            for id, lm in enumerate(self.results.pose_landmarks.landmark):
                h, w, c = img.shape
                #print(id, lm)
                cx, cy = int(lm.x * w), int(lm.y * h)
                lmList.append([id, cx, cy])
                if draw:
                    cv2.circle(img, (cx, cy), 10, (255, 0, 0), cv2.FILLED)


def main():
    cap = cv2.VideoCapture(0)
    pTime = 0
    detector = poseDetector()


    while True:
        success, img = cap.read()
        img = detector.findPose(img)
        lmList = detector.findPostion(img)
        print(lmList)

        cTime = time.time()
        fps = 1 / (cTime - pTime)
        pTime = cTime

        cv2.putText(img, f'FPS: {int(fps)}',(40, 60), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 0, 255), 2)

        cv2.imshow("image", img)
        cv2.waitKey(1)


if  __name__ == "__main__":
    main()
```

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2544

**Comment by 9Guru** [comment]
I didn't get u

**Comment by sgowroji** [comment]
Hi @9Guru, Can you try this solution mentioned in this https://github.com/google/mediapipe/issues/2544#issuecomment-920225813.  #2544 has same error with same code changes.

**Comment by jigsawcoder** [comment]
Hey, 
I was not able to solve the above problem in my pose estimation project.                                                            
I am using mediapipe==0.8.9.1                                                                               

Here is the traceback:                                                                                                        
Downloading model to /media/billion/DATA/pose-detection/mp_notebooks/pose_env/lib/python3.8/site-packages/mediapipe/modules/pose_landmark/pose_landmark_lite.tflite
Traceback (most recent call last):
  File "aitproject.py", line 56, in <module>
    detector = pm.PoseDetector()
  File "/media/billion/DATA/pose-detection/mp_notebooks/ai_trainer/PoseModule.py", line 17, in __init__
    self.pose = self.mpPose.Pose(self.mode, self.upBody, self.smooth, self.detectionCon, self.trackCon)
  File "/media/billion/DATA/pose-detection/mp_notebooks/pose_env/lib/python3.8/site-packages/mediapipe/python/solutions/pose.py", line 146, in __init__
    super().__init__(
  File "/media/billion/DATA/pose-detection/mp_notebooks/pose_env/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 258, in __init__
    self._input_side_packets = {
  File "/media/billion/DATA/pose-detection/mp_notebooks/pose_env/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 259, in <dictcomp>
    name: self._make_packet(self._side_input_type_info[name], data)
  File "/media/billion/DATA/pose-detection/mp_notebooks/pose_env/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 513, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
TypeError: create_bool(): incompatible function arguments. The following argument types are supported:
    1. (arg0: bool) -> mediapipe.python._framework_bindings.packet.Packet

Invoked with: 0.5

I also checked the smooth is boolean, which you mentioned to check in #2544 

Is there something I am missing??
Please Help!!!
Thanks in advance

**Comment by Kanika637** [comment]
Hey, @jigsawcoder  I am getting the same errors, were you able to solve this one?

**Comment by Ashutosh-4485** [comment]
I had the same error and able to solve it

**This was the previous code :**

  def __init__(self, mode=False, upBody=False, smooth=True,
                 detectionCon=0.5, trackCon=0.5):
 
        self.mode = mode
        self.upBody = upBody
        self.smooth = smooth
        self.detectionCon = detectionCon
        self.trackCon = trackCon
 
        self.mpDraw = mp.solutions.drawing_utils
        self.mpPose = mp.solutions.pose
        self.pose = self.mpPose.Pose(self.mode, self.upBody, self.smooth,
                                     self.detectionCon, self.trackCon)

**and I changed it to this:**


    def __init__(self, mode=False, upBody=False, smooth=True,
                 detectionCon=0.5, trackCon=0.5):


        self.mode = mode
        self.upBody = upBody
        self.smooth = smooth
        self.detectionCon = detectionCon
        self.trackCon = trackCon

        self.mpDraw = mp.solutions.drawing_utils
        self.mpPose = mp.solutions.pose

        **self.pose = self.mpPose.Pose(self.mode
                                     , min_detection_confidence=0.5
                                     , min_tracking_confidence=0.5
                                     )**

For further info visit
[https://stackoverflow.com/questions/69103694/typeerror-create-bool-incompatible-function-arguments/74190299](url)

**Comment by Maheshkumar0018** [comment]
> Hey, @jigsawcoder I am getting the same errors, were you able to solve this one?
import cv2
import mediapipe as mp
import time

class poseDetector:
    def __init__(self, mode=False, modelC=1, upBody=False, smooth=True,
                 detectionCon=0.5, trackCon=0.5):
        self.mode = mode
        self.upBody = upBody
        self.modelC =modelC
        self.smooth = smooth
        self.detectionCon = detectionCon
        self.trackCon = trackCon
        self.mpPose = mp.solutions.pose
        self.pose = self.mpPose.Pose(self.mode, self.modelC, self.upBody, self.smooth,
                                     self.detectionCon,self.trackCon)
        self.mpDraw = mp.solutions.drawing_utils

    def findPose(self, frame, draw=True):
        rgb = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
        result = self.pose.process(rgb)
        if result.pose_landmarks:
            if draw:
                self.mpDraw.draw_landmarks(frame,result.pose_landmarks,self.mpPose.POSE_CONNECTIONS)
        return frame
        #for id, lm in enumerate(result.pose_landmarks.landmark):
        #    h, w, c = frame.shape
        #    cx, cy = int(lm.x*w), int(lm.y*h)
            #print(cx, cy)
        #    cv2.circle(frame,(cx,cy),10,(255,0,0),cv2.FILLED)

   


def main():
    cap = cv2.VideoCapture('./PoseEstimation/videos/production_id_4841985 (2160p).mp4')

    window_width = 960
    window_height = 540
    cv2.namedWindow('Frame', cv2.WINDOW_NORMAL)
    cv2.resizeWindow('Frame', window_width, window_height)

    detector = poseDetector()

    pTime = 0
    while(cap.isOpened()):
        _, frame = cap.read()
        frame = detector.findPose(frame)
        cTime = time.time()
        fps = 1/(cTime-pTime)
        pTime = cTime
        cv2.putText(frame,str(int(fps)),(70,80),cv2.FONT_HERSHEY_PLAIN,
                    7,(255,0,255),5)
        cv2.imshow('Frame',frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

if __name__ == '__main__':
    main()
this will work
