### ISSUE TITLE
Can we run on tpuv3 on Google colab ?

### ISSUE THREAD

**Issue by 1kaiser** [google/mediapipe#2564]

**Comment by sgowroji** [comment]
Hi @1kaiser, Could you please elaborate how above query related to mediapipe ?. You can [refer this](https://stackoverflow.com/questions/64735682/use-tpu-v3-in-google-colab-pro)  for above query from other platforms.

**Comment by 1kaiser** [comment]
can we run https://github.com/huggingface/accelerate with mediapipe on google colab version with tpu enabled

**Comment by sgowroji** [comment]
Hi @1kaiser, We have not tested  it.  But you can try sharing your observations, if there are any errors. Thanks!
