### ISSUE TITLE
Are the holistic z values dependable?

### ISSUE THREAD

**Issue by sn1c3** [google/mediapipe#2568]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution: Ubuntu18.04
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.7
- Solution (e.g. FaceMesh, Pose, Holistic): Holistic 
- Programming Language and version ( e.g. C++, Python, Java): Python

## URL(s) with the issue:
https://google.github.io/mediapipe/solutions/holistic
https://google.github.io/mediapipe/solutions/pose.html

## Description of issue (what needs changing):
The documentation for holistic says, in contrast to pose, that the z values "Should be discarded as currently the model is not fully trained to predict depth". Is this still an actual thing or is this information outdated? 

## If holistic is not usable due to z values:
How to use the hands and pose model on a single image stream? 

EDIT: 
### Use Case
For a project I need a more accurate 3d presentation of my pose. Also, I want to control some features with my hand.

**Comment by sgowroji** [comment]
Hi @sn1c3, 
1. Documentation is upto date. Could you please add your use case w.r.t to it.
2. You can use this [code](https://google.github.io/mediapipe/solutions/pose.html#python-solution-api). to run python pose solution on static images for pose and [hands](https://google.github.io/mediapipe/solutions/hands.html#python-solution-api).

**Comment by sn1c3** [comment]
Hi @sgowroji,

thank you for the fast answer.

Sorry, I wasn't very accurate on my question. I need to use pose and hand model on a video stream, is this still possible?

**Comment by sn1c3** [comment]
okay, the solution was relatively simple. Just add this on the beginning:

```
...
with mp_pose.Pose(
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5) as pose:

    with mp_hands.Hands(
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5) as hands:
 
        while cap.isOpened():
                 ...
```

**Comment by ykk648** [comment]
@sn1c3  So the holistic z values is not dependable, isn't it?
