### ISSUE TITLE
Basel5/Jetson arm

### ISSUE THREAD

**Issue by AndreV84** [google/mediapipe#2571]
How to address ios bazel errors/ android ndk errors on arm jetson with basel Release 5.0.0-pre.20210913.1 (2021-09-17) ?
```
ERROR: Traceback (most recent call last):
	File "/home/nvidia/.cache/bazel/_bazel_nvidia/ff4425722229fc486cc849b5677abe3f/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 529, column 58, in <toplevel>
		ios_application = rule_factory.create_apple_bundling_rule(
	File "/home/nvidia/.cache/bazel/_bazel_nvidia/ff4425722229fc486cc849b5677abe3f/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 950, column 55, in _create_apple_bundling_rule
		rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
	File "/home/nvidia/.cache/bazel/_bazel_nvidia/ff4425722229fc486cc849b5677abe3f/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 228, column 21, in _common_binary_linking_attrs
		apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: error loading package 'mediapipe/gpu': at /home/nvidia/.cache/bazel/_bazel_nvidia/ff4425722229fc486cc849b5677abe3f/external/build_bazel_rules_apple/apple/ios.bzl:37:5: initialization of module 'apple/internal/ios_rules.bzl' failed

**Comment by sgowroji** [comment]
Hi @AndreV84, Could you please provide the steps to reproduce the above errors. Thanks!

**Comment by AndreV84** [comment]
@sgowroji 
Could you share steps how not to run into these issues, please?
I just tried hello world/ hand example build with bazel of the latest version

**Comment by AndreV84** [comment]
steps to reproduce
install on jetson/ or desktop
Release 5.0.0-pre.20210913.1 (2021-09-17)
then try to build the hello world or hand tracking examples

**Comment by AndreV84** [comment]
@sgowroji it is not the platform specific issue, in my opinion
it is bazel version specific version issue, as it seems to me
unless the mediapipe scripts after detecting arm platform decided that it is ios or android platform automatically
you should be able to run into the same issue on x86_64 if you try

**Comment by AndreV84** [comment]
Could you explain why at all it starts to load android/ ios packages for bazel?

**Comment by AndreV84** [comment]
is there an easy way to disable the ios/ android dependencies while building desktop example?

**Comment by AndreV84** [comment]
probably it is an issue with mediapipe workspaces file

**Comment by AndreV84** [comment]
Even after fowngrading the basel 
I can occur the issue for that I should possibly create a new issue?
```
FO: From Compiling mediapipe/calculators/tensor/inference_calculator_gl.cc:
In file included from external/opencl_headers/CL/cl.h:32:0,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:42,
                 from ./mediapipe/util/tflite/tflite_gpu_runner.h:25,
                 from mediapipe/calculators/tensor/inference_calculator_gl.cc:28:
external/opencl_headers/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
ERROR: /home/nvidia/mediapipe/mediapipe/calculators/tensor/BUILD:657:11: Compiling mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc: In member function 'virtual absl::lts_2020_09_23::StatusOr<mediapipe::Tensor> mediapipe::{anonymous}::OpenCvProcessor::Convert(const mediapipe::Image&, const mediapipe::RotatedRect&, const mediapipe::Size&, float, float)':
mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc:106:12: error: could not convert 'tensor' from 'mediapipe::Tensor' to 'absl::lts_2020_09_23::StatusOr<mediapipe::Tensor>'
     return tensor;
            ^~~~~~
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 227.963s, Critical Path: 202.95s
INFO: 972 processes: 128 internal, 844 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by AndreV84** [comment]
@sgowroji

**Comment by sgowroji** [comment]
Hi @AndreV84, Thank you for your patience. I have added @hadon and @mcclanahoochie, who can guide you on the above queries.

**Comment by AndreV84** [comment]
trying to disable opencv2 support in opencv build to try again

**Comment by AndreV84** [comment]
seems either gcc needs to be updated or mediapipe needs to be downgraded? no compatibility with gcc7 with the latest mediapipe release?
https://github.com/google/mediapipe/issues/1733
https://github.com/google/mediapipe/issues/1673

**Comment by mcclanahoochie** [comment]
Yes please try using gcc8, as suggested in https://github.com/google/mediapipe/issues/1733#issuecomment-828661652 to fix the 'Tensor' compile error. gcc8 appears to be required by the absl library.

Also, in general, MediaPipe doesn't guarantee support for the latest Bazel version (especially a pre-release). Support for the newer Bazel versions usually lags a bit (because newer Bazel versions tend to break things, and those need to be addressed, such as it appears here).

**Comment by AndreV84** [comment]
so which basel to use?

**Comment by mcclanahoochie** [comment]
the bazel used in https://github.com/google/mediapipe/issues/2571#issuecomment-926519110 looks like it works, probably just needs gcc8+ at that point

**Comment by CoderJackLiu** [comment]
> 
so ,have u  disable the android and ios plateform?

**Comment by CoderJackLiu** [comment]
the same issuss  .

**Comment by lemio** [comment]
Still bumping into this issue after having solved this issue https://github.com/google/mediapipe/issues/1972

Steps to reproduce:


https://developers.google.com/mediapipe/framework/getting_started/install

git clone --depth 1 https://github.com/google/mediapipe.git
cd mediapipe
docker build --tag=mediapipe .


docker run -it --name mediapipe mediapipe:latest

https://github.com/google/mediapipe/issues/1972#issuecomment-1072994746

apt install nodejs npm
npm install -g @bazel/bazelisk --force

GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world

https://github.com/google/mediapipe/issues/2571

`GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world
ERROR: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/build_bazel_rules_apple/apple/internal/rule_support.bzl", line 217, column 36, in <toplevel>
		deps_cfg = apple_common.multi_arch_split,
Error: 'apple_common' value has no field or method 'multi_arch_split'
ERROR: error loading package 'mediapipe/gpu': at /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/build_bazel_rules_apple/apple/ios.bzl:33:5: at /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl:75:5: initialization of module 'apple/internal/rule_support.bzl' failed
ERROR: /mediapipe/mediapipe/framework/BUILD:1014:11: errors encountered resolving select() keys for //mediapipe/framework:port
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.481s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
`
