### ISSUE TITLE
Typo in the code example

### ISSUE THREAD

**Issue by Max-Korsakov** [google/mediapipe#2573]
Thank you for submitting a MediaPipe documentation issue.
The MediaPipe docs are open source! To get involved, read the documentation Contributor Guide
## URL(s) with the issue:

https://google.github.io/mediapipe/solutions/face_detection#javascript-solution-api

## Description of issue (what needs changing):
Typo in the JS code example. Put a comma between object's properties in the faceDetection.setOptions

Kinds of documentation problems:
![image](https://user-images.githubusercontent.com/48759392/134230032-595b8c0e-6a58-4ca3-afec-6d634992f427.png)

**Comment by sgowroji** [comment]
Thank you for sharing the issue with complete details. We have fixed this and it will be available in the next release.
