### ISSUE TITLE
Convert to Openpose joints format?

### ISSUE THREAD

**Issue by Frank-Dz** [google/mediapipe#2575]
Is there a way to convert the full-body output of mediapipe into the Openpose format?

Thanks!

**Comment by sgowroji** [comment]
Hi @Frank-Dz, Could you please elaborate your use case on the above query. Thanks!

**Comment by Frank-Dz** [comment]
> Hi @Frank-Dz, Could you please elaborate your use case on the above query. Thanks!

I am doing research on full-body HPE and want to convert the result in the same format for campairson.

**Comment by sparshgarg23** [comment]
Hi,even I am looking for a way to convert the results of mediapipe into open pose.The reason being that I am looking to use the results of mediapipe to fit 3d models using SMPL(but they rely on usage of openpose,which outputs only 25 landmarks ) as compared to the output of mediapipe which includes 33 landmarks

**Comment by GuangtaoLyu** [comment]
> 嗨，甚至我正在寻找一种方法将 mediapipe 的结果转换为开放姿势。原因是我希望使用 mediapipe 的结果来拟合使用 SMPL 的 3d 模型（但他们依赖于使用 openpose，它只输出 25 个地标），而 mediapipe 的输出包括 33 个地标

have you solved it?
