### ISSUE TITLE
Not able to use LandmarkGrid from '@mediapipe/control_utils_3d'. TypeError: Cannot read properties of undefined (reading 'Vector3')

### ISSUE THREAD

**Issue by GiselaMD** [google/mediapipe#2578]
Getting error when importing LandmarkGrid from '@mediapipe/control_utils_3d'

TypeError: Cannot read properties of undefined (reading 'Vector3')

dependencies:
    "@mediapipe/camera_utils": "^0.3.1632336052",
    "@mediapipe/control_utils": "^0.6.1629159505",
    "@mediapipe/control_utils_3d": "^0.2.1625245254",
    "@mediapipe/drawing_utils": "^0.3.1620248257",
    "@mediapipe/pose": "^0.4.1630009814",

Reproducible code: https://codesandbox.io/s/icy-brook-5pqne?file=/src/index.js

**Comment by AHRealift** [comment]
+1, status?

**Comment by mhays-google** [comment]
Solution: Import `control_utils_3d` before `control_utils`.

```
import LandmarkGrid from "@mediapipe/control_utils_3d";
import controls from "@mediapipe/control_utils";
import drawingUtils from "@mediapipe/drawing_utils";
import mpPose from "@mediapipe/pose";
```

**Comment by mcwachanga** [comment]
@sgowroji  I have imported `controls_utils_3d ` before `controls_utils` and the error still persists. here are my versions:

```
"@mediapipe/camera_utils": "^0.3.1640029074",
"@mediapipe/control_utils": "^0.6.1629159505",
"@mediapipe/control_utils_3d": "^0.3.1635987963",
"@mediapipe/drawing_utils": "^0.3.1620248257",
"@mediapipe/pose": "^0.5.1635988162"
```

**Comment by sgowroji** [comment]
Hi @mcwachanga, Could you please confirm whether the above files were downloaded in the network tab.

**Comment by mcwachanga** [comment]
@sgowroji I appreciate the timely response. I'm using angular and I think the util is included by webpack after importing it like so:
`import * as Controls3D from "@mediapipe/control_utils_3d"; `

This is the console error.
![controls bug](https://user-images.githubusercontent.com/9365510/151385135-31477e38-d70e-46e8-83de-64c219b0e6d6.PNG)

Seems like the util is downloading ThreeJS library (which already exists in my project) but it's not showing up in the network?
![controls network](https://user-images.githubusercontent.com/9365510/151387859-4222a69b-0857-44b7-a567-9a473591de96.PNG)

**Comment by daniele-gusmini** [comment]
I have the same problem, is there a solution?

**Comment by AgentCosmic** [comment]
Load it from CDN instead of using from npm.
