### ISSUE TITLE
using tracking detect multi-hands problem

### ISSUE THREAD

**Issue by jerryli1119** [google/mediapipe#2579]
Hello,
I use the python3.6.9 and pip install mediapipe. mediapipe version is 0.8.3.
In this version I encountered the same problem. https://github.com/google/mediapipe/issues/628

In 0.8.3ver, two results on the same hand.
![0_8_3](https://user-images.githubusercontent.com/34928698/134465086-37f67324-f0d5-49b6-a888-d878397f5757.jpg)

but i downgrade the version (0.8.0)
![0_8_0](https://user-images.githubusercontent.com/34928698/134465159-c96c9800-fab9-4bb4-b82d-9f9a865e130c.jpg)

So your suggestion me that I continue to use the 0.8.0 version?

**Comment by sgowroji** [comment]
Hi @jerryli1119, Could you please try with the latest release [0.8.7.1 ](https://github.com/google/mediapipe/releases#:~:text=Latest%20release-,v0.8.7.1,-6abec12). Thanks!

**Comment by jerryli1119** [comment]
Hi @sgowroji, i tried to use the latest version. The problem has been solved. Thank you.
So is it not recommended to use the previous old version?

**Comment by sgowroji** [comment]
Yes We are continuously updating and improving our repo and solutions. Glad to know you resolved, We are closing this issue now.
