### ISSUE TITLE
I want to introduce Holistic into the project in the same way as Solution Hand. But an error is reported after startup

### ISSUE THREAD

**Issue by tianhonglilei** [google/mediapipe#2580]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution :Android 11
- Compiler version :
- Programming Language and version:Java
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.7
- Bazel version:4.1
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):sdk-29 / ndk-21
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): build solution aar
- OpenCV version (if running on desktop):

**Describe the problem**:
I want to introduce Holistic into the project in the same way as Solution Hand. I tried to add code to the BUILD file of solutioncore, and the build succeeded. But an error was reported after the project was introduced. I tried to add and set the attribute setUpperBodyOnly, but it didn't work. I hope you can help me look at this problem in your busy schedule. Thank you.

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

solutioncore BUILD [https://github.com/google/mediapipe/blob/v0.8.7/mediapipe/java/com/google/mediapipe/solutioncore/BUILD](url)
I modified it here below：
```
              # Native dependencies of all MediaPipe solutions.
              cc_binary(
                  name = "libmediapipe_jni.so",
                  linkshared = 1,
                  linkstatic = 1,
                  # TODO: Add more calculators to support other top-level solutions.
                  deps = [
                      "//mediapipe/java/com/google/mediapipe/framework/jni:mediapipe_framework_jni",
                      "//mediapipe/modules/face_landmark:face_landmark_front_cpu_image",
                      "//mediapipe/modules/face_landmark:face_landmark_front_gpu_image",
                      "//mediapipe/modules/hand_landmark:hand_landmark_tracking_cpu_image",
                      "//mediapipe/modules/hand_landmark:hand_landmark_tracking_gpu_image",
                      "//mediapipe/modules/holistic_landmark:holistic_landmark_cpu",
                      "//mediapipe/modules/holistic_landmark:holistic_landmark_gpu",
                  ],
              )
```

I created a class Holistic similar to solution Hand in the project and introduced it to the project, and an error was reported after startup.

Error log :
```
          E/libEGL: validate_display:91 error 3008 (EGL_BAD_DISPLAY)
          E/native: E20210923 14:36:51.577350  3571 graph.cc:470] while processing the input side packets of subgraph node HolisticLandmarkGpu: ; Tag "UPPER_BODY_ONLY" does not exist in the subgraph config.
          E/SolutionBase: Error occurs when starting the MediaPipe solution graph.
          com.google.mediapipe.framework.MediaPipeException: invalid argument: while processing the input side packets of subgraph node HolisticLandmarkGpu: ; Tag "UPPER_BODY_ONLY" does not exist in the subgraph config.
                  at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
                  at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:324)
                  at com.google.mediapipe.solutioncore.SolutionBase.start(SolutionBase.java:113)
                  at com.google.mediapipe.examples.holitic.Holitic.<init>(Holitic.java:87)
                  at com.google.mediapipe.examples.hands.MainActivity.setupStreamingModePipeline(MainActivity.java:251)
                  at com.google.mediapipe.examples.hands.MainActivity.lambda$setupLiveDemoUiComponents$9$MainActivity(MainActivity.java:226)
                  at com.google.mediapipe.examples.hands.-$$Lambda$MainActivity$HYbQOkTPFFzdblZcYyg4yx-MNp0.onClick(Unknown Source:2)
                  at android.view.View.performClick(View.java:7191)
                  at android.view.View.performClickInternal(View.java:7164)
                  at android.view.View.access$3500(View.java:821)
                  at android.view.View$PerformClick.run(View.java:27862)
                  at android.os.Handler.handleCallback(Handler.java:914)
                  at android.os.Handler.dispatchMessage(Handler.java:100)
                  at android.os.Looper.loop(Looper.java:224)
                  at android.app.ActivityThread.main(ActivityThread.java:7551)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```

**Comment by sgowroji** [comment]
Hi @tianhonglilei, Are you trying to build a holistic solution with gradle API as we did for [Face Mesh](https://github.com/google/mediapipe/tree/710fb3de58dc10b7bc75f9cb758300c9016a5e4f/mediapipe/examples/android/solutions#:~:text=.%E2%80%8A.-,facemesh,-Project%20import%20generated) and [Hands](https://github.com/google/mediapipe/tree/710fb3de58dc10b7bc75f9cb758300c9016a5e4f/mediapipe/examples/android/solutions/hands)?

**Comment by tianhonglilei** [comment]
Hi @sgowroji, Yes, I want to use Holistic and Iris in the project, It would be even better if the new version can provide gradle api like Face Mesh and Hand.

**Comment by tianhonglilei** [comment]
Hi @sgowroji, Please take a look at the log I submitted, how should the problem of this attribute UPPER_BODY_ONLY be solved? thanks

**Comment by sgowroji** [comment]
Hi @tianhonglilei, Could you please share your graph or code changes to investigate further. Thanks!

**Comment by tianhonglilei** [comment]
Hi @sgowroji , I imitated the modification of Solution Hand [https://github.com/google/mediapipe/tree/v0.8.7/mediapipe/java/com/google/mediapipe/solutions/hands](url) and created these classes.
<img width="400" alt="WX20210924-180932@2x" src="https://user-images.githubusercontent.com/18715516/134658064-ebede343-a1cf-4ff8-8d63-477c3f3307b7.png">

```
@AutoValue
public abstract class HolisticOptions {
    public static final int STREAMING_MODE = 1;
    public static final int STATIC_IMAGE_MODE = 2;

    public HolisticOptions() {
    }

    @HolisticOptions.Mode
    public abstract int mode();

    //UPPERBODYONLY
    public abstract boolean upperBodyOnly();

    public abstract float minDetectionConfidence();

    public abstract float minTrackingConfidence();

    public abstract boolean runOnGpu();

    public static HolisticOptions.Builder builder() {
        return (new AutoValue_HoliticOptions.Builder()).withDefaultValues();
    }

    @com.google.auto.value.AutoValue.Builder
    public abstract static class Builder {
        public Builder() {
        }

        public HolisticOptions.Builder withDefaultValues() {
            return this.setMinDetectionConfidence(0.7F).setMinTrackingConfidence(0.7F).setUpperBodyOnly(false).setRunOnGpu(true);
        }

        public abstract HolisticOptions.Builder setMode(int value);

        public abstract HolisticOptions.Builder setMinDetectionConfidence(float value);

        public abstract HolisticOptions.Builder setMinTrackingConfidence(float value);

        public abstract HolisticOptions.Builder setUpperBodyOnly(boolean value);

        public abstract HolisticOptions.Builder setRunOnGpu(boolean value);

        public abstract HolisticOptions build();
    }

    public @interface Mode {
    }
}
```

Holistic code:
```
         SolutionInfo solutionInfo = SolutionInfo.builder()
                .setBinaryGraphPath(options.runOnGpu() ? "holistic_tracking_gpu.binarypb" : "holistic_tracking_cpu.binarypb")
                .setImageInputStreamName("image")
                .setOutputStreamNames(OUTPUT_STREAMS)
                .setStaticImageMode(options.mode() == 1)
                .build();
        this.initialize(context, solutionInfo, this.graphOutputHandler);
        Map<String, Packet> inputSidePackets = new HashMap();
        this.start(inputSidePackets);
```

**Comment by sgowroji** [comment]
Hi @tianhonglilei, Present the team does not have any plans to release the Holistic Gradle API. On this thread am adding @camillol and @jiuqiant to have a look at your error.

**Comment by jiuqiant** [comment]
Neither https://github.com/google/mediapipe/blob/master/mediapipe/modules/holistic_landmark/holistic_landmark_gpu.pbtxt nor https://github.com/google/mediapipe/blob/master/mediapipe/graphs/holistic_tracking/holistic_tracking_gpu.pbtxt has an input side packet to set if the model detects "upperBodyOnly". Maybe you can remove "upperBodyOnly" from the code.

**Comment by tianhonglilei** [comment]
Hi @jiuqiant ,Thanks,I only added this attribute “upperBodyOnly” because I saw the error log above.

**Comment by lhalcyon** [comment]
> Hi @sgowroji , I imitated the modification of Solution Hand [https://github.com/google/mediapipe/tree/v0.8.7/mediapipe/java/com/google/mediapipe/solutions/hands](url) and created these classes. <img alt="WX20210924-180932@2x" width="400" src="https://user-images.githubusercontent.com/18715516/134658064-ebede343-a1cf-4ff8-8d63-477c3f3307b7.png">
> 
> ```
> @AutoValue
> public abstract class HolisticOptions {
>     public static final int STREAMING_MODE = 1;
>     public static final int STATIC_IMAGE_MODE = 2;
> 
>     public HolisticOptions() {
>     }
> 
>     @HolisticOptions.Mode
>     public abstract int mode();
> 
>     //UPPERBODYONLY
>     public abstract boolean upperBodyOnly();
> 
>     public abstract float minDetectionConfidence();
> 
>     public abstract float minTrackingConfidence();
> 
>     public abstract boolean runOnGpu();
> 
>     public static HolisticOptions.Builder builder() {
>         return (new AutoValue_HoliticOptions.Builder()).withDefaultValues();
>     }
> 
>     @com.google.auto.value.AutoValue.Builder
>     public abstract static class Builder {
>         public Builder() {
>         }
> 
>         public HolisticOptions.Builder withDefaultValues() {
>             return this.setMinDetectionConfidence(0.7F).setMinTrackingConfidence(0.7F).setUpperBodyOnly(false).setRunOnGpu(true);
>         }
> 
>         public abstract HolisticOptions.Builder setMode(int value);
> 
>         public abstract HolisticOptions.Builder setMinDetectionConfidence(float value);
> 
>         public abstract HolisticOptions.Builder setMinTrackingConfidence(float value);
> 
>         public abstract HolisticOptions.Builder setUpperBodyOnly(boolean value);
> 
>         public abstract HolisticOptions.Builder setRunOnGpu(boolean value);
> 
>         public abstract HolisticOptions build();
>     }
> 
>     public @interface Mode {
>     }
> }
> ```
> 
> Holistic code:
> 
> ```
>          SolutionInfo solutionInfo = SolutionInfo.builder()
>                 .setBinaryGraphPath(options.runOnGpu() ? "holistic_tracking_gpu.binarypb" : "holistic_tracking_cpu.binarypb")
>                 .setImageInputStreamName("image")
>                 .setOutputStreamNames(OUTPUT_STREAMS)
>                 .setStaticImageMode(options.mode() == 1)
>                 .build();
>         this.initialize(context, solutionInfo, this.graphOutputHandler);
>         Map<String, Packet> inputSidePackets = new HashMap();
>         this.start(inputSidePackets);
> ```

Hi , LiLei . I am doing the same stuff , trying to work out a holistic solution . Have u succeed in this work, would u share me with ur java code

**Comment by MelisaSosa** [comment]
hello @tianhonglilei , I'm also trying to implement holistic on Android and I wanted to know if you succeeded and, if you don't mind, I'd like to ask you some questions 🙏 thank you a lot
