### ISSUE TITLE
Objectron-JS:how to get "rotation"/“translation”/“scale”

### ISSUE THREAD

**Issue by DLGL99GL** [google/mediapipe#2581]
![image](https://user-images.githubusercontent.com/69023459/134473460-c3e70d01-1e70-4d3a-8264-b1cf0b54d37a.png)
![image](https://user-images.githubusercontent.com/69023459/134475073-4d65877a-f6d6-4b68-86ab-8d39d50b8d90.png)

Objectron（3D Object Detection） Output:
landmarks_2d    
landmarks_3d 
rotation
translation 
scale

i can find it in Python Solution API, but  didn't find all in JavaScript Solution API when I used  console.log(detectedObject);there isn't  "rotation"/“translation”/“scale”;
Could you help me?thanks

**Comment by HarryXD2018** [comment]
Hi, @DLGL99GL,
> i can find it in Python Solution API, but didn't find all in JavaScript Solution API when I used console.log(detectedObject);there isn't "rotation"/“translation”/“scale”;

I am interested in the Python API you mentioned, would you please tell me what the API looks like? Thanks!

**Comment by DLGL99GL** [comment]
> Hi, @DLGL99GL,
> 
> > i can find it in Python Solution API, but didn't find all in JavaScript Solution API when I used console.log(detectedObject);there isn't "rotation"/“translation”/“scale”;
> 
> I am interested in the Python API you mentioned, would you please tell me what the API looks like? Thanks!

![image](https://user-images.githubusercontent.com/69023459/140596906-3662febc-6875-428f-bbf9-f60611f3d9a6.png)

detected_object.rotation detected_object.translation  can find in Python Solution API of [https://google.github.io/mediapipe/solutions/objectron#javascript-solution-api](mediapipe objectron)

**Comment by DLGL99GL** [comment]
> Hi, @DLGL99GL,
> 
> > i can find it in Python Solution API, but didn't find all in JavaScript Solution API when I used console.log(detectedObject);there isn't "rotation"/“translation”/“scale”;
> 
> I am interested in the Python API you mentioned, would you please tell me what the API looks like? Thanks!
![image](https://user-images.githubusercontent.com/69023459/140597069-9558d8c1-ce27-49cf-b181-92bff700e8d6.png)

detected_object.rotation detected_object.translation can find in Python Solution API of [https://google.github.io/mediapipe/solutions/objectron#javascript-solution-api](url)

**Comment by HarryXD2018** [comment]
Hi, thanks for replying. Actually, I am looking for the same question on Face Mesh. I didn't see you were discussing objection. Thanks anyway. :)

**Comment by mhays-google** [comment]
Sure enough!  Python and JavaScript operate off of the same internal data.  I'll raise this issue and we'll get rotation/translation/scale into the javascript API.

**Comment by mhays-google** [comment]
> Hi, thanks for replying. Actually, I am looking for the same question on Face Mesh. I didn't see you were discussing objection. Thanks anyway. :)

Hey there.  Face_mesh does emit a matrix transform for the face.  A little different than scale/transform/rotation, but a lot easier when dealing with packages like threejs where you might be sticking something onto the face.

**Comment by mhays-google** [comment]
I have released a new version of Objectron (0.4) that surfaces scale/rotation/translation on the results object, just as you would expect.  I'll update the live demo to point to this version soon.  Tell me if you have any issues, but I'll close this for now.

**Comment by HarryXD2018** [comment]
> > Hi, thanks for replying. Actually, I am looking for the same question on Face Mesh. I didn't see you were discussing objection. Thanks anyway. :)
> 
> Face_mesh does emit a matrix transform for the face. A little different than scale/transform/rotation, but a lot easier when dealing with packages like threejs where you might be sticking something onto the face.

Thanks for replying. Honestly, I have been finding the matrix transform (Python face mesh solution) for days. Would you please show me how to get it? That would help me a lot.

**Comment by mhays-google** [comment]
> Thanks for replying. Honestly, I have been finding the matrix transform (Python face mesh solution) for days. Would you please show me how to get it? That would help me a lot.

We haven't normalized the representation across all of our languages.  So in this instance, the JavaScript folks are getting something ahead of time.  This is the reason there is no demo calling attention to it in the JavaScript library -- I jumped the gun a bit.  But I'll talk with the team.  I'd love to see what people do with this.

**Comment by DLGL99GL** [comment]
> I have released a new version of Objectron (0.4) that surfaces scale/rotation/translation on the results object, just as you would expect. I'll update the live demo to point to this version soon. Tell me if you have any issues, but I'll close this for now.
@mhays-google  hello，i tested the example of [objectron](https://codepen.io/mediapipe/full/BaWvzdY),But it hasn't been updated yet；may i ask when you plan to update it?

**Comment by DLGL99GL** [comment]
> I have released a new version of Objectron (0.4) that surfaces scale/rotation/translation on the results object, just as you would expect. I'll update the live demo to point to this version soon. Tell me if you have any issues, but I'll close this for now.

hello，i test the example of [Objectron](https://codepen.io/mediapipe/full/BaWvzdY)，butI found it hasn't been updated yet；May I ask when you plan to update?  @mhays-google

**Comment by shivammaindola** [comment]
@sgowroji @mhays-google Objectron is still not updated. Can you please update it so that we can access the rotation values?

**Comment by mhays-google** [comment]
I'm looking at the version served from jsdelivr.  Check that you are actually downloading the latest:

https://cdn.jsdelivr.net/npm/@mediapipe/objectron@0.4.1636596145/index.d.ts

```
/**
 * The relevant information about a particular object detection.
 */
export declare interface ObjectDetection {
 ...<SNIP>...
  /**
   * 3x3 row-major rotation matrix describing the orientation of the rigid
   * object's frame of reference in the camera-coordinate system.
   */
  rotation: number[];
  /**
   * 3x1 vector describing the scale of the rigid object's frame of reference in
   * the camera-coordinate system.
   */
  scale: number[];
  /**
   * 3x1 vector describing the translation of the rigid object's frame of
   * reference in the camera-coordinate system in meters.
   */
  translation: number[];
}
```
