### ISSUE TITLE
Pose landmark confidence not available

### ISSUE THREAD

**Issue by petoknm** [google/mediapipe#2582]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Linux Manjaro
- MediaPipe version: 0.8.7
- Solution: Pose
- Programming Language and version: Python 3.9.7

**Describe the expected behavior:**
I want to get pose landmark confidence per frame, not just set a `min_detection_confidence`, so I can perform my own offline filtering.

Is there a way to get this information?

**Comment by sgowroji** [comment]
Hi @petoknm, Could you please elaborate your use case with more details. Thanks!

**Comment by petoknm** [comment]
I am dealing with some movement that gets obstructed and it would be nice to filter spurious detections out, for this I need to be able to tell apart which detections are strong (high confidence) and which ones are weak (low confidence).

I want to perform offline filtering (filtering after detecting pose on an entire video) as opposed to the built-in online filtering ("smoothing") because of certain advantages that can bring (like interpolation, convolution filters, etc.). And this would benefit from having confidence on the individual landmarks for weighted filters that could then use this to differentiate between strong and weak detections and affect the output more or less based on that.

**Comment by jiuqiant** [comment]
You can modify pose.py to add ["pose_detection"](https://github.com/google/mediapipe/blob/710fb3de58dc10b7bc75f9cb758300c9016a5e4f/mediapipe/modules/pose_landmark/pose_landmark_cpu.pbtxt#L107) as an output.

Go to site-packages/mediapipe/python/solutions/pose.py and modify line 166 to be

```
outputs=['pose_landmarks', 'pose_world_landmarks', 'segmentation_mask', 'pose_detection'])
```

"results.pose_detection" will give you the score: https://github.com/google/mediapipe/blob/master/mediapipe/framework/formats/detection.proto#L34. Here is an example if you do `print(results.pose_detection)`:

```
label_id: 0
score: 0.88259405
location_data {
  format: RELATIVE_BOUNDING_BOX
  relative_bounding_box {
    xmin: 0.43128788
    ymin: 0.42205355
    width: 0.20010132
    height: 0.35578358
  }
  relative_keypoints {
    x: 0.60679907
    y: 1.4073309
  }
  relative_keypoints {
    x: 0.4823539
    y: 0.26469108
  }
  relative_keypoints {
    x: 0.52839404
    y: 0.7340994
  }
  relative_keypoints {
    x: 0.43620652
    y: -0.10337046
  }
}
```

As a reference, here is how we get "plam detection" from the hands solution: https://github.com/google/mediapipe/issues/1390#issuecomment-745615822.

**Comment by petoknm** [comment]
I was looking for per-landmark score (score for LEFT_EAR, RIGHT_ANKLE, RIGHT HIP, etc.) but I assume the underlying model does not have such an output.

**Comment by jiuqiant** [comment]
Unfortunately, the output landmark protobuf message doesn't have a confidence score field.
