### ISSUE TITLE
How add filter in facemeshResult solution

### ISSUE THREAD

**Issue by zhoujingheng** [google/mediapipe#2583]
i want to add beautify filter in camera，how can i add filter in facemeshResult solution callback renderResult()

**Comment by zhoujingheng** [comment]
can you give me a sample about this

**Comment by kostyaby** [comment]
Hey @zhoujingheng,

Please see https://github.com/google/mediapipe/issues/1498#issuecomment-774886460 for additional guidance. Unfortunately, I don't have any additional code samples to share

**Comment by zhoujingheng** [comment]
Hey@kostyaby，i use android，because facemesh has opengl and camera, so i can not only use the point，and do not add beautify filter,do you have suggest about this?
