### ISSUE TITLE
Mediapipe AutoFlip error - Segmentation Fault 

### ISSUE THREAD

**Issue by kdubey19** [google/mediapipe#2585]
I've followed the installation steps for autoflip and build it using the following command:

bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/autoflip:run_autoflip

I ran the autoflip example by specifying the input & output file locations using command:

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip \ --calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt \ --input_side_packets=input_video_path=/absolute/path/to/the/local/video/file,output_video_path=/absolute/path/to/save/the/output/video/file,aspect_ratio=1:1

and I get the following error:
![image](https://user-images.githubusercontent.com/32731664/134506324-ee9b0102-cb26-439c-839a-0c97fc2b71e7.png)

I20210923 17:45:56.113070   901 shot_boundary_calculator.cc:115] Shot change at: 24.32 seconds.
I20210923 17:45:56.887724   901 shot_boundary_calculator.cc:115] Shot change at: 26.04 seconds.
I20210923 17:45:57.679097   908 shot_boundary_calculator.cc:115] Shot change at: 28 seconds.
W20210923 17:45:58.502621   904 opencv_video_decoder_calculator.cc:230] Not all the frames are decoded (total frames: 750 vs decoded frames: 749).
Segmentation fault

At times the code would throw the warning *Not all the frames are decoded* and lead to success but most of the times it fails.

Below are the system details:
OS : Windows 10 i7,
Memory : 16 GB,
OpenCV @ 3,
Bazelisk version: v1.10.1 | Build label: 3.7.2

**Comment by tullie** [comment]
+1 it's failing for me with a segmentation fault on the life_at_google.mp4 example.

**Comment by kdubey19** [comment]
@nathanfrey-google  @sgowroji  - Request you to please help with the above error

**Comment by kdubey19** [comment]
@sgowroji @jiuqiant  - Request you to please help with the above error at the earliest

**Comment by hironaka** [comment]
Same here

**Comment by darkzbaron** [comment]
Same here!

**Comment by ayushgdev** [comment]
Hello @kdubey19 
Did any of the solutions given above by the community work for you? 
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) (including Autoflip), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
