### ISSUE TITLE
Integrating Mediapipe to an existing C++ project

### ISSUE THREAD

**Issue by mahtaabdn** [google/mediapipe#2586]
> I am trying to use Mediapipe's Holisting Tracking example in an existing C++ project in Qt. First, I built the .so file:
```
package(default_visibility = ["//mediapipe/examples:__subpackages__"])
cc_binary(
    name = "libmediapipe.so",
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/formats:image_frame",
        "//mediapipe/framework/formats:image_frame_opencv",
        "//mediapipe/framework/port:file_helpers",
        "//mediapipe/framework/port:opencv_highgui",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:opencv_video",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        # Stuff used by the models we want
        "//mediapipe/graphs/holistic_tracking:holistic_tracking_to_render_data",
        "//mediapipe/graphs/holistic_tracking:holistic_tracking_cpu_graph_deps",
    ],
    linkopts = ["-Wl,-soname,libmediapipe.so.0"],
    linkshared = 1, ## important
)
```

> Then, I added libmediapipe.so to my Qt project, and then I wrote the following lines of code:
```
std::string calculator_graph_config_contents;
std::string holistic_calculator_graph_config_file = "/home/mahtab/mediapipe/graphs/holistic_tracking/holistic_tracking_cpu.pbtxt";
absl::Status configLoaded = mediapipe::file::GetContents(holistic_calculator_graph_config_file, &calculator_graph_config_contents);
```

> But, When I run the code I have this error:
```
error: undefined reference to `mediapipe::file::GetContents(absl::string_view, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool)'
arbody.o: In function `ARRunnable::run(QVideoFrame*, QVideoSurfaceFormat const&, QFlags<QVideoFilterRunnable::RunFlag>)':
arbody.cpp:(.text+0x171): undefined reference to `mediapipe::file::GetContents(absl::string_view, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool)'
```

> I would appreciate any help.

**Comment by willstott101** [comment]
I've had to set `alwayslink=1,` in `mediapipe/framework/BUILD` for the target `cc_library(name = "calculator_graph",`

**Comment by mahtaabdn** [comment]
> I've had to set `alwayslink=1,` in `mediapipe/framework/BUILD` for the target `cc_library(name = "calculator_graph",`

I've also set `alwayslink=1`, too. But it doesn't work.

**Comment by willstott101** [comment]
Have you tried doing the same thing for the `//mediapipe/framework/port:file_helpers` target? I don't use that one, so IDK if it's neccessary.

**Comment by willstott101** [comment]
You can read the file however you want too - if that function isn't working you can just read it with normal C++ or Qt stuff

**Comment by rigngsbase** [comment]
@mahtaabdn  I must admit that I am quite a newb when it comes to build systems. So far I've managed to build the hello_word and the Pose Tracking examples on Windows (going through quite a few hoops along the way) https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows

Of course, building those examples gives me an executable, which I can't integrate in another project.

What I'd like to do is have mediapipe as a dll or something similar so I can pass the framework an image and get joint coordinates in return, ideally. Can someone point me in the right direction?

I am going to use this Pose Tracking project

https://github.com/google/mediapipe/tree/master/mediapipe/examples/desktop/pose_tracking

**Comment by raibosravan** [comment]
@mahtaabdn : Better to convert your project to BAZEL build sys  and include Qt lib dependencies in BAZEL build files instead of trying to add mediapipes in Qt project file.
