### ISSUE TITLE
Sending to wrong VM  (Javascript Selfie-Segmentation)

### ISSUE THREAD

**Issue by jimver04** [google/mediapipe#2590]
Hi,
my application with Selfie-Segmentation sometimes works but sometimes not. By comparing the logs I found that the application is not working when the VM that the solution was send is not the same as the original VM (see image below, right side). However, when there is no original VM referred then the application works well. 

Why is it send to another VM ? How can I force the VM number to be the same ? Why the good example has no VM number on the initialization ?

Google Chrome v93.0.4577.82 

camera_utils@0.3/camera_utils.js
control_utils@0.6/control_utils.js
drawing_utils@0.3/drawing_utils.js
selfie_segmentation@0.1/selfie_segmentation.js

![image](https://user-images.githubusercontent.com/1898502/134625787-f17cfdb9-c4a9-448b-be68-1c9ff1f4ea74.png)

**Comment by sgowroji** [comment]
Hi @jimver04, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by jimver04** [comment]
wait just 5' to generate a codepen

**Comment by jimver04** [comment]
Here is the codepen.

https://codepen.io/jimver04/pen/gORdBwp

**Comment by jimver04** [comment]
For some reason, in Firefox 92.0 doesn't stack, although the 2D canvas present a blinking behaviour. The main issue is in Chrome which is sending to wrong VM to about 90% of the occasions. Only 1 out of 10 works, the rest of the time is stack completely.

**Comment by jimver04** [comment]
Just load the codepen above with Chrome. The first time will work, but if you press refresh (F5) will stack. If you see in the console, the first time there is no VM reference in the initialization (see my figure above), but the second the VM is initialized with a number but send to another number. I suspect that the issue might be solved with queueMicrotask when receiving the files on WASM (initialization phase).

https://stackoverflow.com/questions/20388563/chrome-console-vm/67026569#67026569
https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide

**Comment by sgowroji** [comment]
Hi @jimver04, Thank you for your patience and  also for sharing the above details. We have shared your request to @mhays-google who can guide you on this. Thanks!

**Comment by mhays-google** [comment]
I don't have any feedback right now, but inviting a peer.

@tyrmullen -- take a look at this?

**Comment by kuaashish** [comment]
Hello @jimver04,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
