### ISSUE TITLE
How to plot joints with less visiblity

### ISSUE THREAD

**Issue by aafaqin** [google/mediapipe#2592]
How to plot the joints which have a lower visibility in Pose estimation.
The detection are happening pretty accurate and result is in landmark array. But only points witch high coincidence are ploted. How  to plot all the points

**Comment by sgowroji** [comment]
Hi @aafaqin, Could you please elaborate your use case with more details. Thanks!

**Comment by aafaqin** [comment]
> Hi @aafaqin, Could you please elaborate your use case with more details. Thanks!

For example I am detecting knee in the 
`
results = pose.process(image)
`
I get the knee detections.

but when I do 
```
 mp_drawing.draw_landmarks(
        image,
        results.pose_landmarks,
        mp_pose.POSE_CONNECTIONS,
    )
```
   The knee is not visible on the plotted image

**Comment by aafaqin** [comment]
another example 
Left elbow is not plotted
```
landmark {
  x: 0.44888752698898315
  y: 0.3038821518421173
  z: -0.11011102050542831
  visibility: 0.15941433608531952
}
```
but right elbow is  plotted
```
landmark {
  x: 0.44472721219062805
  y: 0.315041720867157
  z: -0.2294567972421646
  visibility: 0.8888634443283081
}
```
How can i plot left elbow as well??
![image](https://user-images.githubusercontent.com/22724087/134635703-b2a34a1a-b55e-4405-8580-cc96269babb4.png)

**Comment by aafaqin** [comment]
[mediapipe/python/solutions/drawing_utils.py](url) 
In this file
`
_PRESENCE_THRESHOLD = 0.5
_VISIBILITY_THRESHOLD = 0.5
`
 modify these 2 variables to get plots of joints with low probability
