### ISSUE TITLE
Attention Mesh: High-fidelity Face Mesh Prediction in Real-time

### ISSUE THREAD

**Issue by lucmichalski** [google/mediapipe#2593]
Hi guys,

Hope you are all well !

I am trying mediapipe with unity3d with the following project: https://github.com/keijiro/FaceMeshBarracuda

![68747470733a2f2f692e696d6775722e636f6d2f4f4b46576b75672e676966 (1)](https://user-images.githubusercontent.com/1963546/134635417-e3aebb0b-5d88-4630-b206-effe99111e82.gif)

And I like to achieve face animation of this avatar based on facemesh predictions.
![1 jpgA1500AD1-301E-4DD4-9641-5FE40A1E69B2Zoom](https://user-images.githubusercontent.com/1963546/134635024-1ca1681c-a13f-4479-b76d-70e980025ae7.jpg)

Unfortunately, I failed to animate the avatar and after a couple of research I found that paper, from google, and linked to the mediapipe project: https://arxiv.org/abs/2006.10962

So I was wondering if you have considered to open source the code for this paper as it is really close of what I d like to achieve to animate the face of my android.

Thanks for any insights or inputs on that question.

Cheers,
Luc Michalski

**Comment by mcclanahoochie** [comment]
Hi,
The face mesh module used by that unity project is the open source mediapipe face mesh graph/model. 
To animate a character in unity, you will need to create a mapping from the face mesh coordinates into points corresponding to the character model in unity. 
The FaceMeshBarracuda project seems to already handle importing the mediapipe points into unity very well, so the remaining piece is to map those points in unity (handled by FaceMeshBarracuda) into your models' coordinate system.
Another project that integrates meidapipe & unity is https://github.com/midopooler/CharacterAnimationUsingMediapipe (focused on body pose points)

**Comment by lucmichalski** [comment]
HI @mcclanahoochie ,

Thanks for your reply !

The link is dead. ^^

Cheers,
Luc
