### ISSUE TITLE
Update which version of abseil c++ mediapipe depends on

### ISSUE THREAD

**Issue by capt-sms** [google/mediapipe#2594]
"mediapipe depends on an old version of abseil c++ that does not include [a commit](https://github.com/abseil/abseil-cpp/commit/5bf048b8425cc0a342e4647932de19e25ffd6ad7#diff-c2c26d26953e79ce20dd00dccad9e10e0249a17861480d58e73c4616786f2679) necessary to work on newer libstdc++ versions. So, com_google_absl in the mediapipe [WORKSPACE](https://github.com/google/mediapipe/blob/137e1cc7630524ea1c3a9b120985285fe43c8a3f/WORKSPACE#L23) needs an update."

So, mediapipe doesn't build with GCC11 as a result and it's already being shipped as a default so it's a problem.

**Comment by sgowroji** [comment]
Hi @capt-sms, Could you please share the errors with present build/install. Can you also share the steps to reproduce it. Thanks!

**Comment by capt-sms** [comment]
> Hi @capt-sms, Could you please share the errors with present build/install. Can you also share the steps to reproduce it. Thanks!

Just install GCC11 (for me it's just on a fresh Fedora installation, it pulls the newest libstdc++) and run:

`bazelisk run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 --sandbox_writable_path ~/.ccache --sandbox_debug --verbose_failures mediapipe/examples/desktop/hello_world:hello_world`

it builds and then this happens:

> external/com_google_absl/absl/synchronization/internal/graphcycles.cc: In member function 'void absl::lts_2020_09_23::synchronization_internal::GraphCycles::RemoveNode(void*)':
> external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:26: error: 'numeric_limits' is not a member of 'std'
>   451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
>       |                          ^~~~~~~~~~~~~~
> external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:49: error: expected primary-expression before '>' token
>   451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
>       |                                                 ^
> external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:52: error: '::max' has not been declared; did you mean 'std::max'?
>   451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
>       |                                                    ^~~
>       |                                                    std::max
> In file included from /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/algorithm:62,
>                  from external/com_google_absl/absl/synchronization/internal/graphcycles.cc:38:
> /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algo.h:3467:5: note: 'std::max' declared here
>  3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
>       |     ^~~
> 1632479329.418486073: src/main/tools/linux-sandbox-pid1.cc:410: wait returned pid=2, status=0x100
> 1632479329.418505079: src/main/tools/linux-sandbox-pid1.cc:428: child exited normally with code 1
> 1632479329.418759391: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
> Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
> INFO: Elapsed time: 87.276s, Critical Path: 82.65s
> INFO: 140 processes: 6 internal, 134 linux-sandbox.
> FAILED: Build did NOT complete successfully
> FAILED: Build did NOT complete successfully

If I switch to Clang (that apparently helped before) by exporting CC/CXX, the same build command returns similar errors:

> external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:26: error: no member named 'numeric_limits' in namespace 'std'
>   if (x->version == std::numeric_limits<uint32_t>::max()) {
>                     ~~~~~^
> external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:41: error: unexpected type name 'uint32_t': expected expression
>   if (x->version == std::numeric_limits<uint32_t>::max()) {
>                                         ^
> external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:52: error: no member named 'max' in the global namespace
>   if (x->version == std::numeric_limits<uint32_t>::max()) {
>                                                  ~~^
> 3 errors generated.
> 1632479644.592470104: src/main/tools/linux-sandbox-pid1.cc:410: wait returned pid=2, status=0x100
> 1632479644.592492238: src/main/tools/linux-sandbox-pid1.cc:428: child exited normally with code 1
> 1632479644.592746223: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
> Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
> INFO: Elapsed time: 200.591s, Critical Path: 162.44s
> INFO: 430 processes: 106 internal, 324 linux-sandbox.
> FAILED: Build did NOT complete successfully
> FAILED: Build did NOT complete successfully

As I understand, this needs to be done: https://www.gnu.org/software/gcc/gcc-11/porting_to.html#header-dep-change

**Comment by sgowroji** [comment]
Hi @capt-sms, Can you pull the latest version and check . Its updated now https://github.com/google/mediapipe/blob/33d683c67100ef3db37d9752fcf65d30bea440c4/WORKSPACE#:~:text=%23%20ABSL%20cpp%20library,)
