### ISSUE TITLE
Javascript example gives wrong download location for control_utils_3d.js

### ISSUE THREAD

**Issue by diarmidmackenzie** [google/mediapipe#2596]
Thank you for submitting a MediaPipe documentation issue.
The MediaPipe docs are open source! To get involved, read the documentation Contributor Guide

## URL(s) with the issue:
https://google.github.io/mediapipe/solutions/pose.html#javascript-solution-api

## Description of issue (what needs changing):

This line is wrong.  
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/control_utils_3d.js" crossorigin="anonymous"></script>

Should be:
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d/control_utils_3d.js" crossorigin="anonymous"></script>

### Clear description

The provided link does not work.  Attempts to download the JS file fail - and the whole example provided does not work as a result.

The JS file can be downloaded from the link that I have suggested.

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
https://github.com/google/mediapipe/blob/master/CONTRIBUTING.md

Yeah, ok.

**Comment by sgowroji** [comment]
Hi @diarmidmackenzie, Could you please point us the location in our documentation where the links are wrong?

**Comment by diarmidmackenzie** [comment]
See the PR that I created.
https://github.com/google/mediapipe/pull/2597

Alternatively, see in the issue where it says: URL(s) with the issue...

Go to that URL:
https://google.github.io/mediapipe/solutions/pose.html#javascript-solution-api

Now use "search in page" (that's Ctrl-F if you are using Google Chrome" for the text I said was wrong.

e.g. search for: "drawing_utils/control_utils_3d.js"

That is the bit of text that is wrong.

Just in case it's still not clear, I have done a screenshot for you with the incorrect text highlighted in orange, and the URL visible in the browser...

![image](https://user-images.githubusercontent.com/16045703/134989824-e1eed50b-3c31-4abc-8fe8-474f9c17a4f1.png)

**Comment by sgowroji** [comment]
Thank you for raising the PR. That will be reviewed by the team and will be pushed into the Github code repo, if there are no code changes in it. We are closing this issue now and please subscribe for the  #2597  PR for further updates.

**Comment by JudeOsborn** [comment]
I can confirm that the URL in the screenshot above is incorrect. 

However, I've tried changing the URL as suggested but when I do I get an error in the JS console when trying to run the example code (same as the screenshot above):

<img width="809" alt="Screen Shot 2021-11-23 at 5 10 31 pm" src="https://user-images.githubusercontent.com/255014/142978211-14ef5df5-453e-4ed4-b85a-fffe0362bcb6.png">

**Comment by diarmidmackenzie** [comment]
Does this work for you?  Runs for me without errors, and my recollection is that it was just a copy/paste of this sample code, witht the error fixed.

https://diarmidmackenzie.github.io/face-geometry/mediapipe/original.html

**Comment by JudeOsborn** [comment]
Yes, that does work for me, however upon inspecting the source it does not
appear to include control_utils_3d.js.

[image: Screen Shot 2021-11-24 at 12.09.08 pm.png]

**Comment by diarmidmackenzie** [comment]
https://github.com/diarmidmackenzie/face-geometry/blob/main/mediapipe/original.html#L7

**Comment by JudeOsborn** [comment]
This version looks good for my purposes. Thank you.
