### ISSUE TITLE
mediapipe supports every tflite file？

### ISSUE THREAD

**Issue by zhangcd123** [google/mediapipe#260]
I want know wether mediapipe supports every tflite file, for example deeplabv3?

**Comment by mgyong** [comment]
@zhangcd123 Each MediaPipe example requires calculators for pre-processing (processing images into tensors of right shape) for the tflite model in question. Similarly, you will also need post processing calculators to convert the tensor output results specific to the tflite model to appropriate output. We have not done any work on deeplab as such you will have to implement your own pre-processing and post processing calculators for the deeplabv3 tflite model

**Comment by zhangcd123** [comment]
But when I used mobilenetv2+deeplabv3+ tflite file in mediapipe and got some ops that Mediapipe not support such as BATCH_TO_SPACE_ND 、SPACE_TO_BATCH_ND，these two ops should I implement by myself？

**Comment by MAkcanca** [comment]
BATCH_TO_SPACE_ND is already implemented, SPACE_TO_BATCH_ND not so sure.
On the TFliteModelImporter.js file, you need to implement those in the **_addOpsAndParams** function. Must be around line 400. You will see the pattern.

For instance, to add RELU
```
case tflite.BuiltinOperator.RELU: {
          opType = this._nn.RELU;
        } break;
```

**Comment by zhangcd123** [comment]
@MAkcanca can you tell me where is the TFliteModelImporter.js file, I can not find it.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by PrinceP** [comment]
I was trying to run the default model present for deeplab from https://www.tensorflow.org/lite/models/segmentation/overview
Following is the log from loading the tflite model with same setup of hair segmentation. 

```
I/native: I0101 18:25:18.158473 19366 tflite_inference_calculator.cc:211] TfLiteInference:Process1
I/native: I0101 18:25:18.168609 19366 tflite_inference_calculator.cc:247] TfLiteInference:Process2
I/native: I0101 18:25:18.169961 19366 recolor_calculator.cc:131] RGB OUT Tagged
I/native: I0101 18:25:18.179634 19366 graph.cc:415] Start running the graph, waiting for inputs.
I/native: I0101 18:25:18.180408 19366 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 5
I/native: I0101 18:25:18.182210 19440 gl_context.cc:233] GL version: 3.2 (OpenGL ES 3.2 V@385.0 (GIT@bc00834, I609ab310b2) (Date:04/11/19))
I/native: I0101 18:25:18.186280 19434 ColorSliderCalculator.cc:77] Color Slider Calculator Runner0 0 0
D/ExternalTextureConv: Created output texture: 3 width: 1444 height: 1925
I/native: I0101 18:25:18.198865 19439 ColorSliderCalculator.cc:77] Color Slider Calculator Runner0 0 0
I/native: I0101 18:25:18.199147 19436 jni_util.cc:40] GetEnv: not attached
I/native: I0101 18:25:18.307039 19365 resource_util_android.cc:42] Successfully loaded: person_segmentation.tflite
I/tflite: Initialized TensorFlow Lite runtime.
I/tflite: Created TensorFlow Lite delegate for GPU.
I/tflite: Replacing 70 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
I/native: I0101 18:25:19.411098 19365 tflite_inference_calculator.cc:301] TfLiteInference:Process3
I/native: I0101 18:25:19.464181 19365 tflite_inference_calculator.cc:308] TfLiteInference:Process4
    I0101 18:25:19.464304 19365 tflite_inference_calculator.cc:314] TfLiteInference:Process4.1
    I0101 18:25:19.464329 19365 tflite_inference_calculator.cc:317] TfLiteInference:Process4.1
```
The tflite inference calculator gets stuck at following code snippet from [tflite_inference_calculator.cc](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_inference_calculator.cc)

```
    LOG(INFO) << "TfLiteInference:Process4.1" << std::endl;
    RET_CHECK_EQ(input_tensors.size(), 1);

    LOG(INFO) << "TfLiteInference:Process4.1" << std::endl;
    MP_RETURN_IF_ERROR(gpu_helper_.RunInGlContext(
        [this, &input_tensors]() -> ::mediapipe::Status {
          // Explicit copy input.
          RET_CHECK_CALL(CopyBuffer(input_tensors[0], gpu_data_in_->buffer));
          return ::mediapipe::OkStatus();
        }));

    LOG(INFO) << "TfLiteInference:Process4.1.1" << std::endl;
```
Compilation is successful from bazel. What is the issue at RET_CHECK_CALL(CopyBuffer(input_tensors[0], gpu_data_in_->buffer));
Can someone redirect me?

**Comment by eknight7** [comment]
Are you seeing some error @PrinceP ?

**Comment by PrinceP** [comment]
@eknight7 The process is not in error. It is stuck at the tflite_inference_calculator.

**Comment by PrinceP** [comment]
Any updates or pointers I can follow for the problem @eknight7 ?
