### ISSUE TITLE
How does per-point visibility in BlazePose calculated?

### ISSUE THREAD

**Issue by andreanlay** [google/mediapipe#2601]
Hello,

I read the BlazePose paper and it said BlazePose implement per-point-visibility classifier by creating occlusion simulation, but I don't see how this classifier works, is it by calculating intersection between object or by using specific NNs. I tried searching the source code for explanation but I cannot find it.

Is there any explanation for how visibility calculated?

Thanks!

**Comment by sgowroji** [comment]
Hi @andreanlay, If you are looking for pose classification. Please go through our documentation and python code samples from [here](https://google.github.io/mediapipe/solutions/pose_classification.html#classification)

**Comment by andreanlay** [comment]
Hello @sgowroji, actually I'm not looking for pose classification. I am looking for how BlazePose's calculate keypoints visibility.
I just inspected BlazePose's trained model from this repo and I saw that BlazePose's directly outputs 5 values(including visibility) for each keypoints. 
So I just want to make sure is it true if BlazePose's calculates visibility directly in the CNN (not by using any manual calculation)?

**Comment by kuaashish** [comment]
Hello @andreanlay,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by andreanlay** [comment]
Hi @kuaashish, thanks for the heads up. I will check out latest MediaPipe solutions for my future ML projects, thanks!

**Comment by kuaashish** [comment]
Thank you for the confirmation @andreanlay, Please do check our new upgraded solutions and use case which are superset of the Legacy solutions.
