### ISSUE TITLE
    Calculator::Process() for node "holisticlandmarkgpu__poselandmarkgpu__poselandmarkbyroigpu__poselandmarksandsegmentationinverseprojection__InverseMatrixCalculator" failed: ; Inverse matrix cannot be calculated.tors/util/inverse_matrix_calculator.cc:38) 

### ISSUE THREAD

**Issue by wingdi** [google/mediapipe#2602]
platform：Android（phone：huawei mate30 4g, os HarmonyOS, arch: arm64+Da vinci Core ）,  aar

question 1 :  I run [holistictrackinggpu.apk](https://drive.google.com/file/d/1o-Trp2GIRitA0OvmZWUQjVMa476xpfgK/view?usp=sharing) from https://google.github.io/mediapipe/solutions/holistic.html , the view is black. anyone have successed run the apk ?

question 2： I use latest mediapipe code build and generated holistic_tracking.aar and corresponding .binarypb / .tflite
When I run demo, it Got this error:
```
E/FrameProcessor: Mediapipe error: 
    com.google.mediapipe.framework.MediaPipeException: internal: Graph has errors: 
    Calculator::Process() for node "holisticlandmarkgpu__poselandmarkgpu__poselandmarkbyroigpu__poselandmarksandsegmentationinverseprojection__InverseMatrixCalculator" failed: ; Inverse matrix cannot be calculated.tors/util/inverse_matrix_calculator.cc:38) 
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:395)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:458)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:403)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:338)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)

``` 
The used code is copy from: mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java

**Comment by wingdi** [comment]
Anyone have encounter this problem ?

**Comment by wingdi** [comment]
I think maybe because the input frame problem. So i extract local video Frame give  Graph in FrameProcessor.java, it called graph.addConsumablePacketToInputStream(videoInputStream,imagePacket,timestamp).  this way didn't show error,  But the output SurfaceView still black,  and didn't call back FrameProcessor's callback.

**Comment by sgowroji** [comment]
Hi @wingdi, From the logs we can see you have made some changes in the graph. Could you please share your graph changes to investigate the issue further. Thanks! 

E/FrameProcessor: Mediapipe error: 
    com.google.mediapipe.framework.MediaPipeException: internal: **Graph has errors:**

**Comment by theColorfulRainbow** [comment]
Hey,

I get a similar issue on the Python version for Mediapipe.
The issue occurs when performing Pose estimation.
It also seems to occur only on certain videos.
This is my Stack Trace:

```
E20210927 12:03:19.345840 81099 calculator_graph.cc:804] INTERNAL: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "poselandmarkbyroicpu__poselandmarksandsegmentationinverseprojection__InverseMatrixCalculator" failed: ; Inverse matrix cannot be calculated.tors/util/inverse_matrix_calculator.cc:38) 

RuntimeError: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "poselandmarkbyroicpu__poselandmarksandsegmentationinverseprojection__InverseMatrixCalculator" failed: ; Inverse matrix cannot be calculated.tors/util/inverse_matrix_calculator.cc:38) 

````

**Comment by wingdi** [comment]
@theColorfulRainbow  Yes, we encounter the same error,   I still have not solve it.

@sgowroji thanks for reply !  I do changed some code in FrameProcessor.java , but other code and configuration profile didn't change. And when I using didn't changed FrameProcessor.java, it still have this problem.

**Comment by theColorfulRainbow** [comment]
In case this takes too long to solve, my workaround is to **reset** the object. 
This will require you to go **modify** the source code. 
What I did, is I added a function called _reset()_ that basically calls the _init()_ function, as it seemed as if it just resets the object parameters. (you could just say pose.__init__() with the same amount of success)

**Comment by Ar4enal** [comment]
Try to build the latest aar.
