### ISSUE TITLE
ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:palmdetectioncpu__Inferencecalculator__palmdetectioncpu__input_tensor" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").

### ISSUE THREAD

**Issue by karataserol** [google/mediapipe#2603]
Hi  Sgowroji 

when ı try to run below code or any mediapipe example on my OS (linux Mint 20) ı am getting below error and I couldn't find any solution other than writing to you 

so could you have look and let me know please if any solution 

/////////////////////////////////Code //////

import cv2
import mediapipe as mp
import time

cap = cv2.VideoCapture(1)

mpHands = mp.solutions.hands
hands = mpHands.Hands()
mpDraw = mp.solutions.drawing_utils

pTime = 0
cTime = 0

while True:
    success, img = cap.read()
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = hands.process(imgRGB)
    # print(results.multi_hand_landmarks)

    if results.multi_hand_landmarks:
        for handLms in results.multi_hand_landmarks:
            for id, lm in enumerate(handLms.landmark):
                # print(id, lm)
                h, w, c = img.shape
                cx, cy = int(lm.x * w), int(lm.y * h)
                print(id, cx, cy)
                # if id == 4:
                cv2.circle(img, (cx, cy), 15, (255, 0, 255), cv2.FILLED)

            mpDraw.draw_landmarks(img, handLms, mpHands.HAND_CONNECTIONS)

    cTime = time.time()
    fps = 1 / (cTime - pTime)
    pTime = cTime

    cv2.putText(img, str(int(fps)), (10, 70), cv2.FONT_HERSHEY_PLAIN, 3,
                (255, 0, 255), 3)

  cv2.imshow("Image", img)
    cv2.waitKey(1)

////////////////////////////////////////erorr mesage////////////////////////////////////////////////////////////////////////

Traceback (most recent call last):
  File "/root/PycharmProjects/pythonProject2/main.py", line 9, in <module>
    hands = mpHands.Hands()
  File "/root/PycharmProjects/pythonProject2/venv/lib/python3.9/site-packages/mediapipe/python/solutions/hands.py", line 109, in __init__
    super().__init__(
  File "/root/PycharmProjects/pythonProject2/venv/lib/python3.9/site-packages/mediapipe/python/solution_base.py", line 237, in __init__
    validated_graph.initialize(
ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:palmdetectioncpu__Inferencecalculator__palmdetectioncpu__input_tensor" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2306. Can you refer this [code](https://google.github.io/mediapipe/solutions/hands.html#python-solution-api) for static image.

**Comment by karataserol** [comment]
hello thank you for your repply , ı have try it  again with static picture  again but ı couldnt 

/////////////////////////////////////////////////////code/////////////////////////////////////////////////
import cv2
import mediapipe as mp
mp_face_detection = mp.solutions.face_detection
mp_drawing = mp.solutions.drawing_utils

# For static images:
IMAGE_FILES = ['/home/pars/Masaüstü/pi.jpeg' ]
with mp_face_detection.FaceDetection(
    model_selection=1, min_detection_confidence=0.5) as face_detection:
  for idx, file in enumerate(IMAGE_FILES):
    image = cv2.imread(file)
    # Convert the BGR image to RGB and process it with MediaPipe Face Detection.
    results = face_detection.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

    # Draw face detections of each face.
    if not results.detections:
      continue
    annotated_image = image.copy()
    for detection in results.detections:
      print('Nose tip:')
      print(mp_face_detection.get_key_point(
          detection, mp_face_detection.FaceKeyPoint.NOSE_TIP))
      mp_drawing.draw_detection(annotated_image, detection)
    cv2.imwrite('/tmp/annotated_image' + str(idx) + '.png', annotated_image)




/////////////////////// here is result ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Traceback (most recent call last):
  File "/home/pars/PycharmProjects/pythonProject2/main.py", line 8, in <module>
    with mp_face_detection.FaceDetection(
  File "/home/pars/PycharmProjects/pythonProject2/venv/lib/python3.9/site-packages/mediapipe/python/solutions/face_detection.py", line 89, in __init__
    super().__init__(
  File "/home/pars/PycharmProjects/pythonProject2/venv/lib/python3.9/site-packages/mediapipe/python/solution_base.py", line 237, in __init__
    validated_graph.initialize(
ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:Inferencecalculator__input_tensors" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").

Process finished with exit code 1





////////////////////////////////debug/////////////////////////////////////

Connected to pydev debugger (build 212.5284.44)
Traceback (most recent call last):
  File "/home/pars/Documents/pycharm-community-2021.2.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/pars/Documents/pycharm-community-2021.2.2/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/pars/PycharmProjects/pythonProject2/main.py", line 8, in <module>
    with mp_face_detection.FaceDetection(
  File "/home/pars/PycharmProjects/pythonProject2/venv/lib/python3.9/site-packages/mediapipe/python/solutions/face_detection.py", line 89, in __init__
    super().__init__(
  File "/home/pars/PycharmProjects/pythonProject2/venv/lib/python3.9/site-packages/mediapipe/python/solution_base.py", line 237, in __init__
    validated_graph.initialize(
ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:Inferencecalculator__input_tensors" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").

Process finished with exit code 1

**Comment by sgowroji** [comment]
Hi @karataserol, You can try this [colab](https://colab.sandbox.google.com/drive/1FvH5eTiZqayZBOHZsFm-i7D-JvoB9DVz)

**Comment by karataserol** [comment]
Can you please explain to me why I can't run this code on my own operating system 
am i doing a mistake? , is there anything else i need to fix , i wanted to produce in other projects with this module , 
can you help me please

**Comment by sgowroji** [comment]
Hi @karataserol,  You need to add the Hands images to your IMAGE_FILES[]  array as below and check the image in the tmp folder. And  `pip install mediapipe==0.8.7.1` to get the latest python mediapipe package.


```
image=cv2.imread('hands.jpeg')
IMAGE_FILES.append(image)
```

**Comment by karataserol** [comment]
dear Sgowroji 
my problem is not above code  i pasted it just as an example please have a look my first mesage ,  no matter what i try  code releted mediapipe i am geting same error which is below

I don't know if it is from the tensorflow module or the cpu, do I need to add another module, else do I have a hardware problem?

As I understand from a previous problem similar to the subject, I think there is no solution for mediapipe, I wonder if these error codes that I have added below have no equivalent in your systems

What does the following error code mean to you? could you answer please

```
#Traceback (most recent call last):
  File "/home/pars/PycharmProjects/pythonProject2/main.py", line 8, in <module>
    with mp_pose.Pose(
  File "/home/pars/PycharmProjects/pythonProject2/venv/lib/python3.9/site-packages/mediapipe/python/solutions/pose.py", line 146, in __init__
    super().__init__(
  File "/home/pars/PycharmProjects/pythonProject2/venv/lib/python3.9/site-packages/mediapipe/python/solution_base.py", line 237, in __init__
    validated_graph.initialize(
ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:posedetectioncpu__Inferencecalculator__posedetectioncpu__input_tensors" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").
```

**Comment by karataserol** [comment]
ok thank you so much mr.Hadon ı solved my problem with your solition

**Comment by kivancagaogluu** [comment]
@karataserol How did you solve this problem? Whatever i rename variables doesn't matter getting same error
``ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:poselandmarkcpu__posedetectioncpu__Inferencecalculator__poselandmarkcpu__posedetectioncpu__input_tensors" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").``

**Comment by karataserol** [comment]
> @karataserol How did you solve this problem? Whatever i rename variables doesn't matter getting same error `ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:poselandmarkcpu__posedetectioncpu__Inferencecalculator__poselandmarkcpu__posedetectioncpu__input_tensors" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").`

`
**@kivancagaogluu  muhtemelen kodu çalıştırmaya denediğiniz işletim sisteminde varsayılan cpu yerine  gpu  seçili bu nedenle inputu stream edemiyorsunuz , maalasef library değisiklik yaparakda bu durumu çozemeyeceksiniz , ya yeni bir kod ekleyip  istemciden modeli cpu da çalıştırmasını deneyceksiniz yada   0 dan cpu ve gpu ayarları yaparak başka bir sanal makine kurup onun üzerinde çalıştırmayı deneyeceksiniz** `

**Comment by kivancagaogluu** [comment]
@karataserol Yanıtınız için çok teşekkür ederim. Hobi olarak başladığım bir projeydi belki ileriki bir tarihte devam ederim. Sorunun net bir çözümünü ne kadar arasam da bulamadım.

**Comment by Hafikan** [comment]
@kivancagaogluu merhabalar erol hocam, Linux mint, Raspian ve Win 10 da farklı farklı python sürümlerinde teker teker denedim. Linux tabanlı sistemlerde bu hatayı alıyorum ve çözümü pek yok gibi anlaşılan. Mediapipe kütüphanesini de bir projeden dolayıı Linux işletim sistemi üzerine kurmam gerekiyor. Tam olarak nasıl bir çözüm uygulayabiliriz?

**Comment by karataserol** [comment]
@Hafikan  merhaba windows 10 üzerinde  sanal bir  makineye linux kurarak deneyin ,

**Comment by Hafikan** [comment]
@karata raspbery pi de bu yazılımı kullanmam gerekiyor.

**Comment by karataserol** [comment]
@Hafikan  ekteki çözümü deneyip bilgi verirmisin ,işe yaramazsa sonuçların çıktısını alıp paylaşın ona gore elimden gelen bir şey olursa soyleyeyim 

eger raspi 3 model b kullanıyorsan 

`sudo pip3 install pathlib. And I run the code again with pip3: sudo pip install mediapipe-rpi3`

diger çözüm 

`a useful package to install mediapipe fastly in raspberry
for raspberry pi 3 and raspberry pi 4

//FFmpeg and OpenCV

sudo apt install ffmpeg python-opencv
// dependency packages

sudo apt install libxcb-shm0 libcdio-paranoia-dev libsdl2-2.0-0 libxv1  libtheora0 libva-drm2 libva-x11-2 libvdpau1 libharfbuzz0b libbluray2 libatlas-base-dev libhdf5-103 libgtk-3-0 libdc1394-22 libopenexr23
finally for raspberry pi 3 use :

sudo pip install mediapipe-rpi3
or for raspberry pi 4 use :

sudo pip install mediapipe-rpi4
the commands were taken from :

for raspberrypi 3: https://pypi.org/project/mediapipe-rpi3/

for raspberry pi 4: https://pypi.org/project/mediapipe-rpi4/`

kaynak 
https://stackoverflow.com/questions/67410495/how-to-install-and-use-mediapipe-on-raspberry-pi-4

**Comment by alpersolak** [comment]
ı got this Error bu find simple solutions
sudo raspi-config
6-advaced options 
a2 - gldriver
g2 - gl 
press enter 
this work for me 
good luck

**Comment by AliUnalunlukal** [comment]
@karataserol hocam benim proje için sadece linux kullanılabilecek bir bilgisayarda mediapipe kullanmam gerekiyor

**Comment by AliUnalunlukal** [comment]
nasıl çözerim

**Comment by alpersolak** [comment]
https://google.github.io/mediapipe/getting_started/gpu_support.html
burdan gerekli kurulumları yaparsan sorun çözülür

**Comment by insanolanbiri** [comment]
Sanırsam sadece Türkçe sistemlerde bu hata çıkıyor (bkz: #3311) geçici bir çözüm için raspberryi ingilizce olarak kullanmak veya programı LC_ALL=en_US.UTF8 ile çalıştırmak işe yarayabilir
