### ISSUE TITLE
Implemented iris in python Using docker installation

### ISSUE THREAD

**Issue by sandesh1994199** [google/mediapipe#2605]
**System information:- Windows 10, WSL2
- OS Platform and Distribution :ubuntu 18.04
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):
- Programming Language and version :-python 3.6.9

I have fallowed #1530 and #2320 to implement iris in python.

**After successful build** 

[5,446 / 5,680] Compiling mediapipe/framework/tool/text_to_binary_graph.cc [for host]; 3s local

Target //mediapipe/python:_framework_bindings.so up-to-date:

[5,680 / 5,680] checking cached actions

  bazel-bin/mediapipe/python/_framework_bindings.so

[5,680 / 5,680] checking cached actions

INFO: Elapsed time: 153.277s, Critical Path: 95.04s

[5,680 / 5,680] checking cached actions

INFO: 400 processes: 2 internal, 398 local.

[5,680 / 5,680] checking cached actions

INFO: Build completed successfully, 400 total actions

INFO: Build completed successfully, 400 total actions

running modify_inits

running build_py

copying mediapipe/__init__.py -> build/lib.linux-x86_64-3.6/mediapipe

running egg_info

writing mediapipe.egg-info/PKG-INFO

writing dependency_links to mediapipe.egg-info/dependency_links.txt

writing requirements to mediapipe.egg-info/requires.txt

writing top-level names to mediapipe.egg-info/top_level.txt

reading manifest file 'mediapipe.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

warning: no previously-included files matching '.git*' found anywhere in distribution

warning: no files found matching '*.binarypb' under directory 'mediapipe/models'

warning: no files found matching '*.tflite' under directory 'mediapipe/graphs'

writing manifest file 'mediapipe.egg-info/SOURCES.txt'

copying mediapipe/graphs/iris_tracking/iris_tracking_cpu.binarypb -> build/lib.linux-x86_64-3.6/mediapipe/graphs/iris_tracking

copying mediapipe/modules/face_detection/face_detection_full_range_cpu.binarypb -> build/lib.linux-x86_64-3.6/mediapipe/modules/face_detection

copying mediapipe/modules/face_detection/face_detection_short_range_cpu.binarypb -> build/lib.linux-x86_64-3.6/mediapipe/modules/face_detection

copying mediapipe/modules/face_landmark/face_landmark_front_cpu.binarypb -> build/lib.linux-x86_64-3.6/mediapipe/modules/face_landmark

copying mediapipe/modules/hand_landmark/hand_landmark_tracking_cpu.binarypb -> build/lib.linux-x86_64-3.6/mediapipe/modules/hand_landmark

copying mediapipe/modules/holistic_landmark/holistic_landmark_cpu.binarypb -> build/lib.linux-x86_64-3.6/mediapipe/modules/holistic_landmark

copying mediapipe/modules/objectron/objectron_cpu.binarypb -> build/lib.linux-x86_64-3.6/mediapipe/modules/objectron

copying mediapipe/modules/pose_landmark/pose_landmark_cpu.binarypb -> build/lib.linux-x86_64-3.6/mediapipe/modules/pose_landmark

copying mediapipe/modules/selfie_segmentation/selfie_segmentation_cpu.binarypb -> build/lib.linux-x86_64-3.6/mediapipe/modules/selfie_segmentation

running remove_generated

removing generated binary graphs: mediapipe/modules/selfie_segmentation/selfie_segmentation_cpu.binarypb

removing generated binary graphs: mediapipe/modules/holistic_landmark/holistic_landmark_cpu.binarypb

removing generated binary graphs: mediapipe/modules/face_landmark/face_landmark_front_cpu.binarypb

removing generated binary graphs: mediapipe/modules/objectron/objectron_cpu.binarypb

removing generated binary graphs: mediapipe/modules/hand_landmark/hand_landmark_tracking_cpu.binarypb

removing generated binary graphs: mediapipe/modules/face_detection/face_detection_short_range_cpu.binarypb

removing generated binary graphs: mediapipe/modules/face_detection/face_detection_full_range_cpu.binarypb

removing generated binary graphs: mediapipe/modules/pose_landmark/pose_landmark_cpu.binarypb

error: [Errno 2] No such file or directory: '/mediapipe/mediapipe/calculators/__init__.py'

(mphigh_env) ]0;root@4b0f54910cf9: /mediapiperoot@4b0f54910cf9:/mediapipe#

**I am facing following error** 

(mphigh_env) ]0;root@4b0f54910cf9: /mediapiperoot@4b0f54910cf9:/mediapipe# python test.py

Traceback (most recent call last):

  File "test.py", line 3, in <module>

    mp_iris = mp.solutions.iris

AttributeError: module 'mediapipe' has no attribute 'solutions'

**Comment by sgowroji** [comment]
Hi @sandesh1994199, Could you please have a look at this https://github.com/google/mediapipe/issues/2418#issuecomment-908267743

**Comment by lghasemzadeh** [comment]
> Iris landmarks are now available in the [python face mesh solution](https://google.github.io/mediapipe/solutions/face_mesh#python-solution-api) by setting [refine_landmarks](https://google.github.io/mediapipe/solutions/face_mesh#refine_landmarks) to True.
Thanks for the update.

@sgowroji  But why this [table](https://google.github.io/mediapipe/solutions/solutions) is not up to dated?
Is the performance the same as Iris module itself?
Is that available in Holistic solution as well? since Holistic contains Facemesh.

**Comment by cancan101** [comment]
When using `refine_landmarks=True` on Python face mesh solution, is there anyway to get access to the [iris depth](https://google.github.io/mediapipe/solutions/iris#depth-from-iris)?
