### ISSUE TITLE
Need help with mediapipe facial landmark

### ISSUE THREAD

**Issue by vadile** [google/mediapipe#2606]
Hey 
For one of my projects, I am using media pipe to get facial landmarks points x,y,z of various features on the face from a recorded video. I am using a video as an input and getting a CSV file of these landmarks as an output. I just realized that my video is 10,000 frames and the final output is only for around 9,500 frames. Hence some landmarks are missing. It makes sense since sometimes mediapipe breaks in the middle and hence doesn't give landmark on those frames. I need help on how to solve this issue or if not how shall I get Null value output for these undetermined frames instead of nothing.
I am using face_landmarks in results.multi_face_landmarks to get these landmarks.

**Comment by sgowroji** [comment]
Hi @vadile, Thank you for sharing your query. Could you please share your code changes and tested video for reference to investigate further. Thanks!

**Comment by vadile** [comment]
Here is the code.
video can be any closeup shot. here is an example. https://youtu.be/gq4K9QtYXI4

import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_face_mesh = mp.solutions.face_mesh
import time
import csv
drawing_spec = mp_drawing.DrawingSpec(thickness=1, circle_radius=1)
cap = cv2.VideoCapture(r'C:\Users\vatsala.adile\Desktop\facial landmark\Vatsala Face Landmark\Mod01_Visit2_Code222.mp4')
prevTime = 0
with mp_face_mesh.FaceMesh(
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5) as face_mesh:
    while (cap.isOpened()):
        success, image = cap.read()
        if not success:
            print("Ignoring empty camera frame.")
            continue
        image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)
        image.flags.writeable = False
        results = face_mesh.process(image)
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        with open('Mod01_Visit2_Code222newdata.csv','a', newline='') as csvfile:
            fieldnames=['faciallandmarks']
            thewriter= csv.DictWriter(csvfile, fieldnames=fieldnames)
            if results.multi_face_landmarks:
                for face_landmarks in results.multi_face_landmarks:
                    thewriter.writerow({'faciallandmarks':face_landmarks})
                    mp_drawing.draw_landmarks(
                        image=image,
                        landmark_list=face_landmarks,
                        connections=mp_face_mesh.FACE_CONNECTIONS,
                        landmark_drawing_spec=drawing_spec,
                        connection_drawing_spec=drawing_spec)
    
            currTime = time.time()
            fps = 1 / (currTime - prevTime)
            prevTime = currTime
            cv2.putText(image, f'FPS: {int(fps)}', (20, 70), cv2.FONT_HERSHEY_PLAIN, 3, (0, 196, 255), 2)
            cv2.imshow('MediaPipe FaceMesh', image)5
        
            if cv2.waitKey(5) & 0xFF == 27:
                break
    cap.release

**Comment by vadile** [comment]
I think the problem arises when there is hand in front of eyes or if the face is partially hidden. Which I assume will be harder to fix. I would like to be able to get none or null for the xyz landmarks value for those frames instead of nothing,

**Comment by arashtavakoli** [comment]
You may be able to add the results frame by frame to a dictionary and then fill the frames that mediapipe doesn't detect anything with nans or 0 or whatever you want. Then in the end write the dictionary to a csv file using Pandas.
