### ISSUE TITLE
Question about Mediapipe pose estimation for better FPS

### ISSUE THREAD

**Issue by richardhfj** [google/mediapipe#2607]
Hello everyone,
We are looking to implement the Mediapipe pose estimation model into an Android device. Is it better to use the pose estimation from the Google ML Kit (base/accurate) or rather to grab the tflite model for blazepose 3d ghum?

We are currently using the ML Kit on device pose estimation (base model) but running into a problem with the device only running at 2-3 FPS so we are now looking into further acceleration (XNNPack) in hopes of running with a higher performance. Is it better to use pose_landmark_lite.tflite in this type of situation? Or can XNNPack be directly applied to the ML Kit SDK? Or is there any other type of acceleration that we should be considering? Thanks.

**Comment by sgowroji** [comment]
Hi @richardhfj, You can understand it from here https://github.com/google/mediapipe/issues/1160#issuecomment-872706753
