### ISSUE TITLE
Mediapipe Handtracking not working Desktop WSL

### ISSUE THREAD

**Issue by all3naby** [google/mediapipe#261]
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1     mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
Starting local Bazel server and connecting to it...
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (88 packages loaded, 3619 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/allen/.cache/bazel/_bazel_allen/34990734c3ebcb226096e604c857bd84/sandbox
ERROR: /home/allen/mediapipe/mediapipe/gpu/BUILD:227:1: C++ compilation of rule '//mediapipe/gpu:gpu_buffer_format' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./mediapipe/gpu/gpu_buffer_format.h:23:0,
                 from mediapipe/gpu/gpu_buffer_format.cc:15:
./mediapipe/gpu/gl_base.h:57:10: fatal error: EGL/egl.h: No such file or directory
 #include <EGL/egl.h>
          ^~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 207.468s, Critical Path: 183.79s
INFO: 83 processes: 83 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

**Comment by jiuqiant** [comment]
Sorry about the inconvenience. The following BUILD file fix should solve this issue. We will push it out in a coming release.

```
--- a/mediapipe/calculators/image/BUILD
+++ b/mediapipe/calculators/image/BUILD
@@ -356,13 +356,13 @@ cc_library(
         "//mediapipe/framework/port:opencv_imgproc",
         "//mediapipe/framework/port:ret_check",
         "//mediapipe/framework/port:status",
-        "//mediapipe/gpu:gpu_buffer",
     ] + select({
         "//mediapipe/gpu:disable_gpu": [],
         "//conditions:default": [
             "//mediapipe/gpu:gl_calculator_helper",
             "//mediapipe/gpu:gl_simple_shaders",
             "//mediapipe/gpu:gl_quad_renderer",
+            "//mediapipe/gpu:gpu_buffer",
             "//mediapipe/gpu:shader_util",
         ],
     }),
```

**Comment by all3naby** [comment]
> Sorry about the inconvenience. The following BUILD file fix should solve this issue. We will push it out in a coming release.
> 
> ```
> --- a/mediapipe/calculators/image/BUILD
> +++ b/mediapipe/calculators/image/BUILD
> @@ -356,13 +356,13 @@ cc_library(
>          "//mediapipe/framework/port:opencv_imgproc",
>          "//mediapipe/framework/port:ret_check",
>          "//mediapipe/framework/port:status",
> -        "//mediapipe/gpu:gpu_buffer",
>      ] + select({
>          "//mediapipe/gpu:disable_gpu": [],
>          "//conditions:default": [
>              "//mediapipe/gpu:gl_calculator_helper",
>              "//mediapipe/gpu:gl_simple_shaders",
>              "//mediapipe/gpu:gl_quad_renderer",
> +            "//mediapipe/gpu:gpu_buffer",
>              "//mediapipe/gpu:shader_util",
>          ],
>      }),
> ```
Should I paste this code inside \mediapipe\mediapipe\examples\desktop\hand_tracking\built to get the program running?

**Comment by jiuqiant** [comment]
Hi, the error message shows that "Label '//mediapipe/gpu:gpu_buffer' is duplicated in the 'deps' attribute of rule 'image_cropping_calculator'". Please double check if you  deleted [line 359](https://github.com/google/mediapipe/blob/9437483827ca26bb41949cba5c9477f604c0a6fb/mediapipe/calculators/image/BUILD#L359) and add "//mediapipe/gpu:gpu_buffer" to [line 365](https://github.com/google/mediapipe/blob/9437483827ca26bb41949cba5c9477f604c0a6fb/mediapipe/calculators/image/BUILD#L365).

**Comment by all3naby** [comment]
> Hi, the error message shows that "Label '//mediapipe/gpu:gpu_buffer' is duplicated in the 'deps' attribute of rule 'image_cropping_calculator'". Please double check if you deleted [line 359](https://github.com/google/mediapipe/blob/9437483827ca26bb41949cba5c9477f604c0a6fb/mediapipe/calculators/image/BUILD#L359) and added "//mediapipe/gpu:gpu_buffer" to [line 365](https://github.com/google/mediapipe/blob/9437483827ca26bb41949cba5c9477f604c0a6fb/mediapipe/calculators/image/BUILD#L365).

INFO: From Compiling mediapipe/calculators/util/annotation_overlay_calculator.cc:
mediapipe/calculators/util/annotation_overlay_calculator.cc: In static member function 'static mediapipe::Status mediapipe::AnnotationOverlayCalculator::GetContract(mediapipe::CalculatorContract*)':
mediapipe/calculators/util/annotation_overlay_calculator.cc:185:7: warning: variable 'num_render_streams' set but not used [-Wunused-but-set-variable]
   int num_render_streams = cc->Inputs().NumEntries();
       ^~~~~~~~~~~~~~~~~~
INFO: From Compiling external/org_tensorflow/tensorflow/lite/minimal_logging_default.cc:
external/org_tensorflow/tensorflow/lite/minimal_logging_default.cc:26:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push

external/org_tensorflow/tensorflow/lite/minimal_logging_default.cc:27:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wformat-nonliteral"

external/org_tensorflow/tensorflow/lite/minimal_logging_default.cc:29:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop

cc1plus: warning: unrecognized command line option '-Wno-extern-c-compat'
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu up-to-date:
  bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu
INFO: Elapsed time: 474.191s, Critical Path: 227.69s
INFO: 394 processes: 394 processwrapper-sandbox.
INFO: Build completed successfully, 396 total actions


This is the output, the program did not run. What should I do to see the output?

**Comment by jiuqiant** [comment]
It shows that build process is completed successfully. Then, please follow [the instruction](https://github.com/google/mediapipe/blob/9437483827ca26bb41949cba5c9477f604c0a6fb/mediapipe/docs/hand_tracking_desktop.md#tensorflow-lite-hand-tracking-demo-with-webcam-cpu) to **run** the binary:
```
$ GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu \
    --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt
```

**Comment by all3naby** [comment]
> It shows that build process is completed successfully. Then, please follow [the instruction](https://github.com/google/mediapipe/blob/9437483827ca26bb41949cba5c9477f604c0a6fb/mediapipe/docs/hand_tracking_desktop.md#tensorflow-lite-hand-tracking-demo-with-webcam-cpu) to **run** the binary:
> 
> ```
> $ GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu \
>     --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt
> ```

I1124 23:05:58.518589  6394 demo_run_graph_main.cc:52] Initialize the calculator graph.
I1124 23:05:58.526885  6394 demo_run_graph_main.cc:56] Initialize the camera or load the video.
[ WARN:0] global /tmp/build_opencv/opencv/modules/videoio/src/cap_v4l.cpp (807) open VIDEOIO ERROR: V4L: can't open camera by index 0
E1124 23:05:58.557898  6394 demo_run_graph_main.cc:141] Failed to run the graph: ; capture.isOpened()(mediapipe/examples/desktop/demo_run_graph_main.cc:64)
This is the  result.

**Comment by jiuqiant** [comment]
WSL doesn't support opencv with webcam. Please follow [the TFlite Hand Tracking instruction](https://github.com/google/mediapipe/blob/446d7cf6b6aac5f25c0e8aa549aa2f592ae3d027/mediapipe/examples/desktop/README.md#L61) to run the demo on a video file instead.

**Comment by all3naby** [comment]
How can I use this hand tracking code as a module for my python program?

**Comment by jiuqiant** [comment]
Unfortunately, we currently don't prvoide python interface for hand tracking. If you want to achieve this, please take a look at [our media sequence python examples](https://github.com/google/mediapipe/tree/446d7cf6b6aac5f25c0e8aa549aa2f592ae3d027/mediapipe/examples/desktop/media_sequence) to make one for hand tracking for yourself.

**Comment by all3naby** [comment]
Will I have to train any data to get the result?

**Comment by all3naby** [comment]
@DESKTOP-FM98REJ:~/mediapipe$ python -m mediapipe.examples.desktop.media_sequence.charades_dataset \
>   --alsologtostderr \
>   --path_to_charades_data=/tmp/charades_data/ \
>   --path_to_mediapipe_binary=bazel-bin/mediapipe/examples/desktop/\
> media_sequence/media_sequence_demo  \
>   --path_to_graph_directory=mediapipe/graphs/media_sequence/
I1125 10:03:19.814534 140057281431360 charades_dataset.py:265] Downloading data.
I1125 10:03:19.815454 140057281431360 charades_dataset.py:333] Creating data directory.
I1125 10:03:19.816649 140057281431360 charades_dataset.py:335] Downloading license.
I1125 10:03:19.817559 140057281431360 charades_dataset.py:340] Downloading annotations.
I1125 10:03:19.818321 140057281431360 charades_dataset.py:345] Downloading videos.
I1125 10:03:19.819063 140057281431360 charades_dataset.py:350] Extracting annotations.
I1125 10:03:19.819901 140057281431360 charades_dataset.py:356] Extracting videos.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/allen/mediapipe/mediapipe/examples/desktop/media_sequence/charades_dataset.py", line 516, in <module>
    app.run(main)
  File "/home/allen/.local/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/allen/.local/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/allen/mediapipe/mediapipe/examples/desktop/media_sequence/charades_dataset.py", line 504, in main
    flags.FLAGS.path_to_graph_directory)
  File "/home/allen/mediapipe/mediapipe/examples/desktop/media_sequence/charades_dataset.py", line 266, in generate_examples
    annotation_dir, video_dir = self._download_data()
  File "/home/allen/mediapipe/mediapipe/examples/desktop/media_sequence/charades_dataset.py", line 359, in _download_data
    with zipfile.ZipFile(local_videos_path) as videos_zip:
  File "/usr/lib/python2.7/zipfile.py", line 793, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 834, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

What does this mean?

**Comment by jiuqiant** [comment]
We are closing this issue because the original issue (Mediapipe Handtracking not working Desktop WSL) is already solved.
