### ISSUE TITLE
Render the landmarks myself, do not render them in pixelBuffer from output.

### ISSUE THREAD

**Issue by sek790c** [google/mediapipe#2610]
I am working on handtrack for iOS . I get landmarks from output and render them by unity 3d, and I also want to render the camera view by [MPPLayerRenderer renderPixelBuffer:pixelBuffer];
But pixelBuffer above already contains landmarks detected. Is there a way to throw it away and just show the origin frame  from camera?

**Comment by sgowroji** [comment]
Hi @sek790c, Could you please share your code changes to investigate further. Thanks!
