### ISSUE TITLE
Javascript API for Iris Depth Tracking

### ISSUE THREAD

**Issue by mysticidiot** [google/mediapipe#2612]
I'm working on a web application which requires the user to sit at a certain distance away from the camera. 

Does an API for Iris depth tracking exist or is in the works?

**Comment by sgowroji** [comment]
Hi @mysticidiot, Present we don't have any javascript API solutions for IRIS Depth tracking. But you can  have a look at our 
[Visualizer](https://google.github.io/mediapipe/solutions/iris.html#web) in Web for the same.

**Comment by mysticidiot** [comment]
Okay thanks for the response.
