### ISSUE TITLE
Deploying MediaPipe for scalability

### ISSUE THREAD

**Issue by command0r** [google/mediapipe#2613]
I believe this is an Architecture and design type of question, and I was unable to find a respective category and any documentation as to how the solution can be scaled to sustain the load. I take it MediaPipe can be deployed as a Docker container, which is good. However, unless the app that does the processing is deployed to the same or another container beside it, it would require another approach to call MediaPipe's APIs.
If I'm to use MediaPipe in Python, I may want to wrap the internal APIs into the REST services with either Django or Flask, so they can be called by the backend services that implement the logic for processing. So far, so good?
Now, once I'm interested in "Pose estimation" as such and I need the MediaPipe to process the video files (and this type of processing is quite resource-demanding in nature, especially when it comes to CPU time), I need to figure the right deployment Architecture that would be scalable at the same time. I thought of deploying the MediaPipe's Docker container and the backend services (that implement RESTful APIs) in a GKE cluster, so the containers can scale depending on the CPU/Memory consumption. Furthermore, the GKE cluster would sit behind the load balancer and queuing service/message bus to ensure reliability and guarantee that no files would be lost along the way. Is this the right approach?
Also, in order to enhance the solution and improve the processing time, I wonder where the right place for the GPU-powered VM's in this kind of scheme is?
Please advice.

**Comment by sgowroji** [comment]
Hi @command0r, Could you please share us the observation of what have you tried in deploying MediaPipe pose estimation solution  and what performance errors have you faced in doing it with Python platform. Thanks!

**Comment by command0r** [comment]
Any news on this, guys?

**Comment by kuaashish** [comment]
Hello @command0r,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
