### ISSUE TITLE
Internal loop timestamps break filtering inside loop

### ISSUE THREAD

**Issue by DeanIsMe** [google/mediapipe#2615]
**Problem**
The [`BeginLoopCalculator`](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/begin_loop_calculator.h) makes its own timestamp for items within the loop, which is completely divorced from the actual timestamps that it receives.

```
  // Fake timestamps generated per element in collection.
  Timestamp loop_internal_timestamp_ = Timestamp(0);
```
Other calculators use `cc->InputTimestamp()` to determine how much time has passed since previous packets, such as `mediapipe\util\filtering\one_euro_filter.cc` and `mediapipe\util\filtering\relative_velocity_filter.cc`.
If any of these calculators are used within a loop, they will not work as intended because the `cc->InputTimestamp()` call will read the fake timestamp generated by `BeginLoopCalculator`.

**My proposed solution**
I've solved this problem for my solution by making `loop_internal_timestamp_` jump up to the value of `cc->InputTimestamp()` in the `Process()` call of `BeginLoopCalculator`. The change is an addition of 1 line.

mediapipe\lounge\calculators\lounge_begin_loop_calculator.h:
```
  absl::Status Process(CalculatorContext* cc) final {
++    loop_internal_timestamp_ = std::max(cc->InputTimestamp(), loop_internal_timestamp_);
    Timestamp last_timestamp = loop_internal_timestamp_;
```
This solution could stretch out the timestamps undesirably if a system is able to process an average of more than 1 loop per microsecond, but I think that's very unlikely.

**Side note**
I know that implementing stateful filters within a loop can be problematic because we then need a separate state for each item in the loop, but that's a separate issue.

**Comment by kuaashish** [comment]
Hello @DeanIsMe,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
