### ISSUE TITLE
Full Range object detection model output

### ISSUE THREAD

**Issue by fortminors** [google/mediapipe#2617]
**System information** (Please provide as much relevant information as possible)
- Solution: FaceDetection
- Programming Language: C++, Python

**Describe the expected behavior:**

Hello! I am trying to understand the output of the Full Range face detector model. There are two outputs:

**reshaped_regressor_face_4** of shape [1,2304,16]
and
**reshaped_classifier_face_4** of shape [1,2304,1]

What do these shapes and values represent? I checked the model card and it states: `Tensor of predicted embeddings representing anchors transformation which are further used in Non Maximum Suppression algorithm.` What are anchors transformation in this case? And how should it be used in NMS algorithm? Are there examples of these? Thanks!

**Comment by sgowroji** [comment]
Hi @fortminors, Thank you for reaching us for the above query. Did you get a chance to go through our [documentation](https://google.github.io/mediapipe/solutions/models.html#face-detection).
