### ISSUE TITLE
Disable face model into holistic solution

### ISSUE THREAD

**Issue by ThiruSS** [google/mediapipe#2618]
I use mediapipe within a web page, but I only need the kps of the body and hands, so I don't need the overhead of using the face model.
Is there a way to disable the face model in the Javascript solution. Or would it be possible for the development team to consider introducing that option when using the holistic solution?
Thank you very much.

**Comment by sgowroji** [comment]
Hi @ThiruSS,  If you are looking for javascript can you go through it https://github.com/google/mediapipe/issues/2028#issuecomment-888703030

**Comment by ctcx** [comment]
useful
