### ISSUE TITLE
Latest version does not build on Windows

### ISSUE THREAD

**Issue by mysticidiot** [google/mediapipe#2619]
When I run -
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Users\admin\AppData\Local\Programs\Python\Python39\python.exe" mediapipe/
examples/desktop/hello_world

The following error is displayed -
.\mediapipe/framework/packet.h(452): error C2143: syntax error: missing ';' before '&&'
.\mediapipe/framework/packet.h(452): error C2143: syntax error: missing '>' before ';'
.\mediapipe/framework/packet.h(452): note: see reference to class template instantiation 'mediapipe::packet_internal::is_concrete_proto_t<T>' being compiled
.\mediapipe/framework/packet.h(452): error C2143: syntax error: missing ',' before ';'
.\mediapipe/framework/packet.h(452): error C2143: syntax error: missing ';' before '}'

Its caused due to the following lines in packet.h -
struct is_concrete_proto_t
    : public std::integral_constant<
          bool, std::is_base_of<proto_ns::MessageLite, T>{} &&
                    !std::is_same<proto_ns::MessageLite, T>{} &&
                    !std::is_same<proto_ns::Message, T>{}> {};

In an already closed <a href = "https://github.com/google/mediapipe/issues/908">issue</a> I saw that this is not an issue in Linux but only in Windows MSVC. They suggested to downgrade the version of mediapipe to 0.75 but this was about a year ago.

Is there a fix for this? Since v0.75 doesn't have the latest solutions.

I'm using bazel version 4.2.1 and python version 3.9.7

![image](https://user-images.githubusercontent.com/69745268/135669489-8035fef4-3eaf-4304-a39a-33fe4fd59274.png)

**Comment by jiuqiant** [comment]
The [issue](https://github.com/google/mediapipe/issues/908) you mentioned is solved as https://github.com/google/mediapipe/issues/975#issuecomment-706467559. I built the packet library (bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 framework:packet) with the latest version and it works well on my end:

<img width="370" alt="Untitled" src="https://user-images.githubusercontent.com/3359144/135763994-8cfb5613-35c6-4d40-b1dd-d6ebd9ff37a0.png">

Can this caused by the MSVC version you use?

**Comment by mysticidiot** [comment]
Yeah I think the MSVC version is causing the issue. I can't install VS 19 on my laptop so used VS 17. The official Bazel doc specified any version of VS was fine. Is there a way of running the latest build using VS 17?

**Comment by mysticidiot** [comment]
I figured out a way to install VS 19 so the issue was resolved.
