### ISSUE TITLE
Accessing confidence scores of each landmark in hand tracking

### ISSUE THREAD

**Issue by JECBello** [google/mediapipe#262]
I was wondering, does each landmark from the hand tracking example come with a confidence score? If so, would it be possible to extract those confidence scores somehow?

**Comment by mgyong** [comment]
@fanzhanggoogle Pls correct me if i am mistaken.
The landmark model does not output any confidence scores for 21 landmarks.

**Comment by eknight7** [comment]
Yes, there is no confidence score. See the definition of `NormalizedLandmark` in https://github.com/google/mediapipe/blob/master/mediapipe/framework/formats/landmark.proto
