### ISSUE TITLE
pose elevaçao lateral

### ISSUE THREAD

**Issue by glaucia-desing** [google/mediapipe#2620]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):
- Programming Language and version ( e.g. C++, Python, Java):

**Describe the expected behavior:**

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by glaucia-desing** [comment]
![2021-09-24 (2)imagem](https://user-images.githubusercontent.com/56209111/135693645-32a1ba09-c53e-4d2a-b927-6b56b13e9061.png)
![Uploading elevaçao lateral.gif…]()

**Comment by glaucia-desing** [comment]
![Uploading elevaçao lateral.gif…]()

**Comment by sgowroji** [comment]
Hi @glaucia-desing, Could you please elaborate your use case with complete details. Thanks!
