### ISSUE TITLE
How can I get hips offset when using pose_world_landmarks of Pose Solution

### ISSUE THREAD

**Issue by ludidilu** [google/mediapipe#2623]
Hi,

POSE_WORLD_LANDMARKS
x, y and z: Real-world 3D coordinates in meters with the origin at the center between hips.

How can I get hips offset when using pose_world_landmarks of Pose Solution?

**Comment by sgowroji** [comment]
Hi @ludidilu, Could you please elaborate your query with more details. Thanks!
