### ISSUE TITLE
Get the problem: "Failed to set mediaType (stream 0, (0x0 @ 1) MFVideoFormat_RGB32(unsupported media type)" with iris_tacking on windows

### ISSUE THREAD

**Issue by Victoria-1** [google/mediapipe#2626]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

Environment: win8+opencv3.4.10+vs2015

I have run iris_depth_from_image_desktop successfully,here is the result:
D:\mediaPipe\mediapipe-master>bazel-bin\mediapipe\examples\desktop\iris_tracking\iris_depth_from_image_desktop --input_image_path=C:\Users\melomonkey\Desktop\iris_test.jpg --output_image_path=C:\Users\melomonkey\Desktop\result.jpg
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Left Iris Depth: 92 cm.
Right Iris Depth: 90 cm.

But when i try to use video file as input, I get such problem:
D:\mediaPipe\mediapipe-master>bazel-bin\mediapipe\examples\desktop\iris_tracking\iris_tracking_cpu_video_input --calculator_graph_config_file=mediapipe\graphs\iris_tracking\iris_tracking_cpu_video_input.pbtxt 
--input_side_packets=input_video_path=D:\mediaPipe\mediapipe-master\test_video\iris_test_video.mp4,
output_video_path=D:\mediaPipe\mediapipe-master\result_video\iris_result_video.mp4
[ WARN:0] Failed to set mediaType (stream 0, (0x0 @ 1) MFVideoFormat_RGB32(unsupported media type)
E20211004 11:30:15.135386  5500 simple_run_graph_main.cc:149] Failed to run the graph: CalculatorGraph::Run() failed in Run:
Calculator::Open() for node "OpenCvVideoDecoderCalculator" failed: ; Fail to read any frames from the video file at D:\mediaPipe\mediapipe-master\test_video\iris_test_video.mp4

It seems something wrong with opencv to read video, any ideas? Thanks!

**Comment by sgowroji** [comment]
Hi @Victoria-1, I think its unable to read a frame from the test video used in the above and returns [empty](https://github.com/google/mediapipe/blob/b899d17f185f6bcbf3f5947d3e134f8ce1e69407/mediapipe/calculators/video/opencv_video_decoder_calculator.cc#:~:text=//%20Unfortunately%2C%20cap_-%3Eget,%7D) when trying to read the first frame of the video.  Is it with only one video or same with other videos ?

**Comment by Victoria-1** [comment]
I have tried at least 3 videos and get the same problem. I take the video with mobile phone, it will be a matter?  Because there is a confusing thing, when i run "iris_depth_from_image_desktop", the test image i use is also from mobile phone, but some images (from different mobile phones) do not work. It is related to exif info, i wonder what kind of exif info must be included in the image?  And is there any restriction of the video?

**Comment by sgowroji** [comment]
It works on single image as mentioned here https://google.github.io/mediapipe/solutions/iris.html#single-image-depth-estimation.

**Comment by yanxky** [comment]
I‘m faced with the same situation with Victoria-1: I can run the program with the input from my camera or single images, but when I run it with a video, it just return "[ WARN:0] Failed to set mediaType (stream 0, (0x0 @ 1) MFVideoFormat_RGB32(unsupported media type)
E20220322 14:06:07.629348 22252 simple_run_graph_main.cc:149] Failed to run the graph: CalculatorGraph::Run() failed in Run:
Calculator::Open() for node "OpenCvVideoDecoderCalculator" failed: ; Fail to read any frames from the video file at video/input.mp4".

**Comment by darkzbaron** [comment]
Same here!
