### ISSUE TITLE
Object detection and tracking on Desktop

### ISSUE THREAD

**Issue by edgar-bcn** [google/mediapipe#2627]
Hi,

First of all I would like to thank you for sharing such a cool solution as MediaPipe.

I'm struggling with a number of practical issues, and need some hints to go on.

Currently I've successfully built your Object Detection and Tracking solution for Desktop following the instructions [here](https://google.github.io/mediapipe/solutions/object_detection).

Problem is when I run the application it goes mad, detecting and tracking non existing objects.

During the building process I got some warning messages regarding repository import skipping, but it completed successfully.

I also got an error while trying to load canberra-gtk-module when running the application, but after some googling it seems doesn't matter.

Could you please help me?

Thanks in advance,
Edgar

**System information**
- OS Platform and Distribution: Ubuntu 20.04.3 LTS
- MediaPipe version: 0.8.7
- Bazel version: 3.7.2
- Solution: Object Detection + Box Tracking
- Programming Language and version: C++

**Other info / Complete Logs :**
[log.txt](https://github.com/google/mediapipe/files/7276779/log.txt)

**Comment by sgowroji** [comment]
Hi @edgar-bcn, Could you please share a recording video or  screenshot to illustrate the problem you're facing.

**Comment by edgar-bcn** [comment]
> Hi @edgar-bcn, Could you please share a recording video or screenshot to illustrate the problem you're facing.

Attached you'll find the recording video.

I have built the solution with the following command:

**bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/object_tracking:object_tracking_cpu**

And running it with this one:

**GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/object_tracking/object_tracking_cpu \
  --calculator_graph_config_file=mediapipe/graphs/tracking/object_detection_tracking_desktop_live.pbtxt**

Thank you for your support.

Regards,
Edga

https://user-images.githubusercontent.com/65038470/136002293-6c8d30ce-42a5-483c-bf1e-409f31b979ec.mp4

r

**Comment by edgar-bcn** [comment]
@sgowroji Is there any workaround to try while waiting  for support answer?

**Comment by edgar-bcn** [comment]
Simply adding a FlowLimiterCalculator node at the very beginning of object_detection_cpu.pbtxt (like on non-tracking version of Object detection) it works.

I'm newie on MediaPipe (and ML in general) so don't know if this the right solution.

**Comment by sureshdagooglecom** [comment]
Hi @edgar-bcn ,
This is issue can be resolved in the latest version of MediaPipe , could you please check and close this issue.
