### ISSUE TITLE
Face_landmark tflite model inference in TensorRT on Jetson nano 

### ISSUE THREAD

**Issue by Ram-Godavarthi** [google/mediapipe#2628]
Hello,

I am using face_landmark model with 468 features for face recognition. 
I could able to port it to TensorRT 8 (tested with ./trtexce command) and it works there without any errors.

But, I would like to do it in TensorRT 6. Is there a possibility / anyone has done it in TensorRT 6 successfully ??
Thanks in advance.

**Comment by sgowroji** [comment]
Hi @Ram-Godavarthi, Thank you for sharing your observation on TensorRT 8.  What is the problem are you seeing while trying to do it on TensorRT 6. And please share your steps of reproduction. Thanks!

**Comment by Ram-Godavarthi** [comment]
Hi @sgowroji ,
thanks for getting back so quickly.
I have written a plugin for RELU layer by referring this [repo](https://github.com/nwesem/mtcnn_facenet_cpp_tensorRT)

I get this error when I try to build an engine.

PARSER CREATED
----------------------------------------------------------------
Input filename:   ../facenetModels/facenet_468_mediapipe.onnx
ONNX IR version:  0.0.4
Opset version:    9
Producer name:    tf2onnx
Producer version: 1.9.2
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).
While parsing node number 1 [Conv]:
ERROR: ModelImporter.cpp:296 In function importModel:
[5] Assertion failed: tensors.count(input_name)
parsing failed:

**Comment by kuaashish** [comment]
Hello @Ram-Godavarthi,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
