### ISSUE TITLE
hello_world build did NOT complete successfully

### ISSUE THREAD

**Issue by WilhelmIllust** [google/mediapipe#263]
This is what I do:
```bazel run --define MEDIAPIPE_DISABLE_GPU=1     mediapipe/examples/desktop/hello_world:hello_world --sandbox_debug        ```
and this is what I got:

 INFO: Writing tracer profile to '/home/<username>/.cache/bazel/_bazel_billy/a0afdf9d2053f98551204973a6293a8b/command.profile.gz'
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/a5f9bcd64453ff3d1f64cb4da4786db3d2da7f82.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "0a00e0f5d9adc22661caea5c5e44e4f63aa251acbc0b13d10a74cf9883e6e97c"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/<username>/.cache/bazel/_bazel_billy/a0afdf9d2053f98551204973a6293a8b/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /mnt/c/Users/shenw/mediapipe/WORKSPACE:28:1
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/<username>/.cache/bazel/_bazel_billy/a0afdf9d2053f98551204973a6293a8b/external/com_google_protobuf/BUILD:106:1: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1) process-wrapper failed: error executing command
  (cd /home/<username>/.cache/bazel/_bazel_billy/a0afdf9d2053f98551204973a6293a8b/sandbox/processwrapper-sandbox/310/execroot/mediapipe && \
  exec env - \
    PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/ProgramData/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Intel/iCLS Client/:/mnt/c/Program Files/Intel/iCLS Client/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files/Microsoft SQL Server/110/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/:/mnt/c/Program Files/Microsoft/Web Platform Installer/:/mnt/c/Program Files (x86)/Microsoft ASP.NET/ASP.NET Web Pages/v1.0/:/mnt/c/Program Files/Java/jdk1.8.0_121/bin:/mnt/c/Program Files/Java/jdk1.8.0_131/bin:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/d/Program Files/Git/cmd:/mnt/c/platform-tools:/mnt/c/Users/shenw/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/shenw/AppData/Local/GitHubDesktop/bin:/%USERPROFILE%/AppData/Local/Microsoft/WindowsApps' \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /home/<username>/.cache/bazel/_bazel_billy/install/0eaad79e03c843a15f078930a471406a/_embedded_binaries/process-wrapper '--timeout=0' '--kill_delay=15' /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_objs/protobuf_lite/strutil.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_objs/protobuf_lite/strutil.pic.o' -fPIC -iquote external/com_google_protobuf -iquote bazel-out/k8-fastbuild/bin/external/com_google_protobuf -isystem external/com_google_protobuf/src -isystem bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src -Wno-sign-compare -Wno-unused-function -Wno-uninitialized -Wno-unused-result -Wno-comment -Wno-return-type -Wno-unused-local-typedefs -Wno-ignored-attributes '-std=c++14' -DHAVE_PTHREAD -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-write-strings -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/stubs/strutil.cc -o bazel-out/k8-fastbuild/bin/external/com_google_protobuf/_objs/protobuf_lite/strutil.pic.o)
gcc: error: unrecognized command line option '-std=c++14'
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 28.271s, Critical Path: 27.42s
INFO: 49 processes: 49 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by jiuqiant** [comment]
Hi, It's likely to be a temporary network problem because the actual error is  "class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found". See the similar issues: https://github.com/google/mediapipe/issues/153, https://github.com/google/mediapipe/issues/19, and https://github.com/google/mediapipe/issues/3.  

The best solution is to retry the build command later. However, if you are blocked by a firewall, you may want to use VPN.
