### ISSUE TITLE
Webcam Access Being Requested When Not Using

### ISSUE THREAD

**Issue by JelaniThompson** [google/mediapipe#2633]
Hello there,

I'm working on a project with selfie segmentation and loving the performance so far. I'm making a background/foreground subtraction project and I've run into a bit of an issue. The browser I'm currently using doesn't have webcam access and I'm running the background subtraction on MP4 videos. It works great when I'm able to allow webcam access, but I have no idea why it's being requested in the first place. 

Here's my code: [https://gist.github.com/JelaniThompson/fe18bb5b431ec0815b8b136cd309591a](https://gist.github.com/JelaniThompson/fe18bb5b431ec0815b8b136cd309591a)

Would any of you guys happen to know how to prevent webcam access being asked for in my example? I'd like it to default to not asking and only trigger if I choose to toggle the mode to webcam view.

**Comment by sureshdagooglecom** [comment]
Hi @JelaniThompson ,
Are you still looking for the resolution on this issue.
