### ISSUE TITLE
Medipipe objectron js not returned properties

### ISSUE THREAD

**Issue by dikiy007** [google/mediapipe#2637]
Good afternoon, could you help me, I have one problem in your documentation it says that api returns the following properties: 
landmarks_2d, landmarks_3d , rotation, translation, scale 

https://google.github.io/mediapipe/solutions/objectron.html#output

Programming language : typescript

But some of the parameters are not returned to me. That are: rotation , translation , scale

![image](https://user-images.githubusercontent.com/44896236/136392719-de4cc9ef-d208-41ca-bcf0-2a93c5d766a9.png)

Please help me resolve this problem. Thanks

**Comment by ayushgdev** [comment]
Hello @dikiy007 
Are you still looking for a resolution? We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
