### ISSUE TITLE
Fail to build Android Example App

### ISSUE THREAD

**Issue by Hank-MIA** [google/mediapipe#2638]
Hello, this is probably stupid, I googled the error but couldn't find anything.
**System information**
 - OS Platform and Distribution : Linux Ubuntu 20.04 LTS
 - MediaPipe version : v0.8.7.1
 - Bazel version: 3.7.2
 - Android SDK and NDK versions : Android 10, NDK 21.4.7075529
 - OpenCV version : 4.2

**Describe the problem**
I'm following the instruction to build an android example app:
https://google.github.io/mediapipe/getting_started/android.html

All previous steps worked fine, but this gave me error:
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

**Complete Logs**
Starting local Bazel server and connecting to it...
DEBUG: /home/zh/.cache/bazel/_bazel_zh/ade7adc40316010507b8acbef44c6dff/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/zh/.cache/bazel/_bazel_zh/ade7adc40316010507b8acbef44c6dff/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/zh/.cache/bazel/_bazel_zh/ade7adc40316010507b8acbef44c6dff/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/zh/.cache/bazel/_bazel_zh/ade7adc40316010507b8acbef44c6dff/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/zh/.cache/bazel/_bazel_zh/ade7adc40316010507b8acbef44c6dff/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/zh/.cache/bazel/_bazel_zh/ade7adc40316010507b8acbef44c6dff/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/zh/.cache/bazel/_bazel_zh/ade7adc40316010507b8acbef44c6dff/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/zh/.cache/bazel/_bazel_zh/ade7adc40316010507b8acbef44c6dff/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /home/zh/.cache/bazel/_bazel_zh/ade7adc40316010507b8acbef44c6dff/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (176 packages loaded, 17074 targets configured).
INFO: Found 1 target...
INFO: From Compiling mediapipe/framework/calculator.pb.cc [for host]:
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc: In member function 'virtual google::protobuf::uint8* mediapipe::ProfilerConfig::_InternalSerialize(google::protobuf::uint8*, google::protobuf::io::EpsCopyOutputStream*) const':
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:1734:41: warning: 'bool mediapipe::ProfilerConfig::enable_input_output_latency() const' is deprecated [-Wdeprecated-declarations]
 1734 |   if (this->enable_input_output_latency() != 0) {
      |                                         ^
In file included from bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/mediapipe/framework/calculator.pb.h:2778:13: note: declared here
 2778 | inline bool ProfilerConfig::enable_input_output_latency() const {
      |             ^~~~~~~~~~~~~~
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:1801:39: warning: 'bool mediapipe::ProfilerConfig::trace_log_duration_events() const' is deprecated [-Wdeprecated-declarations]
 1801 |   if (this->trace_log_duration_events() != 0) {
      |                                       ^
In file included from bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/mediapipe/framework/calculator.pb.h:3045:13: note: declared here
 3045 | inline bool ProfilerConfig::trace_log_duration_events() const {
      |             ^~~~~~~~~~~~~~
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc: In member function 'virtual size_t mediapipe::ProfilerConfig::ByteSizeLong() const':
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:1900:41: warning: 'bool mediapipe::ProfilerConfig::enable_input_output_latency() const' is deprecated [-Wdeprecated-declarations]
 1900 |   if (this->enable_input_output_latency() != 0) {
      |                                         ^
In file included from bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/mediapipe/framework/calculator.pb.h:2778:13: note: declared here
 2778 | inline bool ProfilerConfig::enable_input_output_latency() const {
      |             ^~~~~~~~~~~~~~
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:1955:39: warning: 'bool mediapipe::ProfilerConfig::trace_log_duration_events() const' is deprecated [-Wdeprecated-declarations]
 1955 |   if (this->trace_log_duration_events() != 0) {
      |                                       ^
In file included from bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/mediapipe/framework/calculator.pb.h:3045:13: note: declared here
 3045 | inline bool ProfilerConfig::trace_log_duration_events() const {
      |             ^~~~~~~~~~~~~~
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc: In member function 'void mediapipe::ProfilerConfig::MergeFrom(const mediapipe::ProfilerConfig&)':
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:2020:40: warning: 'bool mediapipe::ProfilerConfig::enable_input_output_latency() const' is deprecated [-Wdeprecated-declarations]
 2020 |   if (from.enable_input_output_latency() != 0) {
      |                                        ^
In file included from bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/mediapipe/framework/calculator.pb.h:2778:13: note: declared here
 2778 | inline bool ProfilerConfig::enable_input_output_latency() const {
      |             ^~~~~~~~~~~~~~
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:2047:38: warning: 'bool mediapipe::ProfilerConfig::trace_log_duration_events() const' is deprecated [-Wdeprecated-declarations]
 2047 |   if (from.trace_log_duration_events() != 0) {
      |                                      ^
In file included from bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/mediapipe/framework/calculator.pb.h:3045:13: note: declared here
 3045 | inline bool ProfilerConfig::trace_log_duration_events() const {
      |             ^~~~~~~~~~~~~~
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc: In member function 'virtual google::protobuf::uint8* mediapipe::CalculatorGraphConfig_Node::_InternalSerialize(google::protobuf::uint8*, google::protobuf::io::EpsCopyOutputStream*) const':
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:2634:33: warning: 'bool mediapipe::CalculatorGraphConfig_Node::has_profiler_config() const' is deprecated [-Wdeprecated-declarations]
 2634 |   if (this->has_profiler_config()) {
      |                                 ^
In file included from bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/mediapipe/framework/calculator.pb.h:3959:13: note: declared here
 3959 | inline bool CalculatorGraphConfig_Node::has_profiler_config() const {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc: In member function 'virtual size_t mediapipe::CalculatorGraphConfig_Node::ByteSizeLong() const':
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:2788:33: warning: 'bool mediapipe::CalculatorGraphConfig_Node::has_profiler_config() const' is deprecated [-Wdeprecated-declarations]
 2788 |   if (this->has_profiler_config()) {
      |                                 ^
In file included from bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/mediapipe/framework/calculator.pb.h:3959:13: note: declared here
 3959 | inline bool CalculatorGraphConfig_Node::has_profiler_config() const {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc: In member function 'void mediapipe::CalculatorGraphConfig_Node::MergeFrom(const mediapipe::CalculatorGraphConfig_Node&)':
bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:2875:32: warning: 'bool mediapipe::CalculatorGraphConfig_Node::has_profiler_config() const' is deprecated [-Wdeprecated-declarations]
 2875 |   if (from.has_profiler_config()) {
      |                                ^
In file included from bazel-out/host/bin/mediapipe/framework/calculator.pb.cc:4:
bazel-out/host/bin/mediapipe/framework/calculator.pb.h:3959:13: note: declared here
 3959 | inline bool CalculatorGraphConfig_Node::has_profiler_config() const {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
**ERROR**: /home/zh/.cache/bazel/_bazel_zh/ade7adc40316010507b8acbef44c6dff/external/org_tensorflow/tensorflow/core/util/BUILD:374:24: error executing shell command: '/bin/bash -c bazel-out/android-arm64-v8a-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}  external/local...' failed (Exit 127): bash failed: error executing command /bin/bash -c 'bazel-out/android-arm64-v8a-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c 'bazel-out/android-arm64-v8a-opt-ST-e0f78fafe98f/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/env: 'python': No such file or directory
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 24.971s, Critical Path: 14.63s
INFO: 201 processes: 140 internal, 61 linux-sandbox.
FAILED: Build did NOT complete successfully

Any help is appreciated!

**Comment by sgowroji** [comment]
Hi @Hank-MIA, Can you try the workaround mentioned in this https://github.com/google/mediapipe/issues/2284
