### ISSUE TITLE
Mediapipe's calculator in Python for signal processing

### ISSUE THREAD

**Issue by KrzysiekBrzostowski** [google/mediapipe#2641]
Hello,

I am new to Mediapipe. I would like to ask you that it is possible to process audio signals in Mediapipe based on Python?
I found this
https://github.com/google/mediapipe/tree/master/mediapipe/util/filtering
an example of low-pass filter in .cc file. How can I build a Calculator in Python which will be ready to use in the Mediapipe framework? 

I would appreciate a minimum working example.

**Comment by jiuqiant** [comment]
> Hi, Mediapipe's calculator can be written, for example, in C++. Is it possible to write Mediapipe's calculator in Python (with the use of Python's libraries)?

Unfortunately, writing MediaPipe calculators in other language than C++ is not currently supported.
