### ISSUE TITLE
Is npm mediapipe package open source?

### ISSUE THREAD

**Issue by longerking** [google/mediapipe#2649]
I am learning about the use of javascrpt in mediapipe, but I found that the npm package drawing_utils.js introduced in the case is through script cdn. I can’t find the corresponding source code description for drawing_utils.js  in the project. Is this part open source? Where can I find the corresponding description?

https://google.github.io/mediapipe/getting_started/javascript.html

**Comment by raphaelmenges** [comment]
I would highly welcome to open the source of these NPM packages! I am trying to run MediaPipe/FaceMesh within an Electron/Vite environment which might require certain adaptation in fetching any dependencies.

**Comment by legel** [comment]
This is an issue.  It seems like in order to achieve just basic customization of the drawing_utils.js, we will be required to reproduce everything from scratch.
