### ISSUE TITLE
mediapipe tflite model support multiple inputs? 

### ISSUE THREAD

**Issue by rzyangKyle** [google/mediapipe#265]

**Comment by rzyangKyle** [comment]
I want to test my asr model use TensorFlowInferenceCalculator
this my pbtxt:
  CalculatorGraphConfig graph_config =
      ::mediapipe::ParseTextProtoOrDie<CalculatorGraphConfig>(
          R"(
            input_stream: "A"
	    input_stream: "B"
            node {
              calculator: "TfLiteInferenceCalculator"
              input_stream: "TENSORS:A"
	      input_stream: "TENSORS:B"
              output_stream: "TENSORS:outputs"
              options {
                [mediapipe.TfLiteInferenceCalculatorOptions.ext] {
                  use_gpu: false
                  model_path: "mediapipe/calculators/tflite/testdata/****.tflite"
                }
              }
            }
          )");
this is error info :
F1121 14:47:34.620530 36866 calculator_graph.cc:123] Non-OK-status: Initialize(config) status: Unknown: ValidatedGraphConfig Initialization failed.
;
; tag "TENSORS" index 0 already had a name "decoder_inputs" but is being reassigned a name "joint_inputs"
For calculator:

Then I modify the pbtxt as follow:
  CalculatorGraphConfig graph_config =
      ::mediapipe::ParseTextProtoOrDie<CalculatorGraphConfig>(
          R"(
            input_stream: "A"
	    input_stream: "B"
            node {
              calculator: "TfLiteInferenceCalculator"
              input_stream: "TENSORS:0:A"
	      input_stream: "TENSORS:1:B"
              output_stream: "TENSORS:outputs"
              options {
                [mediapipe.TfLiteInferenceCalculatorOptions.ext] {
                  use_gpu: false
                  model_path: "mediapipe/calculators/tflite/testdata/****.tflite"
                }
              }
            }
          )");
But also has error，what should I do for mutiinputs for tflite model or pb model

**Comment by lcycoding** [comment]
Actually, the `TENSORS` tag accepts vector of tensor.
Why not try to modify some of the code, and parse out the tensor you needed separately?

**Comment by eknight7** [comment]
Do you have multiple input vectors of tensors?

**Comment by rzyangKyle** [comment]
I modify the  TfLiteConverterCalculator's code to generate input vectors of tensors  and solve it

**Comment by eknight7** [comment]
Okay, good to know things worked out. Closing the issue.

**Comment by srinivasnumburi** [comment]
Good Morning,
We are having similar problem of using multiple inputs in a TFLite model. 
@rzyangKyle -looks like you have solved this problem. Please can you share the details of the changes done in  TfLiteConverterCalculator. 
We are trying to use mediapipe to run TFLite model with multiple inputs and use SSBO. 
We are getting errors in binding multiple SSBO objects to Invoke method for TFLiteInference  in TfLiteConverterCalculator.
Btw were you able to run the model in GPU or CPU with multiple inputs.
