### ISSUE TITLE
Manipulating Stick Figure and access pose landmarks on Android

### ISSUE THREAD

**Issue by taatiq882** [google/mediapipe#2652]
Hello Guys, Excuse me if ask lame questions. I am pretty new to all this. I have got an android project which is using aar and pose. I want to manipulate the stick figure colors and points and furthermore, I want to show information real time based on the pose landmarks information. Can Anyone guide me where I can do that stuff ?

**Comment by taatiq882** [comment]
Actually. I want to display specific points for example I just want to display only the inner eye point. Furthermore, I want to change the color of the stick figure. Also want to calculate the head rotation angle. So for all these modification I want to know where the stick figure is printing and where I can access the pose landmarks so I could do calculations realtime. I would really appreciate if you could help me in this regard.

**Comment by vishal-bhosle** [comment]
@taatiq882 were you able to implement this?

**Comment by taatiq882** [comment]
Nop I couldn't. As I couldn't find any helping material.
