### ISSUE TITLE
Runtime Errors

### ISSUE THREAD

**Issue by 424778940z** [google/mediapipe#2653]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): `Ubuntu 20.04 LTS`
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): `GCC 9`
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): `C++ 17`
- Installed using virtualenv? pip? Conda? (if python): `N\A`
- [MediaPipe version](https://github.com/google/mediapipe/releases): `33d683c67100ef3db37d9752fcf65d30bea440c4`
- Bazel version: `3.7.2`
- XCode and Tulsi versions (if iOS): `N\A`
- Android SDK and NDK versions (if android): `N\A`
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): `N\A`
- OpenCV version (if running on desktop): `OpenCV 4.2`

**Describe the problem**:

Basically trying to make a library from MediaPipe. things in `MediaPipeLibrary.cpp` is the similar to `demo_run_graph.cc` but with a class. I also made a small program to to test the library.

Compile and link all passed, then included and linked to my cmake project, also compiles and links fine.
However, if I run it, it will fail at:
`config = mediapipe::ParseTextProtoOrDie<mediapipe::CalculatorGraphConfig>(calculator_graph_config_contents)`
With error:
`[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:309] Error parsing text-format mediapipe.CalculatorGraphConfig: 53:66: Could not find type "type.googleapis.com/mediapipe.FlowLimiterCalculatorOptions" stored in google.protobuf.Any.`

Bazel config:
```
cc_library(
    name = "MediaPipeLibrary_",
    srcs = [
        "MediaPipeLibrary.cpp",
        ],
    hdrs = [
        "pbtxt_defines.hpp",
        "MediaPipeLibrary.hpp",
        ],
    deps = [
        #main
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/formats:image_frame",
        "//mediapipe/framework/formats:image_frame_opencv",
        "//mediapipe/framework/port:file_helpers",
        "//mediapipe/framework/port:opencv_highgui",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:opencv_video",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
        "//mediapipe/gpu:gl_calculator_helper",
        "//mediapipe/gpu:gpu_buffer",
        "//mediapipe/gpu:gpu_shared_data_internal",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",

        #types
        "//mediapipe/framework/formats:landmark_registration",

        #model
        "//mediapipe/graphs/holistic_tracking:holistic_tracking_gpu_deps",
    ],
    copts = ["-DMEDIAPIPE_TREE",],
    alwayslink = True,
    linkstatic = True,
    features = ["fully_static_link"],
)
```
---
If I build the source in tree, I get following error when run it:
`
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/repeated_field.h:2421] CHECK failed: GetArenaNoVirtual() == other->GetArenaNoVirtual(): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GetArenaNoVirtual() == other->GetArenaNoVirtual():
`

Bazel config
```
cc_binary(
    name = "mediapipe_library_test",
    srcs = [
        "test.cc",
        ],
    deps = [
        ":mediapipelibrary_",
    ],
    linkstatic = True,
)
```
---
Seems to me the first issue is include related, the `FlowLimiterCalculatorOptions` is defined in `"mediapipe/calculators/core/flow_limiter_calculator.pb.h"`
And it is in the core part, and set to always link, how can it be missing?
Have no idea about the second one.

Did I missing anything?

**Comment by 424778940z** [comment]
> If I build the source in tree, I get following error when run it:
> `[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/repeated_field.h:2421] CHECK failed: GetArenaNoVirtual() == other->GetArenaNoVirtual(): terminate called after throwing an instance of 'google::protobuf::FatalException' what(): CHECK failed: GetArenaNoVirtual() == other->GetArenaNoVirtual():`

Just an update onthe in tree build issue.
After some dig around found the issue is caused by linker.
It was missing following symble.
It was an issue from Bazel config, that somehow decided not link those for me.
```
     3 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipe21registrati
     2 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipe21registrati
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipe8internalL20
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL34FieldDesc
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL34FieldDesc
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL40FieldDesc
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL34GraphTrac
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL34GraphTrac
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL40GraphTrac
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL71ThreadPoo
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL71ThreadPoo
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL77ThreadPoo
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL29ImageForm
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL29ImageForm
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL35ImageForm
     8 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL22kPlatform
    11 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL17kGpuShare
    11 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL24kGpuShare
     6 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL16kGpuExecu
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL43RenderAnn
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL43RenderAnn
     4 OBJECT  LOCAL  DEFAULT   17 _ZN9mediapipeL49RenderAnn
```

**Comment by ayushgdev** [comment]
Hello @424778940z 
We are revisiting older issues. Would you please confirm if you are still looking for a resolution?
