### ISSUE TITLE
Hand detection/tracking accuracy

### ISSUE THREAD

**Issue by RohitSingh1226** [google/mediapipe#2658]
**System information** (Please provide as much relevant information as possible)

I have written a custom code for mediapipe
Windows 10 
Laptop (i7-9th gen 16GB ram 1650 max-q)
Webcam: Intel realsense 415.
Python v3.7

Latest Mediapipe
Hands mediapipe solution
Running in Vs code.

**Describe the current behavior:**

In my custom mediapipe program, I have only allowed the program to detect the right hand using handedness. It works nicely until I hide my right hand behind my back and then it starts to detect the inverted left hand i.e when it is in normal rest position.
What could be the solution for this? Should I print out the **Score** with the label? 

**Also Is there a way to fixate on only one person amongst two-three people?** 

Overall the detection works as expected, but these cases have to be considered for my project. Please suggest a way to make it more accurate and to work for one hand amongst two-three people.

The video File attached below shows the problem which occurs occasionally 
Only the right hand should be detected, but it is not doing that.
Please suggest how do I make it more accurate.

https://user-images.githubusercontent.com/35935157/137078602-e8dcd807-67ab-47d5-814c-2658b190c5f6.mp4

**Comment by sgowroji** [comment]
Hi @RohitSingh1226, Could you please share your code changes to  investigate your issue. Thanks!

**Comment by RohitSingh1226** [comment]
Hi @sgowroji 

class HandDetector():
    def __init__(self, mode=False, maxHands=1, detectionCon=0.5, trackCon=0.5):
        self.mode = mode
        self.maxHands = maxHands
        self.detectionCon = detectionCon
        self.trackCon = trackCon
        self.rightHand = False

        self.mpHands = mp.solutions.hands
        self.hands = self.mpHands.Hands(self.mode, self.maxHands,
                                        self.detectionCon, self.trackCon)
        self.mpDraw = mp.solutions.drawing_utils

    def findHands(self, img, handNo=0, draw=False):

        lmList = []
        img.flags.writeable = False
        #imgRGB = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        self.results = self.hands.process(img)
        

        if self.results.multi_handedness:
            for hand_handedness in self.results.multi_handedness:
                handedness_dict = MessageToDict(hand_handedness)
                if handedness_dict['classification'][0]['label'] == "Left":
                    if self.results.multi_hand_landmarks:
                        myHand = self.results.multi_hand_landmarks[handNo]
                        for id, lm in enumerate(myHand.landmark):

                            h, w, c = img.shape
                            cx, cy = int(lm.x * w), int(lm.y * h)

                            lmList.append([id, cx, cy])
                            
                            if draw:
                                cv2.circle(img, (cx, cy), 5, (255, 0, 255), cv2.FILLED)
                        
                        if draw:
                            for handLms in self.results.multi_hand_landmarks:
                                self.mpDraw.draw_landmarks(img, handLms, self.mpHands.HAND_CONNECTIONS)

        return lmList
        
        
        This is for restricting the detection for the right hand

**Comment by RohitSingh1226** [comment]
@sgowroji any updates?

**Comment by sgowroji** [comment]
Hello, we are constantly improve our hand models by mining a new samples, where model tend to fail. And hopefully issue you are facing would be gone in a new release.

We tried many different approaches and see that even sometimes for some particular cases they could improve the model quality, they also can decrease model quality for other cases, so we try to handle issues via neural network itself and the dataset, and not by adding complicated post-processing logic.
