### ISSUE TITLE
Problem by starting a python code using systemd

### ISSUE THREAD

**Issue by Zakaria1405** [google/mediapipe#2659]
I have some problem with running my python script using the systemd configuration. When I execute the python script in a normal way i don't get any error. As soon as I use the systemd configuration I get this error: [Please click here to see the image](https://i.stack.imgur.com/Lg68J.jpg)I’ll be grateful if someone can help me.
`  
   import cv2
   import mediapipe as mp

    class HandDetector:
    # PS: please setup the detection and track variable to 0.4 if you are using a thermal camera for a better view
    # instance initialisation
    def __init__(self, mode=False, maxHands=1, detectionCon=0.8, trackCon=0.8):
        self.mode = mode
        self.maxHands = maxHands
        self.detectionCon = detectionCon
        self.trackCon = trackCon
        self.mpHands = mp.solutions.hands
        self.hands = self.mpHands.Hands(self.mode, self.maxHands,
                                        self.detectionCon, self.trackCon)
        self.mpDraw = mp.solutions.drawing_utils
        self.results = None

    def Find_Hands(self, img, draw=True):
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        self.results = self.hands.process(imgRGB)
        if self.results.multi_hand_landmarks:
            for handLms in self.results.multi_hand_landmarks:

                if draw:
                    self.mpDraw.draw_landmarks(img, handLms, self.mpHands.HAND_CONNECTIONS)
        return img

    def Find_Position(self, img):
        lmList = []
        if self.results.multi_hand_landmarks:
            myHand = self.results.multi_hand_landmarks[0]
            for id, lm in enumerate(myHand.landmark):
                h, w, c = img.shape
                cx, cy = int(lm.x * w), int(lm.y * h)

                lmList.append([id, cx, cy])

        return lmList
`

**Comment by sgowroji** [comment]
Hi @Zakaria1405, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by sgowroji** [comment]
Hi @Zakaria1405. Can you try upgrading the python as we support 3.10 now and get the latest 0.8.9 code. Latest  init method now has 5 params (see https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/hands.py#L89) and the third parameter is model_complexity, which is an int. And your error in Init is caused by it. Thanks!
