### ISSUE TITLE
Get hand_tracking_cpu source code to extract detected hand metadata

### ISSUE THREAD

**Issue by research506** [google/mediapipe#266]
By running this code below, I am able to get the demo app to run but, where can I get the source code so that I can get the hand metadata regarding finger positions and joints?

```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu \
    --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt
```

I will like to modify: bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu so I can output a file with hand metadata for sign language analysis. But this seems to be a binary file. How can I use this or integrate this with a new app?

**Comment by MAkcanca** [comment]
You are probably looking for 
> mediapipe/examples/desktop/demo_run_graph_main.cc

**Comment by research506** [comment]
> You are probably looking for
> _mediapipe/examples/desktop/demo_run_graph_main.cc_

hi @MAkcanca 

Thank you for your response. I am new to this, so bear with me here for a moment. So I need to put to use the multi_hand_graph (/mediapipe/blob/master/mediapipe/graphs/hand_tracking/multi_hand_tracking_desktop.pbtxt a)

so I guess to run this it will be something like...
demo_run_graph_main.cc --calculator_graph_config_file=multi_hand_tracking_desktop.pbtxt --input_video_path=myVideo.pm4 --output_video_path=something.mp4

Thank you sir

**Comment by MAkcanca** [comment]
demo_run_graph_main.cc is a Code file. You can't directly run it without compiling it first.
Try checking out the documents for details on how to compile and run: https://mediapipe.readthedocs.io/en/latest/multi_hand_tracking_desktop.html

**Comment by research506** [comment]
So i did:

cc mediapipeline

`bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop:demo_run_graph_main`

and got:
ERROR: Cannot run target //mediapipe/examples/desktop:demo_run_graph_main: Not executable

any idea on why bazel dont like it?

**Comment by research506** [comment]
I was able to build it using `bazel build :demo_run_graph_main ` directly from the examples/desktop folder

**Comment by research506** [comment]
now i need to obtiain the hand segments and nodes from open CV

**Comment by eknight7** [comment]
@research506 
Please look at https://mediapipe.readthedocs.io/en/latest/multi_hand_tracking_desktop.html for how to build and run multi-hand tracking example on desktop.

On desktop, you can add an output stream poller to `demo_run_graph_main.cc` or `demo_run_graph_main_gpu.cc`, such as
```
ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller multi_hand_landmarks_poller,
                   graph.AddOutputStreamPoller("multi_hand_landmarks"));
```

to listen for output packets on a particular output stream, such as `"multi_hand_landamrks"` above. 
See https://mediapipe.readthedocs.io/en/latest/hello_world_desktop.html for example.

Then, on every frame, check if a packet is available in the output stream:
```
mediapipe::Packet multi_hand_landmarks_packet;
if (!multi_hand_landmarks_poller.Next(&multi_hand_landmarks_packet)) break;
const auto& multi_hand_landmarks = multi_hand_landmarks_packet.Get<std::vector<std::vector<mediapipe::NormalizedLandmark>>>();
```

Note that you need a dependency on
```
#include "mediapipe/framework/formats/landmark.pb.h"
```
in the file you are modifying (and modify the corresponding rule in `BUILD` file as well).

And then you should be able to do what you want with these landmarks, such as print them:
```
int hand_index = 0;
for (const auto& hand_landmarks : multi_hand_landmarks) {
  int landmark_index = 0;
  for (const auto& landmark : hand_landmark) {
    std::cout << "[Hand<" << hand_index << ">] Landmark<" << landmark_index++ << ">: (" << landmark.x() << ", " << landmark.y() << ", " << landmark.z() << ")\n";
  }
 std::cout << "\n";
 ++hand_index;
}
```

**Comment by research506** [comment]
> @research506
> Please look at https://mediapipe.readthedocs.io/en/latest/multi_hand_tracking_desktop.html for how to build and run multi-hand tracking example on desktop.
> 
> On desktop, you can add an output stream poller to `demo_run_graph_main.cc` or `demo_run_graph_main_gpu.cc`, such as
> 
> ```
> ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller multi_hand_landmarks_poller,
>                    graph.AddOutputStreamPoller("multi_hand_landmarks"));
> ```
> 
> to listen for output packets on a particular output stream, such as `"multi_hand_landamrks"` above.
> See https://mediapipe.readthedocs.io/en/latest/hello_world_desktop.html for example.
> 
> Then, on every frame, check if a packet is available in the output stream:
> 
> ```
> mediapipe::Packet multi_hand_landmarks_packet;
> if (!multi_hand_landmarks_poller.Next(&multi_hand_landmarks_packet)) break;
> const auto& multi_hand_landmarks = multi_hand_landmarks_packet.Get<std::vector<std::vector<mediapipe::NormalizedLandmark>>>();
> ```
> 
> Note that you need a dependency on
> 
> ```
> #include "mediapipe/framework/formats/landmark.pb.h"
> ```
> 
> in the file you are modifying (and modify the corresponding rule in `BUILD` file as well).
> 
> And then you should be able to do what you want with these landmarks, such as print them:
> 
> ```
> int hand_index = 0;
> for (const auto& hand_landmarks : multi_hand_landmarks) {
>   int landmark_index = 0;
>   for (const auto& landmark : hand_landmark) {
>     std::cout << "[Hand<" << hand_index << ">] Landmark<" << landmark_index++ << ">: (" << landmark.x() << ", " << landmark.y() << ", " << landmark.z() << ")\n";
>   }
>  std::cout << "\n";
>  ++hand_index;
> }
> ```

My brother, this was the droid I was looking for. I will update this thread with a link to my repo where the code can be found. I owe you a beer

**Comment by garyscetbon** [comment]
@eknight7 could you please explain 

> in the file you are modifying (and modify the corresponding rule in BUILD file as well).

I added the line `"//mediapipe/framework/formats:landmark_proto",` to the "demo_run_graph_main" cc_library in the mediapipe/examples/desktop/BUILD file but I get the following error at build time:

`rule '//mediapipe/framework/formats:landmark_proto' is misplaced here (expected cc_library, objc_library, cc_proto_library or cc_import) and '//mediapipe/framework/formats:landmark_proto' does not have mandatory providers: 'CcInfo'`

I'm a total neophyte in c++ and I think the error comes from the fact that I also have to update the srcs parameter, but I tried every way I could think of to add the mediapipe/framework/formats/landmark.proto to srcs and nothing worked. Any help would be appreciated.

**Comment by eknight7** [comment]
Link to updated gist for example: https://gist.github.com/eknight7/d4a57504c8f866fc80c0eb2c61ff6b4f
