### ISSUE TITLE
Selfie Segmentation Web Demo will crush with iOS Safari.

### ISSUE THREAD

**Issue by ats05** [google/mediapipe#2660]
I have great expectations for Mediapipe's solution.
But when I tried **Selfie Segmentation** with iOS Device(iPhone X : iOS 15), it didnt work as expected,

I tried this demo from [here](https://google.github.io/mediapipe/solutions/selfie_segmentation#resources)
https://codepen.io/mediapipe/pen/wvJyQpq

And, I've also tried several Mediapipe demos, but none ob them may work as well.

It's also possible that my test device is just out of memory because it's old.

**System information** 

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):
  - No. It happened on Web demo.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
  - iOS 15. I tried with iPhone X.
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
  - Safari 15
- Programming Language and version ( e.g. C++, Python, Java):
  - Of cause, JavaScript.
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ):
  - Selfie Segmentation

**Describe the current behavior:**

Safari tab will crush.
I cant catch some console error.

Thanks.

**Comment by sgowroji** [comment]
Hi @ats05, Could you please provide the error logs and screen recording video of the above error to investigate the issue. Thanks

**Comment by ats05** [comment]
Unfortunately, Safari's DevTool is not able to catch the error log.

In the capture, the tab crashes once, reloads, and then crashes again.
It shows this behavior every time.

If you have any other useful research methods or information, please let me know.

https://user-images.githubusercontent.com/10459423/137116277-747fb4ab-3079-4834-8242-e20995f69c05.MP4
![log](https://user-images.githubusercontent.com/10459423/137116504-2e65f85b-860f-4740-afa0-8b33b36d4a22.png)


Thanks!

**Comment by tyrmullen** [comment]
I suspect this is an iOS15/Safari15 issue, since previously Safari did not support WebGL2.  We actually have a lot of custom code for Safari support in order to ensure everything runs in a WebGL1 context on Safari, so some compatibility fixes may be necessary.

For tracking, related issues are: #2675 and #2536 .

**Comment by eldog** [comment]
My application crashes unless I turn off `GPU Process: Canvas Rendering` off through the iOS setting menu.

Setting > Safari > Advanced > Experimental Features > GPU Process: Canvas Rendering

I got this information from https://github.com/flutter/flutter/issues/89655

Seems to be related to this issue,

https://developer.apple.com/forums/thread/684843

Some are saying it only happens on pages with unicode, not sure if this is true. But running on the GPU with iOS 15 safari seems to only work for ~10 seconds until the page crashes without turning the above option off. It takes longer to happen with lower resolution media captures (like 320x240), but still happens eventually. 

So it looks like an iOS WebGL2 issue. Running on CPU using the `useCpuInference` option is an alternative and didn't seem to crash, but has almost unusable performance.

**Comment by jalamprea** [comment]
It is still happening on iOS 15 but at least here is a workaround.
Use the `useCpuInference:true` on mediaPipe options.
Then on the onFrame callback from the CameraUtils, when you call `selfieSegmentation.send(.....)` add a .catch call to capture those random errors from mediaPipe and webGL and then reset the segmentation `selfieSegmentation.reset()`

Is not an elegant solution but it works... for the end user, they will see a small glitch in the camera and then continue working properly.

**Comment by Sakshamkapur** [comment]
Hey @jalamprea it only seems to work after we remount the canvas for me also its very laggy.. do we have any other alternatives for this or i will have to change the library
Also one the canvas is rendered its not converting to img using todataurl api of canvas 
Does any one know y?

**Comment by kuaashish** [comment]
Hello @ats05,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
