### ISSUE TITLE
no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type

### ISSUE THREAD

**Issue by xiaogong331** [google/mediapipe#2662]
### platform
wsl linux ubuntu and window10

I  has been successfully installed the mediapipe in my wsl ubuntu and output the "hello world"

### My SDK and NDK address

SDK: /mnt/c/Users/26797/AppData/Local/Android/Sdk

NDK:/mnt/c/Users/26797/AppData/Local/Android/Sdk/ndk/20.1.5948944

### bug
When I execute "bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu"
it show: 

"ERROR: While resolving toolchains for target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
INFO: Elapsed time: 0.416s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)"

Whether if WSL can not use the window path?

**Comment by sgowroji** [comment]
Hi @xiaogong331, Could you please confirm whether the NDK and SDK paths are set correct and try updating the NDK to 21 as mentioned in our [prerequsites](https://google.github.io/mediapipe/getting_started/android.html#prerequisite). And we also released Hands gradle Android API solutions in our [Repo](https://google.github.io/mediapipe/getting_started/android_solutions.html#android-solution-apis).

**Comment by fimo719** [comment]
HI @tigerya214 
I want to know how do you fix it because I get the same error.
Can you tell me, please~~

**Comment by fimo719** [comment]
＠rathishkumar He says to use the code below to fix it but I get other errors.
https://github.com/google/mediapipe/issues/1244#issuecomment-729589707
android_sdk_repository(
    name = "androidsdk",
    path = "/Library/android/sdk"
)

android_ndk_repository(
    name = "androidndk",
    path = "/Library/android/sdk/ndk/21.3.6528147"
)

ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: 
INFO: Elapsed time: 3.072s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (139 packages loaded, 9353 targets\
 configured)
