### ISSUE TITLE
FaceMesh solution in Python: How to set virtual camera parameters?

### ISSUE THREAD

**Issue by trzy** [google/mediapipe#2667]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): Using FaceMesh example with webcam capture for now
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows, Python 3.8
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.8
- Bazel version: N/A
- Solution (e.g. FaceMesh, Pose, Holistic): FaceMesh
- Programming Language and version ( e.g. C++, Python, Java): Python 3.8

**Describe the expected behavior:**
N/A

**Standalone code you may have used to try to get what you need :**
N/A

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

The FaceMesh documentation here (https://google.github.io/mediapipe/solutions/face_mesh.html) suggests that virtual camera parameters can be set (e.g., camera intrinsics) but I don't see an API for this in the FaceMesh Python module. How is it currently estimating depth without this information and can the results be improved by supplying intrinsic parameters?

**Comment by ruchind159** [comment]
Hi @trzy , did you find out how they are doing it? or were you able to measure physical measurements of facial features?

**Comment by kuaashish** [comment]
Hello @trzy,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
