### ISSUE TITLE
Mediapipe v0.8.6 and later can not install on Jetson Nano

### ISSUE THREAD

**Issue by sonnv174** [google/mediapipe#2668]
There is this error when I install mediapipe on Jetson Nano by this cmd:
`pip3 install mediapipe`

> ERROR: Could not find a version that satisfies the requirement mediapipe
> ERROR: No matching distribution found for mediapipe

I have seen this [post](https://github.com/google/mediapipe/blob/master/docs/getting_started/troubleshooting.md#python-pip-install-failure) and setup python3.8 and 3.9, but still got that error.
How can I install mediapipe v0.8.6 and later on Jetson Nano?

**Comment by Sid4597** [comment]
were you able to install higher versions?
