### ISSUE TITLE
Error while upgrading to 0.4.1633558788 mediapipe pose

### ISSUE THREAD

**Issue by mehtapaxshal** [google/mediapipe#2669]
Error while upgrading mediapipe **pose** npm version from 0.2.1614787780 to latest i.e. 0.4.1633558788

```
Calculator::Open() for node "poselandmarkgpu__poselandmarkbyroigpu__poselandmarkmodelloader__LocalFileContentsCalculator" failed: Failed to read file third_party/mediapipe/modules/pose_landmark/pose_landmark_full.tflite. [type.googleapis.com/mediapipe.StatusList='\n\xe1\x01\x08\x02\x12\xdc\x01\x43\x61lculator::Open() for node \"poselandmarkgpu__poselandmarkbyroigpu__poselandmarkmodelloader__LocalFileContentsCalculator\" failed: Failed to read file third_party/mediapipe/modules/pose_landmark/pose_landmark_full.tflite.']
put_char @ pose_solution_simd_wasm_bin.js:9
write @ pose_solution_simd_wasm_bin.js:9
...
...
...
r @ camera_utils.js:7
(anonymous) @ camera_utils.js:7
requestAnimationFrame (async)
q @ camera_utils.js:7
a.video.onloadedmetadata @ camera_utils.js:7
ReactTest.js:327 RuntimeError: abort(undefined) at Error
    at jsStackTrace (pose_solution_simd_wasm_bin.js:9)
    at stackTrace (pose_solution_simd_wasm_bin.js:9)
    at abort (pose_solution_simd_wasm_bin.js:9)
    at _abort (pose_solution_simd_wasm_bin.js:9)
    at pose_solution_simd_wasm_bin.wasm:0x517665
    at pose_solution_simd_wasm_bin.wasm:0x517520
    at pose_solution_simd_wasm_bin.wasm:0x51767e
    at pose_solution_simd_wasm_bin.wasm:0x19398
    at pose_solution_simd_wasm_bin.wasm:0x14436
    at SolutionWasm$send [as send] (eval at new_ (pose_solution_simd_wasm_bin.js:9), 

```

**Comment by sgowroji** [comment]
Hi @mehtapaxshal,  Could you please have a look at this https://github.com/google/mediapipe/issues/2267#issuecomment-875862168

**Comment by mehtapaxshal** [comment]
Any updates on this issue? Looking forward for the fix and unblock our team.

**Comment by mehtapaxshal** [comment]
Any updates guys?

**Comment by mhays-google** [comment]
Thanks for the patience.  I did stage a new version of pose recently, and it does not exhibit this error.  Can you try upgrading?

**Comment by mehtapaxshal** [comment]
@mhays-google I did try the new version just now and still errors out. FYI, I tried the npm version - 0.5.1635988162

Let me know if you need any other information to debug more about this issue.
cc @sgowroji

**Comment by mehtapaxshal** [comment]
@mhays-google Anything I can try on my end or is there any debug information you would like me to send to you to figure out the issue?

**Comment by mhays-google** [comment]
I'm sorry that this is still blocking your team.  This error: 

"Failed to read file third_party/mediapipe/modules/pose_landmark/pose_landmark_full.tflite"

The path is internal, but the file is still part of the bundle.  This tells me that the tflite file is not getting read correctly, and is probably missing.  Take a look at the network tab and make sure that this file is being downloaded with a 200.  Also, this could happen if, for some reason, the internal graph is being run before the file has finished downloading.  I use promises to sync everything, so it shouldn't be an issue.

**Comment by mehtapaxshal** [comment]
@mhays-google Thanks for your response.

I checked the network tab and I can see 200 responses from the network.

<img width="1427" alt="Screen Shot 2021-12-01 at 9 26 20 PM" src="https://user-images.githubusercontent.com/16583481/144363038-5e213424-1080-4765-b5fd-0b6f46c664a7.png">

**Comment by mehtapaxshal** [comment]
Btw, just making sure the way I am calling the file is correct or not. I am doing like this:

`const pose = new Pose({locateFile: (file) => {
      return `https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5/${file}`;
    }});`

**Comment by mhays-google** [comment]
You are actually looking for `pose_landmark_full.tflite`, not `pose_web.binarypb`

I see 'pose_landmark_full.tflite' being loaded, but I do not see `pose_landmark_full.tflite` getting loaded.  Look in your options and set `model_complexity` to 0, just as a sanity check.  Tell me if that works.

**Comment by mehtapaxshal** [comment]
I tried setting `model_complexity` to 0, still no luck. I don't see  `pose_landmark_full.tflite` in the network tab i.e. not getting loaded. What can cause this issue?

**Comment by mhays-google** [comment]
Hi mehtapaxshal, can you tell me if the demo at code.mediapipe.dev/codepen/pose works on your machine (that is, the same machine on which you are experiencing this error?)

If the solution fails to start, it won't load the file.  You can try calling `await pose.initialize();`.  This will force everthing to try to initialize before sending your first frame.

**Comment by mehtapaxshal** [comment]
@mhays-google Figured out the issue. I was missing some configurations in my code that wasn't loading the required file. I am able to make it work now with the latest version. Thanks a lot for your help.

Thanks @sgowroji 
Appreciated!

**Comment by sgowroji** [comment]
Hi @mehtapaxshal, Glad you are issue resolved and thank you for sharing the update.
