### ISSUE TITLE
Error while building iris tracking example on Ubuntu 20.04.3 for Android

### ISSUE THREAD

**Issue by jarey99** [google/mediapipe#2670]
Hello, I'm following the steps to build an Android application using Mediapipe, and so far I've successfully completed the installation procedure for Window's Subsystem for Linux (WSL) using Ubuntu 20.04.3 (https://google.github.io/mediapipe/getting_started/install.html). I'm now trying to build the iris tracking example from the Mediapipe repository on WSL by following these instructions: https://google.github.io/mediapipe/getting_started/android. I've installed Android Studio on my Window's 10 device and am using SDK Build-Tools 29.0.1, SDK Platform-Tools 31.0.3, SDK Command-line Tools 5.0, NDK 21.4.7075529, and Android 10.0 (Q) with API Level = 29 to build the iris tracking example. After specifying $ANDROID_HOME and $ANDROID_NDK_HOME with

```javascript
export ANDROID_HOME=/mnt/c/Users/[USER]/AppData/Local/Android/Sdk
export ANDROID_NDK_HOME=/mnt/c/Users/[USER]/AppData/Local/Android/Sdk/ndk/21.4.7075529
```

and building the iris tracking example with

```javascript
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/iristrackinggpu:iristrackinggpu
```

I get the following ERROR:

```javascript
ERROR: /home/[USER]/.cache/bazel/_bazel_[USER]/161e1a9f048e67cf54be7520be6418b1/external/androidsdk/BUILD.bazel:13:25: @androidsdk//:aapt2_binary: missing input file 'external/androidsdk/build-tools/29.0.1/aapt2', owner: '@androidsdk//:build-tools/29.0.1/aapt2'
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/iristrackinggpu:iristrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/[USER]/.cache/bazel/_bazel_[USER]/161e1a9f048e67cf54be7520be6418b1/external/androidsdk/BUILD.bazel:13:25 1 input file(s) do not exist
```

I get this error when I run ANY of the examples (i.e. posetacking, handtracking, etc) so any help would be greatly appreciated!

**Comment by sgowroji** [comment]
Hi @jarey99, Can you try executing the command  `bazel clean --expunge` and test the above steps again.
