### ISSUE TITLE
Face geometry in javascript

### ISSUE THREAD

**Issue by nicktasios** [google/mediapipe#2673]
Is it possible to get the face geometry like [here](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt) from within javascript?

I found that [this file](https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619/face_mesh_solution_packed_assets_loader.js) loads the face geometry as a binarypb, but I don't if it's actually executed and where it's stored.

**Comment by sgowroji** [comment]
Hi @nicktasios, Could you please elaborate your use case with the above query. Thanks!

**Comment by MahdiHabibiXr** [comment]
> 

Hi :)) Can we have the example code now?

**Comment by cancan101** [comment]
@mhays-google, Is the FaceGeometry that you previously referenced (which provides for each face the transform matrix for the head pose) the same as the `facial_transformation_matrixes` returned by the "Face Landmarker": https://developers.google.com/mediapipe/solutions/vision/face_landmarker/web_js#handle_and_display_results?
