### ISSUE TITLE
Pass options into subgraph

### ISSUE THREAD

**Issue by alexdmiller** [google/mediapipe#2674]
<em>Please make sure that this is a feature request.</em>

**Describe the feature and the current behavior/state:**

I have a subgraph which contains calculators that expose parameters. I would like to nest this subgraph within my main graph multiple times, but each time pass in a different set of parameters.

If this feature already exists, it is undocumented. As far as I can tell, none of the example subgraphs within the mediapipe repository do this.

**Will this change the current api? How?**

When instantiating a subgraph, options could be passed like so:

```
node {
    calculator: "MySubGraph"
    input_stream: "input"
    output_stream: "output"
    node_options: {
        my_first_calculator: [type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
           model_path: "mediapipe/models/detection_model_1.tflite"
        }
        my_second_calculator: [type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
           model_path: "mediapipe/models/detection_model_2.tflite"
        }
    }
}
```

**Who will benefit with this feature?**

People that want to use subgraphs to reduce redundancy within their graphs. The mediapipe examples could themselves likely be improved with such a structure?

**Please specify the use cases for this feature:**

If you have a subgraph which is used by multiple graphs, or used in the same graph multiple times, and you want to pass different options to different subgraphs.

**Any Other info:**

**Comment by kaomoneus** [comment]
Hi guys! Any progress on that?

**Comment by alexdmiller** [comment]
Any update on this? Thanks!

**Comment by ayeganov** [comment]
I would like to have this feature to be able to customize paths to my models within the subgraph.
