### ISSUE TITLE
get graph error while call AddPacketToInputStream

### ISSUE THREAD

**Issue by InvisibleLeVen** [google/mediapipe#2676]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>
 
- Windows desktop c++
- Pose solution

**Describe the current behavior:**
When calling AddOutputStreamPoller to set observe_timestamp_bounds to true, the following error occurs when calling AddPacketToInputStream
run_status.message() outputs the following error message

Graph has errors:
Calculator::Process() for node "poselandmarkcpu__poselandmarkbyroicpu__poselandmarksandsegmentationinverseprojection__InverseMatrixCalculator" failed: ; Inverse matrix cannot be calculated.tors/util/inverse_matrix_calculator.cc:38)

This happens when a person cannot be detected for a period of time

If observe_timestamp_bounds is set to false, this will not happen, but the Next function will always be stuck when the camera cannot detect people.

**Comment by Avnsx** [comment]
Same happens for me using python

**Comment by melvinebenezer** [comment]
Any updates on this issue ?

**Comment by kuaashish** [comment]
Hello @InvisibleLeVen,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
