### ISSUE TITLE
python unicode error -> FileNotFoundError: The path does not exist.

### ISSUE THREAD

**Issue by dyc081818** [google/mediapipe#2677]
I use pyinstaller to compile the Python project, and finally generate an exe executable file. When the exe file path contains unicode characters, it will report an error: 

> Traceback (most recent call last):
>   File "mediapipe_facemesh.py", line 81, in <module>
>   File "mediapipe_facemesh.py", line 29, in show_face_mesh
>   File "mediapipe\python\solutions\face_mesh.py", line 94, in __init__
>   File "mediapipe\python\solution_base.py", line 237, in __init__
> FileNotFoundError: The path does not exist.

**Comment by Giovannibriglia** [comment]
I have the same problem

**Comment by Fourtinato99** [comment]
+1

**Comment by xesdiny** [comment]
+1

**Comment by YaroslavFur** [comment]
This helped me with the 237 line error, I just followed the instruction of [Bar-Levav] (edited .spec file + special pyinstaller compilation command):
https://stackoverflow.com/questions/67887088/issues-compiling-mediapipe-with-pyinstaller-on-macos

**Comment by dyc081818** [comment]
> This helped me with the 237 line error, I just followed the instruction of [Bar-Levav] (edited .spec file + special pyinstaller compilation command): https://stackoverflow.com/questions/67887088/issues-compiling-mediapipe-with-pyinstaller-on-macos

Thanks Reply
But obviously that approach is too cumbersome, I can offer an easier way
`a = Analysis(py_files,
             pathex=[],
             binaries=[],
             datas=[('Your Python Path/Lib/site-packages/mediapipe/modules', 'mediapipe/modules')]
`

**Comment by dyc081818** [comment]
> This helped me with the 237 line error, I just followed the instruction of [Bar-Levav] (edited .spec file + special pyinstaller compilation command): https://stackoverflow.com/questions/67887088/issues-compiling-mediapipe-with-pyinstaller-on-macos

Thanks Reply
But obviously that approach is too cumbersome, I can offer an easier way in spec file:
`a = Analysis(py_files,
             pathex=[],
             binaries=[],
             datas=[('Python Path/Lib/site-packages/mediapipe/modules', 'mediapipe/modules')],`

The above configuration is added to copy the modules folder to the target folder, and it can run correctly
But if the path of the exe contains unicode characters, it will report an error

> File "mediapipe\python\solutions\face_mesh.py", line 94, in __init__
> File "mediapipe\python\solution_base.py", line 237, in __init__
> FileNotFoundError: The path does not exist.

mediapipe doesn't seem to be able to find binaries in paths containing unicode

**Comment by AdeniltonR** [comment]
Hello, I'm having this same problem using midiapipe, can you help me.

**Comment by kuaashish** [comment]
Hello @dyc081818,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
