### ISSUE TITLE
Is there any way to unlock the operating speed limit on android?

### ISSUE THREAD

**Issue by unizzang0907** [google/mediapipe#2679]
Have I written custom code (as opposed to using a stock example script provided in Mediapipe): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 11
MediaPipe version: 0.8.8
Solution (e.g. FaceMesh, Pose, Holistic): Holistic
Programming Language and version ( e.g. C++, Python, Java): Flutter, Javascript

Hello, I'm making a mediapipe that works on Android.
In the process of building the environment, we are using the method of floating the media pipe in the app by using the web view format in the app. This way I can use the mediapipe in my Javascript environment. 
However, using this method will make Holistic very slow. In the case of Javascript in the existing PC environment, the performance was 30FPS, whereas this method was limited to about 5FPS. It was confirmed that 5FPS was also displayed when the webview was turned on in a PC environment. 
Since it is a web view format made on Android, I am guessing that the operating speed is limited. Is there any way to get rid of this restriction? Or is there a way to make Holisitc run at 15fps or higher in the app?

**Comment by sgowroji** [comment]
Hi @unizzang0907, Could you please share your code  and graph changes to understand the issue much better. Thanks!
