### ISSUE TITLE
Mediapipe running multi_hand_tracking_desktop

### ISSUE THREAD

**Issue by pranayagra** [google/mediapipe#268]
For reference, the hello_world_desktop file works correctly. I am using WSL Ubuntu. However, when I attempt to run the multi_hand_tracking_desktop file for CPU (command below), I receive an error:

**Bazel Version:**
Build label: 0.27.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 17 13:00:46 2019 (1560776446)
Build timestamp: 1560776446
Build timestamp as int: 1560776446

**Command:**
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu

**Error:**
INFO: Analyzed target //mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/pranayhalo/mediapipe/mediapipe/gpu/BUILD:141:1: C++ compilation of rule '//mediapipe/gpu:gl_context' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 63 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./mediapipe/gpu/gl_context.h:31:0,
                 from mediapipe/gpu/gl_context_egl.cc:22:
./mediapipe/gpu/gl_base.h:57:10: fatal error: EGL/egl.h: No such file or directory
 #include <EGL/egl.h>
          ^~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 24.936s, Critical Path: 24.08s
INFO: 26 processes: 26 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

**Comment by eknight7** [comment]
Are you able to run any other desktop demo apps? Example: https://mediapipe.readthedocs.io/en/latest/face_detection_desktop.html ?

**Comment by eknight7** [comment]
Also, please have a look at a similar thread for reference: https://github.com/google/mediapipe/issues/261

**Comment by pranayagra** [comment]
> Are you able to run any other desktop demo apps? Example: https://mediapipe.readthedocs.io/en/latest/face_detection_desktop.html ?

**For this example, the command:**
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/face_detection:face_detection_cpu

**is working (Build complete, has the expected target message), which is more than I got with the multi_hand_tracking_desktop. However, running the command:** 
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_detection/face_detection_cpu \
    --calculator_graph_config_file=mediapipe/graphs/face_detection/face_detection_desktop_live.pbtxt

**is giving the following error: **

bazel-bin/mediapipe/examples/desktop/face_detection/face_detection_cpu: error while loading shared libraries: libopencv_calib3d.so.4.1: cannot open shared object file: No such file or directory

this file seems to be located at the same level as mediapipe:
- pranayhalo
  - .cache (
     - bazel
          - _bazel_pranayhalo
                  ..... - face_detection_cpu
  - mediapipe
     - mediapipe
     - ....

The following is the full location of the face_detection_cpu file:
C:\Users\prana\AppData\Local\Packages\CANONI~1.04O\LOCALS~1\rootfs\home\PRANAY~1\CACHE~1\bazel\_BAZEL~1\022C3E~1\execroot\MEDIAP~1\BAZEL-~1\k8-opt\bin\MEDIAP~1\examples\desktop\FACE_D~1

**Comment by pranayagra** [comment]
> Also, please have a look at a similar thread for reference: #261

That change gives the following error on the same command:
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1
mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu

ERROR: /home/pranayhalo/mediapipe/mediapipe/graphs/hand_tracking/subgraphs/BUILD:45:1: error loading package 'mediapipe/calculators/image': /home/pranayhalo/mediapipe/mediapipe/calculators/image/BUILD (Permission denied) and referenced by '//mediapipe/graphs/hand_tracking/subgraphs:multi_hand_detection_cpu'
ERROR: /home/pranayhalo/mediapipe/mediapipe/graphs/hand_tracking/subgraphs/BUILD:45:1: error loading package 'mediapipe/calculators/image': /home/pranayhalo/mediapipe/mediapipe/calculators/image/BUILD (Permission denied) and referenced by '//mediapipe/graphs/hand_tracking/subgraphs:multi_hand_detection_cpu'
ERROR: Analysis of target '//mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu' failed; build aborted: error loading package 'mediapipe/calculators/image': /home/pranayhalo/mediapipe/mediapipe/calculators/image/BUILD (Permission denied)
INFO: Elapsed time: 0.241s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: mediapipe/calculators/image

**Comment by MAkcanca** [comment]
Have you tried running the CMD/Powershell with administrator privileges?

**Comment by pranayagra** [comment]
> Have you tried running the CMD/Powershell with administrator privileges?

Yes, I have tried running Ubuntu 18.04 with administrator privileges

**Comment by eknight7** [comment]
Can you please retry with the latest version? https://github.com/google/mediapipe/releases/tag/v0.6.6

**Comment by mgyong** [comment]
Closing this thread for now. If there are still issues, pls reopen
