### ISSUE TITLE
Xcode & Tulsi version ,I an using a tool  Tulsi for generating Xcode projects from Bazel build configurations. bazel version is 3.7.2 Xcode version is 12.5.1(12E507) ,which version of Tulsi can I use ? or what wrong with this?

### ISSUE THREAD

**Issue by xiaoxiaohan1993** [google/mediapipe#2682]
INFO: Build option --xcode_version has changed, discarding analysis cache.
ERROR: /Users/administrator/Desktop/mediapipe/tulsi/src/tools/bazel_cache_reader/BUILD:15:31: in macos_command_line_application rule //src/tools/bazel_cache_reader:bazel_cache_reader: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_administrator/ff224cad84acd3994ba85759c03e5327/external/build_bazel_rules_apple/apple/internal/macos_rules.bzl", line 1192, column 58, in _macos_command_line_application_impl
		link_result = linking_support.register_linking_action(
	File "/private/var/tmp/_bazel_administrator/ff224cad84acd3994ba85759c03e5327/external/build_bazel_rules_apple/apple/internal/linking_support.bzl", line 103, column 47, in _register_linking_action
		return apple_common.link_multi_arch_binary(
Error in link_multi_arch_binary: link_multi_arch_binary() got unexpected keyword argument 'stamp'
ERROR: Analysis of target '//:tulsi' failed; build aborted: Analysis of target '//src/tools/bazel_cache_reader:bazel_cache_reader' failed
INFO: Elapsed time: 5.266s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded, 517 targets c\
onfigured)

**Comment by xiaoxiaohan1993** [comment]
I want create an Xcode project,so I install Tulsi.
git clone https://github.com/bazelbuild/tulsi.git
cd tulsi
modify build_and_run.sh
xcode_version="12.4" to xcode_version="12.5.1(12E507)"
then ,
sh build_and_run.sh

and I seing abrove error.

**Comment by xiaoxiaohan1993** [comment]
I successfully use bazel built ios app,and can use on my ipad,
but Failed when I want use Tulsi create an Xcode project .

**Comment by sgowroji** [comment]
Have you tried upgrading the bazel and checking the above. What is your bazel configuration?
