### ISSUE TITLE
For Iris Desktop GPU example, got the error "Side packet "focal_length_pixel" is required but was not provided." 

### ISSUE THREAD

**Issue by Victoria-1** [google/mediapipe#2683]
I tried running the Iris GPU example in Debian10. The build was successful but something wrong with running:

I20211018 04:42:46.943851  3898 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
I20211018 04:42:46.947917  3898 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
I20211018 04:42:47.070009  3898 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 4
I20211018 04:42:47.074930  3908 gl_context.cc:331] GL version: 3.0 (OpenGL ES 3.0 Mesa 18.3.6)
I20211018 04:42:47.075035  3898 demo_run_graph_main_gpu.cc:68] Initialize the camera or load the video.
I20211018 04:42:47.934391  3898 demo_run_graph_main_gpu.cc:89] Start running the calculator graph.
E20211018 04:42:47.942932  3898 demo_run_graph_main_gpu.cc:197] Failed to run the graph: ValidateRequiredSidePackets failed to validate: 
; Side packet "focal_length_pixel" is required but was not provided.

I found one solution: https://github.com/google/mediapipe/issues/1265#issue-738145799. 

cv::cvtColor(camera_frame_raw, camera_frame, cv::COLOR_BGR2RGBA);
    if (!load_video) {
      cv::flip(camera_frame, camera_frame, /*flipcode=HORIZONTAL*/ 1);
    }

    // Wrap Mat into an ImageFrame.
    auto input_frame = absl::make_unique<mediapipe::ImageFrame>(
        mediapipe::ImageFormat::SRGBA, camera_frame.cols, camera_frame.rows,
        mediapipe::ImageFrame::kGlDefaultAlignmentBoundary);
    cv::Mat input_frame_mat = mediapipe::formats::MatView(input_frame.get());
    camera_frame.copyTo(input_frame_mat);

The code has already added 'A' to both RGB and SRGB.
But it does not work for me , any other suggestions? Thanks！

**Comment by mcclanahoochie** [comment]
the error is
` Side packet "focal_length_pixel" is required but was not provided.`

this can be sent to the graph via [StartRun](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc#L92)

```
      std::map<std::string, mediapipe::Packet> extra_side_packets;
      extra_side_packets.insert({"focal_length_pixel", mediapipe::MakePacket<float>(XXX)});
      auto r = graph.StartRun(extra_side_packets);
```

replace XXX with your focal length

**Comment by lilinxiong** [comment]
@mcclanahoochie Hi, I have a question. What I see in the [iris_tracking](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/examples/desktop/iris_tracking/iris_depth_from_image_desktop.cc#L140) of the desktop is an input image. Is it because ```focal_length_pixel``` cannot be obtained on the desktop?
My ultimate goal is to achieve iris_depth on the desktop.
I am not very familiar with Windows desktop development, but I can directly call API on Android and get ```focal_length_pixel``` ([CameraXPreviewHelper.java#L458-L471](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/java/com/google/mediapipe/components/CameraXPreviewHelper.java#L458-L471)) through calculation. Logically, I feel that there is also a way to get ```focal_length_pixel``` on Windows desktop.
Can you help me? thank you very much~

**Comment by mcclanahoochie** [comment]
if you are loading a JPG or PNG that has the focal lenght exif data, then the desktop can work just fine, by querying the image for the right value (in exif data). 
Webcams do not provide that value programmatically (like phones do), so you need to find it (or compute it) and specify manually.

**Comment by lilinxiong** [comment]
Thank you for your reply, can I understand that as long as I provide ```focal_length_pixel```, no matter if I input a picture, video, or data collected from the camera, I can use iris_tracking normally on the desktop.
