### ISSUE TITLE
mediapipe  face effects for multiple faces.

### ISSUE THREAD

**Issue by saadullahphaedra** [google/mediapipe#2684]
i need to apply facial filters using medipipe "face effects" android solution for multiple faces.

currently "face effects" solution works for only one face.

is there any way to change number of face in face effects solution just like face mesh solution where i only changed.

from 

private static final int NUM_FACES = 1;

to 

private static final int NUM_FACES = 2;

**Comment by sgowroji** [comment]
As mentioned in the [documentation](https://google.github.io/mediapipe/solutions/face_mesh#face-effect-example) it supports only one face.
