### ISSUE TITLE
Retrieve boxes and Ids on MainActivity

### ISSUE THREAD

**Issue by ibrandiay** [google/mediapipe#2685]
Hello
I manage to run successfully MediaPipe Box Tracking with aar on android studio.  However, I want get the tracking box info (Rect, label, Id , confidence). But i don't know how. thank you for helping me

**Comment by kuaashish** [comment]
Hello @ibrandiay,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
