### ISSUE TITLE
hand tracking gpu or cpu version show result error

### ISSUE THREAD

**Issue by ydxt** [google/mediapipe#269]
I use this code compile success.
```
 bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS \
    mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
```

and use this code for run:
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu \
    --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt
```

It crashed. gpu and cpu version have the same problem
![mediapipe error](https://user-images.githubusercontent.com/7225304/69520495-d8cccc00-0f97-11ea-8cc2-6639a75a4744.png)
.

some output inforemation:
I1125 15:12:29.904856 14970 demo_run_graph_main_gpu.cc:56] Initialize the calculator graph.
I1125 15:12:29.906642 14970 demo_run_graph_main_gpu.cc:60] Initialize the GPU.
I1125 15:12:29.913755 14970 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 5
I1125 15:12:29.964725 14977 gl_context.cc:233] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 440.26)
I1125 15:12:29.964769 14970 demo_run_graph_main_gpu.cc:66] Initialize the camera or load the video.
I1125 15:12:30.767511 14970 demo_run_graph_main_gpu.cc:91] Start running the calculator graph.
I1125 15:12:30.767782 14970 demo_run_graph_main_gpu.cc:96] Start grabbing and processing frames.
INFO: Created TensorFlow Lite delegate for GPU.

**Comment by eknight7** [comment]
Hi, are you able to run the object detection demo? https://mediapipe.readthedocs.io/en/latest/object_detection_desktop.html#tensorflow-lite-object-detection-demo-with-webcam-cpu

**Comment by ydxt** [comment]
> Hi, are you able to run the object detection demo? https://mediapipe.readthedocs.io/en/latest/object_detection_desktop.html#tensorflow-lite-object-detection-demo-with-webcam-cpu

it works. but "Hand Tracking Demo" is error.

**Comment by MAkcanca** [comment]
I managed to make it work for only 1 frame by adding `cv::waitKey(25)` After the line 78 at the demo_run_graph_main.cc
I believe problem lies on the  `if (!poller.Next(&packet)) break; // line 114` This line hangs

**Comment by MAkcanca** [comment]
Related to #242

**Comment by saizhang12** [comment]
Having the same issue, when running using :
> bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt 

it only works for 1 frame and then hangs at this line
>  if (!poller.Next(&packet)) break;
The hand_detection_desktop_live.pbtxt works fine.

My env: macOS 10.14, xcode 10, opencv 3.4.5

**Comment by eknight7** [comment]
Can you please retry these examples with the latest version? https://github.com/google/mediapipe/releases/tag/v0.6.6

**Comment by ydxt** [comment]
> Can you please retry these examples with the latest version? https://github.com/google/mediapipe/releases/tag/v0.6.6

thanks. new version is work.
