### ISSUE TITLE
face_mesh_gpu build successfully but get errors when running

### ISSUE THREAD

**Issue by tomleader** [google/mediapipe#2693]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Linux Ubuntu 20
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc 9.3.0
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): c++
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.8
- Bazel version: 3.7.2
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): opencv-4.2

**Describe the problem**:

Build ok with the command:
```
bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
  mediapipe/examples/desktop/face_mesh:face_mesh_gpu 
```
When I try to run then:
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_mesh/face_mesh_gpu --calculator_graph_config_file=mediapipe/graphs/face_mesh/face_mesh_desktop_live_gpu.pbtxt

Failed to run the graph: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES2 request. 
``` 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
  mediapipe/examples/desktop/face_mesh:face_mesh_gpu 

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_mesh/face_mesh_gpu --calculator_graph_config_file=mediapipe/graphs/face_mesh/face_mesh_desktop_live_gpu.pbtxt
```

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

```
I20211019 21:34:15.891260 18689 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
I20211019 21:34:15.904681 18689 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
I20211019 21:34:15.917039 18689 gl_context_egl.cc:162] Successfully initialized EGL. Major : 1 Minor: 5
W20211019 21:34:15.917093 18689 gl_context_egl.cc:167] Creating a context with OpenGL ES 3 failed: UNKNOWN: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES3 request. 
W20211019 21:34:15.917111 18689 gl_context_egl.cc:168] Fall back on OpenGL ES 2.
E20211019 21:34:15.921241 18689 demo_run_graph_main_gpu.cc:197] Failed to run the graph: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES2 request. 
```

**Comment by sgowroji** [comment]
Could you verify that your OpenGL ES version is 3.1 or above? See this requirement at https://google.github.io/mediapipe/getting_started/gpu_support.html#opengl-es-setup-on-linux-desktop

**Comment by tomleader** [comment]
> Could you verify that your OpenGL ES version is 3.1 or above? See this requirement at https://google.github.io/mediapipe/getting_started/gpu_support.html#opengl-es-setup-on-linux-desktop

```
glxinfo | grep -i opengl

OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 12.0.0, 256 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 21.0.3
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

```

**Comment by sgowroji** [comment]
Hi @tomleader, Found a similar issue https://github.com/google/mediapipe/issues/1483#issuecomment-765811256 can you try the workaround mentioned in it. Thanks!

**Comment by tomleader** [comment]
> Hi @tomleader, Found a similar issue [#1483 (comment)](https://github.com/google/mediapipe/issues/1483#issuecomment-765811256) can you try the workaround mentioned in it. Thanks!

I had already try ... but still got the same error
