### ISSUE TITLE
Build failing in Windows 10

### ISSUE THREAD

**Issue by mysticidiot** [google/mediapipe#2695]
**System information** 
- Windows 10
- Bazel 4.2.1
- Python version 3.9.7
- Tensorflow version 2.6.0
- Mediapipe version latest
- OpenCV version 3.4.10

**Describe the problem**:

While running the build for iris depth estimation or hand tracking using - 

PS F:\mediapipe> bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Users\admin\AppData\Local\Progra
ms\Python\Python39\python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

I get the following error -

 From Action external/org_tensorflow/tensorflow/core/util/version_info.cc:
L A U N C H E R   E R R O R :   C a n n o t   l a u n c h   p r o c e s s :   " p y t h o n . e x e "   C : \ U s e r s \ a d m i n \ _ b a z e l _ a d m i n \ c e x 6 4 6 b y \ e x e c r o o t \ m e d i a p i p e \ b a z e l - o u t \ x 6 4 _ w i n d o w s - o p t - S T - e 0 f 7 8 f a f e 9 8 f \ b i n \ e x t e r n a l \ o r g _ t e n s o r f l o w \ t e n s o r f l o w \ t o o l s \ g i t \ g e n _ g i t _ s o u r c e . z i p   - - g e n e r a t e   e x t e r n a l / l o c a l _ c o n f i g _ g i t / g e n / s p e c . j s o n   e x t e r n a l / l o c a l _ c o n f i g _ g i t / g e n / h e a d   e x t e r n a l / l o c a l _ c o n f i g _ g i t / g e n / b r a n c h _ r e f   b a z e l - o u t / x 6 4 _ w i n d o w s - o p t / b i n / e x t e r n a l / o r g _ t e n s o r f l o w / t e n s o r f l o w / c o r e / u t i l / v e r s i o n _ i n f o . c c   - - g i t _ t a g _ o v e r r i d e =
 R e a s o n :   ( e r r o r :   2 ) :   T h e   s y s t e m   c a n n o t   f i n d   t h e   f i l e   s p e c i f i e d .

ERROR: C:/users/admin/_bazel_admin/cex646by/external/org_tensorflow/tensorflow/core/util/BUILD:374:24: output 'external/org_tensorflow/tensorflow/core/util/version_info.cc' was not created
ERROR: C:/users/admin/_bazel_admin/cex646by/external/org_tensorflow/tensorflow/core/util/BUILD:374:24: Action external/org_tensorflow/tensorflow/core/util/version_info.cc failed: not all outputs were created or valid
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.

Any help is much appreciated!

**Comment by mysticidiot** [comment]
> Hi @mysticidiot, Can you check this Duplicate #1658 and try the workarounds mentioned in it

Hi @sgowroji, so if I understand correctly, I should downgrade Bazel version to 3.7.2? Or should I downgrade the Python version since the issue in bazelbuild/bazel#13053 mentioned using a lower version of JDK.
What bazel version and python version would you recommend?

**Comment by sgowroji** [comment]
Hi @mysticidiot, Can you try executing the command `bazel clean --expunge ` and please follow the steps from [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows). Python 3.7 to 3.9 and Bazel 3.7.2  to higher.

**Comment by mysticidiot** [comment]
Hey. I resolved the issue by downgrading my Bazel version to 3.7.2 and Python 3.7.6
The example codes are working now. Thank you!
