### ISSUE TITLE
Build failing in Windows 10，failed in the ninth step of the official installation tutorial， [An error occurred during the fetch of repository 'local_execution_config_python']

### ISSUE THREAD

**Issue by loiswen** [google/mediapipe#2696]
**System information** 
- Windows 10
- Bazel 3.7.2
- Python version 3.8.10 
- Installed using virtualenv? pip? Conda? (if python):
- Mediapipe version latest
- OpenCV version 3.4.10

**Describe the problem**:
 see the error when building MediaPipe on Windows:
`ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed

ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Repository command failed`

I have tried this workaround but it didn't solve：https://github.com/google/mediapipe/issues/724

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Program Files//Python3.8.10//python.exe" mediapipe/examples/desktop/hello_world`

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:
`C:\Users\17272\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Program Files//Python3.8.10//python.exe" mediapipe/examples/desktop/hello_world
Starting local Bazel server and connecting to it...
DEBUG: C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  C:/users/17272/mediapipe/WORKSPACE:409:14: in <toplevel>
  C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/tensorflow/workspace2.bzl:1085:19: in workspace
  C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/tensorflow/workspace2.bzl:85:27: in _tf_toolchains
  C:/users/17272/_bazel_17272/ekfsvi3b/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/17272/_bazel_17272/ekfsvi3b/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/17272/_bazel_17272/ekfsvi3b/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
'C://Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Repository command failed
'C://Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
INFO: Elapsed time: 7.183s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 11 targets configured)`

![e1](https://user-images.githubusercontent.com/47554331/138231172-ce55d11b-d6c9-4558-ac37-3f9c1092a1a2.JPG)
![e2](https://user-images.githubusercontent.com/47554331/138231199-9c0604c4-304d-4da1-8fd3-b16821cd839c.JPG)

**Comment by fadi-GitHub** [comment]
@loiswen was your problem solved if yes please tell as I am facing the same problem.

**Comment by homuler** [comment]
As a workaround, you can install python in a path that does not contain spaces (e.g. `C:\Users\YOUR_ACCOUNT\AppData\Local\Programs\Python\Python39\python.exe`).

**Comment by CoderJackLiu** [comment]
reinstall python in a custom folder resolve the error.
