### ISSUE TITLE
Hand tracking for desktop

### ISSUE THREAD

**Issue by karfly** [google/mediapipe#27]
Hey,

In your latest [blog](https://ai.googleblog.com/2019/08/on-device-real-time-hand-tracking-with.html) you released a very nice hand-tracking model. In [docs](https://github.com/google/mediapipe/blob/master/mediapipe/docs/hand_tracking_mobile_gpu.md) I only found an example for mobile devices.

Is it somehow possible to use your hand-tracking model on the desktop?

**Comment by jiuqiant** [comment]
Currently, we only have [the desktop demos](https://github.com/google/mediapipe/blob/master/mediapipe/docs/object_detection_desktop.md) for object detection.
We are working on the other desktop demos and will have a better desktop coverage soon.

**Comment by imLogM** [comment]
> Currently, we only have [the desktop demos](https://github.com/google/mediapipe/blob/master/mediapipe/docs/object_detection_desktop.md) for object detection.
> We are working on the other desktop demos and will have a better desktop coverage soon.

Nice job！！！ Looking forward the desktop version of "hand tracking"  ~

**Comment by mgyong** [comment]
@mcclanahoochie FYI
