### ISSUE TITLE
Record video from Mediapipe Outputs video stream ?

### ISSUE THREAD

**Issue by afsaredrisy** [google/mediapipe#270]
I am trying to record video from [mediapipe](https://github.com/google/mediapipe) output surface into mp4 file, I tried by setting a ```RecordableSurfaceView``` to ```SurfaceOutput``` like this.

```java
previewDisplayView = new RecordableSurfaceView(this);

...
// Code inside surfaceCreated(SurfaceHolder holder)
frameProcessor.getVideoSurfaceOutput().setSurface(holder.getSurface());


```

This [RecordableSurfaceView](https://github.com/UncorkedStudios/recordablesurfaceview/blob/master/recordablesurfaceview/src/main/java/com/uncorkedstudios/android/view/recordablesurfaceview/RecordableSurfaceView.java) I am using instead of ```SurfaceView```

After recording video from this surface a corrupt file being generated by SurfaceView?

What will be the easy way to record video from ```Mediapipe``` output video stream.

**Comment by eknight7** [comment]
Hi @afsaredrisy , this is a bit out of scope of MediaPipe, because once the output is available from the graph in Java, you should be able to use regular Android classes to do what you want with the data, such as record it in a file.

**Comment by code-iot** [comment]
I could get recording done. frameProcessor.getVideoSurfaceOutput().setSurface() should be called by passing the Surface that was created by RecordableSurfaceview. But with this even though recording works fine, I don't see the preview. Preview comes as black screen. I could not find any solution so far. I know this is out of scope for MediaPipe, but posting here, in case someone is getting the corrupt output video.

**Comment by JBHua** [comment]
> I could get recording done. frameProcessor.getVideoSurfaceOutput().setSurface() should be called by passing the Surface that was created by RecordableSurfaceview. But with this even though recording works fine, I don't see the preview. Preview comes as black screen. I could not find any solution so far. I know this is out of scope for MediaPipe, but posting here, in case someone is getting the corrupt output video.

I'm getting the exact same behavior. To be more specific, I can EITHER save the video successfully and get a black screen preview OR I can set up the preview without error while the saved video is corrupted. I failed to achieve both goals at the same time.

My guess is that one Surface can only be connected to one output, but having a preview and recording a video essentially needs us to connect the Surface to two outputs simultaneously. Reference: [https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/framework/SurfaceOutput.java#L48](url)

**Comment by afsaredrisy** [comment]
Here is work around I did you can check it, It is build with older version of Mediapipe but you can use the same approach with new also. 
https://github.com/afsaredrisy/MediapipeSegmentationGradle

**Comment by JBHua** [comment]
> Here is work around I did you can check it, It is build with older version of Mediapipe but you can use the same approach with new also.
> https://github.com/afsaredrisy/MediapipeSegmentationGradle

I will check it out! Thank you Afsar!
