### ISSUE TITLE
what positions correspond to do the 7 keypoints from the Palm detection outputs?

### ISSUE THREAD

**Issue by TaoZappar** [google/mediapipe#2700]
I noticed there are 7 keypoints from the palm detection results (7 dots within the green box). could someone explain where these 7 keypoints correspond to? 

Also, what are they used for? I assume they are used for determine the bbox orientation. However, the green box is alway upright , doesn't rotate during the detection.

And they are very jittery, any way to alleviate this problem?

many thanks.
![image](https://user-images.githubusercontent.com/92162158/138318685-e9dbc681-cec1-43b4-99a0-9e85d288c998.png)

**Comment by sgowroji** [comment]
Before @bazarevsky replies on this thread, Can you check https://github.com/google/mediapipe/issues/1638#issuecomment-974167633 for more understanding of palm detection output

**Comment by MrLaki5** [comment]
For anybody still wondering: here’s the answer

<img width="772" height="394" alt="Image" src="https://github.com/user-attachments/assets/b77553d8-e252-4946-903a-7a2316d9a8f4" />
