### ISSUE TITLE
Segmentation fault on OnePlus 7 Pro and Samsung Galaxy S10e

### ISSUE THREAD

**Issue by Leander250** [google/mediapipe#2705]
- Have I written custom code?:
No, i used the android facemesh example in the mediapipe repo: 
https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions

- OS Platform and Distribution:
Build on Win 10 19042.1237

- Mobile device:
Executed on OnePlus 7 Pro with Android 11. Reproduced on Samsung Galaxy S10e

- [MediaPipe version](https://github.com/google/mediapipe/releases):
v0.8.8

- Bazel version (if compiling from source):
3.7.2

- Solution:
FaceMesh

- Android Studio, NDK, SDK versions:
SDK Version: 30

**Describe the current behavior:**
When using the OnePlus 7 Pro or the Samsung Galaxy S10e a segmentation fault occurs and the app will be closed or the screen freezes, after clicking on "Start Camera", with the following error:
`A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x6ddb5bb998 in tid 1837 (Thread-8), pid 3843 (e.apps.facemesh)`

This does not happen on my Xiaomi Mi Mix 2 under the same conditions.

**Describe the expected behavior:**
FaceMesh can be used without crashing

**Standalone code to reproduce the issue:**
https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions

**Other info / Complete Logs :**
I added the complete debug log and parts of the logcat log as attachments (The logact log contains a more detailed error message):

[logcat.txt](https://github.com/google/mediapipe/files/7397430/logcat.txt)
[log.txt](https://github.com/google/mediapipe/files/7397120/log.txt)

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2604#issuecomment-961309080

**Comment by sgowroji** [comment]
Hi @Leander250, Duplicate #2604 Is fixed in the latest release. Could you please verify the above issue with latest release.

**Comment by Leander250** [comment]
I tried it a few times with the latest Version (commit: cf101e62) and it seems to work now.
