### ISSUE TITLE
Extracting face pose transformation matrix in FaceMesh

### ISSUE THREAD

**Issue by sygi** [google/mediapipe#2707]
I am using FaceMesh in combination with [the python colab](https://colab.research.google.com/drive/1FCxIsJS9i58uAsgsLFqDwFmiPO14Z2Hd). I successfully managed to extract landmark points on a custom face photo. I would now like to transform the landmarks back to the [canonical face model](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model.fbx) (to transfer to other faces).

**Describe the expected behavior:**
I would like to get the matrix transforming from the custom face coordinates to the canonical one, such that if I apply the matrix transformation to the landmarks I found I would get vertex positions P. When moved the vertices in the canonical face model mesh to these positions, the canonical face should show the same pose as the custom face.

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): unrelated, Debian Linux
- [MediaPipe version](https://github.com/google/mediapipe/releases): using mediapipe-0.8.8.1-cp37-cp37m-manylinux_2_17_x86_64 build.
- Bazel version: unrelated, I don't know.
- Solution (e.g. FaceMesh, Pose, Holistic): FaceMesh
- Programming Language and version ( e.g. C++, Python, Java): python

**Comment by sgowroji** [comment]
Hi @sygi, In Python it need huge coding  and we don't have any plans as of now.

**Comment by ianni67** [comment]
Hello @sygi , I guess that the answer you're looking for might be in [this post](https://github.com/google/mediapipe/issues/1642#issuecomment-795804710). I already discussed this issue (for the C++ implementation) with @kostyaby. You'll find more interesting issues in the same thread.
