### ISSUE TITLE
 Mediapipe Commercial Use - License info Display

### ISSUE THREAD

**Issue by PaulCreaserML** [google/mediapipe#2709]
1. OS WIndows10, etc

2. OS Architecture e.g. x86_64

11. Issue Details

We are planning to release a commercial product based on Mediapipe, which uses the face mesh and landmark model.

Our customer would like to provide a read me page, with info concerning the third party open source libraries, OpenCV etc… used in the commercial application.

One idea is to simply take the Mediapipe license ( Apache) found in GitHub and copy it into the third party license info page. We are thinking of putting the Mediapipe name, followed by version number and license into the page.

Is there a best practice for this.

**Comment by sgowroji** [comment]
Hi @PaulCreaserML , This https://github.com/google/mediapipe/issues/1290#issuecomment-727150276 will answer your query better.  Thanks!
