### ISSUE TITLE
Pose Estimation without Face Detection

### ISSUE THREAD

**Issue by shukkkur** [google/mediapipe#2713]
**System information**

- Programming language : Python

Currently if the mediapipe pose estimation can't detect the face, the whole detection fails. It would be nice to have a detection model that tries to detect only the body.

**use cases for this feature:**
I am currently working on a workout-counter project, so whenever the barbell covers the face the detection fails and it least to more false negatives result (counter doesn't count the rep) 
Similar problem is with the bench press
![image](https://user-images.githubusercontent.com/78250180/138808200-43380f13-aa6c-4c04-be1a-8e23faa35e51.png)

**Comment by patrick508** [comment]
Bump. @shukkkur did you ever manage to do this? We use MediaPipe with Unity, but are also wondering if we can somehow remove face from detection. We are experiences weird issues. If someone is standing still, and rotates only their head to the side, coordinates for the shoulders(which we use to detect the angle) also change. We are hoping that by removing face from detection this should perhaps be better.

**Comment by shukkkur** [comment]
@patrick508 Hey there! Nah, unfortunately I couldn't find anything. 
I am still sure that the idea of removing head from detection should improve the accuracy overall. 
In case you find anything, keep us posted!  
😄

**Comment by mcdonasd1212** [comment]
@shukkkur @patrick508  I was thinking that removing the face might improve performance.

**Comment by kuaashish** [comment]
Hello @shukkkur,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by shukkkur** [comment]
The issue is not resolved and quite unfortunate that none of the developers got to see it before it is closed. Now definitely no one is gonna solve it.
