### ISSUE TITLE
About MediaPipe HandsTracker , Swift  IOS APP, Where and How to configure the three parameters ,"max_num_hands, min_detection_condition and min_detection_condition".

### ISSUE THREAD

**Issue by xiaoxiaohan1993** [google/mediapipe#2714]
let tracker: HandTracker = HandTracker()!

tracker.startGraph()
tracker.delegate = self

tracker.processVideoFrame(CVBuffer)

func handTracker(_ handTracker: HandTracker!,
 　　　　　　　　　　didOutputLandmarks landmarks: [Landmark]!) {
}
func handTracker(_ handTracker: HandTracker!,
　　　　　　　　　　 didOutputPixelBuffer pixelBuffer: CVPixelBuffer!) {
}

**Comment by sgowroji** [comment]
You can check the code for Max_num_hands from here https://github.com/google/mediapipe/blob/master/mediapipe/examples/ios/handtrackinggpu/HandTrackingViewController.mm#:~:text=//%20Max%20number%20of,int%20kNumHands%20%3D%202%3B and other you can try changes in the respective Hands graph.

**Comment by yujinnee** [comment]
@xiaoxiaohan1993  Could you share your iOS project file which has prebuilt handtracker framework for me?
