### ISSUE TITLE
Building Android Apk fail

### ISSUE THREAD

**Issue by taatiq882** [google/mediapipe#2716]
![Screenshot from 2021-10-26 16-43-05](https://user-images.githubusercontent.com/30371302/138903084-120b1722-d55d-4662-b056-1abd724bbd50.png)
**Running setup_opencv.s**h
![Screenshot from 2021-10-26 16-49-07](https://user-images.githubusercontent.com/30371302/138904158-ff9629be-a668-42a0-90f9-17ba569eb5d4.png)

![Screenshot from 2021-10-26 15-57-35](https://user-images.githubusercontent.com/30371302/138894253-0eb16482-d853-42e0-80b2-0afb22bc7e3c.png)

![Screenshot from 2021-10-26 15-59-28](https://user-images.githubusercontent.com/30371302/138894571-2c2c7985-2bf7-4b51-aa03-78e890a87c2f.png)
**Already Done with this :-**
export ANDROID_HOME=/home/tatiq/Android/Sdk
export ANDROID_NDK_HOME=/home/tatiq/Android/Sdk/ndk/21.4.7075529

**Comment by sgowroji** [comment]
Hi @taatiq882, If you are looking for Hand solutions in android you can use the same with gradle api  from [here](https://google.github.io/mediapipe/getting_started/android_solutions.html) if you still face error in building the hand solutions in android.
