### ISSUE TITLE
How to get per joint's confidence value in pose estimation?

### ISSUE THREAD

**Issue by Frank-Dz** [google/mediapipe#2718]
How can we get per joint's confidence value in pose estimation?
e.g., [x,y,c] for each joint.

**Comment by soshishimada** [comment]
Any update here? I'm aware MediaPipe returns the confidence value for a whole pose.
But I also wanna obtain "per joint" confidence value for hand poses, i.e., different confidence values for each 21 joint.

**Comment by kuaashish** [comment]
Hello @Frank-Dz,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
