### ISSUE TITLE
Issue with Bazel for ONOS

### ISSUE THREAD

**Issue by Tomasz158** [google/mediapipe#272]
I have the following issue when I try to build ONOS. Lab environment on RHEL installed on a Hyper-V host.
![error](https://user-images.githubusercontent.com/48249316/69588294-69cb9380-0fe8-11ea-95ca-a31a80547078.jpg)

**Comment by jiuqiant** [comment]
I am not sure what ONOS is and how it is related to MediaPipe. Moreover, RHEL is not a Linux distribution that MediaPipe officially support. It's also unclear to me that why Bazel pulls in go_sdk for MediaPipe on RHEL. It would be better to file this issue to the Bazel repo (https://github.com/bazelbuild/bazel).
