### ISSUE TITLE
template_matching for ios

### ISSUE THREAD

**Issue by mpost** [google/mediapipe#2720]
The matrix on the README currently states that the template_matching using KNIFT is available on Android only. Is this because there is no example for it on iOS is yet or because it is not possible on iOS? In any case is there a plan to support iOS?

**Comment by jianingwei** [comment]
It is possible on iOS. But we don't have an example for iOS.

**Comment by mpost** [comment]
Thanks for the answer. Good to hear that it would work on iOS as well. Hope to see an example soon as well.

**Comment by dandingol03** [comment]
> Thanks for the answer. Good to hear that it would work on iOS as well. Hope to see an example soon.

HI, @mpost. The matrix you mentioned above is the pose matrix of object? I can't figure out how to get the pose matrix of object from the solution KNIFT. Can you give me some idea if possible~ Thanks in advance.
