### ISSUE TITLE
Mediapipe installation isssue

### ISSUE THREAD

**Issue by monit-org** [google/mediapipe#2722]
Hi, I'm trying to install mediapipe on ubuntu 20.04, through compiling and creating wheel (linux_aarch64.whl). 
However I'm getting this error while compiling :

ERROR: /home/muhammad/mediapipe/mediapipe/calculators/image/BUILD:691:11: Compiling mediapipe/calculators/image/affine_transformation_runner_opencv.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 67 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/image/affine_transformation_runner_opencv.cc: In member function 'virtual absl::lts_20210324::StatusOr<mediapipe::ImageFrame> mediapipe::{anonymous}::OpenCvRunner::Run(const mediapipe::ImageFrame&, const std::array<float, 16>&, const mediapipe::AffineTransformation::Size&, mediapipe::AffineTransformation::BorderMode)':
mediapipe/calculators/image/affine_transformation_runner_opencv.cc:148:12: error: could not convert 'out_image' from 'mediapipe::ImageFrame' to 'absl::lts_20210324::StatusOr<mediapipe::ImageFrame>'
     return out_image;
            ^~~~~~~~~
Target //mediapipe/modules/holistic_landmark:holistic_landmark_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.

After a little bit of research, I found out that, I have to replace 'return out_image;' but don't know the correct phrase to replace it.

**Comment by przemoch-dev** [comment]
I have the same issue building from master on Jetson Xavier NX - Ubuntu 18.04

@monit-org did you resolve it yet?

**Comment by monit-org** [comment]
No. I'm still waiting for the response. Checking every day that I'll get any answer.

**Comment by jiuqiant** [comment]
Similar to the explanation and the solution described in https://github.com/google/mediapipe/issues/1733#issuecomment-828661652, you probably want to upgrade the gcc version.

**Comment by przemoch-dev** [comment]
@monit-org which version did you try to build? I had this issue on master, but was able to build it when checkout to 0.8.4. Now I face some other error, but the compilation passed

**Comment by YU1070** [comment]
return absl::StatusOr<mediapipe::ImageFrame> ( mediapipe::ImageFrame(std::move(out_image)));

**Comment by YU1070** [comment]
return absl::StatusOr<mediapipe::ImageFrame> ( mediapipe::ImageFrame(std::move(out_image)));

**Comment by YU1070** [comment]
return absl::StatusOr<mediapipe::ImageFrame> ( mediapipe::ImageFrame(std::move(out_image)));

**Comment by six7pro** [comment]
return absl::StatusOr<mediapipe::ImageFrame> ( mediapipe::ImageFrame(std::move(out_image))); 

Its work for me
