### ISSUE TITLE
Bazel build for x86 target

### ISSUE THREAD

**Issue by edgar-bcn** [google/mediapipe#2723]
Hi,

I would like to compile a MediaPipe solution with Bazel for Windows x86 (32-bit).

I've successfully compiled Bazel samples simply adding --cpu=x64_x86_windows, but when trying the same thing with a MediaPipe solution I get the following error:
ERROR: Error fetching repository: java.io.IOException: The repository's path is "/usr" (absolute: "/usr") but this directory does not exist.
ERROR: C:/users/edgar/documents/mediapipe/third_party/BUILD:186:6: //third_party:opencv_binary depends on @linux_opencv//:opencv in repository @linux_opencv which failed to fetch. no such package '@linux_opencv//': The repository's path is "/usr" (absolute: "/usr") but this directory does not exist.

Thanks in advance,
Edgar

**Comment by sgowroji** [comment]
Hi @edgar-bcn, Could you please confirm your opencv is installed and properly setup in the machine. Can you try doing the https://github.com/google/mediapipe/blob/master/setup_opencv.sh and verify the above steps . Logs shows issues of opencv not properly setup.

**Comment by edgar-bcn** [comment]
> Hi @edgar-bcn, Could you please confirm your opencv is installed and properly setup in the machine. Can you try doing the https://github.com/google/mediapipe/blob/master/setup_opencv.sh and verify the above steps . Logs shows issues of opencv not properly setup.

But I'm running MediaPipe on Windows not WSL.

I installed x86 version of OpenCV (and change PATH according) but nothing.

**Comment by edgar-bcn** [comment]
The problem is when running build with --cpu=x64_x86_windows option parameter it goes to the default local repository as shown below.

1. Extract from mediapipe\third-party\BUILD:

alias(
    name = "opencv_binary",
    actual = select({
        "//mediapipe:android_x86": "@android_opencv//:libopencv_x86",
        "//mediapipe:android_x86_64": "@android_opencv//:libopencv_x86_64",
        "//mediapipe:android_armeabi": "@android_opencv//:libopencv_armeabi-v7a",
        "//mediapipe:android_arm": "@android_opencv//:libopencv_armeabi-v7a",
        "//mediapipe:android_arm64": "@android_opencv//:libopencv_arm64-v8a",
        "//mediapipe:ios": "@ios_opencv//:opencv",
        "//mediapipe:macos": "@macos_opencv//:opencv",
        "//mediapipe:windows": "@windows_opencv//:opencv",
        "//conditions:default": "@linux_opencv//:opencv", **<--- GOES HERE**
    }),
)

2. Extract from mediapipe\WORKSPACE:

new_local_repository(
    name = "linux_opencv",
    build_file = "@//third_party:opencv_linux.BUILD",
    path = "/usr", **<--- THIS DIRECTORY DOES NOT EXIST ON WIJNDOWS INSTALLATION**
)

**Comment by xfj81525** [comment]
does any one successfully compile mediapipe for x86 ?

**Comment by xfj81525** [comment]
hi @edgar-bcn, did you successfully compile mediapipe for x86 now? would you like to share your experience? thanks in advance

**Comment by kuaashish** [comment]
Hello @edgar-bcn,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
