### ISSUE TITLE
Feature Request: Hand Segmentation

### ISSUE THREAD

**Issue by flobaader** [google/mediapipe#2724]
**System information**

- MediaPipe Solution: Hands
- Programming language : Python
- Are you willing to contribute it: No

**Describe the feature and the current behavior/state:**
I would be awesome if the hands solution would feature an segmentation like recenlty implemented in the pose tracking.

**Will this change the current api? How?**
Probably a new parameter called `enable_segmentation ` for the hand model.

**Who will benefit with this feature?**
Everyone that wants to have the border of the hands.

**Please specify the use cases for this feature:**
We want to do hand size measurements and therefore need to know the border of the hand and not only the landmarks.

**Any Other info:**

**Comment by hadi1376tm** [comment]
Yes that would be very useful.

**Comment by kuaashish** [comment]
@flobaader,

Pose Landmarker for MP Tasks contains segmentation mask.

**Comment by PaulDDD** [comment]
This would indeed be useful.

**Comment by ShonubiSamuel** [comment]
Yeah, a Hand Segmentation would be very much appreciated.
