### ISSUE TITLE
FaceMesh web demo got errors on Mac Safari

### ISSUE THREAD

**Issue by tomleader** [google/mediapipe#2725]
The facemesh demo url: 
https://codepen.io/mediapipe/pen/KKgVaPJ

my Env: Macbook pro M1(Big Sur 11.4), Safari 14.1.1

When use Safari, errors occur.
1. If I use the default options(refine_landmarks==false), the landmarks on the canvas are on the wrong position,
which means the program itself runs ok, but the output is not right.

2. If I use the default options(refine_landmarks==true), the demo stop working, and I check the log on console:
```
"=== Source Location Trace: === "
"third_party/mediapipe/framework/tool/status_util.cc:139"
""
"F1028 16:49:32.031000       1 solutions_wasm.embind.cc:679] Check failed: absl::OkStatus() == ::util::status_internal::AsStatus((graph_->WaitUntilIdle())) (OK vs. NOT_FOUND: CalculatorGraph::Run() failed in Run: "
"Calculator::Open() for node 'facelandmarkfrontgpu__facelandmarkgpu__inferencecalculator__facelandmarkfrontgpu__facelandmarkgpu__InferenceCalculator' failed: Can not find ( bracket in for loop. [type.googleapis.com/mediapipe.StatusList='\n\xc5\x01\x08\x05\x12\xc0\x01\x43\x61lculator::Open() for node \'facelandmarkfrontgpu__facelandmarkgpu__inferencecalculator__facelandmarkfrontgpu__facelandmarkgpu__InferenceCalculator\' failed: Can not find ( bracket in for loop.']"
"=== Source Location Trace: === "
"third_party/mediapipe/framework/tool/status_util.cc:139"
") "
"*** Check failure stack trace: ***"
"undefined"
```

I think maybe there are some bugs in the wasm file? (brackets missing?)

ps:
The demo runs quite well on Chrome(94).
The demo runs quite well on my iPhone(13) Safari.
I know that the webGL version fallback to 1.0 on safari.

**Comment by mhays-google** [comment]
I will bring this up to the team.  I'm assuming this it the new face_mesh enhancements that just went out a week ago, and that previous versions did work.

**Comment by JamesGrom** [comment]
I'm getting the same error... for safari on mac
![IMG_4392](https://user-images.githubusercontent.com/53055317/144688241-106d62e6-91a9-4b3b-b793-f52c66a4ebd6.jpeg)

**Comment by mhays-google** [comment]
I know that the team wanted to work on getting this on Safari in general, but to my knowledge, there is no short term plan.  I think it came down to support for WebGL.  I apologize for that inconvenience.

**Comment by tyrmullen** [comment]
FWIW, the facemesh demo seems to run fine on Desktop Safari for me (both with and without refine_landmarks).  I'm using Safari Version 15.1 (16612.2.9.1.30, 16612) on a MacBook Pro (Big Sur 11.6.1).  So perhaps try updating your Safari and see if the issue is resolved?

**Comment by ekrausso** [comment]
Does not work for me on Safari 15.5 on a Mac mini (M1, 2020).... I get the 'is not well supported' alert.

**Comment by ekrausso** [comment]
I'm using face_mesh and camera_utils.js on a project and get this error when trying to open the camera:

"Failed to acquire camera feed: OverconstrainedError: Invalid constraint".

Only on macOS safari, works fine on iOS..

Is there any workaround or should I just ditch camera_utils? @mhays-google
