### ISSUE TITLE
Accept the Webcodec VideoFrame interface

### ISSUE THREAD

**Issue by aankur** [google/mediapipe#2726]
Hi,
This is regarding the videoframe interface. 
https://w3c.github.io/webcodecs/#videoframe-interface
https://web.dev/mediastreamtrack-insertable-media-processing/

Currently faceDetection.send({image: videoElement});

Or similar javascript api does not accept video frame directly.

It would be good to have. 

**System information** (Please provide as much relevant information as possible)
Chrome 94 on supported OS

- MediaPipe Solution (you are using):
Face detection,  javascript,  chrome browser
- Programming language 
javascript,  browser
- Are you willing to contribute it (Yes/No): Do not know how to. Willing to.

**Describe the feature and the current behavior/state:**
Send currently accepts canvas, image and video
**Will this change the current api? How?**
Yes, api will now accept videoframe
**Who will benefit with this feature?**
Anyone using the Mediastream insertable streams API
**Please specify the use cases for this feature:**
Natively support Mediastream insertable streams API

**Comment by mhays-google** [comment]
What does "video frame directly" mean to you?

**Comment by aankur** [comment]
Please See this hands demo, with the MediaStream Insertable Streams API, 
" VideoFrame is a CanvasImageSource. A VideoFrame can be passed to any method accepting a CanvasImageSource"
it would be great to use this directly rather than have to draw it on a canvas first,
this is applicable to all javascript supported solutions

```html
<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils/camera_utils.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils/control_utils.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/drawing_utils.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands.js" crossorigin="anonymous"></script>

</head>
<body>

<button onClick='demostart()'>demostart</button>
<video id='video-after' autoPlay></video>

<script>
  let globalController = null;
  let timestamp = null;
  let stream = null;
  let canvasElement2 = null;
  let canvasCtx2 = null;

  const hands = new Hands({locateFile: (file) => {
    return `https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`;
  }});

  hands.setOptions({
    maxNumHands: 2,
    modelComplexity: 1,
    minDetectionConfidence: 0.5,
    minTrackingConfidence: 0.5
  });

  function onResults (results) {
    if (!canvasCtx2) {
      return;
    }
    canvasElement2.width = results.image.width;
    canvasElement2.height = results.image.height;
    canvasCtx2.save();
    canvasCtx2.clearRect(0, 0, canvasElement2.width, canvasElement2.height);
    canvasCtx2.drawImage(
      results.image, 0, 0, canvasElement2.width, canvasElement2.height);
    if (results.multiHandLandmarks) {
      for (const landmarks of results.multiHandLandmarks) {
        drawConnectors(canvasCtx2, landmarks, HAND_CONNECTIONS,
          {color: '#00FF00', lineWidth: 5});
        drawLandmarks(canvasCtx2, landmarks, {color: '#FF0000', lineWidth: 2});
      }
    }
    canvasCtx2.restore();
    globalController.enqueue(new VideoFrame(canvasElement2, { timestamp, alpha: 'discard' }));
  }

  hands.onResults(onResults);
  hands.initialize();

  async function demostart () {
    canvasElement2 = new OffscreenCanvas(1280, 720);
    canvasCtx2 = canvasElement2.getContext('2d');
    const canvasElement = new OffscreenCanvas(1280, 720);
    const canvasCtx = canvasElement.getContext('2d');
    stream = await navigator.mediaDevices.getUserMedia({ video: { width: 1280 } });
    const videoTrack = stream.getVideoTracks()[0];
    const trackProcessor = new MediaStreamTrackProcessor({ track: videoTrack });
    const trackGenerator = new MediaStreamTrackGenerator({ kind: 'video' });

    const transformer = new TransformStream({
      async transform (videoFrame, controller) {
        const width = videoFrame.displayWidth;
        const height = videoFrame.displayHeight;
        canvasElement.width = width;
        canvasElement.height = height;
        canvasCtx.drawImage(videoFrame, 0, 0);
        timestamp = videoFrame.timestamp;
        globalController = controller;
        await hands.send({ image: canvasElement }); // using videoFrame does not work, have to draw it on to a canvas first
        // would be good to have results as a response to async .send, instead a callback
        videoFrame.close();
      },
    });

    trackProcessor.readable.pipeThrough(transformer).pipeTo(trackGenerator.writable);
    
    const videoAfter = document.getElementById('video-after');
    const streamAfter = new MediaStream([trackGenerator]);
    videoAfter.srcObject = streamAfter;
  }
</script>
</body>
</html>

```

**Comment by tyrmullen** [comment]
VideoFrame may be a CanvasImageSource, but that doesn't mean it can be used as a texture source for a WebGLRenderingContext (and I believe it can't, although I haven't tried it yet myself).  Try videoFrame.createImageBitmap() instead.

**Comment by aankur** [comment]
Hi,
videoFrame.createImageBitmap is not a function

**Comment by aankur** [comment]
Hi,
As per the sample implementation here, it looks to be used in a webgl context directly.
https://github.com/webrtc/samples/blob/gh-pages/src/content/insertable-streams/video-processing/js/webgl-transform.js#L185

for Chrome 90+

**Comment by tyrmullen** [comment]
That's even better then!  I didn't see that capability mentioned in the [W3 specs](https://www.w3.org/TR/webcodecs/), but if it can be used for texImage2d, then you should be able to just pass the VideoFrame through directly.  Just add and fill in a "width" and "height" field to your VideoFrame, and cast it as ImageBitmap if you need to (i.e. if TS compiler complains), and then send it directly in the .send() call.

**Comment by aankur** [comment]
Hi,
That worked, supplied custom (width, height) property to videoFrame. 
so for chrome version <=90 use videoFrame.createImageBitmap()
and chrome 90+ use videoFrame but add width, height to the object

**Comment by batbrain9392** [comment]
Is there no way we can make this solution from @tyrmullen official?

> That's even better then! I didn't see that capability mentioned in the [W3 specs](https://www.w3.org/TR/webcodecs/), but if it can be used for texImage2d, then you should be able to just pass the VideoFrame through directly. Just add and fill in a "width" and "height" field to your VideoFrame, and cast it as ImageBitmap if you need to (i.e. if TS compiler complains), and then send it directly in the .send() call.

**Comment by batbrain9392** [comment]
So instead of `await selfieSegmentation.send({ image: { ...videoFrame, height, width } });`, we have to use
```js
videoFrame.width = videoFrame.displayWidth;
videoFrame.height = videoFrame.displayHeight;
await selfieSegmentation.send({ image: videoFrame });
```
