### ISSUE TITLE
why cannot send many pictures in version 0.8.8.1 or later

### ISSUE THREAD

**Issue by wangzi815** [google/mediapipe#2728]
when i send many pictures,only get 2 handresult in version 0.8.8.1 or later？in other version such as 0.8.7.1,when i send many pictures,eg 100,i can get 100 handresult. my code as below:
                            for (int i = 0; i < jpgfileList.size(); i++) {
                              String aa = "" + jpgfileList.get(i);
                              //System.out.println(aa);
                              try {
                                FileInputStream fis = new FileInputStream(aa);
                                bitmap = BitmapFactory.decodeStream(fis);
                              } catch (IOException e) {
                                Log.e(TAG, "Bitmap reading error:" + e);
                              }
                              hands.send(bitmap);
                            }
when i add sleep(100) after hands.send(bitmap),i can get more result.when i add sleep(300) after hands.send(bitmap),i can get more more result.

**Comment by wangzi815** [comment]
> Hi @wangzi815 , What is the error seen when you are trying to send more images in the latest version?

no error,eg:i input 100 bitmaps,but get only 2 hand result ,later,no other result output..v0.8.7 has no such problem.

**Comment by wangzi815** [comment]
the probblem only produce on the platform android,not on python.

**Comment by sgowroji** [comment]
Hi @wangzi815, FlowLimiterCalculator does drop images during processing. And it is intended for new release.
