### ISSUE TITLE
For the android solution, provide a method to load tflite models from the file system instead of directly loading from Android assets in C++

### ISSUE THREAD

**Issue by liuguicen** [google/mediapipe#2729]
Thank you for your work！
For the android solution,  can you provide a way to load the model from a file system instead of directly loading it from the asset in C++. 
Because in this way, developers can download the model through the server  when the user needs it. If packaging model into the apk, this will significantly increase the size of the package and affect the user experience.

**Comment by kuaashish** [comment]
Hello @liuguicen,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
