### ISSUE TITLE
How can Mediapipe work on windows system?

### ISSUE THREAD

**Issue by mrpanrp** [google/mediapipe#273]
I'm trying to create a Android Studio project using the handtracking feature on Wins, How may I actually do it?

**Comment by mgyong** [comment]
@mrpanrp We have released [MediaPipe on Windows](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows) with [v0.7.5](https://github.com/google/mediapipe/releases/tag/v0.7.5)
Please check it out and give us feedback
