### ISSUE TITLE
Failed to read file third_party/mediapipe/modules/hand_landmark/hand_landmark_full.tflite

### ISSUE THREAD

**Issue by Julianvaldesv** [google/mediapipe#2731]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
Windows 10
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
- Programming Language and version ( e.g. C++, Python, Java):
JavaScript 
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ):
HandPose MediaPipe. 

**Describe the current behavior:**
![image](https://user-images.githubusercontent.com/67173697/139495078-072f0c9d-933d-4264-93b5-762270a44472.png)

**Describe the expected behavior:**
It was working perfectly a few days ago. 

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:
![image](https://user-images.githubusercontent.com/67173697/139495217-e6eeb1ae-73ff-49af-ac0c-3349d42d4309.png)
![image](https://user-images.githubusercontent.com/67173697/139495302-1ce60df8-f286-4bdf-a35f-86619ce9a9c0.png)

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached
![image](https://user-images.githubusercontent.com/67173697/139495386-1a81785e-975e-4763-9580-0450eb445b68.png)

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2708 . Please have a look at the resolution provided in it.

**Comment by Julianvaldesv** [comment]
It's fixed now.

Thanks for your help.
