### ISSUE TITLE
python3.10.0

### ISSUE THREAD

**Issue by eng-psycho** [google/mediapipe#2732]
I'm using python version : 3.10.0
but when i  tried to install mediapipe .. I got this error:
```
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe

```

**Comment by sgowroji** [comment]
Hi @eng-psycho, Python 3.10 is not supported by Mediapipe yet. Please use Python 3.7 to 3.9. Thanks!

**Comment by sgowroji** [comment]
Python 3.10 is now officially supported https://github.com/google/mediapipe/issues/2884#issuecomment-993043516
