### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by ultralegendary** [google/mediapipe#2733]
# face mesh landmark points
is there a landmark map for face mesh?. 
coz i want the 468 points mapping of face
here is the mapping for hand which is found in the website: https://google.github.io/mediapipe/images/mobile/hand_landmarks.png
like this, I want the mapping for face. Tried search no lead :(.

**Comment by sgowroji** [comment]
Hi @ultralegendary, Are you looking for this https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png

**Comment by ultralegendary** [comment]
exactly!
thank you @sgowroji
