### ISSUE TITLE
Selfie segmentation: filter out persons in background

### ISSUE THREAD

**Issue by spflueger** [google/mediapipe#2734]
Hi all,
first of all thanks for open sourcing these useful packages and pre-trained models

<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): selfie segmentation
- Programming language : python
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state:**
I'm would like to detect and filter out people in the background of the selfie segmentation, so that only the person doing a video call is detected. Currently the model detects everyone in the picture.

**Will this change the current api? How?**
Either new model which would be selectable or some filter which which runs some optional post processing code.

**Who will benefit with this feature?**
Everyone who wants video conferencing with background person filtering

**Please specify the use cases for this feature:**
Video conferencing without detecting ppl in the background.

**Any Other info:**

**Comment by sureshdagooglecom** [comment]
Hi @spflueger ,
If multiple person with similar scale will be present then it will detect some/all faces as per this [document](https://drive.google.com/file/d/1dCfozqknMa068vVsO2j_1FgZkW_e3VWv/preview).

**Comment by Payetus** [comment]
I am interested in this issue also.
