### ISSUE TITLE
mediapipe js how to upload and download pre-recorded video 

### ISSUE THREAD

**Issue by AlexeiKaplenko** [google/mediapipe#2735]
- MediaPipe Solution: Hands, Pose, Face-mesh
- Programming language : typescript, javascript

1)How can I upload a video without using SourcePicker from the controls panel and then process it using mediapipe js solutions?
2)How can I download pre-recorded video after processing? If I understood correctly each frame is processed independently and rendered on canvas. I can't find a solution how to combine frames into a video using code from codepen (controls.SourcePicker class).

**Comment by sgowroji** [comment]
Hi @AlexeiKaplenko, Have you tried checking our [codepen examples ](https://codepen.io/mediapipe) in MediaPipe. You can upload a video from the control options. Thanks!

**Comment by AlexeiKaplenko** [comment]
@sgowroji, I did try what you proposed  [#2485 (comment)](URL). The problem with this approach was that mediapipe processing speed is slower than video framerate (60 fps in my case). Thus using media recorder results in missing frames in the output video. Currently, I am using a hack to pause the original video while mediapipe processes the current frame, and then it starts playing  video again, the procedure repeats for each frame. Link to my code
[](https://gist.github.com/AlexeiKaplenko/0c588e9c72be2106b72d4e74af6637d0)
This approach produces video with 8 fps. I can increase the frame rate in the browser by adjusting video.playbackRate to match the original video fps. However, blob object created from recorded chunks produces video with 8 fps after downloading video file (it looks like video in slow motion). 
1) Is there a more elegant way to use mediapipe and process each video frame without pausing the video for every single frame? 
2) How can I change the final downloaded video frame rate without sending it to the server?

**Comment by tyrmullen** [comment]
On my laptop, I've found that Chrome usually caps any video to 30FPS max (60FPS is the display refresh rate, but not the movie framerate-- you can use "requestVideoFrameCallback" to better distinguish, or check the video.currentTime to ensure it's progressed).
1.  Unfortunately, playing a video frame-by-frame has long been an asked-for browser feature, but I know of no API for it; usually something like what you suggest (pause and play, ensuring single-frame advancement) seems to be the generally accepted approach.  The requestVideoFrameCallback approach at least gives you a [presentedFrames](https://wicg.github.io/video-rvfc/#dom-videoframemetadata-presentedframes) property too, though, so you can easily see if any frames were accidentally skipped.
2.  Are you using MediaRecorder with some timeout interval, or manually specifying when data is captured via ".requestData()"?  I'd assume with the latter your video should be saved at least at a reasonable ~30fps rate (so maybe 2x slowdown if your input video is 60fps).  It looks like you can specify videoBitsPerSecond and audioBitsPerSecond in the MediaRecorderOptions, so I'd assume that'd be how you'd speed things up or slow them down, but I've never needed to use those options, so I can't vouch for any of this (this is well outside of the MediaPipe domain).
