### ISSUE TITLE
Correcting Pose Estimation for specific Poses/Movements.

### ISSUE THREAD

**Issue by LT93L0** [google/mediapipe#2736]
Hi!
While using Mediapipe for Pose Estimation I found that some of the poses are not precisely detected. I would like to detect Folk dancing motives and sometimes Mediapipe estimates the move badly or doesn't even see it. 
So my question is that: Is there a way to correct these miss calculated moves with my own dataset of folk dancing? Is there a way to teach the algorithm further so it would find all the hand and leg movements perfectly?

**Comment by sgowroji** [comment]
Hi @LT93L0, Could you please point us the badly effected output with video recording or images to understand the issue much better. Thanks!

**Comment by LT93L0** [comment]
Sure I will send you. But I just want to know that is there a way to make some of the estimations more precise with my own dataset?

**Comment by sgowroji** [comment]
Not actually from here https://github.com/google/mediapipe/issues/1322#issuecomment-732418934.
