### ISSUE TITLE
mediapipe processing video on iOS have big memory(but not leak) when maxFramesInFlight is 0 default

### ISSUE THREAD

**Issue by czy2014hust** [google/mediapipe#2738]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): iOS 15
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
- Programming Language and version ( e.g. C++, Python, Java):
- [MediaPipe version](https://github.com/google/mediapipe/releases): lastest
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ):
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
- Xcode & Tulsi version (if issue is related to building for iOS): 13.1

**Describe the current behavior:**
```c
use AVAssetImageGenerator on iOS to generate frames
[generator generateCGImagesAsynchronouslyForTimes:frames_list completionHandler:^(CMTime requestedTime, CGImageRef  _Nullable image, CMTime actualTime, AVAssetImageGeneratorResult result, NSError * _Nullable error) {
    if(result == AVAssetImageGeneratorFailed || !image || error) {
      NSLog(@"%@", error.localizedDescription);
      return;
    }
    CFHolder<CVPixelBufferRef> inputBuffer;
    CreateCVPixelBufferFromCGImage(image, &inputBuffer);
    [self processVideoFrame:*inputBuffer timestamp:requestedTime fromSource:self.videoSource];
    CMTime lastTime = [values.lastObject CMTimeValue];
    if(CMTimeCompare(lastTime, requestedTime) == 0){
      NSError* closeerror;
      BOOL isclose = [self.mediapipeGraph closeAllInputStreamsWithError:&closeerror];
      if(isclose){
        NSLog(@"close all input stream\n");
      }else{
        NSLog(@"%@", closeerror);
      }
    }
    
  }];
```

**Describe the expected behavior:**
The memory will up to hundreds MB, when maxFramesInFlight is 0 default(I think this is normal), BUT KEPP the max memory(not realse) even close input_stream, and after mediapipe graph Run() done.

 If set mediapipe graph to nil afte the graph Run done, the memory look like normal(dozens MB), but I do not want to release the mediapipe graph. 

Profiling the app with Xcode instruments, it look like the `CVPixelBufferCreate` alloc the big memory, but not realse as soon as the this frame process is done.

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

**Comment by kuaashish** [comment]
Hello @czy2014hust,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
