### ISSUE TITLE
Error while making Hand Tracking module

### ISSUE THREAD

**Issue by 3bdo7ss** [google/mediapipe#2739]
Hi I have this problem while I'm making Hand Tracking module
Windows 10

code:

`

    import cv2
    import mediapipe as mp
    import time
    
    
    class handDetector():
        def __init__(self, mode=False, maxHands=2, detectioncon=0.5, trackcon=0.5):
            self.mode = mode
            self.maxHands = maxHands
            self.detectioncon = detectioncon
            self.trackcon = trackcon
    
            self.mpHands = mp.solutions.hands
            self.hands = self.mpHands.Hands(self.mode, self.maxHands, self.detectioncon, self.trackcon)
            self.mpDraw = mp.solutions.drawing_utils
    
        def findHands(self, img, draw=True):
    
            imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            results = self.hands.process(imgRGB)
    
            if results.multi_hand_landmarks:
                for handlms in results.multi_hand_landmarks:
                    if draw:
                        self.mpDraw.draw_landmarks(img, handlms, self.mpHands.HAND_CONNECTIONS)
            return img
            # for id, lm in enumerate(handlms.landmark):
            #     h, w, c = img.shape
            #     cx, cy = int(lm.x * w), int(lm.y * h)
            #     print(id, cx, cy)
            #      if id == 12:
            #          cv2.putText(img, "FUCK", (cx, cy), cv2.FONT_HERSHEY_PLAIN, 3, (255, 0, 255), 3)
    
    
    def main():
        pTime = 0
        cTime = 0
        cap = cv2.VideoCapture(0)
        detector = handDetector()
        while True:
            success, img = cap.read()
            img = detector.findHands(img)
    
            cTime = time.time()
            fps = 1 / (cTime - pTime)
            pTime = cTime
    
            cv2.putText(img, str(int(fps)), (10, 70), cv2.FONT_HERSHEY_PLAIN, 3, (255, 0, 255), 3)
    
            cv2.imshow("Image", img)
    
            cv2.waitKey(1)
    
    
    if __name__ == "__main__":
        main()import cv2
    import mediapipe as mp
    import time
    
    
    class handDetector():
        def __init__(self, mode=False, maxHands=2, detectioncon=0.5, trackcon=0.5):
            self.mode = mode
            self.maxHands = maxHands
            self.detectioncon = detectioncon
            self.trackcon = trackcon
    
            self.mpHands = mp.solutions.hands
            self.hands = self.mpHands.Hands(self.mode, self.maxHands, self.detectioncon, self.trackcon)
            self.mpDraw = mp.solutions.drawing_utils
    
        def findHands(self, img, draw=True):
    
            imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            results = self.hands.process(imgRGB)
    
            if results.multi_hand_landmarks:
                for handlms in results.multi_hand_landmarks:
                    if draw:
                        self.mpDraw.draw_landmarks(img, handlms, self.mpHands.HAND_CONNECTIONS)
            return img
            # for id, lm in enumerate(handlms.landmark):
            #     h, w, c = img.shape
            #     cx, cy = int(lm.x * w), int(lm.y * h)
            #     print(id, cx, cy)
            #      if id == 12:
            #          cv2.putText(img, "FUCK", (cx, cy), cv2.FONT_HERSHEY_PLAIN, 3, (255, 0, 255), 3)
    
    
    def main():
        pTime = 0
        cTime = 0
        cap = cv2.VideoCapture(0)
        detector = handDetector()
        while True:
            success, img = cap.read()
            img = detector.findHands(img)
    
            cTime = time.time()
            fps = 1 / (cTime - pTime)
            pTime = cTime
    
            cv2.putText(img, str(int(fps)), (10, 70), cv2.FONT_HERSHEY_PLAIN, 3, (255, 0, 255), 3)
    
            cv2.imshow("Image", img)
    
            cv2.waitKey(1)
    
    
    if __name__ == "__main__":
        main()
           
    

`

Error Message:
`

    Traceback (most recent call last):
      File "C:/Users/HP/PycharmProjects/handdetection/HandTrackingModule.py", line 56, in <module>
        main()
      File "C:/Users/HP/PycharmProjects/handdetection/HandTrackingModule.py", line 39, in main
        detector = handDetector()
      File "C:/Users/HP/PycharmProjects/handdetection/HandTrackingModule.py", line 14, in __init__
        self.hands = self.mpHands.Hands(self.mode, self.maxHands, self.detectioncon, self.trackcon)
      File "C:\Users\HP\PycharmProjects\handdetection\venv\lib\site-packages\mediapipe\python\solutions\hands.py", line 114, in __init__
        super().__init__(
      File "C:\Users\HP\PycharmProjects\handdetection\venv\lib\site-packages\mediapipe\python\solution_base.py", line 258, in __init__
        self._input_side_packets = {
      File "C:\Users\HP\PycharmProjects\handdetection\venv\lib\site-packages\mediapipe\python\solution_base.py", line 259, in <dictcomp>
        name: self._make_packet(self._side_input_type_info[name], data)
      File "C:\Users\HP\PycharmProjects\handdetection\venv\lib\site-packages\mediapipe\python\solution_base.py", line 513, in _make_packet
        return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
    TypeError: create_int(): incompatible function arguments. The following argument types are supported:
        1. (arg0: int) -> mediapipe.python._framework_bindings.packet.Packet
    
    Invoked with: 0.5
    [ WARN:0] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
    
    Process finished with exit code 1

`

**Comment by Metadorius** [comment]
I have the same issue. Hands solution in MediaPipe 0.8.8.1 seems to be broken. In 0.8.8.0 the solution is working fine though. Just for the record this was tested on Python versions 3.9.7 and 3.9.1, in virtual environments.

**Comment by jiuqiant** [comment]
Because Hand's __init__ now has 5 params and the third parameter is model_complexity, which is an int. Please modify your code accordingly.

**Comment by singhania0601** [comment]
I have uploaded hand - tracking module on my github page, you can use that.
Mediapipe latest issue uses one parameter extra than the earlier model

**Comment by Reihannudin** [comment]
@singhania0601 Thank you so much , This is file work

**Comment by amulbaby420** [comment]
[ WARN:0@3.408] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "C:\Users\SURIYA\Desktop\virtualzoom\main.py", line 21, in <module>
    hands,img = detector_hand.findHands(img)
  File "C:\Users\SURIYA\AppData\Roaming\Python\Python310\site-packages\cvzone\HandTrackingModule.py", line 48, in findHands
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by HKABIG** [comment]
At the place of arguments of detectionCon and trackCon place the values in int()

**Comment by Mohammad-Alghrawe** [comment]
> I have the same issue. Hands solution in MediaPipe 0.8.8.1 seems to be broken. In 0.8.8.0 the solution is working fine though. Just for the record this was tested on Python versions 3.9.7 and 3.9.1, in virtual environments.

Thanks a lot

**Comment by bdKiron** [comment]
This is my first time here. Whenever I run this code I always get this error. I've tried many times to update different versions of OpenCV, cvzone and mediapipe.
AttributeError: module 'HandTrackingModule' has no attribute 'handDetector'

Hope someone will help me to solve this error.Thank you in advance.

import cv2
import time
import os
import HandTrackingModule as htm

wCam, hCam = 640, 480

cap = cv2.VideoCapture(1)
cap.set(3, wCam)
cap.set(4, hCam)

folderPath = "E:\\opencv tutorial\\opencv exercise\\finger detector\\FingerImages"
myList = os.listdir(folderPath)
print(myList)
overlayList = []
for imPath in myList:
    image = cv2.imread(f'{folderPath}/{imPath}')
    # print(f'{folderPath}/{imPath}')
    overlayList.append(image)

print(len(overlayList))
pTime = 0

detector = htm.handDetector(detectionCon=0.75)

tipIds = [4, 8, 12, 16, 20]

while True:
    success, img = cap.read()
    img = detector.findHands(img)
    lmList = detector.findPosition(img, draw=False)
    # print(lmList)

    if len(lmList) != 0:
        fingers = []

        # Thumb
        if lmList[tipIds[0]][1] > lmList[tipIds[0] - 1][1]:
            fingers.append(1)
        else:
            fingers.append(0)

        # 4 Fingers
        for id in range(1, 5):
            if lmList[tipIds[id]][2] < lmList[tipIds[id] - 2][2]:
                fingers.append(1)
            else:
                fingers.append(0)

        # print(fingers)
        totalFingers = fingers.count(1)
        print(totalFingers)

        h, w, c = overlayList[totalFingers - 1].shape
        img[0:h, 0:w] = overlayList[totalFingers - 1]

        cv2.rectangle(img, (20, 225), (170, 425), (0, 255, 0), cv2.FILLED)
        cv2.putText(img, str(totalFingers), (45, 375), cv2.FONT_HERSHEY_PLAIN,
                    10, (255, 0, 0), 25)

    cTime = time.time()
    fps = 1 / (cTime - pTime)
    pTime = cTime

    cv2.putText(img, f'FPS: {int(fps)}', (400, 70), cv2.FONT_HERSHEY_PLAIN,
                3, (255, 0, 0), 3)

    cv2.imshow("Image", img)
    cv2.waitKey(1)

**Comment by bunny-001** [comment]
thanks

**Comment by pranzalkhadka** [comment]
> I have uploaded hand - tracking module on my github page, you can use that. Mediapipe latest issue uses one parameter extra than the earlier model

Thanks

**Comment by jainaryan10001** [comment]
import cv2
import mediapipe as mp
import math

import mediapipe as mp

class handDetector():
    def __init__(self, mode=False, maxHands=2, detectionCon=0.5, trackCon=0.5):
        self.mode = mode
        self.maxHands = maxHands
        self.detectionCon = detectionCon
        self.trackCon = trackCon
        self.mpHands = mp.solutions.hands

        # Hands object create karte waqt arguments ko sahi parameter names do
        self.hands = self.mpHands.Hands(
            static_image_mode=self.mode,
            max_num_hands=self.maxHands,
            min_detection_confidence=self.detectionCon,
            min_tracking_confidence=self.trackCon
        )

        self.mpDraw = mp.solutions.drawing_utils
        self.tipIds = [4, 8, 12, 16, 20]

    def findHands(self, img, draw=True):

        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        self.results = self.hands.process(imgRGB)

        if self.results.multi_hand_landmarks:
            for handLms in self.results.multi_hand_landmarks:
                if draw:
                    self.mpDraw.draw_landmarks(
                        img, handLms, self.mpHands.HAND_CONNECTIONS)

        return img

    def findPosition(self, img, handNo=0, draw=True):

        xList = []
        yList = []
        bbox = []
        self.lmList = []

        if self.results.multi_hand_landmarks:

            myHand = self.results.multi_hand_landmarks[handNo]

            for id, lm in enumerate(myHand.landmark):

                h, w, c = img.shape
                cx, cy = int(lm.x * w), int(lm.y * h)

                xList.append(cx)
                yList.append(cy)

                self.lmList.append([id, cx, cy])

                if draw:
                    cv2.circle(img, (cx, cy), 5,
                               (255, 0, 255), cv2.FILLED)

            xmin, xmax = min(xList), max(xList)
            ymin, ymax = min(yList), max(yList)

            bbox = xmin, ymin, xmax, ymax

            if draw:
                cv2.rectangle(img,
                              (bbox[0]-20, bbox[1]-20),
                              (bbox[2]+20, bbox[3]+20),
                              (0,255,0),2)

        return self.lmList, bbox

    def fingersUp(self):

        fingers = []

        if self.lmList[self.tipIds[0]][1] > self.lmList[self.tipIds[0]-1][1]:
            fingers.append(1)
        else:
            fingers.append(0)

        for id in range(1,5):

            if self.lmList[self.tipIds[id]][2] < self.lmList[self.tipIds[id]-2][2]:
                fingers.append(1)
            else:
                fingers.append(0)

        return fingers

    def findDistance(self, p1, p2, img, draw=True):

        x1, y1 = self.lmList[p1][1], self.lmList[p1][2]
        x2, y2 = self.lmList[p2][1], self.lmList[p2][2]

        cx, cy = (x1+x2)//2, (y1+y2)//2

        if draw:
            cv2.circle(img,(x1,y1),15,(255,0,255),cv2.FILLED)
            cv2.circle(img,(x2,y2),15,(255,0,255),cv2.FILLED)
            cv2.line(img,(x1,y1),(x2,y2),(255,0,255),3)
            cv2.circle(img,(cx,cy),15,(255,0,255),cv2.FILLED)

        length = math.hypot(x2-x1,y2-y1)

        return length, img, [x1,y1,x2,y2,cx,cy]

######################################################## 
Backend tkagg is interactive backend. Turning interactive mode on.
#######################################################
Exception has occurred: AttributeError
module 'mediapipe' has no attribute 'solutions'
  File "C:\Users\ARYAN JAIN\OneDrive\Desktop\ai\HandTrackingModule.py", line 13, in __init__
    self.mpHands = mp.solutions.hands
  File "C:\Users\ARYAN JAIN\OneDrive\Desktop\ai\VolumeHandControl.py", line 17, in <module>
    detector = htm.handDetector(detectionCon=0.7, maxHands=1)
AttributeError: module 'mediapipe' has no attribute 'solutions'

problem kasa solve hogi ya meduapipe ka sar version install kar liya but kuch ho rha h error aya rha h

second code#########################################################
import cv2
import time
import numpy as np
import HandTrackingModule as htm
from ctypes import cast, POINTER
from comtypes import CLSCTX_ALL
from pycaw.pycaw import AudioUtilities, IAudioEndpointVolume

wCam, hCam = 640, 480

cap = cv2.VideoCapture(0)
cap.set(3, wCam)
cap.set(4, hCam)

pTime = 0

detector = htm.handDetector(detectionCon=0.7, maxHands=1)

devices = AudioUtilities.GetSpeakers()
interface = devices.Activate(
IAudioEndpointVolume._iid_, CLSCTX_ALL, None)

volume = cast(interface, POINTER(IAudioEndpointVolume))

volRange = volume.GetVolumeRange()
minVol = volRange[0]
maxVol = volRange[1]

volBar = 400
volPer = 0

while True:

    success, img = cap.read()

    img = detector.findHands(img)
    lmList, bbox = detector.findPosition(img)

    if len(lmList) != 0:

        length, img, lineInfo = detector.findDistance(4, 8, img)

        vol = np.interp(length,[50,200],[minVol,maxVol])
        volBar = np.interp(length,[50,200],[400,150])
        volPer = np.interp(length,[50,200],[0,100])

        volume.SetMasterVolumeLevel(vol,None)

    cv2.rectangle(img,(50,150),(85,400),(255,0,0),3)
    cv2.rectangle(img,(50,int(volBar)),(85,400),(255,0,0),cv2.FILLED)

    cv2.putText(img,f'{int(volPer)} %',(40,450),
    cv2.FONT_HERSHEY_COMPLEX,1,(255,0,0),3)

    cTime = time.time()
    fps = 1/(cTime-pTime)
    pTime = cTime

    cv2.putText(img,f'FPS:{int(fps)}',(40,50),
    cv2.FONT_HERSHEY_COMPLEX,1,(255,0,0),3)

    cv2.imshow("Image",img)
    cv2.waitKey(0)
