### ISSUE TITLE
iOS setup failure : 'absl/base/macros.h' file not found

### ISSUE THREAD

**Issue by MaxZeng** [google/mediapipe#274]
I follow the instruction of "Setting up MediaPipe for iOS" (https://github.com/google/mediapipe/blob/master/mediapipe/docs/mediapipe_ios_setup.md), and I can build the "EdgeDectionGpuApp" successfully, but When try to build "HandDetectionGpuApp", Xcode shows me following error message:

 /Users/uc/CodeLab/mediapipedemo/ERROR: /Users/uc/CodeLab/mediapipe/mediapipe/examples/ios/facedetectioncpu/BUILD:40:1: C++ compilation of rule '//mediapipe/examples/ios/facedetectioncpu:FaceDetectionCpuAppLibrary' failed (Exit 1) wrapped_clang failed: error executing command
/Users/uc/CodeLab/mediapipe/mediapipe/framework/calculator_state.h:25:10: 'absl/base/macros.h' file not found
/Users/uc/CodeLab/mediapipedemo/Mediapipe.xcodeproj/.tulsi/Scripts/bazel_build.py:549: Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/1228771/69594797-6fe96080-1038-11ea-9dba-ad18a9bd6df5.png">

**Comment by eknight7** [comment]
Are other iOS examples failing as well?

**Comment by hsimprovis** [comment]
it has a permanent problem with abseil library, despite it works through command line build 

bazel build --config=ios_arm64 mediapipe/examples/ios/handdetectiongpu:HandDetectionGpuApp

tulsi fails to build it using xcode environment

**Comment by seberta** [comment]
@eknight7 we are having the same issue and it is a blocker for the prototype we are trying to build on iOS.

**Comment by hsimprovis** [comment]
Just checked one more time, with the latest master sources and got the same problem
EdgeDetection build and run going smoothly but other samples do not work.

**Comment by cocodrips** [comment]
I faced the same problem.
I succeeded to build when I run on a device instead of simulator.

**Comment by sne21star** [comment]
I am facing the same issue as well. Has anyone succeeded in getting it to work on a simulator?

**Comment by ignacioambrois** [comment]
I am having the same issue while trying to build the HandTrackingGpu app with ```config=ios_x86_64``` and attempting to deploy it to a device instead of a simulator.

**Comment by brucechou1983** [comment]
Having the same issue on mediapipe v0.7.5. Tulsi generated project doesn't work as well. And the ios setup [support document](https://github.com/google/mediapipe/blob/master/mediapipe/docs/mediapipe_ios_setup.md) is no longer available.
