### ISSUE TITLE
iOS Objc : Get LandmarkList instead of NormalizedLandmarkList

### ISSUE THREAD

**Issue by Ankish** [google/mediapipe#2740]
Thank you for submitting a MediaPipe documentation issue.
The MediaPipe docs are open source! To get involved, read the documentation Contributor Guide
## URL(s) with the issue:

Check out the example:
https://github.com/google/mediapipe/blob/master/mediapipe/examples/ios/posetrackinggpu/PoseTrackingViewController.mm

## Description of issue (what needs changing):

```
// Receives a raw packet from the MediaPipe graph. Invoked on a MediaPipe worker thread.
- (void)mediapipeGraph:(MPPGraph*)graph
     didOutputPacket:(const ::mediapipe::Packet&)packet
          fromStream:(const std::string&)streamName {
  if (streamName == kLandmarksOutputStream) {
    if (packet.IsEmpty()) {
      NSLog(@“[TS:%lld] No pose landmarks”, packet.Timestamp().Value());
      return;
    }
    const auto& landmarks = packet.Get<::mediapipe::NormalizedLandmarkList>(); 
 // how to use
    NSLog(@“[TS:%lld] Number of pose landmarks: %d”, packet.Timestamp().Value(),
          landmarks.landmark_size());
    for (int i = 0; i < landmarks.landmark_size(); ++i) {
      NSLog(@“\tLandmark[%d]: (%f, %f, %f)“, i, landmarks.landmark(i).x(),
            landmarks.landmark(i).y(), landmarks.landmark(i).z());
    }
  }
}
```
Crash:
if we use LandmarkList instead of NormalizedLandmarkList, in:
`
    const auto& landmarks = packet.Get<::mediapipe::NormalizedLandmarkList>(); 
`
```
Packet::Get() failed: The Packet stores “mediapipe::NormalizedLandmarkList”, but “mediapipe::LandmarkList” was requested.
```
How can we get the LandmarkList instead of NormalizedLandmarkList? Any documentation regarding that would be great.

**Comment by czy2014hust** [comment]
Because the type of the mediapipe graph's ouptut is `NormalizedLandmarkList `, change/modify the output type to be `LandmarkList ` if you wang to use this type.

**Comment by Ankish** [comment]
We did that, it crashes. Is this the right place to modify ?
` const auto& landmarksUnNormalized = packet.Get<::mediapipe::LandmarkList>(); `




```
// Receives a raw packet from the MediaPipe graph. Invoked on a MediaPipe worker thread.
- (void)mediapipeGraph:(MPPGraph*)graph
       didOutputPacket:(const ::mediapipe::Packet&)packet
            fromStream:(const std::string&)streamName {
    if (streamName == kLandmarksOutputStream) {
        if (packet.IsEmpty()) { return; }
        const auto& landmarks = packet.Get<::mediapipe::NormalizedLandmarkList>();
        const auto& landmarksUnNormalized = packet.Get<::mediapipe::LandmarkList>();
        
        
        //        for (int i = 0; i < landmarks.landmark_size(); ++i) {
        //            NSLog(@"\tLandmark[%d]: (%f, %f, %f)", i, landmarks.landmark(i).x(),
        //                  landmarks.landmark(i).y(), landmarks.landmark(i).z());
        //        }
        NSMutableArray<Landmark *> *result = [NSMutableArray array];
        for (int i = 0; i < landmarks.landmark_size(); ++i) {
            Landmark *landmark = [[Landmark alloc] initWithX:landmarks.landmark(i).x()
                                                           y:landmarks.landmark(i).y()
                                                           z:landmarks.landmark(i).z()];
            [result addObject:landmark];
        }
        [_delegate upperBodyPoseTracker: self didOutputNormalizedLandmarks: result];

        NSMutableArray<Landmark *> *resultNon = [NSMutableArray array];
        for (int i = 0; i < landmarksUnNormalized.landmark_size(); ++i) {
            Landmark *landmark = [[Landmark alloc] initWithX:landmarksUnNormalized.landmark(i).x()
                                                           y:landmarksUnNormalized.landmark(i).y()
                                                           z:landmarksUnNormalized.landmark(i).z()];
            [resultNon addObject:landmark];
        }
        [_delegate upperBodyPoseTracker: self didOutputLandmarks: resultNon];
        
    
    }
}
```

**Comment by czy2014hust** [comment]
Modify the mediapipe graph(pbtxt) you use.

**Comment by Ankish** [comment]
I am using full-body pose for iOS. What I see normalized points setup is over multiple files? Is it possible to get both normal and normalized landmarks than just one of it.

**Comment by gkarpiak** [comment]
@czy2014hust is right you need to update the graph. The graph produces specific outputs, and for each output you corresponding packets, which are of specific type.

Then you can `Get` values from packets, and using the wrong "type" results in an error. So if you want `LandmarkList` you would need to convert from `NormalizedLandmarkList` either in the graph or after you `Get` the value.

For the graph file, please check the source: you already have your controller and usually some dependencies and assets can be found in corresponding "BUILD" file, so look there for the "graph" dependency.
