### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'model_selection'

### ISSUE THREAD

**Issue by INF800** [google/mediapipe#2742]
mediapipe==0.8.3 is the latest possible version supported in python 3.6. 

We cannot use face detection `model_selection` in it like this
```python
  with mp_face_detection.FaceDetection(model_selection=0, 
                                       min_detection_confidence=0.5) as face_detection:
```
Causing
```python
TypeError: __init__() got an unexpected keyword argument 'model_selection'
```

Shall I send a PR fixing this issue?

It works if we remove  'model_selection' as in
```python
  with mp_face_detection.FaceDetection(# model_selection=0, 
                                       min_detection_confidence=0.5) as face_detection:
```

**Comment by sgowroji** [comment]
Hi @INF800, Could you please try with the latest release. Do you encounter any errors with the latest release. Thanks!

**Comment by INF800** [comment]
I am not able to install 0.8.9 with python3.6 using `pip install
mediapipe==0.8.9`. The most recent available release is 0.8.3 according to
pip

**Comment by sgowroji** [comment]
MediaPipe Python support extended you  can try 3.7 to 3.9.

**Comment by INF800** [comment]
There are some requirements which restrict me to use 3.6 only.

**Comment by INF800** [comment]
Here it states 3.6 is not supported. Wdym by "support extended"?

https://github.com/google/mediapipe/blob/f4e7f6cc48e89a4702860a370c431e56568800d1/setup.py#L451-L454

**Comment by sgowroji** [comment]
Yes model_selection is one of the argument in it.

**Comment by daveabiy** [comment]
Is this problem solved? I'm also facing it now
