### ISSUE TITLE
Trying to build on Xavier NX  and got: undefined symbol: zaxpyc_k on import

### ISSUE THREAD

**Issue by przemoch-dev** [google/mediapipe#2744]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution: Nvidia Ubuntu 18.04
- Compiler version: gcc 7.5.0
- Programming Language and version: Python 3.8.8
- Installed using virtualenv? pip? Conda?: venv
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.4
- Bazel version: Bazelisk 

**Describe the problem**:
I'm trying to compile and install mediapipe on my Xavier NX with Ubuntu 18.04. After several compilation problems on master, I decided to build from 0.8.4. I was able to build and install whl file. When I try to import mediapipe I got following error:

```
>>> import mediapipe as mp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/przemek/mediapipe/venv/lib/python3.8/site-packages/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/data/przemek/mediapipe/venv/lib/python3.8/site-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: /usr/lib/aarch64-linux-gnu/libblas.so.3: undefined symbol: zaxpyc_k
```

To prepare my environment I followed [this](https://github.com/jiuqiant/mediapipe_python_aarch64) instruction. I also added `"WITH_LAPACK": "OFF"` to `third_party/BUILD`. 

Any idea what is going on here?

**Comment by sgowroji** [comment]
Hi @przemoch-dev,  Could you please share your steps to reproduce the above error. Thanks!
