### ISSUE TITLE
camera_utils.js documentation

### ISSUE THREAD

**Issue by JpEncausse** [google/mediapipe#2749]
I try to use FaceMesh solution in JavaScript.

I'm lookling for camera_utils.js deep documentation in order to select the correct webcam, etc ... like with `getUserMedia` because the Camera object select my front laptop camera :-(

I try to understand what is the code of `onFrame() ` so I would be able to bypass / rewrite my own (if it is simple).

**Comment by ayushgdev** [comment]
Hello @JpEncausse 
We are working our way through documentation improvement to help users build the solutions easily. Meanwhile, you can refer to the type definition files in the comment [here](https://github.com/google/mediapipe/issues/1408#issuecomment-810652766) which will give visibility into what can be called within the API of the Javascript solutions.
