### ISSUE TITLE
Using a Face Effect on Face Mesh for Desktop/JS

### ISSUE THREAD

**Issue by JpEncausse** [google/mediapipe#2750]
According to the [documentation](https://google.github.io/mediapipe/solutions/face_mesh.html#effect-renderer) and [this issue](https://github.com/google/mediapipe/issues/1155) it's possible to apply a PNGBlob 2D or 3D to a FaceMesh. 

- Is there an example for Desktop / JS ?
- Android code seems to use a [FaceMeshResult + GPU trick](https://google.github.io/mediapipe/solutions/face_mesh#face-effect-example)

Any simple JS Demo that apply the face pattern ?

**Comment by furkandindar** [comment]
Hi, I am also curious if you have a JS  demo or documentation about face effects. I've been trying to use MediaPipe + ThreeJS to render sunglasses on the face using MediaPipe's facemesh, but I would very much like to try MediaPipe's own face effect renderer as stated in this [documentation](https://google.github.io/mediapipe/solutions/face_mesh.html#effect-renderer)

**Comment by sgowroji** [comment]
Hi @furkandindar, Have a look at this https://github.com/google/mediapipe/issues/2673#issuecomment-946113076

**Comment by mhays-google** [comment]
We expose the 3d geometry of the face, and this can be fed directly into toolkits such as ThreeJS.  We have internal demos showing face effects.  I will bring this up to the team as I would love to release this to the larger community.

**Comment by ZeroLu** [comment]
@mhays-google Hi there, just want you to know that we also want a face geometry web demo badly! I searched the entire Internet for this. I found some demos on TF blog but they are all broken :(
Like this one: https://blog.tensorflow.org/2020/11/iris-landmark-tracking-in-browser-with-MediaPipe-and-TensorFlowJS.html

**Comment by JpEncausse** [comment]
Would be awesome to have a standalone web example of FaceMesh
- with glasses
- with lipstick
- with hair segmentation

I'm working on SamrtMirror using Google Chrome only :-/
It seems PerfectCorp did something like that in the browser with MediaPipe

**Comment by im-AMS** [comment]
Can we expect the same for python version?

**Comment by htorrendell** [comment]
Hey everyone, 

Any updates on this or any expected time frame?

Thanks!

**Comment by fedegonzal** [comment]
Hey! some new here? I want to put my face over my face!

**Comment by Fayazexo** [comment]
@mhays-google Hi, do you have plans to release the demos yet?

**Comment by JpEncausse** [comment]
Little push up, 
A demo of  Face Overlay for the web would be awesome 
- To add Glasses, Hat, ...
- To update makeup (color overlay)

There is more and more startups working on that kind of usecase. A little for the web would kickstart everyone ;-)

**Comment by DouglasLapsley** [comment]
You might find this helpful: https://hiukim.github.io/mind-ar-js-doc/more-examples/threejs-face-facemesh/

**Comment by esinanturan** [comment]
> mhays-google

Any hope about showing some demos for face effect API ?

**Comment by MahdiHabibiXr** [comment]
:)) Add me to waiters list.
Is there any news about the face ffect demos?

**Comment by kuaashish** [comment]
Hello @JpEncausse,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by JpEncausse** [comment]
@kuaashish the new MediaPipe solution is very promising, I like the HandTracking demo !
But there is no mention to Face Landmarks :-( there is so much usecase on JS/Web:
- Face Augmented Reality for Beauty and Skin Care or Glasses
- Reading Lips
- Eye Tracking

Any plan to add them to the demos ? It is one of the key features Google/MediaPipe have compared to Microsoft that will no longer provide Face Description ...

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,
We have any plans to include this in our new mediapipe solutions?

**Comment by schmidt-sebastian** [comment]
https://www.npmjs.com/package/@mediapipe/tasks-vision alpha 11 and higher include FaceLandmarker.
