### ISSUE TITLE
c++ and python api got different landmark features in human pose

### ISSUE THREAD

**Issue by 13717630148** [google/mediapipe#2752]
i first used following code to get landmark of a frame:
``from mediapipe.python.solutions import pose as mp_pose

pose_tracker = mp_pose.Pose()

result = pose_tracker.process(image=input_frame)

pose_landmarks = result.pose_landmarks

pose_landmarks = np.array([[lmk.x * frame_width, lmk.y * frame_height, lmk.z * frame_width]
                                        for lmk in pose_landmarks.landmark],dtype=np.float32)``
and i got a nunpy array as follows:
[[ 634.3986     231.39737   -242.14374  ]
 [ 638.53796    225.56795   -231.34702  ]
 [ 640.9735     225.58327   -231.36649  ]
 [ 643.5247     225.67976   -231.40306  ]
 [ 630.5147     225.67435   -228.89035  ]
 [ 627.58954    225.82338   -228.93024  ]
 [ 625.39417    226.071     -228.92004  ]
 [ 647.06616    228.7434    -157.56358  ]
 [ 622.5644     229.79178   -147.76384  ]
 [ 639.00085    238.97804   -214.79036  ]
 [ 629.9175     239.23721   -212.22125  ]
 [ 664.452      272.1932    -111.2407   ]
 [ 608.8511     274.18243    -87.85767  ]
 [ 678.51904    320.2788    -214.82025  ]
 [ 595.87915    321.0516    -171.97601  ]
 [ 684.4783     283.09787   -382.719    ]
 [ 586.5908     288.11108   -356.83374  ]
 [ 687.08203    271.4092    -414.47818  ]
 [ 582.2318     276.6213    -388.52237  ]
 [ 686.99805    266.16354   -407.46936  ]
 [ 582.5347     272.57913   -385.13553  ]
 [ 685.4358     269.66318   -383.22504  ]
 [ 584.97705    275.40308   -360.08548  ]
 [ 651.0969     354.4542      -7.875162 ]
 [ 620.9331     355.09402      7.762096 ]
 [ 649.02014    417.9712       1.5189542]
 [ 623.5113     420.01038     45.31877  ]
 [ 646.65967    463.75635    187.5009   ]
 [ 625.5711     464.46173    224.79932  ]
 [ 644.61597    467.5548     202.08922  ]
 [ 628.6172     468.63928    239.58493  ]
 [ 647.499      485.02032    127.97751  ]
 [ 623.8875     486.83322    164.93224  ]]

then i used c++ to get landmarks of the same frame,with api 'NormalizedLandmarksToLandmarks' from landmarks_smoothing_calculator.cc.The results is shown as followed:
Nose640.014,357.54,0.158837
Left_eye_inner638.802,209.015,0.418818
Left_eye647.894,228.051,-159.877
Left_eye_outer650.583,228.033,-159.866
Right_eye_inner637.205,228.702,-159.45
Right_eye634.511,228.762,-159.465
Right_eye_outer631.909,228.907,-159.388
Left_ear652.978,231.161,-84.5544
Right_ear629.234,232.304,-84.1727
Mouth_left646.585,241.911,-143.874
Mouth_right636.59,242.254,-143.826
Left_UpperArm666.802,273.909,-38.8589
Right_UpperArm637.205,273.339,-30.5638
Left_Forearm677.657,320.775,-86.3749
Right_Forearm228.702,320.019,-93.837
Left_Hand687.852,290.439,-71.7128
Right_Hand-159.45,286.444,-88.0493
Left_pinky640.014,280.121,-249.684
Right_pinky590.613,274.941,-287.423
Left_index693.741,275.842,-253.845
Right_index590.414,269.865,-286.735
Left_thumb690.808,278.821,-228.09
Right_thumb593.424,273.695,-260.056
Left_Thigh634.511,356.966,1.06808
Right_Thigh625.312,357.614,-1.06721
Left_Calf228.762,421.484,14.1848
Right_Calf628.208,420.492,20.1499
Left_ankle-159.465,465.91,167.948
Right_ankle630.867,465.165,187.903
Left_heel648.176,469.87,180.334
Right_heel632.806,467.352,202.267
Left_foot_index653.624,487.644,118.325
Right_foot_index632.154,486.248,141.351

we can see that the elements of two results varies from each other in corresponding position,especially in z axis.
i have no idea of it.

**Comment by sgowroji** [comment]
Hi @13717630148, Could you please provide your Code changes, Configuration details. Thanks!

**Comment by 13717630148** [comment]
no problem. my co-worker will upload it
