### ISSUE TITLE
Aligned bounding box using facemesh

### ISSUE THREAD

**Issue by Winvoker** [google/mediapipe#2754]
- MediaPipe Solution (you are using): FaceMesh
- Programming language : Python

I am using facemesh and i want to get aligned bounding boxes from an image or directly from webcam. In this gif in mediapipe's docs, is drawing a perfectly aligned bounding box however in the API I could not get any bounding box when using facemesh. So i found a code which can get me a bounding box from max-min keypoints to get a bounding box however this is not what i want. I want aligned bounding boxes.

![Alinged bounding box from mediapipe page](https://google.github.io/mediapipe/images/mobile/face_mesh_android_gpu.gif)
I am able to do something like this

![this](https://user-images.githubusercontent.com/45109898/140919514-7a12e950-3ace-45fd-a005-e810b90a5610.png)

```
if results.multi_face_landmarks:
    for face_landmarks in results.multi_face_landmarks:
        print(face_landmarks.landmark)
        h, w, c = image.shape
        cx_min = w
        cy_min = h
        cx_max = cy_max = 0
        for id, lm in enumerate(face_landmarks.landmark):
            cx, cy = int(lm.x * w), int(lm.y * h)
            if cx < cx_min:
                cx_min = cx
            if cy < cy_min:
                cy_min = cy
            if cx > cx_max:
                cx_max = cx
            if cy > cy_max:
                cy_max = cy
        cv2.rectangle(
            image, (cx_min, cy_min), (cx_max, cy_max), (255, 255, 0), 2
        )
```

Will you add an option to get these aligned bounding boxes ?

**Comment by Winvoker** [comment]
any updates ? @jiuqiant @sgowroji

**Comment by sgowroji** [comment]
Hi @Winvoker, Did you try adding the face detection bounding box using `mp_drawing.draw_detection(annotated_image, detection)` in face mesh.  You can try changing the attributes in  drawing_utils.py and also drawing_styles.py

**Comment by d4rk-lucif3r** [comment]
Just do
                cv2.rectangle(image, (cx_min-130, cy_min-130),
                            (cx_max+130, cy_max+130), (255, 255, 0), 5)
