### ISSUE TITLE
Getting error when calling selfieSegmentation.send method in react project

### ISSUE THREAD

**Issue by artakpoghosyan1** [google/mediapipe#2756]
**I am trying to integrate [selfie segmentation](https://google.github.io/mediapipe/solutions/selfie_segmentation#javascript-solution-api) in `react` project**. Following the documentation example I have this code:

```
React.useEffect(() => {
      const canvas = canvasRef.current!
      const video = videoRef.current!
      const canvasCtx = canvas.getContext('2d')!
      function onResults(results): void {
          canvasCtx.save();
          canvasCtx.clearRect(0, 0, canvas.width, canvas.height);
          canvasCtx.drawImage(results.segmentationMask, 0, 0, canvas.width, canvas.height);


          canvasCtx.globalCompositeOperation = "source-in";
          canvasCtx.fillStyle = "#00FF00";
          canvasCtx.fillRect(0, 0, canvas.width, canvas.height);

          canvasCtx.globalCompositeOperation = "destination-atop";
          canvasCtx.drawImage(
              results.image,
              0,
              0,
              canvas.width,
              canvas.height
          );

          canvasCtx.restore();
      }

      const selfieSegmentation = new SelfieSegmentation({locateFile: (file) => {
              return `https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/${file}`;
          }});

      selfieSegmentation.onResults(onResults)

      const camera = new Camera(video, {
          onFrame: async () => {
              await selfieSegmentation.send({image: video});
          },
          width: 1280,
          height: 720
      });

      camera.start()
  }, [])
```

**and getting this error:**

```
 Uncaught (in promise) RuntimeError: abort(undefined) at Error.    selfie_segmentation_solution_simd_wasm_bin.js:9
    at jsStackTrace (selfie_segmentation_solution_simd_wasm_bin.js:9)
    at stackTrace (selfie_segmentation_solution_simd_wasm_bin.js:9)
    at abort (selfie_segmentation_solution_simd_wasm_bin.js:9)
    at _abort (selfie_segmentation_solution_simd_wasm_bin.js:9)
    at selfie_segmentation_solution_simd_wasm_bin.wasm:0x4bbd06
    at selfie_segmentation_solution_simd_wasm_bin.wasm:0x4bbbc1
    at selfie_segmentation_solution_simd_wasm_bin.wasm:0x4bbd1f
    at selfie_segmentation_solution_simd_wasm_bin.wasm:0x15294
    at selfie_segmentation_solution_simd_wasm_bin.wasm:0xffa9
    at SolutionWasm$send [as send] (eval at new_ (selfie_segmentation_solution_simd_wasm_bin.js:9), <anonymous>:9:1)
    at abort (selfie_segmentation_solution_simd_wasm_bin.js:9)
    at _abort (selfie_segmentation_solution_simd_wasm_bin.js:9)
    at selfie_segmentation_solution_simd_wasm_bin.wasm:0x4bbd06
    at selfie_segmentation_solution_simd_wasm_bin.wasm:0x4bbbc1
    at selfie_segmentation_solution_simd_wasm_bin.wasm:0x4bbd1f
    at selfie_segmentation_solution_simd_wasm_bin.wasm:0x15294
    at selfie_segmentation_solution_simd_wasm_bin.wasm:0xffa9
    at SolutionWasm$send [as send] (eval at new_ (selfie_segmentation_solution_simd_wasm_bin.js:9), <anonymous>:9:1)
    at qa.eval [as h] (selfie_segmentation.js?ce85:64)
    at ta (selfie_segmentation.js?ce85:14)
abort @ selfie_segmentation_solution_simd_wasm_bin.js:9
_abort @ selfie_segmentation_solution_simd_wasm_bin.js:9
$func6070 @ selfie_segmentation_solution_simd_wasm_bin.wasm:0x4bbd06
$func6068 @ selfie_segmentation_solution_simd_wasm_bin.wasm:0x4bbbc1
$func6072 @ selfie_segmentation_solution_simd_wasm_bin.wasm:0x4bbd1f
$func223 @ selfie_segmentation_solution_simd_wasm_bin.wasm:0x15294
$func193 @ selfie_segmentation_solution_simd_wasm_bin.wasm:0xffa9
SolutionWasm$send @ VM120983:9
eval @ selfie_segmentation.js?ce85:64
ta @ selfie_segmentation.js?ce85:14
next @ selfie_segmentation.js?ce85:15
h @ selfie_segmentation.js?ce85:40
Promise.then (async)
r @ camera_utils.js?141c:7
eval @ camera_utils.js?141c:7
requestAnimationFrame (async)
q @ camera_utils.js?141c:7
a.video.onloadedmetadata @ camera_utils.js?141c:7
```

**Comment by sgowroji** [comment]
Hi @artakpoghosyan1, Can you confirm the files downloaded properly https://github.com/google/mediapipe/issues/2631#issuecomment-944661312. Thanks!

**Comment by artakpoghosyan1** [comment]
Hi @sgowroji. I've installed all file via npm and imported them in my component. So yes files are downloaded.

<img width="763" alt="Screen Shot 2021-11-10 at 11 38 35" src="https://user-images.githubusercontent.com/13457544/141070203-c162c0ab-9316-4ef8-8cd2-bb6d19b88043.png">

**Comment by tyrmullen** [comment]
It looks like you're trying to locate files online via jsdelivr with this line:
`return `https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/${file}`;`

But if you downloaded the files and imported them locally, then you'd probably want to be targeting those downloaded files instead (wherever they are located).

**Comment by st-trangnguyen** [comment]
Hi guys, I am trying to integrate selfie segmentation in react project to handle the virtual background feature. I have an button to start/stop sharing my webcam. When I stopped sharing my webcam, the camera light on my macbook is on. Anyone can help me to know how to solve this issue?

**Comment by artakpoghosyan1** [comment]
> Reference

Hi @tyrmullen

<img width="735" alt="Screen Shot 2021-11-22 at 15 50 14" src="https://user-images.githubusercontent.com/13457544/142857512-a06d3746-49f4-4a42-8452-b3b2d53cf1e9.png">

This is how documentation says to use `SelfieSegmentation` api. It returns 4 files:

<img width="903" alt="Screen Shot 2021-11-22 at 15 54 26" src="https://user-images.githubusercontent.com/13457544/142859307-c0a84a2b-280b-4762-a1f0-4b8ed444e36b.png">

How can I pass those files in other way?

**Comment by tyrmullen** [comment]
@artakpoghosyan1 The documentation is assuming that you are retrieving all files online, and not downloading any of them locally before-hand.  See the CodePen for better specifics on this method than the documentation: https://codepen.io/mediapipe/pen/wvJyQpq.  Note in particular the "settings" tab of the HTML, which has:
```
<script src="https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation.js" crossorigin="anonymous">
```
and the constructor:
```
const selfieSegmentation = new SelfieSegmentation({locateFile: (file) => {
  return `https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/${file}`;
}});
```
So they both "match" in that they are both going to be reloaded from the internet live at version 0.1.

If you download any of these files locally before-hand for your setup (so your "import" statement is grabbing them locally, and NOT reloading them live from the internet at a particular version), then you need to make sure that ALL of the files you use are at the precise same version (i.e. 0.1.xxxxx, where the .xxxxx must match as well).  This means instead of using
`https://cdn.jsdelivr.net/npm/...`, you should instead be having a local URL which matches *your* web-app setup.  For example `/my_assets/...` (wherever you are staging the files which have been downloaded).

Although I don't recommend mixing "live" and "offline" assets, if you still want to be fetching from an online resource, then I'd recommend specifying the full version, to better ensure a match.  So whatever version you downloaded locally, let's call that "0.1.12345", you'd need
```
  return `https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1.12345/${file}`;
```
