### ISSUE TITLE
How to implement 3d glass rendering using facemesh.

### ISSUE THREAD

**Issue by kXborg** [google/mediapipe#2757]
Hi, can someone tell me how to implement 3d glass ( or any custom object) rendering using Facemesh? As it is shown on the documentation page. I can't find any example code for that.
![example](https://google.github.io/mediapipe/images/face_geometry_renderer.gif)

**Comment by sgowroji** [comment]
Hi @kXborg, Present we don't have any example, but you can go through this for more understanding https://github.com/google/mediapipe/issues/1155. You can also build one from here https://google.github.io/mediapipe/solutions/face_mesh#face-effect-example
