### ISSUE TITLE
AttributeError: module 'mediapipe' has no attribute 'solutions'

### ISSUE THREAD

**Issue by TonyStark8250** [google/mediapipe#2758]
First of all I couldn't install mediapipe with pip so I cloned the repo and copied the "mediapipe" folder and pasted it in python's site-packages folder. But when I try 
`import mediapipe as mp

mpHands = mp.solutions.hands`

it says "mediapipe has no attribute solutions" but there is the solutions folder inside the mediapipe's python folder. I'm using python 3.8 and currently on windows 7 32bit. I'm a beginner in this field. Please help

**Comment by sgowroji** [comment]
Hi @TonyStark8250,   Have you tried checking this https://google.github.io/mediapipe/getting_started/python.html#mediapipe-in-python

**Comment by veera20** [comment]
Hi ,I have installed mediapipe through sources mediapipe in riscv target is importing fine but when i try to use mediapipe library for a test script ,I am facing error like AttributeError: module 'mediapipe' has no attribute 'solutions'

**Comment by CorpusCallosum** [comment]
Did you ever sort this out?
I'm experiencing the same problem now...
