### ISSUE TITLE
How to use segmentation with Pose solution on TFJS?

### ISSUE THREAD

**Issue by ats05** [google/mediapipe#2759]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): Pose
- Programming language : typescript(JavaScript)
- Are you willing to contribute it (Yes/No): Yes

Currently, the segmentation mask is not available in Pose solution on TFJS runtime.
Are there any plans for this to be available?

The Mediapipe runtime doesn't work on iOS, so I'd like to use it as an alternative now.

Thanks,

**Comment by sgowroji** [comment]
Hi @ats05, Could you please confirm the above query is about https://google.github.io/mediapipe/solutions/pose#enable_segmentation in Javascript MediaPipe pose solution. Please check and reach out for more information. Thanks!

**Comment by ats05** [comment]
Hi @sgowroji ,

Thank you for response.
Yes, I'm just asking to that config.

**Comment by sgowroji** [comment]
You can set  enableSegmentation: true,
as below in Javascript solution and can find the same in control options of [codepen](https://codepen.io/mediapipe/full/jOMbvxw) examples

`pose.setOptions({
  modelComplexity: 1,
  smoothLandmarks: true,
  enableSegmentation: true,
  smoothSegmentation: true,
  minDetectionConfidence: 0.5,
  minTrackingConfidence: 0.5
});`

**Comment by ats05** [comment]
@sgowroji ,

Thanks for information.

And sorry, I was asking about "BlazePose with TFJS". 
https://github.com/tensorflow/tfjs-models/tree/master/pose-detection/src/blazepose_tfjs

Perhaps I shouldn't have asked in the MediaPipe repository.

Thanks!
