### ISSUE TITLE
Document about use Custom model 

### ISSUE THREAD

**Issue by aliakbarhamzeh1378** [google/mediapipe#2761]
Hello. 
is there any documents or tutorial for using a custom model on media pipe python or javascript?
I had a lot of searches, but I can't find anything about this.

**Comment by sgowroji** [comment]
Hi @aliakbarhamzeh1378, Could you please elaborate your query with More details.  Thanks!

**Comment by aliakbarhamzeh1378** [comment]
I want to use selfie segmentation. 
but the media pipe default model was not good for me. 
I want to use other TensorFlow models for selfie segmentation and convert them to wasm ( web assembly ) for the load to my code. 
I trying to find any document or tutorial about using a custom model on mediapipe js or python.
all of the documents and blog posts use the default model and there is not any document for load and use the custom model in mediapipe.

**Comment by sgowroji** [comment]
Hi @aliakbarhamzeh1378, For python you can create your own graph using the calculators and execute as mentioned here https://google.github.io/mediapipe/getting_started/python_framework.html#graph.

**Comment by mhays-google** [comment]
Thank you for the patience.  I've created a new version (0.3.1640029074) with the stop() method properly exported.

**Comment by Elise8** [comment]
Hey, any update on how can we use a custom model on media pipe javascript? Thanks!

**Comment by elYeodeol** [comment]
Hey, do you have any udpate on how we can use a custom model on mediapipe javascript ? Thanks
