### ISSUE TITLE
Hardware Configuration for MediaPipe (Pose, ...) on Chrome

### ISSUE THREAD

**Issue by JpEncausse** [google/mediapipe#2762]
Hi,
I'm looking for Hardware recommendation to run MediaPipe on Chrome to perform live Pose Estimation, Face Augmented Reality, for Digital Signage usecase (SmartMirror, Fitting Room, Sports Coach, etc ...)

My current SmartMirror use a Chromebit (HDMI Key on ChromeOS) small and great device no longer supported by Google. It's a ARM Cortex A17 1.8Ghz. But it's slow as hell on Pose Estimation might be few FPS / second at best. It's smooth on a Razer Laptop Core i7...

What target processor / configuration should run smoothly MediaPipe Pose or Face on Chrome ?
- I target ChromeOS because it's fast / simple / accurate compared to a multitool windows or a DIY linux (but may be it's a mistake ?)
- I target a small form factor like HDMI Key or small box because let's be honest MediaPipe is about user interraction (aka Didital Signage you can't use a Gaming Laptop or GTX30x to make it run IRL ;-)
- I understand a MediaPipe usage is app on end user's mobile phone (for instance AR Makeup) but I rather use a regular computer for a SmartMirror

Any advice, pointer, help would be awesome if core team have some prefered/target devices/processor in mind ?

**Comment by JpEncausse** [comment]
I looked deeper into processor and according to benchmarks :
- Chromebit == RPi4 == ChromeCast Box
- Chrome Box Celeron is x2 better
- Chrome Box Corei3 is x6 better (half my Laptop CPU)
- Chrome Box Core i5 is x10 better

It's only the CPU, I assume MediaPipe in Chrome rely a lot on GPU also ?
Core i3 seems to be a sweat spot price vs power did someone give a try with Pose Estimation in a Browser ?

![image](https://user-images.githubusercontent.com/1140867/141661508-6c8db7e3-8a5a-41a9-9b56-27ec9cdebb31.png)

**Comment by mcclanahoochie** [comment]
CPU Mark is a decent proxy for performance. Another proxy would be GPU performance.
When MediaPipe runs in Chrome, it uses both CPU/GPU in this way:
_input image > GPU pre-processing > CPU model inference > GPU post-processing > GPU rendering_
The most demanding part would be model inference, but that is only half of the picture.

I have an 8-core celeron chromebook , and with https://codepen.io/mediapipe/full/jOMbvxw i get around 12fps running the 'lite' model.

**Comment by JpEncausse** [comment]
More and more RK3588 popup these weeks
- with strong TPU
- good video processing
- fanless, 8nm

Does anyone give a try ? For my [SmartMirror](https://reflets.io) I'm looking for a low-cost, small form factor device to Run Android/Chrome with MediaPipe / TFJS and  Canvas/ThreeJS

ChromeBit was so good, but Google no longer maintain it. And it's a little too weak and old in 2022 to run all these processing.

**Comment by kuaashish** [comment]
Hello @JpEncausse,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
