### ISSUE TITLE
FaceMesh SavedModel Availability

### ISSUE THREAD

**Issue by nihalraman** [google/mediapipe#2763]
Hi! Are the savedmodel/.pb files for Facemesh are publicly available? I'm looking to fine-tune the model for an individual person (similar to https://www.tensorflow.org/hub/tutorials/tf2_image_retraining), and I can only find .tflite and TensorFlow js format files online. Thanks for the help!

**Comment by sgowroji** [comment]
Hi @nihalraman, You can find the models and model cards from here https://google.github.io/mediapipe/solutions/models.html.

**Comment by nihalraman** [comment]
How do I convert either of these formats to the savedmodel format (or any other format where I can easily fine-tune the model with additional data)? Sorry if this is a basic question--I'm pretty new to this. Thanks for the help!

**Comment by sgowroji** [comment]
Hello, unfortunately we do not plan to share the training code for FaceMesh models in the nearest future.
If you would like to train your custom FaceMesh model, you might be interested in some details, on how we trained our existing models: https://arxiv.org/abs/1907.06724 and https://google.github.io/mediapipe/solutions/face_mesh.html
