### ISSUE TITLE
Jetson Nano mediapipe 0.8.5 and AttributeError: module 'mediapipe.python.solutions' has no attribute 'drawing_styles'

### ISSUE THREAD

**Issue by zubairahmed-ai** [google/mediapipe#2764]
- OS Platform and Distribution : [Jetson Nano docker JetPack 4.6 (L4T R32.6.1) docker container](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-ml)
- Programming Language and version : Python 3.9
- Installed using virtualenv? pip? Conda? (if python): pip
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.5

**Describe the problem**:
I have the dreaded error `AttributeError: module 'mediapipe.python.solutions' has no attribute 'drawing_styles'` and I know the solution is to upgrade to `mediapipe 0.8.6` but that isn't available on Jetson Nano, so please tell me the alternative to go around this issue?

```
mp_drawing_styles = mp.solutions.drawing_styles
AttributeError: module 'mediapipe.python.solutions' has no attribute 'drawing_styles'
```

**Comment by jiuqiant** [comment]
You can go back to the v0.8.4 to find the example code. For example, for running hands api, you can go to https://github.com/google/mediapipe/blob/v0.8.4/docs/solutions/hands.md#python-solution-api.

**Comment by lghasemzadeh** [comment]
@zubairahmed-ai hello, how did you resolve the error?

**Comment by zubairahmed-ai** [comment]
I stopped using it and switched to Nvidia Pose estimation

**Comment by roelboumans** [comment]
I received the same error. I upgraded to the latest mediapipe version (at the moment of writing 0.8.9.1) by
pip install mediapipe==0.8.9.1
Then I did not have this error anymore.
