### ISSUE TITLE
Please what version of python is suitable for media pipe and other modules like autopy, numpy and the rest of them.

### ISSUE THREAD

**Issue by jerry11671** [google/mediapipe#2765]

**Comment by sgowroji** [comment]
Hi @jerry11671,  For MediaPipe Python 3.7 to 3.9.

**Comment by jerry11671** [comment]
> Hi @jerry11671,  For MediaPipe Python 3.7 to 3.9. 
Thanks...
Are there any requirement to install it.....Like things that should be installed first before installing it.

**Comment by sgowroji** [comment]
Hi @jerry11671, We have pretty much clear documentation on [Python](https://google.github.io/mediapipe/getting_started/python.html#mediapipe-in-python) .  You can also refer our MediaPipe Python [Colab](https://google.github.io/mediapipe/getting_started/python.html#mediapipe-on-google-colab) solutions.  And this our installation [documentation](https://google.github.io/mediapipe/getting_started/install.html) for supported OS
