### ISSUE TITLE
Unable to find the type for stream "image".  It may be set to AnyType or something else that isn't determinable,

### ISSUE THREAD

**Issue by cndcnd085** [google/mediapipe#2767]
mediapipe0.87,  after building gpu python API success,i encount Unable to find the type for stream "image".  It may be set to AnyType or something else that isn't determinable,

**Comment by sgowroji** [comment]
Hi @cndcnd085, Can you please go through this This is intended. MediaPipe Python package only contains CPU graphs. If you need to run any GPU graphs, see #1651 (comment).

**Comment by cndcnd085** [comment]
'm making a pose_ tracking_ GPU program, I can compile with C + + and execute it correctly. Now I want to make a python API. I did it according #1651 to modify my pose_ tracking_ Gpu.pbtxt file, but I still have runtime error:; Unable to find the type for stream "image". It may be set to anytype or something else that isn't deterministic, or the type may be defined but not registered_ tracking_ Gpu.pbtxt is as follows       


# MediaPipe graph that performs pose tracking with TensorFlow Lite on GPU.

# GPU buffer. (GpuBuffer)
input_stream: "IMAGE:image"

# Output image with rendered results. (GpuBuffer)
output_stream: "output_video"




# Pose landmarks. (NormalizedLandmarkList)
output_stream: "pose_landmarks"




node: {
  calculator: "ColorConvertCalculator"
  input_stream: "RGB_IN:image"
  output_stream: "RGBA_OUT:image_rgba"
}

node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "image_rgba"
  output_stream: "image_gpu"
}






# Generates side packet to enable segmentation.
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:enable_segmentation"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet { bool_value: false }
    }
  }
}

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.





# Subgraph that detects poses and corresponding landmarks.
node {
  calculator: "PoseLandmarkGpu"
  input_side_packet: "ENABLE_SEGMENTATION:enable_segmentation"
  input_stream: "IMAGE:image_gpu"
  output_stream: "LANDMARKS:pose_landmarks"
  output_stream: "SEGMENTATION_MASK:segmentation_mask"
  output_stream: "DETECTION:pose_detection"
  output_stream: "ROI_FROM_LANDMARKS:roi_from_landmarks"
}

# Subgraph that renders pose-landmark annotation onto the input image.
node {
  calculator: "PoseRendererGpu"
  input_stream: "IMAGE:image_gpu"
  input_stream: "LANDMARKS:pose_landmarks"
  input_stream: "SEGMENTATION_MASK:segmentation_mask"
  input_stream: "DETECTION:pose_detection"
  input_stream: "ROI:roi_from_landmarks"
  output_stream: "IMAGE:output_video"
}

**Comment by kuaashish** [comment]
Hello @cndcnd085,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
