### ISSUE TITLE
Version 0.8.9 release notes and new hand landmarks model benchmark

### ISSUE THREAD

**Issue by matanster** [google/mediapipe#2768]
It seems that 0.8.9 is the version that gets installed now from pip, and it looks like it brings around two versions of the landmarks detection model: a light (lite) and a full landmarks detection model, both of which having very different sizes compared to the previously shipped model from previous versions. The same holds as to the palm detection model. 

Could be nice to have some documentation as to the test performance benchmarks of these new models compared to the previously shipped ones. Or just any notes on the training methodology used this time around. 

And in general, add a quick release note for 0.8.9 on the [github releases page](https://github.com/google/mediapipe/releases). 

Thanks for having already updated the model card with the details of the new version of the model ...

**Comment by sgowroji** [comment]
Hi @matanster, You can try checking our https://google.github.io/mediapipe/solutions/models.html#hands from here.Please reach us if you still have more queries  with respect to any context which you don't find from the model cards.

**Comment by matanster** [comment]
Hi @sgowroji and thanks for your response! I have summarized the information disclosure gap [here](https://github.com/google/mediapipe/issues/742#issuecomment-991899577) just yesterday actually. I don't find that the model cards nor the inline code documentation provide a lot of clarification about this aspect which is complicated under the hood but needs to be simple from the outside. Unless the training data was very unevenly prepared in those regards, my feeling is that this all could be clarified more authoritatively.

**Comment by sgowroji** [comment]
Hi @matanster, Could you please elaborate your points for which you are expecting the documentation and also what all queries you had and did not found them from model cards and MediaPipe page. Thanks!

**Comment by matanster** [comment]
Thanks @jiuqiant for updating the release page!

The release trains are much appreciated. Basically it would be just nice to specify the nature of the model update when releasing a new model, such as on [the release pages](https://github.com/google/mediapipe/releases). And then, as it's the first release with world landmarks, to clarify on their semantics as per the information that is currently kind of lacking which I lay out here (https://github.com/google/mediapipe/issues/742#issuecomment-993701072).

**Comment by sgowroji** [comment]
We will consider your request . Thank you so much for the input.
