### ISSUE TITLE
How to convert hand_landmark tFLite model to pb ​Save Model ?

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#2770]
How to convert hand_landmark tFLite model to pb Save Model?

**Comment by LMR2018** [comment]
How to parse hand_landmark_lite.tflite?

**Comment by sgowroji** [comment]
Hi @LMR2018, Could you please elaborate your query with more details. Thanks!

**Comment by LMR2018** [comment]
I want to convert mediapipe/modules/hand_landmark/hand_landmark_lite. tflite model to PB model and I want to convert PB model to RKNN model

**Comment by LMR2018** [comment]
> 嗨@LMR2018，您能否详细说明您的查询。谢谢！

I want to convert mediapipe/modules/hand_landmark/hand_landmark_lite. Tflite model to PB model and I want to convert PB model to RKNN model

**Comment by sgowroji** [comment]
Hi @LMR2018, Have you tried doing like this https://stackoverflow.com/questions/53664279/converting-tflite-to-pb. Did you encounter any error ?

**Comment by LMR2018** [comment]
> Hi @LMR2018, Have you tried doing like this https://stackoverflow.com/questions/53664279/converting-tflite-to-pb. Did you encounter any error ?

Did you say this is how to transform?  

tensorflow_1.12/tensorflow/bazel-bin/tensorflow/contrib/lite/toco/toco -- 
output_file=coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.pb -- 
output_format=TENSORFLOW_GRAPHDEF --input_format=TFLITE -- 
input_file=coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.tflite -- 
inference_type=FLOAT --input_type=FLOAT --input_array="" --output_array="" -- 
input_shape=1,450,450,3 --dump_grapHviz=./

**Comment by LMR2018** [comment]
> Hi @LMR2018, Have you tried doing like this https://stackoverflow.com/questions/53664279/converting-tflite-to-pb. Did you encounter any error ?

import numpy as np
import tensorflow as tf

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="converted_model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

This step is normal, how to convert hand_landmark_lite.tflite into PB model?

**Comment by sgowroji** [comment]
Is it possible Duplicate https://github.com/google/mediapipe/issues/2853#issuecomment-986884141 ?
