### ISSUE TITLE
Is there a chance to process mult-person keypoints in one image?

### ISSUE THREAD

**Issue by Syencil** [google/mediapipe#2771]
blazepose is a wonderful method to get pose landmarks. however, i found this in annotation(mediapipe.solutions.pose.process)——“Processes an RGB image and returns the pose landmarks on the most prominent person detected.” 
i dont wanna miss other people in image. what should i do?

**Comment by sgowroji** [comment]
Hi @Syencil,  This is what you can do at present https://github.com/google/mediapipe/issues/1691#issuecomment-797159603
