### ISSUE TITLE
Build getting failed on Raspberry Pi 4 8 GB

### ISSUE THREAD

**Issue by hasankhurshid29** [google/mediapipe#2775]
https://spyjetson.blogspot.com/2021/06/installing-mediapipecpu-mode-on.html
OS: Raspbian OS Latest 64 Bit
I am following the steps given in the above link. 
On step: # python3 setup.py bdist_wheel
The build get failed and show this error: 
ERROR: /usr/local/src/mediapipe/mediapipe/calculators/tensor/BUILD:127:11: C++ compilation of rule '//mediapipe/calculators/tensor:inference_calculator_cpu' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 162 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 162 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./mediapipe/calculators/tensor/inference_calculator.h:25,
from mediapipe/calculators/tensor/inference_calculator_cpu.cc:21:
./mediapipe/framework/api2/node.h: In substitution of 'template<class _Functor, class, class> std::function<std::unique_ptrmediapipe::internal::CalculatorBaseFactory()>::function(_Functor) [with _Functor = ; = ; = ]':
./mediapipe/framework/api2/node.h:89:55: required from 'static mediapipe::RegistrationToken mediapipe::api2::internal::NodeRegistrationStatic::Make() [with T = mediapipe::api2::InferenceCalculatorCpuImpl]'
./mediapipe/framework/api2/node.h💯76: required from 'mediapipe::NoDestructormediapipe::RegistrationToken mediapipe::api2::internal::NodeRegistrationStaticmediapipe::api2::InferenceCalculatorCpuImpl::registration'
./mediapipe/framework/api2/node.h:94:51: required from 'struct mediapipe::api2::internal::NodeRegistrationStaticmediapipe::api2::InferenceCalculatorCpuImpl'
./mediapipe/framework/api2/node.h:136:67: required from 'class mediapipe::api2::RegisteredNodemediapipe::api2::InferenceCalculatorCpuImpl'
./mediapipe/framework/api2/node.h:151:7: required from 'class mediapipe::api2::NodeImpl<mediapipe::api2::InferenceCalculatorCpu, mediapipe::api2::InferenceCalculatorCpuImpl>'
mediapipe/calculators/tensor/inference_calculator_cpu.cc:67:14: required from here
./mediapipe/framework/api2/node.h:89:55: internal compiler error: Segmentation fault
89 | return mediapipe::CalculatorBaseRegistry::Register(
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
90 | T::kCalculatorName,
| ~~~~~~~~~~~~~~~~~~~
91 | absl::make_unique<mediapipe::internal::CalculatorBaseFactoryFor>);
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0x7f84d70217 __libc_start_main
../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See file:///usr/share/doc/gcc-10/README.Bugs for instructions.
Target //mediapipe/modules/face_detection:face_detection_short_range_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1262.720s, Critical Path: 1034.02s
INFO: 902 processes: 245 internal, 657 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by sgowroji** [comment]
Hi @hasankhurshid29, You can refer this https://github.com/jiuqiant/mediapipe_python_aarch64 from MediaPipe documentation as mentioned [here](https://google.github.io/mediapipe/getting_started/python.html#building-mediapipe-python-package)

**Comment by hasankhurshid29** [comment]
Not working

**Comment by sgowroji** [comment]
Please follow the instructions and steps mentioned here 

MediaPipe PyPI currently doesn’t provide aarch64 Python wheel files. For building and using MediaPipe Python on aarch64 Linux systems such as Nvidia Jetson and Raspberry Pi, please read [here](https://github.com/jiuqiant/mediapipe_python_aarch64).
