### ISSUE TITLE
What are the mean and STD capabilities of hand_landmark_lite.tflite training data after data augmentation?  

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#2778]
What are the mean and STD capabilities of hand_landmark_lite.tflite training data after data augmentation?

**Comment by LMR2018** [comment]
@sgowroji    I want to know the mean_values and std_values of mediapipe/modules/hand_landmark/hand_landmark_lite.tflite model training

**Comment by ayushgdev** [comment]
Hello @LMR2018 
You can find the mean and STD values for hand_landmark model in the page 5 of [model card of hand solution](https://drive.google.com/file/d/1-rmIgTfuCbBPW_IFHkh3f0-U_lnGrWpg/preview).
