### ISSUE TITLE
TensorFlow graph model for selfie segmentation

### ISSUE THREAD

**Issue by albertxing** [google/mediapipe#2779]
**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): Selfie segmentation
- Programming language: JS/TS
- Are you willing to contribute it (Yes/No): No (unable to)

**Describe the feature and the current behavior/state:**
Only TFLite models are currently publicly released. Are there plans to make the uncompressed (non-TFLite) graph models available?

**Please specify the use cases for this feature:**
Some platforms are unable to run TFLite, notably WebGL. However, the TF.js WebGL backend is able to run uncompressed JSON graph models.

TFLite is available in the browser, but only through WASM, which may not be compatible with all use cases.

**Comment by mhays-google** [comment]
The solution does not willingly expose TFlite models, and does not currently run under WebGL.  A WebGL inference engine may be in the works, but I have no timeline for this feature.
