### ISSUE TITLE
I want to know the mean_values and std_values of mediapipe/modules/hand_landmark/hand_landmark_lite.tflite model training  

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#2780]
I want to know the mean_values and std_values of mediapipe/modules/hand_landmark/hand_landmark_lite.tflite model training  

Can you convert mediapipe/modules/hand_landmark/hand_landmark_lite.tflite model to .pb model, I am new, can you give me the code?

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2778

**Comment by sgowroji** [comment]
We are closing this issue as we already marked the above issue to a duplicate one and an engineer assigned to address it.
