### ISSUE TITLE
Request FaceMesh on side-face support

### ISSUE THREAD

**Issue by linyu0219** [google/mediapipe#2781]
Facemesh is very useful, itself has detecting and tracking, I like use it in my work.
But it can not get landmark now when a face is side like below, 
![studio_168](https://user-images.githubusercontent.com/29172715/142121727-153d7514-0a2f-4407-876e-c2d7a28a51e1.jpg)
Can add side face support in future?
Maybe it can't detect side face in detection phase.

**Comment by linyu0219** [comment]
I don't know why first time the landmark can't get, but in second time I got it .

**Comment by linyu0219** [comment]
![raw_131](https://user-images.githubusercontent.com/29172715/142129469-62fd74a1-04cc-4c78-8bfe-d40bd8b6b629.jpg)

**Comment by sgowroji** [comment]
Hi @linyu0219, Could you please share on which platform are you seeing the above?

**Comment by linyu0219** [comment]
> Hi @linyu0219, Could you please share on which platform are you seeing the above?

python linux latest version

**Comment by sgowroji** [comment]
Its Large feature request, require new model, thats not in present roadmap. We have shared this request to the product team.
