### ISSUE TITLE
Ensuring the version of tflite models used in Python API

### ISSUE THREAD

**Issue by codeastra2** [google/mediapipe#2782]
Hello , thanks so much for the awesome mediapipe Python package, it's super helpful!
I noticed that this package uses tflite models as part of it's implementation. However, I was wondering if there was way to verify that these are the latest packages as per the [documentation](https://google.github.io/mediapipe/solutions/models.html#face-mesh) ? I did see the [PyPi release page](https://pypi.org/project/mediapipe/#history),  but would there be a way to verify that these releases contain the latest models? Thanks again!

**Comment by jiuqiant** [comment]
Hi, we build the PyPI packages per GitHub release. So, the MediaPipe version number in GitHub and the PyPI package version should be the same and the tflite models in PyPI packages should always be the latest ones.
