### ISSUE TITLE
How to get pose_world_landmarks in Android?

### ISSUE THREAD

**Issue by Ar4enal** [google/mediapipe#2783]
I am using custom holistic binarypb. I edited the pbtxt like this: 
just add  _output_stream: "WORLD_LANDMARKS:pose_world_landmarks"_
![image](https://user-images.githubusercontent.com/36718239/142169526-7a424e70-8c8f-42c8-8e93-e705aedc6de1.png)

It shows this error:
_while processing the output streams of subgraph node HolisticLandmarkGpu: ; Tag "WORLD_LANDMARKS" does not exist in the subgraph config._
![image](https://user-images.githubusercontent.com/36718239/142169293-7b309ecd-969a-41db-8712-d1a96340a799.png)

**Comment by sgowroji** [comment]
Hi @Ar4enal, Could you please provide steps to reproduce the above error. Thanks!

**Comment by Ar4enal** [comment]
@sgowroji  ok
First I custom the holistic binary graph by adding output_stream. It is based on _mediapipe\graphs\holistic_tracking\holistic_tracking_gpu.pbtxt_

I add some output streams like pose landmark and face landmark:
[https://github.com/Ar4enal/Avatar/blob/master/app/src/main/assets/holistic_world_tracking_gpu.pbtxt](url)

Then I bazel build this graph:
[https://github.com/Ar4enal/mp_ae_holis/blob/master/app/src/main/assets/holistic_world_tracking_gpu.binarypb](url)


I change the binaryGraphName to _holistic_world_tracking_gpu.binarypb_ in example code:
 ```
AndroidAssetUtil.initializeNativeAssetManager(this);
    eglManager = new EglManager(null);
    processor =
        new FrameProcessor(
            this,
            eglManager.getNativeContext(),
            applicationInfo.metaData.getString("binaryGraphName"),  //holistic_world_tracking_gpu.binarypb
            applicationInfo.metaData.getString("inputVideoStreamName"),
            applicationInfo.metaData.getString("outputVideoStreamName"));
```

And last I run the code it shows _Tag "WORLD_LANDMARKS" does not exist in the subgraph config._ error.

**Comment by sgowroji** [comment]
For pose world landmarks you can find in this file [gpu](https://github.com/google/mediapipe/blob/33d683c67100ef3db37d9752fcf65d30bea440c4/mediapipe/modules/pose_landmark/pose_landmark_gpu.pbtxt) and [cpu](
https://github.com/google/mediapipe/blob/33d683c67100ef3db37d9752fcf65d30bea440c4/mediapipe/modules/pose_landmark/pose_landmark_cpu.pbtxt#:~:text=%23%20Pose%20world%20landmarks,output_stream%3A%20%22WORLD_LANDMARKS%3Apose_world_landmarks%22)
