### ISSUE TITLE
Crossbuild to aarch64 with glibc_2.27

### ISSUE THREAD

**Issue by gk6k6k** [google/mediapipe#2785]
**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04, with cross compiler gnu gcc aarch64
- Compiler version: gcc/g++ 8 and gcc/g++ 9
- Programming Language and version: C++ 14
- Installed using virtualenv? no, full git clone
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.6
- Bazel version: 3.7.2
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): 3.4

Hi all, I try to deploy my application on aarch64 (raspberry pi as test machine) but do not compile whole on the target machine. The problem is that the target machine supports glibc 2.27 only and I cannot upgrade it.

I have Ubuntu 20.04 as a source machine, tried to cross-build it for aarch64, and it works. But it requires glibc 2.29 (version from the source machine). So I try to force it to build with 2.27 without any success.

I try to change target glibc in: mediapipe/external/crosstool/cc_toolchain_config.bzl from "target_libc = local" to "target_libc = glibc-2.27"

iris_tracking_cpu will build but I have an error on runtime
libm.so.6: version 'GLIB_C_2.29' not found (required by libiris_tracking_cpu.so)

Please remember that I cannot upgrade glibc on target.

Used build command:
bazel --output_base=./tmp_build build --crosstool_top=@crosstool//:toolchains --features=-supports_dynamic_linker --compiler=gcc --cpu=aarch64 -c opt --force_pic --define MEDIAPIPE_DISABLE_GPU=1 run_mediapipe/iris_tracking_cpu

**Comment by kuaashish** [comment]
Hello @gk6k6k,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
