### ISSUE TITLE
[Android] Custom / Build pose_tracking have no effect

### ISSUE THREAD

**Issue by 3myr** [google/mediapipe#2788]
--------------------------------------------
**System information**
- Linux Ubuntu 18.04
- Bazel version: 
  - Bazelisk version: v1.10.1
  - Build label: 3.7.2

- Solution :
  - Pose
- Programming Language and version :
  - Java
  - Gradle
- Archetype used :
  - https://github.com/yuxiaohui78/Mediapipe-android-pose-tracking
--------------------------------------------

I want to custom the landmarks output ( color, thickness, etc... ) so i modify the .pbtxt file : 
```
mediapipe/graphs/pose_tracking/subgraphs
```
For my test, i change the color of landmarks and delete connections.

After that, to be sure i got a clean environment, i go to my directory mediapipe and run : 
```
bazel clean
bazel shutdown
```

Then : 
```
bazel build -c opt --strip=ALWAYS --host_crosstool_top=@bazel_tools//tools/cpp:toolchain     --fat_apk_cpu=arm64-v8a,armeabi-v7a mediapipe/graphs/pose_tracking:pose_tracking_gpu_binary_graph
```

I go to :
```
mediapipe/bazel-bin/mediapipe/graphs/pose_tracking
```

and copy the pose_tracking_gpu.binarypb generated into my app/assets/

So i got :
- pose_detection.tflite
- pose_landmark_full.tflite
- pose_tracking_gpu.binarypb

But when i build my apk with gradle ( installDebug ), i don't see the modification.

I'm a beginner with mediapipe and i don't know what i did wrong.

**Comment by jiuqiant** [comment]
I think the following steps should update the graph file in the android project:
1) modify pose_renderer_gpu.pbtxt
2) build the "pose_tracking_gpu_binary_graph" target
3) copy the generated binarypb into the assets dir

If you don't see those changes, you can first build the mediapipe pose example app (https://google.github.io/mediapipe/solutions/pose#mobile) with the modified pose_renderer_gpu.pbtxt to see if your modifications are valid or not.
