### ISSUE TITLE
Whether the output of the hand landmark model is the keypoint obtained by regression?

### ISSUE THREAD

**Issue by NeekHua** [google/mediapipe#2789]
If inscribe

**Comment by NeekHua** [comment]
Using this open source model[https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_lite.tflite](url)

**Comment by sgowroji** [comment]
Hi @NeekHua, Could you please elaborate your query with complete details. Thanks!

**Comment by NeekHua** [comment]
@sgowroji Hello,I'm using this open source model[https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_lite.tflite](url)to detect hand_landmark.My using language is Python,tensorflow version is 1.15.
Now I use my own hand_detect model to crop the picture that contains the hand and resize 224  for land_mark_lite.tflite input data.
My question is that how do the key points of the model's output appear on the original diagram.Whether the output of the hand landmark model is the keypoint obtained by regression?
I read postprocess have normhandlandmarklist ,whether it is  divide 224?

**Comment by NeekHua** [comment]
and I find this  hand_landmark_lite.tflite is not accuracy.I want to ask why mediapipe package have high acccuracy.Whether is it use this model?
