### ISSUE TITLE
I want to use Android system for hand_landmark, the official default model is hand_landmark_full. Tflite model, I want to replace it with hand_landmark_lite.  

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#2791]
I want to use Android system for hand_landmark, the official default model is hand_landmark_full. tflite model, I want to replace it with hand_landmark_lite model， How do I change android's configuration?

**Comment by sgowroji** [comment]
Hi @LMR2018, You can find the Android Hands Gradle Solution https://google.github.io/mediapipe/solutions/hands#android-solution-api

**Comment by sgowroji** [comment]
Hi @LMR2018, Could you please see the solution parameter "model_complexity", this substitutes between two models.  
https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/solutions/hands/HandsOptions.java#L50.
