### ISSUE TITLE
How I can save image in phone gallery after detection in facemesh?

### ISSUE THREAD

**Issue by Shakirsadiq6** [google/mediapipe#2792]
I am using facemesh mediapipe for liveness detection using JAVA which I have achieved using landmarks to check blink detection. Now if a person blinked I want my camera to capture the image of that person.

**Comment by sgowroji** [comment]
Hi @Shakirsadiq6, This comment will help you understand the eye blinking detection.  Once you receive the detection  event you can implement the camera capture function.

**Comment by Shakirsadiq6** [comment]
Hi @sgowroji, I already have achieved the detection, I want to know how I can implement camera capture function. Any references please?

**Comment by sgowroji** [comment]
Its not a use case with mediapipe but you can find multiple examples w.r.t your requirement. I can share you some https://stackoverflow.com/questions/9744790/how-to-take-camera-capture-without-a-preview-from-a-service-or-thread
