### ISSUE TITLE
What is the difference between hand_landmark_lite.tflite and hand_landmark_full.tflite?  Can I replace hand_landmark_full.tflite with hand_landmark_lite.tflite?  The hand_landmark_lite.tflite model looks smaller  

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#2794]
What is the difference between hand_landmark_lite.tflite and hand_landmark_full.tflite?  Can I replace hand_landmark_full.tflite with hand_landmark_lite.tflite?  The hand_landmark_lite.tflite model looks smaller

**Comment by sgowroji** [comment]
Hi @LMR2018, You can find the complete details from here https://drive.google.com/file/d/1-rmIgTfuCbBPW_IFHkh3f0-U_lnGrWpg/preview
