### ISSUE TITLE
Python failed to load the hand_landmark_tracking_gpu.binarypb model.  Can Hand_landmark Python use a GPU?  

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#2796]
C:\Users\Dev16\Anaconda3\lib\site-packages\mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu.binarypb
Traceback (most recent call last):
  File "F:/murong/projects1/mediapipe_master/mediapipe/python/predict_test.py", line 19, in <module>
    min_detection_confidence=0.5) as hands:
  File "C:\Users\Dev16\Anaconda3\lib\site-packages\mediapipe\python\solutions\hands.py", line 128, in __init__
    'multi_handedness'
  File "C:\Users\Dev16\Anaconda3\lib\site-packages\mediapipe\python\solution_base.py", line 239, in __init__
    binary_graph_path=os.path.join(root_path, binary_graph_path))
RuntimeError: ValidatedGraphConfig Initialization failed.
FromImageCalculator: ; GPU is disabled. Cannot use IMAGE_GPU stream./from_image_calculator.cc:96) 
ImageTransformationCalculator::GetContract failed to validate: 
For input streams ValidatePacketTypeSet failed:
Tag "IMAGE_GPU" index 0 was not expected.
For output streams ValidatePacketTypeSet failed:
Tag "IMAGE_GPU" index 0 was not expected.
No registered object with name: HandLandmarkTrackingGpu; Unable to find Calculator "HandLandmarkTrackingGpu"

**Comment by sgowroji** [comment]
Hi @LMR2018, Could you please provide steps to reproduce the above error. Thanks!

**Comment by LMR2018** [comment]
> 嗨@LMR2018，您能否提供重现上述错误的步骤。谢谢！

Anaconda3\lib\site-packages\mediapipe\python\solutions\hands.py default loading _BINARYPB_FILE_PATH =  'mediapipe/modules/hand_landmark/ hand_landmark_tracking_CPU. binarypb' is replaced with _BINARYPB_FILE_PATH =  'mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu.binarypb', then put hand_landmark_tracking_gpu.binarypb into the appropriate path,  Run directly is this error

**Comment by LMR2018** [comment]
> 嗨@LMR2018，您能否提供重现上述错误的步骤。谢谢！

Anaconda3\lib\site-packages\mediapipe\python\solutions\hands.py default loading _BINARYPB_FILE_PATH =  'mediapipe/modules/hand_landmark/ hand_landmark_tracking_CPU. binarypb' is replaced with _BINARYPB_FILE_PATH =  'mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu.binarypb', then put hand_landmark_tracking_gpu.binarypb into the appropriate path,  Run directly is this error

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2126
