### ISSUE TITLE
Face Mesh GPU - TfLiteGpuDelegate Prepare: Program is not properly linked

### ISSUE THREAD

**Issue by magorors** [google/mediapipe#2797]
**System information** 
- Using example face mesh code.
- JetPack 4.6 (Ubuntu 18.04) - Jetson AGX Xavier 
- MediaPipe version: v0.8.8
- Bazel version: 3.7.2
- Solution: FaceMesh
- Programming Language: C++

**Describe the expected behavior:**
I built both the Face Mesh CPU and GPU version on the Jetson AGX Xavier, the CPU implementation works. In case of the Hand Tracking solution both the CPU and GPU one works, but **when I try to run the Face Mesh with GPU it gives me the following error which I couldn't solve yet:**

INFO: Created TensorFlow Lite delegate for GPU.
ERROR: TfLiteGpuDelegate Prepare: Program is not properly linked: Compute info
---------------------
0(84) : error C1068: array index out of bonds
0(84) : error C1068: array index out of bonds
0(84) : error C1068: array index out of bonds
0(84) : error C1068: array index out of bonds
0(84) : error C1068: array index out of bonds
......
0(96) : error C1068: array index out of bonds
......
when I try to run the Face Mesh with GPU it gives me the following error which I couldn't solve yet:
ERROR: Node number 712 (TfLiteGpuDelegate) failed to prepare
ERROR: Restored original execution plan after delegate application failure. ... demo_run_graph_main_gpu.cc:186] Shutting down. Segmentation fault (core dumped).

To reproduce the error: I simply followed the installation instructions for Ubuntu with GPU:

https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu
https://google.github.io/mediapipe/getting_started/gpu_support.html#opengl-es-setup-on-linux-desktop

Please help me if you had this problem before. Thank you in advance. :)

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2678

**Comment by sgowroji** [comment]
Closing as per duplicates issue resolved with this https://github.com/google/mediapipe/issues/2678#issuecomment-989348636

**Comment by sgowroji** [comment]
Hi @magorors, Could you please go through this https://github.com/google/mediapipe/issues/2678#issuecomment-989348636
