### ISSUE TITLE
macOS arm64 (lack of) support should be documented

### ISSUE THREAD

**Issue by justin-f-perez** [google/mediapipe#2798]
## URL(s) with the issue:

https://github.com/google/mediapipe/blob/master/docs/getting_started/python.md
https://github.com/google/mediapipe/blob/master/docs/getting_started/ios.md
https://github.com/google/mediapipe/blob/master/docs/getting_started/install.md#installing-on-macos

## Description of issue (what needs changing):

On some paths through the Getting Started documentation, it's not clear that arm64 macs are unsupported at the moment. For example, the [Android docs](https://google.github.io/mediapipe/getting_started/android) send you to [install on mac](https://google.github.io/mediapipe/getting_started/install.html#installing-on-macos) which has you try- and fail- to build and run the C++ Hello World demo.

It seems arm64 macOS is unsupported, but that information isn't easy to find in the docs.
* ["M1" site:mediapipe.dev](https://www.google.com/search?q=%22M1%22+site%3Amediapipe.dev&oq=%22M1%22+site%3Amedia&aqs=chrome.1.69i57j69i59.9312j0j7&sourceid=chrome&ie=UTF-8)
* ["arm64" "darwin" site:mediapipe.dev](https://www.google.com/search?q=%22arm64%22+%22darwin%22+site%3Amediapipe.dev&oq=%22arm64%22+%22darwin%22+site%3Amediapipe.dev&aqs=chrome..69i57.306j0j7&sourceid=chrome&ie=UTF-8)
* ["rosetta" site:mediapipe.dev](https://www.google.com/search?q=%22rosetta%22+site%3Amediapipe.dev&sxsrf=AOaemvJGKvYof1cp8pggcnBcm8cGQqn4Yg%3A1637175774243&ei=3lGVYd2eDsKStAb-xJFI&oq=%22rosetta%22+site%3Amediapipe.dev&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGAFQ7QRY-CJg8iRoAnAAeACAAWuIAbEKkgEEMTUuMZgBAKABAcABAQ&sclient=gws-wiz&ved=0ahUKEwjdhdWDi6D0AhVCCc0KHX5iBAkQ4dUDCA4&uact=5)
* ["arm64" "mac"](https://www.google.com/search?q=%22arm64%22+%22mac%22+site%3Amediapipe.dev&sxsrf=AOaemvIuS6B7qjS5Xb0pO5qHhk3cisGLrA%3A1637175798802&ei=9lGVYaGsMIHWtQbapL2ABw&oq=%22arm64%22+%22mac%22+site%3Amediapipe.dev&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGAFQ8whY0BpgkyBoAnAAeACAAYcBiAGbB5IBBDEwLjGYAQCgAQHAAQE&sclient=gws-wiz&ved=0ahUKEwih_6-Pi6D0AhUBa80KHVpSD3AQ4dUDCA4&uact=5)

### Current state
This is a [common and unexpected outcome for new developers](https://stackoverflow.com/questions/68451012/what-could-be-the-alternative-type-of-darwin-arm64-on-bazel-3-7-2-for-setting)
```sh
❯ git clone https://github.com/google/mediapipe.git && cd mediapipe
❯ bazel --version # or <anything> - the release doesn't exist. This always fails.
2021/11/13 18:45:31 Downloading https://releases.bazel.build/3.7.2/release/bazel-3.7.2-darwin-arm64...
2021/11/13 18:45:32 could not download Bazel: HTTP GET https://releases.bazel.build/3.7.2/release/bazel-3.7.2-darwin-arm64 failed with error 404
```

[PRs adding M1 support](https://github.com/google/mediapipe/pull/2591)  but
> MediaPipe with its TensorFlow dependence needs Bazel to build everything from scratch. I don't think bazel already supports M1 yet: bazelbuild/bazel#11628.
[11 months ago](https://github.com/google/mediapipe/issues/1514#issuecomment-763029564) #1514
and
[tensorflow must upgrade first](https://github.com/google/mediapipe/issues/2516)

## Getting Started > Python docs

> MediaPipe currently doesn't support arm macOS.
[5 months ago](https://github.com/google/mediapipe/issues/2120#issuecomment-858163183)

> The wheels are for x86_64 only.
[9 months ago](https://github.com/google/mediapipe/issues/1622#issuecomment-780017724) 

### install on macos without conda
see [this thread](https://github.com/google/mediapipe/issues/2120#issuecomment-894796864) for how to install without conda

### install on macos with conda
These instructions assume `conda` is already installed (e.g. via `brew install --cask miniconda && conda init && exec zsh`)

1. create `environment.yml` file:
```yaml
name: mediapipe-x86
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - mediapipe>=0.8.9
variables:
  CONDA_SUBDIR: osx-64
```

2. create env (installs dependencies, including python and mediapipe)
```shell
$ conda env create --file environment.yml
$ conda activate mediapipe-x86

# test installation
$ python3 -c 'print("this make take a few moments..."); import mediapipe; import cv2; print("ok");'
```

## Installation > macOS docs

For example the following text could be added to the Installing on macOS section instructing users to attempt to build 'Hello world', "x86_64 only; macOS arm64 is currently unsupported. Please check back later."

**Comment by justin-f-perez** [comment]
Here's a path of less resistance users getting started with mediapipe python solutions on darwin arm64.

These instructions assume `conda` is already installed (e.g. via `brew install --cask miniconda && conda init && exec zsh`)

1. create `environment.yml` file:
```yaml
name: mediapipe-x86
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - mediapipe>=0.8.9
variables:
  CONDA_SUBDIR: osx-64
```

2. create env (installs dependencies, including python and mediapipe)
```shell
$ conda env create --file environment.yml
$ conda activate mediapipe-x86
```

3. test installation
```shell
$ python3 -c 'print("this make take a few moments..."); import mediapipe; import cv2; print("ok");'
```

**Comment by justin-f-perez** [comment]
Closing since I've moved on to other projects and won't be able to keep this issue up to date

**Comment by sureshdagooglecom** [comment]
Hi @justin-f-perez ,
We don't support to support MAC OS Arm64 in MediaPipe due to limited support we have but sharing this with internal team.

**Comment by justin-f-perez** [comment]
> Hi @justin-f-perez ,
> We don't support to support MAC OS Arm64 in MediaPipe due to limited support we have but sharing this with internal team.

many thanks. In retrospect, mediapipe works normally as long as you find a to advertise as x86_64. I updated the last sentence of the issue. (To suggest referencing the manufacturer docs instead of "try again later")

overall problem isnt that mediapipe and other projects *can't* run on these machines- it's that they refuse to, because it appears to be an unsupported platform. If the user tricks the build tools into thinking they're running on x86_64,  the emulator works well.

**Comment by albert239825** [comment]
Hello, I would just like to express my interest in this feature. I have an M1 Macbook Pro and I'm trying to figure out a method to use the mediapipe library in a python project. Any help would be greatly appreciated. Thanks!

**Comment by justin-f-perez** [comment]
@albert239825 
```shell
# create the environment using x86_64 python3
❯ conda create --name=my_mediapipe_environment --override-channels --channel='conda-forge/osx-64' python

# below line causes 'conda activate <env name>' to export CONDA_SUBDIR=osx-64
# this causes conda to look exclusively for x86_64 packages while the environment
# is active (thus, 'conda install' you do while the environment is active is sure
# to use the same architecture as your python)
❯ conda env config vars set --name=my_mediapipe_environment CONDA_SUBDIR=osx-64

# activate the environment
❯ conda activate my_mediapipe_environment

# install meidapipe, it works!
❯ pip install mediapipe

# test import mediapipe just be sure
❯ python -c 'import mediapipe'

# NOTE: it does *actually* work beyond just importing
```

**Comment by ah3243** [comment]
> @albert239825
> 
> ```shell
> # create the environment using x86_64 python3
> ❯ conda create --name=my_mediapipe_environment --override-channels --channel='conda-forge/osx-64' python
> 
> # below line causes 'conda activate <env name>' to export CONDA_SUBDIR=osx-64
> # this causes conda to look exclusively for x86_64 packages while the environment
> # is active (thus, 'conda install' you do while the environment is active is sure
> # to use the same architecture as your python)
> ❯ conda env config vars set --name=my_mediapipe_environment CONDA_SUBDIR=osx-64
> 
> # activate the environment
> ❯ conda activate my_mediapipe_environment
> 
> # install meidapipe, it works!
> ❯ pip install mediapipe
> 
> # test import mediapipe just be sure
> ❯ python -c 'import mediapipe'
> 
> # NOTE: it does *actually* work beyond just importing
> ```
> 
> The alternative is to install an x86_64 python yourself and manually manage the environment. I don't recommend it. If you don't have `conda`, you can get it through homebrew via `brew install miniconda`

You have no idea how long I've been looking or trying different solutions for this. I kept and old macbook just to debug mediapipe applications. Incredible thank you!

**Comment by justin-f-perez** [comment]
> > @albert239825
> > ```shell
> > # create the environment using x86_64 python3
> > ❯ conda create --name=my_mediapipe_environment --override-channels --channel='conda-forge/osx-64' python
> > 
> > # below line causes 'conda activate <env name>' to export CONDA_SUBDIR=osx-64
> > # this causes conda to look exclusively for x86_64 packages while the environment
> > # is active (thus, 'conda install' you do while the environment is active is sure
> > # to use the same architecture as your python)
> > ❯ conda env config vars set --name=my_mediapipe_environment CONDA_SUBDIR=osx-64
> > 
> > # activate the environment
> > ❯ conda activate my_mediapipe_environment
> > 
> > # install meidapipe, it works!
> > ❯ pip install mediapipe
> > 
> > # test import mediapipe just be sure
> > ❯ python -c 'import mediapipe'
> > 
> > # NOTE: it does *actually* work beyond just importing
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The alternative is to install an x86_64 python yourself and manually manage the environment. I don't recommend it. If you don't have `conda`, you can get it through homebrew via `brew install miniconda`
> 
> You have no idea how long I've been looking or trying different solutions for this. I kept and old macbook just to debug mediapipe applications. Incredible thank you!

Glad it helped! It looks like you may be able to install natively on M1 now too thanks to a community member building arm64 wheels under a different package name: #3277 I haven't tried this yet though
