### ISSUE TITLE
Selfie Segmentation JS bindings do not run without `unsafe-eval`

### ISSUE THREAD

**Issue by ostap0207** [google/mediapipe#2799]
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Chrome 96
- Programming Language and version ( e.g. C++, Python, Java): JavaScript
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.5
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ): Selfie Segmentation

**Describe the current behavior:**
MediaPipe Selfie Segmentation library does not work without `unsafe-eval` CSP. This is because https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1.1632777926/selfie_segmentation_solution_simd_wasm_bin.js contains dynamically generated code via `Function`.
Adding `unsafe-eval` is not always an option as it less secure.

We are aware that wasm will not run without `unsafe-eval` either, but that is a separate issue and is being mitigated in Chrome by a new CSP [wasm-unsafe-eval](https://www.chromestatus.com/feature/5499765773041664).

**Describe the expected behavior:**
MediaPipe Selfie Segmentation JS bindings works without `unsafe-eval`.

**Standalone code to reproduce the issue:**
https://ostap0207.github.io/mediapipe-selfie-segmentation-csp/index.html
Code: https://github.com/ostap0207/mediapipe-selfie-segmentation-csp/blob/master/index.html
This page has SCP set to disallow `unsafe-eval`.

Error in the console:

```
selfie_segmentation_solution_wasm_bin.js:9 Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src https://cdn.jsdelivr.net".

    at new Function (<anonymous>)
    at createNamedFunction (selfie_segmentation_solution_wasm_bin.js:9)
    at extendError (selfie_segmentation_solution_wasm_bin.js:9)
    at selfie_segmentation_solution_wasm_bin.js:9
    at qa.h (selfie_segmentation.js:50)
    at ta (selfie_segmentation.js:14)
    at ua.next (selfie_segmentation.js:15)
    at selfie_segmentation.js:40
    at new Promise (<anonymous>)
    at Y (selfie_segmentation.js:40)
```

emscripten used to have a flag `NO_DYNAMIC_EXECUTION`, however even it was removed https://github.com/emscripten-core/emscripten/issues/5911, so there should be no need for dynamic execution.

**Comment by mhays-google** [comment]
There are no plans to add this at this time, but members of the team are now aware of this issue.

**Comment by akbar-animaker** [comment]
@mhays-google is there any possibility to take that priority to fix that issue.. Because of that we were unable to proceed next steps to use mediapipe

**Comment by kaseyhackspace** [comment]
Is there any workaround for this issue?

**Comment by mark-beeby** [comment]
@ostap0207 were you able to work around this? I've manipulated the wasm_bin.js to some success (removed a couple of the evals successfully) but ultimately the code architecture is incredibly difficult to unwind and remove the reliance on `createNamedFunction`.

**Comment by SridhuSekar** [comment]
To make selfie segmentation JS bindings do run without unsafe-eval after migrating selfie segmentation from manifest V2 to V3 without using the unsafe-eval. You will have to replace the files with the one in the below link. Which worked for me in my project.
https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1.1675465747/

**Comment by mmerezhko-hv** [comment]
> To make selfie segmentation JS bindings do run without unsafe-eval after migrating selfie segmentation from manifest V2 to V3 without using the unsafe-eval. You will have to replace the files with the one in the link below. Which worked for me in my project. https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1.1675465747/

Are there any other workarounds?

**Comment by luciancioroga** [comment]
This solution doesn't work, still breaking the CSP due to attempting to append a <script> inline:
`line 65: ... var b=document.createElement("script");b.setAttribute("src",a);b.setAttribute("crossorigin","anonymous");return new Promise(function(c){b.addEventListener("load",function(){c()},!1);b.addEventListener("error",function(){c()},!1);document.body.appendChild(b)})`
