### ISSUE TITLE
Minor bazel definition bug with building the hands example/solution from source

### ISSUE THREAD

**Issue by matanster** [google/mediapipe#2801]
# Version Information
Pulling from [the following commit](https://github.com/google/mediapipe/commit/cf101e62a9d49a51be76836b2b8e5ba5c06b5da0) from master, which is the latest commit on that branch today. 

# Problem Description and Workaround
On Ubuntu 20.04, I have set up to build the hands solution from source, by following here ― https://google.github.io/mediapipe/getting_started/cpp.html#building-c-command-line-example-apps

I have made the modifications to the build files `WORKSPACE` and to `third_parties/open_cv_linux.BUILD` for using OpenCV 4. 

After having succeeding in building the hello world dummy solution (using the instructions from [here](https://google.github.io/mediapipe/getting_started/hello_world_cpp.html)), I encountered trouble building the hands solution.

As long as the following build command is supposed to work when the working directory is the project top level directory:
```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
```

Then it may seem as if the following line is missing in the build file [`opencv_linux.BUILD`](https://github.com/google/mediapipe/blob/cf101e62a9d49a51be76836b2b8e5ba5c06b5da0/third_party/opencv_linux.BUILD):
```
package(default_visibility = ["//visibility:public"])
```

I have added it myself, which enables the build to proceed. Issue solved. Looks like an inadvertent omission in the source code. 

# How to Handle missing OpenCV header file when building examples from source

The remainder of this post is just helpful if like me, anyone built and installed OpenCV from source while forgetting to build it with OpenCV contrib. Building some MediaPipe examples/solutions will require having OpenCV built & installed with its contrib codebase, so that they will find some contrib code which they require for their own complication. 

```
ERROR: mediapipe/examples/desktop/BUILD:38:11: C++ compilation of rule '//mediapipe/examples/desktop:demo_run_graph_main' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 61 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 61 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from mediapipe/examples/desktop/demo_run_graph_main.cc:26:
./mediapipe/framework/port/opencv_video_inc.h:88:10: fatal error: opencv2/optflow.hpp: No such file or directory
   88 | #include <opencv2/optflow.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

This is after successfully building and installing OpenCV 4.5.4 from source, optflow.hpp is simply not part of the OpenCV basic build.

The thing is that OpenCV (version 4.5.4 and like other versions too) simply doesn't have/install the particular header file `optflow.hpp`, it rather installs as part of OpenCV's contrib code repository. You just need to build OpenCV along with its contrib codebase. [The build command for that is specified in the online documentation](https://docs.opencv.org/4.5.4/d7/d9f/tutorial_linux_install.html). This will enable building the above MediaPipe example as intended, give or take some standard make/bazel clean commands. 

Disclaimer: I ended up building OpenCV 4.2.0, after seeing that it is the recommended (?) version for my version of Ubuntu as per Mediapipe docs [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu).

HTH.

**Comment by sgowroji** [comment]
Hi @matanster, You can find some help from this https://github.com/google/mediapipe/issues/970#issuecomment-667219458

**Comment by matanster** [comment]
Sure thanks. Anyway, I think the bazel file visibility omission might be a small newly introduced build bug, or I can't figure why it is so sensible to add it as a way for enabling the build of the example hands pipeline from above.

```
package(default_visibility = ["//visibility:public"])
```
