### ISSUE TITLE
How to manually provide starting box positions for Box Tracking?

### ISSUE THREAD

**Issue by bogdandonduk** [google/mediapipe#2802]
Hello. The Box Tracking solution's overview states:

<em>The box tracking solution consumes image frames from a video or camera stream, and starting box positions with timestamps, indicating 2D regions of interest to track, and computes the tracked box positions for each frame. In this specific use case, the starting box positions come from object detection, **but the starting position can also be provided manually by the user or another system.**</em>

Please can you share a detailed guide on how to provide these starting positions manually?

**Comment by bogdandonduk** [comment]
Replies are so operative

**Comment by tankchenggeng** [comment]
I have the same question, anyone can help us?

**Comment by tankchenggeng** [comment]
up up up!

**Comment by tankchenggeng** [comment]
up up up!
help help help !
Go on !!!

**Comment by yegenzhi** [comment]
you can feed the detections or any starting boxes to the "START_POS" stream of box_tracker_calculator.
