### ISSUE TITLE
I want to scale the image of android Camera multiHandLandmarks. Where should I scale the model input?

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#2804]
I want to scale the image of android Camera multiHandLandmarks. Where should I scale the model input?

**Comment by sgowroji** [comment]
Hi @LMR2018,  The mediapipe models are limited to fixed-size input. So it is not recommended to scale the image. Doing it may or may not give you the appropriate results.

**Comment by LMR2018** [comment]
@sgowroji I want to convert camera frame data of camera mode in Android Hand_landmark model into bitmap data, and then deduce bitmap of the model. How should I convert it?
