### ISSUE TITLE
fatal error: 'opencv2/core/version.hpp' file not found apple M1 bazel 4.1.0

### ISSUE THREAD

**Issue by aerdy** [google/mediapipe#2805]
Use --sandbox_debug to see verbose messages from the sandbox
In file included from mediapipe/examples/desktop/demo_run_graph_main.cc:22:
In file included from ./mediapipe/framework/formats/image_frame_opencv.h:20:
./mediapipe/framework/port/opencv_core_inc.h:18:10: fatal error: 'opencv2/core/version.hpp' file not found
#include <opencv2/core/version.hpp>

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2519
