### ISSUE TITLE
Unable to build the python package

### ISSUE THREAD

**Issue by mathieuseguin** [google/mediapipe#2807]
**System information**
- OS Platform and Distribution: Ubuntu 20.04.3 LTS
- Compiler version: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- Programming Language and version : Python 3.8.10
- Installed using: virtualenv
- [MediaPipe version](https://github.com/google/mediapipe/releases): latest (cf101e62a9d49a51be76836b2b8e5ba5c06b5da0) - v0.8.8
- Bazel version: 3.7.2
- OpenCV version (if running on desktop): 3.4 & 4.5.4 (gstreamer)

**Describe the problem**:

I'm trying to build the python package. Ultimately I would like for my mediapipe package to use a custom OpenCV build that includes GStreamer.

# First attempt - Builtin OpenCV build script

I tried to build the package following the steps outlined in "[Installing on Debian and Ubuntu](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu)" & "[Building MediaPipe Python Package](https://google.github.io/mediapipe/getting_started/python.html#building-mediapipe-python-package)" but end up with the following error ([full output log](https://github.com/mathieuseguin/mediapipe-docker/blob/main/mediapipe/mediapipe.log#L7159)):
```
[31 / 32] [Prepa] Linking mediapipe/python/_framework_bindings.so
ERROR: /usr/local/src/mediapipe/mediapipe/python/BUILD:19:17: Linking of rule '//mediapipe/python:_framework_bindings.so' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/python/_framework_bindings.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/python/_framework_bindings.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: error: cannot find -lImath
/usr/bin/ld.gold: error: cannot find -lIlmImf
/usr/bin/ld.gold: error: cannot find -lIex
/usr/bin/ld.gold: error: cannot find -lHalf
/usr/bin/ld.gold: error: cannot find -lIlmThread
/usr/bin/ld.gold: error: cannot find -lavresample
collect2: error: ld returned 1 exit status
Target //mediapipe/python:_framework_bindings.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 31.119s, Critical Path: 29.78s
```

You can replicate using the following [Dockerfile](https://github.com/mathieuseguin/mediapipe-docker/blob/main/mediapipe/Dockerfile), which was run via:
```
docker build --no-cache -t mediapipe -f Dockerfile . > mediapipe.log
```

---

## Second attempt, custom OpenCV build

When trying to compile OpenCV 4 with GStreamer enabled, the mediapipe python package building fails with ([full output log](https://github.com/mathieuseguin/mediapipe-docker/blob/main/mediapipe_with_gstreamer/mediapipe_with_gstreamer.log#L10028)):
```
generating binarypb: mediapipe/modules/pose_landmark/pose_landmark_cpu
generating binarypb: mediapipe/modules/selfie_segmentation/selfie_segmentation_cpu
[0m[91merror: can't copy 'mediapipe/examples/android/solutions/facedetection/src/main/res': doesn't exist or not a regular file
[0m
```

You can replicate using the following [Dockerfile](https://github.com/mathieuseguin/mediapipe-docker/blob/main/mediapipe_with_gstreamer/Dockerfile), which was run via
```
docker build --no-cache -t mediapipe_with_gstreamer -f Dockerfile . > mediapipe_with_gstreamer.log
```

--- 

Would love some insights on what I'm missing!

Thanks!

**Comment by sgowroji** [comment]
Hi @mathieuseguin, Can you try the workarounds mentioned in this  issues https://github.com/google/mediapipe/issues/2458#issuecomment-904842657,  https://github.com/google/mediapipe/issues/2041#issuecomment-847711380

**Comment by mathieuseguin** [comment]
Hi @sgowroji,

Thank you for your suggestions.

I'm not using `python3 setup.py install --link-opencv` but `python3 setup.py bdist_wheel`: https://github.com/mathieuseguin/mediapipe-docker/blob/main/mediapipe/Dockerfile#L45. I'll try with `python3 setup.py install` as suggested and report back.

Regarding the second suggestions, I am already running setup_opencv.sh: https://github.com/mathieuseguin/mediapipe-docker/blob/main/mediapipe/Dockerfile#L37 - or did I miss something?

Mathieu

**Comment by mathieuseguin** [comment]
@sgowroji I was able to fix the linking issue for the "Builtin OpenCV build script" by [installing the missing packages](https://github.com/mathieuseguin/mediapipe-docker/blob/main/mediapipe/Dockerfile#L33) according to https://github.com/google/mediapipe/blob/master/third_party/opencv_linux.BUILD#L9

Now both of my Dockerfile fail with:
```
error: can't copy 'mediapipe/examples/android/solutions/facedetection/src/main/res': doesn't exist or not a regular file
```

regardless of if I'm using `python3 setup.py install`, `python3 setup.py install --link-opencv` or `python3 setup.py bdist_wheel`

**Comment by njuFerret** [comment]
same problem, when compiled under raspi4b with ubuntu 20.04, the path `mediapipe/examples/android/solutions/facedetection/src/main/res`  is a soft link, I remove the link and copy same folder with `../../../res` at the same place and sucessfully built the library.

**Comment by mathieuseguin** [comment]
thanks @njuFerret! I also had to remove the links for `facemesh` and `hands`, but ultimately got it working!
Really appreciate the help!

**Comment by Gaozhongpai** [comment]
> links
I have the same issues. Could you explain what and where the links you removed? Thanks

**Comment by RyanPaulMcKenna** [comment]
(Robot-ROM) fvr510@pc282:~/mediapipe$ python3 setup.py bdist_wheel
/home/fvr510/anaconda3/envs/Robot-ROM/lib/python3.8/site-packages/setuptools/dist.py:544: UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running bdist_wheel
/home/fvr510/anaconda3/envs/Robot-ROM/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: dev is an invalid version and will not be supported in a future release
  warnings.warn(
running build
running build_py
running gen_protos
generating proto file: build/lib.linux-x86_64-cpython-38/mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options_pb2.py
Invoking: /usr/bin/protoc -I. --python_out=/home/fvr510/mediapipe/build/lib.linux-x86_64-cpython-38 mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:30:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:34:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:39:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:44:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:47:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:51:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
Command '['/usr/bin/protoc', '-I.', '--python_out=/home/fvr510/mediapipe/build/lib.linux-x86_64-cpython-38', 'mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto']' returned non-zero exit status 1.
(Robot-ROM) fvr510@pc282:~/mediapipe$ 

My error is different, what could the solution be?

**Comment by RyanPaulMcKenna** [comment]
```
(Robot-ROM) fvr510@pc282:~/mediapipe$ python3 setup.py bdist_wheel
/home/fvr510/anaconda3/envs/Robot-ROM/lib/python3.8/site-packages/setuptools/dist.py:544: UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running bdist_wheel
/home/fvr510/anaconda3/envs/Robot-ROM/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: dev is an invalid version and will not be supported in a future release
  warnings.warn(
running build
running build_py
running gen_protos
generating proto file: build/lib.linux-x86_64-cpython-38/mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options_pb2.py
Invoking: /usr/bin/protoc -I. --python_out=/home/fvr510/mediapipe/build/lib.linux-x86_64-cpython-38 mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:30:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:34:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:39:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:44:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:47:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:51:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
Command '['/usr/bin/protoc', '-I.', '--python_out=/home/fvr510/mediapipe/build/lib.linux-x86_64-cpython-38', 'mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto']' returned non-zero exit status 1.
(Robot-ROM) fvr510@pc282:~/mediapipe$ 


```
