### ISSUE TITLE
Instant motion tracking in web browser

### ISSUE THREAD

**Issue by pot2mayo** [google/mediapipe#2811]
It's as much of a question as it is a feature request but is there any reason why Instant Motion Tracking has not been ported to any platform other than Android?

It would be especially really helpful to have it running in the web browser.

Is there any technical reason it could not done?
(performance issues? relies on Android-specific component?)

**Comment by pot2mayo** [comment]
@mgyong 
I see that the ticket was assigned to you by @sgowroji 
Do you have any update on the topic?
The question would also concerns instant motion tracking on iOS

**Comment by AmirHossein-nr** [comment]
any updates on this topic please ?!!

**Comment by tso996** [comment]
I've been waiting for this as well. In order for them to make the instant motion tracking solution work in the web browser, the tracking modules need to be compiled into WebAssembly. They have the Objectron solution available on the web browser now, which I think uses the tracking modules so I don't think it will be long before they bring imt to browser. If you want to try to compile the modules for the web browser yourself this [thread](https://github.com/google/mediapipe/issues/877) could be useful.

**Comment by ayushgdev** [comment]
Hello @pot2mayo 
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 
You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
