### ISSUE TITLE
How do I convert the camera's data stream into a Bitmap stream to recognize hand_landmark_lite.tflite and then convert the Bitmap back to video output?  

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#2812]
How do I convert the camera's data stream into a Bitmap stream to recognize hand_landmark_lite.tflite and then convert the Bitmap back to video output?

**Comment by sgowroji** [comment]
Hi @LMR2018, Could you please provide your use case w.r.t the above query. Thanks!

**Comment by LMR2018** [comment]
> Hi @LMR2018, Could you please provide your use case w.r.t the above query. Thanks!

// For camera input and result rendering with OpenGL.
HandsOptions handsOptions =
    HandsOptions.builder()
        .setStaticImageMode(false)
        .setMaxNumHands(2)
        .setRunOnGpu(true).build();
Hands hands = new Hands(this, handsOptions);
hands.setErrorListener(
    (message, e) -> Log.e(TAG, "MediaPipe Hands error:" + message));

// Initializes a new CameraInput instance and connects it to MediaPipe Hands Solution.
CameraInput cameraInput = new CameraInput(this);
cameraInput.setNewFrameListener(
    textureFrame -> hands.send(textureFrame));

// Initializes a new GlSurfaceView with a ResultGlRenderer<HandsResult> instance
// that provides the interfaces to run user-defined OpenGL rendering code.
// See mediapipe/examples/android/solutions/hands/src/main/java/com/google/mediapipe/examples/hands/HandsResultGlRenderer.java
// as an example.
SolutionGlSurfaceView<HandsResult> glSurfaceView =
    new SolutionGlSurfaceView<>(
        this, hands.getGlContext(), hands.getGlMajorVersion());
glSurfaceView.setSolutionResultRenderer(new HandsResultGlRenderer());
glSurfaceView.setRenderInputImage(true);

hands.setResultListener(
    handsResult -> {
      if (result.multiHandLandmarks().isEmpty()) {
        return;
      }
      NormalizedLandmark wristLandmark =
          handsResult.multiHandLandmarks().get(0).getLandmarkList().get(HandLandmark.WRIST);
      Log.i(
          TAG,
          String.format(
              "MediaPipe Hand wrist normalized coordinates (value range: [0, 1]): x=%f, y=%f",
              wristLandmark.getX(), wristLandmark.getY()));
      // Request GL rendering.
      glSurfaceView.setRenderData(handsResult);
      glSurfaceView.requestRender();
    });

// The runnable to start camera after the GLSurfaceView is attached.
glSurfaceView.post(
    () ->
        cameraInput.start(
            this,
            hands.getGlContext(),
            CameraInput.CameraFacing.FRONT,
            glSurfaceView.getWidth(),
            glSurfaceView.getHeight()));

**Comment by LMR2018** [comment]
cameraInput.setNewFrameListener(
textureFrame -> hands.send(textureFrame));

I want to see the c++ low-level implementation, I should in？

**Comment by sgowroji** [comment]
Hi @LMR2018, Could you please provide your use case with c++ on hands. Thanks!

**Comment by sgowroji** [comment]
Hi  @LMR2018, You can find the implementation  in our [hands graphs ](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.pbtxt) . To understand the calculators and graph you can go through this https://google.github.io/mediapipe/framework_concepts/framework_concepts.html

**Comment by LMR2018** [comment]
> 嗨@LMR2018，您能否提供您的用例和 C++。谢谢！

@sgowroji   I wonder where I can find their c++ code?  I want to print the time of their image preprocessing and the time of model inference respectively. Hand.send (textureFrame)
