### ISSUE TITLE
world hand coordinates are wrong when back of hand in horizontal screen ？

### ISSUE THREAD

**Issue by Gzzgz** [google/mediapipe#2813]
hello， I got new hand_landmark_lite.tflite and hand_landmark_full.tflite models  and convert them onnx models. so I just test my only hand image. I find that when  back of hand in horizontal screen its result is bad. just look like that:

<img width="640" alt="1" src="https://user-images.githubusercontent.com/15968092/143201314-5a70a2a1-17a7-49e6-a369-153a148374f0.png">

and _lite model is better than _full model. as the same time the 21 uvd handlandmarks are good!
the input image like that:
![图片](https://user-images.githubusercontent.com/15968092/143202570-36f5712d-8541-49a3-a59f-df3621c476b1.png)

**Comment by sgowroji** [comment]
Hi @Gzzgz, Thank you for reaching us regarding the above issue. Could you please provide the steps to reproduce the above scenario with complete graph and code details. Thanks!
