### ISSUE TITLE
For windows, "pip install mediapipe" command is not working

### ISSUE THREAD

**Issue by Andd54** [google/mediapipe#2814]
When trying to install the package, it simply won't work.
![image](https://user-images.githubusercontent.com/70097898/143238385-d3fd4651-4aa2-4738-ac37-a4fbce9b2906.png)
`pip install mediapipe`
![image](https://user-images.githubusercontent.com/70097898/143238487-de875daf-553e-4703-a0a7-9b0d6bf367c4.png)
![image](https://user-images.githubusercontent.com/70097898/143238529-44cb29d4-81d2-4cca-8899-fc0b03e08859.png)

**Comment by sgowroji** [comment]
Hi @Andd54 , Python 3.10 is not supported by MediaPipe yet. Please use Python 3.7 to 3.9. Thanks!

**Comment by Andd54** [comment]
ow, thanks. I solved it with a venv.😀

**Comment by Anushree1291** [comment]
> 

how did u solve it. I have been trying. But could'nt do anything

**Comment by Ustd8152** [comment]
I m also not able to solve it

**Comment by Andd54** [comment]
I suggest you using a virtual environment for python, that did worked for windows

**Comment by Andd54** [comment]
> > 
> 
> 
> 
> How? Can you plz help

I suggest you using a virtual environment for python, that did worked for windows
