### ISSUE TITLE
Proper way of locating file when using SelfieSegmentation

### ISSUE THREAD

**Issue by ebarooni** [google/mediapipe#2815]
Im trying to use selfie segmentation in an angular app. After installing the package using `npm i @mediapipe/selfie_segmentation` I tried constructing a selfie segmentation instance by using the following code:

<img width="712" alt="Bildschirmfoto 2021-11-24 um 13 35 05" src="https://user-images.githubusercontent.com/66495214/143239433-f526c9d5-369a-4c7b-afef-32a0eaa180ac.png">

Which yields the following error:

<img width="590" alt="Bildschirmfoto 2021-11-24 um 13 31 07" src="https://user-images.githubusercontent.com/66495214/143238849-d7ff0277-e864-4038-9178-b262a6f1e617.png">

However, instead the following works:

`https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/${file}`

How can i locate the file from the node_modules folder if i dont want to address it from cdn?

**Comment by sgowroji** [comment]
Hi @ebarooni, This https://github.com/google/mediapipe/issues/2756#issuecomment-975828630 answers your query.

**Comment by ebarooni** [comment]
@sgowroji Tnx for the link but I already checked that comment and my idea was `node_modules/@mediapipe/selfie_segmentation/${path}` would be the correct directory.

**Comment by tyrmullen** [comment]
@ebarooni That would be correct if you are staging your webpage from the directory on your filesystem where you actually ran the `npm i @mediapipe/selfie_segmentation` command.  For example, just running:
`npm i @mediapipe/selfie_segmentation && python3 -m http.server` will start up a website at "localhost:8000", and if you type in an asset like "http://localhost:8000/node_modules/@mediapipe/selfie_segmentation/selfie_segmentation.js" into your browser, you can see that the assets all load now.

I suspect you're staging your webpage from a different directory on your filesystem, so you'll need to:
(a) make sure that the "node_modules" directory is staged as well (commands like `python3 -m http.server` by default will stage the current directory and all sub-directories, but nothing else)
(b) adjust your path accordingly

Or just copy the "node_modules/@mediapipe" directory over to wherever your webpage lives in your local filesystem (the directory where the website is staged from) before you stage, and then refer to it with `@mediapipe/selfie_segmentation/${path}`.

**Comment by ebarooni** [comment]
@tyrmullen Thank you for the explanation. I simply copied the content of the directory as you said under assets/ and it was successful. However, the question that i have regarding this is that doesnt copy pasting the content of the installed package in node_modules contradict npm installing a package?
Because I would expect that when a package is installed, i can simply use it as-is. Therefore, copying the content of an installed package into a different directory and referring to them seems inefficient to me.

**Comment by tyrmullen** [comment]
Well, in a sense you can use the package "as-is"-- the issue isn't with grabbing the package, but rather with how you're staging your website.  As long as your website staging/serving process includes the proper node modules, then you'll be fine (which can be done with server code, with a custom build script to temporarily copy specific node_modules directories, or with other methods).  I'm not very familiar with npm or node_modules myself, so I don't know if they have recommended procedures for staging a website using specific node_modules dependencies, but JS dependency management does appear to be a common problem for web devs, and indeed many tools seem to exist online for this (e.g. webpack, rollup, and parcel), so those might be something to look into if this issue becomes a problem for scalability.
