### ISSUE TITLE
How to interpret the Face Detection output from the tflite model

### ISSUE THREAD

**Issue by sainisanjay** [google/mediapipe#2816]
I would like to run the model using Nvidia TensorRT. Therefore, i want to know how to interpret the Face Detection bounding box from the output node:
As output from output node is: float32[1,896,16]
num_classes: 1
num_boxes: 896
num_coords: 16

Should num_coords be 4?
I got this output in TensorRT:
![test](https://user-images.githubusercontent.com/25616511/143274914-3a559060-be0a-4c6b-b433-c7b64f740c08.jpg)
Output does not look correct for me, seems i am making some mistake. Can someone help me. Thanks

**Comment by Jerryzhangzhao** [comment]
4 coordinate value(2 point) for face bounding box and 12 coordinate(6 point) for facial keypoint coordinate: left eye,right eys, nose, mouth, lefteye tragion,right eye tragion.
Model card: https://drive.google.com/file/d/1d4-xJP9PVzOvMBDgIjz6NhvpnlG9_i0S/preview

**Comment by sainisanjay** [comment]
Thanks @sgowroji for your response. So from 16 coordinated initial 4 points are belongs to Face BBox and remaining 12 is for Facial Keypoints right?
