### ISSUE TITLE
64 bit requirement

### ISSUE THREAD

**Issue by anhqttruong** [google/mediapipe#2817]
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 11
- [MediaPipe version](https://github.com/google/mediapipe/releases): Latest
- Bazel version: Latest
- Solution (e.g. FaceMesh, Pose, Holistic): Hands
- Programming Language and version ( e.g. C++, Python, Java): Java

**Describe the expected behavior:** The solution example which detects hand key points in real-time was expected be able to be published on Google play and support 64 bit architectures. I tried to publish the solution app but unsuccessful.  In fact, I had an error which said: "This release is not compliant with the Google Play 64-bit requirement." 
Please help.

**Standalone code you may have used to try to get what you need :** No

**Other info / Complete Logs :** The following APKs or app bundles are available to 64-bit devices, but they only have 32-bit native code: [4]
Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code that it needs. This avoids increasing the overall size of your app.

**Comment by anhqttruong** [comment]
I wonder if this problem only affects me and not others. Could you please confirm by trying to upload the hands solution on Google Play ? Thank you in advance.

**Comment by sgowroji** [comment]
Hi @anhqttruong, Could you please confirm the above error reflecting from  is this from google gmaven repo or from your own build. Can you refer this https://stackoverflow.com/questions/57586642/this-release-is-not-compliant-with-the-google-play-64-bit-requirement-error-stil to understand more about the fix.

**Comment by anhqttruong** [comment]
I believe it was from the google gmaven repo. In fact, I just cloned the GitHub repo of the MediaPipe hands, synced all project with griddle files, generate signed Bundle then uploaded it to Google Play Console. The stackoverflow you mentioned matched perfectly with my issue except I could not succeed uploading the bundle file to Google play with the fix in the link ... The same error applied despite have armeabi-v7a...

**Comment by sgowroji** [comment]
We do have many applications in Playstore and with the same implementation and never noticed such compliance errors.
