### ISSUE TITLE
world coordinates with the origin on the floor

### ISSUE THREAD

**Issue by hyeyoungjo** [google/mediapipe#2820]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): Mediapipe 0.8.8.1
- Programming language : python
- Are you willing to contribute it (Yes/No): no

**Describe the feature and the current behavior/state:
currently, Mediapipe's POSE_WORLD_LANDMARKS provide x, y, z coordinated in meters with the origin at the center between hips.
I would like to get **3D coordinated align to the world space**. So, when a person squatting, instead of fixed hips with feet going up and down, feet would stay on the floor with hips going down and up.

![problem](https://user-images.githubusercontent.com/49541763/143515526-bbff098a-2c96-44fb-8f3d-a025b4c00a22.JPG)
![solution](https://user-images.githubusercontent.com/49541763/143515537-7ab893be-6210-435d-81b4-3f83cf3f5343.JPG)

**Will this change the current API? How?
From my understanding, 3D pose estimation using top-down approach requires the final step aligning to world space.
It will complete the API and enable many use cases, especially in animation.

**Who will benefit with this feature?
3D animators

**Please specify the use cases for this feature:
I would like to use webcam to make 3D skeleton in Blender or Unity.

**Any Other info:**
I found similar questions being asked and staled with no solutions. 
I'm pretty new to programming, If there are any solutions or a way to achieve this, I'll be grateful for your suggestions.
I tried fixing it in Blender calculating offset from feet to hips inversely, but it feels like maybe it is a feature already inside the Mediapipe, and I'm doing unnecessary steps.

**Comment by remmel** [comment]
What is probably missing is the translation of the skeleton (eg how far is the person from the camera, which hight...)

**Comment by sgowroji** [comment]
Hi @hyeyoungjo,  You can try that with some implementation in  data format tweak which can be provide through a custom calculator.

**Comment by Matteo-0** [comment]
Hello!
@hyeyoungjo where you able to solve this problem. I would like to copy squatting movements but I obtain fixed hips with feet going up and downwhich is uncorrect. Hope you can help!

Thanks.

**Comment by sidk99** [comment]
Hi @sgowroji , can you please elaborate on the data format tweak?

"You can try that with some implementation in data format tweak which can be provide through a custom calculator."
