### ISSUE TITLE
After I use Building Android Example apps with Bazel to generate APK, APK can run normally on my phone, but on RK3399 Android flash back, do you know what the reason is?  

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#2821]
After I use Building Android Example apps with Bazel to generate APK, APK can run normally on my phone, but on RK3399 Android flash back, do you know what the reason is?  

compile command：
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

**Comment by sgowroji** [comment]
Hi @LMR2018, What is the error are you seeing while running on RK3399 ?

**Comment by LMR2018** [comment]
> 

I directly run the installed APK, but I can't see any mistakes. It just flashes back after opening the application, and I can't open the interface

**Comment by LMR2018** [comment]
> Hi @LMR2018, What is the error are you seeing while running on RK3399 ?

I directly run the installed APK, but I can't see any mistakes. It just flashes back after opening the application, and I can't open the interface

**Comment by sgowroji** [comment]
Hi @LMR2018, Could you please provide a recording reference to understand the issue and android logcat logs(bug report) to investigate further.

**Comment by LMR2018** [comment]
> Hi @LMR2018, Could you please provide a recording reference to understand the issue and android logcat logs(bug report) to investigate further.

adb: failed to install bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install com.google.mediapipe.apps.handtrackinggpu without first uninstalling.]

**Comment by LMR2018** [comment]
> Hi @LMR2018, Could you please provide a recording reference to understand the issue and android logcat logs(bug report) to investigate further.

(base) ubuntu@ubuntu:mediapipe$ adb install bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu.apk

adb: failed to install bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install com.google.mediapipe.apps.handtrackinggpu without first uninstalling.]

**Comment by LMR2018** [comment]
@sgowroji   I don't know how to view the Android Logcat log on android.

**Comment by sgowroji** [comment]
Hi @LMR2018, Try to perform this [steps](https://developer.android.com/studio/debug/bug-report) to capture the bug report from your device  when ever error occurs. You can share the report to investigate about issue for further. Thanks!
