### ISSUE TITLE
[autoflip] : Segmentation fault (core dumped) issue when running autoflip on CentOs 8,with opencv 3.4

### ISSUE THREAD

**Issue by ithanwu** [google/mediapipe#2822]
Dear All ,
When I tried to use the solution `autoflip` to automatically crop the video snowboarding.mp4 provided by this link https://drive.google.com/corp/drive/u/0/folders/1KK9LV--Ey0UEVpxssVLhVl7dypgJSQgk into aspect ratio 1:1 
I run into a Segmentation fault ,and I cannot get across it by all the way I tried ! I tried to run the solution on different server ,U can't image it has been suffering me for almost two weeks !
Please !
HELP!!!

The command I use : 
![image](https://user-images.githubusercontent.com/95072185/143552682-6f5107d2-57f4-4528-abda-a0fc6075a5be.png)

What the terminal say:
![image](https://user-images.githubusercontent.com/95072185/143552891-bc0f1f80-b299-4a7f-a7b5-f393c990ed06.png)

I meet this issue on every server I use ,I'll list the information of one of them: 

**System information** 
- Have I written custom code: NO
- OS Platform and Distribution:  **Linux CentOs 8 64-bit** , and `uname -a` result is below  :
```
Linux localhost.localdomain 4.18.0-193.el8.x86_64 
```
- [MediaPipe version](https://github.com/google/mediapipe/releases):latest (v0.8.8)
- Bazel version: 3.7.2
- Solution (e.g. FaceMesh, Pose, Holistic): autoflip
- Programming Language and version ( e.g. C++, Python, Java): C++
- gcc version : 8.5.0 20210514 (Red Hat 8.5.0-4)
- g++ version : 8.5.0 20210514 (Red Hat 8.5.0-4)
- Cmake version : 3.22.0 (I built it from source ,and installed it to the user path,I am not a sudoer of my server)
- x264 version : 0.164.3075 66a5bc1 (also built from source)
- ffmpeg version : 4.4.1 (built from source with x264 enabled)
- Opencv version : 3.4.14 (build from source with the ffmpeg above)

**Describe the expected behavior:**

I run the command suggested by this link https://google.github.io/mediapipe/solutions/autoflip.html 
And it's expected to generate cropped video with aspect ratio of 1:1

**Standalone code you may have used to try to get what you need :**

I uploaded the `WORKSPACE` file and `opencv_linux.BUILD` and `ffmpeg_linux.BUILD` files ,you can find them on the tail of this  issue.
For some issues of the internet,I downloaded many files and put them on my local system ,so you may see many urls of the third party resources are replaced by my local file path ,and you konw that doesn't matter.
 
If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:
It's easy to reproduce this error ,once I run the command below ,it occurs!
```
bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip  \
  --calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt \
--input_side_packets=input_video_path=/home/wyn/codes/mediapipe/cacheFiles/snowboarding.mp4,\
output_video_path=/home/wyn/codes/mediapipe/cacheFiles/snowboarding_res.mp4,aspect_ratio=1:1
```

oh , by the way , the command i used to build `autoflip` is the same as the official document suggested  ：
```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/autoflip:run_autoflip
```

### The related files, github doesn't support `.BUILD` type ,so I appended `.txt` to finish the upload .
[opencv_linux.BUILD.txt](https://github.com/google/mediapipe/files/7607320/opencv_linux.BUILD.txt)
[ffmpeg_linux.BUILD.txt](https://github.com/google/mediapipe/files/7607321/ffmpeg_linux.BUILD.txt)
[WORKSPACE.txt](https://github.com/google/mediapipe/files/7607322/WORKSPACE.txt)

**Comment by ithanwu** [comment]
no answer ? why ? 
any more information needed ?

**Comment by ithanwu** [comment]
No one answered me , why ?
Is there any more information needed ?

**Comment by ithanwu** [comment]
I uninstalled opencv and rebuilt a 3.4.10 version ,then I rebuild the auto flip and test it ,nothing changed !
HELP ！！！ yelling in despair .....

**Comment by sgowroji** [comment]
Hi @ithanwu, Thank you for being patience. We have already added owners on this issue. You will be receiving the update very soon.

**Comment by ithanwu** [comment]
> Hi @ithanwu, Thank you for being patience. We have already added owners on this issue. You will be receiving the update very soon.

thx !!!

**Comment by ithanwu** [comment]
I want to add some more information here. I've tried the docker ,and this issue is reproduced ! Yeah ,exactly the docker file included in this project....

**Comment by ithanwu** [comment]
could you please have a look at this issue ?.......

**Comment by ithanwu** [comment]
Oh,My god ! Anyone help me ???

**Comment by ithanwu** [comment]
latest news , the error now gone away ,And i did't change any of your code !!!!
i typed several lines log in the "mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc",and then the error disappear and the video i want to crop if properly resized by the app ,then I feel it so strange ,so I tried to recover the .cc file to the original state and rebuild the app before rerunning it .The error doesn't appear ....
How Can that BE !!!? 
SO WEIRD!!!

**Comment by ithanwu** [comment]
I rebuild the mediapipe on other server that has a similar envirenment ,and the issue is reproduced ,
and then I run the autoflip demo by gdb ,I located the stack ,where the error happens in the file "mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc", the method with problem is 
TfLiteTensorsToDetectionsCalculator::ProcessCPU
I am trying to fix it ,but I tried many place ,none worked ! 
Could U please check that function ??

**Comment by ithanwu** [comment]
![image](https://user-images.githubusercontent.com/95072185/146137528-a8384aae-8468-4cd1-a0f6-a1626fe2794a.png)

i finally find ,if i change this period value to a bigger one ,the segment fault error gone away ,but i ' m not sure does it really cause this problem ,
the video I used to test is snowboarding.mp4  provided by you from google drive

**Comment by ithanwu** [comment]
It's kind of your to reply me and confirm this issue's real cause

**Comment by zldeGit** [comment]
I have the same problem, did you solve it?

**Comment by ithanwu** [comment]
try to find the file autoflip_graph.pbtxt
the modify the calculator "PacketThinnerCalculator"
as I mentioned here https://github.com/google/mediapipe/issues/2822#issuecomment-994385991
yet it's solved ,I don't know why .
Anyway ,It do work.



> I have the same problem, did you solve it?

**Comment by AlverGant** [comment]
I have found that reducing the number of threads reduces the probability of the problem to occur.

Running autoflip on linux with the following code appears to solve the problem but also reduces performance:
GLOG_logtostderr=1 taskset --cpu-list 0 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip .....

**Comment by senpo** [comment]
I found the way to avoid this problem is to ensure the output files don't exist. Make sure you remove the previous output file before you run the graph. Tested on both the autoflip_graph.pbtxt and autoflip_graph_development.pbtxt.

**Comment by ayushgdev** [comment]
Hello @ithanwu Have the suggestions provided by the community worked for you?
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) (including Autoflip), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by ithanwu** [comment]
I had already posted my solution to avoid this issue, it's really quite a long time to wait for someone to help me ,when I promoted this issue , I was building an app ,but finally it was abounded ,as this legacy  solution is no more supported by the developers ,this issue should be closed ,if anyone use this ,pls refer to my solution here https://github.com/google/mediapipe/issues/2822#issuecomment-994385991
