### ISSUE TITLE
(Android - Hands Graph) How to properly access palm detections stream and set handtrackinggpumobilegraph to run in static image mode?

### ISSUE THREAD

**Issue by 123epsilon** [google/mediapipe#2825]
I am currently building an android application using a mediapipe AAR from the hand tracking example app for android. I want to be able to access the palm detections stream to obtain palm detection confidence values and run the hand tracking graph in static image mode in order to force palm detection to run on every frame that comes in from the camera. 

I was able to accomplish this in the Python API by editing the media pipe source to return the palm detections stream and then setting the hands object to use static image mode in the constructor. How can I accomplish this in the android version? I am currently running the model using the FrameProcessor and by specifying the graph name/input side packets.

Alternatively, is there a way to accomplish this using the Hands Solution API? It is unclear from the docs. I would appreciate any guidance in implementing this - I have already looked at snippets from the following two issues but they did not provide enough information for me to continue:

https://github.com/google/mediapipe/issues/644
https://github.com/google/mediapipe/issues/535

**Comment by sgowroji** [comment]
Hi @123epsilon, Did you get a chance to go through  Hands Android Gradle api solutions with clear implementation and documentation from here https://google.github.io/mediapipe/solutions/hands#camera-input. You can use staticImageMode and runOnGpu.

**Comment by 123epsilon** [comment]
Hi @sgowroji yes I saw that it is very simple to use the API Solution to set staticImageMode to true, however, is it possible to extract specific streams from the handtrackinggpu graph while it runs? In particular I would like to extract output packets from the "palm_detections" stream rather than the default landmarks stream.

**Comment by LMR2018** [comment]
@123epsilon    Hello, you have solved it？I am a newbie, can you tell me more about the specific implementation? I want to look at the image preprocessing and inference process of android Hand_landmark model and I want to know how long each process take

**Comment by 123epsilon** [comment]
@LMR2018 I don't know how you would time that other than attempting to individually run each calculator on some benchmark test set and then recording the time they take to execute on cpu/gpu. I believe that the Hands API does actually allow you to specify output streams in the constructor though this is not noted in the documentation, if you look at the source on github there is a parameter where this is possible. Unfortunately the solution API is presenting problems when I attempt to integrate with my project - I'll try to post a logcat or error trace.

**Comment by PopoTeaTree** [comment]
From this link (https://github.com/google/mediapipe/issues/644#issuecomment-980508648), 'palm_detections' is the output from Hand detection graph. And 'Detections' output of Detection node in Hand tracking graph is the 'palm_detections' output. You can see more clear in C++ file.

![EBC8C06A-9C42-4CCB-A3A6-578C2DC2D111](https://user-images.githubusercontent.com/52104672/146786407-b9ca5efc-f72d-47d9-a770-377022c69aa9.jpeg)
>>Hand tracking graph<<

<img width="579" alt="image" src="https://user-images.githubusercontent.com/52104672/146786538-66a78457-15f3-4614-aa4b-4cc06d13564c.png">
>>Hand detection graph<<

**Comment by aa12356jm** [comment]
@123epsilon hi， how do you get the results of palm detections? i want to get the palm bbox for my project，can you share some python  codes ? thanks

**Comment by PopoTeaTree** [comment]
> @123epsilon hi， how do you get the results of palm detections? i want to get the palm bbox for my project，can you share some python codes ? thanks

https://github.com/metalwhale/hand_tracking you see the exaple how to get the box from this git link.

**Comment by kuaashish** [comment]
Hello @123epsilon,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
