### ISSUE TITLE
Any solutions for Mixamo models translations

### ISSUE THREAD

**Issue by shane99a** [google/mediapipe#2826]
Mixamo automatically rigs a 3d model with skeleton. https://www.mixamo.com/#/ 
Just wondering does Mediapipe support translation to the bones from Mixamo? I have researched and could not find anyone doing this. 

Alternatively is it possible to make a animated model from the data generated from mediapipe. Just wondering if mediapipe has already done this or have any resources to make it possible for someone to implement this.

Here are the bones in Mixamo:
![image](https://user-images.githubusercontent.com/5408993/143720512-c5aa57db-9aae-4a3f-b796-9e74b975591f.png)

**Comment by sgowroji** [comment]
Hi @shane99a, We don't have any examples with Mixamo.

**Comment by corlangerak** [comment]
Did you manage to find a way to use mediapipe and Mixamo?

**Comment by shane99a** [comment]
No I'm still trying to figure it out. However, I also found a paid solution: https://www.deepmotion.com, not sure if they use mediapipe, but their service matches my needs. But I'm still seeing if I can do it myself.

**Comment by superdav42** [comment]
Looks like a project was started to do this in python https://github.com/Nor-s/mediapipe-to-mixamo

**Comment by manoj-323** [comment]
> Looks like a project was started to do this in python https://github.com/Nor-s/mediapipe-to-mixamo

thankyou sir its a great reference point in my project, really appreciated
