### ISSUE TITLE
Mediapipe on Pre-recorded video

### ISSUE THREAD

**Issue by V-m1r** [google/mediapipe#2827]
Hey!
I was wondering if it is possible to use mediapipe pose tracking on pre-recorded videos?
If so, May you please share the code if any, or describe in detail how to do it?

**Comment by sgowroji** [comment]
Hi @V-m1r, You can try the similar implementation as mentioned here https://github.com/google/mediapipe/issues/1589#issuecomment-952186886. But you need to update the pose parameters in it.
