### ISSUE TITLE
How to convert relative face bounding box location to absolute coordinates 

### ISSUE THREAD

**Issue by sainisanjay** [google/mediapipe#2829]
Any one can help me to convert relative face bounding box location to absolute coordinates. 

```
const float scale_x = float(frameSize.width) / float(inputSize.width);
const float scale_y = float(frameSize.height) / float(inputSize.height);
float x0 = rects[i * ow] * scale_x; // left
float w = rects[(i * ow) + 1] * scale_x; // width 
float y0 = rects[(i * ow) + 2] * scale_y; // top
float h = rects[(i * ow) + 3] * scale_y; // height             
mRects.push_back(cv::Rect(x0, y0, w, h));
```

Based on my implementation my detected face BBox is overlapping other place in the image then the actual face (Attached image)
![test](https://user-images.githubusercontent.com/25616511/143811404-24bbf066-c50d-4b26-9f52-de2fd29e9f3c.jpg)

**Comment by sgowroji** [comment]
Hi @sainisanjay, Are you testing the above on a cropped image or scaled image in c++.  ?. Try checking the same with other platforms  python and java implementation.

**Comment by sainisanjay** [comment]
@sgowroji I am testing on cropped image.
