### ISSUE TITLE
In hand tracking mobile gpu can i modification hand landmarks x and y information

### ISSUE THREAD

**Issue by chobe111** [google/mediapipe#283]
currently i made a application using mediapipe i want to modificate hand landmarks info(21 points)
can i do this with mediapipe? also i wonder about where to draw circle in c++? or java open GL 

i`m sorry to you to ask stupid question

**Comment by mgyong** [comment]
@chobe111 For example in the [face detection graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt ) u need to directly modify `DetectionsToRenderDataCalculator` and the `AnnotationOverlayCalculator` calculator to draw the circle

**Comment by suraj-0387** [comment]
I am also working handtracking application and I have similar requirement as above and top of it I want a perticular point in from native code to java code so that I can place particular item on it.Basically I want to place an AR object  on it

**Comment by chobe111** [comment]
> @chobe111 For example in the [face detection graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt) u need to directly modify `DetectionsToRenderDataCalculator` and the `AnnotationOverlayCalculator` calculator to draw the circle

thank you 👍 :)  i will try to modify the DetectionsToRenderDatacalculator and AnnotationOverlayCalculator

**Comment by vineet15889** [comment]
@suraj-0387 I have tried 3d model for hand landmark, and it gives landmark in aspect ratio like -> x:0.34, y: 7.56, z:5, if you want actual x and y position for your device you should do.
->
 x = DEVICE_SCREEN_WIDTH * x_value,
 y = DEVICE_SCREEN_HEIGHT * y_value.

One more thing you should remember that the starting point is the top right corner of your device. So for iPhone developer x will be.
x = DEVICE_SCREEN_WIDTH  - (DEVICE_SCREEN_WIDTH * x_value)

**Comment by suraj-0387** [comment]
@vineet15889 Did you succeeded in augmenting an 3d object on lankmark points?Did you used sceneform or base code?

**Comment by vineet15889** [comment]
@suraj-0387 just use SceneKit on top of render layer to accommodate the 3d environment. You can find more info about ARKit at https://developer.apple.com/documentation/arkit

**Comment by suraj-0387** [comment]
@vineet15889 Thanks for your input but I am working on Android (Sceneform)
