### ISSUE TITLE
[iOS] How we can custom landmark(draw line or hide landmarks line)

### ISSUE THREAD

**Issue by alfian0** [google/mediapipe#2830]
Hi ...did anyone explore mediapipe on iOS ?
my question is why iOS documentation is fewer than other, I have difficulty when follow documentation to custom facemesh when we want to hide line graph and red square on the detected face

thanks and appreciate for the answer

**Comment by sgowroji** [comment]
Hi @alfian0, You can do the changes in the face_mesh_mobile_gpu graph w.r.t face mesh and build the code as mentioned here https://google.github.io/mediapipe/getting_started/ios

**Comment by alfian0** [comment]
did you mean this file ?
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_mesh/subgraphs/face_renderer_gpu.pbtxt
any documentation for custom this file ?

**Comment by alfian0** [comment]
<img width="604" alt="Screen Shot 2021-12-08 at 13 58 51" src="https://user-images.githubusercontent.com/21122436/145163034-01cc7a64-5b9e-461f-a9c0-bd8bbf14e35b.png">

I try di comment this node and I got this error
<img width="622" alt="Screen Shot 2021-12-08 at 13 59 36" src="https://user-images.githubusercontent.com/21122436/145163109-ba515886-6f02-48f8-9977-df0246902a32.png">

any suggestion @sgowroji ?

**Comment by alfian0** [comment]
Oh sorry, some NORM_RECTS not commented
