### ISSUE TITLE
Visibility for hand landmarks

### ISSUE THREAD

**Issue by siyuan-peng** [google/mediapipe#2831]
The [document](https://google.github.io/mediapipe/solutions/hands#output) says that there is a `visibility` value associated with each landmark in `multi_hand_world_landmarks`. 
However, when I'm printing them out, they all seem to be 0.0 (which I'm pretty sure are the default values). 
Is there a way to extract the visibility values for each hand landmark, or if my understanding is wrong?

I'm using the ready-to-go Python solution (Python 3.7.9) running on a Windows 10 desktop.

**Comment by sgowroji** [comment]
Hi @siyuan-peng, "multi_hand_world_landmarks" field  contains the hand landmarks on each detected hand in real-world 3D coordinates which is in meters with the origin at the hand's approximate geometric center. Could you please check with the latest version.

**Comment by siyuan-peng** [comment]
> Hi @siyuan-peng, "multi_hand_world_landmarks" field contains the hand landmarks on each detected hand in real-world 3D coordinates which is in meters with the origin at the hand's approximate geometric center. Could you please check with the latest version.

The [latest document](https://google.github.io/mediapipe/solutions/hands#multi_hand_world_landmarks) still contains a `visibility` description.

**Comment by gkarpiak** [comment]
@siyuan-peng thanks for the bug report. Indeed, it's a documentation bug - hand landmarks model doesn't output visibility. Documentation, should be fixed with the next release.

**Comment by hananbeer** [comment]
> [@siyuan-peng](https://github.com/siyuan-peng) thanks for the bug report. Indeed, it's a documentation bug - hand landmarks model doesn't output visibility. Documentation, should be fixed with the next release.

does the model not output confidence scores at all? or is it just the library not reading them? why?
