### ISSUE TITLE
getting error in android studio when App is started

### ISSUE THREAD

**Issue by niranjan-tech** [google/mediapipe#2833]
E/native: E20211130 10:11:55.696344 22541 calculator_graph.cc:805] INTERNAL: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "handlandmarktrackinggpu__palmdetectiongpu__inferencecalculator__handlandmarktrackinggpu__palmdetectiongpu__InferenceCalculator" failed: ; (TfLiteGpuDelegateBindBufferToTensor( delegate_.get(), gpu_buffers_in_.back()->GetOpenGlBufferWriteView().name(), interpreter_->inputs()[i]))==(kTfLiteOk)
E/SolutionBase: Error occurs while starting the MediaPipe solution graph. Error details: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "handlandmarktrackinggpu__palmdetectiongpu__inferencecalculator__handlandmarktrackinggpu__palmdetectiongpu__InferenceCalculator" failed: ; (TfLiteGpuDelegateBindBufferToTensor( delegate_.get(), gpu_buffers_in_.back()->GetOpenGlBufferWriteView().name(), interpreter_->inputs()[i]))==(kTfLiteOk)
    com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "handlandmarktrackinggpu__palmdetectiongpu__inferencecalculator__handlandmarktrackinggpu__palmdetectiongpu__InferenceCalculator" failed: ; (TfLiteGpuDelegateBindBufferToTensor( delegate_.get(), gpu_buffers_in_.back()->GetOpenGlBufferWriteView().name(), interpreter_->inputs()[i]))==(kTfLiteOk)
        at com.google.mediapipe.framework.Graph.nativeWaitUntilGraphIdle(Native Method)
        at com.google.mediapipe.framework.Graph.waitUntilGraphIdle(Graph.java:452)
        at com.google.mediapipe.solutioncore.SolutionBase.start(SolutionBase.java:126)
        at com.google.mediapipe.solutions.hands.Hands.<init>(Hands.java:155)
        at com.google.mediapipe.examples.hands.MainActivity.setupStreamingModePipeline(MainActivity.java:275)
        at com.google.mediapipe.examples.hands.MainActivity.lambda$setupLiveDemoUiComponents$9$MainActivity(MainActivity.java:260)
        at com.google.mediapipe.examples.hands.-$$Lambda$MainActivity$g0SRLoh0DlC9y-61r5BnVlAk-q4.onClick(lambda)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22462)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6221)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by sgowroji** [comment]
Hi @niranjan-tech, Could you please provide steps to reproduce the above error. Thanks!

**Comment by niranjan-tech** [comment]
> Hi @niranjan-tech, Could you please provide steps to reproduce the above error. Thanks!

The Application run was successful but when I press start camera it showed me above error.

**Comment by sgowroji** [comment]
Hi @niranjan-tech, Did you try the gradle approach to build android hands solutions. https://github.com/google/mediapipe/issues/2339#issuecomment-902841279

**Comment by ksiv** [comment]
I think I have same error. 
12/06 14:13:34: Launching 'hands' on Pixel 5 - API 31.
Install successfully finished in 127 ms.
$ adb shell am start -n "com.google.mediapipe.apps.hands/com.google.mediapipe.examples.hands.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 13740 on device 'pixel_5_-_api_31 [emulator-5554]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/pipe.apps.hand: Late-enabling -Xcheck:jni
W/pipe.apps.hand: Unexpected CPU variant for X86 using defaults: x86_64
I/ndk_translation: Initialized NDK translation (aarch64), version 0.2.3
V/studio.deploy: Startup agent attached to VM
V/studio.deploy: No existing instrumentation found. Loading instrumentation from instruments-1f2f27f8.jar
W/re-initialized>: type=1400 audit(0.0:339): avc: granted { execute } for path="/data/data/com.google.mediapipe.apps.hands/code_cache/startup_agents/4ba71210-agent.so" dev="dm-5" ino=139269 scontext=u:r:untrusted_app:s0:c146,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c146,c256,c512,c768 tclass=file app=com.google.mediapipe.apps.hands
W/pipe.apps.hand: DexFile /data/data/com.google.mediapipe.apps.hands/code_cache/.studio/instruments-1f2f27f8.jar is in boot class path but is not in a known location
V/studio.deploy: Applying transforms with cached classes
W/pipe.apps.hand: Redefining intrinsic method java.lang.Thread java.lang.Thread.currentThread(). This may cause the unexpected use of the original definition of java.lang.Thread java.lang.Thread.currentThread()in methods that have already been compiled.
W/pipe.apps.hand: Redefining intrinsic method boolean java.lang.Thread.interrupted(). This may cause the unexpected use of the original definition of boolean java.lang.Thread.interrupted()in methods that have already been compiled.
D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10146; state: DISABLED
W/pipe.apps.hand: Entry not found
W/pipe.apps.hand: Entry not found
W/pipe.apps.hand: Entry not found
W/pipe.apps.hand: JIT profile information will not be recorded: profile file does not exist.
W/pipe.apps.hand: JIT profile information will not be recorded: profile file does not exist.
W/pipe.apps.hand: JIT profile information will not be recorded: profile file does not exist.
V/GraphicsEnvironment: ANGLE Developer option for 'com.google.mediapipe.apps.hands' set to: 'default'
V/GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/libEGL: loaded /vendor/lib64/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv2_emulation.so
W/pipe.apps.hand: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0x73fc30d1b490, tid 13768
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
W/OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
D/EGL_emulation: eglCreateContext: 0x73fc30d1c150: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0x73fc30d1c150: ver 2 0 (tinfo 0x73fe52601080) (first time)
I/Gralloc4: mapper 4.x is not supported
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0x73fc30d1a710, tid 13768
D/goldfish-address-space: allocate: Ask for block of size 0x100
D/goldfish-address-space: allocate: ioctl allocate returned offset 0x3efffe000 size 0x2000
W/Gralloc4: allocator 4.x is not supported
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
W/System: A resource failed to call close. 
D/EGL_emulation: app_time_stats: avg=194.68ms min=3.05ms max=1198.81ms count=7
D/TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) with jobId=210577738 in 30000ms(Backend next call timestamp 1670324961420). Attempt 1
I/native: I20221206 11:13:36.287755 13740 asset_manager_util.cc:59] Created global reference to asset manager.
W/pipe.apps.hands: type=1400 audit(0.0:340): avc: denied { getattr } for path="/dev/pmsg0" dev="tmpfs" ino=465 scontext=u:r:untrusted_app:s0:c146,c256,c512,c768 tcontext=u:object_r:pmsg_device:s0 tclass=chr_file permissive=0 app=com.google.mediapipe.apps.hands
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0x73fc30d26950, tid 13740
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
W/EglManager: could not create GLES 3 context: java.lang.IllegalArgumentException: eglChooseConfig failed
D/EGL_emulation: eglCreateContext: 0x73fc30d26350: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0x73fc30d26350: ver 2 0 (tinfo 0x73fe52601100) (first time)
E/libEGL: validate_display:537 error 3008 (EGL_BAD_DISPLAY)
I/native: I20221206 11:13:36.408282 13740 gl_context_egl.cc:84] Successfully initialized EGL. Major : 1 Minor: 4
W/native: W20221206 11:13:36.409402 13740 gl_context_egl.cc:183] Creating a context with OpenGL ES 3 failed: UNKNOWN: ; eglChooseConfig() returned error 0x3000
W/native: W20221206 11:13:36.409709 13740 gl_context_egl.cc:184] Fall back on OpenGL ES 2.
D/EGL_emulation: eglCreateContext: 0x73fc30d264d0: maj 2 min 0 rcv 2
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0x73fc30d1f990, tid 13794
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
D/EGL_emulation: eglMakeCurrent: 0x73fc30d264d0: ver 2 0 (tinfo 0x73fe52601180) (first time)
I/native: I20221206 11:13:36.466877 13794 gl_context.cc:335] GL version: 2.0 (OpenGL ES 2.0 (4.5.0 NVIDIA 516.94))
I/native: I20221206 11:13:36.536020 13740 graph.cc:478] Start running the graph, waiting for inputs.
I/native: I20221206 11:13:36.593600 13797 resource_util_android.cc:89] Successfully loaded: palm_detection_full.tflite
I/native: I20221206 11:13:36.607448 13795 resource_util_android.cc:89] Successfully loaded: hand_landmark_full.tflite
I/tflite: Initialized TensorFlow Lite runtime.
I/tflite: Created TensorFlow Lite delegate for GPU.
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glBindBuffer:639 GL error 0x500 condition [!GLESv2Validation::bufferTarget(ctx, target)]
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glBufferData:664 GL error 0x500 condition [!GLESv2Validation::bufferTarget(ctx, target)]
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glBindBuffer:639 GL error 0x500 condition [!GLESv2Validation::bufferTarget(ctx, target)]
E/native: E20221206 11:13:36.626132 13740 calculator_graph.cc:844] INTERNAL: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "handlandmarktrackinggpu__palmdetectiongpu__inferencecalculator__handlandmarktrackinggpu__palmdetectiongpu__InferenceCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/inference_calculator_gl.cc:163) (TfLiteGpuDelegateBindBufferToTensor( delegate_.get(), gpu_buffers_in_.back()->GetOpenGlBufferWriteView().name(), interpreter_->inputs()[i]))==(kTfLiteOk)
E/SolutionBase: Error occurs while starting the MediaPipe solution graph. Error details: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "handlandmarktrackinggpu__palmdetectiongpu__inferencecalculator__handlandmarktrackinggpu__palmdetectiongpu__InferenceCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/inference_calculator_gl.cc:163) (TfLiteGpuDelegateBindBufferToTensor( delegate_.get(), gpu_buffers_in_.back()->GetOpenGlBufferWriteView().name(), interpreter_->inputs()[i]))==(kTfLiteOk)
    com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "handlandmarktrackinggpu__palmdetectiongpu__inferencecalculator__handlandmarktrackinggpu__palmdetectiongpu__InferenceCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/inference_calculator_gl.cc:163) (TfLiteGpuDelegateBindBufferToTensor( delegate_.get(), gpu_buffers_in_.back()->GetOpenGlBufferWriteView().name(), interpreter_->inputs()[i]))==(kTfLiteOk)
        at com.google.mediapipe.framework.Graph.nativeWaitUntilGraphIdle(Native Method)
        at com.google.mediapipe.framework.Graph.waitUntilGraphIdle(Graph.java:464)
        at com.google.mediapipe.solutioncore.SolutionBase.start(SolutionBase.java:126)
        at com.google.mediapipe.solutions.hands.Hands.<init>(Hands.java:155)
        at com.google.mediapipe.examples.hands.MainActivity.setupStreamingModePipeline(MainActivity.java:275)
        at com.google.mediapipe.examples.hands.MainActivity.lambda$setupLiveDemoUiComponents$9$com-google-mediapipe-examples-hands-MainActivity(MainActivity.java:260)
        at com.google.mediapipe.examples.hands.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7441)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.apps.hands, PID: 13740
    com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "handlandmarktrackinggpu__palmdetectiongpu__inferencecalculator__handlandmarktrackinggpu__palmdetectiongpu__InferenceCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/inference_calculator_gl.cc:163) (TfLiteGpuDelegateBindBufferToTensor( delegate_.get(), gpu_buffers_in_.back()->GetOpenGlBufferWriteView().name(), interpreter_->inputs()[i]))==(kTfLiteOk)
        at com.google.mediapipe.framework.Graph.nativeWaitUntilGraphIdle(Native Method)
        at com.google.mediapipe.framework.Graph.waitUntilGraphIdle(Graph.java:464)
        at com.google.mediapipe.solutioncore.SolutionBase.start(SolutionBase.java:126)
        at com.google.mediapipe.solutions.hands.Hands.<init>(Hands.java:155)
        at com.google.mediapipe.examples.hands.MainActivity.setupStreamingModePipeline(MainActivity.java:275)
        at com.google.mediapipe.examples.hands.MainActivity.lambda$setupLiveDemoUiComponents$9$com-google-mediapipe-examples-hands-MainActivity(MainActivity.java:260)
        at com.google.mediapipe.examples.hands.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7441)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
D/TransportRuntime.SQLiteEventStore: Storing event with priority=DEFAULT, name=COREML_ON_DEVICE_SOLUTIONS for destination cct
D/EGL_emulation: app_time_stats: avg=4.95ms min=1.51ms max=35.03ms count=56
D/TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/EGL_emulation: app_time_stats: avg=14.43ms min=1.51ms max=59.64ms count=40
D/EGL_emulation: app_time_stats: avg=11.59ms min=1.41ms max=61.65ms count=46
D/EGL_emulation: app_time_stats: avg=6.69ms min=1.19ms max=52.84ms count=52
I/Process: Sending signal. PID: 13740 SIG: 9


My hands/build.gradle ndk /sdk versions
android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"
    ndkVersion "21"


    defaultConfig {
        applicationId "com.google.mediapipe.apps.hands"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
    }
