### ISSUE TITLE
A sample code in the document could not be run properly

### ISSUE THREAD

**Issue by hosson** [google/mediapipe#2836]
https://google.github.io/mediapipe/getting_started/python_framework.html#:~:text=Start%20the%20graph,rgb_img).at(1))

When you run the code in the document, it outputs the following error messages:

`AttributeError: module 'mediapipe.python.packet_creator' has no attribute 'create_str'`
A right attribute name would be `'create_string'`.

`TypeError: create_image_frame() got an unexpected keyword argument 'format'`
A right keyword argument would be `'image_format'`.

**Comment by sgowroji** [comment]
Hi @hosson, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by hosson** [comment]
@sgowroji 
Thank you for your comment.
I think that only the sample code in the document has simply mistakes.
Therefore, you revise the document, and this problem will be resolved.

Just in case, I provide the steps to reproduce the above errors.

OS : ubuntu20.04
1. run `$ pip install mediapipe` and `$ pip install opencv-python`
2. run the following code in Python 3.8.12.
```
import mediapipe as mp
import cv2

config_text = """
  input_stream: 'in_stream'
  output_stream: 'out_stream'
  node {
    calculator: 'PassThroughCalculator'
    input_stream: 'in_stream'
    output_stream: 'out_stream'
  }
"""
graph = mp.CalculatorGraph(graph_config=config_text)
output_packets = []
graph.observe_output_stream(
    'out_stream',
    lambda stream_name, packet:
        output_packets.append(mp.packet_getter.get_str(packet)))

graph.start_run()

graph.add_packet_to_input_stream(
    'in_stream', mp.packet_creator.create_str('abc').at(0))

rgb_img = cv2.cvtColor(cv2.imread('/path/to/your/image.png'), cv2.COLOR_BGR2RGB)
graph.add_packet_to_input_stream(
    'in_stream',
    mp.packet_creator.create_image_frame(format=mp.ImageFormat.SRGB,
                                         data=rgb_img).at(1))
```
then the error messages will be output.

**Comment by jiuqiant** [comment]
Thanks for reporting. Will fix it in the coming release.

**Comment by sgowroji** [comment]
Hi @hosson, Can you please verify the above issue with next release and reach us back if you have any further queries. Thanks!
