### ISSUE TITLE
Skelton moving one person to another . 

### ISSUE THREAD

**Issue by ramkeshshadowcast** [google/mediapipe#2838]
Hello ,
When i am opening camera and there are more than one person so skeleton move from 1 person to another . Due to this value changed . How we can focus skeleton on single person ? . I know it works best with single person but i want it should not move when more then one persons are in front of camera . It should work with first detected person . How we can customize graph ? . If possible please let's us know . Reply asap please .

**Comment by sgowroji** [comment]
Hi @ramkeshshadowcast, Could you please go through [this](https://github.com/google/mediapipe/issues/1691#issuecomment-797159603) reference for clear understanding  of multi pose implementation.
