### ISSUE TITLE
How to debug an apk on an actual Android device?

### ISSUE THREAD

**Issue by pekochun** [google/mediapipe#2841]
-Environment
I use Windows and WSL.
The Ubuntu version is Ubuntu 18.04LTS.

-Bazel version
Bazelisk version: development
Build label: 4.2.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:17:47 2021 (1630336667)
Build timestamp: 1630336667
Build timestamp as int: 1630336667

**[Provide the exact sequence of commands / steps that you executed before running into the problem].

I used the following article to create an apk file and installed it on my Android.
I was able to build the app without any problems, but the app gave an error on the Android side and could not be launched.
How can I debug it in such a case?

https://medium.com/@asnkngt/windows-google-mediapipe-complete-android-setup-guide-2209b279abe4

```
bazel build -c dbg --config=android_arm64 --define 3D=true mediapipe/examples/android/src/java/com/google/mediapipe/apps/testApp

adb install bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/testApp/testApp.apk

adb connect 192.168.1.8:9999
```

**Comment by sgowroji** [comment]
Hi @pekochun, Can you check the logcat logs or adb bug report to check the errors w.r.t the apk.

**Comment by pekochun** [comment]
@sgowroji 
Thanks for the reply.

I usually use `adb root` in Windows command prompt.
Does your reply mean that I should change `adb root` to `adb logcat`?
Or can I just use `adb logcat` after running `adb root`?
I do not understand how to use logcat.

**Comment by sgowroji** [comment]
Hi @pekochun, You can understand it from here https://developer.android.com/studio/command-line/logcat. And for crashes or error you can search for FATAL errors or null pointer exceptions w.r.t MediaPipe.
