### ISSUE TITLE
base on opencv-4.5.1  , Use  build aar, crash ,dlopen failed: cannot locate symbol  "__subtf3"

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#2842]
System information (Please provide as much relevant information as possible)

OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
MediaPipe version: v0.8.6
Bazel version:bazel 4.1.0
Solution (e.g. FaceMesh, Pose, Holistic): HANDTRACK aar
Programming Language and version ( e.g. C++, Python, Java): Java
Describe the expected behavior:

My goal was to create an aar to  using the handtracking aar on Android Studio with gradle

When I replace the .aar file in the libs folder (from the face_detection and multi_hand_tracking demo/example projects) with the one that I generated following the steps in
https://google.github.io/mediapipe/getting_started/android_archive_library.html

I get the following crash at
System.loadLibrary("mediapipe_jni");

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__subtf3" referenced by "/data/app/~~IXWF_H6noRNss6OBiB8kZQ==/com.my.mediapipe.apps.myapplication-Eds2VNkZzhvjhYw-zhjNaw==/lib/arm64/libmediapipe_jni.so"...

So i  Switch to OpenCV 4.  but i need opencv-4.5.1  
sed -i -e 's:3.4.3/opencv-3.4.3:4.5.1/opencv-4.5.1:g' WORKSPACE
sed -i -e 's:libopencv_java3:libopencv_java4:g' third_party/opencv_android.BUILD

i use opencv-4.5.1  is different from opencv-4.0.1 in exzample . 
But it still reports an same error !
nm -D libmediapipe_jni.so |grep subtf3 
the symbol is still stay in.

**Comment by sgowroji** [comment]
Hi @chensisi0730, Can you try adding "api_level=21" as mentioned here https://github.com/google/mediapipe/issues/1224#issuecomment-745190852. and let me know if it works. Thanks!

**Comment by chensisi0730** [comment]
@sgowroji , I had tryed add "api_level=21"  ,but i do not work .

**Comment by chensisi0730** [comment]
i use opencv-4.5.1 is different from opencv-4.0.1 in exzample .
sed -i -e 's:3.4.3/opencv-3.4.3:4.5.1 /opencv-4.5.1 :g' WORKSPACE
sed -i -e 's:libopencv_java3:libopencv_java4:g' third_party/opencv_android.BUILD
$ nm -D libmediapipe_jni.so |grep subtf3 
0000000000cc3814 T __subtf3
$ nm -l libmediapipe_jni.so |grep subtf3 |c++filt
0000000000cc3814 T __subtf3	/usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/soft-fp/subtf3.c:35
0000000000cc3814 t $x	/usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/soft-fp/subtf3.c:36

the symbol is still stay in. But it still reports the same error !

**Comment by sgowroji** [comment]
Hi @chensisi0730,  Can you downgrade to use the preferred bazel version 3.7.2? Both MediaPipe and TensorFlow (tflite repo) are on that Bazel version.

**Comment by chensisi0730** [comment]
hi @sgowroji downgrade to bazel version 3.7.2  ,  But it still reports the same error !

**Comment by jiuqiant** [comment]
I never tried mediapipe aar with opencv 4.5.1. Do you have the sam issue with opencv 4.0.1? If the issue is specific to opencv 4.5, please consider reporting it to the opencv community.

**Comment by chensisi0730** [comment]
hi @jiuqiant  I used  latest mediapipe ,  and  create aar ：
cat mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example_handtrack/BUILD 
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_multi_hand_aar",
    calculators = ["//mediapipe/graphs/hand_tracking:mobile_calculators"],
)

the calculators is not ["//mediapipe/graphs/hand_tracking:multi_hand_mobile_calculators"], 

and  build command is :
bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example_handtrack:mp_multi_hand_aar.aar  
  then  follow  [https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example](url)  , replace the libopencv3.so to  libopencv4.so   ,and replace libmediapipe_jni.so  ?

**Comment by jiuqiant** [comment]
It doesn't matter whether we do the aar approach or build the example app by bazel directly. They should come end up with the same result/error.

Can you try to build mediapipe example app with OpenCV 4.0.x or OpenCV 4.1.x to verify if the issue is caused by some newly added code into OpenCV 4? Another suggestion is to use a higher ndk version that has the latest gcc features. ndk 21 might be too old.

According to
https://developer.arm.com/documentation/ka004751/1-0?lang=en&rev=3, the issue is related to the long double library on arm64.

**Comment by chensisi0730** [comment]
@jiuqiant When i use NDK23  ，build failded !

ERROR: /data/github_code/mediapipe-work/meidiapipe_latest/mediapipe/WORKSPACE:253:23: //external:android/crosstool depends on @androidndk//:default_crosstool in repository @androidndk which failed to fetch. no such package '@androidndk//': Expected directory at /data/programe-file/ANDRIOD_SDK/ndk/22.0.7026061/platforms but it is not a directory or it does not exist. Unable to read the Android NDK at /data/programe-file/ANDRIOD_SDK/ndk/22.0.7026061, the path may be invalid. Is the path in android_ndk_repository() or ANDROID_NDK_HOME set correctly? If the path is correct, the contents in the Android NDK directory may have been modified.
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example_handtrack:mp_multi_hand_aar.aar' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.290s
INFO: 0 processes.

**Comment by chensisi0730** [comment]
I want to update mediapipe and  opencv4  base on [https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example/issues](url) , but java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found

**Comment by jiuqiant** [comment]
You need to have NDK 22 first on your local system. Please install NDK 22 first via Android Studio and update the ANDROID_NDK_HOME variable accordingly. 

> @jiuqiant When i use NDK22  ，build failded !
> 
> 
> 
> ERROR: /data/github_code/mediapipe-work/meidiapipe_latest/mediapipe/WORKSPACE:253:23: //external:android/crosstool depends on @androidndk//:default_crosstool in repository @androidndk which failed to fetch. no such package '@androidndk//': Expected directory at /data/programe-file/ANDRIOD_SDK/ndk/22.0.7026061/platforms but it is not a directory or it does not exist. Unable to read the Android NDK at /data/programe-file/ANDRIOD_SDK/ndk/22.0.7026061, the path may be invalid. Is the path in android_ndk_repository() or ANDROID_NDK_HOME set correctly? If the path is correct, the contents in the Android NDK directory may have been modified.
> 
> ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example_handtrack:mp_multi_hand_aar.aar' failed; build aborted: Analysis failed
> 
> INFO: Elapsed time: 0.290s
> 
> INFO: 0 processes.
> 
>

**Comment by chensisi0730** [comment]
@jiuqiant  
I have installed  NDK 22 first via Android Studio , export  ANDROID_NDK_HOME=/data/programe-file/ANDRIOD_SDK/ndk/22.0.7026061 
Another point ， refer to  [https://google.github.io/mediapipe/getting_started/android.html#prerequisite](url)
Building Android example apps with Bazel
Prerequisite
Install MediaPipe following these instructions.
Setup Java Runtime.
Setup Android SDK release 28.0.3 and above.
Setup Android NDK version between 18 and 21.

**Comment by chensisi0730** [comment]
hi @jiuqiant @sgowroji   :
NDK version  can not updates  to 22 。 can you test it ?

**Comment by chensisi0730** [comment]
hi@sgowroji  #2636  in that replies , you said "follow the Prerequisites on NDK versions from documentation"

**Comment by sgowroji** [comment]
Hi @chensisi0730, Its updated now please check https://google.github.io/mediapipe/getting_started/android.html#prerequisite

**Comment by chensisi0730** [comment]
in  docs/getting_started/install.md
     Option 1. Follow
     [the official Bazel documentation](https://docs.bazel.build/versions/master/install-windows.html)
-    to install Bazel 3.7.2 or higher.
+    to install Bazel 4.2.1 or higher.

So  , i must  update to 4.2.1 ?

**Comment by chensisi0730** [comment]
> Hi @chensisi0730, Its updated now please check https://google.github.io/mediapipe/getting_started/android.html#prerequisite


@jiuqiant  I have installed NDK 22   via Android Studio  and  setup_android_sdk_and_ndk.sh   , test in 3 environment  (ubuntu16  ubuntu18  macos)  , but  all of them  update failed !

**Comment by jiuqiant** [comment]
Apologize for the trouble. I also don't have any clue why that happens since we never tried building mediapipe aar with opencv 4.5+. My suggestion is going back to opencv 4.1 or lower to build mediapipe aar.

Also, please consider https://maven.google.com/web/index.html?#com.google.mediapipe:hands.

**Comment by jiuqiant** [comment]
Apologize for the trouble. I also don't have any clue why that happens since we never tried building mediapipe aar with opencv 4.5+. My suggestion is going back to opencv 4.1 or lower to build mediapipe aar.

Also, please consider https://maven.google.com/web/index.html?#com.google.mediapipe:hands.


Update:
I can confirm that the issue is caused by opencv 4.5.1. The issue is not producible when the mediapipe apps is building with either opencv 3.4.3  or opencv 4.0.1 while I see missing symbol issues with opencv 4.5.1. Please consider downgrading the opencv version to a version that mediapipe supports.

To do the experiment, I modified the code as the following:

```
index 6331690..6405aa1 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -221,7 +221,7 @@ http_archive(
     build_file = "@//third_party:opencv_android.BUILD",
     strip_prefix = "OpenCV-android-sdk",
     type = "zip",
-    url = "https://github.com/opencv/opencv/releases/download/3.4.3/opencv-3.4.3-android-sdk.zip",
+    url = "https://github.com/opencv/opencv/releases/download/4.5.1/opencv-4.5.1-android-sdk.zip",
 )

 # After OpenCV 3.2.0, the pre-compiled opencv2.framework has google protobuf symbols, which will
@@ -413,3 +413,5 @@ libedgetpu_dependencies()

 load("@coral_crosstool//:configure.bzl", "cc_crosstool")
 cc_crosstool(name = "crosstool")
+android_sdk_repository(name = "androidsdk")
+android_ndk_repository(name = "androidndk")
diff --git a/third_party/opencv_android.BUILD b/third_party/opencv_android.BUILD
index 6c00457..391b834 100644
--- a/third_party/opencv_android.BUILD
+++ b/third_party/opencv_android.BUILD
@@ -5,7 +5,7 @@ licenses(["notice"])  # BSD license

 exports_files(["LICENSE"])

-OPENCV_LIBRARY_NAME = "libopencv_java3.so"
+OPENCV_LIBRARY_NAME = "libopencv_java4.so"

 OPENCVANDROIDSDK_NATIVELIBS_PATH = "sdk/native/libs/"
```

**Comment by jiuqiant** [comment]
Apologize for the trouble. I also don't have any clue why that happens since we never tried building mediapipe aar with opencv 4.5+. My suggestion is going back to opencv 4.1 or lower to build mediapipe aar.

Also, please consider https://maven.google.com/web/index.html?#com.google.mediapipe:hands.


Update:
I can confirm that the issue is caused by opencv 4.5.1. The issue is not producible when the mediapipe apps are building with either opencv 3.4.3  or opencv 4.0.1 while I see missing symbol issues with opencv 4.5.1. Please consider downgrading the opencv version to a version that mediapipe currently supports.

To do the experiment, I modified the code as the following:

```
index 6331690..6405aa1 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -221,7 +221,7 @@ http_archive(
     build_file = "@//third_party:opencv_android.BUILD",
     strip_prefix = "OpenCV-android-sdk",
     type = "zip",
-    url = "https://github.com/opencv/opencv/releases/download/3.4.3/opencv-3.4.3-android-sdk.zip",
+    url = "https://github.com/opencv/opencv/releases/download/4.5.1/opencv-4.5.1-android-sdk.zip",
 )

 # After OpenCV 3.2.0, the pre-compiled opencv2.framework has google protobuf symbols, which will
@@ -413,3 +413,5 @@ libedgetpu_dependencies()

 load("@coral_crosstool//:configure.bzl", "cc_crosstool")
 cc_crosstool(name = "crosstool")
+android_sdk_repository(name = "androidsdk")
+android_ndk_repository(name = "androidndk")
diff --git a/third_party/opencv_android.BUILD b/third_party/opencv_android.BUILD
index 6c00457..391b834 100644
--- a/third_party/opencv_android.BUILD
+++ b/third_party/opencv_android.BUILD
@@ -5,7 +5,7 @@ licenses(["notice"])  # BSD license

 exports_files(["LICENSE"])

-OPENCV_LIBRARY_NAME = "libopencv_java3.so"
+OPENCV_LIBRARY_NAME = "libopencv_java4.so"

 OPENCVANDROIDSDK_NATIVELIBS_PATH = "sdk/native/libs/"
```

**Comment by chensisi0730** [comment]
> Apologize for the trouble. I also don't have any clue why that happens since we never tried building mediapipe aar with opencv 4.5+. My suggestion is going back to opencv 4.1 or lower to build mediapipe aar.
> 
> Also, please consider https://maven.google.com/web/index.html?#com.google.mediapipe:hands.
> 
> Update: I can confirm that the issue is caused by opencv 4.5.1. The issue is not producible when the mediapipe apps are building with either opencv 3.4.3 or opencv 4.0.1 while I see missing symbol issues with opencv 4.5.1. Please consider downgrading the opencv version to a version that mediapipe currently supports.
> 
> To do the experiment, I modified the code as the following:
> 
hi @jiuqiant  
The issue   you mentioned  is " lack  symbol "__subtf3" "  or  can not update  NDK to r22 ?

**Comment by jiuqiant** [comment]
I still tried it with ndk 21. Back to your original issue, it's highly likely caused by the opencv version.

**Comment by chensisi0730** [comment]
> 
1、 So  you tried it with NDK21  and opencv4.5.1  ,  also   report " lack symbol "__subtf3" "  ? and could you attempt to NDK 22 and opencv4.5.1 ?
2 、With  opencv4.1.2 ,  system work ok ,  but  because some reason  ,  i can not  fallback (or  rollback) to 4.1 .2  in  actual use  because  other modules need to use Opencv4.5.1 

thank you very much !

**Comment by chensisi0730** [comment]
@jiuqiant   要不我们用中文交流吧？
我现在的任务就是产品的其他模块更新了 Opencv4.5.1  ，所以我要同步更新。然后就报错"__subtf3" 运行崩溃。然后升级ndk22也失败，您可以测试下，使用NDK22和opencv4.5.1  吗？

**Comment by jiuqiant** [comment]
For Android NDK, Bazel currently doesn't support Android NDK r22+. We have to use r21 and below.  https://github.com/bazelbuild/bazel/issues/12889 provides more details. Apologize for the previous wrong suggestion.

For OpenCV 4.5.1, we are in progress of removing MediaPipe from depending on OpenCV. Thus, we don't plan to support more new OpenCV versions. MediaPipe should work fine with OpenCV 3.x and OpenCV 4.0.x.

**Comment by jiuqiant** [comment]
For Android NDK, Bazel currently doesn't support Android NDK r22+. We have to use r21 and below.  https://github.com/bazelbuild/bazel/issues/12889 provides more details. Apologize for the previous wrong suggestion.

For OpenCV 4.5.1, we are in progress of removing MediaPipe from depending on OpenCV. Thus, we don't plan to support more new OpenCV versions. MediaPipe should work fine with OpenCV 3.x and OpenCV 4.0.x.

Please consider using MediaPipe Android Solution (https://maven.google.com/web/index.html?#com.google.mediapipe:hands) if possible. The  Android Solution uses OpenCV static libraries and shouldn't have the missing symbol issues.

**Comment by chensisi0730** [comment]
> For Android NDK, Bazel currently doesn't support Android NDK r22+. We have to use r21 and below. [bazelbuild/bazel#12889](https://github.com/bazelbuild/bazel/issues/12889) provides more details. Apologize for the previous wrong suggestion.
> 
> For OpenCV 4.5.1, we are in progress of removing MediaPipe from depending on OpenCV. Thus, we don't plan to support more new OpenCV versions. MediaPipe should work fine with OpenCV 3.x and OpenCV 4.0.x.
> 
> Please consider using MediaPipe Android Solution (https://maven.google.com/web/index.html?#com.google.mediapipe:hands) if possible. The Android Solution uses OpenCV static libraries and shouldn't have the missing symbol issues.

So  , can you OpenCV  version in homepage ?

**Comment by chensisi0730** [comment]
So  ,you never upgrade  opencv4.1.x  to hegher  opencv version ?

**Comment by jiuqiant** [comment]
> > For Android NDK, Bazel currently doesn't support Android NDK r22+. We have to use r21 and below. [bazelbuild/bazel#12889](https://github.com/bazelbuild/bazel/issues/12889) provides more details. Apologize for the previous wrong suggestion.
> > For OpenCV 4.5.1, we are in progress of removing MediaPipe from depending on OpenCV. Thus, we don't plan to support more new OpenCV versions. MediaPipe should work fine with OpenCV 3.x and OpenCV 4.0.x.
> > Please consider using MediaPipe Android Solution (https://maven.google.com/web/index.html?#com.google.mediapipe:hands) if possible. The Android Solution uses OpenCV static libraries and shouldn't have the missing symbol issues.
> 
> So , can you mark OpenCV version in homepage of MediaPipe?

We already mentioned it at 
 the beginning of https://github.com/google/mediapipe/blob/master/docs/getting_started/install.md.

**Comment by jiuqiant** [comment]
> So ,you never upgrade opencv4.1.x to hegher opencv version ?

Currently we don't have such plan.

**Comment by chensisi0730** [comment]
can  i  disabling opencv when defining MEDIAPIPE_DISABLE_OPENCV to 1 in the bazel command?

**Comment by chensisi0730** [comment]
or can i   compile MEDIAPIPE  and OPENCV  in  a staticLib ?

**Comment by chensisi0730** [comment]
@jiuqiant 
HI  ：jiuqiant
any updata  opencv4.5.1 ?
