### ISSUE TITLE
ETA for Instant Motion Tracking on iOS or other platforms?

### ISSUE THREAD

**Issue by aheze** [google/mediapipe#2844]
**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution: [Instant Motion Tracking](https://google.github.io/mediapipe/solutions/instant_motion_tracking)
- Programming language: Swift
- Are you willing to contribute it: Yes

**Describe the feature and the current behavior/state:**

Currently, Instant Motion Tracking seems to only be supported on Android:

[<kbd><img width="622" alt="Screenshot of README.md showing Instant Motion Tracking support for only Android" src="https://user-images.githubusercontent.com/49819455/144275973-f0b23ad6-45d2-4427-a27f-283f771076e0.png"></kbd>](https://github.com/google/mediapipe/blob/master/README.md)

**Will this change the current api? How?**

Possibly, some APIs might need to be changed to be consistent with both Android and iOS

**Who will benefit with this feature?**

Mobile developers for both iOS and Android

**Please specify the use cases for this feature:**

AR apps for iOS and possibly other platforms

**Any Other info:**

Thanks for all the amazing work!

**Comment by sgowroji** [comment]
MediaPipe has limited resources for new features.  While this is a good idea, we don't foresee any debo area.
