### ISSUE TITLE
Why are you guys not releasing the 3D annotation tool?

### ISSUE THREAD

**Issue by sarimmehdi** [google/mediapipe#2846]
[This](https://google.github.io/mediapipe/solutions/objectron.html#obtaining-real-world-3d-training-data) will be extremely beneficial for the community. Is there a reason why this tool is not being released to the general public?

**Comment by sgowroji** [comment]
Marking the above issue as duplicate of https://github.com/google/mediapipe/issues/2131 and please subscribe the parent issue for more details as we assigned engineer on it.

**Comment by sgowroji** [comment]
Hi @sarimmehdi, This was the last update w.r.t your request https://github.com/google/mediapipe/issues/1472#issuecomment-788708081. At Present there are no plans  to release the 3D Annotation tool. But we will share your request to the team to have a relook  again.
