### ISSUE TITLE
Undefined symbol with self-built MediaPipe Python package

### ISSUE THREAD

**Issue by HBnetDE** [google/mediapipe#2848]
**System information**
- OS Platform and Distribution: WSL - Ubuntu 20.04
- Compiler version: gcc 9.3.0
- Programming Language and version: Python 3.9.9 
- Installed using virtualenv? pip? Conda? (if python): Using the poetry package manager
- MediaPipe version: Cloned from master (commit cf101e62a9d49a51be76836b2b8e5ba5c06b5da0)
- Bazel version: 4.2.1
- OpenCV version (if running on desktop): 4.2.0

I am trying to build a python wheel for the mediapipe. However when I install the wheel in a python environment and attempt to
import it, I get the following error: `ImportError: <path to environment>/python3.9/site-packages/mediapipe/python/_framework_bindings.cpython-39-x86_64-linux-gnu.so: undefinded symbol: ippicviNormDiff_Inf_16_uC1R`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I have followed the steps provided [here](https://google.github.io/mediapipe/getting_started/python.html)
I have tried both option 1 and 2 for OpenCV installation.

I have created the python environment in the directory I cloned the mediapipe repository in:
```bash
python -m venv env
source ./env/bin/activate
pip install -r requirements.txt
```

I then built the program (logs provided for both commands):
```bash
python setup.py gen_protos
python setup.py bdist_wheel
```

Afterwards I installed the created wheel in a python environment.
In the activated python environment the following produces an error:
Shell:
```bash
python
```
Python interpreter
```py
import mediapipe
```
This produces the following error:
`ImportError: <path to environment>/python3.9/site-packages/mediapipe/python/_framework_bindings.cpython-39-x86_64-linux-gnu.so: undefinded symbol: ippicviNormDiff_Inf_16_uC1R`

I have also seen issue #1368 suggesting a different build flag for OpenCV. However, this does not seem to have changed anything.

**Logs**
The path to my home directory has been replaced with `$HOME` for privacy reasons.
[gen_protos.log](https://github.com/google/mediapipe/files/7640929/gen_protos.log)
[bdist_wheel.log](https://github.com/google/mediapipe/files/7640932/bdist_wheel.log)

**Comment by jiuqiant** [comment]
You probably can do the following to disable ippicv. 

```
diff --git a/third_party/BUILD b/third_party/BUILD
index e2044cfd..045e7577 100644
--- a/third_party/BUILD
+++ b/third_party/BUILD
@@ -107,6 +107,7 @@ cmake_external(
         "BUILD_PERF_TESTS": "OFF",
         "BUILD_EXAMPLES": "OFF",
         "BUILD_SHARED_LIBS": "ON" if OPENCV_SHARED_LIBS else "OFF",
+        "WITH_IPP": "OFF",
         "WITH_ITT": "OFF",
         "WITH_JASPER": "OFF",
         "WITH_JPEG": "ON",
```

Reference: https://stackoverflow.com/questions/38595169/in-the-context-of-opencv-what-is-ippicv

**Comment by HBnetDE** [comment]
Ok, now I'm getting the error: `ImportError: <path to environment>/python3.9/site-packages/mediapipe/python/_framework_bindings.cpython-39-x86_64-linux-gnu.so: undefinded symbol: _ZN2cv3MatC1Ev`

**Comment by HBnetDE** [comment]
I have tried to build it in a docker container instead of the wsl (Dockerfile attached).  The only changes I have made to mediapipe files is in third_party/opencv_linux.BUILD (also attached). I get the same error here
[Dockerfile.txt](https://github.com/google/mediapipe/files/7787979/Dockerfile.txt)
[opencv_linux.BUILD.txt](https://github.com/google/mediapipe/files/7787982/opencv_linux.BUILD.txt)
.

**Comment by ayushgdev** [comment]
Hello @HBnetDE Would you please try this again in the latest MediaPipe version?  A lot has changed and you should be able to build it without any issue.
