### ISSUE TITLE
Extract image from graph

### ISSUE THREAD

**Issue by eddiebarry** [google/mediapipe#285]
How can we get the exact image on which inference has been performed ?

In the android app, i think it can be accessed using "AndroidPacketGetter.java" file, but the usage documentation could be more elaborate.

Could someone please help ?

Also, i tried the opencv image encode calculator but it is crashing the android app when included in the graph

i included         "//mediapipe/calculators/image:opencv_image_encoder_calculator", in the Graph build file.

The error being thrown is 

"cannot locate symbol "_ZN2cv8imencodeERKNS_6StringERKNS_11_InputArray"

which i think means cannot find the shared object which contains the cv::imencode to string from Input array method

**Comment by lcycoding** [comment]
I believe the `getBitmapFromRgba(Packet packet)` in AndroidPacketGetter.java will help.

But you need to revise the calculator itself to output an `ImageFrame` Packet first.

Note: Also remember to add `processor.getGraph ().addPacketCallback("stream name", new PacketCallback(){})` before your graph's start/preheat process.

**Comment by eddiebarry** [comment]
Thank you so much

**Comment by zerohit** [comment]
Can you share the code that solves this problem, thank you very much
