### ISSUE TITLE
Some problems in deploying the target detection. Tflite model to Android devices

### ISSUE THREAD

**Issue by honggang0524** [google/mediapipe#2852]
In the target detection task, replace the model with my own model and deploy it to the Android device. The CPU can run normally. When I try to run on the Android GPU device, the app opens and a black screen appears. Print logcat and prompt: Calculator:: process() for node "tflitetensorstodetectionscolculator" Failed: read buffer does not match write buffer size. Gpu graph does not make any node modification, but only changes some parameters to make them more consistent with my model.

**Comment by sgowroji** [comment]
Hi @honggang0524, Could you please provide complete details to reproduce  steps and device information in which the black screen appears. Thanks!

**Comment by honggang0524** [comment]
I want to implement a pedestrian Detection task, use my own data set, train according to the steps in Tensorflow Object Detection API, and convert it into a. Tflite model.

When I placed the obtained.tflite model in the Mediapipe framework, I first copied a copy of all object_Detection files and performed all the following steps in that folder.

Step_A: Modify some parameters of graph, such as image size,. Tflite path, lab_map path

Step_B: to avoid tflite_tensors_to_detections_calculator TfLiteTensorToDetectionsCalculator of class conflict, amend the name of the class, the corresponding graph do replacement.


Step_C: After completing the above steps, both desktop and CPU_Android can be detected.I got an error when I deployed it on GPU_Android.

Some of the software and versions are as follows:

Bazel: 2

The SDK: 31.0.0

NDK:2.0

OPENCV: 3.4.16

The Android version of my mobile device is 11 with snapdragon 865 processor.

If you need any more information, please contact me by email, thank you very much!!



| |
honggang0524
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/3/2021 ***@***.***> wrote：

Hi @honggang0524, Could you please provide complete details to reproduce steps and device information in which the black screen appears. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sgowroji** [comment]
Thank you for the above details. Could you please share the complete error logs to investigate the issue further. Thanks!

**Comment by honggang0524** [comment]
Sure

I am using the following command to print log: adb shell "logcat | grep PID", get the following error log:

12-06 14:54:42.344  9230  9313 E FrameProcessor: Mediapipe error: 

12-06 14:54:42.344  9230  9313 E FrameProcessor: com.google.mediapipe.framework.MediaPipeException: invalid argument: Graph has errors: 

12-06 14:54:42.344  9230  9313 E FrameProcessor: Calculator::Process() for node "TfLiteTensorsToDetectionsCalculatorForPerson" failed: Read buffer does not match write buffer size.

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:404)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:458)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:405)

12-0614:54:42.344 9230 9313EFrameProcessor:        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:340)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source:4)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at android.os.Handler.handleCallback(Handler.java:938)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at android.os.Handler.dispatchMessage(Handler.java:99)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at android.os.Looper.loop(Looper.java:257)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)















| |
honggang0524
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/6/2021 ***@***.***> wrote：

Thank you for the above details. Could you please share the complete error logs to investigate the issue further. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by honggang0524** [comment]
Hi, there is another situation that feels necessary to mention, in the model transformation discipline, the uint8 model is obtained, while mediapipe's Tflite model is all of float32 type. Does it have an impact on the final deployment results?

Attached below is my latest error log:

2021-12-07 13:56:26.810 E/tflite: Following operations are not supported by GPU delegate:

    ADD: OP is supported, but tensor type/shape doesn't supported.

2021-12-07 13:56:26.807 I/tflite: Created TensorFlow Lite delegate for GPU.

    CONCATENATION: OP is supported, but tensor type/shape doesn't supported.

    CONV_2D: OP is supported, but tensor type/shape doesn't supported.

    CUSTOM TFLite_Detection_PostProcess: TFLite_Detection_PostProcess

2021-12-07 13:56:26.463 E/libc: Access denied finding property "vendor.camera.aux.packagelist"

    DEPTHWISE_CONV_2D: OP is supported, but tensor type/shape doesn't supported.

    DEQUANTIZE: Operation is not supported.

2021-12-07 13:56:26.810 E/tflite: Following operations are not supported by GPU delegate:

    LOGISTIC: OP is supported, but tensor type/shape doesn't supported.

    QUANTIZE: Operation is not supported.

    ADD: OP is supported, but tensor type/shape doesn't supported.

    RESHAPE: OP is supported, but tensor type/shape doesn't supported.

    CONCATENATION: OP is supported, but tensor type/shape doesn't supported.

    No operations will run on the GPU, and all 110 operations will run on the CPU.

    CONV_2D: OP is supported, but tensor type/shape doesn't supported.

    CUSTOM TFLite_Detection_PostProcess: TFLite_Detection_PostProcess

    DEPTHWISE_CONV_2D: OP is supported, but tensor type/shape doesn't supported.

    DEQUANTIZE: Operation is not supported.

    LOGISTIC: OP is supported, but tensor type/shape doesn't supported.



| |
honggang0524
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/6/2021 ***@***.***> wrote：

Sure

I am using the following command to print log: adb shell "logcat | grep PID", get the following error log:

12-06 14:54:42.344  9230  9313 E FrameProcessor: Mediapipe error: 

12-06 14:54:42.344  9230  9313 E FrameProcessor: com.google.mediapipe.framework.MediaPipeException: invalid argument: Graph has errors: 

12-06 14:54:42.344  9230  9313 E FrameProcessor: Calculator::Process() for node "TfLiteTensorsToDetectionsCalculatorForPerson" failed: Read buffer does not match write buffer size.

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:404)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:458)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:405)

12-0614:54:42.344 9230 9313EFrameProcessor:        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:340)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source:4)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at android.os.Handler.handleCallback(Handler.java:938)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at android.os.Handler.dispatchMessage(Handler.java:99)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at android.os.Looper.loop(Looper.java:257)

12-06 14:54:42.344  9230  9313 E FrameProcessor:        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)















| |
honggang0524
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/6/2021 ***@***.***> wrote：

Thank you for the above details. Could you please share the complete error logs to investigate the issue further. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kuaashish** [comment]
Hello @honggang0524,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
