### ISSUE TITLE
Problem with pbtxt file on the TF serving server

### ISSUE THREAD

**Issue by Luna0214** [google/mediapipe#2853]
I am trying to serve the mediapipe landmark pbtxt file on the tensorserving which accept ONLY pb fomat file.
May I ask you to how I get the pb file or please guide me to get it.

**Comment by sgowroji** [comment]
Hi @Luna0214, Could you please elaborate your use case w.r.t the above query. Thanks!

**Comment by Luna0214** [comment]
What I am trying to do is, using mediapipe model serving via tensorserving for my school project.
So I clone the repos. of mediapipe and the pose_landmark_cpu.pbtxt file put on the server which is can't parse on the TF serving.
Therefore I need the pb format version of mediapipe pose_landmark_cpu to serve.
I have tried some code from some website:

`import tensorflow as tf
from tensorflow.python.saved_model import signature_constants
from tensorflow.python.saved_model import tag_constants

export_dir = './saved'
graph_pb = 'my_quant_graph.pb'

builder = tf.saved_model.builder.SavedModelBuilder(export_dir)

with tf.gfile.GFile(graph_pb, "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

sigs = {}

with tf.Session(graph=tf.Graph()) as sess:
    # name="" is important to ensure we don't get spurious prefixing
    tf.import_graph_def(graph_def, name="")
    g = tf.get_default_graph()
    inp = g.get_tensor_by_name("real_A_and_B_images:0")
    out = g.get_tensor_by_name("generator/Tanh:0")

    sigs[signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY] = \
        tf.saved_model.signature_def_utils.predict_signature_def(
            {"in": inp}, {"out": out})

    builder.add_meta_graph_and_variables(sess,
                                         [tag_constants.SERVING],
                                         signature_def_map=sigs)

builder.save()`

BUT STILL not working.

What I want is pose_landmark with pb format file.
Please help.

**Comment by jiuqiant** [comment]
Mediapipe uses tflite for inference and the model format is .tflite. TF serving is for tensorflow models and the saved model format is a .pb file. So, they are two different systems and you probably can't use Mediapipe models with TF serving.
