### ISSUE TITLE
How to perform transformations on frames before they enter the graph? (Hands)

### ISSUE THREAD

**Issue by 123epsilon** [google/mediapipe#2855]
I am trying to perform a hue shift on certain images before they enter the MediaPipe Hands graph, using the example app. What is the proper way to do this? Either I'd like to edit the camera stream before it is converted from an OpenGL texture to a regular texture or I would like to edit the converted texture frame before it is fed to the frame processor. 

I have looked into using native CameraX or OpenGLES20 methods and have not found what I'm looking for. Can anyone please advise as to how to implement this?

**Comment by sgowroji** [comment]
Hi @123epsilon, Could you please elaborate your use case with complete details. What transformations do you want to perform on frames.

**Comment by 123epsilon** [comment]
@sgowroji Specifically I want to convert to HSV and rotate the hue or perform some corresponding operation in RGB. The main issue here is that it is not clear how to perform this operation on a SurfaceTexture prior to it being read by the frameprocessor.

Here is an example using python and cv2:

```
def rotate_hue(val, deg):
       return (val + deg) % 180"

re, frame = cap.read() #reading in camera frames using cv2
image = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
  
hsv_frame = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
angle = angles[index] #this can just be any angle 0-360
hsv_frame[:, :, 0] = rotate_hue(hsv_frame[:, :, 0], angle)
hsv_frame = np.array(hsv_frame, dtype=np.uint8)
image = cv2.cvtColor(hsv_frame, cv2.COLOR_HSV2BGR)

# flip the image
image = cv2.flip(image,1)
image.flags.writeable = False
results = hands.process(image)

```

**Comment by mcclanahoochie** [comment]
Which platform/language is this? If this is for Python, you can just insert your code above into the [hands example](https://google.github.io/mediapipe/solutions/hands#python-solution-api).

Alternatively, have you considered just writing a calculator to do this, and have that be the first calculator in the graph? There are many calculators you [could use as an example](https://github.com/google/mediapipe/tree/master/mediapipe/calculators/image).

**Comment by 123epsilon** [comment]
@sgowroji @mcclanahoochie 

I am currently working on a calculator to perform this operation using OpenCV. I am a little confused as to where to find information on many of the objects that the Calculator depends upon such as CalculatorContract, CalculatorContext, Inputs, Outputs, ImageFrame etc. In the meanwhile I've been looking through the mediapipe source to get an idea of how to use them. 

I have a few questions:
1) I intend to insert this calculator in the vanilla hand tracking graph just after the FlowLimiterCalcuator, is this the right place to put this functionality? I wanted to avoid any synchronization problems.

2) I assumed that the ImageFrame outputted from the FlowLimiterCalculator would be RGB but I know that CameraX by default returns a YCbCr format, which format should I expect as my input?

3) I implemented the hue shift on the input image by extracting the cv::Mat representation of the image, converting to HSV using OpenCV, iterating through the pixels to shift the hue values individually, and then using cv::cvtColor to convert back to RGB. How can I then convert the resulting cv::Mat object to an ImageFrame object (which I assume the rest of the graph expects).

I greatly appreciate all the help I've received so far - we are much closer now to completing our application thanks to the great support we have received from the Mediapipe team and community!

As this is my first time working with Mediapipe I've included my code below, please let me know if I've made any mistakes thus far:


```
#include "absl/strings/str_cat.h"
#include "mediapipe/framework/calculator_framework.h"
#include "mediapipe/framework/formats/image_frame.h"
#include "mediapipe/framework/formats/image_frame_opencv.h"
#include "mediapipe/framework/port/opencv_core_inc.h"
#include "mediapipe/framework/port/opencv_imgproc_inc.h"

namespace mediapipe {

// For every image frame in the input stream, convert to HSV and perform a hue shift
// by delta degrees, output as RGBA image frame.
//
// Example config:
// node {
//   calculator: "HueShiftCalculator"
//   input_side_packet: "DELTA:hue_delta"
//   input_stream: "IMAGE:image"
//   output_stream: "HUE_IMG:hue_shifted_image"
// }
//

class HueShiftCalculator : public CalculatorBase {
	public:
		static absl::Status GetContract(CalculatorContract* cc) {
			//Classes extending CalculatorBase must implement GetContract
			//Here we set the expected types for each input and output
			cc->Inputs().Index(tick_signal_index).SetAny();
			cc->Inputs().Tag("DELTA").Set<int>();
			cc->Inputs().Tag("IMAGE").Set<ImageFrame>();
			cc->Outputs().Tag("HUE_IMG").Set<ImageFrame>();

			return absl::OkStatus();
		}

	//Process is run repeatedly as long as input stream packets are available
	absl::Status Process(CalculatorContext* cc) final {
		// Store input signals.

		//get delta and rgb image frame
		int hue_shift = cc->Inputs().Tag("DELTA").Get<Int>();
		//<<<I'm assuming that this input is RGB but this could be incorrect>>>
		ImageFrame rgb_frame = cc->Inputs().Tag("IMAGE").Get<ImageFrame>();
		cv::Mat hsv_frame_mat;
		//convert rgb frame to hsv and store in hsv_frame_mat
		cv::Mat rgb_frame_mat = ::mediapipe::formats::MatView(&rgb_frame);
		cv::cvtColor(rgb_frame_mat, hsv_frame_mat, CV_RGB2HSV);

		//perform hue shift by delta degrees
		//https://answers.opencv.org/question/178766/adjust-hue-and-saturation-like-photoshop/
		for (int j = 0; j < hsv_frame_mat.rows; j++)
		{
			for (int i = 0; i < hsv_frame_mat.cols; i++)
			{
				// Get hue at 0th channel. OpenCV Hue is constrained to [-180,180] 
				// Saturation is hsv.at<Vec3b>(j, i)[1], and 
				// Value is hsv.at<Vec3b>(j, i)[2].
				hsv_frame_mat.at<Vec3b>(j, i)[0] = (hsv_frame_mat.at<Vec3b>(j, i)[0] + (unsigned char) hue_shift) % 180;
			}
		}

		cv::cvtColor(hsv_frame_mat, rgb_frame_mat, CV_HSV2RGB);

		//<<<how to convert this matrix into an ImageFrame?>>>

		return absl::OkStatus();
	}

};

REGISTER_CALCULATOR(HueShiftCalculator);
}  // namespace mediapipe
```

**Comment by mcclanahoochie** [comment]
If you are using an android mediapipe example as your base, when frames get to the graph they are in RGBA format already, on GPU. You don't need to worry about YUV conversion. 

You may need a [GpuBufferToImageFrameCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/object_detection/object_detection_mobile_cpu.pbtxt#L15) to get ImageFrame into your calculator.  (and possibly the opposite: ImageFrameToGpuBufferCalculator for converting back to GPU).

I would reference other code such as [RenderCPU here](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/image/set_alpha_calculator.cc#L234) for guidance on handling input/output streams and ImageFrame<->cv::Mat conversion ... but it looks like you almost have it.

**Comment by 123epsilon** [comment]
> If you are using an android mediapipe example as your base, when frames get to the graph they are in RGBA format already, on GPU. You don't need to worry about YUV conversion.
> 
> You may need a [GpuBufferToImageFrameCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/object_detection/object_detection_mobile_cpu.pbtxt#L15) to get ImageFrame into your calculator. (and possibly the opposite: ImageFrameToGpuBufferCalculator for converting back to GPU).
> 
> I would reference other code such as [RenderCPU here](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/image/set_alpha_calculator.cc#L234) for guidance on handling input/output streams and ImageFrame<->cv::Mat conversion ... but it looks like you almost have it.

Thank you! I had just run into the issue of converting an ImageFrame to GPUBuffer and this reply helped a lot! I will implement this over the next few days and close this issue within the week if I can get the calculator to work. 

To be clear, in order to manipulate an ImageFrame, I should just obtain the underlying cv::Mat and make changes to that object, which will then be reflected in the ImageFrame object? From there I can send it to the output stream as I did above, yes?

**Comment by 123epsilon** [comment]
As a sanity check I figured I would post my updated calculator and graph for feedback:

Calculator:
```
//Process is run repeatedly as long as input stream packets are available
    absl::Status Process(CalculatorContext* cc) final {
        // Store input signals.
        //get delta and rgba image frame
        int hue_shift = cc->InputSidePackets().Tag("DELTA").Get<int>();
        const ImageFrame &rgba_frame = cc->Inputs().Tag("IMAGE").Get<ImageFrame>();
        cv::Mat rgba_frame_mat = :mediapipe::formats::MatView(&rgba_frame)

        //opencv provides rgb->hsv but no rgba->hsv conversion
        //convert rgba to rgb
        cv::Mat rgb_frame_mat(rgba_frame_mat.rows, rgba_frame_mat.cols, rgba_frame_mat.type());
        cv::cvtColor(rgba_frame_mat, rgb_frame_mat, CV_RGBA2RGB);

        //convert rgb frame to hsv and store in hsv_frame_mat
        cv::Mat hsv_frame_mat(rgb_frame_mat.rows, rgb_frame_mat.cols, rgb_frame_mat.type());
        cv::cvtColor(rgb_frame_mat, hsv_frame_mat, CV_RGB2HSV);

        //perform hue shift by delta degrees
        //https://answers.opencv.org/question/178766/adjust-hue-and-saturation-like-photoshop/
        for (int j = 0; j < hsv_frame_mat.rows; j++)
        {
            for (int i = 0; i < hsv_frame_mat.cols; i++)
            {
                // Get hue at 0th channel. OpenCV Hue is constrained to [0, 179]
                // Saturation is hsv.at<Vec3b>(j, i)[1], and
                // Value is hsv.at<Vec3b>(j, i)[2].
                hsv_frame_mat.at<cv::Vec3b>(j, i)[0] = (hsv_frame_mat.at<cv::Vec3b>(j, i)[0] + (unsigned char) hue_shift) % 180;
            }
        }

        //hsv back to rgb
        cv::Mat new_rgb_frame_mat(hsv_frame_mat.rows, hsv_frame_mat.cols, hsv_frame_mat.type());
        cv::cvtColor(hsv_frame_mat, new_rgb_frame_mat, CV_HSV2RGB)

        //rgb back to rgba with final output_frame
        //changed to use absl::make_unique
        auto output_frame = absl::make_unique<ImageFrame>(rgba_frame.Format(), rgba_frame.Width(), rgba_frame.Height());
        cv::Mat shifted_mat = ::mediapipe::formats::MatView(output_frame.get());
        cv::cvtColor(new_rgb_frame_mat, shifted_mat, CV_RGB2RGBA);

        //send to output stream
        cc->Outputs().Tag("HUE_IMG").Add(output_frame.release(), cc->InputTimestamp());

        return absl::OkStatus();
    }
```

Hand Tracking Graph:
```
# MediaPipe graph that performs multi-hand tracking with TensorFlow Lite on GPU.
# Used in the examples in
# mediapipe/examples/android/src/java/com/mediapipe/apps/handtrackinggpu.

# GPU image. (GpuBuffer)
input_stream: "input_video"

# Max number of hands to detect/process. (int)
input_side_packet: "num_hands"

# Model complexity (0 or 1). (int)
input_side_packet: "model_complexity"

#HueShift to perform
input_side_packet: "hue_delta"

# GPU image. (GpuBuffer)
output_stream: "output_video"
# Collection of detected/predicted hands, each represented as a list of
# landmarks. (std::vector<NormalizedLandmarkList>)
output_stream: "hand_landmarks"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

#convert gpubuffer to image frame for custom hue shift calculator
node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "throttled_input_video"
  output_stream: "throttled_input_video_cpu"
}

#custom hue shift calculator
node {
  calculator: "HueShiftCalculator"
  input_side_packet: "DELTA:hue_delta"
  input_stream: "IMAGE:throttled_input_video_cpu"
  output_stream: "HUE_IMG:hue_shifted_image"
}

#convert image frame to gpu buffer for inference
node{
    calculator: "ImageFrameToGpuBufferCalculator"
    input_stream: "hue_shifted_image"
    output_stream: "hue_shifted_image_gpu"
}

# Detects/tracks hand landmarks.
node {
  calculator: "HandLandmarkTrackingGpu"
  input_stream: "IMAGE:hue_shifted_image_gpu"
  input_side_packet: "MODEL_COMPLEXITY:model_complexity"
  input_side_packet: "NUM_HANDS:num_hands"
  output_stream: "LANDMARKS:hand_landmarks"
  output_stream: "HANDEDNESS:handedness"
  output_stream: "PALM_DETECTIONS:palm_detections"
  output_stream: "HAND_ROIS_FROM_LANDMARKS:hand_rects_from_landmarks"
  output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:hand_rects_from_palm_detections"
}

# Subgraph that renders annotations and overlays them on top of the input
# images (see hand_renderer_gpu.pbtxt).
node {
  calculator: "HandRendererSubgraph"
  input_stream: "IMAGE:hue_shifted_image_gpu"
  input_stream: "DETECTIONS:palm_detections"
  input_stream: "LANDMARKS:hand_landmarks"
  input_stream: "HANDEDNESS:handedness"
  input_stream: "NORM_RECTS:0:hand_rects_from_palm_detections"
  input_stream: "NORM_RECTS:1:hand_rects_from_landmarks"
  output_stream: "IMAGE:output_video"
}
```

Please let me know if I made any obvious mistakes, thank you!

**Comment by sgowroji** [comment]
@123epsilon, Did you see any errors with your above  calculator?

**Comment by 123epsilon** [comment]
@sgowroji Sorry for the delay, the above calculator generates the following error:

A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 19801 (mediapipe/19801), pid 19710 (ple.phantomouse)

Could this be a problem in how we are using the unique pointer?

**Comment by mcclanahoochie** [comment]
i think this is creating an RGBA mat

```
 cv::Mat rgb_frame_mat(rgba_frame_mat.rows, rgba_frame_mat.cols, rgba_frame_mat.type());
```
use CV_8UC3 instead
