### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'createTexture')

### ISSUE THREAD

**Issue by khalid-alsaleh-dev** [google/mediapipe#2856]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createTexture')
    at __glGenObject (cdn.jsdelivr.net/npm/@mediapipe/holistic/holistic_solution_simd_wasm_bin.js:9)
    at _glGenTextures (cdn.jsdelivr.net/npm/@mediapipe/holistic/holistic_solution_simd_wasm_bin.js:9)
    at cdn.jsdelivr.net/npm/@mediapipe/holistic/holistic_solution_simd_wasm_bin.wasm
    at cdn.jsdelivr.net/npm/@mediapipe/holistic/holistic_solution_simd_wasm_bin.wasm
    at Object.createTexture (eval at new_ (cdn.jsdelivr.net/npm/@mediapipe/holistic/holistic_solution_simd_wasm_bin.js:9), <anonymous>:7:10)
    at oa.h (static/js/vendors~main.chunk.js:2619)
    at ra (static/js/vendors~main.chunk.js:628)
    at sa.next (static/js/vendors~main.chunk.js:658)
    at b (static/js/vendors~main.chunk.js:679)

  Getting this error while using holistic solution on react.js

  "dependencies": {
        "@mediapipe/camera_utils": "^0.3.1632432234",
        "@mediapipe/control_utils": "^0.6.1629159505",
        "@mediapipe/drawing_utils": "^0.3.1620248257",
        "@mediapipe/holistic": "^0.5.1635989137",
        "@testing-library/jest-dom": "^5.11.4",
        "@testing-library/react": "^11.1.0",
        "@testing-library/user-event": "^12.1.10",
        "bootstrap": "^5.1.3",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-router-dom": "^6.0.2",
        "react-scripts": "4.0.3",
        "react-webcam": "^6.0.0",
        "web-vitals": "^1.0.1"
    },

**Comment by sgowroji** [comment]
Hi @khalid-alsaleh-dev, Could you please provide steps to reproduce the above error. Thanks!

**Comment by khalid-alsaleh-dev** [comment]
This is my code:

useEffect(() => {
    const holistic = new Holistic({
      locateFile: (file) => {
        console.log(`${file}`);
        return `https://cdn.jsdelivr.net/npm/@mediapipe/holistic/${file}`;
      },
    });
    holistic.setOptions({
      modelComplexity: 1,
      smoothLandmarks: true,
      minDetectionConfidence: 0.5,
      minTrackingConfidence: 0.5,
    });
    holistic.onResults(onResults);

    if (
      typeof webcamRef.current !== "undefined" &&
      webcamRef.current !== null
    ) {
      const camera = new Camera(webcamRef.current.video, {
        onFrame: async () => {
          await holistic.send({ image: webcamRef.current.video });
        },
        width: 1280,
        height: 720,
      });
      camera.start();
    }
  }, []);

**Comment by sgowroji** [comment]
Hi @khalid-alsaleh-dev, Could you please go through this https://github.com/google/mediapipe/issues/1735#issuecomment-804419168 for the above error. Thanks!
