### ISSUE TITLE
Why do we transform the color image to COLOR_BGR2RGB? 

### ISSUE THREAD

**Issue by sn1c3** [google/mediapipe#2858]
I am using the pose and hands solutions for a while now. What I wondered ever since is why we transform the image colors before processing?

Code line from [pose](https://google.github.io/mediapipe/solutions/pose) : 
```
# Convert the BGR image to RGB before processing.
results = pose.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
```
Of course, mediapipe performs way better with it, but I do not exactly know why. I have read the underlying studies for these models and I have found no explanation for this.

**Comment by czy2014hust** [comment]
The format from cv2.imread() is BGR, but the model(algorithm) should have input image with RGB format.

**Comment by sgowroji** [comment]
Hi @sn1c3,

You can find the same in site packages 


> 
> def process(self, image: np.ndarray) -> NamedTuple:
>     """ Processes an RGB image and returns the pose landmarks on the most prominent person detected.
> 
>     Args:
>       image: An RGB image represented as a numpy ndarray.
> 
>     Raises:
>       RuntimeError: If the underlying graph throws any error.
>       ValueError: If the input image is not three channel RGB.

**Comment by sn1c3** [comment]
Oh sorry for the late reply. Thanks this solved my problem!

**Comment by bug-author** [comment]
wondering the same. the answers above answer the what, not the why part.
