### ISSUE TITLE
Getting error when importing LandmarkGrid from '@mediapipe/control_utils_3d'

### ISSUE THREAD

**Issue by AHRealift** [google/mediapipe#2859]
Getting error when importing LandmarkGrid from '@mediapipe/control_utils_3d'

TypeError: Cannot read properties of undefined (reading 'Vector3')

dependencies:
"@mediapipe/camera_utils": "^0.3.1632336052",
"@mediapipe/control_utils": "^0.6.1629159505",
"@mediapipe/control_utils_3d": "^0.2.1625245254",
"@mediapipe/drawing_utils": "^0.3.1620248257",
"@mediapipe/pose": "^0.4.1630009814",

Reproducible code: https://codesandbox.io/s/icy-brook-5pqne?file=/src/index.js

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2578

**Comment by AHRealift** [comment]
Solution: `<script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d/control_utils_3d.js" crossorigin="anonymous" ></script>`
