### ISSUE TITLE
Multi hand detection - Android - Error parsing graph

### ISSUE THREAD

**Issue by aaaldo** [google/mediapipe#286]
Hello,

I'm working on a hand gesture piloted app for Android. Up to last week, i was successfully testing the single hand gesture recognition using an aar + binarygraph generated following this guide (https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md).

Unfortunatly, my attempt to try the multi hand gesture failed : i'm encountering the following issue at runtime : 

`E/native: E1202 15:14:30.472064 29428 graph.cc:411] ; Input Stream "hand_landmarks" for node with sorted index 4 does not have a corresponding output stream.`

I've run through all the pbtxt and didn't found any problems using the graph visualisation tool.

Any idea to help ? 

Thanks in advance.

**Comment by eknight7** [comment]
Can you do a fresh pull and retry?

**Comment by aaaldo** [comment]
My bad actually, it was an old PacketCallback from my code that was calling this input stream. Sorry for the false bug, thought it was due to the graph itself, as stated in the error message.
All clear ! Thanks for the support !
