### ISSUE TITLE
How is the hand_landmark gesture model used on binocular camera images?  

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#2860]
How is the hand_landmark gesture model used on binocular camera images?

**Comment by sgowroji** [comment]
Hi @LMR2018, Could you please elaborate your use case with complete details. Thanks!

**Comment by LMR2018** [comment]
> 嗨@LMR2018，您能否用完整的细节详细说明您的用例。谢谢！

I want to pinpoint the z-axis depth coordinates of hand_landmark gesture model. can I do it with a binocular camera?  If so, what should I do?

**Comment by LMR2018** [comment]
@sgowroji    I want to pinpoint the z-axis depth coordinates of hand_landmark gesture model. can I do it with a binocular camera? If so, what should I do?

**Comment by sgowroji** [comment]
Hi @LMR2018, We haven't tried any such before. Could you please try and check the above with Hands solutions and let us know the behaviour. Thanks!

**Comment by mzhkby** [comment]
Hello, how do you realize the binocular camera?I can't open two cameras at the same time using CameraX.

**Comment by mzhkby** [comment]
@LMR2018
