### ISSUE TITLE
Hand Landmark for a custom aarch64 board

### ISSUE THREAD

**Issue by gaurav-parashar** [google/mediapipe#2861]
<em>Thanks a lot team for creating such an amazing tool.Kudos!<em>

I am trying to use mediapipe framework for hand gesture recognition. The challenging part is, the board on which I am trying to run the inference, is running on Debian OS with aarch64 architecture. And I am restricted to use only a fraction of available memory on the board. (4GB of RAM and around 10GB of storage space, in which 6-7GB is already occupied).
- Since I just want handlandmark features, is it possible to get just that part, and not the complete mediapipe package?
- I tried using tflite models available in the repository, but they were not accurate enough to get the task done, hence I am planning to stick with the full model. 

Any help/suggestions in this direction would be really helpful.

Cheers,
Gaurav

**Comment by ayushgdev** [comment]
Hello @gaurav-parashar 

We are revisiting older issues. To answer your questions:
1. It is not possible to get just a single solution segregated from mediapipe framework.
2. The TfLite model are the same models used in the framework as well, however, part of the power of MediaPipe comes from the preprocessing as well. As long as you are following same preprocessing steps, you should be able to get similar accuracy as with E2E solution usage. As an excerpt of the preprocessing, the preprocessing of the image is done in several steps:

- [`ImageTransformationCalculator`](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_tracking_cpu_image.pbtxt#L98) in hand_landmark_tracking_cpu.pbtxt file scales, rotates, and flips images horizontally or vertically. This image is fed to handlandmarkcpu subgraph.
- [`ImageToTensorCalculator`](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_cpu.pbtxt#L40)  in hand_landmark_cpu.pbtxt file (subgraph) transforms a region of image into a 224x224 tensor while keeping the aspect ratio, and therefore may result in potential letterboxing.
...
...  // Perform model inference
...
- [`TensorsToLandmarksCalculator`](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_cpu.pbtxt#L156)  in hand_landmark_cpu.pbtxt file decodes the landmark tensors coming from model inference, into a list of landmarks and performs normalization of landmarks
- [`LandmarkLetterboxRemovalCalculator`](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_cpu.pbtxt#L176) adjusts those normalized landmarks on the letterboxed hand image to the corresponding locations on the same image with the letterbox removed (hand image before image transformation).
