### ISSUE TITLE
TfLiteInferenceCalculator failed to load model.

### ISSUE THREAD

**Issue by shivambhardwaj120** [google/mediapipe#2862]
<em> I tried to load my custom model with TfliteInferenceCalculator. It gave following error:
IrisTrackingGpuApp[1840:609884] The model is not a valid Flatbuffer buffer. I passed the path of a tflite model and I am working with latest mediapipe. I am building a IOS app.<em>

**Comment by sgowroji** [comment]
Hi @shivambhardwaj120, Could you please provide steps to reproduce the above error. Thanks!

**Comment by shivambhardwaj120** [comment]
Hi @sgowroji,  I changed  a lot of things in the subgraph of iris tracking subgraph, I am not sure,  you can reproduce it directly. Subgraph takes a GPU image as input, resize it to (224,224,3), make it a cpu image, passes it to "TfLiteConverterCalculator" and then to 
node {
calculator: "TfLiteInferenceCalculator"
input_stream: "TENSORS:right_image_tensor"
output_stream: "TENSORS:right_detection_tensors"
node_options: {
[type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
model_path: "mediapipe/models/custom.tflite"

}
}
}

**Comment by gkarpiak** [comment]
@shivambhardwaj120 there's a chance that your model is not available at the path you provided, try to look what you need to do make sure your iOS has custom.tflite model.

For example for iris demo models are ensured by including them into "data": https://github.com/google/mediapipe/blob/master/mediapipe/examples/ios/iristrackinggpu/BUILD#L66-L67

**Comment by sgowroji** [comment]
Hi @shivambhardwaj120, Could you please verify the issue w.r.t the above [comment](https://github.com/google/mediapipe/issues/2862#issuecomment-989028569). Thanks!

**Comment by shivambhardwaj120** [comment]
Hi @gkarpiak,  you were right, I didn't know that I need to update the path to IristrackinggpuApp build as well. I updated only the subgraph of iristracking graph and build of model folder. Thanks @gkarpiak @sgowroji for the help.
