### ISSUE TITLE
How to configure 3d models in Android hand tracking GPU?  I want more accurate z coordinates, okay?  

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#2864]
How to configure 3d models in Android hand tracking GPU?  I want more accurate z coordinates, okay?

**Comment by sgowroji** [comment]
Hi @LMR2018,  On Android Hands gradle you can find the result of https://github.com/google/mediapipe/blob/d4bb35fe5a44b3419ca86e4c7ecbc931dded2122/mediapipe/java/com/google/mediapipe/solutions/hands/HandsResult.java#:~:text=//%20Collection%20of%20detected/tracked%20hands%27%20landmarks,%7D. To run on GPU you should enable runOnGput to True
