### ISSUE TITLE
Are there NDK version  any updates ？

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#2866]
[https://google.github.io/mediapipe/](url) have this  describe ：
Building Android example apps with Bazel
Prerequisite
Install MediaPipe following these instructions.
Setup Java Runtime.
Setup Android SDK release 28.0.3 and above.
Setup Android NDK version between 18 and 21.

Are there NDK version  any updates ？

**Comment by sgowroji** [comment]
There is already a duplicate issue https://github.com/google/mediapipe/issues/2842 is open . So closing this above issue and please subscribe for the latest updates on the duplicate ticket for further comments.
