### ISSUE TITLE
Using face_geometry on the basis of face_mesh does not work.

### ISSUE THREAD

**Issue by lilinxiong** [google/mediapipe#2867]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.8
- Bazel version: 4.2.1
- Solution (e.g. FaceMesh, Pose, Holistic): FaceGeometry
- Programming Language and version ( e.g. C++, Python, Java): C++

**Describe the expected behavior:**

I can get the face_mesh landmark on Windows, and they can work normally. I now want to get the pose matrix, scale, rotation, translation, etc. of the face. On Android, I can get it through face_geometry. Can I use the same method on Windows? To get it?

**Standalone code you may have used to try to get what you need :**

I tried to build a new pbtxt as follows:
```pbtxt
# MediaPipe graph that performs face mesh with TensorFlow Lite on CPU.

# Input image. (ImageFrame)
input_stream: "input_video"

# Output image with rendered results. (ImageFrame)
output_stream: "output_video"
output_stream: "video_presence"

# Collection of detected/processed faces, each represented as a list of
# landmarks. (std::vector<NormalizedLandmarkList>)
output_stream: "multi_face_landmarks"
output_stream: "landmark_presence"

output_stream: "multi_face_geometry"
output_stream: "geometry_presence"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Defines side packets for further use in the graph.
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:0:num_faces"
  output_side_packet: "PACKET:1:with_attention"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet { int_value: 1 }
      packet { bool_value: true }
    }
  }
}

node {
  calculator: "FaceGeometryEnvGeneratorCalculator"
  output_side_packet: "ENVIRONMENT:environment"
  node_options: {
    [type.googleapis.com/mediapipe.FaceGeometryEnvGeneratorCalculatorOptions] {
      environment: {
        origin_point_location: TOP_LEFT_CORNER
        perspective_camera: {
          vertical_fov_degrees: 63.0  # 63 degrees
          near: 1.0  # 1cm
          far: 10000.0  # 100m
        }
      }
    }
  }
}

# Subgraph that detects faces and corresponding landmarks.
node {
  calculator: "FaceLandmarkFrontCpu"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "NUM_FACES:num_faces"
  input_side_packet: "WITH_ATTENTION:with_attention"
  output_stream: "LANDMARKS:multi_face_landmarks"
  output_stream: "ROIS_FROM_LANDMARKS:face_rects_from_landmarks"
  output_stream: "DETECTIONS:face_detections"
  output_stream: "ROIS_FROM_DETECTIONS:face_rects_from_detections"
}

# Extracts a single set of face landmarks associated with the most prominent
# face detected from a collection.
node {
  calculator: "SplitNormalizedLandmarkListVectorCalculator"
  input_stream: "multi_face_landmarks"
  output_stream: "face_landmarks"
  node_options: {
    [type.googleapis.com/mediapipe.SplitVectorCalculatorOptions] {
      ranges: { begin: 0 end: 1 }
      element_only: true
    }
  }
}

# Extracts the input image frame dimensions as a separate packet.
node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "SIZE:input_image_size"
}

# Applies smoothing to the single set of face landmarks.
node {
  calculator: "FaceLandmarksSmoothing"
  input_stream: "NORM_LANDMARKS:face_landmarks"
  input_stream: "IMAGE_SIZE:input_image_size"
  output_stream: "NORM_FILTERED_LANDMARKS:smoothed_face_landmarks"
}

# Puts the single set of smoothed landmarks back into a collection to simplify
# passing the result into the `FaceGeometryFromLandmarks` subgraph.
node {
  calculator: "ConcatenateLandmarListVectorCalculator"
  input_stream: "smoothed_face_landmarks"
  output_stream: "multi_smoothed_face_landmarks"
}

# Computes face geometry from face landmarks for a single face.
node {
  calculator: "FaceGeometryFromLandmarks"
  input_stream: "MULTI_FACE_LANDMARKS:multi_smoothed_face_landmarks"
  input_stream: "IMAGE_SIZE:input_image_size"
  input_side_packet: "ENVIRONMENT:environment"
  output_stream: "MULTI_FACE_GEOMETRY:multi_face_geometry"
}

# Subgraph that renders face-landmark annotation onto the input image.
node {
  calculator: "FaceRendererCpu"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "LANDMARKS:multi_face_landmarks"
  input_stream: "NORM_RECTS:face_rects_from_landmarks"
  input_stream: "DETECTIONS:face_detections"
  output_stream: "IMAGE:output_video"
}

# add PacketPresenceCalculator
node {
  calculator: "PacketPresenceCalculator"
  input_stream: "PACKET:multi_face_landmarks"
  output_stream: "PRESENCE:landmark_presence"
}

# add PacketPresenceCalculator
node {
  calculator: "PacketPresenceCalculator"
  input_stream: "PACKET:multi_face_geometry"
  output_stream: "PRESENCE:geometry_presence"
}

# add PacketPresenceCalculator
node {
  calculator: "PacketPresenceCalculator"
  input_stream: "PACKET:output_video"
  output_stream: "PRESENCE:video_presence"
}
```

The contents of the BUILD script are as follows:
```bazel
load("//mediapipe/library/desktop:windows_dll_library.bzl", "windows_dll_library")
licenses(["notice"])

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["//examples:__pkg__"],
)

package(default_visibility = ["//mediapipe/examples:__subpackages__"])

windows_dll_library(
    name = "MPFaceMeshGeometry",
    srcs = [
        ...
        ],
    hdrs = [
        ...
        ],
    # Define COMPILING_DLL to export symbols during compiling the DLL.
    copts = ["/DCOMPILING_DLL"],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/formats:image_frame",
        "//mediapipe/framework/formats:image_frame_opencv",
        "//mediapipe/framework:packet",
        "//mediapipe/framework/formats:detection_cc_proto",
        "//mediapipe/framework/formats:landmark_cc_proto",
        "//mediapipe/framework/formats:matrix",
        "//mediapipe/framework/formats:rect_cc_proto",
        "//mediapipe/framework/port:file_helpers",
        "//mediapipe/framework/port:opencv_highgui",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",

        # FaceMesh
        "//mediapipe/calculators/core:constant_side_packet_calculator",
        "//mediapipe/calculators/core:packet_presence_calculator",
        "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/graphs/face_mesh/subgraphs:face_renderer_cpu",
        "//mediapipe/modules/face_landmark:face_landmark_front_cpu",
        # FaceGeometry
        "//mediapipe/modules/face_geometry:env_generator_calculator",
        "//mediapipe/calculators/core:split_vector_calculator",
        "//mediapipe/calculators/image:image_properties_calculator",
        "//mediapipe/graphs/face_effect/subgraphs:face_landmarks_smoothing",
        "//mediapipe/calculators/core:concatenate_vector_calculator",
        "//mediapipe/modules/face_geometry:face_geometry_from_landmarks",
    ]
)
## Link to face_mesh_lib.dll through its import library.
cc_binary(
    name = "MPFaceMeshGeometry_cpu",
    srcs = [ "MP_HUMAN_3D_TEST.cpp", ],
    deps = [
        "//third_party:glog",
        "//mediapipe/framework/port:opencv_highgui",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:opencv_video",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        ":MPFaceMeshGeometry",
    ],
    data = [
        "//mediapipe/graphs/face_effect:face_effect_gpu.binarypb",
        "//mediapipe/modules/face_geometry/data:geometry_pipeline_metadata.binarypb",
    ],
)
```

It seems logically no problem, but it does not work.

**Other info / Complete Logs :**
I saw [cannot get geometry_pipeline_metadata.binarypb to be built #1584](https://github.com/google/mediapipe/issues/1584)
My purpose is not to use Face_effect to work on Windows, I only need the face_geometry in [face_geometry.proto#pose_transform_matrix](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/face_geometry.proto#L59)
If there are other ways to get the matrix, then I can not use face_geometry. Can you help me? thank you very much!

**Comment by lilinxiong** [comment]
oh~ I found the problem, in the location of [geometry_pipeline.cc#L127-L130](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc#L127-L130), Check the incoming landmark_list. 
The model I use is: [face_landmark_with_attention.tflite](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_landmark/face_landmark_with_attention.tflite), The number of landmarks it outputs is 478, not 468. So it is not working properly. 
I got the [canonical_metric_landmarks_.cols()](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc#L128) size from [geometry_pipeline.cc](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc) and the number of vertex_buffer in [geometry_pipeline_metadata_landmarks.pbtxt](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt) is related.
So I have a question now, in the face_geometry module, is there no need for the landmark of the iris? If it is not needed, how can the modification be more reasonable? If necessary, do you need to modify  [geometry_pipeline_metadata_landmarks.pbtxt](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt)?

**Comment by lilinxiong** [comment]
I have changed it to make it more suitable for the actual scene. The changes are as follows:
[geometry_pipeline.cc#L127-L133](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc#L127-L133):
```c++
    RET_CHECK_GT(screen_landmark_list.landmark_size(),
                 canonical_metric_landmarks_.cols())
        << "The number of landmarks doesn't match the number passed upon landmark_size: " 
        << screen_landmark_list.landmark_size() 
        << " canonical_metric_landmarks_.cols: " 
        << canonical_metric_landmarks_.cols() 
        << " initialization!";

    Eigen::Matrix3Xf screen_landmarks = Eigen::Matrix3Xf(3, canonical_metric_landmarks_.cols());
    ConvertLandmarkListToEigenMatrix(screen_landmark_list, screen_landmarks);
```
[geometry_pipeline.cc#L260-L270](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc#L260-L270):

```c++
  static void ConvertLandmarkListToEigenMatrix(
      const NormalizedLandmarkList& landmark_list,
      Eigen::Matrix3Xf& eigen_matrix) {
    for (int i = 0; i < eigen_matrix.cols(); ++i) {
      const auto& landmark = landmark_list.landmark(i);
      eigen_matrix(0, i) = landmark.x();
      eigen_matrix(1, i) = landmark.y();
      eigen_matrix(2, i) = landmark.z();
    }
  }
```

reason:
The number of landmarks used in face_geometry is not less than the number it needs, which is 468. Then create a matrix according to canonical_metric_landmarks_.cols(). Even if the subsequent (geometry_pipeline_metadata_landmarks.pbtxt)[https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt] is modified (decreased or increased), it will not affect the normal process.
If you approve of my modification, I will mention pr.

**Comment by lilinxiong** [comment]
The following heading has been revised, this heading is more suitable for the content of the discussion.

**Comment by lilinxiong** [comment]
@sgowroji Does anyone reply to me.

**Comment by ianni67** [comment]
> I have changed it to make it more suitable for the actual scene. The changes are as follows: [geometry_pipeline.cc#L127-L133](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc#L127-L133):
> 
> ```c++
>     RET_CHECK_GE(screen_landmark_list.landmark_size(),
>                  canonical_metric_landmarks_.cols())
>         << "The number of landmarks doesn't match the number passed upon landmark_size: " 
>         << screen_landmark_list.landmark_size() 
>         << " canonical_metric_landmarks_.cols: " 
>         << canonical_metric_landmarks_.cols() 
>         << " initialization!";
> 
>     Eigen::Matrix3Xf screen_landmarks = Eigen::Matrix3Xf(3, canonical_metric_landmarks_.cols());
>     ConvertLandmarkListToEigenMatrix(screen_landmark_list, screen_landmarks);
> ```
> 
> [geometry_pipeline.cc#L260-L270](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc#L260-L270):
> 
> ```c++
>   static void ConvertLandmarkListToEigenMatrix(
>       const NormalizedLandmarkList& landmark_list,
>       Eigen::Matrix3Xf& eigen_matrix) {
>     for (int i = 0; i < eigen_matrix.cols(); ++i) {
>       const auto& landmark = landmark_list.landmark(i);
>       eigen_matrix(0, i) = landmark.x();
>       eigen_matrix(1, i) = landmark.y();
>       eigen_matrix(2, i) = landmark.z();
>     }
>   }
> ```
> 
> reason: The number of landmarks used in face_geometry is not less than the number it needs, which is 468. Then create a matrix according to canonical_metric_landmarks_.cols(). Even if the subsequent [geometry_pipeline_metadata_landmarks.pbtxt](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt) is modified (decreased or increased), it will not affect the normal process. If you approve of my modification, I will mention pr.

@lilinxiong thank you very much for sharing your solution. Did you check that the solution actually returns a correct matrix? I'd love to adopt it but I'm a bit afraid of changing that part of the code.

**Comment by lilinxiong** [comment]
> > I have changed it to make it more suitable for the actual scene. The changes are as follows: [geometry_pipeline.cc#L127-L133](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc#L127-L133):
> > ```c++
> >     RET_CHECK_GE(screen_landmark_list.landmark_size(),
> >                  canonical_metric_landmarks_.cols())
> >         << "The number of landmarks doesn't match the number passed upon landmark_size: " 
> >         << screen_landmark_list.landmark_size() 
> >         << " canonical_metric_landmarks_.cols: " 
> >         << canonical_metric_landmarks_.cols() 
> >         << " initialization!";
> > 
> >     Eigen::Matrix3Xf screen_landmarks = Eigen::Matrix3Xf(3, canonical_metric_landmarks_.cols());
> >     ConvertLandmarkListToEigenMatrix(screen_landmark_list, screen_landmarks);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [geometry_pipeline.cc#L260-L270](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc#L260-L270):
> > ```c++
> >   static void ConvertLandmarkListToEigenMatrix(
> >       const NormalizedLandmarkList& landmark_list,
> >       Eigen::Matrix3Xf& eigen_matrix) {
> >     for (int i = 0; i < eigen_matrix.cols(); ++i) {
> >       const auto& landmark = landmark_list.landmark(i);
> >       eigen_matrix(0, i) = landmark.x();
> >       eigen_matrix(1, i) = landmark.y();
> >       eigen_matrix(2, i) = landmark.z();
> >     }
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > reason: The number of landmarks used in face_geometry is not less than the number it needs, which is 468. Then create a matrix according to canonical_metric_landmarks_.cols(). Even if the subsequent [geometry_pipeline_metadata_landmarks.pbtxt](https://github.com/google/mediapipe/blob/v0.8.8/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt) is modified (decreased or increased), it will not affect the normal process. If you approve of my modification, I will mention pr.
> 
> @lilinxiong thank you very much for sharing your solution. Did you check that the solution actually returns a correct matrix? I'd love to adopt it but I'm a bit afraid of changing that part of the code.

@ianni67 It is correct, because the iris coordinates are added after the original face_landmark, and then become 478 landmarks. The modification I made here is to abandon the landmarks of the following 10 iris. This modification does not affect the original Only 468 points are needed in the process to generate the matrix.

**Comment by ianni67** [comment]
Thank you very much, @lilinxiong for your kind reply. I added your modifications to my project and I can confirm that it is working.

**Comment by lilinxiong** [comment]
> Thank you very much, @lilinxiong for your kind reply. I added your modifications to my project and I can confirm that it is working.

you are welcome! I'm very happy to be able to help you.

**Comment by ianni67** [comment]
As reported in issue #1786, the changes proposed by @lilinxiong work perfectly but represent only a work-around. The correct solution would be, in my opinion, allowing the geometry pipeline calculator to process all the 478 landmarks produced by the attention model, thus including the iris landmarks in the process. This would fix  an internal incongruence of the mediapipe framework and, at the same time, allow us to rely on an approximate, yet useful, estimate of the irises in the Metric space
Possible AR applications coherent with the current mediapipe trend would be, for example, changing the eye color, or adding artificial light reflexes onto the eye.

**Comment by lilinxiong** [comment]
> As reported in issue #1786, the changes proposed by @lilinxiong work perfectly but represent only a work-around. The correct solution would be, in my opinion, allowing the geometry pipeline calculator to process all the 478 landmarks produced by the attention model, thus including the iris landmarks in the process. This would fix an internal incongruence of the mediapipe framework and, at the same time, allow us to rely on an approximate, yet useful, estimate of the irises in the Metric space Possible AR applications coherent with the current mediapipe trend would be, for example, changing the eye color, or adding artificial light reflexes onto the eye.

I agree with your opinion. But I want to say another point. In the original face_landmark, only 468 face landmarks were generated, and iris was added through a later module. Then face_geometry is only used for face_landmarks. In later versions, through ``with_attention``, face_landmarks supports the output of left right iris landmarks. 

Note: that ``with_attention`` is optional, not required. If it is false, then 468 landmarks are still output in the end.

So face_geometry is not obligated to process the 478 points containing iris landmarks. If it can handle it, then really great. So my modification point is: ```RET_CHECK_EQ -> RET_CHECK_GE``` takes into account that if 478 points are supported in the future, then it can also run from a code point of view.  Because the data of ```canonical_metric_landmarks_``` is from [geometry_pipeline_metadata_landmarks.pbtxt](https://github.com/google/mediapipe/blob/v0.8.9/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt).

**Comment by kuaashish** [comment]
Hello @lilinxiong,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
