### ISSUE TITLE
How to get 2 world-coordinate outputs("multi_hand_world_landmarks" and "pose_world_landmarks") in one pbtxt?

### ISSUE THREAD

**Issue by BingoZha** [google/mediapipe#2868]
A few days ago,i got the "pose_world_landmarks" output in holistic_tracking,but i also needed the fingers' tracking in world-coordinate system,so i added the output in holistic_tracking_cpu.pbtxt:
node {
  calculator: "HolisticLandmarkCpu"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "POSE_LANDMARKS:pose_landmarks"
  output_stream: "POSE_ROI:pose_roi"
  output_stream: "POSE_DETECTION:pose_detection"
  output_stream: "FACE_LANDMARKS:face_landmarks"
  output_stream: "LEFT_HAND_LANDMARKS:left_hand_landmarks"
  output_stream: "RIGHT_HAND_LANDMARKS:right_hand_landmarks"
  output_stream: "WORLD_LANDMARKS:pose_world_landmarks"
  output_stream: "WORLD_LANDMARKS:multi_hand_world_landmarks"
}

When i ran it,it generated an error:
E20211207 17:14:09.696341 21756 demo_run_graph_main.cc:286] Failed to run the graph: while processing the output streams of subgraph node HolisticLandmarkCpu: ; tag "WORLD_LANDMARKS" index 0 already had a name "pose_world_landmarks" but is being reassigned a name "multi_hand_world_landmarks"

Maybe it doesn't support in holistic module.I found that hands module has the output called "multi_hand_world_landmarks",so could you tell me any methods to add this output in holistic_tracking_cpu.pbtxt?

**Comment by sgowroji** [comment]
Hi @BingoZha, Could you please provide steps to reproduce the error with usecase. Thanks!

**Comment by BingoZha** [comment]
Hi @sgowroji  I modified the file (mediapipe\graphs\holistic_tracking\holistic_tracking_cpu.pbtxt).I added two outputs and modified the "HolisticLandmarkCpu" node：

...
output_stream: "pose_world_landmarks"
output_stream: "multi_hand_world_landmarks"
...
node {
  calculator: "HolisticLandmarkCpu"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "POSE_LANDMARKS:pose_landmarks"
  output_stream: "POSE_ROI:pose_roi"
  output_stream: "POSE_DETECTION:pose_detection"
  output_stream: "FACE_LANDMARKS:face_landmarks"
  output_stream: "LEFT_HAND_LANDMARKS:left_hand_landmarks"
  output_stream: "RIGHT_HAND_LANDMARKS:right_hand_landmarks"
  output_stream: "WORLD_LANDMARKS:pose_world_landmarks"
  output_stream: "WORLD_LANDMARKS:multi_hand_world_landmarks"
}
...
It obviously looks wrong,but i have no idea to add output "multi_hand_world_landmarks".The issue can be simplified to ”Could one pbtxt have two world-coordinate outputs? “.
Thanks.

**Comment by BingoZha** [comment]
Hi @sgowroji  Could you have any methods to convert location(normallanmarks) to world-coordinate location?

**Comment by BingoZha** [comment]
I modified the subgraphs and it works,but the pose_world_landmarks did not synchronize with the hands_world_landmarks.Could you have any ideas?

**Comment by naomipappe** [comment]
Hi @BingoZha! 

Could you please share how you modified the sub-graphs? Did you manage to obtain the `pose_world_landmarks` data?

**Comment by BingoZha** [comment]
> Hi @BingoZha!
> 
> Could you please share how you modified the sub-graphs? Did you manage to obtain the `pose_world_landmarks` data?

This can help you.
git clone -b unreal https://github.com/wongfei/mediapipe.git ue4-mediapipe-wrapper 

https://github.com/wongfei/ue4-mediapipe-plugin

**Comment by kuaashish** [comment]
Hello @BingoZha,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
