### ISSUE TITLE
Python package being built is 0.8 not latest

### ISSUE THREAD

**Issue by anoop54** [google/mediapipe#2869]
Hi, I built the python package through docker & everything worked fine. However the version on this package is 0.8, not 0.8.9. Why is that the case? When I pip install mediapipe on my non aarch machine I will get the latest package 0.8.9, but with building my self I get 0.8. 

I noticed in setup.py has __version__ which is 0.8 & has not changed over the various version.

**Comment by jiuqiant** [comment]
The setup.py we release is for customizing graphs and testing locally. We probably should put "local" or "dev" as the version tag to make this point clear. If you are looking for an official version, please go to https://pypi.org/project/mediapipe.
