### ISSUE TITLE
Can not build example on fresh checkout

### ISSUE THREAD

**Issue by kubat** [google/mediapipe#287]
Hello,

I have a vanilla machine with prerequisites installed (OSX 10.14.6; homebrew) per [these instructions](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md). Attempting to build/run the following error:

```console
% bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu
ERROR: /Users/kubat/Documents/code/mediapipe/mediapipe/framework/profiler/BUILD:267:1: Illegal ambiguous match on configurable attribute "copts" in //mediapipe/framework/profiler:profiler_resource_util:
//mediapipe:apple
//mediapipe:macos
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu' failed; build aborted: 

/Users/kubat/Documents/code/mediapipe/mediapipe/framework/profiler/BUILD:267:1: Illegal ambiguous match on configurable attribute "copts" in //mediapipe/framework/profiler:profiler_resource_util:
//mediapipe:apple
//mediapipe:macos
Multiple matches are not allowed unless one is unambiguously more specialized.
INFO: Elapsed time: 0.360s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 17 targets configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 17 targets configured)
```
The same errors are seen with the hello world example.

As I'm new to bazel, I'm unsure what flags may need to be passed to specifify this is `:macos` and not for ios (I'm assuming that's what `:apple` is targeting).

Is this a global configuration? Or flaw in build files?

Best,
Rony

**Comment by jiuqiant** [comment]
I believe it's caused by using Bazel 1.2.1 on mac. Sorry about the inconvenience and we are working on a fix. If you are looking for a temporary workaround. Please read [the updated instruction](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-macos) to downgrade to Bazel 1.1.0.
