### ISSUE TITLE
Vectors concatenation and clipping enhancements

### ISSUE THREAD

**Issue by kaomoneus** [google/mediapipe#2871]
**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): cf101e62
- Programming language : C++
- Are you willing to contribute it (Yes/No): Yes

It would be good to enhance vector concatenation and clipping operations.

### Concatenation
Concatetation works fine except that sometimes it's good to clip it.

### Clipping
Currently clipping takes first *N* items of the vector. But it would be good though to parametrize it to take *N* items from tail.

### Bringing all together (optional)
I believe, we could combine both operations.

```
node {
  calculator: "ConcatenateFloatVectorCalculator"
  input_stream: "wrist_pos"
  input_stream: "prev_wrist_pos_series"
  output_stream: "wrist_pos_series"
  options {
    [mediapipe.ConcatenateFloatVectorCalculator.ext] {
      max_vec_size: 10
      clip_mode: clip_tail
    }
  }
}
```

### Will this change current API?

In all cases it is possible to keep backward compatibility. But yes it will change API because it's about enhancing existing calculators.

**Who will benefit with this feature?**
Well, I think all of us might get more optimal graphs having such enhancement at hands.

**Please specify the use cases for this feature:**
For example I'm gathering some series, e.g. wrist position. Once I get *N* items I want to pass it through LSTM, so I drop everything which is older than *N* frames.

So I gather it by *concat* operation, and then I *clip* it. So graph runner have to invoke two separate nodes to get desired result. I suspect this is a common case two use combination of those two nodes, when you collect series. Combing them together allows to reduce amount of calculator calls.

Furthermore if we would know that we need to gather + clip it, we would use some sort of *circular array* instead of `std::vector`. That would be much faster.

**Comment by kaomoneus** [comment]
@hadon , ping. Shall I work on it?

**Comment by sgowroji** [comment]
Hi @kaomoneus,  Please follow [this](https://github.com/google/mediapipe/blob/master/CONTRIBUTING.md) guidelines and share the PR details.
