### ISSUE TITLE
Can't build Android Hello World example with bazel

### ISSUE THREAD

**Issue by ntaylorbishop** [google/mediapipe#2872]
[I'm using this guide.](https://google.github.io/mediapipe/getting_started/hello_world_android.html) This line is failing:  

`bazel build -c opt --config=android_arm64 $APPLICATION_PATH:helloworld`

With the following error:

`ERROR: Config value 'android_arm64' is not defined in any .rc file`

Nothing in the doc talks about running into this. Google searching is also failing me.

**Comment by sgowroji** [comment]
Hi @ntaylorbishop, Could you please check whether you defined this values in your code. https://github.com/google/mediapipe/blob/master/.bazelrc#:~:text=build%3Aandroid_arm64%20%2D%2Dconfig%3Dandroid,fat_apk_cpu%3Darm64%2Dv8a in [bazelrc](https://github.com/google/mediapipe/blob/master/.bazelrc) file
