### ISSUE TITLE
JS-Solutions-codepens wasn't working on most of android devices.

### ISSUE THREAD

**Issue by vKrypto** [google/mediapipe#2874]
### In-short:
hacked js-script, now working in all android, even older phones also. checkout updated **[codepen](https://codepen.io/vkrypto/pen/yLzJoEG)**.

### Problem:
as I found the main reason for not working in android devices, your asset_loader script was running twice. which caused some conflict and errors.

### Explaining Hack:
I need to make sure asset_loader doesn't run twice, that was quite tedious, so I changed their common function **locateFile** in a manner so that it avoids repetitive asset loading.

### Script Part:
I just replaced,

_const config = {locateFile: (file: string) => {
   return `https://cdn.jsdelivr.net/npm/@mediapipe/hands@${mpHands.VERSION}/${file}`;
}};_

With Following.

_let filesLoaded = []
const config = {locateFile: (file: string) => {
     if(!filesLoaded.includes(file)){return `https://cdn.jsdelivr.net/npm/@mediapipe/hands@${mpHands.VERSION}/${file}`};
}};_

### Extra things:
I heard a lot of people are facing the caching issue and other versioning issues.
so here is **totally offline** version of the same code-pen [download-here](https://www.ornaz.com/realtime-tryon-v9-zipped) or [live demo](https://www.ornaz.com/realtime-tryon-v9-offline-version/).

### optimization:
I have created a [realtime-tryon-for-rings](https://www.ornaz.com/realtime-tryon-v8/), using an old version of media pipe.

I have a few things in mind which can optimize Media pipe(a little bit), will update here soon.
Mediapipe's current version FPS, can be increased by a lot.

### Request:
hi Team, media pipe is growing super fast. a request to you guys. it will be so helpful if you upload a basic example of media pipe js solution build ( config.. etc.).. though I know the level of complexity, I am sure you guys will find a way.

**Comment by sgowroji** [comment]
Hi @vKrypto, Thank you so much for bringing the above error. Could you please provide the device details, So that we can try verifying them from our end.

**Comment by vKrypto** [comment]
> Hi @vKrypto, Thank you so much for bringing the above error. Could you please provide the device details, So that we can try verifying them from our end.
hi @sgowroji  I have tried in 3-4 android devices (e.g: Samsung F62), it's not working( actually it's a bit confusing sometimes(2/100) it works.)

Maybe it's a timing issue.

**Comment by vKrypto** [comment]
getting this error, 

`VM19 hands_solution_simd_wasm_bin.js:9 Uncaught (in promise) RuntimeError: abort(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)) at Error
    at jsStackTrace (VM19 hands_solution_simd_wasm_bin.js:9)
    at stackTrace (VM19 hands_solution_simd_wasm_bin.js:9)
    at abort (VM19 hands_solution_simd_wasm_bin.js:9)
    at Object.get (VM19 hands_solution_simd_wasm_bin.js:9)
    at VM19 hands_solution_simd_wasm_bin.js:9
    at pa.h (hands.js:57)
    at G (hands.js:14)
    at sa.next (hands.js:15)
    at hands.js:15
`


![Screenshot from 2021-12-10 13-07](https://user-images.githubusercontent.com/25729859/145535828-7ed6374a-d55b-46c5-ae68-3f21288fcb29.png)

**Comment by sgowroji** [comment]
Thanks for sharing the error log. I see there is already a [bug](https://github.com/google/mediapipe/issues/2823) is addressed which is having similar error logs and team is working on it.
