### ISSUE TITLE
Successfully build aar to introduce the project, but an error is reported when the project is running

### ISSUE THREAD

**Issue by tianhonglilei** [google/mediapipe#2875]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Redmi Note 8 pro
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
- Programming Language and version ( e.g. C++, Python, Java): Java
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.8
- Bazel version (if compiling from source): 4.1.0-homebrew
- Solution ( e.g. FaceMesh, Pose, Holistic ): 
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): AndroidSDK-29, NDK-r21e
- Xcode & Tulsi version (if issue is related to building for iOS):

**Describe the current behavior:**
Successfully build aar to introduce the project, but an error is reported when the project is running

**Describe the expected behavior:**
I don't know why it reports an error, hope to get your help, thank you

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached
[errorlog.txt](https://github.com/google/mediapipe/files/7684544/errorlog.txt)

**Comment by tianhonglilei** [comment]
I use the aar file built by others is ok

**Comment by sgowroji** [comment]
Hi @tianhonglilei, Could you please provide the steps used to reproduce the above error. Thanks!

**Comment by tianhonglilei** [comment]
@sgowroji I found the problem in the process of reproducing, one less file was copied in the assets, the problem was solved, thank you very much.
