### ISSUE TITLE
Mediapipe Pose w/ selfie segmentation - understanding Landmark coordinates and interacting with SegmentationMask, Connectors, etc.

### ISSUE THREAD

**Issue by AHMetaCubes** [google/mediapipe#2877]
Output: POSE_LANDMARKS 

- x and y: Landmark coordinates normalized to [0.0, 1.0] by the image width and height respectively.
- z: Represents the landmark depth with the depth at the midpoint of hips being the origin, and the smaller the value the closer the landmark is to the camera. The magnitude of z uses roughly the same scale as x.

Output: POSE_WORLD_LANDMARKS

- x, y and z: Real-world 3D coordinates in meters with the origin at the center between hips.

Question:

How would we map the normalized landmark values to to x, y, and z pixel coordinates on the DOM etc? 

How would we map the normalized world landmark values to to x, y, and z pixel coordinates on the DOM etc? 

Possible to get the "x, y and z: Real-world 3D coordinates in meters with the origin at the center between hips." without using/rendering the LandmarkGrid?

How to extract user body size/measurement data from the drawn connectors, segmentation mask, or distance between pose/focal points?

How to estimate the center of user body - chest?

Thank you for any help! Let me know if you need more detail.

**Comment by sgowroji** [comment]
Hi @AHRealift, Which platform are you referring the above. Thanks!

**Comment by AHRealift** [comment]
> Hi @AHRealift, Which platform are you referring the above. Thanks!

React, Javascript ... sorry for the late reply! Still appreciate any help or guidance. Thanks!

**Comment by AHRealift** [comment]
Status?  What is the difference between poseWorldLandmarks and poseLandmarks?

**Comment by fly2max** [comment]
> I have the same question and same the answer. I found the result to calculating angles using pose_landmarks and pose_world_landmarks are different.
