### ISSUE TITLE
Can we use mediapipe eye track detection for multiple persons?

### ISSUE THREAD

**Issue by PurushottamaRaoK** [google/mediapipe#2879]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using):
- Programming language : C++/typescript/Python/Objective C/Android Java
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state:**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Please specify the use cases for this feature:**

**Any Other info:**

**Comment by sgowroji** [comment]
HI @PurushottamaRaoK,  could you please provide your use case with the above feature request. Thanks!
