### ISSUE TITLE
"landmarks" attribute not being recognized in mediapipe

### ISSUE THREAD

**Issue by NevadaLarson** [google/mediapipe#2882]
-VSCode Windows 10
- [MediaPipe version] 0.8.9

import cv2 as cv
import mediapipe as mp
import time

cap = cv.VideoCapture(0)

mpHands = mp.solutions.hands
hands = mpHands.Hands()
mpDraw = mp.solutions.drawing_utils

cTime = 0
pTime = 0

while True:
    isTrue, frame = cap.read()
    frame = cv.flip(frame,1)
    frameRGB = cv.cvtColor(frame, cv.COLOR_BGR2RGB)
    results = hands.process(frameRGB)
    # print(results.multi_hand_landmarks)

    if results.multi_hand_landmarks:
        for handlms in results.multi_hand_landmarks:
            print(enumerate(handlms.landmarks))            #error here
            mpDraw.draw_landmarks(frame,handlms,mpHands.HAND_CONNECTIONS)
     
    cTime = time.time()
    fps = 1/(cTime - pTime)
    pTime = cTime

    if int(fps) < 30:
        cv.putText(frame,str(int(fps)), (10,70), cv.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2)
    else:
        cv.putText(frame,str(int(fps)), (50,70), cv.FONT_HERSHEY_SIMPLEX,1,(255,0,255),2)

    cv.imshow('Video', frame)

    if cv.waitKey(20) & 0xFF == ord('d'):
        break

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "d:\NEXUS\Hand Tracking\HandTrackingMin.py", line 23, in <module>
    print(enumerate(handlms.landmarks))
AttributeError: landmarks
[ WARN:0] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by sgowroji** [comment]
Hi @NevadaLarson , Could you please provide steps to reproduce the error with config details. Thanks!

**Comment by NevadaLarson** [comment]
I am an absolute beginner and the above solution does not make sense to me. Can you explain a little bit more?

**Comment by sgowroji** [comment]
Hi @NevadaLarson, Please check the documentation of Hands python code samples. Above code doesn't have any parameters as mentioned here https://google.github.io/mediapipe/solutions/hands.html#python-solution-api.

User the appropriate parameters as shown here 

```
mp_hands.Hands(
    static_image_mode=True,
    max_num_hands=2,
    min_detection_confidence=0.5) 
```

**Comment by NevadaLarson** [comment]
After days of frustration writing landmark instead of landmarks worked.

if results.multi_hand_landmarks:
    for handlms in results.multi_hand_landmarks:
        print(enumerate(handlms.landmarks))            #error here
        mpDraw.draw_landmarks(frame,handlms,mpHands.HAND_CONNECTIONS)
