### ISSUE TITLE
`@mediapipe/selfie_segmentation` npm package can be bundled by Rollup, but raises an error in runtime.

### ISSUE THREAD

**Issue by sile** [google/mediapipe#2883]
First of all, thank you for publishing this great library.
I'm new to this library and TypeScript, so not sure that this is actually a bug. 
Please let me know if you have any misunderstandings 🙏 

**System information** (Please provide as much relevant information as possible)

- Have I written custom code: Yes
- OS Platform and Distribution: mac OS Monterey 12.0.1
- Browser and version: Google Chrome 96.0.4664.93
- Programming Language and version: TypeScript v4.5.3
- [MediaPipe version](https://github.com/google/mediapipe/releases): [@mediapipe/selfie_segmentatoin-v0.1.1632777926](https://www.npmjs.com/package/@mediapipe/selfie_segmentation)
- Solution: Selfie Segmentation

**Describe the current behavior:**

Failed to instantiate the `SelfieSegmentation` class from a JavaScript file bundled by [Rollup](https://rollupjs.org/guide/en/).

The screenshot below shows the error message (please refer to the following `Standalone code to reproduce the issue` section about what is the context of `index.html`):
<img width="1047" alt="screenshot0" src="https://user-images.githubusercontent.com/181413/145775421-afbcac9c-b992-42e8-8664-71a1e90ceb1a.png">

**Describe the expected behavior:**

Be able to instantiate `SelfieSegmentatoin` class without errors (the `Hello World!` message below is emitted after the instantiation).
<img width="1047" alt="screenshot1" src="https://user-images.githubusercontent.com/181413/145775593-d526c291-7795-46cc-bd24-62e76dfbd86c.png">

**Standalone code to reproduce the issue:**

I created a small example package, that provides a class only instantiating `SelfieSegmentation`, to reproduce this issue.

```console
// Files.
$ ls
index.html index.ts package.json rollup.config.js

// Build this package.
$ npm install
$ npm run build

// Open `index.html` on a browser (Chrome in my case).
// The result has been shown at the first screenshot.
$ open index.html
```

`index.html`:
```html
<html>
  <head>
    <meta charset="utf-8">
    <title>Example</title>
  </head>
  <body>
    <script src="bundle.js"></script>
    <script>
      const selfie = new window.Example.SelfieSegmentationWrapper();
      console.log("Hello World!");
    </script>
  </body>
</html>
```

`index.ts`:
```typescript
import {SelfieSegmentation} from "@mediapipe/selfie_segmentation";

class SelfieSegmentationWrapper {
    private inner: SelfieSegmentation;

    constructor() {
        this.inner = new SelfieSegmentation({
            locateFile: (file: string) => {
                return `"https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/${file}`;
            },
        });
        this.inner.setOptions({
            modelSelection: 1,
        });
    }
}

export { SelfieSegmentationWrapper };
```

`package.json`:
```json
{
  "name": "example",
  "version": "0.0.0",
  "scripts": {
    "build": "rollup -c ./rollup.config.js"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^21.0.1",
    "@rollup/plugin-node-resolve": "^13.0.6",
    "@rollup/plugin-typescript": "^8.3.0",
    "rollup": "^2.61.1",
    "typescript": "^4.5.3"
  },
  "dependencies": {
    "@mediapipe/selfie_segmentation": "^0.1.1632777926"
  }
}
```

`rollup.config.js`:
```javascript
import typescript from '@rollup/plugin-typescript';
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';

export default {
    input: 'index.ts',
    plugins: [
        typescript(),
        commonjs(),
        resolve()
    ],
    output: {
        sourcemap: false,
        file: 'bundle.js',
        format: 'umd',
        name: 'Example',
    }
};
```

**Other info / Complete Logs :**

I don't exactly know why it works but if the line `exports.SelfieSegmentation = SelfieSegmentation;` is appended to `selfie_segmentation.js`, the problem is disappeared:

```console
$ echo 'exports.SelfieSegmentation = SelfieSegmentation;' >> node_modules/@mediapipe/selfie_segmentation/selfie_segmentation.js
$ npm run build

// Now, the "Hello World!" message is printed as shown in the second screenshot.
$ open index.html
```

**Comment by englishtom** [comment]
Just adding that I am experiencing the same issue with the @mediapipe/hands package. Using the package installed via npm works fine but if I compile it with Rollup then I am given `TypeError: JT.Hands is not a constructor`.

You can see the same issue with the CDN version of the package using this standalone script:

`
<html>

<head>

    <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/hand-pose-detection"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/hands"></script>

</head>

<body>

    <img id="myImg" src="https://victordibia.com/handtrack.js/images/samples/0.jpg"/>

    <script>
        const img = document.getElementById('myImg');
        const model = handPoseDetection.SupportedModels.MediaPipeHands;
        const detectorConfig = {
            runtime: 'mediapipe',
            modelType: 'full',
            solutionPath: 'https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.4.1635986972',
        };

        const detector = handPoseDetection.createDetector(model, detectorConfig).then(() => {
            console.log('Ready to detect', detector);

            detector.estimateHands(img).then((hands) => {
                console.log('Got results!', hands);  
            });
        });

    </script>
</body>

</html>
`

**Comment by englishtom** [comment]
@tyrmullen It does not, however, using the Hands library directly without TensorFlow works well for me so that is the approach I have moved forwards with.

**Comment by utileetdulce** [comment]
This might help to understand the issue:

>Rollup CommonJS plugin can't work with obfuscated packages because it relies on static analysis to determine its exports.

- https://github.com/vitejs/vite/issues/4680#issuecomment-903244405

**Comment by holtwick** [comment]
By @bluwy :

> Note: The core issue of @mediapipe/selfie_segmentation is that exports a non-ESM file in pkg.module, which should be ESM. I'd suggest contacting the package author to fix it, but for now I've documented the difference of dependencies handled in dev and build that might help in debugging the issue. https://github.com/vitejs/vite/issues/4680#issuecomment-1059917240

Does someone have a workaround for this issue?

**Comment by sile** [comment]
Just FYI, I implemented a custom rollup plugin that appends the line `exports.SelfieSegmentation = SelfieSegmentation;` to the selfie_segmentation.js during the bundle phase as our workaround: https://github.com/shiguredo/media-processors/blob/develop/packages/virtual-background/rollup.config.js#L73

**Comment by holtwick** [comment]
> Just FYI, I implemented a custom rollup plugin that appends the line `exports.SelfieSegmentation = SelfieSegmentation;` to the selfie_segmentation.js during the bundle phase as our workaround: https://github.com/shiguredo/media-processors/blob/develop/packages/virtual-background/rollup.config.js#L73

Awesome, thanks so much. This works for me! 

I use this plugin now in my `vite.config.ts` under `build.rollupOptions.plugins`.

**Comment by mattrossman** [comment]
> Just FYI, I implemented a custom rollup plugin that appends the line exports.SelfieSegmentation = SelfieSegmentation; to the selfie_segmentation.js during the bundle phase as our workaround: https://github.com/shiguredo/media-processors/blob/develop/packages/virtual-background/rollup.config.js#L73

Thanks for sharing. In my case the error was related to MediaPipe Facemesh, so I adjusted the plugin as follows:

```js
function mediapipe_workaround() {
  return {
    name: "mediapipe_workaround",
    load(id) {
      if (path.basename(id) === "face_mesh.js") {
        let code = fs.readFileSync(id, "utf-8")
        code += "exports.FaceMesh = FaceMesh;"
        return { code }
      } else {
        return null
      }
    },
  }
}

```

**Comment by kuaashish** [comment]
Hello @sile,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by sile** [comment]
@kuaashish Thank you for letting me know about the new solutions. I tried using the [Image Segmenter](https://developers.google.com/mediapipe/solutions/vision/image_segmenter/web_js) (with label=person) for selfie segmentation purposes. However, I decided to continue using the legacy selfie segmentation package as the segmentation mask generated by the Image Segmenter seemed too rough (and it took longer wall clock time to process each frame).
I will consider switching to the new solutions once an alternative for the legacy selfie segmentation becomes available.

**Comment by kuaashish** [comment]
@sile,
Thank you checking out our new solutions. Others legacy solutions source code will be available in the Github if you choose.
Further, We need your confirmation to move issue to close if this is no longer issue from your end.

**Comment by sile** [comment]
@kuaashish I see. It's okay to close this issue 👍

**Comment by Spencer17x** [comment]
Maybe you can use vite-plugin-mediapipe：https://github.com/Spencer17x/arca/tree/main/packages/vite-plugin/vite-plugin-mediapipe

**Comment by Bersaelor** [comment]
> > Just FYI, I implemented a custom rollup plugin that appends the line exports.SelfieSegmentation = SelfieSegmentation; to the selfie_segmentation.js during the bundle phase as our workaround: https://github.com/shiguredo/media-processors/blob/develop/packages/virtual-background/rollup.config.js#L73
> 
> Thanks for sharing. In my case the error was related to MediaPipe Facemesh, so I adjusted the plugin as follows:
> 
> ```js
> function mediapipe_workaround() {
>   return {
>     name: "mediapipe_workaround",
>     load(id) {
>       if (path.basename(id) === "face_mesh.js") {
>         let code = fs.readFileSync(id, "utf-8")
>         code += "exports.FaceMesh = FaceMesh;"
>         return { code }
>       } else {
>         return null
>       }
>     },
>   }
> }
> ```

Hey @mattrossman , I'm encountering the exact same issue, trying to bundle mediapipe/facemesh into a vite built application ( also `Ik.FaceMesh is not a constructor` )

The link you quoted doesn't go anywhere anymore, do you happen to still have a full vite plugin that the method you wrote goes into?

**Comment by mattrossman** [comment]
@Bersaelor That `mediapipe_workaround` method in the quoted message is the full vite plugin, you call it within the vite `plugins` config.

For posterity, here's a [permalink to the original](https://github.com/shiguredo/media-processors/blob/07e54bf7114bc1bbe71bbbd43128c07f3221cf97/packages/virtual-background/rollup.config.mjs#L72-L86
) by @sile that I based it on (it looks like they just renamed the file extension which broke that other link). And [here's where it's used in the config](https://github.com/shiguredo/media-processors/blob/07e54bf7114bc1bbe71bbbd43128c07f3221cf97/packages/virtual-background/rollup.config.mjs#L25).
