### ISSUE TITLE
Does not build with Python 3.10

### ISSUE THREAD

**Issue by buzo-ffm** [google/mediapipe#2884]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Arch Linux
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): GCC 10
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.10
- Installed using virtualenv? pip? Conda? (if python): no, native Arch packages
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.8.r4.gcf101e62
- Bazel version: 4.2.2
- OpenCV version (if running on desktop): 4.5.4

**Describe the problem**:
The AUR package [python-mediapipe-git](https://aur.archlinux.org/packages/python-mediapipe-git/) does not build any more since Arch Linux switched to Python 3.10.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
`CC=gcc-10 CXX=g++-10 python setup.py build --link-opencv`
See [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-mediapipe-git) for the complete build script.

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:
[python-mediapipe-git-v0.8.8.r4.gcf101e62-1-x86_64-build.log](https://github.com/google/mediapipe/files/7703224/python-mediapipe-git-v0.8.8.r4.gcf101e62-1-x86_64-build.log)

**Comment by sgowroji** [comment]
Hi @buzo-ffm, Python 3.10 is not supported by MediaPipe yet. Please use Python 3.7 to 3.9. Thanks!

**Comment by buzo-ffm** [comment]
Thanks @sgowroji. Do you have any idea when 3.10 would be supported?

**Comment by jiuqiant** [comment]
Thanks for reporting this. Python 3.10 is now supported in https://github.com/google/mediapipe/releases/tag/v0.8.9.
