### ISSUE TITLE
Error on XCODE build 

### ISSUE THREAD

**Issue by muhammadabdullah34907** [google/mediapipe#2887]
xcode=13.1
bazelisk bazel version=4.2.2

Users/macbookair/Documents/aman/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:54:13: C++ compilation of rule '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuAppLibrary' failed (Exit 1): wrapped_clang failed: error executing command

**Comment by sgowroji** [comment]
Hi @muhammadabdullah34907, Could you please provide the steps and commands used to reproduce the above error. Thanks!

**Comment by muhammadabdullah34907** [comment]
@sgowroji thank you so much for the very quick response. 

So basically after tulsi app generates the xcode project for mediapipe, then I just changed the build system from legacy to new build system. Then added the account in signing capabilities and then selected the handstracking app. Then I have click on build  button to generate the build. 

![Screenshot 2021-12-15 at 12 18 44 PM](https://user-images.githubusercontent.com/55294154/146141058-b547d559-a4b5-49e9-bdfc-ec913886ab68.png)

**Comment by muhammadabdullah34907** [comment]
@sgowroji I am using bazelisk with bazel version 4.2.2, is there any issue of bazel version with this app ?

**Comment by sgowroji** [comment]
If you are trying to build IOS framework then refer https://github.com/google/mediapipe/issues/1549.  And also this w.r.t to the logs shared in the above comment https://github.com/google/mediapipe/issues/537. If that doesn't resolve your error. Please send us the complete logs to understand the issue to investigate further.

**Comment by muhammadabdullah34907** [comment]
@sgowroji actually helloworld app works fine and build succeed but hand tracking app and pose estimation apps are giving this error and this is whole logs I am getting.
![image](https://user-images.githubusercontent.com/55294154/146164914-da6cd99f-161e-436f-9480-269269580edd.png)

**Comment by muhammadabdullah34907** [comment]
@sgowroji I have also tried the above-shared resources you shared but had no success. I don't know if it's bazel issue.

**Comment by muhammadabdullah34907** [comment]
@sgowroji thank you, I was able to fix that error but now it's a new error. Please check the below screenshot for complete logs.


Showing All Messages
/Users/macbookair/Documents/aman/mediapipe/external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:185:16: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on iOS 11 or newer

![Screenshot 2021-12-16 at 2 19 19 AM](https://user-images.githubusercontent.com/55294154/146266538-59e9d444-ae2b-4e70-a997-418449a35ba9.png)

**Comment by willbetheone** [comment]
I have the same problem 。Did you resolve it？ @muhammadabdullah34907

/Users/macbookair/Documents/aman/mediapipe/external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:185:16: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on iOS 11 or newer

**Comment by coldfish0726** [comment]
I solved this same issue by https://github.com/google/mediapipe/issues/3054#issuecomment-1031094864

> I have the same problem 。Did you resolve it？ @muhammadabdullah34907
> 
> /Users/macbookair/Documents/aman/mediapipe/external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:185:16: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on iOS 11 or newer

**Comment by kuaashish** [comment]
Hello @muhammadabdullah34907,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
