### ISSUE TITLE
mediapipe bazel android bug libprotobuf_javalite.jar target value 1.7. Use 1.8 or later

### ISSUE THREAD

**Issue by wxq1770** [google/mediapipe#2888]
openjdk version "1.8.0_292" OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10) OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode) bazel 3.7.2

Python 3.7.4 opencv-3.4.3 android-ndk-r19c

bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:facedetectiongpu

warning: -parameters is not supported for target value 1.7. Use 1.8 or later.

ERROR: /private/var/tmp/_bazel_qingzai/3fb4ffc2a9009e01bb6f98ddec9d6dae/external/com_google_protobuf/BUILD:679:13: Desugaring external/com_google_protobuf/libprotobuf_javalite.jar for Android failed: Worker process did not return a WorkResponse:

ERROR: /private/var/tmp/_bazel_qingzai/3fb4ffc2a9009e01bb6f98ddec9d6dae/external/maven/BUILD:981:11: Desugaring maven/v1/https/maven.aliyun.com/repository/central/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar for Android failed: Worker process did not return a WorkResponse:

ERROR: /Users/qingzai/Downloads/mediapipe/mediapipe/java/com/google/mediapipe/framework/BUILD:127:16: Desugaring mediapipe/java/com/google/mediapipe/framework/libmediapipe_exception_android.jar for Android failed: Worker process did not return a WorkResponse:

ERROR: /private/var/tmp/_bazel_qingzai/3fb4ffc2a9009e01bb6f98ddec9d6dae/external/maven/BUILD:890:11: Desugaring maven/v1/https/maven.aliyun.com/repository/central/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar for Android failed: Worker process did not return a WorkResponse:

ERROR: /private/var/tmp/_bazel_qingzai/3fb4ffc2a9009e01bb6f98ddec9d6dae/external/com_google_protobuf/BUILD:679:13: Desugaring external/com_google_protobuf/libprotobuf_javalite.jar for Android failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /private/var/tmp/_bazel_qingzai/3fb4ffc2a9009e01bb6f98ddec9d6dae/bazel-workers/worker-66-Desugar.log ---8<---8<--- Unknown option: 1 Usage: head [-options] ... -m use method for the request (default is 'HEAD') -f make request even if head believes method is illegal -b Use the specified URL as base -t Set timeout value -i Set the If-Modified-Since header on the request -c use this content-type for POST, PUT, CHECKIN -a Use text mode for content I/O -p use this as a proxy -P don't load proxy settings from environment -H send this HTTP header (you can specify several)

-u            Display method and URL before any response
-U            Display request headers (implies -u)
-s            Display response status code
-S            Display response status chain
-e            Display response headers
-d            Do not display content
-o <format>   Process HTML content in various ways

-v            Show program version
-h            Print this message

-x            Extra debugging output
---8<---8<--- End of log ---8<---8<--- Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:facedetectiongpu failed to build Use --verbose_failures to see the command lines of failed build steps.

**Comment by sgowroji** [comment]
Hi @wxq1770, Are you building the above with docker ? try upgrading your open jdk and verify the above commands. Seems duplicate of https://github.com/google/mediapipe/issues/1628

**Comment by wxq1770** [comment]
not docker running
run failed

openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)

bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:facedetectiongpu


> Hi @wxq1770, Are you building the above with docker ? try upgrading your open jdk and verify the above commands. Seems duplicate of #1628

**Comment by kuaashish** [comment]
Hello @wxq1770,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
