### ISSUE TITLE
Switch ios posetrackinggpu to selfie camera

### ISSUE THREAD

**Issue by likwifi** [google/mediapipe#2889]
Hello,

I'm trying to switch the camera to selfie for posetrackinggpu module for IOS,
appreciate it if you can help with that.

**Comment by sgowroji** [comment]
Hi @likwifi, You can change it to front in back here https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/examples/ios/posetrackinggpu/Info.plist#:~:text=%3Ckey%3ECameraPosition%3C/key,string%3Eback%3C/string%3E from info.plist file. 

` <key>CameraPosition</key>
  <string>front</string>`

**Comment by likwifi** [comment]
Perfect thank you,
and it's not related to this thread but I'm just trying to pass those coordinates stream to unity character, would it be possible not to render anything and just output landmarks.
Also, appreciate if you comment whenever typical IOS device will handle this kind of workload.
I'm not familiar with Objective C so pardon me if questions sound naive.

**Comment by sgowroji** [comment]
I have not tried anything such yet on unity. But i can point you to https://github.com/homuler/MediaPipeUnityPlugin here some of the community members use on unity.

**Comment by sgowroji** [comment]
Closing this issue as the above query is answered!
