### ISSUE TITLE
How to use Effect Renderer in Mediapipe with Android Archive?

### ISSUE THREAD

**Issue by vicaloy** [google/mediapipe#2890]
Hi,

I want to place a texture in face mesh with face detection aar in android, but I don't know how to do it, please help.

I understood that is possible, the documentation say:

EFFECT RENDERER
The Effect Renderer is a component, which serves as a working example of a face effect renderer. It targets the OpenGL ES 2.0 API to enable a real-time performance on mobile devices and supports the following rendering modes:

3D object rendering mode: a virtual object is aligned with a detected face to emulate an object attached to the face (example: glasses);
Face mesh rendering mode: a texture is stretched on top of the face mesh surface to emulate a face painting technique.
In both rendering modes, the face mesh is first rendered as an occluder straight into the depth buffer. This step helps to create a more believable effect via hiding invisible elements behind the face surface.

Thanks in advance!

**Comment by sgowroji** [comment]
Hi @vicaloy, Please refer this issues to understand the implementation https://github.com/google/mediapipe/issues/1155, https://github.com/google/mediapipe/issues/1789 please reach us if you have any specific query with respect to the above context. You can find the [Android code ](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect/MainActivity.java)for face effect Thanks!
