### ISSUE TITLE
mediapipe pose support with coral tpu

### ISSUE THREAD

**Issue by sohail759** [google/mediapipe#2891]
<em>I m looking for human body pose estimation with google coral tpu.</em>

- MediaPipe Solution (Bosy Pose):
- Programming language : Python
- Are you willing to contribute it (Yes):

Currently, the media pipe pose estimation is not accelerated with coral edge tpus, so its a request to please add support for human pose estimation with tpus.

**Comment by sgowroji** [comment]
MediaPipe has limited resources for new features.  While this is a good idea, we don't foresee any debo area.
