### ISSUE TITLE
Face landmark key points index

### ISSUE THREAD

**Issue by tri-bao** [google/mediapipe#2892]
Hello, this is quite a very basic question. I tried to search throughout issue list of this repository but couldn't find one. Please advice.

Is the order of key points in `NormalizedLandmarkList` returned by the Iris tracking of mediapipe same as the tensorflowJS FaceMesh solution? I mean I am looking for the same definition as this typescript [https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection/src/mediapipe-facemesh/keypoints.ts](https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection/src/mediapipe-facemesh/keypoints.ts).

For example, according to tensorflowJS FaceMesh, the index 1 is a nose tip point. So if I do the following, I will get the same point.
```
LandmarkProto.NormalizedLandmarkList landmarks = LandmarkProto.NormalizedLandmarkList.parseFrom(landmarksRaw);
NormalizedLandmark noseTip = landmarks.getLandmarkList().get(1);
```

There is [FaceMeshConnections.java](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/solutions/facemesh/FaceMeshConnections.java) in the facemesh android solution, but it seems to me that the file defines connection lines

Thanks.

**Comment by sgowroji** [comment]
Hi @tri-bao, You can find the coordinates here for facemesh https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png

**Comment by tri-bao** [comment]
thanks @sgowroji

**Comment by wwdok** [comment]
> Hi @tri-bao, You can find the coordinates here for facemesh https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png

@sgowroji But this image does not have the 10 iris vertex indices, where can find these 10 iris vertex indices ?

**Comment by kholdarbekov** [comment]
The facial landmarks indexes seems to be outdated in this [pic](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png)

Where can I find up-to-date mapping landmarks to indexes?
PS: [there is one](https://developers.google.com/mediapipe/solutions/vision/face_landmarker) but it's not clear

**Comment by Intiserahmed** [comment]
https://storage.googleapis.com/mediapipe-assets/documentation/mediapipe_face_landmark_fullsize.png

you can find here
