### ISSUE TITLE
Using mediapipe hand solution to create hand landmark dataset

### ISSUE THREAD

**Issue by anathema43** [google/mediapipe#2893]
Hi, 
I am using mediapipe handsolution to create handlandmark dataset and I encountered some basic problem. while extracting hand landmark i encountered some valuses as None(for eg- if wrist is not visible then the wrist landmark is none) . So i am confused what valuw should I put in the label vector for that landamrk should i put zero (but (0,0) is also a location ) wont it affect the model?
should i put np.nan, is it possible? and how will a model learn to ignore those values?

Thank you for your effort
![none](https://user-images.githubusercontent.com/37859650/146330326-6907c655-52b5-4c24-a024-1ca87ecc8a10.png)
![none1](https://user-images.githubusercontent.com/37859650/146330714-218a889f-d2aa-42dc-aaf3-8eb774d89dee.png)

**Comment by sgowroji** [comment]
Hi @anathema43, Could you please provide steps to reproduce the above behaviour. Thanks!
