### ISSUE TITLE
When will the iris API for Python release？

### ISSUE THREAD

**Issue by TommyZihao** [google/mediapipe#2895]

**Comment by TommyZihao** [comment]
I think iris is just like face detection and face mesh, easy to develop it for Python, isn't it?

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2605#issuecomment-938049615. You can achieve this with facemesh in python by setting refine_landmarks to True.

**Comment by TommyZihao** [comment]
> Duplicate [#2605 (comment)](https://github.com/google/mediapipe/issues/2605#issuecomment-938049615). You can achieve this with facemesh in python by setting refine_landmarks to True.

How can I get iris distance from camera through face mesh attention model, I think it's not available in face mesh API.

**Comment by jiuqiant** [comment]
Unfortunately, FashMesh doesn't provide the iris distance data. It only has the iris landmarks. 

We currently do have a plan to make a separate iris solution.

**Comment by TommyZihao** [comment]
> Unfortunately, FashMesh doesn't provide the iris distance data. It only has the iris landmarks.
> 
> We currently do have a plan to make a separate iris solution.

Please make it as soon as possible, this is my video tutorial about face mesh
https://www.bilibili.com/video/BV1ei4y1d7zA?
I want to make one for iris, too.
