### ISSUE TITLE
Python Implementation for Object Detection

### ISSUE THREAD

**Issue by AsRaNi1** [google/mediapipe#2897]
The python implementation of object detection can be achieved by using the DNN module of cv2 and the YOLO weights. It would be great to have that here. I have the code ready, may I generate a pull request for validation?
![My Post](https://user-images.githubusercontent.com/84843295/146437754-20e4be72-2ffa-4b03-b06d-7c8112d991fe.png)

**Comment by sgowroji** [comment]
Hi @AsRaNi1, Please raise a  PR  and follow the instructions mentioned in the contributing guide. Thanks!
