### ISSUE TITLE
why support golang?

### ISSUE THREAD

**Issue by EddieChan1993** [google/mediapipe#2898]
Hope to provide support for golang

**Comment by sgowroji** [comment]
Hi @EddieChan1993, Could you please elaborate your use case with respect to the above feature request. Thanks!

**Comment by EddieChan1993** [comment]
> Hi @EddieChan1993, Could you please elaborate your use case with respect to the above feature request. Thanks!

Because go is a popular development language at present, if mediapipe supports golang language, mediapipe will be more popular and more developers can use mediapipe.

**Comment by sgowroji** [comment]
Hi @EddieChan1993, Absolutely you can start initiating one as [solutions](https://google.github.io/mediapipe/getting_started/getting_started.html) mentioned in our platforms. We do have similar platform community like [unity](https://github.com/homuler/MediaPipeUnityPlugin), react and [others](https://github.com/mgyong/awesome-mediapipe)

**Comment by EddieChan1993** [comment]
3ks

**Comment by asoseil** [comment]
any update about this?

**Comment by igoracmelo** [comment]
If it exposes C/C++ functions, you can interoperate using cgo.
So I don't believe official support is necessary...
