### ISSUE TITLE
Different output when build with opt and dbg for boxtracker

### ISSUE THREAD

**Issue by laosanlyu** [google/mediapipe#2899]
build for the same graph with opt and dbg option but get different output. 
build with opt:
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/object_tracking:object_tracking_cpu `
build with dbg:
`bazel build -c dbg --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/object_tracking:object_tracking_cpu`

run the compiled binary for the same video:
`bazel-bin/mediapipe/examples/desktop/object_tracking/object_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/tracking/object_detection_tracking_desktop_live.pbtxt --input_video_path=/media/data/palm_detection/test_videos/IMG_2430_3.MOV `

visualization:
1. build with dbg:
![compile_with_dbg](https://user-images.githubusercontent.com/85405539/146480039-c6340089-0116-477f-85d6-5bd306cd1c36.png)
2.  build with opt:
![compile_with_opt](https://user-images.githubusercontent.com/85405539/146480090-1a78fb54-0a87-40cd-8b72-23bee41aaea3.png)

**Comment by sgowroji** [comment]
Hi @laosanlyu, Could you please share the video to test the above scenario and let us know if there are any code changes w.r.t the above. Thanks!

**Comment by laosanlyu** [comment]
> Hi @laosanlyu, Could you please share the video to test the above scenario and let us know if there are any code changes w.r.t the above. Thanks!
Sorry, the video file is too big to upload, there is no code changes. any videos will get similar result

**Comment by laosanlyu** [comment]
closed by mistake

**Comment by kuaashish** [comment]
Hello @laosanlyu,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
