### ISSUE TITLE
Youtube Extracting Features Step 5 Bazel build failed

### ISSUE THREAD

**Issue by Cagriyoruk** [google/mediapipe#290]
Hi, 
I'm trying to create my own dataset files for Youtube8M. So I'm using Mediapipes feature extraction method to extract both rgb and audio. But even though I install necessary libraries like OpenCV, FFmpeg, Tensorflow... I encounter an issue at step 5. My OS is Centos. I'm using a Shared Computing Cluster.  The versions of the modules I'm using are:

  1) python3/3.6.9   2) cuda/10.0       3) opencv/4.0.1    4) ffmpeg/4.2.1    5) bazel/0.25.0    6) gcc/5.5.0

I also tried different versions of gcc. Because I was having issues with the raw version of the code. I modified a little bit. Here is the modified version of the code:

CC=`which gcc` CXX=`which g++` bazel build -c opt   --define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true  mediapipe/examples/desktop/youtube8m:extract_yt8m_features  

My error log is:

ERROR: /projectnb/ece601/youtube-challenge/data/yt8m/mediapipe/mediapipe/examples/desktop/youtube8m/BUILD:17:1: Linking of rule '//mediapipe/examples/desktop/youtube8m:extract_yt8m_features' failed (Exit 1) gcc failed: error executing command /share/pkg.7/gcc/5.5.0/install/bin/gcc -o bazel-out/k8-opt/bin/mediapipe/examples/desktop/youtube8m/extract_yt8m_features ... (remaining 15 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-opt/bin/mediapipe/calculators/tensorflow/_objs/pack_media_sequence_calculator/pack_media_sequence_calculator.o:pack_media_sequence_calculator.cc:function mediapipe::PackMediaSequenceCalculator::Process(mediapipe::CalculatorContext*): error: undefined reference to 'cv::imencode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
bazel-out/k8-opt/bin/mediapipe/util/sequence/_objs/media_sequence/media_sequence.o:media_sequence.cc:function mediapipe::mediasequence::(anonymous namespace)::ReconcileMetadataImages(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tensorflow::SequenceExample*) [clone .constprop.286]: error: undefined reference to 'cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
bazel-out/k8-opt/bin/mediapipe/calculators/video/_objs/opencv_video_decoder_calculator/opencv_video_decoder_calculator.o:opencv_video_decoder_calculator.cc:function mediapipe::OpenCvVideoDecoderCalculator::Open(mediapipe::CalculatorContext*): error: undefined reference to 'cv::VideoCapture::VideoCapture(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/youtube8m:extract_yt8m_features failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 998.778s, Critical Path: 392.56s
INFO: 2626 processes: 1 local, 2625 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

Thank you.

**Comment by jiuqiant** [comment]
The error is

**Comment by jiuqiant** [comment]
The error is undefined reference to 'cv::VideoCapture::VideoCapture', which means MediaPipe can't find your OpenCV libraries. This is [a similar issue](https://github.com/google/mediapipe/issues/224) for your reference. Please find your OpenCV's header files and libraries, and then follow the option 2 of the step 3 in [the instruction](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-centos)  to modify WORKSPACE and opencv_linux.BUILD.

**Comment by Cagriyoruk** [comment]
I actually modified the files before I post the error. I modified WORKSPACE, opencv_linux.BUILD and ffmpeg_linux.BUILD. Before I modified those files, the build wasn't running at all. It was giving an error instantly. Are there other lines that I need to modify other than specified ones? So I modified those files as the WORKSPACE:

new_local_repository(
    name = "linux_opencv",
    build_file = "@//third_party:opencv_linux.BUILD",
    path = "/share/pkg.7/opencv/4.0.1/install"
)

new_local_repository(
    name = "linux_ffmpeg",
    build_file = "@//third_party:ffmpeg_linux.BUILD",
    path = "/share/pkg.7/ffmpeg/4.2.1/install"
)
///////////////////////////////////////////////////////////////////////////////////////////////
And the opencv_linux.BUILD:
# Description:
#   OpenCV libraries for video/image processing on Linux

licenses(["notice"])  # BSD license

exports_files(["LICENSE"])

# The following build rule assumes that OpenCV is installed by
# 'apt-get install libopencv-core-dev libopencv-highgui-dev \'
# '                libopencv-imgproc-dev libopencv-video-dev' on Debian/Ubuntu.
# If you install OpenCV separately, please modify the build rule accordingly.
cc_library(
    name = "opencv",
    srcs = glob(
        [
            "lib64/libopencv_core.so",
            "lib64/libopencv_calib3d.so",
            "lib64/libopencv_features2d.so",
            "lib64/libopencv_highgui.so",
            "lib64/libopencv_imgcodecs.so",
            "lib64/libopencv_imgproc.so",
            "lib64/libopencv_video.so",
            "lib64/libopencv_videoio.so",
        ],
    ),
    hdrs = glob(["include/opencv4/opencv2/**/*.h*"]),
    includes = ["include/opencv4"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)

Thanks

**Comment by jiuqiant** [comment]
Can you change the hdrs field of the opencv cc_library to be `hdrs = glob(["include/opencv4/**/*.h*"]),` or `hdrs = glob(["include/opencv4/opencv2/**/*.h*"]),`?
I guess the regex of the current hdrs field probably don't match anything.

**Comment by Cagriyoruk** [comment]
It didn't change anything. Still having the same error.

**Comment by jiuqiant** [comment]
Can you verify that the header files are in `/share/pkg.7/opencv/4.0.1/install/include/opencv4/opencv2` and the libraries are in `/share/pkg.7/opencv/4.0.1/install/lib64/`?

**Comment by Cagriyoruk** [comment]
I checked both of them. It looks like they have the files. 

<img width="1128" alt="2019-12-04 (3)" src="https://user-images.githubusercontent.com/55101879/70187677-d3206600-16bc-11ea-8e4d-f38d23bc12bb.png">

<img width="1128" alt="2019-12-04 (2)" src="https://user-images.githubusercontent.com/55101879/70187700-de739180-16bc-11ea-9729-2c977423d5f8.png">

**Comment by jiuqiant** [comment]
OK, let try the following

```
cc_library(
    name = "opencv",
    srcs = glob([
        "lib64/libopencv_core.so",
        "lib64/libopencv_calib3d.so",
        "lib64/libopencv_features2d.so",
        "lib64/libopencv_highgui.so",
        "lib64/libopencv_imgcodecs.so",
        "lib64/libopencv_imgproc.so",
        "lib64/libopencv_video.so",
        "lib64/libopencv_videoio.so",]),
    hdrs = glob(["include/opencv4/**/*.h*"]),
    includes = ["include/opencv4/"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
```

We had [a similar setting](https://github.com/google/mediapipe/blob/v0.5.0/third_party/opencv_macos.BUILD) for macos in v0.5 with opencv 4.0.1.

**Comment by Cagriyoruk** [comment]
<img width="1128" alt="2019-12-04 (6)" src="https://user-images.githubusercontent.com/55101879/70196000-4cc44e00-16d5-11ea-860b-2a198570bd27.png">

I just cleaned the cache and tried again with the calculator test. Still the same result. Am I missing something on the WORKSPACE? It goes until the very end, then produce the result. 

<img width="1128" alt="2019-12-04 (8)" src="https://user-images.githubusercontent.com/55101879/70196992-6c10aa80-16d8-11ea-87f1-76b98927c6d8.png">

**Comment by jiuqiant** [comment]
I started a fresh CentOS instance on google cloud and installed OpenCV 3.3 by following [this instruction](https://www.vultr.com/docs/how-to-install-opencv-on-centos-7). 

OpenCV3 is installed in /usr/local.
```
[jqtang@centos ~]$ ls /usr/local/include/opencv2
calib3d      dnn.hpp         highgui.hpp    ml.hpp              photo.hpp      superres.hpp  videostab.hpp
calib3d.hpp  features2d      imgcodecs      objdetect           shape          video
core         features2d.hpp  imgcodecs.hpp  objdetect.hpp       shape.hpp      video.hpp
core.hpp     flann           imgproc        opencv.hpp          stitching      videoio
cvconfig.h   flann.hpp       imgproc.hpp    opencv_modules.hpp  stitching.hpp  videoio.hpp
dnn          highgui         ml             photo               superres       videostab

[jqtang@centos ~]$  ls /usr/local/lib/
libopencv_calib3d.so           libopencv_imgcodecs.so        libopencv_stitching.so
libopencv_calib3d.so.3.3       libopencv_imgcodecs.so.3.3    libopencv_stitching.so.3.3
libopencv_calib3d.so.3.3.0     libopencv_imgcodecs.so.3.3.0  libopencv_stitching.so.3.3.0
libopencv_core.so              libopencv_imgproc.so          libopencv_superres.so
libopencv_core.so.3.3          libopencv_imgproc.so.3.3      libopencv_superres.so.3.3
libopencv_core.so.3.3.0        libopencv_imgproc.so.3.3.0    libopencv_superres.so.3.3.0
libopencv_dnn.so               libopencv_ml.so               libopencv_videoio.so
libopencv_dnn.so.3.3           libopencv_ml.so.3.3           libopencv_videoio.so.3.3
libopencv_dnn.so.3.3.0         libopencv_ml.so.3.3.0         libopencv_videoio.so.3.3.0
libopencv_features2d.so        libopencv_objdetect.so        libopencv_video.so
libopencv_features2d.so.3.3    libopencv_objdetect.so.3.3    libopencv_video.so.3.3
libopencv_features2d.so.3.3.0  libopencv_objdetect.so.3.3.0  libopencv_video.so.3.3.0
libopencv_flann.so             libopencv_photo.so            libopencv_videostab.so
libopencv_flann.so.3.3         libopencv_photo.so.3.3        libopencv_videostab.so.3.3
libopencv_flann.so.3.3.0       libopencv_photo.so.3.3.0      libopencv_videostab.so.3.3.0
libopencv_highgui.so           libopencv_shape.so            pkgconfig
libopencv_highgui.so.3.3       libopencv_shape.so.3.3        python2.7
libopencv_highgui.so.3.3.0     libopencv_shape.so.3.3.0

``` 

And then I edited the WORKSPACE file and opencv_linux.BUILD like the following:
```
diff --git a/WORKSPACE b/WORKSPACE
index c09ca03..80d2e3d 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -129,7 +129,7 @@ tf_workspace(tf_repo_name = "org_tensorflow")
 new_local_repository(
     name = "linux_opencv",
     build_file = "@//third_party:opencv_linux.BUILD",
-    path = "/usr",
+    path = "/usr/local",
 )

diff --git a/third_party/opencv_linux.BUILD b/third_party/opencv_linux.BUILD
index ef2aeb4..a4f8726 100644
--- a/third_party/opencv_linux.BUILD
+++ b/third_party/opencv_linux.BUILD
@@ -13,14 +13,14 @@ cc_library(
     name = "opencv",
     srcs = glob(
         [
-            "lib/x86_64-linux-gnu/libopencv_core.so",
-            "lib/x86_64-linux-gnu/libopencv_calib3d.so",
-            "lib/x86_64-linux-gnu/libopencv_features2d.so",
-            "lib/x86_64-linux-gnu/libopencv_highgui.so",
-            "lib/x86_64-linux-gnu/libopencv_imgcodecs.so",
-            "lib/x86_64-linux-gnu/libopencv_imgproc.so",
-            "lib/x86_64-linux-gnu/libopencv_video.so",
-            "lib/x86_64-linux-gnu/libopencv_videoio.so",
+            "lib/libopencv_core.so*",
+            "lib/libopencv_calib3d.so*",
+            "lib/libopencv_features2d.so*",
+            "lib/libopencv_highgui.so*",
+            "lib/libopencv_imgcodecs.so*",
+            "lib/libopencv_imgproc.so*",
+            "lib/libopencv_video.so*",
+            "lib/libopencv_videoio.so*",
         ],
     ),
     hdrs = glob(["include/opencv2/**/*.h*"]),
```
Finally, I can run our image_frame_opencv_test, which means OpenCV is working with MediaPipe.
```
[jqtang@centos mediapipe]$ bazel run -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/framewor
k/formats:image_frame_opencv_test
INFO: Analyzed target //mediapipe/framework/formats:image_frame_opencv_test (0 packages loaded,
 2 targets configured).
INFO: Found 1 target...
Target //mediapipe/framework/formats:image_frame_opencv_test up-to-date:
  bazel-bin/mediapipe/framework/formats/image_frame_opencv_test
INFO: Elapsed time: 1.998s, Critical Path: 1.85s
INFO: 2 processes: 2 processwrapper-sandbox.
INFO: Build completed successfully, 6 total actions
INFO: Running command line: external/bazel_tools/tools/test/test-setup.sh mediapipe/framework/f
INFO: Build completed successfully, 6 total actions
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //mediapipe/framework/formats:image_frame_opencv_test
-----------------------------------------------------------------------------
Running main() from external/com_google_googletest/googlemock/src/gmock_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from ImageFrameOpencvTest
[ RUN      ] ImageFrameOpencvTest.ConvertToMat
[       OK ] ImageFrameOpencvTest.ConvertToMat (1 ms)
[ RUN      ] ImageFrameOpencvTest.ImageFormats
[       OK ] ImageFrameOpencvTest.ImageFormats (0 ms)
[----------] 2 tests from ImageFrameOpencvTest (1 ms total)
[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (1 ms total)
[  PASSED  ] 2 tests
```

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
