### ISSUE TITLE
How to make the  Holistic work on the CPU？

### ISSUE THREAD

**Issue by ithour** [google/mediapipe#2900]
I tried to compile and use holistictrackingcpu。  but appear .MediaPipeException: invalid argument: Graph has errors: 
    Packet type mismatch on calculator outputting to stream "input_video": The Packet stores "::mediapipe::Image", but "mediapipe::ImageFrame" was requested.

**Comment by sgowroji** [comment]
Hi @ithour, Could you please provide steps to reproduce the above error. Thanks!

**Comment by ithour** [comment]
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "holistic_tracking_cpu",
    calculators = ["//mediapipe/graphs/holistic_tracking:holistic_tracking_cpu_graph_deps"],
)
-----------------------------------------------------------------------------------------------------------------------
bazel build -c opt --strip=ALWAYS \
--action_env PYTHON_BIN_PATH=$(which python3) \
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
--fat_apk_cpu=arm64-v8a,armeabi-v7a \
//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_holistic_cpu:holistic_tracking_cpu.aar
-----------------------------------------------------------------------------------------------------------------------------------
mediapipe_binary_graph(
    name = "holistic_tracking_cpu",
    graph = "holistic_tracking_cpu.pbtxt",
    output_name = "holistic_tracking_cpu.binarypb",
    deps = [":holistic_tracking_cpu_graph_deps"],
)
--------------------------------------------------------------------------------------------------------------------------------------------
bazel build -c opt \
--action_env PYTHON_BIN_PATH=$(which python3) \
mediapipe/graphs/holistic_tracking:holistic_tracking_cpu

------------------------------------------------------------------------------------------------------------------------------------------

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        try {
            applicationInfo =
                    getPackageManager().getApplicationInfo(getPackageName(), PackageManager.GET_META_DATA);
        } catch (PackageManager.NameNotFoundException e) {
            Log.e(TAG, "Cannot find application info: " + e);
        }
        mCameraFps = findViewById(R.id.camera_fps);
        previewDisplayView = new SurfaceView(this);
        setupPreviewDisplayView();

        // Initialize asset manager so that MediaPipe native libraries can access the app assets, e.g.,
        // binary graphs.
        AndroidAssetUtil.initializeNativeAssetManager(this);
        eglManager = new EglManager(null);
        processor = new FrameProcessor(this,
                        eglManager.getNativeContext(),
                        "holistic_tracking_cpu.binarypb",
                        applicationInfo.metaData.getString("inputVideoStreamName"),
                        applicationInfo.metaData.getString("outputVideoStreamName")
                );

        processor.getVideoSurfaceOutput().setFlipY(applicationInfo.metaData.getBoolean("flipFramesVertically", FLIP_FRAMES_VERTICALLY));
    }
    
    @Override
    protected void onResume() {
        super.onResume();
        converter = new ExternalTextureConverter(eglManager.getContext(), applicationInfo.metaData.getInt("converterNumBuffers", 2));
        converter.setFlipY(
                applicationInfo.metaData.getBoolean("flipFramesVertically", FLIP_FRAMES_VERTICALLY));
        converter.setConsumer(processor);
        if (PermissionHelper.cameraPermissionsGranted(this)) {
            startCamera();
        }
    }
---------------------------------------------------------------------------------------------------------------
An exception occurs when the camera is turned on ， error log：
2021-12-17 14:00:46.468 26701-26728/com.google.mediapipe.apps.mediapipeholistic E/FrameProcessor: Mediapipe error: 
    com.google.mediapipe.framework.MediaPipeException: invalid argument: Graph has errors: 
    Packet type mismatch on calculator outputting to stream "input_video": The Packet stores "mediapipe::GpuBuffer", but "mediapipe::ImageFrame" was requested.
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:395)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:458)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:403)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:338)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$IXJjtE68JMV2CMJNQcFYhTUqhj8.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:263)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)

**Comment by ithour** [comment]
@sgowroji

**Comment by Ar4enal** [comment]
same problem

**Comment by Ar4enal** [comment]
@ithour same problem. Did you solve it?

**Comment by ithour** [comment]
@Ar4enal  yes， reference resources  ：https://google.github.io/mediapipe/solutions/face_detection.html

**Comment by Ar4enal** [comment]
> @Ar4enal yes， reference resources ：https://google.github.io/mediapipe/solutions/face_detection.html

Sorry, I do not understand how this reference resource is related to holistic cpu?

**Comment by ithour** [comment]
@Ar4enal 
imitate face_detection cpu
 CPU PIPELINE
This is very similar to the GPU pipeline except that at the beginning and the end of the pipeline it performs GPU-to-CPU and CPU-to-GPU image transfer respectively. As a result, the rest of graph, which shares the same configuration as the GPU pipeline, runs entirely on CPU.

Graph: mediapipe/graphs/face_detection/face_detection_mobile_cpu.pbtxt
Android target: (or download prebuilt ARM64 APK) mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu:facedetectioncpu
iOS target: mediapipe/examples/ios/facedetectioncpu:FaceDetectionCpuApp

**Comment by Ar4enal** [comment]
> 

I got it! Thank you very much.

But the rendered surface has a problem. The facemesh can be detected correctly. But the pose and hands landmarks can not move. I wonder whether you have met this problem.

**Comment by ithour** [comment]
Everything is normal for me

**Comment by Ar4enal** [comment]
> 

Alright, thank you anyway.
