### ISSUE TITLE
How to check for mediapipe version on Raspbian?

### ISSUE THREAD

**Issue by hasankhurshid29** [google/mediapipe#2902]
I build a v0.8.8 using https://github.com/PINTO0309/mediapipe-bin#4-build this guide. But when it completed successfully, still the codes which are meant to run on v0.8.8 or greater were giving error on tags which they can't find. So how can I check the version of mediapipe installed?

OS: Raspbian 64 Bit
Raspberry Pi 4 8 GB

**Comment by sgowroji** [comment]
Hi @hasankhurshid29, Please go through our MediaPipe Code repo https://github.com/google/mediapipe. For python solutions you can build it from here https://google.github.io/mediapipe/getting_started/python

**Comment by Aurosutru** [comment]
Answers here have not addressed the OP's question, which was, _So how can I check the version of mediapipe installed?_
