### ISSUE TITLE
Segmentation fault (core dumped) when running Holistic GPU example on Ubuntu 20.04

### ISSUE THREAD

**Issue by rdisabato** [google/mediapipe#2905]
Hi,
I can successfully build the "holistic_tracking_gpu" example, but when I run it I get the following error: 
"Segmentation fault (core dumped)"

I can successfully build and run the "hand_tracking_gpu" example without any problem.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): NO custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Linux Ubuntu 20.04
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.9
- Bazel version: 4.2.1
- Solution (e.g. FaceMesh, Pose, Holistic): Holistic
- Programming Language and version ( e.g. C++, Python, Java): C++

**Describe the expected behavior:**
I expected that running holistic would open the webcam window with the landmarks displayed 

**Standalone code you may have used to try to get what you need :**
Reproduce the problem is very simple:
1. Install Ubuntu 20.04
2. Download the zip of the Mediapipe release 0.8.9
3. Run the steps of the Mediapipe installation on Linux Ubuntu at the official link: https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu (at the step 3, choose the option 2 "Run setup_opencv.sh".
4. Add the GPU support by executing the steps in the chapter "OpenGL ES Setup on Linux Desktop " at the official link: https://google.github.io/mediapipe/getting_started/gpu_support.html

5. After executing these steps i solved an error caused by missing numpy, so in installed it with the command:
pip install numpy.

6. Build the holistic_tracking_gpu: bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/holistic_tracking:holistic_tracking_gpu
7. Run the holistic_tracking_gpu: bazel-bin/mediapipe/examples/desktop/holistic_tracking/holistic_tracking_gpu --calculator_graph_config_file=mediapipe/graphs/holistic_tracking/holistic_tracking_gpu.pbtxt

After the run i get the error: "Segmentation fault (core dumped)"

I get no error if i build and run the "hand_tracking_gpu" example.

**Other info / Complete Logs :**
[issue.txt](https://github.com/google/mediapipe/files/7740776/issue.txt)

**Comment by rdisabato** [comment]
The pull request #2463 from @homuler has fixed the problem, but it is not merged in the official Medipipe. Why?
2 months have passed since the pull request.

**Comment by khayyat71** [comment]
I'm facing the same problem put on pose_tracking example

**Comment by mcclanahoochie** [comment]
Please see https://github.com/google/mediapipe/issues/2170

**Comment by yash-s-expertrons** [comment]
Facing the same issue in Pose Detection
