### ISSUE TITLE
Misnamed pose landmark in JS solution

### ISSUE THREAD

**Issue by AzureRain1** [google/mediapipe#2906]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Fedora 35
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Chrome 96.0.4664.110
- Programming Language and version ( e.g. C++, Python, Java): JavaScript
- [MediaPipe version](https://github.com/google/mediapipe/releases): @mediapipe/holistic: 0.5.1635989137
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ): Holistic
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
- Xcode & Tulsi version (if issue is related to building for iOS):

**Describe the current behavior:**
The pose landmarks are named differently in Typescript definition and the actuall JS code. In TS, `POSE_LANDMARKS` has mouth landmarks named `MOUTH_LEFT` and `MOUTH_RIGHT`, but in actual JS code they are named `RIGHT_LEFT` and `LEFT_RIGHT` for index 9 and 10.

**Describe the expected behavior:**
The indices are correctly named `MOUTH_LEFT` and `MOUTH_RIGHT`.

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:
In `function onResults(results: Results)` from the holistic demo, comment out
```
removeLandmarks(results);
```
and add after
```
  console.log(results.poseLandmarks[POSE_LANDMARKS.MOUTH_LEFT]);
  console.log(results.poseLandmarks[POSE_LANDMARKS.MOUTH_RIGHT]);
  console.log(results.poseLandmarks[POSE_LANDMARKS.RIGHT_LEFT]);
  console.log(results.poseLandmarks[POSE_LANDMARKS.LEFT_RIGHT]);
```
. The first two output `undefined` and the latter two output actual values.

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

**Comment by sgowroji** [comment]
Hi @AzureRain1, Thank you for using pose solution. Could you please bring any logs or data specific to the above behaviour  to investigate further. Thanks!

**Comment by AzureRain1** [comment]
@sgowroji As I mentioned above, just go to the Demo page of the JS Holistic solution at [https://codepen.io/mediapipe/pen/LYRRYEw](https://codepen.io/mediapipe/full/jOMbvxw), open the Editor and insert
```
  console.log(results.poseLandmarks[POSE_LANDMARKS.MOUTH_LEFT]);
  console.log(results.poseLandmarks[POSE_LANDMARKS.MOUTH_RIGHT]);
  console.log(results.poseLandmarks[POSE_LANDMARKS.RIGHT_LEFT]);
  console.log(results.poseLandmarks[POSE_LANDMARKS.LEFT_RIGHT]);
```
above line 109, and you will see the behavior. Any scene with a face in it will work.

**Comment by kuaashish** [comment]
Hello @AzureRain1,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
