### ISSUE TITLE
Cannot access MediaPipe npm from CDN

### ISSUE THREAD

**Issue by TomHsiao1260** [google/mediapipe#2908]
It seems that MediaPipe npm has been blocked by the chrome browser since yesterday. I cannot load related code & models from MediaPipe CDN. Has anyone faced a similar problem? You can test the following links:

https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils/camera_utils.js
https://cdn.jsdelivr.net/npm/@mediapipe/control_utils/control_utils.js
https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/drawing_utils.js
https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js

**Comment by sgowroji** [comment]
Hi @TomHsiao1260, Could you please share the error logs to investigate the issue further. Thanks!

**Comment by TomHsiao1260** [comment]
Hi, thank for the quick reply! I think it's a temporary issue from `cdn.jsdelivr.net` and it works well now. So I close this issue.
