### ISSUE TITLE
Finding Iris RGB Pixels 

### ISSUE THREAD

**Issue by Roopesh-Bharatwaj-K-R** [google/mediapipe#2909]
I have the Iris Landmarks Points( 5 : Centre, left, right, top, bottom). X,Y Coordinates 

Can we Able to get the Entire Iris each Pixel(RGB)  Information, is there any specific Call i should Make.

**Comment by sgowroji** [comment]
Hi @Roopesh-Bharatwaj-K-R,  Could you please point us to the above code with any links which you are referring and also elaborate with complete details. Thanks!
