### ISSUE TITLE
Assign Rect_id

### ISSUE THREAD

**Issue by FlyingD3** [google/mediapipe#2910]
Hello,
I'm writing some code to track the rectangles in the handtracking application and to do it I've put this line of code inside it:

static const char* kRectOutputStream = "hand_rects_from_landmarks";
[self.mediapipeGraph addFrameOutputStream:kRectOutputStream outputPacketType:MPPPacketTypeRaw];

From this I obtain center_x, width, height  and so on, but the rect_id (that in rectangle.h  @is optional) is empty.

How can I do to assign the Id's when the rectangles are created?

Thank you

**Comment by sgowroji** [comment]
Hi @FlyingD3, Could you please elaborate your use case with respect to the above query. Thanks!

**Comment by FlyingD3** [comment]
Of course, I'm writing an app for iOS and I need to track the movements of two hands of 2 different persons. The inputs are some videos preloaded on the app. I'm able to extract the coordinates of the rectangles and the landmarks of every hand. In order to track the movements correctly during the time I need to have the rect id of the boxes. In the class rectangle.h there's the id like optional field but is always empty. How can assign this id and propagate during the frames. I don't know if was I clear enough.

**Comment by kuaashish** [comment]
Hello @FlyingD3,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
