### ISSUE TITLE
Facemesh landmarks inconsistency 

### ISSUE THREAD

**Issue by Anulo2** [google/mediapipe#2911]
Informations
- I'm using React 17.0.2 and three.js
- I want to compare the landmarks of a face in 2 different moments. For example when I'm smiling or not.
- Windows 10
- MediaPipe version: https://www.npmjs.com/package/@mediapipe/face_mesh latest
- Solution: FaceMesh

I expect the model to return landmarks that when I rotate my face and move around will remain the same distance between eachother if I don't change my expression. If this is true I should be able to push the landmarks to a points geometry in three.js, save the current points geometry and a reference one, rotate the current one to the reference one and move it so it lines up with the reference geometry. I can do that but when I rotate my head in some directions the landmarks don't appear to maintain the shape but rather shrink/stretch. 
This leads to my main issue which is that I can't compare the reference landmarks with the current landmarks in a reliable way because of the shrinking/stretching.

Is this a desired behaviour in the model? If it is, any tip on how I could counter it?

**Comment by sgowroji** [comment]
Hi @Anulo2,   Could you please provide shrinking/stretching behaviour w.r.t Facemesh model with some screenshots or videos to understand the issue and also code implementation with respect to the above query. Thanks!

**Comment by Anulo2** [comment]
hi @sgowroji, I've created a small project with the code to recreate the issue, you can find it [here](https://gitlab.com/qbgdevs/google-mediapipe-issue). 
I've also added a demonstration image: https://gitlab.com/qbgdevs/google-mediapipe-issue/-/raw/main/Demonstrationpng.png
The red dots you see are the initial facemesh landmarks that I use as a reference, while the white points are the landmarks of the actual face that I want to compare to the original one. These points are rotated and moved so that they should match the original face. 
To rotate the face I use a pivot (the big red sphere) that can be moved around with three sliders so it match the videocamera position in the 3d space. I've added this because I've noticed it's more precise and the landmarks seems to morph only when i tilt my head.
If you want to see the code I use to rotate everythingh, look here: https://gitlab.com/qbgdevs/google-mediapipe-issue/-/blob/main/src/Components/Renderer/handleFaces.js#L87
I hope this will help you understand the issue I'm having.
Thanks for your time!

**Comment by kuaashish** [comment]
Hello @Anulo2,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
