### ISSUE TITLE
My code wont work after install mediapipe

### ISSUE THREAD

**Issue by ruadoVn** [google/mediapipe#2912]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):Garuda OS
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:Brave Browser
- Programming Language and version ( e.g. C++, Python, Java):Python
- [MediaPipe version](https://github.com/google/mediapipe/releases):0.8.9.1

**Describe the current behavior:**
The program wont work and this the log
Traceback (most recent call last):
  File "/run/media/ruadovn/CODE/Python/SoundControl/test.py", line 16, in <module>
    detector=htm.handDetector(detectionCon=0.55)
  File "/run/media/ruadovn/CODE/Python/SoundControl/hand.py", line 19, in __init__
    self.hands = self.mpHands.Hands(self.mode, self.maxHands,
  File "/run/media/ruadovn/CODE/Python/SoundControl/venv3.9/lib/python3.9/site-packages/mediapipe/python/solutions/hands.py", line 114, in __init__
    super().__init__(
  File "/run/media/ruadovn/CODE/Python/SoundControl/venv3.9/lib/python3.9/site-packages/mediapipe/python/solution_base.py", line 258, in __init__
    self._input_side_packets = {
  File "/run/media/ruadovn/CODE/Python/SoundControl/venv3.9/lib/python3.9/site-packages/mediapipe/python/solution_base.py", line 259, in <dictcomp>
    name: self._make_packet(self._side_input_type_info[name], data)
  File "/run/media/ruadovn/CODE/Python/SoundControl/venv3.9/lib/python3.9/site-packages/mediapipe/python/solution_base.py", line 513, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
TypeError: create_int(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int) -> mediapipe.python._framework_bindings.packet.Packet

Invoked with: 0.55
**Describe the expected behavior:**
The program must run
**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:
"""
Hand Module

"""

import cv2
import mediapipe as mp
import time

class handDetector():
    def __init__(self, mode=False, maxHands=2, detectionCon=0.5, trackCon=0.5):
        self.mode = mode
        self.maxHands = maxHands
        self.detectionCon = detectionCon
        self.trackCon = trackCon

        self.mpHands = mp.solutions.hands
        self.hands = self.mpHands.Hands(self.mode, self.maxHands,
                                        self.detectionCon, self.trackCon)
        self.mpDraw = mp.solutions.drawing_utils

    def findHands(self, img, draw=True):
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        self.results = self.hands.process(imgRGB)
        # print(results.multi_hand_landmarks)

        if self.results.multi_hand_landmarks:
            for handLms in self.results.multi_hand_landmarks:
                if draw:
                    self.mpDraw.draw_landmarks(img, handLms,
                                               self.mpHands.HAND_CONNECTIONS)
        return img

    def findPosition(self, img, handNo=0, draw=True):

        lmList = []
        if self.results.multi_hand_landmarks:
            myHand = self.results.multi_hand_landmarks[handNo]
            for id, lm in enumerate(myHand.landmark):
                # print(id, lm)
                h, w, c = img.shape
                cx, cy = int(lm.x * w), int(lm.y * h)
                # print(id, cx, cy)
                lmList.append([id, cx, cy])
                if draw:
                    cv2.circle(img, (cx, cy), 15, (255, 0, 255), cv2.FILLED)

        return lmList

def main():
    pTime = 0
    cTime = 0
    cap = cv2.VideoCapture(1)
    detector = handDetector()
    while True:
        success, img = cap.read()
        img = detector.findHands(img)
        lmList = detector.findPosition(img)
        if len(lmList) != 0:
            print(lmList[4])

        cTime = time.time()
        fps = 1 / (cTime - pTime)
        pTime = cTime

        cv2.putText(img, str(int(fps)), (10, 70), cv2.FONT_HERSHEY_PLAIN, 3,
                    (255, 0, 255), 3)

        cv2.imshow("Image", img)
        cv2.waitKey(1)

if __name__ == "__main__":
    main()
**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

**Comment by sgowroji** [comment]
Because Hand's __init__ method now has 5 params (see https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/hands.py#L89) and the third parameter is model_complexity, which is an int. Please modify your code accordingly.

**Comment by yoyojacky** [comment]
python 3.10 
mediapipe : 0.8.9.1
Same result : 
D:\Pycharm-Projects\venv\Scripts\python.exe D:/Pycharm-Projects/Opencv-Sample/020-HandDetectionGame.py
Traceback (most recent call last):
  File "D:\Pycharm-Projects\Opencv-Sample\020-HandDetectionGame.py", line 9, in <module>
    detector = htm.handDetector()
  File "D:\Pycharm-Projects\Opencv-Sample\HandTrackingModule.py", line 13, in __init__
    self.hands = self.mpHands.Hands(self.mode, self.maxHands, self.detectionCon, self.trackCon)
  File "D:\Pycharm-Projects\venv\lib\site-packages\mediapipe\python\solutions\hands.py", line 114, in __init__
    super().__init__(
  File "D:\Pycharm-Projects\venv\lib\site-packages\mediapipe\python\solution_base.py", line 258, in __init__
    self._input_side_packets = {
  File "D:\Pycharm-Projects\venv\lib\site-packages\mediapipe\python\solution_base.py", line 259, in <dictcomp>
    name: self._make_packet(self._side_input_type_info[name], data)
  File "D:\Pycharm-Projects\venv\lib\site-packages\mediapipe\python\solution_base.py", line 513, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
TypeError: create_int(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int) -> mediapipe.python._framework_bindings.packet.Packet

Invoked with: 0.5
[ WARN:0@2.635] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
