### ISSUE TITLE
Is there any way to get the local coordinates of the face mesh?

### ISSUE THREAD

**Issue by pekochun** [google/mediapipe#2913]
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):

I used the following code.

  https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu/MainActivity.java

If you code it like this you can get the screen coordinates, but I don't want that.
float eyePoint1 = multiFaceLandmarks.get(0).getLandmarkList().get(374).getY()*1920f;

Is there a way to get local coordinates such that the center of the face is the origin?

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):

Android

- Solution (e.g. FaceMesh, Pose, Holistic):

Face Mesh

- Programming Language and version ( e.g. C++, Python, Java):
Java

**Comment by sgowroji** [comment]
Hi @pekochun, If you are looking for face coordinates you can find it here https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png  and android connections of eyes and others can be seen here https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/solutions/facemesh/FaceMeshConnections.java
