### ISSUE TITLE
Error while building objectdetection3d example on Windows 10 wsl (Ubuntu 20.04.3) for Android

### ISSUE THREAD

**Issue by UgurErcelik** [google/mediapipe#2914]
I'm following the steps [Mediapipe Android](https://google.github.io/mediapipe/getting_started/android.html) to build an Android application(Objectdetection3d) using Mediapipe,I've successfully completed the installation procedure for Window's Subsystem for Linux (WSL) using Ubuntu 20.04.3

I'm now trying to build the objectdetection3d example from the Mediapipe repository on WSL by following these [Mediapipe](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows-subsystem-for-linux-wsl) instructions. My Versions :
![image](https://user-images.githubusercontent.com/46873580/147075038-3de7ed77-2eae-4eec-a127-24c4cd602a9d.png)
![image](https://user-images.githubusercontent.com/46873580/147075058-5f8de0f0-6ae0-43a1-a1b9-4314b1fad1cb.png)
![image](https://user-images.githubusercontent.com/46873580/147075076-134ad0a5-005f-4494-aa7c-9477cc31b1f7.png)

I am specifying $ANDROID_HOME and $ANDROID_NDK_HOME with

```
export ANDROID_HOME=/mnt/c/Users/[USER]/AppData/Local/Android/Sdk 
export ANDROID_NDK_HOME=/mnt/c/Users/[USER]/AppData/Local/Android/Sdk/ndk/21.0.6113669
```

Then, I am building the objectdetection example with
```
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d:objectdetection3d'
```
And I get this error :
![image](https://user-images.githubusercontent.com/46873580/147074974-9e57cb2d-b23e-452e-914f-db729e41ee67.png)

What should i do for solution ?

**Comment by sgowroji** [comment]
Hi @UgurErcelik, What is the bazel version ?  Did you  try executing the build commands `bazel clean --expunge` and verify with the above steps again.

**Comment by UgurErcelik** [comment]
i tried this command ``` bazel clean --expunge ``` a lot but got the same error.
My Versions :
Bazelisk version: v1.10.1
Build label: 4.2.2

**Comment by UgurErcelik** [comment]
Hi @sgowroji , is there a different solution about this problem ? I searched a lot but couldn't find

**Comment by sgowroji** [comment]
Hi @UgurErcelik, Seems like your SDK is not properly installed. Were you able to run any hello world example on android ?

**Comment by UgurErcelik** [comment]
Hello @sgowroji ,yes i ran hello world example and different example,my sdk is running properly,i dont think problem about sdk

**Comment by sureshdagooglecom** [comment]
Could you please reproduce the above error with the latest release and let us know if the issue still exists. Thanks!
