### ISSUE TITLE
How do we build autoflip with tensorflow GPU support?

### ISSUE THREAD

**Issue by nelsontseng0704** [google/mediapipe#2915]
Hi Mediapipe team,
How do we build Autoflip pipeline with Tensorflow GPU support?

**System information**:

OS Platform and Distribution : Linux Ubuntu16.04 with Nvidia GPU (CUDA support) 
MediaPipe version: 0.8.6
Bazel version: bazel 3.7.2
Solution: Autoflip
Programming Language: C++

**Describe the problem**:

First question is about the tutorial(https://google.github.io/mediapipe/getting_started/gpu_support.html#tensorflow-cuda-support-and-setup-on-linux-desktop) is about setting Tensorflow GPU on Ubuntu desktop, does this tutorial also doable for Ubuntu?

Second question is about after setting up Tensorflow GPU on Ubuntu, how we build the AutoFlip pipeline with GPU support? 
Maybe we just need set from ` MEDIAPIPE_DISABLE_GPU=1` to `MEDIAPIPE_DISABLE_GPU=0`

`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=0 mediapipe/examples/desktop/autoflip:run_autoflip`

**Comment by sgowroji** [comment]
Hi @nelsontseng0704,  MEDIAPIPE_DISABLE_GPU = 1 will disable the GPU support.  Did you see any error while building Autoflip with GPU ?

**Comment by peternaf** [comment]
Hi @sgowroji \ @nelsontseng0704 
Were you able to find a solution to compile AutoFlip with TF and GPU?
