### ISSUE TITLE
Pose or holistic solution leans the body forward in straight facing the camera pictures

### ISSUE THREAD

**Issue by gilcu2** [google/mediapipe#2918]
As was reported in previous issue in straight facing the camera pictures , pose or holistic solutions leans the body forward. For example in a clean picture of someone in standup facing the camera, when you analized the depth, the feet are deeper than the expected  position, the trunk is bent forward and the arms are well in front of the body. In general, the higher is a body part is, the less than expected depth is predicted.
Atached the plots of the problem using landmarks and world landmarks, the input picture. The problem happens in all cases straight facing the camera pictures with people in stand up position.

Results obtained with the pose or holistic code example in the repo.
- Arch Linux updated on Monday
- Python 3.10.1
- Mediapipe Python module 0.8.9.1

Expected behaviour is that the predicted depths of every part of the body  be similar because in the picture the  person is clearly in standup position. Can be reproduced using the anexed picture.
Can some parameter help me with this problem?

Picture:
![armsBottom10-3](https://user-images.githubusercontent.com/4577745/147153911-cd94bb36-f7b7-44fc-b811-c376278a2769.jpg)

Annotated:
![annotated_image3](https://user-images.githubusercontent.com/4577745/147154065-fa2d9ffe-280b-44f2-8cab-c6102fa6f0b8.png)

Landmarks:
![ArmsBottom10 3-Lanmark](https://user-images.githubusercontent.com/4577745/147154246-9eb0a6e3-407b-4388-9a94-73308d47a00c.png)

World Landmarks:
![ArmsBottom10 3-WorldLanmark](https://user-images.githubusercontent.com/4577745/147154356-6f739df7-5851-4f15-b0e2-f1598d321c64.png)

**Comment by sgowroji** [comment]
Hi @gilcu2, Thank you for reaching us regarding the above issue. Did you see the same with our pose or holistic solution python examples. We did not encounter any such scenarios, Could you please share your code changes to understand the above behaviour. Thanks!

**Comment by gilcu2** [comment]
I used exactly your example code for pose detection. Any way, I am copying it here.  You can reproduce by processing the image I attached before and rotate the plot of the pose_world landmarks to have a lateral view.

>   

>      import cv2
> 
>      import mediapipe as mp
>      import numpy as np
> 
> 
>      mp_drawing = mp.solutions.drawing_utils
>      mp_drawing_styles = mp.solutions.drawing_styles
>      mp_pose = mp.solutions.pose
> 
>      def pose():
> 
>       # For static images:
>       IMAGE_FILES = [
>         '/home/gilcu2//armsBottom10-3.jpg',
>       ]
> 
>       BG_COLOR = (192, 192, 192) # gray
>       with mp_pose.Pose(
>         static_image_mode=True,
>         model_complexity=2,
>         enable_segmentation=True,
>         min_detection_confidence=0.5) as pose:
>         for idx, file in enumerate(IMAGE_FILES):
>           print(f'File: {file}')
>           image = cv2.imread(file)
>           image_height, image_width, _ = image.shape
>           # Convert the BGR image to RGB before processing.
>           results = pose.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
> 
>           if not results.pose_landmarks:
>               print('No results')
>               continue
>           landmarks=results.pose_world_landmarks.landmark
>           noseIndex=mp_pose.PoseLandmark.NOSE
>         
>         
> 
>           annotated_image = image.copy()
>           # Draw segmentation on the image.
>           # To improve segmentation around boundaries, consider applying a joint
>           # bilateral filter to "results.segmentation_mask" with "image".
>           condition = np.stack((results.segmentation_mask,) * 3, axis=-1) > 0.1
>           bg_image = np.zeros(image.shape, dtype=np.uint8)
>           bg_image[:] = BG_COLOR
>           annotated_image = np.where(condition, annotated_image, bg_image)
>           # Draw pose landmarks on the image.
>           mp_drawing.draw_landmarks(
>               annotated_image,
>               results.pose_landmarks,
>               mp_pose.POSE_CONNECTIONS,
>             landmark_drawing_spec=mp_drawing_styles.get_default_pose_landmarks_style())
>           cv2.imwrite('/tmp/annotated_image' + str(idx) + '.png', annotated_image)
>           # Plot pose world landmarks.
>            mp_drawing.plot_landmarks(
>               results.pose_world_landmarks, p_pose.POSE_CONNECTIONS)
> 
> 
>      if __name__ == '__main__':
>        pose()
>

**Comment by ItsMeAbby** [comment]
@gilcu2 @yiusay This issue is regarding the uneven axies. In Matplotlib, the axis values of plots changes as per values. There for the limit is required to put. So , in [drawing_utils.py] (https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/drawing_utils.py) , you have to add limits to all x,y,z axis.

  ax.set_xlim((-1,1))
  ax.set_ylim((-1,1))
  ax.set_zlim((-1,1))

The values can be minimum -1 and maximum 1, as they all are normalized.

@gilcu2 you can see that the axis values start from -0.2 and goes to 0.6, This is what causes the main issue. 

@sgowroji is have created a pull request (https://github.com/google/mediapipe/pull/3284) to solve this bug too. 


![earlier](https://user-images.githubusercontent.com/54268477/164999757-3ab0f5b1-937a-48aa-be75-c0be8bd0eab6.png)

![later](https://user-images.githubusercontent.com/54268477/164999766-46dae70f-a9e1-41ce-b266-5e0b419f6951.png)

There is still a small lean in it. It is due to the reason that the z axis is not a proper z axis. It is approximation.

**Comment by sgowroji** [comment]
++ @sureshdagooglecom

**Comment by gilcu2** [comment]
Hi @sgowroji , thanks. I will try with your solution (-:

**Comment by matanster** [comment]
I'm not sure that I follow how the uneven axes contribute to the "lean forward" artefact being described, perhaps you can further elucidate that connection in a more idiot proof way. 

Also about saying that the Z values are an approximation, in what sense? They are just predictions made by the model are they not? Whereby the model has been trained with lesser quality Z values than the X, Y values given the nature of the training data it is being trained with. 

Why would clipping the values "correct" the lean-forward without introducing inaccuracy in the general case?

Can you add more clarity?

**Comment by gilcu2** [comment]
Hi @sgowroji. I think you only change the depth scale but the problem follows the same, sorry

**Comment by ItsMeAbby** [comment]
> I'm not sure that I follow how the uneven axes contribute to the "lean forward" artefact being described, perhaps you can further elucidate that connection in a more idiot proof way?
> 
> Further, in what sense do you consider the Z axis to be an approximation? Obviously the model is less accurate about its Z values (indebted to the training data that only partially had Z values in it).
> 
> And then, why would this clipping "correct" the lean-forward without introducing inaccuracy in the general case?
> 
> Can you add more clarity please?

The Z value is calculated as approximation from the midpoint or left and right waist named as HIP. So when u print the landmarks value of z axis, the possible ranges are from -1 to +1. If the z value is 0 it means the the depth of it is same as the depth of hip, or it aligns exactly in straight line with hip. The negative values shows that the  hip point is close to camera than the specified point. The positive z value of the point, shows that  its closer to camera than the hip point.

So the face will always be closer to camera than the hip. Rest there are certain inaccuracies in the depth estimation

**Comment by gilcu2** [comment]
> > I'm not sure that I follow how the uneven axes contribute to the "lean forward" artefact being described, perhaps you can further elucidate that connection in a more idiot proof way?
> > Further, in what sense do you consider the Z axis to be an approximation? Obviously the model is less accurate about its Z values (indebted to the training data that only partially had Z values in it).
> > And then, why would this clipping "correct" the lean-forward without introducing inaccuracy in the general case?
> > Can you add more clarity please?
> 
> The Z value is calculated as approximation from the midpoint or left and right waist named as HIP. So when u print the landmarks value of z axis, the possible ranges are from -1 to +1. If the z value is 0 it means the the depth of it is same as the depth of hip, or it aligns exactly in straight line with hip. The negative values shows that the hip point is close to camera than the specified point. The positive z value of the point, shows that its closer to camera than the hip point.
> 
> So the face will always be closer to camera than the hip. Rest there are certain inaccuracies in the depth estimation

Can you propose some transformation to fix this  effect and have more real coordinates?

**Comment by LGuilhermeRodrigues** [comment]
me facing the camera placed on a table, similar to the image in the first comment:
![image](https://user-images.githubusercontent.com/68308462/184555509-d02a106e-cfc3-4862-a832-5d6680c42d43.png)

**Comment by kuaashish** [comment]
Hello @gilcu2,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
