### ISSUE TITLE
MultipleHandTracking Android app not responding

### ISSUE THREAD

**Issue by alizahidraja** [google/mediapipe#292]
I seem to be having an issue with the multiple hand tracking application, it doesnt seem to work, it just gets stuck
can you see what the issue is?
The phone i am using has 4GB Ram and is P20Lite

**Comment by eknight7** [comment]
Can you share some logs please? Any idea about how many frames it processes before getting stuck? How about the state of the app when it is getting stuck - are there any number of hands detected in the frame? Is this issue reproducible repeatedly?

**Comment by alizahidraja** [comment]
it processed one frame
and it just got stuck without any detection
can it be because of slow processing power of the device?
The single hand tracking app worked with lag on the same phone

**Comment by eknight7** [comment]
Multi-hand tracking uses the same underlying graphs as single-hand tracking. If single hand tracking is slow, multi-hands will be slow too.
Were you able to get any logs or figure out what is causing the delay?

**Comment by alizahidraja** [comment]
Found out the issue, it’s very fast and gives real-time results on stock android’s. Not very much on other android’s who have their own OS layer on top of that.
Thanks for your assist!
