### ISSUE TITLE
Improve accuracy of detection and tracking on IR camera output.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [google/mediapipe#2920]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): MediaPipe Hands
- Programming language : Python/Android Java
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state:** Currently the hand tracking solution is unusable on IR camera output. An updated model will greatly improve the performance.

**Will this change the current api? How?** Not sure. But most probably not.

**Who will benefit with this feature?** Any application area where performance on low light conditions is a necessity.

**Please specify the use cases for this feature:** Most products are expected to be deployed in the wild and low light conditions are no rarity.

**Any Other info:**

The IR fails to preserve the shape of the hand and fingers are not easily distinguishable. Tracking fails frequently. A lot of glare is also observed.

**Comment by sgowroji** [comment]
Thank you for reaching us regarding the above query. What is unusable on IR camera output.Could you please elaborate your query with more details. Did you see any errors with hands solution on IR camera, and yes can you share the error details to investigate the above issue.

**Comment by Sreerag-ibtl** [comment]
Actually, it can detect hands in a feed from the IR camera. But it's failing frequently. This frequent lack of prediction from the model makes it unreliable.

I'll share some recordings once I have access to the IR camera.

**Comment by sgowroji** [comment]
Hi @Sreerag-ibtl, Your recordings will be helpful for further investigation. Thanks!

**Comment by PawanBhatt28** [comment]
I am using the mediapipe for Hospitals use on Patient's landmarks detection. When the amount of light is low or not directly to the face of the patient, if the patient is facing against the light, then amount of noise is increasing too much and declaring a static threshold is becoming a huge problem.
If anyone can help me through this, please. Thankyou.
