### ISSUE TITLE
Delegate GPU for face_mesh on desktop

### ISSUE THREAD

**Issue by DuyguSerbes** [google/mediapipe#2921]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):   Linux Ubuntu 19.04
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.3
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic): FaceMesh
- Programming Language and version ( e.g. C++, Python, Java): Python

**Describe the expected behavior:**

When I run the code, It delegate for CPU not GPU? How can I run on GPU?
```
import cv2
import mediapipe as mp
import time
mp_drawing = mp.solutions.drawing_utils
mp_face_mesh = mp.solutions.face_mesh

# For webcam input:
drawing_spec = mp_drawing.DrawingSpec(thickness=1, circle_radius=1)
cap = cv2.VideoCapture(0)
start_time = 0
with mp_face_mesh.FaceMesh(
    max_num_faces=1,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5) as face_mesh:
  while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      continue

    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = face_mesh.process(image)

    # Draw the face mesh annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

    # Flip the image horizontally for a selfie-view display.
    if (time.time() - start_time) > 0:
        print("FPS: ", 1 / (time.time() - start_time))
        counter = 0
        start_time = time.time()
    cv2.imshow('MediaPipe Face Mesh', cv2.flip(image, 1))
    if cv2.waitKey(5) & 0xFF == 27:
      break
cap.release()
```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

**Comment by sgowroji** [comment]
Hi @DuyguSerbes, You can refer this https://github.com/google/mediapipe/issues/2451 and for facemesh please follow this https://github.com/google/mediapipe/issues/2451#issuecomment-903969081.
