### ISSUE TITLE
The archive contains nothing that can be signed

### ISSUE THREAD

**Issue by muhammadabdullah34907** [google/mediapipe#2922]
I have successfully built the media pipe but when I want to distribute the app on the apple store or testflight. it shows me this error.
The archive contains nothing that can be signed
![Screenshot 2021-12-24 at 10 34 22 AM](https://user-images.githubusercontent.com/55294154/147321293-5ce0d571-bc1d-41c6-8dce-c2bffd1f6923.png)

**Comment by muhammadabdullah34907** [comment]
My machine's specs.

![Screenshot 2021-12-24 at 10 43 36 AM](https://user-images.githubusercontent.com/55294154/147321329-131a59c1-b474-4dbe-b0ff-8e59c5ae50a4.png)

**Comment by sgowroji** [comment]
Hi @muhammadabdullah34907, Could you please provide the steps to reproduce and xcode error logs. Thanks!

**Comment by sgowroji** [comment]
Hello @muhammadabdullah34907, Let us know if you still see the above error  and i wanted to try this https://github.com/google/mediapipe/issues/133#issuecomment-1049678841 workaround.   If you have already found the fix/resolution for the same, Please share us in the below comments that would really benefit the community with your contributions. Reach us back if you still have any queries

**Comment by jankoJelic** [comment]
Hello I am having the same issue. The app runs on simulators, and I was able to upload to App Store Connect earlier this month as you will see in screenshots.

This is the new archive that gets the same error as in this thread: 
<img width="676" alt="Screenshot 2022-03-22 at 22 12 17" src="https://user-images.githubusercontent.com/78728156/159577174-b87039a4-4caa-4ce4-a75a-e2948001b24c.png">

and here is the old one that is already on app store:
<img width="615" alt="Screenshot 2022-03-22 at 22 12 24" src="https://user-images.githubusercontent.com/78728156/159577232-31a9f97b-b6a8-4e2d-88ac-6f90efab8b9c.png">

The only difference I can see is on the bottom right side of the window.
