### ISSUE TITLE
Way to implement Mediapipe using React native

### ISSUE THREAD

**Issue by ctippur** [google/mediapipe#2924]
Hello,

I am looking for some documentation around implementing Mediapipe models using react-native.
Something on the lines below:
https://stackoverflow.com/questions/69839121/how-to-implement-mediapipe-pose-library-in-react-native-expo

Shekar

**Comment by sgowroji** [comment]
Hi @ctippur, We don't provide any standalone examples on react native at present. But you can follow this implementation https://github.com/google/mediapipe/issues/587#issuecomment-610585088 to start doing one.

**Comment by ctippur** [comment]
Thanks for responding. The link in the comment seem to throw a 404.
https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md

**Comment by sgowroji** [comment]
Please refer this https://google.github.io/mediapipe/getting_started/android_archive_library.html

**Comment by ctippur** [comment]
Thank you!
