### ISSUE TITLE
Bounding box of detected person on mediapipe pose estimation

### ISSUE THREAD

**Issue by glennford49** [google/mediapipe#2926]
Where can i get the bounding box of pose estimation?
In results.pose_landmarks, i think the width and height are given, but the x,y are not, if i extract the results.segmentation_mask it gives me a 480 arrays, does anybody knows the bounding box of person detected in this mediapipe pose estimation?

**Comment by sgowroji** [comment]
Hi @glennford49, Please see this for drawing the bounding box https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/drawing_utils.py#:~:text=def%20draw_detection(,color%2C%20bbox_drawing_spec.thickness)

**Comment by omkarmohanjoshi** [comment]
I am also trying to get bounding box of pose estimation. I am using draw_detection function as mention above. But I am getting this error - AttributeError: 'google.protobuf.pyext._message.FieldProperty' object has no attribute 'format'
There is some issue with detection.location_data. Please help me understand
