### ISSUE TITLE
FaceGeometry without Renderer - iOS Example

### ISSUE THREAD

**Issue by anappdev2** [google/mediapipe#2927]
I was trying to play with Face Effect example for iOS. Currently example includes renderer and displays pixelBuffer directly. I wanted to handle all the rendering in the app and needed landmarks and pose matrix.  Here is what I have tried

Made changes in the graph files to remove FlowLimiterCalculator and FaceGeometryEffectRendererCalculator nodes
Resulting face_effect_gpu.pbtxt graph file is

```
# GPU buffer. (GpuBuffer)
input_stream: "input_video"
output_stream: "multi_face_geometry"

# Generates an environment that describes the current virtual scene.
node {
  calculator: "FaceGeometryEnvGeneratorCalculator"
  output_side_packet: "ENVIRONMENT:environment"
  node_options: {
    [type.googleapis.com/mediapipe.FaceGeometryEnvGeneratorCalculatorOptions] {
      environment: {
        origin_point_location: TOP_LEFT_CORNER
        perspective_camera: {
          vertical_fov_degrees: 63.0  # 63 degrees
          near: 1.0  # 1cm
          far: 10000.0  # 100m
        }
      }
    }
  }
}

# Computes the face geometry for a single face. The input source is defined
# through `use_face_detection_input_source`.
node {
  calculator: "SingleFaceGeometryFromLandmarksGpu"
  input_stream: "IMAGE:input_video"
  input_side_packet: "ENVIRONMENT:environment"
  output_stream: "MULTI_FACE_GEOMETRY:multi_face_geometry"
}
```

Also commented out following in FaceEffectViewController.mm as not using video_output and side packets
```
+ (MPPGraph*)loadGraphFromResource:(NSString*)resource{
....
....
//  side_packets[kUseFaceDetectionInputSourceInputSidePacket] =  mediapipe::MakePacket<bool>(kUseFaceDetectionInputSource);
//  [newGraph addSidePackets:side_packets];
...
...
//  [newGraph addFrameOutputStream:kOutputStream outputPacketType:MPPPacketTypePixelBuffer];
...
....
}


- (void)processVideoFrame:(CVPixelBufferRef)imageBuffer
                timestamp:(CMTime)timestamp
               fromSource:(MPPInputSource*)source {
...
...
  // Alongside the input camera frame, we also send the `selected_effect_id` int packet to indicate
  // which effect should be rendered on this frame.
//  [self.graph movePacket:std::move(selectedEffectIdPacket)
//              intoStream:kSelectedEffectIdInputStream
//                   error:nil];

}
```
Example calls following method only couple of times and then stops calling it
```
- (void)mediapipeGraph:(MPPGraph*)graph
     didOutputPacket:(const ::mediapipe::Packet&)packet
          fromStream:(const std::string&)streamName {
```
Though it continues to call
```
- (void)processVideoFrame:(CVPixelBufferRef)imageBuffer
                timestamp:(CMTime)timestamp
               fromSource:(MPPInputSource*)source {
```

What am I doing wrong? Is there any other way of getting landmarks and pose matrix without using a renderer?

**Comment by sgowroji** [comment]
Hi @anappdev2, What is the error do you encounter while doing the above changes ?

**Comment by anappdev2** [comment]
Hi @sgowroji ,
As mentioned 
```
- (void)mediapipeGraph:(MPPGraph*)graph
     didOutputPacket:(const ::mediapipe::Packet&)packet
          fromStream:(const std::string&)streamName {
```
does not get called after two frames. If I use renderer node it gets called for each frame.

**Comment by roimulia2** [comment]
Hey @anappdev2, have you managed to solve this?

**Comment by anappdev2** [comment]
Sorry for a late reply. One of the work around is to apply a face effect in graph, ignore the pixel received and just use landmarks/geometry.

**Comment by anappdev2** [comment]
> 

@roimulia2 Sorry for a late reply. One of the work around is to apply a face effect in graph, ignore the pixel received and just use landmarks/geometry.

**Comment by kuaashish** [comment]
Hello @anappdev2,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
