### ISSUE TITLE
How can we get accurate points on wrist?

### ISSUE THREAD

**Issue by veetechh** [google/mediapipe#2929]
I am playing with few use cases for wrist, is there a way to get accurate points on wrist?

If not, do you have plans to launch landmarks on wrist ?

**Comment by sgowroji** [comment]
Hi @veetechh, Could you please provide your usecase w.r.t the above feature request. Thanks!

**Comment by veetechh** [comment]
Please find the link below for one of the use cases.

https://zamst.com/cms/wp-content/uploads/2018/03/wrist_band_01-500x500.jpg

**Comment by veetechh** [comment]
@mgyong would be of great use if you can include this feature. any idea?

**Comment by sgowroji** [comment]
We suspect that new model and app engineering will be required to solve this well.  
That additional engineering is not on Google MediaPipe roadmap.  we have shared this to the product team and will let you know if there is any further update.
