### ISSUE TITLE
Build errors on linux (CPU or GPU) for examples using tflite or tensorflow / works on macOSX

### ISSUE THREAD

**Issue by ksachdeva** [google/mediapipe#293]
I have successfully compiled the face_detection and object_detection examples on OSX (CPU). 

I have successfully compiled the hello world example on Linux (Ubuntu 18.04 / CPU). However, the face_detection & object_detection on Linux are not building and it is because of error in fetching "eigen_archive"

I have tried it on two different computers (Linux) and it is the same behavior. Here is the log -

Main error message is

ERROR: An error occurred during the fetch of repository 'eigen_archive':
   java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz, https://bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz] to /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/eigen_archive/66be6c76fc01.tar.gz: Checksum was 8c25d1439a5432a417abe01e2f2e4252959c51668574d9b6367ca0263e741965 but wanted 6d8ed482addd14892d7b0bd98fec2c02f18fdab97775bda68c3f2a99ffb190fb

## Full Log

$ bazel build -c opt mediapipe/examples/desktop/object_detection:object_detection_tensorflow \
  --define MEDIAPIPE_DISABLE_GPU=1
INFO: Writing tracer profile to '/home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/command.profile.gz'
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/f482488b481a799ca07e7e2d153cf47b8e91a60c.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Build option --compilation_mode has changed, discarding analysis cache.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "445e18e79d16b52925b2738a169ec80682268fb68394e1d618509bff9cd1f8d3"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/ml/Desktop/Dev/users/ksachdeva/projects/mediapipe/WORKSPACE:32:1
INFO: Call stack for the definition of repository 'eigen_archive' which is a tf_http_archive (rule definition at /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/org_tensorflow/third_party/repo.bzl:121:19):
 - /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/org_tensorflow/tensorflow/workspace.bzl:171:5
 - /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/org_tensorflow/tensorflow/workspace.bzl:61:5
 - /home/ml/Desktop/Dev/users/ksachdeva/projects/mediapipe/WORKSPACE:124:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was 8c25d1439a5432a417abe01e2f2e4252959c51668574d9b6367ca0263e741965 but wanted 6d8ed482addd14892d7b0bd98fec2c02f18fdab97775bda68c3f2a99ffb190fb
ERROR: An error occurred during the fetch of repository 'eigen_archive':
   java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz, https://bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz] to /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/eigen_archive/66be6c76fc01.tar.gz: Checksum was 8c25d1439a5432a417abe01e2f2e4252959c51668574d9b6367ca0263e741965 but wanted 6d8ed482addd14892d7b0bd98fec2c02f18fdab97775bda68c3f2a99ffb190fb
INFO: Call stack for the definition of repository 'snappy' which is a tf_http_archive (rule definition at /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/org_tensorflow/third_party/repo.bzl:121:19):
 - /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/org_tensorflow/tensorflow/workspace.bzl:617:5
 - /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/org_tensorflow/tensorflow/workspace.bzl:61:5
 - /home/ml/Desktop/Dev/users/ksachdeva/projects/mediapipe/WORKSPACE:124:1
INFO: Call stack for the definition of repository 'com_googlesource_code_re2' which is a tf_http_archive (rule definition at /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/org_tensorflow/third_party/repo.bzl:121:19):
 - /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/org_tensorflow/tensorflow/workspace.bzl:205:5
 - /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/org_tensorflow/tensorflow/workspace.bzl:61:5
 - /home/ml/Desktop/Dev/users/ksachdeva/projects/mediapipe/WORKSPACE:124:1
ERROR: /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/org_tensorflow/third_party/eigen3/BUILD:33:1: @org_tensorflow//third_party/eigen3:eigen3 depends on @eigen_archive//:eigen in repository @eigen_archive which failed to fetch. no such package '@eigen_archive//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz, https://bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz] to /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/eigen_archive/66be6c76fc01.tar.gz: Checksum was 8c25d1439a5432a417abe01e2f2e4252959c51668574d9b6367ca0263e741965 but wanted 6d8ed482addd14892d7b0bd98fec2c02f18fdab97775bda68c3f2a99ffb190fb
ERROR: Analysis of target '//mediapipe/examples/desktop/object_detection:object_detection_tensorflow' failed; build aborted: no such package '@eigen_archive//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz, https://bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz] to /home/ml/.cache/bazel/_bazel_ml/13aac975263948755edda1912cb9e179/external/eigen_archive/66be6c76fc01.tar.gz: Checksum was 8c25d1439a5432a417abe01e2f2e4252959c51668574d9b6367ca0263e741965 but wanted 6d8ed482addd14892d7b0bd98fec2c02f18fdab97775bda68c3f2a99ffb190fb
INFO: Elapsed time: 3.469s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (53 packages loaded, 2412 targets configured)`

`

**Comment by MitchDtown** [comment]
Same problem here.
https://storage.googleapis.com/mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz doesnt seem to exist.

i worked around it dirty by editing the worspace.bzl file in ~/.cache/bazel/_bazel_*username*/*some number*/external/org_tensorflow/tensorflow/workspace.bzl

here i completely replaced the part where it loads the "eigen"-archive  with this:

    tf_http_archive(
        name = "eigen_archive",
        build_file = clean_dep("//third_party:eigen.BUILD"),
        patch_file = clean_dep("//third_party/eigen3:gpu_packet_math.patch"),
        sha256 = "091d1a3124ea41ac2e70e30028365d78d43a1c617a26445aef15e140e4fab1dd",
        strip_prefix = "eigen-eigen-afc120bc03bd",
        urls = [
            "https://storage.googleapis.com/mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/afc120bc03bd.tar.gz",
            "https://bitbucket.org/eigen/eigen/get/afc120bc03bd.tar.gz",
        ],
    )

afterwards i got another error where it was missing the file "TensorBlockV2.h" in path:
~/.cache/bazel/_bazel_hs-*username*/*somenumber*/external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorBlockV2.h

worked around this by creating a blank file with this name.

After that it worked fine.

**Comment by jiuqiant** [comment]
It seems like object_detection_tensorflow can be built on Debian now. Here are the steps I did:

```
git clone https://github.com/google/mediapipe.git
cd mediapipe/
bazel clean --expunge
bazel build -c opt  --copt -DMESA_EGL_NO_X11_HEADERS  --define 'no_aws_support=true'  mediapipe/examples/desktop/object_detection:object_detection_tensorflow
```
Then,  I see that object_detection_tensorflow is successfully built.
```
Target //mediapipe/examples/desktop/object_detection:object_detection_tensorflow up-to-date:
  bazel-bin/mediapipe/examples/desktop/object_detection/object_detection_tensorflow
INFO: Elapsed time: 271.774s, Critical Path: 192.81s
INFO: 3264 processes: 3262 linux-sandbox, 2 local.
INFO: Build completed successfully, 3320 total actions
```

**Comment by jiuqiant** [comment]
The solution to fix this eigen library fetching issue is the following.

1. Create `third_party/org_tensorflow_e3a7bdbebb99352351a19e2e403136166aa52934.diff` in mediapipe and put the following code into that file.
```
diff --git a/tensorflow/workspace.bzl b/tensorflow/workspace.bzl
index a0546b5f83..c7a9f39ded 100755
--- a/tensorflow/workspace.bzl
+++ b/tensorflow/workspace.bzl
@@ -172,9 +172,9 @@ def tf_repositories(path_prefix = "", tf_repo_name = ""):
         name = "eigen_archive",
         build_file = clean_dep("//third_party:eigen.BUILD"),
         patch_file = clean_dep("//third_party/eigen3:gpu_packet_math.patch"),
-        sha256 = "6d8ed482addd14892d7b0bd98fec2c02f18fdab97775bda68c3f2a99ffb190fb",
-        strip_prefix = "eigen-eigen-66be6c76fc01",
+        sha256 = "add24720f99ab4f3222f4c8a887f2609554cf9187d4f7d24a777a151a0ee2548",
+        strip_prefix = "eigen-git-mirror-4898dcdb06f1b1b0441b8e15119764793f8997e2",
         urls = [
-            "https://storage.googleapis.com/mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz",
-            "https://bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz",
+            "https://storage.googleapis.com/mirror.tensorflow.org/github.com/eigenteam/eigen-git-mirror/archive/4898dcdb06f1b1b0441b8e15119764793f8997e2.tar.gz",
+            "https://github.com/eigenteam/eigen-git-mirror/archive/4898dcdb06f1b1b0441b8e15119764793f8997e2.tar.gz",
         ],
     )
```
2. Modify the WORKSPACE file as the following
```
       "https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/%s.tar.gz" % _TENSORFLOW_GIT_COMMIT,
       "https://github.com/tensorflow/tensorflow/archive/%s.tar.gz" % _TENSORFLOW_GIT_COMMIT,
     ],
+    # Patch https://github.com/tensorflow/tensorflow/commit/e3a7bdbebb99352351a19e2e403136166aa52934
+    patches = [
+        "@//third_party:org_tensorflow_e3a7bdbebb99352351a19e2e403136166aa52934.diff"
+    ],
+    patch_args = [
+        "-p1",
+    ],
     strip_prefix = "tensorflow-%s" % _TENSORFLOW_GIT_COMMIT,
     sha256 = _TENSORFLOW_SHA256,
 )
```

3. Run `bazel clean --expunge` to clean the cache

4. Run your build command again

We will push the fix to GitHub soon.

**Comment by ksachdeva** [comment]
Thanks @jiuqiant . This is to confirm that your suggestions/changes made it work on Linux.

**Comment by jiuqiant** [comment]
The fix is in the master branch.

**Comment by YangHaha123** [comment]
> The solution to fix this eigen library fetching issue is the following.
> 
> 1. Create `third_party/org_tensorflow_e3a7bdbebb99352351a19e2e403136166aa52934.diff` in mediapipe and put the following code into that file.
> 
> ```
> diff --git a/tensorflow/workspace.bzl b/tensorflow/workspace.bzl
> index a0546b5f83..c7a9f39ded 100755
> --- a/tensorflow/workspace.bzl
> +++ b/tensorflow/workspace.bzl
> @@ -172,9 +172,9 @@ def tf_repositories(path_prefix = "", tf_repo_name = ""):
>          name = "eigen_archive",
>          build_file = clean_dep("//third_party:eigen.BUILD"),
>          patch_file = clean_dep("//third_party/eigen3:gpu_packet_math.patch"),
> -        sha256 = "6d8ed482addd14892d7b0bd98fec2c02f18fdab97775bda68c3f2a99ffb190fb",
> -        strip_prefix = "eigen-eigen-66be6c76fc01",
> +        sha256 = "add24720f99ab4f3222f4c8a887f2609554cf9187d4f7d24a777a151a0ee2548",
> +        strip_prefix = "eigen-git-mirror-4898dcdb06f1b1b0441b8e15119764793f8997e2",
>          urls = [
> -            "https://storage.googleapis.com/mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz",
> -            "https://bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz",
> +            "https://storage.googleapis.com/mirror.tensorflow.org/github.com/eigenteam/eigen-git-mirror/archive/4898dcdb06f1b1b0441b8e15119764793f8997e2.tar.gz",
> +            "https://github.com/eigenteam/eigen-git-mirror/archive/4898dcdb06f1b1b0441b8e15119764793f8997e2.tar.gz",
>          ],
>      )
> ```
> 
> 1. Modify the WORKSPACE file as the following
> 
> ```
>        "https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/%s.tar.gz" % _TENSORFLOW_GIT_COMMIT,
>        "https://github.com/tensorflow/tensorflow/archive/%s.tar.gz" % _TENSORFLOW_GIT_COMMIT,
>      ],
> +    # Patch https://github.com/tensorflow/tensorflow/commit/e3a7bdbebb99352351a19e2e403136166aa52934
> +    patches = [
> +        "@//third_party:org_tensorflow_e3a7bdbebb99352351a19e2e403136166aa52934.diff"
> +    ],
> +    patch_args = [
> +        "-p1",
> +    ],
>      strip_prefix = "tensorflow-%s" % _TENSORFLOW_GIT_COMMIT,
>      sha256 = _TENSORFLOW_SHA256,
>  )
> ```
> 
> 1. Run `bazel clean --expunge` to clean the cache
> 2. Run your build command again
> 
> We will push the fix to GitHub soon.

Hello, Can this solution be used on Coral Dev Board?

**Comment by YangHaha123** [comment]
> The solution to fix this eigen library fetching issue is the following.
> 
> 1. Create `third_party/org_tensorflow_e3a7bdbebb99352351a19e2e403136166aa52934.diff` in mediapipe and put the following code into that file.
> 
> ```
> diff --git a/tensorflow/workspace.bzl b/tensorflow/workspace.bzl
> index a0546b5f83..c7a9f39ded 100755
> --- a/tensorflow/workspace.bzl
> +++ b/tensorflow/workspace.bzl
> @@ -172,9 +172,9 @@ def tf_repositories(path_prefix = "", tf_repo_name = ""):
>          name = "eigen_archive",
>          build_file = clean_dep("//third_party:eigen.BUILD"),
>          patch_file = clean_dep("//third_party/eigen3:gpu_packet_math.patch"),
> -        sha256 = "6d8ed482addd14892d7b0bd98fec2c02f18fdab97775bda68c3f2a99ffb190fb",
> -        strip_prefix = "eigen-eigen-66be6c76fc01",
> +        sha256 = "add24720f99ab4f3222f4c8a887f2609554cf9187d4f7d24a777a151a0ee2548",
> +        strip_prefix = "eigen-git-mirror-4898dcdb06f1b1b0441b8e15119764793f8997e2",
>          urls = [
> -            "https://storage.googleapis.com/mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz",
> -            "https://bitbucket.org/eigen/eigen/get/66be6c76fc01.tar.gz",
> +            "https://storage.googleapis.com/mirror.tensorflow.org/github.com/eigenteam/eigen-git-mirror/archive/4898dcdb06f1b1b0441b8e15119764793f8997e2.tar.gz",
> +            "https://github.com/eigenteam/eigen-git-mirror/archive/4898dcdb06f1b1b0441b8e15119764793f8997e2.tar.gz",
>          ],
>      )
> ```
> 
> 1. Modify the WORKSPACE file as the following
> 
> ```
>        "https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/%s.tar.gz" % _TENSORFLOW_GIT_COMMIT,
>        "https://github.com/tensorflow/tensorflow/archive/%s.tar.gz" % _TENSORFLOW_GIT_COMMIT,
>      ],
> +    # Patch https://github.com/tensorflow/tensorflow/commit/e3a7bdbebb99352351a19e2e403136166aa52934
> +    patches = [
> +        "@//third_party:org_tensorflow_e3a7bdbebb99352351a19e2e403136166aa52934.diff"
> +    ],
> +    patch_args = [
> +        "-p1",
> +    ],
>      strip_prefix = "tensorflow-%s" % _TENSORFLOW_GIT_COMMIT,
>      sha256 = _TENSORFLOW_SHA256,
>  )
> ```
> 
> 1. Run `bazel clean --expunge` to clean the cache
> 2. Run your build command again
> 
> We will push the fix to GitHub soon.

Hello, this problem also occurs in cross-compiling in the docker environment (for the coral development board), but a new error is reported using this solution. Is this method suitable for cross-compiling for the coral development board?(My workstation is ubuntu16.04,I configured according to the following link
https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/README.md#coral-dev-board-setup-experimental)
