### ISSUE TITLE
Getting hand coordinates from video recording

### ISSUE THREAD

**Issue by EigenSpiral** [google/mediapipe#2930]
Hi, I'm doing a research project with hand tracking and I'm interested in mediapipe.
I need the coordinates for the duration of the motion: ideally you input the video and get an array of points corresponding to each joint for each moment in time. 

Currently I'm first converting the video into the image frames, then looping through the folder of frames and then getting the landmark coordinates like:
X_20 = hand_landmarks.landmark[mp_hands.HandLandmark.PINKY_TIP].x

Is this okay or is there a better way to do this?

**Comment by sgowroji** [comment]
Hi @EigenSpiral,  Yes you can do it on a video.

**Comment by EigenSpiral** [comment]
But is this the right way to do it? Or is there a better way?

**Comment by Era360** [comment]
You can check Mediapipe's documentation on how to do it on video. 
[https://google.github.io/mediapipe/solutions/hands](url)

**Comment by EigenSpiral** [comment]
but this is a for doing it simultaneously, how can I do it on a video file that has already been recorded like 'test.mp4'

**Comment by Era360** [comment]
#You can clone the hand tracking module in my repository and use it as follows:
[https://github.com/Era360/handTrackerModule](url)

cap = cv2.VideoCapture("test.mp4")
tr = hT.HandDetector()

while cap.isOpened():
    success, vid = cap.read()
    if not success:
        print("Ignoring empty camera frame.")
        break

    vid = tr.find_hands(vid)
    if tr.find_position(vid) != None:
        print(tr.find_position(vid))
    else:
        print("No Hand detected")

    cv2.imshow('MediaPipe Hands', vid)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()`

**Comment by EigenSpiral** [comment]
What is hT.HandDetector()?

**Comment by EigenSpiral** [comment]
Hi,
Sorry to bother you again, I am a little confused. When I run the following code, the ID always comes out to 0(wrist) instead of ranging from 0 to 20 (to show all the joints). How can I get the data for other joints also?

HandTracker.py:

    def find_position(self, image):
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        if self.results.multi_hand_landmarks:
            my_hand = self.results.multi_hand_landmarks[0]

            for id, lms in enumerate(my_hand.landmark):
                print("CURRENT ID",id)
                h, w, c = image.shape
                cx, cy = int(lms.x * w), int(lms.y * h)
                lm_list = cx
                return cx, cy
                
And in testing.py:

cap = cv2.VideoCapture("IMG-2257.MOV")
tr = hT.HandDetector()

counter = 0
prevID = 0
prevIDmatch = True

while cap.isOpened():
    success, vid = cap.read()
    if not success:
        print("Ignoring empty camera frame.")
        break

    vid = tr.find_hands(vid)
    if tr.find_position(vid) != None:
        temp = tr.find_position(vid)
    else:
        print("No Hand detected")

**Comment by Era360** [comment]
You can leave **testing.py** the way it is and edit the module in the **find_position** function as follows: 
```
def find_position(self, image):
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        if self.results.multi_hand_landmarks:
            my_hand = self.results.multi_hand_landmarks[0]
            all_landmark = []

            for id, lms in enumerate(my_hand.landmark):
                h, w, c = image.shape
                cx, cy = int(lms.x * w), int(lms.y * h)
                all_landmark.append((id, cx, cy))
            return all_landmark
```
Find position function will return a list of sets, where each set contains an id, x-coordinate, and y-coordinate.
or you can edit it to return whatever format you want, eg: dict.

**Comment by EigenSpiral** [comment]
Thank you so much!!
