### ISSUE TITLE
It's show error, I used mediapipe with jetson nano.

### ISSUE THREAD

**Issue by ninenox-dev** [google/mediapipe#2931]
It's error, log is below. 
Please help me. Thank you.
`[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:324] Warning parsing text-format mediapipe.CalculatorGraphConfig: 125:5: text format contains deprecated field "use_gpu"
Traceback (most recent call last):
  File "/home/ninenox/Desktop/hand_tracking/main.py", line 14, in <module>
    min_tracking_confidence=0.5)
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/hands.py", line 145, in __init__
    outputs=['multi_hand_landmarks', 'multi_handedness'])
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solution_base.py", line 254, in __init__
    self._graph.start_run(input_side_packets)
RuntimeError: ; eglGetDisplay() returned error 0x3000ontext_egl.cc:157) `

**Comment by sgowroji** [comment]
Hi @ninenox-dev, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by ninenox-dev** [comment]
I run this code.
```
# Import Libraries
import cv2
import time
import mediapipe as mp


rtsp_cam = 'rtsp://user:pass@192.168.1.2/stream1'
cap = cv2.VideoCapture(rtsp_cam)


mpHands = mp.solutions.hands
hands = mpHands.Hands(static_image_mode=False,
                      max_num_hands=2,
                      min_detection_confidence=0.5,
                      min_tracking_confidence=0.5)
mpDraw = mp.solutions.drawing_utils

pTime = 0
cTime = 0

while True:
    success, img = cap.read()
    
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = hands.process(imgRGB)
    #print(results.multi_hand_landmarks)

    if results.multi_hand_landmarks:
        for handLms in results.multi_hand_landmarks:
            for id, lm in enumerate(handLms.landmark):
                #print(id,lm)
                h, w, c = img.shape
                cx, cy = int(lm.x *w), int(lm.y*h)
                #if id ==0:
                cv2.circle(img, (cx,cy), 3, (255,0,255), cv2.FILLED)

            mpDraw.draw_landmarks(img, handLms, mpHands.HAND_CONNECTIONS)


    cTime = time.time()
    fps = 1/(cTime-pTime)
    pTime = cTime

    cv2.putText(img,str(int(fps)), (10,70), cv2.FONT_HERSHEY_PLAIN, 3, (255,0,255), 3)

    cv2.imshow("Image", img)
    cv2.waitKey(1)
```

**Comment by sgowroji** [comment]
Hi @ninenox-dev, This will help you resolving the above error https://github.com/google/mediapipe/issues/1273#issuecomment-846378557

**Comment by JeffFun23** [comment]
Hello I have the same problem, and I checked the solution in #1273(comment), but I don't get it.
Why does it has to do with image format ? 
I just build an class of Hands 
sorry for bad English

**Comment by ninenox-dev** [comment]
@JeffFun23 I still had problem, If you fix it already please tell me. Thank you.

**Comment by JeffFun23** [comment]
> @JeffFun23 I still had problem, If you fix it already please tell me. Thank you.

I haven't solved it either, hope someone could save us Q__Q

**Comment by JeffFun23** [comment]
@ninenox-dev do you use ssh to connect with jetson nano ?
 I found that if I directly use jetson nano without ssh, I wouldn't have this problem

**Comment by ninenox-dev** [comment]
> @ninenox-dev do you use ssh to connect with jetson nano ? I found that if I directly use jetson nano without ssh, I wouldn't have this problem

yes, I use with ssh. I will try directly follow you. 
Thank you.

**Comment by kuaashish** [comment]
@ninenox-dev,

We will be not supporting the Jeston Nano. However, there are [plugin](https://github.com/Melvinsajith/How-to-Install-Mediapipe-in-Jetson-Nano) from the community which might help in this context But We don't have a plan to support it and does not provide support in how to use them.

**Comment by cujino** [comment]
> I install mediapipe with jetson nano from this steps https://github.com/feitgemel/Jetson-Nano-Python/blob/master/Install-MediaPipe/Setup.txt
> 
> ```
> pip install setup
> wget https://bootstrap.pypa.io/get-pip.py
> sudo python3 get-pip.py
> rm get-pip.py
> 
> 
> sudo pip3 install pip --upgrade
> sudo pip3 install opencv_contrib_python
> 
> git clone https://github.com/PINTO0309/mediapipe-bin
> cd mediapipe-bin
> 
> ./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh
> 
> sudo pip3 install \
> numpy-1.19.4-cp36-none-manylinux2014_aarch64.whl \
> mediapipe-0.8.5_cuda102-cp36-none-linux_aarch64.whl
> ```
> 
> and I run this code.
> 
> ```
> # Import Libraries
> import cv2
> import time
> import mediapipe as mp
> 
> 
> rtsp_cam = 'rtsp://user:pass@192.168.1.2/stream1'
> cap = cv2.VideoCapture(rtsp_cam)
> 
> 
> mpHands = mp.solutions.hands
> hands = mpHands.Hands(static_image_mode=False,
>                       max_num_hands=2,
>                       min_detection_confidence=0.5,
>                       min_tracking_confidence=0.5)
> mpDraw = mp.solutions.drawing_utils
> 
> pTime = 0
> cTime = 0
> 
> while True:
>     success, img = cap.read()
>     
>     imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
>     results = hands.process(imgRGB)
>     #print(results.multi_hand_landmarks)
> 
>     if results.multi_hand_landmarks:
>         for handLms in results.multi_hand_landmarks:
>             for id, lm in enumerate(handLms.landmark):
>                 #print(id,lm)
>                 h, w, c = img.shape
>                 cx, cy = int(lm.x *w), int(lm.y*h)
>                 #if id ==0:
>                 cv2.circle(img, (cx,cy), 3, (255,0,255), cv2.FILLED)
> 
>             mpDraw.draw_landmarks(img, handLms, mpHands.HAND_CONNECTIONS)
> 
> 
>     cTime = time.time()
>     fps = 1/(cTime-pTime)
>     pTime = cTime
> 
>     cv2.putText(img,str(int(fps)), (10,70), cv2.FONT_HERSHEY_PLAIN, 3, (255,0,255), 3)
> 
>     cv2.imshow("Image", img)
>     cv2.waitKey(1)
> 

I get a No such file or directory on the whl installs, did you change any permissions or moved files to make it work? 
thank you

**Comment by HuynhNhan0104** [comment]
When I only plug in the HDMI to VGA adapter, I do not encounter this issue, and I can also use VNC Viewer to execute the code without having to connect a monitor. I am not sure of the exact reason behind this, but in my case, the problem is resolved when I continue to remote SSH. I share for anyone getring this error,  hope it's helpful

> > @ninenox-dev do you use ssh to connect with jetson nano ? I found that if I directly use jetson nano without ssh, I wouldn't have this problem
> 
> yes, I use with ssh. I will try directly use jetson nano without ssh follow your solution. Thank you.

![Screenshot 2023-08-05 165229](https://github.com/google/mediapipe/assets/86313535/0ca90d51-16c0-4f49-8b15-d9ce2f1a4e89)
