### ISSUE TITLE
Question about up-to-scale pose estimation with Mediapipe and Objectron Dataset

### ISSUE THREAD

**Issue by AlbertoRemus** [google/mediapipe#2933]
Hello, I find this work really valuable to extract the 6D pose of an object in the wild.

By consulting https://github.com/google/mediapipe/issues/2581 I understood how to get rotation matrix, translation vector and scaling vector, my question is mostly related to the scaling factor(s), to understand if the obtained results can be valuable for real world object wrt camera pose estimation

I'll refer to this snippet taken from here https://google.github.io/mediapipe/solutions/objectron.html#python-solution-api:

```
import cv2
import mediapipe as mp
import requests
mp_drawing = mp.solutions.drawing_utils
mp_objectron = mp.solutions.objectron

# Save image
response = requests.get("https://images.unsplash.com/photo-1543508282-6319a3e2621f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1015&q=80")
location = "img/shoe1.jpg"
file = open(location, "wb")
file.write(response.content)
file.close()

# static images list
IMAGE_FILES = ["img/shoe1.jpg"]

with mp_objectron.Objectron(static_image_mode=True,
                            max_num_objects=5,
                            min_detection_confidence=0.5,
                            focal_length=(1.0, 1.0),
                            principal_point=(0.0, 0.0),
                            model_name='Shoe') as objectron:

    for idx, file in enumerate(IMAGE_FILES):
        image = cv2.imread(file)

        # Convert the BGR image to RGB and process it with MediaPipe Objectron.
        results = objectron.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

        # Draw box landmarks.
        if not results.detected_objects:
            print(f'No box landmarks detected on {file}')
            continue
        print(f'Box landmarks of {file}:')
        annotated_image = image.copy()
        for detected_object in results.detected_objects:
            mp_drawing.draw_landmarks(
                annotated_image, detected_object.landmarks_2d, mp_objectron.BOX_CONNECTIONS)

            print("rotation")
            print(detected_object.rotation)

            print("translation")
            print(detected_object.translation)

            print("scale")
            print(detected_object.scale)

            mp_drawing.draw_axis(annotated_image, detected_object.rotation,
                                 detected_object.translation)
            cv2.imwrite('./tmp/annotated_image' + str(idx) + '.png', annotated_image)
            print("object box written")
```

As a result on an image from the wild I obtained:
<img src="https://user-images.githubusercontent.com/54797872/147576056-1943e067-ae43-480a-9db8-4de6be6abf04.png" width="50%" height="50%" />

```
rotation
[[ 0.90936464  0.07602954  0.93087411]
 [ 0.28203747  0.98212755 -0.27384761]
 [-0.30579537  0.17217645  0.24182823]]

translation
[ 0.02109673  0.00575765 -0.4891189 ]

scale
[0.16521809 0.18310817 0.49653161]
```

Here's a list of questions:
1) Is the translation vector expressed in meters?
2) Given an homogeneous vector **u** in the object frame, how can I obtain the (homogeneous) vector **v** in the camera frame given the 3x1 scale vector? It should be **v** = [R, **t**; **0**, 1]**u** without scale factor? Is the scale to be organized as a 3x3 diagonal matrix?
3) In the above case I can expect a wrong scale due to the fact I don't have the correct intrinsic parameters `focal_length` and `principal_point`, once I get them however can I expect to get the correct one?
4) Provided the scale of the above example is wrong, is the sign of the z component of the translation vector reasonable? It is negative (0.4891189) and hence I find this quite curious.

I thank you in advance and remain at your disposal for further clarification.

**Comment by AlbertoRemus** [comment]
> 2. Given an homogeneous vector u in the object frame, how can I obtain the (homogeneous) vector v in the camera frame given the 3x1 scale vector? It should be v = [R, t; 0, 1]u without scale factor? Is the scale to be organized as a 3x3 diagonal matrix?

I'm not completely sure, but as far as I understood, with further investigation, what here we call [_scale_](https://google.github.io/mediapipe/solutions/objectron.html#output) is actually the _size_ of the bounding box, which is required being this a category-aware method in 9D (3 rotation, 3 translation, 3 size).

Indeed by looking at the above image we have a bounding box `[0.16521809 0.18310817 0.49653161]` wide, with the latter dimension coherently bigger than the other two.

Feel free to let me know if this is the case or there are some flaws in my understanding

**Comment by AlbertoRemus** [comment]
> > 2. Given an homogeneous vector u in the object frame, how can I obtain the (homogeneous) vector v in the camera frame given the 3x1 scale vector? It should be v = [R, t; 0, 1]u without scale factor? Is the scale to be organized as a 3x3 diagonal matrix?

> I'm not completely sure, but as far as I understood, with further investigation, what here we call [_scale_](https://google.github.io/mediapipe/solutions/objectron.html#output) is actually the _size_ of the bounding box, which is required being this a category-aware method in 9D (3 rotation, 3 translation, 3 size).
 Indeed by looking at the above image we have a bounding box `[0.16521809 0.18310817 0.49653161]` wide, with the latter dimension coherently bigger than the other two.
 Feel free to let me know if this is the case or there are some flaws in my understanding

> 4. Assuming the scale of the above example is wrong,  is the sign of the z component of the translation vector reasonable? It is negative (-0.4891189) and hence I find this quite curious.

I think this should properly answer to most of my doubts related to question 2 and 4 https://google.github.io/mediapipe/solutions/objectron.html#output

**Comment by AlbertoRemus** [comment]
> 1. Is the translation vector expressed in meters?

This should confirm it: https://github.com/google/mediapipe/issues/2581#issuecomment-984820629

**Comment by AlbertoRemus** [comment]
At this point my doubts are mostly related to point 3.

> In the above case I can expect a wrong scale due to the fact I don't have the correct intrinsic parameters `focal_length` and `principal_point`, once I get them however can I expect to get the correct one?

In particular I think the source of my confusion is related to the difference of the (afaik) 1D scaling-factor and the 3D scale vector mentioned before

Sorry if I introduced some noise and I'm open to any further clarification

**Comment by ahmadyan** [comment]
Sry for the late replies, I never saw this issue. 

- Is the translation vector expressed in meters?
Yes, it is metric (as in it is not pixel), but the scale is relative. In your example, [0.16521809 0.18310817 0.49653161], the scale factor (roughtly) is 2.0, so if you divide everything by 2: [0.08, 0.09, 0.25] which is the [height, width, length] of the shoe.

- Given an homogeneous vector u in the object frame, how can I obtain the (homogeneous) vector v in the camera frame given 
the 3x1 scale vector? It should be v = [R, t; 0, 1]u without scale factor? Is the scale to be organized as a 3x3 diagonal matrix?
Very close; Compute the object transformation matrix [R|t] (object-frame to the camera frame) and multiply the inverse of it [R|t]^-1 * u. Also a vector (which denotes a point) does not have scale. A box has scale.

- In the above case I can expect a wrong scale due to the fact I don't have the correct intrinsic parameters focal_length and principal_point, once I get them however can I expect to get the correct one?
Even if you get the correct intrinsic, still the estimation would be up-to-scale. We cannot predict metric scale from a monocular image.

- Provided the scale of the above example is wrong, is the sign of the z component of the translation vector reasonable?
It should be negative, it is -0.5m in front of the camera.

**Comment by AlbertoRemus** [comment]
@ahmadyan many thanks for the detailed reply!

I'm going to close this issue, I'll open new ones if needed
