### ISSUE TITLE
How does mediapipe detect finger landmark points?

### ISSUE THREAD

**Issue by amitbohra1234** [google/mediapipe#2936]
I wanted to know, once a palm (not hand) is detected in a frame, the cropped palm image is passed to the landmarks detection model, so it can detect the landmarks available on the palm, but how does it detect the landmarks available on fingers?
If not palm but hand cropped image is passed to the landmarks detection model, then how does mediapipe get the hand cropped image from the palm detection model (for every rotated, tilted hand in frame)?

**Comment by sgowroji** [comment]
Hi @amitbohra1234, Did you get chance to go through our documentation https://google.github.io/mediapipe/solutions/hands#palm-detection-model

**Comment by amitbohra1234** [comment]
I went through the documentation, read the paper as well and tried to look out for even the code, but didn't get it. Palm is smaller than hand, and it doesn't cover out the region for fingers and thumb, so when detecting out palm, how do the landmarks are localized for fingers and thumb?

**Comment by sgowroji** [comment]
Hi @amitbohra1234, You refer this for finger landmark points https://github.com/google/mediapipe/issues/2997#issuecomment-1016408409
