### ISSUE TITLE
While using mediapipe pose detection with single image file, it doesnt point right foot index, however when i print its coordinate it exists. It doesnt print it on image 

### ISSUE THREAD

**Issue by rmham93** [google/mediapipe#2937]
While using mediapipe pose detection with single image file, it doesnt point right foot index, however when i print its coordinate it exists. It doesnt print it on image 
![pose10 (2)](https://user-images.githubusercontent.com/26356167/147659249-f26b341d-f23f-461d-bf75-9b62957291f3.png)

**Comment by sgowroji** [comment]
Hi @rmham93, Which platform are you seeing the above.?

**Comment by rmham93** [comment]
I have used jupyter notebook with Anaconda nav 2.0.3. Python version 3.8.10. I used static image input and got this images. When there is dress sometimes it doesnt find foot sometimes like above it finds coordinate but no connection
