### ISSUE TITLE
autoflip: I want to log cropped_frames locations where cropped_frames displays?

### ISSUE THREAD

**Issue by in-manish** [google/mediapipe#2938]
I'm using autoflip to transform normal videos into different aspect ratio videos, explained https://ai.googleblog.com/2020/02/autoflip-open-source-framework-for.html.

In [MediaPipe Graph](https://google.github.io/mediapipe/solutions/autoflip#mediapipe-graph) https://google.github.io/mediapipe/solutions/autoflip#mediapipe-graph
the ScenceCropping node exporting cropped frames using [SceneCroppingCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/calculators/scene_cropping_calculator.cc)
I'm trying to log coordinats where scene cropping happening in frame.

where i should put log to get coordinates

**Comment by kuaashish** [comment]
Hello @in-manish,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
