### ISSUE TITLE
FaceMesh nose landmarks not correct on artificial (rendered) facial imagery

### ISSUE THREAD

**Issue by HWiese1980** [google/mediapipe#2939]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): to some extent custom code. But it's mostly based on the example code provided by MediaPipe for FaceMesh on Python. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 11
- Programming Language and version ( e.g. C++, Python, Java): Python 3.9
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.9.1
- Solution ( e.g. FaceMesh, Pose, Holistic ): FaceMesh

**Describe the current behavior:**
On artificial (rendered) facial imagery, nose width does not show as much impact on land marks as other facial attributes

**Describe the expected behavior:**
On artificial (rendered) facial imagery, nose width should be reflected correctly in the detection of facial landmarks

**Standalone code to reproduce the issue:**
I've added a couple example images that show the issue. Raw images, images with rendered landmarks, combined images showing the two extremes (e.g. nose width blendshape of the digital character set to -1 and +1, same about nose height, mouth width and eyes height)

**Additional information**
Since the model provides valid detection of almost all landmarks with all blendshapes I've tested, except for the nose, I'll consider this a bug, even though the model assumedly isn't really made for detecting landmarks on artificial data. 

I'd appreciate any help. Maybe there's something I can do with the rendered image (shaders...) to achieve renders that MediaPipe will work better with? 

**Information about the attached files**

All files have the corresponding blendshape in the filename (`chin_height` etc.). `m1` means blendshape value set to -1, `p1` means blendshape value set to +1. The `delta` png files contain renderings of the landmarks only. The `lm` files contain the faces plus the detected landmarks. The files without landmarks can be used to reproduce the issue by means of the MediaPipe example code. 

As you can see below, the different blendshapes all have at least some impact on the landmarks. Except for the nose width blendshape where there's almost no noticable difference (red and green landmarks around nose match, regardless of the actual width of the nose) between nose width = -1 or nose width = +1. 

## Chin Height
*Blendshape -1 (raw, w/o landmarks)*
![chin_height_m1](https://user-images.githubusercontent.com/743912/147670420-92d4527f-bfa4-4a24-ac5d-7228b4a9f730.png)

*Blendshape +1 (raw, w/o landmarks)*
![chin_height_p1](https://user-images.githubusercontent.com/743912/147670422-be63ea85-e7d0-445f-abaf-7c7a1f88d44e.png)

*Blendshape -1 (w. landmarks)*
![chin_height_m1_lm](https://user-images.githubusercontent.com/743912/147670421-c3a74460-f3da-45d1-b2a7-284e44a7919d.png)

*Blendshape +1 (w. landmarks)*
![chin_height_p1_lm](https://user-images.githubusercontent.com/743912/147670377-e04be5fe-fd07-4be4-9a68-836056a192d2.png)

*Landmarks only with blendshapes -1 (green) and +1 (red)*
![chin_height_delta_lm](https://user-images.githubusercontent.com/743912/147670419-022eeaa2-f7b1-4b13-9102-fb75e3ea944e.png)

## Eyes height
*Blendshape -1 (raw, w/o landmarks)*
![eyes_height_m1](https://user-images.githubusercontent.com/743912/147670385-36e094dd-6093-45be-b3cc-32086ab5f0df.png)

*Blendshape +1 (raw, w/o landmarks)*
![eyes_height_p1](https://user-images.githubusercontent.com/743912/147670389-2df1da52-a57b-4923-ad56-b5ecde957c86.png)

*Blendshape -1 (w. landmarks)*
![eyes_height_m1_lm](https://user-images.githubusercontent.com/743912/147670387-7796872f-1596-4721-8d4d-f7a2f2812f21.png)

*Blendshape +1 (w. landmarks)*
![eyes_height_p1_lm](https://user-images.githubusercontent.com/743912/147670392-d29ee5d7-6123-4b1b-a078-6a55af8d1789.png)

*Landmarks only with blendshapes -1 (green) and +1 (red)*
![eyes_height_delta_lm](https://user-images.githubusercontent.com/743912/147670384-a7f12ef9-bdfd-4bf1-9cc6-106b49e206f1.png)

## Mouth width
*Blendshape -1 (raw, w/o landmarks)*
![mouth_width_m1](https://user-images.githubusercontent.com/743912/147670396-c9efb2d9-3bcd-4695-baf6-60a45a834aff.png)

*Blendshape +1 (raw, w/o landmarks)*
![mouth_width_p1](https://user-images.githubusercontent.com/743912/147670399-395453c0-3e4e-4520-a52e-164a1ef3a051.png)

*Blendshape -1 (w. landmarks)*
![mouth_width_m1_lm](https://user-images.githubusercontent.com/743912/147670397-a53029b5-e70e-409a-8fb3-3104c2f10728.png)

*Blendshape +1 (w. landmarks)*
![mouth_width_p1_lm](https://user-images.githubusercontent.com/743912/147670400-54893ec2-d03f-4752-839a-b6e01d1c9c22.png)

*Landmarks only with blendshapes -1 (green) and +1 (red)*
![mouth_width_delta_lm](https://user-images.githubusercontent.com/743912/147670394-b23fe6d1-566a-4212-b63b-3ba7687bec7f.png)

## Nose height
*Blendshape -1 (raw, w/o landmarks)*
![nose_height_m1](https://user-images.githubusercontent.com/743912/147670406-7467ffb4-2d8b-4682-9ded-acdb6246e20a.png)

*Blendshape +1 (raw, w/o landmarks)*
![nose_height_p1](https://user-images.githubusercontent.com/743912/147670410-0addf227-ea6d-46f9-842b-dedbfe0bbf26.png)

*Blendshape -1 (w. landmarks)*
![nose_height_m1_lm](https://user-images.githubusercontent.com/743912/147670408-85884608-5f7e-466c-b7b9-3bad4745e5f3.png)

*Blendshape +1 (w. landmarks)*
![nose_height_p1_lm](https://user-images.githubusercontent.com/743912/147670411-9bcd3879-d89a-4e40-8c07-4b758c21e241.png)

*Landmarks only with blendshapes -1 (green) and +1 (red)*
![nose_height_delta_lm](https://user-images.githubusercontent.com/743912/147670404-7c791eb7-4dfa-491c-bfa8-fd86afb67449.png)

## Nose width (affected; LMs around nose wrong!)
*Blendshape -1 (raw, w/o landmarks)*
![nose_wide_m1](https://user-images.githubusercontent.com/743912/147670413-5829443f-3608-4e7e-bef2-93f14e3c62ae.png)

*Blendshape +1 (raw, w/o landmarks)*
![nose_wide_p1](https://user-images.githubusercontent.com/743912/147670416-3024d25b-afaa-4248-b78f-da9ce2111b25.png)

*Blendshape -1 (w. landmarks)*
![nose_wide_m1_lm](https://user-images.githubusercontent.com/743912/147670414-5dd9ff0d-0e52-42ac-8b4e-95544782303c.png)

*Blendshape +1 (w. landmarks)*
![nose_wide_p1_lm](https://user-images.githubusercontent.com/743912/147670417-8e1023cd-237c-44b6-822b-dfb32e515483.png)

*Landmarks only with blendshapes -1 (green) and +1 (red)*
![nose_wide_delta_lm](https://user-images.githubusercontent.com/743912/147670412-e286a414-c9c7-4f7e-b820-bee3c94b8e06.png)

**Comment by HWiese1980** [comment]
Seems like the upload killed the filenames... I'll edit the issue to reflect the original names.

**Comment by HWiese1980** [comment]
Alright, finished sorting and describing the images.

**Comment by HWiese1980** [comment]
In case you need more sample images I can generate as many as you need from arbitrary angles and distances, light setups (a bit more difficult) and blendshapes...

**Comment by sgowroji** [comment]
Thank you for patience. We have assigned the above issue to the right owner who can assist you better. Thanks!

**Comment by HWiese1980** [comment]
Cool, thank you very much!

**Comment by kostyaby** [comment]
Thanks for reporting the observation! I added folks who worked on the NN model training to comment further

**Comment by HWiese1980** [comment]
Thank you, @kostyaby 

Any news? Do you need more data?

**Comment by kostyaby** [comment]
Hey @HWiese1980,

I don't train NNs so I really can't comment on the phenomenon you described. @kartynnik and @ivan-grishchenko are the NN experts and should be able to help you

**Comment by HWiese1980** [comment]
Yeah, I'm just wondering if something's going on behind the scenes. No worries!

**Comment by kartynnik** [comment]
Hi @HWiese1980,

Thank you for your extensive research! This is an interesting find.
It's a property of the current model that one can't do much about; we'll take your test cases into account for the new iterations of the model (there are some plans to update it but no particular timeline as of now).

**Comment by HWiese1980** [comment]
@kartynnik That's a pity, but thanks for the information. I think the width of a nose is a vital part of the uniqueness of a face, so a model that allows for face recognition should definitely take it into account. Question is, is the reason that the pictures are artificial? Or does it also occur on real faces? Does your model see a general correlation between, say, face width or eyes distance and nose width? Or how do you get the nose width right if it's not based on the actual nose width?

As I said, if you need further data, more examples like this, I can generate it anytime.

**Comment by kartynnik** [comment]
@HWiese1980 Excuse me for the extremely late response.

> a model that allows for face recognition should definitely take it into account

As per the [model card](https://drive.google.com/file/d/1QvwWNfFoweGVjsXF3DXzcrCnz-mx-Lha/preview), face recognition/identification is explicitly out of scope of this model (see "Out-of-scope applications" under "Intended Uses"):
> Predicted face geometry does
> not provide facial recognition
> or identification and does not
> store any unique face
> representation.

Thank you for your report and for the proposal!

**Comment by HWiese1980** [comment]
Ah, that's really sad. I'd have loved to use MediaPipe for a more way more detailed measurement of facial properties than DLib and co allow. Do you happen to know of any other models that can do what I would like to do, generate remotely as many landmarks, and are preferably as easy to use as yours? Wherever I look for face _recognition_ models, all I get are face _detection_ models instead, or DLib and similar with fewer facial landmarks, i.e. fewer details.

**Comment by HWiese1980** [comment]
Oh, just to clarify my use case a little more: it's not actual _recognition_ (i.e. identifying a person from an image by their facial attributes) but simply _measuring_ these attributes. However, I'm aware that this _could_ be seen as _recognition_, as these measurements are of course practically the basis of the following classification.

**Comment by kuaashish** [comment]
Hello @HWiese1980,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
