### ISSUE TITLE
What is the perfect size of the image for pose and holistic?

### ISSUE THREAD

**Issue by AK51** [google/mediapipe#2940]
If there are lots of people, I want to crop the roi and run the posenet or holistic.
What is the perfect size of the image? 256 x 256?

Thanks.

**Comment by sgowroji** [comment]
Hi @AK51, It is as per our [documentation](https://google.github.io/mediapipe/solutions/pose.html#pose-estimation-quality)  any image contains only a single person located 2-4 meters from the camera give good pose estimation quality.

**Comment by AK51** [comment]
Hi,
When I use the webcam, the "pose" works fine. 
But if I cropped a person (about 300x300) from a 1920 x 1080, the skeleton is not easy to be recognized....
The image is low resolution of 300 x300 but not too blurry.
Is there anyway I can improve it?
I have set the following parameters already.... Thx
with mp_pose.Pose(min_detection_confidence=0.1, min_tracking_confidence=0.5, static_image_mode=True, model_complexity=0,  enable_segmentation=False, smooth_segmentation=False) as pose:

**Comment by sgowroji** [comment]
MediaPipe engineers think 300x300 should suffice.  The failure is a mystery.
Can the user post some examples of his 300x300 images to troubleshoot further. Thanks!

**Comment by AK51** [comment]
I think blurry image after cropping is one of the problem.
For another reason is the tracking.
I think the tracking is off (static_image_mode=True) that's that the recognition is bad.
As mediapipe can only track one person, for each cropped image, if I get the skeleton, how can I pass the info to the next frame?
Do I create an array of pose?
Any sample code (or pseudo code)
Thx

**Comment by kuaashish** [comment]
Hello @AK51,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
