### ISSUE TITLE
The order of facial landmarks returned by face_mesh is not the same as that of the template face.

### ISSUE THREAD

**Issue by ascust** [google/mediapipe#2946]
Hi,
I used the landmark detector to get 468 points from a face image. I also loaded the template mesh (obj file) using trimesh to get vertices and triangles. Then I found a problem when I was trying to plot landmarks of both faces. They seem not in the same order. For example, I plot the very first landmark, and please see the attached images below. The upper one is from the template face and the lower one is from my test face.

![image](https://user-images.githubusercontent.com/12552820/147813783-44011632-e39d-4873-aa4e-e22fc7e0c463.png)
![image](https://user-images.githubusercontent.com/12552820/147813798-ea8e1ce5-a222-4790-a5bc-465e2586dcfc.png)

**Comment by sgowroji** [comment]
Hi @ascust, Could you please provide steps to reproduce the above templates. Thanks!

**Comment by ascust** [comment]
@sgowroji Hi, I think I might have found the reason. It seems that trimesh would change the order of the vertices when loading a mesh from an obj file. Then I read the obj file line by line manually, the issue was gone.
