### ISSUE TITLE
Autoflip:Custom object detection

### ISSUE THREAD

**Issue by gauravzazz** [google/mediapipe#2948]
how can we custom create an object detector or track a custom object in auto flip.

**Comment by sgowroji** [comment]
Hi @gauravzazz, Could you please elaborate your query with complete details. Thanks!

**Comment by gauravzazz** [comment]
I am using auto flip to edit basketball videos and found that this model is not identifying or tracking basketball in any frame. I want it to track the fall and crop the frame with it most of the time.

**Comment by sgowroji** [comment]
Hi @gauravzazz, Did you get a chance to implement the above with object detection [solution](https://google.github.io/mediapipe/solutions/object_detection.html) as mentioned here in any of the platform. You can implement the above in many platforms we have clear documentation with respect to it. Please reach us back if you have any further queries.

Marking this issue as duplicate https://github.com/google/mediapipe/issues/2949 of the present issue.
