### ISSUE TITLE
Autoflip:Training model for custom videos

### ISSUE THREAD

**Issue by gauravzazz** [google/mediapipe#2949]
Can we train auto flip for the custom categories of videos?  if yes how ??

**Comment by sgowroji** [comment]
Hi @gauravzazz , It works on every video. Did you face any issues w.r.t to it ?

**Comment by gauravzazz** [comment]
hi @sgowroji, I am trying to use this on sports videos such as basketball and football. Most of the time it fails to capture the "happening" area. I visualized the frames of such videos, it never tracks or identifies the ball. In the documentation, there is a provision to add a feature detection calculator, but I am not sure how to add that.

**Comment by sgowroji** [comment]
duplicate  https://github.com/google/mediapipe/issues/2948

**Comment by sgowroji** [comment]
Closing this issue with https://github.com/google/mediapipe/issues/2948#issuecomment-1004535050 reference. Please reach us back if you have any queries on the above context. Thanks!
