### ISSUE TITLE
hair segmentation output frame is rotated automatically in android smart tv

### ISSUE THREAD

**Issue by rahulsuxsena1** [google/mediapipe#2950]
I have an android smart tv resolution  720*1280. width 720, height 1280
the hair segmention is working fine but the output frame is rotated 90 degrees. means in a portrait mode the output is coming as landscape.
kindly suggest any solution.

Thanks

**Comment by sgowroji** [comment]
Hi @rahulsuxsena1, could you please provide the screenshot with respect to the above error. Thanks!

**Comment by rahulsuxsena1** [comment]
Hi @sgowroji ,
Sure. PFA the link for the screenshot
https://drive.google.com/file/d/1q0I8VwSg2RE2SGcu-sC3DRlxMiWZw_bY/view?usp=sharing

All UI elements are good at their orientation but the output stream of colored hair is being rotated.
Thanks
Rahul

**Comment by sgowroji** [comment]
Hi @rahulsuxsena1, Its more an android implementation.Try choosing the "select Portrait to rotate the screen" option or enable the portrait mode from TV settings.

**Comment by rahulsuxsena1** [comment]
Hi @sgowroji , Thanks for your reply, but as mentioned the UI elements are at correct orientation only the output stream is being rotated. The TV is at portrait mode as the UI elements shown in the screenshot are aligned correctly as portrait but only the output stream is rotated.

**Comment by PrinceP** [comment]
Hi @rahulsuxsena1 , Can you try changing this flag `"cameraFacingFront": "True"` or `"flipFramesVertically": "True"` in the BUILD file.

**Comment by sgowroji** [comment]
Thanks for update @PrinceP, Did you try the above comment @rahulsuxsena1.
