### ISSUE TITLE
AttributeError: module 'mediapipe' has no attribute 'solutions'

### ISSUE THREAD

**Issue by itzme65** [google/mediapipe#2954]
I can't install mediapipe using command line in raspberrypi 3b+ . So, i'm using this files in my program file. But, there is showing attribute error. AttributeError: module 'mediapipe' has no attribute 'solutions'. How to fix this?? (My source code file name is different)

**Comment by itzme65** [comment]
@sgowroji Sir...please help me. How to fix this??

**Comment by sgowroji** [comment]
Hi @itzme65, Could you please provide the complete steps to reproduce the above error. Thanks!

**Comment by itzme65** [comment]
1st i download the mediapipe zip file and extract it. After that, i put my handgesture.py file into the extract folder. When i run this handgesture.py, it is showing this error:
Traceback (most recent call last):
  File "D:\aperiproject\mediapipe-master\mediapipe-master\handTrackingModul.py", line 71, in <module>
    main()
  File "D:\aperiproject\mediapipe-master\mediapipe-master\handTrackingModul.py", line 51, in main
    detector = handDetector()
  File "D:\aperiproject\mediapipe-master\mediapipe-master\handTrackingModul.py", line 13, in __init__
    self.mpHands = mp/python.solutions.hands
NameError: name 'python' is not defined
![Capture](https://user-images.githubusercontent.com/97146381/148182378-25bd1256-3be7-458e-969c-70756d2bce48.PNG)

**Comment by itzme65** [comment]
@sgowroji Now what to do?

**Comment by itzme65** [comment]
@sgowroji Now, how can i fix this error?

**Comment by sgowroji** [comment]
Did you try ` pip install mediapipe` ? Please try the hands python solution from here https://google.github.io/mediapipe/solutions/hands#python-solution-api. 
your hands code should be like this 
`
mp_hands = mp.solutions.hands`

**Comment by itzme65** [comment]
@sgowroji Yes..i tried pip install mediapipe. But its not working.
And i also tried mp_hands = mp.solutions.hands. Same error
![Capture](https://user-images.githubusercontent.com/97146381/148186452-8a473d72-1c17-49dc-bdaa-0427b493bc23.PNG)

**Comment by sgowroji** [comment]
Is your file had the same name as the library. Similar issue https://github.com/google/mediapipe/issues/1928

**Comment by itzme65** [comment]
@sgowroji No same name as the library. I can ensure it.

**Comment by sgowroji** [comment]
Can you share your code changes ? And also confirm that your site packages as mediapipe  framework code downloaded successfully ?

**Comment by itzme65** [comment]
@sgowroji I think "no". How to check the site packages as mediapipe framework code downloaded or not??

**Comment by itzme65** [comment]
https://drive.google.com/drive/folders/1D2QaoRlwfPBEAIiUHE891JkBHO0JpvAY?usp=sharing
Here is the full file. (mynew.py,new1.py,new2.py is my code )

**Comment by manas1988** [comment]
Hi @itzme65 !  From this [thread ](https://github.com/google/mediapipe/issues/2954#issuecomment-1005465246) , It seems you have not installed dependencies prior installing  Mediapipe. Can you check the  instructions mentioned in these threads ? Link [1](https://github.com/jiuqiant/mediapipe_python_aarch64),[ 2](https://github.com/superuser789/MediaPipe-on-RaspberryPi). Thanks!

**Comment by ryota2425** [comment]
The reason is that there is already a folder named "mediapipe "in the folder where you run the program.

"""
python3
"""

"""
import mediapipe as mp
print(np.__path__)
"""

Either renaming the mediapipe folder or changing the location where you run the program will solve the problem.

**Comment by Pixie34** [comment]
import cv2
import mediapipe as mp


#Declarar variables para mediapipe.
cap = cv2.VideoCapture(0) #Seleccionar el output ya que puede haber mas de 1.
mpManos = mp.solutions.hands #Variable para la detección de partes de las manos.
manos = mpManos.Hands() #Variable para la detección de manos.
mpDibujo = mp.solutions.drawing_utils #Variable para dibujar las manos.

while True: 
    success, image = cap.read() #Detección exitosa de fuente de video.
    imageRGB = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) #Convertir BGR a RGB para mediapipe.
    results = manos.process(imageRGB) #Procesar RGB para detectar manos.

    #Verificar si se detectaron manos.
    if results.multi_hand_landmarks:
        for handLms in results.multi_hand_landmarks: #Deteccion de varias manos. #handLms = Hand Landmarks
            for id, lm in enumerate(handLms.landmark): #Enumerar partes de la mano.
                h, w, c = image.shape #Se adapta a la resolución de la camara.
                cx, cy = int(lm.x * w), int(lm.y * h) #Posición central de la mano en coordenadas.
               
                if id == 12 : #Pulgar = 4
                    cv2.circle(image, (cx, cy), 25, (255, 0, 255), cv2.FILLED) #Rellenar un circulo en el pulgar.

            mpDibujo.draw_landmarks(image, handLms, mpManos.HAND_CONNECTIONS) #Trazar la forma de las manos en el output.
            mpDibujo.draw_framework

    cv2.imshow("Prueba", image) #Mostrar el video en una ventana.
    key = cv2.waitKey(20)
    if key == 27: #Si se presiona ESC se cierra el programa.
        break




it says module 'mediapipe.python.solutions.drawing_utils' has no attribute 'draw_framework'

**Comment by assemsbry** [comment]
> Is your file had the same name as the library. Similar issue #1928

what file are you talking about sir
