### ISSUE TITLE
CodePen demos are performing very low (2-5fps) on Mobile browsers

### ISSUE THREAD

**Issue by furkandindar** [google/mediapipe#2956]
- OS Platform and Distribution: IOS 14,15
- Solution: all solutions except Face Mesh
- Programming Language and version : JavaScript

Hi,

When I try to run JavaScript CodePen demos, all solutions except Face Mesh perform very low (2-5fps). Is there a current development for this? I would like to use Hand, Objectron and Holistic solutions for my web app which should also be able to run on mobile browsers. Thanks in advance!

**Comment by sgowroji** [comment]
Hi @furkandindar, Please find the supported platforms of  MediaPipe codepen and javascript solutions https://google.github.io/mediapipe/getting_started/javascript#supported-plaforms.
