### ISSUE TITLE
how can I get pbtxt file from binarypb file

### ISSUE THREAD

**Issue by mostafamdy** [google/mediapipe#2958]
Hello 
how can I get pbtxt graph file from binarypb

**Comment by sgowroji** [comment]
Hi @mostafamdy, Could you please share your use case with respect to the above request. Thanks!

**Comment by mostafamdy** [comment]
I have code from github for android  solution and I want to use [Visualizer mediapipe tool  ](https://viz.mediapipe.dev/)  to know what happen inside the graph but the visualizer don't support binary graph so can I convert binary graph to pbtxt format

**Comment by sgowroji** [comment]
This can be done but that need more work. There is an opensource protobuf printing tool.  
protobuf API: protobuf::TextFormat, you need to build you own converter with that API.  
(https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.text_format)
(https://medium.com/@nathantnorth/protocol-buffers-text-format-14e0584f70a5)

**Comment by elYeodeol** [comment]
hi, 
is it possible to reopen this issue? 
I'd like to visualize a binarypb file and i cannot convert it in pbtxt.
@mostafamdy how did you write your own converter?

thank you

**Comment by sureshdagooglecom** [comment]
Hi @elYeodeol ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/885.

**Comment by sureshdagooglecom** [comment]
Hi @elYeodeol ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/885.

**Comment by elYeodeol** [comment]
I checked this issue. I tried to recreate the 'pose_web.binarypb' (file loaded when you launch the pose solution page of mediapipe). I want to recreate it bc I want to change the subgraph to modify options. But ive got the wasm error "SolutionWasm$loadGraph" when i used my custom pose_web.binarypb file instead of the original one. So maybe i didn't recreate it perfectly..

**Comment by sureshdagooglecom** [comment]
Hi @elYeodeol ,
Do you still have error?

**Comment by FUBAR2077** [comment]
Any help with #885 will be appreciated, just posted more info about how models look after conversion

**Comment by elYeodeol** [comment]
Hey, 

I am still trying to get a .pbtxt file from a binarypb file.
Specifically, I would like to convert the graph pose_web.binarypb into pose_web.pbtxt
Any help would be appreciated,

Thank you
