### ISSUE TITLE
How to use  MediaPipe Android Solution

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#2960]
How to use  MediaPipe Android Solution (https://maven.google.com/web/index.html?#com.google.mediapipe:hands) ?
can you give me a exzample ?

**Comment by sgowroji** [comment]
Hi @chensisi0730, You can follow the steps from here https://google.github.io/mediapipe/solutions/hands#android-solution-api. and for building the code please refer this https://google.github.io/mediapipe/getting_started/android_solutions.html
