### ISSUE TITLE
FaceMesh Example Does Not Work on iPad with v0.8.9 (works with 0.8.8)

### ISSUE THREAD

**Issue by anappdev2** [google/mediapipe#2961]
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution : iOS 11.4.1
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.9
- Bazel version: 
- Solution : FaceMesh
- Programming Language and version : Objective-C

**Describe the expected behavior:**
Facemesh displaed on screen 

FaceMesh app working on iPhone devices and not working on iPad.
Something changed between v0.8.8 & v0.8.9 as FaceMesh is working on iPad in v0.8.8. With v0.8.9 release FaceMesh does not display the points and the mesh on Face on iPad. Works well on iPhone.

**Comment by sgowroji** [comment]
Hi @anappdev2, Could you please elaborate the above error with more details like video recording of the error and error logs if there are any. Thanks!

**Comment by anappdev2** [comment]
Its not about video recording its just that the mesh is not displayed properly on iPad (as mentioned works great on iPhone). Its very flaky and just turn into small blob of red dots.

Same thing works on ipad with V0.8.8

**Comment by sgowroji** [comment]
@anappdev2  It would be helpful for investigating if you can share the logs or screenshot of the " not displayed on ipad " results.

**Comment by anappdev2** [comment]
Here is screen grab of what is displayed on iPad.
https://user-images.githubusercontent.com/59765390/148884935-69b06795-220a-45f5-ba55-3c3731379a01.mp4

Here is the output on iPhone
https://user-images.githubusercontent.com/59765390/148885259-0736cd9b-4051-4d0b-be21-65ae2aca7e50.mp4

Hope this helps resolving the problem.

**Comment by kuaashish** [comment]
Hello @anappdev2,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
