### ISSUE TITLE
Is there any possibility we can use Mediapipe solutions to build an Autoflip for static images?

### ISSUE THREAD

**Issue by nelsontseng0704** [google/mediapipe#2965]
So far I know Autoflip only handles movie format, is there any possibility we can use other solutions in Mediapipe that can build an Autoflip for static images?

System information (Please provide as much relevant information as possible)

OS Platform and Distribution :iOS 11.3.1
MediaPipe version: 0.8.6
Bazel version: bazel 3.7.2
Solution: Autoflip
Programming Language: C++

**Comment by sgowroji** [comment]
Hi @nelsontseng0704,  https://google.github.io/mediapipe/solutions/autoflip.html works for input videos. May not able available for images yet.
