### ISSUE TITLE
How to get pose_landmark_gpu.binarypb?

### ISSUE THREAD

**Issue by tankchenggeng** [google/mediapipe#2967]
In python, how to use pose_landmark_gpu.binarypb。It will use pose_landmark_cpu.binarypb by below。
mp_pose = mp.solutions.pose
pose = mp_pose.Pose(static_image_mode=False,
                    model_complexity=1,
                    enable_segmentation=False,
                    min_detection_confidence=0.5,
                    )

**Comment by sgowroji** [comment]
Hi @tankchenggeng, Could you please elaborate your query with complete details. Thanks!

**Comment by tankchenggeng** [comment]
If I install mediapipe by $ pip install mediapipe, there is a file named pose_lankmark_cpu.binarypb in the folder site-packages/mediapipe/modules/pose_landmark/。At the same time, I find I can set the model path at site-packages/mediapipe/python/solutions/pose.py, like below:

_BINARYPB_FILE_PATH = 'mediapipe/modules/pose_landmark/pose_landmark_cpu.binarypb' 

the code row is 90!

So, I hope to  get a pose_landmark_gpu.binarypb, that I can use mediapipe with GPU ( avoid compile )

**Comment by sgowroji** [comment]
Hi @tankchenggeng, May be you can try downgrading to MediaPipe version to v0.8.3.1  and then follow the implementation as mentioned here https://github.com/google/mediapipe/issues/1651#issuecomment-790176010

**Comment by tankchenggeng** [comment]
![image](https://user-images.githubusercontent.com/44495942/149468934-b1b28437-6096-460d-b9ae-b3ba3a61d446.png)
I get some errors as below when run git apply above_patch.diff
`
$ git apply above_patch.diff
error: patch failed: mediapipe/modules/holistic_landmark/holistic_landmark_gpu.pbtxt:47
error: mediapipe/modules/holistic_landmark/holistic_landmark_gpu.pbtxt: patch does not apply
error: patch failed: mediapipe/python/BUILD:71
error: mediapipe/python/BUILD: patch does not apply
error: patch failed: mediapipe/python/solutions/holistic.py:44
error: mediapipe/python/solutions/holistic.py: patch does not apply
error: patch failed: setup.py:223
error: setup.py: patch does not apply
`

**Comment by sgowroji** [comment]
Above patch errors are on windows? Could you please try on linux with the same. Thanks!

**Comment by hujb48** [comment]
@tankchenggeng Hi, have u solved this question on "how to get the pose_landmark_gpu.binarypb"

**Comment by tankchenggeng** [comment]
No，I don't solve the question by the time.
