### ISSUE TITLE
No matching toolchains found for types @bazel_tools 

### ISSUE THREAD

**Issue by gakuto235** [google/mediapipe#2968]
<em>Hi guys. So I followed the instructions from [https://google.github.io/mediapipe/getting_started/android#option-2-build-with-bazel-in-android-studio]( Examples) to build an example of hand tracking with mediapipe.However, during the build process, I got the following error.The error is located at the bottom of the code.</em>

`C:\Users\GACKT\mediapipe_repo\mediapipe>bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  C:/users/gackt/mediapipe_repo/mediapipe/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/gackt/_bazel_gackt/uytxjeyg/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: C:/users/gackt/_bazel_gackt/uytxjeyg/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/gackt/_bazel_gackt/uytxjeyg/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/gackt/_bazel_gackt/uytxjeyg/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/gackt/_bazel_gackt/uytxjeyg/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/gackt/_bazel_gackt/uytxjeyg/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/gackt/_bazel_gackt/uytxjeyg/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/gackt/_bazel_gackt/uytxjeyg/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/gackt/_bazel_gackt/uytxjeyg/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/gackt/_bazel_gackt/uytxjeyg/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/gackt/_bazel_gackt/uytxjeyg/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/gackt/_bazel_gackt/uytxjeyg/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build option --linkopt has changed, discarding analysis cache.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3839996049629e6377abdfd04681ddeeb0cc3db13b9d2ff81bf46700cb4529f7"
DEBUG: Repository rules_cc instantiated at:
  C:/users/gackt/mediapipe_repo/mediapipe/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/gackt/_bazel_gackt/uytxjeyg/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: While resolving toolchains for target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
INFO: Elapsed time: 0.215s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 52 targets configured)`

**System information**
- windows10
- Android SDK Build-Tools 30.0.0
- NDK 21.0.6113669

**Describe the problem**:
"no matching toolchains found for types"What do I need to do to resolve this error?

**Comment by sgowroji** [comment]
Hi @gakuto235, If you are looking for Android Hands solution then you can try this gradle api solutions from here https://google.github.io/mediapipe/getting_started/android_solutions.html

**Comment by gakuto235** [comment]
Hi, thanks for the reply.
It seems that the URL I commented on wasn't working properly. The correct URL is this one: https://google.github.io/mediapipe/getting_started/android
I was also working on a mediapipe build on the site you referred me to.
Please let me know if there is any information I am missing.

**Comment by sgowroji** [comment]
@gakuto235  In https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows, there is a note saying that building MediaPipe Android apps is still not possible on native Windows. Please do this in WSL instead.
