### ISSUE TITLE
com.google.protobuf.InvalidProtocolBufferException: Message type does not match the expected type. Expected: null Got: mediapipe.NormalizedLandmarkList

### ISSUE THREAD

**Issue by tulanglaoli** [google/mediapipe#2970]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
    com.google.protobuf.InvalidProtocolBufferException: Message type does not match the expected type. Expected: null Got: mediapipe.NormalizedLandmarkList
        at com.google.mediapipe.framework.ProtoUtil.unpack(ProtoUtil.java:61)
        at com.google.mediapipe.framework.PacketGetter.getProto(PacketGetter.java:126)
        at com.lite.holistic_tracking.holistic_activity.lambda$onCreate$0(holistic_activity.java:122)
        at com.lite.holistic_tracking.-$$Lambda$holistic_activity$bCIeVnrN40oLEc_v1wQIKV6OZoY.process(Unknown Source:0)

holistic_activity.java in 122 code:
processor.addPacketCallback(
                    OUTPUT_LANDMARKS_STREAM_NAME,
                    (packet) -> {
                        Log.v(TAG, "Received pose landmarks packet.");
                        try {
//                            NormalizedLandmarkList defaultInstance = Internal.getDefaultInstance(NormalizedLandmarkList.class);

//                            String expectedType = ProtoUtil.getTypeName(defaultInstance.getClass());
//                            Log.v(TAG, "Received pexpectedType:"+expectedType+" defaultInstance:"+defaultInstance.getClass());
                            NormalizedLandmarkList poseLandmarks =
   <here is 122>                                 PacketGetter.getProto(packet, NormalizedLandmarkList.class);

                            Log.v(
                                    TAG,
                                    "[TS:"
                                            + packet.getTimestamp()
                                            + "] "
                                            + getPoseLandmarksDebugString(poseLandmarks));
                        } catch (InvalidProtocolBufferException exception) {
                            Log.e(TAG, "Failed to get proto.", exception);
                        }
                    });
- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):Android 30
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:Red Mi
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
- Programming Language and version ( e.g. C++, Python, Java):Java
- [MediaPipe version](https://github.com/google/mediapipe/releases):releases
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ):Holistic
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):SDK 30 ,NDK 
- Xcode & Tulsi version (if issue is related to building for iOS):

i have see the source code, the problem is at  ProtoUtil.unpack(ProtoUtil.java:61)
in 61 
String expectedType = ProtoUtil.getTypeName(defaultInstance.getClass());

ProtoUtil  use getTypeName to find string need to use registerTypeName to register first .
but i research  all code ,but no where use it to register ?

so i Manual code 
ProtoUtil.registerTypeName(NormalizedLandmarkList.class,"mediapipe.NormalizedLandmarkList");
at start position and  solve  this  problem.

i don't think Manual register is a good way .  the register job should be in auto.

**Comment by sgowroji** [comment]
Hi @tulanglaoli, Have you tried the workarounds mentioned here https://github.com/google/mediapipe/issues/1013#issuecomment-718640088. ?
