### ISSUE TITLE
i want to get the angle of wrist using mp hands solution

### ISSUE THREAD

**Issue by choigawoon** [google/mediapipe#2973]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using):
- Programming language : C++/typescript/Python/Objective C/Android Java
- Are you willing to contribute it (Yes/No):

mediapipe                     0.8.4.2
python
yes

**Describe the feature and the current behavior/state:**

i cannot get the angle of the wrist just by having the palm context.

**Will this change the current api? How?**

i think no

**Who will benefit with this feature?**

i want to make the app for rehabilitation patient.
rehabilitation patient cannot get the help due to the money, time, or and so on.

**Please specify the use cases for this feature:**

i want to get the angles of wrist like the below.
![image](https://user-images.githubusercontent.com/3104530/148776773-553c7ba3-c410-4820-8656-fe2e6c5ba0d3.png)
![image](https://user-images.githubusercontent.com/3104530/148776956-11225d17-5e53-405b-8040-197714e75258.png)

**Any Other info:**

**Comment by sgowroji** [comment]
We suspect that new model and app engineering will be required to solve this well.  
That additional engineering is not on Google MediaPipe roadmap.  Will share this to the product team and will let you know if there is any further update.
