### ISSUE TITLE
Hair segmentation in JS - can MediaPipe Visualizer be stripped to run-time only?

### ISSUE THREAD

**Issue by pgaston** [google/mediapipe#2974]
I'd like to use Hair Segmentation in a browser app.     (btw, it's fabulous that face mesh and selfie segmentation are already there.)

Seeing as hair segmentation works great using  MediaPipe Visualizer in a browser - is it possible to run that graph (or one slightly modified for fine-tuning output) on the web - baked into my cordova app (cross-platform framework using vanilla HTML w/ js)?

From documentation a year+ ago, it seems like things are coming 'soon'.    Just prodding.    Thanks!

Thanks!     p

(btw, a poor substitute may be combining face mesh w/ selfie segmentation - that may be good enough for academic analysis purposes.)

**Comment by narendraadloid** [comment]
Is there some way to deploy a hair segmentation model on the web app? Any help is much appreciated.

**Comment by ayushgdev** [comment]
Hello @pgaston 
We are building a set of new, improved [MediaPipe Solutions](https://developers.google.com/mediapipe/solutions) to help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. And we request the MediaPipe developer community help us uncover the issues and make the APIs more resilient.

Would you please check in the new [Image Segmentation solution](https://developers.google.com/mediapipe/solutions/vision/image_segmenter/web_js) ? You only need to replace the path to the TfLite model while calling the `createFromOptions()`
```
ImageSegmenter.createFromOptions(vision, {
    baseOptions: {
      modelAssetPath: 'your/path/to/hair_segmentation_model.tflite'
    },
    runningMode: runningMode
  });
```
