### ISSUE TITLE
Data synchronization with mediapipe

### ISSUE THREAD

**Issue by EigenSpiral** [google/mediapipe#2975]
Hi, I'm doing a research project where I'm be collecting data with sensors while doing hand movements. I would like to synchronize the feature coordinates extracted with mediapipe with the sensor data. Since comparing time-stamps doesn't seem possible here, what is the recommended method to synchronize the data?

**Comment by sgowroji** [comment]
Hi @EigenSpiral, Could you please elaborate your use case with complete details. Thanks!

**Comment by EigenSpiral** [comment]
I'm researching the information in IMU data -- 3 IMU is strapped to different parts of the subject's hand, Mediapipe is used to determine the ground truth of the hand movement. For the dataset, the IMU data needs to be synchronized with the Mediapipe data, but they have different sampling rates & no common time stamps (there are time stamps for the IMU data)

**Comment by kuaashish** [comment]
Hello @EigenSpiral,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
