### ISSUE TITLE
Mediapipe models can't load on chrome extension

### ISSUE THREAD

**Issue by hongzimao** [google/mediapipe#2977]
**System information** 
- OS Platform and Distribution: M1 or intel, macOS Monterey 12.1. Chrome 96.0.4664.110.
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.9, npm @mediapipe/face_mesh version 0.4.1633559619

**Describe the problem**:
We are trying to use the latest mediapipe solutions for a chrome extension, where we import mediapipe in the extension's content script. Following the issue https://github.com/google/mediapipe/issues/2097, we have fixed the data loading problem and we believe all dependencies should be loaded correctly. However, when sending images input into mediapipe, we are hitting an error originated deep inside the compiled js (attaching a screenshot). This occurs around loading `createMediapipeSolutionsPackedAssets`. 

Just wondering if anyone has managed to get mediapipe to work with chrome extension content script? Or if there's any insight/workaround for this error? Thanks a lot for the help!
<img width="657" alt="Screen Shot 2022-01-10 at 10 00 55 PM" src="https://user-images.githubusercontent.com/5906100/148895275-bd46e9d1-c950-4c16-b6f0-becac3d36238.png">

**Comment by sgowroji** [comment]
Hi @hongzimao, Can you provide your code changes to understand the issue and steps to reproduce the above issue. Thanks!

**Comment by hongzimao** [comment]
@sgowroji thanks for following up. I believe the minimum code here is producing the same error we see: https://github.com/google/mediapipe/issues/2097#issuecomment-858414593

**Comment by hongzimao** [comment]
@sgowroji any update? The linked issue didn't get resolved after a series of investigation.

**Comment by major-mann** [comment]
Any movement on this issue?

**Comment by maccesch** [comment]
I have the same issue

**Comment by major-mann** [comment]
@maccesch 
> I have the same issue

I discovered the issue. Content scripts for chrome extensions run in their own context, and mediapipe loads additional scripts by adding script tags. Those additional scripts look for global properties which don't exist in the page context.

2 things are needed to get it working.

1. Add a trustedTypes policy (see below. This can be done from the content script)
2. Inject the primary script by adding a script tag and setting it's src

Trusted types policy (Note this is completely unrestrictive, and as such holds some risk)

```
window.trustedTypes.createPolicy('default', {
    // Mediapipe requires these for loading 
    createScriptURL: (string: string) => string,
    createScript: (script: string) => script,
});
```

**Comment by moonrailgun** [comment]
Same with @major-mann , and i have another resolution is make sure all context run in hosted page.

run `chrome.tabs.executeScript` into inject scripts  and use `web_accessible_resources` to proxy all libs.

you can checkout my repo and find how i resolve its problem in chrome extension

[become-waifu](https://github.com/moonrailgun/become-waifu)

extension part is: [here](https://github.com/moonrailgun/become-waifu/tree/master/extension)

**Comment by nico-martin** [comment]
@major-mann, do you have a working demo of your somewhere?
@moonrailgun, the link you your extensions part does not work anymore.

**Comment by moonrailgun** [comment]
> @moonrailgun, the link you your extensions part does not work anymore.

Has updated in origin comment

**Comment by kuaashish** [comment]
Hello @hongzimao,

We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you!!
