### ISSUE TITLE
Changes in ViewController.mm did not reflect in the app

### ISSUE THREAD

**Issue by vineet15889** [google/mediapipe#298]
I have configured hand-tracking example using tulsi and it working fine, but if I make any change in files it's not reflected in IPA.

**Comment by mgyong** [comment]
@vineet15889 Can you provide more info on what you actually did?

**Comment by vineet15889** [comment]
For example, if I make any changes to UIViewController file (like log some information) it does not take effect, its also not hitting the breakpoint.
