### ISSUE TITLE
What is the sampling rate of mediapipe?

### ISSUE THREAD

**Issue by EigenSpiral** [google/mediapipe#2980]
I thought the sampling rate of mediapipe would be dependent on the camera (with iPhone it should be 30fps), but an 11-second video is outputting 648 frames, is this expected?

**Comment by sgowroji** [comment]
Hi @EigenSpiral, Could you please elaborate your query with complete details. Thanks!

**Comment by EigenSpiral** [comment]
Mediapipe can extract coordinate data from videos. How many frames of coordinate data can it extract over 1 second?

**Comment by EigenSpiral** [comment]
To confirm, is the mediapipe frame rate dependant solely on the camera's framerate
