### ISSUE TITLE
Terms and Condition of use

### ISSUE THREAD

**Issue by lghasemzadeh** [google/mediapipe#2981]
Is MediaPipe free and open-sourced for industry/commercial use?
I mean is it possible for a company to use mediapipe library into their developed algorithms and then sell that as a product?
Thank you

**Comment by sgowroji** [comment]
Hi @lghasemzadeh, Have a look at this https://github.com/google/mediapipe/issues/2959#issuecomment-1008566384

**Comment by lghasemzadeh** [comment]
Hi @sgowroji I check the link you shared but I can not understand the context clearly.
Would you please help me through that. I only want to know that **is it possible or not**?
Thank you

**Comment by sgowroji** [comment]
You can refer Apache 2.0 license for further information. Thanks!
