### ISSUE TITLE
mediapipe hangs if tensorflow imported

### ISSUE THREAD

**Issue by serengil** [google/mediapipe#2986]
Hello,

I am using a mac with macOS Catalina (version 10.15.7) - intel core i7. If I import tensorflow first, then mediapipe hangs and waits. If I don't mediapipe, then it works. I write the following code to test importing and not importing tensorflow cases. 

BTW, my python version is 3.8.12 and mediapipe version is 0.8.9.1.

```
if False:
    import tensorflow as tf
    print(tf.__version__) #mine version is 2.7.0

import mediapipe as mp
import cv2

img = cv2.imread("deepface/tests/dataset/img1.jpg")

mp_face_detection = mp.solutions.face_detection

#this line prints "INFO: Created TensorFlow Lite XNNPACK delegate for CPU." if tensorflow was not imported yet
face_detector = mp_face_detection.FaceDetection( min_detection_confidence=0.6)

#this line hangs and waiting if tensorflow was imported
results = face_detector.process(img)

print(results.detections)
```

I found a similar issue [here](https://github.com/google/mediapipe/issues/1461), but it is closed because of inactivity.

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/1461#issuecomment-754868931

**Comment by serengil** [comment]
But that is not a solution, right?

**Comment by sgowroji** [comment]
Yes its known issue in MediaPipe and We don't have any resolution at present. We will keep you inform on the main thread once we found any update. Thanks!

**Comment by kuaashish** [comment]
Hello @serengil,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
