### ISSUE TITLE
Gpu examples run on ubuntu docker when creating a context with OpenGL ES 3 failed!

### ISSUE THREAD

**Issue by tuotuoshao** [google/mediapipe#2987]
**System information**
- OS Platform and Distribution : ubuntu 20.04 docker 
- Programming Language and version : c++
- Bazel version: 4.2.1
- OpenCV version : 4

**Describe the problem**:
I'm runing gpu examples on ubuntu docker, and It doesn't own a desktop, just used as a server.
At the beginning，error message is like this:
    Unable to Initialize EGLpipe!
Then, I run a command: Xvfb 0: -screen 0 1280x768x16 &, and export DISPLAY=:0, the error message changes, it's like this:
    Creating a context with OpenGL ES 3 failed: UNKNOWN:; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES3 request, 
    Fall back on OpenGL ES 2.
    Failed to run graph:; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES2 request.
I have tried many solutions in the Issues but all of them didn't work，maybe it's because I'm runing gpu examples in a docker? 
any ideas?

**Complete Logs:**
beginning error message:
![飞书20220113-170815](https://user-images.githubusercontent.com/51219602/149299774-750965af-8ae5-4975-b25e-abf2b894faba.png)
then:
![飞书20220113-172010](https://user-images.githubusercontent.com/51219602/149301805-8892a5dd-598e-424a-a22e-a7b47fba7b80.png)

**Comment by sgowroji** [comment]
Hi @tuotuoshao, Similar issue https://github.com/google/mediapipe/issues/1483#issuecomment-765811256. Did you try the workaround mentioned in it

**Comment by tuotuoshao** [comment]
> Hi @tuotuoshao, Similar issue [#1483 (comment)](https://github.com/google/mediapipe/issues/1483#issuecomment-765811256). Did you try the workaround mentioned in it

I have tried this workaround but it dosen't work!

**Comment by mcclanahoochie** [comment]
Can you also check these other related issues https://github.com/google/mediapipe/issues/932 and https://github.com/google/mediapipe/issues/840 ?
