### ISSUE TITLE
JavaScript Face Mesh multiFaceGeometry returns empty

### ISSUE THREAD

**Issue by furkandindar** [google/mediapipe#2988]
Hi,

I am using MediaPipe's FaceMesh solution in JavaScript. I am able to obtain landmarks from `multiFaceLandmarks` which returns 468 landmarks. There is also `multiFaceGeometry` array which is empty and I would like to know why it returns empty. `multiFaceGeometry` might be what I am actually intend to use because as stated in [MediaPipe Face Mesh](https://google.github.io/mediapipe/solutions/face_mesh.html) 

> The Face Geometry module moves away from the screen coordinate space towards a metric 3D space and provides necessary primitives to handle a detected face as a regular 3D object. By design, you’ll be able to use a perspective camera to project the final 3D scene back into the screen coordinate space with a guarantee that the face landmark positions are not changed.

Here is the result that I get:

![Screen Shot 2022-01-13 at 3 14 41 PM](https://user-images.githubusercontent.com/33446963/149328514-bf6570ef-677f-49ed-a8cd-889ee1112647.png)

Can you help me with this? Thanks in advance!

**Comment by furkandindar** [comment]
Hello @tyrmullen , can you provide me some info about this? Thanks in advance!

**Comment by tyrmullen** [comment]
The multiFaceGeometry API has not yet been officially released (IIRC we still need to fix its interactions with refineMesh), so really that property should simply not exist.  However, if you want to experiment with it (with no guarantees for any sort of proper behavior), then you might be able to see something if you set `enableFaceGeometry` to `true` in the options.

**Comment by furkandindar** [comment]
Thanks for your response @tyrmullen , enabling enableFaceGeometry: true makes the app crash so currently I can not experiment it.

> react_devtools_backend.js:4045 Calculator::Process() for node "facegeometryfromlandmarksandimage__FaceGeometryPipelineCalculator" failed: RET_CHECK failure (third_party/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc:128) screen_landmark_list.landmark_size() == canonical_metric_landmarks_.cols() (478 vs. 468) The number of landmarks doesn't match the number passed upon initialization!; Failed to convert landmarks from the screen to the metric space!; Failed to estimate face geometry for multiple faces! [type.googleapis.com/mediapipe.StatusList='\n\xeb\x03\x08\r\x12\xe6\x03\x43\x61lculator::Process() for node \"facegeometryfromlandmarksandimage__FaceGeometryPipelineCalculator\" failed: RET_CHECK failure (third_party/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc:128) screen_landmark_list.landmark_size() == canonical_metric_landmarks_.cols() (478 vs. 468) The number of landmarks doesn\'t match the number passed upon initialization!; Failed to convert landmarks from the screen to the metric space!; Failed to estimate face geometry for multiple faces!']
Uncaught (in promise) RuntimeError: abort(undefined) at Error
    at jsStackTrace (face_mesh_solution_simd_wasm_bin.js:9:69351)
    at stackTrace (face_mesh_solution_simd_wasm_bin.js:9:69527)
    at abort (face_mesh_solution_simd_wasm_bin.js:9:43094)
    at _abort (face_mesh_solution_simd_wasm_bin.js:9:180736)
    at face_mesh_solution_simd_wasm_bin.wasm:0x4fd04e
    at face_mesh_solution_simd_wasm_bin.wasm:0x4fcf09
    at face_mesh_solution_simd_wasm_bin.wasm:0x4fd067
    at face_mesh_solution_simd_wasm_bin.wasm:0x198ad
    at face_mesh_solution_simd_wasm_bin.wasm:0x1493c
    at SolutionWasm$send [as send] (eval at new_ (face_mesh_solution_simd_wasm_bin.js:9:161510), <anonymous>:9:1)
    at abort (face_mesh_solution_simd_wasm_bin.js:9:43125)
    at _abort (face_mesh_solution_simd_wasm_bin.js:9:180736)
    at face_mesh_solution_simd_wasm_bin.wasm:0x4fd04e
    at face_mesh_solution_simd_wasm_bin.wasm:0x4fcf09
    at face_mesh_solution_simd_wasm_bin.wasm:0x4fd067
    at face_mesh_solution_simd_wasm_bin.wasm:0x198ad
    at face_mesh_solution_simd_wasm_bin.wasm:0x1493c
    at SolutionWasm$send [as send] (eval at new_ (face_mesh_solution_simd_wasm_bin.js:9:161510), <anonymous>:9:1)
    at pa.h (face_mesh.js:67:1)
    at sa (face_mesh.js:14:1)

**Comment by tyrmullen** [comment]
That's what I was referring to when I said you'd need to leave `refineMesh` as `false` above.  The CodePen does not crash if you enable face geometry and DON'T enable mesh refinements.  So you can experiment with one or the other, but not both.

**Comment by furkandindar** [comment]
Sorry that i missed out that part, got it now, the result array didn't make any sense for me though. Thanks for the help!

**Comment by tyrmullen** [comment]
Ahh, sorry to hear that; hopefully if/when this becomes a real released feature that will no longer be the case.  And no problem!

**Comment by furkandindar** [comment]
<img width="907" alt="Screen Shot 2022-02-04 at 5 36 32 PM" src="https://user-images.githubusercontent.com/33446963/152547321-ea14050e-e6ad-4fcf-b996-95886a304136.png">

Hello again, is there any documentation for me to understand above values?  For multiFaceLandmarks it's pretty straightforward and explained in the [documentation](https://google.github.io/mediapipe/solutions/face_mesh.html#face-geometry-module).

<img width="1259" alt="Screen Shot 2022-02-04 at 5 38 00 PM" src="https://user-images.githubusercontent.com/33446963/152547776-f0cf4e90-8334-458d-a327-8a0e2004294d.png">

**Comment by YuriPoluk** [comment]
@tyrmullen any ETA for multiFaceGeometry API official release?

**Comment by webdevog** [comment]
@tyrmullen I came from this [issue](https://github.com/google/mediapipe/issues/3003) and looks like current issue has the same root. Is there any workaround maybe to be able to use refineLandmarks enabled? Or when approximately multiFaceGeometry API can be released? Thanks a lot in advance!

**Comment by tyrmullen** [comment]
Correct-- and this will likely be the next update, but there's no definite ETA at this point.

**Comment by webdevog** [comment]
@tyrmullen just to confirm: further release of multiFaceGeometry API should resolve the [issue](https://github.com/google/mediapipe/issues/3003) and we need to wait for the release. Correct? Thanks

**Comment by raphaelmenges** [comment]
I have seen that there has been an update of the face mesh module on NPM to version 0.4.1657299874 three days ago. Are any updates included regrading this issue?

**Comment by raphaelmenges** [comment]
The update seems to be gone? Now the latest version is 0.4.1633559619 again 👀

**Comment by ericljiang** [comment]
It's now 2023, any updates? Is there a different issue tracking this since this issue is closed?
