### ISSUE TITLE
Mediapipe on AI Accelerators

### ISSUE THREAD

**Issue by lghasemzadeh** [google/mediapipe#2989]
Hello,
Is it possible to run mediapipe solutions on 'Renesas V3H'? since V3H has AI accelerators instead of GPU.
https://www.renesas.com/us/en/document/fly/renesas-r-car-v3h
Thank you

**Comment by sgowroji** [comment]
Hi @lghasemzadeh, Did you encounter any error while running the MediaPipe on the above. Can you share your observation? Thanks!

**Comment by lghasemzadeh** [comment]
Hello,
I have not tested it yet. I need to purchase the chip first. But before buying that I wanted to be sure if I can run mediapipe on it or not.
Referring to the characteristics of the processor I shared its link previously, can you guide me if it will be a suitable platform for mediapipe?
Thank you

**Comment by lghasemzadeh** [comment]
Hi,
Is there any update?
I am waiting for your response.

**Comment by sgowroji** [comment]
Hi @lghasemzadeh, With the specs shared in it seems that work with MediaPipe. But we have not tested with the device.

**Comment by mcclanahoochie** [comment]
Mediapipe should run on that CPU, but I don't think Mediapipe can take advantage [yet] of any of the specialized chips on that board.

**Comment by lghasemzadeh** [comment]
> Mediapipe should run on that CPU, but I don't think Mediapipe can take advantage [yet] of any of the specialized chips on that board.
> 
> As sgowroji@ mentioned, we don't have that board for testing

Thank you so much for the answer.
What are those specialized chips?

**Comment by mcclanahoochie** [comment]
According to https://www.renesas.com/us/en/products/automotive-products/automotive-system-chips-socs the V3H does not have a GPU (see chart at bottom)

**Comment by lghasemzadeh** [comment]
> According to https://www.renesas.com/us/en/products/automotive-products/automotive-system-chips-socs the V3H does not have a GPU (see chart at bottom)

Yes, it doesn't have. This is the thing that I mentioned in the first comment, and this the reason that I opened this issue. My last question is, since there is no GPU, does any of the above AI hardware accelerators support the OpenGL ES which is the base of mediapipe?
Thank you

**Comment by mcclanahoochie** [comment]
It is unlikely that the other accelerators will run OpenGL ES.

*If* OpenGL is even supported on the board, it would be through emulation on accelerators (probably slow) or some CPU implementation such as [SwiftShader](https://github.com/google/swiftshader) (very slow). 

I think if there was an integrated GPU it would be mentioned somewhere (so likely doesn't have), but it is hard to find information on the Renesas website.

Is buying an R-car version with a known GPU (at least OpenGL ES 3.1+) not an option?
