### ISSUE TITLE
Failed to generate android AAR

### ISSUE THREAD

**Issue by HebaMohamed** [google/mediapipe#299]
Hello team, I got that error when trying to generate aar file

`.../mediapipe/mediapipe/framework/tool/BUILD:97:1: Linking of rule '//mediapipe/framework/tool:encode_as_c_string' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -lc++ -fobjc-link-runtime -Wl,-S -o bazel-out/host/bin/mediapipe/framework/tool/encode_as_c_string ... (remaining 13 argument(s) skipped)`

Using that command

`bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_hand_tracking_aar`

**Comment by billhung** [comment]
I failed doing this too. I couldn't find aar_example
