### ISSUE TITLE
Chin Side Landmarks Are Misplaced If Mouth is Opened

### ISSUE THREAD

**Issue by anappdev2** [google/mediapipe#2990]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): iOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone
- Programming Language and version ( e.g. C++, Python, Java): Objective C
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.9, 0.8.8
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ): FaceMesh / FaceEffect
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
- Xcode & Tulsi version (if issue is related to building for iOS): 

**Describe the current behavior:**
Once you open mouth the chin side landmarks don't move appropriately. If face is rotated as well (with mouth open) its even worse. Both FaceMesh and FaceEffect Solutions don't work.  

**Describe the expected behavior:**
Once user opens mouth the chin side landmarks should also move down. Also if face is rotated while mouth is open landmarks should move accordingly.

**Standalone code to reproduce the issue:**
iOS Example FaceMesh and FaceEffect

The problem is similar as [#1017](https://github.com/google/mediapipe/issues/1017) as it is closed I am opening a new one.  It's not as bad as that one but when mouth is opened the landmarks & face mask don't cover the chin area.

**Comment by sgowroji** [comment]
Hi @anappdev2, Can you share the images in which error occurred to investigate further. Thanks!

**Comment by anappdev2** [comment]
![Screenshot 2022-01-18 at 11 56 14 AM](https://user-images.githubusercontent.com/59765390/149882590-a22ab85a-cc38-4376-9f1f-b618f84adb06.png)
![Screenshot 2022-01-18 at 11 55 52 AM](https://user-images.githubusercontent.com/59765390/149882615-0835a174-0b1a-40e5-8268-9c83b8cd1f09.png)

These are couple of example images.

**Comment by roimulia2** [comment]
Same issue on our app, please advice. Thank you!

**Comment by kuaashish** [comment]
Hello @anappdev2,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by roimulia2** [comment]
Hey @kuaashish ! Thank you for the response. I'm not seeing an updated Face Mesh solution there. Is it not released yet?

**Comment by kuaashish** [comment]
@roimulia2,
Thank you for your interest in the MediaPipe solutions, Although we cannot commit any date for now, However, you should expect it to be rolled out in two weeks.

**Comment by roimulia2** [comment]
Perfect! Last question @kuaashish, if I may, will it be the same codebase for the face mesh detection as in the legacy just updated to the new infrastructure? Or should we expect improvement in the algorithms/models themselves?
