### ISSUE TITLE
Object Detection solution

### ISSUE THREAD

**Issue by arnitkun** [google/mediapipe#2993]
Hi!

Can anyone point me the way as to how one would be building something like one of the "solutions" for the object detection on desktop?

I have seen a couple of issues but they seem to be lacking information as to how one would do it themselves since it is not available as one.

P.S. : Also if someone could point me as to how to use the mediapipe graphs, that would be great. I have recently come across the framework.

**Comment by sgowroji** [comment]
For object detection on C++ you can find the documentation from here https://google.github.io/mediapipe/solutions/object_detection#live-camera-input
