### ISSUE TITLE
How to buuld a .aar file like 'com.google.mediapipe:hands:latest.release'

### ISSUE THREAD

**Issue by huangandy** [google/mediapipe#2994]
Hi ,

I got a tutorial for building a model from graph

but I want to build an aar like the solution example one

How should I design my BUILD file to announce the android_library source with "hands" or "soluttion_core" ?

Then generate an aar like "https://mvnrepository.com/artifact/com.google.mediapipe"

**Comment by sgowroji** [comment]
Hi @huangandy, Please go through this  MediaPipe Android [Solutions](https://google.github.io/mediapipe/getting_started/android_solutions.html#mediapipe-android-solutions. ) You can find hands [source](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions/hands) code .

**Comment by huangandy** [comment]
Hi @sgowroji ,

Yes, I just saw this source and used it.

This project use gradle include from maven,

but I want to build this AAR myself with same functions.

How should I do? I found a lot tutorial to make hands detect(only set "mobile caculator" in BUILD) but not the same as the one in the example source.

**Comment by sgowroji** [comment]
We have very clear steps to build Android AAR here https://google.github.io/mediapipe/getting_started/android_archive_library.html

**Comment by emad-eldeen** [comment]
@huangandy

**Comment by huangandy** [comment]
> @huangandy
> I understand why you asked this question. I am trying to do the same.
> The documentation on how to create an AAR won't lead to generating one like the one in the maven repository.
> Did you manage to generate it?

No….I just gave up.

**Comment by emad-eldeen** [comment]
I was able to generate the solution_core aar with bazel build --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/java/com/google/mediapipe/solutioncore:solution_core
I am still trying with hands aar

**Comment by haoXu1990** [comment]
> I was able to generate the solution_core aar with bazel build --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/java/com/google/mediapipe/solutioncore:solution_core I am still trying with hands aar

@emad-eldeen 
hi,  How to compile hands AAR

**Comment by RepublicOfKorokke** [comment]
Can this help you?

build params are refered from https://google.github.io/mediapipe/getting_started/android_archive_library.html
and https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/solutions/hands/BUILD#L18

```
bazel build -c opt --strip=ALWAYS \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    --legacy_whole_archive=0 \
    --features=-legacy_whole_archive \
    --copt=-fvisibility=hidden \
    --copt=-ffunction-sections \
    --copt=-fdata-sections \
    --copt=-fstack-protector \
    --copt=-Oz \
    --copt=-fomit-frame-pointer \
    --copt=-DABSL_MIN_LOG_LEVEL=2 \
    --linkopt=-Wl,--gc-sections,--strip-all \
    //mediapipe/java/com/google/mediapipe/solutions/hands:hands.aar
```

**Comment by haoXu1990** [comment]
> Can this help you?
> 
> Build parameters referenced from https://google.github.io/mediapipe/getting_started/android_archive_library.html and https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/solutions/hands/BUILD#L18
> 
> ```
> bazel build -c opt --strip=ALWAYS \
>     --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
>     --fat_apk_cpu=arm64-v8a,armeabi-v7a \
>     --legacy_whole_archive=0 \
>     --features=-legacy_whole_archive \
>     --copt=-fvisibility=hidden \
>     --copt=-ffunction-sections \
>     --copt=-fdata-sections \
>     --copt=-fstack-protector \
>     --copt=-Oz \
>     --copt=-fomit-frame-pointer \
>     --copt=-DABSL_MIN_LOG_LEVEL=2 \
>     --linkopt=-Wl,--gc-sections,--strip-all \
>     //mediapipe/java/com/google/mediapipe/solutions/hands:hands.aar
> ```

hi, thk,  you solution to my problem
