### ISSUE TITLE
Mediapipe on AWS

### ISSUE THREAD

**Issue by sushma-snk** [google/mediapipe#2998]
I have been using mediapipe for pose estimation (python). I would like to integrate pose estimation with existing android app on aws. Would opencv and mediapipe charge a lot when installed on aws? If so, may  know the charges please?
Thanks in advance.

**Comment by sgowroji** [comment]
Hi @sushma-snk, MediaPipe won't charge people.
AWS would charge them.

**Comment by sushma-snk** [comment]
Sure, Thank you @sgowroji
