### ISSUE TITLE
Can't use Hand Tracking library. Bitcode not enabled in the static .a

### ISSUE THREAD

**Issue by schumy** [google/mediapipe#300]
Hi all,

I'm having some issues compiling the library for iOS. Currently when using the project of the library(so not the app one), the static .a that I get after it can't be included in my project because it seems that bitcode is not enabled. I checked the target(I'm using the hand tracking library) and bitcode seems enabled but for some reason, the outcome has not bitcode and thus, can't be used. 
Anybody else facing the same issue?

**Comment by HebaMohamed** [comment]
Yes I faced that issue too before, cannot import any thing in the new project after importing the .a and even .framework

**Comment by schumy** [comment]
@HebaMohamed I understand then that you haven't been able to resolve it?

**Comment by HebaMohamed** [comment]
@schumy yes unfortunately I didn't, so for a demo purpose I moved to android aar option

**Comment by juanapp** [comment]
Any update on this? I still can't run it...

**Comment by fenollp** [comment]
Did you try using an `ios_framework` target?
See https://github.com/bazelbuild/rules_apple/blob/master/doc/frameworks.md

**Comment by ottijp** [comment]
How about adding `--copt=-fembed-bitcode` to build command?
