### ISSUE TITLE
ERROR:Compiling src/qc8-gemm/gen/1x8c4-minmax-fp32-neondot.c failed: (Exit 1): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target ... (remaining 86 argument(s) skipped)

### ISSUE THREAD

**Issue by PixelChen24** [google/mediapipe#3000]
- OS Platform and Distribution :Ubuntu18.04
- Bazel version: 4.2.1
- Android SDK API32; NDK 18.1

I am trying to compile the Android project using bazel, I run this command:
``bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu``
After processing for several minutes, I got this error:
``
ERROR: /home/chen/.cache/bazel/_bazel_chen/97f729a8801dcbd476fe5b1b4e67c85d/external/XNNPACK/BUILD.bazel:7071:19: Compiling src/qc8-gemm/gen/1x8c4-minmax-fp32-neondot.c failed: (Exit 1): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target ... (remaining 86 argument(s) skipped)
``

**Comment by sgowroji** [comment]
Hi @PixelChen24, Could you please confirm , as you followed all the steps mentioned here  https://google.github.io/mediapipe/getting_started/android.html#building-android-example-apps-with-bazel

**Comment by PixelChen24** [comment]
> 

Yes, I followed every step in this tutorial

**Comment by PixelChen24** [comment]
> Hi @PixelChen24, Could you please confirm , as you followed all the steps mentioned here https://google.github.io/mediapipe/getting_started/android.html#building-android-example-apps-with-bazel

Yes, I followed every step in this tutorial

**Comment by sgowroji** [comment]
Can you try this https://github.com/google/mediapipe/issues/2636#issuecomment-937981139

**Comment by PixelChen24** [comment]
> Can you try this https://github.com/google/mediapipe/issues/2636#issuecomment-937981139

Thank you for your suggestion, but both my sdk version(31) and ndk version(18) have satisfied the requirement

**Comment by sgowroji** [comment]
You can try Android Hands [Gradle](https://google.github.io/mediapipe/solutions/hands#android-solution-api) API solutions . If you have problem in building the above solution.
