### ISSUE TITLE
@mediapipe/camera_utils doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module

### ISSUE THREAD

**Issue by simlevesque** [google/mediapipe#3002]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):  Linux Ubuntu 21.10
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Javascript
- [MediaPipe version](https://github.com/google/mediapipe/releases): @mediapipe/camera_utils@0.3.1640029074 and @mediapipe/drawing_utils@0.3.1620248257

**Describe the problem**:
I'm getting the warnings in my console when compiling using esbuild/vite:
**Complete Logs:**
```
@mediapipe/camera_utils doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
@mediapipe/drawing_utils doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
```
  vite v2.7.10 dev server running at:

  > Local: http://localhost:8080/
  > Network: use `--host` to expose

  ready in 1210ms.

7:42:32 p.m. [vite] new dependencies found: json-stringify-deterministic, @mediapipe/drawing_utils, updating...
@mediapipe/camera_utils doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
@mediapipe/drawing_utils doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix
```

**Comment by sgowroji** [comment]
Hi @simlevesque, Can you share your code changes and steps to reproduce the issue at our end. Thanks!

**Comment by tyrmullen** [comment]
I have no experience with esbuild/vite, so reassigning this one.
