### ISSUE TITLE
@mediapipe/facemesh with refineLandmarks crashes if used as npm module instead of script from cdn

### ISSUE THREAD

**Issue by YuriPoluk** [google/mediapipe#3003]
When imported from npm module facemesh doesn't work with refineLandmarks: true, same code works perfectly if facemesh script is downloaded from cdn as in the demo. Here's full log

geometry_pipeline.cc:128] generic::internal: RET_CHECK failure (third_party/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc:128) screen_landmark_list.landmark_size() == canonical_metric_landmarks_.cols() (478 vs. 468) The number of landmarks doesn't match the number passed upon initialization!

Calculator::Process() for node "facegeometryfromlandmarksandimage__FaceGeometryPipelineCalculator" failed: RET_CHECK failure (third_party/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc:128) screen_landmark_list.landmark_size() == canonical_metric_landmarks_.cols() (478 vs. 468) The number of landmarks doesn't match the number passed upon initialization!; Failed to convert landmarks from the screen to the metric space!; Failed to estimate face geometry for multiple faces! [type.googleapis.com/mediapipe.StatusList='\n\xeb\x03\x08\r\x12\xe6\x03\x43\x61lculator::Process() for node \"facegeometryfromlandmarksandimage__FaceGeometryPipelineCalculator\" failed: RET_CHECK failure (third_party/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc:128) screen_landmark_list.landmark_size() == canonical_metric_landmarks_.cols() (478 vs. 468) The number of landmarks doesn\'t match the number passed upon initialization!; Failed to convert landmarks from the screen to the metric space!; Failed to estimate face geometry for multiple faces!']

**Comment by sgowroji** [comment]
Hi @YuriPoluk, Could you please share your code changes to reproduce the issue. Thanks!

**Comment by YuriPoluk** [comment]
Here's minimal code required to reproduce the issue

`import * as facemesh from "@mediapipe/face_mesh";

init()

async function init() {
  const config = {
    locateFile: (file) => {
      return `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@${facemesh.VERSION}/${file}`
    }
  }

  const solutionOptions = {
    selfieMode: true,
    enableFaceGeometry: true,
    maxNumFaces: 1,
    refineLandmarks: true,
    minDetectionConfidence: 0.5,
    minTrackingConfidence: 0.5
  }
  
  const faceMesh = new facemesh.FaceMesh(config);
  faceMesh.setOptions(solutionOptions);
  faceMesh.onResults(()=>{})
  await faceMesh.initialize()

  const element = document.getElementsByClassName('cam')[0]
  element.width = 512
  element.height = 512
  
  const stream = await navigator.mediaDevices.getUserMedia({video: { width: 512, height: 512 }})
  element.srcObject = stream
  element.onloadedmetadata = () => {
    element.play()
    faceMesh.send({image: element})
  }
}`

**Comment by kdementiev-reinvently** [comment]
I have the same issue as @YuriPoluk 

Example from CodePan working fine, but when I connect **@mediapipe/face_mesh** package to my Vue.JS application and activate refineLandmarks - something crashing inside of the package.

In my project I'm using latest version of **@mediapipe/selfie_segmentation** and **@mediapipe/face_mesh**.

PS. Also, there is no any good documentation or examples using **@mediapipe** packages in TypeScript projects.

**Comment by webdevog** [comment]
Hi! The same issue here, everything works great with cdn but when used as npm module and refineLandmarks turned on. Crash logs are the same as provided by @YuriPoluk

**Comment by raphaelmenges** [comment]
I am using the NPM version 0.4.1633559619 of [@mediapipe/face_mesh](https://www.npmjs.com/package/@mediapipe/face_mesh) as well and for me either `refineLandmarks` or `enableFaceGeometry` can be activated at once, but not both at once. If I set both to `true`, face mesh crashes:

```
geometry_pipeline.cc:128] generic::internal: RET_CHECK failure (third_party/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc:128) screen_landmark_list.landmark_size() == canonical_metric_landmarks_.cols() (478 vs. 468) The number of landmarks doesn't match the number passed upon initialization!
```

**Comment by webdevog** [comment]
Guys, it is still an issue for me. Any updates or do you need some more information? Please help

**Comment by tyrmullen** [comment]
Just to confirm: multiFaceGeometry hasn't been officially released yet, in large part because it does not yet work with refineLandmarks.  So this is expected behavior for now.  Further discussion will continue on #2988.
