### ISSUE TITLE
Custom Object Detection Model Clarity

### ISSUE THREAD

**Issue by jen-co** [google/mediapipe#3007]
## URL(s) with the issue:
https://github.com/google/mediapipe/tree/master/mediapipe/models/object_detection_saved_model

## Description of issue (what needs changing):

It would be useful for the guide on custom training an object detection model and exporting it for TFLite purposes to be updated for Tensorflow 2. And in the same breath to make it clear that the current documentation applies to TF 1 (also which version of TF1 and python would be useful). This was a source of quite a lot of confusion for me initially.

In any case I ended up following the [tutorial](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193) linked in the documentation but it is quite outdated - some of the links are broken and trying to run it on the Google Cloud platform has been problematic (gave up trying to get it to run as the only TF1 and python options currently available are 1.15.0 and Python3.7 which for some reason didn't seem to work with the object detection examples - was getting strange numpy version mismatch errors). I have however managed to get this running on Google Colab with Tensorflow 1.15.2 and python 3.7 (i,e the transfer learning and exporting to tflite) but it would be useful to be able to leverage TF2, especially as TF1 seems to be getting deprecated in more and more places.

The problem I am facing with TF2 is that it no longer supports the export_tflite_ssd_graph function. Instead, I see in a few places that it is recommended to use export_tflite_graph_tf2, and this function no longer has the option to turn off post-processing. What is the suggested workflow with mediapipe for a model exported in this way (i.e. without --add_postprocessing_op=False)? Or is this not yet an option? 

Thanks in advance!

**Comment by sgowroji** [comment]
Hi @jen-co,  Could you please  share us  the list of broken links which are not working. Thanks!

**Comment by jen-co** [comment]
Thank you for the quick response.
List of broken links in the [mediapipe object detection info](https://github.com/google/mediapipe/tree/master/mediapipe/models/object_detection_saved_model):
- https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md 
- https://www.tensorflow.org/lite/convert/cmdline_examples

List of broken links in the [linked tutorial](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193):
- https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md
-https://colab.research.google.com/github/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb
- https://www.tensorflow.org/mobile/tflite/
- https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md
- https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/toco
- https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/g3doc/cmdline_reference.md

For most of these links its possible to find where they exist now so missing links are a minor part of the need for clarity in the info. I think the most useful is info on which versions of tensorflow and python are needed. Additionally, as mentioned more info on how to go about doing this for TF2.

Thanks again

**Comment by sgowroji** [comment]
Hi @jen-co, [Tf1](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md) Version of Tensorflow is needed  and we also updated our docs which you see the  updated changes in the next release.  Reach us back if you still have any query w.r.t the above.

**Comment by Conru1** [comment]
https://developers.google.com/mediapipe/api/solutions
https://developers.google.com/mediapipe/api/solutions/java/com/google/mediapipe/tasks/vision/objectdetector/ObjectDetector
I see that the new Mediapipe task API in the link above uses TF2 style object detection models with four outputs.

Will this change the answer given above by @sgowroji ? Will you be able to use TF2 object detection models sometime in the future?
