### ISSUE TITLE
mediapipe low FPS

### ISSUE THREAD

**Issue by CYChuang** [google/mediapipe#3009]
Hello everyone:
We use mediapipe build a project like video
[https://drive.google.com/file/d/1rRrlYNVcPWF70FS-Ux69YmX5hqBWyVxt/view?usp=sharing](url)
However the FPS is very low.
We want to know it's the mediapipe's problem or we can fix it by other solution.
If someone know how to slove it, please tell me thanks.

**Comment by sran-ranvir** [comment]
How can i change the thickness of drawing utility below 1 ! i want something like 0.2 ????

**Comment by ahmadyan** [comment]
You need to share more details about what's happening here, what is the fps you are getting and more importantly what device are you using. Which graph you are using, what type of delegate you are using in the background (cpu/xnn, gpu with OpenGL/OpenCL). Try running our reference implementation and you should see over 30fps on standard devices (e.g. Pixel-3 afterward).
