### ISSUE TITLE
Linker error when trying to utilise OpenCV objdetect module

### ISSUE THREAD

**Issue by Kazanian2** [google/mediapipe#3010]
Hi,

I'm working on an Android app which uses MediaPipe for several tasks. Now, I have added my own MediaPipe calculator which uses CascadeClassifier of OpenCV. Building MediaPipe with this new calculator worked fine, but when starting the Android app, I get following linker error:

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN2cv17CascadeClassifier16detectMultiScaleERKNS_11_InputArrayERNSt6__ndk16vectorINS_5Rect_IiEENS4_9allocatorIS7_EEEEdiiNS_5Size_IiEESD_" referenced by "/data/app/~~z2vi__sniDuC2OkNu0_Fnw==[...]==/lib/arm64/libmediapipe_jni.so"...
```

The call in the calculator looks like this:

```
cv::Mat grayscale_view;
cv::cvtColor(input_view, grayscale_view, cv::COLOR_RGB2GRAY);
std::vector<cv::Rect> rect;
cascadeClassifier.detectMultiScale(grayscale_view, rect, 1.3, 5);
```

CascadeClassifier is part of OpenCV's objdetect module, so this is added to OPENCV_MODULES in the file /third_party/BUILD

I already tried clearing the bazel-bin and bazel-out folders and building MediaPipe anew. Also, the build folders of the Android app have been deleted. But I always get this linker error.

By unzipping the MediaPipe aar file that is used by the Android app, I could open libmediapipe_jni.so in a text editor and the string from the error message is present:
```
_ZN2cv17CascadeClassifier16detectMultiScaleERKNS_11_InputArrayERNSt6__ndk16vectorINS_5Rect_IiEENS4_9allocatorIS7_EEEEdiiNS_5Size_IiEESD_
```

In libopencv_java3.so this exact string is not present, but some entries containing detectMultiScale can be found.

Can you please give me any advice on this? I have been searching for days now and don't know how to fix this.
Thanks in advance!

**Comment by sgowroji** [comment]
@Kazanian2 , Did you get a chance to refer this duplicate issue https://github.com/google/mediapipe/issues/1224

**Comment by Kazanian2** [comment]
I already tried adding "api_level = 21" in the WORKSPACE file and rebuilding MediaPipe but still get the same error

**Comment by Kazanian2** [comment]
I changed the code to call other functions of CascadeClassifier. There are no linker errors when using getFeatureType() or empty(), but detectMultiScale does not work. I investigated the entries in libopencv_java3.so and libmediapipe_jni.so. There are some differences:

``
libopencv_java3.so:
detectMultiScaleERKNS_11_InputArrayERSt6vectorINS_5Rect_IiEESaIS6_EERS4_IiSaIiEEdiiNS_5Size_IiEESE_

libmediapipe_jni.so:
detectMultiScaleERKNS_11_InputArrayERNSt6__ndk16vectorINS_5Rect_IiEENS4_9allocatorIS7_EEEEdiiNS_5Size_IiEESD_
``

Can you make something out of this?

**Comment by Kazanian2** [comment]
Any suggestions?

**Comment by Kazanian2** [comment]
???

**Comment by Kazanian2** [comment]
push

**Comment by Kazanian2** [comment]
Any help, please?

**Comment by jiuqiant** [comment]
Seems like the different symbols are caused by building mediapipe and opencv android libraries with different ndk and sdk versions. A possible solution is to build mediapipe and opencv into the same dynamic library by following https://github.com/google/mediapipe/issues/2105#issuecomment-905689538

**Comment by Kazanian2** [comment]
Thank you @jiuqiant ! That did the trick. I was able to rebuild it that way and run it without linker errors.
