### ISSUE TITLE
Install Hello World but crashed with: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### ISSUE THREAD

**Issue by zhiheng-ldj** [google/mediapipe#3011]
**System information** (Please provide as much relevant information as possible)
- Docker built with https://google.github.io/mediapipe/getting_started/install.html. 
- Device with Android 7.1.2.

**Describe the problem**:

I am using docker to build apps followed by https://google.github.io/mediapipe/getting_started/install.html. 
I am trying to deploy helloworld application.
I tried to build app with :
bazel build -c opt --config=android_arm64 $APPLICATION_PATH:helloworld
and it worked.
Then I connect the device with adb connect.
Then I tried to install it with :
adb install bazel-bin/$APPLICATION_PATH/helloworld.apk
and it crashed.

**Complete Logs:**

$ adb install bazel-bin/$APPLICATION_PATH/helloworld.apk
adb: failed to install bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/helloworld.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

**Comment by sgowroji** [comment]
@zhiheng-ldj, Did you check this https://github.com/google/mediapipe/issues/1402
