### ISSUE TITLE
Face Mesh Effect Samples for Web

### ISSUE THREAD

**Issue by htorrendell** [google/mediapipe#3014]
Hi, 

I was wondering if there are plans to make public for web platform the Face Mesh Renderer Effects that are currently available on Mobile. Are these technically compatible with Web JS?

![face_geometry_renderer](https://user-images.githubusercontent.com/10697832/150849496-5c40da4a-629e-41a0-92d6-f7a0031b8adb.gif)

Thanks!

**Comment by sgowroji** [comment]
Hi @htorrendell, Marking it as duplicate of https://github.com/google/mediapipe/issues/2750#issuecomment-964444032

**Comment by htorrendell** [comment]
Hey @sgowroji, apologies for the duplicate. Thanks for noting.
