### ISSUE TITLE
How to add AR effects to agumented face?

### ISSUE THREAD

**Issue by kyung645** [google/mediapipe#3019]
Hi, 

On the https://google.github.io/mediapipe/solutions/face_mesh.html page, the demo gif with the three people show animation effects like snowing or sweating on sunny day. But there is no documentation about how to add these kinds of animations? Would you happen to have any suggestions on how to accomplish such animation effects as seen in that demo gif on the face mesh page? Thanks so much.

https://google.github.io/mediapipe/images/face_mesh_ar_effects.gif

**Comment by sgowroji** [comment]
Hi @kyung645, We don't have Examples for AR effects for your above query. But you can build them from here by referring this https://google.github.io/mediapipe/solutions/face_mesh#face-effect-example. You can choose graph or other platforms like android or IOS to build one.
