### ISSUE TITLE
Examples (object_detection) using tensorflow calculators on macOS/Apple does not compile

### ISSUE THREAD

**Issue by ksachdeva** [google/mediapipe#302]
I tried to run the object detection using tensorflow example on macOS and it did not compile.

The compilation errors are because of conflicting usage of conditions in bazel. for eg. 

in mediapipe/calculcators/util/BUILD (see below) you have both "apple" and "macos"

```
cc_library(
    name = "detection_label_id_to_text_calculator",
    srcs = ["detection_label_id_to_text_calculator.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":detection_label_id_to_text_calculator_cc_proto",
        "//mediapipe/framework/formats:detection_cc_proto",
        "//mediapipe/framework/port:status",
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework:packet",
        "//mediapipe/util:resource_util",
    ] + select({
        "//mediapipe:android": [
            "//mediapipe/util/android/file/base",
        ],
        "//mediapipe:apple": [
            "//mediapipe/util/android/file/base",
        ],
        "//mediapipe:macos": [
            "//mediapipe/framework/port:file_helpers",
        ],
        "//conditions:default": [
            "//mediapipe/framework/port:file_helpers",
        ],
    }),
    alwayslink = 1,
)
```

and bazel give errors like following -

```
ERROR: Analysis of target '//mediapipe/examples/desktop/object_detection:object_detection_tensorflow' failed; build aborted:

/Users/ksachdeva/Desktop/Dev/exp/mediapipe/mediapipe/calculators/util/BUILD:288:1: Illegal ambiguous match on configurable attribute "deps" in //mediapipe/calculators/util:detection_label_id_to_text_calculator:
//mediapipe:apple
//mediapipe:macos
Multiple matches are not allowed unless one is unambiguously more specialized.
```

##

This happened for with following files :

mediapipe/framework/profiler/BUILD
mediapipe/util/BUILD
mediapipe/calcluators/util

I do not know/understand bazel enough but I commented (mostly guess work) one of the "apple" or "macos" in these files and this made the example compiled (and run as well).

**Comment by jiuqiant** [comment]
It's due the incompatibality bewteen MediaPipe and Bazel 1.2.1. We are working on a fix. The temporally workaround is to downgrade Bazel to 1.1.0. See the step 3 option 1 of the [instruction](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-macos).

**Comment by ksachdeva** [comment]
Apologies for the unintended noise. here is what happened -

I did install bazel 1.1.0 and successfully used for other examples. It seems that before trying the tensorflow example I must have done `brew update` which replaced 1.1.0 with 1.2.X

To confirm :

I uninstalled the one from brew and tensorflow object detection on osx is compiling. 

Regards & thanks
Kapil
