### ISSUE TITLE
How can I get coordinate from Packet <mediapipe::Detection>> ????

### ISSUE THREAD

**Issue by MinHyeong-Lee** [google/mediapipe#3021]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): **Yes. It is my custom code.**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): **Linux Ubuntu 18.04**
- [MediaPipe version](https://github.com/google/mediapipe/releases): **0.8.9**
- Bazel version: **4.2.1**
- Solution (e.g. FaceMesh, Pose, Holistic): **Face Detection**
- Programming Language and version ( e.g. C++, Python, Java): **C++**

**Describe the expected behavior:**

**Standalone code you may have used to try to get what you need :**

I want to get result coordinates of Face Detection.
I appended a little in my code.

1. face_detection_full_range_desktop_live.pbtxt
![image](https://user-images.githubusercontent.com/48749902/151323812-bc97a93d-fa34-4319-aae7-fe01e95a28af.png)
Just add output_stream: "detections"

2. my code 
![image](https://user-images.githubusercontent.com/48749902/151321988-07772d36-6a12-4f3a-a0d3-3edc3a7ef0b1.png)

![image](https://user-images.githubusercontent.com/48749902/151322144-74def40d-dc48-4049-a30c-90b92eab1133.png)

3. Result
![image](https://user-images.githubusercontent.com/48749902/151322245-74440598-1eb5-47e1-8d82-b6b32e9d167f.png)

I can now print the coordinates to the terminal.
I want to parse that DebugString and use it as a variable in my code.

How can I parse that result stream DebugString() and use it as variable??

example ) 
result = Parse(DebugString());

std::cout << "xmin : " << result[0].xmin

Thanks for reading.

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment]
Hello @MinHyeong-Lee,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
