### ISSUE TITLE
question about One Euro Filter

### ISSUE THREAD

**Issue by likefxz2009** [google/mediapipe#3022]
I first use the OneEuroFilter code in https://github.com/jaantollander/OneEuroFilter with python, and then use the OneEuroFilter code in mediapipe. But I find the difference of the two implementations:
in mediapipe:
use  ( x - lastRawValue)
![image](https://user-images.githubusercontent.com/19486844/151334588-d475eead-4c77-4e1f-b328-7206cb4abfa4.png)
https://github.com/google/mediapipe/blob/master/mediapipe/util/filtering/one_euro_filter.cc
in jaantollander:
use (x - lastValue)
![image](https://user-images.githubusercontent.com/19486844/151334769-b14983ed-8bab-44bc-ba6d-b1ed738561d0.png)

so i check the thesis：
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/19486844/151335432-4becd2c6-97d4-47ec-90bd-22eb17fbc3d3.png)
which use ( x - hatxprev), same as jaantollander's code.
so I want to know why you use lastRawValue not lastValue?

**Comment by sgowroji** [comment]
Hi @likefxz2009, Could you please elaborate your use case with the above query. Thanks!
