### ISSUE TITLE
Inverse matrix cannot be calculated

### ISSUE THREAD

**Issue by mgarbade** [google/mediapipe#3023]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code: yes
- OS Platform and Distribution: Android 10
- Mobile device: Huawei P30 Pro
- Programming Language and version: C++
- [MediaPipe version]: v0.8.8 commit: cf101e6 from 2021-11-13 05:10
- Bazel version: 3.7.2
- Solution: Pose
- NDK version: 21.3.6528147
- SDK version: 30.0.3

**current behavior:**
Our app using mediapipe runs fine on many Android devices, but on a particular device (Huawei P30 Pro), we get the following error:

```
2022-01-24 13:39:26.259 24512-24728/org.aisc.ailib.example.app_example_2 E/FrameProcessor: Mediapipe error: 
    com.google.mediapipe.framework.MediaPipeException: internal: Graph has errors: 
    Calculator::Process() for node "poselandmarkgpu__poselandmarkbyroigpu__poselandmarksandsegmentationinverseprojection__InverseMatrixCalculator" failed: ; Inverse matrix cannot be calculated.le_mediapipe/mediapipe/calculators/util/inverse_matrix_calculator.cc:38) 
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:395)
```
The app crashes after throwing the above mentioned error.   

We found two fixes for mediapipe to prevent the app from crashing. You can check them in my forked mediapipe repository
    [here](https://github.com/mgarbade/mediapipe/commits/fix_cannot_invert_matrix_bug)

The fix, prevents the app from crashing the detected pose now becomes weird and sometimes gets lost for a couple of seconds. Sometimes the detection "catches itself" again after a while but sometimes it's also gone forever. However the detection accuracy on the above mentioned smartphones still differs significantly from that  on other devices. It is unclear why this bug only appears on some devices. The bug appears also if instead of the live camera feed we input frames from a prerecorded video.   

**expected behavior:**
Mediapipe's pose detection accuracy should work similar on different devices with video frames as the input.

**Standalone code to reproduce the issue:**
not possible. we test it inside our own app, but the error clearly comes from mediapipe as it should not be possible that the app crashes entirely no matter what the input images to the mediapipe graph look like

**Other info / Complete Logs :**
... not sure what to put here, can update this section on demand...

**Comment by sgowroji** [comment]
Thanks for sharing us complete details of the above issue with with fixes. Our engineer team will review it and will let you know the status on the same.

**Comment by alexiscatnip** [comment]
Just had a similar error on windows. 

windows, python 3.7, mediapipe pose model complexity 1

WARNING: Logging before InitGoogleLogging() is written to STDERR
E20220625 02:25:20.911455 32260 calculator_graph.cc:804] INTERNAL: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "poselandmarkbyroicpu__poselandmarksandsegmentationinverseprojection__InverseMatrixCalculator" failed: ; Inverse matrix cannot be calculated.tors/util/inverse_matrix_calculator.cc:38)

**Comment by jonmatthis** [comment]
I run into the same error as @alexiscatnip  with Windows, Python 3.7, model complexity 2

**Comment by kuaashish** [comment]
Hello @mgarbade,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
