### ISSUE TITLE
JavaScript Libraries Lack API Documentation

### ISSUE THREAD

**Issue by rvadhavk** [google/mediapipe#3026]
## URL(s) with the issue:
https://google.github.io/mediapipe/getting_started/javascript.html

## Description of issue (what needs changing):
The docs only contain examples but no API documentation listing methods and type signatures for libraries such as drawing_utils.js and face_mesh.js.  Also, there doesn't seem to be JS/TS code in this repository, and the JS available on jsdelivr is minified.

**Comment by sgowroji** [comment]
Please go through our present javascript documentation https://google.github.io/mediapipe/getting_started/javascript#mediapipe-in-javascript

**Comment by rvadhavk** [comment]
@sgowroji I visited those links and didn't find any API documentation listing methods and type signatures, just usage examples.

**Comment by sgowroji** [comment]
Thank you for the details. We have shared your request to the team, who will assist on your above queries.

**Comment by thgpddl** [comment]
![image](https://user-images.githubusercontent.com/48787805/169657751-cbe21f5b-e899-43c7-a543-c04339d07a19.png)

# When I click on your link, the site that opens is as shown, not the JavaScript api document

**Comment by kuaashish** [comment]
Hello @rvadhavk,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
