### ISSUE TITLE
Success Installed APP crashed on device

### ISSUE THREAD

**Issue by zhiheng-ldj** [google/mediapipe#3027]
Hi I am trying to deploy object detection app on device with CPU.

**Other info / Complete Logs :**
I am using:
bazel build -j 1 -c opt --config=android_arm 

**mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu:objectdetectioncpu**

to build and 

**adb install bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu/objectdetectioncpu.apk**

to install. And they succeed.

When I trying to use it on device, it will crash. What my be the reason?

Thanks!

**Comment by zhiheng-ldj** [comment]
I have tried hello world (edge detection) and it works perfectly. I have tried facedetectioncpu and it crashed as before.

Thanks for your help!

**Comment by sgowroji** [comment]
Hi @zhiheng-ldj, Can you provide  complete error logs to understand the issue. Thanks!

**Comment by zhiheng-ldj** [comment]
> Hi @zhiheng-ldj, Can you provide complete error logs to understand the issue. Thanks!

Hi, can I get the error log in my android device? It seems all good in my host~

**Comment by sgowroji** [comment]
Yes follow this to get the bug report https://developer.android.com/studio/debug/bug-report in android device.

**Comment by zhiheng-ldj** [comment]
> Yes follow this to get the bug report https://developer.android.com/studio/debug/bug-report in android device.

Hi I got it, is it like this?

--------- beginning of crash
01-28 16:35:02.485  1497  1497 E AndroidRuntime: FATAL EXCEPTION: main
01-28 16:35:02.485  1497  1497 E AndroidRuntime: Process: com.google.mediapipe.apps.facedetectioncpu, PID: 1497
01-28 16:35:02.485  1497  1497 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.google.mediapipe.apps.facedetectioncpu-1/lib/arm/libmediapipe_jni.so"...
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1562)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at com.google.mediapipe.apps.basic.MainActivity.<clinit>(MainActivity.java:59)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2563)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2732)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6141)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
01-28 16:35:02.485  1497  1497 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
01-28 16:35:02.488   478   998 W ActivityManager:   Force finishing activity com.google.mediapipe.apps.facedetectioncpu/com.google.mediapipe.apps.basic.MainActivity
01-28 16:35:02.490   478   998 W ActivityManager:   Force finishing activity com.google.mediapipe.apps.facedetectioncpu/com.google.mediapipe.apps.basic.MainActivity
01-28 16:35:02.490   478   998 W ActivityManager: Duplicate finish request for ActivityRecord{85ed21b u0 com.google.mediapipe.apps.facedetectioncpu/com.google.mediapipe.apps.basic.MainActivity t4 f}
01-28 16:35:02.492  1497  1497 I Process : Sending signal. PID: 1497 SIG: 9
01-28 16:35:02.515   478   998 I ActivityManager: Process com.google.mediapipe.apps.facedetectioncpu (pid 1497) has died

Thanks!

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/1224. Update your changes with https://github.com/google/mediapipe/issues/1224#issuecomment-745190852

**Comment by zhiheng-ldj** [comment]
> Duplicate #1224. Update your changes with [#1224 (comment)](https://github.com/google/mediapipe/issues/1224#issuecomment-745190852)

Hi,

Thanks for your help! It works perfectly.

BTW I have a question:

**Can I add some functions (written by python for example) based on the apps? How should I do these developments?**

Thanks?!

**Comment by sgowroji** [comment]
@zhiheng-ldj, May be you can write some rest API's on python and use same to call them on Android. Again that goes with your business requirement. You can check those queries in our slack channel  (https://mediapipe.slack.com/) where you get help from the MediaPipe community members.
