### ISSUE TITLE
How to rotate the camera's previewframe with the screen orientation

### ISSUE THREAD

**Issue by Ijustakid** [google/mediapipe#3028]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): havent
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy Tab S7
- Programming Language and version ( e.g. C++, Python, Java): Java
- [MediaPipe version](https://github.com/google/mediapipe/releases): newest
- Bazel version (if compiling from source): No
- Solution ( e.g. FaceMesh, Pose, Holistic ): Hands
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): Android Studio Arctic Fox | 2020.3.1 
 compileSdkVersion 30
- Xcode & Tulsi version (if issue is related to building for iOS):

**Describe the current behavior:**
When the pad is placed landscape, neither the preview nor the camera frame is rotated.

I modified androidmanifest.xml: 
<activity android:screenOrientation="unspecified"
android:configChanges="orientation|screenSize">

Although all the views are displayed landscape, the camera frames are still portrait.

This prevents me from doing the later gesture detection for landmark points.

**Describe the expected behavior:**
I want the frame of the camera to rotate with the direction of the screen. 

I see in another project that I can get the screen orientation:
angle = ((WindowManager)getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay().getRotation();

Subsequently, the frames are rotated according to the orientation:
converter = new CustomExternalTextureConverter(eglManager.getContext(), 2,270);
(Like #568 )

But I don't know how to define a process in the ./mediapipe/examples/android/solutions/hands/src/main/java/com/google/mediapipe/examples/hands/MainActivity.java

Thanks.

**Comment by sgowroji** [comment]
Hi @Ijustakid, Have you tried adding android:screenOrientation="landscape" in manifest and setRequestedOrientation (ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE); in MainActivity.Java
