### ISSUE TITLE
Help in Saving Hand Keypoints for MultipleHandTracking in dekstop and in both iOS and Android Application

### ISSUE THREAD

**Issue by alizahidraja** [google/mediapipe#303]
Hello,
I need help in Saving Hand Keypoints for MultipleHandTracking in dekstop and in both iOS and Android Application
I am looking to save the coordinates of all the keypoints of 2 hands.
I need to save them in both desktop and for mobile applications.
Saving as in getting the exact coordinates with respect to the bounding boxes of the detection or their coordinates in general

**Comment by eknight7** [comment]
Please look at the example source code. It shows you how to get hand landmarks for both single hand and multi-hand apps in Android and iOS on the application layer (Java/Objective-C).
