### ISSUE TITLE
MediaPipe Pose Estimation -  ML Kit alternative

### ISSUE THREAD

**Issue by FabianoFGomes** [google/mediapipe#3030]
I'm not going to use the ML kit and Pose Classification Colab to generate a CSV file.

Is there an alternative or some way to not use CSV files. If there is how to use it in MediaPipe? Is it by "solutionPath"?

**Comment by sgowroji** [comment]
Hi @FabianoFGomes, Could you please elaborate your query with complete details. Thanks!
