### ISSUE TITLE
How to do some developments based on example app?

### ISSUE THREAD

**Issue by zhiheng-ldj** [google/mediapipe#3031]
**System information** (Please provide as much relevant information as possible)
- Solution (e.g. FaceMesh, Pose, Holistic): Pose

**Describe the expected behavior:**
Hi, I am trying to use pose-tracking app and it works perfectly.

Where can I do some developments such as print some strings on my screen or do some simple calculators based on the result?

Thanks!

**Comment by sgowroji** [comment]
Hi @zhiheng-ldj, Which platform are you referring for the above query ? Can you share your usecase w.r.t to it.

**Comment by zhiheng-ldj** [comment]
> Hi @zhiheng-ldj, Which platform are you referring for the above query ? Can you share your usecase w.r.t to it.

Hi @sgowroji , I want to deploy the app in android devices. What I want is to do some post-process on the model result and print some strings/numbers on my screen.

Can I use Python API to do this? Or C++? I can write these 2 languages but not JAVA. How should I do?

I have checked the Python API provided by mediapipe but it does not show how to build and install it as .apk?

Thanks very much!

**Comment by zhiheng-ldj** [comment]
> Hi @zhiheng-ldj, Which platform are you referring for the above query ? Can you share your usecase w.r.t to it.

Hi @sgowroji , what I want is to do some post-processing of model results and show some words on screen.

For example, I want to do some calculations with the landmarks of my bodies and show some words on screen like:
"You are sitting." / "You are standing." based on the result of post-processing.

How should I do it? Could you help me figure out the proper way to do it?

I have checked the TextView method on .xml file but I don't think that is the way...

Thank you very much!

**Comment by kuaashish** [comment]
Hello @zhiheng-ldj,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
