### ISSUE TITLE
How to design a graph for pose tracking which runs in parallel

### ISSUE THREAD

**Issue by Billccx** [google/mediapipe#3034]
Dear researchers (or anyone reading this issue):
        I am working on a project about pose estimation. Here is my plan: 

Firstly, utilize 2 cameras, getting videos from different viewpoint. Then, run mediapipe pose tracking algorithm on two videos respectively, and get the landmarks from two different viewpoints. After that, using bundle adjustment to merge two sets of landmarks from different viewpoint, as the graph output.

Considering this project runs in real time, I plan to use 2 threads to do pose estimation in parrllel (one thread for one viewpoint), then synchronize the output landmarks from two thread and send them into the downstream bundle adjustment calculator.

Here is the graph I design:

![EA77E209443043EBA45FF3FFC1D8E34E](https://user-images.githubusercontent.com/52842460/151707121-7873484c-b140-4ea9-a5fd-deb64f9a46c8.png)

I wonder if this plan could be implemented by mediapipe？Will mediapipe run this graph in parallel (two threads as i wish) automatically? Or I have to do something deliberately to enable parallel? What should I do?

I looking forward to your reply and thanks in advance!

**System information** 
- custom code
- Linux Ubuntu 20.04
- Solution: Pose
- C++

**Comment by brucechou1983** [comment]
The short answer is yes you can do that with MediaPipe. About threading in MP read [this](https://google.github.io/mediapipe/getting_started/faq.html#how-to-run-calculators-in-parallel).

**Comment by sgowroji** [comment]
@brucechou1983  Thank you for sharing.

**Comment by LiuYi-Up** [comment]
> Dear researchers (or anyone reading this issue): I am working on a project about pose estimation. Here is my plan:
> 
> Firstly, utilize 2 cameras, getting videos from different viewpoint. Then, run mediapipe pose tracking algorithm on two videos respectively, and get the landmarks from two different viewpoints. After that, using bundle adjustment to merge two sets of landmarks from different viewpoint, as the graph output.
> 
> Considering this project runs in real time, I plan to use 2 threads to do pose estimation in parrllel (one thread for one viewpoint), then synchronize the output landmarks from two thread and send them into the downstream bundle adjustment calculator.
> 
> Here is the graph I design:
> 
> ![EA77E209443043EBA45FF3FFC1D8E34E](https://user-images.githubusercontent.com/52842460/151707121-7873484c-b140-4ea9-a5fd-deb64f9a46c8.png)
> 
> I wonder if this plan could be implemented by mediapipe？Will mediapipe run this graph in parallel (two threads as i wish) automatically? Or I have to do something deliberately to enable parallel? What should I do?
> 
> I looking forward to your reply and thanks in advance!
> 
> **System information**
> 
> * custom code
> * Linux Ubuntu 20.04
> * Solution: Pose
> * C++

Hi, excuse me. I have the same proplem with you. Did you have resolve the problem that run mediapipe in multi threads? Could you share the example?

I'm looking forward your reply!

Best wishes!

**Comment by Billccx** [comment]
> > Dear researchers (or anyone reading this issue): I am working on a project about pose estimation. Here is my plan:
> > Firstly, utilize 2 cameras, getting videos from different viewpoint. Then, run mediapipe pose tracking algorithm on two videos respectively, and get the landmarks from two different viewpoints. After that, using bundle adjustment to merge two sets of landmarks from different viewpoint, as the graph output.
> > Considering this project runs in real time, I plan to use 2 threads to do pose estimation in parrllel (one thread for one viewpoint), then synchronize the output landmarks from two thread and send them into the downstream bundle adjustment calculator.
> > Here is the graph I design:
> > ![EA77E209443043EBA45FF3FFC1D8E34E](https://user-images.githubusercontent.com/52842460/151707121-7873484c-b140-4ea9-a5fd-deb64f9a46c8.png)
> > I wonder if this plan could be implemented by mediapipe？Will mediapipe run this graph in parallel (two threads as i wish) automatically? Or I have to do something deliberately to enable parallel? What should I do?
> > I looking forward to your reply and thanks in advance!
> > **System information**
> > 
> > * custom code
> > * Linux Ubuntu 20.04
> > * Solution: Pose
> > * C++
> 
> Hi, excuse me. I have the same proplem with you. Did you have resolve the problem that run mediapipe in multi threads? Could you share the example?
> 
> I'm looking forward your reply!
> 
> Best wishes!

Hello. I think this [project](https://github.com/Billccx/multiviewPose/blob/main/mediapipe/examples/desktop/mypose10/mypose_tracking10.pbtxt) will be a little bit helpful.  I tried to implement the pipeline mentioned before. However, I can not ensure its correctness, since I found the pipeline got stuck sometimes.
