### ISSUE TITLE
Pose tracking / segmentation underperforms on Ryzen 9 3900X

### ISSUE THREAD

**Issue by MaksymAtNimagna** [google/mediapipe#3035]
**System information** (Please provide as much relevant information as possible): Ryzen 9 3900X 3.8GHz 32 GB RAM
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): Pose example
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 10, up to date
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.8
- Bazel version: 3.7.2
- Solution (e.g. FaceMesh, Pose, Holistic): Pose
- Programming Language and version ( e.g. C++, Python, Java): C++
For benchmarking purposes the default graph provided is being used.

**Describe the expected behavior:**
High performance is achieved, the load is distributed equally to all the CPU cores.

**Actual behavior**
Only one thread seems to be utilized, for 800x600 resolution, the frame time is roughly 33ms. Technically speaking, this is a real time performance (~30fps), but it's strange that it's not much better than what one could expect on a mobile phone despite running it on one of the top of the line CPUs. While testing it on i7 7700k, the frame time is 18ms/frame, but still only one thread seems to be utilized. The difference between Intel and AMD is also interesting. I benchmarked it on 5 different machines and Intel outperforms the AMD even in the case of older intel CPUs.

Is it possible to build with some options that allow distributing the workload equally between all the cores/threads for better performance or modify the graph somehow? I also created a dll of the Pose solution so I can sideload it into an app I'm working on and the performance is exactly the same as in the demo. 30ms/frame wouldn't be a problem if not for the fact that we need to run a whole bunch of other image processing operations on each frame and Pose consumes the entire frame time budget already.

**Comment by sgowroji** [comment]
Hi @MaksymAtNimagna, Thank you for sharing your query. Could you please provide any references like error logs or screenshots  where it underperforms on the above.

**Comment by MaksymAtNimagna** [comment]
Thank you for replying so fast! There are no errors and it's just a relatively low framerate issue where only a single core is being utilized (at least looking at the task manager) - what specifically could I provide to help you better to take a closer look at the issue?

**Comment by MaksymAtNimagna** [comment]
> Hi @MaksymAtNimagna, Thank you for sharing your query. Could you please provide any references like error logs or screenshots where it underperforms on the above.

Thank you for replying so fast! There are no errors and it's just a relatively low framerate issue where only a single core is being utilized (at least looking at the task manager) - what specifically could I provide to help you better to take a closer look at the issue?

**Comment by MaksymAtNimagna** [comment]
![image](https://user-images.githubusercontent.com/88328636/153367004-fdaf5b82-b89a-4aa3-b653-c267412a68e7.png)
![image](https://user-images.githubusercontent.com/88328636/153367055-9969f27d-9729-4161-84db-c8b4053e99cc.png)
![image](https://user-images.githubusercontent.com/88328636/153367084-4e19df6e-c0b4-47aa-a7d4-691480817dfd.png)
![image](https://user-images.githubusercontent.com/88328636/153367111-cba2e6d8-1ae3-4d33-a724-95a98bc14cd2.png)

Here I include data collected from other platforms. Unfortunately I don't have a table for laptops, but even on laptop i7 7820HK the performance is within 30ms/frame range and that's one of the top of the line mobile CPUs. Can something be done about the poor utilization of threads? For some reason everything seems to run on a single thread and not even utilize it fully in any of the cases above.

**Comment by mcclanahoochie** [comment]
Hi, a few questions:

Are you running the CPU or GPU graph?  
If CPU graph, Is the inference delegate using xnnpack? 
If GPU graph, then there isn't much more to parallelize on CPU. 
If CPU graph, is your OpenCV compiled with all the intrinsics enabled (if you didn't use setup_opencv.sh)?
Do the machines have similar DDR ram configurations/specs? 

There is a `num_threads` option you can add to your graphs
add `num_threads: 10` (or any number) to the top of your graphs.
The default is to choose a number based on # of cpus, but specifying a specific number might be beneficial..? This is just specifying a thread pool size, though (not forcing anything).

**Comment by MaksymAtNimagna** [comment]
@mcclanahoochie has there been any progress on this issue? The strangest part for me is that only one core is being utilized regardless of the CPU.

**Comment by MaksymAtNimagna** [comment]
Ping?

**Comment by MaksymAtNimagna** [comment]
Has there been any progress on this or plans to better distribute the code across the cores or utilize GPU?

**Comment by kuaashish** [comment]
Hello @MaksymAtNimagna,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
