### ISSUE TITLE
Output result gives different z values for Live face and picture face

### ISSUE THREAD

**Issue by showbit01** [google/mediapipe#3036]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):
- Programming Language and version ( e.g. C++, Python, Java):

**Describe the expected behavior:**

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by sgowroji** [comment]
Hi @showbit01, Can you fill the above issue template to investigate further and provide the necessary references like images used in testing the above. Thanks!

**Comment by sgowroji** [comment]
Has mentioned here (https://google.github.io/mediapipe/solutions/face_mesh.html#python-solution-api)z represents the landmark depth with the depth at center of the head being the origin, and the smaller the value the closer the landmark is to the camera. The magnitude of z uses roughly the same scale as x. So z value differs with Live face and picture face.

**Comment by sgowroji** [comment]
@showbit01 reach us back if you still have a query and need more details. Thank!

**Comment by xiang-zhe** [comment]
Hi, @sgowroji, z represents the landmark depth with the depth at center of the head being the origin, I want to know which coordinate it mean about "center of the head being the origin"; and in hand, z represents the landmark depth with the depth at the wrist being the origin, that i know z value of hand should take **WRIST** as origin, while face mesh should take **NOSE**(index is 0 in bodypose) as origin.
