### ISSUE TITLE
MediaPipe installation in AWS EC2 instance

### ISSUE THREAD

**Issue by sushma-snk** [google/mediapipe#3037]
I am working on MediaPipe for an application. Everything works fine on local server but how do i install MediaPipe in AWS EC2 instance?
Found this: [https://dev.classmethod.jp/articles/mediapipe-install-on-aws-ec2-with-gpu-english/]
The charges are too high.
Has anyone worked on MediaPipe in AWS? Kindly request you to help me out...
Thanks, in advance!!!

**Comment by sgowroji** [comment]
Hi  @sushma-snk Can you try checking the same in our slack community which is More active and can assist well on this type of queries.  https://mediapipe.slack.com/join/shared_invite/zt-ey6bzgpe-QzmGV4DQ7oDLVslgXYvshQ#/shared-invite/email. Meanwhile we will keep this thread open to address from the community. In Github try raising support or bug related issues which need guidance from the engineers.

**Comment by sushma-snk** [comment]
Will check in Slack Community.
Thanks for quick reply @sgowroji
