### ISSUE TITLE
Android solution for face mesh brings different land marks

### ISSUE THREAD

**Issue by nivsaparov1** [google/mediapipe#3038]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic): Face Mesh
- Programming Language and version ( e.g. C++, Python, Java): JAVA

**Describe the expected behavior:**
Loading the same video from my camera and logging all face landmarks or even just the nose landmark for each frame will lead to the same result each time.

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:
To avoid loading the video each time I set the `videoInput` to loop 
`            videoInput.setLooping(true);
`

**Comment by sgowroji** [comment]
Hi @nivsaparov1, Can you provide any reference to illustrate the above scenario. Thanks!

**Comment by nivsaparov1** [comment]
Sure, something important to mention is happening when I configure faceMesh with `setStaticImageMode(false)` 
https://drive.google.com/file/d/1wyAevWVw9cje8ibge0emiHT8s-aGcWji/view?usp=sharing
@sgowroji

**Comment by kuaashish** [comment]
Hello @nivsaparov1,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
