### ISSUE TITLE
Unable to overlay png image in annotation_renderer.cc

### ISSUE THREAD

**Issue by Hrituraj202** [google/mediapipe#3039]
HI, I am new to c++ but exploring things in mediapipe. 
I am working on iris_tracking project. I want to overlay color lens on eyes using png.
But before anything else I was trying to overlay a png over the frame like this but it gives error.

`  cv::Mat lens = cv::imread(file::JoinPath("./", "/mediapipe/calculators/image/testdata/lens.png"));
lens.copyTo(mat_image_(cv::Rect(0, 0, 100, 100)));
`

And if I simply do `lens.copyTo(mat_image_);` it gives me an image like this 
<img width="312" alt="error" src="https://user-images.githubusercontent.com/20509898/151854581-5784a1a9-5fa7-43d7-9171-89e784ee2e8e.png">

How can i achieve something in this?
There is no proper documentation on how to do this. I have spent days trying different things.
Please also recommend me ways on how to achieve familiarity in this mediapipe framework in c++, because I want to learn it and use for my projects.

**Comment by sgowroji** [comment]
Hi @Hrituraj202, To start doing the MediaPipe in C++ then you should go through this https://google.github.io/mediapipe/getting_started/cpp.html#mediapipe-in-c . You can refer the code implementation and comments mentioned in the https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/util/annotation_renderer.cc for documentation. What is your use case with respect to the above query ?

**Comment by Hrituraj202** [comment]
HI @sgowroji, thanks for you response. 
Actually I have been working on the iris_tracking project and trying to remove all the annotations.
I want to overlay a lens png image over the iris.
I am trying to implement a DrawImage method in annotation_renderer.cc just like other methods like.. DrawRectangle, DrawRoundedRectangle, DrawOval, DrawText, DrawLine, DrawArrow etc

**Comment by mcclanahoochie** [comment]
I believe the mat_image_ inside annotation renderer is RGB format (CV_8UC3), make sure the loaded png image is also the same format
