### ISSUE TITLE
Algorithms Specification

### ISSUE THREAD

**Issue by lghasemzadeh** [google/mediapipe#3040]
Hello,

Is there any **algorithm specification**, requirement or evaluation guideline for mediapipe, specially the Facemesh, Holistic, Face Geometry and Object Detection solutions.
1) I want to know the strength and weakness of these solutions? 
2) Is there any constraint or environmental circumstances/conditions that these solution can works better or worst there? 

Thank you

**Comment by sgowroji** [comment]
If you find any could you please share us. We can consider them in our continuous improvements which we do to our MediaPipe solutions. And you can even refer our **previous GitHub issues** to know more about the above solutions   **strength & weakness**,  **better or worst**  and where it encounter problems and the **support/solutions** provided by the Engineers and community members.

**Comment by lghasemzadeh** [comment]
I checked the previous issues but I did not find what I am looking for.
I think there should be a constrain/specification/requirement list for mediapipe. During developing a software there will be lots of issue and constraints detected/observed by developers which they are listed. Would you please tag one of the mediapipe's developer to know his/her idea?
currently I found an issue regarding the FPS constraints and I will post it as soon as I have time.
Thank you very much

**Comment by sgowroji** [comment]
Hi @lghasemzadeh, Can you share more details like which platform and MediaPipe solution are you referring for the above request. And also share your use case with complete details. We assigned this issue to @mcclanahoochie who can guide you well on MediaPipe performance.
