### ISSUE TITLE
Hand gesture/Holistic on coral

### ISSUE THREAD

**Issue by fbenamrouche** [google/mediapipe#3041]
I see that holistic/ hand tracking/ gesture is doing exactly what we want on mobile phone/android.

I would like to use an nxp imx8 under android attached to a camera, but unfortunately, the gpu is way too slow (I need it to do other AI computation too) and unfortunately the models are not working with the the TPU inside (int8 only)
I would like to test also the possibility to use the Coral edge tpu for the same use case.

Do you think you can provide a working model for edge TPU? That would be awesome!

Thanks!

**Comment by mcclanahoochie** [comment]
Thank you for the feedback. Unfortunately there are no plans to export quantized models at this time.
