### ISSUE TITLE
Mediapipe pose not working with react

### ISSUE THREAD

**Issue by faraznisar** [google/mediapipe#3042]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
I am trying to work with mediapipe pose in my react app but it doesn't work and I get a "Uncaught (in promise) RuntimeError: abort(undefined) at Error" in the "pose_solution_simd_wasm_bin.js" file.
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
  I have changed bits and pieces of the code to make it work with react but other than that, I haven't changed it too much
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
  Windows 11 
- [MediaPipe version](https://github.com/google/mediapipe/releases):
     "@mediapipe/camera_utils": "^0.3.1640029074",
    "@mediapipe/control_utils": "^0.6.1629159505",
    "@mediapipe/drawing_utils": "^0.3.1620248257",
    "@mediapipe/pose": "^0.5.1635988162",
- Bazel version:
   NA
- Solution (e.g. FaceMesh, Pose, Holistic):
  POSE
- Programming Language and version ( e.g. C++, Python, Java):
 Javascript
**Describe the expected behavior:**
 I need the program to detect the pose and it is not doing it, rather throwing an error
**Standalone code you may have used to try to get what you need :**
   import * as cam from "@mediapipe/camera_utils";
import * as mediapipePose from "@mediapipe/pose";

import React, { useEffect, useRef, useState } from 'react';
import { drawConnectors, drawLandmarks } from '@mediapipe/drawing_utils'

import { Pose } from "@mediapipe/pose";
import Webcam from 'react-webcam'

const UserPose = () => {
    // * refs to the html elements
    const webcamRef = useRef(null);
    const canvasRef = useRef(null);
    // const landmarkRef = useRef(null);
    let userPoseAngle = null;
    let camera = null;
    let down;
    let repsCounter = 0;

    const [repCounter, setRepCounter] = useState(null)
    // let repsCounter = 0;
    // * function to draw the landmarks once the pose has been determined
    function onResults(results) {
        let landmarks = results.poseLandmarks // * all the landmarks in the pose

        //  * getting the values for the three landmarks that we want to use
        try { // * we get errors every time the landmarks are not available
            // * will provide dynamic landmarks later "landmarks[mediapipePose.POSE_LANDMARKS.{landmark}]"
            let leftShoulder = landmarks[mediapipePose.POSE_LANDMARKS.LEFT_SHOULDER];
            let leftElbow = landmarks[mediapipePose.POSE_LANDMARKS.LEFT_ELBOW];
            let leftWrist = landmarks[mediapipePose.POSE_LANDMARKS.LEFT_WRIST];
            calculatePoseAngle(leftShoulder, leftElbow, leftWrist);
        } catch (error) {
            // console.error(error);
        }
        // Define the canvas element dimensions using the earlier created refs
        canvasRef.current.width = webcamRef.current.video.videoWidth
        canvasRef.current.height = webcamRef.current.video.videoHeight

        const canvasElement = canvasRef.current;
        const canvasCtx = canvasElement.getContext("2d")
        canvasCtx.save();
        canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
        canvasCtx.drawImage(results.image,
            0,
            0,
            canvasElement.width,
            canvasElement.height
        )
        drawConnectors(canvasCtx,
            results.poseLandmarks, mediapipePose.POSE_CONNECTIONS,
            { color: 'white', lineWidth: 1 });
        // * The dots are the landmarks 
        drawLandmarks(canvasCtx, results.poseLandmarks,
            { color: 'red', lineWidth: 1, radius: 2 });
        canvasCtx.restore();
    }

    // * calculating the angles in the user pose
    const calculatePoseAngle = (a, b, c) => {
        let radians = Math.atan2(c.y - b.y, c.x - b.x) - Math.atan2(a.y - b.y, a.x - b.x) // * fetching the radians using the atan2 function 
        let angle = radians * (180 / Math.PI) // * calculating the angle from the radian
        // need to provide dynamic values for angles as per requirement later along with the number of reps.
        if (angle > 180) { // * if the angle is greater than 180, then it is negative so changing it back to positive or an actual angle possible for a human being, lol..
            angle = 360 - angle
        }
        if (angle > 0 && angle < 180) { // * if the angle is positive, then it is a positive angle
            // console.log(angle.toFixed(2), "currentAngle");
        }
        userPoseAngle = angle.toFixed(2);
        calculateReps(userPoseAngle);
    }
    const calculateReps = (angle) => {
        // console.log(angle);
        if (angle >= 160) {
            down = true;
        }
        if (angle <= 40 && down) {
            down = false;
            // setRepCounter(repCounter + 1);
            repsCounter += 1;
            console.log(repsCounter, "repsCounter");
        }
        // console.log('out');
        // console.log(repsCounter, "repsCounter");
    }
    useEffect(() => {
        const userPose = new Pose({
            locateFile: (file) => {
                return `https://cdn.jsdelivr.net/npm/@mediapipe/pose/${file}`;
            },
        });
        userPose.setOptions({
            maxNumFaces: 1,
            minDetectionConfidence: 0.8,
            minTrackingConfidence: 0.8,
        });
        userPose.onResults(onResults);
        if (
            typeof webcamRef.current !== "undefined" &&
            webcamRef.current !== null
        ) {
            camera = new cam.Camera(webcamRef.current.video, { // no issues with the exaustive-deps. We do not need to store the camera object for current purposes
                onFrame: async () => {
                    await userPose.send({ image: webcamRef.current.video });
                },
                width: 1280,
                height: 720,
            });
            camera.start();
        }
    }, []);
    return <div>
        <div className="App">
            <h1>{repCounter}</h1>
            <Webcam
                ref={webcamRef}
                style={{
                    position: "absolute",
                    marginLeft: "auto",
                    marginRight: "auto",
                    left: 0,
                    right: 0,
                    textAlign: "center",
                    zindex: 9,
                    width: 1280,
                    height: 720,
                }}
            />
            <canvas
                ref={canvasRef}
                style={{
                    position: "absolute",
                    marginLeft: "auto",
                    marginRight: "auto",
                    left: 0,
                    right: 0,
                    textAlign: "center",
                    zindex: 9,
                    width: 1280,
                    height: 720,
                }}
            ></canvas>
            <div className="landmark-grid-container"></div>
        </div>
    </div>
};

export default UserPose;

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

 If needed I will provide the repository but the above code should be enough to replicate it in react

**Other info / Complete Logs :**
 NA
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:
[error.txt](https://github.com/google/mediapipe/files/7984615/error.txt)

Extra information that might help understand the issue: 

 If I change the versions to all the dependencies to the ones below
    "@mediapipe/camera_utils": "^0.3.1640029074",
    "@mediapipe/control_utils": "^0.3.1622680678",
    "@mediapipe/drawing_utils": "^0.3.1620248257",
    "@mediapipe/pose": "^0.3.1621277220",
    and use the `https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.2/${file}` (v2) of the cdn everything works just fine.

Do let me know if using the older version puts me at a disadvantage or if it is fine using the configuration that I can get working in my setup.

**Comment by ayoub-root** [comment]
update your pose options
  userPose.setOptions({
        selfieMode: true,
        modelComplexity: 0,
        smoothLandmarks: true,
        enableSegmentation: false,
        smoothSegmentation: true,
        minDetectionConfidence: 0.5,
        minTrackingConfidence: 0.5,
      });

**Comment by kuaashish** [comment]
Hello @faraznisar,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by g4ze** [comment]
Hey! @faraznisar did you get a solution??

**Comment by faraznisar** [comment]
> Hey! @faraznisar did you get a solution??

I’ll have to get back to you on this one. Been like forever since I opened this issue. I’ll have a look and update you

**Comment by g4ze** [comment]
Any leads?
