### ISSUE TITLE
How to get a Image directly from TflitInferenceCalculator

### ISSUE THREAD

**Issue by akdu12** [google/mediapipe#3043]
Hello
I'm looking to use a calculator to convert The tensors returned after inference but couldn't find the proper calculator

does MP already have an implementation for this case?
thank you!

**Comment by sgowroji** [comment]
Hi @akdu12, Can you elaborate your use case with the above query. Thanks!

**Comment by akdu12** [comment]
@sgowroji I have a custom model which take an image and returns an image and was trying to build the graph for it, but looking at the examples from MP, they are either classifications , seg or tracking. do you have an idea about a simple graph that takes an gpu image- does the inference then returns a gpu image?
