### ISSUE TITLE
Unable to build mediapipe for older Android versions

### ISSUE THREAD

**Issue by AbinayaKumar25** [google/mediapipe#3045]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 20.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Java
- Installed using virtualenv? pip? Conda? (if python): No
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version: 4.2.1
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android): SDK 28.0.3
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:
I am trying to build mediapipe example apps for older Android versions. But it throws error saying Bazel requires Android SDK 30 or greater. I understand the bazel and SDK versions are not compatible. Which version should I use to build Mediapipe with Android SDK build-tools 28?

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

Bazel requires Android build tools version 30.0.0 or newer, 28.0.3 was provided

**Comment by sgowroji** [comment]
Hi @AbinayaKumar25,You can try our Gradle Android API solutions https://google.github.io/mediapipe/getting_started/android_solutions.html#mediapipe-android-solutions

**Comment by AbinayaKumar25** [comment]
I tried to build aar file but I ended up with the error as stated above. Bazel requires android build tools 30 or newer. I have a hard constraint that I can’t update my build tools. Any suggestions?

**Comment by sgowroji** [comment]
What is the error are you seeing while building the code.

**Comment by AbinayaKumar25** [comment]
Build failed. Bazel requires android build tools 30 or newer. My Bazel version is 4.2.1

**Comment by sgowroji** [comment]
This are Prerequisites  https://google.github.io/mediapipe/getting_started/android.html#prerequisite, But still you can build. and run applications with [android:minSdkVersion="21" ](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/solutions/hands/src/main/AndroidManifest.xml#:~:text=%3Cuses%2Dsdk,android%3AtargetSdkVersion%3D%2230%22%20/%3E)

**Comment by AbinayaKumar25** [comment]
Does it mean I cannot run applications with Android buildtools version 28 or 29?

**Comment by AbinayaKumar25** [comment]
@sgowroji  Could you confirm whether mediapipe cannot be built with Android build tools version 29 or below?

**Comment by AbinayaKumar25** [comment]
@sgowroji could you confirm the above question?

**Comment by kuaashish** [comment]
Hi @AbinayaKumar25,
Could you please go through the [above](https://github.com/google/mediapipe/issues/3045#issuecomment-1063148600) comment and let us know the status of the issue. Thank you!
