### ISSUE TITLE
For anyone who wants a fast solution meanwhile someone fixs this error. It works for me, Just get module path from meadiapipe or the module what you get error and write in python console:

### ISSUE THREAD

**Issue by Omkar-Jawalkar** [google/mediapipe#3046]
For anyone who wants a fast solution meanwhile someone fixs this error. It works for me, Just get module path from meadiapipe or the module what you get error and write in python console:

import mediapipe
print(mediapipe . __ file __ )  (without black spaces)

once you get path folder, just copy all mediapipe folder and paste in your folder where you have your exe file and that is all!. Luck

_Originally posted by @ElectroCoderEC in https://github.com/google/mediapipe/issues/2162#issuecomment-974658826_

**Comment by Omkar-Jawalkar** [comment]
Traceback (most recent call last):
  File "Scroll_using_Hands.py", line 38, in <module>
  File "HandTrackingMod.py", line 22, in __init__
  File "mediapipe\python\solutions\hands.py", line 114, in __init__
  File "mediapipe\python\solution_base.py", line 237, in __init__
FileNotFoundError: The path does not exist.

**Comment by sgowroji** [comment]
Hi @Omkar-Jawalkar, Can you share the steps to reproduce the above error with complete details like code and configuration. Thanks!

**Comment by Omkar-Jawalkar** [comment]
**Here is the Mediapipe module**
    
    
    import cv2
    import mediapipe as mp
    import time
    import math
    import numpy as np
    
    class handDetector():
        def __init__(self, mode=False, maxHands=2, modelComplex=1, detectionCon=0.5, trackCon=0.5):
            self.mode = mode
            self.maxHands = maxHands
            self.modelComplex = modelComplex
            self.detectionCon = detectionCon
            self.trackCon = trackCon
            
            self.mpHands = mp.solutions.hands
            self.hands = self.mpHands.Hands(self.mode,self.maxHands,self.modelComplex, self.detectionCon, self.trackCon)
            self.mpDraw = mp.solutions.drawing_utils
            self.tipIds = [4,8,12,16,20]
    
        
        def findHands(self, img, draw=True):
            
            imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            self.results = self.hands.process(imgRGB)
        #     print(results.multi_hand_landmarks)
    
            if self.results.multi_hand_landmarks:
                for handLms in self.results.multi_hand_landmarks:
                    if draw:
                        self.mpDraw.draw_landmarks(img, handLms, self.mpHands.HAND_CONNECTIONS)
                    
            return img       
                    
        def findPosition(self, img, handNo=0, draw=True):
            xList = []
            yList = []
            bbox = []
            self.lmList = []
            if self.results.multi_hand_landmarks:
                myHand = self.results.multi_hand_landmarks[handNo]
                for id, lm in enumerate(myHand.landmark):
                    # print(id, lm)
                    h, w, c = img.shape
                    cx, cy = int(lm.x * w), int(lm.y * h)
                    xList.append(cx)
                    yList.append(cy)
                    # print(id, cx, cy)
                    self.lmList.append([id, cx, cy])
                    if draw:
                        cv2.circle(img, (cx, cy), 3, (0, 255,0), cv2.FILLED)
    
                xmin, xmax = min(xList), max(xList)
                ymin, ymax = min(yList), max(yList)
                bbox = xmin, ymin, xmax, ymax
    
                if draw:
                    cv2.rectangle(img, (xmin - 20, ymin - 20), (xmax + 20, ymax + 20),
                                  (0, 255, 0), 2)
    
            return self.lmList, bbox
    
                    
        def fingersUp(self):
    
            fingers1 = []
    
            # For Thumb
    
            if self.lmList[self.tipIds[0]][1] >  self.lmList[self.tipIds[0]-1][1]:
                fingers1.append(1)
            else: 
                fingers1.append(0)
    
            # For Fingers 
            for id in range(1,5):
                if self.lmList[self.tipIds[id]][2] <  self.lmList[self.tipIds[id]-2][2]:
                    fingers1.append(1)
    
                else: 
                    fingers1.append(0)
    
            return fingers1
    
    
        def findDistance(self,p1,p2,img,draw=True,r=15,t=3):
            x1,y1 = self.lmList[p1][1:]
            x2,y2 = self.lmList[p2][1:]
            cx, cy = (x1 + x2) // 2, (y1 + y2) // 2 
    
            if draw:
                cv2.line(img, (x1,y1), (x2,y2), (255,0,255), t)
                cv2.circle(img, (x1,y1), r, (255,0,255), cv2.FILLED)
                cv2.circle(img, (x2,y2), r, (255,0,255), cv2.FILLED)
                cv2.circle(img, (cx,cy), r, (0,0,255), cv2.FILLED)
            length = mathhypot(x2 - x1 ,y2 - y1)
    
    
            return length, img, [x1,y1,x2,y2,cx,cy]
    
    
    
    
    
    
    
    
        
        
        
        
    def main():
        
        pTime = 0
        cTime = 0
        
        cap = cv2.VideoCapture(0)
        detector = handDetector()
    
        while True:
            sucess, img = cap.read()
            img = detector.findHands(img)
            lmList, bbox = detector.findPosition(img)
            if len(lmList) != 0:
                print(lmList[8])
            
            
            cTime = time.time()
            fps = 1/(cTime-pTime)
            pTime = cTime
    
            cv2.putText(img,str(int(fps)),(10,70),cv2.FONT_HERSHEY_PLAIN, 3, (255,0,255), 3 )
    
            cv2.imshow("Image", img)
            cv2.waitKey(2)
    
    
    if __name__ =="__main__":
        main()

**Comment by Omkar-Jawalkar** [comment]
When we execute the this program, it runs fine
But When we convert this program(.py) to (.exe) file using **pyinstaller** and try to execute, it gives an error

_Here's that error_

> Traceback (most recent call last):
  File "Scroll_using_Hands.py", line 38, in <module>
  File "HandTrackingMod.py", line 22, in __init__
  File "mediapipe\python\solutions\hands.py", line 114, in __init__
  File "mediapipe\python\solution_base.py", line 237, in __init__
FileNotFoundError: The path does not exist.


**Here's my Program**
    
    import pynput
    import HandTrackingMod as htm
    import time
    import os
    import cv2
    import autopy
    from tkinter import *
    
    from pynput.keyboard import Key, Controller
    keyboard = Controller()
    buttonText = ['Click Me']
    
    
    cap = cv2.VideoCapture(0)
    w,h = autopy.screen.size()
    cap.set(3,w)
    cap.set(4,h)
    detector = htm.handDetector()
    keyValueUp = "Key.up"
    keyValueDown = "Key.down"
    
    
    root = Tk()
    root.geometry('500x500')
    a = Label(root, text="Happy Scrolling with Hands")
    a.pack()
    
    
    def execute():
        while True:
            success, img = cap.read()
            img = detector.findHands(img)
            lmList, bbox = detector.findPosition(img)
            if len(lmList) !=0:
                fingers = detector.fingersUp()
    
        #         For scrolling up
                if (fingers[1] == 0):
                    keyboard.press(Key.down)
                else:
                    keyboard.release(Key.down)
                    if(fingers[0] == 0):
                        keyboard.press(Key.up)
                    else:
                        keyboard.release(Key.up)
                        fingers[0] = 1;
    
            cv2.imshow("Image", img)
            
            if cv2.waitKey(27) & 0xFF == ord('q'):
                cap.release
                exit()
                break;
               
        
    
    
    button1 = Button(root, text=str(buttonText[0]), font=("Arial", 25)
                  ,background='Green',fg='white', bd='5', command = execute)
    button2 = Button(root, text="Turn Off", font=("Arial", 25)
                  ,background='Red',fg='white', bd='5', command = root.destroy)
    button1.pack(side = "top",fill=BOTH)
    button2.pack(side = "top",fill=BOTH)
    a2 = Label(root, text="Hint : Press 'q' to stop the camera and then close it :)")
    a2.pack()
    
    root.mainloop()

**Comment by Omkar-Jawalkar** [comment]
**Not only this project, but also other projects in which I've used mediapipe, when converted from (.py) file to (.exe) and tried to run, gives the same error**

**Comment by YaroslavFur** [comment]
This helped me with the 237 line error, I just followed the instruction of [Bar-Levav] (edited .spec file + special pyinstaller compilation command):
https://stackoverflow.com/questions/67887088/issues-compiling-mediapipe-with-pyinstaller-on-macos

**Comment by sureshdagooglecom** [comment]
Hi @Omkar-Jawalkar ,
Please follow the below steps to py to exe.
1)Open up the command line
2)Navigate to the folder that contains the programm.py program
2)Run pyinstaller programm.py 
This creates a folder called “dist” in the folder that contains your Python code, and within that folder you’ll find your .exe file.
