### ISSUE TITLE
Inference calculator WebGL accelerated

### ISSUE THREAD

**Issue by AlexMemomi** [google/mediapipe#3049]
Hello there. 
As far as we understand - there is no official wasm build support for current state of repository, but what is available  - prebuild npm packages. It seems like it was built from some mediapipe branch which is not public. I don't sure about the reasone (maybe its difficult to keep configuration for all of the platform supported), but for now - we can build it as wasm with only pthread / simd support within our fork. We see that some critical files to use webgl accelerated backend are excluded from main repo. As what we can see from binaries - there was kind of `MlDriftWebGl` inference calculator which is missing and was never published.
Is it possible to add it maybe as an extra repository (just a sources, we don't care if its buildable or not)? The reason why we ask - is that we want to use single wasm (combined with our code) without any additional packages and JS bridges.

**Comment by kuaashish** [comment]
@AlexMemomi,

Please check our MP Tasks Web can use GPU delegate now.
