### ISSUE TITLE
Error when using the video source directly as input to the face detector V0.4 without the mediapipe utilities in the demo 

### ISSUE THREAD

**Issue by Poufy** [google/mediapipe#3051]
Hello,

I have closely examined the existing media pipe demo for the face detector and I wanted to use the face detection model in my application. I have no need for the other dependencies in the demo like the control, drawing and camera utilities. Reading through other issues it was mentioned that we can directly pass the video source to the call like so
```js
await faceDetection.send({ image: videoElement })
```

And this is what I tried, but I keep coming across errors I cannot understand.

<strong> The exact same setup works when I replace version 0.4 with version 0.3 </strong>

![image](https://user-images.githubusercontent.com/35203098/152567462-b35feac3-0748-404e-8fd7-5ab2788facf2.png)

Here is the current code I have right now.

```js
const mpFaceDetection = window;

let inputCanvas = document.createElement('canvas');
let inputCanvasCtx = inputCanvas.getContext('2d');

// Getting the stream from the user device.
let stream = await navigator.mediaDevices.getUserMedia(constraints);
let stream_settings = stream.getVideoTracks()[0].getSettings();
let { width, height, frameRate } = stream_settings;
inputCanvas.width = width;
inputCanvas.height = height;

video.srcObject = stream;
video.play();

let faceDetection = new mpFaceDetection.FaceDetection({
       locateFile: (file) => {
            return `https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.4/${file}`;
        }
});

faceDetection.setOptions({
       modelSelection: 0,
       minDetectionConfidence: 0.5
    });

faceDetection.onResults(onFaceDetection);

video.requestVideoFrameCallback(captureFrame);

async function captureFrame() {
    // Draw current frame to canvas
    inputCanvasCtx.drawImage(video, 0, 0);
    // Get frame from our canvas.
    let frame = inputCanvasCtx.getImageData(0, 0, inputCanvas.width, inputCanvas.height);

    await faceDetection.send({ image: frame });
   
    video.requestVideoFrameCallback(captureFrame);

};

```

**Comment by Poufy** [comment]
Would love any comments on this topic. I am only going for performance here, so if the model used in version 0.3 and 0.4 do not different much in terms of performance, I am happy to use 0.3.

**Comment by sgowroji** [comment]
Hi @Poufy, Could you please refer this https://github.com/google/mediapipe/issues/2953#issuecomment-1005104992 which is similar to the above context. Thanks!
