### ISSUE TITLE
Can I use Mediapipe on IOS with Java

### ISSUE THREAD

**Issue by V-m1r** [google/mediapipe#3052]
I have already designed an app on Android with mediapipe and am wondering if I can use the code structure in Java for iOS as well using multi-os engine.
If yes, can someone provide details how to I can achieve that? 
Thank you!

**Comment by sgowroji** [comment]
Hi @V-m1r, You can Start building IOS applications following this [steps](https://google.github.io/mediapipe/getting_started/ios.html), We don't have java examples of IOS applications . If you are looking for Multiplatform support you can try using Javascript solutions to render on browsers from our [JS](https://google.github.io/mediapipe/getting_started/javascript.html) solutions.  There are also [unity](https://github.com/homuler/MediaPipeUnityPlugin) plugin where you can build applications of MediaPipe in many platform which is shared by the community members.
