### ISSUE TITLE
How to get the 3D coordinate of the face landmarks?

### ISSUE THREAD

**Issue by chuckle-lee** [google/mediapipe#3053]
I hope to get the 3D coordinates and use meshlab to construct the faces. thanks everybody!

**Comment by Lando31337** [comment]
Good call Chuckle-Lee. Same request, but more specifically the canonical 3D mesh in euclidean 3D space i.e before it has been translated for display on the image. Second prize would be the matrix transformation to convert the landmarks back to a 3D mesh.

**Comment by chuckle-lee** [comment]
I used the following to get the coordinates and save it as a ply file which can be opened by meshlab. But there are only landmarks and I don't know how to draw mesh based on these landmarks.

# to get the coordinates
for landmarks in results.multi_face_landmarks:
  x = [landmark.x for landmark in landmarks.landmark]
  y = [landmark.y for landmark in landmarks.landmark]
  z = [landmark.z for landmark in landmarks.landmark]
print(len(x))
x_num= np.array(x)
y_num= np.array(y)
z_num= np.array(z)
data=np.vstack([x_num,y_num,z_num]).T

#  save it as a ply file, this was from online resources

import numpy as np
def create_output(vertices, colors, filename):
    colors = colors.reshape(-1, 3)
    vertices = np.hstack([vertices.reshape(-1, 3), colors])
    np.savetxt(filename, vertices, fmt='%f %f %f %d %d %d')     
    ply_header = '''ply
    		format ascii 1.0
    		element vertex %(vert_num)d
    		property float x
    		property float y
    		property float z
    		property uchar red
    		property uchar green
    		property uchar blue
    		end_header
    		\n
    		'''
    with open(filename, 'r+') as f:
        old = f.read()
        f.seek(0)
        f.write(ply_header % dict(vert_num=len(vertices)))
        f.write(old)

output_file = '3D_coordinate.ply'
one = np.ones((478,3))
one = np.float32(one)*255
create_output(data, one, output_file)

**Comment by sgowroji** [comment]
Hi @chuckle-lee, World landmarks are not yet available for FaceMesh.

**Comment by HakuWang** [comment]
> Hi @chuckle-lee, World landmarks are not yet available for FaceMesh in python.

Hi, the face geometry module I also want to know if the face geometry module can meet my similar needs. I want to get the vertex coordinates to build the 3d face model.

**Comment by sgowroji** [comment]
We haven't integrated the face geometry data in the Python API. Will provide updates when it becomes available. There is already a thread where you can get more information regarding the same. https://github.com/google/mediapipe/issues/1912
