### ISSUE TITLE
ios example posetrackingpu does not build

### ISSUE THREAD

**Issue by simplyakash** [google/mediapipe#3054]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):
 > MacOS Big Sur version : 11.6.2 (20G314)
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):
> Apple clang version 13.0.0 (clang-1300.0.29.30)
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): 
> using C++ 14 ( Also fails with C++ 17 )
> ios examples of  mediapipe on xcode 13.2.1 using Tulsi
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
> 0.8.9
- Bazel version:
> bazel 5.0.0
- XCode and Tulsi versions (if iOS):
> xcode 13.2.1, tulsi Version 0.20220105.88 (0.20220105.88)
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:
We are just trying to build the MediaPipe iOS examples following the directions provided:
https://google.github.io/mediapipe/getting_started/ios.html
The build fails on xcode with these errors :

Shell Script Invocation Error Group
/var/tmp/_bazel_akash/2a9da715097c90fabc4924769ab48f63/external/com_google_protobuf/BUILD:155:11: Compiling src/google/protobuf/arena.cc failed: (Aborted): wrapped_clang failed: error executing command
/Users/akash/virdio/mediapipe/external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:192:5: Aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on iOS 11 or newer
/Users/akash/virdio/mediapipe/external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:185:16: Aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on iOS 11 or newer
/Users/akash/virdio/mediapipe/external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:185:16: Aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on iOS 11 or newer
Build did NOT complete successfully
/Users/akash/virdio/tulsi_projects/Mediapipe.xcodeproj/.tulsi/Scripts/bazel_build.py:594: Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
> The exact sequence of instructions is provided on the page **(https://google.github.io/mediapipe/getting_started/ios.html
)**

It fails when we build for iphone 12 pro max simulator and the actual phone as well.
We tried setting the ios Deployment Target to ios 11 but it did not help.

This issue seems similar to, but slightly different from, this one:
https://github.com/google/mediapipe/issues/3032
A comment was made there that it works when building for the actual phone; that did NOT work for us.

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by simplyakash** [comment]
Changing MIN_IOS_VERSION = "10.0" to MIN_IOS_VERSION = "11.0" in the BUILD files for the ios examples allowed us to build the examples.

**Comment by sgowroji** [comment]
Thank you for sharing your resolution. It is very helpful to community who are having a similar issue. Thanks!
