### ISSUE TITLE
Control utils 3d cdn is not working

### ISSUE THREAD

**Issue by faraznisar** [google/mediapipe#3055]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):
   Mostly the same code, just added the angle calculations for my purposes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
   Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
    Haven't tested on a mobile device
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
    Version 97.0.4692.99 (Official Build) (64-bit) google chrome
- Programming Language and version ( e.g. C++, Python, Java):
    Javascript
- [MediaPipe version](https://github.com/google/mediapipe/releases):
        <script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/control_utils_3d.js"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils/camera_utils.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils/control_utils.js"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/drawing_utils.js"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js" crossorigin="anonymous"></script>
- Bazel version (if compiling from source):
    NA
- Solution ( e.g. FaceMesh, Pose, Holistic ):
    Pose
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
   NA
- Xcode & Tulsi version (if issue is related to building for iOS):
    NA
**Describe the current behavior:**
   app.js:6 Uncaught ReferenceError: LandmarkGrid is not defined
    at app.js:6:14 in console
   Status Code: 404  (from disk cache) in network tab
**Describe the expected behavior:**
    Landmark grid should work
**Standalone code to reproduce the issue:**
   https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/control_utils_3d.js - just visit here, 404 for the file.
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:
https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/control_utils_3d.js - fix this
**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

**Comment by sgowroji** [comment]
Hi @faraznisar, Could you please verify **control_utils_3d.js** is actually loading into your script tag as mentioned here https://github.com/google/mediapipe/issues/2388#issuecomment-895407600

**Comment by faraznisar** [comment]
> Hi @faraznisar, Could you please verify **control_utils_3d.js** is actually loading into your script tag as mentioned here [#2388 (comment)](https://github.com/google/mediapipe/issues/2388#issuecomment-895407600)
![code](https://user-images.githubusercontent.com/35908301/152957699-aae854df-30be-4521-9f7a-9373697aec5f.png)
There is the entire list of CDNs that I am using.
![image](https://user-images.githubusercontent.com/35908301/152958268-05cc5dc0-ceb4-475b-834f-c2e0e671e342.png)
![image](https://user-images.githubusercontent.com/35908301/152958343-670e12e3-7a3e-461f-bace-5d74814e6490.png)
Also the screenshot of the network tab and as you can see control_utils_3d is not loading.

**Comment by tyrmullen** [comment]
You are using "drawing_utils/control_utils_3d.js" instead of "control_utils_3d/control_utils_3d.js".

Also, when checking the Network tab, I recommend using "disable cache", since otherwise the browser may not try to make the network fetches again, but may simply return cached responses (e.g. HTTP 304's).

**Comment by faraznisar** [comment]
Fix the solution api for javascript on your website.
https://google.github.io/mediapipe/solutions/pose.html#javascript-solution-api

**Comment by faraznisar** [comment]
![image](https://user-images.githubusercontent.com/35908301/153128038-a5b94ac5-f019-4ad3-88da-7899477bc8eb.png)
Now I see this issue. I see your comment here https://github.com/google/mediapipe/issues/2388#issuecomment-1033319297 
Does this mean that the solution won't work till the new version is released?
If not, is there a workaround for the time being?
In both cases, do we have an ETA on when the new version will be released?

**Comment by sgowroji** [comment]
Please refer the "disable cache" recommendation as mentioned in the above https://github.com/google/mediapipe/issues/3055#issuecomment-1033038996. ETA was about the document  update of api fix which is mentioned above.

**Comment by faraznisar** [comment]
![image](https://user-images.githubusercontent.com/35908301/153129388-f38d4d1e-f813-4015-bda3-667e8099573f.png)
No effect whatsoever.
`    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d/control_utils_3d.js"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils/camera_utils.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils/control_utils.js"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/drawing_utils.js"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js" crossorigin="anonymous"></script>`
The scripts
--------------------------------
`
    <div class="container">
        <video class="input_video"></video>
        <canvas class="output_canvas" width="1280px" height="720px"></canvas>
        <div class="landmark-grid-container"></div>
    </div>
`
The HTML
-----------------------
`
const videoElement = document.getElementsByClassName("input_video")[0];
const canvasElement = document.getElementsByClassName("output_canvas")[0];
const canvasCtx = canvasElement.getContext("3d");
const landmarkContainer = document.getElementsByClassName('landmark-grid-container')[0];
const grid = new LandmarkGrid(landmarkContainer);
`
The elements
------------------------------------
`
function onResults(results) {
    if (!results.poseLandmarks) {
        grid.updateLandmarks([]);
        return;
    }
    let landmarks = results.poseLandmarks

    const canvasCtx = canvasElement.getContext("3d")
    canvasCtx.save();
    canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
    canvasCtx.drawImage(results.image,
        0,
        0,
        canvasElement.width,
        canvasElement.height
    )
    drawConnectors(canvasCtx,
        results.poseLandmarks, POSE_CONNECTIONS,
        { color: 'green', lineWidth: 5 });
    drawLandmarks(canvasCtx, results.poseLandmarks,
        { color: 'red', lineWidth: 3, radius: 2 });
    drawLandmarks.poseLandmarks
    canvasCtx.restore();
    grid.updateLandmarks(results.poseWorldLandmarks);
}
const pose = new Pose({
    locateFile: (file) => {
        return `https://cdn.jsdelivr.net/npm/@mediapipe/pose/${file}`;
    },
});
pose.setOptions({
    modelComplexity: 1,
    smoothLandmarks: true,
    enableSegmentation: true,
    smoothSegmentation: true,
    minDetectionConfidence: 0.5,
    minTrackingConfidence: 0.5,
});
pose.onResults(onResults);

const camera = new Camera(videoElement, {
    onFrame: async () => {
        await pose.send({ image: videoElement });
    },
    width: 1280,
    height: 720
});
camera.start();
`
The rest of the code. 
------------------------------
I removed the custom code that I needed for my purposes. If needed I will add this to a repository because so far I tried everything you said but still no result.

**Comment by kuaashish** [comment]
Hello @faraznisar,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
