### ISSUE TITLE
How to save landmarks of multiple people (in one frame)

### ISSUE THREAD

**Issue by Tanmay2511** [google/mediapipe#3056]
I want to get headpose(looking left or right ) for multiple people in one frame.
How can i store facial landmarks for multiple people from one frame ?

This is code for detecting headpose of single person in one frame.

`  
import cv2
import mediapipe as mp
import numpy as np
import time

mp_drawing = mp.solutions.drawing_utils
drawing_spec = mp_drawing.DrawingSpec(thickness=1, circle_radius=1)

cap = cv2.VideoCapture(0)
mp_face_mesh = mp.solutions.face_mesh
max_num_faces = 2
face_mesh = mp_face_mesh.FaceMesh(max_num_faces=3, min_detection_confidence=0.5, min_tracking_confidence=0.5)

while cap.isOpened():
    success, image = cap.read()
    # start_time = time.time()

    # Flip the image for selfie-view display
    # Also convert the color space from BGR to RGB
    image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)

    # To improve performance
    image.flags.writeable = False

    # sotring result
    results = face_mesh.process(image)

    image.flags.writeable = True

    # color space from RGB to BGR
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    img_h, img_w, img_c = image.shape
    face_3d = []
    face_2d = []

    if results.multi_face_landmarks:
        for face_landmarks in results.multi_face_landmarks:
            for index, lm in enumerate(face_landmarks.landmark):

                if index == 33 or index == 263 or index == 1 or index == 61 or index == 291 or index == 199:
                    if index == 1:
                        nose_2d = (lm.x * img_w, lm.y * img_h)
                        nose_3d = (lm.x * img_w, lm.y * img_h, lm.z)

                    x, y = int(lm.x * img_w), int(lm.y * img_h)

                    # Get the 2D Coordinates
                    face_2d.append([x, y])

                    # Get the 3D Coordinates
                    face_3d.append([x, y, lm.z])

                    # Converting toNumPy array
            face_2d = np.array(face_2d, dtype=np.float64)

            # Converting to NumPy array
            face_3d = np.array(face_3d, dtype=np.float64)

            # The camera matrix
            focal_length = 1 * img_w
            cam_matrix = np.array([[focal_length, 0, img_h / 2],
                                   [0, focal_length, img_w / 2],
                                   [0, 0, 1]])

            # The distortion parameters
            dist_matrix = np.zeros((4, 1), dtype=np.float64)

            # Solve PnP
            success, rot_vec, trans_vec = cv2.solvePnP(face_3d, face_2d, cam_matrix, dist_matrix)

            # Get rotational matrix
            rmat, jac = cv2.Rodrigues(rot_vec)

            # Get angles of rotation
            angles, mtxR, mtxQ, Qx, Qy, Qz = cv2.RQDecomp3x3(rmat)

            # Get the y rotation degree
            x = angles[0] * 360
            y = angles[1] * 360
            z = angles[2] * 360

            # See where the user's head moving
            if y < -10 and y > -24:
                 text = "Looking Left"
                 start = time.localtime().tm_sec
            elif y > 10 and y < 24:
                text = "Looking Right"
            elif y > 24 or y < -24:
                text = "Turning Back"
            elif x < -10:
                text = "Writing"
            else:
                start = 0
                end = time.localtime().tm_sec
                text = "Looking Forward"

            print(text)

            # print(start)
            # print(end)
            left_time = abs(end - start)

            # points to draw line on nose
            p1 = (int(nose_2d[0]), int(nose_2d[1]))
            p2 = (int(nose_2d[0] + y * 10), int(nose_2d[1] - x * 10))

            cv2.line(image,p1,p2,(0,255,0),3)

            # Adding text on screen
            cv2.putText(image, text, (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0, 255), 6)
            cv2.putText(image, "x: " + str(np.round(x,2)), (500, 100), cv2.FONT_HERSHEY_SIMPLEX, 1,(0, 0, 255), 2)
            cv2.putText(image, "y: " + str(np.round(y, 2)), (500, 150), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
            cv2.putText(image, "z: " + str(np.round(z, 2)), (500, 200), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)

        mp_drawing.draw_landmarks(
            image=image,
            landmark_list=face_landmarks,
            connections=mp_face_mesh.FACEMESH_TESSELATION,
            landmark_drawing_spec=drawing_spec,
            connection_drawing_spec =drawing_spec )

        cv2.imshow('Head Pose Estimation', image)
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
print(f"Looking at left for {left_time} sec")
cap.release()

`

**Comment by sgowroji** [comment]
Hi @Tanmay2511, What is the error are you seeing in the above request?

**Comment by Tanmay2511** [comment]
In above code how can I store facial landmarks of different people detected  in frame ?

**Comment by sgowroji** [comment]
Did you try checking the same with change or adjusting the min_detection_confidence value accordingly. Can you try and let us know. Thanks!

**Comment by ahmadmustafaanis** [comment]
I am also getting a single person detected in a frame. How to do multiple detections?
![image](https://user-images.githubusercontent.com/47111429/165731073-ba58b6d4-674f-44e1-9aa0-4982a3919e41.png)
