### ISSUE TITLE
Error while running Face mesh with Refine Landmark on C++

### ISSUE THREAD

**Issue by adnan6336** [google/mediapipe#3058]
<em>Error while running Face mesh with Refine Landmark = True<em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 18.04
- [MediaPipe version](https://github.com/google/mediapipe/releases): Latest Release i-e 0.8.9
- Solution (e.g. FaceMesh, Pose, Holistic): FaceMesh
- Programming Language and version ( e.g. C++, Python, Java): C++

**I got an error when running FaceMesh C++ version on GPU with refine landmark = True**

Error:0(96) : error C1068: array index out of bonds
......
ERROR: Node number 712 (TfLiteGpuDelegate) failed to prepare
ERROR: Restored original execution plan after delegate application failure. ... demo_run_graph_main_gpu.cc:186] Shutting down. Segmentation fault (core dumped).

**To reproduce same error**,

```
cd mediapipe

bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
  mediapipe/examples/desktop/face_mesh:face_mesh_gpu

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_mesh/face_mesh_gpu \
  --calculator_graph_config_file=mediapipe/graphs/face_mesh/face_mesh_desktop_live_gpu.pbtxt
```
I have checked the similar issue on #2678 #2797 but they are closed and I can't find any solution.
it works on CPU but I need this on GPU and with refine_landmarks as they are much more accurate than the previous one wihtout iris.
Any help would be much appreciated.
Thanks for this great repo. !

**Comment by sgowroji** [comment]
Hi @adnan6336,  As mentioned in this https://github.com/google/mediapipe/issues/2678#issuecomment-989348636  .
1. Did you try this suggestions, i.e. refine_landmarks = true option actually runs a different ML model ([here](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark_with_attention.tflite))
 2. And also  try using a snapshot of tensorflow that is closer to the release date of [refine_landmarks](https://github.com/google/mediapipe/releases/tag/v0.8.8) (Oct 06, 2021)

**Comment by adnan6336** [comment]
> Hi @adnan6336, As mentioned in this [#2678 (comment)](https://github.com/google/mediapipe/issues/2678#issuecomment-989348636) .
> 
> 1. Did you try this suggestions, i.e. refine_landmarks = true option actually runs a different ML model ([here](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark_with_attention.tflite))
> 2. And also  try using a snapshot of tensorflow that is closer to the release date of [refine_landmarks](https://github.com/google/mediapipe/releases/tag/v0.8.8) (Oct 06, 2021)

Thank-you for the quick response,
The first suggestion is basically the information, I know when setting refine_landmarks = true, it runs different model and so the error while running on GPU and works flawlessly while running on CPU
The second suggestion is a bit confusion for me as I don't know how to change the tensorflow version(close to OCT 06,2021) within mediapipe, because I didn't install tensorflow or tensorflow lite seperately as it comes with mediapipe so how do I change that?

**Comment by adnan6336** [comment]
@sgowroji 
I have also tried mediapipe 0.8.8 version still got same error.

**Comment by yayu22** [comment]
i am also having same issue in python when running facemesh refined landmarks on GPU. @sgowroji @mcclanahoochie

**Comment by adnan6336** [comment]
@sgowroji  @mcclanahoochie 
Hi Guys, any direction that I work on?

**Comment by sgowroji** [comment]
@adnan6336, Thank you for being patience. We have shared your request to one of our engineer who will respond on the above query.

**Comment by mcclanahoochie** [comment]
did the update in https://github.com/google/mediapipe/issues/2678#issuecomment-1051449676 work?

**Comment by adnan6336** [comment]
> 

Thankyou for the reply brother.
Unfortunately there is no  ```use_advanced_gpu_api: true``` option in face_landmark_gpu .

For the reference:
face_landmark_gpu.pbtxt
```# Runs a TensorFlow Lite model on GPU that takes an image tensor and outputs a
# vector of GPU tensors representing, for instance, detection boxes/keypoints
# and scores.
node {
  calculator: "InferenceCalculator"
  input_stream: "TENSORS:input_tensors"
  input_side_packet: "MODEL:model"
  input_side_packet: "CUSTOM_OP_RESOLVER:op_resolver"
  output_stream: "TENSORS:output_tensors"
  options: {
    [mediapipe.InferenceCalculatorOptions.ext] {
      # Do not remove. Used for generation of XNNPACK/NNAPI graphs.
    }
  }
}
```

**Comment by adnan6336** [comment]
> did the update in [#2678 (comment)](https://github.com/google/mediapipe/issues/2678#issuecomment-1051449676) work?

Thankyou for the reply brother @mcclanahoochie 
Unfortunately there is no ```use_advanced_gpu_api: true``` option in face_landmark_gpu graph

For the reference:
face_landmark_gpu.pbtxt

```
# vector of GPU tensors representing, for instance, detection boxes/keypoints
# and scores.
node {
  calculator: "InferenceCalculator"
  input_stream: "TENSORS:input_tensors"
  input_side_packet: "MODEL:model"
  input_side_packet: "CUSTOM_OP_RESOLVER:op_resolver"
  output_stream: "TENSORS:output_tensors"
  options: {
    [mediapipe.InferenceCalculatorOptions.ext] {
      # Do not remove. Used for generation of XNNPACK/NNAPI graphs.
    }
  }
}
```

**Comment by adnan6336** [comment]
@mcclanahoochie any update?
I still couldn't fix this issue.

**Comment by adnan6336** [comment]
Any updates?

**Comment by adnan6336** [comment]
@mcclanahoochie @sgowroji , kindly let me know if there is anything I can do with this problem.
thanks

**Comment by adnan6336** [comment]
any update guys?

**Comment by adnan6336** [comment]
its been over a year this and I am still facing this issue. kindly responsd.

**Comment by adnan6336** [comment]
Sorry for the inactivity, but I have tested the new solutions, still facemesh with refine_landmark=True does not work on GPU.
