### ISSUE TITLE
CUDA 11 Support

### ISSUE THREAD

**Issue by khayyat71** [google/mediapipe#3059]
I would like to know if Mediapipe supports CUDA 11.
I'm currently intending to create a C++ project and use mediapipe as a pose detection library.

**Comment by ArashHosseini** [comment]
@khayyat71 yes, i am using it with cuda 11.4

**Comment by sgowroji** [comment]
As mentioned [here](https://google.github.io/mediapipe/getting_started/gpu_support.html#tensorflow-cuda-support-and-setup-on-linux-desktop) MediaPipe framework doesn’t require CUDA for GPU compute and rendering. However, MediaPipe can work with TensorFlow to perform GPU inference on video cards that support CUDA. 

Present you can try CUDA 10 and not have much support for 11.

**Comment by mcdonasd1212** [comment]
Are there plans for Cuda 11 support?   Has any been successful building with tensorflow?  I am looking for way to improve live video frame rate on Ubuntu i5 cpu and GTX 1660 super gpu.   The goal is displaying video with pose overlay at 30 fps from camera input at 60 fps.

**Comment by tom-doerr** [comment]
Would also be very interested in the performance aspect of the tensorflow build. Is it faster than the OpenGL one? 
The mediapipe hand tracking only gives me 30 fps instead of the 120 fps in the [benchmark](https://blog.tensorflow.org/2021/11/3D-handpose.html).
```
tom@desktop-20-3 
---------------- 
OS: Ubuntu 20.04.3 LTS x86_64 
Host: MS-7B00 1.0 
Kernel: 5.11.0-44-generic 
Uptime: 45 days, 3 hours, 37 mins 
Packages: 3547 (dpkg), 28 (snap) 
Shell: bash 5.0.17 
Resolution: 1440x2560, 2560x1440, 1080x1920 
WM: i3 
Theme: Adwaita [GTK3] 
Icons: Adwaita [GTK3] 
Terminal: kitty 
Terminal Font: Ubuntu Mono 9.0 
CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 1080 Ti 
GPU: NVIDIA GeForce GTX 1060 6GB 
Memory: 19386MiB / 64254MiB 
```

@mcdonasd1212 I wrote some code that parallelizes the calls to mediapipe, which allows you to get much higher frame rates: https://github.com/tom-doerr/mediapipe_parallel_demo

**Comment by khayyat71** [comment]
> @khayyat71 yes, i am using it with cuda 11.4
I'm using cuda 11.6 now
But trying to build the pose tracking example to use cuda, but not being successful yet...
