### ISSUE TITLE
Unable to run face_effect, graph errors out on id check

### ISSUE THREAD

**Issue by abhisaar** [google/mediapipe#3060]
I am trying to run [face_effect](https://github.com/google/mediapipe/tree/master/mediapipe/graphs/face_effect) demo which renders the face paint and glasses. It is not included in the examples so I am making a binary using the provided library '[face_effect_gpu_deps](https://github.com/google/mediapipe/blob/e6c19885c6d3c6f410c730952aeed2852790d306/mediapipe/graphs/face_effect/BUILD#L25)'

My build file is at /mediapipe/examples/desktop/face_effect/BUILD similar to other provided examples
```
cc_binary(
    name = "face_effect_gpu",
    deps = [
        "//mediapipe/examples/desktop:demo_run_graph_main_gpu",
        "//mediapipe/graphs/face_effect:face_effect_gpu_deps",
    ],
)
```

On executing this binary, I get this error:
[collection.h:417](https://github.com/google/mediapipe/blob/e6c19885c6d3c6f410c730952aeed2852790d306/mediapipe/framework/collection.h#L417) Check failed: id < EndId() (1 vs. 1)

I have been able to run all the other examples successfully on both CPU and GPU. Could you please let me know what is going wrong or provide an example to run face effects?

Build command:
`bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11   mediapipe/examples/desktop/face_effect:face_effect_gpu`

Run command (using the face_effect_gpu.pbtxt):
`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_effect/face_effect_gpu   --calculator_graph_config_file=mediapipe/graphs/face_effect/face_effect_gpu.pbtxt`

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): Modified stock example
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 20.04.3 LTS
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.9.1
- Bazel version: 4.2.1
- Solution (e.g. FaceMesh, Pose, Holistic): FaceMesh
- Programming Language and version ( e.g. C++, Python, Java): C++

**Describe the expected behavior:**
The face_effect module runs

**Other info / Complete Logs :**
I20220206 22:37:01.470067 158366 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
I20220206 22:37:01.475389 158366 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
I20220206 22:37:01.482228 158366 gl_context_egl.cc:162] Successfully initialized EGL. Major : 1 Minor: 5
I20220206 22:37:01.529899 158383 gl_context.cc:334] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 460.91.03)
I20220206 22:37:01.530066 158366 demo_run_graph_main_gpu.cc:68] Initialize the camera or load the video.
I20220206 22:37:01.701638 158366 demo_run_graph_main_gpu.cc:89] Start running the calculator graph.
I20220206 22:37:01.705971 158366 demo_run_graph_main_gpu.cc:94] Start grabbing and processing frames.
**F20220206 22:37:01.706034 158369 collection.h:417] Check failed: id < EndId() (1 vs. 1)** 
*** Check failure stack trace: ***
    @     0x56281e95b0ab  google::LogMessage::SendToLog()
    @     0x56281e95705d  google::LogMessage::Flush()
    @     0x56281e9574cd  google::LogMessageFatal::~LogMessageFatal()
    @     0x56281e885864  mediapipe::internal::Collection<>::Get()
    @     0x56281e8ae1a8  mediapipe::InputSidePacketHandler::SetInternal()
    @     0x56281e8ae9c7  mediapipe::InputSidePacketHandler::Set()
    @     0x56281e8ad16e  mediapipe::OutputSidePacketImpl::SetInternal()
    @     0x56281e8ad3b5  mediapipe::OutputSidePacketImpl::Set()
    @     0x56281e85f1f4  mediapipe::(anonymous namespace)::EnvGeneratorCalculator::Open()
    @     0x56281e8a243c  mediapipe::CalculatorNode::OpenNode()
    @     0x56281e88cebe  mediapipe::internal::SchedulerQueue::OpenCalculatorNode()
    @     0x56281e88d83b  mediapipe::internal::SchedulerQueue::RunNextTask()
    @     0x56281e8cbfe7  mediapipe::ThreadPool::RunWorker()
    @     0x56281e8ccd59  mediapipe::ThreadPool::WorkerThread::ThreadBody()
    @     0x7fda734ad609  start_thread
    @     0x7fda700de293  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by sgowroji** [comment]
Hi @abhisaar, Can you share your code changes to troubleshoot the issue. Thanks!

**Comment by abhisaar** [comment]
Thank you @sgowroji for your reply. Please find attached my build file (added a .txt so that Github will let me attach it). I am building the already provided targets at 'face_effect:face_effect_gpu_deps' and using the stock 'face_effect_gpu.pbtxt' file.

Happy to provide more details!

[BUILD.txt](https://github.com/google/mediapipe/files/8039730/BUILD.txt)

**Comment by abhisaar** [comment]
Hi Sunil, would you need any other information from me? Thank you.

**Comment by kuaashish** [comment]
Hello @abhisaar,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
