### ISSUE TITLE
Is mediapipe selfie segmentation demo runs on CPU ? 

### ISSUE THREAD

**Issue by A-KVerma** [google/mediapipe#3061]
This template is for miscellaneous issues not covered by the other issue categories

For questions on how to work with MediaPipe, or support for problems that are not verified bugs in MediaPipe, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mediapipe) and [Slack](https://mediapipe.page.link/joinslack) communities.

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/google/mediapipe/security).

For high-level discussions about MediaPipe, please post to discuss@mediapipe.org, for questions about the development or internal workings of MediaPipe, or if you would like to know how to contribute to MediaPipe, please post to developers@mediapipe.org.

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/3063
