### ISSUE TITLE
FaceMesh unable to place landmarks on faces that are relatively small.  Unable to detect relatively small faces in video?

### ISSUE THREAD

**Issue by Kiranraj227** [google/mediapipe#3064]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):
- Programming Language and version ( e.g. C++, Python, Java):

**Describe the expected behavior:**

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by Kiranraj227** [comment]
IDE: Pycharm
Python: 3.8.8
Virtual environment: Anaconda
CPU: i5 - 5th Gen
OS: Windows 10

**Comment by sgowroji** [comment]
Hi @Kiranraj227, Can you share us any references like videos, images to understand the above request much better. Thanks!

**Comment by Kiranraj227** [comment]
Hi @sgowroji, I think the video below should reproduce the same problem. You might notice when the truck driver is further away from the camera, the FaceMesh module can't detect his face.
https://www.youtube.com/watch?v=im3mzC1CPCo

**Comment by Kiranraj227** [comment]
![image](https://user-images.githubusercontent.com/71511899/153339675-2036f4d6-ad7a-4ee5-a1a4-0ece0f45b40e.png)

**Comment by Kiranraj227** [comment]
@sgowroji, Please let me know once you have downloaded the picture as I need to delete it. Thanks

**Comment by Kiranraj227** [comment]
Hi sorry, attached is the image where the landmarks are not detected.
![image](https://user-images.githubusercontent.com/71511899/154798128-bc6c3e8b-9da9-4aea-8100-66a69805ba80.png)

**Comment by Kiranraj227** [comment]
When I crop out the original image where the face takes about 70% of the image, the landmarks are detected.
![image](https://user-images.githubusercontent.com/71511899/154798286-d7db0360-8921-4252-9691-9d56a12fc42c.png)

**Comment by sgowroji** [comment]
This gives you understanding about the face tracking implementation https://github.com/google/mediapipe/issues/1895#issuecomment-822121488

**Comment by Kiranraj227** [comment]
Issue:  [#1723](https://github.com/google/mediapipe/issues/1723)

I think this issue is more relevant. From this issue, I understand that there are different models that are tailored to detect faces within 2 meters and 5 meters. So by changing to the 5-meter model it should be able to detect smaller (further away from the camera) faces right?

**Comment by SutirthaChakraborty** [comment]
Any help with how to call the use [FaceDetectionFullRangeCpu](https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_detection/face_detection_full_range_cpu.pbtxt) in python?
