### ISSUE TITLE
How does Mediapipe compare with Leap motion?

### ISSUE THREAD

**Issue by EigenSpiral** [google/mediapipe#3066]
Hi,
Are there any studies or research comparing Mediapipe hand tracking & Leap motion hand tracking? How does Mediapipe compare to Leap?

**Comment by sgowroji** [comment]
Hi @EigenSpiral, May be you can refer this https://github.com/google/mediapipe/issues/36 where community discussed about leap motion.

**Comment by ayushgdev** [comment]
@EigenSpiral are you still looking for any comparison?
