### ISSUE TITLE
Xcode Undefined symbols for architecture arm64 "absl::lts_20210324::InvalidArgumentError(absl::lts_20210324::string_view)", referenced from:       absl::lts_20210324::StatusOr<std::__1::vector<google::protobuf::MessageLite const*, std::__1::allocator<google::protobuf::MessageLite const*> > > 

### ISSUE THREAD

**Issue by fash2017** [google/mediapipe#3068]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution: MacOS Monterey version 12.1
- Compiler version: Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin21.2.0
- Programming Language and version: Objective C, swift,  
- Bazel version: bazel 5.0.0-homebrew 
- XCode and Tulsi versions (if iOS): Xcode 13.1

**Describe the problem**: I am attempting to build a custom ios ipad app that translates ASL to english using Mediapipe. I'm new to IOS and have tried to use as many tutorials as possible. When I try to build the app on Xcode i run into this issue:
<img width="840" alt="Screen Shot 2022-02-10 at 9 41 11 PM" src="https://user-images.githubusercontent.com/42719396/153529703-f7adf8f1-f0fd-4d63-921d-ce008d1d4e58.png">

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

I mainly followed this tutorial to build the application: https://medium.com/deelvin-machine-learning/how-to-build-mediapipe-on-ios-f5e4cabf47f5

I attempted to create theirs first and everything worked fine. But then when I did it again with my files I ran into the issues in the image above stating "Linking mediapipe/examples/ios/DASLapp/DASLapp_bin failed: (Aborted): wrapped_clang_pp failed: error executing command"

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

Error Log file: 
[Build target DASLapp_2022-02-10T21-14-16.txt](https://github.com/google/mediapipe/files/8045636/Build.target.DASLapp_2022-02-10T21-14-16.txt)

BUILD file: 
MIN_IOS_VERSION = "11.0"
load(
    "@build_bazel_rules_apple//apple:ios.bzl",
    "ios_application",
)
ios_application(
#Name of your application
    name = "DASLapp",
#Bundle_id – should coincide with the one mentioned in the application
    bundle_id = "ISD.DASL",
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = ["Info.plist"],
    minimum_os_version = MIN_IOS_VERSION,
#Path to your provisioning_profile file
        provisioning_profile = "//mediapipe/examples/ios/DASLapp:provisioning_profile.mobileprovision",
    deps = [
        ":DASLappLibrary",
        "@ios_opencv//:OpencvFramework",
    ],
)
objc_library(
    name = "DASLappLibrary",
    srcs = [
        "AppDelegate.m",
        "ViewController.mm",
        "ViewControllerPhrase.mm",
        "AppViewController.mm",
        "main.m",
    ],
    hdrs = [
        "AppDelegate.h",
        "ViewControllerPhrase.h",
        "ViewController.h",
        "AppViewController.h", 
    ],
    data = [
        "Base.lproj/LaunchScreen.storyboard",
        "Base.lproj/Main.storyboard",
        "//mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu_binary_graph",
        "//mediapipe/modules/hand_landmark:hand_landmark_full.tflite",
        "//mediapipe/modules/hand_landmark:handedness.txt",
        "//mediapipe/modules/palm_detection:palm_detection_full.tflite",
        "//mediapipe/models:model_targeted_a.tflite",
        "//mediapipe/models:model_targeted_b.tflite",
        "//mediapipe/models:palm_detection_labelmap.txt",
    ],
    sdk_frameworks = [
        "UIKit",
        "AVFoundation",
        "CoreGraphics",
        "CoreMedia",
    ],
    deps = [
        "//mediapipe/objc:mediapipe_framework_ios",
        "//mediapipe/objc:mediapipe_input_sources_ios",
        "//mediapipe/objc:mediapipe_layer_renderer",
        "//mediapipe/framework/formats:landmark_cc_proto",
        "//mediapipe/graphs/hand_tracking:mobile_calculators",
    ],
)

ViewController.mm:
`#import "ViewController.h"

#import "mediapipe/objc/MPPGraph.h"
#import "mediapipe/objc/MPPCameraInputSource.h"
#import "mediapipe/objc/MPPLayerRenderer.h"

#include "mediapipe/framework/formats/landmark.pb.h"

static NSString* const kGraphName = @"hand_tracking_mobile_gpu";

static const char* kInputStream = "input_video";
static const char* kOutputStream = "output_video";
static const char* kLandmarksOutputStream = "hand_landmarks";
static const char* kVideoQueueLabel = "com.google.mediapipe.example.videoQueue";

@interface ViewController () <MPPGraphDelegate, MPPInputSourceDelegate>

// The MediaPipe graph currently in use. Initialized in viewDidLoad, started in viewWillAppear: and
// sent video frames on _videoQueue.
@property(nonatomic) MPPGraph* mediapipeGraph;

@end

@implementation ViewController {
    /// Handles camera access via AVCaptureSession library.
    MPPCameraInputSource* _cameraSource;

    IBOutlet UIView *_liveView;
    /// Inform the user when camera is unavailable.
    IBOutlet UILabel* _noCameraLabel;
      /// Display the camera preview frames
    //  IBOutlet UIView* _liveView;
    //  IBOutlet UIView *_liveView;
    
    /// Render frames in a layer.
    MPPLayerRenderer* _renderer;

  /// Process camera frames on this queue.
    dispatch_queue_t _videoQueue;
}

#pragma mark - Cleanup methods

- (void)dealloc {
  self.mediapipeGraph.delegate = nil;
  [self.mediapipeGraph cancel];
  // Ignore errors since we're cleaning up.
  [self.mediapipeGraph closeAllInputStreamsWithError:nil];
  [self.mediapipeGraph waitUntilDoneWithError:nil];
}

#pragma mark - MediaPipe graph methods

+ (MPPGraph*)loadGraphFromResource:(NSString*)resource {
  // Load the graph config resource.
  NSError* configLoadError = nil;
  NSBundle* bundle = [NSBundle bundleForClass:[self class]];
  if (!resource || resource.length == 0) {
    return nil;
  }
  NSURL* graphURL = [bundle URLForResource:resource withExtension:@"binarypb"];
  NSData* data = [NSData dataWithContentsOfURL:graphURL options:0 error:&configLoadError];
  if (!data) {
    NSLog(@"Failed to load MediaPipe graph config: %@", configLoadError);
    return nil;
  }

  // Parse the graph config resource into mediapipe::CalculatorGraphConfig proto object.
  mediapipe::CalculatorGraphConfig config;
  config.ParseFromArray(data.bytes, data.length);

  // Create MediaPipe graph with mediapipe::CalculatorGraphConfig proto object.
  MPPGraph* newGraph = [[MPPGraph alloc] initWithGraphConfig:config];
  [newGraph addFrameOutputStream:kOutputStream outputPacketType:MPPPacketTypePixelBuffer];
  [newGraph addFrameOutputStream:kLandmarksOutputStream outputPacketType:MPPPacketTypeRaw];
  return newGraph;
}

#pragma mark - UIViewController methods

- (void)viewDidLoad {
  [super viewDidLoad];

  _renderer = [[MPPLayerRenderer alloc] init];
  _renderer.layer.frame = _liveView.layer.bounds;
  [_liveView.layer addSublayer:_renderer.layer];
  _renderer.frameScaleMode = MPPFrameScaleModeFillAndCrop;
  // When using the front camera, mirror the input for a more natural look.
  _renderer.mirrored = YES;

  dispatch_queue_attr_t qosAttribute = dispatch_queue_attr_make_with_qos_class(
      DISPATCH_QUEUE_SERIAL, QOS_CLASS_USER_INTERACTIVE, /*relative_priority=*/0);
  _videoQueue = dispatch_queue_create(kVideoQueueLabel, qosAttribute);

  _cameraSource = [[MPPCameraInputSource alloc] init];
  [_cameraSource setDelegate:self queue:_videoQueue];
  _cameraSource.sessionPreset = AVCaptureSessionPresetHigh;
  _cameraSource.cameraPosition = AVCaptureDevicePositionFront;
  // The frame's native format is rotated with respect to the portrait orientation.
  _cameraSource.orientation = AVCaptureVideoOrientationPortrait;

  self.mediapipeGraph = [[self class] loadGraphFromResource:kGraphName];
  self.mediapipeGraph.delegate = self;
  // Set maxFramesInFlight to a small value to avoid memory contention for real-time processing.
  self.mediapipeGraph.maxFramesInFlight = 2;
}

// In this application, there is only one ViewController which has no navigation to other view
// controllers, and there is only one View with live display showing the result of running the
// MediaPipe graph on the live video feed. If more view controllers are needed later, the graph
// setup/teardown and camera start/stop logic should be updated appropriately in response to the
// appearance/disappearance of this ViewController, as viewWillAppear: can be invoked multiple times
// depending on the application navigation flow in that case.
- (void)viewWillAppear:(BOOL)animated {
  [super viewWillAppear:animated];

  [_cameraSource requestCameraAccessWithCompletionHandler:^void(BOOL granted) {
    if (granted) {
      [self startGraphAndCamera];
      dispatch_async(dispatch_get_main_queue(), ^{
        _noCameraLabel.hidden = YES;
      });
    }
  }];
}

- (void)startGraphAndCamera {
  // Start running self.mediapipeGraph.
  NSError* error;
  if (![self.mediapipeGraph startWithError:&error]) {
    NSLog(@"Failed to start graph: %@", error);
  }

  // Start fetching frames from the camera.
  dispatch_async(_videoQueue, ^{
    [_cameraSource start];
  });
}

#pragma mark - MPPGraphDelegate methods

// Receives CVPixelBufferRef from the MediaPipe graph. Invoked on a MediaPipe worker thread.
- (void)mediapipeGraph:(MPPGraph*)graph
    didOutputPixelBuffer:(CVPixelBufferRef)pixelBuffer
              fromStream:(const std::string&)streamName {
  if (streamName == kOutputStream) {
    // Display the captured image on the screen.
    CVPixelBufferRetain(pixelBuffer);
    dispatch_async(dispatch_get_main_queue(), ^{
      [_renderer renderPixelBuffer:pixelBuffer];
      CVPixelBufferRelease(pixelBuffer);
    });
  }
}

// Receives a raw packet from the MediaPipe graph. Invoked on a MediaPipe worker thread.
- (void)mediapipeGraph:(MPPGraph*)graph
     didOutputPacket:(const ::mediapipe::Packet&)packet
          fromStream:(const std::string&)streamName {
  if (streamName == kLandmarksOutputStream) {
    if (packet.IsEmpty()) {
      NSLog(@"[TS:%lld] No hand landmarks", packet.Timestamp().Value());
      return;
    }
    const auto& landmarks = packet.Get<::mediapipe::NormalizedLandmarkList>();
    NSLog(@"[TS:%lld] Number of landmarks on hand: %d", packet.Timestamp().Value(),
          landmarks.landmark_size());
    for (int i = 0; i < landmarks.landmark_size(); ++i) {
      NSLog(@"\tLandmark[%d]: (%f, %f, %f)", i, landmarks.landmark(i).x(),
            landmarks.landmark(i).y(), landmarks.landmark(i).z());
    }
  }
}

#pragma mark - MPPInputSourceDelegate methods

// Must be invoked on _videoQueue.
- (void)processVideoFrame:(CVPixelBufferRef)imageBuffer
                timestamp:(CMTime)timestamp
               fromSource:(MPPInputSource*)source {
  if (source != _cameraSource) {
    NSLog(@"Unknown source: %@", source);
    return;
  }
  [self.mediapipeGraph sendPixelBuffer:imageBuffer
                            intoStream:kInputStream
                            packetType:MPPPacketTypePixelBuffer];
}

@end
`

Any help will be great please. I have looked at the various issues that were similar to mine but none of them provided any solutions that has worked so please don't mark this as a duplicate. Thank you!

**Comment by sgowroji** [comment]
Hi @fash2017, Did you get a chance to check this similar https://github.com/google/mediapipe/issues/2147

**Comment by fash2017** [comment]
Accidentely closed this my bad. Yes i took a look at that link as well. It did not provide any helpful solutions.

**Comment by sureshdagooglecom** [comment]
Hi @fash2017 ,
We don't support to  support MAC OS Arm64 in MediaPipe due to limited support we have but sharing this with internal team.
