### ISSUE TITLE
Python implementation of Object Detection

### ISSUE THREAD

**Issue by AsRaNi1** [google/mediapipe#3069]
<em>The Object detection using python is done using dnn module of cv2 and thus I can contribute to this feature</em>

Uses pre-trained weights for object detection and a labels file that names the objects detected

- MediaPipe Solution (you are using): using cv2 for object detection
- Programming language: Python
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state:**

**Will this change the current api? How?**
This will be a new feature added into the mediapipe python library and no changes in the API will occur

**Who will benefit with this feature?**
The end-user of mediapipe will surely benefit from this since computer vision and machine learning is mostly carried out using python so such a feature will also help in the organization's growth

**Please specify the use cases for this feature:**
The program detects objects in the frame, in both video and in an image, the video is taken as an input and the CNN takes over for detecting the objects

Example of object detection by the program shown through a GIF:
![image](https://user-images.githubusercontent.com/84843295/153655205-a7fe8fe6-6079-45a4-b9bb-dbb1b799c75f.png)

**Comment by sgowroji** [comment]
Thank you for sharing your request. Please share your PR contributions for the above request.

**Comment by AsRaNi1** [comment]
Yes, sending a PR request

**Comment by innat** [comment]
@sgowroji Please reopen this issue. It shouldn't be closed. 
cc. @AsRaNi1
