### ISSUE TITLE
setup_opencv's make -j can "hang" due to excessive parallelism

### ISSUE THREAD

**Issue by mncharity** [google/mediapipe#307]
`setup_opencv.sh` uses `make -j` without a numeric argument, so make "will not limit the number of jobs that can run simultaneously".[man make]

The opencv build seems to peak at around 150 jobs.

Not all systems can gracefully handle 150 simultaneous compiler processes.  Possible outcomes include interminable or failed compilation, and an unresponsive or damaged system.

This unusually degree of parallelism can be reduced with little performance cost.  On one 6/12 hexacore 32GB SSD system, the current `make -j` took 160 s.  A `make -j 16` was within 1% and 1 second of that.   A `make -j 8` was around 10% slower.   Both avoid hanging an old 2/4 16GB HDD laptop.  As does `make -j 32`.

Recommendation: replace the current `make -j` with `make -j 16`.

**Comment by jiuqiant** [comment]
Thanks for the suggestion. Fixed in https://github.com/google/mediapipe/commit/38ee2603a7faf46d4283daaf73e455912307f0ff.
