### ISSUE TITLE
Docker Build Fails

### ISSUE THREAD

**Issue by AmitMY** [google/mediapipe#3071]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): `macOS + M1`

**Describe the problem**:
```sh
git clone https://github.com/google/mediapipe.git
cd mediapipe
 docker build --tag mediapipe .
```

Error:

> [10/14] RUN pip3 install tensorflow==1.14.0:
#13 0.800 Collecting tensorflow==1.14.0
#13 1.441   Could not find a version that satisfies the requirement tensorflow==1.14.0 (from versions: )
#13 1.442 No matching distribution found for tensorflow==1.14.0

**Complete Logs:**
![image](https://user-images.githubusercontent.com/5757359/153770664-9c666a01-7c9d-4f01-adad-d0c2ce1a0658.png)

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/3070

**Comment by AmitMY** [comment]
Not a duplicate...
This is using *your* Dockerfile, and it doesn't build as is.

**Comment by ingyeomental** [comment]
I solved this way
```
FROM tensorflow/tensorflow:1.14.0
```
and comment out

```
# RUN pip3 install tensorflow==1.14.0
...
# RUN ln -s /usr/bin/python3 /usr/bin/python
```
