### ISSUE TITLE
Poor Results when using Depth from Iris on Google Pixel 6

### ISSUE THREAD

**Issue by Kazanian2** [google/mediapipe#3072]
Hello,

we tested MediaPipe's depth from iris algorithm on different Android phones. While it works great on most phones, there is quite a big deviation when using Google Pixel 6. The test setup was to place the phone at a distance of 50cm from the users face. On Pixel 6 it calculates a distance of 44cm (6cm deviation), while it works almost perfectly on Pixel 4a or Pixel 5 (for example). All tests where done without glasses or contact lenses.

I did some research and the specs of the front cameras of Pixel 4a, 5 and 6 that can be found online look similar. MediaPipe's algorithm uses the physical sensor width and focal length of front camera to calculate the focal length in pixels which is in turn used to estimate the iris distance. This is the snippet of the MediaPipe code:

```
// Computes the focal length of the camera in pixels based on lens and sensor properties.
  private float calculateFocalLengthInPixels() {
    // Focal length of the camera in millimeters.
    // Note that CameraCharacteristics returns a list of focal lengths and there could be more
    // than one focal length available if optical zoom is enabled or there are multiple physical
    // cameras in the logical camera referenced here. A theoretically correct of doing this would
    // be to use the focal length set explicitly via Camera2 API, as documented in
    // https://developer.android.com/reference/android/hardware/camera2/CaptureRequest#LENS_FOCAL_LENGTH.
    float focalLengthMm =
        cameraCharacteristics.get(CameraCharacteristics.LENS_INFO_AVAILABLE_FOCAL_LENGTHS)[0];
    // Sensor Width of the camera in millimeters.
    float sensorWidthMm =
        cameraCharacteristics.get(CameraCharacteristics.SENSOR_INFO_PHYSICAL_SIZE).getWidth();
    return frameSize.getWidth() * focalLengthMm / sensorWidthMm;
  }
```

The Google Pixel 6 has only one front camera, so there is no possibility the wrong focal length is selected. The sensor width is the same for Pixel 4a, 5 and 6, so this can't be the difference either. Investigating the focal length of the cameras, revealed this:

Pixel 4a -> focal length = 2.57 mm
Pixel 5 -> focal length = 2.57 mm
Pixel 6 -> focal length = 2.51 mm

Seems like there is a difference in the camera. Or maybe the wrong value is set in the camera characteristics? But when I change the code to use a focal length of 2.57mm for the Pixel 6 instead, the calculated is distance is something like 46cm. So, it is a bit closer to the expected value of 50cm, but there is still a deviation of 4cm.

Can you please help me figure out what the reason for the deviation might be? 
Could it be that Google put the wrong focal length in the camera characteristics?
Or are there other factors which are not considered in the algorithm that come into play on this specific phone?

Any help is appreciated!
Thank you!

**Comment by sgowroji** [comment]
Hi @Kazanian2, Thank you for reaching us regarding the above issue. Could you please provide any more references to illustrate the above scenario with any recording or observations.

**Comment by Kazanian2** [comment]
Hi @sgowroji,
recordings wouldn't help any further because they could only show a distance value that is incorrect. All my observations I have already written above.

If you have a Google Pixel 6 for testing at hands, maybe you can also try the depth from iris example and measure if the calculated distance is correct.
https://google.github.io/mediapipe/solutions/iris.html

**Comment by Kazanian2** [comment]
I took a picture of a printed circle and performed the distance calculation by hand using 2.51mm as focal length. The resulting distance was correct. This proves that the focal length is correct.

The image dimensions and sensor width that are used by MediaPipe during calculation also look correct. I have the feeling that the image is zoomed. Because the calculated iris size in pixels is greater compared to the one on Pixel 4a. But the values for linear zoom and zoom ratio indicate that no zoom is active.

Do you have any ideas what might cause the problem?
Are you able to reproduce this on a Google Pixel 6?

**Comment by Kazanian2** [comment]
Any ideas on this?

**Comment by kuaashish** [comment]
Hello @Kazanian2,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
