### ISSUE TITLE
While extracting keypoint values, it says "AttributeError: landmarks"

### ISSUE THREAD

**Issue by BaiduriRazak** [google/mediapipe#3075]
len(results.left_hand_landmarks.landmarks)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [11], in <module>
----> 1 len(results.left_hand_landmarks.landmarks)

AttributeError: landmarks

**Comment by sgowroji** [comment]
Similar https://github.com/google/mediapipe/issues/2882#issuecomment-998579772
