### ISSUE TITLE
iOS PoseTrackingGpuApp joints flickering issue

### ISSUE THREAD

**Issue by pratimash** [google/mediapipe#3078]
Hi Team, I was checking iOS PoseTrackingGpuApp app. in iPhone 11, 14.3.
 Even if person is standing still, we can see points are moving. Ex. If we observe elbow joint its moving a lot. 
 I have attached the video for the reference.

https://user-images.githubusercontent.com/71701808/154037991-6ca35bdf-fb7c-4dcd-8830-4e778df8bd2e.mp4

Is there any settings, through which we get better stable poses?

**Comment by zzmicer** [comment]
Hey @pratimash,
Actually, it's quite good performance for real-time solution. However, you can check LandmarksSmoothingCalculator in PoseLandmarkFiltering graph. You might want to research one_euro_filter implementation and play with its parameters.
