### ISSUE TITLE
Python wheel with GPU graphs for Linux

### ISSUE THREAD

**Issue by juvekaradheesh** [google/mediapipe#3079]
Could you please provide the wheel with the GPU graphs for Linux (I need for face mesh)? Not asking you to update on PyPI but just upload somewhere so that Linux users can directly access it. I would be extremely grateful. Thanks!

@jiuqiant

**Comment by qtw1998** [comment]
The same

**Comment by juvekaradheesh** [comment]
Thanks for the reply! I guess we don't have it for [face landmark detection](https://developers.google.com/mediapipe/solutions/vision/face_landmarker) yet. Hope it comes out soon! Also, can you guide us to some docs to run the new Python API on GPU?

**Comment by kuaashish** [comment]
@juvekaradheesh,
This is in our roadmap. Will provide updates when it becomes available. Thank you
