### ISSUE TITLE
WSL install fails due to missing unzip

### ISSUE THREAD

**Issue by mncharity** [google/mediapipe#308]
Yesterday I observed a first-time install of WSL (Ubuntu), and of mediapipe.  The "Install Windows ADB" step was skipped, and the setup_opencv.sh option was used (with a tweaked `make -j 4`).

The mediapipe install failed because command `unzip` was missing, and was rescued by apt-get install'ing it.

The "Install the needed packages" step already includes a package `zip`, which does *recommends* package `unzip`.[1](https://packages.ubuntu.com/eoan/zip)  But the current installation instructions have apt-get install called with `--no-install-recommends`, so unzip isn't installed.

Recommendation: Add unzip to the apt-get install in step "4. Install the needed packages."

**Comment by jiuqiant** [comment]
Thanks for the suggestion. Fixed in https://github.com/google/mediapipe/commit/38ee2603a7faf46d4283daaf73e455912307f0ff.
