### ISSUE TITLE
Mediapipe error in hand tracking

### ISSUE THREAD

**Issue by EigenSpiral** [google/mediapipe#3084]
I was using the mediapipe hand tracking and noticed two instances where the estimated motion doesn't match the actual motion. Any idea on what causes this? What can I do to get better results?
 
Instance 1: https://youtu.be/-BFybUdPpK0

Instance 2: https://youtu.be/KNZbXx9hPzo

**Comment by sgowroji** [comment]
Hi @EigenSpiral,  Which platform are you referring the above. Thanks!

**Comment by EigenSpiral** [comment]
Hi, what do you mean by platform? The youtube videos show the mediapipe tracking of the hands, but as shown in the above clips it is not matching the actual motion of the hand -- while the finger is folding mediapipe is showing a straight finger

**Comment by sgowroji** [comment]
@EigenSpiral, Is it implemented through python, javascript or others? .Could you please help me in reproducing the same with complete steps at our end. Thanks!
