### ISSUE TITLE
flags.h not found in absl/flags folder

### ISSUE THREAD

**Issue by chauncey1213** [google/mediapipe#3086]
I successfully executed
`bazel-bin\mediapipe\examples\desktop\hand_tracking\hand_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt`

Then I use vs2019 to coding c++
When I code
`#include"absl/flags/flag.h"`
vs2019 return "cannot open source file"absl/flags/flag.h"",
so I opened absl/flags folder and foung flag.h wasn't in the folder

Is there any solution please?

**Comment by sureshdagooglecom** [comment]
Hi @chauncey1213 could you provide steps to reproduce this issue?

**Comment by chauncey1213** [comment]
@sureshdagooglecom 
I wrote only the following.

```
#include<iostream>
#include<opencv2/opencv.hpp>
#include"absl/flags/flag.h"
```
And the errors are
```
Error	        C1083	Cannot open include file: 'absl/flags/flag.h': No such file or directory
Error (active)	E1696	cannot open source file "absl/flags/flag.h"
```

**Comment by chauncey1213** [comment]
@sureshdagooglecom 
If you find any solution, please tell me, thanks.

**Comment by chauncey1213** [comment]
@sureshdagooglecom 
I successfully solved the problem, thank you for your help!

**Comment by Yang-lin-09** [comment]
@chauncey1213 
Hello, I encountered the same problem when cross-compiling, how did you solve it?
