### ISSUE TITLE
Mediapie hands full model less accurate than light model

### ISSUE THREAD

**Issue by MJ1998** [google/mediapipe#3089]
- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu
- Programming Language and version ( e.g. C++, Python, Java): Python
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.9.1
- Solution ( e.g. FaceMesh, Pose, Holistic ): Hands

Full model does not detect hand in an image where is present whereas the light model does.

Since full model is supposed to perform better than light model, with min_detection_confidence set to 0.5, it should detect hand in an image where light model detected hand with same min_detection_confidence (actual confidence even higher)

Update: Infact this happens for lots of images, approximately 7% from a dataset size of 50k that I have.

**Comment by sureshdagooglecom** [comment]
Hi @MJ1998 , did you get time to check on this [2173](https://github.com/google/mediapipe/issues/2173) issue , i hope it helps you .

**Comment by MJ1998** [comment]
Hi @sureshdagooglecom in [comment ](https://github.com/google/mediapipe/issues/2173#issuecomment-974162810) it says "model quality depend not only on model capacity, but also on training dataset and target domain" so its possible and understandable. 

But ideally it should not be working this way is what I am conveying here.

**Comment by ayushgdev** [comment]
@MJ1998 This is an interesting observation. However, we cannot investigate on this due to lack of dataset you are using. 
Would it be possible for you to provide the dataset it it does not violate intellectual property rights? it can be the case that the full model is not able to detect hand in a certain orientation/color/exposure conditions of the image.
