### ISSUE TITLE
Terminal freezes trying to extract iris landmarks from frame.

### ISSUE THREAD

**Issue by Fima2003** [google/mediapipe#3090]
**System information**
- I have added a couple of lines to demo_run_graph_main:
- - `#include "mediapipe/calculators/util/landmarks_to_render_data_calculator.pb.h"`
- - `#include "mediapipe/framework/formats/landmark.pb.h"`
- - `constexpr char kDetectionsStream[] = "face_landmarks_with_iris";`
- - `ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller poller_detection,`
`                   graph.AddOutputStreamPoller(kDetectionsStream));`
- - `mediapipe::Packet detection_packet;`
`    if (!poller_detection.Next(&detection_packet)) break;`
    `auto& output_landmarks = detection_packet.Get<std::vector<::mediapipe::NormalizedLandmarkList>>();`
   ` for (const ::mediapipe::NormalizedLandmarkList& normalizedlandmarkList : output_landmarks) {`
        `LOG(INFO) << normalizedlandmarkList.DebugString();`
    `}`
- MacOS on M1
- Mediapipe version: Latest version 
- Bazel version: 4.2.1
- Iris Solution
- Using C++

I want the program to show me the landmarks of face and iris + show the resulting live-stream with these landmarks on my face

It writes everything up to `INFO: Created TensorFlow Lite XNNPACK delegate for CPU.`

**Comment by sureshdagooglecom** [comment]
Hi @Fima2003, Please provide steps to reproduce this issue.

**Comment by Fima2003** [comment]
Hi! I wanted to print out the landmarks of my face with iris at each frame the program gets, for that i added another output channel in the program, called kDetectionStream. Then I assigned a poller poller_detection to this output stream and finally, I run the poller. So, at the end I am supposed to get the landmarks of my face and iris in my output_landmarks variable, but for some reason it doesn't even open the window, that shows the camera output. Here is my full code: https://pastebin.com/H8JV6hsM

So, my question is why? What is the problem. A little bit of debugging showed me that it takes forever to process if `(!poller_detection.Next(&detection_packet)) break;`

**Comment by Fima2003** [comment]
Hi! I wanted to print out the landmarks of my face with iris at each frame the program gets, for that i added another output channel in the program, called kDetectionStream. Then I assigned a poller poller_detection to this output stream and finally, I run the poller. So, at the end I am supposed to get the landmarks of my face and iris in my output_landmarks variable, but for some reason it doesn't even open the window, that shows the camera output. Here is my full code: https://pastebin.com/H8JV6hsM

A little bit of debugging showed me that it takes forever to process
if (!poller_detection.Next(&detection_packet)) break;

So, my question is why does it freeze there?
