### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by pythonsql21** [google/mediapipe#3092]
As mentioned in the paper: "MediaPipe Hands: On-device Real-time Hand Tracking", what is the commercial 3D
hand model tool did you use to generate your synthetic data?

**Comment by pythonsql21** [comment]
I refer to the hand media pipe. Please refer to this paper: https://arxiv.org/abs/2006.10214. In the data generation step, the Google team used a synthetic dataset generated using the commercial 3D hand model tool. I wanted to know what tool/software did the team use to generate a synthetic hand dataset? I am planning to make the same synthetic dataset for my ML project. thx.

**Comment by sgowroji** [comment]
Hi @pythonsql21, As mentioned the output results with 21 3D landmarks you can generate the same with any platform your are familiar with by using  [world landmarks](https://google.github.io/mediapipe/solutions/hands#multi_hand_world_landmarks).  You can try building one such with [Three.js – JavaScript 3D Library](https://threejs.org/) if you wanted to target it on JavaScript. Same if you are planning to build on Python you can refer mplot3d library. This https://github.com/google/mediapipe/issues/851#issuecomment-651990259 gives you more information about the synthetic images used.

**Comment by pythonsql21** [comment]
@sgowroji Thank you for your prompt response.
