### ISSUE TITLE
How to set min_detection_confidence & min_tracking_confidence in C++

### ISSUE THREAD

**Issue by June1124** [google/mediapipe#3094]
Hi, I can set these two params in python, but can't set them in C++,
it can be set in a config file or another method?

**Comment by JH-Lam** [comment]
> Hi @June1124 , you can set configurations , please see the appropriate calculators. for min_detection_confidence - [min_Score](https://github.com/google/mediapipe/blob/d4bb35fe5a44b3419ca86e4c7ecbc931dded2122/mediapipe/modules/palm_detection/palm_detection_gpu.pbtxt#:~:text=min_score_thresh%3A%200.5) for min_tracking_confidence- [threshold](https://github.com/google/mediapipe/blob/6abec128edd6d037e1a988605a59957c22f1e967/mediapipe/modules/pose_landmark/tensors_to_pose_landmarks_and_segmentation.pbtxt#:~:text=%7D-,%23%20Applies%20a%20threshold%20to%20the%20confidence%20score%20to%20determine%20whether,%7D,-%23%20Drops%20input%20tensors)

that seems not the answer to the problem

**Comment by TamyGit** [comment]
I am facing this problem too.
I know how to change it statically.
 -> [pose_detection_cpu.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection_cpu.pbtxt#L131)
But, I want to change it at runtime.
There is a hint, but I have no idea how to do it.
https://google.github.io/mediapipe/getting_started/faq.html#how-to-change-settings-at-runtime
