### ISSUE TITLE
Confusion between the framework and the toolkit.

### ISSUE THREAD

**Issue by kXborg** [google/mediapipe#3095]
Hi,
<br>
I am a bit confused with the MediaPipe toolkit. The following diagram was presented in the **MediaPipe Overview Talk - Google Seattle 13 Feb 2020**. Can someone clear the following doubts?
<br>
![Screenshot 2022-02-18 224110](https://user-images.githubusercontent.com/55614432/154730038-e0bcb2bc-1019-4252-b37b-bd9b518383b8.jpg)
<br>
![Screenshot 2022-02-18 223322](https://user-images.githubusercontent.com/55614432/154729052-be603194-cc27-40b4-b012-51abb305d529.jpg)
<br>
1. Is the MediaPipe framework and MediaPipe Toolkit the same?
2. Are the APIs ( Graph construction, execution, and Calculator) called Toolkit?
3. What is the overall relationship between the solutions, framework, and Toolkit?

**Comment by sureshdagooglecom** [comment]
Hi @kXborg , we have media pipe framework for different [platforms](https://google.github.io/mediapipe/getting_started/getting_started.html) and also we have different [solutions](https://google.github.io/mediapipe/solutions/solutions.html) , we have different use cases for different platforms and media pipe is also one of the tool kit for  deep learning use cases.

**Comment by kXborg** [comment]
Hi @sureshdagooglecom , thanks for replying. But my question is regarding the MediaPipe Toolkit and its components. If you could answer the following question number-wise, that would be very helpful.

1. Is **Toolkit** = **framework** + **solutions**?

2. From the second image given above, what does **Applications(Desktop/Server. Android, iOS, Embedded)** mean? Does it refer to the MediaPipe solutions?

**Comment by sureshdagooglecom** [comment]
Hi @kXborg , 
1) Is Toolkit = framework + solutions --yes 
2)From the second image given above, what does Applications(Desktop/Server. Android, iOS, Embedded) mean? Does it refer to the MediaPipe solutions-- yes it is media pipe solutions where it can be used in different applications.
