### ISSUE TITLE
Frame Freeze using HumanPose 

### ISSUE THREAD

**Issue by mcdonasd1212** [google/mediapipe#3097]
Ubuntu 18.02 Python 3.7 OpenCV 4 with i5 cpu and GTX 1660 Super GPU.   Mediapipe has been compiled with OpenGL ES.

When streaming from a webcam (1920 x 1080 @ 60 fps), the video is freezing after a few frames.   Any recommendations?

**Comment by sureshdagooglecom** [comment]
Hi @mcdonasd1212 ,can you please recorded video and code changes  to investigate further.

**Comment by mcdonasd1212** [comment]
The issue was related to memory usage from the camera. This can be considered closed.
