### ISSUE TITLE
synchronize two input streams

### ISSUE THREAD

**Issue by Billccx** [google/mediapipe#3098]
**System information** (Please provide as much relevant information as possible)
- written custom code
- Solution: Pose
- Programming Language: C++

Dear researchers:
I am working on a project about pose estimation. Here is my plan:
(1) utilize 2 cameras, getting videos from different viewpoint. 
(2) run mediapipe pose tracking algorithm on two videos respectively, and get the landmarks from two different viewpoints. 
(3) After that, using triangulation to merge two sets of landmarks from different viewpoint.

I want to synchronize two input streams of the "TriangulationCalculator", which is defined by myself.  
Here is the graph I designed (adapted from mediapipe/mediapipe/graphs/pose_tracking/pose_tracking_cpu.pbtxt):

```
input_stream: "input_video0"
input_stream: "input_video1"

output_stream: "output_landmarks"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video0"
  input_stream: "input_video1"
  input_stream: "FINISHED:output_landmarks"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video0"
  output_stream: "throttled_input_video1"
}

# Subgraph that detects poses and corresponding landmarks.
node {
  calculator: "PoseLandmarkCpu"
  #input_side_packet: "ENABLE_SEGMENTATION:enable_segmentation"
  input_stream: "IMAGE:throttled_input_video0"
  output_stream: "LANDMARKS:pose_landmarks0"
  output_stream: "WORLD_LANDMARKS:pose_world_landmarks0" 
  #output_stream: "SEGMENTATION_MASK:segmentation_mask0"
  output_stream: "DETECTION:pose_detection0"
  output_stream: "ROI_FROM_LANDMARKS:roi_from_landmarks0"
}

node {
  calculator: "PoseLandmarkCpu"
  #input_side_packet: "ENABLE_SEGMENTATION:enable_segmentation"
  input_stream: "IMAGE:throttled_input_video1"
  output_stream: "LANDMARKS:pose_landmarks1"
  output_stream: "WORLD_LANDMARKS:pose_world_landmarks1" 
  #output_stream: "SEGMENTATION_MASK:segmentation_mask1"
  output_stream: "DETECTION:pose_detection1"
  output_stream: "ROI_FROM_LANDMARKS:roi_from_landmarks1"
}

node{
  calculator: "TriangulationCalculator"
  input_stream: "NORM_FILTERED_LANDMARKS:0:pose_landmarks0"
  input_stream: "NORM_FILTERED_LANDMARKS:1:pose_landmarks1"
  output_stream: "FUSED_NORM_FILTERED_LANDMARKS:output_landmarks"
}



```
Calculator "PoseLandmarkCpu" is predefined by mediapipe (mediapipe/mediapipe/modules/pose_landmark/pose_landmark_cpu.pbtxt), I just use it in my project directly. 

The input stream "input_video0" and "input_video1" have same timestamp, but I don't know whether "pose_landmarks0" and "pose_landmarks1" have same timestamp. (pose_landmarks0 is related with input_video0 while pose_landmarks1 is related with input_video1)

**How to synchronize two input streams** ("pose_landmarks0" and "pose_landmarks1") **of "TriangulationCalculator", to ensure that "pose_landmarks0" is the result of "input_video0" and "pose_landmarks1" is the result of "input_video1" ?** ("input_video0" and "input_video1" have same timestamp)

Please forgive my confusing description. If you failed to understand my question, please let me know and I will explain it in detail. 

Thanks in advance and I'm looking forward to your reply.

**Comment by sureshdagooglecom** [comment]
Hi  @Billccx , please check this [issue](https://github.com/google/mediapipe/issues/401) for two different inputs.
