### ISSUE TITLE
Seg Fault 11 when building object-tracking demo (Mac M1 with Rosetta) 

### ISSUE THREAD

**Issue by abertics** [google/mediapipe#3099]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution: macOS 12.0.1; Hardware: MacBook Air (M1, 2020)
- Bazel version: 4.2.1
- OpenCV version (if running on desktop): 3.4.16

**Describe the problem**:
I am just trying to get the out-of-the-box desktop examples running. After much effort, hello_world works, but none of the other (hand tracking or box tracking) do.

I followed the instructions to set up on mac, but could not get hello_world to compile. There is a tragic lack of compatibility with M1. I saw this open issue https://github.com/google/mediapipe/issues/1514 and followed all the suggestions, and could still not get it to build. 

I then tried to use docker, but ran into a dead end there as well, also related to M1.

I finally used Rosetta 2 and installed x86_64 versions of brew, python, and bazelisk and was able to get hello_world to build and run successfully. But, if I try any of the other demos that actually do something, nothing builds. First I run into an error locating opencv, but it resolves itself when I update the directory in the WORKSPACE file. I get a Segmentation fault: 11 error.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

bazel86 build -c opt  --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/object_tracking:object_tracking_cpu --sandbox_debug --verbose_failures

**Complete Logs:**

INFO: Analyzed target //mediapipe/examples/desktop/object_tracking:object_tracking_cpu (120 packages loaded, 5731 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /private/var/tmp/_bazel_abbybertics/c49fc0191f0f60f315193467a8b12248/sandbox
ERROR: /Users/abbybertics/Desktop/vball-video/try3/mediapipe/mediapipe/graphs/tracking/subgraphs/BUILD:120:26: Executing genrule //mediapipe/graphs/tracking/subgraphs:renderer_cpu_inc failed: (Segmentation fault): sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_abbybertics/c49fc0191f0f60f315193467a8b12248/sandbox/darwin-sandbox/61/execroot/mediapipe && \
  exec env - \
    PATH=/Users/abbybertics/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-x86_64/bin:/Users/abbybertics/opt/anaconda3/bin:/Users/abbybertics/opt/anaconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    TMPDIR=/var/folders/zm/wfc1rvmj47134sp7zlfpr35m0000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_abbybertics/c49fc0191f0f60f315193467a8b12248/sandbox/darwin-sandbox/61/sandbox.sb /var/tmp/_bazel_abbybertics/install/d3bd16a8b22c859ba58f5dca04a9b1aa/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/mediapipe/framework/tool/encode_as_c_string "bazel-out/darwin-opt/bin/mediapipe/graphs/tracking/subgraphs/renderer_cpu.binarypb" > "bazel-out/darwin-opt/bin/mediapipe/graphs/tracking/subgraphs/renderer_cpu.inc"')
/bin/bash: line 1: 84686 Segmentation fault: 11  bazel-out/host/bin/mediapipe/framework/tool/encode_as_c_string "bazel-out/darwin-opt/bin/mediapipe/graphs/tracking/subgraphs/renderer_cpu.binarypb" > "bazel-out/darwin-opt/bin/mediapipe/graphs/tracking/subgraphs/renderer_cpu.inc"
Target //mediapipe/examples/desktop/object_tracking:object_tracking_cpu failed to build
INFO: Elapsed time: 62.953s, Critical Path: 29.72s
INFO: 102 processes: 50 internal, 52 darwin-sandbox.
FAILED: Build did NOT complete successfully

**Comment by sureshdagooglecom** [comment]
Hi @abertics , did you try in checking media pipe official [documentation](https://google.github.io/mediapipe/getting_started/install.html#installing-on-macos) to install in Mac and also please try to check this [steps](https://www.codestudyblog.com/cs2112pyc/1230193450.html) to install.

**Comment by abertics** [comment]
Yes, I first used the official documentation to install, but it didn't work. It ended with a "symbol not found in flat namespace '_CFRelease'" error that I couldn't figure out how to resolve.

**Comment by sureshdagooglecom** [comment]
Hi @abertics , did you get a chance to check [this](https://github.com/google/mediapipe/issues/1514) issue.

**Comment by abertics** [comment]
@sureshdagooglecom yes, I did. I linked to it in my original post. Initially tried everything mentioned in there, but it is still not resolved. That led me to try using x86_64 architecture with Rosetta, which led me to the current bug that I have.

**Comment by ayushgdev** [comment]
Hi @abertics 
For error message _symbol not found in flat namespace '\_CFRelease'"_
Find the 
```
cc_library(
           name = "status"
```
 in file mediapipe/mediapipe/framework/port/BUILD in your mediapipe workspace(folder).
Add following snippet in the cc_library():
```
linkopts = select({
        "//mediapipe:macos": [
            "-framework CoreFoundation",
        ],
        "//conditions:default": [],
    }),
```
This should resolve the issue.
