### ISSUE TITLE
running build_binary_graphs > error: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by chenlize96** [google/mediapipe#3101]
I'm trying to build MediaPipe Python Package on Windows by following the corresponding [tutorial](https://google.github.io/mediapipe/getting_started/python.html#ready-to-use-python-solutions).
When executing the last step: python setup.py install --link-opencv, the following error information comes:

> (mp_env) C:\Users\chenl\Desktop\mediapipe>python setup.py install --link-opencv
> C:\Users\chenl\Desktop\virtual\mp_env\lib\site-packages\setuptools\dist.py:477: UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
>   warnings.warn(
> running install
> running build_binary_graphs
> error: [WinError 2] The system cannot find the file specified
> 

I checked my bazel version, and it could compile hello-world successfully.
(mp_env) C:\Users\chenl\Desktop\mediapipe>bazel --version
bazel 4.2.1
Can anyone help me solve this problem?

**Comment by sureshdagooglecom** [comment]
Hi @chenlize96 , [duplicate issue](https://github.com/google/mediapipe/issues/1602).

**Comment by chenlize96** [comment]
@sureshdagooglecom It is not duplicate.
Firstly, the outputs are quite different.
Secondly, I have tried "bazel clean --expunge", but it shows the same error.

**Comment by sgowroji** [comment]
@chenlize96, Which version of Python are you using? Did you refer this https://github.com/google/mediapipe/issues/1325

**Comment by chenlize96** [comment]
> @chenlize96, Which version of Python are you using? Did you refer this #1325

It is 3.8.10. #1325 is not the same issue. I do not want to use 'pip3 install mediapipe' to install mediapipe. Instead, I use the installation tutorial to install it step by step.

**Comment by sureshdagooglecom** [comment]
@chenlize96, as per the [document](https://google.github.io/mediapipe/getting_started/python.html#:~:text=Download%20the%20latest%20protoc%20win64%20zip%20from%20the%20Protobuf%20GitHub%20repo%2C%20unzip%20the%20file%2C%20and%20copy%20the%20protoc.exe%20executable%20to%20a%20preferred%20location.%20Please%20ensure%20that%20location%20is%20added%20into%20the%20Path%20environment%20variable.). Did you  Download the latest protoc win64 zip and which release you have downloaded?.

**Comment by chenlize96** [comment]
@sureshdagooglecom yes, I downloaded 3.19.4-64. Also I added it into my path

**Comment by sureshdagooglecom** [comment]
@chenlize96 ,did you install OpenCV if yes what is the version?

**Comment by chenlize96** [comment]
@sureshdagooglecom The version of OpenCV is 3.4.10, and it was installed at C:\opencv. However, when I tried "import cv2" in python, it raised an error 'no module found', so I inputted 'pip3 install opencv-python'. Both two ways led to the same error mentioned above

**Comment by sureshdagooglecom** [comment]
@chenlize96 ,
1)First do run these commands inside Terminal/CMD:
conda update anaconda-navigator  
conda update navigator-updater
2)For windows if you have anaconda installed, you can simply do:
pip install opencv-python or conda install -c https://conda.binstar.org/menpo opencv.
please try above commands.

**Comment by chenlize96** [comment]
@sureshdagooglecom Thanks. However, I need to avoid using anaconda. I have already tried 'pip3 install opencv-python' then 'import cv2' works. My question is that there is an error when I run 'running build_binary_graphs' OR 'python setup.py install --link-opencv'

**Comment by chenlize96** [comment]
@sureshdagooglecom My pip is the latest version.

**Comment by chenlize96** [comment]
Can anyone help me please?

**Comment by chenlize96** [comment]
Solved. Find subprocess.py in your lib，CTRL+f to search 'class Popen', replace 'shell = False' with 'shell = True' in __init__.
However, new errors happened. They are about python path invalid. I closed this issue about this topic. Thanks all your help.

**Comment by chenlize96** [comment]
If someone meets the similar issue like invalid python path, please add 'PYTHON_LIB_PATH' into your environmental variables, its value is 'C:\Users\chenl\AppData\Local\Programs\Python\Python38\Lib'  (this path is the lib in my laptop. also, python without anaconda works great)

**Comment by chenlize96** [comment]
All these are run on the system terminal of Windows. Thanks.

**Comment by ErrorBot1122** [comment]
> Solved. Find subprocess.py in your lib

Where? I'm using a venv and I cant seem to find it there.
