### ISSUE TITLE
confidence score of each single landmark 

### ISSUE THREAD

**Issue by zeina-abuaisheh** [google/mediapipe#3104]
I am using the holistic model in Python,

Is there a way to get the confidence score of each single landmark of the face/hand/pose landmarks?

Thanks

**Comment by sureshdagooglecom** [comment]
Hi @zeina-abuaisheh , please check this closed [issue](https://github.com/google/mediapipe/issues/644) once.

**Comment by zeina-abuaisheh** [comment]
Thanks, I took a look at the issue you referred to, it's not the same.
First I am using Python. Second, I want the confidence score of each single landmark of a single detection.
For instance, for facemesh, I would like to have the score for each of the 478 landmarks, same for the 21 landmarks of each hand.

Thanks

**Comment by sureshdagooglecom** [comment]
Hi @zeina-abuaisheh ,
We don't support  confidence score in python since we have limited support.

**Comment by xiyichen** [comment]
Is it possible to get confidence score of every single landmarks with C++?

**Comment by Jourtics** [comment]
Hey, @zeina-abuaisheh, @xiyichen  Did you find any confidence score measure?

**Comment by vitorpmh** [comment]
The z-axis could be used as scores depending on your method.
