### ISSUE TITLE
Mediapipe python interface is not working on GPU based on the newest version.

### ISSUE THREAD

**Issue by hujb48** [google/mediapipe#3106]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Linux Ubuntu 20.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc 9.3.0
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.9.4
- Installed using virtualenv? pip? Conda? (if python): virtual env (By pip)
- [MediaPipe version](https://github.com/google/mediapipe/releases): the newest  0.8.9
- Bazel version: the newest 4.2.1

**Describe the problem**:
Hi, SIR, I have just followed the [issue #1651](https://github.com/google/mediapipe/issues/1651) and [issue #2691](https://github.com/google/mediapipe/issues/2691)  to gain a '.whl' file for offline installation. The process of building is successful, then I use 'pip' command to install it offline via guide https://github.com/jiuqiant/mediapipe_python_aarch64, and then I run the 'Holistic'  demo code, then got the same mistake like  issue #2691. By the way, I also Imitated the example #2041 to correct the file "b/mediapipe/modules/pose_landmark/pose_landmark_gpu.pbtxt", the problem would also appeared like #2691, how could I do to solve the problem? What about "Pose" & "Hand" part? Maybe, the latest version of mediapipe is not satisfied with those solutions like #1651 #2041, and #2691?

**[Provide the exact sequence of commands / steps that you executed before running into the problem]**:
just like #1651 , #2691  and #2041
and follow the https://google.github.io/mediapipe/getting_started/python#building-mediapipe-python-package

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by sureshdagooglecom** [comment]
Hi @hujb48 , can you refer media pipe [official document](https://google.github.io/mediapipe/getting_started/gpu_support.html) for GPU issues.

**Comment by rachelgomez161999** [comment]
Try the following with v0.8.3.1:

diff --git a/mediapipe/modules/holistic_landmark/holistic_landmark_gpu.pbtxt b/mediapipe/modules/holistic_landmark/holistic_landmark_gpu.pbtxt
index 990b21d..738204a 100644
--- a/mediapipe/modules/holistic_landmark/holistic_landmark_gpu.pbtxt
+++ b/mediapipe/modules/holistic_landmark/holistic_landmark_gpu.pbtxt
@@ -47,7 +47,7 @@
 
 type: "HolisticLandmarkGpu"
 
-# GPU image. (GpuBuffer)
+# CPU image.
 input_stream: "IMAGE:image"
 
 # Whether to detect/predict the full set of pose landmarks (see below), or only
@@ -73,10 +73,22 @@ output_stream: "FACE_LANDMARKS:face_landmarks"
 output_stream: "POSE_ROI:pose_landmarks_roi"
 output_stream: "POSE_DETECTION:pose_detection"
 
+node: {
+  calculator: "ColorConvertCalculator"
+  input_stream: "RGB_IN:image"
+  output_stream: "RGBA_OUT:image_rgba"
+}
+
+node: {
+  calculator: "ImageFrameToGpuBufferCalculator"
+  input_stream: "image_rgba"
+  output_stream: "image_gpu"
+}
+
 # Predicts pose landmarks.
 node {
   calculator: "PoseLandmarkGpu"
-  input_stream: "IMAGE:image"
+  input_stream: "IMAGE:image_gpu"
   input_side_packet: "UPPER_BODY_ONLY:upper_body_only"
   input_side_packet: "SMOOTH_LANDMARKS:smooth_landmarks"
   output_stream: "LANDMARKS:pose_landmarks"
@@ -87,7 +99,7 @@ node {
 # Predicts left and right hand landmarks based on the initial pose landmarks.
 node {
   calculator: "HandLandmarksLeftAndRightGpu"
-  input_stream: "IMAGE:image"
+  input_stream: "IMAGE:image_gpu"
   input_stream: "POSE_LANDMARKS:pose_landmarks"
   output_stream: "LEFT_HAND_LANDMARKS:left_hand_landmarks"
   output_stream: "RIGHT_HAND_LANDMARKS:right_hand_landmarks"
@@ -108,7 +120,7 @@ node {
 # Predicts face landmarks based on the initial pose landmarks.
 node {
   calculator: "FaceLandmarksFromPoseGpu"
-  input_stream: "IMAGE:image"
+  input_stream: "IMAGE:image_gpu"
   input_stream: "FACE_LANDMARKS_FROM_POSE:face_landmarks_from_pose"
   output_stream: "FACE_LANDMARKS:face_landmarks"
 }
diff --git a/mediapipe/python/BUILD b/mediapipe/python/BUILD
index 3bd188d..49df43b 100644
--- a/mediapipe/python/BUILD
+++ b/mediapipe/python/BUILD
@@ -71,5 +71,8 @@ cc_library(
         "//mediapipe/modules/pose_detection:pose_detection_cpu",
         "//mediapipe/modules/pose_landmark:pose_landmark_by_roi_cpu",
         "//mediapipe/modules/pose_landmark:pose_landmark_cpu",
+        "//mediapipe/modules/holistic_landmark:holistic_landmark_gpu",
+        "//mediapipe/gpu:image_frame_to_gpu_buffer_calculator",
+        "//mediapipe/calculators/image:color_convert_calculator",
     ],
 )
diff --git a/mediapipe/python/solutions/holistic.py b/mediapipe/python/solutions/holistic.py
index 898bb15..90a025d 100644
--- a/mediapipe/python/solutions/holistic.py
+++ b/mediapipe/python/solutions/holistic.py
@@ -44,7 +44,7 @@ from mediapipe.python.solutions.pose import PoseLandmark
 from mediapipe.python.solutions.pose import UPPER_BODY_POSE_CONNECTIONS
 # pylint: enable=unused-import
 
-BINARYPB_FILE_PATH = 'mediapipe/modules/holistic_landmark/holistic_landmark_cpu.binarypb'
+BINARYPB_FILE_PATH = 'mediapipe/modules/holistic_landmark/holistic_landmark_gpu.binarypb'
 
 
 class Holistic(SolutionBase):
@@ -90,14 +90,14 @@ class Holistic(SolutionBase):
             'smooth_landmarks': smooth_landmarks and not static_image_mode,
         },
         calculator_params={
-            'poselandmarkcpu__ConstantSidePacketCalculator.packet': [
+            'poselandmarkgpu__ConstantSidePacketCalculator.packet': [
                 constant_side_packet_calculator_pb2
                 .ConstantSidePacketCalculatorOptions.ConstantSidePacket(
                     bool_value=not static_image_mode)
             ],
-            'poselandmarkcpu__posedetectioncpu__TensorsToDetectionsCalculator.min_score_thresh':
+            'poselandmarkgpu__posedetectiongpu__TensorsToDetectionsCalculator.min_score_thresh':
                 min_detection_confidence,
-            'poselandmarkcpu__poselandmarkbyroicpu__ThresholdingCalculator.threshold':
+            'poselandmarkgpu__poselandmarkbyroigpu__ThresholdingCalculator.threshold':
                 min_tracking_confidence,
         },
         outputs=[
diff --git a/setup.py b/setup.py
index 5acad7b..8ebebe4 100644
--- a/setup.py
+++ b/setup.py
@@ -223,7 +223,8 @@ class BuildBinaryGraphs(build.build):
         'face_detection/face_detection_front_cpu',
         'face_landmark/face_landmark_front_cpu',
         'hand_landmark/hand_landmark_tracking_cpu',
-        'holistic_landmark/holistic_landmark_cpu', 'objectron/objectron_cpu',
+        'holistic_landmark/holistic_landmark_gpu', 
+        'objectron/objectron_cpu',
         'pose_landmark/pose_landmark_cpu'
     ]
     for binary_graph in binary_graphs:
@@ -238,7 +239,8 @@ class BuildBinaryGraphs(build.build):
         'bazel',
         'build',
         '--compilation_mode=opt',
-        '--define=MEDIAPIPE_DISABLE_GPU=1',
+        '--copt=-DMESA_EGL_NO_X11_HEADERS',
+        '--copt=-DEGL_NO_X11',
         '--action_env=PYTHON_BIN_PATH=' + _normalize_path(sys.executable),
         os.path.join('mediapipe/modules/', graph_path),
     ]
@@ -294,7 +296,8 @@ class BuildBazelExtension(build_ext.build_ext):
         'bazel',
         'build',
         '--compilation_mode=opt',
-        '--define=MEDIAPIPE_DISABLE_GPU=1',
+        '--copt=-DMESA_EGL_NO_X11_HEADERS',
+        '--copt=-DEGL_NO_X11',
         '--action_env=PYTHON_BIN_PATH=' + _normalize_path(sys.executable),
         str(ext.bazel_target + '.so'),
     ]

**_Regards,
Rachel Gomez_**

**Comment by hujb48** [comment]
> Hi @hujb48 , can you refer media pipe [official document](https://google.github.io/mediapipe/getting_started/gpu_support.html) for GPU issues.

Thx for the reply, it's very nice of you. Right now, I have followed the  "OpenGL ES Setup on Linux Desktop" from [page](https://google.github.io/mediapipe/getting_started/gpu_support.html) you given. The first of the part has been done successfully, which is "check if your Linux desktop GPU can run MediaPipe with OpenGL ES". Then I used this command for the building process in my virtual env, 
 **' bazel build --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 '**
but anather mistake appears:

2022/02/23 19:49:40 could not resolve the version 'latest' to an actual version number: unable to determine latest version: could not list Bazel versions in GCS bucket: could not list GCS objects at https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: could not fetch https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: Get "https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/": read tcp 10.10.52.142:60808->172.217.160.106:443: read: connection reset by peer

So, my question is how to deal with it? By the way, I am unfamiliar with those building process, however I refer the mediapipe [python guide](https://google.github.io/mediapipe/getting_started/python.html) to build .whl for offline installation, which can successfully used on CPU. But, it is hard to use on GPU for python, the old version of mediapipe can been operated like #2041 an #1651, while those solutions are not adapted to the latest version of mediapipe, or maybe some mistakes have made during the correction in #2691? So could you give some advise on how to run this API on GPU easily and clearly?

**Comment by sureshdagooglecom** [comment]
MediaPipe Python package only contains CPU graphs. If you need to run any GPU graphs, see #1651 (comment).

**Comment by hujb48** [comment]
> MediaPipe Python package only contains CPU graphs. If you need to run any GPU graphs, see #1651 (comment).

Yes sir, but regrettably, it isn't worked on the right now version of Mediapipe which is 0.8.9. By the way, the old version of the Mediapipe is not suitable for my project due to the absence of the 3D world coordinates of the hand.
Thus, how to run any GPU graphs on the latest version?

**Comment by sureshdagooglecom** [comment]
@hujb48 ,
we don't have python GPU graphs , it is only available for CPU.
