### ISSUE TITLE
What device types and iOS versions are supported in Handtrackinggpu sample？

### ISSUE THREAD

**Issue by willbetheone** [google/mediapipe#3107]
Xcode13.2.1 ，iPad Air, iOS 12.5 
Sample Handtrackinggpu is unavailable, and print a message in the "Xcode console".
The message is:
"Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)"

Why the demo can not detect？  And  What device types and iOS versions are supported in Handtrackinggpu sample？

**Comment by sureshdagooglecom** [comment]
Hi @willbetheone,  Did you get a chance to go through this prerequisite for [IOS](https://google.github.io/mediapipe/getting_started/ios.html#prerequisite).

**Comment by AlphaEric** [comment]
Hi @sureshdagooglecom , I have been through it and run successed in iPad (9th generation) with iOS 15.2.1.

**Comment by willbetheone** [comment]
Hi @sureshdagooglecom , I have been through it and run successed in iPad (9th generation) with iOS 15.2.1.

**Comment by sureshdagooglecom** [comment]
@willbetheone, We don't have much environment to test with different devices yet and it's one of the plan for our future road map. At present we can state that all the devices which support the prerequisites while building with  iOS.

**Comment by willbetheone** [comment]
Thank you for your answer. Looking forward to the implementation of this plan that supporting devices and systems can be listed in the future.
