### ISSUE TITLE
How to replace Selfie Segmentation background "C++ Windows 10"

### ISSUE THREAD

**Issue by Alvazz** [google/mediapipe#3108]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): **Windows 10**
- [MediaPipe version](https://github.com/google/mediapipe/releases):  **v0.7**
- Bazel version: **5.0.0**
- Solution (e.g. FaceMesh, Pose, Holistic): **Selfie Segmentation**
- Programming Language and version ( e.g. C++, Python, Java): **C++**

**Describe the expected behavior:**

I ran the Selfie Segmentation example provided by Mediapipe and it worked successfully. The virtual background is displayed in blue by default. I want to replace it with a picture. For example, I pass in a picture, which can be used as a virtual background, but I don't know how to do it, and I don't have any documentation guidance. I have no clue. I hope I can get help .

**Standalone code you may have used to try to get what you need :**  ??

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook: No

**Other info / Complete Logs :** No
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached: No

**Comment by sureshdagooglecom** [comment]
Hi @Alvazz , can you provide code changes to reproduce this issue.

**Comment by Alvazz** [comment]
replace Selfie Segmentation background's blue color as image.

I ran the Selfie Segmentation example and it worked successfully, the background color is blue, I want to set the background to an image, my development runtime is windows 10. Is there any way to achieve this?

![image](https://user-images.githubusercontent.com/50744096/155984377-909eb38a-98e3-4df3-8d9a-14184b6f7bb4.jpg)
