### ISSUE TITLE
MultiHandtrackingGPU not working on MacOs

### ISSUE THREAD

**Issue by AbrarFastian** [google/mediapipe#311]
Please tell me how to run multiplehandtrackinggpu on macos

Most common Error: fatal error: 'EGL/egl.h' file not found

Other error: GPUprogram not found

**Comment by mcclanahoochie** [comment]
Currently MediaPipe only supports GPU processing in Linux,Android,iOS. 
Official MacOS GPU support may come sometime in the future (on the roadmap, but not soon).
