### ISSUE TITLE
Hand tracking world coordinates

### ISSUE THREAD

**Issue by gianluca-amprimo** [google/mediapipe#3112]
For a paper I am writing, I need to know how the 3d world coordinates are estimated, but I cannot find a clear explanation on the method employed by mediapipe. Is there any reference I can check?

**Comment by sureshdagooglecom** [comment]
Hi @gianluca-amprimo , did you get a chance to check [this](https://github.com/google/mediapipe/issues/742) issue.

**Comment by kuaashish** [comment]
Hello @gianluca-amprimo,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
