### ISSUE TITLE
Help in obtaining 68 landmarks

### ISSUE THREAD

**Issue by gd1925** [google/mediapipe#3116]
Hi all,

Could someone tell me how to map the 468 landmarks to 68 landmarks? I saw this issue [https://github.com/google/mediapipe/issues/421](url)
 which addresses the same question, but I was wondering if someone has managed to do it and could provide some help in the mapping. Thank you in advance.

**Comment by sureshdagooglecom** [comment]
Hi @gd1925 , could you please share some more information to investigate further on this issue and am not able to find this [issue](https://github.com/google/mediapipe/issues/url) in github.

**Comment by gd1925** [comment]
Hi Sir, I have been thinking about it and trying manual mapping. Comparing the locations manually. Could you suggest me some other way if possible?

**Comment by kuaashish** [comment]
Hello @gd1925,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
