### ISSUE TITLE
How do I use the Python version of the GPU

### ISSUE THREAD

**Issue by jintaocui-lingoace** [google/mediapipe#3117]
I installed Mediapipe using pip install mediapipe,But it's running on CPU, which is slow and I want to use GPU acceleration. Please help me.

**Comment by sureshdagooglecom** [comment]
Hi @jintaocui-lingoace ,MediaPipe  python solutions supports only for  CPU graphs ,You can follow https://github.com/google/mediapipe/issues/1651#issuecomment-790176010 to run the GPU graphs. Sorry for the inconvenience.

**Comment by jintaocui-lingoace** [comment]
> 嗨@jintaocui-lingoace，MediaPipe python解决方案仅支持CPU图形，您可以按照[#1651（评论）](https://github.com/google/mediapipe/issues/1651#issuecomment-790176010)运行GPU图形。很抱歉给您带来不便。

Thank you for your answer. Can I use gpu acceleration if I use c++?

**Comment by sureshdagooglecom** [comment]
Please check MediaPipe official  [document](https://google.github.io/mediapipe/getting_started/cpp.html#:~:text=being%20not%20accessible.-,Option%202%3A%20Running%20on%20GPU,-Note%3A%20This%20currently) to use GPU in C++.

**Comment by jintaocui-lingoace** [comment]
> 

I read the document use GLOG_logtostderr = 1 bazel - bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu \
--calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt Command but bazel - bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu without this folder then I use GLOG_logtostderr = 1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu   -- Calculator_graph_config_file =mediapipe/ Graphs /hand_tracking/hand_tracking_desktop_live.pbtxt But command not found as well No such file or directory

**Comment by sureshdagooglecom** [comment]
Hi @jintaocui-lingoace , can you please explain the steps to reproduce this issue.
