### ISSUE TITLE
Build Mediapipe hand issue 

### ISSUE THREAD

**Issue by sambath-krian** [google/mediapipe#3118]
following error i am getting if i build the media pipe hand modules using "bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Program Files\Python37\python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu"

Warning: skipping import of repository 'pybind11' because it already exists.
WARNING: C:/users/sambath.subbarayalu_/git_rep/mediapipe_test/mediapipe/mediapipe/framework/tool/BUILD:182:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: C:/users/sambath.subbarayalu_/git_rep/mediapipe_test/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (1 packages loaded, 405 targets configured).
INFO: Found 1 target...
INFO: From Compiling mediapipe/framework/tool/text_to_binary_graph.cc [for host]:
C:\users\sambath.subbarayalu__bazel_sambath.subbarayalu_\3n7uzcn5\execroot\mediapipe\bazel-out\host\bin\external\com_github_glog_glog_virtual_includes\windows_glog_headers\glog\logging.h(1660) : warning C4722: 'google::NullStreamFatal::~NullStreamFatal': destructor never returns, potential memory leak
ERROR: C:/users/sambath.subbarayalu_/git_rep/mediapipe_test/mediapipe/mediapipe/calculators/video/BUILD:198:11: C++ compilation of rule '//mediapipe/calculators/video:opencv_video_decoder_calculator' failed (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 46 argument(s) skipped)
.\mediapipe/framework/port/opencv_video_inc.h(88): fatal error C1083: Cannot open include file: 'opencv2/optflow.hpp': No such file or directory
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.915s, Critical Path: 4.35s
INFO: 191 processes: 171 internal, 20 local.
FAILED: Build did NOT complete successfully

**Comment by sureshdagooglecom** [comment]
Hi @sambath-krian ,Please follow this steps mentioned in this https://github.com/google/mediapipe/issues/724.
