### ISSUE TITLE
Impossible to use LandmarkGrid

### ISSUE THREAD

**Issue by daniele-gusmini** [google/mediapipe#3119]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Chrome (javascript)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
- Programming Language and version ( e.g. C++, Python, Java): Javascript
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ):
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
- Xcode & Tulsi version (if issue is related to building for iOS):

**Describe the current behavior:**

**Describe the expected behavior:**

I would like to move LandmarkGrid to a React app, I successfully moved all the other part of the code but LandmarkGrid is not working. I tried 2 ways:

1. `import * as LandmarkGrid from "https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d@0.2/control_utils_3d.js";`
In this case I receive as error:

Uncaught (in promise) ReferenceError: javascript is not defined

2. `import * as LandmarkGrid from "@mediapipe/control_utils_3d";`
In this case I received as error:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Vector3')
    at landmark_grid.ts:631:1
    at Object.__webpack_modules__../node_modules/@mediapipe/control_utils_3d/control_utils_3d.js.goog.loadModule (landmark_grid.ts:631:1)
    at Object../node_modules/@mediapipe/control_utils_3d/control_utils_3d.js (landmark_grid.ts:631:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at App.js:13:1
    at Function.__webpack_require__.a (async module:63:1)
    at Module../src/components/functional/PoseLogger.js (App.js:13:1)
    at Module.options.factory (react refresh:6:1)

I read that other have similar problem but not found any working solution, can you help me?

**Comment by sureshdagooglecom** [comment]
Hi @daniele-gusmini , could you please add [this](https://google.github.io/mediapipe/getting_started/javascript.html#:~:text=%3Chead%3E%0A%3Cscript%20src%3D%22https%3A//cdn.jsdelivr.net/npm/%40mediapipe/drawing_utils%400.1/drawing_utils.js%22%20crossorigin%3D%22anonymous%22%3E%3C/script%3E%0A%3Cscript%20src%3D%22https%3A//cdn.jsdelivr.net/npm/%40mediapipe/holistic%400.1/holistic.js%22%20crossorigin%3D%22anonymous%22%3E%3C/script%3E%0A%3C/head%3E)  scripts directly to your HTML.

**Comment by daniele-gusmini** [comment]
Sorry for the delay, I'm using React framework so I need to use the nom package

**Comment by Paolo-Sotorro** [comment]
I'm also trying to use it with React and getting similar errors but in different files:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/99659485/161340756-86c418d1-bfdb-45e9-bd43-51c5c574fb7d.png">

**Comment by ayoub-root** [comment]
same issue
