### ISSUE TITLE
How can I have the  all codes of this project pose tracking  c++ mediapipe  in Visual Studio c++ 2019 ? 

### ISSUE THREAD

**Issue by problemSolvingProgramming** [google/mediapipe#3120]
How can I have the  all codes of this project pose tracking  c++ mediapipe  in Visual Studio c++ 2019 ?

**Comment by sureshdagooglecom** [comment]
Hi @problemSolvingProgramming ,We have already an issue with similar context which is in progress. Please have a look at it https://github.com/google/mediapipe/issues/1162
