### ISSUE TITLE
Does mediapipe work with python 3.9?

### ISSUE THREAD

**Issue by goulaoalex** [google/mediapipe#3121]
Hello, I've been trying to set up mediapipe on my raspberry pi 3 for the last couple of days and I've had a lot of trouble. Doing my research to find a solution I've noticed that no user is using python 3.9 with mediapipe. So my question is, does mediapipe work with python 3.9?

**Comment by sureshdagooglecom** [comment]
Hi @goulaoalex , Thanks for raising the issue. 
MediaPipe supports upto 3.10 v, please refer [this](https://github.com/jiuqiant/mediapipe_python_aarch64) to build python in raspberry pi .

**Comment by vduyhai** [comment]
> Hi @goulaoalex , Thanks for raising the issue. MediaPipe supports upto 3.10 v, please refer [this](https://github.com/jiuqiant/mediapipe_python_aarch64) to build python in raspberry pi .

Hi, I'm using PyQt5 and mediapipe on raspberry pi 4 (4GB RAM - Debian Bullseye). The PyQt5 is installed succesfully using python 3.9 and incompatible with any lower python versions, so I have to try install mediapipe with python 3.9. I've tried the link above but it doesn't work with python 3.9. Do you have any update for mediapipe installation with python 3.9?
