### ISSUE TITLE
Mediapipe holistic javascript slows down setInterval()

### ISSUE THREAD

**Issue by galharth** [google/mediapipe#3123]
Hello,

I have a javascript interval that prints its progress every 10 miliseconds.
Before I load mediapipe holistic on the web the timing works good, every 10 milliseconds the code prints out the interval progress, after I load mediapipe I receive this warnings:
```
holistic_solution_simd_wasm_bin.js:9 I0227 12:06:45.086000       1 gl_context_webgl.cc:151] Successfully created a WebGL context with major version 3 and handle 3
holistic_solution_simd_wasm_bin.js:9 I0227 12:06:45.089000       1 gl_context.cc:351] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)))
holistic_solution_simd_wasm_bin.js:9 W0227 12:06:45.089000       1 gl_context.cc:821] OpenGL error checking is disabled

```

And afterward, the interval progress timing slows down, you can see clearly what happens in the following video (the interval progress slows down and it no longer prints its progress every 10 milliseconds).

https://user-images.githubusercontent.com/564274/155877992-72a80279-a5fa-47dd-8f68-d045a3450d9a.mp4

I reproduced the problem in this codepen https://codepen.io/galharth/pen/KKyGqLO?editors=1111

I added this code to the js file that loads medipipe holistic:

```
var seconds = 0;
var interval = setInterval(function() {
  seconds += 0.01
  console.log(seconds)
}, 10);

```
You can see in the codepen javascript console that after mediapipe is loaded the console.log that is inside the setInterval function prints the interval progress slower than expected.

Thank you🙏

**Comment by sureshdagooglecom** [comment]
Hi @galharth , please provide steps to reproduce this issue.

**Comment by galharth** [comment]
Hi @sureshdagooglecom 

I reproduced the problem in this codepen https://codepen.io/galharth/pen/KKyGqLO?editors=1111

I added this code to the js file that loads medipipe holistic:

```
var seconds = 0;
var interval = setInterval(function() {
  seconds += 0.01
  console.log(seconds)
}, 10);

```
You can see in the codepen javascript console that after mediapipe is loaded the console.log that is inside the setInterval function prints the interval progress slower than expected.


Thanks,
Gal

**Comment by kuaashish** [comment]
Hello @galharth,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
