### ISSUE TITLE
Can i use MediaPipe with javafx ?

### ISSUE THREAD

**Issue by TAHRI-Khalid** [google/mediapipe#3124]
I want use MediaPipe with my projet JavaFx , but i don't found any dependency for java , wich can i use  can someone provide details how to I can achieve that?
Thank you!

**Comment by sureshdagooglecom** [comment]
Hi @TAHRI-Khalid ,Currently  MediaPipe is not  supporting  for java  but  you can try android [solutions](https://google.github.io/mediapipe/getting_started/android.html) .Sorry for the inconvenience.

**Comment by TAHRI-Khalid** [comment]
Thank you @sureshdagooglecom  , MediaPipe is a greate work ,I hope you planning a support for JAVA

**Comment by sureshdagooglecom** [comment]
@TAHRI-Khalid ,we will raise this as a feature request with internal team.
