### ISSUE TITLE
AppleVision Performance

### ISSUE THREAD

**Issue by zetyquickly** [google/mediapipe#3127]
Hello,

I was reading the documentation and came across this [comparison](https://google.github.io/mediapipe/solutions/pose.html#pose-estimation-quality). Here is said that AppleVision model has some performance and there's a link to the Apple's documentation.

The question is, how could one know that AppleVision model still performs in the same way as it was at the moment of documenting? I'm asking because from the comparison it is clear that BlazePose based solution was better, but does it still?

**Comment by sureshdagooglecom** [comment]
Hi @zetyquickly , Could you please elaborate your use case to investigate further on this issue.

**Comment by zetyquickly** [comment]
Hello,

So, in the table [here](https://google.github.io/mediapipe/solutions/pose.html#pose-estimation-quality) we see that AppleVision performs at 32.8 mAP on Yoga dataset, while BlazePose Light performs 45.0 mAP (am I right that this model is used in MediaPipe Pose Estimation Solution?). 

On the other hand, we have Apple's [documentation](https://developer.apple.com/documentation/vision/detecting_human_body_poses_in_images) that introduces their solution. This solution might have been updated since the time since the above mentioned table was filled. 

And I am trying to understand is this table still a good source to decide which model has better performance on iOS device, the one from MediaPipe (as table shows) or the one from AppleVision (which might be updated)?

**Comment by sureshdagooglecom** [comment]
@zetyquickly , below [table](https://google.github.io/mediapipe/solutions/pose.html#:~:text=To%20evaluate%20the,from%20COCO%20topology.) is a good resource from MediaPipe to understand the performances of iOS devices.

**Comment by zetyquickly** [comment]
OK, thank you
