### ISSUE TITLE
Any tables showing the model parameters and amount of computation （FLOPs) for  models?

### ISSUE THREAD

**Issue by Stephenfang51** [google/mediapipe#3128]
I was so curious about the Palm detector and hand landmark detector model
The paper only indicated that params of hand landmark detector for light, full, heavy, how about amount of computation(Flops)?

and params and Flops for palm detector.
Is there easy way or API we can count ourself? 

Thanks your great works !

**Comment by sureshdagooglecom** [comment]
Hi @Stephenfang51 ,
can you please check [this](https://google.github.io/mediapipe/framework_concepts/realtime_streams.html) document to  understand how Real-time Streams works in calculating the computation time.
