### ISSUE TITLE
windows.h': No such file or directory

### ISSUE THREAD

**Issue by sambath-krian** [google/mediapipe#3129]
System information

OS: Windows 10
Bazel version 3.7.2
Python version 3.7
VS Community 2019 14.29.30133

System information

OS: Windows 10
Bazel version 3.7.2
Python version 3.7
VS Community 2019 14.29.30133

Environmental Variable setting :
**BAZEL_VC** C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC

**BAZEL_VC_FULL_VERSION** 14.29.30133

**BAZEL_VS** C:\Program Files (x86)\Microsoft Visual Studio\2019\Community

**BAZEL_WINSDK_FULL_VERSION**  10.0.22000.00

Description

Hello!

I tried to build the C++ examples on Windows. The hello_world example works, but the hand tracking example gave this error:  

  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/flatbuffers /Ibazel-out/host/bin/external/flatbuffers /Ibazel-out/host/bin/external/flatbuffers/src/_virtual_includes/flatbuffers /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw /D_USE_MATH_DEFINES /std:c++17 /Fobazel-out/host/bin/external/flatbuffers/src/_objs/flatbuffers/util.obj /c external/flatbuffers/src/util.cpp
Execution platform: @local_execution_config_platform//:platform
external/flatbuffers/src/util.cpp(30): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build

**Comment by sambath-krian** [comment]
build : bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Program Files\Python37\python.exe" mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu --verbose_failures

**Comment by sambath-krian** [comment]
Build completed successfully, 3055 total actions-after rerplacing winsdk10.0.19041.685/000

**Comment by laughing33** [comment]
I canceled the BAZEL_WINSDK_FULL_VERSION, which means not to tell bazel the version of sdk, let it try to find the default one.
