### ISSUE TITLE
MediaPipe KNIFT knift_labelmap.txt

### ISSUE THREAD

**Issue by hbyjw** [google/mediapipe#3133]
How to get the correct tab order？

In the `knift_labelmap.txt`  I thought it was 
```
1-XLP
2-AJS
3-LHQWJN
4-ZZM
```
but it turned out to be

```
4-ZZM
3-LHQWJN
1-XLP
2-AJS
```

**Comment by hbyjw** [comment]
I used my own image to build `template_matching.aar` `knift_index.pb` `mobile_cpu.binarypb` but I don't know how to fill in `knift_labelmap.txt` correctly, when I run it in android studio, I don't know how to make it correct Modified `knift_labelmap.txt`.


![git 问题描述](https://user-images.githubusercontent.com/13883357/156324154-15797742-28fe-4f98-9e50-9c2e1bd3f791.jpg)

**Comment by PrinceP** [comment]
@hbyjw In the template creation directory what is the sequence of image files? 

`
bazel-bin/mediapipe/examples/desktop/template_matching/template_matching_tflite \
--calculator_graph_config_file=mediapipe/graphs/template_matching/index_building.pbtxt \
--input_side_packets="file_directory=<template image directory>,file_suffix=png,output_index_filename=<output index filename>"
`

That particular sequence should be taken in knift_label.txt file.

**Comment by hbyjw** [comment]
@PrinceP  

 template creation directory 

![文件顺序](https://user-images.githubusercontent.com/13883357/156958693-bf5667d2-0e14-49d4-8139-948e0e8f7b91.jpg)

knift_label.txt


![文件顺序2](https://user-images.githubusercontent.com/13883357/156958810-6682ecde-febf-43d0-80d7-452df8e7bff9.jpg)

1. If I put it in android studio according to the settings in `knift_label.txt`, the order displayed in the phone is wrong

2. I would like to know if the `knife_label.txt `is created automatically, or if I create it myself. If it was me, where should I put the knift_label.txt when I create the `knife_index.pb`

**Comment by hbyjw** [comment]
@PrinceP 

https://github.com/google/mediapipe/issues/3133#issuecomment-1060133736


The correct name of the item in the picture is `3-LianHuaQingWenJIaoNang`


![Screenshot_20220307-110031_testMediapipe](https://user-images.githubusercontent.com/13883357/156960656-047d7c62-827d-4984-8238-81c06c6fca86.jpg)

**Comment by PrinceP** [comment]
@hbyjw 

1. The knift_label file has to be given by the user only. 

> Step 3: Replace [mediapipe/models/knift_index.pb](https://github.com/google/mediapipe/tree/master/mediapipe/models/knift_index.pb) with the index file you generated, and update [mediapipe/models/knift_labelmap.txt](https://github.com/google/mediapipe/tree/master/mediapipe/models/knift_labelmap.txt) with your own template names.


2. The index is made here. Can you put some debug statements in calculator and check the sequence of indexes taken. https://github.com/google/mediapipe/blob/b899d17f185f6bcbf3f5947d3e134f8ce1e69407/mediapipe/calculators/video/box_detector_calculator.cc#L51

**Comment by hbyjw** [comment]
@PrinceP 


I don't know much about C++, but I'll give it a try

**Comment by yegenzhi** [comment]
Is image #3 the only wrong detection? if you shoot the image #1 xianglianpian, i wonder what is detection result from the demo?

**Comment by hbyjw** [comment]
@yege




![顺序](https://user-images.githubusercontent.com/13883357/156970888-9028a3eb-aae2-4620-8f76-4febef163c7e.jpg)

**Comment by hbyjw** [comment]
@yegenzhi 



![顺序](https://user-images.githubusercontent.com/13883357/156970888-9028a3eb-aae2-4620-8f76-4febef163c7e.jpg)

**Comment by yegenzhi** [comment]
that's indeed an interesting bug.
when you run index_building.pbtxt, can you look out for the logs from this file?
https://github.com/google/mediapipe/blob/e6c19885c6d3c6f410c730952aeed2852790d306/mediapipe/calculators/util/local_file_pattern_contents_calculator.cc#L60
you can just copy paste the logs here.

**Comment by hbyjw** [comment]
Where can I see the log, I don't see it in the terminal.

![temp2](https://user-images.githubusercontent.com/13883357/156975683-eba9eb89-caae-47c7-9099-d60e65797a4e.jpg)

**Comment by yegenzhi** [comment]
ok.
i believe if you add the following line to LN54 of this file, this may fix your issue.

 std::sort(filenames_.begin(), filenames_.end());

can you please try?

**Comment by hbyjw** [comment]
https://github.com/google/mediapipe/issues/3133#issuecomment-1060212351

I wrote the record to txt

![temp5](https://user-images.githubusercontent.com/13883357/156976229-8d654a6d-2ab2-415c-bd0f-5b5015febc10.jpg)

**Comment by yegenzhi** [comment]
you can add " --alsologtostderr" to your command to make the logs show in terminal.

yes. the bug is because the match file api at LN50 does not guarantee the matched result in exact order.
we will fix this in the next release.

Thanks for the catch.

**Comment by hbyjw** [comment]
Okay thank you.

I will add the code and try again.

**Comment by hbyjw** [comment]
https://github.com/google/mediapipe/issues/3133#issuecomment-1060220075


After adding the code, the correct order is displayed.
