### ISSUE TITLE
GPU or CPU?

### ISSUE THREAD

**Issue by lghasemzadeh** [google/mediapipe#3134]
Hello,

1) Running mediapipe in python, for example the Facemesh, Holistic, Iris and Object Detection solutions will be more efficient, in terms of both speed and performance on GPU or CPU (in fair conditions)?
2) Is there any comparison chart, link or discussion? (except than #2719 and #2497)
3) If one of CPU or GPU is more efficient, would you explain why?

Thank you

**Comment by sureshdagooglecom** [comment]
Hi @lghasemzadeh ,
please refer media pipe official [document](https://google.github.io/mediapipe/framework_concepts/gpu.html#:~:text=MediaPipe%20supports%20calculator,features%20when%20needed) for GPU and CPU detailed comparison.

**Comment by lghasemzadeh** [comment]
@sureshdagooglecom Thank you for the reply. 
But the link doesn't cover my question.
I need to know using which of CPU or GPU is more efficient for MediaPipe in terms of FPS and performance? at the first glance it is reasonable that GPU might be better but I checked lots of issues in this repository that shows CPU is more efficient. But is there any official reference or comparison which Mediaipe developers can provide? I am really confused!

**Comment by tom-doerr** [comment]
Also a comparison between the OpenGL and Tensorflow versions would be really helpful.
I'm getting 30 FPS for the Handpose estimation with CPU as well as with the OpenGL version.
```
            .-/+oossssoo+/-.               tom@desktop-20-3 
        `:+ssssssssssssssssss+:`           ---------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.3 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: MS-7B00 1.0 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.11.0-44-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 51 days, 14 hours, 9 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3548 (dpkg), 28 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1440x2560, 2560x1440, 1080x1920 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: i3 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Theme: Adwaita [GTK3] 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Icons: Adwaita [GTK3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Terminal: kitty 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal Font: Ubuntu Mono 9.0 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA GeForce GTX 1080 Ti 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GTX 1060 6GB 
      -+sssssssssssssssssyyyssss+-         Memory: 18577MiB / 64254MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                   
```

**Comment by tom-doerr** [comment]
@lghasemzadeh You can find a benchmark here: https://blog.tensorflow.org/2021/11/3D-handpose.html
The site also includes a link to a live demo where you can choose between executing on CPU or GPU.

**Comment by lghasemzadeh** [comment]
> @lghasemzadeh You can find a benchmark here: https://blog.tensorflow.org/2021/11/3D-handpose.html The site also includes a link to a live demo where you can choose between executing on CPU or GPU.

Thank you @tom-doerr.
@sureshdagooglecom there should be a document comparing or at least giving an answer to this fundamental question. I am sure that it came to mediapipe's developers' mind to compare the FPS for both GPU and CPU.

**Comment by mcclanahoochie** [comment]
On average, the GPU should offer better performance, but as usual, it depends. 
Which CPU and GPU are paired? How fast is the system memory? What resolution is the camera/video? 
Is this on desktop or mobile or web? 
On mobile, GPU is almost always faster (for recent devices). On desktop there is more variance (ARM or x86? integrated GPU or dedicated?). 
If you are referring to the provided examples, It doesn't hurt to try both versions and see which one works best on your system/device.

**Comment by kuaashish** [comment]
Hi @lghasemzadeh,
Could you please go through the [above](https://github.com/google/mediapipe/issues/3134#issuecomment-1087986854) comment. Thank you!

**Comment by matanox** [comment]
@kuaashish are there any benchmarks that you may have at hand for inference time on some GPU models?
