### ISSUE TITLE
How to detect Emotions using Face Mesh Landmarks Mediapipe

### ISSUE THREAD

**Issue by msreevani060** [google/mediapipe#3135]
Hi, 

I have replicated the following document in my system : 

https://www.analyticsvidhya.com/blog/2021/07/facial-landmark-detection-simplified-with-opencv/

With this could only get Facial Landmarks, not sure how to proceed with landmarks to get Euclidean distance for all 468 landmarks for emotion detection. 

Can anyone please help me with guidance.

**Comment by sureshdagooglecom** [comment]
Hi @msreevani060 ,
you can calculate the euclidean distance landmarks using this method where you can pass the landmark points in arguments.
def euclaideanDistance(point, point1):
    x, y = point
    x1, y1 = point1
    distance = math.sqrt((x1 - x)**2 + (y1 - y)**2)
    return distance

**Comment by sureshdagooglecom** [comment]
Hi @msreevani060 , kindly provide your code changes to investigate further on this.

**Comment by Oliver2552** [comment]
Hi, 

Once you create a distance/graph matrix using your 468 landmarks, you should have a 468x468 matrix. You can then use that as input into a CNN, specifying an input shape of (468, 468, 1) (only 1 channel). Alternatively, you can also explore the use of a graph neural networks (GNN) or graph convolutional neural networks (GCNN).

That being said, while MediaPipe may offer 468 facial landmarks, using all of them may not be the best approach, computationally speaking - its expensive to compute. Consider narrowing down the number of landmarks you chose and see which of the 468 most effectively attribute to emotions (e.g. eyes, nose, mouth, eyebrows etc..).
