### ISSUE TITLE
How can I get fixed landmarks?

### ISSUE THREAD

**Issue by helpyouifican** [google/mediapipe#3136]
I used python for real-time 478(included iris) face mesh and iris tracking APK for android11.
However, I found that Real-time landmarks constantly trembled regardless of my head movement.
I need exact calculation for distance of each landmark. Is any ideas for this problem?

**Comment by sureshdagooglecom** [comment]
Hi @helpyouifican ,
did you get a chance to check this issue https://github.com/google/mediapipe/issues/1891
