### ISSUE TITLE
Iris Detection problem

### ISSUE THREAD

**Issue by Roopesh-Bharatwaj-K-R** [google/mediapipe#3139]
Iris Detection issue on some Images:
detection appears out of iris area . Code is written in C++ and wrapper for Python.

Ubuntu Os: Ubuntu 20.04.3 LTS.
![test_Blue](https://user-images.githubusercontent.com/77121467/156557159-14927b94-febd-4c16-8a6a-bd8046a1b2a9.jpg)

**Comment by sureshdagooglecom** [comment]
Hi @Roopesh-Bharatwaj-K-R ,
could you please elaborate the issue to investigate further.
