### ISSUE TITLE
Using third party libraries with Mediapipe

### ISSUE THREAD

**Issue by JECBello** [google/mediapipe#314]
Hello, I apologize if this question is more related to Bazel than Mediapipe, but is there a proper way to include third party libraries with Mediapipe? I have the third party library stored as a folder within the same folder that I run the build command and was wondering if there was a simpler way to include this library rather than creating a BUILD file for each subfolder within the library. This library further depends on other libraries which contain many files and creating multiple BUILD files for these dependencies seems inefficient.    

I should mention that I was able to build static library files(.a) for the third party library. I was considering an approach similar to how OpenCV is included (including a build file within the third_party folder that references the shared library files and references the header files), but I am unsure if this will work. 

Thank you!

**Comment by jiuqiant** [comment]
If you already have the static libraries, you can follow the OpenCV solution that we have in the workspace file. In theory, it should work. However, to use your libraries in MediaPipe with Bazel, you still need to write a BUILD file for your libraries. Hope this helps.

**Comment by nyanmn** [comment]
@jiuqiant 
Mediapipe is very useful.

How can I add in third party library like https://github.com/felHR85/UsbSerial to mediapipe?
For normal Android Studio project, I just need to add in

allprojects {
	repositories {
		jcenter()
		maven { url "https://jitpack.io" }
	}
}
to build.gradle.
And add the dependency to module's build.gradle:

implementation 'com.github.felHR85:UsbSerial:6.1.0'

But for mediapipe, how can I add in to interface usbserial?
