### ISSUE TITLE
how can i remove the segmentation mask in ios framework for pose tracking

### ISSUE THREAD

**Issue by chanhoucheng** [google/mediapipe#3140]
hi does anyone has any idea how to remove the segmentation mask from the output image after pose tracking, basically i want my original with only the pose landmarks. Currently  i am ending up with an image with blue blackground due to segmentation mask. I have figured out how to change the segmentation mask color by changing the rgb values in pose_renderer_gpu.pbtxt

Any help is appreciated!

**Comment by PrinceP** [comment]
Can you change the enable_segmentation to false.
[enable_segmentation](https://google.github.io/mediapipe/solutions/pose#enable_segmentation)

**Comment by sureshdagooglecom** [comment]
Hi @chanhoucheng ,
can you change as per [this](https://google.github.io/mediapipe/solutions/pose#:~:text=Default%20to%20true.-,ENABLE_SEGMENTATION,the%20solution%20also%20generates%20the%20segmentation%20mask.%20Default%20to%20false.,-SMOOTH_SEGMENTATION).

**Comment by chanhoucheng** [comment]
i was able to set that when i was doing my python prototype project in my py function call, but i cant seem to find this in the ios example, may i know where is it located? the only place i found the variable enable_segmentation was in .pbtxt files and there dont seem to be any place i can set that value

**Comment by chanhoucheng** [comment]
hi all, thanks for the tips, i finally figured out how to do it, i forgot that the pbtxt can be set to false for enable_segmentation
