### ISSUE TITLE
Drawing and writing implementation in  hands solution

### ISSUE THREAD

**Issue by omarzain27** [google/mediapipe#3142]
<em>Air writing and drawing in Mediapipe hand tracking solution.</em>

**System information** (will use hand tracking landmark to write or draw in live webcam )

- MediaPipe Solution (you are using): using Mediapipe and cv2
- Programming language: Python
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state:**

This feature allow users  to use mediapipe hand tracking in useful things like teaching writing and drawing this will make hand tracking more useful and easy to use.

**Will this change the current API? How?**

This will be a new feature added into the mediapipe python library and no changes in the API will occur

**Who will benefit with this feature?**

The end-user of mediapipe will surely benefit from this since computer vision and machine learning is mostly carried out using python so such a feature will also help in the organization's growth. and can use in many things like :
 - Webinar or Meet Integration
 - Online Classes
 - Apps using AR

**Future Works**
NPM package may be ?
And improved Gesture or Option to Choose Gesture

**Comment by kuaashish** [comment]
Hello @omarzain27,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
