### ISSUE TITLE
no documentation on how `.pbtxt` files are generated for face effects

### ISSUE THREAD

**Issue by jedi2610** [google/mediapipe#3144]
there is almost (or basically) no documentation on how the `.pbtxt` files are generated for the face effects `glass` and `axis`. this is my first time using mediapipe and i'm trying to implement few basic snapchat like filters (i know there are better ways like AR, etc).

using opencv to accomplish this seems to work but using a `.pbtxt` file with all the mesh coordinates (or whatever they are called) pre-mapped seems to be more efficient both computationally and from an implementation perspective. i googled it but the results were all related to the normal `.pbtxt` files for tensorflow models. so it would be nice to know how those files are generated. thank you.

**Comment by sureshdagooglecom** [comment]
Hi @jedi2610 ,did you get a chance to check this issue https://github.com/google/mediapipe/issues/1155?

**Comment by jedi2610** [comment]
yeah i did (only later though). it didn't show up when i googled "generate `.pbtxt` files for images" so sorry about that. there is one thing though, i downloaded a few `.obj` files from [cgtrader](https://www.cgtrader.com/) and used the unofficial python script mentioned in the issue above but it doesn't work on the `.obj` file i have. i googled that too and found that there are a few ways to represent the data in a `.obj` file. but ig i'll have to deal with that on my own. ty i'll close this issue.
