### ISSUE TITLE
Interactive Color change in hairsegmentationgpu 

### ISSUE THREAD

**Issue by PrinceP** [google/mediapipe#3148]
Pull request - https://github.com/google/mediapipe/pull/3145

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): hairsegmentationgpu
- Programming language : C++/Android Java
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state:**

The node options provide a static color to Recolor calculator.  

**Will this change the current api? How?**

An additional RGB_OUT label is added in input stream.

**Who will benefit with this feature?**

For any recolor calculator usage, the user can provide its own set of RGB values to recolor

**Please specify the use cases for this feature:**

- AR apps - Live changes to face or other aspects of color
- #18
- Can be used in providing a base tutorial for other dynamic changes to calculators

**Any Other info:**
The implementation is done only on hairsegmentationgpu. Need to work on CPU approach.

 #334

**Comment by sureshdagooglecom** [comment]
Hi @PrinceP , You can try doing it using this issues https://github.com/google/mediapipe/issues/420, https://github.com/google/mediapipe/issues/18
