### ISSUE TITLE
Mediapipe effect renderer(face effect) module using python or C/C++

### ISSUE THREAD

**Issue by locoChan** [google/mediapipe#3149]
Hello, 

I am working on a project that uses a mediapipe to give a face effect.

Is there any way I can use mediapipe's effect renderer module (calculator, https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/effect_renderer_calculator.cc) in python or C/C++?

If possible, we want information about the pipeline that uses the effect renderer module.

Thank you

**Comment by sureshdagooglecom** [comment]
Hi @locoChan ,did you a get chance to check this [issue](https://github.com/google/mediapipe/issues/1155).

**Comment by locoChan** [comment]
Sorry for the late reply.

https://github.com/google/mediapipe/issues/1155#issuecomment-995079150

I have already seen this content, and I thought that maybe the Python API is not provided.
Is that right?

I want to study an example of the effect renderer module operated on the desktop.

Again, sorry for the late reply.

**Comment by Xelawk** [comment]
Why can't just provide an example of C++, as your open source project is specifically designed to create pitfalls for people?
