### ISSUE TITLE
Why the contributors and commits are masked for this repo? These statistics are important for the community to assess the stability of the project.

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#315]
Is this project going to be well maintained like TensorFlow?

**Comment by yxchng** [comment]
Is this project going to be well maintained like TensorFlow?

**Comment by jiuqiant** [comment]
We haven't taken any pull requests and all the commits are made by the MediaPipe team with a tool called Copybara (https://github.com/google/copybara).
