### ISSUE TITLE
MacOS: Segmentation Fault on building MediaPipe's example C++ app

### ISSUE THREAD

**Issue by neufii** [google/mediapipe#3150]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): **Installed on MacOS Monterey 12.3 Beta**
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): **Apple clang version 13.0.0 (clang-1300.0.29.30)**
- [MediaPipe version](https://github.com/google/mediapipe/releases): **0.8.9**
- Bazel version: **4.2.1**
- XCode and Tulsi versions (if iOS): **Command Line Tool 13.2.0.0.1.1638488800** installed via command line not App Store
- OpenCV version (if running on desktop): **4.5.3**

**Describe the problem**:
I've installed mediapipe and successfully run helloWorld. However, when I try building C++ command-line example apps running on CPU (https://google.github.io/mediapipe/getting_started/cpp.html), I always get the following error.
I've tried re-install everything and also tried install xcode from the app store but still get the error.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu`

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

```
DEBUG: /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
WARNING: /Users/neufii/Documents/Work/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /Users/neufii/Documents/Work/mediapipe/mediapipe/framework/tool/BUILD:182:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/neufii/Documents/Work/mediapipe/mediapipe/graphs/hand_tracking/subgraphs/BUILD:24:26: Executing genrule //mediapipe/graphs/hand_tracking/subgraphs:hand_renderer_cpu_inc failed: (Segmentation fault): sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/sandbox/darwin-sandbox/1353/execroot/mediapipe && \
  exec env - \
    PATH=/Users/neufii/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-x86_64/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands \
    TMPDIR=/var/folders/yy/vtyc_g4x0w7dtpjywdb5xt0w0000gn/T/ \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_neufii/f5de0899693f5576c099856be410b430/sandbox/darwin-sandbox/1353/sandbox.sb /var/tmp/_bazel_neufii/install/d3bd16a8b22c859ba58f5dca04a9b1aa/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/mediapipe/framework/tool/encode_as_c_string "bazel-out/darwin-opt/bin/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.binarypb" > "bazel-out/darwin-opt/bin/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.inc"')
/bin/bash: line 1: 95387 Segmentation fault: 11  bazel-out/host/bin/mediapipe/framework/tool/encode_as_c_string "bazel-out/darwin-opt/bin/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.binarypb" > "bazel-out/darwin-opt/bin/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_cpu.inc"
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
INFO: Elapsed time: 0.621s, Critical Path: 0.29s
INFO: 136 processes: 136 internal.
FAILED: Build did NOT complete successfully
```

**Comment by sureshdagooglecom** [comment]
Hi @neufii , can you provide steps to reproduce the issue.

**Comment by neufii** [comment]
Hi, I just followed the installation guide [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-macos)(use option 1 for opencv). 

After I successfully run Hello World Example (step 6), I just stay in the same folder (mediapipe) and follow [the guide](https://google.github.io/mediapipe/getting_started/cpp.html) with option 1 (Running on CPU). I got the error above after running the command in step 1.

**Comment by PrinceP** [comment]
@neufii 
Can you try with this
`bazel clean --expunge`

and retrying the build command.

**Comment by neufii** [comment]
@PrinceP Thank you for the suggestion. I've tried `bazel celan --expunge` followed by `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu` (also tried `bazel `clean` then build command) but they didn't work for my case 🥲

**Comment by neufii** [comment]
UPDATE: I've uninstalled command line tools and installed xcode from App Store. Still got the same error.

**Comment by PrinceP** [comment]
These steps are done ? 
`brew install opencv@3`
`brew uninstall --ignore-dependencies glog`

Can you add --verbose_failures in your command also?

**Comment by neufii** [comment]
@PrinceP Yes, I already did those step and got the error. However, I just managed to solve my case.
1. Remove command line tools
2. Install XCode from the App Store and accept the license agreement
3. `bazel clean --expunge`

Thank you for the support :)
