### ISSUE TITLE
Problem fetching directories

### ISSUE THREAD

**Issue by zkScorpionzk** [google/mediapipe#3151]
I've been following the installation guide for mediapipe, I'm in a Ubuntu 18.04 virtual machine and when I try to run the 

> 
> **bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
>     mediapipe/examples/desktop/hello_world:hello_world**

it prints this errors:

![Captura de pantalla de 2022-03-07 21-08-48](https://user-images.githubusercontent.com/49993279/157110108-7c7a2bd8-cdda-4a96-a3d1-a69d69ebdfc3.png)

I've been trying different solutions but so far nothing worked, any help?

**Comment by sureshdagooglecom** [comment]
Hi @zkScorpionzk ,
can you provide steps to reproduce this issue.

**Comment by zkScorpionzk** [comment]
I started downloading Ubuntu 18.04 for my Oracle VM then:

Downloaded Java jre

> sudo apt-get install default-jre

Installed bazel

> npm install -g @bazel/bazelisk

Cloned mediapipe repository

> git clone https://github.com/google/mediapipe.git

Changed directory

> cd mediapipe

Installed opencv ad FFmpeg

> sudo apt-get install -y \
>     libopencv-core-dev \
>     libopencv-highgui-dev \
>     libopencv-calib3d-dev \
>     libopencv-features2d-dev \
>     libopencv-imgproc-dev \
>     libopencv-video-dev

Now at this point when running 

> 
> bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
>     mediapipe/examples/desktop/hello_world:hello_world

I had the error "numpy" directory not found, I installed numpy and checked the python directory

> echo $PYTHON_BIN_PATH
> export PYTHON_BIN_PATH=/usr/bin/python3
> $PYTHON_BIN_PATH -c 'import numpy'

After that, when running the hello_world it's when happened the mentioned error.

I've done 

> bazel version
and after running again the hello_world this happened:

![Captura de pantalla de 2022-03-08 10-11-23](https://user-images.githubusercontent.com/49993279/157205076-498ac27b-b805-4f31-a422-9e4e5837e18f.png)

Looks like it didn't failed but it doesn't show the hello world

**Comment by PrinceP** [comment]
`
export GLOG_logtostderr=1
`
is missing

**Comment by zkScorpionzk** [comment]
Still not printing the hello world
![Captura de pantalla de 2022-03-09 09-28-01](https://user-images.githubusercontent.com/49993279/157402358-94b3a0db-4a8f-4e72-8621-c9a826518a7d.png)

**Comment by sureshdagooglecom** [comment]
@zkScorpionzk ,
Could you please share bazel version.

**Comment by zkScorpionzk** [comment]
Yeah sorry for the delay:
![Captura de pantalla de 2022-04-08 15-16-40](https://user-images.githubusercontent.com/49993279/162434044-e4fae8ef-5d14-4aa2-85cf-0a3d77797447.png)

**Comment by sureshdagooglecom** [comment]
Hi @zkScorpionzk ,
Could you please share any logs w.r.t above issue to investigate further.

**Comment by zkScorpionzk** [comment]
Sorry, what do you mean with w.r.t?

**Comment by sureshdagooglecom** [comment]
Hi @zkScorpionzk ,
Could you please share any logs for  above issue to investigate further.
