### ISSUE TITLE
Unreal Engine 4.23.1 support

### ISSUE THREAD

**Issue by aaronvdbrugge** [google/mediapipe#3152]
Is it possible to implement MediaPipe for UE 4.23.1?

Specifically HTML5 builds for web.

Thank you.

**Comment by PrinceP** [comment]
@aaronvdbrugge  Checkout this unofficial plugin.
 
https://github.com/wongfei/ue4-mediapipe-plugin

**Comment by aaronvdbrugge** [comment]
Thank you for your speedy reply, I really appreciate the great service.

So technically there should be no issue using Media Pipe with UE4.23.1?

I will check it out for sure.

**Comment by aaronvdbrugge** [comment]
I'm back, it says the requirement for the plugin is "Windows". But I'm not sure if that's referring to the project or to MediaPipe. Would MediaPipe technically work fine on an HTML5 build?

**Comment by aaronvdbrugge** [comment]
@PrinceP Sadly that plugin only offers support for Windows. :/

**Comment by kinectsources** [comment]
> @aaronvdbrugge Checkout this unofficial plugin.
> 
> https://github.com/wongfei/ue4-mediapipe-plugin

Will that repo works for Android targetting platform ?
