### ISSUE TITLE
poseWorldLandmarks missing from holistic js api

### ISSUE THREAD

**Issue by Thaina** [google/mediapipe#3155]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): html javascript
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.5.1635989137 as per https://www.jsdelivr.com/package/npm/@mediapipe/holistic
- Solution: Holistic
- Programming Language and version: JavaScript, chrome

**Describe the expected behavior:**

`holistic.onResults` should also provide `poseWorldLandmarks` in the same way as `pose.onResults`

Actually I wish `holistic.setOption` should provide option to let us enable and enable/disable each feature. And `worldPosition` should be boolean option to change every landmarks into world position. So we could have hand and face mesh in world position too

**Standalone code you may have used to try to get what you need :**

```js

  const pose = new Pose({
    locateFile: (file) => {
      if(file.startsWith("pose"))
        return `https://cdn.jsdelivr.net/npm/@mediapipe/pose/${file}`;
      return `https://cdn.jsdelivr.net/npm/@mediapipe/holistic/${file}`; // by unknown reason. Sometimes holistic file would trying to be loaded in here
    }
  });

  pose.setOptions({
    modelComplexity: 1,
    smoothLandmarks: true,
    enableSegmentation: false,
    smoothSegmentation: false,
    refineFaceLandmarks: true,
    minDetectionConfidence: 0.2,
    minTrackingConfidence: 0.2
  });

  pose.onResults((result) => {
     result.poseWorldLandmarks; // exist
  });


  const holistic = new Holistic({
    locateFile: (file) => {
      if(file.startsWith("pose"))
        return `https://cdn.jsdelivr.net/npm/@mediapipe/pose/${file}`;
      return `https://cdn.jsdelivr.net/npm/@mediapipe/holistic/${file}`;
    }
  });

  holistic.setOptions({
    modelComplexity: 1,
    smoothLandmarks: true,
    enableSegmentation: false,
    smoothSegmentation: false,
    refineFaceLandmarks: true,
    minDetectionConfidence: 0.2,
    minTrackingConfidence: 0.2
  });

  holistic.onResults((results) => {
     result.poseWorldLandmarks; // missing
  });
```

**Other info / Complete Logs :**

`undefined`

**Comment by sureshdagooglecom** [comment]
Hi @Thaina ,can you provide steps to reproduce this issue.

**Comment by Thaina** [comment]
@sureshdagooglecom Every holistic sample in js has this issue. poseWorldLandmarks just missing

**Comment by Thaina** [comment]
@sureshdagooglecom What response do you need?

**Comment by Thaina** [comment]
As you can see just debug the holistic result object. 

![image](https://user-images.githubusercontent.com/1042507/157835131-159c2af8-42d2-4275-bf80-07dbf5fa1714.png)

There was no `poseWorldLandmarks` and also no mention about world coordinate for left and right hand

As per document here there should be output for world landmark https://google.github.io/mediapipe/solutions/holistic.html#pose_world_landmarks

![image](https://user-images.githubusercontent.com/1042507/157835420-9a139990-1af6-4015-8bfd-5315f7e0ad97.png)

And also there was not even a mention about left/right hand in world coordinate

What happen to you?

**Comment by Thaina** [comment]
@sureshdagooglecom What are you waiting for?

**Comment by senzen888** [comment]
@Thaina The cdn version does contain the world landmark, but it is `result.ea` instead of 'result.poseWorldLandmarks'. However, `poseWorldLandmarks` is indeed missing in the npm package export. @sureshdagooglecom Would you mind taking a look at the missing `poseWorldLandmarks` in `@mediapipe/holistic`? I believe this is a bug because 'result.poseWorldLandmarks' is available in `@mediapipe/pose` and 'result.poseWorldLandmarks' is not in any version of holistic in the npm package.

**Comment by Thaina** [comment]
@senzen888 Thank you very much for your clarification

Indeed `poseWorldLandmarks` exist in `@mediapipe/pose` and I need to use that instead of holistic.

But I don't use npm version directly (I don't have knowledge about new js import system at all).
However I can still confirm that it not exist in npm version too. Because I use JSDoc typescript for js autocomplete in vscode which installed from npm. And the typescript version also not present `poseWorldLandmarks` in `holistic.onResults`

And so, what would it will be the fixed of this problem? Did you will have us use `ea` property instead? I wish that would be properly mentioned in documents too then

Thank you very much again

**Comment by henning101** [comment]
Hey everyone! I also noticed that there is only the ```ea``` option in ```@mediapipe/pose```. I am also wondering about this line in the documentation: ```z: Should be discarded as currently the model is not fully trained to predict depth, but this is something on the roadmap.```. When I use ```poseWorldLandmarks``` I actually get some decent results for the ```z``` axis but now I'm not sure what to use?

**Comment by Thaina** [comment]
@henning101 In my opinion, there was difference model between normal landmarks and world landmarks and currently now `poseLandmarks` cannot give you decent `z`

So if you really need to map `xyz` value to 3D application you should use `poseWorldLandmarks`
While `poseLandmarks` made for other usage like gesture and segmentation. Especially relative to screen

**Comment by henning101** [comment]
@Thaina Hi Thaina! Thank you for your reply! I worked on it a bit more and I realized that I need more stability for the ```z``` coordinate in general. Do you maybe know some good approach to derive a ```z``` approximation from the ```2D``` pose e.g. via keypoint angles.

**Comment by senzen888** [comment]
@Thaina Yes, the way around this would be to simply use `ea` for now if you are using the CDN version. I unfortunately cannot improve the docs because I am not part of google and figured this out via logging. @sureshdagooglecom would you mind exposing `ea` in the type definition. I did this locally and resolved the issue for me.

**Comment by sureshdagooglecom** [comment]
Hi @Thaina ,
Hope https://github.com/google/mediapipe/issues/3155#issuecomment-1079803517 helps to resolve this issue and please reopen this issue if still issues persists.

**Comment by Thaina** [comment]
The issue is not solved. That was only short term workaround. And I would suggest please properly fix the API

**Comment by Thaina** [comment]
@sureshdagooglecom I can't reopen this issue by my own

**Comment by Thaina** [comment]
Is this already fixed?

**Comment by kuaashish** [comment]
Hello @Thaina,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by Thaina** [comment]
> Hello @Thaina, We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).
> 
> You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

Would the holistics will be made into the list of solutions ?

**Comment by kuaashish** [comment]
@Thaina,

This is already in our roadmap(Check [here](https://developers.google.com/mediapipe/solutions/guide#legacy)). We will let you know once becomes available from our end. For now we can not provide any timeline about the release date.  Thank you!

**Comment by Thaina** [comment]
Thank you very much

Still I would like to ask, will the upgrade version support multiple holistic landmarks and stream of depth image too? Depth camera become more common and so support it would make holistic more accurate

**Comment by kuaashish** [comment]
@Thaina,

This needs to be checked with new solutions available. For now, We do not have any such documentation where the changes done compare to old legacy with upgraded one are available. Our new solution has been improved and performance increased. Further, We will let you know if any relevant document will be available from our end. However, We would like you to explore upgraded solution and revert back if the poseWorldLandmarks are missing from it.  Thank you!

**Comment by Thaina** [comment]
So the upgrade are not done yet? Are there any progress?

**Comment by kuaashish** [comment]
@Thaina,

We will working towards publish the solution as soon as possible, Which still is in our roadmap And will let you know once becomes available from our end.

**Comment by Thaina** [comment]
To be honest I have to ping this to keep the bot out from marking this as stale

**Comment by kuaashish** [comment]
Thanks for the replay back, Will keep the issue until the solution will be available from our end And will let you know.

**Comment by Thaina** [comment]
@kuaashish Thank you very much. I see there is `poseWorldLandmarks` API as expect

However, seem like there is no `faceWorldLandmarks` equivalence for `faceLandmarks`. Did it impossible to provided or it just being left out by some reason?

**Comment by kuaashish** [comment]
Hi @Thaina,

Currently, there are no faceWorldlandmarks available for the faceLandmarker. However, we currently lack information on this matter. In the meantime, could you please submit a [feature request](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Afeature&projects=&template=14-feature-request-issue-template.yaml) using the provided template with the necessary fields? We will share this with our team, and if there is enough demand, we may consider adding this feature in the near future. We would appreciate your confirmation to mark this issue as resolved and close the status, As our new Holistic Task API now returns the poseWorldlandmarks.

Thank you!!
