### ISSUE TITLE
Mediapipe hands screen landmark depth shrinkage and sometimes world landmark width shrinkage

### ISSUE THREAD

**Issue by roachsinai** [google/mediapipe#3156]
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):Windows 11
- [MediaPipe version](https://github.com/google/mediapipe/releases):0.8.9
- Bazel version:4.2.2
- Solution (e.g. FaceMesh, Pose, Holistic):Hands
- Programming Language and version ( e.g. C++, Python, Java):C++

**Describe the expected behavior:**

I've read some source code related to Hands of mediapipe, including preprocess, rotate palm, landmark inference, project landmarks, and port it to a simple C++ project.

Mediapipe 0.8.9 hand landmark model output two landmarks: screen and world, and model itself has two version:lite and full.

From the output I draw use opencv viz module, the depth of scree landmark output of full version is shrinkage than depth of lite version model. And the both screen version of 0.8.9 is shrinkage than 0.8.7.

Show result of hand_landmark_lite.tflite v 0.8.9 (the top left is screen landmakr):

![image](https://user-images.githubusercontent.com/9500049/157366097-15eed875-64a4-4760-a977-97dea0774e29.png)

Show result of hand_landmark_full.tflite v 0.8.9:

![image](https://user-images.githubusercontent.com/9500049/157366956-df20efa4-8da7-4179-a4b5-edec9f1f2cca.png)

Show result of hand_landmark.tflite v 0.8.7:

![image](https://user-images.githubusercontent.com/9500049/157368797-69cb5bb3-8419-429b-8ce3-d3e0c5dd7823.png)

So as show in above images, in my viewpoint, landmark of 0.8.7 is more acceptable, then hand_landmark_lite.tflite.

---

By the way, v0.8.9 world landmarks will distort in some pattern:

![image](https://user-images.githubusercontent.com/9500049/157388557-b1916ecb-ce70-42ad-bfb9-1fb7c0443600.png)

Above image shows world landmarks are shrinkage in width.

![image](https://user-images.githubusercontent.com/9500049/157388958-9adf200c-a086-4523-9f96-7a985b9fb0e0.png)

Above are another example.

**Comment by roachsinai** [comment]
These are three videos(images) used in above description:

https://user-images.githubusercontent.com/9500049/157389239-1b7e6097-95ab-4915-b763-628a611eb879.mp4

https://user-images.githubusercontent.com/9500049/157389254-76702be9-6b09-4f16-91ac-f98520813715.mp4

https://user-images.githubusercontent.com/9500049/157389257-596ee5d8-7124-404f-8918-fbdc48b1da49.mp4

**Comment by roachsinai** [comment]
Any suggestions to help this issue will be appreciated!

**Comment by Stephenfang51** [comment]
@roachsinai Hello, Sir  How did you find the origin of the world coordinate for the right images ?

**Comment by roachsinai** [comment]
> @roachsinai Hello, Sir How did you find the origin of the world coordinate for the right images ?

No I didn't find the origin, I just use opencv  plot THE ORIGIN: （0， 0， 0）.
