### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)

### ISSUE THREAD

**Issue by Fhlpmah** [google/mediapipe#3157]
I tried to install mediapipe on windows 7 32 bit, and im using python 3.7.9.
But as soon as i tried it on my face detection project it goes like this :

> ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe

and i already look up to #1340 and still couldnt find the solution.
I installed the mediapipe using

`pip3 install mediapipe`

and also tried with the virtual environment for 3.7 but still couldnt work.
Is it because of my OS type? Does mediapipe even support 32bit?

Would love to hear your answers real soon. Thank you

**Comment by sureshdagooglecom** [comment]
Hi @Fhlpmah , 
Please check [this](https://google.github.io/mediapipe/getting_started/troubleshooting.html#:~:text=after%20running%20pip%20install%20mediapipe%20usually%20indicates%20that%20there%20is%20no%20qualified%20MediaPipe%20Python%20for%20your%20system.%20Please%20note%20that%20MediaPipe%20Python%20PyPI%20officially%20supports%20the%2064%2Dbit%20version%20of%20Python%203.7%20to%203.10%20on%20the%20following%20OS%3A) MediaPipe official document for version mismatch

**Comment by Fhlpmah** [comment]
@sureshdagooglecom ahhhhhh alright i didnt see that. Thanks bro

**Comment by Isrealthekid** [comment]
i have the same issue but i use win 10 and version 3.12.1
