### ISSUE TITLE
Face mesh landmarks 'visibility' and 'presence' values are always 0

### ISSUE THREAD

**Issue by waleedrazakhan92** [google/mediapipe#3159]
I'm working with mediapipe face mesh landmarks model. What I want is to find the 468 landmarks for a face and then filter out any faces with occluded landmarks. The model has these attributes defined as landmarks 'visibility' and 'presence'. But when I print out these values for all the landmarks they appear to be 0. For a frontal face they should atleast have a value greater than 0.5.

**Comment by sureshdagooglecom** [comment]
Hi @waleedrazakhan92 , 
could you please share us in which platform you are trying this solution.

**Comment by waleedrazakhan92** [comment]
@sureshdagooglecom I'm using google colab.

**Comment by waleedrazakhan92** [comment]
> Hi @waleedrazakhan92 , could you please share us in which platform you are trying this solution.

@sureshdagooglecom  I'm using google colab.

**Comment by sureshdagooglecom** [comment]
Hi @waleedrazakhan92 ,
As model predicts presence and visibility as x,y values ,to get propobalities you need to apply the sigmoid function on these values so you will get   values in the range [0, 1]. We have to do this in the subsequent calculators just after the model inference in the graph.

So reasonable threshold will be 0.5 if you apply the sigmoid.

**Comment by waleedrazakhan92** [comment]
> Hi @waleedrazakhan92 , As model predicts presence and visibility as x,y values ,to get propobalities you need to apply the sigmoid function on these values so you will get values in the range [0, 1]. We have to do this in the subsequent calculators just after the model inference in the graph.
> 
> So reasonable threshold will be 0.5 if you apply the sigmoid.

@sureshdagooglecom  can you guide me as to which calculator file do I need to change and where do i put the sigmoid function?

**Comment by jimb2834** [comment]
@sureshdagooglecom - Hi Suresh, We are building a Python script to filter some face images and also wanted to use the Landmarks as a method. 

We assumed there existed a "per landmark" method or argument which; IF a landmark was not able to be applied/used or it was somehow blocked VS predicted and placed.

Usecase: We have some images were part of the Chin or Mouth is missing/covered and we want to filter that from entering a dataset. 

Can you point me in the direction of sample code or link to help me (Python)

**Comment by sureshdagooglecom** [comment]
Hi @jimb2834 ,can you share me your code changes to investigate further on this issue.

**Comment by waleedrazakhan92** [comment]
> Hi @waleedrazakhan92 , As model predicts presence and visibility as x,y values ,to get propobalities you need to apply the sigmoid function on these values so you will get values in the range [0, 1]. We have to do this in the subsequent calculators just after the model inference in the graph.
> 
> So reasonable threshold will be 0.5 if you apply the sigmoid.

Hi @sureshdagooglecom please guide me through the process of adding the calculators in the code. I believe the inference is importing the FaceMesh class from this file(https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/face_mesh.py) and in the imports section there are a number of 'calculators' imported from 'mediapipe.calculators' that calculate the final landmarks on the face. 

What i don't understand is, to utilize the 'visibility' and 'presence' attribute of the face mesh model(assuming the model does support the visibility and presence attributes), which calculator do i need to import from 'mediapipe.calculators'? 

I also believe that we need to import the calculator in 'https://github.com/google/mediapipe/blob/master/mediapipe/python/solution_base.py' and add it to :
`CALCULATOR_TO_OPTIONS = {
    'ConstantSidePacketCalculator':
        constant_side_packet_calculator_pb2.ConstantSidePacketCalculatorOptions,
    'ImageTransformationCalculator':
        image_transformation_calculator_pb2
        .ImageTransformationCalculatorOptions,
    'LandmarksSmoothingCalculator':
        landmarks_smoothing_calculator_pb2.LandmarksSmoothingCalculatorOptions,
    'LogicCalculator':
        logic_calculator_pb2.LogicCalculatorOptions,
    'ThresholdingCalculator':
        thresholding_calculator_pb2.ThresholdingCalculatorOptions,
    'TensorsToDetectionsCalculator':
        tensors_to_detections_calculator_pb2
        .TensorsToDetectionsCalculatorOptions,
    'Lift2DFrameAnnotationTo3DCalculator':
        lift_2d_frame_annotation_to_3d_calculator_pb2
        .Lift2DFrameAnnotationTo3DCalculatorOptions,
}
`
No which calculator do i need to pass here and what other changes do i need to make to make the visibility and the presence calculators available for my face mesh model inference?

Please any help and example would be appreciated!

**Comment by jimb2834** [comment]
@sureshdagooglecom - I will ask my team lead if we can. But I was following this guide here - 

[](https://towardsdatascience.com/face-landmarks-detection-with-mediapipe-facemesh-555fa2e10b06 )

We are doing the same thing as @waleedrazakhan92 

Our use case is to pass an image which may have part of the "jaw line" obfuscated, or maybe one eye is covered etc.. And use the landmark "visibility" or "presence" to indicate this. 

Qn: Is this possible ?

I thought we could use the landmarks to tell us this info and then I can filter out these bad images.

**Comment by jimb2834** [comment]
@cdibona @sureshdagooglecom  - Is it true that in python you can not get the landmark visibility or presence values?

**Comment by waleedrazakhan92** [comment]
> Hi @waleedrazakhan92 , As model predicts presence and visibility as x,y values ,to get propobalities you need to apply the sigmoid function on these values so you will get values in the range [0, 1]. We have to do this in the subsequent calculators just after the model inference in the graph.
> 
> So reasonable threshold will be 0.5 if you apply the sigmoid.

Hi @sureshdagooglecom,
You said we need to add the sigmoid function to the calculators to get the visibility and presence values between 0 and 1. So i believe that would be the 'tensors_to_landmarks_calculator_pb2.py' calculator. Upon investigating the code I believe that its already applying the sigmoid function on the values. If you see the lines 143-147 isn't it already applying the sigmoid function to the values?


1. `# -*- coding: utf-8 -*-
2. # Generated by the protocol buffer compiler.  DO NOT EDIT!
3. # source: mediapipe/calculators/tensor/tensors_to_landmarks_calculator.proto
4. 
5. import sys
6. _b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
7. from google.protobuf import descriptor as _descriptor
8. from google.protobuf import message as _message
9. from google.protobuf import reflection as _reflection
10. from google.protobuf import symbol_database as _symbol_database
11. # @@protoc_insertion_point(imports)
12. 
13. _sym_db = _symbol_database.Default()
14. 
15. 
16. from mediapipe.framework import calculator_pb2 as mediapipe_dot_framework_dot_calculator__pb2
17. try:
18.   mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe_dot_framework_dot_calculator__options__pb2
19. except AttributeError:
20.   mediapipe_dot_framework_dot_calculator__options__pb2 = mediapipe_dot_framework_dot_calculator__pb2.mediapipe.framework.calculator_options_pb2
21. 
22. 
23. DESCRIPTOR = _descriptor.FileDescriptor(
24.   name='mediapipe/calculators/tensor/tensors_to_landmarks_calculator.proto',
25.   package='mediapipe',
26.   syntax='proto2',
27.   serialized_options=None,
28.   serialized_pb=_b('\nBmediapipe/calculators/tensor/tensors_to_landmarks_calculator.proto\x12\tmediapipe\x1a$mediapipe/framework/calculator.proto\"\x8f\x04\n#TensorsToLandmarksCalculatorOptions\x12\x15\n\rnum_landmarks\x18\x01 \x01(\x05\x12\x19\n\x11input_image_width\x18\x02 \x01(\x05\x12\x1a\n\x12input_image_height\x18\x03 \x01(\x05\x12\x1e\n\x0f\x66lip_vertically\x18\x04 \x01(\x08:\x05\x66\x61lse\x12 \n\x11\x66lip_horizontally\x18\x06 \x01(\x08:\x05\x66\x61lse\x12\x16\n\x0bnormalize_z\x18\x05 \x01(\x02:\x01\x31\x12^\n\x15visibility_activation\x18\x07 \x01(\x0e\x32\x39.mediapipe.TensorsToLandmarksCalculatorOptions.Activation:\x04NONE\x12\\\n\x13presence_activation\x18\x08 \x01(\x0e\x32\x39.mediapipe.TensorsToLandmarksCalculatorOptions.Activation:\x04NONE\"#\n\nActivation\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07SIGMOID\x10\x01\x32]\n\x03\x65xt\x12\x1c.mediapipe.CalculatorOptions\x18\xb0\x8d\x8c\xa0\x01 \x01(\x0b\x32..mediapipe.TensorsToLandmarksCalculatorOptions')
29.   ,
30.   dependencies=[mediapipe_dot_framework_dot_calculator__pb2.DESCRIPTOR,])
31. 
32. 
33. 
34. _TENSORSTOLANDMARKSCALCULATOROPTIONS_ACTIVATION = _descriptor.EnumDescriptor(
35.   name='Activation',
36.   full_name='mediapipe.TensorsToLandmarksCalculatorOptions.Activation',
37.   filename=None,
38.   file=DESCRIPTOR,
39.   values=[
40.     _descriptor.EnumValueDescriptor(
41.       name='NONE', index=0, number=0,
42.       serialized_options=None,
43.       type=None),
44.     _descriptor.EnumValueDescriptor(
45.       name='SIGMOID', index=1, number=1,
46.       serialized_options=None,
47.       type=None),
48.   ],
49.   containing_type=None,
50.   serialized_options=None,
51.   serialized_start=517,
52.   serialized_end=552,
53. )
54. _sym_db.RegisterEnumDescriptor(_TENSORSTOLANDMARKSCALCULATOROPTIONS_ACTIVATION)
55. 
56. 
57. _TENSORSTOLANDMARKSCALCULATOROPTIONS = _descriptor.Descriptor(
58.   name='TensorsToLandmarksCalculatorOptions',
59.   full_name='mediapipe.TensorsToLandmarksCalculatorOptions',
60.   filename=None,
61.   file=DESCRIPTOR,
62.   containing_type=None,
63.   fields=[
64.     _descriptor.FieldDescriptor(
65.       name='num_landmarks', full_name='mediapipe.TensorsToLandmarksCalculatorOptions.num_landmarks', index=0,
66.       number=1, type=5, cpp_type=1, label=1,
67.       has_default_value=False, default_value=0,
68.       message_type=None, enum_type=None, containing_type=None,
69.       is_extension=False, extension_scope=None,
70.       serialized_options=None, file=DESCRIPTOR),
71.     _descriptor.FieldDescriptor(
72.       name='input_image_width', full_name='mediapipe.TensorsToLandmarksCalculatorOptions.input_image_width', index=1,
73.       number=2, type=5, cpp_type=1, label=1,
74.       has_default_value=False, default_value=0,
75.       message_type=None, enum_type=None, containing_type=None,
76.       is_extension=False, extension_scope=None,
77.       serialized_options=None, file=DESCRIPTOR),
78.     _descriptor.FieldDescriptor(
79.       name='input_image_height', full_name='mediapipe.TensorsToLandmarksCalculatorOptions.input_image_height', index=2,
80.       number=3, type=5, cpp_type=1, label=1,
81.       has_default_value=False, default_value=0,
82.       message_type=None, enum_type=None, containing_type=None,
83.       is_extension=False, extension_scope=None,
84.       serialized_options=None, file=DESCRIPTOR),
85.     _descriptor.FieldDescriptor(
86.       name='flip_vertically', full_name='mediapipe.TensorsToLandmarksCalculatorOptions.flip_vertically', index=3,
87.       number=4, type=8, cpp_type=7, label=1,
88.       has_default_value=True, default_value=False,
89.       message_type=None, enum_type=None, containing_type=None,
90.       is_extension=False, extension_scope=None,
91.       serialized_options=None, file=DESCRIPTOR),
92.     _descriptor.FieldDescriptor(
93.       name='flip_horizontally', full_name='mediapipe.TensorsToLandmarksCalculatorOptions.flip_horizontally', index=4,
94.       number=6, type=8, cpp_type=7, label=1,
95.       has_default_value=True, default_value=False,
96.       message_type=None, enum_type=None, containing_type=None,
97.       is_extension=False, extension_scope=None,
98.       serialized_options=None, file=DESCRIPTOR),
99.     _descriptor.FieldDescriptor(
100.       name='normalize_z', full_name='mediapipe.TensorsToLandmarksCalculatorOptions.normalize_z', index=5,
101.       number=5, type=2, cpp_type=6, label=1,
102.       has_default_value=True, default_value=float(1),
103.       message_type=None, enum_type=None, containing_type=None,
104.       is_extension=False, extension_scope=None,
105.       serialized_options=None, file=DESCRIPTOR),
106.     _descriptor.FieldDescriptor(
107.       name='visibility_activation', full_name='mediapipe.TensorsToLandmarksCalculatorOptions.visibility_activation', index=6,
108.       number=7, type=14, cpp_type=8, label=1,
109.       has_default_value=True, default_value=0,
110.       message_type=None, enum_type=None, containing_type=None,
111.       is_extension=False, extension_scope=None,
112.       serialized_options=None, file=DESCRIPTOR),
113.     _descriptor.FieldDescriptor(
114.       name='presence_activation', full_name='mediapipe.TensorsToLandmarksCalculatorOptions.presence_activation', index=7,
115.       number=8, type=14, cpp_type=8, label=1,
116.       has_default_value=True, default_value=0,
117.       message_type=None, enum_type=None, containing_type=None,
118.       is_extension=False, extension_scope=None,
119.       serialized_options=None, file=DESCRIPTOR),
120.   ],
121.   extensions=[
122.     _descriptor.FieldDescriptor(
123.       name='ext', full_name='mediapipe.TensorsToLandmarksCalculatorOptions.ext', index=0,
124.       number=335742640, type=11, cpp_type=10, label=1,
125.       has_default_value=False, default_value=None,
126.       message_type=None, enum_type=None, containing_type=None,
127.       is_extension=True, extension_scope=None,
128.       serialized_options=None, file=DESCRIPTOR),
129.   ],
130.   nested_types=[],
131.   enum_types=[
132.     _TENSORSTOLANDMARKSCALCULATOROPTIONS_ACTIVATION,
133.   ],
134.   serialized_options=None,
135.   is_extendable=False,
136.   syntax='proto2',
137.   extension_ranges=[],
138.   oneofs=[
139.   ],
140.   serialized_start=120,
141.   serialized_end=647,
142. )
143. 
144. _TENSORSTOLANDMARKSCALCULATOROPTIONS.fields_by_name['visibility_activation'].enum_type = _TENSORSTOLANDMARKSCALCULATOROPTIONS_ACTIVATION
145. _TENSORSTOLANDMARKSCALCULATOROPTIONS.fields_by_name['presence_activation'].enum_type = _TENSORSTOLANDMARKSCALCULATOROPTIONS_ACTIVATION
146. _TENSORSTOLANDMARKSCALCULATOROPTIONS_ACTIVATION.containing_type = _TENSORSTOLANDMARKSCALCULATOROPTIONS
147. DESCRIPTOR.message_types_by_name['TensorsToLandmarksCalculatorOptions'] = _TENSORSTOLANDMARKSCALCULATOROPTIONS
148. _sym_db.RegisterFileDescriptor(DESCRIPTOR)
149. 
150. TensorsToLandmarksCalculatorOptions = _reflection.GeneratedProtocolMessageType('TensorsToLandmarksCalculatorOptions', (_message.Message,), dict(
151.   DESCRIPTOR = _TENSORSTOLANDMARKSCALCULATOROPTIONS,
152.   __module__ = 'mediapipe.calculators.tensor.tensors_to_landmarks_calculator_pb2'
153.   # @@protoc_insertion_point(class_scope:mediapipe.TensorsToLandmarksCalculatorOptions)
154.   ))
155. _sym_db.RegisterMessage(TensorsToLandmarksCalculatorOptions)
156. 
157. _TENSORSTOLANDMARKSCALCULATOROPTIONS.extensions_by_name['ext'].message_type = _TENSORSTOLANDMARKSCALCULATOROPTIONS
158. mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_TENSORSTOLANDMARKSCALCULATOROPTIONS.extensions_by_name['ext'])
159. 
160. # @@protoc_insertion_point(module_scope)
161. `
162.

**Comment by jimb2834** [comment]
@sureshdagooglecom - Any word if this is working for anyone?

**Comment by jimb2834** [comment]
@waleedrazakhan92 - have you solved this ? The topic is stale ?

**Comment by jimb2834** [comment]
@sureshdagooglecom - Hello, Could you please let me know if you sell support tickets to review and fix the script ?

**Comment by waleedrazakhan92** [comment]
> @waleedrazakhan92 - have you solved this ? The topic is stale ? What did the Mediapipe team in Slack say ?

@jimb2834 I haven't received a solution yet. There are however a number of similar issues but no helpful solutions have been presented by the team. Also there is no clear cut indication whether the face mesh model indeed outputs 'visibility' and 'presence' values or not. I also did try editing the graph file as mentioned in #3200 but the graph doesn't build. I'm confused why the mediapipe team hasn't been helpful in all this since the issue seems to be recurring.

**Comment by jimb2834** [comment]
bump to stay open and get a reply

**Comment by jimb2834** [comment]
@sureshdagooglecom - Hi Suresh, Would you be willing to re-assign this to someone with more availability ?

**Comment by zeina-abuaisheh** [comment]
Hi, I also have the very same problem, I would love to find a way to have a "visibility", "presence", or a "confidence score" for each individual landmark, I have been trying without any success, did anyone manage to find a solution?

**Comment by jimb2834** [comment]
@zeina-abuaisheh - We as you can see have been waiting >5 months now and no replys. We have no known solution yet the API docs still state Visibility in the facemesh lib docs

**Comment by tsnagtode21** [comment]
@waleedrazakhan92  - Any update about this visibility and presence for each landmark issue? We are still facing this issue.

**Comment by waleedrazakhan92** [comment]
> @waleedrazakhan92 - Any update about this visibility and presence for each landmark issue? We are still facing this issue.

@tsnagtode21 No its not resolved yet.

**Comment by kuaashish** [comment]
Hello @waleedrazakhan92,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by bml1g12** [comment]
> Hello @waleedrazakhan92, We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).
> 
> You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

@kuaashish so the conclusion is the newer model has no way to determine confidence/visibility/presence of keypoints? I'm unclear if you're suggesting as a conclusion to this issue that the Legacy version _does_ have this functionality?

**Comment by msaitool** [comment]
I have the same problem. I want to check if the face is occluded or not. I print the landmark.visibility and landmark.presence and they always are 0 whatever face's occluded or normal. I would like to know what do they for ?

**Comment by manas-jaiswal** [comment]
facing same issue is medaipipe team doing something about it

**Comment by Redhair957** [comment]
dlib can solve it

**Comment by yujia-mt** [comment]
same issue
