### ISSUE TITLE
[face mesh] GPU inference on Google Colab

### ISSUE THREAD

**Issue by waleedrazakhan92** [google/mediapipe#3161]
I'm using the Colab notebook(https://colab.research.google.com/github/kevinash/awesome-ai/blob/main/notebooks/5_FacesAndExpressions/MediaPipe_Face_Mesh.ipynb#scrollTo=BboTB-FAMfPo) to run face mesh landmarks model on static images. The model runs fine on CPU. How do I run inference using the colab gpu?

**Comment by sureshdagooglecom** [comment]
Hi @waleedrazakhan92 , MediaPipe Python package only contains CPU graphs. If you need to run any GPU graphs, see #1651 (comment).
