### ISSUE TITLE
android facemesh with full range face detect

### ISSUE THREAD

**Issue by eli-6over6** [google/mediapipe#3163]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): com.google.mediapipe.solutions.facemesh
- Programming language : Android Java
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state:**
android face mesh will work on small faces or long-range faces

**Will this change the current api? How?**
yes, FaceMeshOptions.builder().setFullRange(true);

**Who will benefit with this feature?**
everyone

**Please specify the use cases for this feature:**
When you far from the camera the user face are not detected.

**Any Other info:**

**Comment by sureshdagooglecom** [comment]
Hi @eli-6over6 , , Can you share the steps followed to reproduce the above issue. Thanks !

**Comment by sureshdagooglecom** [comment]
Hi @eli-6over6 ,
Could you share reference video w.r.t to above use case.

**Comment by eli-6over6** [comment]
Still not fixed. How face detection work with full range on Android?

**Comment by sureshdagooglecom** [comment]
Hi @eli-6over6 ,
Could you share reference video w.r.t to above use case.

**Comment by eli-6over6** [comment]
video is irrelevant here.. 
the question is how facemesh can run with full range?

**Comment by eli-6over6** [comment]
?

**Comment by kuaashish** [comment]
Hello @eli-6over6,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by Ap1075** [comment]
Any updates on this?
