### ISSUE TITLE
Compile Holistic tracking for arm's linux on x86 linux

### ISSUE THREAD

**Issue by Yang-lin-09** [google/mediapipe#3166]
I would like to ask, how to cross compile arm's linux on x86 linux, is there some tutorial that can teach me how to do it? Because the mediapipe file is a bit complicated, and bazel is not very easy to learn. thank you very much for your help.

**Comment by sureshdagooglecom** [comment]
Hi @Yang-lin-09 ,
Can you please elaborate this issue to investigate further.

**Comment by Yang-lin-09** [comment]
I want to compile Holistic tracking for my arm64 RK3399Pro on my x86 computer, but I don't know how to cross compile Holistic tracking, so does mediapipe support this kind of cross compilation? Or do we need some special tricks to do this kind of cross compilation.

**Comment by Yang-lin-09** [comment]
I saw the example compiled to Coral, this operation can also compile the example in the desktop folder, to other arm64 machines?

**Comment by jiuqiant** [comment]
The easiest way is to modify https://github.com/google/mediapipe/blob/master/Dockerfile to base on an aarch64 image and build aarch64 build targets in that docker container.

**Comment by Yang-lin-09** [comment]
Ok, I'll check it out and thank you very much for your answer. I will close this issue.

**Comment by puxiao** [comment]
@Yang-lin-09  你安装成功了吗？我在我的腾讯云上也是安装失败。如果你安装成功了，可以指导我一下吗？

**Comment by Yang-lin-09** [comment]
Yes. So what's your question?
I configured my docker with this file **mediapipe/examples/coral/Dockerfile.arm64**. I successfully cross-compiled the executable from this file **mediapipe/examples/coral/README.md**.

**Comment by puxiao** [comment]
Thanks @Yang-lin-09 

```
uname -a

//
Linux VM_0_8_centos 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Finally, I used '**mediapipe/examples/coral/Dockerfile.amd64**' and succeeded.



<br>

But,

I found that in China, I can't access this page `https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/`.

...

```
root@2073d3308ffb:/# GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world
2022/03/27 05:03:10 could not resolve the version 'latest' to an actual version number: unable to determine latest version: could not list Bazel versions in GCS bucket: could not list GCS objects at https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: could not fetch https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: Get "https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/": dial tcp 172.217.160.106:443: i/o timeout
```

**Comment by Yang-lin-09** [comment]
This can happen very often. I think you can terminate the compilation, recompile a few times which may by useful.

**Comment by wuheng0711** [comment]
I would like to ask how to build aarch64 target in docker container

**Comment by Yang-lin-09** [comment]
> I would like to ask how to build aarch64 target in docker container

I think this link can help you. https://github.com/google/mediapipe/tree/master/mediapipe/examples/coral#cross-compilation

**Comment by wuheng0711** [comment]
> > I would like to ask how to build aarch64 target in docker container
> 
> I think this link can help you. https://github.com/google/mediapipe/tree/master/mediapipe/examples/coral#cross-compilation

Thank you very much. I'll try it.
