### ISSUE TITLE
JavaScript npm packages with ES6 module format

### ISSUE THREAD

**Issue by felixapitzsch** [google/mediapipe#3167]
This issue is intended to extend the discussion from issue #1408 (assigned to @mhays-google). 

In issue #1408, it is being proposed to use d.ts typings from the Mediapipe npm packages as a temporary substitute for having public JavaScript source code available. However, the typings from the npm packages are problematic, because they pretend that the packages provide a module scope with some specific named exports (classes), while the included ES5-IIFE-bundled JavaScript files actually don't provide this. Therefore, I would like to propose/request that the Mediapipe npm packages should contain an ESM-bundle in addition to (or instead of) the ES5-IIFE-bundle.

Reasons why the ESM-bundle would be very helpful:

1. Typings would match the actual code better. Having 'incorrect' typings **breaks some tooling** and build chains.
2. Dumping minified code that is only partially documented into the global namespace could lead to **name collisions** and might not comply with some developers' code quality policies.
3. Including Mediapipe as a dependency in other libraries via real module scopes would allow for **tree-shaking** later on. 
4. ES2021+ code using modules is conveniently **convertible into other code styles** (e.g. using babel/rollup) and earlier ES-versions, but in most cases not the other way around.

Given the existing d.ts files and assuming the original source code is written in Typescript, it should be very easy to change the output format in the tsconfig (and additional build-chain?) to ES2020 or later. Code minification and obfuscation can be applied as with the ES5-IIFE-bundle.

**System information**

- MediaPipe Solution (you are using): JavaScript solution
- Programming language : JavaScript / TypeScript
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state:**

- Requested feature: JavaScript files in Mediapipe npm packages contain ES2020+ code and export statements with specific named exports matching the already provided d.ts files.
- Current behavior: JavaScript files in Mediapipe npm packages contain ES5-IIFE code and lack export statements with specific named exports matching the already provided d.ts files.

**Will this change the current api? How?**

- No, the same API will be available, but properly enclosed by a module scope.
- If multiple code flavors (ES5/ES6) were included in the npm packages, existing applications would not need to change a single line of code. But whoever is interested could optionally use the code as an ES-module.

**Who will benefit with this feature?**

- Anyone with a ES6 build chain.
- Anyone who uses Mediapipe in a library that should stay tree-shakeable.
- Anyone who has the same taste for variable and class names like the Mediapipe developers.

**Please specify the use cases for this feature:**

- Using Mediapipe in a JavaScript library written in ES2021 using ES-modules and RollupJS for bundling. Being able to tree-shake the library when only using some parts of it (maybe not Mediapipe at all) for some web application.

**Comment by kuaashish** [comment]
@felixapitzsch,

This feature has been implemented, Our new MediaPipe Tasks Web supports ES6 format. Please explore the upgraded solutions.

**Comment by felixapitzsch** [comment]
> @felixapitzsch,
> 
> This feature has been implemented, Our new MediaPipe Tasks Web supports ES6 format. Please explore the upgraded solutions.

@kuaashish 
Thanks for the effort to work on this feature request. Even though there is a browser/OS-native [background-blur feature](https://chromestatus.com/feature/5077577782263808) on the horizon,  this upgrade is still highly appreciated. 

I am not sure which commit implements the relevant changes. If it is [this one](https://github.com/google/mediapipe/commit/a7cd7b9a321371737f0bfd27e86800b110acf369), I cannot tell the exact impact on the build process.

Because the Mediapipe JavaScript implementation is closed source, you would need to publish a new NPM-package in order for me and other interested developers to explore the upgraded solution and provide feedback. At the time of writing this, the latest `@mediapipe/selfie_segmentation` package still at version 0.1.1675465747 (4 months old).

**Comment by kuaashish** [comment]
@felixapitzsch,

We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

However, In our upgraded solutions Selfie-Segmentation is the part of Image Segmentation as [noted here](https://developers.google.com/mediapipe/solutions/guide#legacy) And can check the newer package details [@mediapipe/tasks-vision](https://www.npmjs.com/package/@mediapipe/tasks-vision).
