### ISSUE TITLE
iOS: Hand tracking gpu example errors after upgrading Xcode to 13.3 and MacOS 12.3

### ISSUE THREAD

**Issue by Gaozhongpai** [google/mediapipe#3168]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (MacOS 12.3): 
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version: 4.2.
- Solution (e.g. HandTrackingGpuApp):
- Programming Language and version ( iOS):

`bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp --verbose_failures`

**Describe the expected behavior:**

ERROR: /Users/pi/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:34:16: AssetCatalogCompile mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp-intermediates/xcassets failed: (Exit 127): xctoolrunner failed: error executing command 
  (cd /private/var/tmp/_bazel_pi/42d475cadf09c8a581c9bfebea7fe9e7/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=15.4 \
    XCODE_VERSION_OVERRIDE=13.3.0.13E113 \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner actool --compile '[ABSOLUTE]bazel-out/applebin_ios-ios_arm64-opt-ST-50603ff4af65/bin/mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp-intermediates/xcassets' --platform iphoneos --minimum-deployment-target 10.0 --compress-pngs --product-type com.apple.product-type.application --app-icon AppIcon --target-device iphone --target-device ipad --output-partial-info-plist '[ABSOLUTE]bazel-out/applebin_ios-ios_arm64-opt-ST-50603ff4af65/bin/mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp-intermediates/xcassets-info.plist' '[ABSOLUTE]mediapipe/examples/ios/common/Assets.xcassets')
Execution platform: @local_execution_config_platform//:platform
env: python: No such file or directory
Target //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp failed to build
INFO: Elapsed time: 0.661s, Critical Path: 0.43s
INFO: 41 processes: 41 internal.
FAILED: Build did NOT complete successfully

**Comment by Gaozhongpai** [comment]
https://github.com/bazelbuild/rules_apple/issues/243

**Comment by sureshdagooglecom** [comment]
Hi @Gaozhongpai ,
Still are you facing any issue w.r.t above issue?

**Comment by Gaozhongpai** [comment]
I reinstalled the MacOS system back to 11 and solved the problem.

**Comment by jackprescott** [comment]
I am having this issue and would not like to revert my MacOS version. Any suggestions?

**Comment by sureshdagooglecom** [comment]
Hi @jackprescott ,
Could you restart your Macos back to 11 as per @Gaozhongpai .
