### ISSUE TITLE
[Question] How are the model cards generated?

### ISSUE THREAD

**Issue by youquzhiji** [google/mediapipe#3169]
I saw that the model card format is very beautiful and clean, but I cannot find source code that generated the model cards in this repo. How are they generated? Are the model card PDF generation code used in MediaPipe open-sourced?

Thanks!

**Comment by youquzhiji** [comment]
Also, every commit message says "Project import generated by Copybara." Where is the original repository? Is it open to the public? If not, are the original commit messages available?

**Comment by sureshdagooglecom** [comment]
Hi @youquzhiji ,
Please check MediaPipe [documentation](https://google.github.io/mediapipe/solutions/models.html) for model cards information.

**Comment by youquzhiji** [comment]
> Hi @youquzhiji , Please check MediaPipe [documentation](https://google.github.io/mediapipe/solutions/models.html) for model cards information.

Thank you for the reply! But I don't think the documentation include how the model cards on that page are created (i.e. by specific program  or pure human input). It also don't allow us to access older versions of the model cards. Would you tell me how the model cards are generated?

**Comment by sureshdagooglecom** [comment]
Hi @youquzhiji ,
did you get a chance to check [this](https://github.com/google/mediapipe/tree/master/mediapipe/models) github code for models.

**Comment by youquzhiji** [comment]
> Hi @youquzhiji , did you get a chance to check [this](https://github.com/google/mediapipe/tree/master/mediapipe/models) github code for models.

Yes I checked. The converted tflite model files are not the ones used for model card generation.

**Comment by sureshdagooglecom** [comment]
Hi @youquzhiji , did you get the required information now?
