### ISSUE TITLE
HandTrackingGpu not working on Google cloud

### ISSUE THREAD

**Issue by alizahidraja** [google/mediapipe#317]
i have literally tried everything but nothing works

i am using Tesla k80
cuda 10.2
driver 440
 and it gives GL error on line 253 of gl library and i cannot seem to get it running

**Comment by alizahidraja** [comment]
E1212 09:25:37.308670 13890 demo_run_graph_main_gpu.cc:257] Failed to run the graph: Graph has errors: 
Calculator::Open() for node "[TfLiteInferenceCalculator_1, TfLiteInferenceCalculator with output stream: __sg0_detection_tensors]" failed: [GL_INVALID_ENUM]: An unacceptable value is specified for an enumerated argument.: glBufferData in external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_buffer.h:253

**Comment by mcclanahoochie** [comment]
please follow instructions here https://github.com/google/mediapipe/issues/150#issuecomment-565135162
and see if your gpu supports opengl es 3.1+

also make sure the mesa drivers are properly installed
`sudo apt-get install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev
`

**Comment by alizahidraja** [comment]
checked everything oncce again:

lastest error :
Created TensorFlow Lite delegate for GPU.
double free or corruption (fasttop)
Aborted (core dumped)

GL version: 3.1

**Comment by alizahidraja** [comment]
it is fixed

here;s how:

use this command to find your PCIbusid
`nvidia-xconfig --query-gpu-info`

Sample output:
`Number of GPUs: 1

GPU #0:
  Name      : Tesla P4
  UUID      : GPU-093812be-b975-b29b-f6e5-675a9f79f896
  PCI BusID : PCI:0:4:0

  Number of Display Devices: 0
`


then use this command:
`sudo nvidia-xconfig --busid=PCI:0:4:0 --use-display-device=none `--virtual=1280x1024`

this will change your /etc/X11/xorg.conf file
to keep using teamviewer on server, edit the screen section of the conf file as follows
`
Section "Screen"
    Identifier  "Default Screen"
    Monitor     "Configured Monitor"
    Device      "Configured Video Device"
    DefaultDepth 24
    SubSection "Display"
    Depth 24
    Modes "1600x900"
    EndSubSection
EndSection
`

now you can use a server to run the MultipleHandTracking GPU

**Comment by mcclanahoochie** [comment]
excellent! 
nice work and thanks for the detailed instructions :)
