### ISSUE TITLE
A mediapipe model to extract head pose features (yaw, pitch, roll)

### ISSUE THREAD

**Issue by msreevani060** [google/mediapipe#3171]
Expecting Same behavior of posted you tube url :
https://youtu.be/yCvsTPcb5h4

Need to calculate head pose features Yaw, Pitch, roll with face mesh landmarks. 

Please post if any github code citiations/references had.

**Comment by sureshdagooglecom** [comment]
Hi @msreevani060 ,
There are lot you can try with [Gace Geometry API ](https://google.github.io/mediapipe/solutions/face_mesh.html#face-geometry-module). Please have a look at our documentation and reach us back if you still have any specific queries w.r.t to it. Thanks
