### ISSUE TITLE
Verifying a rs256 side packet string in calculator

### ISSUE THREAD

**Issue by RamziAgou** [google/mediapipe#3172]
Hey everyone,

Here is my problem, so I want to create a calculator that receive as a side packet a rs256 string, and verify it.
The main goal of this calculator is being used in an Android environment. 

I managed to create this calculator and make it work in python with the jwt-cpp library. The problem is that this library is using OpenSSL and that it works well on my Linux environment but when I build it with bazel, I obviously got some errors.

After some research, I found that openSSL is kinda difficult to build for Android, and that Google created boringSSL being easier to integrate in Android projects. (https://github.com/google/boringssl)

I managed to build my project with this new dependency and the build was successfull, but then when my Android application load the all the library I got a fatal error : 

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "RSA_new" referenced by "/data/app/~~zOvcucSPKBAPIbausO7cdw==/io.quantiq.cobox-pHTYIDTihazRgyhvufdfTQ==/base.apk!/lib/arm64-v8a/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)

So if I understand it well, it seems that the build with bazel is working because it ignore undefined symbol, but when it comes to runtime it crashed...

So now I am asking you if someone know how to use mediapipe with openssl, boringssl, or just a new way to verify a rs256 string inside a calculator.

Sorry in advance, this is my first issue ever, I tried to be as clear as possible. Let me know if you need more information and thank you for your help

**Comment by sureshdagooglecom** [comment]
Hi @RamziAgou ,
could you provide steps to reproduce this issue.
