### ISSUE TITLE
Is there any way to use shared tensorflow lite library on Android to reduce the aab size?

### ISSUE THREAD

**Issue by junnikokuki** [google/mediapipe#3174]
- MediaPipe Solution (you are using): Face Detection\Face Mesh
- Programming language : C++/Android Java
- Are you willing to contribute it (Yes/No): Yes

I have a use case that need to use tensor-flow lite shared library from maven in Android, but I also want to use the Mediapipe solutions. Is there any compile option that can compile the Mediapipe with shared tensor-flow lite library? Thank you.

**Comment by sureshdagooglecom** [comment]
Hi @junnikokuki ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/77

**Comment by junnikokuki** [comment]
Yes, but my request feature is totally different. Currently the Mediapipe will compile the tensorflow lite lib into the jni so file, but I want to use the tensorflow lite library in a shared way. That is Mediapipe (and other model using tensorflow lite library) can use a shared tensorflow lite so file.

**Comment by jiuqiant** [comment]
Unfortunately, It's currently not supported. We do see this as a great feature to have and will prioritize this work.

**Comment by sureshdagooglecom** [comment]
@junnikokuki , we don't have this shared feature as of now, we will share with internal team as a feature request.

**Comment by csn1800** [comment]
> @junnikokuki , we don't have this shared feature as of now, we will share with internal team as a feature request.

@sureshdagooglecom Is this feature under implementation? Could you please let know the ETA for the same?
