### ISSUE TITLE
How can build application for using live camera to get iris depth info from windows desktop?

### ISSUE THREAD

**Issue by cx68cx** [google/mediapipe#3175]
Hello, I want to build an application demo for detecting iris depth under windows, I can go to the focal length of the external camera, I can build iris_tracking:iris_tracking_cpu now, how can I do it next? Looking forward to your reply and wish you a happy life.

**Comment by cx68cx** [comment]
这个功能类似iris_tracking:iris_depth_from_image_desktop，只是使用了live camera，并且我可以获取焦距，我想我需要一个实例来指导，谢谢你。

**Comment by cx68cx** [comment]
This function is similar to iris_tracking:iris_depth_from_image_desktop, but uses a live camera, and I can get the focal length, I think I need an example to guide, thank you.

**Comment by sureshdagooglecom** [comment]
Hi @cx68cx , 
Did you get a chance to check this issue https://github.com/google/mediapipe/issues/1033.

**Comment by cx68cx** [comment]
> 
Dear sureshdagooglecom, I looked carefully at issue #1033, the question is iris_depth_from_image_desktop example, but what I need is iris_depth_from_live_camera_desktop examplex, looking forward to your reply

**Comment by sureshdagooglecom** [comment]
Please check MediaPipe [document](https://google.github.io/mediapipe/solutions/iris.html#:~:text=examples/ios/iristrackinggpu%3AIrisTrackingGpuApp-,Desktop,LIVE%20CAMERA%20INPUT,-Please%20first%20see) for live input and follow the steps mentioned.

**Comment by cx68cx** [comment]
> Please check MediaPipe [document](https://google.github.io/mediapipe/solutions/iris.html#:~:text=examples/ios/iristrackinggpu%3AIrisTrackingGpuApp-,Desktop,LIVE%20CAMERA%20INPUT,-Please%20first%20see) for live input and follow the steps mentioned.

Dear sureshdagooglecom, I checked the documentation Solutions-Iris-Desktop carefully, according to "LIVE CAMERA INPUT", I don't know how to get the iris depth information. If you have time to guide me patiently, thank you very much.

**Comment by cx68cx** [comment]
> Please check MediaPipe [document](https://google.github.io/mediapipe/solutions/iris.html#:~:text=examples/ios/iristrackinggpu%3AIrisTrackingGpuApp-,Desktop,LIVE%20CAMERA%20INPUT,-Please%20first%20see) for live input and follow the steps mentioned.

i mean “ iris depth information” is <output_stream: "LEFT_IRIS_DEPTH_MM:left_iris_depth_mm"> and <
  output_stream: "RIGHT_IRIS_DEPTH_MM:right_iris_depth_mm">, thank you!

**Comment by sureshdagooglecom** [comment]
@cx68cx ,did you get the required information?

**Comment by cx68cx** [comment]
no bro, i'm confused, can you show me your config or code example, thanks.

**Comment by sureshdagooglecom** [comment]
Please check this graph https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/iris_tracking/subgraphs/iris_and_depth_renderer_gpu.pbtxt

**Comment by andy380743909** [comment]
> Please check this graph https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/iris_tracking/subgraphs/iris_and_depth_renderer_gpu.pbtxt

hi @sureshdagooglecom , I think the problem is how can we get EXIF info from the data stream from webcamera. I had google a lot, but nothing found.
