### ISSUE TITLE
Getting cannot read undefined issue on android chrome sometimes

### ISSUE THREAD

**Issue by veetechh** [google/mediapipe#3177]
Sometimes under mobile internet, I am getting cannot read undefined issue on android chrome and it shows HEAP8 undefined on firefox mobile. It works after I reload. Any solution
![Captureerr](https://user-images.githubusercontent.com/19422397/158762826-c06c3447-c1f2-4939-8803-38c675b30711.JPG)

**Comment by sureshdagooglecom** [comment]
Hi @veetechh ,
import the file using <script src='.....'</script>
then in your react code use
const LandMarkGrid =window.LandmarkGrid

grid = new LandmarGrid (divRef, ....)
be careful to components re-rendering (strictMode)
