### ISSUE TITLE
mediapipe build on macbook pro m1 does not work

### ISSUE THREAD

**Issue by galharth** [google/mediapipe#3178]
mediapipe build on macbook pro m1 does not work

<img width="964" alt="Screen Shot 2022-03-17 at 14 02 36" src="https://user-images.githubusercontent.com/564274/158804602-ad8a67d9-20df-4e8f-8418-27dec290507a.png">

**Comment by sureshdagooglecom** [comment]
Hi @galharth ,
did you get a chance to check [this](https://github.com/google/mediapipe/issues/1597) issue.
