### ISSUE TITLE
how to build helloworld

### ISSUE THREAD

**Issue by guojian186** [google/mediapipe#3180]
workspace(name = "mediapipe")
android_sdk_repository(name = "androidsdk", 
    path="D:/Android/studio_sdk",
    api_level = 23,     
    build_tools_version = "30.0.3")
android_ndk_repository(name = "androidndk",
   path="D:/Android/android-ndk-r21e") 

**Describe the problem**:
D:\out\mediapipe>bazel build -c opt   --config=android_arm --action_env PYTHON_BIN_PATH=C:/Users/ADMIN/AppData/Local/Programs/Python/Python37/python.exe //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build options --cpu, --crosstool_top, and --linkopt have changed, discarding analysis cache.
WARNING: D:/out/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: D:/out/mediapipe/mediapipe/framework/tool/BUILD:182:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld (0 packages loaded, 10807 targets configured).
INFO: Found 1 target...
INFO: From Linking mediapipe/graphs/edge_detection/mobile_gpu_binary_graph_text_to_binary_graph.exe [for host]:
  正在创建库 bazel-out\host\bin\mediapipe\graphs\edge_detection\mobile_gpu_binary_graph_text_to_binary_graph.lib 和对象 bazel-out\host\bin\mediapipe\graphs\edge_detection\mobile_gpu_binary_graph_text_to_binary_graph.exp
ERROR: D:/out/mediapipe/mediapipe/framework/formats/BUILD:90:24: Compiling mediapipe/framework/formats/time_series_header.pb.cc failed: (Exit 1): clang failed: error executing command external\androidndk\ndk\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -D__ANDROID_API__=30 -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target ... (remaining 61 arguments skipped)
clang: error: no such file or directory: '/w'
clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
clang: error: no such file or directory: '/std:c++17'
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 43.305s, Critical Path: 41.24s
INFO: 289 processes: 131 internal, 153 local, 5 worker.
FAILED: Build did NOT complete successfully

D:\out\mediapipe>

**Comment by YasserHawass** [comment]
not yet resolved ，
