### ISSUE TITLE
Mediapipe: Build did NOT complete successfully / Raspberry Pi 3b+ / Raspberry Debian Bullseye

### ISSUE THREAD

**Issue by tedbryantesoro** [google/mediapipe#3181]
**System information**
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Raspberry Debian Bullseye
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): GCC 10.2
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.9
- Installed using virtualenv? pip? Conda? (if python): virtualenv
- [MediaPipe version](https://github.com/google/mediapipe/releases): Latest Release (0.8.9.1)
- Bazel version: 4.2.2
- OpenCV version: 4.5.2

**Describe the problem**:
I am Using Raspberry Pi 3b+

I Have followed the instructions here:
https://google.github.io/mediapipe/getting_started/python.html
https://google.github.io/mediapipe/getting_started/python.html#building-mediapipe-python-package

For installing OpenCV:
can't install opencv-contrib via pip because it took 4 hours and still havent build yet and keeps going forever, so i used this link provided, 
https://singleboardbytes.com/647/install-opencv-raspberry-pi-4.htm

thanks for this other related issue  #3130 , Someone also assisted me doing in that handling this issue but yet failed so i created this seperate issue.

I'm at step 6 of the instruction here (https://google.github.io/mediapipe/getting_started/python.html)

Below are the output of my raspberry pi terminal

(sbb_cv) pi@raspberrypi:~/mediapipe $ python3 setup.py install --link-opencv
/home/pi/.virtualenvs/sbb_cv/lib/python3.9/site-packages/setuptools/dist.py:519: UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running install
/home/pi/.virtualenvs/sbb_cv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running build_binary_graphs
generating binarypb: mediapipe/modules/face_detection/face_detection_short_range_cpu
DEBUG: /home/pi/.cache/bazel/_bazel_pi/b64ded70520c15cba5314bb754a27c61/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/b64ded70520c15cba5314bb754a27c61/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/b64ded70520c15cba5314bb754a27c61/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/b64ded70520c15cba5314bb754a27c61/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/b64ded70520c15cba5314bb754a27c61/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/b64ded70520c15cba5314bb754a27c61/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/b64ded70520c15cba5314bb754a27c61/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/b64ded70520c15cba5314bb754a27c61/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/b64ded70520c15cba5314bb754a27c61/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/b64ded70520c15cba5314bb754a27c61/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/b64ded70520c15cba5314bb754a27c61/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
WARNING: /home/pi/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /home/pi/mediapipe/mediapipe/framework/tool/BUILD:182:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/modules/face_detection:face_detection_short_range_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/pi/mediapipe/mediapipe/calculators/util/BUILD:797:11: Compiling mediapipe/calculators/util/detection_projection_calculator.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 63 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./mediapipe/framework/packet.h:31,
                 from ./mediapipe/framework/graph_service_manager.h:8,
                 from ./mediapipe/framework/calculator_state.h:30,
                 from ./mediapipe/framework/calculator_context.h:23,
                 from ./mediapipe/framework/calculator_base.h:23,
                 from ./mediapipe/framework/calculator_framework.h:54,
                 from mediapipe/calculators/util/detection_projection_calculator.cc:21:
mediapipe/calculators/util/detection_projection_calculator.cc: In substitution of 'template<class _Functor, class, class> std::function<std::unique_ptr<mediapipe::internal::CalculatorBaseFactory>()>::function(_Functor) [with _Functor = <missing>; <template-parameter-1-2> = <missing>; <template-parameter-1-3> = <missing>]':
mediapipe/calculators/util/detection_projection_calculator.cc:58:1:   required from here
./mediapipe/framework/deps/registration.h:387:52: internal compiler error: Segmentation fault
  387 |           RegistryType::Register(#name, __VA_ARGS__))
      |                                                    ^
./mediapipe/framework/calculator_registry.h:24:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   24 |   REGISTER_FACTORY_FUNCTION_QUALIFIED(                                  \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mediapipe/calculators/util/detection_projection_calculator.cc:58:1: note: in expansion of macro 'REGISTER_CALCULATOR'
   58 | REGISTER_CALCULATOR(DetectionProjectionCalculator);
      | ^~~~~~~~~~~~~~~~~~~
0x76a57d9f ???
        ../sysdeps/unix/sysv/linux/arm/sigrestorer.S:64
0x76a3fbdf __libc_start_main
        ./csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
Target //mediapipe/modules/face_detection:face_detection_short_range_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 101.143s, Critical Path: 97.73s
INFO: 135 processes: 129 internal, 6 linux-sandbox.
**FAILED: Build did NOT complete successfully**

**Comment by sureshdagooglecom** [comment]
Hi @tedbryantesoro,
Could you provide steps to reproduce this issue.
