### ISSUE TITLE
Hands solution getting slower over time

### ISSUE THREAD

**Issue by Paolo-Sotorro** [google/mediapipe#3182]
- OS: Windows 10
- Version: 
        "@mediapipe/drawing_utils": "^0.3.1620248257",
         "@mediapipe/hands": "^0.4.1635986972",
- Solution: Hands
- Programming Language: js
- Browser: Electron 

I'm using hands solution in my desktop app and noticed that overtime the performance of the model drops significantly (it takes usually around 10minutes to see fps dropping from ~60 to 10). I've noticed that resetting the model bumps the fps back to 60 but then after some time it's starting to drop again.

This the only code I have regarding mediapipe:

```
export const getHands = () => {
  if (hands === null) {
    hands = new Hands({
      locateFile: (file) => {
        return `https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`;
      },
    });

    hands.onResults(onResults);
  }
  return hands;
};


const onResults = (results) => {
  let canvas: HTMLCanvasElement = document.querySelector('#canvas');
  let canvasCtx = canvas.getContext('2d');
  canvasCtx.save();
  canvasCtx.clearRect(0, 0, canvas.width, canvas.height);
  canvasCtx.drawImage(results.image, 0, 0, canvas.width, canvas.height);
  if (results.multiHandLandmarks) {
    let overlay: HTMLDivElement = document.querySelector('#overlay');
    let landmarks = results.multiHandLandmarks[0];
      try {
        drawConnectors(canvasCtx, landmarks, HAND_CONNECTIONS, {
          color: '#00FF00',
        });
        drawLandmarks(canvasCtx, landmarks, {
          color: '#00FF00',
          fillColor: '#FF0000',
          radius: (data) => {
            return lerp(data.from.z, -0.15, 0.1, 10, 1);
          },
        });
      } catch (e) {
        console.log('Drawing error', e);
      }
    landmarks = null;
    canvas = null;
    overlay = null;
  }
}
```

What could be the cause for this performance issue?

**Comment by sureshdagooglecom** [comment]
Hi @Paolo-Sotorro ,
Can you illustrate the above behavior with any reference. Thanks

**Comment by Paolo-Sotorro** [comment]
@sureshdagooglecom I don't exactly know what do you mean by 'with any reference', could you please guide me?

**Comment by sureshdagooglecom** [comment]
Could you share me any videos on this use case.

**Comment by Paolo-Sotorro** [comment]
Here's the video: https://drive.google.com/file/d/1XJu9GSK9m-9zlByq-CYEXqQg2jdgTEhW/view?usp=sharing
The hardware it's running on is R5800H, 16GB ram and RTX 3060.

**Comment by Paolo-Sotorro** [comment]
Here's the video: https://drive.google.com/file/d/109NNQTYQcD8gF9OQFjD5QtlQ-DKl0eep/view?usp=sharing
Hardware running the solution: R5800H, 16GB ram, RTX3060.

**Comment by sureshdagooglecom** [comment]
Did you get  a chance to check this issue https://github.com/google/mediapipe/issues/1627

**Comment by Paolo-Sotorro** [comment]
Yes I did but it didn't help me as electron is running chromium v. '98.0.4758.109'

**Comment by Paolo-Sotorro** [comment]
I have noticed also that the fps drop happens when the model detects an object:
![2022-03-22_08h18_23](https://user-images.githubusercontent.com/99659485/159428103-f1c3fbfb-3b6b-49ba-bcfe-cdfa5ce825e6.gif)
:

**Comment by alexriedel1** [comment]
Thats intentional as the model only infers hand keypoint if the palm detector detects a hand. The slowdown youre experiencing is the actual keypoint inference time.
