### ISSUE TITLE
how to build helloworld on Android Studio

### ISSUE THREAD

**Issue by cq186** [google/mediapipe#3183]
1.
workspace(name = "mediapipe")
android_sdk_repository(name = "androidsdk",
    path="D:/Android/studio_sdk",
    api_level = 23,
    build_tools_version = "30.0.3")
android_ndk_repository(name = "androidndk",
   path="D:/Android/android-ndk-r21e")

2.error
注意: 包含文件:          C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\xlocale
注意: 包含文件:           C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\xfacet
注意: 包含文件:           C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\xlocinfo
注意: 包含文件:            C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\xlocinfo.h
注意: 包含文件:             C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\cctype
注意: 包含文件:              C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\ctype.h
注意: 包含文件:             C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\clocale
注意: 包含文件:              C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\locale.h
注意: 包含文件:   C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\string
注意: 包含文件:   external/com_google_absl\absl/strings/ascii.h
注意: 包含文件:    external/com_google_absl\absl/strings/string_view.h
注意: 包含文件:     C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\cassert
注意: 包含文件:      C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\assert.h
注意: 包含文件:     external/com_google_absl\absl/base/internal/throw_delegate.h
注意: 包含文件:     C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\string_view
注意: 包含文件:   external/com_google_absl\absl/strings/internal/charconv_parse.h
ERROR: C:/users/admin/_bazel_admin/rgbff6kx/external/com_google_absl/absl/synchronization/BUILD.bazel:68:11: Compiling absl/synchronization/internal/waiter.cc failed: (Exit 1): clang failed: error executing command external\androidndk\ndk\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 -target ... (remaining 56 arguments skipped)
clang: error: no such file or directory: '/w'
clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
clang: error: no such file or directory: '/std:c++17'
ERROR: C:/users/admin/_bazel_admin/rgbff6kx/external/com_google_absl/absl/synchronization/BUILD.bazel:68:11: Compiling absl/synchronization/notification.cc failed: (Exit 1): clang failed: error executing command external\androidndk\ndk\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 -target ... (remaining 56 arguments skipped)
clang: error: no such file or directory: '/w'
clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
clang: error: no such file or directory: '/std:c++17'
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 473.379s, Critical Path: 257.79s
INFO: 1002 processes: 279 internal, 695 local, 28 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

![image](https://user-images.githubusercontent.com/6063018/159104688-3c2fe590-d167-4cc8-bc38-e5175fd8dc9d.png)

**Comment by wingdi** [comment]
Do you solve this problem? I encounter the same problem.

**Comment by guojian186** [comment]
not yet resolved ，

**Comment by wingdi** [comment]
The https://google.github.io/mediapipe/getting_started/install#installing-on-windows , Only can build desktop app, can't build Android app , reference https://github.com/google/mediapipe/issues/1287  , right ?   @jiuqiant

**Comment by sureshdagooglecom** [comment]
Could you please reproduce the above error with the latest release and let us know if the issue still exists. Thanks!
