### ISSUE TITLE
"Fail to read any frames from the video file"

### ISSUE THREAD

**Issue by yanxky** [google/mediapipe#3189]
I have read the question https://github.com/google/mediapipe/issues/2626 and I found that I‘m faced with the same situation with Victoria-1, but it seems that there isn't a solution in https://github.com/google/mediapipe/issues/2626 .
I can run the program with the input from my camera or single images, but when I run it with a video, it just return "[ WARN:0] Failed to set mediaType (stream 0, (0x0 @ 1) MFVideoFormat_RGB32(unsupported media type)
E20220322 14:06:07.629348 22252 simple_run_graph_main.cc:149] Failed to run the graph: CalculatorGraph::Run() failed in Run:
Calculator::Open() for node "OpenCvVideoDecoderCalculator" failed: ; Fail to read any frames from the video file at video/input.mp4".

**Comment by yanxky** [comment]
Environment: win10+opencv3.4.10+vs2019
I also run iris_depth_from_image_desktop successfully and get the output, and the input video and input images are from the same phone. 
As to using single image, I found that it is related to whether the image contains exif info or not. Does video have more requirements? I have tried to record videos with my computer, several phones and one professional camera, but all of these videos get the same result: "Fail to read any frames from the video file at video/input.mp4".

**Comment by peternaf** [comment]
Experiencing same issue with AutoFlip

**Comment by Kelach** [comment]
any luck perter?

**Comment by peternaf** [comment]
Unfortunately no

**Comment by Nakita-alive** [comment]
Try this command, turn the video to muted
ffmpeg -i video.mp4 -an -c copy no_sound.mp4
then use no_sound.mp4 to inference
works for me.

> I have read the question #2626 and I found that I‘m faced with the same situation with Victoria-1, but it seems that there isn't a solution in #2626 . I can run the program with the input from my camera or single images, but when I run it with a video, it just return "[ WARN:0] Failed to set mediaType (stream 0, (0x0 @ 1) MFVideoFormat_RGB32(unsupported media type) E20220322 14:06:07.629348 22252 simple_run_graph_main.cc:149] Failed to run the graph: CalculatorGraph::Run() failed in Run: Calculator::Open() for node "OpenCvVideoDecoderCalculator" failed: ; Fail to read any frames from the video file at video/input.mp4".
