### ISSUE TITLE
Specifying a person to track in a multi person video

### ISSUE THREAD

**Issue by db19891** [google/mediapipe#3190]
I am using human pose tracking in Python, Windows 11, with a video that contains multiple people. I would like to track the pose of the central person only, however it tracks alternate people to the side instead. How do I specify which person to track or alternatively view just the centre of a video? I would like to do this without cropping the video outside of my Program. My program is based off the provided Mediapipe Pose Python script for the webcam/video. Cheers.

**Comment by sureshdagooglecom** [comment]
Hi @db19891 ,
Could you provide any reference video w.r.t above issue.

**Comment by db19891** [comment]
![Pose track wrong person evidence](https://user-images.githubusercontent.com/60779115/159682417-f6f600a9-cacd-4118-95d2-c6b5307f1f96.png)

I couldn't get a video, but here is an image of my problem. I would like to track the powerlifter, not the spotter.

**Comment by sureshdagooglecom** [comment]
Model is not trained to select any specific person at present. We don’t have any video cropping calculator with which it can be built. we do consider it as a feature and share it with internal team.
