### ISSUE TITLE
Hair Segmentation Issue - ImageTransformationCalculator rotates automatically the output video

### ISSUE THREAD

**Issue by oscarlorente** [google/mediapipe#3192]
Hi, I'm using the Hair Segmentation solution (C++, Ubuntu 18.04, GPU enabled) and the results are great, but the output video is automatically rotated 90º. After removing all nodes from the .pbtxt file except the ImageTransformationCalculator (and another calculator I created to save the transformed image to an output video) the problem persists, so I guess it's related to the ImageTransformationCalculator. This is the node configuration:

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:input_video"
  output_stream: "IMAGE_GPU:transformed_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 512
      output_height: 512
    }
  }
}

I have tried with different input videos, and sometimes the output frames are rotated 90º clockwise and sometimes counterclockwise. Any help would be appreciated. Thanks

**Comment by sureshdagooglecom** [comment]
Hi @oscarlorente ,
Could you please share reference video w.r.t above use case.

**Comment by oscarlorente** [comment]
Sure, this is one of the videos used.

https://user-images.githubusercontent.com/42140425/159647292-bbdd33e1-3eac-415d-9a46-a5a7279c7b65.mp4

To build the solution I'm using:

bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hair_segmentation:hair_segmentation_gpu

And to run it:

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hair_segmentation/hair_segmentation_gpu --calculator_graph_config_file=mediapipe/graphs/hair_segmentation/hair_segmentation_desktop_live.pbtxt --input_video_path=input_video.mp4 --output_video_path=output_video.mp4

If I don't pass the "--input(output)_video_path" argument, the webcam is initialized and everything works fine, without any rotation.

**Comment by oscarlorente** [comment]
Hi @sureshdagooglecom any help please?

**Comment by sureshdagooglecom** [comment]
Hi @oscarlorente ,
Try to remove ImageTransformationCalculator, e.g. replace it with PassThroughCalculator that does nothing, there's a chance that something is with the original video or maybe how you save it.
