### ISSUE TITLE
Holistic Solution is throwing out of memory bounds issue in IOS 15.4

### ISSUE THREAD

**Issue by allanchua101** [google/mediapipe#3193]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution: iOS 15.4 (Safari, Chrome, Edge)
- Programming Language and version: JavaScript
- Installed using: NPM
- [MediaPipe version]:
```json
    "@mediapipe/camera_utils": "^0.3.1640029074",
    "@mediapipe/drawing_utils": "^0.3.1620248257",
    "@mediapipe/holistic": "^0.5.1635989137",
```

**Describe the problem**:

It seems that holistic solution is throwing an out of memory bounds issue on the latest ios version (ios 15.4)

**Complete Logs:**
Unhandled Promise Rejection: RuntimeError: Out of bounds memory access (evaluating 'invoker(fn, thisWired, arg0Wired)') promiseEmptyOnRejected promiseReactionJob

**Comment by sureshdagooglecom** [comment]
Hi @allanchua101 ,
Could you please go through this https://github.com/google/mediapipe/issues/2082#issuecomment-852470806.

**Comment by allanchua101** [comment]
Hi @sureshdagooglecom, thanks for replying! Do you have any guides on how to configure our JS-based solutions to use CPU instead of CPU?

**Comment by sureshdagooglecom** [comment]
Hi @allanchua101 ,
Please check [this](https://github.com/google/mediapipe/issues/3134) document for CPU.
