### ISSUE TITLE
Segmentation Fault with multiprocessing (num_workers>0)

### ISSUE THREAD

**Issue by mdv3101** [google/mediapipe#3194]
**System information** 

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): CentOS Linux release 7.9.2009, cuda10.2, cudnn7.6.5
- Programming Language and version ( e.g. C++, Python, Java): Python 3.7.1
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.7.1
- Solution ( e.g. FaceMesh, Pose, Holistic ): FaceMesh

**Describe the current behavior:**
I am using mediapipe to get face landmarks in a dataloader using PyTorch. The code works fine without multiprocessing. But when I increase the number of workers to 1(or more), the code crashes and shows segmentation fault. I have installed mediapipe using pip.

**Comment by sureshdagooglecom** [comment]
Hi @mdv3101 ,
did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/1720

**Comment by mdv3101** [comment]
Hi @sureshdagooglecom 
Yes, I checked that issue. Apparently, the error is not solved in that as well.

**Comment by mdv3101** [comment]
Hi @sureshdagooglecom Can provide any solution to this issue?

**Comment by mdv3101** [comment]
Hi @ivan-grishchenko ,
Can you look into this issue?

**Comment by kuaashish** [comment]
Hi @mdv3101,
Would you please let us know this is still an issue or has been resolved in the latest version `0.8.11 `? If issue persists could you share the complete steps to reproduce the same from our end.

**Comment by milely** [comment]
Hello, have you solved this problem? I use mediapipe in pytorch's Dataset, when the num_workers of Dataloader > 0, the program will get stuck.

**Comment by crj1998** [comment]
same issue here
