### ISSUE TITLE
anyway that I can download APK file for Objectron ? 

### ISSUE THREAD

**Issue by kotran88** [google/mediapipe#3195]
on mediapipe repository, there's only 3 example for hand tracking and face mesh that I can execute . 
but I'm looking for Objectron example, and looking for it but can't find it any. 
is it runnable on android device? 
 
if so, please let me know how to download example source or at least APK file to test it 

by seeing https://www.youtube.com/watch?v=AmFoxQ5aWAs
it seems there's example source or APK file at least...

**Comment by sureshdagooglecom** [comment]
Hi @kotran88 ,
Yes , we have objectron  for android ,check this [document](https://google.github.io/mediapipe/solutions/object_detection).

**Comment by ahmadyan** [comment]
You can either compile the APK from mediapipe, or you can get the pre-built APK from [this link](https://google.github.io/mediapipe/solutions/objectron.html#mobile)
