### ISSUE TITLE
Ground plane detection

### ISSUE THREAD

**Issue by jgrabes** [google/mediapipe#3196]
I'm just wondering if there's a way to configure any of the solutions in this library to detect a ground plane (i.e. an elevation level and a normal vector). I know there's an object detection solution, could this be applied to finding a ground plane?

I'm using python currently, so ideally any solution would be easily applied to the existing python approaches. Any advice would be greatly appreciated!

**Comment by sureshdagooglecom** [comment]
Hi @jgrabes ,
Could you please elaborate w.r.t to above issue.

**Comment by qingwufong** [comment]
Is there a way to detect ground position with pose detect model？We input picture generated by movement camera to mediapipe, In 3D scence avatar drived by landmark coordinate will float off the ground.
