### ISSUE TITLE
MLModel Support

### ISSUE THREAD

**Issue by lukasfolle** [google/mediapipe#3199]
Hi,

I really enjoy the ease of use of mediapipe on the desktop, now I would like to use mediapipe's hand detection tool in an iOS App.
I found the getting started for mediapipe in iOS Apps very confusing. I would rather like to use the plain detection model.

Previously, the conversion of tf or pytorch models was rather easy using the coreml tools (https://coremltools.readme.io/docs/mlmodel).
Would it be possible, to provide the trained models in pure `.h5` or `.pb`? This would make a conversion to Apples mlmodel substantially easier.

Best,
Lukas

**Comment by sureshdagooglecom** [comment]
Hi @lukasfolle ,
Did you get a chance to check this github [repo](https://github.com/google/mediapipe/tree/master/mediapipe/examples/ios).

**Comment by lukasfolle** [comment]
Hi,

Yes that’s was I was referring to in the first place.

**Comment by sureshdagooglecom** [comment]
Hi @lukasfolle ,
Could you share more information w.r.t above issue.

**Comment by lukasfolle** [comment]
I think I provided plenty of explanation on this. If you would like to get any specific info, please let me know what information you need.
But so far this is leading nowhere...

**Comment by sureshdagooglecom** [comment]
Hi @lukasfolle ,
MediaPipe team hasn't yet considered delivering the solution ML models separately.  MediaPipe team will remain focused on integrating the models with the solutions, and not delivering them separately.
