### ISSUE TITLE
Missing imports in handtrackinggpu in v0.6.6

### ISSUE THREAD

**Issue by ahmed-umair** [google/mediapipe#320]
Hi,

I was really excited to see that a mechanism was added to extract hand landmarks from the pipeline. 

However I'm unable to compile the included **handtrackinggpu** and **multihandtrackinggpu** Android applications via bazel due to some import statements whose targets are missing. Specifically in this
[file](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java) on line numbers 26 and 27, the two import statements fail because the packages being imported do not exist in `mediapipe/mediapipe/java/com/google/mediapipe/` in the repository.

Could someone please clarify if I'm doing something wrong here or is there something missing in the repository?

Thank you

**Comment by eknight7** [comment]
The imports should be generated by line `java_lite_proto_library...` (282) in https://github.com/google/mediapipe/blob/master/mediapipe/framework/formats/BUILD. Can you check your cloned repository has this ?
