### ISSUE TITLE
[face mesh] edit graph to enable visibility and presence feature

### ISSUE THREAD

**Issue by waleedForDeeplearning** [google/mediapipe#3200]
Hi, I'm using Mediapipe Facemesh python API. I'm using it to predict facial landmarks. Every landmark has a visibility and presence attribute that I want to make use of, as I don't want to print the landmark which has a visibility or presence value less than 0.5. As a default setting both the visibility and presence values are set to 0 for facemesh model. I've been following the issue #3159 but there has been no significant leads. 

What I've figured out is that the default binarypb graph doesn't have these values enabled. So we need to create a new binarypb graph with the required visibility and presence calculator nodes added. I've tried following this [https://medium.com/@mahakal001/end-to-end-project-example-in-mediapipe-b74a4a8ebb61](url) to create a dummy graph and learn how to build a graph from scratch. Here is what i learnt :

- We need to first create a "master BUILD" file with the graph and  calculator instructions. Which I believe is already present for the face mesh and we only need to edit that.
- Define a calculator.cc file in mediapipe/calculators/utils for all the calculation process and then register this calculator to the BUILD file in the calculators. Now the presence and visibility calculator should also be present in the calculators folder as it's already used in the [POSE] model and I've checked and made sure that the visibility values are indeed output in the pose model.
- Then we need to write the graph flow file (graph.pbtxt) in mediapipe/graphs/ to write the flow of the model and then add a BUILD file. Now mediapipe/facemesh/graphs folder has already some graphs.pbtxt files available so by my guess we need to modify one of these graph files or one of the subgraph files in the mediapipe/graphs/subgraphs  to let the model know that we want to calculate the visibility and presence calculators in the pipeline graph and get the values. 

After this then we need to build the binary graph file using bazel-build command. And then run inference on it. These are the steps I'm trying to follow but I'm not sure what calculators to add and which of these files do I need to edit. I've tried comparing the graph files with the [pose] model graphs but they're quite different. Though the pose_tracking/subgraph/pose_renderer_cpu.pbtxt has the visibility values like these:
![pose renderer](https://user-images.githubusercontent.com/102373022/160153782-d156ab29-53aa-4715-b1db-aa00970d69d4.png)

Can you guide me what files in the face mesh do I need to edit? It would be immensely helpful if i can get a some leads. And also let me know if my findings have some discrepancies in them. Because I believe that once we have the new binary graph file, we can run inference on it using the API and the visibility and presence values would be present in the resulting landmarks.

**Comment by sureshdagooglecom** [comment]
@waleedForDeeplearning ,
Could you provide steps to reproduce this issue.

**Comment by waleedForDeeplearning** [comment]
> Collaborator

I've followed instructions page https://google.github.io/mediapipe/getting_started/install.html to install the repository. Then I've edited the subgraph file in the graphs/facemesh/sugraphs/face_renderer_cpu.pbtxt to include the visibility flag in the graph nodes like pose estimation. So the new code looks like this:
```
# MediaPipe face mesh rendering subgraph.

type: "FaceRendererCpu"

# CPU image. (ImageFrame)
input_stream: "IMAGE:input_image"
# Collection of detected/predicted faces, each represented as a list of
# landmarks. (std::vector<NormalizedLandmarkList>)
input_stream: "LANDMARKS:multi_face_landmarks"
# Regions of interest calculated based on palm detections.
# (std::vector<NormalizedRect>)
input_stream: "NORM_RECTS:rects"
# Detected palms. (std::vector<Detection>)
input_stream: "DETECTIONS:detections"

# CPU image with rendered data. (ImageFrame)
output_stream: "IMAGE:output_image"

node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE:input_image"
  output_stream: "SIZE:image_size"
}

# Converts detections to drawing primitives for annotation overlay.
node {
  calculator: "DetectionsToRenderDataCalculator"
  input_stream: "DETECTIONS:detections"
  output_stream: "RENDER_DATA:detections_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.DetectionsToRenderDataCalculatorOptions] {
      thickness: 4.0
      color { r: 0 g: 255 b: 0 }
    }
  }
}

# Outputs each element of multi_face_landmarks at a fake timestamp for the rest
# of the graph to process. At the end of the loop, outputs the BATCH_END
# timestamp for downstream calculators to inform them that all elements in the
# vector have been processed.
node {
  calculator: "BeginLoopNormalizedLandmarkListVectorCalculator"
  input_stream: "ITERABLE:multi_face_landmarks"
  output_stream: "ITEM:face_landmarks"
  output_stream: "BATCH_END:landmark_timestamp"
}

# Converts landmarks to drawing primitives for annotation overlay.
node {
  calculator: "FaceLandmarksToRenderDataCalculator"
  input_stream: "NORM_LANDMARKS:face_landmarks"
  output_stream: "RENDER_DATA:landmarks_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.LandmarksToRenderDataCalculatorOptions] {
      landmark_color { r: 255 g: 0 b: 0 }
      connection_color { r: 0 g: 255 b: 0 }
      thickness: 2
      visualize_landmark_depth: false
    }
  }
}

# Collects a RenderData object for each hand into a vector. Upon receiving the
# BATCH_END timestamp, outputs the vector of RenderData at the BATCH_END
# timestamp.
node {
  calculator: "EndLoopRenderDataCalculator"
  input_stream: "ITEM:landmarks_render_data"
  input_stream: "BATCH_END:landmark_timestamp"
  output_stream: "ITERABLE:multi_face_landmarks_render_data"
}

# Converts normalized rects to drawing primitives for annotation overlay.
node {
  calculator: "RectToRenderDataCalculator"
  input_stream: "NORM_RECTS:rects"
  output_stream: "RENDER_DATA:rects_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.RectToRenderDataCalculatorOptions] {
      filled: false
      color { r: 255 g: 0 b: 0 }
      thickness: 4.0
      
      ##-------------------------------------------------------
      ##Edited node
      utilize_visibility: true
      visibility_threshold: 0.5
    }
  }
}

# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE:input_image"
  input_stream: "detections_render_data"
  input_stream: "VECTOR:0:multi_face_landmarks_render_data"
  input_stream: "rects_render_data"
  output_stream: "IMAGE:output_image"
}
```
But when i build the graph again with the node the build fails.

**Comment by jimb2834** [comment]
@ivan-grishchenko - Were you able to see any proposed solution for these two values to present in the response?

**Comment by jimb2834** [comment]
@sureshdagooglecom - Thank you for reopening this. Is there any timeline for a possible internal review on this topic?

**Comment by elYeodeol** [comment]
Hey, i'm trying to modify to modify the pose tracking solutions graphs! i cannot also manage this. I modified what i wanted and edit BUILD files ect, but it never works... do you have any tips to modify graphs?

**Comment by ayushgdev** [comment]
@waleedForDeeplearning We are revisiting older issues. 
For face mesh, the models (both with and without attention) don't output any visibility or presence scores. Check the [model card](https://drive.google.com/file/d/1QvwWNfFoweGVjsXF3DXzcrCnz-mx-Lha/preview) or see the TfLite output below:
<img width="927" alt="Screenshot 2023-04-19 at 3 28 51 PM" src="https://user-images.githubusercontent.com/118424249/233040083-86d8ab09-6121-441a-94d8-de350401a0b6.png">



However, since the Python API has `NormalizedLandmarkList` as the datatype for output of `FaceMesh` class' `process()` (results.multi_face_landmarks), the output _**has**_ to have presence and visibility scores. Thus, in the C++ code itself, the visibility and presence scores are set to 0 by default (see [here](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tensor/tensors_to_landmarks_calculator.cc#L184)). This calculator is used in [tensors_to_face_landmarks.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/tensors_to_face_landmarks.pbtxt).
Hence, enabling visibility/presence in face mesh is not possible.
