### ISSUE TITLE
Number of face mesh landmarks

### ISSUE THREAD

**Issue by EverLookNeverSee** [google/mediapipe#3201]
Hi there
I am going to implement a face availability check function in order to detect only direct gaze faces in given frames and to do so i intend to use mediapipe face mesh landmarks.
Is there a way to calculate number of landmarks for a sample detected face?

**Comment by sureshdagooglecom** [comment]
Hi @EverLookNeverSee ,
You can capture the "face_detections" stream from the graph, in a similar way as the "hand_landmarks" from [here](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L49) , through 'addPacketCallback'.
See the [detections to render data calculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/detections_to_render_data_calculator.cc) (used in the face detection graph) on how to interpret the "face_detections" data

**Comment by EverLookNeverSee** [comment]
Thanks @sureshdagooglecom

**Comment by lorenzodifuccia** [comment]
Hi @EverLookNeverSee, have you developed the "direct gaze" program?
I'm interested in the same functionality: detect number of faces who gaze to a specific frame (like, computer screen)
