### ISSUE TITLE
MediaPipe Pose - add training data to the model?

### ISSUE THREAD

**Issue by tomerlevi444** [google/mediapipe#3202]
Is it possible to add training data to MediaPipe Pose, so it better recognizes irregular poses?

**Comment by sureshdagooglecom** [comment]
Hi @tomerlevi444 ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/1824

**Comment by Cleoxx** [comment]
Hey, in case you're still interested, check out #3410 , #2761 and #507. I have been looking for an answer on this as well and found these threads quite helpful.

**Comment by sureshdagooglecom** [comment]
Hi @tomerlevi444 ,
For python you can create your own graph using the calculators and execute as mentioned here https://google.github.io/mediapipe/getting_started/python_framework.html#graph.
Have you looked at these closed issues https://github.com/google/mediapipe/issues/2761 and https://github.com/google/mediapipe/issues/507.
Thank you!

**Comment by csn1800** [comment]
Hi @tomerlevi444, I assume you intended make the existing Mediapipe model learn from your data (transfer learning) than training a model from scratch. Hope you found a solution to the problem you mentioned. 

Were you able to use the Mediapipe model and make it learn from your own dataset? I am having a similar requirement and unable to find a solution.

**Comment by il-nietos** [comment]
Hi @tomerlevi444 and @csn1800 did either of you have any success with transfer learning with Mediapipe? I'm trying to find if this is possible myself.

**Comment by csn1800** [comment]
@il-nietos I have not given much time for transfer learning later on, however, it seems that PINTO mode zoo maybe of help to you.

For eg, you may use https://github.com/PINTO0309/PINTO_model_zoo/tree/main/053_BlazePose, download the resources and try using the saved model to enhance and/or modify the model further. I have not tried it on my own, so not sure how efficient the models can be on resource constrained platforms.

**Comment by zaidworks515** [comment]
I want to use Mediapipe Solution (POSE) for animal pose estimation. I have the raw data of cow pictures, how to make that data compatible to be trained with Mediapipe Solution?
