### ISSUE TITLE
MediaPipe Pose - get a confidence graph for joints?

### ISSUE THREAD

**Issue by tomerlevi444** [google/mediapipe#3203]
Is it possible to get the confidence map for each of the 33 detected joints? Currently, AFAIK the joint estimation returns only the most-likely pixel, but there are (not uncommon) cases when there are a few detections with more-or-less the same probability.

Exposing the confidence map helps to better decide the actual position of the joint, for example, in the case when the user is expected to perform a specific movement that is to be tracked.

**Comment by sureshdagooglecom** [comment]
Hi @tomerlevi444 ,
We don't support confidence score in python since we have limited support.

**Comment by tomerlevi444** [comment]
Is the confidence score available for iOS or any other platform?

**Comment by sureshdagooglecom** [comment]
Hi @tomerlevi444 ,
We don't support confidence score in IOS also.
