### ISSUE TITLE
How to build framework for ios  in my App

### ISSUE THREAD

**Issue by yangyuanwei** [google/mediapipe#3205]
How to build a framework package that can be used on IOS, such as .Framework / .a

**Comment by sureshdagooglecom** [comment]
Hi @yangyuanwei ,
Could you please elaborate this issue.

**Comment by yangyuanwei** [comment]
> Hi @yangyuanwei , Could you please elaborate this issue.

for example I want to user mediapipe  for my ios . I want to Build Face Mesh module to  ios framework  do some customize. so I can use for another xcode project. 

in this tutorial :https://google.github.io/mediapipe/getting_started/ios.html 。There is no tutorial to help us build into the iOS SDK, just examples to build mediapipe/examples/ iOS.

I can't debug code with Xcode。

**Comment by sureshdagooglecom** [comment]
Hi @yangyuanwei ,
Please check this official [document](https://google.github.io/mediapipe/solutions/face_mesh.html) for your reference.
