### ISSUE TITLE
Facemesh model conversion to onnx

### ISSUE THREAD

**Issue by pytholic** [google/mediapipe#3206]
Hi. Thank you for the good work and the accurate models!

I am trying to convert the facial landmark `tflite` model to `onnx` format to use it in Unity3D using Onnxruntime.

However, during the conversion, I see some errors. After the conversion, when I load the model in Unity3D using C#, I get the Op not supported error again. I have attached the error images.

I have tried different opsets as well.

Thank you!

![conversion_error](https://user-images.githubusercontent.com/60126503/160353265-97aadafd-4bca-4e00-89c2-87f9e8f683db.JPG)
![unity_onnxruntime_error](https://user-images.githubusercontent.com/60126503/160353281-a9254798-6715-4417-8e2d-9638559802e1.JPG)

**Comment by sureshdagooglecom** [comment]
Hi @pytholic ,
Could you please provide steps to reproduce this issue.

**Comment by pytholic** [comment]
> Hi @pytholic , Could you please provide steps to reproduce this issue.

Hi sure.

1) Downloaded the model from [link](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark.tflite)

2) Used [tf2onnx](https://github.com/onnx/tensorflow-onnx) for conversion with following command:
```
python -m tf2onnx.convert --tflite ./model.tflite --output model.onnx
```

then you get the attached conversion process along with the unsupported operation errors.

**Comment by sureshdagooglecom** [comment]
Hi @pytholic ,
Mediapipe team doesn't recommend or support converting models from TFLite.
