### ISSUE TITLE
Issues with reliability / accuracy in dark rooms (low-light)

### ISSUE THREAD

**Issue by jsegeren** [google/mediapipe#3208]
Issues with reliability / accuracy in dark rooms (low-light)
Not surprisingly, we see that hand detection + tracking performance (both reliability - does it detect at all - and accuracy - does it track correctly) degrades significantly in a dark room / low lighting. (We also see some similar but opposite cases, i.e. bright lighting and light skin. i.e. Adverse environment lighting in general.)  

We want to explore techniques that might help "squeeze out" better perf in these conditions. E.g. Image pre-processing - histogram equalization, or perhaps something else. Do you have any specific recommendations/guidance for us? Or perhaps there is more planned effort on your side to improve the out-of-box performance here?

Thank you for your help!

**Comment by sureshdagooglecom** [comment]
Hi @jsegeren ,
Could you share any reference videos or images w.r.t above issue.

**Comment by sureshdagooglecom** [comment]
Hi @jsegeren ,
Could you please share any reference videos as discusses above.
