### ISSUE TITLE
bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world is wrong

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#3209]
bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world --sandbox_debug

How can I fix this mistake? ( Ubuntu)

wrong:
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "fd225c89de0e7400a9a570feaf631a19dd1f1e57cb7b2f9308be4657a2fdf00c"
DEBUG: Repository rules_cc instantiated at:
  /home/alg/ai/mediapipe/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31: in <toplevel>
WARNING: /home/alg/ai/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /home/alg/ai/mediapipe/mediapipe/framework/tool/BUILD:184:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/alg/ai/mediapipe/mediapipe/framework/BUILD:735:11: Compiling mediapipe/framework/output_side_packet_impl.cc failed: (Exit 1): linux-sandbox failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/sandbox/linux-sandbox/624/execroot/mediapipe && \
  exec env - \
    LD_LIBRARY_PATH=:/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64 \
    PATH=/root/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin:/root/bin:/root/bin:/usr/local/cuda/bin:/root/bin:/usr/local/cuda/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/c87283ec3a7822eea44f4cecb6db792e/linux-sandbox -t 15 -w /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/sandbox/linux-sandbox/624/execroot/mediapipe -w /tmp -w /dev/shm -D -- /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/mediapipe/framework/_objs/output_side_packet_impl/output_side_packet_impl.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/mediapipe/framework/_objs/output_side_packet_impl/output_side_packet_impl.pic.o' -fPIC '-DMEDIAPIPE_DISABLE_GPU=1' -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/com_google_absl -iquote bazel-out/k8-fastbuild/bin/external/com_google_absl -iquote external/com_github_glog_glog -iquote bazel-out/k8-fastbuild/bin/external/com_github_glog_glog -iquote external/com_github_gflags_gflags -iquote bazel-out/k8-fastbuild/bin/external/com_github_gflags_gflags -iquote external/com_google_protobuf -iquote bazel-out/k8-fastbuild/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-fastbuild/bin/external/zlib -Ibazel-out/k8-fastbuild/bin/external/com_github_glog_glog/_virtual_includes/default_glog_headers -Ibazel-out/k8-fastbuild/bin/external/com_github_gflags_gflags/_virtual_includes/gflags -isystem external/com_google_protobuf/src -isystem bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/k8-fastbuild/bin/external/zlib -w '-std=c++17' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c mediapipe/framework/output_side_packet_impl.cc -o bazel-out/k8-fastbuild/bin/mediapipe/framework/_objs/output_side_packet_impl/output_side_packet_impl.pic.o)
1648550181.499545015: src/main/tools/linux-sandbox.cc:152: calling pipe(2)...
1648550181.499571786: src/main/tools/linux-sandbox.cc:171: calling clone(2)...
1648550181.499735927: src/main/tools/linux-sandbox.cc:180: linux-sandbox-pid1 has PID 413974
1648550181.499760801: src/main/tools/linux-sandbox-pid1.cc:641: Pid1Main started
1648550181.499799723: src/main/tools/linux-sandbox.cc:197: done manipulating pipes
1648550181.499892613: src/main/tools/linux-sandbox-pid1.cc:260: working dir: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/sandbox/linux-sandbox/624/execroot/mediapipe
1648550181.499904816: src/main/tools/linux-sandbox-pid1.cc:292: writable: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/sandbox/linux-sandbox/624/execroot/mediapipe
1648550181.499908478: src/main/tools/linux-sandbox-pid1.cc:292: writable: /tmp
1648550181.499912969: src/main/tools/linux-sandbox-pid1.cc:292: writable: /dev/shm
1648550181.499948377: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /
1648550181.499953159: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev
1648550181.499955887: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/pts
1648550181.499958627: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /dev/shm
1648550181.499961354: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/mqueue
1648550181.499963726: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/hugepages
1648550181.499966492: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run
1648550181.499968741: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/lock
1648550181.499971474: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/1000
1648550181.499974401: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/1000/gvfs
1648550181.499976387: src/main/tools/linux-sandbox-pid1.cc:382: remount(nullptr, /run/user/1000/gvfs, nullptr, 2101287, nullptr) failure (Permission denied) ignored
1648550181.499983131: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/1000/doc
1648550181.499984873: src/main/tools/linux-sandbox-pid1.cc:382: remount(nullptr, /run/user/1000/doc, nullptr, 2101287, nullptr) failure (Permission denied) ignored
1648550181.499986807: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/snapd/ns
1648550181.500005100: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys
1648550181.500007745: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/security
1648550181.500011760: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup
1648550181.500014872: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/unified
1648550181.500017750: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/systemd
1648550181.500020474: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/rdma
1648550181.500023300: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/memory
1648550181.500025924: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/pids
1648550181.500028521: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/perf_event
1648550181.500031310: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/devices
1648550181.500033980: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/net_cls,net_prio
1648550181.500036845: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/hugetlb
1648550181.500056425: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/cpuset
1648550181.500059783: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/cpu,cpuacct
1648550181.500062354: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/freezer
1648550181.500064776: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/blkio
1648550181.500067326: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/pstore
1648550181.500070718: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/firmware/efi/efivars
1648550181.500074407: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/bpf
1648550181.500082742: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/debug
1648550181.500085993: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/tracing
1648550181.500088998: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/fuse/connections
1648550181.500092445: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/config
1648550181.500095110: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc
1648550181.500097837: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc/sys/fs/binfmt_misc
1648550181.500103253: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /boot
1648550181.500117817: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /boot/efi
1648550181.500120942: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /var
1648550181.500123126: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /home
1648550181.500125496: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /tmp
1648550181.500128197: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /tmp/.mount_panda5uk3S1T
1648550181.500130749: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core18/2344
1648550181.500133360: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core20/1361
1648550181.500135937: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core20/1376
1648550181.500138123: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/bare/5
1648550181.500140472: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core18/2284
1648550181.500142678: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-3-34-1804/66
1648550181.500145341: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-3-34-1804/77
1648550181.500147921: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gtk-common-themes/1519
1648550181.500150192: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gtk-common-themes/1514
1648550181.500160551: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/snap-store/518
1648550181.500163421: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-3-38-2004/99
1648550181.500166114: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/snapd/15177
1648550181.500168544: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/snapd/14978
1648550181.500170925: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/snap-store/558
1648550181.500173279: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/firefox/1154
1648550181.500176247: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/sandbox/linux-sandbox/624/execroot/mediapipe
1648550181.500179689: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/sandbox/linux-sandbox/624/execroot/mediapipe
1648550181.500182097: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /tmp
1648550181.500184567: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /tmp/.mount_panda5uk3S1T
1648550181.500187050: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /dev/shm
1648550181.500219719: src/main/tools/linux-sandbox-pid1.cc:451: calling fork...
1648550181.500292286: src/main/tools/linux-sandbox-pid1.cc:481: child started with PID 2
cc1plus: fatal error: mediapipe/framework/output_side_packet_impl.cc: Permission denied
compilation terminated.
1648550181.502936909: src/main/tools/linux-sandbox-pid1.cc:498: wait returned pid=2, status=0x100
1648550181.502944349: src/main/tools/linux-sandbox-pid1.cc:516: child exited normally with code 1
1648550181.503202768: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
ERROR: /home/alg/ai/mediapipe/mediapipe/framework/BUILD:620:11: Compiling mediapipe/framework/input_side_packet_handler.cc failed: (Exit 1): linux-sandbox failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/sandbox/linux-sandbox/625/execroot/mediapipe && \
  exec env - \
    LD_LIBRARY_PATH=:/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64 \
    PATH=/root/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-x86_64/bin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin:/root/bin:/root/bin:/usr/local/cuda/bin:/root/bin:/usr/local/cuda/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/c87283ec3a7822eea44f4cecb6db792e/linux-sandbox -t 15 -w /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/sandbox/linux-sandbox/625/execroot/mediapipe -w /tmp -w /dev/shm -D -- /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/mediapipe/framework/_objs/input_side_packet_handler/input_side_packet_handler.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/mediapipe/framework/_objs/input_side_packet_handler/input_side_packet_handler.pic.o' -fPIC '-DMEDIAPIPE_DISABLE_GPU=1' -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/com_google_absl -iquote bazel-out/k8-fastbuild/bin/external/com_google_absl -iquote external/com_github_glog_glog -iquote bazel-out/k8-fastbuild/bin/external/com_github_glog_glog -iquote external/com_github_gflags_gflags -iquote bazel-out/k8-fastbuild/bin/external/com_github_gflags_gflags -iquote external/com_google_protobuf -iquote bazel-out/k8-fastbuild/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-fastbuild/bin/external/zlib -Ibazel-out/k8-fastbuild/bin/external/com_github_glog_glog/_virtual_includes/default_glog_headers -Ibazel-out/k8-fastbuild/bin/external/com_github_gflags_gflags/_virtual_includes/gflags -isystem external/com_google_protobuf/src -isystem bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/k8-fastbuild/bin/external/zlib -w '-std=c++17' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c mediapipe/framework/input_side_packet_handler.cc -o bazel-out/k8-fastbuild/bin/mediapipe/framework/_objs/input_side_packet_handler/input_side_packet_handler.pic.o)
1648550181.503701730: src/main/tools/linux-sandbox.cc:152: calling pipe(2)...
1648550181.503729500: src/main/tools/linux-sandbox.cc:171: calling clone(2)...
1648550181.503908848: src/main/tools/linux-sandbox.cc:180: linux-sandbox-pid1 has PID 413978
1648550181.504626406: src/main/tools/linux-sandbox-pid1.cc:641: Pid1Main started
1648550181.504688973: src/main/tools/linux-sandbox.cc:197: done manipulating pipes
1648550181.504772996: src/main/tools/linux-sandbox-pid1.cc:260: working dir: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/sandbox/linux-sandbox/625/execroot/mediapipe
1648550181.504788325: src/main/tools/linux-sandbox-pid1.cc:292: writable: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/sandbox/linux-sandbox/625/execroot/mediapipe
1648550181.504792402: src/main/tools/linux-sandbox-pid1.cc:292: writable: /tmp
1648550181.504797270: src/main/tools/linux-sandbox-pid1.cc:292: writable: /dev/shm
1648550181.504839420: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /
1648550181.504844372: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev
1648550181.504847096: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/pts
1648550181.504849898: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /dev/shm
1648550181.504852568: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/mqueue
1648550181.504855099: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/hugepages
1648550181.504857786: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run
1648550181.504860295: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/lock
1648550181.504863260: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/1000
1648550181.504866145: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/1000/gvfs
1648550181.504868485: src/main/tools/linux-sandbox-pid1.cc:382: remount(nullptr, /run/user/1000/gvfs, nullptr, 2101287, nullptr) failure (Permission denied) ignored
1648550181.504877960: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/1000/doc
1648550181.504879594: src/main/tools/linux-sandbox-pid1.cc:382: remount(nullptr, /run/user/1000/doc, nullptr, 2101287, nullptr) failure (Permission denied) ignored
1648550181.504881744: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/snapd/ns
1648550181.504902500: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys
1648550181.504905337: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/security
1648550181.504910391: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup
1648550181.504913744: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/unified
1648550181.504916681: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/systemd
1648550181.504919340: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/rdma
1648550181.504921930: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/memory
1648550181.504924645: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/pids
1648550181.504927301: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/perf_event
1648550181.504930033: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/devices
1648550181.504932566: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/net_cls,net_prio
1648550181.504935748: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/hugetlb
1648550181.504957708: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/cpuset
1648550181.504960720: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/cpu,cpuacct
1648550181.504963778: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/freezer
1648550181.504966258: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/blkio
1648550181.504968832: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/pstore
1648550181.504971431: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/firmware/efi/efivars
1648550181.504975001: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/bpf
1648550181.504985192: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/debug
1648550181.504988649: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/tracing
1648550181.504991356: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/fuse/connections
1648550181.504994596: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/config
1648550181.504997262: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc
1648550181.504999912: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc/sys/fs/binfmt_misc
1648550181.505004536: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /boot
1648550181.505019908: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /boot/efi
1648550181.505022951: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /var
1648550181.505025122: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /home
1648550181.505027421: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /tmp
1648550181.505030307: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /tmp/.mount_panda5uk3S1T
1648550181.505032840: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core18/2344
1648550181.505035827: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core20/1361
1648550181.505038161: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core20/1376
1648550181.505040471: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/bare/5
1648550181.505042844: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core18/2284
1648550181.505045196: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-3-34-1804/66
1648550181.505048281: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-3-34-1804/77
1648550181.505051156: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gtk-common-themes/1519
1648550181.505053836: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gtk-common-themes/1514
1648550181.505063618: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/snap-store/518
1648550181.505066391: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-3-38-2004/99
1648550181.505068939: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/snapd/15177
1648550181.505071292: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/snapd/14978
1648550181.505073583: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/snap-store/558
1648550181.505075912: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/firefox/1154
1648550181.505079046: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/sandbox/linux-sandbox/625/execroot/mediapipe
1648550181.505082350: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/sandbox/linux-sandbox/625/execroot/mediapipe
1648550181.505084728: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /tmp
1648550181.505087416: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /tmp/.mount_panda5uk3S1T
1648550181.505089805: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /dev/shm
1648550181.505127685: src/main/tools/linux-sandbox-pid1.cc:451: calling fork...
1648550181.505228860: src/main/tools/linux-sandbox-pid1.cc:481: child started with PID 2
cc1plus: fatal error: mediapipe/framework/input_side_packet_handler.cc: Permission denied
compilation terminated.
1648550181.522207412: src/main/tools/linux-sandbox-pid1.cc:498: wait returned pid=2, status=0x100
1648550181.522219911: src/main/tools/linux-sandbox-pid1.cc:516: child exited normally with code 1
1648550181.526218326: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
INFO: Elapsed time: 1.126s, Critical Path: 0.05s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by LMR2018** [comment]
cc1plus: fatal error: mediapipe/framework/input_side_packet_handler.cc: Permission denied

**Comment by sureshdagooglecom** [comment]
Hi @LMR2018 ,
Due to a recent change on the Bazel side, "rules_foreign_cc" is not available anymore. The solution is to switch to use Bazel 3.4+. I verified the fix in the Docker container. See details at https://github.com/google/mediapipe/issues/1175#issuecomment-704524129. MediaPipe will have a new version out this week to ask users to at least have Bazel 3.4+.
