### ISSUE TITLE
ERROR:  Compiling mediapipe/framework/deps/file_path.cc failed: (Exit 1): linux-sandbox failed: error executing command

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#3210]
ERROR: /home/alg/ai/mediapipe/mediapipe/framework/deps/BUILD:98:11: Compiling mediapipe/framework/deps/file_path.cc failed: (Exit 1): linux-sandbox failed: error executing command

**Comment by sureshdagooglecom** [comment]
Hi @LMR2018 ,
Could you please share more information to reproduce the issue.

**Comment by LMR2018** [comment]
> 嗨@LMR2018， 您能否分享更多信息以重现该问题。

@sureshdagooglecom   bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

root@alg-ubuntu:/home/alg/ai/mediapipe# sudo bazel run --define MEDIAPIPE_DISABLE_GPU=1  mediapipe/examples/desktop/hello_world:hello_world
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
WARNING: /home/alg/ai/mediapipe/mediapipe/framework/tool/BUILD:184:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /home/alg/ai/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
INFO: From Compiling src/google/protobuf/message_lite.cc:
In file included from /usr/include/string.h:519,
                 from external/com_google_protobuf/src/google/protobuf/stubs/port.h:39,
                 from external/com_google_protobuf/src/google/protobuf/stubs/common.h:48,
                 from external/com_google_protobuf/src/google/protobuf/message_lite.h:45,
                 from external/com_google_protobuf/src/google/protobuf/message_lite.cc:36:
In function 'void* memcpy(void*, const void*, size_t)',
    inlined from 'uint8_t* google::protobuf::io::EpsCopyOutputStream::WriteRaw(const void*, int, uint8_t*)' at external/com_google_protobuf/src/google/protobuf/io/coded_stream.h:706:16,
    inlined from 'virtual uint8_t* google::protobuf::internal::ImplicitWeakMessage::_InternalSerialize(uint8_t*, google::protobuf::io::EpsCopyOutputStream*) const' at external/com_google_protobuf/src/google/protobuf/implicit_weak_message.h:84:28,
    inlined from 'bool google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const' at external/com_google_protobuf/src/google/protobuf/message_lite.cc:412:30:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33: warning: 'void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)' specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: /home/alg/ai/mediapipe/mediapipe/framework/deps/BUILD:98:11: Compiling mediapipe/framework/deps/file_path.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 22 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
cc1plus: fatal error: mediapipe/framework/deps/file_path.cc: Permission denied
compilation terminated.
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 100.546s, Critical Path: 82.45s
INFO: 316 processes: 131 internal, 185 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by Tongbook** [comment]
I have a problem of my own， My configuration  virtual machine ubuntu20.04 + bazel5.2.0 + opencv3.4.15 + ffmpeg N-108018-g2ed5925e26

**Comment by ayushgdev** [comment]
@LMR2018 Could you please elaborate your query using the new issue template [here](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=00-build-installation-issue.md)? This allows us to better understand your query in one go and answer accordingly.
