### ISSUE TITLE
http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#3211]
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2f6de37d68a4c69e2ff9eec3cebbf1369e496940.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

**Comment by LMR2018** [comment]
bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

**Comment by ShmulikHass** [comment]
I have  exactly same issue on clean build for Tensorflow C++ using CUDA 1.6 and Bazek 3.7.2 ( or latest, same )

Any solution ?

**Comment by beroso** [comment]
It worked for me after installation of required dependencies.

```console
 brew install opencv@3
 # There is a known issue caused by the glog dependency. Uninstall glog.
 brew uninstall --ignore-dependencies glog
 pip3 install --user six
```

More details can be found in https://google.github.io/mediapipe/getting_started/install.html

**Comment by sureshdagooglecom** [comment]
Hi @LMR2018 ,
Make sure that Python 3 and the Python “six” library are installed by executing below commands.
$ brew install python
$ sudo ln -s -f /usr/local/bin/python3.7 /usr/local/bin/python
$ python --version
Python 3.7.4
$ pip3 install --user six

**Comment by schnitzlein** [comment]
> bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

brings me to:

`root@picam-03:/usr/local/src/mediapipe# bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  /usr/local/src/mediapipe/WORKSPACE:47:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/dcc55e3eb2ef4c80ac4b81dec4ac8dda/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /root/.cache/bazel/_bazel_root/dcc55e3eb2ef4c80ac4b81dec4ac8dda/external/build_bazel_apple_support/crosstool/setup.bzl:69:32: name 'module_extension' is not defined
ERROR: error loading package '': in /root/.cache/bazel/_bazel_root/dcc55e3eb2ef4c80ac4b81dec4ac8dda/external/build_bazel_rules_swift/swift/extras.bzl: in /root/.cache/bazel/_bazel_root/dcc55e3eb2ef4c80ac4b81dec4ac8dda/external/build_bazel_apple_support/lib/repositories.bzl: Extension 'crosstool/setup.bzl' has errors
INFO: Elapsed time: 0,449s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)`

**Comment by schnitzlein** [comment]
I m running and compile under POSIX aka Linux ... with a Raspbian 11 Bulleye.
This is also ARM but not a iOS with OS X or any brew.

Strange but the Architecture is: aarch64
but the CPU is: ARM with Cortex-A72

reproduceable to check with command:
lscpu

or go with: cat /proc/cpuinfo
or go with: cat /etc/os-release


This is the issue, not iOS with arm.
