### ISSUE TITLE
Error in android_sdk_repository: Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'androidsdk')

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#3212]
ERROR: Traceback (most recent call last):
	File "/home/alg/ai/mediapipe/WORKSPACE", line 418, column 23, in <toplevel>
		android_sdk_repository(name = "androidsdk", path = "/root/Android/Sdk")
Error in android_sdk_repository: Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'androidsdk')
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.945s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by sureshdagooglecom** [comment]
Hi @LMR2018 ,
Could you provide steps to reproduce the issue.

**Comment by LMR2018** [comment]
> 

@sureshdagooglecom    bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

**Comment by wingdi** [comment]
Did you define android_sdk_repository twice ?

**Comment by wingdi** [comment]
This is repeated , ref https://github.com/google/mediapipe/issues/3214 , I will close this one.
