### ISSUE TITLE
Enable Segmentation Configuration in Objectron

### ISSUE THREAD

**Issue by kXborg** [google/mediapipe#3213]
Hi,

The documentation shows the following image where the detected object is also segmented. But I can not see any enable_segmentation flag. How can I achieve the following results?
![segmentation](https://google.github.io/mediapipe/images/objectron_sample_network_results.png)

**Comment by sureshdagooglecom** [comment]
Hi @kXborg ,
could you please check [this](https://google.github.io/mediapipe/solutions/pose.html#enable_segmentation) document for more information.

**Comment by kXborg** [comment]
Hi @sureshdagooglecom,
Thanks for responding but that document is for the MediaPipe Pose solution not ![Objectron](https://google.github.io/mediapipe/solutions/objectron.html).  I can not see this API in Objectron docs. The point is, it's not included in the ![Objectron source script](https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/objectron.py) itself. But since the output is being shown in the docs, I was wondering if we can achieve that by using a few modifications.

**Comment by sureshdagooglecom** [comment]
Hi @kXborg ,
We have python solution available API  available for objectron , Please check [this](https://google.github.io/mediapipe/solutions/objectron#:~:text=and%20z%20directions.-,Python%20Solution%20API,-Please%20first%20follow) document for more information.

**Comment by sureshdagooglecom** [comment]
Hi @kXborg ,
MediaPipe solutions do not include an object segmentation model.  It sounds like an interesting project.  We believe that object segmentation models do exist outside of MediaPipe.  Please let us know if you find useful approaches for this problem.
