### ISSUE TITLE
Error in android_sdk_repository: Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'androidsdk')

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#3214]
root@alg-ubuntu:/home/alg/ai/mediapipe# bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH=$(which python3) mediapipe/examples/desktop/hello_world 

DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  /home/alg/ai/mediapipe/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31: in <toplevel>
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2f6de37d68a4c69e2ff9eec3cebbf1369e496940.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4b5ccf4cd017eecbcf65d4a301853c6c/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: Traceback (most recent call last):
	File "/home/alg/ai/mediapipe/WORKSPACE", line 418, column 23, in <toplevel>
		android_sdk_repository(name = "androidsdk", path = "/root/Android/Sdk")
Error in android_sdk_repository: Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'androidsdk')
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.945s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by sureshdagooglecom** [comment]
Hi @LMR2018 ,
Could you provide steps to reproduce the issue.

**Comment by mauricewells** [comment]
Pls look at ending part in WORKSPACE file
you can see android sdk repository defined several times
pls delete that definitions so that define android sdk repository once only

**Comment by MoatazNoaman2001** [comment]
> Pls look at ending part in WORKSPACE file you can see android sdk repository defined several times pls delete that definitions so that define android sdk repository once only

 how to delete definitions?

**Comment by mikel-brostrom** [comment]
This is not working for me after deleting the duplicates...
