### ISSUE TITLE
Model performance decrease while using open cv based skeleton drawing techniques

### ISSUE THREAD

**Issue by arulpraveent** [google/mediapipe#3215]
I ran the mediapipe pose and hands model over a set of images in google colab environment. The performance of the model seems to be better while the default drawing utils is used compared to a custom one using opencv. Is the default drawing utils performing any additional process other than drawing the skeleton? if so then can I get the info on what it is and how to replicate it using opencv.

**Comment by sureshdagooglecom** [comment]
Hi @arulpraveent ,
Drawing_utils are used only to  draw_landmarks on the hands or pose, please refer this [document](https://google.github.io/mediapipe/solutions/hands.html) for more information.

**Comment by arulpraveent** [comment]
@sureshdagooglecom is there a way to get the keypoint values from the drawing utils.

**Comment by sureshdagooglecom** [comment]
Hi @arulpraveent ,
Please check this closed issue https://github.com/google/mediapipe/issues/156

**Comment by sureshdagooglecom** [comment]
Hi @arulpraveent ,
 currently prototyping: plan to migrate to "libyuv" or "halide" or "VM for iOS".
"okr" to deprecate opencv, known performance issue.
