### ISSUE TITLE
Depth Map 

### ISSUE THREAD

**Issue by showbit01** [google/mediapipe#3217]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using):
- Programming language : C++/typescript/Python/Objective C/Android Java
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state:**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Please specify the use cases for this feature:**

**Any Other info:**

**Comment by showbit01** [comment]
Can we find depth maps of face from mediapipe facemesh solution?

**Comment by sureshdagooglecom** [comment]
Hi @showbit01 ,
Can you please check [this](https://google.github.io/mediapipe/solutions/face_mesh.html#:~:text=Collection%20of%20detected,same%20scale%20as%20x) documentation for depth.

**Comment by showbit01** [comment]
Hi ,I have checked but this is about landmarks not depth

**Comment by sureshdagooglecom** [comment]
Hi @showbit01,
Could you please elaborate  this issue to investigate further.

**Comment by showbit01** [comment]
I want to find the depth from the cropped face obtained from mediaipe library,the depth is a 2d matrix composed of z values

**Comment by sureshdagooglecom** [comment]
Hi @showbit01 ,
z: Should be discarded as currently the model is not fully trained to predict depth, but this is something on the roadmap.

**Comment by showbit01** [comment]
> Hi @showbit01 ,
> z: Should be discarded as currently the model is not fully trained to predict depth, but this is something on the roadmap.

Thanks for replying.
Okay got it.
