### ISSUE TITLE
Mediapipe solutions in C#\.NET

### ISSUE THREAD

**Issue by SalvishGoomanee** [google/mediapipe#3219]
Are there any simple implementations of mediapipe pose and\or holistic solutions in C#\.NET? 

I would like to be able to infer a model I trained in Python and saved as a .h5 file. I would like to use that model in Unity if possible?

**Comment by sureshdagooglecom** [comment]
Hi @SalvishGoomanee ,
We don't have MediaPipe solutions in C#\.NET, please check [this](https://google.github.io/mediapipe/) MediaPipe official document for more information.

**Comment by SalvishGoomanee** [comment]
I already know about this. I am looking for possible in C#\.NET.

**Comment by sureshdagooglecom** [comment]
Hi @SalvishGoomanee .
We will raise this request with our internal team ,Thanks

**Comment by zhou123aw** [comment]
@SalvishGoomanee Hi, guys !
Do you have any update about this issue ?

**Comment by DanielAbalde** [comment]
I'm also interesed on this.

**Comment by matlioglu** [comment]
Any updates on this topic ?

**Comment by GeorgeS2019** [comment]
@matlioglu 
Use Unity or Godot .NET Mediapipe wrappers

**Comment by Isaac-Zimba-J** [comment]
Anything on this yet? 
I would like to use Mediapipe on my .net Maui app
