### ISSUE TITLE
How to convert TENSORS_GPU to TENSORS (cpu)?

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#322]

**Comment by mcclanahoochie** [comment]
what is your ideal graph/use-case?

where in the graph do you need this conversion?

the TfLiteInferenceCalculator supports input GPU and output CPU (i.e. TENSORS_GPU in and TENSORS out)

**Comment by yxchng** [comment]
@mcclanahoochie My use case is to debug the output from TfLiteInferenceCalculator when it is a TENSORS_GPU. I need a node to convert it to TENSORS before I can convert to GPUFrame and then cv::Mat for visualization.

I can't just make the output TENSORS because the downstream nodes need it to be a TENSORS_GPU.

**Comment by mcclanahoochie** [comment]
Do the CPU & GPU inference output tensors differ (TENSORS vs TENSORS_GPU)?
They should be the same, or numerically close. In that case, you can just visualize the CPU tensors (TENSORS), and switch back to GPU when you are done visualizing/debugging.

Otherwise, there is no stand-alone GPU->CPU tensor conversion. You will have to take note of what any of the [tensors_to_X_calculator](https://github.com/google/mediapipe/tree/master/mediapipe/calculators/tflite)'s do for converting. For example [ProcessGPU](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc#L401), but it depends what type/dimensions you are working with to adapt for your needs.

**Comment by yxchng** [comment]
@mcclanahoochie  I am trying to debug the provided hair segmentation pipeline which can only run on GPU. I have switched the TFLite model to my own model and the pipeline is not providing me with the correct output (it seems to give a blank mask, likely due to some incompatibility with TFLite GPU delegate).

Therefore, if I want to do a quick debug I need to have a GPU tensor to CPU tensor node. Otherwise, I have to make the entire pipeline works with CPU which is even more tedious.

**Comment by mcclanahoochie** [comment]
Are you getting any logcat errors?
 Such as 
```
ERROR: Next operations are not supported by GPU delegate:
<op name>: Operation is not supported.
```

Connecting a GPU->CPU tensor calculator right after the inference calculator would be exact same thing as running the inference calculator with GPU in and CPU out. 

Also, each calculator in the hair segmentation graph can run on cpu or gpu, so you can create a new hair segmentation graph that runs everything on cpu by changing the stream names. (except on mobile, the _graph_ inputs and outputs must be GPU, but everything in-between can be cpu, including the tensors).

But, an existing generic GPU->CPU converter does not yet exist :/

**Comment by mcclanahoochie** [comment]
To elaborate on the previous comment, running hair segmentation on mobile on cpu...

1. get rid of all the '_GPU' from tags
2. add a GpuBufferToImageFrameCalculator at the beginning of the graph
3. add a ImageFrameToGpuBufferCalculator at the end of the graph

now the processing runs on CPU (the graph input/output must still be GPU on android/ios)

**Comment by yxchng** [comment]
@mcclanahoochie Ok I will try that. Thanks a lot!

**Comment by yxchng** [comment]
@mcclanahoochie It does not work after the change because RecolorCalculator has no CPU support. It gives the error

> Calculator::Process() for node "[RecolorCalculator, RecolorCalculator with output stream: output_video_cpu]" failed: CPU support is not implemented yet.

**Comment by yxchng** [comment]
Ok I solved the problem. 

But still I think it would be good to have GPU to CPU tensor node. :)

**Comment by mcclanahoochie** [comment]
My apologies, I thought that calculator had been updated.

Thanks for the feedback. We have noted the request, and do see value in it.

**Comment by shehramjamil** [comment]
> To elaborate on the previous comment, running hair segmentation on mobile on cpu...
> 
> 1. get rid of all the '_GPU' from tags
> 2. add a GpuBufferToImageFrameCalculator at the beginning of the graph
> 3. add a ImageFrameToGpuBufferCalculator at the end of the graph
> 
> now the processing runs on CPU (the graph input/output must still be GPU on android/ios)

Can we put the image transformation calculator on CPU and all the rest over the GPU using this method above on android?
