### ISSUE TITLE
I need help in extracting the face image from the bounding box

### ISSUE THREAD

**Issue by khairulsynapse** [google/mediapipe#3220]
I have been creating a code for face detection using mediapipe and I am trying to extract the face image to be saved to a local directory. I guess that extrating part is needed to be added to the code below. Can someone help. I was able to print out the bounding box but still unsucessfully figure out how to extract the face image. Please refer to my codes below :

import cv2
import mediapipe as mp
import uuid   # Unique identifier
import os
mp_face_detection = mp.solutions.face_detection
mp_drawing = mp.solutions.drawing_utils

# For webcam input:
cap = cv2.VideoCapture(0)
with mp_face_detection.FaceDetection(
    model_selection=0, min_detection_confidence=0.5) as face_detection:
  while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      continue

    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = face_detection.process(image)

    # Draw the face detection annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    if results.detections:
        for detection in results.detections:
            mp_drawing.draw_detection(image, detection)
    # Flip the image horizontally for a selfie-view display.
    location_data = detection.location_data
    if location_data.format == location_data.RELATIVE_BOUNDING_BOX:
        bb = location_data.relative_bounding_box
        bb_box = [bb.xmin, bb.ymin, bb.width, bb.height]
        print(f"RBBox: {bb_box}")
    cv2.imshow('MediaPipe Face Detection', cv2.flip(image, 1))
    if cv2.waitKey(5) & 0xFF == 27:
        break
  cap.release()
  cv2.destroyAllWindows()

**Comment by sureshdagooglecom** [comment]
Hi @khairulsynapse ,
Could you please share me error logs or any reference images/videos w.r.t above issue.

**Comment by khairulsynapse** [comment]
Hi @sureshdagooglecom. No error. It is just that I need some help with the coding in to extract the face image.

**Comment by khairulsynapse** [comment]
Hi. I guess this is not issue related. I will close it at this moment. Sorry for the inconvenience caused.
