### ISSUE TITLE
Android Hands Solution load Video Left/Right Issue

### ISSUE THREAD

**Issue by lhalcyon** [google/mediapipe#3221]
Here is the scene , user need to do like the video shows. 

I use MP Android Hands Solution to load the demo video , get:
![image](https://user-images.githubusercontent.com/21357951/161184049-f4490037-2b5b-41a1-bc23-2c8feba358a5.png)

Actually , It's right hand video , but solution recognise it as left hand ( left green,right red)
Then I start front camera , and do as video shows , it recognised the hand correctly:
![image](https://user-images.githubusercontent.com/21357951/161184232-92800bee-73de-40fe-a4ac-6816554042ed.png)

I calculate the finger angle of video , compare it to the angle of mine , can't get the idea result each time. (eg: video result: 40 , mine: 40 +- n)

here is my code about angle
```
 NormalizedLandmark a = value.get(0);
      NormalizedLandmark b = value.get(1);
      NormalizedLandmark c = value.get(2);

      double radians = Math.atan2(c.getY() - b.getY(), c.getX() - b.getX()) - Math.atan2(a.getY() - b.getY(), a.getX() - b.getX());
      int angle = (int) Math.abs(radians * 180.0 / Math.PI);
      if (angle > 180){
        angle = 360 - 180;
      }
```
a b c  is the landmark point like  8 7 6.
it's migrated from python methoned in other solved issue

**Comment by lhalcyon** [comment]
Is the video left/right incorrect leads to the compare result  mismatch?

**Comment by sureshdagooglecom** [comment]
Hi @lhalcyon ,
Could you please elaborate this issue.

**Comment by lhalcyon** [comment]
Hi 

> Hi @lhalcyon , Could you please elaborate this issue.

Hi .  That are two questions.
1. Why  Android hands Solution detect the wrong hand after load video ( plz have a look at the pictures above , actually it's the right hand , but detect as left)
2. Does it make difference when I use the right hand landmark to calculate angels compare to the result on 1 ( angle calculate code pasted above)

**Comment by kuaashish** [comment]
Hello @lhalcyon,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
