### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'Vector3') on control_utils_3d.js

### ISSUE THREAD

**Issue by Paolo-Sotorro** [google/mediapipe#3223]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): nope
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Chrome
- Programming Language and version ( e.g. C++, Python, Java): React + typescript
- [MediaPipe version](https://github.com/google/mediapipe/releases): 3d Controls
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ): Hands

I tried to show the 3d mesh on a component using the npm package but im getting this error:
![image](https://user-images.githubusercontent.com/99659485/161345357-07b93a1f-b263-4dab-a0a0-517977f2ced7.png)

I have tried adding <script> to html directly but without success: document.write() is being blocked

Here's the code i have: 
```
import { LandmarkGrid } from '@mediapipe/control_utils_3d';
import React, { useEffect, useRef } from 'react';

const LogViewer = () => {
  const gridContainer = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const grid = new LandmarkGrid(gridContainer.current as HTMLElement);
    grid.updateLandmarks([]);
  }, []);

 return (
      <div ref={gridContainer} style={{ width: '100%', height: '100%', position: 'absolute' }} />
  );
}
```

I read trough other similar issues but none of the solutions worked for me.

**Comment by Paolo-Sotorro** [comment]
In firefox the error is a bit different:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/99659485/161382694-fdeb0917-49e7-420c-8983-93707ba3319c.png">

**Comment by sureshdagooglecom** [comment]
Hi @Paolo-Sotorro ,could you please provide steps to reproduce this issue.

**Comment by Paolo-Sotorro** [comment]
There you go: https://codesandbox.io/s/tender-architecture-ksu49p?file=/src/LandmarkGrid.tsx

**Comment by Paolo-Sotorro** [comment]
Really no one will address it?

**Comment by ayoub-root** [comment]
import the file using <script src='.....'</script>
then in your react code use
const LandMarkGrid =window.LandmarkGrid

grid = new LandmarGrid (divRef, ....)
be careful to components re-rendering (strictMode)

**Comment by mikerudge** [comment]
Still getting the same error with 
```
"@mediapipe/control_utils_3d": "^0.3.1635987963",
```

**Comment by Rahuld27** [comment]
Is it fixed ?

**Comment by kuaashish** [comment]
Hello @Paolo-Sotorro,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
