### ISSUE TITLE
The output of face mesh model is not in [0,1]

### ISSUE THREAD

**Issue by HZNUJeffreyRen** [google/mediapipe#3224]
I try to convert the tflite model to onnx. The results I get with the onnx model are not normalized but between 0 and 192.
I also ran with mediapipe and the result is normalized.
What steps are needed after model inference?

**Comment by sureshdagooglecom** [comment]
Hi @HZNUJeffreyRen ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/1192
