### ISSUE TITLE
Storing handModel on sessionstorage

### ISSUE THREAD

**Issue by veetechh** [google/mediapipe#3225]
I am trying to store initialized handmodel variable on sessionstorage and retrieve it next time when user loads. So that the model files don't have load/initialize second time onwards and this will speed up the loading. It is giving handModel.onresults function not defined after retrieving from sessionstorage.

     let isHandModelLoaded = window.sessionStorage.getItem('isHandModelLoaded');
     console.log("isHandModelLoaded: ", isHandModelLoaded);

    if(isHandModelLoaded == null){
            handModel = new Hands({
            locateFile: (file) => {
                 // return `https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`;
                return `./js/mp/hand/${file}?2`;
             //  return `https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1.1617147326/${file}`;
            }
        });

        handModel.setOptions({
            maxNumHands: 2,
            // modelComplexity: 1,
            modelComplexity: 0,
            minDetectionConfidence: 0.75,
            minTrackingConfidence: 0.75
        });
         window.sessionStorage.setItem('isHandModelLoaded', 'true');
         console.log("handModel1", handModel);
         window.sessionStorage.setItem('handModelVariable', JSON.stringify(handModel));
         console.log("handModel2", JSON.stringify(handModel));
    }
    else{
        handModel = JSON.parse(window.sessionStorage.getItem('handModelVariable'));
        console.log("handModelStored", window.sessionStorage.getItem('handModelVariable'));
        //handModel = JSON.parse(handModelVariable);
    }

After these, I am calling the function below.

handModel.onResults(onPlay_hand);

**Comment by ayushgdev** [comment]
This happens because `JSON.stringify()` strips away the function members of any object before storing to `sessionStorage` or `localStorage`. This is core JS behaviour.
`onResults` is a function which is attached to Hands object prototype. Hence, it cannot be stored in the browser storages.
you can check this behaviour of Javascript language with minimal example:
```
const test = {
    "name": "Rajveer", 
    "summation": function(){
        let a = 12+3;
        console.log("Hello World ", a);
    }
}
console.log(JSON.stringify(test))  // This will not have "summation" function
```
