### ISSUE TITLE
Finding Orientation of 3D Pose

### ISSUE THREAD

**Issue by mmbaguette** [google/mediapipe#3226]
Using the 3D pose estimation model, how can I calculate the yaw, pitch and roll rotation Euler angles? 

For example, if I raised my left arm in front of me, level to the ground, how can I determine that the pitch in this example is 90 degrees?

Similar issues:
https://github.com/google/mediapipe/issues/2809
https://github.com/google/mediapipe/issues/1561

The only issue these threads is address is for the face mesh estimation. I’m looking for the entire pose. 

Python 3.9 on Windows.

**Edit:** I’m not knowledgeable in 3D coordinate physics like matrices. Please tell me more than just giving me a resource where I can calculate these angles.

Thanks.

**Comment by cgtinker** [comment]
in your case you can use the camera look at concept. let's say they shoulder is the eye and the elbow the target and you want to rotate the shoulder to the elbow.
Here a sample code to get going:

```
def vec_length(v: np.array):
    return np.sqrt(sum(i**2 for i in v))

def normalize(v):
    norm = np.linalg.norm(v)
    if norm == 0: 
       return v
    return v / norm

def look_at(eye: np.array, target: np.array):
    axis_z = normalize((eye - target))
    if vec_length(axis_z) == 0:
        axis_z = np.array((0, -1, 0))
        
    axis_x = np.cross(np.array((0, 0, 1)), axis_z)
    if vec_length(axis_x) == 0:
        axis_x = np.array((1, 0, 0))
    
    axis_y = np.cross(axis_z, axis_x)
    rot_matrix = np.matrix([axis_x, axis_y, axis_z]).transpose()
    return rot_matrix
```

this function returns a 3x3 rotation matrix from which you can calculate a quaternion.

**Comment by sureshdagooglecom** [comment]
Hi @mmbaguette ,
Can you provide code changes to investigate further on this issue.

**Comment by mmbaguette** [comment]
I will take a look soon today, as I'm occupied atm. Wdym by code changes?

**Comment by sureshdagooglecom** [comment]
Hi @mmbaguette .
Hope this https://github.com/google/mediapipe/issues/3226#issuecomment-1096846680  helped to resolve this issue .

**Comment by Notedop** [comment]
I was looking for the same and I found this video that does Head Pose Estimation using Mediapipe in Python. 

[Youtube video](https://www.youtube.com/watch?v=-toNMaS4SeQ&t=2s)
[python script](https://github.com/niconielsen32/ComputerVision/blob/master/headPoseEstimation.py)

**Comment by studykic** [comment]
w

**Comment by jinfagang** [comment]
Anyone knows how to convert the 3d pose to quaternion based?

**Comment by studykic** [comment]
도움이 될지 모르겠지만
나는 아래 사이트에서 원하는 각도를 구했습니다 행운을 빌어요
***@***.***/head-pose-estimation-with-mediapipe-and-opencv-in-javascript-c87980df3acb

2023년 2월 2일 (목) 오후 9:50, JinTian ***@***.***>님이 작성:

**Comment by mmbaguette** [comment]
사이트 없어요

**Comment by studykic** [comment]
I don't know if it'll help.
I found the angle I wanted on the site below.

사이트 게시글제목 : Head Pose Estimation with MediaPipe and OpenCV in Javascript

https://medium.com/@susanne.thierfelder/head-pose-estimation-with-mediapipe-and-opencv-in-javascript-c87980df3acb

위 url이 잘 안나오네요
https://is.gd/qc3Y1k

**Comment by mmbaguette** [comment]
고마워,저는 3D Pose 이용해요. 그러나 그것을 읽을 거예, 아마 그것은 돕아요

**Comment by khannabeela** [comment]
@lucasjinreal Did you find how to convert the 3D landmarks from mediapipe to quaternions?

**Comment by lucasjinreal** [comment]
Not yet, not easy to do so, need use IK in game software
