### ISSUE TITLE
Face Mesh - How to search a database record, starting from identifying a person’s face?

### ISSUE THREAD

**Issue by CapitanMurloc** [google/mediapipe#3231]
Hello everyone,

I have been asked to identify faces of people to perform searches in a database.

What data can I use to generate a unique identifier for a face using MediaPipe Face Mesh?

I understand that the benchmarks are helpful, but I don't see how to put it into practice.

If someone who knows more about this topic or has already faced this task can help me or give me some direction, I would appreciate it.

Regards.

**Comment by Blu-Eagle** [comment]
top

**Comment by kuaashish** [comment]
Hi @CapitanMurloc,
MediaPipe does return detections, or face images, or rendered detection rectangles but does not have any APIs for storage of these returned results. Thank you!

**Comment by CapitanMurloc** [comment]
> 

Thanks for the answer, I actually saw what is required to identify a face uniquely. I use MediaPipe to detect if there is a face and another library to store the face.

**Comment by kuaashish** [comment]
Hi @CapitanMurloc,
Good to hear that you have found the solution for the use case mentioned. Could you please share the implementation to archive the task it will be helpful for community members. Thank you!

**Comment by CapitanMurloc** [comment]
My solution is based on DeepFace (https://github.com/serengil/deepface), the embedding must be stored, for example in ElasticSearch. Then using the cosine function you can perform similarity searches.

**Comment by kuaashish** [comment]
Hi @CapitanMurloc, 
Thank you very much for the contribution! Could we move this issue to close status as it has been resolved. Thank you!
