### ISSUE TITLE
Arm platform face mesh is too slow

### ISSUE THREAD

**Issue by wuheng0711** [google/mediapipe#3232]
I successfully cross compiled the face mesh module and called it on the arm platform. It takes 330ms to process a frame of 640 * 480 * 1 image. I use imx8 development board with 4 processors CortexA53@0.90GHz And 2 CortexA72@1.2GHz 。 Is there any acceleration scheme available? I compiled the desktop version of face mesh in example

**Comment by June1124** [comment]
I too, need to compile the GPU version of the function on ARM-based on C++. What should I do?

**Comment by sureshdagooglecom** [comment]
Hi @wuheng0711 ,
Did you get a chance to check [this](https://google.github.io/mediapipe/solutions/face_mesh.html) official document face mesh.

**Comment by wuheng0711** [comment]
> I too, need to compile the GPU version of the function on ARM-based on C++. What should I do?

You can try to use docker to compile the version on arm, which will improve the speed a lot. In addition, calling the lightweight model will also improve the speed.
