### ISSUE TITLE
The stop() method on the Camera does not disable requestAnimationFrame calls

### ISSUE THREAD

**Issue by Dok11** [google/mediapipe#3233]
I use `camera_utils.js` and after call `.stop()` on the instance of Camera class the requestAnimationFrame still works.

![image](https://user-images.githubusercontent.com/2697890/161802335-2778f873-7735-475f-8418-c2ac9233500c.png)
![image](https://user-images.githubusercontent.com/2697890/161802420-04093796-9ca7-4d90-a19e-78aafe705d05.png)

As you can see the link to the requestAnimationFrame not saved to any class property, so it can't be remove after call the stop method.
![image](https://user-images.githubusercontent.com/2697890/161802616-44a6bc93-b82c-4280-9b2f-d83ccea205c2.png)

And, of course, in the whole js file does not present the cancelAnimationFrame method that should be calls in the stop method.

**Comment by DeividVeloso** [comment]
@Dok11 maybe it is related to this bug, can you test it, please?

https://github.com/google/mediapipe/issues/3373

**Comment by rewrking** [comment]
Experienced this as well integrating mediapipe into a site with dynamic routing. Once `start()` is called, the camera stays on -- indicated in the chrome tab and on the camera, even if the page isn't rendering the contents of the mediapipe stream. 

Calling `stop()` seemingly has no effect.

**Comment by kuaashish** [comment]
Hello @Dok11,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by galharth** [comment]
Hey have you solved this issue ?
