### ISSUE TITLE
Using face mesh tflite model in Unity3D

### ISSUE THREAD

**Issue by pytholic** [google/mediapipe#3234]
Any guide on how to use `tflite` face mesh model in Unity3D?

I have some images which I want to load in Unity3D and then detect landmarks using the face mesh model. Thank you!

**Comment by sureshdagooglecom** [comment]
Hi @pytholic ,
Could you please elaborate use case w,r,t above issue.

**Comment by pytholic** [comment]
> Hi @pytholic , Could you please elaborate use case w,r,t above issue.

I want to perform inference on some images and display results in Unity UI. I wanted to use `onnx` model but I had issues during the conversion process. So I decided to use `tflite` model instead because that is the one provided here in the official repo.

So I wanted to find some help on how to load the model and use it for inference in Unity3D.

**Comment by sureshdagooglecom** [comment]
Hi @pytholic ,
Mediapipe team doesn't recommend or support converting models from TFLite.
