### ISSUE TITLE
How to use mediapipe in Qt?

### ISSUE THREAD

**Issue by Billccx** [google/mediapipe#3235]
Hello!
I want to make a pose tracking APP, using Qt for frontend and mediapipe for backend. 
Could you please tell me how to integrate mediapipe into a Qt project ?
Thanks in advance.

**Comment by sureshdagooglecom** [comment]
Hi @Billccx ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/1373?

**Comment by Billccx** [comment]
@sureshdagooglecom 
Thanks for your reply!
I have checked this issue, but unfortunately failed to get help. 
What I want to do is compile mediapipe to a shared library (.so and header file) and add it to the Qt project. Actually, I only need  to compile a little part of mediapipe to the shared library, since I just use pose tracking.
Could you please tell me how to do? Thanks

**Comment by sureshdagooglecom** [comment]
Hi @Billccx ,
We don't have feature of shared library in Media Pipe at present.

**Comment by MMIINNHH** [comment]
https://github.com/asprecic/mediapipe-qt-integration-example

Take a look at this repository. 
I tried this and succeeded in executing mediapipe .so file  in QT project

**Comment by pedroarroyo** [comment]
> https://github.com/asprecic/mediapipe-qt-integration-example
> 
> Take a look at this repository. I tried this and succeeded in executing mediapipe .so file in QT project

Hi, MinHyeong.  Did you just point the example_lib_path the the mediapipe build folder?
