### ISSUE TITLE
Error when converting face_landmark.tflite to ONNX.

### ISSUE THREAD

**Issue by 170928** [google/mediapipe#3238]
I want to convert face_landmark.tflite to onnx.

So I tried the method below:
```
python -m tf2onnx.convert --tflite face_landmark.tflite --output face_landmark.onnx 
```

However, I keep getting the error below.
```
struct.error: unpack_from requires a buffer of at least 168430094 bytes for unpacking 4 bytes at offset 168430090 (actual buffer size is 129390)
```

Any workarounds?

**Comment by 170928** [comment]
I solved this problem using conversion from [tfjs](https://tfhub.dev/mediapipe/tfjs-model/facemesh/1/default/1) to onnx. 

But, I couldn't create an onnx file using a tflite file.

**Comment by sureshdagooglecom** [comment]
Hi @170928 ,
Mediapipe team doesn't recommend or support converting models from TFLite.
