### ISSUE TITLE
GLES, How to add anti-aliasing ?  

### ISSUE THREAD

**Issue by wingdi** [google/mediapipe#3239]
Platform : Android 
Solution :  Face Mesh

In effect_renderer.cc, I changed dst_texture's color container from glTexImage2D() to glTexStorage2DMultisample(), but it does not work.

**Comment by kuaashish** [comment]
@wingdi,
Are you still looking for the resolution on this issue? If yes, then would you let us know the complete steps followed to reproduce the issue from our end. Feel free to close if no longer issue from your end.
