### ISSUE TITLE
InputStreamHandler choose

### ISSUE THREAD

**Issue by jiqimaogou** [google/mediapipe#324]
I have a situation like this,

one inputstream is less frequency than another，

![image](https://user-images.githubusercontent.com/1407040/70979662-f26fb800-20ec-11ea-84fe-96711fefa6f0.png)

and less frequency inputStream is more fast than another,

if I use SyncInputStreamHandler, the fast inputstream will be processed first, the process sequence is:
0, 1, 3, 2(becaulse, 3 is faster than 2), record to the arrive order. not the packet timestamp

how do I that it output the right order,

0, 1, 2, 3.

**Comment by hadon** [comment]
I think I understand what you want to achieve.  MediaPipe will sequence the inputs in timestamp order if the "DefaultInputStreamHandler" is specified, or if the inputs are included in a single "SyncSet" within "SynSetInputStreamHandler".  

When the inputs are combined in this way, MediaPipe must determine that all input packets up through Timestamp(2) have arrived for before invoking Process() with Timestamp(2).  before invoking Process() with Timestamp(2), MediaPipe will wait until the calculators feeding both the first and second input stream have either delivered a packet at or above Timestamp(2) or have indicated a "timestamp bound" at or above Timestamp(2).

**Comment by hadon** [comment]
To clarify: Packets will be processed out of timestamp-order only through separate SyncSets, or through separate inputs to ImmediateInputStreamHandler.  With DefaultInputStreamHandler, the scheduler will wait for Timestamp(2) before invoking Process() with Timestamp(3).

**Comment by jiqimaogou** [comment]
yes.... does mediapipe support it?

**Comment by eknight7** [comment]
This is what already happens presently.

**Comment by jiqimaogou** [comment]
> This is what already happens presently.

With DefaultInputStreamHandler, is already happens presently.
but DefaultInputStreamHandler must wait for ather inputstream bound is large than the first.

I want to use SyncInputStreamHandler, the SyncInputStreamHandler is not the all inputstream timestamp ordered. timestamp ordered just happend in seperate sync set.

**Comment by jiqimaogou** [comment]
![image](https://user-images.githubusercontent.com/1407040/71155912-c7ff3580-2279-11ea-8f6a-a2834afa2ef3.png)
