### ISSUE TITLE
Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.

### ISSUE THREAD

**Issue by wenweijia** [google/mediapipe#3240]
**Describe the problem**:
Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.

**Comment by sureshdagooglecom** [comment]
Hi @wenweijia ,
Changing MIN_IOS_VERSION = "10.0" to MIN_IOS_VERSION = "11.0" in the BUILD files for the ios examples allowed  to build the examples.

**Comment by wenweijia** [comment]
Hi@sureshdagooglecom ，thanks for your help, I changed it , now it has errror tip: Creating symlink bazel-out/applebin_ios-ios_arm64-dbg-ST-2967bd56a867/bin/mediapipe/examples/ios/facedetectiongpu/FaceDetectionGpuApp-intermediates/embedded.mobileprovision failed: missing input file '//mediapipe:provisioning_profile.mobileprovision'

**Comment by sureshdagooglecom** [comment]
Hi @wenweijia ,
If you are trying to build Hands solution in Android . You can have a look at our gradle api implementation from here https://google.github.io/mediapipe/getting_started/android_solutions.html#mediapipe-android-solutions

**Comment by a10aquafina** [comment]
> CHÀO@wenweijia, Thay đổi MIN_IOS_VERSION = "10.0" thành MIN_IOS_VERSION = "11.0" trong tệp BUILD cho các ví dụ ios được phép xây dựng các ví dụ.

i am using xcode 15.0, min ios version is 12.0, i can not down to 11.0
