### ISSUE TITLE
Multiple extension registrations. Compile success but runtime error

### ISSUE THREAD

**Issue by Billccx** [google/mediapipe#3242]
Hello!
My program failed to run and got the error below:
```
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/extension_set.cc:117] Multiple extension registrations for type "mediapipe.CalculatorOptions", field number 326963320.
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  Multiple extension registrations for type "mediapipe.CalculatorOptions", field number 326963320.
```
What's the problem? 
My program works well before I make a little change. I just changed a calculator which is defined by myself (add a node option for it). Then I recovered my calculator and rebuild my project. However, the problem still exist ! 
Could you please tell me what to do ?

**Comment by Billccx** [comment]
Besides that, I try to rollback the version of my project. I download the previous version of my project on github and build. However, it still go wrong:
```
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/extension_set.cc:117] Multiple extension registrations for type "mediapipe.CalculatorOptions", field number 326963320.
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  Multiple extension registrations for type "mediapipe.CalculatorOptions", field number 326963320.
```

**Comment by sureshdagooglecom** [comment]
Hi @Billccx ,
Could you provide steps to reproduce this issue.

**Comment by zhouyang1989** [comment]
@Billccx Hello，我遇到了一样的问题，请问你当时是怎么解决的呢？
