### ISSUE TITLE
INT8 Quantized models for Palm detection and Hand landmark

### ISSUE THREAD

**Issue by mrtpk123** [google/mediapipe#3243]
Hello,

The TFlite models published for Palm detection and Hand landmark are in float32. I'm looking for TFlite models that are [full integer quantized](https://www.tensorflow.org/lite/performance/post_training_integer_quant) (edge TPU models). Are these models available? 

If these fully integer quantized models are not available, can you share the saved model formats from which I can create full integer quantized models? I'm happy to contribute.

Thanks.

**Comment by sureshdagooglecom** [comment]
Hi @mrtpk123 ,
Did you get a chance to check this closed issue in Edge TPU Models https://github.com/google/mediapipe/issues/212

**Comment by sureshdagooglecom** [comment]
Hi @mrtpk123 ,
Please check [this](https://google.github.io/mediapipe/solutions/models.html)  for different solutions on tflite.

**Comment by mrtpk123** [comment]
Hi @sureshdagooglecom, As I have mentioned in the issue I'm looking for a fully quantized model and the published tflite models are in float.

**Comment by sureshdagooglecom** [comment]
Hi @mrtpk123 ,
We don't have this feature at present , we will take this as a feature request.

**Comment by wuheng0711** [comment]
> 你好@sureshdagooglecom, 正如我在问题中提到的，我正在寻找一个完全量化的模型，并且已发布的 tflite 模型处于浮动状态。

Have you solved this problem? I also met the same demand.

**Comment by mrtpk123** [comment]
@wuheng0711 Unfortunately mediapipe doesn't have the models int8. Check out this repo - https://github.com/PINTO0309/PINTO_model_zoo for models.

**Comment by wuheng0711** [comment]
> @wuheng0711不幸的是 mediapipe 没有 int8 模型。查看此 repo - https://github.com/PINTO0309/PINTO_model_zoo了解模型。

Do you have a lightweight model to convert FLOAT32 to INT8? If so, can you send it to me? I'm not familiar with this style, thank you very much.

**Comment by mrtpk123** [comment]
@wuheng0711 Unfortunately, I don't have any FLOAT32 models. But, there are saved models and PB files in this repo - https://github.com/PINTO0309/PINTO_model_zoo. Please do check it out.

**Comment by freesokim** [comment]
> Hi @mrtpk123 , We don't have this feature at present , we will take this as a feature request.

Hi, do you have a plan to release the quantized models for palm and hand landmark?

**Comment by wuheng0711** [comment]
> @wuheng0711不幸的是，我没有任何 FLOAT32 模型。但是，这个 repo 中有保存的模型和 PB 文件 - https://github.com/PINTO0309/PINTO_model_zoo。请务必检查一下。

When I have a quantitative model, which code should I modify to call?

**Comment by dubrovin-sudo** [comment]
I have the same question! Nice to have INT8 Quantized models for Palm detection and Hand landmark
