### ISSUE TITLE
 Linux：mediapipe.solutions.hands.Hands   existence   serious  Memory leak

### ISSUE THREAD

**Issue by 464hee** [google/mediapipe#3244]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
 Linux Ubuntu 20.04

- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):  YES!

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
 Linux Ubuntu 20.04 ,python3.8，mediapipe==0.8.9.1

- [MediaPipe version](https://github.com/google/mediapipe/releases):
mediapipe==0.8.9.1

- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):
Pose:Hand
- Programming Language and version ( e.g. C++, Python, Java):
 python==3.8

**Describe the expected behavior:**

When exploring hand running detection, the computer running memory has been increased without limit

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:
Error code：

import gc
import mediapipe
import sys
import cv2
import time

def f(kkk):
    hands = mediapipe.solutions.hands.Hands(static_image_mode=False,
                          max_num_hands=1,
                          min_detection_confidence=0.6,
                          min_tracking_confidence=0.6)
    list1 = []
    path='/media/totem_disk/totem/hebingdou/2022-03-26/'+str(kkk)+'.MP4'
    cap = cv2.VideoCapture(path)
    hhd = int(cap.get(7))
    for i in range(hhd):
        success, img = cap.read()
        img = cv2.resize(img, dsize=(640,360), interpolation=cv2.INTER_AREA)
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # results = hands.process(imgRGB)
        list1.append(imgRGB)

    print(sys.getrefcount(list1))
    del hands
    del list1
    gc.collect()
    print("gc 运行结束")
    time.sleep(5)

if __name__ == '__main__':
    b=[1,2,3,4,5,6,7]
    for i in b:
        f(i)

Explain：
I prepared seven videos for hand joint point detection, but found that the list always occupied the computer memory during operation.After investigation, it is found that if I define {  hands = mediapipe.solutions.hands.Hands(....)  }, there will be such a situation, that is, the computer memory will increase infinitely,This happens even if I don't use the variable {  hands = mediapipe.solutions.hands.Hands(....)  }

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by 464hee** [comment]
[Error_demonstration.zip](https://github.com/google/mediapipe/files/8440406/Error_demonstration.zip)
mediapipe Is a good framework , Look forward to your reply！

**Comment by 464hee** [comment]
It has been determined that ：{ success, img11 = cap.read() }  Follow {hands = mediapipe.solutions.hands.Hands(.... ) }  Conflict

**Comment by sureshdagooglecom** [comment]
Hi @464hee,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/1758

**Comment by 464hee** [comment]
> 嗨@464hee， 你有机会检查这个已关闭的问题#1758

ok,i  look look
