### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by aino-vnarayan** [google/mediapipe#3246]
results = face_mesh.process(cv.cvtColor(image, cv.COLOR_BGR2RGB)) return super().process(input_data={'image': image}) input_stream_type = self._input_stream_type_info[stream_name] TypeError: 'NoneType' object is not subscriptable

**Comment by sureshdagooglecom** [comment]
Hi @aino-vnarayan,
Could you share code changes to investigate further on this issue.

**Comment by sALTaccount** [comment]
To anyone else having this issue, this happens if `face_mesh` is closed with `.close()`, and then you try to use it afterwards.
