### ISSUE TITLE
No detail error info when open camera

### ISSUE THREAD

**Issue by JerryMagicc** [google/mediapipe#3247]
**System information** 

- I built the AAR by bazel in Ubuntu 20.04, and then used it in Android Studio which in Windows10.
- My code refer to  [mediapipe_multi_hands_tracking_aar_example], not any change.
- Ubuntu 20.0, Windows 10, Android 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
- Programming Language and version ( e.g. C++, Python, Java):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ):
- Android Studio Bumblebee | 2021.1.1 Patch 2, NDK 24.0.8215888, SDK targetSdk 32, minSdk 21
- 
**Describe the current behavior:**
When I install the example on my phone, it will crash when I allowed camera permissions.

**Describe the expected behavior:**

**Standalone code to reproduce the issue:**
My code refer to  [mediapipe_multi_hands_tracking_aar_example](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example), not any change.

**Other info / Complete Logs :**

04/08 12:20:56: Launching 'app' on HUAWEI CDY-AN00.
App restart successful without requiring a re-install.
$ adb shell am start -n "jervois.archeryrecognition/jervois.archeryrecognition.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 12885 on device 'huawei-cdy_an00-MKB4C20605039549'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/heryrecognitio: Late-enabling -Xcheck:jni
W/heryrecognitio: type=1400 audit(0.0:13720): avc: denied { read } for pid=12885 name="u:object_r:device_config_runtime_native_prop:s0" dev="tmpfs" ino=3325 scontext=u:r:untrusted_app:s0:c227,c256,c512,c768 tcontext=u:object_r:device_config_runtime_native_prop:s0 tclass=file permissive=0
E/libc: Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
E/heryrecognitio: LoadAppImageStartupCache enabled : 1
E/heryrecognitio: Unknown bits set in runtime_flags: 0x8000
I/heryrecognitio: Reinit property: dalvik.vm.checkjni= false
I/heryrecognitio: ReInitProperties: persist.vm.debug.dumpapi= false
D/ActivityThread: Attach thread to application
I/ActivityThread: Init compatible state: true
D/HwFrameworkSecurityPartsFactory: HwFrameworkSecurityPartsFactory in.
I/HwFrameworkSecurityPartsFactory: add HwFrameworkSecurityPartsFactory to memory.
D/BehaviorCollectManager: hook process for AI virus second
I/BehaviorCollectManager: bindAnalyzerService: huawei.android.security.IAppBehaviorDataAnalyzer$Stub$Proxy@556640b pid:12885
D/ApplicationLoaders: createClassLoader zip: /data/app/jervois.archeryrecognition-wznlW0EaXK1HJtt0mhTcyQ==/base.apk librarySearchPath: /data/app/jervois.archeryrecognition-wznlW0EaXK1HJtt0mhTcyQ==/lib/arm64:/data/app/jervois.archeryrecognition-wznlW0EaXK1HJtt0mhTcyQ==/base.apk!/lib/arm64-v8a libraryPermittedPath: /data/user/0/jervois.archeryrecognition parent: java.lang.BootClassLoader@aa7de9d targetSdkVersion: 32 isBundled: false classLoaderName: null sharedLibraries: null
I/HwPartIawareFactory: add android.common.HwPartIawareFactoryImpl to memory.
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=jervois.archeryrecognition#10227#256
I/HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=0 newCnt=1
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=jervois.archeryrecognition#10227#0
I/HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=1 newCnt=1
I/HwTypeface: updateFont: scale=1.0
D/SystemFonts: areFontsVariable: script=Hant
I/AwareBitmapCacher: init processName:jervois.archeryrecognition pid=12885 uid=10227
I/ActivityThread: finishPreloaded preloadStatus 0
I/RmeSchedManager: init Rme, version is: v1.0
I/RmeSchedManager: init Rme, version is: v1.0
I/RtgSchedEvent: current pid:12885 AppType:-1
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@16fbd01
D/OpenGLRenderer: disableOutlineDraw is true
I/OpenGLRenderer: RenderThread: progress name = [jervois.archeryrecognition], viewCornerType = 0
I/iGraphics: [0020080c] pn: jervois.archeryrecognition, p: 12885
I/iGraphics: [0030080c] no spt app: jervois.archeryrecognition
V/ActivityThread: callActivityOnCreate
I/DecorView[]: pkgName:jervois.archeryrecognition old windowMode:0 new windoMode:1, isFixedSize:false
I/OverScrollerOptimization: start init SmartSlideOverScroller and get the overscroller config
I/OverScrollerOptimization: get the overscroller config
W/heryrecognitio: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/heryrecognitio: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/MainActivity: 打印信息：——————————————ApplicationInfo{ff4891d jervois.archeryrecognition}
I/MainActivity: 打印信息：——————————————setupPreviewDisplayView
I/native: I20220408 12:20:57.721663 12885 asset_manager_util.cc:59] Created global reference to asset manager.
E/libEGL: validate_display:104 error 3008 (EGL_BAD_DISPLAY)
I/native: I20220408 12:20:57.743496 12885 gl_context_egl.cc:162] Successfully initialized EGL. Major : 1 Minor: 4
I/native: I20220408 12:20:57.744899 12944 gl_context.cc:334] GL version: 3.2 (OpenGL ES 3.2 v1.r21p0-01rel0.71f38938bf020f9e4ef2f7cf98febe2b)
D/PermissionHelper: checkAndRequestCameraPermissions
I/MainActivity: 打印信息：——————————————Oncreate()
D/ActivityThread: add activity client record, r= ActivityRecord{6c36560 token=android.os.BinderProxy@3c622e8 {jervois.archeryrecognition/jervois.archeryrecognition.MainActivity}} token= android.os.BinderProxy@3c622e8
D/GlThread: Starting GL thread ExternalTextureConverter
I/CameraManagerGlobal: Connecting to camera service
I/MainActivity: 打印信息：——————————————startCamera
I/MainActivity: 打印信息：——————————————onResume()
D/MouseWheelSynthesizer: mMoveStepInDp: 64, mMoveStepInPixel: 192, mUpTimeDelayed: 100
D/ViewRootImpl: ViewRootImpl mIsInProductivePCDisplay: false
I/HwPartPowerOfficeFactory: add HwPartPowerOfficeFactoryImpl to memory.
D/InputEventReceiver: dispatchInputInterval 1000000
I/RmeSchedManager: init Rme, version is: v1.0
I/RtgSchedEvent: current pid:12885 AppType:-1
D/OpenGLRenderer: disableOutlineDraw is true
D/CameraRepository: Added camera: 0
D/HiTouch_PressGestureDetector: onAttached, package=jervois.archeryrecognition, windowType=1, mIsHiTouchRestricted=false
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository: Added camera: 1
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository: Added camera: 2
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository: Added camera: 3
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository: Added camera: 4
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraRepository: Added camera: 5
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/CameraValidator: Verifying camera lens facing on HWCDY, lensFacingInteger: null
W/Gralloc3: mapper 3.x is not supported
I/HwViewRootImpl: removeInvalidNode jank list is null
D/DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
W/InputMethodManager: startInputReason = 1
W/HwRemoteInputMethodManager: isCasting false because IHwDistributedWindowManager is invalid.
D/CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
D/CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
D/DeferrableSurface: Surface created[total_surfaces=1, used_surfaces=0](androidx.camera.core.SurfaceRequest$2@efd0105}
D/CameraXPreviewHelper: Received surface request for resolution 1280x720
D/CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
D/Camera2CameraImpl: {Camera@52ad2c1[id=1]} Use case Preview:androidx.camera.core.Preview-6918643f-4181-4c19-b5a7-3876a4fc5e1a ACTIVE
W/InputMethodManager: startInputReason = 5
D/UseCaseAttachState: Active and attached use case: [] for camera: 1
D/CameraXPreviewHelper: Providing surface
D/Camera2CameraImpl: {Camera@52ad2c1[id=1]} Use cases [Preview:androidx.camera.core.Preview-6918643f-4181-4c19-b5a7-3876a4fc5e1a] now ATTACHED
D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-6918643f-4181-4c19-b5a7-3876a4fc5e1a124887888] for camera: 1
D/UseCaseAttachState: Active and attached use case: [androidx.camera.core.Preview-6918643f-4181-4c19-b5a7-3876a4fc5e1a124887888] for camera: 1
D/Camera2CameraImpl: {Camera@52ad2c1[id=1]} Resetting Capture Session
D/Camera2CameraImpl: {Camera@52ad2c1[id=1]} Releasing session in state INITIALIZED
D/Camera2CameraImpl: {Camera@52ad2c1[id=1]} Attempting to force open the camera.
D/CameraStateRegistry: tryOpenCamera(Camera@52ad2c1[id=1]) [Available Cameras: 1, Already Open: false (Previous state: null)] --> SUCCESS
D/CameraStateRegistry: Recalculating open cameras:
    Camera                                       State                 
    -------------------------------------------------------------------
    Camera@8217133[id=5]                         UNKNOWN               
    Camera@2d64bb5[id=3]                         UNKNOWN               
    Camera@cc7478e[id=0]                         UNKNOWN               
    Camera@52ad2c1[id=1]                         OPENING               
    Camera@3da8916[id=4]                         UNKNOWN               
    Camera@7cd13c0[id=2]                         UNKNOWN               
    -------------------------------------------------------------------
    Open count: 1 (Max allowed: 1)
D/Camera2CameraImpl: {Camera@52ad2c1[id=1]} Opening camera.
D/Camera2CameraImpl: {Camera@52ad2c1[id=1]} Transitioning camera internal state: INITIALIZED --> OPENING
D/CameraStateMachine: New public camera state CameraState{type=OPENING, error=null} from OPENING and null
D/CameraStateMachine: Publishing new public camera state CameraState{type=OPENING, error=null}
D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-6918643f-4181-4c19-b5a7-3876a4fc5e1a124887888] for camera: 1
I/CameraManager: open camera: 1, package name: jervois.archeryrecognition
D/RenderService: RCS is disable
D/Camera2CameraImpl: {Camera@52ad2c1[id=1]} Use case Preview:androidx.camera.core.Preview-6918643f-4181-4c19-b5a7-3876a4fc5e1a ACTIVE
D/UseCaseAttachState: Active and attached use case: [androidx.camera.core.Preview-6918643f-4181-4c19-b5a7-3876a4fc5e1a124887888] for camera: 1
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/MainActivity: 打印信息：——————————————surfaceCreated
I/MainActivity: 打印信息：——————————————10802124
I/MainActivity: 打印信息：——————————————10802124
I/MainActivity: 打印信息：——————————————surfaceChanged
D/Camera2CameraImpl: {Camera@52ad2c1[id=1]} CameraDevice.onOpened()
D/Camera2CameraImpl: {Camera@52ad2c1[id=1]} Transitioning camera internal state: OPENING --> OPENED
D/CameraStateRegistry: Recalculating open cameras:
    Camera                                       State                 
    -------------------------------------------------------------------
    Camera@8217133[id=5]                         UNKNOWN               
    Camera@2d64bb5[id=3]                         UNKNOWN               
    Camera@cc7478e[id=0]                         UNKNOWN               
    Camera@52ad2c1[id=1]                         OPEN                  
    Camera@3da8916[id=4]                         UNKNOWN               
    Camera@7cd13c0[id=2]                         UNKNOWN               
    -------------------------------------------------------------------
    Open count: 1 (Max allowed: 1)
D/CameraStateMachine: New public camera state CameraState{type=OPEN, error=null} from OPEN and null
D/CameraStateMachine: Publishing new public camera state CameraState{type=OPEN, error=null}
D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-6918643f-4181-4c19-b5a7-3876a4fc5e1a124887888] for camera: 1
D/UseCaseAttachState: Active and attached use case: [androidx.camera.core.Preview-6918643f-4181-4c19-b5a7-3876a4fc5e1a124887888] for camera: 1
D/SyncCaptureSessionBase: [androidx.camera.camera2.internal.SynchronizedCaptureSessionBaseImpl@d9109b0] getSurface...done
D/CaptureSession: Opening capture session.
D/DeferrableSurface: New surface in use[total_surfaces=1, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@efd0105}
D/DeferrableSurface: use count+1, useCount=1 androidx.camera.core.SurfaceRequest$2@efd0105
D/CaptureSession: Attempting to send capture request onConfigured
D/CaptureSession: Issuing request for session.
D/CaptureSession: CameraCaptureSession.onConfigured() mState=OPENED
D/CaptureSession: CameraCaptureSession.onReady() OPENED
W/Gralloc3: allocator 3.x is not supported
D/ExternalTextureConv: Created output texture: 3 width: 720 height: 1280
I/native: I20220408 12:20:58.184103 12945 graph.cc:476] Start running the graph, waiting for inputs.
I/native: I20220408 12:20:58.184319 12945 gl_context_egl.cc:162] Successfully initialized EGL. Major : 1 Minor: 4
I/native: I20220408 12:20:58.187346 13072 gl_context.cc:334] GL version: 3.2 (OpenGL ES 3.2 v1.r21p0-01rel0.71f38938bf020f9e4ef2f7cf98febe2b)
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 13068 (mediapipe/13068), pid 12885 (heryrecognition)
D/ExternalTextureConv: Created output texture: 4 width: 720 height: 1280
I/native: I20220408 12:20:58.221141 13066 resource_util_android.cc:89] Successfully loaded: hand_landmark_full.tflite
I/native: I20220408 12:20:58.224836 13069 jni_util.cc:41] GetEnv: not attached
I/native: I20220408 12:20:58.266769 13064 jni_util.cc:41] GetEnv: not attached
I/native: I20220408 12:20:58.289520 13067 jni_util.cc:41] GetEnv: not attached
I/native: I20220408 12:20:58.331697 13066 jni_util.cc:41] GetEnv: not attached
I/native: I20220408 12:20:58.372510 13065 jni_util.cc:41] GetEnv: not attached
I/native: I20220408 12:20:58.410207 13070 jni_util.cc:41] GetEnv: not attached
I/native: I20220408 12:20:58.569079 13063 jni_util.cc:41] GetEnv: not attached
D/GlThread: Stopping GL thread ExternalTextureConverter
W/libEGL: EGLNativeWindowType 0x75e18f5010 disconnect failed
I/MainActivity: 打印信息：——————————————surfaceDestroyed

**Comment by kuaashish** [comment]
Hello @JerryMagicc,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by JerryMagicc** [comment]
您好，已经收到您的邮件，感谢您的来信。Hello, I have received your email. Thank you for your letter.

**Comment by kuaashish** [comment]
@JerryMagicc,
Please let us know if this is still not an issue from your end further we can move the issue to close status. Thank you
