### ISSUE TITLE
How to use OutputStreamObserver ?

### ISSUE THREAD

**Issue by Billccx** [google/mediapipe#3249]
Hello developers!
I read the source code of mediapipe and found a class called "`OutputStreamObserver`".
According to the comments in mediapipe/frameword/graph_output_stream.h :
```
OutputStreamObserver that observes the output stream and passes packets to the caller via packet_callback.
```
it seems that `OutputStreamObserver` has the same function with `OutputStreamPoller`.

However, I failed to find any document about `OutputStreamObserver`. Could you please tell me how to use it? It will be perfect if you can show me some example code: using `OutputStreamObserver` and callback function to get the output packet from graph

I am looking forward to your reply and thanks in advance!

**Comment by sureshdagooglecom** [comment]
Hi @Billccx ,
Please check [this](https://google.github.io/mediapipe/framework_concepts/calculators.html) document for usage of calculators in MediaPipe

**Comment by Billccx** [comment]
@sureshdagooglecom 
Thanks for your reply! I have read the document about calculators, but what I want to know is how to use `OutputStreamPoller`.
Actually, my question comes from this issue [https://github.com/google/mediapipe/issues/3188](url).
Could you please show me an example about how to use output stream observer ?

**Comment by sureshdagooglecom** [comment]
Hi @Billccx ,
Please check this closed issue for steps on how to use outpur stream https://github.com/google/mediapipe/issues/734
