### ISSUE TITLE
convert normalized coordinates to pixel coordinates

### ISSUE THREAD

**Issue by YongSeongLee25** [google/mediapipe#3250]
I inference the mediapipe blazepose to get the normalized coordinates.
I want to convert it to pixel coordinates.
Do you know how?

**Comment by sureshdagooglecom** [comment]
Hi @YongSeongLee25 ,
Could you please elaborate this issue to investigate further.

**Comment by sureshdagooglecom** [comment]
Hi @YongSeongLee25 ,
Could you please share on which platform you are trying this ?
