### ISSUE TITLE
How to  Scale 3D Objects ?

### ISSUE THREAD

**Issue by onuralpszr** [google/mediapipe#3251]
I was working on Face Effects/Mesh on Android but I didn't see how to scale object while rendering happening on screen, I can handle "screen pinch" via android way but "how to set value to object" while it is running ? 

For example, let's say I run example face-effect app and I wanna "scale" glasses or any other object on scene

**Comment by kuaashish** [comment]
Hello @onuralpszr,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by onuralpszr** [comment]
@kuaashish hello, I am already aware and reading/following new changes and learning to adapt that as well. 
Thank you.

**Comment by kuaashish** [comment]
@onuralpszr,
Thank you for looking out for our new upgraded solutions. These solutions will provide a superset of capabilities available in the legacy solutions. which are more helpful to adopt, more easily build and customize ML solutions for your use case. Further, We need your confirmation if this is no longer an issue from your end then we can move ahead and mark the issue status to close.

**Comment by onuralpszr** [comment]
Sure we can close this issue, and I will raise a new one when it is required. Thank you.
