### ISSUE TITLE
Question: How to understand the output of face_landmark_with_attention.tflite

### ISSUE THREAD

**Issue by wwdok** [google/mediapipe#3253]
face_landmark_with_attention.tflite has following output:
![image](https://user-images.githubusercontent.com/43233772/162772446-ef31cc01-b1ab-4553-8884-28ef204b4e32.png)
Does the `output_mesh_identity` with shape [1,1,1,1404] contains 468 3d coordinates(because 1404 = 468*3)
,and these 468 3d points already contains coordiantes of lips and eye  ? The individual output of `output_lips` `output_left_eye` `output_right_eye` just refine the 2d coordinates of lips and eye ? In python API, it output 478 landmarks, the lips and eye part inside these 478 landmarks come from `output_mesh_identity` or `output_lips` `output_left_eye` `output_right_eye` ? The `output_left_iris` and `output_right_iris` only have 2d coordiantes that do not have z-axis coordiante ? Thanks !

**Comment by a-pipi** [comment]
I am facing the same problem. Do you know how to interpret the output? @wwdok

**Comment by kuaashish** [comment]
Hello @wwdok,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
