### ISSUE TITLE
How to build a c++ static library in ubuntu?

### ISSUE THREAD

**Issue by Kami-chanw** [google/mediapipe#3254]
I am trying to interact c++ and python. I plan to use c++ to collect the hand landmarks and then pass the data to python via ROS. I don't know how to complie ROS with bazel, so I decide to complie mediapipe to a static library. Here is what my code looks like.
```
...
using op_type = void (*)(std::pair<float, float>&, std::pair<float, float>&,
                         std::pair<float, float>&, std::pair<float, float>&);

absl::Status RunMPPGraph(op_type operation) {
...
}
int mediapipe_main(int argc, char **argv, op_type operation) {
...
}
...
```
Here are my steps:

1. I added `linkstate = True` to BUILD files which are in `mediapipe/examples/desktop` and `mediapipe/examples/desktop/hand_tracking` respectively. 
2. I ran bazel by `bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11   mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
`
Then, it showed 
```
ERROR: /home/mediapipe/mediapipe/examples/desktop/hand_tracking/BUILD:36:10: Linking mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o:function _start: error: undefined reference to 'main'
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
```

I wonder that
1. How to deal with this problme?
2. Are there any other solutions to solve the problem of interacting c++ and python on realtime?

**Comment by sureshdagooglecom** [comment]
Hi @Kami-chanw ,
Please check MediaPipe official [document](https://google.github.io/mediapipe/getting_started/install.html) to buld MediaPipe on ubuntu.
