### ISSUE TITLE
The definition of hand’s approximate geometric center

### ISSUE THREAD

**Issue by IDownToEarth** [google/mediapipe#3255]
Please provide a link to the documentation entry, for example: https://google.github.io/mediapipe/solutions/hands.html#multi_hand_world_landmarks

## Description of issue (what needs changing):
Could you please give more information about the definition of hand's approximate geometric center? I couldn't quiet understand this origin of coordinate system. If there are some picture to describe it will be better

Kinds of documentation problems:

### Clear description

For example, why should someone use this method? How is it useful?
Knowing the origin of gesture's coordinate is important when we use the gesture skeletion ouput. But if I don't know the definition of hand's approximate geometric center, I don't know the coordinate of the gesture in world coordinate also.

**Comment by sureshdagooglecom** [comment]
Hi @IDownToEarth ,
"multi_hand_world_landmarks" field contains the hand landmarks on each detected hand in real-world 3D coordinates which is in meters with the origin at the hand's approximate geometric center. Could you please check with the latest version.

**Comment by IDownToEarth** [comment]
![image](https://user-images.githubusercontent.com/32896542/162910928-60041605-981e-4495-971e-6f1906d87c91.png)
I just find this part do some description, but I am still confused with the hand's approximate geometric center, I still not know the origin of the coordinate system.
Another person also has the same question.
https://groups.google.com/g/mediapipe/c/lrcaVbeI7h4

**Comment by kuaashish** [comment]
Hello @IDownToEarth,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
