### ISSUE TITLE
[hands] - Reverse hand side annotation

### ISSUE THREAD

**Issue by LucasFernandesBrazil** [google/mediapipe#3256]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code
- OS Platform and Distribution: Windows 10
- Version 0.8.9
- Solution: Hands
- Programming in Kotlin v1.6.20

I'm using the back camera. The hand side annotations should be correct, same as the model used on the front camera.

However, the notes being made on the screen are informing the wrong side of the hand, that is, the inverted side.

**Comment by sureshdagooglecom** [comment]
Hi @LucasFernandesBrazil ,
Could you please share any reference videos to investigate further on this issue.

**Comment by LucasFernandesBrazil** [comment]
Hi @sureshdagooglecom ,
Here is a video demonstrating the problem:

https://user-images.githubusercontent.com/62476878/163173296-6414970d-ac06-4ebf-ad4f-bf07aeb1da53.mp4

**Comment by homuler** [comment]
https://google.github.io/mediapipe/solutions/hands.html#multi_handedness

> Note that handedness is determined assuming the input image is mirrored, i.e., taken with a front-facing/selfie camera with images flipped horizontally. If it is not the case, please swap the handedness output in the application.

When you use the back camera, you should flip the image vertically, or swap the handedness output.

**Comment by LucasFernandesBrazil** [comment]
@homuler ,
When flipping the image vertically, the text is also flipped:
<img height="600em" src="https://user-images.githubusercontent.com/62476878/163194704-a65ab23f-bf7a-451c-ba03-77808c6ea32e.png" />

**Comment by LucasFernandesBrazil** [comment]
Thank you so much @homuler !

**Comment by LucasFernandesBrazil** [comment]
> @LucasFernandesBrazil
> 
> Como inverter a imagem de entrada horizontalmente no lado do Android?

Sorry, could you elaborate more on your question?
