### ISSUE TITLE
APP excute on CPU instead of CPU  when run the opengl version

### ISSUE THREAD

**Issue by BobDLA** [google/mediapipe#3258]
I run the hand tracking demo in docker follow the documents. 
  docker build --tag=mediapipe .
  docker run -it --name mediapipe  -e NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics   --privileged --gpus all  -v /dev/video0:/dev/video0   -v /dev/bus/usb:/dev/bus/usb -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=":0.0"  --cap-add=SYS_PTRACE --security-opt seccomp=unconfined   mediapipe:latest

  apt-get install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev
  apt-get install mesa-utils
  glxinfo | grep -i opengl

// opengl info 
        OpenGL vendor string: NVIDIA Corporation
        OpenGL renderer string: GeForce RTX 2060/PCIe/SSE2
        OpenGL core profile version string: 4.6.0 NVIDIA 460.39
        OpenGL core profile shading language version string: 4.60 NVIDIA
        OpenGL core profile context flags: (none)
        OpenGL core profile profile mask: core profile
        OpenGL core profile extensions:
        OpenGL version string: 4.6.0 NVIDIA 460.39
        OpenGL shading language version string: 4.60 NVIDIA
        OpenGL context flags: (none)
        OpenGL profile mask: (none)
        OpenGL extensions:
        OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 460.39
        OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
        OpenGL ES profile extensions:

I build the GPU version by 
   bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
      mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
And start the app by 
  GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu   --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live_gpu.pbtxt

Got log as
      I20220413 02:37:27.933243  9500 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
      I20220413 02:37:27.936308  9500 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
      libEGL warning: DRI2: failed to authenticate
      I20220413 02:37:27.965591  9500 gl_context_egl.cc:162] Successfully initialized EGL. Major : 1 Minor: 4
      I20220413 02:37:27.969861  9520 gl_context.cc:334] GL version: 3.1 (OpenGL ES 3.1 Mesa 20.0.8)
      I20220413 02:37:27.969961  9500 demo_run_graph_main_gpu.cc:68] Initialize the camera or load the video.
      
      (MediaPipe:9500): dbind-WARNING **: 02:37:28.197: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-AZ0K9rkchm: Connection refused
      Gtk-Message: 02:37:28.217: Failed to load module "canberra-gtk-module"
      Gtk-Message: 02:37:28.218: Failed to load module "canberra-gtk-module"
      I20220413 02:37:28.275028  9500 demo_run_graph_main_gpu.cc:89] Start running the calculator graph.
      I20220413 02:37:28.278831  9500 demo_run_graph_main_gpu.cc:94] Start grabbing and processing frames.
      INFO: Created TensorFlow Lite delegate for GPU.

The App could run, but very slow, about 1S/frame.
The CPU% is high , used by hand_tracking_gpu app. And 
nvidia-smi shows not assign memroy and usage to the app.

So, the app should be still run on CPU instead of GPU, I think. 
Could you check what's the problem?

Thanks

**Comment by sureshdagooglecom** [comment]
Hi @BobDLA ,
Could you please provide steps to reproduce this issue.

**Comment by BobDLA** [comment]
> 
my sytstem
  ubuntu  with nvidia 2060 GPU driver = 460.39
repeat by below steps:
   git clone https://github.com/google/mediapipe.git
   docker build --tag=mediapipe .
   docker run -it --name mediapipe -e NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics --privileged --gpus all -v /dev/video0:/dev/video0 -v /dev/bus/usb:/dev/bus/usb -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=":0.0" --cap-add=SYS_PTRACE --security-opt seccomp=unconfined mediapipe:latest

in the docker, run below command
   apt-get install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev
   apt-get install mesa-utils
   glxinfo | grep -i opengl
   bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11
mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live_gpu.pbtxt

And then use htop and nvidia-smi to check if the app is running on GPU.

**Comment by sureshdagooglecom** [comment]
Hi @BobDLA ,
Could you share which version of openGL you are using.

**Comment by BobDLA** [comment]
OpenGL version string: 4.6.0 NVIDIA 460.39
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 460.39
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

> Hi @BobDLA , Could you share which version of openGL you are using.

**Comment by sureshdagooglecom** [comment]
Hi @BobDLA ,
 OpenglES 2.0 is not supported. Should try with 3.0 . Refer [this](https://google.github.io/mediapipe/getting_started/gpu_support.html#opengl-es-support) document for more information.

**Comment by Gaozhongpai** [comment]
@BobDLA Any updates on this? I have the same problem

**Comment by kuaashish** [comment]
Hello @BobDLA,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
