### ISSUE TITLE
Get 2D Bounding Box from ssdlite_object_detection.tflite

### ISSUE THREAD

**Issue by nargeshn** [google/mediapipe#3259]
Hi MediaPipe team,

I am trying to use "ssdlite_object_detection.tflite" to get the 2D object detection. The raw output includes 2034 detected bounding boxes for every input image. Previously, I used "Tensorflow.image.combined_non_max_suppression" and I did not get reasonable bounding boxes. Then I found "object_detection_cpu.pbtxt" which includes the whole pipeline which is used by MediaPipe for 2D object detection. 
Now my question is that what are my options to get the correct bounding boxes when I am separately using the tflite model rather than the MediaPipe?

**Comment by sureshdagooglecom** [comment]
Hi @nargeshn ,
This issue is related to Tensorflow lite without Mediapipe , we don't support for Tensorflow lite without Mediapipe.
