### ISSUE TITLE
MediaPipe-0.8.9 using tulsi to generate xcode project failed

### ISSUE THREAD

**Issue by shuishou13** [google/mediapipe#3260]
bazel's version 5.1.0
bazel's examples use tulsi to generate ios-app xcode project success and can run

![image](https://user-images.githubusercontent.com/17842877/163118584-cda2c1e1-5e44-481d-a0e4-423efc682125.png)
![image](https://user-images.githubusercontent.com/17842877/163118605-f4e8fbea-6fbe-4c7d-a35d-b78d9c18c068.png)
![image](https://user-images.githubusercontent.com/17842877/163118626-4a7a935d-e160-44d0-8f7c-bd7a3ca88552.png)

**Comment by sureshdagooglecom** [comment]
Hi @shuishou13 ,
Could you provide steps to reproduce this issue.
