### ISSUE TITLE
Is there a Rotation Matrix Returned for FaceMesh?

### ISSUE THREAD

**Issue by hockinsk** [google/mediapipe#3261]
I've seen some discussion here, but no real solution? I'm currently getting Rotation Matrix of a matched face mesh, by passing the coordinates from mediapipe to cv2 e.g.
```
                # Use solvePnP function to get rotation vector
                success, rotation_vec, transition_vec = cv2.solvePnP(
                    face_coordination_in_real_world, face_coordination_in_image,
                    cam_matrix, dist_matrix)
```
Is there a way to get these (or even Euler angles) from mediapipe instead? I can't seem to find any way of doing it?

**Comment by sureshdagooglecom** [comment]
Hi @hockinsk ,
Could you please elaborate w.r.t above issue.

**Comment by hockinsk** [comment]
> 

Sure. So when you get returned the mapped facemesh xyz landmark results there appears to be no further mediapipe solution to get the overall angle of the face/head. ie no yaw, pitch and roll angle or even just a rotation matrix of the of the 468 xyz points as a whole. The way to get the yaw, pitch and roll of the mesh result it to use Open CV's solvePnP and passing it the points to get the rotation matrix needed to calculate yaw, pitch and roll, head angle etc etc. Just wondered if there was a way, or if such a feature could be added. Context is here in a little video using mediapipe to control a 3D panning application i'm working on.
https://www.youtube.com/watch?v=NedYjfX0dOY

**Comment by wongfei** [comment]
@hockinsk this one? https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/face_geometry.proto#L59

**Comment by isdito** [comment]
Hello, There are any solution??? to retrieve yaw, pitch and roll of the mesh

**Comment by fengyun21** [comment]
Hello, There are any solution??? to retrieve yaw, pitch and roll of the mesh

**Comment by hockinsk** [comment]
@isdito @fengyun21 there are no built in functions to return YPR. In the end I used solvePnP to get a rotation vector from the facemesh result via a Rodrigues function to convert that rotation vector to a matrix and then convert the rotation matrix Euler.

**Comment by fengyun21** [comment]
> @isdito @fengyun21 there are no built in functions to return YPR. In the end I used solvePnP to get a rotation vector from the facemesh result via a Rodrigues function to convert that rotation vector to a matrix and then convert the rotation matrix Euler.

thanks very much

**Comment by hockinsk** [comment]
> 

I think that's just the matched 468 geometry points matrix. There's no way to work out (using mediapipe) what the overall facemesh angle is as I can see in that code.

**Comment by lohoopiggy** [comment]
> > @isdito @fengyun21 there are no built in functions to return YPR. In the end I used solvePnP to get a rotation vector from the facemesh result via a Rodrigues function to convert that rotation vector to a matrix and then convert the rotation matrix Euler.
> 
> thanks very much

I met this trouble,too. Can you share your method? I want to use for reference. Thanks a lot.

**Comment by se7enXF** [comment]
The same issue. 

I try to use center of earRight and earLeft as head center position. Use vector from headTop to jawBottom to calculate angleZ and angleX, use vector from eyeRightSide to eyeLeftSide to calculate angleY. Use distance from headTop to jawBottom to calculate scale. The approximate result is correct. The larger the rotation angle, the greater the error.  The boundary value of the origin angle changes severely, which means that when the face is facing forward, a slight movement will cause the angle to swing violently around 0. 

Here is my code in Unity: 

```c#
// faceData is 468 points landmark in screen location
public void SetHeadPosition(Vector3[] faceData)
    {
        const int earRightIndex = 234;
        const int earLeftIndex = 454;
        var earRight = faceData[earRightIndex];
        var earLeft = faceData[earLeftIndex];
        var center = (earRight + earLeft) / 2;
        headModel.transform.position = new Vector3(center.x, center.y, headZ);
    }

public void SetHeadRotation(Vector3[] faceData)
    {

        const int headTopIndex = 10;
        const int jawBottomIndex = 152;
        var from = Vector3.up;
        var to = faceData[headTopIndex] - faceData[jawBottomIndex];
        float angleZ = Vector3.SignedAngle(from, to, Vector3.back);

        from = Vector3.up;
        float angleX = Vector3.SignedAngle(from, to, Vector3.left);

        const int eyeRightSide = 33; 
        const int eyeLeftSide = 263;
        from = Vector3.left;
        to = faceData[eyeRightSide] - faceData[eyeLeftSide];
        float angleY = Vector3.SignedAngle(from, to, Vector3.up);

        headModel.transform.rotation = Quaternion.Euler(angleX, angleY, angleZ);
    }

public void SetHeadScale(Vector3[] faceData)
    {
        const int headTopIndex = 10;
        const int jawBottomIndex = 152;
        const float ratio = 6.5f;  // Tested experience value
        var distance = Vector3.Distance(faceData[headTopIndex], faceData[jawBottomIndex]);
        headModel.transform.localScale = distance * ratio * Vector3.one;
    }
```

As the result is not good, I will try to write the method in [MeFaMo](https://github.com/JimWest/MeFaMo/blob/main/mefamo/custom/face_geometry.py) into c#. It's hard to say what the result is.

**Comment by kuaashish** [comment]
@hockinsk,

Are you still looking for resolution on this issue? Our MP Tasks face landmarker contains rotation matrix.

**Comment by narendraadloid** [comment]
> @hockinsk,
> 
> Are you still looking for a resolution on this issue? Our MP Tasks face landmarker contains rotation matrix.

How can I get yaw, roll, and pitch out of this 4*4 transformation matrix? I have seen that the 4*4 matrix contains rotation matrix, scale and change in position. How do I get Scale, Yaw, Roll, Pitch and Position from that matrix? Any help is appreciated!!!

**Comment by Konstantysz** [comment]
> > @hockinsk,
> > Are you still looking for a resolution on this issue? Our MP Tasks face landmarker contains rotation matrix.
> 
> How can I get yaw, roll, and pitch out of this 4x4 transformation matrix? I have seen that the 4x4 matrix contains a rotation matrix, scale and change in position. How do I get Scale, Yaw, Roll, Pitch and Position from that matrix? I am using Babylon JS as rendering engine
> 
> Any help is appreciated!!! 🙏🙏🙏

If you still need help, [here](https://github.com/matthew-brett/transforms3d/blob/main/transforms3d/affines.py#L10C5-L153) is implementation of the decomposition of the 4x4 transformation matrix.
