### ISSUE TITLE
Improve KNIFT documentation

### ISSUE THREAD

**Issue by bergwerf** [google/mediapipe#3263]
## URL with the issue

https://github.com/google/mediapipe/blob/master/docs/solutions/knift.md

## Description of issue

It is not clear from the documentation if it is possible to use the KNIFT models for your own applications, and how to do this. Although https://github.com/google/mediapipe/blob/master/README.md mentions that KNIFT is only available on Android, I could not find any code examples.

The article at https://developers.googleblog.com/2020/04/mediapipe-knift-template-based-feature-matching.html does clarify the internal mechanism a bit. Since both `FeatureDetectorCalculator` and `BoxDetectorCalculator` are implemented in C++, I imagine it should be perfectly possible to run the procedure on Linux (we want to use this for server-side processing).

Some clarification on how to use the KNIFT models on Linux would be very helpful :).

**Comment by sureshdagooglecom** [comment]
Hi @bergwerf ,
Please check [this](https://google.github.io/mediapipe/solutions/knift) official document for code examples of KNIFT in android.

**Comment by bergwerf** [comment]
That is the same document as the one I mentioned. There are no code examples, only build instructions. I looked through the repository to find Android code but I couldn't find any. The build instructions mention https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/examples/android/src/java/com/google/mediapipe/apps/templatematchingcpu/BUILD

**Comment by ayushgdev** [comment]
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

If you use legacy KNIFT solution, you will need to create an AAR file as per the documentation [here](https://developers.google.com/mediapipe/framework/getting_started/android_archive_library) and the target [here](https://google.github.io/mediapipe/solutions/knift#matching-us-dollar-bills)
