### ISSUE TITLE
Getting results.segmentationMask undefined in Holistic mediaPipe

### ISSUE THREAD

**Issue by robindra** [google/mediapipe#3265]
Hi Team, 

As per subject line, I am trying to call holistic.send({image: videoElement}) through window.requestAnimationFrame. As I want to avoid using the Camera because I want to control the camera stream. 

Code in the example which is running perfectly: 
const camera = new Camera(videoElement, {
  onFrame: async () => {
    await holistic.send({image: videoElement});
  },
  width: 720,
  height: 405
});
camera.start();

Now, I modify the code by accessing the camera through getUserMedia and inside the success I set the media stream to the video element and use window.requestAnimationFrame to call holistic.send method. 

navigator.mediaDevices.getUserMedia({video: {width: 720, height: 405}).then((mediaStream) => {
	videoElement.srcObject = null;
	videoElement.srcObject = mediaStream;	
	window.requestAnimationFrame(runVideo);
}).catch((error) => {
	console.log(error)
});

async function  runVideo() {
 await holistic.send({image: videoElement}); 
 window.requestAnimationFrame(runVideo);
}

![image](https://user-images.githubusercontent.com/8190084/163545815-30e475ef-f558-4b34-824b-4b5ea566b1d0.png)

![image](https://user-images.githubusercontent.com/8190084/163545554-73df2f81-08ca-4f2f-a37c-d50283594386.png)

Is it mandatory to use the Camera instance to use the holitic.send method? I tried the same way for "MediaPipe Selfie Segmentation" of getting stream through getUserMedia and its working as expected but getting issue with holistic example. 

Can you please check and share your input on the same?

Code: 
https://plnkr.co/edit/BHGNNiWX9lq538uK

**Comment by kuaashish** [comment]
Hello @robindra,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
