### ISSUE TITLE
Face Mesh AR?

### ISSUE THREAD

**Issue by I1amok** [google/mediapipe#3270]
I want to know how to achieve THE AR effects in the 3D face example?
I only see picture 1, but I can't find the relevant implementation method

**Comment by sureshdagooglecom** [comment]
Hi @I1amok ,
Please check [this](https://google.github.io/mediapipe/solutions/face_detection.html#:~:text=camera.start()%3B%0A%3C/script%3E-,Android%20Solution%20API,-Please%20first%20follow) code implementation for android face solutions.

**Comment by I1amok** [comment]
> Hi @I1amok ,
> Please check [this](https://google.github.io/mediapipe/solutions/face_detection.html#:~:text=camera.start()%3B%0A%3C/script%3E-,Android%20Solution%20API,-Please%20first%20follow) code implementation for android face solutions.

I appreciate your concern, but my problem is not face detection.  how to achieve the AR effect in face Mesh?

**Comment by sureshdagooglecom** [comment]
Hi @I1amok ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/1889.

**Comment by I1amok** [comment]
> Hi @I1amok ,
> Did you get a chance to check this closed issue #1889.

ok,Thank you again for your concern
