### ISSUE TITLE
Process multiple images in one run instead of using for loop 

### ISSUE THREAD

**Issue by sid0913** [google/mediapipe#3273]
- stock script from Mediapipe for now:
- Linux:
- MediaPipe 0.8.9.1(https://github.com/google/mediapipe/releases):
- Face Mesh:
- Python):

I want to know if it is possible to send in multiple frames and have it processed in one run of the neural net instead of using a for loop and passing one image at a time

**Comment by sureshdagooglecom** [comment]
Hi @sid0913 ,
Could you please elaborate w.r.t above issue to investigate further.

**Comment by sid0913** [comment]
Currently, to process a set of landmarks for a set of images we use :

for idx, file in enumerate(IMAGE_FILES)

Where IMAGE_FILES is an array of the image file paths

in the code presented on the instruction page for mediapipe: [tutorial](https://google.github.io/mediapipe/solutions/face_mesh#face-landmark-model)

Instead of this I want to import all the images as np arrays and cluster them as a tensor- (N,L,W,3) shape where L is the length of the image and W is the width and N is the number of images I want to pass to the neural net. 

I want to know how I can pass this whole tensor directly through mediapipe's neural net to get a tensor with all the N images' landmarks in one go. This avoids the for loop and is much more efficient for my use case.

**Comment by sid0913** [comment]
Any updates on this?

**Comment by sureshdagooglecom** [comment]
Hi @sid0913 ,
Could you provide your code changes to investigate further on this issue.

**Comment by MaxInnerCircle** [comment]
Also interested in some method of processing multiple images at once, instead of looping through the images one at a time like this:

```py
import cv2  
import mediapipe as mp

mp_face_detection = mp.solutions.face_detection
face_detection = mp_face_detection.FaceDetection(model_selection=1, min_detection_confidence=0.5)

for image in directory:
  img = cv2.imread(image)
  rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  
  result = face_detection.process(rgb)

  if result.detections:
    print('face')
  else:
    print('no face')
```

**Comment by sid0913** [comment]
+1

**Comment by MaxInnerCircle** [comment]
> Any updates on this? It would be really useful a way to do a batch inference instead of doing a for loop

Hey, I managed to come up with something using the [multiprocessing module](https://docs.python.org/3/library/multiprocessing.html), here is a simplified version of it:

```py
from multiprocessing import get_context, TimeoutError

def image_processor_function(photo):
    # Process photo and return prediction
    return str(photo) + ' > 1/0'

def multiprocess_photos(photos: list, pool_size: int):
    # Create nested lists, each list is N long
    photos_nested = [list(i) for i in zip(*(iter(photos),) * pool_size)]
    photos_nested.append(photos[-(len( photos ) % pool_size):])
    
    predictions = []

    with get_context("spawn").Pool(processes=pool_size) as pool:
        for photo_list in photos_nested:
            multiple_results = [pool.apply_async( image_processor_function, (photo,)) for photo in photo_list]

            try:
                for result in multiple_results:
                    # Do something with the results
                    predictions.extend( [result.get(timeout=(5*pool_size))] )
            except TimeoutError:
                # Handle timeout errors
                print('timeout')

    return predictions

if __name__ == '__main__':  
    print( multiprocess_photos(['photo1', 'photo2', 'photo3', 'photo4', 'photo5'], 2) )
```
