### ISSUE TITLE
How to build a AAR content "solutions/facemesh" and "modules/facegeometry"

### ISSUE THREAD

**Issue by Coloryr** [google/mediapipe#3274]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution :Linux Ubuntu 20.04, Android 11
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):gcc
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):Java
- [MediaPipe version](https://github.com/google/mediapipe/releases):latest.release
- Bazel version:5.0.0
- Android SDK and NDK versions (if android):31 21n

**Describe the problem**:
I try use this `BUILD` file to build a aar,
but not content solutions file.
```
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_face_effect",
    calculators = [
    "//mediapipe/graphs/face_effect:face_effect_gpu_deps",
    "//mediapipe/graphs/face_mesh:mobile_calculators"
    ],
)
```

**Comment by Coloryr** [comment]
I want to get face mash and head pitch/yaw/roll.

**Comment by kuaashish** [comment]
Hello @Coloryr,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
