### ISSUE TITLE
Windows Installation does not work due to wrong environment variables Windows 10

### ISSUE THREAD

**Issue by steven5clu884** [google/mediapipe#3276]
The directions for installation on Windows 10 are faulty
# Please find the exact paths and version numbers from your local version.
C:\> set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
C:\> set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
C:\> set BAZEL_VC_FULL_VERSION=<Your local VC version>
C:\> set BAZEL_WINSDK_FULL_VERSION=<Your local WinSDK version>

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools DOES NOT EXIST, and there is no indication what exe, dll, bat or file you are requiring

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC DOES NOT EXIST and there is no indication what .exe, dll, bat of ile you are requiring

<Your local VC version> what file are you looking for devenv.exe , devenv.com, VsGA.exe , and other exe and if I have installed studio 2022 there are even more choices to make

<Your local WinSDK version> again what files are you looking for ??? h files, cpp files, lib files ???

       Machine Id: {ABBFCD85-FB5D-46EF-8D13-E99E5C534181}
         Operating System: Windows 10 Enterprise 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
                 Language: English (Regional Setting: English)
      System Manufacturer: Dell Inc.
             System Model: XPS 8930
                     BIOS: 1.0.12 (type: UEFI)
                Processor: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 CPUs), ~3.2GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16192MB RAM
                Page File: 16187MB used, 5379MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12

Tried to follow installation instructions here
https://google.github.io/mediapipe/getting_started/install.html

I have visual studio 2019 and 2022 installed on my Windows 10 System

**Comment by andrechen** [comment]
If you have hard time with bazel build (and willing to pull some third party libraries), an easy visual studio 2019 solution with few selected examples is here. check it out...
https://github.com/andrechen/mediapipe/tree/master/visualstudio

**Comment by sureshdagooglecom** [comment]
Hi @steven5clu884 ,
Please check out [this](https://github.com/andrechen/mediapipe/tree/master/visualstudio) for more information for installation.
