### ISSUE TITLE
Hand Tracking - Can I know the output type of the network in use ? 

### ISSUE THREAD

**Issue by moonchildz** [google/mediapipe#3279]
I understand that the output of the solution becomes 3 x 21 0~1 coordinate values. 

I am studying the hand detection deep learning methods and I want to know the output of the NETWORK of palm detection - hand detection model. 

I guess the w x h x 21 heatmap is the output of the network. Can you please tell me I am guessing right or what I am missing ?

**Comment by sureshdagooglecom** [comment]
Hi @moonchildz ,
21 3D landmarks for hand detection, could you please elaborate w.r.t above issue.

**Comment by moonchildz** [comment]
@sureshdagooglecom 
Thanks for reply. Are 21 3D coordinate values come directly from the dense layer, or calculated from w x h heatmap-like layers? Inferring from the paper I saw that it resizes all image to 256 x 256 and I want to know that how the mediapipe.hand responds to an arbitrary image size.

**Comment by sureshdagooglecom** [comment]
Hi @

**Comment by sureshdagooglecom** [comment]
Hi @moonchildz ,
 21 3D coordinate values are calculated from heatmap layers, please refer MediaPipe documentation for more information.
