### ISSUE TITLE
Is there any special reason why OpenGL is used instead of OpenCL for GPU operations in all the calculators?

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#328]
I am just curious about the design choice, which may help me to decide on my own design choice.

**Comment by yxchng** [comment]
Ok. Apparently it is already explained here:

![Selection_001](https://user-images.githubusercontent.com/10518587/71097717-65f7ef00-21eb-11ea-8a78-fccbbfd05ef6.png)

It is because more devices support OpenGL than OpenCL.

**Comment by mcclanahoochie** [comment]
You are correct: on mobile(ios/androd) OpenGL is _currently_ more available than OpenCL.

< my option >
Otherwise, if you are targeting non-android/ios devices (laptop/desktop/raspberrypi/etc.), then OpenCL _could_ be more compatible because OpenCL doesn't require a GPU to run. 
< / my option >

**Comment by rajhlinux** [comment]
Is it possible I can use MediaPipe using OpenCL? I ask because I have an AMD Radeon GPU running in FreeBSD 13.1. So far FreeBSD does not seem to have OpenGL ES 3.1 and only have version 2.
