### ISSUE TITLE
Face Mesh fail when enableFaceGeometry: true, Javascript

### ISSUE THREAD

**Issue by ZeroLu** [google/mediapipe#3280]
**System information**
- Any web browser would have this bug.

**Describe the current behavior:**
When using the [MediaPipe - Facemesh](https://codepen.io/mediapipe/pen/KKgVaPJ?editors=0011) on codepen, if I change the enableFaceGeometry to false in code( line 61), and tap the GUI to change the "Refine Landmarks" to yes. The app would stop working and throw errors.

**Describe the expected behavior:**
The refine landmark should still work even when enableFaceGeometry is set to true. The refine landmark should work with different number of facial landmarks.

**My understanding:**
When refine landmarks was set to true, additional landmarks will be created, like the Iris etc. Apparently, this change would cause FaceGeometry to fail. But it shouldn't work this way, right? I want to **use refine landmarks and face geometry simultaneously** in my app.

> Please help!! We want to release this app soon!

**Standalone code to reproduce the issue:**
1. Go to https://codepen.io/mediapipe/pen/KKgVaPJ?editors=0011
2. Do the following:
<img width="670" alt="face mesh fail" src="https://user-images.githubusercontent.com/7347148/164957816-7255fb27-5007-4c37-a0fc-1c86e451de49.png">

**Other info / Complete Logs :**
The logs from console:
`"I0424 13:11:13.001000       1 gl_context_webgl.cc:169] Successfully destroyed WebGL context with handle 3"
"I0424 13:11:13.005000       1 gl_context_webgl.cc:151] Successfully created a WebGL context with major version 3 and handle 3209"
"I0424 13:11:13.008000       1 gl_context.cc:351] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)))"
"E0424 13:11:14.206000       1 geometry_pipeline.cc:128] generic::internal: RET_CHECK failure (third_party/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc:128) screen_landmark_list.landmark_size() == canonical_metric_landmarks_.cols() (478 vs. 468) The number of landmarks doesn't match the number passed upon initialization!"
"Stack trace:"
""
"E0424 13:11:14.207000       1 calculator_graph.cc:810] INTERNAL: CalculatorGraph::Run() failed in Run: "
"Calculator::Process() for node 'facegeometryfromlandmarksandimage__FaceGeometryPipelineCalculator' failed: RET_CHECK failure (third_party/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc:128) screen_landmark_list.landmark_size() == canonical_metric_landmarks_.cols() (478 vs. 468) The number of landmarks doesn't match the number passed upon initialization!; Failed to convert landmarks from the screen to the metric space!; Failed to estimate face geometry for multiple faces! [type.googleapis.com/mediapipe.StatusList='\n\xeb\x03\x08\r\x12\xe6\x03\x43\x61lculator::Process() for node \'facegeometryfromlandmarksandimage__FaceGeometryPipelineCalculator\' failed: RET_CHECK failure (third_party/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc:128) screen_landmark_list.landmark_size() == canonical_metric_landmarks_.cols() (478 vs. 468) The number of landmarks doesn\'t match the number passed upon initialization!; Failed to convert landmarks from the screen to the metric space!; Failed to estimate face geometry for multiple faces!']"
"=== Source Location Trace: ==="
"third_party/mediapipe/framework/tool/status_util.cc:139"
""
"F0424 13:11:14.207000       1 solutions_wasm.embind.cc:679] Check failed: absl::OkStatus() == ::util::status_internal::AsStatus((graph_->WaitUntilIdle())) (OK vs. INTERNAL: CalculatorGraph::Run() failed in Run: "
"Calculator::Process() for node 'facegeometryfromlandmarksandimage__FaceGeometryPipelineCalculator' failed: RET_CHECK failure (third_party/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc:128) screen_landmark_list.landmark_size() == canonical_metric_landmarks_.cols() (478 vs. 468) The number of landmarks doesn't match the number passed upon initialization!; Failed to convert landmarks from the screen to the metric space!; Failed to estimate face geometry for multiple faces! [type.googleapis.com/mediapipe.StatusList='\n\xeb\x03\x08\r\x12\xe6\x03\x43\x61lculator::Process() for node \'facegeometryfromlandmarksandimage__FaceGeometryPipelineCalculator\' failed: RET_CHECK failure (third_party/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc:128) screen_landmark_list.landmark_size() == canonical_metric_landmarks_.cols() (478 vs. 468) The number of landmarks doesn\'t match the number passed upon initialization!; Failed to convert landmarks from the screen to the metric space!; Failed to estimate face geometry for multiple faces!']"
"=== Source Location Trace: ==="
"third_party/mediapipe/framework/tool/status_util.cc:139"
") "
"*** Check failure stack trace: ***"
"undefined"`

**Comment by ZeroLu** [comment]
Anyone? @sureshdagooglecom

**Comment by sureshdagooglecom** [comment]
Hi @ZeroLu ,
The CodePen does not crash if you enable face geometry and DON'T enable mesh refinements. So you can experiment with one or the other, but not both.

**Comment by ZeroLu** [comment]
Hi @sureshdagooglecom ,

In my application, I need to use both face geometry and landmark refinement. Is that possible to achieve? Basically I want to create an Animoji like experience with media pipe, where you can control the expression of an avatar.

**Comment by tyrmullen** [comment]
Unfortunately, currently you can only use one or the other, but not both simultaneously.  The next update to FaceMesh should contain the fix for this, but there is no ETA yet for that.  See related issues #2988 and #3003.

**Comment by ZeroLu** [comment]
Hi @tyrmullen ,

Thanks for clarifying!  I have to use refine landmark in my app. But I only need faceGeometry to get the rotation and position of the face, nothing else. Is it possible to get the rotation and position of the face with the face landmark data?
