### ISSUE TITLE
Preprocessing video dataset. Using Mediapipe Pose solution.

### ISSUE THREAD

**Issue by Dilipraj6** [google/mediapipe#3282]
Hello,

I don't know if we can ask general questions here but I'm giving it a go. Please close this if its not relevant.

I'm using Windows, Jupyter notebook, Mediapipe to collect keypoints, tensorflow, keras.

I am doing an action recognition task and I have a dataset with videos. I used Mediapipe to collect the keypoints through webcam. And now stuck at preprocessing the video dataset. So my question is:

--There are so many methods we use for video classification. One being Pose detection(using the keypoints of our body). Where can we learn about this specific method? Any websites, books, blogs, please let me know.

--Learning the theory is one and learning the code is another. Where can I find the basic syntax code for this particular method?

Any answer would be really appreciated.

Thank you.

**Comment by sureshdagooglecom** [comment]
Hi @Dilipraj6 ,
Please MediaPipe github [code](https://github.com/google/mediapipe) for your code reference.

**Comment by Dilipraj6** [comment]
Thanks for replying. I have checked the link which you've provided and I didn't find any code. I don't know if I checked at the right place in that link. Anyways, the thing is I have successfully got to a point where I can see the Mediapipe's landmarks and the drawings through my webcam. The actual help I need is for preprocessing my video dataset. I don't know how to do it. If you can help me in any way, that would be really good. It will help me a lot.

**Comment by sureshdagooglecom** [comment]
Hi @Dilipraj6 ,
Could you please refer [this](https://google.github.io/mediapipe/solutions/pose.html) for code and theoretical understanding on pose estimation.
