### ISSUE TITLE
Effect Renderer

### ISSUE THREAD

**Issue by saketh433** [google/mediapipe#3285]
<em>Please make sure that this is a feature request.</em>
I would like to render a 3d object over Mediapipe Landmarks. 
**System information** (Please provide as much relevant information as possible)
Using Jetson Nano
- MediaPipe Solution (you are using): Face Mesh
- Programming language : Python
- Are you willing to contribute it (Yes/No):
Yes
**Describe the feature and the current behavior/state:**
Right now, I am able to render a 2d image over Mediapipe Landmarks to give an illusion of a 3d effect.
**Will this change the current api? How?**
Yes, it would add a nice feature
**Who will benefit with this feature?**
Everyone who wants to use this feature
**Please specify the use cases for this feature:**
AR, VR
**Any Other info:**
None

**Comment by RuentGen** [comment]
I also want to render a 3d object over Mediapipe Landmarks.
System information (Please provide as much relevant information as possible)

MediaPipe Solution (you are using): Face Mesh
Programming language : JavaScript
Are you willing to contribute it (Yes/No):
Yes
Describe the feature and the current behavior/state:
Currently we are able to render 3D object using threejs 
Will this change the current api? How?
When would be the Effect Renderer will be available
Who will benefit with this feature?
Everyone who wants to use this feature
Please specify the use cases for this feature:
AR, VR
Any Other info:
None
