### ISSUE TITLE
Building MediaPipe on Android fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by fimo719** [google/mediapipe#3287]
Linux Ubuntu 20.04
- Bazel version: 5.0.0

I need help

I run this code
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

then I get this error

ERROR: /home/wen/mediapipe/WORKSPACE:417:23: fetching android_ndk_repository rule //external:androidndk: Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable must be set.
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable must be set.
INFO: Elapsed time: 0.262s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
igured)

How can I fix it

**Comment by fimo719** [comment]
Now, I delect WORKSPACE 417:23 android_ndk_repository(name = "androidndk") ,I get the new error.

ERROR: /home/wen/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/BUILD:35:15: While resolving toolchains for target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type

**Comment by sureshdagooglecom** [comment]
Hi @fimo719 .
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/854.

**Comment by fimo719** [comment]
HI @sureshdagooglecom 
I very thank you so much for answering me.
I will try that.

**Comment by sureshdagooglecom** [comment]
Hi @fimo719 ,
Closing this issue , if you have further issues please open this anytime.
