### ISSUE TITLE
Using frames from python script ( RealSense + MediaPipe )

### ISSUE THREAD

**Issue by iklemyshev** [google/mediapipe#3290]
Hello!
I'm just newbie to MediaPipe workflow, so I'm trying to figure out the possibility of using RealSense RGBD stream with MP solutions.

The problem is: I can only get rgb-frame and depth-frame from RealSense camera via RS SDK and librealsense in python script, like the others flow just in loop. Can the sink nodes of MP or some other method be the bridge to connect image frames from my script to MediaPipe graph solution?

Another side of the problem is that I'm using Jetson NX, and the only solution to use mediapipe with GPU support is to use it like here ( docker + bazel + mediapipe ): https://github.com/AndreV84/mediapipe

Please help me to understand of how to!

**Comment by sureshdagooglecom** [comment]
Hi @iklemyshev .
Could you provide more information to investigate further on this issue.

**Comment by Basuki74** [comment]
I want to continue with this question..

**Comment by kuaashish** [comment]
@iklemyshev,

Thanks for raising this request. However, We will be not supporting MediaPipe plus RealSense and feature is in not our roadmap.
