### ISSUE TITLE
Is it possible to save Mediapipe - Pose output?

### ISSUE THREAD

**Issue by AkhilaPerumalla123** [google/mediapipe#3291]
I am following "https://github.com/nicknochnack/MediaPipePoseEstimation" this tutorial for the Mediapipe pose estimate.
Is there any way to save Predicted Video output and predicted Landmarks?

**Comment by sureshdagooglecom** [comment]
Hi @AkhilaPerumalla123 ,
Did you get a chance to check this closed https://github.com/google/mediapipe/issues/2144.
