### ISSUE TITLE
how to get finger confidence or handedness in C++

### ISSUE THREAD

**Issue by dennishuang85** [google/mediapipe#3293]
Doing a research project for UE4 virtual avatar by using Mediapipe. However, the finger keypoints are not always accurate, and the detection result is not as good as official demo. My idea is try to get the confidence or handedness score to filter the bad dataset. But seems current code is not supported to provide confidence for each finger. Does anyone know how to solve this problem, or any better way to get the accurate keypoint data for all the fingers? Thank you

**Comment by sureshdagooglecom** [comment]
Hi @dennishuang85 ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/2072

**Comment by dennishuang85** [comment]
> Hi @dennishuang85 , Did you get a chance to check this closed issue #2072

Thank you for reply. I tried this one already. it seems only have confidence for the hands, doesn't include the confidence of fingers.

**Comment by sureshdagooglecom** [comment]
Hi @dennishuang85 ,
Please check this  https://github.com/google/mediapipe/issues/644#issuecomment-982705863 for fingers tracking on hands.

**Comment by dennishuang85** [comment]
> Hi @dennishuang85 , Please check this [#644 (comment)](https://github.com/google/mediapipe/issues/644#issuecomment-982705863) for fingers tracking on hands.

I tried it before. but it still cannot solve my problem. I can get the confidence score for palm, but not the fingers. The landmark of fingers are always detected, but not reliable. I would like to get confidence score to filter the "bad" dataset. I tried to use the palm confidence score for fingers, but the result was not good enough.

**Comment by sureshdagooglecom** [comment]
Hi @dennishuang85 ,
Unfortunately the landmark model is not trained to provide confidence scores.

**Comment by dennishuang85** [comment]
> Hi @dennishuang85 , Unfortunately the landmark model is not trained to provide confidence scores.

I realized that. Do you have any other method to get the confidence scores for the fingers?
