### ISSUE TITLE
[Hands] Recognition issues when the fingertip is facing the webcam.

### ISSUE THREAD

**Issue by noljajy** [google/mediapipe#3294]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): win0
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.9.1
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic) Hands
- Programming Language and version ( e.g. C++, Python, Java): Python3.9

**Describe the expected behavior:**
The Korean sign language Fingerspelling recognition test is being conducted using mediapipe and one web camera.
I would like to hear your opinion on how to improve some of the low recognition rates of fingerspelling.
The low recognition rate is when the fingertip faces the camera.
There are four types of fingerspelling.
Fingerspelling in the video is 'eo', 'ye', 'e', and 'ye' in order.
Does anyone know how to solve this problem?

https://tv.kakao.com/v/428320422

** I tested it as below.
1. Distance : close or far
2. Lighting : bright or dark
3. Background : simple or complexity

Please understand that I am not good at English.

**Comment by sureshdagooglecom** [comment]
Hi @noljajy ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/450.

**Comment by noljajy** [comment]
> Hi @noljajy , Did you get a chance to check this closed issue #450.

Thank you for your answer.
I will check the issue that you told me.

**Comment by noljajy** [comment]
> Hi @noljajy , Did you get a chance to check this closed issue #450.

I checked the issue you told me.
#450 Answers stated that they plan to release a significantly improved version with much better tracking soon.
Is the current Mediapipe an improved version?
Even though it is an improved version, is there a limit to distinguishing the fingertips?
Or are you conducting research and development to improve the tracking function?

**Comment by noljajy** [comment]
> Hi @noljajy , Did you get a chance to check this closed issue #450.
I checked the issue you told me.
There was no solution to the case where the fingertip faces the camera.
I solved some of this problem using two web cameras.
I want to solve it using one web camera, can you tell me the solution?

**Comment by noljajy** [comment]
Hi @sureshdagooglecom, thank you for your comment.

I checked the issue you told me.
There was no solution to the case where the fingertip faces the camera.
I solved some of this problem using two web cameras.
I want to solve it using one web camera, can you help me?

**Comment by sureshdagooglecom** [comment]
Hi @noljajy ,
Could you share any reference video w.r.t above issue.
