### ISSUE TITLE
tflite palm detection and hand landmark models

### ISSUE THREAD

**Issue by abucka** [google/mediapipe#3297]
Hello,

first of all I would like to thank for this great repository.

I have a question on how to use the palm_detection.tflite and hand_landmark.tflite to detect multiple hands in the image. I understand from the model card that the input images have to be resized to the size of 192x192 pixels and normalised to the range (0.0, 1.0). Unfortunately I am not sure how to post process the output from the palm_detection.tflite model. How to apply NMS algorithm in this case and how to pass it to the hand_landmark model?

I would be very grateful for some tips.

**Comment by sureshdagooglecom** [comment]
Hi @abucka .
On changing the  max_num_hands=3 will It be able to detect the other hands, try with these if you are still facing issues in adding it ,please share code changes to investigate further.

**Comment by abucka** [comment]
Hi @sureshdagooglecom, thank you for your answer. I just don't know which script I should use, I found hands.py but in this script the media pipe lib is used, I would like to use tflite models for hand and landmark detection without using MediaPipe lib. Could you please guide me which script should I use? Thanks

**Comment by sureshdagooglecom** [comment]
Hi @abucka ,
Please use [this](https://google.github.io/mediapipe/solutions/hands.html#:~:text=Hands(%0A%20%20%20%20static_image_mode%3DTrue%2C-,max_num_hands%3D2%2C,-min_detection_confidence%3D0.5)%20as) code snippet and change this parameters.

**Comment by sureshdagooglecom** [comment]
Hi @abucka ,
Please use [this](https://google.github.io/mediapipe/solutions/hands.html#:~:text=Hands(%0A%20%20%20%20static_image_mode%3DTrue%2C-,max_num_hands%3D2%2C,-min_detection_confidence%3D0.5)%20as) code snippet and change this parameters.
