### ISSUE TITLE
How to get the names of face key points

### ISSUE THREAD

**Issue by tiantianaixuexi** [google/mediapipe#3299]
Hello, I want to apply the face key point detection function to the virtual character of UE4, and he can successfully obtain the data and read it successfully. The bones on UE4 are named by name, but there is no corresponding name in the key point data of MediaPipe. How can I get the name of each key point?

**System information** (Please provide as much relevant information as possible)
Windows

- MediaPipe Solution (you are using):
Python C++
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state:**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Please specify the use cases for this feature:**

**Any Other info:**

**Comment by sureshdagooglecom** [comment]
Hi @tiantianaixuexi ,
We have closed issue on getting names on face key points , could you please check this closed issue https://github.com/google/mediapipe/issues/1615.
