### ISSUE TITLE
Links seem broken in documentation

### ISSUE THREAD

**Issue by shashankchaudhry** [google/mediapipe#33]
On this page:
https://mediapipe.readthedocs.io/en/latest/help.html

Both "file an issue on GitHub" and "MediaPipe repo" seem to take me to 404 pages.

On https://mediapipe.readthedocs.io/en/latest/framework_concepts.html?highlight=CalculatorContext#calculatorbase:

"The following are code snippets from CalculatorBase.h." -> Link seems to give me a 500 error.

**Comment by chuoling** [comment]
Thanks for the report. We will have them fixed in the next push.

In the meantime, please find the correct link to CalculatorBase.h at https://github.com/google/mediapipe/blob/master/mediapipe/framework/calculator_base.h.

**Comment by chuoling** [comment]
Fixed in https://github.com/google/mediapipe/commit/dc9216dc595585d495250d0692afe35985d816ff.
