### ISSUE TITLE
Install Mediapipe for coral dev board fails: Wheel is not supported on this platform

### ISSUE THREAD

**Issue by a-pipi** [google/mediapipe#3300]
**System information** 
- Coral dev board
- Mendel GNU/Linux 5 (Eagle)
- Python 3.7.3
- Installed using pip
- mediapipe-0.8.9.1-cp37-cp37m-manylinux2014_aarch64.whl and mediapipe-0.8.1-cp38-cp38-linux_aarch64.whl
- Bazel 5.1.1

Problem:
I have followed the steps on this page: https://github.com/jiuqiant/mediapipe_python_aarch64. I got it working until the part where I try to install mediapipe. I have tried to do the following two commands: 
`python3 -m pip install mediapipe-python-aarch64/mediapipe-0.8.4-cp38-cp38-linux_aarch64.whl`
and 
`python3 -m pip install mediapipe-python-aarch64/mediapipe-0.8.9.1-cp37-cp37m-manylinux2014_aarch64.whl`

I tried to execute the command with and without `--no-deps` appended. Executing this gives me the following error:

```
Requirement 'mediapipe-python-aarch64/mediapipe-0.8.9.1-cp37-cp37m-manylinux2014_aarch64.whl' looks like a filename, but the file does not exist
mediapipe-0.8.9.1-cp37-cp37m-manylinux2014_aarch64.whl is not a supported wheel on this platform.
```
What is going wrong here?

**Comment by sureshdagooglecom** [comment]
Hi @a-pipi ,
Could you please share which version of ubuntu you are using?

**Comment by a-pipi** [comment]
I now see that the tutorial is for an Ubuntu OS, I am trying to install it on Mendel OS. Is there a way to install the Mediapipe module on a Coral dev board with Mendel OS?

**Comment by sureshdagooglecom** [comment]
HI @a-pipi ,
Please follow the steps mentioned in [this](https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/README.md) document to set MediaPipe on coral devices.
