### ISSUE TITLE
Use  RationalFactorResampleCalculator in android env, build error

### ISSUE THREAD

**Issue by quire7** [google/mediapipe#3301]
<em>bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceemotionmultimodality:faceemotionmultimodality</em>

**My configuration**:
Ubuntu 18.04
Tensorflow==[v2.5.0-rc0]
g++ --version==7.5.0
bazel --version==bazel 3.4.1- (@non-git)
mediapipe==v0.8.2
androidndk==v21.3.6528147
androidsdk==v27

mobile_cpu.pbtxt :

node {
  calculator: "RationalFactorResampleCalculator"
  input_stream: "mono_waveform"
  output_stream: "resampled_waveform"
  node_options: {
    [type.googleapis.com/mediapipe.RationalFactorResampleCalculatorOptions] {
      target_sample_rate: 16000.0
    }
   }
}

BUILD:
cc_library(
    name = "mobile_calculators",
    deps = [
           "//mediapipe/calculators/audio:basic_time_series_calculators",
           "//mediapipe/calculators/audio:mfcc_mel_calculators",
           "//mediapipe/calculators/audio:rational_factor_resample_calculator",
    ],
)

**Error**:
pateo@pateo-OptiPlex-3070:~/fxd/work/gitLab/mediapipe$ bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceemotionmultimodality:faceemotionmultimodality
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 21. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]. Bazel will attempt to treat the NDK as if it was r20. This may cause compilation and linkage problems. Please download a supported NDK version.
WARNING: API level 30 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
WARNING: /home/pateo/fxd/work/gitLab/mediapipe/mediapipe/calculators/audio/BUILD:155:11: in cc_library rule //mediapipe/calculators/audio:rational_factor_resample_calculator: target '//mediapipe/calculators/audio:rational_factor_resample_calculator' depends on deprecated target '@com_google_audio_tools//audio/dsp:resampler_rational_factor': RationalFactorResampler is superseded by QResampler. Please see migration notes at the top of resampler_rational_factor.h.
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceemotionmultimodality:faceemotionmultimodality (2 packages loaded, 205 targets configured).
INFO: Found 1 target...
ERROR: /home/pateo/fxd/work/gitLab/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceemotionmultimodality/BUILD:19:10: Linking of rule '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceemotionmultimodality:libmediapipe_jni.so' failed (Exit 1) clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -shared -o ... (remaining 676 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
**external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lpthread**
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceemotionmultimodality:faceemotionmultimodality failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.297s, Critical Path: 0.92s
INFO: 1 process: 1 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by sureshdagooglecom** [comment]
Hi @quire7 ,
DId you get  a chance to check this closed issuehttps://github.com/google/mediapipe/issues/194.

**Comment by quire7** [comment]
> audio:rational_factor_resample_calculator
desktop extract_yt8m_features build success. but use rational_factor_resample_calculator in android env, build error. I guess build '@com_google_audio_tools//audio/dsp:resampler_rational_factor' in android env error

**Comment by sureshdagooglecom** [comment]
Hi @quire7 ,
Could you please elaborate this  https://github.com/google/mediapipe/issues/3301#issuecomment-1120114724.

**Comment by quire7** [comment]
> Hi @quire7 , Could you please elaborate this [#3301 (comment)](https://github.com/google/mediapipe/issues/3301#issuecomment-1120114724).

i have solved it,  modify com_google_audio_tools bazel env for android.
