### ISSUE TITLE
Error while trying to print the Left hand and right hand landmarks.

### ISSUE THREAD

**Issue by Dilipraj6** [google/mediapipe#3302]
I am using a Holistic solution and trying to get the left hand, right hand and pose landmarks. I am giving my webcam feed as input.

When I run the code below, there are no errors and everything is good:

cap = cv2.VideoCapture(0)
//Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        //Read feed
        ret, frame = cap.read()

        // Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        // Draw landmarks
        draw_styled_landmarks(image, results)

        // Show to screen
        cv2.imshow('OpenCV Feed', image)

        // Break
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

After this, I was trying to check if I got the landmarks by using "results.left_hand_landmarks.landmark" and length of the landmarks using "len(results.left_hand_landmarks.landmark)" I am getting this "AttributeError: 'NoneType' object has no attribute 'landmark'"

The funny part is the problem is only with left hand and right hand landmarks. I was able to get the Pose landmarks and its length. Please help.

I am on windows, using jupyter notebook, Holistic Solution, Python

**Comment by sureshdagooglecom** [comment]
Hi @Dilipraj6 ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/1803.

**Comment by priyanshurohilla** [comment]
> I am using a Holistic solution and trying to get the left hand, right hand and pose landmarks. I am giving my webcam feed as input.
> 
> When I run the code below, there are no errors and everything is good:
> 
> cap = cv2.VideoCapture(0) //Set mediapipe model with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic: while cap.isOpened():
> 
> ```
>     //Read feed
>     ret, frame = cap.read()
> 
>     // Make detections
>     image, results = mediapipe_detection(frame, holistic)
>     print(results)
>     
>     // Draw landmarks
>     draw_styled_landmarks(image, results)
> 
>     // Show to screen
>     cv2.imshow('OpenCV Feed', image)
> 
>     // Break
>     if cv2.waitKey(10) & 0xFF == ord('q'):
>         break
> cap.release()
> cv2.destroyAllWindows()
> ```
> 
> After this, I was trying to check if I got the landmarks by using "results.left_hand_landmarks.landmark" and length of the landmarks using "len(results.left_hand_landmarks.landmark)" I am getting this "AttributeError: 'NoneType' object has no attribute 'landmark'"
> 
> The funny part is the problem is only with left hand and right hand landmarks. I was able to get the Pose landmarks and its length. Please help.
> 
> I am on windows, using jupyter notebook, Holistic Solution, Python

same issue is happening with me. Plz give us the solution

**Comment by mammubarak** [comment]
same issue occurred to me , i dont what is the reason 
i didnt got any answers 
pls help me

**Comment by priyanshurohilla** [comment]
> same issue occurred to me , i dont know what is the reason i didnt got any answers pls help me

Hi everyone!, This is not a code issue actually rather its more of an operation issue. The reason you are not getting the landmarks because you are not showing your hand in the feed. Once you show that, landmarks will show up in ur code. I hope this clears it up.

**Comment by kuaashish** [comment]
Hello @Dilipraj6,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
