### ISSUE TITLE
Slow perfomance of Hands in iOS Safari

### ISSUE THREAD

**Issue by spaskhalov** [google/mediapipe#3303]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.</em>

This issue is reproduced in [Hands](https://google.github.io/mediapipe/solutions/hands) solution.

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): iOS 15.4.1
- [MediaPipe version](https://github.com/google/mediapipe/releases): latest [v0.8.9](https://github.com/google/mediapipe/tree/v0.8.9)
- Bazel version: -
- Solution (e.g. FaceMesh, Pose, Holistic): Hands
- Programming Language and version ( e.g. C++, Python, Java): JS

**Describe the expected behavior:**

Official web example on [code pen](https://code.mediapipe.dev/codepen/hands), run extremely slow at iOS devices (tested on iPhone 11, iPhone 12 Pro max, iPhone 13 pro). It show around 6-7 fps at all. At same time, at Android it run pretty well.
Also if i run raw graph "Hand Tracking" at [MediaPipe Visualizer](https://viz.mediapipe.dev/) it run at 30 FPS at iOS devices.

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

Just open [web demo](https://code.mediapipe.dev/codepen/hands) at iOS device.

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by sureshdagooglecom** [comment]
Hi @spaskhalov ,
could you please share any reference videos w.r.t above issue.

**Comment by spaskhalov** [comment]
Of course. Here it is.Pay attention to FPS counter and web cam feed.
https://youtube.com/shorts/2RHGtFGeiUk?feature=share

**Comment by KTRosenberg** [comment]
I can also confirm that on a Mac M1 Max (similar ARM son architecture), the frame rate drops precipitously.

**Comment by spaskhalov** [comment]
@sureshdagooglecom can you confirm, that problem exists for you?

**Comment by sureshdagooglecom** [comment]
Hi @spaskhalov ,
Below is the code to build Ios.
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_framework")

ios_framework(
    name = "MyFramework",
    hdrs = [
        "ObjcClass.h",
    ],
    infoplists = ["Info.plist"],
    bundle_id = "com.noppelab.MyFramework",
    families = ["iphone", "ipad"],
    minimum_os_version = "10.0",
    deps = [
        ":HandTrackingGpuAppLibrary",
        "@ios_opencv//:OpencvFramework",
    ],
)

objc_library(
    name = "HandTrackingGpuAppLibrary",
    srcs = [
        "ObjcClass.mm",
    ],
    hdrs = [
        "ObjcClass.h",
    ],
    
    sdk_frameworks = [
        "AVFoundation",
        "CoreGraphics",
        "CoreMedia",
        "UIKit"
    ],
    copts = ["-std=c++17"],
    data = [
        "//mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu.binarypb",
        "//mediapipe/modules/hand_landmark:hand_landmark.tflite",
        "//mediapipe/modules/hand_landmark:handedness.txt",
        "//mediapipe/modules/palm_detection:palm_detection.tflite",
    ],
    deps = [
        "//mediapipe/examples/ios/common:CommonMediaPipeAppLibrary",
        "//mediapipe/util:annotation_renderer",
    ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            "//mediapipe/graphs/hand_tracking:mobile_calculators",
            "//mediapipe/framework/formats:landmark_cc_proto",
        ],
    }),
)

Could you please check this https://github.com/google/mediapipe/issues/2507#issuecomment-916900036 to buld hands on ios.

**Comment by spaskhalov** [comment]
@sureshdagooglecom, Hi! I have problems with running Hands solution in Safari on iOS. So i don't think that my problem is related with https://github.com/google/mediapipe/issues/2507#issuecomment-916900036 . BTW in native iOS app Hands solution performance is great!

**Comment by spaskhalov** [comment]
I can confirm, that forcing set useCpuInference to false (more details [here](https://github.com/google/mediapipe/issues/2536#issuecomment-940313444)) is help us.
