### ISSUE TITLE
 How to use Effect Renderer in Mediapipe with Javascript? 

### ISSUE THREAD

**Issue by lv2lrn4lf** [google/mediapipe#3304]
So, I'm trying to find information on how to use textures with Mediapipe, as showcased, describe, and explain on this page https://google.github.io/mediapipe/solutions/face_mesh.html the problem is that there is no example of this with code, just showcasing a gif of it as illustrated in Fig 5. An example of face effects rendered by the Face Transform Effect Renderer.. How would one go about this in javascript?

is there a function to feed textures too?

Can Mediapipe be used to render textures, and other 3d models? As well as animate those objects?

**Comment by sureshdagooglecom** [comment]
Hi @lv2lrn4lf ,
Did you get a chance to check this closed https://github.com/google/mediapipe/issues/1155.
