### ISSUE TITLE
Mediapipe holistic model runtime issue on GPU with v0.8.9 and latest version on master (works fine in v0.8.7) 

### ISSUE THREAD

**Issue by naveenkulkarni-movidius** [google/mediapipe#3305]
**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): yes
- OS Platform and Distribution: Linux Ubuntu 20.04 
- Programming Language and version: Mediapipe Python
- [MediaPipe version]: https://github.com/google/mediapipe/tree/v0.8.9 or latest master
- Bazel version (if compiling from source): bazel 5.1.1
- Solution ( e.g. FaceMesh, Pose, Holistic ): Holistic

**Describe the current behavior:**
Mediapipe holistic solution compiles fine when using latest version of mediapipe(master or branch v0.8.9) and patched to get holistic models running on a GPU, but fails during runtime.

**Describe the expected behavior:**
Mediapipe holistic solution compiles and also runs on a GPU when using  v0.8.7. There seem to be a regression going from v0.8.7 to v0.8.9.

**Standalone code to reproduce the issue:**
_git clone git@github.com:google/mediapipe.git
cd mediapipe
git checkout master
git apply ../mediapipe_master.patch
python setup.py gen_protos
python setup.py install --link-opencv_

**Other info / Complete Logs :**
        _holistic = mp_holistic.Holistic(static_image_mode=False, model_complexity=1, smooth_landmarks=False,
  File "/home/ubuntu/anaconda3/envs/mlpipe_master/lib/python3.8/site-packages/mediapipe/python/solutions/holistic.py", line 114, in __init__
    super().__init__(
  File "/home/ubuntu/anaconda3/envs/mlpipe_master/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 258, in __init__
    canonical_graph_config_proto = self._initialize_graph_interface(
  File "/home/ubuntu/anaconda3/envs/mlpipe_master/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 415, in _initialize_graph_interface
    self._output_stream_type_info = {
  File "/home/ubuntu/anaconda3/envs/mlpipe_master/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 416, in <dictcomp>
    get_name(tag_index_name): get_stream_packet_type(tag_index_name)
  File "/home/ubuntu/anaconda3/envs/mlpipe_master/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 404, in get_stream_packet_type
    validated_graph.registered_stream_type_name(stream_name))
RuntimeError: ; Unable to find the type for stream "segmentation_mask".  It may be set to AnyType or something else that isn't determinable, or the type may be defined but not registered._
_

**Comment by naveenkulkarni-movidius** [comment]
[mediapipe_master.zip](https://github.com/google/mediapipe/files/8595322/mediapipe_master.zip)
Attaching the patch zip file for reference. It is very easy to reproduce as provided in the steps above. Please help resolve the issue.

**Comment by sureshdagooglecom** [comment]
Hi @naveenkulkarni-movidius ,
MediaPipe Python package only contains CPU graphs. If you need to run any GPU graphs, see https://github.com/google/mediapipe/issues/1651 (comment).

**Comment by naveenkulkarni-movidius** [comment]
Hi @sureshdagooglecom, this patch is taken from #1651 and with additional changes as well. It is working well with v0.8.7 of mediapipe, what is being asked here is v0.8.9 doesn't work with a similar patch. So it is a bug in v0.8.9 which was not there in v0.8.7. I have attached the patch for v0.8.9 above which does not work. The same above patch works fine with v0.8.7. If you could help provide a fix for the GPU graph with v0.8.9, it would be help with workload processing for faster performance. Adding @jiuqiant here to the thread for additional context and info. Thanks!

**Comment by naveenkulkarni-movidius** [comment]
[mediapipe_v0.8.10.zip](https://github.com/google/mediapipe/files/8734999/mediapipe_v0.8.10.zip)
@xiong-jie-y , Thanks for sharing the patch. However there have been few more fixes related to legacy GPU usage etc. in the latest version. I see some difference between the commit version(c6c80c37452d0938b1577bd1ad44ad096ca918e0) which your patch is based off of and latest commit(4a20e9909d55838d5630366ce719844cf06ae85c). I am attaching the patch which is the combination of my previous patch and your changes to get rid of segmentation_mask error. However now I see a different error. Can you let me know if you see any other fix missing here from the patch? Here are the error logs below.                                                                                                                                                                                
I20220520 00:28:30.500936 510626 calculator_graph.cc:123] Initialize the GPU.
E20220520 00:28:30.507282 510626 calculator_graph.cc:132] INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:83) egl_initializedUnable to initialize EGL                                                                              
File "/home/ubuntu/anaconda3/envs/mlpipe_v0.8.10/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 289, in __init__
    self._graph.start_run(self._input_side_packets)
RuntimeError: Service "kGpuService", required by node ImageFrameToGpuBufferCalculator, was not provided and cannot be created: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:83) egl_initializedUnable to initialize EGL

**Comment by xiong-jie-y** [comment]
@naveenkulkarni-movidius 
Hi,

I rebased my branch onto latest commit and it worked in my environment.
Could you first check if my branch works in your environment with hand example or some simple examples first? :slightly_smiling_face: 
https://github.com/xiong-jie-y/mediapipe/tree/add_gpu_support_for_python

**Comment by naveenkulkarni-movidius** [comment]
@xiong-jie-y, thanks again for confirming that it works with the latest commit :) I found that there was a minor change needed(on top of add_gpu_support_for_python branch) where I had to disable "EGL_WINDOW_BIT" in my env. With this change and another change to use opencv4, it seems to be working fine now. My only concern is that it hangs without any warning or error after sometime(1-2 minutes), have you noticed any such issue on your end? I am trying to understand how this can be debugged using more logging info etc. Will share more logs on this, in the meantime if this is something you already know it would be good to understand the issue. Thanks

**Comment by naveenkulkarni-movidius** [comment]
@xiong-jie-y , it seems to be stable and do not see a hang now :). Thanks again for your inputs!

**Comment by jjkindergarten** [comment]
@naveenkulkarni-movidius Hi i met the same issue:
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20220711 03:52:58.992661  7331 calculator_graph.cc:123] Initialize the GPU.
E20220711 03:52:59.008455  7331 calculator_graph.cc:132] INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:83) egl_initializedUnable to initialize EGL
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    with mp_holistic.Holistic(
  File "/usr/lib/python3.8/site-packages/mediapipe/python/solutions/holistic.py", line 114, in __init__
    super().__init__(
  File "/usr/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 289, in __init__
    self._graph.start_run(self._input_side_packets)
RuntimeError: Service "kGpuService", required by node poselandmarkgpu__posedetectiongpu__ImageToTensorCalculator, was not provided and cannot be created: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:83) egl_initializedUnable to initialize EGL

when you say disable "EGL_WINDOW_BIT" in your env, what did you mean exactly? do you mind sharing the patch?

Thank you!

**Comment by VanillaTiger** [comment]
@xiong-jie-y I follow your instructions as in [https://github.com/google/mediapipe/issues/3266#issuecomment-1121056087](url) but I am getting Build Errors from Bazel.

I installed Bazelisk so it automatically installs Bazel 5.0 but which version are you using ? I suspect bazel version issue.

`ERROR: Traceback (most recent call last):
	File "/home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/rules_cc/cc/private/rules_impl/cc_flags_supplier.bzl", line 16, column 76, in <toplevel>
		load("@bazel_tools//tools/cpp:toolchain_utils.bzl", "find_cpp_toolchain", "use_cpp_toolchain")
Error: file '@bazel_tools//tools/cpp:toolchain_utils.bzl' does not contain symbol 'use_cpp_toolchain' (did you mean 'find_cpp_toolchain'?)
ERROR: Skipping 'mediapipe/modules/face_detection/face_detection_short_range_gpu': error loading package 'mediapipe/modules/face_detection': at /home/aszummer/Projects/mediapipe_for_gpu/mediapipe/mediapipe/framework/tool/mediapipe_graph.bzl:23:6: at /home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/org_tensorflow/tensorflow/lite/core/shims/cc_library_with_tflite.bzl:4:5: at /home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/org_tensorflow/tensorflow/lite/build_def.bzl:4:5: at /home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/org_tensorflow/tensorflow/tensorflow.bzl:13:5: at /home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/org_tensorflow/tensorflow/core/platform/rules_cc.bzl:4:5: at /home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/org_tensorflow/tensorflow/core/platform/default/rules_cc.bzl:11:5: at /home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/rules_cc/cc/defs.bzl:17:6: initialization of module 'cc/private/rules_impl/cc_flags_supplier.bzl' failed
WARNING: Target pattern parsing failed.
ERROR: error loading package 'mediapipe/modules/face_detection': at /home/aszummer/Projects/mediapipe_for_gpu/mediapipe/mediapipe/framework/tool/mediapipe_graph.bzl:23:6: at /home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/org_tensorflow/tensorflow/lite/core/shims/cc_library_with_tflite.bzl:4:5: at /home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/org_tensorflow/tensorflow/lite/build_def.bzl:4:5: at /home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/org_tensorflow/tensorflow/tensorflow.bzl:13:5: at /home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/org_tensorflow/tensorflow/core/platform/rules_cc.bzl:4:5: at /home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/org_tensorflow/tensorflow/core/platform/default/rules_cc.bzl:11:5: at /home/aszummer/.cache/bazel/_bazel_aszummer/a7445427326cf8038eb0a63fbc71cae1/external/rules_cc/cc/defs.bzl:17:6: initialization of module 'cc/private/rules_impl/cc_flags_supplier.bzl' failed
INFO: Elapsed time: 19.991s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: mediapipe/modules/face_detection
`

**Comment by naveenkulkarni-movidius** [comment]
> @naveenkulkarni-movidius Hi i met the same issue: WARNING: Logging before InitGoogleLogging() is written to STDERR I20220711 03:52:58.992661 7331 calculator_graph.cc:123] Initialize the GPU. E20220711 03:52:59.008455 7331 calculator_graph.cc:132] INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:83) egl_initializedUnable to initialize EGL Traceback (most recent call last): File "demo.py", line 15, in with mp_holistic.Holistic( File "/usr/lib/python3.8/site-packages/mediapipe/python/solutions/holistic.py", line 114, in **init** super().**init**( File "/usr/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 289, in **init** self._graph.start_run(self._input_side_packets) RuntimeError: Service "kGpuService", required by node poselandmarkgpu__posedetectiongpu__ImageToTensorCalculator, was not provided and cannot be created: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:83) egl_initializedUnable to initialize EGL
> 
> when you say disable "EGL_WINDOW_BIT" in your env, what did you mean exactly? do you mind sharing the patch?
> 
> Thank you!
[mediapipe_v0.8.10.zip](https://github.com/google/mediapipe/files/9215089/mediapipe_v0.8.10.zip)
Maybe it's a version issue, the above patch works with v0.8.10

**Comment by VanillaTiger** [comment]
For me its working now, 

in the code provided by @xiong-jie-y there is a mistake you need to change in .bazelVersion 5.0.0 to 5.2.0 then the build is going succesfull and i dont get the error i mentioned.

in addition please ensure you have protobuf==3.20 otherwise you also get errors.

finally for build to complete probably you have installed opencv4 so also before the building process you need to do changes in opencv4_linux.BUILD just uncomment parts as stated here [https://google.github.io/mediapipe/getting_started/install.html#:~:text=opencv2/cvconfig.h"%2C-,"include/opencv4/opencv2/**/*.h*"%2C,-])%2C%0A%20%20includes%20%3D](url)

after that the repo shared by @xiong-jie-y worked.

**Comment by naveenkulkarni-movidius** [comment]
@xiong-jie-y , have you seen issues enabling mediapipe 0.10.9 (latest version) on GPU? I tried compiling using previous instructions: https://github.com/google/mediapipe/blob/master/docs/getting_started/python.md. But it keeps giving out this error: 

Command '['/usr/bin/protoc', '-I.', '--python_out=/home/ubuntu/src/mediapipe/build/lib.linux-x86_64-cpython-38', 'mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto']' returned non-zero exit status 1

Is there a need to use different version of setuptools ? I tried using various setuptools package versions <66.0.0. None of them seem to be working. Not sure if these instructions are valid anymore? This is for holistic tracking though, other modules likely have newer API for GPU support.

**Comment by lanzani** [comment]
If you want to use mediapipe with GPU, I suggest looking [here ](https://jetson-docs.com/libraries/mediapipe/overview) :)

**Comment by naveenkulkarni-movidius** [comment]
> If you want to use mediapipe with GPU, I suggest looking [here ](https://jetson-docs.com/libraries/mediapipe/overview) :)

Thank you @lanzani . Good to know there is a GPU solution with later versions of mediapipe :), I will look into more details soon. But these are not built using OpenGL backend and are not built on x86 platform right? I wanted to understand if these are only for aarch64 only or have support for x86 platform as well?

**Comment by lanzani** [comment]
I've built them primarily for jetson nano (aarch64) since it was my main use case. If you need mediapipe for x86 with GPU support, I suggest to look at the installation guide on the mediapipe website :)

**Comment by naveenkulkarni-movidius** [comment]
> I've built them primarily for jetson nano (aarch64) since it was my main use case. If you need mediapipe for x86 with GPU support, I suggest to look at the installation guide on the mediapipe website but I've not tested it personally yet :)

Thanks for the clarification. I have built on the x86 platform with Nvidia GPU using OpenGL backend as you can see in the thread above. However that was prior to version 0.10.x. There have been a few issues post 0.10.x, will try to find a workaround to get it working using OpenGL backend. Thanks again for the jetson link :)

**Comment by naveenkulkarni-movidius** [comment]
> Thank you, I agree that maybe this wasn't the best place to post my link, but I've wasted so many hours to made mediapipe works on jetson with GPU that I thought it would be useful to other developers :)
> 
> If you find a workaround to build mp 0.10.x with OpenGL on x86, I'm curious to know about it in order to add the approach to jetson-docs.com :)

I can understand when you say "wasted hours", because I have gone through the same on my side. Will definitely post here if I find a workaround :)
