### ISSUE TITLE
Model of Hand Tracking

### ISSUE THREAD

**Issue by wuheng0711** [google/mediapipe#3306]
mediapipe\modules\palm_detection\palm_detection_full.tflite

Is the model “palm_detection_full.tflite” in float32 format？I want to convert it into int8 quantitative model, which has improved the processing speed on arm.

Is there any good way? If there is an on-site int8 quantitative model, it would be better.

**Comment by sureshdagooglecom** [comment]
Hi @wuheng0711 ,
Yes we have MediaPipe solutions in flaot32 format, kindly refer [this](https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/drawing_utils.py#:~:text=axis_world%20%3D%20np.float32(%5B%5B0%2C%200%2C%200%5D%2C%20%5B1%2C%200%2C%200%5D%2C%20%5B0%2C%201%2C%200%5D%2C%20%5B0%2C%200%2C%201%5D%5D)) document.
