### ISSUE TITLE
How to use  mediapipe to analyze muscle movement?

### ISSUE THREAD

**Issue by JoyX2** [google/mediapipe#3307]
how to use Face mesh to  analyzes subtle muscle movements (instead of tracking 200-400 points ) ?

I wanna identify what facial muscle is and let facemesh detect the muscle movement rather than going after every single landmark

this way if some points jittered for whatever reason, it can be detected and ignored if it doesn't make any sense ( sense the muscle would move all points of the muscle together )

here is a thought, how to create blendshapes using facemesh, like (for example : open eyes wide, then hit space "create an LeftEye blendshape hotkey" > the blendshape gets saved in a folder ) 

then track how likely the current feed from the webcam is to the saved blend shapes instead of the points ?

**Comment by sureshdagooglecom** [comment]
Hi @JoyX2 ,
Did you get a chance to check this closed issue.

**Comment by JoyX2** [comment]
@jiuqiant  Im sorry, I got a notification of a comment by you, but I cant see it.

**Comment by sureshdagooglecom** [comment]
Hi @JoyX2 ,
We don't have this feature due to limited support , we consider this as a feature request and share it internally.

**Comment by JoyX2** [comment]
> Hi @JoyX2 , We don't have this feature due to limited support , we consider this as a feature request and share it internally.

internally? as not a public version or an opensource? but mediapipe itself this is an open source as far as I know, isn't it?

**Comment by sureshdagooglecom** [comment]
Hi @JoyX2 ,
My comment was since this is a feature request ,needs development and to be released in the MediaPipe next release.
