### ISSUE TITLE
FaceMesh setServicePacket:forService:  How to use it?

### ISSUE THREAD

**Issue by zhuzhuxingtianxia** [google/mediapipe#3309]
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution ( iOS 15.2):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (FaceMesh):
- Programming Language and version ( iOS):

in iOS，api `- (void)setServicePacket:(mediapipe::Packet&)packet
              forService:(const mediapipe::GraphServiceBase&)service` 
How to use it? I don't see relevant use cases

**Comment by sureshdagooglecom** [comment]
Hi @zhuzhuxingtianxia ,
This function will set which service has to be set for the particular model  like  GraphServiceBase.

**Comment by zhuzhuxingtianxia** [comment]
Can you give a practical example？

**Comment by sureshdagooglecom** [comment]
Hi @zhuzhuxingtianxia ,
Graph service mostly for GPU resources, and other google-internal use cases and no public examples.  
It can be used to provide a graph-wide resource to certain specific calculators.
