### ISSUE TITLE
Iphone overheating

### ISSUE THREAD

**Issue by zzmicer** [google/mediapipe#3312]
Hello, I'm running SelfieSegmentation graph on IOS. 
My Iphone 11 warms up noticeably.  
<img width="862" alt="Screenshot 2022-05-02 at 13 22 04" src="https://user-images.githubusercontent.com/41323462/166220510-dcd2276f-1aaf-488a-87bb-207a05c9db21.png">

I suggest this happens because of running OpenGL ES code(rather than Metal) on IOS. 
Any other ideas, what's causing this heating? How to fix it?

**Comment by yangyuanwei** [comment]
Has the problem of Iphone overheating been solved？

**Comment by zzmicer** [comment]
@yangyuanwei  No, I couldn't figure out why it's happening :(
Waiting for response @NikolayChirkov @sureshdagooglecom

**Comment by zzmicer** [comment]
@NikolayChirkov @sureshdagooglecom 
Any updates?

**Comment by zzmicer** [comment]
@NikolayChirkov @sureshdagooglecom 
Hey, any news on this issue?

**Comment by kuaashish** [comment]
Hello @zzmicer,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
