### ISSUE TITLE
How to show or hide landmark connections and points in IOS？

### ISSUE THREAD

**Issue by zhuzhuxingtianxia** [google/mediapipe#3314]
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution ( iOS 15.2):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (FaceMesh):
- Programming Language and version ( iOS):

in Python Solution API, we can set the connections and styles with the method `mp_drawing.draw_landmarks`,
in JavaScript Solution API,  we can set styles with the method `drawConnectors`.
So how to set it in iOS？

In the development phase, we use annotation and point debugging, but in production, we need to hide.
What should I do？

**Comment by sureshdagooglecom** [comment]
Hi @zhuzhuxingtianxia ,
Did you get a chance to check this closed issue https://google.github.io/mediapipe/getting_started/ios.html.

**Comment by sureshdagooglecom** [comment]
Hi @zhuzhuxingtianxia ,
Please check [this](https://google.github.io/mediapipe/getting_started/ios.html) document on drawing landmarks in Ios.

**Comment by zhuzhuxingtianxia** [comment]
but nothing ?

**Comment by sureshdagooglecom** [comment]
Hi @zhuzhuxingtianxia ,
Please check [this](https://github.com/google/mediapipe/blob/master/docs/solutions/face_mesh.md) code repo for drawing face mesh solution on Ios.
