### ISSUE TITLE
Pose Estimation - Avatar puppeteering

### ISSUE THREAD

**Issue by JpEncausse** [google/mediapipe#3315]
Hello,

- I setup a Rigged ReadyPlayer.Me / Mixamo Avatar available in ThreeJS. 
- I setup MediaPipe Pose estimation from Webcam (drawing landmarks with `drawConnectors()` )

How should I convert [data from Pose Estimation](https://google.github.io/mediapipe/solutions/pose.html#output) to Avatar Rigged values in an efficient way ? Do someone already did that in an exemple ?

I assume I should use the real world data relative to `center between hips` ? Then ? compute rotation (and position) ? Or may be only work with delta between frames ?

**Comment by AmitMY** [comment]
If you figure out how to make it work reliably, let me know :)
Here's my attempt with mixamo and mediapipe https://www.youtube.com/watch?v=TyJuU9_GOaw

**Comment by sureshdagooglecom** [comment]
Hi @AmitMY ,
what are the remaining difficulties with this conversion, could you please share any pointers.

**Comment by Nor-s** [comment]
[This](https://github.com/Nor-s/mediapipe-to-mixamo) is a project I'm currently working on. You need to get the relative angles of the binding poses of the model.

**Comment by JpEncausse** [comment]
Thanks @Nor-s !
That's weird Google do not provide such helpers in MediaPipe in order to animate "any" Puppet. I agree Rigging can be performed various ways but Google could set good pratices / normalize. 

It's a real pain to use Blender / Mixamo / ... just to have a working Avatar. The day a GAFAM set a way to rig a human body it will be a game changer to all avatar creation. 

(same for lipsync ... Microsoft, Occulus use different Viseme)

**Comment by Nor-s** [comment]
yes i think so too. 
Also, you might be able to take advantage of [this project](https://freemocap.org/). 
This seems to be very good, such as converting mixamo into mocap data and utilizing the functions of blender.
[youtube](https://www.youtube.com/watch?v=FX7c7XmNJcU)
