### ISSUE TITLE
facedetect javascript nodejs start failed

### ISSUE THREAD

**Issue by gushenjie** [google/mediapipe#3317]
![image](https://user-images.githubusercontent.com/10531802/166610898-b7bac178-2281-4888-879b-536c43f7ff73.png)

**Comment by sureshdagooglecom** [comment]
Hi @gushenjie ,
Could you provide steps to reproduce this issue.

**Comment by gushenjie** [comment]
this is my source code demo,just use face detect sample
https://topvision-cv.com/tv/mediapipenodejs.zip

**Comment by kuaashish** [comment]
Hello @gushenjie,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
