### ISSUE TITLE
How to save landmarks to csv/json?

### ISSUE THREAD

**Issue by andriotik007** [google/mediapipe#3319]
I am planning on using holistic solution for Machine Learning. The results are returned as NormalizedLandmarkList, do you have any build-in methods, to convert it into an output file with landmarks? Also, retrieved landmarks don't seem to be ordered by the id of the Landmarks as in documentation (results.pose_landmarks.landmark[0] /= Nose Landmark), how can I retrieve them in the same order, as in documentation?

**Comment by sureshdagooglecom** [comment]
Hi @andriotik007 ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/1803.
