### ISSUE TITLE
How to update the mediapipe graphs and add it to gradle project

### ISSUE THREAD

**Issue by suraj-0387** [google/mediapipe#332]
We are a working on a mediapipe handtracking application and we are trying to make some changes to the graphs of handtracking(subgraphs).I have created the handtracking application using the Gradle. I have created an arr library file and integrated it in a gradle based project.Now I would like to know how to update the graphs and add the updated graphs to the Gradle project

**Comment by jiuqiant** [comment]
First, you need to modify the hand tracking graph [multi_hand_tracking_mobile.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile.pbtxt). Then, call Bazel to regenerate the binarypb. For multi-hand tracking, you need to run the following command to regenerate multi_hand_tracking_mobile_gpu.binarypb.
```
bazel build mediapipe/graphs/hand_tracking:multi_hand_tracking_mobile_gpu_binary_graph

...
Target //mediapipe/graphs/hand_tracking:multi_hand_tracking_mobile_gpu_binary_graph up-to-date:
  bazel-bin/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile_gpu.binarypb
INFO: Elapsed time: 9.318s, Critical Path: 1.57s
```

Finally, copy the new generated bazel-bin/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile_gpu.binarypb to your project.

**Comment by AlexYiningLiu** [comment]
> First, you need to modify the hand tracking graph [multi_hand_tracking_mobile.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile.pbtxt). Then, call Bazel to regenerate the binarypb. For multi-hand tracking, you need to run the following command to regenerate multi_hand_tracking_mobile_gpu.binarypb.
> 
> ```
> bazel build mediapipe/graphs/hand_tracking:multi_hand_tracking_mobile_gpu_binary_graph
> 
> ...
> Target //mediapipe/graphs/hand_tracking:multi_hand_tracking_mobile_gpu_binary_graph up-to-date:
>   bazel-bin/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile_gpu.binarypb
> INFO: Elapsed time: 9.318s, Critical Path: 1.57s
> ```
> 
> Finally, copy the new generated bazel-bin/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile_gpu.binarypb to your project.

I ran the command 
```
bazel build mediapipe/graphs/hand_tracking:multi_hand_tracking_mobile_gpu_binary_graph
```
but received the error:
```
ERROR: C:/users/alexl/studioprojects/mediapipe/mediapipe/graphs/hand_tracking/BUILD:98:1: //mediapipe/graphs/hand_trac
king:multi_hand_tracking_mobile_gpu_binary_graph_text_to_binary_graph depends on //mediapipe/framework/tool:text_to_bi
nary_graph in repository @ which failed to fetch. no such package '@com_google_protobuf//': Traceback (most recent cal
l last):
```
Protobuf is installed on my computer as I checked with:
![image](https://user-images.githubusercontent.com/46139686/85318393-ea267a00-b48d-11ea-86eb-c5e3e29cb354.png)

Can you think of any fixes for this problem? I added a node to the graph and I just need to convert it to a binarypb file so I can try it in my project.

**Comment by AlexYiningLiu** [comment]
> First, you need to modify the hand tracking graph [multi_hand_tracking_mobile.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile.pbtxt). Then, call Bazel to regenerate the binarypb. For multi-hand tracking, you need to run the following command to regenerate multi_hand_tracking_mobile_gpu.binarypb.
> 
> ```
> bazel build mediapipe/graphs/hand_tracking:multi_hand_tracking_mobile_gpu_binary_graph
> 
> ...
> Target //mediapipe/graphs/hand_tracking:multi_hand_tracking_mobile_gpu_binary_graph up-to-date:
>   bazel-bin/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile_gpu.binarypb
> INFO: Elapsed time: 9.318s, Critical Path: 1.57s
> ```
> 
> Finally, copy the new generated bazel-bin/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile_gpu.binarypb to your project.

Where do you actually find the multi_hand_tracking_mobile_gpu.binarypb file? I can't see it in mediapipe/graphs/hand_tracking

**Comment by seasiainfotech** [comment]
[multi_hand_tracking_mobile.pbtx](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile.pbtxt)
above link show page not found exception
please help me i am facing issue with mediapipe remove extra renderer ovelays (square etc.)
