### ISSUE TITLE
Instant Motion Tracker - Provide tracking coordinates

### ISSUE THREAD

**Issue by ardulogic** [google/mediapipe#3320]
Hello, I'm trying to make an (android) use case of Instant-Motion-Tracker, where it controls a camera gimbal. What I need is after setting the point, to have a constant stream of updated coordinates. Is there any chance to receive tracking coordinates from Instant Motion Tracker? 

After inspection of the code, it seems that now it only "plays around" with the gif or 3d object, but doesnt give out the coordinates, so they can be used in MainActivity.  Is there any way to build this project and assign some listener to retrieve those coordinates?

**Comment by sureshdagooglecom** [comment]
Hi @ardulogic ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/2551.
