### ISSUE TITLE
Hands' landmarks from Holistic 

### ISSUE THREAD

**Issue by AceCHQ** [google/mediapipe#3322]
Thanks for your excellent jobs. I have downloaded mediapipe by pip install. However, I can not get the results that Holistic's web demo shows, like my hands. And the visual results of hands are the same  as the mediapipe pose, including just few landmarks. The result is as follows. Is that anything wrong? I want him to capture every joint of my finger，and the hand repo can finish it. 
![image](https://user-images.githubusercontent.com/104981253/166904436-d6d0a0ec-9114-4c18-8c1a-8fdd50d2f1cb.png)

**Comment by sureshdagooglecom** [comment]
Hi @AceCHQ ,
Did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/2930.

**Comment by AceCHQ** [comment]
Thanks~
