### ISSUE TITLE
Docker image improper bazel setup when run on Windows

### ISSUE THREAD

**Issue by NNskelly** [google/mediapipe#3325]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):  Windows 10 Pro 21H1 19043.1645 (Docker Desktop 4.7.1 (77678) running against WSL version 2, Kernel version 5.10.16)
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): 
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.9
- Bazel version: Docker image default 5.0.0
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:
Very new to Docker, but my understanding is that the Docker image and build script ought to moot the toolchain present on the host platform.  That said, host platform is a Win10 box with WSL2 left at its default iirc Ubuntu settings.

Following the Installing Using Docker instructions verbatim from https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker ,
- the git pull works fine; latest commit would have been https://github.com/google/mediapipe/commit/c6c80c37452d0938b1577bd1ad44ad096ca918e0
- the docker build command does not show any conspicuous errors, but looks nothing like the cited expected output, so either the expected output is very out of date, or this may be the root of my issue
- the docker run command successfully creates and enters the container
- the bazel mediapipe sample invocation fails with a very cryptic and I suspect partially clipped bazel versioning issue (likely improper parsing/rendering of formatting/escape characters in the message?).  Needless to say, any other attempt to use bazel to run mediapipe content fails similarly.
- any subsequent attempt to invoke anything whatsoever involving bazel from within the container (even after several exit/stop/start/attach cycles) yields the same error.  Even e.g. `bazel version` to check/verify the version shows the same error about a version mismatch.
- it seems docker is not quite set up to readily allow manually pointing apt at the bazel repo and versioning that way, but manual installs of explicitly bazel 5.0.0, via hand-copied linux install .sh scripts, to /root/bin and/or /user/local/lib/bazel/bin, and invocations of either the $PATH'd default `bazel` or explicit `/path/to/bazel`, likewise yield the cryptic error

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
Longstanding development machine has several versions of Visual Studio installed, most recently 2019, including C++ development.  Git is installed.  WSL is installed.  Installed Windows-side versions of e.g. bazel and opencv, although my understanding is that these ought to be irrelevant to the Docker/WSL context.  If you want more specific details, I'll need to know exactly what to look for where.

Otherwise, followed https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker directly, reproducing the same results on fresh checkouts using PowerShell, Admin PowerShell, and basic Command Prompt.
`git clone https://github.com/google/mediapipe.git`
`cd mediapipe`
`docker build --tag=mediapipe .`
`docker run -it --name mediapipe mediapipe:latest`
(in container) `GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world`

**Complete Logs:**

```
D:\Unity_mediapipe_docker\mediapipe>docker build --tag=mediapipe .
[+] Building 2.9s (19/19) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 2.56kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 58B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ubuntu:18.04                                                    0.6s
 => [ 1/14] FROM docker.io/library/ubuntu:18.04@sha256:d21b6ba9e19feffa328cb3864316e6918e30acfd55e285b5d3df1d8ca3  0.0s
 => [internal] load build context                                                                                  2.1s
 => => transferring context: 312.26MB                                                                              2.1s
 => CACHED [ 2/14] WORKDIR /io                                                                                     0.0s
 => CACHED [ 3/14] WORKDIR /mediapipe                                                                              0.0s
 => CACHED [ 4/14] RUN apt-get update && apt-get install -y --no-install-recommends         build-essential        0.0s
 => CACHED [ 5/14] RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++  0.0s
 => CACHED [ 6/14] RUN pip3 install --upgrade setuptools                                                           0.0s
 => CACHED [ 7/14] RUN pip3 install wheel                                                                          0.0s
 => CACHED [ 8/14] RUN pip3 install future                                                                         0.0s
 => CACHED [ 9/14] RUN pip3 install six==1.14.0                                                                    0.0s
 => CACHED [10/14] RUN pip3 install tensorflow==1.14.0                                                             0.0s
 => CACHED [11/14] RUN pip3 install tf_slim                                                                        0.0s
 => CACHED [12/14] RUN ln -s /usr/bin/python3 /usr/bin/python                                                      0.0s
 => CACHED [13/14] RUN mkdir /bazel &&     wget --no-check-certificate -O /bazel/installer.sh "https://github.com  0.0s
 => CACHED [14/14] COPY . /mediapipe/                                                                              0.0s
 => exporting to image                                                                                             0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:32158b87535ee0b1eb6bb9f12e01f8a46e8ccd1fb8ea8e9233ac3455c90ace49                       0.0s
 => => naming to docker.io/library/mediapipe                                                                       0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

D:\Unity_mediapipe_docker\mediapipe>docker run -it --name mediapipe mediapipe:latest
root@4394842a1dc5:/mediapipe# GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world
 (specified in /mediapipe/.bazelversion), but it wasn't found in /usr/local/lib/bazel/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

You can download the required version directly using this command:
-linux-x86_64)&& chmod +x bazel-5.0.0url -fLO https://releases.bazel.build/5.0.0
root@4394842a1dc5:/mediapipe# bazel version
 (specified in /mediapipe/.bazelversion), but it wasn't found in /usr/local/lib/bazel/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

You can download the required version directly using this command:
-linux-x86_64)&& chmod +x bazel-5.0.0url -fLO https://releases.bazel.build/5.0.0
root@4394842a1dc5:/mediapipe# which bazel
/usr/local/bin/bazel
root@4394842a1dc5:/mediapipe#
```

**Comment by sureshdagooglecom** [comment]
Hi @NNskelly ,
Could you provide steps to reproduce this issue.

**Comment by NNskelly** [comment]
As cited, it has been 100% reproducible for me by following the steps listed on https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker verbatim.  The inlined command window dump contains the entire process after the initial git pull, but I could retry from the top and copy the output including that if it's strictly necessary.
```
git clone https://github.com/google/mediapipe.git
cd mediapipe
docker build --tag=mediapipe .
docker run -it --name mediapipe mediapipe:latest
```
at which point I am successfully in the container, but any and every invocation of bazel for any reason yields the error:
`GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world`
or
`bazel version`
or
`/usr/local/bin/bazel version`
or even just
`bazel`

**Comment by sureshdagooglecom** [comment]
Hi @NNskelly ,
Run without CACHE, "--no-cache", show the logs from that docker build.  
otherwise, unclear why this docker image would lack a working "bazel"
