### ISSUE TITLE
Mediapipe Solution Core & FaceMesh 0.8.10 (Maven Repo) BUG!!!

### ISSUE THREAD

**Issue by PraveshARMedical** [google/mediapipe#3326]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Developed on Windows 10, Tested on Android 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy A70
- Programming Language and version ( e.g. C++, Python, Java): Java
- [MediaPipe version](https://github.com/google/mediapipe/releases): Latest maven repository 0.8.10 (Updated today) for solution core and face mesh
- Solution ( e.g. FaceMesh, Pose, Holistic ): Solution Core & Face Mesh
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): Android Studio Bumblebee | 2021.1.1 Patch 1, SDK Compile version: 31
Windows 10 10.0
Memory: 16 GB
Cores: 8

**Describe the current behaviour: We have an app that uses iris landmarks from Face mesh to get the length of the iris. With that, we try to measure the width of the mouth. It was working up until today's update hit. Somehow, the landmark points are not providing the correct values. 
It was working until version 0.8.9-alpha-5.

**Describe the expected behaviour: Distance between landmarks 61 and 291 is showing 0.

**Comment by schmidt-sebastian** [comment]
@PraveshARMedical Thanks for reporting this. We are able to reproduce this issue locally.

**Comment by PraveshARMedical** [comment]
I hope it gets fixed soon. Meanwhile, where can I find new things/update logs added to the latest Facemesh build?

**Comment by jiuqiant** [comment]
It should be fixed by 0.8.10.1-alpha-1. Sorry for the breakage.
