### ISSUE TITLE
How to crop out the letterbox paddings from the output of ImageTransformationCalculator?

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#333]
ImageCroppingCalculator is not able to handle letterbox_padding output from ImageTransformationCalculator.

**Comment by fanzhanggoogle** [comment]
Could you describe your question in more detail?
If you don't want to have padding on the image, you can try eg. [STRECH](https://github.com/google/mediapipe/blob/d144e564d8f48737f1bf684ee741c9ccf6a5909d/mediapipe/gpu/scale_mode.proto#L22) mode for scale.

**Comment by yxchng** [comment]
ImageTransformationCalculator gives an output called `letterbox_padding` which stores the pad information used by the calculator. 

This information should be able to be used by ImageCroppingCalculator to return us the original image size without padding. Otherwise how can I get back the original image size without padding?

**Comment by fanzhanggoogle** [comment]
If I understand correctly, you want to crop an image after it's transformed but with padding removed? In that case, you are correct that we don't support handling padding in the cropping calculator. However, you can use [FILL_AND_CROP](https://github.com/google/mediapipe/blob/d144e564d8f48737f1bf684ee741c9ccf6a5909d/mediapipe/gpu/scale_mode.proto#L31) in ImageTransformationCalculator which gives you an image without padding and you can directly use the result in cropping calculator and get an image without padding. Does that help?

**Comment by fanzhanggoogle** [comment]
Feel free to re-open if you have further questions.
