### ISSUE TITLE
Knift has a memory leak in Android

### ISSUE THREAD

**Issue by hbyjw** [google/mediapipe#3330]
I use AAR files to develop applications, and there is a memory leak. Then I tested that the APK generated using the script in the document will still leak memory.

**System information** (Please provide as much relevant information as possible)

- custom code: 
  1. `mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl` replace `libopencv_java3`  with `libopencv_java4`
  2. `mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/AndroidManifest.xml`  -> `applaciton add  android:debuggable="true"`
 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
  1. Linux Ubuntu 20.04 ,Android 9 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
  1. Samsung Galaxy Note8
 
- Programming Language and version ( e.g. C++, Python, Java):
  1. Java
- [MediaPipe version](https://github.com/google/mediapipe/releases):
  version:The latest code on GitHub
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ): 
   1. KNIFT
 

**Describe the current behavior:**
1. Use the following command to generate the APK file.
```shell
# Switch to OpenCV 4
sed -i -e 's:3.4.3/opencv-3.4.3:4.0.1/opencv-4.0.1:g' WORKSPACE
sed -i -e 's:libopencv_java3:libopencv_java4:g' third_party/opencv_android.BUILD

# Build and install app
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/templatematchingcpu


# Switch back to OpenCV 3
sed -i -e 's:4.0.1/opencv-4.0.1:3.4.3/opencv-3.4.3:g' WORKSPACE
sed -i -e 's:libopencv_java4:libopencv_java3:g' third_party/opencv_android.BUILD

```
2. Install APK, and then use the profiler of Android studio to detect memory changes. The mobile phone is placed on the desktop without moving, and there is no object to be recognized in the camera viewfinder box.

https://user-images.githubusercontent.com/13883357/167331161-eb4cd0fe-ffbc-449c-9cda-072452f3db66.MOV

3.  Run out of memory until the application crashes.
![截屏2022-05-09 10 54 17](https://user-images.githubusercontent.com/13883357/167332890-a8f70a59-4a30-419e-ae65-95cdad2e8f18.png)

  
**Describe the expected behavior:**

**Standalone code to reproduce the issue:**

**Other info / Complete Logs :**
[knift.log](https://github.com/google/mediapipe/files/8648506/knift.log)

**Comment by sureshdagooglecom** [comment]
Hi @hbyjw ,
Did you get a chance to closed issue https://github.com/google/mediapipe/issues/1089

**Comment by hbyjw** [comment]
@sureshdagooglecom 

I'll test the method used #1089 tomorrow

**Comment by hbyjw** [comment]
@sureshdagooglecom 

I modified the code according to #1089 information, but there will still be memory leakage. When a value is reached, the camera preview interface will be stuck in the last position

![KNIFT_BUG](https://user-images.githubusercontent.com/13883357/167565762-f5420811-07ce-46d9-8894-cce3a6e80ffd.png)




https://user-images.githubusercontent.com/13883357/167572895-ce3fe1ac-0de6-4a2f-a613-441f412a3072.MOV

**Comment by hbyjw** [comment]
@sureshdagooglecom 

~~不知道下面的图片对解决问题是否有帮助，这是使用的Android Studio 中的Profiler  Record Natvie allocations~~

I don't know whether the following pictures are helpful to solve the problem. This is the profiler record natvie allocations in Android studio

![截屏2022-05-11 15 03 20](https://user-images.githubusercontent.com/13883357/167789319-7571a70e-2d77-49ee-98d4-4f9475eb2e6e.png)

**Comment by hbyjw** [comment]
I added some code

`mediapipe/calculators/image/feature_detector_calculator.cc` -> `absl::Status FeatureDetectorCalculator::Process(CalculatorContext* cc)`  add `  free(tensor.data.data);// 释放内存 `

![截屏2022-05-12 17 45 29](https://user-images.githubusercontent.com/13883357/168042724-2bb46771-3373-48c2-91aa-0f082533b696.png)


I don't know whether the added code is appropriate. My C + + level is very low. The added results basically meet my needs.

![截屏2022-05-12 17 41 14](https://user-images.githubusercontent.com/13883357/168041790-5ae9d357-7734-4205-99b4-4bc7740c1fc6.png)

**Comment by sureshdagooglecom** [comment]
Hi @hbyjw ,
Are you still facing any issues w.r.t above issue.

**Comment by hbyjw** [comment]
@yegenzhi 

 不知道我的操作是否符合你的意思，见图片。这样操作生成的aar以及 `mobile_cpu.binarypb` 会出现如下错误。
因为要获取标记框的坐标，我参考https://github.com/google/mediapipe/issues/1624#issuecomment-782265180
 在labeled_detections中添加了TimedBoxProtoList的内容 

English is not good. The following content is translated by software

I don't know whether my operation is in line with your meaning. See the picture. New AAR and ` mobile_cpu.binarypb ` has the following error.
I need to get the coordinates of the marker box, so refer to https://github.com/google/mediapipe/issues/1624#issuecomment -782265180  added `TimedBoxProtoList` to `labeled_detections`

```log
2022-05-20 11:18:42.251 20734-20842/com.yjw.yujiaweitestknift E/native: E20220520 11:18:42.251859 20842 graph.cc:472] ; Input Stream "patches" for node with sorted index 4 does not have a corresponding output stream.
2022-05-20 11:18:42.256 20734-20842/com.yjw.yujiaweitestknift E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.yjw.yujiaweitestknift, PID: 20734
    com.google.mediapipe.framework.MediaPipeException: unknown: ; Input Stream "patches" for node with sorted index 4 does not have a corresponding output stream.
        at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
        at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:324)
        at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:553)
        at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:421)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:439)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:403)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:338)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$IXJjtE68JMV2CMJNQcFYhTUqhj8.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)

```


![截屏2022-05-20 11 22 37](https://user-images.githubusercontent.com/13883357/169444154-3f6b8033-b09c-4dfa-a546-484d24202c5d.png)

**Comment by sureshdagooglecom** [comment]
Hi @hbyjw ,
This appears to be a leak in native libraries specific to this Knift demo.  
We will investigate further when we can.

**Comment by hbyjw** [comment]
@sureshdagooglecom 
OK.

**Comment by ayushgdev** [comment]
Hello @hbyjw 
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
