### ISSUE TITLE
Serious Performance decrease in windows desktop on all models in some release after 0.8.4

### ISSUE THREAD

**Issue by ThanosHugin** [google/mediapipe#3331]
We updated recently to 0.8.9 and noticed some serious performance drop on all models! (to the point where it is unusable in our project)
Before that we have been using mediapipe 0.8.4 for our windows application and the performance was really good.
Is anyone aware of some new features that might be causing this ? (note in windows it is all CPU) 
To verify it wasn't something on our side we  run the hands demo in both versions and the performance drop was very obvious there too 
If you want me I can try all new releases inbetween one by one to pinpoint where the drop appeared
Thanks in advance for any help!

**Comment by sureshdagooglecom** [comment]
Hi @ThanosHugin ,
Could you share any reference videos w.r.t above isssue.

**Comment by ThanosHugin** [comment]
Hello @sureshdagooglecom :)
here are two videos I captured on my not so powerful laptop using 0.8.4 and 0.8.9 respectively

https://user-images.githubusercontent.com/73824077/168268613-d0baff14-5f58-4de7-86ab-8f4a459c7b37.mp4

https://user-images.githubusercontent.com/73824077/168268797-13fa1c1a-c744-45c3-800e-5e4ccbd7e75a.mp4

turns out the difference in performance is not as dramatic as i originally thought but there is some slowdown 
there
can you notice it ?

**Comment by ThanosHugin** [comment]
hmm ok turns out i was wrong
added some code to measure performance:

    auto start = std::chrono::steady_clock::now();
    if (!poller.Next(&packet)) break;
    auto& output_frame = packet.Get<mediapipe::ImageFrame>();
    auto end = std::chrono::steady_clock::now();
    auto ms =  std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
    total_ms += ms;
    frame_count++;
    if ( frame_count > 40)
    {
        total_ms /= frame_count;
        std::cout << "Average elapsed time in ms:" << total_ms << std::endl;  
        total_ms = 0;
        frame_count = 0;
    }

here are the results for the different releases
0.8.4
c:\Projects\HTMediaPipe\mediapipe>bazel-bin\mediapipe\examples\desktop\hand_tracking\hand_tracking_cpu.exe --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Replacing 117 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 2 partitions.
INFO: Replacing 64 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 1 partitions.
Average elapsed time in ms:21
Average elapsed time in ms:33
Average elapsed time in ms:29
Average elapsed time in ms:24
Average elapsed time in ms:26
Average elapsed time in ms:24
Average elapsed time in ms:28
Average elapsed time in ms:32
Average elapsed time in ms:26
Average elapsed time in ms:37
Average elapsed time in ms:37
Average elapsed time in ms:28
Average elapsed time in ms:28
Average elapsed time in ms:32
Average elapsed time in ms:36
[ WARN:0] terminating async callback


0.8.6
c:\Projects\HTMediaPipe\mediapipe>bazel-bin\mediapipe\examples\desktop\hand_tracking\hand_tracking_cpu.exe --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Average elapsed time in ms:28
Average elapsed time in ms:30
Average elapsed time in ms:28
Average elapsed time in ms:34
Average elapsed time in ms:27
Average elapsed time in ms:33
Average elapsed time in ms:26
Average elapsed time in ms:27
Average elapsed time in ms:27
Average elapsed time in ms:30
Average elapsed time in ms:37
[ WARN:0] terminating async callback


0.8.8
c:\Projects\HTMediaPipe\mediapipe>bazel-bin\mediapipe\examples\desktop\hand_tracking\hand_tracking_cpu.exe --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Average elapsed time in ms:8
Average elapsed time in ms:9
Average elapsed time in ms:7
Average elapsed time in ms:8
Average elapsed time in ms:10
Average elapsed time in ms:12
Average elapsed time in ms:10
Average elapsed time in ms:14
Average elapsed time in ms:10
Average elapsed time in ms:12
Average elapsed time in ms:12
Average elapsed time in ms:14
Average elapsed time in ms:14
Average elapsed time in ms:14
Average elapsed time in ms:13
Average elapsed time in ms:14
Average elapsed time in ms:14
Average elapsed time in ms:13
Average elapsed time in ms:13



0.8.9
c:\Projects\HTMediaPipe\mediapipe>bazel-bin\mediapipe\examples\desktop\hand_tracking\hand_tracking_cpu.exe --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Average elapsed time in ms:26
Average elapsed time in ms:28
Average elapsed time in ms:25
Average elapsed time in ms:30
Average elapsed time in ms:29
Average elapsed time in ms:25
Average elapsed time in ms:27
Average elapsed time in ms:32
Average elapsed time in ms:33
Average elapsed time in ms:27
Average elapsed time in ms:20
Average elapsed time in ms:28
Average elapsed time in ms:27
[ WARN:0] terminating async callback

looks like 0.8.4 and 0.8.9 perform very similarly
(interestingly 0.8.8 seems to be performing significantly better but the hand detection seemed to be problematic!
not sure what is going on there)
i will close this issue now
