### ISSUE TITLE
Proper way to clean up FrameProcessor in Android?

### ISSUE THREAD

**Issue by dkmoon** [google/mediapipe#3332]
Hello there,

I'm wondering how to clean up FrameProcessor in Android.
I took a look into `basic/MainActivity.java` in the example directory, but it seems it closes only an external converter instance and leaves a FrameProcessor instance alive. Is this an expected way?

I tried to close by calling `FrameProcessor.close()` but I found it sometimes hangs regardless of calling `FrameProcessor.getGraph().closeAllInputStreams()`.

I'm asking this question because I think I need to re-create a FrameProcessor when my input side packet gets changes. (My understanding is input side packet is a kind of constant and I cannot change it as soon as the graph starts. I searched from previous questions and there was a recommendation to use input stream instead of input side packet, but my case wouldn't work because I need to feed it to `FaceGeometryPipelineCalculator` which takes camera environment as a side packet.

Thank you.

**Comment by dkmoon** [comment]
I found @sureshdagooglecom tagged `solution:face_geometry`. Actually, I'm not using the solutions. Instead, I built my aar according to the manual and succeeded to run a graph using a face geometry. My initial question was what's a code sequence to shutdown processor cleanly. I tried a code like below, but got an error.

```
processor.getGraph().closeAllInputStreams();
processor.getGraph().cancelGraph();
processor.close();
```

**Comment by sureshdagooglecom** [comment]
Hi @dkmoon ,
Could you share latest error so that we can investigate further on this.
