### ISSUE TITLE
Not able to render assets in face effect.

### ISSUE THREAD

**Issue by Gojo1729** [google/mediapipe#3333]
**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): Nope
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Realme X7 5G
- [MediaPipe version](https://github.com/google/mediapipe/releases):  v0.8.9
- Bazel version (if compiling from source): bazel 5.0.0
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): 

**Describe the current behavior:**
I'm building the apk file using the BUILD file present inside  `//mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect using the command` - 

`bazel build -c opt --strip=ALWAYS     --host_crosstool_top=@bazel_tools//tools/cpp:toolchain     --fat_apk_cpu=arm64-v8a,armeabi-v7a     --legacy_whole_archive=0     --features=-legacy_whole_archive     --copt=-fvisibility=hidden     --copt=-ffunction-sections     --copt=-fdata-sections     --copt=-fstack-protector     --copt=-Oz     --copt=-fomit-frame-pointer     --copt=-DABSL_MIN_LOG_LEVEL=2     --linkopt=-Wl,--gc-sections,--strip-all     //mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect:faceeffect.apk` . The apk file is getting built without any error but I'm not able see any effects rendered on my screen. 

**Describe the expected behavior:**
See the effects rendered on the screen.

**Other info / Complete Logs :**
I tried copying the code under faceeffect directory and built the face effect aar file, by setting `USE_FACE_DETECTION_INPUT_SOURCE` 
I was able to render only the axis asset.

**Comment by Gojo1729** [comment]
@sureshdagooglecom Any updates on this ?

**Comment by sureshdagooglecom** [comment]
Hi @Gojo1729 ,
Could you provide steps to reproduce this issue.

**Comment by Gojo1729** [comment]
@sureshdagooglecom Just build the android binary for face effect using BUILD file present in `\\mediapipe\examples\android\src\java\com\google\mediapipe\apps\faceeffect` using the command 
```
bazel build -c opt --strip=ALWAYS --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a --legacy_whole_archive=0 --features=-legacy_whole_archive --copt=-fvisibility=hidden --copt=-ffunction-sections --copt=-fdata-sections --copt=-fstack-protector --copt=-Oz --copt=-fomit-frame-pointer --copt=-DABSL_MIN_LOG_LEVEL=2 --linkopt=-Wl,--gc-sections,--strip-all //mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect:faceeffect.apk
```

And install the apk, this apk is not rendering the assets which it was suppose to render - glasses, face mask

**Comment by Gojo1729** [comment]
@sureshdagooglecom  Any updates on this ?

**Comment by Gojo1729** [comment]
@sgowroji Any suggestions here ? The rest all apks built using the BUILD file present inside 
`mediapipe\mediapipe\examples\android\src\java\com\google\mediapipe\apps`  are working fine apart from `faceeffect`

**Comment by Gojo1729** [comment]
@sureshdagooglecom It's working in v0.8.10

**Comment by sureshdagooglecom** [comment]
Hi @Gojo1729 ,
Are you facing any challanges with v0.8.10?

**Comment by Gojo1729** [comment]
The issue is with v0.8.9, I think I might have made some unnoticed changes in the files, after creating a new clone it's working
