### ISSUE TITLE
AutoFlip how make output video more clearer

### ISSUE THREAD

**Issue by jay-col** [google/mediapipe#3334]
Compared with the original video, the output video is blurred.
Anyone can help?

For questions on how to work with MediaPipe, or support for problems that are not verified bugs in MediaPipe, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mediapipe) and [Slack](https://mediapipe.page.link/joinslack) communities.

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/google/mediapipe/security).

**Comment by sureshdagooglecom** [comment]
Hi @jay-col ,
Could you please share any reference video w.r.t above issue.

**Comment by jay-col** [comment]
For example, this video，https://www.youtube.com/watch?v=_uUdJalMaF8，
![Snipaste_2022-05-25_21-25-28](https://user-images.githubusercontent.com/51410924/170273209-439392f5-36ec-4ab4-aa21-da7a75f7a35c.png)
，seems to have intercepted part of it and then zoomed in，can it just clip the center column without zooming in?

**Comment by jay-col** [comment]
> Hi @jay-col , Could you please share any reference video w.r.t above issue.
![image](https://user-images.githubusercontent.com/51410924/170274763-e3014535-4b0b-4583-a614-fb9a3de8ec68.png)
thanks for your reply, for example, this video，https://www.youtube.com/watch?v=_uUdJalMaF8，It looks like it intercepted part of it and then zoomed in to the scale，can it just intercept the whole part in the middle without zooming in?
