### ISSUE TITLE
What is in .data file?

### ISSUE THREAD

**Issue by elYeodeol** [google/mediapipe#3337]
Hey,

I am using the pose solution on Javascript. When I launch my web page, a .data file is requested, is there any way of knowing what the .data file contains? I know that it contains the detection model, but the file is too big to include only that.

is it possible to modify it?

Thank you!

**Comment by sureshdagooglecom** [comment]
Hi @elYeodeol ,
The [something].data file should contain all of the assets needed by the C++ WebAssembly code.  If you want to know more details about the contents, there is also a [something].js file (where the "[something]" part is the same).  If you look at the very end of that .js file, you can see the names (and also can find the sizes) of all assets in the corresponding .data file.

**Comment by sureshdagooglecom** [comment]
Hi @elYeodeol ,
We are closing this issue , if issue still persists please reopen the issue.
