### ISSUE TITLE
Overhead of a FrameProcessor that is not receiving input streams?

### ISSUE THREAD

**Issue by dkmoon** [google/mediapipe#3338]
Hi there,

I'm working for an Android project.
I'm considering to have multiple instances of FrameProcessor (e.g. one for face detection and another for pose detection)
Not all instances will receive input streams at the same time.
Do you think it's OK to have multiple ones? Otherwise, is it better to put all required features in a single big graph and to have only one FrameProcessor?

Thanks.

**Comment by sureshdagooglecom** [comment]
Hi @dkmoon ,
We are looking into this issue , we will revert back in sometime.

**Comment by sureshdagooglecom** [comment]
Hi @dkmoon ,
We don't expect terrible performance from multiple FrameProcessor's.  Please feel free to give that a try first, if that is most convenient for you.  There is likely some performance gain from merging into a single graph, but please try it the easy way first.
