### ISSUE TITLE
Holistic Model in Android 

### ISSUE THREAD

**Issue by ArtanBerisha1** [google/mediapipe#3340]
Hi, 

I was checking android examples that you have implemented, until now I found only 3 examples (with source code): 
- Face Detection
- Face Mesh
- Hands
I also found the .apk file of the Holistic model, so I wanted to ask if there is any plan to release the Holistic demo app with source code like the models mentioned above ?

**Comment by sureshdagooglecom** [comment]
Hi @ArtanBerisha1 ,
We will consider this as a feature request and we will share this with internal teams.

**Comment by CatinoRosalba** [comment]
Hi @ArtanBerisha1,

Did you find an example (source code) for the holistic model? 
It would be very helpful to have an example or some videos/documentation to use the holistic model on android app.
Thank you in advance for your help.

**Comment by EBDitore** [comment]
I would also like to have an example, with pictures and videos if possible, would anyone know of one?

**Comment by ArtanBerisha1** [comment]
Hi @CatinoRosalba ,
No I didn't find any example for holistic model, will have to check the edge detection example first and then hopefully will know how to setup the holistic model.
