### ISSUE TITLE
scaled 3d landmarks Objectron

### ISSUE THREAD

**Issue by UX3D-mazzini** [google/mediapipe#3341]
Solution: Objectron
Language: Javascript

I'm trying to render a cube on top of the predicted landmarks of the shoe using Three.js and the Objectron javascript API.
The model predicts 2d landmarks, and the 3d_landmarks are obtained using the epnp algorithm.

If I 'unproject' the 2d landmarks onto the world space, I obtain some world coordinates, that I expect to be the same as the 3d_landmarks predicted coordinates. (according to the coordinates documentation)

The problem is that the 3d coordinates are not reaching the borders of the canvas, they seem to be scaled in a way that they never reach the corresponding bigger values of the 2d unprojected landmarks.

Seeing this [issue](https://github.com/google-research-datasets/Objectron/issues/57#issuecomment-1029305891)  maybe is a scale problem, but I would like to understand how the focal length and the principal point influence my solution. 
Maybe it's because I didn't set the focal length and the principal point. but I don't understand if this is something related to the hardware device I use or to some projection matrix or the camera object parameters.
I would like to know how to better understand the 3d_landmarks respect to the camera

**Comment by UX3D-mazzini** [comment]
Can somebody help with this?

**Comment by kaugray** [comment]
> Can somebody help with this?

did you find a way to work with this?
i have been trying to achieve the same result

**Comment by ayushgdev** [comment]
Hello @UX3D-mazzini 
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
