### ISSUE TITLE
Running the calculator graph takes infinite time

### ISSUE THREAD

**Issue by anvuong48** [google/mediapipe#3343]
Hi everyone,

-I am trying to run mediapipe application for tracking iris after building successfully. 
-My command line is below:
**bazel-bin\mediapipe\examples\desktop\iris_tracking\iris_tracking_cpu_video_input   --calculator_graph_config_file=mediapipe/graphs/iris_tracking/iris_tracking_cpu_video_input.pbtxt     --input_side_packets=input_video_path="C://Users//anv1581s//Downloads//testvid.mp4",output_video_path="D://anv1581s//anv//VideosMediapipe"**

After using this command line, it starts to run the calculator graph. But it takes infinite time. Nothing happens after that. You can see attached image
![image](https://user-images.githubusercontent.com/45357524/168023034-d20f1e7d-8bae-4e92-84bd-f857dd34a114.png)

- I tried to change slash to backslash, but it did not work. Does anyone have solution for this problem?

Thank you very much

 Best regards

**Comment by sureshdagooglecom** [comment]
Hi @anvuong48 ,
Could you please check [this] document to understand the time stamp on calculators.

**Comment by anvuong48** [comment]
Hi @sureshdagooglecom 

Sorry for my late reply. I solved  this problem. The problem comes from my input video. I could not open it on windows. That's why the calculator cannot run it. I just need to change the input video, then the problem was solved.

**Comment by anvuong48** [comment]
But I am facing to another problem now. Before I used a tflite model from my colleauge and it worked. But when I created my own tflite model and applied it to mediapipe iris tracking. It did not work and this below error happened.

![image](https://user-images.githubusercontent.com/45357524/169260615-0953e679-b4ae-44da-859e-71adf6e3a492.png)

Do you know why? Thank you very much

**Comment by sureshdagooglecom** [comment]
Hi @anvuong48 ,
Could you please compare both tflite models and check  the difference , hopefully versions might be the issue.

**Comment by anvuong48** [comment]
Hi @sureshdagooglecom ,
 
I tried to compare these two tflite models with a software named netron https://github.com/lutzroeder/netron/releases/tag/v5.8.1

- These two files are exactly same. There are no differences between them. But it still did not work with my tflite model :( I don't know why

**Comment by anvuong48** [comment]
I checked these two tfllite models again and saw this below differences

- From my tflite model
![image](https://user-images.githubusercontent.com/45357524/169704784-8b3cf593-0b84-463d-a317-41e7c8960e11.png)

- From tflite model of my colleauge
![image](https://user-images.githubusercontent.com/45357524/169704838-eee0163e-30ba-4041-aa64-b74bddde2920.png)

They have different order. Do you know why?

**Comment by sureshdagooglecom** [comment]
Hi @anvuong48 ,
I assume there are no useful log warnings or error messages.
Suggestion: add logging print statements to some Calculator::Open and Calculator::Process functions, and see how far along the graph initialization gets.
