### ISSUE TITLE
Tools to generated  mesh_3D.proto format txt file out of .obj file

### ISSUE THREAD

**Issue by 1733208392** [google/mediapipe#3344]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): face effect
- Programming language : Python
- Are you willing to contribute it (Yes):

**Describe the feature and the current behavior/state:**
As described bye the title. It seems quite difficult to generated the .pbtxt file with the required mesh_3d.proto format from a 3d .obj file. Do you guys have a script to do this? 

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Please specify the use cases for this feature:**
When developing other customised face effect, developers need to create theirs own 3D model then rendering with the estimated face geometry. 

**Any Other info:**

**Comment by sureshdagooglecom** [comment]
Hi @1733208392 ,
Could you please share more information to investigate this issue further.

**Comment by 1733208392** [comment]
According to the definition of mesh_3d.proto

`syntax = "proto2";

package mediapipe.face_geometry;

option java_package = "com.google.mediapipe.modules.facegeometry";
option java_outer_classname = "Mesh3dProto";

message Mesh3d {
  enum VertexType {
    // Is defined by 5 coordinates: Position (XYZ) + Texture coordinate (UV).
    VERTEX_PT = 0;
  }

  enum PrimitiveType {
    // Is defined by 3 indices: triangle vertex IDs.
    TRIANGLE = 0;
  }

  optional VertexType vertex_type = 1;
  optional PrimitiveType primitive_type = 2;
  // Vertex buffer size is a multiple of the vertex size (e.g., 5 for
  // VERTEX_PT).
  repeated float vertex_buffer = 3;
  // Index buffer size is a multiple of the primitive size (e.g., 3 for
  // TRIANGLE).
  repeated uint32 index_buffer = 4;
}`
The 3D effect object such as glass should be composed as below format

`vertex_type: VERTEX_PT
primitive_type: TRIANGLE
vertex_buffer: -2.865879
vertex_buffer: 4.170119
vertex_buffer: 6.039360
vertex_buffer: 0.736954
vertex_buffer: 0.299098

vertex_buffer: -2.865879
vertex_buffer: 7.625508
vertex_buffer: 6.026333
vertex_buffer: 0.999900
vertex_buffer: 0.563411
.
.
index_buffer: 0
index_buffer: 1
index_buffer: 4
index_buffer: 1
index_buffer: 5
index_buffer: 4
.
.
.
`
However, normally, the 3D object made out of tools such as 3dmax or blender can be exported as .obj format, which is as below

`# Blender v2.92.0 OBJ File: ''
# www.blender.org
mtllib box unwrap.mtl
o Plane_Plane.001

#[Vertices: Vertex x y z]
v -2.865879 4.170119 6.039360 
v -2.865879 7.625508 6.026333
v 2.865879 4.178114 6.039360
v 2.865879 7.625508 6.039361
v -2.865879 4.170119 5.803236
v 2.865879 7.620375 5.800169
v 2.865879 4.178153 5.800169
v -2.865879 7.625508 5.800169
vt 0.736954 0.299098
vt 0.999900 0.563411
vt 0.299127 0.735878
vt 0.561461 0.999578
vt 0.718962 0.281062
vt 0.000100 0.436653
vt 0.438155 0.000100
vt 0.018364 0.454897
vt 0.999900 0.034796
vt 0.017926 0.979865
vt 0.280900 0.717607
vt 0.982666 0.017521
vt 0.035758 0.998529
vt 0.455421 0.017346

vn 0.0000 -0.0038 -1.0000
vn 0.0020 -0.0005 -1.0000
vn 0.0004 -0.0033 -1.0000
vn 0.0023 0.0000 -1.0000
vn -0.0014 1.0000 0.0000
vn -0.0014 1.0000 0.0002
vn -0.0000 -0.9998 0.0215
vn 1.0000 0.0000 0.0000
vn -1.0000 -0.0000 0.0000
vn 0.0005 -0.0000 1.0000
vn 0.0001 0.0007 1.0000
vn 0.0004 0.0002 1.0000
vn 0.0000 0.0009 1.0000
vn -0.0009 -1.0000 0.0000
usemtl None
s 1

#[Faces: ]
f 1/1/1 2/2/2 3/3/3
f 2/2/2 4/4/4 3/3/3
f 1/1/5 3/3/6 5/5/5
f 4/6/7 2/7/7 6/8/7
f 2/9/8 1/1/8 5/5/8
f 3/3/9 6/10/9 7/11/9
f 2/9/8 5/5/8 8/12/8
f 6/10/9 3/3/9 4/13/9
f 7/11/10 6/8/11 5/5/12
f 5/5/12 6/8/11 8/14/13
f 6/8/14 2/7/14 8/14/14
f 5/5/5 3/3/6 7/11/6
`
Making the conversion can be very tedious, because when you generate the vertex buffer array by combining the Vertex position (x,y,z) and the UV texture map 2d coordinates(u,v), we actually made a new vertex buffer array with completely different indices so that when you generate the index buffer array you have to change the values accordingly. e.g 2/9 -> 4 based on the indices of your generated vertex array. 

<img width="335" alt="image" src="https://user-images.githubusercontent.com/52324327/168418415-51ecc618-c026-4338-aecc-c60525e8732a.png">

**Comment by sureshdagooglecom** [comment]
Hi @1733208392 ,
 We don’t have a script or tool  to convert  but we can work on that.
Consider: "We welcome your contribution or suggestions for this tooling".
