### ISSUE TITLE
Decoding the iris detection output

### ISSUE THREAD

**Issue by FSet89** [google/mediapipe#3345]
According to the [model card](https://drive.google.com/file/d/1bsWbokp9AklH2ANjCfmjqEzzxO1CNbMu/preview), the output for iris detection are 74+5 2D landmarks coordinates. However, I am getting 213 outputs, including negative numbers. How can I retrieve the specified coordinates?

**Comment by sureshdagooglecom** [comment]
Hi @FSet89 ,
Could you share your code changes w.r.t above issue to investigate further on this.

**Comment by FSet89** [comment]
```
model_path = 'iris_landmark.tflite'
interpreter = tf.lite.Interpreter(model_path=model_path)
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print(output_details)
```

[{'name': 'output_eyes_contours_and_brows', 'index': 384, **'shape': array([  1, 213]**, dtype=int32), 'shape_signature': array([  1, 213], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'output_iris', 'index': 385, 'shape': array([ 1, 15], dtype=int32), 'shape_signature': array([ 1, 15], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

**Comment by kuaashish** [comment]
Hello @FSet89,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
