### ISSUE TITLE
How count model infer time in C++ ubuntu environment?

### ISSUE THREAD

**Issue by NeekHua** [google/mediapipe#3346]
as the title

**Comment by sureshdagooglecom** [comment]
Hi @NeekHua ,
We have closed issue https://github.com/google/mediapipe/issues/657 for counting model inference .

**Comment by NeekHua** [comment]
@sureshdagooglecom  thanks your reply. that issue about android.
But I worked in linux desktop.And I changes   [https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/demo_run_graph_main.cc](url) .
changes details is following:
`    clock_t start   = clock();
    MP_RETURN_IF_ERROR(graph.AddPacketToInputStream(
        kInputStream, mediapipe::Adopt(input_frame.release())
                          .At(mediapipe::Timestamp(frame_timestamp_us))));
    
    // Get the graph result packet, or stop if that fails.
    
    mediapipe::Packet packet;
    if (!poller.Next(&packet)) break;
    
    auto& output_frame = packet.Get<mediapipe::ImageFrame>();
    clock_t end   = clock();`
I don't know if this is the infer time of the model.

**Comment by sureshdagooglecom** [comment]
Hi @NeekHua ,
While trying to get GraphProfiler working. you can use  this workaround,  calling 2x .addPacketCallback() to get the elapsed time between 2 streams on the graph.

Ex.

 processor.getGraph().addPacketCallback("palm_detections", new PacketCallback(){

      @Override
      public void process(Packet packet)
      {
          Log.d("MEDIAPIPE", "palm_detections timestamp="  +  System.currentTimeMillis() );
      }

  });
Then you can  add another one to the second Stream on the graph and subtract both timestamps. This is not accurate given the asynchronous nature of the library but is best you could get at the moment.

**Comment by NeekHua** [comment]
Hello@sureshdagooglecom,
I don't catch your meaning . your means is add 
this code to graphprofiler?
```
processor.getGraph().addPacketCallback("palm_detections", new PacketCallback(){

  @Override
  public void process(Packet packet)
  {
      Log.d("MEDIAPIPE", "palm_detections timestamp="  +  System.currentTimeMillis() );
  }

});
```

**Comment by sureshdagooglecom** [comment]
Hi @NeekHua ,
Yes, that needs to be added to the graphprofiler.
