### ISSUE TITLE
In iOS Pose Tracking Demo, how can I get the raw image that I input?

### ISSUE THREAD

**Issue by jiemi** [google/mediapipe#3347]
Hi!
In iOS Pose Tracking Demo, image is call back by delegate but the image has been manipulated just like the picture below,there is 
 a big red box , blue backgroud and many key points
![image](https://user-images.githubusercontent.com/14103123/168477869-53f375d8-1060-418a-b5a4-9b9b7df67178.png)
I want to get the orignal  image ,is there a way to get that?If there is not, How can I synchronize the camera render in opengl view  and algorithm results?

Any help would be appreciated.

**Comment by sureshdagooglecom** [comment]
Hi @jiemi ,
Could you provide steps to reproduce this issue.
