### ISSUE TITLE
ImageCroppingCalculator has an assertion statement that prevents it being used to crop image to a desired width and height

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#335]
Is this line https://github.com/google/mediapipe/blob/38ee2603a7faf46d4283daaf73e455912307f0ff/mediapipe/calculators/image/image_cropping_calculator.cc#L135 not supposed to exist?

ImageCroppingCalculator can accept desired `width` and `height` options. To use it to crop image to a desired width and height, we do not need `RECT` and `NORM_RECT`. However, with this line, MediaPipe will give the following error when `RECT` and `NORM_RECT` are not specified:

```
I1220 12:16:59.688881 10141 demo_run_graph_main_gpu.cc:56] Initialize the calculator graph.
E1220 12:16:59.689085 10141 demo_run_graph_main_gpu.cc:186] Failed to run the graph: ValidatedGraphConfig Initialization failed.
ImageCroppingCalculator: ; cc->Inputs().HasTag(kRectTag) ^ cc->Inputs().HasTag(kNormRectTag)culator.cc:135) 
```

I have to tried to comment out that line and it works. Therefore, I think it should be removed?

**Comment by fanzhanggoogle** [comment]
Your are right. Thank you very mush for spotting the bug. We fixed the bug internally already and will update in the next release.

**Comment by fanzhanggoogle** [comment]
This should be fixed in the new release.
