### ISSUE TITLE
questions about pose landmark

### ISSUE THREAD

**Issue by suke27** [google/mediapipe#3351]
Hi, 
i have a question about pose landmark, mediapipe-master\mediapipe\modules\pose_landmark\pose_landmark_lite.tflite and pose_landmark_full.tflite models, when we check the models, we found they are the quantified models with fp16. i have a question that,  is there unquantified models? Plz help to check! thanks
![image](https://user-images.githubusercontent.com/30656046/168774545-b32f4dc3-9512-45ca-bfb3-42e6e85dc3a2.png)

**Comment by elYeodeol** [comment]
Hey, maybe you can try to convert your model in other format like .pb and then reconvert it in tflite. It works for me

**Comment by suke27** [comment]
> Hey, maybe you can try to convert your model in other format like .pb and then reconvert it in tflite. It works for me

do you convert it use tensorflow? could you share the tools you used. we check TFLiteConverter, it seems latest TFLiteConverter did not support convert to pb now.

**Comment by elYeodeol** [comment]
You can check this git : https://github.com/PINTO0309/tflite2tensorflow
Using this git will allow you to get your model in various formats including saved_model and onnx. 
Then use this : https://github.com/tensorflow/tensorflow/issues/42425
and transform your subclassing model into tflite, and you wont have the quantized nodes.

It's the only method i found, I think there are much simpler ways

I hope I've helped you

**Comment by sureshdagooglecom** [comment]
Thank you for sharing your resolution in the above https://github.com/google/mediapipe/issues/3351#issuecomment-1128748891.
@suke27 , could you please try once with above comments.
