### ISSUE TITLE
Not found: ValidatedGraphConfig Initialization failed.When I use handtrackinggpu.aar for Android，print：No registered calculator found

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#3352]
I build hand tracking aar or handTrackingGpu.aar，use it in Android error,print:
this is my error information from android stdio log print when I build hand trcking application:
`
    com.google.mediapipe.framework.MediaPipeException: not found: ValidatedGraphConfig Initialization failed.
    No registered object with name: MultiHandDetectionSubgraph; Unable to find Calculator "MultiHandDetectionSubgraph"
    No registered object with name: MultiHandLandmarkSubgraph; Unable to find Calculator "MultiHandLandmarkSubgraph"
    No registered object with name: MultiHandRendererSubgraph; Unable to find Calculator "MultiHandRendererSubgraph"
`

**Comment by chensisi0730** [comment]
i have set 
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
mediapipe_aar(
        name = "my_handtrackinggpu_aar",
        calculators = [
        "//mediapipe/graphs/hand_tracking:mobile_calculators",
        "//mediapipe/calculators/core:pass_through_calculator",
        "//mediapipe/calculators/core:constant_side_packet_calculator",
        "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/graphs/hand_tracking/subgraphs:hand_renderer_gpu",
        "//mediapipe/modules/hand_landmark:hand_landmark_tracking_gpu",
       ],
)

**Comment by jiuqiant** [comment]
Which mediapipe graph is used with the aar?

**Comment by chensisi0730** [comment]
I used  the latest  version of the mediapipe repo  (v0.8.10)

**Comment by sureshdagooglecom** [comment]
Hi @chensisi0730 ,
There is a separate target for "multi-hand" subgraphs, ""multi_hand_landmark_gpu".  This needs to be included in the dependencies for the AAR target.

**Comment by chensisi0730** [comment]
> Hi @chensisi0730 , There is a separate target for "multi-hand" subgraphs, ""multi_hand_landmark_gpu". This needs to be included in the dependencies for the AAR target.
 could you tell me  configeration of build file
