### ISSUE TITLE
[EFFECT RENDERER] How to use EFFECT RENDERER in python?

### ISSUE THREAD

**Issue by baolongnguyenmac** [google/mediapipe#3357]
I have found the [document](https://google.github.io/mediapipe/solutions/face_mesh.html#effect-renderer) that talks about using Effect Renderer to apply a 3D filter on face. But it is not written clearly about how I can use it in python (I have tried to search on Google and have not found any tutorial or document). Can you prove document/tutorial in more detail about how I can use Effect Renderer? Thank you!

**Comment by sureshdagooglecom** [comment]
Hi @baolongnguyenmac ,
MediaPipe Effect Renderer  can be used using [this](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/effect_renderer_calculator.cc) calculater.

**Comment by baolongnguyenmac** [comment]
Hi @sureshdagooglecom. Thank you for replying me.
How can I use this file in Python, Android and iOS? Do you have any example?

**Comment by sureshdagooglecom** [comment]
Hi @baolongnguyenmac ,
This is an example renderer, that showcases some basic techniques of face AR. At the current moment, we do not intend to make it as comprehensive as what you might expect from other production-quality AR renderers like Snapchat / Facebook has in their user-facing products

If you are interested in mobile platforms, I'd recommend you to take a lot at https://github.com/google/filament. It shouldn't be hard to drive the Filament renderer using mediapipe.face_geometry.FaceGeometry to create effects of a much better visual quality.
