### ISSUE TITLE
Holistic : right_hand_landmarks.landmark x,y range issue

### ISSUE THREAD

**Issue by timtungGit** [google/mediapipe#3358]
I got a landmark value not in range [0.0, 1.0] when I use Holistic as the picture below 
the xPos/yPos shouldn't be over 1.0, but it happened and caused an error when I tried to draw somthing at that landmark position
How can I deal with this?
![mediapipe_issue_1](https://user-images.githubusercontent.com/90244742/169255640-b3d80404-9b95-42f1-8d06-71062848f77b.png)

**Comment by sureshdagooglecom** [comment]
Hi @timtungGit ,
Holistic can't be used to detect hand landmarks since hand coordinates are trained with different set of data.

**Comment by timtungGit** [comment]
In my case hand landmarks detection works fine, the issue occurred when the hand landmarks still remain in the view, the coordinate value should be [0.0, 1.0], but it wents to 1.0X
![圖片2](https://user-images.githubusercontent.com/90244742/169458768-5317d075-1cbd-4ccd-8d9c-1e8d6165a8a3.jpg)

**Comment by sureshdagooglecom** [comment]
Hi @timtungGit ,
They are normalized values (range [0..1]). Simply scale by the frame dimensions to determine the pixel-based location:
int x = landmark_normal_x * image.width();
int y = landmark_normal_y * image.height();

**Comment by sureshdagooglecom** [comment]
Hi @timtungGit .
Did you scale the output values as below.
int x = landmark_normal_x * image.width();
int y = landmark_normal_y * image.height();
