### ISSUE TITLE
Not detect a new module added in the project

### ISSUE THREAD

**Issue by Ncuaresma** [google/mediapipe#3360]
I compiled de Object detection desktop project and it worked property. 
After that I created two new modules to create new functionality but the project does not detect the modules added and I get this compilation error:
![error 2022-05-19 14-43-35](https://user-images.githubusercontent.com/55456044/169321759-3efcc980-516c-4add-b3be-529ce2fe2558.png)
Does someone know how could I solve it?
Thank you so much.

**Comment by sureshdagooglecom** [comment]
Hi @Ncuaresma ,
Could you please elaborate this issue to investigate further.

**Comment by Ncuaresma** [comment]
> 

Hi @sureshdagooglecom my issue is that I created a class 2 new classes (frame and box) in mediapipe with their correspond files .c and .h, they compile themselves property.
Now I am trying to add some of the functionality I created in the project Object detection, but when I compile everything together the modules I created are not detected so the build fails. (Error in the picture I added before)
I suppose is something about adding dependencies in some files, or something that the builds checks before going to the folder where are located and where I have not added them and so the build does not find these files.

**Comment by Ncuaresma** [comment]
Hello @sureshdagooglecom, to give you more explanation about what I want to do.
I would like to get the object boxes obtained in each frame in the example and after calculate de distance from the camera to the object.
So I have coded the functionality but I can not incorporate it to the example code, the modules I created are not detected. 

Thank you,

**Comment by sureshdagooglecom** [comment]
Hi @Ncuaresma ,
It looks like some source files are not found during compilation.  Could there be a missing dependency in your new build targets?  Can you include your new build target def in the bug report?
