### ISSUE TITLE
How to remove face mesh model from holistic to get better performance

### ISSUE THREAD

**Issue by ayoub-root** [google/mediapipe#3363]
Hello, 
I wanna use only hands , and body pose, i tried to combine both models but lead to decrease the performance especially when two controllers update at the same time.

**Comment by sureshdagooglecom** [comment]
Hi @ayoub-root ,
Try to use  different  calculator  for different solutions , please use static solution at one time.

**Comment by ayoub-root** [comment]
Static solution means dealing Ith javascript api or jaust graph , in my case i want to update in api directly, i dont know how, could plz give more details , any tutorial 8f plz.

**Comment by sureshdagooglecom** [comment]
Hi @ayoub-root ,
Could you please provide code changes to investigate further on this issue.

**Comment by ayoub-root** [comment]
> Hi @ayoub-root , Could you please provide code changes to investigate further on this issue.

this is my problem, i didn't find the js source code like it provided for python lib, or is there anyway to convert the modified holistic graph solution to a JS api ?

**Comment by gkarpiak** [comment]
MediaPipe doesn't provide a way to customize JS APIs so there's not much you can do here at the moment.

Overall, not for JS API, but using directly through C++/Java, to disable face mesh model in holistic you would need to create your own graph (or modify the existing one). E.g. you could copy holistic graph and remove the part that you don't need: https://github.com/google/mediapipe/blob/master/mediapipe/modules/holistic_landmark/holistic_landmark_gpu.pbtxt#L140-L146

By the way, Bazel supports C++ to WASM/JS now, so you could try the above and writing your own JS API.
