### ISSUE TITLE
I just want say this is a garbege project !

### ISSUE THREAD

**Issue by liuguicen** [google/mediapipe#3364]
Your algorithm is pretty good，but the project is a garbege. This is the most difficult open source library I have ever used. It is so difficult to use, difficult to understand and has so many problems

Why use the fuck bazel make so many problems 
why use fuck graphs hide the open source code

**Comment by thgpddl** [comment]
> 你的算法相当不错，但这个项目是一个garbege。这是我用过的最困难的开源库。它很难使用，难以理解，并且有很多问题
> 
> 为什么使用他妈的bazel做了这么多问题，为什么使用他妈的图隐藏开源代码

兄弟，我只想给你个赞，我在理解别人JavaScript项目中使用的mediapipe，但是我似乎没有找到mediapipe 的文档和api介绍之类的，头都要秃了

**Comment by sureshdagooglecom** [comment]
Hi @liuguicen ,
Bazel is a tool that automates software builds and tests. Supported build tasks include running compilers and linkers to produce executable programs and libraries, and assembling deployable packages for Android, iOS and other target environments. Bazel is similar to other tools like Make, Ant, Gradle, Buck, Pants and Maven that is the reason we use bazel in MediaPipe.
