### ISSUE TITLE
Where can I find the use documents of the  drawing_utils?

### ISSUE THREAD

**Issue by thgpddl** [google/mediapipe#3367]
This template is for miscellaneous issues not covered by the other issue categories

For questions on how to work with MediaPipe, or support for problems that are not verified bugs in MediaPipe, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mediapipe) and [Slack](https://mediapipe.page.link/joinslack) communities.

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/google/mediapipe/security).

# I'm using the @mediapipe/drawing_utils, but I don't know what api the drawing_utils has. Where can I find the use documents of the  drawing_utils?

**Comment by sureshdagooglecom** [comment]
Hi @thgpddl ,
MediaPipe drawing_utils used as Utilities to draw landmarks and connectors and this [link](https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/drawing_utils.py) is  for drawing_utols code in python.
