### ISSUE TITLE
Scale values interpretation

### ISSUE THREAD

**Issue by UX3D-mazzini** [google/mediapipe#3368]
Solution: Objectron
Language: Javascript API , Three.js

Can somebody explain better what the scale values obtained from the objectron solution mean? I'm trying to render a mesh on top of the predicted landmarks. When I assign this scale values to the 3dmodel it is transformed in an inaccurate and weird way.

This is what I found in the documentation and in the Javascript implementation:
- scale:  3x1 vector describing the scale of the rigid object's frame of reference in the camera-coordinate system.
- scale : relative scale of the object along x, y and z directions.

What does relative mean here?   
How a mesh scale is influenced if those values are used to set the mesh scale? Is the final result influenced by the initial scale of the mesh I load?

**Comment by sureshdagooglecom** [comment]
Hi @UX3D-mazzini ,
To provide 3D coordinates in camera coordinate system at least requires calibration of camera which is depend on the devices. This is beyond our current scope which is to enable hand tracking on any types of cameras.
One possible way to achieve that is to use ARCore/ARKit for Android/IOS to get 3D sparse point cloud and then align the keypoints with those hand landmarks.

**Comment by sureshdagooglecom** [comment]
Hi @UX3D-mazzini ,
Marking this as duplicate https://github.com/google/mediapipe/issues/3341 and we are waiting for issue resolution.
