### ISSUE TITLE
Code that uses the object detection android app

### ISSUE THREAD

**Issue by Ncuaresma** [google/mediapipe#3369]
Good afternoon,

I would like to add some new functionality to the example of the Android application Object Detection, I have seen that the only main that is used is the MainActivity.java. Where can I find the output_matrix that returns the application to add after that my functionality to the output frame?

Thank you.

**Comment by sureshdagooglecom** [comment]
Hi @Ncuaresma ,
Could you elaborate this issue w.r.t above issue , what kind of functionality you are adding?

**Comment by Ncuaresma** [comment]
I would like to get the boxes obtained in each frame to calculate de distance to the object.
For that I need to find in the code the moment the output frame is shown in the screen, but I can not find it.

**Comment by Ncuaresma** [comment]
> Hi @Ncuaresma , Could you elaborate this issue w.r.t above issue , what kind of functionality you are adding?

I would like to get the boxes obtained in each frame to calculate de distance to the object.
For that I need to find in the code the moment the output frame is shown in the screen, but I can not find it.

**Comment by Ncuaresma** [comment]
Hi @sureshdagooglecom, I would like to find where is the NDK code for this example application.
Where can I find it?

**Comment by sureshdagooglecom** [comment]
Hi @Ncuaresma ,
Please follow instructions below to build Android example apps in the supported MediaPipe [solutions](https://google.github.io/mediapipe/solutions/solutions.html).
