### ISSUE TITLE
Mediapipe not working with Bazel 2.0.0 on Ubuntu 18.04

### ISSUE THREAD

**Issue by magiov** [google/mediapipe#337]
When running the [Hello World desktop example](https://github.com/google/mediapipe/blob/master/mediapipe/docs/hello_world_desktop.md) with [Bazel 2.0.0](https://github.com/bazelbuild/bazel/releases/tag/2.0.0) on Ubuntu 18.04, it is returned `Unrecognized option: --incompatible_depset_is_not_iterable=false`.
If the option is commented out in [.bazelrc](https://github.com/google/mediapipe/blob/master/.bazelrc), the following errors about the [WORKSPACE](https://github.com/google/meadiapipe/blob/master/WORKSPACE) are returned:  
```
name 'maven_server' is not defined
name 'maven_jar' is not defined
...
```

With the previous version of Bazel (e.g. 1.0.0), everything works fine.

**Comment by jiuqiant** [comment]
Confirm that MediaPipe is not compatible with Bazel 2.0.0. Please stay with an earlier version of Bazel. Thanks.

**Comment by jiuqiant** [comment]
Made a documentation fix in https://github.com/google/mediapipe/commit/a007fdccb6a88920e99a9154e5679024b12b9f6d
