### ISSUE TITLE
Error `selfieSegmentation.close()` to stop the video process  - `Cannot pass deleted object as a pointer of type SolutionWasm`

### ISSUE THREAD

**Issue by DeividVeloso** [google/mediapipe#3373]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): **NO**
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: **Chrome  101.0.4951.64 MacOS**
- Programming Language and version ( e.g. C++, Python, Java): **JAVASCRIPT**
- [MediaPipe version](https://github.com/google/mediapipe/releases): 
      **"@mediapipe/camera_utils": "^0.3.1640029074",**
      **"@mediapipe/selfie_segmentation": "^0.1.1632777926"**
- Solution ( e.g. FaceMesh, Pose, Holistic ):
     **@mediapipe/camera_utils**
     **@mediapipe/selfie_segmentation**

**Describe the current behavior:**

When executing `selfieSegmentation.close()` to stop the video process (Close OpenGL) it is throwing an error, I tried the [MediaPipe - Selfie Segmentation](https://codepen.io/mediapipe/pen/wvJyQpq) official examples and if you include a button in HTML and execute the `selfieSegmentation.close()` in javascript it will thrown an error.

I tried many ways to stop the selfieSegmentation and Camera Utils to avoid a leak of memory when I'm not using anymore the virtual background video.

Ways:
  - Execute `selfieSegmentation.close()` (No success) 
  - Set `selfieSegmentation` equal null (No success)
  - Set `selfieSegmentation.onResult(() => {})`  (No success)
  - Execute `selfieSegmentation.reset()` (No success) 
  
Follow the image:

![image-20220519-185221](https://user-images.githubusercontent.com/16343871/170051453-66de667f-d91b-48a9-8b5a-962ec2ee10d3.png)

**Describe the expected behavior:**

When executing `selfieSegmentation.close()` I want to stop the OpenGl process and `requestAnimatedFrame` to stop using the virtual background video feature to avoid a leak of memory.

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:

You can try it here [MediaPipe - Selfie Segmentation](https://codepen.io/mediapipe/pen/wvJyQpq) official examples and you need to include a button in HTML and execute the `selfieSegmentation.close()` in javascript, it will throw an error.

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

```
"BindingError: Cannot pass deleted object as a pointer of type SolutionWasm*
    at BindingError.<anonymous> (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation_solution_simd_wasm_bin.js:9:136510)
    at new BindingError (eval at createNamedFunction (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation_solution_simd_wasm_bin.js:9:135404), <anonymous>:4:34)
    at throwBindingError (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation_solution_simd_wasm_bin.js:9:138087)
    at RegisteredPointer.nonConstNoSmartPtrRawPointerToWireType [as toWireType] (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation_solution_simd_wasm_bin.js:9:152816)
    at SolutionWasm$send [as send] (eval at new_ (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation_solution_simd_wasm_bin.js:9:161520), <anonymous>:7:28)
    at qa.h (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation.js:64:336)
    at ta (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation.js:14:299)
    at ua.next (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation.js:15:91)
    at h (https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/selfie_segmentation.js:40:446)"
```

![image](https://user-images.githubusercontent.com/16343871/170055821-f18b9ff0-03d4-4b23-b2a3-6edf81bd48b1.png)

**Comment by sureshdagooglecom** [comment]
Hi @DeividVeloso ,
It may be due to memeory issues , we have similar issue runnung in thread https://github.com/google/mediapipe/issues/2819.

**Comment by DeividVeloso** [comment]
@sureshdagooglecom I think that is related, but @mhays-google did not solve it yet, so I don't know why the issue was closed on that thread.

This is an important bug that happens for everyone, I believe that many people are using it to create a background on video streams as google meets does and a video conference consumes a lot of resources already, so I would like to get this fixed. If you don't have time to fix it, could you guys open-source the code, please? Or point out where the files are? Maybe I or someone else can help with this.

cc: @ostap0207

**Comment by DeividVeloso** [comment]
Maybe this is related was well https://github.com/google/mediapipe/issues/3233

**Comment by DeividVeloso** [comment]
Maybe this is related too https://github.com/google/mediapipe/issues/3271

**Comment by DeividVeloso** [comment]
@sureshdagooglecom any update, please?

**Comment by DeividVeloso** [comment]
Any update, the issue is still there yet?

**Comment by DeividVeloso** [comment]
Hello @mhays-google, did you have a chance to take a look?

Thank you.

**Comment by DeividVeloso** [comment]
Hello team, any update on it, please?

**Comment by MatejFacko** [comment]
Any update on this? It's till reproducible in the newest version

**Comment by NTsyklinskiy** [comment]
how to solve this problem?

**Comment by Emma-He** [comment]
Running into the same issue :(

**Comment by Mazuh** [comment]
it's still happening to me also.

**Comment by avicarpio** [comment]
Still happening, I'm not able to close the selfieSegmentation process.

**Comment by kuaashish** [comment]
Hello @DeividVeloso,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by pruthvik-sheth** [comment]
Is this issue solved? In my case I am using the hand landmarker model from tasks-vision and when doing `handLandmarker.close()` (in a react application) I get `I0229 18:53:36.093000 1927856 gl_context_webgl.cc:132] Successfully destroyed WebGL context with handle 1 vision_wasm_internal.js:9` and my browser tab freezes. If anyone knows the solution would be of great help. Thanks.
