### ISSUE TITLE
Library/package version string available?

### ISSUE THREAD

**Issue by andioz** [google/mediapipe#3374]
Hello,

This is maybe a stupid problem, but I really tried to find information about that but without success: I'm using mediapipe from Python, and I want to know the current package version, for example to show in an about box. Typically I would expect a `mediapipe.__version__` string, bit this doesn't work.

Is there another way to get the version information out of the package, maybe by a `C` function?

Thanks,
Andi

**Comment by sureshdagooglecom** [comment]
Hi @andioz ,
We have different [versions](https://github.com/google/mediapipe/releases) of MediaPipe  and try to use latest version then after success installation version will be displayed.

**Comment by andioz** [comment]
Hi @sureshdagooglecom,

thanks for your reply. Well, what you suggest is what I'm already doing. My question is how can I retrieve the package version programmatically at runtime? I mean without running pip or setuptools or some other tool which is maybe not installed in a customers environment.

**Comment by andioz** [comment]
> Hi @andioz , Downgrade protobuf to 3.20.1 and it works.

Hi @sureshdagooglecom, thank you very much for this information. It is indeed very valuable, because right now the compatibiliy issue hits us.

But my original question has nothing to do with compatibility or other problems, it is a general question. But from the current state of discussion I should assume there is no version information yet inside the package/module? Maybe you can add one in the next versions? Even protobuf has it:

```python
>>> import google.protobuf
>>> google.protobuf.__version__
'3.20.1'
```

**Comment by sureshdagooglecom** [comment]
Hi @andioz ,
We were not aware of this version symbol convention.  We are glad to follow it if it's helpful to many clients.  Can you confirm that this convention is common and generally useful?

**Comment by andioz** [comment]
Hi @sureshdagooglecom, thanks for your interest in supporting version information! Yes I can confirm that this convention is very common and definitely useful. In may help clients to add conditional code depending on your package's version. Here some links:

https://stackoverflow.com/a/459185/330272
https://peps.python.org/pep-0008/#module-level-dunder-names
https://martin-thoma.com/python-package-versions/

For the version number itself, semantic versioning is strongly recommended:
https://peps.python.org/pep-0440/
https://semver.org/

**Comment by jiuqiant** [comment]
Hi, if you use the latest version (the current latest version is 0.9.0.1), the version string is available:

```
Python 3.9.9 (main, Nov 21 2021, 03:23:44)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mediapipe
>>> mediapipe.__version__
'0.9.0.1'
```
