### ISSUE TITLE
Mediapipie hand pose depth annotation problems

### ISSUE THREAD

**Issue by Stephenfang51** [google/mediapipe#3375]
Hello, Thanks for the awesome work for advanced

The paper mentioned that using rendered image for depth of supervision, how did you annotate the real-world image for depth values?  

Thansk ！

**Comment by sureshdagooglecom** [comment]
Hi @Stephenfang51 ,
X, y and z: Real-world 3D coordinates in meters with the origin at the center between hips in pose and kindly refer MediaPipe official [document](https://google.github.io/mediapipe/solutions/pose.html#:~:text=x%2C%20y,corresponding%20pose_landmarks.) for more informatiomn.

**Comment by Stephenfang51** [comment]
> Hi @Stephenfang51 , X, y and z: Real-world 3D coordinates in meters with the origin at the center between hips in pose and kindly refer MediaPipe official [document](https://google.github.io/mediapipe/solutions/pose.html#:~:text=x%2C%20y,corresponding%20pose_landmarks.) for more informatiomn.

thanks for the reply, what I meaned  is that "how did you annotate the depth:z for **real-world image** for Nureal  network to learn" since you dont know what actual relative depths value for each keypoint of a "hand"(not pose). 

The paper mentioned that the supervision of depth value only from rendered image(3d models), which you can easily compute the  relative depths  right?(or I was wrong)

**Comment by koegl** [comment]
> > Hi @Stephenfang51 , X, y and z: Real-world 3D coordinates in meters with the origin at the center between hips in pose and kindly refer MediaPipe official [document](https://google.github.io/mediapipe/solutions/pose.html#:~:text=x%2C%20y,corresponding%20pose_landmarks.) for more informatiomn.
> 
> thanks for the reply, what I meaned is that "how did you annotate the depth:z for **real-world image** for Nureal network to learn" since you dont know what actual relative depths value for each keypoint of a "hand"(not pose).
> 
> The paper mentioned that the supervision of depth value only from rendered image(3d models), which you can easily compute the relative depths right?(or I was wrong)

As per the [documentation](https://google.github.io/mediapipe/solutions/hands.html#hand-landmark-model):
"we take Z-value from image depth map"
