### ISSUE TITLE
how can i build the mediapipe on my own app

### ISSUE THREAD

**Issue by kinlam0221** [google/mediapipe#3376]
how can i build mediapipe on my android app or ios app.

**Comment by sureshdagooglecom** [comment]
Hi @kinlam0221 ,
We have official document for [ios](https://google.github.io/mediapipe/getting_started/ios.html) and [android](https://google.github.io/mediapipe/getting_started/android.html) ,please follow mentioned steps in the document.

**Comment by kinlam0221** [comment]
but the mentioned steps in the document just teach us to build a example apps. I wanna to build the Solutions on my xcode app. please help!!

**Comment by sureshdagooglecom** [comment]
We have [steps](https://google.github.io/mediapipe/getting_started/ios.html#:~:text=your%20provisioning%20profile.-,Build%20and%20run%20an%20app%20using%20Xcode,-Create%20the%20Xcode) mentioned and code for Xcode.
