### ISSUE TITLE
Docker install

### ISSUE THREAD

**Issue by Linduri** [google/mediapipe#3378]
**System information** (Please provide as much relevant information as possible)
- Windows 10 Pro
- Docker

**Problem and solution**:
When following the docker install tutorial found here (https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker) I would receive this error "(specified in /mediapipe/.bazelversion), but it wasn't found in /usr/local/lib/bazel/bin." when trying to run the line "root@bca08b91ff63:/mediapipe# GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world". I remedied this issue by removing the CRLF in the .bazelversion file. Please update the main branch to prevent others having this issue!

**Comment by sureshdagooglecom** [comment]
Hi @Linduri ,
Could you provide steps to reproduce this issue.

**Comment by Linduri** [comment]
1. Create a new docker image using the steps found here "https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker"
2. Run the image in a new contained using "docker run -it --name mediapipe mediapipe:latest"
3. Try to run the hello world using "GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world"

**Comment by sureshdagooglecom** [comment]
Hi @Linduri ,
 Run without CACHE, "--no-cache", show the logs from that docker build.  
otherwise, unclear why this docker image would lack a working "bazel"

**Comment by Linduri** [comment]
I have since fixed the issue but I did try using "--no-cache" when I had the error and it still reported the same error. I have fixed the problem by removing the CRLF in the .bazelversion file.
