### ISSUE TITLE
Note WSL doesn't support USB cameras

### ISSUE THREAD

**Issue by mncharity** [google/mediapipe#338]
It appears WSL does not provide access to USB camera devices.

Using a USB camera for input is a common use case.  All mediapipe platforms other than WSL support it.  It is non-obvious that WSL doesn't.  The issue has come up in  #149 and #261, but these are now closed and low visibility.

Recommendation: Add a cautionary note to https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows-subsystem-for-linux-wsl , like "Note: WSL has historically not provided access to USB cameras.  Mediapipe can use a video file as input."

**Comment by jiuqiant** [comment]
Thanks for the suggestion! We will put the cautionary note into install.md soon.

**Comment by jiuqiant** [comment]
The note for WSL is added. See https://github.com/google/mediapipe/commit/ae6be10afe59a6a99d8a68007784706ac98720dd#diff-956151db6fecd29fe7cba43281162199R358
