### ISSUE TITLE
protobuf C++ run on iOS App error

### ISSUE THREAD

**Issue by weirenfighting** [google/mediapipe#3380]
I want to run google mediapipe on iOS device
I manually drag all files into Xcode instead of using bazel and tulsi
but I got an error when use protobuf C++ source 

Version: v3.15.6
Language: C++

<img width="2206" alt="WX20220526-112421@2x" src="https://user-images.githubusercontent.com/17874839/170409942-bc0f9561-2337-4604-942e-09fff823e3c5.png">

**Comment by sureshdagooglecom** [comment]
Hi @weirenfighting ,
Could you please provide steps to reproduce this issue.
