### ISSUE TITLE
Can I Change Pose Landmarks?

### ISSUE THREAD

**Issue by WaterS-MoYu** [google/mediapipe#3381]
Hi,
I have successfully installed Mediapipe and run it on my computer. 
I decide to use Mediapipe because I want to use it to help my 3D models to dance like the real human dancing in videos. But my 3D models' bones are not similar as the pose landmarks, especially the body part, Mediapipe's model is a '_square_' body, but my models are a '_vertical line_' body (like the openpose example).
So I am considering to change the Mediapipe's pose landmark, but I can't find any exmaple on website, therefore I came here to ask for help.
Thanks

**Comment by sureshdagooglecom** [comment]
Hi @WaterS-MoYu ,
Could you share any reference video or code changes to investigate further on this issue.

**Comment by kuaashish** [comment]
Hi @WaterS-MoYu,
Can you please elaborate query with complete details and provide a sample of what your expected output rendering should be, so that we can provide plausible solution for your use case? Thank you!
