### ISSUE TITLE
[Question] Custom object detection for Mediapipe's object tracker

### ISSUE THREAD

**Issue by briliantnugraha** [google/mediapipe#3383]
Hi, thanks for the great repo.

Btw, could I know, is it possible to change/update the object tracker's object detection tflite model (default is mobilenet_ssdlite) to other object detection's tflite model without changing the code (for tracker, it does not have Python support)?

Or do we need to match the output of the default model to make it work?

---

CMIIW, the reason of my question is due to the base code, which seems to support any model, as long as the I/O matches the default model, thanks for your help in advance.

ref: 
- [object detection + tracker structure](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/tracking/object_detection_tracking_mobile_gpu.pbtxt#L25)

**Comment by sureshdagooglecom** [comment]
Hi @briliantnugraha ,
Could you please elaborate this issue to investigate further on this issue.

**Comment by briliantnugraha** [comment]
Hi @sureshdagooglecom , I want to make an object detection for the tracker in Mediapipe.
Is it possible to do it (like putting custom ONNX/tflite model as the object detection, and just connect the detection output as long as the detection format matches) with the tracker in Media pipe?

Or do I need to follow the current structure and algorithm of Mediapipe to do so?
Thanks in advance.

**Comment by sureshdagooglecom** [comment]
Hi @briliantnugraha ,
You need to follow current structure and algorithm of Mediapipe.
