### ISSUE TITLE
Camera() mediapipe ==> NotAllowedError: play() can only be initiated by a user gesture

### ISSUE THREAD

**Issue by danielSoler93** [google/mediapipe#3385]
**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 11 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Redmi 7 note
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Chrome Mobile 101 
- Programming Language and version ( e.g. C++, Python, Java): JS
- [MediaPipe version](https://github.com/google/mediapipe/releases): @mediapipe/camera_utils": "^0.3.1640029074",
- Bazel version (if compiling from source): -
- Solution ( e.g. FaceMesh, Pose, Holistic ): Camera_utils mediapipe
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
- Xcode & Tulsi version (if issue is related to building for iOS):

**Describe the current behavior:**

I have an Error **NotAllowedError: play() can only be initiated by a user gesture.** and the only play there's without a handling exception is within the camera_utils from mediapipe and the console.logs from the clients indicate that stops there

**Describe the expected behavior:**

I exepect no issue with playing the video

**Standalone code to reproduce the issue:**
I can't reproduce the problem myself

**Code**

```
this.camera = new Camera(this.video, {
			onFrame: recursiveCamera,
			width: width / 2,
			height: height
		});
		if (this.props.cameraEnabled) {
			this.camera.start()
				.then()
				.catch((err) => { handleCameraPermissionFailed(err, this.props.history) });
		}
```

**Comment by traksl** [comment]
By editing Mediapipe library and setting some trial and error we can confirm is the video.play() within the @mediapipe > camera_utils > camera_utils.js

`onloadedmetadata=function(){a.video.play();P(a)}}`

I beleive, generally, when doing video.play() should be a handle to check everything is ok:

 ```
var promise = video.play()
  if (promise !== undefined) {
    promise.then(_ => {
     console.log(`Autoplay good tag: ${tag}`)
    }).catch(error => {
      console.error`Autoplay error tag: ${tag}`)
      });
    }
```

Thank you very much for your time!

**Comment by danielSoler93** [comment]
By editing Mediapipe library and setting some trial and error we can confirm is the video.play() within the @mediapipe > camera_utils > camera_utils.js

onloadedmetadata=function(){a.video.play();P(a)}}

I beleive, generally, when doing video.play() should be a handle to check everything is ok:

var promise = video.play()
 if (promise !== undefined) {
   promise.then(_ => {
    console.log(`Autoplay good tag: ${tag}`)
   }).catch(error => {
     console.error`Autoplay error tag: ${tag}`)
     });
   }
Thank you very much for your time!

**Comment by danielSoler93** [comment]
Hi, could I ask why did you close this issue? Is it completed somewhere I have not seen?
