### ISSUE TITLE
Is Mediapipe Iris coming to Maven Repository?

### ISSUE THREAD

**Issue by PraveshARMedical** [google/mediapipe#3386]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): Mediapipe FaceMesh
- Programming language: Android Java
- Are you willing to contribute it (Yes/No): Not enough expertise

**Describe the feature and the current behaviour/state:**
     All I really want is the depth estimation which is not available in Mediapipe Facemesh. Mediapipe Iris has it but integrating into our project seems difficult
**Will this change the current api? How?**
    Possibly.
**Who will benefit from this feature?**
    A lot of people. I think Iris is more accurate for measuring the distance between the user and camera which has more benefits.
**Please specify the use cases for this feature:**
    One of the features we want to implement is calculating if the user is looking parallel to the camera.
**Any Other info:**

**Comment by sureshdagooglecom** [comment]
Hi @PraveshARMedical ,
Unfortunately, It's currently not supported. We do see this as a great feature to have and will prioritize this work.

**Comment by kuaashish** [comment]
Hello @PraveshARMedical,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
