### ISSUE TITLE
hand-tracking does not run

### ISSUE THREAD

**Issue by ihmc3jn09hk** [google/mediapipe#339]
Trying to test and run the "Hand Tracking" example with GPU support but failed with message:
"**Can't find file**". I tried to edit the _demo_run_graph_main_gpu.cc_ and add the path of the graph, e.g. `/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile.pbtxt`, for variable "`calculator_graph_config_file`" but still reported "**Can't find file**".
The hello_world runs smoothly but not the hand_tracing example.
I am trying to run it on Desktop Linux with with Nvidia GF 980M (yeah, laptop) but not with good luck. 

Anyone can help?

```
$ bazel-1.2.1 run --copt -DMESA_EGL_NO_X11_HEADERS mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "85034fc47a5cec8e4abd7f809f821af70e0fac2278250ebf015511c46ebe2c75"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/gg/.cache/bazel/_bazel_xxxx/9eb4af064af98945a846e7283e806dba/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/gg/xxxx/mediapipe/mediapipe/WORKSPACE:34:1
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu up-to-date:
  bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu
INFO: Elapsed time: 0.112s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
E1223 18:04:30.893712 30210 demo_run_graph_main_gpu.cc:186] Failed to run the graph: ; Can't find file: 

```

**Comment by ihmc3jn09hk** [comment]
Problem solve!
Hint: Working directory

**Comment by northeastsquare** [comment]
anymore hints? I met the same problem

**Comment by ihmc3jn09hk** [comment]
> anymore hints? I met the same problem

Assuming you compiled successfully like I do, create a shortcut folder at your build directory.
For example:

`$ln -s mediapipe <path-to-mediapipe>`
