### ISSUE TITLE
Segmentation fault (core dumped) python API 

### ISSUE THREAD

**Issue by pixml27** [google/mediapipe#3390]
**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): NO custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 20.04.2 LTS
- Programming Language and version ( e.g. C++, Python, Java): python
- [MediaPipe version](https://github.com/google/mediapipe/releases):  0.8.9 and 0.8.4
- Bazel version (if compiling from source): 4.2.1 and 3.7.2 (python versions respectively)
- Solution ( e.g. FaceMesh, Pose, Holistic ):  face_detection_full_range_cpu.pbtxt

**Describe the current behavior:**
Hi guys!
I'm trying to add my detection and classification model into a mediapipe and ran into problems almost immediately =)
First of all, I built mediapipe [from source ](https://google.github.io/mediapipe/getting_started/python.html#building-mediapipe-python-package) and installed opencv with [setup_opencv.sh](https://github.com/google/mediapipe/blob/master/setup_opencv.sh) from your repo
Then I tried to reproduce an [already written graph ](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_detection/face_detection_full_range_cpu.pbtxt) in python api as [described here](https://google.github.io/mediapipe/getting_started/python_framework.html#graph)

I have Segmentation fault (core dumped) on the line
`graph.add_packet_to_input_stream(
    'input_image', pack
    )`

**Describe the expected behavior:**
Have a detection_tensors in output_packets list

**Standalone code to reproduce the issue:**
So my code looks like this:

```
import mediapipe as mp
import cv2
config_text = '''
    input_stream: 'input_image'
    output_stream: 'detection_tensors'

    node:  {
              calculator: "ToImageCalculator"
              input_stream: "IMAGE_CPU:input_image"
              output_stream: "IMAGE:multi_backend_image"
            }
     
    node: {
              calculator: "ImageToTensorCalculator"
              input_stream: "IMAGE:multi_backend_image"
              output_stream: "TENSORS:input_tensors"
              output_stream: "MATRIX:transform_matrix"
              options: {
                [mediapipe.ImageToTensorCalculatorOptions.ext] {
                  output_tensor_width: 640
                  output_tensor_height: 640
                  keep_aspect_ratio: true
                  output_tensor_float_range {
                    min: 0
                    max: 1.0
                  }
                  border_mode: BORDER_ZERO
                }
              }
            }
    node {
              calculator: "InferenceCalculator"
              input_stream: "TENSORS:input_tensors"
              output_stream: "TENSORS:detection_tensors"
              options: {
                [mediapipe.InferenceCalculatorOptions.ext] {
                  model_path: "....../mediapipe/mediapipe/modules/face_detection/face_detection_full_range_sparse.tflite"
                  delegate {
                    xnnpack {}
                  }
                }
              }
            }
'''
graph = mp.CalculatorGraph(graph_config=config_text)
output_packets = []
graph.observe_output_stream(
     'detection_tensors',
     lambda stream_name, packet:
         output_packets.append(packet))

rgb_img = cv2.cvtColor(cv2.imread('../image.png'), cv2.COLOR_BGR2RGB)

graph.start_run()
pack = mp.packet_creator.create_image_frame(image_format=mp.ImageFormat.SRGB,
                                         data=rgb_img).at(0)
graph.add_packet_to_input_stream(
    'input_image', pack
    )
graph.close()
```

**Other info / Complete Logs :**
I am doing my experiments in jupiter-notebook and nothing happens there (it just freezes or kernel dies)
I get the error Segmentation fault (core dumped) when I execute the code in the python interpreter through the linux terminal

I already tried change delegates and add line use_advanced_gpu_api: false as delegator option [(this solution)](https://github.com/google/mediapipe/pull/2463)
And also I've tried build mediapipe 0.8.4 as [suggested here](
https://github.com/google/mediapipe/issues/1734)  (after git checkout on tag v0.8.4 i built it from source and do same things)
None of this worked for me. Can you help somehow?

**Comment by pixml27** [comment]
> Hi @pixml27 ,
> Could you please share any logs or errors w.r.t above issue.

The only error message i have is "Segmentation fault (core dumped)"

**Comment by kuaashish** [comment]
Hello @pixml27,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
