### ISSUE TITLE
How to test or debug this?

### ISSUE THREAD

**Issue by pixml27** [google/mediapipe#3391]
Well, I successfully built object_detection desktop tflite solution (thanks for you work!)
Now i want to change your tflite model to mine. What i'm doing:
0. I have a trained single class detection model with a treshold equal to 0.5
1. i don't have anchors in my model (so i just delete node 'SsdAnchorsCalculator')
2. My model is yolov5 in tflite format, i colud change order of outputs as i want. As i understand, i can run TfLiteTensorsToDetectionsCalculator without anchors, so [as write here  ](https://github.com/google/mediapipe/blob/4a20e9909d55838d5630366ce719844cf06ae85c/mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc#L358), my model should have 4 outputs,  which I pass through TENSORS:detection_tensors: tensor of bounding boxes, tensor of calsses, tensor of scores and tensor with num boxes
3. I add this output to my model, it looks like this:
![image](https://user-images.githubusercontent.com/38530905/171437466-08768bd2-6df7-468c-ad63-0837acce5e27.png)
4. my graph is like on object detection, but with some little changes:
```
max_queue_size: 1

node {
  calculator: "OpenCvVideoDecoderCalculator"
  input_side_packet: "INPUT_FILE_PATH:input_video_path"
  output_stream: "VIDEO:input_video"
  output_stream: "VIDEO_PRESTREAM:input_video_header"
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:input_video"
  output_stream: "IMAGE:transformed_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 640
      output_height: 640
    }
  }
}

node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE:transformed_input_video"
  output_stream: "TENSORS:image_tensor"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteConverterCalculatorOptions] {
      zero_center: false
    }
  }
}

node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS:image_tensor"
  output_stream: "TENSORS:detection_tensors"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
      model_path: "/notebooks/git-repos/crpt-cv-lib/exp-mediapipe/int_1_01.tflite"
    }
  }
}


node {
  calculator: "TfLiteTensorsToDetectionsCalculator"
  input_stream: "TENSORS:detection_tensors"
  output_stream: "DETECTIONS:detections"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteTensorsToDetectionsCalculatorOptions] {
      num_classes: 1
      num_coords: 4
      apply_exponential_on_box_size: false
      sigmoid_score: false
      min_score_thresh: 0.5
      reverse_output_order: true
      ignore_classes: 2
    }
  }
}

node {
  calculator: "DetectionLabelIdToTextCalculator"
  input_stream: "detections"
  output_stream: "output_detections"
  node_options: {
    [type.googleapis.com/mediapipe.DetectionLabelIdToTextCalculatorOptions] {
      label_map_path: "mediapipe/models/crpt.txt"
    }
  }
}

node {
  calculator: "DetectionsToRenderDataCalculator"
  input_stream: "DETECTIONS:output_detections"
  output_stream: "RENDER_DATA:render_data"
  node_options: {
    [type.googleapis.com/mediapipe.DetectionsToRenderDataCalculatorOptions] {
      thickness: 10.0
      color { r: 255 g: 0 b: 0 }
    }
  }
}

node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE:input_video"
  input_stream: "render_data"
  output_stream: "IMAGE:output_video"
}


node {
  calculator: "OpenCvVideoEncoderCalculator"
  input_stream: "VIDEO:output_video"
  input_stream: "VIDEO_PRESTREAM:input_video_header"
  input_side_packet: "OUTPUT_FILE_PATH:output_video_path"
  node_options: {
    [type.googleapis.com/mediapipe.OpenCvVideoEncoderCalculatorOptions]: {
      codec: "avc1"
      video_format: "mp4"
    }
  }
}
```

5. So, it runs and runs without errors (that is, I pass all checks on the dimensions of the tensors). But for some reason nothing is rendered on the final video! What could I be missing?

P.S. More globally, my question can be reformulated as follows: is it possible, when testing writing graphs in a mediapipe, to look at the inputs and outputs of nodes (to, for example, compare what comes into the calculator in your example and mine - and find an error)? What do I need to do?

**Comment by pixml27** [comment]
I will be very grateful if you answer me today 🙏🙏

**Comment by sureshdagooglecom** [comment]
Hi @pixml27 ,
Could you please provide steps to reproduce this issue further.

**Comment by pixml27** [comment]
Thanks a lot for your answer!
I figured it out and let me correct you a little: TfLiteTensorsToDetectionsCalculator can also get 4 tesors, as stated[ here](https://github.com/google/mediapipe/blob/4a20e9909d55838d5630366ce719844cf06ae85c/mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc#L358), and then everything will work fine.
Anyway, the easiest way to add a custom tflite model to the mediapipe is to make the right outputs during the model conversion
