### ISSUE TITLE
Where to find anchor information of latest face detection model

### ISSUE THREAD

**Issue by jindanchu** [google/mediapipe#3393]
Hello,

we observe that the latest face dection model(face_detection_full_range_sparse.tflite) accept 192x192x3 as input, not 128x128x3 anymore, is there anyplace stored anchor information of that? We need to run this tflite directly, but can not generate bounding box without correct anchor information, if use 128x128x3's anchor info, we got "out of index" failure. Could anyone give us a hand?

Thanks very much!

Best Regards
Walter

**Comment by jindanchu** [comment]
Hello, anyone can give me a hand?

**Comment by kuaashish** [comment]
Hello @jindanchu,

We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you!!
