### ISSUE TITLE
Blazepose Javascript solution takes 100% CPU utilization.

### ISSUE THREAD

**Issue by prajwal-v-athreya** [google/mediapipe#3394]
**System information**
- I am using the example code provided on mediapipe's github
- Running the JS solution for pose estimation
- [MediaPipe version](https://github.com/google/mediapipe/releases): all versions have this issue
- Bazel version: all versions have this issue
- Solution: Pose
- Programming Language and version : JavaScript - latest

**Describe the expected behavior:**

When the model runs on a browser it is using 100% CPU. Due to this other services are getting choked. Is there a way to reduce the amount of CPU it is utilizing and making it lighter? I have even used modelComplexity in different modes as well but it hasn't been very useful.

These are the options I am using:
pose.setOptions({
  staticimagemode: false,
  modelComplexity: 0,
  selfieMode: true,
  smoothLandmarks: true,
  enableSegmentation: false,
  smoothSegmentation: false,
  minDetectionConfidence: 0.5,
  minTrackingConfidence: 0.5
});

**Comment by prajwal-v-athreya** [comment]
These are the pose options I am using.
pose.setOptions({
  staticimagemode: false,
  modelComplexity: 0,
  selfieMode: true,
  smoothLandmarks: true,
  enableSegmentation: false,
  smoothSegmentation: false,
  minDetectionConfidence: 0.5,
  minTrackingConfidence: 0.5
});

**Comment by kuaashish** [comment]
Hello @prajwal-v-athreya,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
