### ISSUE TITLE
Build failed on macOS with Apple Silicon.

### ISSUE THREAD

**Issue by eignil** [google/mediapipe#3397]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): macOS 12.4 (21F79)
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):Apple clang version 13.1.6 (clang-1316.0.21.2.5)
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
- Installed using virtualenv? pip? Conda? (if python):pip
- [MediaPipe version](https://github.com/google/mediapipe/releases):v0.8.10
- Bazel version:bazel 5.0.0
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): opencv@3:3.4.16_3

**Describe the problem**:
Follow the guiding of https://google.github.io/mediapipe/getting_started/install.html#installing-on-macos and https://google.github.io/mediapipe/getting_started/hello_world_cpp.html to run the hello world example.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (79 packages loaded, 1654 targets configured).
INFO: Found 1 target...
INFO: From Linking external/com_google_absl/absl/types/libbad_variant_access.a:
warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: bazel-out/darwin_arm64-fastbuild/bin/external/com_google_absl/absl/types/libbad_variant_access.a the table of contents is empty (no object file members in the library define global symbols)
INFO: From Linking external/com_google_absl/absl/flags/libflag.a:
warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: bazel-out/darwin_arm64-fastbuild/bin/external/com_google_absl/absl/flags/libflag.a the table of contents is empty (no object file members in the library define global symbols)
INFO: From Linking external/com_google_absl/absl/types/libbad_optional_access.a:
warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: bazel-out/darwin_arm64-fastbuild/bin/external/com_google_absl/absl/types/libbad_optional_access.a the table of contents is empty (no object file members in the library define global symbols)
Target //mediapipe/examples/desktop/hello_world:hello_world up-to-date:
  bazel-bin/mediapipe/examples/desktop/hello_world/hello_world
INFO: Elapsed time: 53.516s, Critical Path: 46.30s
INFO: 985 processes: 365 internal, 620 darwin-sandbox.
INFO: Build completed successfully, 985 total actions
INFO: Build completed successfully, 985 total actions
dyld[46728]: symbol not found in flat namespace '_CFRelease'

**Comment by eignil** [comment]
I can fix this with the change like below. Not sure any other missed changes as this error appear when I compile some other modules.

mediapipe % git diff mediapipe/framework/port/BUILD
diff --git a/mediapipe/framework/port/BUILD b/mediapipe/framework/port/BUILD
index 87944d8..090576d 100644
--- a/mediapipe/framework/port/BUILD
+++ b/mediapipe/framework/port/BUILD
@@ -394,6 +394,12 @@ cc_library(
         "@com_google_absl//absl/status",
         "@com_google_absl//absl/strings",
     ],
+    linkopts = select({
+        "//mediapipe:macos": [
+            "-framework CoreFoundation",
+        ],
+        "//conditions:default": [],
+    }),
 )

 cc_library(

**Comment by sureshdagooglecom** [comment]
Hi @eignil ,
Please follow below mentioned steps.
1)Write your terminal application from within finder, select get info, and enable `open using rosetta'
2)Open up your terminal application with the rosetta flag set
3)Create a virtual env in your project, python3 -m venv myvenv
4)Activate it, source ./myvenv/bin/activate
5)pip install --upgrade pip
6)pip install mediapipe

**Comment by leochoo** [comment]
How about this?
https://github.com/cansik/mediapipe-silicon

**Comment by LluisColom** [comment]
> How about this?
> https://github.com/cansik/mediapipe-silicon

Personally I would not recommend depending on 3rd parties software to run MediaPipe.
In future releases the changes in the repo you mentioned could not be up to date.
