### ISSUE TITLE
Draw each pose landmark in a different colour

### ISSUE THREAD

**Issue by Sahil-RB** [google/mediapipe#3399]
Is there a landmark_drawing_spec that can draw each of the 33 landmarks in a different colour?

**Comment by sureshdagooglecom** [comment]
Hi @Sahil-RB ,
Below are the default Drawing specs for color. You can change the color with python implementation as per your business requirement!

(48, 255, 48) For Green color
def get_default_pose_landmarks_style() -> Mapping[int, DrawingSpec]:
"""Returns the default pose landmarks drawing style.

Returns:
A mapping from each pose landmark to its default drawing spec.
"""
pose_landmark_style = {}
left_spec = DrawingSpec(
color=(48, 255, 48), thickness=_THICKNESS_POSE_LANDMARKS)
right_spec = DrawingSpec(
color=(48, 255, 48), thickness=_THICKNESS_POSE_LANDMARKS)
