### ISSUE TITLE
What's the hand keypoint detection model?

### ISSUE THREAD

**Issue by jinfagang** [google/mediapipe#34]
Any paper for that model? How should we obtain the dataset?

**Comment by mgyong** [comment]
@fanzhanggoogle We currently don't have a paper on this yet. You can read details of the model through the [model card](https://mediapipe.page.link/handmc) & [Google AI blog post](https://mediapipe.page.link/handgoogleaiblog)

**Comment by jinfagang** [comment]
@mgyong  Thank u so much. I look at the model card which has a link illustrate on SSD model, sounds like it a SSD detection model with 7 points togather output? How do u guys design the 7 points location regression parts anyway?

**Comment by mgyong** [comment]
See [illustration of 7 points](https://lh6.googleusercontent.com/eiAXkFzur-YRrtIYHpV0YTD2SZR_TAojq7K4GqBR9kzR5elW8T0JlAW6EKx2qGPwrW3W10Y1rWATgErf_xd4NlVzXSgT8C7y9cPtDRy8EQ-rc2R6Lhjp65ie1_usaE8ss05fJHA-) for the palm detector
