### ISSUE TITLE
how to draw 3d object in mediapipe handtracking app

### ISSUE THREAD

**Issue by suraj-0387** [google/mediapipe#340]
I trying to draw a 3d object in mediapipe handtracking application. Is there any reference which can help to to achieve my task

**Comment by jiuqiant** [comment]
Drawing 3d object is beyond MediaPipe's scope. MediaPipe itself doesn't provide any library to draw 3d objects. But, after [getting the landmarks in Java](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/multihandtrackinggpu/MainActivity.java#L103), you should be able to use any Andorid drawing library to draw 3d objects.
