### ISSUE TITLE
Where to set the camera parameters？

### ISSUE THREAD

**Issue by alexw-atf** [google/mediapipe#3402]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

Hi, I'm working with the Face Mesh in python for a project. The solution page specifies "The virtual camera parameters can be set freely, however for better results it is advised to set them as close to the real physical camera parameters as possible." So, where should I look to set the virtual camera parameters to the calibrated camera parameters? Thanks!!

**Comment by kuaashish** [comment]
Hi @alexw-atf!  Could you check this [thread](https://github.com/google/mediapipe/issues/2110#issuecomment-867786652) for reference. Thank you!

**Comment by alexw-atf** [comment]
Hi @kuaashish, I went through this thread before. But I don't think the comments really answer the question. Would you be able to direct me to where the virtual camera parameters are defined or where I can define my own camera parameters? Thanks.

**Comment by kuaashish** [comment]
Hi @alexw-atf, You can define the virtual camera parameters under the **[environment.proto](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/environment.proto)**. Please let us know if this resolves the issue. Thank you!

**Comment by kuaashish** [comment]
Hi @alexw-atf, Sorry for the late response! Could you please try to build MediaPipe from [source](https://google.github.io/mediapipe/getting_started/install.html) and make the necessary changes in the [environment.proto](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/environment.proto) virtual camera parameters. Thank you!

**Comment by alexw-atf** [comment]
@kuaashish thanks for the help!
