### ISSUE TITLE
opencv-contrib-python-headless as requirement

### ISSUE THREAD

**Issue by maxstrobel** [google/mediapipe#3403]
**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): Python wheel
- Programming language : Python
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state:**

Currently opencv-contrib-python is installed as requirement. If you want to use mediapipe inside a Docker container huge images are required, because of GUI dependencies.

Proposal: Use opencv-contrib-python-headless as requirement, which is slimmer & works without the heavy dependencies.

**Will this change the current api? How?**

No.

**Who will benefit with this feature?**

Python users that develop / deploy inside Docker containers.

**Please specify the use cases for this feature:**

Development / deployment of the Python mediapipe package inside Docker containers.

**Any Other info:**

**Comment by kuaashish** [comment]
Hi @maxstrobel, Could you please provide the steps to reproduce and more information about the issue. Thank you

**Comment by gentnm** [comment]
@kuaashish I just ran into the same problem. I can provide some steps to reproduce the issue and give some further information.

mediapipe currently has opencv-python-contrib as a dependency which starting with version 4.3.0.38 is not working in headless environments anymore (cf. https://github.com/opencv/opencv-python/issues/370) . So in a docker setup, mediapipe won't be working anymore.

Therefore it would be nice to either use the headless version in all cases or to also be able to specify a headless version for mediapipe.

Build a docker image with
`Docker
FROM python:3.9-slim
RUN pip install mediapipe

ENTRYPOINT [ "python" , "-c"]
CMD [ "import mediapipe" ]
`
and then execute:
`docker build -t mediapipe-test . && docker run mediapipe-test`

**Comment by gentnm** [comment]
@kuaashish @sureshdagooglecom 

Is it possible to reopen this or should I open a new issue?

**Comment by kuaashish** [comment]
Hi @gentnm, Please raise a new issue with mentioning the reference of this issue. Thank you!
