### ISSUE TITLE
How to flip the input image horizontally for solution hands on android side?

### ISSUE THREAD

**Issue by kuangzy2011** [google/mediapipe#3407]
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 11
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.9
- Bazel version: 3.7.2
- Solution (e.g. FaceMesh, Pose, Holistic): Hands
- Programming Language and version ( e.g. C++, Python, Java): Java

**Describe the expected behavior:**

***Target: mediapipe/java/com/google/mediapipe/solutions/hands***

I'm using the back camera. The hand side annotations should be correct, same as the model used on the front camera.

However, the notes being made on the screen are informing the wrong side of the hand, that is, the inverted side.

Issue 3256 mentioned that need to flip the input image horizontally, but class ExternalTextureConverter only has method setFlipY.
When I do some change in CameraInput->start(...), the out image also flip vertically, while apk mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/ only flip the output render, is there anything I missed?.

I need to predict gesture with real hand, not just swap the handedness output. So it would better to just flip the input image horizontally and ***DO NOT*** change the output when switch phone camera.

//CameraInput->start(...)
if (newFrameListener == null) {
    throw new MediaPipeException(
        MediaPipeException.StatusCode.FAILED_PRECONDITION.ordinal(),
        "newFrameListener is not set.");
}

***//Add code here***
***if(cameraFacing == CameraInput.CameraFacing.BACK) {***
***converter.setFlipY(true);***
***}***

frameTexture = converter.getSurfaceTexture();

**Comment by kuaashish** [comment]
Hi @kuangzy2011,
This can be done by adding the `android:screenOrientation="landscape"` in manifest and `setRequestedOrientation (ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);` in MainActivity.Java. Thank you!
