### ISSUE TITLE
error  undefined symbol: glBindImageTexture

### ISSUE THREAD

**Issue by shu988** [google/mediapipe#341]
I want to run the example -- Hand Tracking Demo with Webcam (GPU) .
I used this statement ---bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS \
    mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
and it succeed.
but when i want to use this statement--GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu \
    --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt
it failed and reports an error :
bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu: ### **symbol lookup error:** bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu: **undefined symbol: glBindImageTexture**
How to solve?

**Comment by mcclanahoochie** [comment]
Hi, please see https://github.com/google/mediapipe/issues/317#issuecomment-565154074 and https://github.com/google/mediapipe/issues/150#issuecomment-565135162 and report back the results.

MediaPipe GPU only works with video cards that support OpenGL 3.1 and up, and the error suggests your gpu driver doesn't have that support

**Comment by shu988** [comment]
Thank  you very much!!
