### ISSUE TITLE
🤔MediaPipe Pose - How to Train MediaPipe on a Custom Dataset or is it allow to use Custom Data? and how.

### ISSUE THREAD

**Issue by QuincyChoyQC** [google/mediapipe#3410]
1. Is it allow a custom dataset/my model?
2. How to train?
3. How to use it?

I am running it on python at Jupyter, I could not find any tutorial for that.
Hope someone can give me some guides.

**Comment by QuincyChoyQC** [comment]
🤔

**Comment by nrkrishna** [comment]
Second this question. Would love to know if it's possible to extend it to cover specific scenarios. I'm interested in fine tuning performance of the 3d pose detection for specific fitness movements, e.g. baseball swing and golf swing. Thanks!

**Comment by kuaashish** [comment]
Hi @QuincyChoyQC, For python you can create your own graph using the calculators and execute as mentioned here https://google.github.io/mediapipe/getting_started/python_framework.html#graph. Thank you

**Comment by QuincyChoyQC** [comment]
Thank you kuaashish, I think you have answered my question.
I missed these two questions.
