### ISSUE TITLE
MediaPipe Android Archive ERROR

### ISSUE THREAD

**Issue by gavel94** [google/mediapipe#3412]
- Bazel version:5.2.0

**Describe the problem**:
 "bazel run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
    mediapipe/examples/desktop/hello_world:hello_world" is successful.
Problems with the bazel version?
I read the log that bazel couldn't find the toolchain？

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:
gavel@gavel-virtual-machine:/usr/local/mediapipe$ bazel build -c opt --strip=ALWAYS \
>     --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
>     --fat_apk_cpu=arm64-v8a,armeabi-v7a \
>     --legacy_whole_archive=0 \
>     --features=-legacy_whole_archive \
>     --copt=-fvisibility=hidden \
>     --copt=-ffunction-sections \
>     --copt=-fdata-sections \
>     --copt=-fstack-protector \
>     --copt=-Oz \
>     --copt=-fomit-frame-pointer \
>     --copt=-DABSL_MIN_LOG_LEVEL=2 \
>     --linkopt=-Wl,--gc-sections,--strip-all \
>     //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar
DEBUG: /home/gavel/.cache/bazel/_bazel_gavel/462cd1bf5fd25a4910344f60f0511903/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/gavel/.cache/bazel/_bazel_gavel/462cd1bf5fd25a4910344f60f0511903/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /home/gavel/.cache/bazel/_bazel_gavel/462cd1bf5fd25a4910344f60f0511903/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/gavel/.cache/bazel/_bazel_gavel/462cd1bf5fd25a4910344f60f0511903/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/gavel/.cache/bazel/_bazel_gavel/462cd1bf5fd25a4910344f60f0511903/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/gavel/.cache/bazel/_bazel_gavel/462cd1bf5fd25a4910344f60f0511903/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/gavel/.cache/bazel/_bazel_gavel/462cd1bf5fd25a4910344f60f0511903/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/gavel/.cache/bazel/_bazel_gavel/462cd1bf5fd25a4910344f60f0511903/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/gavel/.cache/bazel/_bazel_gavel/462cd1bf5fd25a4910344f60f0511903/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/gavel/.cache/bazel/_bazel_gavel/462cd1bf5fd25a4910344f60f0511903/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /home/gavel/.cache/bazel/_bazel_gavel/462cd1bf5fd25a4910344f60f0511903/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: /usr/local/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: While resolving toolchains for target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection_android_lib: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar' failed; build aborted: 
INFO: Elapsed time: 0.356s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
igured)

**Comment by sureshdagooglecom** [comment]
Hi @gavel94 ,
Could you provide steps to reproduce this issue.

**Comment by gavel94** [comment]
Install MediaPipe according to the documentation.After running the c++ example successfully.
Create a mediapipe_aar() target.
"""
gavel@gavel-virtual-machine:/usr/local/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example$ pwd
/usr/local/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example
gavel@gavel-virtual-machine:/usr/local/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example$ cat BUILD 
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_face_detection",
    calculators = ["//mediapipe/graphs/face_detection:mobile_calculators"],
)
gavel@gavel-virtual-machine:/usr/local/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example$ 

"""
The next step run:
"""
gavel@gavel-virtual-machine:/usr/local/mediapipe$ bazel build -c opt --strip=ALWAYS     --host_crosstool_top=@bazel_tools//tools/cpp:toolchain     --fat_apk_cpu=arm64-v8a,armeabi-v7a     --legacy_whole_archive=0     --features=-legacy_whole_archive     --copt=-fvisibility=hidden     --copt=-ffunction-sections     --copt=-fdata-sections     --copt=-fstack-protector     --copt=-Oz     --copt=-fomit-frame-pointer     --copt=-DABSL_MIN_LOG_LEVEL=2     --linkopt=-Wl,--gc-sections,--strip-all     //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar

"""

After executing this specification, the expected result is not obtained.The log is on top。

**Comment by gavel94** [comment]
I haven't seen it. I'm going to try it now. Thank you for your help.
