### ISSUE TITLE
Issue on building tensorflow-2.9.0 on centos 7.3

### ISSUE THREAD

**Issue by rajeev921** [google/mediapipe#3413]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Centos 7
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc 9.3.1
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): c++
- Installed using virtualenv? pip? Conda? (if python): 
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version: 5.0.0
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:

I am trying to build tensorflow 2.9.0 with bazel 5.0.0 from source. but getting these issue while starting.
cuda - 11.2 , cuDNN - 8.1 in Centos7.3.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

bazel  build  --config=cuda --config=v2 --config=opt --verbose_failures -c opt --cxxopt=-std=c++17 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow:tensorflow_cc //tensorflow:install_headers tensorflow:tensorflow_framework //tensorflow/tools/...

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

```
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/093ed77f7d50f75b376f40a71ea86e08cedb8b80.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

DEBUG: 
.cache/bazel/74ec22257a67dd1b8da1cbc24b2c24fb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default

WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

ERROR: /remote/home/rrajeev/tensorflow/tensorflow/tools/toolchains/win_1803/py38/BUILD:9:11: in interpreter_path attribute of py_runtime rule //tensorflow/tools/toolchains/win_1803/py38:py3_runtime: must be an absolute path.

ERROR: /remote/home/rrajeev/tensorflow/tensorflow/tools/toolchains/win_1803/py38/BUILD:9:11: Analysis of target '//tensorflow/tools/toolchains/win_1803/py38:py3_runtime' failed

 Elapsed time: 80.921s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (95 packages loaded, 1584 targets configured)
    currently loading: @com_google_protobuf// ... (8 packages)
    Fetching ...zel_rules_docker; Cloning 9bfcd7dbf0294ed9d11a99da6363fc28df904502 of https://github.com/bazelbuild/rules_docker.git
    Fetching @local_execution_config_python; fetching
    Fetching @local_config_python; fetching
    Fetching @pasta; fetching
    Fetching @speech_commands; fetching
    Fetching https://storage.googleapis.com/download.tensorflow.org/models/inception_v1.zip
    Fetching .../pasta; Extracting .cache/bazel/external/pasta/temp27256293479294320\
98/v0.1.8.tar.gz
    Fetching https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz ... (10 fetches)
```

**Comment by kuaashish** [comment]
Hi @rajeev921, Could you please post this issue on the Tensorflow [repo.](https://github.com/tensorflow/tensorflow/issues). Thank you!

**Comment by rajeev921** [comment]
@kuaashish Done, Thank you. 

Closing this issue.
