### ISSUE TITLE
[Error] WebGL: INVALID_VALUE: texSubImage2D: no pixels - on macbook safari

### ISSUE THREAD

**Issue by rkgnanesh** [google/mediapipe#3414]
**Im getting this error on macbook safari, Landmarks are not accurate when this error occurs, how to fix this issue ?**

[Error] WebGL: INVALID_VALUE: texSubImage2D: no pixels
	texSubImage2D
	_glTexSubImage2D (hands_solution_wasm_bin.js:9:207609)
	wasm-stub
	<?>.wasm-function[2532]
	<?>.wasm-function[2400]
	<?>.wasm-function[2169]
	<?>.wasm-function[5499]
	<?>.wasm-function[5498]
	<?>.wasm-function[2293]
	<?>.wasm-function[2147]
	<?>.wasm-function[5098]
	<?>.wasm-function[5088]
	<?>.wasm-function[5024]
	<?>.wasm-function[221]
	<?>.wasm-function[191]
	wasm-stub
	SolutionWasm$send (Anonymous Script 1 (line 8))
	(anonymous function) (hands.js:73)
	G (hands.js:14:298)
	(anonymous function) (hands.js:15:93)
	promiseReactionJob

**Comment by sureshdagooglecom** [comment]
Hi @rkgnanesh ,
Could you elaborate this issue and please provide steps to reproduce this issue.
