### ISSUE TITLE
Build apk is ok,  but when using aar have problem.

### ISSUE THREAD

**Issue by wingdi** [google/mediapipe#3416]
Platform : Android; sdk-31, ndk-21.4.7075529.
Solution: facemesh.

I have changed some code of mediapipe  to implement Physically Based Rendering. this is the render result of face_effect_gpu.apk using `mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect/BUILD`

![Screenshot_20220610_192303_com google mediapipe a(1)](https://user-images.githubusercontent.com/25787391/173171234-9a333d33-3fc8-47df-991b-9e5b35892f03.jpg)

The effect is ok .

This is the BUILD file used to build aar:
```
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "face_effect_gpu",
    calculators = ["//mediapipe/graphs/face_effect:face_effect_gpu_deps"],
)
```
And then using this aar in my project ,it don't have pbr effect. like this :
 
![Screenshot_20220611_104553_com ai glassview_edit_(1)](https://user-images.githubusercontent.com/25787391/173171244-249b9df6-994f-4f9d-ac49-04488ec7cdb3.jpg)

When using aar, I have checked,  all maps are loaded, openGLES didn't report error ,  everything seems fine, what may problems of this ?

Build apk and aar command :
```
bazel build -c opt --strip=ALWAYS \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    --config=android_arm64 \
//mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect:face_effect_gpu
```

**Comment by wingdi** [comment]
Stuck here all day,  Who can tell me what's the problem ?  very thankful.

**Comment by sureshdagooglecom** [comment]
Hi @wingdi ,
Could you provide steps to reproduce this issue.

**Comment by wingdi** [comment]
Hi, I have found it is a build problem.  
When using gradle, the render result is bad as above post.
Now we only consider bazel . When target is recognized as an android_binary handled by Android BInary Handler, the render result is normal：
![image](https://user-images.githubusercontent.com/25787391/173708714-0f6768f7-6ecb-4845-a0ae-4c97c3a48727.png)
When target is recognized as an unknown rule handled by Generic Handler. the render result is bad .
![image](https://user-images.githubusercontent.com/25787391/173708776-62bcbe06-1e8b-4ef5-9216-bd0365360f62.png)
 it seems like gradle, and bazel with unknown rule handler by Generic Handler did something about code or resources. But what they do?  I have asked at bazelbuild/intellij , There have no answer.

**Comment by sureshdagooglecom** [comment]
Hi @wingdi ,
Please follow below pre-requisites.
This are Prerequisites https://google.github.io/mediapipe/getting_started/android.html#prerequisite, But still you can build. and run applications with [android:minSdkVersion="21"](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/solutions/hands/src/main/AndroidManifest.xml#:~:text=%3Cuses%2Dsdk,android%3AtargetSdkVersion%3D%2230%22%20/%3E)

**Comment by wingdi** [comment]
```
                glBindFramebuffer(GL_FRAMEBUFFER, captureFBO);
                glBindRenderbuffer(GL_RENDERBUFFER, captureRBO);
                glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT24, 512, 512);
                glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, captureRBO);
                glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, brdfLUTTexture, 0);
                glViewport(0, 0, 512, 512);
                brdfShader.use();
                glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
                renderQuad();
                ...
                glActiveTexture(GL_TEXTURE2);
                glBindTexture(GL_TEXTURE_2D, brdfLUTTexture);
```
When build result is aar , can't sampling data from brdfLUTTexuture, but when build result is apk, can sampling(get) data from brdfLUTTexture. I have test many times step by step.

**Comment by sureshdagooglecom** [comment]
Hi @wingdi ,
Could you please explain how AAR packaging could be interfering with the PBR texture.
