### ISSUE TITLE
KNIFT on other platforms

### ISSUE THREAD

**Issue by manb911** [google/mediapipe#3417]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):Javascript
- Solution (e.g. FaceMesh, Pose, Holistic):KNIFT
- Programming Language and version ( e.g. C++, Python, Java): Javascript

**Describe the expected behavior:** I was wondering if it would be possible currently to build a graph for KNIFT on javascript for web deployment? Or is it limited to the native mobile apps for now?

**Comment by sureshdagooglecom** [comment]
Hi @manb911 ,
We don't have support for KNIFT on Web, and currently do not have it on the roadmap.

**Comment by Mcilie** [comment]
Is there a particular reason as to why KNIFT is exclusively android? What would need to be done to port it to iOS or Web? Where would i start?

**Comment by Thaina** [comment]
@sureshdagooglecom What's the problem and are there any reason we can't have this feature in other platform?

**Comment by Benjamin-Wegener** [comment]
https://github.com/Benjamin-Wegener/KNIFT-GPU this was trained from scratch on linux
