### ISSUE TITLE
Pose Movements and Screen Coordinates

### ISSUE THREAD

**Issue by CusterFun** [google/mediapipe#3418]
**Describe the expected behavior:**

how should I judge the relationship between the pose landmarks and the screen coordinates.

how should I judge body whether to move left or right.

how should I judge a person is jumping.

**Comment by CusterFun** [comment]
## 1. how should I judge the relationship between the pose landmarks and the screen coordinates?

use windows size divide by image size get a ratio.

```dart
  void _paintPose(Canvas canvas, Size size) {
    if (pose == null) return;

    final double hRatio =
        imageSize.width == 0 ? 1 : size.width / imageSize.width;
    final double vRatio =
        imageSize.height == 0 ? 1 : size.height / imageSize.height;

    offsetForPart(PoseLandmark part) =>
        Offset(part.position.x * hRatio, part.position.y * vRatio);

    // Landmark connections
    final landmarksByType = {for (final it in pose!.landmarks) it.type: it};
    for (final connection in connections) {
      final point1 = offsetForPart(landmarksByType[connection[0]]!);
      final point2 = offsetForPart(landmarksByType[connection[1]]!);
      canvas.drawLine(point1, point2, linePaint);
    }

    for (final part in pose!.landmarks) {
      // Landmark points
      canvas.drawCircle(offsetForPart(part), 5, pointPaint);
      if (part.type.isLeftSide) {
        canvas.drawCircle(offsetForPart(part), 3, leftPointPaint);
      } else if (part.type.isRightSide) {
        canvas.drawCircle(offsetForPart(part), 3, rightPointPaint);
      }

      // Landmark labels
      TextSpan span = TextSpan(
        text: part.type.toString().substring(16),
        style: const TextStyle(
          color: Color.fromRGBO(0, 128, 255, 1),
          fontSize: 10,
          shadows: [
            ui.Shadow(
              color: Color.fromRGBO(255, 255, 255, 1),
              offset: Offset(1, 1),
              blurRadius: 1,
            ),
          ],
        ),
      );
      TextPainter tp = TextPainter(text: span, textAlign: TextAlign.left);
      tp.textDirection = TextDirection.ltr;
      tp.layout();
      tp.paint(canvas, offsetForPart(part));
    }
  }

```

## 2. how should I judge body whether to move left or right.

```dart
  Future<void> leftRightLogic(Pose pose, Size size, Size imageSize) async {
    final double hRatio =
        imageSize.width == 0 ? 1 : size.width / imageSize.width;
    final double vRatio =
        imageSize.height == 0 ? 1 : size.height / imageSize.height;

    for (final part in pose.landmarks) {
      // judge body move to left
      if (part.type == PoseLandmarkType.rightAnkle &&
          part.position.x * hRatio <= size.width * 4 / 10) {
        setBodyMovementDetector('left');
      }
      // judge body move to right
      if (part.type == PoseLandmarkType.leftAnkle &&
          size.width * 6 / 10 <= part.position.x * hRatio) {
        setBodyMovementDetector('right');
      }
    }
  }
```

**Comment by Safi9024** [comment]
Can I find real co-ordinates in x,y,z in cm/m using pose detection?

**Comment by kuaashish** [comment]
Hello @CusterFun,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
