### ISSUE TITLE
How to modify mediapipe android source code

### ISSUE THREAD

**Issue by suraj-0387** [google/mediapipe#342]
I am using the gradle to build the mediapipe handtracking application.Now I want to update mediapipe code.Is there any way to update it in gradle or is there some another way

**Comment by jiuqiant** [comment]
What do you mean by building MediaPipe in gradle? MediaPipe can be only built with Bazel. But, we do provide a way to make an android achieve library. If you go with the AAR approach, you probably can modify the source code, rebuild the AAR with Bazel, and import the new AAR into Android Studio.
