### ISSUE TITLE
Cannot Run Android Studio Facemesh on Camera copying Example App Code

### ISSUE THREAD

**Issue by Hayden2018** [google/mediapipe#3420]
<em>I try to copy sample code from the Android Studio example App but the InputCamera Stream is not working. It is working fine in the example app though.<em>

**System information** (Please provide as much relevant information as possible)
- Windows 11 Pro
- Android Studio 2021.2.1 Patch 1
- Java Project with JDK 1.8
- MediaPipe 0.8.10 on Maven
- Grade 7.2.1
- FaceMesh not working (Others too)

**Procedure Taken**
- Download example app from GitHub (and run the Windows fix which need to change rm -> del)
- Create another app project with same min and target sdk.
- Modify build.gradle to include MediaPipe in new project
- Copy the three java class in example app to new project with some package renaming
- Copy activity_main.xml from example app to new app project
- Fix some string reference issue
- Build the new app (Success but the camera stream cant run when tested)

**Expected Behavior**
Camera stream start when I click and camera button in the app

**Encountered Behaviour**
The camera stream does not start. After some investigation the resume and pause event keep firing but not sure how the two are related.

Please let me know if additional setup is need to run the code. Thankyou very much for any help.

**Comment by sureshdagooglecom** [comment]
Hi @Hayden2018 ,
Could you please share code changes to investigate further on this issue.

**Comment by Hayden2018** [comment]
Hi @sureshdagooglecom 
There is no code changes but copying. I copy the follwing to a new empty Android Studio project.

The three Java files under [mediapipe/examples/android/solutions/facemesh/src/main/java/com/google/mediapipe/examples/facemesh/](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions/facemesh/src/main/java/com/google/mediapipe/examples/facemesh)

The Main Activity XML under
[mediapipe/mediapipe/examples/android/solutions/res/layout/](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions/res/layout)

Then add mediapipe to build.gradle

The resulting project build sucessfully but cameraInput is not working. (It work in the original example app) Thanks.

**Comment by Hayden2018** [comment]
Hi @sureshdagooglecom 

In that case its seems to be problem about the Javascript API. My problem is about Android Studio API.

Also, the problem there is about video input not working. In my case both video and camera input is not working if the code is copied outside the original project.

**Comment by sureshdagooglecom** [comment]
Hi @Hayden2018 ,
Could you please code changes to investigate on this issue.
