### ISSUE TITLE
ARKit 52 blendshapes support request

### ISSUE THREAD

**Issue by GeorgeS2019** [google/mediapipe#3421]
<em>Please make sure that this is a feature request.</em>

**Describe the feature and the current behavior/state:**

Is there a plan to output the facial blendshapes that are compatible with the ARKit 52 blendshapes?

**Will this change the current api? How?**

This is an addition to the existing API.

**Who will benefit with this feature?**

This provides facial mocap for avatars that use the ARKit 52 blendshapes.

**Please specify the use cases for this feature:**

Currently, Users who are using industry standards e.g. [Character Creator 3 ](https://character-creator.reallusion.com/) limit themselves only facial mocap apps from Apple App Store

This feature request will democratize Facial Mocap apps to Android and make them available through **Google Store.**

Related [discussion](https://github.com/google/mediapipe/issues/1678#issuecomment-1115357969)

Related [community effort](https://alter.xyz/mocap4face/) to address this unmet need for android phone users

**Comment by GeorgeS2019** [comment]
[Relevant attempt](https://hinzka.hatenablog.com/entry/2021/12/02/005814) by VRM communities to adopt the ARKit 52 blendshapes

**Comment by sureshdagooglecom** [comment]
Hi @GeorgeS2019 ,
Blendshapes come from Xeno (https://drive.google.com/open?id=1f030M8gbXgJN-5-JhcPkDnK5ehIwl3grNhRXSZBXvjw&resourcekey=0-q6Z33dZKrau_ngUh0gJDeA) .
The basic implementation is ready, but was waiting for a stable MediaPipe version of the app to submit. Pushing to M2 sounds good.

**Comment by GeorgeS2019** [comment]
@sureshdagooglecom  

Hi Suresh, could you clarify what you mean by M2?

MediaPipe has become an industry standard for developers. I believe many would not need to wait for the app you refer to but would use the basic implementation immediately as part of the MediaPipe SDK. 

**Please PR** it so the community could **build** or use the **nightly built** version immediately and start testing it so we could iteratively feedback on the basic implementation.

**Comment by GeorgeS2019** [comment]
For reference:

[VSBuild discussion](https://github.com/google/mediapipe/issues?q=is%3Aissue+is%3Aopen+Windows+build#issuecomment-1123345899) and [source codes](
https://github.com/andrechen/mediapipe/blob/f843e68a958f4a452be848bfef9855c540f2845e/visualstudio/live_demo/main.cc#L47)

**Comment by zk2ly** [comment]
@sureshdagooglecom Please support this feature request for https://github.com/google/mediapipe/issues/3421

**Comment by zk2ly** [comment]
> @sureshdagooglecom

No access rights

**Comment by huhai463127310** [comment]
> > @sureshdagooglecom
> 
> No access rights

+1

**Comment by GeorgeS2019** [comment]
@kuaashish could you help address some of the questions here? Assuming that @sureshdagooglecom is on a long holiday

**Comment by brunodeangelis** [comment]
+1 for this. It would really democratize the virtual character puppeteering market, allowing developers to build things we've not imagined yet

**Comment by GeorgeS2019** [comment]
@brunodeangelis  I am about to close this issue as our requests are being ignored.

**Comment by jinfagang** [comment]
I think 52 bs is not easily integrated with media pipe, but one can using a new model to regression these outputs with the input of 3d face pose.

**Comment by brunodeangelis** [comment]
> I think 52 bs is not easily integrated with media pipe, but one can using a new model to regression these outputs with the input of 3d face pose.

Could you expand on this please? What type of model? Do you have an example?

**Comment by emphaticaditya** [comment]
any update on this guys? Is it in progress on dropped?

**Comment by noeykan** [comment]
I'm also waiting for this feature to be released so much... Please update this issue!

**Comment by GeorgeS2019** [comment]
Hope to get an update soon on the support of this technology  :-)

**Comment by dandingol03** [comment]
> Hi @GeorgeS2019 , Blendshapes come from Xeno (https://drive.google.com/open?id=1f030M8gbXgJN-5-JhcPkDnK5ehIwl3grNhRXSZBXvjw&resourcekey=0-q6Z33dZKrau_ngUh0gJDeA) . The basic implementation is ready, but was waiting for a stable MediaPipe version of the app to submit. Pushing to M2 sounds good.

the link of the google drvie is invalid

**Comment by xuyixun21** [comment]
> > 你好@GeorgeS2019, Blendshapes 来自 Xeno ( https://drive.google.com/open?id=1f030M8gbXgJN-5-JhcPkDnK5ehIwl3grNhRXSZBXvjw&resourcekey=0-q6Z33dZKrau_ngUh0gJDeA )。基本实现已准备就绪，但正在等待应用程序的稳定 MediaPipe 版本提交。推到 M2 听起来不错。
> 
> google drvie 的链接无效

+1

**Comment by puhuajiang** [comment]
Any update so far?

**Comment by srcnalt** [comment]
This feature can be revolutionary. Really wondering why it gets ignored.

**Comment by GeorgeS2019** [comment]
I close it due to lack of interest.

**Comment by umarl** [comment]
It seems they are working on this: https://github.com/google/mediapipe/commit/ba10ae8410ce431f593c95986a230add675e5ccd 
But the models aren't available and there's no info on how to use it.

**Comment by baronha** [comment]
+1

**Comment by GeorgeS2019** [comment]
1. static let eyeBlinkLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing closure of the eyelids over the left eye.
1. static let eyeLookDownLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing movement of the left eyelids consistent with a downward gaze.
1. static let eyeLookInLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing movement of the left eyelids consistent with a rightward gaze.
1. static let eyeLookOutLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing movement of the left eyelids consistent with a leftward gaze.
1. static let eyeLookUpLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing movement of the left eyelids consistent with an upward gaze.
1. static let eyeSquintLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing contraction of the face around the left eye.
1. static let eyeWideLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing a widening of the eyelids around the left eye.
1. static let eyeBlinkRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing closure of the eyelids over the right eye.
1. static let eyeLookDownRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing movement of the right eyelids consistent with a downward gaze.
1. static let eyeLookInRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing movement of the right eyelids consistent with a leftward gaze.
1. static let eyeLookOutRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing movement of the right eyelids consistent with a rightward gaze.
1. static let eyeLookUpRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing movement of the right eyelids consistent with an upward gaze.
1. static let eyeSquintRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing contraction of the face around the right eye.
1. static let eyeWideRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing a widening of the eyelids around the right eye.
1. static let jawForward: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing forward movement of the lower jaw.
1. static let jawLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing leftward movement of the lower jaw.
1. static let jawRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing rightward movement of the lower jaw.
1. static let jawOpen: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing an opening of the lower jaw.
1. static let mouthClose: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing closure of the lips independent of jaw position.
1. static let mouthFunnel: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing contraction of both lips into an open shape.
1. static let mouthPucker: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing contraction and compression of both closed lips.
1. static let mouthLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing leftward movement of both lips together.
1. static let mouthRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing rightward movement of both lips together.
1. static let mouthSmileLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing upward movement of the left corner of the mouth.
1. static let mouthSmileRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing upward movement of the right corner of the mouth.
1. static let mouthFrownLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing downward movement of the left corner of the mouth.
1. static let mouthFrownRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing downward movement of the right corner of the mouth.
1. static let mouthDimpleLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing backward movement of the left corner of the mouth.
1. static let mouthDimpleRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing backward movement of the right corner of the mouth.
1. static let mouthStretchLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing leftward movement of the left corner of the mouth.
1. static let mouthStretchRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing rightward movement of the left corner of the mouth.
1. static let mouthRollLower: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing movement of the lower lip toward the inside of the mouth.
1. static let mouthRollUpper: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing movement of the upper lip toward the inside of the mouth.
1. static let mouthShrugLower: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing outward movement of the lower lip.
1. static let mouthShrugUpper: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing outward movement of the upper lip.
1. static let mouthPressLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing upward compression of the lower lip on the left side.
1. static let mouthPressRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing upward compression of the lower lip on the right side.
1. static let mouthLowerDownLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing downward movement of the lower lip on the left side.
1. static let mouthLowerDownRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing downward movement of the lower lip on the right side.
1. static let mouthUpperUpLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing upward movement of the upper lip on the left side.
1. static let mouthUpperUpRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing upward movement of the upper lip on the right side.
1. static let browDownLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing downward movement of the outer portion of the left eyebrow.
1. static let browDownRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing downward movement of the outer portion of the right eyebrow.
1. static let browInnerUp: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing upward movement of the inner portion of both eyebrows.
1. static let browOuterUpLeft: ARFaceAnchor.BlendShapeLocation
   >.  The coefficient describing upward movement of the outer portion of the left eyebrow.
1. static let browOuterUpRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing upward movement of the outer portion of the right eyebrow.
1. static let cheekPuff: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing outward movement of both cheeks.
1. static let cheekSquintLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing upward movement of the cheek around and below the left eye.
1. static let cheekSquintRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing upward movement of the cheek around and below the right eye.
1. static let noseSneerLeft: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing a raising of the left side of the nose around the nostril.
1. static let noseSneerRight: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing a raising of the right 
1. static let tongueOut: ARFaceAnchor.BlendShapeLocation
   >. The coefficient describing extension of the tongue.

**Comment by GeorgeS2019** [comment]
```c++
static constexpr std::array<absl::string_view, 52> kBlendshapeNames = {
    "_neutral",
    "browDownLeft",
    "browDownRight",
    "browInnerUp",
    "browOuterUpLeft",
    "browOuterUpRight",
    "cheekPuff",
    "cheekSquintLeft",
    "cheekSquintRight",
    "eyeBlinkLeft",
    "eyeBlinkRight",
    "eyeLookDownLeft",
    "eyeLookDownRight",
    "eyeLookInLeft",
    "eyeLookInRight",
    "eyeLookOutLeft",
    "eyeLookOutRight",
    "eyeLookUpLeft",
    "eyeLookUpRight",
    "eyeSquintLeft",
    "eyeSquintRight",
    "eyeWideLeft",
    "eyeWideRight",
    "jawForward",
    "jawLeft",
    "jawOpen",
    "jawRight",
    "mouthClose",
    "mouthDimpleLeft",
    "mouthDimpleRight",
    "mouthFrownLeft",
    "mouthFrownRight",
    "mouthFunnel",
    "mouthLeft",
    "mouthLowerDownLeft",
    "mouthLowerDownRight",
    "mouthPressLeft",
    "mouthPressRight",
    "mouthPucker",
    "mouthRight",
    "mouthRollLower",
    "mouthRollUpper",
    "mouthShrugLower",
    "mouthShrugUpper",
    "mouthSmileLeft",
    "mouthSmileRight",
    "mouthStretchLeft",
    "mouthStretchRight",
    "mouthUpperUpLeft",
    "mouthUpperUpRight",
    "noseSneerLeft",
    "noseSneerRight"};
```

**Comment by GeorgeS2019** [comment]
All 52 blendshape coefficients:
- 0  - _neutral  (ignore it)
- 1  - browDownLeft
- 2  - browDownRight
- 3  - browInnerUp
- 4  - browOuterUpLeft
- 5  - browOuterUpRight
- 6  - cheekPuff
- 7  - cheekSquintLeft
- 8  - cheekSquintRight
- 9  - eyeBlinkLeft
- 10 - eyeBlinkRight
- 11 - eyeLookDownLeft
- 12 - eyeLookDownRight
- 13 - eyeLookInLeft
- 14 - eyeLookInRight
- 15 - eyeLookOutLeft
- 16 - eyeLookOutRight
- 17 - eyeLookUpLeft
- 18 - eyeLookUpRight
- 19 - eyeSquintLeft
- 20 - eyeSquintRight
- 21 - eyeWideLeft
- 22 - eyeWideRight
- 23 - jawForward
- 24 - jawLeft
- 25 - jawOpen
- 26 - jawRight
- 27 - mouthClose
- 28 - mouthDimpleLeft
- 29 - mouthDimpleRight
- 30 - mouthFrownLeft
- 31 - mouthFrownRight
- 32 - mouthFunnel
- 33 - mouthLeft
- 34 - mouthLowerDownLeft
- 35 - mouthLowerDownRight
- 36 - mouthPressLeft
- 37 - mouthPressRight
- 38 - mouthPucker
- 39 - mouthRight
- 40 - mouthRollLower
- 41 - mouthRollUpper
- 42 - mouthShrugLower
- 43 - mouthShrugUpper
- 44 - mouthSmileLeft
- 45 - mouthSmileRight
- 46 - mouthStretchLeft
- 47 - mouthStretchRight
- 48 - mouthUpperUpLeft
- 49 - mouthUpperUpRight
- 50 - noseSneerLeft
- 51 - noseSneerRight

**Comment by GeorgeS2019** [comment]
To all users here, please encourage this [project ](https://github.com/homuler/MediaPipeUnityPlugin/issues/862)to support the latest 52 blendshapes. Do generously support the new feature request with emoji and the project with stars

**Comment by GeorgeS2019** [comment]
The relevant commit was on 16th Feb

Will need to wait for the next release.
![image](https://user-images.githubusercontent.com/49812372/220991096-04c35f30-17a8-406f-b075-772469ec0104.png)

**Comment by Zhangtiande** [comment]
I also saw the commit about blendshape, but I don't know whether I can use it directly now

**Comment by Zhangtiande** [comment]
That's great, thanks to the developers

**Comment by GeorgeS2019** [comment]
# Step1 : 
## face_blendshapes.tflite

# Step2 : [according to this project](https://github.com/keijiro/FaceMeshBarracuda/issues/24#issue-1618129677)
 
- Converts .tflite into ONNX using tflite2onnx
- Replace Pad operators with combinations of ConstantOfShape and Concat.
- Add Expand operators to PRelu slope inputs.

**Comment by fadiaburaid** [comment]
If you want to try the model and can't wait for the documentation you can download it from here
[face_blendshapes.tflite](https://storage.googleapis.com/mediapipe-assets/face_blendshapes.tflite)
The easiest way to test it is on Python. You can use it in Unity without converting to ONNX by using
[TF Lite to  Unity Plugin](https://github.com/asus4/tf-lite-unity-sample)

**Comment by GeorgeS2019** [comment]
[See the mediapipe blendshapes in action](https://github.com/google/mediapipe/issues/4162#issuecomment-1467531976)

![msedge_beivNJt8ur](https://user-images.githubusercontent.com/49812372/224948043-6b7f192b-97e8-412e-bfc8-ad6a04a1767e.gif)

**Comment by GeorgeS2019** [comment]
[Python example using blendshape](https://github.com/google/mediapipe/blob/54e4dfc853ddb6d75004a0bb79ef72dcdd8308f9/mediapipe/tasks/python/test/vision/face_landmarker_test.py)

**Comment by GeorgeS2019** [comment]
I need your support for this [issue ](https://github.com/google/mediapipe/issues/4171#issuecomment-1483388848)to allow more USERS interested of testing the blendshape in Game Engine doing it in faster iteration.

**Comment by GeorgeS2019** [comment]
After close to 9 months of REQUEST and with **MANY** HERE supporting the IDEA <======. 
I am closing this issue NOW!    
https://www.phizmocap.dev/

![msedge_GG8r4VZSI3](https://user-images.githubusercontent.com/49812372/227644951-d454f023-dc02-4740-87ec-51e0820cb1e4.gif)

**Comment by baronha** [comment]
> After close to 9 months of REQUEST and with **MANY** HERE supporting the IDEA <======. I am closing this issue NOW! https://www.phizmocap.dev/

Are you using mediapipe for this project? I found it used from an archived package `mocap4face` of `facemoji`

**Comment by GeorgeS2019** [comment]
Combination...I believe

**Comment by GeorgeS2019** [comment]
@baronha 

https://github.com/google/mediapipe/issues/4200#issue-1640418344

**Comment by GeorgeS2019** [comment]
Consider supporting this [issue](https://github.com/google/mediapipe/issues/4206)

**Comment by GeorgeS2019** [comment]
https://github.com/google/mediapipe/issues/4210

**Comment by weeeeigen** [comment]
I have installed mediapipe=0.9.2.1 by pip to use this good blendshape estimation. If anyone knows how to move it, it would be helpful if you could tell me.

**Comment by FishWoWater** [comment]
@GeorgeS2019 @fadiaburaid fa   Thank you for your efforts to make this amazing feature possible!  Do you have any python / javascript example to use this tflite model?   It's seems that [official guide](https://developers.google.com/mediapipe/solutions/vision/face_landmarker) is still in progress and the [python example](https://github.com/google/mediapipe/blob/54e4dfc853ddb6d75004a0bb79ef72dcdd8308f9/mediapipe/tasks/python/test/vision/face_landmarker_test.py)  can't run

**Comment by GeorgeS2019** [comment]
To Everyone, this is [PART 2](https://github.com/google/mediapipe/issues/4428#issue-1715496637), please **support**!!!!!!

**Comment by kuaashish** [comment]
@GeorgeS2019,

Could you let us know if we can mark issue as resolved and close? However, We are following up on another issue raised #4428.  Thank you!!

**Comment by GeorgeS2019** [comment]
@kuaashish 
Thank you for your support.  I need it to present global crisis

**Comment by FishWoWater** [comment]
@schmidt-sebastian @kuaashish Hi, researchers! Could you please give me some hint on the training details of this blendshape estimator? I have referred to your solution [page](https://storage.googleapis.com/mediapipe-assets/Model%20Card%20Blendshape%20V2.pdf) but still couldn't get the point. How did you generate the ground-truth 3D blendshapes(52 coefficients) from 3D mesh reconstruction? Is it an optimization-based logic where a rigged face's blendshapes are optimized to deform the canonical mesh towards the captured 3D mesh ?

**Comment by PooyaDeperson** [comment]
Hello just a heads-up! There's a new page with high-quality references and a detailed guide on creating ARKit's 52 facial blendshapes
https://pooyadeperson.com/the-ultimate-guide-to-creating-arkits-52-facial-blendshapes/
