### ISSUE TITLE
Build a MediaPipe AAR  error

### ISSUE THREAD

**Issue by siliconvallley** [google/mediapipe#3422]
Refer to the construction steps of the official website:
https://google.github.io/mediapipe/getting_started/android_archive_library.html

1. 
>$ cd mediapipe/examples/android/src/java/com/google/mediapipe/apps/ 
$ mkdir aar_example
$ cd aar_example
$ touch BUILD

2. Put the following content in the BUILD file.

> load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
> mediapipe_aar(
    name = "mediapipe_face_detection",
    calculators = ["//mediapipe/graphs/face_detection:mobile_calculators"],
)

3. Run the Bazel build command to generate the AAR.

> bazel build -c opt --strip=ALWAYS \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    --legacy_whole_archive=0 \
    --features=-legacy_whole_archive \
    --copt=-fvisibility=hidden \
    --copt=-ffunction-sections \
    --copt=-fdata-sections \
    --copt=-fstack-protector \
    --copt=-Oz \
    --copt=-fomit-frame-pointer \
    --copt=-DABSL_MIN_LOG_LEVEL=2 \
    --linkopt=-Wl,--gc-sections,--strip-all \
	--verbose_failures \
    //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar

Result: There is a build error, can you help me to see what the problem is?

![1655102371530](https://user-images.githubusercontent.com/18340690/173294260-76a4ec4d-6152-4485-bfac-298aba3778a4.jpg)

**Comment by kuaashish** [comment]
Hi @siliconvallley!, Could you please try to use Android **SDK release 30.0.0 or above** and **NDK version between 18 and 21**. Please follow the [instructions](https://google.github.io/mediapipe/getting_started/android.html) mentioned in the documentation. Thank you!

**Comment by siliconvallley** [comment]
Hi @kuaashish，

Thanks for replying to my issue.

My problem is solved.
![1655261941194](https://user-images.githubusercontent.com/18340690/173727387-4f41d531-972c-4715-ad0d-277b350631c9.jpg)

First I find the file "mediapipe_aar.bzl" which outputs error log 1, 
then through error log 2 "/bin/bash:$'\r': command not found" 
I guess the current error should be in "mediapipe_aar.bzl" caused by newlines, 
so I did the following to the "mediapipe_aar.bzl" file:

`sed -i 's/\r$//' mediapipe_aar.bz`

solved the problem.

**Comment by kuaashish** [comment]
Hi @siliconvallley, Thank you for letting us know. Could we move this issue to closed status?

**Comment by siliconvallley** [comment]
Hi @kuaashish，Thank you for your reply. I think this issue should be closed.

**Comment by kuaashish** [comment]
Hi @siliconvallley, Thanks for the confirmation! Closing this issue as it resolved.
