### ISSUE TITLE
Mediapipe face detector's (short) predicted bbox coordinates are affected by the min_detection_confidence (threshold) value.

### ISSUE THREAD

**Issue by Shubhambindal2017** [google/mediapipe#3423]
**System information** 

- Browser - Google Chrome Version 102.0.5005.63
- Programming Language and version - Python 3.7.13
- Mediapipe version - for browser npm face_detection@0.4.1646425229 while for python test media pipe v0.8.10
- Solution: Face Detection

**Describe the current behavior:**
I have done this test for the short-range face_detection model. For both python-based as well for javascript-based solution, I found that for the same image with the change in min_detection_confidence, the predicted bbox coordinates changes by some precision, while predicted confidence scores for the bboxes remains the same. 
As this short-range face detection model is used for face_mesh, face_mesh output is also affected by this by a small margin (Example - (NOT FOR THE BELOW SHARED IMAGE) resulting in a very weird case for a unique image (not common and not many), for the same image, a low thresh resulting in no face_mesh predicted while a high thresh resulting in a face_mesh predicted, I noticed that this is because bbox are predicted for both cases, but a change in predicted bbox results for this behavior). I noticed this issue, while I was trying to find the best min_detection_confidence threshold for my data.

**Describe the expected behavior:**
The expected behavior is that for the same image the bbox coordinates values should not change with a change in min_detection_confidence, given that their confidence score is greater than or equal to the set min_detection_confidence.

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Image that I am using for both tests - [Image](https://images.popbuzz.com/images/63063?crop=16_9&width=660&relax=1&signature=YY3yb4mnau4LYXb7YrtahWe1lIM=)**
![image](https://user-images.githubusercontent.com/31540058/173306367-7a1e317c-d226-404b-b23e-041924290ee8.jpg)

1. For Javascript Solution (Opening with a live server through VS Code)

``` javascript
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils/camera_utils.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils/control_utils.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/drawing_utils.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/face_detection/face_detection.js" crossorigin="anonymous"></script>
</head>

<body>
  <div class="container">
    <video class="input_video"></video>
    <img id='image_element' src="" crossorigin="anonymous">
    <canvas class="output_canvas" width="1280px" height="720px"></canvas>
  </div>
</body>
</html>

<script type="module">
  const videoElement = document.getElementsByClassName('input_video')[0];
  const canvasElement = document.getElementsByClassName('output_canvas')[0];
  const canvasCtx = canvasElement.getContext('2d');
  
  const image = document.getElementById("image_element");
  image.src = "image.jpg"

  function onResults(results) {
    // Draw the overlays.
    canvasCtx.save();
    canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
    canvasCtx.drawImage(
        results.image, 0, 0, canvasElement.width, canvasElement.height);
    if (results.detections.length > 0) {
      for (const detection of results.detections){
        console.log(detection.boundingBox)
        drawRectangle(
            canvasCtx, detection.boundingBox,
            {color: 'blue', lineWidth: 4, fillColor: '#00000000'});
        drawLandmarks(canvasCtx, detection.landmarks, {
          color: 'red',
          radius: 5,
        });
      }
    }
    canvasCtx.restore();
  }
  
  const faceDetection = new FaceDetection({locateFile: (file) => {
    return `https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.4.1646425229/${file}`;
  }});
  faceDetection.setOptions({
    model: 'short',
    minDetectionConfidence: 0.4 // try changing it to 0.5
  });
  faceDetection.onResults(onResults);
  
  await faceDetection.send({image: image})

  </script>
```

For min_detection_confidence - 0.4, predicted bbox coordinates : 
![image](https://user-images.githubusercontent.com/31540058/173305525-138b2318-8780-4862-82ca-6991f4fab6e5.png)
For min_detection_confidence - 0.5, predicted bbox coordinates : 
![image](https://user-images.githubusercontent.com/31540058/173305552-40d6df96-f11f-4dae-a744-0da5af97ff9f.png)

You can notice, that for the same image with a change in min_detection_confidence the values of the predicted bboxes are not exactly the same, while ideally, they should be exactly the same

2. For Python-Based Solution 

You can find similar behaviour here at this colab notebook : [Notebook](https://colab.research.google.com/drive/1e1jzZAZHu3FORdvGaub5e2bpilntAouf?usp=sharing)

![image](https://user-images.githubusercontent.com/31540058/173310993-5a2ddb3a-711f-4af8-b14a-9a603bd46d8f.png)

All predicted boxes are not exactly the same (with all floating points) - meaning that the threshold is affecting the predicted bbox coordinate values.

**Comment by sureshdagooglecom** [comment]
Hi @Shubhambindal2017 ,
Threshold impact will be more in detecting the bounding boxes , hence it is necessary to set appropriate threshold values.

**Comment by Shubhambindal2017** [comment]
Yes, but thresholds should not change/affect the same bounding boxes coordinates values (assuming that their scores are >= set confidence score). It seems to be a bug, I have explained this issue more clearly in my above post.

**Comment by kuaashish** [comment]
Hello @Shubhambindal2017,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
