### ISSUE TITLE
Control 5 servos with 5 fingers

### ISSUE THREAD

**Issue by mslmgzde** [google/mediapipe#3424]
i want to control 5 servo with my 5 fingers angles . How can I do it ? please help me

**Comment by mslmgzde** [comment]
this is my code 4 servos working but fifth one is not working. I get the issue that the bytes must be within the range (0, 256)
can you help me ?

`import cv2
import serial
import mediapipe as mp
import math
import numpy as np
import time
import pyfirmata

#--------------

board = pyfirmata.Arduino('COM4')
servoisaret = board.get_pin('d:5:s')
servoorta = board.get_pin('d:9:s')
servoyuz = board.get_pin('d:10:s')
servoserce = board.get_pin('d:6:s')
servob = board.get_pin('d:11:s')
  

mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands



# Webcam Setup
wCam, hCam = 640, 480
cam = cv2.VideoCapture(0)
cam.set(3,wCam)
cam.set(4,hCam)


with mp_hands.Hands(
    model_complexity=0,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5) as hands:

  while cam.isOpened():
    success, image = cam.read()

    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = hands.process(image)
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    if results.multi_hand_landmarks:
      for hand_landmarks in results.multi_hand_landmarks:
        mp_drawing.draw_landmarks(
            image,
            hand_landmarks,
            mp_hands.HAND_CONNECTIONS,
            mp_drawing_styles.get_default_hand_landmarks_style(),
            mp_drawing_styles.get_default_hand_connections_style()
            )

    # multi_hand_landmarks method for Finding postion of Hand landmarks      
    lmList = []
    if results.multi_hand_landmarks:
      myHand = results.multi_hand_landmarks[0]
      for id, lm in enumerate(myHand.landmark):
        h, w, c = image.shape
        cx, cy = int(lm.x * w), int(lm.y * h)
        lmList.append([id, cx, cy])          

    # Assigning variables for Thumb and Index finger position
    if len(lmList) != 0:
     
      #isaret
      x1, y1 = lmList[5][1], lmList[5][2]
      x2, y2 = lmList[8][1], lmList[8][2]
     
      #orta

      x3, y3 = lmList[9][1], lmList[9][2]
      x4, y4 = lmList[12][1], lmList[12][2]
      
      #yuzuk

      x5, y5 = lmList[13][1], lmList[13][2]
      x6, y6 = lmList[16][1], lmList[16][2]
      
      #serce

      x7, y7 = lmList[17][1], lmList[17][2]
      x8, y8 = lmList[20][1], lmList[20][2]
      
      #bas

      x9, y9 = lmList[1][1], lmList[1][2]
      x10, y10 = lmList[4][1], lmList[4][2]

      # Marking Thumb and Index finger
      cv2.circle(image, (x1,y1),15,(255,255,255))  
      cv2.circle(image, (x2,y2),15,(255,255,255))
      cv2.circle(image, (x3,y3),15,(255,255,255))  
      cv2.circle(image, (x4,y4),15,(255,255,255))
      cv2.circle(image, (x5,y5),15,(255,255,255))
      cv2.circle(image, (x6,y6),15,(255,255,255))
      cv2.circle(image, (x7,y7),15,(255,255,255))
      cv2.circle(image, (x8,y8),15,(255,255,255))
      cv2.circle(image, (x9,y9),15,(255,255,255))
      cv2.circle(image, (x10,y10),15,(255,255,255))   
      cv2.line(image,(x1,y1),(x2,y2),(255,0,0),3)
      cv2.line(image,(x3,y3),(x4,y4),(0,255,0),3)
      cv2.line(image,(x5,y5),(x6,y6),(0,255,0),3)
      cv2.line(image,(x7,y7),(x8,y8),(0,255,0),3)
      cv2.line(image,(x9,y9),(x10,y10),(0,255,0),3)
      length = math.hypot(x2-x1,y2-y1)
      length2 = math.hypot(x4-x3,y4-y3)
      length3 = math.hypot(x6-x5,y6-y5)
      length4 = math.hypot(x8-x7,y8-y7)
      length1 = math.hypot(x10-x9,y10-y9)
      if length < 180:
        cv2.line(image,(x1,y1),(x2,y2),(0,0,0),3)

      
      Pos = np.interp(length, [50, 220], [0, 180])
      Posgripper= (round(Pos))
      #print(Posgripper)
      converted_Posgripper = str(Posgripper)
      cv2.putText(image, str(Posgripper), (50, 60), cv2.FONT_HERSHEY_COMPLEX, 2, (255, 0, 0))
      #cv2.line(image, 320, 320, (0,0,0), 2)
      Servopos=(180-Posgripper)
      print (Servopos)
      servoisaret.write(Servopos)

      if length2< 180:

       Pos2 = np.interp(length2, [50, 200], [0, 180])
       Posgripper2= (round(Pos2))
       #print(Posgripper)
       converted_Posgripper2 = str(Posgripper2)
       cv2.putText(image, str(Posgripper2), (50, 120), cv2.FONT_HERSHEY_COMPLEX, 2, (0, 255, 0))
       #cv2.line(image, 320, 320, (0,0,0), 2)
       Servopos2=(180-Posgripper2)
       print (Servopos2)
       servoorta.write(Servopos2) 

      if length3< 180:

       Pos3 = np.interp(length3, [50, 200], [0, 180])
       Posgripper3= (round(Pos3))
       #print(Posgripper)
       converted_Posgripper3 = str(Posgripper3)
       cv2.putText(image, str(Posgripper3), (50, 180), cv2.FONT_HERSHEY_COMPLEX, 2, (0, 255, 0))
       #cv2.line(image, 320, 320, (0,0,0), 2)
       Servopos3=(180-Posgripper3)
       print (Servopos3)
       servoyuz.write(Servopos3) 

      if length4< 180:

       Pos4 = np.interp(length4, [50, 150], [0, 180])
       Posgripper4= (round(Pos4))
       #print(Posgripper)
       converted_Posgripper4 = str(Posgripper4)
       cv2.putText(image, str(Posgripper4), (50, 240), cv2.FONT_HERSHEY_COMPLEX, 2, (0, 255, 0))
       #cv2.line(image, 320, 320, (0,0,0), 2)
       Servopos4=(180-Posgripper4)
       print (Servopos4)
       servoserce.write(Servopos4) 

      
    
    cv2.imshow('handDetector', image) 
    if cv2.waitKey(1) & 0xFF == ord('q'):
      break
cam.release()`

**Comment by ayushgdev** [comment]
@mslmgzde Would you please let us know if your issue is resolved or you are still looking for a resolution?
