### ISSUE TITLE
Why rotation values are so noisy

### ISSUE THREAD

**Issue by UX3D-mazzini** [google/mediapipe#3427]
Solution: Objectron
Language: Javascript API

I printed the rotation values in Euler form using threejs. I wonder why this signal is so jittery if it is because of mediapipe or is something I did wrong. I also find it weird that the y coordinate is pretty smooth. Is this related to the GimbalLock? Does somebody have the same issue?
 
measurements taken in static environment
![rotation](https://user-images.githubusercontent.com/91960463/173547005-c1e397e3-038f-4fe0-bcba-3f4c8d2c4cb0.png)
t

**Comment by sureshdagooglecom** [comment]
Hi @UX3D-mazzini ,
Could you share more information to reproduce this issue.

**Comment by matildao-pane** [comment]
Thanks fr the reply, but I was referring to Objectron

**Comment by UX3D-mazzini** [comment]
Thanks for the reply but I was referring to the OBjectron solution, what is the difference?
