### ISSUE TITLE
What's the meaning of Z value in face landmarks 3D?

### ISSUE THREAD

**Issue by colincheung755** [google/mediapipe#3429]
Hi, I'm still confused about the Z value in 3D facial landmarks. To be clear, how is the value Z calculated in your GROUND TRUTH?

Thanks_

**Comment by colincheung755** [comment]
is right for above question?
![image](https://user-images.githubusercontent.com/107389015/173782101-973df5f7-5ba8-44af-b83a-919b17ac427a.png)

**Comment by kuaashish** [comment]
Hi @colincheung755, Have a look at this comment https://github.com/google/mediapipe/issues/1895#issuecomment-822121488 face geometry is clearly explained with all the coordinates. Thank you!

**Comment by colincheung755** [comment]
你好，邮件我已收到。张昱航

**Comment by colincheung755** [comment]
你好，邮件我已收到。张昱航
