### ISSUE TITLE
Option to return tensors from Face Mesh

### ISSUE THREAD

**Issue by mattrossman** [google/mediapipe#3433]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): Face Mesh
- Programming language : JavaScript, TypeScript
- Are you willing to contribute it (Yes/No): Yes, pending #1408

**Describe the feature and the current behavior/state:**

I would like to receive Face Mesh predictions as `tf.Tensor` values rather than plain JavaScript objects. This would allow the values to remain on the GPU for further processing.

Currently, a large portion of the Face Mesh animation loop is spent reading from the GPU (profiled from [here](https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html?model=mediapipe_face_mesh)):

<img width=500 src="https://user-images.githubusercontent.com/22670878/173895239-6d91022d-acfe-4a08-8294-e2c8147e0ebe.png" />

My understanding (correct me if I'm wrong) is that this operation is responsible for converting the `tf.Tensor` texture data on GPU into JavaScript values for the CPU. For those who wish to perform further Tensorflow computation on the mesh output, this step adds significant and unnecessary waiting time.

**Will this change the current api? How?**

Yes. An older distribution of Tensorflow's facemesh included a `returnTensors` parameter in its API, [archived here](https://github.com/tensorflow/tfjs-models/tree/facemesh-v0.0.5/facemesh). This flag allowed the mesh to be output as `tf.Tensor2D` according to [the type definitions](https://cdn.jsdelivr.net/npm/@tensorflow-models/facemesh@0.0.5/dist/index.d.ts).

I propose a similar parameter for the MediaPipe solution within `FaceMeshInterface.setOptions()`.

For example:

```js

faceMesh.setOptions({
  returnTensors: true  // default: false
});
```

This would therefore change the type definition for return values too.

**Who will benefit with this feature?**

Users of `@mediapipe/face_mesh` as well as the `@tensorflow-models/face-landmarks-detection` wrapper.

**Please specify the use cases for this feature:**

This feature is useful for those want to build Tensorflow models on top of the Face Mesh solution with maximum performance.

**Any Other info:**

N/A

**Comment by kuaashish** [comment]
Hi @mattrossman, 
Thanks for raising this feature request. This looks like an interesting request. We will discuss this feature internally and prioritize it among others. Thank you!

**Comment by kuaashish** [comment]
Hello @mattrossman,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
