### ISSUE TITLE
MediaPipe C++ API compile for android

### ISSUE THREAD

**Issue by jyh2378** [google/mediapipe#3435]
Hi,
I want to MediaPipe C++ API on android.
Is it possible to cross-compile to generate .so or .a for C++ API for Android?
I can't find any information for C++ API for android information

**Comment by kuaashish** [comment]
Hi @jyh2378, Currently MediaPipe does not have the C++ interface to build Android solutions. You can create [Android AAR using any solution ](https://google.github.io/mediapipe/getting_started/android_archive_library.html#mediapipe-android-archive) to build android examples. We will let you know if there is any specific update on the above request. Thank you!

**Comment by jyh2378** [comment]
Thank you for answer. I hope that this part will be added someday!
