### ISSUE TITLE
Can ARCore and Mediapipe co-work together?

### ISSUE THREAD

**Issue by TZECHIN6** [google/mediapipe#3436]
Hi, I am having a hard time to finding a way to integrate both AI & AR. I am trying to first use object detection model to detect custom-object (YOLO preferred) --> Pass the class and bounding box coordination to ARCore --> ARCore put a 3D model/flowing text on top of the detected object.

So, could I pass the video stream to Mediapipe, then object detector will work on that captured frame, and pass back the class and location to the ARCore to render a virtual object on top. Does it supposes to work in this way or do I misunderstanding the usage of Mediapipe?

**Comment by kuaashish** [comment]
Hi @TZECHIN6, Have you looked at this closed issue #583 and [comment](https://github.com/google/mediapipe/issues/583#issuecomment-609919618). 
Please let us know if you still need any help. Thank you!

**Comment by TZECHIN6** [comment]
Hi @kuaashish , sorry i think i still need your help on this. If Unity is used for AR implementation, do i still need ARCore? or Unity + Mediapipe can do the trick for my task once I could build my own AAR?

**Comment by kuaashish** [comment]
Hi @TZECHIN6, Unity is not officially supported by **MediaPipe** yet. Assuming this [MediaPipeUnityPlugin](https://github.com/homuler/MediaPipeUnityPlugin) could be more helpful. Thank you!
