### ISSUE TITLE
What is the algorithm that use mediapipe solution pose ?

### ISSUE THREAD

**Issue by FwZtheone** [google/mediapipe#3437]
Hello everyone, I would like to understand how mediapipe works with the Pose solution. is it machine learning or deep learning if so what type of learning is it? then what algorithm does it use? I searched but I did not find house

**Comment by sureshdagooglecom** [comment]
Hi @FwZtheone ,
Mask R-CNN is a very popular algorithm for instance segmentation. The model has the capability to simultaneously localize and classify objects by creating a bounding box around the object and also by creating a segmentation mask. The basic architecture can be easily extended for Human Pose Estimation tasks.

**Comment by FwZtheone** [comment]
Hi, I did some research. I came to the conclusion that the Mediapipe Pose solution is blazepose which is itself deep learning, in terms of architecture it must be CNN

**Comment by sureshdagooglecom** [comment]
Hi @FwZtheone ,
It is using algorithm which is similar to R-CNN architecture.
