### ISSUE TITLE
mediapipe==0.8.3 Solutions.Pose , how to set up model_complexity 

### ISSUE THREAD

**Issue by 5A8G0001** [google/mediapipe#3438]
The version I originally used was mediapipe==0.8.10,but for other reasons I had to use 0.8.3.
however, the 0.8.3 version does not have this model_complexity  parameter when it is initialized.
Are there any other alternatives?

**Comment by sureshdagooglecom** [comment]
Hi @5A8G0001 ,
Could you please 0.8.9 version for model complexity , since we don't have model complexity parameter in 0.8.3.

**Comment by 5A8G0001** [comment]
> Hi @5A8G0001 , Could you please 0.8.9 version for model complexity , since we don't have model complexity parameter in 0.8.3.
thanks for your reply.
But since I have to use python3.6.6 to develop, I have to use 0.8.3

**Comment by 5A8G0001** [comment]
> Hi @5A8G0001 ,
> can we close this issue if the issue got resolved?

ok, thank you very much for your reply.
