### ISSUE TITLE
Run Mediapipe on background service (Android)

### ISSUE THREAD

**Issue by fiveshit** [google/mediapipe#3439]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>
I want to run Mediapipe on the background service .Is it possible?
I want to implement a function like "TouchFree". 
 
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution Android 11
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):
- Programming Language and version : Java

**Describe the expected behavior:**
It can handtracking to control phone/tv on Android.
Using mediapipe detect my finger to control Android device.
**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by sureshdagooglecom** [comment]
Hi @fiveshit ,
Could you provide steps to reproduce this issue and please elaborate this issue to know more.

**Comment by fiveshit** [comment]
Hi @sureshdagooglecom 
I just would to know it is possible ? Because I tried to implement service but it's failed.
for example code as below:
MainActivity.java
public class MainActivity extends AppCompatActivity implements View.OnClickListener{
private static final String TAG = "ServiceMain";
    // declaring objects of Button class
    private Button start, stop;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_hand_main);
        // assigning ID of startButton
        // to the object start
        start = (Button) findViewById( R.id.startButton );

        // assigning ID of stopButton
        // to the object stop
        stop = (Button) findViewById( R.id.stopButton );
        PermissionHelper.checkAndRequestCameraPermissions(this);
        // declaring listeners for the
        // buttons to make them respond
        // correctly according to the process
        start.setOnClickListener( this );
        stop.setOnClickListener( this );
    }
    public void onClick(View view) {

        // process to be performed
        // if start button is clicked
        if(view == start){
            // starting the service
            startService(new Intent( this, Hand_stracking_Service.class ) );
        }

        // process to be performed
        // if stop button is clicked
        else if (view == stop){

            // stopping the service
            stopService(new Intent( this, Hand_stracking_Service.class ) );

        }
    }
}


Hand_stracking_Service.java

public class Hand_stracking_Service extends Service {
 @Override
    public int onStartCommand(Intent intent, int flags, int startId){
    /* do hand tracking functions */
}
@Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }
}

**Comment by fiveshit** [comment]
Floating window function can work on my project so close it

**Comment by haoXu1990** [comment]
solved it ? 
i had the same problem.

**Comment by fiveshit** [comment]
Hi @haoXu1990 
you can use Floating window function to solve it.

**Comment by haoXu1990** [comment]
Hi, tks reply.
Floating window how to solved CameraX  lifecycleowner.

**Comment by fiveshit** [comment]
Hi @haoXu1990 
I don't understand your question. but maybe you can survey #513 rewrite camerahelper function

**Comment by MakeMeCookie** [comment]
@fiveshit  @haoXu1990 @sureshdagooglecom It was solved by using the floating window. The floating window is used on the screen, but does it apply to the background? Or is the app self-running, not the background?
