### ISSUE TITLE
How to draw custom drawing in mediapipe handtracking application 

### ISSUE THREAD

**Issue by suraj-0387** [google/mediapipe#344]
I am working on mediapipe hand tracking application and I want to do some modifications such that it should give me the landmark points of hand but it should not draw lines on the screen like current but I should able to modify it as per my requirement

**Comment by mgyong** [comment]
@suraj-0387 you have to make changes to the [annotation overlay calculator]?(https://github.com/google/mediapipe/blob/9437483827ca26bb41949cba5c9477f604c0a6fb/mediapipe/calculators/util/annotation_overlay_calculator.cc)
