### ISSUE TITLE
Error in detection.location_data

### ISSUE THREAD

**Issue by omkarmohanjoshi** [google/mediapipe#3441]
Hi

I am trying to get bounding box of the pose estimate using draw_detection function given in drawing_utils.py but I am getting error in location_data.  

Error is - "AttributeError: 'google.protobuf.pyext._message.FieldProperty' object has no attribute 'format'"

detection = detection_pb2.Detection giving me this error. I am not sure what input draw_detection needs for detection parameter.  Please hep me understand

**Comment by sureshdagooglecom** [comment]
Hi @omkarmohanjoshi ,
Could you provide any changes to investigate further on this issue.
