### ISSUE TITLE
How to stop (turn off) face tracking in JS based FaceMesh solution?

### ISSUE THREAD

**Issue by Shubhambindal2017** [google/mediapipe#3443]
**System information** (Please provide as much relevant information as possible)
- [MediaPipe version](https://github.com/google/mediapipe/releases): Mediapipe FaceMesh 0.4.1633559619
- Solution (e.g. FaceMesh, Pose, Holistic): FaceMesh
- Programming Language and version ( e.g. C++, Python, Java): Javascript

Is there any way with which I can stop (turn off) face tracking in the javascript-based faceMesh solution, such that for every image input it gets - it first do the face detection and doesn't rely on the predictions of the previous image (face tracking)? I know in the Python-based solution, this can be done by setting static_img_mode to True, but I am not able to find any such parameter for the JS-based solution. One option is to create a new facemesh object for every image using Facemesh({locateFile:......}), but it seems it is too expensive. Is there any other way, I can achieve this?

**Comment by Shubhambindal2017** [comment]
Thanks, @sureshdagooglecom for your reply, but I am looking to off face tracking for the Javascript-based FaceMesh solution, and I am not sure whether above mentioned commenting out step can be done for it.

**Comment by ayushgdev** [comment]
Hi @Shubhambindal2017 
For the moment, we don't support the `static_image_mode` parameter and the tracking cannot be switched off for Javascript based solutions.  To get more details on the Javascript API, please refer to [this](https://github.com/google/mediapipe/issues/1408#issuecomment-810652766) comment.
