### ISSUE TITLE
How to link manually installed opencv4 ??

### ISSUE THREAD

**Issue by jiapei100** [google/mediapipe#3449]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 22.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc/g++ 11.2.0/clang 14.0.3
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.10.4
- Installed using virtualenv? pip? Conda? (if python): pip
- [MediaPipe version](https://github.com/google/mediapipe/releases): 
```console
commit 4a20e9909d55838d5630366ce719844cf06ae85c (HEAD -> master, tag: v0.8.10, upstream/staging, upstream/master, upstream/HEAD, origin/master)
Author: MediaPipe Team <mediapipe-team@google.com>
Date:   Fri May 6 14:39:20 2022 -0700
......
```
- Bazel version: 5.2.0
- XCode and Tulsi versions (if iOS): N/A
- Android SDK and NDK versions (if android): N/A
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): N/A
- OpenCV version (if running on desktop): 4.6.0-dev

**Describe the problem**:
```console
➜  mediapipe git:(master) ✗ bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 --copt -I/usr/local/include/opencv4 --copt -L/usr/local/lib --copt -lopencv_core --copt -lopencv_calib3d --copt -lopencv_features2d --copt -lopencv_highgui --copt -lopencv_imgcodecs --copt -lopencv_imgproc --copt -lopencv_video --copt -lopen_videoio \

......
 
   34 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
      |                                                                                                        ^
ERROR: ....../mediapipe/mediapipe/examples/desktop/hand_tracking/BUILD:36:10: Linking mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu-2.params

Use --sandbox_debug to see verbose messages from the sandbox
ld.lld: error: unable to find library -l:libopencv_core.so
ld.lld: error: unable to find library -l:libopencv_calib3d.so
ld.lld: error: unable to find library -l:libopencv_features2d.so
ld.lld: error: unable to find library -l:libopencv_highgui.so
ld.lld: error: unable to find library -l:libopencv_imgcodecs.so
ld.lld: error: unable to find library -l:libopencv_imgproc.so
ld.lld: error: unable to find library -l:libopencv_video.so
ld.lld: error: unable to find library -l:libopencv_videoio.so
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 45.521s, Critical Path: 22.93s
INFO: 868 processes: 2 internal, 866 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

Just following [MediaPipe in C++ - Option 2: Running on GPU](https://google.github.io/mediapipe/getting_started/cpp)

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

As above...

**Comment by kuaashish** [comment]
Hi @jiapei100, Above issue might be with opencv installed successfully and not linked properly. Can you try the workaround mentioned here https://github.com/google/mediapipe/issues/2624#issuecomment-934325347. Thank you

**Comment by pius-braun** [comment]
I had the same issue yesterday on my raspberry pi 4.
I solved it by editing `mediapipe/third_party/opencv_linux.BUILD`.
In `cc_library()` I changed `linkopts` like this:

```
linkopts = [
        "-l:/usr/local/lib/aarch64-linux-gnu/libopencv_core.so",
        "-l:/usr/local/lib/aarch64-linux-gnu/libopencv_calib3d.so",
        "-l:/usr/local/lib/aarch64-linux-gnu/libopencv_features2d.so",
        "-l:/usr/local/lib/aarch64-linux-gnu/libopencv_highgui.so",
        "-l:/usr/local/lib/aarch64-linux-gnu/libopencv_imgcodecs.so",
        "-l:/usr/local/lib/aarch64-linux-gnu/libopencv_imgproc.so",
        "-l:/usr/local/lib/aarch64-linux-gnu/libopencv_video.so",
        "-l:/usr/local/lib/aarch64-linux-gnu/libopencv_videoio.so",
    ],
```
means, entering the full path to the opencv libraries.
Hope this helps.

**Comment by kuaashish** [comment]
Hi @pius-braun, Thanks for sharing the workaround. @jiapei100 could you please try the above [workaround](https://github.com/google/mediapipe/issues/3449#issuecomment-1161636500) and let us know if you successfully linked the opencv4. Thank you

**Comment by imyhxy** [comment]
There is a `-L/usr/local/lib` in the linkopts, which is the path to your user-compiled opencv, you must forgot the part.

```bash
  linkopts = [
    "-L/usr/local/lib",
    "-l:libopencv_core.so",
    "-l:libopencv_calib3d.so",
    "-l:libopencv_features2d.so",
    "-l:libopencv_highgui.so",
    "-l:libopencv_imgcodecs.so",
    "-l:libopencv_imgproc.so",
    "-l:libopencv_video.so",
    "-l:libopencv_videoio.so",
  ],
```
