### ISSUE TITLE
Bitmap Converter

### ISSUE THREAD

**Issue by farukkyldzx** [google/mediapipe#3451]
Hello. I use hair segmentation. I want to buy a mask (black & white) for hair coloring and to make changes. I looked at other issues and couldn't find the answer.

OR I want to see the image I see in Surface View as a bitmap
```
processor.addPacketCallback("output_video"){ packet->
            
        }
```

How can I convert the data I listen as a packet to a bitmap?

**Comment by sureshdagooglecom** [comment]
Hi @farukkyldzx ,
Hair segmentation can be done in hair_segmentation_mobile_gpu.pbtxt calculator usinfg below code snippet.
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hair_segmentation/hair_segmentation_mobile_gpu.pbtxt#:~:text=node%20%7B-,calculator%3A%20%22RecolorCalculator%22,%7D,-%7D
