### ISSUE TITLE
How to open, build and run iristrackinggpu with Android Studio (OSX)?

### ISSUE THREAD

**Issue by agGitHub** [google/mediapipe#3453]
Hi,

I don't understand how to open, build and run iristrackinggpu with Android Studio (on Mac OSX).

What root folder or root file should I open with Android Studio? Any specific script to execute once the project open?

Thanks.

**Comment by kuaashish** [comment]
Hi @agGitHub, Could you please respond to the above [comment](https://github.com/google/mediapipe/issues/3453#issuecomment-1161647769). Thank you

**Comment by agGitHub** [comment]
I don't manage to open properly this project in Android Studio (not recognized as Android project). Please give the detailed steps to open this project. Thanks.
