### ISSUE TITLE
How to remove specific landmarks from Hand Landmark Model

### ISSUE THREAD

**Issue by alexwtx** [google/mediapipe#3454]
[Hands solution](https://google.github.io/mediapipe/solutions/hands.html) issue.

**System information** 
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 10
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.7
- Bazel version: 
- Solution (e.g. FaceMesh, Pose, Holistic): Hands
- Programming Language and version ( e.g. C++, Python, Java): Python

**Describe the expected behavior:**
How to remove specific hand landmarks with mediapipe (Remove thumb)? I want to remove the thumb from the Hand landmark tracking Mediapipe model to only track my 4 fingers without the thumb. How can I do that?

**Here's what I have done so far and I was able to remove the unwanted CONNECTIONS by defining a custom connections list. But still landmark dots/points visible. How can I remove them?** 

![image](https://user-images.githubusercontent.com/106930836/174804362-acbfaada-fa9f-4ea5-b6fd-0d34ad0515f7.png)

**Standalone code you may have used to try to get what you need :**
````
import cv2
import mediapipe as mp

mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands
handConnection = [(5, 9), (10, 11), (5, 6), (15, 16), (13, 17), (18, 19),
            (6, 7), (0, 17), (9, 10), (0, 5), (14, 15),
            (11, 12), (19, 20), (9, 13), (17, 18), (13, 14), (7, 8)]

cap = cv2.VideoCapture(1)

def main():
    hands = mp_hands.Hands(
        min_detection_confidence=0.7, min_tracking_confidence=0.7)
    hand_landmark_drawing_spec = mp_drawing.DrawingSpec(thickness=5, circle_radius=5)
    hand_connection_drawing_spec = mp_drawing.DrawingSpec(thickness=10, circle_radius=10)

    while cap.isOpened():
        ret, image = cap.read()
        image = cv2.flip(image, 1)
        image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)
        results_hand = hands.process(image)
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        if results_hand.multi_hand_landmarks:
            for hand_landmarks in results_hand.multi_hand_landmarks:
                mp_drawing.draw_landmarks(
                    image=image,
                    landmark_list=hand_landmarks,
                    connections=handConnection,
                    landmark_drawing_spec=hand_landmark_drawing_spec,
                    connection_drawing_spec=hand_connection_drawing_spec)

        keypress = cv2.waitKey(1)
        if keypress == ord('c'):
            break
        cv2.imshow("Img", image)

    hands.close()
    cap.release()

main()
````

**Comment by alexwtx** [comment]
@kuaashish can you help please?

**Comment by sureshdagooglecom** [comment]
Hi @alexwtx ,
Yes, it can be done by removing input_stream: "landmark_render_data"or input_stream: "VECTOR:0:multi_hand_landmarks_render_data" from AnnotationOverlayCalculator config.

Depends on your application is on top of multihand or single hand tracking and the graph is on cpu or gpu, you need to modify one of the the following graphs:
[mediapipe/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_cpu.pbtxt](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_cpu.pbtxt#L142)

Line 142 in [252a571](https://github.com/google/mediapipe/commit/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7)

   input_stream: "VECTOR:0:multi_hand_landmarks_render_data" 

[mediapipe/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_gpu.pbtxt](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_gpu.pbtxt#L142)

Line 142 in [252a571](https://github.com/google/mediapipe/commit/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7)

**Comment by alexwtx** [comment]
> Hi @alexwtx , Yes, it can be done by removing input_stream: "landmark_render_data"or input_stream: "VECTOR:0:multi_hand_landmarks_render_data" from AnnotationOverlayCalculator config.
> 
> Depends on your application is on top of multihand or single hand tracking and the graph is on cpu or gpu, you need to modify one of the the following graphs: [mediapipe/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_cpu.pbtxt](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_cpu.pbtxt#L142)
> 
> Line 142 in [252a571](https://github.com/google/mediapipe/commit/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7)
> 
> input_stream: "VECTOR:0:multi_hand_landmarks_render_data"
> 
> [mediapipe/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_gpu.pbtxt](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_gpu.pbtxt#L142)
> 
> Line 142 in [252a571](https://github.com/google/mediapipe/commit/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7)

I'm sorry. I'm a beginner to MediaPipe. How can I access **multi_hand_renderer_gpu.pbtxt** file? there's no  **/mediapipe/graphs** directory in my local pip installed mediapipe library.
or do I have to create that file?

**Comment by sureshdagooglecom** [comment]
Hi @alexwtx ,
There  will be directory when you import MediaPipe files, please check files and import it ,so that you can do changes as steps mentioned in the above comments.
