### ISSUE TITLE
Error running hello_world on macos

### ISSUE THREAD

**Issue by carat-hansol** [google/mediapipe#3457]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): MacOS 12.1
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): Apple clang version 13.1.6
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.10
- Bazel version: 5.0.0
- XCode and Tulsi versions (if iOS): 
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:

I was following these installation steps: https://google.github.io/mediapipe/getting_started/install.html#installing-on-macos
But failed to run hello_world at the end.
Perhaps something to do with failing to download some dependencies via HTTP 404?

**Complete Logs:**

$ bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
Extracting Bazel installation...
Starting local Bazel server and connecting to it...

Lots of other logs..

Error: file '@bazel_tools//tools/cpp:toolchain_utils.bzl' does not contain symbol 'use_cpp_toolchain' (did you mean 'find_cpp_toolchain'?)

Thank you in advance :)

**Comment by pablovela5620** [comment]
I'm having this exact error aswell, on both my mac m1 machine and a different ubuntu machine. Looks like its specifically this
`load("@bazel_tools//tools/cpp:toolchain_utils.bzl", "find_cpp_toolchain", "use_cpp_toolchain")
Error: file '@bazel_tools//tools/cpp:toolchain_utils.bzl' does not contain symbol 'use_cpp_toolchain' (did you mean 'find_cpp_toolchain'?)`

Everything seemed to be building fine before, but I needed to clean the cache and used `bazel clean --expunge` and now I'm getting that error

**Comment by pablovela5620** [comment]
Hmm the interesting thing is I get a similar error when trying it on version 0.8.9 of mediapipe which uses bazel version 4.2.1, but I still get the same error

**Comment by carat-hansol** [comment]
FYI, I'm using mediapipe v0.8.10

**Comment by pablovela5620** [comment]
Looks like that fixed things for me on v0.8.10 🎉  Thank you so much for the solution

**Comment by sureshdagooglecom** [comment]
Hi @carat-hansol ,
Looks like issue has been resolved, can we close this issue?

**Comment by carat-hansol** [comment]
Yes, this issue is resolved.
Thanks :)

**Comment by kboyarshinov** [comment]
The real reason why this fails with Bazel 5.0.0 is because [rules_cc](https://github.com/bazelbuild/rules_cc) recently received some new commits that only work with newer Bazel, while [mediapipe uses `main`](https://github.com/google/mediapipe/blob/master/WORKSPACE#L37) branch as a direct dependency. 

@sureshdagooglecom Is there a reason why mediapipe doesn't use bundled `rules_cc`? I tried removing dependency from WORKSPACE and some builds I tested worked even with Bazel 5.0.0.

**Comment by schmidt-sebastian** [comment]
Thanks for the issue. We have fixed this internally and will prepare a new release shortly.

**Comment by brucechou1983** [comment]
Facing the same issue on version 0.8.8 and bazel 3.7.2.

**Comment by schmidt-sebastian** [comment]
We will update the code on GitHub today.
