### ISSUE TITLE
Selfie Segmentation (Javascript) requires unsafe-eval

### ISSUE THREAD

**Issue by mark-beeby** [google/mediapipe#3458]
**System information** (Please provide as much relevant information as possible)

- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Chrome 102
- Programming Language and version ( e.g. C++, Python, Java): Javascript
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.10 (NPM @mediapipe/selfie_segmentation@0.1.1632777926)
- Solution ( e.g. FaceMesh, Pose, Holistic ): Selfie Segmentation

**Describe the current behavior:**

Selfie Segmentation is now totally incompatible with Chrome Extensions as it requires `unsafe-eval`, Chrome have recently revoked this option from extensions without exception (Manifest v3) and so today there is no workaround. The eval occurs through the use of dynamically generated functions, as seen in:- https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1.1632777926/selfie_segmentation_solution_simd_wasm_bin.js.

**Describe the expected behavior:**

Selfie Segmentation should not require unsafe-eval, as this is no longer an option for Chrome Extension developers. 
`emscripten` also no longer requires the offending dynamic execution: https://github.com/emscripten-core/emscripten/issues/5911

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:

https://ostap0207.github.io/mediapipe-selfie-segmentation-csp/index.html
Code: https://github.com/ostap0207/mediapipe-selfie-segmentation-csp/blob/master/index.html
This page has SCP set to disallow unsafe-eval.

Error in the console:

```
selfie_segmentation_solution_wasm_bin.js:9 Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src https://cdn.jsdelivr.net".
    at new Function (<anonymous>)
    at createNamedFunction (selfie_segmentation_solution_wasm_bin.js:9)
    at extendError (selfie_segmentation_solution_wasm_bin.js:9)
    at selfie_segmentation_solution_wasm_bin.js:9
    at qa.h (selfie_segmentation.js:50)
    at ta (selfie_segmentation.js:14)
    at ua.next (selfie_segmentation.js:15)
    at selfie_segmentation.js:40
    at new Promise (<anonymous>)
    at Y (selfie_segmentation.js:40)
```

There was a similar issue reported last year, but at the time developers had workarounds, given these are no longer available I'm very much hoping we can get this issue more attention.

**Comment by mark-beeby** [comment]
@sureshdagooglecom / @kuaashish - a quick glance down the issues list shows @mhays-google no longer seems to support the MediaPipe project and this issue is likely to die without comment. Is there anyone else that might be able to input here?

**Comment by JamesOughton-about** [comment]
hi - any updates on this please?

**Comment by github-itsec-oculavis** [comment]
Is there any update on this issue?

**Comment by Bustuk** [comment]
Any update?

**Comment by desi-dimitrova** [comment]
I am facing the same issue with the holistic package when I am migrating a chrome extension from manifest v2 to v3... is there any update?

**Comment by nskaiser** [comment]
I too have this issue. I can no longer update my Chrome Extension which uses Manifest v2 and Holistic does not work with Manifest v3. What are our options here? Thanks.

**Comment by Bustuk** [comment]
Actually options are limited. It would be doable with sandboxes pages, [but currently they are bugged](https://developer.chrome.com/docs/extensions/mv3/known-issues/). Bug in chromium to follow: https://bugs.chromium.org/p/chromium/issues/detail?id=1247690. 
@nskaiser @desi-dimitrova I don't know if the solution I came up with will work for you, but I load mediapipe inside Iframe(and open camera etc from there) and communicate the results via post-message.

**Comment by virtualsapiens** [comment]
Thanks for the suggestion. It unfortunately won't work for our application.  This will prevent most new Chrome Extensions from utilizing MediaPipe so hopefully it can be addressed soon.

**Comment by nskaiser** [comment]
Thanks for the suggestion. It unfortunately won't work for our application. This will prevent most new Chrome Extensions from utilizing MediaPipe so hopefully it can be addressed soon.

**Comment by Sridhu-animaker** [comment]
You can replace the file in your project with the below link will work. It worked in my project.
https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1.1675465747/

**Comment by Sridhu-animaker** [comment]
To upgrade from manifest V2 to V3. You can replace the file in your project with the below link will work. It worked in my project.
https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1.1675465747/

**Comment by kuaashish** [comment]
Hello @mark-beeby,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by mmerezhko-hv** [comment]
The problem is not solved. unsafe-eval - worst decision.
