### ISSUE TITLE
Labels become mirror letters in iOS HandTracking

### ISSUE THREAD

**Issue by mbotsu** [google/mediapipe#346]
Hi.

Displaying a labels_to_render_data_calculator.cc with hand tracking on the iPhone turns into a mirror character.
Do you understand the cause?
The desktop will display normally.

Thank you.
![IMG_0123](https://user-images.githubusercontent.com/33709712/71468331-eb415c00-2808-11ea-8621-949b0a967a97.jpeg)

**Comment by vineet15889** [comment]
I have not tried, but I think you try to change the value of "_renderer.mirrored = YES;" to "NO" .
let me know if it work...

**Comment by eknight7** [comment]
@mbotsu Were you able to solve this issue?

**Comment by mbotsu** [comment]
Hi.
This is not expected behavior.
Inverting with "_renderer.mirrored" also inverts the video.

Another problem was found. Label cut off at edge of screen.

Thank you.
