### ISSUE TITLE
How to feed 3D data [79 x 18 x 2] as input tensor to tflite model?

### ISSUE THREAD

**Issue by mgarbade** [google/mediapipe#3461]
I have I written a custom graph:  
  - it expects an Eigen::Matrix as input
  - converts the matrix into a tensor
  - runs a tflite model on the tensor
  - convert the output tensor to a vector of floats
  - returns that vector

Here is the graph:
```
input_stream: "MATRIX:in"
output_stream: "FLOATS:out"

node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "MATRIX:in"
  output_stream: "TENSORS:image_tensor"
  options: {
    [mediapipe.TfLiteConverterCalculatorOptions.ext] {
      zero_center: false
    }
  }
}

node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS:image_tensor"
  output_stream: "TENSORS:tensor_features"
  options: {
    [mediapipe.TfLiteInferenceCalculatorOptions.ext] {
      model_path: "mediapipe/models/my_model.tflite"
    }
  }
}

node {
  calculator: "TfLiteTensorsToFloatsCalculator"
  input_stream: "TENSORS:tensor_features"
  output_stream: "FLOATS:out"
}
```

The graph compiles and runs, when i feed it with some toy input Eigen::Matrix. Weirdly, it does not even crash when the input matrix has wrong dimensions (but of course the output result is non-sensical).   
Anyway, I was trying to feed in the exact data that is expected by `my_model.tflite`, wich is (according to Netron) a tensor of shape [1 x 79 x 18 x 2]. This corresponds to pose-estimation results for my own pose-estimator (batch_size = 1, num_frames = 79, num_keypoints = 18, num_dimensions = 2 (x and y).  

As you might know `TfLiteConverterCalculator` only accepts IMAGE or MATRIX as inputs. However, MATRIX only stands for 2D Eigen::Matrix data structures, which is not suitable for my case.

How should I feed my data to the mediapipe graph?

Some further infos:  
- I can perform inference with the `my_model.tflite` model successfully in an python program, so the model works fine  
- OS: Ubuntu 18.04
- MediaPipe version: 4a20e99 tag: v0.8.10
- Solution: Hello World (modified)
- Programming Language: C++

**Comment by sureshdagooglecom** [comment]
Hi @mgarbade ,
We have similar issue regarding input to tflite model , please check this [issue](https://github.com/google/mediapipe/issues/199).

**Comment by mgarbade** [comment]
The referenced thread is very hard to read because of bad formatting and as far as I can see it's not directly related to my question: The two mentioned issue authors both try to feed an image to a tflite model, whereas I'm trying to feed a 3D tensor of float data to the tflite model.

**Comment by sureshdagooglecom** [comment]
Hi @mgarbade ,
Can you close the issue if the issue has been resolved.
