### ISSUE TITLE
How to change input type in detection_unique_id_calculator.cc?

### ISSUE THREAD

**Issue by Ar4enal** [google/mediapipe#3464]
in detection_unique_id_calculator.cc, I want to input `Detection` instead of `std::vector<Detection>`. The output does not change.

How to code in these parts?

https://github.com/google/mediapipe/blob/4a20e9909d55838d5630366ce719844cf06ae85c/mediapipe/calculators/util/detection_unique_id_calculator.cc#L57-L61

https://github.com/google/mediapipe/blob/4a20e9909d55838d5630366ce719844cf06ae85c/mediapipe/calculators/util/detection_unique_id_calculator.cc#L90-L105

**Comment by sureshdagooglecom** [comment]
Hi @Ar4enal ,
For a calculator with inputs, the framework calls Process() repeatedly whenever at least one input stream has a packet available. The framework by default guarantees that all inputs have the same timestamp (see [Synchronization](https://google.github.io/mediapipe/framework_concepts/synchronization.html) for more information). Multiple Process() calls can be invoked simultaneously when parallel execution is enabled. If an error occurs during Process(), the framework calls Close() and the graph run terminates.

**Comment by Ar4enal** [comment]
> Hi @Ar4enal , For a calculator with inputs, the framework calls Process() repeatedly whenever at least one input stream has a packet available. The framework by default guarantees that all inputs have the same timestamp (see [Synchronization](https://google.github.io/mediapipe/framework_concepts/synchronization.html) for more information). Multiple Process() calls can be invoked simultaneously when parallel execution is enabled. If an error occurs during Process(), the framework calls Close() and the graph run terminates.

Thanks for replying. I know how the calculator works. 

I just want to change the input stream type of this calculator. 

Because I separate these calculators into 2 systems and I can not pass `std::vector<Detection>` into the `detection_unique_id_calculator`. I can only pass `Detection` into it.

Looking forward to some advice~

**Comment by Ar4enal** [comment]
Solved by changing the input type into DetectionList.
