### ISSUE TITLE
Blink detection with Iris tracking solution in c++

### ISSUE THREAD

**Issue by FereshtehFeiz** [google/mediapipe#3466]
Hello, 
Beside Real-time Pupil Tracking, I want to have blink detection in the real time video(webcam)
my doubt is: is it possible to do it with Iris tracking solution in C++? The MediaPipe Visualizer of Iris Tracking when the eye is closed still shows the blue landmarks of the pupils.
https://viz.mediapipe.dev/demo/iris_tracking
The Iris tracking code let me add these features? or someone has already done? 
Thank you

**Comment by sureshdagooglecom** [comment]
Hi @FereshtehFeiz ,
We have detailed documentation on building real time blink detection , please follow the [documentation](https://google.github.io/mediapipe/solutions/iris.html) with steps written in doc.

**Comment by FereshtehFeiz** [comment]
Sorry but I couldn't find related to the blink detection, could you please show more in detail? 
Is there any GitHub repo for this paper for Irish landmark?
https://arxiv.org/pdf/2006.11341.pdf
Thank you

**Comment by sureshdagooglecom** [comment]
Hi @FereshtehFeiz ,
Can you close this issue if issue got resolved.
