### ISSUE TITLE
knift model with a smaller batch size

### ISSUE THREAD

**Issue by shesung** [google/mediapipe#3467]
The batch size of provided knift tflite models are 200, 400 and 1k。A smaller batch size can help to achieve a lower latency。Is there a way to change the batch size in tflite file?

**Comment by shesung** [comment]
Thanks! But knift tflite model did have a explicit batch_size(200, 400, 1k). Smaller batch size is prefered in some case.

**Comment by sureshdagooglecom** [comment]
Hi @shesung ,
Due to limited support , we don't have this support ,please use multiple graphs in parallel to run batch size images.

**Comment by Benjamin-Wegener** [comment]
i used different batch sizes, so it should be possible to generate smaller ones

**Comment by Benjamin-Wegener** [comment]
https://github.com/Benjamin-Wegener/KNIFT-GPU
