### ISSUE TITLE
Import a third-party library from github for iOS

### ISSUE THREAD

**Issue by fchen09** [google/mediapipe#3470]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):iOS15.5
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): not sure
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): objective-C
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases):latest on github
- Bazel version: 5.2.0
- XCode and Tulsi versions (if iOS): Xcode13
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:
I want to import a Obj-C library into mediapipe, and I tried the PodToBuild, but I used the url: https://github.com/Figure53/F53OSC. It seems not work.
Anyone knows the correct url or overall process with Bazel.
I am new with Bazel.
Thank you!

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/84703080/175981070-3ac7b35a-7f74-49b5-a5a9-0335409933c9.png">

**Comment by kuaashish** [comment]
Hi @fchen09, Could you please elaborate your query with complete details. Thank you!

**Comment by fchen09** [comment]
Hi, kuaashish,
I tried to import an Obj-C library into the Xcode project generated from the official example, but I am not sure how to do it.
So far, I just dragged the source file [from ](https://github.com/Figure53/F53OSC/tree/master/Sources) into the example, but I cannot import "F53OSC.h" with an error "F53OSC.h was not found".
Also, I tried to add a build file attached, and it shows a compile error below:
<img width="782" alt="Screen Shot 2022-07-03 at 5 46 28 PM" src="https://user-images.githubusercontent.com/84703080/177035892-80d130ee-75ef-4ae3-98e6-8451a8aa4b29.png">

[F53OSC.zip](https://github.com/google/mediapipe/files/9034569/F53OSC.zip)
The above BUILD file was produced by the tool: https://github.com/bazel-ios/cocoapods-bazel

Now, I am so confused about how to import an obj-c library in Mediapipe.
The usual ways like Cocoapods or simply dragging the library into the Ccode project does not work.
Could you give a tutorial about how to import a third-party obj-C library into Mediapipe?
This is important to secondary develop an APP with Mediapipe.
I appreciate your help.

**Comment by kuaashish** [comment]
Hi @fchen09, Please follow the[ instructions](https://google.github.io/mediapipe/getting_started/hello_world_ios.html#:~:text=Save%20the%20project%20to%20an%20appropriate%20location.%20Let%E2%80%99s%20call%20this%20%24PROJECT_TEMPLATE_LOC.%20So%20your%20project%20will%20be%20in%20the%20%24PROJECT_TEMPLATE_LOC/HelloWorld%20directory.%20This%20directory%20will%20contain%20another%20directory%20named%20HelloWorld%20and%20an%20HelloWorld.xcodeproj%20file) mentioned in the official documentation. Thank you!
