### ISSUE TITLE
Is there any way to install mediapipe on the mips architecture?

### ISSUE THREAD

**Issue by imhjh** [google/mediapipe#3471]
Hello! I need to run MediaPipe Python on mips64el Loongbian GNU/Linux 10 (buster), which is base on Debian 10.  i tried to use x86_64 (Debian GNU/Linux 10 buster )computer to build but it did't works, i don't known how to build. 

System information：
gcc version 8.3.0 (Debian 8.3.0-6+loongbian1)
Python 3.7.3

**Comment by kuaashish** [comment]
Hi @imhjh, Could you please elaborate your query with complete details. Thank you!

**Comment by imhjh** [comment]
> Hi @imhjh, Could you please elaborate your query with complete details. Thank you!

HI, 
I want to build mediapipe python package(python wheel files) for mips architecture on my conputer, is that ok to  Cross-Compile for MIPS architecture on Debian Linux? or i can only build this package on my MIPS architecture?
Sorry for my poor grammar.
