### ISSUE TITLE
Use two MediaPipe solutions at the same time.

### ISSUE THREAD

**Issue by GreenVegetables** [google/mediapipe#3472]
I have used the AAR of selfie-segmentation in my project and it is working fine. All contents of the package com.google.mediapipe are included in the AAR. like this:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/9369149/176104214-50742ebd-f4c6-4764-b58e-84b7f4853c24.png">

At the same time, I want to use facemesh with solution api way. In build.gradle, I added
```kotlin
implementation("com.google.mediapipe:solution-core:0.8.10.1-alpha-1")
implementation("com.google.mediapipe:facemesh:0.8.10.1-alpha-1")
```
When I run the project, it reports an error like this:

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/9369149/176104477-407affad-f68c-4ce3-97e1-f602ca115565.png">

Because the solution-core dependencies also contain these：

<img width="520" alt="image" src="https://user-images.githubusercontent.com/9369149/176104728-3041cc7f-95fe-448d-826e-41476c08b86b.png">

How can I use selfie-segmentation and facemesh at the same time. please help me. thanks

**Comment by zzmicer** [comment]
Hello @GreenVegetables
I've faced your issue before. The only solution I found - combine multiple solutions in one graph. For example you first perform selfie segmentation and after that run face detection.

**Comment by sureshdagooglecom** [comment]
Hi @GreenVegetables ,
Yes , you will have use 2 different solutions in two different times.
