### ISSUE TITLE
How to connect only a few characteristic points

### ISSUE THREAD

**Issue by 459zyt** [google/mediapipe#3474]
I use this method to display these points, but these points cannot be connected by lines？
I show the points 11, 12, 13, 14 on the body, but I can't connect the points with a line
![image](https://user-images.githubusercontent.com/94236736/176640510-50450317-9912-405f-b465-be301bbbb213.png)

```
from mediapipe.framework.formats import landmark_pb2
landmark_subset = landmark_pb2.NormalizedLandmarkList(
      landmark = [
          results.pose_landmarks.landmark[11],
          results.pose_landmarks.landmark[12], 
          results.pose_landmarks.landmark[13],
          results.pose_landmarks.landmark[14], 
      ]
)
annotated_image = image.copy()
mp_drawing.draw_landmarks(
    image=annotated_image,
    landmark_list=landmark_subset)
cv2_imshow(annotated_image)
```

**Comment by kuaashish** [comment]
Hi @459zyt, Could you please elaborate your query with complete details. Thank you!

**Comment by 459zyt** [comment]
> 你好@459zyt, 请您详细说明您的查询并提供完整的详细信息。谢谢！

I added more detailed instructions

**Comment by kuaashish** [comment]
Hi @459zyt, Please feel free to reopen if the issue still persists. Thank you!
