### ISSUE TITLE
Turning Calculators on/off during run time

### ISSUE THREAD

**Issue by PraveshARMedical** [google/mediapipe#3475]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 22.04
- [MediaPipe version](https://github.com/google/mediapipe/releases): latest
- Bazel version: N/A
- Solution (e.g. FaceMesh, Pose, Holistic): Iris Tracking
- Programming Language and version ( e.g. C++, Python, Java): Java

**Describe the expected behavior:** I wanted to know if there is a way to disable/hide/turn off the "Left: 47 cm & Right: 47 cm" text output from the calculator "iris_to_render_data_calculator.cc" during run time of my app. I would still like to enable it in runtime too.    [Image Link for Reference: ](https://imgur.com/a/e4Lytns)

Also, how can I take a picture frame from the output when we tap on screen or press button. In cameraX, we can use the ImageCapture Class to get an ImageProxy. Would be awesome if there is any CameraXHelper function with which I can achieve this or any other way.

I would appreciate your advice and help. Thanks!

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**iris_to_render_data_calculator.cc**
```

if (cc->Inputs().HasTag(kLeftIrisDepthTag) &&
      !cc->Inputs().Tag(kLeftIrisDepthTag).IsEmpty()) {
    const float left_iris_depth =
        cc->Inputs().Tag(kLeftIrisDepthTag).Get<float>();
    if (!std::isinf(left_iris_depth)) {
      line = "Left : ";
      absl::StrAppend(&line, ":", std::round(left_iris_depth / 10), " cm");
      lines.emplace_back(line);
    }
  }
  if (cc->Inputs().HasTag(kRightIrisDepthTag) &&
      !cc->Inputs().Tag(kRightIrisDepthTag).IsEmpty()) {
    const float right_iris_depth =
        cc->Inputs().Tag(kRightIrisDepthTag).Get<float>();
    if (!std::isinf(right_iris_depth)) {
      line = "Right : ";
      absl::StrAppend(&line, ":", std::round(right_iris_depth / 10), " cm");
      lines.emplace_back(line);
    }
  }

  AddTextRenderData(options, image_size, lines, render_data.get());
  
  void IrisToRenderDataCalculator::**AddTextRenderData**(
    const IrisToRenderDataCalculatorOptions& options,
    const std::pair<int, int>& image_size,
    const std::vector<std::string>& lines, RenderData* render_data) {
  int label_baseline_px = options.vertical_offset_px();
  float label_height_px =
      std::ceil(options.font_height_px() * kFontHeightScale);
  if (options.location() == IrisToRenderDataCalculatorOptions::TOP_LEFT) {
    label_baseline_px += label_height_px;
  } else if (options.location() ==
             IrisToRenderDataCalculatorOptions::BOTTOM_LEFT) {
    label_baseline_px += image_size.second - label_height_px * lines.size();
  }
  const auto label_left_px = options.horizontal_offset_px();
  for (int i = 0; i < lines.size(); ++i) {
    auto* label_annotation = render_data->add_render_annotations();
    label_annotation->set_thickness(5);

    label_annotation->mutable_color()->set_r(255);
    label_annotation->mutable_color()->set_g(0);
    label_annotation->mutable_color()->set_b(0);
    auto* text = label_annotation->mutable_text();
    text->set_display_text(lines[i]);
    text->set_font_height(options.font_height_px());
    text->set_left(label_left_px);
    text->set_baseline(label_baseline_px + i * label_height_px);
    text->set_font_face(options.font_face());
  }
}
```

**Comment by sureshdagooglecom** [comment]
Hi @PraveshARMedical ,
We have calculators implemented for different functions to perform , please check [this](https://google.github.io/mediapipe/framework_concepts/calculators.html#:~:text=A%20calculator%20is%20created%20by%20defining%20a%20new%20sub%2Dclass%20of%20the%20CalculatorBase%20class%2C%20implementing%20a%20number%20of%20methods%2C%20and%20registering%20the%20new%20sub%2Dclass%20with%20Mediapipe.%20At%20a%20minimum%2C%20a%20new%20calculator%20must%20implement%20the%20below%20four%20methods) document to understand more on calculators.
