### ISSUE TITLE
Pose tilt along Z-axis

### ISSUE THREAD

**Issue by sillysalat** [google/mediapipe#3476]
Greeting.

I've faced an issue with results of Pose estimation solution.
The technical side works well for me, but the results show repetitive missbehaviour. 

MediaPipe version: 0.8.10
- Solution Pose
- Python, Unity, C#, tflite.

I haven't modifies the code.

Clear frontal images of human facing the camera after inference produce results of figure tilted along a Z-axis.

Pose estimation of image below:
<img width="1076" alt="s" src="https://user-images.githubusercontent.com/65604434/176710792-8c35d855-b1ae-4bae-bc0a-b148ec35323a.png">
results in:
![download](https://user-images.githubusercontent.com/65604434/176710990-6ae07b93-3571-4d7a-9b47-6d583e4ae3a8.png)

I wonder if there's a treatment for this, as I have observed it independently of devices

**Comment by kboyarshinov** [comment]
@sillysalat Judging from the range of XYZ axies on the image, you seem to be using normalized landmarks for 3D visualations. These output landmarks are normalized to input image in XY axies, but Z represents approximate depth from the camera. Try using world landmarks output instead - real-world 3D coordinates representing keypoint location in space, measured in meters.

[More information](https://google.github.io/mediapipe/solutions/pose.html#output) about the output from the documentation.

**Comment by sillysalat** [comment]
> 

You are right, the plot I posted was based on normalized pose_landmarks. However it's because I was checking all the options and saved the wrong plot for the post.

Here's the same issue with pose_world_landmarks:
![pose_world_landmarks](https://user-images.githubusercontent.com/65604434/176737979-f4454f28-7e82-4a3f-a260-4cfa7e8d6474.png)

still hope there's a minor inattentiveness of mine to be easily solved.

**Comment by sureshdagooglecom** [comment]
Hi @sillysalat ,
Recently we updated the released model to produced additional world 3D landmarks output with origin in hips center.
More details can be found in API: https://google.github.io/mediapipe/solutions/pose#pose_world_landmarks
And in the blog: https://blog.tensorflow.org/2021/08/3d-pose-detection-with-mediapipe-blazepose-ghum-tfjs.html

**Comment by jksfood** [comment]
@sillysalat  @sureshdagooglecom Hello, I had the same problem, The Z axis is tilted forward, How can I solve this problem?
