### ISSUE TITLE
Support for `sim_arm64` (Apple Silicon) for iOS - Implementation steps included

### ISSUE THREAD

**Issue by mathaeus** [google/mediapipe#3477]
**System information** (Please provide as much relevant information as possible)

- Programming language : Objective C / iOS
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state:**
Currently the iOS Mediapipe framework does not support compilation for arm64 Simulator (Apple Silicon). That means one can't compile an iOS app that includes the Mediapipe framework on a MacBook with M1 chip in the "native way" (unless you're targeting a physical device). Running Xcode in `Rosetta` mode is the only workaround at the moment. 

## Steps to add support for `sim_arm64`

ℹ️ **I already implemented all the steps necessary in a fork and things work as far as I can tell.**

- Below are all of the details.
- I can't open a PR right away since I think the openCV part needs to be solved in general first. Happy for feedback.

#### 1. Add the config setting for the simulator to the Bazel config itself

<details>
 <img width="496" alt="01_config" src="https://user-images.githubusercontent.com/5389635/176710239-44a4da84-ff53-4b8c-b3ac-f3a338243269.png">
</details>

#### 2. Use a tensorflow release that supports sim_arm64
<details>
<img width="790" alt="02_tensorflow" src="https://user-images.githubusercontent.com/5389635/176710655-c0bb161c-8fc9-43ba-a786-857cf46c19f9.png">
</details>

#### 3. Use a pre-built openCV xcframework for iOS that supports sim_arm64
[Since the official openCV repo does not yet come with pre-built xcframeworks](https://github.com/opencv/opencv/pull/18976) that support `sim_arm64` I built it myself from source with the command below and then uploaded it to a custom repo as a release asset. This step would need further exploration for openCV just also providing the pre-built xcframework.

```
// Checked out 'https://github.com/opencv/opencv/releases/tag/4.6.0' which is the newest release at the time of writing
python3 platforms/apple/build_xcframework.py --out build --iphoneos_archs arm64 --iphonesimulator_archs arm64,x86_64 --build_only_specified_archs
```
<details>
<img width="888" alt="03_opencv" src="https://user-images.githubusercontent.com/5389635/176712153-3800128c-c3ee-4c00-a552-2f23b848260e.png">
</details>

#### 4. Update the Apple build rules in Bazel to the ones supporting xcframework (imports)
<details>
<img width="884" alt="04_bazel_rules" src="https://user-images.githubusercontent.com/5389635/176712261-89f0b2c6-2317-4277-84e2-a2ed61ac1bb3.png">
</details>

#### 5. Adapt the openCV code for xcframework
<details>
<img width="605" alt="05_xcframework" src="https://user-images.githubusercontent.com/5389635/176712361-63fd7a5f-c497-477f-8427-7803584f7e13.png">
</details>

----

**Will this change the current api? How?**

No

**Who will benefit with this feature?**

Anyone who is using the iOS Mediapipe framework (and is running on Apple Silicon - which will be sooner or later "everyone")

**Comment by mathaeus** [comment]
@sureshdagooglecom did you have some time to have a look at my suggested changes?

Is this something that the Mediapipe team can take care of or do you prefer me opening a PR?
The open question about how to integrate OpenCV still needs to be answered. It seems like from the official OpenCV repo we can't expect support for pre-built xcframeworks anytime soon unfortunately.

**Comment by mathaeus** [comment]
@kuaashish pinging you in the hope to get some feedback :)

**Comment by sglim** [comment]
+1

**Comment by mathaeus** [comment]
Bumping this 😬 

@sureshdagooglecom is this something that the Mediapipe team is planning to look into?

**Comment by shreyash-sharechat** [comment]
`this.issue.bump()`

**Comment by kuaashish** [comment]
Hello @mathaeus,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
