### ISSUE TITLE
Running Face Mesh on Android with specified images

### ISSUE THREAD

**Issue by MigraineSurvivor** [google/mediapipe#3478]
- OS Platform and Distribution (Android 11):
- Solution (FaceMesh):
- Programming Language (Java)
- Android Studio 
In the Android Face Mesh solution, it runs by selecting photos from the gallery. I would like to know how I could run a specific image without the user's interference. Automatically choosing a specific image either from the gallery or saved up drawable. 
I would like to know how I could do both of these (automatically choose from gallery and automatically choose from drawable). 
Thanks in advance

**Comment by sureshdagooglecom** [comment]
Hi @MigraineSurvivor ,
We don't support that in MediaPipe to run on specified images.

**Comment by MigraineSurvivor** [comment]
> Hi @MigraineSurvivor , We don't support that in MediaPipe to run on specified images.

I am actually new to Java and Android as well however, can't the following code be changed to accommodate a specific image?

Intent pickImageIntent = new Intent(Intent.ACTION_PICK);
pickImageIntent.setDataAndType(MediaStore.Images.Media.INTERNAL_CONTENT_URI, "image/*");
imageGetter.launch(pickImageIntent);

**Comment by sureshdagooglecom** [comment]
Hi @MigraineSurvivor ,
What is the error you are getting when you are executing that code.

**Comment by MigraineSurvivor** [comment]
> Hi @MigraineSurvivor , What is the error you are getting when you are executing that code.

I get no error, it works fine but I would like the button to automatically choose an image from the gallery or drawable without the user's interference instead of the user picking an image.

**Comment by sureshdagooglecom** [comment]
Hi @MigraineSurvivor ,
We do not have that support as of now , if the issue is resolved please close this issue.
