### ISSUE TITLE
Mediapipe Holistic AAR - Extract Keypoints

### ISSUE THREAD

**Issue by 1alexuwu** [google/mediapipe#3483]
I found a mediapipe holistic aar here https://github.com/shadow111/mediapipe-holistic-tracking-aar-example and it works fine. I combined some code from the mediapipe multihand tracking aar from mediapipe itself to make the holistic access the front cam. Now my question is how to extract keypoints? I can't find examples or documentation.

**Comment by sureshdagooglecom** [comment]
Hi @1alexuwu ,
We have issue running in the thread https://github.com/google/mediapipe/issues/64, please check this issue.
