### ISSUE TITLE
There is a problem with the meshing instance image of face_geometry

### ISSUE THREAD

**Issue by YongHe999** [google/mediapipe#3484]
There is a problem with the meshing sample image of face_geometry，

Below is a sample image from github

https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png

However, the image generated by the program is like the following one

https://mediapipe.dev/assets/img/photos/faceMesh.jpg

There are some differences in the division of the mesh between the two pictures. According to the line data of face_mesh_connections.py, the correct one should be the one below.

The triangle mesh list is created with reference to the coordinate point connection relationship in face_mesh_connections.py
https://github.com/google/mediapipe/pull/3419

**Comment by andrechen** [comment]
Can't find that **face_model_landmarks_triangles.txt**. But as i checked **canonical_face_model.obj** and **geometry_pipeline_metadata_landmarks.pbtxt**. Both files are coincident with canonical_face_model_uv_visualization.png. I can construct the exactly the same image as **canonical_face_model_uv_visualization.png** either from the canonical_face_model.obj or geometry_pipeline_metadata_landmarks.pbtxt. 

Maybe, that **face_mesh_connections.py** is not valid anymore?

**the 1st triangle's vertex indices are { 174, 156, 134 } (note obj file uses one-indexed)**
https://github.com/google/mediapipe/blob/63e679d99ca45b30514a9d84c9351a2d77bb9ba0/mediapipe/modules/face_geometry/data/canonical_face_model.obj#L937

**compare to the 1st first triangle indices { 173, 155, 133 } (zero-indexed)**
https://github.com/google/mediapipe/blob/63e679d99ca45b30514a9d84c9351a2d77bb9ba0/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt#L2392-L2394

**Comment by andrechen** [comment]
Can't find that **face_model_landmarks_triangles.txt**. But as i checked **canonical_face_model.obj** and **geometry_pipeline_metadata_landmarks.pbtxt**. Both files are coincident with canonical_face_model_uv_visualization.png. I can construct the exactly the same image as **canonical_face_model_uv_visualization.png** either from the canonical_face_model.obj or geometry_pipeline_metadata_landmarks.pbtxt. 

Maybe, that **face_mesh_connections.py** is not valid anymore?

**the 1st triangle's vertex indices are { 174, 156, 134 } (note obj file uses one-indexed)**
https://github.com/google/mediapipe/blob/63e679d99ca45b30514a9d84c9351a2d77bb9ba0/mediapipe/modules/face_geometry/data/canonical_face_model.obj#L937

**compare to the 1st first triangle indices { 173, 155, 133 } (zero-indexed)**
https://github.com/google/mediapipe/blob/63e679d99ca45b30514a9d84c9351a2d77bb9ba0/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt#L2392-L2394

**Comment by YongHe999** [comment]
There may be some problems with my expression, the grid displayed by the sample code on Python Colab is as follows,

![1](https://user-images.githubusercontent.com/97277469/177002722-9c311739-d5bf-45d6-8153-bd8bf45caaca.PNG)


canonical_face_model_uv_visualization.png is as follows，It is obvious that the meshing in the forehead is different。
![2](https://user-images.githubusercontent.com/97277469/177002725-73768fde-6415-480d-b48f-e4b5ba74bda0.PNG)


As for face_model_landmarks_triangles.txt, it's in https://github.com/google/mediapipe/pull/3419/files, just a list of grid indices

**Comment by andrechen** [comment]
So to speak, face_mesh_connections.py is incorrect and your triangle list file is not correct, either.

**Comment by YongHe999** [comment]
Mesh generation is a form of expression. The official Python example code shows that mesh generation and face_ mesh_ connections. Py is the same as canonical_ face_ model_ uv_ visualization. PNG is different. There needs to be a unity between the two. Maybe they need to modify the sample code.

**Comment by andrechen** [comment]
mediapipe/mediapipe/modules/face_geometry/data/canonical_face_model.fbx
![image](https://user-images.githubusercontent.com/2261137/177024337-a954b59c-48ac-4e87-9e8a-a80e824f7406.png)

mediapipe/mediapipe/modules/face_geometry/data/canonical_face_model.obj
![image](https://user-images.githubusercontent.com/2261137/177024353-c169d66e-e983-4ef8-8c24-8ebdc2b2250f.png)

**Comment by sureshdagooglecom** [comment]
Hi @YongHe999 ,
Are you still facing any issue.
