### ISSUE TITLE
how to run Iris Depth solution on webcamera or video file not static image?

### ISSUE THREAD

**Issue by andy380743909** [google/mediapipe#3486]
I can run the `iris_depth_from_image_desktop` successfully. 
And I know I must get EXIF info from Image using the `ImageFilePropertiesCalculator` calculator like this:

> Computes the focal length in pixels based on EXIF information stored in the
> image file. The output is an ImageFileProperties object containing relevant
> image EXIF information along with focal length in pixels.
> node {
>   calculator: "ImageFilePropertiesCalculator"
>   input_stream: "IMAGE:input_video"
>   output_side_packet: "image_file_properties"
> }

but the data type of the input_stream is Raw Image Data, so I need to get Raw Image Data from webcamera or video file.

Can anyone tell me how to do this?

**Comment by andy380743909** [comment]
I have run the Iris Depth Demo app on iPhone successfully, and I know how does it work, it obtain the focal length pixels from the iOS API, then feed it to the mediapipe graph through a input side packet. 
And also I can run the Iris Depth from image Demo on macOS, it accept a static image with EXIF info as input stream, the graph read the focal length pixels data from the EXIF, so mediapipe can calculate the Iris Depth.
But now I'm trying to build an macOS app using the built-in FaceTime HD Camera to calculate the Iris Depth, the key problem is how to get the `focal length pixels` of the built-in FaceTime HD Camera, I had try a lot of solutions, but still can not get it.

the solutions I had try:

### 1. build a graph with input_video as input stream, convert each frame of the video to Raw Image Data, then get EXIF from Raw Image Data

failed, because I didn't find an opencv API that can  convert frame of the video to Raw Image Data

### 2. use the macOS CoreMedia framework to get CameraIntrinsicMatrix info from CMSampleBuffer

`if #available(macOS 10.13, *) {
          if (!didReadCameraIntrinsicMatrix) {
              if let camData = CMGetAttachment(sampleBuffer, key:kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix, attachmentModeOut:nil) as? Data {
                  let matrix: matrix_float3x3 = camData.withUnsafeBytes { $0.pointee }
                  cameraIntrinsicMatrics = matrix
                  print(matrix)
                  // > simd_float3x3(columns: (SIMD3<Float>(1599.8231, 0.0, 0.0), SIMD3<Float>(0.0, 1599.8231, 0.0), SIMD3<Float>(539.5, 959.5, 1.0)))
                  didReadCameraIntrinsicMatrix = true
              }
          }
          
      } else {
          // Fallback on earlier versions
          
      }`

**Comment by kuaashish** [comment]
Hi @andy380743909, Have you looked at this closed issue #1133 and [comment](https://github.com/google/mediapipe/issues/1133#issuecomment-699239014). Thank you!

**Comment by andy380743909** [comment]
yes，we can close this issue now.

**Comment by xueyin220807** [comment]
> 我读过很多问题和堆栈溢出，我认为问题是如何获取相机内在矩阵，所以这不是媒体管道的范围。
> 
> 我已经找到了解决方案，我使用OpenCV和棋盘进行相机校准，所以我得到了相机内在矩阵，然后将其作为输入端数据包传递给mediapipe。
> 
> 谢谢！



> I have read many issues and stackoverflow，I think the problem is how to get the camera intrinsic matrix，so it's not the mediapipe's scope.
> 
> I have find the solution，I use OpenCV and chessboard to do camera calibration，so I get the camera intrinsic matrix，then pass it to mediapipe as input side packet.
> 
> thank you！
I also used python to get the matrix, but I do not know the technical details of the matrix passed to mediapipe, can you provide the code details?

thank you
