### ISSUE TITLE
Integration for Threejs or Blender coordinates

### ISSUE THREAD

**Issue by ireneb612** [google/mediapipe#3489]
It would be usefull to have a function that transfroms the coordinates to the coordinate systems of threejs or Blender! Would it be possible?

**Comment by sureshdagooglecom** [comment]
Hi @ireneb612 ,
Could you please elaborate w.r.t above issue.

**Comment by ireneb612** [comment]
@sureshdagooglecom So i'm trying to take the landmarks generated by the mediapipe pose model to my Three.js avatar! But it seems like the coodinate systems are different! I was wondering where is the origin of the landmarks? Is it in the Hips? does the y go positivelly up? does the x go positivelly to the right? does the z positivelly come towards the screen ? all these informations are not provided anywhere

**Comment by kuaashish** [comment]
@ireneb612,

Could you please let us know if you are still looking resolution for the use case mentioned or the issue has been resolved? 

Thank you!!
