### ISSUE TITLE
Android Solutions Examples are missing x86_64 architecture libs and get rejected by Google Play Store

### ISSUE THREAD

**Issue by hpflatorre** [google/mediapipe#3490]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 10 21H2 building for Android
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Java
- [MediaPipe version](https://github.com/google/mediapipe/releases):  [v0.8.10.2](https://github.com/google/mediapipe/tree/v0.8.10.2)
- Bazel version: not used
- Android SDK and NDK versions (if android): Android Studio Build tools 31.1.0-rc, NDK 21.4

**Describe the problem**:

The ready to use [Mediapipe Solutions Examples for android](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions) will build successfully but will not generate the x86_64 libraries. Without the x86_64 version of limediapipe_jni.so, any app based on the examples will be rejected by Google Plays Store for not complying with x64 requirements.

The other architectures (armeabiv7a arm64-v8a x86) are generated as expected. This is the result aab bundle in the inspector:
![image](https://user-images.githubusercontent.com/6450237/177207409-b1621544-01bd-4750-8923-0c44a513433e.png)

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

I followed the instructions from https://google.github.io/mediapipe/getting_started/android_solutions.html to setup the symbolic links and built the project directly on Android Studio

**Complete Logs:**
No errors from android build output

Is this an issue with the Example Android Studio Projects? Or maybe with the maven repositories?

**Comment by kuaashish** [comment]
Hi @hpflatorre, Have you looked at this closed issue #2979. Thank you!
