### ISSUE TITLE
How to use ImageProxy to render and analyze in mediapipe（Android）

### ISSUE THREAD

**Issue by 390057892** [google/mediapipe#3494]
At present, mediapipe uses cameraX preview for rendering. I want to use the ImageProxy generated by cameraX imageanalysis for incoming analysis. Is there a solution？

**Comment by 390057892** [comment]
> 你好@390057892, 由于支持有限，我们暂时没有此支持。

Does it support ByteBuffer format?

**Comment by 390057892** [comment]
Because I don't need preview rendering, I just want to use the algorithm to pass in ByteBuffer and return coordinate points.

**Comment by sureshdagooglecom** [comment]
Hi @390057892 ,
Yes it supports ByteBuffer format  , please check this code changes https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/framework/PacketCreator.java

**Comment by 390057892** [comment]
Can you provide me with a demo, thank you

**Comment by 390057892** [comment]
please give me a demo，thank you，I can't find the relevant usage

**Comment by sureshdagooglecom** [comment]
Hi @390057892 ,
what kind of usage you are looking for so that we can check based on that?
