### ISSUE TITLE
How can I get More Temporally Stable Face Landmarks!?  (ie less jitter)

### ISSUE THREAD

**Issue by Fredrum** [google/mediapipe#3495]
I'm working on Windows 64bit and Python.

Iv'e made a basic opecv + mediapipe face track example. I started with this code,
https://pysource.com/2021/05/14/facial-landmarks-detection-with-opencv-mediapipe-and-python/

Mediapipe for Python 0.8.10.1

- Solution (e.g. FaceMesh, Pose, Holistic):  **FaceMesh**

**Describe the expected behavior:**

I would like the result to be stable over time. So it's not jittering and skipping around when looking at the resulting sequence.
I am not concerned about latency or execution duration.
Currently the fitting around eyes and mouth looks good but the overall fitting of the 'face plate' is skipping around quite a lot. 
I would like it to looks smoothly stable as I watch it.

**Standalone code you may have used to try to get what you need :**

Currently setting up the FaceMesh like this,
`face_mesh = mp_face_mesh.FaceMesh(static_image_mode=False, max_num_faces=1, refine_landmarks=True, min_detection_confidence=0.5, min_tracking_confidence=0.95)`

I tried different min_tracking_confidence values.

How can achieve a more stable and less jittery result?

Cheers!

**Comment by Fredrum** [comment]
Hi and thank you very much for your reply and suggestions!
I will try that tool out and see if it is the solution I'm looking for!
Cheers

**Comment by sureshdagooglecom** [comment]
Hi @Fredrum ,
Can you close this issue if you have solution now.

**Comment by sureshdagooglecom** [comment]
@matthewwiese ,
Please open new issue for javascript based solutions.
