### ISSUE TITLE
mediapipe pose model for feet toe/heel is not accurate in some cases

### ISSUE THREAD

**Issue by denfromufa** [google/mediapipe#3496]
We are testing MediaPipe Human Body Pose Model in Colab notebooks via Python API and noticed some issues with heel and toe prediction when testing on video frames of running on treadmill.

As you can see on the picture for the leg that is behind the heel and toe keypoints/markers are misplaced in some cases.

We noticed that some other models can handle this scenario well.

Which dataset did you use to train a whole-body model that includes toe and heel markers?

See picture below:

<img width="267" alt="Screen Shot 2022-07-06 at 4 19 01 PM" src="https://user-images.githubusercontent.com/7870949/177647221-fc05474d-d784-40ad-a023-b605c860ee9a.png">

**Comment by denfromufa** [comment]
@sureshdagooglecom [this] is missing

**Comment by sureshdagooglecom** [comment]
Have added now , pleae check

**Comment by denfromufa** [comment]
Hi Sureshda, what is [this]? BTW, we tried heavy/full/lite blazepose models
in mediapipe as well as video stream option too.

**Comment by lagom03** [comment]
> Hi @denfromufa , Please [this](https://google.github.io/mediapipe/solutions/pose.html#:~:text=MediaPipe%20Pose%20is%20a%20ML,ML%20Kit%20Pose%20Detection%20API.) official document for pose in which it is mentioned algorithms and data have been used to train the models.

Hi, I can't access [this]. it says 404?? 
"The site configured at this address does not contain the requested file."
