### ISSUE TITLE
How to improve accuracy of Box Tracking (Desktop)

### ISSUE THREAD

**Issue by PZerua** [google/mediapipe#3497]
Hi!

I am doing some tests with the Box Tracking solution ([graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/tracking/object_detection_tracking_desktop_live.pbtxt)), and I am wondering if there is any way to improve the accuracy by changing graph/subgraphs parameters (at the cost of more performance). It works well when using my webcam, but I am trying to make it work in more stressed sutuations (for instance, detecting people in [this video](https://youtu.be/I8318biYyuU)).

First I increased the max number of detections [here](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/tracking/subgraphs/object_detection_cpu.pbtxt#L110). Then I  tried increasing the resolution [here](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/tracking/subgraphs/object_detection_cpu.pbtxt#L19) and [here](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/tracking/subgraphs/object_detection_cpu.pbtxt#L57), but does not seem to work at all (It breaks detection). I don't really know what else could I change, there are a lot of parameters that I find hard to understand.

Also, the console spams "no history. confidence : 1.0" even when standing still with my webcam, is this normal? 

Since there is not much documentation yet, I would appreciate some guidance on this.

Thanks!

**Comment by kuaashish** [comment]
Hi @PZerua, Could you confirm the full set of captions are used for "ObjectDetectionSubgraphCpu" and "ObjectTrackingSubgraphCpu" subgraphs. Thank you!

**Comment by PZerua** [comment]
Hi! Thanks, I am not sure what you mean by "captions", but the subgraphs are exactly the same as the ones located in "mediapipe/graphs/tracking/subgraphs/" except for max number of detections [here](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/tracking/subgraphs/object_detection_cpu.pbtxt#L110), which I increased.

I recently checked that the model only works with 320x320 images so it makes sense it does not work with other resolutions. I just wonder if accuracy can be improved changing other parameters when using Mediapipe in desktop.

Let me know if that answer you question. Thanks again.

**Comment by sureshdagooglecom** [comment]
Hi @PZerua ,
Could you please confirm what the full set of captions are for "ObjectDetectionSubgraphCpu",
 "ObjectTrackingSubgraphCpu".  if not, we could augment the subgraph/solution options, or suggest how user "hack" the options at the calculator level.  
if you have  all options, we must say this is true limitation of the solution.

**Comment by PZerua** [comment]
Sorry, I was on vacation.

Again, I'm not sure what you mean by "captions". If you mean the graph, I incorporated both "ObjectDetectionSubgraphCpu" and "ObjectTrackingSubgraphCpu" in a single graph so I could change paratemers easier. I'll attach it here so you can take a look:

[graph.txt](https://github.com/google/mediapipe/files/9350712/graph.txt)

Thanks.

**Comment by kuaashish** [comment]
Hello @PZerua,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
