### ISSUE TITLE
RuntimeError while loading face_landmark_with_attention.tflite (FaceMesh with attention tflite model)

### ISSUE THREAD

**Issue by adityasihag1804** [google/mediapipe#3498]
I'm trying to load `face_landmark_with_attention.tflite` in python in the following way and getting the following RuntimeError. Please help me out in this.

```
import tensorflow as tf
Interpreter = tf.lite.Interpreter
model_path = "face_landmark_with_attention.tflite"
interpreter = Interpreter(model_path = model_path)
interpreter.allocate_tensors()
```

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/var/folders/nt/k07ftqmx091blwpws3lg7w1r0000gn/T/ipykernel_19856/978597763.py in <module>
     17 interpreter = Interpreter(model_path = model_path)
     18 
---> 19 interpreter.allocate_tensors()
     20 
     21 input_details = interpreter.get_input_details()

/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/tensorflow/lite/python/interpreter.py in allocate_tensors(self)
    512   def allocate_tensors(self):
    513     self._ensure_safe()
--> 514     return self._interpreter.AllocateTensors()
    515 
    516   def _safe_to_run(self):

RuntimeError: Encountered unresolved custom op: Landmarks2TransformMatrix.
See instructions: https://www.tensorflow.org/lite/guide/ops_customNode number 192 (Landmarks2TransformMatrix) failed to prepare.
```

The given [link](https://www.tensorflow.org/lite/guide/ops_customNode) is giving 404 error.

I'm using tensorflow 2.8.0 on MacOS M1 machine.

**Comment by adityasihag1804** [comment]
@kuaashish 'face_landmark_with_attention.tflite' is the FaceMesh with attention model file provided in the repo. I'm trying to load up the given tflite model in python, and when `allocate_tensors` function for the model is called, the above-given error is thrown. The model has some special ops for attention. Which it is not able to recognise.

I'm guessing when the tflute model was created, `allow_custom_ops` for the converter was not set to `True`. Please look into this. I hope I was elaborate enough.

**Comment by kuaashish** [comment]
Hi @adityasihag1804, Landmarks2TransformMatrix is a special TFLite ops that has not been implemented in the latest release of TF version. You can try with [Tensorflow Source Code](https://github.com/KenjiAsaba/tensorflow/releases) shared by community supports the custom ops like Landmarks2TransformMatrix. Thank you!

**Comment by adityasihag1804** [comment]
@kuaashish Any guide on how to install that specific version of tf.
I tried this -> `pip install -U git+https://github.com/KenjiAsaba/tensorflow.git@Mediapipe_v0.8.9`
But got the following error,
```
Collecting git+https://github.com/KenjiAsaba/tensorflow.git@Mediapipe_v0.8.9
  Cloning https://github.com/KenjiAsaba/tensorflow.git (to revision Mediapipe_v0.8.9) to /tmp/pip-req-build-fj3dn50w
  Running command git clone --filter=blob:none --quiet https://github.com/KenjiAsaba/tensorflow.git /tmp/pip-req-build-fj3dn50w
  Running command git checkout -b Mediapipe_v0.8.9 --track origin/Mediapipe_v0.8.9
  Switched to a new branch 'Mediapipe_v0.8.9'
  Branch 'Mediapipe_v0.8.9' set up to track remote branch 'Mediapipe_v0.8.9' from 'origin'.
  Resolved https://github.com/KenjiAsaba/tensorflow.git to commit 35845189a59e5e815516106abb76f41fc85e93fd
ERROR: git+https://github.com/KenjiAsaba/tensorflow.git@Mediapipe_v0.8.9 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by adityasihag1804** [comment]
> Hi @adityasihag1804, Landmarks2TransformMatrix is a special TFLite ops that has not been implemented in the latest release of TF version. You can try with [Tensorflow Source Code](https://github.com/KenjiAsaba/tensorflow/releases) shared by community supports the custom ops like Landmarks2TransformMatrix. Thank you!

@kuaashish  Any guide on how to install that specific version of tf.
I tried this -> pip install -U git+https://github.com/KenjiAsaba/tensorflow.git@Mediapipe_v0.8.9
But got the following error,
```
Collecting git+https://github.com/KenjiAsaba/tensorflow.git@Mediapipe_v0.8.9
  Cloning https://github.com/KenjiAsaba/tensorflow.git (to revision Mediapipe_v0.8.9) to /tmp/pip-req-build-fj3dn50w
  Running command git clone --filter=blob:none --quiet https://github.com/KenjiAsaba/tensorflow.git /tmp/pip-req-build-fj3dn50w
  Running command git checkout -b Mediapipe_v0.8.9 --track origin/Mediapipe_v0.8.9
  Switched to a new branch 'Mediapipe_v0.8.9'
  Branch 'Mediapipe_v0.8.9' set up to track remote branch 'Mediapipe_v0.8.9' from 'origin'.
  Resolved https://github.com/KenjiAsaba/tensorflow.git to commit 35845189a59e5e815516106abb76f41fc85e93fd
ERROR: git+https://github.com/KenjiAsaba/tensorflow.git@Mediapipe_v0.8.9 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by BastinFlorian** [comment]
Hey @adityasihag1804, did you solve tour issue ? I have the same problem.
