### ISSUE TITLE
Pose 3D landmarks to Three.js

### ISSUE THREAD

**Issue by ireneb612** [google/mediapipe#3499]
Hi I have estracted the 3D landmarks from videos and now i would like to make the coordinates:
(Example of Left shoulder vector:

 731.13856212,    #x
 285.72247771,   #y
 -0.05692306,     #z   )

work in the Three.js coordinate space! Can anyone help me?

**Comment by sureshdagooglecom** [comment]
Hiu @ireneb612 ,
Below is the code snippet for co ordinates ,please check and revert back.
lf_sh = pose_landmarks["left_shoulder"]
lf_wr = pose_landmarks["left_wrist"]

orient = look_at(np.array([lf_sh["x"], lf_sh["y"], lf_sh["z"]]), 
    np.array([lf_wr["x"], lf_wr["y"], lf_wr["z"]]))

print(np.rad2deg(orien

**Comment by sachinksachu** [comment]
Hi @ireneb612 , did you able to convert the 3d pose landmarks to Three JS coordinate space?
