### ISSUE TITLE
multi-hand tracking destop 

### ISSUE THREAD

**Issue by QingyueMeng** [google/mediapipe#350]
Can I run the multi-hand tracking desktop application in Mac OS?

**Comment by jiuqiant** [comment]
The multi-hand tracking cpu demo supports macOS. You can follow [the instruction](https://mediapipe.readthedocs.io/en/latest/multi_hand_tracking_desktop.html#tensorflow-lite-multi-hand-tracking-demo-with-webcam-cpu) to run it on macOS. The gpu version is currently Linux only and we we are in progress of making it work on macOS.
