### ISSUE TITLE
Lock/limit the angle at which body joints are detected (pose)

### ISSUE THREAD

**Issue by abedicodes** [google/mediapipe#3500]
How can the (camera) angle be limited in the body-joints detection of the MediaPipe pose? I am experiencing random horizontal flips in the body joints (between the front angle and the back angle). Because the faces in my video dataset are blurred, MediaPipe has difficulty detecting the angle of the body joints and alternates between front and back angles. Can I restrict MediaPipe to only detect body joints from the front angle?

**Comment by sureshdagooglecom** [comment]
Hi @abedicodes ,
We have similare issue https://github.com/google/mediapipe/issues/2999 , please check this issue for angle calculations.
