### ISSUE TITLE
In face_mesh JS: `Uncaught (in promise) RuntimeError: Aborted(LinkError: import object field 'invoke_viid' is not a Function)`

### ISSUE THREAD

**Issue by ndrewtl** [google/mediapipe#3501]
**System information** (Please provide as much relevant information as possible)
- Copypasted in [JS face_mesh demo](https://google.github.io/mediapipe/solutions/face_mesh#javascript-solution-api) . Code is [this.](https://gist.github.com/ndrewtl/f30acda2e4c93f92f7ed77fd405ea50d) 
- Platform: WSL / Arch Linux
- Solution: FaceMesh
- Programming Language and version ( e.g. C++, Python, Java): JS

**Describe the expected behavior:**
Demo works as expected. Demo file as I ran it is [here.](https://gist.github.com/ndrewtl/f30acda2e4c93f92f7ed77fd405ea50d) 

**Other info / Complete Logs:**

Full error message:
```js
Uncaught (in promise) RuntimeError: Aborted(LinkError: import object field 'invoke_viid' is not a Function)
    abort https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_simd_wasm_bin.js:9
    createMediapipeSolutionsWasm https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_simd_wasm_bin.js:9
face_mesh_solution_simd_wasm_bin.js:9:25559
```

**Comment by ndrewtl** [comment]
I got this running the basic `face_mesh` demo. But I realized that this was only happening in Firefox, which is not supported. Chrome works. Are there any plans to make this API available for Firefox?

**Comment by kuaashish** [comment]
Hello @ndrewtl,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
