### ISSUE TITLE
FaceMesh failing for INTERNAL: RET_CHECK failure options_.has_num_classes() 

### ISSUE THREAD

**Issue by alantly** [google/mediapipe#3504]
**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): macOS 12.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not checked
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Chrome Version 103.0.5060.114 (Official Build) (arm64)
- Programming Language and version ( e.g. C++, Python, Java): Javascript
- [MediaPipe version](https://github.com/google/mediapipe/releases): face_mesh@0.4.1657299874
- Bazel version (if compiling from source): N/A
- Solution ( e.g. FaceMesh, Pose, Holistic ): FaceMesh
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): N/A
- Xcode & Tulsi version (if issue is related to building for iOS): N/A

**Describe the current behavior:**
FaceMesh consistently failing on loading due to
```
1 tensors_to_detections_calculator.cc:650] INTERNAL: RET_CHECK failure (third_party/mediapipe/calculators/tensor/tensors_to_detections_calculator.cc:650) options_.has_num_classes() 
```

**Describe the expected behavior:**
Expected FaceMesh to not crash.

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:

Can be reproduced by exactly copying the [JS FaceMesh example](https://google.github.io/mediapipe/solutions/face_mesh#javascript-solution-api) or running the [FaceMesh web demo](https://codepen.io/mediapipe/details/KKgVaPJ).

The issue is only seen in `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1657299874/`. The error is not seen when using a previous version `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619/`.
 

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

chrome console logs
[-1657441507664.log](https://github.com/google/mediapipe/files/9078713/-1657441507664.log)

**Comment by getnamo** [comment]
related: https://github.com/google/mediapipe/issues/3506

**Comment by sureshdagooglecom** [comment]
Hi @alantly ,
Rolling back to [0.4.1633559619](https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619/) appears to fix it

change your script include from
https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4/face_mesh.js to
https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619/face_mesh.js until fix is made.

Looks like the 0.4.1657299874 release broke it.

**Comment by alantly** [comment]
Thanks for the response. I have been using 0.4.1633559619` already and it works.

**Comment by tyrmullen** [comment]
Yes-- that was a broken release; it has been already deprecated, but jsdelivr does not always point to the correct version yet.  For now, either explicitly targeting the old version (as you have done) or just targeting no-version (/@mediapipe/face_mesh/face_mesh.js) should work around the problem.

Also, while the release has been deprecated for all Solutions, I believe the breakages associated with this error are in face_mesh and face_detection alone.
