### ISSUE TITLE
visibility and presence always be 0.

### ISSUE THREAD

**Issue by endink** [google/mediapipe#3505]
visibility and presence fields in a NormalizedLandmark for the Holistic Solution always be 0. Is this  unsupported right now?

**Comment by kuaashish** [comment]
Hi @endink, Could you please elaborate your query with complete details. Thank you!

**Comment by endink** [comment]
<img width="581" alt="1657682595030" src="https://user-images.githubusercontent.com/240164/178643914-72fd631a-561e-4038-b405-41dc4c46cdb9.png">

Sorry, visibility and presence the fields is in MediapipeUnityPlugin project. 

Simply, if the the score or visibility of the hand landmark in this Holistic scene available now ? ( like the pose landmarks). 

BTW, please forgive me for my English grammar errors.

**Comment by jimb2834** [comment]
@endink - We opened the same issue but never got a reply on the reason why it never detects anything other than 0, nor that it was a defect

**Comment by endink** [comment]
@jimb2834 we can only wait for a reply...

**Comment by ajmakoni** [comment]
@kuaashish is there any update on this issue? This issue is affecting other validations such visibility and presence of various points of interest as it is always 0 hence wrong results. One example is palm validation, checks for palm validation and visibility on an image with only points 8,12,16,20,7,11,15,19, mediapipe is returning other points not available on the image hence wrong results

**Comment by jimb2834** [comment]
@elYeodeol - there are old issues related to Visibility and Presence of landmarks re: face mesh specifically from a while back - 
https://github.com/google/mediapipe/issues/3200
https://github.com/google/mediapipe/issues/3159

But anytime someone solves it, ping me and we are happy to pay for the solution.

**Comment by ajmakoni** [comment]
> @elYeodeol - there are old issues related to Visibility and Presence of landmarks re: face mesh specifically from a while back - #3200 #3159
> 
> But anytime someone solves it, ping me and we are happy to pay for the solution.

Hi jimb2834, have you looked at Google mlkit library for face landmarks? https://developers.google.com/ml-kit my experience has been impressive.

**Comment by jimb2834** [comment]
@ajmakoni - Hi, thanks for the message. The main issue was landmark quantity; whether it reflects "visibility" or "presence" I did not check. So the landmark Qty, Visibility, and Presence values were all needed.  GCP ML kit for face has a lower landmark qty.

**Comment by ajmakoni** [comment]
> @ajmakoni - Hi, thanks for the message. The main issue was landmark quantity; whether it reflects "visibility" or "presence" I did not check. So the landmark Qty, Visibility, and Presence values were all needed for our use case. GCP ML kit for face has a lower landmark qty.

Okay, I get your point

**Comment by endink** [comment]
Is there any good news for this? Nobody care it?

**Comment by jimb2834** [comment]
@endink - I was in the MediaPipe slack channel and saw this

![image](https://user-images.githubusercontent.com/53540864/188140308-599fe87f-3f48-4c10-a834-9b3a6acbb903.png)

**Comment by endink** [comment]
@jimb2834 it only worked for pose landmarks, but not in handlandmarks.

**Comment by kuaashish** [comment]
Hello @endink,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by guunnz** [comment]
Mediapipe unity plugin stills gives always 0 for visibility and presence for normalizedlandmarks in handtracking

**Comment by yiyiyaya1122** [comment]
Mediapipe unity plugin stills gives always 0 for visibility and presence for normalizedlandmarks in handtracking
