### ISSUE TITLE
RuntimeError: Aborted(native code called abort()) -- Unable to run Face Detection and Face Mesh CodePen Examples (jsDelivr CDN)

### ISSUE THREAD

**Issue by matthewwiese** [google/mediapipe#3506]
**System information**

- Have I written custom code: No, I am attempting to run the official CodePen examples.
- OS Platform and Distribution: Windows 10 and Ubuntu 20.04
- Mobile device: Probably? Haven't tested.
- Browser and version: Chrome 103 (Windows) and Firefox 102 (Ubuntu)
- Programming Language and version: JavaScript/Browser
- MediaPipe version: 0.4, this loader is causing issues: https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.4/face_detection_solution_simd_wasm_bin.js
- Bazel version: N/A
- Solution: Face Detection, Face Mesh
- Android Studio, NDK, SDK versions: N/A
- Xcode & Tulsi version: N/A

**Describe the current behavior:**

The Face Detection and Face Mesh WASM bundle fails to load. The following error is logged to the browser console:
```
Uncaught (in promise) RuntimeError: Aborted(native code called abort())
```

**Describe the expected behavior:**

The CodePen examples for Face Detection and Face Mesh should work. [Holistic](https://codepen.io/mediapipe/pen/LYRRYEw) appears unaffected.

**Standalone code to reproduce the issue:**
* [Face Detection CodePen Example](https://codepen.io/mediapipe/pen/dyOzvZM)
* [Face Mesh CodePen Example](https://codepen.io/mediapipe/pen/KKgVaPJ)

**Other info / Complete Logs :**
Full error message I am encountering:
```
Uncaught (in promise) RuntimeError: Aborted(native code called abort())
    at abort (face_detection_solution_simd_wasm_bin.js:9:25559)
    at _abort (face_detection_solution_simd_wasm_bin.js:9:158659)
    at face_detection_solution_simd_wasm_bin.wasm:0x49fef3
    at face_detection_solution_simd_wasm_bin.wasm:0x49fd49
    at face_detection_solution_simd_wasm_bin.wasm:0x49ff3c
    at face_detection_solution_simd_wasm_bin.wasm:0x16fd1
    at face_detection_solution_simd_wasm_bin.wasm:0x11773
    at SolutionWasm.SolutionWasm$send [as send] (eval at new_ (face_detection_solution_simd_wasm_bin.js:9:135234), <anonymous>:9:1)
    at pa.h (face_detection.js:81:19)
    at H (face_detection.js:14:296)
```

**Comment by getnamo** [comment]
rolling back to [0.4.1633559619](https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619/) appears to fix it

change your script include from 
`https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4/face_mesh.js` to
`https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619/face_mesh.js` until fix is made.

Looks like the `0.4.1657299874` release broke it.

**Comment by kuaashish** [comment]
Hi @matthewwiese, I could successfully reproduced the CodePen examples(**Face Detection** and **Face Mesh**) on the above mentioned devices with particular browser with no errors. Could you provide the steps to reproduce the code and explain more about the issue. Thank you!

**Comment by matthewwiese** [comment]
> rolling back to [0.4.1633559619](https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619/) appears to fix it
> 
> change your script include from `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4/face_mesh.js` to `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619/face_mesh.js` until fix is made.
> 
> Looks like the `0.4.1657299874` release broke it.

This must've been it! Thanks for the assistance with sleuthing @getnamo 

> Hi @matthewwiese, I could successfully reproduced the CodePen examples(**Face Detection** and **Face Mesh**) on the above mentioned devices with particular browser with no errors. Could you provide the steps to reproduce the code and explain more about the issue. Thank you!

Hi @kuaashish it appears that whichever build was causing the error has now been "pushed" out by a more recent build taking the place of `@mediapipe/face_detection@0.4`.

It appears that @getnamo's suggestion may have been the problem? I haven't tested Face Mesh locally, but a boilerplate Face Detection example based off the CodePen now works with `@0.4`.

I'll leave this issue open in case the team wants to explore further.

**Comment by tyrmullen** [comment]
Correct, the `0.4.1657299874` release had breakages and was deprecated.  Face Mesh and Face Detection in particular both had this issue.  JsDelivr can take some time to invalidate its caching, and as of yesterday, it was pointing `face_mesh/` and `face_detection/` to the good version, while it was pointing `face_mesh@0.4/` and `face_detection@0.4/` to the bad version.  So those two CodePens have been temporarily changed to remove the `@0.4`, but hopefully that will not be necessary in the future.
