### ISSUE TITLE
Make android solutions(face detection) buildable with 'minifyEnabled true' build option.

### ISSUE THREAD

**Issue by francescogatto** [google/mediapipe#3509]
System information (Please provide as much relevant information as possible)

MediaPipe Solution (you are using): Face detection
Programming language : Android Java
Are you willing to contribute it (Yes/No): Yes (if I can)
Describe the feature and the current behavior/state:
I followed Mediapipe Android Solutions tutorial to build facedetection app and ran it on my device. It worked perfectly. However, when I changed minifyEnabled configuration to true in build.gradle file, the app crashed. I tried to use the proguard rule in my app suggested in another [issue](https://github.com/google/mediapipe/issues/3236): 

`-keepclassmembers class * extends com.google.protobuf.GeneratedMessageLite { <fields>; }
`

but not works. 
I use the last mediapipe gradle version (8.10.0)
Will this change the current api? How?
Yes.

Who will benefit with this feature?
Anyone who wants to shrink their app.

Please specify the use cases for this feature:
The solutions apps will be shrinkable.

Error log from android studio:
```
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.RuntimeException: Field platform_ for x9.o not found. Known fields are [private int x9.o.p, private int x9.o.q, private java.lang.String x9.o.r, private java.lang.String x9.o.s, private java.lang.String x9.o.t, private static final x9.o x9.o.u, private static volatile com.google.protobuf.p1 x9.o.v]
    java.lang.RuntimeException: Field platform_ for x9.o not found. Known fields are [private int x9.o.p, private int x9.o.q, private java.lang.String x9.o.r, private java.lang.String x9.o.s, private java.lang.String x9.o.t, private static final x9.o x9.o.u, private static volatile com.google.protobuf.p1 x9.o.v]
        at com.google.protobuf.h1.e0(:7)
        at com.google.protobuf.h1.O(:52)
        at com.google.protobuf.h1.M(:2)
        at com.google.protobuf.r0.e(:8)
        at com.google.protobuf.r0.a(:13)
        at com.google.protobuf.s1.c(:3)
        at com.google.protobuf.s1.d(:1)
        at com.google.protobuf.g0.v(:1)
        at com.google.protobuf.g0$a.k(:3)
        at com.google.protobuf.g0$a.i(:1)
        at z9.f.<init>(:24)
        at y9.i.e(:3)
        at y9.c.e(:2)
        at aa.d.<init>(:11)
        at ui.video.facedetection.FaceDetector.u(:9)
```

**Comment by sureshdagooglecom** [comment]
Hi @francescogatto ,
Adding the following lines in proguard-rules.pro prevented the release build crash:

-keep class com.google.mediapipe.solutioncore.** {*;}
-keep class com.google.protobuf.** {*;}
-keepclassmembers class * extends com.google.protobuf.GeneratedMessageLite {
  <fields>;
}

**Comment by francescogatto** [comment]
i tried, but is not working
