### ISSUE TITLE
How to convert the result of Mediapipe into .OBJ format for our own face that we want to do texture mapping?

### ISSUE THREAD

**Issue by della0418** [google/mediapipe#3511]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):windows10
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):python3.9
- Installed using virtualenv? pip? Conda? (if python):conda

**Describe the problem**:
We want to convert the result of Mediapipe into .OBJ format for our own face that we want to do texture mapping , but there are some problems : We don't know how to get complete .OBJ format with our data that got from Mediapipe. We only can get the coordinate of  the Mediapipe's landmarks , which are v in .OBJ.
We have done to make our face mesh , but we hope to let 2D facial picture paste to 3D face mesh. We don't know how to get vn , vt ,and f in .OBJ format . We need to know the rules of them. 
Our main reason is letting the code run uv mapping with any useful programming language.
We have used Blender to manually facial mapping ,and  output the .OBJ that tried to get the rules of vn, vt, and f.

**Comment by andrechen** [comment]
It's easy to start from here...
https://github.com/google/mediapipe/blob/63e679d99ca45b30514a9d84c9351a2d77bb9ba0/mediapipe/modules/face_geometry/data/canonical_face_model.obj

You'll need to modify vt from normalized landmarks xy, deduce metric 3d coordinates (face_geometry module) to get then use simple math to calculate normal vectors, vn from v (average from shared triangles to get more appealing results), last, add vn indices to f. 

https://www.cs.cmu.edu/~mbz/personal/graphics/obj.html

**Comment by sureshdagooglecom** [comment]
Hi @della0418 ,
we do support OBJ topology format via converting into [mediapipe.face_geometry.Mesh3d](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/mesh_3d.proto) via the [non-official converter](https://gist.github.com/kostyaby/bc3b931e23a46422294b7dcc1fdb7990);

**Comment by della0418** [comment]
@andrechen How can I get the coordinates of the points which on my texture(vt)? I only know they would be in 0 to 1

**Comment by andrechen** [comment]
check #3512 for [answer with C++ source code](https://github.com/andrechen/mediapipe/blob/dfa428288e6a39a2ecd37167a00818ea19ec5e1b/visualstudio/face_effect/face_effect_renderer.cc#L554)

**Comment by sureshdagooglecom** [comment]
Hi @della0418 ,
Please check this solution from community https://github.com/google/mediapipe/issues/3512#issuecomment-1186422810 and revert back.
