### ISSUE TITLE
How to convert the result of Mediapipe into .OBJ format for our own face that we want to do texture mapping?

### ISSUE THREAD

**Issue by della0418** [google/mediapipe#3512]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):windows10
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):python3.9
- Installed using virtualenv? pip? Conda? (if python):conda

**Describe the problem**:
We want to convert the result of Mediapipe into .OBJ format for our own face that we want to do texture mapping , but there are some problems : We don't know how to get complete .OBJ format with our data that got from Mediapipe. We only can get the coordinate of  the Mediapipe's landmarks , which are v in .OBJ.
We have done to make our face mesh , but we hope to let 2D facial picture paste to 3D face mesh. We don't know how to get vn , vt ,and f in .OBJ format . We need to know the rules of them. 
Our main reason is letting the code run uv mapping with any useful programming language.
We have used Blender to manually facial mapping ,and  output the .OBJ that tried to get the rules of vn, vt, and f.

**Comment by sureshdagooglecom** [comment]
Hi @della0418 ,
we do support OBJ topology format via converting into [mediapipe.face_geometry.Mesh3d](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/mesh_3d.proto) via the [non-official converter](https://gist.github.com/kostyaby/bc3b931e23a46422294b7dcc1fdb7990);

**Comment by andrechen** [comment]
the [non-official converter](https://gist.github.com/kostyaby/bc3b931e23a46422294b7dcc1fdb7990) converts .obj to [mediapipe.face_geometry.Mesh3d](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/mesh_3d.proto). It does not 'convert the result of Mediapipe into .OBJ format'. Or do we miss something?

Enough talks!
I have done exporting simple .obj files [here](https://github.com/andrechen/mediapipe/blob/dfa428288e6a39a2ecd37167a00818ea19ec5e1b/visualstudio/face_effect/face_effect_renderer.cc#L554) (no '**vn**', though). Run [face_effect](https://github.com/andrechen/mediapipe/tree/master/visualstudio/face_effect) example, press 'o' to export .obj at anytime...

![blender_wireframe](https://user-images.githubusercontent.com/2261137/179387403-d87e410e-ef7a-4e8b-8895-ee97bfd8be87.jpg)
![blender_texturemap](https://user-images.githubusercontent.com/2261137/179387413-532c1b5b-d98e-40ad-a797-783a8a79a92d.jpg)

**Comment by sureshdagooglecom** [comment]
Hi @della0418 ,
Still do you have any issue w.r.t above issue.
