### ISSUE TITLE
library "libmediapipe_jni.so" not found

### ISSUE THREAD

**Issue by nfadeluca** [google/mediapipe#3513]
**System information:**
- Have I written custom code?: No
- OS Platform and Distribution: Linux Ubuntu 22.04
- MediaPipe version: v0.8.10.2
- Bazel version: 5.2
- Solution: Hands
- Programming Language and version: JDK 18.0.1
- Emulator: Pixel 4a, API 30, R Android 11.0 x86_64 (Android Studio Virtual Device)

**Expected behavior:**
On running solution in Android Studio emulator, once start camera is pressed, webcam view should be presented and hand detection should work as displayed in Mediapipe examples.

However, once start camera is pressed, webcam activates yet screen of the application remains black or the application crashes.

**Reproducing Error:**
I reproduced the error on another device using:
- Ubuntu 21.10
- Mediapipe v0.8.10.2
- Bazel v5.2
- JDK v.11.0.2
- Emulator: Pixel XL, API 30, R Android 11.0 x86_64 (Android Studio Virtual Device)

Followed all instruction to install as listed in: 
https://google.github.io/mediapipe/getting_started/install.html
Installed SDK & NDK through Android Studio's SDK Manager, using:
Android SDK 33.0.0 & 30.0.3
NDK 21.4.7075529

However due to an error that occurred on both devices I had to copy dx.jar from Android/Sdk/build-tools/30.0.3/lib into Android/Sdk/build-tools/33.0.0/lib which allowed me to move forward in the installation process without errors.

I built and ran the Hands Solution following the Mediapipe guide under the 'Building Solution Example' Apps section at:
https://google.github.io/mediapipe/getting_started/android_solutions.html

**Just to Re-iterate:**
I run the MainActivity of the solution through android studio after importing it as a new project, and following the steps listed on the Mediapipe guide, the app loads up with three option, I press the start camera option, and then the screen either goes black with the webcam turned on, or the app crashes. After this, the Run terminal contains the error below:

**Other info / Complete Logs :**
The following error appears in Android Studio's run terminal after the black screen occurs
![image](https://user-images.githubusercontent.com/71537945/178579267-8fad2111-1b8f-4a9c-9f1b-8439f394e93f.png)

**Comment by sureshdagooglecom** [comment]
Hi @nfadeluca ,
The error seems to beUnexpected CPU variant for X86 using defaults: x86_64.
The AAR you downloaded only supports armeabi and arm64. It doesn't have x86_64 support (mostly for emulators).

**Comment by sureshdagooglecom** [comment]
Hi @nfadeluca ,
Could you please provide steps to reproduce this issue.

**Comment by nfadeluca** [comment]
@sureshdagooglecom Hi Suresh, I have already wrote the steps down in the **Reproducing the Error** section of my post above.

**Comment by sureshdagooglecom** [comment]
Hi @nfadeluca .
Yes, it is to do with android studio and please check this closed issue https://github.com/google/mediapipe/issues/2979.
