### ISSUE TITLE
bazel run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \     mediapipe/examples/desktop/hello_world:hello_world

### ISSUE THREAD

**Issue by Fanthers** [google/mediapipe#3515]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):ubuntu16.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):gcc 7.5
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):python3.7
- Installed using virtualenv? pip? Conda? (if python):conda
- [MediaPipe version](https://github.com/google/mediapipe/releases):5.2.0
- Bazel version:5.2.0
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:
Error when executing header:
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build Use --verbose_failures to see the command lines of failed build steps

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

(mediapipe) fyq@fyq-matrix-01:~/ycy/mediapipe$ bazel run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11     mediapipe/examples/desktop/hello_world:hello_world
DEBUG: /home/fyq/.cache/bazel/_bazel_fyq/d460e7fe5a8123432ba511bff9da1bcf/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/fyq/.cache/bazel/_bazel_fyq/d460e7fe5a8123432ba511bff9da1bcf/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /home/fyq/.cache/bazel/_bazel_fyq/d460e7fe5a8123432ba511bff9da1bcf/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/fyq/.cache/bazel/_bazel_fyq/d460e7fe5a8123432ba511bff9da1bcf/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/fyq/.cache/bazel/_bazel_fyq/d460e7fe5a8123432ba511bff9da1bcf/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/fyq/.cache/bazel/_bazel_fyq/d460e7fe5a8123432ba511bff9da1bcf/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/fyq/.cache/bazel/_bazel_fyq/d460e7fe5a8123432ba511bff9da1bcf/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/fyq/.cache/bazel/_bazel_fyq/d460e7fe5a8123432ba511bff9da1bcf/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/fyq/.cache/bazel/_bazel_fyq/d460e7fe5a8123432ba511bff9da1bcf/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/fyq/.cache/bazel/_bazel_fyq/d460e7fe5a8123432ba511bff9da1bcf/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /home/fyq/.cache/bazel/_bazel_fyq/d460e7fe5a8123432ba511bff9da1bcf/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
WARNING: /home/fyq/ycy/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /home/fyq/ycy/mediapipe/mediapipe/framework/tool/BUILD:184:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/fyq/ycy/mediapipe/mediapipe/gpu/BUILD:212:11: Compiling mediapipe/gpu/gl_texture_buffer.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 51 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from ./mediapipe/gpu/gl_texture_view.h:23:0,
                 from ./mediapipe/gpu/gl_texture_buffer.h:27,
                 from mediapipe/gpu/gl_texture_buffer.cc:15:
./mediapipe/gpu/gpu_buffer_storage.h: In instantiation of 'mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&)::<lambda(std::shared_ptr<mediapipe::internal::GpuBufferStorage>)> [with StorageFrom = mediapipe::GlTextureBuffer; StorageTo = mediapipe::GpuBufferStorageImageFrame; F = std::shared_ptr<mediapipe::GpuBufferStorageImageFrame> (&)(std::shared_ptr<mediapipe::GlTextureBuffer>)]':
./mediapipe/gpu/gpu_buffer_storage.h:89:10:   required from 'struct mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GlTextureBuffer; StorageTo = mediapipe::GpuBufferStorageImageFrame; F = std::shared_ptr<mediapipe::GpuBufferStorageImageFrame> (&)(std::shared_ptr<mediapipe::GlTextureBuffer>)]::<lambda(class std::shared_ptr<mediapipe::internal::GpuBufferStorage>)>'
./mediapipe/gpu/gpu_buffer_storage.h:93:60:   required from 'mediapipe::internal::GpuBufferStorageRegistry::RegistryToken mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GlTextureBuffer; StorageTo = mediapipe::GpuBufferStorageImageFrame; F = std::shared_ptr<mediapipe::GpuBufferStorageImageFrame> (&)(std::shared_ptr<mediapipe::GlTextureBuffer>)]'
mediapipe/gpu/gl_texture_buffer.cc:355:32:   required from here
./mediapipe/gpu/gpu_buffer_storage.h:90:50: error: variable 'converter' has function type
             -> std::shared_ptr<GpuBufferStorage> {
                                                  ^
./mediapipe/gpu/gpu_buffer_storage.h:90:50: error: variable 'converter' has function type
./mediapipe/gpu/gpu_buffer_storage.h: In instantiation of 'struct mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GlTextureBuffer; StorageTo = mediapipe::GpuBufferStorageImageFrame; F = std::shared_ptr<mediapipe::GpuBufferStorageImageFrame> (&)(std::shared_ptr<mediapipe::GlTextureBuffer>)]::<lambda(class std::shared_ptr<mediapipe::internal::GpuBufferStorage>)>':
./mediapipe/gpu/gpu_buffer_storage.h:93:60:   required from 'mediapipe::internal::GpuBufferStorageRegistry::RegistryToken mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GlTextureBuffer; StorageTo = mediapipe::GpuBufferStorageImageFrame; F = std::shared_ptr<mediapipe::GpuBufferStorageImageFrame> (&)(std::shared_ptr<mediapipe::GlTextureBuffer>)]'
mediapipe/gpu/gl_texture_buffer.cc:355:32:   required from here
./mediapipe/gpu/gpu_buffer_storage.h:89:10: error: field 'mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GlTextureBuffer; StorageTo = mediapipe::GpuBufferStorageImageFrame; F = std::shared_ptr<mediapipe::GpuBufferStorageImageFrame> (&)(std::shared_ptr<mediapipe::GlTextureBuffer>)]::<lambda(std::shared_ptr<mediapipe::internal::GpuBufferStorage>)>::<converter capture>' invalidly declared function type
         [converter](std::shared_ptr<GpuBufferStorage> source)
          ^~~~~~~~~
./mediapipe/gpu/gpu_buffer_storage.h: In instantiation of 'mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&)::<lambda(std::shared_ptr<mediapipe::internal::GpuBufferStorage>)> [with StorageFrom = mediapipe::GpuBufferStorageImageFrame; StorageTo = mediapipe::GlTextureBuffer; F = std::shared_ptr<mediapipe::GlTextureBuffer> (&)(std::shared_ptr<mediapipe::GpuBufferStorageImageFrame>)]':
./mediapipe/gpu/gpu_buffer_storage.h:89:10:   required from 'struct mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GpuBufferStorageImageFrame; StorageTo = mediapipe::GlTextureBuffer; F = std::shared_ptr<mediapipe::GlTextureBuffer> (&)(std::shared_ptr<mediapipe::GpuBufferStorageImageFrame>)]::<lambda(class std::shared_ptr<mediapipe::internal::GpuBufferStorage>)>'
./mediapipe/gpu/gpu_buffer_storage.h:93:60:   required from 'mediapipe::internal::GpuBufferStorageRegistry::RegistryToken mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GpuBufferStorageImageFrame; StorageTo = mediapipe::GlTextureBuffer; F = std::shared_ptr<mediapipe::GlTextureBuffer> (&)(std::shared_ptr<mediapipe::GpuBufferStorageImageFrame>)]'
mediapipe/gpu/gl_texture_buffer.cc:359:34:   required from here
./mediapipe/gpu/gpu_buffer_storage.h:90:50: error: variable 'converter' has function type
             -> std::shared_ptr<GpuBufferStorage> {
                                                  ^
./mediapipe/gpu/gpu_buffer_storage.h:90:50: error: variable 'converter' has function type
./mediapipe/gpu/gpu_buffer_storage.h: In instantiation of 'struct mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GpuBufferStorageImageFrame; StorageTo = mediapipe::GlTextureBuffer; F = std::shared_ptr<mediapipe::GlTextureBuffer> (&)(std::shared_ptr<mediapipe::GpuBufferStorageImageFrame>)]::<lambda(class std::shared_ptr<mediapipe::internal::GpuBufferStorage>)>':
./mediapipe/gpu/gpu_buffer_storage.h:93:60:   required from 'mediapipe::internal::GpuBufferStorageRegistry::RegistryToken mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GpuBufferStorageImageFrame; StorageTo = mediapipe::GlTextureBuffer; F = std::shared_ptr<mediapipe::GlTextureBuffer> (&)(std::shared_ptr<mediapipe::GpuBufferStorageImageFrame>)]'
mediapipe/gpu/gl_texture_buffer.cc:359:34:   required from here
./mediapipe/gpu/gpu_buffer_storage.h:89:10: error: field 'mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GpuBufferStorageImageFrame; StorageTo = mediapipe::GlTextureBuffer; F = std::shared_ptr<mediapipe::GlTextureBuffer> (&)(std::shared_ptr<mediapipe::GpuBufferStorageImageFrame>)]::<lambda(std::shared_ptr<mediapipe::internal::GpuBufferStorage>)>::<converter capture>' invalidly declared function type
         [converter](std::shared_ptr<GpuBufferStorage> source)
          ^~~~~~~~~
In file included from /usr/include/c++/7/functional:58:0,
                 from external/com_google_absl/absl/meta/type_traits.h:39,
                 from external/com_google_absl/absl/memory/memory.h:34,
                 from ./mediapipe/gpu/gl_texture_buffer.h:23,
                 from mediapipe/gpu/gl_texture_buffer.cc:15:
/usr/include/c++/7/bits/std_function.h:685:7: error: 'std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GlTextureBuffer; StorageTo = mediapipe::GpuBufferStorageImageFrame; F = std::shared_ptr<mediapipe::GpuBufferStorageImageFrame> (&)(std::shared_ptr<mediapipe::GlTextureBuffer>)]::<lambda(std::shared_ptr<mediapipe::internal::GpuBufferStorage>)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = std::shared_ptr<mediapipe::internal::GpuBufferStorage>; _ArgTypes = {std::shared_ptr<mediapipe::internal::GpuBufferStorage>}]', declared using local type 'mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GlTextureBuffer; StorageTo = mediapipe::GpuBufferStorageImageFrame; F = std::shared_ptr<mediapipe::GpuBufferStorageImageFrame> (&)(std::shared_ptr<mediapipe::GlTextureBuffer>)]::<lambda(std::shared_ptr<mediapipe::internal::GpuBufferStorage>)>', is used but never defined [-fpermissive]
       function<_Res(_ArgTypes...)>::
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/7/bits/std_function.h:685:7: error: 'std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GpuBufferStorageImageFrame; StorageTo = mediapipe::GlTextureBuffer; F = std::shared_ptr<mediapipe::GlTextureBuffer> (&)(std::shared_ptr<mediapipe::GpuBufferStorageImageFrame>)]::<lambda(std::shared_ptr<mediapipe::internal::GpuBufferStorage>)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = std::shared_ptr<mediapipe::internal::GpuBufferStorage>; _ArgTypes = {std::shared_ptr<mediapipe::internal::GpuBufferStorage>}]', declared using local type 'mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GpuBufferStorageImageFrame; StorageTo = mediapipe::GlTextureBuffer; F = std::shared_ptr<mediapipe::GlTextureBuffer> (&)(std::shared_ptr<mediapipe::GpuBufferStorageImageFrame>)]::<lambda(std::shared_ptr<mediapipe::internal::GpuBufferStorage>)>', is used but never defined [-fpermissive]
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.821s, Critical Path: 4.68s
INFO: 124 processes: 119 internal, 5 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by kuaashish** [comment]
Hi @Fanthers, Could you please elaborate your query with complete details and standalone code to reproduce the issue. Thank you!

**Comment by Fanthers** [comment]
1. System information 

OS Platform and Distribution:ubuntu16.04
Compiler version :gcc 7.5
Programming Language and version:python3.7
conda
MediaPipe version:5.2.0
Bazel version:5.2.0

2. peoblem

**Comment by kuaashish** [comment]
Hi @Fanthers, Have you followed the instructions mentioned in the [documentation](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu) to build the above example. Thank you!

**Comment by SkyDream666** [comment]
Hi @Fanthers, Have you solved this problem finally? I meet the same issue and the System information is same with yours.

**Comment by SkyDream666** [comment]
I meet the same problems and I update my gcc version to gcc9.4.0, then the problem has been solved.  May be that "[converter](std::shared_ptr<GpuBufferStorage> source)......" only supported in higher gcc version. Please refer to
https://gcc.gnu.org/projects/cxx-status.html#cxx17  and https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0512r0.pdf

**Comment by kuaashish** [comment]
Hi @SkyDream666, Thank you very much for the solution. It will be helpful for other community members.
