### ISSUE TITLE
Missing 2 landmarks in between standard and attention FaceMesh model.

### ISSUE THREAD

**Issue by janglinko-dac** [google/mediapipe#3516]
Hello! 
As I understand from documentation, AttentionModule produces 478 landmars face model, adding Irises to the standard one. 
`mp_face_mesh.FACEMESH_NUM_LANDMARKS = 468`
`mp_face_mesh.FACEMESH_NUM_LANDMARKS_WITH_IRISES = 478`
However, `mp_face_mesh.FACEMESH_IRISES=8`.

My  question is what are those two missing landmarks? I have 468 landmarks canonical face model and I want to solve PnP.
I could not find 478 landmarks canonical face model. If You can provide me with such one, it will be great!

Best,
Jan

**Comment by kuaashish** [comment]
Hi @janglinko-dac, Could you please elaborate your query with complete details. Thank you!

**Comment by kuaashish** [comment]
Hello @janglinko-dac,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
