### ISSUE TITLE
Windows10 compiles mediapipe error：

### ISSUE THREAD

**Issue by wz2wd** [google/mediapipe#3517]
D:\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D:\\Anaconda3\\envs\\mmd26\\python.exe" mediapipe/examples/desktop/hello_world
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/a87782c34d667d1c1a18fe82a9a7abfc72fd345b.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: C:/users/asus/_bazel_asus/hr7sucjp/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/hr7sucjp/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/hr7sucjp/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/hr7sucjp/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/hr7sucjp/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/hr7sucjp/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/hr7sucjp/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/hr7sucjp/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/hr7sucjp/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/hr7sucjp/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/asus/_bazel_asus/hr7sucjp/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: Traceback (most recent call last):
        File "C:/users/asus/_bazel_asus/hr7sucjp/external/rules_cc/cc/private/rules_impl/cc_flags_supplier.bzl", line 16, column 76, in <toplevel>
                load("@bazel_tools//tools/cpp:toolchain_utils.bzl", "find_cpp_toolchain", "use_cpp_toolchain")
Error: file '@bazel_tools//tools/cpp:toolchain_utils.bzl' does not contain symbol 'use_cpp_toolchain' (did you mean 'find_cpp_toolchain'?)
ERROR: While resolving toolchains for target //mediapipe/examples/desktop/hello_world:hello_world: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in C:/users/asus/_bazel_asus/hr7sucjp/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in C:/users/asus/_bazel_asus/hr7sucjp/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
INFO: Elapsed time: 0.133s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
HOW do I deal with this? thanks.

**Comment by kuaashish** [comment]
Hi @wz2wd, Could you please elaborate your query with complete details. Thank you!

**Comment by wz2wd** [comment]
These problems  have been solved.thanks.

**Comment by kuaashish** [comment]
Hi @wz2wd, Thank you for the confirmation. Can we move this issue to close status hence the issue has been resolved. 
Thank you!

**Comment by Secondgrade** [comment]
> These problems have been solved.thanks.

Hi there,
It is such a wicked problem, and I am still stuck here. It is good to here that you solve this problem and do you mind share your experience with the community? I would be really apprciate it. Thanks.
