### ISSUE TITLE
World Hand Landmarks in iOS example

### ISSUE THREAD

**Issue by denred0** [google/mediapipe#3518]
Hello!

I successfully launched _https://github.com/google/mediapipe/tree/master/mediapipe/examples/ios/handtrackinggpu_ example and get 3D hand landmarks in local coodrinate system:
https://github.com/google/mediapipe/blob/63e679d99ca45b30514a9d84c9351a2d77bb9ba0/mediapipe/examples/ios/handtrackinggpu/HandTrackingViewController.mm#L49 

Is it possible to obtain world hand landmarks in this iOS example?
Thanks.

**Comment by kuaashish** [comment]
Hi @denred0, Could you please elaborate your query with complete details. Thank you!
