### ISSUE TITLE
What is the rational for padding channels in face_detection_front.tflite model?

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#352]
![Screenshot from 2019-12-27 19-16-36](https://user-images.githubusercontent.com/10518587/71515306-91f72c80-28dd-11ea-84ac-54c32fe05773.png)

I am trying to reimplement the face_detection_front.tflite (modified BlazeFace) in TF so that I can train it. And it seems like you are using weird operations like padding channels. What is the rationale for doing that? It doesn't seem to make sense.

**Comment by fanzhanggoogle** [comment]
This is mostly because we keep the aspect ratio of the input image when training the model.

**Comment by yxchng** [comment]
@fanzhanggoogle huh? If you want to keep the aspect ratio, you pad the height and width, not the channels. Isn’t it?

**Comment by fanzhanggoogle** [comment]
Ah, sorry that I didn't understand your question correctly before. Yes, this is intended in our design. Usually people don't use residual module when the input/output doesn't have the same number of channels, but it actually worked pretty well for our cases. Another idea could be concatenate/slicing the pass through channels to be able to add with the convolution pass.

**Comment by yxchng** [comment]
@fanzhanggoogle It is quite weird that padding with zeros on the channels can work. It is very counter-intuitive.

**Comment by roachsinai** [comment]
@yxchng have you try to convert tflite model to onnx? Which will add an extra split operation like below, and do you know what's the meaning?

![image](https://user-images.githubusercontent.com/9500049/126196534-87e69667-ae26-402f-a474-7e3ca8fdd034.png)

@yxchng @fanzhanggoogle any help will be appreciated!
