### ISSUE TITLE
stuck at "make: Entering directory " when building cross-compile docker environments for coral dev-board

### ISSUE THREAD

**Issue by fjzhangcr** [google/mediapipe#3520]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): ubuntu 20
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): GNU Make 4.2.1 Built for x86_64-pc-linux-gnu

- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases): 
- Bazel version:
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:
i have install docker and make tools on my ubuntu. then i follow the instructure, typing in:
```
indeed@indeed-virtual-machine:~/Desktop/mediapipe-master$ make -C mediapipe/examples/coral PLATFORM=arm64 docker
make: Entering directory '/home/indeed/Desktop/mediapipe-master/mediapipe/examples/coral'
```
then the console stucked~~~
![image](https://user-images.githubusercontent.com/102020341/179075239-a0e040fc-7e5a-4556-99c0-855007ea3f9a.png)

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment]
Hi @fjzhangcr, Could you please follow the steps mentioned [here](https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/README.md) to build the cross-compiled mediapipe in the Coral Dev Board. Thank you!

**Comment by fjzhangcr** [comment]
thank you for you response.
I just strictly follower the instruction. I read two options to compile mediapip:  build by bazel or cross-compile for coral dev-board.
I choose the second option. First, setup the docker env by typing in 
```
# For ARM64 (e.g. Coral Dev Board)
make -C mediapipe/examples/coral PLATFORM=arm64 docker
```
then I stucked~~~

did you mean I have to install bazel tools before cross-compiling? I am confused~~

thanks

**Comment by fjzhangcr** [comment]
thank you, I know bazel is a necessary tool especially the 5.2.0 version
`indeed@indeed-virtual-machine:~/Desktop/mediapipe-master$ ls`
bazel-5.3.1-installer-linux-x86_64.sh  BUILD.bazel                build_ios_examples.sh  Dockerfile  LICENSE      mediapipe  requirements.txt              setup_opencv.sh  third_party
build_android_examples.sh              build_desktop_examples.sh  CONTRIBUTING.md        docs        MANIFEST.in  README.md  setup_android_sdk_and_ndk.sh  setup.py         WORKSPACE

`indeed@indeed-virtual-machine:~/Desktop/mediapipe-master$ bazel version`
Build label: 5.2.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 7 16:02:26 2022 (1654617746)
Build timestamp: 1654617746
Build timestamp as int: 1654617746

I think I have acomplished the software dependency~~
But when I build the mediapipe edgetpu demo, it tell me that **Skipping 'build': no such target '//:build':** 
`indeed@indeed-virtual-machine:~/Desktop/mediapipe-master$ bazel build   --compilation_mode=opt   --define darwinn_portable=1   --define MEDIAPIPE_DISABLE_GPU=1   --define MEDIAPIPE_EDGE_TPU=usb   --linkopt=-l:libusb-1.0.so   mediapipe/examples/coral:face_detection_tpu build`

indeed@indeed-virtual-machine:~/Desktop/mediapipe-master$ bazel build   --compilation_mode=opt   --define darwinn_portable=1   --define MEDIAPIPE_DISABLE_GPU=1   --define MEDIAPIPE_EDGE_TPU=usb   --linkopt=-l:libusb-1.0.so   mediapipe/examples/coral:face_detection_tpu build
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: Skipping 'build': no such target '//:build': target 'build' not declared in package '' defined by /home/indeed/Desktop/mediapipe-master/BUILD.bazel
ERROR: no such target '//:build': target 'build' not declared in package '' defined by /home/indeed/Desktop/mediapipe-master/BUILD.bazel
INFO: Elapsed time: 0.341s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
