### ISSUE TITLE
smooth_landmrks works on pose_world_landmarks as well?

### ISSUE THREAD

**Issue by fchen09** [google/mediapipe#3522]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):IOS
- [MediaPipe version](https://github.com/google/mediapipe/releases):0.8.9
- Bazel version:5.2.0
- Solution (e.g. FaceMesh, Pose, Holistic):Pose
- Programming Language and version ( e.g. C++, Python, Java): obj-C

**Describe the expected behavior:**
In my thoughts, smooth_landmrks works on pose_world_landmarks as well. However, it looks not
**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

Hello, google team
MediaPipe is a powerful tool for 3D animation; however, the pose demonstration APP cannot satisfy the requirement of smooth motion even if the smooth_lanmarks is set to true. This must be resolved for more applications with Mediapipe. From my observation, the normalized landmarks on the screen look stable, but the pose_world_landmarks are not as stable as normalized landmarks. It makes me doubt whether smooth_landmarks works on pose_world_landmarks as well. I believe it does not, based on my experience. Please confirm whether my conjecture is true or not. Thank you!

**Comment by fchen09** [comment]
OK, I got the solution, the one_euro_filter's parameters are too weak to suppress jitters on pose_world_landmarks. We need enhance these parameters. Hope you guys check those parameters. Thanks.

**Comment by kuaashish** [comment]
Hi @fchen09, Could we move this to close status as the issue has been resolved as per the [above](https://github.com/google/mediapipe/issues/3522#issuecomment-1185215872) comment. Thank you!

**Comment by fchen09** [comment]
> Hi @fchen09, Could we move this to close status as the issue has been resolved as per the [above](https://github.com/google/mediapipe/issues/3522#issuecomment-1185215872) comment. Thank you!

Sure, thanks!
