### ISSUE TITLE
Object Detection Tensorflow does not compile on Windows 11

### ISSUE THREAD

**Issue by PZerua** [google/mediapipe#3524]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution: Windows 11 (21996.1)
- Compiler version: 14.29.30133
- Programming Language and version: C++
- MediaPipe version: v0.8.10.2
- Bazel version: 5.2.0
- OpenCV version: 3.4.10

**Describe the problem**:
When compiling Object Detection with Tensorflow model (as described [here](https://google.github.io/mediapipe/solutions/object_detection.html)), it gives different compilation errors each time (I guess because of threaded compile). Also, debug and release builds give different errors. I can compile and execute the ``objectdetectioncpu`` example with no problem.

Again, not always the same file but:
Release build always give errors related to ``REGISTER_KERNEL_BUILDER`` compiling org_tensorflow.
Debug build always give errors related to conversion between types.

**Provide the exact sequence of commands / steps that you executed before running into the problem:**

Debug
```
set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
set BAZEL_VC_FULL_VERSION=14.29.30133
set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0

bazel build -c dbg --define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true --linkopt=-s --action_env PYTHON_BIN_PATH="C://Users//GTI//AppData//Local//Programs//Python//Python310//python.exe" mediapipe/examples/desktop/object_detection:object_detection_tensorflow
```

Release
```
set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
set BAZEL_VC_FULL_VERSION=14.29.30133
set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0

bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true --linkopt=-s --action_env PYTHON_BIN_PATH="C://Users//GTI//AppData//Local//Programs//Python//Python310//python.exe" mediapipe/examples/desktop/object_detection:object_detection_tensorflow
```

**Complete Logs:**
[log_dbg.txt](https://github.com/google/mediapipe/files/9130912/log_dbg.txt)
[log_opt.txt](https://github.com/google/mediapipe/files/9131003/log_opt.txt)

**Comment by kuaashish** [comment]
Hi @PZerua, MediaPipe on windows is experimental, we could use your help to investigate. Thank you!
