### ISSUE TITLE
FaceMesh is not detected properly when device is in landscape or portrait upside-down.

### ISSUE THREAD

**Issue by carat-hansol** [google/mediapipe#3525]
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android
- [MediaPipe version](https://github.com/google/mediapipe/releases): 8.10.0
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic): FaceMesh
- Programming Language and version ( e.g. C++, Python, Java): Java

**Describe the expected behavior:**

I am developing a camera app using Mediapipe FaceMesh solution and saw that facemesh is not properly detected when the device is in landscape or portrait upside-down.
So I tried **Android FaceMesh example app** you provide, and checked that face mesh is not detected properly.

<img width=200 src="https://user-images.githubusercontent.com/92852376/179693201-20b0384d-3397-49b4-b180-4b6a66085709.jpeg"/>

Works perfectly in portrait, but:

<img width=400 src="https://user-images.githubusercontent.com/92852376/179693529-47e15700-f613-4be5-9b70-43a44a7139a4.jpeg"/>
<img width=200 src="https://user-images.githubusercontent.com/92852376/179693569-31a27100-34ed-4e6f-8f4b-2b3feac793d0.jpeg"/>

When in landscape or upside down, face mesh is also kinda upside down.

Is there any way we can resolve this problem?
Thank you in advance :)

**Comment by kuaashish** [comment]
Hi @carat-hansol, Have you looked at similar closed issue #3028  and [comment](https://github.com/google/mediapipe/issues/3028#issuecomment-1023990110). Thank you!
