### ISSUE TITLE
Disable landmarks visibility for pose tracking Unreal Engine

### ISSUE THREAD

**Issue by LightQniX** [google/mediapipe#3527]
Hello guys! Could you please tell me, I use Unreal engine plugin (https://github.com/wongfei/ue4-mediapipe-plugin ) I need to hide landmarks from the video image. Is there such a possibility? Thanks!

**Comment by sureshdagooglecom** [comment]
Hi @LightQniX ,
Yes, it can be done by removing input_stream: "landmark_render_data"or input_stream: "VECTOR:0:multi_hand_landmarks_render_data" from AnnotationOverlayCalculator config.

**Comment by LightQniX** [comment]
Please tell me where it can be found this file "AnnotationOverlayCalculator". I found files like these
[pose_landmarks.txt](https://github.com/google/mediapipe/files/9179570/pose_landmarks.txt)
but .pbtxt

**Comment by sureshdagooglecom** [comment]
Hi @LightQniX ,
Landmarks are rendered by AnnotationOverlayCalculator which is controlled by "LandmarksToRenderDataCalculator",  which is invoked in graphs such as:
  google3/third_party/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_gpu.pbtxt
One approach would be to remove these calculators from the "multi_hand_renderer_gpu.pbtxt" graph.

**Comment by LightQniX** [comment]
Thank you very much! You have helped a lot!!!
