### ISSUE TITLE
ERROR about "Build a MediaPipe Android example."

### ISSUE THREAD

**Issue by Javacr** [google/mediapipe#3531]
**System information (version)**
Linux OpenCV = 4.2.0
Operating System / Platform = Windows 64 Bit WSL2(ubuntu20.04)
Android OpenCv =4.2.0
Android SDK = latest
Android NDK = r21e
Detailed description
I successfully ran a c++ example of Hello World in WSL. However, when I tried to build a MediaPipe Android example in WSL, I encountered an error.

ERROR: /home/jim/.cache/bazel/_bazel_jim/9ded6e7e7b0b353b7548db4c7484a645/external/android_opencv/BUILD.bazel:14:12: SolibSymlink _solib_arm64-v8a/_U@android_Uopencv_S_S_Clibopencv_Uarm64-v8a___Usdk_Snative_Slibs_Sarm64-v8a/libopencv_java3.so failed: missing input file 'external/android_opencv/sdk/native/libs/arm64-v8a/libopencv_java3.so', owner: '@android_opencv//:sdk/native/libs/arm64-v8a/libopencv_java3.so'
ERROR: /home/jim/.cache/bazel/_bazel_jim/9ded6e7e7b0b353b7548db4c7484a645/external/android_opencv/BUILD.bazel:14:12: SolibSymlink _solib_arm64-v8a/_U@android_Uopencv_S_S_Clibopencv_Uarm64-v8a___Usdk_Snative_Slibs_Sarm64-v8a/libopencv_java3.so failed: 1 input file(s) do not exist
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu:objectdetectiongpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/jim/.cache/bazel/_bazel_jim/9ded6e7e7b0b353b7548db4c7484a645/external/android_opencv/BUILD.bazel:14:12 SolibSymlink _solib_arm64-v8a/_U@android_Uopencv_S_S_Clibopencv_Uarm64-v8a___Usdk_Snative_Slibs_Sarm64-v8a/libopencv_java3.so failed: 1 input file(s) do not exist
INFO: Elapsed time: 0.328s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully

**I have not found relevant solutions so far.**

**Comment by kuaashish** [comment]
Hi @Javacr, Could you provide the complete steps to reproduce the issue and more details about the issue. Thank you!

**Comment by Javacr** [comment]
> Hi @Javacr, Could you provide the complete steps to reproduce the issue and more details about the issue. Thank you!

Thank you for your reply. I have solved the problem, the main reason is that I use android opencv 4 in WORKSPACE. When I changed to Android OpenCV 3, the APK build was successful.

**Comment by kuaashish** [comment]
Hi @Javacr, Good to hear that the issue has been resolved. Could you move this issue to close status as it doesn't need further assistance. Thank you!
