### ISSUE TITLE
Finger detcection 

### ISSUE THREAD

**Issue by CheungBH** [google/mediapipe#3535]
Hello. Do you have a finger detection demo for IOS? I can only find the hand detection demo, without detection fingers.

**Comment by sureshdagooglecom** [comment]
Hi @CheungBH ,
For IOS we have very clear documentation [here](https://google.github.io/mediapipe/getting_started/ios). You can build an Hand tracking code from the above link and reach us if you still have any query. For ASL language recognition look at reference https://github.com/google/mediapipe/issues/450
