### ISSUE TITLE
JS FaceMesh documentation

### ISSUE THREAD

**Issue by ndrewtl** [google/mediapipe#3536]
Thank you for submitting a MediaPipe documentation issue.
The MediaPipe docs are open source! To get involved, read the documentation Contributor Guide
## URL(s) with the issue:

https://google.github.io/mediapipe/solutions/face_mesh.html

## Description of issue (what needs changing):

The Facemesh documentation doesn't currently include an explanation of the `Mesh` type or how to use the `getVertexBufferList()` or `getIndexBufferList()` methods. All docs I can find only describe `landmark` functionality. I would like to know how to parse or decode the `Mesh` and other FaceGeometry types, as well as have an example of say, importing a FaceMesh as a mesh or animation into Three.js. The types are well-defined, so clearly there is a standardized functionality here. I would just like a description of what it is.

**Comment by brunodeangelis** [comment]
The docs for Mediapipe are just awful. There's no API reference to be found anywhere. I hope they fix this sometime

**Comment by kuaashish** [comment]
Hello @ndrewtl,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
