### ISSUE TITLE
how to measure person's height?

### ISSUE THREAD

**Issue by sosoyeon1125** [google/mediapipe#3538]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):Linux Ubuntu 18.04
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):  Holistic
- Programming Language and version ( e.g. C++, Python, Java):  Python

**Describe the expected behavior:**

Could you tell me how to measure a person's height using a mediapipe??
Or can you tell me issues and examples related to this?
 get some help... i beg you....

**Comment by kuaashish** [comment]
Hi @sosoyeon1125, Yes, It's possible to detect the person's height in the MediaPipe using the "Pose" solution. 
Please follow the below steps to measure the person's height:

1) Start with the MediaPipe "pose" solution.
2) Find the head and toe landmarks in "world coordinates".
3) Measure the vector in world coordinates between these landmarks.  

Thank you!

**Comment by sal-p** [comment]
> 

HI, do you know how does mediapipe calculate POSE_WORLD_LANDMARKS? I mean what method/ scientific principle does it use to extract how far away, say, neck, or left hand is from the center of the hip? I need this in order to establish credibility of some of my results that I have gotten from it. Thanks :)
