### ISSUE TITLE
Mediapipe how to detect a speific person?

### ISSUE THREAD

**Issue by ArtfulMinx** [google/mediapipe#3539]
I observed that it only detects the closest person to the cam in a video, but I want to detect a person who is some distance away and not the closest one? How do I do that?

btw the person I want to detect can be considered to be center of the video

Thank you

**Comment by akryeem** [comment]
+1
I see the issue of detecting multiple persons is repeatedly raised from time to time and the solution suggested (modify the graph) isn't really practical as there is no any tutorial on how to make such graph modification, in addition to the requirement to recompile the whole model.
I think MP can do a huge favor to the community by adding support for multi-pose detection! the approach proposed in  https://github.com/google/mediapipe/issues/1691#issuecomment-1103730953 can be a good start.

BTW, other libraries such as OpenPose do support the multi-pose detection, it's better that MP add such ability to avoid people from searching alternative libraries.

**Comment by sureshdagooglecom** [comment]
Hi @ArtfulMinx ,
Could you please check this https://github.com/google/mediapipe/issues/3539#issuecomment-1193091309 comments and confirm still if you have any error.

**Comment by akryeem** [comment]
@sureshdagooglecom none of the comments there describes the steps needed to enable multiple persons detection, it says that the graph need to be changed. How to change it? is there any explanation or tutorial on how to build and use a modified graph?

**Comment by sureshdagooglecom** [comment]
Hi @ArtfulMinx ,
Could you please share any reference video to investigate further on this issue.
