### ISSUE TITLE
Incorrect display

### ISSUE THREAD

**Issue by Javacr** [google/mediapipe#3542]
![无标题1](https://user-images.githubusercontent.com/44012990/180633688-240a8842-42d8-40ec-9a68-d386998cb329.png)

![无标题](https://user-images.githubusercontent.com/44012990/180633636-d73a3f8f-d7cf-4a6c-8317-d4f0e4afabc7.png)

When I run the official [face detection example](https://github.com/jiuqiant/mediapipe_face_detection_aar_example), I encounter a strange problem. As shown in the screenshots, no matter the "input_video" or "output_video", the display result is wrong and the image is stretched.

**Comment by Javacr** [comment]
I have solved this issue. When I give up  using "displaySize" in MainActivity, the image is right.

**Comment by sureshdagooglecom** [comment]
Hi @Javacr,
can you close this issue if resolved.
