### ISSUE TITLE
Hello World BUILD should not require internal deps

### ISSUE THREAD

**Issue by cgtinker** [google/mediapipe#3546]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- Linux Manjaro

**Describe the problem**:
Running the hello_world BUILD from a another local repository results in visibility issues. This took me quiet a while to figure out as a hello_world example usually should be easy to run.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
- Create a new repository
- Configure the workspace (containing mediapipe deps)
- Use mediapipe as local repository
- Run the hello_world example

**Solution**:
Change the hello_world dependencies from:

```
cc_binary(
    name = "hello_world",
    srcs = ["hello_world.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//mediapipe/calculators/core:pass_through_calculator",
        
        "//mediapipe/framework:calculator_graph",
        "//mediapipe/framework/port:logging",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
    ],
)
```

To:

```
cc_binary(
    name = "hello_world",
    srcs = ["hello_world.cc"],

    deps = [
        "//mediapipe/calculators/core:pass_through_calculator",
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/port:logging",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
    ],
)

```

**Comment by kuaashish** [comment]
Hello @cgtinker,

This is a legacy solution And We will be not able to fix this issue. Thank you!!
