### ISSUE TITLE
handtracking is not right, but only detection

### ISSUE THREAD

**Issue by northeastsquare** [google/mediapipe#355]
I think the examples in hand pose, just done detection with landmark, but no tracking in videos.
for example https://github.com/google/mediapipe/blob/master/mediapipe/docs/hand_tracking_desktop.md
have only detection, not tracking.
So, maybe should change name

**Comment by mgyong** [comment]
Hand tracking example does do simple loop based tracking just not using an existing MediaPipe object tracking calculators.
