### ISSUE TITLE
IOS Example of Selfie Segmentation using Background Blur and picture

### ISSUE THREAD

**Issue by jessonliu** [google/mediapipe#3551]
As for the ios example of selfie segmentation, could you please give me more details? Could you add the background blur effect and the example of changing the background to a picture? Thank you very much

**Comment by wangrenzhu** [comment]
Why not do it yourself？？
custom the render and do it

**Comment by mcclanahoochie** [comment]
Try using the [MaskOverlayCalculator](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/calculators/image/mask_overlay_calculator.cc) (instead of RecolorCalculator)  to overlay a custom image stream (such as blurred background).

**Comment by kuaashish** [comment]
Hi @jessonliu, Could you please go through the [above comment](https://github.com/google/mediapipe/issues/3551#issuecomment-1238663326) and try the suggestion mentioned. Thank you!
