### ISSUE TITLE
Output model tensorflow

### ISSUE THREAD

**Issue by watermellon2018** [google/mediapipe#3552]
I convert model tensorflow lite into tensorflow. And i predict the pose estimate at image. Output is tensor of shape [39 5]. I need only key points of body and coordinates. I get slice [0:33, 0:3] and i want it to draw at image. How i can do that? The range output model strange, it is not [0-1], i try to put this is at image with shape 256*256, but it is not correct. I try to use Sigmoid for predict tensor, but get strange values, example:
[[1.000+00, 6.526e-29, 0], [1.000+00, 8.36e-31, 0], [0.0000009, 0.99999991]
Thanks

**Comment by watermellon2018** [comment]
Normalization not help, i convert prediction array to range [0; 1] and get this:
![image](https://user-images.githubusercontent.com/41168830/181181411-4c90a99f-7e6e-40e8-b73a-f380384fc737.png)

**Comment by watermellon2018** [comment]
I normalization this way:
```
        inputMax = 256
        inputMin = -256
        leftSpan = inputMax - inputMin
        rightSpan = 1 - 0
        
        predictions = (predictions - inputMin) / leftSpan
```

**Comment by kuaashish** [comment]
Hi @watermellon2018, Is it implemented through python, Javascript or others? Could you please help me in reproducing the same with complete steps at our end. Thank you!

**Comment by watermellon2018** [comment]
@kuaashish It is implemented through python. I use tensorflow model `pose_landmark_heavy`. I pass image into model and get tensor with shape 1, 195, make reshape (39, 5), get only 33 points and 2 (x, y) coordinates, then i flip horizontal and normalized it
Code:
```
TFLITE_FILE_PATH = 'model_float32.pb' # i convert tflite into tf
    graph_def = tf.compat.v1.GraphDef()
    with tf.io.gfile.GFile(TFLITE_FILE_PATH, 'rb') as f:
        graph_def.ParseFromString(f.read())
        tf.import_graph_def(graph_def, name='')

    input_node = 'input_1:0'
    output_layer = 'Identity:0'

 with tf.compat.v1.Session() as sess:
        prob_tensor = sess.graph.get_tensor_by_name(output_layer)
        predictions = sess.run(prob_tensor, {input_node: [input_data] })

        predictions = predictions.reshape((1, 39, 5))
        print(np.min(predictions[0, :, 0:2]), np.max(predictions[0, :, 0:2]))
        predictions = predictions[:, 0:33, 0:2][0]
        predictions[:, 0] = (256 - predictions[:, 0]) / 256
        predictions[:, 1] = predictions[:, 1] / 256
```

**Comment by kuaashish** [comment]
Hi @watermellon2018, Have you looked at this closed issue #1701  and [comment](https://github.com/google/mediapipe/issues/1701#issuecomment-797131246). Thank you!

**Comment by watermellon2018** [comment]
@kuaashish Thank you. I added normalize image and post proccessing of the prediction, it a little bit help. But when i merged prediction from Python API and prediction from Tensorflow model. I get this (blue - python api / green - tensorflow):
![myplot](https://user-images.githubusercontent.com/41168830/181687381-1718d708-da69-4b18-84ab-fbff6d89ac33.png)

**Comment by liuyulvv** [comment]
@watermellon2018 Good jobs, can you share your codes? The picture seems to be from the bgr channel.

**Comment by kuaashish** [comment]
Hi @watermellon2018, This issue to more related to tensorflow. Could you please raise this issue to tensorflow [repo](https://github.com/tensorflow/tensorflow/issues).
Thank you!

**Comment by fchen09** [comment]
@watermellon2018 can you share how you convert tflite into tf? Thanks!
