### ISSUE TITLE
Implementation of 3d glass try on using mediapipe

### ISSUE THREAD

**Issue by gopig99** [google/mediapipe#3553]
Hi, can anyone help me in implementing the 3d glass try-on or rendering on face using mediapipe. In documentation there is no sample code for that
example image/gif - 
!
[68747470733a2f2f676f6f676c652e6769746875622e696f2f6d65646961706970652f696d616765732f666163655f67656f6d657472795f72656e64657265722e676966](https://user-images.githubusercontent.com/68884919/181165803-15a78bb2-69f5-4241-b64a-bc1cacadaca3.gif)
.

**Comment by onuralpszr** [comment]
Example code : https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect

Related Document link with face effect section : https://google.github.io/mediapipe/solutions/face_mesh.html#face-effect-example

**Comment by gopig99** [comment]
Thank you @onuralpszr , Can we implement this in python?

**Comment by onuralpszr** [comment]
Close example I found is here : https://learnopencv.com/create-snapchat-instagram-filters-using-mediapipe/  that may be help you out in certain point. 

Other related issue is : https://github.com/google/mediapipe/issues/3149 

Good luck.

**Comment by gopig99** [comment]
yes after following that I have  annotated and executed .....got an error
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\ptsetreg.cpp:1108: error: (-215:Assertion failed) count >= 0 && to.checkVector(2) == count in function 'cv::estimateAffinePartial2D'

[ WARN:1@19.242] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by kuaashish** [comment]
Hi @gopig99, Could you please elaborate your query with complete details and standalone code to reproduce the issue. 
Thank you!

**Comment by gopig99** [comment]
Hi @kuaashish here is the repository https://github.com/gopig99/AR-filters-MediPipe

**Comment by kuaashish** [comment]
Hi @gopig99, Have you looked at this [#SO](https://stackoverflow.com/questions/35428739/opencv-estimateaffine3d-failes-with-cryptic-error-message) issue. Thank you!

**Comment by Siziff** [comment]
hello everyone, I'm trying to figure out how to transfer the texture to the face without marking the dots (as was done in the previous comments) ? For example, in Spark AR, it is enough to add a picture according to a template and it is automatically stretched to the points of the face, is it possible to do this in Mediapipe?

**Comment by Samreena-123** [comment]
How can I achieve virtual jewellery set try on only using computer vision open cv and mediapipe?
