### ISSUE TITLE
Creating ios examples externally

### ISSUE THREAD

**Issue by serrabii** [google/mediapipe#3556]
Hi,

Is there a way to write an ios example such as those in `mediapipe/mediapipe/examples/ios` outside of mediapipe's repository?

It seems that all such examples need to depend on rules (`//mediapipe/objc:mediapipe_framework_ios`, `//mediapipe/objc:mediapipe_input_sources_ios`, `//mediapipe/objc:mediapipe_layer_renderer`) which are not **publicly visible**.

**My use case:**

I have done some changes to `mediapipe/mediapipe/examples/ios/common` so that i can run graphs on a video file instead of the camera. It works when i build the example directly from the cloned mediapipe repository.

However i would like to version control my ios app independently from the mediapipe repository (which can then be added as an `http_archive` in my `WORKSPACE`).

**Comment by serrabii** [comment]
Hi @sureshdagooglecom ,

Thanks for replying.

I believe that the documentation you linked doesn't build the ios app outside of the mediapipe source code.

> Copy these files to a directory named HelloWorld to a location that can access the MediaPipe source code. For example, the source code of the application that we will build in this tutorial is located in mediapipe/examples/ios/HelloWorld.

**Comment by sureshdagooglecom** [comment]
Hi @serrabii ,
Could you please elaborate this use case with more information to investigate further on this .
What is the meaning of building app outside the mediapipe source code.

**Comment by serrabii** [comment]
Hi @sureshdagooglecom ,

I am doing something similar to https://github.com/google/mediapipe/issues/256 . Since I am using mediapipe as a remote bazel dependency i can't depend on rules that aren't publicly visible.

**Comment by schmidt-sebastian** [comment]
We will discuss this with the team and follow up.

**Comment by schmidt-sebastian** [comment]
The build rules are now public.

**Comment by serrabii** [comment]
Great, thank you so much!
