### ISSUE TITLE
Mediapipe webserver

### ISSUE THREAD

**Issue by razor123max** [google/mediapipe#3558]
<em>Please make sure that this is a feature request.</em>

- MediaPipe Solution (you are using): **facemesh, Iris**
- Programming language : **C++**
- Are you willing to contribute it (Yes/No):

Is there anyway to put mediapipe behind web-server while utilising GPU? any pointers?

I am planning to use webRTC for video or grpc with image frame by frame request, any pointers?

**Comment by kuaashish** [comment]
Hi @razor123max,
Are you still looking for the resolution or the issue has been resolved from your end. Thank you!

**Comment by kuaashish** [comment]
Hi @razor123max,
Thanks for your confirmation. Could you please elaborate your query with more details and required support you are referring to. Thank you!

**Comment by razor123max** [comment]
1) Mediapipe deployment on the web-server hosted on cloud? If possible, with GPU support
2) WebRTC / GRPC video stream as a source to Mediapipe, rather than local camera source

**Comment by kuaashish** [comment]
Hi @razor123max,
We believe this will be a challenging use case of MediaPipe config and will require some special expertise in configuring GPU drivers, such as NVIDIA drivers on server. We don't have a working "self-serve" solution for GPU on server. Thank you!

**Comment by kuaashish** [comment]
Hi @mcclanahoochie,
Could you please look into the above issue. Thank you!

**Comment by kuaashish** [comment]
Hi @mcclanahoochie,
Could you please share some plausible routes for manual implementation of web-server by the user? Thank you!

**Comment by mcclanahoochie** [comment]
One example of a simple webserver that runs mediapipe is [youtube8m](https://google.github.io/mediapipe/solutions/youtube_8m.html). The yt8m example runs a binary mediapipe [analysis graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt) on linux, and streams the results to the webpage. There are probably other examples on the internet to search for.
For gpu support, you need to ensure the server can run mediapipe GPU by following these [instructions](https://google.github.io/mediapipe/getting_started/gpu_support.html), and also edit whatever graph you run to use GPU calculators.

If you want to run a custom model inference on GPU inside the browser, that is currently not supported. 
The mediapipe Javascript solutions API provided does use GPU for inference (but these are not customizable). If you can make use of the javascript [solutions on web](https://codepen.io/mediapipe) API, you will benefit form GPU inference.
