### ISSUE TITLE
How to debug mediapipe

### ISSUE THREAD

**Issue by northeastsquare** [google/mediapipe#356]
For example, How to print some node's output shape and values?
while tensorflow have tf.Print

**Comment by afsaredrisy** [comment]
Hey @northeastsquare  if you are using android & want to debug calculators then you can use ```android/log.h```.
Import ```c #include <android/log.h>``` in corresponding calculator and use ```c __android_log_print(ANDROID_LOG_ERROR, "%d ", value);``` 

Note: This will not work inside Shader code.

**Comment by lcycoding** [comment]
For normal linux_x86 debug, just simply use GLOG to debug.

For instance
`LOG(INFO) << tensor->dims->data[0];`

Also remember to export GLOG_logtostderr=1 before running the process.

**Comment by northeastsquare** [comment]
Sorry, I have not describe clearly.For example, one graph has many same node type, I just want to print in particlular node

**Comment by jiuqiant** [comment]
> Hey @northeastsquare if you are using android & want to debug calculators then you can use `android/log.h`.
> Import `#include <android/log.h>` in corresponding calculator and use `__android_log_print(ANDROID_LOG_ERROR, "%d ", value);`
> 
> Note: This will not work inside Shader code.

FYI, you also can use GLOG to debug Android. We have [a glog patch for Android](https://github.com/google/mediapipe/blob/master/third_party/com_github_glog_glog_9779e5ea6ef59562b030248947f787d1256132ae.diff)

**Comment by jiuqiant** [comment]
> Sorry, I have not describe clearly.For example, one graph has many same node type, I just want to print in particlular node

Every node has a unique node name in the graph. You can do `LOG(INFO) << cc->NodeName() << " DEBUG INFO YOU NEED";` to show the node name as well as the debug info in Calculator's Open(), Process(), and Close() methods.

**Comment by northeastsquare** [comment]
Thank you, @jiuqiant ,cc->NodeName

**Comment by zhenfengcao** [comment]
debugging mediapipe is too slow... do we need to rebuild the whole project for every tiny change of the code? ---it would usually take more than half an hour.  how can we make it quiker? Thanks

**Comment by matanster** [comment]
Is there a feature in the framework allowing more declarative logging of a processing node's (calculator) output yet?
