### ISSUE TITLE
Where is the Objectron 2stage graph?

### ISSUE THREAD

**Issue by matildao-pane** [google/mediapipe#3561]
Solution: Objectron

Where can I find the file with the precise description of the graph used by the 2 stage architecture Objectron??? At this 
[link](https://github.com/google/mediapipe/tree/master/mediapipe/modules/objectron) 
I can only see files with 1_stage description in the name. 
Which one is referred to the 2stage architecture?

**Comment by matildao-pane** [comment]
Besides I dont understand if the detection and tracking is applied differently to the 2stage architecture, because it seems from the papers and the documentation that the detection and tracking subgraphs are related only to the 1stage

**Comment by matildao-pane** [comment]
https://arxiv.org/abs/2006.13194

does the technique described here in this paper is applied also to the 2stage architecture?

**Comment by sureshdagooglecom** [comment]
Hi @matildao-pane .
Yes , that paper describes about 2 stage architecture.
