### ISSUE TITLE
Graph Profiling and Tracing

### ISSUE THREAD

**Issue by optimaltaskin** [google/mediapipe#3562]
Hi,

I tried to implement profiling to solve issues I'm experiencing with face effect module. I followed steps mentioned in [documentation](https://google.github.io/mediapipe/tools/tracing_and_profiling.html). However coulnd't make it work.

In the docs it says I should add code snippet below in the CalculatorGraphConfig  which is in calculator.proto.

```
profiler_config {
  trace_enabled: true
  enable_profiler: true
  trace_log_interval_count: 200
  trace_log_path: "/sdcard/Download/"
}
```

I have added that snippet in the calculator.proto file as mentioned but it didn't work. Then I have added the code lines into my graph file(to all nodes seperately) then during runtime I have received depreceated warning message which indicated that profile_config is deprecated and ignored. 

Could anyone please help me about how to implement the profiler? I'm running Mediapipe on desktop (Ubuntu 21.04) and using C++ with version 10.3.0. Bazel version is v1.12.0 and  finally mediapipe version is v0.8.10.2. 
I really appreciate any help. Thanks.

**Comment by Conru1** [comment]
Hi,
I got mine working on android by only adding the profiler_config to the top of my graph file right before the first node. Not in calculator.proto and not in each node separately.

**Comment by optimaltaskin** [comment]
Thanks @Conru1, that helped a lot. I got it working as well. However I couldn't find what I was looking for, but that's another subject  :)
