### ISSUE TITLE
the z coordinate of pose tracking should not be affaced by swinging arms.

### ISSUE THREAD

**Issue by fchen09** [google/mediapipe#3566]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):ios 15.5
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.10
- Bazel version: 5.2
- Solution (e.g. FaceMesh, Pose, Holistic): pose
- Programming Language and version ( e.g. C++, Python, Java): OC

**Describe the expected behavior:**
3D body tracking is amazing with mediapipe, but the accuracy of the z coordinate requires improvement. For example, swinging only arms should not affect the z coordinate of other static joints, such as the nose, ears, etc. However, when I only move my arms, my nose and other facial joints are swinging, too. I believe it is caused by the depthAI that weights all pixels including other joints. Can the correlation among different joints be decoupled? or how to mitigate the coupling of various joints? Can we impose the depth data from the lidar or depth camera to improve the z-axis accuracy? Thanks.

**Comment by sureshdagooglecom** [comment]
Hi @fchen09 ,
Could you please share any reference video and also if any code changes to investigate further on this issue.

**Comment by fchen09** [comment]
At this stage, pardon me cannot share the video. Let me draw how it is going on in the figure. When I swing my arms, the body was lean back and forth depending on whether the arm is backward or forward. Any solution to the unwanted swing? Thanks.
![IMG_1358](https://user-images.githubusercontent.com/84703080/182541074-1bf0b27a-037a-4e14-a578-998177a46ba8.JPG)

**Comment by sureshdagooglecom** [comment]
Hi @fchen09 ,
We have closed issue which is having answer for queries on Z co-ordinate , could you please check that closed [issue](https://github.com/google/mediapipe/issues/1611#issuecomment-974941821).
