### ISSUE TITLE
process output of pose_landmark_lite

### ISSUE THREAD

**Issue by liuyulvv** [google/mediapipe#3567]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 10
- [MediaPipe version](https://github.com/google/mediapipe/releases): [v0.8.10.2](https://github.com/google/mediapipe/tree/v0.8.10.2)
- Bazel version: 5.2.0
- Solution (e.g. FaceMesh, Pose, Holistic): Pose
- Programming Language and version ( e.g. C++, Python, Java): Python3

**Describe the expected behavior:**

Since mediapipe cannot use gpu for acceleration under windows, I want to use onnxruntime for acceleration.

I convert tflite to onnx, and make sure the conversion is successful.

```python
pose_landmark = onnxruntime.InferenceSession(
    "pose_landmark_lite.onnx",
    providers=["CUDAExecutionProvider", "CPUExecutionProvider"],
)
capture = cv2.VideoCapture("D:/video/mother.mp4")

if capture.isOpened():
    hasFrame, frame = capture.read()
else:
    hasFrame = False

while hasFrame:
    # img1: 256x256
    # img2: 128x128
    img1, img2, scale, pad = resize_pad(frame)
    input = torch.from_numpy(img1.astype(np.float32))
    input = input.unsqueeze(0)
    (
        pose_landmarks,
        pose_world_landmarks,
        segmentation_mask,
        pose_landmarks_roi,
        pose_detection,
    ) = pose_landmark.run(
        None, {pose_landmark.get_inputs()[0].name: input.cpu().numpy()}
    )
    print(
        pose_landmarks.shape,  # (1, 195)
        pose_world_landmarks.shape,  # (1, 1)
        segmentation_mask.shape,  # (1, 256, 256, 1)
        pose_landmarks_roi.shape,  # (1, 64, 64, 39)
        pose_detection.shape,  # (1, 117)
    )
    hasFrame, frame = capture.read()
    key = cv2.waitKey(1)
    if key == 27:
        break
```

As shown in the comments of the above code, the shape of pose_landmarks is `(1, 195)`.

When using `mp.pose`, the output of the `pose_landmarks` is similar to

```
landmark {
  x: 0.3057445287704468
  y: 0.9131049513816833
  z: -0.014605664648115635
  visibility: 0.9162100553512573
  presence: 0.9988192915916443
}

...

landmark {
  x: 0.3057445287704468
  y: 0.9131049513816833
  z: -0.014605664648115635
  visibility: 0.9162100553512573
  presence: 0.9988192915916443
}
```

They are `32` landmark as described in document.

What is the processing between these two `outputs` ? I didn't find the relevant python code.

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment]
Hi @liuyulvv, Could you please elaborate your query with complete details. Thank you!

**Comment by liuyulvv** [comment]
@kuaashish How to convert `pose_landmarks`(one of the outputs of pose_landmark_lite, a tensor with shape of (1,195)), into
```
  x: 0.3057445287704468
  y: 0.9131049513816833
  z: -0.014605664648115635
  visibility: 0.9162100553512573
  presence: 0.9988192915916443
```

What is the relationship between `195 numbers` and `33` landmarks' `x, y, z, visibility, and presence` ? Thanks a lot.

**Comment by ted1986122** [comment]
@liuyulvv   I convert tflite to onnx aways fails.Can you give me a model of onnx?

**Comment by liuyulvv** [comment]
@ted1986122 https://github.com/liuyulvv/mediapipe/tree/main/mediapipe/modules/pose_landmark

**Comment by vigneshrk29** [comment]
Hi liuyulvv,

Did you figure out how to get the landmarks from (1,195)) tensor?

Thanks

**Comment by HzHzHzHzHz** [comment]
> @kuaashish How to convert (one of the outputs of pose_landmark_lite, a tensor with shape of (1,195)), into`pose_landmarks`
> 
> ```
>   x: 0.3057445287704468
>   y: 0.9131049513816833
>   z: -0.014605664648115635
>   visibility: 0.9162100553512573
>   presence: 0.9988192915916443
> ```
> 
> What is the relationship between and landmarks' ? Thanks a lot.`195 numbers``33``x, y, z, visibility, and presence`
Have you solved this problem yet? Can you explain how this result was converted if it is resolved?

**Comment by HzHzHzHzHz** [comment]
> 如何将（形状为 （1，195）的张量 pose_landmark_lite 的输出之一）转换为`pose_landmarks`
> 
> ```
>   x: 0.3057445287704468
>   y: 0.9131049513816833
>   z: -0.014605664648115635
>   visibility: 0.9162100553512573
>   presence: 0.9988192915916443
> ```
> 
> 和地标之间有什么关系？多谢。`195 numbers``33``x, y, z, visibility, and presence`

Have you solved this problem yet? Can you explain how this result was converted if it is resolved?

**Comment by liuyulvv** [comment]
@HzHzHzHzHz @vigneshrk29 

landmark_list  = [$`x_1`$ ,$` y_1`$, $` z_1`$, $`visibility_1`$, $`presence_1`$, $`x_2`$, ... $`presence_2`$, ......]
values ​​are stored continuously
