### ISSUE TITLE
Mediapipe: How to convert pose landmarks from Pixel_space to World_space

### ISSUE THREAD

**Issue by UtsaChattopadhyay** [google/mediapipe#3571]
I am working on building a standalone cpp project for detecting pose. We are able to get the pixel space output while doing pose detection.
[Here](https://google.github.io/mediapipe/solutions/pose.html#pose-landmark-model-blazepose-ghum-3d), it says that the pose landmark model detects 33 landmarks in pixel and world space, where each landmark has 4 values (x,y,z, visibility). We are looking for a way to convert the landmark values from pixel space to world space using some formula or detailed process for conversion.

Thanks.

**Comment by Pogosito** [comment]
@UtsaChattopadhyay Hi! 
I faced the same task did you found the formula/answer ?

**Comment by Safi9024** [comment]
anyone get how to solve that problem? if yes, please help

**Comment by UtsaChattopadhyay** [comment]
Resolved

**Comment by kuaashish** [comment]
@UtsaChattopadhyay,

Thanks for the confirmation, Closing this issue as it has been resolved.
