### ISSUE TITLE
Mediapipe Build Error

### ISSUE THREAD

**Issue by yifeix5** [google/mediapipe#3574]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information**:
-  Linux Ubuntu 18.04
- Compiler version: gcc/g++ 8
- Programming Language and version: Python 3.6.9
- Installed based on this link: https://github.com/AndreV84/mediapipe
- Bazel version: 6.0.0

**Describe the problem**:
When I build the Mediapipe, it comes an error at the end:

-----------------------------------------------------------------------------------------------------------------
ERROR: /home/elephant/mediapipe/mediapipe/calculators/tensor/BUILD:371:11: Compiling mediapipe/calculators/tensor/tensors_to_detections_calculator.cc failed: undeclared inclusion(s) in rule '//mediapipe/calculators/tensor:tensors_to_detections_calculator':
this rule is missing dependency declarations for the following files included by 'mediapipe/calculators/tensor/tensors_to_detections_calculator.cc':
  '/usr/lib/gcc/aarch64-linux-gnu/8/include/stddef.h'
  '/usr/lib/gcc/aarch64-linux-gnu/8/include/stdarg.h'
  '/usr/lib/gcc/aarch64-linux-gnu/8/include/stdint.h'
  '/usr/lib/gcc/aarch64-linux-gnu/8/include-fixed/limits.h'
  '/usr/lib/gcc/aarch64-linux-gnu/8/include-fixed/syslimits.h'
  '/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h'
  '/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_fp16.h'
  '/usr/lib/gcc/aarch64-linux-gnu/8/include/float.h'
Target //mediapipe/modules/face_detection:face_detection_short_range_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 917.975s, Critical Path: 908.90s
INFO: 10 processes: 10 internal.
FAILED: Build did NOT complete successfully
---------------------------------------------------------------------------------------------------------------------

Does anyone know how to solve this issue? Thank you so much in advance.

**Comment by kuaashish** [comment]
Hi @yifeix5, Could you please build the above example using steps mentioned in the official documentation as mentioned [here](https://google.github.io/mediapipe/getting_started/cpp.html). Please let us know if still encounter the error. Thank you!

**Comment by yifeix5** [comment]
> Hi @yifeix5, Could you please build the above example using steps mentioned in the official documentation as mentioned [here](https://google.github.io/mediapipe/getting_started/cpp.html). Please let us know if still encounter the error. Thank you!

Thank you for your reply. I tried to use official document to build Mediapipe on Ubuntu 18.04, but I still get "missing dependency" error, which is shown below.

--------------------------------------------------------------------------------------------------------
ERROR: /home/elephant/mediapipe/mediapipe/calculators/tensor/BUILD:118:11: Compiling mediapipe/calculators/tensor/inference_calculator.cc failed: undeclared inclusion(s) in rule '//mediapipe/calculators/tensor:inference_calculator_interface':
this rule is missing dependency declarations for the following files included by 'mediapipe/calculators/tensor/inference_calculator.cc':
  '/usr/lib/gcc/aarch64-linux-gnu/8/include/stddef.h'
  '/usr/lib/gcc/aarch64-linux-gnu/8/include/stdarg.h'
  '/usr/lib/gcc/aarch64-linux-gnu/8/include/stdint.h'
  '/usr/lib/gcc/aarch64-linux-gnu/8/include-fixed/limits.h'
  '/usr/lib/gcc/aarch64-linux-gnu/8/include-fixed/syslimits.h'
  '/usr/lib/gcc/aarch64-linux-gnu/8/include/stdbool.h'
Target //mediapipe/modules/face_detection:face_detection_short_range_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 850.781s, Critical Path: 796.54s
INFO: 5 processes: 5 internal.
FAILED: Build did NOT complete successfully
----------------------------------------------------------------------------------------------------------

**Comment by kuaashish** [comment]
Hi @yifeix5, Could you please confirm that you are still looking for resolution or the issue has been resolved. Thank you!
