### ISSUE TITLE
Method Used to Calculate POSE_WORLD_LANDMARKS?

### ISSUE THREAD

**Issue by sal-p** [google/mediapipe#3577]
Hi, does anyone know how does mediapipe calculate POSE_WORLD_LANDMARKS? I mean staring from the info of pelvis/ hip, what principles or assumptions does it use to say any landmark, say neck or shoulder, is a certain distance (x, y, z) away from it?
There seems to be no information about it in the documentation.

**Comment by kuaashish** [comment]
Hi @sal-p, "pose_world_landmarks" are the pose landmarks in **real-world 3D coordinates** that are in meters with the origin at the center between hips. 

Coordinates **X** and **Y** are the Landmark coordinates normalized to [0.0, 1.0] by the image width and height respectively. **Z** coordinate represents the landmark depth with the depth at the midpoint of hips being the origin, and the smaller the value the closer the landmark is to the camera.

Please refer to this closed issue (https://github.com/google/mediapipe/issues/1611) to know more about it. 
Thank you!

**Comment by sal-p** [comment]
> #1611

That was a very good explanation, and the resources provided by users in the issue you've linked helped too but they still missed the point. 
Let me explain it again, let's say we have a person that is sitting straight and another who's hunched over. In each case mediapipe pose world landmarks will yield different x, y, and z coordinates for neck landmark (because in each case it's in different relative spatial position relative to the centre of the hips). 
My question is how does mediapipe determine where the neck or any other landmark relative to the centre of the hip is? Surely, it isn't a simple hardcoded distance, but based on some model (vitruvian man) or some other information about landmark's depth, for example. I'm interested in understanding that, thanks.

**Comment by kuaashish** [comment]
Hello @sal-p,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
