### ISSUE TITLE
Can I learn more about mediapipe?

### ISSUE THREAD

**Issue by Woong0416** [google/mediapipe#3579]
I want to use Holistic among the functions of Mediapipe to extract the desired point and skeleton with just images of the arms and legs. For that reason, I need to learn images or images of my arms and legs, is there a way?

**Comment by sureshdagooglecom** [comment]
Hi @Woong0416 ,
MediaPipe solutions has official document on understing how solutions works on different platforms , please refer [this](https://google.github.io/mediapipe/solutions/holistic.html) document and revert back if you have any questions.
