### ISSUE TITLE
Firefox compatibility for viz.mediapipe.dev

### ISSUE THREAD

**Issue by PrinceP** [google/mediapipe#358]
Visualizer on firefox is buggy. The nodes are not clearly connected. Had to use chrome for the parser to run successfully.

![image](https://user-images.githubusercontent.com/10251537/71551968-38dfe380-2a18-11ea-9f25-eda86670f45b.png)

**Comment by mgyong** [comment]
@PrinceP We ensure compatibility for chrome but not necessary for Firefox. It is best to use MediaPipe Visualizer with Chrome
