### ISSUE TITLE
How to detect palms python

### ISSUE THREAD

**Issue by Liampour** [google/mediapipe#3583]
Hello guys,
Is there a way to detect palms in python without detecting all hand landmarks ?

**Comment by kuaashish** [comment]
Hi @Liampour, Yes, You could take the palm_detection_tflite model (https://github.com/google/mediapipe/blob/master/mediapipe/modules/palm_detection/palm_detection_full.tflite) and use the standard tflite api to run it without Mediapipe in Python. Thank you!

**Comment by Liampour** [comment]
Hi @kuaashish 
Thank you for your quick reply!
I am a bit confused, could you give me more information about how to use this file?

**Comment by kuaashish** [comment]
Hi @Liampour, You can refer to this colab [example](https://github.com/shortcipher3/stackoverflow/blob/master/mediapipe_iris_2d_landmarks.ipynb) of iris tflite model implementation to use the palm detection tflite. Thank you!

**Comment by Liampour** [comment]
Hi @kuaashish 
Thank you for your help. I have also found this example useful https://github.com/aashish2000/hand_tracking?fbclid=IwAR2qPR5WQVVA2s_1dENWW8p_j3Siqclq4LlSfEgFYJNHy-9UHzz2c6Ld8Go

Is it possible to run palm_detection_tflite model with coral usb accelerator?

**Comment by kuaashish** [comment]
Hi @Liampour, Yes, Coral Usb accelerator is capable of running the tflite model with Python as example mentioned in [official_documentation](https://coral.ai/docs/edgetpu/tflite-python/#overview). You can follow the above example to build and run the palm_detection_tflite model on Edge device. Thank you!

**Comment by kuaashish** [comment]
Hi @kuaashish, Could you please confirm your query has been addressed as per the above [comment](https://github.com/google/mediapipe/issues/3583#issuecomment-1210207771) or need further assistance on the issue. Thank you!

**Comment by Liampour** [comment]
Hi @kuaashish, you have answered completely my questions. Thanks a lot for your time and your helpful responses

**Comment by kuaashish** [comment]
Hi @Liampour, Thanks for the confirmation, Can we move this issue to the close status. Thank you!
