### ISSUE TITLE
taking alarm for  a Certain pose

### ISSUE THREAD

**Issue by moahaimen** [google/mediapipe#3584]
Hi I need to make an alarm for a human in a certain pose in a video .mp4 from a movie, for example, if he lifts his arms 180 degrees towards the camera or horizontally, so I tried to take angles but couldn't
could you help me by code example

**Comment by LGuilhermeRodrigues** [comment]
180º is impossible in practice using my code because it ranges from 0º to 180º, but it would work with smaller values:
```
import numpy as np

a = np.array([right_hip.X,right_hip.Y,right_hip.Z]) 
b = np.array([right_shoulder.X, right_shoulder.Y, right_shoulder.Z])
c = np.array([right_elbow.X, right_elbow.Y,right_elbow.Z])

ba = a - b
bc = c - b

cosine_angle = np.dot(ba, bc) / (np.linalg.norm(ba) * np.linalg.norm(bc))
angle = np.arccos(cosine_angle)

if(np.degrees(angle)>145):
    print('arm is lifted')
```

**Comment by moahaimen** [comment]
thank you very much for answering,
can I take you to email to give you more explanation? please?

**Comment by moahaimen** [comment]
> 180º is impossible in practice using my code because it ranges from 0º to 180º, but it would work with smaller values:
> 
> ```
> import numpy as np
> 
> a = np.array([right_hip.X,right_hip.Y,right_hip.Z]) 
> b = np.array([right_shoulder.X, right_shoulder.Y, right_shoulder.Z])
> c = np.array([right_elbow.X, right_elbow.Y,right_elbow.Z])
> 
> ba = a - b
> bc = c - b
> 
> cosine_angle = np.dot(ba, bc) / (np.linalg.norm(ba) * np.linalg.norm(bc))
> angle = np.arccos(cosine_angle)
> 
> if(np.degrees(angle)>145):
>     print('arm is lifted')
> ```

https://www.youtube.com/watch?v=-Flb7eBK5Gs
for this video for example i need to take the shooting pose 
and give alarm for it i tried media pip but it didn't get the skeleton well
and the formula I think it would be harder
sorry for many question i just start learning python and deep learning with object detection 3 months ago 
thank you very much

**Comment by sureshdagooglecom** [comment]
Hi @moahaimen ,
Can you close this issue if it is resolved.
