### ISSUE TITLE
Not able to download its sources in Android studio

### ISSUE THREAD

**Issue by surapuramakhil** [google/mediapipe#3585]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 11, Android 12
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Java
- Installed using virtualenv? pip? Conda? (if python): No
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.10
- Bazel version:
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):  compile and target sdk 30
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): 
- OpenCV version (if running on desktop):

**Describe the problem**:
when I click on download sources in android studio bellow error message apprears

```
Attempt to download sources from Google

FAILURE: Build failed with an exception.

* Where:
Initialization script 'C:\Users\surap\AppData\Local\Temp\ijmiscinit4.gradle' line: 25

* What went wrong:
Execution failed for task ':app:DownloadSources'.
> Could not resolve all files for configuration ':app:downloadSources_2d3139e8-7c4b-44c8-a21e-f04ca146e13f'.
   > Could not find com.google.mediapipe:facedetection:0.8.10@aar.
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment]
Hi @surapuramakhil, Could you elaborate your query with complete details. Thank you!

**Comment by surapuramakhil** [comment]
@kuaashish 

Repro Steps
1. Try adding library to your android project
2. Now you can import classes etc
3. when you open library classes like "com.google.mediapipe.solutions.facedetection.FaceDetection" in Android studio. Now on top there would be an option to download sources (try doing that)

**Comment by kuaashish** [comment]
Hi @surapuramakhil, Could you please let us know if you successfully built MediaPipe as mentioned [here](https://google.github.io/mediapipe/getting_started/android.html#building-android-example-apps-with-bazel) and able to run the [Hello_world example](https://google.github.io/mediapipe/getting_started/install.html). If yes, Could you provide the [System information](https://google.github.io/mediapipe/getting_started/help.html) to look into the issue further.
Thank you!

**Comment by surapuramakhil** [comment]
Yes. I was able to run Hello world example

Updated system information in issue card

**Comment by kuaashish** [comment]
Hi @surapuramakhil, I was able to successfully reproduce the issue on the mentioned Operating System and device in Android Studio with no error. Could you please follow the steps mentioned in [official documentation](https://google.github.io/mediapipe/getting_started/android_solutions.html). Thank you!

**Comment by surapuramakhil** [comment]
I have done that. landed into issue after following mentioned in offical documentation

**Comment by kuaashish** [comment]
Hello @surapuramakhil,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
