### ISSUE TITLE
GPU Face detection is not working in ARM Mali G52 

### ISSUE THREAD

**Issue by moorthy-bs** [google/mediapipe#3587]
<em>GPU based desktop face detection is not working in the custom ARM platform with Mali G52 GPU (3 cores).
The running environment has 64 bit kernel and 32 bit rootfs.
mediapipe is built with 32 bit
Mali G52 supports Open GL 3.2
Tested the same solution in CPU version and it is working fine
<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Custom Linux with kernel 5.4.97
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.7
- Bazel version: 3.7.2
- Solution (e.g. FaceMesh, Pose, Holistic): Face Detection (Desktop)
- Graph config: mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt
- Programming Language and version ( e.g. C++, Python, Java): C++

**Describe the expected behavior:**
Expected:
- Output frame with annoted coordinates
- face coordinates to be obtained from face_detections output poller

Observed:
- output frame without face coordinates annotation
- face_detections output poller queue size is always zero so, `poller.Next(&packet)` hangs

**Other info / Complete Logs :**
Build failure:
Observed undefined reference for few GL APIs. few given for eg.

- glProgramUniformMatrix4fv
- glDisableVertexAttribArray
- glGenTextures

So, libmali is linked as given below
```
diff --git a/mediapipe/gpu/BUILD b/mediapipe/gpu/BUILD
index da53b98a..13ead426 100644
--- a/mediapipe/gpu/BUILD
+++ b/mediapipe/gpu/BUILD
@@ -79,6 +79,7 @@ GL_BASE_LINK_OPTS_OSS = GL_BASE_LINK_OPTS + select({
         # Ex: libegl1-mesa-dev libgles2-mesa-dev, or libegl1-nvidia libgles2-nvidia, etc...
         "-lGLESv2",
         "-lEGL",
+        "-lmali",
     ],
     "//mediapipe:android": [],
     "//mediapipe:ios": [],
```

In running environment, observed
- ImageFrame object creation is fine with SRGBA format
- texture creation is fine
- gpu_frame obtained and copied the input frame data
- status OK for AddPacketToInputStream()

GL info from execution log
```
I20211231 20:59:16.428643  8189 gl_context_egl.cc:170] Successfully initialized EGL. Major : 1 Minor: 4
I20211231 20:59:16.430573  8233 gl_context.cc:332] GL version: 3.2 (OpenGL ES 3.2 v1.r28p0-01eac0.d149eabd88b54d516647155d4b07afc7)
```

**Comment by sureshdagooglecom** [comment]
Hi @moorthy-bs ,
Could you provide steps to reproduce this issue.
