### ISSUE TITLE
How can i add my dataset in to Mediapipe?

### ISSUE THREAD

**Issue by Woong0416** [google/mediapipe#3588]
Hi guys 

I need some help to solve my issue 

I want to draw a landmark of the body part of the image with only the images of the arms and legs.
use by pose model in mediapipe 

then i need to add my legs and arms image in to tflite  right ? 

so how can i add my dataset ?? 

please help me ...

**Comment by sureshdagooglecom** [comment]
Hi @Woong0416 ,
For python you can create your own graph using the calculators and execute as mentioned here https://google.github.io/mediapipe/getting_started/python_framework.html#graph.
Have you looked at these closed issues https://github.com/google/mediapipe/issues/2761 and https://github.com/google/mediapipe/issues/507.

**Comment by Woong0416** [comment]
thank you for your answer i saw that page so then i make new graph ??

**Comment by sureshdagooglecom** [comment]
Yes , you can make new graph, please close the issue if resolved.

**Comment by Woong0416** [comment]
I'm sorry, but I don't know exactly what order to make the graph after seeing the article in the mediapipe you told me to look at. And if I finished making the graph, I would appreciate it if you could tell me how to use it.

**Comment by sureshdagooglecom** [comment]
Hi @Woong0416 ,
For python you can create your own graph using the calculators and execute as mentioned here https://google.github.io/mediapipe/getting_started/python_framework.html#graph.

**Comment by arianatri** [comment]
> Hi @Woong0416 , For python you can create your own graph using the calculators and execute as mentioned here https://google.github.io/mediapipe/getting_started/python_framework.html#graph.

this is not helping, we are asking to find out the wayt to train our custom models yet you show us the way to create graphs?!
