### ISSUE TITLE
Replace pose_detection.tflite with my own model.

### ISSUE THREAD

**Issue by mch0dmin** [google/mediapipe#3589]
If I want to replace pose_detection.tflite with my own pose detection model(eg. HRNet-Human-Pose-Estimation), what should I do to make it work?

Can you give me some advice？

Thanks very much.

**Comment by sureshdagooglecom** [comment]
Hi @mch0dmin ,
could you elaborate this issue to understand better.

**Comment by mch0dmin** [comment]
hi @sureshdagooglecom ,

Glad to receive your reply！

I want to do this : 

(1) First, I have a model of human pose estimation, eg. https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/human-pose-estimation-3d-0001 or https://github.com/HRNet/HRNet-Human-Pose-Estimation.

(2)  And then I convert these pose estimation models to .tflite format, eg. **hrnet.tflite.** ( Because the example in mediapipe uses the .tflite model.)

(3) Now i want to run mediapipe/examples/desktop/pose_tracking:pose_tracking_cpu, but i don't use default model pose_detection.tflite, which is provided by mediapipe. Instead, use the model I converted to replace it.

I have made some attempts, but I have encountered mistakes. I don't know whether this is feasible, or what model needs to be used to replace the model provided by mediapipe.

Thank you again for your reply.

**Comment by mch0dmin** [comment]
hi @sureshdagooglecom, can you give me some advice? Thanks!

**Comment by guker** [comment]
> hi @sureshdagooglecom, can you give me some advice? Thanks!

pose_detection.tflite predict a box and four keypoint,  do your model can predict a box and four keypoint? if not, your model cant be used.

**Comment by sureshdagooglecom** [comment]
Hi @mch0dmin ,
Modesl detects box and four keypoint.

**Comment by miaochx** [comment]
hi @guker and @sureshdagooglecom Thank you very much for your answers. Is there any way that I can get a similar model?

**Comment by mch0dmin** [comment]
hi @guker and @sureshdagooglecom ，
Thank you very much for your answers. Is there any way that I can get a similar model?

**Comment by sureshdagooglecom** [comment]
Hi @mch0dmin ,
We don't provide similar models .
