### ISSUE TITLE
3d model in desktop hand tracking CPU

### ISSUE THREAD

**Issue by ChuyiZhong** [google/mediapipe#359]
Hi all
I am trying to get 3d coordinates in hand tracking desktop CPU model. And I have changed the path from hand_landmark.tflite to hand_landmark_3d.tflite in hand_landmark_cpu.pbtxt.
But I still can't get the values in Z axis, only x and y values are shown.
Did I miss something?
All help are appreciated.

**Comment by mgyong** [comment]
@ChuyiZhong This is solved in #202
