### ISSUE TITLE
Handtracking with edge device

### ISSUE THREAD

**Issue by Masterythepua** [google/mediapipe#3592]
Hello guys,
Can the hand tracking model be used on a device like raspberry pi with an edge device like Coral TPU?
Thanks

**Comment by kuaashish** [comment]
Hi @Masterythepua, Hand tracking model is currently not available on the Edge devices. MediaPipe has limited resources for new features. We will let you know if there is any specific update on this request. 

You can refer to this issue [#426](https://github.com/google/mediapipe/issues/426) and [#426(comment)](https://github.com/google/mediapipe/issues/426#issuecomment-581536031) for more information.  Thank you!

**Comment by Masterythepua** [comment]
Hi @kuaashish 
I use the handtracking model to achieve gesture control of raspberry pi
When I use the handtracking model with raspberry pi I have 10 FPS. Is there a way to increase the FPS to 15 or 20?

**Comment by kuaashish** [comment]
Hi @Masterythepua, This gives you better understanding [#3158 (comment)](https://github.com/google/mediapipe/issues/3158#issuecomment-1063689196). Thank you!

**Comment by kuaashish** [comment]
Hi @Masterythepua, Thank you for the confirmation. Can we move this issue to close status if it does not need further assistance. Thank you!
