### ISSUE TITLE
Inferencing queries

### ISSUE THREAD

**Issue by SoumyajitMukherjee-droid** [google/mediapipe#3594]
Can the model infer on CPU or only on GPU?
Can it infer high resolution image or at max, what resolution of the image can be inferred
Can the model perform the 3D pose estimation
Also share the Inference Speed in FPS

**Comment by sureshdagooglecom** [comment]
Hi @SoumyajitMukherjee-droid 
Could you please check [this](https://google.github.io/mediapipe/solutions/pose.html) document ,it contains all the answers for your questions.
