### ISSUE TITLE
Bitmap passed to FaceDetector and bitmap returned by FaceDetectionResult.inputBitmap() isn't same object and data

### ISSUE THREAD

**Issue by surapuramakhil** [google/mediapipe#3595]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
- Programming Language and version ( e.g. C++, Python, Java):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ):
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
- Xcode & Tulsi version (if issue is related to building for iOS):

**Describe the current behavior:**
I have performed hashCode check and equal check between Bitmap passed to face Detector (com.google.mediapipe.solutions.facedetection.FaceDetection) and inputBitmap() returned from FaceDetectionResult 

both are Not matching

Here is the output:
```
D/: input bitmap hashcode: 128811049
D/: inputBitMap() from FaceDetectionResult Hashcode: 178405294
D/: hashCode integer comparison: -1
D/: Bitmap object comparison: false
```
 

**Describe the expected behavior: **
both should be same.  Both Bitmaps should have same hashCode() and should also satisfy equal's condition

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

**Comment by sureshdagooglecom** [comment]
Hi @surapuramakhil ,
You can try using this below code to input a image or video and display the graph on top of it.
https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/solutions/facemesh/src/main/java/com/google/mediapipe/examples/facemesh/MainActivity.java#:~:text=%7D)%3B-,Button%20loadImageButton%20%3D%20findViewById(R.id.button_load_picture)%3B,%7D,-/**%20The%20core%20MediaPipe

**Comment by surapuramakhil** [comment]
I will try this and let you know.
Incorrect platform marked to this issue - Platform is Android 12 (Pixel 5A) device

**Comment by sureshdagooglecom** [comment]
Hi @surapuramakhil ,
Can you close the issue if you have got the resolution.
