### ISSUE TITLE
Obtain 'detection_confidence' and 'tracking-confidence' of PoseLandmarks for each frame

### ISSUE THREAD

**Issue by LNMBTL** [google/mediapipe#3597]
Hello, I am doing pose tracking on python. I have two questions about this:
1) Is it possible to get the 'detection_confidence' and 'tracking_confidence' for each frame? If so, how?
2) How is it possible that in "results" I still have access to the information "PoseLandmarks" even for landmarks that have not been 
detected, or that are not visible in the frame? For example, in the image below, my ankles are hidden by the table, but with a print I manage to have pose the landmark  of my left ankle and I have a value. How is it possible ?

    if results.pose_landmarks:
      print(
          f'Nose coordinates: ('
          f'{results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_ANKLE].x * image_width}, '
          f'{results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_ANKLE].y * image_height})'
      )

Thank you very much!

<img width="601" alt="Capture" src="https://user-images.githubusercontent.com/16302683/184101224-f2c490e8-861c-4474-9f38-09651c41df97.PNG">

**Comment by sureshdagooglecom** [comment]
Hi @LNMBTL ,
Could you elaborate this issue to investigate better on this issue.

**Comment by LNMBTL** [comment]
Hello, sorry I'm not sure to understand,  you want me to give you more details  ?

**Comment by sureshdagooglecom** [comment]
Hi @LNMBTL ,
Could you please refer this closed issue https://github.com/google/mediapipe/issues/1620 , please check and revert back.
