### ISSUE TITLE
Adding support to fine-tune models?

### ISSUE THREAD

**Issue by ahmed-shariff** [google/mediapipe#360]
Are there any plans to allow fine-tuning the models for specific needs? Or will it be possible to share the training code?

**Comment by mgyong** [comment]
@ahmed-shariff There is no plan to share the training code or the dataset (due to privacy issues) for any of the MediaPipe example TF models

**Comment by cagcoach** [comment]
@mgyong are there plans for a (probably paid) fine-tune service, so that I can upload somewhere my training data and get an optimized model back? I'm working with the 3D Human Pose Estimator and some moves I try to detect seem to be out of scope...
