### ISSUE TITLE
How to remove some http_archive libraries? But use local installed packages instead?

### ISSUE THREAD

**Issue by jiapei100** [google/mediapipe#3600]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution: Ubuntu 22.04
- Compiler version: gcc/g++ 11.2.0
- Programming Language and version: C++20, Python3.10.4
- Installed using virtualenv? pip? Conda? (if python): build from source
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.10.2
- Bazel version: 5.2 
- XCode and Tulsi versions (if iOS): N/A
- Android SDK and NDK versions (if android): N/A
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): N/A
- OpenCV version (if running on desktop): 4.6.0

**Describe the problem**:
After having doublechecked **WORKSPACE**, I commented out a bunch of **http_archive**s which needs to be downloaded and rebuilt ??? However, I've already had most of the packages installed. In such, there should be a way to use **local libraries** directly, rather than **downloading from http_achive**. 

**My question: how ?** Thank you very much.

**Complete Logs:**
```console
➜  mediapipe git:(master) ✗ bazel run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
    mediapipe/examples/desktop/hello_world:hello_world
INFO: Build options --copt and --define have changed, discarding analysis cache.
ERROR: ....../mediapipe/mediapipe/examples/desktop/hello_world/BUILD:19:10: error loading package 'mediapipe/framework': at ....../mediapipe/mediapipe/framework/port/build_config.bzl:6:6: Unable to find package for @com_google_protobuf//:protobuf.bzl: The repository '@com_google_protobuf' could not be resolved: Repository '@com_google_protobuf' is not defined. and referenced by '//mediapipe/examples/desktop/hello_world:hello_world'
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.318s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (41 packages loaded, 159 targets configured)
FAILED: Build did NOT complete successfully (41 packages loaded, 159 targets configured)
    currently loading: mediapipe/framework ... (2 packages)
```

**Comment by kuaashish** [comment]
Hi @jiapei100, Have you looked at this issue [#SO](https://stackoverflow.com/questions/72288867/include-c-library-in-bazel-project) to add external library from outside of workspace into bazel. Thank you!
