### ISSUE TITLE
uv_texture map the mesh error

### ISSUE THREAD

**Issue by zw20045500** [google/mediapipe#3602]
https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model.obj
https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt

I get uv from canonical_face_model.obj and uv from geometry_pipeline_metadata_landmarks.pbtxt, and build the PiecewiseAffineTransform from the two uv. and then warp the image , so i can get the face texture. (python)

but i don't know how to mapper the mesh(for example canonical_face_model.obj), i add put the face texture on canonical_face_model.obj directly, it's not ok.

I saw the issue https://github.com/google/mediapipe/issues/1698, but i still not clear how mapper the the face texture to myself mesh.

**Comment by kuaashish** [comment]
Hi @zw20045500, Have you looked at this [#1698(comment)](https://github.com/google/mediapipe/issues/1698#issuecomment-794814532), mentioned the clear steps to export face as UV texture map. Meanwhile you could follow the UV texture implementation example in Python [here](https://github.com/apple2373/mediapipe-facemesh/blob/main/main.ipynb). 
Thank you!

**Comment by zw20045500** [comment]
Hi kuaashish, thank your reply.
Yes, i implemented with reference to his example. 
But I want to put uv map into my customize mesh base on  canonical_face_model(I add more verts and faces).
So i dont't how to map. His example is base on canonical_face_model, I want to implement to put vu(make from mediapipe) to map my customize mesh.
Could you provide me with some guidance about how to solve by python? thanks

**Comment by kostyaby** [comment]
Hey @zw20045500,

If you have your own mesh (you mention adding vertices and faces), you're now responsible for synchronizing between (A) the canonical mesh UV 2D space and (B) the new mesh UV 2D space. I'm afraid there is no silver bullet here; you basically need to make sure the two UV coordinate systems are "aligned" with each other. I expect this to be a fairly manual process

As a good start, pls try visualizing UV coordinates for (A) (should look like [this](https://developers.google.com/static/ar/images/canonical-face-texture-photoshop.jpg)) with red color and for (B) with blue color on a single texture 1024x1024. If no good mapping currently exists, you should see the red topology not matching the blue topology. Your next step would be to modify the blue topology (=derived from your own mesh) to "look alike" the red topology. Once they are more-or-less synchronized, you should see that transferring textures from (A) to (B) should give good visual results. Again, this will be an ad-hoc manual process, not much guidance I can provide there

**Comment by kuaashish** [comment]
Hi @zw20045500, Could you please go through the [above comment](https://github.com/google/mediapipe/issues/3602#issuecomment-1237657056). Thank you!

**Comment by zw20045500** [comment]
@kostyaby thank you guidance very much

**Comment by wizVR-zhangjun** [comment]
@zw20045500 
![boy2](https://user-images.githubusercontent.com/60952586/196132456-7c3d1847-887d-43df-b6ba-b60bae1a632a.jpg)
![1663921773162](https://user-images.githubusercontent.com/60952586/196132481-3740c026-7a29-4488-8c11-e205bd9d984a.png)
Is that what you want?

**Comment by zw20045500** [comment]
@wizVR-zhangjun 
I want to get face uv by mediapipe to my customsize mesh.  can you give me your email address, we can comminicate deeply. Thank you!
