### ISSUE TITLE
Streams connection when re-using subgraphs

### ISSUE THREAD

**Issue by serrabii** [google/mediapipe#3603]
Hi,

According to the docs, the outputs from some calculators are connected to the inputs of other calculators using named streams.

However it is unclear to me how the connections are made when re-using a subgraph. 

For example, the subgraph [FaceDetectionShortRangeCpu](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_detection/face_detection_short_range_cpu.pbtxt) has an output stream called **detections**. But it is later re-used in the graph [face_detection_desktop_live](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/face_detection_desktop_live.pbtxt) with an output stream called **face_detections**.

Thank you!

**Comment by sureshdagooglecom** [comment]
Hi @serrabii ,
We have similar issue on thread https://github.com/google/mediapipe/issues/783, please check this and revert back.
