### ISSUE TITLE
Hardware for handtracking

### ISSUE THREAD

**Issue by Masterythepua** [google/mediapipe#3605]
Hi 
I am looking for single board computer to run Mediapipe to perform live hand tracking.
Some suggestions are raspberry pi 4 or nvidia Jetson Nano.
Which of the two can achieve higher fps?
Any other board suggestion is welcome 
Thanks!

**Comment by sureshdagooglecom** [comment]
Hi @Masterythepua ,
Rasberry pi gives higher fps and you an also try with OAK-D, OAK-D lite, OAK-1.
