### ISSUE TITLE
How to compute nose, left head, right head transform matrix

### ISSUE THREAD

**Issue by dandingol03** [google/mediapipe#3606]
**Background:**
Hi, i am glad to know this amazing ai repo. Recently, i use mediapipe as ai engine to inference 3d face landkmark and [filament](https://github.com/google/filament) as my 3d rendering engine.  I use these two engine to implement ar 3d sticker
**Question:**
After i read the blog about [MediaPipe 3D Face Transform](https://developers.googleblog.com/2020/09/mediapipe-3d-face-transform.html) , i know the pos matrix is used to find the best suitable transform matrix to transform `Canonical Face Model `to runtime face model. So is there any possible i can compute the nose, lefthead, righthead transform matrix? I need these trasnform matrix to position different part of 3d sticker, such as a nose decoration.

**Comment by sureshdagooglecom** [comment]
Hi @dandingol03 ,
We have closed this similar issue https://github.com/google/mediapipe/issues/1457 , please check and revert back.
