### ISSUE TITLE
Error in box_tracker_calculator.cc

### ISSUE THREAD

**Issue by Ar4enal** [google/mediapipe#3609]
I build an Android AAR for **[Box Tracking]** and I got this error in box_tracker_calculator.cc

`Box at time 1 already present; ignoring`
`Box at time 2 already present; ignoring`
`Box at time 3 already present; ignoring`

https://github.com/google/mediapipe/blob/cc6a2f7af65977248b2a15f471503da2832f583a/mediapipe/calculators/video/box_tracker_calculator.cc#L381-L388

And the number keeps increasing.

I can not understand these codes. Can someone explain this error part code?

**Comment by sureshdagooglecom** [comment]
Hi @Ar4enal ,
Can you please provide steps to reproduce this issue.
