### ISSUE TITLE
How to simplify the process for extracting the youtube8M features？

### ISSUE THREAD

**Issue by yw2278** [google/mediapipe#361]
Is it possible to just use one model to do the extraction? without the meidapipe frame?

**Comment by jiuqiant** [comment]
Yes, it should be possible to do the feature extraction by using the VGGish and Inception models directly. If you are interested in reproducing the feautre extraction pipeline, feel free to take a look at [the feature extraction graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/youtube8m/feature_extraction.pbtxt) and choose your favitore language to do it. I feel sorry that we won't be able to do this becuase it's beyond MediaPipe's scope.
