### ISSUE TITLE
Shoe Try-On

### ISSUE THREAD

**Issue by vikarshiitk** [google/mediapipe#3610]
I want to put a 3D model of shoe on a bare foot in Augumented Reality and render it according to the foot movement . can you share some resorces related to this.

**Comment by PrinceP** [comment]
@vikarshiitk   Hope this helps - https://github.com/PrinceP/congenial-system

**Comment by honeykinng345** [comment]
Hey Team I have successfully built 3d shoe object detection. now please anyone tell me how I can add a 3d shoe mask to my feet? I have the shoe obj file. and I replace it with the current obj file(module.obj.uuu) that is in the sneaker asset folder. but not working. same as issue https://github.com/google/mediapipe/issues/1453. @ahmadyan,...

**Comment by vikarshiitk** [comment]
> @vikarshiitk Hope this helps - https://github.com/PrinceP/congenial-system

thanx

**Comment by gopig99** [comment]
> @vikarshiitk Hope this helps - https://github.com/PrinceP/congenial-system

Is there any example in python, where it does the same application of shoe try on?

**Comment by sprengerst** [comment]
+1

**Comment by jianingwei** [comment]
The uuu file format is probably a special one for encryption purposes. Adel, do you have more information around this?

**Comment by burungiu** [comment]
Did someone solved this one?

**Comment by leolima** [comment]
> @vikarshiitk Hope this helps - https://github.com/PrinceP/congenial-system

didnt help.
