### ISSUE TITLE
243 named landmarks and 225 missing from (outdated) keypoints.ts

### ISSUE THREAD

**Issue by jordan-bird** [google/mediapipe#3612]
Hello,

Is there a newer version of keypoints.ts? There doesn't seem to be one in this repo. 

https://github.com/tensorflow/tfjs-models/blob/838611c02f51159afdd77469ce67f0e26b7bbb23/face-landmarks-detection/src/mediapipe-facemesh/keypoints.ts

In this older version, we can take 243 landmarks to identify which part of the face the point exists on. There are 225 without names though, can they be found anywhere? The names would be useful to explore which parts of the face carry the most information for biometrics etc. rather than just referring to their index

For example, indices 455 through 462 don't exist in that older version, and then 463 through to the end 467 refer to the leftEyeLower (1 index 8, 2 index 8, 3 index 8) and leftEyeUpper (0 index 0, 1 index 0)

Thanks!

**Comment by kuaashish** [comment]
Hi @jordan-bird, This issue is more related to the tensorflow. Could you please raise this request into the [tensorflow-repo](https://github.com/tensorflow/tensorflow/issues). Thank you!

**Comment by jordan-bird** [comment]
@kuaashish I don't think this is a tensorflow issue, the landmarks and their labels are MediaPipe related

**Comment by kuaashish** [comment]
Hi @jordan-bird, 
Could you please elaborate your query with complete details and different observations made in the both of cases. 
Thank you!
