### ISSUE TITLE
Holistic Performance does not meet

### ISSUE THREAD

**Issue by ar0127** [google/mediapipe#3615]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
  1. My code based on your example [mediapipe/examples/android/src/java/com/google/mediapipe/]
  2. I add  addMultiStreamCallback to check performance as :
  
```
             processor.getGraph().addMultiStreamCallback(
                OUTPUT_LANDMARKS_STREAM,
                packets -> {
                    Packet packet = packets.get(0);

                    long currTimeMs = System.currentTimeMillis();
                    float fps = 1000 / (currTimeMs - oldTimeMs);

                    float avr = getFpsAverage(fps);

                    if (packet.isEmpty()) {
                        Log.i(TAG, "[0] report rate : " + fps + ", " + avr);
                    } else {
                        Log.i(TAG, "[1] report rate : " + fps + ", " + avr);
                    }

                    oldTimeMs = currTimeMs;
                });
```

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
  Linux Ubuntu 22.04

- [MediaPipe version](https://github.com/google/mediapipe/releases):
  [v0.8.10.2](https://github.com/google/mediapipe/tree/v0.8.10.2)

- Bazel version:
  bazel 5.2.0

- Solution (e.g. FaceMesh, Pose, Holistic):
  Holistic

- Programming Language and version ( e.g. C++, Python, Java):
 android (c++, Java)

**Describe the expected behavior:**
I expected It worked over 20 fps on device, but It worked under 10 fps when all landmarks(face, body pose, hand) were detected.
it was mentioned your blog : https://ai.googleblog.com/2020/12/mediapipe-holistic-simultaneous-face.html
My chipset is qcs8250 (I think my device is better than S9+)

:56:49.479 7373-7430/com.lge.myholistic I/MainActivity: [1] report rate : 7.0, 7.4
2022-07-29 10:56:49.608 7373-7426/com.lge.myholistic I/MainActivity: [1] report rate : 7.0, 7.4
2022-07-29 10:56:49.751 7373-7429/com.lge.myholistic I/MainActivity: [1] report rate : 6.0, 7.1
2022-07-29 10:56:49.878 7373-7429/com.lge.myholistic I/MainActivity: [1] report rate : 7.0, 7.1
2022-07-29 10:56:50.002 7373-7431/com.lge.myholistic I/MainActivity: [1] report rate : 8.0, 7.2
2022-07-29 10:56:50.137 7373-7430/com.lge.myholistic I/MainActivity: [1] report rate : 7.0, 7.2
2022-07-29 10:56:50.253 7373-7431/com.lge.myholistic I/MainActivity: [1] report rate : 8.0, 7.2
2022-07-29 10:56:50.365 7373-7429/com.lge.myholistic I/MainActivity: [1] report rate : 9.0, 7.5
2022-07-29 10:56:50.488 7373-7426/com.lge.myholistic I/MainActivity: [1] report rate : 8.0, 7.5
2022-07-29 10:56:50.615 7373-7431/com.lge.myholistic I/MainActivity: [1] report rate : 7.0, 7.4
2022-07-29 10:56:50.740 7373-7432/com.lge.myholistic I/MainActivity: [1] report rate : 8.0, 7.5
2022-07-29 10:56:50.865 7373-7432/com.lge.myholistic I/MainActivity: [1] report rate : 7.0, 7.5
2022-07-29 10:56:50.985 7373-7433/com.lge.myholistic I/MainActivity: [1] report rate : 8.0, 7.7

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by ar0127** [comment]
addtionally,

I wrote BUILD file to make aar:

```
load(
    "//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl",
    "mediapipe_aar"
)

mediapipe_aar(
    name = "mediapipe_holistic_lge",
    calculators = ["//mediapipe/graphs/holistic_tracking:holistic_tracking_gpu_deps"],
)
```

**Comment by sureshdagooglecom** [comment]
Hi @ar0127 ,
Do you have still issue w.r.t this issue?

**Comment by ar0127** [comment]
Hi @sureshdagooglecom 

Yes, I have this issue still.

I built aar and I used it with your holistic graph with no modification.
I just followed your guide.

I want to get your opion to improve performance.

thanks

**Comment by ar0127** [comment]
Hi @sureshdagooglecom 

I reopened the issue.
I didn't know the the issue closed when i wrote comment.

**Comment by sureshdagooglecom** [comment]
Hi @ar0127 ,
Could you please share complete w.r.t above issue.
