### ISSUE TITLE
Only need landmark points but not rendering or SurfaceView

### ISSUE THREAD

**Issue by HOLDfoot** [google/mediapipe#3620]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)
Any android device

- MediaPipe Solution (you are using): Pose
- Programming language : Android Java
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state:**
Can we get only the landmark points but not rendering

**Will this change the current api? How?**
Remove surfaceview

**Who will benefit with this feature?**
Person who need only landmark

**Please specify the use cases for this feature:**
For android TV developer. Their screen may run otherthing. mediapipe will run on background.

**Any Other info:**
![截图](https://user-images.githubusercontent.com/12047708/185525495-34fb4792-accd-41a3-9931-74cae97cd1c0.png)
Why manay simillar issue isn't fixed but is closed.
I wan't to konw the answer about 
'''
Can we get only the landmark points but not rendering

'''
Reference link: https://github.com/google/mediapipe/issues/348

**Comment by wangrenzhu** [comment]
You can do it yourself
use CalculatorGraph start custom graph
Custom graph:
add landmark output


`# MediaPipe graph that performs face mesh with TensorFlow Lite on GPU.

# GPU buffer. (GpuBuffer)
input_stream: "input_video"

# Max number of faces to detect/process. (int)
input_side_packet: "num_faces"

# Output image with rendered results. (GpuBuffer)
output_stream: "output_video"
# Collection of detected/processed faces, each represented as a list of
# landmarks. (std::vector<NormalizedLandmarkList>)
output_stream: "multi_face_landmarks"

# output_stream: "face_detections"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Defines side packets for further use in the graph.
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:with_attention"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet { bool_value: true }
    }
  }
}

# Subgraph that detects faces and corresponding landmarks.
node {
  calculator: "FaceLandmarkFrontGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "NUM_FACES:num_faces"
  input_side_packet: "WITH_ATTENTION:with_attention"
  output_stream: "LANDMARKS:multi_face_landmarks"
  output_stream: "ROIS_FROM_LANDMARKS:face_rects_from_landmarks"
  output_stream: "DETECTIONS:face_detections"
  output_stream: "ROIS_FROM_DETECTIONS:face_rects_from_detections"
}

node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  # input_stream: "detections_render_data"
  # input_stream: "VECTOR:0:multi_face_landmarks_render_data"
  # input_stream: "rects_render_data"
  output_stream: "IMAGE_GPU:output_video"
}
`

**Comment by kuaashish** [comment]
Hi @HOLDfoot, Have you looked at the mentioned closed issue [#348(comment)](https://github.com/google/mediapipe/issues/348#issuecomment-1007103756), shared the workaround to get only landmarks points. Thank you!
