### ISSUE TITLE
Better handling on situations where the camera isn't allowed/exists

### ISSUE THREAD

**Issue by codingMASTER398** [google/mediapipe#3621]
**System information**
- MediaPipe Solution (you are using): Hands (specifically the camera_utils)
- Programming language : JavaScript
- Are you willing to contribute to it (Yes/No): No

**Describe the feature and the current behavior/state:**
Right now if the browser does not allow the camera to be used in the webpage, the `camera_utils` module handles the error by using the browser's built-in `alert` feature and throwing it (however having it not able to be caught via a try/catch in `new Camera` or `camera.start`)

How it handles it now:
```js
.catch(function(f){var h="Failed to acquire camera feed: "+f;console.error(h);alert(h);throw f;})
```

Browser:
![image](https://user-images.githubusercontent.com/55938439/185737434-d6dbf195-aa7a-4dfc-be9c-b709bb4daac5.png)
This means that you are unable to create visually appealing error messages or easily catch them through conventional methods.

**Will this change the current api? How?**
Possibly a `.onError` or removing the `alert` and allowing it to be caught on `new Camera` or `camera.start`

**Who will benefit with this feature?**
Developers using the `camera_utils` module in their web project will be able to catch an error with more ease and without the browser's limited `alert` feature.

**Please specify the use cases for this feature:**
Chopping off technical information and giving the user a better alert that the developer can customise, or any other sort of method conveying the message, so the end user has a better understanding of what they did wrong.

**Any Other info:**
Camera setup code:
```js
const camera = new Camera(videoElement, {
  onFrame: async () => {
    await hands.send({ image: videoElement });
  },
  width: 1280,
  height: 720
});
camera.start();
```

**Comment by ayushgdev** [comment]
@codingMASTER398 
Thanks for raising this issue. The feature request indeed is an important one  to allow users to handle exceptions at their front. We will make sure to discuss and prioritize it in our roadmap.

**Comment by kuaashish** [comment]
Hello @codingMASTER398,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
