### ISSUE TITLE
offer another PyPi build that includes more models, or another method to use heavy model without download?

### ISSUE THREAD

**Issue by M00NSH0T** [google/mediapipe#3622]
I'm trying to use mediapipe in a GCP cloud function (Python). My biggest issue is that I want to use models other than the default model (complexity=1) for pose landmark detection. I'm most interested in getting a better segmentation mask from the pose object, so I'd like to opt for the complexity=2 model, but the problem is that this model is not included in the package by default, and the ```_download_oss_pose_landmark_model(model_complexity)``` function that gets called when you create a pose object doesn't have the permissions it needs within a GCP cloud function. Plus, I'd rather not have to download a model every time I run the function from a fresh instance...

I created a fork where I downloaded/included the appropriate model I wanted and commented out the call to download the model, but I can't figure out how I can include this in my cloud function. I tried building it again and included it within my cloud function's zip file, but it didn't work. I tried linking to my GitHub repo within the requirements.txt, that failed as well. 

The solution I'd love would be if you could create an official 'mediapipe-full' package that includes all the tflite models and put that on PyPi. Would that be possible?

Or do you have any other suggestions for how I might use mediapipe in a cloud function using a 'heavy' model or any other model other than the default one?

thanks!

**Comment by M00NSH0T** [comment]
and just to clarify the bug I get when I try building it myself, it looks like the same bug that people were getting when trying to install on a raspberry pi, namely:

```ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'```

I built it in Ubuntu, then moved the directory from site-packages into my working python directory within the zip file I use to create the Cloud Function. The error above is what shows up in the logs.

**Comment by M00NSH0T** [comment]
one other solution I just thought of could be to enable users to specify a custom path to whatever model they want to use, instead of just complexity=[0,1,2].

**Comment by sureshdagooglecom** [comment]
Hi @M00NSH0T ,
Do you have still problem w.r.t above issue.

**Comment by M00NSH0T** [comment]
Hi @sureshdagooglecom,
Yes I never figured this out. I've got a clunky alternative solution I've been using in the meantime, but I'd really love to be able to use other models than the default complexity=1 model from a cloud function. But I haven't been able to figure out a viable solution. Any help would be appreciated.
thanks!

**Comment by kuaashish** [comment]
Hello @M00NSH0T,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
