### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tmtcam-042** [google/mediapipe#3623]
https://github.com/google/mediapipe/blob/63e679d99ca45b30514a9d84c9351a2d77bb9ba0/mediapipe/python/solutions/drawing_styles.py#L57
https://github.com/google/mediapipe/blob/63e679d99ca45b30514a9d84c9351a2d77bb9ba0/mediapipe/python/solutions/drawing_styles.py#L40

Minor typo in python drawing_styles.py - _PALM_LANMARKS should be _PALM_LANDMARKS

**Comment by sureshdagooglecom** [comment]
Hi @tmtcam-042 ,
Could you share steps to reproduce this issue.

**Comment by kuaashish** [comment]
@tmtcam-042,
Thanks for the finding out this bug! This issue has fixed now commit [921b6a6](https://github.com/google/mediapipe/commit/921b6a6befae381ba873fb61ba170d902a1c6b02) recently.
