### ISSUE TITLE
Mac M1 pip can not found media pipe python package from pip

### ISSUE THREAD

**Issue by lucasjinreal** [google/mediapipe#3629]
Mac M1 pip can not found media pipe python package from pip.

Anyway can I install directly from pypi?

**Comment by sureshdagooglecom** [comment]
Hi @jinfagang ,
M1 is not currently supported.

**Comment by jinfagang** [comment]
Is there any plan to support M1?

**Comment by sureshdagooglecom** [comment]
Hi @jinfagang .
Yes, we have plan to support on this and Google team is working on it.

**Comment by jinfagang** [comment]
@sureshdagooglecom that would be awesome, any timeline on when will we have a version?

**Comment by kuaashish** [comment]
Hi @jinfagang, Have you looked at this closed issue #3656 and [#3656(comment)](https://github.com/google/mediapipe/issues/3656). Could you try the command mentioned in the [comment](https://github.com/google/mediapipe/issues/3656). Please let us know if this resolves the issue. Thank you!

**Comment by jinfagang** [comment]
@kuaashish hi, thanks, it worked, haven't tried if it can inference or not,  can this directly using for ifnerence?

**Comment by kuaashish** [comment]
Hi @jinfagang, MediaPipe team has plans to support the M1 officially and are working on it but don't have much info on this.  Meanwhile this forked from MediaPipe branch must work as expected. Thank you!

**Comment by ayushgdev** [comment]
Hello @jinfagang 
Support for Python package installation via pip for Mac M1 has been released in v0.9.3.0. Please make sure to use Python >=v3.8.
