### ISSUE TITLE
Shoes 3d model

### ISSUE THREAD

**Issue by honeykinng345** [google/mediapipe#3631]
Hey all, can anyone please share me the shoes detect 3d model app repo using media pipe ...

**Comment by sureshdagooglecom** [comment]
Hi @honeykinng345 ,
We have offiicial document to detect 3d model for shoes and other objects , please check [this](https://google.github.io/mediapipe/solutions/objectron.html) document.

**Comment by honeykinng345** [comment]
hey, thanks for the reply ... I downloaded the sample code and followed all
these instructions mentioned on the official media pipe documentation but
did not run the sample 3d object code.

**Comment by sureshdagooglecom** [comment]
Hi @honeykinng345 ,
What is the error you are gettiong , could you please share logs to understand better on this issue.

**Comment by honeykinng345** [comment]
> Hi @honeykinng345 , What is the error you are gettiong , could you please share logs to understand better on this issue.

@sureshdagooglecom I have resolved this issue now(the issue is the android version I have set the android version into a works space file and installed the Java then it's working )

**Comment by sureshdagooglecom** [comment]
Hi @honeykinng345 ,
Can you close this issue if you have got the resolution.
