### ISSUE TITLE
Memory access out of bounds error while tracking Hands on Samsung Internet (on samsung device)

### ISSUE THREAD

**Issue by Adkaros** [google/mediapipe#3633]
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): **No, happens in mediapipe codepen example**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): **Android 12.0 (Samsung phones specifically, see known devices in Other Info)**
- [MediaPipe version](https://github.com/google/mediapipe/releases): **@mediapipe/hands@0.4.1646424915**
- Solution (e.g. FaceMesh, Pose, Holistic): **Hands**
- Programming Language and version ( e.g. C++, Python, Java): **JS / Web**

**Describe the expected behavior:**
User tracks hand within camera feed without mediapipe crashing / disappearing while using Samsung Internet browser.

**Standalone code you may have used to try to get what you need :**
None, this is occurring with the base demo, it does work if the user sets the Smart anti-tracking setting to "Never"

**If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:**
1). With a samsung phone, open [mediapipe hands codepen](https://codepen.io/mediapipe/pen/RwGWYJw ), with Samsung Internet browser
2). Once tracking begins, position hand in frame
3). Wait for tracking to stop or disappear, or if an error is seen in the inspector window (can debug from chrome://inspect/#devices on your PC)

**Other info / Complete Logs :**
Known devices with issue: **s22, s22+, s21 fe, flip3, fold3**

This issue seems to be happening with phones that have the Snapdragon chipset, although I'm not sure if it's conclusive (ie. might not be a factor, but it seems to work on exyonos chipset from our limited testing on those phones)

With the affected phones, I've noticed that turning the Smart anti-tracking setting to "Never" seems to fix the issue. That being said, the default setting is "Always", I'm looking for a potential work-around here that wouldn't require users to change the setting manually. (the setting can be found at samsung internet settings -> browsing privacy dashboard -> smart antitracking)

**Log of error**
[codepen.io-1661371161061.log](https://github.com/google/mediapipe/files/9419082/codepen.io-1661371161061.log)

**Screenshot of error, most relevant being the bottom error, top errors don't appear to affect tracking**
![mediapipe_error_samsunginternet](https://user-images.githubusercontent.com/7696222/186511306-a380f811-3084-43f6-ae0b-c3be63897b1c.png)

**Comment by kuaashish** [comment]
Hi @Adkaros, Have you looked at this similar closed issue #2188 and [#2188(comment)](https://github.com/google/mediapipe/issues/2188#issuecomment-899911783). Thank you!

**Comment by Adkaros** [comment]
> Hi @Adkaros, Have you looked at this similar closed issue #2188 and [#2188(comment)](https://github.com/google/mediapipe/issues/2188#issuecomment-899911783). Thank you!

Hey @kuaashish, thanks for the reply, I checked the chrome version on the phones I have and one was up to date, and the other I updated and re-tested, but still crashes on samsung internet (chrome never crashes with the demo or hand tracking). I also updated samsung internet browser but still crashes with newest version

**Comment by kuaashish** [comment]
Hi @Adkaros, Currently MediaPipe does not support the Samsung Internet Browser. MediaPipe has tested on [this](https://google.github.io/mediapipe/getting_started/javascript.html#supported-plaforms) platform successfully.  
MediaPipe has limited resources for new features. We will let you know if there is any specific update on this request. 
Thank you!
