### ISSUE TITLE
error generated while building with docker on mac os 

### ISSUE THREAD

**Issue by bloodgroup-cplusplus** [google/mediapipe#3636]
[10/14] RUN pip3 install tensorflow==2.2.0:
#13 1.224 ERROR: Could not find a version that satisfies the requirement tensorflow==2.2.0 (from versions: 2.10.0rc0, 2.10.0rc1, 2.10.0rc2)
#13 1.224 ERROR: No matching distribution found for tensorflow==2.2.0
------
executor failed running [/bin/sh -c pip3 install tensorflow==2.2.0]: exit code: 1

I tried installing tensorflow using pip command ( pip3 install tensorflow-macos)
It still shows this error trace. Also tried changing the tensorflow version to 2.9.2 on the Dockerfile and it still generates the error below 

 => CACHED [ 8/14] RUN pip3 install future                                                                                            0.0s
 => CACHED [ 9/14] RUN pip3 install six==1.14.0                                                                                       0.0s
 => ERROR [10/14] RUN pip3 install tensorflow==2.9.2                                                                                  1.3s
------
 > [10/14] RUN pip3 install tensorflow==2.9.2:
#13 1.268 ERROR: Could not find a version that satisfies the requirement tensorflow==2.9.2 (from versions: 2.10.0rc0, 2.10.0rc1, 2.10.0rc2)
#13 1.269 ERROR: No matching distribution found for tensorflow==2.9.2
------
executor failed running [/bin/sh -c pip3 install tensorflow==2.9.2]: exit code: 1

**Comment by kuaashish** [comment]
Hi @bloodgroup-cplusplus, Could you elaborate your query with complete details and standalone code to reproduce the issue from our end. Thank you!

**Comment by bloodgroup-cplusplus** [comment]
This is a build issue that occurred while trying to build mediapipe using docker
While running the third command after clone and changdir into mediapipe 
docker build --tag=mediapipe . (this is the third command i gave on the terminal)
[+] Building 6.7s (14/18)                                                       
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 34B                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04            4.9s
 => [internal] load build context                                          0.2s
 => => transferring context: 199.97kB                                      0.2s
 => [ 1/14] FROM docker.io/library/ubuntu:20.04@sha256:af5efa9c28de78b754  0.0s
 => CACHED [ 2/14] WORKDIR /io                                             0.0s
 => CACHED [ 3/14] WORKDIR /mediapipe                                      0.0s
 => CACHED [ 4/14] RUN apt-get update && apt-get install -y --no-install-  0.0s
 => CACHED [ 5/14] RUN update-alternatives --install /usr/bin/gcc gcc /us  0.0s
 => CACHED [ 6/14] RUN pip3 install --upgrade setuptools                   0.0s
 => CACHED [ 7/14] RUN pip3 install wheel                                  0.0s
 => CACHED [ 8/14] RUN pip3 install future                                 0.0s
 => CACHED [ 9/14] RUN pip3 install six==1.14.0                            0.0s
 => ERROR [10/14] RUN pip3 install tensorflow==2.9.2                       1.7s
------
 > [10/14] RUN pip3 install tensorflow==2.9.2:
#13 1.706 ERROR: Could not find a version that satisfies the requirement tensorflow==2.9.2 (from versions: 2.10.0rc0, 2.10.0rc1, 2.10.0rc2)
#13 1.707 ERROR: No matching distribution found for tensorflow==2.9.2
------
executor failed running [/bin/sh -c pip3 install tensorflow==2.9.2]: exit code:





I tried installing tensorflow using pip command ( pip3 install tensorflow-macos)
It still shows this error trace. Also tried changing the tensorflow version to 2.9.2 on the Dockerfile and it still generates the above error

**Comment by kuaashish** [comment]
Hi @bloodgroup-cplusplus, Please refer to this closed issue #3071 and [comment](https://github.com/google/mediapipe/issues/3071#issuecomment-1045133677) for your query. Thank you!
