### ISSUE TITLE
How to use face data to drive face models

### ISSUE THREAD

**Issue by wizVR-zhangjun** [google/mediapipe#3639]
I have a face.fbx and I want to drive this face.fbx using face data
![1661493705259](https://user-images.githubusercontent.com/60952586/186833067-ee6b3d49-f6df-462e-9d6e-636d485eab8e.png)
Similar to the form above ，Ask the teacher for advice

**Comment by sureshdagooglecom** [comment]
Hi @wizVR-zhangjun ,
Coudl you please share more information to understand this issues better.
