### ISSUE TITLE
Shoes try on feet

### ISSUE THREAD

**Issue by honeykinng345** [google/mediapipe#3640]
Hey Team I have successfully built 3d shoe object detection. now please anyone tell me how I can add a 3d shoe mask to my feet? I have the shoe obj file. and I replace it with the current obj file(module.obj.uuu) that is in the sneaker asset folder. but not working.  same as issue #1453. @ahmadyan,

**Comment by kuaashish** [comment]
Hi @honeykinng345, We are already tracking this issue here https://github.com/google/mediapipe/issues/3610. Could you post your comment there in #3610 and close this issue as a duplicate. 
Thank you!

**Comment by honeykinng345** [comment]
issues closed because of duplication of #3610

**Comment by kuaashish** [comment]
Hi @honeykinng345, Could you please post your comment on the [above](https://github.com/google/mediapipe/issues/3640#issuecomment-1228279015) mentioned issue. We are following up issues with the internal team and revert back if any update. 
Thank you!

**Comment by honeykinng345** [comment]
> Hi @honeykinng345, Could you please post your comment on the [above](https://github.com/google/mediapipe/issues/3640#issuecomment-1228279015) mentioned issue. We are following up issues with the internal team and will revert back if any update on this request. Thank you!

@kuaashish  already posted ...

**Comment by kuaashish** [comment]
Hi @honeykinng345, 
Closing this issue as duplicate and following up with issue #3610. Thank you!
