### ISSUE TITLE
Densify convert and reshape error

### ISSUE THREAD

**Issue by lhray** [google/mediapipe#3641]
python3 -m tf2onnx.convert --opset 9 --tflite pose_detection.tflite --output pose_detection.onnx

convert the pose_detection model and get the reshape error: ValueError: cannot reshape array of size 96 into shape (16,1,1,24)

I output the densify op weight data and find the data size is 96, but reshape to 16*24
and i don't know how to fix this issue.

netron alse can't read and show the weight data like following picture.
![image](https://user-images.githubusercontent.com/14047988/186835966-a82de16d-9934-4b2f-a87f-e8aab7337175.png)

weight data(96): 
[ 0.585   -0.2019   0.1757  -0.2625   0.3838   0.5024   0.3354  -0.6963
  0.1682   0.926   -1.145   -0.7993   0.2128  -0.02856  0.3303   2.12
  0.1296  -0.1813   2.02     1.324   -0.6035  -0.675   -0.1738   0.3193
 -0.525   -0.35     0.8535   1.132    0.826   -1.314   -0.876   -0.5127
 -1.239   -1.41    -0.808    0.248   -0.56     0.853    0.577    0.3152
  0.735    0.1467   0.6475  -0.557    0.89     0.6587  -1.069   -0.7744
  0.3777  -0.11444  0.163   -0.1626   0.9165   1.118   -0.2289  -0.2062
  1.3955   0.8765   0.3557   0.7856   1.146   -0.878    1.393    0.408
 -0.4387  -0.1606  -1.043    0.01602  0.2427  -1.106   -0.196   -0.07544
 -1.025    1.005    0.4026  -0.354   -0.1081  -0.4453   1.341   -1.071
 -0.5107  -0.2021  -0.6323   1.089    0.4944   0.1757   0.2756   0.1859
  0.8525   0.884    2.436   -0.83    -1.048    1.597    1.196    1.279  ]

**Comment by kuaashish** [comment]
Hi @lhray, Mediapipe team doesn't recommend or support converting models from TFLite. Thank you!
