### ISSUE TITLE
pose_landmark_heavy.tflite not copied to mediapipe installation

### ISSUE THREAD

**Issue by garyli03** [google/mediapipe#3643]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):Linux Ubuntu 20.04/ Windows 11
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): 9.4.0
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.8.10
- Installed using virtualenv? pip? Conda? (if python): Docker
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.10.2
- Bazel version: 5.2.0
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): 4.5.0

**Describe the problem**:
After running python3 setup.py install --link-opencv

the build install succeed. However, when checking /usr/local/lib/python3.8/dist-packages/mediapipe/modules/pose_landmark folder, only pose_landmark_full.tflite is copied, although in mediapipe/modules/pose_landmarks/BUILD file, 

```
exports_files(
   srcs =  [
        "pose_landmark_full.tflite",
        "pose_landmark_heavy.tflite",
        "pose_landmark_lite.tflite",
    ],
)
```

I know we can manually copy these models into the installation folder,  I also understand the model can be downloaded at run time if they are not in the installation folder. I still want to figure out why these models are not copied. 

I did a little investigation, that seems the bazel build didn't copy all the models to `build/lib.linux-x86_64-3.8/mediapipe/modules/pose_landmark folder`. And the `exports_files` tag in BUILD file only copy files from `build/lib.linux-x86_64-3.8/mediapipe/modules/pose_landmark ` to `/usr/local/lib/python3.8/dist-packages/mediapipe/modules/pose_landmark`.

I

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
```
python3 setup.py gen_protos   
python3 setup.py install --link-opencv
```
**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment]
Hi @garyli03, Hope this [#2093(comment)](https://github.com/google/mediapipe/issues/2093#issuecomment-854657871) gives you better understanding for your query. Thank you!

**Comment by am-official** [comment]
You can either [download them manually](https://google.github.io/mediapipe/solutions/models.html#pose) and move them into the working directory, OR it be will automatically be downloaded if not found in the working directory.
