### ISSUE TITLE
How to only recognition face on an holistic framework, do you support?   Thank you very much

### ISSUE THREAD

**Issue by xxqwf** [google/mediapipe#3648]

**Comment by xxqwf** [comment]
@sgowroji

**Comment by liuyulvv** [comment]
You need to new a `holistic_landmark_only_face.pbtxt` like `holistic_landmark_cpu.pbtxt`, and remove `HandLandmark`, `PoseLandmark` can't be removed because `FaceLandmark` need its output.

Why don't you try `FaceMesh`?

**Comment by xxqwf** [comment]
> 

你好, 我想构建一个包,应用在不同的场景!  例如, 只识别手势、或者姿势! 但是我构建的holistic同时输出面部、姿势、手势. 导致大多数手机卡顿

**Comment by xxqwf** [comment]
> 

@liuyulvv  你好, 我想构建一个包,应用在不同的场景! 例如, 只识别手势、或者姿势! 但是我构建的holistic同时输出面部、姿势、手势. 导致大多数手机卡顿

**Comment by liuyulvv** [comment]
@xxqwf [Hand](https://google.github.io/mediapipe/solutions/hands.html)是只识别手势的，[Pose](https://google.github.io/mediapipe/solutions/pose.html)是只识别姿势的。

Holistic本来就是面部、姿势、手势的集成方案。如果你想一个包根据需求只检测某一部分的话，你可以试试将Holistic打包成一个库（我不懂安卓，在pc上是打包成链接库），然后根据需求建立自己的`graph`在运行的时候更改`graph`参数(pc命令行里面的`--calculator_graph_config_file`)，在`graph`里面去掉不需要的`calculator`和`output_stream`

**Comment by sureshdagooglecom** [comment]
Hi @xxqwf ,
Yes , we do have face deteciton solution in MediaPipe , please check [this](https://google.github.io/mediapipe/solutions/face_detection.html) link.

**Comment by xxqwf** [comment]
> Hi @xxqwf , Yes , we do have face deteciton solution in MediaPipe , please check [this](https://google.github.io/mediapipe/solutions/face_detection.html) link.

How to pack `Hand` and `Pose` into an AAR, they do not affect each other

**Comment by xxqwf** [comment]
> @xxqwf [Hand](https://google.github.io/mediapipe/solutions/hands.html)是只识别手势的，[Pose](https://google.github.io/mediapipe/solutions/pose.html)是只识别姿势的。
> 
> Holistic本来就是面部、姿势、手势的集成方案。如果你想一个包根据需求只检测某一部分的话，你可以试试将Holistic打包成一个库（我不懂安卓，在pc上是打包成链接库），然后根据需求建立自己的`graph`在运行的时候更改`graph`参数(pc命令行里面的`--calculator_graph_config_file`)，在`graph`里面去掉不需要的`calculator`和`output_stream`

我试了更改不同的graph, 好像不行。我现在想构建一个包，让他包含`Hand`和`Pose`，但是我不太清楚`Build`里的内容！

**Comment by liuyulvv** [comment]
@xxqwf 从[这里](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_cpu.pbtxt#L39-L48)可以看到Holistic的输出除了Hand和Pose，还有Face的。

Face的输出是在[这里](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/modules/holistic_landmark/holistic_landmark_cpu.pbtxt#L127-L146)计算的，直接注释掉，`graph`那边Face相关的[output_stream](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_cpu.pbtxt#L45)和[这里](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_cpu.pbtxt#L65)也注释掉，应该是可以的。

**Comment by xxqwf** [comment]
@liuyulvv 我尝试修改了这些，还是没跑起来

**Comment by liuyulvv** [comment]
@xxqwf 我注释了这些地方，在PC上CPU跑起来了

[1](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_cpu.pbtxt#L45) [2](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_cpu.pbtxt#L65) [3](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_to_render_data.pbtxt#L16) [4](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_to_render_data.pbtxt#L450-L752) [5](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_to_render_data.pbtxt#L771-L772) [6](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/modules/holistic_landmark/holistic_landmark_cpu.pbtxt#L93) [7](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/modules/holistic_landmark/holistic_landmark_cpu.pbtxt#L127-L146)

**Comment by xxqwf** [comment]
> @xxqwf 我注释了这些地方，在PC上CPU跑起来了
> 
> [1](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_cpu.pbtxt#L45) [2](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_cpu.pbtxt#L65) [3](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_to_render_data.pbtxt#L16) [4](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_to_render_data.pbtxt#L450-L752) [5](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/graphs/holistic_tracking/holistic_tracking_to_render_data.pbtxt#L771-L772) [6](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/modules/holistic_landmark/holistic_landmark_cpu.pbtxt#L93) [7](https://github.com/liuyulvv/mediapipe/blob/e42a9ed4c9a31a10d2d1e34ccec647b6504688a1/mediapipe/modules/holistic_landmark/holistic_landmark_cpu.pbtxt#L127-L146)

谢谢啦， 按照你的方法跑起来了！

**Comment by xxqwf** [comment]
@liuyulvv 只包含`Hand`和`Pose`的包，帧数有明显提高，但还是有些卡顿。怎样能把`Hand`和'Pose'打到同一个包里呢

**Comment by xxqwf** [comment]
@liuyulvv 只包含`Hand`和`Pose`的`Holistic`包，帧数有明显提高，但还是有些卡顿。怎样能把`Hand`和'Pose'打到同一个包里, 并且当使用`Hand`的时候不启用`Pose`，当使用'Pose'的时候不启用'Hand'，老哥你有研究过这个方案吗

**Comment by liuyulvv** [comment]
@xxqwf PC上我是做到了，就是把Pose和Hand打包成动态链接库，main函数根据需求读取graph就行了

**Comment by xxqwf** [comment]
> @xxqwf PC上我是做到了，就是把Pose和Hand打包成动态链接库，main函数根据需求读取graph就行了

打包成一个动态链接库，还是两个呢

**Comment by liuyulvv** [comment]
都可以吧，只要你可执行文件链接上就可以。我是打包成一个，要不然要写两个头文件接口

**Comment by xxqwf** [comment]
> 
可以参考下你写的`Build`文件吗

**Comment by xxqwf** [comment]
> 都可以吧，只要你可执行文件链接上就可以。我是打包成一个，要不然要写两个头文件接口。
> 
> > 打包成一个动态链接库，还是两个呢

可以参考下你写的Build文件吗

**Comment by liuyulvv** [comment]
@xxqwf [DLL](https://github.com/liuyulvv/mediapipe/blob/e3a6cc289078aacc73d1a4fb7c62026504cc0efc/mediapipe/dll/BUILD#L23-L24)这个是把Holistic和Iris打包在一起的，只是测试用的

**Comment by kuaashish** [comment]
Hi @xxqwf, Have you looked at this similar closed issue #2028 and [#2028(comment) ](https://github.com/google/mediapipe/issues/2028#issuecomment-888703030)will give you a better understanding of modifying the internal graphs. Thank you!
