### ISSUE TITLE
An error occurred when I was building the MediaPipe Android sample application in Ubuntu

### ISSUE THREAD

**Issue by gjn2659338105** [google/mediapipe#3649]
I downloaded the SDK and NDK in Ubuntu and configured them according to the documents on the official website. However, an error occurred when I executed the command to generate the Android AAR file:

The command is:
chmod -R 755 mediapipe/
bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a
//mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mediapipe_hand_tracking

And the error is:
external/XNNPACK/src/qu8-igemm/gen/1x8c4-minmax-rndnu-neondot.c:77:16: error: assigning to 'uint32x2_t' (vector of 2 'uint32_t' values) from incompatible type 'int'
vnacc0 = vdot_u32(vnacc0, va_zero_point, va0x01234567);

![image](https://user-images.githubusercontent.com/109133657/187591903-42729386-0bef-4d45-8c5c-6138f18e527d.png)

**Comment by gjn2659338105** [comment]
I checked online and someone said it was the NDK version

My Ubuntu version is 20.04
My SDK version is 30.0.3
My NDK version is: Android-NDK-r18b

After that, I downloaded the NDK version of r21e and reconfigured it, but it was the same error. Does anyone know how to solve it?

**Comment by sureshdagooglecom** [comment]
Hi @gjn2659338105 ,
adb can be installed separately without Android Studio. So, I am not sure if the issue is related to the Android Studio version. The best way is to use the adb install command to install some other apps from the terminal. It this works, then try your robotcontrol app.

**Comment by gjn2659338105** [comment]
> Hi @gjn2659338105 , adb can be installed separately without Android Studio. So, I am not sure if the issue is related to the Android Studio version. The best way is to use the adb install command to install some other apps from the terminal. It this works, then try your robotcontrol app.

I downloaded it directly from Ubuntu with the command ‘setup_android_sdk_and_ndk.sh’ , without the Android Studio configuration.

**Comment by gjn2659338105** [comment]
Thank you. It is indeed the NDK version. I downloaded R21E before, but forgot to change the path in the workspace, so R18B is still in operation.
Now I've solved the problem！
