### ISSUE TITLE
mediapipe INT8 quantization 

### ISSUE THREAD

**Issue by wz2wd** [google/mediapipe#3651]
Hi!
I wonder if mediapipe supports INT8 quantization? Or can INT8 quantization be done? If so, are there any relevant references to draw from? thanks.

**Comment by sureshdagooglecom** [comment]
Hi @wz2wd ,
TfLiteInferenceCalculator can accept quantized tensors, but this must first be set in the TfLiteConverterCalculator options

node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE:input_video"
  output_stream: "TENSORS:image_tensor"
  options: {
    [mediapipe.TfLiteConverterCalculatorOptions.ext] {
      use_quantized_tensors: true
    }
  }
}
but GPU does not support quantized tensors

**Comment by wz2wd** [comment]
@sureshdagooglecom So, can I understand that mediapipe does not support quantification at present? thanks.

**Comment by sureshdagooglecom** [comment]
Hi @wz2wd ,
Yes , for GPU does not support quantized tensors.

**Comment by wz2wd** [comment]
@sureshdagooglecom thanks.
Then, I wonder if it is possible to use CPU for INT8 quantization of the model? If so, how should it be done?

**Comment by sureshdagooglecom** [comment]
Hi @wz2wd ,
TfLiteInferenceCalculator can accept quantized tensors, but this must first be set in the TfLiteConverterCalculator options

node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE:input_video"
  output_stream: "TENSORS:image_tensor"
  options: {
    [mediapipe.TfLiteConverterCalculatorOptions.ext] {
      use_quantized_tensors: true
    }
  }
}
but GPU does not support quantized tensors
