### ISSUE TITLE
How to Understand hand_recrop.tflite Model  Structure Concept

### ISSUE THREAD

**Issue by johnodin99** [google/mediapipe#3652]
Hi guys,

Appreciate your contribution on Media Pipe,

I Parse the hand_recrop.tflite to Diagraph from Netron, but can not understand the concept, it is not the same Spatial Transformer Networks ,not produce the affine matrix and just output tensor 1×1 ×1×4,
I think it is location, how can I more understand the Concept and detail!

Thank a Lot!

**Comment by sureshdagooglecom** [comment]
Hi @johnodin99 .
We don't have hand_recrop.tflite as per https://google.github.io/mediapipe/solutions/models.html document. could you please verify once and confirm the issue.

**Comment by mengxinZHANG** [comment]
@johnodin99 Have you understood the meaning of the output of the recrop model? I cannot understand the meaning of these four numbers，could you tell me?
