### ISSUE TITLE
World Space Tracking With Objectron 

### ISSUE THREAD

**Issue by ababilinski** [google/mediapipe#3653]
Is it possible to get the world space position of an object using Objectron? I tried reading the 3d position, but it didn't seem to change when I moved the object further away from the camera. 

If depth cannot be obtained from the Lifted Objects, is it possible to combine it with Instant Motion Tracking?

**Comment by kuaashish** [comment]
Hi @ababilinski, We have similar closed issue #1463, Please check and get us back if any further queries. Thank you!
