### ISSUE TITLE
Building Android example fails when deleting libmediapipe_jni.so

### ISSUE THREAD

**Issue by murilolima** [google/mediapipe#3655]
**System information**
- OS Platform and Distribution: Ubuntu 20.04
- Compiler version: g++ 9.4.0
- Programming Language and version: C++ 17
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.10.2
- Bazel version: 5.2.0
- Android SDK and NDK versions (if android):
  * Android SDK: https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
  * Android NDK: https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): not using AAR
- OpenCV version (if running on desktop): 4

**Describe the problem**:
Building the Android example fails with the following error:

[...] mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/BUILD:29:11: SolibSymlink _solib_arm64-v8a/_U_S_Smediapipe_Sexamples_Sandroid_Ssrc_Sjava_Scom_Sgoogle_Smediapipe_Sapps_Shandtrackinggpu_Cmediapipe_Ujni_Ulib___Umediapipe_Sexamples_Sandroid_Ssrc_Sjava_Scom_Sgoogle_Smediapipe_Sapps_Shandtrackinggpu/libmediapipe_jni.so failed: failed to delete output files before executing action
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build

It works if I use `bazel mobile-install`.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
```
sed -i '/include\/opencv4/s/#//g' third_party/opencv_linux.BUILD
echo 'android_ndk_repository(name="androidndk", api_level=21)' >> WORKSPACE
echo 'android_sdk_repository(name="androidsdk")' >> WORKSPACE
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
```

**Comment by kuaashish** [comment]
Hi @murilolima, Could you please try with new approach using Gradle as mentioned [here ](https://github.com/google/mediapipe/blob/master/docs/getting_started/android_solutions.md). Please refer to this thread #2339 and #2339(comment) for better understanding. Thank you!

**Comment by murilolima** [comment]
It worked with AndroidStudio, and as I mentioned above also with `bazel mobile-install`.

Is building with `bazel build` not recommended?

I suggest updating the [MediaPipe in Android instructions](https://google.github.io/mediapipe/getting_started/android.html) accordingly.

**Comment by kuaashish** [comment]
Hi @murilolima, Could you please provide the complete error logs and steps to reproduce the issue. Thank you!

**Comment by kuaashish** [comment]
Hello @murilolima,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by murilolima** [comment]
The instructions still point to using `blaze build` and `adb install` in the [Framework page](https://developers.google.com/mediapipe/framework/getting_started/android).
