### ISSUE TITLE
unable to install mediapipe in mac osx

### ISSUE THREAD

**Issue by rnag** [google/mediapipe#3656]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Mac Os M1
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):  n/a
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.7.13 and also 3.10.4
- Installed using virtualenv? pip? Conda? (if python): pip
- [MediaPipe version](https://github.com/google/mediapipe/releases): any
- Bazel version: /
- XCode and Tulsi versions (if iOS): !
- Android SDK and NDK versions (if android): !
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): !
- OpenCV version (if running on desktop): i wanna just try `pip install mediapipe` honestly

**Describe the problem**:

I cannot installing media pipe using the library installer pip. I am having Mac Pro with apple M1 Max chipset.

Here is from the logs:

```console
$ pip install mediapipe
Looking in indexes: https://pypi.org/simple, https://rnag:****@artifactory.collegeboard.org/api/pypi/itp-pypi-local/simple
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):** I think I done it earlier.

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached: see please above.

**Comment by kuaashish** [comment]
Hi @rnag, Could you try the below command to install MediaPipe using pip: `pip install mediapipe-silicon` 
Please let us know if this works. 
Thank you!

**Comment by kuaashish** [comment]
Hi @rnag, Could you please respond to the above [comment](https://github.com/google/mediapipe/issues/3656#issuecomment-1235200591) and confirm still encountering the same error or it has been resolved successfully. Thank you!

**Comment by rnag** [comment]
@kuaashish Hi there, I realized I forgot to update this issue accordingly, but the suggested command did indeed work for me on my M1 mac. Installing `mediapipe-silicon` as an alternative did work perfectly in my case, and so I believe this issue can be marked as resolved. Thanks again!

**Comment by kuaashish** [comment]
Hi @rnag, Thanks for the confirmation. Closing this issue as it has been resolved. Thank you!
