### ISSUE TITLE
3D model Stabilization in AR

### ISSUE THREAD

**Issue by vikarshiitk** [google/mediapipe#3657]
I am working on a Shoe Try-On project I have successfully project the Shoe 3d Model on Human Foot.  But I am facing an issue of model stabilization.  What can be the solution for it.

**Comment by kuaashish** [comment]
Hi @vikarshiitk, Could you please provide the complete details about the issue and query related to model stabilization. Thank you!

**Comment by vikarshiitk** [comment]
> Hi @vikarshiitk, Could you please provide the complete details about the issue and query related to model stabilization. Thank you!

@kuaashish while rendering sometimes the shoe model disappear and some times it shows vibrations

**Comment by kuaashish** [comment]
Hi @vikarshiitk, Could you share the complete code used to implement this model to investigate it further. Thank you!
