### ISSUE TITLE
Face alignment 

### ISSUE THREAD

**Issue by NguyenTrongThinh** [google/mediapipe#3662]
<em>Please add face alignment feature to mediapipe.</em>

**System information** 
- MediaPipe Solution (you are using): mediapipe for android
- Programming language : Android/Kotlin/Java
- Are you willing to contribute it (Yes/No): Yes

This feature will help to increase face recognition accuracy.

**Comment by kuaashish** [comment]
Hi @NguyenTrongThinh, Thank you for this feature request. MediaPipe has limited resources for new features although this is a great feature request that will share this to the internal team and let you know if there is any specific update on this issue. Thank you!

**Comment by kuaashish** [comment]
Hello @NguyenTrongThinh,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
