### ISSUE TITLE
ImportError: DLL load failed while importing _framework_bindings: The specified module could not be found.

### ISSUE THREAD

**Issue by byron-ojua** [google/mediapipe#3665]
**System information**
- Windows 11 Pro - Version 21H2; Build 22000.856:
- Resource base intel core i5 7th Gen, 16Gb RAM
- Python 3.10.6:
- Installed using pip:
- IDE is PyCharm community 2022.2:
- MP version 0.8.10.1:
- OpenCV version 4.6.0.66:

I am trying to use mediapipe with OpenCV to do some hand tracking, but I am getting the following error. I have seen many threads with this error, but none of the solutions have worked for me.:

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
pip install mediapipe
pip install openCV-python
pip install --upgrade pip
pip install msvc-runtime
pip install setuptools --upgrade --ignore-installed

**Complete Logs:**
"C:\Users\Byron Ojua-Nice\PycharmProjects\HandTracking\venv\Scripts\python.exe" "C:/Users/Byron Ojua-Nice/PycharmProjects/HandTracking/main.py" 
Traceback (most recent call last):
  File "C:\Users\Byron Ojua-Nice\PycharmProjects\HandTracking\main.py", line 2, in <module>
    import mediapipe as mp
  File "C:\Users\Byron Ojua-Nice\PycharmProjects\HandTracking\venv\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "C:\Users\Byron Ojua-Nice\PycharmProjects\HandTracking\venv\lib\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: DLL load failed while importing _framework_bindings: The specified module could not be found.

Process finished with exit code 1

**Comment by kuaashish** [comment]
Hi @byron-ojua, Did you able to install MediaPipe on windows as mentioned [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows). If Yes, Could you please try these workaround  mentioned on the https://github.com/google/mediapipe/issues/1839#issuecomment-817253475 and https://github.com/google/mediapipe/issues/1839#issuecomment-817363779. Thank you!

**Comment by byron-ojua** [comment]
Hello @kuaashish I followed the [MediaPipe in Python](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows) steps. I tried the two things you linked before I posted. All of the videos I was watching were saying that for Python, I just had to use pip to do the install. Are all of those programs in the steps you provided required to make MediaPipe work? I am seeing like 10GB of downloads.

**Comment by kuaashish** [comment]
Hi @byron-ojua, Yes, Please follow the official documentation to build MediaPipe from source Or depends on use case you could follow the Python Solution API example code of Hands as mentioned in the [documentation](https://google.github.io/mediapipe/solutions/hands.html#python-solution-api). Thank you!

**Comment by byron-ojua** [comment]
I am still getting the same error.

**Comment by kuaashish** [comment]
Hi @byron-ojua, Please try the suggestion mentioned in the similar SO [issue](https://stackoverflow.com/questions/69780732/getting-errors-with-opencv-and-mediapipe-for-making-hand-tracking-module-in-pyth) and revert back if encounter the same error. 
Thank you!
