### ISSUE TITLE
I want to map a face image I took into a 3D face model

### ISSUE THREAD

**Issue by wizVR-zhangjun** [google/mediapipe#3666]
I don't know what to do, please teach me

**Comment by sureshdagooglecom** [comment]
Hi @wizVR-zhangjun ,
First, you ll need some face topology that establishes semantic relationship between 3D positions of the face mesh vertices and some 2D texture coordinates. I'd start with the canonical face model used in MediaPipe Face Geometry module ([UV visualization](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png); Face Geometry formats: [metadata schema](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/geometry_pipeline_metadata.proto), [mesh 3D schema](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/protos/mesh_3d.proto), [metadata text](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt)).
We have closed issue on this https://github.com/google/mediapipe/issues/1698, please check

**Comment by wizVR-zhangjun** [comment]
@sureshdagooglecom 
Thanks to the teacher's guidance, the problem was solved

**Comment by zw20045500** [comment]
> @sureshdagooglecom Thanks to the teacher's guidance, the problem was solved

hello, can you tell how to solve, can you share me your code, thank you very much

**Comment by wizVR-zhangjun** [comment]
> > @sureshdagooglecom Thanks to the teacher's guidance, the problem was solved
> 
> hello, can you tell how to solve, can you share me your code, thank you ver

[OpenCVManager.ZIP](https://github.com/google/mediapipe/files/9796270/OpenCVManager.ZIP)

You need to change.zip to.cs and I'm using c# and I hope that helps

**Comment by divastar** [comment]
I couldn't open the file [OpenCVManager.ZIP](https://github.com/google/mediapipe/files/9796270/OpenCVManager.ZIP)  it says damaged

**Comment by wizVR-zhangjun** [comment]
> @divastar  You need to change the suffix {OpenCVManager.ZIP--->OpenCVManager.cs}
