### ISSUE TITLE
Mediapipe GPU: Build did NOT complete successfully.

### ISSUE THREAD

**Issue by Choyon10** [google/mediapipe#3668]
**System information** 
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Linux Ubuntu 18.04(Nvidia GeForce GTX 1080)
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc - 8.4.0, g++ - 8.4.0 
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.7.13
- Installed using virtualenv? pip? Conda? (if python): Conda
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.10.2
- Bazel version: 5.2
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): 4.5.3

**Describe the problem**:
Trying to build MediaPipe with TensorFlow GPU per instructions https://google.github.io/mediapipe/getting_started/gpu_support.html#tensorflow-cuda-support-and-setup-on-linux-desktop and get this error

```
ERROR: /home/neuron/Desktop/mediapipe/WORKSPACE:246:23: fetching android_ndk_repository rule //external:androidndk: Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable must be set.
ERROR: Analysis of target '//mediapipe/examples/desktop/face_mesh:face_mesh_gpu' failed; build aborted: Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable must be set.
INFO: Elapsed time: 0.137s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 11 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 11 targets configured)
    currently loading: @cmake_3.19.6_toolchains// 
```

**[Provide the exact sequence of commands/steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
I started from a fresh install. So here is every step.

1. Install Cuda 10.2
2. Install cuDNN 8.2.1
3. Make an anaconda virtual environment with python version 3.7.
4. Build OpenCV from the source.
```
$ wget -O opencv.zip https://github.com/opencv/opencv/archive/4.5.3.zip
$ wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.5.3.zip
$ unzip opencv.zip
$ unzip opencv_contrib.zip
$ mv opencv-4.5.3 opencv
$ mv opencv_contrib-4.5.3 opencv_contrib
(mediapipe37)$ pip install numpy
(mediapipe37)$ cd ~/opencv
(mediapipe37)$ mkdir build
(mediapipe37)$ cd build
(mediapipe37)$ cmake -D CMAKE_BUILD_TYPE=RELEASE \
		-D CMAKE_INSTALL_PREFIX=/usr/local \
		-D INSTALL_PYTHON_EXAMPLES=ON \
		-D INSTALL_C_EXAMPLES=OFF \
		-D OPENCV_ENABLE_NONFREE=ON \
		-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
		-D PYTHON_EXECUTABLE=~/.virtualenvs/mp_env/bin/python \
		-D WITH_TBB=ON \
		-D WITH_CUDA=ON \
		-D BUILD_opencv_cudacodec=ON \
		-D ENABLE_FAST_MATH=1 \
		-D CUDA_FAST_MATH=1 \
		-D WITH_CUBLAS=1 \
		-D WITH_V4L=ON \
		-D WITH_GSTREAMER=ON \
		-D OPENCV_GENERATE_PKGCONFIG=ON \
		-D OPENCV_PC_FILE_NAME=opencv.pc \
		-D BUILD_EXAMPLES=ON
(mediapipe37)$ make -j12
(mediapipe37)$ sudo make install
(mediapipe37)$ sudo ldconfig
```
- move the file into the virual enviroment
```
(mediapipe37)$ cd ~
(mediapipe37)$ cd /usr/local/lib/python3.7/site-packages/cv2/python-3.7/
(mediapipe37)$ sudo mv cv2.cpython-37m-x86_64-linux-gnu.so cv2.so
(mediapipe37)$ cd  /home/neuron/anaconda3/envs/mediapipe37/lib/
(mediapipe37)$ ln -s /usr/local/lib/python3.7/site-packages/cv2/python-3.7/cv2.so cv2.so
`
- Verify cv2 install
`>>> cv2.__version__
'4.5.3'
```

### Section - Build for GPU 
Follow the instruction for building media-pipe installation page: https://google.github.io/mediapipe/getting_started/install.html
Step 1: Install Bazelisk use this link https://docs.bazel.build/versions/main/install-ubuntu.html
```
$sudo apt update && sudo apt install bazel
(mediapipe37)$bazel --version
bazel--5.2.0
```
Step 2: Follow as is
Step 3: Use Option 3 (not OpenCV has already been built from source)
-- In the the WORKSPACE file do a search for new_local_repository update /usr to /usr/local
-- In opencv_linux uncomment lines required for OpenCV build from source DO NOT copy and past provided example.
-- For ffmpeg no change required

https://google.github.io/mediapipe/getting_started/python.html#building-mediapipe-python-package

Step 1: skip sudo apt install python3-dev and sudo apt install cmake
Step 2: skip
Step 3: Use
```
(mediapipe37)$ pip3 install -r requirements.txt
(mediapipe37)$ pip install tensorflow
```

https://google.github.io/mediapipe/getting_started/gpu_support.html#tensorflow-cuda-support-and-setup-on-linux-desktop

step1: Update ~/.bashrc
```
(mediapipe37)$ echo "export PATH=/usr/local/cuda-10.2/bin${PATH:+:${PATH}}" >> ~/.bashrc
(mediapipe37)$ echo "export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64,/usr/local/cuda-10.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" >> ~/.bashrc
(mediapipe37)$ echo "export TF_CUDA_PATHS=/usr/local/cuda-10.2,/usr/lib/x86_64-linux-gnu,/usr/include" >> ~/.bashrc
(mediapipe37)$ source ~/.bashrc
(mediapipe37)$ sudo ldconfig
```
step2: update the .bazelrc in the mediapipe directory.
`(mediapipe37)$bazel run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/face_mesh:face_mesh_gpu`
`(mediapipe37)$bazel build -c opt --config=cuda --spawn_strategy=local --define no_aws_support=true --copt -DMESA_EGL_NO_X11_HEADERS mediapipe/examples/desktop/object_detection:object_detection_tensorflow`
- Before it was built into CPU for example hello world program. but now it's not working for the hello world program also.
`bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world`
**Complete Logs:**
The same error is given for all the cases.

**Comment by kuaashish** [comment]
Hi @Choyon10. Could you confirm that you have followed the [TensorFlow GPU documentation](https://www.tensorflow.org/install/gpu#software_requirements) to install the required NVIDIA software on your Linux desktop and able to verify the installation as mentioned in the [documentation](https://google.github.io/mediapipe/getting_started/gpu_support.html#tensorflow-cuda-support-and-setup-on-linux-desktop). Thank you!
