### ISSUE TITLE
mediapipe/framework/deps/registration_token.cc: Permission denied compilation terminated.

### ISSUE THREAD

**Issue by Tongbook** [google/mediapipe#3669]
ERROR: /home/yjkj-ztx/Desktop/ztx/mediapipe/mediapipe/framework/deps/BUILD:214:11: Compiling mediapipe/framework/deps/registration_token.cc failed: (Exit 1): linux-sandbox failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/e934be0c1805df5ece76f97052536283/sandbox/linux-sandbox/407/execroot/mediapipe && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/41b71f1bb3ce13f20cfeeb31a9357113/linux-sandbox -t 15 -w /root/.cache/bazel/_bazel_root/e934be0c1805df5ece76f97052536283/sandbox/linux-sandbox/407/execroot/mediapipe -w /tmp -w /dev/shm -D -- /bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/mediapipe/framework/deps/_objs/registration_token/registration_token.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/mediapipe/framework/deps/_objs/registration_token/registration_token.pic.o' -fPIC -iquote . -iquote bazel-out/k8-fastbuild/bin -w '-std=c++17' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c mediapipe/framework/deps/registration_token.cc -o bazel-out/k8-fastbuild/bin/mediapipe/framework/deps/_objs/registration_token/registration_token.pic.o)
1662445443.457507520: src/main/tools/linux-sandbox.cc:152: calling pipe(2)...
1662445443.457564611: src/main/tools/linux-sandbox.cc:171: calling clone(2)...
1662445443.457995350: src/main/tools/linux-sandbox.cc:180: linux-sandbox-pid1 has PID 99103
1662445443.458072933: src/main/tools/linux-sandbox-pid1.cc:641: Pid1Main started
1662445443.458209722: src/main/tools/linux-sandbox.cc:197: done manipulating pipes
1662445443.458472488: src/main/tools/linux-sandbox-pid1.cc:260: working dir: /root/.cache/bazel/_bazel_root/e934be0c1805df5ece76f97052536283/sandbox/linux-sandbox/407/execroot/mediapipe
1662445443.458506164: src/main/tools/linux-sandbox-pid1.cc:292: writable: /root/.cache/bazel/_bazel_root/e934be0c1805df5ece76f97052536283/sandbox/linux-sandbox/407/execroot/mediapipe
1662445443.458517776: src/main/tools/linux-sandbox-pid1.cc:292: writable: /tmp
1662445443.458528107: src/main/tools/linux-sandbox-pid1.cc:292: writable: /dev/shm
1662445443.458606514: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /
1662445443.458623552: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev
1662445443.458631240: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/pts
1662445443.458638785: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /dev/shm
1662445443.458644509: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/hugepages
1662445443.458650917: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/mqueue
1662445443.458682336: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run
1662445443.458689608: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/lock
1662445443.458696241: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/credentials/systemd-sysusers.service
1662445443.458702890: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/vmblock-fuse
1662445443.458709601: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/snapd/ns
1662445443.458717093: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/1000
1662445443.458748830: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/1000/gvfs
1662445443.458754470: src/main/tools/linux-sandbox-pid1.cc:382: remount(nullptr, /run/user/1000/gvfs, nullptr, 2101287, nullptr) failure (Permission denied) ignored
1662445443.458759508: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/1000/doc
1662445443.458762523: src/main/tools/linux-sandbox-pid1.cc:382: remount(nullptr, /run/user/1000/doc, nullptr, 2101287, nullptr) failure (Permission denied) ignored
1662445443.458766313: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys
1662445443.458773391: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/security
1662445443.458783490: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup
1662445443.458792441: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/pstore
1662445443.458799559: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/bpf
1662445443.458806352: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/debug
1662445443.458813194: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/debug/tracing
1662445443.458820306: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/tracing
1662445443.458826760: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/config
1662445443.458833124: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/fuse/connections
1662445443.458840801: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc
1662445443.458866144: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc/sys/fs/binfmt_misc
1662445443.458875028: src/main/tools/linux-sandbox-pid1.cc:382: remount(nullptr, /proc/sys/fs/binfmt_misc, nullptr, 2101281, nullptr) failure (Operation not permitted) ignored
1662445443.458879711: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc/sys/fs/binfmt_misc
1662445443.458886725: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core20/1587
1662445443.458892752: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/bare/5
1662445443.458909172: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-3-38-2004/112
1662445443.458914611: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/firefox/1635
1662445443.458919904: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/snapd/16292
1662445443.458925722: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/snap-store/582
1662445443.458930997: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/snapd-desktop-integration/14
1662445443.458936433: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gtk-common-themes/1535
1662445443.458942820: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /boot/efi
1662445443.458968122: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /media/yjkj-ztx/CDROM
1662445443.458976111: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core20/1611
1662445443.458981175: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-3-38-2004/115
1662445443.458985733: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core/13425
1662445443.458990431: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/code/106
1662445443.458995425: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/android-studio/123
1662445443.459005726: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /root/.cache/bazel/_bazel_root/e934be0c1805df5ece76f97052536283/sandbox/linux-sandbox/407/execroot/mediapipe
1662445443.459016872: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /root/.cache/bazel/_bazel_root/e934be0c1805df5ece76f97052536283/sandbox/linux-sandbox/407/execroot/mediapipe
1662445443.459021875: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /tmp
1662445443.459027033: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /dev/shm
1662445443.459121517: src/main/tools/linux-sandbox-pid1.cc:451: calling fork...
1662445443.459269345: src/main/tools/linux-sandbox-pid1.cc:481: child started with PID 2
cc1plus: fatal error: mediapipe/framework/deps/registration_token.cc: Permission denied
compilation terminated.
1662445443.467263028: src/main/tools/linux-sandbox-pid1.cc:498: wait returned pid=2, status=0x100
1662445443.467280252: src/main/tools/linux-sandbox-pid1.cc:516: child exited normally with code 1
1662445443.467754441: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by sureshdagooglecom** [comment]
Hi @Tongbook ,
Could you provide steps to reproduce this issue.
