### ISSUE TITLE
How to reduce the time of hand detection inference

### ISSUE THREAD

**Issue by SuzieSzn** [google/mediapipe#367]
Our requirement is hand detection's fps >=30

I used Android mobile device(used Qualcomm 845 chipset) and changed Camera preview size to 640 x 480 to count the fps of hand detection.
Mostly is 15~20 fps.

by log, we found in TfLiteTensorsToDetectionsCalculator.cc  "Copy decoded boxes from GPU to CPU" has taken most time.

01-02 18:09:23.451 17598 17979 D Calculator: TfLiteTensorsToDetectionsCalculator ProcessGPU Copy decoded boxes from GPU to CPU begin
01-02 18:09:23.492 17598 17979 D Calculator: TfLiteTensorsToDetectionsCalculator ProcessGPU Copy decoded boxes from GPU to CPU end

Could you give some advice to improve it?
Thanks in advance.

**Comment by mcclanahoochie** [comment]
I'm not sure if there is much that can [easily] be done without completely re-writing how the calculator decodes boxes.

One thing to try:  see if just using the CPU path for this calculator is faster...
Simply change the input stream of this calculator from TENSORS_GPU to TENSORS, and also for the output of tflite inference calculator (the rest of the graph remains the same)...

inference calc:
```
output_stream: "TENSORS_GPU:detection_tensors" 
   --> output_stream: "TENSORS:detection_tensors"
```
detections calc:
```
input_stream: "TENSORS_GPU:detection_tensors" 
   --> input_stream: "TENSORS:detection_tensors"
```
