### ISSUE TITLE
Blazeface Model inference output interpretation 

### ISSUE THREAD

**Issue by razor123max** [google/mediapipe#3671]
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): yes python script
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Linux
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic): Facemesh and facedetect
- Programming Language and version ( e.g. C++, Python, Java): Python

I am trying to use BlazeFace model as standalone model with Triton inference server, How do i interpret the output of the model and how do i decide the detected face region from output? 
I see that output0 is regressors float32[1,896,16] and output1 is classificators  float32[1,896,1]

**Comment by kuaashish** [comment]
Hi @razor123max, Please follow this closed issue #1010 and [#1010(comment) ](https://github.com/google/mediapipe/issues/1010#issuecomment-690716813) for your query. Thank you!

**Comment by razor123max** [comment]
Thank you for your response @kuaashish, from the comments of the closed issue #1010 does not talk about processing the regressors output with some anchor processing similar to SSD, if i am not wrong? if I only run the tflite model exported in ONNX format the values i get are not in 0-1 range aswell (I presume missing self sigmoidal). If some one can explain the anchor point processing part that would be awesome. Thanks.

**Comment by kuaashish** [comment]
@razor123max,

Are you still looking for resolution on issue?
