### ISSUE TITLE
Unable to suppress info logs from "XNNPACK Delegate"

### ISSUE THREAD

**Issue by RandGor** [google/mediapipe#3672]
I have logging I dont want to:
```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```
It appears when I am using this lib. I don't think it requires any code. I cannot find any info how it even possible to remove this kind of logs from this lib.

**Comment by kuaashish** [comment]
Hi @RandGor, "INFO: Created TensorFlow Lite XNNPACK delegate for CPU." is an information log. If you would like to disable it then you can go through this https://github.com/google/mediapipe/issues/2094. Thank you!

**Comment by kuaashish** [comment]
Hi @RandGor, Could you respond to the above **[comment](https://github.com/google/mediapipe/issues/3672#issuecomment-1238912484)** and please let us know this resolves the issue. Thank you!

**Comment by RandGor** [comment]
> Hi @RandGor, Could you respond to the above **[comment](https://github.com/google/mediapipe/issues/3672#issuecomment-1238912484)** and please let us know this resolves the issue. Thank you!

Hello @kuaashish ! I think this can help. But I think it is a great idea to make this logs optional in the future (make all devs understand it)
