### ISSUE TITLE
Mediapipe face mesh to full head is that possible? maybe transforming that into FLAME?

### ISSUE THREAD

**Issue by FrankEscobar** [google/mediapipe#3676]
Obviously I mean the procedural head model https://flame.is.tue.mpg.de/ but if you know any other alternative to get a full head you are welcome!

Thank you in advance.

**Comment by wilbsmond** [comment]
Following. I'm interested to know how to relate face mesh model to full head in 3D, so that the face and head landmarks / geometry are connected. Is there an off-the-shelf model that does that?

**Comment by kuaashish** [comment]
Hi @FrankEscobar,
Face-mesh is not very much adapted to each human head shape, it is simply deformed to align with each user's head image.
Could you confirm that does flame do something similar or does it require specific use head shapes?
Thank you!

**Comment by FrankEscobar** [comment]
It uses its own base mesh.

As far as I know there are other solutions that adapt their own output to FLAME controlers so they can use this standarized head model.

Anyway if there is any other way to create full head mesh from Mediapipe it could be great anyway, FLAME was just one suggestion.

**Comment by kuaashish** [comment]
Hello @FrankEscobar,

We still do not offer the full head model in facemesh, and We will be not adding this feature for now. However, Will let you know if full head model is possible in MediaPipe. Thank you!!
