### ISSUE TITLE
Can't `pip install mediapipe' on Docker alpine linux

### ISSUE THREAD

**Issue by Dekwin** [google/mediapipe#3677]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution: Docker, image python:3.8-alpine
- Installed using virtualenv? pip? Conda? (if python): pip
- [MediaPipe version](https://github.com/google/mediapipe/releases): latest
- OpenCV version (if running on desktop): not installed

**Describe the problem**:

I tried to install mediapipe inside the alpine python image (python:3.8-alpine), but got an error:
```
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

My Dockerfile looks like: 
```Dockerfile
ARG IMAGE=python:3.8-alpine
FROM ${IMAGE}

RUN pip install mediapipe
```

But if I use Debian based image (python:3.8) it works normally and it can find a mediapipe package:

```Dockerfile
ARG IMAGE=python:3.8
FROM ${IMAGE}

RUN pip install mediapipe
```

**Comment by kuaashish** [comment]
Hi @Dekwin, Could you please elaborate the use case with respect to prefer docker alpine image. Thank you!

**Comment by DanielSarmiento04** [comment]
try with python:3.8-slim-buster
example


`FROM python:3.8-slim-buster
`
`COPY . .
`
`
RUN pip install -r requirements.txt
`
`
CMD ["python", "main.py"]
`
![image](https://user-images.githubusercontent.com/90324959/189741222-cc6654e5-6777-4d02-a8cc-ffe92f848d8b.png)

**Comment by gentnm** [comment]
Please note that, using slim python images will result in problems with opencv (https://github.com/google/mediapipe/issues/3661) as they require additional dependencies.

For the issue here, it seems mediapipe only provides manylinux wheels, that are not supported on alpine systems.
