### ISSUE TITLE
Is there any way to achieve ARCore-like functions with just mediapipe and opengl or related 3D rendering engines (such as Filament) in Android with gradle？

### ISSUE THREAD

**Issue by ouyangpeng** [google/mediapipe#3679]
I found that it is easy to use ARCore to achieve AR effects, but **ARCore** can only be used in some machine, not my android device. 

so I plan to use Mediapipe to obtain some functions such as face 3D mesh, but how to combine **Mediapipe** and **OpenGL** to achieve **AR** functions? 

It's not clear, mediapipe has a Face Effect Example, but the code is compiled with **Bazel** and I can't understand it. I wonder if there is an example project compiled with gradle? So I can refer to how to achieve. 

Thank you very much !

**Comment by sureshdagooglecom** [comment]
Hi @ouyangpeng ,
Unity is not officially supported by MediaPipe yet. Assuming this [MediaPipeUnityPlugin](https://github.com/homuler/MediaPipeUnityPlugin) could be more helpful. Thank you!

**Comment by ouyangpeng** [comment]
> Hi @ouyangpeng , Unity is not officially supported by MediaPipe yet. Assuming this [MediaPipeUnityPlugin](https://github.com/homuler/MediaPipeUnityPlugin) could be more helpful. Thank you!

Thank you , I don't mean to use the combination of Unity and MediaPipe, but consider using MediaPipe combined with Filament or other 3D rendering engines to achieve an effect similar to ARCore combined with Filament, such as this case[ Scenform-android](https://github.com/SceneView/sceneform-android), I wonder if there is a related sample code for MediaPipe combined with Filament?
