### ISSUE TITLE
Hand Tracking Landmark ordering

### ISSUE THREAD

**Issue by wtesler** [google/mediapipe#368]
Does anyone know the ordering of the 21 landmarks for a hand? Like which ones are the thumb, pinky etc... I can't find anywhere that it is stated. Thanks.

**Comment by PrinceP** [comment]
http://www-rech.telecom-lille.fr/shrec2017-hand/ might help.

**Comment by wtesler** [comment]
That one has 22 points while these have 21. Perhaps it is the same besides the palm point is excluded in these?

**Comment by wtesler** [comment]
Is it like this picture?

[Hand Diagram](https://www.learnopencv.com/wp-content/uploads/2018/09/handpose-demo-keypoints.jpg)

**Comment by PrinceP** [comment]
[Link](https://user-images.githubusercontent.com/14876277/65331840-ea5ab780-db93-11e9-922a-8d7334826982.png)

#119

**Comment by wtesler** [comment]
Awesome, thanks.
