### ISSUE TITLE
Can't detect tilted face in the image input

### ISSUE THREAD

**Issue by Aarushi240** [google/mediapipe#3685]
Hello everyone,

I was trying Mediapipe Facemesh Solutions. When processing some images containing face couldn't detect the tilted face in the image.

**System information** 

- OS Platform and Distribution: Windows 8
- Solution: Facemesh
- Programming Language: Javascript

**Image to reproduce:**

![output (tilted photo)](https://user-images.githubusercontent.com/83343665/189326947-89182464-9930-4c7d-8124-91a4ab2c9538.PNG)

**Code to reproduce:**

    const canvasElement = document.getElementsByClassName('output_canvas')[0];
    const canvasCtx = canvasElement.getContext('2d');
    main();
    function onResults(results) {
      canvasCtx.save();
      
      canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
      canvasCtx.drawImage(results.image, 0, 0, canvasElement.width, canvasElement.height);
      if (results.multiFaceLandmarks) {
        for (const landmarks of results.multiFaceLandmarks) {
            
          drawConnectors(canvasCtx, landmarks, FACEMESH_TESSELATION,
                         {color: '#C0C0C070', lineWidth: 1});
          drawConnectors(canvasCtx, landmarks, FACEMESH_RIGHT_EYE, {color: '#FF3030'});
          drawConnectors(canvasCtx, landmarks, FACEMESH_RIGHT_EYEBROW, {color: '#FF3030'});
          drawConnectors(canvasCtx, landmarks, FACEMESH_RIGHT_IRIS, {color: '#FF3030'});
          drawConnectors(canvasCtx, landmarks, FACEMESH_LEFT_EYE, {color: '#30FF30'});
          drawConnectors(canvasCtx, landmarks, FACEMESH_LEFT_EYEBROW, {color: '#30FF30'});
          drawConnectors(canvasCtx, landmarks, FACEMESH_LEFT_IRIS, {color: '#30FF30'});
          drawConnectors(canvasCtx, landmarks, FACEMESH_FACE_OVAL, {color: '#E0E0E0'});
          drawConnectors(canvasCtx, landmarks, FACEMESH_LIPS, {color: '#E0E0E0'});
        }
      }
      canvasCtx.restore();
    }
    
    const faceMesh = new FaceMesh({locateFile: (file) => {
      return `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${file}`;
    }});
    faceMesh.setOptions({
      staticImageMode: true,
      maxNumFaces: 2,
      refineLandmarks: true,
      minDetectionConfidence: 0.9,     
      minTrackingConfidence: 0.5
    });
    faceMesh.onResults(onResults);

**Output (Not Tilted Face)**

![Output (straight photo)](https://user-images.githubusercontent.com/83343665/189327174-43ab4b65-0145-41e7-ad24-1e9cf91f1c59.PNG)

**Output (Tilted Face)**

![output (tilted photo)](https://user-images.githubusercontent.com/83343665/189327293-50414e70-469b-4749-8b6f-2a607f11f305.PNG)

**Comment by kuaashish** [comment]
Hi @Aarushi240, Our dataset for training face detection for front camera is composed of mostly selfie images and we trained with rotation augmentation (+/- 45 degrees). So there're training examples up to 90 degrees rotation.
However, we don't have much flipped face in the dataset and the model is not expected to work in that case. 
Thank you!

**Comment by kuaashish** [comment]
Hi @Aarushi240, Could you confirm your query has been addressed as per the [above](https://github.com/google/mediapipe/issues/3685#issuecomment-1241870754) comment and move the issue to the close status as has been resolved. Thank you
