### ISSUE TITLE
Issue in cvzone module

### ISSUE THREAD

**Issue by Janakinathverma** [google/mediapipe#3687]
from charset_normalizer import detect
import cv2
import cvzone
from cvzone.HandTrackingModule import Handdetector
from time import sleep
import numpy as np
from pynput.keyboard import Controller
cap=cv2.VideoCapture(0,cv2.CAP_DSHOW)
cap.set(3,1280)
cap.set(4,720)
detector=Handdetector(detectionCon=0.8)
cap.set(5,674)

This code is showing errors.

python -u "d:\file\pros\myproject-main\virtualkeyboard.py"
Traceback (most recent call last):
  File "d:\file\pros\myproject-main\virtualkeyboard.py", line 4, in <module>
    from cvzone.HandTrackingModule import Handdetector
ImportError: cannot import name 'Handdetector' from 'cvzone.HandTrackingModule' (C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\cvzone\HandTrackingModule.py)

Please lead me with a solution.

**Comment by kuaashish** [comment]
Hi @Janakinathverma, This issue is more related to the cvzone please raise this issue into relavant repo. Thank you!
