### ISSUE TITLE
Holistic Landmark

### ISSUE THREAD

**Issue by hazenne7** [google/mediapipe#3689]
![image](https://mediapipe.dev/images/mobile/holistic_pipeline_example.jpg)

In the MediaPipe holistic docs image above, it uses both hand and face re-crop to form the landmarks but we are only able to apply the face re-crop. How can we use the hand re-crop?

**Comment by kuaashish** [comment]
Hi @hazenne7,
Could you confirm that you are able to find out the initial hands ROI region of interest. The hand re-crop model is designed to refine the initial hands ROI. If yes, then please let us know if initial hands ROI is not sufficient. 
Thank you!

**Comment by hazenne7** [comment]
Thanks for the reply. I am not issuing the initial hands ROI. What i mean by my question is, how can i apply Holistic with the hands landmarks like on all of the Holistic example picture?

![alt text](https://mediapipe.dev/images/mobile/holistic_pipeline_example.jpg)

Holistic landmarks used on this [MediaPipe demo web](https://mediapipe.dev/demo/holistic_remote/) is what i mean, not a hand landmark on top of the pose's hand landmark

**Comment by kuaashish** [comment]
Hello @hazenne7,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customise ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
