### ISSUE TITLE
More readable changelogs

### ISSUE THREAD

**Issue by abitrolly** [google/mediapipe#369]
While many open source projects impose guidelines to maintain good log messages, the mediapipe [commit history](https://github.com/google/mediapipe/commits/master) contains no commit messages at all.

Maybe use http://www.catb.org/esr/reposurgeon/ for git import?

**Comment by mgyong** [comment]
@abitrolly This is due to the project use of internal Google tools to do code transformation. Thanks for your suggestion and we will take it into consideration in the future @jiuqiant

**Comment by abitrolly** [comment]
@mgyong so what tools do you use except https://github.com/google/copybara ?

**Comment by abitrolly** [comment]
@mgyong so did you consider adding change logs here?

**Comment by abitrolly** [comment]
I'd like to know if it's worth the hassle to upgrade from 0.8.8 to 0.8.8.1 and what could go wrong if I go straight to 0.8.9.1

**Comment by abitrolly** [comment]
Found that releases at https://github.com/google/mediapipe/releases contain tiny tag on the left with actual version that I haven't spotted before. No 0.8.8.1 or 0.8.9.1 info, but already useful.
