### ISSUE TITLE
Original vs Normalised Co-ordinates

### ISSUE THREAD

**Issue by ThinLizzy13** [google/mediapipe#3691]
Hello, 

Apologies if this is trivial but I'm wondering if there's something else I'm missing when it comes to how the normalised co-ordinates are calculated. I'm NSlogging the landmarks similar to this issue #2764 (https://github.com/google/mediapipe/issues/2740) to print out the landmarks coordinates. 

I would've assumed to retrieve the original co-ordinates one should just multiply by the image frame height and width. However doing so I still get decimals (and not even close to suggest truncation errors)
I had a look through the graphs and calculators but am still at a bit of a loss. Any help in retrieving the original co-ordinates would be much appreciated.

Best,
RG

**Comment by kuaashish** [comment]
Hi @ThinLizzy13, 
Could you please provide the complete details of the platform and solution which you are referring to. 
Thank you!

**Comment by ThinLizzy13** [comment]
Absolutely apologies.
I'm using iOS with all the latest versions. The solution is for the iris, however I would envisage that this would be applicable across all solutions that output co-ordinates.
Thanks !

**Comment by kuaashish** [comment]
Hi @ThinLizzy13, Please refer to this issue #739 and [#739(comment)](https://github.com/google/mediapipe/issues/739#issuecomment-637819276) for better understanding of your query. Thank you!
