### ISSUE TITLE
Getting totally different output from Mediapipe Hands Python API and tflite model

### ISSUE THREAD

**Issue by Mohit0928** [google/mediapipe#3694]
I'm running inference using the [Python API](https://google.github.io/mediapipe/solutions/hands.html#python-solution-api) of **Hand Landmark Detection** to generate hand keypoint.

I'm running inference on the same image with [tflite model](https://storage.googleapis.com/mediapipe-assets/hand_landmark_full.tflite) of **Hand Landmark Detection**. 

I haver created a Colab Notebook [here](https://colab.research.google.com/drive/1SnhsjEooKRAu9zh_GdOkNbwIZIUN5nWc?usp=sharing) where I have used both the approach.

But I'm getting totally different output from both. What's going under the hood? Could anyone please explain why I'm getting different output from both. These should be a bit similar at least.

**Comment by kuaashish** [comment]
Hi @Mohit0928, Mediapipe hand-landmarks solution, is designed to basically just run the tflite model. It is surprising to get very different output from the two tflite model runners. 

Could you please provide the demo with very different output with several good input images it will be helpful to investigate further on the issue. Thank you!
