### ISSUE TITLE
fatal error: 'third_party/GL/gl/include/EGL/egl.h' file not found

### ISSUE THREAD

**Issue by HardikElitefit** [google/mediapipe#3696]
Error while building example in macOS

ERROR: /Users/trootech/mediapipe/mediapipe/calculators/core/BUILD:941:11: Compiling mediapipe/calculators/core/split_vector_calculator.cc failed: (Exit 1): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 -target ... (remaining 185 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from mediapipe/calculators/core/split_vector_calculator.cc:24:
./mediapipe/framework/formats/tensor.h:42:10: fatal error: 'third_party/GL/gl/include/EGL/egl.h' file not found
#include "third_party/GL/gl/include/EGL/egl.h"

How to fix?

**Comment by Ar4enal** [comment]
Solve by
```
export ANDROID_HOME=<path to the Android SDK>
export ANDROID_NDK_HOME=<path to the Android NDK>
echo "android_sdk_repository(name = \"androidsdk\")" >> WORKSPACE
echo "android_ndk_repository(name = \"androidndk\", api_level=21)" >> WORKSPACE
```

 [MediaPipe on Android](https://google.github.io/mediapipe/getting_started/android.html)

Try it

**Comment by kuaashish** [comment]
Hi @HardikElitefit, Could you please provide the steps to reproduce and complete details about the issue. Thank you!

**Comment by HardikElitefit** [comment]
@Ar4enal  Worked

**Comment by kuaashish** [comment]
Hi @HardikElitefit, Thanks for the confirmation. Marking as similar issue #3693. Thank you!
