### ISSUE TITLE
Segmentation fault after installing mediapipe on raspberry pi 3 model b

### ISSUE THREAD

**Issue by Mousavikia** [google/mediapipe#3699]
Hi community...
After updating numpy to its latest version I tried to install mediapipe on my raspberry pi 3 model b with following instructions found in [here](https://pypi.org/project/mediapipe-rpi3/)...

```
sudo apt install ffmpeg python3-opencv python3-pip
sudo apt install libxcb-shm0 libcdio-paranoia-dev libsdl2-2.0-0 libxv1  libtheora0 libva-drm2 libva-x11-2 libvdpau1 libharfbuzz0b libbluray2 libatlas-base-dev libhdf5-103 libgtk-3-0 libdc1394-22 libopenexr23
sudo pip3 install mediapipe-rpi3
```
After getting the successful installed massage on all of the above packages, I tried to import mediapipe in python3 but I get this message:

`Segmentation fault`
After this message python quits automatically.

Even when I wanted to import opencv I get the same message again, but any other packages like numpy, os and ... work fine. Can someone help?

Note: I installed the latest version of raspberry pi os from [here](https://www.raspberrypi.com/software/operating-systems/) and I installed Raspberry Pi OS (Legacy) version.

**Comment by kuaashish** [comment]
Hi @Mousavikia, MediaPipe doesn't have official Python package to install Raspberry pi 3 separately. Could you please follow steps mentioned in the official documentation to build mediapipe in the Edge devices eg. Raspberry pi, Coral board. Thank you!
