### ISSUE TITLE
extract youtube8m features batchly from multiple videos

### ISSUE THREAD

**Issue by xiongjun19** [google/mediapipe#370]
I have managed  to run the example  of extracting features following the guide in youtube 8m. 
but the pipe line seems designed for extracting features of single video. I want to extract features from mulitple videos. it would be very helpful for some instruction .

**Comment by jiuqiant** [comment]
Yes, the pipeline is designed for extracting features from a single video. As you might be aware, the pipeline is already in multithreaded mode and it utilizes as much resources as possible of a single machine. The simplest solution is to write some script to call the following two steps for each video in sequence. If you need to do the video processing in parallel, MediaPipe is able to do it but we haven't had a plan to release that yet.

```
python -m mediapipe.examples.desktop.youtube8m.generate_input_sequence_example \
  --path_to_input_video=/absolute/path/to/the/local/video/VIDEO_ID \
  --clip_end_time_sec=120

bazel-bin/mediapipe/examples/desktop/youtube8m/extract_yt8m_features \
  --calculator_graph_config_file=mediapipe/graphs/youtube8m/feature_extraction.pbtxt \
  --input_side_packets=input_sequence_example=/tmp/mediapipe/metadata.pb  \
  --output_side_packets=output_sequence_example=/tmp/mediapipe/FEATURES_OF_VIDEO_ID.pb
```

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
