### ISSUE TITLE
How can we integrate mediapipe to our custom iOS application?

### ISSUE THREAD

**Issue by pratyushpratik-thesilverlabs** [google/mediapipe#3701]
I have referred to the docs of mediapipe but there is not any feasible way or some package manager to achieve this. 
Also, there is no support for Swift. 
There is only ways through which we can run examples application of mediapipe but none for the integration to custom iOS application.

**Comment by kuaashish** [comment]
Hi @pratyushpratik-thesilverlabs, MediaPipe native APIs C++ can support bindings to Swift.

There is cpp interop which looks like: https://github.com/pschuh/cpp_example/blob/master/Sources/CPPExample/include/example.h
This can be used like: 
https://github.com/pschuh/cpp_example/blob/master/Sources/Example/Basic.swift.

I expect that you'll need a swift wrapper over the c++ code for a while into the future. We have already demo example of custom iOS application contributed by Googler [here](https://github.com/mgyong/awesome-mediapipe#ios). 
Thank you!
