### ISSUE TITLE
I am using detectron2 for Foot keypoint detection . I want to visualize the keypoint heatmaps , can you suggest?

### ISSUE THREAD

**Issue by vikarshiitk** [google/mediapipe#3702]
pred_keypoint_heatmaps: tensor([[[[-1.6246e+00, -2.1436e+00, -3.1817e+00,  ..., -3.0422e+00,
           -2.1779e+00, -1.7458e+00],
          [-1.9384e+00, -2.4925e+00, -3.6006e+00,  ..., -3.4789e+00,
           -2.4824e+00, -1.9841e+00],
          [-2.5661e+00, -3.1902e+00, -4.4384e+00,  ..., -4.3525e+00,
           -3.0912e+00, -2.4606e+00],
          ...,
          [-1.7894e+00, -2.8602e+00, -5.0018e+00,  ..., -5.7117e+00,
           -3.4794e+00, -2.3632e+00],
          [-9.6427e-01, -1.9968e+00, -4.0619e+00,  ..., -3.5743e+00,
           -1.9055e+00, -1.0711e+00],
          [-5.5169e-01, -1.5651e+00, -3.5919e+00,  ..., -2.5057e+00,
           -1.1186e+00, -4.2511e-01]],

I am getting this output after prediction

**Comment by sureshdagooglecom** [comment]
Hi @vikarshiitk ,
Could you share complete steps to reproduce this issue.
