### ISSUE TITLE
New install cannot find face detection models

### ISSUE THREAD

**Issue by monkeyswarm** [google/mediapipe#3704]
Face mesh (and holistic) solutions missing tflite models. (Other solutions such as hand tracking are working fine)

Follow documentation to install and run on MacOS via bazel and C++
On running
`$ GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_mesh/face_mesh_cpu   --calculator_graph_config_file=mediapipe/graphs/face_mesh/face_mesh_desktop_live.pbtxt`

Fails due to missing tflite model:
`E20220918 14:37:27.581456 205329920 demo_run_graph_main.cc:154] Failed to run the graph: Graph has errors: 
Calculator::Open() for node "facelandmarkfrontcpu__facedetectionshortrangecpu__facedetectionshortrange__facedetection__inferencecalculator__facelandmarkfrontcpu__facedetectionshortrangecpu__facedetectionshortrange__facedetection__InferenceCalculator" failed: ; Can't find file: mediapipe/modules/face_detection/face_detection_short_range.tflite`

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): 2018 MacBook Pro (not M1) on MacOS 12.5.1
- [MediaPipe version](https://github.com/google/mediapipe/releases): top of tree, last commit Thu Sep 8 
- Bazel version: 5.2.0
- Solution (e.g. FaceMesh, Pose, Holistic): Face mesh (and holistic)
- Programming Language and version ( e.g. C++, Python, Java): C++

**Describe the expected behavior:**
Solutions run as described in setup docs.

**Standalone code you may have used to try to get what you need :**
No additional code has been written.

**Comment by monkeyswarm** [comment]
Note that I then tried Iris detection, with a similar failure.
I then ran the 'face detection' solution, which, surprisingly, worked.
I went back and tried Iris and Face Mesh, which then started working.

Seems like only running 'Face Detection' solution will download the model? And other solutions find it after?

**Comment by sureshdagooglecom** [comment]
Hi @monkeyswarm ,
We have closed issue running in thread  https://github.com/google/mediapipe/issues/2516 , please check and verify.

**Comment by monkeyswarm** [comment]
Hi @sureshdagooglecom , what about issue #2516 is related to this issue? I am on a different bazel version, and not on an M1 mac. I don't see any mention of builds not finding models in that thread. Please advise.

**Comment by sureshdagooglecom** [comment]
Hi @monkeyswarm ,
Could you please let us know if your issue has been resolved as per the above https://github.com/google/mediapipe/issues/3698#issuecomment-1247905371 Thank you!

**Comment by Fogrunner** [comment]
I wasted whole of day to find why. Please, write somewhere  : the demos are needed to build sequentially.
