### ISSUE TITLE
How to change the color of landmarks in pose tracking for android (pose_tracking_gpu)

### ISSUE THREAD

**Issue by brunobarbieri** [google/mediapipe#3706]
I am using the pose_tracking_gpu in java. It draws all the landmark points and connections of those points. 
How can I change the color of the landmarks and lines?

Got landmarks from:

processor.addPacketCallback(
                OUTPUT_LANDMARKS_STREAM_NAME,
                (packet) -> {
                    //Log.v(TAG, "Received multi-hand landmarks packet.");

                    //Log.v(TAG, packet.toString());
                    byte[] landmarksRaw = PacketGetter.getProtoBytes(packet);
                    try {
                        LandmarkProto.NormalizedLandmarkList landmarks = LandmarkProto.NormalizedLandmarkList.parseFrom(landmarksRaw);
                       ...

**Comment by kuaashish** [comment]
Hi @brunobarbieri, You can find the "RenderData" calculator options in: 

[mediapipe/graphs/pose_tracking/subgraphs/pose_renderer_gpu.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/pose_tracking/pose_tracking_gpu.pbtxt)

Some drawing options like lion color and color thickness can be specified there. For more control over rendering of landmarks, more "RenderData" calculators can be added and invoked in [pose_renderer_gpu.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/pose_tracking/subgraphs/pose_renderer_gpu.pbtxt), or alternatively the landmark coordinates from NormalizedLandmarkList could be rendered directly using Java drawing functions.

Approach is used in solutions such as: [mediapipe/python/solutions/pose_test.py](https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/pose_test.py) and [mediapipe/python/solutions/drawing_utils.py](https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/drawing_utils.py) 

Thank you!
