### ISSUE TITLE
Drive 3D head face

### ISSUE THREAD

**Issue by wizVR-zhangjun** [google/mediapipe#3709]
First of all, thanks to the mediapipe work hard.

I have a problem here that I need your help with. Thank you very much.

There is a 3D head model in my scene, and now I need to map my facial actions to the face of the 3D head model in real time. I need an idea to realize this, please help me

**Comment by wizVR-zhangjun** [comment]
Hi @kuaashish Is there a solution to this problem? Thanks

**Comment by wizVR-zhangjun** [comment]
![ac579b4fffa14a59b08e42654e9c18ee](https://user-images.githubusercontent.com/60952586/192994459-a0a51259-b367-4858-8bc0-fa7cf9b6a1fa.gif)
@kuaashish How does this work? What algorithm is the facial expression based on 
Thank you for your hard work。

**Comment by kuaashish** [comment]
Hi @wizVR-zhangjun, 

This is done through face mesh.  The face mesh landmarks capture details such as month shape and eyes closed.  The face mesh landmarks initially consist of 2d points showing where in the image each landmark occurs.

Using these 2d facemesh landmarks, you could derive some facial feature shifts, relative to the resting face, such as mouth-point shift, eyelid-point shift, etc.  Now given these shift values, you could apply similar shifts to the corresponding features of the  head model rig.  
To measure the shifts in facemesh landmarks most accurately, there is a mediapipe geometry library, 
see : [mediapipe/modules/face_geometry](https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_geometry?q=mediapipe%20geometry).  And a MediaPipe graph, see [face_geometry_from_landmarks.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_effect/subgraphs/single_face_geometry_from_landmarks_gpu.pbtxt). Thank you!

**Comment by wizVR-zhangjun** [comment]
Hi @kuaashish 
First of all, thank you for taking time out of your busy schedule to help me. What puzzles me now is that I do not know how to map the data of 3D facial points to the model. What knowledge points do I need to learn?
Please be patient with my unintelligent student.
thank you!

**Comment by kuaashish** [comment]
Hi @wizVR-zhangjun, 
Please go through this [#3602(comment)](https://github.com/google/mediapipe/issues/3602#issuecomment-1237657056) to understand better in the mapping into 3D facial points. Thank you!
