### ISSUE TITLE
Can I build multi applications in one same aar?

### ISSUE THREAD

**Issue by Sara533** [google/mediapipe#371]
Can I build multi applications in one same aar?
For example:build hand tracking and object tracking into an aar together, and then I could implement hand tracking or object tracking by only one aar.

I have tried this work, but failed.
`mediapipe_aar(
    name = "mediapipe_aar",
    calculators = [
	"//mediapipe/graphs/hand_tracking:mobile_calculators",
	"//mediapipe/graphs/tracking:mobile_calculators",
],
)`
It was OK to build the aar,.
But when I used the aar in android studio to run the app, it was failed.
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN2cv3Mat20updateContinuityFlagEv" referenced by "/data/app/com.example.handtracking-KOEkMvNA074xIxID1P7blA==/lib/arm64/libmediapipe_jni.so"...`

**Comment by jiuqiant** [comment]
I think it's possible to have multiple applications in one AAR. The AAR will contain the MediaPipe framework and a collection of calculators for hand tracking and object tracking.
The compiler complains about missing symbol "_ZN2cv3Mat20updateContinuityFlagEv". Therefore, the error seems to be the undefined reference to cv::Mat::updateContinuityFlag(). Have you put the libopencv_java3.so into your Android Studio project?

**Comment by Moufdi96** [comment]
@Sara533 I need to use hand tracking and face detection in one Android app, and I am wondering if you succeeded to solve this issue ?

**Comment by Moufdi96** [comment]
> Can I build multi applications in one same aar?
> For example:build hand tracking and object tracking into an aar together, and then I could implement hand tracking or object tracking by only one aar.
> 
> I have tried this work, but failed.
> `mediapipe_aar( name = "mediapipe_aar", calculators = [ "//mediapipe/graphs/hand_tracking:mobile_calculators", "//mediapipe/graphs/tracking:mobile_calculators", ], )`
> It was OK to build the aar,.
> But when I used the aar in android studio to run the app, it was failed.
> `java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN2cv3Mat20updateContinuityFlagEv" referenced by "/data/app/com.example.handtracking-KOEkMvNA074xIxID1P7blA==/lib/arm64/libmediapipe_jni.so"...`

@Sara533 I need to use hand tracking and face detection in one Android app, and I am wondering if you succeeded to solve this issue ?
