### ISSUE TITLE
Crash during model serialization if OpenCL not initialized (InferenceCalculator)

### ISSUE THREAD

**Issue by vertify-mldev1** [google/mediapipe#3710]
The inference calculator crashes if model caching is activated (via serialized_model_dir and model_token options) and TFLiteGPURunner falls back to OpenGL api (i.e. when OpenCL initialization fails).
The crash occurs during model serialization on [this line](https://github.com/google/mediapipe/blob/cc6a2f7af65977248b2a15f471503da2832f583a/mediapipe/util/tflite/tflite_gpu_runner.cc#L281) since cl_environment_ is a null pointer.
I tested it on a Google Pixel 2 which doesn't have the OpenCL library.
Alternatively you can set targetSdkVersion in app/build.gradle to 31 or above and OpenCL won't be linked by default.

**System information** (Please provide as much relevant information as possible)
- OS / used build tools
Android 12
NDK: 21.3.6528147
SDK: 30
Build tools: 30.0.3
- Installed using virtualenv? pip? Conda? (if python):
no
- [MediaPipe version](https://github.com/google/mediapipe/releases):
0.8.11
- Bazel version:
5.3.0

**Comment by kuaashish** [comment]
Hi @vertify-mldev1, 
Could you please provide the complete details about the issue, which solution you are referring to and steps to reproduce the issue from our end. Thank you!
