### ISSUE TITLE
MediaPipe.js can't be used on website with TrustedType enforced

### ISSUE THREAD

**Issue by liuyinglao** [google/mediapipe#3711]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

We are trying to run mediapipe holistic on Chrome and when it is loading the holistic_solution_simd_wasm_bin.js file, it complains that the file violate the TrustedType policy.  

- MediaPipe Solution (you are using): MediaPipe Holistic (https://google.github.io/mediapipe/solutions/holistic.html#pose_landmarks)
- Programming language : javascript with flow.js

- Are you willing to contribute it (Yes/No):
Yes, but may only with spare time

**Describe the feature and the current behavior/state:**
Currently if the website use TrustedType

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Eventually, Chrome will expect more and more sites and libs to use TrustedType. So I expect every team who want their website run on Chrome?

**Please specify the use cases for this feature:**
we are building a features based on mediapipe to capture user action for interaction.

**Comment by kuaashish** [comment]
Hello@liuyinglao,

Closing this issue as seems to be hosting problem, You should host the dependencies by yourself. However, We will be further not able to provide the support on it. Thank you!
