### ISSUE TITLE
Can the mediapipe infer multiple images at the same time

### ISSUE THREAD

**Issue by lofyol** [google/mediapipe#3712]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using):
- Programming language : C++/typescript/Python/Objective C/Android Java
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state:**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Please specify the use cases for this feature:**

**Any Other info:**

**Comment by kuaashish** [comment]
Hi @lofyol, 
Could you please elaborate your query with complete details and solution which you referring to. Thank you!

**Comment by lofyol** [comment]
> Hi @lofyol, Could you please elaborate your query with complete details and solution which you referring to. Thank you!

At present, the human body key point detection under the python solution can only infer one image at a time, but I wonder if I can infer multiple images at the same time, because there is a need to infer multiple video streams at the same time

**Comment by lofyol** [comment]
<-_->

**Comment by lofyol** [comment]
<_-_>

**Comment by lofyol** [comment]
<_-_>

**Comment by lofyol** [comment]
<-_——>

**Comment by kuaashish** [comment]
Hi @lofyol, Sorry for the late response. Please refer to this closed issue #3273 and [#3273(comment](https://github.com/google/mediapipe/issues/3273#issuecomment-1232717734)) for your query. Thank you!

**Comment by lofyol** [comment]
> Hi @lofyol, Sorry for the late response. Please refer to this closed issue #3273 and [#3273(comment](https://github.com/google/mediapipe/issues/3273#issuecomment-1232717734)) for your query. Thank you!

This is not an official multi image reasoning

**Comment by kuaashish** [comment]
Hi @lofyol, MediaPipe does not have any official documentation and examples to infer the multiple images at a loop. Please follow the workaround mentioned which is contributed by the community. Thank you!
