### ISSUE TITLE
Docker build on Win10 will not run helloworld

### ISSUE THREAD

**Issue by ybott** [google/mediapipe#3714]
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 10

Using mediapipe master the docker helloworld instance does not work correctly. 
https://google.github.io/mediapipe/getting_started/install#installing-using-docker

Step 2

`
PS \mediapipe> docker build --tag=mediapipe .
[+] Building 1411.2s (20/20) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                               0.0s
 => => transferring dockerfile: 2.75kB                                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                                                  0.0s
 => => transferring context: 58B                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                                    3.9s
 => [ 1/15] FROM docker.io/library/ubuntu:20.04@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16                                                                                            5.4s
 => => resolve docker.io/library/ubuntu:20.04@sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16                                                                                              0.0s
 => => sha256:35ab2bf57814e9ff49e365efd5a5935b6915eede5c7f8581e9e1b85e0eecbe16 1.42kB / 1.42kB                                                                                                                     0.0s
 => => sha256:a0a45bd8c6c4acd6967396366f01f2a68f73406327285edc5b7b07cb1cf073db 529B / 529B                                                                                                                         0.0s
 => => sha256:a0ce5a295b637a10bc329ded296a0c895e5e56e7c5e674188d423e213b0d213e 1.46kB / 1.46kB                                                                                                                     0.0s
 => => sha256:675920708c8bf10fbd02693dc8f43ee7dbe0a99cdfd55e06e6f1a8b43fd08e3f 28.57MB / 28.57MB                                                                                                                   4.6s
 => => extracting sha256:675920708c8bf10fbd02693dc8f43ee7dbe0a99cdfd55e06e6f1a8b43fd08e3f                                                                                                                          0.6s
 => [internal] load build context                                                                                                                                                                                  2.3s
 => => transferring context: 56.76MB                                                                                                                                                                               2.3s
 => [ 2/15] WORKDIR /io                                                                                                                                                                                            0.1s
 => [ 3/15] WORKDIR /mediapipe                                                                                                                                                                                     0.0s
 => [ 4/15] RUN apt-get update && apt-get install -y --no-install-recommends         build-essential         gcc-8 g++-8         ca-certificates         curl         ffmpeg         git         wget           1193.2s
 => [ 5/15] RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8                                                                                          0.5s
 => [ 6/15] RUN pip3 install --upgrade setuptools                                                                                                                                                                  2.6s
 => [ 7/15] RUN pip3 install wheel                                                                                                                                                                                 1.1s
 => [ 8/15] RUN pip3 install future                                                                                                                                                                                2.2s
 => [ 9/15] RUN pip3 install absl-py numpy opencv-contrib-python protobuf==3.20.1                                                                                                                                 17.4s
 => [10/15] RUN pip3 install six==1.14.0                                                                                                                                                                           1.2s
 => [11/15] RUN pip3 install tensorflow==2.2.0                                                                                                                                                                   163.9s
 => [12/15] RUN pip3 install tf_slim                                                                                                                                                                               1.9s
 => [13/15] RUN ln -s /usr/bin/python3 /usr/bin/python                                                                                                                                                             0.4s
 => [14/15] RUN mkdir /bazel &&     wget --no-check-certificate -O /bazel/installer.sh "https://github.com/bazelbuild/bazel/releases/download/5.2.0/bazel-5.2.0-installer-linux-x86_64.sh" &&     wget --no-chec  10.9s
 => [15/15] COPY . /mediapipe/                                                                                                                                                                                     0.2s
 => exporting to image                                                                                                                                                                                             6.3s
 => => exporting layers                                                                                                                                                                                            6.3s
 => => writing image sha256:ca1ef6eb4def98f151709a727a78949b09a8ba71435eefc096d714672aba361c                                                                                                                       0.0s
 => => naming to docker.io/library/mediapipe   
`

Step 3

`root@0a22b0c9215b:/mediapipe# GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world
 (specified in /mediapipe/.bazelversion), but it wasn't found in /usr/local/lib/bazel/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

You can download the required version directly using this command:
-linux-x86_64)&& chmod +x bazel-5.2.0url -fLO https://releases.bazel.build/5.2.0
`

**Comment by kuaashish** [comment]
Hi @ybott, 
Could you please provide the complete error log to investigate the issue further. Thank you!

**Comment by ybott** [comment]
Hi @kuaashish, thanks for looking at this. I am unable to provide more information.
I followed the installation instructions from the docker section of the getting started page. Step 1 was to install docker. Step 2 was to build the docker instance. Step 3 failed to find bazel within the docker image and resulted in the above error log. Are there more error logs? Can you tell me where they are?

**Comment by schmidt-sebastian** [comment]
Can you confirm whether you can install Bazel in Docker? Your logs show an install of version 5.2.0, but no output to verify this step.

**Comment by kuaashish** [comment]
Hi @ybott, Could you go through the [above](https://github.com/google/mediapipe/issues/3714#issuecomment-1275292656) comment and let us know the required input. Thank you!
