### ISSUE TITLE
Are you Chinese? If so, I will use Chinese.

### ISSUE THREAD

**Issue by ZSDXC** [google/mediapipe#3716]
Hi, 我也遇到了同样的问题，QueueSize()一直为0 ，但是可以获取到数据。但是当检测不到数据的时候就会卡死在pose_poller->Next(&pose_pack)。你遇到过这种问题吗？
if (pose_poller != nullptr)
	{
		std::cout << "====pose in====  size: "<< pose_poller->QueueSize() << std::endl;
		mediapipe::Packet pose_pack;
		
		if (pose_poller->Next(&pose_pack))
		{
			auto& output_landmarks = pose_pack.Get<mediapipe::NormalizedLandmarkList>();
			std::cout << "pose size: " << output_landmarks.landmark_size() << std::endl;
			pose.clear();
			for (int i = 0; i < output_landmarks.landmark_size(); i++)
			{
				cv::Point2f p;
				const mediapipe::NormalizedLandmark landmark = output_landmarks.landmark(i);
				p.x = landmark.x() * camera_frame.cols;
				p.y = landmark.y() * camera_frame.rows;
				pose.emplace_back(p);
			}
		}
	}

**Comment by kuaashish** [comment]
Hi @ZSDXC, 
Could you please elaborate your query with complete details and steps to reproduce the issue from our end. Thank you!
