### ISSUE TITLE
Closing as stale. Please reopen if you'd like to work on this further.

### ISSUE THREAD

**Issue by peter6053** [google/mediapipe#3719]
Closing as stale. Please reopen if you'd like to work on this further.

_Originally posted by @google-ml-butler[bot] in https://github.com/google/mediapipe/issues/3212#issuecomment-1099061984_

**Comment by peter6053** [comment]
<img width="684" alt="ERRO4" src="https://user-images.githubusercontent.com/35918656/192137746-69ec74de-d2c8-475d-9a78-dc25fc4f8bf0.png">

This is still an issie

**Comment by sureshdagooglecom** [comment]
Hi @peter6053 ,
We are marking it as duplicate issue since we have similar issue running on thread https://github.com/google/mediapipe/issues/3214

**Comment by ayushgdev** [comment]
@peter6053 
Are you still looking for resolution on this issue? 
From the terminal output, it seems like you are not using official mediapipe repository, rather trying some tutorial project on android. With third-party or user created repositories as well, WORKSPACE file defines a folder as a bazel workspace. In the official mediapipe repository, in WORKSPACE _file_, only two lines need to be added to configure the android ecosystem for mediapipe.
```
android_sdk_repository(name = "androidsdk", api_level=33, build_tools_version="<YOUR_BUILD_TOOL_VERSION>")
android_ndk_repository(name = "androidndk", api_level=21)
```
Please check if you have duplicate android_sdk_repository() call in the workspace file. This might be conflicting and raising the error.

**Comment by ArtanBerisha1** [comment]
Hi @ayushgdev , I am having the same issue, 
When I run 
`android_ndk_repository(name = "androidndk", api_level=21)`
I get the following error:
`zsh: number expected`

same for the previous command, but there I don't know how to find the build tool version

**Comment by ayushgdev** [comment]
Hi @ArtanBerisha1 
`android_ndk_repository(name = "androidndk", api_level=21)` is not a command for shell but rather to be included in the WORKSPACE.bazel file (.bazel is optional as per bazel naming convention). Please refer the image below. There are two lines added in the WORKSPACE file. Those are the required ones:


<img width="851" alt="Screen Shot 2022-12-12 at 10 05 20 AM" src="https://user-images.githubusercontent.com/118424249/206961933-0a173b20-c909-4aaf-9209-838e255de7f9.png">

Further, to know the build tools version, follow the steps below:
1. Open Android Studio. 
2. Go to Tools -> SDK manager
3. Go to SDK Tools tab
4. Expand **Android Build SDK-Tools** section. You will see one of the build tools version checked with status installed. If not, please consider installing version 30.0.3.
5. Expand **NDK(Side by Side)** section. You will see one of the NDk tools version checked with status installed. If not, consider installing version 21.1.6352462.
