### ISSUE TITLE
Cant run setup_android_sdk_and_ndk.sh with docker

### ISSUE THREAD

**Issue by Acimaz** [google/mediapipe#372]
Im unable to setup the sdk and ndk on my docker container:

`root@7b0554079dc6:/mediapipe# bash ./setup_android_sdk_and_ndk.sh
./setup_android_sdk_and_ndk.sh: line 22: $'\r': command not found
: invalid optionsdk_and_ndk.sh: line 23: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./setup_android_sdk_and_ndk.sh: line 24: $'\r': command not found
./setup_android_sdk_and_ndk.sh: line 27: syntax error near unexpected token `elif'
'/setup_android_sdk_and_ndk.sh: line 27: `elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then`

and thus, unable to build.

**Comment by jiuqiant** [comment]
What's the host platform you are on?

I just run the setup_android_sdk_and_ndk.sh in a docker container on Debian and it works ok.

```bash
root@9d162953b2a8:/mediapipe# bash ./setup_android_sdk_and_ndk.sh
Warning: android_sdk_path (argument 1) is not specified. Fallback to ~/Android/Sdk/
Warning: android_ndk_path (argument 2) is not specified. Fallback to ~/Android/Sdk/ndk-bundle/android-ndk-<NDK_VERSION>/
Warning: ndk_version (argument 3) is not specified. Fallback to r18b.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 52  147M   52 77.8M    0     0  90.3M      0  0:00:01 --:--:--  0:00:01 90.2M^C
root@af9c90e9564e:/mediapipe# bash ./setup_android_sdk_and_ndk.sh
Warning: android_sdk_path (argument 1) is not specified. Fallback to ~/Android/Sdk/
Warning: android_ndk_path (argument 2) is not specified. Fallback to ~/Android/Sdk/ndk-bundle/android-ndk-<NDK_VERSION>/
Warning: ndk_version (argument 3) is not specified. Fallback to r18b.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  147M  100  147M    0     0  97.6M      0  0:00:01  0:00:01 --:--:-- 97.6M
Archive:  /tmp/android_sdk/android_sdk.zip
......
Android NDK is now installed. Consider setting $ANDROID_NDK_HOME environment variable to be /root/Android/Sdk/ndk-bundle/android-ndk-r18b
Set android_ndk_repository and android_sdk_repository in WORKSPACE
Done
```

**Comment by Acimaz** [comment]
Well, I ran it on a Windows machine, and that's probably why it didn't work. I misunderstood the way docker works and I thought it doesn't matter which host machine is running.

**Comment by AjManoj** [comment]
When docker copied files from windows to docker, windows line ending also gets copied.So to convert them linux line endings run following 

`sed -i -e 's/\r$//' setup_android_sdk_and_ndk.sh`

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by thecoder-elite** [comment]
Thank you @AjManoj your solution works!

**Comment by MoatazNoaman2001** [comment]
> When docker copied files from windows to docker, windows line ending also gets copied.So to convert them linux line endings run following
> 
> `sed -i -e 's/\r$//' setup_android_sdk_and_ndk.sh`

it magic
