### ISSUE TITLE
hello_world  build failed

### ISSUE THREAD

**Issue by simzhangbest** [google/mediapipe#3721]
windows 11 
visual studio 2019

![image](https://user-images.githubusercontent.com/24918900/192190251-7fcc8701-c720-4a49-95ae-ab485abe6d18.png)

**Comment by simzhangbest** [comment]
`WARNING: D:/workspace_sim/mediapipe/mediapipe/framework/tool/BUILD:185:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (79 packages loaded, 1673 targets configured).
INFO: Found 1 target...
ERROR: C:/users/15301/_bazel_15301/r4lpv3cd/external/com_github_gflags_gflags/BUILD:16:30: Executing genrule @com_github_gflags_gflags//:gflags_h failed: (Exit -1): tools failed: error executing command C:\tools -c ... (remaining 1 argument skipped)
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\tools" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; awk '{ gsub(/@GFLAGS_ATTRIBUTE_UNUSED@/, \"\"); gsub(/@INCLUDE_GFLAGS_NS_H@/, \"#include \\\"gflags/gflags_google.h\\\"\"); print; }' external/com_github_gflags_gflags/src/gflags.h.in > bazel-out/x64_windows-opt/bin/external/com_github_gflags_gflags/gflags.h"): 鎷掔粷璁块棶銆?
 (error: 5)
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 28.680s, Critical Path: 0.15s
INFO: 33 processes: 33 internal.
FAILED: Build did NOT complete successfully`

log file is here

**Comment by simzhangbest** [comment]
using build command :
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D://ProgramData//Anaconda3//envs//d2l//python.exe"  mediapipe/examples/desktop/hello_world --verbose_failures`

**Comment by kuaashish** [comment]
Hi @simzhangbest, We are closing this issue as a duplicate and already tracking with another issue #3715. Thank you!

**Comment by jojinshallar** [comment]
I got the same problem.Is there any solution?

**Comment by 2197808908a** [comment]
> using build command : `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D://ProgramData//Anaconda3//envs//d2l//python.exe" mediapipe/examples/desktop/hello_world --verbose_failures`

@simzhangbest I tried a command with --verbose_failures' and it didn't work
