### ISSUE TITLE
How to build mediapie for Windows x86?

### ISSUE THREAD

**Issue by HzHzHzHzHz** [google/mediapipe#3722]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment]
Hi @HzHzHzHzHz, 
Could you please elaborate your query with complete details and steps to reproduce the issue from our end. Thank you!

**Comment by HzHzHzHzHz** [comment]
>The official documentation describes the Mediapipe example build for Windows x64, but what should I do if I want to build the Windows x86 example? Does Mediapipe only support x64 build on Windows?

**Comment by HzHzHzHzHz** [comment]
The official documentation describes the Mediapipe example build for Windows x64, but what should I do if I want to build the Windows x86 example? Does Mediapipe only support x64 build on Windows? @kuaashish

**Comment by kuaashish** [comment]
Hi @HzHzHzHzHz,
Mediapipe doesn't support 32-bit python. all of the [wheels](https://pypi.org/project/mediapipe/#files) are for 64-bit python.
