### ISSUE TITLE
Is there any way around to disable unsafe-eval for JavaScript?

### ISSUE THREAD

**Issue by github-itsec-oculavis** [google/mediapipe#3723]
### Problem

Mediapipe library doesn't work without enabling unsafe-eval in JavaScript, that may lead to cross site scripting attacks, is there any way to use library without unsafe eval?

**Comment by kuaashish** [comment]
Duplicate of #3458

**Comment by kuaashish** [comment]
Hi @github-itsec-oculavis, We are following up with the issue #3458 and will revert back if there is any specific update on issue. Thank you!

**Comment by github-itsec-oculavis** [comment]
> Hi @github-itsec-oculavis, We are following up with the issue #3458 and will revert back if there is any specific update on issue. Thank you!

Hi @kuaashish I had a look there, nobody is responding to that issue.

**Comment by kuaashish** [comment]
Hi @github-itsec-oculavis, Looks like we could do that but we would need to publish new packages. There might be some downsides so I am not sure that we will do so (at least not in the near future). Thank you!

**Comment by nskaiser** [comment]
This is a big problem for anyone that wants to use MediaPipe and a Chrome Extension now that Manifest v3 is required. Is there any movement on this at Google? Thanks.

**Comment by mmerezhko-hv** [comment]
Any roadmap updates about CSP issues?
