### ISSUE TITLE
[Javascript mediapipe] Isn't there no poseWorldLandmarks in mediapipe js

### ISSUE THREAD

**Issue by ajs3801** [google/mediapipe#3724]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic):
- Programming Language and version ( e.g. C++, Python, Java):

**Describe the expected behavior:**

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by ajs3801** [comment]
Could you see the url I wrote in stackoverflow? (https://stackoverflow.com/questions/73760591/is-there-poseworldlandmarks-in-mediapipe-javascript). 
I try to make web AI implemented by python before. But I found that there is no pose_worldlandmarks in javascript. Is there a poseWorldLandmarks?

**Comment by kuaashish** [comment]
Hi @ajs3801, Please refer to this closed issue #2261 for your query. Thank you!

**Comment by ajs3801** [comment]
Thank you, sir. Now I will try it. Thanks!
