### ISSUE TITLE
Debug framework with Xcode

### ISSUE THREAD

**Issue by yousifa** [google/mediapipe#3726]
Hi,

How can I debug / view source from an xcode project that is using a framework compiled w/ mediapipe? I am unable to hit any symbolic breakpoints even (maybe an example here would help).

**Comment by kuaashish** [comment]
Hi @yousifa, Please refer to this [Mediapipe: How to configure debugger? ](https://stackoverflow.com/questions/72488330/mediapipe-how-to-configure-debugger-using-vs-code-and-bazel)issue for your query. Thank you!
