### ISSUE TITLE
How to get/create Mediapipe Hands training dataset? 

### ISSUE THREAD

**Issue by SSopin** [google/mediapipe#3727]
Hello,

I need to fine tune MediaPipe Hands to recognize a couple more landmarks, however, it is not clear how to train it since Mediapipe datasets aren't public. I'd like to create my own dataset, however it is not clear how landmark target values were calculated, which is important because I want my landmarks to be consistent with the ones provided by MediaPipe Hands. Could you please suggest how to do that?
Thanks!

**Comment by kuaashish** [comment]
Hi @SSopin, Please refer to this closed issue #3410 and [#3410(comment)](https://github.com/google/mediapipe/issues/3410#issuecomment-1156394511) for your query. Thank you!

**Comment by SSopin** [comment]
Hi @kuaashish. 
Thank you for your response. It seems you are referring to the answer related to fine tuning and using custom models within MediaPipe which is very helpful. My question was mostly about dataset creation. I am just curious how target landmarks were calculated for the initial training dataset? I want to recreate the process so that my training data is consistent with MediaPipe one. 

For example, did you take pictures using LiDAR Depth Camera to calculate target Z index, while target values for X and Y coordinates were calculated based on screen coordinates? Or you used some other methods to calculate target coordinates? 
Thanks.

**Comment by kuaashish** [comment]
Hi @SSopin, Hope this issue #742 and [#742(comment)](https://github.com/google/mediapipe/issues/742#issuecomment-639104199) will give a better understanding for your query. Thanks!
