### ISSUE TITLE
Modify CalculatorGraphConfig using Java API

### ISSUE THREAD

**Issue by physxP** [google/mediapipe#3731]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): macos m1
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.11
- Bazel version: 5.2.0
- Solution (e.g. FaceMesh, Pose, Holistic): Pose - TensorsToDetectionsCalculator
- Programming Language and version ( e.g. C++, Python, Java): Java

**Describe the expected behavior:**
Java Graph located at `mediapipe/java/com/google/mediapipe/framework/Graph.java` should be able to modify the graph but I can't figure out how to read node options
**Standalone code you may have used to try to get what you need :**
I have a class that extends the `ImageSolutionsBase` class. In the constructor I have following code:

```java
// get graph config
CalculatorProto.CalculatorGraphConfig config = solutionGraph.getCalculatorGraphConfig();
// search required node
CalculatorProto.CalculatorGraphConfig.Node detectionConfidenceNode = config.getNodeList().stream().filter(node -> Objects.equals(node.getCalculator(), "TensorsToDetectionsCalculator")).findFirst().get();
// get node options
CalculatorOptionsProto.CalculatorOptions nodeOpts = detectionConfidenceNode.getOptions();


```
I get the node nodeOpts but it contains binary values, how do I modify these options?
What I need is the actual node options from this so I can modify min_confidence_threshold.

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment]
Hi @physxP,
Could you please elaborate your query with complete details and followed steps to reproduce the issue from our end. Thank you!
