### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by asd26187** [google/mediapipe#3733]
error: In target "//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp_entitlements"; the bundle_id ("com.google.mediapipe.HelloWorlds") did not match the id in the entitlements ("934dcfe0-9c89-e925d94b1.mediapipe.examples.FaceDetectionCpu").

When I compile the project with xcode13.4.1, I get an error about the bundle id, I don't have this bundle id set. I want to know the file where the entitlements are located? How should I go about changing it?

**Comment by kuaashish** [comment]
Hi @asd26187, Could you confirm that you have changed the `bundle identifier` as configured the provisioning profile. Please follow [this](https://qiita.com/ponte1010/items/ed10cb2b5dcf7579f9bc#2-change-bundle-identifier) reference for your query. Thank you!

**Comment by asd26187** [comment]
Yes, I am sure I have changed the bundle_id="com.google.mediapipe.HelloWorlds" in the BUILD file. I want to configure this bundle_id for all BUILD files, but I found that maybe I can run it in helloworld project, but in other projects it will report error, how should I configure bundle_id in BUILD file and BUNDLE_ID_PREFIX in bundle_id.bzl file?

**Comment by kuaashish** [comment]
Hi @asd26187, You need a different bundle id for a different solution to build. Please follow the above reference and try to change them accordingly. Thank you!

**Comment by asd26187** [comment]
Yes, following your method, changing the corresponding bundle_id will allow me to run different projects, but this will lead to a new problem, that I will have many apps on my phone, if I want to integrate all the functions in one app, how should I do it? Thanks

**Comment by kuaashish** [comment]
Hi @asd26187, Please follow the instructions mentioned in the official [documentation](https://google.github.io/mediapipe/getting_started/ios.html#set-up-a-bundle-id-prefix) to set up a bundle id prefix for all mediapipe examples. Thank you!

**Comment by asd26187** [comment]
@kuaashish  But the documentation does not write out how the bundle_id prefix should be set globally and how the bundle_id of individual projects should be set? Or could you please tell me how I should be able to compile all the functions in the example into a framework so that I can use all the functions in one project.thx!

**Comment by kuaashish** [comment]
Hello @asd26187,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
