### ISSUE TITLE
Get the 3d coordinate output of the model

### ISSUE THREAD

**Issue by Youmimzy** [google/mediapipe#3735]
This template is for miscellaneous issues not covered by the other issue categories

For questions on how to work with MediaPipe, or support for problems that are not verified bugs in MediaPipe, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mediapipe) and [Slack](https://mediapipe.page.link/joinslack) communities.

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/google/mediapipe/security).
Compile the library inference model directly with tensorflowlite。I modified my own code to get the normalized real world x, y, z coordinates through the following official code.
![image](https://user-images.githubusercontent.com/49750484/192768304-16931c81-235b-4836-b159-2aef106f5c01.png)
![image](https://user-images.githubusercontent.com/49750484/192768168-e815dc9b-9662-4f96-b6e0-3fc888287d32.png)
But the output doesn't seem to be correct, what am I doing wrong?

**Comment by sureshdagooglecom** [comment]
Hi @Youmimzy ,
On Android Hands gradle you can find the result of https://github.com/google/mediapipe/blob/d4bb35fe5a44b3419ca86e4c7ecbc931dded2122/mediapipe/java/com/google/mediapipe/solutions/hands/HandsResult.java#:~:text=//%20Collection%20of%20detected/tracked%20hands%27%20landmarks,%7D. To run on GPU you should enable runOnGput to True
