### ISSUE TITLE
How do I train my own object detection model?

### ISSUE THREAD

**Issue by dubrovin-sudo** [google/mediapipe#3736]
Dear colleagues?

Whether the mediapipe allows retraining the Object Detection graph?  At the moment, the mediapipe offers a standard solution for a standard dataset (probably COCO). But I want to detect ear. How do I train my model and use it in the mediapipe?

I didn't find obvious solutions in the documentation

**Comment by kuaashish** [comment]
Hi @dubrovin-sudo, For now, MediaPipe doesn't provide any model-training or model-tuning libraries or tools. However, MediaPipe team is actively researching adding such a tool.  
Workaround, If you use Tensoflow to train a new object detection model, MediaPipe can consume the new model through the configurations of the MediaPipe solutions. Thank you!
