### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by serrabii** [google/mediapipe#3737]
Hi,

> For questions on how to work with MediaPipe, or support for problems that are not verified bugs in MediaPipe, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mediapipe) and [Slack](https://mediapipe.page.link/joinslack) communities.

I am unable to join the MediaPipe Slack Channel. The slack invite linked above is restricted to @google.com emails. Is the slack channel not a public community?

Thanks in advance

**Comment by kuaashish** [comment]
Hi @serrabii, Could you please join through [this](https://join.slack.com/t/mediapipe/shared_invite/zt-1gygl2lpu-4UxAPsr8e8qMb8vmQuCXxw) invitation and let us know if you are part of official MediaPipe slack channel. Thank you!

**Comment by serrabii** [comment]
Many thanks for the quick response, that invite links worked and I have joined the official MediaPipe slack channel!

**Comment by kuaashish** [comment]
Hi @serrabii, Glad to hear that you are part of the MediaPipe channel. Could we move this issue to close status as it has been resolved. Thank you!

**Comment by kuaashish** [comment]
Hi @franckOL,
Seems the invitation link has been expried. Could you join through this [invitation](https://join.slack.com/t/mediapipe/shared_invite/zt-1jqmrzg34-waJBaqdLt7_228BUOgxPwg) and let us know if you are part of the slack community. Thank you!

**Comment by joshuadeguzman** [comment]
Hey @kuaashish, thank you for the link, I think we should update the docs with a non-expiring link to join Slack!
