### ISSUE TITLE
objectdetection3d build to android sdk error: fetching 2 tflite files failed

### ISSUE THREAD

**Issue by RoachNier** [google/mediapipe#3742]
Hi~I have problems in building objectdetection3d to android sdk on Ubuntu. The error is:
```
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @com_google_mediapipe_object_detection_ssd_mobilenetv2_oidv4_fp16_tflite; fetching
    Fetching @com_google_mediapipe_object_detection_3d_sneakers_tflite; fetching
```
However, I succeeded in building objectdetectiongpu and a few other applications. I checked the tflite file and found it is in third_party/external_files.bzl, and also there is urls:
`    http_file(
        name = "com_google_mediapipe_object_detection_ssd_mobilenetv2_oidv4_fp16_tflite",
        sha256 = "d0a5255bf8c4f5a0bc4240741a76c41d5e939f7655078f945f50ab53a9375da6",
        urls = ["https://storage.googleapis.com/mediapipe-assets/object_detection_ssd_mobilenetv2_oidv4_fp16.tflite?generation=1661875879063676"],
    )`
The urls is good that I can download tflite directly from browser but I can not download when I use bazel command to build as I questioned below.
Can anyone tells me how to fix it? Maybe I can copy the tflite files into some directories so that I can skip the downloading in bazel building? 
Thanks!

**Comment by RoachNier** [comment]
And now the Error turns into:
`ERROR: /home/aiserver/projects/mediapipe/mediapipe/graphs/object_detection_3d/calculators/BUILD:22:24: no such target '//mediapipe/gpu:gl_animation_overlay_calculator_cc_proto': target 'gl_animation_overlay_calculator_cc_proto' not declared in package 'mediapipe/gpu' defined by /home/aiserver/projects/mediapipe/mediapipe/gpu/BUILD and referenced by '//mediapipe/graphs/object_detection_3d/calculators:gl_animation_overlay_calculator_cc_proto'
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d:objectdetection3d' failed; build aborted: 
INFO: Elapsed time: 0.186s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 9827 targets configured)`

I strictly followed the tutotial and the command I use is :
`bazel build -c opt --config android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d:objectdetection3d`

**Comment by kuaashish** [comment]
Hi @RoachNier, Could you please follow[ this](https://github.com/google/mediapipe/issues/3698#issuecomment-1247905371) comment and let us know if this resolves the issue. Thank you!

**Comment by kuaashish** [comment]
Hi @RoachNier, 
Could you please confirm the issue has been resolved as per the above [comment](https://github.com/google/mediapipe/issues/3742#issuecomment-1263151129) or still you are looking for the resolution.
Thank you!

**Comment by MarsH2o2** [comment]
I have the same problem,

Execute ./build_android_examples.sh in the root directory

The following error is reported:
ERROR: /mnt/e/mediapipe/mediapipe/graphs/object_detection_3d/calculators/BUILD:22:24: no such target '//mediapipe/gpu:gl_animation_overlay_calculator_cc_proto': target 'gl_animation_overlay_calculator_cc_proto' not declared in package 'mediapipe/gpu' defined by /mnt/e/mediapipe/mediapipe/gpu/BUILD and referenced by '//mediapipe/graphs/object_detection_3d/calculators:gl_animation_overlay_calculator_cc_proto'
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking' failed; build aborted:

**Comment by MarsH2o2** [comment]
@kuaashish

**Comment by MarsH2o2** [comment]
I have the same problem,

Execute ./build_android_examples.sh in the root directory

The following error is reported:
ERROR: /mnt/e/mediapipe/mediapipe/graphs/object_detection_3d/calculators/BUILD:22:24: no such target '//mediapipe/gpu:gl_animation_overlay_calculator_cc_proto': target 'gl_animation_overlay_calculator_cc_proto' not declared in package 'mediapipe/gpu' defined by /mnt/e/mediapipe/mediapipe/gpu/BUILD and referenced by '//mediapipe/graphs/object_detection_3d/calculators:gl_animation_overlay_calculator_cc_proto'
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking' failed; build aborted:

@kuaashish

**Comment by kuaashish** [comment]
Hi @RoachNier, We are following up with the issue #3759 raised. @RoachNier, Could you please update the system information as mentioned in the [documentation](https://github.com/google/mediapipe/issues/3759). Thank you!
