### ISSUE TITLE
(ANDROID) mediapipe::CalculatorGraph Initialize failed by mediapipe::CalculatorGraphConfig

### ISSUE THREAD

**Issue by fishhead012** [google/mediapipe#3744]
// Step
1. create config(mediapipe::CalculatorGraphConfig) from holistic_gpu.pbtxt 
2. mediapipe::CalculatorGraph->Initialize(config)
3. log as below Initialization failed

anyone know how to fix it?  :D

// LOG
UNKNOWN: ValidatedGraphConfig Initialization failed.
SplitNormalizedLandmarkListCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
SplitDetectionVectorCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
SplitNormalizedLandmarkListCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
SplitNormalizedLandmarkListCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
ImageToTensorCalculator: ; RET_CHECK failure (external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:146) options.has_output_tensor_float_range() || options.has_output_tensor_int_range() || options.has_output_tensor_uint_range()Output tensor range is required.
ImageToTensorCalculator: ; RET_CHECK failure (external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:146) options.has_output_tensor_float_range() || options.has_output_tensor_int_range() || options.has_output_tensor_uint_range()Output tensor range is required.
ImageToTensorCalculator: ; RET_CHECK failure (external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:146) options.has_output_tensor_float_range() || options.has_output_tensor_int_range() || options.has_output_tensor_uint_range()Output tensor range is required.
ImageToTensorCalculator: ; RET_CHECK failure (external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:146) options.has_output_tensor_float_range() || options.has_output_tensor_int_range() || options.has_output_tensor_uint_range()Output tensor range is required.
InferenceCalculatorGl: ; RET_CHECK failure (external/com_google_mediapipe/mediapipe/calculators/tensor/inference_calculator_gl.cc:93) !options.model_path().empty() ^ kSideInModel(cc).IsConnected()Either model as side packet or model path in options is required.
SplitTensorVectorCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
SplitNormalizedLandmarkListCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
SplitLandmarkListCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
SwitchDemuxCalculator::GetContract failed to validate: 
For input streams ValidatePacketTypeSet failed:
Tag "NORM_LANDMARKS" index 0 was not expected.
SwitchMuxCalculator::GetContract failed to validate: 
For output streams ValidatePacketTypeSet failed:
Tag "NORM_FILTERED_LANDMARKS" index 0 was not expected.
SwitchDemuxCalculator::GetContract failed to validate: 
For input streams ValidatePacketTypeSet failed:
Tag "IMAGE_SIZE" index 0 was not expected.
Tag "NORM_LANDMARKS" index 0 was not expected.
Tag "OBJECT_SCALE_ROI" index 0 was not expected.
SwitchMuxCalculator::GetContract failed to validate: 
For output streams ValidatePacketTypeSet failed:
Tag "NORM_FILTERED_LANDMARKS" index 0 was not expected.
SwitchDemuxCalculator::GetContract failed to validate: 
For input streams ValidatePacketTypeSet failed:
Tag "LANDMARKS" index 0 was not expected.
SwitchMuxCalculator::GetContract failed to validate: 
For output streams ValidatePacketTypeSet failed:
Tag "FILTERED_LANDMARKS" index 0 was not expected.
SwitchDemuxCalculator::GetContract failed to validate: 
For input streams ValidatePacketTypeSet failed:
Tag "LANDMARKS" index 0 was not expected.
SwitchMuxCalculator::GetContract failed to validate: 
For output streams ValidatePacketTypeSet failed:
Tag "FILTERED_LANDMARKS" index 0 was not expected.
SplitNormalizedLandmarkListCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
ImageToTensorCalculator: ; RET_CHECK failure (external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:146) options.has_output_tensor_float_range() || options.has_output_tensor_int_range() || options.has_output_tensor_uint_range()Output tensor range is required.
ImageToTensorCalculator: ; RET_CHECK failure (external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:146) options.has_output_tensor_float_range() || options.has_output_tensor_int_range() || options.has_output_tensor_uint_range()Output tensor range is required.
SplitTensorVectorCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
SplitNormalizedLandmarkListCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
ImageToTensorCalculator: ; RET_CHECK failure (external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:146) options.has_output_tensor_float_range() || options.has_output_tensor_int_range() || options.has_output_tensor_uint_range()Output tensor range is required.
ImageToTensorCalculator: ; RET_CHECK failure (external/com_google_mediapipe/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:146) options.has_output_tensor_float_range() || options.has_output_tensor_int_range() || options.has_output_tensor_uint_range()Output tensor range is required.
SplitTensorVectorCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
InferenceCalculatorGl: ; RET_CHECK failure (external/com_google_mediapipe/mediapipe/calculators/tensor/inference_calculator_gl.cc:93) !options.model_path().empty() ^ kSideInModel(cc).IsConnected()Either model as side packet or model path in options is required.
SwitchDemuxCalculator::GetContract failed to validate: 
For input streams ValidatePacketTypeSet failed:
Tag "" index 0 was not expected.
SwitchMuxCalculator::GetContract failed to validate: 
For output streams ValidatePacketTypeSet failed:
Tag "" index 0 was not expected.
Tag "" index 1 was not expected.
SwitchDemuxCalculator::GetContract failed to validate: 
For input streams ValidatePacketTypeSet failed:
Tag "TENSORS" index 0 was not expected.
SwitchMuxCalculator::GetContract failed to validate: 
For output streams ValidatePacketTypeSet failed:
Tag "LANDMARKS" index 0 was not expected.
InferenceCalculatorGl: ; RET_CHECK failure (external/com_google_mediapipe/mediapipe/calculators/tensor/inference_calculator_gl.cc:93) !options.model_path().empty() ^ kSideInModel(cc).IsConnected()Either model as side packet or model path in options is required.
InferenceCalculatorGl: ; RET_CHECK failure (external/com_google_mediapipe/mediapipe/calculators/tensor/inference_calculator_gl.cc:93) !options.model_path().empty() ^ kSideInModel(cc).IsConnected()Either model as side packet or model path in options is required.

**Comment by kuaashish** [comment]
Hi @fishhead012 
Could you please elaborate your query with complete details and clear steps to reproduce the issue from our end. Thank you!

**Comment by fishhead012** [comment]
> Hi @fishhead012 Could you please elaborate your query with complete details and clear steps to reproduce the issue from our end. Thank you!

Below are my settings. Any small clue would be appreciated. :D

# GPU buffer. (GpuBuffer)
input_stream: "input_video"

output_stream: "pose_landmarks"
output_stream: "pose_world_landmarks"
output_stream: "segmentation_mask"
output_stream: "pose_roi"
output_stream: "pose_detection"
output_stream: "face_landmarks"
output_stream: "left_hand_landmarks"
output_stream: "right_hand_landmarks"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:face_landmarks"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.FlowLimiterCalculatorOptions] {
      max_in_flight: 1
      max_in_queue: 1
      # Timeout is disabled (set to 0) as first frame processing can take more
      # than 1 second.
      in_flight_timeout: 0
    }
  }
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  input_side_packet: "ROTATION_DEGREES:input_rotation"
  input_side_packet: "FLIP_HORIZONTALLY:input_horizontally_flipped"
  input_side_packet: "FLIP_VERTICALLY:input_vertically_flipped"
  output_stream: "IMAGE_GPU:transformed_input_video"
}

node {
  calculator: "HolisticLandmarkGpu"
  input_stream: "IMAGE:transformed_input_video"
  input_side_packet: "MODEL_COMPLEXITY:model_complexity"
  input_side_packet: "SMOOTH_LANDMARKS:smooth_landmarks"
  input_side_packet: "REFINE_FACE_LANDMARKS:refine_face_landmarks"
  input_side_packet: "ENABLE_SEGMENTATION:enable_segmentation"
  input_side_packet: "SMOOTH_SEGMENTATION:smooth_segmentation"
  output_stream: "POSE_LANDMARKS:pose_landmarks"
  output_stream: "WORLD_LANDMARKS:pose_world_landmarks"
  output_stream: "SEGMENTATION_MASK:segmentation_mask_gpu"
  output_stream: "POSE_ROI:pose_roi"
  output_stream: "POSE_DETECTION:pose_detection"
  output_stream: "FACE_LANDMARKS:face_landmarks"
  output_stream: "LEFT_HAND_LANDMARKS:left_hand_landmarks"
  output_stream: "RIGHT_HAND_LANDMARKS:right_hand_landmarks"
}

node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:segmentation_mask_gpu"
  input_side_packet: "ROTATION_DEGREES:output_rotation"
  input_side_packet: "FLIP_HORIZONTALLY:output_horizontally_flipped"
  input_side_packet: "FLIP_VERTICALLY:output_vertically_flipped"
  output_stream: "IMAGE_GPU:segmentation_mask_unrotated_gpu"
}

node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "segmentation_mask_unrotated_gpu"
  output_stream: "segmentation_mask"
}

**Comment by kuaashish** [comment]
Hi @fishhead012,
Could you please confirm that still you are looking for the resolution or the issue has been resolved. Thank you!

**Comment by fishhead012** [comment]
I still haven't been able to solve the problem below.

<Platform>
ANDROID

<Code location>
absl::Status NodeTypeInfo::Initialize(
.... 
       MP_RETURN_IF_ERROR(calculator_factory->GetContract(&contract_)).SetPrepend()
           << node_class << ": ";
     .....
      static absl::Status GetContract(CalculatorContract* cc) {
          .....
              if (cc->Outputs().NumEntries() != options.ranges_size()) {
                   return absl::InvalidArgumentError(
                   "The number of output streams should match the number of ranges "
                   "specified in the CalculatorOptions.");
              }

<ErrLog>
SplitNormalizedLandmarkListCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
SplitDetectionVectorCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
SplitNormalizedLandmarkListCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
SplitNormalizedLandmarkListCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.

**Comment by fishhead012** [comment]
1. pc (cpu) works
2. android (gpu) not works

// err nodes
holisticlandmarkgpu__handlandmarksleftandrightgpu__SplitNormalizedLandmarkListCalculator_1
holisticlandmarkgpu__handlandmarksleftandrightgpu__SplitNormalizedLandmarkListCalculator_2
holistictrackingtorenderdata__handwristforpose_1__SplitNormalizedLandmarkListCalculator
holistictrackingtorenderdata__handwristforpose_2__SplitNormalizedLandmarkListCalculator
holisticlandmarkgpu__poselandmarkgpu__poselandmarkbyroigpu__tensorstoposelandmarksandsegmentation__SplitNormalizedLandmarkListCalculator
holisticlandmarkgpu__handlandmarksleftandrightgpu__handlandmarksfromposegpu_1__handvisibilityfromhandlandmarksfrompose__SplitNormalizedLandmarkListCalculator
....

// code location
class SplitListsCalculator : public CalculatorBase {
 public:
  static absl::Status GetContract(CalculatorContract* cc)
.....
if (cc->Outputs().NumEntries() != options.ranges_size()) {
        return absl::InvalidArgumentError(
            "The number of output streams should match the number of ranges "
            "specified in the CalculatorOptions.");
      }

// 
most options.ranges_size()  is 0.
I don't know how to load ranges_size . can you tell me?

**Comment by kuaashish** [comment]
Hi @fishhead012,
Could you please share the complete steps to reproduce w.r.t to the [above](https://github.com/google/mediapipe/issues/3744#issuecomment-1289830212) mentioned error from our end. Thank you!

**Comment by fishhead012** [comment]
The value of ptions.ranges_size() is always 0 
if Node.has_options() is TRUE.

If the value of options.combine_outputs() is FALSE

I get the error "The number of output streams should match the number of ranges specified in the CalculatorOptions".

How do I match the output stream and number of ranges?

// ANDROID, holistic_tracking
