### ISSUE TITLE
(Exit 1120): link.exe failed: error executing command

### ISSUE THREAD

**Issue by lzw-lzw** [google/mediapipe#3745]
Something wrong when build hand_tracking

INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/lzw/desktop/mediapipe/mediapipe-master/mediapipe/examples/desktop/hand_tracking/BUILD:31:10: Linking mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu.exe failed: (Exit 1120): link.exe failed: error executing command D:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX64\x64\link.exe ... (remaining 1 argument skipped)
  正在创建库 bazel-out\x64_windows-opt\bin\mediapipe\examples\desktop\hand_tracking\hand_tracking_cpu.lib 和对象 bazel-out\x64_windows-opt\bin\mediapipe\examples\desktop\hand_tracking\hand_tracking_cpu.exp
LINK : warning LNK4217:符号“TfLiteXNNPackDelegateOptionsDefault”(在“ xnnpack_delegate.lib(xnnpack_delegate.obj)”中定义)已由“inference_calculator_cpu.lo.lib(inference_calculator_cpu.obj)”(函数“"private: class absl::lts_20210324::StatusOr<class std::unique_ptr<struct TfLiteDelegate,class std::function<void __cdecl(struct TfLiteDelegate *)> > > __cdecl mediapipe::api2::InferenceCalculatorCpuImpl::MaybeCreateDelegate(class mediapipe::CalculatorContext *)" (?MaybeCreateDelegate@InferenceCalculatorCpuImpl@api2@mediapipe@@AEAA?AV?$StatusOr@V?$unique_ptr@UTfLiteDelegate@@V?$function@$$A6AXPEAUTfLiteDelegate@@@Z@std@@@std@@@lts_20210324@absl@@PEAVCalculatorContext@3@@Z)”中)导入
LINK : warning LNK4217:符号“TfLiteXNNPackDelegateCreate”(在“ xnnpack_delegate.lib(xnnpack_delegate.obj)”中定义)已由“inference_calculator_cpu.lo.lib(inference_calculator_cpu.obj)”(函数“"private: class absl::lts_20210324::StatusOr<class std::unique_ptr<struct TfLiteDelegate,class std::function<void __cdecl(struct TfLiteDelegate *)> > > __cdecl mediapipe::api2::InferenceCalculatorCpuImpl::MaybeCreateDelegate(class mediapipe::CalculatorContext *)" (?MaybeCreateDelegate@InferenceCalculatorCpuImpl@api2@mediapipe@@AEAA?AV?$StatusOr@V?$unique_ptr@UTfLiteDelegate@@V?$function@$$A6AXPEAUTfLiteDelegate@@@Z@std@@@std@@@lts_20210324@absl@@PEAVCalculatorContext@3@@Z)”中)导入
LINK : warning LNK4217:符号“TfLiteXNNPackDelegateDelete”(在“ xnnpack_delegate.lib(xnnpack_delegate.obj)”中定义)已由“inference_calculator_cpu.lo.lib(inference_calculator_cpu.obj)”(函数“"private: class absl::lts_20210324::StatusOr<class std::unique_ptr<struct TfLiteDelegate,class std::function<void __cdecl(struct TfLiteDelegate *)> > > __cdecl mediapipe::api2::InferenceCalculatorCpuImpl::MaybeCreateDelegate(class mediapipe::CalculatorContext *)" (?MaybeCreateDelegate@InferenceCalculatorCpuImpl@api2@mediapipe@@AEAA?AV?$StatusOr@V?$unique_ptr@UTfLiteDelegate@@V?$function@$$A6AXPEAUTfLiteDelegate@@@Z@std@@@std@@@lts_20210324@absl@@PEAVCalculatorContext@3@@Z)”中)导入
tflite_model_calculator.lo.lib(tflite_model_calculator.obj) : error LNK2019: 无法解析的外部符号 "public: __cdecl tflite::MMAPAllocation::MMAPAllocation(int,unsigned __int64,unsigned __int64,class tflite::ErrorReporter *)" (??0MMAPAllocation@tflite@@QEAA@H_K0PEAVErrorReporter@1@@Z)，函数 "class std::unique_ptr<class tflite::MMAPAllocation,struct std::default_delete<class tflite::MMAPAllocation> > __cdecl std::make_unique<class tflite::MMAPAllocation,int const &,unsigned __int64 const &,unsigned __int64 const &,class tflite::ErrorReporter *,0>(int const &,unsigned __int64 const &,unsigned __int64 const &,class tflite::ErrorReporter * &&)" (??$make_unique@VMMAPAllocation@tflite@@AEBHAEB_KAEB_KPEAVErrorReporter@2@$0A@@std@@YA?AV?$unique_ptr@VMMAPAllocation@tflite@@U?$default_delete@VMMAPAllocation@tflite@@@std@@@0@AEBHAEB_K1$$QEAPEAVErrorReporter@tflite@@@Z) 中引用了该符号
bazel-out\x64_windows-opt\bin\mediapipe\examples\desktop\hand_tracking\hand_tracking_cpu.exe : fatal error LNK1120: 1 个无法解析的外部命令
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.075s, Critical Path: 1.29s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

what's the problem

**Comment by andrechen** [comment]
in this [line](https://github.com/google/mediapipe/blob/6678a091e0f8ed5edd89c38598458b9694ab8037/mediapipe/calculators/tflite/tflite_model_calculator.cc#L87), it calls tflite::MMAPAllocation(int, size_t, size_t, tflite::ErrorReporter*) constructor, but unfortunately, tensorflow-lite fails to implement it for os that doesn't support **mmap**, or map files into memory.  see... https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/mmap_allocation_disabled.cc

Since windows os has no such thing, you can simply comment out the block in **tflite_model_calculator.cc**, like


```
#ifndef _WIN32
  if (cc->InputSidePackets().HasTag("MODEL_FD")) {
      // from tensorflow/tensorflow/lite/allocation.h line 59
      RET_CHECK(tflite::MMAPAllocation::IsSupported()) << "[Platform not support] Failed to load TfLite model from MODEL_FD";
      
      model_packet = cc->InputSidePackets().Tag("MODEL_FD");
      const auto& model_fd =
          model_packet.Get<std::tuple<int, size_t, size_t>>();
      auto model_allocation = std::make_unique<tflite::MMAPAllocation>(
          std::get<0>(model_fd), std::get<1>(model_fd), std::get<2>(model_fd),
          tflite::DefaultErrorReporter());
      model = tflite::FlatBufferModel::BuildFromAllocation(
          std::move(model_allocation), tflite::DefaultErrorReporter());
  }
#endif
```

**Comment by lzw-lzw** [comment]
thanks,it helps me a lot!

**Comment by kuaashish** [comment]
Hi @lzw-lzw, 
Could you please elaborate your query with complete details and steps to reproduce the issue from our end.
Thank you!

**Comment by TexenJin** [comment]
老哥，这个问题你解决了吗？

**Comment by TexenJin** [comment]
> 解决了 按照上面这个回复注释掉那一段就可以了

我又看了一下，我那个跟你的不一样，能把截图发给你，帮我看看吗？

**Comment by TexenJin** [comment]
链接：https://pan.baidu.com/s/16i-N0oyNbUH4hloEoGn2Wg?pwd=1111 
提取码：1111 
--来自百度网盘超级会员V5的分享

**Comment by lzw-lzw** [comment]
你这个和我的一样的吧 你试试上面那个注释掉

**Comment by TexenJin** [comment]
> 

好的好的，我试试

**Comment by TexenJin** [comment]
> 你这个和我的一样的吧 你试试上面那个注释掉

哦哦哦，成功了

**Comment by TexenJin** [comment]
Mine worked either, thank you.

**Comment by TexenJin** [comment]
> in this [line](https://github.com/google/mediapipe/blob/6678a091e0f8ed5edd89c38598458b9694ab8037/mediapipe/calculators/tflite/tflite_model_calculator.cc#L87), it calls tflite::MMAPAllocation(int, size_t, size_t, tflite::ErrorReporter*) constructor, but unfortunately, tensorflow-lite fails to implement it for os that doesn't support **mmap**, or map files into memory. see... https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/mmap_allocation_disabled.cc
> 
> Since windows os has no such thing, you can simply comment out the block in **tflite_model_calculator.cc**, like
> 
> ```
> #ifndef _WIN32
>   if (cc->InputSidePackets().HasTag("MODEL_FD")) {
>       // from tensorflow/tensorflow/lite/allocation.h line 59
>       RET_CHECK(tflite::MMAPAllocation::IsSupported()) << "[Platform not support] Failed to load TfLite model from MODEL_FD";
>       
>       model_packet = cc->InputSidePackets().Tag("MODEL_FD");
>       const auto& model_fd =
>           model_packet.Get<std::tuple<int, size_t, size_t>>();
>       auto model_allocation = std::make_unique<tflite::MMAPAllocation>(
>           std::get<0>(model_fd), std::get<1>(model_fd), std::get<2>(model_fd),
>           tflite::DefaultErrorReporter());
>       model = tflite::FlatBufferModel::BuildFromAllocation(
>           std::move(model_allocation), tflite::DefaultErrorReporter());
>   }
> #endif
> ```

Mine worked either, thank you.

**Comment by kuaashish** [comment]
Hi @lzw-lzw, Good to hear that the issue has been resolved as per the above [comment](https://github.com/google/mediapipe/issues/3745#issuecomment-1274190437). Could we move this issue to close status as it has resolved and does not require further support. Thank you!

**Comment by lzw-lzw** [comment]
yes，thanks！

**Comment by Chrismas60** [comment]
I‘ve met this problem. And I operated like above, the problem can't be solved. what's the problem? 
my system setting: 
Mediapipe: 0.10.3
Visual studio: 2022. 
<img width="1274" alt="image" src="https://github.com/google/mediapipe/assets/143788724/3659d965-ccf6-486e-bb9f-317ea71f07b7">

**Comment by neuxys** [comment]
@Chrismas60 My problem is the same as yours. Have you solved it yet?
