### ISSUE TITLE
argument types are supported 1. (arg0: int) invoke 0.5

### ISSUE THREAD

**Issue by rodrigoluciano** [google/mediapipe#3746]
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (Ubuntu Linux):
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.11
- Solution ():

-  Use the modelcomplexity parameter to solve the problem
    def __init__(self, mode=False, max_hands=2,model_complexity=1, detection_con=0.5, track_con=0.5):
        self.mode = mode
        self.maxHands = max_hands
        self.modelComplex = model_complexity
        self.detectionCon = detection_con
        self.trackCon = track_con
        self.mpHands = mp.solutions.hands
        self.hands = self.mpHands.Hands(self.mode, self.maxHands,self.modelComplex,
                                        self.detectionCon, self.trackCon)
        self.mpDraw = mp.solutions.drawing_utils 

- Programming Language and version ( Python):

**Describe the expected behavior:**
TypeError: create_int(): incompatible function arguments. The following argument types are supported: 1. (arg0: int) -> mediapipe.python._framework_bindings.packet.Packet Invoked with: 0.5

This Solved for me

**Comment by kuaashish** [comment]
Hi @rodrigoluciano, 
Could you please elaborate your query with complete details and steps to reproduce the issue from our end. 
Thank you!

**Comment by NightKnight-5008** [comment]
what have worked for me but slowed down the fps of the code BY ALOT is to change your code to detection_con=1, track_con=1

**Comment by NightKnight-5008** [comment]
also this is my code `def __init__(self, mode=False, maxHands=2, model_complexity=0.6, detectionCon=0, trackCon=0.4):`
