### ISSUE TITLE
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

### ISSUE THREAD

**Issue by divastar** [google/mediapipe#3748]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- Windows 10:
- Programming Language and version ( Python 3 ):
- [MediaPipe version]: latest docker
- [MediaPipe version 0.8.11:
- Bazel version 5.3.1:
- OpenCV version 4.6.0:

**Describe the problem**:

**[Provide the exact sequence of commands / steps that you executed before running into the problem]I followed the installation instructions on  https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows : Installing using Docker
docker build --tag=mediapipe .
docker run mediapipe

gave me No module named 'mediapipe.python._framework_bindings'

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

(base) PS C:\Users\korin\mediapipe-master> docker run mediapipe
Traceback (most recent call last):
  File "./myface.py", line 2, in <module>
    import mediapipe as mp
  File "/mediapipe/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/mediapipe/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

**Comment by kuaashish** [comment]
Hi @divastar, Have you looked at this similar closed issue #3130 and [#3130(comment)](https://github.com/google/mediapipe/issues/3130#issuecomment-1148672993). Thank you!
