### ISSUE TITLE
[Instant Motion Tracking] Tracking outside the camera's field of view

### ISSUE THREAD

**Issue by ngthlong1990** [google/mediapipe#3749]
Hi. I am using Instant Motion Tracking and it works fine within camera view. However, when the camera spans away and back, the tracking is not correct any more. As I read on the paper https://arxiv.org/pdf/1907.06796.pdf they say they "_allow for limited region tracking outside the camera’s field of view–enabling a virtual object to reappear in approximately the same spot when panning away and back again. Combining visual information for 3D translation and IMU data for 3D rotation lets us track and render virtual content correctly in the viewfinder with 6DoF, with the initial object scale being set by the user. With this parallelization, the system is fast and efficient, can track moving or static regions, and furthermore requires no calibration–it works on any device with a gyroscope._"
I have searched everywhere and have no clue how to make it possible. Did I miss something?
Besides, I have an idea that I will pause tracking when the anchor is outside of the camera, and will continue when camera is back. Is this possible with our mediapipe?
Thank you for any reply.

**Comment by kuaashish** [comment]
Hi @ngthlong1990, 
Could you please elaborate your query with complete details and code changes made. 
Thank you!

**Comment by ngthlong1990** [comment]
**System information**
- Have I written custom code: Not yet, just use current project only
- OS Platform and Distribution: Linux Kubuntu 20.04, Android 12
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.10
- Bazel version: 5.3.1
- Solution: Instant Motion Tracking
- Programming Language and version: Java

**Describe the expected behavior:**
When I pan the camera away from the sticker, and then return, the sticker is gone or moves to a different place (tracking goes wrong)

**Standalone code you may have used to try to get what you need :** Not yet

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:
This is a demo video: 

<iframe src="https://drive.google.com/file/d/1LQQbRagtVeRraRZ1xbRHJFFIATKFOQtJ/preview" width="640" height="480" allow="autoplay"></iframe>

I am finding a solution, so not yet have an idea on how to do. Any help is appreciate. Thank you.

**Comment by ayushgdev** [comment]
Hello @ngthlong1990 
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
