### ISSUE TITLE
Ubuntu Bazel build unrecognized option error

### ISSUE THREAD

**Issue by Magsun** [google/mediapipe#375]
Hello to anyone who sees this issue report, I would be so happy if someone can help.
I met this unrecognized option error while I'm trying to convert local video to yt8m format features.
The command line is listed below:
bazel build -c opt \   
--define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true \
mediapipe/examples/desktop/youtube8m:extract_yt8m_features

The whole info of this error is:
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=168
INFO: Reading rc options for 'build' from /workspace/paddlevideo/mediapipe/.bazelrc:
  'build' options: --jobs 128 --define=absl=1 --cxxopt=-std=c++14 --copt=-Wno-sign-compare --copt=-Wno-unused-function --copt=-Wno-uninitialized --copt=-Wno-unused-result --copt=-Wno-comment --copt=-Wno-return-type --copt=-Wno-unused-local-typedefs --copt=-Wno-ignored-attributes --incompatible_disable_deprecated_attr_params=false --incompatible_depset_is_not_iterable=false --apple_platform_type=macos --apple_generate_dsym
ERROR: Unrecognized option: --incompatible_depset_is_not_iterable=false

My bazel version is 2.0.0 installed by binary .sh file, and sys version is Ubuntu 16.04.
FFMPEG and OPENCV are installed.

Kindly help me solve this problem, please.

**Comment by mcclanahoochie** [comment]
Hi, 
Please note that MediaPipe does not yet support bazel 2.0.0+ (see [here](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md)). Please try installing a supported version of bazel (between  v0.24.1 and v1.2.1) and see if that fixes the issue.

**Comment by Magsun** [comment]
> Hi,
> Please note that MediaPipe does not yet support bazel 2.0.0+ (see [here](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md)). Please try installing a supported version of bazel (between v0.24.1 and v1.2.1) and see if that fixes the issue.

Ah, sorry that I didn't see this before, after installed older version it's fixed. Thanks for your help!

**Comment by chensisi0730** [comment]
> Hi,
> Please note that MediaPipe does not yet support bazel 2.0.0+ (see [here](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md)). Please try installing a supported version of bazel (between v0.24.1 and v1.2.1) and see if that fixes the issue.

install Bazel 2.0 or higher.  in https://mediapipe.readthedocs.io/en/latest/install.html#installing-on-debian-and-ubuntu
