### ISSUE TITLE
Pose: No Such file or directory: pose_landmark_heavy.tflite

### ISSUE THREAD

**Issue by Frany-oss** [google/mediapipe#3750]
I'm trying to build a .exe and I'm using Pose Detection in a part of my program. 
What I use to execute the file:
```bash
pyinstaller --online main_ui.py
```
When I run de .exe (using pyinstaller) a get this error:
![Screenshot 2022-10-03 103011](https://user-images.githubusercontent.com/54272736/193616966-f514625f-81a2-4b14-96db-b7b3e518cd3d.jpg)

**System information** 
- Windows 10:
- Using Pyinstaller version 5.4.1 for generating the .exe
- MediaPipe version: 0.8.11
- Solution (e.g. FaceMesh, Pose, Holistic): Pose
- Programming Language and version ( e.g. C++, Python, Java): Python`

I read on issue #3675 about the different solutions and I've tried them all.

When I tried to create the directory it says in the error it doesn't matter because if in the Temp folder, so everytime it executes it creates a new one.

The URL on the download_utils.py is:

```python
import os
import shutil
import urllib.request

_GCS_URL_PREFIX = 'https://storage.googleapis.com/mediapipe-assets/'

def download_oss_model(model_path: str):
  """Downloads the oss model from Google Cloud Storage if it doesn't exist in the package."""

  mp_root_path = os.sep.join(os.path.abspath(__file__).split(os.sep)[:-4])
  model_abspath = os.path.join(mp_root_path, model_path)
  if os.path.exists(model_abspath):
    return
  model_url = _GCS_URL_PREFIX + model_path.split('/')[-1]
  print('Downloading model to ' + model_abspath)
  with urllib.request.urlopen(model_url) as response, open(model_abspath,
                                                           'wb') as out_file:
    if response.code != 200:
      raise ConnectionError('Cannot download ' + model_path +
                            ' from Google Cloud Storage.')
    shutil.copyfileobj(response, out_file)
```

In my site_packages I have the ```pose_landmark_heavy.tflite```
```console
C:\Users\franc\AppData\Local\Programs\Python\Python39\Lib\site-packages\mediapipe\modules\pose_landmark
```

The code where I use Mediapipe:
```python
import math
import cv2
import numpy as np
from time import time
import mediapipe as mp
import matplotlib.pyplot as plt

mp_pose = mp.solutions.pose

pose = mp_pose.Pose(static_image_mode = True, min_detection_confidence = 0.3, model_complexity = 2)

mp_drawing = mp.solutions.drawing_utils 

def detectPose(image, pose, display = True, verbose = False):
    output_image = image.copy()
    
    imageRGB = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    results = pose.process(imageRGB)

    height, width, _ = image.shape
    
    landmarks = []
    
    if results.pose_landmarks:
    
        mp_drawing.draw_landmarks(image=output_image, landmark_list=results.pose_landmarks,
                                  connections=mp_pose.POSE_CONNECTIONS)
        
        for landmark in results.pose_landmarks.landmark:
    
            landmarks.append((int(landmark.x * width), int(landmark.y * height),
                              (landmark.z * width)))

    if verbose:
        print('Landmarks are: ', landmarks)

    if display:

        plt.figure(figsize=[22,22])
        plt.plot(122);plt.imshow(output_image[:,:,::-1]);plt.title("Output Image");plt.axis('off');
        mp_drawing.plot_landmarks(results.pose_world_landmarks, mp_pose.POSE_CONNECTIONS)
        
    else:
        
        return output_image, landmarks

        
```

**Comment by kuaashish** [comment]
Hi @Frany-oss, 
Could you please elaborate your query with complete details and steps to reproduce the issue from our end. Thank you!

**Comment by Frany-oss** [comment]
Hi @kuaashish I just edited my comment with the full code use in my program. Let me know if you need any more information.

**Comment by kyoybs** [comment]
please try:
pyinstaller PhysicalHand.py --add-data="C:\Users\xujianjun\AppData\Roaming\Python\Python39\site-packages\mediapipe\modules;mediapipe/modules" -F -w

————————————————
版权声明：本文为CSDN博主「xujianjun229」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/xujianjun229/article/details/120049583

**Comment by Frany-oss** [comment]
Thank you @kyoybs, that was it!!! 

:)

**Comment by swe-cognitica** [comment]
I'm facing the same issue. Is PhysicalHand.py and main_ui.py the same.

**Comment by swe-cognitica** [comment]
I'm facing the same issue. The location is "/home/username/.local/lib/python3.8/site-packages/mediapipe/modules/pose_landmark/pose_landmark_lite.tflite". 
I ran the command "pyinstaller functions.py --add-data="/home/username/.local/lib/python3.8/site-packages/mediapipe/modules;mediapipe/modules" -F -w

But I got the following error:
 pyinstaller: error: argument --add-data: invalid add_data_or_binary value: '/home/cognitica-ai-f1122-f2_55/.local/lib/python3.8/site-packages/mediapipe/modules;mediapipe/modules'

Please suggest what could be done
