### ISSUE TITLE
Palm Detection Model Output

### ISSUE THREAD

**Issue by AshaLilyPatel** [google/mediapipe#3751]
Hi, I'm struggling to process the output of the palm detection tflite model. 

I obtain the 7 hand landmarks and they appear to match the shape of the hand in the input image - which suggests that I've correctly found the highest probability prediction and corresponding anchor - however they are not aligned on the image (likewise with the main bounding box). 

I've so far been unsuccessful at reverse engineering the transformation between this output and the correct position (e.g simply multiplying the normalised outputs by the image width & height, using the anchor offset etc). I've looked at the documentation and all of the solutions referenced in previous similar issues, however I can't find a clear explanation. Note that my implementation is written in Python; I'm not using MediaPipe graph.

It feels as though I'm missing something simple (or perhaps my whole method is wrong). If anyone has a good explanation of the post-processing steps it would be greatly appreciated!

Thank you in advance.

**Comment by kuaashish** [comment]
Hi @AshaLilyPatel, 
Please refer to this issue #1638 and [#1638(comment)](https://github.com/google/mediapipe/issues/1638#issuecomment-974167633) for better understanding on your query. Thank you!
