### ISSUE TITLE
Extract intermediate layer features from Hand Landmark model

### ISSUE THREAD

**Issue by pyxploiter** [google/mediapipe#3753]
Is there any possible way to extract intermediate layer features from Hand landmark model instead of final hand landmarks?

**Comment by kuaashish** [comment]
Hi @pyxploiter, 
Have you looked at this closed issue #3492 and [#3492(comment)](https://github.com/google/mediapipe/issues/3492#issuecomment-1177722813), which will give you better understanding to extract the each landmarks. 
Thank you!
