### ISSUE TITLE
python configure error on windows

### ISSUE THREAD

**Issue by divastar** [google/mediapipe#3756]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
Windows 10:
Programming Language and version ( Python 3 ):
[MediaPipe version]: latest docker
[MediaPipe version 0.8.11:
Bazel version 5.3.1:
OpenCV version 4.6.0:
**Describe the problem**:    Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//k//AppData//Local//Programs//Python//Python310//python.exe' is not executable. Is it the python binary?

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
followed the tutorial on https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows

the next step in building with bazel resulted in python.exe' is not executable error

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

\mediapipe-master> bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//k//AppData//Local//Programs//Python//Python310//python.exe" mediapipe/examples/desktop/hello_world
>>
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  C:/users/k/mediapipe-master/WORKSPACE:483:14: in <toplevel>
  C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/tensorflow/workspace2.bzl:879:19: in workspace
  C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/tensorflow/workspace2.bzl:86:27: in _tf_toolchains
  C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//k//AppData//Local//Programs//Python//Python310//python.exe' is not executable. Is it the python binary?
ERROR: C:/users/k/mediapipe-master/WORKSPACE:483:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/k/_bazel_k/stl2uqx6/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//k//AppData//Local//Programs//Python//Python310//python.exe' is not executable. Is it the python binary?
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C://Users//k//AppData//Local//Programs//Python//Python310//python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 0.259s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
PS C:\Users\k\mediapipe-master>

**Comment by kuaashish** [comment]
Hi @divastarm, Have you looked at this closed issue #3459 and [#3459(comment)](https://github.com/google/mediapipe/issues/3459#issuecomment-1167468953). Thank you!
