### ISSUE TITLE
Can't install mediapipe on PyCharm IDE.

### ISSUE THREAD

**Issue by younasm** [google/mediapipe#3758]
I am using python version: 3.10.6 
already have installed all other packages but only mediapipe is giving me this error. also tried with terminal but same error.

```
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

need urgent help!

**Comment by kuaashish** [comment]
Hi @younasm, 
Could you try to downgrade the Python version to the `3.10.0` and please let us know if the issue has been resolved or need further help. Thank you!

**Comment by younasm** [comment]
> Hi @younasm, Could you try to downgrade the Python version to the `3.10.0` and please let us know if the issue has been resolved or need further help. Thank you!

same issue not working for me. i tried version 3.8, 3.9, 3.10. also tried with specify version of mediapipe still not working.

**Comment by younasm** [comment]
> Hi @younasm, Could you try to downgrade the Python version to the `3.10.0` and please let us know if the issue has been resolved or need further help. Thank you!

any help!

**Comment by kuaashish** [comment]
Hi @younasm, 
Could you please elaborate your query with complete details and steps followed to reproduce the issue from our end. Please update the system information as mentioned in the [documentation](https://google.github.io/mediapipe/getting_started/help.html#system-information). Thank you!

**Comment by kuaashish** [comment]
Hi @younasm, 
Could you please go through this thread [#so](https://stackoverflow.com/questions/68659865/cannot-pip-install-mediapipe-on-macos-m1) and follow the steps mentioned to build the mediapipe in the MacOS. Thank you!

**Comment by younasm** [comment]
> Hi @younasm, Could you please go through this thread [#so](https://stackoverflow.com/questions/68659865/cannot-pip-install-mediapipe-on-macos-m1) and follow the steps mentioned to build the mediapipe in the MacOS. Thank you!

yes i can install `pip install mediapipe-silicon` but not `mediapipe` on my m1 macOs 12.4.

**Comment by kuaashish** [comment]
Hi @younasm,
Currently MediaPipe does not support the Apple Mac M1. The team is actively working towards supporting the MediaPipe on the Mac M1 chip but does not have the more details on this. 
Workaround, You can use build using the command `pip install mediapipe-silicon`. Please refer to this running thread #1514 and [#1514(Comment)](https://github.com/google/mediapipe/issues/1514#issuecomment-1210888269) for better understanding. Thank you!

**Comment by Ron-Caster** [comment]
I too can't install mediapipe on Pycharm. Windows 11, PyCharm 2022.3.1 and Python 3.11. Went all night wide awake. Mediapipe won't install. Any solution?

**Comment by chameen9** [comment]
@Ron-Caster Do you got a Solution?

**Comment by Ron-Caster** [comment]
> @Ron-Caster Are you got a Solution?
> 
> 

I did it on laptop but don't remember now. But can't figure it out now on Raspberry Pi.

**Comment by Ron-Caster** [comment]
> pip install mediapipe

 or

> pip3 install mediapipe, worked

in RPi4, 

> pip install mediapipe, didn't work at first.

sudo pip3 install mediapipe-rpi4    <- worked in RPi4

**Comment by chameen9** [comment]
@Ron-Caster I Found the solution

**Comment by sparky2711** [comment]
> @Ron-Caster I Found the solution

please share the solution how to install mediapipe on windows 11

**Comment by kuaashish** [comment]
Hello @younasm,
We have released Universal Wheels with version `0.9.3.0` as guided [here](https://github.com/google/mediapipe/releases/tag/v0.9.3.0) in the release page with Python 3.11.
Please try out to build mediapipe using pip let us know if still an issue from your end.

**Comment by younasm** [comment]
> Hello @younasm, We have released Universal Wheels with version `0.9.3.0` as guided [here](https://github.com/google/mediapipe/releases/tag/v0.9.3.0) in the release page with Python >= 3.8. Please try out to build mediapipe using pip let us know if still an issue from your end.

Thank you so much for your hard work I have successfully installed it on both terminal and on PyCharm 
<img width="1137" alt="Screenshot 2023-04-20 at 1 13 13 PM" src="https://user-images.githubusercontent.com/46291811/233267478-97709c55-44da-4744-bb9d-a1cb775e6e8e.png">

**Comment by kuaashish** [comment]
@younasm,
Thank you for your kind words. Request from the community has helped us include this feature. We would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Further, We need your confirmation to move the status of issue to close as the issue has been resolved.

**Comment by kuaashish** [comment]
Hello @younasm,
Could you please update the status of the above comment. Thank you
