### ISSUE TITLE
Execute ./build_android_examples.sh the following error occurs

### ISSUE THREAD

**Issue by MarsH2o2** [google/mediapipe#3759]
System information
- Ubuntu 20.04
- Compiler version gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- Programming Language java jdk11
- Bazel version: 5.2.0

Describe the problem:

I have execute ./build_android_examples.sh, but  the following error occurs:
WARNING: /mnt/e/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /mnt/e/mediapipe/mediapipe/framework/tool/BUILD:185:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
ERROR: /mnt/e/mediapipe/mediapipe/graphs/object_detection_3d/calculators/BUILD:22:24: no such target '//mediapipe/gpu:gl_animation_overlay_calculator_cc_proto': target 'gl_animation_overlay_calculator_cc_proto' not declared in package 'mediapipe/gpu' defined by /mnt/e/mediapipe/mediapipe/gpu/BUILD and referenced by '//mediapipe/graphs/object_detection_3d/calculators:gl_animation_overlay_calculator_cc_proto'
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking' failed; build aborted:
INFO: Elapsed time: 0.814s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded, 107 targets configured)

**Comment by kuaashish** [comment]
Hi @MarsH2o2, 
Could you please elaborate your query with a complete error log and steps to reproduce the issue from our end. Please update the system information as mentioned in the [documentation](https://google.github.io/mediapipe/getting_started/help.html#system-information). Thank you!

**Comment by MarsH2o2** [comment]
Here are the steps to reproduce:

1. git clone mediapipe
2. Execute setup_android_sdk_and_ndk.sh
3. Execute setup_opencv.sh
4. Execute build_android_examples.sh
5. Prompt to need bazelisk, I downloaded and installed it from github
6. Execute build_android_examples.sh again

Then in the end, the above problem appeared. The complete log is as follows (I only post the log of the failure to build instantmotiontracking apk ):

=== Target: mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /home/qiangyang/.cache/bazel/_bazel_qiangyang/067b1ed5ccc61fbd05007e7bd039403e/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
WARNING: /media/qiangyang/HDD/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /media/qiangyang/HDD/mediapipe/mediapipe/framework/tool/BUILD:185:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
ERROR: /media/qiangyang/HDD/mediapipe/mediapipe/graphs/object_detection_3d/calculators/BUILD:22:24: no such target '//mediapipe/gpu:gl_animation_overlay_calculator_cc_proto': target 'gl_animation_overlay_calculator_cc_proto' not declared in package 'mediapipe/gpu' defined by /media/qiangyang/HDD/mediapipe/mediapipe/gpu/BUILD and referenced by '//mediapipe/graphs/object_detection_3d/calculators:gl_animation_overlay_calculator_cc_proto'
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking:instantmotiontracking' failed; build aborted: 
INFO: Elapsed time: 0.219s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded, 206 targets configured)

**Comment by MarsH2o2** [comment]
I rolled back the code to the commit of 2022-6-30, and the compilation was successful. The information of the successful node is as follows:
GitOrigin-RevId: 0f2489d226f1e2a5d718a8b9efe5e8198ba4ab3b
63e679d9 MediaPipe Team <mediapipe-team@google.com> on 6/30/2022 at 2:00 AM
committed by Sebastian Schmidt <mrschmidt@gmail.com> on 6/30/2022 at 2:45am

Because I saw that someone modified mediapipe/mediapipe/gpu/BUILD after this node causing it to have the above problem.

**Comment by EricHe56** [comment]
Hi, I have met same issue. The reasone is mediapipe/graphs/object_detection_3d/calculators/BUILD contains a invalid reference in line 67: 
`":gl_animation_overlay_calculator_cc_proto",`
seems previouse version of this file code contains related target on 10/16/2020 v0.7.12 c828392681bc343a90e188c5ad5f295bada1eefb

**Comment by MarsH2o2** [comment]
> 你好，我也遇到了同样的问题。原因是 mediapipe/graphs/object_detection_3d/calculators/BUILD 在第 67 行包含无效引用： `":gl_animation_overlay_calculator_cc_proto",` 此文件代码的先前版本似乎在 10/16/2020 [v0.7.12 c828392上包含相关目标](https://github.com/google/mediapipe/commit/c828392681bc343a90e188c5ad5f295bada1eefb)

You can check the commit record, it's caused by a later commit, but I don't know what his commit does, so I rolled it back.

**Comment by EricHe56** [comment]
> > 你好，我也遇到了同样的问题。原因是 mediapipe/graphs/object_detection_3d/calculators/BUILD 在第 67 行包含无效引用： `":gl_animation_overlay_calculator_cc_proto",` 此文件代码的先前版本似乎在 10/16/2020 [v0.7.12 c828392上包含相关目标](https://github.com/google/mediapipe/commit/c828392681bc343a90e188c5ad5f295bada1eefb)
> 
> You can check the commit record, it's caused by a later commit, but I don't know what his commit does, so I rolled it back.

Yep, rollback too and got that apk

**Comment by kuaashish** [comment]
Hi @MarsH2o2, 
Thanks for the confirmation. Could you move this issue to close status as has been resolved as per the [above comment](https://github.com/google/mediapipe/issues/3759#issuecomment-1277535328). Thank you!
