### ISSUE TITLE
Can`t build with Bazel

### ISSUE THREAD

**Issue by asd26187** [google/mediapipe#3760]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):MacOS Monterey 12.6
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):Apple clang version 14.0.0
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):Python 3.10.7
- Installed using virtualenv? pip? Conda? (if python):pip
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:5.2.0
- XCode and Tulsi versions (if iOS):Xcode 14.0.1 Tulsi Version 0.20220310.88
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:
When I build with the Bazel build command I get the following error in the terminal, I can't understand how this error is caused or how I should eliminate it, please help me, thanks！
---------------------------------
INFO: Repository 'rules_java' used the following cache hits instead of downloading the corresponding file.
 * Hash 'bc81f1ba47ef5cc68ad32225c3d0e70b8c6f6077663835438da8d5733f917598' for https://mirror.bazel.build/github.com/bazelbuild/rules_java/archive/7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip
If the definition of 'rules_java' was updated, verify that the hashes were also updated.
ERROR: Analysis of target '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp' failed; build aborted: 
INFO: Elapsed time: 31.539s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (109 packages loaded, 1601 targets configured)
    currently loading: @com_google_protobuf// ... (4 packages)
    Fetching @com_google_absl; fetching
    Fetching @macos_opencv; Restarting.
    Fetching ...s_java; Extracting /private/var/tmp/_bazel_yunxiao/84aa27cfb29363c19191829\
22649c93d/external/rules_java/temp1980986689431104084/7cf3cefd652008d0a64a419c34c13bdca6c8\
f178.zip
    Fetching ...e_absl; Extracting /private/var/tmp/_bazel_yunxiao/84aa27cfb29363c19191829\
22649c93d/external/com_google_absl/temp18088582760554807661/20210324.2.tar.gz
    Fetching ...or_mac; Extracting /private/var/tmp/_bazel_yunxiao/84aa27cfb29363c19191829\
22649c93d/external/google_toolbox_for_mac/temp3594538897784615978/v2.2.1.zip
-----------------------------
**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment]
Hi @asd26187, 
Could you please elaborate your query with complete details and steps to reproduce the issue from our end. Thank you!

**Comment by asd26187** [comment]
I followed the [steps](https://google.github.io/mediapipe/getting_started/ios.html) here to install python as well as bazelisk and configure mobileprovision, but when I used
bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp
to build handtrackinggpu, I get these errors above.
@kuaashish

**Comment by kuaashish** [comment]
Hi @asd26187, Could you please share the complete error log and MediaPipe version used to investigate further. Thank you!

**Comment by kuaashish** [comment]
Hi @asd26187, Could you verify that you have changed the bundle_id as mentioned [here](https://google.github.io/mediapipe/getting_started/ios.html#custom-provisioning) in the documentation. If yes, then please try the workaround mentioned in this issue [#995(comment) ](https://github.com/google/mediapipe/issues/995#issuecomment-689168495). Thank you!

**Comment by asd26187** [comment]
Hi, when I changed the Bundle id I got another error, I changed the name to MediaPipe in the BUILD file I'm not sure why this error is reported? Can you help me to see? Thank you!
```
bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:MediaPipe
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /private/var/tmp/_bazel_yunxiao/6c3252f5b8b4818edac3a632a3033cff/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: /Users/yunxiao/Desktop/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:57:5: syntax error at 'hdrs': expected ,
ERROR: Skipping 'mediapipe/examples/ios/handtrackinggpu:MediaPipe': no such target '//mediapipe/examples/ios/handtrackinggpu:MediaPipe': target 'MediaPipe' not declared in package 'mediapipe/examples/ios/handtrackinggpu' defined by /Users/yunxiao/Desktop/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//mediapipe/examples/ios/handtrackinggpu:MediaPipe': target 'MediaPipe' not declared in package 'mediapipe/examples/ios/handtrackinggpu' defined by /Users/yunxiao/Desktop/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD
INFO: Elapsed time: 0.119s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```
This is the content of my BUILD file
```
load(
    "@build_bazel_rules_apple//apple:ios.bzl",
    "ios_application",
)
load(
    "//mediapipe/examples/ios:bundle_id.bzl",
    "BUNDLE_ID_PREFIX",
    "example_provisioning",
)

licenses(["notice"])

MIN_IOS_VERSION = "11.0"

alias(
    name = "handtrackinggpu",
    actual = "HandTrackingGpuApp",
)
load("@build_bazel_rules_apple//apple:ios.bzl","ios_framework",)
ios_framework(
    name = "MediaPipe"
    hdrs = [
        "HandTrackingViewController.h",
    ],
    infoplists = ["Info.plist"],
    bundle_id = BUNDLE_ID_PREFIX + ".mediapipe.examples.HandTrackingGpu",
    families = ["iphone","ipad"],
    minimum_os_version = MIN_IOS_VERSION,
    deps = [
        ":HandTrackingGpuAppLibrary",
        "@ios_opencv//:OpencvFramework",
    ],
)

```

**Comment by kuaashish** [comment]
Hi @asd26187, 
Please have a look at this [example](https://github.com/mgyong/awesome-mediapipe#ios) to build the Hand tracking in the ios and change the bundle id as mentioned [here](https://qiita.com/ponte1010/items/ed10cb2b5dcf7579f9bc#2-change-bundle-identifier) and let us know if encountering the same error. Thank you!

**Comment by asd26187** [comment]
Yes, I changed the bundleID and solved the problem just now, now there is a new problem, the framework I packaged does not work properly because the header files inside refer to the header files of other modules, how should I configure BUILD?
![image](https://user-images.githubusercontent.com/13916417/195075009-023724cf-e3a3-44e7-8350-81c391f3e25b.png)
![image](https://user-images.githubusercontent.com/13916417/195075317-6404ac72-86a8-4c9b-8e18-cbaf43bb9532.png)

**Comment by asd26187** [comment]
Can anyone tell me how to make a mediaPipe iOS framwork?

**Comment by kuaashish** [comment]
Hi @asd26187, 
Could you confirm that you have followed the steps to build mediapipe in the iOS as mentioned in the[ here](https://google.github.io/mediapipe/getting_started/ios.html). Please refer to Xcode project example shared by the Googler [here ](https://github.com/mgyong/awesome-mediapipe#ios).Thank you!

**Comment by asd26187** [comment]
Hi @kuaashish ,
Thank you very much, I've been able to compile the ios framework with the bazel build command, but I still can't understand how to depend on the files in other directories. For example, I compiled the common static library with 
```
bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/common:common
```
but when I introduced the static library into my project, I got an error from xcode build : 'mediapipe/objc/MPPCameraInputSource.h' file not found, because the file MPPCameraInputSource.h is not in the common directory, how should I write the BUILD file to make sure that all the files needed for the common static library can be How should I write the BUILD file to ensure that all the files needed by the common static library are linked in? I hope I didn't cause you any trouble, best wishes.

Translated with www.DeepL.com/Translator (free version)

**Comment by asd26187** [comment]
Hi @kuaashish 
This [article](https://powderapp.medium.com/mediapipe-tutorial-find-memes-that-match-your-facial-expression-9bf598da98c0) is already two years old,the project directory structure is not the same as before, is there a recent tutorial on packaging iOS framework?

**Comment by asd26187** [comment]
OK,thanks a lot!

**Comment by kuaashish** [comment]
Hi @asd26187,
Could we move this issue to the close status as the issue has been addressed and hope doesn't require the further support from us. Thank you!
