### ISSUE TITLE
Running Mediapipe in the cloud at scale

### ISSUE THREAD

**Issue by virtualsapiens** [google/mediapipe#3762]
I'm curious if anyone is running Mediapipe at scale in the cloud (AWS, GCP, etc)? I am working on an architecture that will need to scale up/down to support 1000s of frames per second (coming from multiple users).  Looking into running Medipaipe c++ on GPUs, but curious if anyone has any insights to share around scaling this.  Thanks!

**Comment by kuaashish** [comment]
Hi @virtualsapiens, 
Currently building MediaPipe is not tested on cloud platform such as GCP, AWS and does not have official documentation. Hope this article https://dev.classmethod.jp/articles/mediapipe-install-on-aws-ec2-with-gpu-english/ to build the MediaPipe in the AWS will be helpful. Thank you!

**Comment by WillBeebe** [comment]
I am. If you're still interested, I'm setting it up on GKE in GCP
