### ISSUE TITLE
The face lmks results has a large error when set "static_image_mode=False"  between windows and linux?

### ISSUE THREAD

**Issue by Dian-Yi** [google/mediapipe#3764]
First, I test face landmarks detection using python code  in windwos and linux, They are in the same python environment.
I get face lmks corrdinates from different OS(windows and linux). But, their maximum difference is over 7 pixle.
when I set static_image_mode==True, their maximum difference is very small.

**Comment by kuaashish** [comment]
Hi @Dian-Yi, 
static_image_mode: Whether to treat the input images as a batch of static and possibly unrelated images, or a video stream. See details in https://google.github.io/mediapipe/solutions/pose#static_image_mode. Please revert back if you have further question. Thank you!

**Comment by Dian-Yi** [comment]
> Hi @Dian-Yi, static_image_mode: Whether to treat the input images as a batch of static and possibly unrelated images, or a video stream. See details in https://google.github.io/mediapipe/solutions/pose#static_image_mode. Please revert back if you have further question. Thank you!

but when `static_image_mode=False`, the video stream face lmks results has has a large different between windows and linux. So, maybe tracking face process is different between windows and linux? or Has some error in tracking face in different OS?

**Comment by kuaashish** [comment]
Hi @Dian-Yi, 
Could you please bring up to our notice different results set observed in both of the cases to investigate further. Thank you!

**Comment by Dian-Yi** [comment]
my test video and code :

https://user-images.githubusercontent.com/44020057/196380741-76ea9fb4-e9c0-42f6-8f7e-6590ae6821ba.mp4


```
import cv2
import mediapipe as mp
import numpy as np

mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_face_mesh = mp.solutions.face_mesh


def make_lmks_data(all_frame):
    all_lmks = []
    with mp_face_mesh.FaceMesh(
            static_image_mode=False,
            max_num_faces=1,
            refine_landmarks=True,
            min_tracking_confidence=0.5,
            min_detection_confidence=0.5) as face_mesh:
        for idx, file in enumerate(all_frame):
            image = all_frame[idx]
            im_w, im_h = image.shape[1], image.shape[0]
            # Convert the BGR image to RGB before processing.
            results = face_mesh.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

            # Print and draw face mesh landmarks on the image.
            if not results.multi_face_landmarks:
                print(f"frame [{idx}]: no detection ")
                continue

            for face_landmarks in results.multi_face_landmarks:
                lmk = face_landmarks.landmark
                lmks_num = len(lmk)
                lmks468 = np.zeros((lmks_num, 3))

                for kp_idx in range(lmks_num):
                    lmks468[kp_idx, 0] = lmk[kp_idx].x * im_w
                    lmks468[kp_idx, 1] = lmk[kp_idx].y * im_h
                    lmks468[kp_idx, 2] = lmk[kp_idx].z * im_w
                # np.savetxt("face_lmks.txt", lmks468)
                all_lmks.append(lmks468)
    all_frame = np.array(all_lmks)
    print(all_frame.shape)
    np.save('face_lmks.npy', all_frame)


def get_frame(video_file):
    cap = cv2.VideoCapture(video_file)
    all_frame = []
    while True:
        ret, frame = cap.read()
        if not ret:break
        all_frame.append(frame)
    return all_frame

if __name__ == '__main__':
    all_frame =  get_frame("out.mp4")
    make_lmks_data(all_frame)

    # win_data = np.load('face_lmks.npy')
    # linux_data = np.load('face_lmks_linux.npy')
    # diff = win_data - linux_data
    # dif = np.abs(diff[0])
    # print(np.max(diff[:, :, 0]), np.max(diff[:, :, 1]), np.max(diff[:, :, 2]))
```
you can run this code in windows and LInux,  the np.max(diff) x, ,y z is: `1.9742202758789062 1.6003131866455078 0.9938335418701172`。 In some special videos, this value array is more big and maybe greater than 7pixel.

**Comment by kuaashish** [comment]
Hello @Dian-Yi,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
