### ISSUE TITLE
Running hand landmark model without mediapipe

### ISSUE THREAD

**Issue by emilwinzell** [google/mediapipe#3768]
Hello

I am want to implement a hand detection algorithm on a mobile device and need to run the **hand_landmark_lite.tflite** model separately without the mediapipe library. When I run inference on some images with the model I get poor predictions of the landmarks (compared to running with mediapipe and `static_image_mode = True, model_complexity=0` (see code below). I have two questions:

* What do the four different outputs from the model (**hand_landmark_lite.tflite**)mean? 
*  Are mediapipe doing something else to the predictions in order to enhance them? I don't understand why my predictions would be much worse with the same model.

Example images of results:

**Mediapipe prediction with (static_image_mode = True, model_complexity=0)**
<img width="186" alt="mediapipe" src="https://user-images.githubusercontent.com/67626018/195522918-a423ba2e-0b14-4f5e-a3f1-6b3f3ed2a348.png">

**Prediction with hand_landmark_lite.tflite**
<img width="189" alt="handlmk" src="https://user-images.githubusercontent.com/67626018/195523201-106b6f8a-d0d7-4a29-b423-9263561474a8.png">

My code for running inference:
macOS Catalina
python 3.8.5
tensorflow 2.7.0
tflite-runtime 2.5.0
mediapipe: 0.8.11

```python
import cv2
import numpy as np
import tflite_runtime.interpreter as tflite
import glob
from time import time

def get_data():
    data = []
    imgs = []
    for file in glob.glob('<PATHTOIMAGES>/img_*.jpg'):
        img = cv2.imread(file)
        img_244 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img_224 = cv2.resize(img_244, (224,224))[np.newaxis, :, :, :]

        img_224 = (np.float32(img_224) - 0.0) / 255.0
        data.append(img_224)
        imgs.append(img)

    return data, imgs

def main():

    model_path = '<PATHTOMODEL>/hand_landmark_lite.tflite'
    interpreter = tflite.Interpreter(model_path=model_path)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    print('INPUT\n', input_details)
    print('OUTPUT\n',output_details)

    data,imgs = get_data() # get and preprocess data
    input_data = data[1] # take one of the images
    org_image = imgs[1] # save original
    print(input_data.shape)

    interpreter.set_tensor(input_details[0]['index'], input_data)

     # Execute the inference
    t1=time()
    interpreter.invoke()
    t2=time()

    output_data1 = interpreter.get_tensor(output_details[0]['index'])[0]
    #print(output_data1)
    output_data2 = interpreter.get_tensor(output_details[1]['index'])
    #print(output_data2)
    output_data3 = interpreter.get_tensor(output_details[2]['index'])
    #print(output_data3)
    output_data4 = interpreter.get_tensor(output_details[3]['index'])
    #print(output_data4)

    pred = np.array(output_data1)
    pred = np.reshape(pred,(-1,3))
    landmarks = []
    for i,lmk in enumerate(pred):
        #print(lmk)
        lmx = int(lmk[0]/224.0*500)
        lmy = int(lmk[1]/224.0*500)
        landmarks.append([lmx, lmy])
        if i == 8: # make the tip of the idex finger more visible for reference
            cv2.circle(org_image,(lmx,lmy), 4, (255,0,0), -1)
        else:
            cv2.circle(org_image,(lmx,lmy), 2, (0,0,255), -1)

    print(landmarks)
    cv2.imshow('tflite model', org_image)
    cv2.waitKey(0)
    print('Inference time:',t2-t1,'s')

if __name__ == "__main__":
    main()
```

**Comment by kuaashish** [comment]
Hi @emilwinzell, Could you provide the demo with different output with several good input images it will be helpful to investigate further on the issue. Thank you!

**Comment by emilwinzell** [comment]
Found a proper implementation at: [https://github.com/aashish2000/hand_tracking](url). Will try to use some of the code in my project

**Comment by kuaashish** [comment]
Hi @emilwinzell, 
Please refer to the above [example](https://github.com/google/mediapipe/issues/3768#issuecomment-1277466636) to implement the hand_tracking tflite model and let us know if you are encountering the same error. Thank you!

**Comment by smartheit** [comment]
Hi, I am seeing the same phenomena as emilwinzell.
The example where he was pointing do works but is still not as good as using mediapipe directly.
I can't use mediapipe too as the final model should run on CNN accelerator in a FPGA device. It there an example with the latest hand_landmark.tflite model ?
