### ISSUE TITLE
How to calculate the palm size

### ISSUE THREAD

**Issue by ZYX-MLer** [google/mediapipe#3776]
The paper "MediaPipe Hands: On-device Real-time Hand Tracking" side the MSE normalized by palm size is 13.4%. 
Can you tell me, how to calculate the palm size, and do you test the method using the error in mm?

Best wishes

**Comment by kuaashish** [comment]
Hi @ZYX-MLer,
Could you please elaborate your query with complete details and use case to calculate the palm size using the Handtracking solution. Thank you!
