### ISSUE TITLE
Android AAR without required pakcages `solutions` & `solutioncore`

### ISSUE THREAD

**Issue by xbwee1024** [google/mediapipe#3777]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 11
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic): FaceMesh
- Programming Language and version ( e.g. C++, Python, Java): Java

**Describe the expected behavior:**
1. build facemesh solution android aar as following: [Android Archive Library](https://google.github.io/mediapipe/getting_started/android_archive_library.html)
2. Copy facemesh aar to my projects `app/libs/`, after gradle sync and compile project, errors happened
`package com.google.mediapipe.solutions.facemesh does not exists`
4. unzip aar to get classes.jar, open it with jd-gui, there is no `com.google.mediapipe.solutions` and `com.google.mediapipe.solutioncore` in deed.

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:
![1666146291677-image](https://user-images.githubusercontent.com/2572134/196582559-dd100633-1a57-4784-895d-23bda0f92294.png)

**Comment by kuaashish** [comment]
Hi @xbwee1024,
Could you please elaborate your query with complete details and support you are looking to. Thank you!

**Comment by xbwee1024** [comment]
My problem is: 
1. There is no `com.google.mediapipe.solutioncore` and `com.google.mediapipe.solutions.facemesh` in the generated AAR archive. I build it as follows:
`bazel build -c opt --strip=ALWAYS --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a --legacy_whole_archive=0 --features=-legacy_whole_archive --copt=-fvisibility=hidden --copt=-ffunction-sections --copt=-fdata-sections --copt=-fstack-protector --copt=-Oz --copt=-fomit-frame-pointer --copt=-DABSL_MIN_LOG_LEVEL=2 --linkopt=-Wl,--gc-sections,--strip-all //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_mesh.aar`

2. How to build a complete solution (i.e. facemesh) android AAR which can be used in my project.

**Comment by notjedi** [comment]
@xbwee1024 i don't think there is a way to do that. the files inside of `mediapipe/examples/android/solutions` are just examples and are not meant to be used as an AAR. at least afaik.

**Comment by xbwee1024** [comment]
After sync with gradle, I found `facemesh-0.8.11-alpha-1.aar` and `solution-core-0.8.11-alpha-1.aar` which is downloaded from maven, so I tried to build `solution_core` and `facemesh` AAR seperatedly, this resolved my problems. (If I tried to build one whole aar, it will be always failed with weird errors).
Thanks~

**Comment by xbwee1024** [comment]
@notjedi  Thanks for your reply, I don't think so, because mediapipe team give this guideline: https://google.github.io/mediapipe/getting_started/android_archive_library.html

And indeed, we can customize and build solutions AAR and used in other android projects.

**Comment by xbwee1024** [comment]
@notjedi  Thanks for your reply, I don't think so, because mediapipe team give this guideline: https://google.github.io/mediapipe/getting_started/android_archive_library.html

And indeed, we can customize and build solutions AAR and used in other android projects.

**Comment by xbwee1024** [comment]
BTW：
If anybody has the same problem, you could refer to my changes for some suggestions:
https://github.com/xbwee1024/mediapipe/commit/6d17ccb32b56def2c4c13c8aad5b40ed3c9dc3e2
