### ISSUE TITLE
Euler angles of Hand

### ISSUE THREAD

**Issue by harirnair** [google/mediapipe#3778]
I'm using Mediapipe Pose Model in javascript, I wanted to know whether there is any way to calculate orientation of the hand with respect to wrist using the keypoints available from the model.

**Comment by kuaashish** [comment]
Hi @harirnair,
The hand model itself is limited to hand-landmarks only, does not include any arm-landmarks, so there is not sufficient info in the landmarks to calculate the wrist-angle. 
Another, Hand-landmarks are 2D landmarks calibrated to the video frame image, So 3D wrist angle will be difficult to calculate, even given an assumption about the arm positions. Possibly the MediaPipe geometry library could be helpful. Thank you!

**Comment by harirnair** [comment]
I'm using Pose model and taking the keypoints of wrist, i.e keypoint[16] and need to get the angle of hand, keypoint[18] or [20] with respect to [16].

**Comment by kuaashish** [comment]
Hello @harirnair,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
