### ISSUE TITLE
How to read the kinetics processed tfrecord?

### ISSUE THREAD

**Issue by skaws2003** [google/mediapipe#378]
I just followed the [kinetics data processing example](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/media_sequence/README.md#custom-videos-in-the-kinetics-format), and got `kinetics_700_custom_25fps_rgb_flow-00000-of-00001` under tmp/ms/kinetics.

I tried reading as suggested on [this issue](https://github.com/google/mediapipe/issues/257#issuecomment-555654883):
```
import tensorflow as tf
for example in tf.python_io.tf_record_iterator('/tmp/ms/kinetics/kinetics_700_custom_25fps_rgb_flow-00000-of-00001'):
  print(tf.train.SequenceExample.FromString(example))
```
But it shows really weird string like:
```
(...)
w{_\177\351=\200(\372\377\000\237O\363\351\3158\003\307\241\340\375\001\037\347\350\t\350)\3149\007\260\353\323\363\347\257\037\313\236\234;\253\333\327\364\323\327_\313\272\002:(=O\177\363\365?\316\212`\024QE\000\025\033\203\370\177Rx\343\327\236\275\375\252JF\350x\317\267\371\377\000#\257Z\007\027f\275\177=\010(\245\364\374\275\273\177\237a\217\255%\006\341E\024P\007\377\331"                   }                                                                                                                                                              }                                                                                                                                                                feature {                                                                                                                                                          bytes_list {                                                                                                                                                       value: "\377\330\377\340\000\020JFIF\000\001\001\000\000\001\000\001\000\000\377\333\000C\000\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\001\377\
(...)
```
It seems like there is a problem on reading. What should I do in order to read properly?

**Comment by jiuqiant** [comment]
Have you tried @bryanseybold's [suggestion](https://github.com/google/mediapipe/issues/257#issuecomment-562744007)?

The output is expected to have some unreadable bytes because of the encoded images.

**Comment by skaws2003** [comment]
@jiuqiant Thank you for response. I tried below, which I believe ame with the referred suggestion.
```
from mediapipe.examples.desktop.media_sequence.kinetics_dataset import Kinetics
import tensorflow as tf

data = Kinetics("...")
dataset = data.as_dataset("custom")

tensors = dataset.make_one_shot_iterator().get_next()
images = tensors["images"]
flow = tensors["flow"]

sess = tf.InteractiveSession()
with sess.as_default():
  print(images.eval())
```
It runs well before the final line, but typing the final line results this exception
```
Traceback (most recent call last):
  File "/home/skaws2003/venv/exercise/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/skaws2003/venv/exercise/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/skaws2003/venv/exercise/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map_parse_fn_190}} Name: , Context feature 'clip/label/index' is required but could not be found.
         [[{{node ParseSingleSequenceExample/ParseSingleSequenceExample}}]]
         [[IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/skaws2003/venv/exercise/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 798, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/skaws2003/venv/exercise/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 5407, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/skaws2003/venv/exercise/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/skaws2003/venv/exercise/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/skaws2003/venv/exercise/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/skaws2003/venv/exercise/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Name: , Context feature 'clip/label/index' is required but could not be found.
         [[{{node ParseSingleSequenceExample/ParseSingleSequenceExample}}]]
         [[IteratorGetNext]]
```

**Comment by bryanseybold** [comment]
Ah, there's a bug but also an immediate work-around.

When you create the data set, please allow the code to download the label map by keeping the default flag value of --download_labels_for_map=true. 

I'll change the reading code to take a parameter for whether to parse the label index field. (If you want, you could comment out or delete those lines as a temporary fix.)

Thank you for reporting this.

**Comment by bryanseybold** [comment]
Rather than the flag not being true, you may not have specified a label in your custom data .csv.
That makes sense for evaluation, so this is definitely a bug. I'll add that new parameter.

**Comment by ss-github-code** [comment]
After setting parse_labels=False in kinetics_dataset.py, I can get images.eval() to work (or flow.eval() to work). But when I try to call both images.eval() and flow.eval(), I get an OutOfRangeError: End of sequence error,

**Comment by bryanseybold** [comment]
Responding to:
> After setting parse_labels=False in kinetics_dataset.py, I can get images.eval() to work (or flow.eval() 
> to work). But when I try to call both images.eval() and flow.eval(), I get an OutOfRangeError: End of 
> sequence error,

The behavior of .eval() can be surprising with datasets in tf1. (tf2 doesn't have this issue.) Each time you call .eval(), it will run the entire data set provider to get a new example, extract the part you called eval on (images or flow) and throw away the other. The images and flow will not match for a single example if you use .eval(). Instead use:

```
with tf.Session() as sess:
    images_out, flow_out = sess.run([images, flow])
```

My guess is that you only have one element in your data set. When you call eval a second time, there's not a second element in your data set to retrieve, and it throws an error. Is that correct?

**Comment by ss-github-code** [comment]
Thank you! that works. One more question though: if I look at avi file, it shows a resolution of 320x240. But when I look at the numpy array, it has a shape (79, 256, 340, 3). What does that mean?

Also, evaluate_sample.py shows the shape to be (79, 224, 224, 3). What would I need to do in the graph to make sure that I get a 224x224 carved out so that I can match the _IMAGE_SIZE in evaluate_sample.py.

**Comment by bryanseybold** [comment]
The videos are automatically rescaled to 256 along the height dimension by the ScaleImageCalculator at line 55 of this file: https://github.com/google/mediapipe/blob/master/mediapipe/graphs/media_sequence/tvl1_flow_and_rgb_from_file.pbtxt

The reason for downscaling the image is that it decreases memory costs. The preprocessing for I3D then further downsamples to 224x224, so 256x? seemed like a reasonable resolution to crop from. Typically, I think inference numbers for I3D are reported on center crops (so take the middle 224x224 crop out of the 256 x 340 image) and pass that to evaluate_sample.
`cropped_image = image[:, 16:-16, 62:-62, :]` should be a center crop (though using variables instead of constants will make it more flexible).

**Comment by ss-github-code** [comment]
Thanks, but I am still unable to replicate the result of evaluate_sample.py for v_CricketShot_g04_c01.avi. It does run but the Norm of logits and the top class is incorrect.

**Comment by johnnyclapham** [comment]
> csv

Were you able to replicate the results and what was the solution?

**Comment by johnnyclapham** [comment]
> Thanks, but I am still unable to replicate the result of evaluate_sample.py for v_CricketShot_g04_c01.avi. It does run but the Norm of logits and the top class is incorrect. Is there any debugging step that I can use to identify the problem. e.g. can I take a dump of the rgb before it is normalized.


Were you able to replicate the results and what was the solution?
