### ISSUE TITLE
MediaPipe  hand model

### ISSUE THREAD

**Issue by aureosun** [google/mediapipe#3780]
I'm using mediapipe to build my own appplications, but found the performance did not achieve the desired effect. so I'd like to training the model using my own data to meet the specific scenario. but the information of [palm_detection](https://github.com/google/mediapipe/tree/master/mediapipe/modules/palm_detection) and [hand_landmark](https://github.com/google/mediapipe/tree/master/mediapipe/modules/hand_landmark) is insufficient, could you please give me more info? the paper "MediaPipe Hands: On-device Real-time Hand Tracking"( https://arxiv.org/abs/2006.10214v1) also encounter the same problem, any infomation about the above models ? please help me, thanks!

**Comment by kuaashish** [comment]
Hi @aureosun,
Is it implemented through python, javascript or other solutions available in mediapipe? Could you share the complete details to  understand the issue better, Thank you!
