### ISSUE TITLE
memory leak inside `effect_renderer.cc`

### ISSUE THREAD

**Issue by notjedi** [google/mediapipe#3784]
**System information**

- Have I written custom code: Yes
- OS Platform and Distribution: Andorid
- Programming Language and version: C++
- [MediaPipe version](https://github.com/google/mediapipe/releases): 467cd34feb273e9f839480acb69e5ca721f4dc29
- Bazel version (if compiling from source): `5.2.0`

**Describe the current behavior:**
In [mediapipe/modules/face_geometry/libs/effect_renderer.cc#L164](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/libs/effect_renderer.cc#L164), the current implementation uses `glDeleteProgram` to delete the `GL_TEXTURE_2D`. this leads to a memory leak, as the correct way to delete a texture created using `glGenTextures` would be to use `glDeleteTextures`.

**Describe the expected behavior:**
Should correctly delete the `GL_TEXTURE_2D` using `glDeleteTextures` instead of `glDeleteProgram` so the `Texture` object doesn't leak memory.

**Standalone code to reproduce the issue:**
The existing example of [face_effect](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect) should be enough to reproduce the bug.

**Comment by kuaashish** [comment]
Hi @notjedi,
Could you elaborate your query with complete details and observation made in the case of a memory leak.
Thank you!
