### ISSUE TITLE
Unclear how to access palm data when using `multiHandWorldLandmarks`

### ISSUE THREAD

**Issue by hybridherbst** [google/mediapipe#3788]
## URL(s) with the issue:
https://google.github.io/mediapipe/solutions/hands.html#multi_hand_world_landmarks

## Description of issue (what needs changing):

Kinds of documentation problems:
While multi_hand_landmarks are in camera space and already contain palm position data, multi_hand_world_landmarks are relative to the palm position. However, the docs do not explain how to access palm position and orientation, for example from JavaScript.

### Clear description

For restoring actual 3D positions of hands, multi_hand_landmarks isn't very useful (as the resulting depth data is distorted). multi_hand_world_landmarks seems to return "less distorted" values, but is in palm space. Thus, the docs should provide a way to fetch palm space so that these types of data can be mapped to each other.

### Raises listed and defined

Are the errors defined? For example,

### Usage example

No, there is no usage example for how to get palm position and combine that data with multi_hand_world_landmarks.

**Comment by kuaashish** [comment]
Hi @hybridherbst,
We have this thread #3047 already running to retrieve the both hand coordinates and functions mentioned to get the landmarks using the multiHandWorldLandmarks. Thank you!

**Comment by hybridherbst** [comment]
Hi @kuaashish, I read through that other issue but can't see information related to the problem outlined here.
While `multi_hand_landmarks` are in screen space, `multi_hand_world_landmarks` are in palm space. 

My question would thus be how to access plam coordinates from JavaScript for use with world landmarks. 

The other thread doesn't seem to use world landmarks at all, and screen-space landmarks don't have that issue.

**Comment by kuaashish** [comment]
Hi @hybridherbst,
Palm coordinates are currently only communicated between calculators in the graph, [hand_landmark_cpu.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_cpu.pbtxt) or [hand_landmark_gpu.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_gpu.pbtxt).  The transformation is done using MediaPipe calculators, not currently in JavaScript.

Approaches: 
 * try writing a small graph to do the transformation, and run this from JavaScript. 
 * try adding an output stream for the palm "region of interest", and then implementing a transform in JavaScript.  
 
Thank you!
