### ISSUE TITLE
Android app crash with SIGSEGV

### ISSUE THREAD

**Issue by wujiayi0214** [google/mediapipe#3789]
We use face_mesh solution in our app, and get crash report of google play, we tested during development but didn't face such crash

backtrace:
  #00  pc 0x0000000000080130  /apex/com.android.runtime/lib64/bionic/libc.so (strlen+16)
  #01  pc 0x00000000001e87c8  /data/app/com.selfie.demo.pro-kUZPts2keA74R0Vb5rCfxQ==/split_config.arm64_v8a.apk (mediapipe::PathToResourceAsFile(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+216)
  #02  pc 0x00000000001ab564  /data/app/com.selfie.demo.pro-kUZPts2keA74R0Vb5rCfxQ==/split_config.arm64_v8a.apk (mediapipe::LocalFileContentsCalculator::Open(mediapipe::CalculatorContext*)+192)
  #03  pc 0x00000000007c79a0  /data/app/com.selfie.demo.pro-kUZPts2keA74R0Vb5rCfxQ==/split_config.arm64_v8a.apk (mediapipe::CalculatorNode::OpenNode()+432)
  #04  pc 0x00000000007bd270  /data/app/com.selfie.demo.pro-kUZPts2keA74R0Vb5rCfxQ==/split_config.arm64_v8a.apk (mediapipe::internal::SchedulerQueue::OpenCalculatorNode(mediapipe::CalculatorNode*)+160)
  #05  pc 0x00000000007bd0ec  /data/app/com.selfie.demo.pro-kUZPts2keA74R0Vb5rCfxQ==/split_config.arm64_v8a.apk (mediapipe::internal::SchedulerQueue::RunNextTask()+100)
  #06  pc 0x00000000007df2a4  /data/app/com.selfie.demo.pro-kUZPts2keA74R0Vb5rCfxQ==/split_config.arm64_v8a.apk (mediapipe::ThreadPool::RunWorker()+124)
  #07  pc 0x00000000007df00c  /data/app/com.selfie.demo.pro-kUZPts2keA74R0Vb5rCfxQ==/split_config.arm64_v8a.apk (mediapipe::ThreadPool::WorkerThread::ThreadBody(void*)+796)
  #08  pc 0x00000000000e55b4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
  #09  pc 0x0000000000085458  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

**Comment by kuaashish** [comment]
Hi @wujiayi0214,

Replace the SwitchContainer and ConstantPacketCalculator with a simpler file path, see if the crash can still happen.
**Suggestation:** accept "FILE_PATH" side packet as an input side packet into the graph. 

Please refer to [this](https://stackoverflow.com/questions/55795041/how-to-solve-android-fatal-signal-11-sigsegv-code-1-fault-addr-0x0-in-tid-xx) issue and let us know if you are encountering the same error. Thank you!
