### ISSUE TITLE
face recognition on mediapipe

### ISSUE THREAD

**Issue by interesting926** [google/mediapipe#3791]
I have just started learning mediapipe and I want to know how I can achieve face recognition. I know that face detections detect faces and face mesh checks for landmarks on a person's face, but how should I compare the face in the camera with the data stored in the program?

**Comment by kuaashish** [comment]
Hi @interesting926,
Is it implemented through Python, Javascript or other solutions available in the MediaPipe? Could you please help us to understand the query better from our end. Thank you!

**Comment by interesting926** [comment]
i use python,and i wonder how can i use face  recognition

**Comment by kuaashish** [comment]
Hi @interesting926,
MediaPipe does not include a face recognition, module or model. Thank you!

**Comment by kuaashish** [comment]
Hi @interesting926,
Could you please go through the [above](https://github.com/google/mediapipe/issues/3791#issuecomment-1305346174) comment and let us know if we can move the issue to the close status. Thank you!
