### ISSUE TITLE
Deth-from-iris web demo not working

### ISSUE THREAD

**Issue by alexandernst** [google/mediapipe#3793]
**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): MacOS 12.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Chrome 106.0.5249.119
- Programming Language and version ( e.g. C++, Python, Java): N/A
- [MediaPipe version](https://github.com/google/mediapipe/releases): N/A
- Bazel version (if compiling from source): N/A
- Solution ( e.g. FaceMesh, Pose, Holistic ): Depth from Iris
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): N/A
- Xcode & Tulsi version (if issue is related to building for iOS): N/A

**Describe the current behavior:**

I tried to try the demo at https://viz.mediapipe.dev/demo/iris_depth and it failed running

**Describe the expected behavior:**

The demo should run.

**Standalone code to reproduce the issue:**

https://viz.mediapipe.dev/demo/iris_depth

**Other info / Complete Logs :**
N/A

**Comment by kuaashish** [comment]
Hi @alexandernst,
Please refer to this closed issue #3486 and [#3486(Comment)](https://github.com/google/mediapipe/issues/3486#issuecomment-1177803351) for better understanding of your query. Thank you!

**Comment by alexandernst** [comment]
@kuaashish I'm talking about the web demo hosted at https://viz.mediapipe.dev/demo/iris_depth, which is not working. Please check the link

**Comment by kuaashish** [comment]
Hi @alexandernst,
Thanks for reporting this bug. I was able to reproduce the issue the Depth-from-iris web demo is not working in the MacOS 12.6 with Chrome 106.0.5249.119 as expected. We are forwarding this issue to the appropriate team and Hope this issue will be fixed soon. Thank you!

**Comment by kuaashish** [comment]
Hello @alexandernst,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
