### ISSUE TITLE
Mediapipe code which does drawing of lines on hand

### ISSUE THREAD

**Issue by suraj-0387** [google/mediapipe#380]
which part of java code does the display of lines on hand

**Comment by lcycoding** [comment]
The annotation part is not in java, it's in the calculator `AnnotationOverlay`

**Comment by suraj-0387** [comment]
Is it possile to draw 3d object with mediapipe library in java code?

**Comment by lcycoding** [comment]
I think what you need is to design a mediapipe graph which can draw the designated object, then run on Android sample app.
