### ISSUE TITLE
build c++ native  hand_tracking_cpu error

### ISSUE THREAD

**Issue by quire7** [google/mediapipe#3802]
- OS Platform and Distribution (Linux Ubuntu 18.04):
- Compiler version (gcc/g++ 7.5.0):
- Programming Language and version ( e.g. C++ 17 ):

- [MediaPipe version](v.0.8.10.2):
- Bazel version: 5.2.0
- OpenCV version (4.x):

**Describe the problem**:
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

**Complete Logs:**
pateo@pateo-OptiPlex-3070:~/fxd/work/gitLab/mediapipe$ bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
DEBUG: /home/pateo/.cache/bazel/_bazel_pateo/5d11cd4a980ad421ad0c4e0fc4dc57da/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/pateo/.cache/bazel/_bazel_pateo/5d11cd4a980ad421ad0c4e0fc4dc57da/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /home/pateo/.cache/bazel/_bazel_pateo/5d11cd4a980ad421ad0c4e0fc4dc57da/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/pateo/.cache/bazel/_bazel_pateo/5d11cd4a980ad421ad0c4e0fc4dc57da/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/pateo/.cache/bazel/_bazel_pateo/5d11cd4a980ad421ad0c4e0fc4dc57da/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/pateo/.cache/bazel/_bazel_pateo/5d11cd4a980ad421ad0c4e0fc4dc57da/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/pateo/.cache/bazel/_bazel_pateo/5d11cd4a980ad421ad0c4e0fc4dc57da/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/pateo/.cache/bazel/_bazel_pateo/5d11cd4a980ad421ad0c4e0fc4dc57da/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/pateo/.cache/bazel/_bazel_pateo/5d11cd4a980ad421ad0c4e0fc4dc57da/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/pateo/.cache/bazel/_bazel_pateo/5d11cd4a980ad421ad0c4e0fc4dc57da/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /home/pateo/.cache/bazel/_bazel_pateo/5d11cd4a980ad421ad0c4e0fc4dc57da/external/org_tensorflow/third_party/repo.bzl:124:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build options --copt, --cxxopt, and --host_cxxopt have changed, discarding analysis cache.
WARNING: /home/pateo/fxd/work/gitLab/mediapipe/mediapipe/framework/tool/BUILD:184:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /home/pateo/fxd/work/gitLab/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (12 packages loaded, 5654 targets configured).
INFO: Found 1 target...
INFO: From Compiling mediapipe/framework/tool/message_type_util.cc [for host]:
mediapipe/framework/tool/message_type_util.cc: In static member function 'static int mediapipe::DescriptorReader::MatchingPrefixLength(const string&, const string&)':
mediapipe/framework/tool/message_type_util.cc:66:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     while (i < std::min(s.size(), t.size()) && s[i] == t[i]) {
            ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: /home/pateo/fxd/work/gitLab/mediapipe/mediapipe/calculators/tensor/BUILD:756:11: Compiling mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 61 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc: In member function 'virtual absl::lts_20210324::StatusOr<mediapipe::Tensor> mediapipe::{anonymous}::OpenCvProcessor::Convert(const mediapipe::Image&, const mediapipe::RotatedRect&, const mediapipe::Size&, float, float)':
**_mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc:135:12: error: could not convert 'tensor' from 'mediapipe::Tensor' to 'absl::lts_20210324::StatusOr<mediapipe::Tensor>'
     return tensor;
            ^~~~~~_**
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 248.528s, Critical Path: 130.80s
INFO: 1220 processes: 80 internal, 1140 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by kuaashish** [comment]
Hi @quire7,
Could you confirm that you have followed the steps to build MediaPipe as mentioned in the official [documentation](https://google.github.io/mediapipe/getting_started/install.html) and able to build the Hello_world example successfully as mentioned [here](https://google.github.io/mediapipe/getting_started/hello_world_cpp.html#hello-world-in-c). Thank you!
