### ISSUE TITLE
Cannot run simple hellow world project, error: does not contain symbol 'use_cpp_toolchain'

### ISSUE THREAD

**Issue by bmartynchyk** [google/mediapipe#3803]
<em>Hi, 
I'm newbie in mediapipe. I have simple mediapipe project on Ubuntu which I created above 1 year ago. And the project was building and running. I decided to immerse myself into mediapipe again. And now I'm about one week and a half cann't to solve the issue how to build and run my 1 year old project. I change different Ubuntu systems since 16 to 22. Now I on 20.04.5. I'm working on VirtualBox.</em>

**System information**
- OS: Linux Ubuntu 20.04.5 (installed as guest OS on VirtualBox)
- Compiler version: g++ 9.4.0
- Programming Language: C++ 14
- Installed using virtualenv: pip3 (python version: 2.7.18, python3 version: 3.8.10)
- MediaPipe version: I don't know how to find out my current version of mediapipe. I can if you clarify my how to do it.
- Bazel version: 3.4.1

**Describe the problem**:
<em>I cannot build and run my project.</em>

**Exact sequence of commands / steps I executed before running into the problem:**
<em>After installing virtual machine I doing these commands:</em>

$ sudo apt-get apdate
$ sudo apt-get upgrade

$ sudo apt install python3-pip
$ sudo apt-get apdate

$ pip install -r requirements.txt

<em>requirements.txt has following content:</em>
absl-py
dataclasses
numpy == 1.19.3
opencv-python
protobuf>=3.11.4
six
wheel

<em>Then I was installing bazel version 3.4.1</em>
mkdir $HOME/bazel-3.4.1
cd $HOME/bazel-3.4.1
wget https://github.com/bazelbuild/bazel/releases/download/3.4.1/bazel-3.4.1-dist.zip
sudo apt-get install build-essential openjdk-8-jdk python zip unzip
unzip bazel-3.4.1-dist.zip
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
sudo cp output/bazel /usr/local/bin/

<em>Then I was running script to build OpenCV from source code and modify the MediaPipe opencv config.</em>
$ ./setup_opencv.sh

<em>And try to build the target</em>
$ bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 \
  mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

<em>After that I got following errors:</em>

**Complete Logs:**
bm@bm-VirtualBox:~/shared/dynamic_comands_hgr_cpu_main$ bazel build --config debug -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop:demo_run_graph_main
ERROR: /home/bm/.cache/bazel/_bazel_bm/df2374ae819f096af0328365b4e8c162/external/rules_cc/cc/private/rules_impl/compiler_flag.bzl:17:1: file '@bazel_tools//tools/cpp:toolchain_utils.bzl' does not contain symbol 'use_cpp_toolchain' (did you mean 'find_cpp_toolchain'?)
ERROR: While resolving toolchains for target //mediapipe/examples/desktop:demo_run_graph_main: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /home/bm/.cache/bazel/_bazel_bm/df2374ae819f096af0328365b4e8c162/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/compiler_flag.bzl' has errors
ERROR: Analysis of target '//mediapipe/examples/desktop:demo_run_graph_main' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /home/bm/.cache/bazel/_bazel_bm/df2374ae819f096af0328365b4e8c162/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/compiler_flag.bzl' has errors
INFO: Elapsed time: 0.102s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)

**Comment by kuaashish** [comment]
Hi @bmartynchyk,
Please refer to this closed issue #3457 and [#3457(Comment)](https://github.com/google/mediapipe/issues/3457#issuecomment-1163816267) for better understanding on your query. Thank you!
