### ISSUE TITLE
E/chromium: [ERROR:web_contents_delegate.cc(238)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.

### ISSUE THREAD

**Issue by hanbyeongky** [google/mediapipe#3804]
I'm trying to add functionality to my hybrid app by leveraging the Mideapipe Face Mesh for JavaScript.

However, the permission error keeps popping up because it runs as a webview.
It says that you do not have permission and the video itself does not appear.
Does anyone know how to solve it???

I am packing after work using ionic vue capacitor.

please answer my question
![20221030_203943](https://user-images.githubusercontent.com/41810924/198876527-85c1ea32-086a-4087-8d94-1e88ec2f501d.png)

**Comment by kuaashish** [comment]
Hi @hanbyeongky,
MediaPipe team has not yet tested any solutions, including face-mesh, on WebView in JavaScript. Seems plausible that the permissions problem is related to WebView. 
We think this bug requires more investigation. If you could help us to investigate, the MediaPipe team will appreciate and be interested in any findings. Thank you!
