### ISSUE TITLE
cannot install accordiing to installation tutorial

### ISSUE THREAD

**Issue by liaoyd16** [google/mediapipe#3805]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Linux Ubuntu 20.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, Python 3.10
- Installed using virtualenv? pip? Conda? (if python): none
- [MediaPipe version](https://github.com/google/mediapipe/releases): none
- Bazel version: bazel 5.2.0
- XCode and Tulsi versions (if iOS): none
- Android SDK and NDK versions (if android): none
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): none
- OpenCV version (if running on desktop): 4.6.0

**Describe the problem**: following all steps in https://google.github.io/mediapipe/getting_started/install.html, I still cannot use mediapipe in python:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mediapipe'
```
I tried to run setup.py, but got stuck and had to interrupt. Then mediapipe could not be successfully imported.

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/Downloads/mediapipe/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/home/daniel/Downloads/mediapipe/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'
```

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
```
git clone https://github.com/google/mediapipe.git
cd mediapipe/
sudo apt-get install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev
export GLOG_logtostderr=1
bazel run --define MEDIAPIPE_DISABLE_GPU=1     mediapipe/examples/desktop/hello_world:hello_world
bazel build --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11
python setup.py build
```
Then, the process stuck at here:
```
[1,594 / 1,605] CcCmakeMakeRule third_party/opencv_cmake/include; 272s linux-sandbox
```
I had to interrupt the process.
I tried to copy `mediapipe/` directory to `site-packages/` directory, but it couldn't find mediapipe.solutions:

```
>>> import mediapipe.solutions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mediapipe.solutions'
```

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by liaoyd16** [comment]
I followed https://google.github.io/mediapipe/getting_started/python.html#building-mediapipe-python-package instructions, and after the installation was done, I ran the python in "mediapipe/mp_env/bin/", and then `import mediapipe`, but still got
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/Downloads/mediapipe/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/home/daniel/Downloads/mediapipe/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'
```
Then I switched out of the `mediapipe/` folder and ran steps above, and encountered this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/Downloads/mediapipe/mp_env/lib/python3.10/site-packages/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/home/daniel/Downloads/mediapipe/mp_env/lib/python3.10/site-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: /home/daniel/Downloads/mediapipe/mp_env/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2cv3MatC1Ev
```

**Comment by owuQQQ** [comment]
I also encountered the same problem, I'm using Pycharm and tried to download Mediapipe by "pip install Mediapipe", but it seems that the IDE couldn't find the package.

**Comment by bedbad** [comment]
@jiuqiant how to solve this problem if mediapipe is installed hermetically  through the pip_parse bazel rule(requirements installed automatically) and you can't exit the repo?
