### ISSUE TITLE
js holistic solution crashes when setting refineFaceLandmarks

### ISSUE THREAD

**Issue by vladmandic** [google/mediapipe#3806]
per comments in #3534, `refineFaceLandmarks` is supported in in [holistic@0.5](https://www.npmjs.com/package/@mediapipe/holistic)

however, when i enable it using 

```js
holistic.setOptions({ smoothLandmarks: true, refineFaceLandmarks: true, enableFaceGeometry: true });
```

it immediately crashes:

```log
holistic_solution_simd_wasm_bin.js:9      
  Uncaught (in promise) RuntimeError: abort(undefined) at Error
    at jsStackTrace (holistic_solution_simd_wasm_bin.js:9:69364)
    at stackTrace (holistic_solution_simd_wasm_bin.js:9:69540)
    at abort (holistic_solution_simd_wasm_bin.js:9:43094)
    at _abort (holistic_solution_simd_wasm_bin.js:9:180749)
    at holistic_solution_simd_wasm_bin.wasm:0x5686f9
    at holistic_solution_simd_wasm_bin.wasm:0x56859e
    at holistic_solution_simd_wasm_bin.wasm:0x568712
    at holistic_solution_simd_wasm_bin.wasm:0x1ce27
    at holistic_solution_simd_wasm_bin.wasm:0x17ecd
    at SolutionWasm.SolutionWasm$send [as send] (eval at new_ (holistic_solution_simd_wasm_bin.js:9:161523), <anonymous>:9:1)
    at abort (holistic_solution_simd_wasm_bin.js:9:43125)
    at _abort (holistic_solution_simd_wasm_bin.js:9:180749)
    at holistic_solution_simd_wasm_bin.wasm:0x5686f9
    at holistic_solution_simd_wasm_bin.wasm:0x56859e
    at holistic_solution_simd_wasm_bin.wasm:0x568712
    at holistic_solution_simd_wasm_bin.wasm:0x1ce27
    at holistic_solution_simd_wasm_bin.wasm:0x17ecd
    at SolutionWasm.SolutionWasm$send [as send] (eval at new_ (holistic_solution_simd_wasm_bin.js:9:161523), <anonymous>:9:1)
    at oa.h (holistic.js:74:19)
    at ra (holistic.js:14:299)
```

when `refineFaceLandmarks = false`, solution works as expected.

platform: javascript
version: @mediapipe/holistic 0.5.1635989137
browser: chrome 107 on windows 11

**Comment by vladmandic** [comment]
*update*  

this happens only if `enableFaceGeometry = true` is also set  
so its one or the other and @mediapipe/holistic provides no safeguards of setting both to true and crashing.

**Comment by kuaashish** [comment]
Hi @vladmandic,
MediaPipe holistic solution does not have the `enableFaceGeometry` option for configuration. The supported configuration options are listed [here](https://google.github.io/mediapipe/solutions/holistic#javascript-solution-api). However, if you would be kind enough to share the document you are referring to, it would help to analyze the problem in a better way. Thank you!

**Comment by vladmandic** [comment]
see `@mediapipe/holistic/index.d.ts/Options`:

```ts
/**
 * Configurable options for Holistic.
 */
export interface Options {
  enableFaceGeometry?: boolean;
  selfieMode?: boolean;
  modelComplexity?: 0|1|2;
  smoothLandmarks?: boolean;
  enableSegmentation?: boolean;
  smoothSegmentation?: boolean;
  refineFaceLandmarks?: boolean;
  minDetectionConfidence?: number;
  minTrackingConfidence?: number;
}
```

so `enableFaceGeometry` is definitely listed as option for configuration.

**Comment by kuaashish** [comment]
Hi @ivan-grishchenko,
Is the holistic model supports the `enableFaceGeometry` option in JavaScript solution? Thank you!

**Comment by kuaashish** [comment]
@vladmandic,

This is a legacy solution And We will be not able to fix this issue.
