### ISSUE TITLE
mediapipe/holistic incorrect handling of connected models

### ISSUE THREAD

**Issue by vladmandic** [google/mediapipe#3810]
currently `@mediapipe/holistic` solution performs
1. delete what it considers duplicate landmarks from result
2. reconnect different models by artificially drawing a line between them

for example, it deletes `results.poseLandmarks[POSE_LANDMARKS.RIGHT_WRIST]`
and then to make hand "appear" connected to body, it draws a line between:
`[results.poseLandmarks[h.POSE_LANDMARKS.RIGHT_ELBOW], results.rightHandLandmarks[0]`

which looks decent enough on 2D canvas, but when visualized in 3D you can see that pose and hand landmarks each have its own relative z-axis and hand appears in a very wrong place

much better solution is 
- do not delete `results.poseLandmarks[POSE_LANDMARKS.RIGHT_WRIST]` (leave it as-is)
- renormalize z-axis values for all landmarks in `results.rightHandLandmarks` by adding z-axis value from `results.poseLandmarks[POSE_LANDMARKS.RIGHT_WRIST]`  
  (no need to modify x and y values as they are similar enough between models)

same applies to face mesh model - it also needs to be corrected to have position relative to body as currently floats behind it by when visualized in 3d.

platform: this happens in `javascript` solution, although i have not checked other language ports and its likely same applies there
version: @mediapipe/holistic 0.5.1635989137
browser: chrome 107 on windows 11

**Comment by kuaashish** [comment]
Hi @vladmandic,
Could you provide the complete error logs and steps followed to reproduce the issue from our end. Thank you!

**Comment by vladmandic** [comment]
@kuaashish this is not about error logs, its about visually wrong locations of connected models (hand and face when compared to pose).

for example, see screenshot - with input video, 2d overlay and 3d view looking from the side - i've circled the incorrect position of the hand in 3d view.
![image](https://user-images.githubusercontent.com/57876960/199973203-93fa0f9f-0ac9-4771-bac8-c248cdb5bd74.png)

and then look at the second screenshot after i manually correct the z-axis values for hand landmarks by adding z-axis value from pose landmarks wrist.
![image](https://user-images.githubusercontent.com/57876960/199973217-7c1014cc-5486-416d-9729-73ad96653176.png)

**Comment by kuaashish** [comment]
Hi @ivan-grishchenko,
Could you please look into this issue about the incorrect handling of Javascript holistic solution.

**Comment by kuaashish** [comment]
Hello @vladmandic,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by vladmandic** [comment]
it does not answer the question if its fixed?
you're moving users to new solution which is ok to do, but since issue exists, it shouldn't be on user to migrate just to check if issue exists in the new solution and then open new issue for it then.

**Comment by kuaashish** [comment]
@vladmandic,

This is a legacy solution And We will be not able to fix this issue.
