### ISSUE TITLE
MediaPipe Iris Not detecting Focal length from exif data from of certain images in data set

### ISSUE THREAD

**Issue by monkeygobah** [google/mediapipe#3811]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- I am trying to implement MediaPipe Iris in c++ to analyze some eyelids for a project I am working on. I have not made any changes to the code of the desktop example provided by Mediapipe
- MacOS 11.5.1
- Most recent MediaPipe version 0.8.11:
- Bazel version: bazel release 5.2.0
- Only using mediaPipe Iris for this task (pre-made solution- installed according to instructions on site
- Programming Language and version ( e.g. C++, Python):

**Describe the expected behavior:**
Hi everyone! I really hope someone can give me some help with this. I am medical student using MediaPipe for some projects, and I have run into some issues getting the Iris solution to run on all of my photos. All of my photos contain exif data (including focal length and/or 35mm information), but on certain images I get an error that says 

`E20221102 00:45:22.687819 91213312 iris_depth_from_image_desktop.cc:155] Failed to run the graph: Failed to get packet from output stream 'left_iris_depth_mm'.`

I have been trying to solve this problem using two photos from the same camera with the same focal length and exif data, and one works and the other does not. 

When I get the verbose output of the error log from the photo that does not work, there is this line in the error message:

`Focal length in 35 mm should be non-zero to compute focal length in pixels.`

When I check the exif data from command line using exiftool I get this:

` exiftool /Users/geo/Desktop/data/FA/2013_01_14/2013_01_1480799687_2_.JPG | grep -i focal
Focal Length                    : 60.0 mm
Min Focal Length                : 59.9 mm
Max Focal Length                : 59.9 mm
Max Aperture At Min Focal       : 2.0
Max Aperture At Max Focal       : 2.0
Focal Length In 35mm Format     : 90 mm
Focal Length                    : 60.0 mm (35 mm equivalent: 90.0 mm)
Hyperfocal Distance             : 8.17 m`

Some images in my data set run just fine, and they were taken on the same camera with the same specs as the images that don't run OK.  Am I missing something obvious? I am very much a beginner in c++ but I have really been running in circles trying to get this figured out. Any help would be greatly appreciated. This is also my first time posting on here so I apologize if this is in the wrong place or format. Thanks in advance for any help, as well as for the thoughtful discussion that happens on this forum.

The whole error (non verbose) is attached below: I can provide the whole verbose output if necessary.

`
I20221102 12:11:46.161865 24788480 iris_depth_from_image_desktop.cc:135] Initialize the calculator graph.
I20221102 12:11:46.179554 24788480 iris_depth_from_image_desktop.cc:58] Load the image.
I20221102 12:11:46.182642 24788480 iris_depth_from_image_desktop.cc:62] Start running the calculator graph.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
E20221102 12:11:46.283324 24788480 iris_depth_from_image_desktop.cc:155] Failed to run the graph: Failed to get packet from output stream 'left_iris_depth_mm'`

**Comment by kuaashish** [comment]
Hi @monkeygobah,
Could you please share the sample images to investigate further on this issue. Thank you!
