### ISSUE TITLE
Did it support on wechat mini app?

### ISSUE THREAD

**Issue by rainbowechoes** [google/mediapipe#3812]
I can open this demo (https://codepen.io/mediapipe/full/KKgVaPJ) in m1 mac mini and iphone. But when use it in wechat mini app, it report ` 'platform' of undefined`.

Did it not support? how should to fix it ?

**Comment by kuaashish** [comment]
Hi @rainbowechoes,
MediaPipe supports and tested successfully in this platform and browsers as mentioned in the official documentation [here](https://google.github.io/mediapipe/getting_started/javascript.html#supported-plaforms). Please follow the documentation and let us know if you encounter the error in [mentioned](https://google.github.io/mediapipe/getting_started/javascript.html#supported-plaforms) platforms. Thank you!

**Comment by kuaashish** [comment]
Hi @rainbowechoes,
Please go through the [above](https://github.com/google/mediapipe/issues/3812#issuecomment-1303205475) comment and let us know if we can move this issue to close status as it has been resolved. 
Thank you!

**Comment by rainbowechoes** [comment]
> Hi @rainbowechoes, Please go through the [above](https://github.com/google/mediapipe/issues/3812#issuecomment-1303205475) comment and let us know if we can move this issue to close status as it has been resolved. Thank you!

sorry, I reply late. I read this doc before. But when the error occur, how can I know the platform is what in runtime?

**Comment by kuaashish** [comment]
Hi @rainbowechoes,
Currently MediaPipe does not have this feature available and Team has limited resources for new features. We will let you know if there will be any specific update in future on this request. Thank you!

**Comment by rainbowechoes** [comment]
ok, thanks for your reply! I hope MediaPipe can have these feature in future.

**Comment by zbygit** [comment]
in wechatApplet，the pose is empty object，can not use

**Comment by zbygit** [comment]
in wechatApplet，the pose is empty object，can not use?
![image](https://github.com/google/mediapipe/assets/26167970/2df90bef-3e6a-407b-b89f-9ba44eb6a2b7)

![image](https://github.com/google/mediapipe/assets/26167970/8849b6fb-5ea9-455f-bbe2-d35daf0f948f)
