### ISSUE TITLE
Mediapipe Holistic AAR crashes after giving Camera Permissions

### ISSUE THREAD

**Issue by celsodasecond** [google/mediapipe#3816]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):  Ubuntu 20.04 / Android 11
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc 9.4.0
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 2.7.18
- Installed using virtualenv? pip? Conda? (if python): pip
- [MediaPipe version](https://github.com/google/mediapipe/releases): v.0.8.11
- Bazel version: 5.2.2
- Android SDK and NDK versions (if android): SDK and ndk from "setup_android_sdk_and_ndk.sh"
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): YES

**Describe the problem**:
I used shadow's [AAR template](https://github.com/shadow111/mediapipe-holistic-tracking-aar-example) in building my App. It works successfully, until:

1. Changing the .binarypb file and kept shadow111's aar as is - I modified the "holistic_tracking_to_render_data.pbtxt" (Only removed the rendering on some of the parts in the face region) and the render changes did not reflect on my app. 
2. Using a custom AAR as per the instructions in [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) force closes the application after giving camera permissions. There is not much errors that can be seen as it closes the app quickly. The BUILD file looks like this: 

`load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")`

`mediapipe_aar(`
`name = "mediapipe_holistic",`
`calculators = ["//mediapipe/graphs/holistic_tracking:holistic_tracking_gpu_deps",],`
`)`

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
I followed the official steps and instructions from MediaPipe's Android Archive page.

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:
![image](https://user-images.githubusercontent.com/75917932/199742822-cfe5910c-4dec-4b3d-9149-d94a8d7fdfc5.png)
The app crashes on line 190 as per the log:
[log.pdf](https://github.com/google/mediapipe/files/9929972/log.pdf)

**Comment by ylj318** [comment]
i take the same problem

**Comment by MakeMeCookie** [comment]
i take the same problem.
How did you resolve this issue?
