### ISSUE TITLE
Gzip support on Js

### ISSUE THREAD

**Issue by arianatri** [google/mediapipe#3819]
hey guys,
Is Gzip supported on this platform yet?
As I have seen there are many **instantiateStreaming()** (instead of **instantiate()** )function calls.
I get this error when I set gzip ON in Nginx :
`           TypeError: "Response has unsupported MIME type"`
and it's because  instantiateStreaming function is MIME type sensitive
the MIME types for faceMesh files are :
```
           text/javascript ( for js files)
           application/json (for package.json and etc (if exist))
           application/octet-stream ( for data files and hex files)
           application/wasm (for wasm file)
```

**Comment by arianatri** [comment]
@kuaashish 
@sureshdagooglecom 
It will be really appreciated if hopefully, you answer me, please.

**Comment by arianatri** [comment]
https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiateStreaming#:~:text=Note%3A%20For%20this%20to%20work%2C%20.wasm%20files%20should%20be%20returned%20with%20an%20application/wasm%20MIME%20type%20by%20the%20server.

it's on writen mozilla.org too

**Comment by arianatri** [comment]
guys 4 days have past please notice me :'(

**Comment by arianatri** [comment]
guys ?!  anyone?

**Comment by dancingplatypus** [comment]
I'm really confused here.

What platform are you referring to?  Github?  MediaPipe?  WASM? Angular? I have no idea to what context this refers.  What are "facemesh files"?  What does nginx have to do with any of this?

Are you asking if someone out there in the world has a zip library for JavaScript?  I use https://gildas-lormeau.github.io/zip.js/ myself.   Are you asking how instantiateStreaming works with WASM? No idea.

In general, consider StackOverflow for questions like this. e.g.:
https://stackoverflow.com/questions/52239924/webassembly-instantiatestreaming-wrong-mime-type

**Comment by kuaashish** [comment]
Hi @arianatri,
Could you please go through the [above](https://github.com/google/mediapipe/issues/3819#issuecomment-1314118834) and let us know the required inputs. Thank you!
