### ISSUE TITLE
align the person pose

### ISSUE THREAD

**Issue by RCpengnan** [google/mediapipe#3821]
The paper says:"we align the person so that the point between the hips is loceated at the center of the square image passed as the neural network input".
I found that some pose estimation algorithms can't detect the inverted pose at present, but blazepose can detect the inverted algorithm very well. I think this is the advantage of the alignment of the skeleton, but I don't know how to adjust the skeleton in the detection stage, do I need to detect the hips first?If you can't detect the skeleton in a inverted pose, how can you detect the key points in the hips? Since the part of skeleton alignment is not explained in detail in the paper, could you please explain how the skeleton is adjusted in the detection stage? Thank you~

**Comment by kuaashish** [comment]
Hi @RCpengnan,
Is it implemented through the Python, JavaScript or other solutions available in MediaPipe to understand the issue better from our end. Thank you!
