### ISSUE TITLE
Unable to find an identity on the system matching the ones in provision_profile.mobileprovision on macOS13

### ISSUE THREAD

**Issue by WorldObserver-cli** [google/mediapipe#3822]
**System information**
- MacOS13, iOS15:
- Bazel version: 5.3.2
- Xcode version 14.1 and Tulsi versions 0.20
- latest CLI and support Xcode14.1

this is my BUID Content :
licenses(["notice"])  # Apache 2.0

MIN_IOS_VERSION = "11.0"

load(
    "@build_bazel_rules_apple//apple:ios.bzl",
    "ios_application",
)

ios_application(
    name = "DemoApp",
    bundle_id = "com.demo.app.main",
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = ["Info.plist"],
    minimum_os_version = MIN_IOS_VERSION,
        provisioning_profile = "//mediapipe/custom_mediapipe/xxxxx:provisioning_profile.mobileprovision",
    deps = [":DemoAppLibrary"],
)

objc_library(
    name = "DemoAppLibrary",
    srcs = [
        "AppDelegate.mm",
        "MainViewController.mm"
    ],
    hdrs = [
        "AppDelegate.h",
        "MainViewController.h"
    ],
    data = [
        "Base.lproj/LaunchScreen.storyboard",
        "Base.lproj/Main.storyboard",
        "//mediapipe/graphs/edge_detection:mobile_gpu_binary_graph",
    ],
    sdk_frameworks = [
        "UIKit",
        "AVFoundation",
        "CoreGraphics",
        "CoreMedia"
    ],
    deps = [
    "//mediapipe/objc:mediapipe_framework_ios",
    "//mediapipe/objc:mediapipe_input_sources_ios",
    "//mediapipe/objc:mediapipe_layer_renderer",
    "//mediapipe/graphs/edge_detection:mobile_calculators",
    ]
)

As per doc of mediapipe, I created a  simplest iOS project and I also have installed development certificate for bundle id on my mac.

And I put the 'provisioning_profile.mobileprovision' that is downloaded from apple development account into project directory.

When I use bazel script: 

$ bazel  build -c opt --config=ios_arm64 mediapipe/xxxx/xxxx:DemoApp

I got the error: 

`Unable to find an identity on the system matching the ones in provision_profile.mobileprovision.`

I know what this error means. It means the provision_profile.mobileprovision doesn't include my local certificate, but i am very sure my local certifcate exists in  provision_profile.mobileprovision.

And I also create an other iOS project using provision_profile.mobileprovision, it works well.

So why does the mediapipe  ios_application give me this error. everything is ok. I even change to a non-macos13 mac. The mediapipe  ios project works well, it did not give me the error. 

So ios_application has issue in macOS13? 

Does anyone come across the same issue?

**Comment by kuaashish** [comment]
Hi @WorldObserver-cli,
Have you looked at this closed issue #3599 and [#3599(Comment)](https://github.com/google/mediapipe/issues/3599#issuecomment-1216206837). Thank you!

**Comment by WorldObserver-cli** [comment]
> #3599(Comment)

**Comment by kuaashish** [comment]
Hi @WorldObserver-cli,
Could you please let us know if the [above](https://github.com/google/mediapipe/issues/3822#issuecomment-1305338540) comment resolves this issue. Thank you!

**Comment by colinBoyer** [comment]
> Hi @WorldObserver-cli,
> Could you please let us know if the [above](https://github.com/google/mediapipe/issues/3822#issuecomment-1305338540) comment resolves this issue. Thank you!

Thanks for you replay. 

Not resolve for me , I have changed to a non-macos13 Mac. 
And I am very sure that the provsion_profile.mobileprovison and the certificate on my Mac are matched.
So I don't know whether the ios_application rule has issue on macOS13.

**Comment by WorldObserver-cli** [comment]
Thanks for your reply.
 I have changed to other Mac, the solutions that you offer to me don't work.  With same code and certificate,Non-macOS13 works well, but macOS13 doesn't.

**Comment by kuaashish** [comment]
Hi @WorldObserver-cli,
Could you please let us know if this issue #3854 and [#3854(Comment)](https://github.com/google/mediapipe/issues/3854#issuecomment-1314797431) resolves the above error. Thank you!

**Comment by dangkhoasdc** [comment]
I faced the issue recently, this is my fix: https://github.com/google/mediapipe/issues/1596#issuecomment-1297252729

**Comment by wenoptics** [comment]
> I faced the issue recently, this is my fix: [#1596 (comment)](https://github.com/google/mediapipe/issues/1596#issuecomment-1297252729)

Thanks @dangkhoasdc this help solve my issue on XCode 14

**Comment by WorldObserver-cli** [comment]
Pls refer to @dangkhoasdc 's solution. it works well on macOS13 and Xcode14.1.
