### ISSUE TITLE
face mesh & landmark detection: lips pressed together

### ISSUE THREAD

**Issue by monsteradurm** [google/mediapipe#3824]
Hi, I am wondering if anyone else has tried or come up with a solution for the following problem.
The generally wonderful landmark detection, is estimating the lip position incorrectly when lips are "pursed together" see example below with my ugly mug:

<img width="234" alt="image" src="https://user-images.githubusercontent.com/7044684/200199626-402c3e34-59ac-41fa-8298-48567ae97a3b.png">

In this picture the lips are held together tightly so they are not so visible but is estimated as though they are, therefore when i try to measure the distance between top of lip(pt 0) and bottom of lip(pt 17), the difference is largely the same as if they were not pursed together at all.

Does anyone have a workaround for doing this sort of thing or a recommendation?

**Comment by sureshdagooglecom** [comment]
Hi @monsteradurm ,
Could you please confirm us in which platform you are facing this issue like python , javascript ,android etc.

**Comment by monsteradurm** [comment]
Sure thing.

I am using the media pipe for unity plugin from here: https://github.com/homuler/MediaPipeUnityPlugin.

**Comment by monsteradurm** [comment]
any suggestions at all would be wonderful..

**Comment by kuaashish** [comment]
Hello @monsteradurm,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
