### ISSUE TITLE
Using cropped stream video as input to the holistic model

### ISSUE THREAD

**Issue by ainanicolau** [google/mediapipe#3827]
I would like to analyse an embedded video stream (`iframe`) using the holistic model. Is there any way to do this?
I’ve been doing screen capture as an alternative for now, but the frame rate is not great.

Also, I would like to crop the video before it’s used as input, so I'll probably need to do it as a canvas. I've seen some models allow `HTMLImageElement` or `HTMLCanvasElement` as inputs (https://github.com/google/mediapipe/issues/1388). Is this the same case for the holistic model?

**Comment by kuaashish** [comment]
Hi @ainanicolau,
Could you elaborate your query with more complete details to understand the issue better from our end. Thank you!

**Comment by avirads** [comment]
The question as to how to pass a canvas, an image as input to hands.send method, if solved, needs some documentation over here (  https://google.github.io/mediapipe/solutions/hands#javascript-solution-api )on how to achieve this. If, not, needs a solution. Looks like the bot closed the issue automatically but is bound to be asked again by whoever wants to follow that route. Thanks... avinash.
