### ISSUE TITLE
 How to draw a 3D mask on the face?

### ISSUE THREAD

**Issue by ducanh3005** [google/mediapipe#3828]
After I get 468 points ( x, y ,z) from tflite model by Java, how can I draw a mask (use .obj file)on my face, please give me some tutorial make a mask in face by Java 

![image](https://user-images.githubusercontent.com/61770725/200509053-71827247-5956-4c20-a27f-0d6de6939d48.png)

![image](https://user-images.githubusercontent.com/61770725/200509255-20aedc12-64ce-47e9-bb97-0cb4b83bf2e9.png)

**Comment by kuaashish** [comment]
Hi @ducanh3005,
Please refer to this closed issue #3553 for better understanding of your query. Thank you!

**Comment by ducanh3005** [comment]
> Hi @ducanh3005, Please refer to this closed issue #3553 for better understanding of your query. Thank you!

Thanks for your answer. This example depends on the Mediapipe's MainActivity class so is there a way without using them and still be able to draw the mask on the camera? I recognized faces and landmarks, this is the way i did

https://github.com/ducanh3005/face-ml

**Comment by NguyenDaoHuy** [comment]
Hi @ducanh3005, 
I have the same issue as you, have you solved it yet? Can you share it with me? I come from VietNam and I think you are too

**Comment by kostyaby** [comment]
Hey @ducanh3005 and @NguyenDaoHuy,

Did you guys take a look at the Android `faceeffect` example shared in this repository? [Link](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect)

The rendering there is done as a part of a MediaPipe calculator written in C++. If you'd like to do rendering in Java, then I'd suggest you take a look into [jMonkeyEngine](https://jmonkeyengine.org/) or [Filament](https://github.com/google/filament#android), but please note that you'd have to do the Java-level integration between MediaPipe and the chosen rendering library yourself

**Comment by kuaashish** [comment]
Hi @ducanh3005,
Could you please go through the [above](https://github.com/google/mediapipe/issues/3828#issuecomment-1314271607) comment. Thank you!

**Comment by ducanh3005** [comment]
> 

Yes i understand your mean. Thank you for your support!
