### ISSUE TITLE
Calling CalculatorGraph::Cancel() while opening nodes causes deadlock on the next graph run

### ISSUE THREAD

**Issue by kon72** [google/mediapipe#3830]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): macOS 12.6 M1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
- Programming Language and version ( e.g. C++, Python, Java): C++
- [MediaPipe version](https://github.com/google/mediapipe/releases): 9504c5e6a1a88fc19f3a98fd2d16ef6f09160d56
- Bazel version (if compiling from source): 5.2.0
- Solution ( e.g. FaceMesh, Pose, Holistic ):
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
- Xcode & Tulsi version (if issue is related to building for iOS):

**Describe the current behavior:**
Say we have three calculators just passing around side packets (see the reproducible code below!)
`SleepCalculator` will sleep for 1 second and pass its input side packet to `PassThroughCalculator`, which immediately hands over the side packet to `SidePacketToStreamCalculator`.

If I start the graph with some input side packet and cancel its run while `SleepCalculator` is sleeping inside `Open()` function, `SleepCalculator` will send the input side packet to `PassThroughCalculator` after 1 second of sleep, but `PassThroughCalculator` are not going to be open as the cancel request was issued.
Then, when I start the graph again with the same input side packet, it hangs at `poller.Next(&packet)`.

The root cause of this problem is where we cache the output side packets for the next run.
For `PassThroughCalculator` on the second run, `OutputsAreConstant(default_context)` holds true as its `prev_input_side_packets_` are produced on the first run and input side packets are not changed across the runs, whereas its output side packets are not produced/cached yet as the first run was cancelled early and the calculator was never open. Thus, `ResendSidePackets()` could not send output side packets to subsequent nodes and those nodes will indefinitely wait for the input side packets that never arrive.
I guess we need an extra check to not try to resend side packets and force to open calculator when those are not yet populated.
https://github.com/google/mediapipe/blob/9504c5e6a1a88fc19f3a98fd2d16ef6f09160d56/mediapipe/framework/calculator_node.cc#L493-L499

**Describe the expected behavior:**
Opens `PassThroughCalculator` on the second run even if the graph was cancelled early on the first run.

**Standalone code to reproduce the issue:**
```c++
#include "mediapipe/framework/calculator_framework.h"
#include "mediapipe/framework/port/logging.h"
#include "mediapipe/framework/port/parse_text_proto.h"
#include "mediapipe/framework/port/status.h"

namespace mediapipe {

class SleepCalculator : public CalculatorBase {
 public:
  static absl::Status GetContract(CalculatorContract* cc) {
    cc->InputSidePackets().Index(0).Set<std::string>();
    cc->OutputSidePackets().Index(0).SetSameAs(
        &cc->InputSidePackets().Index(0));
    return absl::OkStatus();
  }
  absl::Status Open(CalculatorContext* cc) final {
    absl::SleepFor(absl::Milliseconds(1000));
    cc->OutputSidePackets().Index(0).Set(cc->InputSidePackets().Index(0));
    return absl::OkStatus();
  }
  absl::Status Process(CalculatorContext* cc) final { return absl::OkStatus(); }
};
REGISTER_CALCULATOR(SleepCalculator);

absl::Status Run() {
  CalculatorGraphConfig config =
      ParseTextProtoOrDie<CalculatorGraphConfig>(R"pb(
        node {
          calculator: "SleepCalculator"
          input_side_packet: "in"
          output_side_packet: "out1"
        }
        node {
          calculator: "PassThroughCalculator"
          input_side_packet: "out1"
          output_side_packet: "out2"
        }
        node {
          calculator: "SidePacketToStreamCalculator"
          input_side_packet: "out2"
          output_stream: "AT_ZERO:out"
        }
      )pb");

  CalculatorGraph graph;
  MP_RETURN_IF_ERROR(graph.Initialize(config));
  ASSIGN_OR_RETURN(OutputStreamPoller poller,
                   graph.AddOutputStreamPoller("out"));

  std::map<std::string, mediapipe::Packet> input_side_packets = {
      {"in", MakePacket<std::string>("Hello World!")}};

  MP_RETURN_IF_ERROR(graph.StartRun(input_side_packets));
  absl::SleepFor(absl::Milliseconds(500));
  // Cancel graph while SleepCalculator is sleeping in Open().
  graph.Cancel();
  RET_CHECK_EQ(graph.WaitUntilDone().code(), absl::StatusCode::kCancelled);

  MP_RETURN_IF_ERROR(graph.StartRun(input_side_packets));

  mediapipe::Packet packet;
  // Deadlock here as SidePacketToStreamCalculator is waiting for its input
  // side packet which never arrives.
  while (poller.Next(&packet)) {
    LOG(INFO) << packet.Get<std::string>();
  }

  MP_RETURN_IF_ERROR(graph.WaitUntilDone());

  return absl::OkStatus();
}
}  // namespace mediapipe

int main(int argc, char** argv) {
  FLAGS_colorlogtostderr = true;
  google::InitGoogleLogging(argv[0]);
  auto status = mediapipe::Run();
  if (!status.ok()) {
    LOG(FATAL) << status.ToString();
  }
  return 0;
}
```

**Other info / Complete Logs :**

**Comment by kinsei0916** [comment]
Drop-in patch for this

```diff
diff --git a/mediapipe/framework/calculator_node.cc b/mediapipe/framework/calculator_node.cc
index f6a1c7db..9b5d1d8a 100644
--- a/mediapipe/framework/calculator_node.cc
+++ b/mediapipe/framework/calculator_node.cc
@@ -455,10 +455,9 @@ absl::Status ResendSidePackets(CalculatorContext* cc) {
   auto& outs = cc->OutputSidePackets();
   for (CollectionItemId id = outs.BeginId(); id < outs.EndId(); ++id) {
     Packet packet = GetPacket(outs.Get(id));
-    if (!packet.IsEmpty()) {
-      // OutputSidePacket::Set re-announces the side-packet to its mirrors.
-      outs.Get(id).Set(packet);
-    }
+    RET_CHECK(!packet.IsEmpty());
+    // OutputSidePacket::Set re-announces the side-packet to its mirrors.
+    outs.Get(id).Set(packet);
   }
   return absl::OkStatus();
 }
@@ -614,6 +613,8 @@ absl::Status CalculatorNode::CloseNode(const absl::Status& graph_status,
     CloseOutputStreams(outputs);
   }
 
+  input_side_packet_handler_.CacheInputSidePackets();
+
   {
     absl::MutexLock status_lock(&status_mutex_);
     status_ = kStateClosed;
diff --git a/mediapipe/framework/input_side_packet_handler.cc b/mediapipe/framework/input_side_packet_handler.cc
index 9b01cc31..a3355ba4 100644
--- a/mediapipe/framework/input_side_packet_handler.cc
+++ b/mediapipe/framework/input_side_packet_handler.cc
@@ -27,7 +27,6 @@ absl::Status InputSidePacketHandler::PrepareForRun(
     std::function<void()> input_side_packets_ready_callback,
     std::function<void(absl::Status)> error_callback) {
   int missing_input_side_packet_count;
-  prev_input_side_packets_ = std::move(input_side_packets_);
   ASSIGN_OR_RETURN(
       input_side_packets_,
       tool::FillPacketSet(*input_side_packet_types, all_side_packets,
@@ -42,6 +41,10 @@ absl::Status InputSidePacketHandler::PrepareForRun(
   return absl::OkStatus();
 }
 
+void InputSidePacketHandler::CacheInputSidePackets() {
+  prev_input_side_packets_ = std::move(input_side_packets_);
+}
+
 bool InputSidePacketHandler::InputSidePacketsChanged() {
   return prev_input_side_packets_ == nullptr ||
          input_side_packets_ == nullptr ||
diff --git a/mediapipe/framework/input_side_packet_handler.h b/mediapipe/framework/input_side_packet_handler.h
index c0a3249a..bcc36f1f 100644
--- a/mediapipe/framework/input_side_packet_handler.h
+++ b/mediapipe/framework/input_side_packet_handler.h
@@ -52,6 +52,8 @@ class InputSidePacketHandler {
 
   const PacketSet& InputSidePackets() const { return *input_side_packets_; }
 
+  void CacheInputSidePackets();
+
   // Returns true if the set of input-side-packets has changed since the
   // previous run.
   bool InputSidePacketsChanged();
```

**Comment by kinsei0916** [comment]
Gently ping @kuaashish

Was this behavior confirmed as a legit bug? If so, do you have any plans to ship an official patch for this to OSS?

**Comment by kuaashish** [comment]
Hello @kon72,

We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you!!

**Comment by kon72** [comment]
Hello @kuaashish,

I'm happy to hear about new MediaPipe solutions, however, I'm currently working on creating a C++ Text-to-Speech engine backed by MediaPipe. Since the TTS task is not listed in [the examples](https://developers.google.com/mediapipe/solutions/examples), I'm building MediaPipe from source code and calling MediaPipe C++ API directly to build and run my graph.

I'm facing a deadlock when I repeatedly start and cancel the graph as it's a common use case for my application. I mentioned this behavior earlier with a minimum example, but more specifically, I have three calculators `LocalFileContentsCalculator`, `TfLiteModelCalculator`, and `InferenceCalculator` in a graph for my TTS task (with each corresponding to the calculator in the reproduction code above: `SleepCalculator`, `PassThroughCalculator`, `SidePacketToStreamCalculator`)

When one cancels the graph while `LocalFileContentsCalculator` is loading model binary from a file and then starts the graph again, this calculator is considered as "no need to be executed again" and MediaPipe tries to resend the model binary that should've been cached beforehand, but actually it is NOT cached.

```pbtxt
...

node {
  calculator: "LocalFileContentsCalculator"
  input_side_packet: "FILE_PATH:model_path"
  output_side_packet: "CONTENTS:model_blob"
}

node {
  calculator: "TfLiteModelCalculator"
  input_side_packet: "MODEL_BLOB:model_blob"
  output_side_packet: "MODEL:model"
}

node {
  calculator: "InferenceCalculator"
  input_stream: "TENSORS:tensor_in"
  output_stream: "TENSORS:tensor_out"
  input_side_packet: "OP_RESOLVER:opresolver"
  input_side_packet: "MODEL:model"
}

...
```

Maybe I'm doing wrong here but I managed to circumvent this issue with [this patch](https://github.com/google/mediapipe/issues/3830#issuecomment-1312400139), by changing the timing that caching happens. Would be good if it will be fixed upstream...

Thank you!
