### ISSUE TITLE
why is there such a strange import in the python api in the mediapipe.solutions module

### ISSUE THREAD

**Issue by mar0us** [google/mediapipe#3833]
why does the python api in the mediapipe.solutions module import like this "import mediapipe.python.solutions.drawing_styles", and not like this "from mediapipe.python.solutions import drawing_styles", what is the reason for this? this also disables type hints in the same vs code, and does not allow you to go to the definition of the function

**Comment by kuaashish** [comment]
Hello @mar0us, 
It is possible to import like `from mediapipe.python.solutions import holistic, drawing_styles, drawing_utils` and intellisense also works along with the definition of function in VSCode. Would you please let us know which OS, python version and mediapipe version are you using? Thank you!
