### ISSUE TITLE
2d pose mapping

### ISSUE THREAD

**Issue by ashisharorambdev** [google/mediapipe#3834]
Hi,
I'm trying to integrate @mediapipe/pose in my react project for 2d mapping with COCO key points.
but as I see I can only use @mediapipe/pose for 3d mapping.
so is there any way I can use it for 2d mapping?

**Comment by kuaashish** [comment]
Hi @ashisharorambdev,
Could you elaborate your query with more details to understand the issue better from our end. Thank you!

**Comment by ashisharorambdev** [comment]
hi @kuaashish sorry for the delayed response
I have some COCO key points for the 2d model which I want to map using @mediapipe/pose but from what I saw in the examples I can only map the 3d model using this library.
So is there any way I can use this library of 2d mapping?
below I have listed 17 key points I want to map

0: 'nose',
1: 'left_eye',
2: 'right_eye',
3: 'left_ear',
4: 'right_ear',
5: 'left_shoulder',
6: 'right_shoulder',
7: 'left_elbow',
8: 'right_elbow',
9: 'left_wrist',
10: 'right_wrist',
11: 'left_hip',
12: 'right_hip',
13: 'left_knee',
14: 'right_knee',
15: 'left_ankle',
16: 'right_ankle'

**Comment by ashisharorambdev** [comment]
hi, @kuaashish any update regarding my query?

**Comment by kuaashish** [comment]
Hi @ashisharorambdev,
Can you please let us know the following:
- What does the mean by "mapping"?  Does mean "rendering"?  
- We believe you would like to convert MediaPipe landmarks to/from COCO key-points?

Mediapipe does include several 2d models and 2d renderers.  2d landmarks are common inside MediaPipe. Thank you!
