### ISSUE TITLE
Unable to compile Iris tracking in Docker

### ISSUE THREAD

**Issue by plashchynski** [google/mediapipe#3835]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):
Docker version 20.10.17, build 100c701 on Amazon Linux 2
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):
g++ (Ubuntu 8.4.0-3ubuntu2) 8.4.0
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
C++14
- [MediaPipe version](https://github.com/google/mediapipe/releases):
[v0.8.11](https://github.com/google/mediapipe/tree/v0.8.11) but reproduced on the master as well
- Bazel version:
5.2.0
- OpenCV version (if running on desktop):
4.2.0

**Describe the problem**:

The command to compile ```examples/desktop/iris_tracking:iris_tracking_cpu_video_input```

```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/iris_tracking:iris_tracking_cpu_video_input
```

result in the error:

```
In file included from ./mediapipe/framework/formats/image_frame_opencv.h:20,
                 from mediapipe/calculators/video/opencv_video_encoder_calculator.cc:25:
./mediapipe/framework/port/opencv_core_inc.h:18:10: fatal error: opencv2/core/version.hpp: No such file or directory
 #include <opencv2/core/version.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/iris_tracking:iris_tracking_cpu_video_input failed to build
```

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

```

GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/iris_tracking:iris_tracking_cpu_video_input
```

**Complete Logs:**

[complete console log](https://gist.github.com/plashchynski/a0786f4b40196aff4d916a1fbd5010f4)

**Comment by plashchynski** [comment]
I've tried to add ```--copt -I/usr/include/opencv4/ ```:

```bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --copt -I/usr/include/opencv4/ mediapipe/examples/desktop/iris_tracking:iris_tracking_cpu_video_input```

The command results in another error:

```
In file included from mediapipe/calculators/video/opencv_video_decoder_calculator.cc:23:
./mediapipe/framework/port/opencv_video_inc.h:88:10: fatal error: opencv2/optflow.hpp: No such file or directory
 #include <opencv2/optflow.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/iris_tracking:iris_tracking_cpu_video_input failed to build
```

[full log](https://gist.github.com/plashchynski/1dd9922c238a9961d66854d65dcdaa14)

**Comment by plashchynski** [comment]
The problem was solved by installing an additional package ```libopencv-contrib-dev``` into a container and by adding a ```--copt -I/usr/include/opencv4/``` flag for ```bazel build```.

**Comment by kuaashish** [comment]
Hi @plashchynski,
Thank you for sharing your request. we will forward the request to the appropriate team to fix the issue soon. Thank you!

**Comment by kuaashish** [comment]
Hello @plashchynski,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
