### ISSUE TITLE
Is there any way to compile and run youtube8m anymore? the install guides are clearly not tested,....

### ISSUE THREAD

**Issue by LDeillon** [google/mediapipe#3836]
I have tried every platform you claim to support. I can always compile and run the hello world example but the youtube8m will never pass the Bazel build step 5 in any situation, not even in the docker you provide.
 Can you test and fix your install guide, fix the docker or provide a collab that will run the youtube8m? Having an untested "install guide" only makes people lose time,...............................................

tried every version of mediapipe available with every version of tensorflow.

on windows and Dockers: The Bazel Build file in youtube8m_extractor is not recognized or has an issue that you need to fix.

on Linux: If you are lucky enough to be able to compile the bazel crap you will get a DecodeJPEG error when trying to run the code, none of the solutions proposed on the different forums works with the current version of dependencies anymore.

**Comment by kuaashish** [comment]
Hi @LDeillon,
Thanks for reporting this bug. Could you please provide complete error logs which have been faced while installing in the above platforms to investigate further. Thank you!
