### ISSUE TITLE
 Is it possible to get the poscentermatrix from the uniform scaling, orientation from the KNIFT solution

### ISSUE THREAD

**Issue by dandingol03** [google/mediapipe#3839]
Describe the problem:
HI, there is some obstacle i met when i try to get the pose-center-matrix from the KNIFT solution.First of all, i want to recognize some feature plane. So i choose the KNIFT solution which can compute the uniform scaling and orientation for me. However, the most import pose-center-matrix is lost, i need that matrix to convert the image-space coordinate from 2d to 3d. Because i need to draw some effect on that plane in the virtual 3d space. I need some advice,thanks.

**Comment by kuaashish** [comment]
Hi @dandingol03,
Could you please elaborate your query with complete details to understand better from our end. Thank you!

**Comment by dandingol03** [comment]
@kuaashish yes. I want to find some specific solution which can help me to recognize 2d feature plane and put some virtual 3d asset on that plane. Moreover, this virtual 3d asset still stay at the same place after i move away the phone camera

**Comment by dandingol03** [comment]
> Hi @dandingol03, Could you please elaborate your query with complete details to understand better from our end. Thank you!

it is something like slam task. I am not fimiliar with slam. But what i need is the same with the instance-placement function which arcore provide

**Comment by ayushgdev** [comment]
Hello @dandingol03 
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
