### ISSUE TITLE
About calculator issues

### ISSUE THREAD

**Issue by mapleyuan** [google/mediapipe#384]
I add my calculator to pbtxt file, and I got this error, what's that mean? thx

FaceDetectionCpuApp[1775:860250] failed to send packet: Error Domain=GoogleUtilStatusErrorDomain Code=13 "" UserInfo={NSLocalizedDescription=, GUSGoogleUtilStatusErrorKey=<GUSUtilStatusWrapper: 0x2832c8b30; status = >}

**Comment by eknight7** [comment]
Can you explain a bit more about what you did to modify the FaceDetectionCpuApp? Did you modify the BUILD file appropriately for the new calculator's dependencies?

**Comment by eknight7** [comment]
Also this is on iOS right?

**Comment by mapleyuan** [comment]
@eknight7  yep, it's on iOS.
1.  I create my calculator and extend CalculatorBase, like the official demo PacketClonerCalculator
2. add it to the BUILD file
3. and I got this error
2020-01-10 16:42:36.457722+0800 FaceDetectionCpuApp[1928:916628] failed to send packet: Error Domain=GoogleUtilStatusErrorDomain Code=13 "" UserInfo={NSLocalizedDescription=, GUSGoogleUtilStatusErrorKey=<GUSUtilStatusWrapper: 0x283e5ddd0; status = >}

cc_library(
    name = "packet_cloner_calculator",
    srcs = ["packet_cloner_calculator.cc"],
    visibility = ["//visibility:public"],
    deps = [
        ":util",
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/util:resource_util",
        "//mediapipe/framework/stream_handler:fixed_size_input_stream_handler",
        "//mediapipe/framework/port:ret_check",
    ],
    alwayslink = 1,
)

PacketClonerCalculator

// For every packet that appears in B, outputs the most recent packet from each
// of the A_i on a separate stream.

#include <vector>

#include "absl/strings/str_cat.h"
#include "mediapipe/framework/calculator_framework.h"

namespace mediapipe {

// For every packet received on the last stream, output the latest packet
// obtained on all other streams. Therefore, if the last stream outputs at a
// higher rate than the others, this effectively clones the packets from the
// other streams to match the last.
//
// Example config:
// node {
//   calculator: "PacketClonerCalculator"
//   input_stream: "first_base_signal"
//   input_stream: "second_base_signal"
//   input_stream: "tick_signal"
//   output_stream: "cloned_first_base_signal"
//   output_stream: "cloned_second_base_signal"
// }
//
class PacketClonerCalculator : public CalculatorBase {
 public:
  static ::mediapipe::Status GetContract(CalculatorContract* cc) {
    const int tick_signal_index = cc->Inputs().NumEntries() - 1;
    // cc->Inputs().NumEntries() returns the number of input streams
    // for the PacketClonerCalculator
    for (int i = 0; i < tick_signal_index; ++i) {
      cc->Inputs().Index(i).SetAny();
      // cc->Inputs().Index(i) returns the input stream pointer by index
      cc->Outputs().Index(i).SetSameAs(&cc->Inputs().Index(i));
    }
    cc->Inputs().Index(tick_signal_index).SetAny();
    return ::mediapipe::OkStatus();
  }

  ::mediapipe::Status Open(CalculatorContext* cc) final {
    tick_signal_index_ = cc->Inputs().NumEntries() - 1;
    current_.resize(tick_signal_index_);
    // Pass along the header for each stream if present.
    for (int i = 0; i < tick_signal_index_; ++i) {
      if (!cc->Inputs().Index(i).Header().IsEmpty()) {
        cc->Outputs().Index(i).SetHeader(cc->Inputs().Index(i).Header());
        // Sets the output stream of index i header to be the same as
        // the header for the input stream of index i
      }
    }
    return ::mediapipe::OkStatus();
  }

  ::mediapipe::Status Process(CalculatorContext* cc) final {
    // Store input signals.
    for (int i = 0; i < tick_signal_index_; ++i) {
      if (!cc->Inputs().Index(i).Value().IsEmpty()) {
        current_[i] = cc->Inputs().Index(i).Value();
      }
    }

    // Output if the tick signal is non-empty.
    if (!cc->Inputs().Index(tick_signal_index_).Value().IsEmpty()) {
      for (int i = 0; i < tick_signal_index_; ++i) {
        if (!current_[i].IsEmpty()) {
          cc->Outputs().Index(i).AddPacket(
              current_[i].At(cc->InputTimestamp()));
          // Add a packet to output stream of index i a packet from inputstream i
          // with timestamp common to all present inputs
          //
        } else {
          cc->Outputs().Index(i).SetNextTimestampBound(
              cc->InputTimestamp().NextAllowedInStream());
          // if current_[i], 1 packet buffer for input stream i is empty, we will set
          // next allowed timestamp for input stream i to be current timestamp + 1
        }
      }
    }
    return ::mediapipe::OkStatus();
  }

 private:
  std::vector<Packet> current_;
  int tick_signal_index_;
};

REGISTER_CALCULATOR(PacketClonerCalculator);
}  // namespace mediapipe

**Comment by eknight7** [comment]
Does your app depend on `PacketClonerCalculator`? Did you add it as a dependency for your app?

**Comment by mapleyuan** [comment]
@eknight7 
![image](https://user-images.githubusercontent.com/6057711/72230324-856a1800-35ef-11ea-925b-2d9dc025b9ab.png)
