### ISSUE TITLE
Unable to connect to the slack group. 

### ISSUE THREAD

**Issue by tikitong** [google/mediapipe#3841]
Hi, I have a question about the use of the `mediapipe.framework.formats.detection_pb2.Detection` class, I asked on StackOverflow : https://stackoverflow.com/questions/74377760/how-to-sort-the-result-of-face-detection-process

As I have no answer I would like to ask the question on Slack but I can't connect to the group. Is it possible for the MediaPipe Team workspace administrator to invite me? Many thanks.

**Comment by kuaashish** [comment]
Hi @tikitong,
Could you join through [this](https://join.slack.com/t/mediapipe/shared_invite/zt-1jqmrzg34-waJBaqdLt7_228BUOgxPwg) invitation and please let us know if you are part of the official mediapipe slack community. Thank you!

**Comment by tikitong** [comment]
@kuaashish Thanks a lot, I get in! I don't know if it's official now but I confirmed I have joined the group.
