### ISSUE TITLE
error building handtracking gpu example with bazel

### ISSUE THREAD

**Issue by Mohamedben10** [google/mediapipe#3843]
hello mediapipe community...
im using the following command line to build handtrackinggpu example provided by mediapipe but always get build error i tried almost every solution by with no positive result
command line:
sudo bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

thank you very mush for helping me 

 
error:
DEBUG: /root/.cache/bazel/_bazel_root/5d145bfc5dc6c9914048ebba04ab0b40/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
WARNING: /home/med/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /home/med/mediapipe/mediapipe/framework/tool/BUILD:185:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/med/mediapipe/mediapipe/framework/BUILD:102:24: Generating JavaLite proto_library //mediapipe/framework:packet_factory_proto failed: (Exit 1): protoc failed: error executing command bazel-out/k8-opt-exec-50AE0418/bin/external/com_google_protobuf/protoc '--java_out=lite:bazel-out/android-arm64-v8a-opt/bin/mediapipe/framework/packet_factory_proto-lite-src.jar' ... (remaining 5 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
mediapipe/framework/packet_factory.proto: warning: directory does not exist.
Could not make proto path relative: mediapipe/framework/packet_factory.proto: No such file or directory
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.100s, Critical Path: 0.01s
INFO: 10 processes: 10 internal.
FAILED: Build did NOT complete successfully

**System information** (Please provide as much relevant information as possible)
- Linux Ubuntu 22.04 LTS
- gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
------openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)

**Comment by kuaashish** [comment]
Hi @Mohamedben10,
Could you confirm that you have built the mediapipe as mentioned in the [documentation](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu) and able to run the hello_world [example](https://google.github.io/mediapipe/getting_started/hello_world_android.html) successfully. Thank you!
