### ISSUE TITLE
Indexing Issue

### ISSUE THREAD

**Issue by DestroytheCity** [google/mediapipe#3844]
Our team is using mediapipe for 3D pose estimation in a hallway using 4 cameras. We are encountering an issue where the skeleton from one camera seems to be placed on another camera (ie skeleton from camera 1 is placed over the view of camera 3). Has anyone encountered a similar problem/have a solution?

**Comment by kuaashish** [comment]
Hi @DestroytheCity,
Is it implemented through Python, Javascript or other solutions available in the MediaPipe. Could you let us know the complete steps followed and sample images to understand the issue better from our end. Thank you!

**Comment by DestroytheCity** [comment]
Hi @kuaashish! We are running python on Ubuntu. Attached is a sample image 
<img width="441" alt="Screen Shot 2022-11-11 at 11 13 01 AM" src="https://user-images.githubusercontent.com/114196168/201413750-4fdc3060-9f06-4809-8d46-0f4dd2fb54b9.png">

**Comment by kuaashish** [comment]
Hi @DestroytheCity,
Could you please confirm that you are still looking for resolution or the issue has been resolved. Thank you!
