### ISSUE TITLE
How can I tell if a hand landmark point is self-occluded?

### ISSUE THREAD

**Issue by mpuu00001** [google/mediapipe#3847]
Hi! 

I want to use Mediapipe Hands to find self-occluded points.
For example, when we are performing sign language. There are some hand joints that are occluded by a certain part of the hands. My goal is to find those points that are occluded by hands that are holding nothing. 

Note: some images contain both hands of a person, and all images include only one person. Therefore, it is possible that some points are occluded by the hand itself or another hand of the person. 

![Screenshot 2022-11-11 at 17 49 13](https://user-images.githubusercontent.com/86390633/201314171-6ef3df79-9a17-4793-80ec-90b0c5e7f901.png)

From the above gesture, the points labelled as 5, 9, and 13 should be outputted as self-occluded points. 

I would appreciate any ideas you have. Thank you in advance!

**Comment by kuaashish** [comment]
Hi @mpuu00001,
Is it implemented through Python, Javascript or other solutions available? Could you please elaborate your query with complete details. Thank you!

**Comment by mpuu00001** [comment]
Hi @kuaashish, 
I would like to implement it through Python. My original idea is to compute the Euclidean distances between each point and set a threshold to determine if they overlapped with each other. However, there are many flaws in this idea. For example, this method cannot tell whether two points are just too close to each other or which point is the occluded point or which point is the one that causes the occlusion of another point.

**Comment by kuaashish** [comment]
Hi @bazarevsky,
Is it possible to get it done using some sort of algorithm? seems like a new model will need to be trained which is aware of occlusion.

**Comment by kuaashish** [comment]
Hello @mpuu00001,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
