### ISSUE TITLE
Building mediapipe with custom OpenCV path

### ISSUE THREAD

**Issue by siquus** [google/mediapipe#3848]
I am using Archlinux with OpenCV in /usr/local/include, /usr/local/lib. I haven't found documentation on how to change the OpenCV default directories used by mediapipe. The build error says that the <opencv2/...> include files can't be found. The solutions I found online, like adding 

`copts = ["-I/usr/local/include/opencv4/"]`

to opencv_linux.BUILD do not work. Using `--define=OPENCV=source` fails because some enums are not defined.

Could you please add some documentation on how to set the OpenCV path manually? Thanks!

**Comment by serrabii** [comment]
Did you check https://google.github.io/mediapipe/getting_started/install.html, there are multiple options to setting up OpenCV.

**Comment by siquus** [comment]
Ah..sorry about that. For what it's worth, here are the steps necessary to build mediapipe on Archlinux:

### OpenCV

1. Some special opencv_contrib modules are required which are not built by default by OpenCV. Following the commands from mediapipe/setup_opencv.sh works. I used OpenCV's default "4.x" branches for both repositories rather than the "3.4" from the file.
2. In [mediapipe's install instructions](https://google.github.io/mediapipe/getting_started/install.html), scroll down to "OpenCV 4 setup" and change mediapipe/WORKSPACE and mediapipe/thirdparty/opencv_linux.BUILD accordingly.

### Bazel 

1. change mediapipe/.bazelversion to contain the version your system is using (I used 5.3.2)
3. Bazel has [known issues with openjdk17](https://github.com/bazelbuild/bazel/issues/15831). The workaround mentioned in that issue, adding `--host_jvm_args="--add-opens=java.base/java.lang=ALL-UNNAMED"`, works for me.

### Compiling
`bazel --host_jvm_args="--add-opens=java.base/java.lang=ALL-UNNAMED" build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu`
