### ISSUE TITLE
python 3.11 can't install mediapipe

### ISSUE THREAD

**Issue by mustafa-ozlu** [google/mediapipe#3849]
i use python 3.11
i want to install mediapipe but can't install.
i was try 
pip install mediapipe
python -m pip install mediapipe
pip install mediapipe.whl
but always give me a error
screenshot attached.

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 10
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.11
- Installed using virtualenv? pip? Conda? (if python): pip
- [MediaPipe version](https://github.com/google/mediapipe/releases):  mediapipe 0.8.11

- OpenCV version (if running on desktop): 4.6.0.66

![ss](https://user-images.githubusercontent.com/26308636/201327973-3d72ae2d-7fcd-480e-9e3f-29cad83b312e.PNG)

**Comment by kuaashish** [comment]
Hi @mustafa-ozlu,
Python 3.11 is not supported by Mediapipe yet. Please refer to [this](https://github.com/google/mediapipe/releases/tag/v0.8.9) document and use Python 3.7 to 3.9. Attaching the relevant thread #1325 for better understanding. Thank you!

**Comment by kuaashish** [comment]
Hi @mustafa-ozlu,
Could you please update the status of the above issue. Thank you!

**Comment by HELLO1234231** [comment]
It doesnt work and it has been half a year somebody help me PLZZZZZZZZZZZZZZZZZZZ!!!!!!!

**Comment by aryansri-19** [comment]
> It doesnt work and it has been half a year somebody help me PLZZZZZZZZZZZZZZZZZZZ!!!!!!!

just use python 3.8 (env) interpreter

**Comment by Weq511762338** [comment]
If you are using Windows, according to the [Troubleshooting page](https://developers.google.com/mediapipe/framework/getting_started/troubleshooting) :

> after running pip install mediapipe usually indicates that there is no qualified MediaPipe Python for your system. Please note that MediaPipe Python PyPI officially supports the 64-bit version of Python 3.7 to 3.10 on the following OS:
x86_64 Linux
x86_64 macOS 10.15+
amd64 Windows
If the OS is currently supported and you still see this error, please make sure that both the Python and pip binary are for Python **3.7 to 3.10**

I just installed **3.10 64-bit** version and worked

**Comment by Muhammad-Anees99** [comment]
PS D:\Semester4\CP_II\PBL> pip install mediapipe    
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
it shows error for python 3.11!!!!!!!!!!!!!!!!!

**Comment by g-o-o-g-l-e** [comment]
I need help on #58

**Comment by g-o-o-g-l-e** [comment]
I need help on #59

**Comment by g-o-o-g-l-e** [comment]
#57

**Comment by g-o-o-g-l-e** [comment]
I am using py 3.12 and 64-bit on pycharm

**Comment by aryansri-19** [comment]
> I am using py 3.12 and 64-bit on pycharm

supported python versions: 3.8 to 3.11
Refer https://developers.google.com/mediapipe/solutions/setup_python

**Comment by g-o-o-g-l-e** [comment]
> > I am using py 3.12 and 64-bit on pycharm
> 
> supported python versions: 3.8 to 3.11 Refer https://developers.google.com/mediapipe/solutions/setup_python

Please tell me if there is another way
