### ISSUE TITLE
Python for Android Wrong Build Version

### ISSUE THREAD

**Issue by mrks89** [google/mediapipe#3852]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):
Linux Ubuntu 22.04.1 LTS
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):
gcc 11.3.0
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
-Python 3.10.6
- Installed using virtualenv? pip? Conda? (if python):
-Conda
- [MediaPipe version](https://github.com/google/mediapipe/releases):
0.8.11 (in conda environment, but I am building with buildozer)
- Android SDK and NDK versions (if android):
SDK = 32 and 33, NDK = 20.1.5948944 and 25.1.8937393
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):
4.6.0.66 (in conda environment)

**Describe the problem**:

I successfully build a python kivy app for android on my Ubuntu system which makes use of opencv and mediapipe. However, when runnning the app I get the following error in logcat:

`ImportError: dlopen failed: "/data/data/org.test.myapp/files/app/_python_bundle/site-packages/mediapipe/python/_framework_bindings.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)`

What I infer from this log is, that mediapipe was build for x86_64 but for the android app it would use the aarch64 build. I tried creating my own p4a recipe but when looking up the pypi builds, there is no aarch64 version.

Further research lead me to similar questions which are all unanswered. Any idea how to solve this or work around it?

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

buildozer android debug deploy run

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

`ImportError: dlopen failed: "/data/data/org.test.myapp/files/app/_python_bundle/site-packages/mediapipe/python/_framework_bindings.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)`

**Comment by kuaashish** [comment]
Hi @mrks89,
Could you please elaborate your query with complete details w.r.t use case of the issue. Thank you

**Comment by mrks89** [comment]
Hi @kuaashish 
the use case is building an android and ios app using mediapipe and python. Therefore I implemented a kivy app which is build using buildozer. In the build definition I added numpy, opencv and mediapipe so it properly includes these libraries. Which it actually does, so there are nor error during the build. However, the app screen pops up and closes againg. If analyzed with logcat, I get the error mentioned in my issue description. Any other details necessary? I think you have everything I can provide.

**Comment by kuaashish** [comment]
Hi @mrks89,
This looks like an issue with Kivy (problem with build configuration()). You need to follow up with them. We do not directly support this framework. the error indicates a missing shared-object lib for ARM.

**Comment by zeroche72** [comment]
Has this problem been resolved?

**Comment by akazadengr** [comment]
I am also facing the same issue while building android apps using opencv and mediapipe. Could you please give me exact solution to overcome the issue. 

ImportError: dlopen failed: "/data/data/org.test.myapp/files/app/_python_bundle/site-packages/mediapipe/python/_framework_bindings.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)

**Comment by Codewithkaint** [comment]
Someone able to solve the problem??

**Comment by commando22** [comment]
I am also facing the same issue. I have been looking for resolutions for the last 1 week but haven't found one yet.

**Comment by lugozil** [comment]
Me pasa el mismo problema, la aplicación se me cierra al abrirla en el tlfn. Alguien a encontrado la solución ?

**Comment by guysoft** [comment]
Hey, I am getting this issue too.

A solution does require a way to build mediapipe for arm64 linux, with that it would be possible to make a python-for-android recipe. However, I am not sure if the rpi build instructions, the only ones I see for arm on linux, are good enough for this. They use docker and might have some pre-packaged dependencies that would not play well with android.

Is there a way to build for arm64 linux without docker?
