### ISSUE TITLE
GlContextOptions ignored when using option_value

### ISSUE THREAD

**Issue by ghost** [google/mediapipe#3855]
Hi,

I have tried to set a different gpu context using the option:

```
[mediapipe.GlContextOptions.ext] {
   gl_context_name: "my_ctx"
 }
```

However, i noticed that it gets ignored when the node has `option_value` fields.

This is blocking because I can't separate gpu contexts of subgraphs that needs to be reused with different options. 
It is also unclear to me how graph options are passed to a node that is using multiple option types. 

**Steps to reproduce** 

1. Add the `gl_context_name` option to any of the GPU nodes (`ImageToTensorCalculator`, `TensorsToDetectionsCalculator`, `InferenceCalculator`, `AnnotationOverlayCalculator`) of the graph config `mediapipe/modules/face_detection/face_detection.pbtxt`
2. Log the name of the chosen gpu context for each node in `gpu_shared_data_internal.cc`:
```
  const auto& options =
      node->GetCalculatorState().Options<mediapipe::GlContextOptions>();
  if (options.has_gl_context_name() && !options.gl_context_name().empty()) {
    context_key = absl::StrCat("user:", options.gl_context_name());
  } else if (gets_own_context) {
    context_key = absl::StrCat("auto:", node_type);
  } else if (kGlCalculatorShareContext) {
    context_key = SharedContextKey();
  } else {
    context_key = absl::StrCat("auto:", node_id);
  }
  LOG(INFO) << "Node " << node_id << " will use context " << context_key;
```
3. Install the facedetectiongpu example app on android
```
bazel mobile-install -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu
```

**Comment by serrabii** [comment]
Hi @kuaashish , sorry for the ping but would it possible to confirm that you can reproduce this issue and whether it is indeed a bug? Thanks in advance.

**Comment by kuaashish** [comment]
Hello @ghost
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
