### ISSUE TITLE
Hand  tracking , when running the GPU and CPU version,  GPU version cannot detect the landmark, but the CPU version can detect the landmark  , The same error  happened in other solutions . 

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#3858]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
- OS Platform and Distribution (Android 11 api=30, Redmi K40 Pro+):
- [MediaPipe version](https://github.com/google/mediapipe/releases): latest
- Bazel version:3.7.2
- Solution :  FaceMesh, Hand tracking ...
- Programming Language and version ( e.g. C++, Python, Java):

**Describe the expected behavior:**
 I used these  project in my phone :
[https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example](url)

**Other info / Complete Logs :**
report errors :"2022-11-15 18:28:38.830 29859-29859/com.example.mediapipemultihandstrackingapp E/libEGL: validate_display:87 error 3008 (EGL_BAD_DISPLAY) " 

[k40 debug.txt](https://github.com/google/mediapipe/files/10175163/k40.debug.txt)

**Comment by kuaashish** [comment]
Hi @chensisi0730,
Could you please elaborate your query with complete details and observation made in both of the cases to investigate further. Thank you!

**Comment by chensisi0730** [comment]
@kuaashish ,

**Comment by chensisi0730** [comment]
[https://drive.google.com/file/d/1XEX9rnHpVH1uuaCvhaJHVgj819VB1MFD/view?usp=sharing](url)

**Comment by kuaashish** [comment]
Hi @chensisi0730,
It looks like the issue with android device you are using, Would you try in the different device let us know if issue still persists.

**Comment by chensisi0730** [comment]
The issue sure is with the android device  using , but my job is to adapt all mobile phones including this device

**Comment by kuaashish** [comment]
Hi @chensisi0730,
This seems issue with mediapipe as I see from log that device has OpenGL ES 3.2 V@0530.0 version which required the OpenGL ES 3.2 to run the graphs/calculators as listed in [documentation](https://google.github.io/mediapipe/framework_concepts/gpu.html#opengl-es-support). We are assigning this issue to the right owner to do more investigation on issue. Thanks!

**Comment by mcclanahoochie** [comment]
The demo video shows you running the Face detection App. 
The graph seems to be loading hand tracking models (taken from your log file)
```
2022-12-07 18:22:05.668 19856-12259/com.example.mediapipemultihandstrackingapp I/native: I20221207 18:22:05.668534 12259
 resource_util_android.cc:89] Successfully loaded: palm_detection_full.tflite
```
but the graph is probably configured for face model settings (resolution/normalization/etc).

The AAR example you link to contains its [own set of models ](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example/tree/master/app/src/main/assets) , please make sure the correct graph and models are getting used.

**Comment by chensisi0730** [comment]
@mcclanahoochie  
I did two experiments,  
 In first   experiment  , i  run  [https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example](https://github.com/google/mediapipe/issues/url)
so result in   [k40 debug.txt](https://github.com/google/mediapipe/files/10175163/k40.debug.txt)

 in seconde   experiment  , i  run  face detction  of GPU and CPU version , Video based on this recording 。

so  you are confused !!

**Comment by chensisi0730** [comment]
@mcclanahoochie ：
hi  :
You know what I mean ?

**Comment by kuaashish** [comment]
Hello @chensisi0730,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
