### ISSUE TITLE
Duplicated calculator causes black screen

### ISSUE THREAD

**Issue by cc5721** [google/mediapipe#386]
I'm currently trying to create a custom calculator for edge detection gpu to test with before trying to do other things. The app is built and works normally. I wanted to see what happens when I create a calculator first.

I duplicated the luminance calculator to create luminance_calculator2.cc and renamed the class to LuminanceCalculator2.
I added it to the BUILD file in mediapipe/mediapipe/calculators/image

cc_library(
    name = "luminance_calculator2",
    srcs = ["luminance_calculator2.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//mediapipe/framework/port:ret_check",
        "//mediapipe/framework/port:status",
        "//mediapipe/gpu:gl_simple_calculator",
        "//mediapipe/gpu:gl_simple_shaders",
        "//mediapipe/gpu:shader_util",
    ],
    alwayslink = 1,
)

Then edited the files in mediapipe/mediapipe/graphs/edgedetection so the BUILD uses luminance_calculator2 in the deps field and the PBTXT uses LuminanceCalculator2 in the calculator field.

Can someone explain what I'm doing wrong or missed?
Running `bazel build -c opt --config=android_arm64 //mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu` and downloading it on my phone produces a black screen like this instead of the sobel edges:

![Screenshot_20200110-025554_Edge Detection GPU](https://user-images.githubusercontent.com/59723980/72135614-f17d1f80-3354-11ea-922b-8f7d04395cf4.jpg)

**Comment by cc5721** [comment]
Also, my phone is a Samsung Galaxy S8. the edge example works but changing the calculator doesn't

**Comment by eknight7** [comment]
Can you share your pbtxt file?

**Comment by cc5721** [comment]
I didn't edit it much from the original.

BUILD:
licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mobile_calculators",
    deps = [
        "//mediapipe/calculators/image:luminance_calculator2",
        "//mediapipe/calculators/image:sobel_edges_calculator",
    ],
)

load(
    "//mediapipe/framework/tool:mediapipe_graph.bzl",
    "mediapipe_binary_graph",
)

mediapipe_binary_graph(
    name = "mobile_gpu_binary_graph",
    graph = "edge_detection_mobile_gpu.pbtxt",
    output_name = "mobile_gpu.binarypb",
)

edge_detection_mobile_gpu.pbtxt:
# Images coming into and out of the graph.
input_stream: "input_video"
output_stream: "output_video"

# Converts RGB images into luminance images, still stored in RGB format.
node: {
  calculator: "LuminanceCalculator2"
  input_stream: "input_video"
  output_stream: "luma_video"
}

# Applies the Sobel filter to luminance images sotred in RGB format.
node: {
  calculator: "SobelEdgesCalculator"
  input_stream: "luma_video"
  output_stream: "output_video"
}

**Comment by eknight7** [comment]
In the `LuminanceCalculator2` file, did you change the line: `REGISTER_CALCULATOR(LuminanceCalculator);` to `REGISTER_CALCULATOR(Luminance2Calculator);` ?

**Comment by eknight7** [comment]
Also, can you try `adb logcat` to see if you are getting any errors?

**Comment by cc5721** [comment]
Yes

`#include "mediapipe/framework/port/ret_check.h"
#include "mediapipe/framework/port/status.h"
#include "mediapipe/gpu/gl_simple_calculator.h"
#include "mediapipe/gpu/gl_simple_shaders.h"
#include "mediapipe/gpu/shader_util.h"

enum { ATTRIB_VERTEX, ATTRIB_TEXTURE_POSITION, NUM_ATTRIBUTES };

namespace mediapipe {

// Converts RGB images into luminance images, still stored in RGB format.
// See GlSimpleCalculatorBase for inputs, outputs and input side packets.
class LuminanceCalculator2 : public GlSimpleCalculator {
 public:
  ::mediapipe::Status GlSetup() override;
  ::mediapipe::Status GlRender(const GlTexture& src,
                               const GlTexture& dst) override;
  ::mediapipe::Status GlTeardown() override;

 private:
  GLuint program_ = 0;
  GLint frame_;
};
REGISTER_CALCULATOR(LuminanceCalculator2);

::mediapipe::Status LuminanceCalculator2::GlSetup() {
  // Load vertex and fragment shaders
  const GLint attr_location[NUM_ATTRIBUTES] = {
      ATTRIB_VERTEX,
      ATTRIB_TEXTURE_POSITION,
  };
  const GLchar* attr_name[NUM_ATTRIBUTES] = {
      "position",
      "texture_coordinate",
  };

  const GLchar* frag_src = GLES_VERSION_COMPAT
      R"(
#if __VERSION__ < 130
  #define in varying
#endif  // __VERSION__ < 130

#ifdef GL_ES
  #define fragColor gl_FragColor
  precision highp float;
#else
  #define lowp
  #define mediump
  #define highp
  #define texture2D texture
  out vec4 fragColor;
#endif  // defined(GL_ES)

  in vec2 sample_coordinate;
  uniform sampler2D video_frame;
  const highp vec3 W = vec3(0.2125, 0.7154, 0.0721);

  void main() {
    vec4 color = texture2D(video_frame, sample_coordinate);
    float luminance = dot(color.rgb, W);
    fragColor.rgb = vec3(luminance);
    fragColor.a = 1 - color.a;
  }

  )";

  // shader program
  GlhCreateProgram(kBasicVertexShader, frag_src, NUM_ATTRIBUTES,
                   (const GLchar**)&attr_name[0], attr_location, &program_);
  RET_CHECK(program_) << "Problem initializing the program.";
  frame_ = glGetUniformLocation(program_, "video_frame");
  return ::mediapipe::OkStatus();
}

::mediapipe::Status LuminanceCalculator2::GlRender(const GlTexture& src,
                                                  const GlTexture& dst) {
  static const GLfloat square_vertices[] = {
      -1.0f, -1.0f,  // bottom left
      1.0f,  -1.0f,  // bottom right
      -1.0f, 1.0f,   // top left
      1.0f,  1.0f,   // top right
  };
  static const GLfloat texture_vertices[] = {
      0.0f, 0.0f,  // bottom left
      1.0f, 0.0f,  // bottom right
      0.0f, 1.0f,  // top left
      1.0f, 1.0f,  // top right
  };

  // program
  glUseProgram(program_);
  glUniform1i(frame_, 1);

  // vertex storage
  GLuint vbo[2];
  glGenBuffers(2, vbo);
  GLuint vao;
  glGenVertexArrays(1, &vao);
  glBindVertexArray(vao);

  // vbo 0
  glBindBuffer(GL_ARRAY_BUFFER, vbo[0]);
  glBufferData(GL_ARRAY_BUFFER, 4 * 2 * sizeof(GLfloat), square_vertices,
               GL_STATIC_DRAW);
  glEnableVertexAttribArray(ATTRIB_VERTEX);
  glVertexAttribPointer(ATTRIB_VERTEX, 2, GL_FLOAT, 0, 0, nullptr);

  // vbo 1
  glBindBuffer(GL_ARRAY_BUFFER, vbo[1]);
  glBufferData(GL_ARRAY_BUFFER, 4 * 2 * sizeof(GLfloat), texture_vertices,
               GL_STATIC_DRAW);
  glEnableVertexAttribArray(ATTRIB_TEXTURE_POSITION);
  glVertexAttribPointer(ATTRIB_TEXTURE_POSITION, 2, GL_FLOAT, 0, 0, nullptr);

  // draw
  glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

  // cleanup
  glDisableVertexAttribArray(ATTRIB_VERTEX);
  glDisableVertexAttribArray(ATTRIB_TEXTURE_POSITION);
  glBindBuffer(GL_ARRAY_BUFFER, 0);
  glBindVertexArray(0);
  glDeleteVertexArrays(1, &vao);
  glDeleteBuffers(2, vbo);

  return ::mediapipe::OkStatus();
}

::mediapipe::Status LuminanceCalculator2::GlTeardown() {
  if (program_) {
    glDeleteProgram(program_);
    program_ = 0;
  }
  return ::mediapipe::OkStatus();
}

}  // namespace mediapipe
`

**Comment by cc5721** [comment]
Right now adb isn't working on my phone. It works every once in a while so I'll try and check when it possible.

**Comment by eknight7** [comment]
Okay, I did the changes you mentioned, and the app still works on my end. Do share any logging results you get.

**Comment by cc5721** [comment]
01-10 11:22:56.333 31692 31713 E FrameProcessor: Mediapipe error:
01-10 11:22:56.333 31692 31713 E FrameProcessor: com.google.mediapipe.framework.MediaPipeException: internal: Graph has errors:
01-10 11:22:56.333 31692 31713 E FrameProcessor: Calculator::Process() for node "[LuminanceCalculator2, LuminanceCalculator2 with output stream: luma_video]" failed: ; Problem initializing the program.ulators/image/luminance_calculator2.cc:84)
01-10 11:22:56.333 31692 31713 E FrameProcessor:        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
01-10 11:22:56.333 31692 31713 E FrameProcessor:        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:380)
01-10 11:22:56.333 31692 31713 E FrameProcessor:        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:258)
01-10 11:22:56.333 31692 31713 E FrameProcessor:        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:261)
01-10 11:22:56.333 31692 31713 E FrameProcessor:        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:211)
01-10 11:22:56.333 31692 31713 E FrameProcessor:        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source:4)
01-10 11:22:56.333 31692 31713 E FrameProcessor:        at android.os.Handler.handleCallback(Handler.java:873)
01-10 11:22:56.333 31692 31713 E FrameProcessor:        at android.os.Handler.dispatchMessage(Handler.java:99)
01-10 11:22:56.333 31692 31713 E FrameProcessor:        at android.os.Looper.loop(Looper.java:214)
01-10 11:22:56.333 31692 31713 E FrameProcessor:        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:134)
01-10 11:22:56.504 31692 31713 I chatty  : uid=10373(com.google.mediapipe.apps.edgedetectiongpu) ExternalTexture identical 4 lines

**Comment by cc5721** [comment]
It seems to be working after using `bazel build -c opt --config=android_arm //mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu`

After calling it, both android_arm and android_arm64 versions appear to be working on my device. Is there any particular reason why this might be the case?

**Comment by jiuqiant** [comment]
android_arm is armeabi-v7a and android_arm64 is essentially arm64-v8a. See https://github.com/google/mediapipe/blob/master/.bazelrc#L34. According to http://www.greenbagpipes.com/samsung_galaxy_s8,  the chip of galaxy s8 is ARM Cortex-A53 and Samsung Exynos M2. Seems like both of them support ARMv8-A64-bit instruction set. Not quite sure what's going wrong with android_arm64.

**Comment by cc5721** [comment]
Alright, thank you. I'm not sure what is wrong but since it's working, I guess the issue should be closed?
