### ISSUE TITLE
FaceMesh Desktop Run "Can't find file: mediapipe/modules/face_detection/face_detection_short_range.tflite"

### ISSUE THREAD

**Issue by kangyul** [google/mediapipe#3864]
**System information**
- Have I written custom code: X
- OS Platform and Distribution: macOS Ventura (Version 13.0)
- [MediaPipe version](https://github.com/google/mediapipe/releases): master branch
- Bazel version: 5.2.0
- Solution: FaceMesh
- Programming Language and version: C++ 

**Describe the expected behavior:**

Build and run Face Landmark Example on Desktop Running on CPU

**Standalone code you may have used to try to get what you need :**

Build
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/face_mesh:face_mesh_cp`

Run
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_mesh/face_mesh_cpu \
      --calculator_graph_config_file=mediapipe/graphs/face_mesh/face_mesh_desktop_live.pbtxt
```

**Other info / Complete Logs :**
The complete error log
```
I20221116 17:59:35.089862 246048000 demo_run_graph_main.cc:54] Initialize the calculator graph.
I20221116 17:59:35.095134 246048000 demo_run_graph_main.cc:58] Initialize the camera or load the video.
I20221116 17:59:36.638492 246048000 demo_run_graph_main.cc:79] Start running the calculator graph.
I20221116 17:59:36.639755 246048000 demo_run_graph_main.cc:84] Start grabbing and processing frames.
E20221116 17:59:36.674479 246048000 demo_run_graph_main.cc:154] Failed to run the graph: Graph has errors:
Calculator::Open() for node "facelandmarkfrontcpu__facedetectionshortrangecpu__facedetectionshortrange__facedetection__inferencecalculator__facelandmarkfrontcpu__facedetectionshortrangecpu__facedetectionshortrange__facedetection__InferenceCalculator" failed: ; Can't find file: mediapipe/modules/face_detection/face_detection_short_range.tflite
```

The current working directory when the command runs

```
❯ pwd
/Users/scienceshow/Desktop/opencv/mediapipe

❯ ls
BUILD.bazel                  WORKSPACE                    build_desktop_examples.sh    setup.py
CONTRIBUTING.md              bazel-bin                    build_ios_examples.sh        setup_android_sdk_and_ndk.sh
Dockerfile                   bazel-mediapipe              docs                         setup_opencv.sh
LICENSE                      bazel-out                    mediapipe                    third_party
MANIFEST.in                  bazel-testlogs               package.json                 tsconfig.json
README.md                    build_android_examples.sh    requirements.txt             yarn.lock
```

I have tried this command and encountered the same error 
```
set GLOG_logtostderr=1
bazel-bin/mediapipe/examples/desktop/face_mesh/face_mesh_cpu   --calculator_graph_config_file=mediapipe/graphs/face_mesh/face_mesh_desktop_live.pbtxt
```

**Comment by kuaashish** [comment]
Hi @kangyul,
Have you looked at this similar closed issue #3761 and [#3761(Comment)](https://github.com/google/mediapipe/issues/3761#issuecomment-1285199965). Thank you!

**Comment by kangyul** [comment]
Yeah I've looked at the similar closed issue and tried everything in there. However, I couldn't figure out what you said at #3761: "This might be fixed by invoking the "face_mesh_cpu" binary using bazel". Could you elaborate more about this step? Thanks!

**Comment by limsb95** [comment]
I have the same problem running face_mesh solution on windows

**Comment by BluValor** [comment]
I have the same problem for FaceMesh and Holistic cpu examples on macOS Monterey (Version 12.5.1).

**Comment by elix22** [comment]
Having the same problem , running on MacBook Pro 16 , Intel chip , macOS Monterey 12.6.1

Elis-MacBook-Pro-16:mediapipe elialoni$ GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/holistic_tracking/holistic_tracking_cpu  --calculator_graph_config_file=mediapipe/graphs/holistic_tracking/holistic_tracking_cpu.pbtxt
I20221121 17:49:35.667063 322156032 demo_run_graph_main.cc:48] Get calculator graph config contents: # Tracks and renders pose + hands + face landmarks.

# CPU image. (ImageFrame)
input_stream: "input_video"

# CPU image with rendered results. (ImageFrame)
output_stream: "output_video"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.FlowLimiterCalculatorOptions] {
      max_in_flight: 1
      max_in_queue: 1
      # Timeout is disabled (set to 0) as first frame processing can take more
      # than 1 second.
      in_flight_timeout: 0
    }
  }
}

node {
  calculator: "HolisticLandmarkCpu"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "POSE_LANDMARKS:pose_landmarks"
  output_stream: "POSE_ROI:pose_roi"
  output_stream: "POSE_DETECTION:pose_detection"
  output_stream: "FACE_LANDMARKS:face_landmarks"
  output_stream: "LEFT_HAND_LANDMARKS:left_hand_landmarks"
  output_stream: "RIGHT_HAND_LANDMARKS:right_hand_landmarks"
}

# Gets image size.
node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "SIZE:image_size"
}

# Converts pose, hands and face landmarks to a render data vector.
node {
  calculator: "HolisticTrackingToRenderData"
  input_stream: "IMAGE_SIZE:image_size"
  input_stream: "POSE_LANDMARKS:pose_landmarks"
  input_stream: "POSE_ROI:pose_roi"
  input_stream: "LEFT_HAND_LANDMARKS:left_hand_landmarks"
  input_stream: "RIGHT_HAND_LANDMARKS:right_hand_landmarks"
  input_stream: "FACE_LANDMARKS:face_landmarks"
  output_stream: "RENDER_DATA_VECTOR:render_data_vector"
}

# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "VECTOR:render_data_vector"
  output_stream: "IMAGE:output_video"
}
I20221121 17:49:35.668082 322156032 demo_run_graph_main.cc:54] Initialize the calculator graph.
I20221121 17:49:35.691287 322156032 demo_run_graph_main.cc:58] Initialize the camera or load the video.
I20221121 17:49:37.939334 322156032 demo_run_graph_main.cc:79] Start running the calculator graph.
I20221121 17:49:37.940101 322156032 demo_run_graph_main.cc:84] Start grabbing and processing frames.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
I20221121 17:49:38.940539 322156032 demo_run_graph_main.cc:92] Ignore empty frames from camera.
E20221121 17:49:39.353267 322156032 demo_run_graph_main.cc:154] Failed to run the graph: Graph has errors: 
Calculator::Open() for node "holisticlandmarkcpu__facelandmarksfromposecpu__facedetectionshortrangebyroicpu__facedetectionshortrange__facedetection__inferencecalculator__holisticlandmarkcpu__facelandmarksfromposecpu__facedetectionshortrangebyroicpu__facedetectionshortrange__facedetection__InferenceCalculator" failed: ; Can't find file: mediapipe/modules/face_detection/face_detection_short_range.tflite

**Comment by elix22** [comment]
Having the same problem , MacBook Pro 16 , Intel chip , macOS Monterey (Version 12.6.1)


**GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/holistic_tracking/holistic_tracking_cpu  --calculator_graph_config_file=mediapipe/graphs/holistic_tracking/holistic_tracking_cpu.pbtxt**
...
...
I20221121 17:49:35.668082 322156032 demo_run_graph_main.cc:54] Initialize the calculator graph.
I20221121 17:49:35.691287 322156032 demo_run_graph_main.cc:58] Initialize the camera or load the video.
I20221121 17:49:37.939334 322156032 demo_run_graph_main.cc:79] Start running the calculator graph.
I20221121 17:49:37.940101 322156032 demo_run_graph_main.cc:84] Start grabbing and processing frames.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
I20221121 17:49:38.940539 322156032 demo_run_graph_main.cc:92] Ignore empty frames from camera.
E20221121 17:49:39.353267 322156032 demo_run_graph_main.cc:154] Failed to run the graph: Graph has errors: 
Calculator::Open() for node "holisticlandmarkcpu__facelandmarksfromposecpu__facedetectionshortrangebyroicpu__facedetectionshortrange__facedetection__inferencecalculator__holisticlandmarkcpu__facelandmarksfromposecpu__facedetectionshortrangebyroicpu__facedetectionshortrange__facedetection__InferenceCalculator" failed: ; Can't find file: mediapipe/modules/face_detection/face_detection_short_range.tflite

**Comment by elix22** [comment]
checking out v0.8.10.2
**git checkout v0.8.10.2**
Works fine 

v0.8.11 - same error

**Comment by cdiddy77** [comment]
This is a basic demo app, not working right out of the box. The most obvious question is: how does one ensure that `[bazel-bin?]/mediapipe/modules/face_detection/face_detection_short_range.tflite` exists?

**Comment by cdiddy77** [comment]
To answer my own question, I downloaded from [here](https://storage.googleapis.com/mediapipe-assets/face_detection_short_range.tflite) to bazel-bin as above, and now the demo works. That isn't super satisfying, but whatever, I guess?

**Comment by ayushgdev** [comment]
Hello @kangyul 
This is a known bug which we have escalated to the release management team. For the time being, you can simply bypass this error by downloading the concerned file and pasting it to the location prompted by the error.  For your case, please download short range model from [this section](https://google.github.io/mediapipe/solutions/models.html#face-detection) and copy paste it within mediapipe/modules/face_detection/.

In general, please go to the [Model cards page](https://google.github.io/mediapipe/solutions/models.html) and download the required file.

**Comment by imyhxy** [comment]
The model files already download in the `~/.cache/bazel` directory, for some reasons, it not automatically copy to the workspace. I think this maybe some issue of bazel.

**Comment by russelljahn** [comment]
Confirming I can repro this running the holistic_tracking_cpu demo on Ubuntu 18.04:

`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/holistic_tracking/holistic_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/holistic_tracking/holistic_tracking_cpu.pbtxt` 

I can confirm that @cdiddy77's workaround above does work to get it running:

> To answer my own question, I downloaded from [here](https://storage.googleapis.com/mediapipe-assets/face_detection_short_range.tflite) to bazel-bin as above, and now the demo works. That isn't super satisfying, but whatever, I guess?
> 
> I discovered this link [here](https://github.com/google/mediapipe/blob/1761cdcef4ff6fd37d04d15de765eccd7c0a5bcc/docs/solutions/models.md#L18)

**Comment by chopper-lee-brain** [comment]
After being updated to download tflite files from gcp, the necessary tflite files have to be specified in BUILD.

In the face mesh and holistic examples, the `face_detection_short_range.tflite` required for face detection was missing.
When examples are build and run for the first time, an error occurs that the face detection model cannot be found.

I make a PR for fixing these errors.
https://github.com/google/mediapipe/pull/4236

**Comment by FunnyWii** [comment]
> To answer my own question, I downloaded from [here](https://storage.googleapis.com/mediapipe-assets/face_detection_short_range.tflite) to bazel-bin as above, and now the demo works. That isn't super satisfying, but whatever, I guess?
> 
> I discovered this link [here](https://github.com/google/mediapipe/blob/1761cdcef4ff6fd37d04d15de765eccd7c0a5bcc/docs/solutions/models.md#L18)

Works！
