### ISSUE TITLE
render shoes model on feet

### ISSUE THREAD

**Issue by DaehoDaeho** [google/mediapipe#3865]
hi~
i'm using Unity3d and MediapipeUnityPlugin.
i'm trying render shoes model on feet.
i'm checking Objectron sample.
but i can't find unity3d based example or solution.
I don't know much about Python or other languages.
can someone give me some help?
how can I implement it as a Unity based plugin?

**Comment by kuaashish** [comment]
Hi @DaehoDaeho,
Similar to issue #3610 has already been assigned to the team but due to limited bandwidth it will take a moment to address the issue. Meanwhile, You can go through the workaround mentioned in the similar issue referred to. Thank you!

**Comment by sprengerst** [comment]
+1

**Comment by kuaashish** [comment]
Hello @DaehoDaeho,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
