### ISSUE TITLE
Gradle Import Unknown for Mediapipe Pose Detection

### ISSUE THREAD

**Issue by Faiizii** [google/mediapipe#3867]
What is the gradle import for pose detection ? like `
    implementation 'com.google.mediapipe:hands:latest.release'`

**Comment by kuaashish** [comment]
Hi @Faiizii,
Unfortunately, MediaPipe does not have a Pose detection Android solution available with Gradle as mentioned [here](https://google.github.io/mediapipe/getting_started/android_solutions.html#mediapipe-android-solutions). However, You could still build the Android aar solution as mentioned [here](https://google.github.io/mediapipe/solutions/pose.html#main-example) in the documentation. Thank you!

**Comment by kuaashish** [comment]
Hi @Faiizii,
[Google's Maven Repository](https://google.github.io/mediapipe/getting_started/android_solutions.html#mediapipe-android-solutions) does not contain the prebuilt MediaPipe solution for pose tracking. Hence, pose tracking cannot be included directly as gradle dependency. Although custom AAR packages can be built as per the guide given [here](https://google.github.io/mediapipe/solutions/pose.html#mobile). Thank you!

**Comment by kuaashish** [comment]
Hi @Faiizii,
We are marking this as feature request and sharing with internal team to look into this feature further. Thanks!

**Comment by kuaashish** [comment]
Hello @Faiizii,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by Faiizii** [comment]
Hi @kuaashish Thanks for the new guide. I loved your dedication for this new feature/enhancement request. Now, I've moved to new opportunity. I will definitely give it a try in the future. I am closing this for now. BTW, I loved your library and its accuracy as compared to other available ML solutions.
