### ISSUE TITLE
Processing Steps Between Face Detection and Face Mesh

### ISSUE THREAD

**Issue by barisbatuhan** [google/mediapipe#3868]
**System information**

-  OS: Ubuntu WSL in Windows 10
- Solution: Face Mesh
- Programming Language: Python 3
- MediaPipe Version: latest

**Describe the expected behavior:**

I am trying to use the `face_landmark.tflite` module (from the path `<python_packages_dir>/mediapipe/modules/face_landmark` in the Python installation directory) to detect landmarks of an already cropped face with 0.25 margin on each side, that is resized to 192x192. However, I do not get my results as accurate as using `mp.solutions.face_mesh.FaceMesh`. I know that Face Mesh module includes a detection process first, and then ROI extraction, and lastly running the landmark model. However, I have seen that in `mp.solutions.holistic.Holistic` there is an extra face/ROI alignment module, whose node can be seen below and from this [link](https://github.com/google/mediapipe/blob/master/mediapipe/modules/holistic_landmark/face_detection_front_detections_to_roi.pbtxt):

```
# Converts the face detection into a rectangle (normalized by image size)
# that encloses the face and is rotated such that the line connecting right side
# of the right eye and left side of the left eye is aligned with the X-axis of
# the rectangle.
node {
  calculator: "DetectionsToRectsCalculator"
  input_stream: "DETECTIONS:detections"
  input_stream: "IMAGE_SIZE:image_size"
  output_stream: "NORM_RECT:raw_roi"
  options: {
    [mediapipe.DetectionsToRectsCalculatorOptions.ext] {
      rotation_vector_start_keypoint_index: 0  # Right eye.
      rotation_vector_end_keypoint_index: 1  # Left eye.
      rotation_vector_target_angle_degrees: 0
      conversion_mode: USE_KEYPOINTS
    }
  }
}
``` 

I know that the processing steps are not the same for Holistic and Face Mesh. Moreover, if I align my 192x192 cropped face so that the left and right eye centers are parallel to the X-axis of the image (by taking the nose point as the center), then my results with `.tflite` model is closer to the MediaPipe FaceMesh API. In the graph structure and the source codes, I could not find the extra processing steps for Face Mesh between detection and landmark extraction. 

So my questions are:

1) Which processing steps are applied between detection and landmark localization? Which file gives the details of these steps?
2) Does face alignment occur in these processing steps? If yes, then by using which points the angle of rotation is calculated and which point is assumed to be the center of the rotation?
3) I followed the [Model Card](https://drive.google.com/file/d/1QvwWNfFoweGVjsXF3DXzcrCnz-mx-Lha/preview) for setting face margin, cropping, and resizing. Are these values still valid for Face Mesh or are they deprecated? If they are deprecated, where can I find the up-to-date values?

Thanks.

**Comment by barisbatuhan** [comment]
Hi, It has ben almost 3 weeks but I did not get any response. I just want to remind this issue. Thanks.

**Comment by chuoling** [comment]
> Which processing steps are applied between detection and landmark localization? Which file gives the details of these steps?

https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_detection_front_detection_to_roi.pbtxt

> Does face alignment occur in these processing steps? If yes, then by using which points the angle of rotation is calculated and which point is assumed to be the center of the rotation?

Please see the calculator options in the aforementioned graph, and implementation of the corresponding calculators https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/detections_to_rects_calculator.cc and https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/rect_transformation_calculator.cc.

> I` followed the [Model Card](https://drive.google.com/file/d/1QvwWNfFoweGVjsXF3DXzcrCnz-mx-Lha/preview) for setting face margin, cropping, and resizing. Are these values still valid for Face Mesh or are they deprecated? If they are deprecated, where can I find the up-to-date values?

The configurations documented in the model cards are parameters used in model quality/fairness evaluation. For image processing configurations in the end-to-end Face Mesh solution (e.g., mp.solutions.face_mesh.FaceMesh), please refer to the aforementioned graph and calculator configuration & implementation.
