### ISSUE TITLE
Hi guys i cant install mediapipe

### ISSUE THREAD

**Issue by Nurzodbe** [google/mediapipe#3870]
#mediapipe
i cant install mediapipe

python version 3.11.0
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe

**Comment by kuaashish** [comment]
Hi @Nurzodbe, 
MediaPipe has no official support for Python 3.11 yet. Please use version 3.7-3.10. You can keep a track of the supported version from the releases page [here](https://github.com/google/mediapipe/releases). Thank you!

**Comment by kuaashish** [comment]
@Nurzodbe,
Could you please go through the [above](https://github.com/google/mediapipe/issues/3870#issuecomment-1319630342) comment and let us know if we can move this issue to close status as it has been resolved. Thank you!
