### ISSUE TITLE
how to get landmarks using Holistic tracking solution on Android?

### ISSUE THREAD

**Issue by beakyangsu** [google/mediapipe#3872]
System information (Please provide as much relevant information as possible)

Have I written custom code (as opposed to using a stock example script provided in Mediapipe): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 11
[MediaPipe version](https://github.com/google/mediapipe/releases): latest git clone (v0.8.9)
Bazel version: 4.2.1
Solution (e.g. FaceMesh, Pose, Holistic): Pose
Programming Language and version ( e.g. C++, Python, Java): Java and Kotlin

Hi.
How to get landmarks using Holistic tracking solution on Android?
I tryed this code. 
`  processor.addPacketCallback(
               "right_hand_landmarks",
                (packet) -> {
                    List<LandmarkProto.NormalizedLandmarkList> l =
                            PacketGetter.getProtoVector(packet, LandmarkProto.NormalizedLandmarkList.parser());
                });`

 
but failed. 
I think  output Stream for "right_hand_landmarks" doesnt't exist. 
I'm working on this example code. 
https://github.com/shadow111/mediapipe-holistic-tracking-aar-example.

Please let me know how to get landmarks on Android using holistic.
I want to get landmarks for right hand, left hand, face, pose.

Thanks.

**Comment by beakyangsu** [comment]
Please answer~

**Comment by kuaashish** [comment]
Hi @chuoling,
Could you please share the some pointers here.

**Comment by chuoling** [comment]
The AAR example https://github.com/shadow111/mediapipe-holistic-tracking-aar-example you use runs the [holistic_tracking_gpu.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/holistic_tracking/holistic_tracking_gpu.pbtxt) graph underneath, which only has a single output stream "output_video". You'll want to add, e.g., "right_hand_landmarks", as additional graph output streams, similar to how it's done in https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt#L18 (which is then used in https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example/blob/master/app/src/main/java/com/example/mediapipemultihandstrackingapp/MainActivity.java#L116).

**Comment by thivux** [comment]
> The AAR example https://github.com/shadow111/mediapipe-holistic-tracking-aar-example you use runs the [holistic_tracking_gpu.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/holistic_tracking/holistic_tracking_gpu.pbtxt) graph underneath, which only has a single output stream "output_video"

@chuoling I wonder how did you know that that repo used the `holistic_tracking_gpu.pbtxt` graph underneath? i searched the repo and found no `.pbtxt` file
