### ISSUE TITLE
Mediapipe Breaks on IOS 15.4

### ISSUE THREAD

**Issue by JackRealift** [google/mediapipe#3874]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):

Using the MediaPipe pose demo: https://codepen.io/mediapipe/pen/jOMbvxw

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):

IOS 15.4

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:

iPhone 13 Pro Max, IOS 15.4

- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:

Safari and Chrome

- Programming Language and version ( e.g. C++, Python, Java):

Javascript 

- [MediaPipe version](https://github.com/google/mediapipe/releases):

Latest

- Bazel version (if compiling from source):

N/A

- Solution ( e.g. FaceMesh, Pose, Holistic ):

Pose

- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):

N/A

- Xcode & Tulsi version (if issue is related to building for iOS):

14.1

**Describe the current behavior:**

Large error stack appears when running IOS 15.4 on latest version of Mediapipe and older versions. I'm trying to load the pose detection model and it does not load. 

**Describe the expected behavior:**

On other IOS versions at and above 14 it loads perfectly normally. 

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:

Using the MediaPipe pose demo: [Demo](https://codepen.io/mediapipe/pen/jOMbvxw)

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

[LogsForMPOn15.4.txt](https://github.com/google/mediapipe/files/10044256/LogsForMPOn15.4.txt)

**Comment by kuaashish** [comment]
Hi @JackRealift,
Currently, Camera option is unavailable in Chrome on iOS as mentioned [here](https://google.github.io/mediapipe/getting_started/javascript.html#supported-plaforms). Could you please confirm that the iOS above 14.0 version issue still persists in Safari? Thank you!

**Comment by JackRealift** [comment]
@kuaashish I am using Safari and Chrome. I found that it worked with and above 14 with the exception of 15.4.

**Comment by kuaashish** [comment]
Hello @JackRealift,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
