### ISSUE TITLE
Unable to install mediapipe in m2 mac

### ISSUE THREAD

**Issue by akhilsurnedi5479** [google/mediapipe#3875]
Tried to install mediapipe in m2.
Tried using "pip install mediapipe-silicon "
![image](https://user-images.githubusercontent.com/30592366/202822361-7b2168b9-cf62-456b-b7bc-06f621c8abbc.png)

Even downgraded python to 3.7.15

**Comment by akhilsurnedi5479** [comment]
Python 3.9 is working

**Comment by kuaashish** [comment]
Hello @akhilsurnedi5479,
We have released Universal Wheels with version `0.9.3.0` as guided [here](https://github.com/google/mediapipe/releases/tag/v0.9.3.0) in the release page with Python 3.11. 
Please try out to build mediapipe using pip let us know if still an issue from your end. Thank you

**Comment by kuaashish** [comment]
@akhilsurnedi5479,
Thanks for the confirmation, mediapipe-silicon wheels are not officially maintained by our team. We encourage you to use the official mediapipe wheels. Please let us know if we can move the issue to close status as the issue has been resolved.

**Comment by akhilsurnedi5479** [comment]
@kuaashish,
Everything works good. Thank you. You can close this issue.
