### ISSUE TITLE
Input Image Size Change Ignored by AnnotationOverlayCalculator

### ISSUE THREAD

**Issue by serrabii** [google/mediapipe#3878]
Hi, 

I have a use case where an input stream accepts frames with different sizes. This could be as simple as connecting different camera resolutions at different times during the same run of the graph.

However, I have noticed a visual bug that i traced to the calculator `AnnotationOverlayCalculator`, where `GlSetup` is called only once during the first call to `Process`. This leads to the assumption that all incoming images have the same `width_` and `height_`. Is this the expected behaviour?

To workaround this, I have added a few lines of code to reinitialise the gpu if the input image size changes. However, I think 
that calculators should be implemented to be as stateless as possible. What are your thoughts regarding state for nodes/calculators?

 ```
  if (use_gpu_) {
#if !MEDIAPIPE_DISABLE_GPU
    // Reinitialize if input image size has changed.
    if (gpu_initialized_) {
      const float alignment = ImageFrame::kGlDefaultAlignmentBoundary;
      if (image_frame_available_) {
        const auto& input_frame = cc->Inputs().Tag(kGpuBufferTag).Get<mediapipe::GpuBuffer>();
        gpu_initialized_ = (width_ == RoundUp(input_frame.width(), alignment)) &&
                (height_ == RoundUp(input_frame.height(), alignment));
      } else {
        gpu_initialized_ = (width_ == RoundUp(options_.canvas_width_px(), alignment)) &&
                (height_ == RoundUp(options_.canvas_height_px(), alignment));
      }
    }

    if (!gpu_initialized_) {
      MP_RETURN_IF_ERROR(
          gpu_helper_.RunInGlContext([this, cc]() -> absl::Status {
            return GlSetup<mediapipe::GpuBuffer, kGpuBufferTag>(cc);
          }));
      gpu_initialized_ = true;
    }
    if (cc->Inputs().HasTag(kGpuBufferTag)) {
      MP_RETURN_IF_ERROR(
          (CreateRenderTargetGpu<mediapipe::GpuBuffer, kGpuBufferTag>(
              cc, image_mat)));
    }
#endif  // !MEDIAPIPE_DISABLE_GPU
```

**Comment by kuaashish** [comment]
Hi @serrabii,
Could you elaborate your query with complete details, error logs and steps followed to reproduce the issue from our end. Thank you!

**Comment by serrabii** [comment]
Hi @kuaashish 

The simplest way to reproduce this error would be to modify `mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java` in order to change the camera   without restarting the graph.

1. First, change the function `startCamera` to accept two more arguments.

```
  public void startCamera(CameraHelper.CameraFacing cameraFacing, Size targetResolution) {
    cameraHelper = new CameraXPreviewHelper();
    previewFrameTexture = converter.getSurfaceTexture();
    cameraHelper.setOnCameraStartedListener(
        surfaceTexture -> {
          onCameraStarted(surfaceTexture);
        });
    cameraHelper.startCamera(
        this, cameraFacing, previewFrameTexture, targetResolution);
  }
```

2. Second, change the `onResume` to change the camera after a certain delay. In this example, I start the BACK camera with a target resolution of 1440x1080 for 5 seconds then change to the FRONT camera with the default target resolution which is 1280x720. I am not sure if all devices with back camera can capture with 1440x1080 but the bug can be reproduced as long as the capture resolution changes.

```
  @Override
  protected void onResume() {
    super.onResume();
    converter =
        new ExternalTextureConverter(
            eglManager.getContext(),
            applicationInfo.metaData.getInt("converterNumBuffers", NUM_BUFFERS));
    converter.setFlipY(
        applicationInfo.metaData.getBoolean("flipFramesVertically", FLIP_FRAMES_VERTICALLY));
    converter.setConsumer(processor);
    if (PermissionHelper.cameraPermissionsGranted(this)) {
      // First start BACK camera for few secs
      startCamera(CameraHelper.CameraFacing.BACK, new  Size(1440, 1080));

      // After 5secs, start FRONT camera with different Resolution 
      new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
        @Override
        public void run() {
          converter.close();
          previewDisplayView.setVisibility(View.GONE);
          converter =
                  new ExternalTextureConverter(
                          eglManager.getContext(),
                          applicationInfo.metaData.getInt("converterNumBuffers", NUM_BUFFERS));
          converter.setFlipY(
                  applicationInfo.metaData.getBoolean("flipFramesVertically", FLIP_FRAMES_VERTICALLY));
          converter.setConsumer(processor);
          startCamera(CameraHelper.CameraFacing.FRONT, null);
        }
      }, 5000);
    }
  }
```

3. Install `facedetectiongpu` and check that after 5 secs, when the app swaps to the FRONT camera with default target resolution, the  preview would still be using the first target resolution adapted to the display size using Fill and Crop of `GlSurfaceSinkCalculator`. You can also simply compare the resulting preview with the one obtained before applying these changes.
