### ISSUE TITLE
Left Hand Landmark for MP pose and MP hand

### ISSUE THREAD

**Issue by UtsaChattopadhyay** [google/mediapipe#3879]
I am using both mediapipe pose and mediapipe hand models to get landmarks and retarget to an AVATAR for animation.
But the LeftHand (15) and RightHand (16) landmark from mediapipe POSE and wrist landmark (0) from mediapipe Hands is not the same for one image, and so while creating the BVH, for the whole body including hand bones, I am getting wrong rotation for the hand part. 
Both are working fine seperately.
May I know is there any way to map the HandLandmark origin to the pose Landmark one?
Thanks

**Comment by kuaashish** [comment]
Hi @UtsaChattopadhyay,
Could you please elaborate your query with complete details and platform which you are referring to. Thank you!

**Comment by UtsaChattopadhyay** [comment]
Yeah sure. The link below explains a bit on this.
https://github.com/google/mediapipe/issues/3491#issuecomment-1185161389
So I am using mediapipe pose and mediapipe hand together to generate landmark and then later create Euler rotations to make BVH out of it.
But the LeftHand landmark of mediapipe pose [here] https://mediapipe.dev/images/mobile/pose_tracking_full_body_landmarks.png is calculated with hips at the center and for the hand at the HANDS GEOMETRIC CENTER. So i want to map the hand calculated WRIST landmark to the one calculated already by the POSE model to merge both together.
If you have any isight on this please let me know.
Thanks.

**Comment by UtsaChattopadhyay** [comment]
![rotation_difference](https://user-images.githubusercontent.com/44424045/203884833-a0bfaf70-3b12-4fcd-8198-fcd9759b0c0b.PNG)
If you refer to the picture, thats how it looks if I use the Landmark value for LeftHand from two models. I just want to map the Hand model landmark output to Pose model. 
Any help is appreciated.

**Comment by UtsaChattopadhyay** [comment]
Hi,
I have solved the issue, so tentatively you have to do this
MediaPipeHolistic:BODY_CENTERED_HAND_COORDINATES = 
MediaPipePose:POSE_WORLD_LANDMARKS:AverageValueOfHandCoordinates + MediaPipeHands:MULTI_HAND_WORLD_LANDMARKS
Thanks.

**Comment by kuaashish** [comment]
Hi @UtsaChattopadhyay,
Glad to know the issue has been resolved! Could we move this issue to the close status as resolved. Thank you!

**Comment by UtsaChattopadhyay** [comment]
Yeah sure
