### ISSUE TITLE
How output keypoints without image/video by Hand tracking ?

### ISSUE THREAD

**Issue by chiaruy** [google/mediapipe#388]
I want get keypoints of hand by hand tracking without output video on android system.
keypoints can immediate update to array is well best.
i don't want save keypoints to external memory then read it, it is slowly.
how can i do?

thanks advance

**Comment by romaindebraize** [comment]
Did you find a solution ?

**Comment by eknight7** [comment]
@romaindebraize I never got to answer the question as it got closed. Can you clarify a little bit about what you need here?  Thanks.
