### ISSUE TITLE
Mediapipe Pose, how can I release memory hold by pose model? (Python)

### ISSUE THREAD

**Issue by aerarslan** [google/mediapipe#3881]
Hi! I am creating a pose model and this holds let's say 100MB in the memory. When I remove the pose model object with "del" command and use the garbage collector, the memory it holds is not released. Exactly 100MB is held in the memory until I reset my environment. How can I release the whole memory that is held by the Pose model? 

For example, if it holds 100 MB for the pose model and if I create the pose model in a for loop for 10 iterations, at the end it exactly holds 1000MB even though I create the objects with the same name and delete/garbage-collect them.

I am creating Pose Model more than once because I am running many videos with different resolutions. If I try using the same Pose model for a video that has a different resolution, I am getting the error below. Maybe this might help to find a solution to my problem.

E20221123 15:36:44.515576 11080 calculator_graph.cc:805] INTERNAL: CalculatorGraph::Run() failed in Run:
Calculator::Process() for node "posesegmentationfiltering__SegmentationSmoothingCalculator" failed: ; (current_mat.rows)==(previous_mat.rows)s/image/segmentation_smoothing_calculator.cc:196)

**Comment by kuaashish** [comment]
Hi @aerarslan, 
Would you please confirm if you are closing or resetting the calculator graph between subsequent initialization's or not?
Thank you!

**Comment by aerarslan** [comment]
Hi @kuaashish 
Thank you for your answer. I am not closing or resetting the calculator graph between initializations. I was expecting this as the root of my problem because also in the troubleshooting part of the mediapipe I saw some related information but I could not understand how to implement it. Could you please send me an example of how to close and reset the calculator graph between initializations in Python?

**Comment by kuaashish** [comment]
Hi @aerarslan,
reset() is available in [SolutionBase](https://github.com/google/mediapipe/blob/master/mediapipe/python/solution_base.py#L388) class, hence it will be available for all solutions classes derived from SolutionBase. So within your context manager for the pose detection, use your pose object to call reset() once you need to release graph. Please find a sample snippet below:
```
with pose.Pose(static_image_mode=True) as pose_obj:
  results = pose_obj.process(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
  pose_obj.reset()
```
Thank you!

**Comment by crystalssssssssssssssssssss** [comment]
@kuaashish Can you give a c++ release example? thank you~
