### ISSUE TITLE
Selfie Segmentation background replacement in windows

### ISSUE THREAD

**Issue by kishor-e** [google/mediapipe#3884]
I'm trying to replace the background( from default blue background to a custom image) in Selfie Segmentation in windows.

This is the custom calculator that I've used for replacing the background

    ::mediapipe::Status BackgroundMaskingCalculator::Process(CalculatorContext* cc) {

    ///////////////////////ANDROID Asset reading method
    // cv::Mat background;

    // mediapipe::StatusOr<std::string> status = ::mediapipe::PathToResourceAsFile("clouds2.png"); 
    // mediapipe::StatusOr<std::string> status = ::mediapipe::PathToResourceAsFile("stars.png"); 
    // mediapipe::StatusOr<std::string> status = ::mediapipe::PathToResourceAsFile("buildings.jpg"); 
    

    // if (status.ok()){
    // background = cv::imread(status,value() 1);
    // }

    ///////////////////////////////// DESKTOP Asset reading method
    // cv::Mat background = cv::imread("mediapipe/calculators/image/testdata/front_camera_pixel2.jpg");
    cv::Mat background = cv::imread("mediapipe/calculators/image/testdata/buildings.jpg");    
    std::cout << " Process() of BgMasking" << std::endl;

    const auto& input_img = cc->Inputs().Tag("IMAGE_CPU").Get<ImageFrame>();
    cv::Mat input_mat = formats::MatView(&input_img);

    const auto& mask_img = cc->Inputs().Tag("MASK_CPU").Get<ImageFrame>();
    cv::Mat mask_mat = formats::MatView(&mask_img);
    // std::cout << mask_mat << std::endl;

    cv::cvtColor(background, background, cv::COLOR_BGR2RGB);
    cv::cvtColor(background, background, cv::COLOR_RGB2RGBA);
    cv::resize(background, background, input_mat.size());       

    // create binary bg mask
    cv::Mat channels[4];
    cv::split(mask_mat, channels);

    cv::Mat bg_mask;
    cv::Mat fg_mask;

    cv::Mat in[] = {channels[3], channels[3], channels[3], channels[3]};
    cv::merge(in, 4, bg_mask);

    cv::bitwise_not(bg_mask, fg_mask); 
    bg_mask = bg_mask/255.0;
    fg_mask = fg_mask/255.0;

    int k= 9;
    cv::GaussianBlur(bg_mask, bg_mask, cv::Size(k,k), 7);
    cv::GaussianBlur(fg_mask, fg_mask, cv::Size(k,k), 7);
    
    // //create bg image = image*bgmask
    cv::Mat bg_image;
    cv::multiply(background,bg_mask, bg_image);

    // //create fg image = image*fgmask
    cv::Mat fg_image;
    cv::multiply(input_mat,fg_mask, fg_image);

    cv::Mat output_image;
    cv::add(fg_image, bg_image, output_image);

    LOG(INFO) << "Creating output image Success!";
    std::unique_ptr<ImageFrame> output_frame(
        new ImageFrame(input_img.Format(), input_img.Width(), input_img.Height()));

    cv::Mat output_mat = formats::MatView(output_frame.get());

    output_image.copyTo(output_mat);
    cc->Outputs().Tag("OUTPUT_VIDEO").Add(output_frame.release(), cc->InputTimestamp());

    LOG(INFO) << "Background Replacement Success!";
    return ::mediapipe::OkStatus();
    }
    REGISTER_CALCULATOR(::mediapipe::BackgroundMaskingCalculator);}

and this is the graph file in selfie_segmentation_cpu.pbtxt

```
input_stream: "input_video"
input_side_packet: "MODEL_SELECTION:model_selection"
output_stream: "output_video"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:segmentation_mask"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node {
  calculator: "SwitchContainer"
  input_side_packet: "SELECT:model_selection"
  input_stream: "IMAGE:input_video"
  output_stream: "TENSORS:input_tensors"
  options: {
    [mediapipe.SwitchContainerOptions.ext] {
      select: 0
      contained_node: {
        calculator: "ImageToTensorCalculator"
        options: {
          [mediapipe.ImageToTensorCalculatorOptions.ext] {
            output_tensor_width: 256
            output_tensor_height: 256
            keep_aspect_ratio: false
            output_tensor_float_range {
              min: 0.0
              max: 1.0
            }
            border_mode: BORDER_ZERO
          }
        }
      }
      contained_node: {
        calculator: "ImageToTensorCalculator"
        options: {
          [mediapipe.ImageToTensorCalculatorOptions.ext] {
            output_tensor_width: 256
            output_tensor_height: 144
            keep_aspect_ratio: false
            output_tensor_float_range {
              min: 0.0
              max: 1.0
            }
            border_mode: BORDER_ZERO
          }
        }
      }
    }
  }
}

node {
  calculator: "PreviousLoopbackCalculator"
  input_stream: "MAIN:throttled_input_video"
  input_stream: "LOOP:segmentation_mask"
  input_stream_info: {
    tag_index: "LOOP"
    back_edge: true
  }
  output_stream: "PREV_LOOP:previous_segmentation_mask"
}

node {
  calculator: "SetAlphaCalculator"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "ALPHA:previous_segmentation_mask"
  output_stream: "IMAGE:mask_embedded_input_video"
}

node {
  calculator: "TfLiteCustomOpResolverCalculator"
  output_side_packet: "OP_RESOLVER:op_resolver"
}

node {
  calculator: "SelfieSegmentationModelLoader"
  input_side_packet: "MODEL_SELECTION:model_selection"
  output_side_packet: "MODEL:model"
}

node {
  calculator: "InferenceCalculator"
  input_stream: "TENSORS:input_tensors"
  output_stream: "TENSORS:output_tensors"
  input_side_packet: "MODEL:model"
  input_side_packet: "OP_RESOLVER:op_resolver"
  options: {
    [mediapipe.InferenceCalculatorOptions.ext] {
      delegate {
        xnnpack {}
      }
    }
  }
}

node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE_CPU:input_video"
  output_stream: "SIZE:input_size"
}

node {
  calculator: "TensorsToSegmentationCalculator"
  input_stream: "TENSORS:output_tensors"
  input_stream: "OUTPUT_SIZE:input_size"
  output_stream: "MASK:mask_image"
  options: {
    [mediapipe.TensorsToSegmentationCalculatorOptions.ext] {
      activation: NONE
    }
  }
}

node: {
  calculator: "FromImageCalculator"
  input_stream: "IMAGE:mask_image"
  output_stream: "IMAGE_CPU:segmentation_mask"
}

node {
  calculator: "BackgroundMaskingCalculator"
  input_stream: "IMAGE_CPU:mask_embedded_input_video"
  input_stream: "MASK_CPU:segmentation_mask"
  output_stream: "OUTPUT_VIDEO:output_video"
}



```

But this isn't working out for some reason, could anyone correct the mistakes? or guide me the correct possible way?

**Comment by kuaashish** [comment]
Hi @kishor-e,
Is it implemented through Python, JavaScript or other solutions available? Could you please help us to understand the issue better from our end. Thank you!

**Comment by kishor-e** [comment]
Hi @kuaashish, thanks for the reply! 
I am implementing the required changes in mediapipe source code itself.

Since running the Selfie Segmentation in desktop(windows 11) gives the background color as blue, I want to set the background to an image.

![man15](https://user-images.githubusercontent.com/60582659/203955232-9543e4ce-9ba5-4996-8f18-e084bbf0b1c5.jpg)


So, to Replace the background to an image, I've used a custom calculator for which I shared the code snippet in the above comment.

The node calling this calculator is 

```
node {
  calculator: "BackgroundMaskingCalculator"
  input_stream: "IMAGE_CPU:mask_embedded_input_video"
  input_stream: "MASK_CPU:segmentation_mask"
  output_stream: "OUTPUT_VIDEO:output_video"
}

``` 
The graph file used is also shared above. When i run this, the output windows crashes. Somehow the problem lies in graph file, could you guide me in making changes to it, so that it works.
