### ISSUE TITLE
Mediapipe for iOS building error

### ISSUE THREAD

**Issue by yyzhao78** [google/mediapipe#3885]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution ( iOS 14.4):
- Programming Language and version ( Python 3.7.3 ):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:(5.3.2)
- XCode (14.0.1)and Tulsi versions(0.2022) :

**Describe the problem**:
according to ”https://google.github.io/mediapipe/getting_started/ios.html “,I built the xcode project with tulsi。My project with xcode build HelloWorldApp failed，The error prompt is as follows:

**************
/Users/yaozhao/mediapipe/mediapipe/gpu/BUILD:472:13: Middleman _middlemen/mediapipe_Ugpu_Umetal_Ushared_Uresources-Objc_build_arch_ios-arm64-min11.0-applebin_ios-ios_arm64-dbg-ST-2967bd56a867_with_suffix__non_objc_arc failed: missing input file '//mediapipe/gpu:metal_shared_resources.h'

/Users/yaozhao/mediapipe/mediapipe/gpu/BUILD:472:13: Middleman _middlemen/mediapipe_Ugpu_Umetal_Ushared_Uresources-Objc_build_arch_ios-arm64-min11.0-applebin_ios-ios_arm64-dbg-ST-2967bd56a867_with_suffix__non_objc_arc failed: 1 input file(s) do not exist

Aspect @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_outputs_aspect of //mediapipe/examples/ios/helloworld:HelloWorldApp up-to-date:

  bazel-out/applebin_ios-ios_arm64-dbg-ST-2967bd56a867/bin/mediapipe/examples/ios/helloworld/HelloWorldApp.tulsiouts

/Users/yaozhao/mediapipe/mediapipe/gpu/BUILD:472:13: Middleman _middlemen/mediapipe_Ugpu_Umetal_Ushared_Uresources-Objc_build_arch_ios-arm64-min11.0-applebin_ios-ios_arm64-dbg-ST-2967bd56a867_with_suffix__objc_arc failed: missing input file '//mediapipe/gpu:metal_shared_resources.h'

/Users/yaozhao/mediapipe/mediapipe/gpu/BUILD:472:13 Middleman _middlemen/mediapipe_Ugpu_Umetal_Ushared_Uresources-Objc_build_arch_ios-arm64-min11.0-applebin_ios-ios_arm64-dbg-ST-2967bd56a867_with_suffix__non_objc_arc failed: 1 input file(s) do not exist
*******************************************

At the same time, I found that under the project directory tree, metal_ shared_ resources. H and metal_ shared_ Resources.mm These two file projects refer to, but they do not exist.

How can i do？

Thanks a lot！

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/119038017/203935976-242247e6-a098-4e13-879b-1689506480a2.png">

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment]
Hi @yyzhao78,
Could you please confirm that MacOS processor types such as M1, M2 or Intel? and let us know if you have successfully built the MediaPipe as mentioned [here](https://google.github.io/mediapipe/getting_started/ios.html#prerequisite) before building the ios hello_world example. Thank you!

**Comment by yyzhao78** [comment]
Hi ，thanks for your reply！
The processor is Intel！
Now，I can not build the HelloWorldApp！
The errors are followed：
[image: image.png]

**Comment by yyzhao78** [comment]
I have built Tulsi App successfully and generated the MediaPipe project
successfully。
[image: image.png]
Do I have any missing steps?

Thanks and Regards！

**Comment by kuaashish** [comment]
Hi @yyzhao78,
Glad to know you have successfully generated the MediaPipe project in the Tulsi App. However, Could you please let us know what do you mean by the missing steps. Thank you!

**Comment by test524** [comment]
@kuaashish  Im facing same issue 
OS Platform : MacOS Monterey  12.6
Processor: M1 
Bazel version: 5.3.2
Programming Language and version: Python 3.10.8 
Im trying to Run this command 
bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp
<img width="1552" alt="Screenshot 2022-11-30 at 8 56 57 AM" src="https://user-images.githubusercontent.com/23077610/204719164-f55f6fe1-8959-4c7c-9a50-b84f57176936.png">

**Comment by kuaashish** [comment]
Hi @test524,
Unfortunately, MediaPipe does not support the Apple Silicon chip such as M1 and M2. We still do not have native Python wheels and can be run Python under Rosetta. Thank you!

**Comment by yyzhao78** [comment]
> Hi @test524,
> Unfortunately, MediaPipe does not support the Apple Silicon chip such as M1 and M2. We still do not have native Python wheels and can be run Python under Rosetta. Thank you!

Hi @kuaashish 
Thanks your reply！
It's the version of git clone mediapipe，I downgrade the version of mediapipe
Then i can build successfully and run on iPhoneX successfully!
However, a new problem occurred. I tried to modify the posttrackingGpuApp. I added an MFMailComposeViewController in the project. The following error occurred！

<img width="901" alt="image" src="https://user-images.githubusercontent.com/119038017/204760514-4dbf5227-4d12-410e-b211-048399a54dea.png">

The project's settting is below
<img width="949" alt="image" src="https://user-images.githubusercontent.com/119038017/204761497-b28be97e-df68-48f8-92e8-ce109654281a.png">

After commenting the MFMailComposeViewController code, everything is OK again!

**Comment by yyzhao78** [comment]
I have found the settings  in  "common " --- "build" file。
<img width="293" alt="image" src="https://user-images.githubusercontent.com/119038017/204956936-cb145ece-04f6-4c2a-912f-81c475262340.png">
that 's OK！

**Comment by yyzhao78** [comment]
> Hi @test524,
> Unfortunately, MediaPipe does not support the Apple Silicon chip such as M1 and M2. We still do not have native Python wheels and can be run Python under Rosetta. Thank you!

Hi: @kuaashish 
I can run this app on iPhoneX successfully , I what to archive the IPA,but i got  errors :
<img width="759" alt="image" src="https://user-images.githubusercontent.com/119038017/204968686-fdeaf1a5-9206-44ee-b358-f8832e72f57c.png">

the PoseTrackingGpuApp 12-1-22, 12.52 PM.xcarchive file is null（1kb）, After  I distributed App the error prompt is as follows:
<img width="745" alt="image" src="https://user-images.githubusercontent.com/119038017/204969235-4ebfacb3-0554-4447-88bb-165232258c72.png">
thanks a lot！

**Comment by kuaashish** [comment]
Hi @yyzhao78,
You can try the workaround as mentioned here [#133 (Comment)](https://github.com/google/mediapipe/issues/133#issuecomment-1049678841) w.r.t the above error and please let us know if the issue still persists. Thank you!

**Comment by doctor-xray** [comment]
Hello I have the same Error, how I can build on my M1 Pro?
What I must change?!

ERROR: /Users/don/Projects/mediapipe/mediapipe/gpu/BUILD:484:13: Middleman _middlemen/mediapipe_Ugpu_Umetal_Ushared_Uresources-Objc_build_arch_ios-arm64-min11.0-applebin_ios-ios_arm64-opt-ST-2967bd56a867_with_suffix__objc_arc failed: missing input file '//mediapipe/gpu:metal_shared_resources.h'
ERROR: /Users/don/Projects/mediapipe/mediapipe/gpu/BUILD:484:13: Middleman _middlemen/mediapipe_Ugpu_Umetal_Ushared_Uresources-Objc_build_arch_ios-arm64-min11.0-applebin_ios-ios_arm64-opt-ST-2967bd56a867_with_suffix__objc_arc failed: 1 input file(s) do not exist
Target //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/don/Projects/mediapipe/mediapipe/gpu/BUILD:484:13 Middleman _middlemen/mediapipe_Ugpu_Umetal_Ushared_Uresources-Objc_build_arch_ios-arm64-min11.0-applebin_ios-ios_arm64-opt-ST-2967bd56a867_with_suffix__objc_arc failed: 1 input file(s) do not exist
INFO: Elapsed time: 1.046s, Critical Path: 0.18s
INFO: 29 processes: 29 internal.
FAILED: Build did NOT complete successfully

**Comment by kuaashish** [comment]
Hi @yyzhao78,
This issue has been fixed in [commit](https://github.com/google/mediapipe/commit/b0b38a0013c819a6db4156330cbbe2e0dab11bd8). Could you verify and update the status?

**Comment by kuaashish** [comment]
@doctor-xray,
Could you try now this issue has been fixed commit as mentioned and let us know if can build the iOS example on M1 pro?
