### ISSUE TITLE
Using Face-Mesh solution on a video-track from Agora.io (JavaScript)

### ISSUE THREAD

**Issue by hrshmllw** [google/mediapipe#3886]
Is it possible to use a video-track from Agora and apply the Face-mesh solution to it?

I'm having problems since the Agora video track already uses the web-camera and I can't get them to function both.

**Comment by kuaashish** [comment]
Hi @hrshmllw,
Since this is a third party service, allow us some time to find the feasibility of incorporating MediaPipe into the camera output of Agora. Thank you!

**Comment by kuaashish** [comment]
@hrshmllw,

We do not provide the support for third-party frameworks, And not in our roadmap to include/configure/test external framework.
