### ISSUE TITLE
Mediapipe hands JavaScript doesn't work on iOS devices, but it works on Android, Windows. 

### ISSUE THREAD

**Issue by Narottam04** [google/mediapipe#3887]
**System information** (Please provide as much relevant information as possible)
- Have I written custom code : **Yes** 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): **iOS**
- Solution : **Hands**
- Programming Language and version:  **JavaScript**

**Describe the expected behavior:**
The Mediapipe hands is not working on iOS, but it works on Android, Windows, and other platforms. My goal is to have the canvas take up the entire screen width and height without losing responsiveness of camera.

Here's the hosted website: https://signlanguage.webdrip.in/app/playnumbers/

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

Github Gist of the problem: https://gist.github.com/Narottam04/9d3383270101c69a6fd6389f589163a8
Github Repo: https://github.com/Narottam04/SignLanguage/tree/master/frontend

**Comment by kuaashish** [comment]
Hi @Narottam04,
Would you please also list out the browsers and iOS version you are testing this on? Thank you!

**Comment by Narottam04** [comment]
I have tested on 
iOS version: 15, 16
Browsers: Safari and ios Chrome

The mediapipe hands codepen works properly on both versions. Additionally, I was able to run the hands demo, but when I tried to make the canvas take up the entire screen width and height, I encountered issue where it will only show white screen.

When I tried to debug, I think the problem arises on following lines (Linked repo and gist on the issues above). I tried to find a solution, but nothing worked.

`// Get Video Properties
      const videoWidth = videoElement.videoWidth
      const videoHeight = videoElement.videoHeight
    
      // set video width
      videoElement.width = videoWidth
      videoElement.height = videoHeight
    
    
      // Set canvas width and height
      canvasElement.width = videoWidth 
      canvasElement.height = videoHeight 
      
      canvasCtx.save();
      canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
      canvasCtx.drawImage(
          results.image, 0, 0, canvasElement.width, canvasElement.height);`

![error](https://user-images.githubusercontent.com/74066540/204460347-bc5cab6d-a5d3-46c1-a376-fa2b95c78408.jpeg)

**Comment by ayushgdev** [comment]
Hello @Narottam04 
We are building a set of new, improved [MediaPipe Solutions](https://developers.google.com/mediapipe/solutions) to help you more easily build and customize ML solutions for your applications. We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) and upgrading others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you tto migrate your code to the new APIs(check out the new [gesture recognition solution](https://mediapipe-studio.webapps.google.com/demo/gesture_recognizer)). Once migration is done, please check if this issue still persists. If so, please let us know and we would be available in a prompt to support your queries.
