### ISSUE TITLE
The computation time of Mediapipe solution: Pose varied with minimum confidence

### ISSUE THREAD

**Issue by crapper** [google/mediapipe#3888]
<em>Please make sure that this is a [Pose](https://google.github.io/mediapipe/solutions/pose) issue.<em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):
````
import os
from turtle import color
import cv2
from cv2 import circle
import mediapipe as md
import numpy as np
import time
import json
import math
from scipy.spatial import distance


md_drawing = md.solutions.drawing_utils
md_drawing_styles = md.solutions.drawing_styles
md_pose = md.solutions.pose

frame_count = 0
total_fps = 0
count = 0
position = None
filedir = r"C:\Users\DanielFung\Desktop\fyp\testset\coco2017\1_new"
flist = os.listdir(filedir)
flist.sort()
waitingtime = [0]
starttime = time.time()
#"keypoints": [
# "nose",
# "left_eye",
# "right_eye",
# "left_ear",
# "right_ear",
# "left_shoulder",
# "right_shoulder",
# "left_elbow",
# "right_elbow",
# "left_wrist",
# "right_wrist",
# "left_hip",
# "right_hip",
# "left_knee",
# "right_knee",
# "left_ankle",
# "right_ankle"],
count = 0
extract = [0, 2, 5, 7, 8, 11, 12, 13, 14, 15, 16, 23, 24, 25, 26, 27, 28]
with md_pose.Pose(
    min_detection_confidence = 0.5,
    static_image_mode = True
) as pose:
        for i in range(0, 2000):
            if flist[i].endswith(".jpg"):
                count+=1
                print(count)
                framestart = time.time()
                frame = cv2.imread(os.path.join(filedir, flist[i]))
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                # frame = cv2.flip(frame, 0)
                results = pose.process(frame)
                frameend = time.time()
                waitingtime.append(frameend - framestart)
totaltime = time.time() - starttime
with open(r"C:\Users\DanielFung\Desktop\fyp\py\Experiment1\0.5MediapipeTime.txt", "a+") as f:
    f.write("Total time: "+str(totaltime)+ "\n")
    f.write("FPS: "+str(1000/totaltime)+ "\n")
    sum = 0
    for item in range(1, len(waitingtime)-1):
        sum += waitingtime[item]
    f.write("Average waiting time: "+str(sum/(len(waitingtime)-2))+ "\n")
    for item in waitingtime:
        f.write("%s\n" % str(item))
````

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Window 11
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.11
- Solution (e.g. FaceMesh, Pose, Holistic): Pose
- Programming Language and version ( e.g. C++, Python, Java): Python
**Describe the issue**
I try to perform a comparison experience on Mediapipe Blazepose performance in computation time with python on a 1000 single person image from COCO, however I found that when the computation time will varied with the minimum confidence. Is this mean for mediapipe, if it found a body point is having confidence below the minimum confidence, it will just terminte and return with none, thats why the computation time be better when the min-confidence is larger?

The computation time for minimum confidence 0, 0.5 and 1 result as follows:

Total time: 173.26513504981995 #for min confidence value 0
FPS: 5.771501575966013

Total time: 91.70882368087769 #for min confidence value 0.5
FPS: 10.904076182241024

Total time: 48.397177934646606 #for min confidence value 1
FPS: 20.662361787919856

As shown, the time almost 4 time faster when the minimun confidence is 1. Is there any reason for this?

**Comment by ayushgdev** [comment]
Hi @crapper 
`min_detection_confidence` allows the graph to discard some detections "early" and avoid some processing for those detections. This helps in narrowing down the probable candidates to process through the series of graph networks.  
Often thresholds are used to optimize processing by limiting the number of entities or ROI's tracked and we are using the same here.

**Comment by crapper** [comment]
> Hi @crapper `min_detection_confidence` allows the graph to discard some detections "early" and avoid some processing for those detections. This helps in narrowing down the probable candidates to process through the series of graph networks. Often thresholds are used to optimize processing by limiting the number of entities or ROI's tracked and we are using the same here.

Thank you for you reply, but may I ask why such a situation will happen when I check the length of keypoints (xy) will be 66. But while the actual drawn point only contain the top half of the body?

![image](https://user-images.githubusercontent.com/26902835/214019800-c77ea229-e10e-42bd-8294-a4e26c6ee10b.png)
