### ISSUE TITLE
How can I extract landmarks from an image of the arm with the mediapipe?

### ISSUE THREAD

**Issue by Woong0416** [google/mediapipe#3889]
Hello first of all thank you for reading my question. I am trying to derive a new landmark as a landmark by recognizing the arm as shown in the image below. However, even if Pose or holistic is used, there are many cases where landmarks cannot be pulled out well when only the arm comes out alone, so I would like to ask how to do it. Any help would be appreciated.
![스크린샷 2022-11-28 오후 1 09 18](https://user-images.githubusercontent.com/99726996/204192227-b654e3cc-0e5b-4407-a7ce-2c63acebd42a.png)

![그림1](https://user-images.githubusercontent.com/99726996/204192385-34d7cea2-a637-47cb-8b6b-9a694d9987cb.png)

**Comment by kuaashish** [comment]
Hi @Woong0416,
From the images provided, it can be seen that the model suffers to detect the arm in cases where only a part of arm is visible. Unfortunately, this will be a case where custom model training can help.
In our soltuion for realtime detection and tracking of the person in frame, we focus on detecting the bounding box of a relatively rigid body part like the human face or torso. Thus, if torso (or a part of it )is not visible, it is having hard time detection the arm. Further, quoting from the [paper](https://arxiv.org/pdf/2006.10204.pdf)

> We restrict our dataset to those cases where either the whole person is visible, or where hips and shoulders keypoints can be confidently annotated.

Please refer the research paper in this [model card](https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview) more details how the pose detection works. This might give a clue to develop custom solution. Thank you!

**Comment by Woong0416** [comment]
Thankyou @kuaashish 
Your answer has been of great help. Thank you. So is it possible to customize the Mediapipe ? Or do I have to create a new pose estimation model?

**Comment by kuaashish** [comment]
Hi @Woong0416,
For python you can create your own graph using the calculators and execute as mentioned here https://google.github.io/mediapipe/getting_started/python_framework.html#graph if using the other platforms we believe a new training will be required. Thank you!

**Comment by arianatri** [comment]
> Hi @Woong0416, For python you can create your own graph using the calculators and execute as mentioned here https://google.github.io/mediapipe/getting_started/python_framework.html#graph if using the other platforms we believe a new training will be required. Thank you!

Am I allowed to train a custom model to keypoint somthing like fingernails using mediapipe model?

**[here](https://github.com/google/mediapipe/issues/2123#issuecomment-974152958)** says I cant!
am I missing something?
