### ISSUE TITLE
Hand Tracking App shows only black screen on LineageOS

### ISSUE THREAD

**Issue by marvin21** [google/mediapipe#389]
I build the apk for the hand tracking example and wanted to run it on an Oneplus One with LineageOS 16 installed. The application itself starts without a problem, but the camera does not open, the screen remains black. There is no error message displayed and the app does not crash.  Tried to figure out if there are any error messages with `adb logcat`, but without results.

Has anyone an idea if LineageOS fails to meet any prerequisites to run Mediapipe?

**Comment by jiuqiant** [comment]
Could you test [the face detection cpu example](https://github.com/google/mediapipe/blob/master/mediapipe/docs/face_detection_mobile_cpu.md) on LineageOS? This can help us understand if the problem is gpu related or not.

**Comment by marvin21** [comment]
I tested the face detection cpu example and it worked without a problem, my face was detected via the front camera.

**Comment by jiuqiant** [comment]
If the CPU demo works well, it means that the MediaPipe framework as well as TFLite CPU and OpenCV work on LineageOS. Then, it might be a TFLite GPU and/or OpenGL related issue. Can you test the real-time sobel edge detection as well? If it also works, I highly doubt that it's a pure TFLite GPU issue. Here is the build command to build the sobel edge detection app:
```
bazel build -c opt  --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu:edgedetectiongpu
```

BTW, what's the GPU of your hardware? It's also worthwhile to see if it supports OpenGL ES 3.1 and up. See https://github.com/google/mediapipe/issues/341#issuecomment-569334484.

**Comment by marvin21** [comment]
The edge detection also runs without a problem.
As you mentioned the GPU, I checked the version and it seems like the Qualcomm Adreno 330 does only supports OpenGL ES until 3.0, but no further versions. So I think this might cause the problem here.

Anyway, thank you for your quick support!

**Comment by jiuqiant** [comment]
Welcome!
