### ISSUE TITLE
Cross-Compilation on QNX with GCC-v5.4.0

### ISSUE THREAD

**Issue by barisbatuhan** [google/mediapipe#3890]
While trying to cross-compile Mediapipe for QNX, I have seen in several places that Mediapipe requires c++17 and gcc >= 8.

1) Is there any way to compile Mediapipe with gcc 5.4.0 and c++14? Is there any old version that supports this configuration? 

2) Is there any guide or work that successfully cross-compiles Mediapipe for QNX?

Thank.s

**Comment by kuaashish** [comment]
Hi @barisbatuhan,
MediaPipe default compiler version is c++17 that is specified in .bazelrc file. However, older mediapipe versions have default compiler version c++14, in versions 0.6.4 to 0.8.0. 
To manually set up a compiler in build command, you can use --cxxopt flag like --cxxopt='-std=c++17'. Please refer to the bazel [documentation](https://bazel.build/docs/user-manual#cxxopt) for more details. 
MediaPipe has been test successfully on these edges devices such as Raspberry Pi & Coral Dev Board as mentioned [here ](https://github.com/google/mediapipe/tree/master/mediapipe/examples/coral) in guide. Thank you!
