### ISSUE TITLE
How to get iris and refined eye landmark coordinates from Mediapipe Iris C++

### ISSUE THREAD

**Issue by monkeygobah** [google/mediapipe#3891]
- Have I written custom code: No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Mac M1 BigSur
- Bazel version: 5.3.2
- Solution: Iris
- Programming Language and version: C++

**Describe the expected behavior:**

C++ noob here. I am working on a project where I need to get the landmarks of the iris and refined eye mapping from mediapipe iris in C++. I have referred to #1177, but that does not seem to work on a static image. Everything works and I can get the output tracings which look great, but I cannot figure out how to get the landmarks from the code. I cannot share the pictures due to privacy concerns, but in essence I want to get the xyz coordinates of the analyzed image (see image) and store them in a txt file or some format which I can then use later.

<img width="663" alt="image" src="https://user-images.githubusercontent.com/117255104/204439484-4e569de9-fa7a-417d-b13f-6c0ba5531975.png">

My current solution is just to extract the tracings by color and regenerate them in Python after Mediapipe has finished, but I feel like there has to be a better way. Any help is appreciated! Thank you so so so much and let me know if you need any more info.

**Comment by kuaashish** [comment]
@monkeygobah,
Sorry for the late response, Would you please let us know if you are still looking for the resolution or the issue has been resolved from you end? Thank you!

**Comment by monkeygobah** [comment]
Hi- sorry for my late reply as well. I did not find a resolution within mediapipe but solved the problem by changing the color of the R and L eyelid tracings and then extracting them later in python. It is not the best solution as I would rather just have the indexed points, but it does work well enough for now. If there is a way to get the real coordinates out, though, I would love to know!

**Comment by kuaashish** [comment]
Hi @gkarpiak,
Could you please look into this issue? Thank you!

**Comment by kuaashish** [comment]
Hello @monkeygobah,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
