### ISSUE TITLE
Get Real World coordinates in meters

### ISSUE THREAD

**Issue by ridasaleem0** [google/mediapipe#3892]
Hi, I'm working on the "pose_world_landmarks" to get the real-world coordinates in meters. I was able to capture the true depth values of the x and y axis in my camera coordinate system using the following snippet but I am unable to get the z-axis. 

`            x_coord = pose_landmarks.x * frame_width
`
`            y_coord = pose_landmarks.y * frame_height
`

Any leads would be appreciated.

**Comment by ridasaleem0** [comment]
@sgowroji

**Comment by leochocolat** [comment]
If I understood the docs correctly the z position is based on the geometrical center of the pose so not usable for world z position. 
The trick I tried is calculating the x,y distance between the 2 points of the mouth, the larger that distance is the closer the subject is from the camera. It's super hacky but can work in some cases.

**Comment by kuaashish** [comment]
Hi @ridasaleem0,
Is it implemented through the Python, JavaScript or other solutions available? 
Could you help us to understand the issue better and steps followed to reproduce the issue from our end. Thank you!

**Comment by ridasaleem0** [comment]
@kuaashish Thank you for your response. 

Currently, I am utilizing Python's "pose_world_landmarks" function to get to the 3D pose points. I am able to convert the x and y axis into actual real-world coordinates according to my camera width/height rather than using the normalized values that the API returns. However, I am not sure how we can get the z-axis in the same way? Any help on that side would be appreciated.

Previously I was using Mediapipe's 2d pose landmarks function to get pose points and then using a depth camera to transform them into real-world 3d coordinates. However, I want to replace my depth camera with an off-the-shelf RGB camera and use Mediapipe's "pose_world_landmarks" function to get those depth values.

**Comment by kuaashish** [comment]
Hi @ridasaleem0,
The MediaPipe pose model provides z-keypoint which is an "estimate" from the GHUM model using 2D projecctions. The z-keypoint represents the distance "relative" to the plane of the subject's hips, which is the origin of the Z axis. So you can imagine a vertical place at the hip joint of the subject and any value <0 represents distance between camera and person.
So you can filter out negative valued z-keypoints to know if a key-point is between camera and hip or beyond. However, as the distance is relative, it cannot be used to reliably estimate  metric distance of real world. For details, please refer the model card [here](https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview). Thank you!
