### ISSUE TITLE
Select BlazePose model (converted tflite to edge_tpu tflite) without model_complexity

### ISSUE THREAD

**Issue by MarioCavero** [google/mediapipe#3894]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Mendel Linux (Debian 10.0)
- [MediaPipe version](https://github.com/google/mediapipe/releases): mediapipe-0.8.11
- Solution (e.g. FaceMesh, Pose, Holistic): Pose
- Programming Language and version ( e.g. C++, Python, Java): Python

**Describe the expected behavior:**
I installed and run some inferences via Blazepose on the Google Coral. As it is for CPU only (Did not see there was a way to compile it for TPU, although it seems that the steps given are for a usb accelerator?). I converted the tflite model to a tflite_edgetpu model. I was wondering if there is a way to select a model to run inferences that is not followed by the following structure:
```
with mp_pose.Pose(
    static_image_mode=True,
    model_complexity=0,
	    enable_segmentation=False,
    min_detection_confidence=0.5) as pose:

```
`model_complexity` selects one of the three models that Mediapipe has (downloads them if not found). I was wondering if there is a specific way to select another model (in my case, the same pose model, but it is for tpu, already compiled). The models are stored in: `/usr/local/lib/python3.7/dist-packages/mediapipe/modules/pose_landmark`
**Standalone code you may have used to try to get what you need :**
```
import cv2
import mediapipe as mp
import glob
import numpy as np
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_pose = mp.solutions.pose
# For static images:
IMAGE_FILES = glob.glob('/home/mendel/blaze_test_images/*.jpg')
BG_COLOR = (192, 192, 192) # gray
with mp_pose.Pose(
    static_image_mode=True,
    model_complexity=0,
	    enable_segmentation=False,
    min_detection_confidence=0.5) as pose:
  for idx, file in enumerate(IMAGE_FILES):

    image = cv2.imread(file)
    image_height, image_width, _ = image.shape
    # Convert the BGR image to RGB before processing.
    results = pose.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    if not results.pose_landmarks:
      continue
    annotated_image = image.copy()
    # Draw segmentation on the image.
    # To improve segmentation around boundaries, consider applying a joint
    # bilateral filter to "results.segmentation_mask" with "image".
    ##condition = np.stack((results.segmentation_mask,) * 3, axis=-1) > 0.1
    ##bg_image = np.zeros(image.shape, dtype=np.uint8)
    ##bg_image[:] = BG_COLOR
    ## annotated_image = np.where(condition, annotated_image, bg_image)
    # Draw pose landmarks on the image.
    before_drawing_time = time.time()
    mp_drawing.draw_landmarks(
        annotated_image,
        results.pose_landmarks,
        mp_pose.POSE_CONNECTIONS,
        landmark_drawing_spec=mp_drawing_styles.get_default_pose_landmarks_style())
    after_drawing_time = time.time()
#    print(f'Saving image! Drawing done in {after_drawing_time - before_drawing_time}')
    cv2.imwrite('/home/mendel/blaze_test_images/' + str(idx) + '.png', annotated_image)
    # Plot pose world landmarks.
    mp_drawing.plot_landmarks(
        results.pose_world_landmarks, mp_pose.POSE_CONNECTIONS)
```

**Comment by abymmathew-mli** [comment]
There is a sample of how to proceed using calculator graphs. However, the solution is c++.

https://github.com/google/mediapipe/tree/master/mediapipe/examples/coral

I haven't tried, but will over the weekend. If you have success please post, since it will be helpful mutually.

**Comment by kuaashish** [comment]
Hello @MarioCavero,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you!
