### ISSUE TITLE
How to use the ML solution of Iris Depth and Hands simultaneously in MediaPipe?

### ISSUE THREAD

**Issue by xxxneo000** [google/mediapipe#3895]
We need to create a MediaPipe project on iOS, which uses the front-camera of the iPhone to run iris depth and hands recognition at the same time.

Specific usage scenarios:
We need to run a small game, in which we can track the iris and obtain the iris depth, and recognize hands gestures.

Real time input:
Live video streaming from iPhone front-camera

Real time output:
1. Processed video stream (original resolution, no content is rendered)
2. The position of the iris center point of the left eye (screen coordinate system)
3. The position of the iris center point of the right eye (screen coordinate system)
4. left_ iris_ depth_ mm
5. right_ iris_ depth_ mm
6. The position of 21 bone points in the hand (screen coordinate system)

Question:
How to create a “. pbtxt” in the MediaPipe Visualizer, which can simultaneously run iris depth and hands recognition?

**Comment by ayushgdev** [comment]
Hello @xxxneo000 
Please allow us sometime to ponder upon the solution and provide some pointers to your query.

**Comment by xxxneo000** [comment]
> 

OK，thanks very much

**Comment by xxxneo000** [comment]
@ayushgdev OK，thanks very much.

**Comment by xxxneo000** [comment]
@ayushgdev Is there a solution that uses both frameworks in MediaPipe?

**Comment by ayushgdev** [comment]
@xxxneo000 no there is no ready to use solution in MediaPipe framework. But to address your query, we are working to produce such a graph. We really appreciate your patience.

**Comment by xxxneo000** [comment]
> @xxxneo000 no there is no ready to use solution in MediaPipe framework. But to address your query, we are working to produce such a graph. We really appreciate your patience.

OK.We also need FaceGeometry and Hands simultaneously in MediaPipe?

**Comment by ayushgdev** [comment]
Hello @xxxneo000 
Apologies for the late reply. We have discussed this internally and as much we would like to help on this front, we cannot provide a ready to use ".pbtxt" file at the moment. 
However, to provide you some pointers to get started with, you have to manually merge the graphs of [Iris Tracking](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/iris_tracking/iris_tracking_cpu.pbtxt) and [Hand Tracking](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/hand_tracking_desktop.pbtxt).
You can use the `ConcatenateNormalizedLandmarkListCalculator` to merge the landmarks predicted by MediaPipe. As an example, you can refer to [iris_tracking_cpu.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/iris_tracking/iris_tracking_cpu.pbtxt) which merges face landmarks and iris_landmarks.
There might be some inefficiencies as we might be running the same calculator twice.
Also to provide a heads up, we are planning to look into graph/solution merging APIs but there is no concrete timeline for delivery.
