### ISSUE TITLE
About face effect, How i can capture frame 

### ISSUE THREAD

**Issue by hopdd** [google/mediapipe#3897]
I want to get ByteBuffer from surfaceTexture . This surface is initialized in CameraXPreviewHelper and then passed down to C++ code. But i'm having a bit of trouble about getting out each frame whenever the surface is rendered . I'm thinking in two directions :

 1 . Use EGLContext from EglManager to use callback from ImageReader.OnImageAvailableListener when ever surface is rendered .

 2.  I believe that, in [effect_renderer_calculator.cc ](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/effect_renderer_calculator.cc) there are things that i need . 

How can i do？

Thanks a lot！

**Comment by kuaashish** [comment]
Hi @hopdd,
Please refer to this specific [#475(Comment)](https://github.com/google/mediapipe/issues/475#issuecomment-593785593) for better understanding on your query.
