### ISSUE TITLE
pip install mediapipe giving an old version of Mediapipe which fails with tutorials using new Mediapipe version

### ISSUE THREAD

**Issue by shreshtashetty** [google/mediapipe#3898]
Hi,

When I install Mediapipe through pip and then try to use it with the Python code on the [facemesh](https://google.github.io/mediapipe/solutions/face_mesh) tutorial page, it gives me a lot of errors. It turns out that pip installs an older version of Mediapipe because many of the files on the Mediapipe github are not in the pip version.

I tried copy pasting some files and lines of code here and there hoping to resolve the issue. My code finally ran without throwing in any errors, but `face_mesh.process()` doesn't give me anything for `results.multi_face_landmarks` (NoneType).

Any help?

**Comment by ayushgdev** [comment]
Hi @shreshtashetty 
Can you please provide an output of the command `pip install --force-reinstall mediapipe` which would allow us to look which version is installed in the system?

**Comment by shreshtashetty** [comment]
Hi,
Following is the output of `pip install --force-reinstall mediapipe`:
![mediapipe_pip_reinstall](https://user-images.githubusercontent.com/14017651/205555727-acd2c53a-d95b-46b8-a3f6-8d80d70085ea.jpg)

Also, when I tried to build mediapipe using `python3 setup.py bdist_wheel`, I get the following:
![build_mediapipe_error](https://user-images.githubusercontent.com/14017651/205555989-c9bb69c4-b9c4-4492-9b64-592b28459329.jpg)

**Comment by ayushgdev** [comment]
@shreshtashetty Looks like you are trying to install in an environment where tensorflow is already present. This is conflicting with other python packages. 
Can you please follow steps to create new environment and then install mediapipe as provided [here](https://google.github.io/mediapipe/getting_started/python.html#ready-to-use-python-solutions)?
Also we strongly encourage our users to simply run `pip install mediapipe` to use the ready-to-use solutions, more convenient and much faster.

**Comment by shreshtashetty** [comment]
@ayushgdev UPDATE: The reason `results.multi_face_landmarks` gives me a `NoneType` is that I used a 48x48 image from the FER+ dataset which was too small for the model to detect anything and I just needed to go with a bigger image. 

But even with just `pip install mediapipe` and a bigger image, I still get an error with the tutorials on the mediapipe page with `mp_face_mesh.FACEMESH_TESSELATION `. The pip installation of mediapipe doesn't have it, but the github version of it does, which is what the tutorials seem to be based on (correct me if I'm wrong).

Any idea how I could get around this discrepancy?

**Comment by ayushgdev** [comment]
@shreshtashetty Can you check if the code below runs in your system? This runs fine in a virtual environment setup  for mediapipe as per the documentation. 
```
import mediapipe, cv2
from mediapipe.python.solutions import drawing_styles, drawing_utils, face_mesh

cam = cv2.VideoCapture(0)
CONNECTION_STYLE = drawing_styles.get_default_face_mesh_tesselation_style()
CONNECTIONS = face_mesh.FACEMESH_TESSELATION

with face_mesh.FaceMesh(max_num_faces=1, min_detection_confidence=0.8, static_image_mode=False) as face_context:
    while cam.isOpened():
        success, img = cam.read()
        
        if success:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            results = face_context.process(img)

            # showing the image colors properly
            img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
            if results.multi_face_landmarks:
                for landmarks in results.multi_face_landmarks:
                    drawing_utils.draw_landmarks(img, landmark_list=landmarks, connections=CONNECTIONS, landmark_drawing_spec=None, connection_drawing_spec=CONNECTION_STYLE)
            
        cv2.imshow('Webcam footage', img)
        if cv2.waitKey(5) & 0xFF==27:
            cam.release()
            cv2.destroyAllWindows()
```

**Comment by shreshtashetty** [comment]
Hi, @ayushgdev 
This is the error I get:
```
File "../apps/mpTest.py", line 6, in <module>
    CONNECTIONS = face_mesh.FACEMESH_TESSELATION
AttributeError: module 'mediapipe.python.solutions.face_mesh' has no attribute 'FACEMESH_TESSELATION'
```

**Comment by ayushgdev** [comment]
Thank you @shreshtashetty 
Would you mind providing the exact steps you took to setup mediapipe so that we can reproduce the issue at our end? 
Suggested is the use of the [new issue template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=00-build-installation-issue.md) which can provide the necessary details to us to replicate the issue.

**Comment by Iamsakir** [comment]
same problem please give me a solution

**Comment by qwy1995** [comment]
excuse me , does anyone have the old version mediapipe whl ,Iinstall mediapipe == 0.10.5 tensorflow-gpu==2.10.1，but the protobuf vision can not satify both them，I want to try the old version mediapipe
