### ISSUE TITLE
yarn add @mediapipe/selfie_segmentation no longer works 

### ISSUE THREAD

**Issue by geoidesic** [google/mediapipe#3899]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Mac OS Ventura 13.0.1 (22A400)
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): dunno, not using it?
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): node -v 12.22.12
- Installed using virtualenv? pip? Conda? (if python): no
- [MediaPipe version](https://github.com/google/mediapipe/releases): @latest
- Bazel version: N/A
- XCode and Tulsi versions (if iOS): N/A
- Android SDK and NDK versions (if android): N/A
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): N/A
- OpenCV version (if running on desktop): huh?

**Describe the problem**:

Can no longer install this using yarn

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

'yarn add @mediapipe/selfie_segmentation produces an error

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

% yarn add @mediapipe/selfie_segmentation@latest
yarn add v1.22.19
[1/5]   Validating package.json...
[2/5]   Resolving packages...
[3/5]   Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@mediapipe/selfie_segmentation/-/selfie_segmentation-0.1.1632777926.tgz: incorrectdata check".

**Comment by geoidesic** [comment]
Also the same deal via npm:
```
% npm install @mediapipe/selfie-segmentation
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mediapipe%2fselfie-segmentation - Not found
npm ERR! 404
npm ERR! 404  '@mediapipe/selfie-segmentation@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/noeldacosta/.npm/_logs/2022-12-02T13_23_34_213Z-debug.log
```

**Comment by geoidesic** [comment]
I tried manually installing this version: 0.1.1657300547 and that worked but I got this:
```
[1/5]   Validating package.json...
[2/5]   Resolving packages...
warning @mediapipe/selfie_segmentation@0.1.1657300547: This version is not supported
```

Something has gone wrong with the npm repository for this package as the version that is considered current on npm is [0.1.1632777926](https://registry.yarnpkg.com/@mediapipe/selfie_segmentation/-/selfie_segmentation-0.1.1632777926.tgz] which does not exist in the package registry.

**Comment by ayushgdev** [comment]
Hello @geoidesic 
This issue is related to node version. In the details, it can be seen you are using node v12. Apple Mac M1 uses new ARM based CPU architecture which is only supported in node after v16 release. The release notes are attached [here](https://github.com/nodejs/node/releases/tag/v16.0.0).
