### ISSUE TITLE
HTMLImageElement exception

### ISSUE THREAD

**Issue by wheelie33** [google/mediapipe#3900]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):  Mac OS Ventura M1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Safari 16.1 (18614.2.9.1.12)
- Programming Language and version ( e.g. C++, Python, Java): Javascript
- [MediaPipe version](https://github.com/google/mediapipe/releases):  https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.4/pose.js
- Bazel version (if compiling from source): N/A
- Solution ( e.g. FaceMesh, Pose, Holistic ): Pose
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): N/A
- Xcode & Tulsi version (if issue is related to building for iOS): N/A

**Describe the current behavior:**

Trying to load an HtmlImageElement into the pose.send and it throws an unhandled exception:

[Error] Unhandled Promise Rejection: RuntimeError: abort(undefined) at jsStackTrace@https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.4.1633558788/pose_solution_wasm_bin.js:9:69350
stackTrace@https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.4...
	ua (pose.js:14:438)
	(anonymous function) (pose.js:15:192)
	e (pose.js:41:501)
	promiseReactionJob

**Describe the expected behavior:**
Should work just like a frame of web cam video

**Standalone code to reproduce the issue:**
Provide a reproducible test case that is the bare minimum necessary to replicate the problem. If possible, please share a link to Colab/repo link /any notebook:

https://gist.github.com/wheelie33/03499b02c60edbbedc4239a13f690cb7

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

**Comment by ayushgdev** [comment]
Hi @wheelie33 
Thanks for bringing attention to this issue. The issue is reproducible with the gist provided. 
Further, to add more context to this, the issue is not limited to image element. It is reproducible with the javascript pose demo provided in documentation. It throws same error when modelComplexity variable is not set explicitly, though as per documentation it is set to 1 by default. 
We shall look into this and prioritize it internally. However, as a workaround, please consider adding 
```
pose.setOptions({
   modelComplexity: 1
})
```
before `window.onload`. This would resolve your issue.

**Comment by wheelie33** [comment]
Awesome!  thank you.  The worked!  my next troubleshooting step was to start adding in a line by line until it worked.  This is great, thank you

**Comment by ayushgdev** [comment]
Glad your query was addressed. Can we mark issue to close status?

**Comment by wheelie33** [comment]
Yes!

**Comment by Neilblaze** [comment]
> Hi @wheelie33 Thanks for bringing attention to this issue. The issue is reproducible with the gist provided. Further, to add more context to this, the issue is not limited to image element. It is reproducible with the javascript pose demo provided in documentation. It throws same error when modelComplexity variable is not set explicitly, though as per documentation it is set to 1 by default. We shall look into this and prioritize it internally. However, as a workaround, please consider adding
> 
> ```
> pose.setOptions({
>    modelComplexity: 1
> })
> ```
> 
> before `window.onload`. This would resolve your issue.

@ayushgdev any update on when this is expected to roll out? Thanks! :)
