### ISSUE TITLE
ios example apps not building

### ISSUE THREAD

**Issue by frey1esm** [google/mediapipe#3901]
Osx 12.4 / xcode 13.4.1

mediapipe 
tulsi Version 0.20221005.88 (0.20221005.88)

- Bazel version: 5.2.0
- XCode and Tulsi versions (if iOS):

**Describe the problem**:

Trying to load an example ios app onto an iphone using the [MediaPipe on iOS tutorial.](https://google.github.io/mediapipe/getting_started/ios.html#create-an-xcode-project)

After running tulsi, xcode loads. I select an example app (e.g. PoseTrackingGpuApp) and select automatic signing and team.

Then I run `python3 mediapipe/examples/ios/link_local_profiles.py` in terminal in the mediapipe repo directory.

Then build.

Build fails with these errors:

`Creating symlink bazel-out/applebin_ios-ios_arm64-dbg-ST-2967bd56a867/bin/mediapipe/examples/ios/posetrackinggpu/PoseTrackingGpuApp-intermediates/embedded.mobileprovision failed: 1 input file(s) do not exist`

`Creating symlink bazel-out/applebin_ios-ios_arm64-dbg-ST-2967bd56a867/bin/mediapipe/examples/ios/posetrackinggpu/PoseTrackingGpuApp-intermediates/embedded.mobileprovision failed: missing input file '//mediapipe:provisioning_profile.mobileprovision'`

**Comment by kuaashish** [comment]
Hi @frey1esm,
Would you let us know if you have done [step 4 of the ios xcode setup](https://google.github.io/mediapipe/getting_started/ios.html#set-up-provisioning) to symlink your mobileprovision certificate as this file provisioning_profile.mobileprovision that the build process is looking for

> cd mediapipe
> ln -s ~/Downloads/MyProvisioningProfile.mobileprovision mediapipe/provisioning_profile.mobileprovision

If yes, then could you try to copy the mobileprovision file into mediapipe/mediapipe and rename it to provisioning_profile.mobileprovision?
