### ISSUE TITLE
In some cases I got 2 Left hands (or Right)

### ISSUE THREAD

**Issue by PavelAgurov** [google/mediapipe#3902]
I use mediapipe version 0.8.11 and Hands detection with settings:

    hands = mpHands.Hands(
                    static_image_mode= False, 
                    max_num_hands = 2,
                    min_detection_confidence= 0.8,
                    min_tracking_confidence = 0.8
            )

.....

        if results.multi_hand_landmarks:
            for handType, handLms in zip(results.multi_handedness, results.multi_hand_landmarks):
                mpDraw.draw_landmarks(img, handLms, mpHands.HAND_CONNECTIONS)
                print(handType)
            hand1_new = results.multi_hand_landmarks[0].landmark
            if len(results.multi_hand_landmarks) == 2:
                hand2_new = results.multi_hand_landmarks[1].landmark

Python, Windows, JupiterNotebook.

**Describe the current behavior:**
In some cases (when hand is visible as fist) I have 2 Left hands with good probabilities.
With Right hand it's also possible.

**Describe the expected behavior:**
I guess it should be only one Left hand if it's the same coords.

![2_left_hands](https://user-images.githubusercontent.com/37487002/205464526-d1cfb3ee-d0a6-4c9f-a54c-d5a7db17ff2b.png)

**Comment by kuaashish** [comment]
Hi @PavelAgurov,
Please allow us some time to share the any possible solution to the observation mentioned.

**Comment by kuaashish** [comment]
Hi @PavelAgurov,
Please allow us some time to share the any possible solution to the observation mentioned.

**Comment by PavelAgurov** [comment]
I can provide example(s) of input if needed.

**Comment by kuaashish** [comment]
@PavelAgurov,
Thanks for the reply!! Providing the example will be more helpful to understand the issue better from our end.

**Comment by PavelAgurov** [comment]
Please find data that was recognized as 2 Left hands with the same coords:

```
[landmark {
  x: 0.2769083
  y: 0.76771235
  z: -3.239203e-07
}
landmark {
  x: 0.2533634
  y: 0.802271
  z: -0.050840996
}
landmark {
  x: 0.23432064
  y: 0.8256263
  z: -0.09188586
}
landmark {
  x: 0.23488261
  y: 0.8416432
  z: -0.124252416
}
landmark {
  x: 0.23797552
  y: 0.84089196
  z: -0.15588646
}
landmark {
  x: 0.26496348
  y: 0.75405574
  z: -0.113334954
}
landmark {
  x: 0.25849894
  y: 0.75561446
  z: -0.1566533
}
landmark {
  x: 0.23374778
  y: 0.7916034
  z: -0.17892459
}
landmark {
  x: 0.20937555
  y: 0.8204909
  z: -0.19189456
}
landmark {
  x: 0.27643466
  y: 0.7087383
  z: -0.10346897
}
landmark {
  x: 0.24764231
  y: 0.695384
  z: -0.14117454
}
landmark {
  x: 0.20555642
  y: 0.71918327
  z: -0.1518512
}
landmark {
  x: 0.17359903
  y: 0.7420903
  z: -0.16102219
}
landmark {
  x: 0.2775539
  y: 0.6780304
  z: -0.09494146
}
landmark {
  x: 0.24329485
  y: 0.66316193
  z: -0.12708178
}
landmark {
  x: 0.19884942
  y: 0.6780439
  z: -0.13595977
}
landmark {
  x: 0.16818902
  y: 0.69536126
  z: -0.14275958
}
landmark {
  x: 0.27434954
  y: 0.6598588
  z: -0.0889524
}
landmark {
  x: 0.23745586
  y: 0.6539933
  z: -0.114237
}
landmark {
  x: 0.19944549
  y: 0.6640084
  z: -0.123690054
}
landmark {
  x: 0.17279452
  y: 0.67714
  z: -0.13072725
}
, landmark {
  x: 0.1782154
  y: 0.93768847
  z: -4.0703956e-08
}
landmark {
  x: 0.23144819
  y: 0.8727762
  z: -0.0033394776
}
landmark {
  x: 0.2520983
  y: 0.8018973
  z: -0.017812446
}
landmark {
  x: 0.2684797
  y: 0.7497646
  z: -0.034932632
}
landmark {
  x: 0.28295743
  y: 0.7001501
  z: -0.047864318
}
landmark {
  x: 0.16477507
  y: 0.6853812
  z: -0.024858348
}
landmark {
  x: 0.26766855
  y: 0.6634499
  z: -0.058381677
}
landmark {
  x: 0.29581043
  y: 0.7405415
  z: -0.07409343
}
landmark {
  x: 0.28071713
  y: 0.79440665
  z: -0.07967225
}
landmark {
  x: 0.14938074
  y: 0.6872054
  z: -0.036880527
}
landmark {
  x: 0.2723422
  y: 0.67256826
  z: -0.06744876
}
landmark {
  x: 0.29827994
  y: 0.75906986
  z: -0.0688904
}
landmark {
  x: 0.27903694
  y: 0.80650365
  z: -0.06530807
}
landmark {
  x: 0.14578941
  y: 0.71389145
  z: -0.05016167
}
landmark {
  x: 0.26555118
  y: 0.6935424
  z: -0.08037126
}
landmark {
  x: 0.2860596
  y: 0.779207
  z: -0.06723591
}
landmark {
  x: 0.26587772
  y: 0.8275005
  z: -0.052122686
}
landmark {
  x: 0.14938967
  y: 0.75642943
  z: -0.06341711
}
landmark {
  x: 0.24713139
  y: 0.7471509
  z: -0.08149708
}
landmark {
  x: 0.26482272
  y: 0.8056644
  z: -0.06949914
}
landmark {
  x: 0.24952382
  y: 0.8439414
  z: -0.05640859
}
]
```

**Comment by kuaashish** [comment]
Hi @PavelAgurov,
We need your help to debug the issue more this is a stray hand detection from some previous frame?
Do you have insight about where the additional left hand comes from?

**Comment by PavelAgurov** [comment]
I think it's issue of model - in some cases model decided that it's 2 hands instead of one.
I can try to check source code of library and check if I can trace it.
From other side I think if you will get coords and run model with it you can receive 2 hands.

**Comment by kuaashish** [comment]
@PavelAgurov,
Thanks for reaching us back. If any observation you can find out that will really helpful for us to fix this issue and improve the solution for the other community members. Meanwhile, We are assigning this issue to right owner. Thanks!!

**Comment by PavelAgurov** [comment]
Not sure if issue above is related to my. 
Sorry, I will try to find more details this week, was very busy.

**Comment by PavelAgurov** [comment]
Hi, sorry for long delay. So, please find short test and test image:

```
import cv2
import mediapipe as mp

file= "hand_2.jpg"
imageFromFile = cv2.imread(file)

mpHands = mp.solutions.hands
hands = mpHands.Hands(
                static_image_mode= False, 
                max_num_hands = 2,
                min_detection_confidence= 0.8,
                min_tracking_confidence = 0.8
        )

for i in range(100):
    # pre-processing
    img = imageFromFile
    img = cv2.flip(img, 1)
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # recognition
    results = hands.process(imgRGB)

    # result
    if results.multi_hand_landmarks:
        
        if len(results.multi_hand_landmarks) == 2:
            print('2 hands')
            print(results.multi_handedness[0], results.multi_handedness[1])
        else:
            print('1 hand')
            print(results.multi_handedness[0])

```            

Output:

```
1 hand
classification {
  index: 1
  score: 0.9981314
  label: "Right"
}

2 hands
classification {
  index: 1
  score: 0.9894802
  label: "Right"
}
 classification {
  index: 1
  score: 0.99468213
  label: "Right"
}

1 hand
classification {
  index: 1
  score: 0.9986132
  label: "Right"
}

1 hand
classification {
  index: 1
  score: 0.9985285
  label: "Right"
}

1 hand
classification {
  index: 1
  score: 0.9981314
  label: "Right"
}

2 hands
classification {
  index: 1
  score: 0.9894802
  label: "Right"
}
 classification {
  index: 1
  score: 0.99468213
  label: "Right"
}

1 hand
classification {
  index: 1
  score: 0.9986132
  label: "Right"
}

1 hand
classification {
  index: 1
  score: 0.9985285
  label: "Right"
}

1 hand
classification {
  index: 1
  score: 0.9981314
  label: "Right"
}

2 hands
classification {
  index: 1
  score: 0.9894802
  label: "Right"
}
 classification {
  index: 1
  score: 0.99468213
  label: "Right"
}
```

As you can see the same image can be recognized as 2 hands or only one.

Image example attached.
![hand_2](https://user-images.githubusercontent.com/37487002/217502773-7a3664ca-0ae1-447d-9765-d5bcc7dcf745.jpg)

**Comment by PavelAgurov** [comment]
Please note - if I add coordinates output I will have very close values:

`print(results.multi_hand_landmarks[0].landmark[0], results.multi_hand_landmarks[1].landmark[0])`

hand1:
```
x: 0.81331605
y: 0.7915341
z: -5.4251996e-07
```

hand2:
```
x: 0.8017197
y: 0.7396451
z: -2.7306643e-07
```

**Comment by kuaashish** [comment]
Hello @PavelAgurov,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by PavelAgurov** [comment]
Thanks, of course I will check new one. But my problem was not to easily build solution, but have output without bug :)

**Comment by kuaashish** [comment]
@PavelAgurov,
Please explore our new upgraded hand solutions and if you encounter the similar behaviour, feel free raise a new issue with complete details to reproduce the issue from our end. Further, We need your confirmation to move the status to close if now this is no longer issue from your end. Thank you
