### ISSUE TITLE
Uncaught (in promise) Error: MakeProtoPacket failed: $No registered object with name: 'mediapipe.NormalizedRect'

### ISSUE THREAD

**Issue by toreal** [google/mediapipe#3904]
**System information** (Please provide as much relevant information as possible)

-
I run following command to build the vision_pkg
`bazel build mediapipe/tasks/web:vision_pkg`

And, using follwing code to test GestureRecognizer.

`import {MediaPipeCamera} from './camera_util';`
`import {GestureRecognizer,GestureRecognizerResult } from '@mediapipe/tasks-vision';`
`const video = document.getElementById('video') as HTMLVideoElement;`
`let recognizer =null;`
`GestureRecognizer.createFromModelPath({wasmLoaderPath:"./wasm/vision_wasm_internal.js",`
`wasmBinaryPath:"./wasm/vision_wasm_internal.wasm"`
 `},"gesture_recognizer.task").then(r=>{`
  `r.setOptions({runningMode:'video'}).then( () =>{`
   ` recognizer =r;`
  `})`
 `})`
 `const camera = new MediaPipeCamera({`
 ` video,`
 ` onFrame: async () => {`
`if ( recognizer != null){`
` var res= recognizer.recognizeForVideo(video ,  performance.now()) as GestureRecognizerResult;`
` console.log(res.landmarks);`
`}`
`}`
`});`
`camera.start();`

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): macOS BigSur
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Chrome
- Programming Language and version ( e.g. C++, Python, Java): typescript
- [MediaPipe version](https://github.com/google/mediapipe/releases): lastest
- Bazel version (if compiling from source): 5.2.0
- Solution ( e.g. FaceMesh, Pose, Holistic ): GestureRecognizer

**Describe the current behavior:**

Here is the logs from the console.

vision_wasm_internal.js:1045 I0000 00:00:1670163008.747000       1 gl_context_webgl.cc:151] Successfully created a WebGL context with major version 3 and handle 1
put_char @ vision_wasm_internal.js:1045
vision_wasm_internal.js:1045 I0000 00:00:1670163008.750000       1 gl_context.cc:359] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)))
put_char @ vision_wasm_internal.js:1045
vision_wasm_internal.js:1045 W0000 00:00:1670163008.750000       1 gl_context.cc:1000] OpenGL error checking is disabled
put_char @ vision_wasm_internal.js:1045
vision_wasm_internal.js:1029 Graph successfully started running.
vision_wasm_internal.js:1045 INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
put_char @ vision_wasm_internal.js:1045
vision_wasm_internal.js:1029 Graph finished closing successfully.
vision_wasm_internal.js:1045 I0000 00:00:1670163008.832000       1 gl_context_webgl.cc:169] Successfully destroyed WebGL context with handle 1
put_char @ vision_wasm_internal.js:1045
vision_wasm_internal.js:1045 W0000 00:00:1670163008.841000       1 model_task_graph.cc:207] A local ModelResources object is created. Please consider using ModelResourcesCacheService to cache the created ModelResources object in the CalculatorGraph.
put_char @ vision_wasm_internal.js:1045
vision_wasm_internal.js:1045 W0000 00:00:1670163008.856000       1 model_task_graph.cc:207] A local ModelResources object is created. Please consider using ModelResourcesCacheService to cache the created ModelResources object in the CalculatorGraph.
put_char @ vision_wasm_internal.js:1045
vision_wasm_internal.js:1045 W0000 00:00:1670163008.868000       1 model_task_graph.cc:173] A local ModelResources object is created. Please consider using ModelResourcesCacheService to cache the created ModelResources object in the CalculatorGraph.
put_char @ vision_wasm_internal.js:1045
vision_wasm_internal.js:1045 W0000 00:00:1670163008.873000       1 model_task_graph.cc:207] A local ModelResources object is created. Please consider using ModelResourcesCacheService to cache the created ModelResources object in the CalculatorGraph.
put_char @ vision_wasm_internal.js:1045
3vision_wasm_internal.js:1045 W0000 00:00:1670163008.874000       1 model_task_graph.cc:173] A local ModelResources object is created. Please consider using ModelResourcesCacheService to cache the created ModelResources object in the CalculatorGraph.
put_char @ vision_wasm_internal.js:1045
vision_wasm_internal.js:1045 W0000 00:00:1670163008.877000       1 model_task_graph.cc:173] A local ModelResources object is created. Please consider using ModelResourcesCacheService to cache the created ModelResources object in the CalculatorGraph.
put_char @ vision_wasm_internal.js:1045
vision_wasm_internal.js:1045 I0000 00:00:1670163008.895000       1 gl_context_webgl.cc:151] Successfully created a WebGL context with major version 3 and handle 2
put_char @ vision_wasm_internal.js:1045
vision_wasm_internal.js:1045 I0000 00:00:1670163008.902000       1 gl_context.cc:359] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)))
put_char @ vision_wasm_internal.js:1045
vision_wasm_internal.js:1029 Graph successfully started running.
vision_bundle.js:13581 Uncaught (in promise) Error: MakeProtoPacket failed: $No registered object with name: mediapipe.NormalizedRect
    at GestureRecognizer.handleErrors (vision_bundle.js:13581:19)
    at GestureRecognizer.finishProcessing (vision_bundle.js:13574:14)
    at GestureRecognizer.process (vision_bundle.js:20737:15)
    at GestureRecognizer.processVideoData (vision_bundle.js:13636:21)
    at GestureRecognizer.recognizeForVideo (vision_bundle.js:20727:22)
    at _callee$ (pose_demo.ts:34:34)
    at tryCatch (pose_demo.ts:5:1357)
    at Generator.eval (pose_demo.ts:5:4174)
    at Generator.eval [as next] (pose_demo.ts:5:2208)
    at asyncGeneratorStep (pose_demo.ts:6:103)

'mediapipe.NormalizedRect' did not register.

**Describe the expected behavior:**

Can you provide documentation to help me with this problem?

**Comment by kuaashish** [comment]
Hi @toreal,
Could you please elaborate your query with complete details and steps followed to reproduce the issue from our end.

**Comment by toreal** [comment]
1. prepare the model under linux (because of gpu)

`bazel build --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/model_maker/python/vision/gesture_recognizer:gesture_recognizer_demo`

3. rename the tflite files to fit the names under bazel-bin. 

`mv palm_detection_full.tflite hand_detector.tflite`
`mv hand_landmark_full.tflite hand_landmarks_detector.tflite`

4. run the command to get the task under data
`bazel-bin/mediapipe/model_maker/python/vision/gesture_recognizer:gesture_recognizer_demo --export_dir="data"`

5. prepare the  project

`bazel build mediapipe/tasks/web:vision_pkg`
`npm install bazel-bin/mediapipe/tasks/web/vision_pkg`
`npx webpack `
`http-server `

**Comment by toreal** [comment]
Finally, I realized that for some reason googler changed its name from  'mediapipe' to 'drishti'
It works now. If I modified as following.

` this.graphRunner.addProtoToStream(
        FULL_IMAGE_RECT.serializeBinary(), 'drishti.NormalizedRect',
        NORM_RECT_STREAM, timestamp);`
