### ISSUE TITLE
Build in container doesn't fetch model files

### ISSUE THREAD

**Issue by dbeiski-artlist** [google/mediapipe#3906]
**System information**
- Mac with intel processor, macOS v12.5.1 
- System inside the container as in the repo [Dockerfile](https://github.com/google/mediapipe/blob/master/Dockerfile)
- Added libopencv-contrib-dev to apt-get install sequence to fix a another issue

**The Problem**:
I am trying to use AutoFlip inside a container, based on the dockerfile and instructions in the [documentation](https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker).
After building the container and the pipeline, I get an error:

> Failed to run the graph: CalculatorGraph::Run() failed in Run:
> Calculator::Open() for node "autoflipobjectdetectionsubgraph__DetectionLabelIdToTextCalculator" failed: ; Can't find file: mediapipe/models/ssdlite_object_detection_labelmap.txt

Looking into the container files, the models directory is empty, meaning that the pipe build doesn't fetch the model files needed for the AutoFlip pipe.

The first error of this kind was for the tflite file, but I found it [here](https://google.github.io/mediapipe/solutions/object_detection) and added it manually. The file I in the quoted error I couldn't find.

**Command sequence:**
- Added video files to the mediapipe directory to be copied during image build
- Removed "AUDIO_FILE_PATH:audio_path" parameters from input and output packets in node config to fix a different issue (ffmpeg isn't recognized, and this is what the logs suggested)

- Build image with
`$ docker build . -t mediapipe`

- Run image with 
`$ docker run -it mediapipe`

- Within the container:
Build command:
`$ bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --copt -I/usr/include/opencv4/ mediapipe/examples/desktop/autoflip:run_autoflip`
The term "--copt -I/usr/include/opencv4/ " was added to fix a different issue

- Make output directory

- Run pipe on video
`$ GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip   --calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt   --input_side_packets=input_video_path=mediapipe/videos/551041_Baby_Toddler_Beach_Walking_By_Mayalab_Artlist_HD.mp4,output_video_path=./output/test.mp4,aspect_ratio=9:16`

**Complete Logs:**
Attached
[autoflip_run.log](https://github.com/google/mediapipe/files/10164228/autoflip_run.log)
[graph_build.log](https://github.com/google/mediapipe/files/10164230/graph_build.log)
[hello_world_test.log](https://github.com/google/mediapipe/files/10164232/hello_world_test.log)
[image_build.log](https://github.com/google/mediapipe/files/10164233/image_build.log)

**Comment by dbeiski-artlist** [comment]
@kuaashish **_solution:autoflip_** tag would be a better fit

**Comment by Tvax** [comment]
try to update the [download_utils.py] if needed (https://github.com/google/mediapipe/blob/d3f98334bfe533a57ec2c2fa85294c21e25fe0af/mediapipe/python/solutions/download_utils.py) (https://github.com/google/mediapipe/issues/3698#issuecomment-1247905371)

or you can download them manually from:
- https://storage.googleapis.com/mediapipe-assets/ssdlite_object_detection_labelmap.txt
- https://storage.googleapis.com/mediapipe-assets/ssdlite_object_detection.tflite

**Comment by kuaashish** [comment]
Hello @dbeiski-artlist,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by dbeiski-artlist** [comment]
@kuaashish thank you for your response!
Is AutoFlip expected to be available in the new MediaPipe solutions?

**Comment by kuaashish** [comment]
@dbeiski-artlist,
Unfortunately, No, We are ending fully support of these [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) (Status:Support Ending), However, All source code related to ending MediaPipe Legacy Solutions will be continue to available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). You can continue to use those legacy solutions in your applications if you choose However, we will be unavailable to provide support of solutions ending and will be removed from 1st of June as already notified [here](https://google.github.io/mediapipe/solutions/solutions#solutions).

**Comment by dbeiski-artlist** [comment]
Thank you
