### ISSUE TITLE
How to run tflite model(downloaded from mediapipe) with ARKit session captured image?

### ISSUE THREAD

**Issue by frank-1992** [google/mediapipe#3908]
I have a tflite model handtracking and I want to run model using ARKit session captured image. It's showing source pixel format is invalid. I was able to run tflite model using AVCapture session:

// Not working with ARKit frame
`func session(_ session: ARSession, didUpdate frame: ARFrame) {
    handTracker.processVideoFrame(pixelBuffer)
}`

// Working fine with AVCapture session
`func captureOutput(_ output: AVCaptureOutput, didOutput sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection) {
    let pixelBuffer = CMSampleBufferGetImageBuffer(sampleBuffer)
   handTracker.processVideoFrame(pixelBuffer)
}`

**Comment by ayushgdev** [comment]
Can you please provide details as per the applicable template mentioned in the [documentation](https://google.github.io/mediapipe/getting_started/help.html#system-information)?

**Comment by GongHongORzm** [comment]
if you get the right answer, pls.  share it with me,because I'm tring to find the way to user mediapeipe with ARKit, thanks!

**Comment by frank-1992** [comment]
> if you get the right answer, pls. share it with me, because I'm tring to find the way to use mediapeipe with ARKit, thanks!

OK, if you find the way ,you can also share it with me ,thanks

**Comment by kuaashish** [comment]
Hello @frank-1992,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you

**Comment by 2hiTee** [comment]
> if you get the right answer, pls. share it with me, because I'm tring to find the way to use mediapeipe with ARKit, thanks!

Hi,

Have you find out how to use mediapipe with ARKit? Are they compatible? This is crucial to me. Thanks for your help!

**Comment by 2hiTee** [comment]
> > if you get the right answer, pls. share it with me, because I'm tring to find the way to use mediapeipe with ARKit, thanks!
> 
> OK, if you find the way ,you can also share it with me ,thanks

Hi,

Have you find out how to use mediapipe with ARKit? Are they compatible? This is crucial to me. Thanks for your help!
