### ISSUE TITLE
Jump Detection With MediaPipe Pose

### ISSUE THREAD

**Issue by DiegoTondorf** [google/mediapipe#3909]
Hello,
I am Diego Fellipe Tondorf, a master's student in the Graduate Program in Applied Computing at UDESC, my advisor is Marcelo da Silva Hounsell and I am part of the Laboratory of Research on Visual Applications (LARVA) 

I am using the MediaPipe Pose as a control for a game NUI, replacing the old control (Kinect) for the Webcam.

In the new game design, objects were added that require the player to jump, which created a problem of how to get this information, because Pose takes the player as the zero point.

**System information**
- Windows 10 Pro : 21H2
- mediapipe : 0.8.9.1
- MediaPipe Pose
- Python

**Expected behavior:**
There are several objects coming towards the player, some of them are coming at the player's feet, and to evade them the player needs to jump. 

The game needs to take the coordinates in 3 dimensions, which is why POSE_WORLD_LANDMARKS is used, the problem is that the origin point is the hips and when the player jumps the original point moves with it.

To solve this problem an estimate is made of where the player's floor is, saving the last X iterations and averaging these position. When the player is too far away from the floor the program understands that he is jumping, Sending the corrected coordinates to the game.

But if it moves slowly back and forth the program has difficulty understanding whether it is jumping or not. 

What I would like to know is if it is possible to improve this form or if there is a better way to test the jump.

I have edited the whole code to make it cleaner and easier to understand, the full code is at the link below.

**Code**

```python
/.../

#Get lower foot id
def GetLowerFootId(_landmarks):
    return 29 if  (_landmarks[29].y>_landmarks[30].y) else 30


#Get floor y estimative from landmarks
def GetFloorY(_yList, _lowerFootY):
    _yList.insert(0, _lowerFootY)
                    
    if len(yList)>ListLimit:
       yList.pop(ListLimit)
    
    sum = 0
    for x in _yList:
        sum = sum + x
    
    return sum/len(_yList)   
	
/.../

#Final corrections of data to SIRTET
def LandmaksCorrections(_world_landmarks, _xOffset, _feetY, _yOffSet):    
    dist = 1000
    for i in index:
        _world_landmarks[i].x = (_world_landmarks[i].x * dist) + _xOffset
        _world_landmarks[i].y = ((_world_landmarks[i].y - _feetY) * dist * -1) - 950 - _yOffSet
        _world_landmarks[i].z = (_world_landmarks[i].z * dist) + 2500
    return _world_landmarks 

/.../

###
# Start of Jump

#Get lower foot y from landmarks
lowerFootY = float(landmarks[lowerFootId].y)

#Get floot y estimative from landmarks
floorY = GetFloorY(yList, lowerFootY)

/.../

#Get the difference between the lowest foot and the floor
yOffSet = (lowerFootY - floorY) * 3500            

#Smoothes the variation to not consider jumping every frame
yOffSetVariation = abs(yOffSet) - 51  

if yOffSetVariation < 0:
	yOffSet = 0
#Base height y for the jump
	jumpbaseY = 0
#If the variation is large enough, consider a jump
else:
	if jumpbaseY == 0:
		jumpbaseY = world_landmarks[lowerFootId].y   

#Checks and stores the values of the current jump and the highest jump
if yOffSet != 0:
	currJump = jumpbaseY - world_landmarks[lowerFootId].y
	if currJump > highestJump:
		highestJump = round(currJump, 3)
		jumpProp = round(highestJump / estHeight * 100, 3)

# End of Jump
###

#Get the lower foot y, from world to data corretion
feetY = world_landmarks[lowerFootId].y 

#Final corrections of data to SIRTET
world_landmarks = LandmaksCorrections(world_landmarks, xOffset, feetY, yOffSet)
/.../

```

**Other info:**
More information about the project on the link: 
	https://udescmove2learn.wordpress.com/jogos/sirtet-k3d/
The complete code can be viewed at:
	https://drive.google.com/file/d/1_dHigUyLERPEc219MybzCZFcb8MNodeu/view

**Comment by kuaashish** [comment]
@DiegoTondorf,
Jump detection itself is outside of scope of mediapipe solutions and has not been experimented yet. We welcome the community contribution here

**Comment by rm6759** [comment]
Inferring a floor plane and tracking feet kepoints against the infered floor plane looks complicated.

An alternate solution would be do develop a reference data set of various ways one can jump.  I would expect you could accomplish this with 10-20 frames of data.   Once you have jump reference frames, you can simply compare live video frames with the jump references, and score against them e.g. best score indicates jump type.  

Landmarks or world landmarks should work ok.  The z axis is the same in either set.

World landmarks being relative distance from center of hips may simplify a scoring system however, there is probably some value in standard landmarks if there is a requirement to track lateral movement within the frame.

Regarding creation of the jump references:  These will not be frames of world coordinates, but rather relationships values between keypoints that are involved in jumping.  How do ankles change in relation to knees based on difference ways one can jump,   Do wrists change relationship  from hips, etc.    

Creating reference frames allows easy table updates as opposed to rewriting foot/floor tracking code.  If the reference frames (for any player poses) can be read at startup and moved into an array e.g. numpy, performance should good enough to keep up with your video stream.

**Comment by kuaashish** [comment]
@DiegoTondorf,

This is out of our scope and We believe that will be not provide the support on it. However, [This implementation](https://github.com/skyindde/Jumping_Jack_Counter) will give you better understanding on use case described here And we suggest you to follow up with them.  Thank you
