### ISSUE TITLE
Is it possible to change the 256 to a larger 512

### ISSUE THREAD

**Issue by Sanerly** [google/mediapipe#391]
# Transforms the input image on GPU to a 256x256 image. To scale the input
# image, the scale_mode option is set to FIT to preserve the aspect ratio,
# resulting in potential letterboxing in the transformed image.
node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:input_video"
  output_stream: "IMAGE_GPU:transformed_input_video"
  output_stream: "LETTERBOX_PADDING:letterbox_padding"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 256
      output_height: 256
      scale_mode: FIT
    }
  }
}
Is it possible to change the 256 to a larger 512？

**Comment by mcclanahoochie** [comment]
I don't know what graph this is from, but likely 256 was chosen because the following calculators (or ML model) expects that particular size.
The width and height can be whatever you wish, assuming the downstream calculators can handle that size.

**Comment by fanzhanggoogle** [comment]
As @mcclanahoochie said, this is determined by the model itself. And perserving the aspect ratio is also the consideration for better performance during training. So it has to be 256x256 with input aspect ratio for the specific model.
