### ISSUE TITLE
mediapipe pose tracking crashes on android 10

### ISSUE THREAD

**Issue by Mohamedben10** [google/mediapipe#3910]
Hello every one;
i have built successfully, with bazel, an application that i develloped byy my self based on pose tracking code provided by mediapipe but i have two situation:
1/ the application runs well on android lower or equal android 9;
2/ the application installs successfuly but crashes with the following message " application keeps stopping" on android 10

androidmanifest.xml file

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.google.mediapipe.apps.kneemonitoring">
      <uses-sdk
      android:minSdkVersion="21"
      android:targetSdkVersion="33" 
      android:compileSdkVersion="33"
      />
      
      
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
    
    <uses-permission android:name="android.permission.CAMERA" />

    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    
    <uses-feature
        android:glEsVersion="0x00020000"
        android:required="true" />

    <application
        tools:replace="android:appComponentFactory"
        android:appComponentFactory='klb'
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:requestLegacyExternalStorage="true"
        android:requestRawExternalStorageAccess="true"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:allowClearUserData="true"
        android:allowBackup="false"
        android:theme="@style/Theme.KneeAssessment">
        <activity
            android:name=".HomeActivity"
            android:exported="true"
            >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".KneeAssessmentActivity"
            android:exported="true"
            />
        <activity
            android:name=".ChooseTheAssessmentActivity"
            android:exported="true"
            />
        <activity
            android:name=".TutorialActivity"
            android:exported="true"
            />
        <activity
            android:name=".AssessmentReportRightActivity"
            android:exported="true"
            />

        <activity
            android:name=".AssessmentReportLeftActivity"
            android:exported="true"
            />

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>
    </application>

</manifest>

the android sdk and ndk path add at the end of WORKSPACE:

android_sdk_repository(name = "androidsdk", path = "/home/med/Android/Sdk")
android_ndk_repository(name = "androidndk", api_level=21, path = "/home/med/Android/Sdk/ndk-bundle/android-ndk-r21")

any one can help me to solve this issue??? thank you

**Comment by ayushgdev** [comment]
@Mohamedben10 Can you please provide more information regarding the error you are facing? An error log attachment would help us address your issue better.

**Comment by Mohamedben10** [comment]
sorry for late reply the problem of crashing was due tu drawer layout...

**Comment by ayushgdev** [comment]
Glad the issue is resolved @Mohamedben10 . If no further assistance is required on this error, can you please close the issue?

**Comment by Mohamedben10** [comment]
thank you for you rhelp
