### ISSUE TITLE
I want get the Face Landmark、Hand Landmark and Body Landmark on MediaPipe Holistic

### ISSUE THREAD

**Issue by Epoch2022-iOS** [google/mediapipe#3912]
Hello, I'm developer with an iOS application,
Now I need Use MediaPipe Holistic To Tracking human body、face and hands, I try to Run the Example Demo and get the realtime pixelBuffer, But I can't get the **Face Landmark、Hand Landmark and Body Landmark** with the code.

I need your help now to get that landmark.

Before that, I found one that could be accessed **Face Landmark** Demo，[get face landmark demo link](https://github.com/61315/mediapipe-prebuilt)

language：Swift/Objective-C
Xcode Version：14.0.1
Device：IPhone 12 Pro Max

**Comment by kuaashish** [comment]
Hello @Epoch2022-iOS,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
