### ISSUE TITLE
In building AAR file of FaceEffect , FaceGeometry java class and Matrix Data is not including.

### ISSUE THREAD

**Issue by prasadankitt** [google/mediapipe#3913]
Actually when we are creating faceeffect AAR as mentioned in documentation its get builded successfully and in my android app i am able to get that aar. But when we are writing our MainActivity there it is unable to find FaceGeometry and Matrix Data. 

In  //mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect/MainActivity.java they are using same code but in import they have 
**import com.google.mediapipe.modules.facegeometry.FaceGeometryProto.FaceGeometry;
import com.google.mediapipe.formats.proto.MatrixDataProto.MatrixData;**
But it is not present in my  classes.jar file of AAR otherwise its get included automatically if FaceGeometry and Matrix Data is present .

I think while building its unable to convert FaceFeometryProto in java file. 

![Screenshot (64)](https://user-images.githubusercontent.com/63342124/206465561-d4d10b49-0339-40e6-a733-93767328fbbf.png) 

my build file for making face effect AAR :-
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_face_effect",
    calculators = ["//mediapipe/graphs/face_effect:face_effect_gpu_deps"],
)

What i have to do in order to resolve this ?
Kindly check the picture you will understand what i am trying to say and please provide a solution ASAP.

**Comment by jeffreyrajanofficial** [comment]
I'm also facing the same issue. Any solution for this?

**Comment by kuaashish** [comment]
Hi @prasadankitt,
Would you let know the complete steps followed to address the issue better from our end

**Comment by jeffreyrajanofficial** [comment]
@kuaashish 

OS: macOS - 13.1(M2)
BUILD File- 
```
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_face_effect",
    calculators = [
    "//mediapipe/graphs/face_effect:face_effect_gpu_deps",
    "//mediapipe/graphs/face_mesh:mobile_calculators"
    ],
)
```
Command line - 
```bazel build -c opt --strip=ALWAYS --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a --legacy_whole_archive=0 --features=-legacy_whole_archive --copt=-fvisibility=hidden --copt=-ffunction-sections --copt=-fdata-sections --copt=-fstack-protector  --copt=-Oz --copt=-fomit-frame-pointer --copt=-DABSL_MIN_LOG_LEVEL=2 --linkopt=-Wl,--gc-sections,--strip-all  //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_effect.aar```

Output - Successful
 After successfully generating the AAR file. I got the below result. 
<img width="1031" alt="Screenshot 2022-12-15 at 1 00 45 PM" src="https://user-images.githubusercontent.com/16349497/207799436-a0eacd69-ce45-4393-a892-0cba5873e8d5.png">

When I tried to access FaceGeometry, I was getting the below error.
<img width="465" alt="Screenshot 2022-12-15 at 1 03 36 PM" src="https://user-images.githubusercontent.com/16349497/207799997-49df9369-83c7-4a94-bcb1-7b56216114b4.png">

Am I following the right way to generate AAR for android FaceEffect?

**Comment by prasadankitt** [comment]
@kuaashish  
He @jeffreyrajanofficial  has already explained it above what issue we are facing . Rajan according to documentations we are generating Aar properly.

**Comment by kuaashish** [comment]
Hi @prasadankitt, @jeffreyrajanofficial. Thanks for bring out to our notice! this looks like a bug in our android solution and possibly problem with bazel build targets. we will investigate it and let you know the workaround can be fix in the upcoming releases.

**Comment by schmidt-sebastian** [comment]
Can you build `bazel build //mediapipe/modules/face_geometry/protos:face_geometry_java_proto_lite` and share the output? This is what my class looks like: https://gist.github.com/schmidt-sebastian/a7023dedc9103666301d9a71aa83c50c

This properly defines the missing class.

**Comment by dineshoptisol** [comment]
@schmidt-sebastian In that shared proto file, some are missing proto dependencies.
The below files are not found. 
1. com.google.mediapipe.formats.proto.MatrixDataProto.MatrixData
2. com.google.mediapipe.modules.facegeometry.Mesh3dProto.Mesh3d

any idea?

**Comment by BTLDXX-x** [comment]
hello @schmidt-sebastian, i build `bazel build //mediapipe/modules/face_geometry/protos:face_geometry_java_proto_lite`

it print: 

```
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
INFO: Build option --compilation_mode has changed, discarding analysis cache.
INFO: Analyzed target //mediapipe/modules/face_geometry/protos:face_geometry_java_proto_lite (1 packages loaded, 1726 targets configured).
INFO: Found 1 target...
Target //mediapipe/modules/face_geometry/protos:face_geometry_java_proto_lite up-to-date:
  bazel-bin/mediapipe/modules/face_geometry/protos/libmesh_3d_proto-lite.jar
  bazel-bin/mediapipe/framework/formats/libmatrix_data_proto-lite.jar
  bazel-bin/mediapipe/modules/face_geometry/protos/libface_geometry_proto-lite.jar
  bazel-bin/mediapipe/modules/face_geometry/protos/face_geometry_proto-lite-src.jar
INFO: Elapsed time: 6.213s, Critical Path: 4.15s
INFO: 14 processes: 1 internal, 12 darwin-sandbox, 1 worker.
INFO: Build completed successfully, 14 total actions
```

does it has any problem? i built the aar also facing the issue
thanks for your help.
