### ISSUE TITLE
compile androidsdk//:dx_jar_import failed

### ISSUE THREAD

**Issue by zhangkom** [google/mediapipe#3914]
1, build for android on macbook pro.

2, mediapipe version
mediapipe 0.8.11 

3, software:
macos 10.15.7
bazel 5.2.0

4, compile instruct:
~/bin/bazel build -c opt --strip=ALWAYS \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    --legacy_whole_archive=0 \
    --features=-legacy_whole_archive \
    --copt=-fvisibility=hidden \
    --copt=-ffunction-sections \
    --copt=-fdata-sections \
    --copt=-fstack-protector \
    --copt=-Oz \
    --copt=-fomit-frame-pointer \
    --copt=-DABSL_MIN_LOG_LEVEL=2 \
    --linkopt=-Wl,--gc-sections,--strip-all \
    //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar

5,error message:

external/com_google_absl/absl/base/attributes.h:648:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                ^
2 warnings generated.
ERROR: /private/var/tmp/_bazel_kom/70cfb2c6ae99156d7025a87d5c74de38/external/androidsdk/BUILD.bazel:13:25: Extracting interface @androidsdk//:dx_jar_import failed: missing input file 'external/androidsdk/build-tools/33.0.1/lib/dx.jar', owner: '@androidsdk//:build-tools/33.0.1/lib/dx.jar'
ERROR: /private/var/tmp/_bazel_kom/70cfb2c6ae99156d7025a87d5c74de38/external/androidsdk/BUILD.bazel:13:25: Extracting interface @androidsdk//:dx_jar_import failed: 1 input file(s) do not exist
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /private/var/tmp/_bazel_kom/70cfb2c6ae99156d7025a87d5c74de38/external/androidsdk/BUILD.bazel:13:25 Extracting interface @androidsdk//:dx_jar_import failed: 1 input file(s) do not exist
INFO: Elapsed time: 3469.091s, Critical Path: 970.82s
INFO: 4037 processes: 140 internal, 3895 darwin-sandbox, 2 worker.
FAILED: Build did NOT complete successfully

<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by zhangkom** [comment]
androidsdk % cd build-tools 
kom@zhangkom build-tools % ls
23.0.3	24.0.1	24.0.3	25.0.1	25.0.3	26.0.1	26.0.3	27.0.1	27.0.3	28.0.1	28.0.3	29.0.1	29.0.3	30.0.1	30.0.3	32.0.0	33.0.1
24.0.0	24.0.2	25.0.0	25.0.2	26.0.0	26.0.2	27.0.0	27.0.2	28.0.0	28.0.2	29.0.0	29.0.2	30.0.0	30.0.2	31.0.0	33.0.0


build-tools % find . -name dx.jar
./27.0.1/lib/dx.jar
./24.0.0/lib/dx.jar
./30.0.0/lib/dx.jar
./25.0.0/lib/dx.jar
./26.0.1/lib/dx.jar
./24.0.1/lib/dx.jar
./30.0.1/lib/dx.jar
./27.0.0/lib/dx.jar
./26.0.0/lib/dx.jar
./25.0.1/lib/dx.jar
./29.0.2/lib/dx.jar
./28.0.2/lib/dx.jar
./29.0.3/lib/dx.jar
./28.0.3/lib/dx.jar
./23.0.3/lib/dx.jar
./25.0.3/lib/dx.jar
./26.0.2/lib/dx.jar
./27.0.2/lib/dx.jar
./24.0.3/lib/dx.jar
./30.0.3/lib/dx.jar
./26.0.3/lib/dx.jar
./25.0.2/lib/dx.jar
./24.0.2/lib/dx.jar
./30.0.2/lib/dx.jar
./27.0.3/lib/dx.jar
./28.0.1/lib/dx.jar
./29.0.1/lib/dx.jar
./28.0.0/lib/dx.jar
./29.0.0/lib/dx.jar

These is not a dx.jar in 33.0.1.

**Comment by RepublicOfKorokke** [comment]
Android SDK over 31.0.0 has no dx.jar in its dir
So use SDK 30.0.3 (or lower)
