### ISSUE TITLE
compile face mesh aar

### ISSUE THREAD

**Issue by zhangkom** [google/mediapipe#3915]
1, build for android on macbook pro.
2, mediapipe version
mediapipe 0.8.11
3, software:
macos 10.15.7
bazel 5.2.0
4, compile instruct:
~/bin/bazel build -c opt --strip=ALWAYS
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain
--fat_apk_cpu=arm64-v8a,armeabi-v7a
--legacy_whole_archive=0
--features=-legacy_whole_archive
--copt=-fvisibility=hidden
--copt=-ffunction-sections
--copt=-fdata-sections
--copt=-fstack-protector
--copt=-Oz
--copt=-fomit-frame-pointer
--copt=-DABSL_MIN_LOG_LEVEL=2
--linkopt=-Wl,--gc-sections,--strip-all
//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_mesh_gpu.aar

And it is successful, the result is following:

   creating: lib/
   creating: lib/arm64-v8a/
  inflating: lib/arm64-v8a/libopencv_java3.so  
  inflating: lib/arm64-v8a/libmediapipe_jni.so  
   creating: lib/armeabi-v7a/
  inflating: lib/armeabi-v7a/libmediapipe_jni.so  
  inflating: lib/armeabi-v7a/libopencv_java3.so  
  adding: jni/arm64-v8a/libmediapipe_jni.so (deflated 70%)
  adding: jni/arm64-v8a/libopencv_java3.so (deflated 59%)
  adding: jni/armeabi-v7a/libmediapipe_jni.so (deflated 51%)
  adding: jni/armeabi-v7a/libopencv_java3.so (deflated 50%)
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_mesh_gpu.aar up-to-date:
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/mediapipe_face_mesh_gpu.aar
INFO: Elapsed time: 212.438s, Critical Path: 207.94s
INFO: 456 processes: 9 internal, 441 darwin-sandbox, 6 worker.
INFO: Build completed successfully, 456 total actions

5, The interface of my own aar is different from the example from Face Mesh Solution example. How can I compile a aar of Face Mesh solution aar?  I just want to send a bitmap to mediapipe and get 478*3 face mesh points in own aar, please help. Thanks a lot. 

<img width="417" alt="Screen Shot 2022-12-10 at 4 37 29 PM" src="https://user-images.githubusercontent.com/15842542/206841562-278badd7-4b05-448e-873c-9acad1eef60e.png">
<img width="610" alt="Screen Shot 2022-12-10 at 4 38 13 PM" src="https://user-images.githubusercontent.com/15842542/206841578-dd0e0e59-80a4-45f8-b960-9cc805dfc600.png">

**Comment by kuaashish** [comment]
Hi @zhangkom,
This can be done(Getting the all landmarks on face mesh) using the graph [face_mesh_mobile.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_mesh/face_mesh_mobile.pbtxt), 
However, You will be required to use this output_stream: "multi_face_landmarks" in MainActivity,java similar approach can be seen here in https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example/blob/master/app/src/main/java/com/example/mediapipemultihandstrackingapp/MainActivity.java#L116 to get all landmarks of holistic solution in AAR.
