### ISSUE TITLE
my application crashes when trying to show the bottomsheetdialog 

### ISSUE THREAD

**Issue by Mohamedben10** [google/mediapipe#3917]
hello every one,
im trying to develop an application that open a bottomsheetdialog the application is built successfully with bazel but when trying to access to the bottomsheet it crashes i attached the logcat below

12-11 22:03:06.587 12544 12544 D AndroidRuntime: Shutting down VM
12-11 22:03:06.599 12544 12544 W .kneemonitorin: Accessing hidden method Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)
12-11 22:03:06.600 12544 12544 E .kneemonitorin: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
--------- beginning of crash
12-11 22:03:06.603 12544 12544 E AndroidRuntime: FATAL EXCEPTION: main
12-11 22:03:06.603 12544 12544 E AndroidRuntime: Process: com.google.mediapipe.apps.kneemonitoring, PID: 12544
12-11 22:03:06.603 12544 12544 E AndroidRuntime: java.lang.ClassCastException: android.support.design.widget.CoordinatorLayout cannot be cast to androidx.coordinatorlayout.widget.CoordinatorLayout
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at com.google.android.material.bottomsheet.BottomSheetDialog.ensureContainerAndBehavior(BottomSheetDialog.java:274)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at com.google.android.material.bottomsheet.BottomSheetDialog.wrapInBottomSheet(BottomSheetDialog.java:286)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at com.google.android.material.bottomsheet.BottomSheetDialog.setContentView(BottomSheetDialog.java:121)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at com.google.mediapipe.apps.kneemonitoring.AssessmentReportLeftActivity.showBottomSheetDialog(AssessmentReportLeftActivity.java:381)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at com.google.mediapipe.apps.kneemonitoring.AssessmentReportLeftActivity.access$000(AssessmentReportLeftActivity.java:50)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at com.google.mediapipe.apps.kneemonitoring.AssessmentReportLeftActivity$2.onClick(AssessmentReportLeftActivity.java:144)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at android.view.View.performClick(View.java:6659)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6631)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at android.view.View.access$3100(View.java:790)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:26187)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:907)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7625)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
12-11 22:03:06.603 12544 12544 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
12-11 22:03:06.650 12544 12544 I Process : Sending signal. PID: 12544 SIG: 9

the function where i show the bottomsheet
    private void showBottomSheetDialog() {

        final BottomSheetDialog bottomSheetDialog = new BottomSheetDialog(this);
        bottomSheetDialog.setContentView(R.layout.create_duration_pin_bottomsheet_layout);

       bottomSheetDialog.show();
    }

please help me

**Comment by ayushgdev** [comment]
Hi @Mohamedben10 Can you please provide more details on the issue? From the logs provided, i.e. 

`android.support.design.widget.CoordinatorLayout cannot be cast to androidx.coordinatorlayout.widget.CoordinatorLayout`

it seems like an issue with the native Android Fragment configuration, not particularly MediaPipe. However, this is a preliminary analysis and more information on the platform, the use case you are trying to build, the version information, etc. can help to resolve the issue better.
Please refer to the [templates](https://github.com/google/mediapipe/issues/new/choose) and provide more information as per the applicable option.
