### ISSUE TITLE
onResults callback never gets called

### ISSUE THREAD

**Issue by mridulgupta210** [google/mediapipe#3918]
**System information** (Please provide as much relevant information as possible)

- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Google chrome and Microsoft Chromium Edge
- Programming Language and version ( e.g. C++, Python, Java): Javascript
- [MediaPipe version](https://github.com/google/mediapipe/releases): latest
- Solution ( e.g. FaceMesh, Pose, Holistic ): Facemesh

**Describe the current behavior:**
I have implemented code using facemesh and camera utils and somehow the onResults callback is never called for me.
The camera is working fine and I am able to see the video in the HTML video tag as well. The canvas is always empty as onResults was never called

On little debugging I could see from faceMesh.send function, it is not going beyond the ".initialize" function
![image](https://user-images.githubusercontent.com/48939591/206993736-1c75f17d-352a-4037-987d-28fa53226459.png)

**Describe the expected behavior:**
onResults should get called

**Standalone code to reproduce the issue:**
```
        videoElement = ge_cl(_d, "br-pdp-vto-input-video")[0];
        canvasElement = ge_cl(_d, "br-pdp-vto-output-canvas")[0];
        canvasCtx = canvasElement.getContext('2d');

        const faceMesh = new mpFaceMesh.FaceMesh({
            locateFile: (file) => {
                return `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@${mpFaceMesh.VERSION}/${file}`;
            }
        });

        faceMesh.setOptions({
            maxNumFaces: 1,
            refineLandmarks: true,
            minDetectionConfidence: 0.5,
            minTrackingConfidence: 0.5
        });
        faceMesh.onResults(onResults); // the OnResults method never gets called

        const onCameraFrame = async () => {
            await faceMesh.send({ image: videoElement });
        }

        const camera = new mpCamera.Camera(videoElement, {
            onFrame: onCameraFrame,
            width: 1280,
            height: 720
        });

        camera.start();
```

**Other info / Complete Logs :**
Nothing in browser console. Let me know if there are other ways to get any internal mediapipe logs

**Comment by ayushgdev** [comment]
@mridulgupta210 Can you please provide more details by choosing the suitable issue template [here](https://github.com/google/mediapipe/issues/new/choose)? This allows us to capture more information to provide resolution. 
Also, along with the template information, please let us know the technology you are using (for example, vanilla JS/React/Angular).

**Comment by mridulgupta210** [comment]
> @mridulgupta210 Can you please provide more details by choosing the suitable issue template [here](https://github.com/google/mediapipe/issues/new/choose)? This allows us to capture more information to provide resolution. Also, along with the template information, please let us know the technology you are using (for example, vanilla JS/React/Angular).

@ayushgdev I have updated the original question with the template

**Comment by ayushgdev** [comment]
@mridulgupta210 Thanks for the update. However can you clarify if you are using React angular or vanilla JS? 
_If_ you are using vanilla JS(since you only mentioned Javascript), I have several queries:
1. How are you importing the mediapipe facemesh solution? Because I see you are using a module reference `mpFaceMesh` and `mpCamera` to access FaceMesh however, in vanilla JS, you don't use modular imports.
2. `onResults` function is not defined in the gist provided. Can you confirm you have defined a function?
3. Have you tried running the example from the Javascript solutions [page](https://google.github.io/mediapipe/solutions/face_mesh.html#javascript-solution-api) first?

**Comment by mridulgupta210** [comment]
> @mridulgupta210 Thanks for the update. However can you clarify if you are using React angular or vanilla JS? _If_ you are using vanilla JS(since you only mentioned Javascript), I have several queries:
> 
> 1. How are you importing the mediapipe facemesh solution? Because I see you are using a module reference `mpFaceMesh` and `mpCamera` to access FaceMesh however, in vanilla JS, you don't use modular imports.
> 2. `onResults` function is not defined in the gist provided. Can you confirm you have defined a function?
> 3. Have you tried running the example from the Javascript solutions [page](https://google.github.io/mediapipe/solutions/face_mesh.html#javascript-solution-api) first?

Yes I am using vanillaJS
1. I tried several ways. In a brute force way, I have simply copied the entire content of face_mesh.js file from npm package and pasted on top of my script file.
2. Yes, I have that function defined.
3. Yes, that too does not work for me somehow.

**Comment by ayushgdev** [comment]
Okay. First try to run the example app. 
1. Go to the Javascript [section](https://google.github.io/mediapipe/solutions/face_mesh.html#javascript-solution-api). 
2. Copy the code from `<!DOCTYPE html>` to `</html>` (that is the first code block) into a file. Save the file as an .html file.
3. Copy the code from `<script type="module">` to `</script>` (that is the second code block) and paste it BEFORE the `</body>` (closing body tag). Essentially, you need to include the script tag inside the body tag. 
4. Save the file and open it in a browser. 
5. The example app should run after giving camera permission.

**Comment by victorwilker12** [comment]
you need to implement the OnResults function:
EXAMPLE : https://github.com/google/mediapipe/blob/master/docs/solutions/face_mesh.md

```

function onResults(results) {
  canvasCtx.save();
  canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
  canvasCtx.drawImage(
      results.image, 0, 0, canvasElement.width, canvasElement.height);
  if (results.multiFaceLandmarks) {
    for (const landmarks of results.multiFaceLandmarks) {
      drawConnectors(canvasCtx, landmarks, FACEMESH_TESSELATION,
                     {color: '#C0C0C070', lineWidth: 1});
      drawConnectors(canvasCtx, landmarks, FACEMESH_RIGHT_EYE, {color: '#FF3030'});
      drawConnectors(canvasCtx, landmarks, FACEMESH_RIGHT_EYEBROW, {color: '#FF3030'});
      drawConnectors(canvasCtx, landmarks, FACEMESH_RIGHT_IRIS, {color: '#FF3030'});
      drawConnectors(canvasCtx, landmarks, FACEMESH_LEFT_EYE, {color: '#30FF30'});
      drawConnectors(canvasCtx, landmarks, FACEMESH_LEFT_EYEBROW, {color: '#30FF30'});
      drawConnectors(canvasCtx, landmarks, FACEMESH_LEFT_IRIS, {color: '#30FF30'});
      drawConnectors(canvasCtx, landmarks, FACEMESH_FACE_OVAL, {color: '#E0E0E0'});
      drawConnectors(canvasCtx, landmarks, FACEMESH_LIPS, {color: '#E0E0E0'});
    }
  }
  canvasCtx.restore();
}
```
