### ISSUE TITLE
Bad outline with selfie segmentation 

### ISSUE THREAD

**Issue by retwas** [google/mediapipe#3919]
**System information**  Windows 11

**My code:**
I use "default" code :
```
import cv2
import mediapipe as mp
import numpy as np
mp_drawing = mp.solutions.drawing_utils
mp_selfie_segmentation = mp.solutions.selfie_segmentation

IMAGE_FILES = []
BG_COLOR = (192, 192, 192)
MASK_COLOR = (255, 255, 255)
with mp_selfie_segmentation.SelfieSegmentation(
    model_selection=0) as selfie_segmentation:
  for idx, file in enumerate(IMAGE_FILES):
    image = cv2.imread(file)
    image_height, image_width, _ = image.shape
    results = selfie_segmentation.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

    condition = np.stack((results.segmentation_mask,) * 3, axis=-1) > 0.1

    fg_image = np.zeros(image.shape, dtype=np.uint8)
    fg_image[:] = MASK_COLOR
    bg_image = np.zeros(image.shape, dtype=np.uint8)
    bg_image[:] = BG_COLOR
    output_image = np.where(condition, fg_image, bg_image)
    cv2.imwrite('/tmp/selfie_segmentation_output' + str(idx) + '.png', output_image)
```

**Describe the current behavior:**
I have bad outline 
![image](https://user-images.githubusercontent.com/2582561/207024728-6266d6f9-1e3d-4ce8-8981-2f63dec8c3ce.png)
![image](https://user-images.githubusercontent.com/2582561/207024742-3d745e04-7c02-43f5-a705-0f5a1deac5c6.png)

**Describe the expected behavior:**
When I use it online it's perfect : https://codepen.io/mediapipe/pen/wvJyQpq
So, I use same camera in same room.

Perfect in js exemple (codeopen.io), but when I use the lib un python, I have bad outline. I can change condition (0.1 to 0.5), it's a little better. But compare to exemple online it's really bad.

I use RGB, BGR, level up contrast before put it to selfie_segmentation process but that's not better..

Do I need to use special image processing before give it to selfie segmentation process ?

**Comment by kuaashish** [comment]
Hi @retwas,
Would you let us know the complete details followed to reproduce the issue, sample images and different behaviour noticed in the both of case it will be very helpful for us to look deep issue from our end.

**Comment by retwas** [comment]
Thanks, for exemple you can see the result with this photo.
All the left side is detected as a person.

Original :
![b](https://user-images.githubusercontent.com/2582561/207440400-e25f095b-e2e5-4589-b85e-1eee52d976a7.jpg)

With mediapipe selfie segmentation : 
![out2](https://user-images.githubusercontent.com/2582561/207440449-df0c7615-14c8-4eaf-b326-3ec9834d9852.jpg)

![out33](https://user-images.githubusercontent.com/2582561/207440480-ba0537b6-9fa6-4ec4-acff-46127cf986a6.jpg)

**Comment by retwas** [comment]
Any idea ?

**Comment by kuaashish** [comment]
Hi @retwas,
This is a interesting finding, we will discuss this internally and let you know the cause of this or any possible solution.

**Comment by retwas** [comment]
> Hi @retwas, This is a interesting finding, we will discuss this internally and let you know the cause of this or any possible solution.

I noticed that it's better with model selection set to `Landscape` instead of `General` and with `Selfie Mode` set to `off`.

![Screenshot from 2022-12-20 09-51-17](https://user-images.githubusercontent.com/2582561/208624480-6f9fcbe9-eb4c-453f-823a-efaa32b9d840.png)

![Screenshot from 2022-12-20 09-51-29](https://user-images.githubusercontent.com/2582561/208624491-5ea9de9c-89a1-4223-8570-9d6d833eb74e.png)

![Screenshot from 2022-12-20 09-51-35](https://user-images.githubusercontent.com/2582561/208624506-d5570213-56b9-450c-ad14-2ad4de1508f2.png)

**Comment by retwas** [comment]
Any news ? :) Thanks

**Comment by kuaashish** [comment]
Hi @retwas,
This difference has observed because of the graphs(CPU vs GPU) used in the both of the platforms. Python uses the cpu-graph https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/face_detection.py#L25 and JavaScript(Web model) uses the gpu-graph https://github.com/google/mediapipe/blob/c688862570156908cd95303afb06beb0935e5cc6/mediapipe/modules/face_detection/face_detection_short_range_gpu.pbtxt.
