### ISSUE TITLE
Is it possible to place 3d object in java,C++ codein mediapipe application

### ISSUE THREAD

**Issue by nitesh123-kumar** [google/mediapipe#392]
I am working on mediapipe handtracking application and I am looking out to place a 3d object on one of the lankmark points of hand.Is is possible to place an 3d object in java code with tracking capability  or is it possible in c++ code or is it rendered by a mediapipe graph?

**Comment by khabya** [comment]
I have the same issue can anyone help?

**Comment by mgyong** [comment]
Placing 3D object on landmark point can be done using other frameworks like Coco3D that is independent of MediaPipe.
