### ISSUE TITLE
HelloWorld example is build successfully but it doesn't print # Hello World!

### ISSUE THREAD

**Issue by ArtanBerisha1** [google/mediapipe#3921]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): MacOS Ventura 13.0.1
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
```
Python 3.9.6
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
OpenJDK 64-Bit Server VM (build 11.0.13+0-b1751.21-8125866, mixed mode)
```
- Installed using virtualenv? pip? Conda? (if python):
`conda 22.9.0`
- [MediaPipe version](https://github.com/google/mediapipe/releases):
It should be the latest (I am not sure how to check that) since I have pulled the latest changes today
- Bazel version:
`bazel 5.2.0`
- Android SDK and NDK versions (if android): 
```
Found existing $ANDROID_HOME=/Users/artanberisha/Android/Sdk and $ANDROID_NDK_HOME=/Users/artanberisha/Android/Sdk/ndk-bundle/android-ndk-r21
Bazel will locate Android SDK and NDK automatically.
```

**Describe the problem**:

I am going thru the installation document of media pipe for macOS([here](https://google.github.io/mediapipe/getting_started/install.html)), and in the last step it says to run HelloWorld example in c++, with the following command:

```
bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/hello_world:hello_world
```
It says that I am going to get "Hello World" 10 times, but what I get is:

```
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (77 packages loaded, 1738 targets configured).
INFO: Found 1 target...
Target //mediapipe/examples/desktop/hello_world:hello_world up-to-date:
  bazel-bin/mediapipe/examples/desktop/hello_world/hello_world
INFO: Elapsed time: 0.622s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
dyld[45268]: symbol not found in flat namespace '_CFRelease'
```

I am confused since I don't know if should I check this problem or not, but since none of the other examples are working, I think I have to solve this issue first.

**Comment by ayushgdev** [comment]
Hi @ArtanBerisha1 
Can you please try the changes provided in [this](https://github.com/google/mediapipe/issues/3099#issuecomment-1346052098) comment ?

**Comment by kishor-e** [comment]
@ArtanBerisha1 Could you try setting this command again and see if it works? `$ export GLOG_logtostderr=1
`

**Comment by ArtanBerisha1** [comment]
Hi,
Thanks @ayushgdev your solution worked :)
