### ISSUE TITLE
Android Virtual Background solution developed from Selfie Segmenation

### ISSUE THREAD

**Issue by Vishnu39** [google/mediapipe#3923]
**System information** 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 12): Docker
- Mediapipe solution: Selfie Segmentation

I want to replace the background in Selfie segmentation (currently by default mediapipe use recolor_calculator.cc to color the background)
I have tried to use mask_overlay_calculator.cc (as recommended in other tickets) but end up having an error (mentioned below) related to null value . Any suggestions ?

Error Log:
E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.tst.selfiesegmentation, PID: 28298
    com.google.mediapipe.framework.MediaPipeException: invalid argument: ValidatedGraphConfig Initialization failed.
    PacketClonerCalculator::GetContract failed to validate: 
    For input streams ValidatePacketTypeSet failed:
    Failed to get tag "" index 1
    Tag "TICK" index 0 was not expected.
        at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
        at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:324)
        at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:553)
        at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:421)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:439)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:403)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:338)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$Y1vV_XyLsWZ0ebOvq-iwjQ0H3Sw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
I/Process: Sending signal. PID: 28298 SIG: 9

**My graph**

```
input_stream: "input_video"
input_stream: "background_video"
output_stream: "output_video"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node {
   calculator: "PacketClonerCalculator"
   input_stream: "TICK:throttled_input_video"
   input_stream: "background_video"
   output_stream: "throttled_background_video"
   input_stream_handler {
   input_stream_handler: "ImmediateInputStreamHandler"
   }
 }

node {
 calculator: "ImageTransformationCalculator"
 input_stream: "IMAGE_GPU:throttled_background_video"
 output_stream: "IMAGE_GPU:scaled_background_video"
 node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 1280
      output_height: 720
    }
  }
}


node {
  calculator: "SelfieSegmentationGpu"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "SEGMENTATION_MASK:segmentation_mask"
}

node {
  calculator: "MaskOverlayCalculator"
  input_stream: "VIDEO:0:scaled_background_video"
  input_stream: "VIDEO:1:throttled_input_video"
  input_stream: "MASK:segmentation_mask"
  output_stream: "IMAGE_GPU:output_video"
}
```

Frontend Android  way I pass background image to graph

        processor.setOnWillAddFrameListener(timestamp -> {
            imgNamePacket = processor.getPacketCreator().createString("buildings.jpg");
            processor.getGraph().addConsumablePacketToInputStream("background_video", imgNamePacket, timestamp);
            imgNamePacket.release();
        });

**Comment by ayushgdev** [comment]
Hello @Vishnu39 
The error is coming from the PacketClonerCalculator. If you check the source code for the [packet_cloner_calculator.cc](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/core/packet_cloner_calculator.cc#L148), it searches for the index 0 stream if tag TICK is given. Can you please try by removing the tag TICK from the PacketClonerCalculator?

**Comment by Vishnu39** [comment]
Hi @ayushgdev thanks for the suggestion I have seen the same issue on another ticket [https://github.com/google/mediapipe/issues/3405](url) ,so I have updated mediapipe to latest  as TICK  was added to PacketClonerCalculator on more recent version of mediapipe, now I have another error regarding packet type , please recommend.

`E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.tst.selfiesegmentation, PID: 16618
    com.google.mediapipe.framework.MediaPipeException: invalid argument: Graph has errors: 
    Packet type mismatch on calculator outputting to stream "background_video": The Packet stores "std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >", but "mediapipe::GpuBuffer" was requested.
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:407)
        at com.tst.selfiesegmentation.MainActivity.lambda$onResume$0$MainActivity(MainActivity.java:132)
        at com.tst.selfiesegmentation.-$$Lambda$MainActivity$efP67EyOfl0ixsnjnaiFIvsK0CI.onWillAddFrame(Unknown Source:2)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:444)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:485)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:413)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$Y1vV_XyLsWZ0ebOvq-iwjQ0H3Sw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)`

**Comment by ayushgdev** [comment]
The error specifies the packet type is not a mediapipe::GpuBuffer. Packet being pushed into the graph contains a String  , whereas the graph expects it to be mediapipe::GpuBuffer. 
Please make sure you are passing image to FrameProcessor via a GPU texture container like [SurfaceTexture](https://developer.android.com/reference/android/graphics/SurfaceTexture).

Also as a side note, I noticed there is a line in your code 
`imgNamePacket = processor.getPacketCreator().createString("buildings.jpg");`
Assuming the processor is FrameProcessor, `getPacketCreator` will return [AndroidPacketCreator](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/framework/AndroidPacketCreator.java), which does not have any method like `createString`.

**Comment by Vishnu39** [comment]
Thank you again @ayushgdev , I have made the changes so that i can convert imageframe to GPUbuffer by using [ImageFrameToGpuBufferCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/gpu/image_frame_to_gpu_buffer_calculator.cc) however i get an error regarding,  cant find object [ImageFrameToGpuBufferCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/gpu/image_frame_to_gpu_buffer_calculator.cc) Here is the error
`E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.tst.selfiesegmentation, PID: 19086
    com.google.mediapipe.framework.MediaPipeException: not found: ValidatedGraphConfig Initialization failed.
    No registered object with name: ImageFrameToGpuBufferCalculator; Unable to find Calculator "ImageFrameToGpuBufferCalculator"
        at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
        at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:336)
        at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:553)
        at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:421)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:439)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:485)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:413)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$Y1vV_XyLsWZ0ebOvq-iwjQ0H3Sw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
I/Process: Sending signal. PID: 19086 SIG: 9
`
Below is my code for graph **BUILD**

`load(
    "//mediapipe/framework/tool:mediapipe_graph.bzl",
    "mediapipe_binary_graph",
)

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "selfie_segmentation_gpu_deps",
    deps = [
        "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/gpu:image_frame_to_gpu_buffer_calculator",
        "//mediapipe/calculators/core:packet_cloner_calculator",
        "//mediapipe/calculators/image:image_transformation_calculator",
        "//mediapipe/calculators/image:mask_overlay_calculator",
        "//mediapipe/modules/selfie_segmentation:selfie_segmentation_gpu",
    ],
)

mediapipe_binary_graph(
    name = "selfie_segmentation_gpu_binary_graph",
    graph = "selfie_segmentation_gpu.pbtxt",
    output_name = "selfie_segmentation_gpu.binarypb",
    deps = [":selfie_segmentation_gpu_deps"],
)

cc_library(
    name = "selfie_segmentation_cpu_deps",
    deps = [
       "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/gpu:image_frame_to_gpu_buffer_calculator",
        "//mediapipe/calculators/core:packet_cloner_calculator",
        "//mediapipe/calculators/image:image_transformation_calculator",
        "//mediapipe/calculators/image:mask_overlay_calculator",
        "//mediapipe/modules/selfie_segmentation:selfie_segmentation_cpu",
    ],
)

mediapipe_binary_graph(
    name = "selfie_segmentation_cpu_binary_graph",
    graph = "selfie_segmentation_cpu.pbtxt",
    output_name = "selfie_segmentation_cpu.binarypb",
    deps = [":selfie_segmentation_cpu_deps"],
)
`

Below is the code for **selfie_segmentation_gpu.pbtxt**

`# MediaPipe graph that performs selfie segmentation with TensorFlow Lite on GPU.


input_stream: "input_video"

input_stream: "background_video"

output_stream: "output_video"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "background_video"
  output_stream: "gpubuffer_video"
}

node {
   calculator: "PacketClonerCalculator"
   input_stream: "TICK:throttled_input_video"
   input_stream: "gpubuffer_video"
   output_stream: "throttled_background_video"
   input_stream_handler {
   input_stream_handler: "ImmediateInputStreamHandler"
   }
 }

node {
 calculator: "ImageTransformationCalculator"
 input_stream: "IMAGE_GPU:throttled_background_video"
 output_stream: "IMAGE_GPU:scaled_background_video"
 node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 1280
      output_height: 720
    }
  }
}

node {
  calculator: "SelfieSegmentationGpu"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "SEGMENTATION_MASK:segmentation_mask"
}

node {
  calculator: "MaskOverlayCalculator"
  input_stream: "VIDEO:0:scaled_background_video"
  input_stream: "VIDEO:1:throttled_input_video"
  input_stream: "MASK:segmentation_mask"
  output_stream: "IMAGE_GPU:output_video"
}`

Below is the code for selfie_segmentation_cpu.pbtxt

`
input_stream: "input_video"

input_stream: "background_video"

output_stream: "output_video"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "background_video"
  output_stream: "gpubuffer_video"
}

node {
   calculator: "PacketClonerCalculator"
   input_stream: "TICK:throttled_input_video"
   input_stream: "gpubuffer_video"
   output_stream: "throttled_background_video"
   input_stream_handler {
   input_stream_handler: "ImmediateInputStreamHandler"
   }
 }

node {
 calculator: "ImageTransformationCalculator"
 input_stream: "IMAGE_GPU:throttled_background_video"
 output_stream: "IMAGE_GPU:scaled_background_video"
 node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 1280
      output_height: 720
    }
  }
}

node {
  calculator: "SelfieSegmentationCpu"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "SEGMENTATION_MASK:segmentation_mask"
}

node {
  calculator: "MaskOverlayCalculator"
  input_stream: "VIDEO:0:scaled_background_video"
  input_stream: "VIDEO:1:throttled_input_video"
  input_stream: "MASK:segmentation_mask"
  output_stream: "IMAGE_GPU:output_video"
}`

Thank you for time @ayushgdev .

**Comment by Vishnu39** [comment]
Hi @ayushgdev , I got the problem, its was that i didn't list [ImageFrameToGpuBufferCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/gpu/image_frame_to_gpu_buffer_calculator.cc) in aar BUILD ,

`load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_selfie",
    calculators = [
         "//mediapipe/calculators/core:flow_limiter_calculator",
         **"//mediapipe/gpu:image_frame_to_gpu_buffer_calculator",**
         "//mediapipe/calculators/core:packet_cloner_calculator",
        "//mediapipe/calculators/image:image_transformation_calculator",
        "//mediapipe/calculators/image:mask_overlay_calculator",
         "//mediapipe/modules/selfie_segmentation:selfie_segmentation_gpu"
        ],
)`

Now I end up in a new error regarding assets 

/data/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/selfiesegmentationgpu/BUILD:35:15: no such package 'mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic': error globbing [res/**] op=FILES: /data/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/res/layout (Input/output error) and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/selfiesegmentationgpu:selfiesegmentationgpu'

I will look into it ,
Thanks

**Comment by ayushgdev** [comment]
Hi @Vishnu39 
Can you please provide the **exact** steps to reproduce the issue at our end? With standard steps we are not able to reproduce the issue.
Suggested is to provide all the changes that you made as part of this implementation.

**Comment by Vishnu39** [comment]
Hi @ayushgdev ,
Issue was related to scope of resource files which I solved. Now its working fine . Its working fine.

**Comment by hezhubo** [comment]
> Hi @ayushgdev , Issue was related to scope of resource files which I solved. Now its working fine .

Hi @Vishnu39 , Can you tell me how you solved it?
