### ISSUE TITLE
How to get android pose detection visibility?

### ISSUE THREAD

**Issue by KenTee920806** [google/mediapipe#3924]
I would like to ask does mediapipe android pose detection API provide pose visibility instead of InFrameLikelihood score?

I studied the guide below and realize that it only provide InFrameLikelihood in this API.
[Pose Detection API](https://developers.google.com/ml-kit/vision/pose-detection)

Is there a method to get pose visibility?

Thanks for your helping!

**Comment by kuaashish** [comment]
Hi @KenTee920806,
Please allow us some time to look into the issue, will get back as soon as we can provide any useful pointers on issue.

**Comment by SharmaDhruv2511** [comment]
I want to contribute to this particular problem. Is anyone working on it???
@KenTee920806 
@kuaashish

**Comment by KenTee920806** [comment]
@SharmaDhruv2511 I am still waiting for @kuaashish to provide useful pointers on this issue.

**Comment by kuaashish** [comment]
Hello @KenTee920806,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
