### ISSUE TITLE
Face and Hand, Get world landmark position (holictic)

### ISSUE THREAD

**Issue by fishhead012** [google/mediapipe#3925]
I want to get 3d world landmark location of face and hand for unreal engine in holistic.

Pose world can be obtained in 3D world coordinate system, but I don't know how to do face and hand.

**Comment by kuaashish** [comment]
Hi @fishhead012,
Could you elaborate your query with complete details such as platform you are referring to and complete details to reproduce the issue from our end.

**Comment by jinfagang** [comment]
@kuaashish Did u solved your problem? Got same here
