### ISSUE TITLE
error whilst running setup.py protoc is not found 

### ISSUE THREAD

**Issue by Lord-Duck** [google/mediapipe#3928]
- windows 10
- python 11
- installed using a venv
- latest media pipe version
- opencv 4.6

i have the path of protoc in my envioment varibles but i get a error running setup.py: 'protoc is not found'.
i extracted the mediapipe files installed the dependencies, extracted protoc and added it to my PATH envioment varible. ran setup.py and i get the error 

logs:
py setup.py install --link-opencv
UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running install
SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running build
running build_py
running gen_protos
protoc is not found. Please run 'apt install -y protobuf-compiler' (linux) or 'brew install protobuf'(macos) to install protobuf compiler binary.

**Comment by Lord-Duck** [comment]
i have found the problem to be vs codes built in terminal but a new problem arose :
running build
running build_py
running gen_protos
running generate_metadata_schema
error: [WinError 2] The system cannot find the file specified

**Comment by kuaashish** [comment]
Hi @Lord-Duck,
Would you let us know the complete steps followed to build the mediapipe to address issue better from our end.

**Comment by Lord-Duck** [comment]
i was in my venv that i have been using for some time now and i proceeded to unzip the master folder and then install the requirements. afterthat i then did the command: python3 setup.py install --link-opencv

**Comment by kuaashish** [comment]
Hi @Lord-Duck,
Does this similar closed issue [#2051(comment)](https://github.com/google/mediapipe/issues/2051#issuecomment-844853243) resolves the issue?

**Comment by Lord-Duck** [comment]
sorry no my system has protoc working fine 
![image](https://user-images.githubusercontent.com/85259422/209213318-2940000a-a800-4f38-b321-e251d6bcc6b1.png)

**Comment by kuaashish** [comment]
Hi @Lord-Duck,
Looks like the issue with the python version as mentioned in the issue description. Mediapipe has no official support for Python 3.11 yet. You can try with the version 3.7-3.10 to build mediapipe and please let us know if you need further support on this.

**Comment by Lord-Duck** [comment]
i tryed that already, still the same error

**Comment by kuaashish** [comment]
@ayushgdev,
Could you look into this issue.

**Comment by ayushgdev** [comment]
@Lord-Duck Please try the changes as provided in [this](https://github.com/google/mediapipe/issues/3101#issuecomment-1053214940) comment. The user faced exactly same error of [WinError 2]. 
If error related to Python Lib path are thrown,create PYTHON_LIB_PATH as an environment variable with its value pointing to the absolute path to **Lib** directory inside Python installation directory.

**Comment by Lord-Duck** [comment]
i have done this already yet still i get the error
![image](https://user-images.githubusercontent.com/85259422/209555206-8d337aa3-e380-4d65-a19a-2d7b2b1e7ab5.png)

**Comment by ayushgdev** [comment]
Hello @Lord-Duck 
From the PYTHON_LIB_PATH path, it seems you are using Python 3.11 version. Please use Python 3.10 version for both PATH variable and PYTHON_LIB_PATH,  and then retry building python package.
