### ISSUE TITLE
Slicing wavefront file for different rendering scenarios

### ISSUE THREAD

**Issue by indradeepc** [google/mediapipe#3933]
Hi All,
I am super new to play around with 3D objects. My goal is to put a glass ([OBJ_Glass.obj](https://skfb.ly/oBFJL)) on a canonical face ([canonical_face_model.obj](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_geometry/data/canonical_face_model.obj)) provided by mediapipe. I am using python for accomplishing the task. I have successfully appended the glass on the face but still struggling with some issues

I am unable to figure out

1.	How to divide obj.faces for different rendering scenarios.
2.	How to use the canonical face as an occluder to hide glass arms behind facial points.

Thanks for any suggestions

**Comment by ayushgdev** [comment]
Hello @indradeepc 
Can you please provide more details on the use case along with the platform, solution, OS, etc.? We advise using the [new issue template](https://github.com/google/mediapipe/issues/new/choose) while creating the issues to provide the maximum relevant information.
