### ISSUE TITLE
Building abc/libmain.jar (7 source files) and running annotation processors (AutoValueProcessor, AutoBuilderProcessor) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:-

### ISSUE THREAD

**Issue by dharmeshdevstree** [google/mediapipe#3934]
Hello
I am getting this error related to AutoValueProcessor
Error:(7, 15) Building abc/libmain.jar (7 source files) and running annotation processors (AutoValueProcessor, AutoBuilderProcessor) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 17 arguments skipped)

Error:(71, -1) cannot access MessageLiteOrBuilder
Error:(71, -1) cannot access Parser
Error:(77, -1) cannot access GeneratedMessageLite

![image](https://user-images.githubusercontent.com/86298602/208368807-59b34afc-cbc3-4967-9e1d-e3afe13e03d1.png)

Bazel version : 5.4.0

Anyone have an idea it's appreciable.
Thanks

**Comment by kuaashish** [comment]
Hi @dharmeshdevstree,
Would you let us know the complete steps to reproduce the issue to address the issue better from our end? 
Please share the system information to do the external troubleshooting as mentioned in the [template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=00-build-installation-issue.md).

**Comment by dharmeshdevstree** [comment]
Hello @kuaashish 
Thanks for response.
First, i import project using bazel plugin in Android studio,
I created solution_core.aar file as per mediapipe doc and put in my project inside libs folder.
In workspace and BUILD folders added permission and maven install syntax.
in build folder solution_core.aar import using aar_import.
After above step setup when i sync bazel sync at that moment getting above error.

Anything related to BAZEL version? I am using 5.4.0

Thanks

**Comment by kuaashish** [comment]
Hi @dharmeshdevstree,
Are you able to build successfully the hello_world example as mentioned in [documentation](https://google.github.io/mediapipe/getting_started/android.html#prerequisite)? We need additional information about operating system where above error is taking place.

**Comment by dharmeshdevstree** [comment]
Hello @kuaashish 
Yes i am able to build Hello_world example successfully

**Comment by dharmeshdevstree** [comment]
Hi @ayushgdev, @kuaashish 
Please help me on above issue
Thanks

**Comment by kuaashish** [comment]
Hi @dharmeshdevstree,
Could you inspect the following and get us back if pointers will not work in your case:

- Try downgrading the bazel version to 5.2.0.
- Try with different JDK versions (Refer to bazel thread [#5572](https://github.com/bazelbuild/bazel/issues/5572))
