### ISSUE TITLE
"3D object detection" Incorrect output with desktop &  Windows platform & C++

### ISSUE THREAD

**Issue by JiSight** [google/mediapipe#3935]
**System information** (Please provide as much relevant information as possible)
- windows11:
- CPU -- Intel:
-  C++:
-  Desktop: 

**Describe the problem**:
Follow[ the official tutorial instructions](https://google.github.io/mediapipe/solutions/objectron), compile and run 
The result is not rendered in the final output video
Is it a usage error on my part?

1.  Build
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D://CodeEnvironment//Python//Python310//python.exe" mediapipe/examples/desktop/object_detection_3d:objectron_cpu
![2b5c5a944f1ecb7176099920a19bc11](https://user-images.githubusercontent.com/75829346/208370068-b4bc4769-1527-4f4d-aa8b-a4df6da7a573.png)

2.  Run
bazel-bin\mediapipe\examples\desktop\object_detection_3d\objectron_cpu --calculator_graph_config_file=mediapipe/graphs/object_detection_3d/objectron_desktop_cpu.pbtxt --input_side_packets="input_video_path=d:/cup.mp4,output_video_path=d:/cup_video_x.mp4,box_landmark_model_path=mediapipe/modules/objectron/object_detection_3d_cup.tflite,allowed_labels=Mug"

![b8133ea68a69e72f6401ea28253702c](https://user-images.githubusercontent.com/75829346/208370229-ca5f4797-efca-4599-9111-051a8542a1b4.png)

 
My Video assets

https://user-images.githubusercontent.com/75829346/208370369-711fad69-4aa8-40b8-9125-db387a882758.mp4

**Comment by ayushgdev** [comment]
Hi @JiSight 
The commands you are running are correct. However, we do not support native Windows officially as of now. 
On copying and running the same commands on Mac, they are running fine and detecting the objects. So it can be the issue with Windows only. 
If possible, would you please try running on different OS? The officially supported OS are listed [here](https://google.github.io/mediapipe/getting_started/faq.html#can-i-run-mediapipe-on-ms-windows).

**Comment by JiSight** [comment]
> Hi @JiSight The commands you are running are correct. However, we do not support native Windows officially as of now. On copying and running the same commands on Mac, they are running fine and detecting the objects. Please check the video attached.
> 
>  cups_annotated.mp4 
> So it can be the issue with Windows only. If possible, would you please try running on different OS? The officially supported OS are listed [here](https://google.github.io/mediapipe/getting_started/faq.html#can-i-run-mediapipe-on-ms-windows).


**Reply**
Thank you very much for your reply. @ayushgdev 

From the table below, you can see that Objectron should be supported:
![624f768eb0b603fcbcdf5aa7301b2a2](https://user-images.githubusercontent.com/75829346/208538478-5e50f0ad-f7e1-4b20-8b5d-97516262047f.png)

I have tried almost all the C++ supported solutions in this table, 
 Can be executed in win11,

Maybe there's a **bug** here

**Comment by JiSight** [comment]
@ayushgdev 
Got it
Unfortunately, I can't debug this Code,
The problem should be in the "BoxLandmarkSubgraph" section,
Thank you for your patient reply
Thank you

**Comment by ayushgdev** [comment]
@JiSight I understand the problem you are facing. However, would you please try to run it in Ubuntu or Mac and check if you encounter the similar issue? Since the solution is working as provided in examples on Mac at our end, we still suspect it can be Windows issue.
