### ISSUE TITLE
Class CaptureDelegate is implemented in both··· Use in iOS app framework

### ISSUE THREAD

**Issue by Epoch2022-iOS** [google/mediapipe#3936]
`
- Class CaptureDelegate is implemented in both···
- Class CvAbstractCamera is implemented in both···
- Class CvPhotoCamera is implemented in both···
- Class CvVideoCamera is implemented in both···
- Class MPPGraph is implemented in both···
- Class MPPTimestampConverter is implemented in both···
- Class GUSUtilStatusWrapper is implemented in both···
- Class MPPGraphGPUData is implemented in both···
- Class TFLBufferConvert is implemented in both···
- Class MPPMetalUtil is implemented in both···
- Class MPPMetalHelper is implemented in both···
- Class CaptureDelegate is implemented in both··· 
- Class CvAbstractCamera is implemented in both···
- Class CvPhotoCamera is implemented in both···
- Class CvVideoCamera is implemented in both···`

When I user Face track and hand Track, Xcode Conslog output this error msg.

**Comment by Epoch2022-iOS** [comment]
this is my work demo :[https://github.com/Epoch2022-iOS/FaceAndHand](url)

**Comment by kuaashish** [comment]
Hi @Epoch2022-iOS,
Are you trying to build/integrate the two solution in a app? Would you let us know the complete steps which you have followed and the provided work demo is not working in my case.

**Comment by Epoch2022-iOS** [comment]
yeah, I want build the hands and face detection solution in a app at the same time. But I get the error.
according to my own guess.I made the framework, if you want working it, you can download it with [[https://github.com/Epoch2022-iOS/FaceAndHand](https://github.com/google/mediapipe/issues/url)](url)

when finish download. copy it to your mediapipe file. and use `bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/facegeometry:MPPBFaceGeometry`to build it.

**Comment by Epoch2022-iOS** [comment]
> Hi @Epoch2022-iOS,
> Are you trying to build/integrate the two solution in a app? Would you let us know the complete steps which you have followed and the provided work demo is not working in my case.

yeah, I want build the hands and face detection solution in a app at the same time. But I get the error.
according to my own guess.I made the framework, if you want working it, you can download it with [[https://github.com/Epoch2022-iOS/FaceAndHand](https://github.com/google/mediapipe/issues/url)](url)

when finish download. copy it to your mediapipe file. and use bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/facegeometry:MPPBFaceGeometryto build it.

**Comment by Epoch2022-iOS** [comment]
> Hi @Epoch2022-iOS,
> Are you trying to build/integrate the two solution in a app? Would you let us know the complete steps which you have followed and the provided work demo is not working in my case.

Here's another thing I tried today:
I have made two frameworks respectively, one is hands framework and the other is face detection framework.
The two frameworks work fine independently, but when I copy them into the same project, the above file duplication problem occurs.
this is my work file:[https://github.com/Epoch2022-iOS/DoubleFrameworkTest-iOS.git](url)

**Comment by kuaashish** [comment]
Hi @Epoch2022-iOS,
MediaPipe iOS builder is only designed to support a single iOS file per application. If you have archived linking two or more solutions in a single library, we can consider some instructions for other users.

**Comment by Epoch2022-iOS** [comment]
> Hi @Epoch2022-iOS,
> MediaPipe iOS builder is only designed to support a single iOS file per application. If you have archived linking two or more solutions in a single library, we can consider some instructions for other users.

thanks. We just want use face and hand detection at one project. or you can download my work with [link:](https://github.com/Epoch2022-iOS/DoubleFrameworkTest-iOS), if you can help us soul the error, then we can deal the aim.

**Comment by kuaashish** [comment]
@Epoch2022-iOS,
MediaPipe solutions are designed to support the single iOS/Android file per application and team has not been tested such implementation if you could able to build such application with two or more solutions that we can good to include in the documentation. Thank you!

**Comment by suyashjoshi** [comment]
having same problem!
