### ISSUE TITLE
fd leak in facemesh

### ISSUE THREAD

**Issue by chenguoting** [google/mediapipe#3938]
ImageSolutionBase new a EglManager instance in initialize(). but not release it in close().
it cause fd leak.

**Comment by kuaashish** [comment]
Hi @chenguoting,
Would you let us know the solution you are trying, platform which you are referring Python, JavaScript and share the complete steps followed to understand the issue better from our end.

**Comment by chenguoting** [comment]
> Hi @chenguoting, Would you let us know the solution you are trying, platform which you are referring Python, JavaScript and share the complete steps followed to understand the issue better from our end.

I use java.
implementation 'com.google.mediapipe:solution-core:0.8.1-alpha-1'
implementation 'com.google.mediapipe:facemesh:0.8.11-alpha-1'

**Comment by kuaashish** [comment]
@chenguoting,
Are you still resolution for the issue raised? If yes, As from description it is not clear that exact steps followed to reproduce the issue. We recommend to fill the [template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abug&template=bug_issue_template.yaml) to get maximum relevant information to help the issue you are facing. Thank you!
