### ISSUE TITLE
Why the drawn coordinate points do not disappear

### ISSUE THREAD

**Issue by 459zyt** [google/mediapipe#3941]
I draw human body coordinate points on a black window, but the coordinate points will remain even if there is no human body in that place.How to make these points disappear normally.This is code.
![image](https://user-images.githubusercontent.com/94236736/209064641-3824cc44-3693-4d19-808f-d2624fbb0e76.png)

```
import cv2
import numpy as np
import mediapipe as mp

cap = cv2.VideoCapture('show.mp4')
height,width=480,852
blank_image = np.zeros((height,width,3), np.uint8)

mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while (cap.isOpened()):

        ret, frame = cap.read()
        if ret :
            image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            image.flags.writeable = False
            results=pose.process(image)
            image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
            mp_drawing.draw_landmarks(blank_image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS,
                                      mp_drawing.DrawingSpec(color=(245, 117, 66), thickness=2, circle_radius=2),
                                      mp_drawing.DrawingSpec(color=(245, 66, 230), thickness=2, circle_radius=2)
                                      )
            cv2.imshow("",image)
            cv2.imshow(" ",blank_image)
            if cv2.waitKey(25) & 0xFF == ord('q'):
                break


        else:
            break


cap.release()


cv2.destroyAllWindows()

**Comment by ayushgdev** [comment]
Hi @459zyt 
There is a bug in initialisation of the `blank_image` in the given code. The `blank_image` is only initialised once and the landmarks are being drawn on the same numpy array again and again. That is why you see all the landmarks together collected over time. Simply move this line 
```
blank_image = np.zeros((height,width,3), np.uint8)
```
to place it AFTER `ret, frame = cap.read()`.

**Comment by 459zyt** [comment]
> 你好@459zyt`blank_image`给定代码中的 初始化存在错误。仅初始化一次，`blank_image`地标一次又一次地绘制在同一个 numpy 数组上。这就是为什么您会看到所有地标随时间收集在一起的原因。只需移动这条线
> 
> ```
> blank_image = np.zeros((height,width,3), np.uint8)
> ```
> 
> 将它放在 AFTER 之后`ret, frame = cap.read()`。

Thanks
