### ISSUE TITLE
Android build crashes when model_complexity set to 0 in posetrackinggpu

### ISSUE THREAD

**Issue by Raghav997** [google/mediapipe#3942]
Issue: 
When building with model_complexity set to 0 (through variable `select: 0`) in `pose_landmark_model_loader.pbtxt`  the app crashes. It works fine when the same is default of 1. I'm simply running the sample app with only this change.

Platform: Android Mobile

Errors: No error while building, app apk starts and crashes.

**Comment by kuaashish** [comment]
Hi @Raghav997,
This can be an interesting finding. Would you let us know the complete steps followed to build the aar to understand the issue better. We suggest to fill the [template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=00-build-installation-issue.md) to get maximum information to debug on the issue.

**Comment by Raghav997** [comment]
I just followed basic instructions given here.
[(https://google.github.io/mediapipe/getting_started/android.html)]

To replicate, just follow the instructions. You'll see the "1" model is working whereeas the lite "0" is crashing.

**Comment by Raghav997** [comment]
Any update on this?

**Comment by kuaashish** [comment]
Hi @Raghav997, 
It looks like the two of one Tflite model files being missing from build file

  "[third_party/mediapipe/modules/pose_landmark/pose_landmark_lite.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/BUILD#L170)" missing.
  "[third_party/mediapipe/modules/pose_landmark/pose_landmark_full.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/BUILD#L168)" found.

Could you verify that "pose_landmark_lite" is actually missing from the BUILD file? If missing, you might need to add the dependency to pose_landmark_lite.tflite to the BUILD file.

**Comment by taeyeonlee** [comment]
In Ubuntu, I just downloaded the mediapipe git source ($ git clone https://github.com/google/mediapipe.git) and build the holistictrackinggpu android solution.
$ bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/holistictrackinggpu:holistictrackinggpu
and the holistictrackinggpu.apk (which was built in the bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/holistictrackinggpu/holistictrackinggpu.apk) is working well on my Android Phone.

Do you know how to set 0 for the value "model_complexity" for holistictrackinggpu Android ?
I just modified the mediapipe/mediapipe/modules/pose_landmark/pose_landmark_model_loader.pbtxt  as like below.
                node {
                       calculator: "SwitchContainer"
                       input_side_packet: "SELECT:model_complexity"
                       output_side_packet: "PACKET:model_path"
                       options: {
                                       [mediapipe.SwitchContainerOptions.ext] {
                                         select: 1				
and built again ($ bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/holistictrackinggpu:holistictrackinggpu)
but the holistictrackinggpu.apk is not working on the Android Phone.
I want to set 0 for the value "model_complexity" for holistictrackinggpu android.
