### ISSUE TITLE
com.google.mediapipe.framework.MediaPipeException: not found: ValidatedGraphConfig Initialization failed.

### ISSUE THREAD

**Issue by dharmeshdevstree** [google/mediapipe#3943]
Hi
No registered object with name: HolisticLandmarkCpu; Unable to find Calculator "HolisticLandmarkCpu"
No registered object with name: HolisticTrackingToRenderData; Unable to find Calculator "HolisticTrackingToRenderData"
No registered object with name: AnnotationOverlayCalculator; Unable to find Calculator "AnnotationOverlayCalculator"

I am using solution_core.aar file in my project.
Application install successfully and when i call setupStreamingModePipeline method and try to open steaming part at that moment getting above error.
Anyone can give suggestion how to registered in my project after i used AAR file.
If any one have solution_core.aar file please share with binarypb and tflite for assets folder.
Bazel version : 6.0.0
OS : Ubuntu 20.04   64 bit
Thanks

**Comment by ayushgdev** [comment]
Hi @dharmeshdevstree 
Please make sure you have added these calculators to the list of calculators in holistic solution AAR BUILD tracking file; particularly, in the bazel function `mediapipe_aar()`, `calculators` property. 
Also, I see the `bazel` version you are using is 6.0.0. It is advised to install [bazelisk](https://github.com/bazelbuild/bazelisk) and then build the solution with .bazelversion file stating the predefined version only.

**Comment by dharmeshdevstree** [comment]
Hello @ayushgdev 

Thanks for reply.

I added calculators property.
![image](https://user-images.githubusercontent.com/86298602/209281014-283d9139-41a4-4ec4-96e6-5590307ec80d.png)

And generated solution_core.aar file using
bazel build --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/java/com/google/mediapipe/solutioncore:solution_core
command. (If anything miss to generate aar file please let me know).

Target //mediapipe/java/com/google/mediapipe/solutioncore:solution_core up-to-date:
  bazel-bin/mediapipe/java/com/google/mediapipe/solutioncore/solution_core.aar
  
This is the path AAR file generated.

After i added above AAR file in my project still gettting below error.
![image](https://user-images.githubusercontent.com/86298602/209281407-a83dc60b-b19d-4856-a3e9-a21ff4ae3510.png)

Please suggest on above things and it's appriciated.
Thanks

**Comment by ayushgdev** [comment]
Hello @dharmeshdevstree 
Can you please try building the FaceDetection AAR first and let us know if that works for you?
