### ISSUE TITLE
Errors Running AutoFlip Using Docker: "Can't find file: mediapipe/models/ssdlite_object_detection.tflite"

### ISSUE THREAD

**Issue by Kelach** [google/mediapipe#3946]
Hello! 

**System information** (Please provide as much relevant information as possible)
- **Windows** 11
- **Docker Engine**: v20.10.21
- **Pyhton** 3.8.10
- **OpenCV** 4.6.0
- **Bazel** 5.2.0
- **Programming Language:** C++, Python, 
- **Solution** AutoFlip

**Describe the expected behavior:**
I want to successfully run AutoFlip using Docker (Desktop)

**Standalone code you may have used to try to get what you need :**

I am able to build AutoFlip in my "MediaPipe" Docker container :

    bazel build -c opt --verbose_failures --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/autoflip:run_autoflip

But after running this:
     
    GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip --
    calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt -- 
    input_side_packets=input_video_path=/mediapipe/life_at_google.mp4,
    output_video_path=/mediapipe/life_at_google_edit.mp4,aspect_ratio=1:1

I get this error:

    I20221223 16:34:19.086550  7955 simple_run_graph_main.cc:122] Initialize the calculator graph.
    I20221223 16:34:19.087823  7955 simple_run_graph_main.cc:137] Start running the calculator graph.
    E20221223 16:34:19.164170  7955 simple_run_graph_main.cc:149] Failed to run the graph: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "OpenCvVideoDecoderCalculator" failed: ; OpenCVVideoDecoderCalculator can't save the audio file 
    because FFmpeg is not installed. Please remove output_side_packet: "SAVED_AUDIO_PATH" from the node config.

I follow the intructions to modify my node config, but when I re-run i get this error:

    I20221223 18:09:08.977695  7972 simple_run_graph_main.cc:122] Initialize the calculator graph.
    I20221223 18:09:08.979044  7972 simple_run_graph_main.cc:137] Start running the calculator graph.
    W20221223 18:09:09.028327  7972 opencv_video_decoder_calculator.cc:230] Not all the frames are decoded (total frames: 3920 vs 
    decoded frames: 0).
    E20221223 18:09:09.029410  7972 simple_run_graph_main.cc:149] Failed to run the graph: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "autoflipobjectdetectionsubgraph__TfLiteInferenceCalculator" failed: ; Can't find file: 
    mediapipe/models/ssdlite_object_detection.tflite

In the folder mentioned in this error there is only a [BUILD](https://github.com/google/mediapipe/tree/master/mediapipe/models) file, but it only "mentions" "ssdlite_object_detection.tflite". 

What am I doing wrong?

## **A Last Note**: 
The MediaPipe Docs say AutoFlip only works with OpenCV3. However, the Docker image I build after following the MediaPipe installation instructions uses OpenCV 4, and I don't know how to go about downgrading OpenCV3 in this context (I don't have much experience with Docker).

**Comment by dungtam73** [comment]
Check this issues: 
[https://github.com/google/mediapipe/issues/3698](url)

You can checkout from here then put all model file into **mediapipe/models**
[https://github.com/dungtam73/MediapipeModels.git](url)

**Comment by Kelach** [comment]
Thank you, downloading the models files into that directory worked. But do you know how I could also fix the first Error? " OpenCVVideoDecoderCalculator can't save the audio file 
because FFmpeg is not installed." Ideally, I'd like to preserve the audio. 
### Note: 
Running "ffmpeg -version" to verify I have it installed returns this output:

```
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --
incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-
filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-
libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --
enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-
libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine 
--enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100


```

**Comment by ayushgdev** [comment]
@Kelach Output of `ffmpeg -version` indicates you have it installed and the system/container is able to recognise the command. 
However, the MediaPipe might not be able to pick it up and that is why it might be throwing error.
Can you check in the WORKSPACE file that the path to the ffmpeg program is correct or not for your container?
1. Open terminal within the container and run the command `which ffmpeg`. This points to the directory your system is finding the ffmpeg in.
2. In WORKSPACE file, search for 
```
new_local_repository(
    name = "linux_ffmpeg",
```
and check the path.
The path should match the output given by the command `which ffmpeg`.

**Comment by Kelach** [comment]
Hi, @ayushgdev sorry for the delayed response. Thank you for the explanation. I checked my WORKSPACE and found:

```
new_local_repository(
    name = "linux_ffmpeg",
    build_file = "@//third_party:ffmpeg_linux.BUILD",
    path = "/usr"
)
```
Running "which ffmpeg" in the container shows that the program is actually located here:

`/usr/bin/ffmpeg`

To fix, I modified the ffmpeg path in my WORKSPACE to:
```
new_local_repository(
...
...
    path = "/usr/bin"
)
```

I reubuild (both the Docker image, and then AutoFlip), and then re-run the command:
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip --
calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt -- 
input_side_packets=input_video_path=/mediapipe/life_at_google.mp4,
output_video_path=/mediapipe/life_at_google_edit.mp4,aspect_ratio=1:1
```

But still get the same error:

```
I20221228 19:10:15.906983  8425 simple_run_graph_main.cc:122] Initialize the calculator graph.
I20221228 19:10:15.918859  8425 simple_run_graph_main.cc:137] Start running the calculator graph.
E20221228 19:10:16.032655  8425 simple_run_graph_main.cc:149] Failed to run the graph: CalculatorGraph::Run() failed in Run:
Calculator::Open() for node "OpenCvVideoDecoderCalculator" failed: ; OpenCVVideoDecoderCalculator can't save the audio file because FFmpeg is not installed. Please remove output_side_packet: "SAVED_AUDIO_PATH" from the node config.
```
Which means MediaPipe still cannot find ffmpeg? But Why?

**Comment by ayushgdev** [comment]
Hello @Kelach 
Apologies for the late reply. Can you please try building OpenCV from source using script [here](https://github.com/google/mediapipe/blob/master/setup_opencv.sh) and including that in MediaPipe?
Meanwhile, we are also working at our end to check the root cause of the issue.

**Comment by Kelach** [comment]
hi @ayushgdev apologies for the late reply. I'm now facing errors trying to build OpenCV from source using the shell script in the MediaPipe root directory.

when I run: ```sh ./setup_opencv.sh```

I get the following error:
```
: not foundncv.sh: 27: 
./setup_opencv.sh: 28: set: Illegal option -
```


I tried running ```bash ./setup_opencv.sh``` but got some errors (different) again:

```
./setup_opencv.sh: line 27: $'\r': command not found
: invalid optionh: line 28: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./setup_opencv.sh: line 46: syntax error near unexpected token `elif'
'/setup_opencv.sh: line 46: `    elif [[ -x "$(command -v dnf)" ]]; then
```

Is there another way I should be trying to build OpenCV from source in  my docker container?

**Comment by ayushgdev** [comment]
Hello @Kelach 
Thanks for informing of this issue with the script. We realise there is an update needed to ./setup_opencv.sh, thanks to your comment.
You can refer Option 3 [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu) to build OpenCV from source and set it up on docker.

**Comment by Ananya0703** [comment]
> Check this issues: [https://github.com/google/mediapipe/issues/3698](url)
> 
> You can checkout from here then put all model file into **mediapipe/models** [https://github.com/dungtam73/MediapipeModels.git](url)

Hi Could you share a link for the models. I am facing the same issue abt the files not being in the mediapipe/models directory. I clicked on the link above but seems to be expired/invalid
