### ISSUE TITLE
build_android_examples.sh fails with Operation not permitted: '/usr/local/bin/python3'

### ISSUE THREAD

**Issue by visharma0** [google/mediapipe#3947]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): macOS Ventura 13.1, Android 13
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): 
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Java
- Installed using virtualenv? pip? Conda? (if python): brew
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:
I'm following the instructions at https://google.github.io/mediapipe/getting_started/android.html and executing the script to build all android examples but it's failing. On a separate note, I've previously been able to run the helloworld example.

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

 ./build_android_examples.sh -d out_dir

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:
app_dir: mediapipe/examples/android/src/java/com/google/mediapipe/apps
out_dir: out_dir
strip: true
Switching to OpenCV 3
=== Target: mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
WARNING: /Users/vsharma/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /Users/vsharma/mediapipe/mediapipe/framework/tool/BUILD:184:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld (27 packages loaded, 7242 targets configured).
INFO: Found 1 target...
INFO: From Linking external/com_google_absl/absl/flags/libflag.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_absl/absl/flags/_objs/flag/flag.o has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: bazel-out/host/bin/external/com_google_absl/absl/flags/libflag.a the table of contents is empty (no object file members in the library define global symbols)
INFO: From Linking external/com_google_absl/absl/base/libbase.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_absl/absl/base/_objs/base/unscaledcycleclock.o has no symbols
INFO: From Linking external/com_google_absl/absl/types/libbad_optional_access.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_absl/absl/types/_objs/bad_optional_access/bad_optional_access.o has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: bazel-out/host/bin/external/com_google_absl/absl/types/libbad_optional_access.a the table of contents is empty (no object file members in the library define global symbols)
INFO: From Linking external/com_google_absl/absl/debugging/libdebugging_internal.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_absl/absl/debugging/_objs/debugging_internal/elf_mem_image.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_absl/absl/debugging/_objs/debugging_internal/vdso_support.o has no symbols
INFO: From Linking external/com_google_absl/absl/strings/libstrings.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_absl/absl/strings/_objs/strings/string_view.o has no symbols
INFO: From Linking external/com_google_protobuf/libprotobuf.lo [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/error_listener.o has no symbols
ERROR: /private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/external/maven/BUILD:404:11: AarResourcesExtractor external/maven/_aar/unzipped/resources/androidx_legacy_legacy_support_v4 failed: (Exit 1): aar_resources_extractor failed: error executing command bazel-out/darwin-opt-exec-50AE0418/bin/external/bazel_tools/tools/android/aar_resources_extractor --input_aar ... (remaining 9 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/sandbox/darwin-sandbox/2766/execroot/mediapipe/bazel-out/darwin-opt-exec-50AE0418/bin/external/bazel_tools/tools/android/aar_resources_extractor", line 392, in <module>
    Main()
  File "/private/var/tmp/_bazel_vsharma/e7d47f5c8a5e8b13df96b5c75b03757d/sandbox/darwin-sandbox/2766/execroot/mediapipe/bazel-out/darwin-opt-exec-50AE0418/bin/external/bazel_tools/tools/android/aar_resources_extractor", line 382, in Main
    os.execv(args[0], args)
PermissionError: [Errno 1] Operation not permitted: '/usr/local/bin/python3'
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 217.361s, Critical Path: 214.19s
INFO: 667 processes: 131 internal, 509 darwin-sandbox, 27 worker.
FAILED: Build did NOT complete successfully

**Comment by kuaashish** [comment]
Hi @visharma0,
From the logs seems issue with the MacOS permission to access the command from terminal. Please try the following steps and let us know if error still persists:

- Go to **System Settings**-> **Privacy and Security**.
- On the right side click on **Full Disk Access**.
-  Provide the access to **Terminal** option and enter the required password.
- Now Terminal added with permission.

**Comment by VelvetAcidChrist** [comment]
Same problem, only on Windows. I ran terminal and powershell and command line both normally and as administrator:

```
PS I:\AndroidSD\Models> python convert.py --ckpt_path I:/AndroidSD/Models/ --output_path I:/AndroidSD/Models/android-models/
Traceback (most recent call last):
  File "I:\AndroidSD\Models\convert.py", line 51, in <module>
    app.run(main)
  File "C:\Users\AcidChrist\AppData\Local\Programs\Python\Python310\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\AcidChrist\AppData\Local\Programs\Python\Python310\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "I:\AndroidSD\Models\convert.py", line 48, in main
    run(ckpt_path, output_path)
  File "I:\AndroidSD\Models\convert.py", line 27, in run
    ckpt = th.load(ckpt_path, map_location="cpu")
  File "C:\Users\AcidChrist\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\AcidChrist\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\AcidChrist\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'I:/AndroidSD/Models/'
```
