### ISSUE TITLE
how to use static image work in ios? 

### ISSUE THREAD

**Issue by lxm1799** [google/mediapipe#3948]
hi team!
I have tried many ways to use static pictures to detect faces or gestures, but all is failed 
so could u can support this ?
1、support use static image detect
2、support to got the  detect score

**Comment by lxm1799** [comment]
Oh, it's because I misunderstood it before. Now I can use static image detection, but I'm still looking for a way to get socre

**Comment by ayushgdev** [comment]
Hello @lxm1799 
Would you please elaborate your query with details so that we can provide prompt resolution. We advise to use the [new issue template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=00-build-installation-issue.md) to while opening new issues.

**Comment by lxm1799** [comment]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution : mini(2018 i7)、 macOS:Ventura 13.0
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:5.2.0
- XCode and Tulsi versions (if iOS): xcode:14.0 、Tulsi:Version 0.20221005.88

**Describe the problem**:
1、how to use static image decete in ios ?(Note: At present, I have used a static image to successfully detect in the facedetectiongpu demo project)

2、how to get decete score in ios ?

**Comment by lxm1799** [comment]
hi team!
could u tell how to get the confidance socre in faceDeceteDemo ? i rellay need it .tks

**Comment by lxm1799** [comment]
i resovle it ,hope can help someone ----->https://github.com/lxm1799/FaceMediapipe

**Comment by ayushgdev** [comment]
Hello @lxm1799 
Glad that you have found the solution. Thanks for sharing this with the community. Can we close this issue?
