### ISSUE TITLE
Bazel build takes too much time

### ISSUE THREAD

**Issue by yw2278** [google/mediapipe#395]
When I build for Youtube8M feature extractor， 
bazel build -c opt \
  --define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true \
  mediapipe/examples/desktop/youtube8m:extract_yt8m_features
it takes hours to finish， is that normal?

**Comment by jiuqiant** [comment]
The mediapipe framework doesn't take long time to build. So, if you build our hello world example, it should take 2 to 3 mins. extract_yt8m_features depends on the tensorflow inference engine. The most time consuming part is to compile and link those built-in tensorflow ops. It's expected to take longer time if your machine doesn't have powerful CPUs. For your reference, it takes 35 mins to build on a 15-inch 2017 macbook pro.

**Comment by zhangatao** [comment]
> When I build for Youtube8M feature extractor，
> bazel build -c opt
> --define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true
> mediapipe/examples/desktop/youtube8m:extract_yt8m_features
> it takes hours to finish， is that normal?
请问你的网络问题是怎么解决的
