### ISSUE TITLE
[Android] How not to draw UI graphs? (multi-hand tracking example.)

### ISSUE THREAD

**Issue by seoungbin0125** [google/mediapipe#3956]
I'm using a multi-hand tracking example.

I hope the app doesn't take pictures of the landmark UI.
How can I not film UIs?

There are also two additional questions.
1. How to use Wide Camera Preview
2. How to modify media pipe source code
- Even if you modify the java - component file of git and create an aar file, it has not changed.
I don't know what to do

Thank you. I've been wandering for a week, and I need your help

**Comment by ayushgdev** [comment]
Hi @seoungbin0125 
Would you please clarify your query with complete details using the [new issue template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=00-build-installation-issue.md)? 
Along with the questions given in the template, please answer the following:
1. _Which_  app are you referring to when you say "I hope the app doesn't take pictures of the landmark UI."?
2. Why do you want to change the source code of MediaPipe? Any specific use case that you want to address?

**Comment by seoungbin0125** [comment]
I mean the Android app.

I want to remove the displayed shapes in the picture below.

<img width="126" alt="image" src="https://user-images.githubusercontent.com/67889670/209791445-a08a478c-1c3d-4e1e-8664-e417b06867c8.png">

**Comment by ayushgdev** [comment]
Hi @seoungbin0125 
You need to remove the AnnotationOverlayCalculator from the hand_renderer_gpu.pbtxt graph located in mediapipe/graphs/hand_tracking/subgraphs and build another AAR to include in your app.
