### ISSUE TITLE
Preprocess for face detection model

### ISSUE THREAD

**Issue by sonfire186** [google/mediapipe#3959]
how to do preprocess for face detection model?
I to call the model directly `face_detection_short_range.tflite`.  And I get negative values ​​in `regressors`

**Comment by kuaashish** [comment]
@sonfire186,
As from the description I can understand that you would like to call the any of one .tflite models available in the build file. However, we would like to know more about the issue, platform you are working eg. Python, JavaScript or other platform available to assist better on the issue.
