### ISSUE TITLE
Run MediaPipe on python without any preview

### ISSUE THREAD

**Issue by stonecropa** [google/mediapipe#3961]
<img width="131" alt="捕获" src="https://user-images.githubusercontent.com/114655828/210195407-e87cbf57-dce1-44c1-bbd4-6aa0b4c5b284.PNG">
<em>I am using MediaPipe to run a holistic estimation network followed by an action classifier.
I want to turn off the rendering of the output video and  only want to use the output of bones.
Like this picture, but I use video.

Are there any examples available that explain how to use mediapipe without any preview rendering ?
How to display only skeletons in videos generated by mediapipe
<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows10
- MediaPipe Tasks SDK version:
- Task name (e.g. Object detection, Gesture recognition etc.):
- Programming Language and version ( e.g. C++, Python, Java): Python

**Comment by kuaashish** [comment]
Hi @stonecropa,
Please allow us sometime to share any possible solution to the support you are looking.

**Comment by stonecropa** [comment]
> Hi @stonecropa, Please allow us sometime to share any possible solution to the support you are looking.

OK

**Comment by stonecropa** [comment]
> Hi @stonecropa, Please allow us sometime to share any possible solution to the support you are looking.
![image](https://user-images.githubusercontent.com/114655828/211195434-cdc36a92-12bd-457d-b551-942d7fe1f3bf.png)
![image](https://user-images.githubusercontent.com/114655828/211195590-a265278c-df6e-41a1-8d4f-05cd6cdcb539.png)

I found this, but it's a image I want a video.
I hope you can answer this question Thank you.

**Comment by kuaashish** [comment]
Hi @stonecropa,
This is beyond mediapipe scope. The API only outputs pose landmarks, and users can process the landmarks with other tools such as matplotlib.pyplot. For video, We guess need a video rendering engine/game engine. We are not familiar with video rendering. However, We found that some users doing  it with unity: [Ref](https://www.youtube.com/watch?v=pQ-LHpGuUmM) Thank you!

**Comment by kuaashish** [comment]
@stonecropa,
Please go though the [above](https://github.com/google/mediapipe/issues/3961#issuecomment-1423721281) comment and feel free to close if this is no longer issue from your end. Thank you!
