### ISSUE TITLE
How to build Android AAR without opencv output(lines) like mediapipe Facemesh Solutions.

### ISSUE THREAD

**Issue by wh173d3v11** [google/mediapipe#3963]
Hi, I need to create similar like Facemesh Solutions aar, will later use as library module in my Android Studio Project, so that i can able to modify or customize the solutions core files which is in mediapipe/java folder.

1.  I can be able to generate Android AAR, but its building with OpenCV Library files. How can I build without OpenCV library similar like Solutions AAR locally.

currently I'm using below one to create Android AAR for face mesh.
```

load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_face_mesh",
    calculators = ["//mediapipe/graphs/face_mesh:mobile_calculators"],
)
```

2. [THIS IS SOLVED -  THANKS @onuralpszr ] I just saw the source code inside the folder *java/com/google/mediapipe/*** . 
when I try to include these as library module getting some files not found, for example **com.google.mediapipe.proto.GraphTemplateProto.CalculatorGraphTemplate**. please let me know should I include any more files in different places. [THIS IS SOLVED -  THANKS @onuralpszr ]

**Comment by onuralpszr** [comment]
You need to run protoc from [protocol-buffers](https://developers.google.com/protocol-buffers) and generate java or kotlin code based what you wanna use it.

File you need (make sure you have other import files as well 

https://github.com/google/mediapipe/blob/master/mediapipe/framework/tool/calculator_graph_template.proto

CalculatorGraphTemplate is [here](https://github.com/google/mediapipe/blob/master/mediapipe/framework/tool/calculator_graph_template.proto#L38)

Example use on my own case (different one but it should show the main idea)

```
protoc --java_out=/home/onuralps/protobuff_outputs mediapipe/modules/face_geometry/protos/face_geometry.proto 
protoc --java_out=/home/onuralps/protobuff_outputs mediapipe/modules/face_geometry/protos/mesh_3d.proto
protoc --java_out=/home/onuralps/protobuff_outputs mediapipe/framework/formats/matrix_data.proto
```

**Comment by onuralpszr** [comment]
> @onuralpszr Thanks, i will check this. you know how can we build AAR without opencv output/library files.?

I only change openCV version 3 or 4 based on the solution or project I was working on it.  Plus, openCV used very widely in project I don't think it is possible (at least I never tried  to remove openCV completely from what I compile. Maybe someone else knows it) 

Technically openCV version is set in [here](https://github.com/google/mediapipe/blob/master/WORKSPACE#L289)

**Comment by onuralpszr** [comment]
> `"--define EXCLUDE_OPENCV_SO_LIB=1"` They mentioned here -[mediapipe_aar.bzl](https://github.com/google/mediapipe/blob/add5600d0d4e9f0213ebf58088301dc7e743194a/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl#L64)
> 
> Finally openCV Lib files not included, but **_unfortunately it makes app crashes_** (possibly because of OpenCv Jni files not found) 👎🏼

Did you try to include your own openCV ? Also you are  correct, I forget that option in bzl file. I checked my own project and I remember that I include openCV4 myself instead of what they offer but problem is internally in some solutions it does crash because difference between cv3 and cv4 and how is it code inside mp source

**Comment by onuralpszr** [comment]
>Yeah you are right, i also noticed that they used openCV3 for some usecase and openCV4 for some . for facemesh they >using openCV3, we can check here - [MainActivity.java](https://github.com/google/mediapipe/blob/add5600d0d4e9f0213ebf58088301dc7e743194a/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java#L63)

Yes that is why there are 2 cv configs (cv4 and cv3) but in some cases you can use cv4 instead of cv3 even project asked to use cv3 (not %100 guarantee and you may wanna check everything work as intended) 

(I tested that too) 

> However, I believe that it would work if we use OpenCV 3 or 4 depending on the use case.

It does work (I tested)

**Comment by kuaashish** [comment]
Hi @wh173d3v11,

We are no longer maintaining the legacy facemesh solution, as it has been integrated into the new Face Landmarker task API, as explained in our [documentation](https://developers.google.com/mediapipe/solutions/guide#legacy). 

We intend to explore and implement our upgraded Face Landmarker in Android, following the steps outlined in our [documentation](https://developers.google.com/mediapipe/solutions/vision/face_landmarker/android). 

Additionally, we kindly request you to inform us of any errors encountered during the exploration process.

Thank you
