### ISSUE TITLE
How can we apply Filters in particular Coordinates or area with CameraX + Mediapipe Android AAR

### ISSUE THREAD

**Issue by wh173d3v11** [google/mediapipe#3964]
I’m trying to create a iris filter app. I created aar from the help of thier docs and i can able to get the coordinates of iris

I’m using CameraX + Mediapipe AAR file.

How or what are the possibilities to show some color filters on only the iris part (typically adding filter in that coordinates)

**Comment by kuaashish** [comment]
Hi @wh173d3v11,
Would you let us know the complete steps followed to build the particular app of iris example? We suggest to fill the [template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=00-build-installation-issue.md) and provide the maximum relevant information to address better the support you are looking.

**Comment by prakashsrv** [comment]
@wh173d3v11 got any answer to your question?

**Comment by prakashsrv** [comment]
can you please share the code or project?

**Comment by kuaashish** [comment]
@wh173d3v11,

Are you still looking resolution on this issue?
