### ISSUE TITLE
can't find java_home when build the libmeidapip_jni.so

### ISSUE THREAD

**Issue by chenguoting** [google/mediapipe#3965]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):
#62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
Java
- [MediaPipe version](https://github.com/google/mediapipe/releases):
https://github.com/google/mediapipe/tree/v0.8.11
- Bazel version:
bazel 5.2.0
- Android SDK and NDK versions (if android):
SDK 30.0.3 NDK 21

I want to build the libmediapipe_jni.so
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu:libmediapipe_jni.so

but it fail.
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  /DATA/share/chen_guoting/mediapipe-0.8.11/WORKSPACE:49:13: in <toplevel>
Repository rule http_archive defined at:
  /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/131dda9acc6978aba4740d75ca45f411fbabd726.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/8700849191dea2ca9c12a3d26ec41fac0814671b.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build options --copt, --cpu, --crosstool_top, and 5 more have changed, discarding analysis cache.
INFO: Repository local_jdk instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:27:6: in <toplevel>
  /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
  /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/bazel_tools/tools/jdk/local_java_repository.bzl:231:32: in local_java_repository
Repository rule _local_java_repository_rule defined at:
  /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/bazel_tools/tools/jdk/local_java_repository.bzl:202:46: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_jdk':
   Traceback (most recent call last):
	File "/DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/bazel_tools/tools/jdk/local_java_repository.bzl", line 127, column 32, in _local_java_repository_impl
		"does not exist." % (java_home, str(java_home_path)))
Error: not all arguments converted during string formatting
ERROR: /DEFAULT.WORKSPACE.SUFFIX:27:6: fetching _local_java_repository_rule rule //external:local_jdk: Traceback (most recent call last):
	File "/DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/bazel_tools/tools/jdk/local_java_repository.bzl", line 127, column 32, in _local_java_repository_impl
		"does not exist." % (java_home, str(java_home_path)))
Error: not all arguments converted during string formatting
INFO: Repository rules_java instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:429:6: in <toplevel>
  /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /DATA/share/chen_guoting/.cache/bazel/_bazel_chen_guoting/d896184a08a2df64667676d0a6a83c7f/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu:libmediapipe_jni.so' failed; build aborted: not all arguments converted during string formatting
INFO: Elapsed time: 0.106s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 11 targets configured)
    currently loading: @bazel_tools//tools/python ... (6 packages)
    Fetching @commands_overloads; Restarting.
    Fetching @local_execution_config_python; fetching

**Comment by chenguoting** [comment]
![image](https://user-images.githubusercontent.com/31856348/210679307-7b35e0d7-4568-48d3-9cdb-08e3b3d86936.png)
I have set java_ home,sdk,ndk in the environment @wh173d3v11

**Comment by ayushgdev** [comment]
Hello @chenguoting 
Would you please let us know why are you building libmediapipe_jni.so file? Is there any specific use case in your application that you would want to be catered?

**Comment by chenguoting** [comment]
My colleague solved the problem by adding this parameter --java_runtime_version=remotejdk_11
