### ISSUE TITLE
Not able to build docker image for autoflip on ubantu 20.04

### ISSUE THREAD

**Issue by akashAD98** [google/mediapipe#3967]
im getting this issue 

<img width="774" alt="image" src="https://user-images.githubusercontent.com/62583018/210544738-e2dee35f-9b9f-4880-b97c-2d7ba70d652a.png">

help is really appreciated,I want to run autoflip repo,

**Comment by ayushgdev** [comment]
Hello @akashAD98 
Can you please use the [new issue template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=00-build-installation-issue.md) to provide all the relevant details? We need details on the host OS, the docker version, and the minimal set of steps you have performed which led to this issue.

**Comment by akashAD98** [comment]
@ayushgdev im using NVIDIA GeForce RTX 3090  ubantu 20.4 machine   
i followed https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker


Docker version 20.10.21, build baeda1f


<img width="596" alt="image" src="https://user-images.githubusercontent.com/62583018/210795959-bf90caf4-d397-48ff-a0b0-9ca7b4433297.png">


<img width="775" alt="image" src="https://user-images.githubusercontent.com/62583018/210795897-e795ee8a-ba75-40af-a387-8d29550c2e58.png">

**Comment by ayushgdev** [comment]
@akashAD98 
We followed the same guide on fresh ubuntu 20.04 VM. However, we are not able to reproduce the issue. One probable area to look for resolution is that the issue might be with your network blocking some specific set of IPs. Can you check your network admin to make sure there is no blocking of IPs?

**Comment by akashAD98** [comment]
@ayushgdev let me try

**Comment by ayushgdev** [comment]
@akashAD98 Is your issue resolved?
