### ISSUE TITLE
[Android] multi-hand tracking AAR file, but it doesn't work.

### ISSUE THREAD

**Issue by seoungbin0125** [google/mediapipe#3968]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- Mac OS
- Java
- Bazel version:5.2.0
- Android NDK 21.4.7075529

**Describe the problem**:

I built a multi-hand tracking AAR file, but it doesn't work.

In the working example, the size of the AAR file is 66.2 MB, but the AAR size I created is only about 20 MB.

How can I make a hand tracking AAR file?
In the example, only the face is detailed.

In the AAR file I created, the message below appears and turns off.
Log : A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 5019 (mediapipe/5019), pid 4331 (andstrackingapp)
But I think the AAR file was not made normally.

**Comment by kuaashish** [comment]
Hi @seoungbin0125,
Would you please let us know the complete steps followed to reproduce the issue better from our end?

**Comment by kuaashish** [comment]
Hi @seoungbin0125,
Have you tried the both of the example in the android emulator or physical android devices?

**Comment by kuaashish** [comment]
@seoungbin0125,
All MediaPipe android solutions are tested against the real physical devices and in the emulator the above behaviour is excepted. If you will able to run the solutions in the virtual device that can be consider the insights to the other community members. Please try the solutions in the real devices and revert back if issue still persists. Thanks!
