### ISSUE TITLE
[Android] The camera display area is small.

### ISSUE THREAD

**Issue by seoungbin0125** [google/mediapipe#3969]
<em>Please make sure that this is a [Tasks](https://developers.google.com/mediapipe/solutions) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):
- Android 11
- latest
- multi-hand tracking solution
- java

**Describe the expected behavior:**
The camera seems to be zoomed in and printed out.
I checked if it was actually zoomed in, but it wasn't.
What this means is that the camera preview doesn't show the whole thing, but it shows the cut part.
If you show me another camera app, I'll show you the whole thing, but in the hand tracking example app, the camera display is small.

There is a size difference even in the basics, not using wide zoom.
Please refer to the image below.

- Defalut App 
![KakaoTalk_20230105_112714991](https://user-images.githubusercontent.com/67889670/210687730-6de589cc-2c8b-496f-acd7-e9f7b103a050.jpg)

- Media Pipe App
![KakaoTalk_20230105_112714991_01](https://user-images.githubusercontent.com/67889670/210687735-942f2cc3-a7f7-49ea-bebd-c2cd569a97ec.jpg)

I have another question.
What is the difference between detection_full and detection_lite?
I think I'm using full by default, but how do I use lite?

Thank you.

**Comment by seoungbin0125** [comment]
Additionally, either the x-axis or the y-axis appears to be truncated in the view.

I think the size of the camera view and the output view are different.
I think the x-axis is the same, but I think the camera axis is bigger than the y-axis.

**Comment by ayushgdev** [comment]
Hello @seoungbin0125 
Which build are you trying to use- Gradle or AAR? Will need this information to reproduce the issue and provide solution

**Comment by gianlucagal** [comment]
Sorry if I re-open this issue but I have the same problem using .aar file for edge detection and Gradle android app. 
Anyone can have some suggestion about that?
