### ISSUE TITLE
What exactly ExternalTextureRenderer do?

### ISSUE THREAD

**Issue by suraj-0387** [google/mediapipe#397]
What is the role of ExternalTextureRenderer?.Is it responsible to render landmark images along with the connection between them? Can anyone explain i detail.

**Comment by madhaviKumari** [comment]
```ExternalTextureRenderer``` is to render camera input which is ExternalTexture to a offscreen texture.
It is not responsible to show anything on surface/view, It is to render camera frame to a Texture of FrameBuffer & This texture is used in ```AppTextureFrame``` object which is input to Mediapipe or which is used as input stream for Mediapipe.

**Comment by suraj-0387** [comment]
So it means that it only display camera input without any modification but then where the modification and display of landmark points are done and how it is displayed to camera

**Comment by suraj-0387** [comment]
Thanks @madhaviKumari.But then  where is the processing of camera frames are done to render landmark points with connector and how it is then displayed on the screen

**Comment by madhaviKumari** [comment]
Look at [AnnotationOverlayCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/annotation_overlay_calculator.cc). This calculator is responsible to draws annotations and overlays them on top of the input images.
For Hand_tracking_gpu this is the shader used.

```c++
in vec2 sample_coordinate;
    uniform sampler2D input_frame; // Input Frame coming from Camera
    uniform sampler2D overlay; 
    uniform vec3 transparent_color;
    void main() {
      vec3 image_pix = texture2D(input_frame, sample_coordinate).rgb;
      vec3 overlay_pix = texture2D(overlay, sample_coordinate).rgb;
      vec3 out_pix = image_pix;
      float dist = distance(overlay_pix.rgb, transparent_color);
      if (dist > 0.001) out_pix = overlay_pix;
      fragColor.rgb = out_pix;
      fragColor.a = 1.0;
    }

```

**Comment by suraj-0387** [comment]
> `ExternalTextureRenderer` is to render camera input which is ExternalTexture to a offscreen texture.
> It is not responsible to show anything on surface/view, It is to render camera frame to a Texture of FrameBuffer & This texture is used in `AppTextureFrame` object which is input to Mediapipe or which is used as input stream for Mediapipe.

@madhaviKumari Does it mean that it renders the updated camera inputs after the modification done by mediapipe graph?

**Comment by madhaviKumari** [comment]
> > `ExternalTextureRenderer` is to render camera input which is ExternalTexture to a offscreen texture.
> > It is not responsible to show anything on surface/view, It is to render camera frame to a Texture of FrameBuffer & This texture is used in `AppTextureFrame` object which is input to Mediapipe or which is used as input stream for Mediapipe.
> 
> @madhaviKumari Does it mean that it renders the updated camera inputs after the modification done by mediapipe graph?

No it is before that, i.e Texture on which ```ExternalTextureRender``` is rendering camera frame will be input to the MediaPipe. So any change you want to make to drawing surface should be done in```AnnotationOverlayCalculator``` calculator.

**Comment by suraj-0387** [comment]
vi@madhaviKumari.Yes.It passes the converted texture to frameprocessor where the processing of landmark points are done and the output it added to SurfaceOutput.But do you any idea about how to render custom drawing and do not render the landmark point on the surfaceView.
vi@madhaviKumari.Thanks for your valuable inputs

**Comment by madhaviKumari** [comment]
What kind of custom drawing you want?  if you don't want to draw landmark points then modify shader code in ```AnnotationOverlayCalculator``` like this 


```
void main() {
      vec4 image_pix = texture2D(input_frame, sample_coordinate);
      fragColor = image_pix;
    }
```

If you want to overlay any other object on the input frame then you can pass that object to this shader using ```uniform sampler2D``` from ```GlRender``` method of ```AnnotationOverlayCalculator```. But what exactly you want to draw?

**Comment by suraj-0387** [comment]
@madhaviKumari . Actually I am trying to add 3d object or image at a specific landmark point.S I want lankmark point for drawing but I do not want to display the current output

**Comment by sgowroji** [comment]
Hi @suraj-0387, We are closing this issue as we see above your queries were answered. Let us know if you still looking for any relevant query. Thanks!
