### ISSUE TITLE
Face Occlusion Detection

### ISSUE THREAD

**Issue by ahmad-bashir-ai** [google/mediapipe#3972]
I want to detect the occlusion in coming in front of the face region in a video. It will take video frames as input and for each frame it will give an output whether the face the in the current frame is occluded or not.

**Comment by ayushgdev** [comment]
Hello @ahmad-bashir-ai 
Can you please let us know which technology you are working on? Also, if possible, please share a sample image and expected output pair to help us understand the requirement better.

**Comment by ahmad-bashir-ai** [comment]
I need to detect occlusions in front of faces for a given frame. For example, I have these two frames from the same video. One has occlusion in front of the face and in other the face is completely non-occluded. It should give answer in the form of yes/no. Yes(if there is any occlusion in front of face) No( if there is not any occlusion)
For the first image, it should give a no answer and for the second it should give yes.

<img width="538" alt="Screenshot 2023-01-09 at 12 18 22 PM" src="https://user-images.githubusercontent.com/119527683/211257482-6f32d65e-49d4-4b87-99c6-d45972de6ad8.png">


<img width="538" alt="Screenshot 2023-01-09 at 12 18 08 PM" src="https://user-images.githubusercontent.com/119527683/211257727-d4ecd214-9f1b-4836-b587-a6f273e7f56c.png">

**Comment by ayushgdev** [comment]
Hello @ahmad-bashir-ai 
This is currently not possible with MediaPipe models. The MediaPipe models detect whether there _is a face or not_. You need to train custom model to detect whether the face _is occluded or not_, which will be needed to use in conjunction with pre-trained model to detect a face in the frame first. 
We would suggest taking a look at [Tensorflow model maker](https://www.tensorflow.org/lite/models/modify/model_maker) which can help in training models in relatively easier way.
