### ISSUE TITLE
How to run JavaScript solution with increased GPU priority?

### ISSUE THREAD

**Issue by TigerHix** [google/mediapipe#3977]
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): Yes and no (issue exists for both)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 11
- [MediaPipe version](https://github.com/google/mediapipe/releases): Latest
- Bazel version: N/A
- Solution (e.g. FaceMesh, Pose, Holistic): Hands
- Programming Language and version ( e.g. C++, Python, Java): JavaScript

**Describe the expected behavior:**
MediaPipe inference in JavaScript slows down drastically when there are other 3D applications running in the foreground. Normally the tracking is \~24 FPS, but if I launch a resource-intensive 3D application/game (say Elden Ring), the tracking FPS drops drastically to 3~4 FPS. Switching the foreground application to the MediaPipe JavaScript solution immediately improves the FPS. This is on a i9-9900K + RTX 2080 Ti.

Notably, **the Python solution does not have this problem.** Tracking FPS remains stable no matter what application is running in the foreground. I am using official demo code for both.

**Standalone code you may have used to try to get what you need :**
I have tried to build the MediaPipe JavaScript solution as an electron app and manually raise its process priority in Task Manager (or through [`SetPriorityClass` Win32 API](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setpriorityclass)) to "Realtime". I have also tried to run the electron app with administrator privileges. However, both didn't work.

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook: The JS hands demo reproduces this.

**Other info / Complete Logs :**
N/A

**Comment by ayushgdev** [comment]
Hello @TigerHix 
Please allow us sometime to reproduce the issue at our end. We will need to see this behaviour and check the issue on Linux systems/Mac OS as well, since Windows support is still experimental as of now and therefore, cannot be certainly relied upon to consider an issue as a bug.

**Comment by TigerHix** [comment]
> Hello @TigerHix Please allow us sometime to reproduce the issue at our end. We will need to see this behaviour and check the issue on Linux systems/Mac OS as well, since Windows support is still experimental as of now and therefore, cannot be certainly relied upon to consider an issue as a bug/performance issue.

Thanks. The issue does not occur on Windows + Python. It only exists on Windows + JavaScript, so I think that might be a clue.

**Comment by ayushgdev** [comment]
The camera utils in MediaPipe library uses `requestAnimationFrame()` to schedule a callback function which is fired 60 times every second or as per display refresh rate. **`requestAnimationFrame()` calls are paused in most browsers when running in background tabs to save power/resources.** Henceforth you see the frame rate drop in running JS based solutions and not Python based.

Also, I noticed you are running an Nvidia Device. Nvidia Drivers have a setting "Background Application Max Frame Rate" based on which it caps the maximum frame rate of any GPU using background app to the specified value. Though there is a high chance the issue is because of how the browser behaves in background(since you are not encountering it on Python based application), you can also try tweaking this value _just_ to understand the workings more.

**Comment by TigerHix** [comment]
@ayushgdev Thanks for investigating. I have "Background Application Max Frame Rate" off in my NVIDIA control panel settings, so I think that isn't the cause here.

I will look into `requestAnimationFrame()`.

**Comment by ButzYung** [comment]
@TigerHix Since you are using `electron`, make sure that you set `backgroundThrottling` to false so that `requestAnimationFrame()` won't be paused as @ayushgdev described

**Comment by TigerHix** [comment]
@ButzYung Thanks, I have already set `backgroundThrottling` to false, but apparently it's still throttled by GPU. I will keep investigating.

**Comment by ButzYung** [comment]
@TigerHix Actually I am developing an electron app that uses MediaPipe as well (Holistic), and it seems strange to me that your fps is actually quite low (24) even in normal condition, considering that you have a pretty powerful PC. I wonder if there are actually other factors that slow down the frame rate.

**Comment by TigerHix** [comment]
> @TigerHix Actually I am developing an electron app that uses MediaPipe as well (Holistic), and it seems strange to me that your fps is actually quite low (24) even in normal condition, considering that you have a pretty powerful PC. I wonder if there are actually other factors that slow down the frame rate.

Ah okay. This is pretty normal because my webcam is capped at 30 FPS, and at low-light conditions it drops to 20-25 FPS. I am also running the highest quality hand tracking model, I believe that one is more resource-intensive than holistic (correct me if I'm wrong), and running the official CodePen demo yields similar FPS.

**Comment by ayushgdev** [comment]
@TigerHix Did you get any chance to look through the `requestAnimationFrame()` and their default behaviour defined by the browsers?
