### ISSUE TITLE
[iOS] Linking issue with *.tflite files for ios_static_framework!

### ISSUE THREAD

**Issue by Berezhnyj** [google/mediapipe#3978]
System information:
- MediaPipe v0.8.7.1 :
- Bazel version: 5.2.0
- XCode 14.0.1
- iOS 16 (iPhone 7)

**Describe the problem:**

I have faced with the problem of building static framework with Mediapipe.

Working solution for dynamic version:
```
apple_binary(
    name = "face_landmarks_detector_ios",
    deps = [
        ":face_landmarks_detector_ios_lib",
        "@opencv_framework_ios16//:OpencvFramework"
    ],
    data = [
        "//mediapipe/modules/face_detection:face_detection_short_range.tflite",
        "//mediapipe/modules/face_landmark:face_landmark.tflite",
    ],
    platform_type = "ios",
    binary_type = "dylib"
)
```
Not working solution for static framework:
```
ios_static_framework(
    name = "face_landmarks_detector_ios_static",
    minimum_os_version = "16.0",
    platform_type = "ios",
    families = ["iphone"],
    deps = [
        ":face_landmarks_detector_ios_lib",
        "@opencv_framework_ios16//:OpencvFramework",
    ],
    resources = [
        "//mediapipe/modules/face_detection:face_detection_short_range.tflite",
        "//mediapipe/modules/face_landmark:face_landmark.tflite",
    ],
)
```

And here is this lib to see that is inside 'face_landmarks_detector_ios_lib':
```
cc_library(
    name = "face_landmarks_detector_ios_lib",
    srcs = [
        "face_landmarks_detector.cc",
    ],
    hdrs = [
        "export.h",
        "face_landmarks_detector.h"
    ],
    copts = ["-std=c++17"],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/graphs/face_mesh/subgraphs:face_renderer_gpu",
        "//mediapipe/calculators/core:flow_limiter_calculator",
        ":face_landmarks_detector_front_gpu",
        "//mediapipe/calculators/core:constant_side_packet_calculator",
        ":desktop_live_calculators",
    ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            ":mobile_calculators",
            "//mediapipe/framework/formats:landmark_cc_proto",
        ],
    }),
    data = [
        "//mediapipe/modules/face_detection:face_detection_short_range.tflite",
        "//mediapipe/modules/face_landmark:face_landmark.tflite",
    ],
    defines = ["COMPILING_FACE_DETECTOR_API"],
    alwayslink = 1,
)
```

**Problem:**

After linking it to the iOS app with XCode I will get issues related to tensor flow models. Especially for:
```
         "//mediapipe/modules/face_detection:face_detection_short_range.tflite",
        "//mediapipe/modules/face_landmark:face_landmark.tflite",
```
Somehow _ios_static_framework_ is ignoring this files, rather than dynamic build working good without any issues.
Environment and setting of the project is the same for dynamic and static lib.

**Here is text from issue when app is running on the device (iPhone 7 iOS 16):**
```
2023-01-08 13:28:55.216549+0200 app-api[13255:7401738] Error NOT_FOUND: ValidatedGraphConfig Initialization failed.
No registered object with name: FaceLandmarksDetectorFrontCpu; Unable to find Calculator "FaceLandmarksDetectorFrontCpu"
No registered object with name: FaceRendererCpu; Unable to find Calculator "FaceRendererCpu"
```

**Questing is:  How to link this tflite files to ios_static_framework?**

**Comment by kuaashish** [comment]
Hi @Berezhnyj,
As from the issue description I can see that the problem you are facing to build the solution on the iOS. Would you let us know the exact steps you have followed and details about the macOS version to help more on the issue?

**Comment by Berezhnyj** [comment]
Hello @kuaashish!
Thanks for quick response!

I am trying to build this solution of macOS 12.6.1.

Steps for build this static framework:
1. First of all I have simple settings for graph config (I am using c++ for my project):
```
constexpr char GraphConfig[] = R"pb(
  input_stream: 'input_video'

  input_side_packet : 'num_faces'
  output_stream : 'output_video'
  output_stream : 'multi_face_landmarks'
  output_stream : 'face_count'

  node{
    calculator: 'FlowLimiterCalculator'
    input_stream : 'input_video'
    input_stream : 'FINISHED:output_video'
    input_stream_info : {
      tag_index: 'FINISHED'
      back_edge : true
    }
    output_stream: 'throttled_input_video'
  }

  # Subgraph that detects faces and corresponding landmarks.
  node{
    calculator: 'FaceLandmarksDetectorFrontCpu'
    input_stream : 'IMAGE:throttled_input_video'
    output_stream : 'LANDMARKS:multi_face_landmarks'
    output_stream : 'ROIS_FROM_LANDMARKS:face_rects_from_landmarks'
    output_stream : 'DETECTIONS:face_detections'
    output_stream : 'ROIS_FROM_DETECTIONS:face_rects_from_detections'
    output_stream : 'FACE_COUNT_FROM_LANDMARKS:face_count'
  }

  # Subgraph that renders face - landmark annotation onto the input image.
  node{
    calculator: 'FaceRendererCpu'
    input_stream : 'IMAGE:throttled_input_video'
    input_stream : 'LANDMARKS:multi_face_landmarks'
    input_stream : 'NORM_RECTS:face_rects_from_landmarks'
    input_stream : 'DETECTIONS:face_detections'
    output_stream : 'IMAGE:output_video'
  }
)pb";
```
And inside constructor the default flow for mediapipe graph config:
 ```
 mediapipe::CalculatorGraphConfig config = 
      mediapipe::ParseTextProtoOrDie<mediapipe::CalculatorGraphConfig>(GraphConfig);

  absl::Status status = m_graph->Initialize(config);
  if (!status.ok())
    throw std::runtime_error(status.ToString());
```

And inside this status I get that error what was described in the problem.

2. To build solution I use this command:
```
bazel build -c opt
                --config=ios_arm64
                --action_env PYTHON_BIN_PATH=/usr/bin/python3
                --apple_platform_type=ios
                --sandbox_debug
                --experimental_enable_objc_cc_deps
                --features=-swift.no_generated_header
                --apple_bitcode=embedded
                --copt=-fembed-bitcode
                --verbose_failures
                mediapipe/face_landmarks_detector:face_landmarks_detector_ios_static
```
3. Where 'mediapipe/face_landmarks_detector:face_landmarks_detector_ios_static' is also described is problem (let me know if you need more details for this component, because this is standard things what I found on official tutorials).
4. Inside Xcode project I was include generated static framework and also made bounds for tensor models:
I have copied "//mediapipe/modules/face_detection:face_detection_short_range.tflite" and //mediapipe/modules/face_landmark:face_landmark.tflite" as Wrapper for project (perfectly works for dynamic lib) by destination subgraph "mediapipe/modules/face_detection/".

Do you need something else, or more details?

**Comment by kuaashish** [comment]
Hi @Berezhnyj,
MediaPipe (and Google) typically build a single binary from a set of target dependencies. Mediapipe targets are mainly tested for this build scheme(monolithic binary build scheme). If you succeed in linking a static mediaPipe binary, we can consider some instructions for other users. Thanks!!

**Comment by kuaashish** [comment]
@Berezhnyj,
Could you please go though the above [comment](https://github.com/google/mediapipe/issues/3978#issuecomment-1400111713) and feel free to close if this is no longer issue from your end. thank you!
