### ISSUE TITLE
Is there need for reinitalize for the pose instance each time for new video?

### ISSUE THREAD

**Issue by crapper** [google/mediapipe#3979]
I'm doing a real time detection with mediapipe pose, and there has a button to allow the user to on/off the camera, since the model is not in static mode, the previous frames will definitely affect the detection.
For example, if a user on the camera for 10s and close it for 10s,
after restart it, will there a need for reinitialize the pose instance such to prevent the old frames affect the pose estimation?

I'm asking this is because the initialization of the pose instance is very time consuming, it will definitely affect the program....

**Comment by ayushgdev** [comment]
Hello @crapper 
Would you please let us know the technology you are using(Python, JS, Java)?

**Comment by crapper** [comment]
> Hello @crapper Would you please let us know the technology you are using(Python, JS, Java)?

Sorry for that, I'm using python, tkinter with opencv reading and fed them to the Mediapipe pose model.

**Comment by ayushgdev** [comment]
@crapper There is a need to reinitialize the graph for new video. For this purpose, use the `reset()` which is available in [SolutionBase](https://github.com/google/mediapipe/blob/master/mediapipe/python/solution_base.py#L388) class. So within your context manager for the pose detection, use your pose object to call reset() once you need to release graph. Please find a sample snippet below:

```
with pose.Pose(static_image_mode=True) as pose_obj:
  results = pose_obj.process(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
  pose_obj.reset()
```

**Comment by crapper** [comment]
I see, thanks you for help.
