### ISSUE TITLE
Accessibility to the MediaPipe's Surface Screen for Renderering

### ISSUE THREAD

**Issue by VaishakVN** [google/mediapipe#398]
I believe the graph pbtxt files are set of instructions to execute the flow of the Mediapipe application.
**Requesting guidance on-**
Currently we have the landmark points annotated and available on the Mediapipe's existing surface screen. Any possibility of accessing the surface screen by us to draw/insert image or object of our liking.
The **primary goal** is to insert an image/object to the already detected landmark point.

**Comment by eknight7** [comment]
This may be helpful: https://github.com/google/mediapipe/issues/397#issuecomment-576145283
