### ISSUE TITLE
AutoFlip: can not crop well in some videos

### ISSUE THREAD

**Issue by MichaelLee310** [google/mediapipe#3982]
Hi, 
    I run the project to test my own videos, 2 video cropping effects are not very good. 

[https://photos.app.goo.gl/u86WbPbPfdZ1W1n76](url)    at 00:15~00:16, two faces appear, but neither is cropped

[https://photos.app.goo.gl/vufiAtPCgc4WJtMY8](url)       at 00:00~00:05, there is a leopard in the scene, but the leopard's head is not cropped

The running code:
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip \ --calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt \ --input_side_packets=input_video_path=/absolute/path/to/the/local/video/file,output_video_path=/absolute/path/to/save/the/output/video/file,aspect_ratio=9:16

Thank you very much~~

**Comment by kuaashish** [comment]
Hi @MichaelLee310,
From the issue description I can see that example photos url has not accessible from our end. Would you update the issue description to address the issue better?

**Comment by MichaelLee310** [comment]
https://photos.app.goo.gl/xtUPbukgQ9Ryg2YGA      at 00:15~00:16, two faces appear, but neither is cropped

https://photos.app.goo.gl/Mdn8Fbx8TBExfTPK9      at 00:00~00:05, there is a leopard in the scene, but the leopard's head is not cropped

Are these two urls accessible? @kuaashish

**Comment by MichaelLee310** [comment]
https://photos.app.goo.gl/xtUPbukgQ9Ryg2YGA     at 00:15~00:16, two faces appear, but neither is cropped

https://photos.app.goo.gl/Mdn8Fbx8TBExfTPK9     at 00:00~00:05, there is a leopard in the scene, but the leopard's head is not cropped

Are these two urls accessible? @kuaashish

**Comment by kuaashish** [comment]
@MichaelLee310,
Apologies for the late response, urls which has mentioned in the above comment is accessible from our end.
Would you share the different observation made on other input videos(properly vs w.r.t to above videos url) and if any code changes done will more help to investigate on issue.
