### ISSUE TITLE
Hello World issue on Docker

### ISSUE THREAD

**Issue by carnage102** [google/mediapipe#3984]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Mac OS Ventura
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc-8
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases): 8.11
- Bazel version: 5.2.0
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): 

**Describe the problem**:
I'm new to using Docker and I'm attempting to run step 3 (the Hello World example) following the Docker Installation tutorial here: https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker
but I'm running into an "qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory" error. I tried troubleshooting after reading a couple of answers I found online regarding changing my platform to "--platform=linux/amd64" on the FROM line of the dockerfile but nothing changed. I can't help but feel I'm either not editing/running the edited DockerFile correctly or that my issue is something else entirely. 

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**after deleting the old container and editing the DockerFile FROM line to: "FROM --platform=linux/amd64 ubuntu:20.04"**
-docker build --tag=mediapipe .  
-docker run -it --name mediapipe mediapipe:latest 
-bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world
-qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by ayushgdev** [comment]
@carnage102 This is not a platform specific issue. This is because bazel is not properly installed/not being recognised by the system. If you run `bazel --version`, it will also give the same error. Please reinstall bazel in the container using the correct [distro guidelines](https://bazel.build/install).
