### ISSUE TITLE
need help regarding autofip mediapipe- python implementation

### ISSUE THREAD

**Issue by akashAD98** [google/mediapipe#3985]
may i know how can i build a simple pipeline for python,can someone tell me the logic .
i want to detect object & crop the area based on aspect ration, I saw autoflip is doing it but I want to build it from scratch, 

suggestions are really appreciated  thanks

**Comment by kuaashish** [comment]
Hi @akashAD98,
Currently, Auto-flip solution is not available in the python platform as described in the documentation [here](https://google.github.io/mediapipe/#ml-solutions-in-mediapipe). We can mark this is feature request and based on internal discussion can prioritise the request.

**Comment by akashAD98** [comment]
okay , im tryting to build this feature from scratch, I'm not getting smooth frames & not able to save video, can you help me here?
@kuaashish

**Comment by akashAD98** [comment]
My approch: detect people in each frame of the video, then it will check the size and aspect ratio of the bounding box of the largest detected person, compare it with the desired size and aspect ratio, and resize the frame accordingly.

& I have implemented it, but need some suggestions, regarding how should I improve it, I'm waiting for someone who can help me , thanks a lot.

note:please suggest me if my approach is wrong, or should I need to add something, I don't know c ++,so trying to build it from scratch. thanks

**Comment by kuaashish** [comment]
Hi @akashAD98,
Use case which you are looking is not currently supported by auto-flip. As mentioned here in [documentation](https://google.github.io/mediapipe/solutions/autoflip.html#required-vs-best-effort-saliency-features) "If the user would like to detect and preserve scenes of lions in a wildlife protection video, for example, they could implement and add a feature detection calculator for lions into the pipeline. Refer to AutoFlipFaceDetectionSubgraph and FaceToRegionCalculator". 

This can be done by https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt#L124 by adjusting the weight of the particular detection you need. In the use case mentioned you might be required to train a new Tflite model and change the tflite path [here](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/subgraph/autoflip_object_detection_subgraph.pbtxt#L40).

**Comment by akashAD98** [comment]
@kuaashish thanks but i want to build it from scratch like object detection+tracking + reframming. i want to know logic for this, I'm using crop method but getting weird results, so I need some suggestions regarding this

**Comment by kuaashish** [comment]
@akashAD98,
Would you please share complete use case and the different result observed to help more on the support you are looking from us.

**Comment by akashAD98** [comment]
I want to use  any detection model like yolov,v8 & tracker model ,&. Want to implement same logic of medipipe using python

**Comment by kuaashish** [comment]
@akashAD98 , Any real example or result set you are getting will be more helpful to understand the issue better from our end

**Comment by akashAD98** [comment]
@kuaashish where should i post my code , can you share your mail id, otherwise aksdesai1998@gmail.com is my mail,

my logic is 
1. detect person
2.track the person - find the largest bounding box, & reframe similar like autoflim

but I'm not getting frames correctly

**Comment by akashAD98** [comment]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/62583018/215472400-43407cec-4032-4d63-8eb2-71538365145e.png">

from this video frame, I'm getting a person with the maximum bounding box, now I want to add an aspect ratio  & save the video similar like autoflip , how should I do it? & whats the aprroch

**Comment by kuaashish** [comment]
Hi @jiuqiant,
Could you please look into this issue.

**Comment by kuaashish** [comment]
Hello @akashAD98,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by akashAD98** [comment]
@kuaashish i can see there is no autoflip in new repo.i have done the half part of code.still have few issues .
