### ISSUE TITLE
camera_utils.js:537 Failed to acquire camera feed: NotReadableError: Could not start video source

### ISSUE THREAD

**Issue by kashitsoft** [google/mediapipe#3987]
from today js stop responding to chrome and safari 

Showing this error - 

camera_utils.js:537 Failed to acquire camera feed: NotReadableError: Could not start video source

**Comment by kuaashish** [comment]
Hi @kashitsoft,
Could you elaborate your query with complete details and steps followed to reproduce the issue from our end?

**Comment by kuaashish** [comment]
@kashitsoft,
Does this [thread](https://stackoverflow.com/questions/65506547/how-to-fix-this-error-notreadableerror-could-not-start-video-source) helps on the query you have raised?

**Comment by dodorian92** [comment]
i have the same problem when i start working on my mobile devices. I'm using React with a WebCam component and I've noticed that the problem happens when I initialize the camera of '@mediapipe/camera_utils'. That might be right but how do I get react to run mediapipe. i tried running my facemesh.send at intervals but this is obviously not the best way.
this is my code
```
  useEffect(() => {
    if (effectRenderer != null) {
      
      const faceMesh = new FaceMesh({
        locateFile: (file) => {
          return `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${file}`;
        },
      });
    
      faceMesh.setOptions(solutionOptions);

      if (typeof webcamRef.current !== "undefined" && webcamRef.current !== null ) {
        if (dimensionSet ) {

        let camera = new cam.Camera(webcamRef.current.video, {
            onFrame: async () => {
                await faceMesh.send({ image: webcamRef.current.video })
            },
             width: VIDEO_WIDTH ,
             height: VIDEO_HEIGHT ,
        });
        camera.start();
    }

      faceMesh.onResults((results) => {
        if (results.multiFaceLandmarks) {
          effectRenderer.render(results);
        }
      });

         with this code it works on mobile chrome. comment on the room
    //   if (typeof webcamRef.current !== "undefined" && webcamRef.current !== null ) {
    //   setInterval(() => {
    //     faceMesh.send({ image: webcamRef.current?.video });
    //   }, 1000 / 18); // invia un frame ogni 33ms (30 fps)
     }
     }
  }, [ effectRenderer]);
``` 
component used for the chamber

```
  return (
    <div>
  <Webcam
  ref={webcamRef}
   height={VIDEO_HEIGHT}
  width={VIDEO_WIDTH}
  style={{
    position: "absolute",
    right: 0,
    top: 0,
    transform: "scaleX(-1)",
    marginBottom: "0px",
  }}
 
></Webcam>

      <canvas
        ref={canvasRef}
        width={window.innerWidth }
        height={window.innerHeight }
      ></canvas>
   
    </div>
  );
```

**Comment by TheYass1n** [comment]
any solutions yet

**Comment by kolorfilm** [comment]
Have the same problem here. Will this be fixed with the new mediaPipe version?

**Comment by pablim** [comment]
> i have the same problem when i start working on my mobile devices. I'm using React with a WebCam component and I've noticed that the problem happens when I initialize the camera of '@mediapipe/camera_utils'. That might be right but how do I get react to run mediapipe. i tried running my facemesh.send at intervals but this is obviously not the best way. this is my code
> 
> ```
>   useEffect(() => {
>     if (effectRenderer != null) {
>       
>       const faceMesh = new FaceMesh({
>         locateFile: (file) => {
>           return `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${file}`;
>         },
>       });
>     
>       faceMesh.setOptions(solutionOptions);
> 
>       if (typeof webcamRef.current !== "undefined" && webcamRef.current !== null ) {
>         if (dimensionSet ) {
> 
>         let camera = new cam.Camera(webcamRef.current.video, {
>             onFrame: async () => {
>                 await faceMesh.send({ image: webcamRef.current.video })
>             },
>              width: VIDEO_WIDTH ,
>              height: VIDEO_HEIGHT ,
>         });
>         camera.start();
>     }
> 
>       faceMesh.onResults((results) => {
>         if (results.multiFaceLandmarks) {
>           effectRenderer.render(results);
>         }
>       });
> 
>          with this code it works on mobile chrome. comment on the room
>     //   if (typeof webcamRef.current !== "undefined" && webcamRef.current !== null ) {
>     //   setInterval(() => {
>     //     faceMesh.send({ image: webcamRef.current?.video });
>     //   }, 1000 / 18); // invia un frame ogni 33ms (30 fps)
>      }
>      }
>   }, [ effectRenderer]);
> ```
> 
> component used for the chamber
> 
> ```
>   return (
>     <div>
>   <Webcam
>   ref={webcamRef}
>    height={VIDEO_HEIGHT}
>   width={VIDEO_WIDTH}
>   style={{
>     position: "absolute",
>     right: 0,
>     top: 0,
>     transform: "scaleX(-1)",
>     marginBottom: "0px",
>   }}
>  
> ></Webcam>
> 
>       <canvas
>         ref={canvasRef}
>         width={window.innerWidth }
>         height={window.innerHeight }
>       ></canvas>
>    
>     </div>
>   );
> ```

I have the same problem

**Comment by WilliamWelsh** [comment]
Anyone ever figure this out?

**Comment by italogustavoborba** [comment]
Anyone ever figure this out?
