### ISSUE TITLE
I just want to say thank you!

### ISSUE THREAD

**Issue by fchen09** [google/mediapipe#3991]
Dear MediaPipe Team,
I just wanna say thank you to develop such a wonderful AI, and it helps me start my APP business successfully.
Here is what I have developed with MediaPipe.

PinoQuest: https://apps.apple.com/us/app/pinoquest/id6444877037
PinoSoft: https://apps.apple.com/us/app/pinosoft/id1643661244

I wish we can further cooperate to develop the APP and make it more popular, although it has been popular so far.
Hope we can talk more about it. my email: pinosoft.vr@gmail.com

Thank you! Salute!

**Comment by kuaashish** [comment]
Hi @fchen09,
Glad to hear that! Thank you for the kind words! This helps us to improve our product and can see larger community are adopting the mediapipe. Hope product will be more helpful for the developer community to do build the application as per individual or organization requirements.

**Comment by kuaashish** [comment]
@fchen09,
would you go through the above [comment](https://github.com/google/mediapipe/issues/3991#issuecomment-1381367805) and please feel free to close if no longer issue from your end. Thanks!
