### ISSUE TITLE
How to create webgl context

### ISSUE THREAD

**Issue by RuentGen** [google/mediapipe#3993]
Hi first of all  I want to thank all of the google developers who are always improving the mediapipe framework 
all of you are the best. 

I am trying to create ar web application using mediapipe  face_mesh solution, I'm studying the emscrpten compiler which I will be used to compile my CPP file to web assembly, Now I am struggling to understand where should I start first, but  in my opinion, maybe it is better to start in creating a context in WEBGL,  and I saw that there's already gpu_context_web.cc included in mediapipe/gpu directory but I dont know how to use it to create a webgl context. Can someone help me , or maybe explain to me how I can use it?

**Comment by ayushgdev** [comment]
Hi @hadon 
Can you please share some insights on this issue?

**Comment by DonCuenca** [comment]
gpu_context_web.cc is connected with gpu_shared_data_internal.cc. You can create multiple WebGLs by using this function  ASSIGN_OR_RETURN(auto gpu_resources, mediapipe::GpuResources::Create(maincontext));

**Comment by kuaashish** [comment]
Hello @RuentGen,

Are you still looking for resolution on this Or the issue has been resolved? Thank you!!
