### ISSUE TITLE
For the image of the back of the hand, the MULTI_HAND_WORLD_LANDMARKS has very poor precision. 

### ISSUE THREAD

**Issue by DIYer22** [google/mediapipe#3994]
Using the official WEB demo(https://codepen.io/mediapipe/full/RwGWYJw), the performance on the back of the hand is very poor
When the hand is straight up, the 3D coordinates are ok:  
![image](https://user-images.githubusercontent.com/10448025/212287556-f860febc-598d-45db-b70b-30c7ea14f99a.png)  

When the hand is horizontal, the coordinates of the palm collapse:  
![image](https://user-images.githubusercontent.com/10448025/212287673-45461d82-2bde-4c26-a35a-957898656959.png)

**Comment by kuaashish** [comment]
Hi @DIYer22,
Thanks for the bringing out to our notice, MediaPipe solution are improving with the new release. We will bring this internally and let you know the any possible solutions.

**Comment by kuaashish** [comment]
Hi @bazarevsky,
Could you please have look into this issue. Thank you!

**Comment by kuaashish** [comment]
Hi @bazarevsky,
Could you please have look into this issue. Thank you!

**Comment by kuaashish** [comment]
Hello @DIYer22,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
