### ISSUE TITLE
What's next for mediapipe?

### ISSUE THREAD

**Issue by joansc** [google/mediapipe#3998]
Hello,

I was wondering what are the coming big updates/milestones for Mediapipe?  Any new features we could see in the coming months?
Thanks,

Joan

**Comment by kuaashish** [comment]
Hi @joansc,
Thanks for the raising issue, MediaPipe new solution are coming out about the gesture recognition but still in the testing phase and can not provide any ETA as of now. You can check all the latest release and new solution updates from the guide [here](https://github.com/google/mediapipe/releases).

**Comment by kuaashish** [comment]
@joansc,
would you please go through the above [comment](https://github.com/google/mediapipe/issues/3998#issuecomment-1383761868) and feel free to close if this now no longer issue from your end.

**Comment by jenperson** [comment]
Hi Joan,

I'm happy to share that MediaPipe [announced](https://youtu.be/6BDu_sz_y0U?t=669) the launch of MediaPipe Solutions in December! You can find the details in our [new documentation](https://developers.google.com/mediapipe/solutions), but I'll give you the highlights:

- MediaPipe Tasks provide solutions to common ML problems like [object detection](https://developers.google.com/mediapipe/solutions/vision/object_detector), [image classification](https://developers.google.com/mediapipe/solutions/vision/image_classifier), and [gesture recognition](https://developers.google.com/mediapipe/solutions/vision/gesture_recognizer). There are also text tasks like [text classification](https://developers.google.com/mediapipe/solutions/text/text_classifier). We are adding more tasks over time, so keep checking back for more options!
- Many of the MediaPipe Tasks are customizable in only a few lines of code using MediaPipe Model Maker. For example, you can make a [custom gesture recognizer](https://developers.google.com/mediapipe/solutions/vision/gesture_recognizer/customize) using your own dataset and labels for gestures. Check out our [rock paper scissors game](https://codepen.io/mediapipe-preview/pen/KKeybMr) for an example of custom gesture recognition.
- With the new [MediaPipe Studio](https://mediapipe-studio.webapps.google.com/), you can see some of our demos and change options. In the future, you will be able to customize your tasks in MediaPipe Studio without writing any code.

If you have any questions, please drop a comment in this thread or reach out to me on [LinkedIn](https://www.linkedin.com/in/jennifer-person/).

-Jen
