### ISSUE TITLE
Unnecessary garbage collection in v8 when inferring

### ISSUE THREAD

**Issue by paderevski** [google/mediapipe#3999]
The mediapipe selfie_segmentation model causes Chrome's v8 engine to fire off a Major_GC garbage collection every few frames. This is not a performance problem in a small website but in my use case, a very large React app, these GCs can consume considerable CPU time. The same behavior is confirmed with mediapipe and tfjs backend, and probably Chrome's "fault" more than mediapipe's. But any insight into why this is occurring, or how to circumvent, would be helpful.

See in the below image, about a dozen GCs in just a few seconds of running simply
`let segmentation = await segmenter.segmentPeople(video);`
in a `setInterval` loop.

<img width="641" alt="Screen Shot 2023-01-14 at 12 02 51 PM" src="https://user-images.githubusercontent.com/75690676/212485480-ce41338b-5277-45d9-9074-15dacee44204.png">

The reason I call this unnecessary, is that the heap size is < 10Mb and each GC is cleaning up 200Kb or so. Certainly not a good use of CPU time during a video processing loop.

Environment: Mac 12.4/Intel; Chrome 108.0.5359.124 (Official Build)

**Comment by ayushgdev** [comment]
Hello @paderevski 
Thank you for investigating into this matter and raising your concern. Although you seem to be running custom code, could you please check if you are calling `close()` once your are done within the loop for each selfie segmentation object?

One key problem is that JS has no finalizers, which means it's unfortunately impossible for C++ code running in WASM to know when garbage is collected. The workaround for this is usually to force users to call some sort of .close() function as soon as resources are ok to be freed, on any JS object which is backed by C++ memory.

**Comment by ayushgdev** [comment]
@Justinyu1618 
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) (including selfie segmentation), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Image segmentation is replacement for selfie segmentation in new tasks APIs.
