### ISSUE TITLE
How to Predict 3D Faces Using Models?

### ISSUE THREAD

**Issue by zhouhao-learning** [google/mediapipe#4]
I'm glad to see your work. I'm just interested in 3D face detection. Under the `model` folder, I saw some of the models you provided. I want to achieve the following effects:
![image](https://user-images.githubusercontent.com/24581773/60271937-ccc7da00-9925-11e9-93b2-9521580f7da4.png)
But I don't know how to use the model you provide to build prediction code. Can you give me some guidance? Thank you very much.

**Comment by mgyong** [comment]
The 3D face model is significantly more difficult than the [facedetector_front.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/models/facedetector_front.tflite) we have in the model folder. We recommend that you read the [publication for Face Mesh](https://sites.google.com/corp/view/perception-cv4arvr/facemesh?authuser=0)

What is the use case you are looking at for 3D face detection?

**Comment by zhouhao-learning** [comment]
@mgyong 
Sorry, maybe the meaning of the expression is wrong. I actually want to use the model you provided to do face detection. I want to get the following detection effect:
![image](https://user-images.githubusercontent.com/24581773/60310759-d9304f00-9986-11e9-93ff-494b2d738727.png)
But I don't know how to use your model and build prediction code. Can you help me?

**Comment by mgyong** [comment]
@zhouhao-learning Have you gone through the [Face detection for Android running GPU example](https://mediapipe.readthedocs.io/en/latest/face_detection_android_gpu.html)?
If you have issues with understanding some of the Android APIs for MediaPipe, you can start with [simpler example](https://mediapipe.readthedocs.io/en/latest/hello_world_android.html)

**Comment by zhouhao-learning** [comment]
No, I didn't run the Face detection for Android running GPU example. I don't want to run on Android right now. I just want to write a predictive code that can achieve the face alignment effect, but I don't know how to build the prediction code. Can you help me? Thank you.

**Comment by mgyong** [comment]
@zhouhao-learning This 3D face mesh issue is out of scope for project currently

**Comment by zhouhao-learning** [comment]
@mgyong 
No, if it is beyond the scope of the project, how do you achieve the following effects?
![image](https://user-images.githubusercontent.com/24581773/60380501-4d4b1f80-9a79-11e9-8c3b-8f1000127a6b.png)

**Comment by kartynnik** [comment]
@zhouhao-learning If you are interested in getting the effects by any means, you might find it useful to know that this 3D face mesh technology is exposed via the [Augmented Faces API](https://developers.google.com/ar/develop/java/augmented-faces/) in ARCore.

**Comment by zhouhao-learning** [comment]
@kartynnik 
Thank you for sharing. I'm still looking for ways to implement Python
