### ISSUE TITLE
need to keep a record of the ouput stream 

### ISSUE THREAD

**Issue by schieleines** [google/mediapipe#4000]
I am using  this code for hand and gesture recognition: https://github.com/kinivi/hand-gesture-recognition-mediapipe
I was wondering how to print an output file in csv or excel of the landmarks coordinatess. For now the stream runs live while mediapipe is working. 
I would like to print, at the end of each mediapipe session when I stop the code, a csv or excel file of the live stream landmarks with all the coordinates 

I have tried to create a clock to stop the mediapipe from running and print an output but it did not work,
Help would be amazing ! thanks !

**Comment by kuaashish** [comment]
Hi @schieleines,
You can try the similar implementation as mentioned here [#1803 (comment)](https://github.com/google/mediapipe/issues/1803#issuecomment-879065289) But you need to update the python implementation for the hands solution.
