### ISSUE TITLE
AutoFlip: Fix the height of cropping window and disable scaling

### ISSUE THREAD

**Issue by harisrab** [google/mediapipe#4004]
I have a video and at moments autoflip tool scales and zooms into the video too much that nothing stays visible. Is it possible that we can fix the height of the cropping window and let it just slide on x-axis as needed. Can someone explain how can I edit the config file to make this possible. 

@markmcd @cdibona @camillol @kuaashish 

Thank you.

**Comment by kuaashish** [comment]
Hello @harisrab,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
