### ISSUE TITLE
How can i check when i say any letter like 'a' ?

### ISSUE THREAD

**Issue by sukrubeyy** [google/mediapipe#4007]
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_face_mesh = mp.solutions.face_mesh

FACE_CONNECTIONS = frozenset([
    # Lips.
    (61, 146),
    (146, 91),
    (91, 181),
    (181, 84),
    (84, 17),
    (17, 314),
    (314, 405),
    (405, 321),
    (321, 375),
    (375, 291),
    (61, 185),
    (185, 40),
    (40, 39),
    (39, 37),
    (37, 0),
    (0, 267),
    (267, 269),
    (269, 270),
    (270, 409),
    (409, 291),
    (78, 95),
    (95, 88),
    (88, 178),
    (178, 87),
    (87, 14),
    (14, 317),
    (317, 402),
    (402, 318),
    (318, 324),
    (324, 308),
    (78, 191),
    (191, 80),
    (80, 81),
    (81, 82),
    (82, 13),
    (13, 312),
    (312, 311),
    (311, 310),
    (310, 415),
    (415, 308),
])

# For webcam input:
drawing_spec = mp_drawing.DrawingSpec(thickness=1, circle_radius=1)
cap = cv2.VideoCapture(0)
with mp_face_mesh.FaceMesh(
    max_num_faces=1,
    refine_landmarks=True,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5) as face_mesh:
  while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      continue
    #print(type(lipsUpperOuter))
    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = face_mesh.process(image)
    print(results.multi_face_landmarks[0].landmark[0])
    # Draw the face mesh annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    if results.multi_face_landmarks:
      for face_landmarks in results.multi_face_landmarks:
        #Draw Lips Mesh
        mp_drawing.draw_landmarks(
            image=image,
            landmark_list=face_landmarks,
            connections=FACE_CONNECTIONS,
            landmark_drawing_spec=None,
            connection_drawing_spec=mp_drawing_styles
            .get_default_face_mesh_tesselation_style())
    # Flip the image horizontally for a selfie-view display.
    cv2.imshow('MediaPipe Face Mesh', cv2.flip(image, 1))
    if cv2.waitKey(5) & 0xFF == 27:
      break
cap.release()

**Comment by kuaashish** [comment]
Hi @sukrubeyy,
Could you please elaborate your query with complete details. Thanks!

**Comment by sukrubeyy** [comment]
Sure, i want to draw when i say any letter on the webcam. For example when i say 'A' or 'B' i capture lips landmarks coordinates and calculate then draw 'A' or 'B' on the screen.

**Comment by kuaashish** [comment]
Hi @sukrubeyy,
Capture the face landmarks into python, implement lip motion detection in python manually. If you are having the face_landmarks in python, should be able to print the landmark coordinates.  

See: FACEMESH_LIPS in face_mesh.py.  is a set of landmark indexes.  

Simply take difference of lip landmark coordinates between frames, gives motion vector in screen coordinates, this might be sufficient.  For more advanced, want lip motion with respect to rest of face landmarks, possibly even 3d face landmarks.

**Comment by sukrubeyy** [comment]
i got it thx for you help :)

**Comment by sukrubeyy** [comment]
i got it thx for you help :)
