### ISSUE TITLE
Installing on macOS ERROR

### ISSUE THREAD

**Issue by Hyun-Jegal** [google/mediapipe#4009]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (macOS 13.1):

$ export GLOG_logtostderr=1

$ bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

...
...
WARNING: /Users/jegalh/Desktop/github/ext/mediapipe/mediapipe/framework/tool/BUILD:184:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /Users/jegalh/Desktop/github/ext/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (84 packages loaded, 1753 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_jegalh/df2440b6536b80ffb35662537b73b9fc/external/com_google_protobuf/BUILD:208:11: Compiling src/google/protobuf/wire_format.cc failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics ... (remaining 38 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/com_google_protobuf/src/google/protobuf/wire_format.cc:1130:67: error: too few arguments to function call, expected 5, have 4
                                                    target, stream);
                                                                  ^
/usr/local/include/google/protobuf/wire_format_lite.h:631:19: note: 'InternalWriteMessage' declared here
  static uint8_t* InternalWriteMessage(int field_number,
                  ^
external/com_google_protobuf/src/google/protobuf/wire_format.cc:1370:7: error: too few arguments to function call, expected 5, have 4
      HANDLE_TYPE(MESSAGE, Message, Message)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/wire_format.cc:1366:23: note: expanded from macro 'HANDLE_TYPE'
        target, stream);                                                       \
                      ^
/usr/local/include/google/protobuf/wire_format_lite.h:631:19: note: 'InternalWriteMessage' declared here
  static uint8_t* InternalWriteMessage(int field_number,
                  ^
external/com_google_protobuf/src/google/protobuf/wire_format.cc:1437:69: error: too few arguments to function call, expected 5, have 4
      message_reflection->GetMessage(message, field), target, stream);
                                                                    ^
/usr/local/include/google/protobuf/wire_format_lite.h:631:19: note: 'InternalWriteMessage' declared here
  static uint8_t* InternalWriteMessage(int field_number,
                  ^
3 errors generated.
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.483s, Critical Path: 2.82s
INFO: 165 processes: 151 internal, 14 darwin-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by kuaashish** [comment]
Hi @Hyun-Jegal,
You can try the workaround as mentioned here [#13660 (comment)](https://github.com/google/mediapipe/issues/3660#issuecomment-1236453132) and please let us know if this workaround resolves the issue.

**Comment by kuaashish** [comment]
@Hyun-Jegal,
Would you let us know the status of the above issue and please feel free to close if no longer issue at your end.
