### ISSUE TITLE
Two streams enter into the same node

### ISSUE THREAD

**Issue by MaximKsh** [google/mediapipe#401]
I'm trying to modify ObjectDetection node by adding a second input stream to DetectionLabelIdToText node. I want to send to calculator some extra data (for example, label names).

I modify object_detection_mobile_gpu.pbtxt

```input_stream: "second_input"
...
node {
  calculator: "DetectionLabelIdToTextCalculator"
  input_stream: "filtered_detections"
  input_stream: "SECOND:second_input"
  output_stream: "output_detections"
  node_options: {
    [type.googleapis.com/mediapipe.DetectionLabelIdToTextCalculatorOptions] {
      label_map_path: "mediapipe/models/ssdlite_object_detection_labelmap.txt"
    }
  }
}
...
```

and add to detection_label_id_to_text_calculator.cc method GetContract:

`cc->Inputs().Get("SECOND", 0).Set<int>();`

I expect nothing changes and app will works like without modification, but after adding a second input stream to node, calculator's method Process isn't called at all and screen is only black.

What I am doing wrong? Similar case is explained into documentation as example calculator.

**Comment by afsaredrisy** [comment]
Showing full pbtx(Graph) file will be helpful. hope you are setting type of the stream in  ```GetContract``` method of the corresponding calculators. as ```cc->Inputs().Index(0).SetAny();```

**Comment by afsaredrisy** [comment]
Showing full pbtx file will be helpful

**Comment by MaximKsh** [comment]
detection_label_id_to_text_calculator.cc and object_detection_mobile_gpu.pbtxt:
[https://gist.github.com/MaximKsh/baeb582fc73ed9ecfd5562b6f6684114](https://gist.github.com/MaximKsh/baeb582fc73ed9ecfd5562b6f6684114)

Bazel target for launch:
`//mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu:objectdetectiongpu`

Other files are unchanged

**Comment by eknight7** [comment]
Does this issue only happen in this particular calculator? Have you tried modifying other calculators and observed any similar issues?

**Comment by MaximKsh** [comment]
This case can be reproduced by single-node calculator

test_calculator.cc:
```
#include "mediapipe/framework/calculator_framework.h"
class TestCalculator : public mediapipe::CalculatorBase {
public:
    static mediapipe::Status GetContract(mediapipe::CalculatorContract* cc) {
        cc->Inputs().Get("", 0).SetAny();
        cc->Outputs().Get("", 0).SetSameAs(&cc->Inputs().Get("", 0));

        cc->Inputs().Get("SECOND", 0).SetAny();

        return mediapipe::OkStatus();
    }
    mediapipe::Status Open(mediapipe::CalculatorContext* cc) final {
        cc->SetOffset(mediapipe::TimestampDiff(0));
        return mediapipe::OkStatus();
    }
    mediapipe::Status Process(mediapipe::CalculatorContext* cc) final {
        if (!cc->Inputs().Get("", 0).IsEmpty()) {
            cc->Outputs().Get("", 0).AddPacket(cc->Inputs().Get("", 0).Value());
        }
        return mediapipe::OkStatus();
    }
};
REGISTER_CALCULATOR(TestCalculator);

```

object_detection_mobile_gpu.pbtxt:
```
input_stream: "input_video"
input_stream: "second_input"
output_stream: "output_video"

node {
  calculator: "TestCalculator"
  input_stream: "input_video"
  input_stream: "SECOND:second_input"
  output_stream: "output_video"
}

```

**Comment by afsaredrisy** [comment]
I reproduced your issue & fixed it.

First thing pass the ```second_input``` through ```FlowLimiterCalculator``` as:
```
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "second_input"
  input_stream: "FINISHED:detections"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
  output_stream: "throttled_second_input"
}
```

Now use ```throttled_second_input``` in ```DetectionLabelIdToTextCalculator``` as:
```
node {
  calculator: "DetectionLabelIdToTextCalculator"
  input_stream: "filtered_detections"
  input_stream: "SECOND:throttled_second_input"
  output_stream: "output_detections"
  node_options: {
    [type.googleapis.com/mediapipe.DetectionLabelIdToTextCalculatorOptions] {
      label_map_path: "mediapipe/models/ssdlite_object_detection_labelmap.txt"
    }
  }
}
```

Set SECOND input to any in ```DetectionLabelIdToTextCalculator``` 's ```GetContract```: 

```c
 if (cc->Inputs().HasTag("SECOND")) {
  cc->Inputs().Tag("SECOND").SetAny();
  }
```

Next step is to add your input to second_input. You need to add it from ```FrameProcessor.java``` 
like this. 

```java
 @Override
  public void onNewFrame(final TextureFrame frame) {

   ....

   Packet imagePacket = packetCreator.createGpuBuffer(frame);

    // If your secondPacket is not a texture or image then you can use other packetCreator methods
   // I am using createGpuBuffer for simplicity 
    Packet secondPacket = packetCreator.createGpuBuffer(frame);

    try {
      // addConsumablePacketToInputStream allows the graph to take exclusive ownership of the
      // packet, which may allow for more memory optimizations.
      mediapipeGraph.addConsumablePacketToInputStream(
          videoInputStream, imagePacket, frame.getTimestamp());
      mediapipeGraph.addConsumablePacketToInputStream("second_input",
              secondPacket,frame.getTimestamp());
    } catch (MediaPipeException e) {
      Log.e(TAG, "Mediapipe error: ", e);
    }
    imagePacket.release();
    secondPacket.release();


  ....
}
```

After making these changes you will be able to run it, I tried & it is working now.

**Comment by MaximKsh** [comment]
Thank you for explanation.

Process is called when both streams contain packet, isn't it? Is any way exist to use one stream with high frequency (gpu buffers, for example) and other one with low frequency (for example, one packet per ten seconds)?
Let me explain what I mean. I want to change label_id to label_text conversion in different way than in example. 
1. For the first time label_cache is empty (mapping label_id -> label_text)
1. For any detection from input stream "filtered_detections" I check cache and if it does not contain the specified label_id I send this label_it to some output stream (unkown_labels, for example). If label_cache contains required id, I just set text to Detection.
1. In Java code I subcribe to "unkown_labels" output stream, get text of label_id and return it to graph by sending it to "second_input" vector. 
1. Packets, described in previous section, are added to label_cache into calculator code.

Is this algorithm a good way to do this or better to send second_input packets with gpu frames?

**Comment by hadon** [comment]
Thanks Afsar.  Your fix looks correct to me.  

MaximKsh, a typical way to combine streams with different frequencies is to use PacketClonerCalculator to produce packets from both streams at the same frequency (at the "tick" frequency) with the same timestamps.  It sounds like in your use case there will be occasional lookup of a label text, and those occasional lookup results will form a low frequency input-stream.  I'm not sure I've followed the use case.
