### ISSUE TITLE
Autoflip on the web

### ISSUE THREAD

**Issue by tangentlin** [google/mediapipe#4010]
<em>Please make sure that this is a feature request.</em>

**System information**

- MediaPipe Solution (you are using): AutoFlip
- Programming language : typescript
- Are you willing to contribute it: Yes

**Describe the feature and the current behavior/state:**
Bring AutoFlip feature to web so that users can have ways to pick the AutoFlip detection algorithm that fits their videos the best.

AutoFlip involves 1) calculations of "reframing" rects and 2) render and encode video with "reframe".  Because browser video API can render the crop video without having to encode a whole new video, this saves the time and network bandwidth to re-encode a new video, thus users can quickly see to cropped video before committing to the final solution.

**Will this change the current api? How?**
Likely not

**Who will benefit with this feature?**
End users who wish to adopt AutoFlip or tweak AutoFlip to produce the best outcome.

**Please specify the use cases for this feature:**
- Users with landscape video and wish to turn it into portrait video
- Users who wish two adjust AutoFlip detection such as face or object to achieve best output outcome

**Comment by ayushgdev** [comment]
Hello @tangentlin Thanks for raising this feature request. From the description, it looks like your idea is to have a playground on web where users can experiment with different parameters settings of Autoflip solution and check which ones fit best for them. Later on, they can use the desktop solution with same settings to do the conversion of the required video, possibly of a much longer duration.

This looks like an interesting request. We will discuss this feature internally and prioritise it among others. However, it might take sometime since we are running along several trenches to improve MediaPipe in near future.

**Comment by tangentlin** [comment]
Hi @ayushgdev, thanks for the explanation.  I used to work in a major company's ads' team and noticed users had low adoption on automatic AI feature through UX research; our experiments also saw more rapid feedbacks translated higher adoptions and trust.

Features such as AutoFlip could be accelerated by decoupling two steps -- 1) calculation of crops, and 2) generating the mp4 that realizes the crop.  In step 1, crops can be done in the browser, and preview without generating a new mp4; as for step 2, it could be either done in the browser or backend API.  Step 2 can be done without calling AutoFlip AI because it is just a rendition of cropped video.

Like you said, Step 1 is like a playground where user can define cropping strategies, and get a transient result of the cropping at a more rapid pace.  Step 2 is entirely up to the implementation to choose whether MP4 generation should be done in the browser (UI) or backend.  Such separation would yield better user experience and make AutoFlip more popular.

Taking it further, the interactive UI could also provide user feedbacks or analytics to help AutoFlip or AutoFlip project adoption teams to improve the algorithm.

As a software engineer myself, I would be very interested in helping what it takes to bring this feature to JS/WASM.  Thanks.

**Comment by ayushgdev** [comment]
Thanks for the detailed explanation @tangentlin . We will take this request and provide a playground that best fits all users' needs.

**Comment by kuaashish** [comment]
Hello @tangentlin,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.

**Comment by Neilblaze** [comment]
> I would be very interested in helping what it takes to bring this feature to JS/WASM

Me too! Adding support for Autoflip on web will certainly be a game-changer for every online video editor out there.

**Comment by bartadaniel** [comment]
Such a great idea, I am sad to see it go down. Do you know of any alternatives?
