### ISSUE TITLE
Problem with Handlandmark Tracking graph

### ISSUE THREAD

**Issue by ChunfangWang** [google/mediapipe#4013]
I am running mediapipe c++ on Linux and confused with tracking part in hand-landmark-tracking. 
Would you please give me some help? Thank you. 

Steps:
bazel build --define MEDIAPIPE_DISABLE_GPU=1 -c dbg mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

Run 
 "program": "mediapipe/bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu",
"args":[    "--calculator_graph_config_file",
                "mediapipe/mediapipe/graphs/hand_tracking/hand_tracking_desktop.pbtxt",
                "--input_side_packets",
        "input_video_path=mediapipe/hand_loop.mp4,
output_video_path=mediapipe/hand_loop_annotated.mp4,model_complexity=0,use_prev_landmarks=true" ],
"environment": [{ "name": "LD_LIBRARY_PATH", "value": "/usr/local/lib" },
                            {"name": "GLOG_v", "value": "1"}],

Results:
Test video contains one hand, not moving much. 
Palm Detection was performed on every frame. 

Debugging: 

From visualization of this graph, 
only one GateCalculator which compares the vector size of (prev_hand_rect_from_landmarks) < num_hands to decide whether to run PalmDetectionCpu node. 
In this case, with default num_hands = 2, for videos with one hand, tracking is not ON because len(list of prev_hand_rect_from_landmark) < num_hands ---> Palm detection was run on every frame. 

How does AssociationNormRect node  which compute IOU(hand_rect_from_palm_detection, prev_hand_rect_from_landmark) >= threshold control whether to run PalmDetectionCpu node. 
This idea was illustrated in paper and this pbtxt file, but annotation ouptut as well as debugging output could not match. 
Palm Detection was run on every frame. 

Quoted from Paper
"One key optimization MediaPipe provides is that the palm detector only runs as needed (fairly infrequently), saving significant
computation. We achieve this by deriving the hand location in the current video frames from the computed hand landmarks in the previous frame, eliminating the need to apply the palm detector on every frame. For robustness, the hand tracker model also outputs an additional scalar capturing the confidence that a hand is present and reasonably aligned in the input crop. Only when the confidence falls below a certain threshold is the hand detection model reapplied to the next frame.
"

 Thank you very much.

**Comment by ayushgdev** [comment]
Hello @ChunfangWang 
Thanks for raising your issue. Please allow us some time to check the visualisation of the graph created and the issue mentioned. We will revert back to you shortly.

**Comment by ayushgdev** [comment]
Hello @ChunfangWang 
There is a bounding box computed from HandLandmarks, which encloses all hand-landmarks, this is similar to the palm detection bounding box.  In order to use this in place of palm detection, it must be assigned the successive timestamp in order to make it available on the successive frame.  The successive timestamp is provided by PreviousLoopbackCalculator.

**Comment by ChunfangWang** [comment]
Hello @ayushgdev 
Thanks for your reply. My questions is related to how do you decide whether to use the bounding box computed from HandLandmarks or to initilize a new palm detection for the successive frame? 

From the code it seems merely depends on whether the number of hands present in the scene, if it is less than 2 (default max_hand_detected), run palm detection, or else use bounding box from HandLandmarks.

**Comment by ayushgdev** [comment]
Yes @ChunfangWang . That is the case. This is defined using the GateCalculator and depends on `prev_has_enough_hands` output stream coming from `NormalizedRectVectorHasMinSizeCalculator`. You can find the conditions in the [CollectionHasMinSizeCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/collection_has_min_size_calculator.h#L47):
- Num of input and output streams should be 1 each. 
- minimum size/number of hands should be present as input_side_packet  if not passed as calculator option

The packet creation of the [`prev_has_enough_hands`](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/collection_has_min_size_calculator.h#L83) depends on the input_side_packet.
The number of hands are predicted in the previous frame are propagated through the `PreviousLoopbackCalculator` to the next timestamp input frame, subsequently to GateCalculator and then NormalizedRectVectorHasMinSizeCalculator. If the maximum number of predicted hands satisfies [this condition](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/collection_has_min_size_calculator.h#L81), the palm detection won't run again.

**Comment by ayushgdev** [comment]
Closing the issue due to lack of activity.
