### ISSUE TITLE
I use mediapipe holistic,but a video has no hands for a few seconds, other times are normal

### ISSUE THREAD

**Issue by stonecropa** [google/mediapipe#4014]
<em>just like this picture
this is my code about hand
if results.left_hand_landmarks:
mp_drawing.draw_landmarks(
annotated_frame,
results.left_hand_landmarks,
mp_holistic.HAND_CONNECTIONS,
mp_drawing_styles.get_default_hand_landmarks_style(),
mp_drawing_styles.get_default_hand_connections_style())
if results.right_hand_landmarks:
mp_drawing.draw_landmarks(
annotated_frame,
results.right_hand_landmarks,
mp_holistic.HAND_CONNECTIONS,
mp_drawing_styles.get_default_hand_landmarks_style(),
mp_drawing_styles.get_default_hand_connections_style())

I would appreciate it if you could answer
<em>
![image](https://user-images.githubusercontent.com/114655828/213365638-63bd7cd8-e0a3-4f02-937b-af65314893a6.png)
![image](https://user-images.githubusercontent.com/114655828/213365661-4109709e-b4d2-4733-89ed-b1148da64c21.png)

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- Python version (e.g. 3.8): python 3.9

**Comment by ayushgdev** [comment]
Hello @stonecropa 
From your description, it seems that the model is not able to detect the left and right hand landmarks. Holistic solution is a solution which is combination of Face, Pose and Hands solutions and optimised to work in sync. So the BlazePose model is detecting the hands and marking it's landmarks, but the hands graph is not able to do so. 

This will need some investigation. Here are few things to do:
1. Please identify the exact frames from the video which are having this issue. Capture them as an image. you may take a screenshot by pausing video or do it programmatically if you know how to. 
2. Use the MP holistic solution with `static_image_mode` set to true on this image/video frame. Check if this gives incorrect results as well.
3. Use the MP Hands solution with `static_image_mode` set to true on this image/video frame. Check if this gives incorrect results as well.

If there are differences in the output of MP Holistic and MP Hands, do let us know. It might indicate need of optimization of the solution.
