### ISSUE TITLE
Build FaceMesh to use inside a macos Swift app

### ISSUE THREAD

**Issue by peymanbateni** [google/mediapipe#4018]
I am trying to build a media pipe FaceMesh to use it inside a Swift macOS app. There are build scripts for iOS and I am trying to modify them to build for Swift as a framework to be embedded inside my macOS app. I found this example (https://github.com/swittk/MediapipeFaceMeshIOSLibrary) for building an iOS framework but how can I build face mesh for macOS use specifically, not as a python package, but rather for use with Swift?

**System information**
- macOS M1 13.0
- MediaPipe v0.8.11
- Bazel version: 5.2.0
- Swift 5

**Comment by ayushgdev** [comment]
Hello @peymanbateni, MediaPipe native APIs C++ can support bindings to Swift.
You can create custom CPP interoperator like [this](https://github.com/pschuh/cpp_example/blob/master/Sources/CPPExample/include/example.h) and use as given in this [example](https://github.com/pschuh/cpp_example/blob/master/Sources/Example/Basic.swift.).

Although this is a possible solution, I expect that you'll need a swift wrapper over the C++ code for the time being.

**Comment by peymanbateni** [comment]
Thank you for the information. I am also having a tough time building desktop APIs on macOS M1.

**Comment by peymanbateni** [comment]
Also the example provided unfortunately results in a GitHub page not found error :/

**Comment by ayushgdev** [comment]
Apologies for broken link. It was a period in the link at the end, causing it to break. [Here](https://github.com/pschuh/cpp_example/blob/master/Sources/Example/Basic.swift) is the link to the example
