### ISSUE TITLE
Error building model inference youtube8m

### ISSUE THREAD

**Issue by Tortoise17** [google/mediapipe#4019]
I have error building youtube8m inference model example. 

I have 
OS =  CentOS 7
Tensorflow-gpu = 1.15.5
Python = 3.7
OpenCV = 3.4
gcc = 8.5
Cuda = 10.2
mediapipe = recent github cloned
and 
command is 

`bazel build -c opt --linkopt=-s --define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true mediapipe/examples/desktop/youtube8m:extract_yt8m_features`

and output is 

```
/run/media/omni/omni_work/new_exp/mediapipe/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  /home/onmi/.cache/bazel/_bazel_onmi/b57c1847c7ca79f7145bb84498f18615/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: /run/media/omni/omni_work/new_exp/mediapipe/mediapipe/calculators/tensorflow/BUILD:401:11: no such package '@com_google_absl//absl/log': BUILD file not found in directory 'absl/log' of external repository @com_google_absl. Add a BUILD file to a directory to mark it as a package. and referenced by '//mediapipe/calculators/tensorflow:tensorflow_inference_calculator'
ERROR: Analysis of target '//mediapipe/examples/desktop/youtube8m:extract_yt8m_features' failed; build aborted: 
INFO: Elapsed time: 0.199s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 113 targets co\
nfigured)
    currently loading: @org_tensorflow//tensorflow/core/example
    Fetching @sobol_data; fetching
```

If you can hint me which package is actually it pointing as missing. It would be kind help

<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment]
Hi @Tortoise17,
Would you let us know you are able to build/install the mediapipe as mentioned [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-centos) in documentation? If yes, then please share the complete error logs to understand the issue better from our end.

**Comment by Tortoise17** [comment]
Dear @kuaashish  Yes, I tried everything like this. 

Error below with complete log and commandline is 

```

$ bazel build -c opt --define='MEDIAPIPE_DISABLE_GPU=1' --linkopt=-s mediapipe/examples/desktop/youtube8m:model_inference
Starting local Bazel server and connecting to it...
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /home/omni/.cache/bazel/_bazel_omni/b57c1847c7ca79f7145bb84498f18615/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: /run/media/omni/omni_work/new_exp/mediapipe/mediapipe/calculators/tensorflow/BUILD:401:11: no such package '@com_google_absl//absl/log': BUILD file not found in directory 'absl/log' of external repository @com_google_absl. Add a BUILD file to a directory to mark it as a package. and referenced by '//mediapipe/calculators/tensorflow:tensorflow_inference_calculator'
ERROR: Analysis of target '//mediapipe/examples/desktop/youtube8m:model_inference' failed; build aborted: 
INFO: Elapsed time: 3.916s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (114 packages loaded, 463 targets configured)
    currently loading: @org_tensorflow//tensorflow/core/example
```

**Comment by Tortoise17** [comment]
@kuaashish any tip

**Comment by kuaashish** [comment]
Hi @Tortoise17,
Thanks for the reporting issue! this issue has already been in our notice. we suggest to wait a week new releases are coming out regarding the version 0.9.1.0 in github. However, this has been released in the [pypi](https://pypi.org/project/mediapipe/) but due to conflict taking more than usual time in github.

**Comment by Tortoise17** [comment]
@thank you, I am waiting.

**Comment by Tortoise17** [comment]
@kuaashish Is there any tip or helpful hint. I have tried with the current available git release and still it is not successful. Please if you can guide me.

**Comment by kuaashish** [comment]
Hello @Tortoise17,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
