### ISSUE TITLE
...does not contain a toolchain for cpu 'ios_x86_64

### ISSUE THREAD

**Issue by sevar83** [google/mediapipe#402]
Hi, I am trying to sync a new mediapipe project in Android Studio on my Ubuntu but got an Apple-related error. How can I disable iOS build targets to get rid of the errors?

Environment:
Ubuntu 18.04 64-bit
Android Studio 3.5.2
SDK installed
NDK installed
Bazel plugin for IntelliJ
Bazel 1.2.1

```
Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: /home/sevar/bin/bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --

Command: git diff --name-status --no-renames d144e564d8f48737f1bf684ee741c9ccf6a5909d

Computing VCS working set...
  .aswb/.bazelproject (added)
  .aswb/.blaze/aar_libraries/activity-1.0.0-rc01_151eaabb.aar/AndroidManifest.xml (added)
  .aswb/.blaze/aar_libraries/activity-1.0.0-rc01_151eaabb.aar/R.txt (added)
  .aswb/.blaze/aar_libraries/activity-1.0.0-rc01_151eaabb.aar/aar.timestamp (added)
  .aswb/.blaze/aar_libraries/activity-1.0.0-rc01_151eaabb.aar/jars/classes_and_libs_merged.jar (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/AndroidManifest.xml (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/R.txt (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/aar.timestamp (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/annotations.zip (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/jars/classes_and_libs_merged.jar (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/proguard.txt (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/public.txt (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/res/anim/abc_fade_in.xml (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/res/anim/abc_fade_out.xml (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/res/anim/abc_grow_fade_in_from_bottom.xml (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/res/anim/abc_popup_enter.xml (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/res/anim/abc_popup_exit.xml (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/res/anim/abc_shrink_fade_out_from_bottom.xml (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/res/anim/abc_slide_in_bottom.xml (added)
  .aswb/.blaze/aar_libraries/appcompat-1.1.0-rc01_1bedbbb1.aar/res/anim/abc_slide_in_top.xml (added)
  (and 973 more)

Querying targets in project directories...
Command: /home/sevar/bin/bazel query --tool_tag=ijwb:AndroidStudio --output=label_kind --keep_going "attr(\"tags\", \"^((?!manual).)*$\", //...:all - //bazel-bin/...:all - //bazel-genfiles/...:all - //bazel-out/...:all - //bazel-testlogs/...:all - //bazel-mediapipe/...:all - //.aswb/...:all)" --

1310 targets found under project directories; syncing 190 of them.
Sync targets from project view directories:
  //third_party:androidx_material
  //mediapipe/util/tracking:push_pull_filtering_proto
  //mediapipe/util/tracking:frame_selection_proto
  //mediapipe/util/tracking:frame_selection_solution_evaluator_proto
  //mediapipe/util/tracking:camera_motion_proto
  //mediapipe/java/com/google/mediapipe/components:android_microphone_helper
  //mediapipe/gpu:gl_surface_sink_calculator_proto
  //mediapipe/gpu:gl_scaler_calculator_proto
  //mediapipe/gpu:gl_context_options_proto
  //mediapipe/gpu:copy_calculator_proto
  //mediapipe/framework/tool:source_proto
  //mediapipe/framework/tool:node_chain_subgraph_proto
  //mediapipe/framework/tool:calculator_graph_template_java_proto
  //mediapipe/framework/testdata:zoo_mutation_calculator_proto
  //mediapipe/framework/testdata:zoo_mutator_proto
  //mediapipe/framework/testdata:sky_light_calculator_proto
  //mediapipe/framework/testdata:night_light_calculator_proto
  //mediapipe/framework/stream_handler:timestamp_align_input_stream_handler_proto
  //mediapipe/framework/stream_handler:sync_set_input_stream_handler_proto
  //mediapipe/framework/stream_handler:fixed_size_input_stream_handler_proto
  //mediapipe/framework/stream_handler:default_input_stream_handler_proto
  //mediapipe/framework/formats/object_detection:anchor_proto
  //mediapipe/framework/formats/motion:optical_flow_field_data_proto
  //mediapipe/framework/formats/annotation:locus_proto
  //mediapipe/framework/formats:rect_proto
  //mediapipe/framework/formats:rect_java_proto_lite
  //mediapipe/framework/formats:matrix_data_proto
  //mediapipe/framework/formats:classification_proto
  //mediapipe/framework:thread_pool_executor_proto
  //mediapipe/framework:test_calculators_proto
  //mediapipe/framework:packet_test_proto
  //mediapipe/framework:calculator_contract_test_proto
  //mediapipe/examples/desktop/autoflip/quality:focus_point_proto
  //mediapipe/examples/desktop/autoflip/calculators:video_filtering_calculator_proto
  //mediapipe/examples/desktop/autoflip/calculators:signal_fusing_calculator_proto
  //mediapipe/examples/desktop/autoflip/calculators:shot_boundary_calculator_proto
  //mediapipe/examples/desktop/autoflip/calculators:scene_cropping_calculator_proto
  //mediapipe/examples/desktop/autoflip/quality:cropping_proto
  //mediapipe/examples/desktop/autoflip/calculators:localization_to_region_calculator_proto
  //mediapipe/examples/desktop/autoflip/calculators:face_to_region_calculator_proto
  //mediapipe/examples/desktop/autoflip/quality:visual_scorer_proto
  //mediapipe/examples/desktop/autoflip/calculators:border_detection_calculator_proto
  //mediapipe/examples/desktop/autoflip:autoflip_messages_proto
  //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu:mediapipe_lib
  //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu:mediapipe_lib
  //mediapipe/framework/formats:detection_java_proto_lite
  //mediapipe/framework/formats:detection_proto
  //mediapipe/framework/formats:location_data_proto
  //mediapipe/framework/formats/annotation:rasterization_proto
  //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu:mediapipe_lib

Plus 140 more targets
Sync targets from project view targets:
  //mediapipe/examples/android/...:all
  //mediapipe/java/...:all

Building Bazel targets...
Command: /home/sevar/bin/bazel build --tool_tag=ijwb:AndroidStudio --keep_going --build_event_binary_file=/tmp/intellij-bep-436a821d-963b-47cc-b52a-c9998348dc75 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/home/sevar/.AndroidStudio3.5/config/plugins/aswb/aspect --output_groups=intellij-info-android,intellij-info-generic,intellij-info-java,intellij-info-kt,intellij-resolve-android,intellij-resolve-java,intellij-resolve-kt -- //third_party:androidx_material //mediapipe/util/tracking:push_pull_filtering_proto //mediapipe/util/tracking:frame_selection_proto //mediapipe/util/tracking:frame_selection_solution_evaluator_proto //mediapipe/util/tracking:camera_motion_proto //mediapipe/java/com/google/mediapipe/components:android_microphone_helper //mediapipe/gpu:gl_surface_sink_calculator_proto //mediapipe/gpu:gl_scaler_calc...
Loading: 
Loading: 0 packages loaded
INFO: Build option --apple_generate_dsym has changed, discarding analysis cache.
Analyzing: 225 targets (40 packages loaded, 0 targets configured)
ERROR: /home/sevar/.cache/bazel/_bazel_sevar/ebe89b353648009692a4e0f5cb7407b5/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_x86_64'
ERROR: While resolving configuration keys for @com_google_absl//absl/time:time: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/strings:strings: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/synchronization:synchronization: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/memory:memory: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: /home/sevar/.cache/bazel/_bazel_sevar/ebe89b353648009692a4e0f5cb7407b5/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 21. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]. Bazel will attempt to treat the NDK as if it was r20. This may cause compilation and linkage problems. Please download a supported NDK version.
WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
ERROR: While resolving configuration keys for @com_google_protobuf//:protobuf: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/base:core_headers: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/types:optional: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/meta:type_traits: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/container:flat_hash_set: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/container:flat_hash_map: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/base:dynamic_annotations: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/strings:str_format: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/algorithm:container: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/container:fixed_array: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
ERROR: While resolving configuration keys for @com_google_absl//absl/base:base: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
Analyzing: 225 targets (175 packages loaded, 13572 targets configured)
Analyzing: 225 targets (181 packages loaded, 13916 targets configured)
WARNING: errors encountered while analyzing target '//mediapipe/gpu:gl_ios_test': it will not be built
INFO: Analysis succeeded for only 224 of 225 top-level targets
INFO: Analyzed 225 targets (181 packages loaded, 14110 targets configured).

INFO: Found 224 targets...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 8.943s, Critical Path: 0.02s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully
build invocation result: build_error
Sync was successful, but there were Bazel build errors. The project may not be fully updated or resolve until fixed. If the errors are from your working set, please uncheck 'Bazel > Sync > Expand Sync to Working Set' and try again.
Parsing build outputs...
Total rules: 380, new/changed: 0, removed: 0
Reading IDE info result...
Updating target map
Loaded 0 aspect files, total size 0kB
Target map size: 269
Reading jdeps files...
Loaded 0 jdeps files, total size 0kB
Reading package manifests...
Java content entry count: 2
Updating Unpacked AAR libraries...
Updating Jar Cache...
Total Jar Cache size: 21813 kB (76 files)
Prefetching files...
Refreshing files
Computing directory structure...
Initializing project SDKs...
Committing project structure...
Workspace has 89 libraries
Android resource module count: 10, run config modules: 0, order entries: 20, generated resources: 0
Workspace has 12 modules
Updating in-memory state...
Could not read from manifest file: /home/sevar/workspace/android/mediapipe/AndroidManifest.xml
Sync finished

Timing summary:
BlazeInvocation: 9.4s, Prefetching: 1ms, Other: 103ms
```

**Comment by sevar83** [comment]
Just no note that I've managed to build them through the command line as suggested in the READMEs.

**Comment by SHWON96** [comment]
I have same issue as you. did you solve this problem?

**Comment by anhduy5689h** [comment]
I also have the same issue with Environment MACOS.

**Comment by konovalov-k** [comment]
> The error could mean that Bazel can't find an appropriate c++ compiler on your mac. Did you install Xcode in your /Applications folder (that's where Bazel will look for it), and are the Xcode command line tools also installed?
Link -  #https://github.com/google/mediapipe/issues/31
I found it in closed issues, can you @anhduy5689h @SHWON96 check it? Do you have installed XCode?

**Comment by sheep94lion** [comment]
I met the same problem on Linux, I follow the tutorial to build the project in Android studio:
https://google.github.io/mediapipe/getting_started/building_examples.html#android

**Comment by Samuel-wei** [comment]
Hi, I have same issue, any advise for me? thank you .

Environment:
Ubuntu 20.04 64-bit
Android Studio 3.5.3
SDK installed
NDK installed
Bazel plugin for IntelliJ
Bazel 4.0.0


Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: /usr/bin/bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --

Command: git diff --name-status --no-renames 8ac2d4dbb7a6addfe7be0258663d5b8acf77bb3b

Computing VCS working set...
  .aswb/.bazelproject (added)
  .aswb/.blaze/modules/.project-data-dir.iml (added)
  .aswb/.blaze/modules/.workspace.iml (added)
  .aswb/.idea/.name (added)
  .aswb/.idea/codeStyles/Project.xml (added)
  .aswb/.idea/externalDependencies.xml (added)
  .aswb/.idea/misc.xml (added)
  .aswb/.idea/modules.xml (added)
  .aswb/.idea/runConfigurations.xml (added)
  .aswb/.idea/vcs.xml (added)
  .aswb/.idea/workspace.xml (added)
  WORKSPACE (modified)
  setup_android_sdk_and_ndk.sh (modified)

Sync targets from working set:
  //:all

Querying targets in project directories...
Command: /usr/bin/bazel query --tool_tag=ijwb:AndroidStudio --output=label_kind --keep_going "attr(\"tags\", \"^((?!manual).)*$\", //...:all - //mediapipe/objc/...:all - //mediapipe/examples/ios/...:all - //bazel-bin/...:all - //bazel-genfiles/...:all - //bazel-out/...:all - //bazel-testlogs/...:all - //bazel-mediapipe/...:all - //.aswb/...:all)" --

2329 targets found under project directories; syncing 353 of them.
Sync targets from project view directories:
  //third_party:androidx_material
  //mediapipe/util/tracking:push_pull_filtering_proto
  //mediapipe/util/tracking:frame_selection_proto
  //mediapipe/util/tracking:frame_selection_solution_evaluator_proto
  //mediapipe/util/tracking:camera_motion_proto
  //mediapipe/util:render_data_java_proto_lite
  //mediapipe/util:color_java_proto_lite
  //mediapipe/util:audio_decoder_java_proto_lite
  //mediapipe/modules/objectron/calculators:tflite_tensors_to_objects_calculator_java_proto_lite
  //mediapipe/modules/objectron/calculators:tflite_tensors_to_objects_calculator_proto
  //mediapipe/modules/objectron/calculators:tensors_to_objects_calculator_java_proto_lite
  //mediapipe/modules/objectron/calculators:tensors_to_objects_calculator_proto
  //mediapipe/modules/objectron/calculators:object_java_proto_lite
  //mediapipe/modules/objectron/calculators:lift_2d_frame_annotation_to_3d_calculator_java_proto_lite
  //mediapipe/modules/objectron/calculators:lift_2d_frame_annotation_to_3d_calculator_proto
  //mediapipe/modules/objectron/calculators:frame_annotation_tracker_calculator_java_proto_lite
  //mediapipe/modules/objectron/calculators:frame_annotation_tracker_calculator_proto
  //mediapipe/modules/objectron/calculators:frame_annotation_to_rect_calculator_java_proto_lite
  //mediapipe/modules/objectron/calculators:frame_annotation_to_rect_calculator_proto
  //mediapipe/modules/objectron/calculators:filter_detection_calculator_java_proto_lite
  //mediapipe/modules/objectron/calculators:filter_detection_calculator_proto
  //mediapipe/modules/objectron/calculators:camera_parameters_java_proto_lite
  //mediapipe/modules/objectron/calculators:camera_parameters_proto
  //mediapipe/modules/objectron/calculators:belief_decoder_config_java_proto_lite
  //mediapipe/modules/objectron/calculators:belief_decoder_config_proto
  //mediapipe/modules/objectron/calculators:annotation_java_proto_lite
  //mediapipe/modules/objectron/calculators:annotation_proto
  //mediapipe/modules/objectron/calculators:object_proto
  //mediapipe/modules/objectron/calculators:a_r_capture_metadata_java_proto_lite
  //mediapipe/modules/objectron/calculators:a_r_capture_metadata_proto
  //mediapipe/modules/holistic_landmark/calculators:roi_tracking_calculator_java_proto_lite
  //mediapipe/modules/holistic_landmark/calculators:roi_tracking_calculator_proto
  //mediapipe/modules/face_geometry/protos:mesh_3d_java_proto_lite
  //mediapipe/modules/face_geometry/protos:geometry_pipeline_metadata_java_proto_lite
  //mediapipe/modules/face_geometry/protos:environment_java_proto_lite
  //mediapipe/modules/face_geometry/protos:geometry_pipeline_metadata_proto
  //mediapipe/modules/face_geometry:geometry_pipeline_calculator_java_proto_lite
  //mediapipe/modules/face_geometry:geometry_pipeline_calculator_proto
  //mediapipe/modules/face_geometry:env_generator_calculator_java_proto_lite
  //mediapipe/modules/face_geometry:env_generator_calculator_proto
  //mediapipe/modules/face_geometry/protos:environment_proto
  //mediapipe/modules/face_geometry:effect_renderer_calculator_java_proto_lite
  //mediapipe/modules/face_geometry:effect_renderer_calculator_proto
  //mediapipe/java/com/google/mediapipe/components:android_microphone_helper
  //mediapipe/graphs/object_detection_3d/calculators:model_matrix_java_proto_lite
  //mediapipe/graphs/object_detection_3d/calculators:model_matrix_proto
  //mediapipe/graphs/object_detection_3d/calculators:gl_animation_overlay_calculator_java_proto_lite
  //mediapipe/graphs/object_detection_3d/calculators:gl_animation_overlay_calculator_proto
  //mediapipe/graphs/object_detection_3d/calculators:annotations_to_render_data_calculator_java_proto_lite
  //mediapipe/graphs/object_detection_3d/calculators:annotations_to_render_data_calculator_proto

Plus 303 more targets
Sync targets from project view targets:
  //mediapipe/examples/android/...:all
  //mediapipe/java/...:all

Building Bazel targets...
Command: /usr/bin/bazel build --tool_tag=ijwb:AndroidStudio --keep_going --build_event_binary_file=/tmp/intellij-bep-b470340d-191e-44a8-ba59-d21d628b7074 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/home/samuel/.AndroidStudio3.5/config/plugins/aswb/aspect --output_groups=intellij-info-android,intellij-info-generic,intellij-info-java,intellij-resolve-android,intellij-resolve-java -- //:all //mediapipe/calculators/audio:mfcc_mel_calculators_proto //mediapipe/calculators/audio:rational_factor_resample_calculator_proto //mediapipe/calculators/audio:spectrogram_calculator_proto //mediapipe/calculators/audio:stabilized_log_calculator_proto //mediapipe/calculators/audio:time_series_framer_calculator_proto //mediapipe/calculators/core:clip_vector_size_calculator_java_pr...
Loading: 
Loading: 0 packages loaded
Analyzing: 400 targets (0 packages loaded, 0 targets configured)
ERROR: /home/samuel/.cache/bazel/_bazel_samuel/8816d386203000a152c9d1ae5d26ed67/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_x86_64'
ERROR: /home/samuel/.cache/bazel/_bazel_samuel/8816d386203000a152c9d1ae5d26ed67/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Analyzing: 400 targets (7 packages loaded, 177 targets configured)
Sync cancelled

**Comment by sgowroji** [comment]
bazel clean --expunge; will resolve this issue.
