### ISSUE TITLE
How to install mediapipe 0.9.0.1 on Jetson Nano

### ISSUE THREAD

**Issue by rahulthemillionvisions** [google/mediapipe#4020]
<em>Please make sure that this is a feature request.</em>

**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using):
- Programming language : C++/typescript/Python/Objective C/Android Java
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state:**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Please specify the use cases for this feature:**

**Any Other info:**

**Comment by ayushgdev** [comment]
Hello @rahulthemillionvisions To use MediaPipe solutions on Jetson Nano, you need to build Python package from the source as prescribed [here](https://google.github.io/mediapipe/getting_started/troubleshooting.html#python-dll-load-failure-on-windows). However, the Python package available on Pypi and the Github source are not in sync (as reported in #4002). Github source has v0.8.11 and Pypy has v0.9.0.1. 
This will be addressed in upcoming days with new release. Post that, you will be able to build and install MP > v0.9.0.1 . Apologies for the inconvenience caused.

**Comment by ayushgdev** [comment]
Hello @rahulthemillionvisions We have released new version of MediaPipe on both PyPi and GitHub. Now you can build Python package v0.9.1 from the source as prescribed [here](https://google.github.io/mediapipe/getting_started/troubleshooting.html#python-dll-load-failure-on-windows)
