### ISSUE TITLE
A Question on visiblity in Mediapipe pose solution

### ISSUE THREAD

**Issue by crapper** [google/mediapipe#4021]
Currently, I am doing experiment with mediapipe with some fitness activity. I understanded that the min confidence allow the model to eliminate the calculation once those frames with not all 33 point with higher than the min confidence was found which speed up the whole process.

However, I saw there a visiblity field for the output landmarks for each points. the drawing_utils.py provided a view to control the threshold of this visiblity and not draw those points below it. 
![image](https://user-images.githubusercontent.com/26902835/214022430-6d416a3f-97e1-45c5-96be-d75b8cea26bd.png)

I want to ask since those 33 keypoints have to be all over the min_confidence such to be calculated, why we still need to use visiblity to eliminate those points for showing in the frame?

I can set the visiblity to 0 such to show the lower body:
![image](https://user-images.githubusercontent.com/26902835/214022810-5427ad26-b5fb-4bc3-8330-8b236921461e.png)

**Comment by rm6759** [comment]
I find the visibility value in each landmark tuple to be useful as a weight/validation.  When calculating a relationship between two keypoints, I may include visibility within the calculation as a means of weighting the calculation.  

Visibility values can be very helpful in evaluating how the model may be inferring  keypoints in various poses which allows more flexibility in coding. 

With models never being 100% accurate, more information is helpful.

**Comment by kuaashish** [comment]
Hello @crapper,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
