### ISSUE TITLE
Train Mediapipe Blazepose Solution with Different Datasets

### ISSUE THREAD

**Issue by amaan4152** [google/mediapipe#4023]
I am a graduate student at The Cooper Union working on a thesis project and have contacted the authors directly but got no reply back regarding this concern. 

I was wondering if it is possible to train the original Blazepose model in Python using different datasets such as Human3.6M. Looking at other issues, it seems y'all are redirecting us to look at constructing Mediapipe graphs, but I don't see how we can use graphs to train y'all's original Blazepose model with different datasets. 

It would be greatly appreciated if you can mention if it is possible to do what I have mentioned, and if so, how would one go about this?

**Comment by kuaashish** [comment]
@amaan4152,
Yes, this is possible but the basic scheme is fairly common with MediaPipe, replacing only the model, keeping the calculator-graphs. The model needs to be trained with the exact same signature (input and output fields).  
Model training is mostly separate from calculator-graphs, it is organized according to model-metadata.

**Comment by amaan4152** [comment]
When you mention model-metadata are you referencing how I would need to utilize MediaSequence to construct my dataset and use the appropriate calculators for MediaSequence? 

Also, examining the current graphs for `pose_tracking`, the graphs seem to utilize inference calculators for the pose models. Are there pose model graphs that contain calculators for the entire Blazepose architecture such that I can train all the layers appropriately with the Human3.6M dataset? 

I am still struggling to grasp the entire workflow for training Blazepose using Mediapipe. I somewhat understand that we can use MediaSequence to compile video frames as a dataset. But, how can I utilize a directory of multiple video sequences with their respective annotations and feed that into a Blazepose training graph?

**Comment by amaan4152** [comment]
Hi, I was wondering if I could get more insight on the general issue I stated above. It would be great if I could be guided to train the original Blazepose architecture with the popular Human3.6M dataset. The resources I have been directed to were a bit enigmatic to follow through. Assistance would be greatly appreciated.

**Comment by kuaashish** [comment]
Hello @amaan4152,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Although, Our new solutions model maker can take your datasets work as per the your use case. Thank you

**Comment by kuaashish** [comment]
Hello @amaan4152,
For now, only image classification and Object detection models can be retrained with model maker. We will let you know if any specific updates will become available about the support of pose landmark. Thank you

**Comment by scottxp** [comment]
+1 on model maker for pose landmark detection.

I am interested in retraining the BlazePose model using model maker for better accuracy, specifically in the detection of the wrist landmarks. Our use case is to accurately detect wrist position during chest compressions. BlazePose is quite good out of the box, but will occasionally drift near the top and bottom of the compression. 

I've also tried the hand detection model, but it tends to be problematic since the hands are overlapping. Is a brand new, custom-trained model my best bet in this case, either to replace the current model or to augment the wrist landmark positions as another node in the graph? Any suggestions are much appreciated!

**Comment by 124bit** [comment]
+1 on model maker for pose landmark detection.
