### ISSUE TITLE
How to blur the background except the selfie segmentation using Javascript?

### ISSUE THREAD

**Issue by yellagoud** [google/mediapipe#4025]
I would like to implement blur background with Selfie segmentation. I don't find any answers to blur the background image using Mediapipes Javascript API? Please let us know if we have any other options.

**Comment by ayushgdev** [comment]
Hello @yellagoud 
Selfie Segmentation with background blur cannot be implemented in Javascript API as of now. We only have released background re-color calculator compiled for JS solution. Unfortunately, there aren't any other solution in Mediapipe which support blur as well. 
However, with Python and/or C++, it is possible since with those solutions, you can edit graph and recompile the binaries. Thus [MaskOverlayCalculator](https://github.com/google/mediapipe/blob/61bc4556af586bb3837f17187568d1345b3ee8f5/mediapipe/calculators/image/mask_overlay_calculator.cc) can be used for that purpose.

**Comment by yellagoud** [comment]
Hello @ayushgdev 
Thank you for the reply.
To fix this, I am drawing each Frame received from the selfie segmented result onto the new Canvas element and doing the blur using the canvas context filter method.
ctx.filter = 'blur(20px)'

This is blurring each frame but the problem is when I maximize the chrome window canvas drawing is getting slow resulting in slow video motion.

Do you have any idea? why the canvas drawing is causing slow when we maximize the window?

**Comment by ayushgdev** [comment]
Hello @yellagoud I did create an example to use canvas context blur filter on image rendering. You can find the example [here](https://github.com/ayushgdev/MediaPipeCodeSamples/blob/main/Vanilla%20JS/selfie%20segmentation%20with%20bg%20blur.html). However, I am not able to find the issue of slow video motion. Please check if this example works fine at your end.

**Comment by yellagoud** [comment]
Hello @ayushgdev Thank you so much for your reply. 

I am loading all the media pipe-related JS code in the parent window in my application and loading video in the child window and applying blur background in the child window. If I maximize the child window then selfie segmentation result frames are receiving very slowly which is causing the observable delay.

But if I load in Video in the parent window itself and apply blur background then frames are received without delay. In your example, if you load all JS code in the parent window and show the video in the Child window and apply blur then in maximize mode you may see the same issue.

**Comment by ayushgdev** [comment]
@yellagoud Thanks for the explanation. However the usage of two windows is still unclear. Is it possible to provide a **minimal** example over GitHub so reproduce the issue at our end?

**Comment by danrossi** [comment]
I just discovered the calculator MaskOverlayCalculator. How is it possible to do a full texture masking for the javascript solution. It seems to be doing a shader mix like I would have to be doing in javascript. If its done in the gpu buffer directly it would be more efficient. Than having to reprint the video and add the mask in webgl. I noticed the video input is printed to a webgl context also. So having to reprint after is inefficient, the texture for the frame could be used directly. 

I asked in another ticket of also adding SegmentationSmoothingCalculator to smooth the mask before applying to the video texture. The edges are blocky requiring inefficient bilateral filter of the mask in a shader afterwards. 

I would rather not having to maintain custom compiles. Do these need to be compiled into a special graph file for segmentation. And does this need to be done on different platforms. Its confusing how you build with special calculators in there other than what is default. I think the masking of the video texture and smoothing should be default.

**Comment by danrossi** [comment]
According to this. This is the usage for the mask calculator. So it takes a background image texture to mix with the video texture and the mask. As I have to do in my webgl shader. 

Is this possible via the javascript implementation ? Adding a background image for the texture. There is alot of interesting calculators not enabled by default and of use for the purposing of masking a video texture with background image. 

I'm still fine tuning my shader, it takes the alpha not r from the mask as I am rendering the mask as alpha to webgl

```
gl_FragColor = mix(bgTex, vec4(frameTex.rgb, 1.0), maskTex.a);
```

https://github.com/google/mediapipe/issues/1123#issuecomment-727108695
