### ISSUE TITLE
Cannot build example android apps in WSL

### ISSUE THREAD

**Issue by philiprkk** [google/mediapipe#4026]
Hello, I'm trying to build the example Android apps through WSL (Ubuntu 22.04) on my Windows 11 machine but I'm having trouble with some paths. I've followed the instructions but it seems like there's some misalignment between the android sdk/ndk folder structure and what the build process is looking for.

There error:
```
ERROR: /home/philip/Repositories/mediapipe/WORKSPACE:547:23: fetching android_sdk_repository rule //external:androidsdk: java.io.IOException: Expected directory at /home/philip/Android/Sdk/platforms but it is not a directory or it does not exist. Unable to read the Android SDK at /home/philip/Android/Sdk, the path may be invalid. Is the path in android_sdk_repository() or ANDROID_HOME set correctly? If the path is correct, the contents in the Android SDK directory may have been modified.
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: Expected directory at /home/philip/Android/Sdk/platforms but it is not a directory or it does not exist. Unable to read the Android SDK at /home/philip/Android/Sdk, the path may be invalid. Is the path in android_sdk_repository() or ANDROID_HOME set correctly? If the path is correct, the contents in the Android SDK directory may have been modified.
INFO: Elapsed time: 0.369s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded, 12 targets configured)
    currently loading: @rules_foreign_cc//tools/build_defs/shell_toolchain/toolchains ... (4 packages)
    Fetching @androidndk; Restarting.
    Fetching @remotejdk11_linux_toolchain_config_repo; fetching
    Fetching @remotejdk11_linux_s390x_toolchain_config_repo; fetching

philip:~/Repositories/mediapipe$ echo $ANDROID_HOME
/home/philip/Android/Sdk/
philip:~/Repositories/mediapipe$ echo $ANDROID_NDK_HOME
/home/philip/Android/Sdk/ndk-bundle/android-ndk-r21/
```

The last lines in the WORKSPACE file autogenerated from running the setup:
android_sdk_repository(name = "androidsdk", path = "/home/philip/Android/Sdk")
android_ndk_repository(name = "androidndk", api_level=21, path = "/home/philip/Android/Sdk/ndk-bundle/android-ndk-r21")

**Comment by kuaashish** [comment]
Hi @philiprkk,
Would you please let us know if this closed issue [#1281(comment)](https://github.com/google/mediapipe/issues/1281#issuecomment-786498715) resolves the above error you are getting?

**Comment by philiprkk** [comment]
> Hi @philiprkk, Would you please let us know if this closed issue [#1281(comment)](https://github.com/google/mediapipe/issues/1281#issuecomment-786498715) resolves the above error you are getting?

Isn't that what I'm doing already here?
android_ndk_repository(name = "androidndk", api_level=21, path = "/home/philip/Android/Sdk/ndk-bundle/android-ndk-r21")

**Comment by kuaashish** [comment]
Hi @philiprkk,
Could you please confirm that you are still looking for resolution or the issue has been fixed? Thank you!

**Comment by philiprkk** [comment]
> Hi @philiprkk, Could you please confirm that you are still looking for resolution or the issue has been fixed? Thank you!

Hello, I never resolved the issue but I'm not currently looking for a resolution either, thank you
