### ISSUE TITLE
Camera orientation doesn't change when app orientation does

### ISSUE THREAD

**Issue by javaservlets** [google/mediapipe#4029]
Hi... this issue was closed as stale but it has not been fixed. Ie, issue is that while it is indeed possible to change the app orientation to horizontal, the *camera* orientation does not change. Is there a way to programmatically change the camera orientation too? 

Original posting: "Sorry, this does not work for me. The app and all layout elements rotate. But the camera picture is 90 degrees wrong. How can I rotate the camera picture with the hand landmarks on it?

_Originally posted by @drink2 in https://github.com/google/mediapipe/issues/3877#issuecomment-1384420543_

**Comment by kuaashish** [comment]
Hi @javaservlets,
Would you let us know the complete steps followed to reproduce the issue? Android solution you are using such as maven prebuilt and building the app through the android aar as mentioned here in [documentation](https://google.github.io/mediapipe/getting_started/android.html).

**Comment by javaservlets** [comment]
steps to reproduce: 
1. build the OOTB GestureRecognition APK from https://developers.google.com/mediapipe/solutions/vision/gesture_recognizer/android
2. change the manifest file so that default orientation is landscape
==> note that it is 'indeed possible to change the app orientation to horizontal, but the camera orientation does not change. 

Ie, the app will be in landscape but the camera stays in portrait.

verified on a galaxy 22; based on what I've read on S.O, some other vendors may have 'better behaving' cameras

**Comment by kuaashish** [comment]
@javaservlets,
This gives you better understanding [#4006(comment)](https://github.com/google/mediapipe/issues/4006#issuecomment-1400068251) on the query raised. Thanks!

**Comment by kuaashish** [comment]
@javaservlets,
Could you please go through the above [comment](https://github.com/google/mediapipe/issues/4029#issuecomment-1410004823) and feel free to close if this is no longer issue from your end. thank you!
