### ISSUE TITLE
Objectron for Human detection

### ISSUE THREAD

**Issue by SRai22** [google/mediapipe#4032]
**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): Objectron
- Programming language : typescript/javascript
- Are you willing to contribute it (Yes/No): Yes

Describe the feature and the current behavior/state: Current objectron models identify specific objects like chair, shoe etc. This request is to create a model for 3D bounding box detection of humans. The object detection detects the humans as bounding boxes, but getting a 3D bounding box around and tracking it would open up new avenues to use mediapipe.

Will this change the current api? How? No, it should not because it is only adding a new object model which outputs a bounding box similar to existing one

Who will benefit with this feature?
Mobile users as well as adds to IoT applications

Please specify the use cases for this feature:
Clothing apps, Covid like 6 ft distance alerting, Robotics edge compute ODOA systems

**Comment by kuaashish** [comment]
Hi @SRai22,
This looks interesting feature request! We are sharing this request internally and based on discussion will prioritize among others. Thank you!

**Comment by kuaashish** [comment]
Hello @SRai22,
We are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), but upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. However, We can see that this feature has been added to the new MediaPipe solution and Demo to detect person can been seen [here](https://mediapipe-studio.webapps.google.com/demo/object_detector). Thank you

**Comment by kuaashish** [comment]
@SRai22, 
Thank you reverting back and actively using our solutions. 
As this feature has been already added here, Can we go ahead and mark the issue as closed?

**Comment by SRai22** [comment]
I'll have to disagree on the subject of this feature being added already. The request was more specific on identifying 3D bounding boxes around human in the scene similar to the existing 'cup objectron', 'shoe objectron', 'chair objectron'. But since the support on objectron is no longer continued, I think you can close this issue. 

Thanks

**Comment by kuaashish** [comment]
@SRai22,
Apologies for the misunderstanding. We would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. Thank you
