### ISSUE TITLE
Can we find the circumference of the finger?

### ISSUE THREAD

**Issue by DenizEs-1** [google/mediapipe#4033]
- When I examined the code, I observed that the points determined were the joint parts of the fingers. (all in the middle of the finger)
- İf the dots give the middle of the finger can I find the edges of the finger too?
- My goal is to find the thickness of the ring finger.

**Comment by kuaashish** [comment]
Hi @DenizEs-1,
Could you please elaborate your query with complete details? Team suggest to fill the template as mentioned [here ](https://github.com/google/mediapipe/issues/new/choose)to get the more relevant information to address better on the support you are looking. Thanks!!
