### ISSUE TITLE
Is there a way to use Mediapipe python on the web?

### ISSUE THREAD

**Issue by Prana-S** [google/mediapipe#4034]
I have been trying to use Mediapipe python on the web. Is there a way to do it?

**Comment by rm6759** [comment]
I have the same interest,  I want to avoid javascript and keep as much as possible in python.  I've looked at some python http server packages but haven't decided on one.

Streamlit looks like a nice low-code option for outputting reults.  https://streamlit.io/

**Comment by kuaashish** [comment]
Hi @Prana-S,
Currently we do not have such application build and tested using the Python. However, we can see this has already been implemented [here](https://github.com/HaoyuWang00/Mediapipe-Django-API) and example codebase with Django that might be helpful for use-case mentioned. Thank you!

**Comment by Prana-S** [comment]
When I follow those steps, my application still opens in a new window. Heres is what I see:

![image](https://user-images.githubusercontent.com/87503279/215920029-d782c663-4da8-4666-9c8f-e2539d28d846.png)

**Comment by kuaashish** [comment]
Hi @Prana-S,
We do not have the official web application build/ tested using the Python. Reference shared here is by the GitHub community member implemented the application with mediapipe. It will be good practice if you can follow and raise same issue in member [repo](https://github.com/HaoyuWang00/Mediapipe-Django-API).
