### ISSUE TITLE
How to set 0 for the value "model_complexity" for holistictrackinggpu android ?

### ISSUE THREAD

**Issue by taeyeonlee** [google/mediapipe#4035]
Hi
In Ubuntu, I just downloaded the mediapipe git source ($ git clone https://github.com/google/mediapipe.git) and build the holistictrackinggpu android solution.
$ bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/holistictrackinggpu:holistictrackinggpu
and the holistictrackinggpu.apk (which was built in the bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/holistictrackinggpu/holistictrackinggpu.apk) is working well on my Android Phone.

Do you know how to set 0 for the value "model_complexity" for holistictrackinggpu Android ?
I just modified the mediapipe/mediapipe/modules/pose_landmark/pose_landmark_model_loader.pbtxt  as like below.
```
                node {
                       calculator: "SwitchContainer"
                       input_side_packet: "SELECT:model_complexity"
                       output_side_packet: "PACKET:model_path"
                       options: {
                              [mediapipe.SwitchContainerOptions.ext] {
                                  select: 0		
```		
and built again ($ bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/holistictrackinggpu:holistictrackinggpu)
but the holistictrackinggpu.apk is not working on the Android Phone.
I want to set 0 for the value "model_complexity" for holistictrackinggpu android.

**System information** 
- OS Platform and Distribution : Ubuntu 18.04.6 LTS, Android 11):
- Compiler version : gcc 11.1.0
- Programming Language and version : Mediapipe (C++, Python 3.6, Java)
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.11
- Bazel version: 5.2.0
- Android SDK and NDK versions (if android): NDK 21.0.6113669, Android SDK Platform 11
- OpenCV version (if running on desktop): 3.4.19

**Comment by ayushgdev** [comment]
Hello @taeyeonlee 

From the file pose_landmark_model_loader.pbtxt, it can be seen model complexity is accepted as `input_side_packet`. You can set model complexity as an `input_side_packet` using the [`FrameProcessor`](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/FrameProcessor.java) API. The FrameProcessor API has a method `setInputSidePackets()`. This method accepts a hashmap as a parameter, which you can set with input side packets with `Packet` type value. The packet type value can be created using [`PacketCreator`](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/framework/AndroidPacketCreator.java) class. So in your MainActivity.java file, you can set the input side packets like below:

```
// Create packet creator object
AndroidPacketCreator packetCreator = processor.getPacketCreator();
// Create hashmap to hold packets
Map<String, Packet> inputSidePackets = new HashMap<>();
// Add the packet
Packet pkt = packetCreator.createInt32(0);
inputSidePackets.put("model_complexity", pkt);
// set input side packet to the processor
processor.setInputSidePackets(inputSidePackets);
```

**Comment by taeyeonlee** [comment]
Hello @ayushgdev 
There's no Java Android Example for holistictrackinggpu in the Git (https://github.com/google/)
Do you know where the Java Android Example for holistictrackinggpu is ?
and How to get the tflite files (pose_landmark_full.tflite, pose_landmark_lite.tflite, pose_landmark_heavy.tflite) ?

Thanks in advance

**Comment by ayushgdev** [comment]
Hello @taeyeonlee Unfortuately, there are no Java Android example available for holistic MediaPipe solution. Building an AAR package using the instructions [here](https://google.github.io/mediapipe/getting_started/android_archive_library.html) is the only viable option to use holistic tracking on Android.

**Comment by taeyeonlee** [comment]
Hello @ayushgdev 
I succeeded to build the AAR package using the instructions [https://google.github.io/mediapipe/getting_started/android_archive_library.html]
mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD.										
```
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")										
										
mediapipe_aar(										
 name = "mediapipe_holistic_gpu",										
 calculators = ["//mediapipe/graphs/holistic_tracking:holistic_tracking_gpu_deps"],										
)										
										
bazel build -c opt --strip=ALWAYS \										
 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \										
 --fat_apk_cpu=arm64-v8a,armeabi-v7a \										
 --legacy_whole_archive=0 \										
 --features=-legacy_whole_archive \										
 --copt=-fvisibility=hidden \										
 --copt=-ffunction-sections \										
 --copt=-fdata-sections \										
 --copt=-fstack-protector \										
 --copt=-Oz \										
 --copt=-fomit-frame-pointer \										
 --copt=-DABSL_MIN_LOG_LEVEL=2 \										
 --linkopt=-Wl,--gc-sections,--strip-all \										
 //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_holistic_gpu.aar										
```
  
and, downloaded the all tflite files from (https://google.github.io/mediapipe/solutions/models.html#pose)
(face_detection_full_range.tflite, face_detection_short_range.tflite, face_landmark.tflite, hand_landmark_full.tflite, hand_landmark_lite.tflite, hand_recrop.tflite, palm_detection_full.tflite, palm_detection_lite.tflite, pose_detection.tflite, pose_landmark_full.tflite, pose_landmark_heavy.tflite, pose_landmark_lite.tflite) are put on the app\src\main\assets

and buid the graph binary (holistic_tracking_gpu.binarypb)  `bazel build -c opt mediapipe/graphs/holistic_tracking:holistic_tracking_gpu `

I modified the MainActivity.java as you said.
```
    protected void onCreate(Bundle savedInstanceState) {
    			...
        processor =
                new FrameProcessor(
                        this,
                        eglManager.getNativeContext(),
                        applicationInfo.metaData.getString("binaryGraphName"),
                        applicationInfo.metaData.getString("inputVideoStreamName"),
                        applicationInfo.metaData.getString("outputVideoStreamName")
                        );
        processor
                .getVideoSurfaceOutput()
                .setFlipY(
                        applicationInfo.metaData.getBoolean("flipFramesVertically", FLIP_FRAMES_VERTICALLY));

        PermissionHelper.checkAndRequestCameraPermissions(this);

        // Create packet creator object
        AndroidPacketCreator packetCreator = processor.getPacketCreator();
				// Create hashmap to hold packets
        Map<String, Packet> inputSidePackets = new HashMap<>();
				// Add the packet
        Packet pkt = packetCreator.createInt32(0);
        inputSidePackets.put("model_complexity", pkt);
				// set input side packet to the processor
        processor.setInputSidePackets(inputSidePackets);
        ...

```
In Android Studio, the APK are buit and runs on Android phone.

but, log says 
```
2023-01-31 20:34:21.695 7787-7812/com.lite.holistic_tracking I/native: I20230131 20:34:21.695410  7812 resource_util_android.cc:90] Successfully loaded: pose_detection.tflite													
2023-01-31 20:34:21.698 7787-7893/com.lite.holistic_tracking I/native: I20230131 20:34:21.698518  7893 resource_util_android.cc:90] Successfully loaded: face_landmark.tflite													
2023-01-31 20:34:21.700 7787-7894/com.lite.holistic_tracking I/native: I20230131 20:34:21.700376  7894 resource_util_android.cc:90] Successfully loaded: hand_landmark_full.tflite													
2023-01-31 20:34:21.707 7787-7891/com.lite.holistic_tracking I/native: I20230131 20:34:21.707446  7891 resource_util_android.cc:90] Successfully loaded: hand_landmark_full.tflite													
2023-01-31 20:34:21.710 7787-7895/com.lite.holistic_tracking I/native: I20230131 20:34:21.710309  7895 resource_util_android.cc:90] Successfully loaded: pose_landmark_full.tflite													
2023-01-31 20:34:24.336 7787-7812/com.lite.holistic_tracking I/native: I20230131 20:34:24.336257  7812 resource_util_android.cc:90] Successfully loaded: hand_recrop.tflite													
2023-01-31 20:34:24.355 7787-7812/com.lite.holistic_tracking I/native: I20230131 20:34:24.355337  7812 resource_util_android.cc:90] Successfully loaded: hand_recrop.tflite													
2023-01-31 20:34:24.383 7787-7812/com.lite.holistic_tracking I/native: I20230131 20:34:24.383088  7812 resource_util_android.cc:90] Successfully loaded: face_detection_short_range.tflite		
```											

The pose_landmark_full.tflite was loaded.  I want to load the pose_landmark_lite.tflite.
Do you know how to load the pose_landmark_lite.tflite ?

**Comment by ayushgdev** [comment]
Hello @taeyeonlee Would it be possible for you to share your application/minimal holistic app on GitHub repo, if there is not an Intellectual Property issue?
