### ISSUE TITLE
Code typo in Gesture recognition code demo

### ISSUE THREAD

**Issue by taktran** [google/mediapipe#4036]
## URL(s) with the issue:

https://developers.google.com/mediapipe/solutions/vision/gesture_recognizer/web_js which links to https://codepen.io/mediapipe-preview/pen/zYamdVd in several locations

### Incorrect code

In the linked codepen (https://codepen.io/mediapipe-preview/pen/zYamdVd), there is a typo in the code, where the running modes for the video button code, need to be in all caps, as per the [docs](https://developers.google.com/mediapipe/solutions/vision/gesture_recognizer).

From line `181` of the JS file:

```diff
-  if (runningMode === "image") {
-    runningMode = "video";
+  if (runningMode === "IMAGE") {
+    runningMode = "VIDEO";
```

This means, when you click on the `ENABLE WEBCAM` button, it doesn't do anything.

Here is a forked codepen with the fixes above and the webcam button: https://codepen.io/taktran/pen/KKBBomM

The MediaPipe Studio seems to have it working as expected though: https://mediapipe-studio.webapps.google.com/demo/gesture_recognizer

### Submit a pull request?

I think someone from mediapipe just needs to update the codepen.

**Comment by ayushgdev** [comment]
Hello @taktran Thanks for identifying this bug. We will fix it in the codepen demo at the earliest

**Comment by jenperson** [comment]
The demo has been updated.

**Comment by ayushgdev** [comment]
@taktran Can you please check and let us know if your issue is fixed now? If so, we request you to close the issue.

**Comment by taktran** [comment]
It works now 🎉  Thanks!
