### ISSUE TITLE
Mediapipe release tag for v0.9.0 and v0.9.0.1

### ISSUE THREAD

**Issue by naveenkulkarni-movidius** [google/mediapipe#4037]
Mediapipe release tag on Github for PyPi version 0.9.0 and 0.9.0.1 are not available. The latest release tag in github is for v0.8.11. Can you please help tag corresponding release versions in [mediapipe github](https://github.com/google/mediapipe)?

**Comment by kuaashish** [comment]
Hi @naveenkulkarni-movidius,
Release part in the Github still on our queue. we will let you know once version and release notes will be updated. Thank you!

**Comment by kuaashish** [comment]
@naveenkulkarni-movidius,
Unfortunately, releasing the unsynced version (0.9.0.1) in GitHub repository would not be possible now as there have been lots of changes since then and it is intractable to consolidate them back in time.
Instead, a new version, v0.9.1, has been released. Now the PyPi repository and the GitHub repository are in sync.
Could you please look into this close if this is no longer issue from your end? Thank you!

**Comment by Nophlock** [comment]
Out of curiosity, what were the changes in version 0.9.0.1/0.9.0 from 0.8.11? Since I can't find any changelogs for this.

**Comment by kuaashish** [comment]
@naveenkulkarni-movidius,
Please go through the [above](https://github.com/google/mediapipe/issues/4037#issuecomment-1415103495) comment and feel free to close if no longer issue from your end. Thank you!

**Comment by naveenkulkarni-movidius** [comment]
Thank you for the update! Now I see equivalent versions of v0.9.1 on PyPi and Github repo. However I think it's important to have this info for each release. Please make sure you tag the github repo each time there is a PyPi release. Also it's good to know what improvements were made and have that available on github in release notes. Thanks again, you can close the issue.

**Comment by kuaashish** [comment]
@naveenkulkarni-movidius,
Thank you for brining to our attention, we always make sure release will be more user friendly. However, conflict between the  github repo could push the latest version `0.9.1 ` and will take the feedback to internally here. Thank you!
