### ISSUE TITLE
Mtk android mobile phone issue with mediapipe aar (black screen)

### ISSUE THREAD

**Issue by llljjj7** [google/mediapipe#4038]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- OS Platform and Distribution 
Android 12
- Mobile device:
android phone with MTK chipset - Lg Q630, Lg Velvet MTK

- Programming Language and version 
Kotlin
- Solution
Handtracking, Holistic
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
android studio : dolphin
min sdk : 29, targetSdk 32
ndk : 25.1.8937393

**Describe the current behavior:**
Hello. I am developing using Mediapipe on some Android phone.
When developing using Mediapipe aar by referring to the github below, the preview screen does not appear. (HandTracking, holistic)
(The sample app below does the same.)
https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example

It works fine on phones that use Qualcomm chips (Samsung note 20, galaxy S21, Lg V50..), but only occurs on MTK chipset phones (Lg Q630, Lg Velvet MTK). I'm not sure, but I suspect the part related to open gl.

1. It does not operate when entering for the first time, and operates normally when re-entering after exiting with the home key.
After onPause and onResume, it works normally, and when I tested it, it works normally when I restart the camera, close the converter, and recreate the converter.

2. After installing the app, the first callback (preview image or packet callback - coordinates) comes up a long time later. After receiving the callback once, the phenomenon does not occur even if restarted. In the case of LG Velvet MTK, holistic often takes more than 30 seconds.

**Describe the expected behavior:**
The camera preview screen should come out fine and the packet callback should come proper time.

**Other info / Complete Logs :**
 Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached

If you restart the camera and regenerate the convert, it works normally.
var firstCnt  = 0
private val surfaceCallback = object : SurfaceHolder.Callback {
        override fun surfaceCreated(holder: SurfaceHolder) {
            Log.d(TAG, "surfaceCreated")
            processor!!.videoSurfaceOutput.setSurface(holder.surface)
        }

        override fun surfaceChanged(holder: SurfaceHolder, format: Int, width: Int, height: Int) {
            Log.d(TAG, "surfaceChanged $width X $height")
            onPreviewDisplaySurfaceChanged(holder, format, width, height)
            if (firstCnt < 1) {
                firstCnt++
                Handler(Looper.getMainLooper()).postDelayed({
                    converter?.close()
                    previewSurfaceView?.visibility = View.GONE

                    //reInit consumer
                    converter = ExternalTextureConverter(eglManager!!.context, 2)
                    converter!!.setFlipY(FLIP_FRAMES_VERTICALLY)
                    converter!!.setConsumer(processor)
                        //start camera
                        startCamera()
                    }
                }, 1000)
            }
        }

        override fun surfaceDestroyed(holder: SurfaceHolder) {
            Log.d(TAG, "surfaceDestroyed")
            processor!!.videoSurfaceOutput.setSurface(null)
        }
    }
Thank you for reading

**Comment by kuaashish** [comment]
Hi @llljjj7,
MediaPipe models takes several seconds to load up and this behaviour is excepted. Models can take different time to load that mainly depends on the solutions using such as Holistic, Pose, Hands. In MTKs devices, that can be issue with OpenGL and chips performance compare to Qualcomm that needs more research. However, You can try out the workaround mentioned here [#1508(comment)](https://github.com/google/mediapipe/issues/1508#issuecomment-797232485). Thank you!

**Comment by kuaashish** [comment]
@llljjj7,
Could you please go through the above [comment](https://github.com/google/mediapipe/issues/4038#issuecomment-1408360395) and feel free to close this is no longer issue from your end.
