### ISSUE TITLE
gesture recognition graph

### ISSUE THREAD

**Issue by yyqgood** [google/mediapipe#404]
hello, is there a graph that provides gesture recognition?

**Comment by PrinceP** [comment]
You can always modify the existing graph
![image](https://user-images.githubusercontent.com/10251537/72951715-63be1d00-3db5-11ea-9da6-044cce28e16a.png)

At Annotation Overlay calculator, the gesture recognition code can be inserted.

**Comment by fanzhanggoogle** [comment]
Hi @yyqgood , we haven't released any graph handling gesture recognition. But with the landmarks, you should be able to recognize gestures based on the topology of each finger. You can check #296 for reference.

**Comment by yyqgood** [comment]
@fanzhanggoogle, thank you for your reply!
