### ISSUE TITLE
How to set customized model path?

### ISSUE THREAD

**Issue by jinfagang** [google/mediapipe#4040]
I am using a node graph like this:

```
(
		# MediaPipe graph that performs face mesh with TensorFlow Lite on CPU.
		# Input image. (ImageFrame)
		input_stream: "input_video"
		# Output image with rendered results. (ImageFrame)
		output_stream: "output_video"
		# Collection of detected/processed faces, each represented as a list of
		# landmarks. (std::vector<NormalizedLandmarkList>)
		output_stream: "multi_face_landmarks"
		# Throttles the images flowing downstream for flow control. It passes through
		# the very first incoming image unaltered, and waits for downstream nodes
		# (calculators and subgraphs) in the graph to finish their tasks before it
		# passes through another image. All images that come in while waiting are
		# dropped, limiting the number of in-flight images in most part of the graph to
		# 1. This prevents the downstream nodes from queuing up incoming images and data
		# excessively, which leads to increased latency and memory usage, unwanted in
		# real-time mobile applications. It also eliminates unnecessarily computation,
		# e.g., the output produced by a node may get dropped downstream if the
		# subsequent nodes are still busy processing previous inputs.
		node {
			calculator: "FlowLimiterCalculator"
			input_stream: "input_video"
			input_stream: "FINISHED:output_video"
			input_stream_info: {
				tag_index: "FINISHED"
				back_edge: true
			}
			output_stream: "throttled_input_video"
		}
		# Defines side packets for further use in the graph.
		node {
			calculator: "ConstantSidePacketCalculator"
			output_side_packet: "PACKET:0:num_faces"
			output_side_packet: "PACKET:1:use_prev_landmarks"
			output_side_packet: "PACKET:2:with_attention"
			node_options: {
				[type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
					packet { int_value: 1 }
					packet { bool_value: true }
					packet { bool_value: true }
				}
			}
		}
		# Subgraph that detects faces and corresponding landmarks.
		node {
			calculator: "FaceLandmarkFrontCpu"
			input_stream: "IMAGE:throttled_input_video"
			input_side_packet: "NUM_FACES:num_faces"
			input_side_packet: "USE_PREV_LANDMARKS:use_prev_landmarks"
			input_side_packet: "WITH_ATTENTION:with_attention"
			output_stream: "LANDMARKS:multi_face_landmarks"
			output_stream: "ROIS_FROM_LANDMARKS:face_rects_from_landmarks"
			output_stream: "DETECTIONS:face_detections"
			output_stream: "ROIS_FROM_DETECTIONS:face_rects_from_detections"
		}
		# Subgraph that renders face-landmark annotation onto the input image.
		node {
			calculator: "FaceRendererCpu"
			input_stream: "IMAGE:throttled_input_video"
			input_stream: "LANDMARKS:multi_face_landmarks"
			input_stream: "NORM_RECTS:face_rects_from_landmarks"
			input_stream: "DETECTIONS:face_detections"
			output_stream: "IMAGE:output_video"
		}
	)
```

This will using a default path of tflite,

Is there a way to set a cusomtized tflite path? In somwhwat reason my project **must** using a customized path.

**Comment by andrechen** [comment]
one way to specify resource root directory is to use **resource_root_dir** command line flag
https://github.com/google/mediapipe/blob/ee2f940e1fcc0e07c16afd773250b42ad41b36af/mediapipe/util/resource_util_default.cc#L52

like...
https://github.com/andrechen/mediapipe/blob/6507d32a91618c36df0203ae55b31be16f793276/visualstudio/demo_run_graph_main.cc#L208

**Comment by jinfagang** [comment]
@andrechen  Hello, I didn't use absl neither glog.

Also, I think this is not a universal way.

Does there any way to set specific Node model path customized in proto?

**Comment by schmidt-sebastian** [comment]
Unfortunately, this graph currently doesn't allow custom locations for file names. What environment are you running the graph under? You should be able to set the flag `--resource_root_dir` to point to any directory or relative path on your system (as you invoke your binary).

**Comment by jinfagang** [comment]
@schmidt-sebastian  hello, if graph can not specific, which code/entrance I can set to support? Or how to modify graph node name to set model path (I think it should be supported)

Since you said there is a flag can specific, where does this flag takes effect? 

I need manually set model path since my program runs on a relative bin, which should using my path otherwise I don't know where to put these assets.

**Comment by schmidt-sebastian** [comment]
Unfortunately, this part of the code does not let you specify the path as part of the graph. This is a design decision that we hope to mitigate soon in newer versions of this API (but this could take a while).

I am not sure how you launch your binary. The command line flag above can be passed to the MediaPipe binary as you would pass any other environment variables. Can you let us know how you launch your process? We might be able to help then.

**Comment by lwcode** [comment]
> Unfortunately, this part of the code does not let you specify the path as part of the graph. This is a design decision that we hope to mitigate soon in newer versions of this API (but this could take a while).
> 
> I am not sure how you launch your binary. The command line flag above can be passed to the MediaPipe binary as you would pass any other environment variables. Can you let us know how you launch your process? We might be able to help then.

like this: .\holistic_tracking_cpu.exe --resource_root_dir asserts
but it do not work, get the error,such as:
Calculator::Open() for node "holisticlandmarkcpu__poselandmarkcpu__poselandmarkbyroicpu__poselandmarkmodelloader__LocalFileContentsCalculator" failed: ; Can't find file: mediapipe/modules/pose_landmark/pose_landmark_full.tflite
