### ISSUE TITLE
Can't iter the output landmark 

### ISSUE THREAD

**Issue by lucasjinreal** [google/mediapipe#4042]
I simply get output with this:

```c++


if (mp_pipe->GetOutputQueueSize(pose_landmarks_out) > 0) {
    auto output_landmarks =
        mp_pipe->DirectlyGetNormalizedLandmarkList(pose_landmarks_out);
    std::cout << "why stucked here?\n";

    std::cout << mp_pipe->GetOutputQueueSize(face_landmarks_out) << ", "
              << mp_pipe->GetOutputQueueSize(pose_landmarks_out) << ", "
              << output_landmarks->landmark_size() << std::endl;

    if (output_landmarks != nullptr) {
      std::cout << "output landmarks not null?" << output_landmarks->landmark().size() << std::endl;
      for (auto a: output_landmarks->landmark()) {
        std::cout << a;
      }
      for (const mediapipe::NormalizedLandmark &lm :
           output_landmarks->landmark()) {
        printf("%f %f %f\n", lm.x(), lm.y(), lm.z());
        Landmark lm_{lm.x(), lm.y(), lm.z()};
        pose_landmarks.push_back(lm_);
      }
      std::cout << "pose landmarks one: " << pose_landmarks.size() << std::endl;
    }
  }
```

The `DirectlyGetNormalizedLandmarkList` is a wrapper of mediapipe parse packet API:

```c++
const mediapipe::NormalizedLandmarkList *
LibMPImpl::DirectlyGetNormalizedLandmarkList(const char *outputStream) {
  // directly return Packet as NormalizedLandmark, call it if you kown type!
  if (m_pollers.find(outputStream) == m_pollers.end()) {
    LOG(INFO) << "No poller found for output stream '" << outputStream
              << "'. Was it created using AddOutputStream beforehand?";
    return nullptr;
  }
  mediapipe::Packet outputPacket;
  if (!m_pollers.at(outputStream)->Next(&outputPacket)) {
    LOG(INFO) << "Poller for output stream '" << outputStream
              << "' has no next packet. Call m_graph.WaitUntilDone() to see "
                 "error (or destroy LibMP object). Are models available under "
                 "mediapipe/models and mediapipe/modules?";
    return nullptr;
  }
  // now you can have a NormalizedLandmarkList ptr
  return &outputPacket.Get<mediapipe::NormalizedLandmarkList>();
}

```

The model is holistic, and I need get face && pose landmarks.

But the output is very confusing:

![image](https://user-images.githubusercontent.com/21303438/215758781-8316e9fa-bc6c-4cbb-bb72-5741cbc2ddd9.png)

the face landmark get properly.

But pose landmark, I get 33 keypoints of output, but can not iter it to get every single landmark.

Why?

**Comment by andrechen** [comment]
the local variable, outputPacket, goes out of scope after DirectlyGetNormalizedLandmarkList() returns?

**Comment by jinfagang** [comment]
@andrechen if so, the `output_landmarks ` should be nullptr and there would be LOG msg out there, but is not.

**Comment by andrechen** [comment]
more likely, it's the dangling pointer, not nullptr. you can copy the code to where you call it to quickly verify it.

**Comment by jinfagang** [comment]
@andrechen it could be, but seems not my sitution, as you can see, I called the output_landmarks after, and it prints 33 which is the pose landmarks size.
if a dangling pointer or nullptr, it should coredumped. isnt it?

**Comment by kuaashish** [comment]
Hello @lucasjinreal,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
