### ISSUE TITLE
Docker build issue

### ISSUE THREAD

**Issue by PrinceP** [google/mediapipe#4043]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Xavier Ubuntu 18.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): Docker
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): NA
- Installed using virtualenv? pip? Conda? (if python): Docker
- [MediaPipe version](https://github.com/google/mediapipe/releases): [v0.8.11](https://github.com/google/mediapipe/releases/tag/v0.8.11)
- Bazel version: 5.2.0

**Describe the problem**:
Dockerfile is to be corrected. 

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

`
$ git clone -–depth 1 https://github.com/google/mediapipe.git
`
`
$ cd mediapipe
`
`
$ docker build --tag=mediapipe .
`
**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

Step 17/18 : RUN mkdir /bazel &&     wget --no-check-certificate -O /bazel/installer.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh" &&     wget --no-check-certificate -O  /bazel/LICENSE.txt "https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE" &&     chmod +x /bazel/installer.sh &&     /bazel/installer.sh  &&     rm -f /bazel/installer.sh
 ---> Running in 9aa582388107
--2023-01-31 10:01:08--  https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 49.44.79.236, 2405:200:1607:2820:41::36
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|49.44.79.236|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2405:200:1607:2820:41::36|:443... failed: Cannot assign requested address.
Retrying.

--2023-01-31 10:03:20--  (try: 2)  https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|49.44.79.236|:443...
failed: Connection timed out.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2405:200:1607:2820:41::36|:443... failed: Cannot assign requested address.
Retrying.

--2023-01-31 10:05:32--  (try: 3)  https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|49.44.79.236|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2405:200:1607:2820:41::36|:443... failed: Cannot assign requested address.
Retrying.

--2023-01-31 10:07:46--  (try: 4)  https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|49.44.79.236|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2405:200:1607:2820:41::36|:443... failed: Cannot assign requested address.
Retrying.

**Comment by ayushgdev** [comment]
Hello @PrinceP 
We are not able to reproduce the issue at our end on Ubuntu 18.04. The file is downloaded well. Please refer the screenshot attached. 
<img width="1006" alt="license" src="https://user-images.githubusercontent.com/118424249/216025684-9e0ac87d-b1d1-4906-986d-95f8cd8091ec.png">
But it does seem like you are on a network which is not allowing access to the bazel license file and that is why the network is throwing connection timed out. This can happen if you are on a closed network like in an organization. 
Can you please try to visit the link https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE via browser first?

**Comment by PrinceP** [comment]
Not able to access -> https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE

The network is working fine. No VPN is used.

**Comment by ayushgdev** [comment]
@PrinceP Since you are not able to access it from the browser as well and this file has public visibility, this is definitely a network/firewall issue. Please contact your network administrator for permission to access this file.
