### ISSUE TITLE
Can not get output video image out

### ISSUE THREAD

**Issue by jinfagang** [google/mediapipe#4045]
I using this to get vidoe as cv::Mat inside mediapipe:

```c++
cv::Mat LibMPImpl::DirectlyGetAsCvMat(const char *outputStream) {
  // we get output as mediapipe::ImageFrame
  if (m_pollers.find(outputStream) == m_pollers.end()) {
    LOG(INFO) << "No poller found for output stream '" << outputStream
              << "'. Was it created using AddOutputStream beforehand?";
    return cv::Mat{};
  }
  mediapipe::Packet outputPacket;
  if (!m_pollers.at(outputStream)->Next(&outputPacket)) {
    LOG(INFO) << "Poller for output stream '" << outputStream
              << "' has no next packet. Call m_graph.WaitUntilDone() to see "
                 "error (or destroy LibMP object). Are models available under "
                 "mediapipe/models and mediapipe/modules?";
    return cv::Mat{};
  }

  auto &output_frame = outputPacket.Get<mediapipe::ImageFrame>();
  cv::Mat mat_out = mediapipe::formats::MatView(&output_frame);
  cv::cvtColor(mat_out, mat_out, cv::COLOR_RGB2BGR);
  return mat_out;
}
```

the mat_out returned when I called it:

```
auto out_res = mp_pipe->DirectlyGetAsCvMat(output_frame_out);
    std::cout << out_res.rows << "x" << out_res.cols << std::endl;
```

and I got output of cv::Mat dimension.

But I can not write,cvtColor, or show it.

write with unknown exception:

imwrite_('a.png'): can't write data: unknown exception

what's the problem?

**Comment by itsarraj** [comment]
Hello sir ,
I am new to open source contribution.
I already know java , my tech stacks & tools includes C, C++ , Python , Java, JavaScript , HTML , CSS , SQL , Bootstrap, ReactJS, ExpressJS, NodeJS & Git . I need a little help from your side to contribute to these amazing projects.

**Comment by ayushgdev** [comment]
Hello @jinfagang 
Would you please elaborate on your query? Minimally, please mention on below points so that we can replicate the issue at our end.
1. Which Calculator are you trying to edit?
2. Which solution are you modifying ?
3. Any modifications to the graphs done?
4. The purpose of this modification so that we can suggest any alternative, if available already
