### ISSUE TITLE
add an aar file, the app will crash.

### ISSUE THREAD

**Issue by MakeMeCookie** [google/mediapipe#4046]
url : https://google.github.io/mediapipe/getting_started/android_archive_library.html
![Screenshot from 2023-02-01 15-57-20](https://user-images.githubusercontent.com/116155637/215973085-40139698-ac8d-42f6-9ac2-be24ca6490df.png)

I built handtracking on Android.
Referred to the above site to create an aar file. 
Above is the composition of the aar file I made.
When I add the aar file to the lib folder and start the app, the app crashes. 
Is there another way to compile the aar file?

**Comment by kuaashish** [comment]
Hi @MakeMeCookie, 
Would you let us know if you are following the target mentioned [here](https://google.github.io/mediapipe/solutions/hands.html#palmhand-detection-only-no-landmarks) to build and run the hands solution? Further we need information about the device which you using in the physical device or in android emulator?
However, We suggest that to fill the [template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=00-build-installation-issue.md) to understand more on issue.

**Comment by MakeMeCookie** [comment]
![Screenshot from 2023-02-01 16-11-38](https://user-images.githubusercontent.com/116155637/215975791-c1ad3905-b757-4e61-9e24-76ec7c44dee5.png)
Added .pbtxt and tflite files above. Do you have any missing AAR files?
I use Galaxy S9+, Android 10, and api30.

**Comment by kuaashish** [comment]
@MakeMeCookie,
Please share the complete error logs you are getting with respect to above error.

**Comment by liangzhengang** [comment]
i cant find the  tflite.
how to generate this tflite？
i use " bazel build -c opt mediapipe/graphs/xxxx:xxxx_binary_graph ”  it only generate  the binarypb file.please help me thx.............
