### ISSUE TITLE
Holistic pose landmark lag

### ISSUE THREAD

**Issue by jinfagang** [google/mediapipe#4047]
![image](https://user-images.githubusercontent.com/21303438/216007646-33881836-db39-4ad7-82c8-a1b067daf84d.png)

![image](https://user-images.githubusercontent.com/21303438/216007714-7a4f5d91-4de2-413d-a8f6-ce4c929581e3.png)

why there is a pose landmark lack in hoslistic?

what could be the reason?

**Comment by kuaashish** [comment]
Hi @jinfagang,
Would you please let us know complete details about the issue? We suggest to fill the[ template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abug&template=bug_issue_template.yaml) to understand the issue better and provide possible solution on the query raised. Thank you!
