### ISSUE TITLE
how to debug on Android Studio?

### ISSUE THREAD

**Issue by mapleyuan** [google/mediapipe#405]
I have change the params -opt to -dbg, but not working.

-c
dbg
--config=android_arm64

**Comment by eknight7** [comment]
Are you trying to debug Java code or C++ calculators?

**Comment by mapleyuan** [comment]
@eknight7 debug the C++ calculators.

**Comment by mgyong** [comment]
@mapleyuan   Use LOG(INFO) example here
https://github.com/google/mediapipe/blob/ae6be10afe59a6a99d8a68007784706ac98720dd/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc#L51
