### ISSUE TITLE
keypresses causing Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by econokeith** [google/mediapipe#4053]
This issue only pertains to keypresses after importing mediapipe. All of the Solutions I've tried seem to work fine. 

**System information** 
- Ubuntu 20.04.3 LTS
- Python 3.8.10
- mediapipe 0.9.1.0
- opencv-python 4.6.0

**Describe the expected behavior:**
If I don't import mediapipe: 
```
import cv2
import time
#import mediapipe

capture = cv2.VideoCapture(0)

while True:
    success, frame = capture.read()
    if success is False:
        continue

    time.sleep(1/30)
    cv2.imshow("name", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        print('you hit q')
        break

print('finished!')
```
then everything works as expected and hitting 'q' causes: 
```
you hit 'q'
finished!
Process finished with exit code 0
```

**Describe the current behavior:**
However, if I import mediapipe, then any keypress causes a SIGSEGV error:
```
import cv2
import time
import mediapipe

capture = cv2.VideoCapture(0)

while True:
    success, frame = capture.read()
    if success is False:
        continue

    time.sleep(1/30)
    cv2.imshow("name", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        print('you hit q')
        break

print('finished!')
```
output:
```
Segmentation fault (core dumped)
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
where printing and/or any cleanup don't happen. Also, using the faulthandler, the error is occuring with the waitKey function

**Comment by ayushgdev** [comment]
Hello @econokeith 
Thanks for bringing out this issue. Please allow us sometime to reproduce the issue at our end on similar config VM and act upon the findings.

**Comment by econokeith** [comment]
for what it's worth. I tried this on my M1 macbook pro and the error doesn't occur.

**Comment by ayushgdev** [comment]
Agreed on the Macbook M1 Pro observation @econokeith. We also tried on it and it is running smoothly. We are looking into this issue. However, we are having trouble procuring a Ubuntu 20.03 VM since any cloud machine don't have access to Webcam so naturally, MediaPipe is throwing error for it. 
Again reiterating, please allow us sometime to reproduce the issue at our end.

**Comment by econokeith** [comment]
If it helps, I was able to reproduce the error with the following code and no cams connected to my machine:

```
import cv2
import time
#import mediapipe
import numpy as np

frame = np.zeros((300, 300, 3), dtype='uint8')
while True:
    time.sleep(1/30)
    cv2.imshow("frame", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        print("you hit 'q'")
        break

print('finished!')
```
the same behavior, where cv2.waitKey crashes the process, when I import mediapipe

**Comment by kuaashish** [comment]
Hello @econokeith,

We have rolled out the newer version 0.10.1 as noted in the [release page](https://github.com/google/mediapipe/releases/tag/v0.10.1). Please reproduce the issue in newer version and revert back if encounter the similar behaviour. Thank you!
