### ISSUE TITLE
//mediapipe/framework/port:status dep pulls in unneeded org_tensorflow package

### ISSUE THREAD

**Issue by kikiotsuka** [google/mediapipe#4054]
I'm adding a dependency on //mediapipe/framework/port:status so I can utilize MP_RETURN_IF_ERROR and MP_ASSIGN_OR_RETURN but it also pulls in org_tensorflow which seems unnecessary and I was hoping if this could get refactored out.

**Comment by kuaashish** [comment]
Hi @kikiotsuka,
Could you please elaborate your query with complete details and steps to reproduce the issue from our end. Thank you!

**Comment by kikiotsuka** [comment]
In order to use the status macros MP_RETURN_IF_ERROR for my copybara script I added "@mediapipe//mediapipe/framework/port:status" as a dependency which calls into framework/deps build file which runs load("//mediapipe/framework/port:build_config.bzl", "mediapipe_proto_library"), and then in framework/port/build_config.bzl it runs load("//mediapipe/framework/tool:mediapipe_graph.bzl", "mediapipe_options_library") which lastly loads tensorflow as a dependency

**Comment by kuaashish** [comment]
Hi @kikiotsuka,
Would you please let us know the exact steps to reproduce the issue?

**Comment by kikiotsuka** [comment]
I have a build file that adds a dependency on `//mediapipe/framework/port:status` to use MP_RETURN_IF_ERROR and I'm having to add the other tensorflow dependencies as well for it to build. The tensorflow dependency comes from mediapipe_graph.bzl but I think it could be separated out

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,
Could you please look into this issue? Thank you!

**Comment by schmidt-sebastian** [comment]
@kikiotsuka Thanks for this request. Unfortunately, I don't think this is something we can prioritize right now. We would be willing to take a contribution if you can make this work. Thanks!
