### ISSUE TITLE
[Android] In Mediapipe Hands: java.lang.RuntimeException: glClear: GL error: 0x501

### ISSUE THREAD

**Issue by pritam-ghosh-dev** [google/mediapipe#4055]
<em>I'm trying to render a Bitmap at the wrist coordinate of hand. So I'm following this [solution](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions/hands/src/main/java/com/google/mediapipe/examples/hands). In ```HandResultGlRenderer.java``` I'm receiving the HandsResult in ```renderResult(HandsResult result, float[] projectionMatrix)``` function.  <em>
After getting the wrist coordinate I'm calling another function ```drawBitmap(landmark.getX(), landmark.getY(),bitmap)```
Here's how drawBitmap() looks like:
```
  private void drawBitmap(float x, float y, Bitmap bitmap) {
    int textureId = loadTexture(bitmap);
    GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, textureId);

    // Define the texture coordinates for the bitmap.
    float[] textureCoordinates = {
            0.0f, 1.0f,
            1.0f, 1.0f,
            0.0f, 0.0f,
            1.0f, 0.0f
    };

    // Define the vertex coordinates for the bitmap.
    float[] vertices = {
            x - (bitmap.getWidth() / 2.0f), y - (bitmap.getHeight() / 2.0f), 0.0f,
            x + (bitmap.getWidth() / 2.0f), y - (bitmap.getHeight() / 2.0f), 0.0f,
            x - (bitmap.getWidth() / 2.0f), y + (bitmap.getHeight() / 2.0f), 0.0f,
            x + (bitmap.getWidth() / 2.0f), y + (bitmap.getHeight() / 2.0f), 0.0f
    };

    // Enable vertex array and texture array.
    GLES30.glEnableVertexAttribArray(positionHandle);
    GLES30.glEnableVertexAttribArray(textureCoordinateHandle);

    // Update the vertex buffer and texture coordinate buffer.
    FloatBuffer vertexBuffer = ByteBuffer.allocateDirect(vertices.length*4)
            .order(ByteOrder.nativeOrder())
            .asFloatBuffer()
            .put(vertices);
    vertexBuffer.position(0);
    FloatBuffer textureCoordinateBuffer = ByteBuffer.allocateDirect(textureCoordinates.length*4)
            .order(ByteOrder.nativeOrder())
            .asFloatBuffer()
            .put(textureCoordinates);
    textureCoordinateBuffer.position(0);


    // Set the vertex and texture coordinate buffer for the shaders.
    GLES30.glEnableVertexAttribArray(positionHandle);
    GLES30.glVertexAttribPointer(positionHandle, 3, GLES30.GL_FLOAT, false, 0, vertexBuffer);

    GLES30.glEnableVertexAttribArray(textureCoordinateHandle);
    GLES30.glVertexAttribPointer(textureCoordinateHandle, 2, GLES30.GL_FLOAT, false, 0, textureCoordinateBuffer);


    // Draw the bitmap.
    GLES30.glDrawArrays(GLES30.GL_TRIANGLE_STRIP, 0, 4);

    // Disable vertex array and texture array.
    GLES30.glDisableVertexAttribArray(positionHandle);
    GLES30.glDisableVertexAttribArray(textureCoordinateHandle);

  }
```

And here is how ```loadTexture()``` looks like:
```
 private int loadTexture(Bitmap bitmap) {
    // Generate a new texture ID
    int[] textureIds = new int[1];
    GLES30.glGenTextures(1, textureIds, 0);

    // Bind the texture
    GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, textureIds[0]);

    // Set the texture parameters
    GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D, GLES30.GL_TEXTURE_MIN_FILTER, GLES30.GL_LINEAR);
    GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D, GLES30.GL_TEXTURE_MAG_FILTER, GLES30.GL_LINEAR);
    GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D, GLES30.GL_TEXTURE_WRAP_S, GLES30.GL_CLAMP_TO_EDGE);
    GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D, GLES30.GL_TEXTURE_WRAP_T, GLES30.GL_CLAMP_TO_EDGE);

    // Load the bitmap into the texture
    GLUtils.texImage2D(GLES30.GL_TEXTURE_2D, 0, bitmap, 0);

    // Unbind the texture
    GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, 0);

    // Return the texture ID
    return textureIds[0];
  }
```
But when I'm running the app, the camera is opening as usual, but I when bring my hand near the camera, the app crashes with the following error:
**Error information** 
```
FATAL EXCEPTION: GLThread 9071
         Process: com.google.mediapipe.apps.hands, PID: 28664
         java.lang.RuntimeException: glClear: GL error: 0x501
         at com.google.mediapipe.glutil.ShaderUtil.checkGlError(ShaderUtil.java:175)
         at com.google.mediapipe.components.GlSurfaceViewRenderer.renderFrame(GlSurfaceViewRenderer.java:101)
         at com.google.mediapipe.solutioncore.SolutionGlSurfaceViewRenderer.onDrawFrame(SolutionGlSurfaceViewRenderer.java:84)
         at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1605)
         at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1284)
```
It's showing that the error is thrown from ```ShaderUtil.java```, I couldn't debug the issue.

**System information** 
I'm testing on my OnePlus9R
- Android Version: 13
- API Level: 33
- OpenGL ES: 3.2
- GPU Vendor: Qualcomm
- GPU Renderer: Adreno(TM) 650 @ 670 MHz
- Solution: Hands
- Programming Language and version ( e.g. C++, Python, Java):

**Comment by pritam-ghosh-dev** [comment]
@ayushgdev kindly let me know about any update on this issue, I've been stuck with this issue for weeks

**Comment by ayushgdev** [comment]
Hello @pritam-ghosh-dev 
We are working on it however, GL errors are difficult to debug so it is taking more than median time. Please allow us sometime to debug the issue.

**Comment by pritam-ghosh-dev** [comment]
Thanks for looking over this issue

**Comment by ayushgdev** [comment]
@pritam-ghosh-dev Can you please advice where/how the variable `textureCoordinateHandle` is defined?

**Comment by pritam-ghosh-dev** [comment]
@ayushgdev here is my ```setUp()``` method:

```  
public void setupRendering() {
    program = GLES30.glCreateProgram();
    int vertexShader = loadShader(GLES30.GL_VERTEX_SHADER, VERTEX_SHADER);
    int fragmentShader = loadShader(GLES30.GL_FRAGMENT_SHADER, FRAGMENT_SHADER);
    GLES30.glAttachShader(program, vertexShader);
    GLES30.glAttachShader(program, fragmentShader);
    GLES30.glLinkProgram(program);
    textureCoordinateHandle = GLES30.glGetAttribLocation(program, "inputTextureCoordinate");
    samplerHandle = GLES30.glGetUniformLocation(program, "sampler");
    positionHandle = GLES30.glGetAttribLocation(program, "vPosition");
    projectionMatrixHandle = GLES30.glGetUniformLocation(program, "uProjectionMatrix");
    colorHandle = GLES30.glGetUniformLocation(program, "uColor");
  }
```

**Comment by ayushgdev** [comment]
Thanks for this gist @pritam-ghosh-dev . Just initial thoughts, this seems like the glThread is getting spun up but after finishing the job, it is not able to return the results back to the main worker. We will get back to you shortly.

**Comment by pritam-ghosh-dev** [comment]
okay thanks

**Comment by pritam-ghosh-dev** [comment]
hi @ayushgdev any update on the issue?

**Comment by ayushgdev** [comment]
Hello @pritam-ghosh-dev 
This issue is coming from `textureCoordinateHandle` variable. 
```
textureCoordinateHandle = GLES20.glGetAttribLocation(program, "inputTextureCoordinate");
```
The line above in `setupRendering` is returning -1. This means that the `inputTextureCoordinate` is not an active attribute in the program object, and thus it is not required. 
To fix the error, you can simply put a check to use the `textureCoordinateHandle` only if it has a value > 0 at all references, like below:
```
if(textureCoordinateHandle > 0)
      GLES30.glEnableVertexAttribArray(textureCoordinateHandle);
...
...
if(textureCoordinateHandle > 0){
      GLES30.glEnableVertexAttribArray(textureCoordinateHandle);
      GLES30.glVertexAttribPointer(textureCoordinateHandle, 2, GLES30.GL_FLOAT, false, 0, textureCoordinateBuffer);
    }
```

**Comment by pritam-ghosh-dev** [comment]
hi @ayushgdev 
got your point, made the necessary changes. But still getting the same error.

![Screenshot (1414)](https://user-images.githubusercontent.com/120572141/220048691-bb616e2f-b6d6-4382-b296-79084f467dfc.png)

**Comment by pritam-ghosh-dev** [comment]
Commenting coz, stat:awaiting response tag wasn't removed

**Comment by ayushgdev** [comment]
@pritam-ghosh-dev Have you added condition before this line as well? 
```
GLES30.glEnableVertexAttribArray(textureCoordinateHandle);
```
There are 3 places in total where it needs to be added. I see two changes in the screenshot.

**Comment by pritam-ghosh-dev** [comment]
Yeah sorry, I missed that. 
After I made the changes the app isn't crashing, but whenever a wrist is detected, the camera texture is becoming black. Maybe it's because no texture is assigned to the renderer. 
I have limited knowledge of OpenGl, any idea on how to fix the camera getting black issue? @ayushgdev

**Comment by ayushgdev** [comment]
Always happy to help. However, this issue is different than the original issue and the original errors have been resolved. To keep the context of the issue as relevant to the original issue as possible, may I suggest you close this issue and open another one?
This helps community and us to search through the issues in concise manner.

**Comment by pritam-ghosh-dev** [comment]
Thanks for the support, I have raised another issue with this continuation
