### ISSUE TITLE
Building with bazel:  name 'json' is not defined

### ISSUE THREAD

**Issue by thegabriele97** [google/mediapipe#4056]
**System information** 
- OS Platform and Distribution: PYNQ - Linux Ubuntu 22.04 aarch64
- Compiler version: gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)
- Programming Language and version: Python 3.10.4
- Bazel version: bazel 3.7.2

Hi!
I am trying to build the wheel for aarch64 because it is not provided in the PyPi repo. To do that, I cloned the mediapipe repository and lanched the build step with 

```sh
python3 setup.py gen_protos && python3 setup.py bdist_wheel  
```

The problem is that, after a few minutes of downloading/extracting stuff, bazel outputs a series of errors:

> 
> ERROR: /home/xilinx/.cache/bazel/_bazel_xilinx/dbcb6bd62247f0988afcb64139fd29a7/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:483:28: name 'json' is not defined
> ERROR: /home/xilinx/.cache/bazel/_bazel_xilinx/dbcb6bd62247f0988afcb64139fd29a7/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:594:20: name 'json' is not defined
> ERROR: /home/xilinx/.cache/bazel/_bazel_xilinx/dbcb6bd62247f0988afcb64139fd29a7/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:625:19: name 'json' is not defined
> ERROR: error loading package '': in /home/xilinx/.cache/bazel/_bazel_xilinx/dbcb6bd62247f0988afcb64139fd29a7/external/build_bazel_rules_nodejs/index.bzl: Extension 'internal/npm_install/npm_install.bzl' has errors

Why it happens and how can I solve it? Thank you!

**Comment by flySheldon** [comment]
I also encountered this problem when compiling under the desktop environment. Can I ask you how to solve it?

**Comment by kuaashish** [comment]
@flySheldon,
Could you please raise a new fresh issue with the [template ](https://github.com/google/mediapipe/issues/new/choose) and complete steps to reproduce the issue from our end? Thank you!

**Comment by thegabriele97** [comment]
> I also encountered this problem when compiling under the desktop environment. Can I ask you how to solve it?

I used bazelisk instead of bazel. In this way, the mediapipe build process can use the bazel version it wishes

**Comment by flySheldon** [comment]
> > I also encountered this problem when compiling under the desktop environment. Can I ask you how to solve it?
> 
> I used bazelisk instead of bazel. In this way, the mediapipe build process can use the bazel version it wishes
I solved the problem with your method, thank you

**Comment by flySheldon** [comment]
> >> I also encountered this problem when compiling under the desktop environment. Can I ask you how to solve it?
> 
> >I used bazelisk instead of bazel. In this way, the mediapipe build process can use the bazel version it wishes
>I solved the problem with your method, thank you

**Comment by flySheldon** [comment]
@thegabriele97 I solved the problem with your method, thank you
