### ISSUE TITLE
Segmentation mask with smoothing

### ISSUE THREAD

**Issue by danrossi** [google/mediapipe#4058]
This has been asked before but the response doesn't mention how to add SegmentationSmoothingCalculator back into the segmentation graph files. Should there be mask smoothing added by default ? 

How does this snippet get added into the segmentation file used. Does it need a special build or configuration via the javascript api ? And if it needs a special build can this be chosen instead of the default ?

https://github.com/google/mediapipe/issues/2282#issuecomment-907546309
I believe this one is used on windows desktop not the gpu for some reason.

https://github.com/google/mediapipe/blob/master/mediapipe/graphs/selfie_segmentation/selfie_segmentation_cpu.pbtxt
https://github.com/google/mediapipe/blob/master/mediapipe/modules/selfie_segmentation/selfie_segmentation_cpu.pbtxt

Or does one need to do smoothing filtering of the mask via webgl shaders on returned results ? The edges are blocky on results.

**Comment by ayushgdev** [comment]
Hi @danrossi In the Javascript solutions, one cannot change the graphs since they are precompiled and provided in the wasm files via CDN. So smoothing task, unfortunately has to be on the end user via WebGL. 
Just a note, we are trying to have good improvements in the upcoming versions. So please allow us sometime to prioritise this in our roadmap. Although we cannot provide any timeline yet.

**Comment by danrossi** [comment]
I have a webgl rendering solution of the ImageBitmap to textures, ive upgraded it from the bodypix solution. But I've been having a hard time with performance testing in chrome. a 1080 HD camera video as input increases cpu and uses less gpu. If I restrict the webgl viewport to 720p its less cpu. Not as bad as canvas software rendering which is 10% more cpu. Firefox has lower cpu and more gpu usage. 

With no segmentation and no texture upload just drawArrays in a 1080p viewport chrome uses more cpu than gpu. I think there is a bug there I may need to report it. Its ok in Firefox. I have an Nvidia card on windows. 

I think I might have to see if a downscaled video input in a buffer canvas helps. 

I will upload a test showing mixing the video with the mask and a background image. And apparant smoothing of the mask. 

May I ask if I am using webgl, is there a way to access the buffers to use to print as textures. I noticed the input video is being printed to a webgl texture for input to the wasm, so it means I may not have to reprint it after to mix with the mask. If the mask is also in webgl I may not need to reprint that also. 

Sorry if this is off topic but its related.

**Comment by danrossi** [comment]
here is the tests. For some reason in this migrated code the cpu is lower when forcing max resolution of the camera in chrome. Its hard to debug what my problem is. But this shows webgl render. If I can somehow reuse the webgl textures for rendering the mask that would be of use. 

https://codepen.io/danrossi/pen/wvEBREv
https://electroteque.org/dev/mediapipe/public.html

**Comment by ayushgdev** [comment]
Hello @danrossi 
Thanks for this detailed analysis. Please allow us sometime to understand the cause of the issue and get back to you.

**Comment by danrossi** [comment]
I think the blur shader integration is working on the mask but I see there is a calculator for that already not built into the selfie segmentation. It would be good to know how to reuse the video texture uploaded to the wasm. There is webgl video texture rendering happening internally that is uploaded to wasm. And I have to do it again when applying the mask texture. The high cpu usage is caused by a software encoding of the canvas stream it seems and not the mediapipe solution or webgl render. So restricting it to 720p is the only way.

**Comment by ayushgdev** [comment]
@tyrmullen Can you please check this issue?

**Comment by tyrmullen** [comment]
The old selfie segmentation Solution has been deprecated in favor of the new [MediaPipe Segmentation Solution](https://developers.google.com/mediapipe/solutions/vision/image_segmenter), so we will probably not be making upgrades to the old version at this point in time.

However, the new version already allows for grabbing the WebGLTexture directly, which should support users in need of highest performance.  See issue #4360 for more details.

Specifically, I think this should cut out the final canvas-->canvas or canvas-->ImageBitmap copy from your current pipeline, although I should note that captureStream likely has some nontrivial overhead itself, (but using that may be necessary for your use case).

**Comment by danrossi** [comment]
Thanks very much that is interesting and I will take a look. Currently I use a WebGL shader to mix the mask with the video  and a background. And if share screening the screen video is the background. It currently requires smoothing of the mask in the shader however. Is the mask now pre-smoothed then ? 

So the api has changed yet again. Its not expecting cpu draw of video with a buffer returned like previously. But still doing stuff in 2d canvas.  But with webgl I will still need to use the buffer to draw to a text to mix all the elements. As they don't come premixed. Is that 2d code smoothing the mask ? 

I will try and upgrade and run performance tests. So the new import is
```
https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.2
```
I have made a ticket about cpu encoding of captureStream which at 1080p consumes alot of cpu it has to be restricted to 720p. I'm not sure where it's at.

```
 void main(void) {
            
            vec4 maskTex = texture(mask, v_texCoord); 
            vec4 frameTex = texture(frame, v_texCoord);
            vec4 bgTex = texture(background, v_texCoord);
            vec3 frameColor = frameTex.rgb;
            vec3 backgroundColor = bgTex.rgb;
            float maskVal = 0.0;
            float u_lightWrapping = 0.1;
  
            vec2 u_coverage = vec2(0.1,0.5);
  
            maskVal = maskSmoothing(frameColor);
  
            frameColor = lightWrapping(frameColor, backgroundColor, maskVal, u_coverage);
         
  
            outColor = mix(bgTex, vec4(frameColor, 1.0), maskVal);
          }
   ```

**Comment by danrossi** [comment]
I see in the demo it's still expecting a cpu draw of the video and then mask applied after. A premixed output would be nice or at least the mask pre-smoothed using one of the available calculators. There is confusing documentation which running mode to use with a MediaStream input. Either VIDEO or LIVE_STREAM.

**Comment by danrossi** [comment]
I see softmax is applied to the mask now so I can close this ticket. but the cpu draw example with 720p input consumes alot of cpu and gpu. With webgl it's low cpu but 17% gpu. With selfie segmentation and webgl mix render its 4% cpu and 7% gpu. So this new method is higher resources than the old one. 

I see a webgltexture for the mask is returned however how can I used that or the webgl context returned to mix a background and video ? I'm not getting any mix blending using alpha channel with this new method using something like this with webgl. Like I have with selfie segmentation. The background texture is set and doesn't need to be re-rendered. the 2D option is too high resources and not useful. 


```
 gl.activeTexture(gl.TEXTURE2);
      gl.texImage2D(
        gl.TEXTURE_2D,        // target 
        0,                    // level
        gl.RGBA,             // internalformat
        gl.RGBA,             // format, "must be the same as internalformat"
        gl.UNSIGNED_BYTE,     // type of data below
            results.categoryMask.canvas

      );

      gl.activeTexture(gl.TEXTURE1);
      gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGB, gl.RGB, gl.UNSIGNED_BYTE, localVideo);

   
   
      gl.drawArrays(gl.TRIANGLE_FAN, 0, 4);
```

With a shader like 

```
#version 300 es
        #ifdef GL_FRAGMENT_PRECISION_HIGH
          precision highp float;
        #else
          precision mediump float;
        #endif
    
        uniform sampler2D background;
        uniform sampler2D frame;
        uniform sampler2D mask;
    
        in vec2 v_texCoord;
    
        out vec4 outColor;


        void main(void) {
          
          vec4 maskTex = texture(mask, v_texCoord); 
          vec4 frameTex = texture(frame, v_texCoord);
          vec4 bgTex = texture(background, v_texCoord);
          vec3 frameColor = frameTex.rgb;
          vec3 backgroundColor = bgTex.rgb;
        

       
          //outColor = maskTex;
          outColor = mix(bgTex, vec4(frameColor, 1.0), maskTex.a);
        
        ```

**Comment by danrossi** [comment]
My issue was the test file using a large canvas size for the stream capture which is cpu encoding. I will make another ticket how to apply the webgl texture returned using webgl for rendering to prevent the cpu draw of the video. The model is now using softmax post processing for smoothing.

**Comment by danrossi** [comment]
The edges seem less accurate compared to selfiesegmentation. The mask is blank when rendering it alone for some reason.
