### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':

### ISSUE THREAD

**Issue by jinfagang** [google/mediapipe#4059]
```
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
```

**Comment by jinfagang** [comment]
For anyone already did these 2 steps ,but still get above error:

1. you have set python path though: `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D:\\anaconda\\envs\\py310\\python.exe" mediapipe/examples/desktop/helloworld.dll`
2. you have installed numpy to your python

<img width="594" alt="image" src="https://user-images.githubusercontent.com/21303438/216752260-31b34b1b-f9e4-438f-95af-9995faa685fe.png">

You can comment out these 2 methods, _check_python_lib and bin. Then you can pass the error.

I didn't know why it got when check, but obviously google's people have too much time on written so much complicated code while they can do it 1000x easier.

And of course users get 10000x harder using their source codes.

**Comment by kuaashish** [comment]
Hi @jinfagang,
Could you please elaborate your query with complete details, error logs and steps to reproduce the issue from our end.
