### ISSUE TITLE
performance tool

### ISSUE THREAD

**Issue by jiqimaogou** [google/mediapipe#406]
https://mediapipe.readthedocs.io/en/latest/measure_performance.html

can you open source the performance tool?

**Comment by mgyong** [comment]
We will be launching features for performance measurement in Visualizer (https://viz.mediapipe.viz). We do not have plans to open source the performance tool.

**Comment by jiqimaogou** [comment]
![image](https://user-images.githubusercontent.com/1407040/74209153-8317de00-4cc1-11ea-9b11-61054d32b63a.png)
I can see the icon,

**Comment by mgyong** [comment]
@jiqimaogou  We have released [experimental profiling and tracing](https://github.com/google/mediapipe/blob/master/mediapipe/docs/tracer.md) at [viz.mediapipe.dev](https://viz.mediapipe.dev) with [v0.7.5](https://github.com/google/mediapipe/releases/tag/v0.7.5)
Please check it out and give us feedback
