### ISSUE TITLE
Build app using Bazel or Gradle

### ISSUE THREAD

**Issue by H1eu69** [google/mediapipe#4061]
I want to develop an android app using mediapipe. As i follow tutorial there is an instruction about build app using bazel but can i build without bazel but gradle?. If yes, how?

**Comment by kuaashish** [comment]
@H1eu69,
Unfortunately, This part is not available for the all solution available here. As mentioned [here](https://google.github.io/mediapipe/getting_started/android_solutions.html#mediapipe-android-solutions), Building app Using the Gradle is only available build & tested for the facemesh, facedetection and hands solutions.

**Comment by H1eu69** [comment]
So i have to follow tutorial mentioned [here](https://google.github.io/mediapipe/getting_started/android_archive_library.html) for the rest of solutions?

**Comment by kuaashish** [comment]
@H1eu69,
As mentioned [here](https://google.github.io/mediapipe/solutions/solutions.html#solutions), You can build/run rest of others solution that are available using the **Android AAR** and need to select the **target** as guided [here](https://google.github.io/mediapipe/solutions/hands.html#main-example)(**Android Target**) as example of build app using for **hands** solution.

**Comment by kuaashish** [comment]
@H1eu69,
Please go through the [above](https://github.com/google/mediapipe/issues/4061#issuecomment-1420200397) comment and feel free to close this is no longer issue from your end. Thank you!
