### ISSUE TITLE
Camera_Utils does not have camera.stop() anymore in latest version 0.3.1675465971

### ISSUE THREAD

**Issue by FabianOrduna** [google/mediapipe#4064]
Hello!

In the past I looked for a solution to stop a camera. I found on this thread https://github.com/google/mediapipe/issues/1606 that camera.stop() was a function that help to achive this beaviour.

I was able to use it until 0.3.1640029074 version.

However, with latest version I'm not able to use it and get the following message:

**Uncaught TypeError: camera.stop is not a function
    at endMediapipe
    at HTMLButtonElement.onclick**

Please, take a look since this function is really helpful

**Comment by tyrmullen** [comment]
New version 0.3.1675466862 should bring back the `.stop()` call.  Please let us know if there are any other issues with it!

**Comment by FabianOrduna** [comment]
Thanks for the quick response! I'm seeing it working with latest version
