### ISSUE TITLE
how to reduce cpu usage of the hand tracking solution(gpu version) for Snapdragon 845

### ISSUE THREAD

**Issue by ppphoebeee** [google/mediapipe#4065]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe):no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 11
- [MediaPipe version](https://github.com/google/mediapipe/releases):the newest version
- Bazel version:6.0.0
- Solution (e.g. FaceMesh, Pose, Holistic):hands
- Programming Language and version ( e.g. C++, Python, Java):java

**Describe the expected behavior:I used gpu version of hand tracking but the cpu usage is very high nearly 80%.I want to know which function of the hand tracking still use cpu under this version? If anybody understand the reasons,please answer the problem,thank you!

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment]
Hi @ppphoebeee,
Would you let us know the observation made in the both of cases GPU vs CPU usage if can share the if any code changes made or screenshot of console that will be more helpful for us to provide the possible resolution on the issue. Thank you!
