### ISSUE TITLE
Results interface is missing ea property

### ISSUE THREAD

**Issue by nohr** [google/mediapipe#4068]
The "Results" interface for Holistic is missing the "ea" property and its corresponding type. When I log the event from the onResult method, I see all of the properties defined in index.d.ts including ea, which i need for 3D pose landmarks.

**System information** (Please provide as much relevant information as possible)
- MacOS 13 Macbook M1 Pro
- [MediaPipe version](https://github.com/google/mediapipe/releases): ^0.5.1675471629
- Solution: Holistic
- Programming Language and version: Typescript 4.9.4

**Describe the expected behavior:**
Expecting to see:
```typescript
export interface Results {
  poseLandmarks: NormalizedLandmarkList;
  faceLandmarks: NormalizedLandmarkList;
  multiFaceGeometry: FaceGeometry[];
  rightHandLandmarks: NormalizedLandmarkList;
  leftHandLandmarks: NormalizedLandmarkList;
  segmentationMask: GpuBuffer;
  image: GpuBuffer;
  ea: // Interface ;
}
```

**Standalone code you may have used to try to get what you need :**
```typescript
import { Holistic, Results } from "@mediapipe/holistic";

function onResults(results: Results){
   const { ea } = results; // Throws `Property 'ea' does not exist on type 'Results'.ts(2339)`
}

new Holistic({...}).onResults(onResults);
```

**Comment by ayushgdev** [comment]
Hello @nohr
Thanks for raising this request. I understand this request is with respect to poseWorldLandmarks property, as given [here](https://github.com/google/mediapipe/issues/3155#issuecomment-1064909625). Thanks for bringing this back up to our attention. We will keep this(poseWorldLandmark property) in queue to include in the type definition file and rename in javascript file as well in next release.

**Comment by tyrmullen** [comment]
`ea` has never been a property we've exposed or supported, and so should not exist in any of our `index.d.ts` files.  From what I can tell, we've never officially supported `poseWorldLandmarks` for the `Holistic` Solution, but users were able to discover a way to grab that information from the Results structure for that last version of the API.  The obfuscated JavaScript property happened to be called `ea` for that version.  So you'll either need to try to do the same for the latest version of Holistic, or else you can continue to use `ea` and just use the previous version of Holistic (@0.5.1635989137, specifically).
