### ISSUE TITLE
pip install mediapipe with Python 3.8

### ISSUE THREAD

**Issue by Sanimag** [google/mediapipe#4069]
Hello, same issue
![image](https://user-images.githubusercontent.com/56559719/217215931-262025bc-35ab-43f4-b2c9-61f2913a10d8.png)
![image](https://user-images.githubusercontent.com/56559719/217216015-66d5dc7b-8fc6-4d54-8594-eed285e31f8b.png)
![image](https://user-images.githubusercontent.com/56559719/217216079-7a27db8b-20fb-40c5-92e0-891970ab68e1.png)
![image](https://user-images.githubusercontent.com/56559719/217216181-01aab10e-28c6-44e0-9b18-d052adaa7dda.png)
![image](https://user-images.githubusercontent.com/56559719/217216236-e1755dfb-a459-4fa3-ac27-f7ae62af2f6c.png)

_Originally posted by @Sanimag in https://github.com/google/mediapipe/issues/1325#issuecomment-1420520987_

**Comment by kuaashish** [comment]
Hi @Sanimag,
Would you please let us know the complete details about the issue such as operating system you are using, steps followed to understand the issue better from our end? Thank you!

**Comment by Sanimag** [comment]
I ran that on my laptop with Windows 22H2 19045.2486. About Python and pip version I mentioned above and it all satisfies to requirements. The error has still remained even after I upgraded my pip.

**Comment by kuaashish** [comment]
@Sanimag,
Could you let us know the complete steps followed to reproduce the issue from our end? Thank you!

**Comment by Sanimag** [comment]
I wanted to create computer vision application that includes libraries such as cv2 and mediapipe.
Firstly, I installed cv2 by typing "pip install opencv-python", it was successfull 
Then wanted to install mediapipe by "pip install mediapipe" and error occued!
And after I upgraded my pip to last version, thought maybe it was a reason, but not. 
So i opened the issue

**Comment by Bhawna-Sharma-9903** [comment]
please try 
pip install --user mediapipe==0.8.7.1(which ever version you wish for). 
i hope this helps.

**Comment by Sanimag** [comment]
> please try pip install --user mediapipe==0.8.7.1(which ever version you wish for). i hope this helps.

Thanks for suggestion, but I'd tried it and it still doesn't working

**Comment by kuaashish** [comment]
@Sanimag,
Please excuse delayed response, Are you able to resolve the error or still looking a resolution from our end? thank you!
