### ISSUE TITLE
How to create  .so lib file for using Solutions Java Source.

### ISSUE THREAD

**Issue by wh173d3v11** [google/mediapipe#4071]
Hi, I'm trying to use solutions Java source in my project directly, which is [here](https://github.com/google/mediapipe/tree/master/mediapipe/java/com/google/mediapipe).

How can i create .so file for this Java Source. ??

* Tried creating AAR and using that .so lib files ,but **Not Worked**.

**Comment by kuaashish** [comment]
Hi @wh173d3v11,
Could you please let us know if this [#3531(comment)](https://github.com/google/mediapipe/issues/3531#issuecomment-1190007066) resolves the issue? Thank you!

**Comment by kuaashish** [comment]
Hi @wh173d3v11,

Could you please confirm if you still require assistance with this matter? If so, we would like to inform you that AAR solutions for app development are no longer under maintenance, and we anticipate that the reported issue will not be resolved.

We recommend exploring our latest Task APIs, which represent an enhanced iteration of our legacy Solutions. You can find more details [here](https://developers.google.com/mediapipe/solutions/guide#legacy). While it should be possible to import all MediaPipe solutions into a project using our new method for building Android Apps, we have not tested it yet.

Additionally, you may refer to the corresponding [documentation](https://developers.google.com/mediapipe/solutions) for the All new Task APIs and implementation instructions for Android [here](https://developers.google.com/mediapipe/solutions/setup_android). Should you encounter any issues during implementation, please feel free to report them to us.

Thank you!!
