### ISSUE TITLE
An error occurred during the fetch of repository 'rules_foreign_cc'

### ISSUE THREAD

**Issue by pareekshiv07** [google/mediapipe#4073]
### OS Platform and Distribution

macos

### Programming Language and version

java

### Bazel version

bazel 5.2.0

### Android SDK and NDK versions (if android)

pixel 5 api 30
android 11.0

### Android AAR (if android)

None

### Describe the problem

```shell
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/hairsegmentationgpu:hairsegmentationgpu
```

### Complete Logs

```shell
An error occurred during the fetch of repository 'rules_foreign_cc':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_xxx/e16bf2cb4a010c61f2f7c06851ef75fc/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_foreign_cc/archive/0.1.0.zip] to /private/var/tmp/_bazel_xxx/e16bf2cb4a010c61f2f7c06851ef75fc/external/rules_foreign_cc/temp6405001367640443065/0.1.0.zip: Connection reset
```

**Comment by ayushgdev** [comment]
Helo @pareekshiv07 
Can you please let us know if you have followed the [Android setup guide](https://google.github.io/mediapipe/getting_started/android.html#building-android-example-apps-with-bazel) after the Installation guide for your [Mac OS](https://google.github.io/mediapipe/getting_started/install.html#installing-on-macos)?
Specifically, the WORKSPACE file should be updated with the android_ndk_repository() and android_sdk_repository() rules.
Also, refer to [this comment](https://github.com/google/mediapipe/issues/3719#issuecomment-1345868251) on how to update the WORKSPACE file.
