### ISSUE TITLE
Failed to Build the tulsi project

### ISSUE THREAD

**Issue by adityanair174** [google/mediapipe#4074]
Hello, so I’ve been researching for a resolution since a while. Referred to ticket #3342 #3240 #50 
And could find any resolution. I’m currently on 

-Mac OS Ventura
-Apple Silicon M2 Processor
-XCode 14.2

I followed the exact same steps from the [mediapipe documentation](https://google.github.io/mediapipe/getting_started/ios.html) and also referred to multiple [other](https://qiita.com/ponte1010/items/ed10cb2b5dcf7579f9bc) ones. Wasn’t able to decode the reason. Anyone here can help me out? Would appreciate it! 

I'm able to print the [Hello World C++ code](https://google.github.io/mediapipe/getting_started/hello_world_cpp.html)

Below is the error log that I'm getting:
------------------------------------------
ERROR: Traceback (most recent call last):
ERROR: /Users/adityanair/mediapipe/mediapipe/calculators/tflite/BUILD:178:11: Target '@org_tensorflow//tensorflow/lite/delegates/gpu:gl_delegate' contains an error and its package is in error and referenced by '//mediapipe/calculators/tflite:tflite_inference_calculator'
ERROR: Analysis of target '//mediapipe/examples/ios/iristrackinggpu:IrisTrackingGpuApp' failed; build aborted: 
General failure: Bazel aspects could not be built.

<img width="646" alt="Screenshot 2023-02-08 at 6 16 15 PM" src="https://user-images.githubusercontent.com/57316811/217533524-de002e47-3271-46d6-bf4f-b0cc7554f90d.png">

**Comment by adityanair174** [comment]
Below is the error log that I'm getting:
------------------------------------------
ERROR: Traceback (most recent call last):
ERROR: /Users/adityanair/mediapipe/mediapipe/calculators/tflite/BUILD:178:11: Target '@org_tensorflow//tensorflow/lite/delegates/gpu:gl_delegate' contains an error and its package is in error and referenced by '//mediapipe/calculators/tflite:tflite_inference_calculator'
ERROR: Analysis of target '//mediapipe/examples/ios/iristrackinggpu:IrisTrackingGpuApp' failed; build aborted: 
General failure: Bazel aspects could not be built.

**Comment by kuaashish** [comment]
Hi @adityanair174,
This error we can able to reproduce at our end. we will discuss this internally and let you know the possible solution to run/build the ios example. Thank you!
<img width="716" alt="Screenshot 2023-02-17 at 2 54 54 PM" src="https://user-images.githubusercontent.com/98159216/219607634-0c286f99-b78e-4ca3-add6-5ac64540be27.png">

**Comment by tetromino** [comment]
FYI: `--exoblaze` startup option does not exist in Bazel. It exists only in Blaze (Google-internal variant of Bazel). Blaze and Bazel are related, but their sets of options/flags are not quite the same.

I suspect a Google internal Blaze command line somehow got exported without testing, and it's not compatible with Bazel.

**Comment by richardgetz** [comment]
Any update on this? I am facing a similar issue trying to build the hand tracking example for iOS.

**Comment by kuaashish** [comment]
@adityanair174,

Please modify the [Configs/MediaPipe.tulsigen](https://github.com/google/mediapipe/blob/master/mediapipe/MediaPipe.tulsiproj/Configs/MediaPipe.tulsigen) under the folder [MediaPipe.tulsiproj](https://github.com/google/mediapipe/tree/master/mediapipe/MediaPipe.tulsiproj) As workaround:

Input @ before every buildTargets path from L26 https://github.com/google/mediapipe/blob/master/mediapipe/MediaPipe.tulsiproj/Configs/MediaPipe.tulsigen#L26 as below:

```
"buildTargets" : [
"@//mediapipe/examples/ios/facedetectioncpu:FaceDetectionCpuApp",
"@//mediapipe/examples/ios/facedetectiongpu:FaceDetectionGpuApp",
"@//mediapipe/examples/ios/faceeffect:FaceEffectApp",
"@//mediapipe/examples/ios/facemeshgpu:FaceMeshGpuApp",
"@//mediapipe/examples/ios/handdetectiongpu:HandDetectionGpuApp",
"@//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp",
"@//mediapipe/examples/ios/helloworld:HelloWorldApp",
"@//mediapipe/examples/ios/holistictrackinggpu:HolisticTrackingGpuApp",
"@//mediapipe/examples/ios/iristrackinggpu:IrisTrackingGpuApp",
"@//mediapipe/examples/ios/objectdetectioncpu:ObjectDetectionCpuApp",
"@//mediapipe/examples/ios/objectdetectiongpu:ObjectDetectionGpuApp",
"@//mediapipe/examples/ios/objectdetectiontrackinggpu:ObjectDetectionTrackingGpuApp",
"@//mediapipe/examples/ios/posetrackinggpu:PoseTrackingGpuApp",
"@//mediapipe/examples/ios/selfiesegmentationgpu:SelfieSegmentationGpuApp",
"@//mediapipe/objc:mediapipe_framework_ios"
```

Ref: [Generate[FAIL]: 0.2356s [Details]: General failure: Failed to resolve labels.](https://github.com/google/mediapipe/issues/4387)
