### ISSUE TITLE
Plans to bring Object Detection to web / web assembly? 

### ISSUE THREAD

**Issue by shawnmitchell** [google/mediapipe#4076]
### MediaPipe Solution (you are using)

Object Detection

### Programming language

typescript / web assembly

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

```shell
I'd like to use Object Detection on web / web assembly. I see support for Objectron so it seems Object Detection should be doable.
```

### Will this change the current API? How?

```shell
No
```

### Who will benefit with this feature?

Developers who want to use Object Detection in their web applications

### Please specify the use cases for this feature

```shell
The ability to detect trained objects from within a web / web assembly application
```

**Comment by ayushgdev** [comment]
Hello @shawnmitchell 
Unfortunately there are no plans to bring Web assembly for Object detection in Javascript. We might include it in our roadmap later, if the demand escalates, however it is not as of now.

**Comment by shawnmitchell** [comment]
> Hello @shawnmitchell Unfortunately there are no plans to bring Web assembly for Object detection in Javascript. We might include it in our roadmap later, if the demand escalates, however it is not as of now.

Thanks @ayushgdev. I know @prantoran was doing some work on an emscripten wasm build target. Is there a chance you might open source the scripts your team used to produce the Objectron wasm target from the C++ code base?

**Comment by ayushgdev** [comment]
@shawnmitchell We are working on open-sourcing the JS solutions code as well. It has been a demand by the users for quite sometime now, and we do realise there has ben delay in addressing it. However, please be assured that it is in our active work segment and they will be released once stable.
