### ISSUE TITLE
iOS Installation guide does not work if the Xcode version is different than 13.4.1

### ISSUE THREAD

**Issue by ayushgdev** [google/mediapipe#4078]
### Description of issue (what needs changing)

The documentation of iOS setup says that the build_and_run.sh file should be executed. However it failed with error if the Xcode version installed in the system is not same as the one specified in the script. 

### Clear description

The documentation should specify at least that there might be a need to change the xcode_version in the build_and_run.sh script in Tulsi repo

### Raises listed and defined

ERROR: .../external/local_config_xcode/BUILD:12:13: in xcode_config rule @ loca1_config_xcode//:host_xcodes: --xcode_version=13.4.1 specified, but '13.4.1' is not an available Xcode version

### Submit a pull request?

Yes

**Comment by ayushgdev** [comment]
This has been fixed internally.

**Comment by BTLDXX-x** [comment]
hi @ayushgdev, i still met this issue. how can i solve it?
thanks a lot

**Comment by scofielddd** [comment]
hi how you guys solve this question

**Comment by Waaheeda** [comment]
@scofielddd Hi, I looked for build_and_run.sh in spotlight and changed Xcode version in script to my current version of Xcode and executed script again using command sh build_and_run.sh  and it worked like charm :) 💯
