### ISSUE TITLE
Followup question about mediapipe extractor and youtube8m data

### ISSUE THREAD

**Issue by yw2278** [google/mediapipe#408]
for video id fg6m. the feature I get from the feature extractor are flaots like 0.40838873, -0.66608351, -0.52097726, -0.60093373, -0.3703512, but the correspoding feature from the Chanllenge data are 155., 86., 106., 82., 97. even though I use quantize the two data are quite different, for eg. -0.60093373 quantized to 89, but corresponding value is 82.

So, except the quantize, is there any extra step to get exact youtube8m challenge data?

**Comment by jiuqiant** [comment]
No, there is no extra step after quantization. The feature extraction pipeline we open sourced is using the public VGGish and Inception models. It is expected to generate the approximate results.
