### ISSUE TITLE
metalTextureWithGpuBuffer

### ISSUE THREAD

**Issue by jfdream** [google/mediapipe#4081]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

iOS,macOS

### Programming Language and version

C++,ObjC

### MediaPipe version

0.9.1

### Bazel version

5.0

### Solution

facemesh

### Describe the actual behavior

```shell
This method metalTextureWithGpuBuffer create the id<MTLTexture> there is a problem, when CVMetalTextureRef release id<MTLTexture> memory unreliable, there might be modified and Cause the picture to flicker
```

### Describe the expected behaviour

```shell
Release CVMetalTextureRef when id<MTLTexture> is not required
```

### Standalone code/steps you may have used to try to get what you need

```shell
It is stable reproduce on some intel macOS models
```

**Comment by kuaashish** [comment]
Hi @jfdream,
Sorry for the late response! Could you please let us know complete steps followed to reproduce the issue from our end. Thank you!
