### ISSUE TITLE
mediapipe facemesh orientation

### ISSUE THREAD

**Issue by isdito** [google/mediapipe#4085]
Good morning,

I would like to know if a person looks at the camera or not. I can't get the orientation of the face.

Nor the position of the eyes and chin to somehow calculate the pitch, yaw, roll

Can someone help me with a simple example, which I can't find, they are all references to incomplete parts that cannot be seen.

Thank you

**Comment by kuaashish** [comment]
Hi @isdito,
Would you please let us know the complete details, platform, solution you are using? It's recommend to fill the [template ](https://github.com/google/mediapipe/issues/new/choose) to get max relevant info to understand the issue better. Thank you!
