### ISSUE TITLE
Windwos can not run Gesture model???

### ISSUE THREAD

**Issue by jinfagang** [google/mediapipe#4087]
### OS Platform and Distribution

RuntimeError: File loading is not yet supported on Windows

### Compiler version

RuntimeError: File loading is not yet supported on Windows

### Programming Language and version

RuntimeError: File loading is not yet supported on Windows

### Installed using virtualenv? pip? Conda?(if python)

RuntimeError: File loading is not yRuntimeError: File loading is not yet supported on Windowset supported on Windows

### MediaPipe version

0.9

### Bazel version

5.1

### XCode and Tulsi versions (if iOS)

RuntimeError: File loading is not yet supported on Windows

### Android SDK and NDK versions (if android)

RuntimeError: File loading is not yet supported on Windows

### Android AAR (if android)

Yes

### OpenCV version (if running on desktop)

RuntimeError: File loading is not yet supported on Windows

### Describe the problem

```shell
A bug happened!RuntimeError: File loading is not yet supported on Windows
```

### Complete Logs

```shell
RuntimeError: File loading is not yet supported on Windows
```

**Comment by kuaashish** [comment]
Hi @jinfagang,
Would you please let us know the complete steps followed to run/build the above example in windows? Thank you!

**Comment by trysightdev** [comment]
I'm having this issue as well. I followed this example and have the exact same error
https://github.com/googlesamples/mediapipe/blob/main/examples/hand_landmarker/python/hand_landmarker.ipynb

I'm using Windows 11 and Python 3.9.13


```RuntimeError                              Traceback (most recent call last)
Cell In[12], line 10
      8 base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
      9 options = vision.HandLandmarkerOptions(base_options=base_options, num_hands=2)
---> 10 detector = vision.HandLandmarker.create_from_options(options)
```


`RuntimeError: File loading is not yet supported on Windows`

I thought this could be from setting model_asset_path in BaseOptions but even if I remove that or try to change it to model_asset_buffer it still doesn't work
It seems like create_from_options will always cause this error even if I change BaseOptions settings
