### ISSUE TITLE
Getting error when run the project.

### ISSUE THREAD

**Issue by Sonamgupta2109** [google/mediapipe#409]
Hi, 

I am getting error output path is not specific. When trying to run the project. It's scan successfully. Please help how can i resolved this. Please see the error screen sort.

https://docs.google.com/uc?export=download&id=1aYXmMx9p3XMPvrarXibNKnCnZ2hBOP7x

Here is the logs :

Waiting for target device...
Invoking mobile-install...
Command: /home/emilence/bin/bazel mobile-install --tool_tag=ijwb:AndroidStudio --device 94bc5328 "--adb_arg=-s " --adb_arg=94bc5328 --adb /home/emilence/Android/Sdk/platform-tools/adb --curses=no --color=yes --progress_in_terminal_title=no -c opt --config=android_arm64 --fission=no -c dbg --build_event_binary_file=/tmp/intellij-bep-383fdfbb-bc4b-49eb-93ef-cd6c885c7129 --nobuild_event_binary_file_path_conversion -- //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

INFO: Writing tracer profile to '/home/emilence/.cache/bazel/_bazel_emilence/d31ce70e37bd06623c564a089528eec3/command.profile.gz'
Loading: 
Loading: 0 packages loaded
INFO: Build options --compilation_mode, --cpu, --crosstool_top, and 3 more have changed, discarding analysis cache.
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (0 packages loaded, 0 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (0 packages loaded, 0 targets configured)
WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (39 packages loaded, 284 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (57 packages loaded, 620 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (75 packages loaded, 3687 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (94 packages loaded, 7189 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (102 packages loaded, 8605 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (112 packages loaded, 10043 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (120 packages loaded, 10891 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (130 packages loaded, 11724 targets configured)
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (131 packages loaded, 11787 targets configured).

INFO: Found 1 target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[710 / 1,550] checking cached actions
[2,165 / 2,166] [Prepa] Installing //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
INFO: From Installing //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu:
Updating 1 dex...
Updating application resources...
Updating 2 native libs...
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu up-to-date:
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu_files/full_deploy_marker
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu_files/deploy_info_incremental.deployinfo.pb
INFO: Elapsed time: 294.656s, Critical Path: 268.82s
INFO: 1 process: 1 local.
INFO: Build completed successfully, 3 total actions
INFO: Build completed successfully, 3 total actions
INFO: Build Event Protocol files produced successfully.
INFO: Build completed successfully, 3 total actions
Reading deployment information...
Total Jar Cache size: 19957 kB (57 files)
Command: /home/emilence/bin/bazel info --tool_tag=ijwb:AndroidStudio execution_root --curses=no --color=yes --progress_in_terminal_title=no -c opt --config=android_arm64 --fission=no -c dbg --

INFO: Writing tracer profile to '/home/emilence/.cache/bazel/_bazel_emilence/d31ce70e37bd06623c564a089528eec3/command.profile.gz'

**Comment by Acimaz** [comment]
Can you post the log in here instead of a link to a .png online? :)

**Comment by Sonamgupta2109** [comment]
I added the logs. Please help how can i install

**Comment by mgyong** [comment]
For the hands tracking, we have [steps on how to compile the aar](https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md) and [an example of aar that you can use in gradle](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example)
