### ISSUE TITLE
Upgrade macOS silicon to 0.9.1!!!

### ISSUE THREAD

**Issue by jinfagang** [google/mediapipe#4090]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

macos

### MediaPipe version

0.8.11

**Comment by kuaashish** [comment]
@jinfagang,
Seems you are looking the build/run the mediapipe latest version `0.9.1`. As mentioned [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-macos) in documentation, You will be able to build/run the Hello_world example as attached here in screenshot. Please follow up with the guide and revert back if still issue from your end. Thank you!
<img width="1364" alt="Screenshot 2023-02-10 at 3 22 50 PM" src="https://user-images.githubusercontent.com/98159216/218417724-fd5b475e-abd6-4850-ac17-6dcf95b12054.png">

**Comment by jinfagang** [comment]
No, I want the pip version be upraded. I don't want build myself on mac, I don't want install  bazel, my mac is run out of space.

**Comment by kuaashish** [comment]
Hi @jinfagang,
Unfortunately,  Still we are unable to provide the official support on macOS using the PyPi package. This is already a request which has been shared with the team. However, we are forwarding this request to team. Thank you!

**Comment by schmidt-sebastian** [comment]
We have released Universal Wheels with version 0.9.3.9.
