### ISSUE TITLE
Possibility of patent infringement of game operation using Mediapipe Pose

### ISSUE THREAD

**Issue by tomo-kofu** [google/mediapipe#4092]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows

### Solution

Pose FaceMesh Hands

### Programming Language and version

C++

### Describe the actual behavior

```shell
We are creating tools to operate games based on motion, such as Mediapipe Pose.
I am concerned whether this constitutes a patent infringement of a past patent.

For example, wouldn't the following Microsoft Kinect patent be infringed?
  https://patents.google.com/patent/US8660303B2/en?q=(microsoft+motion+model+tracking+capture)&oq=microsoft+motion+model+tracking+capture

Technically, Kinect uses a depth camera and Mediapipe uses an RGB camera, so I think there are some differences.
I think it might apply to the doctrine of equivalence.
```

**Comment by kuaashish** [comment]
Hi @tomo-kofu,
Could you please elaborate your query with complete details. Thank you!

**Comment by tomo-kofu** [comment]
Hi kuaashish.

thank you for your reply.

Sorry, I don't know much about patents.
It is difficult to explain the details, but I will add as much as I can understand.


Mediapipe Pose uses an RGB camera (web camera) to detect a person's skeleton and estimate their posture.
For example, if the person in the camera jumps, the character in the action game will jump.
Besides, if a person punches, a character in a fighting game will punch.
It was fun to try.


So, we considered whether we could release it commercially to the world.

Then I realized that there were already similar technologies and products. It's a Microsoft Kinect.
Kinect uses a depth camera to capture human motion and control the game with your movements.
Similar to above, when a person jumps, the game character jumps or punches.

The technical content of this Kinect was patented as described in the following URL.
  https://patents.google.com/patent/US8660303B2/en?q=(microsoft+motion+model+tracking+capture)&oq=microsoft+motion+model+tracking+capture
  This is probably the Japanese version: https://www.j-platpat.inpit.go.jp/c1800/PU/JP-5739872/C81A7D37A7E4239D851C941E8D089506045E7B07BA5A2B405C2C52129DDA30D9/15/ja


Both of the above are the same in terms of motion capture.
However, they use different cameras. An RGB camera and a depth camera.
Therefore, I believe that there is no patent infringement.

However, upon further investigation, I realized that there is a doctrine of equivalents in patent infringement.
I wasn't sure if replacing the depth camera with an RGB camera would apply to the doctrine of equivalents.
It seems that there are some conditions for the doctrine of equivalents to apply.
Below is the reference URL for the doctrine of equivalents.
  https://en.wikipedia.org/wiki/Doctrine_of_equivalents


After all, I considered it for more than several days, but I didn't know whether it would be a doctrine of equivalents and a patent infringement.
If anyone knows, please let me know.


Thank you for reading.

**Comment by tomo-kofu** [comment]
I uploaded a video to YouTube to explain what I made.
It use body to operate the Chrome dino game.
Please take a look at the URL below.
  https://www.youtube.com/watch?v=CdKiSRHxDWw

**Comment by kuaashish** [comment]
@tomo-kofu,
Please allow us sometime to share the best information on the issue. thank you!!

**Comment by kuaashish** [comment]
@tomo-kofu,
we think that the mediapipe license allows this. However, we can not let you know about the whether this will infringement the Microsoft patent right or not.(Suggestion: Please contact with the legal adviser mainly who have expertise in patent copyright and infringement). Thank you!

**Comment by tomo-kofu** [comment]
Thank you for your reply.

I got it.
Maybe it's not patent infringement.
However, I would like to proceed cautiously, so I would like to publish information on YouTube etc. and obtain the opinions of experts.

So, I shot a video of how to operate Vircadia.
Just out of curiosity, let me share.

https://youtu.be/rjTYurtS-c4

thank you for reading.

**Comment by kuaashish** [comment]
@tomo-kofu,
Thank you for reverting us back, Please feel free to close if this is no longer issue from your end.

**Comment by tomo-kofu** [comment]
Thank you for contacting us.

I got it.
I will try to upload some information on the internet.

I will close this issue once I have confirmed the answer. Is that okay?

I hurriedly re-recorded the video of vircadia, so I will share it here.
  https://youtu.be/-ljSMVA0vqU

**Comment by kuaashish** [comment]
Hi @tomo-kofu,
Could you please update the status of the above and let us know if we can mark this issue as resolved. Thank you!

**Comment by tomo-kofu** [comment]
Thank you for contacting us.

In the case of testing or research, it seems that there are cases where patent infringement does not occur.
For now, I will close this issue. thank you very much.
