### ISSUE TITLE
Error when loading @mediapipe/control_utils_3d from cdn.jsdelivr.net

### ISSUE THREAD

**Issue by maxwellpeterson** [google/mediapipe#4094]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Browser and version if the issue happens on browser

Google Chrome 110.0.5481.77

### Programming Language and version

Javascript

### Solution

Hands

### Describe the actual behavior

A ReferenceError is thrown when loading the @mediapipe/control_utils_3d package from https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d/control_utils_3d.js. While this script is being loaded, it initiates a GET request to /deps.js on the host domain, which fails.

Note that there is no other Javascript on the page, and the errors are caused by merely downloading the package using a <script> tag.

### Describe the expected behaviour

The @mediapipe/control_utils_3d package can be loaded from jsDelivr without any errors being thrown, and without any requests being initiated to the host domain.

Note that this is the behavior when downloading @mediapipe/camera_utils, @mediapipe/control_utils, and @mediapipe/drawing_utils from jsDelvr. Only the @mediapipe/control_utils_3d package appears to be broken.

### Standalone code/steps you may have used to try to get what you need

Open the following HTML file in Chrome (or serve it locally with a static HTTP server):

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <script
      src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d/control_utils_3d.js"
      crossorigin="anonymous"
    ></script>
  </head>
  <body></body>
</html>
```

### Other info / Complete Logs

Console error when HTML file is opened/served:

Uncaught ReferenceError: javascript is not defined
  at mesh_viewer.ts:97:45

In the network tab of developer tools, you should also see a failed GET request to /deps.js that was initiated by mesh_viewer.ts:97

Note that the same console error and failed request appear in the web demo (https://codepen.io/mediapipe/pen/jOMbvxw) that is linked at the end of the hands docs (https://google.github.io/mediapipe/solutions/hands.html#resources). In this case, the browser is able to swallow the errors and the web demo can use code from the @mediapipe/control_utils_3d package, but it appears that something is broken with the way this particular package is built/bundled.

**Comment by ayushgdev** [comment]
@maxwellpeterson Thanks for bringing our attention to this issue and documenting the issue with minute detail. 
We shall have a look at it and fix it.

**Comment by akssieg** [comment]
In my case earlier it was showing:
```
Uncaught ReferenceError: javascript is not defined
    at mesh_viewer.ts:97:45
GET http://127.0.0.1:5501/deps.js net::ERR_ABORTED 404 (Not Found)
Refused to execute script from 'http://127.0.0.1:5501/deps.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

but after putting `window.CLOSURE_NO_DEPS=1;` it still shows:
```
Uncaught ReferenceError: javascript is not defined
    at mesh_viewer.ts:97:45
```
