### ISSUE TITLE
PoseTrackingGpu Sample app returns null instead of landmraks

### ISSUE THREAD

**Issue by seunggyuV** [google/mediapipe#4095]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android 12

### Mobile device if the issue happens on mobile device

galaxy s10 5g

### Programming Language and version

Java

### MediaPipe version

0.9.1

### Solution

Pose

### Describe the actual behavior

```shell
2023-02-14 17:43:02.672 23728-23851 MainActivity            pid-23728                            V  Received pose landmarks packet.
2023-02-14 17:43:02.672 23728-23851 MainActivity            pid-23728                            E  Failed to get proto.
                                                                                                    com.google.protobuf.InvalidProtocolBufferException: Message type does not match the expected type. Expected: null Got: mediapipe.NormalizedLandmarkList
                                                                                                    	at com.google.mediapipe.framework.ProtoUtil.unpack(ProtoUtil.java:58)
                                                                                                    	at com.google.mediapipe.framework.PacketGetter.getProto(PacketGetter.java:127)
                                                                                                    	at com.google.mediapipe.framework.PacketGetter.getProto(PacketGetter.java:136)
                                                                                                    	at com.google.mediapipe.apps.posetrackinggpu.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:43)
                                                                                                    	at com.google.mediapipe.apps.posetrackinggpu.MainActivity$$Lambda$0.process(Unknown Source:0)

There are only error logs, not landmarks. Maybe the model returns null.
```

### Describe the expected behaviour

```shell
I expected there will be log containing pose landmarks.
Because of these codes in posetrackinggpu/MainActivity.java


@Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // To show verbose logging, run:
    // adb shell setprop log.tag.MainActivity VERBOSE
    if (Log.isLoggable(TAG, Log.VERBOSE)) {
      processor.addPacketCallback(
          OUTPUT_LANDMARKS_STREAM_NAME,
          (packet) -> {
            Log.v(TAG, "Received pose landmarks packet.");
            try {
              NormalizedLandmarkList poseLandmarks =
                  PacketGetter.getProto(packet, NormalizedLandmarkList.class);
              Log.v(
                  TAG,
                  "[TS:"
                      + packet.getTimestamp()
                      + "] "
                      + getPoseLandmarksDebugString(poseLandmarks));
            } catch (InvalidProtocolBufferException exception) {
              Log.e(TAG, "Failed to get proto.", exception);
            }
          });
    }
  }
```
```


### Standalone code/steps you may have used to try to get what you need

```shell
I'm sorry. I don't know why this happend.
```

**Comment by kuaashish** [comment]
@seunggyuV,
Would you please share the exact steps followed to debug issue at our end? Thank you!

**Comment by seunggyuV** [comment]
@kuaashish

Thank you for your reply.
If you run the PoseTrackingGpu sample app for Android you can see the bug in the logs. Tag is MainActivity

After writing this issue, I looked at the code a bit more and I found that the landmark value is not null.

https://github.com/google/mediapipe/blob/d450a673c0ee4a9a810577475ddea3d3d351070a/mediapipe/java/com/google/mediapipe/framework/ProtoUtil.java#L54-L73
 I found a problem in mediapipe/java/com/google/mediapipe/framework/ProtoUtil.java that NormalizedLandmarkList.getclass() returns null unintentionally. How can i solve it? Thank you a lot.

**Comment by kuaashish** [comment]
Hi @seunggyuV,
Could you please confirm that you have created the aar_file as mentioned [here](https://google.github.io/mediapipe/getting_started/android_archive_library.html) as this solution is directly not available to use? If already followed the mentioned steps, can you share the complete code package to github to understand the issue better. Thank you!

**Comment by seunggyuV** [comment]
@kuaashish 
I was building and testing an android app right with Basel. I used this command
`bazelisk build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu:posetrackinggpu`


This time, as you said I made a sample app after building aar_file. But sadly, the same error log occurs. I put my code here.

[https://github.com/seungy0/PoseRecognitionSample](url)

Thank you for your kindness.

**Comment by magic-fit** [comment]
@seunggyuV I had the same issue. You need to register the type with ProtoUtil:

```
ProtoUtil.registerTypeName(
  NormalizedLandmarkList::class.java,
  "mediapipe.NormalizedLandmarkList"
)
```

**Comment by seunggyuV** [comment]
@magic-fit OMG you are right. Thank you so much!!

How did you know that??

I'm reading mediapipe website, codes etc. How can I find the information like this?

Do you have to read the code one by one to understand it? It was difficult because the files were connected like a spider's web.

How do I figure out how to use classes like ProUtil you mentioned?? I would really appreciate it if you could give me some advice.

Thank you again.

**Comment by seunggyuV** [comment]
@kuaashish The problem is solved. But I think the sample app needs to be fixed.

We need to insert this code 

`ProtoUtil.registerTypeName(
            NormalizedLandmarkList.class,
            "mediapipe.NormalizedLandmarkList"
    );`
here
https://github.com/google/mediapipe/blob/223c504d819c4ef8ff2dae71e7e5b02fdbdaa510/mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu/MainActivity.java#L33

**Comment by kuaashish** [comment]
@seunggyuV,
Glad to hear that the issue has been resolved!, Thank you for the contribution above that will be help community. Closing this issue as it has been resolved.
