### ISSUE TITLE
 “mediapipe/examples/desktop/hello_world:hello_world” compilation is failed

### ISSUE THREAD

**Issue by makananamu** [google/mediapipe#4097]
### OS Platform and Distribution

Linux Ubuntu 22.04

### Compiler version

gcc 11.3.0

### Programming Language and version

C++

### Bazel version

5.2.0

### Android AAR (if android)

None

### Describe the problem

```shell
I think I correctly installed Mediapipe on Linux using the documentation(https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu).I installed openCV  with setup_opencv.sh and Android with command (bash setup_android_sdk_and_ndk.sh ~/Android/Sdk ~/Android/Ndk r18b).But I failed to compile the Hello World C++ project for CPU. ( I gave the command from the documentation: bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world ).See next logs.
There is really no platforms folder in my /home/usr/Android/Sdk directory. Is there a problem with my Android environment installation?  Is the Android environment necessary when compiling and running desktop projects？
```

### Complete Logs

```shell
ERROR: /home/usr/mediapipe-master/mediapipe-master/WORKSPACE:547:23: fetching android_sdk_repository rule //external:androidsdk: java.io.IOException: Expected directory at /home/usr/Android/Sdk/platforms but it is not a directory or it does not exist. Unable to read the Android SDK at /home/usr/Android/Sdk, the path may be invalid. Is the path in android_sdk_repository() or ANDROID_HOME set correctly? If the path is correct, the contents in the Android SDK directory may have been modified.
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Expected directory at /home/usr/Android/Sdk/platforms but it is not a directory or it does not exist. Unable to read the Android SDK at /home/usr/Android/Sdk, the path may be invalid. Is the path in android_sdk_repository() or ANDROID_HOME set correctly? If the path is correct, the contents in the Android SDK directory may have been modified.
INFO: Elapsed time: 1.069s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded, 11 targets configured)
FAILED: Build did NOT complete successfully (4 packages loaded, 11 targets configured)
    currently loading: @bazel_tools//tools/python ... (5 packages)
    Fetching @local_execution_config_python; fetching
    Fetching @remotejdk11_macos_toolchain_config_repo; fetching
```

**Comment by MakeMeCookie** [comment]
@makananamu  
The path of this error content is not correct now. The ANDROID SDK, NDK file path should be set under line 547 in the WORKSPACE file.

**Comment by makananamu** [comment]
> 
@MakeMeCookie 
Thank you for your reply! Could you please tell me how to set the path of SDK and NDK in the WORKSPACE file? At present, I only set the path of "ANDROID_HOME" in "/etc/profile". At the same time, I also found that there is no "platform" folder under my "/home/usr/Android/Sdk"  directory, but there is a  "platform"  folder under the "/home/usr/Android/Sdk/ndk-bundle/android-ndk-r21/" path. Which path should I set in the WORKSPACE file?
How can I solve it? Thank you a lot.

**Comment by kuaashish** [comment]
Hi @makananamu,

Could you please inspect the following sequentially:

- Check the **Bazel version** if version is above or lower to 5.2.0, Make sure you have bazel supported version **5.2.0**.

- Verify the **OpenCV** version make sure if version is **4.*** then mentioned [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu) **Step 3** choose the **Option1**  and see the _`"Note. On Debian 11/Ubuntu 21.04 where OpenCV 4.5 is installed with libopencv-video-dev, libopencv-contrib-dev should also be installed."`_ and install all libraries mentioned above and below the Note.
- In the **Step 3** **Option 3** under `OpenCV 4 setup:` make sure you have modified the files [opencv_linux.BUILD](https://github.com/google/mediapipe/blob/master/third_party/opencv_linux.BUILD) and [ffmpeg_linux.BUILD](https://github.com/google/mediapipe/tree/master/third_party/ffmpeg_linux.BUILD)(tested with OpenCv 4.5 in Linux 22.04 LTS).

I could successfully reproduce the issue and run the hello_world example in 22.04 LTS with Bazel version 5.2.0, OpenCV 4.5 attached the screenshot below. Please inspect the above points and revert back if still an issue. Thanks!!
<img width="1724" alt="Screenshot 2023-02-17 at 11 34 14 AM" src="https://user-images.githubusercontent.com/98159216/219574280-f6e419b3-da6c-4995-a0e9-226a0d907f66.png">

**Comment by kuaashish** [comment]
@makananamu,
Could you please update the status of the above issue? Thank you!

**Comment by makananamu** [comment]
@kuaashish I'm sorry, please forgive me for my late reply. I have solved my problem according to your steps. The reason is that I did not install the dependent package according to the tips in Note. Thank you very much for your help and apologize again for my impoliteness and delay.

**Comment by makananamu** [comment]
@kuaashish I'm sorry, please forgive me for my late reply. I have solved my problem according to your steps. The reason is that I did not install the dependent package according to the tips in Note. Thank you very much for your help and apologize again for my impoliteness and delay.

**Comment by kuaashish** [comment]
@makananamu,
No Issue, Glad to hear that issue has been resolved. Could you please let us know if we can move the issue to close status as resolved. Thank you!
