### ISSUE TITLE
Correct usage of Xcode when creating mediapipe projects

### ISSUE THREAD

**Issue by Acimaz** [google/mediapipe#410]
Hey,

atm, I'm working through the examples (EdgeDetection) on my mac for iOS and whenever I import mediapipe classes it obviously can't be found because the paths in the example don't take that into account. I was wondering, are you guys using it like this as well? No code completion and constantly full of errors when editing in Xcode for example? I'm really struggling to use it like this and even if I fix my own paths mediapipes classes show the same error.

Maybe I am using it the wrong way though.

**Comment by Acimaz** [comment]
Due to these errors, I'm not able to build the project (trying to show video frames live following the iOS [Hello World Tutroial](https://mediapipe.readthedocs.io/en/latest/hello_world_ios.html).
Im pasting only the error lines here:

`ERROR: /Users/ayhan/Development/Repositories/mediapipe/mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/BUILD:21:1: C++ compilation of rule '//mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample:EdgeDetectionGpuAppLibraryTest' failed (Exit 1) wrapped_clang failed: error executing command 
  (cd /private/var/tmp/_bazel_ayhan/e152f34855cd300d7c692ed185c73309/sandbox/darwin-sandbox/883/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=13.2 \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    XCODE_VERSION_OVERRIDE=11.3.1.11C504 \
  external/local_config_cc/wrapped_clang -arch arm64 '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -g -Wshorten-64-to-32 -Wbool-conversion -Wconstant-conversion -Wduplicate-method-match -Wempty-body -Wenum-conversion -Wint-conversion -Wunreachable-code -Wmismatched-return-types -Wundeclared-selector -Wuninitialized -Wunused-function -Wunused-variable -iquote . -iquote bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin -Ibazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/external/google_toolbox_for_mac -Iexternal/google_toolbox_for_mac -isystem external/com_google_protobuf/src -isystem bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/external/com_google_protobuf/src -isystem external/zlib_archive -isystem bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/external/zlib_archive -isystem external/com_github_glog_glog/src -isystem bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/external/com_github_glog_glog/src -MD -MF bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/_objs/EdgeDetectionGpuAppLibraryTest/arc/ViewController.d '-DGLES_SILENCE_DEPRECATION=1' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DMEDIAPIPE_PROFILER_AVAILABLE -DOS_IOS -fno-autolink -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -fobjc-arc '-miphoneos-version-min=10.0' -Wno-sign-compare -Wno-unused-function -Wno-uninitialized -Wno-unused-result -Wno-comment -Wno-return-type -Wno-unused-local-typedefs -Wno-ignored-attributes -Os '-DNDEBUG=1' -Wno-unused-variable -Winit-self -Wno-extra -c mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.m -o bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/_objs/EdgeDetectionGpuAppLibraryTest/arc/ViewController.o)
Execution platform: @local_config_platform//:host`

`mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.m:25:5: error: unknown type name 'MPPLayerRenderer'
    MPPLayerRenderer* _renderer;
    ^
mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.m:32:19: error: use of undeclared identifier 'MPPLayerRenderer'
    _renderer = [[MPPLayerRenderer alloc] init];
                  ^
mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.m:35:32: error: use of undeclared identifier 'MPPFrameScaleModeFillAndCrop'
    _renderer.frameScaleMode = MPPFrameScaleModeFillAndCrop;`

`mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.m:70:9: error: implicit declaration of function 'dispatch_queue' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        dispatch_queue(_videoQueue, ^{`

**Comment by Acimaz** [comment]
However, I can build the example project under examples/ios/edgedetectiongpu without any of the errors above.

**Comment by mgyong** [comment]
@Acimaz 
Did you try to use Tulsi to import your MediaPipe pipeline into Xcode project
https://mediapipe.readthedocs.io/en/latest/mediapipe_ios_setup.html#creating-an-xcode-project

**Comment by Phando** [comment]
Hey All,
This project looks amazing! I've got the examples projects running from the command line and from Tulsi. Even when I am in xcode, the project that is generated is hardly useable. Take hand tracking for instance, I am unable to adjust the line widths or colors of the rendered landmarks. What is the strategy to incorporate the landmarks into my top level app? Is there a mediapipe example that has the code at the top level like a normal project? A swift hello world would be freaking amazing.

**Comment by mgyong** [comment]
@Phando Check out this [tutorial](https://medium.com/@powderapp/mediapipe-tutorial-find-memes-that-match-your-facial-expression-9bf598da98c0) in the [awesome-mediapipe repo](https://github.com/mgyong/awesome-mediapipe/#ios)
