### ISSUE TITLE
How to get from NormalizedRect a rotation in (X,Y,Z)?

### ISSUE THREAD

**Issue by burungiu** [google/mediapipe#4103]
Hello everyone,

I want to convert NormalizedRect given by the Objectron in something like 3D rotation values.
I got these values
`{ "xCenter": 0.326659143, "yCenter": 0.7140226, "height": 0.2670138, "width": 0.0828191638, "rotation": 0.02296813 }`

But I don't know how to convert them into 3D rotation values.

This template is for miscellaneous issues not covered by the other issue categories

For questions on how to work with MediaPipe, or support for problems that are not verified bugs in MediaPipe, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mediapipe) and [Slack](https://mediapipe.page.link/joinslack) communities.

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/google/mediapipe/security).

**Comment by kuaashish** [comment]
HI @burungiu,
Could you please elaborate your query with more details. Thank you!

**Comment by burungiu** [comment]
Hello, I try to place a sneaker over the boundboxes in mediapipe/objectron. I don't know how to positionate it based on coordinates which algorithm returns.
