### ISSUE TITLE
Low FPS for Samsung Note 10+ Android phone

### ISSUE THREAD

**Issue by fchen09** [google/mediapipe#4107]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android 12

### MediaPipe version

v0.9.1

### Bazel version

5.2.0-homebrew

### Solution

Pose-gpu

### Programming Language and version

Java

### Describe the actual behavior

```shell
When I run the "posetrackinggpu" official example on my Samsung Note 10+ Android phone, it shows only around 9 -12 FPS, and GPU usage of around 42 % when tracing. If not tracing, it shows 20 FPS and GPU use of 18 %. I am wondering how to improve GPU use and improve the to 30 FPS. Thanks!
Tracing: https://photos.app.goo.gl/k2yApFCiEiuDDLV16
Not Tracing: https://photos.app.goo.gl/pqCVjmCnVmkGB9TD7
```

### Describe the expected behaviour

```shell
Expect to run posetrackingGPU at 30 FPS with more GPU use.
```

**Comment by kuaashish** [comment]
Hi @fchen09,
As mentioned here [#1160(comment)](https://github.com/google/mediapipe/issues/1160#issuecomment-872706753), _"MediaPipe graphs will queue/drop frames when the input is faster than the system can handle. The more powerful the device (or more simple the graph), the less frames dropped/queued, the higher fps can be achieved."_. We suggest that please follow the input described here and let us know report back if any significance improvement will observed. Thank you!

**Comment by fchen09** [comment]
Is it possible to utilize GPU 100 %? Now, it only uses around 50%.

**Comment by kuaashish** [comment]
@fchen09,
Could you please report us any of the screenshot matter to GPU utilization, code changes done to provide the possible solution?

**Comment by fchen09** [comment]
Please refer to the below links for GPU usage. It shows 42 % at the top-right.
Tracing: https://photos.app.goo.gl/k2yApFCiEiuDDLV16
Not Tracing: https://photos.app.goo.gl/pqCVjmCnVmkGB9TD7

Below is my graph, any nodes could be dropped?
# MediaPipe graph that performs pose tracking with TensorFlow Lite on GPU.

# GPU buffer. (GpuBuffer)
input_stream: "input_video"

# Output image with rendered results. (GpuBuffer)
output_stream: "output_video"
# Pose landmarks. (NormalizedLandmarkList)
output_stream: "pose_landmarks"

# Generates side packet to enable segmentation.
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:enable_segmentation"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet { bool_value: true }
    }
  }
}

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Subgraph that detects poses and corresponding landmarks.
node {
  calculator: "PoseLandmarkGpu"
  input_side_packet: "SMOOTH_LANDMARKS:true"
  input_side_packet: "ENABLE_SEGMENTATION:enable_segmentation"
  input_side_packet: "SMOOTH_SEGMENTATION:true"
  input_side_packet: "USE_PREV_LANDMARKS:true"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "LANDMARKS:pose_landmarks"
  output_stream: "WORLD_LANDMARKS:pose_world_landmarks"
  output_stream: "SEGMENTATION_MASK:segmentation_mask"
  output_stream: "DETECTION:pose_detection"
  output_stream: "ROI_FROM_LANDMARKS:roi_from_landmarks"
}

# Subgraph that renders pose-landmark annotation onto the input image.
node {
  calculator: "PoseRendererGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "LANDMARKS:pose_landmarks"
  input_stream: "SEGMENTATION_MASK:segmentation_mask"
  input_stream: "DETECTION:pose_detection"
  input_stream: "ROI:roi_from_landmarks"
  output_stream: "IMAGE:output_video"
}

**Comment by kuaashish** [comment]
@fchen09,
GPU utilization depends How fast is the system memory? What resolution is the camera/video? On mobile, GPU is almost always faster (for recent devices). You can try to read the camera with GStreamer, Instead of CameraPreview thread can be found [here](https://forums.developer.nvidia.com/t/using-mediapipe-gpu-accelerated-python-solutions-with-cuda-accelerated-opencv/192949/4) may increase the GPU utilization. Thanks!

**Comment by fchen09** [comment]
@kuaashish GStreamer is for CUDA, not for Android plateform. Can you provide other solutions, such as NNAPI?
Furthermore, I even installed the official apk https://drive.google.com/file/d/17GFIrqEJS6W8UHKXlYevTtSCLxN9pWlY/view
It still shows 15~16 FPS. I expect it could run 30 FPS on Note 10+. Thanks.

**Comment by kuaashish** [comment]
@fchen09,
Yes, It is possible to use the solutions such as NNAPI. we suggest to edit the this path https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_by_roi_cpu.pbtxt#L144 Line144 change the delegate to NNAPI. However, solution uses by default the xnnpack delegate, we believe that using the NNAPI delegate you can be able to expect the good fps and also would like to report back if any difference made. Additionally, we recommend to go through the [thread](https://github.com/google/mediapipe/issues/1962) to understand the better on delegates. Thanks

**Comment by fchen09** [comment]
@kuaashish 
I edited the official posetrackinggpu sample code by changing https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_by_roi_cpu.pbtxt#L144 Line 144 to nnapi(), and change the build file https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu/BUILD every "gpu" to "cpu". However, the result leads to a crash on the app built by Bazel. Do you have any ideas on how to fix the bug? Thanks!

**Comment by kuaashish** [comment]
@fchen09,
Could you please share the complete error logs you are getting?

**Comment by fchen09** [comment]
@kuaashish here the log is: 

[logcat.zip](https://github.com/google/mediapipe/files/11075135/logcat.zip)

**Comment by fchen09** [comment]
@kuaashish Is it possible to provide a nnapi tutorial? I have searched the github, but I can't get a good tutorial.

**Comment by fchen09** [comment]
@kuaashish Excuse me to ask you again. does the official apk represent the highest FPS that can achieve for Android smart phones? Or there is space to improve? Thank you?
 https://drive.google.com/file/d/17GFIrqEJS6W8UHKXlYevTtSCLxN9pWlY/view
