### ISSUE TITLE
How to reduce cpu and memory utilization

### ISSUE THREAD

**Issue by xiaolinpeter** [google/mediapipe#4109]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

window 10

### MediaPipe version

0.8.10.1

### Solution

mediapipe hands

### Programming Language and version

python

### Describe the actual behavior

```shell
the cpu utilization is 16% and the memory utilization is 162mb
```

### Describe the expected behaviour

```shell
the cpu utilization the memory utilization can decrease
```

### Standalone code/steps you may have used to try to get what you need

```shell
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

# For webcam input:
cap = cv2.VideoCapture(0)
with mp_hands.Hands(
    model_complexity=0,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5) as hands:
  while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      continue

    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = hands.process(image)

    # Draw the hand annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    if results.multi_hand_landmarks:
      for hand_landmarks in results.multi_hand_landmarks:
        mp_drawing.draw_landmarks(
            image,
            hand_landmarks,
            mp_hands.HAND_CONNECTIONS,
            mp_drawing_styles.get_default_hand_landmarks_style(),
            mp_drawing_styles.get_default_hand_connections_style())
    # Flip the image horizontally for a selfie-view display.
    cv2.imshow('MediaPipe Hands', cv2.flip(image, 1))
    if cv2.waitKey(5) & 0xFF == 27:
      break
cap.release()
```

**Comment by ayushgdev** [comment]
Hello @xiaolinpeter Would you please try this with the latest release of v0.9.1 since we have optimized our solutions?
Also, we would request you to elaborate upon
- Which parts of the solution can be optimized?
- Who will benefit with this feature?
- The use cases for this feature?

**Comment by xiaolinpeter** [comment]
> 
thanks your answer, I will try v0.9.1

**Comment by xiaolinpeter** [comment]
> 你好@xiaolinpeter由于我们已经优化了我们的解决方案，请您使用最新版本的v0.9.1 试试一下吗？ 另外，我们会要求您详细说明
> 
> * 解决方案的哪些部分可以优化？
> * 谁将从这一变化中受益？
> * 改变这个用例？

i try the same code with mediapipe (v0.9.1), but I am sorry to tell you the cpu utilization is 16%  and the memory utilization is 321mb, the cpu  utilization have no difference, the memory utilization get bigger

**Comment by ayushgdev** [comment]
Hello @xiaolinpeter 
Would you please provide hardware spec of the device you are using? Because the CPU utilisation of 16% is relative metric with respect to the device config. We are able to reproduce the issue of around 170Mb memory utilisation. However, we need hardware details as well to _exactly_ replicate this issue at our end.

Also, just to provide context, we are trying to isolate the problem between the graph and the model inference.
