### ISSUE TITLE
Unable to build the hello world example project code when following the tutorial for iOS

### ISSUE THREAD

**Issue by Acimaz** [google/mediapipe#411]
Hey, due to these errors, I'm not able to build the project (trying to show video frames live following the iOS [Hello World Tutroial](https://mediapipe.readthedocs.io/en/latest/hello_world_ios.html).
Im pasting only the error lines here:

`ERROR: /Users/ayhan/Development/Repositories/mediapipe/mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/BUILD:21:1: C++ compilation of rule '//mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample:EdgeDetectionGpuAppLibraryTest' failed (Exit 1) wrapped_clang failed: error executing command 
  (cd /private/var/tmp/_bazel_ayhan/e152f34855cd300d7c692ed185c73309/sandbox/darwin-sandbox/883/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=13.2 \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    XCODE_VERSION_OVERRIDE=11.3.1.11C504 \
  external/local_config_cc/wrapped_clang -arch arm64 '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -g -Wshorten-64-to-32 -Wbool-conversion -Wconstant-conversion -Wduplicate-method-match -Wempty-body -Wenum-conversion -Wint-conversion -Wunreachable-code -Wmismatched-return-types -Wundeclared-selector -Wuninitialized -Wunused-function -Wunused-variable -iquote . -iquote bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin -Ibazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/external/google_toolbox_for_mac -Iexternal/google_toolbox_for_mac -isystem external/com_google_protobuf/src -isystem bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/external/com_google_protobuf/src -isystem external/zlib_archive -isystem bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/external/zlib_archive -isystem external/com_github_glog_glog/src -isystem bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/external/com_github_glog_glog/src -MD -MF bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/_objs/EdgeDetectionGpuAppLibraryTest/arc/ViewController.d '-DGLES_SILENCE_DEPRECATION=1' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DMEDIAPIPE_PROFILER_AVAILABLE -DOS_IOS -fno-autolink -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -fobjc-arc '-miphoneos-version-min=10.0' -Wno-sign-compare -Wno-unused-function -Wno-uninitialized -Wno-unused-result -Wno-comment -Wno-return-type -Wno-unused-local-typedefs -Wno-ignored-attributes -Os '-DNDEBUG=1' -Wno-unused-variable -Winit-self -Wno-extra -c mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.m -o bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/_objs/EdgeDetectionGpuAppLibraryTest/arc/ViewController.o)
Execution platform: @local_config_platform//:host`

`mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.m:25:5: error: unknown type name 'MPPLayerRenderer'
    MPPLayerRenderer* _renderer;
    ^
mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.m:32:19: error: use of undeclared identifier 'MPPLayerRenderer'
    _renderer = [[MPPLayerRenderer alloc] init];
                  ^
mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.m:35:32: error: use of undeclared identifier 'MPPFrameScaleModeFillAndCrop'
    _renderer.frameScaleMode = MPPFrameScaleModeFillAndCrop;`

`mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.m:70:9: error: implicit declaration of function 'dispatch_queue' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        dispatch_queue(_videoQueue, ^{`

**Comment by Acimaz** [comment]
However, I can build the example project under examples/ios/edgedetectiongpu without any of the errors above.

**Comment by eknight7** [comment]
Looks like the tutorial doesn't mention to add the following header files:

```
#import "mediapipe/objc/MPPGraph.h"
#import "mediapipe/objc/MPPCameraInputSource.h"
#import "mediapipe/objc/MPPLayerRenderer.h"
```

We will fix that. Does adding the files fix your issue?

**Comment by Acimaz** [comment]
Yea i just found that too while reading through the original example code. But unfortunately it doesnt fix the problem. These two errors still remain after adding it:

`ERROR: /Users/ayhan/Development/Repositories/mediapipe/mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/BUILD:21:1: C++ compilation of rule '//mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample:EdgeDetectionGpuAppLibrary' failed (Exit 1) wrapped_clang failed: error executing command 
  (cd /private/var/tmp/_bazel_ayhan/e152f34855cd300d7c692ed185c73309/sandbox/darwin-sandbox/620/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=13.2 \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    XCODE_VERSION_OVERRIDE=11.3.1.11C504 \
  external/local_config_cc/wrapped_clang -arch arm64 '-stdlib=libc++' '-std=gnu++11' '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -g -Wshorten-64-to-32 -Wbool-conversion -Wconstant-conversion -Wduplicate-method-match -Wempty-body -Wenum-conversion -Wint-conversion -Wunreachable-code -Wmismatched-return-types -Wundeclared-selector -Wuninitialized -Wunused-function -Wunused-variable -iquote . -iquote bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin -Ibazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/external/google_toolbox_for_mac -Iexternal/google_toolbox_for_mac -isystem external/com_google_protobuf/src -isystem bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/external/com_google_protobuf/src -isystem external/zlib_archive -isystem bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/external/zlib_archive -isystem external/com_github_glog_glog/src -isystem bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/external/com_github_glog_glog/src -MD -MF bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/_objs/EdgeDetectionGpuAppLibrary/arc/ViewController.d '-DGLES_SILENCE_DEPRECATION=1' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DMEDIAPIPE_PROFILER_AVAILABLE -DOS_IOS -fno-autolink -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -fobjc-arc '-miphoneos-version-min=10.0' -Wno-sign-compare -Wno-unused-function -Wno-uninitialized -Wno-unused-result -Wno-comment -Wno-return-type -Wno-unused-local-typedefs -Wno-ignored-attributes -Os '-DNDEBUG=1' -Wno-unused-variable -Winit-self -Wno-extra -c mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.mm -o bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-opt/bin/mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/_objs/EdgeDetectionGpuAppLibrary/arc/ViewController.o)
Execution platform: @local_config_platform//:host
`

`mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.mm:47:32: error: cannot initialize a parameter of type 'id<MPPInputSourceDelegate>' with an lvalue of type 'ViewController *const __strong'
    [_cameraSource setDelegate:self queue:_videoQueue];
                               ^~~~
./mediapipe/objc/MPPInputSource.h:58:49: note: passing argument to parameter 'delegate' here
- (void)setDelegate:(id<MPPInputSourceDelegate>)delegate queue:(dispatch_queue_t)queue;
                                                ^
mediapipe/examples/ios/EdgeDetectionExample/EdgeDetectionExample/ViewController.mm:71:9: error: use of undeclared identifier 'dispatch_queue'
        dispatch_queue(_videoQueue, ^{`

**Comment by Acimaz** [comment]
I tried a bazel clean --expunge because I changed the ViewController.m to ViewController.mm.
I thought the c++ compiler error is related to the file extension, but it wasn't because it still displays it.

**Comment by Acimaz** [comment]
The fact that I am able t build the original hello world example would mean that I am missing something or configured something wrong in my project. But i don't know what it is yet.

**Comment by Acimaz** [comment]
So, when completely pasting the ViewController.mm code from the original example to my project and adding the needed lines to the BUILD file it compiles. So it had to be something in my code above which was not correct. Can't say what it was though.

**Comment by Acimaz** [comment]
Ok, so I think I've found out the real issue. The method "viewWillAppear" in the tutorial is something else than the one used in the original example file.
When I remove the code inside the method to build is successful.

Please update the tutorials as this wastes a lot of time for people who want to learn the mediapipe framework. ✌️

**Comment by eknight7** [comment]
Thanks for your investigation. We will fix the tutorial.

**Comment by PAVUNRAJ** [comment]
I have to face this header file issue is  'mediapipe/objc/MPPCameraInputSource.h' file not found. @Acimaz
