### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmediapipe_jni.so" not found

### ISSUE THREAD

**Issue by vietnt-uet** [google/mediapipe#4111]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android

### Mobile device if the issue happens on mobile device

Samsung Galaxy Tab A8 (Can reproduce issue on Xiaomi and Sony devices too)

### Programming Language and version

Java

### Bazel version

5.0

### Solution

Face Mesh

### Android Studio, NDK, SDK versions (if issue is related to building in Android environment)

NDK 21.4.7075529

### Describe the actual behavior

```shell
I can build the facemeshgpu example and get it run on my tablet. However when I build MediaPipe Android Archive follow by this instruction: https://google.github.io/mediapipe/getting_started/android_archive_library.html I get crash when use this AAR in my Android app.

I have added api_level 21 in WORKSPACE:
android_sdk_repository(name = "androidsdk",  path = "/Users/vietnt/Library/Android/sdk")
android_ndk_repository(name = "androidndk", api_level = 21, path = "/Users/vietnt/Library/Android/sdk/ndk/21.4.7075529")

My latest Android build tools is 30.0.3
```

### Describe the expected behaviour

```shell
When use AAR, it shouldn't crash
```

### Standalone code/steps you may have used to try to get what you need

```shell
1. Build AAR
2. Import AAR to an Android project
3. Observe it crash when load JNI
```

**Comment by kuaashish** [comment]
Hi @vietnt-uet,
Could please report us the CPU Architecture and Instruction Sets of the Samsung Galaxy Tab S8 using? You can follow this [example](https://android.gadgethacks.com/how-to/android-basics-see-what-kind-processor-you-have-arm-arm64-x86-0168051/) to retrieve the information.

**Comment by vietnt-uet** [comment]
@kuaashish This is information I captured from the device.
![Screenshot_20230221-140016_Droid Info](https://user-images.githubusercontent.com/5250857/220271356-61f80e22-97f3-4fe6-9311-93df2428d825.jpg)

**Comment by kuaashish** [comment]
@vietnt-uet,
Could you please share the complete error logs, code changes done to find out the root cause of the issue?

**Comment by vietnt-uet** [comment]
Below are log in my sample Android application, the error show for command:
 System.loadLibrary("mediapipe_jni");
 
<img width="1027" alt="Screenshot 2023-02-22 at 14 31 08" src="https://user-images.githubusercontent.com/5250857/220552571-7c0ecb44-4049-45e1-8e54-9a422e922fc6.png">

Here the the AAR I built: https://drive.google.com/drive/folders/1AGGx3TmgoUF4sjIWfvgh0Ho7yuCTd7US?usp=sharing

**Comment by arifaizin** [comment]
Solve this issue by run the project in real device, not in emulator

**Comment by vietnt-uet** [comment]
@arifaizin I didn't try again from last time however before I was using real device only.

**Comment by kuaashish** [comment]
Hi @vietnt-uet,

We are no longer maintaining the legacy facemesh solution, as it has been integrated into the new Face Landmarker task API, as explained in our [documentation](https://developers.google.com/mediapipe/solutions/guide#legacy). We intend to explore and implement our upgraded Face Landmarker in Android, following the steps outlined in our [documentation](https://developers.google.com/mediapipe/solutions/vision/face_landmarker/android). Additionally, we kindly request you to inform us of any errors encountered during the exploration process.

Thank you
