### ISSUE TITLE
How to get hand 3d world landmarks from holistic?

### ISSUE THREAD

**Issue by jinfagang** [google/mediapipe#4114]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### Describe the actual behavior

```shell
How to get hand 3d world landmarks from holistic?
```

### Describe the expected behaviour

```shell
How to get hand 3d world landmarks from holistic?
```

### Standalone code/steps you may have used to try to get what you need

```shell
How to get hand 3d world landmarks from holistic?
```

### Other info / Complete Logs

```shell
How to get hand 3d world landmarks from holistic?
```

**Comment by Thaina** [comment]
If I understand your issue correctly

Holistic has 3d world landmark separated from poseLandmarks. In js sdk that field was named `ea` and you can use that. I don't know about other languages

**Comment by jinfagang** [comment]
@Thaina  I mean hands.

I have solved it though.

**Comment by Dillxn** [comment]
> @Thaina I mean hands.
> 
> I have solved it though.

Would you mind sharing how you solved it, please?

**Comment by jinfagang** [comment]
No
