### ISSUE TITLE
[Android] Mediapipe Hands: Issue with rendering bitmap at a specific landmark on Hand on camera feed

### ISSUE THREAD

**Issue by pritam-ghosh-dev** [google/mediapipe#4115]
<em>I'm trying to render a Bitmap at the wrist coordinate of hand. So I'm following this [solution](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions/hands/src/main/java/com/google/mediapipe/examples/hands). In ```HandResultGlRenderer.java``` I'm receiving the HandsResult in ```renderResult(HandsResult result, float[] projectionMatrix)``` function.  <em>
After getting the wrist coordinate I'm calling another function ```drawBitmap(landmark.getX(), landmark.getY(),bitmap)```
Here's how drawBitmap() looks like:
```
  private void drawBitmap(float x, float y, Bitmap bitmap) {
    int textureId = loadTexture(bitmap);
    GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, textureId);

    // Define the texture coordinates for the bitmap.
    float[] textureCoordinates = {
            0.0f, 1.0f,
            1.0f, 1.0f,
            0.0f, 0.0f,
            1.0f, 0.0f
    };

    // Define the vertex coordinates for the bitmap.
    float[] vertices = {
            x - (bitmap.getWidth() / 2.0f), y - (bitmap.getHeight() / 2.0f), 0.0f,
            x + (bitmap.getWidth() / 2.0f), y - (bitmap.getHeight() / 2.0f), 0.0f,
            x - (bitmap.getWidth() / 2.0f), y + (bitmap.getHeight() / 2.0f), 0.0f,
            x + (bitmap.getWidth() / 2.0f), y + (bitmap.getHeight() / 2.0f), 0.0f
    };

    // Enable vertex array and texture array.
    GLES30.glEnableVertexAttribArray(positionHandle);
    if(textureCoordinateHandle > 0){
        GLES30.glEnableVertexAttribArray(textureCoordinateHandle);
    }
    // Update the vertex buffer and texture coordinate buffer.
    FloatBuffer vertexBuffer = ByteBuffer.allocateDirect(vertices.length*4)
            .order(ByteOrder.nativeOrder())
            .asFloatBuffer()
            .put(vertices);
    vertexBuffer.position(0);
    FloatBuffer textureCoordinateBuffer = ByteBuffer.allocateDirect(textureCoordinates.length*4)
            .order(ByteOrder.nativeOrder())
            .asFloatBuffer()
            .put(textureCoordinates);
    textureCoordinateBuffer.position(0);


    // Set the vertex and texture coordinate buffer for the shaders.
    GLES30.glEnableVertexAttribArray(positionHandle);
    GLES30.glVertexAttribPointer(positionHandle, 3, GLES30.GL_FLOAT, false, 0, vertexBuffer);
    if(textureCoordinateHandle > 0){
        GLES30.glEnableVertexAttribArray(textureCoordinateHandle);
        GLES30.glVertexAttribPointer(textureCoordinateHandle, 2, GLES30.GL_FLOAT, false, 0, textureCoordinateBuffer);
    }


    // Draw the bitmap.
    GLES30.glDrawArrays(GLES30.GL_TRIANGLE_STRIP, 0, 4);

    // Disable vertex array and texture array.
    GLES30.glDisableVertexAttribArray(positionHandle);
    if(textureCoordinateHandle > 0){
        GLES30.glDisableVertexAttribArray(textureCoordinateHandle);
    }

  }
```

And here is how ```loadTexture()``` looks like:
```
 private int loadTexture(Bitmap bitmap) {
    // Generate a new texture ID
    int[] textureIds = new int[1];
    GLES30.glGenTextures(1, textureIds, 0);

    // Bind the texture
    GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, textureIds[0]);

    // Set the texture parameters
    GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D, GLES30.GL_TEXTURE_MIN_FILTER, GLES30.GL_LINEAR);
    GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D, GLES30.GL_TEXTURE_MAG_FILTER, GLES30.GL_LINEAR);
    GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D, GLES30.GL_TEXTURE_WRAP_S, GLES30.GL_CLAMP_TO_EDGE);
    GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D, GLES30.GL_TEXTURE_WRAP_T, GLES30.GL_CLAMP_TO_EDGE);

    // Load the bitmap into the texture
    GLUtils.texImage2D(GLES30.GL_TEXTURE_2D, 0, bitmap, 0);

    // Unbind the texture
    GLES30.glBindTexture(GLES30.GL_TEXTURE_2D, 0);

    // Return the texture ID
    return textureIds[0];
  }
```
```setUpRendering()``` method:
```
public void setupRendering() {
    program = GLES30.glCreateProgram();
    int vertexShader = loadShader(GLES30.GL_VERTEX_SHADER, VERTEX_SHADER);
    int fragmentShader = loadShader(GLES30.GL_FRAGMENT_SHADER, FRAGMENT_SHADER);
    GLES30.glAttachShader(program, vertexShader);
    GLES30.glAttachShader(program, fragmentShader);
    GLES30.glLinkProgram(program);
    textureCoordinateHandle = GLES30.glGetAttribLocation(program, "inputTextureCoordinate");
    samplerHandle = GLES30.glGetUniformLocation(program, "sampler");
    positionHandle = GLES30.glGetAttribLocation(program, "vPosition");
    projectionMatrixHandle = GLES30.glGetUniformLocation(program, "uProjectionMatrix");
    colorHandle = GLES30.glGetUniformLocation(program, "uColor");
  }
```
But when I'm running the app, the camera is opening as usual, but I when bring my hand near the camera, the camera screen becomes black. Need support in debugging the issue

**System information** 
I'm testing on my OnePlus9R
- Android Version: 13
- API Level: 33
- OpenGL ES: 3.2
- GPU Vendor: Qualcomm
- GPU Renderer: Adreno(TM) 650 @ 670 MHz
- Solution: Hands

**Comment by pritam-ghosh-dev** [comment]
previously the app was crashing this error 

```
FATAL EXCEPTION: GLThread 9071
         Process: com.google.mediapipe.apps.hands, PID: 28664
         java.lang.RuntimeException: glClear: GL error: 0x501
         at com.google.mediapipe.glutil.ShaderUtil.checkGlError(ShaderUtil.java:175)
         at com.google.mediapipe.components.GlSurfaceViewRenderer.renderFrame(GlSurfaceViewRenderer.java:101)
         at com.google.mediapipe.solutioncore.SolutionGlSurfaceViewRenderer.onDrawFrame(SolutionGlSurfaceViewRenderer.java:84)
         at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1605)
         at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1284)
```
The crashing issue was resolved in [this thread](https://github.com/google/mediapipe/issues/4055). But now the camera screen is becoming black.

**Comment by ayushgdev** [comment]
Hi @pritam-ghosh-dev Thanks for keeping the issues atomic in nature. 
Would you please provide the details on the following:
- when is the camera becoming black? Is it from the moment you start the camera or when hand is placed in the camera view?
- would you attach logcat if there is any error in it?

**Comment by pritam-ghosh-dev** [comment]
- The camera is becoming black only when a hand is placed in the camera view, and once the hand is put away from the camera view, it's again back to normal.
- No crash or such kind of error is appearing. Attaching logcat from the moment when hand was placed in front of the camera.
![Screenshot (1415)](https://user-images.githubusercontent.com/120572141/220541729-84167801-06b0-404e-a122-595f7fb65ad4.png)

**Comment by ayushgdev** [comment]
@pritam-ghosh-dev This is not an issue. The OpenGL is rendering a shape that is being asked for in the code. The screen is being rendered by the ` GLES30.glDrawArrays(GLES30.GL_TRIANGLE_STRIP, 0, 4);` line. If you comment it out, it will work just fine and draw the hands but will not draw any shape (as expected).
`glDrawArrays()` takes the shape it has to draw, and you specify the from and to indices which will correspond to the vertices specified using the `float[] vertices` in `drawBitmap()`. To experiment, try changing this line as 
```
GLES30.glDrawArrays(GLES30.GL_LINE_STRIP, 0, 3);
```
You will see diagonal lines drawn over the hand.

**Comment by pritam-ghosh-dev** [comment]
hi @ayushgdev thanks for the input, it helped me debugging the issue, I had to resize the bitmap before passing it. because its dimensions were too large, the triangle strips were taking the whole screen. ``` GLES30.glDrawArrays(GLES30.GL_TRIANGLE_STRIP, 0, 4);``` this part is working fine now.
So now at the wrist point a black rectangular strip is occurring, but this strip isn't taking the texture of the bitmap, i.e. the bitmap isn't getting rendered.
Attaching screenshots for current and expected behaviour.

 **Current Behaviour:**

![IMG_20230222_174828](https://user-images.githubusercontent.com/120572141/220620385-8958f4a1-629a-4774-a248-b8705a85421d.jpg)

 **Expected Behaviour:**

![Screenshot_2023-02-22-18-13-01-05_86198e2e97ee3bea02a16a96e3e7fd16](https://user-images.githubusercontent.com/120572141/220623135-73e5fead-7df5-4c78-907f-13054473f316.jpg)

I'm trying to draw the same watch bitmap in my case, which is coming as black strip. Kindly let me know what changes should I make.

**Comment by ayushgdev** [comment]
@pritam-ghosh-dev This is not a MediaPipe related issue. Although we cannot offer solution to this issue due to bandwidth crunch, you might take a look at [Android ARCore](https://developers.google.com/ar/develop/getting-started) instead of drawing a bitmap. 
It seems you are trying an app to offer a virtual try-on service. If that is the case, if you would draw a bitmap on this location, on turning your wrist, this would still render the bitmap and will not give a 3D view of the watch.

**Comment by ayushgdev** [comment]
Closing the issue due to lack of activity and the original issue was resolved.
