### ISSUE TITLE
 https://developers.google.com/mediapipe/solutions/vision/image_classifier/python

### ISSUE THREAD

**Issue by abundance-io** [google/mediapipe#4121]
### Description of issue (what needs changing)

wrong parameters  supplied to mp.Image function

### Clear description

on the page when converting from a numpy array to an mp Image the parameter for the image format should be image_format not format 

### Parameters defined

no

### Submit a pull request?

i'll try

**Comment by ayushgdev** [comment]
Thanks for highlighting the issue @abundance-io . Would you be submitted a PR for the same?

**Comment by ayushgdev** [comment]
This has been resolved in internal change. Closing the issue.
