### ISSUE TITLE
Convert landmark to blendshape.

### ISSUE THREAD

**Issue by baronha** [google/mediapipe#4122]
`mediapipe` is so great. But I still can't find a solution to convert from `mediapipe` to `blendshapes`. I need the names of point in `blendshapes` via `mediapipe`.

I found [this issue](https://github.com/google/mediapipe/issues/3421) and https://github.com/google/mediapipe/commit/ba10ae8410ce431f593c95986a230add675e5ccd.

Is there a way to apply it to `Javascript`? I'm using `Ready Player Me's 3DModel` via react-three-fiber and it's working based on `blendshapes`.

[readyplayermemodel.glb.zip](https://github.com/google/mediapipe/files/10824971/readyplayermemodel.glb.zip)

**Comment by kuaashish** [comment]
@baronha,
Thanks for the reminding the feature request, We are marking this as Duplicate of #3421 and forwarding the request internally based on other roadmaps we will let us know if any specific update on this functionality. thank you!

**Comment by baronha** [comment]
It is already public in production. I will close this issue. Thank you mediapipe's team

**Comment by HyungjoonYang** [comment]
> It is already public in production. I will close this issue. Thank you mediapipe's team

Can you tell me where can I find the link for this feature?

**Comment by Barissevilmis** [comment]
> > It is already public in production. I will close this issue. Thank you mediapipe's team
> 
> Can you tell me where can I find the link for this feature?

Class in the following link provides this functionality.

* https://developers.google.com/mediapipe/api/solutions/python/mp/tasks/vision/FaceLandmarker

You can find .task data from the following link: 

https://github.com/google/mediapipe/tree/54e4dfc853ddb6d75004a0bb79ef72dcdd8308f9/mediapipe/tasks/testdata/vision
