### ISSUE TITLE
apk execution error

### ISSUE THREAD

**Issue by zeroche72** [google/mediapipe#4129]
### OS Platform and Distribution

android

### Compiler version

colab

### Programming Language and version

python

### Android AAR (if android)

None

### Describe the problem

```shell
I made an apk file in colab just fine.
With Python + Camera + OpenCV + Colab
The apk file worked fine on the phone.

However, I did use Mediapipe for analysis.
Python+Camera+Opencv+Mediapipe+Colab
The APK file was created well in Colab, but
Doesn't run on phone.

I would like some help on this matter.

Error when applying 'import mediapipe as mp'
```

### Complete Logs

```shell
It runs on the phone, so it's unconfirmed
```

**Comment by ayushgdev** [comment]
Hello @zeroche72 
- Would you please let us know if you are using Kivy to build android apps with Python?
- Also, whcih MediaPipe solution are you building?

**Comment by zeroche72** [comment]
> Hello @zeroche72
> 
> * Would you please let us know if you are using Kivy to build android apps with Python?
> * Also, whcih MediaPipe solution are you building?

Thanks for the answer.

I compiled it from the colab site.
'https://colab.research.google.com/'

The environment is like this:
Python 3.8.10 
mediapipe 0.9.1.0

**Comment by ayushgdev** [comment]
@zeroche72 Understood, but Python code is not natively supported by Android ecosystem until you use third party solutions like [Kivy](https://kivy.org/). Hence, the ask is if you are using any such wrappers/third party libraries to bring Python to Android apk file.
Or it would be even better if you can provide a _minimal hello world app (even without MediaPipe)_ to understand how are you building the app using colab.

**Comment by zeroche72** [comment]
> 

I want to use it for pose detection.
Pose detection was successful on the desktop.

My guess is that the media pipe doesn't work properly on Android.

If you compile by activating the line below in the code
An error occurs when launching the phone.

' import mediapipe as mp '

**Comment by ayushgdev** [comment]
@zeroche72 Please use [AAR solutions](https://google.github.io/mediapipe/getting_started/android_archive_library.html) for working on Android. Python APIs **cannot** be used in Android. Also, you will need to first setup the system with Android Studio, SDK, and NDK. Please check the guide [here](https://google.github.io/mediapipe/getting_started/android.html). 
Google Colab cannot be used for creating Android apps.

**Comment by zeroche72** [comment]
> @zeroche72 Please use [AAR solutions](https://google.github.io/mediapipe/getting_started/android_archive_library.html) for working on Android. Python APIs **cannot** be used in Android. Also, you will need to first setup the system with Android Studio, SDK, and NDK. Please check the guide [here](https://google.github.io/mediapipe/getting_started/android.html). Google Colab cannot be used for creating Android apps.
> 
> Also, if you decide to explore Hands, Face Detection or Face Mesh, we have Maven packages prebuilt. So you can follow [this guide](https://google.github.io/mediapipe/getting_started/android_solutions.html) to build solutions in easier way.

I thank you for providing a lot of information from you.

My purpose is to create android app in python language.

First, I created a simple Android app using Google Colab in Python language.
An app that controls the camera has also been successful.

I'd go a step further and try using a media pipe.

Other modules can be used by importing them.
The current mission is to find information about why the MediaPipes module is failing.

**Comment by ayushgdev** [comment]
@zeroche72 Android apps cannot be created in Python natively. You will need to use Kivy for that. And frameworks like Kivy are not supported officially by MediaPipe. 
I would reiterate the ask - Please share a colab notebook with ANY minimal android app that you are creating with Python.
