### ISSUE TITLE
Datasets and Architectures

### ISSUE THREAD

**Issue by lucasvieirademiranda** [google/mediapipe#413]
Hello,

Is there a plan to release the database used for training and the architectures used to implement hand tracking? I am currently testing the algorithm in recognizing hand configurations of the Brazilian sign language and have encountered some problems. I attached some of my results for your knowledge only.

[analysis.zip](https://github.com/google/mediapipe/files/4094363/analysis.zip)

**Comment by palmloftz** [comment]
Hello, I have any question about this. 
How to normalize x, y coordination both movement and rotation of hand ? 
I have encountered this problem to gesture something from hand tracking. 
Thank you.

**Comment by fanzhanggoogle** [comment]
Hi @lucasvieirademiranda Thank you for trying the hand pipeline. Nice results! Good to hear that you are using it to solving the challenging sign language recognition! Unfortunately, we don't plan to release our dataset or training pipeline. But we do plan to release a significantly improved version of the pipeline in terms of quality in the coming months. Hope that'll help your project.
