### ISSUE TITLE
Mediapipe face mesh Jittering issue

### ISSUE THREAD

**Issue by AyishwaryaM** [google/mediapipe#4130]
Hi mediapipe developers!!
I am working on mediapipe face mesh, I am able to get face mesh with 468 landmarks properly but I am facing jittering issue ,
and for me it's very important to reduce or stabilize this jittering effect of face mesh.
I have tried many ways but not working. Below are my system specification
OS - windows11
Python 3.8
mediapipe- 0.8.11
OpenCV- 4.6.0
Though I am not making much movement but the face mesh as well as point cloud is getting jittered(shaking).

Please reply

**Comment by kuaashish** [comment]
@AyishwaryaM,
Sorry for the issue you are facing However, Jittering behaviour is expected and we already have this issue (#825) reported earlier and sill is in open status. Although, we suggest that please upgrade to latest version of mediapipe 0.9.1 and try out the calculator [LandmarksSmoothingCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/landmarks_smoothing_calculator.cc) mentioned [here](https://github.com/google/mediapipe/issues/825#issuecomment-867816841) will definitely help out to reduce the jittering as per the use case.

**Comment by AyishwaryaM** [comment]
@kuaashish ,
Is there any landmark smoothing technique like computing the moving average of the landmark coordinates ?
I tried with latest mediapipe version but it seems nothing change.

**Comment by kuaashish** [comment]
@AyishwaryaM,
We do have such smoothing technique available to reduce the jittering effect. You can find the similar implementation 
using the calculator [LandmarksSmoothingCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/landmarks_smoothing_calculator.cc) and pose_landmark example [here](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_filtering.pbtxt#L92). However, we see that smoothing technique has not been implemented in face mesh [example](https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_landmark), You may need to define that explicitly. Thanks!

**Comment by AyishwaryaM** [comment]
Do I need to do in the same way as you [LandmarksSmoothingCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/landmarks_smoothing_calculator.cc) did in pose_landmarks example ?
What changes do I need to do ?

**Comment by AyishwaryaM** [comment]
Can you please guide me How we can write the LandmarkSmoothingaCalculator for face mesh ?
I have tried but getting very confusing these calculators ?

**Comment by AyishwaryaM** [comment]
Sure, thank you for quick reply, will wait for solution!

**Comment by AyishwaryaM** [comment]
Hello, 
Can we expect now something on jittering issue ?

**Comment by AyishwaryaM** [comment]
Hello, Google mediapipe developers,
Can we expect some workable solution which resolves damping of face mesh issue ?

**Comment by kuaashish** [comment]
Hi @AyishwaryaM,

We would like to inform you that the implementation you are currently utilizing is now considered a legacy solution. It is no longer under maintenance, and support for it has been completely discontinued, as indicated on this [page](https://developers.google.com/mediapipe/solutions/guide#available_solutions).

The functionality has undergone an upgrade and is now integrated into the Face Landmarker Task API. We encourage you to explore our new Face Landmarker Task API, along with its corresponding [documentation](https://developers.google.com/mediapipe/solutions/vision/face_landmarker), and review the provided [Python examples](https://developers.google.com/mediapipe/solutions/vision/face_landmarker/python#code_example).

Additionally, we kindly request that you inform us of any similar issues related to jitter that you may encounter while using the upgraded Face Landmarker Task API.

Thank you
