### ISSUE TITLE
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed

### ISSUE THREAD

**Issue by BTLDXX-x** [google/mediapipe#4136]
### OS Platform and Distribution

android

### Programming Language and version

java

### Bazel version

5.2.0

### Android SDK and NDK versions (if android)

sdk version: 33, ndk version: 21

### Android AAR (if android)

None

### Describe the problem

```shell
hello, 
i' m following the documentation to build handtrackinggpu, but failed. 
i can run the hello world on desktop, [Installation]<https://developers.google.com/mediapipe/framework/getting_started/install#installing_on_macos>
thanks for your help
```

### Complete Logs

```shell
2 warnings generated.
INFO: SystemSuspensionEvent: Computer put to sleep
INFO: SystemSuspensionEvent: Computer woken up
ERROR: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/androidsdk/BUILD.bazel:13:25: Extracting interface @androidsdk//:dx_jar_import failed: missing input file 'external/androidsdk/build-tools/33.0.0/lib/dx.jar', owner: '@androidsdk//:build-tools/33.0.0/lib/dx.jar'
ERROR: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/androidsdk/BUILD.bazel:13:25: Extracting interface @androidsdk//:dx_jar_import failed: 1 input file(s) do not exist
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /private/var/tmp/_bazel_apple/0c483615d5b745ff81a46399bf65f611/external/androidsdk/BUILD.bazel:13:25 Extracting interface @androidsdk//:dx_jar_import failed: 1 input file(s) do not exist
INFO: Elapsed time: 4500.010s, Critical Path: 1403.83s
INFO: 2932 processes: 149 internal, 2775 darwin-sandbox, 8 worker.
FAILED: Build did NOT complete successfully
```

**Comment by ayushgdev** [comment]
Hi @BTLDXX-x This looks like a workspace setup issue. A few suggestions:
- Try recloning the repository
- Make sure you followed _each step_ of [android setup guide](https://google.github.io/mediapipe/getting_started/android.html)
- Use Android SDK 30.0.3 and Android NDK 21.1.6352462 (install via Android Studio)
- Make [this change](https://github.com/google/mediapipe/issues/3719#issuecomment-1345868251) in the WORKSPACE file

**Comment by BTLDXX-x** [comment]
@ayushgdev thanks for your reply. i'll try again

**Comment by kuangzy2011** [comment]
@BTLDXX-x ,

    Please check if you have this [issue 4128](https://github.com/google/mediapipe/issues/4128).

    I check sdk31 and sdk33, there is no  dx.jar in build-tools/xx.x.x/.

**Comment by BTLDXX-x** [comment]
i'v succeeded after making [this change](https://github.com/google/mediapipe/issues/3719#issuecomment-1345868251) in the WORKSPACE file. thank you.

**Comment by BTLDXX-x** [comment]
@kuangzy2011 , i haven't met this [issue 4128](https://github.com/google/mediapipe/issues/4128).

**Comment by ayushgdev** [comment]
Glad to hear your issue is resolved @BTLDXX-x . Shall we close the issue?
