### ISSUE TITLE
MediaPipe instance creation is taking too much time on some Android devices.

### ISSUE THREAD

**Issue by FaizanAhmadPF** [google/mediapipe#4137]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Android

### Mobile device if the issue happens on mobile device

Infinix Hot 9 Play

### Programming Language and version

Java

### MediaPipe version

Latest (0.9.1)

### Solution

FaceMesh

### Describe the actual behavior

```shell
To use MediaPipe in Android app, I am using these dependencies:
    implementation 'com.google.mediapipe:solution-core:latest.release'
    implementation 'com.google.mediapipe:facemesh:latest.release'

To get MediPipe Instance for Face Mesh:
                     new FaceMesh(
                        context,
                        FaceMeshOptions.builder()
                                .setStaticImageMode(true)
                                .setRefineLandmarks(true)
                                .setMinDetectionConfidence(0.8f)
                                .setRunOnGpu(true)
                                .build());

On average, it is taking 2 to 3 seconds to return instance of MediaPipe.
But on some other devices (e.g: Infinix Hot 9 play (Android version:10)) It is taking about 1 minute to return the instance.
Even to demo app for the face mesh (provided on this link: https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions) is also taking about 1 minute to create the instance.
```

### Describe the expected behaviour

```shell
It should provide instance for face mesh within (max) 2 to 3 seconds on each device.
```

### Standalone code/steps you may have used to try to get what you need

```shell
new FaceMesh(
                        context,
                        FaceMeshOptions.builder()
                                .setStaticImageMode(true)
                                .setRefineLandmarks(true)
                                .setMinDetectionConfidence(0.8f)
                                .setRunOnGpu(true)
                                .build());
```

**Comment by kuaashish** [comment]
@FaizanAhmadPF,
Would you please let us know the complete details and exact steps followed to reproduce the issue from our end? Thank you!

**Comment by FaizanAhmadPF** [comment]
As I attached your Demo app link, please have a look on that, that app is taking too much time on some devices to open camera.
new FaceMesh(
                        context,
                        FaceMeshOptions.builder()
                                .setStaticImageMode(true)
                                .setRefineLandmarks(true)
                                .setMinDetectionConfidence(0.8f)
                                .setRunOnGpu(true)
                                .build());
                                
This step is taking time too much on some devices & 2 to 3 seconds average on each device.

**Comment by kuaashish** [comment]
@FaizanAhmadPF,
This behaviour is expected. MediaPipe model takes significant times several 8-10 seconds to load up and start up the camera. Scenario depends on the device to device if more powerful the device is the time to pop up the camera will be minimal. (Refer: #3384) Thank you!

**Comment by FaizanAhmadPF** [comment]
Okay, can you please tell me that what is difference bwteen runOnGPU and runOnCPU (setRunOnGpu(true/false))?

**Comment by kuaashish** [comment]
@FaizanAhmadPF,
This parameter `setRunOnGpu(true/false)` defines that solution will run/inference on the GPU/CPU. You can check out the code [here](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/solutions/facemesh/src/main/java/com/google/mediapipe/examples/facemesh/MainActivity.java#L46).

**Comment by FaizanAhmadPF** [comment]
I know it will decide whether to run on GPU or CPU, but what will be effected, what will be changes occue in both cases on android devices? (e.g: speed, accuracy, smoothness etc etc.)

**Comment by kuaashish** [comment]
@FaizanAhmadPF,
Please raise a new issue with another query raised and Feel free to close if actual issue has been resolved. Thank you!
