### ISSUE TITLE
Accuracy of Shoe detection 

### ISSUE THREAD

**Issue by burungiu** [google/mediapipe#4139]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

iOS 16.3.1

### Solution

Objectron

### Programming Language and version

C#

### Describe the actual behavior

Hello, I'm using https://github.com/homuler/MediaPipeUnityPlugin (which uses google/mediapipe as core algorithm) to build a mobile application as shoe try-on. But, it has low accuracy of detection, and sometimes it doesn't detect the shoe and it's size properly.

In this video you can see the behaviour of actual solution, which I configured with minDetection (0.1-0.2) and min tracking to (0.3-0.5). Is there a way to make it work smoothly or something to improve detection?

https://user-images.githubusercontent.com/10330202/221908690-a480275f-ad1e-4f6e-807d-df2c563f9066.MP4

**Comment by ayushgdev** [comment]
Hello @burungiu 
This Unity package is not official MediaPipe package. Hence we cannot provide support for it. But you can try to switch to [Two stage objectron ](https://google.github.io/mediapipe/solutions/objectron.html#two-stage-objectron)which will affect speed but can provide better accuracy.

**Comment by LucasLCO** [comment]
@burungiu i making the same project, but i am struggling in the positioning of the shoe model inside unity coordinate system. When i start moving  the camera, it seems to lose reference of the position on where it is. Did you stumble on something like that too? Another problem that i think it is going to happen is the occlusion of leg on the shoe. I dont have any idea how i going to do that. If you could help me on those, i would be really thankful.
