### ISSUE TITLE
[Hand tracking] Simplifying it with Python

### ISSUE THREAD

**Issue by juandspy** [google/mediapipe#414]
I've seen different issues, such as [this one](https://github.com/google/mediapipe/issues/56#issuecomment-533040888), talking about importing the .tflite model directly in Python. I have more or less achieved to make inference but I'm facing some problems.

At first, the code:
```
# Image preprocessing
hand_img = tf.io.read_file(image_path)
hand_img = tf.image.decode_jpeg(hand_img, channels=3)
hand_img = tf.image.convert_image_dtype(hand_img, tf.float32)
hand_img = tf.image.resize(hand_img, [IMG_WIDTH, IMG_HEIGHT])
hand_img = hand_img.numpy()
input_img = tf.expand_dims(hand_img, 0)

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path=MODEL_PATH)
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test model on random input data.

interpreter.set_tensor(input_details[0]['index'], input_img)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])

coordinates = np.split(output_data[0], 21)
```
return 21 coordinates of X and Y, which seems to make sense:
![image](https://user-images.githubusercontent.com/42124482/72890710-d2966a00-3d12-11ea-9ed3-a7f2c75622de.png)

However, the precision is really worse in real time.
My Python:

![python](https://user-images.githubusercontent.com/42124482/72891537-bbf11280-3d14-11ea-98c6-35a92d4acdc0.gif)

Mediapipe example:
![c++](https://user-images.githubusercontent.com/42124482/72891817-62d5ae80-3d15-11ea-9a18-717771f9c33d.gif)

Mediapipe precision is absolutly impressive. 
Any key on what could be the issue? 
Is there any direct implementation of the hand tracking model in Python not using pipes?

Thanks in advance!

**Comment by sylvainblot** [comment]
@juandspy well done!
Its off topic but I used a large image, tf only accept to resize it to 256x256, how do I get back the original coordinate?
Thanks

**Comment by sylvainblot** [comment]
@juandspy well done

with a single 256x256 image I'm getting:
![mygraph](https://user-images.githubusercontent.com/1027809/73279898-09c2ba80-41ee-11ea-8efa-7dceb8f6ccc6.png)

which seems  inaccurate, any clue ?

regards

**Comment by juandspy** [comment]
Yeah. I'm also facing that inaccuracy. I'm not sure why is it. Probably the merge of HandDetection and HandLandmark in the HandTracking graph that mediapipe uses, corrects this inaccuracy.

**Comment by sylvainblot** [comment]
![mygraph](https://user-images.githubusercontent.com/1027809/73281388-34ae0e00-41f0-11ea-91b5-fa8c4368302d.png)
by rotation the image

**Comment by Michael89** [comment]
Hi, I'm also using python but I didn't get how to interpret output of model. I got values to big, biger than image size. How do you map it back to image?
for x, y, z in reshaped:
    print(x, y, z)

573.80396 1138.6875 -0.5462184
512.19476 526.3536 -17.587683
395.7162 361.91742 -63.645428
247.3991 443.3079 -111.23162
395.80304 240.30655 -126.76595
338.83054 -276.07986 24.11412
283.15622 -170.65422 -6.851598
228.72849 -276.0158 42.301826
332.07233 -460.34985 77.28722
422.06848 57.55536 -57.851364
68.32035 289.09445 -213.2822
112.70252 430.18494 -322.52512
439.9105 96.31158 -396.45728
450.60266 300.95844 -123.822266
666.96643 433.0503 -213.00067
711.6204 544.53937 239.52797
537.97314 562.55566 577.8816
324.63577 363.35474 -222.2933
568.38525 690.36237 -263.50482
628.2681 553.7078 -36.720222
608.9159 319.2119 204.9598

**Comment by sylvainblot** [comment]
Hi @Michael89 
On my side i'm providing a 256x256 image which works fine. 

If you have a big image you might want to extract the hand bounding box first to create a 256x256 image that fit the hand, at least that my approach, any other ideas are welcome :)

**Comment by Michael89** [comment]
@sylvainblot 
I'm also providing 256x256 image
actuale here is the image
![download](https://user-images.githubusercontent.com/313445/73434603-b7011400-434f-11ea-85a6-9e5537256750.png)
This is image of my hand and for it I have those numbers

**Comment by sylvainblot** [comment]
I'm getting:
```
[(67.98676, 216.81247), (48.239227, 176.49408), (48.94, 132.46643), (67.43353, 98.06007), (84.31809, 72.16643), (53.83757, 129.44159), (82.58482, 86.53169), (111.75812, 64.71044), (136.81989, 45.145515), (73.14721, 154.08087), (109.6786, 117.43848), (146.87065, 89.81086), (182.57198, 66.37898), (90.41551, 181.6039), (127.017715, 158.05835), (162.15512, 134.39056), (194.96605, 113.93574), (109.865814, 210.03871), (143.98386, 198.50995), (167.80283, 191.39081), (193.8373, 184.0172)]
```

try with that code and replace PATH_TO:
```
    image_tf_size = [256, 256]
    # Image preprocessing
    tf.enable_eager_execution()

    hand_img = tf.io.read_file(image_path)
    hand_img = tf.image.decode_jpeg(hand_img, channels=3)
    hand_img = tf.image.convert_image_dtype(hand_img, tf.float32)
    hand_img = tf.image.resize(hand_img, image_tf_size)
    hand_img = hand_img.numpy()
    input_img = tf.expand_dims(hand_img, 0)

    # Load TFLite model and allocate tensors.
    interpreter = tf.lite.Interpreter(model_path='PATH_TO/mediapipe/mediapipe/models/hand_landmark.tflite')
    interpreter.allocate_tensors()

    # Get input and output tensors.
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # Test model on random input data.

    interpreter.set_tensor(input_details[0]['index'], input_img)

    interpreter.invoke()

    # The function `get_tensor()` returns a copy of the tensor data.
    # Use `tensor()` in order to get a pointer to the tensor.
    output_data = interpreter.get_tensor(output_details[0]['index'])

    coordinates = np.split(output_data[0], 21)

    return [(c[0], c[1]) for c in coordinates]
```

result:
![result_hand](https://user-images.githubusercontent.com/1027809/73435249-93869b00-4348-11ea-86e5-d746d0b522dd.png)

**Comment by Michael89** [comment]
Hmm, thnx for help. I'm using hand_landmark_3d.tflite instead of hand_landmark.tflite I hope that they worked same way and differs only with third dimension.
Thank you for pointing that.

**Comment by Michael89** [comment]
@sylvainblot Thank you one more time, I figured out my issue. It was noob failure, I feed my image as 0..255 RGB values instead 0..1. That's why I got such big values.

**Comment by mgyong** [comment]
@Michael89 Can you provide link to your python code available for other folks to refer?
