### ISSUE TITLE
Issue loading holistic assets inside Electron app

### ISSUE THREAD

**Issue by desi-dimitrova** [google/mediapipe#4140]
When I try to load holistic from the CDN URL like this:

```holistic = new Holistic({locateFile: (file) => `https://cdn.jsdelivr.net/npm/@mediapipe/holistic/${file}`});```

I get the following error

![Screenshot 2023-03-02 133709](https://user-images.githubusercontent.com/98762671/222418237-ac27bf30-8ad1-4089-8a5f-5e95006be15b.png)

Somehow the path is changed to some of the local app path + the CDN URL... This only happens in an Electron app. If it's just a normal react app, for example, it works fine.

Is there something different I need to do in the Electron app in order to load holistic from the CDN?

**Comment by virtualsapiens** [comment]
Hi @kuaashish  wondering if there is any info on this one? Thank you.

**Comment by nskaiser** [comment]
Hi @kuaashish , was there any updates on this?

**Comment by kuaashish** [comment]
Hi @nskaiser,
Could you please elaborate your query with complete details about the issue such the steps followed to reproduce the from our end. Thank you!
