### ISSUE TITLE
New (March 2023) MediaPipe suddenly deprecates most APIs. Unclear migration path on supported APIs

### ISSUE THREAD

**Issue by nlothian** [google/mediapipe#4142]
Currently (3 March 2023) the MediaPipe documentation says:

> MediaPipe is currently in alpha at v0.7. We may be still making breaking API changes and expect to get to stable APIs by v1.0.

Since yesterday, it also says:

> Attention: Thanks for your interest in MediaPipe! We are moving to https://developers.google.com/mediapipe as the primary developer documentation site for MediaPipe starting April 3, 2023.

> This notice and web page will be removed on April 3, 2023.

Going to https://developers.google.com/mediapipe/solutions/guide we find this:

![image](https://user-images.githubusercontent.com/117304/222608625-660d8418-e96a-4f74-8938-fa210778d350.png)

Firstly (and you can ignore this but).. Wow.. WTF? [Relevant](https://steve-yegge.medium.com/dear-google-cloud-your-deprecation-policy-is-killing-you-ee7525dc05dc). 

Secondly: What is the difference between "Upgrade" vs "Upgraded" in the status column?

Thirdly: The column "New MediaPipe Solution" isn't very useful. I'd expect some kind of link to the technical documentation.

https://developers.google.com/mediapipe/api/solutions only has links for the packet format. Where is all the technical docs for eg pose detection going to go?

**Comment by ayushgdev** [comment]
Hello @nlothian 
We are deprecating support for few APIs however, MediaPipe as a whole is improving. The new APIs are more resilient and much easier to use than the current ones. 
"Upgraded" means the new replacement solution is available now and the legacy solution "has been upgraded". "Upgrade" simply means it is in the pipeline and team is working heavily on making the solutions available but it is not available for consumption yet.
New MediaPipe Solution lists the new solution name corresponding to the legacy solution it is replacing. Although, I agree the links can be added for the new solution lists and we will take it up shortly. But the new solution can still be reached (if available for consumption) via the [examples homepage](https://developers.google.com/mediapipe/solutions/examples).
