### ISSUE TITLE
 hi , the coordinate(x and y) of landmark 8 is not correct , deviate the actual location of the INDEX_FINGER_TIP,  I hope some one give me suggestion, thanks

### ISSUE THREAD

**Issue by xiaolinpeter** [google/mediapipe#4144]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

window 10

### MediaPipe version

0.8.10.1

### Solution

hands

### Programming Language and version

python

### Describe the actual behavior

```shell
the coordinate(x and y) of landmark 8 is deviate the actual location of the INDEX_FINGER_TIP, if this problem can not solved,  I will also can not solved pinch gesture
```

### Describe the expected behaviour

```shell
I hope the coordinate(x and y) of landmark 8 is more acurrate,
```

### Standalone code/steps you may have used to try to get what you need

```shell
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
@Project ：mediapipe 
@File ：demo_1.py
@Author ：xiaolin_peter
@email：zheng.xiaolin@tslsmart.com
@Date ：2023/2/22 20:47 
'''
import cv2
import mediapipe as mp

mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

# For webcam input:
cap = cv2.VideoCapture(0)
with mp_hands.Hands(
        model_complexity=0,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5) as hands:
    while cap.isOpened():
        success, image = cap.read()
        if not success:
            print("Ignoring empty camera frame.")
            # If loading a video, use 'break' instead of 'continue'.
            continue

        # To improve performance, optionally mark the image as not writeable to
        # pass by reference.
        image.flags.writeable = False
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        results = hands.process(image)

        # Draw the hand annotations on the image.
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        if results.multi_hand_landmarks:
            for hand_landmarks in results.multi_hand_landmarks:
                mp_drawing.draw_landmarks(
                    image,
                    hand_landmarks,
                    mp_hands.HAND_CONNECTIONS,
                    mp_drawing_styles.get_default_hand_landmarks_style(),
                    mp_drawing_styles.get_default_hand_connections_style())
                point4_w = hand_landmarks.landmark[4].x * 640
                point4_h = hand_landmarks.landmark[4].y * 480
                point8_w = hand_landmarks.landmark[8].x * 640
                point8_h = hand_landmarks.landmark[8].y * 480
                cv2.circle(image, (int((point4_w + point8_w) / 2), int((point4_h + point8_h) / 2)), 8, (0, 0, 255),
                           cv2.FILLED)
                cv2.line(image, (int(point4_w), int(point4_h)), (int(point8_w), int(point8_h)), (0, 255, 255), 5,
                         cv2.LINE_4)
        # Flip the image horizontally for a selfie-view display.
        cv2.imshow('MediaPipe Hands', cv2.flip(image, 1))
        if cv2.waitKey(5) & 0xFF == 27:
            break
cap.release()
```

**Comment by xiaolinpeter** [comment]
picture1:  
![image](https://user-images.githubusercontent.com/27184803/222904429-788fc8c1-305b-4e95-bb47-c86717b08faf.png)
picture2:
![image](https://user-images.githubusercontent.com/27184803/222904466-68b9fb35-19da-4ee3-9948-ac04d1597ca0.png)

I think picture1 is ok, but coordinate of picture2 is deviate the actual location

**Comment by xiaolinpeter** [comment]
https://user-images.githubusercontent.com/27184803/222904591-04b003b7-802b-43f5-8566-bd7a3314bb91.mp4

**Comment by ayushgdev** [comment]
Hello @xiaolinpeter 
It seems like it is due to the training of the model. The models are trained to _many_ of the hand orientations, but there are particular orientation and finger setup which it might be able to recognise. If you see the image below, the setup is very similar to a **fist** which is why it assumes the index finger is folded as well. 
<img width="768" alt="Screenshot 2023-03-06 at 11 13 19 AM" src="https://user-images.githubusercontent.com/118424249/223351623-4f0b187a-953e-43cf-aec7-5917bc025b66.png">

To combat this issue, I would suggest you to train the model with [tensorflow model maker ](https://www.tensorflow.org/lite/models/modify/model_maker) for such hand orientations. You might also like to experiment if  negative hard mining can add up to the accuracy with lesser training examples.

**Comment by xiaolinpeter** [comment]
> > 你好@xiaolinpeter 这似乎是由于模型的训练。这些模型针对_许多_手部方向进行了训练，但它可能能够识别特定的方向和手指设置。如果您看到下图，设置与**拳头**非常相似，这就是为什么它假设食指也折叠起来。 <img alt="屏幕截图 2023-03-06 11 13 19 AM" width="768" src="https://user-images.githubusercontent.com/118424249/223351623-4f0b187a-953e-43cf-aec7-5917bc025b66.png">
> > [为了解决这个问题，我建议您使用tensorflow model maker](https://www.tensorflow.org/lite/models/modify/model_maker)训练模型以适应这种手部方向。您可能还想试验一下，如果使用较少的训练示例，负面的硬挖掘是否可以增加准确性。
> > hi @ayushgdev thanks your suggestion, i will try your suggestion

hi @ayushgdev can you tell me dataset format of training model, thanks

**Comment by ayushgdev** [comment]
Hello @xiaolinpeter 
I checked in with the team. Unfortunately, this is not supported by model maker either.  In general Model Maker currently only supports customization of "classification-type" of Tasks. 
But we have discussed this issue internally with other members and we will look into how your reported issue can be addressed when we train our next iteration of the landmark model.

**Comment by xiaolinpeter** [comment]
> 你好@xiaolinpeter 我和团队签到。不幸的是，这也不被模型制造商支持。一般来说，Model Maker目前只支持自定义Tasks的“分类类型”。 但我们已经与其他成员在内部讨论了这个问题，我们将研究在我们训练下一次迭代的地标模型时如何解决你报告的问题。

thanks your reply

**Comment by ayushgdev** [comment]
Can we close this issue @xiaolinpeter ?

**Comment by xiaolinpeter** [comment]
> Can we close this issue @xiaolinpeter ?

ok, I'm sorry to so late to reply for you

**Comment by xiaolinpeter** [comment]
> Closing as stale. Please reopen if you'd like to work on this further.

ok, thanks
