### ISSUE TITLE
Import Numpy in Pose docs

### ISSUE THREAD

**Issue by lucifertrj** [google/mediapipe#4146]
### Description of issue (what needs changing)

import numpy as np is missing in the Pose documentation code. np is used without importing. 

### Clear description

Just a documentation fix to import the missing module. 

### Submit a pull request?

Yes, already submitted.

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,
Could you please look into this pull request https://github.com/google/mediapipe/pull/4145? Thank you!

**Comment by kuaashish** [comment]
Closing this as the issue has been merged commit [d6fb7c3](https://github.com/google/mediapipe/commit/d6fb7c365ecc21445ac4c7bbd198fa8b3ec8b758)
