### ISSUE TITLE
How to define an image module holistic_landmark_image like mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu_image.pbtxt

### ISSUE THREAD

**Issue by kuangzy2011** [google/mediapipe#4147]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### Describe the actual behavior

```shell
Refering mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu_image.pbtxt.

I want to define a holistic landmark tracking gpu image module like mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu_image.pbtxt for android project, no need to output the rendered image.

But I don't known how to mark the FINISHED tag in node FlowLimiterCalculator.
As you know,  Module HandLandmarkTrackingGpuImage returns single target hand landmark and marks FINISHED tag with "FINISHED:multi_hand_landmarks", while in module HolisticLandmarkGpu, it returns serval targets such as pose, hands and face. Is it possible to mark FINISHED tag with one of there output landmark?
    
```

**Comment by ayushgdev** [comment]
@kuangzy2011 That is an interesting question. 
If you notice the [hand_landmark_tracking_gpu_image.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu_image.pbtxt) file, `HandLandmarkTrackingGpu` calculator outputs three [outputs](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu_image.pbtxt#L109) which are useful in general scenario- `multi_hand_landmarks`, `multi_hand_world_landmarks`, `multi_handedness`. But along with it, it also gives `palm_detections`, `hand_rects` and `hand_rects_from_palm_detections` which can be used for any other purposes. So it gives 6 outputs, but the [FlowLimiterCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu_image.pbtxt#L69) only uses `multi_hand_landmarks`. 

Similarly, you can choose among `pose_landmarks`, `pose_roi`, `left_hand_landmarks`, `right_hand_landmarks` or `face_landmarks` to use in FlowLimiterCalculator. That can be design choice which landmarks you consider as driving factor for the detection- is it face, hands or complete body pose.
