### ISSUE TITLE
How to add 3d object on hand detection node.

### ISSUE THREAD

**Issue by Sonamgupta2109** [google/mediapipe#415]
Hi,

I am successfully install the app. But i can not understand how an i hide the hand detection overlay view and add my own 3d object on a specific position that i get from landmark position

**Comment by adilmubeen55** [comment]
I am having the same issue

**Comment by fanzhanggoogle** [comment]
I believe there are two questions here:
1) How to disable the rendering of hand landmarks: you can remove all the render data stream in the overlay calculator [here](https://github.com/google/mediapipe/blob/d144e564d8f48737f1bf684ee741c9ccf6a5909d/mediapipe/graphs/hand_tracking/subgraphs/renderer_gpu.pbtxt#L98)
2) How to add 3D object to the rendereing: Are you thinking of using AnnotationOverlayCalculator to render 3D objects or other approaches? It'll be better if you can elaborate more on your approaches.

**Comment by adilmubeen55** [comment]
I want to place an augmented 3D ring on specific point on the finger to be specific. So the goal is to remove landmark overlay which you just explained how to do that. But for next part I don't know what would be the best approach. If you have any suggestion I would appreciate that.

**Comment by fanzhanggoogle** [comment]
In general, you could just extract the landmarks and use any graphics library to render 3D objects. This is kind of beyond the scope of Mediapipe. Sorry that we could help more on that.

**Comment by fanzhanggoogle** [comment]
Feel free to re-open if you have further questions.

**Comment by siddharthoblix** [comment]
@adilmubeen55 Did you ever figure out how to do this?

@fanzhanggoogle I am using Unity to render the 3D model, but is there any way to get rotational information for the points/hand skeleton?

**Comment by tomermesser** [comment]
@adilmubeen55 I'm working on a similar product and I may best solution is to detect index finger using media pipe and get the vector position to render the THREE.js model on the same location. Does someone have a better solution?

**Comment by vikarshiitk** [comment]
@fanzhanggoogle  I want to put a 3D shoe model on a bare foot in AR . How to do that?
