### ISSUE TITLE
If does not use the Z axis in gesture recognition ,  can i  delete the hand_ landmark_ 3d.tflite  used to  reduce the model

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#4150]
### MediaPipe Solution (you are using)

gesture recognition

### Programming language

java

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

```shell
If does not use the Z axis in gesture recognition ,  can i  delete the hand_ landmark_ 3d.tflite  used to  reduce the model
```

### Please specify the use cases for this feature

```shell
NO
```

**Comment by kuaashish** [comment]
@chensisi0730,
Would you please elaborate your query with complete details such the platform you are using Python, Android, C++ or Other solution available in mediapipe to understand the issue better from our end. Thank you!

**Comment by chensisi0730** [comment]
@kuaashish 
Android ，thanks

**Comment by kuaashish** [comment]
@chensisi0730,
You will not be able to modify the internal graph depends on hand_landmark_3d.tflite.

Removing landmarks from the results will not prevent the overhead within the solution.

The binarypb contains the graph that tells the solution what to do. If that binarypb were modified (it's in proto3 format) and the nodes that compute these outputs were removed, the overhead would no longer exist. I'm sure you could figure this out, but we don't support this at this time. We have been experimenting with dynamically disabling sections of the graph based on options, and this might be a reasonable optimization. we will bring this up to the team, but I can't offer you a solution at this time.
