### ISSUE TITLE
Smoothing Pose World Landmarks using Landmarks Smoothing Calculator

### ISSUE THREAD

**Issue by fadiaburaid** [google/mediapipe#4151]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 10

### MediaPipe version

v0.9.1

### Solution

Holistic 

### Programming Language and version

C++

### Describe the actual behavior

Landmarks Smoothing Calculator only accepts Normalized Landmarks as input. Pose World Landmarks are not normalized so cannot be smoothed by the calculator.  If there is a solution or a way to normalize the world landmarks using another calculator, please advise.

### Describe the expected behaviour

Pose World Landmarks are useful to many in applications in my case Avatar puppeteering. It will be great if the calculator can be adapted to both types of input.

**Comment by ayushgdev** [comment]
Okay so to understand the flow of the packets, we shall start with pose_landmark_filtering.pbtxt. You can jump to last section for conclusion as well.

1. In pose_landmark_filtering.pbtxt, [LandmarksSmoothingCalculator](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmark_filtering.pbtxt#L104) is used to output filtered_landmarks, which itself is an output of SwitchContainer calculator which [takes as input filtered_visibility](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmark_filtering.pbtxt#L96) which is an output of SwitchContainer calculator which takes as input_stream the [landmarks](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmark_filtering.pbtxt#L65) coming from the pose_landmark_cpu.pbtxt. In pose_landmark_cpu.pbtxt, unfiltered_pose_landmarks are [coming as input_stream](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmark_cpu.pbtxt#L221) to the PoseLandmarkFiltering calculator which itself is an [output of PoseLandmarkByRoiCpu](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmark_cpu.pbtxt#L210). 
2. Checking the subgraph pose_landmark_by_roi_cpu.pbtxt, the required output stream [tagged as LANDMARKS](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmark_by_roi_cpu.pbtxt#L81) is coming from [PoseLandmarksAndSegmentationInverseProjection](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmark_by_roi_cpu.pbtxt#L174) calculator. Again going into this subgraph [pose_landmarks_and_segmentation_inverse_projection.pbtxt](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmarks_and_segmentation_inverse_projection.pbtxt), we can see that the subgraph's [overall output_stream landmarks](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmarks_and_segmentation_inverse_projection.pbtxt#L50) is coming from [LandmarkProjectionCalculator](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmarks_and_segmentation_inverse_projection.pbtxt#L79). The landmarks are tagged as NORM_LANDMARKS. So we will look at the input to this node. It is adjusted_landmarks which is [coming from LandmarkLetterboxRemovalCalculator](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmarks_and_segmentation_inverse_projection.pbtxt#L65). But this already intakes normalised landmarks(check [comment](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmarks_and_segmentation_inverse_projection.pbtxt#L59)). So we will follow the input to this graph. 
3. This input is [roi_landmarks](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmarks_and_segmentation_inverse_projection.pbtxt#L46) which is coming from parent of this subgraph, which is pose_landmark_by_roi_cpu.pbtxt. Searching for the node which is [outputting `roi_landmarks`](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/pose_landmark_by_roi_cpu.pbtxt#L155) gives `TensorsToPoseLandmarksAndSegmentation`.  The [overall output of this subgraph](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/tensors_to_pose_landmarks_and_segmentation.pbtxt#L72), now, is produced as landmarks tagged as LANDMARKS. Now `SplitNormalizedLandmarkListCalculator` is the calculator producing this output_stream `landmarks`, which itself [takes `all_landmarks`](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/tensors_to_pose_landmarks_and_segmentation.pbtxt#L182) as input_stream coming from `RefineLandmarksFromHeatmapCalculator`. `RefineLandmarksFromHeatmapCalculator` outputs the stream as [NORM_LANDMARKS](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/tensors_to_pose_landmarks_and_segmentation.pbtxt#L170). So this is the point we are getting the normalised output. But notice the [input_stream](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/tensors_to_pose_landmarks_and_segmentation.pbtxt#L168). It is also tagged as NORM_LANDMARKS, with variable raw_landmarks. This variable is coming as [output_stream from `TensorsToLandmarksCalculator`](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/tensors_to_pose_landmarks_and_segmentation.pbtxt#L153). 

Now if we go to this calculator c++ code, [tensors_to_landmarks_calculator.cc](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/calculators/tensor/tensors_to_landmarks_calculator.cc#L71), it quotes 
>    To output normalized landmarks, user must provide the original input image
>    size to the model using calculator option input_image_width and
>    input_image_height.

This normalisation code is [here](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/calculators/tensor/tensors_to_landmarks_calculator.cc#L183). Now if we go back to the tensors_to_pose_landmarks_and_segmentation.pbtxt, and check[ input_side_packets of the `TensorsToLandmarksCalculator`](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/tensors_to_pose_landmarks_and_segmentation.pbtxt#L157), for landmarks, we are giving the `input_image_width` and `input_image_height` as input. 
But for [world landmarks](https://github.com/google/mediapipe/blob/13d7e1a7ba4aa79a3083179f1137a1b32221b3c3/mediapipe/modules/pose_landmark/tensors_to_pose_landmarks_and_segmentation.pbtxt#L199), these side packets are not given. 
**Essentially, this is the input needed to start the normalisation of the landmarks.**

**Comment by fadiaburaid** [comment]
That is what I have been looking for, but it was very difficult to trace the flow.
You're a lifesaver, Thanks a bunch 🙏

**Comment by ayushgdev** [comment]
Always happy to help @fadiaburaid . Shall we close this issue then?

**Comment by fadiaburaid** [comment]
Yes issue resolved you may close it.
