### ISSUE TITLE
Help on post-processing of palm detection

### ISSUE THREAD

**Issue by spoonbobo** [google/mediapipe#4152]
### Description of issue (what needs changing)

Detailed description of pose detection is not described in MediapPipe Pose Model card

### Clear description

https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview I've searched online sources that states the outputs should contain 2254 arrays with each containing xywh and keypoints XY. To get this processed (post-processing) and then to fit in pose landmark model, could anyone help or provide a sample script for the post-processing of detection outputs of BlazePose, i.e. distortion, alignment as this is unclear

**Comment by kuaashish** [comment]
Hi @spoonbobo,
As from the description it is not clear the exact support you are looking from us. Would you please elaborate the query with more details to share the possible solution in the issue raised? Thanks!!

**Comment by spoonbobo** [comment]
Thanks for prompt response. My question is basically how to make use of the outputs from MediaPipe Pose Detection Model that generates [1, 2254, 12] outputs to produce an input of Pose Landmark Model. 

In Pose Detection model card, it says the input to be "Regions in the video frames where a person has been
detected. Represented as a 256x256x3 array with
aligned human full body part, centered by mid-hip in
vertical body pose and rotation distortion of (-10, 10) .
Channels order: RGB with values in [0.0, 1.0]."

Any guidance on converting [1, 2254, 12] output from detection model to fit into Pose Landmark model? Any sample script or source code could help is appreciated.
