### ISSUE TITLE
About cameraxpreview

### ISSUE THREAD

**Issue by MakeMeCookie** [google/mediapipe#4153]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Linux Ubuntu 22.04, Android 10

### MediaPipe Tasks SDK version

master

### Task name (e.g. Image classification, Gesture recognition etc.)

cameraxpreview, handtracking

### Programming Language and version (e.g. C++, Python, Java)

Java

### Describe the actual behavior

```shell
Added to cameraaxzoomratio in cameraaxpreview. When zoomratio is added, the screen magnifies. However, I would like to use buttons to enlarge and shrink the screen. Do I need to load another library?
```

### Describe the expected behaviour

```shell
I want to create a zoom code with cameraaxpreviewHelper and read the code from mainactivity to enlarge and shrink the screen.
```

### Standalone code/steps you may have used to try to get what you need

```shell
Can you tell me the details of how??
```

**Comment by ayushgdev** [comment]
@MakeMeCookie Seems like you have implemented custom zoom feature. Could you please provide how you have added the zoom code, since there is no code for zoom feature in CameraXPreviewHelper.java file?
