### ISSUE TITLE
How can I perform unit tests on entire graphs ?

### ISSUE THREAD

**Issue by TarikTaoui** [google/mediapipe#4155]
### Development OS
Linux Ubuntu 18.04

### Language
C++

### Used Solution
Pose Tracker

### Description of issue (what needs changing)
Detailed description of how to test entire graphs with GoogleTest

### Clear description
I built my own graphs that modify Pose Tracker with custom calculators. I have successfully tested the calculators using GoogleTest but it's not clear how testing entire graphs is done.

**Comment by kuaashish** [comment]
@TarikTaoui,
Would you please let us know the complete details about the issue such as  solution you are using e.g. Facemesh, Pose, Holistic or other solutions available? We suggest to fill the template as mentioned here to get the maximum relevant info to share the support you are looking from us. Thank you!

**Comment by TarikTaoui** [comment]
Hello @kuaashish 
I have edited the issue like you suggested

**Comment by kuaashish** [comment]
Hi @hadon,
Do we have any such methods to perform unit tests on the entire graphs? Could you please look into this and help out to perform the test. Thank you!

**Comment by TarikTaoui** [comment]
Hello @hadon, 
Is there a way to unit test graphs in C++ ? Would be grateful to hear from you asap, thank you very much in advance.

**Comment by najibmoumou** [comment]
I also developed my own calculators and I managed to test them well, but I didn't find a method to test the complete graph. I am stuck at that with no progress. Would appreciate to find an answer here.

**Comment by TarikTaoui** [comment]
Hello everyone,
After some research, i was able to find a way to test graphs. It is done by initializing a CalculatorGraphConfig object with your graph proto text and then initializing a CalculatorGraph object with the config.
