### ISSUE TITLE
Can't install in aarch64 archtitecture

### ISSUE THREAD

**Issue by nevzatdonum** [google/mediapipe#4157]
The mediapipe was installed into both a Windows and Ubuntu 18.04 device successfully. However, I cannot directly install to the aarch64 architecture device or cannot build in Ubuntu machine for aarch64.

What should I follow to install it into the aarch64 architecture?

**Comment by kuaashish** [comment]
@nevzatdonum,
Would you please let us know the complete error logs you are getting and steps you have followed to reproduce the issue from our end? Thank you!
