### ISSUE TITLE
Is it possible to obtain the face detection co-ordinates to android?

### ISSUE THREAD

**Issue by vivekri** [google/mediapipe#416]
I would like to get the face co-ordinates as point and the original frame feed to the frame processor. Can you please help me with this

Current i am using `myfacedetectionapp` as reference mentioned in media pipe documentation

If possible kindly please do share the code

**Comment by fanzhanggoogle** [comment]
Hi, a possible solution is to add a calculator to extract the keypoints of the detection and convert to landmarks. Then you can follow #230 to get the landmarks on Android side.
