### ISSUE TITLE
Where can I find the posetracking project training code and datasets？

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#4160]
Where can I find the posetracking project training code and datasets？

**Comment by ayushgdev** [comment]
@LMR2018 You can refer to [model card](https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview) for understanding the overview, and diversity distribution of the dataset. For details, please refer to the academic paper of [BlazePose model](https://arxiv.org/abs/2006.10204).
