### ISSUE TITLE
Provide instruction how to build or download => face_blendshapes.tflite

### ISSUE THREAD

**Issue by GeorgeS2019** [google/mediapipe#4162]
Provide instruction how to build or download =>[face_blendshapes.tflite](https://github.com/google/mediapipe/blob/ef4a8cde428a0c25fea37e8466d27703e43e0a50/mediapipe/tasks/cc/vision/face_landmarker/face_blendshapes_graph_test.cc#L50)

**Comment by andrechen** [comment]
https://storage.googleapis.com/mediapipe-assets/face_blendshapes.tflite ?

**Comment by kuaashish** [comment]
Hi @andrechen, Community contributions are always welcome. 
@GeorgeS2019 Thank you for the brining this issue to our notice. We are forwarding issue internally and will let you know the if any specific update will receive on this request. Thank you!

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,
We see that as reported here, Documentation to build/ download for the [face_blebdshapes.tflite](https://github.com/google/mediapipe/blob/ef4a8cde428a0c25fea37e8466d27703e43e0a50/mediapipe/tasks/cc/vision/face_landmarker/face_blendshapes_graph_test.cc#L50) has been not included in the guide. Could you please look into this issue and can make possible to include this on the documentation. Thank you!

**Comment by fadiaburaid** [comment]
Hi @kuaashish @schmidt-sebastian 
Could you also please also provide a model card with the details about the training data used? Was it trained on Human data or Synthetic data because from the results I am getting it seems like the model cannot generalize to different face geometries. Using Synthetic data from photo realistic facial rigs could improve results as data can be augmented easily in term of expressions, distance from camera, camera angles, etc.
Thank you

**Comment by GeorgeS2019** [comment]
@fadiaburaid 
If I understand correctly, the heavy lifting is already done by the original FaceMesh. 
The blendshapes simply translate the heavy lifting into an industry format e.g. used by ReadyPlayer.me

**Comment by fadiaburaid** [comment]
@GeorgeS2019 
Yes, you are correct. However, if the blendshapes regression model is not trained on enough and different faces, it will not generalize because of differences in face geometry between people. Which is apparent in the results I am getting.

**Comment by GeorgeS2019** [comment]
@fadiaburaid 
The dev team could need your feedback.
I am independent.
Could you show e.g. Gif and provide feedback to them?

**Comment by SpookyCorgi** [comment]
https://user-images.githubusercontent.com/37282156/224924624-364aa43f-428f-40c7-b2bb-b19e6fe3291a.mov

Really really excited when this becomes production level.
I quickly tested the model on my own browser tools and use it to pilot some avatars.
I basically took the refined landmarks from face_mesh, scale it by image then input the landmarks into the tflite file using tfjs-tflite.

Working
- The model seems really sensitive and accurate when moved slowly (testing by personally making faces with webcam).
Not working
- The output is really jumpy which require a lot of smoothing afterward. Having a confidence output for each blendshape might be helpful in this case.
- The value is really off with face turning by a little

But again I'm a web dev but not ml dev so I might be using the model in the optimal way.

**Comment by GeorgeS2019** [comment]
@fadiaburaid 
> scale it by image 

This could be relevant !

**Comment by GeorgeS2019** [comment]
@andrechen  could you please share your experience? Really appreciate.

**Comment by GeorgeS2019** [comment]
@SpookyCorgi
The relative position of webcam or android phone ( made possible with mediapipe) needs to be fixed  - right in front of the face. No head turning away from the camera.

![image](https://user-images.githubusercontent.com/49812372/224928586-4360cb6b-2e8e-4438-95cd-95aa32dccacc.png)

**Comment by fadiaburaid** [comment]
https://user-images.githubusercontent.com/28487342/224942427-7834595a-2ce9-494f-8990-1868d84bd224.mp4

I fed the normalized face landmarks from face_mesh to the model and used the output to control the face rig. These are the results from Unity using TF Lite Unity plugin.
The head rotations are calculated from the landmarks directly not the blendshapes. You can see the how the face is deformed from the original face at the beginning of the clip. I got the same results using webcam. 
I tried to smooth the landmarks before feeding them to the model to reduce the jitter, but errors in blendshapes tend to increase.
I also notice the eyes don't really move and this could be due to the training data used.

**Comment by GeorgeS2019** [comment]
@fadiaburaid 
you could see the avatar face provided by @SpookyCorgi is not distorted

**Comment by fadiaburaid** [comment]
https://user-images.githubusercontent.com/28487342/224958475-8359b680-4cd2-495a-9483-f715b4cbb451.mp4

Yes !!!
I am getting better results after scaling the landmarks by the image size.

**Comment by GeorgeS2019** [comment]
Image Size is essential!!!!

![image](https://user-images.githubusercontent.com/49812372/224959834-895eb413-c8f2-45d4-9ada-8b379db398ed.png)

**Comment by jays0606** [comment]
They released their update in the official documentation. 
https://developers.google.com/mediapipe/solutions/vision/face_landmarker

**Comment by jeremmoore** [comment]
> https://storage.googleapis.com/mediapipe-assets/face_blendshapes.tflite https://storage.googleapis.com/mediapipe-assets/face_blendshapes_generated_graph.pbtxt https://storage.googleapis.com/mediapipe-assets/face_blendshapes_in_landmarks.prototxt https://storage.googleapis.com/mediapipe-assets/face_blendshapes_out.prototxt
> 
> haven't tried yet.

I have tested the tflite model using the data from prototxt and found that the inference value  is slightly different from the expected value of face_blendshapes_out.prototxt. Meanwhile, the quality of expression driven is worser than the mediapipe python solution, especially the driven of eyes. Does anyone meet the same problem?
