### ISSUE TITLE
I was wondering how I could get the 3d coordinates of a pose like shown In an example on Googles website

### ISSUE THREAD

**Issue by ItalcSeal** [google/mediapipe#4168]
https://user-images.githubusercontent.com/95347559/224527343-6a7a310c-8b31-4e23-bc5a-69dda8788365.mp4

**Comment by ayushgdev** [comment]
@ItalcSeal Would you please let us know which language you are working on?

**Comment by ItalcSeal** [comment]
I am working with python

**Comment by ayushgdev** [comment]
You can access world landmarks in Python as below:

```
results = pose.process(img)
            
if results.pose_world_landmarks:
     # do something here
```
