### ISSUE TITLE
I am working on mediapipe's hair segmentation on android. I want it to take image input instead of video frames. How can I do that?

### ISSUE THREAD

**Issue by keshavoct98** [google/mediapipe#417]

**Comment by afsaredrisy** [comment]
[Mediapipe Hand tracking with Bitmap Image input](https://github.com/afsaredrisy/MediapipeHandtracking_GPU_Bitmap_Input)

You can try above repository, You can apply same changes to segmentation app.

**Comment by fanzhanggoogle** [comment]
Feel free to reopen if there's follow up questions.

**Comment by sobhan87068** [comment]
hello @afsaredrisy,
i tried to use your code with the latest mediapipe version but i am not able to get it to work properly.
the SurfaceView remains blank and there seems to be no detection.
Are there any changes needed to be done to make it compatible with the latest version? am i doing something wrong?

**Comment by MukeshBlippar** [comment]
> [Mediapipe Hand tracking with Bitmap Image input](https://github.com/afsaredrisy/MediapipeHandtracking_GPU_Bitmap_Input)
> 
> You can try above repository, You can apply same changes to segmentation app.

Hi @afsaredrisy , i checked this repository. Can you please tell me where to add this code ? Should i replace this last folder by yours?
mediapipe\examples\android\src\java\com\google\mediapipe\apps\handtrackinggpu. 

I see in original mediapipr repo menifext files are added under  \mediapipe\examples\android\src\java\com\google\mediapipe\apps\basic, but in your repo this comes inside \handtrackinggpu. So i am confused. Please tell me all the configurations i should do to use your code. Would be great if you can add the set up process in your ReadMe in your repo. That will be great useful. Thanks in advance

**Comment by MukeshBlippar** [comment]
> [Mediapipe Hand tracking with Bitmap Image input](https://github.com/afsaredrisy/MediapipeHandtracking_GPU_Bitmap_Input)
> 
> You can try above repository, You can apply same changes to segmentation app.

Does it work with medipapipe AAR or i need to replace handtrackinggpu dir with your source code in original mediapipe repo??

**Comment by afsaredrisy** [comment]
> > [Mediapipe Hand tracking with Bitmap Image input](https://github.com/afsaredrisy/MediapipeHandtracking_GPU_Bitmap_Input)
> > You can try above repository, You can apply same changes to segmentation app.
> 
> Does it work with medipapipe AAR or i need to replace handtrackinggpu dir with your source code in original mediapipe repo??

You can find [MainActivity](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic) in this directory, So you need to paste files in the same directory and accommodate main activity changes, I am not sure about latest changes in MainActivity, haven't try since long time but you will be easily able to find the changes and manually merge MainActivity

**Comment by MukeshBlippar** [comment]
> > > [Mediapipe Hand tracking with Bitmap Image input](https://github.com/afsaredrisy/MediapipeHandtracking_GPU_Bitmap_Input)
> > > You can try above repository, You can apply same changes to segmentation app.
> > 
> > 
> > Does it work with medipapipe AAR or i need to replace handtrackinggpu dir with your source code in original mediapipe repo??
> 
> You can find [MainActivity](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic) in this directory, So you need to paste files in the same directory and accommodate main activity changes, I am not sure about latest changes in MainActivity, haven't try since long time but you will be easily able to find the changes and manually merge MainActivity. 

Thanks for your reply. Now i am getting this error. My preview remains black. 
2021-08-19 19:40:37.264 18933-19175/co.introtuce.mediapipesegmentationgradle D/BmpProducer: Writing frame
2021-08-19 19:40:41.588 18933-19175/co.introtuce.mediapipesegmentationgradle D/BitmapConverter: New Frame
2021-08-19 19:40:55.587 18933-19175/co.introtuce.mediapipesegmentationgradle W/MessageQueue: Handler (android.os.Handler) {fb0309d} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {fb0309d} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:561)
        at android.os.Handler.enqueueMessage(Handler.java:754)
        at android.os.Handler.sendMessageAtTime(Handler.java:703)
        at android.os.Handler.sendMessageDelayed(Handler.java:673)
        at android.os.Handler.post(Handler.java:403)
        at co.introtuce.mediapipesegmentationgradle.imageinput.BitmapConverter$RenderThread.onFrame(BitmapConverter.java:168)
        at co.introtuce.mediapipesegmentationgradle.imageinput.BitmapConverter.onFrame(BitmapConverter.java:84)
        at co.introtuce.mediapipesegmentationgradle.imageinput.BmpProducer.run(BmpProducer.java:40)

**Comment by MukeshBlippar** [comment]
> hello @afsaredrisy,
> i tried to use your code with the latest mediapipe version but i am not able to get it to work properly.
> the SurfaceView remains blank and there seems to be no detection.
> Are there any changes needed to be done to make it compatible with the latest version? am i doing something wrong?

Facing same problem. Have you find any solution yet?
