### ISSUE TITLE
Can BlazePose model realize multi-person recognition and tracking?

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#4172]
Can BlazePose model realize multi-person recognition and tracking?

**Comment by hell-lord** [comment]
MediaPipe Pose is a single-person pose estimation framework

**Comment by ayushgdev** [comment]
Hello @LMR2018 
BlazePose model can only detect single person from a image/video frame cropped to contain only one person. 
If you check page 4->Attributes section of [Pose Model Card](https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview), you will find the following information:
> Human Full-body cropped from the captured frame should contain a single person placed in the center of the image.
