### ISSUE TITLE
Reading image numpy data from a video frame into Mediapipe 

### ISSUE THREAD

**Issue by ctippur** [google/mediapipe#4173]
0

I have a requirement to read a frame output of opencv in Mediapipe. I am using Mediapipe latest version 0.9.1.0.

I am trying to seek a frame in the opencv video input and

```
import mediapipe as mp
import cv2
cap = cv2.VideoCapture(videopath)
cap.set(cv2.CAP_PROP_POS_FRAMES,10)
ret, frame = cap.read()
mp_image = mp.Image(format=mp.ImageFormat.SRGB, data=frame)
```
I get an error:
```
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. mediapipe.python._framework_bindings.image.Image(image_format: mediapipe::ImageFormat_Format, data: numpy.ndarray[numpy.uint8])
    2. mediapipe.python._framework_bindings.image.Image(image_format: mediapipe::ImageFormat_Format, data: numpy.ndarray[numpy.uint16])
    3. mediapipe.python._framework_bindings.image.Image(image_format: mediapipe::ImageFormat_Format, data: numpy.ndarray[numpy.float32])
 ```
I am trying to follow the document here https://developers.google.com/mediapipe/solutions/vision/object_detector/python#video_1

Appreciate any pointers on what I am doing wrong.

**Comment by ctippur** [comment]
Any update on this please? I tried downgrading the version to mediapipe==0.8.10 with the same result.

**Comment by kuaashish** [comment]
@ctippur,
Would you please let us know the operating system you are using, Python environment using such as Jupyter, Annaconda, Colab etc? We recommend to fill the as mentioned [here](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=build.install_issue_template.yaml) to get the maximum relevant information to look into the problem you are facing. Thank you!

**Comment by shawnpark07** [comment]
It seems `input_format` (not `format`) is the right argument.
`mp_image = mp.Image(inpur_format=mp.ImageFormat.SRGB, data=frame)` makes it work for me

**Comment by ctippur** [comment]
I am working on a Mac on a Jupyter notebook.

**Comment by ctippur** [comment]
@shawnpark07 Thank you! That seem to work indeed. Looks like the documentation needs to be corrected. https://developers.google.com/mediapipe/solutions/vision/object_detector/python#video_1

**Comment by kuaashish** [comment]
@ctippur,
Could you please confirm that you are able to set up the python as mentioned [here](https://developers.google.com/mediapipe/solutions/setup_python) to import the medaipipe and vision as mentioned [here](https://developers.google.com/mediapipe/solutions/vision/object_detector/python)? However, We see that information shared is not sufficient to reproduce the issue from our end and we recommend to fill the [template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=build.install_issue_template.yaml) to get the additional info. Thank you!

**Comment by ctippur** [comment]
@kuaashish - Yes. I have followed the mediapipe setup guide to import mediapipe and vision. I will rephrase the question to include the complete code snippet.
Also, @shawnpark07 answer resolved my issue. We can close this now.

**Comment by kuaashish** [comment]
@ctippur,
Thank you for the confirmation, Marking this to close status as the issue has been resolved.
