### ISSUE TITLE
Fail to initialize gesture recognizer

### ISSUE THREAD

**Issue by Dakyz** [google/mediapipe#4178]
I have started to explore mediapipe libs and projects. So I've found [sample one](https://github.com/googlesamples/mediapipe/tree/main/examples/gesture_recognizer/android). If start gesture recognizer app on arm64-v8a device everything is OK. But starting on armeabi-v7a device (Android version is the same and equals to 11) makes facing to some problems:
```
E/tflite: The supplied buffer is not 4-bytes aligned
E/tflite: The model allocation is null/empty
E/native: E20221114 20:29:51.589087  3371 graph.cc:472] Could not build model from the provided pre-loaded flatbuffer: The model allocation is null/empty
W/System.err: com.google.mediapipe.framework.MediaPipeException: unknown: Could not build model from the provided pre-loaded flatbuffer: The model allocation is null/empty
W/System.err:     at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
W/System.err:     at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:336)
W/System.err:     at com.google.mediapipe.tasks.core.TaskRunner.create(TaskRunner.java:71)
W/System.err:     at com.google.mediapipe.tasks.vision.gesturerecognizer.GestureRecognizer.createFromOptions(GestureRecognizer.java:194)
W/System.err:     at com.google.mediapipe.examples.gesturerecognizer.GestureRecognizerHelper.setupGestureRecognizer(GestureRecognizerHelper.kt:95)
W/System.err:     at com.google.mediapipe.examples.gesturerecognizer.GestureRecognizerHelper.<init>(GestureRecognizerHelper.kt:50)
W/System.err:     at com.google.mediapipe.examples.gesturerecognizer.fragment.CameraFragment.onViewCreated$lambda-4(CameraFragment.kt:147)
W/System.err:     at com.google.mediapipe.examples.gesturerecognizer.fragment.CameraFragment.$r8$lambda$xiZI6LDAjMBw-J7vyrjSe_CLWo0(Unknown Source:0)
W/System.err:     at com.google.mediapipe.examples.gesturerecognizer.fragment.CameraFragment$$ExternalSyntheticLambda13.run(Unknown Source:2)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
E/GestureRecognizerHelper 56784282: MP Task Vision failed to load the task with error: unknown: Could not build model from the provided pre-loaded flatbuffer: The model allocation is null/empty
```
I guess the error depends on [device arch](https://android.googlesource.com/platform/external/tensorflow/+/refs/heads/android-s-beta-5/tensorflow/lite/model_test.cc#91). I've asked the same issue there but was redirected here. What can you advice in this sutation?

**Comment by ayushgdev** [comment]
Hello @Dakyz Thanks for trying out the MediaPipe tasks API. 
Would you please let us know complete steps to reproduce the issue at our end?
Also, we request the details of the device you are using to run the sample code.

**Comment by Dakyz** [comment]
Ok. I try to run [sample app](https://github.com/googlesamples/mediapipe/tree/main/examples/gesture_recognizer/android) on Vuzix Blade 2 ( Android 11, armeabi-v7a). I have already run some mediapipe examples on this device ([this one](https://github.com/google/mediapipe/tree/master/mediapipe/java/com/google/mediapipe/solutions/hands)) and everything was fine. Can't figured out what to do in this situation.

**Comment by ayushgdev** [comment]
Hello @Dakyz We are able to replicate this issue. Please allow us sometime to find a quick resolution for this issue, while we can prioritise it for permanent fix in the future release.

**Comment by shubham0204** [comment]
@ayushgdev I'm facing a similar error with the [Hand Landmarker](https://github.com/googlesamples/mediapipe/tree/main/examples/hand_landmarker) sample on Galaxy M13 (Android 13, armeabi-v7a).

**Comment by ayushgdev** [comment]
@jiuqiant Would you please check this issue?

**Comment by shubham0204** [comment]
@jiuqiant I was not aware of the fix. The `task` works correctly when downloaded from `https://storage.googleapis.com/mediapipe-assets/hand_landmarker.task?generation=1677051718270846` instead of `https://storage.googleapis.com/mediapipe-assets/hand_landmarker.task`.
I was following the [googlesamples/mediapipe/hand_landmarker](https://github.com/googlesamples/mediapipe/tree/main/examples/hand_landmarker) sample which was using the latter URL for downloading the `.task` file in `download_tasks.gradle`.

**Comment by Dakyz** [comment]
@jiuqiant Yes, it helps thanks!
