### ISSUE TITLE
How to normalize x, y coordination value in case movement and rotation it ?

### ISSUE THREAD

**Issue by palmloftz** [google/mediapipe#418]
How to normalize x, y coordination value in case movement and rotation it ? 
So I can get it to gesture something with any models. 

Thanks for your answer.

**Comment by fanzhanggoogle** [comment]
Hi @palmloftz I don't really get your question, could you elaborate on more detail? What do you mean by "movement and rotation it"?

**Comment by palmloftz** [comment]
Yes, I'm meaning to movement when x and y value was changed.  If I had dataset that collected x and y value both 21 key points with label.  So I can't prediction hand pose from x and y cause was changed by movement or rotation hand.

**Comment by fanzhanggoogle** [comment]
Hi, really sorry, but I still doesn't quite get your question.
Could you re-phrase it a bit or give an example? Thank you!
