### ISSUE TITLE
This will fix the multiple typos in the new tasks repo.

### ISSUE THREAD

**Issue by kuaashish** [google/mediapipe#4181]
### Clear description

This will fix the multiple typos in the new tasks repo here https://github.com/google/mediapipe/tree/master/mediapipe/tasks

### Submit a pull request?

Submitted a CL

**Comment by Neilblaze** [comment]
Is this up for grabs?

**Comment by Neilblaze** [comment]
@kuaashish Is this up for grabs?

**Comment by kuaashish** [comment]
@Neilblaze,
Yes, This fixes have been merged internally. Closing this issue now. Thank you!
