### ISSUE TITLE
how to got the face feature keypoints for the half face?

### ISSUE THREAD

**Issue by kt-rax** [google/mediapipe#4187]
Is there any one know that the mp could work correctly W/ half faces pictures input ?

**Comment by ayushgdev** [comment]
Hello @kt-rax 
MediaPipe will not work properly with half face inputs. It will be a hit and miss scenario, with mostly misses. If you will check the [Model card for face mesh](https://drive.google.com/file/d/1QvwWNfFoweGVjsXF3DXzcrCnz-mx-Lha/preview), on page 2 in Inputs section, you can find it quoted:
> Videos should be captured in "selfie" mode. As such, it's not suitable for detecting faces:
> - looking away from the camera (more than 80°),
> - inclined from the vertical orientation (more than 8°),
> - only partially visible (less than 50% of the face),
