### ISSUE TITLE
where is the center of head, as origin of z value in facial landmarks?

### ISSUE THREAD

**Issue by flydragon2018** [google/mediapipe#4193]
I try to get the  real world  depth of face to camera , based on the facial keypoints from mediapipe face mesh.

what is the physical position It means to?

**Comment by flydragon2018** [comment]
It doesn't matter  with what platform/language.  Could you please explain what the center is ? or hwo to Get It ?
where the document just mententions as a CENTER.

**Comment by ayushgdev** [comment]
@flydragon2018 The center is not static and not defined as in any anatomical terms. The Face Mesh research paper in page 2 describes the center as 
>  The z-coordinates are interpreted as the depth relative to a reference plane passing through the mesh’s center of mass.

The z-coordinate calculation is being done in [geometry_pipeline.cc](https://github.com/google/mediapipe/blob/331692577e8f9bd77d239519ca28657ce4148d83/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc#L280) file.  This is being called from EstimateFaceGeometry in [geomtry_pipeline.cc](https://github.com/google/mediapipe/blob/331692577e8f9bd77d239519ca28657ce4148d83/mediapipe/modules/face_geometry/libs/geometry_pipeline.h#L50). The center of mass is related to the curvature of the face mesh, which is governed by the weights of the landmarks. The weights are defined [here](https://github.com/google/mediapipe/blob/331692577e8f9bd77d239519ca28657ce4148d83/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt#L16)

**Comment by flydragon2018** [comment]
> @flydragon2018 The center is not static and not defined as in any anatomical terms. The Face Mesh research paper in page 2 describes the center as
> 
> > The z-coordinates are interpreted as the depth relative to a reference plane passing through the mesh’s center of mass.
> 
> The z-coordinate calculation is being done in [geometry_pipeline.cc](https://github.com/google/mediapipe/blob/331692577e8f9bd77d239519ca28657ce4148d83/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc#L280) file. This is being called from EstimateFaceGeometry in [geomtry_pipeline.cc](https://github.com/google/mediapipe/blob/331692577e8f9bd77d239519ca28657ce4148d83/mediapipe/modules/face_geometry/libs/geometry_pipeline.h#L50). The center of mass is related to the curvature of the face mesh, which is governed by the weights of the landmarks. The weights are defined [here](https://github.com/google/mediapipe/blob/331692577e8f9bd77d239519ca28657ce4148d83/mediapipe/modules/face_geometry/data/geometry_pipeline_metadata_landmarks.pbtxt#L16)

thanks for your reply.
