### ISSUE TITLE
Web solution: HandGestureRecognizer example not working https://codepen.io/mediapipe-preview/pen/zYamdVd

### ISSUE THREAD

**Issue by rmajasol** [google/mediapipe#4198]
### Description of issue (what needs changing)

Codepen example provided not working

### Clear description

When i press "enable webcam" button it does not show landmarks

### Raises listed and defined

when i inspect console, it throws errors like this: "Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'nonce-UfAlr5tGHHk=' cpwebassets.codepen.io *.appcues.com *.buysellads.com *.carbonads.com *.carbonads.net *.filestackapi.com *.firebaseio.com *.paypal.com *.paypalobjects.com *.braintreegateway.com *.stripe.com *.wufoo.com wufoo.com www.google.com www.gstatic.com". Either the 'unsafe-inline' keyword, a hash ('sha256-FDyPg8CqqIpPAfGVKx1YeKduyLs0ghNYWII21wL+7HM='), or a nonce ('nonce-...') is required to enable inline execution.  t @ VM9:1"

**Comment by ayushgdev** [comment]
Hello @rmajasol 
Thanks for this request. Would you please provide details on the OS and the browser along with its version you are using to check this demo?
