### ISSUE TITLE
Moving landmarks to change facial expression

### ISSUE THREAD

**Issue by Caroljpeg** [google/mediapipe#4199]
Hey there!
I'm working on a digital art project for school and I would like to be able to change the facial expression of the person looking at the camera.
Right now I succesfully managed to map the texture of my face on the 3d mesh generated by mediapipe: I was wondering if anyone know how I can move some of the landmarks of the mesh (in order, for example to distort the mapped texture in a smile).
I'll provide my code down below.
Any help will be much appreciated! Thank you!
[Project.zip](https://github.com/google/mediapipe/files/11063764/Project.zip)

**Comment by kuaashish** [comment]
Hi @Caroljpeg, 
Could you please elaborate your query with complete details. thank you
