### ISSUE TITLE
Error occurd when create Xcode project using Tulsi

### ISSUE THREAD

**Issue by QingyueMeng** [google/mediapipe#42]
Hi, Thanks for your great job. But when I installed the Tulsi and then tried to generate the Xcode project, I got the following error :

![image](https://user-images.githubusercontent.com/33691506/63514621-966c9c80-c51b-11e9-8960-6b77712fb1ec.png)

Any ideas about it ? Or anything I can do ? Looking forward your reply!

**Comment by Eriie** [comment]
Hi,
I had the same problem, I tried many things and probably installing [python](https://www.python.org/downloads/release/python-374/) solved it

**Comment by mgyong** [comment]
@camillol @chuoling @jiuqiant 
Camillol - pls see this Tulsi related issue

**Comment by camillol** [comment]
This is not actually Tulsi-related, it's Bazel failing when fetching external dependencies. In this case, local_config_git is actually required by TensorFlow.
Try a command line build, maybe it will display a better error message.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
