### ISSUE TITLE
Mediapipe Hair Color using Slider error

### ISSUE THREAD

**Issue by SwatiModi** [google/mediapipe#420]
I was trying to do this, as suggested in your latest comment from this issue thread https://github.com/google/mediapipe/issues/18 ,by setting flip_vertically: true in the graph , I was able to fix the invert issue.

Also about the Color Slider, It does not work but when I set the r/g/b packets to hardcode a single color when calling addConsumablePacketToInputStream(). How to fix this ?

**Comment by PrinceP** [comment]
@SwatiModi Fixed and working at https://github.com/PrinceP/mediapipe
Just modified #18 sandipan1 work.

**Comment by SwatiModi** [comment]
It works, Thanks.

**Comment by LarryBrinzo** [comment]
@PrinceP @SwatiModi @mcclanahoochie Unable to find this repository on GitHub. Can you please help.

**Comment by SwatiModi** [comment]
Hi @LarryBrinzo, I feel the orignal repo by @PrinceP has been deleted.
You can find the relevant files [here](https://drive.google.com/drive/folders/1Lb5SAE7viBujRluVB4oBAn2vwCz2LyAg?usp=sharing)

**Comment by LarryBrinzo** [comment]
Thanks a lot @SwatiModi

**Comment by khmaies5** [comment]
i added those files to the project and added ColorSliderCalculator.cc to the build folder but i got this error in android studio 

`ERROR: /home/khmaies/mediapipe/mediapipe/calculators/image/BUILD:212:24: no such target '//mediapipe/gpu:scale_mode_py_pb2_genproto': target 'scale_mode_py_pb2_genproto' not declared in package 'mediapipe/gpu' defined by /home/khmaies/mediapipe/mediapipe/gpu/BUILD and referenced by '//mediapipe/calculators/image:image_transformation_calculator_py_pb2_genproto'
ERROR: /home/khmaies/mediapipe/mediapipe/calculators/image/BUILD:212:24: no such target '//mediapipe/gpu:scale_mode_py_pb2': target 'scale_mode_py_pb2' not declared in package 'mediapipe/gpu' defined by /home/khmaies/mediapipe/mediapipe/gpu/BUILD and referenced by '//mediapipe/calculators/image:image_transformation_calculator_py_pb2'
`

**Comment by ya332** [comment]
> Hi @LarryBrinzo, I feel the orignal repo by @PrinceP has been deleted. You can find the relevant files [here](https://drive.google.com/drive/folders/1Lb5SAE7viBujRluVB4oBAn2vwCz2LyAg?usp=sharing)

@SwatiModi , Can you share the repo? 

I am getting the following error ` ColorSliderCalculator; Unable to find Calculator "ColorSliderCalculator" Tag "RGB_OUT" index 0 was not expected.`

```
FATAL EXCEPTION: ExternalTextureConverter
01-11 20:52:37.352  8544  9546 E AndroidRuntime: Process: com.google.mediapipe.apps.hairsegmentationgpu, PID: 8544
01-11 20:52:37.352  8544  9546 E AndroidRuntime: com.google.mediapipe.framework.MediaPipeException: unknown: ValidatedGraphConfig Initialization failed.
01-11 20:52:37.352  8544  9546 E AndroidRuntime: No registered object with name: ColorSliderCalculator; Unable to find Calculator "ColorSliderCalculator"
01-11 20:52:37.352  8544  9546 E AndroidRuntime: RecolorCalculator::GetContract failed to validate: 
01-11 20:52:37.352  8544  9546 E AndroidRuntime: For input streams ValidatePacketTypeSet failed:
01-11 20:52:37.352  8544  9546 E AndroidRuntime: Tag "RGB_OUT" index 0 was not expected.
01-11 20:52:37.352  8544  9546 E AndroidRuntime: 	at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
01-11 20:52:37.352  8544  9546 E AndroidRuntime: 	at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:324)
01-11 20:52:37.352  8544  9546 E AndroidRuntime: 	at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:553)
01-11 20:52:37.352  8544  9546 E AndroidRuntime: 	at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:421)
01-11 20:52:37.352  8544  9546 E AndroidRuntime: 	at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:439)
01-11 20:52:37.352  8544  9546 E AndroidRuntime: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:403)
01-11 20:52:37.352  8544  9546 E AndroidRuntime: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:338)
01-11 20:52:37.352  8544  9546 E AndroidRuntime: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source:4)
01-11 20:52:37.352  8544  9546 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-11 20:52:37.352  8544  9546 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-11 20:52:37.352  8544  9546 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
01-11 20:52:37.352  8544  9546 E AndroidRuntime: 	at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
```
