### ISSUE TITLE
Where is the new task api document and example?

### ISSUE THREAD

**Issue by endink** [google/mediapipe#4202]
How can is use task api in C++? Is there any example  for that?

**Comment by kuaashish** [comment]
Hello @endink,
we are marking this as a feature request, However, we see that this is in our roadmap but can not provide the timeline to be available [here](https://developers.google.com/mediapipe/solutions/tasks) in the guide. We will let you know once will receive any specific update on the request. Thank you!

**Comment by endink** [comment]
Thanks, I tried new API in C++( TaskRunner ) , get a run files error, I think this is an error about ModelAsset, no document, so I have to back to the old solution. I also tried the new builder API, it is worked well, its so cool. We can finally generate graph dynamically with c++ code. 

Thanks for your great work! I am waiting the document😜

**Comment by schmidt-sebastian** [comment]
We currently do not have any public documentation (and unfortunately no timeline), but we might be able to answer some specific questions if you have them. I would also advise you to look at our test cases, which show some of the usage.

**Comment by endink** [comment]
Okay, I'll close this issue for now, I'll post a new issue if there is a question.

 Thanks for your reply, mediapipe is a cool project 😄 .
