### ISSUE TITLE
Challenge in Mediapipe's Windows build due to EXTERNAL unsolved issue transferring from Tensorflow  

### ISSUE THREAD

**Issue by GeorgeS2019** [google/mediapipe#4203]
# Update 31st March 2023
Since filing this issue, it is great to see many commits have been done to improve the reliability of building in windows

<details>

# Update 27th March 2023

Confirm, VS2019 solves many unsolved Windows build issues discussed in tensorflow, Bazel and mediapipe. Windows mediapipe building using e.g. MSYS2, MSVC is confusing with untested guidelines AND will continue to lead to frustration when building in Windows. 

With [VS2019](https://github.com/andrechen/mediapipe/tree/master/visualstudio), Windows building will no longer be an experimental waste of time.

@andrechen took THREE weeks
@GeorgeS2019 I wasted ONE week before identifying @andrechen 's workable Windows build VS2019 solution

<details>
<summary>Previous discusisons</summary>
### OS Platform and Distribution

Windows 11

### Compiler version

MSVC and GCC (MSYS2)

### Programming Language and version

c++

### MediaPipe version

0.91 and above

### Bazel version

5.2

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.x

#### March 2023
#[ Can you provide a compiled project file?](https://github.com/google/mediapipe/issues/4171)

Without this, other projects depending on mediapipe are stalling
- [GDMP: Godot plugin for utilizing MediaPipe](https://github.com/j20001970/GDMP/issues/1#issuecomment-1480368521)
- [Pure .NET bindings for Google's MediaPipe](https://github.com/vignetteapp/MediaPipe.NET)
- [Unity plugin to run MediaPipe graphs](https://github.com/homuler/MediaPipeUnityPlugin)

#### Aug 2022
['WindowsApps\python.exe' is not executable](https://github.com/bazelbuild/bazel/issues/12029)

> For those still looking for a solution to this problem: it is probably related to the fact that in the installations of Windows that have bash.exe map to WSL, the normal windows paths are not recognized by WSL and so in third_party/py/python_configure.bzl the _check_python_bin fails. You have to translate the paths between Windows and WSL (bash) using the wslpath util.

@rajkundu 
Can you share how you make it works in Windows and so the Windows community can stop doing it as Windows support is officially experimental

The main problem of building mediapipe in [**windows**](https://developers.google.com/mediapipe/framework/getting_started/install#installing_on_windows) due to unsolved open issues related to external library i.e. tensorflow which has UNSOLVED **Python_BIN_PATH** inherited from tensorflow

Issues supporting this claim
- Windows instruction is experimental as the EXISTING instruction is **obsolete/CONFUSING and lack of proper support**
  - [Windows Installation does not work due to wrong environment variables Windows 10](https://github.com/google/mediapipe/issues/3276)
  
@andrechen
Could you help us SOLVE this UNSOLVABLE mediapipe problem by updating your contribution?
FYI: https://github.com/andrechen/mediapipe/tree/master/visualstudio

@libaineu2004  => try the Visual Studio build

- https://github.com/google/mediapipe/issues/3851
   > https://github.com/google/mediapipe/issues/3851#issuecomment-1323511159  

- 
![image](https://user-images.githubusercontent.com/49812372/227868716-1d65dbd1-6c7e-4b01-b9ce-f1a4c5adcb1a.png)

### [**Installation in windows**](https://developers.google.com/mediapipe/framework/getting_started/install#installing_on_windows)

</details>

</details>

**Comment by GeorgeS2019** [comment]
<details>
<summary>Contributions from @andrechen</summary>

It took me almost 3 weeks to make face mesh build on Visual Studio before I can test and debug easily. So I'd like to share this to anyone who is surfering bazel build and trying to port to Visual Studio like I did. Would be glad if this saves your precious time. Many thanks to mediapipe team for sharing this fantastic work.

Before open up Visual Studio 2019 and make the build, **make camera accessible** and install PowerShell if you haven't yet. Also note that all demos should be launched in Visual Studio IDE, for you can easily debug and learn. Have fun!

**Now you know everything I know.**

### History
 - 2022/04/17 init commit.
 - 2022/05/08 add **x86**(32-bit) target platform, but with few problems... (always prefer **x64** versions)
   - **[Win32 | Debug]** Application crashes after closing. Move to other opencv liibrary may fix this. (**cv::VideoCapture**)
   - **[Win32 | Release]** A suspicious Visual Studio 2019 (ver.16.11.13) bug is found when linking **tensorflow-static** library. Temporary set **tensorflow-lite** optimization level to **Disabled(/Od)** to work around this. Set **C/C++ | Optimization** back to **/O2**, the error reads like...
      ```
      1>------ Build started: Project: face_detection, Configuration: Release Win32 ------
      1> Generating code
      1>D:\git\mediapipe\third_party\tensorflow\third_party\gemmlowp\internal\output.h(176): fatal error C1001: Internal compiler error.
      1>(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 213)
      1> To work around this problem, try simplifying or changing the program near the locations listed above.
      1>If possible please provide a repro here: https://developercommunity.visualstudio.com
      1>Please choose the Technical Support command on the Visual C++
      1> Help menu, or open the Technical Support help file for more information
      1>
      1>Done building project "face_detection.vcxproj" -- FAILED.
      ``` 
 - 2022/05/10 Add **live_demo**, all-in-one demo. Also, mediapipe.lib now become a monolithic static library!!!
 - 2022/05/29 Add **face_effect**, **selfie_segmentation** and face_geometry test module in **face_mesh**
 - 2022/06/08 Tested on Visual Studio 2022 version 17.2.3
 - 2022/07/16 Merge v0.8.10.2
 - 2022/07/17 **face_effect** example now can export **Wavefront .obj** files (press 'o' key)
 - 2022/09/12 Merge v0.8.11
 - 2022/10/08 Merged from upstream

</details>

**Comment by ayushgdev** [comment]
Hello @GeorgeS2019 Thanks for collecting issues and compiling a elaborated issue description. It helps us understand the problem better. 
@jiuqiant Would you please check this issue ?

**Comment by GeorgeS2019** [comment]
@andrechen
> 2022/06/08 Tested on Visual Studio 2022 version 17.2.3

I have tried using the latest VS2022, 17.5.0 => the build fail

**Comment by GeorgeS2019** [comment]
Consider supporting this [issue](https://github.com/google/mediapipe/issues/4206)

**Comment by andrechen** [comment]
> @andrechen
> > 2022/06/08 Tested on Visual Studio 2022 version 17.2.3
> 
> I have tried using the latest VS2022, 17.5.0 => the build fail

You're right, it seems we are having INTERNAL COMPILER ERRORS right now for these versions. Looks like a visual studio bug. But at least, version 17.2.3 does work. 

https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1001?view=msvc-170

**Comment by GeorgeS2019** [comment]
@andrechen 

Very appreciate your IMPORTANT contribution to MediaPipe Windows community

**Comment by GeorgeS2019** [comment]
@andrechen 
I really need to use BlendShape, hopefully in future, u find time to include a blendshape example. Thank you

**Comment by GeorgeS2019** [comment]
Since filing this issue, it is great to see many commits have been done to improve the reliability of building in windows

**Comment by GeorgeS2019** [comment]
https://github.com/google/mediapipe/issues/4227

**Comment by GeorgeS2019** [comment]
@rolandeke 
@Mr-Khans
https://github.com/google/mediapipe/issues/4259

Both Windows 11, alone or using WSL2, have unsolved problems

## Action
Documentation needs to make that clear as well: both WSL (Ubuntu) and Windows 11 are not reflecting Unsolved issues transferred from TensorFlow

By not tagging probably, MORE and MORE Windows 11 and WSl will keep facing FRUSTRATION without knowing that their problems ARE PART OF BIGGER Neglected Issues across DIFFERENT Google projects for Windows and WSL

**Comment by andrechen** [comment]
> @andrechen
> 
> > 2022/06/08 Tested on Visual Studio 2022 version 17.2.3
> 
> I have tried using the latest VS2022, 17.5.0 => the build fail

If you're still interested in [LEGACY solution](https://github.com/andrechen/mediapipe/tree/master/visualstudio), i had fixed tensorflow-lite build break by adding a CPP  **_SILENCE_NONFLOATING_COMPLEX_DEPRECATION_WARNING** for visual studio 2022 v17.5.4. It also works for VS2019 16.11.26. both are the latest version.

One thing that, if you're suffering from **C1001: Internal compiler error**, try disable CPU overclocking.

**Comment by lu-wang-g** [comment]
What is the issue or feature request here?

**Comment by GeorgeS2019** [comment]
Move to https://github.com/google/mediapipe/issues/5366
