### ISSUE TITLE
how to set normal node execute parallelly

### ISSUE THREAD

**Issue by Bakashaka** [google/mediapipe#4204]
I want to make my custom calculator execute parallelly. I found "[max_in_flight](https://github.com/google/mediapipe/tree/master/mediapipe/framework/calculator.proto)" that can make it work in the doc, 
so I changed my calculator graph content like this:
original:
input_stream: "text"
output_stream: "bs"

node {
    calculator: "Text2SpeechCalculator"
    input_stream: "text"
    output_stream: "speech"
}

node {
    calculator: "Audio2BsCalculator"
    input_stream: "speech"
    output_stream: "bs"
}

now:

input_stream: "text"
output_stream: "bs"

node {
    calculator: "Text2SpeechCalculator"
    input_stream: "text"
    output_stream: "speech"
    max_in_flight: 2
}

node {
    calculator: "Audio2BsCalculator"
    input_stream: "speech"
    output_stream: "bs"
    max_in_flight: 2
}

But it didn't work, I don't know why,
When I input text twice, the workflow in the log is "Text2SpeechCalculator::Process() --> Audio2BsCalculator::Process() --> Text2SpeechCalculator::Process() --> Audio2BsCalculator::Process()" rather than my expected  result that "Text2SpeechCalculator::Process() --> Text2SpeechCalculator::Process() --> Audio2BsCalculator::Process() --> Audio2BsCalculator::Process()" .

**Comment by LiuYi-Up** [comment]
> I want to make my custom calculator execute parallelly. I found "[max_in_flight](https://github.com/google/mediapipe/tree/master/mediapipe/framework/calculator.proto)" that can make it work in the doc, so I changed my calculator graph content like this: original: input_stream: "text" output_stream: "bs"
> 
> node { calculator: "Text2SpeechCalculator" input_stream: "text" output_stream: "speech" }
> 
> node { calculator: "Audio2BsCalculator" input_stream: "speech" output_stream: "bs" }
> 
> now:
> 
> input_stream: "text" output_stream: "bs"
> 
> node { calculator: "Text2SpeechCalculator" input_stream: "text" output_stream: "speech" max_in_flight: 2 }
> 
> node { calculator: "Audio2BsCalculator" input_stream: "speech" output_stream: "bs" max_in_flight: 2 }
> 
> But it didn't work, I don't know why, When I input text twice, the workflow in the log is "Text2SpeechCalculator::Process() --> Audio2BsCalculator::Process() --> Text2SpeechCalculator::Process() --> Audio2BsCalculator::Process()" rather than my expected result that "Text2SpeechCalculator::Process() --> Text2SpeechCalculator::Process() --> Audio2BsCalculator::Process() --> Audio2BsCalculator::Process()" .

Hi, I have the same question and plan with yours, did you complete this plan? How?
