### ISSUE TITLE
Info about mediapipe pose world coordinates axis orientation

### ISSUE THREAD

**Issue by gianluca-amprimo** [google/mediapipe#4205]
Hello everybody,
from the documentation I was not able to infer how the axis are oriented in mediapipe pose world coordinates. Is the z axis always pointing toward the camera that is recording and the other axis orthogonal to that one?

**Comment by ayushgdev** [comment]
Hello @gianluca-amprimo 
Yes. The pose model z-axis always point towards the camera _for negative values_. The other axes are orthogonal to it. To quote from the [model card](https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview):
> Z coordinate is measured in "image pixels" like the X and Y coordinates and represents the distance relative to the plane of the subject's hips, which is the origin of the Z axis. Negative values are between the hips and the camera; positive values are behind the hips. Z coordinate scale is similar with X, Y scales but has different nature as obtained not via human annotation, by fitting synthetic data (GHUM model) to the 2D annotation. Note, that Z is not metric but up to scale.

**Comment by gianluca-amprimo** [comment]
Ok that's true for "image coordinates", but what about "world" coordinates. Does the same assumptions on axis orientation hold?

**Comment by bazarevsky** [comment]
Yes, this relates world coordinates as well

**Comment by ayushgdev** [comment]
Thanks @bazarevsky for the clarification.
