### ISSUE TITLE
Have tried troubleshooting for days cannot figure out why this is happening "Mediapipe has no attribute solutions"

### ISSUE THREAD

**Issue by Ibzo1** [google/mediapipe#4207]
### OS Platform and Distribution

Mac M1 OS 13.1

### Compiler version

Apple Clang

### Programming Language and version

Python 3.6

### Installed using virtualenv? pip? Conda?(if python)

Installed using pip

### MediaPipe version

No idea! 

### Android AAR (if android)

None

### Describe the problem

```shell
Just the error in the log below. Funny though when I try to uninstall mediapipe it says it cant find it on my system, and when I try to install it it says: ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
 This is even when I specify a version. Please help!
```

### Complete Logs

```shell
Traceback (most recent call last):
  File "/Users/ibzazh/PycharmProjects/HandTracker/main.py", line 8, in <module>
    mpHands = mp.solutions.hands
AttributeError: module 'mediapipe' has no attribute 'solutions'
```

**Comment by kuaashish** [comment]
Hello @Ibzo1,
Unfortunately, MediaPipe doesn't support the building the package through PyPI/Pip install in the macOS silicon chip such M1, M2(Running [thread](https://github.com/google/mediapipe/issues/4090)). Team is actively working to support this feature However, we can not provide any timeline. As of now, we are marking this as feature request and sharing with the team again internally. Thank you!

**Comment by kuaashish** [comment]
@Ibzo1,
Could you please update the status of the above?

**Comment by Ibzo1** [comment]
Hello! Yes it is working now - thanks so much.

**Comment by kuaashish** [comment]
Thank you for the confirmation, Closing this issue as resolved.
