### ISSUE TITLE
Face landmarks 68 points ?? 

### ISSUE THREAD

**Issue by JaxSulav** [google/mediapipe#421]
What if I want to draw 68 points of face landmarks for face detection gpu? 
There is an option  num_keypoints: 6, in face_detection_mobbile_gpu.pbtxt.. What else would i need to do? Any help will be appreciated. Thank you :)

**Comment by fanzhanggoogle** [comment]
The option is tight to the model it's using. The face detection model predict 6 landmarks on the face along with the bounding box. This option is mostly used for different models. It stays the constant for the same model.

**Comment by JaxSulav** [comment]
Thanks for the info. Is there a framework for training the landmarks and obtaining 68 points landmark model too? Does this means that I cannot use mediapipe to get more than 6 landmarks..?

**Comment by jiuqiant** [comment]
> Thanks for the info. Is there a framework for training the landmarks and obtaining 68 points landmark model too? Does this means that I cannot use mediapipe to get more than 6 landmarks..?

Currently, we have no plan to release a solution to get more 6 face landmarks with MediaPipe.
