### ISSUE TITLE
how to disable xnnpack when build mediapipe

### ISSUE THREAD

**Issue by xiuchen** [google/mediapipe#4212]
### OS Platform and Distribution

ubuntu 16.04

### Compiler version

g++ 

### Programming Language and version

c++ 9.2.0

### Android AAR (if android)

None

### Describe the problem

```shell
How to disable xnnpack when build mediapipe
```

### Complete Logs

```shell
no log
```

**Comment by ayushgdev** [comment]
Hello @xiuchen XNNPack usage can be disabled by NOT using the **delegate** options in any calculator. For example, in the hand_landmark_cpu.pbtxt file, you can disable the xnnpack in [InferenceCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark_cpu.pbtxt#L88) by removing the delegate keyword and its value.
