### ISSUE TITLE
control_utils_3d.js can not render the connection between landmarks.

### ISSUE THREAD

**Issue by ly15927086342** [google/mediapipe#4213]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

mac m1

### Programming Language and version

javascript

### MediaPipe version

@mediapipe/pose^0.5.1635988162

### Solution

Pose

### Describe the actual behavior

```shell
I link the control_utils_3d by CDN(https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d/control_utils_3d.js). All parameters work well unless the connectionColor is not effective, which is different from the document example picture. I mean, the connectionColor and connectionWidth is the line connect two landmarks, right?
```

### Describe the expected behaviour

```shell
I expect that ConnectionColor and ConnectionWidth are effective.
```

### Standalone code/steps you may have used to try to get what you need

```shell
grid = new LandmarkGrid(landmarkContainer, {
        isRotating: false,
        rotationSpeed: 0.01,
        // rotationSpeed: 0.05,
        // fovInDegree: 0.1,
        backgroundColor: 0x000000,
        axesColor: 0xaaaaaa,
        axesWidth: 1,
        centered: true,
        connectionColor: 0x00ffff,
        connectionWidth: 2,
        definedColors: [],
        fitToGrid: true,
        labelPrefix: "",
        labelSuffix: "",
        landmarkSize: 2,
        landmarkColor: 0x00ffff,
        margin: 0,
        minVisibility: 0.65,
        nonvisibleLandmarkColor: 0xaa7777,
        numCellsPerAxis: 3,
        range: 1,
        showHidden: true, // 展示隐藏的connection node
      }) as any;

 grid.updateLandmarks(results.poseWorldLandmarks);
```

**Comment by ayushgdev** [comment]
Hello @ly15927086342 
Connections can be rendered using the `updateLandmarks()`. It is a generic method available as a utility so it needs some more information on what connections it needs to create. The Landmarks are given in the first argument. However, among those landmarks, which landmarks it needs to connect together is missing in your function call. 

To provide that information, you should supply second argument as `POSE_CONNECTIONS`. This constant is available in @mediapipe/pose so no other imports are required. You can check the index.d.ts type definition file for control_utils_3d [here](https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d/index.d.ts).

Please update your function call like this and it should work:
`grid.updateLandmarks(results.poseWorldLandmarks, POSE_CONNECTIONS);`

**Comment by ly15927086342** [comment]
> Hello @ly15927086342 Connections can be rendered using the `updateLandmarks()`. It is a generic method available as a utility so it needs some more information on what connections it needs to create. The Landmarks are given in the first argument. However, among those landmarks, which landmarks it needs to connect together is missing in your function call.
> 
> To provide that information, you should supply second argument as `POSE_CONNECTIONS`. This constant is available in @mediapipe/pose so no other imports are required. You can check the index.d.ts type definition file for control_utils_3d [here](https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d/index.d.ts).
> 
> Please update your function call like this and it should work: `grid.updateLandmarks(results.poseWorldLandmarks, POSE_CONNECTIONS);`

Think you for your answer. It works well.

There is another relative question. When I use npm package @mediapipe/control_utils_3d^0.3.1635987963, it throws error like 'Uncaught TypeError: Cannot read properties of undefined (reading 'Vector3')' from mesh_viewer.ts:32.

However, If I use CDN resource, it works. So is there something wrong with the package @mediapipe/control_utils_3d?

All my dependences are like this:
`  "dependencies": {
    "@mediapipe/camera_utils": "^0.3.1675466862",
    "@mediapipe/control_utils": "^0.6.1675466023",
    "@mediapipe/control_utils_3d": "^0.3.1635987963",
    "@mediapipe/drawing_utils": "^0.3.1675466124",
    "@mediapipe/pose": "^0.5.1635988162",
    "vue": "^3.2.45"
  },`

**Comment by ayushgdev** [comment]
Always happy to help @ly15927086342 . However, this issue seems to be related to a different error. To keep the context of the issue as relevant to the original issue as possible, may I suggest you close this issue and open another one?
This helps community and us to search the issues better in concise manner.

**Comment by ly15927086342** [comment]
> Always happy to help @ly15927086342 . However, this issue seems to be related to a different error. To keep the context of the issue as relevant to the original issue as possible, may I suggest you close this issue and open another one? This helps community and us to search the issues better in concise manner.

Ok, the new issue is this: https://github.com/google/mediapipe/issues/4222
