### ISSUE TITLE
A question regarding to glitter eyeshadows using FaceMesh

### ISSUE THREAD

**Issue by BoraYang** [google/mediapipe#4216]
Does anyone know how to put glitters (particles) on eyelids (to express glitter eyeshadows) on a face using facemesh?

I use three.js and aframe to implement AR Makeup Try-On feature and encountered the issue that textures on eyelids and lips stretched out.

I need to make glitter eyeshadows on eyelids just like the image attached below. Please share your thoughts how to avoid this texture stretching problem.
Thanks.
 
<img width="1260" alt="Screenshot 2023-03-30 at 3 33 49 PM" src="https://user-images.githubusercontent.com/19316616/228749713-4ee6ab0f-35cf-432b-814b-23e23150df73.png">

**Comment by kuaashish** [comment]
Hi @BoraYang,
Could you please elaborate query with complete details, code changes you have made, screenshot of the problem facing, exact support you are looking from us to share the possible solution on the use case mentioned. thank you
