### ISSUE TITLE
Pose Track: Get human part descriptors.

### ISSUE THREAD

**Issue by asafjo23** [google/mediapipe#4219]
Hi MediaPipe,

First, I want to say it's a great project!
Next, I wanted to ask for your help. As part of a research project I am doing, I am using MediaPipe to extract human joints.
I wanted to ask if there is away to extract the human part descriptors and not the final landmarks?

Thanks for any kind of help!
Asaf,

**Comment by ayushgdev** [comment]
Hello @asafjo23 
Would you please elaborate what do you mean by "human part descriptors"?

**Comment by asafjo23** [comment]
Hi ayushgdev,

Thanks for the quick response, really appreciate it.
As far as I know, most pose detectors (or at least the bottom up approach) are locating the human body parts before regressing to final keypoints.
That means, there is a step where there is more infromation about the body part beside the coordinates (like visual fetures). I refered to this information as the body parts descriptors.
So I wanted to ask if there is a way to extract this information from the pose detector (I think it's blaze pose), maybe from one of it's layers? or any other component.

I hope I was managed to clarify my wish.
Thanks again :-)

**Comment by ayushgdev** [comment]
Hello @asafjo23 No there is no such information available in the MediaPipe pose detection models. The only outputs MediaPipe pose detection models produce are coordinates, world coordinates, and segmentation mask. The landmarks/coordinates also contain visibility and presence of each landmark. For more information about the model, you can refer to the [documentation](https://google.github.io/mediapipe/solutions/pose.html#output) and the [model card page](https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview).

**Comment by asafjo23** [comment]
OK @ayushgdev , Thanks for you kind help :-)

**Comment by ayushgdev** [comment]
Can we close this issue @asafjo23 ?

**Comment by asafjo23** [comment]
Yes, I will close it.
