### ISSUE TITLE
control_utils_3d npm package throw error

### ISSUE THREAD

**Issue by ly15927086342** [google/mediapipe#4222]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

mac m1

### Programming Language and version

javascript

### Solution

Pose

### Describe the actual behavior

```shell
When I use npm package @mediapipe/control_utils_3d^0.3.1635987963, it throws error like 'Uncaught TypeError: Cannot read properties of undefined (reading 'Vector3')' from mesh_viewer.ts:32.

However, if I use CDN resource, it works. So is there something wrong with the package @mediapipe/control_utils_3d?

All my dependences are like this:

`
"dependencies":
{
"@mediapipe/camera_utils": "^0.3.1675466862",
"@mediapipe/control_utils": "^0.6.1675466023",
"@mediapipe/control_utils_3d": "^0.3.1635987963",
"@mediapipe/drawing_utils": "^0.3.1675466124",
"@mediapipe/pose": "^0.5.1635988162",
}
`
```

### Describe the expected behaviour

```shell
I expect the control_utils_3d npm package works as CDN does. Because I write my code with TypeScript instead of Javascript.
```

### Standalone code/steps you may have used to try to get what you need

```shell
import { LandmarkGrid } from "@mediapipe/control_utils_3d";

const grid = new LandmarkGrid(landmarkContainer, {
        isRotating: false,
        rotationSpeed: 0.01,
        // rotationSpeed: 0.05,
        // fovInDegree: 0.1,
        backgroundColor: 0x000000,
        axesColor: 0xaaaaaa,
        axesWidth: 1,
        centered: true,
        connectionColor: 0xeeeeee,
        connectionWidth: 10,
        definedColors: [],
        fitToGrid: true,
        labelPrefix: "",
        labelSuffix: "",
        landmarkSize: 2,
        landmarkColor: 0x00ffff,
        margin: 0,
        minVisibility: 0.65,
        nonvisibleLandmarkColor: 0xaa7777,
        numCellsPerAxis: 3,
        range: 1,
        showHidden: true,
      }) as any;

// pose code...

 grid.updateLandmarks(results.poseWorldLandmarks, POSE_CONNECTIONS);
```

**Comment by kuaashish** [comment]
Hi @ly15927086342,
Could you please try these below pointer and let us know if this works.

- Load it from CDN instead of using from npm.
- Import control_utils_3d before control_utils.

```
  import LandmarkGrid from "@mediapipe/control_utils_3d";
  import controls from "@mediapipe/control_utils";
  import drawingUtils from "@mediapipe/drawing_utils";
  import mpPose from "@mediapipe/pose";

```

- Adding : 
`<script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d/control_utils_3d.js" crossorigin="anonymous" ></script>`

**Comment by ly15927086342** [comment]
> Hi @ly15927086342, Could you please try these below pointer and let us know if this works.
> 
> * Load it from CDN instead of using from npm.
> * Import control_utils_3d before control_utils.
> 
> ```
>   import LandmarkGrid from "@mediapipe/control_utils_3d";
>   import controls from "@mediapipe/control_utils";
>   import drawingUtils from "@mediapipe/drawing_utils";
>   import mpPose from "@mediapipe/pose";
> ```
> 
> * Adding :
>   `<script src="https://cdn.jsdelivr.net/npm/@mediapipe/control_utils_3d/control_utils_3d.js" crossorigin="anonymous" ></script>`

Hi @kuaashish. I tried it as your suggestion. The result is that CDN works but npm not.
However, CDN still throws error that 'Uncaught ReferenceError: javascript is not defined at mesh_viewer.ts:97:45', which didn't affect the function use.

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,
Could you please look into this issue? Thank you

**Comment by schmidt-sebastian** [comment]
Are you able to work around this issue for now (or go back to an older version)? Will add this to my backlog, but we are planning to have a replacement for this ready soon.

**Comment by ly15927086342** [comment]
> Are you able to work around this issue for now (or go back to an older version)? Will add this to my backlog, but we are planning to have a replacement for this ready soon.

Hi, @schmidt-sebastian. The older npm package is still not work. I use CDN now.
Is there any upgrade plan about this package? It's my pleasure to upgrade it.

**Comment by schmidt-sebastian** [comment]
We will publish upgrade guides as the new APIs become available.
