### ISSUE TITLE
Why is there no solution to run gpu mediapipe on windows 10?

### ISSUE THREAD

**Issue by Mr-Khans** [google/mediapipe#4227]
Why is there no solution to run gpu mediapipe on windows 10?

**Comment by ayushgdev** [comment]
Would you please elaborate your query with details on which solution you want to use on windows, and which language you are looking the GPU support for?

**Comment by Mr-Khans** [comment]
@ayushgdev , Good day) solution mediapipe hands for Win10 22H2 and language python3.8  for GPU

system: Win10 22H2
language: python3.8

requirements.txt

absl-py
attrs>=19.1.0
flatbuffers>=2.0
matplotlib
numpy
opencv-contrib-python
protobuf>=3.11,<4
sounddevice

when running the script

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

**Comment by kuaashish** [comment]
@Mr-Khans,
Could you please share the complete error logs getting to understand the issue better. However, We suggest to fill the [template](https://github.com/google/mediapipe/issues/new/choose) to get the maximum relevant information to debug the issue facing. thank you

**Comment by Mr-Khans** [comment]
Hello @kuaashish 
Please give me a list or sheet of modules for python including python version and tensorflow-gpu so how could there be a compatibility issue?

**Comment by kuaashish** [comment]
Hello @Mr-Khans,
This is already in our roadmap. Will let you know once it becomes available from our end. Thank you

**Comment by Mr-Khans** [comment]
@kuaashish 
thx)

**Comment by kuaashish** [comment]
@Mr-Khans,

We have rolled out newer version 0.10.1 with python GPU support as noted in [release page](https://github.com/google/mediapipe/releases/tag/v0.10.1).

**Comment by makingpippop** [comment]
Hi @kuaashish,

Is there more information on how to use GPU with python? I tried setting the *Delegate* in the *BaseOptions* to GPU but I got a *NotImplementedError*.

`BaseOptions(delegate=BaseOptions.Delegate.GPU, model_asset_path=model_path)`

`NotImplementedError: GPU Delegate is not yet supported for Windows`

Thanks!

**Comment by adeadzeplin** [comment]
Any updates on this issue?

**Comment by Tomer1577** [comment]
> Hola @kuaashish , This is good news) but delegate use CPU for Windows Python
> 
> ```
> UserWarning: Failed to load image Python extension: '[WinError 127] 'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
>   warn(
> INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
> ```
> 
> Сan you give me a list of recommendations and dependencies to run python mediapipe gpu. Version Python and req.txt ?

I am getting the same thing. is there a way to force it to try GPU first?

**Comment by emalbt** [comment]
Hi, Is there more information on how to use GPU with python?

**Comment by joansc** [comment]
+1

**Comment by joansc** [comment]
Is Python GPU support for Windows on the roadmap? Thanks!

**Comment by JobCS04** [comment]
https://github.com/DavidReveloLuna/TensorflowGPU?tab=readme-ov-file
