### ISSUE TITLE
Mediapipe model, it can be run on a desktop with GPU support?

### ISSUE THREAD

**Issue by Mr-Khans** [google/mediapipe#4228]
Mediapipe model, it can be run on a desktop with GPU support?

**Comment by Mr-Khans** [comment]
Hello @kuaashish, pls, show me about my output.
```python3 setup.py bdist_wheel
/usr/lib/python3/dist-packages/setuptools/dist.py:507: UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running bdist_wheel
running build
running build_py
running gen_protos
running generate_metadata_schema
error: [Errno 2] No such file or directory: 'bazel'
``` 
I am using mediapipe repository and getting bazel error...

**Comment by kuaashish** [comment]
Hello @Mr-Khans,
Would you please let us know the exact support you are looking from us, From the description and recent comment we are not able to get the things that you are trying build mediapipe on Desktop, GPU or Python, GPU? If, You can share the mentioned information then we will be glad to help on the issue you are facing. Thank you

**Comment by Mr-Khans** [comment]
Hola @kuaashish
I want to run mediapipe on gpu using win10 wsl Ubuntu 20.04, bazel 5.2.0, I want to run manual solution, I can't successfully build bazel, it throws build errors.
I want to create a GPU solution manually via bazel.

**Comment by Mr-Khans** [comment]
Hola @kuaashish 

Is there an example of running mediapipe on the GPU using python or in a python environment, because this example uses .cc files, which means C++?
