### ISSUE TITLE
gestureRecognizer remains undefined.

### ISSUE THREAD

**Issue by MJKingsbury** [google/mediapipe#4231]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

MacBook Pro M2, Ventura 13.0 (22A380)

### MediaPipe Tasks SDK version

JavaScript / Web

### Task name (e.g. Image classification, Gesture recognition etc.)

Gesture recognition

### Programming Language and version (e.g. C++, Python, Java)

JavaScript (ReactJS)

### Describe the actual behavior

```shell
gestureRecognizer does not create an instance of the GestureRecognizer class and remains undefined, therefore not allowing predictions for landmarks on the video.

UPDATE: Comments.
```

### Describe the expected behaviour

```shell
gestureRecognizer variable is properly defined in the useEffect, allowing normal functionality. This has worked previously, and yet now seems to not work despite no apparent changes ... unsure why.
```

### Standalone code/steps you may have used to try to get what you need

```shell
https://github.com/MJKingsbury/Theresynth_JS/blob/main/src/Video.js

A link to the code trying to utilise MediaPipe.
```

### Other info / Complete Logs

ERROR UPDATED IN COMMENTS.

**Comment by MJKingsbury** [comment]
[console-export-2023-4-1_15-46-8.txt](https://github.com/google/mediapipe/files/11129802/console-export-2023-4-1_15-46-8.txt)

This is the output from the console, showing the filesetresolver working correctly, and the gesturerecognizer remaining undefined.

**Comment by MJKingsbury** [comment]
EDIT: After some modifications to the code linked above, the gestureRecognizer appears to now be correctly initializing, however no gestures are being returned in the results. I have pushed the now modified code to the repo. Sometimes when I run the code, it doesn't throw errors, however occasionally I receive the following error:

Uncaught (in promise) Error: WaitUntilIdle failed: $CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.; WaitUntilIdle failed
    handleErrors vision_bundle.js:1
    finishProcessing vision_bundle.js:1
    process vision_bundle.js:1
    processVideoData vision_bundle.js:1
    recognizeForVideo vision_bundle.js:1
    predictions Video.js:39
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56
    predictions Video.js:56

No landmarks are shown on screen during testing. Any help would be appreciated.

**Comment by kuaashish** [comment]
Hello @MJKingsbury,
Would you please let us know the version you are using, Is older version of gestureRecognizer being used here? if, We can get the information about version of model used that will be more helpful to understand the issue better. Thank you

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,
Could you please look into this issue? Thank you

**Comment by MJKingsbury** [comment]
@kuaashish I'm looking to have this project completed ASAP, is there an older version of gestureRecognizer I can use for the time being that allows me to capture hand depth data, positioning and also read specific gestures?

**Comment by MJKingsbury** [comment]
@schmidt-sebastian Hi, the repo is linked here: https://github.com/MJKingsbury/Theresynth_JS

Does this provide all the necessary files? I'm not sure what else is needed re: build instructions.

**Comment by MJKingsbury** [comment]
Errors from updated code:

I0000 00:00:1681570183.358000       1 hand_gesture_recognizer_graph.cc:256] Custom gesture classifier is not defined. [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
I0000 00:00:1681570183.375000       1 gl_context_webgl.cc:151] Successfully created a WebGL context with major version 3 and handle 1 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
I0000 00:00:1681570183.376000       1 gl_context.cc:359] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0)) [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
W0000 00:00:1681570183.376000       1 gl_context.cc:1000] OpenGL error checking is disabled [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Graph successfully started running. [vision_wasm_internal.js:1087:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Hi! [Video.js:42](http://localhost:3003/Users/mattkingsbury/Desktop/theresynth/theresynth/src/Video.js)
predict [Video.js:55](http://localhost:3003/Users/mattkingsbury/Desktop/theresynth/theresynth/src/Video.js)
Hi! [Video.js:42](http://localhost:3003/Users/mattkingsbury/Desktop/theresynth/theresynth/src/Video.js)
predict [Video.js:55](http://localhost:3003/Users/mattkingsbury/Desktop/theresynth/theresynth/src/Video.js)
Uncaught (in promise) TypeError: WebGL2RenderingContext.texImage2D: Argument 6 is not valid for any of the 6-argument overloads.
    bindTextureToStream vision_bundle.js:1
    node_modules bundle.js:47897
    wrapStringPtr vision_bundle.js:1
    addGpuBufferAsImageToStream vision_bundle.js:1
    process vision_bundle.js:1
    processVideoData vision_bundle.js:1
    recognizeForVideo vision_bundle.js:1
    predictions Video.js:57
    Video Video.js:43
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    factory react refresh:6
    Webpack 24
[vision_bundle.js:1](http://localhost:3003/Users/mattkingsbury/node_modules/@mediapipe/tasks-vision/vision_bundle.js)
Uncaught (in promise) TypeError: WebGL2RenderingContext.texImage2D: Argument 6 is not valid for any of the 6-argument overloads.
    bindTextureToStream vision_bundle.js:1
    node_modules bundle.js:47897
    wrapStringPtr vision_bundle.js:1
    addGpuBufferAsImageToStream vision_bundle.js:1
    process vision_bundle.js:1
    processVideoData vision_bundle.js:1
    recognizeForVideo vision_bundle.js:1
    predictions Video.js:57
    Video Video.js:43
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    factory react refresh:6
    Webpack 24
[vision_bundle.js:1](http://localhost:3003/Users/mattkingsbury/node_modules/@mediapipe/tasks-vision/vision_bundle.js)
I0000 00:00:1681570183.426000       1 hand_gesture_recognizer_graph.cc:256] Custom gesture classifier is not defined. [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
I0000 00:00:1681570183.443000       1 gl_context_webgl.cc:151] Successfully created a WebGL context with major version 3 and handle 1 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
I0000 00:00:1681570183.443000       1 gl_context.cc:359] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0)) [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
W0000 00:00:1681570183.444000       1 gl_context.cc:1000] OpenGL error checking is disabled [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Graph successfully started running. [vision_wasm_internal.js:1087:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Hi! [Video.js:42](http://localhost:3003/Users/mattkingsbury/Desktop/theresynth/theresynth/src/Video.js)
predict [Video.js:55](http://localhost:3003/Users/mattkingsbury/Desktop/theresynth/theresynth/src/Video.js)
INFO: Created TensorFlow Lite XNNPACK delegate for CPU. [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
E0000 00:00:1681570183.459000       1 image_to_tensor_utils.cc:56] INTERNAL: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0. [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Stack trace: [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
E0000 00:00:1681570183.460000       1 calculator_graph.cc:851] INTERNAL: CalculatorGraph::Run() failed in Run: [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Calculator::Process() for node "mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0. [type.googleapis.com/mediapipe.StatusList='\n\xd7\x03\x08\r\x12\xd2\x03\x43\x61lculator::Process() for node \"mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator\" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.'] [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
=== Source Location Trace: === [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:223 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/framework/calculator_node.cc:948 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
E0000 00:00:1681570183.460000       1 calculator_graph.cc:851] INTERNAL: CalculatorGraph::Run() failed in Run: [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Calculator::Process() for node "mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0. [type.googleapis.com/mediapipe.StatusList='\n\xd7\x03\x08\r\x12\xd2\x03\x43\x61lculator::Process() for node \"mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator\" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.'] [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
=== Source Location Trace: === [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:223 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/framework/calculator_node.cc:948 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
E0000 00:00:1681570183.460000       1 calculator_graph.cc:851] INTERNAL: CalculatorGraph::Run() failed in Run: [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Calculator::Process() for node "mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0. [type.googleapis.com/mediapipe.StatusList='\n\xd7\x03\x08\r\x12\xd2\x03\x43\x61lculator::Process() for node \"mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator\" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.'] [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
=== Source Location Trace: === [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:223 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/framework/calculator_node.cc:948 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Hi! [Video.js:42](http://localhost:3003/Users/mattkingsbury/Desktop/theresynth/theresynth/src/Video.js)
predict [Video.js:55](http://localhost:3003/Users/mattkingsbury/Desktop/theresynth/theresynth/src/Video.js)
E0000 00:00:1681570183.461000       1 gl_graph_runner_internal_image.cc:68] Adding Image to stream image_in was not ok: INTERNAL: Graph has errors: [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Calculator::Process() for node "mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0. [type.googleapis.com/mediapipe.StatusList='\n\xd7\x03\x08\r\x12\xd2\x03\x43\x61lculator::Process() for node \"mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator\" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.'] [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
=== Source Location Trace: === [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:223 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/framework/calculator_node.cc:948 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
E0000 00:00:1681570183.462000       1 calculator_graph.cc:851] INTERNAL: CalculatorGraph::Run() failed in Run: [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Calculator::Process() for node "mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0. [type.googleapis.com/mediapipe.StatusList='\n\xd7\x03\x08\r\x12\xd2\x03\x43\x61lculator::Process() for node \"mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator\" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.'] [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
=== Source Location Trace: === [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/calculators/tensor/image_to_tensor_calculator.cc:223 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
third_party/mediapipe/framework/calculator_node.cc:948 [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
E0000 00:00:1681570183.462000       1 calculator_graph.cc:851] INTERNAL: CalculatorGraph::Run() failed in Run: [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Calculator::Process() for node "mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0. [type.googleapis.com/mediapipe.StatusList='\n\xd7\x03\x08\r\x12\xd2\x03\x43\x61lculator::Process() for node \"mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator\" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.'] [vision_wasm_internal.js:1103:8](https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm/vision_wasm_internal.js)
Uncaught (in promise) Error: Encountered multiple errors: Adding proto packet of type mediapipe.NormalizedRect to stream norm_rect was not ok: $Graph has errors: 
Calculator::Process() for node "mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0., WaitUntilIdle failed: $CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.; WaitUntilIdle failed
    handleErrors vision_bundle.js:1
    finishProcessing vision_bundle.js:1
    process vision_bundle.js:1
    processVideoData vision_bundle.js:1
    recognizeForVideo vision_bundle.js:1
    predictions Video.js:57
    Video Video.js:43
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    factory react refresh:6

**Comment by MJKingsbury** [comment]
@schmidt-sebastian @kuaashish Any update on this?

**Comment by schmidt-sebastian** [comment]
Thanks for the update.

**Comment by ducdm-mor** [comment]
It's kind of late but I can tell this problem is from caching for hot reload when using a router. I was facing the same issue when developing a VueJs app using MediaPie. 
I fixed it by **clearing `gestureRecognizer` before unmounting** every time, remember to try to clear your event listener as well

```

function handlerGestureRecognition(){
if (!gestureRecognizer) {
    console.log("gestureRecognizer not Loaded");
    return;
  }
// your code handle gesture recognition from video stream
}

// clear variable before you destroying component
onBeforeUnmount(() => {

  gestureRecognizer = null; 
  stopStream();
  const video = document.getElementById(webcamName.value) as HTMLVideoElement;
  video.removeEventListener("loadeddata", predictWebcam);
});`
```
