### ISSUE TITLE
Face Detection Short Range C++, Couldn't get any detected faces?

### ISSUE THREAD

**Issue by thang-dao** [google/mediapipe#4232]
I have implemented a face detection C++ program that uses "face_detection_short_range.pbtxt" from Mediapipe, but I am not able to get any results (the output.size() is always 0). Additionally, I would like to know how to obtain the bounding box of faces from the results of the Mediapipe model. Thank you so much for any help. Here is my program:
`#define STB_IMAGE_IMPLEMENTATION

#include <fcntl.h>
#include <unistd.h>

#include "absl/flags/flag.h"
#include "absl/flags/parse.h"
#include "absl/container/flat_hash_set.h"
#include "absl/memory/memory.h"
#include "absl/status/status.h"
#include "absl/strings/match.h"
#include "absl/strings/str_cat.h"
#include "absl/strings/str_join.h"
#include "absl/strings/substitute.h"
#include "mediapipe/framework/port/proto_ns.h"
#include "mediapipe/framework/formats/image_frame_opencv.h"
#include "mediapipe/framework/port/opencv_highgui_inc.h"
#include "mediapipe/framework/port/opencv_imgproc_inc.h"
#include "mediapipe/framework/port/opencv_video_inc.h"
#include "mediapipe/framework/port/status.h"
#include <memory>
#include <vector>

#include "mediapipe/calculators/tensor/image_to_tensor_calculator.pb.h"
#include "mediapipe/calculators/tensor/inference_calculator.pb.h"
#include "mediapipe/calculators/tensor/tensors_to_detections_calculator.pb.h"
#include "mediapipe/calculators/tflite/ssd_anchors_calculator.pb.h"
#include "mediapipe/calculators/util/non_max_suppression_calculator.pb.h"
#include "mediapipe/framework/calculator_framework.h"
#include "mediapipe/framework/formats/detection.pb.h"
#include "mediapipe/framework/formats/rect.pb.h"
#include "mediapipe/framework/port/file_helpers.h"
#include "mediapipe/framework/port/parse_text_proto.h"
#include "mediapipe/framework/tool/options_util.h"
#include "mediapipe/gpu/gpu_origin.pb.h"
#include "mediapipe/modules/face_detection/face_detection.pb.h"
#include "absl/status/statusor.h"
#include "mediapipe/framework/calculator.pb.h"
#include "mediapipe/framework/formats/image_frame.h"

absl::Status RunMPPGraph()
{
  cv::Mat bgr_frame = cv::imread("/root/data/images/test/video1_001.ppm");
  if (bgr_frame.empty())
  {
    std::cerr << "Failed to load input image file." << std::endl;
    return mediapipe::UnknownError("Failed to load input image file.");
  }

  cv::Mat frame;
  cv::cvtColor(bgr_frame, frame, cv::COLOR_BGR2RGB);
  // Wrap Mat into an ImageFrame.

  auto input_frame = absl::make_unique<mediapipe::ImageFrame>(
      mediapipe::ImageFormat::SRGB, frame.cols, frame.rows,
      mediapipe::ImageFrame::kDefaultAlignmentBoundary);

  cv::Mat input_frame_mat = mediapipe::formats::MatView(input_frame.get());
  frame.copyTo(input_frame_mat);

  // mediapipe::CalculatorGraphConfig config = GetFaceDetectionShortRangeCpu();

  std::string calculator_graph_config_file = "mediapipe/modules/face_detection/face_detection_short_range.pbtxt";
  std::string calculator_graph_config_contents;
  MP_RETURN_IF_ERROR(mediapipe::file::GetContents(
      calculator_graph_config_file,
      &calculator_graph_config_contents));
  LOG(INFO) << "Get calculator graph config contents: "
            << calculator_graph_config_contents;
  mediapipe::CalculatorGraphConfig config =
      mediapipe::ParseTextProtoOrDie<mediapipe::CalculatorGraphConfig>(
          calculator_graph_config_contents);

  LOG(INFO) << "Initialize the calculator graph.";

  mediapipe::CalculatorGraph graph;
  graph.Initialize(config);

  graph.ObserveOutputStream("image", [&](const mediapipe::Packet &packet)
                            {
  LOG(INFO) << "Received image packet at timestamp " << packet.Timestamp().Value();
  return absl::OkStatus(); });

  std::vector<mediapipe::Packet> output;
  graph.ObserveOutputStream("DETECTIONS:detections", [&](const mediapipe::Packet &p)
                            {
    output.push_back(p);
    return absl::OkStatus(); });

  graph.StartRun({});
  graph.AddPacketToInputStream(
      "image", mediapipe::Adopt(input_frame.release())
                   .At(mediapipe::Timestamp(20000)));
  graph.CloseAllPacketSources();
  MP_RETURN_IF_ERROR(graph.WaitUntilDone());
  std::cout << output.size() << std::endl;
  return mediapipe::OkStatus();
}

int main(int argc, char **argv)
{

  absl::Status run_status = RunMPPGraph();
  if (!run_status.ok())
  {
    LOG(ERROR) << "Failed to run the graph: " << run_status.message();
    return EXIT_FAILURE;
  }
  else
  {
    LOG(INFO) << "Success!";
  }
  return EXIT_SUCCESS;
}
`

here's log console:
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20230402 09:50:03.066728 34714 face_detection.cc:176] Get calculator graph config contents: # MediaPipe graph to detect faces. (CPU input and inference by default.)
#
# It is required that "face_detection_short_range.tflite" is available at
# "mediapipe/modules/face_detection/face_detection_short_range.tflite"
# path during execution.
#
# EXAMPLE:
#   node {
#     calculator: "FaceDetectionShortRange"
#     input_stream: "IMAGE:image_frame"
#     output_stream: "DETECTIONS:face_detections"
#   }

type: "FaceDetectionShortRange"

# The input image, either ImageFrame, GpuBuffer, or (multi-backend) Image.
input_stream: "IMAGE:image"

# ROI (region of interest) within the given image where faces should be
# detected. (NormalizedRect)
input_stream: "ROI:roi"

# Detected faces. (std::vector<Detection>)
output_stream: "DETECTIONS:detections"

graph_options: {
  [type.googleapis.com/mediapipe.FaceDetectionOptions] {}
}

node {
  calculator: "FaceDetection"
  input_stream: "IMAGE:image"
  output_stream: "DETECTIONS:detections"
  node_options: {
    [type.googleapis.com/mediapipe.FaceDetectionOptions] {
      model_path: "mediapipe/modules/face_detection/face_detection_short_range.tflite"
      tensor_width: 128
      tensor_height: 128

      num_layers: 4
      strides: 8
      strides: 16
      strides: 16
      strides: 16
      interpolated_scale_aspect_ratio: 1.0

      num_boxes: 896
      x_scale: 128.0
      y_scale: 128.0
      h_scale: 128.0
      w_scale: 128.0
      min_score_thresh: 0.1
    }
  }
  option_value: "OPTIONS:options"
}
I20230402 09:50:03.067849 34714 face_detection.cc:182] Initialize the calculator graph.
I20230402 09:50:03.070089 34714 face_detection.cc:189] Received image packet at timestamp 20000
0
I20230402 09:50:03.089236 34714 face_detection.cc:318] Success!

**Comment by ayushgdev** [comment]
Hello @thang-dao 
Can you please format the code so that the code, and comments are understandable ? Right now it looks like headers in between which is causing issues understanding the code. 

Also, Face Detection is available as a solution in C++ so there should not be any need to write the code from scratch. Would you please help us understand which use case of your application is not catered by readily available FD MediaPipe solution?

**Comment by thang-dao** [comment]
hello @ayushgdev, I have project face recognition in C++, I need face detection module to detect faces so I try to use Face Detection model from mediapipe. Could you help me how to use Face Detection solution in C++ from mediapipe? Thanks so much.

**Comment by ayushgdev** [comment]
To build custom app that uses MediaPipe FD internally in C++, you can take reference of the demo_run_graph_main.cc.
The command `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/face_detection:face_detection_cpu` invokes build of the binaries as per the [cc_binary](https://github.com/google/mediapipe/blob/ec1d84aff7f6a4d0a28da6fca8d164a883021bab/mediapipe/examples/desktop/face_detection/BUILD#L29) given in BUILD file of face detection desktop example. This includes the [demo_run_graph_main](https://github.com/google/mediapipe/blob/ec1d84aff7f6a4d0a28da6fca8d164a883021bab/mediapipe/examples/desktop/face_detection/BUILD#L32) cc_binary as the dependency. This binary itself includes the [demo_run_graph_main.cc](https://github.com/google/mediapipe/blob/ec1d84aff7f6a4d0a28da6fca8d164a883021bab/mediapipe/examples/desktop/BUILD#L39) as the source file. If you go to this file, this is the file which takes arguments from the console, supplies `input_stream` to the graph and runs the MediaPipe graph(face detection solution). 
The graph file is given in the command 
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_detection/face_detection_cpu  --calculator_graph_config_file=mediapipe/graphs/face_detection/mediapipe/graphs/face_detection/face_detection_desktop_live.pbtxt.pbtxt
```
So you need to do something similar. In your case, your app's entry point shall replace the demo_run_graph_main.cc in the BUILD file of FD. And then build the example as per the command above.

**Comment by thang-dao** [comment]
Thanks you so much, I follow to [demo_run_graph_main](https://github.com/google/mediapipe/blob/ec1d84aff7f6a4d0a28da6fca8d164a883021bab/mediapipe/examples/desktop/face_detection/BUILD#L32) and I created a custom Detection class to detect faces. However, when I tested it with a dataset, only the first image was predicted correctly.
```
#include <filesystem>
#include "example_impl.h"
#include "absl/flags/flag.h"
#include "absl/flags/parse.h"
#include "mediapipe/framework/formats/image_frame_opencv.h"
#include "mediapipe/framework/port/opencv_highgui_inc.h"
#include "mediapipe/framework/port/opencv_imgproc_inc.h"
#include "mediapipe/framework/port/opencv_video_inc.h"
#include "mediapipe/framework/calculator_framework.h"
#include "mediapipe/framework/port/file_helpers.h"
#include "mediapipe/framework/port/parse_text_proto.h"
#include "mediapipe/framework/port/status.h"
#include "mediapipe/framework/formats/image_frame.h"
#include "mediapipe/framework/formats/detection.pb.h"
using namespace std::chrono;
namespace fs = std::filesystem;

namespace mediapipe
{
    constexpr char kInputStream[] = "input_video";
    constexpr char kOutputStream[] = "face_detections";

    ExampleImpl::~ExampleImpl()
    {
        LOG(INFO) << "Shutting down.";
        absl::Status status = m_graph.CloseInputStream(kInputStream);
        if (status.ok())
        {
            absl::Status status1 = m_graph.WaitUntilDone();
            if (!status1.ok())
            {
                LOG(INFO) << "Error in WaitUntilDone(): " << status1.ToString();
            }
        }
        else
        {
            LOG(INFO) << "Error in CloseInputStream(): " << status.ToString();
        }
    }

    absl::Status ExampleImpl::Init(const std::string &graph, const float& minScore)
    {
        std::cout << "Graph: " << graph << std::endl;
        std::cout << "Detection Min Score: " << minScore << std::endl;
        std::string calculator_graph_config_contents;
        mediapipe::file::GetContents(graph,
                                     &calculator_graph_config_contents);
        LOG(INFO) << "Get calculator graph config contents: "
                  << calculator_graph_config_contents;
        mediapipe::CalculatorGraphConfig config =
            mediapipe::ParseTextProtoOrDie<mediapipe::CalculatorGraphConfig>(
                calculator_graph_config_contents);

        LOG(INFO) << "Initialize the calculator graph.";
        MP_RETURN_IF_ERROR(m_graph.Initialize(config));

        LOG(INFO) << "Start running the calculator graph.";
        mediapipe::StatusOrPoller sop1 = m_graph.AddOutputStreamPoller(kOutputStream);
        assert(sop1.ok());
        m_poller = std::make_unique<mediapipe::OutputStreamPoller>(std::move(sop1.value()));
        MP_RETURN_IF_ERROR(m_graph.StartRun({}));
        this->minScore = minScore;
        return absl::OkStatus();
    }

    int ExampleImpl::Process(uint8_t *data, int width, int height, std::vector<std::vector<int>> &dets, std::vector<std::vector<int>> &eyepairs)
    {
        cv::Mat camera_frame(height, width, CV_8UC3, data);
        auto input_frame = absl::make_unique<mediapipe::ImageFrame>(
            mediapipe::ImageFormat::SRGB, camera_frame.cols, camera_frame.rows,
            mediapipe::ImageFrame::kDefaultAlignmentBoundary);
        cv::Mat input_frame_mat = mediapipe::formats::MatView(input_frame.get());
        camera_frame.copyTo(input_frame_mat);

        size_t frame_timestamp_us =
            (double)cv::getTickCount() / (double)cv::getTickFrequency() * 1e6;

        if (!m_graph.AddPacketToInputStream(kInputStream, mediapipe::Adopt(input_frame.release()).At(mediapipe::Timestamp(m_frame_timestamp))).ok())
        {
            LOG(INFO) << "Failed to add packet to input stream. Call m_graph.WaitUntilDone() to see error (or destroy Example object)";
            return false;
        }
        mediapipe::Packet packet;
        if (!(*m_poller).Next(&packet))
        {
            std::cout << "Couldn't get packet from graph." << std::endl;
            return false;
        }
        const auto &detections = packet.Get<std::vector<mediapipe::Detection>>();
        std::cout << "Number of detection boxes: " << detections.size() << std::endl;
       //...
        }
        return true;
    }
}

int main(int argc, char **argv)
{
    const char *data_path = argv[1];
    const float detectionScore = std::stof(argv[2]);
    std::cout << "Load detection model" << std::endl;
    std::string detectedModel = "/root/face-detection/mediapipe/mediapipe/graphs/face_detection/face_detection_desktop_live.pbtxt";
    mediapipe::Example *detector = nullptr;
    detector = mediapipe::Example::Create(detectedModel, detectionScore);
    std::vector<std::vector<int>> detections;
    std::vector<std::vector<int>> eyePairs;
    auto start = high_resolution_clock::now();
    int count = 0;
    for (const auto &file : fs::directory_iterator(data_path))
    {
        if (!file.is_regular_file())
        {
            continue;
        }
        if (count > 10) {
            break;
        }
        count++;
        std::string filename = file.path().filename().c_str();
        std::string imageFile = file.path().c_str();
        cv::Mat raw_image = cv::imread(imageFile);
        cv::Mat image;
        cv::cvtColor(raw_image, image, cv::COLOR_BGR2RGB);
        std::cout << "Read image: " << imageFile << std::endl;
        int resDet = detector->Process(image.data, image.cols, image.rows, detections, eyePairs);
        if (!resDet)
        {
            std::cout << "Could not detect frome image" << std::endl;
        }
        else
        {
            std::cout << "Number of faces: " << detections.size() << std::endl;
        }
    }
    std::cerr << "Reached end of main function" << std::endl;
    delete detector;
    return 0;
}

```

Here is log:

```
Load detection model
Graph: /root/face-detection/mediapipe/mediapipe/graphs/face_detection/face_detection_desktop_live.pbtxt
Detection Min Score: 0.6
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20230406 12:02:00.120606 3892281 example_impl.cpp:48] Get calculator graph config contents: # MediaPipe graph that performs face mesh with TensorFlow Lite on CPU.

# CPU buffer. (ImageFrame)
input_stream: "input_video"

# Output image with rendered results. (ImageFrame)
output_stream: "output_video"
# Detected faces. (std::vector<Detection>)
output_stream: "face_detections"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Subgraph that detects faces.
node {
  calculator: "FaceDetectionShortRangeCpu"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "DETECTIONS:face_detections"
}

# Converts the detections to drawing primitives for annotation overlay.
node {
  calculator: "DetectionsToRenderDataCalculator"
  input_stream: "DETECTIONS:face_detections"
  output_stream: "RENDER_DATA:render_data"
  node_options: {
    [type.googleapis.com/mediapipe.DetectionsToRenderDataCalculatorOptions] {
      thickness: 4.0
      color { r: 255 g: 0 b: 0 }
    }
  }
}


# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "render_data"
  output_stream: "IMAGE:output_video"
}
I20230406 12:02:00.122481 3892281 example_impl.cpp:54] Initialize the calculator graph.
I20230406 12:02:00.130086 3892281 example_impl.cpp:57] Start running the calculator graph.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Initialized TensorFlow Lite runtime.
Read image: /root/data/images/S243-03-t10_01.ppm
VERBOSE: Replacing 164 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 1 partitions for the whole graph.
Number of detection boxes: 1
Detection score: 0.953089 
Number of faces: 1
Read image: /root/data/images/S425-04-t10_01.ppm
Couldn't get packet from graph.
Could not detect frome image
Read image: /root/data/images/S430-01-t10_01.ppm
I20230406 12:02:00.174587 3892281 example_impl.cpp:80] Failed to add packet to input stream. Call m_graph.WaitUntilDone() to see error (or destroy Example object)
Could not detect frome image
Read image: /root/data/images/S225-02-t10_01.ppm
I20230406 12:02:00.177475 3892281 example_impl.cpp:80] Failed to add packet to input stream. Call m_graph.WaitUntilDone() to see error (or destroy Example object)
Could not detect frome image
Read image: /root/data/images/S468-02-t10_01.ppm
I20230406 12:02:00.183112 3892281 example_impl.cpp:80] Failed to add packet to input stream. Call m_graph.WaitUntilDone() to see error (or destroy Example object)
Could not detect frome image
Read image: /root/data/images/S384-02-t10_01.ppm
I20230406 12:02:00.184715 3892281 example_impl.cpp:80] Failed to add packet to input stream. Call m_graph.WaitUntilDone() to see error (or destroy Example object)
Could not detect frome image
Read image: /root/data/images/S383-01-t10_01.ppm
I20230406 12:02:00.186154 3892281 example_impl.cpp:80] Failed to add packet to input stream. Call m_graph.WaitUntilDone() to see error (or destroy Example object)
Could not detect frome image
Read image: /root/data/images/S377-01-t10_01.ppm
I20230406 12:02:00.195933 3892281 example_impl.cpp:80] Failed to add packet to input stream. Call m_graph.WaitUntilDone() to see error (or destroy Example object)
Could not detect frome image
Read image: /root/data/images/S401-02-t10_01.ppm
I20230406 12:02:00.198196 3892281 example_impl.cpp:80] Failed to add packet to input stream. Call m_graph.WaitUntilDone() to see error (or destroy Example object)
Could not detect frome image
Read image: /root/data/images/S419-09-t10_01.ppm
I20230406 12:02:00.199273 3892281 example_impl.cpp:80] Failed to add packet to input stream. Call m_graph.WaitUntilDone() to see error (or destroy Example object)
Could not detect frome image
Read image: /root/data/images/S457-01-t10_01.ppm
I20230406 12:02:00.200448 3892281 example_impl.cpp:80] Failed to add packet to input stream. Call m_graph.WaitUntilDone() to see error (or destroy Example object)
Could not detect frome image
Reached end of main function
I20230406 12:02:00.200557 3892281 example_impl.cpp:25] Shutting down.
I20230406 12:02:00.201716 3892281 example_impl.cpp:32] Error in WaitUntilDone(): INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
; Packet timestamp mismatch on a calculator receiving from stream "input_video". Current minimum expected timestamp is 1 but received 0. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.
```

I also checked that the image input was correct. Could you give me some advice?

**Comment by ayushgdev** [comment]
Hello @thang-dao 
The error indicates that the timestamp of the frame is not correct. This is because in your [code](https://github.com/google/mediapipe/issues/4232#issue-1650884634), there is a line
`graph.AddPacketToInputStream("image", mediapipe::Adopt(input_frame.release()).At(mediapipe::Timestamp(20000)));`
Here, the timestamp is a constant which should be actually dynamically set by incrementing it with each tick. This should resolve the issue. Check the code [here](https://github.com/google/mediapipe/blob/331692577e8f9bd77d239519ca28657ce4148d83/mediapipe/examples/desktop/demo_run_graph_main.cc#L112) for reference.

**Comment by thang-dao** [comment]
Thanks so much @ayushgdev
