### ISSUE TITLE
model output in embedded device with C？

### ISSUE THREAD

**Issue by RTL8710** [google/mediapipe#4234]
How to efficiently and succinctly convert the output of the model into the structure of the C language by porting the mediapipe model (object_dection) to the arm embedded system?
image

**Comment by ayushgdev** [comment]
@RTL8710 Would you please elaborate your query with complete details like the use case you are addressing, the embedded system you are targetting, and which MediaPipe solution you are trying to use?

**Comment by ayushgdev** [comment]
@RTL8710 MediaPipe uses PyBind11 internally for  C++ integration in Python. However, in your use case, you need to parse output by python in C language. This can be done by embedding the python interpreter in C. Please check the PyBind11 documentation [here](https://pybind11.readthedocs.io/en/stable/advanced/embedding.html) for such use case.

**Comment by RTL8710** [comment]
Thank you very much for your answer!

Introducing the entire Mediapipe project requires the use of PyBind11, but using PyBind11 is too large for embedded systems, so it is not suitable. My embedded system TPU can already parse the output of the model, but how can the post-processing of the model output concisely parse the detection data structure (similar to the screenshot section)?
![image](https://user-images.githubusercontent.com/22052451/230556570-3732997a-bb83-4467-a152-2b616eb75acf.png)

**Comment by RTL8710** [comment]
I looked at the source code  [TfLiteTensorsToDetectionsCalculator::ProcessCPU](https://github.com/google/mediapipe/blob/7b067a1fda2a3ffd3836fdf51b85b162dd696ee6/mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc#L278) in the last few days and found the answer I needed.

**Comment by ayushgdev** [comment]
@RTL8710 Would you please share on the solution that worked for you so that the community can also benefit for similar future requirements?

**Comment by RTL8710** [comment]
[DecodeBoxes](https://github.com/google/mediapipe/blob/7b067a1fda2a3ffd3836fdf51b85b162dd696ee6/mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc#L584) is model output decode，C language overwrite it。
