### ISSUE TITLE
Determine pose world landmarks from tflite model

### ISSUE THREAD

**Issue by vigneshrk29** [google/mediapipe#4238]
Hi,

I am running a custom programe loading the tflite model for pose landmarks and have been able to plot a skeleton using the output ((1,195)) array. But I am not able to understand how to get pose landmarks in the world reference frame or which output it is stored in?

I am not able to determine the logic using the ms_pose pipeline given in the tutorials. 

Sorry

**Comment by ayushgdev** [comment]
Hello @vigneshrk29 Would you please elaborate on the language you are using, whether you are using Lite/Full model?
Also, if possible, can you please share a minimal example code to reproduce the issue at our end?

**Comment by ayushgdev** [comment]
Hello @vigneshrk29 
The pose world landmarks are present in the index 4 of the output. 

**How to get this information?**
If you check the pose solution's pbtxt files,you can reach [`tensors_to_pose_landmarks_and_segmentation.pbtxt`](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/tensors_to_pose_landmarks_and_segmentation.pbtxt#L91) by following the initial graph files. In this file, check the `SplitTensorVectorCalculator`. It outputs few tensors among which is the `world_landmarks_tensor` as well. 
The tensors give the following information:

- landmarks - 2D landmarks
- pose_flag - whether pose is present in the image
- segmentation - foreground/background segmentation mask
- heatmap - heatmap for 33 landmarks to refine those prediced in 2D output
- world_landmarks - 3D landmarks in metric space

If you use `pprint.pprint(output)` directly in your code, you will see the following output:
```
[{'dtype': <class 'numpy.float32'>,
  'index': 337,
  'name': 'Identity',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
                              'scales': array([], dtype=float32),
                              'zero_points': array([], dtype=int32)},
  'shape': array([  1, 195], dtype=int32),
  'shape_signature': array([  1, 195], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': <class 'numpy.float32'>,
  'index': 342,
  'name': 'Identity_1',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
                              'scales': array([], dtype=float32),
                              'zero_points': array([], dtype=int32)},
  'shape': array([1, 1], dtype=int32),
  'shape_signature': array([1, 1], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': <class 'numpy.float32'>,
  'index': 297,
  'name': 'Identity_2',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
                              'scales': array([], dtype=float32),
                              'zero_points': array([], dtype=int32)},
  'shape': array([  1, 256, 256,   1], dtype=int32),
  'shape_signature': array([  1, 256, 256,   1], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': <class 'numpy.float32'>,
  'index': 298,
  'name': 'Identity_3',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
                              'scales': array([], dtype=float32),
                              'zero_points': array([], dtype=int32)},
  'shape': array([ 1, 64, 64, 39], dtype=int32),
  'shape_signature': array([ 1, 64, 64, 39], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': <class 'numpy.float32'>,
  'index': 339,
  'name': 'Identity_4',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
                              'scales': array([], dtype=float32),
                              'zero_points': array([], dtype=int32)},
  'shape': array([  1, 117], dtype=int32),
  'shape_signature': array([  1, 117], dtype=int32),
  'sparsity_parameters': {}}]
```

This indicates there is a tensor at index 4 of the `output` variable with size [1, 117]. This is the workd_landmarks tensor. It contains 33 keypoints + 6 for debug. Each keypoint has (x, y, z) coordinates in the same order, hence the size [1,117].
