### ISSUE TITLE
Running hand tracking on macOS

### ISSUE THREAD

**Issue by AeroBIade** [google/mediapipe#424]
Hi, I'm using this in macbook 16inch and macOS 10.15.2. I finished all the installation and configuration. I can run the hand tracking and the webcam light turns green. But I can't see any image then the program shutting down. It seems no bug. The terminal shows this:

I0130 15:05:19.199403 354282944 demo_run_graph_main.cc:53] Initialize the calculator graph.
I0130 15:05:19.200191 354282944 demo_run_graph_main.cc:57] Initialize the camera or load the video.
I0130 15:05:21.419981 354282944 demo_run_graph_main.cc:78] Start running the calculator graph.
I0130 15:05:21.420181 354282944 demo_run_graph_main.cc:83] Start grabbing and processing frames.
I0130 15:05:22.421401 354282944 demo_run_graph_main.cc:135] Shutting down.
I0130 15:05:22.656774 354282944 demo_run_graph_main.cc:149] Success!

Can you help me to find out what happened?

**Comment by jiuqiant** [comment]
What's your command to build and run the hand tracking demo?
When you run the webcam demos, the terminal should ask you to get the permission to access the webcam in a pop-up window. Do you see that pop-up window?

**Comment by mcclanahoochie** [comment]
can you verify that a separate webcam program like Photo Booth can correctly open and run the webcam?

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by abreu4** [comment]
I have the same issue on a MacBook Pro 16 inch 2019 running Catalina 10.15.6

> What's your command to build and run the hand tracking demo?
> When you run the webcam demos, the terminal should ask you to get the permission to access the webcam in a pop-up window. Do you see that pop-up window?

I don't get a pop up window



> can you verify that a separate webcam program like Photo Booth can correctly open and run the webcam?

Photo booth works

**Comment by abreu4** [comment]
This worked for me

https://github.com/google/mediapipe/issues/477#issuecomment-695921839
