### ISSUE TITLE
When will the Pose Detection code examples be updated on the mediapipe official website?

### ISSUE THREAD

**Issue by luoziang66** [google/mediapipe#4245]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### Programming Language and version

python

**Comment by kuaashish** [comment]
Hello @luoziang66,
Thank you for your interest in MediaPipe Solutions. We are working towards to publish the solution as soon as solution will be ready from our end. As of now, we can not provide any timeline for this. However, Already known solution will be publicly available once it will be ready here in [page](https://developers.google.com/mediapipe/solutions/examples). Thank you
