### ISSUE TITLE
Remove too many unnecessary breaks (`<br/>`) from README.md

### ISSUE THREAD

**Issue by Neilblaze** [google/mediapipe#4247]
### Description of issue (what needs changing)

The mid-section of the [`README`](https://github.com/google/mediapipe/blob/master/README.md) file seems blank & has been produced with too many unnecessary breaks.

### Clear description

Check this ⬇️  https://github.com/google/mediapipe/blob/065d7507818e9bf6f93ae38cbab805c6a4414907/README.md?plain=1#L19-L21

### Request visuals, if applicable

Check this ⬇️ <br/>
![image](https://user-images.githubusercontent.com/48355572/230229548-988b5398-00ff-4045-b47a-88ee3f6069b9.png)

### Submit a pull request?

Yes, I'd love to create a PR to fix this.

**Comment by kuaashish** [comment]
Hello @Neilblaze,
Thank you raising this pull request. We are forwarding request internally and let you know once request will be merged from our end.
