### ISSUE TITLE
hang on when error

### ISSUE THREAD

**Issue by jiqimaogou** [google/mediapipe#425]
if the graph has one error, the packet will not be added to the graph forever, how do i clear the error and let the packet can be added again?

**Comment by jiuqiant** [comment]
According to [this code comment](https://github.com/google/mediapipe/blob/master/mediapipe/framework/calculator_graph.h#L240), no packets can be added to the graph if there is an error. When an error occurs, most clients usually call Cancel() and WaitUntilDone() in sequence to shut down the graph and handle the error. May I know why you prefer to add new packets anyway?

**Comment by jiqimaogou** [comment]
> According to [this code comment](https://github.com/google/mediapipe/blob/master/mediapipe/framework/calculator_graph.h#L240), no packets can be added to the graph if there is an error. When an error occurs, most clients usually call Cancel() and WaitUntilDone() in sequence to shut down the graph and handle the error. May I know why you prefer to add new packets anyway?

yes, may be some error is not crtical, it can be resume anyway, but I want to the error response.

**Comment by jiqimaogou** [comment]
for example, I have a image to decode, if the image decode error, I want to know the error happened, but the graph don't stop anyway.

may be I can add an stream to listen the error, and all error send to the stream.
