### ISSUE TITLE
How to run MediaPipe's 3D Pose Landmark Detection on a GPU?

### ISSUE THREAD

**Issue by kearron** [google/mediapipe#4252]

**Comment by kuaashish** [comment]
Hello @kearron,
Thank you for your interest in MediaPipe Solutions. We are working towards publishing the solution as soon as updating the supported platform in [page](https://developers.google.com/mediapipe/solutions/examples). As of now, we cannot provide any timeline for this. However, already a known solution/supported platforms will be publicly available in the same page.
