### ISSUE TITLE
How to add face filter like a mask and the crown on a live feed 

### ISSUE THREAD

**Issue by somnathX** [google/mediapipe#4255]
Hello, I am working on a personal project. The task is to create a live video feed and add filters like a crown and a face mask in 3d similar to filters in google meet. I am using gltf format. I have written a code for png file using threejs texture and mediapipe. However I haven't got any good solution for gltf formats i.e. 3d files. 

Can someone help on this please?

**Comment by ayushgdev** [comment]
Hello @somnathX Would you please elaborate your query in terms of the solution you are using and whether you are using legacy mediapipe solutions or the new Tasks API?
