### ISSUE TITLE
face_blendershape is a tflite, how to  process 468 face_landmark? because  I know tflite input is (1 , 146 , 2)

### ISSUE THREAD

**Issue by mohui37** [google/mediapipe#4257]
This template is for miscellaneous issues not covered by the other issue categories

For questions on how to work with MediaPipe, or support for problems that are not verified bugs in MediaPipe, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mediapipe) and [Slack](https://mediapipe.page.link/joinslack) communities.

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/google/mediapipe/security).

**Comment by ayushgdev** [comment]
Hello @mohui37 
Would you please elaborate your query with complete details like the platform you are using, the MediaPipe version, the OS being used and the your use case which is not being addressed by already offered solutions?
