### ISSUE TITLE
Compiling src/google/protobuf/any_lite.cc failed: (Exit 1)

### ISSUE THREAD

**Issue by rolandeke** [google/mediapipe#4259]
### OS Platform and Distribution

Windows 11 (WSL)

### Programming Language and version

C++

### Android AAR (if android)

None

### Describe the problem

```shell
I am trying to build the handtrackinggpu example in my ubuntu WSL OS but it fails
```

### Complete Logs

```shell
ERROR: /home/<USERNAME>/.cache/bazel/_bazel_<USERNAME>/9b0c45ac7d66435dc85b349a16a12d35/external/com_google_protobuf/BUILD:155:11: Compiling src/google/protobuf/any_lite.cc failed: (Exit 1): clang failed: error executing command (from target @com_google_protobuf//:protobuf_lite) external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target ... (remaining 49 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
src/main/tools/linux-sandbox-pid1.cc:518: "execvp(external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang, 0x102a720)": No such file or directory
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by rolandeke** [comment]
I get this error below when I try to run the build_android_example.sh script

ERROR: /home/<USERNAME>/.cache/bazel/_bazel_<USERNAME>/9b0c45ac7d66435dc85b349a16a12d35/external/com_google_absl/absl/types/BUILD.bazel:165:11: Compiling absl/types/bad_variant_access.cc failed: (Exit 1): clang failed: error executing command (from target @com_google_absl//absl/types:bad_variant_access) external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target ... (remaining 56 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
src/main/tools/linux-sandbox-pid1.cc:518: "execvp(external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang, 0x17ed7e0)": No such file or directory
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.428s, Critical Path: 4.69s
INFO: 376 processes: 179 internal, 197 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by kuaashish** [comment]
Hello @rolandeke,
Would you please let us know the complete steps followed to reproduce the issue from our end? Thank you
