### ISSUE TITLE
multipleperson pose estimation using mediapipe

### ISSUE THREAD

**Issue by sidh1603** [google/mediapipe#4261]
Hi,

I want to pose estimation for multiple person using media pipe , Would it be possible to make a multiple pose detection on MediaPipe?

even i tried to find solution on this link https://github.com/Gidrian/Mediapipe-YOLO_Multiperson.git
but this link is no more active.

Thanks

**Comment by kuaashish** [comment]
Hello @sidh1603,
Thank you for your interest in MediaPipe Solutions, BlazePose, Pose model can only detect single person from a image/video frame cropped to contain only one person. If you check page 4->Attributes section of [Pose Model Card](https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview), you will find the following information:

> Human Full-body cropped from the captured frame should contain a single person placed in the center of the image.

**Comment by adrianloy** [comment]
This is actually now supported directly by mediapipe, just set the `num_pose` parameter to something greater than 1, see https://developers.google.com/mediapipe/solutions/vision/pose_landmarker. However, I found the performance for detecting multiple person not to be very high.
