### ISSUE TITLE
How can I install mediapipe to jetson nano 

### ISSUE THREAD

**Issue by Liampour** [google/mediapipe#4264]
### OS Platform and Distribution

jetpack 4.6

### Programming Language and version

python

### Android AAR (if android)

None

### Describe the problem

```shell
I have tried to install mediapipe to jetson nano following this tutorial
https://github.com/Melvinsajith/How-to-Install-Mediapipe-in-Jetson-Nano
After completing the installation when I try to run a hand tracking model an error is appearing
Can't find file: mediapipe/modules/hand_landmark/hand_landmark.tflite
```

### Complete Logs

```shell
W20230408 05:55:25.453804  8858 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/hand_landmark/hand_landmark.tflite
```

**Comment by kuaashish** [comment]
Hello @kuaashish,
MediaPipe has not been tested on the Edge devices such as Jeston Nano. Only solutions have been tested on edge device mentioned [here](https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/README.md) and we can see that the repo referred here belongs to individual user suggest you to raise the issue in the relevant repo. Thank you
