### ISSUE TITLE
How to output packet threadsafety in other loop threads?

### ISSUE THREAD

**Issue by xia-chu** [google/mediapipe#4265]
I have a requirement that i can call an asynchronous api in my `Calculator` like this:

```c++
class HttpCallbackCalculator : public CalculatorBase {
public:
    static absl::Status GetContract(CalculatorContract *cc) {
        // ...
    }

    absl::Status Open(CalculatorContext *cc) override {
        // ...
    }

    absl::Status Close(CalculatorContext *cc) override {
        // ...
    }
   
    absl::Status Process(CalculatorContext *cc) override {
       auto requester = std::make_shared<HttpRequester>(EventLoop::getInstance());
       // ... init requester
       
       // submit a http request
       requester->start([cc](Response &res){
            // Http reponsed in event loop thread, this may cause a threadsafety problem, is this okay?
            // I do not want output packet in next `Process` loop, because that would lead to uncertain delays
            cc->Outputs().Tag("").AddPacket(...).At(cc->InputTimestamp()));
       });
       return absl::OkStatus();
    }
```

Thank you very much!

**Comment by xia-chu** [comment]
I'm very sorry, but I tried to check the documents and wiki but i couldn't find the answer

**Comment by kuaashish** [comment]
Hello @xia-chu,
Could you please elaborate your query with complete details. We suggest to fill the issue [template](https://github.com/google/mediapipe/issues/new/choose) to receive the maximum relevant information to look into the issue better. Thank you

**Comment by kuaashish** [comment]
@xia-chu,
Please allow us sometime to share the possible solution on the use case mentioned.

**Comment by xia-chu** [comment]
> @xia-chu, Please allow us sometime to share the possible solution on the use case mentioned.

Thanks!

**Comment by lk-chen** [comment]
Hi @xia-chu ,

Currently It will not work as you expected. Because `CalculatorContext` will be cleaned up after `Process()`, thus you can no longer access `cc->Outputs()` afterwards.

**Comment by xia-chu** [comment]
> Hi @xia-chu ,
> 
> Currently It will not work as you expected. Because `CalculatorContext` will be cleaned up after `Process()`, thus you can no longer access `cc->Outputs()` afterwards.
> 
> The most simple workaround is to use a lock to block until response comes back from callback.

Yes, block `Process`  thread is a good way, 
However, this method cannot achieve the maximum concurrent performance of asynchronous IO。

My current approach is to save the reponse in a queue after an asynchronous callback and wait until the next process and then outputting them。

To reduce the uncertain delay of the next `Process` call, we added a `TICK` clock input signal to the `Calculator` to 
 drive the `Process` to be called in a timely manner.

**Comment by kuaashish** [comment]
@xia-chu,
Please let us know if we can move the status of the issue to close if you do not require further support from our end. 
Thank you

**Comment by xia-chu** [comment]
Ok, it seems that there is no better solution besides the `TICK signal` solution.
This issue can be closed, thanks.

**Comment by LiuYi-Up** [comment]
> Ok, it seems that there is no better solution besides the `TICK signal` solution. This issue can be closed, thanks.

Hi, excuse me. Did you have resolve the problem that run mediapipe in multi threads? Could you share the example?

I'm looking forward your reply!

Best wishes!

**Comment by xia-chu** [comment]
> > Ok, it seems that there is no better solution besides the `TICK signal` solution. This issue can be closed, thanks.
> 
> Hi, excuse me. Did you have resolve the problem that run mediapipe in multi threads? Could you share the example?
> 
> I'm looking forward your reply!
> 
> Best wishes!

I did it like this:
```c++
class HttpCallbackCalculator : public CalculatorBase {
public:
    static absl::Status GetContract(CalculatorContract *cc) {
        // input
        cc->Inputs().Tag("").Set<StreamSet>();

        // TICK input signal to drive outputing
        cc->Inputs().Tag("TICK").SetAny();

        // output
        cc->Outputs().Tag("").Set<StreamSet>();
        return absl::OkStatus();
    }

   absl::Status Process(CalculatorContext* cc) override {
        if (!cc->Inputs().Tag("").Value().IsEmpty()) {
            // input
            auto requester = std::make_shared<HttpRequester>(EventLoop::getInstance());
           // ... init requester
           
           // submit a http request
           requester->start([cc](Response &res){
                // Http reponsed in event loop thread,  save result in a queue
                save(res);
           });
        } else {
            // TICK input signal to drive outputing(consume the queue)
            output(cc);
        }
        return absl::OkStatus();
    }
```
