### ISSUE TITLE
Hair segmentation issue in python

### ISSUE THREAD

**Issue by Rameshv** [google/mediapipe#4266]
I am trying to use this hair segmentation model https://storage.googleapis.com/mediapipe-assets/hair_segmentation.tflite in python and I was following the python guide from this https://developers.google.com/mediapipe/solutions/vision/image_segmenter/python

And using the same notebook mentioned in the link https://colab.research.google.com/github/googlesamples/mediapipe/blob/main/examples/image_segmentation/python/image_segmentation.ipynb

I am able to download the model with

`!wget -O hair.tflite -q https://storage.googleapis.com/mediapipe-assets/hair_segmentation.tflite`

but when trying to run the inference, using the below code

```
base_options = BaseOptions(model_asset_path='hair.tflite')
options = vision.ImageSegmenterOptions(base_options=base_options,running_mode=VisionRunningMode.IMAGE,
                                              output_type=OutputType.CATEGORY_MASK)
 x = vision.ImageSegmenter.create_from_options(options)
```

I am getting the error on line `vision.ImageSegmenter.create_from_options(options)`

```
The input tensor should have dimensions 1 x height x width x 3. Got 1 x 512 x 512 x 4.
``` 

I suspect this is due to tensor size mismatch between the hair model and Vision image segmenter. But I could't find any references to that and stuck.

heres the complete stack trace

<img width="1618" alt="Screenshot 2023-04-10 at 9 57 27 AM" src="https://user-images.githubusercontent.com/750555/230825254-4220c2ef-02b8-4d9f-8e7f-3157c3b24116.png">

**Comment by kuaashish** [comment]
Hi @Rameshv,
Thank you for raising a fresh issue, this is already known to us and we are working towards fix. As workaround, you can load the file manually and use model_asset_buffer: https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/core/base_options.py#L47

Please let us know if the above resolves the issue. Thank you

**Comment by kuaashish** [comment]
Hi @Rameshv,
Could let us know the status of the [above](https://github.com/google/mediapipe/issues/4266#issuecomment-1501383167) if the issue has been resolved or further need help from our end. Thank you!

**Comment by Rameshv** [comment]
Thanks @kuaashish for the response

But I still got the same issue. I have loaded `hair_segmentation.tflite` and used it in `model_asset_buffer`, but its still the same issue

**Comment by kuaashish** [comment]
@Rameshv,
Would you please let us know the information about the OS using, Python Version to reproduce the issue from our end? We suggest to fill the issue [template](https://github.com/google/mediapipe/issues/new/choose) to receive maximum relevant info to understand the issue better and share the possible solution. Thank you

**Comment by ayushgdev** [comment]
Hello @Rameshv Your suspicion is correct. If you check hair segmentation solution graph [here](https://github.com/google/mediapipe/blob/3fdd7f36185ce11c72e76fb9738b1941801dbad8/mediapipe/graphs/hair_segmentation/hair_segmentation_mobile_gpu.pbtxt#L78), it needs number of channels as 4. That is why the error shows the actual shape it got is 1x512x512x4. It infers this from the tflite file. 

However, the ImageSegmenter API [explicitly states](https://github.com/google/mediapipe/blob/3fdd7f36185ce11c72e76fb9738b1941801dbad8/mediapipe/tasks/python/vision/image_segmenter.py#L118) the channels should be 1 or 3. And the batch can only be 1. Hence the error states the expected input was 1 x any height x any width x 3. If you check metadata for DeepLab v3 model, it also expects input to be 257x257x**3**. Hence it works.

**Comment by Rameshv** [comment]
Thanks @ayushgdev for the clarification.

So what do you think is better way to approach this? Is it all possible to do with ImageSegmenter API.??

any pointers to solve this would be really appreciated. I am new to python but I can start digging if I am shown a path..

thanks

**Comment by bencwallace** [comment]
Perhaps it would be possible to find a workaround if the meaning of the fourth channel was made clear. Is it alpha/transparency? CMYK? Time (for video)?

**Comment by ayushgdev** [comment]
@Rameshv There is a possible solution for it as per analysis. Please allow us some more time to investigate on the issue. Apologies for the delay.

**Comment by ayushgdev** [comment]
Hello @Rameshv This issue has been fixed in MediaPipe v0.9.3.0. Please upgrade the package and it should start working.

**Comment by Rameshv** [comment]
Thanks @ayushgdev 
Will download and check in a bit

**Comment by Rameshv** [comment]
I just tried the MediaPipe v0.9.3.0 and the error is gone and it can produce the hair segmentation. But the issue now is, its not producing the correct segmentation.

heres the source image I tried
![13147680-fd2e-4d67-b29a-89b9a6752703](https://user-images.githubusercontent.com/750555/235066549-263e87b3-1c2a-4a3d-911e-9114927b4c1c.jpeg)

And heres the hair segmentation result
![download (36)](https://user-images.githubusercontent.com/750555/235066601-e4cea82c-5144-4d75-8f9e-ce0d1b16e0de.png)

And the same image producing correct segmentation with selfie segmentaion
![download (37)](https://user-images.githubusercontent.com/750555/235066658-1f5e37b1-be25-43f7-975b-86cbe186e8e0.png)

And with deeplabv3
![download (38)](https://user-images.githubusercontent.com/750555/235066713-d46374e0-6fc0-4333-9a16-1fa0eba68ed1.png)

As you can see both the selfie and deeplabv3 segmentaion produce correct results, but the hair segmentation is not.

any ideas what could be the issue??

**Comment by WillReynolds5** [comment]
Same problem as above, bad mask on every image i try.

**Comment by ayushgdev** [comment]
Hello @Rameshv hair segmentation will only produce a mask for the hair. While in contrast, the selfie segmentation will produce mask for human body. Hence both are different applications and incomparable.

**Comment by Rameshv** [comment]
Hi @ayushgdev I think you misunderstood me. What I said was the hair segmentation doesnt produce correct hair mask and not it should be same as self segmentation. if you can look at the hair mask produced, it is completely different from the source image. Hope this helps

**Comment by ayushgdev** [comment]
Hello @Rameshv 
Thanks for bringing this issue. Answer to this will help others as well. As conveyed [earlier](https://github.com/google/mediapipe/issues/4266#issuecomment-1506691008), hair segmentation requires 4 channels while the output of `mp.Image.create_from_file(image_file_name)` creates an image representation with 3 channels. Hence, the last channel is treated as alpha channel and based on that, the computation happens. 
To resolve this issue, we can add an empty alpha channel to the image. 
So you can simply use opencv to read the image, add alpha channel, and then create a MediaPipe Image object using `mp.Image()` constructor.

```python
#  image = mp.Image.create_from_file(image_file_name)      <----------- Comment this out

# read image using OpenCV
rgb_image = cv2.imread("person.jpeg")
rgba_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2RGBA)
# set alpha channel to empty.
rgba_image[:,:,3] = 0
# create MP Image object from numpy array
image = _Image(image_format=_ImageFormat.SRGBA, data=rgba_image)
```

**Comment by mariomosko** [comment]
@ayushgdev 
Is there any chance that you could show the entire implementation the _Image part is not very clear.
Thank you in advance

**Comment by ayushgdev** [comment]
_Image is essentially Image class. Check the imports below:
```
from mediapipe.python._framework_bindings import image as image_module
_Image = image_module.Image
```

**Comment by ayushgdev** [comment]
No problem. ImageFormat is imported as below
```
from mediapipe.python._framework_bindings import image_frame
_ImageFormat = image_frame.ImageFormat
```

**Comment by mariomosko** [comment]
@ayushgdev  thank you 

for me personally now it works!
thank you so much

**Comment by Gauravi1** [comment]
@ayushgdev can you please provide me full code of hair segmentation
