### ISSUE TITLE
To build, for example, the C++ example app of the legacy MediaPipe Hand Detection solution with CPU. failed

### ISSUE THREAD

**Issue by shizhixiao** [google/mediapipe#4267]
### OS Platform and Distribution

Linux Ubuntu 22.04

### Compiler version

gcc/g++ 9

### Programming Language and version

python 3.10

### Installed using virtualenv? pip? Conda?(if python)

pip

### Bazel version

6.1

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.6.0

### Describe the problem

```shell
ERROR: /home/gc/mediapipe/mediapipe/util/BUILD:160:11: Compiling mediapipe/util/annotation_renderer.cc failed: (Exit 1): gcc failed: error executing command (from target //mediapipe/util:annotation_renderer) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 57 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from ./mediapipe/util/annotation_renderer.h:20,
                 from mediapipe/util/annotation_renderer.cc:15:
./mediapipe/framework/port/opencv_core_inc.h:18:10: fatal error: opencv2/core/version.hpp: No such file or directory
   18 | #include <opencv2/core/version.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 69.598s, Critical Path: 67.94s
INFO: 167 processes: 129 internal, 38 linux-sandbox.
FAILED: Build did NOT complete successfully
```

### Complete Logs

```shell
opencv_linux.BUILD already edited as below：
linkopts = [ 
        "-l/usr/local/lib",
        "-l:libopencv_core.so",
        "-l:libopencv_calib3d.so",
        "-l:libopencv_features2d.so",
        "-l:libopencv_highgui.so",
        "-l:libopencv_imgcodecs.so",
        "-l:libopencv_imgproc.so",
        "-l:libopencv_video.so",
        "-l:libopencv_videoio.so",
    ],
```

**Comment by shizhixiao** [comment]
I made some modifications in opencv_linux.build according to the official documents, and now the error has changed：

In file included from mediapipe/calculators/video/opencv_video_encoder_calculator.cc:30:
./mediapipe/framework/port/opencv_video_inc.h:88:10: fatal error: opencv2/optflow.hpp: No such file or directory
   88 | #include <opencv2/optflow.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~

**Comment by shizhixiao** [comment]
i installed libopencv-contrib-dev ,and now Build completed successfully~
thank you

**Comment by shizhixiao** [comment]
new problem， when i run it :

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.6.0) /home/gc/opencv-4.6.0/modules/core/src/matrix_wrap.cpp:1476: error: (-27:Null pointer) create() called for the missing output array in function 'create'

what should i do？ Reduce the version of opencv？

**Comment by kuaashish** [comment]
Hello @shizhixiao,
Glad to hear that the issue has been resolved. Update: I followed the installation steps mentioned [here](https://developers.google.com/mediapipe/framework/getting_started/install#installing_on_debian_and_ubuntu) and able to run hello_world example on Ubuntu 22.04.2, Python 3.10.6, OpenCV 4.6.0.66, Bazel 6.1.0 with gcc version 11.3.0. 
Please build using the mentioned configuration and let us know if the error still persists.
<img width="1098" alt="Screenshot 2023-04-10 at 4 21 39 PM" src="https://user-images.githubusercontent.com/98159216/230889007-8c61da98-1ca4-4e75-8d76-6f4f347ac79f.png">
<img width="1093" alt="Screenshot 2023-04-10 at 4 20 54 PM" src="https://user-images.githubusercontent.com/98159216/230889114-76a5a3de-2c13-4fb6-828d-0c760f3236f4.png">

Thank you!
