### ISSUE TITLE
RuntimeError: Unable to initialize runfiles: ERROR: external/bazel_tools/tools/cpp/runfiles/runfiles.cc(120): cannot find runfiles (argv0="")

### ISSUE THREAD

**Issue by ywugwu** [google/mediapipe#4272]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

windows11

### Programming Language and version

Python 3.8, 3.9, 3.10

### Solution

Gesture Recognition

### Describe the actual behavior

Fail to create gesture recognizer from the official code: `GestureRecognizer.create_from_options(options)`

I got RuntimeError:
```
RuntimeError                              Traceback (most recent call last)
Cell In[4], line 21
     15     print('gesture recognition result: {}'.format(result))
     17 options = GestureRecognizerOptions(
     18     base_options=BaseOptions(model_asset_path='gesture_recognizer.task'),
     19     running_mode=VisionRunningMode.LIVE_STREAM,
     20     result_callback=print_result)
---> 21 with GestureRecognizer.create_from_options(options) as recognizer:
     22     print('gesture recognizer created')

File c:\Users\Wuy19\.conda\envs\py38\lib\site-packages\mediapipe\tasks\python\vision\gesture_recognizer.py:296, in GestureRecognizer.create_from_options(cls, options)
    277   options.result_callback(gesture_recognizer_result, image,
    278                           timestamp.value // _MICRO_SECONDS_PER_MILLISECOND)
    280 task_info = _TaskInfo(
    281     task_graph=_TASK_GRAPH_NAME,
    282     input_streams=[
   (...)
    294     ],
    295     task_options=options)
--> 296 return cls(
    297     task_info.generate_graph_config(
    298         enable_flow_limiting=options.running_mode ==
    299         _RunningMode.LIVE_STREAM), options.running_mode,
    300     packets_callback if options.result_callback else None)
...
     65       'callback should not be provided.')
---> 66 self._runner = _TaskRunner.create(graph_config, packet_callback)
     67 self._running_mode = running_mode

RuntimeError: Unable to initialize runfiles: ERROR: external/bazel_tools/tools/cpp/runfiles/runfiles.cc(120): cannot find runfiles (argv0="")
```

### Describe the expected behaviour

An object GestureRecognizer should be initilized

### Standalone code/steps you may have used to try to get what you need

Actually I just used the official code from https://developers.google.com/mediapipe/solutions/vision/gesture_recognizer/python as follows:

```
import mediapipe as mp

BaseOptions = mp.tasks.BaseOptions
GestureRecognizer = mp.tasks.vision.GestureRecognizer
GestureRecognizerOptions = mp.tasks.vision.GestureRecognizerOptions
GestureRecognizerResult = mp.tasks.vision.GestureRecognizerResult
VisionRunningMode = mp.tasks.vision.RunningMode

# Create a gesture recognizer instance with the live stream mode:
def print_result(result: GestureRecognizerResult, output_image: mp.Image, timestamp_ms: int):
    print('gesture recognition result: {}'.format(result))

options = GestureRecognizerOptions(
    base_options=BaseOptions(model_asset_path='gesture_recognizer.task'),
    running_mode=VisionRunningMode.LIVE_STREAM,
    result_callback=print_result)
with GestureRecognizer.create_from_options(options) as recognizer:
    print('gesture recognizer created')
```

**Comment by kuaashish** [comment]
Hello @ywugwu,
This issue is known to us and we are working towards fix. As workaround, you can load the file manually and use model_asset_buffer: https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/core/base_options.py#L47

Please let us know if this resolves the issue. Ref: #4220, Thank you

**Comment by ywugwu** [comment]
> Hello @ywugwu, This issue is known to us and we are working towards fix. As workaround, you can load the file manually and use model_asset_buffer: https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/core/base_options.py#L47
> 
> Please let us know if this resolves the issue. Ref: #4220, Thank you

Hello @kuaashish ,

How can I manually load the file?

I tried reading the model file as a binary file, passing it to BaseOptions via `model_assert_buffer`  and creating a GestureRecognizer as follows:
```
with open('gesture_recognizer.task', 'rb') as f:
    model = f.read()
options = GestureRecognizerOptions(
    base_options=BaseOptions(model_asset_buffer=model),
    running_mode=VisionRunningMode.IMAGE,)
recognizer = vision.GestureRecognizer.create_from_options(options)
```

But this GestureRecognizer can not detect any gestures in my images, so I'm wondering if I did something wrong

**Comment by xiaolinpeter** [comment]
> Hello @ywugwu, This issue is known to us and we are working towards fix. As workaround, you can load the file manually and use model_asset_buffer: https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/core/base_options.py#L47
> 
> Please let us know if this resolves the issue. Ref: #4220, Thank you

hi， @kuaashish, I try this way, I can not solve the problem. (my python version is 3.8 and mediapipe version is 0.9.2.1 for window)
1 the error as follow:
![image](https://user-images.githubusercontent.com/27184803/231379834-14626556-558b-47e0-87d4-ad544f4e19a9.png)
2 my code picture as follow:
![image](https://user-images.githubusercontent.com/27184803/231380031-2aec3e71-4911-4561-84fa-bb86d86bf187.png)
`import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
from baseOptions import BaseOptions
# STEP 2: Create an GestureRecognizer object.
base_options = BaseOptions(model_asset_buffer='gesture_recognizer.task')
options = vision.GestureRecognizerOptions(base_options=base_options)
recognizer = vision.GestureRecognizer.create_from_options(options)

images = []
results = []
IMAGE_FILENAMES = ["images/img.png"]
for image_file_name in IMAGE_FILENAMES:
  # STEP 3: Load the input image.
  image = mp.Image.create_from_file(image_file_name)
  # STEP 4: Recognize gestures in the input image.
  recognition_result = recognizer.recognize(image)
  # STEP 5: Process the result. In this case, visualize it.
  images.append(image)
  top_gesture = recognition_result.gestures[0][0]
  hand_landmarks = recognition_result.hand_landmarks
  results.append((top_gesture, hand_landmarks))
  print(hand_landmarks)
`
I hope you give me some suggestion when you have time, thanks

**Comment by kuaashish** [comment]
Hello @ywugwu,
Thank you for the brining out this bug to our notice. We are able to reproduce the issue using the model_buffer_asset and can see workaround is no longer load the file manually. However, We are going to fix this bug in the upcoming release but can not provide any timeline.
<img width="959" alt="Screenshot 2023-04-12 at 4 22 01 PM" src="https://user-images.githubusercontent.com/98159216/231438496-b905f4cb-e5ca-4322-91d1-8308f576874b.png">

**Comment by kuaashish** [comment]
Hello @ywugwu,
Could you please raise a new issue with complete details to understand issue better from our end? We suggest to fill the issue [template](https://github.com/google/mediapipe/issues/new/choose) to receive the maximum relevant to debug the issue. Thank you

**Comment by ywugwu** [comment]
> Hello @ywugwu, Could you please raise a new issue with complete details to understand issue better from our end? We suggest to fill the issue [template](https://github.com/google/mediapipe/issues/new/choose) to receive the maximum relevant to debug the issue. Thank you

Hi @kuaashish ,

I created a new issue at https://github.com/google/mediapipe/issues/4275. Please let me know if you need any further information.

**Comment by schmidt-sebastian** [comment]
This has already been fixed in `master` and will be part of the next release, which is coming within the next couple of days.

**Comment by MatthiasSagerer** [comment]
> schmidt-sebastian

That sounds great!
How do I know if there's a new release where this has been fixed?
Also, I guess to get the new release I can just `pip install --upgrade --force-reinstall mediapipe`, right?
