### ISSUE TITLE
about face effect?

### ISSUE THREAD

**Issue by Xelawk** [google/mediapipe#4274]
not found for c++ face effect example, but only android example. Why no example for c++?

**Comment by kuaashish** [comment]
Hello @Xelawk,
Thank you for your interest in the MediaPipe solutions. This is in our roadmap already, We are upgrading our face effect solution in the new page [here](https://developers.google.com/mediapipe/solutions/vision/face_landmarker), will become publicly once will be ready from our end. However, we can not provide any timeline for this.

**Comment by andrechen** [comment]
> not found for c++ face effect example, but only android example. Why no example for c++?

you can [wait](https://developers.google.com/mediapipe/solutions/vision/face_landmarker), or check [this](https://github.com/andrechen/mediapipe/tree/master/visualstudio/face_effect) out.
