### ISSUE TITLE
RuntimeError in creating GestureRecognizer

### ISSUE THREAD

**Issue by ywugwu** [google/mediapipe#4275]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

windows 11

### Programming Language and version

Python 3.8, 3.9, 3.10

### MediaPipe version

0.9.2.1

### Solution

Gesture Recognition

### Describe the actual behavior

I just: 

1. create a new conda environment with python=3.8 and install the lastest using `$ python -m pip install mediapipe`

2. Using official code to create a gesture recognizer :
```shell
import mediapipe as mp

BaseOptions = mp.tasks.BaseOptions
GestureRecognizer = mp.tasks.vision.GestureRecognizer
GestureRecognizerOptions = mp.tasks.vision.GestureRecognizerOptions
VisionRunningMode = mp.tasks.vision.RunningMode

# Create a gesture recognizer instance with the image mode:
options = GestureRecognizerOptions(
    base_options=BaseOptions(model_asset_path='/path/to/model.task'),
    running_mode=VisionRunningMode.IMAGE)
with GestureRecognizer.create_from_options(options) as recognizer:
  # The detector is initialized. Use it here.
  # ...
```
3. Then I run the Python file and got RuntimeError: Unable to initialize runfiles: ERROR: external/bazel_tools/tools/cpp/runfiles/runfiles.cc(120): cannot find runfiles (argv0="")

### Describe the expected behaviour

```shell
None
```

### Standalone code/steps you may have used to try to get what you need

```shell
import mediapipe as mp

BaseOptions = mp.tasks.BaseOptions
GestureRecognizer = mp.tasks.vision.GestureRecognizer
GestureRecognizerOptions = mp.tasks.vision.GestureRecognizerOptions
VisionRunningMode = mp.tasks.vision.RunningMode

model_path = 'gesture_recognizer.task'
options = GestureRecognizerOptions(
    base_options=BaseOptions(model_asset_path=model_path),
    running_mode=VisionRunningMode.IMAGE)
with GestureRecognizer.create_from_options(options) as recognizer:
    print('Gesture recognizer created.')
```

**Comment by schmidt-sebastian** [comment]
This has already been fixed in `master` and will be part of the next release, which is coming within the next couple of days.
