### ISSUE TITLE
Missing selfie_mode on new mediapipe js hands solutions

### ISSUE THREAD

**Issue by guptarohan3112** [google/mediapipe#4285]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 10 Laptop 

### Browser and version if the issue happens on browser

Microsoft Edge

### Programming Language and version

Javascript (React)

### Solution

Hands

### Describe the actual behavior

```shell
The selfie_mode option is missing from the updated js library, meaning the handedness of webcam input is the wrong way round. I might be missing something here but it appears to be an omission.
```

### Describe the expected behaviour

```shell
See above
```

### Standalone code/steps you may have used to try to get what you need

```shell
See above
```

**Comment by kuaashish** [comment]
Hello @guptarohan3112,
Would you please let us know the complete detail, Steps you have followed to reproduce the issue and share the possible solution on the issue raised. Thank you

**Comment by TigerHix** [comment]
Bumping this issue as having the exact same problem. In `@mediapipe/hands` package version `0.4.1646424915`, one can create a `Hands` solution with selfie mode enabled by:

```
import {Hands} from "@mediapipe/hands";
const Hands = new Hands();
hands.setOptions({
  maxNumHands: 2,
  selfieMode: true, // <------
  modelComplexity: 1,
  minDetectionConfidence: 0.5,
  minTrackingConfidence: 0.9,
});
```

However, this option is missing from [`HandLandmarkerOptions`](https://github.com/google/mediapipe/blob/c7ba201e6a4bdd822bdc11502702f7284bdedd25/mediapipe/tasks/web/vision/hand_landmarker/hand_landmarker_options.d.ts#L20) in the `@mediapipe/tasks-vision` package.

Seems like a feature gap to me!
