### ISSUE TITLE
Do you have compiled libraries for iOS?It is very difficult for me to compile your project.

### ISSUE THREAD

**Issue by github-liuxu** [google/mediapipe#4289]
Do you have compiled libraries for iOS? And how to get your human bones. It is very difficult for me to compile your project, hope you can send me one. liudongxu@meishesdk.com

**Comment by ayushgdev** [comment]
Hello @github-liuxu We do not offer precompiled binaries for iOS as of now. We can discuss it internally and add this to our plan. But it will surely take time and we cannot commit any timeline yet.

**Comment by github-liuxu** [comment]
This compilation is too difficult for me, if possible, can you help me compile an iOS framework? I want to run this project posetrackinggpu.
mac-mini@liudongxudeMac-Mini mediapipe % bazel build -c opt --config=ios_arm64  //mediapipe/examples/ios/posetrackinggpu:posetrackinggpu
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/e510d0bda0876c4baa3a270dca39b95da7ec6d9e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/9084a21c1fb3a8eb411a7ed010ec1e9fcaa01b01.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "691a29db9c336349e48e04c5c2f4873f2890af5cbfa6e51f4de87fefe6169294"
DEBUG: Repository rules_cc instantiated at:
  /Users/mac-mini/Downloads/mediapipe/WORKSPACE:40:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_mac-mini/be217cfa49df986da4cb345b2b513dd5/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
WARNING: /Users/mac-mini/Downloads/mediapipe/mediapipe/framework/tool/BUILD:197:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /Users/mac-mini/Downloads/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/5eff7fb0cf49215d9f68646512797a2258aa00cc.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //mediapipe/examples/ios/posetrackinggpu:posetrackinggpu (176 packages loaded, 8929 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_mac-mini/be217cfa49df986da4cb345b2b513dd5/external/com_google_absl/absl/status/BUILD.bazel:31:11: Compiling absl/status/status.cc failed: (Exit 1): wrapped_clang_pp failed: error executing command (from target @com_google_absl//absl/status:status) external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 68 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/com_google_absl/absl/status/status.cc:129:30: error: 'value' is unavailable: introduced in iOS 12.0
    return (*payloads)[index.value()].payload;
                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
external/com_google_absl/absl/status/status.cc:147:28: error: 'value' is unavailable: introduced in iOS 12.0
    (*rep->payloads)[index.value()].payload = std::move(payload);
                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
external/com_google_absl/absl/status/status.cc:159:57: error: 'value' is unavailable: introduced in iOS 12.0
    GetPayloads()->erase(GetPayloads()->begin() + index.value());
                                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here
    constexpr value_type& value() &
                          ^
3 errors generated.
Error in child process '/usr/bin/xcrun'. 1
Target //mediapipe/examples/ios/posetrackinggpu:PoseTrackingGpuApp failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 172.899s, Critical Path: 20.71s
INFO: 1004 processes: 573 internal, 431 darwin-sandbox.
FAILED: Build did NOT complete successfully

**Comment by fengyun21** [comment]
I have the same problem。 Hope the mediapipe can offer precompiled binaries for iOS as soon as possible

**Comment by kuaashish** [comment]
Hello @github-liuxu,
Thank you for your interest in the MediaPipe solutions. Now we do not have such Pre-complied binaries to click and run the iOS solutions, However, This we can mark this feature request and based on internal discussion we can prioritize the work.

**Comment by fengyun21** [comment]
> Hello @github-liuxu, Thank you for your interest in the MediaPipe solutions. Now we do not have such Pre-complied binaries to click and run the iOS solutions, However, This we can mark this feature request and based on internal discussion we can prioritize the work.

the mediapipe of 0.9.3 compiled fail, but the mediapipe of 0.9.2.1 compiled ok.  why?

**Comment by schmidt-sebastian** [comment]
The libraries for MediaPipe Tasks will be available on Cocoapods soon.

**Comment by trunghvbk** [comment]
> This compilation is too difficult for me, if possible, can you help me compile an iOS framework? I want to run this project posetrackinggpu. mac-mini@liudongxudeMac-Mini mediapipe % bazel build -c opt --config=ios_arm64 //mediapipe/examples/ios/posetrackinggpu:posetrackinggpu WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE. WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/e510d0bda0876c4baa3a270dca39b95da7ec6d9e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/9084a21c1fb3a8eb411a7ed010ec1e9fcaa01b01.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "691a29db9c336349e48e04c5c2f4873f2890af5cbfa6e51f4de87fefe6169294" DEBUG: Repository rules_cc instantiated at: /Users/mac-mini/Downloads/mediapipe/WORKSPACE:40:13: in Repository rule http_archive defined at: /private/var/tmp/_bazel_mac-mini/be217cfa49df986da4cb345b2b513dd5/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in WARNING: /Users/mac-mini/Downloads/mediapipe/mediapipe/framework/tool/BUILD:197:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use. WARNING: /Users/mac-mini/Downloads/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use. WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/5eff7fb0cf49215d9f68646512797a2258aa00cc.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found INFO: Analyzed target //mediapipe/examples/ios/posetrackinggpu:posetrackinggpu (176 packages loaded, 8929 targets configured). INFO: Found 1 target... ERROR: /private/var/tmp/_bazel_mac-mini/be217cfa49df986da4cb345b2b513dd5/external/com_google_absl/absl/status/BUILD.bazel:31:11: Compiling absl/status/status.cc failed: (Exit 1): wrapped_clang_pp failed: error executing command (from target @com_google_absl//absl/status:status) external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 68 arguments skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging external/com_google_absl/absl/status/status.cc:129:30: error: 'value' is unavailable: introduced in iOS 12.0 return (*payloads)[index.value()].payload; ^ /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here constexpr value_type& value() & ^ external/com_google_absl/absl/status/status.cc:147:28: error: 'value' is unavailable: introduced in iOS 12.0 (*rep->payloads)[index.value()].payload = std::move(payload); ^ /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here constexpr value_type& value() & ^ external/com_google_absl/absl/status/status.cc:159:57: error: 'value' is unavailable: introduced in iOS 12.0 GetPayloads()->erase(GetPayloads()->begin() + index.value()); ^ /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here constexpr value_type& value() & ^ 3 errors generated. Error in child process '/usr/bin/xcrun'. 1 Target //mediapipe/examples/ios/posetrackinggpu:PoseTrackingGpuApp failed to build Use --verbose_failures to see the command lines of failed build steps. INFO: Elapsed time: 172.899s, Critical Path: 20.71s INFO: 1004 processes: 573 internal, 431 darwin-sandbox. FAILED: Build did NOT complete successfully

Hi open your `BUILD` file and change the line 

```MIN_IOS_VERSION = "1`.0"```

to ```MIN_IOS_VERSION = "12.0"```
