### ISSUE TITLE
media sequence optical flow results not correct

### ISSUE THREAD

**Issue by vasnakh** [google/mediapipe#429]
I am using mediapipe 0.6.8 and tensorflow 1.14 and trying to create TFRecords to train activity detection network. The problem is that when I actually check the produced result of optical flow it is not correct and there are noises introduced. I believe the problem happens in PackMediaSeuqnceCalculator or StringToSequenceExampleCalculator or it might be when parsing the TF Records as shown below in the code:

tf.image.convert_image_dtype(
        tf.map_fn(tf.image.decode_jpeg,
                  parsed_sequence[ms.get_forward_flow_encoded_key()],
                  back_prop=False,
                  dtype=tf.uint8), tf.float32)

I have already checked the result produced after the OpenCvImageEncoderCalculator encodes the image and decode it using OpenCV and it seems correct.

**Comment by vasnakh** [comment]
Further investigation shows that the serialization is probably correct, but when tensorflow de-serializes the flow data it gets corrupted.

**Comment by vasnakh** [comment]
Found out that the error occurs when deepmind i3d uses tf.image.decode_jpeg. If the bytes are decoded using opencv the problem gets resolved.

**Comment by jiuqiant** [comment]
Glad. to know that the problem is solved.
