### ISSUE TITLE
Request for mediapipe package availability for Python 3.11 on Windows

### ISSUE THREAD

**Issue by CarryOnWithPrabhIdPrabhdeepSingh** [google/mediapipe#4292]
Dear Mediapipe,
 
I am writing to bring to your attention an issue that I have come across while trying to use the mediapipe package on Python 3.11 for Windows. I have noticed that the package is not currently available for this particular configuration, while it is available for both Linux and Mac OS. This limitation is causing significant issues for myself and many other users who rely on this package for various projects.
I would like to request your help in resolving this issue as mediapipe is an important package for my project, and I am unable to use it on my Windows machine due to this limitation. Furthermore, I have recently created a video titled "Mediapipe Installation Error | No Matching Distribution Found For Mediapipe | CarryOnWithPrabh" where I have discussed this limitation, and the video has been watched by over 2000 people. These users are also struggling with the same issue and require access to this package to continue their projects.
It would be greatly appreciated if you could work on making the mediapipe package available for Python 3.11 on Windows, or kindly check if it was accidentally forgotten. The inclusion of this package on Windows will enable a large community of users to continue their projects without any issues.
Thank you for your attention to this matter. Please let me know if there is any further information that you require to assist with this issue.
 
Best regards,
 
CarryOnWithPrabh (Prabhdeep Singh)

**Comment by ayushgdev** [comment]
Hello @CarryOnWithPrabhIdPrabhdeepSingh 
We understand that Windows is an important platform for the developers to work on and we are receiving several requests for the same (#4171, #2509). We have added mediapipe installation via pip on windows to our roadmap, but we dont have any timeline yet. 

For the time being, we would urge you to follow the installation docs given [here](https://developers.google.com/mediapipe/framework/getting_started/install#installing_on_windows) to setup mediapipe environment for desktop solutions, and then follow the Python package build guide [here](https://github.com/google/mediapipe/blob/master/docs/getting_started/python.md#building-mediapipe-python-package) to build your own python package locally.

**Comment by CarryOnWithPrabhIdPrabhdeepSingh** [comment]
Hello @ayushgdev 
Sorry but, I do not know how to build my own package of python, and I want to tell you that, I don't just want mediapipe to be available for python in Windows, but the specific version of Python: 3.11, mediapipe is available for both Linux and mac, but not windows, and people need mediapipe in python 3.11 to make their projects, If they downgraded python 3.11 to 3.10, there would have to make Virtual environments for each of their projects, and would have to install all of their package required for their projects again. So, Kindly tell me when mediapipe is going to be released for Python 3.11 in windows.

**Comment by CarryOnWithPrabhIdPrabhdeepSingh** [comment]
Hello @ayushgdev
Sorry but, I do not know how to build my own package of python, and I want to tell you that, I don't just want mediapipe to be available for python in Windows, but the specific version of Python: 3.11, mediapipe is available for both Linux and mac, but not windows, and people need mediapipe in python 3.11 to make their projects, If they downgraded python 3.11 to 3.10, there would have to make Virtual environments for each of their projects, and would have to install all of their package required for their projects again. So, Kindly tell me when mediapipe is going to be released for Python 3.11 in windows.

**Comment by ayushgdev** [comment]
Understood @CarryOnWithPrabhIdPrabhdeepSingh . Python 3.11 support is the one being requested here. We shall forward this request to the concerned team.

**Comment by kuaashish** [comment]
@CarryOnWithPrabhIdPrabhdeepSingh,

We have rolled out the newer version 0.10.1 as guided in the [release page](https://github.com/google/mediapipe/releases/tag/v0.10.1) and Support of Python 3.11 in the Windows have been added. However, We are working to update the documentation of Python support. Please build using the Python 3.11 and let us know if you encounter any error. Thank you!!
