### ISSUE TITLE
The Packet stores "::mediapipe::Image", but "mediapipe::ImageFrame" was requested.

### ISSUE THREAD

**Issue by iFCoder** [google/mediapipe#4297]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android

### Describe the actual behavior

```shell
What is the possible reason for reporting this error when obtaining attitude point?
MediaPipe packet creation error: invalid argument: Graph has errors: 
    Packet type mismatch on calculator outputting to stream "image": The Packet stores "::mediapipe::Image", but "mediapipe::ImageFrame" was requested.
```

**Comment by ayushgdev** [comment]
Hello @iFCoder 
This error indicates that the packet that you are querying for data stores `mediapipe::Image` datatype, but in while querying the data from the packet, you are defining the datatype to be `mediapipe::ImageFrame`.

This scenario can arise because of two reasons
- The internal graph provides `mediapipe::Image` data as an output of the pocessing, and while capturing the data from the packet, you are explicitly requesting the `mediapipe::ImageFormat`.
- The internal graph processing tries to query the `mediapipe::ImageFrame` data from the packet, because that is the expected and correct datatype. But the input to the graph was given as `mediapipe::Image`

**Comment by iFCoder** [comment]
Could you please check if this code is correct?

**Comment by iFCoder** [comment]
`public class Poses extends ImageSolutionBase {
    private static final String TAG = "Poses";
    private static final String MODEL_COMPLEXITY = "model_complexity";
    private static final String USE_PREV_LANDMARKS = "use_prev_landmarks";
    private static final String GPU_GRAPH_NAME = "pose_landmark_gpu.binarypb";
    private static final String CPU_GRAPH_NAME = "pose_landmark_cpu.binarypb";
    private static final String IMAGE_INPUT_STREAM = "image";
    private static final ImmutableList<String> OUTPUT_STREAMS =
            ImmutableList.of(
                    "pose_landmarks",
                    "pose_world_landmarks");
    private static final int LANDMARKS_INDEX = 0;
    private static final int WORLD_LANDMARKS_INDEX = 1;
    private static final int INPUT_IMAGE_INDEX = 2;
    private final OutputHandler<PosesResult> outputHandler;
    /**
     * Initializes MediaPipe Hands solution.
     *
     * @param context an Android {@link Context}.
     * @param options the configuration options defined in {@link PosesOptions}.
     */
    public Poses(Context context, PosesOptions options) {
        outputHandler = new OutputHandler<>();
        outputHandler.setOutputConverter(packets -> {
            PosesResult.Builder posesResultBuilder = PosesResult.builder();
            try {
                posesResultBuilder.setMultiPoseLandmarks(
                        getProtoVector(packets.get(LANDMARKS_INDEX), LandmarkProto.NormalizedLandmarkList.parser()));
            } catch (MediaPipeException e) {
                reportError("Error occurs while getting MediaPipe hand landmarks.", e);
            }
            try {
                posesResultBuilder.setMultiPoseWorldLandmarks(
                        getProtoVector(packets.get(WORLD_LANDMARKS_INDEX), LandmarkProto.LandmarkList.parser()));
            } catch (MediaPipeException e) {
                reportError("Error occurs while getting MediaPipe hand world landmarks.", e);
            }
            return posesResultBuilder
                    .setImagePacket(packets.get(INPUT_IMAGE_INDEX))
                    .setTimestamp(
                            staticImageMode ? Long.MIN_VALUE : packets.get(INPUT_IMAGE_INDEX).getTimestamp())
                    .build();
        });

        SolutionInfo solutionInfo =
                SolutionInfo.builder()
                        .setBinaryGraphPath(options.runOnGpu() ? GPU_GRAPH_NAME : CPU_GRAPH_NAME)
                        .setImageInputStreamName(IMAGE_INPUT_STREAM)
                        .setOutputStreamNames(OUTPUT_STREAMS)
                        .setStaticImageMode(options.staticImageMode())
                        .build();

        initialize(context, solutionInfo, outputHandler);
        Map<String, Packet> inputSidePackets = new HashMap<>();
        inputSidePackets.put(MODEL_COMPLEXITY, packetCreator.createInt32(options.modelComplexity()));
        inputSidePackets.put(USE_PREV_LANDMARKS, packetCreator.createBool(!options.staticImageMode()));
        start(inputSidePackets);
    }

    /**
     * Sets a callback to be invoked when a {@link PosesResult} becomes available.
     *
     * @param listener the {@link ResultListener} callback.
     */
    public void setResultListener(ResultListener<PosesResult> listener) {
        this.outputHandler.setResultListener(listener);
    }

    /**
     * Sets a callback to be invoked when the Hands solution throws errors.
     *
     * @param listener the {@link ErrorListener} callback.
     */
    public void setErrorListener(@Nullable ErrorListener listener) {
        this.outputHandler.setErrorListener(listener);
        this.errorListener = listener;
    }
}`

**Comment by iFCoder** [comment]
`   

    public class Poses extends ImageSolutionBase {
    private static final String TAG = "Poses";
    private static final String MODEL_COMPLEXITY = "model_complexity";
    private static final String USE_PREV_LANDMARKS = "use_prev_landmarks";
    private static final String GPU_GRAPH_NAME = "pose_landmark_gpu.binarypb";
    private static final String CPU_GRAPH_NAME = "pose_landmark_cpu.binarypb";
    private static final String IMAGE_INPUT_STREAM = "image";
    private static final ImmutableList<String> OUTPUT_STREAMS =
            ImmutableList.of(
                    "pose_landmarks",
                    "pose_world_landmarks");
    private static final int LANDMARKS_INDEX = 0;
    private static final int WORLD_LANDMARKS_INDEX = 1;
    private static final int INPUT_IMAGE_INDEX = 2;
    private final OutputHandler<PosesResult> outputHandler;

    /**
     * Initializes MediaPipe Hands solution.
     *
     * @param context an Android {@link Context}.
     * @param options the configuration options defined in {@link PosesOptions}.
     */
    public Poses(Context context, PosesOptions options) {
        outputHandler = new OutputHandler<>();
        outputHandler.setOutputConverter(packets -> {
            PosesResult.Builder posesResultBuilder = PosesResult.builder();
            try {
                posesResultBuilder.setMultiPoseLandmarks(
                        getProtoVector(packets.get(LANDMARKS_INDEX), LandmarkProto.NormalizedLandmarkList.parser()));
            } catch (MediaPipeException e) {
                reportError("Error occurs while getting MediaPipe hand landmarks.", e);
            }
            try {
                posesResultBuilder.setMultiPoseWorldLandmarks(
                        getProtoVector(packets.get(WORLD_LANDMARKS_INDEX), LandmarkProto.LandmarkList.parser()));
            } catch (MediaPipeException e) {
                reportError("Error occurs while getting MediaPipe hand world landmarks.", e);
            }
            return posesResultBuilder
                    .setImagePacket(packets.get(INPUT_IMAGE_INDEX))
                    .setTimestamp(
                            staticImageMode ? Long.MIN_VALUE : packets.get(INPUT_IMAGE_INDEX).getTimestamp())
                    .build();
        });

        SolutionInfo solutionInfo =
                SolutionInfo.builder()
                        .setBinaryGraphPath(options.runOnGpu() ? GPU_GRAPH_NAME : CPU_GRAPH_NAME)
                        .setImageInputStreamName(IMAGE_INPUT_STREAM)
                        .setOutputStreamNames(OUTPUT_STREAMS)
                        .setStaticImageMode(options.staticImageMode())
                        .build();

        initialize(context, solutionInfo, outputHandler);
        Map<String, Packet> inputSidePackets = new HashMap<>();
        inputSidePackets.put(MODEL_COMPLEXITY, packetCreator.createInt32(options.modelComplexity()));
        inputSidePackets.put(USE_PREV_LANDMARKS, packetCreator.createBool(!options.staticImageMode()));
        start(inputSidePackets);
    }

    /**
     * Sets a callback to be invoked when a {@link PosesResult} becomes available.
     *
     * @param listener the {@link ResultListener} callback.
     */
    public void setResultListener(ResultListener<PosesResult> listener) {
        this.outputHandler.setResultListener(listener);
    }

    /**
     * Sets a callback to be invoked when the Hands solution throws errors.
     *
     * @param listener the {@link ErrorListener} callback.
     */
    public void setErrorListener(@Nullable ErrorListener listener) {
        this.outputHandler.setErrorListener(listener);
        this.errorListener = listener;
    }
}`

**Comment by ayushgdev** [comment]
Hllo @iFCoder 
This error is coming from [ImageSolutionBase.java ](https://github.com/google/mediapipe/blob/0fc6118680a5ae1d7a424a9912b41993e684b0ae/mediapipe/java/com/google/mediapipe/solutioncore/ImageSolutionBase.java#L168) inside the `sendImage()` function. This is being called from overloaded `send()` which accepts BitMap or TextureFrame as input params. 
Dry running the code from [this](https://github.com/google/mediapipe/blob/0fc6118680a5ae1d7a424a9912b41993e684b0ae/mediapipe/java/com/google/mediapipe/solutioncore/ImageSolutionBase.java#L137) point, one can figure out the statement throwing error is 
```
solutionGraph.addConsumablePacketToInputStream(
            imageInputStreamName, imagePacket, timestamp);
```

Yes the code seems to be okay at this place. However, the error must be coming from the place you are using this Poses class. For example, if you are using `onResume()` and inside it, you are calling 
```
cameraInput.setNewFrameListener(textureFrame -> poses.send(textureFrame));
```
this might be the place to check the datatype of the packet during runtime since the error is a RunTime error.
