### ISSUE TITLE
Hand tracking stuck in Initializing...

### ISSUE THREAD

**Issue by 2j4rmp4jo6** [google/mediapipe#430]
I'm trying Visualizing MediaPipe Graphs, but the example of hand tracking didn't work, after I press run, the Runner will stuck at Initializing..., my webcam will open, but nothing happened, other examples work successfully, did I missed something or my computer isn't well enough to run?

**Comment by mgyong** [comment]
What browser and the version number? We currently support properly only Chrome

**Comment by 2j4rmp4jo6** [comment]
I'm using Chrome 79.0.3945.130

**Comment by mgyong** [comment]
We have fixed the problem. Can you retry? Thks

**Comment by 2j4rmp4jo6** [comment]
Wow it works, thanks a lot.
By the way, is it possible to track muilt-hand?

**Comment by 2j4rmp4jo6** [comment]
OK, thanks a lot!!
