### ISSUE TITLE
HandsLandmark works on CPU with python and GPU with C++

### ISSUE THREAD

**Issue by YikeStone** [google/mediapipe#4304]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Ubuntu 18.04

### MediaPipe Tasks SDK version

latest

### Task name (e.g. Image classification, Gesture recognition etc.)

Hands Landmark

### Programming Language and version (e.g. C++, Python, Java)

python3.7 and c++

### Describe the actual behavior

```shell
When running HandsLandmark with C++, GPU is used, whereas when using HandsLandmark with python CPU is used.

With python, I get this message and GPU usage is 0%: "INFO: Created TensorFlow Lite XNNPACK delegate for CPU."

whereas with C++ I get good GPU usage when running this command:
bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live_gpu.pbtxt 
 --input_video_path=sample.mp4 --output_video_path=output.mp4
```

### Describe the expected behaviour

```shell
When running python HandsLandmark TFLite should use GPU.
```

### Standalone code/steps you may have used to try to get what you need

```shell
import cv2
import time
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

def print_result(result: vision.HandLandmarkerResult, output_image: mp.Image, timestamp_ms: int):
    print('hand landmarker result: {}'.format(result))

# STEP 2: Create an ImageClassifier object.
base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
options = vision.HandLandmarkerOptions(base_options=base_options,
                                               num_hands=2,
                                               running_mode=vision.RunningMode.LIVE_STREAM,
                                               result_callback=print_result)

detector = vision.HandLandmarker.create_from_options(options)

capture = cv2.VideoCapture(0)

try:
    while True:
        _, frame = capture.read()
        if frame is not None:
            image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image)
            detector.detect_async(mp_image, int(time.time() * 1000))
except KeyboardInterrupt:
    capture.release()
    sys.exit(0)
```

### Other info / Complete Logs

```shell
I am using NVIDIA Jetson TX2. I am able to successfully compile and run mediapipe on a headless Ubuntu 18.04 server.
```

**Comment by YikeStone** [comment]
I know that there are so many issues already opened for this topic. I would like to mention that I have gone through almost all of them and tried various things, after trying all those things now I am able to atleast compile mediapipe for Jetson TX2 and run it in an headless environment without Xserver. Attaching mediapipe git diff:

[diff.txt](https://github.com/google/mediapipe/files/11274371/diff.txt)

**Comment by YikeStone** [comment]
So the issue was the python code I was using for testing. When I tested with solutions/hands_test.py, it worked with GPU.

**Comment by YikeStone** [comment]
I am getting 10fps and GPU usage spikes in between to 100% and then goes to 0%. I am getting 10fps even with model_complexity=0. How can I debug/profile the issue in pipeline?

Test code attached.

[hands_test.py.txt](https://github.com/google/mediapipe/files/11284338/hands_test.py.txt)

**Comment by kuaashish** [comment]
Hello @YikeStone,
Thanks for raising this issue. This is indeed an improvement we expect to be present in the MediaPipe solutions for Python. We shall take this feature request and prfioritize it internally to make it available by default/by using some config options.

In the meantime, please look at https://github.com/google/mediapipe/issues/1042#issuecomment-683506007 to enable GPU acceleration in Python. Since Python can understand Image Frame and there is a requirement of GPU Buffer for GPU processing, this change should help.
