### ISSUE TITLE
RuntimeError: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES2 request

### ISSUE THREAD

**Issue by Adithya-Krishnan** [google/mediapipe#4308]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-b115e2d5e421> in <module>
      6 
      7 # Initialize the hand detector
----> 8 ---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-b115e2d5e421> in <module>
      6 
      7 # Initialize the hand detector
----> 8 detector = HandDetector(maxHands=2, detectionCon=0.8)
      9 
     10 

~/.local/lib/python3.6/site-packages/cvzone/HandTrackingModule.py in __init__(self, mode, maxHands, detectionCon, minTrackCon)
     33         self.hands = self.mpHands.Hands(static_image_mode=self.mode, max_num_hands=self.maxHands,
     34                                         min_detection_confidence=self.detectionCon,
---> 35                                         min_tracking_confidence=self.minTrackCon)
     36         self.mpDraw = mp.solutions.drawing_utils
     37         self.tipIds = [4, 8, 12, 16, 20]

/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/hands.py in __init__(self, static_image_mode, max_num_hands, min_detection_confidence, min_tracking_confidence)
    143                 min_tracking_confidence,
    144         },
--> 145         outputs=['multi_hand_landmarks', 'multi_handedness'])
    146 
    147   def process(self, image: np.ndarray) -> NamedTuple:

/usr/local/lib/python3.6/dist-packages/mediapipe/python/solution_base.py in __init__(self, binary_graph_path, graph_config, calculator_params, side_inputs, outputs)
    252         for name, data in (side_inputs or {}).items()
    253     }
--> 254     self._graph.start_run(input_side_packets)
    255 
    256   # TODO: Use "inspect.Parameter" to fetch the input argument names and

RuntimeError: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES2 request. 
      9 
     10 

~/.local/lib/python3.6/site-packages/cvzone/HandTrackingModule.py in __init__(self, mode, maxHands, detectionCon, minTrackCon)
     33         self.hands = self.mpHands.Hands(static_image_mode=self.mode, max_num_hands=self.maxHands,
     34                                         min_detection_confidence=self.detectionCon,
---> 35                                         min_tracking_confidence=self.minTrackCon)
     36         self.mpDraw = mp.solutions.drawing_utils
     37         self.tipIds = [4, 8, 12, 16, 20]

/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/hands.py in __init__(self, static_image_mode, max_num_hands, min_detection_confidence, min_tracking_confidence)
    143                 min_tracking_confidence,
    144         },
--> 145         outputs=['multi_hand_landmarks', 'multi_handedness'])
    146 
    147   def process(self, image: np.ndarray) -> NamedTuple:

/usr/local/lib/python3.6/dist-packages/mediapipe/python/solution_base.py in __init__(self, binary_graph_path, graph_config, calculator_params, side_inputs, outputs)
    252         for name, data in (side_inputs or {}).items()
    253     }
--> 254     self._graph.start_run(input_side_packets)
    255 
    256   # TODO: Use "inspect.Parameter" to fetch the input argument names and

RuntimeError: ; eglChooseConfig() returned no matching EGL configuration for RGBA8888 D16 ES2 request. 

I'm trying tobuild a gesture detection model on my jetson nano with jetpackk version 4.5, python version 3.6 and pip version 21. But i am encountering the above issue while running ----> detector = HandDetector(maxHands=2, detectionCon=0.8). PLease provide a solution

**Comment by Sagar1711** [comment]
I have the same system, but for me this error only comes up when I run it using systemd service.
