### ISSUE TITLE
library not loaded error

### ISSUE THREAD

**Issue by ChuyiZhong** [google/mediapipe#431]
Hi all
I can build the project successfully such as hand-tracking or face detection, but each time I run the project, an error shows up:
dyld: Library not loaded: /usr/local/opt/ilmbase/lib/libImath-2_3.24.dylib
  Referenced from: /usr/local/opt/opencv@3/lib/libopencv_imgcodecs.3.4.dylib
  Reason: image not found
Abort trap: 6
Can anyone help?  All help are appreciated.

**Comment by mcclanahoochie** [comment]
seems like a dependency of opencv is missing, you can try installing it via
`brew install ilmbase openexr`
or reinstalling opencv
```
brew uninstall opencv@3
brew install -fs opencv@3
```

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
