### ISSUE TITLE
Tulsi for Bazel is no longer maintained and Crashes on start

### ISSUE THREAD

**Issue by SergioRUP** [google/mediapipe#4311]
### OS Platform and Distribution

MacOS 13.2.1

### Programming Language and version

Python 3.7.9

### Installed using virtualenv? pip? Conda?(if python)

pip

### XCode and Tulsi versions (if iOS)

Xcode 14.3 

### Android AAR (if android)

None

### Describe the problem

```shell
For IOS on a MacOS 13.2.1.
Followed the installation steps to the letter.
Tulsi crashes on start.
Can't create the Xcode project.

Tulsi for Bazel is no longer maintained.
How to use rules_xcodeproj instead?
```

### Complete Logs

```shell
After opening tulsi by double clicking on MediaPipe.tulsiproj. The compile button was disabled.
After this, tulsi doesn't even start anymore, crashes immediately.
```

**Comment by kuaashish** [comment]
Hello @SergioRUP,
Please modify the all files under ["buildTargets"](https://github.com/google/mediapipe/blob/master/mediapipe/MediaPipe.tulsiproj/Configs/MediaPipe.tulsigen#L25) of `MediaPipe.tulsigen` of folder [MediaPipe.tulsiproj ](https://github.com/google/mediapipe/tree/master/mediapipe/MediaPipe.tulsiproj)as below:

```
 "buildTargets" : [
    "@//mediapipe/examples/ios/facedetectioncpu:FaceDetectionCpuApp",
    "@//mediapipe/examples/ios/facedetectiongpu:FaceDetectionGpuApp",
    "@//mediapipe/examples/ios/faceeffect:FaceEffectApp",
    "@//mediapipe/examples/ios/facemeshgpu:FaceMeshGpuApp",
    "@//mediapipe/examples/ios/handdetectiongpu:HandDetectionGpuApp",
    "@//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp",
    "@//mediapipe/examples/ios/helloworld:HelloWorldApp",
    "@//mediapipe/examples/ios/holistictrackinggpu:HolisticTrackingGpuApp",
    "@//mediapipe/examples/ios/iristrackinggpu:IrisTrackingGpuApp",
    "@//mediapipe/examples/ios/objectdetectioncpu:ObjectDetectionCpuApp",
    "@//mediapipe/examples/ios/objectdetectiongpu:ObjectDetectionGpuApp",
    "@//mediapipe/examples/ios/objectdetectiontrackinggpu:ObjectDetectionTrackingGpuApp",
    "//mediapipe/examples/ios/posetrackinggpu:PoseTrackingGpuApp",
    "//mediapipe/examples/ios/selfiesegmentationgpu:SelfieSegmentationGpuApp",
    "//mediapipe/objc:mediapipe_framework_ios"
 ],
```
This can be issue with Bazel v6, Please let us know if this resolves the issue from your end.

**Comment by WZS666** [comment]
Hello @kuaashish ,
After i add the @ in buildTargets. But tulsi still crashes immediately.
Any other suggestions? Thank you.

My enviroment - 
Mac mini M1
MacOS 12.6.3
bazel v6.1.1
Xcode 13.4.1
python 3.7.16

**Comment by SergioRUP** [comment]
In my case Tulsi's crash was my fault.
In the "Configs" tab the "Generate" button was disabled, I then double clicked on the MediaPipe row and an Open File popup showed up.
Here is where i messed up, I didn't notice this popup was asking for the Bazel binary file, so I opened the MediaPipe.tulsiproj file instead.
After this Tulsi will always crash on launch.

If someone else also made the same mistake, here is how to fix it.
- Rename the file MediaPipe.tulsiproj to something else, so Tulsi can't find it.
- Run Tulsi, it won't crash anymore.
- Open the renamed MediaPipe.tulsiproj file and on the tab "Configs" double click "MediaPipe" again and this time make sure to open the Bazel binary.
  (for me it was here "/usr/local/Cellar/bazelisk/1.16.0/bin/bazel", but could also be at "/usr/local/Cellar/bazel/6.1.1/bin/bazel" depending on what was installed)
- After this, the Generate button will become enabled


Also, I had to add the "@" like @kuaashish recommended, or it doesn't work.


Still can not compile for IOS though, keep getting errors like "... is unavailable: introduced in iOS 12.0"
Tried several branches, all with similar errors but on different lines of code.

On the branch "Release" this is the error:
`
ERROR: /private/var/tmp/_bazel_sergio/e7e92dbfd0437d119ecd9c8f9cf7a748/external/org_tensorflow/tensorflow/lite/delegates/gpu/common/transformations/BUILD:185:11: Compiling tensorflow/lite/delegates/gpu/common/transformations/make_padding.cc failed: (Exit 1): wrapped_clang_pp failed: error executing command (from target @org_tensorflow//tensorflow/lite/delegates/gpu/common/transformations:make_padding) external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 37 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/org_tensorflow/tensorflow/lite/delegates/gpu/common/transformations/make_padding.cc:41:13: error: 'any_cast<const tflite::gpu::ConstTensorAttributesBase<tflite::gpu::DataType::FLOAT32> &>' is unavailable: introduced in iOS 12.0
      absl::any_cast<const ConstTensorAttributes&>(node.operation.attributes);
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/usr/include/c++/v1/any:607:12: note: 'any_cast<const tflite::gpu::ConstTensorAttributesBase<tflite::gpu::DataType::FLOAT32> &>' has been explicitly marked unavailable here
_ValueType any_cast(any const & __v)
           ^
external/org_tensorflow/tensorflow/lite/delegates/gpu/common/transformations/make_padding.cc:66:19: error: 'any_cast<const tflite::gpu::ConcatAttributes &>' is unavailable: introduced in iOS 12.0
            absl::any_cast<const ConcatAttributes&>(node->operation.attributes);
                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/usr/include/c++/v1/any:622:12: note: 'any_cast<const tflite::gpu::ConcatAttributes &>' has been explicitly marked unavailable here
_ValueType any_cast(any & __v)
           ^
2 errors generated.
Error in child process '/usr/bin/xcrun'. 1
Target //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.174s, Critical Path: 3.90s
INFO: 167 processes: 133 internal, 34 darwin-sandbox.
FAILED: Build did NOT complete successfully
`


But this is another issue.
I think this can be closed.

Thanks
