### ISSUE TITLE
win11 bazel build occured a bug for permission denied

### ISSUE THREAD

**Issue by YZCOrange** [google/mediapipe#4314]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Win11

### Programming Language and version

C++

### MediaPipe version

0.9.1

### Bazel version

5.3.2

### Solution

hello_world,pose_tracking and so on

### Describe the actual behavior

```shell
when I run 'bazel build', it occured an error for this:

ERROR: E:/yzc/project/mediapipe/WORKSPACE:482:14: fetching remote_platform_configure rule //external:local_execution_config_platform: java.io.IOException: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/local_execution_config_platform (Permission denied)
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/local_execution_config_platform (Permission denied)

My environments: win11 + vs2019 + python3.9 + tensorflow1.11.0.
when I was 'bazel build' in win10 by environments above, it can work successfully, but I recently reinstall the system from win10 to win11, then it failed.
```

### Describe the expected behaviour

```shell
I don't know how to solve this problem, please help me to solve it and I will greatly appreciate it!
```

### Standalone code/steps you may have used to try to get what you need

```shell
bazel build -c opt --local_cpu_resources=HOST_CPUS-2 --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D:\\Anaconda3\\envs\\bazel\\python.exe" mediapipe/examples/desktop/hello_world
```

**Comment by YZCOrange** [comment]
win11 powershell/cmd run as administrator it also occured this problem

**Comment by kuaashish** [comment]
Hello @YZCOrange,
From the description, we can see ` bazel version v5.3.2` being used which been recently updated to bazel `v6.1.1` as guided [here ](https://github.com/google/mediapipe/releases/tag/v0.9.3.0) with latest release `v0.9.3.0`. Please build using the latest version, Upgrade the bazel to recommended version and feel free to revert back if still an issue from your end. Thank you

**Comment by YZCOrange** [comment]
> Hello @YZCOrange, From the description, we can see ` bazel version v5.3.2` being used which been recently updated to bazel `v6.1.1` as guided [here ](https://github.com/google/mediapipe/releases/tag/v0.9.3.0) with latest release `v0.9.3.0`. Please build using the latest version, Upgrade the bazel to recommended version and feel free to revert back if still an issue from your end. Thank you!

Thanks a lot! but I have say sorry for this bug was reoccurred, I changed the mediapipe to 'v0.9.3.0' and bazel to 'v6.1.1', it still not work, desperately!

**Comment by YZCOrange** [comment]
> Hello @YZCOrange, From the description, we can see ` bazel version v5.3.2` being used which been recently updated to bazel `v6.1.1` as guided [here ](https://github.com/google/mediapipe/releases/tag/v0.9.3.0) with latest release `v0.9.3.0`. Please build using the latest version, Upgrade the bazel to recommended version and feel free to revert back if still an issue from your end. Thank you!

I don't know whether is related to these 'warnings and debugs' below, so I paste the complete whole process as follows:
`Starting local Bazel server and connecting to it...
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  E:/yzc/project/mediapipe/WORKSPACE:47:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/0aaa6e679847a4eeb407136e7b0bcef93ec652e6.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/898a9ca5e939acd06fd73217423a9276f762d098.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_protobuf' because it already exists.
DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
ERROR: E:/yzc/project/mediapipe/WORKSPACE:494:14: fetching remote_platform_configure rule //external:local_execution_config_platform: java.io.IOException: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/local_execution_config_platform (Permission denied)
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/local_execution_config_platform (Permission denied)`

**Comment by YZCOrange** [comment]
> > Hello @YZCOrange, From the description, we can see ` bazel version v5.3.2` being used which been recently updated to bazel `v6.1.1` as guided [here ](https://github.com/google/mediapipe/releases/tag/v0.9.3.0) with latest release `v0.9.3.0`. Please build using the latest version, Upgrade the bazel to recommended version and feel free to revert back if still an issue from your end. Thank you!
> 
> I don't know whether is related to these 'warnings and debugs' below, so I paste the complete whole process as follows: `Starting local Bazel server and connecting to it... DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e" DEBUG: Repository rules_foreign_cc instantiated at: E:/yzc/project/mediapipe/WORKSPACE:47:13: in <toplevel> Repository rule http_archive defined at: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel> WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/0aaa6e679847a4eeb407136e7b0bcef93ec652e6.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/898a9ca5e939acd06fd73217423a9276f762d098.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'com_google_absl' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'com_google_benchmark' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'flatbuffers' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'pybind11_bazel' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'com_google_protobuf' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'com_google_googletest' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'zlib' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'rules_python' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'build_bazel_apple_support' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'xctestrunner' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'pybind11' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'pybind11_protobuf' because it already exists. DEBUG: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/org_tensorflow/third_party/repo.bzl:132:14: Warning: skipping import of repository 'com_github_glog_glog' because it already exists. ERROR: E:/yzc/project/mediapipe/WORKSPACE:494:14: fetching remote_platform_configure rule //external:local_execution_config_platform: java.io.IOException: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/local_execution_config_platform (Permission denied) ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/local_execution_config_platform (Permission denied)`

**Comment by YZCOrange** [comment]
> Hello @YZCOrange, From the description, we can see ` bazel version v5.3.2` being used which been recently updated to bazel `v6.1.1` as guided [here ](https://github.com/google/mediapipe/releases/tag/v0.9.3.0) with latest release `v0.9.3.0`. Please build using the latest version, Upgrade the bazel to recommended version and feel free to revert back if still an issue from your end. Thank you!

@kuaashish

**Comment by kuaashish** [comment]
Hello @YZCOrange,
Could you please confirm that you are still looking for resolution on this issue or it has been resolved.

**Comment by YZCOrange** [comment]
> I can't solve it in win11, so I gave up and  solved it by reinstalling the win10

**Comment by YZCOrange** [comment]
> Hello @YZCOrange, Could you please confirm that you are still looking for resolution on this issue or it has been resolved.

@kuaashish I can't solve it in win11, so I gave up and solved it by reinstalling the win10

**Comment by YZCOrange** [comment]
> Hello @YZCOrange, Could you please confirm that you are still looking for resolution on this issue or it has been resolved.

   @kuaashish  hello，I’m sorry to bother you again. Recently, I want to build a mediapipe of x86 version, so I changed the dll and lib for x86 version in  'opencv_windows.BUILD' file. But when I run 'bazel build' , it reoccured the problem as follows.

`
ERROR: E:/yzc/project/mediapipe/WORKSPACE:482:14: fetching remote_platform_configure rule //external:local_execution_config_platform: java.io.IOException: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/local_execution_config_platform (Permission denied)
ERROR: Analysis of target '//mediapipe/examples/desktop/holistic_tracking_dll:MediapipeHolisticTracking_x86' failed; build aborted: C:/users/yuanzc/_bazel_yuanzc/ygilrmcs/external/local_execution_config_platform (Permission denied)
INFO: Elapsed time: 496.545s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 6 targets configured)
`
exactly the same!

**Comment by kuaashish** [comment]
@YZCOrange,

Sorry for the delayed response, x86-based PC are 32-bit version Operating System, And We do not support 32-bit Python, All of Python wheels are for 64-bit python. 

Please Build MediaPipe example in the Windows x64 and let us know if you encounter the similar error. Thank you

**Comment by YZCOrange** [comment]
> @YZCOrange,
> 
> Sorry for the delayed response, x86-based PC are 32-bit version Operating System, And We do not support 32-bit Python, All of Python wheels are for 64-bit python.
> 
> Please Build MediaPipe example in the Windows x64 and let us know if you encounter the similar error. Thank you

@kuaashish I konw, so I gave up to build mediapipe for x86 version, but I still encounter the similar error when building mediapipe for x64 version. so I guess that it's my fortune to build mediapipe successfully at the first time, I can't success later.
Anyway, thanks a lot for your reply, I will not use it recently.
Best wishes for you will develop it for a stable version in windows by the not complicated way!

**Comment by kuaashish** [comment]
@YZCOrange,


Thank you for your feedback, We are working towards publish the Pre-Complied binaries for easier build in the Windows, So that community can import easily. However, For now, We do not have any anytime timeline to be available. 

Additionally, Please let us know If this is no longer issue from your end, Can we move ahead and close the issue as resolved?
