### ISSUE TITLE
When new face, body and holistic solutions will be released?

### ISSUE THREAD

**Issue by joansc** [google/mediapipe#4316]
Are there any updates on when these new solutions will be released? Thanks!

**Comment by kuaashish** [comment]
Hello @joansc,
Thank you for your interest in MediaPipe Solutions. We are working towards to publish the solutions as soon as solutions will be ready from our end. As of now, we can not provide any timeline for this. However, Already known solutions will be publicly available once it will be ready here in [page](https://developers.google.com/mediapipe/solutions/examples).
