### ISSUE TITLE
memory increases until it crashes

### ISSUE THREAD

**Issue by rui1998** [google/mediapipe#4321]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

windows python3.6

### Programming Language and version

python

### MediaPipe version

0.8.6.2

### Solution

hands

### Describe the actual behavior

```shell
As I run the function over and over again, memory increases until it crashes，and i am sure i didnt reuse the object,and when i use hands.close(),it didnt worked, and memory still  increased
```

### Describe the expected behaviour

```shell
memory does not  increased
```

### Standalone code/steps you may have used to try to get what you need

```shell
#the following is my code:


class Video:
    def __init__(self):
        self.mp_hands = mp.solutions.hands.Hands(static_image_mode=False,
                max_num_hands=2, min_detection_confidence=0.6, min_tracking_confidence=0.6)
        # self.mp_hands.close()

    def detect_frame(self, frame):
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        results = self.mp_hands.process(frame)
        print(self.mp_hands._input_stream_type_info)

        frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
        results_list = []
        return results_list

    def destory(self):
        self.mp_hands.close()


def video_cap(i,v):


    cap = cv2.VideoCapture(0)
    count = 0
    while cap.isOpened():

        ret, frame = cap.read()
        if not ret or count >=12:
            break
        count += 1
        rst_list = v.detect_frame(frame)
        print(i, rst_list)
    v.destory()
    cap.release()
    cv2.destroyAllWindows()




if __name__ == '__main__':


    while 1:
        video = Video()
        video_cap(1, video)

```

**Comment by rui1998** [comment]
can someone help me      --.--

**Comment by rui1998** [comment]
@ayushgdev

**Comment by ayushgdev** [comment]
Hello @rui1998 Thanks for reporting this issue. Would you please try this code in latest version of MediaPipe v0.9.3.0? It could be the case that it has already been addressed since we are actively evolving this project. 
I have tried reproducing this issue in latest version and it is working perfectly fine for last 10 minutes.
<img width="887" alt="Screenshot 2023-04-21 at 3 26 22 PM" src="https://user-images.githubusercontent.com/118424249/233608294-446b47e7-2597-41a4-8923-56527333ed29.png">

**Comment by rui1998** [comment]
@ayushgdev
