### ISSUE TITLE
Failed to reload some Bazel targets. The loaded project may be incorrect. Debug info: Missing labels: ["//mediapipe/examples/edgeDetection:edgeDetection"]

### ISSUE THREAD

**Issue by mohit7979** [google/mediapipe#4322]
Running /usr/local/bin/bazel info '--override_repository=tulsi=/Users/mohitkumarmohit/Library/Application Support/Tulsi/0.20221005.88/Bazel'
 Running /usr/local/bin/bazel --max_idle_secs=60 query '--override_repository=tulsi=/Users/mohitkumarmohit/Library/Application Support/Tulsi/0.20221005.88/Bazel' --announce_rc --noimplicit_deps --order_output=no --noshow_loading_progress --noshow_progress 'kind(rule, mediapipe/examples/edgeDetection:all)' --output xml
 Build Events JSON file at "/var/folders/sk/mj41bfxx7l9crvqhgxwwxjqw0000gn/T/build_events_39464.json"
 Running /usr/local/bin/bazel build --announce_rc --show_result=0 --noshow_loading_progress --noshow_progress --symlink_prefix=/ --apple_platform_type=ios --cpu=ios_x86_64 --watchos_cpus=i386 --announce_rc '--override_repository=tulsi=/Users/mohitkumarmohit/Library/Application Support/Tulsi/0.20221005.88/Bazel' --compilation_mode=dbg --define=apple.add_debugger_entitlement=1 --define=apple.propagate_embedded_extra_outputs=1 --define=apple.experimental.tree_artifact_outputs=1 --features=debug_prefix_map_pwd_is_dot --tool_tag=tulsi:generator --build_event_json_file=/var/folders/sk/mj41bfxx7l9crvqhgxwwxjqw0000gn/T/build_events_39464.json --noexperimental_build_event_json_file_path_conversion --noexpand_test_suites --features=-parse_headers --noexperimental_run_validations --aspects @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect --output_groups=tulsi_info,-dsyms //mediapipe/examples/edgeDetection:edgeDetection

**Comment by kuaashish** [comment]
Hello @mohit7979,
Could you please elaborate your query with complete details, such as exact steps you have followed, Xcode version to reproduce the issue from our end? We encourage you to fill the [template](https://github.com/google/mediapipe/issues/new/choose) to get more details to reproduce the issue and share the possible solution on the query raised. Thank you
