### ISSUE TITLE
Hand Detection GPU - proto files missing (using Android Studio)

### ISSUE THREAD

**Issue by SamuelJakes** [google/mediapipe#433]
I'm trying to build the Hand Detection GPU app using Android Studio, but these 2 lines are giving me an error:

import com.google.mediapipe.proto.CalculatorProto.CalculatorGraphConfig;
import com.google.mediapipe.proto.GraphTemplateProto.CalculatorGraphTemplate;

The issue seems to be that the "proto" file doesn't exist, and I can't find it anywhere in the github repo. Where do I locate these files? Have I missed something extremely obvious here?

Cheers.

**Comment by rahulsuxsena1** [comment]
Hi @SamuelJakes , can you please help me know how you resolved this issue?
Thanks
