### ISSUE TITLE
New Pose Detection Model

### ISSUE THREAD

**Issue by aris-konstantinidis** [google/mediapipe#4331]
On the [mediapipe website](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker) you mention a new pose detection model coming out soon. Could you give us a rough estimate for the release date? 

Thank you very much for you work :)

**Comment by ayushgdev** [comment]
@aris-konstantinidis Although we cannot commit any date, but you should expect it rolled out in two weeks.

**Comment by aris-konstantinidis** [comment]
Thank you very much! Looking forward to it :)
