### ISSUE TITLE
Media Pipe Hands NPM use error

### ISSUE THREAD

**Issue by JaiGarg314** [google/mediapipe#4333]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Mac 13.2.1 (22D68)

### Browser and version if the issue happens on browser

Version 112.0.5615.49 (Official Build) (arm64)

### Programming Language and version

react.js

### MediaPipe version

0.4.1675469240

### Solution

Hands

### Describe the actual behavior

```shell
I am just trying to integrate media pipe hands onto a React webpage. When trying to import mediapipe and initialize a Hands object using the NPM i get multiple errors. 

caught SyntaxError: Unexpected token '<'

nds.js:57 Uncaught (in promise) TypeError: m is not a function
    at pa.h (hands.js:57:1)
    at G (hands.js:14:1)
    at sa.next (hands.js:15:1)
    at hands.js:15:1
    at new Promise (<anonymous>)
    at ta (hands.js:15:1)
    at H (hands.js:16:1)
    at hands.js:57:1
    at async Promise.all (:3000/index 0)
(
nds.js:57 Uncaught (in promise) TypeError: m is not a function
    at pa.h (hands.js:57:1)
    at G (hands.js:14:1)
    at sa.next (hands.js:15:1)
    at hands.js:15:1
    at new Promise (<anonymous>)
    at ta (hands.js:15:1)
    at H (hands.js:16:1)
    at hands.js:57:1
    at async Promise.all (:3000/index 0)
(


Here is my code:

import React, { useEffect, useRef, useState } from 'react';
import * as Hands from "@mediapipe/hands";

import {
  drawConnectors,
  drawLandmarks,
  Data,
  lerp,
} from '@mediapipe/drawing_utils';
import './handsdetection.css';
import useAuth from '../hooks/useAuth';
import Button from 'react-bootstrap/Button';

export const HandsDetection = () => {
 
  const { auth, setlastWindow, lastWindow } = useAuth();

  const [reloadKey, setReloadKey] = useState(0);

  const [inputVideoReady, setInputVideoReady] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const [handEstimationEnabled, setHandEstimationEnabled] = useState(true);

  const inputVideoRef = useRef(null);
  const canvasRef = useRef(null);
  const contextRef = useRef(null);

  const handEstimationEnabledRef = useRef(handEstimationEnabled);
  
  function reloadComponent() {
    setReloadKey((prevKey) => prevKey + 1);
  }
  
  useEffect(() => {
    handEstimationEnabledRef.current = handEstimationEnabled;
  }, [handEstimationEnabled]);
  
  useEffect(() => {
    try {
      if (!inputVideoReady) {
        return;
      }
      let hands = new Hands.Hands();
      hands.setOptions({
        maxNumHands: 2,
        modelComplexity: 1,
        minDetectionConfidence: 0.75,
        minTrackingConfidence: 0.75,
      });
      
      if (inputVideoRef.current && canvasRef.current) {
        contextRef.current = canvasRef.current.getContext("2d");
        const constraints = {
          video: { width: { min: 1280 }, height: { min: 720 } },
        };
        navigator.mediaDevices.getUserMedia(constraints).then((stream) => {
          if (inputVideoRef.current) {
            inputVideoRef.current.srcObject = stream;
          }
        });
        const onResults = (results) => {
          if (canvasRef.current && contextRef.current) {
            setLoaded(true);
    
            contextRef.current.save();
            contextRef.current.clearRect(
              0,
              0,
              canvasRef.current.width,
              canvasRef.current.height
            );
            contextRef.current.drawImage(
              results.image,
              0,
              0,
              canvasRef.current.width,
              canvasRef.current.height
            );
            if (handEstimationEnabledRef.current) {
              if (results.multiHandLandmarks && results.multiHandedness) {
                for (
                  let index = 0;
                  index < results.multiHandLandmarks.length;
                  index++
                ) {
                  const classification = results.multiHandedness[index];
                  const isRightHand = classification.label === "Right";
                  const landmarks = results.multiHandLandmarks[index];
                  drawConnectors(contextRef.current, landmarks, Hands.HAND_CONNECTIONS, {
                    color: isRightHand ? "#FFFFFF" : "#FFFFFF",
                  });
                  drawLandmarks(contextRef.current, landmarks, {
                    color: isRightHand ? "#FFFFFF" : "#FFFFFF",
                    fillColor: isRightHand ? "#131d36" : "#131d36",
                    radius: (data) => {
                      return lerp(data.from.z, -0.15, 0.1, 10, 0.5);
                    },
                  });
                }
              }
            }
            contextRef.current.restore();
          }
        };
    
        hands.onResults(onResults);
    
        const sendToMediaPipe = async () => {
            if (inputVideoRef.current && inputVideoRef.current.videoWidth) {
              await hands.send({ image: inputVideoRef.current });
            }
          };
      
          const updateVideo = () => {
            sendToMediaPipe();
            requestAnimationFrame(updateVideo);
          };
      
          updateVideo();
    }
    }catch(err){
      reloadComponent()
    }
  }, [inputVideoReady]);

  function toggleHandEstimation() {
    setHandEstimationEnabled(!handEstimationEnabled);
    handEstimationEnabledRef.current = !handEstimationEnabled;
  }

  
  
    if(auth?._id != undefined){
    return (
      <React.Fragment key={reloadKey}> 
      <div className="hands-container">
        {/* Add the button to toggle hand estimation */}
        <Button onClick={toggleHandEstimation} className = "switch">
          {handEstimationEnabled ? 'Disable' : 'Enable'} Hand Estimation
        </Button>
        <video
          autoPlay
          ref={(el) => {
            inputVideoRef.current = el;
            setInputVideoReady(!!el);
          }}
        />
        <canvas ref={canvasRef} width={1280} height={720} />
        {!loaded && (
          <div className="loading">
            <div className="spinner"></div>
            <div className="message">Loading</div>
          </div>
        )}
      </div>
      </React.Fragment>
    );
  }
  else{
    if(lastWindow === "/dashboard"){
        return (
            window.location.href = '/dashboard'
        );
    }
    else{
        setlastWindow("dashboard")
        return (
            window.location.href = '/login'
        );
    }
}

};
Thank you for your support and time
```

### Describe the expected behaviour

```shell
It should just initialize the hand's object and track a user's hands. There is also a button that allows a user to turn on and off the tracking.
```

### Standalone code/steps you may have used to try to get what you need

```shell
I have tried switching to using CDN links, but then I get a buffer error. I have also tried many different combinations of the current code including importing all of Hands or only some. I have also tried reordering code. I have even see that people in the past have had similar issue with the same error but they have not found solutions/ their solutions do not work for me. I have also tried changing to different media pipe versions.
```

**Comment by ayushgdev** [comment]
Hello @JaiGarg314 
Would you please check [this](https://github.com/ayushgdev/MediaPipeCodeSamples/tree/main/React) sample hands solution project in react ? This should help you fix common issues like building with webpack or usage of `useEffect()`.

**Comment by JaiGarg314** [comment]
Hello, thank you for your help. I looked at that code, and I converted it into javascript, but my is still failing actually to draw the landmarks. It is detecting landmarks and possibly draws them but does not update the video. Could you please help me fix this small error? I am so sorry for my confusion, but I have tried to find a solution online, and I could not. Thank you for your help!
Here is my code. 

import React, { useEffect, useRef, useState } from 'react';

import { Camera } from "@mediapipe/camera_utils";
import { Hands, HAND_CONNECTIONS } from "@mediapipe/hands";
import { drawConnectors, drawLandmarks,data,lerp,} from "@mediapipe/drawing_utils";

export const HandsDetection = () => {
  useEffect(() => {
        const videoElement = document.getElementsByClassName("input_video")[0];
        const canvasElement = document.getElementsByClassName("output_canvas")[0];
        const canvasCtx = canvasElement.getContext("2d");

        function onResults(results) {
            if (!canvasCtx) {
                return;
            }
            canvasCtx.save();
            canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
            canvasCtx.drawImage(results.image, 0, 0, canvasElement.width, canvasElement.height);
            if (results.multiHandLandmarks) {
                for (const landmarks of results.multiHandLandmarks) {
                    drawConnectors(canvasCtx, landmarks, HAND_CONNECTIONS, {color: "#FFFFFF"});
                    drawLandmarks(canvasCtx, landmarks, {color: "#FFFFFF",fillColor: "#131d36",radius: (data) => {return lerp(data.from.z, -0.15, 0.1, 10, 0.5);},});
                }
            }
            canvasCtx.restore();
        }

        const hands = new Hands({
            locateFile: (file) => {
                return `https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`;
            },
        });
        hands.setOptions({
            maxNumHands: 2,
            modelComplexity: 1,
            minDetectionConfidence: 0.5,
            minTrackingConfidence: 0.5,
        });
        hands.onResults(onResults);

        const camera = new Camera(videoElement, {
            onFrame: async () => {
                await hands.send({ image: videoElement });
            },
            width: 1280,
            height: 720,
        });
        camera.start();
    }, []);

    return(
        <div class="container">
            <video class="input_video"></video>
            <canvas class="output_canvas" width="1280px" height="720px"></canvas>
        </div>
    );
};

**Comment by JaiGarg314** [comment]
Sorry I did not mean to close this ticket.

**Comment by ayushgdev** [comment]
This is running fine when I convert to tsx. One possible reason for landmark issue could be because of the `lerp()`. Try using a static value first for radius. If it succeeds, try modifying the drawLandmarks function as below
```
drawLandmarks(canvasCtx, landmarks, { color: "#FFFFFF", fillColor: "#131d36", radius: (data) => { return lerp(data.from?.z, -0.15, 0.1, 10, 0.5); }, });
```
Usage of `?` operator in `data.from?.z` ensures there is no error if the data.from is null, since it can be null.

**Comment by JaiGarg314** [comment]
I am now very confused. I tried using a constant for radius, which did not work, and then I even tried directly implementing the ts file from the example you provided, and it is still not drawing the points or connections. Do you have an recommendations on what the issue could be? Thank you so much for your help.

**Comment by ayushgdev** [comment]
@JaiGarg314 Can you please share the project on GitHub(if not confidential) so that we can run it at our end and provide resolution?

**Comment by JaiGarg314** [comment]
Thank you so much. [This](https://github.com/JaiGarg314/temphand) is the git repository (it has a useless handsDection.js file outside of the src, which contains my old attempts at getting the hand tracking to work). When running the server, you may have to create an account, but you do not have to use any real information or emails. Thank you so much for your help.

**Comment by ayushgdev** [comment]
Hello @JaiGarg314 The canvas is not visible actually. What you are seeing is the video element which does not render the landmarks. Canvas does so. 
And canvas element is hidden because of code in dashboard.css 
```
canvas {
    display: none
}
```
Simply removing this resolved the issue

**Comment by JaiGarg314** [comment]
I am so dumb. Thank you so much for your help and patience. Yoy have resolved my issue. I really appreciate your help and time. Have a good day!
