### ISSUE TITLE
Slow video saving time with Mediapipe in Python

### ISSUE THREAD

**Issue by PaStMir** [google/mediapipe#4337]
I am currently working on a project where I am using Mediapipe's facemesh to process a video in Python. However, I am facing an issue where the time taken to save the processed video is longer than the time it takes to process and calculate the facemesh on the video. The saving time takes as long as the video runs.
Has anyone faced a similar issue while using Mediapipe? And if so, how did you resolve it? I would appreciate any insights or suggestions on how to optimize the saving process and reduce the time taken to save the video. Thank you in advance!

        import cv2
        import mediapipe as mp
        mp_drawing = mp.solutions.drawing_utils
        mp_drawing_styles = mp.solutions.drawing_styles
        mp_face_mesh = mp.solutions.face_mesh
        
        # For video input:
        drawing_spec = mp_drawing.DrawingSpec(thickness=1, circle_radius=1)
        cap = cv2.VideoCapture("Video")
        fps = int(cap.get(cv2.CAP_PROP_FPS))
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        out = cv2.VideoWriter("output.mp4", fourcc, fps, (int(cap.get(3)), int(cap.get(4))))
        
        with mp_face_mesh.FaceMesh(
            max_num_faces=1,
            refine_landmarks=True,
            min_detection_confidence=0.5,
            min_tracking_confidence=0.5) as face_mesh:
        
            while cap.isOpened():
                success, image = cap.read()
                if not success:
                    print("End of video.")
                    break
        
                # To improve performance, optionally mark the image as not writeable to
                # pass by reference.
                image.flags.writeable = False
                image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                results = face_mesh.process(image)
        
                # Draw the face mesh annotations on the image.
                image.flags.writeable = True
                image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
                if results.multi_face_landmarks:
                    for face_landmarks in results.multi_face_landmarks:
                        mp_drawing.draw_landmarks(
                            image=image,
                            landmark_list=face_landmarks,
                            connections=mp_face_mesh.FACEMESH_TESSELATION,
                            landmark_drawing_spec=None,
                            connection_drawing_spec=mp_drawing_styles.get_default_face_mesh_tesselation_style())
                        mp_drawing.draw_landmarks(
                            image=image,
                            landmark_list=face_landmarks,
                            connections=mp_face_mesh.FACEMESH_CONTOURS,
                            landmark_drawing_spec=None,
                            connection_drawing_spec=mp_drawing_styles.get_default_face_mesh_contours_style())
                        mp_drawing.draw_landmarks(
                            image=image,
                            landmark_list=face_landmarks,
                            connections=mp_face_mesh.FACEMESH_IRISES,
                            landmark_drawing_spec=None,
                            connection_drawing_spec=mp_drawing_styles.get_default_face_mesh_iris_connections_style())
        
                # Save the annotated frame to video file
                out.write(image)
        
            cap.release()
            out.release()
            cv2.destroyAllWindows()

**Comment by ayushgdev** [comment]
Hello @PaStMir 
We processed a video and got the same results. The video properties are:
Frame size  (1280.0, 720.0)
Video FPS:  29.97002997002997
Video Frame count: 3920.0

The `face_mesh.process()` took 0.03 seconds on an average (attached image below). 0.03 for  3920 frames brings the total time to 132 seconds which was same as video time. The frame processing is taking a very reasonable time, but the number of frames in the video increases the total video processing time. So if it were a 60fps video, this processing will take longer. Hence, it would be better to attribute the video saving time to the number of frames rather than the length of video.

![Figure_1](https://user-images.githubusercontent.com/118424249/234176988-4d3224b8-29b2-4e93-9d88-4dcaa44ab865.png)
