### ISSUE TITLE
How can I overlay bitmap/image on landmarks? I want to overlap png on iris using facelandmarks.

### ISSUE THREAD

**Issue by prakashsrv** [google/mediapipe#4338]
This template is for miscellaneous issues not covered by the other issue categories

For questions on how to work with MediaPipe, or support for problems that are not verified bugs in MediaPipe, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/mediapipe) and [Slack](https://mediapipe.page.link/joinslack) communities.

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/google/mediapipe/security).

**Comment by kuaashish** [comment]
Hello @prakashsrv,
Could you please elaborate your query with complete details, exact possible solutions you are looking for from us. 
Thank you

**Comment by prakashsrv** [comment]
I am looking to create a color lens try-on application using the MediaPipe FaceMesh module. My goal is to overlay a PNG image, containing different color lenses, on the iris of the user's eyes, as detected by the FaceMesh module. This will allow users to virtually "try on" different color lenses and see how they look on their eyes in real-time.

**Comment by kuaashish** [comment]
Hello @prakashsrv,

Sorry for the delayed response, Could you please confirm that you are still looking for the resolution on this or the issue has been resolved from your end?  Thank you!
