### ISSUE TITLE
Hand Detection GPU, Android - Detection keypoints

### ISSUE THREAD

**Issue by haruotsa** [google/mediapipe#434]
I am trying to access the detection keypoints from the hand detection example on Android ("handdetectiongpu").
Are there calculator(s)  to extract the keypoints from a detection stream and convert them to landmarks, which could be then accessed similar to the "multihandtrackinggpu" example?

**Comment by bhack** [comment]
The same could be useful for face landmarks i.e. https://github.com/Star-Clouds/CenterFace

**Comment by haruotsa** [comment]
A somewhat hacky way to accomplish the above is to create custom .proto for the detection and convert it into .java with the accompanied protocol buffer tool. While this works, I still would prefer a cleaner solution e.g. with calculators.

**Comment by eknight7** [comment]
Hi @haruotsa, please see https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu. This example extracts landmarks from a cropped area of the input image. The cropping is done based on the output of the palm detection model.

More details for hand tracking are here: https://ai.googleblog.com/2019/08/on-device-real-time-hand-tracking-with.html

Hand Landmark extraction code: https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L111-L133

**Comment by eknight7** [comment]
Also, please note there is a calculator to convert Landmarks --> Detection here: https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/landmarks_to_detection_calculator.cc, and not vice-versa.

**Comment by bhack** [comment]
@eknight7 What about single stage e2e bbox+landmarks like centerface, object as points and others?

**Comment by haruotsa** [comment]
@bhack Double that. Since streaming of various audio/video trough ML models leads to many kinds of detections, it would be nice to have a more general/flexible way to extract those. @eknight7 Any comments on how this might be taken care of in the future mediapipe releases? (I guess, it makes sense to continue this discussion in another issue)
