### ISSUE TITLE
Why did I use yolov8 to detect the figure, then crop the figure picture, and use mediapipe pose to estimate the figure pose effect is poor? How should I use mediapipe pose to solve the problem of multi-person pose estimation?

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#4340]
Why did I use yolov8 to detect the figure, then crop the figure picture, and use mediapipe pose to estimate the figure pose effect is poor? How should I use mediapipe pose to solve the problem of multi-person pose estimation?

**Comment by kuaashish** [comment]
Hello @LMR2018,
Could you please elaborate your query with complete details, If possible please fill out the issue [template](https://github.com/google/mediapipe/issues/new/choose) to understand the issue better from our end. Thank you!

**Comment by LMR2018** [comment]
boxes = yolov8_boxes(image)

for box in boxes:
    bbox_top_left_x = int(box[0])
    bbox_top_left_y = int(box[1])
    bbox_bottom_right_x = int(box[2])
    bbox_bottom_right_y = int(box[3])

    mediapipe_pose_results = pose.process(image_crop)

    # transposing results to be drawn on the original image
    if mediapipe_pose_results.pose_landmarks != None:
        for landmark in mediapipe_pose_results.pose_landmarks.landmark:
            landmark.x = ((abs(bbox_bottom_right_x - bbox_top_left_x) / width) * landmark.x) + (
                    bbox_top_left_x / width)
            landmark.y = ((abs(bbox_bottom_right_y - bbox_top_left_y) / height) * landmark.y) + (
                    bbox_top_left_y / height)

        # draw the pose annotations on the image
        # set image as writeable
        image.flags.writeable = True
        mp_drawing.draw_landmarks(
            image,
            mediapipe_pose_results.pose_landmarks,
            mp_pose.POSE_CONNECTIONS,
            landmark_drawing_spec=mp_drawing_styles.get_default_pose_landmarks_style())

yolov8 detects people, and then cuts out the original figure to figure pictures. mediapipe pose estimates that the pose effect of people is very poor. Why is this? How should I use mediapipe pose to solve the problem of multi-person pose estimation?
