### ISSUE TITLE
How to install poseTrackingCPU on Android

### ISSUE THREAD

**Issue by fchen09** [google/mediapipe#4341]
### OS Platform and Distribution

Android 12

### Compiler version

bazel 5.2

### Programming Language and version

Java

### MediaPipe version

0.9.1

### Bazel version

5.2

### Android AAR (if android)

None

### Describe the problem

```shell
Hi, I am trying to install PoseTrackingCpu on Samsung Note 10+, but unfortunately, I've never succeeded. I followed https://github.com/google/mediapipe/pull/1773/commits/605afe392c20096f01d311282493798b76da516e
, but it is unsuccessful. Since I am running the apk built by Bazel, I am not sure how to get the LogCat. Could you provide a detailed tutorial about how to run poseTrackingCpu on Android? I appreciate your help!
```

### Complete Logs

```shell
N/A
```

**Comment by ayushgdev** [comment]
Hello @fchen09 The easiest way to install pose solution would be to use the [build_android_examples](https://github.com/google/mediapipe/blob/master/build_android_examples.sh).sh file. Though it will install other apps as well, but may be you can tweak the script and add an `if` condition for installing only pose tracking target.
