### ISSUE TITLE
pose_landmark_heavy.tflite HTTP Error 404: Not Found, and the model is not available online to be downloaded manually

### ISSUE THREAD

**Issue by bhomaidan1990** [google/mediapipe#4343]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Ubuntu 18.04 ARM64 Jetson Nano

### Programming Language and version

Python

### MediaPipe version

0.8.9.1

### Solution

Pose

### Describe the actual behavior

```shell
Downloading model to /home/marvin/.local/lib/python3.8/site-packages/mediapipe/modules/pose_landmark/pose_landmark_heavy.tflite
HTTP Error 404: Not Found
```
```


### Describe the expected behaviour

```shell
I expect the model to be downloaded and ready to work!
```

### Standalone code/steps you may have used to try to get what you need

```shell
#!/usr/bin/env python3.8

import mediapipe as mp

class HumanPoseDetection3D:
    def __init__(self) -> None:
        # Initializing mediapipe pose class.
        self.mp_pose = mp.solutions.pose
        # Setting up the Pose function.
        self.pose = self.mp_pose.Pose(static_image_mode=True, min_detection_confidence=0.3, model_complexity=2)
        # Initializing mediapipe drawing class, useful for annotation.
        self.mp_drawing = mp.solutions.drawing_utils 
        self.mp_drawing_styles = mp.solutions.drawing_styles

if __name__ == "__main__":
    HPD_ = HumanPoseDetection3D()
```

**Comment by ayushgdev** [comment]
Hello @bhomaidan1990 
MediaPipe has shifted to use GCS for storage of models from 0.8.10 version. Hence, this issue. We would suggest you to upgrade MediaPipe to latest version. It would resolve the issue. 
Further, the model can be downloaded manually from [this section](https://github.com/google/mediapipe/blob/0fc6118680a5ae1d7a424a9912b41993e684b0ae/docs/solutions/models.md#pose) of model cards.

**Comment by bhomaidan1990** [comment]
@ayushgdev thanks.
