### ISSUE TITLE
Where is mediapipe's pose key smoothing code? I want to know the implementation principle and code of this pose key point

### ISSUE THREAD

**Issue by LMR2018** [google/mediapipe#4344]
Where is mediapipe's pose key smoothing code? I want to know the implementation principle and code of this pose key point

**Comment by kuaashish** [comment]
Hello @LMR2018,
Could you please point us to the above with any links which you are referring to and also elaborate with complete details. Thank you!

**Comment by LMR2018** [comment]
with mp_pose.Pose(
        static_image_mode=False,
        model_complexity=1,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5) as pose:
      while cap.isOpened():
        success, image = cap.read()
        if not success:
          print("Ignoring empty camera frame.")
          # If loading a video, use 'break' instead of 'continue'.
          # continue
          break

        image = cv2.flip(image, 1)

        start_time = time.time()

        # To improve performance, optionally mark the image as not writeable to
        # pass by reference.
        image.flags.writeable = False
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        results = pose.process(image)

        # Draw the pose annotation on the image.
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        mp_drawing.draw_landmarks(
            image,
            results.pose_landmarks,
            mp_pose.POSE_CONNECTIONS,
            landmark_drawing_spec=mp_drawing_styles.get_default_pose_landmarks_style())

得到的results.pose_landmarks 是怎样进行smooth_landmarks的？可以告诉我smooth具体处理代码是怎样的吗？
