### ISSUE TITLE
Hand landmarks detection with gloves

### ISSUE THREAD

**Issue by GuillemSebastianFletes** [google/mediapipe#4345]
I am trying to use the  Hand Landmarker model to detect hands that are wearing gloves (the gloves color may variate) and the algorith is not capable to properly detect the hands.

**Comment by kuaashish** [comment]
Hello @GuillemSebastianFletes,
The hand tracking model has been trained specifically with exposed hands, In this case the model will not be able to predict the hands with gloves. If you would like to detect with gloves we believe other conditions will require training a similar machine learning model.

**Comment by monxarat** [comment]
Has anyone resolved this task?
