### ISSUE TITLE
Hand Landmarker with projected images

### ISSUE THREAD

**Issue by GuillemSebastianFletes** [google/mediapipe#4346]
I am trying to use the  Hand Landmarker model to detect hands that have to be under a projection and it is not capable to detect the hand when is under projected images.

**Comment by kuaashish** [comment]
Hello @GuillemSebastianFletes,
Could you please elaborate your query with complete details, meant by the under-projected image to understand the issue better from our end. Thank you

**Comment by GuillemSebastianFletes** [comment]
Here ypu have an example of what I mean

![left_not_detected](https://user-images.githubusercontent.com/6809848/234843533-a1484d40-4602-4aa6-ac29-803793bb88d9.png)

**Comment by AdoHaha** [comment]
I don't think you can work with such low-quality photos. The hand is very poorly visible here.

**Comment by kuaashish** [comment]
@GuillemSebastianFletes,

MediaPipe models are trained to work well under "normal conditions" of good lighting and good camera quality. In case of projected images model will not work as excepted. We recommend you to use the better images to feed into the model. If you still see the similar behaviour we will be further look into the issue deeper.  Thank you
