### ISSUE TITLE
Not able to compile Object Detection with Tracking

### ISSUE THREAD

**Issue by loginabhay1** [google/mediapipe#435]
Please help getting this error while building the Object Detection with Tracking.
I am building on desktop the command i am using is `bazel build -c opt mediapipe/examples/desktop/object_tracking:object_tracking_cpu`

```
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/home/ubuntu/.cache/bazel/_bazel_root/d1ffae7cad39d64e0dbd835d781da331/command.profile.gz'
INFO: Analyzed target //mediapipe/examples/desktop/object_tracking:object_tracking_cpu (99 packages loaded, 4242 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/ubuntu/.cache/bazel/_bazel_root/d1ffae7cad39d64e0dbd835d781da331/sandbox
ERROR: /home/ubuntu/.cache/bazel/_bazel_root/d1ffae7cad39d64e0dbd835d781da331/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/BUILD:361:1: C++ compilation of rule '@org_tensorflow//tensorflow/lite/delegates/gpu/gl:request_gpu_info' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 33 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/request_gpu_info.cc: In function 'int tflite::gpu::gl::RequestGpuInfo(tflite::gpu::GpuInfo*)':
external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/request_gpu_info.cc:31:8: error: ambiguating new declaration of 'int tflite::gpu::gl::RequestGpuInfo(tflite::gpu::GpuInfo*)'
 Status RequestGpuInfo(GpuInfo* gpu_info) {
        ^~~~~~~~~~~~~~
In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/request_gpu_info.cc:16:0:
external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/request_gpu_info.h:31:8: note: old declaration 'tflite::gpu::Status tflite::gpu::gl::RequestGpuInfo(tflite::gpu::GpuInfo*)'
 Status RequestGpuInfo(GpuInfo* gpu_info);
        ^~~~~~~~~~~~~~
In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/request_gpu_info.h:23:0,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/request_gpu_info.cc:16:
external/org_tensorflow/tensorflow/lite/delegates/gpu/common/status.h:68:31: error: cannot convert 'const tflite::gpu::Status' to 'int' in return
     if (!status2.ok()) return status2; \
                               ^
external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/request_gpu_info.cc:74:3: note: in expansion of macro 'RETURN_IF_ERROR'
   RETURN_IF_ERROR(GetOpenGlErrors());
   ^~~~~~~~~~~~~~~
external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/request_gpu_info.cc:76:19: error: cannot convert 'tflite::gpu::Status' to 'int' in return
   return OkStatus();
                   ^
Target //mediapipe/examples/desktop/object_tracking:object_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11.865s, Critical Path: 1.09s
INFO: 1 process: 1 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by mcclanahoochie** [comment]
which platform is this?
can you try adding the flag
_--define MEDIAPIPE_DISABLE_GPU=1_
```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/object_tracking:object_tracking_cpu
```

**Comment by loginabhay1** [comment]
Hi thanks for the reply sorry for not being specific i am using ubuntu 18.04, bazel version 1.0.0, opencv 4 lts and have already tried the above command but it also gives the error.
`
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/object_tracking:object_tracking_cpu
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/home/ubuntu/.cache/bazel/_bazel_ubuntu/d1ffae7cad39d64e0dbd835d781da331/command.profile.gz'
INFO: Analyzed target //mediapipe/examples/desktop/object_tracking:object_tracking_cpu (89 packages loaded, 3779 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/ubuntu/.cache/bazel/_bazel_ubuntu/d1ffae7cad39d64e0dbd835d781da331/sandbox
INFO: From ProtoCompile mediapipe/calculators/video/flow_packager_calculator.pb.h:
bazel-out/k8-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/video/box_tracker_calculator.pb.h:
bazel-out/k8-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/core/packet_resampler_calculator.pb.h:
bazel-out/k8-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/video/motion_analysis_calculator.pb.h:
bazel-out/k8-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/video/motion_analysis_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/video/flow_packager_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/video/box_tracker_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
ERROR: /home/ubuntu/Abhay/mediapipe/mediapipe/util/tracking/BUILD:443:1: C++ compilation of rule '//mediapipe/util/tracking:tone_estimation' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 81 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/util/tracking/tone_estimation.cc: In member function 'void mediapipe::ToneEstimation::IntensityPercentiles(const cv::Mat&, const cv::Mat&, bool, mediapipe::ToneChange*) const':
mediapipe/util/tracking/tone_estimation.cc:152:34: error: 'CV_RGB2GRAY' was not declared in this scope
   cv::cvtColor(frame, intensity, CV_RGB2GRAY);
                                  ^~~~~~~~~~~
mediapipe/util/tracking/tone_estimation.cc:152:34: note: suggested alternative: 'CV_RGB'
   cv::cvtColor(frame, intensity, CV_RGB2GRAY);
                                  ^~~~~~~~~~~
                                  CV_RGB
Target //mediapipe/examples/desktop/object_tracking:object_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 27.463s, Critical Path: 17.67s
INFO: 69 processes: 69 linux-sandbox.
FAILED: Build did NOT complete successfully
`

**Comment by mcclanahoochie** [comment]
seems like an [opencv](https://github.com/opencv/opencv/wiki/Opencv4) issue 
please use  cv::COLOR_RGB2GRAY instead of CV_RGB2GRAY

we will note this^ and fix in our next release

for the original error (GPU), please check if your system supports running mediapipe on [gpu desktop](https://mediapipe.readthedocs.io/en/latest/gpu.html#desktop-gpu-linux)

**Comment by ElectricSquirrel** [comment]
bazel-out/k8-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.

Will this affect the operation?
