### ISSUE TITLE
Python GPU/CUDA build guide for mediapipe >v0.9

### ISSUE THREAD

**Issue by JayParikh20** [google/mediapipe#4353]
### OS Platform and Distribution

Ubuntu 20.04 (Jetpack 5.1) 

### Programming Language and version

Python 3.8

### MediaPipe version

>v0.9

### Bazel version

6.1.2

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.7.0

### Describe the problem

There are lots of old solutions for building GPU version for python (#1651, #1042) but all point to an older version v0.8.3.1. I was hoping to get the clear set of instructions for building it for the newer versions. I'm planning it to build on Nvidia Orin 32gb which has aarch64 using this guide, https://github.com/jiuqiant/mediapipe_python_aarch64.

### Complete Logs

```shell
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

**Comment by kuaashish** [comment]
Hello @JayParikh20,
Thanks for raising this issue. This is indeed an improvement we expect to be present in the MediaPipe solutions for Python. We shall take this feature request and prfioritize it internally to make it available by default/by using some config options.

**Comment by JayParikh20** [comment]
Hello @kuaashish, thanks for prioritizing this feature!

**Comment by TigerHix** [comment]
+1, providing GPU delegate for Python would be tremendously helpful.

**Comment by riverzhou** [comment]
Mediapipe v0.10.0 GPU Version with CUDA @ Ubuntu 22.04 (22.04c):

https://github.com/riverzhou/mediapipe.git

**Comment by kuaashish** [comment]
@JayParikh20,

We have rolled out the newer version 0.10.1 with Python GPU support as noted in [release page](https://github.com/google/mediapipe/releases/tag/v0.10.1). Please build python in GPU and let us know if encounter any error.

**Comment by alexioana** [comment]
> Please build python in GPU and let us know if encounter any error.

How? Using [this ](https://developers.google.com/mediapipe/framework/getting_started/gpu_support#tensorflow_cuda_support_and_setup_on_linux_desktop)guide?

**Comment by kuaashish** [comment]
It is still under development, We will let you know once it becomes available from our end.
However, We are moving the status of issue to resolve And closing it as Python GPU support has been added. Thank you!

**Comment by TigerHix** [comment]
> It is still under development, We will let you know once it becomes available from our end.
> However, We are moving the status of issue to resolve And closing it as Python GPU support has been added. Thank you!

Hi, the title of this issue is “Python GPU build guide”, so I think it’s different from “Python GPU support”. Furthermore, could you clarify on “Python GPU support”? Does it require users to build a GPU version of MediaPipe themselves, or there is a config option to switch between CPU/GPU delegates like the web version? There is no mentioning of it in the release notes you provided. It would be great to have a clear documentation on enabling GPU support in Python.
