### ISSUE TITLE
A black screen randomly occurs for Android APP

### ISSUE THREAD

**Issue by fchen09** [google/mediapipe#4358]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Android 9

### Mobile device if the issue happens on mobile device

Samsung Galaxy Note8

### Programming Language and version

Java

### MediaPipe version

0.8.9

### Bazel version

5.2

### Solution

Pose

### Describe the actual behavior

```shell
My app integrated Mediapipe and CameraX. It works well on Samsung Galaxy Note10+. However, when running on Note 8, a black screen randomly occurs when the camera is called. If I recall the camera or put the app in the background and bring it back to the foreground, the captured image is back.
```

### Describe the expected behaviour

```shell
The black screen should not occur; however, it occurs randomly on Note 8
```

### Standalone code/steps you may have used to try to get what you need

```shell
I call the widest FOV camera with:
CameraSelector cameraSelector = new CameraSelector.Builder().addCameraFilter(new MyCameraFilter(cameraID)).build();
```

**Comment by fchen09** [comment]
https://user-images.githubusercontent.com/84703080/235333746-a9374f25-9710-4430-b64b-6d995ba84285.mp4

**Comment by ayushgdev** [comment]
Hello @fchen09 
Could you please check if [this discussion](https://groups.google.com/a/android.com/g/camerax-developers/c/SM6TaG2JXdo) helps debugging your issue? Since this is not a code related issue, it cannot be concretely said what can be the core issue.
