### ISSUE TITLE
MediaPipe Workspace Uses a Legacy Release of Rules Foreign CC

### ISSUE THREAD

**Issue by alexbeattie42** [google/mediapipe#4365]
### MediaPipe Solution (you are using)

n/a

### Programming language

Bazel

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

The current version of RulesForeignCC in the WORKSPACE file is from March 2, 2021:
```shell
http_archive(
   name = "rules_foreign_cc",
   strip_prefix = "rules_foreign_cc-0.1.0",
   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.1.0.zip",
)
```
The latest version contains many useful updates for invoking cmake in bazel.

### Will this change the current API? How?

no

### Who will benefit with this feature?

People building OpenCV and other libraries from source with bazel

### Please specify the use cases for this feature

Improve ability to build foreign libraries with bazel

**Comment by kuaashish** [comment]
@alexbeattie42,
Thank you for raising this request. We are sharing request internally and based on discussion team will prioritise this feature. However, For now, We can not provide any timeline for this.

**Comment by lu-wang-g** [comment]
@schmidt-sebastian may you please take a look at this issue? Thanks!

**Comment by kuaashish** [comment]
@alexbeattie42,

This proposal has been merged in the commit https://github.com/google/mediapipe/commit/4a123445c4d2ca90f0cb3720e6b39dc6179f14a9. Thank you!
