### ISSUE TITLE
About the mediapipeGraph  with a raw packet

### ISSUE THREAD

**Issue by BTLDXX-x** [google/mediapipe#4375]
I use the graph of facemesh at ios platform. Does the function followed only get packet when it detects the faces? Will the function not be called if no face is detected?

```
/// Provides the delegate with a raw packet.
@optional
- (void)mediapipeGraph:(MPPGraph *)graph
       didOutputPacket:(const mediapipe::Packet &)packet
            fromStream:(const std::string &)streamName;
```

**Comment by BTLDXX-x** [comment]
How can I know if it detects no face? 
thanks for your help!

**Comment by BTLDXX-x** [comment]
i do this:

```
if (packet.IsEmpty()) {
        NSLog(@"packet is empty");
      return;
    }
```

but it doesn't print 'packet is empty'. when calls the function, the packet will not be empty?

**Comment by ayushgdev** [comment]
Hello @BTLDXX-x 
You would need to set the observe_timestamp_bounds variable to true. By default it is false so the packet is not returned empty. The variable is in the function argument [ObserveOutputStream()](https://github.com/google/mediapipe/blob/master/mediapipe/framework/calculator_graph.cc#L453)

**Comment by BTLDXX-x** [comment]
@ayushgdev thanks for your reply!

**Comment by ayushgdev** [comment]
@BTLDXX-x Can we close this issue?
