### ISSUE TITLE
How can I use Region Tracking in Android?

### ISSUE THREAD

**Issue by Zuile** [google/mediapipe#4376]
I am trying to use Instant Motion Tracking on Android, but I want to receive camera data by myself and then invoke region tracking to obtain anchor data, similar to FaceMesh. java.

**Comment by kuaashish** [comment]
Hello @Zuile,

We have ended support for the Instant Motion Tracking and upgrading to [these legacy solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) or Already have been upgraded. However, the libraries, documentation, and source code for all the MediaPipe Legacy Solutions or the support we have ended will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Thank you!
