### ISSUE TITLE
Hair segmentation problem with  cv2.bitwise_and 

### ISSUE THREAD

**Issue by mariomosko** [google/mediapipe#4378]
I  am using this hair segmentation model https://storage.googleapis.com/mediapipe-assets/hair_segmentation.tflite in python and  i am having an issue with the function cv2.bitwise_and between the segmentation mask and the original image .

My code is as below :
# Libraries and initializations
import numpy as np
import mediapipe as mp
import cv2
from mediapipe.python._framework_bindings import image
from mediapipe.python._framework_bindings import image_frame
from mediapipe.tasks.python import vision
from mediapipe import tasks
from mediapipe.python._framework_bindings import image as image_module
_Image = image_module.Image
from mediapipe.python._framework_bindings import image_frame
_ImageFormat = image_frame.ImageFormat

BG_COLOR = (192, 192, 192) # gray
MASK_COLOR = (255, 255, 255) # white

OutputType = vision.ImageSegmenterOptions.OutputType
Activation = vision.ImageSegmenterOptions.Activation
VisionRunningMode = vision.RunningMode
BaseOptions =tasks.BaseOptions

IMAGE_FILENAMES = ['13147680-fd2e-4d67-b29a-89b9a6752703.jpeg']

in_file = open("hair.tflite", "rb")
data = in_file.read()

# Create the options that will be used for ImageSegmenter
base_options = BaseOptions(model_asset_buffer=data)
options = vision.ImageSegmenterOptions(base_options=base_options,running_mode=VisionRunningMode.IMAGE,
                                              output_type=OutputType.CATEGORY_MASK)

# Create the image segmenter
with vision.ImageSegmenter.create_from_options(options) as segmenter:

  # Loop through demo image(s)
  for image_file_name in IMAGE_FILENAMES:

    # Create the MediaPipe image file that will be segmented
   # read image using OpenCV
     rgb_image = cv2.imread("person.jpeg")
     rgba_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2RGBA)
# set alpha channel to empty.
     rgba_image[:,:,3] = 0
# create MP Image object from numpy array
    image = _Image(image_format=_ImageFormat.SRGBA, data=rgba_image)

    # Retrieve the masks for the segmented image
    category_masks = segmenter.segment(image)
    # print(category_masks)

    # Generate solid color images for showing the output segmentation mask.
    image_data = image.numpy_view()
    fg_image = np.tile(np.array([MASK_COLOR], dtype=np.uint8), reps=(image_data.shape[0], image_data.shape[1], 1))
    bg_image = np.tile(np.array([BG_COLOR], dtype=np.uint8), reps=(image_data.shape[0], image_data.shape[1], 1))

    for name in category_masks:
      condition = np.stack((name.numpy_view(),) * 3, axis=-1) > 0.2
      output_image = np.where(condition, fg_image, bg_image)

      print(f'Segmentation mask of {name}:')
      resize_and_show(output_image)
       masked_img = cv2.bitwise_and(rgb_img,rgb_img , mask=output_image)

the error that i get :
![Screenshot 2023-05-05 154104](https://user-images.githubusercontent.com/91782518/236474130-40b60b5b-5d56-4611-ae62-9c161f1ab924.jpg)

even though as you can see the shapes are the same and data types are the same.

i am posting it here because if i use another hair segmentation model(not the mediapipe one)  i do not have the problem with cv2.bitwise_and builtin method.

Thank you in advanc

**Comment by ayushgdev** [comment]
Hello @mariomosko 
This problem is because of the mask argument. The [`cv2.bitwise_and`](https://docs.opencv.org/3.4/d0/d86/tutorial_py_image_arithmetics.html) function takes the mask argument as a single channel image, and the `output_image` variable contains an image of size (width, height, 3). 
The issue can be resolved by providing a binary mask with single channel. In the code provided, this mask is available in `name` variable within the `for` loop.
```python
      masked_img = cv2.bitwise_and(rgb_image, rgb_image , mask=name.numpy_view()) 
```
