### ISSUE TITLE
I cant install mediapipe

### ISSUE THREAD

**Issue by Davidd-u** [google/mediapipe#4381]
### OS Platform and Distribution

windows 10

### Programming Language and version

Python 3.11.3

### Installed using virtualenv? pip? Conda?(if python)

pip 23.1.2

### MediaPipe version

0.9.3.0

### Bazel version

Not installed

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.7.0

### Describe the problem

```shell
C:\Users\USUARIO\Downloads>pip install mediapipe
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

### Complete Logs

```shell
When i try to install mediapipe on windows 10, this gives me an error, specifically after using the 

'pip install mediapipe' 

command, the error is this: 

'ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none )
ERROR: No matching distribution found for mediapipe',

when trying to install other pip packages this error doesn't happen, only when I try to install mediapipe
```

**Comment by kuaashish** [comment]
Hello @Davidd-u,
We see that you are using Python 3.11.3, Which is not supported by MediaPipe. We only support Python >=3.8 and <=3.10. Python 3.11 is only supported on MacOS and Linux. Please upgrade to the supported Python version.
