### ISSUE TITLE
Is there any possible to compute real world eye distance using iris depth and face landmark

### ISSUE THREAD

**Issue by dandingol03** [google/mediapipe#4385]
### Task name (e.g. Image classification, Gesture recognition etc.)

iris detection and face virtual trying-on

### Programming Language and version (e.g. C++, Python, Java)

c++

### Describe the actual behavior

```shell
Hi, I use mediapipe to implement virtual try-on glass. Mediapipe is fast and accurate enough, but i found that virtual glass size changed from different personal eye distance. I use the transform mat to fit the virtual glass to the approritate position in metric space, but the transform mat affected by the eye landmark.
```

### Describe the expected behaviour

```shell
I want the try-on glass keeps relative unchange from different personal eye distance. I think maybe i can get the real eye distance from iris model and adjust the glass size using personal eye distance. By the way, the eye distance means the distance between left eye and right eye.
```

### Standalone code/steps you may have used to try to get what you need

```shell
1.get the actual iris depth from iris detect, focal length from camera and the distance between two eyes which projected in pixels. Compute the actual size of eye distance by pinhole imaging
2.get transform mat from face detection, move the virtual glass to the approriate position, and scaled its x,y size by using personal the actual distance of  eye distance.
```

**Comment by ayushgdev** [comment]
Hello @dandingol03 
Please take a look at [`iris_depth_cpu.pbtxt`](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/iris_tracking/iris_depth_cpu.pbtxt#L143). This graph uses "IrisAndDepthRendererCpu" which outputs "LEFT_IRIS_DEPTH_MM" and "RIGHT_IRIS_DEPTH_MM". 
These are real world distance from camera which are accurate with 10% error rate on average. Check the depth from iris section [here](https://github.com/google/mediapipe/blob/master/docs/solutions/iris.md#depth-from-iris)

**Comment by dandingol03** [comment]
> Hello @dandingol03 Please take a look at [`iris_depth_cpu.pbtxt`](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/iris_tracking/iris_depth_cpu.pbtxt#L143). This graph uses "IrisAndDepthRendererCpu" which outputs "LEFT_IRIS_DEPTH_MM" and "RIGHT_IRIS_DEPTH_MM". These are real world distance from camera which are accurate with 10% error rate on average. Check the depth from iris section [here](https://github.com/google/mediapipe/blob/master/docs/solutions/iris.md#depth-from-iris)

Yes, i know the iris depth solution can calculate the real-world distance from camera. I want to compute thre real-world eye distance by using the distance between camera and human face. Is it possible?

**Comment by ayushgdev** [comment]
So you want to calculate distance between the two eyes in the face detected by MediaPipe?

**Comment by dandingol03** [comment]
> So you want to calculate distance between the two eyes in the face detected by MediaPipe?

Yes, the real-world distance between two eyes.

**Comment by ayushgdev** [comment]
@dandingol03 Unfortunately this is not possible since there is no scaling between the pixel distance and the actual metric distance.

**Comment by balavenkataraman123** [comment]
This might be a little bit late, but for an augmented reality project, I built a system to determine the real world distance from the face to the camera using the MediaPipe face landmarks, which could provide the distance to within an inch even when standing 5 feet away from my laptop webcam (1280x720).

https://github.com/balavenkataraman123/Holosense_library

To try it out, run the file in the tests directory after changing the parameters to your parameters.

**Comment by balavenkataraman123** [comment]
![image](https://github.com/google-ai-edge/mediapipe/assets/38150148/89a00c45-830a-473e-8b3f-235161418036)

**Comment by balavenkataraman123** [comment]
That library was written in python but I'm working on a C++ version too

**Comment by balavenkataraman123** [comment]
This might be late but If the depth of the eye is known then you can find their positions in real world coordinates. From that, you can calculate the Euclidean distance.
