### ISSUE TITLE
CodePen Pose detection demo broken with latest release

### ISSUE THREAD

**Issue by peterwake** [google/mediapipe#4388]
### Description of issue (what needs changing)

The latest release has broken the CodePen

### Clear description

Changing the references in the javascript from tasks-vision@latest to tasks-vision@0.1.0-alpha-13 fixes the issue.

### Usage example

https://codepen.io/mediapipe-preview/pen/abRLMxN

**Comment by Neilblaze** [comment]
@peterwake I think it's been fixed now (or at least seems fixed on my end) :)

**Comment by ayushgdev** [comment]
@peterwake We have fixed the issue with the release of Pose Task APIs. Would you please confirm it is working at your end as well?
