### ISSUE TITLE
Tensorflow model directly in android without tflite conversion

### ISSUE THREAD

**Issue by PrinceP** [google/mediapipe#439]
While running the TensorFlow model to android, I am receiving the following error. Is it possible to run PB files directly in android?

`
ERROR: /home/prince/work/mediapipe/mediapipe/calculators/tensorflow/BUILD:461:1: no such target '@org_tensorflow//tensorflow/core:android_tensorflow_lib_lite_nortti_lite_protos': target 'android_tensorflow_lib_lite_nortti_lite_protos' not declared in package 'tensorflow/core' defined by /home/prince/.cache/bazel/_bazel_prince/2c0029220fda8bf56e7d1a5c76230504/external/org_tensorflow/tensorflow/core/BUILD and referenced by '//mediapipe/calculators/tensorflow:tensorflow_session'
`

**Comment by mcclanahoochie** [comment]
our examples all use tflite (tensorflow lite) models and framework on android, not tensorflow directly; and we do not plan to support that use case right now.

you would need to modify the BUILD rules for each tensorflow calculator to add support for tensorflow for your android target; one reference could be [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/BUILD)
