### ISSUE TITLE
limit GPU memory usage

### ISSUE THREAD

**Issue by energygreek** [google/mediapipe#4394]
### MediaPipe Solution (you are using)

selfie_segmentation_gpu

### Programming language

c++

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

```shell
I use ImageFrameToGpuBufferCalculator and GpuBufferToImageFrameCalculator at the head and tail of graph, the problem is the GPU memory usage starts from 10MiB, increases along with execution util 2.5GiB, i'm wandering if there's a limit on GPU memory usage?
```

### Please specify the use cases for this feature

```shell
we run mediapipe on headless server, so there may be multiple instances, 2.5GiB  per process is too high.
```

**Comment by energygreek** [comment]
thank you ! @ayushgdev  but i don't find a c++ solution of `Image Segmentation`,  so must i use python?  BTW, is this `old mediapipe` deprecated?

**Comment by energygreek** [comment]
i want mediapipe to run on GPU mode,  so how to get a GPU version of mediapipe python package?

**Comment by ayushgdev** [comment]
@energygreek 
Yes, we are ending support for [these MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy), and upgrading the others. However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). 

GPU version of MediaPipe Python package does not exist yet. We have already added it to our roadmap, but we don't have any timeline for it yet. Though you can check out [this comment](https://github.com/google/mediapipe/issues/1042#issuecomment-683506007) which provides a hint to create personal GPU version of MP in Python if you are okay building your own solution. Guide on how to build MediaPipe locally is available [here](https://github.com/google/mediapipe/blob/master/docs/getting_started/python.md#building-mediapipe-python-package).
