### ISSUE TITLE
Cannot install mediapipe 0.9.2.0 and 0.9.3.0

### ISSUE THREAD

**Issue by aperez-hub** [google/mediapipe#4396]
### OS Platform and Distribution

Mac OS Version11.4(BigSur) Intel

### Programming Language and version

Python 3.10.11

### Installed using virtualenv? pip? Conda?(if python)

pip (Pycharm)

### MediaPipe version

0.9.2.0,0.9.30

### Android AAR (if android)

None

### Describe the problem

```shell
When installing mediapipe, it only installs 0.9.1.0.
```

### Complete Logs

```shell
ERROR: Could not find a version that satisfies the requirement mediapipe==0.9.3.0 (from versions: 0.8.9.1, 0.8.10, 0.8.10.1, 0.8.11, 0.9.0, 0.9.0.1, 0.9.1.0)
ERROR: No matching distribution found for mediapipe==0.9.3.0
```

**Comment by kuaashish** [comment]
@aperez-hub,

Thanks for bringing this up to our notice. I could able to build mediapipe 0.9.3.1 in macOS Ventura 13.3.1(a) Intel with Python version 3.9.6. Please upgrade to Python version 3.10 or Downgrade to version 3.9.6 and let us know if still an issue from your end. Attaching the relevant screenshot of installation below:

<img width="808" alt="Screenshot 2023-05-12 at 5 04 33 PM" src="https://github.com/google/mediapipe/assets/98159216/f48f68e1-8605-4d2b-983c-632f7d631d6d">

Thank you!

**Comment by aperez-hub** [comment]
Still cannot install with Python 3.9.6, BigSur (11.4).
I just upgraded to macOS Ventura and i am already able to install mediapipe 0.10.0 with Python 3.11. Thank you!

**Comment by kuaashish** [comment]
@aperez-hub,
Thank you for the confirmation, Closing this as issue has been resolved.
