### ISSUE TITLE
Can't install mediapipe (with pip)

### ISSUE THREAD

**Issue by G3raldnx** [google/mediapipe#4399]
### OS Platform and Distribution

windows 11 (amd64)

### Programming Language and version

python 3.7 + 3.10.11 + 3.9.13 + 3.10.5 + 3.9.5 + 3.8.0 + 3.7.0 i have tried all the above

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

0.10.0

### Bazel version

pip version 22.2.2

### Android AAR (if android)

None

### Describe the problem

```shell
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
when i use pip install mediapipe i get the message above
```

### Complete Logs

```shell
?
```

**Comment by kuaashish** [comment]
@G3raldnx,

Thanks for raising this issue, I could now able to build mediapipe 0.10.0 in Windows 11 with Python Version 3.10.7, Pip Version 22.2.2 as screenshot attached here. Please build using the mentioned configuration and let us know if still an issue from your end.

<img width="1475" alt="Screenshot 2023-05-12 at 5 51 50 PM" src="https://github.com/google/mediapipe/assets/98159216/d7bc0f80-b056-42fe-95e2-8b557b3ce9cd">

Thank you!!

**Comment by etosolo322** [comment]
❤️
