### ISSUE TITLE
How to use mediepipe hand tracking in multi thread(CPU or GPU)?

### ISSUE THREAD

**Issue by LiuYi-Up** [google/mediapipe#4402]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Linux Ubuntu 18.04

### Task name (e.g. Image classification, Gesture recognition etc.)

Hand tracking

### Programming Language and version (e.g. C++, Python, Java)

C++

### Describe the actual behavior

```shell
Thanks for the great work.

I follow this repo (https://github.com/HW140701/GoogleMediapipePackageDll/tree/main) to make mediapipe hand tracking as a .so lib, and I run it in 2 threads.In the 1st thread the graph init success, but in the 2nd thread it failed.

I'd greatly appreciate it if anyone could help me!
```

### Describe the expected behaviour

```shell
I want to use the .so in multi threads so I can run in multi camera.
```

### Standalone code/steps you may have used to try to get what you need

```shell
// when I make .so lib I use the follow code to init graph

/**********************************************************************************/
absl::Status GoogleMediapipeHandTrackingDetect::HandTrackingDetect::Mediapipe_InitGraph(const char* model_path)
{
	std::string calculator_graph_config_contents;

	MP_RETURN_IF_ERROR(mediapipe::file::GetContents(model_path, &calculator_graph_config_contents));

	mediapipe::CalculatorGraphConfig config =
		mediapipe::ParseTextProtoOrDie<mediapipe::CalculatorGraphConfig>(
			calculator_graph_config_contents);

	MP_RETURN_IF_ERROR(m_Graph.Initialize(config));

	// 添加landmarks输出流
	mediapipe::StatusOrPoller sop_landmark = m_Graph.AddOutputStreamPoller(m_kOutputLandmarks);
	assert(sop_landmark.ok());
	m_pPoller_landmarks = std::make_unique<mediapipe::OutputStreamPoller>(std::move(sop_landmark.value()));

	MP_RETURN_IF_ERROR(m_Graph.StartRun({}));

	return absl::OkStatus();
}
/**********************************************************************************/
```

### Other info / Complete Logs

```shell
when I 1st init the graph it successful, but in the 2nd thread it init failed and "init internal". Is there anything special to set when I want to run in multi threads?

I'd greatly appreciate it if anyone could help me!
```

**Comment by ayushgdev** [comment]
Hello @LiuYi-Up

We are building a set of new, improved [MediaPipe Solutions](https://developers.google.com/mediapipe/solutions) to help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Would you please check out the new APIs of Hand Tracking and Gesture recognition? If they do not serve your use case, we would request you to elaborate your use case in your application which is not being covered by MediaPipe tasks. We shall try to extend the APIs with the required feature set.

**Comment by LiuYi-Up** [comment]
> Hello @LiuYi-Up
> 
> We are building a set of new, improved [MediaPipe Solutions](https://developers.google.com/mediapipe/solutions) to help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Would you please check out the new APIs of Hand Tracking and Gesture recognition? If they do not serve your use case, we would request you to elaborate your use case in your application which is not being covered by MediaPipe tasks. We shall try to extend the APIs with the required feature set.

- Thanks for your reply! I am making a c++ project which wanna use the handtrcking by mediapipe.The project is used to detect hand landmark separately from multi cameras, it seems like the [#3034](https://github.com/google/mediapipe/issues/3034). So it is hard to me to fix it.What can I try?

- Another problem I meet is that I just use one thread to detect, first I input one camera, it runs quickly(like 2ms/per image) and result is correct. But when I input 2 cameras' frame one by one, it become slower and slower(like 20-30 ms / per image) and the result is wrong(it seems like the current results correspond to many previous images ). I don't know what may occur the problem.

Looking forward your reply~
Best wishes~

**Comment by kuaashish** [comment]
Hello @yichunk,

Could you please confirm that [above implementation](https://github.com/google/mediapipe/issues/4402#issuecomment-1547986515) is possible in the hands tracking solution? Thank you

**Comment by kuaashish** [comment]
@LiuYi-Up,

Hand tracking in MediaPipe graph is a stateful operation, Because it use the hands box from previous frame to locate the hands in current frame. Only one input video stream can be used on the same graph.

If you mix two video streams the tracking will be failed. Thank you!

**Comment by LiuYi-Up** [comment]
> 
Thank you very much for your reply！I solve this problem by creating multi threads and creating multi detectors separately. So I detect two cameras separately.
