### ISSUE TITLE
[JavaScript] `LIVE_STREAM` running mode does not exist

### ISSUE THREAD

**Issue by TigerHix** [google/mediapipe#4405]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 11

### Programming Language and version

JavaScript

### MediaPipe version

0.10.0

### Solution

Hands, Face Landmarks

### Describe the actual behavior

```shell
LIVE_STREAM is not a valid `runningMode` value for `VisionTaskOptions`.
```

### Describe the expected behaviour

```shell
Per documentation, LIVE_STREAM should be a valid `runningMode` value for `VisionTaskOptions`. See https://developers.google.com/mediapipe/solutions/vision/hand_landmarker and https://developers.google.com/mediapipe/solutions/vision/face_landmarker.
```

### Standalone code/steps you may have used to try to get what you need

```shell
const handLandmarker = await HandLandmarker.createFromOptions(
    vision,
    {
      baseOptions: {
        modelAssetPath: "./models/hand_landmarker.task",
        delegate: "GPU"
      },
      numHands: 2,
      runningMode: 'LIVE_STREAM' // <---
    });
handLandmarker.detect(inputImage);
```

This will throw an exception:

```
Error: Task is not initialized with image mode. 'runningMode' must be set to 'IMAGE'.
```
```


### Other info / Complete Logs

_No response_

**Comment by ayushgdev** [comment]
Hello @TigerHix 
We are able to replicate this behaviour. However, LIVE_STREAM mode is not available for JS platform. This is because the VIDEO mode is able to achieve the same result with `navigator.mediaDevices.getUserMedia()`.
However, we do realise the documentation is unclear about this exception for JS and we shall fix it soon. Will update here once the documentation is updated.

**Comment by tlebon** [comment]
docs are still not updated...

**Comment by christo** [comment]
Docs still not updated:
 https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker#configurations_options
