### ISSUE TITLE
The installation is not successful, always fails

### ISSUE THREAD

**Issue by longxingzhu** [google/mediapipe#4406]
### OS Platform and Distribution

windous10

### Compiler version

None

### Programming Language and version

Python3.9.13

### Installed using virtualenv? pip? Conda?(if python)

python

### MediaPipe version

None

### Bazel version

None

### XCode and Tulsi versions (if iOS)

None

### Android SDK and NDK versions (if android)

None

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

opencv-python-3.4.18.65

### Describe the problem

```shell
C:\Users\longx>pip install mediapipe
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: C:\Users\longx\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip
```

### Complete Logs

```shell
C:\Users\longx>pip install mediapipe
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: C:\Users\longx\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip
```

**Comment by zhangpengk** [comment]
@longxingzhu  May be you could try to go to the pypi Official website： https://pypi.org/project/mediapipe/，download  *.whl to local , and using : pip install *.whl to install the mediapipe package

**Comment by kuaashish** [comment]
Hello @longxingzhu,
From the log you have shared here, 
 `To update, run: C:\Users\longx\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip`

We can see that Python 11 is being used to build the MediaPipe, Which is not supported in Windows yet. We only support Python >=3.8 and <=3.10. Python 3.11 is only supported on MacOS and Linux. Please upgrade to the supported Python version.
