### ISSUE TITLE
document supported compiler versions

### ISSUE THREAD

**Issue by clogwog** [google/mediapipe#4408]
On linux when trying to run a few of the c++ examples i noticed that it wouldn't work with my default g++ compiler (version 7.5.0).
hello_world works, but for example face_mesh doesn't

only once i installed g++ 8.0 and specified 

`CC=gcc-8 CXX=g++-8 bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/face_mesh:face_mesh_cpu 
`

maybe  https://developers.google.com/mediapipe/framework/getting_started/install
can be updated to document the supported compiler versions.

**Comment by kuaashish** [comment]
@clogwog,
Thank you for bringing out to our notice, We will bring up this issue internally and will let you know once any specific update on this issue.

**Comment by schmidt-sebastian** [comment]
@kuaashish Can you update the getting started instructions to include that we require gcc 8.x as outlined here: https://github.com/google/mediapipe/blob/master/Dockerfile#L26 ?

**Comment by ayushgdev** [comment]
Documentation has been updated with recommended version of gcc/g++. Closing the issue now.
