### ISSUE TITLE
New Pose Detection Model

### ISSUE THREAD

**Issue by MaryamBoneh** [google/mediapipe#4412]
I want use the new model for the code in this page => https://github.com/google/mediapipe/blob/master/docs/solutions/pose.md
and use this CDN => https://cdn.jsdelivr.net/npm/@mediapipe/pose/ 
But the new version model is not yet on this CDN.
When will you put the model of new version of pose detection on DCN for download?

**Comment by jays0606** [comment]
Check out the npm @mediapipe/vision-tasks.
You can check the demo here. 
https://mediapipe-studio.webapps.google.com/demo/pose_landmarker

**Comment by kuaashish** [comment]
Hello @schmidt-sebastian,
Could you please look into this issue. Thank you

**Comment by schmidt-sebastian** [comment]
We are not publishing models on NPM, and as such they won't be available via JSDeliver. You can use the model from the link here: https://developers.google.com/mediapipe/solutions/vision/pose_landmarker
I would recommend hosting the model on your own so you can update it as needed.
