### ISSUE TITLE
Landmarks' list for "Face landmark detection"

### ISSUE THREAD

**Issue by andergalvan** [google/mediapipe#4413]
Hi, I'm a little bit new with MediaPipe, but I would like to know where I can find the documentation that describes each landmark detected with which point in the face is related. I mean, for example, landmark number 100 is related to iris.

I have been looking in this [link](https://developers.google.com/mediapipe/solutions/vision/face_landmarker/python), but I haven't found any documentation about that.

Thanks in advanced,
Ander

**Comment by andergalvan** [comment]
Thanks for your answer! @ayushgdev

**Comment by ayushgdev** [comment]
Can we consider this issue resolved @andergalvan ?
