### ISSUE TITLE
RefineLandmarksFromHeatmapCalculator possible bug

### ISSUE THREAD

**Issue by evulse** [google/mediapipe#4414]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

All

### Programming Language and version

C++

### Solution

Pose

### Describe the actual behavior

https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/refine_landmarks_from_heatmap_calculator.cc#L127

```cpp
    int center_col = out_lms.landmark(lm_index).x() * hm_width;
    int center_row = out_lms.landmark(lm_index).y() * hm_height;
    // Point is outside of the image let's keep it intact.
    if (center_col < 0 || center_col >= hm_width || center_row < 0 ||
        center_col >= hm_height) {
      continue;
    }
```

### Describe the expected behaviour

I think this code is supposed to be the following, this likely hasn't caused issues as all the models I've looked at use the same dimensions for width and height, however if they are unequal I think this would produce a bug.

I believe this code should be `center_row >= hm_height` instead of  `center_col >= hm_height` as below

```cpp
if (center_col < 0 || center_col >= hm_width || center_row < 0 ||
        center_row >= hm_height)
```

### Standalone code/steps you may have used to try to get what you need

This issue was discovered by just looking at the source code.

**Comment by kuaashish** [comment]
@evulse,
Could you please elaborate your query with more details? that will be more helpful for us to understand the issue and fix the bug as soon as possible from our end. Thank you!

**Comment by evulse** [comment]
Im not sure there is more I can add. 

https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/refine_landmarks_from_heatmap_calculator.cc#L127

The original comment above the code explains what it is supposed to do, but centre_row isn't being checked if it is greater than the hm_height, instead centre_col is being checked against hm_height even though it's an X coordinate which I believe only needs to be checked against hm_width

**Comment by kuaashish** [comment]
@evulse,
Thanks for the your detailed explanation. Please allow us sometime, We will discuss this matter internally and based on the discussion we will let you know update on this issue.

**Comment by schmidt-sebastian** [comment]
Thank you. Fix pending review.
