### ISSUE TITLE
General face-template available

### ISSUE THREAD

**Issue by ChristianNSchmitz** [google/mediapipe#4417]
### MediaPipe Solution (you are using)

v0.10.0

### Programming language

Python

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

```shell
Dear community,
we are currently working with a research application of Face Landmarks in Mediapipe and would like to make a between-subject comparison. For this reason, we would like to generate a general template of the dataset and I would like to ask you whether you have a solution for that?
Thank you very much!
Best,
Christian
```

### Who will benefit with this feature?

Generalizability of the program

### Please specify the use cases for this feature

```shell
Research and comparability of face landmarks
```

**Comment by ayushgdev** [comment]
Hello @ChristianNSchmitz 
The dataset used for training of Face Mesh and face detection solution is not made available for public usage. However, you can refer to the general aspects of the dataset, like geographical distribution, gender, skintone, etc here in the face mesh model card. Also, you can check out the research papers for [BlazeFace](https://arxiv.org/abs/1907.05047) and [BlazePose](https://arxiv.org/abs/2006.10204) solution.
