### ISSUE TITLE
Python Pose Landmark LiveStream  output with Overlay

### ISSUE THREAD

**Issue by mcdonasd1212** [google/mediapipe#4418]
I am working through the sample [code](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python#live-stream_1)

I understand the results are in the result_call  function, but what if I want to display the livevideo with the  landmark overlay?  This seems to be complicated with the threading, is it possible?

Hopefully, you can provide some sample code.

Thank you!

**Comment by mcdonasd1212** [comment]
My goal is to display the livevideo with the landmark overlay at near real-time.  I can do this with the legacy version of MediaPipe Pose but I would like to use this new version.

**Comment by kuaashish** [comment]
@mcdonasd1212,

Could you please share any reference image compare to the legacy solution, And exact support you are looking from our end?
