### ISSUE TITLE
Using Hand Track Model

### ISSUE THREAD

**Issue by samsgates** [google/mediapipe#442]
Shall i use hand track model in to our mobile SDK product along with our own key-point stability improvement and other additional features (note : it's sellable product as well)
if yes, is there any reference link we should indicate in website or product page?

**Comment by fanzhanggoogle** [comment]
You can use our library in your product for free. See our [license](https://github.com/google/mediapipe/blob/master/LICENSE) for more detail.

**Comment by fanzhanggoogle** [comment]
Feel free to create new issue or reopen if there's other questions.
