### ISSUE TITLE
EffiecientDet in object detection

### ISSUE THREAD

**Issue by willemnator** [google/mediapipe#4420]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Linux

### Python Version

3.10

### Task name (e.g. Image classification, Gesture recognition etc.)

Object detection

### Describe the actual behavior

```shell
There is no support for EffiecientDet training in object detection, currently that is supported in tflite-model-maker but this project seems to be the successor, i can't move over until it supports EffiecientDet training
```

### Describe the expected behaviour

```shell
Support EffiecientDet training
```

### Standalone code/steps you may have used to try to get what you need

```shell
https://github.com/google/mediapipe/blob/b350f7239482b542db325f5fa52d5a3e9193778a/mediapipe/model_maker/python/vision/object_detector/model_spec.py
```

**Comment by robodhhb** [comment]
I also need the support for Efficient_Det_Lite0 training because the Colab support for the old Model Maker (Fallback runtime) is limited. I would help to expand the fallback possibility in Colab until Efficient_Det_Lite0 will be supported.

**Comment by joezoug** [comment]
@willemnator, @robodhhb. Unfortunately we don't plan to support efficientdet anymore as the model is not actively maintained internally. Can you try the new model maker with the MobileNetV2 architecture? It should perform similarly to the previous efficientdet model while being smaller in size.

**Comment by joezoug** [comment]
@willemnator I see, we are working on supporting more mobilenet-based architectures which are larger and have bigger input sizes like (384x384). Those should help with your mentioned issues on smaller objects in images, so please stay tuned for that.

**Comment by AnyLifeZLB** [comment]
Is there any articles comparing yoloV8 and EfficientDet_lite models run on mobile phones ? thank you
