### ISSUE TITLE
Label or name of landmark?

### ISSUE THREAD

**Issue by H1eu69** [google/mediapipe#4421]
I am working with Pose landmark detection and i met an issue: Any way to get the landmark for a specific part of body, for example: i need to get the left-elbow and left-wrist connection to be drawn in a different color the the rest remain the same.

**Comment by ayushgdev** [comment]
Hello @H1eu69 
Please provide the following information to better understand and address your issue:
- Programming Language and version (e.g. C++, Python, Java)
- Are you using MediaPipe Tasks or legacy solutions?
- OS Platform and Distribution

**Comment by H1eu69** [comment]
My OS is Ubuntu 20.04, and i am following this guide using Kotlin:

https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/android

**Comment by ayushgdev** [comment]
Hello @H1eu69 
You can get the Landmark from a NormalizedLandmarkList by providing the index of the corresponding location. The indices are labelled in a human stick figure in the documentation [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker#pose_landmarker_model).

**Comment by H1eu69** [comment]
I am able to get it, thank you so much

**Comment by ayushgdev** [comment]
Can we consider this issue as resolved @H1eu69 ?

**Comment by H1eu69** [comment]
Yeah ty

**Comment by Aries2003** [comment]
hi im trying the same thing but facing some errors can please provide syntax for it .To get the Landmark from a NormalizedLandmarkList by providing the index of the corresponding location

**Comment by Aries2003** [comment]
> I am able to get it, thank you so much

can u provide the snippet of it im doing it with wrong syntax

**Comment by H1eu69** [comment]
> > I am able to get it, thank you so much
> 
> can u provide the snippet of it im doing it with wrong syntax

You can find the syntax in [OverlayView](https://github.com/googlesamples/mediapipe/blob/main/examples/pose_landmarker/android/app/src/main/java/com/google/mediapipe/examples/poselandmarker/OverlayView.kt) at the line 79, replace the 0 number to any index you want to get
