### ISSUE TITLE
pip install mediapipe error

### ISSUE THREAD

**Issue by tomyanth** [google/mediapipe#4424]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows

### Programming Language and version

python

### MediaPipe version

latest

### Solution

Cannot Find one so ask here

### Describe the actual behavior

```shell
cannot use pip install for mediapipe with error

ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

### Describe the expected behaviour

```shell
should be able to install mediapipe
```

### Standalone code/steps you may have used to try to get what you need

```shell
I tried to install different version but does not work
```

**Comment by ayushgdev** [comment]
Hello @tomyanth Please provide the details on
- Windows version
- Python version

**Comment by tomyanth** [comment]
Windows 10
Python 3.9.7

**Comment by kuaashish** [comment]
@tomyanth,

Thank you for bringing out to our notice. As workaround, Please upgrade to Python version to 3.10.7 and let us know if still an issue to build MediaPipe. However, I tried to build using the above mentioned Python version, Pip 22.2.2 with latest version 0.10.0 successfully as screenshot attached below. 

<img width="1475" alt="Pip" src="https://github.com/google/mediapipe/assets/98159216/b51e4f64-6402-4853-a7ec-b1846be355e4">

**Comment by dkackman** [comment]
This also happen for 

- windows 11
- python 3.11.3

**Comment by tomyanth** [comment]
ok. I will try and return to you as soon as possible. Thanks

**Comment by kuaashish** [comment]
@tomyanth,
Could you please update the status of the above. Thanks!!

**Comment by tomyanth** [comment]
It seems to work now even I did not update anything. Thanks.

**Comment by tomyanth** [comment]
Sorry for the late reply because I need to restore the computer environment for the test

**Comment by kuaashish** [comment]
@tomyanth,
Thanks for the confirmation, Can we mark the issue has been resolved and close it as this is no longer issue?

**Comment by tomyanth** [comment]
Of course, will let you know if that happens again

**Comment by kuaashish** [comment]
Hello @dkackman,

To keep context of the easier to filter out the issue with title. We suggest you to raise a fresh issue with problem facing in the Windows 11. As, This issue about the Windows 10. Thank you!!

**Comment by kuaashish** [comment]
@dkackman,
Thanks for the confirmation, Closing this issue as resolved.
