### ISSUE TITLE
How to extract standalone tflite model from hand_landmarker.task file?

### ISSUE THREAD

**Issue by HeloWong** [google/mediapipe#4425]
How to extract standalone tflite model from hand_landmarker.task file? if I just want to use palm detection model not hand landmark model.

**Comment by ayushgdev** [comment]
Hello @HeloWong 
You can simply treat the task files as a bundle and hence, unzip them using a GUI or CLI. So on Mac, double clicking shoudl work. On windows, you can right click and extract. 
On Mac terminal/linux terminal, you can use the command `unzip hand_landmarker.task`. 

**However**, MediaPipe tasks API will not work with only TFLite files. '.task' bundles are required for them. If you only need hand detection, you can use [legacy solution](https://github.com/google/mediapipe/blob/937a6b14228591e30f74142ba4f51e456224bb35/docs/solutions/hands.md) in your applications if you choose. The libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe). But we have ended the support for the issues from legacy solution and will only be providing support for Tasks API now.

**Comment by HeloWong** [comment]
Thanks! I have unzip it and got model I want ✔

**Comment by xiaoli-user** [comment]
> Thanks! I have unzip it and got model I want ✔

Hello! I followed these steps and got two tflite models : hand_detector.tflite and hand_landmarks_detector.tflite. Hand _detector has two output ndarrays with shape (1, 2016, 1) and (1, 2016, 18). How to decode them?

**Comment by xttxqjfg** [comment]
> > Thanks! I have unzip it and got model I want ✔
> 
> Hello! I followed these steps and got two tflite models : hand_detector.tflite and hand_landmarks_detector.tflite. Hand _detector has two output ndarrays with shape (1, 2016, 1) and (1, 2016, 18). How to decode them?

你好，请问这个模型输出的解码有结果了么，我现在和您遇到了一样的问题，在单独使用hand_detector的场景下需要解析结果
