### ISSUE TITLE
why iris tracking do not take account of the rotation of head

### ISSUE THREAD

**Issue by dandingol03** [google/mediapipe#4427]
### OS Platform and Distribution

OSX

### Task name (e.g. Image classification, Gesture recognition etc.)

iris tracking

### Programming Language and version (e.g. C++, Python, Java)

c++

### Describe the actual behavior

In the process of iris-to-depth-tracking, i saw the computing of the iris diameter only consider the x span and y span between iris top landmark and iris bottom landmark. If the face is not exactly facing the screen or there is some rotation of the head in the x-z axis, the iris size would be inaccurate. 

```
inline float GetLandmarkDepth(const NormalizedLandmark& ld0,
                              const NormalizedLandmark& ld1,
                              const std::pair<int, int>& image_size) {
  return GetDepth(ld0.x() * image_size.first, ld0.y() * image_size.second,
                  ld1.x() * image_size.first, ld1.y() * image_size.second);
}
```

### Describe the expected behaviour

Take account of the head pos in iris tracking. For example, compute the projected size of iris in x-y plane, and project back to the corret size with face rotation.

**Comment by kuaashish** [comment]
Hello @dandingol03,

We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) And Now, Iris tracking is part of the Face landmark detection as guided [here](https://developers.google.com/mediapipe/solutions/guide). 

These new solutions will provide a superset of capabilities available in the legacy solutions. We recommend you to explore the our new upgraded solution and revert back if you observe the similar behaviour. Thank you!!
