### ISSUE TITLE
Hand Tracking GPU error desktop

### ISSUE THREAD

**Issue by Jaguaribe21** [google/mediapipe#443]
normally run cpu mode but in GPU mode I can't open it anymore, before I could
any possible solution?, 

my video driver: Nvidia  GT 330M 1GB DDR5

log:

bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS     mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "12b4e8a320cff3e3059a0d19d6f274c1696e59d26afb0d1eb2b3560489020461"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/luciano/.cache/bazel/_bazel_luciano/98eff1f756df47c38a9a95edff319cb4/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/luciano/Downloads/mediapipe/WORKSPACE:34:1
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/luciano/Downloads/mediapipe/mediapipe/examples/desktop/hand_tracking/BUILD:36:1: Linking of rule '//mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/gl_texture/gl_texture.o:gl_texture.cc:function tflite::gpu::gl::GlTexture::BindImage(unsigned int, unsigned int) const: error: undefined reference to 'glBindImageTexture'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/command_queue/command_queue.o:command_queue.cc:function tflite::gpu::gl::(anonymous namespace)::DefaultCommandQueue::Dispatch(tflite::gpu::gl::GlProgram const&, tflite::gpu::Vec3<unsigned int> const&): error: undefined reference to 'glMemoryBarrier'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/command_queue/command_queue.o:command_queue.cc:function tflite::gpu::gl::(anonymous namespace)::AdrenoCommandQueue::Dispatch(tflite::gpu::gl::GlProgram const&, tflite::gpu::Vec3<unsigned int> const&): error: undefined reference to 'glMemoryBarrier'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/gl_program/gl_program.o:gl_program.cc:function tflite::gpu::gl::GlProgram::SetParameter(tflite::gpu::gl::Variable const&): error: undefined reference to 'glProgramUniform4fv'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/gl_program/gl_program.o:gl_program.cc:function tflite::gpu::gl::GlProgram::SetParameter(tflite::gpu::gl::Variable const&): error: undefined reference to 'glProgramUniform1i'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/gl_program/gl_program.o:gl_program.cc:function tflite::gpu::gl::GlProgram::SetParameter(tflite::gpu::gl::Variable const&): error: undefined reference to 'glProgramUniform2i'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/gl_program/gl_program.o:gl_program.cc:function tflite::gpu::gl::GlProgram::SetParameter(tflite::gpu::gl::Variable const&): error: undefined reference to 'glProgramUniform4i'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/gl_program/gl_program.o:gl_program.cc:function tflite::gpu::gl::GlProgram::SetParameter(tflite::gpu::gl::Variable const&): error: undefined reference to 'glProgramUniform1ui'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/gl_program/gl_program.o:gl_program.cc:function tflite::gpu::gl::GlProgram::SetParameter(tflite::gpu::gl::Variable const&): error: undefined reference to 'glProgramUniform4ui'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/gl_program/gl_program.o:gl_program.cc:function tflite::gpu::gl::GlProgram::SetParameter(tflite::gpu::gl::Variable const&): error: undefined reference to 'glProgramUniform1f'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/gl_program/gl_program.o:gl_program.cc:function tflite::gpu::gl::GlProgram::SetParameter(tflite::gpu::gl::Variable const&): error: undefined reference to 'glProgramUniform2f'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/gl_program/gl_program.o:gl_program.cc:function tflite::gpu::gl::GlProgram::SetParameter(tflite::gpu::gl::Variable const&): error: undefined reference to 'glProgramUniform4f'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/gl_program/gl_program.o:gl_program.cc:function tflite::gpu::gl::GlProgram::SetParameter(tflite::gpu::gl::Variable const&): error: undefined reference to 'glProgramUniform2iv'
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/_objs/gl_program/gl_program.o:gl_program.cc:function tflite::gpu::gl::GlProgram::Dispatch(tflite::gpu::Vec3<unsigned int> const&) const: error: undefined reference to 'glDispatchCompute'
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.030s, Critical Path: 0.67s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

Thank you!

**Comment by mcclanahoochie** [comment]
Hi, can you try following these instructions to check for GPU support on your system?
https://github.com/google/mediapipe/blob/master/mediapipe/docs/gpu.md#desktop-gpu-linux

**Comment by Jaguaribe21** [comment]
My GPU doesn't really support, thanks for the support :)
