### ISSUE TITLE
Is it possible to train a new model for hand landmarkers recognition?

### ISSUE THREAD

**Issue by Montag83** [google/mediapipe#4432]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

MacOs - Windows - Colab

### Python Version

3.9 - 3.11

### Task name (e.g. Image classification, Gesture recognition etc.)

Hand Landmarks

### Describe the actual behavior

```shell
Can't find a way to train a hand landmarkers model
```

### Describe the expected behaviour

```shell
Train hand landmarkers model
```

### Standalone code/steps you may have used to try to get what you need

```shell
I would like to train a new hand landmarker model. I see that mediapipe model maker includes libraries and methods to train gesture recognition, image classification and several other types of model but I can't find the corresponding for hand landmarkers recognition. Is there a way to train a hand landmarkers recognition model with my own database?
```

**Comment by ayushgdev** [comment]
Hello @Montag83 
Only image classification and Object detection models can be retrained with model maker.
