### ISSUE TITLE
Official definition of the 478 points for Facemesh points

### ISSUE THREAD

**Issue by ccma1** [google/mediapipe#4435]
There are 478 points provided from the FaceMesh. However, is there an official list that should be referred to when interpreting the points? There have been multiple issues related to this, but there are multiple sources, and I'm unsure which is the one that is officially recommended to follow.

The following have been collected from other issues, but is the following meshmap here https://github.com/tensorflow/tfjs-models/blob/646992fd7ab8237c0dc908f2526301414b417c95/face-landmarks-detection/mesh_map.jpg and keypoint https://github.com/tensorflow/tfjs-models/blob/838611c02f51159afdd77469ce67f0e26b7bbb23/face-landmarks-detection/src/mediapipe-facemesh/keypoints.ts from the tfjs repo the same as the one used for the legacy face mesh for Python?

Plotting it shows it looks correct, but I just want to confirm. Thank you.

**Comment by ayushgdev** [comment]
Hello @ccma1 
This information is available in MediaPipe directory as well. The face landmarks' visualisation is available [here](https://github.com/google/mediapipe/blob/7c28c5d58ffbcb72043cbe8c9cc32b40aaebac41/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png). And the contours which join the face landmarks are available [here](https://github.com/google/mediapipe/blob/7c28c5d58ffbcb72043cbe8c9cc32b40aaebac41/mediapipe/python/solutions/face_mesh_connections.py)
