### ISSUE TITLE
Integrate Mediapipe into a python project

### ISSUE THREAD

**Issue by QBoulanger** [google/mediapipe#444]
Hi!

I would like to integrate Mediapipe into a python project. Do you have any tips, or advice on how could I efficiently do so? 

Thank you for your help!

**Comment by mgyong** [comment]
We are working on enabling MediaPipe graphs to run in python basically a MediaPipe Python graph execution API. We will update this thread when we have something to share as we get closer. Thanks

**Comment by trojan03** [comment]
Hi,

you've mentioned that you plan to release a MediaPipe Python graph execution API. Do you already roughly know when it will be shared? We already use https://github.com/metalwhale/hand_tracking but are not happy with the inference speed which is about 12-14 FPS compared to ca. 25 FPS that we achieve using Mediapipe. 

Thank you!

**Comment by Zumbalamambo** [comment]
+1

**Comment by heiwushi** [comment]
+1

**Comment by mgyong** [comment]
Initially plan is to release in Q3 2020 (tentative) a python graph execution API (graph runner) that allows you to run a compiled MediaPipe graph in python.

**Comment by Zumbalamambo** [comment]
+1

**Comment by mgyong** [comment]
@Zumbalamambo @QBoulanger @Zumbalamambo MediaPipe for Python has been launched in [v0.7.9](https://github.com/google/mediapipe/releases/tag/v0.7.9) https://google.github.io/mediapipe/getting_started/building_examples.html#python

**Comment by Zumbalamambo** [comment]
Thank you!!!!!!!!
