### ISSUE TITLE
jni detected error in application: jni getobjectclass called with pending exception java.lang.noclassdeffounderror: com.google.mediapipe.formats.proto.landmarkproto$normalizedlandmarklist

### ISSUE THREAD

**Issue by KauaOrtiz** [google/mediapipe#4441]
### OS Platform and Distribution

Android

### Programming Language and version

Java

### Installed using virtualenv? pip? Conda?(if python)

No

### Android SDK and NDK versions (if android)

SDK 33, NDK 23.1

### Android AAR (if android)

Yes

### Describe the problem

```shell
Hello guys, I'm having a problem with integrating Face Mesh into an app. Initially I made a prototype with the same specifications of SDK, NDK etc. But I'm getting a JNI Error (I've already switched from Protobuflite to Protobuf). Could someone help me where to proceed?
```

### Complete Logs

```shell
Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI GetObjectClass called with pending exception java.lang.NoClassDefFoundError: com.google.mediapipe.formats.proto.LandmarkProto$NormalizedLandmarkList
        at void net.osmand.plus.activities.MapActivity.lambda$onCreate$5$net-osmand-plus-activities-MapActivity(com.google.mediapipe.framework.Packet) (MapActivity.java:811)
        at void net.osmand.plus.activities.MapActivity$$ExternalSyntheticLambda13.process(com.google.mediapipe.framework.Packet) (D8$$SyntheticClass:-1)
     Caused by: java.lang.NoSuchMethodError: No static method emptyProtobufList()Lcom/google/protobuf/Internal$ProtobufList; in class Lcom/google/mediapipe/formats/proto/LandmarkProto$NormalizedLandmarkList; or its super classes (declaration of 'com.google.mediapipe.formats.proto.LandmarkProto$NormalizedLandmarkList' appears in /data/app/~~HDpRMbZFIXSLVwd4kbAi6Q==/br.com.crearesistemas.driverhero-OCtl1-4e1NuBfyADh-YIdQ==/base.apk!classes31.dex)
        at void com.google.mediapipe.formats.proto.LandmarkProto$NormalizedLandmarkList.<init>() (LandmarkProto.java:2220)
        at void com.google.mediapipe.formats.proto.LandmarkProto$NormalizedLandmarkList.<clinit>() (LandmarkProto.java:2573)
        at com.google.protobuf.Parser com.google.mediapipe.formats.proto.LandmarkProto$NormalizedLandmarkList.parser() (LandmarkProto.java:2588)
        at void net.osmand.plus.activities.MapActivity.lambda$onCreate$5$net-osmand-plus-activities-MapActivity(com.google.mediapipe.framework.Packet) (MapActivity.java:811)
        at void net.osmand.plus.activities.MapActivity$$ExternalSyntheticLambda13.process(com.google.mediapipe.framework.Packet) (D8$$SyntheticClass:-1)
```

**Comment by kuaashish** [comment]
Hello @KauaOrtiz,
Would you let us know the complete details about the issues such as operating system using, steps you have followed to reproduce the issue from our end and share the possible solution on error you are getting. Thank you

**Comment by KauaOrtiz** [comment]
Hey @kuaashish,
First of all I installed Mediapipe in Windows using the [WSL tutorial](https://developers.google.com/mediapipe/framework/getting_started/install#installing_on_windows_subsystem_for_linux_wsl) and implemented the AAR Archive of Face Mesh from [Android tutorial](https://developers.google.com/mediapipe/framework/getting_started/android_archive_library).

I created some classes and function to start the camera, calculate euclidean distance and of course to process the frames. The application starts running OK, even turn on the camera, but when i show up in the image the face mesh recognize my face and drawings the points the app crash with **jni detected error in application: jni getobjectclass called with pending exception java.lang.noclassdeffounderror: com.google.mediapipe.formats.proto.landmarkproto$normalizedlandmarklist**.

Logcat it returns me that the error is in this part of code:

`processor.addPacketCallback(
                    OUTPUT_LANDMARKS_STREAM_NAME,
                    (packet) -> {
                        android.util.Log.v("TAG", "Received multi face landmarks packet.");
                        List<LandmarkProto.NormalizedLandmarkList> multiFaceLandmarks =
                                PacketGetter.getProtoVector(packet, LandmarkProto.NormalizedLandmarkList.parser());`

To call processor using this code:
`eglManager = new EglManager(null);
        processor =
                new FrameProcessor(
                        this,
                        eglManager.getNativeContext(),
                        "face_mesh_mobile_gpu.binarypb",
                        "input_video",
                        "output_video");
        processor.getVideoSurfaceOutput().setFlipY(FLIP_FRAMES_VERTICALLY);
        AndroidPacketCreator packetCreator = processor.getPacketCreator();
        Map<String, Packet> inputSidePackets = new HashMap<>();
        inputSidePackets.put(INPUT_NUM_FACES_SIDE_PACKET_NAME, packetCreator.createInt32(NUM_FACES));
        processor.setInputSidePackets(inputSidePackets);`
        
From what I understand of the error, it is in the part of returning the list of face mesh points, when i was looking from solution i found a issue closed in MediaPipe Repository [#443 (Comment)](https://github.com/google/mediapipe/issues/643#issuecomment-618578061) to change protobuflite to protobuf but the error persists.
       
I don't know if I've given you all the information you need but I'm here to answer anything you need! And again thanks a lot for the help!

**Comment by kuaashish** [comment]
@KauaOrtiz,

Sorry for the delayed response, This issue is already known to us, And We are working towards the fix. We will let you know once any update becomes available. Thank you

**Comment by kuaashish** [comment]
Hi @KauaOrtiz,

We are no longer maintaining the legacy facemesh solution, as it has been integrated into the new Face Landmarker task API, as explained in our [documentation](https://developers.google.com/mediapipe/solutions/guide#legacy). We intend to explore and implement our upgraded Face Landmarker in Android, following the steps outlined in our [documentation](https://developers.google.com/mediapipe/solutions/vision/face_landmarker/android). Additionally, we kindly request you to inform us of any errors encountered during the exploration process.

Thank you
