### ISSUE TITLE
Does Mediapipe remove IOS solution for Pose tracking?

### ISSUE THREAD

**Issue by richardcoder** [google/mediapipe#4442]
Sorry to bother, I remember mediapipe has solution for Pose detection/tracking on IOS in old documentation. But on new version website I cannot find the sample solution. And iOS target: [mediapipe/examples/ios/posetrackinggpu:PoseTrackingGpuApp](http://mediapipe/examples/ios/posetrackinggpu/BUILD) which provided in current documentation is also invalid.

So I just want to know if Mediapipe has removed the sample of IOS pose tracking and if I want to build this solution on IOS edge devices, is there any documentation I can refer to? 

Thanks in advance !

**Comment by richardcoder** [comment]
In addition, maybe my memory is not correct. Is MLKit the solution provided for IOS App? Thanks!

**Comment by ayushgdev** [comment]
Hello @richardcoder 
We have not released new MediaPipe Tasks API for iOS yet. The new APIs will be released very soon as we are trying hard to help users transition from legacy to new APIs, but cannot commit on the release timeline for now.
