### ISSUE TITLE
Mediapipe in android

### ISSUE THREAD

**Issue by akokhlik** [google/mediapipe#4445]
I use this in Android  build.gradle     implementation 'com.google.mediapipe:mediapipe-hairsegmentation:0.8.4.1'

and get this error

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.mediapipe:mediapipe-hairsegmentation:0.8.4.1.
     Required by:
         project :app
      > Could not resolve com.google.mediapipe:mediapipe-hairsegmentation:0.8.4.1.
         > Could not get resource 'https://google.bintray.com/mediapipe/com/google/mediapipe/mediapipe-hairsegmentation/0.8.4.1/mediapipe-hairsegmentation-0.8.4.1.pom'

Thank you in advance

**Comment by kuaashish** [comment]
Hello @akokhlik,
 Would you please let us know the complete details about the issue such as steps you have followed, Information about the 
 Operating System, SDK or NDK version using to reproduce the issue from end. We also recommend to fill the issue template 
 to get maximum relevant information to debug the issue.  Thank you!
