### ISSUE TITLE
Face Landmarks transformation matrix to move 3D model in Unity

### ISSUE THREAD

**Issue by brunodeangelis** [google/mediapipe#4449]
The idea I have is essentially to use the face transformation matrix in Unity to apply the transformation to the Canonical 3d mesh, so that I can parent GameObjects to the face and have them move along, or render custom shaders on the face mesh. 

I've carefully read #1642 to try to understand how I can do this or if it is even possible, but I'm still having a hard time figuring it out. I'm aware that somewhere in this process I'd have to take into account the webcam/camera stream or image resolution/aspect ratio, but I'm unsure yet.

Has anyone tried this approach? Appreciate the support

**Comment by kuaashish** [comment]
@brunodeangelis,

MediaPipe does not offer any official support/library/module for mapping the face landmarks to Unity as such. However, 
there are [plugin](https://github.com/homuler/MediaPipeUnityPlugin) from the community is quite up-to-date which might help in this context But We don't have a plan to support Unity yet and does not provide support in how to use them.
 
Thank you!!

**Comment by JimHeo** [comment]
Hi, I have a question about facial_transformation_matrixes from FaceLandmarkerResult.
I extracted translation x,y,z from facial transformation matrix.
But, I have no idea what the range of x,y,z is...
I just want to normalize [0,1], then how can I do...?
