### ISSUE TITLE
Palm detection any tips on how to program it? - Hand Tracking

### ISSUE THREAD

**Issue by FabricioHA** [google/mediapipe#445]
https://github.com/TheJLifeX/mediapipe

There is some way to detect the left or right hand when turning them, because when running the program, the fingers are not recognized correctly.

Thank you for your support.

**Comment by fanzhanggoogle** [comment]
Hi, we do plan to support predicting handedness in our next version and the work is in progress. Hopefully we can get to a point where we can release soon.
Also, would you mind post some examples that the tracking doesn't work for you? It'll be nice for us to understand more about the model limitation. Thank you!

**Comment by JuliaPoo** [comment]
You can determine handedness using ```hand_landmark``` in 3D. Here's my approach in python which I used in my python implementation of the Multi-hand Tracking pipeline:

```python
def is_right_hand(kp):
    
    '''
    Returns True if kp is right hand and False if left hand.
    '''
    
    digitgroups = [
        (17,18,19,20),
        (13,14,15,16),
        (9,10,11,12),
        (5,6,7,8),
        (2,3,4) # Thumb
    ]
    
    palm_dir_vec = np.array([0,0,0], dtype=np.float64)
    for digit in digitgroups:
        for idx in digit[1:]:
            palm_dir_vec += kp[idx] - kp[digit[0]]
            
    palm_pos_vec = np.array([0,0,0], dtype=np.float64)
    for digit in digitgroups:
        palm_pos_vec += kp[digit[0]]
    palm_pos_vec /= len(digitgroups)
    
    top_palm_pos_vec = kp[9]
    
    val = np.dot(np.cross(kp[2] - palm_pos_vec, palm_dir_vec), top_palm_pos_vec - palm_pos_vec)

    if val < 0: return True
    
    return False
```

Here kp is a list of 3D coordinates representing the keypoints.

**Comment by russelldj** [comment]
@JuliaPoo would you be willing to share how you extracted the keypoints into Python?

**Comment by JuliaPoo** [comment]
The reason why I wrote it in python was because I already wrote a python implementation of the Multi-Hand Tracking pipeline and wanted to detect handedness (it's on my github). However, it's entirely possible to implement it on top of the existing pipeline provided by Mediapipe.

**Comment by mgyong** [comment]
Updated the hand model in v0.7.5 for predicting left or right hand.  @JuliaPoo 
@FabricioHA  https://github.com/google/mediapipe/releases/tag/v0.7.5

**Comment by vasanthhr** [comment]
Hi @mgyong @JuliaPoo 

I want to see the prediction of left or right hand in the handpose model(tfjs-model: handpose model).

As of now i can see 21 3d keypoints as output, please suggest me how to predict left or right hand on this handpose model.

**Comment by JuliaPoo** [comment]
@vasanthhr As from release [v0.7.5](https://github.com/google/mediapipe/releases/tag/v0.7.5) onwards, handedness prediction is supported.

**Comment by vasanthhr** [comment]
@JuliaPoo 

This is the handpose I am refering to: [here](https://github.com/tensorflow/tfjs-models/tree/master/handpose) , in this package  I didn't get distinguish left or right hand . Please check on the same.

I gone through code, but I didn't see where in code gets predict left or right hand.

Please check if you can update this repository. Thanks and appreciate you.

**Comment by JuliaPoo** [comment]
@vasanthhr If you want the code responsible for predicting handedness, it is [here](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_tensors_to_classification_calculator.cc). In the [mediapipe graph](https://viz.mediapipe.dev/demo/hand_tracking) for handtracking it is the node called `TfLiteTensorsToClassificationCalculator`.

**Comment by YashRunwal** [comment]
Hello guys! I am working on the same topic now and I have an output which has Hand:[1] and Hand:[2] but can someone help me with what needs to be changed in order to get whether it is a left or a right hand?
