### ISSUE TITLE
Could I obtain an FBX file through Pose landmark detection task

### ISSUE THREAD

**Issue by chenjingyiyaya** [google/mediapipe#4451]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

haven't
### OS Platform and Distribution

Ubuntu 18.04

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose Estimation

### Programming Language and version (e.g. C++, Python, Java)

python

### Describe the actual behavior

```shell
I can get 3-dimensional world coordinates through the pose estimation model with a video
```

### Describe the expected behaviour

```shell
But I want to obtain an FBX format file and apply it in Blender，do you have any soulutions?
```

### Standalone code/steps you may have used to try to get what you need

```shell
none
```

**Comment by ayushgdev** [comment]
Hello @chenjingyiyaya 
MediaPipe does not offer any official support/library/module for converting the landmarks to blendshapes output as such. However, there are third party tools which might help in this context. But we do not provide support in how to use them.
- NVIDIA Maxine AR
- [KalidoKit](https://github.com/yeemachine/kalidokit)

**Comment by chenjingyiyaya** [comment]
Oh，Thank you very much for providing the solution

**Comment by zhangsirya** [comment]
> Can KalidoKit algorithm retrieve the blendshape data for pose estimation?
