### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Jie1124** [google/mediapipe#4453]
<img width="1184" alt="image" src="https://github.com/google/mediapipe/assets/134267672/28e9dbc1-aa7e-4015-83fa-76f205b9c486">

**Comment by Jie1124** [comment]
who can  help me ? thanks

**Comment by ayushgdev** [comment]
@Jie1124 Please provide complete context of the issue. We request you to follow the New issue template [here](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Atask&projects=&template=00-task-issue-template.yaml) if you are using MediaPipe Tasks API  or [here](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Asupport&projects=&template=18-solution-legacy-issue-template.yaml) if you are using MediaPipe Legacy solutions. and then add the details requested in the form.
