### ISSUE TITLE
Recognizing body points with the new Mediapipe tasks-vision API

### ISSUE THREAD

**Issue by xfish3** [google/mediapipe#4457]
In the example published on https://codepen.io/kvasss/pen/dygwpZz, when clicking on the image of a girl, both the key points of the hands and the points of the body are recognized. However, if you click on "Enable camera", then the body points are not displayed.

There is a snippet in the JavaScript code that should display key points of the body, but for some reason it doesn't work (
lines 217-230):

```
if (video.currentTime !== lastVideoTime) {
    lastVideoTime = video.currentTime;
    results = gestureRecognizer.recognizeForVideo(video, nowInMs);
    poseLandmarker.detectForVideo(video, startTimeMs, (result) => {
      canvasCtx.save();
      canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
      for (const landmark of result.landmarks) {
        drawingUtils.drawLandmarks(landmark, {
          radius: (data) => DrawingUtils.lerp(data.from!.z, -0.15, 0.1, 5, 1)
        });
        drawingUtils.drawConnectors(landmark, PoseLandmarker.POSE_CONNECTIONS);
      }
      canvasCtx.restore();
    });
```
	
Why are body points not recognized when connecting the PoseLandmarker module from the new Mediapipe tasks-vision?

**Comment by ayushgdev** [comment]
Hello @xfish3 
On the link shared, there isn't any image of the girl. Also, on enabling the camera, this is working fine. It is drawing the landmarks and connections and predicting the pose if Predictions are enabled. If you click on Disable predictions, then only it will not predict any pose.

**Comment by xfish3** [comment]
Thank you very much for the answer!
Just yesterday, after I wrote, they corrected the example. So now everything is working fine :-)

**Comment by ayushgdev** [comment]
Okay @xfish3 . We shall close this issue now.
