### ISSUE TITLE
why build pose tracking aar are more than 180mb?

### ISSUE THREAD

**Issue by LTYF** [google/mediapipe#4460]
### OS Platform and Distribution

Ubuntu 20

### Programming Language and version

python3.6.5

### Android AAR (if android)

Yes

### Describe the problem

```shell
used this command:
bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a mediapipe/examples/android/src/java/com/google/mediapipe/apps/build_aar:lt_pose_tracking_aar

how can i do if i wanted build the aar less than 30mb?
```

### Complete Logs

```shell
BUILD File:

load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
	name = "lt_pose_tracking_aar",
	calculators = ["//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps"],
)
```

**Comment by PrinceP** [comment]
https://developers.google.com/mediapipe/framework/getting_started/android_archive_library 

bazel build -c opt --strip=ALWAYS \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    --legacy_whole_archive=0 \
    --features=-legacy_whole_archive \
    --copt=-fvisibility=hidden \
    --copt=-ffunction-sections \
    --copt=-fdata-sections \
    --copt=-fstack-protector \
    --copt=-Oz \
    --copt=-fomit-frame-pointer \
    --copt=-DABSL_MIN_LOG_LEVEL=2 \
    --linkopt=-Wl,--gc-sections,--strip-all \

should be used now.

**Comment by kuaashish** [comment]
@LTYF,
Please add "//mediapipe/gpu:gpu_buffer_to_image_frame_calculator" to the calculators list of the [mediapipe_aar](https://developers.google.com/mediapipe/framework/getting_started/android_archive_library).
