### ISSUE TITLE
I want to use the pose tracking framework to detect static images and return key point information of the human body. What should I do?

### ISSUE THREAD

**Issue by LTYF** [google/mediapipe#4461]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### Describe the actual behavior

```shell
There seem to be significant differences between different versions of methods，
```

**Comment by kuaashish** [comment]
@LTYF,

Sorry for the delayed response, Could you please let us know if you are still looking for the resolution on this or issue has been resolved from your end. Thank you
