### ISSUE TITLE
[Help] Does anyone build facemesh framework for iOS?

### ISSUE THREAD

**Issue by nguyencse** [google/mediapipe#4463]
Does anyone build facemesh framework for iOS?
I did not meet the requirements to build the bazel for ios on macOS Ventura with xcode 14.3.

Any helps will be appreciated :((

**Comment by kuaashish** [comment]
@nguyencse,
Would you please try with Xcode 14.2 and MediaPipe 0.10.0 as workaround? There is a known issue in Xcode 14.3 on which team is working actively.

**Comment by nguyennyssf** [comment]
ok thanks @kuaashish I'll try it

**Comment by nguyennyssf** [comment]
Yes, I confirm that I can build v0.10.0 in Xcode 14.2. Thank you for your announcement @kuaashish

**Comment by kuaashish** [comment]
@nguyencse,
Thank you for the confirmation. We are working towards fix the issue with Xcode 14.3, If Xcode version is no longer issue blocker from your end. Can we mark issue to resolved and close it?

**Comment by nguyennyssf** [comment]
sure, thank you @kuaashish

**Comment by nguyencse** [comment]
https://github.com/google/mediapipe/pull/4517

`sudo bash ./build_face_mesh_ios_framework.sh`

This is the script to build xcframework from facemesh for iOS.
