### ISSUE TITLE
python - how to extract non-normalized hand landmark pixel coordinates with labels

### ISSUE THREAD

**Issue by neuropil** [google/mediapipe#4472]
Thank you for providing this pipeline!

I was wondering what set of python functions are best for extracting a table of values for the non-normalized pixel coordinates of the hand landmarks.

I'm assuming the input to the function(s) would be the detection_result?

`annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)`

thanks!

**Comment by kuaashish** [comment]
@neuropil,

Could you please confirm that you are still looking for resolution or the issue has been resolved from your end? Thank you!

**Comment by neuropil** [comment]
@kuaashish I have not received an answer to this query and would greatly appreciate any help!

**Comment by kuaashish** [comment]
Hello @neuropil,

This can be done from below class:

https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/drawing_utils.py#L49

Please update the status, if this works for you. Thank you!!

**Comment by neuropil** [comment]
@kuaashish perfect - thank you so much!
