### ISSUE TITLE
    mp_holistic.FACEMESH_IRISES,     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'mediapipe.python.solutions.holistic' has no attribute 'FACEMESH_IRISES'

### ISSUE THREAD

**Issue by Jetas18** [google/mediapipe#4475]
here is my code

`import mediapipe as mp
import cv2 as cv

mp_drawing = mp.solutions.drawing_utils
mp_holistic = mp.solutions.holistic

capture = cv.VideoCapture(0)
with mp_holistic.Holistic(
    min_detection_confidence=0.7, min_tracking_confidence=0.7
) as holistic:
    while capture.isOpened():
        ret, frame = capture.read()

        frame = cv.resize(frame, (900, 700))

        cv.flip(frame, 1)
        # Detect stuff and render stuff
        image = cv.cvtColor(frame, cv.COLOR_BGR2RGB)
        image.flags.writeable = False

        # Make detections
        results = holistic.process(image)

        image.flags.writeable = True

        image = cv.cvtColor(image, cv.COLOR_RGB2BGR)

        mp_drawing.draw_landmarks(
            image,
            results.face_landmarks,
            mp_holistic.FACEMESH_TESSELATION,
            mp_drawing.DrawingSpec(color=(91, 64, 61), thickness=1, circle_radius=1),
            mp_drawing.DrawingSpec(color=(129, 178, 154), thickness=1, circle_radius=2),
        )

        mp_drawing.draw_landmarks(
            image,
            results.pose_landmarks,
            mp_holistic.POSE_CONNECTIONS,
            mp_drawing.DrawingSpec(color=(91, 64, 61), thickness=2, circle_radius=2),
            mp_drawing.DrawingSpec(color=(129, 178, 154), thickness=2, circle_radius=2),
        )

        mp_drawing.draw_landmarks(
            image,
            results.left_hand_landmarks,
            mp_holistic.HAND_CONNECTIONS,
            mp_drawing.DrawingSpec(color=(91, 64, 61), thickness=2, circle_radius=2),
            mp_drawing.DrawingSpec(color=(129, 178, 154), thickness=2, circle_radius=2),
        )

        mp_drawing.draw_landmarks(
            image,
            results.right_hand_landmarks,
            mp_holistic.HAND_CONNECTIONS,
            mp_drawing.DrawingSpec(color=(91, 64, 61), thickness=2, circle_radius=2),
            mp_drawing.DrawingSpec(color=(129, 178, 154), thickness=2, circle_radius=2),
        )

        mp_drawing.draw_landmarks(
            image,
            results.face_landmarks,
            mp_holistic.FACEMESH_IRISES,
            mp_drawing.DrawingSpec(color=(91, 64, 61), thickness=1, circle_radius=1),
            mp_drawing.DrawingSpec(color=(129, 178, 154), thickness=1, circle_radius=2),
        )

        cv.imshow("YAyyyyyy", image)

        if cv.waitKey(1) & 0xFF == ord("d"):
            break

capture.release()
cv.destroyAllWindows()
`

**Comment by kuaashish** [comment]
@Jetas18,

Would you please let us know the complete steps you are following from the documentation? We can see 
 here in Base Class https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/holistic.py do not have such attributes FACEMESH_IRISES. Also, We recommend to fill the [issue template](https://github.com/google/mediapipe/issues/new/choose) to receive relevant information to reproduce the issue from our end. 

Thank you!!!
