### ISSUE TITLE
Tracking results are significantly different between Android and iOS

### ISSUE THREAD

**Issue by fchen09** [google/mediapipe#4476]
I am using the same set of pose_detection.tflite and pose_landmark_full.tflite, running on Android phone and IPhone, and it gives different tracking positions for joints. iPhone is more accurate. Can you explain how come it gives different results on different platforms? Thank you!

**Comment by kuaashish** [comment]
@fchen09,

We have implemented the model ops on CPU, XNNPack, Metal, OpenGL, WebGL However, each platform uses the different Inference engine. For example, MediaPipe iOS uses Metal as Inference engine and Android is normally uses XNNPack.
