### ISSUE TITLE
Display x,y,z coordinates on one node in hand tracking

### ISSUE THREAD

**Issue by romaindebraize** [google/mediapipe#448]
Hi,
I am working on HandTracking for Android and i would like to see the coordinates of the nodes and display them in live. 

Is there a way to do it ?

Thanks

**Comment by mgyong** [comment]
See code for Android
https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L122-L127

**Comment by romaindebraize** [comment]
Thanks for the fast answer.

Indeed, i figured out how to display X and Y coordinates thanks to `getLandmarksDebugString(landmarks)` but the Z is still at zero. Where can i find this one ? 

More generally, is there an android code example for this feature :
![hand_tracking_3d_android_gpu_small](https://user-images.githubusercontent.com/60918250/74321573-c8501480-4d82-11ea-86b9-9cd03f101ac2.gif)

**Comment by romaindebraize** [comment]
I changed the model  the tflite model path in the
/mediapipe/mediapipe/graphs/hand_tracking/subgraphs/hand_landmark_gpu.pbtxt from `hand_landmark.pbtxt` to `hand_landmark_3d.pbtxt` as explained here : https://github.com/google/mediapipe/issues/202#issuecomment-548987764
