### ISSUE TITLE
How can i know whether some face landmarks are occluded

### ISSUE THREAD

**Issue by dandingol03** [google/mediapipe#4484]
### OS Platform and Distribution

Android Platform

### Task name (e.g. Image classification, Gesture recognition etc.)

Face Detect

### Programming Language and version (e.g. C++, Python, Java)

c++

### Describe the actual behavior

I use face mesh module and geometry module to implement ar face makeup. However i find the face landmark's visibity is always 0. Because We us virtual glass asset to fit user's face, we want to  remind the user if he/she is wearing mask. So How can i know if some face landmark are occluded?

### Describe the expected behaviour
Get the visibility of face mesh landmarks

**Comment by kuaashish** [comment]
Hello @dandingol03,

Thanks for raising this issue. This is indeed an improvement we expect to be present in the MediaPipe solutions. Currently We do not support the detection of occluded landmarks. We shall take this feature request and prfioritize it internally to make it available by default/by using some config options.

**Comment by dandingol03** [comment]
ok, i got it

**Comment by PMPBinZhang** [comment]
now, Mediapipe can return face landmarkes visibility and precense?
