### ISSUE TITLE
I have a problem with gen_protos on aarch64 platform.

### ISSUE THREAD

**Issue by Heartful-echo** [google/mediapipe#4489]
### OS Platform and Distribution

Ubuntu20.04 LTS

### Compiler version

gcc/gcc+8

### Programming Language and version

Python3.8

### MediaPipe version

0.10.0

### Bazel version

5.1

### Android AAR (if android)

None

### Describe the problem

```shell
I have successfully built MediaPipe 0.9.3.0 on aarch64 platform, created whl file and run it on Raspberry Pi4.

However, when building with MediaPipe 0.10.0 using the same procedure, the following error is output.

How can i solve this problem?
```

### Complete Logs

```shell
root@ubuntu:/mp/mediapipe# python3 setup.py gen_protos
running gen_protos
generating proto file: build/lib.linux-aarch64-3.8/mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options_pb2.py
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:30:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:34:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:39:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:44:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
mediapipe/tasks/cc/components/processors/proto/detection_postprocessing_graph_options.proto:47:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
root@ubuntu:/mp/mediapipe#
```

**Comment by kuaashish** [comment]
Hello @Heartful-echo,

Could you please elaborate your query with complete details and steps followed to reproduce the issue from our end.

**Comment by Heartful-echo** [comment]
Hi @kuaashish 

Thank you for your comment.

My steps are below.
$ git clone -b v0.10.0 https://github.com/google/mediapipe

$ sed -i -e "/\"imgcodecs\"/d;/\"calib3d\"/d;/\"features2d\"/d;/\"highgui\"/d;/\"video\"/d;/\"videoio\"/d" third_party/BUILD
$ sed -i -e "/-ljpeg/d;/-lpng/d;/-ltiff/d;/-lImath/d;/-lIlmImf/d;/-lHalf/d;/-lIex/d;/-lIlmThread/d;/-lrt/d;/-ldc1394/d;/-lavcodec/d;/-lavformat/d;/-lavutil/d;/-lswscale/d;/-lavresample/d" third_party/BUILD

$ sed -i -e "/^        # Optimization flags/i \        \"ENABLE_NEON\": \"OFF\"," third_party/BUILD
$ sed -i -e "/^        # Optimization flags/i \        \"WITH_TENGINE\": \"OFF\"," third_party/BUILD

$ sudo python3 setup.py gen_protos

Next, I want to run the following command to build, but I get an error with python3 setup.py gen_protos.

sudo python3 setup.py bdist_wheel

I see a file called detection_*** added in 0.10.0.
This file has syntax = "proto3"; Until now it was syntax = "proto2";
I'm assuming this has an effect.

I tried changing the syntax="proto3" in the detection_*** files to syntax="proto2" and building.
The whl file is created but when I write the code using this whl file I get the below error.

root@ubuntu:/mp# python3 object.py
Traceback (most recent call last):
  File "object.py", line 3, in <module>
    import mediapipe as mp
  File "/usr/local/lib/python3.8/site-packages/mediapipe/__init__.py", line 30, in <module>
    import mediapipe.tasks.python as tasks
ImportError: cannot import name 'python' from 'mediapipe.tasks.python' (/usr/local/lib/python3.8/site-packages/mediapipe/tasks/python/__init__.py)

**Comment by kuaashish** [comment]
@Heartful-echo

I could not reproduce the issue from our end. Would you please let us know the complete steps followed from the mediapipe documentation or Any link? Which you can point here that will be helpful to reproduce the issue.

**Comment by Heartful-echo** [comment]
@kuaashish 

Can you provide the whl file of mediapipe0.10.0 for aarch64 in python3.8 environment?
My aim is to use mediapipe0.10.0 on Raspberry Pi4 64bit.
Thank you

**Comment by kuaashish** [comment]
@Heartful-echo,

We do not have official wheels for aarch64 in python now. However, Support of Raspberry Pi is in our roadmap and will be available soon.

**Comment by Heartful-echo** [comment]
@kuaashish 

This is very good information.
I hope one day MediaPipe will be available on Raspberry Pi and CPUs with the same aarch64 architecture.
This case will be closed.

I appreciate your support.

**Comment by Heartful-echo** [comment]
@kuaashish

This is very good information.
I hope one day MediaPipe will be available on Raspberry Pi and CPUs with the same aarch64 architecture.
This case will be closed.

I appreciate your support.
