### ISSUE TITLE
The mapping between mediapipe and dlib's 68 key points

### ISSUE THREAD

**Issue by shuishiwojiade** [google/mediapipe#4490]
Are there 68 key points in mediapipe that are semantically close to dlib? If it does, I want to know the mapping between mediapipe and dlib's 68 key points. 
Thanks a million!

**Comment by kuaashish** [comment]
Hello @shuishiwojiade,

Please provide complete context of the issue. We request you to follow the New issue template [here](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Atask&projects=&template=00-task-issue-template.yaml) if you are using MediaPipe Tasks API or [here](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Asupport&projects=&template=18-solution-legacy-issue-template.yaml) if you are using MediaPipe Legacy solutions. and then add the details requested in the form.

**Comment by PeizhiYan** [comment]
https://github.com/PeizhiYan/Mediapipe_2_Dlib_Landmarks

This code maps Mediapipe's 478 dense facial landmarks to Dlib's 68 sparse facial landmarks by defining correspondences where each Dlib landmark index corresponds to one or two Mediapipe indices, averaging coordinates when necessary. The function convert_landmarks_mediapipe_to_dlib converts an array of Mediapipe landmarks into Dlib landmarks using this predefined mapping.
