### ISSUE TITLE
MacOS 11.2.3 cannot install 0.10.0

### ISSUE THREAD

**Issue by HuanjieGuo** [google/mediapipe#4492]
### OS Platform and Distribution

macOS 11.2.3

### Programming Language and version

python 3.7

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

0.10.0

### Android AAR (if android)

None

### Describe the problem

```shell
pip install mediapipe==0.10.0
ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.0 (from versions: 0.7.10, 0.8.0, 0.8.1, 0.8.2, 0.8.3.1, 0.8.4.2, 0.8.5, 0.8.6.2, 0.8.7.1, 0.8.7.2, 0.8.7.3, 0.8.8, 0.8.8.1, 0.8.9, 0.8.9.1, 0.8.10, 0.8.10.1, 0.8.11, 0.9.0, 0.9.0.1)
ERROR: No matching distribution found for mediapipe==0.10.0
```

### Complete Logs

```shell
ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.0 (from versions: 0.7.10, 0.8.0, 0.8.1, 0.8.2, 0.8.3.1, 0.8.4.2, 0.8.5, 0.8.6.2, 0.8.7.1, 0.8.7.2, 0.8.7.3, 0.8.8, 0.8.8.1, 0.8.9, 0.8.9.1, 0.8.10, 0.8.10.1, 0.8.11, 0.9.0, 0.9.0.1)
ERROR: No matching distribution found for mediapipe==0.10.0
```

**Comment by Hernandiaz035** [comment]
I ran into the same issue installing mediapipe inside a container, also tried to build the google/mediapipe/dockerfile image and I ran into an architecture mismatch problem

```bash
$ docker run -it --name mediapipe mediapipe:latest

root@62cb30ae1814:/mediapipe# GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world

qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
ERROR: The project you're trying to build requires Bazel 6.1.1 (specified in /mediapipe/.bazelversion), but it wasn't found in /usr/local/lib/bazel/bin.
```

**Comment by kuaashish** [comment]
Hello @Hernandiaz035,

We can see that Python 3.7 is being used to build the MediaPipe, Which is not supported version to build MediaPipe. We only support Python >=3.8 and <=3.10. Python 3.11 is only supported on MacOS and Linux as mentioned [here](https://developers.google.com/mediapipe/solutions/setup_python). Also, We recommend using the macOS version 13.* pr above to not get build to failed. Please upgrade to the supported versions and let us know if the encounter the similar error. Thank you!

**Comment by HuanjieGuo** [comment]
@kuaashish Hi, I upgraded my macOS to 13.4 and tried on python3.9 and 3.11.

I still get the same result. 

```
pip install mediapipe==0.10.0      

ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.0 (from versions: 0.8.9.1, 0.8.10, 0.8.10.1, 0.8.11, 0.9.0, 0.9.0.1, 0.9.1.0)
ERROR: No matching distribution found for mediapipe==0.10.0
```

**Comment by Hernandiaz035** [comment]
Same, I am giving up and switching to another architecture for this project.

I suggest you to do the same in the mean time.

**Comment by kuaashish** [comment]
@HuanjieGuo, 
Please confirm this you are using the Intel based or Silicon chip M1, M2 based macOS?

**Comment by HuanjieGuo** [comment]
@kuaashish  Intel based

**Comment by kuaashish** [comment]
@HuanjieGuo,



We have rolled out the newer version 0.10.1 as [noted](https://pypi.org/project/mediapipe/) here And able to build the MediaPipe 0.10.1 with Python 3.11.3 in the MacBook Pro 2(Intel) Ventura 13.4 as screenshot attached here. Please build using the newer version and let us know if you encounter the similar error.



<img width="889" alt="Screenshot 2023-06-06 at 2 45 49 PM" src="https://github.com/google/mediapipe/assets/98159216/035d762e-ffa0-4375-a939-f1805e2d0268">





Thank you!!

**Comment by HuanjieGuo** [comment]
<img width="641" alt="image" src="https://github.com/google/mediapipe/assets/26168718/61fa0134-8870-4067-aa3f-ca651b7d0abc">
<img width="631" alt="image" src="https://github.com/google/mediapipe/assets/26168718/e2727bf1-24e0-4f1b-87d5-9f163cf5e79f">
<img width="266" alt="image" src="https://github.com/google/mediapipe/assets/26168718/5b30fd54-186d-4801-9267-96b740ed979d">

Doesn't work for me.

**Comment by kuaashish** [comment]
@timherzig,

To keep context of the easier to filter out the issue with title. We suggest you to raise a fresh issue with problem facing in the Silicon macOS. As, This issue more specific to the macOS intel.

**Comment by kuaashish** [comment]
@HuanjieGuo,

Thanks for the update, We are forwarding issue internally and will let you know possible cause to build failure.

**Comment by Modjular** [comment]
I'm also facing the same issue on a 2015 Macbook Pro:
```
Hardware Overview:

  Model Name:                   MacBook Pro
  Model Identifier:             MacBookPro12,1
  Processor Name:               Intel Core i5
  Processor Speed:              2.9 GHz
  Number of Processors:         1
  Total Number of Cores:        2
  L2 Cache (per Core):          256 KB
  L3 Cache:                     3 MB
  Hyper-Threading Technology:   Enabled
  Memory:                       8 GB
  Boot ROM Version:             427.140.8.0.0
  SMC Version (system):         2.28f7
  Serial Number (system):       C02R5608FVH7
  Hardware UUID:                35B925BC-6062-5411-A2FE-3B72218BBE4A
```

When I try to install [using the official instructions](https://developers.google.com/mediapipe/solutions/setup_python#developer_environment_setup):
```
python3 -m pip install mediapipe
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

**Comment by meow-wwww** [comment]
Same problem...
I want to implement mediapipe hand and pose landmark detection on my MacBook Pro, but I'm only able to install mediapipe <=0.9, which doesn't contain PoseLandmarker...
Is there any way to install 0.10 on mac? I have tried so many times but still failing

**Comment by kuaashish** [comment]
Hello @schmidt-sebastian,

Do we have any update available on this issue? Thank you!

**Comment by timherzig** [comment]
I solved this issue using Miniforge3 with Python 3.10 instead of Anaconda.

**Comment by kuaashish** [comment]
@HuanjieGuo,

We have released newest version 0.10.3 as noted here in [release page](https://github.com/google/mediapipe/releases/tag/v0.10.3). Could you please build using the newest version and let us know if this is still an issue in the intel i5 macOS. Thank you

**Comment by hxlei0827** [comment]
@kuaashish 
Hi kuaashish, I am facing the same problems as HuanjieGuo. Intel i5 macos, python3.11.3, mediapipe==0.10.3 still does not work.

**Comment by kuaashish** [comment]
Furthermore, kindly rename the file to a format such as "mediapipe-0.10.7-cp311-cp311-macosx_10_16_x86_64.whl" before proceeding with manual installation. For guidance on the renaming process, you can refer to the provided [thread](https://stackoverflow.com/questions/38866758/filename-whl-is-not-a-supported-wheel-on-this-platform).

Thank you

**Comment by schmidt-sebastian** [comment]
Fixed internally. Release will come soon.

**Comment by yiusay** [comment]
Is MacOS 10.15 not supported anymore for Mediapipe 0.10.0? 

I followed the instruction (https://github.com/google/mediapipe/issues/4492#issuecomment-1772367735) but it did not work. My python version is 3.11.6 and I used mediapipe-0.10.7-cp311-cp311-macosx_11_0_universal2.whl.

**Comment by jimwinkpresage** [comment]
still having the same issue on intel mac; OS 14.1.1
