### ISSUE TITLE
 Demo example "Pose Landmark Detection" throws an error

### ISSUE THREAD

**Issue by xfish3** [google/mediapipe#4493]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android 11

### Mobile device if the issue happens on mobile device

Redmi Note 10S

### Browser and version if the issue happens on browser

Google Chrome 107.0.5304.141

### Programming Language and version

JavaScript

### Solution

Pose

### Describe the actual behavior

```shell
The "Pose Landmark Detection" demo gives the error "Uncaught (in promise): NotReadableError: Could not start video source. Reload page". No camera image
```

### Describe the expected behaviour

```shell
Camera images with body key points
```

### Standalone code/steps you may have used to try to get what you need

```shell
Opened a page with an example on the site https://mediapipe-studio.webapps.google.com/demo/pose_landmarker
```

**Comment by kuaashish** [comment]
Hello @xfish3,
Could you please upgrade the chrome version probably the latest Version 113.0.5672.162 and let us know if you encounter the similar error. Thank you!!
