### ISSUE TITLE
PyPI package not found on windows 11 and python 3.11

### ISSUE THREAD

**Issue by dkackman** [google/mediapipe#4494]
### OS Platform and Distribution

Windows 11 v22621.1778

### Programming Language and version

python 3.11.3

### Installed using virtualenv? pip? Conda?(if python)

yes. pip

### MediaPipe version

0.10.0

### Android AAR (if android)

None

### Describe the problem

```shell
When attempting to install the package with `pip install mediapipe` it fails to find the package on pipy.
```

### Complete Logs

```shell
pip install mediapipe
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```
```

**Comment by dkackman** [comment]
New issue reference from https://github.com/google/mediapipe/issues/4424

**Comment by kuaashish** [comment]
@dkackman,

In Windows Python 3.11 is not supported yet, We only support Python >=3.8 and <=3.10. Python 3.11 is only supported on MacOS and Linux as guided [here](https://developers.google.com/mediapipe/solutions/setup_python). Please upgrade to the supported Python version and revert back if you encounter the similar error. 

Thank you!!

**Comment by dkackman** [comment]
Do you an idea when python 3.11 will be supported on Windows 11?

**Comment by dkackman** [comment]
0.10.0 installs fine on windows 11 with python 3.10 - though still interested in 3.11 support in the interest of simplified dependency management.

**Comment by kuaashish** [comment]
@dkackman,

We have rolled out the newer version 0.10.1 as guided in the release page and Support of Python 3.11 in the Windows have been added. However, We are working to update the documentation of Python support. Please build using the Python 3.11 and let us know if you encounter any error.   Thank you!!

**Comment by kuaashish** [comment]
@dkackman,
Thanks for the update, Can we move ahead and close the issue as it has been resolved?
