### ISSUE TITLE
How to extract Blendshape scores from Mediapipe Face Landmark Detection in C++ envirment?

### ISSUE THREAD

**Issue by blueskyscorpio** [google/mediapipe#4498]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

**Comment by kuaashish** [comment]
@blueskyscorpio,

We still do not have an upgraded version available on the C++ platform, including all task APIs and the Face Landmarker API. However, please be assured that we have already incorporated a Face Landmarker API for C++ into our roadmap, with plans to include other APIs as well.

Corresponding documentation has been prepared for internal use. This documentation will become accessible once it is deemed complete from our end on this [page](https://developers.google.com/mediapipe/solutions/vision/face_landmarker), and instructions for extracting the Blendshape score in the C++ platform will be available on the same page, as [specified ](https://developers.google.com/mediapipe/solutions/vision/face_landmarker/web_js#handle_and_display_results)for the Face Landmarker in the Web platform. Unfortunately, we cannot provide a specific timeline for availability at this time. We appreciate your understanding. Thank you

**Comment by blueskyscorpio** [comment]
Thanks for your reply. I wish I can use c++ api soon.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 25, 2023 15:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [google/mediapipe] How to extract Blendshape scores fromMediapipe Face Landmark Detection in C++ envirment? (Issue #4498)




 
@blueskyscorpio,
 
We still do not have an upgraded version available on the C++ platform, including all task APIs and the Face Landmarker API. However, please be assured that we have already incorporated a Face Landmarker API for C++ into our roadmap, with plans to include other APIs as well.
 
Corresponding documentation has been prepared for internal use. This documentation will become accessible once it is deemed complete from our end on this page, and instructions for extracting the Blendshape score in the C++ platform will be available on the same page, as specified for the Face Landmarker in the Web platform. Unfortunately, we cannot provide a specific timeline for availability at this time. We appreciate your understanding. Thank you

**Comment by blueskyscorpio** [comment]
I confirm this issue solved, thanks!



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 25, 2023 20:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [google/mediapipe] How to extract Blendshape scores fromMediapipe Face Landmark Detection in C++ envirment? (Issue #4498)




 
@blueskyscorpio,
 
Thank you for your prompt response. We will keep you informed as soon as any updates regarding the enhanced solution become available. Additionally, if the issue is no longer persisting, we kindly request your confirmation to change the status of the issue to resolved and proceed with its closure.
