### ISSUE TITLE
Retraining for new gesture

### ISSUE THREAD

**Issue by qgh1223** [google/mediapipe#45]
Can I use this platform to train other gesture？

**Comment by mgyong** [comment]
The models we have just provides 21 landmarks on the hand. Pls read the Google AI blog post for [more info](https://mediapipe.page.link/handgoogleaiblog). It is not possible for you to train new gestures using the tflite file we have provided. What new gestures are you looking to train? @fanzhanggoogle FYI

**Comment by gabrielstuff** [comment]
hello @qgh1223, 
Could you share what you end up doing for gesture recognition ? As replied there: https://github.com/google/mediapipe/issues/40, I think that we could do some basic vptree and distance computation to find what hand pose match the other ones.
