### ISSUE TITLE
Bazel build graph failed 

### ISSUE THREAD

**Issue by artemsokol98** [google/mediapipe#4502]
### OS Platform and Distribution

macOS 12.6 

### Compiler version

Apple clang version 14.0.0 (clang-1400.0.29.202)

### Programming Language and version

Objective-C, Swift, Objective-C++

### MediaPipe version

0.10.0

### Bazel version

6.2.0

### XCode and Tulsi versions (if iOS)

14.2.0.14C18. I use rules_xcodeproj, because Tulsi deprecated

### Android AAR (if android)

None

### Describe the problem

```shell
When I try to build any example/ios (FaceMesh, FaceDetectionGpu and else), I faced with graph errors.
```

### Complete Logs

```shell
artemsokolovskiy@Artems-iMac mediapipe % bazel build mediapipe/examples/ios/facemeshgpu:FaceMeshGpuApp --verbose_failures --sandbox_debug
WARNING: /Users/artemsokolovskiy/Mediapipe2/mediapipe/mediapipe/framework/BUILD:56:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /Users/artemsokolovskiy/Mediapipe2/mediapipe/mediapipe/framework/tool/BUILD:197:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/ios/facemeshgpu:FaceMeshGpuApp (5 packages loaded, 49 targets configured).
INFO: Found 1 target...
ERROR: /Users/artemsokolovskiy/Mediapipe2/mediapipe/mediapipe/graphs/face_mesh/BUILD:64:23: Linking mediapipe/graphs/face_mesh/face_mesh_mobile_gpu_binary_graph_text_to_binary_graph [for tool] failed: (Exit 1): sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_artemsokolovskiy/91f460263cc1ebd6995dcedc71a2c8a7/sandbox/darwin-sandbox/1502/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=13.1 \
    DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin \
    SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk \
    TMPDIR=/var/folders/0z/d7nxqcn15qd2fy3_jgll448r0000gn/T/ \
    XCODE_VERSION_OVERRIDE=14.2.0.14C18 \
    ZERO_AR_DATE=1 \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_artemsokolovskiy/91f460263cc1ebd6995dcedc71a2c8a7/sandbox/darwin-sandbox/1502/sandbox.sb /var/tmp/_bazel_artemsokolovskiy/install/f822566ff435ccaad75bcfd3b2719b0b/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/private/var/tmp/_bazel_artemsokolovskiy/91f460263cc1ebd6995dcedc71a2c8a7/sandbox/darwin-sandbox/1502/stats.out' external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418-ST-0d1fe7b00ffe/bin/mediapipe/graphs/face_mesh/face_mesh_mobile_gpu_binary_graph_text_to_binary_graph-2.params)
stderr (/private/var/tmp/_bazel_artemsokolovskiy/91f460263cc1ebd6995dcedc71a2c8a7/execroot/mediapipe/bazel-out/_tmp/actions/stderr-44) 1953000 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
Target //mediapipe/examples/ios/facemeshgpu:FaceMeshGpuApp failed to build
INFO: Elapsed time: 2.329s, Critical Path: 2.13s
INFO: 38 processes: 25 internal, 12 darwin-sandbox, 1 local.
FAILED: Build did NOT complete successfully
```

**Comment by kuaashish** [comment]
Hello @artemsokol98,
Please confirm this you are using the Intel or silicon chip M1, M2 based macOS?

**Comment by artemsokol98** [comment]
Hello, @kuaashish I use Intel based macOS

**Comment by kuaashish** [comment]
@artemsokol98,

This issue is known to us and working towards the fix it. Please allow us sometime to share the update on this.

**Comment by ndrnrc** [comment]
same issue

**Comment by kuaashish** [comment]
Hi @artemsokol98,

Could you kindly confirm if you still require assistance with this matter? If so, we would like to inform you that our iOS app development using C++ are no longer under active maintenance, and it is unlikely that the reported issue will be resolved.

Instead, we suggest exploring our CocoaPods Version of Face Detection Task API for easier implementation in building your iOS application. This API is an improved version of our legacy Face Detection Solution. You can find more details [here](https://developers.google.com/mediapipe/solutions/guide#legacy).

Furthermore, please refer to the associated Overview [documentation](https://developers.google.com/mediapipe/solutions/vision/face_detector) and implementation instructions for iOS on this [page](https://developers.google.com/mediapipe/solutions/vision/face_detector/ios). Additionally, note that the CocoaPods version for building the iOS app for Face Landmaker is currently in development and will be made available soon, serving as an upgraded version of the legacy Face Mesh Solution.

Should you encounter any challenges during the implementation process, we kindly request you to report them to us promptly for further assistance.

Thank you!
