### ISSUE TITLE
Client-Side Caching for Web

### ISSUE THREAD

**Issue by soroushmadani** [google/mediapipe#4508]
Hi, thank you for your excellent work!

I am currently using the "Face landmark detection for Web" functionality from the `@mediapipe/tasks-vision` npm library with `Next.js`. Everything is functioning perfectly, but I've noticed that whenever my component is dismissed and reopened, it makes requests for the following files: `vision_wasm_internal.js`, `vision_wasm_internal.wasm`, and `face_landmarker.task`.

Is there a way to implement client-side caching, so that these files can be cached and reused the next time the component is opened?

**Comment by kuaashish** [comment]
@soroushmadani,

Could you please let us know if you are using a CDN, Which implements caching mechanism for browser or not?
