### ISSUE TITLE
Hand Detection (desktop) : Build did not complete successfully

### ISSUE THREAD

**Issue by BlueOuael** [google/mediapipe#451]
Hello, 
I have an issue while building the hand tracking example : https://github.com/google/mediapipe/tree/master/mediapipe/examples/desktop
I can build and run object and face detection examples but i am struggled with hand detection and tracking examples. 
Could you please help ?
Thanks.

OS: Ubuntu
gcc version : 5.4.0

Command : bazel build -c opt mediapipe/examples/desktop/hand_tracking:hand_tracking_tflite --define MEDIAPIPE_DISABLE_GPU=1

Build error : 
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_tflite (0 packages loaded, 747 targets configured).
INFO: Found 1 target...
INFO: From Compiling mediapipe/calculators/core/merge_calculator.cc:
In file included from ./mediapipe/framework/calculator_base.h:24:0,
                 from ./mediapipe/framework/calculator_framework.h:54,
                 from mediapipe/calculators/core/merge_calculator.cc:15:
./mediapipe/framework/calculator_registry.h:24:39: warning: 'mediapipe::calculator_registration_89__' defined but not used [-Wunused-variable]
                                       calculator_registration, name,       \
                                       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:23:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(::mediapipe::CalculatorBaseRegistry, \
   ^
mediapipe/calculators/core/merge_calculator.cc:89:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(MergeCalculator);
 ^
./mediapipe/framework/calculator_registry.h:28:7: warning: 'mediapipe::access_registration_89__' defined but not used [-Wunused-variable]
       access_registration, name,                                           \
       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:26:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(                                     \
   ^
mediapipe/calculators/core/merge_calculator.cc:89:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(MergeCalculator);
 ^
cc1plus: warning: unrecognized command line option '-Wno-ignored-attributes'
INFO: From Compiling mediapipe/calculators/core/gate_calculator.cc:
In file included from ./mediapipe/framework/calculator_base.h:24:0,
                 from ./mediapipe/framework/calculator_framework.h:54,
                 from mediapipe/calculators/core/gate_calculator.cc:16:
./mediapipe/framework/calculator_registry.h:24:39: warning: 'mediapipe::calculator_registration_161__' defined but not used [-Wunused-variable]
                                       calculator_registration, name,       \
                                       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:23:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(::mediapipe::CalculatorBaseRegistry, \
   ^
mediapipe/calculators/core/gate_calculator.cc:161:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(GateCalculator);
 ^
./mediapipe/framework/calculator_registry.h:28:7: warning: 'mediapipe::access_registration_161__' defined but not used [-Wunused-variable]
       access_registration, name,                                           \
       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:26:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(                                     \
   ^
mediapipe/calculators/core/gate_calculator.cc:161:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(GateCalculator);
 ^
cc1plus: warning: unrecognized command line option '-Wno-ignored-attributes'
INFO: From Compiling mediapipe/calculators/util/rect_to_render_data_calculator.cc:
In file included from ./mediapipe/framework/calculator_base.h:24:0,
                 from ./mediapipe/framework/calculator_framework.h:54,
                 from mediapipe/calculators/util/rect_to_render_data_calculator.cc:16:
./mediapipe/framework/calculator_registry.h:24:39: warning: 'mediapipe::calculator_registration_99__' defined but not used [-Wunused-variable]
                                       calculator_registration, name,       \
                                       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:23:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(::mediapipe::CalculatorBaseRegistry, \
   ^
mediapipe/calculators/util/rect_to_render_data_calculator.cc:99:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(RectToRenderDataCalculator);
 ^
./mediapipe/framework/calculator_registry.h:28:7: warning: 'mediapipe::access_registration_99__' defined but not used [-Wunused-variable]
       access_registration, name,                                           \
       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:26:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(                                     \
   ^
mediapipe/calculators/util/rect_to_render_data_calculator.cc:99:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(RectToRenderDataCalculator);
 ^
cc1plus: warning: unrecognized command line option '-Wno-ignored-attributes'
INFO: From Compiling mediapipe/calculators/util/detection_letterbox_removal_calculator.cc:
In file included from ./mediapipe/framework/calculator_base.h:24:0,
                 from ./mediapipe/framework/calculator_framework.h:54,
                 from mediapipe/calculators/util/detection_letterbox_removal_calculator.cc:32:
./mediapipe/framework/calculator_registry.h:24:39: warning: 'mediapipe::calculator_registration_152__' defined but not used [-Wunused-variable]
                                       calculator_registration, name,       \
                                       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:23:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(::mediapipe::CalculatorBaseRegistry, \
   ^
mediapipe/calculators/util/detection_letterbox_removal_calculator.cc:152:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(DetectionLetterboxRemovalCalculator);
 ^
./mediapipe/framework/calculator_registry.h:28:7: warning: 'mediapipe::access_registration_152__' defined but not used [-Wunused-variable]
       access_registration, name,                                           \
       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:26:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(                                     \
   ^
mediapipe/calculators/util/detection_letterbox_removal_calculator.cc:152:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(DetectionLetterboxRemovalCalculator);
 ^
cc1plus: warning: unrecognized command line option '-Wno-ignored-attributes'
**_ERROR: /home/idf/Ouael/mediapipe/mediapipe/calculators/image/BUILD:332:1: C++ compilation of rule '//mediapipe/calculators/image:image_cropping_calculator' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 72 argument(s) skipped)_**

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/image/image_cropping_calculator.cc: In member function 'mediapipe::Status mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*)':
mediapipe/calculators/image/image_cropping_calculator.cc:265:3: error: 'boxPoints' is not a member of 'cv'
   cv::boxPoints(min_rect, src_points);
   ^
In file included from ./mediapipe/framework/calculator_base.h:24:0,
                 from ./mediapipe/framework/calculator_framework.h:54,
                 from mediapipe/calculators/image/image_cropping_calculator.cc:18:
mediapipe/calculators/image/image_cropping_calculator.cc: At global scope:
./mediapipe/framework/calculator_registry.h:24:39: warning: 'mediapipe::calculator_registration_111__' defined but not used [-Wunused-variable]
                                       calculator_registration, name,       \
                                       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:23:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(::mediapipe::CalculatorBaseRegistry, \
   ^
mediapipe/calculators/image/image_cropping_calculator.cc:111:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(ImageCroppingCalculator);
 ^
./mediapipe/framework/calculator_registry.h:28:7: warning: 'mediapipe::access_registration_111__' defined but not used [-Wunused-variable]
       access_registration, name,                                           \
       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:26:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(                                     \
   ^
mediapipe/calculators/image/image_cropping_calculator.cc:111:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(ImageCroppingCalculator);
 ^
cc1plus: warning: unrecognized command line option '-Wno-ignored-attributes'
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_tflite failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 19.167s, Critical Path: 16.50s
INFO: 13 processes: 13 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by BlueOuael** [comment]
Hi all, 
I am still blocked with this issue. Could someone help please? 
Could it be a gcc version issue ?
Thanks !

**Comment by fenollp** [comment]
Sounds more like an OpenCV installation issue:
```
mediapipe/calculators/image/image_cropping_calculator.cc:265:3: error: 'boxPoints' is not a member of 'cv'
cv::boxPoints(min_rect, src_points);
```

**Comment by BlueOuael** [comment]
Thanks, I'll check it!

**Comment by eknight7** [comment]
@BlueOuael were you able to resolve this issue?

**Comment by BlueOuael** [comment]
Hello, 
The issue is resolved now. It wasn't related to OpenCV installation. This was fine. 
Actually, it was related to some ubuntu distribution. Some dependencies were missing. Reinstalling ubntu fixed the issue.
