### ISSUE TITLE
Pip install mediapipe==0.10.0 not working !!!

### ISSUE THREAD

**Issue by mustafahalimeh** [google/mediapipe#4512]
### OS Platform and Distribution

MacOS 11.7.6

### Programming Language and version

Python 3.8, 3.9, 3.10

### Installed using virtualenv? pip? Conda?(if python)

pip version 23

### MediaPipe version

0.10.0

### Android AAR (if android)

None

### Describe the problem

```shell
I try in upgrade my mediapipe python library to the latest version 0.10.0 using pip install mediapipe==0.10.0
```

### Complete Logs

```shell
ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.0 (from versions: 0.8.3.1, 0.8.4.2, 0.8.5, 0.8.6.2, 0.8.7.1, 0.8.7.2, 0.8.7.3, 0.8.8, 0.8.8.1, 0.8.9, 0.8.9.1, 0.8.10, 0.8.10.1, 0.8.11, 0.9.0, 0.9.0.1, 0.9.1.0) ERROR: No matching distribution found for mediapipe==0.10.0
```

**Comment by kuaashish** [comment]
Hello @mustafahalimeh,

Please upgraded to macOS version probably 13.3.1 or the newer one. Also make sure build using the python supported version between 3.8 to 3.11 as only supports on macOS and Linux as [guided](https://developers.google.com/mediapipe/solutions/setup_python). Please try out the instructions mentioned here and let us know if you encounter the similar error.  Thank you!!

**Comment by timherzig** [comment]
Hi, I'm having the same problem. Mediapipe does not find a newer version than 0.9.1.0 when installing through pip. I'm running on MacOS 13.4, using a Conda envinronment with Python 3.9 installed and Pip version 23. I followed the linked instructions as well. Thanks for any help!

**Comment by kuaashish** [comment]
@mustafahalimeh,
Thanks for the update. Closing this issue as it has been resolved.

**Comment by hxlei0827** [comment]
> Hi, I'm having the same problem. Mediapipe does not find a newer version than 0.9.1.0 when installing through pip. I'm running on MacOS 13.4, using a Conda envinronment with Python 3.9 installed and Pip version 23. I followed the linked instructions as well. Thanks for any help!

same

**Comment by mustafahalimeh** [comment]
You need to update your Mac OS to the latest version.

**Comment by AnyLifeZLB** [comment]
> > Hi, I'm having the same problem. Mediapipe does not find a newer version than 0.9.1.0 when installing through pip. I'm running on MacOS 13.4, using a Conda envinronment with Python 3.9 installed and Pip version 23. I followed the linked instructions as well. Thanks for any help!
> 
> do you have any updates for solving this? btw the way, I also use the import distutils import os print(distutils.util.get_platform()) to check the macos version, i don't know why it still shows macox_10.9-x86-64.

I've solved it. https://github.com/AnyLifeZLB/FaceVerificationSDK/blob/main/install_newest_mediapipe_on_macos.md

SYSTEM_VERSION_COMPAT ERROR ！！ @hxlei0827

**Comment by roboticsware** [comment]
Same here. My macos version is 10.15 with intel 64bits and tried to install it in all python 3.8 ~ 3.12, but I can never install mediapipe 0.10.0, even PyPI repo has 
mediapipe-0.10.0-cp38-cp38-macosx_12_0_universal2.whl.
