### ISSUE TITLE
"Build Service could not create build operation: Unknown error" compile on Xcode 14.3

### ISSUE THREAD

**Issue by scofielddd** [google/mediapipe#4514]
### OS Platform and Distribution

Mac os Ventura 13.0.01

### Compiler version

Xcode 14.3

### Programming Language and version

c

### Bazel version

6.1.1

### XCode and Tulsi versions (if iOS)

Xcode 14.3

### Android AAR (if android)

None

### Describe the problem

```shell
(base) scofield@ScofielddeMacBook-Pro mediapipe % python3 mediapipe/examples/ios/link_local_profiles.py
Looking for profiles for app ids with prefix 'e5d6756d-c4cb-4a1c-ae59-57b9a6625eb2.mediapipe.examples' in '/Users/scofield/Library/MobileDevice/Provisioning Profiles'
(base) scofield@ScofielddeMacBook-Pro mediapipe %
```

### Complete Logs

```shell
after following the MediaPipe Framework on IOS tutorial, I completed the final step of automatic provision "python3 mediapipe/examples/ios/link_local_profiles.py". Then, I reopen the Xcode and change the "Signing & Capability" of HandTracking GPU to "automatical manage singing", and team to personal team. When I want to Compile the code, after that, it gives me the error that 

Build service could not create build operation: unknown error while handling message: fopen(/Users/<my_name>/Desktop/mediapipe/mediapipe/Build/Intermediates.noindex/XCBuildData/PIFCache/WORKSPACE@v11_hash=(null)_subobjects=10d414fd93735f09e4ab6b5de5ce754a-workspace.lock, wb): Not a directory (20)
```

**Comment by scofielddd** [comment]
"Build service could not create build operation: unknown error while handling message: fopen(/Users/scofield/Desktop/labproject/mediapipe/mediapipe/Build/Intermediates.noindex/XCBuildData/PIFCache/WORKSPACE@v11_hash=(null)_subobjects=10d414fd93735f09e4ab6b5de5ce754a-workspace.lock, wb): Not a directory (20)"
This is the specific error message

**Comment by scofielddd** [comment]
Is there anybody can help me? please

**Comment by kuaashish** [comment]
@scofielddd,

There is a known issue in Xcode 14.3 on which team is working actively. Would you please try with Xcode 14.2 and MediaPipe 0.10.0 as workaround? And let us know if you encounter the similar error. Thank you!!

**Comment by scofielddd** [comment]
However, when I want to run the handtracking program, it show me the error that  "Creating symlink bazel-out/applebin_ios-ios_arm64-opt-ST-2967bd56a867/bin/mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp-intermediates/embedded.mobileprovision failed: 1 input file(s) do not exist"

Creating symlink bazel-out/applebin_ios-ios_arm64-opt-ST-2967bd56a867/bin/mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp-intermediates/embedded.mobileprovision failed: missing input file '//mediapipe:provisioning_profile.mobileprovision'

Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.

Why is about that?

**Comment by kuaashish** [comment]
@scofielddd,

Have you followed the instructions to [set up or create the provisioning](https://developers.google.com/mediapipe/framework/getting_started/ios#set_up_provisioning) profile from the documentation?

**Comment by scofielddd** [comment]
Yes, I solve that issue, but when I run the program, I have another new issue here: error loading package 'third_party': Label '@rules_foreign_cc//tools/build_defs:cmake.bzl' is invalid because 'tools/build_defs' is not a package; perhaps you meant to put the colon here: '@rules_foreign_cc//:tools/build_defs/cmake.bzl'? and referenced by
<img width="1078" alt="截屏2023-06-08 13 20 43" src="https://github.com/google/mediapipe/assets/99227153/f28a28ff-d621-4a1c-b614-44ca3eaa0e9a">
 '//mediapipe/framework/port:logging'

**Comment by kuaashish** [comment]
@scofielddd,

To keep context of the easier to filter out the issue with title. We are following up with another issue raised #4528 and closing this issue as resolved.

**Comment by scofielddd** [comment]
okay
