### ISSUE TITLE
How to get presence and visibility parameters ?

### ISSUE THREAD

**Issue by bhaskar2728** [google/mediapipe#4516]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Android 10

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose Landmark

### Programming Language and version (e.g. C++, Python, Java)

Android

### Describe the actual behavior

```shell
In this documentation https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/android ,
It is given that the result will be this:
PoseLandmarkerResult:
Landmarks:
Landmark #0:
x : 0.638852
y : 0.671197
z : 0.129959
visibility : 0.9999997615814209
presence : 0.9999984502792358
```

### Describe the expected behaviour

```shell
But in the implementation, I am only getting x, y and z values but not visibility and presence.
```

### Standalone code/steps you may have used to try to get what you need

```shell
I have used the exact same code as provided in this sample:
https://github.com/googlesamples/mediapipe/tree/main/examples/pose_landmarker/android
```

**Comment by kuaashish** [comment]
@bhaskar2728,

Sorry for the delayed response,

Could you please confirm that Are you still looking for the resolution or the issue has been resolved from your end?

Thank you!1

**Comment by bhaskar2728** [comment]
The issue has been resolved in the googlesamples/mediapipe github discussion . This is the link: https://github.com/googlesamples/mediapipe/issues/158
