### ISSUE TITLE
In face_mesh_connections.py, provide tuple of sequential list of indices for FACEMESH_FACE_OVAL and other polygonal shapes

### ISSUE THREAD

**Issue by by321** [google/mediapipe#4518]
### MediaPipe Solution (you are using)

face landmarker

### Programming language

Python

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

```shell
Using FACEMESH_FACE_OVAL as an example, currently it is a frozenset of line segments, with each item being (start_point_index, end_point_index). If I want to draw outline of the "face oval", it's not too bad, I just draw all the line segments. But if I want to draw it as a filled polygon, or get a sequential list of polygon vertices, it's not so simple any more.

Because frozenset does not keep insertion order, if I just enumerate it, most likely I'll get a self-intersecting polygon. I see two workarounds:

1. copy the definition of FACEMESH_FACE_OVAL into my code, change frozenset to tuple. But if FACEMESH_FACE_OVAL changes in a future release, my code will stop working.
2. build a sequential list myself. This means enumerate FACEMESH_FACE_OVAL, put items into a dictionary, using first index as key, second index as value. Then construct a list.

What you really want is an ordered frozenset (ordered, unique, immutable), but no such data structure exists in Python (I'll ignore other languages now). The next best thing is to use a tuple. Tuple doesn't guarantee uniqueness, but you can manually ensure it's unique when you define it.

Frozenset is unordered, but with indices of polygon vertices, you want the data to be ordered.
```

### Will this change the current API? How?

```shell
No
```

### Who will benefit with this feature?

People who want facial shapes as a polygon.

### Please specify the use cases for this feature

```shell
Get polygons of facial shapes.
```

**Comment by kuaashish** [comment]
@by321,

Thanks for raising this feature request, We are forwarding issue internally and based on discussion team will prioritise the work.

**Comment by lu-wang-g** [comment]
In the new MediaPipe Tasks library, we've changed to storing the indices using `List`. See [FACE_LANDMARKS_LIPS](https://github.com/google/mediapipe/blob/ac4f60a79385a78ef5af2b8505ee653862bd1c8c/mediapipe/tasks/python/vision/face_landmarker.py#L133) for example. Let me know if it works for your now.

**Comment by by321** [comment]
Yeah, that's more convenient to use than frozenset, thanks.

**Comment by shrutic12** [comment]
Hi! I am using the face landmarker. For a given landmark X on the face mesh, I want to be able to access landmarks on the mesh that share an edge (connection) with this landmark X, or in other words the nearest neighbouring landmarks above, below and adjacent. Is there a way to access the face mesh connections so that I can do this?

**Comment by by321** [comment]
> I want to be able to access landmarks on the mesh that share an edge (connection) with this landmark X

Don't think there's an API for this, but you can build a dictionary using FACE_LANDMARKS_TESSELATION in mediapipe/mediapipe/tasks/python/vision/face_landmarker.py. The key is the landmark index, the value is a list of of indices it connects to.
