### ISSUE TITLE
Is there a way to retrain the holistic model with new labeled data?

### ISSUE THREAD

**Issue by f-conaflores** [google/mediapipe#4519]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python Version

3.9

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose and Hand Landmarks detection

### Describe the actual behavior

```shell
Can Model Maker be used to retrain holistic solution (pose and hand landmarks detection)? If not then... can I have access to the architecture and weights of the model to retrain it with custom code?

Thanks in advance
```

### Describe the expected behaviour

```shell
--
```

### Standalone code/steps you may have used to try to get what you need

```shell
--
```

**Comment by kuaashish** [comment]
Hello @f-conaflores,

We do not have any plan to include customize model for holistic solution, And we believe that is not possible. Only for now, Object Detection, Image Classification, Gesture Recognition And Text Classification models are customizable. Thank you!!
