### ISSUE TITLE
Does MediaPipe currently support batch processing for TFLite?

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#452]
I think we just need to modify TFLiteConverter and TFLiteInference calculators by a bit, i.e. add the batch size to both of them and we would be able to support both single image (batch size = 1) and batch (batch size = n) processing. Any reason to not do that?

**Comment by fanzhanggoogle** [comment]
That's definitely doable. But batch processing currently is hardly/poorly supported on mobile GPUs. So I don't recommend doing that if you are targeting for mobile. But on CPU it should be fine.
Another thing to keep in mind that you'll also need to support other preprocessing calculators to batch inputs. Or you can easily create a new calculator that does batch preprocessing for your case.

**Comment by yxchng** [comment]
@fanzhanggoogle Just curious. How bad is the support on mobile GPUs? Currently my image size is only 48x48. And the batch is about 100. Is it also bad for this situation when the image size is so small, i.e. looping 100 times is faster than doing batch?

**Comment by fanzhanggoogle** [comment]
@impjdi Could you shed light on batch processing support on mobile GPUs? Thank you! 
@impjdi is the lead on TFLite GPU backend.

**Comment by yxchng** [comment]
By the way, even it is really the case that batch processing is slow on mobile, I don't see any reason why changing this  `{height, width, channels_preserved}` to {n, height, width, channels_preserved}` in this line and some other related lines can be of any harm:

https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_converter_calculator.cc#L314

I will make the calculator much more flexible without any overhead.

**Comment by impjdi** [comment]
Before calling `Interpreter::ModifyGraphWithDelegate`, try calling `Interpreter::ResizeInputTensor`.  IIRC batch support is half-way done.

**Comment by yxchng** [comment]
@impjdi Yup. I know how to modify it to support batch processing. I am just curious why don't just make the calculator flexible by making the calculator support batch processing by default when batch processing also makes single image processing possible, so there is no conflict with existing codebase. Any good rationale for not doing that?

**Comment by impjdi** [comment]
No, not really.  We didn't consider batch dimension to be a crucial part of real-time use cases.  It was just never asked by anyone (internally, I may add) and thus never prioritized.
