### ISSUE TITLE
After calling mediapipe.solutions,  can no longer correctly call mediapipe.tasks.vision.

### ISSUE THREAD

**Issue by zeusftk** [google/mediapipe#4520]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Macos or window

### Programming Language and version

python 3.10.8

### Solution

all modules，such as facelandmark，pose

### Describe the actual behavior

```shell
import mediapipe 
import gc
###first load 《mediapipe.solutions.pose.Pose》 module
pos=mediapipe.solutions.pose.Pose(
            static_image_mode=True,
            model_complexity=1,
            enable_segmentation=False,
            min_detection_confidence=0.5)
del pos
del mediapipe
gc.collect()

###then load 《mediapipe.tasks.vision》 module
import mediapipe 
model_path="D:/project/webui/extensions/aftk/extratool/keypose/pose_landmarker_heavy.task"
mediapipe.tasks.vision.PoseLandmarker.create_from_model_path(model_path)
```

### Describe the expected behaviour

```shell
import mediapipe 
import gc
###first load 《mediapipe.solutions.pose.Pose》 module
pos=mediapipe.solutions.pose.Pose(
            static_image_mode=True,
            model_complexity=1,
            enable_segmentation=False,
            min_detection_confidence=0.5)
del pos
del mediapipe
gc.collect()

###then load 《mediapipe.tasks.vision》 module
import mediapipe 
model_path="D:/project/webui/extensions/aftk/extratool/keypose/pose_landmarker_heavy.task"
mediapipe.tasks.vision.PoseLandmarker.create_from_model_path(model_path)
```

### Standalone code/steps you may have used to try to get what you need

```shell
import mediapipe 
import gc
poes=mediapipe.solutions.pose.Pose(
            static_image_mode=True,
            model_complexity=1,
            enable_segmentation=False,
            min_detection_confidence=0.5)
del poes
del mediapipe
gc.collect()

import mediapipe 
model_path="D:/project/webui/extensions/aftk/extratool/keypose/pose_landmarker_heavy.task"
mediapipe.tasks.vision.PoseLandmarker.create_from_model_path(model_path)

发生异常: RuntimeError
Unable to open file at D:\ProgramData\Miniconda3\envs\webui\lib\site-packages/D:\project\webui\extensions\aftk\extratool\keypose\pose_landmarker_heavy.task, errno=22
  File "D:\project\webui\extensions\test\mm.py", line 66, in <module>
    vision.PoseLandmarker.create_from_model_path(model_path)
RuntimeError: Unable to open file at D:\ProgramData\Miniconda3\envs\webui\lib\site-packages/D:\project\webui\extensions\aftk\extratool\keypose\pose_landmarker_heavy.task, errno=22
```

### Other info / Complete Logs

```shell
the task file path changed by base_vision_task_api.py ,unexpected prefix which is “D:\ProgramData\Miniconda3\envs\webui\lib\site-packages/” was added。
```

**Comment by kuaashish** [comment]
@zeusftk,

Would you please let us know the steps you are following from [documentation](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/index#models)? We are not able to find out the exact code example following from the guide.

**Comment by kuaashish** [comment]
@zeusftk,

Could you please share the complete code probably in the colab attachment or any comfortable format?

**Comment by zeusftk** [comment]
`import mediapipe 
import gc
poes=mediapipe.solutions.pose.Pose(
            static_image_mode=True,
            model_complexity=1,
            enable_segmentation=False,
            min_detection_confidence=0.5)
del poes
del mediapipe
gc.collect()

import mediapipe 
model_path="D:/project/webui/extensions/aftk/extratool/keypose/pose_landmarker_heavy.task"
mediapipe.tasks.vision.PoseLandmarker.create_from_model_path(model_path)`


this is all code

**Comment by zeusftk** [comment]
import numpy as np
# import cv2
# import mediapipe as mp
# from mediapipe.tasks import python
# from mediapipe.tasks.python import vision
# import os

# img = cv2.imread('C:/Users/Administrator/Desktop/1-1/0/1.png')

# posetask="D:/project/webui/extensions/aftk/extratool/keypose/pose_landmarker_heavy.task"
# print(os.path.exists(posetask))
# base_options = python.BaseOptions(model_asset_path=posetask)
# options = vision.PoseLandmarkerOptions(
#         base_options=base_options,
#         output_segmentation_masks=True)
# dd=vision.PoseLandmarker
# print(dd.__dict__)
# detector = vision.PoseLandmarker.create_from_options(options)
# image = mp.Image(image_format=mp.ImageFormat.SRGB, data=np.copy(img))
# detection_result = detector.detect(image)
# print(options)

# mp_drawing = mp.solutions.drawing_utils
# mp_drawing_styles = mp.solutions.drawing_styles
# mp_hands = mp.solutions.hands

# imageBGR = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# mp_pose = mp.solutions.pose
# pose=mp_pose.Pose(
#             static_image_mode=True,
#             model_complexity=2,
#             enable_segmentation=False,
#             min_detection_confidence=0.5)
# print("----111",pose.__dict__)
# # with mp_hands.Hands(
# #         static_image_mode=True,
# #         model_complexity=1,
# #         max_num_hands=8,
# #         min_detection_confidence=0.5) as hands:
#     # resultsPose = hands.process(imageBGR)
# resultsPose = pose.process(imageBGR)
    

# base_options = python.BaseOptions(model_asset_path=posetask)
# options = vision.PoseLandmarkerOptions(
#         base_options=base_options,
#         output_segmentation_masks=True)
# dd=vision.PoseLandmarker
# detector = vision.PoseLandmarker.create_from_model_path(posetask)
# image = mp.Image(image_format=mp.ImageFormat.SRGB, data=np.copy(img))
# detection_result = detector.detect(image)


this is another example

**Comment by zeusftk** [comment]
another example

import numpy as np
import cv2
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import os

img = cv2.imread('C:/Users/Administrator/Desktop/1-1/0/1.png')

posetask="D:/project/webui/extensions/aftk/extratool/keypose/pose_landmarker_heavy.task"


mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

imageBGR = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
mp_pose = mp.solutions.pose
pose=mp_pose.Pose(
            static_image_mode=True,
            model_complexity=2,
            enable_segmentation=False,
            min_detection_confidence=0.5)
resultsPose = pose.process(imageBGR)
    

base_options = python.BaseOptions(model_asset_path=posetask)
options = vision.PoseLandmarkerOptions(
        base_options=base_options,
        output_segmentation_masks=True)
dd=vision.PoseLandmarker
detector = vision.PoseLandmarker.create_from_model_path(posetask)
image = mp.Image(image_format=mp.ImageFormat.SRGB, data=np.copy(img))
detection_result = detector.detect(image)

**Comment by zeusftk** [comment]
@kuaashish 
Is there a way to solve it，The code is already  above

**Comment by kuaashish** [comment]
@zeusftk,

Sorry for the delayed response,

Could you please confirm that Are you still looking for the resolution or the issue has been resolved from your end?

Thank you!
