### ISSUE TITLE
Object detection guide for Python       category_allow_list   

### ISSUE THREAD

**Issue by helloSoil** [google/mediapipe#4522]
options = ObjectDetectorOptions(
    base_options=BaseOptions(model_asset_path='efficientdet_lite2.tflite'),
    max_results=1,

    category_deny_list=['person','dog'],
    score_threshold=0.3,
    running_mode=VisionRunningMode.VIDEO)

TypeError: __init__() got an unexpected keyword argument 'category_deny_list'

List of errors

**Comment by kuaashish** [comment]
@helloSoil,

We are not able to reproduce the issue from our end. Please let us know the complete step you have followed from the [documentation](https://developers.google.com/mediapipe/solutions). Also, We recommend to fill the[ issue template](https://github.com/google/mediapipe/issues/new/choose) to get more context about the issue.

**Comment by amitkumarkashyap** [comment]
Its been wrongly documented. correct config is "category_allowlist=['person']"

**Comment by geogan** [comment]
Google spelt the parameter wrong in the documentation! It should be "category_denylist" not like "category_deny_list" in their documentation. Clowns!
