### ISSUE TITLE
Mediapipe Pose livestream segmentation causes Python to quit silently

### ISSUE THREAD

**Issue by ccarmatic** [google/mediapipe#4532]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 11

### MediaPipe Tasks SDK version

mediapipe version 0.10.0

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose

### Programming Language and version (e.g. C++, Python, Java)

python

### Describe the actual behavior

```shell
Mediapipe causes Python interpreter to quit without any error messages , upon trying to call .numpy_view() on the results segmentation mask
```

### Describe the expected behaviour

```shell
(SOLVED)Mediapipe should continue running and constantly output new segmentation masks(SOLVED)
ACTUAL ISSUES:
PoseLandmarkerResult should not return None
the callback function should not surpress error messages
```

### Standalone code/steps you may have used to try to get what you need

```shell
#already posted here: https://github.com/googlesamples/mediapipe/issues/161

import cv2
import mediapipe as mp
import numpy as np

def print_result(result: PoseLandmarkerResult, output_image: mp.Image, timestamp_ms: int):

    # this is the problem line
    alpha= result.segmentation_masks[0].numpy_view()
   

options = PoseLandmarkerOptions(
    base_options=BaseOptions(model_asset_path='pose_landmarker_full.task'),
    running_mode=VisionRunningMode.LIVE_STREAM,
    output_segmentation_masks=True,
    result_callback=print_result)

with PoseLandmarker.create_from_options(options) as pose:
    cap = cv2.VideoCapture(0)
    i = 0
    while (1):
        succes, image = cap.read()
        image = np.array(image)
        imgRGB = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=imgRGB)
        pose.detect_async(mp_image,i)
        i += 1
```

### Other info / Complete Logs

replacing `alpha= result.segmentation_masks[0].numpy_view()` with `alpha= result.segmentation_masks` will cause Mediapipe to continue running, and `alpha` is of type `mediapipe.python._framework_bindings.image.Image object`

**Comment by ccarmatic** [comment]
SOLVED
the issue is caused by PoseLandMarkerResult returning 'none' in the first few frames, thus the [0] and the .numpy_view() are not valid commands

```
def print_result(result: PoseLandmarkerResult, output_image: mp.Image, timestamp_ms: int):
    if result.segmentation_masks is not None:
       alpha= result.segmentation_masks[0].numpy_view()
```

**Comment by kuaashish** [comment]
@ccarmatic,

Thanks for the confirmation. Closing this issue as it has been resolved.
