### ISSUE TITLE
How do I modify the example below to display Streaming Video?

### ISSUE THREAD

**Issue by mcdonasd1212** [google/mediapipe#4533]
Has anyone created a version of the example below using streaming video?

https://github.com/googlesamples/mediapipe/tree/main/examples/pose_landmarker/python

**Comment by kuaashish** [comment]
@mcdonasd1212,

Please refer to below implementation of gesture recognition and modify according for pose landmarker.


```
import mediapipe as mp
import cv2

BaseOptions = mp.tasks.BaseOptions
GestureRecognizer = mp.tasks.vision.GestureRecognizer
GestureRecognizerOptions = mp.tasks.vision.GestureRecognizerOptions
GestureRecognizerResult = mp.tasks.vision.GestureRecognizerResult
VisionRunningMode = mp.tasks.vision.RunningMode

video = cv2.VideoCapture(0)

# Create a image segmenter instance with the live stream mode:
def print_result(result: GestureRecognizerResult, output_image: mp.Image, timestamp_ms: int):
    # cv2.imshow('Show', output_image.numpy_view())
    # imright = output_image.numpy_view()
    print(result.gestures)
    # cv2.imwrite('somefile.jpg', imright)


options = GestureRecognizerOptions(
    base_options=BaseOptions(model_asset_path='gesture_recognizer.task'),
    running_mode=VisionRunningMode.LIVE_STREAM,
    result_callback=print_result)


timestamp = 0
with GestureRecognizer.create_from_options(options) as recognizer:
  # The recognizer is initialized. Use it here.
    while video.isOpened(): 
        # Capture frame-by-frame
        ret, frame = video.read()

        if not ret:
            print("Ignoring empty frame")
            break

        timestamp += 1
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=frame)
        # Send live image data to perform gesture recognition
        # The results are accessible via the `result_callback` provided in
        # the `GestureRecognizerOptions` object.
        # The gesture recognizer must be created with the live stream mode.
        recognizer.recognize_async(mp_image, timestamp)

        if cv2.waitKey(5) & 0xFF == 27:
            break

video.release()
cv2.destroyAllWindows(
```

Reference : [How to implement gesture_recognizer.task for Live stream](https://github.com/google/mediapipe/issues/4448)

**Comment by mcdonasd1212** [comment]
This helps a lot!  One more thing, do you have an example of a function that returns the x,y,z coordinates for each Landmark?

**Comment by kuaashish** [comment]
Hello @mcdonasd1212,

This information is available in the documentation [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python#handle_and_display_results) as noted below: 

> The Pose Landmarker returns a poseLandmarkerResult object for each detection run. The result object contains coordinates for each pose landmark.
> 
> The following shows an example of the output data from this task:
> 
> 
> PoseLandmarkerResult:
>   Landmarks:
>     Landmark #0:
>       x            : 0.638852
>       y            : 0.671197
>       z            : 0.129959
>       visibility   : 0.9999997615814209
>       presence     : 0.9999984502792358
>     Landmark #1:
>       x            : 0.634599
>       y            : 0.536441
>       z            : -0.06984
>       visibility   : 0.999909
>       presence     : 0.999958
>     ... (33 landmarks per pose)

However, waitKey(5) is random value. You can give different value as per your requirements.

**Comment by matanox** [comment]
Is using an incrementing integer really a good practice for supplying the timestamps to this class?
