### ISSUE TITLE
NPM mediapipe library usage not clear in documentation, total built size huge

### ISSUE THREAD

**Issue by Perezmarc** [google/mediapipe#4537]
### Description of issue (what needs changing)

It's awesome we have an npm package, but using the package distributed by npm is not straight forward, since the same npm readme docs say to download wasm files from cdn.

### Clear description

The final built package size of mediapipe/tasks-vision from npm is 860kB because of wasm, but the documentation recommends importing from a cdn, but we still need the types from the package. The end result becomes of having the wasm file in the bundle size but downloading them from the CDN.

**Comment by kuaashish** [comment]
Hello @schmidt-sebastian,
Could you please help out here. Thank you!

**Comment by schmidt-sebastian** [comment]
Our JS library consists of a couple of files. The 3 important ones are:

- The Library JS file (e.g. vision_bundle.js)
- The Wasm Loader script (e.g. vision_wasm_internal.js)
- The Wasm code (e.g. vision_wasm_internal.wasm)

Only the library file needs to be included in your script. While the file size is over 800 kB, the code is modular and your should be able to tree-shake the build fairly substantially. On our end, we can minify the sources, which should reduce the size further, but that requires a new release.

**Comment by schmidt-sebastian** [comment]
Making this a feature request.

**Comment by Perezmarc** [comment]
It would be awesome though to have a documentation on npm on how to use all 3 (js, loader & wasm) from npm, without using external cdn.
Inlcuding wasm files and not specifically describing how to properly use the library it's a bit weird.
Did I miss something?

Thanks again for your work, keep it up!

**Comment by vettorazi** [comment]
Hi @schmidt-sebastian I might have the same question as Perez here.
I'm building an application that will live locally, on a PC without connection to the internet. Where can i download the WASM file that I'm loading in the visionTasks? ("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.0/wasm")

thanks in advance

**Comment by vettorazi** [comment]
Thanks @schmidt-sebastian found it :)

**Comment by kuaashish** [comment]
@vettorazi,

Could you please let us know if we can change the status to close if now no longer issue from your end. Thank you

**Comment by schmidt-sebastian** [comment]
We still need to address the build size issue (hence it is marked as a feature request)

**Comment by schmidt-sebastian** [comment]
This will be fixed in our next release, which should go out this week. The vision library is 160 kB with this build.
