### ISSUE TITLE
Error during Statically linking com.google.devtools.build.android.aapt2.CompiledResources@27912e3

### ISSUE THREAD

**Issue by helloWorldNG** [google/mediapipe#4540]
### OS Platform and Distribution

ubuntu18.0.4

### Compiler version

gcc/g++

### Programming Language and version

ignore

### Bazel version

5.2.0

### Android SDK and NDK versions (if android)

android_sdk_repository(name = "androidsdk",                        build_tools_version = "30.0.3",                        path = "/home/zjm/Android/Sdk") android_ndk_repository(name = "androidndk",                        api_level=21,                        path = '/home/zjm/Android/Sdk/ndk/21.4.7075529')

### Android AAR (if android)

None

### Describe the problem

```shell
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld --verbose_failures --sandbox_debug mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld
```

### Complete Logs

```shell
ERROR: /home/zjm/.cache/bazel/_bazel_zjm/6d3a6312a4e350e29f55a3ebdc686523/external/maven/BUILD:530:11: Linking static android resource library for @maven//:androidx_media_media failed: (Exit 1): linux-sandbox failed: error executing command 
  (cd /home/zjm/.cache/bazel/_bazel_zjm/6d3a6312a4e350e29f55a3ebdc686523/sandbox/linux-sandbox/2000/execroot/mediapipe && \
  exec env - \
    PATH=/home/zjm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    TMPDIR=/tmp \
  /home/zjm/.cache/bazel/_bazel_zjm/install/41b71f1bb3ce13f20cfeeb31a9357113/linux-sandbox -t 15 -w /home/zjm/.cache/bazel/_bazel_zjm/6d3a6312a4e350e29f55a3ebdc686523/sandbox/linux-sandbox/2000/execroot/mediapipe -w /tmp -w /dev/shm -D -- bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool LINK_STATIC_LIBRARY -- --aapt2 bazel-out/k8-opt-exec-50AE0418/bin/external/androidsdk/aapt2_binary --libraries external/androidsdk/platforms/android-34/android.jar --compiled bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media_symbols/symbols.zip --manifest bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media_processed_manifest/AndroidManifest.xml --compiledDep bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_core_core_symbols/symbols.zip:bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_lifecycle_lifecycle_runtime_symbols/symbols.zip:bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_arch_core_core_runtime_symbols/symbols.zip:bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_versionedparcelable_versionedparcelable_symbols/symbols.zip --sourceJarOut bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media.srcjar --rTxtOut bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media_symbols/R.txt --staticLibraryOut bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media_files/library.ap_)
1686730722.821869779: src/main/tools/linux-sandbox.cc:152: calling pipe(2)...
1686730722.821928551: src/main/tools/linux-sandbox.cc:171: calling clone(2)...
1686730722.822311852: src/main/tools/linux-sandbox.cc:180: linux-sandbox-pid1 has PID 4327
1686730722.829107927: src/main/tools/linux-sandbox-pid1.cc:641: Pid1Main started
1686730722.829236136: src/main/tools/linux-sandbox.cc:197: done manipulating pipes
1686730722.829504274: src/main/tools/linux-sandbox-pid1.cc:260: working dir: /home/zjm/.cache/bazel/_bazel_zjm/6d3a6312a4e350e29f55a3ebdc686523/sandbox/linux-sandbox/2000/execroot/mediapipe
1686730722.829539224: src/main/tools/linux-sandbox-pid1.cc:292: writable: /home/zjm/.cache/bazel/_bazel_zjm/6d3a6312a4e350e29f55a3ebdc686523/sandbox/linux-sandbox/2000/execroot/mediapipe
1686730722.829549059: src/main/tools/linux-sandbox-pid1.cc:292: writable: /tmp
1686730722.829559233: src/main/tools/linux-sandbox-pid1.cc:292: writable: /dev/shm
1686730722.829666835: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /
1686730722.829688445: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev
1686730722.829697253: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/pts
1686730722.829704420: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /dev/shm
1686730722.829709888: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/hugepages
1686730722.829715769: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /dev/mqueue
1686730722.829722140: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run
1686730722.829728689: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/lock
1686730722.829735482: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/vmblock-fuse
1686730722.829742187: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/121
1686730722.829749565: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/1000
1686730722.829756172: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/1000/gvfs
1686730722.829763142: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /run/user/1000/doc
1686730722.829796066: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys
1686730722.829802439: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/security
1686730722.829811391: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup
1686730722.829818004: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/unified
1686730722.829825059: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/systemd
1686730722.829831663: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/cpu,cpuacct
1686730722.829838114: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/devices
1686730722.829844811: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/net_cls,net_prio
1686730722.829851300: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/freezer
1686730722.829857556: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/pids
1686730722.829864003: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/memory
1686730722.829870633: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/perf_event
1686730722.829876864: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/blkio
1686730722.829906633: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/rdma
1686730722.829913495: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/cpuset
1686730722.829919748: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/cgroup/hugetlb
1686730722.829926385: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/pstore
1686730722.829932892: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/debug
1686730722.829939384: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/debug/tracing
1686730722.829943644: src/main/tools/linux-sandbox-pid1.cc:382: remount(nullptr, /sys/kernel/debug/tracing, nullptr, 2101281, nullptr) failure (Permission denied) ignored
1686730722.829982523: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/kernel/config
1686730722.829990865: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /sys/fs/fuse/connections
1686730722.829998678: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc
1686730722.830005195: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc/sys/fs/binfmt_misc
1686730722.830016003: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /proc/sys/fs/binfmt_misc
1686730722.830021634: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-logs/106
1686730722.830027175: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core18/2128
1686730722.830032473: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-system-monitor/163
1686730722.830037802: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/core20/1081
1686730722.830056928: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-characters/726
1686730722.830062228: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/snapd/12883
1686730722.830067057: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-calculator/884
1686730722.830072115: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gtk-common-themes/1515
1686730722.830076870: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-3-34-1804/72
1686730722.830081648: src/main/tools/linux-sandbox-pid1.cc:362: remount ro: /snap/gnome-3-38-2004/70
1686730722.830087319: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /home/zjm/.cache/bazel/_bazel_zjm/6d3a6312a4e350e29f55a3ebdc686523/sandbox/linux-sandbox/2000/execroot/mediapipe
1686730722.830093889: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /home/zjm/.cache/bazel/_bazel_zjm/6d3a6312a4e350e29f55a3ebdc686523/sandbox/linux-sandbox/2000/execroot/mediapipe
1686730722.830099081: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /tmp
1686730722.830103874: src/main/tools/linux-sandbox-pid1.cc:362: remount rw: /dev/shm
1686730722.830135556: src/main/tools/linux-sandbox-pid1.cc:451: calling fork...
1686730722.830286854: src/main/tools/linux-sandbox-pid1.cc:481: child started with PID 2
Jun 14, 2023 1:18:45 AM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
SEVERE: Error during processing
java.lang.RuntimeException: Error during Statically linking com.google.devtools.build.android.aapt2.CompiledResources@27912e3:
Command: bazel-out/k8-opt-exec-50AE0418/bin/external/androidsdk/aapt2_binary\
	link\
	--static-lib\
	--manifest\
	/tmp/android_resources_tmp16661386781361787503/manifest-aapt-dummy/AndroidManifest.xml\
	--no-static-lib-packages\
	--no-version-vectors\
	-R\
	/tmp/android_resources_tmp16661386781361787503/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_core_core_symbols/symbols.zip\
	-R\
	/tmp/android_resources_tmp16661386781361787503/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_lifecycle_lifecycle_runtime_symbols/symbols.zip\
	-R\
	/tmp/android_resources_tmp16661386781361787503/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_arch_core_core_runtime_symbols/symbols.zip\
	-R\
	/tmp/android_resources_tmp16661386781361787503/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_versionedparcelable_versionedparcelable_symbols/symbols.zip\
	-R\
	/tmp/android_resources_tmp16661386781361787503/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media_symbols/symbols.zip\
	-I\
	external/androidsdk/platforms/android-34/android.jar\
	--auto-add-overlay\
	-o\
	/tmp/android_resources_tmp16661386781361787503/lib.apk\
	--java\
	/tmp/android_resources_tmp16661386781361787503/java\
	--output-text-symbols\
	/tmp/android_resources_tmp16661386781361787503/R.txt
Output:
aapt2 W 06-14 01:18:44    30    30 LoadedArsc.cpp:657] Unknown chunk type '200'.

	at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
	at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
	at com.google.devtools.build.android.aapt2.ResourceLinker.linkStatically(ResourceLinker.java:252)
	at com.google.devtools.build.android.ValidateAndLinkResourcesAction.main(ValidateAndLinkResourcesAction.java:207)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:105)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:234)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)

Exception in thread "main" java.lang.RuntimeException: Error during Statically linking com.google.devtools.build.android.aapt2.CompiledResources@27912e3:
Command: bazel-out/k8-opt-exec-50AE0418/bin/external/androidsdk/aapt2_binary\
	link\
	--static-lib\
	--manifest\
	/tmp/android_resources_tmp16661386781361787503/manifest-aapt-dummy/AndroidManifest.xml\
	--no-static-lib-packages\
	--no-version-vectors\
	-R\
	/tmp/android_resources_tmp16661386781361787503/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_core_core_symbols/symbols.zip\
	-R\
	/tmp/android_resources_tmp16661386781361787503/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_lifecycle_lifecycle_runtime_symbols/symbols.zip\
	-R\
	/tmp/android_resources_tmp16661386781361787503/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_arch_core_core_runtime_symbols/symbols.zip\
	-R\
	/tmp/android_resources_tmp16661386781361787503/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_versionedparcelable_versionedparcelable_symbols/symbols.zip\
	-R\
	/tmp/android_resources_tmp16661386781361787503/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media_symbols/symbols.zip\
	-I\
	external/androidsdk/platforms/android-34/android.jar\
	--auto-add-overlay\
	-o\
	/tmp/android_resources_tmp16661386781361787503/lib.apk\
	--java\
	/tmp/android_resources_tmp16661386781361787503/java\
	--output-text-symbols\
	/tmp/android_resources_tmp16661386781361787503/R.txt
Output:
aapt2 W 06-14 01:18:44    30    30 LoadedArsc.cpp:657] Unknown chunk type '200'.

	at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
	at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
	at com.google.devtools.build.android.aapt2.ResourceLinker.linkStatically(ResourceLinker.java:252)
	at com.google.devtools.build.android.ValidateAndLinkResourcesAction.main(ValidateAndLinkResourcesAction.java:207)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:105)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:234)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)
1686730725.358025446: src/main/tools/linux-sandbox-pid1.cc:498: wait returned pid=2, status=0x100
1686730725.358044373: src/main/tools/linux-sandbox-pid1.cc:516: child exited normally with code 1
1686730725.376996953: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld failed to build
INFO: Elapsed time: 4.478s, Critical Path: 3.63s
INFO: 99 processes: 84 internal, 1 linux-sandbox, 14 worker.
FAILED: Build did NOT complete successfully
```

**Comment by kuaashish** [comment]
@helloWorldNG,

Could you please elaborate your query with complete details, Steps you are following from the documentation? Thank you!

**Comment by velkouby** [comment]
Same issue

OS Platform and Distribution
ubuntu 23.04

MediaPipe version
No response

Bazel version
5.4.0

Android SDK and NDK versions (if android)
android_sdk 30.0.3 
android_ndk 25.1.8937393


Describe the problem
bazel build //tools/cobra/android/apps/main:cobra_app --android_crosstool_top=@androidndk//:toolchain -c opt --cxxopt=-O3 --copt=-O3 --verbose_failures --fat_apk_cpu=arm64-v8a --incremental_dexing --nouse_workers_with_dexbuilder --define=android_dexmerger_tool=d8_dexmerger --define=android_incremental_dexing_tool=d8_dexbuilder --define=android_standalone_dexing_tool=d8_compat_dx --experimental_use_dex_splitter_for_incremental_dexing
Complete Logs

`velkouby@velkouby-XPS-15:~/dev/albatross-monorepo/ai$ bazel build //tools/cobra/android/apps/main:cobra_app --android_crosstool_top=@androidndk//:toolchain -c opt --cxxopt=-O3 --copt=-O3 --verbose_failures --fat_apk_cpu=arm64-v8a --incremental_dexing --nouse_workers_with_dexbuilder --define=android_dexmerger_tool=d8_dexmerger --define=android_incremental_dexing_tool=d8_dexbuilder --define=android_standalone_dexing_tool=d8_compat_dx --experimental_use_dex_splitter_for_incremental_dexing
INFO: Invocation ID: 58debd85-6d07-44fe-87be-xxxxxxxx
DEBUG: Rule 'python3_hermetic_x86_64-unknown-linux-gnu' indicated that a canonical reproducible form can be obtained by dropping arguments ["patches"]
DEBUG: Repository python3_hermetic_x86_64-unknown-linux-gnu instantiated at:
  /home/velkouby/dev/albatross-monorepo/ai/WORKSPACE:23:18: in <toplevel>
  /home/velkouby/dev/albatross-monorepo/ai/albatross_ai_deps.bzl:625:31: in albatross_ai_deps
  /home/velkouby/.cache/bazel/_bazel_velkouby/8f422ec51e28bf518d5ea1c7945a2e5f/external/rules_python/python/repositories.bzl:416:26: in python_register_toolchains
Repository rule python_repository defined at:
  /home/velkouby/.cache/bazel/_bazel_velkouby/8f422ec51e28bf518d5ea1c7945a2e5f/external/rules_python/python/repositories.bzl:312:36: in <toplevel>
INFO: Build options --android_crosstool_top, --compilation_mode, --copt, and 5 more have changed, discarding analysis cache.
WARNING: /home/velkouby/.cache/bazel/_bazel_velkouby/8f422ec51e28bf518d5ea1c7945a2e5f/external/com_github_mediapipe/mediapipe/framework/tool/BUILD:184:24: in cc_library rule @com_github_mediapipe//mediapipe/framework/tool:field_data_cc_proto: target '@com_github_mediapipe//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /home/velkouby/.cache/bazel/_bazel_velkouby/8f422ec51e28bf518d5ea1c7945a2e5f/external/com_github_mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule @com_github_mediapipe//mediapipe/framework:calculator_cc_proto: target '@com_github_mediapipe//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
DEBUG: /home/velkouby/.cache/bazel/_bazel_velkouby/8f422ec51e28bf518d5ea1c7945a2e5f/external/io_bazel_rules_kotlin/kotlin/kotlin.bzl:124:10: kt_android_library should be loaded from //kotlin:android.bzl
INFO: Analyzed target //tools/cobra/android/apps/main:cobra_app (125 packages loaded, 41605 targets configured).
INFO: Found 1 target...
INFO: From Compiling mediapipe/framework/deps/status_builder.cc [for host]:
external/com_github_mediapipe/mediapipe/framework/deps/status_builder.cc: In lambda function:
external/com_github_mediapipe/mediapipe/framework/deps/status_builder.cc:97:3: warning: control reaches end of non-void function [-Wreturn-type]
   97 |   }());
      |   ^
INFO: From Compiling mediapipe/framework/tool/message_type_util.cc [for host]:
external/com_github_mediapipe/mediapipe/framework/tool/message_type_util.cc: In static member function 'static int mediapipe::DescriptorReader::MatchingPrefixLength(const std::string&, const std::string&)':
external/com_github_mediapipe/mediapipe/framework/tool/message_type_util.cc:66:14: warning: comparison of integer expressions of different signedness: 'int' and 'const long unsigned int' [-Wsign-compare]
   66 |     while (i < std::min(s.size(), t.size()) && s[i] == t[i]) {
      |            ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO: From Merging manifest for //tools/cobra/android/apps/main:cobra_app_kt_base:
Warning: /home/velkouby/.cache/bazel/_bazel_velkouby/8f422ec51e28bf518d5ea1c7945a2e5f/sandbox/linux-sandbox/2041/execroot/albatross-ai/tools/cobra/android/apps/main/AndroidManifest.xml:48:9-51:51 Warning:
        provider#androidx.startup.InitializationProvider@android:authorities was tagged at AndroidManifest.xml:48 to replace other declarations but no other declaration present
INFO: From KotlinCompile //android/tools/generator/src/main:init_generatorkt { kt: 1, java: 0, srcjars: 0 } for k8:
android/tools/generator/src/main/java/com/baracoda/ai/generator/InitGenerator.kt:101:84: warning: 'capitalize(): String' is deprecated. Use replaceFirstChar instead.
    return projectName.split("_").joinToString(separator = "", transform = String::capitalize)
                                                                                   ^
android/tools/generator/src/main/java/com/baracoda/ai/generator/InitGenerator.kt:101:84: warning: 'capitalize(): String' is deprecated. Use replaceFirstChar instead.
    return projectName.split("_").joinToString(separator = "", transform = String::capitalize)
                                                                                   ^
ERROR: /home/velkouby/.cache/bazel/_bazel_velkouby/8f422ec51e28bf518d5ea1c7945a2e5f/external/maven/BUILD:1112:11: Linking static android resource library for @maven//:androidx_media_media failed: (Exit 1): ResourceProcessorBusyBox failed: error executing command 
  (cd /home/velkouby/.cache/bazel/_bazel_velkouby/8f422ec51e28bf518d5ea1c7945a2e5f/sandbox/linux-sandbox/2138/execroot/albatross-ai && \
  exec env - \
    PATH=/home/velkouby/.cache/bazelisk/downloads/bazelbuild/bazel-5.4.0-linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/home/velkouby/.local/share/JetBrains/Toolbox/scripts \
  bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool LINK_STATIC_LIBRARY -- --aapt2 bazel-out/k8-opt-exec-50AE0418/bin/external/androidsdk/aapt2_binary --libraries external/androidsdk/platforms/android-34/android.jar --compiled bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media_symbols/symbols.zip --manifest bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media_processed_manifest/AndroidManifest.xml --compiledDep bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_core_core_symbols/symbols.zip:bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_lifecycle_lifecycle_runtime_symbols/symbols.zip:bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_arch_core_core_runtime_symbols/symbols.zip:bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_annotation_annotation_experimental_symbols/symbols.zip:bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_versionedparcelable_versionedparcelable_symbols/symbols.zip --sourceJarOut bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media.srcjar --rTxtOut bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media_symbols/R.txt --staticLibraryOut bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media_files/library.ap_)
# Configuration: 500287bec02fbfd576e8e65d0e4bdc6ee8fb00aa7ae876ad04a493c7100ef732
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Jun 20, 2023 4:31:18 PM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
SEVERE: Error during processing
java.lang.RuntimeException: Error during Statically linking com.google.devtools.build.android.aapt2.CompiledResources@7c3fdb62:
Command: bazel-out/k8-opt-exec-50AE0418/bin/external/androidsdk/aapt2_binary\
        link\
        --static-lib\
        --manifest\
        /tmp/android_resources_tmp13206799685350123029/manifest-aapt-dummy/AndroidManifest.xml\
        --no-static-lib-packages\
        --no-version-vectors\
        -R\
        /tmp/android_resources_tmp13206799685350123029/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_core_core_symbols/symbols.zip\
        -R\
        /tmp/android_resources_tmp13206799685350123029/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_lifecycle_lifecycle_runtime_symbols/symbols.zip\
        -R\
        /tmp/android_resources_tmp13206799685350123029/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_arch_core_core_runtime_symbols/symbols.zip\
        -R\
        /tmp/android_resources_tmp13206799685350123029/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_annotation_annotation_experimental_symbols/symbols.zip\
        -R\
        /tmp/android_resources_tmp13206799685350123029/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_versionedparcelable_versionedparcelable_symbols/symbols.zip\
        -R\
        /tmp/android_resources_tmp13206799685350123029/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media_symbols/symbols.zip\
        -I\
        external/androidsdk/platforms/android-34/android.jar\
        --auto-add-overlay\
        -o\
        /tmp/android_resources_tmp13206799685350123029/lib.apk\
        --java\
        /tmp/android_resources_tmp13206799685350123029/java\
        --output-text-symbols\
        /tmp/android_resources_tmp13206799685350123029/R.txt
Output:
aapt2 W 06-20 16:31:17    47    47 LoadedArsc.cpp:657] Unknown chunk type '200'.

        at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
        at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
        at com.google.devtools.build.android.aapt2.ResourceLinker.linkStatically(ResourceLinker.java:252)
        at com.google.devtools.build.android.ValidateAndLinkResourcesAction.main(ValidateAndLinkResourcesAction.java:207)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:105)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:234)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)

Exception in thread "main" java.lang.RuntimeException: Error during Statically linking com.google.devtools.build.android.aapt2.CompiledResources@7c3fdb62:
Command: bazel-out/k8-opt-exec-50AE0418/bin/external/androidsdk/aapt2_binary\
        link\
        --static-lib\
        --manifest\
        /tmp/android_resources_tmp13206799685350123029/manifest-aapt-dummy/AndroidManifest.xml\
        --no-static-lib-packages\
        --no-version-vectors\
        -R\
        /tmp/android_resources_tmp13206799685350123029/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_core_core_symbols/symbols.zip\
        -R\
        /tmp/android_resources_tmp13206799685350123029/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_lifecycle_lifecycle_runtime_symbols/symbols.zip\
        -R\
        /tmp/android_resources_tmp13206799685350123029/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_arch_core_core_runtime_symbols/symbols.zip\
        -R\
        /tmp/android_resources_tmp13206799685350123029/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_annotation_annotation_experimental_symbols/symbols.zip\
        -R\
        /tmp/android_resources_tmp13206799685350123029/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_versionedparcelable_versionedparcelable_symbols/symbols.zip\
        -R\
        /tmp/android_resources_tmp13206799685350123029/filtered/bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_media_media_symbols/symbols.zip\
        -I\
        external/androidsdk/platforms/android-34/android.jar\
        --auto-add-overlay\
        -o\
        /tmp/android_resources_tmp13206799685350123029/lib.apk\
        --java\
        /tmp/android_resources_tmp13206799685350123029/java\
        --output-text-symbols\
        /tmp/android_resources_tmp13206799685350123029/R.txt
Output:
aapt2 W 06-20 16:31:17    47    47 LoadedArsc.cpp:657] Unknown chunk type '200'.

        at com.google.devtools.build.android.CommandHelper.execute(CommandHelper.java:42)
        at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:297)
        at com.google.devtools.build.android.aapt2.ResourceLinker.linkStatically(ResourceLinker.java:252)
        at com.google.devtools.build.android.ValidateAndLinkResourcesAction.main(ValidateAndLinkResourcesAction.java:207)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:105)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:234)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)
Target //tools/cobra/android/apps/main:cobra_app failed to build
INFO: Elapsed time: 178.148s, Critical Path: 110.15s
INFO: 1469 processes: 60 remote cache hit, 459 internal, 927 linux-sandbox, 23 worker.
FAILED: Build did NOT complete successfully
`

**Comment by physxP** [comment]
@helloWorldNG  did you find any fix? Suffering from the same issue

**Comment by ninh-huynh** [comment]
Problem still exits in version v0.10.15

**Comment by ninh-huynh** [comment]
Explicit set `api_level = 33` could fix this issue

```
# WORKSPACE 

android_sdk_repository(name = "androidsdk", build_tools_version = "30.0.3", api_level = 33, path = "/home/ninh-huynh/Android/Sdk")
android_ndk_repository(name = "androidndk", api_level=21, path = "/home/ninh-huynh/Android/Sdk/ndk/25.2.9519653")
bind(name = "android/crosstool", actual = "@androidndk//:toolchain")

```
