### ISSUE TITLE
build android module failed

### ISSUE THREAD

**Issue by bugmany** [google/mediapipe#4543]
### OS Platform and Distribution

build android module on MacOS 12.5

### Programming Language and version

python 3.11

### MediaPipe version

master

### Bazel version

6.1.1

### Android SDK and NDK versions (if android)

sdk 32 and ndk 21

### Android AAR (if android)

None

### Describe the problem

```shell
-------------
[for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //mediapipe/modules/hand_landmark:palm_detection_detection_to_roi_graph_text_to_binary_graph) external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/mediapipe/modules/hand_landmark/palm_detection_detection_to_roi_graph_text_to_binary_graph-2.params
-------------
```

### Complete Logs

```shell
ERROR: /Users/sh/home/dev/mediapipe/mediapipe/modules/hand_landmark/BUILD:157:26: Linking mediapipe/modules/hand_landmark/palm_detection_detection_to_roi_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //mediapipe/modules/hand_landmark:palm_detection_detection_to_roi_graph_text_to_binary_graph) external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/mediapipe/modules/hand_landmark/palm_detection_detection_to_roi_graph_text_to_binary_graph-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/private/var/tmp/_bazel_sh/33af044bd895cc3d265fd5e2237b6875/execroot/mediapipe/bazel-out/_tmp/actions/stderr-767) 1460956 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
```

**Comment by kuaashish** [comment]
@bugmany,

We are not able to reproduce the issue from our end. Would you let us know the complete steps following to reproduce the issue from our end?

**Comment by bugmany** [comment]
reproduce step:
1. get mediapipe source code(master branch) from github.
2. run "setup_android_sdk_and_ndk.sh" and set android sdk/ndk path.
3. run "build_android_examples.sh" 
then "helloworld" build pass, but "facedetectioncpu" build failed with those failed.

**Comment by kuaashish** [comment]
Hi @bugmany,

Could you please confirm if you still require assistance with this matter? If so, we would like to inform you that AAR solutions for app development are no longer under maintenance, and we anticipate that the reported issue will not be resolved.

Instead, we recommend utilizing our new Face Detection Task API. This API is  an enhanced version of our legacy Face Detection Solution. Further details can be found [here](https://developers.google.com/mediapipe/solutions/guide#legacy).

Additionally, you may refer to the corresponding Overview [documentation](https://developers.google.com/mediapipe/solutions/vision/face_detector) and implementation instructions for Android on this [page](https://developers.google.com/mediapipe/solutions/vision/face_detector/android). Should you encounter any issues during implementation, please feel free to report them to us.

Thank you!!
