### ISSUE TITLE
Is there any flutter support on Media Pipe

### ISSUE THREAD

**Issue by kkas213** [google/mediapipe#4544]
### MediaPipe Solution (you are using)

Object Detection

### Programming language

Dart

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

```shell
Hi I want to ask is there a chance of flutter support for media pipe features like object detection or image classification task please consider this request as the app example of kotlin is very good and can open many possibilities for flutter developers to
```

### Who will benefit with this feature?

Using this feature many flutter developers can use on device ml features 

### Please specify the use cases for this feature

```shell
Can you provide support for flutter environments for media pipe solutions
```

**Comment by kuaashish** [comment]
@kkas213,

This is already in our roadmap. We will be supporting the flutter soon and work in the progress. For now, We can not provide any timeline to be available.

**Comment by UsamaHameed1** [comment]
Ok thanks for sharing this. Hope the package release soon and benfits the community.

**Comment by charlieforward9** [comment]
Duplicate #3922
