### ISSUE TITLE
Missing `exports` in @mediapipe/tasks-vision NPM package

### ISSUE THREAD

**Issue by ArmorDarks** [google/mediapipe#4547]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

NodeJS

### Programming Language and version

JavaScript

### MediaPipe version

0.10.2-rc2

### Solution

@mediapipe/tasks-vision

### Describe the actual behavior

```shell
Right now legacy `package.json` `main` and `module` properties used to declare esm and commonjs paths.
```

### Describe the expected behaviour

```shell
It's better to have `exports` field
```

### Standalone code/steps you may have used to try to get what you need

```shell
1. Install @mediapipe/tasks-vision
2. Try to import it in Jest file in Node 18+
```

**Comment by schmidt-sebastian** [comment]
Will fix shortly.

**Comment by stedwick** [comment]
how are the types coming along?

**Comment by schmidt-sebastian** [comment]
The types are exported. Let us know if you need anything else.
