### ISSUE TITLE
What is the purpose of converting CvMat to ImageFrame when passing image from node to node? Why not just pass CvMat and skip the conversion?

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#455]
I am in the midst of writing my own calculators and it seems that there are a lot of such conversions in official calculators when most of the operations on CPU are written using OpenCV. Why not save the conversion and pass CvMat around? What are the benefits of converting to ImageFrame?

**Comment by mcclanahoochie** [comment]
Hi,
Good question!  cv::Mat is a perfectly acceptable object to pass around in packet streams between calculators, and can certainly be an option for you (or anyone) writing their own custom calculators. 

The main reason for ImageFrame is more of an internal preference, to not require the dependence on opencv for all [internal] applications that want to use any of the mediapipe calculators/graphs. 

I understand it looks a bit weird on the desktop app to convert from opencv to imageframe, then inside the calculator uses opencv again.

On the other hand, using imageframe as interface, the mobile apps don't need to link in opencv (at the app level) to send camera frames into the medaipie graph (nor should they, as the phone camera frames are GPU based). 

The good news is that any conversion between imageframe and cv::Mat happens with zero copy (the data pointer is shared). So the mediapipe::formats::MatView() just creates a cv::Mat header (no data copy), and is very efficient. 

There isn't much benefit of ImageFrame over opencv for your own calculators, other than consistency with the calculators mediapipe provides.
