### ISSUE TITLE
MediaPipe Face landmark vs. MLKit Face mesh

### ISSUE THREAD

**Issue by DeweyReed** [google/mediapipe#4550]
Thank you for doing the heavy lifting for developers!

They both provide a face mesh of 468 points. It appears that MLKit face mesh uses MediaPipe internally and shares the same canonical face model(.obj file).

Will one of them deprecate another in the future? Which one is better for production use?

**Comment by schmidt-sebastian** [comment]
Unfortunately, we (the engineering team behind MediaPipe) cannot provide an answer to question like this. Product announcements are made via our Blogs or other official channels.
