### ISSUE TITLE
bazel reinstall @kaka-lin

### ISSUE THREAD

**Issue by WitmanTzahi** [google/mediapipe#4551]
bazel reinstall @kaka-lin

_Originally posted by @qichuangguo in https://github.com/google/mediapipe/issues/3057#issuecomment-1586522634_

I getting the following error:
Command 'reinstall' not found. Try 'bazel help'.

**Comment by kuaashish** [comment]
Hello @WitmanTzahi,

Could you please elaborate your query with complete details, Steps followed from the documentation to understand the issue better from our end? Thank you!!

**Comment by kuaashish** [comment]
@WitmanTzahi,

Please allow us sometime to share the possible solution. Thank you

**Comment by kuaashish** [comment]
@WitmanTzahi,

Thanks for the detailed explantation. We believe this can be bug in our solution and that causing the build failure
(Similar Issue #4554 ). However, Allow us sometime to discuss internally and provide the fix or workaround on it.

**Comment by WitmanTzahi** [comment]
Hello,

 

Trying to compile with bazel (iOS). https://developers.google.com/mediapipe/framework/getting_started/hello_world_ios

 

bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/HelloWorld:HelloWorldApp

INFO: Analyzed target //mediapipe/examples/ios/HelloWorld:HelloWorldApp (0 packages loaded, 0 targets configured).

INFO: Found 1 target...

ERROR: /Users/tzahiwitman/mediapipe/mediapipe/examples/ios/HelloWorld/BUILD:8:16: CompileRootInfoPlist mediapipe/examples/ios/HelloWorld/HelloWorldApp-intermediates/Info.plist failed: (Exit 1): plisttool failed: error executing command (from target //mediapipe/examples/ios/HelloWorld:HelloWorldApp) bazel-out/darwin_arm64-opt-exec-50AE0418-ST-9facee45ddd0/bin/external/build_bazel_rules_apple/tools/plisttool/plisttool ... (remaining 1 argument skipped)

 

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging

ERROR: Target "@//mediapipe/examples/ios/HelloWorld:HelloWorldApp" is missing CFBundleVersion.

Target //mediapipe/examples/ios/HelloWorld:HelloWorldApp failed to build

Use --verbose_failures to see the command lines of failed build steps.

ERROR: /Users/tzahiwitman/mediapipe/mediapipe/examples/ios/HelloWorld/BUILD:8:16 Bundling HelloWorldApp failed: (Exit 1): plisttool failed: error executing command (from target //mediapipe/examples/ios/HelloWorld:HelloWorldApp) bazel-out/darwin_arm64-opt-exec-50AE0418-ST-9facee45ddd0/bin/external/build_bazel_rules_apple/tools/plisttool/plisttool ... (remaining 1 argument skipped)

 

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging

INFO: Elapsed time: 0.199s, Critical Path: 0.13s

INFO: 5 processes: 5 internal.

FAILED: Build did NOT complete successfully

 

 

Thanks

 

Tzahi

 

 

 

From: kuaashish ***@***.***>
Reply-To: google/mediapipe ***@***.***>
Date: Wednesday, 21 June 2023 at 13:45
To: google/mediapipe ***@***.***>
Cc: Tzahi Witman ***@***.***>, Mention ***@***.***>
Subject: Re: [google/mediapipe] bazel reinstall @kaka-lin (Issue #4551)

 

@WitmanTzahi,

Thanks for the detailed explantation. We believe this can be bug in our solution and that causing the build failure
(Similar Issue #4554 ). However, Allow us sometime to discuss internally and provide the fix or workaround on it.

**Comment by WitmanTzahi** [comment]
Hello,

 

Trying to make one of your examples working (so far nothing works)

 

https://developers.google.com/mediapipe/framework/getting_started/android

bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

 

ERROR: /private/var/tmp/_bazel_tzahiwitman/3cc828acc993b2f03c3005303ba63b90/external/maven/BUILD:252:11: Merging compiled Android resources for @maven//:androidx_core_core failed: (Exit 1): ResourceProcessorBusyBox failed: error executing command (from target @maven//:androidx_core_core) bazel-out/darwin_arm64-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool MERGE_COMPILED -- --classJarOutput ... (remaining 15 arguments skipped)

 

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging

Jun 22, 2023 8:33:45 AM com.google.devtools.build.android.AndroidCompiledResourceMergingAction main

SEVERE: Error during merging resources

com.google.devtools.build.android.AndroidResourceMerger$MergingException: Error during merging

       at com.google.devtools.build.android.AndroidResourceMerger$MergingException.wrapException(AndroidResourceMerger.java:74)

       at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:227)

       at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:231)

       at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$3.call(ResourceProcessorBusyBox.java:85)

       at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:251)

       at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:181)

Caused by: java.io.IOException: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: Android attribute not found: fontVariationSettings

       at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:122)

       at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:91)

       at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:219)

       ... 4 more

Caused by: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: Android attribute not found: fontVariationSettings

       at com.google.devtools.build.android.AndroidFrameworkAttrIdJar.getAttrId(AndroidFrameworkAttrIdJar.java:48)

       at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.getStyleableInitializers(PlaceholderIdFieldInitializerBuilder.java:329)

       at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.build(PlaceholderIdFieldInitializerBuilder.java:238)

       at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:114)

       ... 6 more

 

Jun 22, 2023 8:33:45 AM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest

SEVERE: Error during merging

Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build

Use --verbose_failures to see the command lines of failed build steps.

INFO: Elapsed time: 834.832s, Critical Path: 272.41s

INFO: 3563 processes: 477 internal, 3073 darwin-sandbox, 13 worker.

FAILED: Build did NOT complete successfully

 

Thanks

 

Tzahi Witman

 

From: kuaashish ***@***.***>
Reply-To: google/mediapipe ***@***.***>
Date: Wednesday, 21 June 2023 at 13:45
To: google/mediapipe ***@***.***>
Cc: Tzahi Witman ***@***.***>, Mention ***@***.***>
Subject: Re: [google/mediapipe] bazel reinstall @kaka-lin (Issue #4551)

 

@WitmanTzahi,

Thanks for the detailed explantation. We believe this can be bug in our solution and that causing the build failure
(Similar Issue #4554 ). However, Allow us sometime to discuss internally and provide the fix or workaround on it.

**Comment by WitmanTzahi** [comment]
Hello,

 

I am trying now android (https://developers.google.com/mediapipe/framework/getting_started/hello_world_android)

I succeeded to run it in the past.

I try just to run basic (which is the first step of hello world example

 

***@***.*** mediapipe % echo $ANDROID_HOME      

/Users/tzahiwitman/Library/Android/sdk

***@***.*** mediapipe % echo $ANDROID_NDK_HOME  

/Users/tzahiwitman/Library/Android/sdk/ndk/21.4.7075529

 

export APPLICATION_PATH=mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic

bazel build -c opt --config=android_arm64 $APPLICATION_PATH:helloworld

ERROR: Skipping 'mediapipe/examples/android/src/java/com/google/mediapipe/appselloworld': no such target '//mediapipe:examples/android/src/java/com/google/mediapipe/appselloworld': target 'examples/android/src/java/com/google/mediapipe/appselloworld' not declared in package 'mediapipe' defined by /Users/tzahiwitman/mediapipe/mediapipe/BUILD (Tip: use `query "//mediapipe:*"` to see all the targets in that package)

WARNING: Target pattern parsing failed.

ERROR: no such target '//mediapipe:examples/android/src/java/com/google/mediapipe/appselloworld': target 'examples/android/src/java/com/google/mediapipe/appselloworld' not declared in package 'mediapipe' defined by /Users/tzahiwitman/mediapipe/mediapipe/BUILD (Tip: use `query "//mediapipe:*"` to see all the targets in that package)

INFO: Elapsed time: 23.967s

INFO: 0 processes.

FAILED: Build did NOT complete successfully (1 packages loaded)

 

 

Maybe / at the end

export APPLICATION_PATH=mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/

bazel build -c opt --config=android_arm64 $APPLICATION_PATH:helloworld

ERROR: Skipping 'mediapipe/examples/android/src/java/com/google/mediapipe/appselloworld': no such target '//mediapipe:examples/android/src/java/com/google/mediapipe/appselloworld': target 'examples/android/src/java/com/google/mediapipe/appselloworld' not declared in package 'mediapipe' defined by /Users/tzahiwitman/mediapipe/mediapipe/BUILD (Tip: use `query "//mediapipe:*"` to see all the targets in that package)

WARNING: Target pattern parsing failed.

ERROR: no such target '//mediapipe:examples/android/src/java/com/google/mediapipe/appselloworld': target 'examples/android/src/java/com/google/mediapipe/appselloworld' not declared in package 'mediapipe' defined by /Users/tzahiwitman/mediapipe/mediapipe/BUILD (Tip: use `query "//mediapipe:*"` to see all the targets in that package)

INFO: Elapsed time: 0.061s

INFO: 0 processes.

FAILED: Build did NOT complete successfully (0 packages loaded)

 




 

 

 

From: kuaashish ***@***.***>
Reply-To: google/mediapipe ***@***.***>
Date: Wednesday, 21 June 2023 at 13:45
To: google/mediapipe ***@***.***>
Cc: Tzahi Witman ***@***.***>, Mention ***@***.***>
Subject: Re: [google/mediapipe] bazel reinstall @kaka-lin (Issue #4551)

 

@WitmanTzahi,

Thanks for the detailed explantation. We believe this can be bug in our solution and that causing the build failure
(Similar Issue #4554 ). However, Allow us sometime to discuss internally and provide the fix or workaround on it.

**Comment by WitmanTzahi** [comment]
Hi,

 

 

I cannot run none of the example programs Android or iOS.

 

 

***@***.*** mediapipe % bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/helloworld:HelloWorldApp

WARNING: /Users/tzahiwitman/mediapipe/mediapipe/framework/BUILD:56:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target ***@***.***_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.

WARNING: /Users/tzahiwitman/mediapipe/mediapipe/framework/tool/BUILD:197:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target ***@***.***_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.

INFO: Analyzed target //mediapipe/examples/ios/helloworld:HelloWorldApp (0 packages loaded, 0 targets configured).

INFO: Found 1 target...

ERROR: /private/var/tmp/_bazel_tzahiwitman/3cc828acc993b2f03c3005303ba63b90/external/com_google_absl/absl/status/BUILD.bazel:31:11: Compiling absl/status/status.cc failed: (Exit 1): wrapped_clang_pp failed: error executing command (from target @com_google_absl//absl/status:status) external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 68 arguments skipped)

 

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging

external/com_google_absl/absl/status/status.cc:129:30: error: 'value' is unavailable: introduced in iOS 12.0

    return (*payloads)[index.value()].payload;

                             ^

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here

    constexpr value_type& value() &

                          ^

external/com_google_absl/absl/status/status.cc:147:28: error: 'value' is unavailable: introduced in iOS 12.0

    (*rep->payloads)[index.value()].payload = std::move(payload);

                           ^

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here

    constexpr value_type& value() &

                          ^

external/com_google_absl/absl/status/status.cc:159:57: error: 'value' is unavailable: introduced in iOS 12.0

    GetPayloads()->erase(GetPayloads()->begin() + index.value());

                                                        ^

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/usr/include/c++/v1/optional:1014:27: note: 'value' has been explicitly marked unavailable here

    constexpr value_type& value() &

                          ^

3 errors generated.

Error in child process '/usr/bin/xcrun'. 1

Target //mediapipe/examples/ios/helloworld:HelloWorldApp failed to build

Use --verbose_failures to see the command lines of failed build steps.

INFO: Elapsed time: 4.361s, Critical Path: 4.19s

INFO: 220 processes: 117 internal, 103 darwin-sandbox.

FAILED: Build did NOT complete successfully

 

 

 

 

From: kuaashish ***@***.***>
Reply-To: google/mediapipe ***@***.***>
Date: Wednesday, 21 June 2023 at 13:45
To: google/mediapipe ***@***.***>
Cc: Tzahi Witman ***@***.***>, Mention ***@***.***>
Subject: Re: [google/mediapipe] bazel reinstall @kaka-lin (Issue #4551)

 

@WitmanTzahi,

Thanks for the detailed explantation. We believe this can be bug in our solution and that causing the build failure
(Similar Issue #4554 ). However, Allow us sometime to discuss internally and provide the fix or workaround on it.

**Comment by kuaashish** [comment]
Hi @WitmanTzahi,

As previously communicated regarding this matter, issue #4393. We are no longer maintaining the legacy face detection solution, as it has been integrated into the new Face detection task API, as explained in our [documentation](https://developers.google.com/mediapipe/solutions/guide#legacy). 

We intend to explore and implement our upgraded Face detection in Android, following the steps outlined in our [documentation](https://developers.google.com/mediapipe/solutions/vision/face_detector/android).

Additionally, we kindly request you to inform us of any errors encountered during the exploration process.

Thank you
