### ISSUE TITLE
module 'mediapipe' has no attribute 'solution'. Did you mean: 'solutions'?

### ISSUE THREAD

**Issue by fishyville** [google/mediapipe#4555]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Window

### Task name (e.g. Image classification, Gesture recognition etc.)

hand gesture

### Programming Language and version (e.g. C++, Python, Java)

python

### Describe the actual behavior

```shell
module 'mediapipe' has no attribute 'solution'. Did you mean: 'solutions'?
```

### Describe the expected behaviour

```shell
It opens camera and will detect my hands
```

### Standalone code/steps you may have used to try to get what you need

```shell
mpHands-mp.solution.drawing_utils
devices=AudioUtilities.GetSpeakers ()
interface=devices. Activate (IAudioEndpointVolume. _iid_,CLSCTX_ALL, None)
volume=cast(interface, POINTER(IAudioEndpointVolume))
```

**Comment by kuaashish** [comment]
@fishyville,

Please import the module 'solutions' not the 'solution', As code structure does not have such class or attribute([Check here](https://github.com/google/mediapipe/tree/master/mediapipe/python/solutions)) like below:

` mpHands-mp.solutions.drawing_utils`

However, let us know if still an issue from your end.

**Comment by fishyville** [comment]
oh, so thats what the mistake are. im so dumb. thanks

**Comment by fishyville** [comment]
oh it kinda fix things but i got this instead:

unsupported operand type(s) for -: 'module' and 'module'

**Comment by kuaashish** [comment]
@fishyville,

Please provide the complete standalone code to reproduce the issue from our end?  Thank you

**Comment by fishyville** [comment]
mpHands-mp.solutions.drawing_utils

The system are referring to the "drawing_utils"

**Comment by kuaashish** [comment]
@fishyville,

We are not able to understand the issue, Please provide the complete steps you are following, Or complete code to reproduce the issue. Thank you

**Comment by fishyville** [comment]
import cv2
import mediapipe as mp
from math import hypot
from ctypes import cast, POINTER
from comtypes import CLSCTX_ALL
from pycaw.pycaw import AudioUtilities, IAudioEndpointVolume
import numpy as np
cap=cv2.VideoCapture (0)#checks for the availability of camera
mpHands=mp.solutions.hands#detects fingers
hands=mpHands. Hands () #completes the initialization and configuration of the hands and fingers

mpHands-mp.solutions.drawing_utils
devices=AudioUtilities.GetSpeakers ()
interface=devices. Activate (IAudioEndpointVolume. _iid_,CLSCTX_ALL, None)
volume=cast(interface, POINTER(IAudioEndpointVolume))


It shows this:

File "c:\Users\USER\OneDrive\Documents\trial 1\blabla.py", line 12, in <module>
    mpHands-mp.solutions.drawing_utils
    ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'module' and 'module'
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
