### ISSUE TITLE
How to obtain mediapipe Face Detection face embedding？

### ISSUE THREAD

**Issue by lonngxiang** [google/mediapipe#4556]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

windows

### Task name (e.g. Image classification, Gesture recognition etc.)

Face Detection

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

```shell
How to obtain mediapipe Face Detection face embedding？
```

### Describe the expected behaviour

```shell
How to obtain mediapipe Face Detection face embedding？
```

### Standalone code/steps you may have used to try to get what you need

```shell
https://github.com/google/mediapipe/blob/master/docs/solutions/face_detection.md
```

**Comment by kuaashish** [comment]
@lonngxiang,

Mediapipe doesn't provide a face recognition method, only face detection. We see there are other module which can help on your use case https://pypi.org/project/face-recognition/ library has good accuracy. However, We do not provide the support on How to use them.

**Comment by lonngxiang** [comment]
> @lonngxiang,
> 
> Mediapipe doesn't provide a face recognition method, only face detection. We see there are other module which can help on your use case https://pypi.org/project/face-recognition/ library has good accuracy. However, We do not provide the support on How to use them.

Ok, thank you. We look forward to your follow-up support, because the mediapipe project has a great advantage, that is, it is small and fast

**Comment by kuaashish** [comment]
@lonngxiang,

We would like you to raise a new feature request to support the face recognition method And We will share internally based on discussion team will prioritise the feature. However, To keep context of actual explanation with title for easier filter out the issue. We need your confirmation to mark the this as resolved and move the status to the close. Thank you

**Comment by currenthandle** [comment]
Please add facial recognition. Specifically for my use case: I need to be able to produce a feature vector (embeddings) for particular individual's face. If another face has a sufficiently close embedding vector, they are the same person.
