### ISSUE TITLE
ReferenceError: FilesetResolver is not defined at initializeObjectDetector

### ISSUE THREAD

**Issue by stojanni** [google/mediapipe#4558]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Windows 11

### MediaPipe Tasks SDK version

tried multiple

### Task name (e.g. Image classification, Gesture recognition etc.)

Object detection 

### Programming Language and version (e.g. C++, Python, Java)

js

### Describe the actual behavior

```shell
im trying to use this example: https://codepen.io/mediapipe-preview/pen/vYrWvNg locally but i get the error
```

### Describe the expected behaviour

```shell
should work without errors
```

### Standalone code/steps you may have used to try to get what you need

```shell
i tried many cdn links but none worked. this is the html: https://pastebin.com/19wSdzTF and this is the js: https://pastebin.com/9q8JNnxG
```

**Comment by stojanni** [comment]
UPDATE i managed to fix it, prolly had made something wrong while setting it up

**Comment by gowtham-myanatomy** [comment]
Hi @stojanni 
can u please mention the way u have fixed it
