### ISSUE TITLE
Source code of Mediapipe Studio face_landmarker demo

### ISSUE THREAD

**Issue by anthnyprschka** [google/mediapipe#4559]
### Browser and Version

Chrome

### URL that shows the problem

https://mediapipe-studio.webapps.google.com/demo/face_landmarker

### Describe the actual behavior

```shell
Hi there, I can't find the source of this demo in Mediapipe Studio: https://mediapipe-studio.webapps.google.com/demo/face_landmarker
```

### Describe the expected behaviour

```shell
Where can I find the source code of mentioned Mediapipe Studio demo? Thanks in advance!
```

**Comment by kuaashish** [comment]
@anthnyprschka,

Javascript Source code is available for MP Tasks, And Will not be published for other Solutions. Thank you

**Comment by kuaashish** [comment]
@anthnyprschka,

JavaScript Source code is only available for MediaPipe Tasks in the [Github Repository](https://github.com/google/mediapipe/tree/master/mediapipe/tasks/web) And face landmarker Source Code is available [here](https://github.com/google/mediapipe/tree/master/mediapipe/tasks/web/vision/face_landmarker). However, For other solutions Studio, Model_maker Source Code will not be published. Thank you
