### ISSUE TITLE
How to interpret palm detection output?

### ISSUE THREAD

**Issue by Michael89** [google/mediapipe#456]
I have run palm detection model on my desktop with tensorflow, and got output of such shape
`output_data[0].shape`
`(2944, 18)`
With such values:
```
array([ -0.8996319 ,   8.055114  ,  37.630108  ,  37.6301    ,
         4.1576405 ,  26.547136  ,   6.306625  ,  -8.648109  ,
         2.4374104 ,  -8.058775  ,  -3.66878   ,  -4.670782  ,
       -10.253105  ,   0.40274066,   4.5256443 ,  24.233337  ,
        -0.4015277 ,  12.955139  ], dtype=float32)
```
What all of this numbers mean and how to project them back on original image?

**Comment by fanzhanggoogle** [comment]
Hi, as in SSD models, these are the predictions based on predefined anchors. We use [TfLiteTensorsToDetectionsCalculator](https://github.com/google/mediapipe/blob/a2a63e387680c090f76072864a107647e874d390/mediapipe/graphs/hand_tracking/subgraphs/hand_detection_gpu.pbtxt#L91) to decode the output tensors given the [SSD anchors](https://github.com/google/mediapipe/blob/a2a63e387680c090f76072864a107647e874d390/mediapipe/graphs/hand_tracking/subgraphs/hand_detection_gpu.pbtxt#L64).

**Comment by Michael89** [comment]
Sorry but I'm still didn't get. I read some articles about SSD but none of them have exactly same configuration of predefined anchors as I understood. And as you mentioned I need to get my output and run through one mode model in order to convert it to boxes on my image. Is it correct.
Currently my code looks like this (using python and tensorflow tflite)
```
interpreter = tflite.Interpreter(model_path="../resources/palm_detection_without_custom_op.tflite")
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
resized = letterbox_image(color, (256, 256))

input_data = [resized.astype(np.float32)/256]
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
classification_out = interpreter.get_tensor(output_details[1]['index'])
```
`output_data.shape # (1, 2944, 18)`
`classification_out.shape # (1, 2944, 1)`
So now I should use [TfLiteTensorsToDetectionsCalculator ](https://github.com/google/mediapipe/blob/a2a63e387680c090f76072864a107647e874d390/mediapipe/graphs/hand_tracking/subgraphs/hand_detection_gpu.pbtxt#L91) and feed it output_data as input and i will get region?
I didn't find any pretrained model that will do this for me. Or I doing something wrong.

**Comment by Michael89** [comment]
I read docs carefully again and understood how it works.
Thnx for your help

**Comment by edwardnguyen1705** [comment]
Hi @Michael89, have you finished getting palm detections (bbox) in the original image?

**Comment by aashish2000** [comment]
Hi @edwardnguyen1705, if you require bounding boxes for palm detections, check out this [repository](https://github.com/aashish2000/hand_tracking). I have implemented a plain palm detector based on [metalwhale's repo](https://github.com/metalwhale/hand_tracking). Hope it helps.

**Comment by edwardnguyen1705** [comment]
Hi @aashish2000 
Thank you.

**Comment by djthegr8** [comment]
I used the TFjS model for this on TFhub, and am getting a single array of `1,2944,19` 
How can I interpret this????

**Comment by denred0** [comment]
For everybody how wants to understand meaning of (2944, 18). It's a 2944 anchor boxes and 18 offsets for them. 
```
out_reg shape is [number of anchors, 18]
Second dimension 0 - 4 are bounding box offset, width and height: dx, dy, w ,h
Second dimension 4 - 18 are 7 hand keypoint x and y coordinates: x1,y1,x2,y2,...x7,y7
```
7 hand keypoints (knuckles, wrist base point, etc)
