### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'export' (at vision_bundle.js:1:880347) when importing Handlandmarker task using JSdeliver

### ISSUE THREAD

**Issue by isaiahltupal** [google/mediapipe#4560]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows (wsl default)

### Task name (e.g. Image classification, Gesture recognition etc.)

HandLandmarker

### Programming Language and version (e.g. C++, Python, Java)

Javascript

### Describe the actual behavior

```shell
Opening the html using the chrome as it is with the JSDelivery tag throws the following error: Uncaught SyntaxError: Unexpected token 'export' (at vision_bundle.js:1:880347)
```

### Describe the expected behaviour

```shell
It should import the vision bundle that will be use to create the handlandmarker
```

### Standalone code/steps you may have used to try to get what you need

```shell
Placing the the following element in the html then opening it in chrome will cause the issue


<head>
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/vision_bundle.js"
    crossorigin="anonymous"></script>
</head>
```
```


### Other info / Complete Logs

_No response_

**Comment by schmidt-sebastian** [comment]
You can import using

```
<head>
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/vision_bundle.mjs"
    crossorigin="anonymous" type="module"></script>
</head>
```

or
```
<head>
  <script src="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/vision_bundle.cjs"
    crossorigin="anonymous"></script>
</head>
```

**Comment by marcusx2** [comment]
@schmidt-sebastian if I use the second option the error `Refused to execute https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/vision_bundle.cjs as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.` is thrown on MacOS Safari

**Comment by Hansson0728** [comment]
same issue here.
