### ISSUE TITLE
"image_format.pb.h" does not exist

### ISSUE THREAD

**Issue by jenniferxuu** [google/mediapipe#4563]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Ubuntu 20.04.5 LTS 

### Task name (e.g. Image classification, Gesture recognition etc.)

Image classification

### Programming Language and version (e.g. C++, Python, Java)

C++

### Describe the actual behavior

```shell
In my code, I have included image_frame.h because I create and use the ImageFrame object. However, image_frame.h includes image_format.pb.h which is not a file I have anywhere - was this file replaced? Am I able to download it from somewhere else? Thanks!
```

### Describe the expected behaviour

```shell
The include statement should be fine and there shouldn't be any dependency issues with MediaPipe files.
```

### Standalone code/steps you may have used to try to get what you need

```shell
Found this other issue that seemed similar but still couldn't get it working: https://github.com/google/mediapipe/issues/436
```

**Comment by kuaashish** [comment]
@jenniferxuu,

Could you please provide the complete code or steps you are following to reproduce the issue? Thank you

**Comment by kuaashish** [comment]
Hello @jenniferxuu,

Have you added the .cpp file in the Build file here?

https://github.com/google/mediapipe/blob/master/mediapipe/framework/formats/BUILD#L148


Please update the status, If this works for you. Thank you!!

**Comment by andrechen** [comment]
image_format.pb.h and image_format.pb.cc are generated by [protocol buffers](https://protobuf.dev/) during the bazel building process if [image_format_proto](https://github.com/google/mediapipe/blob/422556c4a3317bf6cbc9680ac7809152093a4de7/mediapipe/framework/formats/BUILD#L71) dependency is required. protocol buffer compiler generates the correct version of the code from [image_format.proto](https://github.com/google/mediapipe/blob/master/mediapipe/framework/formats/image_format.proto), which is a complementary of image_frame module. To use mediapipe, you need to specify every required dependencies modules in bazel scripts, that's experts do.

if you'd like to generate image_format.pb.h/.cc simply, you can call the protocol buffers compiler, **protoc**, [like this](https://github.com/andrechen/mediapipe/blob/master/visualstudio/build_protos.bat).

**Comment by jenniferxuu** [comment]
@andrechen Just to clarify, I need to run the code you linked so that all the files can be generated by the protocol buffers?

**Comment by andrechen** [comment]
that .bat is just an example to show the **protoc** usage. I use that .bat **on windows** to quickly generate all [.pb.h, pb.cc](https://github.com/andrechen/mediapipe/tree/master/visualstudio/mediapipe/framework/formats) source code by double clicking it. Maybe stick with bazel [BUILD](https://github.com/google/mediapipe/blob/dbe8e401247b871160488374e1383e083748ac16/mediapipe/framework/formats/BUILD#L148) script is easier in your case.

**Comment by jenniferxuu** [comment]
@andrechen I see, thank you! Do you know what the command for the Bazel BUILD file is? From the Hello World example, they used `bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world` so do I just run `bazel run` in order for the BUILD file to generate all .pb.h and .pb.cc files? Thank you!

**Comment by andrechen** [comment]
@jenniferxuu NO, you should clone that entire [repo](https://github.com/andrechen/mediapipe) to your local windows machine, then double click it. you can open up the [visual studio solution](https://github.com/andrechen/mediapipe/tree/master/visualstudio) file to build all **legacy** projects and also debug it line-by-line.

**Comment by kuaashish** [comment]
@jenniferxuu,

Sorry for the delayed response,

Could you please confirm that Are you still looking for the resolution or the issue has been resolved from your end?

Thank you

**Comment by jenniferxuu** [comment]
That worked, thank you!!

**Comment by jenniferxuu** [comment]
That worked, thank you!!
