### ISSUE TITLE
Code in the hand landmark sample notebook causes Python to quit

### ISSUE THREAD

**Issue by QuantumStatic** [google/mediapipe#4569]
I have used the code notebook specified in the docs. While trying to visualise the image with hand land marks drawn upon it, the code breaks, it produces an unknown error. [Code Notebook in the docs](https://github.com/googlesamples/mediapipe/blob/main/examples/hand_landmarker/python/hand_landmarker.ipynb)

My code is below:
```python

def print_result(result, output_image: mp.Image, timestamp_ms: int):
    try:
        img = draw_landmarks_on_image(output_image.numpy_view(), result)
    except Exception:
        print("error")
    else:
        cv2.imshow("pipe", cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
        cv2.waitKey(1)

model_manager = Model_Manager.ModelManager()
options = HandLandmarkerOptions(
    base_options=BaseOptions(model_asset_path=model_manager.HAND_LANDMARKER_MODEL_PATH),
    running_mode=VisionRunningMode.LIVE_STREAM,
    result_callback=print_result,
    num_hands=1)

with HandLandmarker.create_from_options(options) as detector:
    videoCapture = cv2.VideoCapture(0)

    while True:
        frame_exists, frame = videoCapture.read()
        
        if frame_exists:
            mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=frame)
            detector.detect_async(mp_image, mp.Timestamp.from_seconds(time.time()).value)
        
        if 0xFF == ord('q'):
            break

    videoCapture.release()
    cv2.destroyAllWindows()

```

The function draw landmarks on image has been taken as is from the code notebook specified in the docs. Code stops executing right at `cv2.imshow` . I have looked up stackoverflow, nothing made sense to me. The error is: 
```
libc++abi: terminating due to uncaught exception of type pybind11::error_already_set: error: Unknown C++ exception from OpenCV code

At:
  /Users/username/file/path/main.py(74): print_result
  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mediapipe/tasks/python/vision/hand_landmarker.py(254): packets_callback
```

**Comment by kuaashish** [comment]
@QuantumStatic,

Please provide the complete information about the issue, We are not able to reproduce it from our end. Also, We recommend you to fill the [issue template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&projects=&template=15-build-install-issue-template.yaml) to get relevant details. Thank you!!

**Comment by kinaryml** [comment]
> ```python
> global_img, global_results = None, None
> def print_result(result, output_image: mp.Image, timestamp_ms: int):
>     global global_img, global_results
>     global_img = draw_landmarks_on_image(output_image.numpy_view(), result)
>     global_results = result
> ```

@QuantumStatic Could you try this Colab notebook out on your M1 and let us know if you encounter the same issue?

It seems to run fine on Linux in the notebook FYI.

**Comment by kinaryml** [comment]
Replace `cv2_imshow` with `cv2.imshow("MediaPipe Hands", annotated_image)` while running on your M1.
