### ISSUE TITLE
Wouldn't it be a better design if we expose the div and sub values in NormalizeImage function in tflite_converter_calculator.cc as options?

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#457]
With that we can accommodate different normalization values.

Right now, the zero scale option is rather restrictive.

**Comment by mcclanahoochie** [comment]
Thanks for the feedback. 
This is the first request of this type. To help us understand why this is desired, can you please say: What other normalization values are useful, and what is your application, and what other models (other than yours) could benefit from this?
Thanks,

**Comment by yxchng** [comment]
@mcclanahoochie  For example, in most face recognition models use the mean of 127.5 and std of 128, while ImageNet models mostly use ImageNet mean and std.

**Comment by mcclanahoochie** [comment]
Hi,
 All floating point models MediaPipe uses expects values either from [-1,1] or [0,1]. If using a quantized model, no normalization is done (input is assumed to be 8bit already). 
If your model expects floating point values between [x,y], I would suggest writing a simple multiply calculator that follows the converter calc.
This request has been noted, but alternatively, adding 'div' and 'sub' options to LoadOptions() wouldn't be that hard either for a user to do.
Thanks for the update.

**Comment by yxchng** [comment]
@mcclanahoochie yes it wouldn't be hard but I am just suggesting this to make MediaPipe better

**Comment by chuoling** [comment]
This has been implemented in the internal code base upstream, and will be pushed to GitHub in the next release. More specifically, we've added the following option:

optional TensorFloatRange output_tensor_float_range = 9;
message TensorFloatRange {
   optional float min = 1;
   optional float max = 2;
}

**Comment by chuoling** [comment]
https://github.com/google/mediapipe/blob/bdfdaef30585719ed2cd1bc598a3e9879bcc4a1c/mediapipe/calculators/tflite/tflite_converter_calculator.proto#L63
