### ISSUE TITLE
How to use posttracking to detect static images on Android?

### ISSUE THREAD

**Issue by LTYF** [google/mediapipe#4576]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Android5

### Solution

Pose

### Programming Language and version

java

**Comment by kuaashish** [comment]
Hello @LTYF,

You can pass the image through the class https://github.com/google/mediapipe/blob/master/mediapipe/tasks/java/com/google/mediapipe/tasks/vision/poselandmarker/PoseLandmarker.java#L240 as mentioned in the comment:

```
 /**
   * Performs pose landmarks detection on the provided single image. Only use this method when the
   * {@link PoseLandmarker} is created with {@link RunningMode.IMAGE}. TODO update java
   * doc for input image format.
   .
   .
   .
   .
```

Thank you
