### ISSUE TITLE
Sporadic error starting up MediaPipe - attachToGLContext

### ISSUE THREAD

**Issue by magic-fit** [google/mediapipe#4578]
Sometimes MediaPipe crashes on startup (~ 1 out of 10 times) with the following error in my Android app.

android.graphics.SurfaceTexture in attachToGLContext at line 289
com.google.mediapipe.components.ExternalTextureConverter$RenderThread in setSurfaceTextureAndAttachToGLContext at line 15
com.google.mediapipe.components.ExternalTextureConverter in lambda$setSurfaceTextureAndAttachToGLContext$2 at line 3
com.google.mediapipe.components.ExternalTextureConverter in a at line 1
com.google.mediapipe.components.h in run at line 9
android.os.Handler in handleCallback at line 873
android.os.Handler in dispatchMessage at line 99
android.os.Looper in loop at line 193
com.google.mediapipe.glutil.GlThread in run at line 54

Is there any way to catch this error and prevent my app from crashing? I've added an error listener to ExternalTextureConverter temporarily to pass Exceptions back to my app but wandering if there was a better way that doesn't involve editing the library. 

Thank you

**Comment by kuaashish** [comment]
Hello @magic-fit,

Could you please elaborate your query with complete details, Also, We recommend you to fill the [issue template](https://github.com/google/mediapipe/issues/new/choose) to get relevant information to reproduce it And provide the possible solution in the error you are facing. Thank you!!
