### ISSUE TITLE
Seeking Release Date for Latest MediaPipe Holistic Model Update

### ISSUE THREAD

**Issue by PaStMir** [google/mediapipe#4584]
Hello MediaPipe Team,

I'm working with your holistic model in my research :)
Could you please provide an update on when we can expect the release of the latest version of the MediaPipe Holistic Model?

Best regards

**Comment by kuaashish** [comment]
Hello @PaStMir,

Thank you for your interest in MediaPipe solutions. For now, we can not commit any release date. However, Please be assured we will publish the model ASAP solution will be ready from our end.
