### ISSUE TITLE
How to delegate to OpenCL

### ISSUE THREAD

**Issue by fchen09** [google/mediapipe#4585]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android 12

### MediaPipe version

0.10.1

### Bazel version

0.6.1

### Solution

Pose

### Programming Language and version

Java

### Describe the actual behavior

```shell
How do I delegate to OPENCL? When I change the api:OPENCL, I got some errors: Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found. Any way to resolve the issue? Thanks!
```

### Describe the expected behaviour

```shell
Should work on OPENCL without errors.
```

**Comment by kuaashish** [comment]
@fchen09,

Could you elaborate your query with complete details. Also, Please provide the complete steps you are following to reproduce the issue from our end. Thank you!!
