### ISSUE TITLE
Duplicate class com.google.mediapipe.formats.annotation.proto.RasterizationProto

### ISSUE THREAD

**Issue by DanhDao1997** [google/mediapipe#4587]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

MacOS 13.4, Android 13

### Mobile device if the issue happens on mobile device

Pixel 4a 5G

### Programming Language and version

Kotlin

### Solution

Hand

### Describe the actual behavior

```shell
I'm currently trying to use Mediapipe mediapipe:tasks-vision (0.10.1) for Hand Landmarks detection. The project previously used mediapipe:solution-core(0.10.1) dependency. However, when I try to build the project, I got the error Duplicate class com.google.mediapipe.formats.annotation.proto.RasterizationProto found in modules jetified-solution-core-0.10.1-runtime (com.google.mediapipe:solution-core:0.10.1) and jetified-tasks-core-0.10.1-runtime (com.google.mediapipe:tasks-core:0.10.1).
```

### Describe the expected behaviour

```shell
The code runs without duplicate class
```

### Standalone code/steps you may have used to try to get what you need

```shell
None
```

**Comment by kuaashish** [comment]
Hello @DanhDao1997,

Could you please elaborate your query with complete steps followed to reproduce the issue from our end?  Thank you!
