### ISSUE TITLE
Web demo

### ISSUE THREAD

**Issue by Rakeshvcr** [google/mediapipe#459]
Hi, The web demo looks really cool and flawless. I have few use cases that can be done using it, is the source code available and can I use it to commercial use.

**Comment by mgyong** [comment]
@Rakeshvcr What is the use case you are looking to do? 

We plan to release documentation and API for you to run MediaPipe graphs from javascript using Web assembly as demonstrated from the web demos. We will update this thread when we have such an API ready in javascript

**Comment by jackz314** [comment]
Any idea on when the said API would be available? I plan on using this in a project, but if the ETA is too late I'll have to find alternatives.

**Comment by khelkun** [comment]
https://blog.tensorflow.org/2020/03/face-and-hand-tracking-in-browser-with-mediapipe-and-tensorflowjs.html

**Comment by delebash** [comment]
The tensorflow js version is not the same as the one running in the visualizer. Example tfjs handpose estimation https://github.com/tensorflow/tfjs-models/tree/master/handpose does not do multihand.  However the mediapipe visualizer does.
