### ISSUE TITLE
Mediapipe Studio Demo fails - Error: StartGraph failed: $Service "kGpuService", required by node

### ISSUE THREAD

**Issue by il-nietos** [google/mediapipe#4594]
### OS Platform and Distribution

MacOS 13.0 with M2 chip

### Browser and Version

Chrome Version 114.0.5735.198 (Official Build) (arm64)

### Any microphone or camera hardware

in-built camera of mac

### URL that shows the problem

https://mediapipe-studio.webapps.google.com/demo/hand_landmarker

### Describe the actual behavior

```shell
When https://mediapipe-studio.webapps.google.com/demo/hand_landmarker
No detections are given either with CPU or GPU inference with the lowest score threshold level. Same behaviour on the hand landmark detection and gesture recognition.
Browser returns the following error: 

Error: Uncaught (in promise): Error: StartGraph failed: $Service "kGpuService", required by node mediapipe_tasks_vision_face_detector_facedetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageCloneCalculator, was not provided and cannot be created: emscripten_webgl_create_context() returned error 0; StartRun failed
```

### Describe the expected behaviour

```shell
Faces and hands detected.
```

### Other info / Complete Logs

```shell
Error: Uncaught (in promise): Error: StartGraph failed: $Service "kGpuService", required by node mediapipe_tasks_vision_face_detector_facedetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageCloneCalculator, was not provided and cannot be created: emscripten_webgl_create_context() returned error 0; StartRun failed
```

**Comment by kuaashish** [comment]
@il-nietos,

Could you confirm that you are using a canvas And calling the `canvas.getContext('2d')`?  If you are using a canvas, Can you instead use dedicated canvas might resolve the issue.  Please let us know status of the issue if this works for you.

Reference:[Gesture Recognizer unable to use GPU inference](https://github.com/google/mediapipe/issues/4327). 

Thank you!!

**Comment by il-nietos** [comment]
Sorry was not clear - 
I am really only opening the https://mediapipe-studio.webapps.google.com/demo/hand_landmarker in chrome browser and the webcam is automatically opened and should show the detections. But nothing is shown and this error is shown in top bar in the browser.

**Comment by volodymyrl** [comment]
I have this error in the iPhone Firefox for segmentation tsk. 

```
E0823 14:22:10.125000 1819728 gl_graph_runner_internal.cc:260] StartGraph failed: INTERNAL: Service "kGpuService", required by node mediapipe_tasks_vision_image_segmenter_imagesegmentergraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageCloneCalculator, was not provided and cannot be created: emscripten_webgl_create_context() returned error 0; StartRun failed
=== Source Location Trace: === 
third_party/mediapipe/framework/calculator_graph.cc:651
third_party/mediapipe/framework/calculator_graph.cc:682
third_party/mediapipe/framework/calculator_graph.cc:551
research/drishti/app/pursuit/wasm/graph_utils.cc:100
```

```
Unhandled Promise Rejection: Error: Service "kGpuService", required by node mediapipe_tasks_vision_image_segmenter_imagesegmentergraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageCloneCalculator, was not...
```

I also have the same error on the example https://codepen.io/satoren/pen/xxQvmjv provided in this issue from https://github.com/google/mediapipe/issues/4630#issuecomment-1681938382

Is it possible to detect that browser doesn't support the mediapipe lib and prevent this error?

**Comment by satoren** [comment]
@volodymyrl 
I also encountered the same problem with desktop Safari (16.5.1).
Upon investigation, it appears that webgl2 is failing to create a Context, and [Safari's OffscreenCanvas only works with 2d canvas.](https://caniuse.com/offscreencanvas)

In my [example](https://codepen.io/satoren/pen/xxQvmjv), replacing OffscreenCanvas with HTMLCanvasElement worked.
```diff
- const tasksCanvas = new OffscreenCanvas(1,1)
+ const tasksCanvas = document.createElement("canvas")
```

**Comment by satoren** [comment]
@il-nietos 
If you get an error on https://mediapipe-studio.webapps.google.com/demo/hand_landmarker, hardware acceleration may be disabled in your Chrome settings. (If set Inference delegate to CPU, but webgl context cannot be created, an error will occur.)
Can you access `chrome://gpu/` on your chrome to check that WebGL2 is enabled?

**Comment by volodymyrl** [comment]
@satoren, thanks for the helpful advice, as always 😀

**Comment by kuaashish** [comment]
@il-nietos,

We are revisiting the older issues, Could you please confirm that you are still looking for the resolution on this issue or it has been resolved from your end. Thank you
