### ISSUE TITLE
Mediapipe unity standalone build version not working on different pc

### ISSUE THREAD

**Issue by TulgaTDev** [google/mediapipe#4596]
I recently encountered a strange issue. Initially, I developed a Unity project that utilizes the Mediapipe plugin. After completing the project, I built a version that worked fine on my PC. However, when I attempted to run it on a different PC, things didn't go as expected. The annotation points didn't appear on my face (which is recorded through the webcam). As a result, I decided to build the project on the new PC, where the previous build didn't work. When I opened the project, I encountered errors related to the asset loader type from the bootstrap component. To resolve these errors, I changed the asset loader type from "streaming assets" to "local." Then, I switched it back to "streaming assets" for the build. After fixing these errors, I successfully built and ran the project, it worked fine. Interestingly, I also rechecked the first build version from my old computer, and it somehow worked as well. For now, everything seems to be functioning correctly, but I would like to understand the cause of this issue and learn how to prevent it from occurring in the future.

**Comment by kuaashish** [comment]
@TulgaTDev,

MediaPipe does not offer any official support, library, module for mapping the face landmarks to Unity as such. there are [plugin](https://github.com/homuler/MediaPipeUnityPlugin) from the community is quite up-to-date which might help in this context But We don't have a plan to support Unity and does not provide support in how to use them.

However, We are working towards support of flutter and will become available once it will ready from our end. Thank you!!
