### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'maven':

### ISSUE THREAD

**Issue by SnoopPanda** [google/mediapipe#4597]
### OS Platform and Distribution

MacOS Ventura 13.3.1

### Programming Language and version

Android Java

### MediaPipe version

mediapipe-0.9.2.1

### Bazel version

6.2.1

### Android AAR (if android)

Yes

### Describe the problem

```shell
build Android AAR:
bazel build -c opt --strip=ALWAYS \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    --legacy_whole_archive=0 \
    --features=-legacy_whole_archive \
    --copt=-fvisibility=hidden \
    --copt=-ffunction-sections \
    --copt=-fdata-sections \
    --copt=-fstack-protector \
    --copt=-Oz \
    --copt=-fomit-frame-pointer \
    --copt=-DABSL_MIN_LOG_LEVEL=2 \
    --linkopt=-Wl,--gc-sections,--strip-all \
    //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar


all the errors is about MAVEN.
```

### Complete Logs

```shell
wangjie@wangjiedeMacBook-Pro mediapipe-master % 
bazel build -c opt --strip=ALWAYS \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    --legacy_whole_archive=0 \
    --features=-legacy_whole_archive \
    --copt=-fvisibility=hidden \
    --copt=-ffunction-sections \
    --copt=-fdata-sections \
    --copt=-fstack-protector \
    --copt=-Oz \
    --copt=-fomit-frame-pointer \
    --copt=-DABSL_MIN_LOG_LEVEL=2 \
    --linkopt=-Wl,--gc-sections,--strip-all \
    //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/0258a53521cfedf5cb80c2b1d4a66c942615de74.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/7d879c8b161085a4374ea481b93a52adb19c0529.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Repository maven instantiated at:
  /Users/wangjie/Downloads/mediapipe-master/WORKSPACE:434:14: in <toplevel>
  /private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/rules_jvm_external/defs.bzl:121:19: in maven_install
Repository rule coursier_fetch defined at:
  /private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/rules_jvm_external/coursier.bzl:1173:33: in <toplevel>
INFO: repository @maven' used the following cache hits instead of downloading the corresponding file.
 * Hash '5c0a0a3ea600f302ee458b30317425dd9632d1ad8882259fcaf4e9b868b2b1ef' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
 * Hash 'af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
 * Hash '076de041cbebc0a1272b84f1e69f6da5df4961847850b95cb3dfa3f776145225' for https://github.com/coursier/coursier/releases/download/v2.0.16/coursier.jar
 * Hash 'a51d36968dcbdeabb3142c6f5cf9b401a65dc3a095f3144bd0c118d5bb192753' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe
If the definition of 'repository @maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/rules_jvm_external/coursier.bzl", line 821, column 13, in _coursier_fetch_impl
		fail("Unable to run coursier: " + exec_result.stderr)
Error in fail: Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
ERROR: /Users/wangjie/Downloads/mediapipe-master/WORKSPACE:434:14: fetching coursier_fetch rule //external:maven: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/rules_jvm_external/coursier.bzl", line 821, column 13, in _coursier_fetch_impl
		fail("Unable to run coursier: " + exec_result.stderr)
Error in fail: Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
INFO: Repository nodejs_darwin_amd64 instantiated at:
  /Users/wangjie/Downloads/mediapipe-master/WORKSPACE:542:18: in <toplevel>
  /private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl:50:31: in node_repositories
  /private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/rules_nodejs/nodejs/repositories.bzl:400:26: in nodejs_register_toolchains
Repository rule node_repositories defined at:
  /private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/rules_nodejs/nodejs/repositories.bzl:374:36: in <toplevel>
INFO: Repository remotejdk11_macos instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:110:6: in <toplevel>
  /private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
  /private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/bazel_tools/tools/jdk/remote_java_repository.bzl:49:17: in remote_java_repository
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository android_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:463:6: in <toplevel>
  /private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository remote_java_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:364:6: in <toplevel>
  /private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: /Users/wangjie/Downloads/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection_android_lib depends on @maven//:com_google_code_findbugs_jsr305 in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
ERROR: /Users/wangjie/Downloads/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection_android_lib depends on @maven//:com_google_flogger_flogger in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
ERROR: /Users/wangjie/Downloads/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection_android_lib depends on @maven//:com_google_flogger_flogger_system_backend in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
ERROR: /Users/wangjie/Downloads/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection_android_lib depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
ERROR: /Users/wangjie/Downloads/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection_android_lib depends on @maven//:androidx_lifecycle_lifecycle_common in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/91f2fc9cda4e9cacd9a77e276566ea10/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar' failed; build aborted: 
INFO: Elapsed time: 1.147s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
igured)
    currently loading: mediapipe/framework ... (2 packages)
    Fetching repository @npm; Restarting.
    Fetching repository @yarn; Restarting.
    Fetching https://nodejs.org/dist/v16.19.0/node-v16.19.0-darwin-x64.tar.gz
    Fetching https://mirror.bazel.build/....19-ca-jdk11.0.15-macosx_x64.tar.gz
    Fetching https://mirror.bazel.build/.../android_tools_pkg-0.27.0.tar.gz
    Fetching https://mirror.bazel.build/.../java/v12.3/java_tools-v12.3.zip
wangjie@wangjiedeMacBook-Pro mediapipe-master % 
bazel build -c opt --strip=ALWAYS \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    --legacy_whole_archive=0 \
    --features=-legacy_whole_archive \
    --copt=-fvisibility=hidden \
    --copt=-ffunction-sections \
    --copt=-fdata-sections \
    --copt=-fstack-protector \
    --copt=-Oz \
    --copt=-fomit-frame-pointer \
    --copt=-DABSL_MIN_LOG_LEVEL=2 \
    --linkopt=-Wl,--gc-sections,--strip-all \
    //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar
```

**Comment by kuaashish** [comment]
@SnoopPanda,

Could you build the AAR example with latest version 0.10.1. Also, MediaPipe support the Bazel version 6.1.1 But we can see the Bazel version 6.1.2 being used. Please try with recommended versions and let us know if you encounter any error. 

Thank you!!

**Comment by SnoopPanda** [comment]
> e Bazel version 6.1.2 being used. Please try with recommended versions and let us know if you encounter any error.

I got the latest ver 0.10.1 and use the .sh to setup android sdk&ndk.
Unfortunately, failed again.
but My colleague who‘s mac did not installed AndroidStudio, just use the .sh file setup sdk&ndk, get the correct result.
Could you please help me find the problem?
Thank you.

here is the log:

wangjie@wangjiedeMacBook-Pro mediapipe-0.10.1 % sh ./setup_android_sdk_and_ndk.sh 
Warning: android_sdk_path (argument 1) is not specified. Fallback to ~/Android/Sdk/
Warning: android_ndk_path (argument 2) is not specified. Fallback to ~/Android/Sdk/ndk-bundle/android-ndk-<NDK_VERSION>/
Warning: ndk_version (argument 3) is not specified. Fallback to r21.
Warning: android_sdk_path is non empty. Installation of the Android SDK will be skipped.
Warning: android_ndk_path is non empty. Android NDK Installation will be ignored.
Set android_ndk_repository and android_sdk_repository in WORKSPACE
Done
wangjie@wangjiedeMacBook-Pro mediapipe-0.10.1 % bazel build -c opt --strip=ALWAYS \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    --fat_apk_cpu=arm64-v8a,armeabi-v7a \
    --legacy_whole_archive=0 \
    --features=-legacy_whole_archive \
    --copt=-fvisibility=hidden \
    --copt=-ffunction-sections \
    --copt=-fdata-sections \
    --copt=-fstack-protector \
    --copt=-Oz \
    --copt=-fomit-frame-pointer \
    --copt=-DABSL_MIN_LOG_LEVEL=2 \
    --linkopt=-Wl,--gc-sections,--strip-all \
    //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
INFO: Repository maven instantiated at:
  /Users/wangjie/Downloads/mediapipe-0.10.1/WORKSPACE:433:14: in <toplevel>
  /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/rules_jvm_external/defs.bzl:105:19: in maven_install
Repository rule coursier_fetch defined at:
  /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/rules_jvm_external/coursier.bzl:1009:33: in <toplevel>
INFO: repository @maven' used the following cache hits instead of downloading the corresponding file.
 * Hash 'babba8a144533f041a4de791d32de00552e31fa56231f241560a2ce6a7a72702' for https://github.com/coursier/coursier/releases/download/v2.0.7/coursier.jar
 * Hash '5c0a0a3ea600f302ee458b30317425dd9632d1ad8882259fcaf4e9b868b2b1ef' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
 * Hash 'af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
 * Hash 'a51d36968dcbdeabb3142c6f5cf9b401a65dc3a095f3144bd0c118d5bb192753' for https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe
If the definition of 'repository @maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/rules_jvm_external/coursier.bzl", line 687, column 13, in _coursier_fetch_impl
		fail("Unable to run coursier: " + exec_result.stderr)
Error in fail: Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
ERROR: /Users/wangjie/Downloads/mediapipe-0.10.1/WORKSPACE:433:14: fetching coursier_fetch rule //external:maven: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/rules_jvm_external/coursier.bzl", line 687, column 13, in _coursier_fetch_impl
		fail("Unable to run coursier: " + exec_result.stderr)
Error in fail: Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
INFO: Repository android_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:463:6: in <toplevel>
  /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository remote_java_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:364:6: in <toplevel>
  /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository remotejdk11_macos instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:110:6: in <toplevel>
  /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
  /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/bazel_tools/tools/jdk/remote_java_repository.bzl:49:17: in remote_java_repository
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: /Users/wangjie/Downloads/mediapipe-0.10.1/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection_android_lib depends on @maven//:com_google_code_findbugs_jsr305 in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
ERROR: /Users/wangjie/Downloads/mediapipe-0.10.1/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection_android_lib depends on @maven//:com_google_flogger_flogger in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
ERROR: /Users/wangjie/Downloads/mediapipe-0.10.1/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection_android_lib depends on @maven//:com_google_flogger_flogger_system_backend in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
ERROR: /Users/wangjie/Downloads/mediapipe-0.10.1/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection_android_lib depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
ERROR: /Users/wangjie/Downloads/mediapipe-0.10.1/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection_android_lib depends on @maven//:androidx_lifecycle_lifecycle_common in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:80: "execvp(/private/var/tmp/_bazel_wangjie/0ad47d0a57546567fb20cfa0e413c769/external/maven/@@HOMEBREW_JAVA@@/bin/java, ...)": No such file or directory
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_face_detection.aar' failed; build aborted: 
INFO: Elapsed time: 2.149s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (52 packages loaded, 7386 targets configured)
    Fetching repository @local_config_xcode; Fetching the default Xcode version
    Fetching https://mirror.bazel.build/bazel_android_tools/android_tools_pkg-0.27.0.tar.gz
    Fetching https://mirror.bazel.build/bazel_java_tools/releases/java/v12.3/java_tools-v12.3.zip
    Fetching https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu11.56.19-ca-jdk11.0.15-macosx_x64.tar.gz

**Comment by kuaashish** [comment]
Hi @SnoopPanda,

Could you please confirm if you still require assistance with this matter? If so, we would like to inform you that AAR solutions for app development are no longer under maintenance, and we anticipate that the reported issue will not be resolved.

Instead, we recommend utilizing our new Face Detection Task API. This API is an enhanced version of our legacy Face Detection Solution. Further details can be found [here](https://developers.google.com/mediapipe/solutions/guide#legacy).

Furthermore, please refer to the associated Overview [documentation](https://developers.google.com/mediapipe/solutions/vision/face_detector) and implementation instructions for Android on this [page](https://developers.google.com/mediapipe/solutions/vision/face_detector/android). 

Should you encounter any challenges during the implementation process, we kindly request you to report them to us promptly for further assistance.

Thank you!
