### ISSUE TITLE
Pose Landmarks x and y: Landmark coordinates normalized to [0.0, 1.0] out of range

### ISSUE THREAD

**Issue by bhomaidan1990** [google/mediapipe#4598]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Ubunut 20.04

### Programming Language and version

Python 3.8.10

### MediaPipe version

0.10.1

### Solution

Pose landmark detection

### Describe the actual behavior

I'm getting x,y values of the landmark out of the [0, 1] range described [here](https://github.com/google/mediapipe/blob/master/docs/solutions/pose.md#pose_landmarks)

### Describe the expected behaviour

To get x,y values of the landmark in the range [0, 1]

### Standalone code/steps you may have used to try to get what you need

```shell
#!/usr/bin/env python3

import numpy as np
import cv2
import mediapipe as mp
import time

class HumanPoseDetection:
    def __init__(self):
        # TODO: change the path
        model_path = "/home/user/models/pose_landmarker_full.task"
        BaseOptions = mp.tasks.BaseOptions
        self.PoseLandmarker = mp.tasks.vision.PoseLandmarker
        PoseLandmarkerOptions = mp.tasks.vision.PoseLandmarkerOptions
        self.result = mp.tasks.vision.PoseLandmarkerResult
        VisionRunningMode = mp.tasks.vision.RunningMode       

        self.options = PoseLandmarkerOptions(
            base_options=BaseOptions(model_asset_path=model_path),
            running_mode=VisionRunningMode.LIVE_STREAM,
            result_callback=self.callback
            )
        
    def callback(self, result, output_image, timestamp_ms):
        if(result.pose_landmarks):
            self.result = result.pose_landmarks[0]
            for idx, elem in enumerate(self.result):
                if(0 <= elem.x <= 1 and 0 <= elem.y <= 1):
                    pass
                else:
                    print("Warning out of range values: {}".format(elem))

    def detect_pose(self):
        cap = cv2.VideoCapture(0)
        with self.PoseLandmarker.create_from_options(self.options) as landmarker:
            while cap.isOpened():
                _, image = cap.read()
                image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                image = cv2.resize(image, (224, 224)) 
                mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image)
                frame_timestamp_ms = int(time.time() * 1000)
                landmarker.detect_async(mp_image, frame_timestamp_ms)

if __name__=="__main__":
    HPD_ = HumanPoseDetection()
    HPD_.detect_pose()
```

**Comment by kuaashish** [comment]
@bhomaidan1990,

Pose solution which you are using are legacy solution now, We have already upgraded the pose landmark API as guided [here](https://developers.google.com/mediapipe/solutions/guide) And ended support for the legacy pose solution. 

We recommend you to try out new upgraded solution([Pose Python Example](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python)), Which will provide a superset of capabilities available in the legacy solutions. 

Also, Please let us know if you encounter the similar error in upgraded Pose solution. Thank you!

**Comment by bhomaidan1990** [comment]
@kuaashish  I'm using the new upgraded solution and not the legacy one ! But there is no documentation provided for the `landmark` values, so I assumed the old documentation!

**Comment by bhomaidan1990** [comment]
@kuaashish  I have updated the Solution to `Pose landmark detection` instead of the legacy pose, still the Landmark coordinates are not normalized to the range `[0.0, 1.0]`

**Comment by galharth** [comment]
+1

**Comment by schmidt-sebastian** [comment]
Can you provide an example value that was returned from the graph?

**Comment by kinaryml** [comment]
@bhomaidan1990 Could you give this utility a try in your example and let me know if it fixes the issue?

https://github.com/google/mediapipe/blob/37b68714b8c1e9f2ec22ff91c0ef7bb4c10227b7/mediapipe/python/solutions/drawing_utils.py#L49

I believe this was used with the legacy Pose Landmarker solution too.

**Comment by kinaryml** [comment]
Oh and I believe there was already a TODO in the utility here (for out-of-bound image coordinates)

It's possible to apply a fix/workaround here.

https://github.com/google/mediapipe/blob/37b68714b8c1e9f2ec22ff91c0ef7bb4c10227b7/mediapipe/python/solutions/drawing_utils.py#L61

**Comment by kinaryml** [comment]
I'd suggest clamping or wrapping the values. Use whatever works best for your usecase. 

Example of clamping:

```python
def clamp(value):
    return max(0.0, min(1.0, value))
```

**Comment by bhomaidan1990** [comment]
@schmidt-sebastian

> Can you provide an example value that was returned from the graph?
```
NormalizedLandmark(x=0.3442286252975464, y=1.663205623626709, z=0.6675763130187988, visibility=0.0005908278399147093, presence=2.2982736481935717e-05)
NormalizedLandmark(x=0.525449275970459, y=1.726546287536621, z=0.16685475409030914, visibility=0.0006492086104117334, presence=1.1043830454582348e-05)
NormalizedLandmark(x=0.351003497838974, y=1.7091314792633057, z=0.6834827661514282, visibility=0.0016230528708547354, presence=1.9313172742840834e-05)
NormalizedLandmark(x=0.42790234088897705, y=1.763134241104126, z=-0.2120414823293686, visibility=0.0004914221935905516, presence=1.980218439712189e-05)
NormalizedLandmark(x=0.3111097812652588, y=1.7536125183105469, z=0.3353509306907654, visibility=0.0009863366140052676, presence=3.027161983482074e-05)
NormalizedLandmark(x=0.5848674774169922, y=1.0461585521697998, z=-0.22029514610767365, visibility=0.2053297609090805, presence=0.026988795027136803)
NormalizedLandmark(x=0.4060169458389282, y=1.0328614711761475, z=0.22312480211257935, visibility=0.2098243534564972, presence=0.026073340326547623)
```

@kinaryml 

> clamping or wrapping the values

This suggestion while it works, it yields inacurate results as all invisible landmarks will be at the image border, which might distort the pose and cause some issues for further pose processing, e.g pose forcasting.

**Comment by kinaryml** [comment]
> @schmidt-sebastian
> 
> > Can you provide an example value that was returned from the graph?
> 
> ```
> NormalizedLandmark(x=0.3442286252975464, y=1.663205623626709, z=0.6675763130187988, visibility=0.0005908278399147093, presence=2.2982736481935717e-05)
> NormalizedLandmark(x=0.525449275970459, y=1.726546287536621, z=0.16685475409030914, visibility=0.0006492086104117334, presence=1.1043830454582348e-05)
> NormalizedLandmark(x=0.351003497838974, y=1.7091314792633057, z=0.6834827661514282, visibility=0.0016230528708547354, presence=1.9313172742840834e-05)
> NormalizedLandmark(x=0.42790234088897705, y=1.763134241104126, z=-0.2120414823293686, visibility=0.0004914221935905516, presence=1.980218439712189e-05)
> NormalizedLandmark(x=0.3111097812652588, y=1.7536125183105469, z=0.3353509306907654, visibility=0.0009863366140052676, presence=3.027161983482074e-05)
> NormalizedLandmark(x=0.5848674774169922, y=1.0461585521697998, z=-0.22029514610767365, visibility=0.2053297609090805, presence=0.026988795027136803)
> NormalizedLandmark(x=0.4060169458389282, y=1.0328614711761475, z=0.22312480211257935, visibility=0.2098243534564972, presence=0.026073340326547623)
> ```
> 
> @kinaryml
> 
> > clamping or wrapping the values
> 
> This suggestion while it works, it yields inacurate results as all invisible landmarks will be at the image border, which might distort the pose and cause some issues for further pose processing, e.g pose forcasting.

Yep that's true and it's only fixable in the C++ layer.

**Comment by galharth** [comment]
Any update ? thanks :)

**Comment by Sorokopudov** [comment]
I have the same problem - there are coordinates that go beyond [0:1] and because of this, some skeletons are drawn incorrectly

**Comment by vhalis** [comment]
I have found that coordinates go out of range when the keypoint is offscreen. If you don't want that, use `min_pose_detection_confidence` in your `PoseLandmarkerOptions`.

More detail in my answer on the related [StackOverflow](https://stackoverflow.com/questions/76627289/mediapipe-pose-landmarks-out-of-range-0-1/77354932#77354932).
