### ISSUE TITLE
FaceMesh model not working on iOS browsers

### ISSUE THREAD

**Issue by bilalahmed24** [google/mediapipe#4604]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

iOS 16, iOS 15, iOS 14

### Mobile device if the issue happens on mobile device

iPhone 13 Pro Max, iPhone X, iPhone 14 Plus, iPad 10.9

### Browser and version if the issue happens on browser

Safari 16.5, Chrome 114.0.5735.199

### Programming Language and version

JavaScript

### MediaPipe version

0.10.1

### Solution

FaceMesh

### Describe the actual behavior

```shell
Model isn't working on any iOS device, let it be iPhone or iPad but is working on MacOS and safari. Issue seems to be related with iOS.

Simply go to:
https://mediapipe-studio.webapps.google.com/demo/face_landmarker
```

### Describe the expected behaviour

```shell
faceMesh model should detect coordinates as it does on other OS
```

### Standalone code/steps you may have used to try to get what you need

```shell
Simply go to:
https://mediapipe-studio.webapps.google.com/demo/face_landmarker
```

**Comment by kuaashish** [comment]
@bilalahmed24,

Thank you for raising this issue, We are able to reproduce the issue And can see Pose L/andmarker Web demo is not working in iOS browsers. We are forwarding issue internally and let you know once any update becomes available.

**Comment by bilalahmed24** [comment]
@kuaashish faceMesh landmarks model isn't working as well. I am facing same issue in the webApp that I am working on which uses faceMesh model.

**Comment by schmidt-sebastian** [comment]
Our Web Studio team is looking at this.

**Comment by schmidt-sebastian** [comment]
This should be fixed now.
