### ISSUE TITLE
async detection in JavaScript

### ISSUE THREAD

**Issue by hschwane** [google/mediapipe#4608]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

all platforms

### Task name (e.g. Image classification, Gesture recognition etc.)

FaceLandmarker

### Programming Language and version (e.g. C++, Python, Java)

JavaScript

### Describe the actual behavior

```shell
detect() and detectForVideo() run synchronously, blocking the main thread until detection is done.
```

### Describe the expected behaviour

```shell
async versions of detect() and detectForVideo() should exist, as they do (according to the documentation) in the java and python versions of the task. Also, in the older FaceMesh solutions API, a async version (using a callback) was the default.
```

### Standalone code/steps you may have used to try to get what you need

```shell
face landmark task: https://codepen.io/mediapipe-preview/pen/OJBVQJm
old face mesh solution: https://codepen.io/mediapipe/pen/KKgVaPJ
```

### Other info / Complete Logs

```shell
Also it seems that at least when using chrome for Android to access the page, detecting landmarks the new task takes about 70% longer than in the old FaceMesh solution. However I am not an expert at all in profiling web apps, so I might be doing something else wrong as well.
```

**Comment by kuaashish** [comment]
Hello @hschwane,

Could you please elaborate your query with complete details, Also provide the reproducible steps you are following to reproduce the issue from our end. Thank you!!

**Comment by FishWoWater** [comment]
@kuaashish @hschwane 
Can we expect an async typescript version of FaceLandmarker's detection? The new FaceLandmarker API `https://codepen.io/mediapipe-preview/pen/OJBVQJm` seems to run a bit slower than the old facemesh(the face template can't follow the live stream person face as smoothly as it did in facemesh). The reason could be: synchronous detection blocks the render thread, which in turn slowers down the render fps. Another possible reason is the extended pipeline to estimate blendshapes.

**Comment by hschwane** [comment]
Hey, sorry for not getting back here sooner. 
@kuaashish I do not have any specific code or issue to reproduce I could share. Simply profiling the examples / codepens for old an new FaceLandmarker shows the difference in performance. And the lack of an async detection function can be seen in the API documentation.

@FishWoWater Yes that is exactly what I observed and what I was wondering as well. Thanks for specifying.
