### ISSUE TITLE
mediapipe 0.10.0 version is not supported ubuntu 18.04 OS?

### ISSUE THREAD

**Issue by psw7420fusion** [google/mediapipe#4609]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Linux ubuntu 18.04

### Programming Language and version

python

### MediaPipe version

0.10.0

### Solution

Gesture

### Describe the actual behavior

```shell
my development env is ubuntu 18.04 with python 3.7 & pip 22 version
when i try install mediapipe by using pip
there was only 0.8.9 version available

i want to install mediapipe 0.10.0 version
is not support on ubuntu 18.0.4?
```

### Describe the expected behaviour

```shell
my development env is ubuntu 18.04 with python 3.7 & pip 22 version
when i try install mediapipe by using pip
there was only 0.8.9 version available

i want to install mediapipe 0.10.0 version
is not support on ubuntu 18.0.4?
```

### Standalone code/steps you may have used to try to get what you need

```shell
my development env is ubuntu 18.04 with python 3.7 & pip 22 version
when i try install mediapipe by using pip
there was only 0.8.9 version available

i want to install mediapipe 0.10.0 version
is not support on ubuntu 18.0.4?
```

### Other info / Complete Logs

```shell
my development env is ubuntu 18.04 with python 3.7 & pip 22 version
when i try install mediapipe by using pip
there was only 0.8.9 version available

i want to install mediapipe 0.10.0 version
is not support on ubuntu 18.0.4?
```

**Comment by kuaashish** [comment]
@psw7420fusion,

We only support the python version 3.8 to 3.11 as described [here](https://developers.google.com/mediapipe/solutions/setup_python). Please build using the supported versions and let us know if this works for you. Thank you!!

**Comment by kuaashish** [comment]
@psw7420fusion,

Could you please update the status of the above. Thank you
