### ISSUE TITLE
MnasNet classification using TfliteInferenceCalculator

### ISSUE THREAD

**Issue by PrinceP** [google/mediapipe#461]
Models input is not getting loaded properly. The MnasNet is trained using Auto ML.  Attached is the sample graph used and the tflite model.
The tflite model is renamed to .zip for upload error.

[hand_gesture_gpu.txt](https://github.com/google/mediapipe/files/4209593/hand_gesture_gpu.txt)

[mobile_net.zip](https://github.com/google/mediapipe/files/4209594/mobile_net.zip)

**Comment by PrinceP** [comment]
Hi @fanzhanggoogle, is there any issue with tflite calculator. Is pre-processing fine?

**Comment by fanzhanggoogle** [comment]
Hi, I don't see any reason it won't work. It should be fine at least on CPU unless you have custom TFlite ops. On GPU it might be trickier if some ops are not support. Could you share your log/error so that I can provide some guidance?

**Comment by PrinceP** [comment]
The code doesn't crash. 
For CPU, I have to check and get back. 
For GPU, the tflite_inference_calculator.cc gets stuck at the following code
`      
if (gpu_input_) {
       
// Get input image sizes.
        const auto& input_indices = interpreter_->inputs();
        gpu_data_in_.resize(input_indices.size());
        for (int i = 0; i < input_indices.size(); ++i) {
          const TfLiteTensor* tensor = interpreter_->tensor(input_indices[0]);
          gpu_data_in_[i] = absl::make_unique<GPUData>();
          gpu_data_in_[i]->elements = 1;
          for (int d = 0; d < tensor->dims->size; ++d) {
//              LOG(INFO) << "Tensors " << i << " - " <<  d << " -  " <<tensor->dims->data[d]  << std::endl;
            gpu_data_in_[i]->elements *= tensor->dims->data[d];
          }
          // Create and bind input buffer.
          RET_CHECK_CALL(
                  ::tflite::gpu::gl::CreateReadWriteShaderStorageBuffer<float>(
                          gpu_data_in_[i]->elements, &gpu_data_in_[i]->buffer));
          RET_CHECK_EQ(TfLiteGpuDelegateBindBufferToTensor(
                  delegate_, gpu_data_in_[i]->buffer.id(),
                  interpreter_->inputs()[i]),
                       kTfLiteOk);
        }
      }
`

**Comment by PrinceP** [comment]
I was able to run the Efficient net on the pipeline. The fp32 model works fine.
