### ISSUE TITLE
Mediapipe Hand Detection Limitation - Failure to Detect All Hands in the image

### ISSUE THREAD

**Issue by lakshmishreea122003** [google/mediapipe#4612]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Windows 11

### Programming Language and version

Python

### MediaPipe version

0.10.1

### Solution

Improve hand detection in Mediapipe Hands module for accurate detection and landmark extraction of all hands in the image.

### Describe the actual behavior

```shell
I provided an image containing four hands, but the hand-detection process only identified three out of the four hands. As a result, when I attempted to count the number of hands in the image, it incorrectly provided a count of three instead of four.
```

### Describe the expected behaviour

```shell
The Mediapipe Hands module should accurately detect and provide landmarks for all hands present in the image, regardless of the number of hands.
```

### Standalone code/steps you may have used to try to get what you need

```shell
 Link to Jupiter-notebook = https://github.com/lakshmishreea122003/mediapipe-hand-detect/blob/main/Untitled1.ipynb  
```

**Comment by kuaashish** [comment]
@lakshmishreea122003,

Detection of multiple hands in a image is out of our scope. You can find the same information available in page 3 [model card](https://storage.googleapis.com/mediapipe-assets/Model%20Card%20Hand%20Tracking%20(Lite_Full)%20with%20Fairness%20Oct%202021.pdf) OUT-OF-SCOPE APPLICATIONS as guided below:

```
Not appropriate for:
● Counting the number of
hands in a crowd
```

Thank you!!

**Comment by lakshmishreea122003** [comment]
I still have a doubt if Mediapipe is Not appropriate for Counting the number of hands in a crowd, then how can it detect and count 3 hands, but unable to count 4?

**Comment by kuaashish** [comment]
@lakshmishreea122003,

Seems Image which you are feeding into the model contains the occluded hands image. As already guided, In the page 3 model card, OUT-OF-SCOPE APPLICATIONS section:

> Predicting hand landmarks
> with gloves or occlusions.
> For example.....................

Occlusions is out of our scope. However, I could successfully able to reproduce the issue with exposed hands without any error, Please find relevant [gist](https://colab.sandbox.google.com/drive/1JEzjsF-mcRDQ65OKrB4Y75JC6mG8Tc6M?resourcekey=0-CC88a0IuI_28XEnG89ftSw) here. 

Please feed image with exposed hands without occlusions and let us know if you encounter the similar behaviour. Thank you

**Comment by lakshmishreea122003** [comment]
I do get your point. 
But why do I get the below results for the [img](https://i.kinja-img.com/gawker-media/image/upload/s--A99mnFf8--/c_fill,fl_progressive,g_center,h_900,q_80,w_1600/17r2nhmg9n26mjpg.jpg)? I tried with the code that you provided.
![imgg](https://github.com/google/mediapipe/assets/117621286/956c565d-1328-4e9b-ae37-7f8c001ced23)

**Comment by kuaashish** [comment]
@lakshmishreea122003,

Could you please elaborate your query with complete use case you are trying to archive with the hand detection model?

**Comment by lakshmishreea122003** [comment]
I just want to make a project to detect and count the number of hands in the image using Mediapipe. [HERE](https://github.com/lakshmishreea122003/mediapipe-hand-detect/blob/main/Untitled1.ipynb ) is the link to the project. My doubt is if the hand detection model can detect all the hands in the image you provided in [this](https://colab.sandbox.google.com/gist/kuaashish/41261b504e12e0ebcfd39e7b59bb0abd/untitled55.ipynb) then why it is unable to detect all the hands in [this](https://github.com/google/mediapipe/issues/4612#:~:text=results%20for%20the-,img,-%3F%20I%20tried%20with) image that I used.

**Comment by kuaashish** [comment]
@lakshmishreea122003,

You are currently utilising the legacy MediaPipe hand solution, which is no longer maintained by our team. We kindly advise you to refer to our [guide](https://developers.google.com/mediapipe/solutions/guide#legacy), where it is indicated that the hand solution has been upgraded to the new Hands API.

We earnestly request that you transition to our new Hand Task API as outlined in the provided documentation [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/python). Additionally, you can find a [code example](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/hand_landmarker/python/hand_landmarker.ipynb) in the same resource for your reference. Also, we request please report back if you observe similar behaviour in the upgraded task API. Thank you
