### ISSUE TITLE
Documentation for building posetracking iOS app using mediapipe + swift 

### ISSUE THREAD

**Issue by RajaJeeva** [google/mediapipe#4613]
### Description of issue (what needs changing)

I couldn't find any guidelines/documentation for building posetracking iOS app using mediapipe + swift 

### Clear description

Documentation for building posetracking iOS app using mediapipe + swift

**Comment by RajaJeeva** [comment]
I Apologise If I raised this issue in the wrong category.
I am trying to build an ios application using Swift language for pose tracking (using mediapipe). I have tried using swift_ios_library but nothing worked. Always getting some errors.
It would be very helpful if we have any documentation or a sample app for pose tracking using Mediapipe+swift language.

**Comment by kuaashish** [comment]
Hello @schmidt-sebastian,

Could you please help out here? Thank you!

**Comment by RajaJeeva** [comment]
Thank you @kuaashish  ,  
Hi @schmidt-sebastian,  kindly let me know if you need more details regarding this.

**Comment by RajaJeeva** [comment]
Hi @kuaashish / @schmidt-sebastian I would much appreciate it if you could share any reference..

**Comment by schmidt-sebastian** [comment]
This will be added here: https://developers.google.com/mediapipe/solutions/vision/pose_landmarker

We are currently working on this.

**Comment by dprichards-carespace** [comment]
@schmidt-sebastian, can you provide a status on work being done to make mediapipe supporting with Swift? We are developing an app this will really help us out. Any updates on timing you can provide would be greatly appreciated.
