### ISSUE TITLE
Gesture Recognition Python vs JS Perfomances

### ISSUE THREAD

**Issue by RiccardoMaistri** [google/mediapipe#4620]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Linux Ubuntu 20

### MediaPipe Tasks SDK version

0.10.2

### Task name (e.g. Image classification, Gesture recognition etc.)

Gesture Recognition

### Programming Language and version (e.g. C++, Python, Java)

Python3.8

### Describe the actual behavior

```shell
Hi, I am noticing that the performance on the Gesture Recognition Task Demo (both demo and JS example code) on MediaPipe Website is slightly better than the Python version (CPU) in term of detection. At qualitative level I can notice that the web demo can recognize hands at farther distance.
I run the experimen with the same camera, same resolution.
Am I missing something?

I provide the code used for the inference on python
```

### Describe the expected behaviour

```shell
I expect to have similar performances, I am worried about the distance at which the hands are detected/recognized
```

### Standalone code/steps you may have used to try to get what you need

```shell
options = GestureRecognizerOptions(
    base_options=BaseOptions(
        model_asset_path="/home/riccardo/ws/services/detection-service/models/gesture_recognizer.task"),
    running_mode=VisionRunningMode.LIVE_STREAM, num_hands=2,
    result_callback=print_result)

timestamp = 0
with GestureRecognizer.create_from_options(options) as recognizer:
    # The recognizer is initialized. Use it here.
    while video.isOpened():
        # Capture frame-by-frame
        ret, frame = video.read()

        if not ret:
            print("Ignoring empty frame")
            break

        timestamp += 1
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=frame)
        # Send live image data to perform gesture recognition
        # The results are accessible via the `result_callback` provided in
        # the `GestureRecognizerOptions` object.
        # The gesture recognizer must be created with the live stream mode.
        recognizer.recognize_async(mp_image, timestamp)
        # Uncomment for video output
        ann = draw_landmarks_on_image_hand(mp_image, out)
        cv2.imshow('Frame', ann)
        cv2.waitKey(1)

        if cv2.waitKey(5) & 0xFF == 27:
            break

video.release()
cv2.destroyAllWindows()
```

**Comment by kuaashish** [comment]
@RiccardoMaistri,

This behaviour is expected, Both platform supports the different graph structure. Python uses the cpu-graph and JavaScript uses gpu-graph, Performance will be slightly better compare to other one. Thank you

**Comment by RiccardoMaistri** [comment]
> 
Does python support gpu-graph?

**Comment by RiccardoMaistri** [comment]
> @RiccardoMaistri,
> 
> This behaviour is expected, Both platform supports the different graph structure. Python uses the cpu-graph and JavaScript uses gpu-graph, Performance will be slightly better compare to other one. Thank you

Does python support gpu-graph?

**Comment by RiccardoMaistri** [comment]
> @RiccardoMaistri,
> 
> This behaviour is expected, Both platform supports the different graph structure. Python uses the cpu-graph and JavaScript uses gpu-graph, Performance will be slightly better compare to other one. Thank you

Thanks for info, could you provide me a link or a guide to install and build mediapipe with gpu support on Python?

Thanks in advance!

**Comment by RiccardoMaistri** [comment]
One thing that really blow my mind is that if I use mediapipe legacy solution (mp.solutions.hands), the performances are way better

```
import cv2
import mediapipe as mp

mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands


def process_hand_landmarks(image):
    with mp_hands.Hands(static_image_mode=True, max_num_hands=2, min_detection_confidence=0.5) as hands:
        # Convert the image to RGB for processing
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        # Process the image
        results = hands.process(image_rgb)
        # Check for hand landmarks
        if results.multi_hand_landmarks:
            for hand_landmarks in results.multi_hand_landmarks:
                # Draw the landmarks on the image
                mp_drawing.draw_landmarks(image, hand_landmarks, mp_hands.HAND_CONNECTIONS)


cap = cv2.VideoCapture(0)  # Change the argument to the appropriate camera index
while True:
    ret, frame = cap.read()
    if not ret:
        break
    process_hand_landmarks(frame)
    cv2.imshow('Hand Gestures', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
```

**Comment by kuaashish** [comment]
@RiccardoMaistri,

Could you please share the detailed performance issue which you are observing between the legacy solution and our upgraded new solution that will be better for us to bring out to internal notice and share the possible reason. Thank you

**Comment by RiccardoMaistri** [comment]
> @RiccardoMaistri,
> 
> Could you please share the detailed performance issue which you are observing between the legacy solution and our upgraded new solution that will be better for us to bring out to internal notice and share the possible reason. Thank you

Uploading output-1_q2FhDnqw.mp4…
Here is an output video comparing hand keypoint legacy vs hands keypoint (mediapipe 0.10.2), both on CPU

**Comment by schmidt-sebastian** [comment]
cc @lu-wang-g

**Comment by kuaashish** [comment]
@RiccardoMaistri,

The model performance largely depends on the target distance. In the legacy solution, it support short range(targeting at ~2 meter) or long range (targeting at ~5 meter) models. We are working on to support these models in the new API as well, but currently, the new API only support the short range model. Thank you

**Comment by kuaashish** [comment]
Hello @RiccardoMaistri,

Could you please let us know we can mark this issue as resolved and close the status if now no longer is issue from your end? Thank you!

**Comment by RiccardoMaistri** [comment]
Solved, I wiil look forward future updates because I was interested in longer range!

Thanks

> Hello @RiccardoMaistri,
> 
> Could you please let us know we can mark this issue as resolved and close the status if now no longer is issue from your end? Thank you!

**Comment by wolfiex** [comment]
> @RiccardoMaistri,
> 
> We are working towards publish the official documentation Asap. Meanwhile, Please check this [instructions](https://github.com/riverzhou/mediapipe) to build python gpu support. Thank you

Is there a M2 Mac version, or similar alternative available?
