### ISSUE TITLE
MobilenetV2 not working on gpu on android

### ISSUE THREAD

**Issue by pixml27** [google/mediapipe#4624]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Android >=11

### Mobile device if the issue happens on mobile device

Redmi Note 8,Galaxy M12, Nokia XR 20, OnePlus 11 pro, galaxy A50

### Programming Language and version

C++, 

### MediaPipe version

0.8.10

### Solution

android .aar

### Android Studio, NDK, SDK versions (if issue is related to building in Android environment)

Android Studio Dolphin | 2021.3.1 Patch 1, SDK 34, NDK 25

### Describe the actual behavior

```shell
Slow inference for ml models on android 
Tracing shows that the inference started with the CPU delegate, although the graph option is delegate { gpu {} }
```

### Describe the expected behaviour

```shell
Quicker inference for ml models on android 
Tracing shows that the inference running with the GPU delegate, although the graph option is delegate { gpu {} }
```

### Standalone code/steps you may have used to try to get what you need

```shell
node {
   calculator: "InferenceCalculator"
   input_stream: "TENSORS:cropped_image_tensor"
   output_stream: "TENSORS:class_tensors"
   options: {
     [mediapipe.InferenceCalculatorOptions.ext] {
       model_path: "mobilenetv2.tflite"
       delegate { gpu {} }
     }
   }
}
```

### Other info / Complete Logs

```shell
Hi all!

We made a custom graph on a mediapipe and run it on iOS and Android 
Inside it, we make inference of two models - yolov5 nano and mobilenetv2
FPS on iPhones is noticeably higher than on devices running Android
With your tracing instructions (we ran our applications on the same data), we noticed that if on iOS model inference takes <10% of the time, then on Android it is 20-50%
On iPhones, we can definitely see that the Metal delegate connects and infers fairly quickly.

However, it seems to us that, on Android, just all calculations for neural networks are performed on the CPU instead of the GPU (regardless of which delegates we set - we tried gpu, tflite, nnapi and even wrote our own calculator that connects tflitegpuv2)

We tested on different phones: Redmi Note 8, Galaxy M12, Nokia XR 20, OnePlus 11 pro, galaxy A50
If yolov5 really does not work on the gpu delegate (some problems with OpenGL), then on the tflitegpuv2 delegate it turns on and works without errors (the logs say that OpenCL was successfully connected), but the increase in speed relative to the tflite delegate is not noticeable at all 
With mobilentV2 the situation is even stranger, it works both on the gpu{} delegate and on tflitegpuv2, the speeds are about the same, but when we turn on the gpu delegate, and upload the trace file to the https://viz.mediapipe service. dev/ , it shows what it really is... a CPU delegate! (I will add screenshot below)

As a result, we are almost sure that on android inference is performed on the CPU

At the same time, it is not possible to see the GPU load of the phone through Android Studio (I googled that they removed this support), and the Android GPU Inspector supports too few phones. And if we enable GPUWatch on the phone, it shows 50-80% GPU load even if we just use one ImageTransformationCalculator

The questions are: 
1. Is there anything the community knows about such problems (for simplicity, we can focus purely on mobilenetv2 - why does it end up running on the cpu and not the gpu)?
2. Can you advise how to correctly watch GPU loading for Android smartphones (we are rather ML developers and do not have sufficient knowledge in this area)

P.S. If necessary, I can make an abstract graph that works with mobilenetv2 and shows that it works much faster on ios than on android, but it will take me a while
```

**Comment by pixml27** [comment]
Here is the difference between similar calculators with a mobilenetМ2 classifier, and here it is also noticeable that for some reason in the first case the GPU delegate did not turn on
<img width="1055" alt="Снимок экрана 2023-07-19 в 17 09 17" src="https://github.com/google/mediapipe/assets/38530905/8ab2af0b-4c84-4739-8bc3-9be655c05e83">
<img width="1045" alt="Снимок экрана 2023-07-19 в 18 11 11" src="https://github.com/google/mediapipe/assets/38530905/fe74fefc-f6aa-456f-97fd-432792d13569">

**Comment by kuaashish** [comment]
@pixml27,

Thank you for raising this issue. We are forwarding to correct owner, Hope we will receive possible cause of issue you are looking.

**Comment by gkarpiak** [comment]
@pixml27, considering you configured `delegate { gpu {} }` and still see `InferenceCalculatorCpu` running, there's a chance that `gpu` implementations are not registered. (E.g. you could be building your Android apps disabling OpenGL compute for MediaPipe).

Here's the code https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tensor/inference_calculator.cc#L38-L75 where implementation selection and check happens.

**Comment by kuaashish** [comment]
@pixml27,

Could you please go through the [above](https://github.com/google/mediapipe/issues/4624#issuecomment-1659082351) comment. Thank you
