### ISSUE TITLE
mediapipe model maker error Colab

### ISSUE THREAD

**Issue by easyparkingplace** [google/mediapipe#4625]
I need you help, I have error whith  comand in colab:

pip install mediapipe-model-maker or pip install mediapipe-model-maker --user or !pip install mediapipe-model-maker 

Collecting mediapipe-model-maker
  Downloading mediapipe_model_maker-0.2.0-py3-none-any.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.5/117.5 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from mediapipe-model-maker) (1.4.0)
Collecting mediapipe>=0.10.0 (from mediapipe-model-maker)
  Obtaining dependency information for mediapipe>=0.10.0 from https://files.pythonhosted.org/packages/a3/4f/debe59547831963b4d33a28cae68cd53642ca3dd895510e42bad9b50ed6b/mediapipe-0.10.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading mediapipe-0.10.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from mediapipe-model-maker) (1.22.4)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (from mediapipe-model-maker) (4.7.0.72)
Requirement already satisfied: tensorflow>=2.10 in /usr/local/lib/python3.10/dist-packages (from mediapipe-model-maker) (2.12.0)
Requirement already satisfied: tensorflow-datasets in /usr/local/lib/python3.10/dist-packages (from mediapipe-model-maker) (4.9.2)
Requirement already satisfied: tensorflow-hub in /usr/local/lib/python3.10/dist-packages (from mediapipe-model-maker) (0.14.0)
Collecting tf-models-official==2.11.6 (from mediapipe-model-maker)
  Downloading tf_models_official-2.11.6-py2.py3-none-any.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 28.4 MB/s eta 0:00:00
Requirement already satisfied: Cython in /usr/local/lib/python3.10/dist-packages (from tf-models-official==2.11.6->mediapipe-model-maker) (0.29.36)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from tf-models-official==2.11.6->mediapipe-model-maker) (8.4.0)
Requirement already satisfied: gin-config in /usr/local/lib/python3.10/dist-packages (from tf-models-official==2.11.6->mediapipe-model-maker) (0.5.0)
Requirement already satisfied: google-api-python-client>=1.6.7 in /usr/local/lib/python3.10/dist-packages (from tf-models-official==2.11.6->mediapipe-model-maker) (2.84.0)
Collecting immutabledict (from tf-models-official==2.11.6->mediapipe-model-maker)
  Obtaining dependency information for immutabledict from https://files.pythonhosted.org/packages/63/24/2d70ce3bca941be9d81e7e701918b5eb4655e74f5ce7453d3fb6760edfa3/immutabledict-2.2.5-py3-none-any.whl.metadata
  Downloading immutabledict-2.2.5-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: kaggle>=1.3.9 in /usr/local/lib/python3.10/dist-packages (from tf-models-official==2.11.6->mediapipe-model-maker) (1.5.15)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from tf-models-official==2.11.6->mediapipe-model-maker) (3.7.1)
Requirement already satisfied: oauth2client in /usr/local/lib/python3.10/dist-packages (from tf-models-official==2.11.6->mediapipe-model-maker) (4.1.3)
Requirement already satisfied: opencv-python-headless in /usr/local/lib/python3.10/dist-packages (from tf-models-official==2.11.6->mediapipe-model-maker) (4.8.0.74)
Requirement already satisfied: pandas>=0.22.0 in /usr/local/lib/python3.10/dist-packages (from tf-models-official==2.11.6->mediapipe-model-maker) (1.5.3)
Requirement already satisfied: psutil>=5.4.3 in /usr/local/lib/python3.10/dist-packages (from tf-models-official==2.11.6->mediapipe-model-maker) (5.9.5)
Requirement already satisfied: py-cpuinfo>=3.3.0 in /usr/local/lib/python3.10/dist-packages (from tf-models-official==2.11.6->mediapipe-model-maker) (9.0.0)
Requirement already satisfied: pycocotools in /usr/local/lib/python3.10/dist-packages (from tf-models-official==2.11.6->mediapipe-model-maker) (2.0.6)
Collecting pyyaml<6.0,>=5.1 (from tf-models-official==2.11.6->mediapipe-model-maker)
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 16.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

For yours collaborations with error. very thanks

**Comment by TetsuakiBaba** [comment]
Hello. I also confirmed the same error today. This error was caused by the installation of the 5.4.1 version of PyYAML, so I found a workaround for this by referring to this site (https://github.com/aws-actions/setup-sam/issues/82)  and installing mediapipe-model-maker as follows, 

!pip install PyYAML==5.3.1
!pip install rasa
!pip install mediapipe-model-maker

which allowed me to train the model. I know this is a stopgap measure, but until an official fix is made, please try this method.

**Comment by kuaashish** [comment]
Hello @easyparkingplace, @TetsuakiBaba,

Could you downgrade the pip version by using the below command and restart the run time again:

`!pip install pip=21.3.1`

I could able to import` !pip install mediapipe-model-maker ` successfully by downgrading the pip version as screenshot attached. 

<img width="1701" alt="Screenshot 2023-07-20 at 11 47 41 AM" src="https://github.com/google/mediapipe/assets/98159216/ceac6712-55d5-49e6-87c5-cb1b51e152f7">



And please let us know if this works for you. Thank you

**Comment by TetsuakiBaba** [comment]
@kuaashish it worked!! thanks.

**Comment by easyparkingplace** [comment]
It worked. Thank you so much
