### ISSUE TITLE
Make the visualizer open source

### ISSUE THREAD

**Issue by szandara** [google/mediapipe#463]
Hello

The visualizer is a great tool but since it's hosted on the cloud lots of companies would not really be able to use it for development because of infosec policies. Could you release the code in order to allow developers to run it locally safely?

Thanks

**Comment by mgyong** [comment]
We do not have plans to open source visualizer. We are constantly improving the feature set of the visualizer.  The visualizer should not be blocked from access by infosec policies.

**Comment by szandara** [comment]
Then, as a customer how can I be sure that my algorithm design is not made visible to people inside Google?

**Comment by khelkun** [comment]
@mgyong I wish I could use MediaPipe in a web application as your visualizer, but appart from the ["MediaPipe on the Web" article](https://developers.googleblog.com/2020/01/mediapipe-on-web.html) I have not so much clues about how I could achieve this.
Do you please know how I could get some help to achieve my own web integration of MediaPipe?

**Comment by khelkun** [comment]
@mgyong I guess the #459 thread is actually answering my question

**Comment by khelkun** [comment]
@mgyong Could the following article be mentioned on in the github README of mediapipe and eventually in the documentation?
https://blog.tensorflow.org/2020/03/face-and-hand-tracking-in-browser-with-mediapipe-and-tensorflowjs.html

**Comment by brucechou1983** [comment]
@szandara Since the pipeline is described in a .pbtxt file, you can use [Netron](https://github.com/lutzroeder/netron) to visualize it.

**Comment by szandara** [comment]
@brucechou1983 Thanks a lot, it's a very good tip!

**Comment by Takuro-Ito** [comment]
+1

**Comment by matanster** [comment]
I wonder in what ways is the visualizer a great tool for people who have commented. It visualizes a graph, that it does. But I have never found that useful beyond an initial aesthetic kind of pleasure  detached from purpose. 

The graph of execution cannot be traversed in any way near how a regular static graph of execution of a regular programming language code project can. For example, to navigate to a subgraph one has to expand the node name to a lower cased underscore delimited `pbtxt` file name and locate that file in the directory hierarchy, to load that file as well. There is no drill down or drill up / show usages flow. 

Clicking on a subgraph will seemingly not navigate to the corresponding tab which holds the subgraph’s definition, even after that tab has been opened following old-school method which I just described.

Even simple things like getting the top-most entry node to the graph is not a feature. 

I guess it's more of a nice visualizer for very simple graphs serving as a documentation companion. It would be really nice to give it more disciplined "product" work to really make it useful. Maybe open sourcing might help as an alternative path of leverage to make it useful in a much more leveraged/real sense.
