### ISSUE TITLE
Project generation failed when I use tulsi 'Generate' to create a iOS project

### ISSUE THREAD

**Issue by NewQuine** [google/mediapipe#4631]
[09:35:02](0): Project generation failed.
[09:35:02](0): Generate[FAIL]: 7.0076s [Details]: General failure: Failed to resolve labels: [//mediapipe/examples/ios/iristrackinggpu:IrisTrackingGpuApp, //mediapipe/examples/ios/posetrackinggpu:PoseTrackingGpuApp, //mediapipe/examples/ios/facedetectioncpu:FaceDetectionCpuApp, //mediapipe/examples/ios/holistictrackinggpu:HolisticTrackingGpuApp, //mediapipe/examples/ios/handdetectiongpu:HandDetectionGpuApp, //mediapipe/objc:mediapipe_framework_ios, //mediapipe/examples/ios/objectdetectiongpu:ObjectDetectionGpuApp, //mediapipe/examples/ios/facedetectiongpu:FaceDetectionGpuApp, //mediapipe/examples/ios/faceeffect:FaceEffectApp, //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp, //mediapipe/examples/ios/facemeshgpu:FaceMeshGpuApp, //mediapipe/examples/ios/objectdetectiontrackinggpu:ObjectDetectionTrackingGpuApp, //mediapipe/examples/ios/selfiesegmentationgpu:SelfieSegmentationGpuApp, //mediapipe/examples/ios/objectdetectioncpu:ObjectDetectionCpuApp, //mediapipe/examples/ios/helloworld:HelloWorldApp]
[09:35:02](0): Failed to create Xcode project.

**Comment by kuaashish** [comment]
@NewQuine,

I could successfully able to create the Xcode project in Python Version "3.11.3", Bazel Version "6.1.1", Xcode Version "14.2.0.14C18" with recent version 0.10.2 in intel macOS i7 as screenshot attached below:


<img width="300" alt="Screenshot 2023-07-21 at 12 52 26 PM" src="https://github.com/google/mediapipe/assets/98159216/49a3fbc7-7eff-499d-af2b-bc8edcb124b3">



Please create the project using the above configurations and let us know if this works for you. Thank you

**Comment by kuaashish** [comment]
@NewQuine,

Could you please update the status of above? Thank you

**Comment by NewQuine** [comment]
I create the Xcode project in Python Version "3.11.3", Bazel Version "6.2.1", Xcode Version "14.3.1.14E300c", Tulsi Version "0.20221005.88" in intel macOS i5
![1](https://github.com/google/mediapipe/assets/15979336/10cecc79-80bd-4877-a3c2-75b33ae0b79c)
![2](https://github.com/google/mediapipe/assets/15979336/b319c26f-2724-4cf2-867a-3954ae65ca1f)
![3](https://github.com/google/mediapipe/assets/15979336/b4402dfb-b453-47a2-8824-903e42d0ccc8)

**Comment by kuaashish** [comment]
@NewQuine,

Could you follow below implementation as workaround:

In [Configs](https://github.com/google/mediapipe/blob/master/mediapipe/MediaPipe.tulsiproj/Configs) file inside ["buildTargets"](https://github.com/google/mediapipe/blob/master/mediapipe/MediaPipe.tulsiproj/Configs/MediaPipe.tulsigen#L25) add `@` before all 15 files as below:

```
"buildTargets" : [
"@//mediapipe/examples/ios/facedetectioncpu:FaceDetectionCpuApp",
"@//mediapipe/examples/ios/facedetectiongpu:FaceDetectionGpuApp",
"@//mediapipe/examples/ios/faceeffect:FaceEffectApp",
"@//mediapipe/examples/ios/facemeshgpu:FaceMeshGpuApp",
"@//mediapipe/examples/ios/handdetectiongpu:HandDetectionGpuApp",
"@//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp",
"@//mediapipe/examples/ios/helloworld:HelloWorldApp",
"@//mediapipe/examples/ios/holistictrackinggpu:HolisticTrackingGpuApp",
"@//mediapipe/examples/ios/iristrackinggpu:IrisTrackingGpuApp",
"@//mediapipe/examples/ios/objectdetectioncpu:ObjectDetectionCpuApp",
"@//mediapipe/examples/ios/objectdetectiongpu:ObjectDetectionGpuApp",
"@//mediapipe/examples/ios/objectdetectiontrackinggpu:ObjectDetectionTrackingGpuApp",
"@//mediapipe/examples/ios/posetrackinggpu:PoseTrackingGpuApp",
"@//mediapipe/examples/ios/selfiesegmentationgpu:SelfieSegmentationGpuApp",
"@//mediapipe/objc:mediapipe_framework_ios"

```
And Please let us know if this works for you. Thank you!

**Comment by kuaashish** [comment]
Also, We recommend you to use the supported bazel version 6.1.1. Thank you!

**Comment by kuaashish** [comment]
@NewQuine,

Could you please update the status of the above. Thank you

**Comment by NewQuine** [comment]
I am sorry that I have been busy with other work recently. This method  "In [Configs] file inside ["buildTargets"] add @ before all 15 files as below:"  can solve the problem I have encountered. Thank you again for your help.

**Comment by NewQuine** [comment]
Of course, you can mark the issue solved.

**Comment by NewQuine** [comment]
<img width="1099" alt="图片" src="https://github.com/google/mediapipe/assets/15979336/b72e530a-8a1f-4ac7-b1f5-c86fcf3657e0">
I found an error when i run the xcode project in Xcode

**Comment by kuaashish** [comment]
@NewQuine,

To keep context of the easier to filter out the issue with title. We recommend you to raise a fresh issue with complete error logs and instructions following to reproduce the issue from our end And share the possible solution. Thank you
