### ISSUE TITLE
How to get Face geometry from face landmark model in mediapipe solution

### ISSUE THREAD

**Issue by veetechh** [google/mediapipe#4633]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### Solution

FaceMesh

### Programming Language and version

Javascript

### Describe the actual behavior

```shell
Is face geometry feature existing within new face landmark (task) model?

Couldn't get the face geometry output here.

https://codepen.io/mediapipe-preview/pen/OJBVQJm
```

**Comment by kuaashish** [comment]
@veetechh,

This can be used with the result from FaceLandmarker to draw the face geometry in JavaScript :

https://github.com/google/mediapipe/blob/master/mediapipe/tasks/web/vision/face_landmarker/face_landmarks_connections.ts 

Thank you!
