### ISSUE TITLE
impossible to install mediapipe version 0.10.0 on raspberry pi 4

### ISSUE THREAD

**Issue by cyriellesouop** [google/mediapipe#4634]
### OS Platform and Distribution

Debian GNU/Linux 11 (bullseye)

### Compiler version

gcc version 10.2.1 20210110 (Debian 10.2.1-6)

### Programming Language and version

python 3.9.2

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

0.10.0

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.8.0

### Describe the problem

```shell
pip install mediapipe==0.10.0
```

### Complete Logs

```shell
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.0 (from versions: 0.8.9.1)
ERROR: No matching distribution found for mediapipe==0.10.0
```

**Comment by kuaashish** [comment]
@cyriellesouop,

For now, We do not have wheels for AArch64 in Python. However, Please be assured support of Raspberry Pi is already in our roadmap And We will let you know once an update becomes available. Thank you

**Comment by cyriellesouop** [comment]
Ok. Thank you
