### ISSUE TITLE
Unrecognized option: --experimental_repo_remote_exec

### ISSUE THREAD

**Issue by koko-cg** [google/mediapipe#4637]
### OS Platform and Distribution

macOS Ventura 13.4.1

### Programming Language and version

Python 3.9.16

### Installed using virtualenv? pip? Conda?(if python)

Conda

### MediaPipe version

no know

### Bazel version

1.10

### XCode and Tulsi versions (if iOS)

Latest

### Android AAR (if android)

None

### Describe the problem

```shell
bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/hello_world:hello_world
```

### Complete Logs

```shell
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=190
INFO: Reading rc options for 'run' from /Users/kou/0722/mediapipe/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
ERROR: Unrecognized option: --experimental_repo_remote_exec
INFO: Writing tracer profile to '/private/var/tmp/_bazel_kou/dc26a0ac637f6cad0ee0f4d1b6b9b377/command.profile.gz'
```

**Comment by koko-cg** [comment]
memo: Bazelik version is 1.17.0

**Comment by kuaashish** [comment]
@koko-cg,

Could you please run the below command and let us know if this works for you.

bazelisk run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world


Thank you!

**Comment by koko-cg** [comment]
Thank you !

I tried the command you taught me, and there were no errors! However, this is what happened with the last part

**Comment by kuaashish** [comment]
@koko-cg,

Thank you for the confirmation, Can we mark issue resolved and close the status if now this issue is no longer issue from your end.

**Comment by koko-cg** [comment]
Yes, it really helped me out. Thank you from the bottom of my heart!
