### ISSUE TITLE
Cube rotation and movement as per box model from Objectron shoe

### ISSUE THREAD

**Issue by rkgnanesh** [google/mediapipe#4638]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### Solution

Objectron - shoe

### Programming Language and version

Javascript

### Describe the actual behavior

```shell
I am attempting to move and rotate a cube mesh according to the box model obtained from Objectron. However, the mesh is not rotating or moving as the box model moves.
```

### Other info / Complete Logs

```shell
Here is the link for my codepen

https://codepen.io/rkgnanesh/pen/JjeaPXR
```

**Comment by kuaashish** [comment]
@rkgnanesh,

We have ended the support of Objectron Solution as guided [here](https://developers.google.com/mediapipe/solutions/guide). However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose But We are not providing support on it. 

Thank you!!
