### ISSUE TITLE
Emulator/Device listing drop down is greyed out

### ISSUE THREAD

**Issue by jitendersaini** [google/mediapipe#464]
Hello, I'm struggling building this project for android but unable to succeed. The emulator/device listing drop down in Android studio is coming greyed out, even I delete and rebuild with fresh source code but didn't understand why this drop down is greyed out and finally when I try to install the application on android phone it says device not found might be because drop down is greyed out.

**Comment by eknight7** [comment]
Hi @jitendersaini, are you using MediaPipe with [Gradle](https://mediapipe.readthedocs.io/en/latest/install.html#using-mediapipe-with-gradle) or with [Bazel](https://mediapipe.readthedocs.io/en/latest/install.html#using-mediapipe-with-bazel)?

Can you share more details about which app you are running and on which device? Thanks.

**Comment by gigaByte404** [comment]
I have imported the android example for the hand detection model but it's not running.
