### ISSUE TITLE
Build python package on Ubuntu 22.04 libavreformat 

### ISSUE THREAD

**Issue by stephematician** [google/mediapipe#4643]
### OS Platform and Distribution

UbuntuMATE 22.04

### Compiler version

gcc12

### Programming Language and version

Python 3.10

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

0.10.2

### Bazel version

6.1.1

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.5.4

### Describe the problem

Attempted to build on Ubuntu 22.04 via instructions using `pip`, i.e.

```sh
cd /path/to/clone/of/mediapipe
MEDIAPIPE_DISABLE_GPU=0 pip install .
```

Now before I got to that point, I made changes as per the [instructions](https://developers.google.com/mediapipe/framework/getting_started/install). So

-   installed bazel 6.1.1
-   installed compiler via `sudo apt install protobuf-compiler`
-   installed `libopencv-contrib-dev` via APT (my system already had `ffmpeg` and `libavcodec` etc).
-   updated the `third_party/opencv_linux.BUILD` similar to my [earlier comment](https://github.com/google/mediapipe/issues/4371#issuecomment-1647988376)); i.e.

```diff
--- a/third_party/opencv_linux.BUILD
+++ b/third_party/opencv_linux.BUILD
@@ -17,15 +17,15 @@ cc_library(
         # For OpenCV 4.x
         #"include/aarch64-linux-gnu/opencv4/opencv2/cvconfig.h",
         #"include/arm-linux-gnueabihf/opencv4/opencv2/cvconfig.h",
-        #"include/x86_64-linux-gnu/opencv4/opencv2/cvconfig.h",
-        #"include/opencv4/opencv2/**/*.h*",
+        "include/x86_64-linux-gnu/opencv4/opencv2/cvconfig.h",
+        "include/opencv4/opencv2/**/*.h*",
     ]),
     includes = [
         # For OpenCV 4.x
         #"include/aarch64-linux-gnu/opencv4/",
         #"include/arm-linux-gnueabihf/opencv4/",
-        #"include/x86_64-linux-gnu/opencv4/",
-        #"include/opencv4/",
+        "include/x86_64-linux-gnu/opencv4/",
+        "include/opencv4/",
     ],
```

This did not succeed. I also had to pass the `--experimental_allow_proto3_optional` flag (see also issue #71), which I did by modifying `setup.py` (there may be a better option for passing flags - please advise if there is):

```diff
--- a/setup.py
+++ b/setup.py
@@ -222,6 +222,7 @@ class GeneratePyProtos(build_ext.build_ext):
       sys.stderr.write('generating proto file: %s\n' % output)
       protoc_command = [
           self._protoc, '-I.',
+          '--experimental_allow_proto3_optional',
           '--python_out=' + os.path.abspath(self.build_lib), source
       ]
       _invoke_shell_command(protoc_command)
```

This also did not succeed, as I received the error:

```
      /usr/bin/ld.gold: error: cannot find -lavresample                         
      collect2: error: ld returned 1 exit status                                
      make[1]: *** [CMakeFiles/cmTC_a7d66.dir/build.make:99: cmTC_a7d66] Error 1
...
   FAILED: Build did NOT complete successfully                                   
   Command '['bazel', 'build', '--compilation_mode=opt', '--copt=-DNDEBUG', '--action_env=PYTHON_    BIN_PATH=/usr/bin/python3', 'mediapipe/modules/face_detection/face_detection_short_range_cpu', '    --define=MEDIAPIPE_DISABLE_GPU=1', '--define=OPENCV=source']' returned non-zero exit status 1.
   error: subprocess-exited-with-error
...
   Building wheel for mediapipe (setup.py): finished with status 'error'         
   ERROR: Failed building wheel for mediapipe
```

It looks like [`libavresample` has been deprecated](https://bugs.gentoo.org/722274) in favour of `libswresample`. As far as I can tell, there is no need for the former. Out of caution I switched to include `libswresample` in `third_party/BUILD`:

```diff
--- a/third_party/BUILD
+++ b/third_party/BUILD
@@ -224,7 +224,7 @@ cmake(
         "-lavformat",
         "-lavutil",
         "-lswscale",
-        "-lavresample",
+        "-lswresample",
         "-ldl",
         "-lm",
         "-lpthread",
```

With some minor tweaks to `setup.py` so that bazel didn't nuke my memory and cpu's, and to get a valid PEP 440 version number (I chose `0.10.dev3`), I was able to build and install the package, however I have not tested it thoroughly so I cannot say for sure that this is an appropriate fix.

### Complete Logs

See comment below for attached output from `pip install .`

**Comment by stephematician** [comment]
Output of `pip install .` prior to switching out `libavresample`:

[pip_install_output.txt](https://github.com/google/mediapipe/files/12161377/pip_install_output.txt)

**Comment by kuaashish** [comment]
@stephematician,

Based on internal discussion, Fix is appropriate and it should not impact the overall performance. Thank you

**Comment by stephematician** [comment]
Great. I haven't tested any further, but if I do come across any problems I'll put them up here. Otherwise this can probably be closed.

**Comment by kuaashish** [comment]
@stephematician,

Sure, Please report back if you encounter any further issue from your end. For now, If no longer issue, We can mark this resolved and close the status. Thank you!
