### ISSUE TITLE
How to use GPU for calculation in the Python version of Mediapipe v0.10?

### ISSUE THREAD

**Issue by LTYF** [google/mediapipe#4644]
It has been running on the CPU，How can I configure to start GPU? CUDA has already been installed

**Comment by LTYF** [comment]
I am using pose tracking

**Comment by mcdonasd1212** [comment]
I am also interested in a GPU solution.

**Comment by kuaashish** [comment]
Hi @LTYF,

We are pleased to announce the release of MP version 0.10.8, which now supports Python GPU via pip on macOS and Linux. As outlined in the [release notes](https://github.com/google/mediapipe/releases/tag/v0.10.8), we kindly request you to build using the latest version if you are not using the Windows system and inform us of your experience with GPU utilisation using Python Wheels.
