### ISSUE TITLE
Is it currently possible to take mediapipe out of the project and use it as a dependency?

### ISSUE THREAD

**Issue by Varfalamei** [google/mediapipe#4646]
Hi everyone, is it currently possible to take mediapipe out of the project and use it as a dependency?

I tried this with 
git_repository(
    name = "mediapipe",
    remote = "https://github.com/google/mediapipe.git",
    tag = "v0.10.2",
)
But ran into all sorts of problems:
  1. I had to copy WORKSPACE completely from mediapipe and move it to my project, and I would like to keep something like this.
  
  workspace(name = "mediapipe_apps")
  
  load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
  load("@bazel_tools/tools/build_defs/repo:git.bzl", "git_repository")
  
  git_repository(
      name = "mediapipe",
      remote = "https://github.com/google/mediapipe.git",
      tag = "v0.10.2",
  )
  android_sdk_repository(name = "androidsdk")
  android_ndk_repository(name = "androidndk", api_level=21)
  That is so that the other dependencies are pulled from mediapipe's WORKSPACE
  
  2. I had to copy the mediapipe_aar.bzl file to my repository, because it's not clear how to replace the link "//mediapipe/java/com/google/mediapipe/glutil" with "@mediapipe//mediapipe/java/com/google/mediapipe/glutil". Is there any way to opt out of copying?
  
  3. because of default_visibility = ["//visibility:private"] I am not able to use some components. Example:
https://github.com/google/mediapipe/blob/6de275834deebd50c5c42a7ce2b5aba30d6f79ce/mediapipe/framework/BUILD#L21

Maybe there is some other way to take out mediapipe, I would be glad to hear any suggestions

**Comment by schmidt-sebastian** [comment]
We have not designed MediaPipe with this use case in mind. If, however, we only need to change a few visibility declarations then lets us know and we can do so. Will close this for now. You can comment with a list of targets to open up the visibility if that helps.
