### ISSUE TITLE
Distribution with `conda-forge`

### ISSUE THREAD

**Issue by ruben-arts** [google/mediapipe#4647]
He Googlers, 

This is an awesome project. I was testing your pip package and it works very well!

I would like to install your package through the `conda-forge` distribution. This would make it much faster and easier to install on multiple platforms. 

Are you aware of this option and are you willing to distribute it through there?

Have a nice day!

**Comment by schmidt-sebastian** [comment]
Hi, thanks for the suggestion. This is not on our roadmap for now. We may however consider this in the future.

I will close this issue for now. Please take a look at our release notes for updates.
