### ISSUE TITLE
Compile custom c++ calculators for use in Javascript

### ISSUE THREAD

**Issue by jimwinkpresage** [google/mediapipe#4648]
I am trying to implement a custom graph and calculators into javascript framework. The graph seems to run fine on ios and android. Where are the instructions on how to build the custom calculators and graph for javascript?

**Comment by kuaashish** [comment]
@jimwinkpresage,

All Wasm files are prebuilt. We do not support the custom model using the Calculators and Graphs, And We do not have any documentation to build the model in JavaScript Framework. Thank you!!

**Comment by eulercat** [comment]
I think it needs to reopen this issue. Is there any specific reason not to open the ways to make wasm from this project?
This project is open-source, hence many developers might want to make their own wasm from their modifications for many reasons.
+ @kuaashish
