### ISSUE TITLE
Can we train a custom model for mediapipe face mesh 468 3D landmarks using latest mediapipe release?

### ISSUE THREAD

**Issue by aishwarya123mathpati** [google/mediapipe#4649]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 64

### Task name (e.g. Image classification, Gesture recognition etc.)

Face Landmark detection

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

```shell
It's generating 478 3D landmarks using mediapipe face mesh.
```

### Describe the expected behaviour

```shell
I wants to train a custom model for face landmarks using latest medaipipe solutions.
```

### Standalone code/steps you may have used to try to get what you need

```shell
Wanted to train a custom landmark training model using mediapipe model maker.
```

**Comment by kuaashish** [comment]
@aishwarya123mathpati,

For now, We have only Objection Detection, Image Classification, Gesture Recognition And Text Classification are re-trainable. However, We will let you know if any update becomes available to include the Face Landmark feature. Thank you!
