### ISSUE TITLE
example of calling mediapipe via RPC

### ISSUE THREAD

**Issue by walkbird** [google/mediapipe#465]
Hello,

MediaPipe is a great framework to implement video/image process pipeline. I'm trying to integrate MediaPipe with a RPC Framework (like GRPC) to provide an image process service. It would be great if anyone could share some experience or example code.

**Comment by mgyong** [comment]
@walkbird Could you describe your use case more? The closest would be to run a [desktop example like object detection C++ we have](https://github.com/google/mediapipe/blob/master/mediapipe/docs/object_detection_desktop.md) as a c++ binary that runs a MediaPipe graph that constantly streams result protos (eg. detection protos in the case of object detection). Implement a GRPC C++ streaming server to constantly read the output detection protos. We would be interested in such an example as well and would love to get your contribution of how to integrate a GRPC server to a MediaPipe example
