### ISSUE TITLE
Adding Image to stream image_in was not ok: INVALID_ARGUMENT: Graph has errors

### ISSUE THREAD

**Issue by DevaPandiyan** [google/mediapipe#4654]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Web Chrome

### MediaPipe Tasks SDK version

0.10.2

### Task name (e.g. Image classification, Gesture recognition etc.)

Image classification

### Programming Language and version (e.g. C++, Python, Java)

javascript using react

### Describe the actual behavior

```shell
image and video switch.  i switch  video rendering, then  after switch to image it shows an error
```

### Describe the expected behaviour

```shell
image and video switch to get rendering images
```

### Other info / Complete Logs

```shell
vision_wasm_internal.js:9 E0731 03:52:53.371000 1813520 gl_graph_runner_internal_image.cc:68] Adding Image to stream image_in was not ok: INVALID_ARGUMENT: Graph has errors: 
Packet timestamp mismatch on a calculator receiving from stream "norm_rect". Current minimum expected timestamp is 1690775569763001 but received 1690775569763000. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment. [type.googleapis.com/mediapipe.StatusList='\n\xf5\x02\x08\x03\x12\xf0\x02Packet timestamp mismatch on a calculator receiving from stream \"norm_rect\". Current minimum expected timestamp is 1690775569763001 but received 1690775569763000. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.']
=== Source Location Trace: ===
third_party/mediapipe/framework/input_stream_manager.cc:139




vision_wasm_internal.js:9 E0731 03:52:53.372000 1813520 calculator_graph.cc:858] INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
Packet timestamp mismatch on a calculator receiving from stream "norm_rect". Current minimum expected timestamp is 1690775569763001 but received 1690775569763000. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment. [type.googleapis.com/mediapipe.StatusList='\n\xf5\x02\x08\x03\x12\xf0\x02Packet timestamp mismatch on a calculator receiving from stream \"norm_rect\". Current minimum expected timestamp is 1690775569763001 but received 1690775569763000. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.']
=== Source Location Trace: ===
third_party/mediapipe/framework/input_stream_manager.cc:139
```

**Comment by kuaashish** [comment]
@DevaPandiyan,

Could you please elaborate your query with complete details? Also Please provide complete steps following from the documentation to reproduce the issue from our end. Thank you!

**Comment by DevaPandiyan** [comment]
Im Using with camera and Image when im switch to video to image that was not Detect  it s showing error
 Code :
 const faceLandmarkerResult =  await face_landmarker.detect(img);
        
              onResultImage(faceLandmarkerResult,img)

  const faceLandmarkerResult =  await face_landmarker.detect(img);           
              onResultImage(faceLandmarkerResult,img)




const switchMode=async ()=>{
    console.log("swith to  :", runningMod);
     (runningMod === "IMAGE")? runningMod ="VIDEO":runningMod="IMAGE";
    //   (runningMod === "IMAGE")? SetRunningMode("VIDEO"):SetRunningMode("VIDEO");
     

   SetRunningMode(runningMod);
   SetRunningMode(runningMod);
   
   
   
    if(runningModes=="IMAGE"){
    console.log("runningif :", runningMod);
   }else{
    console.log("runningels :", runningMod);
   }
    console.log("running after :", runningMod);
    await face_landmarker.setOptions({ runningMode:runningMod });
    if(runningMod!=="VIDEO"){ 
        stremVideoStop();

        
    }else{


    }


    runningSetup();   

}


Error:


 vision_wasm_internal.js:9 E0731 03:52:53.371000 1813520 gl_graph_runner_internal_image.cc:68] Adding Image to stream image_in was not ok: INVALID_ARGUMENT: Graph has errors: 
Packet timestamp mismatch on a calculator receiving from stream "norm_rect". Current minimum expected timestamp is 1690775569763001 but received 1690775569763000. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment. [type.googleapis.com/mediapipe.StatusList='\n\xf5\x02\x08\x03\x12\xf0\x02Packet timestamp mismatch on a calculator receiving from stream \"norm_rect\". Current minimum expected timestamp is 1690775569763001 but received 1690775569763000. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.']
=== Source Location Trace: ===
third_party/mediapipe/framework/input_stream_manager.cc:139

**Comment by schmidt-sebastian** [comment]
Are you using "video" mode at all or does this issue occur with just "image" mode?

**Comment by spennihana** [comment]
I reported a similar issue (#4769) and after switching to `runningMode=IMAGE`, I no longer see these errors.

**Comment by DevaPandiyan** [comment]
Yeah i fixed it
