### ISSUE TITLE
@mediapipe/tasks-vision include types exports in package.json

### ISSUE THREAD

**Issue by KostisP** [google/mediapipe#4659]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

javascript

### Task name (e.g. Image classification, Gesture recognition etc.)

all

### Programming Language and version (e.g. C++, Python, Java)

javascript 0.3.10

### Describe the actual behavior

```shell
Typescript cannot find a declaration file for @mediapipe/tasks-vision module.
```

### Describe the expected behaviour

```shell
`"types": "./vision.d.ts" ` should be added under exports in package.json

`
"exports": {
    "import":  "./vision_bundle.mjs",
    "require": "./vision_bundle.cjs",
    "default":  "./vision_bundle.mjs",
    "types": "./vision.d.ts" 
  }
`
```

### Standalone code/steps you may have used to try to get what you need

```shell
import { FaceLandmarker } from '@mediapipe/tasks-vision';
```

**Comment by matteoturini** [comment]
Just now faced this issue.

**Comment by kiochan** [comment]
@KostisP 
Here is a temporary solution for this issue.

In your tsconfig change `moduleResolution` to `node`.
This solution will force typescript compiler to read `types` from the root of `package.json` file.

```json
{
  "compilerOptions": {
    "moduleResolution": "node",
  }
}
```

**Comment by schmidt-sebastian** [comment]
Will add this. Should be part of next release.

**Comment by sunapi386** [comment]
Take a look at this issue
https://stackoverflow.com/questions/66096260/why-am-i-getting-referenceerror-self-is-not-defined-when-i-import-a-client-side

In short, the error occurs because the library requires Web APIs to work, which are not available when [Next.js pre-renders the page](https://nextjs.org/docs/pages/building-your-application/rendering) on the server-side.

**Comment by matteoturini** [comment]
> Take a look at this issue https://stackoverflow.com/questions/66096260/why-am-i-getting-referenceerror-self-is-not-defined-when-i-import-a-client-side
> 
> In short, the error occurs because the library requires Web APIs to work, which are not available when [Next.js pre-renders the page](https://nextjs.org/docs/pages/building-your-application/rendering) on the server-side.

No. I faced this issue outside of Next.js.
