### ISSUE TITLE
is platform_specific_profiling deprecated？

### ISSUE THREAD

**Issue by jiqimaogou** [google/mediapipe#466]
https://github.com/google/mediapipe/blob/master/mediapipe/framework/platform_specific_profiling.h

is platform_specific_profiling deprecated? nobody call it anywhere in the code

**Comment by mgyong** [comment]
@jiqimaogou  We have released [experimental profiling and tracing](https://github.com/google/mediapipe/blob/master/mediapipe/docs/tracer.md) at [viz.mediapipe.dev](https://viz.mediapipe.dev) with [v0.7.5](https://github.com/google/mediapipe/releases/tag/v0.7.5)
Please check it out and give us feedback
