### ISSUE TITLE
Pip Install fail with 0.10.3 (Framework not initialized)

### ISSUE THREAD

**Issue by deniz-birlikci** [google/mediapipe#4660]
### OS Platform and Distribution

Linux Ubuntu

### Programming Language and version

Python 3.10

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

0.10.3

### Android AAR (if android)

None

### Describe the problem

```shell
I had previously saved mediapipe landmark output into a pickle file. With Mediapipe 0.10.2 I had no issues. With the new version, it is failing since it cannot find framework, GPU, or modules arguments inside the init file.
```

### Complete Logs

```shell
<ipython-input-9-b3fba84fc51b> in load_files(directory)
      8 
      9     with open(landmark_path, 'rb') as f:
---> 10         landmark_data = pickle.load(f)
     11 
     12     with open(segmentation_path, 'r') as f:

/usr/local/lib/python3.10/dist-packages/mediapipe/__init__.py in <module>
     18 
     19 
---> 20 del framework
     21 del gpu
     22 del modules

NameError: name 'framework' is not defined
```

**Comment by kuaashish** [comment]
@deniz-birlikci,

Could you let us know the Linux Ubuntu version encountering the issue. Also, Please share the complete steps you are following to reproduce the issue from our end. Thank you

**Comment by zihaomu** [comment]
Same issue on MacOS 12.1, Intel CPU. Python 3.10.

**Comment by kuaashish** [comment]
@zihaomu,

Please raise a new issue with complete information to reproduce the issue from our end. Thank you
