### ISSUE TITLE
Unable to run hand detection and face mesh at the same time on Android device

### ISSUE THREAD

**Issue by yanchlu** [google/mediapipe#4662]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Android 11

### MediaPipe Tasks SDK version

latest

### Task name (e.g. Image classification, Gesture recognition etc.)

hand detection, face mesh

### Programming Language and version (e.g. C++, Python, Java)

Java

### Describe the actual behavior

```shell
Hi,I'm currently trying to build an Android App that can both detect hands and faces.

Although Holistic can achieve this, it only outputs 468 face landmarks, while the lastest face mesh model outputs an estimate of 478 3-dimensional face landmarks, that's all I need.

So I try to combine the codes of file mediapipe\examples\android\solutions\hands and file mediapipe\examples\android\solutions\facemesh. But I found that face mesh and hand detection can only run one at the same time, because camera resource can only be called by one ImageSolutionBase class when startCamera().

Is there a way to get CameraInput for both tasks?
```

### Other info / Complete Logs

```shell
Class Hand and Class FaceMesh inherit from Class ImageSolutionBase. They have independent EglManager, resulting in incompatibility of image frame.
```

**Comment by kuaashish** [comment]
@yanchlu,

We recommend you to use the [newTasks API](https://developers.google.com/mediapipe/solutions/tasks#android) and handle the camera data in the Android code. Thank you
