### ISSUE TITLE
Installing with chaquopy fails with error  UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

### ISSUE THREAD

**Issue by rolandeke** [google/mediapipe#4663]
### OS Platform and Distribution

Windows 11 

### Programming Language and version

Java

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

latest

### Android AAR (if android)

None

### Describe the problem

```shell
A bug happened!
```

### Complete Logs

```shell
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "691a29db9c336349e48e04c5c2f4873f2890af5cbfa6e51f4de87fefe6169294"
DEBUG: Repository rules_cc instantiated at:
  D:/mediapipe/WORKSPACE:40:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/user/_bazel_user/hr7sucjp/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: D:/mediapipe/WORKSPACE:586:23: fetching android_sdk_repository rule //external:androidsdk: java.io.IOException: The repository's path is "/home/user/Android/" (absolute: "/home/user/Android") but a symlink could not be created for it, because: /home/user/Android (No such file or directory)
ERROR: Analysis of target '//mediapipe/tasks/metadata:metadata_schema_py' failed; build aborted: The repository's path is "/home/user/Android/" (absolute: "/home/user/Android") but a symlink could not be created for it, because: /home/user/Android (No such file or directory)
INFO: Elapsed time: 145.651s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (7 packages loaded, 18 targets configured)


===============================

 UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```

**Comment by kuaashish** [comment]
@rolandeke,

Could you please elaborate your query with complete details. Also, Please provide the reproducible steps to look into issue from our end. Thank you!!

**Comment by rolandeke** [comment]
Thank you!

I am trying to install mediapipe directly from github with pip using chaquopy in an android studio mobile application project. After cloning the repository I get a build failed error saying **"UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details."** 

I cannot install mediapipe from PYPI using Chaquopy and they do not have mediapipe in their package repository.

**Comment by kinaryml** [comment]
> Thank you!
> 
> I am trying to install mediapipe directly from github with pip using chaquopy in an android studio mobile application project. After cloning the repository I get a build failed error saying **"UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details."**
> 
> I cannot install mediapipe from PYPI using Chaquopy and they do not have mediapipe in their package repository.

@rolandeke A fix is to downgrade setuptools as follows:
`pip install setuptools==65.7.0`

**Comment by kuaashish** [comment]
@rolandeke,

Could you please go through the [above](https://github.com/google/mediapipe/issues/4663#issuecomment-1668112604) and let us know the update. Thank you!!

**Comment by rolandeke** [comment]
> @rolandeke,
> 
> Could you please go through the [above](https://github.com/google/mediapipe/issues/4663#issuecomment-1668112604) and let us know the update. Thank you!!

I tried installing the `setuptools==65.7.0` but still get an error. 
```
pip {
                install "setuptools==65.7.0"
               install "git+https://github.com/google/mediapipe.git"
}
```


Is there any rebuilt Mediapipe wheel that can be used in Android projects?

**Comment by kuaashish** [comment]
Hello @kinaryml,

Could you please look into this issue. Thank you

**Comment by kinaryml** [comment]
@rolandeke You could edit the version here to a valid one like 0.10.3 and try again too.

https://github.com/google/mediapipe/blob/a9c7e22ca4525289b17ad7471e813594b7870c01/setup.py#L33

**Comment by kinaryml** [comment]
> Thank you!
> 
> I am trying to install mediapipe directly from github with pip using chaquopy in an android studio mobile application project. After cloning the repository I get a build failed error saying **"UserWarning: The version specified ('dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details."**
> 
> I cannot install mediapipe from PYPI using Chaquopy and they do not have mediapipe in their package repository.

Also MediaPipe doesn't support installing via git such as "pip install git+https://github.com/google/mediapipe.git"

**Comment by joshuatorre1** [comment]
Hi! Is there any update for this issue? Can MediaPipe be used to Android Studio using Chaquopy? Thank you in advance.

**Comment by kuaashish** [comment]
We are closing this matter due to lack of activity. Thank you
