### ISSUE TITLE
Typo in mp.Image API Reference

### ISSUE THREAD

**Issue by PVTejas-Yottaasys** [google/mediapipe#4664]
### Clear description

In the python documentation for mp.Image, in the code sample for creation examples, lines 3,5: it is unclear which module `ImageFormat` belongs to. From line 11 it becomes apparent that it belongs to `mp`, and I propose the following change:

```diff
import cv2
cv_mat = cv2.imread(input_file)[:, :, ::-1]
-rgb_frame = mp.Image(image_format=ImageFormat.SRGB, data=cv_mat)
+rgb_frame = mp.Image(image_format=mp.ImageFormat.SRGB, data=cv_mat)
gray_frame = mp.Image(
-    image_format=ImageFormat.GRAY,
+    image_format=mp.ImageFormat.GRAY,
    data=cv2.cvtColor(cv_mat, cv2.COLOR_RGB2GRAY))

from PIL import Image
pil_img = Image.new('RGB', (60, 30), color = 'red')
image = mp.Image(
    image_format=mp.ImageFormat.SRGB, data=np.asarray(pil_img))
```

### Correct links

https://developers.google.com/mediapipe/api/solutions/python/mp/Image

**Comment by PVTejas-Yottaasys** [comment]
Accidentally submitted an incomplete issue. Fixed now.

**Comment by kuaashish** [comment]
@PVTejas-Yottaasys,

Thank you for pointing it out. The typo has been fixed in our internal codebase upstream, and will be pushed to GitHub once approved.

**Comment by kuaashish** [comment]
Closing this as it has been fixed internally and changes can be seen in https://developers.google.com/mediapipe/api/solutions/python/mp/Image. Thank you
