### ISSUE TITLE
iOS building mediapipe/tasks/ios/build_ios_framework.sh and import xxx.xcfrmaeworks showing "No registered object with name:xxx" error

### ISSUE THREAD

**Issue by zhuwen15** [google/mediapipe#4665]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

iOS 16.5

### MediaPipe Tasks SDK version

v0.10.3

### Task name (e.g. Image classification, Gesture recognition etc.)

face_landmarker

### Programming Language and version (e.g. C++, Python, Java)

Objc,C++, Swift

### Describe the actual behavior

```shell
After building mediapipe/tasks/ios/build_ios_framework.sh, I got "MediaPipeTasksCommon.xcframework", "MediaPipeTasksVision.xcframework" ,"libMediaPipeTasksCommon_device_graph.a","libMediaPipeTasksCommon_simulator_graph.a". Then I added these files, and "face_landmarker.task" data file to a iOS target, when I setuped FaceLandmarker, "
        let options = FaceLandmarkerOptions()
        let baseOptions = BaseOptions()
        let path = Bundle.main.path(forResource: "face_landmarker", ofType: "task")
        baseOptions.modelAssetPath = path ?? ""
        options.baseOptions = baseOptions
        options.minTrackingConfidence = minPoseTrackingConfidence
        options.runningMode = .liveStream
        options.faceLandmarkerLiveStreamDelegate = self
        do {
            let faceLandmarker = try FaceLandmarker(options: options)
        } catch  {
            print("###FaceLandmarker failed")
        }
"
but errors showed when I catch error"
Error Domain=com.google.mediapipe.tasks Code=5 "NOT_FOUND: ValidatedGraphConfig Initialization failed.
No registered object with name: mediapipe::tasks::vision::face_landmarker::FaceLandmarkerGraph; Unable to find Calculator "mediapipe.tasks.vision.face_landmarker.FaceLandmarkerGraph"
No registered object with name: FlowLimiterCalculator; Unable to find Calculator "FlowLimiterCalculator"" UserInfo={NSLocalizedDescription=NOT_FOUND: ValidatedGraphConfig Initialization failed.
No registered object with name: mediapipe::tasks::vision::face_landmarker::FaceLandmarkerGraph; Unable to find Calculator "mediapipe.tasks.vision.face_landmarker.FaceLandmarkerGraph"
No registered object with name: FlowLimiterCalculator; Unable to find Calculator "FlowLimiterCalculator"} "
```

### Describe the expected behaviour

```shell
Setup FaceLandmarker successfully
```

### Standalone code/steps you may have used to try to get what you need

```shell
let options = FaceLandmarkerOptions()
        let baseOptions = BaseOptions()
        let path = Bundle.main.path(forResource: "face_landmarker", ofType: "task")
        baseOptions.modelAssetPath = path ?? ""
        options.baseOptions = baseOptions
        options.minTrackingConfidence = minPoseTrackingConfidence
        options.runningMode = .liveStream
        options.faceLandmarkerLiveStreamDelegate = self
        do {
            let faceLandmarker = try FaceLandmarker(options: options)
        } catch  {
            print("###FaceLandmarker failed")
        }
```

**Comment by kuaashish** [comment]
@zhuwen15,

Could you elaborate your query with complete details. Also, Please provide the complete steps you are following to reproduce the issue from our end. Thank you!

**Comment by zhuwen15** [comment]
> 

Hi,Sir,Thanks a lot for your reply.My steps are as follows:
1.Terminal cd to mediapipe/tasks/ios/, there is  a shell  file "build_ios_framework.sh".

2.In "build_ios_framework.sh" line 33, set FRAMEWORK_NAME="MediaPipeTasksCommon", then in terminal excuted ./build_ios_framework.sh, got files "MediaPipeTasksCommon.xcframework" and "libMediaPipeTasksCommon_device_graph.a"

3.In "build_ios_framework.sh" line 33, set FRAMEWORK_NAME="MediaPipeTasksVision", also excuted ./build_ios_framework.sh, got file "MediaPipeTasksVision.xcframework"

4. Dragged these three files to a swift target, then downloaded data file "face_landmarker.task" at "https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task", and also dragged this file to the target.

5.In a swift file import MediaPipeTasksVision, excuted the following codes,
        let options =  FaceLandmarkerOptions()
        let baseOptions = BaseOptions()
        let path = Bundle.main.path(forResource: "face_landmarker", ofType: "task")
        baseOptions.modelAssetPath = path ?? ""
        options.baseOptions = baseOptions
        options.minTrackingConfidence = minPoseTrackingConfidence
        options.runningMode = .liveStream
        options.faceLandmarkerLiveStreamDelegate = self
        do {
            let faceLandmarker = try FaceLandmarker(options: options)
        } catch  {
            print("###FaceLandmarker failed")
        }
      ** let faceLandmarker = try FaceLandmarker(options: options)** will catch a error showed as follows _"
Error Domain=com.google.mediapipe.tasks Code=5 "NOT_FOUND: ValidatedGraphConfig Initialization failed.
No registered object with name: mediapipe::tasks::vision::face_landmarker::FaceLandmarkerGraph; Unable to find Calculator "mediapipe.tasks.vision.face_landmarker.FaceLandmarkerGraph"
No registered object with name: FlowLimiterCalculator; Unable to find Calculator "FlowLimiterCalculator"" UserInfo={NSLocalizedDescription=NOT_FOUND: ValidatedGraphConfig Initialization failed.
No registered object with name: mediapipe::tasks::vision::face_landmarker::FaceLandmarkerGraph; Unable to find Calculator "mediapipe.tasks.vision.face_landmarker.FaceLandmarkerGraph"
No registered object with name: FlowLimiterCalculator; Unable to find Calculator "FlowLimiterCalculator"} "_

**Comment by zhuwen15** [comment]
I found that mediapipe project was not compatible with apple static library like [](https://github.com/google/mediapipe/issues/144) was saying.So I change a new way to packaging the iOS framework, and the problem was solved.And I pull a MR [](https://github.com/google/mediapipe/pull/4674)

**Comment by kuaashish** [comment]
Hello @schmidt-sebastian,

Could you please look into this issue. Thank you

**Comment by schmidt-sebastian** [comment]
The build script is used internally to build our CocoaPods targets. Please use the publicly available MediapipeTasksVision pod.
