### ISSUE TITLE
What's the different between the 'mediapipe/modules' and 'mediapipe/tasks/cc/vision'?

### ISSUE THREAD

**Issue by zihaomu** [google/mediapipe#4667]
What's the different between the `mediapipe/modules` and `mediapipe/tasks/cc/vision`?
The latter overlaps a lot with the former. For example `mediapipe/modules/face_geometry/libs` and the `mediapipe/tasks/cc/vision/face_geometry/libs`.

**Comment by kuaashish** [comment]
@zihaomu,

`mediapipe/modules` belongs to MediaPipe Legacy Solution as noted in guide [here](solutions) And `mediapipe/tasks/cc/vision` are new upgraded solutions. 

However, We would recommend you to explore our upgraded [Task APIs](https://developers.google.com/mediapipe/solutions). You can continue to use those legacy solutions in your applications if you choose But We have ended support of upgraded solutions. 

Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. Thank you

**Comment by kuaashish** [comment]
@zihaomu,

Could you please let us know we can mark the issue resolved and close the status if now this is no longer issue from your end. Thank you

**Comment by zihaomu** [comment]
Hi @kuaashish. Thanks for your answer.
