### ISSUE TITLE
Custom Framework on Jetson

### ISSUE THREAD

**Issue by tpm518** [google/mediapipe#4669]
Hello,

I want to build a custom framework in C++ to use multiple models together on a video stream (object detection, face tracking, pose detection) and then run same basic analytics on the model outputs. I want to then run that framework on a Jetson device. Does this approach seem valid? I see that I am able to run Python examples on the Jetson device, but I'm not sure about creating/running custom frameworks.

Thanks,
Tom

**Comment by kuaashish** [comment]
@tpm518,


MediaPipe does not offer any official support, libraries, modules to build into Jetson. there are [plugin](https://github.com/anion0278/mediapipe-jetson) from the community is quite up-to-date which might help in this context But We do not have a plan to support Jeston and does not provide support in how to use them.


Thank you!!
