### ISSUE TITLE
Python compatibility

### ISSUE THREAD

**Issue by Hemantr05** [google/mediapipe#467]
I want to know if autoflip is compatible with python

**Comment by jiuqiant** [comment]
AutoFlip is now C++ only. But, you can write python code to execute the binary via subprocess. We did this to the yt8m example already: https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/youtube8m/viewer/server.py#L155

In the meanwhile, we are working on a project to bring MediaPipe to the Python world.

**Comment by jedell** [comment]
Can you elaborate on how this can be done specifically for autoflip?

**Comment by akashAD98** [comment]
> AutoFlip is now C++ only. But, you can write python code to execute the binary via subprocess. We did this to the yt8m example already: https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/youtube8m/viewer/server.py#L155
> 
> In the meanwhile, we are working on a project to bring MediaPipe to the Python world.

@jiuqiant is there any update on this? how can we implement this in python?

**Comment by desis123** [comment]
is there any update of Autoflip on python
