### ISSUE TITLE
Pose Landmark smoothing_calculator needed

### ISSUE THREAD

**Issue by Abd1799** [google/mediapipe#4670]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Windows 11

### MediaPipe Tasks SDK version

0.10.3

### Task name (e.g. Image classification, Gesture recognition etc.)

pose landmark

### Programming Language and version (e.g. C++, Python, Java)

python 3.9

### Describe the actual behavior

```shell
The pose landmarks are highly jittery, and not at all usable
```

### Describe the expected behaviour

```shell
stable smoothed landmark output
```

### Standalone code/steps you may have used to try to get what you need

```shell
running the pose landmark model in video or live stream mode
```

### Other info / Complete Logs

```shell
the old mediapipe versions i believe have landmark smoothing built in, which is missing in the versions after 0.10.
this issue was also been raised in #4507 , but for c++.
Can someone please help me in adding it back, or help in using one_euro_filter with python api.
```

**Comment by Abd1799** [comment]
Can we manually add this as a step in our pipeline or is there any plans to add this ,when can we expect this to be added

**Comment by kuaashish** [comment]
@Abd1799,

Could you please share any reference images/videos with respect to jitter issue you are facing that can be helpful to look issue better and provide the possible solution. Thank you!!

**Comment by kuaashish** [comment]
Also, Please share the complete reproducible code which you are following.

**Comment by kuaashish** [comment]
Hello @yichunk,

Could you please look into this issue. Thank you

**Comment by mcdonasd1212** [comment]
Also interested in a smoothing function for python.

**Comment by kuaashish** [comment]
@Abd1799,

We are pleased to announce the release of the latest version of MediaPipe, version [0.10.7](https://github.com/google/mediapipe/releases), which addresses the jittering issue observed in the Pose Landmarker.

This issue has been documented in the release [notes ](https://github.com/google/mediapipe/releases/tag/v0.10.7)under "Fixed Pose Landmarker jittering issue." We kindly request you to build using this updated version and inform us of any persisting issues from your perspective. Thank you
