### ISSUE TITLE
Cannot install mediapipe 0.10.3 on raspberry pi 4b running python 3.9.2 and bullseye 32-bit.

### ISSUE THREAD

**Issue by johncblacker** [google/mediapipe#4673]
### OS Platform and Distribution

Raspberry Pi Bullseye 32-bit AARCH64

### Compiler version

gcc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110

### Programming Language and version

Python 3.9.2

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

0.10.3 for python (cp39) anylinux

### Bazel version

? - not building from sources

### XCode and Tulsi versions (if iOS)

not on IOS

### Android SDK and NDK versions (if android)

not on Android

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.5.1

### Describe the problem

```shell
I was able to successfully install version 0.10.3 on my Raspberry pi 3b running the 64-bit version of bullseye; however I cannot install on my raspberry pi 4b running 32-bit bullseye.  I downloaded this file:
mediapipe-0.10.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: mediapipe-0.10.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl is not a supported wheel on this platform.and tried to install with pip; but I keep getting this error:

I looked for "simple" but it appears it is unknown?
```

### Complete Logs

```shell
pi@pi32bbull:/etc/apt $ pip install mediapipe==0.10.3
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.3 (from versions: none)
ERROR: No matching distribution found for mediapipe==0.10.3
I get same error if I use the above downloaded mediapipe installation package.
```

**Comment by kuaashish** [comment]
@johncblacker,

As described in Download files, built distributions section in the [page ](https://pypi.org/project/mediapipe/0.10.3/#files) as below:

[mediapipe-0.10.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl ](https://files.pythonhosted.org/packages/0c/b8/1361c0d898aff1b8b58bdb3ba038e12fc723ab237e1f2d9cff02da542f11/mediapipe-0.10.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl)(32.5 MB [view hashes](https://pypi.org/project/mediapipe/0.10.3/#copy-hash-modal-50836d04-2e60-4f3d-8a29-a583250cd883))
Uploaded Aug 1, 2023 cp311.
..............................................................
All published files for the aarch64(64 bit) not for aarch32(32 bit). However, Raspberry Pi 4b running 32-bit bullseye will be not supported. Thank you
