### ISSUE TITLE
Accuracy of text embedding

### ISSUE THREAD

**Issue by oneday24** [google/mediapipe#4676]
I have tested the text embedding with mobile bert model to caculate the sentence similarlity with 512 dimensions.
Text1: how are you
Text2:  run app
Score: 0.94

The score is too high and definitly wrong score.
Do you know why?
The way I get embedding vector is as below: 

textEmbedder?.let {
            val embed = **it.embed(text).embeddingResult().embeddings().first().floatEmbedding()**
            return embed.asList()
        }

**Comment by kuaashish** [comment]
Hello @fban-google,

Could you please look into this. Thank you

**Comment by hheydary** [comment]
Greetings,
Are you using a custom model? If so has it been properly converted to tflite and does it conform to the task's model [requirements](https://developers.google.com/mediapipe/solutions/text/text_embedder/index#models)?

The recommended model shipped for this task is a light-weight model suitable for on device applications. The corresponding paper for the recommended model can be found [here](https://arxiv.org/abs/1907.04780) and the model is released on TFHub [here](https://tfhub.dev/google/lite-model/universal-sentence-encoder-qa-ondevice/1).
