### ISSUE TITLE
How to feed box tracking calculator with bitmap frames and get results in Android Mediapipe

### ISSUE THREAD

**Issue by devveteran** [google/mediapipe#4678]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android 11

### Task name (e.g. Image classification, Gesture recognition etc.)

Box Tracking

### Programming Language and version (e.g. C++, Python, Java)

Kotlin

### Describe the actual behavior

```shell
Hello!

I've built AAR for Mediapipe box tracking and integrated to my Android application.
This application already has functions to read every frames of RTSP, Phone camera and videos within Gallery for detecting specific objects from them.
Now what I want is to feed the tracking engine with these frames and get results(boxes).
I've been trying to figure out that for 2 days but what I've done so far is the following.

val imagePacket: Packet = packetCreator.createRgbaImageFrame(rgbFrameBitmap)
   try {
      if (imagePacket.isEmpty == false) {
          processor.graph.addConsumablePacketToInputStream(
              INPUT_VIDEO_STREAM_NAME,
              imagePacket,
              java.lang.System.currentTimeMillis()
          )
      }
      imagePacket.release()
   } catch(e: java.lang.Exception) {
       e.printStackTrace()
}
Besides, this code occurs error "Graph is not started because of missing streams".

Also, I'm not sure how to set INPUT_VIDEO_STREAM_NAME properly.
According to the examples, for hand tracking, "hand_landmarks" is used, etc.
Where can I get the available values for this input/output stream names?
Thank you in advance!
```

### Describe the expected behaviour

```shell
Feed bitmap frames to the tracking engine and get results.
```

### Standalone code/steps you may have used to try to get what you need

```shell
val imagePacket: Packet = packetCreator.createRgbaImageFrame(rgbFrameBitmap)
   try {
      if (imagePacket.isEmpty == false) {
          processor.graph.addConsumablePacketToInputStream(
              INPUT_VIDEO_STREAM_NAME,
              imagePacket,
              java.lang.System.currentTimeMillis()
          )
      }
      imagePacket.release()
   } catch(e: java.lang.Exception) {
       e.printStackTrace()
}
```

**Comment by kuaashish** [comment]
@devveteran,

We have completely ended support of Box Tracking solution as noted [here](https://developers.google.com/mediapipe/solutions/guide#legacy). However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose But We are not providing support on it.

Thank you!

**Comment by vidueirof** [comment]
@devveteran have you solved this problem? I'm running face detector, but rtsp stream is really slow compared to device camera. ~1000ms to ~100ms.
