### ISSUE TITLE
FaceLandmarker creation very slow on Firefox/Windows

### ISSUE THREAD

**Issue by delta42** [google/mediapipe#4679]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 10

### Browser and version if the issue happens on browser

Firefox 116.0.2 (64-bit)

### Programming Language and version

JavaScript

### MediaPipe version

0.10.3

### Solution

FaceLandmarker

### Describe the actual behavior

```shell
FaceLandmarker.createFromOptions takes anywhere between 18 and 30 seconds to complete under Firefox on my Windows 10 PC, whereas under Chrome it takes just under 1 second.

The codepen on https://codepen.io/mediapipe-preview/pen/OJBVQJm also takes longer to initialize on Firefox vs, Chrome, although it's not as easy to measure and the default mode is GPU not CPU.
```

### Describe the expected behaviour

```shell
I would expect it to be generally slower on Firefox but not by a factor of 10x-30x.
```

### Standalone code/steps you may have used to try to get what you need

```shell
Relevant code:


initializeAsync = function () {
        if (!this._isInitialized && !this._isInitializing) {
            this._isInitializing = true;
            let taskVision;
            const module = 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.3';
            import(module)
                .then((result) => {
                    taskVision = result;
                    return taskVision.FilesetResolver.forVisionTasks(
                        'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.3/wasm'
                    );
                })
                .then((vision) => {
                    const options = {
                        baseOptions: {
                            modelAssetPath: `https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task`,
                            delegate: 'CPU'
                        },
                        outputFaceBlendshapes: false,
                        runningMode: 'VIDEO',
                        numFaces: 1
                    };
                    return taskVision.FaceLandmarker.createFromOptions(vision, options);
                })
                .then((faceLandmarker) => {
                    this._faceLandmarker = faceLandmarker;
                    this._isInitialized = true;
                    this._isInitializing = false;
                });
        }
    };
```
```


### Other info / Complete Logs

_No response_

**Comment by kuaashish** [comment]
@delta42,

Could you please try with Chrome Browser probably with newest version and let us know if you observe the similar behaviour. Thank you

**Comment by kuaashish** [comment]
@delta42,

We have exclusively conducted testing using our Task APIs on the Chrome and Safari web browsers, as per the provided [guidance](https://developers.google.com/mediapipe/solutions/setup_web#supported_platforms_and_versions). Regrettably, we are unable to assure optimal performance on the Firefox browser due to limitations in bandwidth resources. 
Consequently, we kindly request your cooperation in implementing the Task Web API on a supported platform. We also request that you promptly report any analogous behaviour observed on the browsers we officially endorse.
