### ISSUE TITLE
Why most calculators are using OpenGL < 1.3, which is very old?

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#468]
I see that in most calculators with GPU operations, the version for OpenGL is specified with

https://github.com/google/mediapipe/blob/d68f5e416903e3d756ebe07d08c4a3b911741a91/mediapipe/gpu/gl_simple_shaders.cc#L40

Why use such an old version of OpenGL? What are the rationales?

**Comment by mcclanahoochie** [comment]
Hi,
The code you link to _checks_ if the GLSL version is < 1.3 (OpenGL 3).
This is to support older system/phones for "legacy" OpenGL / OpenGL ES.

By default on desktop MediaPipe uses/requires OpenGL 3.3+ , see [here](https://github.com/google/mediapipe/blob/d68f5e416903e3d756ebe07d08c4a3b911741a91/mediapipe/gpu/gl_simple_shaders.h#L115)

Also, not all calculators use that macro. 
In fact, _all_ of the shaders in the calculators/tflite directory define a version explicitly (to use compute shaders) , [example](https://github.com/google/mediapipe/blob/d68f5e416903e3d756ebe07d08c4a3b911741a91/mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc#L510)
While most of the gpu calculators in the 'image' directory do use that macro (compute shaders not used in there).

So using that macro will allow for most compatibility, but that is not limiting to any version, and one can require a specific version if desired in their own calculators.

**Comment by yxchng** [comment]
Ok thanks for the info.
