### ISSUE TITLE
ImageSegmenter creation from Web Worker hangs on iOS

### ISSUE THREAD

**Issue by delta42** [google/mediapipe#4680]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

iOS 16.5.1

### Mobile device if the issue happens on mobile device

iPhone X

### Browser and version if the issue happens on browser

Safari 16.5.1, Chrome 115.0.5790.160

### Programming Language and version

JavaScript

### MediaPipe version

0.10.3

### Solution

ImageSegmenter 

### Describe the actual behavior

```shell
When the ImageSegmenter is created in a Web Worker on iOS Safari or iOS Chrome, createFromOptions never returns, or at least, it doesn't return in under 60 seconds.

When run on the main thread, createFromOptions works as expected on iOS.
```

### Describe the expected behaviour

```shell
Since ImageSegmenter.createFromOptions works fine from Web Workers on Chromium browsers and Firefox on Windows, and it works fine on all platforms tested when not using a Web Worker, I would expect it to also work on iOS under Web Workers, or at least get some error message, or at the very least, for this to be a current, documented limitation.
```

### Standalone code/steps you may have used to try to get what you need

```shell
Relevant code:


    initializeAsync() {
        if (!this._isInitialized && !this._isInitializing) {
            this._loc = 1;

            this._isInitializing = true;
            let taskVision;
            const module = 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.3';
            import(module)
                .then((result) => {
                    this._loc = 2;

                    taskVision = result;
                    return taskVision.FilesetResolver.forVisionTasks(
                        'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.3/wasm'
                    );
                })
                .then((vision) => {
                    this._loc = 3;

                    const options = {
                        baseOptions: {
                            modelAssetPath:
                                'https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_segmenter/float16/latest/selfie_segmenter.tflite',
                            delegate: 'CPU'
                        },
                        runningMode: 'VIDEO',
                        outputCategoryMask: true,
                        outputConfidenceMasks: false
                    };
                    return taskVision.ImageSegmenter.createFromOptions(vision, options);
                })
                .then((segmenter) => {
                    this._loc = 4;

                    this._imageSegmenter = segmenter;
                    this._isInitialized = true;
                    this._isInitializing = false;
                });
        }
    },
```
```


### Other info / Complete Logs

_No response_

**Comment by schmidt-sebastian** [comment]
@delta42 Do you have any logs you could share (console output from the task)?

**Comment by schmidt-sebastian** [comment]
@delta42 Thank you for diagnosing this. The "document" issue should be fixed in the next release. See https://github.com/google/mediapipe/commit/990bfd2e3eaf0f0c977a7af7330ac4ad54f768cb

**Comment by schmidt-sebastian** [comment]
Let me re-open this.

While Safari now supports OffscreenCanvas, it does not yet support WebGL2RenderingContext: https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/getContext. We are blocked on this right now.

**Comment by dbaynard** [comment]
> While Safari now supports OffscreenCanvas, it does not yet support WebGL2RenderingContext: https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/getContext. We are blocked on this right now.

I'm also blocked on this.

According to the [apple developer documentation](https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-114#WebGL), this functionality was implemented in 2020. I haven't searched properly, but it is not obvious when the regression happened (if it did). I'd be interested to hear what has happened.

**Comment by schmidt-sebastian** [comment]
Unfortunately, this support still seems to not be available: https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/getContext (see support table). We need WebGL2.

https://jsfiddle.net/9ctfb86v/ prints "null' on Safari 16.6 for me.

**Comment by tyrmullen** [comment]
Note that the Apple Developer Documentation linked above is for Safari Technology Preview (STP), not Safari itself.  There is no guarantee that a feature from STP makes it into Safari proper.  In fact, https://caniuse.com/offscreencanvas explicitly mentions STP 17 as having full support while Safari 16.6 has "partial support", and hovering over the "partial support" will pop up a text box explaining that WebGL/WebGL2 contexts specifically are unsupported in Safari still.

Thus, it is technically possible to run fully CPU-based pipelines from a worker thread in Safari, but not ones requiring GL rendering or machine learning.  The team does not currently have bandwidth to restructure the entire ImageSegmenter to be fully CPU-based in order to work around this (hopefully temporary) missing Safari feature, so we're blocked for now.

**Comment by dbaynard** [comment]
Thanks for the explanation. iOS 17 is released today, it seems, so that 'temporary' might be _very_ temporary indeed… here's hoping.

**Comment by kuaashish** [comment]
Hi @delta42,

Could you test the functionality on the latest iOS 17 release? As indicated in the previous comment and detailed in the Apple release [notes](https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#Web-API), OffscreenCanvas with WebGL is expected to be operational in Safari. 

Additionally, could you try this on the latest version of Chrome with iOS 17 and share your findings with us? 

 Thank you
