### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'export' (at vision_bundle.js:1:880347)

### ISSUE THREAD

**Issue by Astro-Abhi** [google/mediapipe#4684]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Web Windows

### MediaPipe Tasks SDK version

0.10.3

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose

### Programming Language and version (e.g. C++, Python, Java)

JS

### Describe the actual behavior

```shell
Script import successfull
```

### Describe the expected behaviour

```shell
Uncaught SyntaxError: Unexpected token 'export' (at vision_bundle.js:1:880347)
```

### Standalone code/steps you may have used to try to get what you need

```shell
<script src="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/vision_bundle.js"></script>
```

**Comment by kuaashish** [comment]
@Astro-Abhi,

Could you please update the status of the above. Thank you

**Comment by Astro-Abhi** [comment]
I tried it, it is still giving the same error

**Comment by kuaashish** [comment]
Hello @schmidt-sebastian,

Could you please look into this issue. Thank you

**Comment by schmidt-sebastian** [comment]
The https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/vision_bundle.cjs does not contain the "export" keyword (as suggested above). Please ensure that you are not using the *.js files from an older version.

**Comment by danrossi** [comment]
> @Astro-Abhi,
> 
> Could you please import using as below and let us know if this works for you.
> 
> ```
> <head>
>   <script src="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/vision_bundle.mjs"
>     crossorigin="anonymous" type="module"></script>
> </head>
> ```
> 
> or
> 
> ```
> <head>
>   <script src="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/vision_bundle.cjs"
>     crossorigin="anonymous"></script>
> </head>
> ```
> 
> Thank you

These don't provide a global namespace when not using as an inline module import which isn't how it would generally work on the page. All the docs use inline module references. And the web docs still reference the broken task bundle url available at jsdelivr. How does an iife version of my app get references to ```FilesetResolver``` etc using the mjs as above ? The cjs breaks as the mimetype is "node". Instead of including on the page I have to build my own bundle then concat it in the non module application. It can't be bundled into the application specifically.

**Comment by RubensZimbres** [comment]
Same problem here, with a customized .tflite model. The model satisfies the MediaPipe model requirements, but the HTML code at codepen only works with the supported models.

Adding any of both scripts at <head> didn't solve the problem.

I get these errors in VSCode:

```
Could not read source map for https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@20230920.0.0: Unexpected 404 response from https://cdn.jsdelivr.net/npm/@mediapipe/vision_bundle_mjs.js.map: Failed to resolve the requested file.
Uncaught TypeError TypeError: Failed to fetch
    at l (cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@20230920.0.0:7:43548)
    at l (cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@20230920.0.0:7:63802)
    at o (cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@20230920.0.0:7:102475)
    at _o (cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@20230920.0.0:7:42141)
    --- await ---
```

And these errors in Chrome inspection/Console:

```
Refused to execute script from 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision/vision_bundle.cjs' because its MIME type ('application/node') is not executable, and strict MIME type checking is enabled.
file.html:1 Access to fetch at 'https://storage.googleapis.com/artigoflash/tflite/1-224-224-3-int8/output/resnet50_quantized.tflitee' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
storage.googleapis.com/xxxxxxxxxx/resnet50_quantized.tflitee:1 
                
       Failed to load resource: net::ERR_FAILED
tasks-vision@20230920.0.0:7 
        
       Uncaught (in promise) TypeError: Failed to fetch
    at ja.l (tasks-vision@20230920.0.0:7:43548)
    at ja.l (tasks-vision@20230920.0.0:7:63802)
    at ja.o (tasks-vision@20230920.0.0:7:102475)
    at _o (tasks-vision@20230920.0.0:7:42141)
    at async createImageClassifier (file.html:198:21)
```
