### ISSUE TITLE
Can I run unet, text encoder and Vae decoder from stable diffusion and use gpu acceleration using google mediapipe's now open source framework?

### ISSUE THREAD

**Issue by fuerpy** [google/mediapipe#4686]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### Describe the actual behavior

```shell
I saw the apk of your hairstyles on the blog and wanted to implement the code. But I want to check first.
```

**Comment by kuaashish** [comment]
@fuerpy,

Could you please elaborate your query with complete details. Thank you!
