### ISSUE TITLE
How works PreviousLoopBackCalculator ?

### ISSUE THREAD

**Issue by romaindebraize** [google/mediapipe#469]
Hi,

I am working on the handtracking for android. I have already found a code to do display a string when a specific position is detected on a frame but i would like to implement a dynamic gesture recognition. For example, I want to detect when the hand goes from a Five position to a fist position.

To do that i tried with a LoopBackCalculator in the handLandmark graph here :
![image](https://user-images.githubusercontent.com/60918250/74937153-cd007280-53eb-11ea-832e-4ca08b6f0c84.png)

![image](https://user-images.githubusercontent.com/60918250/74937426-4c8e4180-53ec-11ea-830e-8b2b3dc54a97.png)

But i have this issue when running the app : 
`2020-02-20 11:08:48.314 32213-32213/? A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffffffffffffffe8 in tid 32213 (andtrackingpits), pid 32213 (andtrackingpits)`

Do you have any idea to solve this problem ?

**Comment by eknight7** [comment]
Hi @romaindebraize, can you share some more details about the output of `adb logcat` when you run this app?

Also, have you tried using your graph on desktop to see if it works there?

**Comment by romaindebraize** [comment]
Hi @eknight7 ,

I didn't try on desktop yet. I will do that and let you know the results.
