### ISSUE TITLE
ImageSegmenter Web Example Unoptimized

### ISSUE THREAD

**Issue by torinmb** [google/mediapipe#4690]
It looks like the web example for the media pipe ImageSegmenter is utilizing a CPU call that is throttling the performance.

Here's the call on the [official documentation example](https://codepen.io/mediapipe-preview/pen/xxJNjbN?editors=0010) for the web on line 152
```const mask: Number[] = result.categoryMask.getAsFloat32Array();``` the segmentation is getting converted from the GPU to the CPU here.  

It looks like there's an alternative call to ```getAsWebGLTexture()```, and you can access the gl context through ```result.categoryMask.getGL()```. Additionally, you can specify the canvas that the ImageSegmenter will use in the constructor so it should be possible. Do you have any examples that don't have the same bottleneck? It seems like the performance on the main website is much better. Any help would be greatly appreciated!

**Comment by kuaashish** [comment]
@torinmb,

Please go through the above and follow up with [#4630(comment)](https://github.com/google/mediapipe/issues/4630#issuecomment-1679680586), Also, Please let us know if you need further help from our end. Thank you

**Comment by danrossi** [comment]
I would like to know how to convert my previous selfie segmentation rendering with WebGL to the current model as it still requires video cpu draw. The current api and model claims to have softmax postprocessing but it's not being activated as per the log. 

How to use the WebGL texture returned to mix with background and video , and render to another gl context ?

My previous shader mix looks like this using the red channel of the mask. There is smoothing being added in the shader instead but not needed if softmax postprocessing is activated.  

```
outColor = mix(bgTex, vec4(frameColor, 1.0), maskTex.r);
```

**Comment by tyrmullen** [comment]
What does the log say regarding softmax exactly?  Softmax should be being automatically applied if:
(a) your model's metadata has softmax set as the activation function
(b) you have chosen to output confidence masks (category masks are not affected by softmax, so as an optimization softmax is not applied if only category masks are produced)
(c) your model has more than 1 category (softmax doesn't make sense if there is only one category)

As for rendering with WebGL, the discussion from issue #4630 looks like it should have what you need, and I can follow up there for more discussion about rendering across contexts.
