### ISSUE TITLE
Using @mediapipe/tasks-vision with Web worker? 

### ISSUE THREAD

**Issue by volodymyrl** [google/mediapipe#4694]
In the documentation, it is often to see recommendations to use **segment()** and **segmentForVideo()** with web worker, but there is no doc about it. 

When I try to do something like this

```
// worker.js

onmessage = async function (e) {
  const { startTimeMs, video } = e.data
  imageSegmenter.segmentForVideo(video, startTimeMs, (result) => {
    postMessage(result)
  })
}
```

I have the error  _Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': WebGLTexture object could not be cloned._ I also can't get result.confidenceMasks[0].getAsFloat32Array() to send it as a plain array because web workers don't support  _getAsFloat32Array_ . Any examples or suggestions?

**Comment by spennihana** [comment]
Hey @schmidt-sebastian do you think you'll be cutting an npm package soon with this fix?

**Comment by wjaykim** [comment]
As a workaround, add following line before run the task.
```js
self.document = {}
```

**Comment by skyuplam** [comment]
as of 8 March, 2024, we still don't get the update 🤔

**Comment by Jur97** [comment]
> As a workaround, add following line before run the task.
> 
> ```js
> self.document = {}
> ```

For anyone trying to run vision tasks in an angular web-worker, one should use globalThis.document = {}. Prevents ios devices from crashing on document, which the mediapipe package is trying to access on ios.
