### ISSUE TITLE
Objectron for new classes other than the ones in ModelName (shoes, cup, etc)

### ISSUE THREAD

**Issue by monajalal** [google/mediapipe#4695]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Ubuntu 22.04

### MediaPipe Tasks SDK version

Objectron

### Task name (e.g. Image classification, Gesture recognition etc.)

6D Pose Estimation

### Programming Language and version (e.g. C++, Python, Java)

Python (open to other languages)

### Describe the actual behavior

```shell
currently inference only works on a limited number of classes, shoes, cup, camera, chair.
https://codepen.io/mediapipe/pen/BaWvzdY
```

### Describe the expected behaviour

```shell
I want to get inference on custom model. Want to get access to training code, documentation for capture or dataset creation for custom object, and finally be able to get real-time 6D inference on custom object of interest.
```

### Standalone code/steps you may have used to try to get what you need

```shell
I haven't tried.
```

**Comment by kuaashish** [comment]
@monajalal,

We have ended the support of Objectron Solution as guided [here](https://developers.google.com/mediapipe/solutions/guide#legacy). However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose But We are not providing support on it.

Thank you!!
