### ISSUE TITLE
When and in  which new version  will the holistic interface be re-provided?

### ISSUE THREAD

**Issue by LebronJames0423** [google/mediapipe#4696]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

windows10.linux，ARM

### Task name (e.g. Image classification, Gesture recognition etc.)

holistic

### Programming Language and version (e.g. C++, Python, Java)

python ,js,c++

### Describe the actual behavior

```shell
used in 3D avatar mission
```

### Describe the expected behaviour

```shell
in one detection, output the whole body and face landmarks
```

### Standalone code/steps you may have used to try to get what you need

```shell
in one detection, output the whole body and face landmarks
```

**Comment by kuaashish** [comment]
@LebronJames0423 ,

Thank you for your interest in the MediaPipe solutions, Holistic new TaskAPI is already in our roadmap and will be available here in the [page ](https://developers.google.com/mediapipe/solutions/vision/holistic_landmarker)once becomes ready from our end with complete information in the model card. However, For now, We can not commit any timeline to be available.
