### ISSUE TITLE
0.10.3 doesn't work - for example in the web test page official test

### ISSUE THREAD

**Issue by UXDart** [google/mediapipe#4701]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

macos 

### Programming Language and version

JS

### Solution

Vision

### Describe the actual behavior

```shell
go to https://codepen.io/mediapipe-preview/pen/ZEqzpRg and change 0.10.0 to 0.10.3 in both places. console shows different errors. like Uncaught (in promise) Error: StartGraph failed: $while processing the output streams of subgraph node mediapipe.tasks.vision.interactive_segmenter.InteractiveSegmenterGraph: Tag "QUALITY_SCORES" does not exist in the subgraph config
```

### Describe the expected behaviour

```shell
it should work :) / this is happening in the last version too. using NPM and tried with the url cdn sample to be sure it wasn't an NPM problem
```

### Standalone code/steps you may have used to try to get what you need

```shell
NA
```

**Comment by kuaashish** [comment]
@UXDart,

Could you please let us know the complete details such macOS you are using is intel Or Silicon based, In which browser you are observing the behaviour to understand the issue better from our end. Thank you!

**Comment by UXDart** [comment]
sure, macOS 13.5 / Chrome (all last versions) / just tried on Firefox and it doesn't work also / M1 processor. the console is full of errors, there is no segmentation done. the errors are crash of the framework. 0.10.1 works... after that it never worked. thanks. same using npm or cdn urls

**Comment by UXDart** [comment]
tested sample also on macOS Intel (not M1) / Chrome and same errors. 0.10.0 and 0.10.1 works after that the sample is missing a change or something is broken. thanks

**Comment by schmidt-sebastian** [comment]
Note that the error you are seeing is due to a mismatched version between the JS and WASM files. You should be able to get past this error by reloading the Colab. I just noticed that there is another error though. Will publish a new version.

**Comment by UXDart** [comment]
Thanks! the other error is the one that shows using npm "Uncaught (in promise) Error: No registered object with name: mediapipe.RenderData; MakeProtoPacket failed". Thanks
