### ISSUE TITLE
Run the Image Generator demo app

### ISSUE THREAD

**Issue by Vickie0710** [google/mediapipe#4703]
When attempting to run the image generator demo application on Android, I found that the "GENERATE" button is not functional. I followed the instructions provided on the official website to install and run the application, but I am unable to generate images. I kindly request assistance in resolving this issue

**Comment by kuaashish** [comment]
@Vickie0710,

Thank you for reporting out this bug, 

@schmidt-sebastian, I could able to reproduce the issue in the Android Device And Generate button is not functional. 
Could you please highlight issue internally. Thank you!

**Comment by joezoug** [comment]
Hi @Vickie0710,

Thanks for raising this issue. I am able to run the app following the guide at https://developers.devsite.corp.google.com/mediapipe/solutions/vision/image_generator. The "Generate" button will not be functional until you initialize the model by pressing the "Initialize" button. Initialization may take a couple of minutes. During initialization the Initialize button will be grayed out and say "Initializing...". Once initialization is complete, the "Generate" button should be functional.

Let me know if that works?

**Comment by kuaashish** [comment]
Hello @Vickie0710,

Could you please go through the above and let us know the status. Thank you

**Comment by Fcucgvhhhvjv** [comment]
@joezoug can you please look at this issue
https://github.com/googlesamples/mediapipe/issues/201#issuecomment-1679202419
custom converted model following the page guide doesnt work .
Also i was able to run some listed model on miui 14 but after i switched rom to pixel experience it crashes right away .
Thank you.

**Comment by Vickie0710** [comment]
Hello,@kuaashish @joezoug
I previously tried pressing the "Initialize" button, but it would immediately exit the page. Then, when I opened the APP and pressed the "Generate" button, it still didn't work.

**Comment by kuaashish** [comment]
Hello @joezoug,

Could you please look into this issue again. Thank you

**Comment by joezoug** [comment]
Hi @Vickie0710,

It sounds like the app is crashing after you press "Initialize". Can double check that you have the weight files located at `/data/local/tmp/image_generator/bins`? If the weights are there, can you please share your crash logs? You can use the logcat tool to get crash logs: https://developer.android.com/tools/logcat.

**Comment by Fcucgvhhhvjv** [comment]
> 

@joezoug can you please take a look at this ?
It is similar to the current issue , also others models dont work that were listed on the demo page.
Thanks

**Comment by joezoug** [comment]
@Fcucgvhhhvjv I'm raising the other issue internally to see if anyone is able to help. What model doesn't work that is listed on the demo page?

**Comment by Fcucgvhhhvjv** [comment]
@joezoug
When i was using miui rom in poco x3 pro i was able to run the sd 1.5 that was listed on the demo page . I tried some other model like cyberreal from huggingface_hub  following the guideline to pick a model and then i converted it , but it crashes after loading into ram , as soon as i click generate it crashes .

I recently switched rom to pixel experience ,now even the mentioned model from the demo page  for which i have a copy didn't work , it doesn't even initialize it crashes right away .


So i have two issues , previously wasn't able to run any model that wasn't listed and in pixel experience even the listed one don't work .

**Comment by joezoug** [comment]
@Fcucgvhhhvjv I'm not very familiar with different Android OS ROMs so I cant say off the top of my head what may be the issue with Pixel Experience. If you have some error logs from `adb logcat` I can take a look.

**Comment by Jeffman112** [comment]
how exactly do i put the model weights in that folder? I cant find data/local/tmp (new to android dev sorry)

**Comment by joezoug** [comment]
The /data/local/tmp/ folder is located on your Android device. To see the folder, you should first run
```adb shell```
which will open up a Unix shell on the device. In the Unix shell, you can run `ls /data/local/tmp/` to see the folder.

In order to push files/folders from your device to the connected Android device, you will need to use the command
```adb push <source path on your computer> <dest path on device>```

See https://developer.android.com/tools/adb for details.
