### ISSUE TITLE
which gcc and g++ should I use?thanks

### ISSUE THREAD

**Issue by Gpwner** [google/mediapipe#4704]

**Comment by kuaashish** [comment]
@Gpwner,

This information is available in the documentation [here](https://developers.google.com/mediapipe/framework/getting_started/install#:~:text=We%20recommend%20installing%20gcc%20and,pip3%20install%20--user%20six%20.) as below:

**_Note: If you plan to use TensorFlow calculators and example apps, there is a known issue with gcc and g++ version 6.3 and 7.3. We recommend installing gcc and g++ version 8.x._**     Thank you!

**Comment by Gpwner** [comment]
thanks ,would you plan to provider pre-build medipipe gpu version ?

**Comment by kuaashish** [comment]
@Gpwner,

To keep context with actual issue with issue title to easier filter out the issue for the community. We would like to raise a new issue complete details and mark this as resolved. Thank you!
