### ISSUE TITLE
Building mediapipe GPU  whl successful but run failed

### ISSUE THREAD

**Issue by Gpwner** [google/mediapipe#4707]
### OS Platform and Distribution

Ubuntu 18.04.5 LTS

### Compiler version

gcc /g++  9.4.0

### Programming Language and version

python3.10.3

### Installed using virtualenv? pip? Conda?(if python)

conda

### Bazel version

6.1.1

### XCode and Tulsi versions (if iOS)

none

### Android SDK and NDK versions (if android)

none

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

default(3.4.0)

### Describe the problem

```shell
Hi,I am building a mediapipe gpu version and I have already build out a whl file.But when I install it into anaconda env I got some the error:

ImportError: /root/anaconda3/envs/test/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /root/anaconda3/envs/test/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so)
```

By the way,I build it using conda env which is python3.10.3 too.
```


### Complete Logs

```shell
log file will be upload.
```

**Comment by Gpwner** [comment]
here are build log
[log.txt](https://github.com/google/mediapipe/files/12375350/log.txt)

**Comment by Gpwner** [comment]
When I run a python script,I got this error:
```
Traceback (most recent call last):
  File "/root/main.py", line 3, in <module>
    import mediapipe as mp
  File "/root/anaconda3/envs/test/lib/python3.10/site-packages/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/root/anaconda3/envs/test/lib/python3.10/site-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: /root/anaconda3/envs/test/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /root/anaconda3/envs/test/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so)
```


Any  help will be appreciate!

**Comment by kuaashish** [comment]
@Gpwner,

Could you please give a try to run below command And let us know if this helps:


`conda install -c conda-forge gcc=12.1.0`


Reference: ['GLIBCXX_3.4.30' not found for librosa in conda virtual environment](https://stackoverflow.com/questions/72540359/glibcxx-3-4-30-not-found-for-librosa-in-conda-virtual-environment-after-tryin). Thank you

**Comment by Gpwner** [comment]
here is main.py:
```
import argparse
import cv2
import mediapipe as mp

def process_video(video_path):
   
    mp_drawing = mp.solutions.drawing_utils
    drawing_spec = mp_drawing.DrawingSpec(thickness=1, circle_radius=1)

    
    mp_face_mesh = mp.solutions.face_mesh
    face_mesh = mp_face_mesh.FaceMesh(static_image_mode=False, max_num_faces=1, min_detection_confidence=0.5)

    
    cap = cv2.VideoCapture(video_path)

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        
        results = face_mesh.process(frame_rgb)

        
        if results.multi_face_landmarks:
            for face_landmarks in results.multi_face_landmarks:
                mp_drawing.draw_landmarks(image=frame, landmark_list=face_landmarks, connections=mp_face_mesh.FACE_CONNECTIONS,
                                          landmark_drawing_spec=drawing_spec, connection_drawing_spec=drawing_spec)

        
        cv2.imshow('Face Mesh', frame)
        if cv2.waitKey(5) & 0xFF == 27:
            break

    cap.release()
    cv2.destroyAllWindows()

    
    face_mesh.close()


parser = argparse.ArgumentParser(description='Process a video.')
parser.add_argument('video_path', type=str, help='The path to the video file.')


args = parser.parse_args()


process_video(args.video_path)
```

**Comment by kuaashish** [comment]
@Gpwner,

Could you create a **Python virtual environment And activate environment** by Using the below command:

`python3 -m venv mp_env && source mp_env/bin/activate`

And Install **MediaPipe Python package and start Python interprete**r Using the below command:

```
(mp_env) pip install mediapipe
(mp_env) python3
```

All steps are mentioned [here](https://github.com/google/mediapipe/blob/master/docs/getting_started/python.md#ready-to-use-python-solutions). Also, please let us know if this works for you. Thank you!

**Comment by Gpwner** [comment]
@kuaashish but I want a GPU support mediapipe.pip install mediapipe will install the cpu verison.This is the reason I rebuild it form source.

**Comment by kuaashish** [comment]
Hello @schmidt-sebastian,

Could you please look into this issue. Thank you

**Comment by Gpwner** [comment]
in  case someone want to reproduce the error,I  will provide a pre-build whl which  modify setup.py :

```
  binary_graphs = [
        'face_detection/face_detection_short_range_cpu',
        'face_detection/face_detection_full_range_cpu',
        'face_landmark/face_landmark_front_cpu',
        'hand_landmark/hand_landmark_tracking_cpu',
        'holistic_landmark/holistic_landmark_cpu', 'objectron/objectron_cpu',
        'pose_landmark/pose_landmark_cpu',
        'selfie_segmentation/selfie_segmentation_cpu'
    ]
```

to:
```
  binary_graphs = [
        'face_detection/face_detection_short_range_gpu',
        'face_detection/face_detection_full_range_gpu',
        'face_landmark/face_landmark_front_gpu',
        'hand_landmark/hand_landmark_tracking_gpu',
        'holistic_landmark/holistic_landmark_gpu', 'objectron/objectron_gpu',
        'pose_landmark/pose_landmark_gpu',
        'selfie_segmentation/selfie_segmentation_gpu'
    ]

```

and run 
```
python3 setup.py bdist_wheel
```


here are whl url:https://github.com/Gpwner/prebuild_mediapipe_gpu/blob/master/dist/mediapipe-0.20.0-cp310-cp310-linux_x86_64.whl


thanks.

**Comment by Gpwner** [comment]
@schmidt-sebastian When do you plan to release the GPU version of mediapipe?thanks

**Comment by kuaashish** [comment]
Hi @Gpwner,

We are pleased to announce the release of MP version 0.10.8, which now supports Python GPU via pip on macOS and Linux. As outlined in the [release notes](https://github.com/google/mediapipe/releases/tag/v0.10.8), we kindly request you to build using the latest version and inform us of your experience with GPU utilisation using Python Wheels.

Thank you
