### ISSUE TITLE
How to find specific landmarks' index number of mediapipe face mesh

### ISSUE THREAD

**Issue by aishwarya123mathpati** [google/mediapipe#4708]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 64

### MediaPipe version

mediapipe 0.10.3

### Solution

Mediapipe face mesh

### Programming Language and version

Python

### Describe the actual behavior

```shell
I am using mediapipe face mesh solution to get 478 landmarks, while using face mesh 478 landmarks, I observed there is one single landmark in the center of eye which is not moving at all, when all others are making some movement based on facial movement.
```

### Describe the expected behaviour

```shell
I wanted to know that particular index number of landmark. So I can skip that particular index number for visualization.
```

**Comment by kuaashish** [comment]
@aishwarya123mathpati,

Could you please share any reference image/video which you are observing to look better into issue. Thank you
