### ISSUE TITLE
HandLandamarkerResult Typo - Hand landmarks detection guide for Python - Navigate -> Create the Task section > Live stream tab

### ISSUE THREAD

**Issue by OrangeDev2** [google/mediapipe#4709]
### Description of issue (what needs changing)

https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/python#create_the_task

### Clear description

Navigate to the Create the task and click the Live stream tab.  There is a typo, `HandLandamarkerResult` should be `HandLandmarkerResult`.  `Error: "HandLandamarkerResult" is not definedPylancereportUndefinedVariable`

### Correct links

https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/python#create_the_task. All I can find is the old content in `mediapipe/docs/solutions /hands.md`. 

### Submit a pull request?

I would if I can find the current hands.md to take a look at the typo.

**Comment by kuaashish** [comment]
@OrangeDev2,

Thank you for reporting out this documentation bug. We have raised internal CL and based on approval changes will reflect into the page.

**Comment by kuaashish** [comment]
@OrangeDev2,

Closing this issue as CL has been merged and reflected change can be see [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/python#live-stream) in the documentation. Thank you
