### ISSUE TITLE
Questions about opening source AutoFlip

### ISSUE THREAD

**Issue by kekeliang** [google/mediapipe#471]
1. How to judge camera's motion mode, is there any additional information needed, such as the sensor  information of the shooting device? Or is it calculated from the video itself?

2. Is this solution currently implemented on the mobile side and how is the speed performance?

3. What other possible application scenarios AutoFlip could be applied to except from reframing?

Many Thanks!

**Comment by jiuqiant** [comment]
Hi @kekeliang, thank you for your interest! I can answer the 2nd question and my colleagues will answer question 1 and 3 later.

For question 2: Based on my experience, AutoFlip can be easily ported to both Android and iOS since MediaPipe itself is a cross-platform framework. The AutoFlip demo relies on the object detection and face tracking subgraphs of MediaPipe and Both of them are real-time MediaPipe application on both Android and iOS. Thus, AutoFlip should have a similar performance on mobile platforms as well.

**Comment by kekeliang** [comment]
Thanks mate @jiuqiant !

**Comment by yijiuzai** [comment]
When AutoFlip can be ported to both Android and iOS? or code is released?

**Comment by yijiuzai** [comment]
@jiuqiant When AutoFlip can be ported to both Android and iOS? or code is released?

**Comment by ndimension** [comment]
Hi @kekeliang, for question 1:
The camera motion is determined on each scene independently.  For each scene, only the video contents will be used to determine how the reframed camera captures the scene.  However, several parameters control what triggers the decision.  The setting _motion_stabilization_threshold_percent_ will control when the camera tracks objects vs holds a stable camera view.  If the detected best viewpoint is actually near the center of the frame but not exactly the center, _snap_center_max_distance_percent_ will snap the view to the exact center (useful on edited video).  If the contents are spread throughout the frame, _allow_sweeping_ set to true will cause the camera to sweep left-to-right to show the user everything in the frame at once.

For question 2: we have not tested for mobile, I will bring this question up to the team and check back.  On desktop, the pipeline runs at around real-time with the input video.

For question 3: The pipeline is mostly focused on reframing.  However, it could be used for 360 fov camera inputs to convert to a normal 30deg fov output.  You might also consider using a speaker detection model to have it focus on the person talking.  Please feel free to present ideas and we can look into adjusting autoflip for your need. 

@yijiuzai let me follow up with the team about IOS and android version.  There is nothing specific to the desktop that is blocking this request so it may not be too difficult.

**Comment by kekeliang** [comment]
It's been really helpful and thanks a lot!
