### ISSUE TITLE
[ Javascript ] even, delegate: "GPU", but "Created XNNPACK delegate for CPU"

### ISSUE THREAD

**Issue by Duke-2** [google/mediapipe#4711]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 11

### Programming Language and version

Chrome 115.0.5790.173

### MediaPipe version

0.10.2

### Solution

tasks-vision

### Describe the actual behavior

```shell
Even though, inference delegate set "GPU" even in samples. It seems not use GPU but CPU on XNNPACK. 

- Sample 1. Demo: Webcam continuous face landmarks detection https://codepen.io/mediapipe-preview/pen/OJBVQJm?editors=0010
  > Chrome console: vision_wasm_internal.js:9 INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

- Sample 2. Face Landmark Detection https://mediapipe-studio.webapps.google.com/demo/face_landmarker
  > Chrome console: INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

Also, test results on an Android phone by myself is same like above.
```

### Describe the expected behaviour

```shell
Expect the delegate for GPU not for CPU. 

Also expect on the GPU
1. Better performance not only PC but also on Android
2. Less battery consumption and heat projection
```

### Standalone code/steps you may have used to try to get what you need

```shell
You can see the results on your sample sites mentioned above.

The exact lines of Demo which is related to this is below. 

async function createFaceLandmarker() {
  const filesetResolver = await FilesetResolver.forVisionTasks(
    "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.3/wasm"
  );
  faceLandmarker = await FaceLandmarker.createFromOptions(filesetResolver, {
    baseOptions: {
      modelAssetPath: `https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task`,
      delegate: "GPU"
    },
    outputFaceBlendshapes: true,
    runningMode,
    numFaces: 1
  });
  demosSection.classList.remove("invisible");
}
```

**Comment by schmidt-sebastian** [comment]
This is expected. You will see both CPU and GPU used for the GPU delegate. The best way to check if GPU is used is by comparing the performance of the models. You should see a significant speed up for models that supports GPU.

**Comment by Duke-2** [comment]
@schmidt-sebastian, I calculated FPS on each delegate options on the Codepen sample. And, There are big peformance btw them. I could have found the difference if I had tested it in advance hehe. Thank you so much for your clear answer and clarification: ) 

I would like to ask you a question: do you have a plan to make better performance of Mediapipe? 
If you do not have the plan. Could you please give me a tip to achieve better peformance on Javascript version of Mediapipe?
