### ISSUE TITLE
Bazel doesn't build ios mediapipe examples

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#4714]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

iOS 

### Programming Language and version

oc

### MediaPipe version

lastest

### Bazel version

5.2

### Solution

handtrackinggpu

### Describe the actual behavior

```shell
Python 3.9.12
bazel 5.2.0
xcode 13.3.1 
macOS 12.3.1 (21E258)



bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp
ERROR: /Users/sisichen/work/mediapipe_work/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:34:16: ProcessEntitlementsFiles mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp_entitlements.entitlements failed: (Exit 1): plisttool failed: error executing command bazel-out/host/bin/external/build_bazel_rules_apple/tools/plisttool/plisttool ... (remaining 1 argument skipped)
```

### Describe the expected behaviour

```shell
I tried to build HandTrackingExample and get this error
```

### Standalone code/steps you may have used to try to get what you need

```shell
1
```

**Comment by kuaashish** [comment]
@chensisi0730,

From the description, We can see that you are using the Bazel Version 5.2.0, Supported Version of Bazel is 6.1.1 as noted here in [.bazelversion](https://github.com/google/mediapipe/blob/master/.bazelversion).  

Please use the recommend version And revert back if encounter any error. Thank you

**Comment by chensisi0730** [comment]
> @chensisi0730,
> 
> From the description, We can see that you are using the Bazel Version 5.2.0, Supported Version of Bazel is 6.1.1 as noted here in [.bazelversion](https://github.com/google/mediapipe/blob/master/.bazelversion).
> 
> Please use the recommended version And revert back if encounter any error. Thank you

ERROR: /Users/sisichen/work/mediapipe_work/mediapipe_newest/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:34:16: in ios_application rule //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_sisichen/a7fca234246f4255617eb5320eaa20b9/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 160, column 61, in _ios_application_impl
		entitlements = entitlements_support.process_entitlements(
	File "/private/var/tmp/_bazel_sisichen/a7fca234246f4255617eb5320eaa20b9/external/build_bazel_rules_apple/apple/internal/entitlements_support.bzl", line 273, column 24, in _process_entitlements
		_validate_bundle_id(bundle_id)
	File "/private/var/tmp/_bazel_sisichen/a7fca234246f4255617eb5320eaa20b9/external/build_bazel_rules_apple/apple/internal/entitlements_support.bzl", line 215, column 25, in _validate_bundle_id
		fail("Invalid character(s) in bundle_id: \"%s\"" % bundle_id)
Error in fail: Invalid character(s) in bundle_id: "*SEE_IOS_INSTRUCTIONS*.mediapipe.examples.HandTrackingGpu"
ERROR: /Users/sisichen/work/mediapipe_work/mediapipe_newest/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:34:16: Analysis of target '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp' failed
ERROR: Analysis of target '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp' failed; build aborted:

**Comment by kuaashish** [comment]
@chensisi0730,

Seems issue with bundle_id, Please have a look at this [example](https://github.com/mgyong/awesome-mediapipe#ios) to build the Hand tracking in iOS And Change the bundle id as mentioned [here](https://qiita.com/ponte1010/items/ed10cb2b5dcf7579f9bc#2-change-bundle-identifier) And let us know the further update from your end. Thank you

**Comment by kuaashish** [comment]
@chensisi0730,

Please change bundle_id to the same one which you set at Provisioning Profile in file [mediapipe/mediapipe/examples/ios/handtrackinggp/BUILD](https://github.com/google/mediapipe/blob/master/mediapipe/examples/ios/handtrackinggpu/BUILD) As below OR you can follow this example section [build-from-terminal ](https://qiita.com/ponte1010/items/ed10cb2b5dcf7579f9bc#build-from-terminal)to set up the bundle_id:


```
bundle_id = BUNDLE_ID_PREFIX + ".HandTrackingGpu",
　　　　　　　　　
bundle_id = "(Bundle Identifier)",
```
And revert back if you encounter further issue. Thank you

**Comment by schmidt-sebastian** [comment]
@chensisi0730 Can you confirm that you are still seeing this issue with the latest `master`? We reverted the change that introduced Bazel platform support.

**Comment by chensisi0730** [comment]
ERROR: /Users/sisichen/work/mediapipe_work/mediapipe_newest/mediapipe/mediapipe/modules/hand_landmark/BUILD:35:26: Linking mediapipe/modules/hand_landmark/hand_landmark_model_loader_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //mediapipe/modules/hand_landmark:hand_landmark_model_loader_graph_text_to_binary_graph) external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418-ST-9facee45ddd0/bin/mediapipe/modules/hand_landmark/hand_landmark_model_loader_graph_text_to_binary_graph-2.params

**Comment by AphroDatalyst** [comment]
i have the same problem,
fail("Invalid character(s) in bundle_id: \"%s\"" % bundle_id)
not solved yet!
