### ISSUE TITLE
Android samples are not compatible with latest versions of 'androidx.camera'

### ISSUE THREAD

**Issue by IvanYoga** [google/mediapipe#472]
Hi there! I am trying to use this framework with own model and it works well. I faced with issue that
`CameraXPreviewHelper` depends on old version of 'camera-core'.

> androidx.camera:camera-core:1.0.0-alpha06

This is part of main method to open camera from helper class. 
```
public void startCamera(Activity context, CameraFacing cameraFacing, SurfaceTexture surfaceTexture) {
        LensFacing cameraLensFacing = cameraFacing == CameraFacing.FRONT ? LensFacing.FRONT : LensFacing.BACK;
        PreviewConfig previewConfig = (new Builder()).setLensFacing(cameraLensFacing).setTargetResolution(TARGET_SIZE).build();
        this.preview = new Preview(previewConfig);
        
        this.preview.setOnPreviewOutputUpdateListener((previewOutput) -> { 
         .
         .
         .
    }
```

Unfortunately `preview.setOnPreviewOutputUpdateListener` do not exist anymore (removed since 1.0.0-alpha07). Please [see](https://android.googlesource.com/platform/frameworks/support/+/c6e1e60f6a115bdf4eae4758db9e76613bd4cf77%5E%21/#F6) change log. 

My question is about correct way to show stream from the camera with result of mediapipe framework.
Looks like there are no way to access to surface texture object. So do we have another options to display the result? Maybe I should get surface texture object in different way. 

Looking forward to your feedback.

**Comment by mapleyuan** [comment]
Face same problem

**Comment by eknight7** [comment]
FYI looking into fixing CameraX issues ASAP.

In the mean time, you can use a custom Camera2 utility and hook up a `SurfaceTexture` object to the `ExternalTextureConverter` as explained here: https://mediapipe.readthedocs.io/en/latest/hello_world_android.html#externaltextureconverter-setup.

**Comment by openingapps** [comment]
Any updates on a replacement for setOnPreviewOutputUpdateListener?

I am still using cameraX alpha4 in my app, but I don't want to release it that way.
Should I wait for a patch, or should I throw out camerax and reimplement with camera2.

By the way, the official documentation for camerax previews (https://developer.android.com/training/camerax/preview) still has the following quote:
> Note: If you require direct access to the SurfaceTexture, such as to perform OpenGL rendering,
> see Manually create a SurfaceTexture.

But there is no longer a section called "Manually create a surface texture".  You might want to update the documentation.

Thanks in advance for any guidance you can provide.

**Comment by MaTriXy** [comment]
Hi,
Any planned update to this?

**Comment by pianyun** [comment]
also facing this issue.
any update?

**Comment by xyz-xiang** [comment]
I find a way and it is work , wish help some one.
the lasted cameraX version is 1.0.0-beta11 and the preview case sample is below:
mProvider?.bindToLifecycle(lifecycleOwner, facing, preview )
the key is the preview
1. wo construct the preview ,  call the setSurfaceProvider , but we need implement interface about SurfaceProvider
2. the surfaceProvider have a param (SurfaceRequest) , and we call it.provideSurface() , we need provide a Surface
3. now we can constrct a SurfaceTexutre using opengles and create a Surface
4. we can use the surfaceTexture finnaly and do whatever
hope can help you

**Comment by hannesa2** [comment]
Sounds promising, do you have a code snippet ?

**Comment by eknight7** [comment]
Hi,
The cameraX API version being used by MediaPipe is now version 1.0.0-beta10 from this release: https://github.com/google/mediapipe/releases/tag/0.7.12

Closing this issue for now. Please feel free to re-open if the question is still relevant. Thank you.
