### ISSUE TITLE
Flipped Handedness in Gesture Recognition

### ISSUE THREAD

**Issue by royeden** [google/mediapipe#4724]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Linux Ubuntu 22.04

### Browser and version if the issue happens on browser

 Electron 25.6.0

### Programming Language and version

JavaScript

### MediaPipe version

@mediapipe/tasks-vision@^0.10.4

### Solution

Gesture Recognition

### Describe the actual behavior

Handedness is flipped for Gesture Recognition via webcam devices.

While testing the Gesture Recognition Task in the [web code example](https://codepen.io/mediapipe-preview/pen/zYamdVd) on a notebook, I've noticed that the handedness result is inverted (due to the camera itself being a frontal camera).

I've attempted to solve this issue by drawing the video frame into a flipped canvas, sending that to the model to process and then flipping it again when using the drawing utils. This fixes the handedness issue and also allows me to sync the output to the model input, but it incurs processing from my side to produce this and lags the process entirely by drawing every frame.

### Describe the expected behaviour

I would expect to have an option to flip the image before sending it to the gesture recognizer.

### Standalone code/steps you may have used to try to get what you need

```js
// During setup:

const context = canvas.getContext('2d')
// Flip the canvas
context.scale(-1, 1)
context.translate(-canvas.width, 0)

const drawingUtils = new DrawingUtils(context)

// Inside the gesture recognizer loop:

// Video element has the webcam stream
context.drawImage(video, 0, 0, canvas.width, canvas.height)
// Now it gets the expected handedness
const results = gestureRecognizer.recognizeForVideo(canvas, Date.now())

// Save the context and flip the canvas again to draw utils, or they will be mirrored
context.save()
context.scale(-1, 1)
context.translate(-canvas.width, 0)

for (const landmarks of results.landmarks) {
  drawingUtils.drawConnectors(landmarks, GestureRecognizer.HAND_CONNECTIONS, {
    color: "#ff0000",
    lineWidth: 5
  })
  drawingUtils.drawLandmarks(landmarks, {
    color: "#00ff00",
    lineWidth: 1,
    radius: 3
  })
}

context.restore()
```

**Comment by kuaashish** [comment]
@royeden,

The issue has been successfully addressed in the most recent release of MediaPipe, specifically in [v0.10.5](https://github.com/google/mediapipe/releases/tag/v0.10.5), as indicated in the [release notes](https://github.com/google/mediapipe/releases). "Swap left and right hand labels"

We kindly request that you verify whether the issue still persists in the latest version and promptly inform us of your findings.

Thank you

**Comment by kuaashish** [comment]
@royeden,

Could you please update the status of the above. Thank you

**Comment by royeden** [comment]
Hello! I was just able to corroborate the fix and it's working correctly!
