### ISSUE TITLE
Download the face mesh v2 tflite model

### ISSUE THREAD

**Issue by jeremmoore** [google/mediapipe#4727]
### MediaPipe Solution (you are using)

face blendshape

### Programming language

c++

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

```shell
Now I am developing an app that drives my own designed avatar using 52 blendshape. The blendshape coefficients and model inference are performed in c++. mediapipe solution shows very excellent solution for this. And face_blendshape.tflite and face mesh v2(478 landmark) are both needed. For now, I cannot find any download information about face mesh v2(mentioned in blendshape model card). The face mesh outputing 468 model (with or without attention) is the only model I can find. So it is possible to download face mesh v2 model?
```

### Will this change the current API? How?

```shell
No
```

### Please specify the use cases for this feature

```shell
Using blendshape to drive my own avatar
```

**Comment by kuaashish** [comment]
@jeremmoore,

Thank you for sharing your request. We are forwarding issue internally based on the discussion team will prioritise the request.

**Comment by schmidt-sebastian** [comment]
The only models we offer are linked here: https://github.com/google/mediapipe/blob/master/docs/solutions/models.md#face-mesh

**Comment by kevinpl07** [comment]
@jeremmoore 
You can access the tflite by by downloading the face landmarker task file [here](https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/latest/face_landmarker.task) and then unzip it from within the terminal.

```console
unzip face_landmarker.task
Archive:  face_landmarker.task
 extracting: face_detector.tflite    
 extracting: face_landmarks_detector.tflite  
 extracting: geometry_pipeline_metadata_landmarks.binarypb  
 extracting: face_blendshapes.tflite 
```
