### ISSUE TITLE
Is C++ No Longer Supported in the Updated Mediapipe?

### ISSUE THREAD

**Issue by kyaohoh** [google/mediapipe#4728]
I had previously built a program using the face_mesh_cpu target in Mediapipe before its recent update.

Now that it has been updated to provide Blendshape values, I am looking to utilize this new feature. 

However, I only see Python listed as a supported language, and C++ is not visible. 

I am inquiring whether it's possible to use the updated Face Landmark Detection feature in C++. 

If this is not possible, I am also interested in finding out if there is a way to apply blendshape-related functionalities to the legacy version.

I have an additional question. In the code examples, I noticed that the repository has shifted from 'google/mediapipe' to 'googlesamples/mediapipe'. 

Previously, I could freely modify the calculators in the 'core' section. With the revamped version, has the ability to freely modify these core calculators been restricted, or is it still possible to make changes?

++
I've read issue https://github.com/google/mediapipe/issues/4636 after checking the labels you've attached. I'm curious if it's confirmed that support for a BlendShapes-52 demo in C++ will be added.

**Comment by kyaohoh** [comment]
I've read issue #4636 after checking the labels you've attached. I'm curious if it's confirmed that support for a BlendShapes-52 demo in C++ will be added.

**Comment by kuaashish** [comment]
@kyaohoh,

We have already incorporated a **Face Landmarker API** for **C++ into our roadmap**, for other API's as well, and the corresponding documentation has been prepared for internal utilisation. This documentation will be made accessible to the public once it is deemed complete from our end. **Currently**, We are unable to furnish a **specific timeline** for its availability.

**Nevertheless**, we hold the perspective that the availability of the **blendshape function** is not extended to **legacy systems**, rendering its **implementation unfeasible**. Another, we hold again viewpoint that this feature should be made available within the new **C++ face landmark API**; **However**, We are unable to **provide confirmation at this time**.

The **repository** transition from ['google/mediapipe'](https://github.com/google/mediapipe) to ['googlesamples/mediapipe' ](https://github.com/googlesamples/mediapipe)has not yet taken place. The ['googlesamples/mediapipe'](https://github.com/googlesamples/mediapipe) repository is intended to exemplify the **fundamental steps associated** with developing applications utilising **our machine learning platform**, as outlined in the **provided guidelines** [here](https://github.com/googlesamples/mediapipe).


**At present**, We do not possess any specific guidance regarding **calculator-related inquiries**. We recommend that you **initiate a new issue**, detailing the complete problem you are encountering from your perspective. Thank you

**Comment by kyaohoh** [comment]
Thank you for the detailed explanation. May I clarify two things?

Then, does the legacy system refer to the 'face_mesh_cpu' target? Or does the legacy system refer to the 'google/mediapipe' repository? I'm curious about the criteria Google uses to distinguish between legacy systems and renewal systems in MediaPipe. Is it based on the target or the repository?

And, will the 'google/mediapipe' repository and the 'googlesamples/mediapipe' repository be integrated? Or do they exist separately and are both maintained because they serve different purposes?

**Comment by kuaashish** [comment]
@kyaohoh,

Currently, the term "face mesh CPU" pertains to our legacy system. As previously communicated, an enhanced version of the C++ codebase is prepared for internal utilization and will be made public once it reaches a state of comprehensive readiness on our part.

Regarding another inquiry, all code-related resources will be exclusively accessible through the repository located at [google/mediapipe](https://github.com/google/mediapipe). For the updated APIs, their corresponding codebase has already been released into the repository [google/mediapipe](https://github.com/google/mediapipe). You may review the codebase pertaining to [tasks](https://github.com/google/mediapipe/tree/master/mediapipe/tasks) and [model_maker](https://github.com/google/mediapipe/tree/master/mediapipe/model_maker), which are components of the novel upgraded solutions.


It is our belief that each repository has been designated to serve distinct purposes, each fulfilling a unique role. The repository located at google/mediapipe is the designated platform for the publication of the complete codebase. On the other hand, the repository at googlesamples/mediapipe is intended to elucidate the fundamental steps required to create applications utilizing our machine learning platform, serving as a resource for demonstrating capabilities through demos.

**Comment by kyaohoh** [comment]
Ah, now I just have to wait for the new facial landmark target to be added to the 'google/mediapipe' repository. Thanks for all the explanation!

**Comment by kuaashish** [comment]
@kyaohoh,

Kindly inform us if it would be appropriate to mark this matter as resolved and subsequently close the associated issue status. Thank you
