### ISSUE TITLE
Camera not configured for MediaPipe?

### ISSUE THREAD

**Issue by OliverKulinski** [google/mediapipe#4730]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 11 22H2

### Programming Language and version

Javascript

### Solution

Hands, camera_utils???

### Describe the actual behavior

```shell
Hi, rookie here,

Sorry if this info is scant, just reaching out for any obvious problem that I'm unaware of.

I am attempting to run Mediapipe in javascript and use jWeb in Max4Live (in Ableton live).
I have a new camera from eConSystems (See3CAM_24CUG - https://www.e-consystems.com/industrial-cameras/ar0234-usb3-global-shutter-camera.asp) but this camera does not register in mediapipe.

Is there any reason that this camera would not work? I'm using partial code from a demo I found on the internet. I can share the code but it is a mess.. I think it is using camera_utils from the mediapipe repo (as the script is loaded).

If you have some code that should definitely recognise the device please share.

Camera registers on webcamtests.com and works in apps and programs, but doesn't get recognised in my mediapipe code.

Thanks
```

### Describe the expected behaviour

```shell
Camera should be recognised.
```

### Standalone code/steps you may have used to try to get what you need

```shell
--
```

**Comment by kuaashish** [comment]
@OliverKulinski,

Might I kindly request you to provide the comprehensive instructions as outlined in the documentation? This will aid in enhancing our understanding of the issue at hand. Thank you

**Comment by OliverKulinski** [comment]
Sorry for the trouble,

I debugged myself and it unexpectedly works now
