### ISSUE TITLE
Tulsi for bazel is no longer maintained ,but I want to use tulsi for mediapipe ，i must use which version of mediapipe ?

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#4732]
### OS Platform and Distribution

iOS

### Programming Language and version

oc

### MediaPipe version

lastest

### Bazel version

5.2

### XCode and Tulsi versions (if iOS)

13.3.1 

### Android AAR (if android)

None

### Describe the problem

```shell
Tulsi for bazel is no longer maintained ,but I want to use tulsi for mediapipe ，i must use which version of mediapipe ?
```

### Complete Logs

```shell
Tulsi for bazel is no longer maintained ,but I want to use tulsi for mediapipe ，i must use which version of mediapipe ?
```

**Comment by kuaashish** [comment]
@chensisi0730,

Kindly grant us the opportunity to engage in internal deliberations regarding the matter. We will ensure to apprise you of any updates in due course. Thank you

**Comment by chensisi0730** [comment]
Can I go back to an earlier version of mediapipe  in order to use Tulsi  ?

**Comment by chensisi0730** [comment]
> @chensisi0730,
> 
> Kindly grant us the opportunity to engage in internal deliberations regarding the matter. We will ensure to apprise you of any updates in due course. Thank you

Can I go back to an earlier version of mediapipe in order to use Tulsi ?

**Comment by kuaashish** [comment]
@chensisi0730,

Currently, if the older version proves to be functional for your requirements, we recommend its utilisation until we receive further updates on this matter. Thank you

**Comment by chensisi0730** [comment]
> @chensisi0730,
> 
> Currently, if the older version proves to be functional for your requirements, we recommend its utilisation until we receive further updates on this matter. Thank you

So  i must use which version of mediapipe and which version of Tulsi  ?

**Comment by kuaashish** [comment]
@chensisi0730,

Following an internal deliberation, it has been determined that we will discontinue the maintenance of the Xcode Project build utilizing Tulsi for the new Task API. Instead, we advise the adoption of the Hand Landmarker iOS Task via CocoaPods, which can be found at the following URL: https://github.com/google/mediapipe/tree/master/mediapipe/tasks/ios/vision/hand_landmarker.

In the interim, you may refer to the provided documentation. Additionally, for further guidance on building, please consult the documentation available at https://developers.google.com/mediapipe/solutions/vision/face_detector/ios. Thank you
