### ISSUE TITLE
CDN  location of cjs bundle

### ISSUE THREAD

**Issue by danrossi** [google/mediapipe#4739]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 11

### Task name (e.g. Image classification, Gesture recognition etc.)

ImageSegmenter

### Programming Language and version (e.g. C++, Python, Java)

javascript,webgl

### Describe the actual behavior

```shell
It seems when trying to dynamically load the bundle via an iife package the cjs cannot be served says something about bad mimetype. And importing the default bundle only works as an inline module but the application code is contained in an iife package. bundling as es with rollup can't import external urls and prefer to keep it cdn served to keep it up to date. 

Does it need to be custom bundled and not use the cdn files ?

The test integration using inline code with the module is working but trying to integrate that can't load the bundle yet. 

https://www.jsdelivr.com/package/npm/@mediapipe/tasks-vision?tab=files
```

### Describe the expected behaviour

```shell
https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.4/vision_bundle.cjs

Served correctly. Assuming it can be dynamically included as a script to the page correctly. Or another way to dynamically include the module and see its exports.
```

### Standalone code/steps you may have used to try to get what you need

```shell
na
```

**Comment by schmidt-sebastian** [comment]
This looks like it might be more of an issue with the CDN and is unfortunately not something we can change from our end. Please take a look at https://codepen.io/mediapipe-preview to see how we import from CDN (this uses TS transpilation by Codepen). Otherwise, we would advise you to host these files yourself.

**Comment by danrossi** [comment]
Inline code is not the standard use case including ts. And neither are applications that common are setup from iife bundles with minimal involvement with inline code. My use case is dynamically loading the script in an iife bundle. 

I will try and experiment to see if it can be an es module and run like an iife bundle with no importing needed. But I dont think my code packager works well as an es6 module. I found a rollup plugin to import external modules so they are imported and resolved on demand. Otherwise rollup can't resolve and treats the import as global.

Should I contact them about it ? So the api is kept up to date and not bundled.

**Comment by danrossi** [comment]
The CJS is not usable in an iife package and therefore neither is the esm module. Like before with the selfie segmentation api. I've downloaded the bundle and included it in the page. 

```
vision_bundle.cjs:1 Uncaught ReferenceError: exports is not defined
    at vision_bundle.cjs:1:36
    ```

**Comment by danrossi** [comment]
It's all good. I tested packaging the app as a module bundle file which can also run just in time like iife without an importing and inline code needed. 

```
 <script type="module" src="bundle.js"></script>
 ```

But my scrambling service cannot build modules because eval causes issues with it. The module is wrapped into eval.

When making tasks api as an iife bundle with an export like so. I can concat the exported mediapipe iife bundle into my built bundle as a global and works. So CDN dynamic loading can't work like with the segment api as the segment api would have been a umd bundle. Although rollup is complaining about "eval" used in the task vision module. 

```
export { ImageSegmenter, FilesetResolver} from "@mediapipe/tasks-vision";
```
