### ISSUE TITLE
Reference point for 3D landmarks in hand tracking

### ISSUE THREAD

**Issue by mihaelagrigore** [google/mediapipe#474]
I have tried to localize this information in the documentation and in the code, but I simply was not able to. 
Your help is much appreciated with figuring this out: when dealing with 3D landmarks in hand tracking, the coordinates of the landmarks are given relative to what reference point ? 

Thank you,
Mihaela

**Comment by romaindebraize** [comment]
Hi @mihaelagrigore,

With 3D landmarks hand tracking the reference landmark is [LM 0](https://github.com/google/mediapipe/issues/119). You will obtain a value between -80 and 80.
