### ISSUE TITLE
Get single frame from handtrackinggpu

### ISSUE THREAD

**Issue by zerohit** [google/mediapipe#475]
How can we get the get image frame in the handtrackinggpu program. 

In the android app, i tried add a callback like this :

    processor.addPacketCallback(
        "output_video",
          (packet) -> {
          });

And i tried to extract image using these methods: 
AndroidPacketGetter.getBitmapFromRgba(packet)
PacketGetter.getProtoBytes(packet)
PacketGetter.getAudioByteData(packet)
but they all crashed.

Could someone please help ?

**Comment by eknight7** [comment]
Hi @zerohit, sorry for the delay in my response. Were you able to resolve this issue? If not, can you please explain: Are you trying to get the rendered image and save it as a file somehow?

One way to do this is to make a client class `FooFrameConsumer` to be an implementation of [TextureFrameConsumer](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/TextureFrameConsumer.java). The [FrameProcessor](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/FrameProcessor.java) already has a `PacketCallback` to [send frames](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/FrameProcessor.java#L101-L122) to every `TextureFrameConsumer` subscribed to receive updates when there are output packets available in the `videoOutputStream`, which for MediaPipe example apps is `output_video`.

Here is some pseudocode to modify the application thereafter.

```
class FooTextureConsumer implements TextureFrameConsumer {
   FooTextureConsumer() { /* do as apt here. */ }
   @Override
   public void onNewFrame(TextureFrame frame) {
      BlaOperationOnFrame(frame);
      ...
   } 
};

class MainActivity ... {
    ...
    @Override
    protected void onCreate(Bundle savedInstanceState) {
       ...
       processor = new FrameProcessor(...);
       processor.addConsumer(new FooTextureConsumer());
    }
    ....
};
```

**Comment by navneetjasrotia** [comment]
Hi @eknight7 in your FooTextureConsumer Class can you explain what is BlaOperation and how can we convert the frame into bitmap ?
