### ISSUE TITLE
what is /protobuf/GeneratedMessageLite ?

### ISSUE THREAD

**Issue by romaindebraize** [google/mediapipe#476]
Hi,

I am using the hand tracking for mobile on Android. I have already built the app on my phone and all works fine. 
Now I am trying to make a native android plugin with hand tracking in order to use it in Unity. I am struggling with this error when i use the plugin i have created :

```
 E/Unity: AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/protobuf/GeneratedMessageLite;
```

Indeed, in the aar created with mediapipe there is no class com.google.mediapipe.protobuf ....
Any idea to solve this issue ? 

Thanks

**Comment by rithgoog** [comment]
@romaindebraize Did you ever figure this out?
