### ISSUE TITLE
MediaPipe's development stage

### ISSUE THREAD

**Issue by heerah1993** [google/mediapipe#4760]
Hi

I would like to know in what phase of Development Mediapipe is? Is it in alpha, beta or stable/Production?

I saw in the following website that it is in Alpha stage. https://pypi.org/project/mediapipe/

[Development stage mentioned in PyPi](https://i.stack.imgur.com/Imx6L.png)

Please clarify the Mediapipe's development status.

Thank you

**Comment by kuaashish** [comment]
@heerah1993,

Could you please go through the above comment and let us know if we mark this issue as resolved. Thank you
