### ISSUE TITLE
About installing Mediapipe

### ISSUE THREAD

**Issue by ajunyo** [google/mediapipe#4761]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows10

### Task name (e.g. Image classification, Gesture recognition etc.)

Mediapipe

### Programming Language and version (e.g. C++, Python, Java)

python

### Describe the actual behavior

```shell
I want to use the compiled opencv with cuda (including contrib) to install Mediapipe, but it cannot be installed.
It can only be successfully installed through pip's opencv python installation. How should we solve it.
```

### Describe the expected behaviour

```shell
.
```

### Standalone code/steps you may have used to try to get what you need

```shell
.
```

**Comment by schmidt-sebastian** [comment]
Please follow the installation guide at https://developers.google.com/mediapipe/framework/getting_started/install.md#installing_on_windows
