### ISSUE TITLE
Android C++ crash pose tracking (Legacy)

### ISSUE THREAD

**Issue by endink** [google/mediapipe#4763]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Android 11

### MediaPipe version

0.10.2

### Bazel version

6.1.1

### Solution

Pose Tracking

### Programming Language and version

C++

### Describe the actual behavior

As a test, I created a simply  pose tracking graph (using mediapipe/framework/api2/builder), but the program crashed when executing graph initialize, and I wonder if the Android platform can be used without Java code ( witout JNI)?

The problem occurs in `ExpandSubgraphs` function of [subgraph_expansion.cc](https://github.com/google/mediapipe/blob/master/mediapipe/framework/tool/subgraph_expansion.cc) with this line of code:
```cpp
!graph_registry->IsRegistered(config->package(),node.calculator());
```

It looks like it crashes when checking for an “unregistered” calculator, in my case ,this calculator is `RecolorCalculator`, the same code and BUILD files don't go wrong under Windows.

```shell
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=0 --linkopt="-s" --config=android_arm64  --action_env PYTHON_BIN_PATH=${PY} mediapipe/unreal:mediapipe_api --define use_android=true 
```

I used WSL (unbuntu) to compile and the compilation went very smoothly.

BTW: Please explain what the `MEDIAPIPE_NO_JNI` compile argument does, and if you open it, it will point to a file that doesn't exist: `resource_util_loonix.cc`.
```

**Comment by kuaashish** [comment]
@endink,

We don’t have official Windows support for C++. Need to fix our CI pipeline for Windows to have any guarantee. However, Only official support we have Python for Windows (and Web). For now, We can not commit anytime to fix it.

**Comment by endink** [comment]
I compiled mediapipe into a `.so` file with **NDK** toolchain (**Android** arm64), and it got an error at runtime. I just wanted to know if I had to use ARR and mediapipe java code? or its a bug on **Android**.

This has nothing about Windows, I'm asking questions about android C++ ....

**Comment by endink** [comment]
@kuaashish 

I debugged myself and found that the program crashes in  `ExpandSubgraphs` function （`subgraph_expansion.cc`)

**Comment by endink** [comment]
I think this the same issue: #4682

**Comment by endink** [comment]
More detail: #4781
