### ISSUE TITLE
Can Mediapipe be used commercially for free?

### ISSUE THREAD

**Issue by Hynsn** [google/mediapipe#4764]
Hi All.
     I‘ m a android developer. I want to know can Mediapipe be used commercially for free? include Mediapipe ML model。

**Comment by kuaashish** [comment]
@Hynsn,

Certainly, MediaPipe **can be employed for commercial purposes**, and MediaPipe is **under Apache 2.0**, as outlined in the terms and conditions specified in https://github.com/google/mediapipe/blob/master/LICENSE, And screenshot attached below:
<img width="1399" alt="Screenshot 2023-09-06 at 3 34 02 PM" src="https://github.com/google/mediapipe/assets/98159216/ab9f8084-4dc8-4ba5-b447-b5b96c9ad679">

For a more comprehensive understanding, I kindly request that you refer to the previously mentioned terms and conditions.
Thank you

**Comment by kuaashish** [comment]
@Hynsn,

Could you please go through the above comment and let us know if we mark this issue as resolved. Thank you
