### ISSUE TITLE
on-device-diffusion-plugins ?

### ISSUE THREAD

**Issue by maceip** [google/mediapipe#4768]
recently y'all posted excellent work: https://ai.googleblog.com/2023/06/on-device-diffusion-plugins-for.html

that article links to the [MediaPipe image generation app](https://mediapipe.page.link/on-device-diffusion-plugins) but it redirects to /

https://mediapipe.page.link/on-device-diffusion-plugins

where's the code?

cc https://github.com/googlesamples/mediapipe/issues/181

**Comment by kuaashish** [comment]
@maceip,

As noted here, In the [page](https://developers.google.com/mediapipe/solutions/vision/image_generator), 

_"The MediaPipe Image Generator is coming soon! Get a sneak peek of its capabilities by trying out the [Image Generator demo app](https://developers.google.com/mediapipe/solutions/vision/image_generator#image_generator_demo_app)._"

You may now proceed to verify and install the prebuilt Image Generator demonstration application by using the guide [here](https://developers.google.com/mediapipe/solutions/vision/image_generator), Which will allow you to explore its capabilities. 

Nevertheless, the remaining source codes and comprehensive documentation pertaining to supported platforms will be made fully accessible on the respective [page](https://developers.google.com/mediapipe/solutions/vision/image_generator) once they have been finalised on our part. At present, we regret to inform you that we are unable to provide a specific timeframe for their availability. Thank you.

**Comment by kelisiya** [comment]
will support LCM to make model faster ?
