### ISSUE TITLE
Macos Catalina Hand tracking

### ISSUE THREAD

**Issue by nov08demo** [google/mediapipe#477]
Hi, I am trying to run the hand tracking example on my macbook pro 16 which is running catalina. I followed the installation process successfully and ran the following commands:

$ bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu
$ GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_cpu \
    --calculator_graph_config_file=mediapipe/graphs/hand_tracking/multi_hand_tracking_desktop_live.pbtxt

and got the following output: 

I0225 10:35:16.197036 499596736 demo_run_graph_main.cc:53] Initialize the calculator graph.
I0225 10:35:16.200453 499596736 demo_run_graph_main.cc:57] Initialize the camera or load the video.
I0225 10:35:18.714452 499596736 demo_run_graph_main.cc:78] Start running the calculator graph.
I0225 10:35:18.714884 499596736 demo_run_graph_main.cc:83] Start grabbing and processing frames.
I0225 10:35:19.715039 499596736 demo_run_graph_main.cc:135] Shutting down.
I0225 10:35:19.954938 499596736 demo_run_graph_main.cc:149] Success!

it runs but then suddenly shuts down with no warnings or errors. The camera is working and I allowed the program permission to access the camera when the initial permissions window popped up. I also attempted running the same example on a separate machine runningMacOs Mojave, which gave me no issues and ran perfectly. Any  reason why it doesnt run on Catalina or mac pro 16"?

**Comment by mcclanahoochie** [comment]
Related https://github.com/google/mediapipe/issues/424

Does providing a [video](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/demo_run_graph_main.cc#L36) work?  
`--input_video_path=/tmp/video.mp4`
Our team hasn't had the opportunity to test on the new Mac OS yet.

Have you tried [this](https://support.apple.com/ko-kr/guide/mac-help/mchlf6d108da/mac) ?

**Comment by nov08demo** [comment]
Hi I have tried the permissions in settings, still no luck

**Comment by Akathian** [comment]
> Related #424
> 
> Does providing a [video](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/demo_run_graph_main.cc#L36) work?
> `--input_video_path=/tmp/video.mp4`
> Our team hasn't had the opportunity to test on the new Mac OS yet.
> 
> Have you tried [this](https://support.apple.com/ko-kr/guide/mac-help/mchlf6d108da/mac) ?

Having the same issue here. This did not work for me either.

**Comment by nov08demo** [comment]
Hi have you guys had a chance to test on Catalina yet? We are still encountering the same issue

**Comment by mcclanahoochie** [comment]
Update: I have just [in-place] upgraded my 2017 macbook 15" to macOS Catalina (10.15.3), and had no issues running the multi-hand desktop demo using the built-in webcam.

Granted, this demo was running fine before the upgrade, but at least I can confirm the upgrade to catalina didn't break things (on my machine). Also, I don't remember doing any special permissions (or was never prompted to by the OS). 

The unknowns are if there is something unique about the 16" macbook, and/or something odd about a "fresh/clean" install of Catalina OS (what the 16" comes with), or just something else not setup correctly.

Do *all* examples have this problem for people with 16" macbooks? 
What version of OpenCV are people using? 
Does the PhotoBooth app work fine?

**Comment by mcclanahoochie** [comment]
list of things to try:
- Terminal /iTerm Camera [permissions](https://support.apple.com/ko-kr/guide/mac-help/mchlf6d108da/mac)
- try video via:  --input_video_path=/tmp/video.mp4 
- see if a simple separate [python](https://subscription.packtpub.com/book/application_development/9781785283932/3/ch03lvl1sec28/accessing-the-webcam) or [c++](https://www.learnopencv.com/read-write-and-display-a-video-using-opencv-cpp-python/) example works
- try a command line capture [program](https://stackoverflow.com/a/58139184)
- going through other suggestions [here](https://stackoverflow.com/questions/56084303/opencv-command-line-app-cant-access-camera-under-macos-mojave/58139184#58139184)
- [try to run ](https://github.com/opencv/opencv/blob/e98852a389b6d9835376003335ea253597d8c7c1/modules/videoio/src/cap_avfoundation_mac.mm#L333) "tcutil reset Camera" in a terminal (no quotes)
- 
if i think of others i can update the list (or if something starts working let me know)

**Comment by nov08demo** [comment]
Hi, we seems to have it working now an older 2015 mac on catalina. The issue seems to persist on the new 16" macs tho, tried the different suggestion you made.

**Comment by mcclanahoochie** [comment]
Possible solution from here: 
https://stackoverflow.com/a/58997222
(slightly modified by me below)

Info:
Every app on Mac OS/iOS/watches OS needs privacy permission from the user before accessing features like camera/ mic/ gallery etc. These permissions are stored in a property list file generally "info.plist". Now as this app will run on the mac itself you need to specify permissions before running.

Solution:
Go to the following on your mac (i'm using iTerm2 to run MediaPipe): 
Finder -> Applications -> iTerm (right-click to show package contents) -> Contents -> Info.plist

Now open "Info.plist" file with any plain text editor and paste the following code right after the opening <dict> tag, which is probably in 4th or 5th line:

```
<key>NSCameraUsageDescription</key>
<string>An application in iTerm2 wants to use the camera.</string>
```
(the above <> was taken from my working iTerm.app info.plist)

**Comment by agrawalramakant** [comment]
Still does not work for me in Mac 16 inch 2019 model.

**Comment by lolanchen** [comment]
Having the same issue when trying to run the face_mesh example, also on the 16' Macbook pro.

**Comment by peterjzhou** [comment]
Same problem met here for 16' MacBook Pro.

**Comment by lcwill** [comment]
I've encountered the same issue described in the original post, with a 16" 2019 MBP running Catalina (10.15.6).

The issue for me seems to be in this section of the code, at the beginning of the image frame processing loop:
```
    // Capture opencv camera or video frame.
    cv::Mat camera_frame_raw;
    capture >> camera_frame_raw;
    if (camera_frame_raw.empty()) break;  // End of video.
```

Apparently, the first frame of the video is empty, i.e. `camera_frame_raw.empty()` returns true, perhaps due to there being some delay between the camera being initialized and video being captured. Modifying the above code as follows allowed me to workaround this issue:
```
    // Capture opencv camera or video frame.
    cv::Mat camera_frame_raw;
    capture >> camera_frame_raw;
    if (camera_frame_raw.empty()) {
      if (!load_video) {
        // Ignore empty frames from camera feed
        continue;
      }
      LOG(INFO) << "Empty frame, end of video reached";
      break;
    }
```

**Comment by yasithmilinda** [comment]
This solution worked for me!

**Comment by abreu4** [comment]
Also worked for me

**Comment by ianni67** [comment]
I got the same problem and fixed it the same way on my ubuntu box. Thank you for pointing it out.
This solution should go upstream, as the issue is well-known also for linux. All programs acquiring live video from webcam with OpenCV should have this check, independently from the OS.

**Comment by S3od22** [comment]
[]()

**Comment by mcclanahoochie** [comment]
Thanks for the updates. The fix has been integrated and should be in the next release.

**Comment by ianni67** [comment]
Sorry for bothering again. I would suggest to extend the fix to the python version of the demo software, too. In my experience the python version of OpenCV suffers from the same issue.
