### ISSUE TITLE
Downloading individual FaceLandmarker models

### ISSUE THREAD

**Issue by markpredigertrinamix** [google/mediapipe#4772]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Embedded

### Task name (e.g. Image classification, Gesture recognition etc.)

Face detection and landmarks

### Programming Language and version (e.g. C++, Python, Java)

C++

### Describe the actual behavior

```shell
We attempting to use Mediapipe face detection and landmarks on a custom embedded platform. We can run neural networks of usual formats like tensorflow(lite) or ONNX. However, the models available at https://developers.google.com/mediapipe/solutions/vision/face_landmarker are .task files, and we could't find any documentation of the file format, except the flatbuffer schema files.
```

### Describe the expected behaviour

```shell
Where can we download the individual "FaceDetector" and "FaceMesh-V2" model files? Or can we extract them from the .task file? 

For the lecacy pipeline, model files are available at https://github.com/google/mediapipe/blob/master/docs/solutions/models.md.
```

### Standalone code/steps you may have used to try to get what you need

```shell
-
```

**Comment by kuaashish** [comment]
@markpredigertrinamix,

Certainly, you have the capability to extract the FaceDetector TFLite model file and the FaceMesh-V2 model file from the facelandmarker.task task file by downloading through the guide [here](https://developers.google.com/mediapipe/solutions/vision/face_landmarker#models) and executing the following command:


`unzip face_landmarker.task `

Additionally, we kindly request confirmation regarding the status of this matter from your perspective. If it has been successfully addressed, may we proceed to mark this issue as resolved and formally close it? Thank you

**Comment by markpredigertrinamix** [comment]
Thanks! I would have found it very beneficial it it were mentioned somethere in the docs that a .task file is just a zip file.
