### ISSUE TITLE
Object detector model tflite model does not output location, category, score, and number of detections.

### ISSUE THREAD

**Issue by tahiyasalam** [google/mediapipe#4774]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

MacOS 13.4

### Python Version

Python 3.10.12

### MediaPipe Model Maker version

0.2.1.3

### Task name (e.g. Image classification, Gesture recognition etc.)

Object detector

### Describe the actual behavior

When exporting the tflite model, the outputs are the location and score, with custom metadata about the anchor generators.

### Describe the expected behaviour
The [model requirements and metadata](https://developers.google.com/mediapipe/solutions/vision/object_detector#model_requirements_and_metadata) listed seem to suggest that in order to comply with the task, the tflite model metadata should contain location, score, category, and number of detections.

### Standalone code/steps you may have used to try to get what you need

Using [this](https://developers.google.com/mediapipe/solutions/customization/object_detector#export_model) sample code for `model.export()`, we can see that we are exporting a model without postprocessing the raw box and class predictions. 

As of [this change](https://github.com/google/mediapipe/commit/61cfe2ca9bacf914c64bb57d4b841263f9b91d67#diff-6c632ef2fd21aca60311efb4596fa2d5146ed684a07735411742087283e479ce), we are no longer exporting the model with nms. Is it possible to have an option to export with nms as well? Without that, is there an easy way to convert the exported MediaPipe object detector model in order to maintain parity with the recommended output?

**Comment by joezoug** [comment]
Hi @tahiyasalam,

I believe the (model requirements and metadata)[https://github.com/google/mediapipe/issues/4774#:~:text=model%20requirements%20and%20metadata] page needs to be updated as the new output format(without NMS) is still compatible with the MediaPipe Object Detector Task. In fact, this is now the preferred format as it allows the model to be run on both GPU and CPU while previously the model with NMS could only be run on CPU.

We will not support the old export format with NMS, but if you need it you can revert your version to (the change)[https://github.com/google/mediapipe/commit/61cfe2ca9bacf914c64bb57d4b841263f9b91d67#diff-6c632ef2fd21aca60311efb4596fa2d5146ed684a07735411742087283e479ce] and try exporting.

**Comment by architjaiswal** [comment]
I am still confused on how to convert the model such that it gets the same 4 outputs I was initially giving. I also saved the model using `model.export_model(model.export_model(model_name=model_out, quantization_config=quantization_config)`

Can someone tell me how to convert the trained model to obtain the 4 output (locations, classes, scores, detections)?

I was trying to run inference in C++ using the following code but it failed due to output mismatch:
````cpp
    // https://www.tensorflow.org/lite/models/object_detection/overview#starter_model
    TfLiteTensor *output_locations =
        interpreter->tensor(interpreter->outputs()[0]);
    TfLiteTensor *output_classes =
        interpreter->tensor(interpreter->outputs()[1]);
    TfLiteTensor *output_scores =
        interpreter->tensor(interpreter->outputs()[2]);
    TfLiteTensor *output_detections =
        interpreter->tensor(interpreter->outputs()[3]);
````
