### ISSUE TITLE
Improved model release

### ISSUE THREAD

**Issue by ahmed-shariff** [google/mediapipe#478]
Is there a timeline/update on when you'll release improved models?

As discussed in #450, #217, etc. the low precision is a problem. I myself am working on microgesture recognition. Would be cool to see an update on this issue.

Cheers.

**Comment by mgyong** [comment]
If we have a newer and significantly better model, we will push updates. As of 18 Mar 2020, we do not have planned updates to models

**Comment by mgyong** [comment]
@ahmed-shariff We have updated the hand model in [v0.7.5](https://github.com/google/mediapipe/releases/tag/v0.7.5). Pls check it out and give us feedback
