### ISSUE TITLE
"Error in glob: recursive wildcard must be its own segment" and "no such target '@linux_opencv//:opencv'" 

### ISSUE THREAD

**Issue by VieiraJardel** [google/mediapipe#4780]
### OS Platform and Distribution

Linux4Tegra, based on Ubuntu 18.04

### Compiler version

gcc / g++ 8

### Programming Language and version

Python 3.6.9

### MediaPipe version

0.8.9

### Bazel version

4.2.1

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.5.0

### Describe the problem

I'm trying to build MediaPipe frombazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu

### Complete Logs

```shell
jv@jv-desktop:~/mediapipe-0.8.9$ bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
DEBUG: /home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: Traceback (most recent call last):
	File "/home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/linux_opencv/BUILD.bazel", line 16, column 16, in <toplevel>
		hdrs = glob([
Error in glob: recursive wildcard must be its own segment
ERROR: /home/jv/mediapipe-0.8.9/third_party/BUILD:186:6: no such target '@linux_opencv//:opencv': target 'opencv' not declared in package '' defined by /home/jv/.cache/bazel/_bazel_jv/60c21662ba14e54423ed5cde1c698284/external/linux_opencv/BUILD.bazel and referenced by '//third_party:opencv_binary'
ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu' failed; build aborted: Analysis failed
INFO: Elapsed time: 2,037s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (6 packages loaded, 19 targets con\
figured)


I have no idea how to solve this problem
```

**Comment by VieiraJardel** [comment]
new_local_repository(
    name = "linux_opencv",
    build_file = "@//third_party:opencv_linux.BUILD",
    path = "/usr/local",


cc_library(
    name = "opencv",
    hdrs = glob([
        # For OpenCV 4.x
        #"include/aarch64-linux-gnu/opencv4/opencv2/cvconfig.h",
        #"include/arm-linux-gnueabihf/opencv4/opencv2/cvconfig.h",
        #"include/x86_64-linux-gnu/opencv4/opencv2/cvconfig.h",
        "/usr/include/opencv4/opencv2**/*.h*",
    ]),
    includes = [
        # For OpenCV 4.x
        #"include/aarch64-linux-gnu/opencv4/",
        #"include/arm-linux-gnueabihf/opencv4/",
        #"include/x86_64-linux-gnu/opencv4/",
        "/usr/include/opencv4/",
    ],
    linkopts = [
        "lib/libopencv_core.so",
        "lib/libopencv_calib3d.so",
        "lib/libopencv_features2d.so",
        "lib/libopencv_highgui.so",
        "lib/libopencv_imgcodecs.so",
        "lib/libopencv_imgproc.so",
        "lib/libopencv_video.so",
        "lib/libopencv_videoio.so",
    ],
    visibility = ["//visibility:public"],

**Comment by kuaashish** [comment]
@VieiraJardel,

It appears that you are attempting to deploy MediaPipe on a Jetson Nano edge device running Linux4Tegra, based on Ubuntu 18.04. Please note that our team currently does not offer support for this specific configuration. However, there are community-developed [plugin](https://github.com/anion0278/mediapipe-jetson) that may be more current and suitable for your needs in this context. It is essential to understand that we do not offer guidance on how to utilise this plugin.

If you encounter additional errors while working with this plugin, we recommend following best practices by reporting the issues within the respective repository and engaging with the community there for further assistance.

**Comment by VieiraJardel** [comment]
I'm sorry. 
The problem was in this line: "include/opencv4/opencv2**/.h",
The correct line is: "include/opencv4/opencv2/**/.h",
