### ISSUE TITLE
Wrong recognition of left and right hands

### ISSUE THREAD

**Issue by Axkgag** [google/mediapipe#4785]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows11

### Programming Language and version

Python

### MediaPipe version

0.10.3

### Solution

Hands

### Describe the actual behavior

When there is only one hand in the picture, the problem of wrong recognition of left and right hands occurs

### Describe the expected behaviour

The left-handed label should be “Left”, and the right-handed label should be “Right”

### Standalone code/steps you may have used to try to get what you need

```shell
import cv2
import mediapipe as mp
import math
from collections import deque

mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
        static_image_mode=False,
        model_complexity=1,
        max_num_hands=4,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5)


data_path = "test.mp4"
save_path = "results.mp4"
cap = cv2.VideoCapture(data_path)

frame_rate = int(cap.get(cv2.CAP_PROP_FPS))
frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))  # 2560
frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))  # 1440

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
outVideo = cv2.VideoWriter(save_path, fourcc, frame_rate, (frame_width, frame_height))

while True:
    ret, frame = cap.read()
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    results = hands.process(frame)
    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)

    hands_list = []

    if results.multi_handedness:
        for hand_label in results.multi_handedness:
            hand_name = hand_label.classification[0].label
            hands_list.insert(0, hand_name)
            print(hand_label)

    if results.multi_hand_landmarks:

        hand_local = {
            "Right_thumb": None,
            "Right_index_finger": None,
            "Left_thumb": None,
            "Left_index_finger": None
        }

        for i in range(len(results.multi_hand_landmarks)):
            hand_name = hands_list[i]
            hand_color = (0, 0, 0) if hand_name == "Right" else (255, 255, 255)

            thumb_tip = results.multi_hand_landmarks[i].landmark[4]
            index_finger_tip = results.multi_hand_landmarks[i].landmark[8]

            if hand_name == "Right":
                hand_local["Right_thumb"] = (
                    min(thumb_tip.x * frame_width, frame_width - 1),
                    min(thumb_tip.y * frame_height, frame_height - 1)
                )
                hand_local["Right_index_finger"] = (
                    min(index_finger_tip.x * frame_width, frame_width - 1),
                    min(index_finger_tip.y * frame_height, frame_height - 1)
                )
            elif hand_name == "Left":
                hand_local["Left_thumb"] = (
                    min(thumb_tip.x * frame_width, frame_width - 1),
                    min(thumb_tip.y * frame_height, frame_height - 1)
                )
                hand_local["Left_index_finger"] = (
                    min(index_finger_tip.x * frame_width, frame_width - 1),
                    min(index_finger_tip.y * frame_height, frame_height - 1)
                )

        for name, point in hand_local.items():
            if point:
                hand_name = name.split("_")[0]
                hand_color = (0, 0, 0) if hand_name == "Right" else (255, 255, 255)
                cv2.circle(frame, (math.floor(point[0]), math.floor(point[1])), 2, hand_color, 2)
                font_text = hand_name + "_" + str(len(results.multi_hand_landmarks))
                cv2.putText(frame, font_text, (math.floor(point[0]), math.floor(point[1])), cv2.FONT_HERSHEY_SIMPLEX, 1, hand_color, 1)

        for hand_landmarks in results.multi_hand_landmarks:
            mp_drawing.draw_landmarks(
                frame, hand_landmarks, mp_hands.HAND_CONNECTIONS)
    outVideo.write(frame)

cap.release()
outVideo.release()
```

### Other info / Complete Logs

```shell
When there is only one hand in the picture, you can find that the label in "multi_handedness" is wrong


    if results.multi_handedness:
        for hand_label in results.multi_handedness:
            hand_name = hand_label.classification[0].label
            hands_list.insert(0, hand_name)
            print(hand_label)
```
```

**Comment by Axkgag** [comment]
![Uploading image.png…]()

**Comment by Axkgag** [comment]
![image](https://github.com/google/mediapipe/assets/92363724/001302aa-d036-45c4-8831-6b6bce27cc4d)

**Comment by kuaashish** [comment]
@Axkgag,

The issue has been successfully addressed in the most recent release of MediaPipe, specifically in [v0.10.5](https://github.com/google/mediapipe/releases/tag/v0.10.5), as indicated in the [release notes](https://github.com/google/mediapipe/releases). _"Swap left and right hand labels_" 

We kindly request that you verify whether the issue still persists in the latest version and promptly inform us of your findings. Please be advised that the provided code does not yield reproducible results on our end. Thank you

**Comment by Axkgag** [comment]
Thank you very much for your reply, but I still found this issue after updating to the latest version of mediapipe v0.10.5
![2](https://github.com/google/mediapipe/assets/92363724/f442b840-a982-4ade-99ec-9f87ffa18a9f)
![results_2](https://github.com/google/mediapipe/assets/92363724/74a7ef25-3017-4be5-9005-b702fed0f85d)
![issue1](https://github.com/google/mediapipe/assets/92363724/42e3b923-88b9-4460-b701-e670c6084ade)

**Comment by kuaashish** [comment]
@Axkgag,

Could you kindly furnish us with the complete code that you are utilising to replicate the issue on our end? Alternatively, sharing it through a Colab gist would be greatly appreciated as it would facilitate a more effective debugging process. Currently, the code you have provided cannot be reproduced on our end.

**Comment by Axkgag** [comment]
import cv2
import mediapipe as mp
import math
from collections import deque

print("mediapipe version: ", mp.__version__)

mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
        static_image_mode=True,
        model_complexity=1,
        max_num_hands=4,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5)


data_path = ""
save_path = ""

img = cv2.imread(data_path)

results = hands.process(img)

if results.multi_handedness:
    for hand_label in results.multi_handedness:
        print(hand_label)

if results.multi_hand_landmarks:
    for hand_landmarks in results.multi_hand_landmarks:
        mp_drawing.draw_landmarks(img, hand_landmarks, mp_hands.HAND_CONNECTIONS)

cv2.imwrite(save_path, img)

**Comment by Axkgag** [comment]
these are test pictures:
![test1](https://github.com/google/mediapipe/assets/92363724/48f6262f-8e77-42d2-9dda-9aa8ceb0289f)
![test2](https://github.com/google/mediapipe/assets/92363724/07b08fa3-b903-40cf-91b6-0b5016a1ef15)
![test3](https://github.com/google/mediapipe/assets/92363724/2537c82d-9e73-4298-9e50-e3cc5595eb37)

**Comment by Axkgag** [comment]
these are the results:
![results1](https://github.com/google/mediapipe/assets/92363724/4a867f94-0c4f-4cf8-bef9-aeae6cf2db4f)
![results2](https://github.com/google/mediapipe/assets/92363724/bb8659f2-2d0c-4086-95f9-0a0246f18f94)
![results3](https://github.com/google/mediapipe/assets/92363724/ad8a91ce-6586-4e74-bdac-acea8d92e12a)

**Comment by Axkgag** [comment]
you can try it with the code and images I provided

```python
import cv2
import mediapipe as mp
import math
from collections import deque

print("mediapipe version: ", mp.__version__)

mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
        static_image_mode=True,
        model_complexity=1,
        max_num_hands=4,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5)


data_path = ""
save_path = ""

img = cv2.imread(data_path)
h, w, c = img.shape

results = hands.process(img)

if results.multi_handedness:
    hand_nums = len(results.multi_handedness)
    for hand_label in results.multi_handedness:
        print(hand_label)
        hand_name = hand_label.classification[0].label

if results.multi_hand_landmarks:
    for hand_landmarks in results.multi_hand_landmarks:
        mp_drawing.draw_landmarks(img, hand_landmarks, mp_hands.HAND_CONNECTIONS)

cv2.putText(img, "hand nums: " + str(hand_nums), (int(0.5 * w), int(0.1 * h)),
                        cv2.FONT_HERSHEY_SIMPLEX, 3, (0, 0, 255), 3)
cv2.putText(img, "hand name: " + hand_name, (int(0.5 * w), int(0.2 * h)),
                        cv2.FONT_HERSHEY_SIMPLEX, 3, (0, 0, 255), 3)

cv2.putText(img, "mediapipe version: " + str(mp.__version__), (int(0.7 * w), int(0.95 * h)),
                        cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)

cv2.imwrite(save_path, img)
```

**Comment by kuaashish** [comment]
@Axkgag

You are currently utilising the legacy MediaPipe hand solution, which is no longer maintained by our team. We kindly advise you to refer to our [guide](https://developers.google.com/mediapipe/solutions/guide#legacy), where it is indicated that the hand solution has been upgraded to the new Hands API. 

We earnestly request that you transition to our new Hand Task API as outlined in the provided documentation [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/python). Additionally, you can find a [code example](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/hand_landmarker/python/hand_landmarker.ipynb) in the same resource for your reference. Also, we request please report back if you observe similar behaviour in the upgraded task API. Thank you
