### ISSUE TITLE
Python support for protobuf >= 4.21.5 for Firebase Functions support

### ISSUE THREAD

**Issue by evulse** [google/mediapipe#4788]
### MediaPipe Solution (you are using)

Pose Landmark

### Programming language

Python

### Are you willing to contribute it

No

### Describe the feature and the current behaviour/state

Mediapipe currently uses a requirement of protobuf < 4 which makes it incompatiable with Firebase and Cloud functions and more specifically the Eventarc system.

### Will this change the current API? How?

N/A

### Who will benefit with this feature?

All firebase users and developers

### Please specify the use cases for this feature

This will allow people to use the python implementation in Firebase to be able to run serverless pipeline and background tasks for their firebase Mobile/Web apps. It also allows the creation of Firebase extensions so that mediapipe can easily be one click integrated with Mobile applications

### Any Other info

You can see the required dependency here -> https://github.com/googleapis/google-cloudevents-python/issues/242

Information for firebase functions -> https://firebase.blog/posts/2023/07/cloud-functions-firebase-ga-and-python

**Comment by kuaashish** [comment]
@evulse,

Thank you raising this request, We are forwarding this feature internally, Based on the discussion, Team will prioritise the work. But for now, We can not provide any timeline to be implemented.

**Comment by uriafranko** [comment]
Any one tested changing the requirements to 5>proto to see if it's really breaks any thing?
