### ISSUE TITLE
hello world desktop example is failed

### ISSUE THREAD

**Issue by cihansimsir** [google/mediapipe#479]
I tried to start program with this command 
$ bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/hello_world:hello_world

and result is:

INFO: Build options --copt and --define have changed, discarding analysis cache.
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (0 packages loaded, 1207 targets configured).
INFO: Found 1 target...
ERROR: /home/cihans/mediapipe/mediapipe/examples/desktop/hello_world/BUILD:19:1: Linking of rule '//mediapipe/examples/desktop/hello_world:hello_world' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-fastbuild/bin/mediapipe/examples/desktop/hello_world/hello_world-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-fastbuild/bin/external/com_github_glog_glog/_objs/glog/utilities.pic.o:utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_Ux86_64_getcontext'
bazel-out/k8-fastbuild/bin/external/com_github_glog_glog/_objs/glog/utilities.pic.o:utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_ULx86_64_init_local'
bazel-out/k8-fastbuild/bin/external/com_github_glog_glog/_objs/glog/utilities.pic.o:utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_ULx86_64_get_reg'
bazel-out/k8-fastbuild/bin/external/com_github_glog_glog/_objs/glog/utilities.pic.o:utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_ULx86_64_step'
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 50.151s, Critical Path: 34.41s
INFO: 249 processes: 249 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

Thank you.

**Comment by jiuqiant** [comment]
Please append --define 'libunwind=true' to the bazel command. A fresh system usually doesn't have libunwind installed by default. But if your system has libunwind, then the define flag is needed.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
