### ISSUE TITLE
Image classification customization - one label

### ISSUE THREAD

**Issue by ezawadzki** [google/mediapipe#4791]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Debian 11.7

### Python Version

3.9.2

### MediaPipe Model Maker version

0.2.1.3

### Task name (e.g. Image classification, Gesture recognition etc.)

Image classification

### Describe the actual behavior

After training on only one label, the label is detected at 100% every time with no variation

### Describe the expected behaviour

After customization with only one label, the scoring should vary less or more

### Standalone code/steps you may have used to try to get what you need

```shell
I followed this tutorial :

https://developers.google.com/mediapipe/solutions/customization/image_classifier

Dataset :
You can you your flowers dataset, just take one folder "daisy" for example
```

**Comment by WhiteHoot** [comment]
Are you attempting a binary classification (ex. daisy and non daisy) ? If so you need a 0 class, basically you have to have 2 dataset, **non_daisy** for **Class 0** and **daisy** for **Class 1**, for class 0 you can have random images that aren't daisies.

**Comment by joezoug** [comment]
@ezawadzki,

What @WhiteHoot said is correct, you will need to at least provide one other class of 'non_daisy' so that the dataset contains examples of daisies and non-daisies.
