### ISSUE TITLE
@bazel_tools BUILD error

### ISSUE THREAD

**Issue by jenniferxuu** [google/mediapipe#4794]
### OS Platform and Distribution

Ubuntu 20.04

### Programming Language and version

C++

### Android AAR (if android)

None

### Describe the problem

I cloned the most recent version of the MediaPipe repo. When I tried to build, it said I had errors regarding @bazel_tools and @platforms and linked a Git Issue. I followed the steps on the Git issue, but am still having trouble BUILDing.

### Complete Logs

```shell
Starting local Bazel server and connecting to it...
ERROR: /home/jxu/.cache/bazel/_bazel_jxu/0e2caeac5a152f729bb471abb656425c/external/bazel_tools/platforms/BUILD:84:6: in alias rule @bazel_tools//platforms:linux: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /home/jxu/.cache/bazel/_bazel_jxu/0e2caeac5a152f729bb471abb656425c/external/bazel_tools/platforms/BUILD:84:6: Analysis of target '@bazel_tools//platforms:linux' failed
ERROR: /home/jxu/mediapipe-pytorch/examples/BUILD:3:10: While resolving toolchains for target //examples:pytorch_inference: Target @local_execution_config_platform//:platform was referenced as a platform, but does not provide PlatformInfo
```

**Comment by kuaashish** [comment]
@jenniferxuu,

Could you elaborate your query with complete details, Also, please let us know the complete steps you are following from the documentation. Thank you

**Comment by jenniferxuu** [comment]
After cloning the MediaPipe repo, I tried to build an example. The error is as shown above on the logs. The error message linked [this Git issue](https://github.com/bazelbuild/bazel/issues/8622), so I followed the directions of running these commands but am still having the Bazel issue:
`sed 's$@bazel_tools//platforms:(linux|osx|windows|android|freebsd|ios|os)$@platforms//os:\1$' -E -i **/*
sed 's$@bazel_tools//platforms:(cpu|x86_32|x86_64|ppc|arm|aarch64|s390x)$@platforms//cpu:\1$' -i -E **/*`

**Comment by jenniferxuu** [comment]
@kuaashish 

Following up!

**Comment by kuaashish** [comment]
@jenniferxuu,


May we kindly request your confirmation regarding whether you are actively seeking a resolution for the issue, or if it is no longer a concern from your perspective? If the matter persists, we would appreciate your assistance in providing us with comprehensive instructions outlining the steps you are following from the MediaPipe documentation to enable us to replicate the issue on our end. 

Additionally, please furnish us with the following details: the version of Bazel you are currently utilising, the specific version of MediaPipe you have installed, and confirmation of your success in building the "Hello world" example as per the guidance provided [here](https://developers.google.com/mediapipe/framework/getting_started/install#installing_on_debian_and_ubuntu).
