### ISSUE TITLE
Conflicts between libraries developed based on handtrackingGpu and other TensorFlow based libraries

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#4795]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

ios

### MediaPipe Tasks SDK version

0.10.1

### Task name (e.g. Image classification, Gesture recognition etc.)

handtrackingGpu

### Programming Language and version (e.g. C++, Python, Java)

oc

### Describe the actual behavior

it runs correctly

### Describe the expected behaviour

it runs correctly

### Standalone code/steps you may have used to try to get what you need

```shell
#0    0x000000010979c864 in TfLiteStatus tflite::ops::builtin::strided_slice::Eval<(tflite::ops::builtin::strided_slice::KernelType)0>(TfLiteContext*, TfLiteNode*) ()
```

**Comment by chensisi0730** [comment]
@kuaashish 
css-intel-Pro-2 bazel % brew config
HOMEBREW_VERSION: 4.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4afb8e5602f3ecc9edf67a44257d8eceeaa8a108
Last commit: 3 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d793577b4ad83222bb580364ff66b1c5fede26a6
Core tap last commit: 2 weeks ago
Core tap branch: master
Core tap JSON: 14 Sep 03:31 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.33.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2 => /Users/zhiyun/Downloads/Xcode.app/Contents/Developer

Bazel 6.1.1  
mediapipe 0.10.1

I followed the official steps to compile handtrackingGpu, refer to
https://developers.google.com/mediapipe/framework/getting_started/ios

The library developed based on handtrackingGpu conflicts with another library based on TensorFlow.
Another library called Nama is also based on TensorFlow. Running handtrackingGpu separately will not cause a crash. If Nama's module is run, it will cause a runtime error, with the following error message  as shown above

**Comment by kuaashish** [comment]
Hello @schmidt-sebastian,

Could you please look into this issue. Thank you

**Comment by kuaashish** [comment]
Hi @chensisi0730,

We would like to let you know that we've introduced a new hand Landmarker Task API for iOS. You can find the [documentation](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/ios) to help you build it into your iOS application. This new API is easier to use and doesn't much rely on additional dependencies like our old hand solution did (we've stopped maintaining that one).

We encourage you to check out our new hand Task API for iOS, especially if you have a specific use case in mind. If you need any support, please feel free to reach out.

Thank you
