### ISSUE TITLE
WSL with built-in camera

### ISSUE THREAD

**Issue by mihaelagrigore** [google/mediapipe#480]
I am running WSL on Windows 10 and I tried to run the Hand Tracking example. 

The build goes fine, but runnning the example fails. 

It seems to me that I narrowed down the problem to the impossibility to access the video stream from the built-in camera of my Microfost Surface tablet. 
I know there is a notification that WSL will not work with a USB camera and that we have to use a video file as input instead. 
But it seems to be the case that WSL might not work with a built-in camera either. This is not mentioned anywhere. 

If this is the case, I think it should be mentioned in the mediapipe readthedocs. But the question is: is this the case ? Is anyone able to run an example that uses a built-in camera in WSL ?

**Comment by jiuqiant** [comment]
We updated [the note regrading using cameras in WSL](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows-subsystem-for-linux-wsl). Base on [this post](https://funvision.blogspot.com/2019/12/opencv-web-camera-and-video-streams-in.html), the solution seems to be manually compiling OpenCV with FFmpeg and GStreamer in WSL.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by mgyong** [comment]
@mcclanahoochie  We have released [MediaPipe on Windows](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows) with [v0.7.5](https://github.com/google/mediapipe/releases/tag/v0.7.5)
Please check it out and give us feedback
