### ISSUE TITLE
Use absl::AnyInvocable in Executor, ThreadPool, and friends

### ISSUE THREAD

**Issue by jiawen** [google/mediapipe#4805]
[absl::AnyInvocable](https://github.com/abseil/abseil-cpp/blob/master/absl/functional/any_invocable.h) is a safer, move-only replacement for `std::function`. mediapipe currently uses `std::function` in [Executor](https://github.com/google/mediapipe/blob/master/mediapipe/framework/executor.h#L64), [ThreadPoolExecutor::Schedule()](https://github.com/google/mediapipe/blob/master/mediapipe/framework/thread_pool_executor.h), and friends. But it is never copied, only moved.

Copying an `std::function` can be expensive and lead to unexpected lifetime issues. Migrating to `absl::AnyInvocable` (or `std::move_only_function` in C++23) is preferred but not a high priority.

I am happy to contribute. It may break some fraction of existing users who are using `std::function`, but those cases are likely to be incorrect. This should not break any lambdas passed in.

**Comment by schmidt-sebastian** [comment]
We have to follow the restrictions and guidelines for both our internal Google build as well as our external facing build. We can therefore not always follow the current best practices. We will revisit this when our underlying infrastructure allows.
