### ISSUE TITLE
Unable to import imagegenerator 0.10.5

### ISSUE THREAD

**Issue by naveengovind** [google/mediapipe#4807]
I'm currently using version 0.10.5, which, according to the release notes, has added the Image Generator API. However, when I try to use the library, I can't import com.google.mediapipe.tasks.vision.imagegenerator as indicated in the official documentation [here](https://developers.google.com/mediapipe/api/solutions/java/com/google/mediapipe/tasks/vision/imagegenerator/ImageGenerator). Upon inspecting the downloaded MediaPipe library, I noticed that com.google.mediapipe.tasks.vision doesn't contain imagegenerator. Interestingly, com.google.mediapipe.tasks.vision.imagegenerator.proto does have imagegenerator in core, suggesting it should also be present in com.google.mediapipe.tasks.vision, but it's missing.

<img width="452" alt="Screenshot 2023-09-16 at 12 53 50 AM" src="https://github.com/google/mediapipe/assets/36118508/8c15bda8-362a-47c0-be11-6fec3624aef9">
<img width="424" alt="Screenshot 2023-09-16 at 1 03 27 AM" src="https://github.com/google/mediapipe/assets/36118508/31aecb2c-7d2c-43df-88ce-5f7b08014273">

**Comment by schmidt-sebastian** [comment]
The image generator is published under a different artifact. Please install `com.google.mediapipe:tasks-vision-image-generator`.
