### ISSUE TITLE
In my  project, the mediapipe conflicts with other modules  with opencv 

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#4808]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

ios

### MediaPipe Tasks SDK version

0.9.1

### Task name (e.g. Image classification, Gesture recognition etc.)

handtrackingGpu

### Programming Language and version (e.g. C++, Python, Java)

oc

### Describe the actual behavior

it runs correctly

### Describe the expected behaviour

it runs correctly

### Standalone code/steps you may have used to try to get what you need

```shell
In my project, the mediapipe conflicts with other modules with opencv4.5.1, 
error report :
objc[25689]:Class CvAbstractCamera
is implemented in both /private/var/containers/Bundle/Application/C5DF102D-C206-40F7-9A60-536A803CCE43
testImageTool.app/Frameworks/opencv2,framework/opencv2(0x111414538) and /private/var/containers/Bundle/Application/C5DF102D-
(206-40F7-9A60-536A83CE43/testImapetol-app/Frameworks/ZMediapine.framework/Zediapipe (0x1077ad5c8).one of the two will be used.which one is undefined.

Mediapipe and other modules rely on OPENCV,
in Mediapipe modules  BUILD file , 
ios_application(
    name = "ZYMediapipeApp",
    bundle_id = "com.zhiyun.mediapipe.ZYMediapipeApp11122",
    families = [
        "iphone",
        "ipad",
    ],
    minimum_os_version = MIN_IOS_VERSION,
    provisioning_profile = "//mediapipe/examples/ios:provisioning_profile",
    deps = [
        ":HandTrackingGpuAppLibrary", 
        "@ios_opencv//:OpencvFramework",
    ],
)
Then, by querying the symbol table using the NM command, it was found that there is an implementation of CvAbstractCamera in the mediapipe:
How do I implement dynamic linking OPENCV? And specify a specific OPENCV version?
```

**Comment by chensisi0730** [comment]
![11企业微信截图_16950342372999](https://github.com/google/mediapipe/assets/16938432/5b769ac4-e6e2-42a3-9a0a-93c175c15982)

**Comment by kuaashish** [comment]
@chensisi0730,

Following internal discussions, we regret to inform you that we have discontinued the maintenance and support for the legacy hand solution. Currently, our understanding of this matter is limited. However, please be assured that the inclusion of Hands in the iOS platform is already part of our roadmap, with anticipated availability on the same [page](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker). at this juncture, we cannot commit to a specific timeline. We appreciate your understanding in this regard. Thank you
