### ISSUE TITLE
Want to use opencv   greater than 3.2.0 , build error ，duplicate symbol 'google::protobuf::internal::ExtensionSet::SetRepeatedUInt64

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#4812]
### OS Platform and Distribution

iOS

### Programming Language and version

oc

### MediaPipe version

0.9.1

### Bazel version

5.2.0

### XCode and Tulsi versions (if iOS)

14.2

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

greater than 3.2.0

### Describe the problem

A bug happened!  I Want to use opencv greater than 3.2.0   ,  According to the description in WORKSPACE：
After OpenCV 3.2.0, the pre-compiled opencv2.framework has google protobuf symbols, which will
trigger duplicate symbol errors in the linking stage of building a mediapipe ios app.
 To get a higher version of OpenCV for iOS, opencv2.framework needs to be built from source with
'-DBUILD_PROTOBUF=OFF -DBUILD_opencv_dnn=OFF'
So , I run command :
bazel build -c opt --copt -DBUILD_PROTOBUF=OFF --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp。
but ,the same error is still reported .

### Complete Logs

```shell
ERROR: /Users/zhiyun/work/mediapipe_work/ios/mediapipe_github/9.1/mediapipe/examples/ios/ZYMediaPipe/zymediapipe/BUILD:34:14: Linking mediapipe/examples/ios/ZYMediaPipe/zymediapipe/ZYMediapipe_bin failed: (Aborted): wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp @bazel-out/ios-arm64-min12.0-applebin_ios-ios_arm64-opt-ST-acb08275552e/bin/mediapipe/examples/ios/ZYMediaPipe/zymediapipe/ZYMediapipe_bin-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
duplicate symbol 'google::protobuf::internal::ExtensionSet::SetRepeatedUInt64(int, int, unsigned long long)' in:
    bazel-out/ios-arm64-min12.0-applebin_ios-ios_arm64-opt-ST-acb08275552e/bin/external/com_google_protobuf/libprotobuf_lite.lo(extension_set.o)
    external/ios_opencv/opencv2.framework/opencv2(extension_set.o)
duplicate symbol 'google::protobuf::internal::ExtensionSet::GetUInt64(int, unsigned long long) const' in:
    bazel-out/ios-arm64-min12.0-applebin_ios-ios_arm64-opt-ST-acb08275552e/bin/external/com_google_protobuf/libprotobuf_lite.lo(extension_set.o)
    external/ios_opencv/opencv2.framework/opencv2(extension_set.o)
```

**Comment by kuaashish** [comment]
@chensisi0730,

Following internal discussions, we regret to inform you that we have discontinued the maintenance and support for the legacy hand solution. Currently, our understanding of this matter is limited. However, please be assured that the inclusion of Hands in the iOS platform is already part of our roadmap, with anticipated availability on the same [page](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker). at this juncture, we cannot commit to a specific timeline. We appreciate your understanding in this regard. Thank you
