### ISSUE TITLE
How do I use gpu in holistic model python solution?

### ISSUE THREAD

**Issue by hamsangjin** [google/mediapipe#4816]
### MediaPipe Solution (you are using)

holistic

### Programming language

python

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

I want to run it on gpu

### Please specify the use cases for this feature

I want to run it on gpu

**Comment by kuaashish** [comment]
@kuaashish,

Currently, we do not possess official support for GPU utilisation within the Python platform for legacy solutions. For new upgraded tasks API's as noted [here](https://developers.google.com/mediapipe/solutions/guide#available_solutions), We are supporting the GPU for python But there is known issue And We are actively working towards fix. 

Nevertheless, it is worth noting that there exists an implementation of Python GPU support available from the community, as indicated by the following link [here](https://github.com/xiong-jie-y/mediapipe/tree/add_gpu_support_for_python), which appears to be consistently updated. For a more comprehensive grasp of the topic, We suggest perusing the following discussion thread. This resource may potentially offer assistance in the present context. 

At this time, we are unable to provide a specific timeline for the upgrade of the Holistic Task API and the introduction of official Python GPU support. Thank you
