### ISSUE TITLE
Can I add new gesture(e.g. zoom in/out) basing on the mediapipe?

### ISSUE THREAD

**Issue by jameswangsm** [google/mediapipe#482]
Current version only support limited gesture detection,how can I add some new gestures in mediapipe? If yes,would you like to brief the way,many thanks.

**Comment by Zumbalamambo** [comment]
@jameswangsm yes it is possible

**Comment by eknight7** [comment]
Hi @jameswangsm, it is possible as discussed in this [talk](https://youtu.be/qXs0QZ6VWS8?t=1503) and some more details are in this [blog post](https://ai.googleblog.com/2019/08/on-device-real-time-hand-tracking-with.html).

**Comment by eknight7** [comment]
Issue https://github.com/google/mediapipe/issues/469 has some interesting relevant discussion as well.

**Comment by jameswangsm** [comment]
thanks a lot:)
