### ISSUE TITLE
Documentation for building graphs in C++ could be expanded

### ISSUE THREAD

**Issue by hans-brgs** [google/mediapipe#4821]
### Description of issue (what needs changing)

The MediaPipe documentation provides examples of how to build CalculatorGraphs programmatically in C++, using the GraphBuilder API, but it seems possible to create graphs using CalculatorGraphConfig as well. Which is the best practice?

### Clear description

I'm looking for guidance on the best practices for building a CalculatorGraph programmatically in C++.

There seem to be two main options:  

1. Using the CalculatorGraphConfig directly:

```
mediapipe::CalculatorGraphConfig BuildGraph1()
{
  mediapipe::CalculatorGraphConfig config;

  config.add_input_stream("input_video");
  config.add_output_stream("output_video");

  auto *pass_through_node = config.add_node();
  pass_through_node->set_calculator("PassThroughCalculator");
  pass_through_node->add_input_stream("input_video");
  pass_through_node->add_output_stream("output_video");

  return config;
}
```

2. Using the GraphBuilder API:

```
mediapipe::CalculatorGraphConfig BuildGraph()
{
  mediapipe::api2::builder::Graph graph;

  // Graph inputs.
  mediapipe::api2::builder::Stream<mediapipe::ImageFrame> image_value = graph.In(0).SetName("input_video").Cast<mediapipe::ImageFrame>();

  auto &pass_node = graph.AddNode("PassThroughCalculator");
  image_value >> pass_node.In(0);

  mediapipe::api2::builder::Stream<mediapipe::ImageFrame> passed_image_value = pass_node.Out(0).Cast<mediapipe::ImageFrame>();

  // Graph outputs.
  passed_image_value.SetName("output_video") >> graph.Out(0);

  // Get `CalculatorGraphConfig` to pass it into `CalculatorGraph`
  return graph.GetConfig();
}
```

 The GraphBuilder API is used in the official [examples](https://developers.google.com/mediapipe/framework/framework_concepts/graphs_cpp) However, I find the CalculatorGraphConfig style to be more straightforward.  Is there an official recommendation on which approach to prefer for building graphs in C++? Are there any tradeoffs to consider between the two styles?  

Some factors I'm interested in: 

- Readability
- Maintainability
- Performance
- Flexibility

Thanks for your insight on this!

### Correct links

[GraphBuilder API](https://developers.google.com/mediapipe/framework/framework_concepts/graphs_cpp)

**Comment by schmidt-sebastian** [comment]
@gkarpiak Do you have a suggestion?

**Comment by gkarpiak** [comment]
> I find the CalculatorGraphConfig style to be more straightforward. Is there an official recommendation on which approach to prefer for building graphs in C++? Are there any tradeoffs to consider between the two styles?

GraphBuilder C++ API benefits show up when you your graphs evolve, you want to share some parts between graphs, refactor it safely. And even for simpler graphs it can improve readability, maintainability and flexibility. Performance-wise, using CalculatorGraphConfig or GraphBuilder C++ API doesn't matter.

Consider the example provided:
1. It clears up stream types in your graph e.g. `Stream<ImageFrame>`
2. It allows you to write your code in a more programmatic way, e.g. instead of relying on hardcoded strings you can actually have variables representing your streams, e.g. `image_value`, `passed_image_value` and those variables can be used independently from node.
3. It enables you to use various C++ language capabilities, e.g. imagine if you want to have 3 pass through nodes where one runs optionally. In protobuf:
```
auto *pass_through_node = config.add_node();
pass_through_node->set_calculator("PassThroughCalculator");
pass_through_node->add_input_stream("input_video");
pass_through_node->add_output_stream("output_video1");

std::string stream_name;
if (is_enabled) {
    auto *pass_through_node = config.add_node();
    pass_through_node->set_calculator("PassThroughCalculator");
    pass_through_node->add_input_stream("output_video1");
    pass_through_node->add_output_stream("output_video2");
    stream_name = "output_video2";
} else {
    stream_name = "output_video1"
}
auto *pass_through_node = config.add_node();
pass_through_node->set_calculator("PassThroughCalculator");
pass_through_node->add_input_stream(stream_name);
pass_through_node->add_output_stream("output_video");
```
and with GraphBuilder API, to avoid duplication/hardcoding and preserve type information you can have the following:
```
// Utility function that passes through any stream, preserve types and avoids calculator name duplication.
template <typename T>
Stream<T> PassThrough(Stream<T> s, Graph& graph) { ... }

Stream<ImageFrame> output_video = PassThrough(input_video, graph);
if (is_enabled) {
  output_video = PassThrough(output_video, graph);
}
output_video = PassThrough(output_video, graph);
```
