### ISSUE TITLE
MediaPipe_Image_Generator: Does this feature and apk can Open Source?

### ISSUE THREAD

**Issue by caofx0418** [google/mediapipe#4822]
MediaPipe_Image_Generator
MediaPipe_Image_Generator: 
Does this feature and apk can Open Source?

**Comment by kuaashish** [comment]
@caofx0418,

Could you please elaborate your query with complete details. Thank you!

**Comment by kuaashish** [comment]
@caofx0418,

If you are in search of the recently released image generator API, you can find it by following the provided link [here](https://developers.google.com/mediapipe/api/solutions/java/com/google/mediapipe/tasks/vision/imagegenerator/package-summary). It's worth noting that the MediaPipe Image Generator feature and its associated APK have already been made open source. For a comprehensive understanding, please refer to the [overview page](https://developers.google.com/mediapipe/solutions/vision/image_generator) for additional details and information.

**Comment by caofx0418** [comment]
I plan to develop a Android/windows tablet APP use this feature with c++ ndk. but current Java API hard integrated in.
if the generator APP demo open source，it will make the work easy.

**Comment by caofx0418** [comment]
> We are working on open-sourcing this code. This is not yet ready.

what time is this ready to open-sourcing?

**Comment by kuaashish** [comment]
@caofx0418,

We are pleased to announce the open-sourcing of the Mediapipe Image Generator APK on GitHub. You can access the repository [here](https://github.com/googlesamples/mediapipe/tree/main/examples/image_generation/android). 

Additionally, comprehensive information on its associated features is available in our [blogs](https://developers.googleblog.com/2023/10/mediapipe-on-device-text-to-image-generation-solution-now-available-for-android-developers.html) and [documentation](https://developers.google.com/mediapipe/solutions/vision/image_generator). Thank you

**Comment by kuaashish** [comment]
@caofx0418,

Can you please check the comment above and tell us if it meets your needs? Thank you.

**Comment by caofx0418** [comment]
it's very nice!

**Comment by caofx0418** [comment]
> @caofx0418,
> 
> Thank you for your prompt reply, For now, If this is no longer issue from your end, Can we go ahead and mark issue resolved and close this.

but i also find "libimagegenerator_gpu.so" still a binary, it's hard to transplant APP to other platform(window/RPI/...).
 Does "libimagegenerator_gpu.so" can Open Source?

**Comment by kuaashish** [comment]
@caofx0418,

To keep the context of the issue as relevant to the original issue as possible, may I suggest you close this issue and open another one?

Also, Please share the details, like your operating system, the steps you followed from the documentation, and the mobile device you're using. This will help us understand and address the issue effectively. This helps community and us to search the issues better in concise manner. Thank you

**Comment by caofx0418** [comment]
> "libimagegenerator_gpu

OK, close this issue, and open anthor one.
