### ISSUE TITLE
Unable to Use MediaPipe Graph with Bitmap Images in Android Studio

### ISSUE THREAD

**Issue by GKarimG** [google/mediapipe#4824]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Android 11 

### Solution

Holistic

### Programming Language and version

Java

### Describe the actual behavior

Currently, I am facing challenges in adapting the MediaPipe framework to accept and process bitmap images instead of video streams. The available documentation and examples do not cover this use case.

### Describe the expected behaviour

I expect to be able to modify the MediaPipe graph or use the framework's components to process individual bitmap images received from the Android app and obtain the desired results.

### Standalone code/steps you may have used to try to get what you need

```shell
I am attempting to implement a custom MediaPipe graph in Android Studio, but most tutorials and resources available online focus on working with video streams. My specific requirement is to make this graph process bitmap images that are captured within the Android app.

**Steps:**
1. I have tried this repo (https://github.com/shadow111/mediapipe-holistic-tracking-aar-example)
2. Attempt to modify or create a custom graph that accepts bitmap images as input.
3. Encounter difficulties in achieving the desired functionality.
```

### Other info / Complete Logs

```shell
**The pbtxt file that we are trying to use**

node {
  calculator: "ImageSourceCalculator"
  input_stream: "input_image"
  output_stream: "image"
}
node {
  calculator: "FaceDetection"
  input_stream: "image"
  output_stream: "detections"
}
node {
  calculator: "FaceMesh"
  input_stream: "image"
  input_stream: "detections"
  output_stream: "face_mesh"
  node_options: {
    [type.googleapis.com/mediapipe.FaceMeshOptions] {
      use_gpu: true
    }
  }
}
node {
  calculator: "Holistic"
  input_stream: "image"
  output_stream: "holistic_landmarks"
  node_options: {
    [type.googleapis.com/mediapipe.HolisticOptions] {
      use_gpu: true
    }
  }
}
```

**Note:** this is the code that we use: 

```
Graph graph = new Graph();
String BINARY_GRAPH_NAME = "test.pbtxt";
if (new File(BINARY_GRAPH_NAME).isAbsolute()) {
     graph.loadBinaryGraph(BINARY_GRAPH_NAME);
} else {
     graph.loadBinaryGraph(AndroidAssetUtil.getAssetBytes(this.getAssets(), BINARY_GRAPH_NAME));
}
```

Error message: (Failed to parse graph)
```

**Comment by schmidt-sebastian** [comment]
Please take a look at https://github.com/google/mediapipe/tree/master/mediapipe/java/com/google/mediapipe/framework/image as well as https://github.com/google/mediapipe/blob/master/mediapipe/tasks/cc/components/processors/image_preprocessing_graph.cc for examples.
