### ISSUE TITLE
javascript is not defined in landmark_grid in MediaPipe Pose demo

### ISSUE THREAD

**Issue by mupakoz** [google/mediapipe#4826]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

MacOs Ventura

### Programming Language and version

Javascript

### Solution

Pose

### Describe the actual behavior

Demo of Pose in codepen.io https://codepen.io/mediapipe/full/jOMbvxw is not starting, there are errors in the console

### Describe the expected behaviour

The demo is working

### Standalone code/steps you may have used to try to get what you need

```shell
https://codepen.io/mediapipe/full/jOMbvxw

I have the same issue locally.
```

**Comment by kuaashish** [comment]
@mupakoz,

Could you kindly inform us whether you are utilising macOS on an Intel-based architecture or the Silicon chip-based macOS? Additionally, please specify the web browser in which you are attempting to execute the demonstration.

**Comment by mupakoz** [comment]
hi @kuaashish, looks like it is working again, probably was something on my end, sorry for the trouble!

**Comment by mupakoz** [comment]
hi @kuaashish I am reopening the issue as it's not working again
It's a Silicon chip-based macOS with Apple M1 Max and Ventura 13.4

The demo does work in Safari, but does not work in Google Chrome

**Comment by kuaashish** [comment]
Hi @mupakoz,

Web demo model of Pose as mentioned here https://codepen.io/mediapipe/full/jOMbvxw is working fine for me in **macOS M1 Pro, Ventura 13.5, Chrome Version 118.0.5993.70 (Official Build) (arm64)**. 

Could you try to upgrade the Chrome Version to tested or newer one, Or If still an issue after upgrading to Chrome Version. Please try to upgrade the macOS Ventura version and let us know if still an issue from your end. Thank you

**Comment by kuaashish** [comment]
Hi @mupakoz,

Could you please let us know the status of the above, If this works for you, So we can go ahead mark the resolved and close the issue. Thank you
