### ISSUE TITLE
Mobilenetv2 detector inference

### ISSUE THREAD

**Issue by Varfalamei** [google/mediapipe#4836]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Android 11

### Python Version

3.10

### MediaPipe Model Maker version

0.2.1.3

### Task name (e.g. Image classification, Gesture recognition etc.)

Object Detection

### Describe the actual behavior

I have trained the mobilenetv2 model for the detection task, I am trying to embed it in the graph and run it via tf.lite.Interpreter, but it doesn't work. In the first case, everything falls, and in the second case, I can't figure out how to take into account all the dimensions

### Describe the expected behaviour

I want to launch a detection model with one target class in the mediapipe graph

### Standalone code/steps you may have used to try to get what you need

```shell
# Mediapipe graph:

node {
   calculator: "ImageToTensorCalculator"
   input_stream: "IMAGE:transformed_input_video"
   output_stream: "TENSORS:image_tensor"
   options {
     [mediapipe.ImageToTensorCalculatorOptions.ext] {
       output_tensor_width: 320
       output_tensor_height: 320
       keep_aspect_ratio: false
       output_tensor_float_range {
         min: 0
         max: 1
       }
     }
   }
 }

node {
   calculator: "InferenceCalculator"
   input_stream: "TENSORS:image_tensor"
   output_stream: "TENSORS:detection_tensors"
   options: {
     [mediapipe.InferenceCalculatorOptions.ext] {
       model_path: "mobilenetv2-320-fp16.tflite"
       delegate { xnnpack {}  }
     }
   }
}

node {
  calculator: "SsdAnchorsCalculator"
  output_side_packet: "anchors"
  node_options: {
    [type.googleapis.com/mediapipe.SsdAnchorsCalculatorOptions] {
      num_layers: 6
      min_scale: 0.2
      max_scale: 0.95
      input_size_height: 320
      input_size_width: 320
      anchor_offset_x: 0.5
      anchor_offset_y: 0.5
      strides: 16
      strides: 32
      strides: 64
      strides: 128
      strides: 256
      strides: 512
      aspect_ratios: 1.0
      aspect_ratios: 2.0
      aspect_ratios: 0.5
      aspect_ratios: 3.0
      aspect_ratios: 0.3333
      reduce_boxes_in_lowest_layer: true
    }
  }
}

node {
  calculator: "TensorsToDetectionsCalculator"
  input_stream: "TENSORS:detection_tensors"
  input_side_packet: "ANCHORS:anchors"
  output_stream: "DETECTIONS:detections"
  options: {
    [mediapipe.TensorsToDetectionsCalculatorOptions.ext]{
      num_classes: 2
      num_boxes: 19125
      num_coords: 4
      min_score_thresh: 0.2
      reverse_output_order: false
      ignore_classes: 0
      apply_exponential_on_box_size: true
    }
  }
}

node {
  calculator: "NonMaxSuppressionCalculator"
  input_stream: "detections"
  output_stream: "filtered_detections"
  node_options: {
    [type.googleapis.com/mediapipe.NonMaxSuppressionCalculatorOptions] {
      min_suppression_threshold: 0.2
      max_num_detections: 2000
      overlap_type: INTERSECTION_OVER_UNION
      return_empty_detections: true
    }
  }
}


# Python tf.lite wrapper
image_resize = image.resize((320, 320))
image_np = np.array(image_resize).astype(np.float32)[None, ...] #
image_np = image_np / 255
main_model = tf.lite.Interpreter(tflite_model_path)
main_model.allocate_tensors()
main_model.set_tensor(0, image_np)
main_model.invoke()
raw_bboxes = main_model.get_tensor(main_model.get_output_details()[0]['index'])[0]
raw_scores = main_model.get_tensor(main_model.get_output_details()[1]['index'])[0, :, 1]

print(raw_bboxes.shape)
chosen_probs = raw_scores >= 0.4
chosen_bboxes = raw_bboxes[chosen_probs]
```

### Other info / Complete Logs

```shell
I would also like to understand if I need anchors

Outputs from my model:
1. bboxes (1, 19125, 4)
2. scores (1, 19125, 2)
```

**Comment by Varfalamei** [comment]
I've trained MOBILENET_V2_I320 from this [link](https://developers.google.com/mediapipe/api/solutions/python/mediapipe_model_maker/object_detector/SupportedModels)  and used mediapipe model maker python api

**Comment by schmidt-sebastian** [comment]
Do you have any logging that you can share with us?

**Comment by ly0303521** [comment]
@schmidt-sebastian @kuaashish I meet a similar problem, also replace ssdlite_object_detection.tflite with ssd_mobilenet_v2.
the problem can be reproduced by this: use the gprah "mediapipe/graphs/object_detection/object_detection_desktop_live.pbtxt", use the model [SSDMobileNet-V2 (float 32)](https://storage.googleapis.com/mediapipe-models/object_detector/ssd_mobilenet_v2/float32/latest/ssd_mobilenet_v2.tflite), the model is download from your website, but also have the same problem. In pbtxt set image size: 256,  num_boxes: 12276. No errors, but detections are wrong

**Comment by ly0303521** [comment]
@Varfalamei  Hi, have you solved, I'm stuck for a long time

**Comment by architjaiswal** [comment]
I am still confused on how to convert the model such that it gets the same 4 outputs I was initially giving. I also saved the model using `model.export_model(model.export_model(model_name=model_out, quantization_config=quantization_config)`

Can someone tell me how to convert the trained model to obtain the 4 output (locations, classes, scores, detections)?
