### ISSUE TITLE
Building python package from Docker container

### ISSUE THREAD

**Issue by moo-joshua** [google/mediapipe#4837]
### OS Platform and Distribution

Docker image on Windows 11 / Linux (Ubuntu 20.04 VM) 

### Compiler version

gcc 8.4.0

### Programming Language and version

Python 

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

latest

### Bazel version

6.1.1

### Android AAR (if android)

None

### Describe the problem

Hi, I am trying to build the Python framework from within the Docker container built from the Dockerfile provided. I've followed the same exact steps in https://github.com/google/mediapipe/issues/4657 to install all the dependencies (etc. opencv using setup_opencv.sh, protobuf-compiler using their official instructions](https://grpc.io/docs/protoc-installation/#install-pre-compiled-binaries-any-os). 

The only difference is that I had to run the following in the container first because I've pulled the repo into a Windows environment:
sed $'s/\r$//' .bazelversion > .bazelversion
sed -i -e 's/\r$//' setup_opencv.sh

After that I ran the install command: python setup.py install --link-opencv. 

But now I am facing a different error, seems to be something wrong with compiling mediapipe/gpu/gl_context.cc.

### Complete Logs

```shell
warning:
  /mediapipe/mediapipe/tasks/metadata/metadata_schema.fbs:486: 21: warning: field names should be lowercase snake_case, got: sentencePiece_model

ERROR: /mediapipe/mediapipe/gpu/BUILD:157:11: Compiling mediapipe/gpu/gl_context.cc failed: (Exit 1): gcc failed: error executing command (from target //mediapipe/gpu:gl_context) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 58 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from mediapipe/gpu/gl_context.cc:15:
./mediapipe/gpu/gl_context.h:252:3: error: 'GlVersion' does not name a type
  252 |   GlVersion GetGlVersion() const;
      |   ^~~~~~~~~
./mediapipe/gpu/gl_context.h:488:7: error: 'GlTextureInfo' does not name a type
  488 | const GlTextureInfo& GlTextureInfoForGpuBufferFormat(GpuBufferFormat format,
      |       ^~~~~~~~~~~~~
mediapipe/gpu/gl_context.cc:210:1: error: 'GlVersion' does not name a type
  210 | GlVersion GlContext::GetGlVersion() const {
      | ^~~~~~~~~
mediapipe/gpu/gl_context.cc:1033:7: error: 'GlTextureInfo' does not name a type
 1033 | const GlTextureInfo& GlTextureInfoForGpuBufferFormat(GpuBufferFormat format,
      |       ^~~~~~~~~~~~~
Target //mediapipe/python:_framework_bindings.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 17.888s, Critical Path: 4.98s
INFO: 247 processes: 147 internal, 100 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
Command '['bazel', 'build', '--compilation_mode=opt', '--copt=-DNDEBUG', '--action_env=PYTHON_BIN_PATH=/usr/bin/python', '//mediapipe/python:_framework_bindings.so', '--define=MEDIAPIPE_DISABLE_GPU=1']' returned non-zero exit status 1.
```

Full install log:
[full log.txt](https://github.com/google/mediapipe/files/12739336/full.log.txt)

Tried this on an Ubuntu 20.04 VM and still getting the same error...

**Comment by moo-joshua** [comment]
[install log.txt](https://github.com/google/mediapipe/files/12739304/install.log.txt)

**Comment by moo-joshua** [comment]
Hi @kuaashish, 

Yes I've checked the workaround in https://github.com/google/mediapipe/issues/4657, verified the contents of mediapipe/__init__.py are correct. So that doesn't seem to be causing my error.

Here are the steps that I took on both Linux 20.04 and Windows 11:
1) Cloned the mediapipe repository, built the docker image and ran it. The following steps are done within the docker container.

2) installed sudo : `apt install sudo`

3) installed cmake :`apt install cmake`

3) installed opencv: `sh setup_opencv.sh` (option2 in this link https://github.com/google/mediapipe/blob/master/docs/getting_started/install.md)

4) activated my Python virtual environment: `python -m venv mp_env && source mp_env/bin/activate
`
5) installed packages in requirements.txt: `pip install -r requirements.txt`

6) ran build command for the Mediapipe package: `python setup.py install --link-opencv`

I've tried these steps multiple times on a freshly built docker image as well, on both Linux 20.04 and Windows 11 and am still getting the same error as above. I've also double checked the Bazel version to be 6.1.1 which is installed by default from the dockerfile.

**Comment by kuaashish** [comment]
Hi @moo-joshua,

Apologies for the detailed response. We have recently launched version 0.10.8 of the MP, as indicated on the [release page](https://github.com/google/mediapipe/releases/tag/v0.10.8). Kindly attempt to build using the Docker container and inform us if the issue persists on your end. If you are still seeking a resolution for this matter and it has not been resolved from your perspective, please let us know.

Thank you!
