### ISSUE TITLE
build c++ app on windows using bazel, found error c2065 and c2039

### ISSUE THREAD

**Issue by westpilgrim63** [google/mediapipe#4841]
### OS Platform and Distribution

windows 11

### Compiler version

visual studio 2019 community c++

### Programming Language and version

c++

### Installed using virtualenv? pip? Conda?(if python)

conda

### MediaPipe version

newest

### Bazel version

6.1.1

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

3.4.10

### Describe the problem

build c++ app on windows using bazel, found error c2065 and c2039.python version:3.10.10
BAZEL_VC_FULL_VERSION=14.29.30133
BAZEL_WINSDK_FULL_VERSION=10.0.17763.0

### Complete Logs

```shell
注意: 包含文件:  C:\users\thinkpad\_bazel_thinkpad\bdwkj4bx\execroot\mediapipe\mediapipe/framework/type_map.h
注意: 包含文件:   C:\users\thinkpad\_bazel_thinkpad\bdwkj4bx\execroot\mediapipe\mediapipe/framework/demangle.h
注意: 包含文件:   C:\users\thinkpad\_bazel_thinkpad\bdwkj4bx\execroot\mediapipe\mediapipe/framework/tool/status_util.h
注意: 包含文件:   C:\users\thinkpad\_bazel_thinkpad\bdwkj4bx\execroot\mediapipe\mediapipe/framework/tool/type_util.h
mediapipe/framework/tool/proto_util_lite.cc(140): error C2039: "GetMessageA": 不是 "mediapipe::tool::ProtoUtilLite::FieldAccess" 的成员
C:\users\thinkpad\_bazel_thinkpad\bdwkj4bx\execroot\mediapipe\mediapipe/framework/tool/proto_util_lite.h(67): note: 参见“mediapipe::tool::ProtoUtilLite::FieldAccess”的声明
mediapipe/framework/tool/proto_util_lite.cc(141): error C2065: “message_”: 未声明的标识符
mediapipe/framework/tool/proto_util_lite.cc(145): error C2065: “field_type_”: 未声明的标识符
mediapipe/framework/tool/proto_util_lite.cc(146): error C2065: “field_id_”: 未声明的标识符
mediapipe/framework/tool/proto_util_lite.cc(146): error C2065: “field_values_”: 未声明的标识符
mediapipe/framework/tool/proto_util_lite.cc(214): error C2039: "GetMessageA": 不是 "mediapipe::tool::ProtoUtilLite::FieldAccess" 的成员
C:\users\thinkpad\_bazel_thinkpad\bdwkj4bx\execroot\mediapipe\mediapipe/framework/tool/proto_util_lite.h(67): note: 参见“mediapipe::tool::ProtoUtilLite::FieldAccess”的声明
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 270.082s, Critical Path: 113.98s
INFO: 774 processes: 235 internal, 539 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
```

**Comment by westpilgrim63** [comment]
i search through the whole mediapipe project and cannot found the funtion :  GetMessageA  ,i only found the function GetMessage.  so where this GetMessageA came from?

**Comment by westpilgrim63** [comment]
@ayushgdev

**Comment by kuaashish** [comment]
Hi @westpilgrim63,

I apologise for the delayed response. Could you kindly confirm whether you are still seeking a resolution for the mentioned issue, or if it has already been resolved on your end? 

If the issue persists, would you please provide the complete steps outlined in the documentation, along with confirmation of the success of the "Hello, World" example as described in the provided documentation [here](https://developers.google.com/mediapipe/framework/getting_started/install#installing_on_windows)? This information will greatly assist us in better understanding and reproducing the issue from our end.


Thank you

**Comment by westpilgrim63** [comment]
i move to mediapipe python version

**Comment by ymingdai** [comment]
> i check the file proto_util_lite.cc(140) ,and only find the function GetMessage in that line, not GetMessageA. i search through the whole mediapipe project and cannot found the funtion : GetMessageA ,i only found the function GetMessage. so where this GetMessageA came from?

have you found the solution of this issue? I encountered the same issues, I also checked this cc file, only Getmessage, no GetMessageA exists, I am so confused.
anyone can help?
