### ISSUE TITLE
What is the current version of MediaPipe supported by Jetson Nano?

### ISSUE THREAD

**Issue by VieiraJardel** [google/mediapipe#4842]
In 2023, which version of MediaPipe is supported by Jetson Nano? I currently use version 0.8.9, but I would like to know if there is any newer version that can be utilized.

**Comment by kuaashish** [comment]
@VieiraJardel,

We are yet to support officially Jeston Nano, For now, Only supported edge device is Raspberry Pi 64bit as noted [here](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions).

**Comment by VieiraJardel** [comment]
Some people assist the Jetson community with the installation of MediaPipe. Are there any of these unofficial channels that you are aware of and can recommend for more up-to-date installations on the Jetson Nano?

The last tutorial I followed was this one, but it only recommends version 0.8.9:
[Link] - https://github.com/anion0278/mediapipe-jetson

**Comment by kuaashish** [comment]
@VieiraJardel,

Presently, our knowledge is limited to the https://github.com/anion0278/mediapipe-jetson plugin, which is currently up-to-date. As we don't have an official plugin, we encourage the community to utilise this well-maintained alternative. It's worth noting that Jeston support is already in our roadmap, and our team is actively working on its implementation. 

However, we cannot provide a specific timeline for its availability at this moment. Thank you
