### ISSUE TITLE
File loading is not yet supported on Windows

### ISSUE THREAD

**Issue by cjl84914** [google/mediapipe#4847]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

win10

### Python Version

Python 3.9.13

### MediaPipe Model Maker version

0.9.0.1

### Task name (e.g. Image classification, Gesture recognition etc.)

https://developers.google.com/mediapipe/solutions/customization/gesture_recognizer

### Describe the actual behavior

data = gesture_recognizer.Dataset.from_folder

### Describe the expected behaviour

no error

### Standalone code/steps you may have used to try to get what you need

```shell
run code:
dataset_path="./rps_data_sample"
data = gesture_recognizer.Dataset.from_folder(
    dirname=dataset_path,
    hparams=gesture_recognizer.HandDataPreprocessingParams()
)

error info:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\anaconda3\lib\site-packages\mediapipe_model_maker\python\vision\gesture_recognizer\dataset.py", line 202, in from_folder
    hand_data = _get_hand_data(
  File "e:\anaconda3\lib\site-packages\mediapipe_model_maker\python\vision\gesture_recognizer\dataset.py", line 114, in _get_hand_data
    with _HandLandmarker.create_from_options(
  File "e:\anaconda3\lib\site-packages\mediapipe\tasks\python\vision\hand_landmarker.py", line 271, in create_from_options
    return cls(
  File "e:\anaconda3\lib\site-packages\mediapipe\tasks\python\vision\core\base_vision_task_api.py", line 65, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
RuntimeError: File loading is not yet supported on Windows
```

**Comment by kuaashish** [comment]
@cjl84914,

This concern was identified in MediaPipe version 0.9.0.1, and it was addressed in the subsequent release, version 0.9.3.0, as documented in the [release page](https://github.com/google/mediapipe/releases/tag/v0.9.3.0) under the description "Gracefully fail resource path lookup for Python on Windows." We recommend upgrading to the latest version, [0.10.5](https://github.com/google/mediapipe/releases/tag/v0.10.5). If the issue persists, kindly inform us of any similar errors you may encounter after the upgrade. Thank you

**Comment by cjl84914** [comment]
@kuaashish 
I can't update mediapipe-model-maker lastest ver.
`run:
pip install mediapipe-model-maker==0.2.1.3
ERROR: Cannot install mediapipe-model-maker because these package versions have conflicting dependencies.
The conflict is caused by:
    tf-models-official 2.13.2 depends on tensorflow-text~=2.13.0
    tf-models-official 2.13.1 depends on tensorflow-text~=2.13.0
run:
pip install tensorflow-text==2.13.0
ERROR: Could not find a version that satisfies the requirement tensorflow-text==2.13.0 (from versions: 2.5.0, 2.6.0rc0, 2.6.0, 2.7.0rc0, 2.7.0rc1, 2.7.3, 2.8.0rc0, 2.8.1, 2.8.2, 2.9.0rc0, 2.9.0rc1, 2.9.0, 2.10.0b2, 2.10.0rc0, 2.10.0)
ERROR: No matching distribution found for tensorflow-text==2.13.0
`

**Comment by kuaashish** [comment]
@cjl84914,

To keep the context of the issue as relevant to the original issue as possible, may I suggest you close this issue and open another one,  With complete details such as OS you are using, Python Version, Mediapipe model maker version to understand the issue better from our end. This helps community and us to search the issues better in concise manner. Thank you
