### ISSUE TITLE
Memory Leak on hands function?

### ISSUE THREAD

**Issue by thecas89-teacher** [google/mediapipe#4848]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 10

### Programming Language and version

Python 

### MediaPipe version

0.10.5

### Solution

Hands

### Describe the actual behavior

Hands recognitions goes to memory leak (out of memory)

### Describe the expected behaviour

Take the landmarks

### Standalone code/steps you may have used to try to get what you need

```shell
Hi, i'm trying the basic example of mediapipe hands recognition with opencv code on

My code is basic:


import cv2
import mediapipe as mp

mp_hands=mp.solutions.hands
mp_drawing=mp.solutions.drawing_utils
webcam = cv2.VideoCapture(0,cv2.CAP_DSHOW)
while webcam.isOpened():
    success, img = webcam.read()
    img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
results=mp_hands.Hands(max_num_hands=3,min_detection_confidence=0.7,min_tracking_confidence=0.6).process(img)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    cv2.imshow('Test', img)
    results=[]
    print("passo")
webcam.release()
cv2.destroyAllWindows()


Unfortunately the ML line results=mp_hands.Hands(max_num_hands=3,min_detection_confidence=0.7,min_tracking_confidence=0.6).process(img)
creates an increase of the memory usage from some MB up to 32 GB.
Where I'm doing it wrong?
```

**Comment by kuaashish** [comment]
@thecas89-teacher,

You are currently utilising the legacy MediaPipe hand solution, which is no longer maintained by our team. We kindly advise you to refer to our [guide](https://developers.google.com/mediapipe/solutions/guide#legacy), where it is indicated that the hand solution has been upgraded to the new Hands API.

We earnestly request that you transition to our new Hand Task API as outlined in the provided documentation [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/python). Additionally, you can find a [code example](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/hand_landmarker/python/hand_landmarker.ipynb) in the same resource for your reference. Also, we request please report back if you observe similar behaviour in the upgraded task API. Thank you
