### ISSUE TITLE
Failure [INSTALL_FAILED_NO_MATCHING_ABIS]

### ISSUE THREAD

**Issue by momo1986** [google/mediapipe#485]
Hello, I have tried to run 
`adb install bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu/facedetectioncpu.apk`

However, I got the error:

> Performing Push Install
> bazel-bin/mediapipe/examples/android/s.... 13.9 MB/s (53064745 bytes in 3.644s)
> 	pkg: /data/local/tmp/facedetectioncpu.apk
> Failure [INSTALL_FAILED_NO_MATCHING_ABIS]

My development operating system is MacOS, while my emulator is 163-MuMu.

I noticed that, in  app's build.graddle, user can set like this
```
splits {
    abi {
        enable true
        reset()
        include 'x86', 'armeabi-v7a','x86_64'
        universalApk true
    }
}

```

But how can I resolve the problem via command line to install mediapipe?

Thanks and regards if anyone can answer my questions.

**Comment by momo1986** [comment]
This problems happens inside the android studio terminal and macos terminal.

**Comment by momo1986** [comment]
How can I run the configuration inside my project to support x86 and armeabi-v7a architecture?

**Comment by momo1986** [comment]
Inside android studio, which virtual devices are recommended for testing and which system image is essential for media pipe support?

Wait for response.

**Comment by tagy** [comment]
I got the same error when trying to install one of the sample app's to a device.

I removed the following from the build command: -c opt --config=android_arm64

So just ran:

> bazel build pathto/mediapipe/apps/objectdetectiongpu:objectdetectiongpu

After that I was able to install the app to a device and use the app, but I don't really understand exactly what I did, but it might point you in the right direction.

**Comment by jiuqiant** [comment]
Seems like the issue is solved and you have some follow-up issues already. Feel free to reopen this if needed. Thanks!
