### ISSUE TITLE
model format availability (tflite, ONNX)

### ISSUE THREAD

**Issue by valsecchi** [google/mediapipe#4854]
back before the main release of 2023, all the models were available as .tflite which allows us user to easilly convert them into .onnx which is widely used.
As by now the models are avilable only as .task, is it possibile to have have a feature to convert the model to a tflite, hence to onnx?
Thanks

**Comment by kuaashish** [comment]
@valsecchi,

The task file encompasses the .tflite model, and you can extract the TFLite files by executing the following command, exemplified by the [face landmarker.task](https://developers.google.com/mediapipe/solutions/vision/face_landmarker#models):

<img width="649" alt="Screenshot 2023-10-04 at 3 22 29 PM" src="https://github.com/google/mediapipe/assets/98159216/4e895fc7-9021-406d-ab97-e57a36ef4bb7">


Upon executing the above command, you will obtain the TFLite files as outlined below:

**- Extracting: face_detector.tflite**
**- Extracting: face_landmarks_detector.tflite**
**- Extracting: face_blendshapes.tflite**

Regrettably, we do not offer support for ONNX input or its corresponding conversion. Additionally, the MediaPipe team neither recommends nor supports the conversion of models from TFLite. Thank you

**Comment by valsecchi** [comment]
Thanks a lot!

**Comment by ErwinCheung** [comment]
the RAR tools can check or unzip the task format model
