### ISSUE TITLE
Clarification about the Parameter Setting in Pose landmark detection guide

### ISSUE THREAD

**Issue by KunHanKH** [google/mediapipe#4859]
### Clear description

In the parameter setting of the PoseLandmarkerOption, there is `min_pose_presence_score`. What is the usage of the parameter? Does this parameter used to filter individual landmarker or the entire set of landmarkers? I try to tune the parameter in the live demo, but no difference is found with various `min_pose_confidence_score` setting. Could you explain the usage to me?`

**Comment by schmidt-sebastian** [comment]
min_pose_presence_score is used to filter the pose before it is being fed to the landmarks calculator. You should see a difference as you move the pose off screen.
