### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Fail to find supported surface info - CameraId:null

### ISSUE THREAD

**Issue by momo1986** [google/mediapipe#486]
Need support for external camera.

Hello, I use the  camera from USB peripherals. 

However, mediapipe/java/com/google/mediapipe/components/CameraXPreviewHelper.java set like this:
```
LensFacing cameraLensFacing =
        cameraFacing == CameraHelper.CameraFacing.FRONT ? LensFacing.FRONT : LensFacing.BACK;
    PreviewConfig previewConfig =
        new PreviewConfig.Builder()
            .setLensFacing(cameraLensFacing)
            .setTargetResolution(TARGET_SIZE)
            .build();
```

It will be crashed that it has the assumptions that the android device has the front cam or back cam. However, for some devices, it use the external camera, e.g., from USBs.

How can I enable the camera usage in USB?

Currently, the face_detection_cpu will be crashed due to failure of camera loading.
 

>    --------- beginning of crash
> 2020-03-02 16:55:39.980 4908-4908/? E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.google.mediapipe.apps.facedetectioncpu, PID: 4908
>     java.lang.RuntimeException: Unable to resume activity {com.google.mediapipe.apps.facedetectioncpu/com.google.mediapipe.apps.facedetectioncpu.MainActivity}: java.lang.IllegalArgumentException: Fail to find supported surface info - CameraId:null
>         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3584)
>         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3624)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1641)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6518)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
>      Caused by: java.lang.IllegalArgumentException: Fail to find supported surface info - CameraId:null
>         at androidx.camera.camera2.impl.Camera2DeviceSurfaceManager.requiresCorrectedAspectRatio(Camera2DeviceSurfaceManager.java:274)
>         at androidx.camera.core.Preview.updateUseCaseConfig(Preview.java:476)
>         at androidx.camera.core.UseCase.<init>(UseCase.java:96)
>         at androidx.camera.core.Preview.<init>(Preview.java:115)
>         at com.google.mediapipe.components.CameraXPreviewHelper.startCamera(CameraXPreviewHelper.java:82)
>         at com.google.mediapipe.apps.facedetectioncpu.MainActivity.startCamera(MainActivity.java:168)
>         at com.google.mediapipe.apps.facedetectioncpu.MainActivity.onResume(MainActivity.java:103)
>         at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
>         at android.app.Activity.performResume(Activity.java:7111)
>         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3559)
>         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3624) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1641) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:164) 
>         at android.app.ActivityThread.main(ActivityThread.java:6518) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

Thanks & Regards!

**Comment by eknight7** [comment]
Hi, we haven't tested Android devices with external USB cameras.
Do you have a class that grabs frames from the USB camera for an Android device? We could discuss how to use it with the MediaPipe example apps. 
Also, which Android device and USB camera are you using?

**Comment by momo1986** [comment]
Hello @eknight7, the USB camera we used is some Logitecch C270, the device we used is the Android device in some piano without inside camera but with external USB camera, Android version is 8.1, Android kernel version is 3.18.71-perf, API level is 27 or 28.

**Comment by momo1986** [comment]
Hello @eknight7 and other guys, I noticed that there are some external libraries to support the external USB library.
https://github.com/jiangdongguo/AndroidUSBCamera
https://github.com/saki4510t/UVCCamera
These are not the official maven library.

I noticed that you defined the dependent library in third_party/BUILD, its grammatical style is a little bit different from build.graddle.

How can I do some configuration and editing to reference the GitHub repositories mentioned above without influence the origin/master branch to support my own request.

If you could support external camera, it would also be very great.

Thanks & Regards!

**Comment by eknight7** [comment]
In fact, the documentation also has some details about using [MediaPipe with Gradle](https://github.com/google/mediapipe/issues/343). @jiuqiant can help more with the question about dependencies in `third_party/BUILD` v/s `build.gradle`.

> If you could support external camera, it would also be very great.

To immediately proceed with using a USB camera Android, try adapting the code in the repositories you found and use it with an example MediaPipe app, such as [edge detection](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu). This [tutorial](https://mediapipe.readthedocs.io/en/latest/hello_world_android.html) describes how to build the edge detection app from scratch, so you can follow it and use your USB camera code instead of the CameraX code linked in the tutorial.

There is some more documentation about external cameras in the [Android developer docs](https://source.android.com/devices/camera/external-usb-cameras).

It is definitely useful to have such a utility for MediaPipe users. We would recommend you to create one and submit a pull request. Please see [Contributing.md](https://github.com/google/mediapipe/blob/master/CONTRIBUTING.md) for more details.

**Comment by momo1986** [comment]
Hello @eknight7, I tried to support USB camera today.

However, I met some problems.

Let me clarify my dilemma.

I tried to add thirdy_paty/BUILD with new configuration:

```
android_library(
   name = "jitpack",
   exports = [
       "@maven//:com_github_jitpack_maven-simple",
   ],
)
android_library(
    name = "com_serenegiant_common",
    exports = [
        "@maven//:com_serenegiant_common",
    ],
)
android_library(
    name = "com_serenegiant_uvccamera",
    exports = [
        "@maven//:com_serenegiant_uvccamera_libuvccamera",
    ],
)
```

It refers to these three maven repositories:
https://mvnrepository.com/artifact/com.github.jitpack/maven-simple
https://mvnrepository.com/artifact/com.serenegiant/common
https://mvnrepository.com/artifact/com.serenegiant.uvccamera/libuvccamera


When I fetch the library with build of cpu-face-detection:
`bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu`


It reports the error:

> ERROR: /Users/junyan/find_android_project/mediapipe-master/third_party/BUILD:140:1: no such target '@maven//:com_serenegiant_common': target 'com_serenegiant_common' not declared in package '' defined by /private/var/tmp/_bazel_junyan/d0562ae4205a819f08c6b310db2d9181/external/maven/BUILD and referenced by '//third_party:com_serenegiant_common'
> INFO: Call stack for the definition of repository 'android_opencv' which is a http_archive (rule definition at /private/var/tmp/_bazel_junyan/d0562ae4205a819f08c6b310db2d9181/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
>  - /Users/junyan/find_android_project/mediapipe-master/WORKSPACE:185:1
> ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu:facedetectioncpu' failed; build aborted: Analysis failed
> INFO: Elapsed time: 1257.395s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (132 packages loaded, 11600 target\
> s configured)

My question is:
1. To use these three maven repositories, is there any error I should fix in thirdy_party/BUILD?
2. What other files should I modifiy under the directory of mediapipe to support these three external Android libraries?

Looks like that there is no problem to fetch the library of jitpack until now.

When loading these third-paty tools smoothly under the project of mediapipe, I think there is no problem for external USB device support.

Thanks & Regards!
^_^

**Comment by eknight7** [comment]
Answered in https://github.com/google/mediapipe/issues/501#issuecomment-596689243.
