### ISSUE TITLE
Mediapipe 在 ios 系统上, 识别效果比其他平台差, 识别出来的face landmark 眼睛不能正常的闭合 

### ISSUE THREAD

**Issue by mingxingren** [google/mediapipe#4861]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

IOS 16.2

### Mobile device if the issue happens on mobile device

iPhone 11

### Programming Language and version

C++

### MediaPipe version

0.8.11

### Solution

FaceMesh

### Describe the actual behavior

mediapipe在ios识别到face landmarks 眼睛不能很好的闭合, 并且抖动地更厉害, 其他平台没这个问题

### Describe the expected behaviour

mediapipe在ios识别到face landmarks 眼睛能正常识别到开闭

### Standalone code/steps you may have used to try to get what you need

```shell
use example code
```

**Comment by kuaashish** [comment]
@mingxingren,

Could you please elaborate your query with complete details. Thank you!
