### ISSUE TITLE
Can't see any error messages after importing ProcessMediapipe in Python

### ISSUE THREAD

**Issue by jorgebonafe** [google/mediapipe#4872]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 10

### Programming Language and version

Python

### MediaPipe version

0.10.7

### Solution

Any

### Describe the actual behavior

Can't see any exceptions

### Describe the expected behaviour

Should be able to see exceptions when they happen

### Standalone code/steps you may have used to try to get what you need

```shell
# Adding this import to any python script will cause
# any exceptions that happen to make the script crash without error messages.
# This makes it very hard to debug complex applications.
# Removing the import will cause the crash to be outputed in the console as it should. This problem happens to any exceptions that may happen.
import mediapipe
makeItCrash = 1/0
```

**Comment by kuaashish** [comment]
@jorgebonafe,

Kindly provide additional details for your inquiry, including comprehensive information such as the steps outlined in the documentation. If possible, include a reproducible code example. This will enable us to better understand the issue and assist you more effectively. Thank you

**Comment by jorgebonafe** [comment]
I did provide a reproducible code example. Just those two lines reproduce the issue. Simple comment and uncomment the import and you will see the issue.

**Comment by jorgebonafe** [comment]
Oops... My apologies, that was a typo. I meant to say import mediapipe. I have corrected the code.

**Comment by schmidt-sebastian** [comment]
The install and basic usage works for me on Windows 10. Please provide additional debugging/logging.

**Comment by jorgebonafe** [comment]
I'm sorry, I don't know how I'm supposed to add additional debugging. There is no way to debug anything.
I have tested it in Windows 10 and it worked. I'm having this problem in Windows 11, with mediapipe 0.10.7, and python 3.8.18. Please let me know if there is any other data you need from me.

**Comment by jorgebonafe** [comment]
Thank you. I have updated the python version and the problem went away.
