### ISSUE TITLE
setLandscapeOrientation in CameraXPreviewHelper.java is not working

### ISSUE THREAD

**Issue by toby018** [google/mediapipe#4873]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android 10

### Mobile device if the issue happens on mobile device

samsung

### Programming Language and version

Java

### MediaPipe version

0.8.11

### Solution

hand

### Android Studio, NDK, SDK versions (if issue is related to building in Android environment)

29

### Describe the actual behavior

setLandscapeOrientation in CameraXPreviewHelper.java is not working

### Describe the expected behaviour

setLandscapeOrientation in CameraXPreviewHelper.java can working

### Standalone code/steps you may have used to try to get what you need

```shell
add setLandscapeOrientation to true in CameraInput.java
rebuild the hand demo app
then test it in pone screenOrientation in landscape
the display show error
```

### Other info / Complete Logs

```shell
Revision: 3adc068e97eaae6a0261368aec44dccb824a0fc5
Author: MediaPipe Team <mediapipe-team@google.com>
Date: 2023/10/10 6:19:26
Message:
Add OnCameraBoundListener and support for landscape orientation to CameraXPreviewHelper

PiperOrigin-RevId: 572054649
----
Modified: mediapipe/java/com/google/mediapipe/components/CameraXPreviewHelper.java
```

**Comment by kuaashish** [comment]
Hi @toby018,

Could you please let us know which documentation you are following to build the Hands Application? If you are using the documentation from [here](https://github.com/google/mediapipe/blob/master/docs/solutions/hands.md), I am sorry to say that this belongs to the legacy solution, which we have discontinued. For more information, please see [here](https://developers.google.com/mediapipe/solutions/guide#legacy).

However, the libraries, documentation, and source code for all the MediaPipe legacy solutions will continue to be available in our [GitHub repository](https://developers.google.com/mediapipe/solutions/guide#legacy) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](ttps://www.npmjs.com/search?q=%40mediapipe). 

We request that you check the [new Hand Landmarker API](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/android) for the Android platform, which can help you more easily build and customise ML solutions for your application. This new Hand Landmarker Task API provides a superset of the capabilities available in the legacy solutions.  Thank you!

**Comment by toby018** [comment]
the [new Hand Landmarker API] using canvas.draw,has too much delay,the legacy solution using opengl draw,has good synchronization.
You team submitted the code for this issue the other day, please help confirm that this issue is fixed? How do I make landscape orientation?

**Comment by kuaashish** [comment]
Hi @toby018,

Thank you for sharing your observations with us. We would like to inform you that we have discontinued support for older legacy solutions. Regarding the landscape orientation issue in the Hand Landmarker API, we have escalated the matter internally. We appreciate your understanding and hope to provide you with a resolution soon.
