### ISSUE TITLE
MediaPipe Python Build: Unexpected Errors on Windows 11

### ISSUE THREAD

**Issue by einsteinfantasy** [google/mediapipe#4876]
### OS Platform and Distribution

 Windows 11

### Compiler version

protoc-24.4

### Programming Language and version

python 3.11

### Installed using virtualenv? pip? Conda?(if python)

virtualenv 

### MediaPipe version

0.10.7

### Bazel version

Bazelisk version: v1.18.0

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

 3.4.10

### Describe the problem

Hello,  I'm relatively new to MediaPipe, and I have encountered an issue with my MediaPipe Python Package build on a Windows 11 system. 

I have successfully installed and ran the 'hello world' example build following the MediaPipe intallation tutorial https://developers.google.com/mediapipe/framework/getting_started/install. 

Later, I managed to build the python package according to the tutorial on:
https://github.com/google/mediapipe/blob/master/docs/getting_started/python.md

However, when I try to import and run my built python package, I encounter the following error:   

  File "G:\testest.py", line 119, in <module>
    with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\mediapipe\mp_env\Lib\site-packages\mediapipe\python\solutions\pose.py", line 146, in __init__
    super().__init__(
  File "G:\mediapipe\mp_env\Lib\site-packages\mediapipe\python\solution_base.py", line 285, in __init__
    self._graph = calculator_graph.CalculatorGraph(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: ValidatedGraphConfig Initialization failed.

Please note that I haven't made any modifications to the git clone of the MediaPipe source code. I just wanted to test if I could compile the MediaPipe python package on Windows 11. 

Here are the steps before I encounter the problem.
1. git clone --depth 1 https://github.com/google/mediapipe.git 
2. cd mediapipe 
3. Edit the .bazelrc file add the following lines as instructed by https://bazel.build/configure/windows#build-c-with-msvc : --output_user_root=G:/temp,   startup --output_base=G:\\bazel_output,    startup --windows_enable_symlinks,    build --enable_runfiles    
4. Edite opencv path in the workspace file 
5. Create a virtual environment with python 3.11: "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe" -m venv mp_env  
6. pip install -r requirements.txt 
7. python setup.py install --link-opencv 
8. run a test python script which works with the official python package 0.10.7.  
I hope someone can guide me on why my custom-built Python MediaPipe package doesn't work the same as the official one. Thank you in advance! 
You can view the complete logs in the Complete Logs section.  

### Complete Logs

```shell
(mp_env) G:\>python testest.py
Video Parameters - Width:  1280  Height:  720  FPS:  60
Traceback (most recent call last):
  File "G:\testest.py", line 119, in <module>
    with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\mediapipe\mp_env\Lib\site-packages\mediapipe\python\solutions\pose.py", line 146, in __init__
    super().__init__(
  File "G:\mediapipe\mp_env\Lib\site-packages\mediapipe\python\solution_base.py", line 285, in __init__
    self._graph = calculator_graph.CalculatorGraph(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: ValidatedGraphConfig Initialization failed.
ImageToTensorCalculator: ; RET_CHECK failure (mediapipe/calculators/tensor/image_to_tensor_calculator.cc:142) ValidateOptionOutputDims(options) returned INTERNAL: ; RET_CHECK failure (.\mediapipe/calculators/tensor/image_to_tensor_utils.h:136) options.has_output_tensor_float_range() || options.has_output_tensor_int_range() || options.has_output_tensor_uint_range()Output tensor range is required.
InferenceCalculatorCpu: ; RET_CHECK failure (mediapipe/calculators/tensor/inference_calculator_cpu.cc:56) !options.model_path().empty() ^ kSideInModel(cc).IsConnected()Either model as side packet or model path in options is required.
SplitDetectionVectorCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
ImageToTensorCalculator: ; RET_CHECK failure (mediapipe/calculators/tensor/image_to_tensor_calculator.cc:142) ValidateOptionOutputDims(options) returned INTERNAL: ; RET_CHECK failure (.\mediapipe/calculators/tensor/image_to_tensor_utils.h:136) options.has_output_tensor_float_range() || options.has_output_tensor_int_range() || options.has_output_tensor_uint_range()Output tensor range is required.
ConstantSidePacketCalculator: ; RET_CHECK failure (mediapipe/calculators/core/constant_side_packet_calculator.cc:64) (cc->OutputSidePackets().NumEntries(kPacketTag))==(options.packet_size())Number of output side packets has to be same as number of packets configured in options.
ConstantSidePacketCalculator: ; RET_CHECK failure (mediapipe/calculators/core/constant_side_packet_calculator.cc:64) (cc->OutputSidePackets().NumEntries(kPacketTag))==(options.packet_size())Number of output side packets has to be same as number of packets configured in options.
ConstantSidePacketCalculator: ; RET_CHECK failure (mediapipe/calculators/core/constant_side_packet_calculator.cc:64) (cc->OutputSidePackets().NumEntries(kPacketTag))==(options.packet_size())Number of output side packets has to be same as number of packets configured in options.
SplitTensorVectorCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
SplitNormalizedLandmarkListCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
SplitLandmarkListCalculator: The number of output streams should match the number of ranges specified in the CalculatorOptions.
```

**Comment by einsteinfantasy** [comment]
> Hi @einsteinfantasy,
> 
> Based on the issue description, it appears that you are using the legacy Pose solution, which has been upgraded to the Pose landmark Task API as described [here](https://developers.google.com/mediapipe/solutions/guide#legacy). We have discontinued support for legacy solutions that have already been upgraded.
> 
> However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).
> 
> You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new Pose Landmarker Task API in the Python](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions.
> 
> Thank you!!

Thank you for your prompt response.@kuaashish 
I see my only choice is to close the issue now.
I understand from your reply that the pose solution I initially mentioned is considered legacy and is not actively supported. However, the primary focus of my project is on the holistic landmarks. As far as my research and understanding go, only the legacy solution currently supports holistic landmarks in MediaPipe.

Considering the significance of the holistic model for many applications, including mine, it's crucial for me to get this issue resolved. If the holistic model is also considered a legacy solution, this would pose challenges for developers who heavily rely on it.

I genuinely appreciate the effort and contributions from the MediaPipe team. However, I still want you to shine some light on how to rebuild the current MediaPipe with changes to use the holistic solution, considering it is most developers' only option.

Thank you for understanding and looking forward to your insights.

**Comment by schmidt-sebastian** [comment]
The new Holistic API is almost ready and will be released soon. Let us know if you are fine to wait for bit.

**Comment by kuaashish** [comment]
Hi @einsteinfantasy,

Our new Holistic Task API has been released. Could you give the new [HolisticLandmarker](https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/vision/holistic_landmarker.py) task APIs a try and let us know if you encounter any issues?

Thank you!!

**Comment by einsteinfantasy** [comment]
> Hi @einsteinfantasy,
> 
> Our new Holistic Task API has been released. Could you give the new [HolisticLandmarker](https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/vision/holistic_landmarker.py) task APIs a try and let us know if you encounter any issues?
> 
> Thank you!!

Thank you for sharing,I'm excited to give the new holistic APIs a try. 
With the introduction of this API, can we also expect a holistic solution release in the near future?

**Comment by kuaashish** [comment]
Hi @einsteinfantasy,

Apologies for any inconvenience, but we are no longer maintaining legacy solutions. The release won't be possible as we. have transitioned to Task APIs, which are upgraded versions offering enhanced capabilities compared to the legacy solutions.

Thank you!!
