### ISSUE TITLE
How to properly include a Licence Notice for using MediaPipe on a Webpage?

### ISSUE THREAD

**Issue by Hybarbel** [google/mediapipe#4877]
I'm using MediaPipes "Face Landmarker"-model in my webproject and would like to include the licence notice in the legal details. 
I haven't found anything about it in the documentations or on the MediaPipe Solution webpage. 
I'm also relatively new to webprogramming and don't realy know if i need the users consent before I use the "Face Landmarker"-model for the web.
Is there a chance anyone can gve me an example on how to include the licence in the legal details?

Kind regards!

**Comment by kuaashish** [comment]
Hi @Hybarbel,

Please allow us sometime to provide the support you are looking from us. Thank you!

**Comment by schmidt-sebastian** [comment]
We are using Apache License Version 2.0: https://github.com/google/mediapipe/blob/master/LICENSE

Please refer to this license text or any documentation you may find. We cannot give legal advise.
