### ISSUE TITLE
FaceLandmarker not available on Mac OS with Python

### ISSUE THREAD

**Issue by piekaa** [google/mediapipe#4882]
### OS Platform and Distribution

macOS Montery 12.7

### Programming Language and version

Python 3.9.5

### Android AAR (if android)

None

### Describe the problem

Cannot use FaceLandmarker on mac with python

### Complete Logs

Hey, is FaceLandmarker planned to be available in Python library on Mac os?

```shell

AttributeError: module 'mediapipe.tasks.python.vision' has no attribute 'FaceLandmarkerOptions'
```

I guess that's related to version, cos for linux 0.10.7 it works

```
pip install mediapipe==0.10.7
ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.7 (from versions: 0.8.4.2, 0.8.5, 0.8.6.2, 0.8.7.1, 0.8.7.2, 0.8.7.3, 0.8.8.1, 0.8.9.1, 0.8.10, 0.8.10.1, 0.8.11, 0.9.0, 0.9.0.1, 0.9.1.0)
ERROR: No matching distribution found for mediapipe==0.10.7
```

Thanks ;)
```

**Comment by kuaashish** [comment]
Hi @piekaa,

Could you please outline the exact steps you are following, referencing the documentation? Additionally, kindly confirm the macOS version you are using—specifying whether it is based on the Silicon chip or Intel. This information will help us reproduce and better understand the issue on our end.

Thank you

**Comment by kuaashish** [comment]
Hi @piekaa,

It appears there may be an issue related to the macOS version. Kindly upgrade to macOS version 13.6 or a newer release. Additionally, ensure that the build is using a Python version supported between 3.8 to 3.11, as it is compatible with macOS, Linux, and Windows as per our [guidelines](https://developers.google.com/mediapipe/solutions/setup_python). 

Please follow the provided instructions and let us know if this works for you. Thank you

**Comment by piekaa** [comment]
Hey @kuaashish, thanks for response.
Apparently my Mac isn't compatible with macOS Ventura (Version 13) :/ 12.7 is highest I can update to.
It's MacBook Air (13-inch, 2017) (Intel)

There is no hope? :D

**Comment by kuaashish** [comment]
Hi @piekaa,

Kindly attempt the manual installation of MediaPipe version 0.10.7 by downloading the wheels file `'mediapipe-0.10.7-cp39-cp39-macosx_11_0_universal2.whl' `from this [source](https://pypi.org/project/mediapipe/0.10.7/#modal-close). Ensure compatibility with your version 3.9.5, and execute the following command:

`pip install path/to/wheel.whl`

Or

`pip3 install path/to/wheel.whl`


Please inform us if this solution is effective in your case. Thank you

**Comment by BrandlMax** [comment]
Hey 👋 I think I have a similar problem:

### OS Platform and Distribution
macOS Sonoma 14.0 (Intel)

### Programming Language and version
Python 3.11.5

### MediaPipe Version
Version: 0.9.1.0

### ERROR
```
AttributeError: module 'mediapipe.tasks.python.vision' has no attribute 'PoseLandmarkerOptions'
```

I also get the following error when trying to install the latest version of MediaPipe:
```
pip install mediapipe==0.10.7

ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.7 (from versions: 0.9.1.0)

ERROR: No matching distribution found for mediapipe==0.10.7
```

When trying to install using the wheels file I also get this error:

```
pip install /mediapipe-0.10.7-cp311-cp311-macosx_11_0_universal2.whl 

ERROR: mediapipe-0.10.7-cp311-cp311-macosx_11_0_universal2.whl is not a supported wheel on this platform.
```

Is macOS 14.0 not yet supported?

If it's a different problem I'll create a separate issue, but I thought it's probably related.

Thank you for your time!

**Comment by piekaa** [comment]
@kuaashish 
> Ensure compatibility with your version 3.9.5

how do I do that? 🤔 

Anyway, tried it and got an error :/
```
pip install mediapipe-0.10.7-cp39-cp39-macosx_11_0_universal2.whl

ERROR: mediapipe-0.10.7-cp39-cp39-macosx_11_0_universal2.whl is not a supported wheel on this platform.
```

**Comment by kuaashish** [comment]
@piekaa,

Kindly create a new request, providing comprehensive details as outlined previously. In the interim, feel free to track this discussion for relevant updates.

**Comment by kuaashish** [comment]
Hi @piekaa,

Please confirm your Python version and obtain the suitable wheel file from this [location](https://pypi.org/project/mediapipe/0.10.7/#files). For instance, if your current Python installation is version 3.9.5, please download the "mediapipe-0.10.7-cp39-cp39-macosx_11_0_universal2.whl" and proceed with a manual installation. 

Similarly, if your Python version is 3.10, download and manually install the "mediapipe-0.10.7-cp310-cp310-macosx_11_0_universal2.whl". Kindly inform us of the effectiveness of this procedure in your specific situation.

Thank you

**Comment by schmidt-sebastian** [comment]
This is the same as https://github.com/google/mediapipe/issues/4888 (which has the slightly more specific title, so I am closing this).
