### ISSUE TITLE
Cross Compiling mediapipe on Ubuntu

### ISSUE THREAD

**Issue by phil-fill** [google/mediapipe#4883]
### OS Platform and Distribution

Ubuntu 22.04.2 LTS

### Compiler version

gcc 11.4.0

### Programming Language and version

-

### MediaPipe version

current

### Bazel version

6.3.2

### Android AAR (if android)

None

### Describe the problem

A bug happened!

### Complete Logs

```shell
root@c339f15c76d1:/mediapipe# pwd
/mediapipe
root@c339f15c76d1:/mediapipe# bazel build \
>     --crosstool_top=@crosstool//:toolchains \
>     --compiler=gcc \
>     --cpu=aarch64 \
>     --define darwinn_portable=1 \
  --defi>     --define MEDIAPIPE_DISABLE_GPU=1 \
>     --define MEDIAPIPE_EDGE_TPU=usb \
>     --linkopt=-l:libusb-1.0.so \
>     mediapipe/examples/coral:face_detection_tpu build
2023/10/17 15:01:23 Downloading https://releases.bazel.build/6.1.1/release/bazel-6.1.1-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/dcffa4094e13d56a30b2cdcdb709ce5d71b38953.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1c154bd755153b5c6ada4bbed58facf23f6abffc.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
ERROR: Skipping 'build': no such target '//:build': target 'build' not declared in package '' defined by /mediapipe/BUILD.bazel (Tip: use `query "//:*"` to see all the targets in that package)
WARNING: Target pattern parsing failed.
ERROR: no such target '//:build': target 'build' not declared in package '' defined by /mediapipe/BUILD.bazel (Tip: use `query "//:*"` to see all the targets in that package)
INFO: Elapsed time: 78.435s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded)
root@c339f15c76d1:/mediapipe#
```

**Comment by 1cipher** [comment]
Hi @phil-fill , could you share how you managed to solve this problem?

**Comment by Sirhxs** [comment]
> ### OS Platform and Distribution
> Ubuntu 22.04.2 LTS
> 
> ### Compiler version
> gcc 11.4.0
> 
> ### Programming Language and version
> 
> ### Installed using virtualenv? pip? Conda?(if python)
> _No response_
> 
> ### MediaPipe version
> current
> 
> ### Bazel version
> 6.3.2
> 
> ### XCode and Tulsi versions (if iOS)
> _No response_
> 
> ### Android SDK and NDK versions (if android)
> _No response_
> 
> ### Android AAR (if android)
> None
> 
> ### OpenCV version (if running on desktop)
> _No response_
> 
> ### Describe the problem
> A bug happened!
> 
> ### Complete Logs
> ```shell
> root@c339f15c76d1:/mediapipe# pwd
> /mediapipe
> root@c339f15c76d1:/mediapipe# bazel build \
> >     --crosstool_top=@crosstool//:toolchains \
> >     --compiler=gcc \
> >     --cpu=aarch64 \
> >     --define darwinn_portable=1 \
>   --defi>     --define MEDIAPIPE_DISABLE_GPU=1 \
> >     --define MEDIAPIPE_EDGE_TPU=usb \
> >     --linkopt=-l:libusb-1.0.so \
> >     mediapipe/examples/coral:face_detection_tpu build
> 2023/10/17 15:01:23 Downloading https://releases.bazel.build/6.1.1/release/bazel-6.1.1-linux-x86_64...
> Extracting Bazel installation...
> Starting local Bazel server and connecting to it...
> WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
> WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/dcffa4094e13d56a30b2cdcdb709ce5d71b38953.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
> WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1c154bd755153b5c6ada4bbed58facf23f6abffc.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'com_google_absl' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'com_google_benchmark' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'flatbuffers' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'pybind11_bazel' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'com_google_protobuf' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'com_google_googletest' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'zlib' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'xctestrunner' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'pybind11' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'pybind11_protobuf' because it already exists.
> DEBUG: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/third_party/repo.bzl:132:14:
> Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
> ERROR: Skipping 'build': no such target '//:build': target 'build' not declared in package '' defined by /mediapipe/BUILD.bazel (Tip: use `query "//:*"` to see all the targets in that package)
> WARNING: Target pattern parsing failed.
> ERROR: no such target '//:build': target 'build' not declared in package '' defined by /mediapipe/BUILD.bazel (Tip: use `query "//:*"` to see all the targets in that package)
> INFO: Elapsed time: 78.435s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (2 packages loaded)
> root@c339f15c76d1:/mediapipe#
> ```

Hi @phil-fill , could you share how you managed to solve this problem?I have the same problem with this issue。
https://github.com/google-ai-edge/mediapipe/issues/5625
