### ISSUE TITLE
want same landmark in holistic and hand

### ISSUE THREAD

**Issue by jmjang000** [google/mediapipe#4886]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows in VS CODE

### MediaPipe version

Version: 0.9.2.1

### Programming Language and version

python

### Describe the actual behavior

holistic in part of hand and hand in part of hand are showing in the same camera

**Comment by kuaashish** [comment]
Hi @jmjang000,

Could you please confirm if the current issue corresponds to case number #4887? If so, we can proceed to close the current case and initiate a follow-up with a new one. Thank you

**Comment by jmjang000** [comment]
> Hi @jmjang000,
> 
> Could you please confirm if the current issue corresponds to case number #4887? If so, we can proceed to close the current case and initiate a follow-up with a new one. Thank you

Yes #4887 is  the current problem!
