### ISSUE TITLE
How to get mediapipe to use Mac silicon GPU for inference

### ISSUE THREAD

**Issue by alanwilter** [google/mediapipe#4896]
I have a MBP with M1 using `homebrew` and needed library installed via pip:

```
Python 3.9.18
mediapipe                 0.9.3.0
mediapipe-silicon         0.9.2.1
```

I'm only annoyed by the fact when I run my code I see this:

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

**Comment by kuaashish** [comment]
Hi @alanwilter,

This task is already on our roadmap and may be included in the upcoming release. At present, utilising GPU via pip is not supported. Unfortunately, we cannot provide a specific timeline for this feature at the moment. 

Thank you

**Comment by alanwilter** [comment]
Certainly! Here's the proofread version of your text:

Exciting news! Thanks for letting us know.

In any case, is there currently any platform (Linux, Mac Intel, Windows, or Windows + WSL) that I could use to run MP with GPU to test the performance of our application? 

Do I need to perform any specific steps? 

A how-to or tutorial would be appreciated if applicable.

**Comment by kuaashish** [comment]
Hi @alanwilter,

At present, the only available resource for running GPU support, which includes both MediaPipe Legacy Solutions, in Python is sourced from a community [repository](https://github.com/riverzhou/mediapipe), specifically from the older version 0.10.1. Unfortunately, beyond this, there are no identifiable resources for GPU support in Python.

Thank you

**Comment by kuaashish** [comment]
HI @alanwilter,

We are pleased to announce the release of MP version 0.10.8, which now supports Python GPU via pip on macOS and Linux. As outlined in the [release notes](https://github.com/google/mediapipe/releases/tag/v0.10.8), we kindly request you to build using the latest version and inform us of your experience with GPU utilisation using Python Wheels.

Thank you

**Comment by alanwilter** [comment]
Thanks for that.

I did give a try and I see this:

```
I0000 00:00:1699650939.597665       1 gl_context.cc:344] GL version: 2.1 (2.1 Metal - 88), renderer: Apple M1 Max
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```
It didn't make any apparent difference time processing but then I realised that the MP step might be done in the GPU, however, I use several numpy functions that I don't think would use the GPU.
Nevertheless, I'm still puzzled with `INFO: Created TensorFlow Lite XNNPACK delegate for CPU`.

**Comment by alanwilter** [comment]
Do I have to install `tensorflow`?

I tried my app in linux with GPU and tensorflow 2.14, able to use GPU and I got this:

```
2023-11-10 16:59:22.284363: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-10 16:59:22.284413: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-10 16:59:22.284462: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-10 16:59:22.292520: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```
Still, no difference in speed.

**Comment by miscedence12** [comment]
@alanwilter  Hello ,may I ask if you have figured this out, I also found no difference in time，I often also get （INFO: TensorFlow Lite XNNPACK delegate created for CPU）.

**Comment by miscedence12** [comment]
@kuaashish

**Comment by alanwilter** [comment]
No, no diff so far. I use a lot of numpy, so I tried Numpy compiled for M1, but not diff either. I tried to parallelise the functions I call, no diff either.

I will give another try on a Linux with GPUs when I have time.

**Comment by wolfiex** [comment]
> release notes

Do you have any instructions on how to enable GPU support?

**Comment by faunris** [comment]
Hi @wolfiex,

I made a small example for this: https://github.com/faunris/ai-hand-tracking

**Comment by jbartolozzi** [comment]
On MacOs 15.5 I was able to get the following in my log and much better performance
```
INFO: Created TensorFlow Lite delegate for Metal.
```
I used python 3.12
`conda create -n "$ENV_NAME" python=3.12 -y`
`pip install --upgrade pip`

Then installed the following
```
mediapipe             0.10.21
ml_dtypes             0.5.1
numpy                 1.26.4
opencv-contrib-python 4.11.0.86
opencv-python         4.11.0.86
```

I should also mention I was seeing the following error until I switched to using RGBA images
```F0000 00:00:1751491869.888206 30240151 gpu_buffer_storage_cv_pixel_buffer.cc:154] Check failed: status_or_buffer is OK (UNKNOWN: ; unsupported ImageFrame format: 1)```
Per the suggestion found here: https://github.com/google-ai-edge/mediapipe/issues/5265#issuecomment-2020611937
