### ISSUE TITLE
Pybind unavailable when installed using chaquopy

### ISSUE THREAD

**Issue by usmanaqeel786** [google/mediapipe#4897]
### OS Platform and Distribution

android

### Programming Language and version

Python

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

latest

### Android SDK and NDK versions (if android)

21

### Android AAR (if android)

None

### Describe the problem

when installing through chaquopy  whl file,  can not see pybind11 modules in mediapipe package

I have been trying to run mediapipe on android studio using chaquopy 14.0

Everything working fine except when package is installed in my android folder, i can not see pybind11 modules which are basically c++ modules required to run library. when i clone git repo, i can see all files available but unable to generate wheel from that repo. i am basically creating a facemesh in mediapipe and need to run python script on android and communicate through modules in my react native app.

Can you please help me to find a solution. When i try to create wheel using setup.py it throws exceptions

### Complete Logs

```shell



Stderr: [FATAL 06:41:17.311 src/main/cpp/blaze.cc:1302] Unknown startup option: '-l'.
  For more info, run 'bazel help startup_options'.
WARNING: Target pattern parsing failed.                                                                                                                                                                                
ERROR: no such package '@flatbuffers//': Non-zero return code(2) when executing 'C:\ProgramData\chocolatey\bin\bazel.exe -l -c "rm" "-rf" 


i am using 

python 3.8.10
chaquopy 14
pip 23.1

i also tried using wsl2 but same results !
```

**Comment by kuaashish** [comment]
Hi @usmanaqeel786,

We have not conducted testing for this particular scenario within MediaPipe, and we do not currently have documented procedures for utilizing Android Studio with Chaquopy.

We kindly ask you to submit a feature request with detailed information regarding this matter. Our team will then internally review and prioritise this task. Thank you for your cooperation.
