### ISSUE TITLE
New Holistic Solution Release

### ISSUE THREAD

**Issue by philiprkk** [google/mediapipe#4899]
Hello! Is there any information as to when the new holistic solution will be available?

**Comment by kuaashish** [comment]
Hi @philiprkk,

The development of the New Holistic Task API is nearing completion and is expected to be included in the upcoming release. Unfortunately, we are currently unable to provide the exact release timing. Thank you for your understanding.

**Comment by philiprkk** [comment]
Good to hear, thanks!

**Comment by imsamimalik** [comment]
Any updates?
