### ISSUE TITLE
Do you have any example of deployment mediapipe to kubernetes in distributed mode?

### ISSUE THREAD

**Issue by dkozlov** [google/mediapipe#49]
Hello,

Do you have any example of deployment mediapipe to kubernetes in distributed mode? Or any plan to have an example with deployment of mediapipe in distributed mode to several machines?

**Comment by mgyong** [comment]
@dkozlov We have [Dockerfile](https://github.com/google/mediapipe/blob/master/Dockerfile) that you can use to build docker containers of MediaPipe.
Typically, MediaPipe graph runtime is one to one machine instance (i.e. parallel independent machines running multiple independent MediaPipe graphs). There is currently no support for MediaPipe in distributed mode (one graph on several machines).
What is the distributed mode you are looking for? and what use case? Media processing of lots of  video files

**Comment by dkozlov** [comment]
For example if you have a pipeline which should be executed in the real time and consist of  large neural network models which could not be placed on the single instance. Model parallelism, lower-latency parallel inference (at batch size 1). As I know Tensorflow could be runned in distributed mode for model parallelism. Do you have any example of integration mediapipe with https://github.com/tensorflow/mesh?

**Comment by dkozlov** [comment]
Thank you for response @mgyong! I have several different models which depend on each other and connected into single complicated pipeline and do not fit in single node. My workload is low-latency parallel inference with batch size equals to single image. Full pipeline latency should be less than 1 second. Actually I am not using the model parallelism it is just separately connected models but I am curious if mediapipe could help me.
