### ISSUE TITLE
How to use mediapipe with camera1.0 or 2.0

### ISSUE THREAD

**Issue by Devin0202** [google/mediapipe#490]
In android demo, mediapipe wrapped the camera and render functions in own way. It set cameraX as default choice. But there existed some projects used camera1.0 or 2.0, we want integrate mediapipe with these ones, for example: handtrackingGpu. What should we do for implementing this with codes?
Thanks~

**Comment by ZYloveGTR** [comment]
i have the same question,do you have any camera2.0 or camer1.0 demo for MediaPipe Android platform

**Comment by IvanYoga** [comment]
I faced with same issue #472 . Unfortunately for this moment we have only one option with 
`androidx.camera:camera-core:1.0.0-alpha06` because mediapipe requires camera's surface texture instance.

**Comment by eknight7** [comment]
FYI looking into fixing CameraX issues ASAP.

**Comment by eknight7** [comment]
FYI: https://github.com/google/mediapipe/issues/513#issuecomment-598052460.

**Comment by yxchng** [comment]
@eknight7 Is there any plan to add support for Camera2 in the future? CameraX is unstable and has many functionalities missing (e.g. unable to select between multiple back or front cameras)!

**Comment by eknight7** [comment]
The cameraX API version being used by MediaPipe is now version 1.0.0-beta10 from this release: https://github.com/google/mediapipe/releases/tag/0.7.12

We don't have any plans presently to provide Camera2 API support, CameraX is an easier to use API: https://developer.android.com/training/camerax.

Closing this issue for now. Please feel free to re-open if the question is still relevant. Thank you.

**Comment by Sreerag-ibtl** [comment]
@eknight7 In my use case I have to use a USB camera. I was wondering if mediapipe can access a USB camera because CameraX does not support external.

**Comment by HOLDfoot** [comment]
I have request a related feature
[https://github.com/google/mediapipe/issues/3508](url)
the current cameraX api is difficult to understand, in the same time, as a android programer, It is also difficault to recompile c++ project like mediapipe. I very hope official to adapt usb camera. It can help me save one week above

**Comment by HOLDfoot** [comment]
Can i repopen this issue, and how?
