### ISSUE TITLE
Different results when detecting facial landmarks in a single image and in a for loop including the single image

### ISSUE THREAD

**Issue by mart1n3rd** [google/mediapipe#4902]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 10

### Task name (e.g. Image classification, Gesture recognition etc.)

Facial Landmarks

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

The landmarks are not in the same coordinates when executing the single image and the same image included in a for loop

### Describe the expected behaviour

the landmarks in the same positions in the first and second execution

### Standalone code/steps you may have used to try to get what you need

```shell
https://colab.research.google.com/drive/1Mkq09EXRqYhhu0sCtfqYLJIK8XjCgkDe#scrollTo=sewWYQz0Mf-z
```

**Comment by kuaashish** [comment]
Hi @mart1n3rd,

Upon examining the provided Colab example, it seems that you are currently utilising the legacy face mesh solution, which is no longer under maintenance and has been integrated into the new Face Landmarker Task API, as explained [here](https://developers.google.com/mediapipe/solutions/guide#legacy).

We encourage you to explore the functionalities of our new Face Landmarker Task API, outlined in detail [here](https://developers.google.com/mediapipe/solutions/vision/face_landmarker), with specific guidance on building in the Python platform provided [here](https://developers.google.com/mediapipe/solutions/vision/face_landmarker/python). Additionally, a corresponding Colab notebook is available for reference [here](https://github.com/googlesamples/mediapipe/blob/main/examples/face_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Face_Landmarker.ipynb).

Kindly report any observed behaviour, ensuring to check if similar issues persist in the upgraded task API. Your feedback is appreciated.   Thank you

**Comment by aiot-tech** [comment]
Adding the parameter `static_image_mode=True` in the function of `mp_face_mesh.FaceMesh` is necessarily
