### ISSUE TITLE
How to customizing a pose recognizer model for recognizing some dance poses classification at android devices?

### ISSUE THREAD

**Issue by cjl84914** [google/mediapipe#4903]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

android12

### MediaPipe version

com.google.mediapipe:tasks-vision:0.10.0

### Solution

Pose

### Programming Language and version

Java

### Describe the actual behavior

detect...?

### Describe the expected behaviour

return pose classification

### Standalone code/steps you may have used to try to get what you need

```shell
I want to customizing a pose recognizer model for recognizing some dance poses classification.
Currently, Mediapipe guide has Hand gesture recognition model customization but no pose.
How to customizing a pose recognizer model for recognizing some dance poses classification at android devices?
```

**Comment by kuaashish** [comment]
Hi @cjl84914,

Currently, we understand that customisation may not be feasible on the Android platform. Nevertheless, we are confident that future updates will enable customisation in Python, similar to what we have already provided, for instance, in Gesture Recognition. 

Thank you

**Comment by cjl84914** [comment]
@kuaashish Thank you very much, My mean is Poses classification model will be enable customisation in Python, running in Android. 
Looking forward to it very much.
