### ISSUE TITLE
Commercial Usage of Object Detection Model

### ISSUE THREAD

**Issue by mosshah** [google/mediapipe#4906]
Considering that [object detection models](https://developers.google.com/mediapipe/solutions/vision/object_detector) are trained with [COCO dataset](https://cocodataset.org/#home), I'm wondering if pre-trained weights are allowed for commercial applications?

**Comment by kuaashish** [comment]
Hi @mosshah,

MediaPipe models are open for commercial use under the Apache License 2.0, as detailed in the [mediapipe/LICENSE](https://github.com/google/mediapipe/blob/master/LICENSE). For your convenience, please refer to the attached screenshot below for additional insights.
<img width="1403" alt="Screenshot 2023-10-25 at 12 38 11 PM" src="https://github.com/google/mediapipe/assets/98159216/94be2cd3-ed62-4698-aea6-e4b1e8959ce7">



Nevertheless, we strongly recommend reviewing the [mediapipe/LICENSE](https://github.com/google/mediapipe/blob/master/LICENSE) thoroughly before integrating them into your specific use case.


Thank you!

**Comment by kuaashish** [comment]
Hi @mosshah,

Could you please provide an update on the current status of the reported issue? If the issue has been resolved from your end, we can proceed to mark it as resolved and close it.

Thank you
