### ISSUE TITLE
Questions regarding Pose Detection custom training on Model Maker [not bug]

### ISSUE THREAD

**Issue by abhinavchawla13** [google/mediapipe#4907]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

N/A

### Python Version

N/A

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose Detection

### Describe the actual behavior

Ability to custom train pose detection model

### Describe the expected behaviour

Unable to find steps

### Standalone code/steps you may have used to try to get what you need

Hey everyone, I was reviewing the new Model Maker approach for custom training the models and was looking to get some answers around pose detection specifically as I wasn't able to find the exact documentation for it. Any help would be appreciated! 

1. How can we train the Pose detection model using the Model Maker? Is it possible?

2. One of the requirements for the current pose detection is the presence of a face. Is there a possibility to train the network without this requirement?

3. If not (2), is there a keypoint detection network that I could train with my custom data?

4. The model works with 3D keypoints. Would it be possible to train it on a 2D output, in hopes of getting higher FPS (on older devices)

Thanks!

**Comment by kuaashish** [comment]
Hi @abhinavchawla13,

Currently, our re-trainable capabilities include Objection Detection, Image Classification, Gesture Recognition, Face Stylization, Image Generation, and Text Classification as outlined in the [documentation](https://developers.google.com/mediapipe/solutions/guide#available_solutions).

However, we appreciate your interest in expanding these capabilities. We will categorise this as a feature request and share it with our team. The prioritisation of this request will be determined through internal discussions aligning with team priorities. We will keep you informed of any updates regarding the potential inclusion of this feature.

Thank you!

**Comment by joezoug** [comment]
Hi @abhinavchawla13 ,

(1) Thanks for raising this request. Unfortunately the team does not have bandwidth currently to add custom Pose Recognition. Your best bet would be to implement something similar to the Gesture Recognizer pipeline: https://github.com/google/mediapipe/tree/master/mediapipe/model_maker/python/vision/gesture_recognizer.

(2) I don't think the Pose Landmark Detection model requires a face to be present. The live demo here: https://mediapipe-studio.webapps.google.com/studio/demo/pose_landmarker works even when my face is outside the camera frame. The documentation for this model is here: https://developers.google.com/mediapipe/solutions/vision/pose_landmarker.

(4) Short answer is no. The provided pose landmark detection network cannot be re-trained and would be used only for data pre-processing in training a custom Pose recognizer model.

**Comment by abhinavchawla13** [comment]
Thanks @joezoug, for (2), I saw in the [model card](https://storage.googleapis.com/mediapipe-assets/Model%20Card%20BlazePose%20GHUM%203D.pdf) that it had mentioned "Head is not visible" in out of scope applications. It does seem to sometimes work well when face isn't there, but other times also gets really confused. I think blazepose uses face detector if possible, as defined in the [paper](https://arxiv.org/pdf/2006.10204.pdf).

Either ways, hoping we can train the model on our own dataset soon. Thanks for the replies (also, @kuaashish)!

**Comment by joezoug** [comment]
Np, happy to help! I will close the issue now.

**Comment by joezoug** [comment]
Np, happy to help! I will close the issue now.
