### ISSUE TITLE
How to make separate gestures with both hands at the same time?

### ISSUE THREAD

**Issue by fff128170** [google/mediapipe#4909]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Task name (e.g. Image classification, Gesture recognition etc.)

Gesture recognition

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

When both of my hands appear in the frame at the same time, only gestures made with my right hand are recognized, unless my right hand disappears, then gestures made with my left hand are recognized.

### Describe the expected behaviour

Detecting gestures on both hands simultaneously is demonstrated in the following link: https://mediapipe-studio.webapps.google.com/studio/demo/gesture_recognizer

### Standalone code/steps you may have used to try to get what you need

```shell
The code I am running is this examples: https://github.com/googlesamples/mediapipe/blob/main/examples/gesture_recognizer/raspberry_pi/recognize.py
```

**Comment by kuaashish** [comment]
Hi @fff128170,

Thank you for bringing the issue to our attention. It appears there is a bug in our Python platform. We have submitted a [pull request](https://github.com/googlesamples/mediapipe/pull/274) for the fix and are currently awaiting approval for the merge.

**Comment by kuaashish** [comment]
Hi @fff128170,

[recognize.py](https://github.com/googlesamples/mediapipe/blob/main/examples/gesture_recognizer/raspberry_pi/recognize.py) has been updated/merged with the necessary changes, and it is expected to function as described in the provided description. Kindly verify the current status and inform us accordingly.

Thank you

**Comment by OBeeNya** [comment]
Hello,

The issue remains, it's still not possible to recognize both hand gestures at the same time.

Despite the merge of the following PR: https://github.com/google-ai-edge/mediapipe-samples/pull/274
