### ISSUE TITLE
Extracting crop coordinates rather than encoding output in AutoFlip

### ISSUE THREAD

**Issue by thesofakillers** [google/mediapipe#491]
Hi, I was hoping to re-utilise/re-adapt AutoFlip so to obtain coordinates of the resulting crops, rather than the actual cropped video output. I've had a look at #454 but it seems like the solution is specific to Android and hand tracking where different calculators are used. 

By inspecting the AutoFlip [graph](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt) on the [mediapipe visualizer](https://viz.mediapipe.dev/) (amazing tool btw, thank you for this), what this basically means is that I'm not interested in running OpenCvVideoEncoderCalculator and am instead interested in the output from SceneCroppingCalculator. This however simply outputs a set of frames, a list of image matrices (vector<cv::Mat>), which are meant for encoding by OpenCV if I understand correctly. 
![autoflip](https://github.com/google/mediapipe/raw/master/mediapipe/docs/images/autoflip_graph.png)

I was hoping to go one step earlier, i.e., simply get the actual coordinates of the crop regions. What I'm ideally hoping to output is a file listing the coordinates of the crop frames and their relevant timestamps, something like [[x, y, w, h, timestamp]].

I'm having trouble determining exactly how to do this. I'm unsure where exactly the transformation from crop coordinates to cropped images (i.e. the cropping) occurs. I believe it occurs [here](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/examples/desktop/autoflip/calculators/scene_cropping_calculator.cc#L410-L414). 

I imagine this means the data I'm actually interested in is contained in the [SceneKeyFrameCropSummary scene_summary](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/examples/desktop/autoflip/calculators/scene_cropping_calculator.cc#L401), but since this [does not contain FocusPoint information](https://github.com/google/mediapipe/blob/ae6be10afe59a6a99d8a68007784706ac98720dd/mediapipe/examples/desktop/autoflip/quality/cropping.proto#L96-L142), this will leave me with the jittery output if I'm not mistaken. 

It seems therefore that I need to edit/replace [scene_cropper.cc](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/quality/scene_cropper.cc) with something that takes into account FocusPointFrames too.

It also seems like there are additional operations performed on the cv::Mat images before returning such as an affine retarget. 

In general, it is unclear to me how to readapt AutoFlip for my needs described above.

Is what I'm seeking feasible? Perhaps a user with more experience in mediapipe can shine a light

Thank you very much, apologies if this sort of question is inappropriate for the issues page

**Comment by thesofakillers** [comment]
is it the `all_xforms` vector returned by `PolynomialRegressionPathSolver::ComputeCameraPath` that I am essentially after? From the docstring in [polynomial_regression_solver.h](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/quality/polynomial_regression_path_solver.h) : 
> The returned |all_xforms| hold the camera location at each timestamp corresponding to each input frame.

width and height I realize is trivial. So in fact what I am after is [[x, y, timestamp]] which this seems to provide. 

That being said I notice in [scene_cropper.cc](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/quality/scene_cropper.cc) that as mentioned above, it seems like there are further operations performed on the image frames themselves, particularly [here](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/examples/desktop/autoflip/quality/scene_cropper.cc#L72-L81) with `AffineRetarget`. I'm unsure what is happening with `AffineRetarget`, is this simply preparing the frames for OpenCV video encoding in the next calculator or is it part of the AutoFlip cropping process?

Thank you in advance

**Comment by thesofakillers** [comment]
The `|all_xforms|` vector, particularly elements (0,2) and (1,2) corresponding to the (x, y) position of the camera was indeed what I was after. I'm still not sure what `AffineRetarget` does afterwards, but I guess it is not relevant to what I'm seeking. 
Anyone interested in my (shoddy) readaptation, come have a look at my [fork](https://github.com/thesofakillers/mediapipe) and/or feel free to ask

**Comment by fedeveloperi81** [comment]
Hello, the thread is already very old, but may be you had found any solution how to extract that info because we are trying to build semi-automatic cropping with UI. Or may be you have found any other solution. Will be very pleased if you answer.
Regards.
