### ISSUE TITLE
mp.ImageFormat or ImageFormat?

### ISSUE THREAD

**Issue by mart1n3rd** [google/mediapipe#4911]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Windows 10

### Task name (e.g. Image classification, Gesture recognition etc.)

Face Landmarks

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

I'm using mp.ImageFormat while creating an mp.Image object but I have an error in the output

### Describe the expected behaviour

To create an mp.Image using mp.ImageFormat as a parameter. 

### Standalone code/steps you may have used to try to get what you need

```shell
import cv2
import mediapipe as mp
cv_mat = cv2.imread(input_file)[:, :, ::-1]
rgb_frame = mp.Image(image_format=mp.ImageFormat.SRGB, data=cv_mat)


and this is my output:

Traceback (most recent call last):
  File "c:\Users\marti\Downloads\tesi_mg\mediapipe2.py", line 103, in <module>
    image = mp.Image(image_format=mp.ImageFormat.SRGB, data=cv_mat)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. mediapipe.python._framework_bindings.image.Image(image_format: mediapipe::ImageFormat_Format, data: numpy.ndarray[numpy.uint8])
    2. mediapipe.python._framework_bindings.image.Image(image_format: mediapipe::ImageFormat_Format, data: numpy.ndarray[numpy.uint16])
    3. mediapipe.python._framework_bindings.image.Image(image_format: mediapipe::ImageFormat_Format, data: numpy.ndarray[numpy.float32])

Invoked with: kwargs: image_format=<ImageFormat.SRGB: 1>, data=array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [ 13,   9,  15],
        ...,
        [ 71,  92, 118],
        [ 63,  87, 118],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [ 81, 108, 144],
        ...,
        [ 71, 102, 138],
        [ 71, 102, 138],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [ 82, 108, 145],
        ...,
        [ 71, 102, 138],
        [ 71, 102, 138],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]], dtype=uint8)


Do I have to use ImageFormat instead of mp.ImageFormat? 
https://developers.google.com/mediapipe/api/solutions/python/mp/Image
From the documentation, I can't understand.
Have I imported the wrong class?
```

**Comment by kuaashish** [comment]
Hi @mart1n3rd,

Thank you for bringing this to our attention. It appears there is a documentation error in the provided example regarding the creation of frames. The examples lack completeness and contain typographical errors, such as in the line:

`rgb_frame = mp.Image(image_format=ImageFormat.SRGB, data=cv_mat)`

The correct syntax should be:

`rgb_frame = mp.Image(image_format=mp.ImageFormat.SRGB, data=cv_mat)`

Similarly, in the case of a gray frame, change:

`gray_frame = mp.Image(image_format=mp.ImageFormat.GRAY8)`

And ensure that the transition from "GRAY" to "GRAY8" is made.

It's important to note that executing the example as-is will result in an error. To address this, we recommend using the following modified example, which has been identified by the community as a workaround:

```
import mediapipe as mp
import cv2
import numpy as np
cv_mat = cv2.imread('/content/sample_data/test.jpg')[:, :, ::-1].copy()
rgb_frame = mp.Image(image_format=mp.ImageFormat.SRGB, data=cv_mat)
gray_frame = mp.Image(
    image_format=mp.ImageFormat.GRAY8,
    data=cv2.cvtColor(cv_mat, cv2.COLOR_RGB2GRAY))

from PIL import Image
pil_img = Image.new('RGB', (60, 30), color = 'red')
image = mp.Image(
    image_format=mp.ImageFormat.SRGB, data=np.asarray(pil_img))
```

For a clearer understanding, please refer to the [thread](https://stackoverflow.com/questions/76280685/mp-image-call-with-sliced-numpy-array-raises-typeerror-init-incompatib). Simultaneously, we have escalated the issue internally and anticipate a prompt resolution.


Thank you

**Comment by mart1n3rd** [comment]
I tried using the updated version of the code in my program like this: 

` image = mp.Image(image_format=mp.ImageFormat.SRGB, data=cv_mat)[:, :, ::-1].copy()`

but I get the following error:

  File "c:\Users\marti\Downloads\tesi_mg\mediapipe2.py", line 142, in captureFaceLMS
    image = mp.Image(image_format=mp.ImageFormat.SRGB, data=cv_mat)[:, :, ::-1].copy()
TypeError: __getitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: mediapipe.python._framework_bindings.image.Image, arg0: List[int]) -> object

Invoked with: <mediapipe.python._framework_bindings.image.Image object at 0x000001560F176390>, (slice(None, None, None), slice(None, None, None), slice(None, None, -1))


But...if I write the same line of code like this:

`image = mp.Image(image_format=mp.ImageFormat.SRGB, data=cv_mat)`

the code works. I don't know if the image does have the correct image format.

**Comment by kuaashish** [comment]
Hi @mart1n3rd,

I will review the configuration you are using on my end and provide you with a workaround shortly. Thank you

**Comment by kuaashish** [comment]
Hi @mart1n3rd,

I managed to make the workaround work in Colab. I've shared it as a [Gist](https://colab.sandbox.google.com/gist/kuaashish/bcf5275a7260e320e814197c9c06b0ba/untitled73.ipynb) for your reference, using the latest MediaPipe version (0.10.7) and Python 3.10.12. Right now, I do not have a Windows 10 machine, so I am having trouble figuring out the issue on Windows 10.

**Comment by mart1n3rd** [comment]
@kuaashish I'm sorry to be a bother but the Colab solution you provided, it only works with a single image for me. When I try and loop those instructions with a for loop to process a list of paths, it gives me the error I reported on my last message.
