### ISSUE TITLE
Ability to save best checkpoint

### ISSUE THREAD

**Issue by kaundinya5** [google/mediapipe#4912]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Ubuntu

### Python Version

3.10

### Task name (e.g. Image classification, Gesture recognition etc.)

Object detection

### Describe the actual behavior

Currently object_detector.ObjectDetector.create() has no way to store the best performing checkpoint. This sometimes means that the last epoch isn't actually the most accurate model.

### Describe the expected behaviour

I dug into the classifier.py code a bit and found that I can use a keras callback to save the best performing one. 
```shell
best_ckpt_callback = tf.keras.callbacks.ModelCheckpoint(
            filepath=os.path.join(checkpoint_path, "keras_model"), monitor="total_loss", save_best_only=True, verbose=1
        )
```
Is there some way to use this saved model while converting the model to tflite instead of the last ckpt?

### Standalone code/steps you may have used to try to get what you need

```shell
model = object_detector.ObjectDetector.create(train_data=train_data, validation_data=validation_data, options=options)
```

**Comment by joezoug** [comment]
Hi @kaundinya5,

Yes you can save a checkpoint of the best model using the callback snippet you provided. You can export this model to tflite using a bit of hacky code with the model maker codebase. After training the model using `model = ObjectDetector.create(...)`, you can then load the best saved model into the `_model` instance variable with `model._model = tf.keras.load_model(<path_to_best_saved_model>, compile=False)` and then try exporting.
