### ISSUE TITLE
Is it possible to output (x,y) without the z coordinate

### ISSUE THREAD

**Issue by fchen09** [google/mediapipe#4913]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

iOS, Android

### MediaPipe version

0.10.7

### Bazel version

6.4.0

### Solution

Pose

### Programming Language and version

swift

### Describe the actual behavior

I can output world coordinate(x,y,z) correctly

### Describe the expected behaviour

I don't need z coordinate. If I can get rid of z and save some coputing power, that will help.

**Comment by kuaashish** [comment]
Hi @fchen09,

Certainly. Could you elaborate on the platform to which you are referring—whether it be Python, iOS, Android, JavaScript, or C++? Additionally, if you can pinpoint the specific example from the documentation, it would be helpful for us to better understand the issue. 

Thank you!

**Comment by fchen09** [comment]
I made an iOS framework. and I have written a func to obtain x, y, z, visibility, and presence

        const auto& landmarks = packet.Get<::mediapipe::LandmarkList>();
        NSMutableArray<Landmark *> *result = [NSMutableArray array];
        for (int i = 0; i < landmarks.landmark_size(); ++i) {
            Landmark *landmark = [[Landmark alloc] initWithX:landmarks.landmark(i).x()
                                                           y:landmarks.landmark(i).y()
                                                           z:landmarks.landmark(i).z()
                                                  visibility:landmarks.landmark(i).visibility()
                                                  presence:landmarks.landmark(i).presence()];
            [result addObject:landmark];
        }
I think it just outputs the results explicitly. However, I think the backend still calculated the z, right?

**Comment by schmidt-sebastian** [comment]
We currently do not have this option. If there is significant demand, we can revisit. We would need some indication that this does improve performance though.

Closing this for now as I don't anticipate much demand but we can re-open if needed.
