### ISSUE TITLE
Finding the transformation matrix between two canocical face models

### ISSUE THREAD

**Issue by Kojon74** [google/mediapipe#4914]
I'm working on a problem where I need to map a point on a face onto another face: as in the image below.

<img width="522" alt="Screenshot 2023-10-25 at 11 48 02 PM" src="https://github.com/google/mediapipe/assets/52554666/c01e5406-d6c8-4705-8634-2c25745dc6df">

Having gone through the mediapipe library it seems like there are some tools that I can use to achieve this but I can't quite put all the pieces together.

I've gone through the [Facial Landmark Detection Guide](https://developers.google.com/mediapipe/solutions/vision/face_landmarker/index#models) which was quite promising, and gave me a facial transformation matrix, but I'm not sure how I can utilize this to perform the mapping. I would greatly appreciate any advice even just to nudge me in the right direction.

**Comment by kuaashish** [comment]
Hi @Kojon74,
