### ISSUE TITLE
Make android solutions(Image segmentation) buildable with 'minifyEnabled true' build option. 

### ISSUE THREAD

**Issue by Quangninh-io** [google/mediapipe#4915]
### OS Platform and Distribution

Android 13

### Programming Language and version

java 17

### MediaPipe version

:0.20230731

### Android AAR (if android)

None

### Describe the problem

A bug happened!

### Complete Logs

```shell
I use MediaPipe Image Segmenter followed the guide . It worked perfectly. However, when I changed minifyEnabled configuration to true in build.gradle file, it can initial valuabe   
val imageSegmenter = ImageSegmenter.createFromOptions(context, options)
I use the last mediapipe gradle version :com.google.mediapipe:tasks-vision:0.20230731
I tried to use the proguard rule in my app suggested 
" -keep class com.google.mediapipe.solutioncore.** {*;}
-keep class com.google.protobuf.** {*;}
-keepclassmembers class * extends com.google.protobuf.GeneratedMessageLite {
*;
}"
but not works.
```

**Comment by kuaashish** [comment]
Hi @Quangninh-io,

Could you share all the details about the issue? This includes the full code, any documentation you're following, the versions of Android Studio and Android SDK you're using, and if possible, the complete error logs. Having this information would greatly help us in reproducing and addressing the issue on our end.

Thank you
