### ISSUE TITLE
Pose/Holistic World Landmarks not accurate

### ISSUE THREAD

**Issue by francescoyou97** [google/mediapipe#4917]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 11

### MediaPipe version

0.8.11 - 0.10.7

### Solution

Pose/Holistic

### Programming Language and version

Python

### Describe the actual behavior

I tested several versions of Mediapipe Pose/Holistic, going from 0.8.11 up to 0.10.7. I always encounter the same problem: pose_world_landmarks are not accurate. I found errors on the coordinates of the landmarks (especially on the x coordinate) and in their use. For example, with the legs spread in a mirror image, I found a difference of even more than 10 cm between the landmarks of the knees and those of the ankles. For example, if the left and right knee are mirror-image, I would expect to observe a similar absolute value of x, but I ended up with values like +0.21, -0.09.  Another aspect is that when trying to determine the length of a part of the body, I found that for taller people, I obtained a leg length that was smaller or at least similar to that of significantly shorter people. Which is not possible or in any case not real.  Attached is a simple piece of code showing the landmarks and distances considered.  I wanted to understand if these errors in accuracy were known, or maybe there is something wrong with my code.

### Describe the expected behaviour

More accurate world coordinates and more precise distances.

### Standalone code/steps you may have used to try to get what you need

```shell
import cv2
import mediapipe as mp
import numpy as np
import math

from mediapipe.python.solutions.pose import PoseLandmark as mp_PoseLandmark

mp_drawing = mp.solutions.drawing_utils
mp_holistic = mp.solutions.holistic

holistic = mp_holistic.Holistic(model_complexity=2, min_detection_confidence=0.7, min_tracking_confidence=0.7, enable_segmentation=True, static_image_mode=True)

cap = cv2.VideoCapture(0)

while cap.isOpened():
    
    ret, frame = cap.read()
    
    if not ret:
        continue

    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    
    frame.flags.writeable = False
    results = holistic.process(frame)
    frame.flags.writeable = True

    try:        
        pose_landmarks_world = results.pose_world_landmarks.landmark
        left_keypoints = [mp_PoseLandmark.LEFT_HIP, mp_PoseLandmark.LEFT_KNEE, mp_PoseLandmark.LEFT_ANKLE]
        right_keypoints = [mp_PoseLandmark.RIGHT_HIP, mp_PoseLandmark.RIGHT_KNEE,mp_PoseLandmark.RIGHT_ANKLE]

        print("Left")
        for keypoint in left_keypoints:
            point = pose_landmarks_world[keypoint.value]
            print(f"{keypoint}: {point.x}, {point.y},{point.z}")

        hip = pose_landmarks_world[mp_PoseLandmark.LEFT_HIP]
        knee = pose_landmarks_world[mp_PoseLandmark.LEFT_KNEE]
        ankle = pose_landmarks_world[mp_PoseLandmark.LEFT_ANKLE]

        hip_knee_left_distance = np.linalg.norm(hip - knee)
        knee_ankle_left_distance = np.linalg.norm(knee - ankle)
        hip_ankle_left_distance = hip_knee_left_distance + knee_ankle_left_distance
        print(f"hip_ankle_left_distance: {hip_ankle_left_distance}")
        
        print("")

        print("Right")
        for keypoint in right_keypoints:
            point = pose_landmarks_world[keypoint.value]
            print(f"{keypoint}: {point.x}, {point.y},{point.z}")

        hip = pose_landmarks_world[mp_PoseLandmark.RIGHT_HIP]
        knee = pose_landmarks_world[mp_PoseLandmark.RIGHT_KNEE]
        ankle = pose_landmarks_world[mp_PoseLandmark.RIGHT_ANKLE]

        hip_knee_right_distance = np.linalg.norm(hip - knee)
        knee_ankle_right_distance = np.linalg.norm(knee - ankle)
        hip_ankle_right_distance = hip_knee_left_distance + knee_ankle_left_distance
        print(f"hip_ankle_right_distance: {hip_ankle_right_distance}")
        
        print("\n")

    except:
        pass

    if cv2.waitKey(1) & 0xFF == 27:
        break

cap.release()
cv2.destroyAllWindows()
```

### Other info / Complete Logs

```shell
This is a log. The first number is the Landmark index. Here I'm frontal to the camera, with legs spread in a mirror-like manner. You can see the discrepancy on the x's in pairs 25-26 and 27-28

23: 0.09410709142684937, -0.003220029640942812,0.02622263878583908
25: 0.19516153633594513, 0.3960910737514496,0.02886791341006756
27: 0.2904597818851471, 0.7279267311096191,0.23155030608177185

24: -0.09195618331432343, -0.0001346813514828682,-0.023451725021004677
26: -0.12523218989372253, 0.33928728103637695,0.026871608570218086
28: -0.22931420803070068, 0.7244243621826172,0.21128584444522858
```

**Comment by fchen09** [comment]
I noticed one knee was taller than the other. Also, when a person facing right and left showed different tracking results. I guess the model does not involve some fundamental symmetries, such as left-right symmetry.

**Comment by francescoyou97** [comment]
Is there a way to improve the solution? For example the image resolution or something else?

**Comment by endink** [comment]
We wait new Holistic solution so long ！

This cause multiple applications can't migrate to the new task API.
