### ISSUE TITLE
tensorboard can support when mediapipe_model_maker train model?

### ISSUE THREAD

**Issue by lonngxiang** [google/mediapipe#4923]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

windows

### Task name (e.g. Image classification, Gesture recognition etc.)

.Image classification

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

tensorboard can support when mediapipe_model_maker train model?

### Describe the expected behaviour

tensorboard can support when mediapipe_model_maker train model?tensorboard can support when mediapipe_model_maker train model?

### Standalone code/steps you may have used to try to get what you need

```shell
tensorboard can support when mediapipe_model_maker train model?
```

**Comment by kuaashish** [comment]
Hi @lonngxiang,

Considering the [issue](https://github.com/google/mediapipe/issues/4880) outlined by our team, you can utilize [TensorBoard](https://www.tensorflow.org/tensorboard) to visualize various aspects of machine learning experimentation. This includes tracking and visualizing metrics like loss and accuracy, visualizing the model graph, and displaying images, text, and audio data. You can find information on setting up TensorBoard with MediaPipe Model Maker in the same thread as [described below](https://github.com/google/mediapipe/issues/4880#issuecomment-1767165400):

> Unfortunately the callback for object detection was not implemented yet - so you may need to hack together something by calling [ObjectDetector.__init__](https://github.com/google/mediapipe/blob/master/mediapipe/model_maker/python/vision/object_detector/object_detector.py#L40) separately instead of using the [ObjectDetector.create](https://github.com/google/mediapipe/blob/master/mediapipe/model_maker/python/vision/object_detector/object_detector.py#L64) method, and then adding the tensorboard callback to model._callbacks after you've initialized the object detector model. After adding the callback, you can call _create_and_train_model just like how it is done in ObjectDetector.create.
> 
> You can see how the tensorboard logging is set in ImageClassifier: https://github.com/google/mediapipe/blob/master/mediapipe/model_maker/python/vision/image_classifier/image_classifier.py#L59. There is a util function called [get_default_callbacks](https://github.com/google/mediapipe/blob/master/mediapipe/model_maker/python/core/utils/model_util.py#L36) which will get you a tensorboard logging and model checkpointing callback.
> 
> Alternatively, the metrics should be printed every epoch so you can also try to capture the logs and use regex to capture the metric values by epoch.

For a clearer understanding, we kindly ask you to review the same thread. 


Thank you
