### ISSUE TITLE
overlap of a region of interest with hand to define a class

### ISSUE THREAD

**Issue by Shahram-73** [google/mediapipe#4926]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

desktop

### Task name (e.g. Image classification, Gesture recognition etc.)

gesture recognition

### Programming Language and version (e.g. C++, Python, Java)

python

### Describe the actual behavior

nothing

### Describe the expected behaviour

gesture recognition on specific roi

### Standalone code/steps you may have used to try to get what you need

```shell
Hello everyone, 
I want to have a model which detects the hand's gesture in 4 different regions of interest that I have drawn on the first frame(boxes or rois are fixed for the whole stream because camera and the assembly line is fixed).

does anyone have any idea or know any source for this?
the only source that I have found is the following link:
https://techtutorialsx.com/2021/04/24/python-mediapipe-finger-roi/
```

**Comment by schmidt-sebastian** [comment]
Are you able to use `IMAGE` mode and pass the same Image multiple times to the Task (with different region of interest)? If I understand your use case correctly, that should work. Note that you can't use LiveStream or Video mode since the task assumes that you are passing frames in sqeuence.
