### ISSUE TITLE
autoflip Failed to run the graph: CalculatorGraph::Run()

### ISSUE THREAD

**Issue by myselfdesai** [google/mediapipe#493]
Test Environment

- setup using docker file
- OpenCV : Run setup_opencv.sh
- bazel 1.1.0
- Hello World desktop example works ok.
This below run successfully
``bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/autoflip:run_autoflip

when I try to run 
`root@0708bb098546:/mediapipe# GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip   --calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt   --input_side_packets=input_video_path=/mediapipe/examples/desktop/object_detection/test_video.mp4,output_video_path=/output_video/data.mp4,aspect_ratio=1:1
`

gives me error

`node {
  calculator: "OpenCvVideoEncoderCalculator"
  input_stream: "VIDEO:cropped_frames"
  input_stream: "VIDEO_PRESTREAM:output_frames_video_header"
  input_side_packet: "OUTPUT_FILE_PATH:output_video_path"
  input_side_packet: "AUDIO_FILE_PATH:audio_path"
  options: {
    [mediapipe.OpenCvVideoEncoderCalculatorOptions.ext]: {
      codec: "avc1"
      video_format: "mp4"
    }
  }
}
I0304 17:27:12.846961 24948 simple_run_graph_main.cc:121] Initialize the calculator graph.
I0304 17:27:12.847947 24948 simple_run_graph_main.cc:134] Start running the calculator graph.
E0304 17:27:12.851966 24948 simple_run_graph_main.cc:146] Failed to run the graph: CalculatorGraph::Run() failed in Run: 
Calculator::Open() for node "[OpenCvVideoDecoderCalculator, OpenCvVideoDecoderCalculator with output stream: video_raw]" failed: ; Fail to open video file at /mediapipe/examples/desktop/object_detection/test_video.mp4
`

**Comment by thesofakillers** [comment]
I'm not a maintainer, but check the directory where you're running the script from. You need to specify the *absolute* path to the input video file, so you may need to include some `../`in the input video path.
