### ISSUE TITLE
Example page giving error @ https://mediapipe-studio.webapps.google.com/studio/demo/face_landmarker

### ISSUE THREAD

**Issue by pogestudio** [google/mediapipe#4932]
https://mediapipe-studio.webapps.google.com/studio/demo/face_landmarker

Example not working. Showing red error at top
<img width="1800" alt="Screenshot 2023-11-04 at 16 17 52" src="https://github.com/google/mediapipe/assets/2547586/e2c14418-b44f-4e42-80c0-81316cdb3458">

Console output:
<img width="1670" alt="Screenshot 2023-11-04 at 16 16 18" src="https://github.com/google/mediapipe/assets/2547586/4ac674c6-9da5-423b-89f6-d6d23aa9c5c9">

Mac, Monterey, 12.6.5
16 inch 2019
2.4 ghz i9 intel
32gb ddr4
AMD Radeon Pro 5500M
Chrome, Version 118.0.5993.117 (Official Build) (x86_64)

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

I am able to replicate the issue on my end using the latest Chrome version 119.0.6045.105 (Official Build) (x86_64) on an Intel macOS i5. It appears that the face landmarker demo is not functioning correctly and is generating an error identical to the one shown by @pogestudio. and attached screenshot as below:

<img width="1788" alt="Screenshot 2023-11-06 at 2 45 24 PM" src="https://github.com/google/mediapipe/assets/98159216/bc7d1306-510e-4d79-8ee8-98c5772a1297">

Could you please have a look into this issue. 


Thank you

**Comment by khanhlvg** [comment]
Thanks for the report! We've fixed the issue.
