### ISSUE TITLE
detection_confidence not taking flouting point number in hand tracking module  

### ISSUE THREAD

**Issue by mohammedpithapur** [google/mediapipe#4933]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

yes

### OS Platform and Distribution

windows 10

### Programming Language and version

python

### Solution

taking flouting point number

### Describe the actual behavior

when inputted flouting point number like 0.75 it throws error 

### Describe the expected behaviour

it dosnt throw error

### Standalone code/steps you may have used to try to get what you need

```shell
class handdetector():
    def __init__(self, mode= False, maxhands= 2,min_detection_confidence=0.5,min_tracking_confidence=0.5):
        self.mode= mode
        self.maxhands= maxhands
        self.detectioncon = min_detection_confidence
        self.trackingcon = min_tracking_confidence

        self.nphands = mp.solutions.hands
        self.hands = self.nphands.Hands(self.mode, self.maxhands,self.detectioncon,self.trackingcon)
        self.mpDraw = mp.solutions.drawing_utils
```

**Comment by kuaashish** [comment]
Hi @mohammedpithapur,

From the code snippet you provided, it appears you are using the legacy hands solution. Please note that this solution has been upgraded and is now integrated into the Hand Landmarker Task API, as explained in the [documentation](https://developers.google.com/mediapipe/solutions/guide#legacy)(We have discontinued support for upgraded legacy solutions, and we are no longer maintaining them). 

The upgraded Task API's are designed to offer better performance compared to the legacy solutions and are easier to adopt for your use case. We encourage you to explore our new Hand Task API following the guidelines provided [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker). You can find the Python guide [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/python), along with a [Python notebook example](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/hand_landmarker/python/hand_landmarker.ipynb). Please let us know if you observe similar behaviour  in the new Task API.

Thank you
