### ISSUE TITLE
To continue training from previously trained model

### ISSUE THREAD

**Issue by yong2khoo-lm** [google/mediapipe#4937]
### MediaPipe Solution (you are using)

MobileNet-V2

### Programming language

Python

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

As-is, let say i have a model that already traind on 100 images. Next day, if i have 100 more, i need to retrain all over again. if the model is able train from the previously trained model, then it would reduce the loads of hardware.

### Please specify the use cases for this feature

If I have 5000 images, i can train it batch by batch, so that my hardware can afford the loads. Otherwise, 5000 images in one training would explode the hardware.

**Comment by kuaashish** [comment]
Hi @yong2khoo-lm,

Thank you for suggesting an expansion of the MediaPipe model maker's functionality. We have forwarded this matter internally for discussion, and the team will prioritise the request. However, at this time, we cannot commit to a specific timeline for its implementation.

Thank you

**Comment by joezoug** [comment]
@yong2khoo-lm, unfortunately this feature is not currently supported through our APIs.

You may be able to write some custom code to do this. The current implementation of the Object Detector model has [save_checkpoint](https://github.com/google/mediapipe/blob/master/mediapipe/model_maker/python/vision/object_detector/model.py#L119) and [load_checkpoint](https://github.com/google/mediapipe/blob/master/mediapipe/model_maker/python/vision/object_detector/model.py#L132) methods.
