### ISSUE TITLE
 Import some github third party libraries for enhancement features [Failure]

### ISSUE THREAD

**Issue by momo1986** [google/mediapipe#494]
Hello, I want to do some enhacement features for USB camera.
However, I met some problems.

Let me clarify my dilemma.

I tried to add thirdy_paty/BUILD with new configuration:

```
android_library(
   name = "jitpack",
   exports = [
       "@maven//:com_github_jitpack_maven-simple",
   ],
)
android_library(
    name = "com_serenegiant_common",
    exports = [
        "@maven//:com_serenegiant_common",
    ],
)
android_library(
    name = "com_serenegiant_uvccamera",
    exports = [
        "@maven//:com_serenegiant_uvccamera_libuvccamera",
    ],
)
```
It refers to these three maven repositories:
https://mvnrepository.com/artifact/com.github.jitpack/maven-simple
https://mvnrepository.com/artifact/com.serenegiant/common
https://mvnrepository.com/artifact/com.serenegiant.uvccamera/libuvccamera

When I fetch the library with build of cpu-face-detection:
`bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu`

It reports the error:

> ERROR: /Users/junyan/find_android_project/mediapipe-master/third_party/BUILD:140:1: no such target '@maven//:com_serenegiant_common': target 'com_serenegiant_common' not declared in package '' defined by /private/var/tmp/_bazel_junyan/d0562ae4205a819f08c6b310db2d9181/external/maven/BUILD and referenced by '//third_party:com_serenegiant_common'
> INFO: Call stack for the definition of repository 'android_opencv' which is a http_archive (rule definition at /private/var/tmp/_bazel_junyan/d0562ae4205a819f08c6b310db2d9181/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
> 
> /Users/junyan/find_android_project/mediapipe-master/WORKSPACE:185:1
> ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu:facedetectioncpu' failed; build aborted: Analysis failed
> INFO: Elapsed time: 1257.395s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (132 packages loaded, 11600 target
> s configured)

My question is:

To use these three maven repositories, is there any error I should fix in thirdy_party/BUILD?
What other files should I modifiy under the directory of mediapipe to support these three external Android libraries?
Looks like that there is no problem to fetch the library of jitpack until now.

When loading these third-paty tools smoothly under the project of mediapipe, I think there is no problem for external USB device support.

Thanks & Regards!
^_^

**Comment by jiuqiant** [comment]
You need to modify [the MediaPipe WORKSPACE file](https://github.com/google/mediapipe/blob/master/WORKSPACE#L236) first -- either modify `maven_install` or add `maven_server` and `maven_jar` for your third party jar libraries. See the Bazel documentation: https://docs.bazel.build/versions/1.1.0/migrate-maven.html#guava-project-example-external-dependencies

**Comment by jiuqiant** [comment]
Seems like this is not an issue anymore. But, there is a follow-up issue: https://github.com/google/mediapipe/issues/504#issue-577507655
