### ISSUE TITLE
Unable to install mediapipe-model-maker==0.2.1.3 on iMac 

### ISSUE THREAD

**Issue by AnyLifeZLB** [google/mediapipe#4945]
**OS Platform and Distribution**
macos Ventura 13.3.1 (a) (22E772610a

**Compiler vers**ion
pip --version 23.3.1

**Programming Language and version**
python3 --version 3.9.0

**Installed using virtualenv? pip? Conda?(if python)**
virtualenv

**MediaPipe version**
ERROR: No matching distribution found for mediapipe>=0.10.0

**Bazel version**
Build label: 6.4.0-homebrew

**Describe the problem**
Can not install 0.10.0 mediaPipe
No matching distribution found for mediapipe>=0.10.0

**Complete Logs**
python -m pip install mediapipe-model-maker==0.2.1.3
Collecting mediapipe-model-maker==0.2.1.3
  Using cached mediapipe_model_maker-0.2.1.3-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: absl-py in ./venv/lib/python3.9/site-packages (from mediapipe-model-maker==0.2.1.3) (1.4.0)
INFO: pip is looking at multiple versions of mediapipe-model-maker to determine which version is compatible with other requirements. This could take a while.
**_ERROR: Could not find a version that satisfies the requirement mediapipe>=0.10.0 (from mediapipe-model-maker) (from versions: 0.8.4.2, 0.8.5, 0.8.6.2, 0.8.7.1, 0.8.7.2, 0.8.7.3, 0.8.8.1, 0.8.9.1, 0.8.10, 0.8.10.1, 0.8.11, 0.9.0, 0.9.0.1, 0.9.1.0)
ERROR: No matching distribution found for mediapipe>=0.10.0_**

**Comment by AnyLifeZLB** [comment]
![image](https://github.com/google/mediapipe/assets/15169396/3c7996e5-f93a-43d6-8cc5-bb4bd7f6fbb4)
Mac os version  is newest ,thank you

**Comment by kuaashish** [comment]
Hi @AnyLifeZLB,

Could you please try out this below command and let us know if this work for you: 


`pip3 install mediapipe-model-maker`


Thank you

**Comment by AnyLifeZLB** [comment]
Default  installed mediapipe-model-maker-0.1.0.2, Still can not install the newest version 0.2.1.3  @kuaashish

**Comment by AnyLifeZLB** [comment]
![image](https://github.com/google/mediapipe/assets/15169396/e57b6280-7724-41db-832e-6a03227dd1f1)

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

Could you please have look into this issue? Thank you

**Comment by schmidt-sebastian** [comment]
@joezoug

**Comment by AnyLifeZLB** [comment]
Our Team want use MediaPipe customize Object detection model run on Android App . 
Unfortunately, neither of our 2 iMacs can install the latest version of MediaPipe

**Comment by FaceAI** [comment]
with the same problem 


pip3 install mediapipe-model-maker==0.2.1.3

Collecting mediapipe-model-maker==0.2.1.3
  Using cached mediapipe_model_maker-0.2.1.3-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: absl-py in ./venv/lib/python3.9/site-packages (from mediapipe-model-maker==0.2.1.3) (1.4.0)
INFO: pip is looking at multiple versions of mediapipe-model-maker to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement mediapipe>=0.10.0 (from mediapipe-model-maker) (from versions: 0.8.6.2, 0.8.7.1, 0.8.7.2, 0.8.7.3, 0.8.8.1, 0.8.9.1, 0.8.10, 0.8.10.1, 0.8.11, 0.9.0, 0.9.0.1, 0.9.1.0)
ERROR: No matching distribution found for mediapipe>=0.10.0

**Comment by FaceAI** [comment]
I've solved it.  https://github.com/AnyLifeZLB/FaceVerificationSDK/blob/main/install_newest_mediapipe_on_macos.md


SYSTEM_VERSION_COMPAT ERROR ！！

**Comment by AnyLifeZLB** [comment]
mosaic
