### ISSUE TITLE
Anchorfree example pipeline

### ISSUE THREAD

**Issue by bhack** [google/mediapipe#495]
Can you add any anchor-free bbox+landmarks/keypoints or segmentation pipeline example for Coral and/or Android?
See also https://github.com/tensorflow/hub/issues/424

**Comment by bhack** [comment]
I've also added SMOKE in the TF.hub ticket as you have added recently 3d bbox example in this repo. 
Another anchor-free Centernet derivated multitask demo (human detection, face landmarks, poise joints) is at https://github.com/tensorboy/centerpose

**Comment by bhack** [comment]
An interesting example to simplify the Face detection example, but probably also pose or hand, pipelines could be Kpnet https://arxiv.org/abs/2003.07543.

**Comment by fanzhanggoogle** [comment]
Hi, thank you for the interests. We currently don't have plan to release anchor free models/pipelines. But we'll definitely keep that in mind since it'll indeed reduce a lot of the post-processing hassle in anchor based detectors.

**Comment by bhack** [comment]
Exactly.
If you want upvote https://github.com/tensorflow/tensorflow/issues/38572
