### ISSUE TITLE
Image Text Recognition

### ISSUE THREAD

**Issue by Juanryhn** [google/mediapipe#4950]
### MediaPipe Solution (you are using)

None

### Programming language

Javascript

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

I need feature that can analyze text in an images

### Who will benefit with this feature?

People that need to detect text and object in an images

### Please specify the use cases for this feature

User want to detect text in an images or video for simplify the process input the special character of numbers and alphabet

**Comment by schmidt-sebastian** [comment]
This is currently not one of our offerings. Will let you know if this changes.
