### ISSUE TITLE
Gpu support on mediapipe 0.10.8

### ISSUE THREAD

**Issue by RiccardoMaistri** [google/mediapipe#4951]
I saw that was added support for GPU con mediapipe on Linux, how can I enable it? Do I have to build properly?

**Comment by kuaashish** [comment]
Hi @RiccardoMaistri,

To enable GPU usage in Python, install the mediapipe package via pip, `"pip install mediapipe".` Note that this functionality is currently available only for macOS and Linux. Please proceed with the installation using the latest version of MP (0.10.8) and inform us about your experience with GPU utilisation. 

Thank you

**Comment by RiccardoMaistri** [comment]
> Hi @RiccardoMaistri,
> 
> To enable GPU usage in Python, install the mediapipe package via pip, `"pip install mediapipe".` Note that this functionality is currently available only for macOS and Linux. Please proceed with the installation using the latest version of MP (0.10.8) and inform us about your experience with GPU utilisation.
> 
> Thank you

Thanks for information, is there a config through which activate o deactivate the GPU? ( in case I do not want to use it)

**Comment by schmidt-sebastian** [comment]
If you want to use GPU, you have to set the delegate here: https://developers.google.com/mediapipe/api/solutions/python/mp/tasks/BaseOptions

**Comment by clogwog** [comment]
just a question regarding the macOS and linux only. does that include linux on a jetson ?
