### ISSUE TITLE
Did you follow the [second post](https://stackoverflow.com/a/65398385/10880084)? It looks like the accepted one is a bit outdated. Make sure you use the x86_64 homebrew via `arch -x86_64 /usr/local/homebrew/bin/brew install python@3.8`. Apologies, I had forgotten that the ARM homebrew is usually default in PATH.

### ISSUE THREAD

**Issue by fjameson** [google/mediapipe#4952]
I'm trying to install a second homebrew so that I can use mediapipe with an Mac M1 but I get a: ''chown: /usr/local: Operation not permitted'' when I run this command: 
      sudo chown -R "$USER":admin /Library/Caches/Homebrew
     even after sudo password input.  What am I doing wrong?

**Comment by kuaashish** [comment]
Hi @fjameson,

Could you please outline the exact steps you are following, referencing the documentation? Additionally, kindly confirm the macOS version, and you are using—specifying whether it is based on the Silicon chip or Intel. Furthermore, we kindly request you to please complete the [template](https://github.com/google/mediapipe/issues/new/choose). This will enable us to gather the maximum relevant information needed to better understand the issue from our end. 

Thank you

**Comment by fjameson** [comment]
@kuaashish I ended up install python3.8 in venv and it worked out that way
