### ISSUE TITLE
Resume training from a checkpoint

### ISSUE THREAD

**Issue by badziyoussef** [google/mediapipe#4953]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

ubuntu

### Python Version

3.10

### Task name (e.g. Image classification, Gesture recognition etc.)

object detection

### Describe the actual behavior

cannot resume training

### Describe the expected behaviour

start training, stop it, resume from checkpoint

### Standalone code/steps you may have used to try to get what you need

```shell
Is it possible to resume a training using media-pipe from a checkpoint? if so any gist that can help? also is it possible to specify a base model (like efficientdet-0, efficientdet-1, ...) to train and choose accuracy or speed? like for tflite-model-maker?
```

**Comment by kuaashish** [comment]
Hi @badziyoussef,

To accomplish this task, utilize the dedicated [save_checkpoints](https://github.com/google/mediapipe/blob/master/mediapipe/model_maker/python/vision/object_detector/model.py#L119) and [load_checkpoints](https://github.com/google/mediapipe/blob/master/mediapipe/model_maker/python/vision/object_detector/model.py#L132) methods designed exclusively for Object Detection Task APIs. For alternative MediaPipe Model Maker APIs, like Image Classification and Gesture Recognition, it is recommended to develop custom code in a manner similar to the available Object Detection methods.

Thank you

**Comment by kuaashish** [comment]
Hi @badziyoussef,

Could you please update us on the status of the issue? If you have no additional questions or concerns, we can proceed to close the matter and mark it as resolved. 

Thank you

**Comment by badziyoussef** [comment]
> Hi @badziyoussef,
> 
> Could you please update us on the status of the issue? If you have no additional questions or concerns, we can proceed to close the matter and mark it as resolved. 
> 
> Thank you
> 
> 

Hi @kuaashish 

Yes we can close this issue, the response was helping.

Thank you
