### ISSUE TITLE
0.10.8 support for GPU on linux on jetson

### ISSUE THREAD

**Issue by clogwog** [google/mediapipe#4956]
In the latest 0.10.8 release the readme says it has GPU support for macOS and linux.
Does this include GPU support for the linux on nvidia jetson machines ?

**Comment by clogwog** [comment]
mmm doesn't look like it is:
`$ python3 ./video.py
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.`
[video.py.txt](https://github.com/google/mediapipe/files/13330213/video.py.txt)

**Comment by clogwog** [comment]
can i get a confirmation for this ?

**Comment by kuaashish** [comment]
Hi @clogwog,

Regrettably, we currently do not offer official support for the Nvidia Jetson Development Kit, encompassing both CPU and GPU functionalities. The sole endorsed edge device is the Raspberry Pi 64-bit, as outlined in our [documentation](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions). 

The recently released version 0.10.8, which facilitates GPU support in Python via Pip, is exclusively compatible with macOS and Linux regular x86 or x86-64 machines, and not applicable to Windows and other operating systems.

Please rest assured that Jetson support is already on our roadmap, and our team is actively engaged in its implementation. However, we are unable to provide a specific timeline for its availability at this time. In the interim, you may leverage the community-developed plugin accessible at https://github.com/anion0278/mediapipe-jetson, which includes GPU support and reasonably up-to-date. It's important to note that the implementation is based on version 0.8.9.

Thank you

**Comment by clogwog** [comment]
@kuaashish Thank you for the confirmation !  Also for the link to the community developed plugin. i didn't know about that one.
