### ISSUE TITLE
Confidence, Visibility and Presence in Pose estimation and tracking

### ISSUE THREAD

**Issue by Saboteur20** [google/mediapipe#4959]
I would like to ask you about the method of calculation of confidence , visibility during training for pose estimation and tracking.

In addition, how and where in the code is it calculated in a real-time video case?

Also, in the case that confidence is not being calculated by a formula, then is it being calculated inside the model and how? 

During training, if the heatmaps and offset maps are used in confidence calculation, would you please explain what they are and how they contribute to the general process of training?

How much can we trust the returned confidence in general?

In pose tracking, how is presence being calculated?

**Comment by schmidt-sebastian** [comment]
@yichunk Can you provide an answer?
