### ISSUE TITLE
Comparing Performance of Facial Landmark Models Between Versions 0.8.9.1 and Latest (November 2023)

### ISSUE THREAD

**Issue by gd1925** [google/mediapipe#4961]
Hello, 

I've been working with the facial landmark model (facemesh) provided by MediaPipe, and I am currently conducting a performance comparison between two versions: the version from Dec 2021 (0.8.9.1) and the latest release as of Nov 2023.

Could you provide any insights or a changelog specific to the facial landmark detection models that would highlight performance improvements or changes made since version 0.8.9.1? I am particularly interested in any enhancements that may impact accuracy.  

This information will be incredibly helpful for my analysis and in deciding whether to integrate the latest version into codebase. Thank you.

**Comment by schmidt-sebastian** [comment]
Both the models and the implementation of the API changed significantly between our old (legacy) solutions and the new MediaPipe Tasks API. We currently do not have comparison data. Is there feature you are interested in or concerned about?
