### ISSUE TITLE
How to expose custom calculator via 'pybind11'?

### ISSUE THREAD

**Issue by Algomorph** [google/mediapipe#4965]
### Description of issue (what needs changing)

Need a guide in https://developers.google.com/mediapipe/framework/getting_started/python_framework for how to actually expose custom calculators

### Clear description

I think it's pretty obvious that if you have custom calculators, you might want to use the graph in python

### Usage example

(ditto description)

**Comment by schmidt-sebastian** [comment]
Unfortunately, this is quite complex, and we cannot provide guidance for this. You should be able to use your calculators once you have added them here: https://github.com/google/mediapipe/blob/master/mediapipe/python/BUILD#L65

Sorry about the lack of help.
