### ISSUE TITLE
Failed using gpu when training at google colab

### ISSUE THREAD

**Issue by AlifAbhiesa** [google/mediapipe#4967]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Linux ubuntu 22.04

### Python Version

3.10.12

### Task name (e.g. Image classification, Gesture recognition etc.)

Object Detection

### Describe the actual behavior

Cannot detect GPU because its install new tensorflow version

### Describe the expected behaviour

Google colab must be have preinstalled tensorflow that can use for GPU, but when install mediapipe-model-maker using pip its also install new version of tensorflow and uninstalling the old one

### Standalone code/steps you may have used to try to get what you need

```shell
Just run command at google colab

!pip install mediapipe-model-maker
```

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

I was able to replicate the issue on our end. As reported by @AlifAbhiesa, the GPU is not being detected following the installation of the MediaPipe Model Maker. Please refer to the [Colab gist](https://colab.sandbox.google.com/gist/kuaashish/f5baa2dfa8e7b3eb86d8e3480ed248cb/4967.ipynb) for a more comprehensive understanding.

Thank you

**Comment by schmidt-sebastian** [comment]
You need to use a Colab instead that has CUDA drivers and an X-Server running.

**Comment by AlifAbhiesa** [comment]
> You need to use a Colab instead that has CUDA drivers and an X-Server running.

Whan do you mean colab with cuda? Is for enable CUDA just change the runtime into GPU right? I've done with it, but still cause new version of tensorflow cuda not detected

**Comment by AlifAbhiesa** [comment]
> Hi @schmidt-sebastian,
> 
> I was able to replicate the issue on our end. As reported by @AlifAbhiesa, the GPU is not being detected following the installation of the MediaPipe Model Maker. Please refer to the [Colab gist](https://colab.sandbox.google.com/gist/kuaashish/f5baa2dfa8e7b3eb86d8e3480ed248cb/4967.ipynb) for a more comprehensive understanding.
> 
> Thank you

Is there any proper solution for this?

**Comment by kuaashish** [comment]
Hi @AlifAbhiesa,

This issue is fixed. After installing the MediaPipe model maker, the GPU is now being detected([Gist](https://colab.sandbox.google.com/gist/kuaashish/463ffaff27de5075e76ae389823da898/4967.ipynb)). Please check to see if the issue persists on your end and let us know.

Thank you

**Comment by kuaashish** [comment]
Hi @AlifAbhiesa,

Could you kindly review the preceding comment and provide us with an update?

Thank you!!
