### ISSUE TITLE
Fail to run AutoFlip on certain videos

### ISSUE THREAD

**Issue by BroderickHigby** [google/mediapipe#497]
W0305 22:35:34.647359 14839 opencv_video_decoder_calculator.cc:224] Not all the frames are decoded (total frames: 6084 vs decoded frames: 3200).
W0305 22:35:35.686440 14839 opencv_video_encoder_calculator.cc:187] OpenCvVideoEncoderCalculator isn't able to attach the audio tracks to the generated video because the audio file path is not specified.
E0305 22:35:35.907760 14839 simple_run_graph_main.cc:146] Failed to run the graph: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "[SceneCroppingCalculator, SceneCroppingCalculator with output stream: cropped_frames]" failed: ; ClampRect(original_frame_width, original_frame_height, &location) returned Internal: ; !(location->x() >= x1 || location->x() + location->width() <= x0 || location->y() >= y1 || location->y() + location->height() <= y0)

**Comment by ndimension** [comment]
Hi @BroderickHigby, thank you for finding this bug.

Would it be possible for you to supply a test video we can use for debugging?  This will help us identify the root cause and then we can push out an update.

**Comment by tapptic-bazzile** [comment]
@ndimension I experience this error even on 'life_at_google.mp4' file from autoflip GDrive folder 
https://drive.google.com/drive/u/0/folders/1KK9LV--Ey0UEVpxssVLhVl7dypgJSQgk

**Comment by m1r4s** [comment]
@ndimension I experience this error even on 'life_at_google.mp4' file from autoflip GDrive folder
https://drive.google.com/drive/u/0/folders/1KK9LV--Ey0UEVpxssVLhVl7dypgJSQgk

**Comment by m1r4s** [comment]
@ndimension I experience this problem even with 'life_at_google.mp4' file from autoflip GDrive folder
https://drive.google.com/drive/u/0/folders/1KK9LV--Ey0UEVpxssVLhVl7dypgJSQgk

I'm not sure if it's relevant. I have opencv v3.4.9

**Comment by jiuqiant** [comment]
@m1r4s, can you report your OS info, gcc version, and bazel version to help us reproduce/debug this issue?
 
Based on https://github.com/google/mediapipe/issues/487#issuecomment-593774685 and https://github.com/google/mediapipe/issues/491, @thesofakillers can run AutoFlip with OpenCV 3.4.9 on Ubuntu 16.04.6 LTS.

**Comment by m1r4s** [comment]
@jiuqiant My specs:

- Linux Mint 18 
- bazel 1.2.1
- gcc 5.4.0

**Comment by thesofakillers** [comment]
I confirm that I am able to run AutoFlip on Ubuntu 16.04.6 LTS, with OpenCV 3.4.9
- bazel 1.2.0
- gcc 5.4.0

**Comment by m1r4s** [comment]
@jiuqiant I have checked also on fresh Ubuntu 18 machine. Problem occurs there too.

- Ubuntu 18.04.4 LTS
- OpenCV 3.2.0
- bazel 1.2.1
- gcc 7.5.0

**Comment by jiuqiant** [comment]
@m1r4s I will try to reproduce your issue on a Google Cloud Ubuntu 18 instance soon.

**Comment by jiuqiant** [comment]
Okay, I can reproduce it on a GCP instance.

I record the detailed steps for ourselves to debug. Feel free to ignore this comment.

Step 1. Start a GCP Ubuntu instance with boot disk  `Google Drawfork Ubuntu 18.04 LTS`.

Step 2. Install basic packages

```
sudo apt-get update && sudo apt-get install -y --no-install-recommends build-essential ca-certificates git g++ wget unzip python python-pip emacs
```

Step 3. Install OpenCV packages

```
sudo apt-get install ffmpeg libopencv-core-dev libopencv-highgui-dev libopencv-calib3d-dev libopencv-features2d-dev libopencv-imgproc-dev libopencv-video-dev
```

Step 4. Install Bazel

```
curl -sLO --retry 5 --retry-max-time 10   https://storage.googleapis.com/bazel/1.2.1/release/bazel-1.2.1-installer-linux-x86_64.sh && sudo mkdir -p /usr/local/bazel/1.2.1 && chmod 755 bazel-1.2.1-installer-linux-x86_64.sh && sudo ./bazel-1.2.1-installer-linux-x86_64.sh --prefix=/usr/local/bazel/1.2.1 && source /usr/local/bazel/1.2.1/lib/bazel/bin/bazel-complete.bash && /usr/local/bazel/1.2.1/lib/bazel/bin/bazel version && alias bazel='/usr/local/bazel/1.2.1/lib/bazel/bin/bazel'
```

Step 5. Git clone mediapipe

```
git clone https://github.com/google/mediapipe.git 
cd mediapipe
```

Step 6. Build AutoFlip

```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples
/desktop/autoflip:run_autoflip
```

Step 7. Run AutoFlip

```
bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip --calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt --input_side_packets=input_video_path=/home/jqtang/life_at_google.mp4,output_video_path=/home/jqtang/life_at_google_output1.mp4,aspect_ratio=1:1
```

Error message:

```
E0312 04:46:39.296072 30440 scene_cropping_calculator.cc:240] ------------------------ (Breathing) Time(s)
: 116.783
E0312 04:46:39.428944 30440 scene_cropping_calculator.cc:240] ------------------------ (Breathing) Time(s)
: 117.117
E0312 04:46:39.792198 30440 scene_cropping_calculator.cc:240] ------------------------ (Breathing) Time(s)
: 117.451
E0312 04:46:39.799410 30440 scene_cropping_calculator.cc:240] ------------------------ (Breathing) Time(s)
: 117.784
E0312 04:46:39.907333 30441 scene_cropping_calculator.cc:240] ------------------------ (Breathing) Time(s)
: 118.118
E0312 04:46:41.008229 30435 simple_run_graph_main.cc:146] Failed to run the graph: CalculatorGraph::Run() 
failed in Run: 
Calculator::Process() for node "[SceneCroppingCalculator, SceneCroppingCalculator with output stream: crop
ped_frames]" failed: ; ClampRect(original_frame_width, original_frame_height, &location) returned INTERNAL
: ; !(location->x() > x1 || location->x() + location->width() < x0 || location->y() > y1 || location->y() 
+ location->height()< y0) 
```

**Comment by jiuqiant** [comment]
@m1r4s  I can reproduce this issue. It seems like AutoFlip detects some out-of-boundary issue and throws an error. You can disable the check by doing the following

```
$ git diff
diff --git a/mediapipe/examples/desktop/autoflip/quality/utils.cc b/mediapipe/examples/desktop/autoflip/quality/utils.cc
index b7b41d9..8b68e99 100644
--- a/mediapipe/examples/desktop/autoflip/quality/utils.cc
+++ b/mediapipe/examples/desktop/autoflip/quality/utils.cc
@@ -60,9 +60,6 @@ void NormalizedRectToRect(const RectF& normalized_location, const int width,
 
 ::mediapipe::Status ClampRect(const int x0, const int y0, const int x1,
                               const int y1, Rect* location) {
-  RET_CHECK(!(location->x() >= x1 || location->x() + location->width() <= x0 ||
-              location->y() >= y1 || location->y() + location->height() <= y0));
-
   int clamped_left, clamped_right, clamped_top, clamped_bottom;
   RET_CHECK(MathUtil::Clamp(x0, x1, location->x(), &clamped_left));
   RET_CHECK(MathUtil::Clamp(x0, x1, location->x() + location->width(),
```

But, this solution is still problematic. If the program gets stuck somewhere, please rerun. 
BTW, please also make sure you have ffmpeg installed.
We will do some investigation and figure out a good solution for this soon.
