### ISSUE TITLE
Mediapipe python cuda gpu docker

### ISSUE THREAD

**Issue by pydehon** [google/mediapipe#4970]
Hello dear mediapipe dev team and community! 

It has been some time that I have been following the mediapipe's project closely and thank you so much for the great work you have done!

I just wanted to bring my stone to your amazing project.

Maybe I didn't look at the right place but I never achieved to get the python gpu (opengl or cuda) version to work reliably. I never bothered filling an issue seeing the number unresolved about this topic. 

Well after a great lot of rebuilding, I finally came to a working docker image that leverage cuda, and gpu with the python lib for one of the latest version of mediapipe.

There is really no issue, I just wanted to modestly share my repo for anyone who would be interested in such a docker ;)

https://github.com/pydehon/mediapipe

Big thank to https://github.com/riverzhou/mediapipe which is the base for my repo

**Comment by kuaashish** [comment]
Hi @pydehon,

Thank you for sharing your GPU implementation with Docker. This contribution holds great potential to assist the community seeking GPU support within Docker. If any community members express interest in this specific implementation, we can guide them to leverage the utilities you have developed.

**Comment by lanzani** [comment]
Thank you! I will try to modify it for Jetson :) 

If I manage to do it, I will add the process to this issue.

**Comment by francescocassini** [comment]
Hi, have you some updates? I'm interested in this project cause Mediapipe is really a good and final solution in the head and body analysis...
I will try these days and I give you a feedback :)
Many thanks

**Comment by lanzani** [comment]
Hello! Try to look [here](https://jetson-docs.com/libraries/mediapipe/overview), I've managed to build mediapipe for jetson and use it in a docker.

There you can find different version of mediapipe, for different python versions on different version of jetpack.

(you can find there also the Dockerfile I've used if you need to make some changes)

Hope it will be useful :)

**Comment by Gnoot01** [comment]
Awesome work on the docker for GPU! It works on my windows using WSL as well. However, it's a bit weird in that somehow it's slower than CPU processing for the latest mediapipe pose model, any thoughts?

**Comment by lanzani** [comment]
I had quite some problems using docker + gpu on wsl... so I've used another device with ubuntu :)

**Comment by pydehon** [comment]
Hey, sorry I've not been very active lately but if you want to leverage gpu performance without issue, just use the Js version of the models that will run on webgpu! I found it quite easy to either put in place a quick api using node or migrating my project from python to opencv.js/mediapipe.js. 

Let me know if you have questions! I'll keep an eye open on the thread this time ;)
