### ISSUE TITLE
Trying to do face detection but get Error that module 'mediapipe.tasks.python.vision' has no attribute 'FaceDetector'

### ISSUE THREAD

**Issue by YashPotdar** [google/mediapipe#4971]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

MacOs Ventura 13 -- Python 3.7.4

### Task name (e.g. Image classification, Gesture recognition etc.)

Face detection and facial landmark detection

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

AttributeError

### Describe the expected behaviour

Object should be created

### Standalone code/steps you may have used to try to get what you need

```shell
Following the code example (https://github.com/googlesamples/mediapipe/blob/main/examples/face_detector/python/face_detector.ipynb), but getting an error when calling `vision.FaceDetectorOptions` saying module 'mediapipe.tasks.python.vision' has no attribute 'FaceDetector'. I noticed that face_detector.py and face_lamdmarker.py are in Github, not in site_packages after running pip install mediapipe.
```

**Comment by kuaashish** [comment]
Hi @YashPotdar,

It appears there is an issue with the primary Python version. I was able to successfully execute the same example using Python 3.11.6 and MP version 0.10.8 on macOS (Sonoma 4.1.1 - build 23B81) without encountering any errors.

Firstly, We recommend upgrading your Python version from 3.8 to 3.11 and attempting the process again. Secondary, If the issue persists, we advise upgrading to the newer macOS version or updating to macOS (Sonoma). Also, Please inform us if this works for you.

Thank you
