### ISSUE TITLE
face_stylizer example throws error in colab 

### ISSUE THREAD

**Issue by grabowCommuter** [google/mediapipe#4973]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

COLAB

### MediaPipe Tasks SDK version

10.8

### Task name (e.g. Image classification, Gesture recognition etc.)

face_stylizer

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

Runtime error in 5th cell of example (https://developers.google.com/mediapipe/solutions/customization/face_stylizer)

### Describe the expected behaviour

Execute create dataset

### Standalone code/steps you may have used to try to get what you need

```shell
https://colab.research.google.com/github/googlesamples/mediapipe/blob/main/examples/customization/face_stylizer.ipynb

Error occurs in cell 5: data = face_stylizer.Dataset.from_image(filename=style_image_path)
"
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-b3643ca17ef4> in <cell line: 1>()
----> 1 data = face_stylizer.Dataset.from_image(filename=style_image_path)

3 frames
/usr/local/lib/python3.10/dist-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py in __init__(self, graph_config, running_mode, packet_callback)
     68           'callback should not be provided.'
     69       )
---> 70     self._runner = _TaskRunner.create(graph_config, packet_callback)
     71     self._running_mode = running_mode
     72 

RuntimeError: Service "kGpuService", required by node mediapipe_tasks_vision_face_stylizer_facestylizergraph__mediapipe.tasks.TensorsToImageCalculator, was not provided and cannot be created: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
"
```

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

I was able to replicate the issue on our end. As reported by @grabowCommuter, There is an issue with the Face Stylizer example in MediaPipe Model Maker. It is not running correctly and is generating the following error: 

"_RuntimeError: Service 'kGpuService', required by node mediapipe_tasks_vision_face_stylizer_facestylizergraph__mediapipe.tasks.TensorsToImageCalculator_ "

When executing the code snippet `data = face_stylizer.Dataset.from_image(filename=style_image_path)`.

Please refer to the [Colab gist](https://colab.sandbox.google.com/gist/kuaashish/99d2c0ed69d4812eb51a03dca06b401d/colab.ipynb) for a more comprehensive understanding.

Thank you

**Comment by schmidt-sebastian** [comment]
This is an issue in MediaPipe and not in ModelMaker. I will take a look.

**Comment by kuaashish** [comment]
Hi @grabowCommuter,

We have fixed the issue. It was a problem with MediaPipe, not the MediaPipe model maker. The model maker relies on MediaPipe and other similar dependencies. Also, Please make sure you've enabled GPU in Colab. For Face Stylizer, a GPU is necessary for running the example.

Thank you!!
