### ISSUE TITLE
Hello World Fails To Build

### ISSUE THREAD

**Issue by mericgeren** [google/mediapipe#4976]
### Device

Jetson AGX Xavier

### OS Platform and Distribution

L4T 32.7.4 (Ubuntu 18.04) / JetPack 4.6.4

### Compiler version

gcc = 7.5.0 / nvcc = 10.2.300

### Programming Language and version

Java = 1.8.0 / Python = 3.6

### Installed using virtualenv? pip? Conda?(if python)

I have installed by following [this guide](https://developers.google.com/mediapipe/framework/getting_started/install) and option 3

### MediaPipe version

0.8.1

### Bazel version

3.7.0

### XCode and Tulsi versions (if iOS)

N/A (Not IOS)

### Android SDK and NDK versions (if android)

N/A (Not Android)

### Android AAR (if android)

N/A (Not Android)

### OpenCV version (if running on desktop)

4.1.1

### Describe the problem

Hello, 

I have installed Bazel 3.7.0 following [this tutorial](https://bazel.build/install/compile-source#bootstrap-bazel). Then git cloned mediapipe with this command: `git clone --depth 1 -b 0.8.1 https://github.com/google/mediapipe.git` and then, made sure that it points to my pre-installed opencv4 by modifying opencv_linux.BUILD (WORKSPACE was correct). Then i have run the command: `bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world` and got an error telling me there wasn't such a package "@rules_foreign_cc//". Then i realized it tries to find something called rules_foreign_cc-master. But, it's main now. So i have changed each "rules_foreign_cc-master"  with "rules_foreign_cc-main". Then, i have tried the command another time. This time it gave an error telling me there is not such a file named "@rules_foreign_cc//:workspace_definitions.bzl ". So i have found and followed [this kind advice](https://github.com/google/mediapipe/issues/2102#issuecomment-853498491) and tried running the command for another time. This time i got an error telling me "Label '@rules_foreign_cc//tools/build_defs:cmake.bzl' is invalid because 'tools/build_defs' is not a package" and another one telling me "Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Analysis failed" and i couldn't find a solution for these erros and subsequent fails. Could you offer your guidance and advises please? 

Kindest regards.

### Complete Logs

This is the output log of my latest try for running `bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world` command:

```shell
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Repository com_google_absl instantiated at:
  /home/mericgeren/mediapipe/WORKSPACE:17:13: in <toplevel>
Repository rule http_archive defined at:
  /home/mericgeren/.cache/bazel/_bazel_mericgeren/9a24e847ebc82a444cfef0515b4986d5/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /home/mericgeren/mediapipe/mediapipe/framework/port/BUILD:203:11: error loading package 'third_party': Label '@rules_foreign_cc//tools/build_defs:cmake.bzl' is invalid because 'tools/build_defs' is not a package; perhaps you meant to put the colon here: '@rules_foreign_cc//:tools/build_defs/cmake.bzl'? and referenced by '//mediapipe/framework/port:logging'
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Analysis failed
INFO: Elapsed time: 29.169s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (28 packages loaded, 60 targets co\
FAILED: Build did NOT complete successfully (28 packages loaded, 60 targets co\
nfigured)
    currently loading: mediapipe/framework/tool
```
This is the output log i got as i tried the `bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world` command again after the command `bazel clean --expunge`:

```

Starting local Bazel server and connecting to it...
WARNING: ignoring LD_PRELOAD in environment.
INFO: Repository rules_proto instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:293:6: in <toplevel>
  /home/mericgeren/.cache/bazel/_bazel_mericgeren/9a24e847ebc82a444cfef0515b4986d5/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /home/mericgeren/.cache/bazel/_bazel_mericgeren/9a24e847ebc82a444cfef0515b4986d5/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository com_google_absl instantiated at:
  /home/mericgeren/mediapipe/WORKSPACE:17:13: in <toplevel>
Repository rule http_archive defined at:
  /home/mericgeren/.cache/bazel/_bazel_mericgeren/9a24e847ebc82a444cfef0515b4986d5/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /home/mericgeren/mediapipe/mediapipe/framework/port/BUILD:203:11: error loading package 'third_party': Label '@rules_foreign_cc//tools/build_defs:cmake.bzl' is invalid because 'tools/build_defs' is not a package; perhaps you meant to put the colon here: '@rules_foreign_cc//:tools/build_defs/cmake.bzl'? and referenced by '//mediapipe/framework/port:logging'
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Analysis failed
INFO: Elapsed time: 18.957s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (36 packages loaded, 98 targets co\
FAILED: Build did NOT complete successfully (36 packages loaded, 98 targets co\
nfigured)
    currently loading: @com_google_protobuf//

```

Here is the WORKSPACE file in it's current state:

[WORKSPACE.txt](https://github.com/google/mediapipe/files/13427329/WORKSPACE.txt)

Here is the opencv_linux.BUILD file in it's current state:

[opencv_linux.BUILD.txt](https://github.com/google/mediapipe/files/13427364/opencv_linux.BUILD.txt)

**Comment by kuaashish** [comment]
Hi @mericgeren,

You are trying to build MediaPipe in Jetson AGX Xavier that we have not tested officially and currently not supported. Only Supported edge device is raspberry Pi 64 as guided in our [documentation](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions), at the moment we will not able provide the support on it. 

However, We would like to inform you know Jeston support is already in our roadmap and team is working and testing it's implementation. But, We can not provide exact timeline for it's availability. Nevertheless, there is community plugin https://github.com/anion0278/mediapipe-jetson is already known with support of Jeston is quite up to date, You may refer the plugin if that maybe prove beneficial you may implement it. 

Thank you

**Comment by mericgeren** [comment]
Thank you for the information and your kind advises.

I will try to use the plugin you have told me about. If you don't mind I am closing this issue as completed.

Kindest regards.
