### ISSUE TITLE
bazel build error Server terminated abruptly (error code: 2, error message: 'Stream removed)

### ISSUE THREAD

**Issue by okhwanbae** [google/mediapipe#4979]
[command.log](https://github.com/google/mediapipe/files/13447617/command.log)

"build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Users\foem9\AppData\Local\Programs\Python\Python39\python.exe" mediapipe\examples\desktop\hello_world"
When using the above command

Loading: Fetching repository @llvm-raw; starting 55s Fetching C:/users/foem9/_bazel_foem9/3vmcl3ou/external/llvm-raw; Extracting 1c154bd755153b5c6ada4bbed58facf23f6abffc.tar.gz 55s
Server terminated abruptly (error code: 2, error message: 'Stream removed', log file: 'c:\users\foem9_bazel_foem9\3vmcl3ou\server\jvm.out')

This error occurs.
There is nothing in jvm.out
Please help me

bazel version: 6.1.1
os:windows 10

opencv version 3.4.10
Python installed 3.9.10.

Environment variable settings are as follows
C:\bazel
C:\Users\foem9\AppData\Local\Programs\Python\Python39
C:\Users\foem9\AppData\Local\Programs\Python\Python39\Scripts
C:\msys64\usr\bin

set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
set BAZEL_VC_FULL_VERSION= 19.29.30153
set BAZEL_WINSDK_FULL_VERSION=10.0.19041.0

opencv was installed in the C:\opencv folder

If the build fails and you use the build command again, the following error occurs.
FATAL: corrupt installation: file 'C:\Users\foem9_bazel_foem9\install\5e201cf3f4291acab0531ef7b20c61ef\A-server.jar' is missing or modified.

**Comment by kuaashish** [comment]
Hi @okhwanbae,

Could you kindly confirm whether the issue still persists or if it has been resolved on your end? 

Thank you
