### ISSUE TITLE
Face Landmark Point

### ISSUE THREAD

**Issue by khabya** [google/mediapipe#498]
a) How to get the face landmark point coordinates of the detected point?
b) Is it possible to normalise the face landmark point to place 2D image or 3D model on it and have the tracking of the model with the face setted up?
C) Is occlusion can be done in hand-tracking and face tracking in mediapipe?

**Comment by khabya** [comment]
Can anyone help me out inn above question?

**Comment by delebash** [comment]
I am new to this and not sure this is what you are looking for but I think so.

See this article
[Face landmarks detection with MediaPipe Facemesh](https://towardsdatascience.com/face-landmarks-detection-with-mediapipe-facemesh-555fa2e10b06)

Towards the end of the paper you can see the javascript debug console and it has the coordinates information in an array.

For each of the facial landmark key point, it contains the location of the x, y axis and depth.
0: Array(3)
    0: 202.05661010742188
    1: 207.98629760742188
    2: -5.985757827758789
    length: 3
