### ISSUE TITLE
Mediapipe Holistic Nondeterministic Behaviour

### ISSUE THREAD

**Issue by tugcekiziltepe** [google/mediapipe#4981]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 10

### Task name (e.g. Image classification, Gesture recognition etc.)

Holistic landmarks detection

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

Non-deterministic Holistic landmarks detection with track mode off

### Describe the expected behaviour

Holistic landmarks detection should be deterministic and should give same result everytime.

### Standalone code/steps you may have used to try to get what you need

```shell
I am using mediapipe python version 0.10.7. I am using code below to initialize Holistic model: 

import mediapipe as mp
mp_holistic = mp.solutions.holistic
holistic = mp_holistic.Holistic(min_detection_confidence=0.3, static_image_mode = True)

I am reading images in a folder sequentially and predicting keypoints using holistic.process(image). I am trying to get rid of images that doesn’t detect right hand keypoints. I run this for a folder in loop. If I re-run this loop with shuffled data, results are changing. My dataset consists of 24k images. In first run, model failed to detect right hand keypoints in 305 images. In the second run, shuffled one, this number becomes 320. I do not get why this happens. This seems non-deterministic and model is not in track mode. Does mediapipe non deterministic?
```

**Comment by kuaashish** [comment]
Hi @tugcekiziltepe,

We have upgraded our MediaPipe Legacy Solutions to include new features like the Holistic Task API. You can still use the old solutions if you prefer, but we recommend checking out the new MediaPipe options. New Task APIs make it easier to build and customize machine learning solutions for your applications.

Could you give the new [HolisticLandmarker](https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/vision/holistic_landmarker.py) task APIs a try and let us know if you encounter any issues?

Thank you!!
