### ISSUE TITLE
 mediapipe_tasks_vision_gesture_recognizer Graph error

### ISSUE THREAD

**Issue by RiccardoMaistri** [google/mediapipe#4982]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Ubuntu 20

### MediaPipe Tasks SDK version

0.10.8

### Task name (e.g. Image classification, Gesture recognition etc.)

Gesture Recognition

### Programming Language and version (e.g. C++, Python, Java)

Python3.8

### Describe the actual behavior

/

### Describe the expected behaviour

/

### Standalone code/steps you may have used to try to get what you need

I  encountered this error while runngin gesture_recognizer on CPU (ubuntu)

```
RuntimeError: Graph has errors: 
Calculator::Process() for node "mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_gesture_recognizer_multiplehandgesturerecognizergraph__mediapipe_tasks_vision_gesture_recognizer_singlehandgesturerecognizergraph__ConcatenateTensorVectorCalculator" failed: Packet isn't the sole owner of the hol

```

**Comment by RiccardoMaistri** [comment]
Full log:


```
    self.mp_detector.recognize_async(
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/tasks/python/vision/gesture_recognizer.py", line 473, in recognize_async
    self._send_live_stream_data({
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 139, in _send_live_stream_data
    self._runner.send(inputs)
RuntimeError: Graph has errors: 
Calculator::Process() for node "mediapipe_tasks_vision_gesture_recognizer_gesturerecognizergraph__mediapipe_tasks_vision_gesture_recognizer_multiplehandgesturerecognizergraph__mediapipe_tasks_vision_gesture_recognizer_singlehandgesturerecognizergraph__ConcatenateTensorVectorCalculator" failed: Packet isn't the sole owner of the holder.

```

**Comment by kuaashish** [comment]
Hi @RiccardoMaistri,

Could you please specify the Ubuntu version you're using? Additionally, provide the detailed steps or examples from the documentation that you're following. This information will help us better understand and reproduce the issue from our end.

Thank you!!

**Comment by RiccardoMaistri** [comment]
> Hi @RiccardoMaistri,
> 
> Could you please specify the Ubuntu version you're using? Additionally, provide the detailed steps or examples from the documentation that you're following. This information will help us better understand and reproduce the issue from our end.
> 
> Thank you!!

I am running mediapipe on a docker container with ubuntu 20.04, this error happens randomly, I still have to figure it out how to reproduce it.

**Comment by cslvjt** [comment]
Hello, have you resolved this issue?
