### ISSUE TITLE
 Unable to open file at \test\hand_landmarker.task

### ISSUE THREAD

**Issue by Jwh-serendipity** [google/mediapipe#4983]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 10

### Python Version

3.9

### MediaPipe Model Maker version

最新

### Task name (e.g. Image classification, Gesture recognition etc.)

手势识别

### Describe the actual behavior

代码无法跑通

### Describe the expected behaviour

代码应该可以跑通

### Standalone code/steps you may have used to try to get what you need

```shell
import cv2
import mediapipe as mp
from mediapipe import solutions
from mediapipe.framework.formats import landmark_pb2
import numpy as np
from mediapipe.tasks import python
from mediapipe.tasks.python import vision


MARGIN = 10  # pixels
FONT_SIZE = 1
FONT_THICKNESS = 1
HANDEDNESS_TEXT_COLOR = (88, 205, 54) # vibrant green

img = cv2.imread("photo.jpg")
cv2.imshow('photo', img)

def draw_landmarks_on_image(rgb_image, detection_result):
  hand_landmarks_list = detection_result.hand_landmarks
  handedness_list = detection_result.handedness
  annotated_image = np.copy(rgb_image)

  # Loop through the detected hands to visualize.
  for idx in range(len(hand_landmarks_list)):
    hand_landmarks = hand_landmarks_list[idx]
    handedness = handedness_list[idx]

    # Draw the hand landmarks.
    hand_landmarks_proto = landmark_pb2.NormalizedLandmarkList()
    hand_landmarks_proto.landmark.extend([
      landmark_pb2.NormalizedLandmark(x=landmark.x, y=landmark.y, z=landmark.z) for landmark in hand_landmarks
    ])
    solutions.drawing_utils.draw_landmarks(
      annotated_image,
      hand_landmarks_proto,
      solutions.hands.HAND_CONNECTIONS,
      solutions.drawing_styles.get_default_hand_landmarks_style(),
      solutions.drawing_styles.get_default_hand_connections_style())

    # Get the top left corner of the detected hand's bounding box.
    height, width, _ = annotated_image.shape
    x_coordinates = [landmark.x for landmark in hand_landmarks]
    y_coordinates = [landmark.y for landmark in hand_landmarks]
    text_x = int(min(x_coordinates) * width)
    text_y = int(min(y_coordinates) * height) - MARGIN

    # Draw handedness (left or right hand) on the image.
    cv2.putText(annotated_image, f"{handedness[0].category_name}",
                (text_x, text_y), cv2.FONT_HERSHEY_DUPLEX,
                FONT_SIZE, HANDEDNESS_TEXT_COLOR, FONT_THICKNESS, cv2.LINE_AA)

  return annotated_image


# STEP 2: Create an HandLandmarker object.
base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')
options = vision.HandLandmarkerOptions(base_options=base_options,
                                       num_hands=2)
detector = vision.HandLandmarker.create_from_options(options)

# STEP 3: Load the input image.
image = mp.Image.create_from_file("photo.jpg")

# STEP 4: Detect hand landmarks from the input image.
detection_result = detector.detect(image)

# STEP 5: Process the classification result. In this case, visualize it.
annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)
cv2.imshow(cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))
```

**Comment by kuaashish** [comment]
Hi @Jwh-serendipity,

I am able to run using the reproducible code you have provided with a few modifications as below in Windows 10, Python 3.9.13 with MP v0.10.8:

`img = cv2.imread("photo.jpg")`, Modified to `img = cv2.imread('Path Of Image')`

`base_options = python.BaseOptions(model_asset_path='hand_landmarker.task')`, Modified to 
`base_options = python.BaseOptions(model_asset_path='Path Of hand_landmarker.task')`

`image = mp.Image.create_from_file("photo.jpg")`, Modified to 
`image = mp.Image.create_from_file('Path Of Image')`

`cv2.imshow(cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))`, Modified to
`cv2.imshow('',cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))`

Here is full code which I have modified and running correctly,

```
import cv2
import mediapipe as mp
from mediapipe import solutions
from mediapipe.framework.formats import landmark_pb2
import numpy as np
from mediapipe.tasks import python
from mediapipe.tasks.python import vision


MARGIN = 10  # pixels
FONT_SIZE = 1
FONT_THICKNESS = 1
HANDEDNESS_TEXT_COLOR = (88, 205, 54) # vibrant green

img = cv2.imread('C:/Users/kuaashish/Downloads/handtest.jpg')
cv2.imshow('photo', img)

def draw_landmarks_on_image(rgb_image, detection_result):
  hand_landmarks_list = detection_result.hand_landmarks
  handedness_list = detection_result.handedness
  annotated_image = np.copy(rgb_image)

  # Loop through the detected hands to visualize.
  for idx in range(len(hand_landmarks_list)):
    hand_landmarks = hand_landmarks_list[idx]
    handedness = handedness_list[idx]

    # Draw the hand landmarks.
    hand_landmarks_proto = landmark_pb2.NormalizedLandmarkList()
    hand_landmarks_proto.landmark.extend([
      landmark_pb2.NormalizedLandmark(x=landmark.x, y=landmark.y, z=landmark.z) for landmark in hand_landmarks
    ])
    solutions.drawing_utils.draw_landmarks(
      annotated_image,
      hand_landmarks_proto,
      solutions.hands.HAND_CONNECTIONS,
      solutions.drawing_styles.get_default_hand_landmarks_style(),
      solutions.drawing_styles.get_default_hand_connections_style())

    # Get the top left corner of the detected hand's bounding box.
    height, width, _ = annotated_image.shape
    x_coordinates = [landmark.x for landmark in hand_landmarks]
    y_coordinates = [landmark.y for landmark in hand_landmarks]
    text_x = int(min(x_coordinates) * width)
    text_y = int(min(y_coordinates) * height) - MARGIN

    # Draw handedness (left or right hand) on the image.
    cv2.putText(annotated_image, f"{handedness[0].category_name}",
                (text_x, text_y), cv2.FONT_HERSHEY_DUPLEX,
                FONT_SIZE, HANDEDNESS_TEXT_COLOR, FONT_THICKNESS, cv2.LINE_AA)

  return annotated_image


# STEP 2: Create an HandLandmarker object.
base_options = python.BaseOptions(model_asset_path='C:/Users/kuaashish/Downloads/hand_landmarker.task')
options = vision.HandLandmarkerOptions(base_options=base_options,
                                       num_hands=2)
detector = vision.HandLandmarker.create_from_options(options)

# STEP 3: Load the input image.
image = mp.Image.create_from_file('C:/Users/kuaashish/Downloads/handtest.jpg')

# STEP 4: Detect hand landmarks from the input image.
detection_result = detector.detect(image)

# STEP 5: Process the classification result. In this case, visualize it.
annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)
cv2.imshow('',cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))
```

Please let us know if this works for you. Thank you

**Comment by kuaashish** [comment]
Hi @Jwh-serendipity,

Could you update the status of the above if you are now able to run example in Windows? please let us know.

Thank you

**Comment by Jwh-serendipity** [comment]
我这边用不了，代码运行时会出现缺少task的报错，然后也下载不了这个task，应该是你们的网页丢失了。请问可以发一份模型给我吗？谢谢！ ---- Replied Message ***@***.***>Date11/28/2023 14:05 ***@***.***> ***@***.***>***@***.***>SubjectRe: [google/mediapipe] Unable to open file at \test\hand_landmarker.task (Issue #4983)
Hi @Jwh-serendipity,
Could you update the status of the above if you are now able to run example in Windows? please let us know.
Thank you

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/google/mediapipe/issues/4983#issuecomment-1829176994",
"url": "https://github.com/google/mediapipe/issues/4983#issuecomment-1829176994",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kuaashish** [comment]
Hi @Jwh-serendipity,

You can obtain the Hand Landmarker Task Model by downloading it from the following link: https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/latest/hand_landmarker.task.

Thank you

**Comment by julrog** [comment]
I have a similar error on windows 11 python 3.9.2:
```
Unable to open file at d:\{...}\env\lib\site-packages/D:\{...}\models\gesture_recognizer.task, errno=22
```

Error thrown at
```
        base_options = python.BaseOptions(
            model_asset_path='models/gesture_recognizer.task')
        options = vision.GestureRecognizerOptions(
            base_options=base_options)
 --->   self.gesture = vision.GestureRecognizer.create_from_options(
            options)
```
I suspect the same reason for this error. On python side the absolute path (via `os.path.abspath(self.model_asset_path)` in `BaseOptions`) is taken but somewhere deeper on the C side of the underlying code the path is again prepended with a path to my virtual environment with the parent location of the mediapipe package, which makes it impossible to find the model file.

**Comment by Jwh-serendipity** [comment]
你好！我下载了这个task，但是我不知道具体用法，我直接放在代码文件夹里面，发现仍然无法使用。请问我该怎么操作？谢谢！​---- Replied Message ***@***.***>Date12/01/2023 13:32 ***@***.***> ***@***.***>***@***.***>SubjectRe: [google/mediapipe] Unable to open file at \test\hand_landmarker.task (Issue #4983)
Hi @Jwh-serendipity,
You can obtain the Hand Landmarker Task Model by downloading it from the following link: https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/latest/hand_landmarker.task.
Thank you

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/google/mediapipe/issues/4983#issuecomment-1835491053",
"url": "https://github.com/google/mediapipe/issues/4983#issuecomment-1835491053",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Jwh-serendipity** [comment]
这是源代码：
import cv2
import mediapipe as mp
from mediapipe import solutions
from mediapipe.framework.formats import landmark_pb2
import numpy as np
from mediapipe.tasks import python
from mediapipe.tasks.python import vision


MARGIN = 10  # pixels
FONT_SIZE = 1
FONT_THICKNESS = 1
HANDEDNESS_TEXT_COLOR = (88, 205, 54) # vibrant green

img = cv2.imread('photo.jpg')
cv2.imshow('photo', img)

def draw_landmarks_on_image(rgb_image, detection_result):
  hand_landmarks_list = detection_result.hand_landmarks
  handedness_list = detection_result.handedness
  annotated_image = np.copy(rgb_image)

  # Loop through the detected hands to visualize.
  for idx in range(len(hand_landmarks_list)):
    hand_landmarks = hand_landmarks_list[idx]
    handedness = handedness_list[idx]

    # Draw the hand landmarks.
    hand_landmarks_proto = landmark_pb2.NormalizedLandmarkList()
    hand_landmarks_proto.landmark.extend([
      landmark_pb2.NormalizedLandmark(x=landmark.x, y=landmark.y, z=landmark.z) for landmark in hand_landmarks
    ])
    solutions.drawing_utils.draw_landmarks(
      annotated_image,
      hand_landmarks_proto,
      solutions.hands.HAND_CONNECTIONS,
      solutions.drawing_styles.get_default_hand_landmarks_style(),
      solutions.drawing_styles.get_default_hand_connections_style())

    # Get the top left corner of the detected hand's bounding box.
    height, width, _ = annotated_image.shape
    x_coordinates = [landmark.x for landmark in hand_landmarks]
    y_coordinates = [landmark.y for landmark in hand_landmarks]
    text_x = int(min(x_coordinates) * width)
    text_y = int(min(y_coordinates) * height) - MARGIN

    # Draw handedness (left or right hand) on the image.
    cv2.putText(annotated_image, f"{handedness[0].category_name}",
                (text_x, text_y), cv2.FONT_HERSHEY_DUPLEX,
                FONT_SIZE, HANDEDNESS_TEXT_COLOR, FONT_THICKNESS, cv2.LINE_AA)

  return annotated_image


# STEP 2: Create an HandLandmarker object.
base_options = python.BaseOptions(model_asset_path='C:/Users/kuaashish/Downloads/hand_landmarker.task')
options = vision.HandLandmarkerOptions(base_options=base_options,
                                       num_hands=2)
detector = vision.HandLandmarker.create_from_options(options)

# STEP 3: Load the input image.
image = mp.Image.create_from_file('C:/Users/kuaashish/Downloads/handtest.jpg')

# STEP 4: Detect hand landmarks from the input image.
detection_result = detector.detect(image)

# STEP 5: Process the classification result. In this case, visualize it.
annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)
cv2.imshow('',cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))
这是所有报错：
D:\py\Anaconda3\python.exe D:/OpenCV/三维人体姿态估计/test/test.py
Traceback (most recent call last):
&nbsp; File "D:\OpenCV\三维人体姿态估计\test\test.py", line 59, in <module&gt;
&nbsp; &nbsp; detector = vision.HandLandmarker.create_from_options(options)
&nbsp; File "D:\py\Anaconda3\lib\site-packages\mediapipe\tasks\python\vision\hand_landmarker.py", line 364, in create_from_options
&nbsp; &nbsp; return cls(
&nbsp; File "D:\py\Anaconda3\lib\site-packages\mediapipe\tasks\python\vision\core\base_vision_task_api.py", line 70, in __init__
&nbsp; &nbsp; self._runner = _TaskRunner.create(graph_config, packet_callback)
RuntimeError: Unable to open file at C:\Users\kuaashish\Downloads\hand_landmarker.task


进程已结束，退出代码为 1



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google/mediapipe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月4日(星期一) 晚上6:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google/mediapipe]  Unable to open file at \test\hand_landmarker.task (Issue #4983)





 
Hi @Jwh-serendipity,
 
Could you kindly provide the full error log from your system?
 
Thank you

**Comment by kuaashish** [comment]
Hi @julrog,

Can you confirm that you can fix this issue on your end? We attempted to resolve it using the command line, where it proved successful. It appears that the problem lies within the Anaconda Environment, specifically with file accessibility within Anaconda Environment. 

Thank you

**Comment by julrog** [comment]
I am not using an anaconda environment, but a virtual environment created with venv (`python -m venv env`). Pose models and everything work fine, just this custom model files can't be loaded and I could not find a way to work around it in the code. Access should also not be a problem. It just changes whatever path I define to an impossible path in the c-part of the mediapipe code (see my previous comment).

**Comment by schmidt-sebastian** [comment]
Can you load the model file manually for now and pass it via the ModelAssetBuffer? I need to debug this further. 

https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/core/base_options.py#L59

**Comment by MalshaDeZ** [comment]
I'm facing the same issue,

even though I follow the suggested solution to the dot, I'm getting the error 

RuntimeError: Unable to open file at C:\Users\Public\projects\test-project\venv\lib\site-packages/C:\Users\Public\projects\test-project\test\atoms\bodyfeatureextraction\resources\pose_landmarker_heavy.task, errno=22

this is the model path I'm giving
 model_path = "C:/Users/Public/projects/test-project/test/atoms/bodyfeatureextraction/resources/pose_landmarker_heavy.task"

Please help me with this, I'm having this will all my functionalities related to Mediapipe.

**Comment by amitduwal** [comment]
@MalshaDeZ How did you solve the path issue? I am using venv and encountering the same issue as you described.

**Comment by MalshaDeZ** [comment]
@amitduwal I just tried the suggested fix by @schmidt-sebastian , `which` loads the model to a buffer and loads it to the base options

 ```
// load the model file from path to a buffer
with open(path, 'rb') as file:
            model_data = file.read()

//pass it as model_asset_buffer
 options = ObjectDetectorOptions(
            base_options=BaseOptions(model_asset_buffer=model_data),
            max_results=5,
            running_mode=VisionRunningMode.IMAGE)
```

**Comment by amitduwal** [comment]
@MalshaDeZ Thannk you for your response.
I also solved it with
base_options=BaseOptions(model_asset_buffer = open(model_path, "rb").read()),

**Comment by gargivedpathak** [comment]
> I have a similar error on windows 11 python 3.9.2:
> 
> ```
> Unable to open file at d:\{...}\env\lib\site-packages/D:\{...}\models\gesture_recognizer.task, errno=22
> ```
> 
> Error thrown at
> 
> ```
>         base_options = python.BaseOptions(
>             model_asset_path='models/gesture_recognizer.task')
>         options = vision.GestureRecognizerOptions(
>             base_options=base_options)
>  --->   self.gesture = vision.GestureRecognizer.create_from_options(
>             options)
> ```
> 
> I suspect the same reason for this error. On python side the absolute path (via `os.path.abspath(self.model_asset_path)` in `BaseOptions`) is taken but somewhere deeper on the C side of the underlying code the path is again prepended with a path to my virtual environment with the parent location of the mediapipe package, which makes it impossible to find the model file.

hey did you resolve this?
