### ISSUE TITLE
如何使用GPU加速手部模型的检测？

### ISSUE THREAD

**Issue by Jwh-serendipity** [google/mediapipe#4984]
### MediaPipe Solution (you are using)

hand solution

### Programming language

Python

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

可以调用GPU提高模型检测的帧率

### Will this change the current API? How?

不知道

### Who will benefit with this feature?

不知道

### Please specify the use cases for this feature

使用GPU加速

### Any Other info

不知道

**Comment by kuaashish** [comment]
Hi @Jwh-serendipity,

To utilize GPU in Python with MediaPipe v0.10.8, start by installing the latest version of the MediaPipe package (0.10.8) using the command "pip install mediapipe." Next, specify the GPU as the delegate, as illustrated in the example provided for the face_landmarker in the BaseOptions. It's important to note that this functionality is currently supported only on macOS and Linux, not on other operating systems.

`base_options = python.BaseOptions(model_asset_path='face_landmarker_v2_with_blendshapes.task', delegate=python.BaseOptions.Delegate.GPU)
`

If you encounter any further issues, please inform us. Thank you!!

**Comment by maidang-zc** [comment]
> Hi @Jwh-serendipity,
> 
> To utilize GPU in Python with MediaPipe v0.10.8, start by installing the latest version of the MediaPipe package (0.10.8) using the command "pip install mediapipe." Next, specify the GPU as the delegate, as illustrated in the example provided for the face_landmarker in the BaseOptions. It's important to note that this functionality is currently supported only on macOS and Linux, not on other operating systems.
> 
> `base_options = python.BaseOptions(model_asset_path='face_landmarker_v2_with_blendshapes.task', delegate=python.BaseOptions.Delegate.GPU) `
> 
> If you encounter any further issues, please inform us. Thank you!!

RuntimeError: Service "kGpuService", required by node mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_core_inferencesubgraph__inferencecalculator__mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_core_inferencesubgraph__InferenceCalculator, was not provided and cannot be created: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300cCell Execution Error

mediapipe的0.10.18 版本，按照你给的方式修改后的报错

**Comment by zeruiz99** [comment]
same error as RuntimeError: Service "kGpuService"
anyone knows how to solve this?
