### ISSUE TITLE
"libmediapipe_tasks_vision_jni.so" not found

### ISSUE THREAD

**Issue by AkmalAfzal** [google/mediapipe#4987]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmediapipe_tasks_vision_jni.so" not found
    java.lang.Runtime.loadLibrary0(Runtime.java:1093)
    java.lang.Runtime.loadLibrary0(Runtime.java:1013)
    java.lang.System.loadLibrary(System.java:1664)
    com.google.mediapipe.tasks.vision.core.BaseVisionTaskApi.<clinit>(BaseVisionTaskApi.java:37)
    com.google.mediapipe.tasks.vision.facedetector.FaceDetector.createFromOptions(FaceDetector.java:142)
    com.ai.photolabz.utils.FaceDetectorHelper.setupFaceDetector(FaceDetectorHelper.kt:37)
    com.ai.photolabz.utils.FaceDetectorHelper.<init>(FaceDetectorHelper.kt:19)
    com.ai.photolabz.ui.activity.images.ImagesViewModel$detectorHelper$2.invoke(ImagesViewModel.kt:48)
    com.ai.photolabz.ui.activity.images.ImagesViewModel$detectorHelper$2.invoke(ImagesViewModel.kt:47)
    kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    com.ai.photolabz.ui.activity.images.ImagesViewModel.getDetectorHelper(ImagesViewModel.java:47)
    com.ai.photolabz.ui.activity.images.ImagesViewModel.access$getDetectorHelper(ImagesViewModel.java:26)
    com.ai.photolabz.ui.activity.images.ImagesViewModel$detectFacesOfRecent$2.invokeSuspend(ImagesViewModel.kt:161)
    kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:584)
    kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by kuaashish** [comment]
Hi @AkmalAfzal,


Could you kindly provide more details about your query? This includes the steps you are following from the documentation, the operating system you are using, the version of Android Studio, as well as the SDK and NDK versions. 

Additionally, could you specify whether you are attempting to run the example on a physical device or an emulator? We recommend filling out the [template](https://github.com/google/mediapipe/issues/new/choose) to ensure we receive comprehensive information and better understand the issue on our end.

Thank you

**Comment by AkmalAfzal** [comment]
Hi @kuaashish
Crash report on firebase so its mean it appear not on emulator device.
Target+compile SDk is 34 and min SDK is 24 
Gradle version is 8.0 and plugin version is 8.1.2
NDK versin is 3.22.1
Android Studio Version is Android Studio Giraffe|2023.3.1 patch 2

This problem occurs in production app. As i understand it may be due to proguard issue even i add proguard rules to keep classes accordingly.(mention in docs)
https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/framework/proguard.pgcfg
mentioned here.

**Comment by JenyaKirmiza** [comment]
the same issue on production 

<img width="548" alt="Image" src="https://github.com/user-attachments/assets/182e2cb3-e844-4ca5-931d-26c357d50bbb" />
<img width="548" alt="Image" src="https://github.com/user-attachments/assets/8213f339-6794-4775-b78f-d3e6d4f3d041" />

**Comment by marioortizmanero** [comment]
I'm also experiencing this issue in production:

```
 Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: library "libmediapipe_tasks_vision_jni.so" not found
java.lang.Runtime.loadLibrary0 (Runtime.java:1090)
```

```
Brand: Samsung
Model: Galaxy A13
Version: Android 14
```

I don't even minimize my output files.

**Comment by santosaprima** [comment]
also experiencing this issue in production
`dlopen failed: library "libmediapipe_tasks_vision_jni.so" not found`

happened on samsung galaxy A13 and other android devices with 32 bit arch
I think this happens after I updated to 0.10.26 last week to adhere to 16 KB requirement

upon analyzing the aab file, I noticed that libmediapipe_tasks_vision_jni.so is not included for 32-bit arch
<img width="293" height="602" alt="Image" src="https://github.com/user-attachments/assets/896a8bc6-99ab-4e69-9361-dbbc5e031a71" />

after updating to 0.10.26.1, the 32-bit .so file is now present.
<img width="299" height="635" alt="Image" src="https://github.com/user-attachments/assets/45d45136-0964-4654-ac8f-ec875082748b" />

<img width="855" height="212" alt="Image" src="https://github.com/user-attachments/assets/e1287a9c-ed46-49f3-aff9-b917e9be545c" />

**Comment by mehranali-dev** [comment]
the same issue on production.
MediaPipe 0.10.26.1

<img width="719" height="335" alt="Image" src="https://github.com/user-attachments/assets/8e2e4cb8-8897-490f-acf9-f24cb43e3f1e" />
