### ISSUE TITLE
How to make sure gesture recognition is running successfully on the gpu？

### ISSUE THREAD

**Issue by miscedence12** [google/mediapipe#4988]
Is there any flag to see if it's running successfully on the GPU? I've tried this many times and it eventually comes up Created TensorFlow Lite XNNPACK delegate for CPU. I use mediapipe 0.10.8

**Comment by miscedence12** [comment]
@kuaashish

**Comment by kuaashish** [comment]
Hi @miscedence12,

To utilize GPU in Python with MediaPipe v0.10.8, start by installing the latest version of the MediaPipe package (0.10.8) using the command "pip install mediapipe." Next, specify the GPU as the delegate, as illustrated in the example provided for the gesture recognition in the BaseOptions. It's important to note that this functionality is currently supported only on macOS and Linux, not on other operating systems.

`base_options = python.BaseOptions(model_asset_path='gesture_recognizer.task', delegate=python.BaseOptions.Delegate.GPU) `

This will guarantee that the example runs on the GPU. Additionally, If you encounter any further issues, please inform us.
 
Thank you!

**Comment by goldwater668** [comment]
@kuaashish 
I have installed and run the following code.
`import mediapipe as mp
  base_options = mp.tasks.BaseOptions(model_asset_path='gesture_recognizer.task',
                                        delegate=mp.tasks.BaseOptions.Delegate.GPU)
    mp_drawing = mp.solutions.drawing_utils
    mp_hands = mp.solutions.hands
    hands = mp_hands.Hands(
        static_image_mode=False,
        max_num_hands=1,
        min_detection_confidence=0.75,
        min_tracking_confidence=0.75)`


 If the following situation occurs, is it considered successful to run the GPU?
`WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1701070555.771645 2857028 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1701070555.796823 2857082 gl_context.cc:344] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 525.147.05), renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
`

 I'd also like to know how to stop the GPU, can you help?

**Comment by miscedence12** [comment]
@goldwater668 I've run it successfully, you can check if your tensorflow is calling the gpu properly，you can test as follow:

> import tensorflow as tf

> print(tf.test.is_gpu_available())

**Comment by goldwater668** [comment]
@miscedence12 
Do I need to install tensorflow?

**Comment by miscedence12** [comment]
@goldwater668 ,you need, you can use pip3 install mediapipe-model-marker,

**Comment by goldwater668** [comment]
@miscedence12 
tensorflow-gpu is True. When tensorflow is not installed, I see in nvidia-smi that the code is running on gpu. This has nothing to do with whether tensorflow is installed or not.

**Comment by miscedence12** [comment]
@goldwater668 Which version of mp are you using?

**Comment by goldwater668** [comment]
@miscedence12 0.10.8

**Comment by kuaashish** [comment]
Hi @miscedence12,

Could you please provide us with the complete example code or direct us to the relevant steps from documentation? This will help us better understand the issue from our end. Thank you

**Comment by miscedence12** [comment]
@kuaashish ,Yes,my pleasure,as follow:
# STEP 1: Import the necessary modules.
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import cv2
import time
import numpy as np
from mediapipe.framework.formats import landmark_pb2
from mediapipe import solutions
cap=cv2.VideoCapture("1.avi")

MARGIN=10
FONT_SIZE=1
HANDEDNESS_TEXT_COLOR=(88,205,54)
FONT_THICKNESS=1
def draw_landmarks_on_image(rgb_image, detection_result,fps):
  hand_landmarks_list = detection_result.hand_landmarks
  handedness_list = detection_result.handedness
  annotated_image = np.copy(rgb_image)

  # Loop through the detected hands to visualize.
  for idx in range(len(hand_landmarks_list)):
    hand_landmarks = hand_landmarks_list[idx]
    handedness = handedness_list[idx]

    # Draw the hand landmarks.
    hand_landmarks_proto = landmark_pb2.NormalizedLandmarkList()
    hand_landmarks_proto.landmark.extend([
      landmark_pb2.NormalizedLandmark(x=landmark.x, y=landmark.y, z=landmark.z) for landmark in hand_landmarks
    ])
    solutions.drawing_utils.draw_landmarks(
      annotated_image,
      hand_landmarks_proto,
      solutions.hands.HAND_CONNECTIONS,
      solutions.drawing_styles.get_default_hand_landmarks_style(),
      solutions.drawing_styles.get_default_hand_connections_style())

    # Get the top left corner of the detected hand's bounding box.
    height, width, _ = annotated_image.shape
    x_coordinates = [landmark.x for landmark in hand_landmarks]
    y_coordinates = [landmark.y for landmark in hand_landmarks]
    text_x = int(min(x_coordinates) * width)
    text_y = int(min(y_coordinates) * height) - MARGIN

    # Draw handedness (left or right hand) on the image.
    cv2.putText(annotated_image, f"{handedness[0].category_name}",
                (text_x, text_y), cv2.FONT_HERSHEY_DUPLEX,
                FONT_SIZE, HANDEDNESS_TEXT_COLOR, FONT_THICKNESS, cv2.LINE_AA)
    cv2.putText(annotated_image,"FPS:"+str(fps).split(".")[0],(10,30),cv2.FONT_HERSHEY_SIMPLEX,1.0,(255,0,0),2,cv2.LINE_AA)

  return annotated_image

model_path='/home/jie/mediapipe_test/hand_landmarker.task'
# cap=cv2.VideoCapture("/home/jie/video/output_right_line.avi")

# STEP 2: Create an HandLandmarker object.
base_options=mp.tasks.BaseOptions(model_asset_path=model_path,
                                    delegate=mp.tasks.BaseOptions.Delegate.GPU)
options = vision.HandLandmarkerOptions(base_options=base_options,
                                      running_mode=mp.tasks.vision.RunningMode.VIDEO,
                                       num_hands=2)
detector = vision.HandLandmarker.create_from_options(options)

# STEP 3: Load the input image.
while True:
    try:
      ret,frame=cap.read()
    except KeyboardInterrupt:
       break
    if not ret :
        break
    # cv2.imwrite("a.jpg",frame)
    

    # image = mp.Image.create_from_file("a.jpg")
    mp_image=mp.Image(image_format=mp.ImageFormat.SRGB,data=np.array(cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)))
    timestap=cap.get(cv2.CAP_PROP_POS_MSEC)
    # STEP 4: Detect hand landmarks from the input image.
    start_time=time.time()
    try:
      detection_result = detector.detect_for_video(mp_image,int(timestap))
    
    #   print(fps)
    except KeyboardInterrupt:
       break
    end_time=time.time()
    fps=1/(end_time-start_time)
    
    # print(detection_result)

    # STEP 5: Process the classification result. In this case, visualize it.
    annotated_image = draw_landmarks_on_image(mp_image.numpy_view(), detection_result,fps)
    cv2.imshow("frame",cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))
    key=cv2.waitKey(1)
    if key==27:
        exit
cv2.destroyAllWindows()

**Comment by miscedence12** [comment]
@kuaashish Yes, my pleasure, as follow:
`# STEP 1: Import the necessary modules.
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import cv2
import time
import numpy as np
from mediapipe.framework.formats import landmark_pb2
from mediapipe import solutions
cap=cv2.VideoCapture("1.avi")

MARGIN=10
FONT_SIZE=1
HANDEDNESS_TEXT_COLOR=(88,205,54)
FONT_THICKNESS=1
def draw_landmarks_on_image(rgb_image, detection_result,fps):
  hand_landmarks_list = detection_result.hand_landmarks
  handedness_list = detection_result.handedness
  annotated_image = np.copy(rgb_image)

  # Loop through the detected hands to visualize.
  for idx in range(len(hand_landmarks_list)):
    hand_landmarks = hand_landmarks_list[idx]
    handedness = handedness_list[idx]

    # Draw the hand landmarks.
    hand_landmarks_proto = landmark_pb2.NormalizedLandmarkList()
    hand_landmarks_proto.landmark.extend([
      landmark_pb2.NormalizedLandmark(x=landmark.x, y=landmark.y, z=landmark.z) for landmark in hand_landmarks
    ])
    solutions.drawing_utils.draw_landmarks(
      annotated_image,
      hand_landmarks_proto,
      solutions.hands.HAND_CONNECTIONS,
      solutions.drawing_styles.get_default_hand_landmarks_style(),
      solutions.drawing_styles.get_default_hand_connections_style())

    # Get the top left corner of the detected hand's bounding box.
    height, width, _ = annotated_image.shape
    x_coordinates = [landmark.x for landmark in hand_landmarks]
    y_coordinates = [landmark.y for landmark in hand_landmarks]
    text_x = int(min(x_coordinates) * width)
    text_y = int(min(y_coordinates) * height) - MARGIN

    # Draw handedness (left or right hand) on the image.
    cv2.putText(annotated_image, f"{handedness[0].category_name}",
                (text_x, text_y), cv2.FONT_HERSHEY_DUPLEX,
                FONT_SIZE, HANDEDNESS_TEXT_COLOR, FONT_THICKNESS, cv2.LINE_AA)
    cv2.putText(annotated_image,"FPS:"+str(fps).split(".")[0],(10,30),cv2.FONT_HERSHEY_SIMPLEX,1.0,(255,0,0),2,cv2.LINE_AA)

  return annotated_image

model_path='/home/jie/mediapipe_test/hand_landmarker.task'
# cap=cv2.VideoCapture("/home/jie/video/output_right_line.avi")

# STEP 2: Create an HandLandmarker object.
base_options=mp.tasks.BaseOptions(model_asset_path=model_path,
                                    delegate=mp.tasks.BaseOptions.Delegate.GPU)
options = vision.HandLandmarkerOptions(base_options=base_options,
                                      running_mode=mp.tasks.vision.RunningMode.VIDEO,
                                       num_hands=2)
detector = vision.HandLandmarker.create_from_options(options)

# STEP 3: Load the input image.
while True:
    try:
      ret,frame=cap.read()
    except KeyboardInterrupt:
       break
    if not ret :
        break
    # cv2.imwrite("a.jpg",frame)
    

    # image = mp.Image.create_from_file("a.jpg")
    mp_image=mp.Image(image_format=mp.ImageFormat.SRGB,data=np.array(cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)))
    timestap=cap.get(cv2.CAP_PROP_POS_MSEC)
    # STEP 4: Detect hand landmarks from the input image.
    start_time=time.time()
    try:
      detection_result = detector.detect_for_video(mp_image,int(timestap))
    
    #   print(fps)
    except KeyboardInterrupt:
       break
    end_time=time.time()
    fps=1/(end_time-start_time)
    
    # print(detection_result)

    # STEP 5: Process the classification result. In this case, visualize it.
    annotated_image = draw_landmarks_on_image(mp_image.numpy_view(), detection_result,fps)
    cv2.imshow("frame",cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))
    key=cv2.waitKey(1)
    if key==27:
        exit
cv2.destroyAllWindows()`

**Comment by kuaashish** [comment]
Hi @miscedence12,

I apologize for misunderstandings. Regarding your situation, could you please confirm if you can utilize MediaPipe on GPU? It seems that, based on @goldwater668, situation, Currently utilizing the legacy hand solution, which does not support GPU. @goldwater668, We recommend transitioning to the new Hand Task API, as per @miscedence12 [implementation](https://github.com/google/mediapipe/issues/4988#issuecomment-1827415696).

Thank you

**Comment by miscedence12** [comment]
@kuaashish Yes, I can confirm that. The output log as follw:
2023-11-27 17:49:41.342541: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1701078582.735469   12429 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1701078582.763792   12473 gl_context.cc:344] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 525.147.05), renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
INFO: Created TensorFlow Lite delegate for GPU.
FPS: 81.35748923458897
FPS: 205.6434595018631
FPS: 164.68917857703786
FPS: 179.45081932143927
FPS: 157.5443789204823
FPS: 159.88046047114432
FPS: 177.67957298991783

If i use cpu, the fps can be about 20

**Comment by kuaashish** [comment]
Hi @miscedence12,

Thank you for confirming. Could you please verify if the GPU issue has been successfully resolved on your end? If so, may we proceed to close the issue and mark it as resolved?

**Comment by kuaashish** [comment]
Hi @miscedence12,

Thank you for confirming. Since the issue has been resolved, may we proceed to close it and mark it as resolved?

**Comment by miscedence12** [comment]
@kuaashish  yes

**Comment by goldwater668** [comment]
@kuaashish There is no way to set the GPU switch directly from the import mediapipe in python. Is it necessary to go through such a big loop?
