### ISSUE TITLE
Can't build android projects using multi_hand_mobile_calculators

### ISSUE THREAD

**Issue by rami-alloush** [google/mediapipe#499]
Hi,
I've successfully built the Android Example of edge_detection, but when I tried to build the examples of **handtracking** or **multihandtracking** I keep getting the exact same error of
`AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "pcond" referenced by "/data/app/rmasoft.firstapp-2/lib/arm64/libmediapipe_jni.so"...`

I believe the error is directly related to the `"//mediapipe/graphs/hand_tracking:multi_hand_mobile_calculators",` dependency, as once I remove it I start getting different errors that makes sense.

The full error is 

```
--------- beginning of crash
03-06 17:54:29.632 10555 10555 E AndroidRuntime: FATAL EXCEPTION: main
03-06 17:54:29.632 10555 10555 E AndroidRuntime: Process: rmasoft.firstapp, PID: 10555
03-06 17:54:29.632 10555 10555 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "pcond" referenced by "/data/app/rmasoft.firstapp-2/lib/arm64/libmediapipe_jni.so"...
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at rmasoft.firstapp.MainActivity.<clinit>(MainActivity.java:34)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1072)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2454)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2626)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5740)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
03-06 17:54:29.632 10555 10555 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
```

I'm using `android-ndk-r18b` (I read it might be related) and I try to run the app on Android v6.0.

P.S. the apps works fine on the device when I download the pre-complied APK from here
https://github.com/google/mediapipe/blob/master/mediapipe/docs/hand_tracking_mobile_gpu.md#android

Thanks

**Comment by eknight7** [comment]
Hi, can you share which device you are building on? Also, are you able to build other apps like face detection/hair segmentation?

**Comment by rami-alloush** [comment]
Thanks @eknight7  for the reply. I'll close the issue as the problem is resolved.
I had made slight modifications to the Landmarks file to write them to a txt file, and that seemed to interfere with the Android build.
Commenting out these edits solved the problem, thanks again.

Modifications Source: https://github.com/rabBit64/Sign-language-recognition-with-RNN-and-Mediapipe

**Comment by teleger** [comment]
When building an AAR file, can you create and use openGL correctly? I tried many times, but I never succeeded, even though I was only part of the code for face detection. Right? Can you give me a hint? Thank you
