### ISSUE TITLE
Selfie Segmentation running slow on Android Device

### ISSUE THREAD

**Issue by roshanSpringCT** [google/mediapipe#4992]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android 13

### MediaPipe version

0.1.1675465747

### Solution

Selfie Segmentation

### Programming Language and version

Javascript

### Describe the actual behavior

I have integrated Selfie Segmentation model in React web app. When I am running web app on android device then after turning on video, app becomes very slow. I have tried both General and Landscape models, both are slow.

### Describe the expected behaviour

Selfie Segmentation model should not make app slow.

**Comment by kuaashish** [comment]
Hi @roshanSpringCT,

Could you please let us know the steps you're taking from the documentation to help us better understand and address the issue?

Thank you

**Comment by roshanSpringCT** [comment]
This is the code that I have
this is inline with the [code here](https://codepen.io/mediapipe/pen/wvJyQpq)

this._selfieSegmentation = new SelfieSegmentation({
            locateFile: (file) => `https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/${file}`,
        });
        this._selfieSegmentation.setOptions({
            modelSelection: 0,
            selfieMode: false,
        });
 navigator.mediaDevices.getUserMedia({ video: true, audio: false })
            .then(async stream => {
                this._videoElement.srcObject = stream;
                this._videoTrack = stream.getVideoTracks()[0];
                this._videoElement.onplaying = () => {
                    const trackProcessor = new MediaStreamTrackProcessor({ track: this._videoTrack });
                    const trackGenerator = new MediaStreamTrackGenerator({ kind: 'video' });
                    const transformer = new TransformStream({
                        transform: async (videoFrame, controller) => {
                            videoFrame.width = videoFrame.displayWidth;
                            videoFrame.height = videoFrame.displayHeight;
                            await this._selfieSegmentation.send({ image: videoFrame });
                            const timestamp = videoFrame.timestamp;
                            const newFrame = new VideoFrame(this._canvasElement, { timestamp });
                            videoFrame.close();
                            controller.enqueue(newFrame);
                        }
                    });
                    trackProcessor.readable.pipeThrough(transformer).pipeTo(trackGenerator.writable)
                    const processedStream = new MediaStream();
                    processedStream.addTrack(trackGenerator);
                    this._videoElement.srcObject = processedStream;
                };
                this._selfieSegmentation.onResults(this._onResultsBackgroundImageChange);
            });
      _onResultsBackgroundImageChange = (results) => {
        this._canvasContext.save();
        this._canvasContext.clearRect(0, 0, this._canvasElement.width, this._canvasElement.height);
        this._canvasContext.drawImage(results.segmentationMask, 0, 0, this._canvasElement.width, this._canvasElement.height);
        this._canvasContext.globalCompositeOperation = 'source-in';
        this._canvasContext.drawImage(results.image, 0, 0, this._canvasElement.width, this._canvasElement.height);
        this._canvasContext.globalCompositeOperation = 'destination-atop';
        this._canvasContext.drawImage(this._bgImage, 0, 0, this._canvasElement.width, this._canvasElement.height);
        this._canvasContext.restore();
    };
