### ISSUE TITLE
ValueError: Expected a model with a single subgraph, found 1.

### ISSUE THREAD

**Issue by Chetancool** [google/mediapipe#4996]
I have trained MOBILENET_V2 for object detection. But while running the model with media pipe python API, I am getting error as follows.

Traceback (most recent call last):
  File "MediaPipe_cv_objdetect_video.py", line 118, in <module>
    detector = vision.ObjectDetector.create_from_options(options)
  File "/home/.local/lib/python3.7/site-packages/mediapipe/tasks/python/vision/object_detector.py", line 211, in create_from_options
    packets_callback if options.result_callback else None)
  File "/home/.local/lib/python3.7/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 65, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
ValueError: Expected a model with a single subgraph, found 1.
FATAL: exception not rethrown
Aborted (core dumped).

**Comment by kuaashish** [comment]
Hi @Chetancool,

Kindly share additional details regarding the issue you are encountering. This includes information such as a reproducible code or steps as per documentation, the operating system in use, installed Python version, and Model Maker version. Providing this information will assist us in reproducing and comprehending the issue from our end. For your convenience, you may also utilize the [issue template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Amodelmaker&projects=&template=11-model-maker-issue-template.yaml) to furnish us with the necessary details.

Thank you

**Comment by Chetancool** [comment]
OS : Ubuntu 20.04.5
Python : 3.7.16
Mediapipe Version : 0.9.0.1
Task : Object Detection

**Code:**
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
modelpath = 'MOBILENET_MULTI_AVG.tflite'

VisionRunningMode = mp.tasks.vision.RunningMode
base_options = python.BaseOptions(model_asset_path=modelpath)
options = vision.ObjectDetectorOptions(base_options=base_options,
                                       running_mode=VisionRunningMode.LIVE_STREAM,
                                       score_threshold=0.5,
                                       result_callback= print_result)

detector = vision.ObjectDetector.create_from_options(options)

**Error:**

Traceback (most recent call last):
  File "MediaPipe_cv_objdetect_video.py", line 118, in <module>
    detector = vision.ObjectDetector.create_from_options(options)
  File "/home/.local/lib/python3.7/site-packages/mediapipe/tasks/python/vision/object_detector.py", line 211, in create_from_options
    packets_callback if options.result_callback else None)
  File "/home/.local/lib/python3.7/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 65, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
**ValueError: Expected a model with a single subgraph, found 1.**
FATAL: exception not rethrown
Aborted (core dumped)

**Model:**
https://drive.google.com/file/d/1Z9kwbqW-G_hPVWtC7vdWmReNcg-g96Uw/view?usp=sharing

**Comment by kuaashish** [comment]
Hi @Chetancool,

It appears that an error is occurring due to the use of Python Version 3.7.16, which is not supported. The recommended versions of Python are 3.8 to 3.11, as specified in the Python Setup [documentation](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions). Additionally, we have a more recent version of MP, namely 0.10.8. Kindly ensure that you are using a supported Python Version and attempt to build with the newer version 0.10.8. Please inform us if you encounter a similar error while running the example.

Thank you

**Comment by kuaashish** [comment]
Hi @Chetancool,

Could you kindly review the previous comment, implement the suggested recommendations, and inform us if the issue persists on your end?

Thank you

**Comment by Chetancool** [comment]
Hi @kuaashish issue has been resolved. Thank you for your fruitful response.
