### ISSUE TITLE
Pose Landmarks Jitter

### ISSUE THREAD

**Issue by leonidasavila** [google/mediapipe#4997]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 11

### Python Version

3.11

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose Landmark Detection

### Describe the actual behavior

The pose estimation in video has to much jittering

### Describe the expected behaviour

Stables landmarks to calculate human pose degrees

### Standalone code/steps you may have used to try to get what you need

```shell
import cv2
import mediapipe as mp
import numpy as np
from math import acos, degrees

mp_pose = mp.solutions.pose

mp_drawing = mp.solutions.drawing_utils

cap = cv2.VideoCapture("newsan.mp4")

with mp_pose.Pose(
    static_image_mode = False) as pose:

        while True: 
            ret, frame = cap.read()
            if ret == False:
                break
                
            #modificamos los fotogramas a RGB p/leer los puntos
            height, width, _ = frame.shape
            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            results = pose.process(frame_rgb)
            
            if results.pose_landmarks is not None:
                
                #lectura de puntos seeccionados
                x1 = int(results.pose_landmarks.landmark[16].x * width)
                y1 = int(results.pose_landmarks.landmark[16].y * height)

                x2 = int(results.pose_landmarks.landmark[14].x * width)
                y2 = int(results.pose_landmarks.landmark[14].y * height)

                x3 = int(results.pose_landmarks.landmark[12].x * width)
                y3 = int(results.pose_landmarks.landmark[12].y * height)
                
                x4 = int(results.pose_landmarks.landmark[11].x * width)
                y4 = int(results.pose_landmarks.landmark[11].y * height)
                
                x5 = int(results.pose_landmarks.landmark[13].x * width)
                y5 = int(results.pose_landmarks.landmark[13].y * height)
                
                x6 = int(results.pose_landmarks.landmark[15].x * width)
                y6 = int(results.pose_landmarks.landmark[15].y * height)
               
                cv2.circle(frame, (x1, y1), 6, (0, 255, 255), 4)
                cv2.circle(frame, (x2, y2), 6, (0, 255, 255), 4)
                cv2.circle(frame, (x3, y3), 6, (0, 255, 255), 4)
                cv2.circle(frame, (x4, y4), 6, (0, 255, 255), 4)
                cv2.circle(frame, (x5, y5), 6, (0, 255, 255), 4)
                cv2.circle(frame, (x6, y6), 6, (0, 255, 255), 4)

                p1 = np.array([x4, y4])
                p2 = np.array([x5, y5])
                p3 = np.array([x6, y6])

                l1 = np.linalg.norm(p2 - p3)
                l2 = np.linalg.norm(p1 - p3)
                l3 = np.linalg.norm(p1 - p2)

                angle = degrees(acos((l1**2 + l3**2 - l2**2) / (2 * l1 * l3)))

                cv2.line(frame, (x1, y1), (x2, y2), (255, 255, 255), 3)
                cv2.line(frame, (x2, y2), (x3, y3), (255, 255, 255), 3)
                cv2.line(frame, (x3, y3), (x4, y4), (255, 255, 255), 3)
                cv2.line(frame, (x4, y4), (x5, y5), (255, 255, 255), 3)
                cv2.line(frame, (x5, y5), (x6, y6), (255, 255, 255), 3)
                cv2.putText(frame, str(int(angle)), (x5 + 30, y5), 1, 1.5, (128, 0, 250), 2)

            cv2.imshow("Frame", frame)
            if cv2.waitKey(1) & 0xFF == 27:
                break
cap.release()
cv2.destroyAllWindows()
```

**Comment by leonidasavila** [comment]
Hi @kuaashish for your quick answer. 

I will make the change to use the API solution and I will give you feedback with the results. 

I'm asume that i will can use specifically points of landmarks ¿This is correct?

**Comment by leonidasavila** [comment]
@kuaashish can you provide me a guide to access a specific landmarks 

I was able to access to default points but i need to read some points 

Thanks

**Comment by kuaashish** [comment]
Hi @leonidasavila,

Could you please specify the landmarks you are targeting and attempting to incorporate for your particular use case?

Thank you

**Comment by leonidasavila** [comment]
Hi @kuaashish, 

Of course. The specify landmarks are: right shoulder, right elbow, right wrist.

Thanks for the example.

**Comment by leonidasavila** [comment]
Hi @kuaashish , i couldn't found any guide to access a particular landmark using the new API with python. 

I'll appreciate your help, thanks

**Comment by kuaashish** [comment]
Hi @leonidasavila,

It appears that you've initiated a new issue, #5023, regarding the recent query we discussed. We've escalated it to the appropriate point of contact and anticipate receiving guidance shortly. In the meantime, we kindly request your attention to the newly raised issue. Your assistance in marking this issue as resolved and closing the status is appreciated.

Thank you

**Comment by leonidasavila** [comment]
Thank yo @kuaashish for your help

**Comment by devanseai** [comment]
I was using mediapipe for pose estimation on two camera video streams which were getting processed in the same while loop. It was working fine and the post output was quite good for both streams. I had mediapipe 0.8.14 installed on my compute since past 2 years. I accidently updated the mediapipe solution and since then my pose estimation output on both streams is FULL of jitters. I am not getting good ouput on either of the streams. When I test the pose output on one vide stream it works very well!

However when I run it on 2 video streams. It is a disaster. I am using exactly same cameras for both feeds.

Can anyone help with this? 

How can I solve this issue using the mediapipe==0.10.14

If not possible, how can I restore mediapipe==0.8.14?
