### ISSUE TITLE
GPU doesn't get enabled for Face Landmark detection on web

### ISSUE THREAD

**Issue by c4b4d4** [google/mediapipe#4998]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

macOS Sonoma 14.0

### Browser and version if the issue happens on browser

Google Chrome 119.0.6045.159

### Programming Language and version

JavaScript

### MediaPipe version

Have ran it using 0.10.8, the [codepen](https://codepen.io/mediapipe-preview/pen/OJBVQJm) uses a lower version but also happens

### Solution

Face Landmark

### Describe the actual behavior

GPU not enabled, even when set

### Describe the expected behaviour

GPU should be used

### Standalone code/steps you may have used to try to get what you need

It can be replicate it in the [codepen](https://codepen.io/mediapipe-preview/pen/OJBVQJm) shared by the online guide.

<img width="692" alt="Screenshot 2023-11-14 at 11 05 59 p m" src="https://github.com/google/mediapipe/assets/375183/a4cfe703-2c61-47fc-ac1d-4d5cfc35c1f9">

In my case, this is how I init it:

FaceLandmark = await TasksVision.FaceLandmarker.createFromOptions(
TasksVision.vision,
{
	baseOptions: {
modelAssetPath: "/neural/face/face_landmarker.task",
delegate: "GPU"
	},
	runningMode: "VIDEO",
	outputFaceBlendshapes:true,
	outputFacialTransformationMatrixes:true,
	numFaces: 1
});
```

**Comment by xieleo5** [comment]
Same issue for python here. Even if I choose delegate: GPU, the model is still loaded to the CPU. Only FaceMesh has this problem, the pose and hand detection are all correct.

**Comment by kuaashish** [comment]
Hi @c4b4d4,

This behavior is anticipated. The CPU and GPU are both employed for the GPU delegate. To confirm GPU utilization, compare model performance. Models supporting GPU should exhibit a notable speed increase. For further clarification, refer to the related [issue](https://github.com/google/mediapipe/issues/4711).

Thank you

**Comment by pruthvik-sheth** [comment]
Is this issue resolved by anyone? I am having the exact same problem. Also @c4b4d4 , as you have implemented using the tasks-vision, do you have any idea how to close the predictions from the model without unloading and reloading the model. Because, when I do `handlandMarker.close()` my browser tab freezes and the console reads `successfully destroyed WebGL context`. I can't find the solution anywhere. If someone knows how to solve this would be of great help. Thanks
