### ISSUE TITLE
mediapipe ios build fails

### ISSUE THREAD

**Issue by yearofthewhopper** [google/mediapipe#50]
**Hi**

the configuration file on each of the iOs examples points to a 9.3sdk / 10.0sdk simulator forcing a build-from-bazel to fail. The resulting errors in the configuration file being set wrong are multiple calls like this while bazel is building:

`AVDepthData.h:75:12: note: 'AVDepthData' has been marked as being introduced in iOS 11.0 here, but the deployment target is _iOS 10.0.0_
@interface AVDepthData : NSObject`

**also** while bazel is looking for the mobileprovisions file it has a cert-fail. The mobileprovisions also checks for a app identifier through bazel which also causes it to fail while looking for an app identifier namespace like "com.google.mediapipe.handtrackinggpu" instead of the user's *app identifier or allowing the user to set their own. 

This makes your examples/ios completely un-workable.

#43 reflects this confusion as well

Please fix or update your documentation to reflect these errors.

**Comment by mgyong** [comment]
@camillol @jiuqiant 
Camillol - Can you kindly take a look at this?

**Comment by DokRaphael** [comment]
It worked for me by changing "com.google.mediapipe.handtrackinggpu" with my identifier in BUILD file in /mediapipe/examples/ios/handtrackinggpu/BUILD

**Comment by yearofthewhopper** [comment]
> It worked for me by changing "com.google.mediapipe.handtrackinggpu" with my identifier in BUILD file in /mediapipe/examples/ios/handtrackinggpu/BUILD

this was the first thing i tried and it didn't work for me for python 3 / xcode 10.3

**Comment by DokRaphael** [comment]
I've also created a provisioning profile with my identifier name and put it in the handtrackinggpu folder

**Comment by yearofthewhopper** [comment]
Yep I did this also and it didn’t work. :) but thank you for the suggestion!

**Comment by jiuqiant** [comment]
yearofthewhopper@, may I know your current issue? Is it still a cert-fail with DokRaphael @'s solution?
It would be helpful if you can provide the detailed error info. Thanks.

**Comment by jiuqiant** [comment]
yearofthewhopper@,  thanks for providing the information.
If I understand your comment correctly, you are able to build `HandDetectionGpuApp.ipa` by running ` bazel build -c opt --config=ios_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu`. If that's the case, the mobileprovision file issue is no longer a problem.

Then, your problem is that xcode crashes when you run the .ipa in the simulator? I guess that's expected because the .ipa is for arm64, not for x86_64. Have you tried installing the app to a real device?

**Comment by yearofthewhopper** [comment]
I don't understand the expected workflow once you get the IPA. How can you get the app onto your phone if XCode crashes? seems kinda like a chicken and the egg situation here. So, yes I am trying to send it to my device but without it loading in Xcode I don't understand how that's possible. I am not trying to run it on simulator that would be pointless I don't know why you'd assume I was trying to do this?

**Comment by jiuqiant** [comment]
Once Bazel builds the IPA, you use Xcode to upload it to the device. In our [instruction](https://mediapipe.readthedocs.io/en/latest/mediapipe_ios_setup.html#building-an-ios-app-from-the-command-line), there are two steps you need to do with Xcode after the IPA is successfully built by Bazel:
Step 3 In Xcode, open the Devices and Simulators window (command-shift-2).
Step 4 Make sure your device is connected. You will see a list of installed apps. Press the “+” button under the list, and select the .ipa file built by Bazel.
I don't think step 3 will crash anything. Do you see the crash in step 4?

**Comment by yearofthewhopper** [comment]
yes this is the point. The IPA causes a crash of Xcode on load. I have read the instructions multiple times, though I appreciate you walking through the steps!

**Comment by mgyong** [comment]
@yearofthewhopper We are unable to replicate the crash on Xcode when loading IPA. It has worked for us on Xcode 10.2.1. Closed this issue for now until more info is provided
