### ISSUE TITLE
Access landmark data on web

### ISSUE THREAD

**Issue by jackz314** [google/mediapipe#500]
I know that the official APIs for JavaScript hasn't come out yet, but I really wanted to try it out in my project so I replicated the [web demo](https://storage.googleapis.com/mediapipe-viz.appspot.com/wasm-demos/hand-tracking-simd/hand_tracking_demo.html) locally. The demo works but I can't figure out how to access the landmark data, it seems that the only data the WebAssembly process function call returns is the millisecond per frame info. Can someone point me to the source of the process call? I wanna see if I can pass back landmark data there as well. IIRC the function involved is `_processGl` (passthrough) and `_process` (direct, I can't get this one to work though). I wonder if something like setting up an output stream poller is possible in this context (this exists in the C++ API).

On a related note, is there an ETA for when the web APIs will be ready? Trying things out based on the demo is pretty restricted and difficult.

**Comment by tyrmullen** [comment]
There is currently no nice way to retrieve the landmark data alone.  The graphs being used for most of our web demos only have a single output stream, which is of type GpuBuffer.  So all of the rendering and processing work is being done fully inside the MediaPipe graph, and the only output stream to observe is the final image to be rendered to canvas/screen.

Those two process calls you mentioned are not meant to be used externally yet, and are therefore extremely inflexible.  In fact, _process was just the CPU/ImageFrame analog for _processGl, used initially for GPU-free testing.

There is no official ETA yet, but I've already started working on the web API, and expect to have some better time estimates in the next week or two.

**Comment by FashengChen0622** [comment]
I had the same problem, but I figure out a way to solve.
The Core thinking is “poller.QueueSize() will show the remaining data in the poller.”.
Since image output always exists, you can using a image poller to poll image.
After polling image data, the landmark poller must be updated: using poller_landmark.QueueSize() to verify whether there is landmark is detected( queue size > 0 means there is nough landmark data to read )

**Comment by tyrmullen** [comment]
For web, the now-released MediaPipe JavaScript Pose, FaceMesh, Hands, and Holistic APIs all return landmark information.  For more information (and live CodePen examples) see https://google.github.io/mediapipe/getting_started/javascript.
