### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by zoroxide** [google/mediapipe#5004]
### OS Platform and Distribution

windows 10 64bit

### Programming Language and version

python 3

### Installed using virtualenv? pip? Conda?(if python)

pip

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.8

### Describe the problem

when I am installing the package with "pip install mediapipe", pip shows me this error

### Complete Logs

```shell
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

**Comment by kuaashish** [comment]
Hi @zoroxide,

Can you confirm that you are utilizing a supported version of Python, specifically between 3.8 and 3.11, as indicated in the [provided guidance](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions) for Python Setup? The description provided does not clearly specify the version of Python in use.

Thank you
