### ISSUE TITLE
AAR problem with support for specific android architecture

### ISSUE THREAD

**Issue by momo1986** [google/mediapipe#501]
AAR external/maven/v1/https/jcenter.bintray.com/com/serenegiant/uvccamera/libuvccamera/1.2.0/libuvccamera-1.2.0.aar missing native libs for requested architecture: arm64-v8a

This blocks the support for android compilation.

How can I resolve it?

Regards!

**Comment by momo1986** [comment]
Actually, two maven artifact exists:
com/serenegiant/uvccamera/libuvccamera/1.2.0
com/serenegiant/uvccamera/libuvccameras/0.0.2.

Will it have conflict?

The issue always happens, since BUILD script is a little different from build.graddle. Some compilation is not very convenient.

**Comment by momo1986** [comment]
If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.

**Comment by jiuqiant** [comment]
Hi, I downloaded libuvccamera-1.2.0.aar and took a close look at its jni directory:
![Screen Shot 2020-03-09 at 10 41 43 AM](https://user-images.githubusercontent.com/3359144/76241834-d878d980-61f2-11ea-99d6-8f87f807e2b0.png)
As you can see, libuvccamera-1.2.0.aar only has armeabi directory. However, MediaPipe generally needs the armeabi-v7a and arm64-v8a directory when we build the Android mobile apps with config=android_arm or config=android_arm64. For example, if you take a look at MediaPipe's AARs, you can find armeabi-v7a and arm64-v8a subdirectories in its jni dir:
![Screen Shot 2020-03-09 at 10 42 10 AM](https://user-images.githubusercontent.com/3359144/76242709-61444500-61f4-11ea-9f0e-2afdc77fa1e1.png)
[Here](https://miro.medium.com/max/1965/1*zbA1QpOCt9t_zwcyXJBM8Q.png) is a good table to understand ABI. Hope this helps.
