### ISSUE TITLE
change the Category allowlist property

### ISSUE THREAD

**Issue by SeaLu** [google/mediapipe#5011]
### Description of issue (what needs changing)

When  we create a object, the object's class is mediapipe.tasks.python.vision.GestureRecognizerOptions, how to change the custom_gesture_classifier_options

### Clear description

let the user modify the Category allowlist according to their needs

**Comment by kuaashish** [comment]
Hi @SeaLu,

Could you provide more details about the use case you want? Also, let us know the specific support you need from us to assist you better.

Thank you
