### ISSUE TITLE
Background do not have a sufficient contrast ratio for "Learn More" text

### ISSUE THREAD

**Issue by abhishekjani08** [google/mediapipe#5014]
Description:
The "Learn More" text on the Mediapipe website is experiencing a contrast ratio issue, making it difficult for users to read. This issue was identified using Google Chrome version 119.0.6045.200, and it has been confirmed through a Lighthouse screenshot.

Details:
- Browser Version: Chrome 119.0.6045.200
- Affected Element: "Learn More" text on the website

Screenshot of lighthouse:
![image](https://github.com/google/mediapipe/assets/88500027/75854973-dd9b-4ca0-aee3-c60686b278d5)
in the section of:
![image](https://github.com/google/mediapipe/assets/88500027/2a399b4e-5a3c-43d3-951a-ea474e7a92bc)

Proposed Solution:
Adjust the background of the "Learn More" text to achieve a sufficient contrast ratio, ensuring better readability for users.

Steps to Reproduce:

1. Open the Mediapipe website in Google Chrome version 119.0.6045.200.
2. Navigate to the section containing the "Learn More" text.
3. Observe the contrast ratio between the text and its background.

We can make it darker to level up the contrast ratio with the background.

**Comment by kuaashish** [comment]
Hi @abhishekjani08,

We are having trouble understanding the issue fully. Can you please give more details or share steps so we can reproduce the problem and understand it better?

Thank you

**Comment by kuaashish** [comment]
Hi @abhishekjani08,

Can you please check again? Our team has fixed it now, as shown in the attached screenshot below:

<img width="1415" alt="Screenshot 2024-01-17 at 09 40 01" src="https://github.com/google/mediapipe/assets/98159216/67c35431-5c7f-4476-ae3b-7a0c27fc433e">

Thank you

**Comment by abhishekjani08** [comment]
Yes @kuaashish , now even i think the issue has been resolved by the team! Great🚀

**Comment by kuaashish** [comment]
Hi @abhishekjani08,

Thank you for the confirmation, Can now mark this issue resolved and close the status?

**Comment by abhishekjani08** [comment]
Yes sure @kuaashish ,
Thankyou!✨🚀
