### ISSUE TITLE
MacOS14.2  M1  can't install mediapipe 0.10.8

### ISSUE THREAD

**Issue by h3clikejava** [google/mediapipe#5015]
### OS Platform and Distribution

MacOS14.2

### Programming Language and version

python 3.7/3.10

### Installed using virtualenv? pip? Conda?(if python)

pip install mediapipe==0.10.8

### MediaPipe version

0.10.8

### Android AAR (if android)

None

### Describe the problem

(py310)h3c-2:~ h3c$ pip install mediapipe==0.10.8 ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.8 (from versions: 0.8.9.1, 0.8.10, 0.8.10.1, 0.8.11, 0.9.0, 0.9.0.1, 0.9.1.0) ERROR: No matching distribution found for mediapipe==0.10.8

### Complete Logs

```shell
I can install 0.9.1.0,but 0.10.x can't
```

**Comment by h3clikejava** [comment]
![image](https://github.com/google/mediapipe/assets/4688773/253e2f10-bb19-461e-beb9-5a9a814de09a)
![image](https://github.com/google/mediapipe/assets/4688773/ddf958e4-d3b8-452f-9d8a-d6b6337a1765)

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

Could you please have a look into this issue? Thank you

**Comment by schmidt-sebastian** [comment]
I am able to install the package on Ventura:  

```
$ python3 --version
Python 3.10.11
$ pip3 install mediapipe==0.10.8
Collecting mediapipe==0.10.8
  Downloading mediapipe-0.10.8-cp310-cp310-macosx_11_0_universal2.whl (47.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.0/47.0 MB 32.3 MB/s eta 0:00:00
Collecting protobuf<4,>=3.11
  Using cached protobuf-3.20.3-py2.py3-none-any.whl (162 kB)
Collecting sounddevice>=0.4.4
  Using cached sounddevice-0.4.6-py3-none-macosx_10_6_x86_64.macosx_10_6_universal2.whl (107 kB)
Collecting flatbuffers>=2.0
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Collecting opencv-contrib-python
  Using cached opencv_contrib_python-4.8.1.78-cp37-abi3-macosx_11_0_arm64.whl (41.4 MB)
Collecting absl-py
  Using cached absl_py-2.0.0-py3-none-any.whl (130 kB)
Collecting matplotlib
  Downloading matplotlib-3.8.2-cp310-cp310-macosx_11_0_arm64.whl (7.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 29.3 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.26.2-cp310-cp310-macosx_11_0_arm64.whl (14.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 31.5 MB/s eta 0:00:00
Collecting attrs>=19.1.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting CFFI>=1.0
  Downloading cffi-1.16.0-cp310-cp310-macosx_11_0_arm64.whl (176 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.8/176.8 kB 771.8 kB/s eta 0:00:00
Collecting fonttools>=4.22.0
  Downloading fonttools-4.46.0-cp310-cp310-macosx_10_9_universal2.whl (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 26.7 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.4.5-cp310-cp310-macosx_11_0_arm64.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.2/66.2 kB 7.1 MB/s eta 0:00:00
Collecting contourpy>=1.0.1
  Downloading contourpy-1.2.0-cp310-cp310-macosx_11_0_arm64.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.2/242.2 kB 17.5 MB/s eta 0:00:00
Collecting pillow>=8
  Downloading Pillow-10.1.0-cp310-cp310-macosx_11_0_arm64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 25.8 MB/s eta 0:00:00
Collecting packaging>=20.0
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting pyparsing>=2.3.1
  Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Collecting cycler>=0.10
  Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: flatbuffers, six, pyparsing, pycparser, protobuf, pillow, packaging, numpy, kiwisolver, fonttools, cycler, attrs, absl-py, python-dateutil, opencv-contrib-python, contourpy, CFFI, sounddevice, matplotlib, mediapipe
Successfully installed CFFI-1.16.0 absl-py-2.0.0 attrs-23.1.0 contourpy-1.2.0 cycler-0.12.1 flatbuffers-23.5.26 fonttools-4.46.0 kiwisolver-1.4.5 matplotlib-3.8.2 mediapipe-0.10.8 numpy-1.26.2 opencv-contrib-python-4.8.1.78 packaging-23.2 pillow-10.1.0 protobuf-3.20.3 pycparser-2.21 pyparsing-3.1.1 python-dateutil-2.8.2 six-1.16.0 sounddevice-0.4.6

[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
```

Will try with Sonoma soon.

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

MP 0.10.9 build appears to be compatible with macOS Intel using Sonoma 14.2 and Python 3.11. I have attached a screenshot for your reference. @h3clikejava, could you please try using Python 3.11 as well? Currently, we believe the issue does not look's like from our end. It is possible that there might be a blockage on your system, although we are not certain at this time. 

<img width="1792" alt="Screenshot 2023-12-18 at 12 01 18" src="https://github.com/google/mediapipe/assets/98159216/a3c807d5-581f-4ce1-9edf-acfd5268acd9">


Kindly inform us of any further status. If we obtain an M1 device with upgraded 14.2, we will attempt to replicate the issue.

Thank you

**Comment by h3clikejava** [comment]
![image](https://github.com/google/mediapipe/assets/4688773/6af99141-62bf-4a40-9f75-c6c07ef29c08)
![image](https://github.com/google/mediapipe/assets/4688773/559c6ced-7249-40b6-ac45-fbbe68fb9472)

M1 still cannot be installed 0.10.8 using python3.11

**Comment by schmidt-sebastian** [comment]
Sorry - even on mac OS 14.2.1 I am unable to reproduce this issue. Can you try to download and install this file directly: https://files.pythonhosted.org/packages/a3/3a/f309c6bdebe596cc8c960542e167331cb01ef130ec38f3da46a499718889/mediapipe-0.10.9-cp311-cp311-macosx_11_0_universal2.whl ? Thanks.

**Comment by JuanMorenoS** [comment]
Hello! Any update :) ?
