### ISSUE TITLE
Is body landmarks based segmentation mask no longer supported?

### ISSUE THREAD

**Issue by Setsukyo** [google/mediapipe#5016]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

iOS 14.1.2

### MediaPipe version

0.9.1.0

### Solution

Pose

### Programming Language and version

Python

### Describe the actual behavior

I hope to get human's contour by using the landmark based segementation. Meanwhile, I cannot install any version later than 0.9.1.0

### Describe the expected behaviour

I got error saying: "AttributeError: module 'mediapipe.tasks.python.vision' has no attribute 'PoseLandmarkerOptions'. Did you mean: 'FaceLandmarkerOptions'?"

### Standalone code/steps you may have used to try to get what you need

```shell
import time
import cv2
import numpy as np
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
from mediapipe.framework.formats import landmark_pb2
from mediapipe import solutions

# Create an PoseLandmarker object.
base_options_PL = python.BaseOptions(model_asset_path="pose_landmarker.task")
options_PL = vision.PoseLandmarkerOptions(base_options=base_options_PL, output_segmentation_masks=True)
detector_PL = vision.PoseLandmarker.create_from_options(options_PL)
```

**Comment by kuaashish** [comment]
Hi @Setsukyo,

In version 0.9.1.0, it seems that the 'PoseLandmarkerOptions' module was not accessible at a specific moment. The Pose Landmarker Python task was introduced starting from [v0.10.0](https://github.com/google/mediapipe/releases/tag/v0.10.0) (refer to the Python release update). This might be the reason why v0.9.1.0 is unable to import the 'PoseLandmarkerOptions' module.

To address this issue, consider upgrading to version 0.10.0 or a later release. If you encounter difficulties to install later version of MediaPipe, please provide additional following details for further investigation and support. if necessary, We will fix the issue internally if genuine bug. 

- Please provide details on the steps you are following from the documentation or the specific command used for installing Mediapipe.

- Indicate whether your macOS is Intel-based or Silicon chip-based, specifying the macOS version (e.g., macOS Sonoma 14.1.1). If it is an Intel-based processor, please specify the type (e.g., i5, i7, i9). If it is Silicon chip-based, mention whether it is M1 or M2.

- Confirm the Python version in use. Note that supported Python versions range from 3.8 to 3.11 (refer to the Python [Step](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions) for more information).

- Include the complete error logs for a thorough analysis.

Thank you

**Comment by kuaashish** [comment]
Hi @Setsukyo,

I successfully installed MP version 0.10.8 on my colleague's MacBook Pro M1, using Python Version 3.10 and macOS 14.1.2. It's functioning properly, and I've attached a screenshot for your reference, including other version details.

![image](https://github.com/google/mediapipe/assets/98159216/cfe49b06-c836-493a-9f8a-7ca7c83bceb6)


Could you kindly reinstall MP with Python Version 3.10 or any supported version between 3.9 and 3.11? This will help us determine if the issue persists. Currently, it seems unlikely that the problem is on MP's side. Additionally, please confirm whether the Python Version in use is 32-bit or 64-bit, as MP supports Python 64-bit.

Thank you

**Comment by Setsukyo** [comment]
Hi @kuaashish 
I attached my Python version and the issue I encountered below.
![InstallMPIssue01](https://github.com/google/mediapipe/assets/46248203/a810751b-bd15-4778-b8a3-976fbb9527eb)
However, I just realized maybe the conda environment caused the issue. I deactivated the conda environment and managed to install versions 0.10.0 and 0.10.8. However, so far, I cannot get a version later than 0.9.1.0 installed under my conda environment. My conda version is 23.1.0

Moreover, even though I can install versions 0.10.0 and 0.10.8, I cannot get the function "vision.PoseLandmarkerOptions(base_options=base_options_PL, output_segmentation_masks=True)" work. It worked with my last version of installations. Acctually, I had it worked 5 days ago.
I appreciate any suggestions.

**Comment by kuaashish** [comment]
Hi @Setsukyo,

The function "vision.PoseLandmarkerOptions(base_options=base_options_PL, output_segmentation_masks=True)" has been successfully imported with v0.10.9, and the entire example is operational. Please refer to the attached GitHub [Gist](https://colab.sandbox.google.com/gist/kuaashish/eb7854fed18bcde391bb9abb8612ee86/5016.ipynb) for further details. Kindly confirm whether you are following the provided [Colab example](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/pose_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Pose_Landmarker.ipynb). If not, please ensure that you follow the same example, and you should observe the proper importation of the function and the successful execution of the example as expected.

Thank you

**Comment by Setsukyo** [comment]
Hi @kuaashish,
Thank you!
I did follow the Colab examples, and everything worked well. It turned out that the function was suddenly not working on my local pc. I will update to v0.10.9 and retry. Thank you for helping me.
Bests.

**Comment by kuaashish** [comment]
Hi @Setsukyo,

Thank you for the update, Could you please let us know if now this is no longer issue from your end, Can we go ahead and close the issue with resolved status.

**Comment by ErikValle2** [comment]
> Hi @Setsukyo,
> 
> I successfully installed MP version 0.10.8 on my colleague's MacBook Pro M1, using Python Version 3.10 and macOS 14.1.2. It's functioning properly, and I've attached a screenshot for your reference, including other version details.
> 
> ![image](https://private-user-images.githubusercontent.com/98159216/289804829-cfe49b06-c836-493a-9f8a-7ca7c83bceb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NTk2OTgsIm5iZiI6MTcyODQ1OTM5OCwicGF0aCI6Ii85ODE1OTIxNi8yODk4MDQ4MjktY2ZlNDliMDYtYzgzNi00OTNhLTlmOGEtN2NhN2M4M2JjZWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA3MzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNzY1NDdmZTllYWIzMDZiMThkODVlNWNiN2Y4MzUzZGYxYjM4YTRhMGNlMjFiYzEwZTdiNTQ1MWRhNDI5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VkNP2r32HICabYw6umV3YNXF7xuEYqha1JCGD7O-0LA)
> 
> Could you kindly reinstall MP with Python Version 3.10 or any supported version between 3.9 and 3.11? This will help us determine if the issue persists. Currently, it seems unlikely that the problem is on MP's side. Additionally, please confirm whether the Python Version in use is 32-bit or 64-bit, as MP supports Python 64-bit.
> 
> Thank you

Right! Just upgrade your mediapipe version to the latest:
`pip install mediapipe -U`
