### ISSUE TITLE
PoseLandmarker - segmentationMasks not in  the PoseLandmakerResult

### ISSUE THREAD

**Issue by MyraChen200** [google/mediapipe#5020]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows

### Browser and version if the issue happens on browser

Google Chrome

### Programming Language and version

JavaScript

### MediaPipe version

0.10.8

### Solution

PoseLandmarker

### Describe the actual behavior

`segmentationMasks` not in poseLandmarker results with options `outputSegmentationMasks: true`

### Describe the expected behaviour

poseLandmarker results should have `segmentationMasks` with MPMask type

### Standalone code/steps you may have used to try to get what you need

```shell
Set options:

const options: PoseLandmarkerOptions = {
  baseOptions: {
    modelAssetPath: `https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/latest/pose_landmarker_lite.task`,
    delegate: "GPU"
  },
  runningMode: "VIDEO",
  numPoses: 2,
  outputSegmentationMasks: true,
};
const poseLandmarker = await PoseLandmarker.createFromOptions(vision, options);
```

The listener:
```
poseLandmarker.detectForVideo(videoRef.current, startTimeMs, (result) => {
  console.log(result)
})
```

Results only have `landmarks`, `worlodLandmarks` and `g`. 
Don’t know what `g` is, but its format is similar to MPMask.
```


### Other info / Complete Logs

_No response_

**Comment by schmidt-sebastian** [comment]
Oops. Will fix this ASAP.
