### ISSUE TITLE
Upgrade Protobuf

### ISSUE THREAD

**Issue by bergwerf** [google/mediapipe#5022]
I currently cannot use Mediapipe together with OR-Tools, because both have different Protobuf constraints. In particular, Mediapipe still requires protobuf <4. I think this should really be updated.

**Comment by schmidt-sebastian** [comment]
What platform are you concerned about? I assume this is Android?

**Comment by RichardLindhout** [comment]
I have the same issue. I am forced to keep a specific version of python to keep working with or-tools and mediapipe.
