### ISSUE TITLE
Access to specific Pose Landmarker Task API (Python)

### ISSUE THREAD

**Issue by leonidasavila** [google/mediapipe#5023]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Ubuntu 22.04

### MediaPipe version

Latest

### Solution

Pose

### Programming Language and version

Python

### Describe the actual behavior

Can't access to a specific landmarks

### Describe the expected behaviour

Access to right_shoulder, right_elbow, right_wrist

### Standalone code/steps you may have used to try to get what you need

```shell
i used this code:

# STEP 1: Import the necessary modules.
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# STEP 2: Create an PoseLandmarker object.
base_options = python.BaseOptions(model_asset_path='pose_landmarker.task')
options = vision.PoseLandmarkerOptions(
    base_options=base_options,
    output_segmentation_masks=True)
detector = vision.PoseLandmarker.create_from_options(options)

# STEP 3: Load the input image.
image = mp.Image.create_from_file("image.jpg")

# STEP 4: Detect pose landmarks from the input image.
detection_result = detector.detect(image)

# STEP 5: Process the detection result. In this case, visualize it.
annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)
cv2_imshow(cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))
```

### Other info / Complete Logs

```shell
But i can´t access to a specific landmarks like using this technique:

import cv2
import mediapipe as mp
import numpy as np
from math import acos, degrees

mp_pose = mp.solutions.pose

mp_drawing = mp.solutions.drawing_utils

cap = cv2.VideoCapture("newsan.mp4")

with mp_pose.Pose(
    static_image_mode = False) as pose:

        while True: 
            ret, frame = cap.read()
            if ret == False:
                break
                
            #modificamos los fotogramas a RGB p/leer los puntos
            height, width, _ = frame.shape
            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            results = pose.process(frame_rgb)
            
            if results.pose_landmarks is not None:
                
                #lectura de puntos seeccionados
                x1 = int(results.pose_landmarks.landmark[16].x * width)
                y1 = int(results.pose_landmarks.landmark[16].y * height)

                x2 = int(results.pose_landmarks.landmark[14].x * width)
                y2 = int(results.pose_landmarks.landmark[14].y * height)
```

**Comment by schmidt-sebastian** [comment]
We need to expose pose landmarker constants. Sorry for the trouble.

**Comment by leonidasavila** [comment]
I was able to access a specific landmark making a normalization of landmark_pb2 but i cant draw it in the image

![image](https://github.com/google/mediapipe/assets/86005601/35537637-44b3-4cf6-91ae-6b9f135431bc)

**Comment by kuaashish** [comment]
Hi @leonidasavila,

Apologies for delayed response, Please use this example in the [gist](https://colab.sandbox.google.com/gist/kuaashish/7cf1f70d4caff2fca03d1a53e2e74bfb/-mediapipe_python_tasks-_pose_landmarker-1.ipynb) to access and draw specific landmarks for the right arm in the image. If you need to access another specific landmarks and draw it in image, feel free to adjust it according to your requirements.

Thank you
