### ISSUE TITLE
Mediapipe GPU support with Windows application

### ISSUE THREAD

**Issue by riflemanl** [google/mediapipe#5024]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windowd 10/11

### MediaPipe Tasks SDK version

v0.10.8

### Task name (e.g. Image classification, Gesture recognition etc.)

HolisticPose detection

### Programming Language and version (e.g. C++, Python, Java)

C++

### Describe the actual behavior

Mediapipe GPU support needs tensorflow+CUDA

### Describe the expected behaviour

Mediapipe GPU support can call to CUDA directly

### Standalone code/steps you may have used to try to get what you need

```shell
I'm building a Windows .exe application that utilize mediapipe. Mediapipe GPU support needs tensorflow+CUDA, but tensorflow after 2.10 is not supporting native Windows anymore. So, is it possible mediapipe call to cuda directly not going through tensorflow?
```

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

Could you please have a look into this issue? 

Thank you
