### ISSUE TITLE
NPM package vision_bundle.mjs and .cjs file have incorrect sourceMappingURL

### ISSUE THREAD

**Issue by samankittani** [google/mediapipe#5027]
NPM package fails to la

None

### OS Platform and Distribution

Ubuntu 22.04

### Programming Language and version

javascript

### MediaPipe version

0.10.8

### Solution

I edited  the sourceMappingURL command from "//# sourceMappingURL=vision_bundle_mjs.js.map" to "//# sourceMappingURL=vision_bundle.mjs.map""

### Describe the actual behavior

the web browser fails to identify where the .map file is located.

### Describe the expected behaviour

The web browser should find where the .map file is located.

### Standalone code/steps you may have used to try to get what you need

```shell
Not sure why, but I fixed my local package by editing  the sourceMappingURL comments from: 
"//# sourceMappingURL=vision_bundle_cjs.js.map" to "//# sourceMappingURL=vision_bundle.cjs.map", 
and  
"//# sourceMappingURL=vision_bundle_mjs.js.map" to "//# sourceMappingURL=vision_bundle.mjs.map"
```

**Comment by kuaashish** [comment]
Hi @samankittani,

We have an updated version, 0.10.9, available on [npmjs](https://www.npmjs.com/package/@mediapipe/tasks-vision/v/0.10.9). Kindly attempt to build using this newer version. you are currently using the older version, 0.10.8. Based on our analysis of past changes and commits, it appears that the issue may not be originating from our end. Please try the build with the newer version and inform us of the status.

Thank you

**Comment by KennethanCeyer** [comment]
Hi @samankittani,
This issue is happening again.

Tested with the version `0.10.17`
