### ISSUE TITLE
Output relationship between pose_landmarks and pose_world_landmarks

### ISSUE THREAD

**Issue by Zenway-Wong** [google/mediapipe#5032]
I'm trying to understand the relationship between pose_landmarks and pose_world_landmarks, as well as the difference between Landmark and NormalizedLandmark in Mediapipe's Pose module.

To the best of my knowledge, the common approch to estimate 3D landmarks is: (1) estimate 2D landmarks; (2) conduct 2D-to-3D lifting. However, Mediapipe seems to estimate them kind of simutanously. I guess Mediapipe Pose module only estimate the 3D coordinates (image coordinate or world coordinate) and get the other one with some transformation.

For short, my question is what is the actual output of AI model of Mediapipe pose, 3D coordinates in image space,  3D coordinates in world space, or both of them?

**Comment by kuaashish** [comment]
Hi @Zenway-Wong,

The Pose landmarker gives results in both 3D coordinates in Image Space and 3D coordinates in World Space. If you check the Python example guide, you'll see the output results for both spaces as mentioned [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python) in "Handle and display results" section:

```
PoseLandmarkerResult:

Landmarks:

    Landmark #0:
      x            : 0.638852
      y            : 0.671197
      z            : 0.129959
      visibility   : 0.9999997615814209
      presence     : 0.9999984502792358
    Landmark #1:
      x            : 0.634599
      y            : 0.536441
      z            : -0.06984
      visibility   : 0.999909
      presence     : 0.999958
    ... (33 landmarks per pose)

 WorldLandmarks:

    Landmark #0:
      x            : 0.067485
      y            : 0.031084
      z            : 0.055223
      visibility   : 0.9999997615814209
      presence     : 0.9999984502792358
    Landmark #1:
      x            : 0.063209
      y            : -0.00382
      z            : 0.020920
      visibility   : 0.999976
      presence     : 0.999998
    ... (33 world landmarks per pose)
  SegmentationMasks:
    ... (pictured below)
```
Kindly consult the provided [thread](https://github.com/google/mediapipe/issues/1611) and[ model card ](https://storage.googleapis.com/mediapipe-assets/Model%20Card%20BlazePose%20GHUM%203D.pdf)for a more comprehensive understanding.

Thank you
