### ISSUE TITLE
Can't "pip install mediapipe" in python 3.12.1 with pip version 23.3.2 in windows

### ISSUE THREAD

**Issue by saptrshighosh** [google/mediapipe#5035]
### OS Platform and Distribution

Windows 11 23H2

### Programming Language and version

Python 3.12.1

### Installed using virtualenv? pip? Conda?(if python)

pip 23.3.2

### MediaPipe version

0.10.9

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.8.1

### Describe the problem

pip install mediapipe

### Complete Logs

```shell
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

**Comment by kuaashish** [comment]
Hi @saptrshighosh,

It seems you are using an unsupported Python version. The recommended versions are between 3.8 and 3.11, as specified in the Python Setup [documentation](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions). Version 3.12 is not yet supported in Mediapipe. Kindly use the recommended version and inform us if you encounter any issues during the Mediapipe build process with Pip.

Thank you

**Comment by saptrshighosh** [comment]
So can I uninstall Python 3.12.1 (latest) from my system and install Python 3.11.7. Or Can I use both at the same time? What would you suggest?

**Comment by kuaashish** [comment]
Hi @saptrshighosh,

If you prefer to continue using version 3.12, we recommend reviewing the StackOverflow [thread](https://stackoverflow.com/questions/4583367/how-to-run-multiple-python-versions-on-windows) provided. It's important to note that we have not tested this specific scenario, and we cannot guarantee the successful installation of MediaPipe. However, based on our observations, similar issues have been resolved by downgrading to a supported version of Python and uninstalling any unsupported versions.

Thank you

**Comment by saptrshighosh** [comment]
Okay, thanks for the information. Let me try with Python 3.11.7. I'll let you know.

**Comment by kuaashish** [comment]
Hi @saptrshighosh,

Certainly, please provide an update on the status, and inform us if any issues persist.

Thank you!!

**Comment by saptrshighosh** [comment]
Yes the `pip install mediapipe` is working in **`Python 3.11.7`**

**Comment by kuaashish** [comment]
Hi @saptrshighosh,

Thank you for confirming. Could you kindly inform us if we may consider this issue resolved and proceed to close the status?

**Comment by saptrshighosh** [comment]
> Hi @saptrshighosh,
> 
> Thank you for confirming. Could you kindly inform us if we may consider this issue resolved and proceed to close the status?

**Comment by saptrshighosh** [comment]
Yes, thanks a lot

**Comment by g-o-o-g-l-e** [comment]
I need help on #57

**Comment by maimemory** [comment]
Now python 3.12.3 can be installed mediapipe

**Comment by Starnodes2024** [comment]
> Now python 3.12.3 can be installed mediapipe

on 3.12.4 i still get the error

**Comment by Rayan-Ali1083** [comment]
i have python 3.7.9 but pip install mediapipe isn't working. any help ?
