### ISSUE TITLE
Import some external library to support new features, but met problem with architecture support

### ISSUE THREAD

**Issue by momo1986** [google/mediapipe#504]
Hello, for android development, I try to support USB features.

But met some problems.

MacOS Bazel Command:
`bazel build -c opt  mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu   --verbose_failures --sandbox_debug --config=android_arm64`

My third_party/BUILD new content:
```
android_library(
    name = "com_serenegiant_common",
    exports = [
        "@maven//:com_serenegiant_common",
    ],
)

android_library(
    name = "com_serenegiant_uvccamera_libuvccamera",
    exports = [
        "@maven//:com_serenegiant_uvccamera_libuvccamera",
    ],
)
android_library(
    name = "com_serenegiant_uvccamera_libuvccameras",
    exports = [
        "@maven//:com_serenegiant_uvccamera_libuvccameras",
    ],
)

android_library(
    name = "com_serenegiant_uvccamera_usbCameraCommon",
    exports = [
        "@maven//:com_serenegiant_uvccamera_usbCameraCommon",
    ],
)





android_library(
     name = "com_quickbirdstudios_opencv",
     exports = [
        "@maven//:com_quickbirdstudios_opencv",
     ],
)
```

My WORKSPACE new feature.
```
maven_install(
    artifacts = [
        "androidx.annotation:annotation:aar:1.1.0",
        "androidx.appcompat:appcompat:aar:1.1.0-rc01",
        "androidx.camera:camera-core:aar:1.0.0-alpha06",
        "androidx.camera:camera-camera2:aar:1.0.0-alpha06",
        "androidx.constraintlayout:constraintlayout:aar:1.1.3",
        "androidx.core:core:aar:1.1.0-rc03",
        "androidx.legacy:legacy-support-v4:aar:1.0.0",
        "androidx.recyclerview:recyclerview:aar:1.1.0-beta02",
	"com.serenegiant:common:aar:0.0.3",
	"com.serenegiant.uvccamera:libuvccamera:aar:1.2.0",
	"com.serenegiant.uvccamera:libuvccameras:aar:0.0.2",
	"com.serenegiant.uvccamera:usbCameraCommon:aar:0.0.1",
        "com.google.android.material:material:aar:1.0.0-rc01",
        "com.quickbirdstudios:opencv:aar:4.1.0",
    ],
    repositories = [
        "https://dl.google.com/dl/android/maven2",
        "https://repo1.maven.org/maven2",
        "https://jcenter.bintray.com",
        "https://maven.google.com",
    ],
)

maven_server(
    name = "google_server",
    url = "https://dl.google.com/dl/android/maven2",
)

maven_server(
    name = "bintray_server",
    url = "https://jcenter.bintray.com",
)

maven_jar(
    name = "com_serenegiant_uvccamera_usbCameraCommon",
    artifact = "com.serenegiant.uvccamera:usbCameraCommon:0.0.1",
    sha1 = "e00ce54db790d024728d40199912de2986f1f75d",
    server = "bintray_server",
)

maven_jar(
    name = "com_serenegiant_uvccamera_libuvccamera",
    artifact = "com.serenegiant.uvccamera:libuvccamera:1.2.0",
    sha1 = "2bed656b882b7fac5ef81e5785b726ca713c7288",
    server = "bintray_server",
)

maven_jar(
    name = "com_serenegiant_uvccamera_libuvccameras",
    artifact = "com.serenegiant.uvccamera:libuvccameras:0.0.2",
    sha1 = "052915390a50a428cdcf20f0244bc640c5ae29f2",
    server = "bintray_server",
)

maven_jar(
    name = "com_serenegiant_common",
    artifact = "com.serenegiant:common:0.0.3",
    sha1 = "ec67b3aa5e653137ff2fb80be967c1a46c7818d6",
    server = "bintray_server",
)

maven_jar(
    name = "com_quickbirdstudios_opencv",
    artifact = "com.quickbirdstudios:opencv:4.1.0",
    sha1 = "201f18b3b3ac2820cb8a95b6796d28a1d64c0d17",
    server = "bintray_server",
)
```

In mediapipe/java/com/google/mediapipe/component, refers to such new packages:
```
# Note: We need to separate the camera helper files in a different BUILD target because CameraX has a minimum Android API
# requirement of API 21. Users of android_components may have different API dependencies.
android_library(
    name = "android_cameras_helper",
    srcs = [
        "CameraHelper.java",
        "CameraXPreviewHelper.java",
        "ExternalCameraView.java",
        "UVCDevice.java",
        "DefaultDeviceConnectListener.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:androidx_appcompat",
        "//third_party:androidx_legacy_support_v4",
        "//third_party:camera2",
        "//third_party:camerax_core",
        "//third_party:com_serenegiant_common",
	"//third_party:com_serenegiant_uvccamera_libuvccamera",
        "//third_party:com_serenegiant_uvccamera_libuvccameras",
	"//third_party:com_serenegiant_uvccamera_usbCameraCommon",
        "//third_party:opencv",
        "//third_party:com_quickbirdstudios_opencv",
	"@androidx_concurrent_futures//jar",
        "@androidx_lifecycle//jar",
        "@com_google_code_findbugs//jar",
        "@com_google_guava_android//jar",
    ],
)
.
```

Unfortunately, I am disturbed by the error message about "hazel build":

> INFO: Writing tracer profile to '/private/var/tmp/_bazel_junyan/d0562ae4205a819f08c6b310db2d9181/command.profile.gz'
> INFO: Build options --cpu, --crosstool_top, --fat_apk_cpu, and 2 more have changed, discarding analysis cache.
> INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu:facedetectioncpu (0 packages loaded, 11707 targets configured).
> INFO: Found 1 target...
> ERROR: /private/var/tmp/_bazel_junyan/d0562ae4205a819f08c6b310db2d9181/external/maven/BUILD:989:1: Filtering AAR native libs by architecture failed (Exit 1) sandbox-exec failed: error executing command 
>   (cd /private/var/tmp/_bazel_junyan/d0562ae4205a819f08c6b310db2d9181/sandbox/darwin-sandbox/2881/execroot/mediapipe && \
>   exec env - \
>     PATH=/opt/local/bin:/opt/local/sbin:/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin \
>     TMPDIR=/var/folders/78/xc16s7dx0l319lk_vf44x_l00000gn/T/ \
>   /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_junyan/d0562ae4205a819f08c6b310db2d9181/sandbox/darwin-sandbox/2881/sandbox.sb /var/tmp/_bazel_junyan/install/154077aea4bc476f9086f48e48456396/_embedded_binaries/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/host/bin/external/bazel_tools/tools/android/aar_native_libs_zip_creator --input_aar external/maven/v1/https/jcenter.bintray.com/com/serenegiant/uvccamera/libuvccameras/0.0.2/libuvccameras-0.0.2.aar --cpu arm64-v8a --output_zip bazel-out/android-arm64-v8a-opt/bin/external/maven/_aar/com_serenegiant_uvccamera_libuvccameras/native_libs.zip)
> ----------------
> Note: The failure of target @bazel_tools//tools/android:aar_native_libs_zip_creator (with exit code 1) may have been caused by the fact that it is a Python 2 program that was built in the host configuration, which uses Python 3. You can change the host configuration (for the entire build) to instead use Python 2 by setting --host_force_python=PY2.
> 
> If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
> ----------------
> AAR external/maven/v1/https/jcenter.bintray.com/com/serenegiant/uvccamera/libuvccameras/0.0.2/libuvccameras-0.0.2.aar missing native libs for requested architecture: arm64-v8a
> Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu:facedetectioncpu failed to build
> INFO: Elapsed time: 7.342s, Critical Path: 1.09s
> INFO: 10 processes: 6 darwin-sandbox, 4 worker.
> FAILED: Build did NOT complete successfully

Since com/serenegiant/uvccamera/libuvccameras/0.0.2 is a maven jar artifact, I am not sure why it reports the missing native libs for arm64-v8a?

And more important, how can I fix it?

Wait for response.

**Comment by jiuqiant** [comment]
Basically, libuvccameras only has armeabi directory while MediaPipe needs armeabi-v7a and arm64-v8a directory in the jni directory of an AAR. See a more detailed answer at https://github.com/google/mediapipe/issues/501#issuecomment-596689243
