### ISSUE TITLE
How to use NNAPI for inference

### ISSUE THREAD

**Issue by ranchuane** [google/mediapipe#5041]
I want to use NNAPI for inference, but I don't know how to modify the following configuration:
node {
  calculator: "InferenceCalculator"
  input_stream: "TENSORS:input_tensors"
  output_stream: "TENSORS:output_tensors"
  options: {
    [mediapipe.InferenceCalculatorOptions.ext] {
      model_path: "detection.tflite"
      delegate {
        xnnpack {}
      }
    }
  }
}

**Comment by kuaashish** [comment]
Hi @ranchuane,

Could you please provide more details about your issue? Additionally, we kindly request you to fill out the template provided [here](https://github.com/google/mediapipe/issues/new/choose). This will help us better understand the issue with relevant information and enable us to provide the assistance you are seeking.

Thank you
