### ISSUE TITLE
Problem with MediaPipe Hands -> Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by simplo** [google/mediapipe#5045]
I'm using the sample code to get hand markers by a video.
It works fine but sometimes the program exit reporting this error:
Process finished with exit code -1073741819 (0xC0000005)
It seems the working time of the program is shorter using higher resolutions, for example 640x480 exits after 5/10 seconds, 512x424 (typical Kinect IR camera) can work for minutes.
I'm working on Windows 10, Python 3.9.18, I7 with 16GBRAM and an nVidia 1070, even if I think I can't use GPU for mediapipe in Windows (at start I get a "INFO: Created TensorFlow Lite XNNPACK delegate for CPU." message).
Thank you in advance!

**Comment by kuaashish** [comment]
Hi @simplo,

Can you please give more details about your question? This includes the steps you are following from the documentation and the platform you are using, like Android, Python, or JavaScript. If you are using Android, please also provide info about your Android device.

Also, it is suggested to fill out the [template](https://github.com/google/mediapipe/issues/new/choose) for better understanding and to help us address the issue more comprehensively.

Thank you

**Comment by simplo** [comment]
FIXED: it was my fault, an issue about a temporary variable released before the cycle was finished.

**Comment by kuaashish** [comment]
Hi @simplo,

Thank you for confirming, Can we go ahead and mark this issue resolved and close the status?
