### ISSUE TITLE
Extract data with Mediapipe

### ISSUE THREAD

**Issue by taserfurkan** [google/mediapipe#5046]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows11

### Task name (e.g. Image classification, Gesture recognition etc.)

Arm Dedection

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

Arm Dedection

### Describe the expected behaviour

Arm Dedection

### Standalone code/steps you may have used to try to get what you need

```shell
I'm trying to extract data with MediaPipe. with this case, I train the some ml model. But I need just left and right arm. I mean ı just need 11,13 and 15. point which is left shoulder, left elbow and left wrist of pose. I wrote some code but the start then close suddenly without any error. Code is here:
```

### Other info / Complete Logs

```shell
import cv2
import mediapipe as mp

mp_pose = mp.solutions.pose
pose = mp_pose.Pose(static_image_mode=False, model_complexity=2, min_detection_confidence=0.5)

RIGHT_ARM_LANDMARKS = [mp_pose.PoseLandmark.RIGHT_SHOULDER,
                       mp_pose.PoseLandmark.RIGHT_ELBOW,
                       mp_pose.PoseLandmark.RIGHT_WRIST]

cap = cv2.VideoCapture(0)

while cap.isOpened():
    ret, frame = cap.read()

    if not ret:
        print("Error: Couldn't read the frame.")
        break

    rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    results = pose.process(rgb_frame)

    if results.pose_landmarks:
        for landmark in RIGHT_ARM_LANDMARKS:
            point = results.pose_landmarks.landmark[landmark]
            landmark_x, landmark_y = int(point.x * frame.shape[1]), int(point.y * frame.shape[0])
            cv2.circle(frame, (landmark_x, landmark_y), 5, (255, 0, 0), -1)

    cv2.imshow("Right Arm Landmarks", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```

**Comment by kuaashish** [comment]
Hi @taserfurkan,

The code you used is from an legacy hand solution, but it is now updated to the Hand Landmarker Task API. You can find the same information in our [documentation](https://developers.google.com/mediapipe/solutions/guide#legacy). We have completely stopped supporting the legacy hand solution. 

Please check out our new Hand Task API [documentation](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker). For new API you can use this example [gist](https://colab.sandbox.google.com/gist/kuaashish/7cf1f70d4caff2fca03d1a53e2e74bfb/-mediapipe_python_tasks-_pose_landmarker-1.ipynb) to extract specific landmarks for the right arm (please adjust for the left arm for drawing as well) and drawing of the right arm without highlighting other key landmarks.

Thank you
