### ISSUE TITLE
autoflip cannot find FFmpeg

### ISSUE THREAD

**Issue by gabriben** [google/mediapipe#505]
Hi,

I have been trying to run autoflip from an AWS instance but I keep getting this error...

`Calculator::Open() for node "[OpenCvVideoDecoderCalculator, OpenCvVideoDecoderCalculator with output stream: video_raw]" failed: ; OpenCVVideoDecoderCalculator can't save the audio file because FFmpeg is not installed. Please remove output_side_packet: "SAVED_AUDIO_PATH" from the node config.`

... when running the basic command

`GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip \
  --calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt \
  --input_side_packets=input_video_path=/absolute/path/to/the/local/video/file,output_video_path=/absolute/path/to/save/the/output/video/file,aspect_ratio=1:1`

**tried config**

- a Docker image, using the [dockerfile](https://github.com/google/mediapipe/blob/master/Dockerfile) provided in the docs
- manual installation following the steps and using bazel-1.0.0 and manual installation of FFmpeg and OpenCV.

(both of these configs result in the same error.)

thank you

**Comment by jiuqiant** [comment]
Thanks for the interest.

AutoFlip uses FFmpeg to extract the audio track from the original video. If you read [the source code](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/video/opencv_video_decoder_calculator.cc#L158), the OpencvVideoDecoderCalculator basically makes a system call to run a FFmpeg command. I think the first thing to figure out is to see if FFmpeg command works on your local machine. Could you try `ffmpeg -version` in the command line? It should print something like the following

```bash
$ ffmpeg -version
ffmpeg version 4.2.1-2+build2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9 (Debian 9.2.1-8)
configuration: --prefix=/usr --extra-version=2+build2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```

Alternatively, if you don't care about the audio (AutoFlip only deals with the video), you can modify [the graph](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt) like the following to ignore audio.

```
diff --git a/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt b/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt
index 95af188..3efda84 100644
--- a/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt
+++ b/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt
@@ -8,7 +8,6 @@ node {
   input_side_packet: "INPUT_FILE_PATH:input_video_path"
   output_stream: "VIDEO:video_raw"
   output_stream: "VIDEO_PRESTREAM:video_header"
-  output_side_packet: "SAVED_AUDIO_PATH:audio_path"
 }

 # VIDEO_PREP: Scale the input video before feature extraction.
@@ -192,7 +191,6 @@ node {
   input_stream: "VIDEO:cropped_frames"
   input_stream: "VIDEO_PRESTREAM:output_frames_video_header"
   input_side_packet: "OUTPUT_FILE_PATH:output_video_path"
-  input_side_packet: "AUDIO_FILE_PATH:audio_path"
   options: {
     [mediapipe.OpenCvVideoEncoderCalculatorOptions.ext]: {
       codec: "avc1"
```

**Comment by gabriben** [comment]
thank you for the quick answer.

Here is what I did relating FFmpeg and modifzing the graph:

**FFMPEG**

I have already tried installing FFMPeg manually and can successfully run `ffmpeg -version`:

`ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8 (Debian 8.3.0-6)
configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100`

But the same error message is still displayed. Of course, I am not too tied to making sound work, which talks to the second solution below.

**Removing lines from the graph**

It does make the process go further, but I get another error related to libx264. It seems to be something related to the compatibility of versions of FFmpeg and OpenCV. I tried downgrading FFmpeg to the version you have (4.2.1), but it didn't solve the problem.

Thank you in advance


**Note**

Maybe you could consider editing the error message so as to explicitly tell the user to delete the two lines mentioned above? Namely,

`output_side_packet: "SAVED_AUDIO_PATH:audio_path"`
`input_side_packet: "AUDIO_FILE_PATH:audio_path"`

The error message for now only hints at removing the first of these two lines: `Please remove output_side_packet: "SAVED_AUDIO_PATH" from the node config.`

**Comment by jiuqiant** [comment]
How do you install OpenCV and FFmpeg? If you compile OpenCV by yourself, please make sure you compile it with FFmpeg and the other necessary dependencies... BTW, AutoFlip requires OpenCV 3.

Another thing to try is to do the graph editing in the docker container.

**Comment by gabriben** [comment]
Well I am installing openCV with the [docker image](https://github.com/google/mediapipe/blob/master/Dockerfile) from the dockerFile in the documentation. 

Seeing it didn't work, I tried to install OpenCV and FFmpeg in different ways and versions without success.

Could you show me what I should strictly add in that dockerfile linked above to make it work? Aside from the obvious `apt-get install ffmpeg` I guess.

Thank you in advance

**Comment by allenday** [comment]
fixed in PR https://github.com/google/mediapipe/pull/678

**Comment by jiuqiant** [comment]
See the fix in the latest version of Dockerfile in v0.7.5.

**Comment by gabriben** [comment]
just an FYI, I used the original mediapipe [Dockerfile](https://github.com/google/mediapipe/blob/master/Dockerfile), to which I added the following:

`RUN apt-get update && apt-get install -y git ffmpeg
RUN pip3 install setuptools
RUN pip3 install ffmpeg-python
WORKDIR /
RUN git clone https://github.com/google/mediapipe.git

RUN touch WORKSPACE

WORKDIR /mediapipe/mediapipe/examples/desktop/
RUN bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 autoflip:run_autoflip`

**Comment by joaomnmoreira** [comment]
@jiuqiant can you help?

**Comment by Kelach** [comment]
> @jiuqiant can you help?

did you find a solution?
