### ISSUE TITLE
Error on ios 14.6 safari：Check failed: prod_token

### ISSUE THREAD

**Issue by huanhunx** [google/mediapipe#5058]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

iOS 14.6

### Mobile device if the issue happens on mobile device

iphone 12 pro

### Browser and version if the issue happens on browser

Safari 14.6

### Programming Language and version

Javascript

### MediaPipe version

0.10.9

### Solution

FaceLandmark

### Describe the actual behavior

Throw an error when I call detectForVideo api

### Describe the expected behaviour

Can get detect results after call detectForVideo api

### Standalone code/steps you may have used to try to get what you need

```shell
https://codepen.io/mediapipe-preview/pen/OJBVQJm

I used the example code I found in document.
```

### Other info / Complete Logs

```shell
F0108 11:43:54.385000 1820112 gl_texture_buffer.cc:205] Check failed: prod_token 
Aborted()
[Error] Unhandled Promise Rejection: RuntimeError: Aborted(). Build with -sASSERTIONS for more info. (evaluating 'new WebAssembly.RuntimeError(what)')
	abort (vision_wasm_nosimd_internal.js:9:5671)
	_abort (vision_wasm_nosimd_internal.js:9:106699)
	wasm-stub
	<?>.wasm-function[5760]
	<?>.wasm-function[3509]
	<?>.wasm-function[242]
	<?>.wasm-function[3274]
	<?>.wasm-function[14273]
	wasm-stub
	14273
	（匿名函数） (vision_wasm_nosimd_internal.js:9:195066)
	（匿名函数） (tasks-vision@0.10.9:7:72323)
	Do (tasks-vision@0.10.9:7:42779)
	va (tasks-vision@0.10.9:7:72247)
	za (tasks-vision@0.10.9:7:73634)
	Ha (tasks-vision@0.10.9:7:73975)
	H (tasks-vision@0.10.9:7:102893)
	（匿名函数） (test.html:373)
	asyncFunctionResume
	（匿名函数）
	promiseReactionJobWithoutPromise
```

**Comment by kuaashish** [comment]
Hi @huanhunx,

It seems that the code example works with iOS 17.x based on past issues. Can you please update your iOS version to newer one probably 17.x and let us know if it's still working?

Thank you

**Comment by siddharthjha387** [comment]
Facing this issue in windows(Chrome browser and Macbook(safari)

Error messgae: `F0923 07:34:15.931000 1836816 gl_texture_buffer.cc:207] Check failed: prod_token `

**Comment by chalapathi-ct** [comment]
Facing the issue in windows 11 and 10 pro  chrome. 

F12111 08:37:32.890000 1905760 gl_texture_buffer.cc:238] Check failed: prod_token
