### ISSUE TITLE
Hand Detection (desktop) : Build did not complete successfully

### ISSUE THREAD

**Issue by AiLac** [google/mediapipe#506]
I have an issue while building the hand tracking example
Could you please help ?

OS: ubuntu1~16.04.12
gcc version : 5.4.0

/home/ailac/Downloads/mediapipe-master/mediapipe/calculators/image/BUILD:332:1: C++ compilation of rule '//mediapipe/calculators/image:image_cropping_calculator' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 74 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/image/image_cropping_calculator.cc: In member function 'mediapipe::Status mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*)':
**mediapipe/calculators/image/image_cropping_calculator.cc:205:8: error: expected unqualified-id before '[' token
   auto [target_width, target_height, rect_center_x, rect_center_y, rotation] =
        ^**
mediapipe/calculators/image/image_cropping_calculator.cc:212:46: error: 'rect_center_x' was not declared in this scope
   const cv::RotatedRect min_rect(cv::Point2f(rect_center_x, rect_center_y),
                                              ^
mediapipe/calculators/image/image_cropping_calculator.cc:212:61: error: 'rect_center_y' was not declared in this scope
   const cv::RotatedRect min_rect(cv::Point2f(rect_center_x, rect_center_y),
                                                             ^
mediapipe/calculators/image/image_cropping_calculator.cc:213:45: error: 'target_width' was not declared in this scope
                                  cv::Size2f(target_width, target_height),
                                             ^
mediapipe/calculators/image/image_cropping_calculator.cc:213:59: error: 'target_height' was not declared in this scope
                                  cv::Size2f(target_width, target_height),
                                                           ^
mediapipe/calculators/image/image_cropping_calculator.cc:214:34: error: 'rotation' was not declared in this scope
                                  rotation * 180.f / M_PI);
                                  ^
mediapipe/calculators/image/image_cropping_calculator.cc: In member function 'void mediapipe::ImageCroppingCalculator::GetOutputDimensions(mediapipe::CalculatorContext*, int, int, int*, int*)':
mediapipe/calculators/image/image_cropping_calculator.cc:389:8: error: expected unqualified-id before '[' token
   auto [crop_width, crop_height, x_center, y_center, rotation] =
        ^
mediapipe/calculators/image/image_cropping_calculator.cc:392:28: error: 'crop_width' was not declared in this scope
   const float half_width = crop_width / 2.0f;
                            ^
mediapipe/calculators/image/image_cropping_calculator.cc:393:29: error: 'crop_height' was not declared in this scope
   const float half_height = crop_height / 2.0f;
                             ^
mediapipe/calculators/image/image_cropping_calculator.cc:398:38: error: 'rotation' was not declared in this scope
     const float rotated_x = std::cos(rotation) * corners[i * 2] -
                                      ^
mediapipe/calculators/image/image_cropping_calculator.cc:403:48: error: 'x_center' was not declared in this scope
     transformed_points_[i * 2] = ((rotated_x + x_center) / src_width);
                                                ^
mediapipe/calculators/image/image_cropping_calculator.cc:404:52: error: 'y_center' was not declared in this scope
     transformed_points_[i * 2 + 1] = ((rotated_y + y_center) / src_height);
                                                    ^
In file included from ./mediapipe/framework/calculator_base.h:24:0,
                 from ./mediapipe/framework/calculator_framework.h:54,
                 from ./mediapipe/calculators/image/image_cropping_calculator.h:5,
                 from mediapipe/calculators/image/image_cropping_calculator.cc:15:
mediapipe/calculators/image/image_cropping_calculator.cc: At global scope:
./mediapipe/framework/calculator_registry.h:24:39: warning: 'mediapipe::calculator_registration_54__' defined but not used [-Wunused-variable]
                                       calculator_registration, name,       \
                                       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:23:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(::mediapipe::CalculatorBaseRegistry, \
   ^
mediapipe/calculators/image/image_cropping_calculator.cc:54:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(ImageCroppingCalculator);
 ^
./mediapipe/framework/calculator_registry.h:28:7: warning: 'mediapipe::access_registration_54__' defined but not used [-Wunused-variable]
       access_registration, name,                                           \
       ^
./mediapipe/framework/deps/registration.h:371:51: note: in definition of macro 'REGISTRY_STATIC_VAR_INNER'
 #define REGISTRY_STATIC_VAR_INNER(var_name, line) var_name##_##line##__
                                                   ^
./mediapipe/framework/deps/registration.h:381:16: note: in expansion of macro 'REGISTRY_STATIC_VAR'
   static auto* REGISTRY_STATIC_VAR(var_name, __LINE__) =                       \
                ^
./mediapipe/framework/calculator_registry.h:26:3: note: in expansion of macro 'REGISTER_FACTORY_FUNCTION_QUALIFIED'
   REGISTER_FACTORY_FUNCTION_QUALIFIED(                                     \
   ^
mediapipe/calculators/image/image_cropping_calculator.cc:54:1: note: in expansion of macro 'REGISTER_CALCULATOR'
 REGISTER_CALCULATOR(ImageCroppingCalculator);
 ^
cc1plus: warning: unrecognized command line option '-Wno-ignored-attributes'
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by Pan-zhaoyu** [comment]
Have you already solved this problem? I met the same error as you.

**Comment by mcclanahoochie** [comment]
Thanks for pointing this out. 
Looks like the way the `GetCropSpecs()` function is written requires  a _c++17_ capable compiler.
It probably should be rewritten to not require c++17.
I will look into updating this, and have the output parameter be part of the function call or something. 

Meanwhile if you want it to work now, then you can upgrade gcc to one that can handle c++17, or rewrite the function to be 
```
void GetCropSpecs(const CalculatorContext* cc,
                  int src_width, int src_height, RectSpec* spec);
```

**Comment by Pan-zhaoyu** [comment]
I solved the above issue by reinstall gcc and g++ to the new version, which match C++17. Agree with that.

**Comment by mcclanahoochie** [comment]
Glad to hear you got things working.
The recent update
https://github.com/google/mediapipe/commit/a3d36eee32999290c1461d469dc33cf63ccdf03a
has removed the need for c++17
