### ISSUE TITLE
when will be the tasks-vision/holistic available ? 

### ISSUE THREAD

**Issue by c1ngular** [google/mediapipe#5060]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

ALL

### Task name (e.g. Image classification, Gesture recognition etc.)

holistic

### Programming Language and version (e.g. C++, Python, Java)

ALL

### Describe the actual behavior

lack

### Describe the expected behaviour

available

### Standalone code/steps you may have used to try to get what you need

```shell
i've noticed that holistic solutions is removed from newer mediapipe updates , is it gonna be available any time soon ?
```

**Comment by kuaashish** [comment]
Hi @c1ngular,

The holistic code is finished, and it will be included in the upcoming release planned for mid-January.

Thank you

**Comment by c1ngular** [comment]
@kuaashish thanks

**Comment by kuaashish** [comment]
Hi @c1ngular,

Can you let us know if you do not have any more questions? If so, can we close the issue and mark it as resolved?

Thank you

**Comment by c1ngular** [comment]
any news on this ?

**Comment by mvazquezgts** [comment]
> any news on this ? @kuaashish

+1, 
Any news about the upcoming scheduled for mid-January?

**Comment by Terrywang2001** [comment]
+1, any news on this?
