### ISSUE TITLE
how to train my own model about object detection?

### ISSUE THREAD

**Issue by ly15927086342** [google/mediapipe#5068]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### MediaPipe version

0.10.6

### Solution

Object Detector

### Programming Language and version

javascript

### Other info / Complete Logs

```shell
I want to detect some object about backetball, such as the backboard, basketball the net and so on. Is there any method for me to train my own model, which finally produces the .tflite or .task file? It's my pleasure to receive your apply! Thank you.
```

**Comment by kuaashish** [comment]
Hi @ly15927086342,

It is possible to customize our Object Detection model to fit your needs. You can train the model according to your requirements and export it as a .task file. To do this, follow the Object Detection model customization guide on this [page](https://developers.google.com/mediapipe/solutions/customization/object_detector). Additionally, check out the Python [Colab example](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/customization/object_detector.ipynb) for training your own model.

Thank you

**Comment by ly15927086342** [comment]
> Hi @ly15927086342,
> 
> It is possible to customize our Object Detection model to fit your needs. You can train the model according to your requirements and export it as a .tflite file. To do this, follow the Object Detection model customization guide on this [page](https://developers.google.com/mediapipe/solutions/customization/object_detector). Additionally, check out the Python [Colab example](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/customization/object_detector.ipynb) for training your own model.
> 
> Thank you

Thank you for your apply! I'll check it out.

**Comment by ly0303521** [comment]
@ly15927086342 你好，目标检测重新训练完之后，你能成功运行吗，我在图“mediapipe/graphs/object_detection/object_detection_desktop_live.pbtxt”中将“ssdlite_object_detection.tflite”换成自己训得，或者使用下载的“ssd_mobilenet_v2.tflite”,修改好参数后，不会报错，但是检测结果都是乱的

**Comment by ly15927086342** [comment]
> @ly15927086342 你好，目标检测重新训练完之后，你能成功运行吗，我在图“mediapipe/graphs/object_detection/object_detection_desktop_live.pbtxt”中将“ssdlite_object_detection.tflite”换成自己训得，或者使用下载的“ssd_mobilenet_v2.tflite”,修改好参数后，不会报错，但是检测结果都是乱的

我是按照colab里的教程，提供了一份新的训练数据进行训练的，可以训练成功。我没试过你这种方式，不了解。
