### ISSUE TITLE
Dependencies don't match

### ISSUE THREAD

**Issue by 1203mueed** [google/mediapipe#5070]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Windows 11x64

### Python Version

3.11

### MediaPipe Model Maker version

0.2.1.3

### Task name (e.g. Image classification, Gesture recognition etc.)

Keypoints detection

### Describe the actual behavior

I'm facing the error:INFO: pip is still looking at multiple versions of mediapipe-model-maker to determine which version is compatible with other requirements. This could take a while. ERROR: Cannot install mediapipe-model-maker==0.1.0.2, mediapipe-model-maker==0.1.1.0 and mediapipe-model-maker==0.1.1.1 because these package versions have conflicting dependencies.  The conflict is caused by:     mediapipe-model-maker 0.1.1.1 depends on mediapipe==0.9.2.1     mediapipe-model-maker 0.1.1.0 depends on mediapipe==0.9.2.1     mediapipe-model-maker 0.1.0.2 depends on mediapipe==0.9.0.1  To fix this you could try to: 1. loosen the range of package versions you've specified 2. remove package versions to allow pip attempt to solve the dependency conflict  ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### Describe the expected behaviour

It should be installed seamlessly.

### Standalone code/steps you may have used to try to get what you need

```shell
I tried --n0-deps. but it doesn't work.
```

### Other info / Complete Logs

```shell
PS E:\Apparel Detector> pip install mediapipe-model-maker --no-deps
Collecting mediapipe-model-maker
  Using cached mediapipe_model_maker-0.2.1.3-py3-none-any.whl.metadata (1.6 kB)
Downloading mediapipe_model_maker-0.2.1.3-py3-none-any.whl (127 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.0/128.0 kB 1.3 MB/s eta 0:00:00
Installing collected packages: mediapipe-model-maker
Successfully installed mediapipe-model-maker-0.2.1.3
```

**Comment by kuaashish** [comment]
Hi @1203mueed,

Can you check if you can install the latest version of MediaPipe Model Maker, which is 0.2.1.3? The logs show that Model Maker 0.2.1.3 version has been installed correctly. Also, please share any extra issues you are having with installing MediaPipe Model Maker using pip.

Thank you!!
