### ISSUE TITLE
Bazel sync failed

### ISSUE THREAD

**Issue by iverdr17** [google/mediapipe#509]
![Screenshot (200)](https://user-images.githubusercontent.com/23277899/76344866-4a067400-6328-11ea-86dd-f5c4b237e3a5.png)

I tried with WSL and followed all the steps as -https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows-subsystem-for-linux-wsl and got the hello world program run perfectly fine but still, it says BAZEL  sync failed.

**Comment by jiuqiant** [comment]
I just tried Bazel sync on macOS and it works Okay. 
![Screen Shot 2020-03-10 at 11 41 32 AM](https://user-images.githubusercontent.com/3359144/76348709-e5b2c880-62c5-11ea-8fba-6b8f57fbe6d6.png)

Do you run Android Studio on Windows or WSL? If it's on Windows, my guess is it still calls Windows' Bazel to build, which is not supported yet by MediaPipe.

**Comment by iverdr17** [comment]
I am running Android Studio on Windows. So how do I build the application(hand tracking) after installing Bazel and running hello world application through WSL? I am using the Windows 10 system.

**Comment by jiuqiant** [comment]
You need to do the following steps to build the APKs:
1) Run [setup_android_sdk_and_ndk.sh](https://github.com/google/mediapipe/blob/dc9216dc595585d495250d0692afe35985d816ff/setup_android_sdk_and_ndk.sh) to download and setup Android SDK and NDK **in WSL**.

2) Run the build command to build the apps **in WSL**. For example, you need to run the following command to build the hand tracking app.

```
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/multihandtrackinggpu
```

3) **In Windows**, go to the Windows directory of the Linux Subsystem to get the apk. The default directory of WSL is C:\Users\YourUsername\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_SomeID\LocalState\rootfs\home

4) Use adb to install the apk.

**Comment by teafff** [comment]
i tried hello world program in ubuntu,but when i bazel run it,I report some errors.Can you tell me some  advices?
