### ISSUE TITLE
Pose not working very good for black people

### ISSUE THREAD

**Issue by ccornelis** [google/mediapipe#5091]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

iOS

### MediaPipe version

GoogleMLKit/PoseDetectionAccurate 3.2.0 (MediaPipe solution not available yet on iOS)

### Solution

Pose

### Programming Language and version

Swift

### Describe the actual behavior

Recognising poses for white/caucasian sprinters works good, for black sprinters it's pretty bad

### Describe the expected behaviour

Should work good for black sprinters too

### Standalone code/steps you may have used to try to get what you need

```shell
I made an iOS app that uses Pose landmarks for sprinters. Every frame of a short video is passed to Pose (as a stream of images) and for white sprinters the app works pretty good.
On the other hand, a recorded video of black sprinters made at the same time, same background, same lighting barely works. 
I tested the app with 6 different backgrounds and lighting conditions. The result was always the same: good results for white athletes, bad results for black athletes.

Will the upcoming Mediapipe Pose for iOS have better support for people of color?
```

**Comment by kuaashish** [comment]
Hi @ccornelis,

Thank you for bringing this matter to our attention. We kindly request you to provide any relevant reference images or videos that would aid in a more effective comparison for both scenarios. This information will greatly assist us in comprehending the issue thoroughly and facilitating internal discussions with our team to enhance overall performance.

Thank you

**Comment by ccornelis** [comment]
The mail also bounced with just 1 video file. Is there another way to send these videos to you?

**Comment by kuaashish** [comment]
Hi @ccornelis,

Please upload the document to Google Drive and provide us with the accessible link. Thank you!!

**Comment by ccornelis** [comment]
https://drive.google.com/open?id=1WnI45GyA1WifIHt749rRyV9dIrfNqbXU&usp=drive_fs

https://drive.google.com/open?id=1WmIG3Fr8ek6C1gOXkElIoYnPCer9t_43&usp=drive_fs

**Comment by kuaashish** [comment]
Hi @ccornelis,

I apologize for the delay in my response. The links you provided are currently inaccessible. Could you please share a accessible link? Thank you

**Comment by ccornelis** [comment]
Sorry for that. Should work now.

https://drive.google.com/file/d/1WnI45GyA1WifIHt749rRyV9dIrfNqbXU/view?usp=sharing

https://drive.google.com/file/d/1WmIG3Fr8ek6C1gOXkElIoYnPCer9t_43/view?usp=sharing

**Comment by schmidt-sebastian** [comment]
We are following up with out model team. Thanks for bringing this to our attention.

**Comment by ayushgdev** [comment]
Hello @ccornelis 

It seems like the camera was farther than 4 meters from the sprinter. If you check the [model card for Pose detection](https://storage.googleapis.com/mediapipe-assets/Model%20Card%20BlazePose%20GHUM%203D.pdf) Page 2, **Out of scope application**, the model does not work for subjects more than 14feet/4 meters away.

To solve this, a simple solution can be to crop the image/video frame. As a test, please check the following code excerpt (the video frame at 00:03 was used for the test):
```python
from mediapipe import solutions
from mediapipe.framework.formats import landmark_pb2
import numpy as np


def draw_landmarks_on_image(rgb_image, detection_result):
  pose_landmarks_list = detection_result.pose_landmarks
  annotated_image = np.copy(rgb_image)

  # Loop through the detected poses to visualize.
  for idx in range(len(pose_landmarks_list)):
    pose_landmarks = pose_landmarks_list[idx]

    # Draw the pose landmarks.
    pose_landmarks_proto = landmark_pb2.NormalizedLandmarkList()
    pose_landmarks_proto.landmark.extend([
      landmark_pb2.NormalizedLandmark(x=landmark.x, y=landmark.y, z=landmark.z) for landmark in pose_landmarks
    ])
    solutions.drawing_utils.draw_landmarks(
      annotated_image,
      pose_landmarks_proto,
      solutions.pose.POSE_CONNECTIONS,
      solutions.drawing_styles.get_default_pose_landmarks_style())
  return annotated_image

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

img = cv2.imread("sprinter.png")
img = img[200:img.shape[0]-200, 200:img.shape[1]-200, :]
cv2_imshow(img)

# STEP 1: Import the necessary modules.
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# STEP 2: Create an PoseLandmarker object.
base_options = python.BaseOptions(model_asset_path='pose_landmarker.task')
options = vision.PoseLandmarkerOptions(
    base_options=base_options,
    output_segmentation_masks=True)
detector = vision.PoseLandmarker.create_from_options(options)

# STEP 3: Load the input image.
image = mp.Image(image_format=mp.ImageFormat.SRGB, data=np.array(img[:,:, ::-1]))

# STEP 4: Detect pose landmarks from the input image.
detection_result = detector.detect(image)

# STEP 5: Process the detection result. In this case, visualize it.
annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)
cv2_imshow(cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))
```

The result is given below:
![image](https://github.com/google/mediapipe/assets/118424249/9cc9cd49-b9c9-4786-baf3-b4442c83f420)
