### ISSUE TITLE
Where is the code to get the hand tracking model inference results? I want to learn what post-processing is done to the direct output of the model.

### ISSUE THREAD

**Issue by Han-WG** [google/mediapipe#5093]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### MediaPipe Tasks SDK version

0.10.9

### Task name (e.g. Image classification, Gesture recognition etc.)

Hand tracking

### Programming Language and version (e.g. C++, Python, Java)

C++

### Describe the actual behavior

None

### Describe the expected behaviour

I use the hand tracking model file of this project to do inference directly, but the inference result is not the same as the output result of the project, what post-processing does this project do to the direct output result of the model? I would like to know where the code to get the direct output of the model is, and I would like to be able to learn the code for the post-processing algorithm directly.

### Standalone code/steps you may have used to try to get what you need

```shell
None
```

**Comment by kuaashish** [comment]
Hi @Han-WG,

Certainly. Please provide the steps you are currently following as per the documentation. Additionally, we would appreciate clarification on your specific query to better understand the support you are seeking from us.

Thank you

**Comment by Han-WG** [comment]
> Hi @Han-WG,
> 
> Certainly. Please provide the steps you are currently following as per the documentation. Additionally, we would appreciate clarification on your specific query to better understand the support you are seeking from us.
> 
> Thank you

I would like to know where the code to get the direct output of the model is, and I would like to be able to learn the code for the post-processing algorithm directly.
For example, the code to get the final results of hand tracking is at : 
https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/calculators/hand_landmarks_to_rect_calculator.cc
The code is : 
const auto& landmarks = cc->Inputs().Tag(kNormalizedLandmarksTag).Get<NormalizedLandmarkList>();
But this is the final processing result of hand tracking, it is post-processing to get it after getting the inference result of the tflite model.
I would like to know in which file or which code the inference result of the tflite model is obtained? It is the one which is not post-processed

**Comment by schmidt-sebastian** [comment]
All model processing is handled by TFLite and invoked through our inference calculators: https://github.com/search?q=repo%3Agoogle%2Fmediapipe%20inferencecalculator&type=code

**Comment by Han-WG** [comment]
> All model processing is handled by TFLite and invoked through our inference calculators: https://github.com/search?q=repo%3Agoogle%2Fmediapipe%20inferencecalculator&type=code

yes.
But how do I get to the result of inference?
May I ask whether this project has used some algorithms to optimize the inference results of the tflite model?

**Comment by ayushgdev** [comment]
In MediaPipe the core are calculators which have 3 functions implemented - Open, Close and Process. The Process function of the inference calculator is what you need to look at. However, inference calculator implementation differs among different GPU platforms. For Mac M1 chips, we use the [inference_calculator_metal.cc](https://github.com/google/mediapipe/blob/c9a984019342b5421c416c6f1441ed384157a548/mediapipe/calculators/tensor/inference_calculator_metal.cc) file but for OpenGL implementation, [inference_calculator_gl.cc](https://github.com/google/mediapipe/blob/c9a984019342b5421c416c6f1441ed384157a548/mediapipe/calculators/tensor/inference_calculator_gl.cc) is used.  To answer the question where the code is to get the direct output for the model, it resides [here](https://github.com/google/mediapipe/blob/c9a984019342b5421c416c6f1441ed384157a548/mediapipe/calculators/tensor/inference_calculator_gl.cc#L215) in the Process() for OpenGL implementation.


For post processing steps, you might want to check out the files for Hand Tracking graphs. For desktop, the root graph is the [hand_tracking_desktop](https://github.com/google/mediapipe/blob/c9a984019342b5421c416c6f1441ed384157a548/mediapipe/graphs/hand_tracking/hand_tracking_desktop.pbtxt#L32). Here, the tracking is done in HandLandmarkTrackingCpu calculator. This actually is itself a subgraph available in the [modules>hand_landmark>handlandmark_traacking_cpu.pbtxt](https://github.com/google/mediapipe/blob/c9a984019342b5421c416c6f1441ed384157a548/mediapipe/modules/hand_landmark/hand_landmark_tracking_cpu.pbtxt). Within this graph, the inference is done using the subgraph [HandLandmarkCPU](https://github.com/google/mediapipe/blob/c9a984019342b5421c416c6f1441ed384157a548/mediapipe/modules/hand_landmark/hand_landmark_tracking_cpu.pbtxt#L199C16-L199C31). Further diving into the HandLandmarkCPU subgraph, we see that [inferenceCalculator](https://github.com/google/mediapipe/blob/c9a984019342b5421c416c6f1441ed384157a548/mediapipe/modules/hand_landmark/hand_landmark_cpu.pbtxt#L69C16-L69C35) is being used. 

Among these graphs and subgraphs, you can track the pre/post processing being done while inference. For example, Letterboxing is done in the node of [ImageToTensorCalculator](https://github.com/google/mediapipe/blob/c9a984019342b5421c416c6f1441ed384157a548/mediapipe/modules/hand_landmark/hand_landmark_cpu.pbtxt#L44). There is also a ThresholdingCalculator which determines whether hand is present or not. There is [ClipDetectionVectorSizeCalculator](https://github.com/google/mediapipe/blob/c9a984019342b5421c416c6f1441ed384157a548/mediapipe/modules/hand_landmark/hand_landmark_tracking_cpu.pbtxt#L113) in hand_landmark_tracking_cpu.pbtxt which drops certain detections.

Similarly you can explore the graphs to find what interests your use case for pre/post processing steps
