### ISSUE TITLE
Testing Palm detection

### ISSUE THREAD

**Issue by akamzin** [google/mediapipe#51]
Hi, 

I want test the models on some of my videos on laptop. Is it possible?

I tried to directly load some of the tf lite models and got error below

ValueError: Didn't find custom op for name 'Convolution2DTransposeBias' with version 1

I am assuming my setup does not have some libraries that they are using and I need to incorporate it. 

Any chance anyone has an idea how to do it. Fairly new building custom libraries with c++.

**Comment by jiuqiant** [comment]
akamzin@, we saw a similar question previously. Please see more details at https://github.com/google/mediapipe/issues/35
