### ISSUE TITLE
Static linking of OpenCV?

### ISSUE THREAD

**Issue by joachimneu** [google/mediapipe#510]
I am building a demo app for Mac on top of the face detection desktop example. To make sharing it easier, I would like to be able to statically link OpenCV and distribute one binary where everything runs out of the box. (How) is it possible to change the `BUILD` files of Bazel to achieve static linking of OpenCV?

**Comment by jiuqiant** [comment]
Should be trivial to switch to use static libraries.

You need to modify the `opencv` cc_rule in [the opencv_macos.BUILD](https://github.com/google/mediapipe/blob/master/third_party/opencv_macos.BUILD) to be something like

```
cc_library(
    name = "opencv",
    srcs = glob(
        [
            "local/opt/opencv@3/lib/libopencv_core.a",
            "local/opt/opencv@3/lib/libopencv_calib3d.a",
            "local/opt/opencv@3/lib/libopencv_features2d.a",
            "local/opt/opencv@3/lib/libopencv_highgui.a",
            "local/opt/opencv@3/lib/libopencv_imgcodecs.a",
            "local/opt/opencv@3/lib/libopencv_imgproc.a",
            "local/opt/opencv@3/lib/libopencv_video.a",
            "local/opt/opencv@3/lib/libopencv_videoio.a",
        ],
    ),
    hdrs = glob(["local/opt/opencv@3/include/opencv2/**/*.h*"]),
    includes = ["local/opt/opencv@3/include/"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
```

**Comment by joachimneu** [comment]
Thanks for the swift reply. With this I get a bunch of unresolved symbols:

```
Undefined symbols for architecture x86_64:
  "_AVCaptureSessionPresetMedium", referenced from:
      CvCaptureCAM::startCaptureDevice(int) in libopencv_videoio.a(cap_avfoundation_mac.mm.o)
  "_AVFileTypeAppleM4V", referenced from:
      CvVideoWriter_AVFoundation::CvVideoWriter_AVFoundation(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, double, CvSize, int) in libopencv_videoio.a(cap_avfoundation_mac.mm.o)
...
```

Is it possible to statically link the OpenCV libraries (and perhaps some select dependencies) but leave most basic libraries dynamically linked, such as those provided with the system?

**Comment by jiuqiant** [comment]
Okay, I see the issue now. Basically, OpenCV relies on the other packages such as ffmpeg, libavformat, dc1394 and etc. Unless we manually link all the static libraries of those dependencies into the srcs field of [the opencv cc_library rule](https://github.com/google/mediapipe/blob/master/third_party/opencv_macos.BUILD), we will see undefined symbols. 

A similar issue was asked before: https://answers.opencv.org/question/198721/after-turning-build_shared_libs-to-off-there-are-too-many-undefined-references/

**Comment by jiuqiant** [comment]
This [blog](https://xiomarg.github.io/blog/How-to-build-machine-independent-Mac-OS-app-with-OpenCV/) might be useful. It describes how to build a machine-independent Mac OS app with OpenCV.

**Comment by joachimneu** [comment]
An example of how to package a Mediapipe-powered backend with a macOS frontend app can be found here: https://github.com/tse-group/magicmask/tree/master/frontend (see the `{notarize,package,update}.sh` scripts)

Note that there might be better (ie, more robust) ways of doing this, but it's a starting point.

**Comment by jiuqiant** [comment]
@joachimneu, thanks for the pointer!
