### ISSUE TITLE
Import or Include the classification of poses for Javascript like the one made for Python 

### ISSUE THREAD

**Issue by ver0z** [google/mediapipe#5103]
### MediaPipe Solution (you are using)

Pose

### Programming language

Javascript

### Are you willing to contribute it

Yes

### Describe the feature and the current behaviour/state

The actual pose detection for javascript does not have the K-NN model to classify poses like the ones made for Python or Android, so is it possible to adapt that feature for the Web/Javascript code ? Is there somewhere this working ?

### Who will benefit with this feature?

This will affect positively the Web developers in general 

### Please specify the use cases for this feature

It will help to keep track on how some task like squad is happening and to count the effective number of repetitions

**Comment by schmidt-sebastian** [comment]
We are no longer maintaining the legacy JS solutions. The new Pose Landmarker Task offers the same functionality for all tasks: https://developers.google.com/mediapipe/solutions/vision/pose_landmarker
