### ISSUE TITLE
Typo on the Media Studio Documentation Page

### ISSUE THREAD

**Issue by Leftaf** [google/mediapipe#5104]
### Description of issue (what needs changing)

The documented options : *category_allow_list* and *category_deny_list* are defined in the source as [category_allowlist] and [category_denylist]

### Clear description

Just took me time so find out this "to" simple difference which generate an error during usage.

### Correct links

https://developers.google.com/mediapipe/solutions/vision/object_detector#configurations_options

### Parameters defined

category_allowlist

category_denylist

**Comment by kuaashish** [comment]
Hi @Leftaf,

Thank you for bringing this to our attention. We have initiated an internal pull request to address these typos, and we will inform you once it has been merged.

**Comment by kuaashish** [comment]
We are closing this issue now, As the internal PR has been successfully merged, and the corresponding changes have been implemented in the documentation. You can review the updated documentation at the following link: https://developers.google.com/mediapipe/solutions/vision/object_detector#configurations_options
