### ISSUE TITLE
 errors encountered resolving select() keys for //mediapipe/framework:port

### ISSUE THREAD

**Issue by KakaWan** [google/mediapipe#5105]
```
ERROR: Traceback (most recent call last):
         File "C:/users/mahesa/_bazel_mahesa/wl6bzqgh/external/build_bazel_rules_apple/apple/internal/rule_support.bzl", line 217, column 36, in <toplevel>
                 deps_cfg = apple_common.multi_arch_split,
 Error: 'apple_common' value has no field or method 'multi_arch_split'
 ERROR: error loading package 'mediapipe/gpu': at C:/users/mahesa/_bazel_mahesa/wl6bzqgh/external/build_bazel_rules_apple/apple/ios.bzl:33:5: at C:/users/mahesa/_bazel_mahesa/wl6bzqgh/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl:75:5: initialization of module 'apple/internal/rule_support.bzl' failed
 ERROR: C:/users/mahesa/mediapipe_repo/mediapipe/mediapipe/framework/BUILD:1003:11: errors encountered resolving select() keys for //mediapipe/framework:port
 ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.779s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```
i'm stack in here, can anyone help me?

_Originally posted by @KakaWan in https://github.com/google/mediapipe/issues/724#issuecomment-1918806224_

**Comment by kuaashish** [comment]
HI @KakaWan,

Could you kindly share the comprehensive steps you are currently executing based on the documentation? Additionally, could you provide details on the versions of Windows, Python, and Bazel being used, along with the complete error log? 

Furnishing this information will enable us to better comprehend the issue at hand and assist you more effectively. We encourage you to use the provided [templates](https://github.com/google/mediapipe/issues/new/choose) to convey these details.

Thank you!!

**Comment by KakaWan** [comment]
I solved this problem yesterday. You just need update **build_bazel_rules_apple** to 3.2.1. You can modify the following text in the mediapipe/WORKSPACE：

`http_archive(
    name = "build_bazel_rules_apple",
    sha256 = "9c4f1e1ec4fdfeac5bddb07fa0e872c398e3d8eb0ac596af9c463f9123ace292",
    url = "https://github.com/bazelbuild/rules_apple/releases/download/3.2.1/rules_apple.3.2.1.tar.gz",
    patches = [
        # Bypass checking ios unit test runner when building MP ios applications.
        "@//third_party:build_bazel_rules_apple_bypass_test_runner_check.diff"
    ],
    patch_args = [
        "-p1",
    ],
)`

**Comment by kuaashish** [comment]
Thank you for confirming. May we proceed to close this issue now, considering that it has been resolved?

**Comment by arksoft-systems** [comment]
solved the problem i had
