### ISSUE TITLE
Re-adapting AutoFlip for usage on video streams

### ISSUE THREAD

**Issue by thesofakillers** [google/mediapipe#511]
From [this answer](https://github.com/google/mediapipe/issues/471#issuecomment-595951556) in #471 and from running AutoFlip myself, I see that in general AutoFlip processes an input video in around real-time, i.e. it takes around the length of time of the video to process the video.

As such, in terms of processing time, re-adapting AutoFlip for usage on video streams (for example, usage on a webcam) rather than a pre-existing video should be feasible. 

That being said, does the AutoFlip architecture even allow such a task? If I'm not mistaken, there are several steps such as the motion smoothing (i.e. the jitter removal) or the shot boundary detection that require sets of frames as inputs, while typically inference on video streams acts on a single frame basis. 

A workaround I'm considering is delaying the incoming stream by a number of frames (seconds even), allowing for chunks of the stream to be inputted as video so to allow the jitter removal, scene detection and other multi-frame calculators to work appropriately. That being said, this may cause issues at chunk boundaries if say they occur mid-scene.

In your experience, is there a minimum length for an input video for AutoFlip to work? Do you have any other suggestions for re-adapting it for usage on video streams? Is it even possible with the given architecture?

Thank you!

**Comment by ndimension** [comment]
Hi @thesofakillers, you are correct in thinking that autoflip can be adapted for real-time usage.  There shouldn't be any big blockers to making this work.  You should be able to look at examples that run directly from the camera input and modify the autoflip graph to use those calculators at the input and output instead of reading from and writing to a file.  

Autoflip does introduce some latency (delay) because of scene buffering.  The parameter that controls this is called _max_scene_size_ and reducing this number will reduce the latency.  However, for inputs that are one long scene (like a webcam) users may notice a jump in camera position when each buffer is processed and flushed.  For better real-time quality we should make changes to maintain the crop position across buffering.  I will discuss internally making this update.

If you create an autoflip graph to work on a real-time stream please share and I can help tune it for your application.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by thesofakillers** [comment]
Hi @ndimension, @jiuqiant. Thank you for replying earlier, I've only recently gotten back to this. 

I've been trying to get this to work by modifying AutoFlip's graph as suggested by @ndimension above. I'm basing my modifications on the [object_detection_desktop_live graph](https://github.com/thesofakillers/mediapipe/blob/master/mediapipe/graphs/object_detection/object_detection_desktop_live.pbtxt), which works fine on my setup. The goal is to test it on my webcam and then move on to an ip video stream later.

However, when I try running my modified graph with 
```bash
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip \
--calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt \
--input_side_packets=aspect_ratio=1:2
```
The graph prints out as expected, but then mediapipe seems to hang on the following:
```bash
I20200525 19:10:24.033686 525520320 demo_run_graph_main.cc:69] Initialize the calculator graph.
I20200525 19:10:24.037720 525520320 demo_run_graph_main.cc:73] Initialize the camera or load the video.
I20200525 19:10:27.993374 525520320 demo_run_graph_main.cc:94] Start running the calculator graph.
I20200525 19:10:27.993629 525520320 demo_run_graph_main.cc:99] Start grabbing and processing frames.
```

---

The changes I made to get to this point can be found at my [fork](https://github.com/thesofakillers/mediapipe/tree/live) (on the `live` branch). In particular I:

- Changed [my AutoFlip graph](url) so that
  - we use graph-level defined `input_stream` and `output_stream`
  - we no longer use OpenCVVideoEncoder and Decoder calculators
  - `max_scene_size` is set to `60`. Keeping the default of `600` does not seem to resolve the issue.
  - There is a FlowLimiterCalculator. Omitting this calculator does not seem to resolve the hanging error 
- Changed [demo_run_graph_main.cc](url) so that we can pass input side packets, in particular the side packet desiring the aspect ratio
- Changed AutoFlip's BUILD so to 
  - reflect the change in calculators
  - Make use of `demo_run_graph_main.cc` so that I can input and output live video

---

I've tried figuring out why it _appears_ to be hanging. It seems like the hanging begins [here](https://github.com/thesofakillers/mediapipe/blob/a07ed0fd7fb00cb2bb126861c3f20fb082331504/mediapipe/examples/desktop/demo_run_graph_main.cc#L126-L129), which seems to suggest that AutoFlip is not sending any result packets. I'm not really sure why it is doing that. Perhaps I'm missing a calculator from the end of my graph. 

I would greatly appreciate any sort of suggestions on how to unblock this. Thank you very much for your work and help thus far!

**Comment by thesofakillers** [comment]
Could we reopen this issue?

**Comment by thesofakillers** [comment]
Hi @ndimension, have you had a chance to take a look at this? Thanks!

**Comment by AlexDevM** [comment]
Hi @ndimension, @thesofakillers 

I am very interesting at this topic. May be you have some updates on it ? Will be appreciated for any information.

**Comment by moses5407** [comment]
Also very interested in a real time autoflip

**Comment by miguel-batista** [comment]
Any updates on this issue?
