### ISSUE TITLE
Windows 10 cannot install mediapipe via pip

### ISSUE THREAD

**Issue by AnthonyvW** [google/mediapipe#5117]
### OS Platform and Distribution

Windows 10 Version 22H2

### Programming Language and version

Python 3.12.0

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

0.10.9

### Android AAR (if android)

None

### Describe the problem

Tried to install mediapipe via pip

### Complete Logs

```shell
pip install mediapipe  
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

**Comment by kuaashish** [comment]
Hi @AnthonyvW,

It seems you are using an unsupported Python version. The recommended versions are between 3.8 and 3.11, as specified in the Python Setup [documentation](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions). Version 3.12 is not yet supported in Mediapipe. Kindly use the recommended version and inform us if you encounter any issues during the Mediapipe build process with Pip.

Thank you

**Comment by AnthonyvW** [comment]
That solved the issue.
