### ISSUE TITLE
User data pointer in C API callbacks

### ISSUE THREAD

**Issue by chnoblouch** [google/mediapipe#5118]
The new tasks C API allows the user to process data asynchronously by setting a result callback in the task options.
Here's the callback for the hand landmarker as an example:
```c
// The options for configuring a MediaPipe hand landmarker task.
struct HandLandmarkerOptions {
  ...
  
  typedef void (*result_callback_fn)(HandLandmarkerResult* result,
                                     const MpImage& image,
                                     int64_t timestamp_ms,
                                     char* error_msg);
  result_callback_fn result_callback;
};
```

The issue I'm having now is that when this function is called, I can't use the results because I have no way of accessing my application data. The only workaround I can think of is creating a global variable for the application data, but I'd like to avoid global state in my code.

This is why C APIs usually implement callbacks using a function pointer along with a user-provided context pointer. The context pointer is passed to the callback function together with the results. Here's an example from the [WebGPU C API](https://github.com/webgpu-native/webgpu-headers/blob/main/webgpu.h) (The context pointer is called `userdata` here):
```c
typedef void (*WGPUBufferMapAsyncCallback)(WGPUBufferMapAsyncStatus status, WGPU_NULLABLE void * userdata) WGPU_FUNCTION_ATTRIBUTE;

...

WGPU_EXPORT void wgpuBufferMapAsync(WGPUBuffer buffer, WGPUMapModeFlags mode, size_t offset, size_t size, WGPUBufferMapAsyncCallback callback, WGPU_NULLABLE void * userdata) WGPU_FUNCTION_ATTRIBUTE;
```

I think adding a similar user data pointer to the C API would make it much more useful:
```diff
struct HandLandmarkerOptions {
  ...
  
  typedef void (*result_callback_fn)(HandLandmarkerResult* result,
                                     const MpImage& image,
                                     int64_t timestamp_ms,
+                                    void *user_data,
                                     char* error_msg);
  result_callback_fn result_callback;
};

...

MP_EXPORT int hand_landmarker_detect_async(void* landmarker,
                                           const MpImage& image,
                                           int64_t timestamp_ms,
+                                          void *user_data,
                                           char** error_msg);
```

**Comment by kuaashish** [comment]
Hi @chnoblouch,

Apologies for delayed response, Could you please confirm whether you are still seeking a resolution to this issue, or if the matter has been resolved from your end?

Thank you!!

**Comment by schmidt-sebastian** [comment]
Will add this. We have encountered the same problem.

**Comment by schmidt-sebastian** [comment]
Sorry - I looked at this more and this won't work for our Vision tasks. Our Async API doesn't have a 1:1 mapping between invocation and callback result. So to do this internally, we would have to track the user-context objects based on the input timestamp that you provide. SInce we also do not guarantee that we invoke the callback is called for each invocation of the async loop (since we can skip frames), this leads to a pretty unreliable API design. At this point, I would prefer if logic like this lived in the user codebase. For APIs that follow the patter `do_something_async(done_callback())` your suggestion is valid though.
