### ISSUE TITLE
WebGL context get lost on iOS if Safari went into background

### ISSUE THREAD

**Issue by gumellupf** [google/mediapipe#5122]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

iOS 17.0.2, 

### Mobile device if the issue happens on mobile device

iPhone 12

### Browser and version if the issue happens on browser

Safari 17.0.2

### Programming Language and version

TypeScript 4.8.0

### MediaPipe version

^0.5.1675471629

### Solution

@mediapipe/holistic

### Describe the actual behavior

We implemented the web solution of holistic in our web app. After some time we receive randomly a 'webGL: context lost' error. Mediapipe is not able to start anymore. Even if we reload or open a new tab. To solve the issue, we need to restart the Safari App. Then it works again. To force the issue, you need to move Safari into the background and come back after some time. Then you will observe the issue.

### Describe the expected behaviour

WeGL context should not be lost or at least restored, so that mediapipe still works. 

### Standalone code/steps you may have used to try to get what you need

```shell
I was also able to reproduce it with your example Project of Holistic: https://codepen.io/mediapipe/pen/LYRRYEw

1. Open example Project
2. Start Holistic
3. Move Safari into background 
4. Open other Apps
5. Move back into Safari tab
6. Reload and observe issue in console

Note: appears randomly. You might need to repeat these steps multiple times. Sometimes it appears earlier. Sometimes not.
```

### Other info / Complete Logs

```shell
• WebGL: context lost.
Error: Uncaught (in promise): TypeError: null is not an object (evaluating 't.alpha') 
_emscripten_webgl_get_contex_attributes@https://192.168.178.21:4200/assets/mediapipe/holistic_solution_simd_wasm_bin.js:9:206992
<?>.wasm-function[6604]@[wasm code]
<?>.wasm-function[6603]@[wasm code]
<?>.wasm-function[5972]@[wasm code]
<?>.wasm-function[225]@[wasm code]
<?>.wasm-function[195]@[wasm code]
SolutionWasm$send@
[...]
• ERROR - Pn@https://192.168.178.21:4200/main.js:23:10961
```

**Comment by ayushgdev** [comment]
Hello @gumellupf 
We have upgraded the MediaPipe Legacy Solutions to new MediaPipe solutions **including Holistic Solution**.
You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check new MediaPipe solutions which can help you more easily build and customize ML solutions for your applications.

Would you please try using the new [HolisticLandmarker task APIs](https://github.com/google/mediapipe/blob/master/mediapipe/tasks/web/vision/holistic_landmarker/holistic_landmarker.ts) and let us know if the problem persists?
