### ISSUE TITLE
GPU Delegate is not yet supported for Windows

### ISSUE THREAD

**Issue by maxmelichov** [google/mediapipe#5126]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Windows 10

### Programming Language and version

Python

### MediaPipe version

 0.10.9

### Solution

face_landmarker

### Describe the actual behavior

Just trying to use mediapipe with GPU on windows

### Describe the expected behaviour

to work...

### Standalone code/steps you may have used to try to get what you need

```shell
`
# STEP 1: Import the necessary modules.
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import time

# STEP 2: Create an FaceLandmarker object.
base_options = python.BaseOptions(model_asset_path='face_landmarker.task')
options = vision.FaceLandmarkerOptions(base_options=base_options,
                                       output_face_blendshapes=True,
                                       output_facial_transformation_matrixes=True,
                                       num_faces=1)

detector = vision.FaceLandmarker.create_from_options(options)

# STEP 3: Load the input image.
image = mp.Image.create_from_file("business-person.png")
start_time = time.time()
# STEP 4: Detect face landmarks from the input image.
detection_result = detector.detect(image)
end_time = time.time()
print(end_time - start_time)
# STEP 5: Process the detection result. In this case, visualize it.
annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)
plt.imshow(cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))`


Error:
`NotImplementedError: GPU Delegate is not yet supported for Windows`
```

**Comment by kuaashish** [comment]
Hi @maxmelichov,

Currently, GPU support in Python is available for Regular Linux and macOS from version 0.10.8 onwards. Unfortunately, Windows support is not yet available. For additional information, please refer to our release [page](https://github.com/google/mediapipe/releases/tag/v0.10.8) Python update section.

Thank you
