### ISSUE TITLE
Issue Implementing Mediapipe Tasks example using Jetpack Compose

### ISSUE THREAD

**Issue by PeterZegarek** [google/mediapipe#5132]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Android 11

### Task name (e.g. Image classification, Gesture recognition etc.)

Hand Landmarker

### Programming Language and version (e.g. C++, Python, Java)

Kotlin

### Describe the actual behavior

Just opening camera - Mediapipe is not running / displaying as expected

### Describe the expected behaviour

Mediapipe runs as usual.

### Standalone code/steps you may have used to try to get what you need

```shell
I have to try to convert the provided code for XML views into a Jetpack Compose accessible solution. I have just been having general issues in terms of what to do as I am not familiar with Views and I built my app using Jetpack Compose.

This is the example I am going off of
https://github.com/googlesamples/mediapipe/tree/main/examples/hand_landmarker/android
```

### Other info / Complete Logs

```shell
If there is a more reasonable way to implement this than using Tasks, please do let me know.
```

**Comment by PeterZegarek** [comment]
Hello, I just wanted to follow up and ask if there was any progress or anyone working on this issue. Thank you.

**Comment by PeterZegarek** [comment]
Following up again. Are there any plans to make this available for Jetpack Compose?

**Comment by kuaashish** [comment]
Hi @PeterZegarek,

Apologies for the delayed response. Currently, we have not tested the scenario with JetPack Compose, so our ability to assist you extensively is limited. However, we encourage you to submit a new feature request for integrating with Jetpack Compose through [this link](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Afeature&projects=&template=14-feature-request-issue-template.yaml). 

Please outline the potential community benefits in your request. Once submitted, we will share it with our team. Depending on discussions and demand, we may consider implementing this feature in the future.

Thank you!!
