### ISSUE TITLE
Opencv calculators

### ISSUE THREAD

**Issue by bhack** [google/mediapipe#515]
I see many calculators (specially in image,video) heavily rely on Opencv lib.
Do you plan to add needed operations in TF  so that pipeline could run in Tensorflow Graph/Runtime?

**Comment by jiuqiant** [comment]
Can you clarify your request? 
Is your reqeust to add opencv tf ops to reproduce this pipeline in TensorFlow or add a mediapipe tf op to run the pipeline as a node in TensorFlow?

**Comment by bhack** [comment]
Yes partially both but mainly if at some point we could run this pipelines directly in Tensorflow runtime eventually to take some future advantage of the graph transformations/optimizzations infra passes or eventually codegen when possibile and minimize dependency on the target device.

**Comment by Zumbalamambo** [comment]
@bhack  any plans on releasing the python version of mediapipe?

**Comment by bhack** [comment]
@Zumbalamambo for python subscribe to https://github.com/google/mediapipe/issues/444

**Comment by bhack** [comment]
@jiuqiant Are you in contact with TFRT @mhong team?
I don't know if the new TFRT runtime could play a role in the context of this thread.

**Comment by mgyong** [comment]
@bhack Currently we depend on opencv for rendering and basic image transformations. We are evaluating constantly if there are alternative more lightweight libraries that perform similar task to OpenCV that we can use as a dependence library for MediaPipe.

**Comment by bhack** [comment]
@mgyong I hope that you can contribute some image transformations in Tensorflow/addons.
