### ISSUE TITLE
mediapipe mphands model error

### ISSUE THREAD

**Issue by junjunjunman** [google/mediapipe#5150]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

windows 10

### MediaPipe Tasks SDK version

3.8.1

### Task name (e.g. Image classification, Gesture recognition etc.)

gesture recognition

### Programming Language and version (e.g. C++, Python, Java)

python 3.10.11

### Describe the actual behavior

Traceback (most recent call last):   File "c:\Users\성준\Desktop\project\a.py", line 8, in <module>     hands = mpHands.Hands()   File "C:\Users\성준\AppData\Roaming\Python\Python310\site-packages\mediapipe\python\solutions\hands.py", line 114, in __init__     super().__init__(   File "C:\Users\성준\AppData\Roaming\Python\Python310\site-packages\mediapipe\python\solution_base.py", line 265, in __init__     validated_graph.initialize( FileNotFoundError: The path does not exist.

### Describe the expected behaviour

hands tracking

### Standalone code/steps you may have used to try to get what you need

```shell
import cv2
import mediapipe as mp
import time

cap = cv2.VideoCapture(0)

mpHands = mp.solutions.hands
hands = mpHands.Hands()
mpDraw = mp.solutions.drawing_utils

pTime = 0
cTime = 0

while True:
    success, img = cap.read()
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = hands.process(imgRGB)
    # print(results.multi_hand_landmarks)

    if results.multi_hand_landmarks:
        for handLms in results.multi_hand_landmarks:
            for id, lm in enumerate(handLms.landmark):
                # print(id, lm)
                h, w, c = img.shape
                cx, cy = int(lm.x * w), int(lm.y * h)
                print(id, cx, cy)
                # if id == 4:
                cv2.circle(img, (cx, cy), 15, (255, 0, 255), cv2.FILLED)

            mpDraw.draw_landmarks(img, handLms, mpHands.HAND_CONNECTIONS)

    cTime = time.time()
    fps = 1 / (cTime - pTime)
    pTime = cTime

    cv2.putText(img, str(int(fps)), (10, 70), cv2.FONT_HERSHEY_PLAIN, 3,
                (255, 0, 255), 3)

    cv2.imshow("Image", img)
    cv2.waitKey(1)
```

error
```
Traceback (most recent call last):
  File "c:\Users\성준\Desktop\project\a.py", line 8, in <module>
    hands = mpHands.Hands()
  File "C:\Users\성준\AppData\Roaming\Python\Python310\site-packages\mediapipe\python\solutions\hands.py", line 114, in __init__
    super().__init__(
  File "C:\Users\성준\AppData\Roaming\Python\Python310\site-packages\mediapipe\python\solution_base.py", line 265, in __init__
    validated_graph.initialize(
FileNotFoundError: The path does not exist.
```

**Comment by kuaashish** [comment]
Hi @junjunjunman,

**Comment by kuaashish** [comment]
Hi @junjunjunman,

From the code snippet you provided and Version which you currency using, it appears you are using the legacy hands solution. Please note that this solution has been upgraded and is now integrated into the Hand Landmarker Task API, as explained in the [documentation](https://developers.google.com/mediapipe/solutions/guide#legacy)(We have discontinued support for upgraded legacy solutions, and we are no longer maintaining them).

The upgraded Task API's are designed to offer better performance compared to the legacy solutions and are easier to adopt for your use case. We encourage you to explore our new Hand Task API following the guidelines provided [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker). You can find the Python guide [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/python), along with a [Python notebook example](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/hand_landmarker/python/hand_landmarker.ipynb). Additionally, Please let us know if you observe similar behaviour in the new Task API as well.

Thank you!!

**Comment by junjunjunman** [comment]
I fixed this error by formatting window thank you for your efforts.

**Comment by kuaashish** [comment]
Hi @junjunjunman,

Thank you for confirming. May we update the issue status to resolved and proceed to close it now?
