### ISSUE TITLE
tasks-vision/holistic - When the announced update scheduled for mid-January will take place.

### ISSUE THREAD

**Issue by ThiruSS** [google/mediapipe#5154]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Ubuntu

### Task name (e.g. Image classification, Gesture recognition etc.)

tasks-vision/holistic

### Programming Language and version (e.g. C++, Python, Java)

Python, Javascript

### Describe the actual behavior

tasks-vision/holistic not available yet

### Describe the expected behaviour

release a new version which includes tasks-vision/holistic

### Standalone code/steps you may have used to try to get what you need

```shell
In the response: https://github.com/google/mediapipe/issues/5060#issuecomment-1882643523. It was indicated that a new release integrating tasks-vision/holistic was expected by mid-January. However, there seems to have been a delay, as updates or specific release dates have not been provided since that announcement.
```

**Comment by DehTop** [comment]
I am also very interested in updates regarding this question :)

**Comment by joansc** [comment]
+1

**Comment by mvazquezgts** [comment]
+1 Any update?

**Comment by arpu** [comment]
looks like [v0.10.10](https://github.com/google/mediapipe/releases/tag/v0.10.10) as it! 

but i cannot find the task  for HolisticLandmarker.createFromOptions  modelAssetPath @schmidt-sebastian any hint? 
tested with 
```
    modelAssetPath: `https://storage.googleapis.com/mediapipe-models/holistic_landmarker/holistic_landmarker_lite/float16/1/holistic_landmarker_lite.task`,

```
but the file is not access able

**Comment by jijamik** [comment]
I think you can find the model here: https://storage.googleapis.com/mediapipe-models/holistic_landmarker/holistic_landmarker/float16/latest/holistic_landmarker.task
But I get the following errors on v0.10.10: 
gl_graph_runner_internal_image.cc:68] Adding Image to stream input_frames_image was not ok: UNIMPLEMENTED: Graph has errors

new wasm build has been added since 0.10.10-rc.20240222, before that i was not even able to load the model, now it load but won't run

```js
holisticLandmarker = await HolisticLandmarker.createFromOptions(vision, options);
console.log(holisticLandmarker) // this is ok since 0.10.10-rc.20240222
...
let holisticResults = holisticLandmarker.detectForVideo(videoInput, startTimeMs);
// this dosen't work actually
```

**Comment by DehTop** [comment]
> I think you can find the model here: https://storage.googleapis.com/mediapipe-models/holistic_landmarker/holistic_landmarker/float16/latest/holistic_landmarker.task

**Comment by schmidt-sebastian** [comment]
Feature launched. We will track GPU support in #5166.
