### ISSUE TITLE
Pose landmark detection: Pose of smaller person not recognized in full image but in clipping

### ISSUE THREAD

**Issue by ixd-hof** [google/mediapipe#5157]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

MacOS 14.2.1

### Browser and version if the issue happens on browser

Chrome Version 121.0.6167.184 (Official Build) (arm64)

### Programming Language and version

Javascript

### Solution

Pose

### Describe the actual behavior

Pose of person (240 px height) on full frame (1920x1080) is not recognized.

### Describe the expected behaviour

Pose of person (240 px height) on full frame (1920x1080) should be recognized.

### Standalone code/steps you may have used to try to get what you need

```shell
To be sure there's no fault in my code i verified the result in the Pose demo:
https://mediapipe-studio.webapps.google.com/demo/pose_landmarker

Model: Pose Landmarker Heavy

Pose of person (240 px height) on full frame (1920x1080) is not recognized.
In a cutout of the person's area (690x460 px) without scaling the person is recognized.

Large frame: https://nextcloud.hof-university.de/s/9isqbnJSkjTnD9X
Cutout: https://nextcloud.hof-university.de/s/snnxZBCPPNJPZ45

The person should be recognized in the larger image, since the pixels are the same. Is there maybe a way to disable scaling in the background, which could be the reason for the effect?
```

**Comment by kuaashish** [comment]
Hi @ixd-hof,

If people are too far from the camera, roughly beyond 14 feet or 4 meters, our Pose Landmaker model might not be able to detect them. You can find the same information in our [model card](https://storage.googleapis.com/mediapipe-assets/Model%20Card%20BlazePose%20GHUM%203D.pdf) under the 'Out of Scope Applications' section, as stated below:

> "_People too far away from the camera (e.g. further than 14 feet/4 meters)_"

Thank you!!
