### ISSUE TITLE
Inquiry about MediaPipe availability on Raspberry Pi 5 for hand tracking project

### ISSUE THREAD

**Issue by Jay042003** [google/mediapipe#5158]
Dear Google MediaPipe Team,

I'm writing to inquire about the availability of MediaPipe, particularly the hand tracking solution, on Raspberry Pi 5. I'm working on a project that requires real-time hand tracking, and I'm interested in using MediaPipe on an RPi 5 due to its compact size and processing power.

I've reviewed the official MediaPipe documentation and searched online forums, but I haven't found any definitive information about official support for RPi 5. While I'm comfortable with technical tasks and coding, I'm unsure whether unofficial methods are reliable or recommended.

Given my project's requirements and my technical background, could you please clarify the following:

Is there official support for MediaPipe, specifically hand tracking, on Raspberry Pi 5?
If not, are there any recommended alternative solutions for achieving real-time hand tracking on RPi 5?
If using unofficial methods is the only option, could you point me towards reliable resources and guidance to ensure compatibility and avoid potential risks?
I know I should probably wait but I am a student and I am considering to buy Raspberry Pi 5 for a project but it is not possible without mediapipe.
I appreciate your time and assistance in clarifying this matter.

**Comment by kuaashish** [comment]
Hi @Jay042003,

Currently, official support for Raspberry Pi 5 is not available. Edge device support is confirmed on Raspberry Pi 4, and we have successfully tested this scenario. Documentation for implementation on Pi 4 can be found [here](https://github.com/googlesamples/mediapipe/tree/main/examples/hand_landmarker/raspberry_pi).

As of now, no community-developed support has come to our attention for Pi 5. Unfortunately, we cannot provide alternative resources. However, considering the software similarities between Raspberry Pi 4 and 5, we suggest testing it yourself. Please inform us of your success. We will notify you once official support for Pi 5 is available. We have already brought this issue to our Engineering team, but we cannot provide you with any timeline for availability.

Thank you for your understanding.
