### ISSUE TITLE
Visibility Scores Remain at 0 for Clearly Visible Joints in Tennis Application

### ISSUE THREAD

**Issue by Nit-Rathore** [google/mediapipe#5159]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)
  
Yes

### OS Platform and Distribution

Ubuntu 22.04

### Programming Language and version

Python: 3.8.17

### MediaPipe version

 0.10.9

### Solution

Pose

### Describe the actual behavior

Visibility scores for clearly visible joints remain at 0, and presence scores are high across all joints, making it challenging to filter based on keypoint reliability for tennis movement analysis.

### Describe the expected behaviour

Visibility scores should reflect the actual visibility of joints in the video frames, with non-zero values for clearly visible joints. Presence scores should provide a meaningful measure to filter out less reliable keypoints.

### Standalone code/steps you may have used to try to get what you need

```shell
1. Set up a MediaPipe 0.10.9 environment on Ubuntu 22.04.
2. Run the pose estimation on a sample tennis video where players are in clear view and actively moving.
3. Observe the output keypoints, focusing on the visibility and presence scores.
```

### Other info / Complete Logs

```shell
In my application, which focuses on analyzing tennis players' movements, I've observed that the visibility scores for keypoints/joints provided by Pose consistently remain at 0, even when the joints are clearly visible in the video frames. This issue is particularly prevalent in dynamic scenes common in tennis, where players are frequently moving and changing orientation.

Additionally, the presence scores for all joints are reported with high confidence, which complicates filtering out unreliable keypoints based on my application's needs. This behavior affects the reliability of pose estimation and subsequent analysis in my tennis-focused application.
```

**Comment by kuaashish** [comment]
Hi @Nit-Rathore,

Could you please provide a detailed outline of the steps you are following, making reference to the documentation? Alternatively, if possible, could you share the complete standalone code to help us reproduce and better understand the issue?

Thank you!!

**Comment by Nit-Rathore** [comment]
Description of steps:

The code loads a pose estimation model using MediaPipe library.
It defines a function to detect human pose keypoints in a video, with options to specify sport type, video path, output paths for CSV and video files, etc.
It checks the validity of specified parameters such as hand and sport.
Directories are created for saving CSV and video files if specified.
A CSV object is initialized to store keypoints.
The video file is opened, and properties such as frame rate, height, and width are extracted.
Frames are processed based on the device (CPU or GPU) using appropriate functions for this case only CPU implementation is shown
Additional functions and steps for processing frames are called or defined within the script.

**Comment by kuaashish** [comment]
Hi @Nit-Rathore,

After reviewing the provided standalone code, it appears that you are currently using the outdated pose solution, which is no longer maintained, and we have ceased support for it. This functionality has been integrated into the new Pose Landmarker Task API, detailed [here](https://developers.google.com/mediapipe/solutions/guide#legacy).

We encourage you to explore the features of our updated Pose Landmarker Task API and suggest replacing the legacy Pose with the new Pose Landmarker. The new solution offers improved performance and additional functionality compared to the legacy pose solution. You can find the guide for the new Pose Landmarker [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker), along with specific instructions for implementation in the Python platform provided [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python). Additionally, a corresponding example Colab notebook is available for reference [here](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/pose_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Pose_Landmarker.ipynb).

Please report any observed behavior, ensuring to check if similar issues persist in the upgraded task API. We value your feedback. Unfortunately, beyond this, there is limited action we can take to address the specific issue you are facing.

Thank you!!

**Comment by ayushgdev** [comment]
Hello @Nit-Rathore 
From the code excerpt, the pose solution being used is indeed obsolete. This is evident in the function
```python
def load_model(model_complexity: int = 2, cpu: bool = True):
   """Return model dictionary."""
   if cpu:
     mp_pose = mp.solutions.pose                      # <= This usage from mediapipe.solutions is obsolete
     return {
       "model_obj": mp_pose.Pose(
         min_detection_confidence=0.2,
         min_tracking_confidence=0.2,
         model_complexity=model_complexity,
        ),
      ...
      ...
```
The new APIs use `PoseLandmarker` class which requires context manager to be created with `with` keyword, and many other major changes. A very small example snippet:
```python
import mediapipe as mp

BaseOptions = mp.tasks.BaseOptions
PoseLandmarker = mp.tasks.vision.PoseLandmarker
PoseLandmarkerOptions = mp.tasks.vision.PoseLandmarkerOptions
VisionRunningMode = mp.tasks.vision.RunningMode

options = PoseLandmarkerOptions(
    base_options=BaseOptions(model_asset_path=model_path),
    running_mode=VisionRunningMode.IMAGE)

with PoseLandmarker.create_from_options(options) as landmarker:
  # The landmarker is initialized. Use it here.
  # Perform pose landmarking on the provided single image.
  pose_landmarker_result = landmarker.detect(mp_image)
```

Please migrate to our new MediaPipe Tasks API. You can find the documentation [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python)
