### ISSUE TITLE
Exporting a Mediapipe-generated model to Coral USB Accelerator

### ISSUE THREAD

**Issue by dorive** [google/mediapipe#5160]
Hello,

I used this Mediapipe [tutorial](https://developers.google.com/mediapipe/solutions/customization/object_detector) to create my custom object detection model. The inference works well when I perform the detection with the Mediapipe function `detection_result = detector.detect(mp_image)`.

As the next step, I wanted to export the model to `tflite` format in order to use it on a Raspberry Pi 4 with the Coral USB Accelerator. I used `model.export_model('my_model.tflite')`. However, when I check the neural network output tensor using `interpreter.get_output_details()`, I get the following:

`[{'name': 'StatefulPartitionedCall:0', 'index': 431, 'shape': array([1, 12276, 4]), 'shape_signature': array([1, 12276, 4]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:1', 'index': 429, 'shape': array([1, 12276, 2]), 'shape_signature': array([1, 12276, 2]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]`

This is unexpected. I was anticipating four tensors representing the boxes, scores, classes, and total counts. However, I received:

- A tensor with shape (1, 12276, 4), which I assume could be the boxes. The number of rows is quite large, and when I plot them, it does not make much sense.
- A tensor with shape (1, 12276, 2), which is float32. Initially, I thought these could be the scores, but upon further inspection, it doesn't align with the scores from my detection with Mediapipe. For example, my detection with Mediapipe is `Detection(bounding_box=BoundingBox(origin_x=228, origin_y=100, width=59, height=99), categories=[Category(index=None, score=0.926233172416687, display_name=None, category_name='face')`, and I don't see that score in the matrix. To clarify, my dataset has only one category.

Does anyone know how these tensors could be interpreted? Is there a way to export the Mediapipe model in a Coral-friendly format?

Thank you.

**Comment by pontrellob** [comment]
Is anybody looking into resolving this issue?  Now that we are have to use mediapipe to customize models, it sure would be nice to have them run using the Coral Accelerator. It used to work when we could use TensorFlow to customize models.
