### ISSUE TITLE
Multi-person tracking of holistic model

### ISSUE THREAD

**Issue by ChristianNSchmitz** [google/mediapipe#5161]
### MediaPipe Solution (you are using)

v0.10.9

### Programming language

Python

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

We would like to perform body and facial tracking of video footage via the holistic model with more than one person included. We would like to ask you whether such a feature is already possible or in development? Thanks a lot!

### Please specify the use cases for this feature

Research

**Comment by ayushgdev** [comment]
Hello @ChristianNSchmitz 
Post discussion with the team, this feature is not possible right now with holistic model. Also, we don't have any plans to extend our tracking to multi-person tracking anytime soon.

**Comment by Thaina** [comment]
@ayushgdev Is this already possible with the new version? Are there any sample for upgraded holistic system with multi body?

**Comment by antiero** [comment]
Multi-person holistic tracking would be amazing - is this possible in an upcoming version?
