### ISSUE TITLE
Remove unnecessary checks for API handles

### ISSUE THREAD

**Issue by elfring** [google/mediapipe#517]
[Extra checks are not needed for zero API handles](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDeleteProgram.xhtml "Delete a program object.") in functions like the following.
- [MaskOverlayCalculator](https://github.com/google/mediapipe/blob/61bc4556af586bb3837f17187568d1345b3ee8f5/mediapipe/calculators/image/mask_overlay_calculator.cc#L273 "Destructor for MaskOverlayCalculator")
- [GlhCreateProgram](https://github.com/google/mediapipe/blob/d68f5e416903e3d756ebe07d08c4a3b911741a91/mediapipe/gpu/shader_util.cc#L130 "GlhCreateProgram function")
- [QuadRenderer::GlTeardown](https://github.com/google/mediapipe/blob/d68f5e416903e3d756ebe07d08c4a3b911741a91/mediapipe/gpu/gl_quad_renderer.cc#L90 "QuadRenderer::GlTeardown function")
- [SobelEdgesCalculator::GlTeardown](https://github.com/google/mediapipe/blob/d68f5e416903e3d756ebe07d08c4a3b911741a91/mediapipe/calculators/image/sobel_edges_calculator.cc#L231 "SobelEdgesCalculator::GlTeardown function")

**Comment by elfring** [comment]
I would appreciate a bit more information for this issue.

**Comment by mcclanahoochie** [comment]
Hi, the MediaPipe team appreciates the feedback.
This code cleanup request has been noted as internal TODO, but currently put as low priority to address later. 
Thanks,
