### ISSUE TITLE
Mediapipe and autopy version on python 3.8

### ISSUE THREAD

**Issue by Exclaver** [google/mediapipe#5179]
### OS Platform and Distribution

Windows 11

### Programming Language and version

Python Python 3.8.0

### Installed using virtualenv? pip? Conda?(if python)

virtualenv and pip

### Android AAR (if android)

None

### Describe the problem

Hey so im trying to install mediapipe and autopy python packages on my venv and i can't install mediapipe on python 3.8, if not on python 3.8 on which version of python  can i install to run both autopy and mediapie for my project?x

### Complete Logs

```shell
(venv) PS C:\Users\Devansh\Downloads\HANDwave-main\HANDwave-main> pip install mediapipe==0.8.7.1       
ERROR: Could not find a version that satisfies the requirement mediapipe==0.8.7.1 (from versions: none)
ERROR: No matching distribution found for mediapipe==0.8.7.1

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
(venv) PS C:\Users\Devansh\Downloads\HANDwave-main\HANDwave-main>
```

**Comment by ayushgdev** [comment]
Hello @Exclaver 
The version you are trying to install had legacy API which we have deprecated the support for. As part of maintenance, we have removed the release 0.8.7.1. 
We highly encourage switching to the newer Tasks APIs which are a superset of the legacy APIs, easier to install and work with as well. Particularly, guessing from your project name, I think you might want to look at the [Gesture Recognition Task](https://developers.google.com/mediapipe/solutions/vision/gesture_recognizer/python). 
For Python 3.8, latest version of MediaPipe, v0.10.10 is available for Windows platform. Please consider installing the latest version and let us know if you face any issue while on it.
