### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [google/mediapipe#518]
[Extra null pointer checks are not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the function “TensorBuffer::CreateGlBuffer”](https://github.com/google/mediapipe/blob/3b6d3c40589968c8333b4a936fbad7a8bea6d7f6/mediapipe/util/tflite/tensor_buffer.cc#L20 "Update candidate").

**Comment by elfring** [comment]
I would appreciate a bit more information for this issue.

**Comment by mcclanahoochie** [comment]
Thanks for the comment and advice. 
The TensorBuffer class will soon be replaced with an updated version that is completely re-designed, and should no longer have the same issue. 
Cheers,
