### ISSUE TITLE
face_mesh model triggers infrared mode on webcam

### ISSUE THREAD

**Issue by eitelkrauss** [google/mediapipe#5183]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

windows 10

### MediaPipe version

"@mediapipe/face_mesh": "^0.4.1633559619",

### Solution

FaceMesh

### Programming Language and version

Javascript

### Describe the actual behavior

webcam is opened with infrared mode on

### Describe the expected behaviour

normal webcam mode

### Standalone code/steps you may have used to try to get what you need

```shell
```

### Other info / Complete Logs
I'm using FaceMesh on a web application working perfectly fine on linux, mac and other windows laptops, but on a HP laptop running Windows 10 the webcam is opened with infrared mode on.  I tested the facelandmarks demo in https://mediapipe-studio.webapps.google.com/demo/face_landmarker and its the same behaviour so I'm guessing its something to do with the model/solution.
I've tried looking for similar cases or issues but without any success.

**Comment by ayushgdev** [comment]
Hello @eitelkrauss 
Thanks for bringing this to our attention. That is a really interesting observation. However, we do not have an HP device at the moment with us. So investigating this issue can take time. 
Nevertheless, many thanks for reporting the issue. Would it be possible to provide the script/the method you have used to monitor the switching on of infrared mode of webcam?

**Comment by eitelkrauss** [comment]
Hi @ayushgdev,
I'm not sure what you mean by monitoring the infrared mode it just opens up on infrared.  The laptop apparently does this by default when it is nighttime, but it's not happening on other apps other than mine and the demo using the FaceLandmarks solution.  This also means it's not only subject to the legacy version I'm using?

This is basically how I'm initializing the model:

```
import * as faceMesh from '@mediapipe/face_mesh';

let model: faceMesh.FaceMeshInterface;

const load = async () => {
    if (model == undefined) {
        model = new faceMesh.FaceMesh({
            locateFile: (file) => {
                return `${MODEL_URL}/${file}`;
            }
        });
        model.setOptions({
            maxNumFaces: 1,
            refineLandmarks: true,
            selfieMode: true,
            minDetectionConfidence: 0.5,
            minTrackingConfidence: 0.5,
        });
    }

    await model.initialize();
}
```

After requesting the camera with getUserMedia() I'm passing an HTMLVideoElement to the send method and I'm not even using `requestAnimationFrame()` but `setInterval()` at 20fps:

```
 public runModel() {
    if(!!this.state.interval) clearInterval(this.state.interval)
    this.state.interval = setInterval(() => {
      this.faceMesh.send(this._video);
    }, 1000 / 20)
  }
 ```
 
 Hope this helps! let me know if you need anything else or if this isn't what you were asking about.
 I understand it can take some time and no issue with that.  I would still like to find out what the problem is though!
Thanks!

**Comment by ayushgdev** [comment]
Can you please provide a screenshot as well of what you see as the webcam output? We are still unclear with the infrared mode actually.
