### ISSUE TITLE
how to train the model?

### ISSUE THREAD

**Issue by jinfagang** [google/mediapipe#519]
Any published model for now?

**Comment by jiuqiant** [comment]
MediaPipe is mainly focusing on data processing and building ML solutions across platforms. Unfortunately, we are not able to train any models. The training phase is usually done by TensorFlow.

**Comment by jinfagang** [comment]
How's the model in example trained? Will it opensource?

**Comment by oritRabani** [comment]
Hello, 
Is it possible to train MediaPipe-pose on a custom dataset?  I couldn't find any code related to training the model. 
Thanks.
