### ISSUE TITLE
MediaPipe WebApp using WASM

### ISSUE THREAD

**Issue by Jwy-jump** [google/mediapipe#5194]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Ubuntu 18.04

### Task name (e.g. Image classification, Gesture recognition etc.)

ObjectDetection

### Programming Language and version (e.g. C++, Python, Java)

JS

### Describe the actual behavior

The ObjectDetector can not run correctly

### Describe the expected behaviour

The ObjectDetector run correctly

### Standalone code/steps you may have used to try to get what you need

```shell
when I use the following code  in MediaPipe WebApp using WASM

// Initialize the object detector.
async function initializeObjectDetector() {
  const visionFilesetResolver = await FilesetResolver.forVisionTasks(
    "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm"
  );
  objectDetector = await ObjectDetector.createFromOptions(visionFilesetResolver, {
    baseOptions: {
      modelAssetPath: "https://storage.googleapis.com/mediapipe-assets/dogs.tflite"
    },
    scoreThreshold: 0.3,
    runningMode: runningMode
  });
}
initializeObjectDetector();

I encountered the following problems：

hello-world-simple.js:1  Uncaught (in promise) RuntimeError: Aborted(`Module.arguments` has been replaced by `arguments_` (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name))
    at abort (hello-world-simple.js:1:19163)
    at Object.get (hello-world-simple.js:1:23110)
    at vision_wasm_internal.js:137:11
    at i (tasks-vision.js:7860:26)
    at async createTaskRunner (tasks-vision.js:7880:66)
    at async State.createPoseLandmarker (renderer.js:33:26)

The solution I came up with was to compile into wasm myself, and how to use it with existing wasm.

I want to know if this is the right idea and how to combine my custom wasm with the existing wasm.Thanks.
```

### Other info / Complete Logs

```shell
s
```

**Comment by ayushgdev** [comment]
Hello @Jwy-jump 
Would you please provide the complete code example to reproduce the issue? We have tried using the code excerpt provided by you to create an example app. However, it works fine on Image mode. 

We have created a simple app [here](https://github.com/ayushgdev/MediaPipeCodeSamples/tree/main/ObjectDetectionLivestream). If you can please suggest some changes in this app which can recreate the exact same issue that you have reported, it would be great

**Comment by tlebon** [comment]
this is a classic mediapipe issue, you are initiailizing the model more than once and it is failing. a google search will pull up similar errors.
