### ISSUE TITLE
Measure degree hip rotation

### ISSUE THREAD

**Issue by mcdonasd1212** [google/mediapipe#5199]
I am looking for python solution that  calculates the degree of hip turn around the Y-axis.

Any guidance would be appreciated.

Using Mediapipe pose 0.10.9

**Comment by ayushgdev** [comment]
Hello @mcdonasd1212 
Would you please provide elaborate explanation with sample image annotating the _hip turn_ that you would like to be tracked? We would like to understand your requirement better first.

**Comment by mcdonasd1212** [comment]
![IMG_1619](https://github.com/google/mediapipe/assets/86633351/f96413c7-99c6-4612-8496-c71fa06e8dd3)

In the attached image, what is the degree the hips are rotated around the Y axis?  I read somewhere that it would be as simple as this:

hip_left_rotation = results.pose_landmarks.landmark[mp.solutions.pose.PoseLandmark.LEFT_HIP].rotation

However, I get an error:
AttributeError: 'NormalizedLandmark' object has no attribute 'rotation'

I have also tried the following, however the angle measurement returned is not the expected value of approximately 80 degrees.

# Step 1: Define points
P = point1_current
D = point2_current
B = D - P  # Vector representing line B

# Choose any arbitrary non-collinear point
non_collinear = np.array([0.1, 0.1, 0.1])

# Step 2: Difference vector Z
Z = B

# Step 3: Difference vector Q
Q = non_collinear - P

# Step 4: Local X and Y axes based on line B
X = np.cross(Z, Q)
Y = np.cross(Z, X)

# Step 5: Local coordinate system matrix
local_coordinate_system = np.vstack((X, Y, Z)).T

# Step 6: Relative 1-2-3 Euler angles (Bryant angles) for point P and D
r_P = R.from_rotvec(P)
r_D = R.from_rotvec(D)
relative_angles = r_P.inv() * r_D
relative_bryant_angles = relative_angles.as_euler('xyz', degrees=True)

# Step 7: Global Bryant angles
global_angles = relative_bryant_angles

# Step 8: Define relationship of Bryant matrices
G = np.array([[1, 0, 0],
              [0, -1, 0],
              [0, 0, 1]])

# Step 9: Isolate relative Bryant angles matrix
R_PG_inv = np.linalg.inv(G) @ r_P.as_matrix()
R_PD_inv = np.linalg.inv(G) @ r_D.as_matrix()
relative_bryant_angles_matrix = R_PG_inv @ r_D.as_matrix()

# Step 10: Substitute global Bryant angles into RGD and RGP matrices
R_PD = G @ r_P.inv().as_matrix() @ r_D.as_matrix()

# Step 11: Extract relative Bryant angles
extracted_relative_angles = r_P.inv() * r_D
extracted_relative_bryant_angles = extracted_relative_angles.as_euler('xyz', degrees=True)
`

**Comment by mcdonasd1212** [comment]
bumping really need some advice.
