### ISSUE TITLE
Trouble creating example Xcode project (Cannot install Tulsi.app)

### ISSUE THREAD

**Issue by WaterBoiledPizza** [google/mediapipe#5200]
### OS Platform and Distribution

macOS 14.3.1

### Programming Language and version

Python 3.11.8

### MediaPipe version

0.10.10

### Bazel version

7.0.2

### XCode and Tulsi versions (if iOS)

XCode 15.2, Tulsi unable to install

### Android AAR (if android)

None

### Describe the problem

I am following the steps to get Mediapipe on iOS: https://developers.google.com/mediapipe/framework/getting_started/ios#create_an_xcode_project and I ran into an error as below when trying to build and run Tulsi

### Complete Logs

```shell
user@Users-MacBook-Pro tulsi % sh build_and_run.sh        
ERROR: Traceback (most recent call last):
    File "/private/var/tmp/_bazel_user/2305db2c4448daa156f4d79a98064c71/external/build_bazel_rules_apple/apple/internal/rule_support.bzl", line 221, column 36, in <toplevel>
        deps_cfg = apple_common.multi_arch_split,
Error: 'apple_common' value has no field or method 'multi_arch_split'
WARNING: Target pattern parsing failed.
ERROR: Skipping '//:tulsi': error loading package '': at /private/var/tmp/_bazel_user/2305db2c4448daa156f4d79a98064c71/external/build_bazel_rules_apple/apple/macos.bzl:33:5: at /private/var/tmp/_bazel_user/2305db2c4448daa156f4d79a98064c71/external/build_bazel_rules_apple/apple/internal/macos_binary_support.bzl:50:5: initialization of module 'apple/internal/rule_support.bzl' failed
ERROR: error loading package '': at /private/var/tmp/_bazel_user/2305db2c4448daa156f4d79a98064c71/external/build_bazel_rules_apple/apple/macos.bzl:33:5: at /private/var/tmp/_bazel_user/2305db2c4448daa156f4d79a98064c71/external/build_bazel_rules_apple/apple/internal/macos_binary_support.bzl:50:5: initialization of module 'apple/internal/rule_support.bzl' failed
INFO: Elapsed time: 0.092s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```
```

**Comment by kuaashish** [comment]
Hi @WaterBoiledPizza,

We have ceased support for App development via the Tulsi App and no longer in maintenance. Instead, we recommend utilizing the CocoaPods version. Additionally, the solution you are attempting to implement is not explicitly specified in the description. 

For instance, if your objective is Object Detection, you can find the necessary steps for CocoaPods at https://developers.google.com/mediapipe/solutions/vision/object_detector/ios. Similarly you can find for other task API's in this page https://developers.google.com/mediapipe/solutions/guide. Also, Please notify us of any challenges encountered during the implementation process. Regrettably, there is limited action we can take to address the issue you are currently experiencing.

Thank you!!

**Comment by WaterBoiledPizza** [comment]
Thank you for the clarification. Will the `MediaPipe Framework on iOS` page get an update about that soon? Or having an admonition about it being outdated and no longer supported would be great!

**Comment by kuaashish** [comment]
Hi @WaterBoiledPizza,

We will let our team know about this issue, and hopefully, it will be added to our documents soon.

Thank you!!
