### ISSUE TITLE
When object whose position is being detected moves out of the frame then results.multi_hand_landmarks[0] becomes a NULL type object (NOT ACTUALLY SURE THAT IS IT A VALID BUG OR NOT)

### ISSUE THREAD

**Issue by akshat-1** [google/mediapipe#5204]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

WINDOWS 11

### Mobile device if the issue happens on mobile device

NO

### Browser and version if the issue happens on browser

NO

### Programming Language and version

python 3.11.1

### MediaPipe version

0.10.11

### Solution

Instead of making it a NULL type object it may be better to set its value to the last value encountered. Its like setting a limit 

### Describe the actual behavior

File "d:\VIRTUAL PIANO\VIRTUAL-PIANO\mp_hand_gesture\mp_hand_detection.py", 
line 91, in <module>     print(f" {IndexCoordinatesLandmark[0]},{IndexCoordinatesLandmark[1]}  {'/'} {MiddleCoordinatesLandmark[0]},{MiddleCoordinatesLandmark[1]} {'/'} {RingCoordinatesLandmark[0]},{RingCoordinatesLandmark[1]} {'/'} {ThumbCoordinatesLandmark[0]},{ThumbCoordinatesLandmark[1]} ")                                                                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~^^^ TypeError: 'NoneType' object is not subscriptable

### Describe the expected behaviour

It might have returned the last value encountered

### Standalone code/steps you may have used to try to get what you need

```shell
Could have used exception handling for this case.
```

### Other info / Complete Logs

```shell
... 
 if results.multi_hand_landmarks:
            for num, hand in enumerate(results.multi_hand_landmarks):
                mp_drawing.draw_landmarks(image, hand, mp_hands.HAND_CONNECTIONS, 
                                        mp_drawing.DrawingSpec(color=(121, 22, 76), thickness=2, circle_radius=4),
                                        mp_drawing.DrawingSpec(color=(250, 44, 250), thickness=2, circle_radius=2),
                                         )
            
            IndexLandmark = results.multi_hand_landmarks[0].landmark[mp_hands.HandLandmark.INDEX_FINGER_TIP]
            IndexCoordinatesLandmark = mp_drawing._normalized_to_pixel_coordinates(IndexLandmark.x, IndexLandmark.y, frameWidth, frameHeight)

            MiddleLandmark = results.multi_hand_landmarks[0].landmark[mp_hands.HandLandmark.MIDDLE_FINGER_TIP]
            MiddleCoordinatesLandmark = mp_drawing._normalized_to_pixel_coordinates(MiddleLandmark.x, MiddleLandmark.y, frameWidth, frameHeight)

            RingLandmark = results.multi_hand_landmarks[0].landmark[mp_hands.HandLandmark.RING_FINGER_TIP]
            RingCoordinatesLandmark = mp_drawing._normalized_to_pixel_coordinates(RingLandmark.x, RingLandmark.y, frameWidth, frameHeight)

            ThumbLandmark = results.multi_hand_landmarks[0].landmark[mp_hands.HandLandmark.THUMB_TIP]
            ThumbCoordinatesLandmark = mp_drawing._normalized_to_pixel_coordinates(ThumbLandmark.x, ThumbLandmark.y, frameWidth, frameHeight)



            
            print(f" {IndexCoordinatesLandmark[0]},{IndexCoordinatesLandmark[1]}  {'/'} {MiddleCoordinatesLandmark[0]},{MiddleCoordinatesLandmark[1]} {'/'} {RingCoordinatesLandmark[0]},{RingCoordinatesLandmark[1]} {'/'} {ThumbCoordinatesLandmark[0]},{ThumbCoordinatesLandmark[1]} ")
```

**Comment by kuaashish** [comment]
Hi @akshat-1,

Could you please provide the exact standalone code you are following, Or steps you are following from the documentation? This information will help us reproduce and better understand the issue on our end.

Thank you!!
