### ISSUE TITLE
Build "libllm_inference_engine_jni.so" error!

### ISSUE THREAD

**Issue by caofx0418** [google/mediapipe#5211]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Linux Ubuntu 20.04

### Task name (e.g. Image classification, Gesture recognition etc.)

llm

### Programming Language and version (e.g. C++, Python, Java)

C++,Java

### Describe the actual behavior

build error

### Describe the expected behaviour

build success, and generate "libllm_inference_engine_jni.so"

### Standalone code/steps you may have used to try to get what you need

```shell
bazel build -c opt --config=android_arm64 mediapipe/tasks/java/com/google/mediapipe/tasks/genai:libllm_inference_engine_jni.so
```

### Other info / Complete Logs

```shell
ERROR: /root/99_reference/mediapipe/mediapipe-v0.10.11/mediapipe/tasks/java/com/google/mediapipe/tasks/core/jni/BUILD:59:11: no such package
'@odml//odml/infra/genai/inference/c': The repository '@odml' could not be resolved: Repository '@odml' is not defined and referenced by '//mediapipe/tasks/ja
va/com/google/mediapipe/tasks/core/jni:llm'
ERROR: Analysis of target '//mediapipe/tasks/java/com/google/mediapipe/tasks/genai:libllm_inference_engine_jni.so' failed; build aborted:
INFO: Elapsed time: 0.168s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

**Comment by kuaashish** [comment]
Hi @caofx0418,

Could you please outline the exact steps you are following, referencing the documentation? This information will help us reproduce and better understand the issue on our end.

Thank you!!

**Comment by caofx0418** [comment]
> Hi @caofx0418,
> 
> Could you please outline the exact steps you are following, referencing the documentation? This information will help us reproduce and better understand the issue on our end.
> 
> Thank you!!

thank you for your replay!
steps:

1.  git clone code 
git clone https://github.com/google/mediapipe.git -b v0.10.11 mediapipe-v0.10.11
2.  init build env for android
cd mediapipe-v0.10.11 && bash setup_android_sdk_and_ndk.sh

3. build libmediapipe_tasks_vision_image_generator_jni.so, it's Success!
bazel build -c opt --config=android_arm64 mediapipe/tasks/java/com/google/mediapipe/tasks/vision/imagegenerator:libmediapipe_tasks_vision_image_generator_jni.so

4. build libllm_inference_engine_jni.so, but it failed!
bazel build -c opt --config=android_arm64 mediapipe/tasks/java/com/google/mediapipe/tasks/genai:libllm_inference_engine_jni.so

**Comment by caofx0418** [comment]
Error log:
The repository '@odml' could not be resolved: Repository '@odml' is not defined and referenced by '//mediapipe/tasks/ja
va/com/google/mediapipe/tasks/core/jni:llm'

It seems the odml can't download!  Need to apply odml additional login permissions?

**Comment by schmidt-sebastian** [comment]
Sorry, we are still catching up on some of the remaining items for our recent launch. We will make building this library easier, but if you want to proceed right now please build against https://github.com/google/mediapipe/blob/master/mediapipe/tasks/cc/genai/inference/c/BUILD#L20

**Comment by caofx0418** [comment]
> Sorry, we are still catching up on some of the remaining items for our recent launch. We will make building this library easier, but if you want to proceed right now please build against https://github.com/google/mediapipe/blob/master/mediapipe/tasks/cc/genai/inference/c/BUILD#L20

but, In Mediapipe Genmma sample App(https://github.com/googlesamples/mediapipe/blob/main/examples/llm_inference/android), it use "ibllm_inference_engine_jni.so"

**Comment by dengzheng-cloud** [comment]
i have tried to use bazel to build target libllm_inference_engine_cpu.so in task/cc/genai/inference/c/BUILD, while during build task-genai, it seems that i can't get through odml, if there is a way to get over odml deps?

**Comment by dengzheng-cloud** [comment]
> As of [e135531](https://github.com/google/mediapipe/commit/e1355313768224e872cea8a4e52661daa4e8e945) you should now be able to build `libllm_inference_engine_jni.so` as expected using:
> 
> ```
> bazel build -c opt --config=android_arm64 mediapipe/tasks/java/com/google/mediapipe/tasks/genai:libllm_inference_engine_jni.so
> ```

![image](https://github.com/google/mediapipe/assets/32841220/6f32f1ff-48a4-4b21-8710-96ab86d22039)
i got no such package odml too. really curious about how to get that odml

**Comment by dengzheng-cloud** [comment]
> As of [e135531](https://github.com/google/mediapipe/commit/e1355313768224e872cea8a4e52661daa4e8e945) you should now be able to build `libllm_inference_engine_jni.so` as expected using:
> 
> ```
> bazel build -c opt --config=android_arm64 mediapipe/tasks/java/com/google/mediapipe/tasks/genai:libllm_inference_engine_jni.so
> ```

miss the pr you mentioned, that works after pull, thank you very much!
