### ISSUE TITLE
How can I Integrate NPU into

### ISSUE THREAD

**Issue by aphlta** [google/mediapipe#5215]
HI,
  We test the hand_landmask on our platform named VS680 , but it is slow than we expected.  As we have a NPU on our chip, I try to run the model on NPU, but I don't know how to Integrate it. Is there any advices?

**Comment by kuaashish** [comment]
Hi @aphlta,

Regrettably, our API layer is currently limited to supporting only CPU and GPU functionalities.

Thank you!!

**Comment by nskaiser** [comment]
I am also looking for NPU support. Is this in the roadmap?

**Comment by kuaashish** [comment]
Hi @nskaiser,

At present, we do not have a roadmap for this feature. Depending on demand, we may consider its implementation in the future. However, for now, we kindly ask you to submit a new feature request outlining the potential benefits for the community. Once received, we will share the request with our team for further consideration.

Thank you!!

**Comment by pzoltowski** [comment]
I'm also wondering if its possible to use CoreML (apple NPU) for delegate. Tensorflow Lite support it and when benchmarking mediapipe models they execute significantly faster on neural engine, e.g some inference runs on iPhone 13 mini:

Pose Landmark models
=original (mediapipe tflite)
- pose_landmarks_detector lite (mediapipe):            mean: NN: 4.70ms, GPU: 10.9ms, CPU: 10.00ms
- pose_landmarks_detector full (mediapipe):            mean: NN: 5.60ms, GPU: 14.7ms, CPU: 14.40ms
- pose_landmarks_detector heavy (mediapipe):        mean: NN: 8.54ms, GPU: 33.4ms, CPU: 51.00ms
