### ISSUE TITLE
Replacing the z coordinate from pos_landmark with depth value

### ISSUE THREAD

**Issue by Shefalidew** [google/mediapipe#5217]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Solution

Holistic

### Programming Language and version

Python

### Describe the actual behavior

While using landmark.x from pose_landmark (which should be normalized between [0,1]) the value of landmark.x exceeds 1.0. This is causing me an issue while trying to get the (x,y) coordinates in the image to replace the landmark.z coordinate with the depth value obtained from a camera. 

### Describe the expected behaviour

Value of pose_landmarks between [0,1]

### Standalone code/steps you may have used to try to get what you need

```shell
For the code, I am using a sequence of RGB images captured and stored using an RGBD camera.

The code to perform that is as follows:
with mp_holistic.Holistic(min_detection_confidence = 0.5, min_tracking_confidence=0.8) as holistic:
        image_data = []
        k=0
        for i in range(len(RGB_X_train)):
            data = []
            print('i:',i)
            color_image = RGB_X_train[i]
            depth_image = depth_X_train[i]
            print(depth_image.shape)
            for j in range(len(color_image)):
                print(j)
                color_frame = color_image[j]
                depth_frame = depth_image[j]
                print(depth_frame.shape)
                image , results = mediapipe_detection(color_frame,holistic)
                Row = []
                # Convert the BGR image to RGB before processing.
                results = holistic.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
                if results.pose_landmarks != None:
                    selected_pose_landmarks = results.pose_landmarks.landmark[11:25]
                    for landmark in selected_pose_landmarks:
                        x_landmark = landmark.x*color_frame.shape[0] 
                        print(f'landmark.x:{landmark.x}')
                        print(x_landmark)
                        y_landmark = landmark.y*color_frame.shape[1] 
                        print(f'landmark.y:{landmark.y}')
                        print(y_landmark)
                        z_landmark = depth_frame[int(x_landmark), int(y_landmark)]*0.001
                        Row.append([landmark.x, landmark.y, z_landmark])
```

### Other info / Complete Logs

```shell
Row_shape: (14, 3)
20
(96, 96)
landmark.x:0.9152279496192932
87.86188316345215
landmark.y:0.40306973457336426
38.69469451904297
landmark.x:0.8090413212776184
77.66796684265137
landmark.y:0.41806355118751526
40.134100914001465
landmark.x:0.9542112946510315
91.60428428649902
landmark.y:0.48584794998168945
46.64140319824219
landmark.x:0.7976877093315125
76.5780200958252
landmark.y:0.47388696670532227
45.49314880371094
landmark.x:0.9863837361335754
94.69283866882324
landmark.y:0.5055044293403625
48.528425216674805
landmark.x:0.8167142868041992
78.40457153320312
landmark.y:0.372141569852829
35.72559070587158
landmark.x:1.0111308097839355
97.06855773925781
landmark.y:0.5321174263954163
51.08327293395996
```

**Comment by matanox** [comment]
Are you talking about fractional values above 1.0, or much larger values? couldn't make much from the printout in a quick glance

**Comment by kuaashish** [comment]
Hi @matanox,

Could you please provide the exact standalone code you are using, Or steps you are following from the documentation? This information will help us reproduce and better understand the issue on our end.

Thank you!!

**Comment by Shefalidew** [comment]
> Are you talking about fractional values above 1.0 or much larger values? couldn't make much from the printout in a quick glance

Since the code was throwing a ValueError at the first instance the value of landmark.x or landmark.y is out of range [0,1], I can say that there are only fractional values above 1.0. However, as I want to access the (x,y) coordinates of the landmark points on the image, even a small increment in value gives me a coordinate value higher than the size of the image   (i.e. 97.06) in this case. 
Currently, I am checking if it exceeds the value much larger than some fractions and I'll let you know.

**Comment by Shefalidew** [comment]
> > Are you talking about fractional values above 1.0 or much larger values? couldn't make much from the printout in a quick glance
> 
> Since the code was throwing a ValueError at the first instance the value of landmark.x or landmark.y is out of range [0,1], I can say that there are only fractional values above 1.0. However, as I want to access the (x,y) coordinates of the landmark points on the image, even a small increment in value gives me a coordinate value higher than the size of the image (i.e. 97.06) in this case. Currently, I am checking if it exceeds the value much larger than some fractions and I'll let you know.

For pose_landmarks the values are exceeding mostly for landmarks.x (but observed the value of landmark.y also exceeding while using pose_world_landmarks). I have given some examples from the pose_landmarks exceeding the value below.

Row_shape: (14, 3)
27
(96, 96)
Exceeding range 91:  1.0301517248153687 0.39825698733329773
Exceeding range 92:  1.0713731050491333 0.4135601222515106
Exceeding range 93:  1.0730830430984497 0.40542563796043396
Exceeding range 94:  1.056106448173523 0.4053201675415039
Row_shape: (14, 3)
28
(96, 96)
Exceeding range 95:  1.0301538705825806 0.39849233627319336
Exceeding range 96:  1.071136236190796 0.41518959403038025
Exceeding range 97:  1.0725706815719604 0.4058196246623993
Exceeding range 98:  1.0558120012283325 0.4058046042919159

**Comment by matanox** [comment]
Just clip the values.

**Comment by kuaashish** [comment]
Hi @Shefalidew,

Could you please confirm whether you are still seeking a resolution to this issue, or if the matter has been resolved from your end?

Thank you!!

**Comment by Shefalidew** [comment]
> Hi @Shefalidew,
> 
> Could you please confirm whether you are still seeking a resolution to this issue, or if the matter has been resolved from your end?
> 
> Thank you!!

Yes, I was able to resolve the issue by clipping the values to exact 0 and 1. 
Thank you!
