### ISSUE TITLE
Cannot find clear documentation on mp.Image, is the expected input BGR or RGB?

### ISSUE THREAD

**Issue by MatoFD** [google/mediapipe#5218]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Ubuntu 22.04.4 LTS

### MediaPipe Tasks SDK version

mediapipe 0.10.8

### Task name (e.g. Image classification, Gesture recognition etc.)

ImageSegmenter

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

Segmenter works but it's not clear if it could work better and I have no good way of measuring the segmentation accuracy

### Describe the expected behaviour

Using mp.Image as designed to its full cappacity

### Standalone code/steps you may have used to try to get what you need

```shell
bgr_img = cv2.imread(img_filepath)
mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=bgr_img)
rgb_img = cv2.cvtColor(bgr_img, cv2.COLOR_BGR2RGB)
mp_image_2 = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb_img)

options = mp.tasks.vision.ImageSegmenterOptions(
          base_options=mp.tasks.BaseOptions(model_asset_path=model_path),
          output_category_mask=True,
          running_mode=mp.tasks.vision.RunningMode.IMAGE, )
with mp.tasks.vision.ImageSegmenter.create_from_options(options) as segmenter:
          # should I use mp_image or mp_image_2 here? rgb_image raises the error from other info
          segmentation_result = segmenter.segment(rgb_image)
```

### Other info / Complete Logs

```shell
The docs for ImageSegmenter (https://developers.google.com/mediapipe/api/solutions/python/mp/tasks/vision/ImageSegmenter) just says it takes as input an RGB image, but if I try to use the cv2 rgb image it throws the following error: 
"""
File "/home/matias/.virtualenvs/mediaPipe/lib/python3.10/site-packages/mediapipe/tasks/python/vision/image_segmenter.py", line 303, in segment
    _IMAGE_IN_STREAM_NAME: packet_creator.create_image(image),
  File "/home/matias/.virtualenvs/mediaPipe/lib/python3.10/site-packages/mediapipe/python/packet_creator.py", line 229, in create_image
    raise ValueError('Please provide \'image_format\' with \'data\'.')
ValueError: Please provide 'image_format' with 'data'.
"""

Then I found that the tasks in mediapipe expect as input a mp.Image, but I cannot find if the input to create the image should be in BGR or RGB. The docs for mp.Image (https://developers.google.com/mediapipe/api/solutions/python/mp/Image) use the image as taken from cv2.imread, which is in BGR format (https://docs.opencv.org/3.4/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56). But this seemed confusing to me based on some colleagues previous uses, and an older issue that helped some people (https://github.com/google/mediapipe/issues/4266#issuecomment-1534153174) first formats the image from BGR to RGBA.

So I would appreciate some clarification in how to correctly use mp.Image as input for mediapipe.Tasks, thank you.
```

**Comment by kuaashish** [comment]
Hi @MatoFD,

You can use both `mp_image` and `mp_image2`. When providing the `rgb_image` to `segmentation_result = segmenter.segment(rgb_image)`, make sure you pass either `mp_image` or `mp_image2`. OpenCV images must be converted to a MediaPipe image first for compatibility since they are not directly supported. As for accuracy-related queries, we currently don't have metrics available for measuring segmentation accuracy.

Among the `mp_image` and `mp_image_2`, you can use both but generally we would recommend to feed RGB image to `mp.Image()` since it has a better segmentation among similar color gradients, however we don't have concrete data to back this up.

Thank you!!

**Comment by MatoFD** [comment]
Thanks! It's good to have a recommended solution and it's working well for now

**Comment by kuaashish** [comment]
Hi @MatoFD,

Thank you for confirming, Can we now proceed to mark this matter as resolved and close the status?
