### ISSUE TITLE
mediapipe hands not working over grayscale images even though I am stacking it to make it 3 channel. 

### ISSUE THREAD

**Issue by Suvi-dha** [google/mediapipe#5226]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Linux Ubuntu

### MediaPipe Tasks SDK version

mp.solutions.hands

### Task name (e.g. Image classification, Gesture recognition etc.)

Hand Detection

### Programming Language and version (e.g. C++, Python, Java)

Python 

### Describe the actual behavior

When trying to detect the keypoints on a gray scale hand image, empty lists are obtained

### Describe the expected behaviour

After stacking grayscale image 3 times, the modle should be able to detect the keypoints on hands

### Standalone code/steps you may have used to try to get what you need

```shell
import cv2
import mediapipe as mp
import numpy as np
import glob
import pdb, os

mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

with mp_hands.Hands( static_image_mode=True, max_num_hands=2, min_detection_confidence=0.5) as hands:
    for idx, file in enumerate(IMAGE_FILES):
        cv_img = cv2.imread(file)[:, :, ::-1].copy()
        cv_img = cv2.cvtColor(cv_img, cv2.COLOR_RGB2GRAY)
        image = cv2.cvtColor(cv_img, cv2.COLOR_GRAY2RGB)
        results = hands.process(image)
        if not results.multi_hand_landmarks:
            continue
```

### Other info / Complete Logs

```shell
Some example images on which it is not working can be accessed from: 
 https://drive.google.com/drive/folders/1laLDeojTNKRaHvTrjSn34eAAIWhmt4X_?usp=sharing
```

**Comment by kuaashish** [comment]
Hi @Suvi-dha,

Based on the code snippet you've shared, it seems you're utilizing an older version of MediaPipe. We've recently introduced improved MediaPipe Tasks APIs that offer greater stability and functionality compared to the older version. 

We highly recommend transitioning to these updated APIs for Hand landmarks, as we've ceased support for legacy solutions. You can access the documentation for the Hand Landmarker [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker). 

However, it's worth noting that the newer version does support Grayscale images. You can refer to the example [gist](https://colab.sandbox.google.com/gist/kuaashish/d1cac26dbe43d2d924ea1896a61c1395/grey.ipynb) demonstrating detection on a grayscale image.

Thank you!!

**Comment by Suvi-dha** [comment]
Hi, Thanks for the input. As asked, I tried and tested the example notebook on my samples and I am still getting empty lists like this. HandLandmarkerResult(handedness=[], hand_landmarks=[], hand_world_landmarks=[])

**Comment by kuaashish** [comment]
Hi @kinarr,

Could you please have look into this issue? 

Thank you!

**Comment by kinarr** [comment]
I'll take a look.

**Comment by kinarr** [comment]
Hi, @Suvi-dha 
Here's the notebook for exploring the results for those samples. It appears there's a challenge with the model generating hand landmarks in images that are too zoomed in, making it difficult to identify details. You might consider using images where the hand is more visible and less zoomed in.

https://colab.research.google.com/drive/1Ejd67MUnHsdIsgH56YgX1uSd_9incPWU

**Comment by Suvi-dha** [comment]
Thank you for your response, appreciate your help. Looks like mediapipe needs more generalization.

**Comment by kinarr** [comment]
> Thank you for your response, appreciate your help. Looks like mediapipe needs more generalization.

@Suvi-dha If the team releases a MediaPipe Model Maker guide for Hand Landmarker, you can fine-tune the model with your own images, similar to the Gesture Recognizer's Model Maker guide.

https://developers.google.com/mediapipe/solutions/customization/gesture_recognizer 

At the moment there's no Hand Landmarker Customization guide.

**Comment by kinarr** [comment]
You can drop your images into MediaPipe Studio and adjust the relevant parameters to obtain reliable results, which helps determine if the model is suitable for your specific conditions. Additionally, you can insert a custom fine-tuned Hand Landmarker model, but currently, MediaPipe Model Maker does not support the HandLandmarker API.

https://mediapipe-studio.webapps.google.com/studio/demo/hand_landmarker
