### ISSUE TITLE
I can't install mediapipe

### ISSUE THREAD

**Issue by Naman18-ai** [google/mediapipe#5234]
### OS Platform and Distribution

Windows 11

### Programming Language and version

Python 3.12.2

### Installed using virtualenv? pip? Conda?(if python)

No

### MediaPipe version

 0.10.11

### Android AAR (if android)

None

### Describe the problem

I cannot install mediapipe 

### Complete Logs

```shell
~pip install mediapipe
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

**Comment by kbidlack** [comment]
@Naman18-ai Python 3.12 is not supported; 3.11 is the latest version that you can use

**Comment by diogommartins** [comment]
> @Naman18-ai Python 3.12 is not supported; 3.11 is the latest version that you can use

Any idea of why there's no support for 3.12 ?

**Comment by Naman18-ai** [comment]
> > @Naman18-ai Python 3.12 is not supported; 3.11 is the latest version that you can use
> 
> Any idea of why there's no support for 3.12 ?

Well idk, I tried it to install on ubuntu an it worked fine

**Comment by kuaashish** [comment]
Hi @Naman18-ai,

Could you kindly verify your Ubuntu Python version and inform us? As mentioned by @kbidlack, Python 3.12 is currently not supported. The supported versions range from 3.8 to 3.11.

Thank you!!

**Comment by Naman18-ai** [comment]
@kuaashish  Ubuntu 22.04.3

**Comment by kuaashish** [comment]
Hi @Naman18-ai,

Installation must work with Python 3.11. If you require support for Python 3.12, please submit a [feature request](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Afeature&projects=&template=14-feature-request-issue-template.yaml). We will then escalate the issue to our team for discussion and potential implementation. If this is now no longer issue, may we mark it as resolved and close the case?

Thank you!!

**Comment by Naman18-ai** [comment]
@kuaashish yes you may mark it as closed
