### ISSUE TITLE
Issues compiling mediapipe project to exe with pyinstaller on windows

### ISSUE THREAD

**Issue by Noob-PeNguiN** [google/mediapipe#5238]
I've written a pyqt6 project on windows, which used mediapipe. I compilied my project to an exe using pyinstaller successfully, yet when i  try to run the exe file, the error occurs:

```
Traceback (most recent call last):
  File "main.py", line 628, in <module>
  File "main.py", line 154, in __init__
  File "argus.py", line 37, in __init__
    self.pose = self.mp_pose.Pose(static_image_mode=static_image_mode,
  File "mediapipe\python\solutions\pose.py", line 146, in __init__
  File "mediapipe\python\solution_base.py", line 264, in __init__
FileNotFoundError: The path does not exist.
```
I've tried the complie it in "one file" and "one directory", yet neighter of them worked.
This is the command I use to complie the file:

pyinstaller --noconfirm --onefile --windowed --icon "E:/pycharm_projects/Argus_GraduationProject/logopeople.ico" --add-data "E:/pycharm_projects/Argus_GraduationProject/argus.py;." --add-data "E:/pycharm_projects/Argus_GraduationProject/logo_people.png;." --add-data "E:/pycharm_projects/Argus_GraduationProject/model.p;." --add-data "E:/pycharm_projects/Argus_GraduationProject/window_ui.py;." --hidden-import "openpyxl.cell._writer" --exclude-module "PyQt5"  "E:/pycharm_projects/Argus_GraduationProject/main.py"

**Comment by kuaashish** [comment]
Hi @Noob-PeNguiN,

Could you please provide additional information about the problem. Include the following details:

- Outline the steps you are following to implement based on the documentation Or share us the standalone code. 
- 
- Specify the MediaPipe, Windows, Python Version

Providing this information will help us better understand and address the issue.

Thank you!!

**Comment by Noob-PeNguiN** [comment]
Grettings.
Strangely, the problem is solved when i use another computer to complie the code, it ran smoothly. 
Anyway, the enviorment that didn't work is as followed:
Mediapipe version:  0.9.0.1
Windows version: 22H2  19045.4170
python version: 3.9.18

**Comment by kuaashish** [comment]
Hi @Noob-PeNguiN,

Thank you for confirming. With this matter addressed, we can now consider it resolved and close the status, as the issue no longer persists from your end.
