### ISSUE TITLE
can I debug on the android example?

### ISSUE THREAD

**Issue by cjf445144540** [google/mediapipe#524]
I can build and run the android example, and it works well. Now I want to learn more about how the project work. It will be very convenient if I can debug with the source code on your android or ios examples. But I cant find some android files such as build.gradle or something like that.
Can I debug on Android Studio or Xcode with your examples? If can, how?

**Comment by eknight7** [comment]
To use MediaPipe with Gradle, please see: https://mediapipe.readthedocs.io/en/latest/install.html#using-mediapipe-with-gradle.

To use MediaPipe with Android Studio, please see: https://mediapipe.readthedocs.io/en/latest/install.html#using-mediapipe-with-bazel

**Comment by cjf445144540** [comment]
> To use MediaPipe with Gradle, please see: https://mediapipe.readthedocs.io/en/latest/install.html#using-mediapipe-with-gradle.
> 
> To use MediaPipe with Android Studio, please see: https://mediapipe.readthedocs.io/en/latest/install.html#using-mediapipe-with-bazel

**Comment by cjf445144540** [comment]
many thanks! :)
