### ISSUE TITLE
Inquiry about dataset usage permission

### ISSUE THREAD

**Issue by sunniehan** [google/mediapipe#5242]
1. I would like to inquire if there would be any issues related to dataset usage permission or copyright if I incorporate palm detection and hand landmark solutions (or others) into a product or app for commercial purposes.
Please let me know if there are any issues regarding dataset rights when using the pre-trained MediaPipe Solution in a commercial product.

2. Is it possible to use the MediaPipe Framework code in a commercial product as long as we comply with the Apache-2.0 license?

**Comment by kuaashish** [comment]
Hi @sunniehan,

MediaPipe models are available for commercial use under the Apache License 2.0, as outlined in the [mediapipe/LICENSE](https://github.com/google/mediapipe/blob/master/LICENSE). For your convenience, additional insights are provided in the attached screenshot below.

<img width="1403" alt="imagelica" src="https://github.com/google/mediapipe/assets/98159216/f87b8a71-7819-40de-9c69-fa55e25fc511">


However, we highly advise thoroughly reviewing the [mediapipe/LICENSE](https://github.com/google/mediapipe/blob/master/LICENSE) before integrating them into your specific use case.

Thank you!

**Comment by sunniehan** [comment]
Hi @kuaashish 

Should we verify not only the MediaPipe source code but also the databases used in the MediaPipe Solution under the Apache-2.0 license? or Is it possible to disclose the dataset for Palm Detection and Hand Landmark to check data license or copyright?

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

Do you have any pointers on this issue?

Thank you!!

**Comment by schmidt-sebastian** [comment]
Please also refer to the model cards that are linked on https://developers.google.com/mediapipe/solutions/vision/hand_landmarker

Outside of what we published, we cannot comment on any usage restrictions.
