### ISSUE TITLE
Codepen example for the new javascript holistic Solution?

### ISSUE THREAD

**Issue by galharth** [google/mediapipe#5256]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Mobile web

### Task name (e.g. Image classification, Gesture recognition etc.)

new holistic task

### Programming Language and version (e.g. C++, Python, Java)

Javascript

### Describe the actual behavior

Code example for the new javascript holistic Solution

### Describe the expected behaviour

No Codepen example for the new javascript holistic Solution

### Standalone code/steps you may have used to try to get what you need

```shell
Codepen example for the new javascript holistic Solution
```

**Comment by kuaashish** [comment]
Hi @galharth,

We expect to release samples soon, starting with Android, followed by others. Documentation will be available afterwards. Though we can not give an exact date, it is in progress and will be out soon.

Thank you!!

**Comment by stormsc1** [comment]
Bump
