### ISSUE TITLE
MediaPipe > 0.10.9 does not work on MacOS.

### ISSUE THREAD

**Issue by JC3** [google/mediapipe#5264]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

MacOS

### Programming Language and version

Python

### MediaPipe version

0.10.11

### Solution

Pose Landmarker

### Describe the actual behavior

0.10.10 and 0.10.11 do not work on MacOS because of https://github.com/google/mediapipe/issues/5188.

### Describe the expected behaviour

Error fixed so that 0.10.12 starts working on MacOS again.

### Standalone code/steps you may have used to try to get what you need

```shell
PoseLandmarker.create_from_options(...)
```

**Comment by SjDuque** [comment]
I am having the same issue with Hand Landmarks on a Mac M3 Max.

**Comment by kuaashish** [comment]
Hi @JC3,

We are aware of this matter and closing this issue. Please proceed to follow up with issue #5188, as we are actively monitoring that one.

Thank you!!
