### ISSUE TITLE
GPU pose landmarker crashes on macos after a few minutes

### ISSUE THREAD

**Issue by JC3** [google/mediapipe#5267]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

macos

### Programming Language and version

python

### Solution

pose landmarker

### Describe the actual behavior

After running for ~5-10 minutes, MediaPipe crashes with a SIGABRT. Crash is consistent, happens on every run.

### Describe the expected behaviour

No crash, or at least something recoverable (i.e. a Python exception instead of a SIGABRT).

### Standalone code/steps you may have used to try to get what you need

```shell
# using pose landmarker detect_async on a live stream obtained from opencv
```

### Other info / Complete Logs

```shell
F0000 00:00:1711479797.025863       2 gpu_buffer_storage_cv_pixel_buffer.cc:154] Check failed: status_or_buffer is OK (INTERNAL: ; RET_CHECK failure (mediapipe/objc/util.cc:280) err == kCVReturnSuccessError creating pixel buffer: -6662) 
*** Check failure stack trace: ***
    @        0x14df3c608  absl::lts_20230125::log_internal::LogMessage::SendToLog()
    @        0x14df3bfa0  absl::lts_20230125::log_internal::LogMessage::Flush()
    @        0x14df3ca30  absl::lts_20230125::log_internal::LogMessageFatal::~LogMessageFatal()
    @        0x14df3ca58  absl::lts_20230125::log_internal::LogMessageFatal::~LogMessageFatal()
    @        0x14d9961c4  mediapipe::ConvertFromImageFrame()
    @        0x14d996a30  std::__1::__invoke_void_return_wrapper<>::__call<>()
    @        0x14d995144  std::__1::invoke<>()
    @        0x14d993ef8  mediapipe::GpuBuffer::StorageHolder::GetStorageForView()
    @        0x14d994960  mediapipe::GpuBuffer::GetStorageForViewOrDie()
    @        0x14d918754  mediapipe::Image::ConvertToGpu()
    @        0x14d611548  std::__1::__function::__func<>::operator()()
    @        0x14d99a860  mediapipe::GlContext::SwitchContextAndRun()
    @        0x14d99a028  mediapipe::GlContext::Run()
    @        0x14d61b810  mediapipe::GlCalculatorHelper::RunInGlContext()
    @        0x14d61b9dc  mediapipe::GlCalculatorHelper::RunInGlContext()
    @        0x14d611254  mediapipe::GlCalculatorHelper::RunInGlContext<>()
    @        0x14d61087c  mediapipe::api2::ImageCloneCalculator::Process()
    @        0x14d9ab5d0  mediapipe::CalculatorNode::ProcessNode()
    @        0x14d98a1b8  mediapipe::internal::SchedulerQueue::RunCalculatorNode()
    @        0x14d989c8c  mediapipe::internal::SchedulerQueue::RunNextTask()
    @        0x14d9a3928  mediapipe::ThreadPool::RunWorker()
    @        0x14d9a3334  mediapipe::ThreadPool::WorkerThread::ThreadBody()
    @        0x1a0aabfa8  _pthread_start
    @        0x1a0aa6da0  thread_start
INFO:mpcamera:Received signal 6.
```

**Comment by JC3** [comment]
Note CPU does not have this issue, I ran a CPU mode application for approximately 12 hours recently with no problems.

**Comment by kuaashish** [comment]
Hi @JC3,

Could you kindly provide the detailed steps you are following from our documentation, or alternatively, share the standalone code with us? This will help us to reproduce the issue and gain a better understanding of it.

Thank you!!

**Comment by kuaashish** [comment]
Hi @JC3, 

Can you please try this code with GPU and let us know if you are still experiencing the same crash.


```
import mediapipe as mp
import cv2

from mediapipe import solutions
from mediapipe.framework.formats import landmark_pb2
import numpy as np


BaseOptions = mp.tasks.BaseOptions
PoseLandmarker = mp.tasks.vision.PoseLandmarker
PoseLandmarkerOptions = mp.tasks.vision.PoseLandmarkerOptions
PoseLandmarkerResult = mp.tasks.vision.PoseLandmarkerResult
VisionRunningMode = mp.tasks.vision.RunningMode


#@markdown To better demonstrate the Pose Landmarker API, we have created a set of visualization tools that will be used in this colab. These will draw the landmarks on a detect person, as well as the expected connections between those markers.
from mediapipe import solutions
from mediapipe.framework.formats import landmark_pb2
import numpy as np

class Mediapipe_BodyModule():
    def __init__(self):
        self.mp_drawing = solutions.drawing_utils
        self.mp_pose = solutions.pose
        self.results = None

    def draw_landmarks_on_image(self, rgb_image, detection_result):
        pose_landmarks_list = detection_result.pose_landmarks
        #pose_landmarks_list = detection_result
        annotated_image = np.copy(rgb_image)

        # Loop through the detected poses to visualize.
        for idx in range(len(pose_landmarks_list)):
            pose_landmarks = pose_landmarks_list[idx]

            # Draw the pose landmarks.
            pose_landmarks_proto = landmark_pb2.NormalizedLandmarkList()
            pose_landmarks_proto.landmark.extend([
            landmark_pb2.NormalizedLandmark(x=landmark.x, y=landmark.y, z=landmark.z) for landmark in pose_landmarks
            ])
            solutions.drawing_utils.draw_landmarks(
            annotated_image,
            pose_landmarks_proto,
            solutions.pose.POSE_CONNECTIONS,
            solutions.drawing_styles.get_default_pose_landmarks_style())
        return annotated_image

    # Create a pose landmarker instance with the live stream mode:
    def print_result(self,result: PoseLandmarkerResult, output_image: mp.Image, timestamp_ms: int):
        #print('pose landmarker result: {}'.format(result))
        self.results = result
        #print(type(result))
        
    
    
    def main(self):
        options = PoseLandmarkerOptions(
            base_options=BaseOptions(model_asset_path='pose_landmarker_lite.task'),
            running_mode=VisionRunningMode.LIVE_STREAM,
            result_callback=self.print_result)

        video = cv2.VideoCapture(0)

        timestamp = 0
        with PoseLandmarker.create_from_options(options) as landmarker:
        # The landmarker is initialized. Use it here.
        # ...
            while video.isOpened(): 
                # Capture frame-by-frame
                ret, frame = video.read()

                if not ret:
                    print("Ignoring empty frame")
                    break

                timestamp += 1
                mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=frame)
                landmarker.detect_async(mp_image, timestamp)
                
                #print(type(self.results))
                
                if(not (self.results is None)):
                    annotated_image = self.draw_landmarks_on_image(mp_image.numpy_view(), self.results)
                    #cv2.imshow('Show',cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))
                    cv2.imshow('Show',annotated_image)
                    print("showing detected image")
                else:
                    cv2.imshow('Show', frame)
                
                if cv2.waitKey(5) & 0xFF == ord('q'):
                    print("Closing Camera Stream")
                    break

            video.release()
            cv2.destroyAllWindows()
            
if __name__ == "__main__":
    body_module = Mediapipe_BodyModule()
    body_module.main() ```
```

Thank you!!

**Comment by arushirai1** [comment]
I get this same issue except on detect_for_video on M2 chip.

` 
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1738469961.798907  151920 gl_context.cc:369] GL version: 2.1 (2.1 Metal - 89.3), renderer: Apple M2
INFO: Created TensorFlow Lite delegate for Metal.
F0000 00:00:1738469965.026552  151979 gpu_buffer_storage_cv_pixel_buffer.cc:154] Check failed: status_or_buffer is OK (UNKNOWN: ; unsupported ImageFrame format: 1) 
*** Check failure stack trace: ***
@        0x174f861e8  absl::log_internal::LogMessage::SendToLog()
    @        0x174f85c54  absl::log_internal::LogMessage::Flush()
    @        0x174f86508  absl::log_internal::LogMessageFatal::~LogMessageFatal()
    @        0x174f86520  absl::log_internal::LogMessageFatal::~LogMessageFatal()
    @        0x17494b174  mediapipe::ConvertFromImageFrame()
    @        0x17494b99c  std::__1::__invoke_void_return_wrapper<>::__call[abi:ue170006]<>()
    @        0x1749493e8  std::__1::invoke[abi:ue170006]<>()
    @        0x1749482c0  mediapipe::GpuBuffer::StorageHolder::GetStorageForView()
    @        0x174948e14  mediapipe::GpuBuffer::GetStorageForViewOrDie()
    @        0x1748d712c  mediapipe::Image::ConvertToGpu()
    @        0x1743b3674  std::__1::__function::__func<>::operator()()
    @        0x17494f410  mediapipe::GlContext::SwitchContextAndRun()
    @        0x17494ee70  mediapipe::GlContext::Run()
    @        0x1743bb884  mediapipe::GlCalculatorHelper::RunInGlContext()
    @        0x1743bba78  mediapipe::GlCalculatorHelper::RunInGlContext()
    @        0x1743b2c70  mediapipe::api2::ImageCloneCalculator::Process()
    @        0x17495ec78  mediapipe::CalculatorNode::ProcessNode()
    @        0x17493e3e8  mediapipe::internal::SchedulerQueue::RunCalculatorNode()
    @        0x17493ddf0  mediapipe::internal::SchedulerQueue::RunNextTask()
    @        0x174957d88  mediapipe::ThreadPool::RunWorker()
    @        0x174957934  mediapipe::ThreadPool::WorkerThread::ThreadBody()
    @        0x1850772e4  _pthread_start
    @        0x1850720fc  thread_start`

when I do the following:
`
def extract_keypointsv6_asimg(video_path):
    cap = cv2.VideoCapture(video_path)
    keypoints = []
    fps = int(cap.get(cv2.CAP_PROP_FPS))
    while cap.isOpened():
        
        ret, frame = cap.read()
        if not ret:
            break
        # Convert the BGR image to RGB
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        img=mp.Image(image_format=mp.ImageFormat.SRGB, data=frame_rgb)
        result = detector.detect_for_video(img, int(cap.get(cv2.CAP_PROP_POS_MSEC))).pose_landmarks 
        if result:
            frame_keypoints = [(lm.x, lm.y, lm.z) for lm in result[0]]
            keypoints.append(frame_keypoints)

    return np.array(keypoints), fps
`
