### ISSUE TITLE
Add support for latest protobuf

### ISSUE THREAD

**Issue by TaiTair** [google/mediapipe#5271]
### MediaPipe Solution (you are using)

0.10.11

### Are you willing to contribute it

No

### Describe the feature and the current behaviour/state

Trying to use mediapipe with protobuf 5.26.1 and it doesn't work

### Will this change the current API? How?

Maybe. I'm not familiar with the api.

### Who will benefit with this feature?

People who use SDXL

### Please specify the use cases for this feature

Using mediapipe to detect and fix hands with SDXL

**Comment by schmidt-sebastian** [comment]
Thanks, we are getting more and more requests on this. Will hopefully have time to address this soon.
