### ISSUE TITLE
Pose Landmarks model not working as expected on iOS

### ISSUE THREAD

**Issue by VasilP202** [google/mediapipe#5273]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

iOS 17.3

### Mobile device if the issue happens on mobile device

iPhone 14 

### Programming Language and version

React Native 0.73.6

### MediaPipe version

Latest

### Solution

Pose Landmark Detection

### Xcode & Tulsi version (if issue is related to building for iOS)

15.3

### Describe the actual behavior

Incorrect detection

### Describe the expected behaviour

Correct detection of poses in real time

### Standalone code/steps you may have used to try to get what you need

```shell
Since there's no direct guide for the iOS platform here developers.google.com/mediapipe/solutions/vision/pose_landmarker, I extracted pose_detector.tflite and pose_landmarks_detector.tflite models from pose_landmarker_full.task. Then, I used the vision-camera-fast-tflite library to run pose_landmarks_detector.tflite.

I managed to get some data. It looks like the model can detect some changes in movement, but the output landmarks are mostly totally incorrect. I would like to know if there is any general guide for pose landmark detection on iOS and if is it even possible. 

I went through guides for multiple platforms and also tried to examine the MediaPipe framework written in Python to see if some preprocessing or postprocessing is going on. However, I still don't have any reasonable explanation for why the model output is incorrect.
```

### Other info / Complete Logs

```shell
Detection example: https://i.stack.imgur.com/0SJNI.jpg
```

**Comment by kuaashish** [comment]
Hi @VasilP202,

We have a new Pose Landmarker iOS example available here. You can find it in the [code base](https://github.com/googlesamples/mediapipe/tree/main/examples/pose_landmarker/ios). We recommend implementing it based on that for now. We are currently working to integrate it into the Pose Landmarker documentation section, and it will be available soon.

Thank you!!

**Comment by VasilP202** [comment]
Thank you for the response.

**Comment by VasilP202** [comment]
@kuaashish Yes, will can close the issue.

**Comment by kuaashish** [comment]
Hi @VasilP202,

Thank you for confirming. We are now closing this issue and marking it as resolved internally.

**Comment by radzio216** [comment]
Hey I am in the exact same boat, unpackaged the.task file and tried running .tflite files using `react-native-fast-tflite` library, like you say I can get some results from the first array outputted by the model but it is no where near tracking any poses. Have you made any progress on this front? Have you found some library or managed to process the output to give you some meaningful results?
