### ISSUE TITLE
mediapipe cannot correctly identify landmark

### ISSUE THREAD

**Issue by JV-X** [google/mediapipe#5276]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)
```

    results = pose.process(cv2.cvtColor(nkFrame, cv2.COLOR_BGR2RGB))
    tmp = results.pose_landmarks

    mpDraw = mp.solutions.drawing_utils
    mpPose = mp.solutions.pose
    mpDraw.draw_landmarks(nkFrame, tmp, mpPose.POSE_CONNECTIONS)
    cv2.imencode('.jpg', nkFrame)[1].tofile(os.path.join(os.getcwd() + f'/Ulrobot/inputs/{time.time()}WithLandmarks.jpg'))

```
I am working on a robot project. The robot obtains pictures through the camera, and the obtained pictures identify landmarks through mediapipe. The robot then uses the landmarks to determine whether there is a person on the bed and whether the person's posture is lying flat, and then determines the robot's subsequent actions. But now I encountered a problem: mediapipe cannot correctly identify the landmark in the picture. What should I do to make mediapipe correctly identify the landmark? please give me some suggestions。

### OS Platform and Distribution

macOs 13.6.1 (22G313)

### MediaPipe version

0.9.1.0

### Solution

Pose

### Programming Language and version

Python3.9.13

### Describe the actual behavior

In the photo of the person lying flat on the sofa, mediapipe cannot correctly identify the landmark.

### Describe the expected behaviour

mediapipe correctly identifies landmark

### Other info / Complete Logs
1711682272.3400729WithLandmarks.jpg：

![1711682272 3400729WithLandmarks](https://github.com/google/mediapipe/assets/29137451/6068a0dc-1228-4367-a4c8-891abc31ad57)

**Comment by JV-X** [comment]
How can I make mediapipe correctly identify landmark? Please give me some suggestions.

**Comment by kuaashish** [comment]
Hi @JV-X,

Currently, you are using the legacy pose solution, it has been upgraded and is now part of the Pose Landmarker Task API, offering enhanced capabilities. Please upgrade to the new API. Find documentation [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker) and a Python implementation guide [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python).

For Legacy Solutions, the libraries, documentation, and source code will remain available on GitHub and through services like Maven and NPM. However, support for upgraded solutions has been discontinued. Refer to our [documentation](https://developers.google.com/mediapipe/solutions/guide#legacy) for more information. If you face issues with the new Pose Landmarker Task API implementation, report them here for assistance.

Thank you!!
