### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by moataz2002** [google/mediapipe#5279]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

windows 11

### Programming Language and version

python 3.12

### Solution

FaceMesh

### Describe the actual behavior

I have tried to install it using pip, and it did not install 

### Describe the expected behaviour

not installed

### Standalone code/steps you may have used to try to get what you need

```shell
"pip install" and not worked
```

**Comment by zoroxide** [comment]
mediapipe is not supported for 3.12, try to install it on python 3.9 (downgrade it)
