### ISSUE TITLE
Improvise  the framework

### ISSUE THREAD

**Issue by Zumbalamambo** [google/mediapipe#528]
Thank you for the great work. I understand that you don't want to release the training pipeline for specific detection models but at the least Please provide a simple example of a training pipeline to show how we could train our models with mediapipe.

**Comment by mgyong** [comment]
@Zumbalamambo MediaPipe is mainly an inference framework that supports currently TensorFlow & TFlite. You can create any MediaPipe graph to run any TF or TFlite model. Hence, MediaPipe is independent and not used for model training only inference
