### ISSUE TITLE
Landmarks for FaceMesh model 

### ISSUE THREAD

**Issue by amaancoder** [google/mediapipe#5281]
Hey team,

For the media Pipe Pose Landmarker model we can fetch landmark points (x , y, z ) coordinates for all 33 landmarks, we have a proper explanation in the docs like Nose (Landmark 0): Represents the position of the nose on the face.
Left Eye (Inner, Landmark 1): Marks the inner corner of the left eye.
Left Eye (Center, Landmark 2): Represents the center of the left eye.
Left Eye (Outer, Landmark 3): Marks the outer corner of the left eye... and so on for the pose model. Is there a way to derive landmarks for the   FACEMESH_TESSELATION model as well it has 478 3D facial landmarks, but I am not able to know what are the landmarks for eyebrows, for lips for mouth, any help with this please !

**Comment by kuaashish** [comment]
Hi @amaancoder,

We regret to inform you that the solution you are currently utilizing relies on a legacy face mesh model. Support for this model has been [discontinued](https://developers.google.com/mediapipe/solutions/guide#legacy) as it has been upgraded and integrated into the Face Landmarker Task API. We strongly recommend migrating to our new Task APIs.

Regarding the legacy Face Mesh, we have not found documentation that aligns with the structure of the new Face Landmarker. However, you can view the 3D landmarks for all points here 

https://github.com/google/mediapipe/blob/a908d668c730da128dfa8d9f6bd25d519d006692/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png

In addition, we regret to inform you that we will not be able to provide extensive assistance at this time, as our primary focus is on further improving our new Task APIs.


Thank you!!
