### ISSUE TITLE
tasks-vision does not appear to be compatible with opencv.js

### ISSUE THREAD

**Issue by Mr-AE** [google/mediapipe#5282]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

ubuntu 18.04

### Browser and version if the issue happens on browser

Google Chrome 122.0.6261.128

### Programming Language and version

Javascript

### Solution

Hand landmarks detection

### Describe the actual behavior

I made a simple change based on the example code  you provided（https://codepen.io/mediapipe-preview/pen/gOKBGPN） to introduce opencv.js in it, but when I introduced opencv.js in the html page, the browser got stuck after launching, and I couldn't even open the developer tools through F12

### Describe the expected behaviour

opencv.js can load normally

### Standalone code/steps you may have used to try to get what you need

```shell
Here is the code I adapted based on the example code：

<link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils/drawing_utils.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands.js" crossorigin="anonymous"></script>

<body>
  <p id="status">opencv.js is loading...</p>
  <h1>Hand landmark detection using the MediaPipe HandLandmarker task</h1>

  <script type="module">
    import {HandLandmarker, FilesetResolver} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.0"
    console.log(1, FilesetResolver);
    window.FilesetResolver = FilesetResolver;
    window.HandLandmarker = HandLandmarker;
  </script>

<div class="InputOutput">
  <div class="caption">dstImg</div>
  <canvas id="dstImg"></canvas>
</div>

  <script defer src="src/main_hand.js" type="text/javascript"></script>

  <!-- Without the following line of code, the program can run normally, but I really need opencv for subsequent development -->
  <script async="" src="opencv.js" type="text/javascript" onload="onOpenCvReady();" onerror="onOpenCvError();"></script>

  <section id="demos" class="invisible">
    <h2>Demo: Detecting Images</h2>
    <p><b>Click on an image below</b> to see the key landmarks of the hands.</p>

    <div class="detectOnClick">
      <img src="https://assets.codepen.io/9177687/hand-ge4ca13f5d_1920.jpg" width="100%" crossorigin="anonymous" title="Click to get detection!" />
    </div>
    <div class="detectOnClick">
      <img src="https://assets.codepen.io/9177687/couple-gb7cb5db4c_1920.jpg" width="100%" crossorigin="anonymous" title="Click to get detection!" />
    </div>

  </section>
```

### Other info / Complete Logs

```shell
The src/main_hand.js in the html above is adapted from the js script in the example code（https://codepen.io/mediapipe-preview/pen/gOKBGPN）

I'm running the program using live server in vscode, so I annotate the import HandLandmarker and FilesetResolver sections at the top of the example code, and instead introduce these modules in the html，using
"<script type="module">
    import {HandLandmarker, FilesetResolver} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.0"
    console.log(1, FilesetResolver);
    window.FilesetResolver = FilesetResolver;
    window.HandLandmarker = HandLandmarker;
  </script>
"
The rest is basically the same as in the example code

I can't provide any more logs because the page gets stuck when I open the browser and I can't open the developer tools
Any advice and help would be appreciated！！
```

**Comment by BlockCnFuture** [comment]
i think u can try this.
[opencv-js](https://github.com/TechStark/opencv-js)
i faced a similar problem and was able to solve it by using [TechStark/opencv-js](https://github.com/TechStark/opencv-js). By the way, what project are u currently working on using OpenCV and MediaPipe? I'm interested to it.

**Comment by schmidt-sebastian** [comment]
This is unfortunately not something we can provide support for. I advise that you should migrate your example to a Node environment (for development, and not running) and use a JavaScript bundler to build your sources. This will mean that you will migrate away from multiple script imports (which all pollute the global namesapce) to a single script import with JavaScript modules. This will rule our many areas of potential conflict between these two libraries.

I would also suggest that you migrate to https://www.npmjs.com/package/@mediapipe/tasks-vision
