### ISSUE TITLE
How to implement mediapipe hair segmentation using mindAR ?

### ISSUE THREAD

**Issue by aishwarya123mathpati** [google/mediapipe#5294]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Windows 64

### MediaPipe Tasks SDK version

Task-vision

### Task name (e.g. Image classification, Gesture recognition etc.)

Hair segmentation

### Programming Language and version (e.g. C++, Python, Java)

Javascript

### Describe the actual behavior

Getting errors of mediapipe task vision package

### Describe the expected behaviour

hair segmentation should be apply when we give any image or webcam feed.

### Standalone code/steps you may have used to try to get what you need

```shell
I wants to build a hair segmentation for a web using mindAR.But I'm facing many issues with mediapipe task vision package such as FilesetResolver is not defiend.
```

**Comment by kuaashish** [comment]
Hi @aishwarya123mathpati,

Currently, we have not tested JavaScript compatibility with mindAR. Consequently, we are unable to offer support for it at this time. However, if you submit a [feature request](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Afeature&projects=&template=14-feature-request-issue-template.yaml) outlining the benefits the community would gain from this implementation, we will review it with our team. Depending on the discussion and demand, we may consider implementing this feature in the future.

Thank you!!
