### ISSUE TITLE
What can I do to integrate into my project?

### ISSUE THREAD

**Issue by Sanerly** [google/mediapipe#53]
I use Gradle to compile projects and don't know how to modify them.

I also met：
INFO: Call stack for the definition of repository 'org_tensorflow' which is a http_archive (rule definition at C:/users/administrator/_bazel_administrator/miimwwwx/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - E:/myproject/mediapipe-master/WORKSPACE:103:1
INFO: Repository 'org_tensorflow' used the following cache hits instead of downloading the corresponding file.
 * Hash 'ddd4e3c056e7c0ff2ef29133b30fa62781dfbf8a903e99efb91a02d292fa9562' for https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz
If the definition of 'org_tensorflow' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   Traceback (most recent call last):
	File "C:/users/administrator/_bazel_administrator/miimwwwx/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
		patch(ctx)
	File "C:/users/administrator/_bazel_administrator/miimwwwx/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 91, in patch
		fail(("Error applying patch %s:\n%s%s...)))
Error applying patch //third_party:tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff:
java.io.IOException: ERROR: src/main/native/windows/process.cc(184): CreateProcessW("C:\ProgramData\chocolatey\lib\bazel" -c "patch '-p1' < E:/myproject/mediapipe-master/third_party/tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff"): ?????
ERROR: no such package '@org_tensorflow//tensorflow': Traceback (most recent call last):
	File "C:/users/administrator/_bazel_administrator/miimwwwx/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
		patch(ctx)
	File "C:/users/administrator/_bazel_administrator/miimwwwx/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 91, in patch
		fail(("Error applying patch %s:\n%s%s...)))
Error applying patch //third_party:tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff:
java.io.IOException: ERROR: src/main/native/windows/process.cc(184): CreateProcessW("C:\ProgramData\chocolatey\lib\bazel" -c "patch '-p1' < E:/myproject/mediapipe-master/third_party/tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff"): ?????
Sync finished

**Comment by Sanerly** [comment]
@mgyong 
Thanks a lot, my project is more complicated and it is difficult to migrate from Gradle. I am currently using windows10, bazel is installed with chocolatey, and then I get an error when opening the MediaPipe project:
E:/myproject/mediapipe-master/WORKSPACE:103:1
INFO: Repository 'org_tensorflow' used the following cache hits instead of downloading the corresponding file.
Hash 'ddd4e3c056e7c0ff2ef29133b30fa62781dfbf8a903e99efb91a02d292fa9562' for https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz
If the definition of 'org_tensorflow' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
Traceback (most recent call last):
File "C:/users/administrator/_bazel_administrator/miimwwwx/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
Patch(ctx)

Is it because I don't have the reason to install tensorflow? I don't know now, I am a little dizzy.

**Comment by Sanerly** [comment]
Thank you, may I ask the next version to consider supporting the Gradle compilation of Android studio under Windows?

**Comment by PrinceP** [comment]
@mgyong Can you explain the error. Syncing again with invalidating caches is not working. 
Is it a windows bazel version issue? Or a org_tensorflow patch has to be updated?
Would like to work on this.

**Comment by PrinceP** [comment]
@mgyong Below is the cause of the error in building. 

> #2019-08-15
_TENSORFLOW_GIT_COMMIT = "67def62936e28f97c16182dfcc467d8d1cae02b4"
_TENSORFLOW_SHA256= "ddd4e3c056e7c0ff2ef29133b30fa62781dfbf8a903e99efb91a02d292fa9562"
http_archive(
    name = "org_tensorflow",
    urls = [
      "https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/%s.tar.gz" % _TENSORFLOW_GIT_COMMIT,
      "https://github.com/tensorflow/tensorflow/archive/%s.tar.gz" % _TENSORFLOW_GIT_COMMIT,
    ],
    strip_prefix = "tensorflow-%s" % _TENSORFLOW_GIT_COMMIT,
    sha256 = _TENSORFLOW_SHA256,
    patches = [
        "@//third_party:tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff",
        "@//third_party:tensorflow_f67fcbefce906cd419e4657f0d41e21019b71abd.diff",
    ],
    patch_args = [
        "-p1",
    ],
)

Causing the below error. Which is applying the patch error. Is this a bazel issue.
> ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   Traceback (most recent call last):
	File "C:/users/XX/_bazel_princ/wsixtlup/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
		patch(ctx)
	File "C:/users/XX/_bazel_princ/wsixtlup/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 91, in patch
		fail(("Error applying patch %s:\n%s%s...)))
Error applying patch //third_party:tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff:
/bin/bash: E:/mediapipe/third_party/tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff: No such file or directory
ERROR: no such package '@org_tensorflow//tensorflow': Traceback (most recent call last):
	File "C:/users/XX/_bazel_princ/wsixtlup/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
		patch(ctx)
	File "C:/users/XX/_bazel_princ/wsixtlup/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 91, in patch
		fail(("Error applying patch %s:\n%s%s...)))
Error applying patch //third_party:tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff:
/bin/bash: E:/mediapipe/third_party/tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff: No such file or directory
Sync finished
