### ISSUE TITLE
Is there a way to improve performance through some configuration parameters?

### ISSUE THREAD

**Issue by huanhunx** [google/mediapipe#5300]
Can face landmarkers optimize performance through some parameters during initialization or detection? For example, reducing some detection points, like stopping predicting irises as mentioned in this issue: https://github.com/tensorflow/tfjs/issues/4108

**Comment by kuaashish** [comment]
Hi @huanhunx,

Currently, it seems that achieving this using certain parameters in our Task API may not be possible. However, we will verify this and update you regarding any further possibilities.

Thank you!!

**Comment by schmidt-sebastian** [comment]
Reducing the number of outputs does not significantly affect performance as this woule be done as a post-processing step. Please ensure you are using a GPU delegate and that you input image size is small.
