### ISSUE TITLE
i was not able to install  pip3 install mediapipe-silicon ,it is for mac os air 

### ISSUE THREAD

**Issue by Richard04Carvalho** [google/mediapipe#5301]
### OS Platform and Distribution

mac os 

### Programming Language and version

python

### Android AAR (if android)

None

### Describe the problem

Not able to install media pipe 

### Complete Logs

```shell
ERROR: Could not find a version that satisfies the requirement mediapipe-silicon (from versions: none)
ERROR: No matching distribution found for mediapipe-silicon
```

**Comment by kuaashish** [comment]
Hi @Richard04Carvalho,

Mediapipe-silicon is not an official Pip package managed by us, instead, it's managed by the community. However, we offer an official package that supports Silicon and Intel-based systems on macOS. 


You can install mediapipe by using the command `pip3 install mediapipe`. 

Additionally, please ensure you are using a supported Python version between 3.8 to 3.11 for a successful installation.

Thank you!!

**Comment by Richard04Carvalho** [comment]
thank you its resolved

**Comment by kuaashish** [comment]
Hi @Richard04Carvalho,

Thank you for confirming. Can we now proceed to mark this as resolved and close the status?
