### ISSUE TITLE
MediaPipe build errors in AndroidStudio using Bazel

### ISSUE THREAD

**Issue by MashaKucherova** [google/mediapipe#531]
Sorry for my English in advance.
MediaPipe is not imported into AndroidStudio using Bazel using the instruction https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#using-mediapipe-with-bazel. At step 8, everything stopped working.
Help, please, I can’t cope myself ((
It displays the following warnings:

`WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
Analyzing: 76 targets (151 packages loaded, 4946 targets configured)
Analyzing: 76 targets (158 packages loaded, 12072 targets configured)
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/components:AudioDataConsumer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/components:AudioDataProcessor.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/components:AudioDataProducer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/components:CameraHelper.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/components:CameraXPreviewHelper.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/components:ExternalTextureConverter.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/components:FrameProcessor.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/components:MicrophoneHelper.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/components:PermissionHelper.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/components:TextureFrameConsumer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/components:TextureFrameProcessor.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/components:TextureFrameProducer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:AndroidAssetUtil.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:AndroidPacketCreator.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:AndroidPacketGetter.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:AppTextureFrame.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:AssetCache.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:AssetCacheDbHelper.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:Compat.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:GlSyncToken.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:Graph.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:GraphGlSyncToken.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:GraphProfiler.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:GraphService.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:GraphTextureFrame.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:MediaPipeException.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:MediaPipeRunner.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:Packet.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:PacketCallback.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:PacketCreator.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:PacketGetter.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:PacketWithHeaderCallback.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:SurfaceOutput.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:TextureFrame.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/framework:TextureReleaseCallback.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/glutil:CommonShaders.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/glutil:EglManager.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/glutil:ExternalTextureRenderer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/glutil:GlThread.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/glutil:ShaderUtil.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
WARNING: /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar:mp_hand_tracking_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/glutil:TextureRenderer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation in /home/masha/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar/BUILD:3:1
Analyzing: 76 targets (159 packages loaded, 13571 targets configured)
INFO: Analyzed 76 targets (159 packages loaded, 13662 targets configured).

INFO: Found 76 targets...
INFO: Deleting stale sandbox base /home/masha/.cache/bazel/_bazel_masha/1581b9a5b307cbf84ac90696efbde9c6/sandbox
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 83.063s, Critical Path: 0.49s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully
build invocation result: build_error`

**Comment by jiuqiant** [comment]
Seems like the error is from mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu_aar, which is not in the official version. Do you create this directory for experimental? 
To help us reproduce this issue, I recommend having a clean version of mediapipe. Thanks.

**Comment by criminact** [comment]
How did you solve this?, getting the same logs while building an aar.

**Comment by anz-ryu** [comment]
I have the same issues about this....
