### ISSUE TITLE
Availability of previous version wheels

### ISSUE THREAD

**Issue by matanox** [google/mediapipe#5314]
Is it possible to make older version wheel files available again from pip/pypi or elsewhere?
The new 0.10.x versions introduced novelties in the sense of "new solutions" but for some applications using only a core pipeline it means breaking api changes, and we still use 0.8.x.

### OS Platform and Distribution

Linux, Windows

### Programming Language and version

python 3.x

### Installed using virtualenv? pip? Conda?(if python)

venv

### MediaPipe version

0.8.11, 0.9.x

**Comment by kuaashish** [comment]
Hi @matanox,

Regrettably, we are unable to revert older versions of the wheel back to PyPi due to consistent storage quota limitations. Additionally, we do not maintain an archive of these wheels to provide somewhere else, sorry so we won't be able to help on this.

Thank you!!

**Comment by matanox** [comment]
Noted. Following an upgrade, I have kept my own copy of the latest version wheels.

**Comment by rraulf** [comment]
@matanox Which version do you use?
