### ISSUE TITLE
Mediapipe with WebGL2...

### ISSUE THREAD

**Issue by Honya2000** [google/mediapipe#5316]
Hello,

I compiled mediapipe for WebAssembly, and trying to use GPU backend for segmentation.
But unfortunately when I tried to use InferenceCalculatorGl and bind GPU buffer to tensor - it fails, because seems like only GL_SHADER_STORAGE_BUFFER buffer types are supported as input, which aren't supported in OpenGL ES 3.0 / WebGL2.

I know official webassembly module works with GPU backend. How can i make it working using the official source code ?

P.S. I used SelfieSegmentation API here...

**Comment by Honya2000** [comment]
I tried to use new vision tasks API for gpu inferencing, and got the same issue:

Calculator::Open() for node "mediapipe_tasks_vision_image_segmenter_imagesegmentergraph__mediapipe_tasks_core_inferencesubgraph__inferencecalculator__mediapipe_tasks_vision_image_segmenter_imagesegmentergraph__mediapipe_tasks_core_inferencesubgraph__InferenceCalculator" failed: OpenGL ES 3.1 or above is required to use OpenGL inference.

**Comment by kuaashish** [comment]
Hi @Honya2000,

Could you kindly provide us with comprehensive details regarding the issue? This includes the steps you are following from our documentation, the operating system you are using, and the version of MediaPipe in use. Additionally, you may utilize the provided [template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abug&projects=&template=16-bug-issue-template.yaml) to furnish us with all the necessary information.

Thank you!!
