### ISSUE TITLE
Bazel build helloworld with a '404 Not Found' error

### ISSUE THREAD

**Issue by teafff** [google/mediapipe#533]
Please help me.when i tried to bazel run helloworld,I wait a long time to download some dependencies.And then,it makes error.
So i hope someone can give me some advice.

bazel build -c opt mediapipe/examples/desktop/hello_world:hello_world

INFO: Call stack for the definition of repository 'org_tensorflow' which is a http_archive (rule definition at /home/yu/.cache/bazel/_bazel_yu/04f3bfb84c6a6907e978f30a60ac4394/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/yu/mediapipe/WORKSPACE:124:1
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz failed: class java.io.IOException Tried to reconnect at offset 6,681,882 but server didn't support it
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz, https://github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz] to /home/yu/.cache/bazel/_bazel_yu/04f3bfb84c6a6907e978f30a60ac4394/external/org_tensorflow/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz: Tried to reconnect at offset 6,681,882 but server didn't support it
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz, https://github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz] to /home/yu/.cache/bazel/_bazel_yu/04f3bfb84c6a6907e978f30a60ac4394/external/org_tensorflow/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz: Tried to reconnect at offset 6,681,882 but server didn't support it
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz, https://github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz] to /home/yu/.cache/bazel/_bazel_yu/04f3bfb84c6a6907e978f30a60ac4394/external/org_tensorflow/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz: Tried to reconnect at offset 6,681,882 but server didn't support it
INFO: Elapsed time: 538.786s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by jiuqiant** [comment]
```
class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
```
The error is a 404 Not Found issue during downloading the external dependencies. Please check your network conntection and retry. VPN is preferred if you are in mainland China. See https://github.com/google/mediapipe/issues/3 for more detail.

**Comment by teafff** [comment]
> ```
> class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
> ```
> 
> 该错误是下载外部依赖项时出现的404 Not Found问题。请检查您的网络连接，然后重试。如果您在中国大陆，则首选VPN。有关更多详细信息，请参见[＃3](https://github.com/google/mediapipe/issues/3)。

ok i will try it again

**Comment by teafff** [comment]
> ```
> class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
> ```
> 
> The error is a 404 Not Found issue during downloading the external dependencies. Please check your network conntection and retry. VPN is preferred if you are in mainland China. See #3 for more detail.

ok i will try it again
