### ISSUE TITLE
Incorrect callback method argument for ObjectDetector.detect_async

### ISSUE THREAD

**Issue by nagok** [google/mediapipe#5337]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Windows 10

### Programming Language and version

Python 3.11.8

### MediaPipe version

0.10.11

### Solution

ObjectDetector

### Describe the actual behavior

A Timestamp type value is passed to the third argument of the ObjectDetector.detect_async callback method. Further value is microsecond.

### Describe the expected behaviour

milliseconds as an int

### Standalone code/steps you may have used to try to get what you need

```shell
https://github.com/google-edge-ai/mediapipe-samples/blob/main/examples/object_detection/raspberry_pi/detect.py:62

  def save_result(result: vision.ObjectDetectorResult, unused_output_image: mp.Image, timestamp_ms: int):
      print(timestamp_ms)
```

**Comment by kuaashish** [comment]
Hi @nagok,

We are having difficulty understanding the issue clearly. Could you please provide more details about the problem you are encountering?

Thank you!!

**Comment by kuaashish** [comment]
Hi @nagok,

We have assigned the PR for review and will update you if any updates becomes available.

Thank you!!

**Comment by kuaashish** [comment]
Hi @nagok,

Thank you for bringing this to our attention. The PR has been successfully merged. As a result, we are closing this issue now.
