### ISSUE TITLE
[Customization] About the application of Mediapipe face detection

### ISSUE THREAD

**Issue by momo1986** [google/mediapipe#535]
Hello,  thanks for sharing.

Currently, I want to customize the Mediapipe API for face detection.

I have two questions:
1. Where (Which Java or C++ file ) can I get the result of model inference with facial landmark points and confidence? My customization logic depends on the judgement of the inference result.
2. Which API is responsible for plot the facial landmark point and confidence on the texture frame just like this figure displayed?
![image](https://user-images.githubusercontent.com/34225874/76947501-aaa53a80-6940-11ea-8801-d6e5f03ad8c1.png)

Thanks if there can be some reply.

**Comment by jiuqiant** [comment]
You need to get the [detection](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/framework/formats/detection.proto) protos from the `output_detections` stream. To do this, the best solution is to add a packet callback in the Java code. We do this to the landmark protos in the hand tracking app already. You can follow [the example code](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L111) to do the similar thing to the detection proto in hand tracking app.

Then, there are `relative_keypoints` inside the `location_data` filed of the detection proto to give you the landmarks. For confidence, please retrieve `score` field of the detection proto.

**Comment by momo1986** [comment]
Hello, Jiuqiant, @jiuqiant 

Thanks for repy.

I have defined the detection.proto in mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl.

```
    _proto_java_src_generator(
        name = "detection_proto",
        proto_src = "mediapipe/framework/formats/detection.proto", 
        java_lite_out = "com/google/mediapipe/formats/proto/DetectionProto.java",
        srcs = ["//mediapipe/framework/formats:protos_src"],
    )
```

I made aar
`bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_examples:mp_face_detection_aar`


However, I get the error message:

> mediapipe/framework/formats/annotation/rasterization.proto: File not found.
> mediapipe/framework/formats/location_data.proto: Import "mediapipe/framework/formats/annotation/rasterization.proto" was not found or had errors.
> mediapipe/framework/formats/location_data.proto:76:14: "Rasterization" is not defined.
> mediapipe/framework/formats/detection.proto: Import "mediapipe/framework/formats/location_data.proto" was not found or had errors.
> mediapipe/framework/formats/detection.proto:38:12: "LocationData" is not defined.
> Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_examples:mp_face_detection_aar failed to build
> Use --verbose_failures to see the command lines of failed build steps.



Looks like the dependecies have not been added. 

However, since ther is no guide-line for adding the configuration of java generation from protobuf in bazel file. I tried to do some "guess" modification, but always have gramatical error.

Could you and other Mediapipe guys give some guideline to add dependent protobuf file? If you have no spare time doing this demo, is ther a guide to add the protobuf java generation with dependencies in bazel-file?

Thanks & Regards!
Momo

**Comment by jiuqiant** [comment]
I think you need to do the following to make the location proto available in your aar. 
BTW, we are going to release the following changes in the next push.

```
index dbbf290..3edd542 100644
--- a/mediapipe/framework/formats/location_data.proto
+++ b/mediapipe/framework/formats/location_data.proto
@@ -23,6 +23,9 @@
 
 import "mediapipe/framework/formats/annotation/rasterization.proto";
 
+option java_package = "com.google.mediapipe.formats.proto";
+option java_outer_classname = "LocationDataProto";
+
 message LocationData {
   // The supported formats for representing location data. A single location
   // must store its data in exactly one way.

index 5ea495a..d501901 100644
--- a/mediapipe/framework/formats/annotation/BUILD
+++ b/mediapipe/framework/formats/annotation/BUILD
@@ -49,3 +49,10 @@
     visibility = ["//visibility:public"],
     deps = [":rasterization_proto"],
 )
+
+# Expose the proto source files for building mediapipe AAR.
+filegroup(
+    name = "protos_src",
+    srcs = glob(["*.proto"]),
+    visibility = ["//mediapipe:__subpackages__"],
+)

index 9aad7e8..38414df 100644
--- a/mediapipe/framework/formats/annotation/rasterization.proto
+++ b/mediapipe/framework/formats/annotation/rasterization.proto
@@ -16,6 +16,9 @@
 
 package mediapipe;
 
+option java_package = "com.google.mediapipe.formats.annotation.proto";
+option java_outer_classname = "RasterizationProto";
+
 // A Region can be represented in each frame as a set of scanlines
 // (compressed RLE, similar to rasterization of polygons).
 // For each scanline with y-coordinate y, we save (possibly multiple) intervals

index 0c0d2aa..6078318 100644
--- a/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
+++ b/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
@@ -78,6 +78,33 @@
         srcs = ["//mediapipe/framework/formats:protos_src"],
     )
 
+    _proto_java_src_generator(
+        name = "rasterization_proto",
+        proto_src = "mediapipe/framework/formats/annotation/rasterization.proto",
+        java_lite_out = "com/google/mediapipe/formats/annotation/proto/RasterizationProto.java",
+        srcs = ["//mediapipe/framework/formats/annotation:protos_src"],
+    )
+
+    _proto_java_src_generator(
+        name = "location_data_proto",
+        proto_src = "mediapipe/framework/formats/location_data.proto",
+        java_lite_out = "com/google/mediapipe/formats/proto/LocationDataProto.java",
+        srcs = [
+            "//mediapipe/framework/formats:protos_src",
+            "//mediapipe/framework/formats/annotation:protos_src",
+        ],
+    )
+
+    _proto_java_src_generator(
+        name = "detection_proto",
+        proto_src = "mediapipe/framework/formats/detection.proto",
+        java_lite_out = "com/google/mediapipe/formats/proto/DetectionProto.java",
+        srcs = [
+            "//mediapipe/framework/formats:protos_src",
+            "//mediapipe/framework/formats/annotation:protos_src",
+        ],
+    )
+
     android_library(
         name = name + "_android_lib",
         srcs = [
@@ -86,6 +113,9 @@
             "//mediapipe/java/com/google/mediapipe/glutil:java_src",
             "com/google/mediapipe/proto/CalculatorProto.java",
             "com/google/mediapipe/formats/proto/LandmarkProto.java",
+            "com/google/mediapipe/formats/proto/DetectionProto.java",
+            "com/google/mediapipe/formats/proto/LocationDataProto.java",
+            "com/google/mediapipe/formats/annotation/proto/RasterizationProto.java",
         ],
         manifest = "AndroidManifest.xml",
         proguard_specs = ["//mediapipe/java/com/google/mediapipe/framework:proguard.pgcfg"],
```

**Comment by momo1986** [comment]
Hello, @jiuqiant .

I follow your guide and get the protobuf-generated java code.

Thanks for your reply.

In your demo,  you name the hand pose graph node stream as:

` private static final String OUTPUT_LANDMARKS_STREAM_NAME = "hand_landmarks";`


I am not very sure what is the naming of the graph node stream for similar face detection, 

I name it as:

` private static final String OUTPUT_DETECTIONS_STREAM_NAME = "output_detections";`


And I write the callback code as:

```
processor.addPacketCallback(
                OUTPUT_DETECTIONS_STREAM_NAME,
                (packet) -> {
                    byte[] detectionsRaw = PacketGetter.getProtoBytes(packet);
                    try {
                        DetectionList detections = DetectionList.parseFrom(detectionsRaw);
                        if (detections == null) {
                            Log.d(TAG, "[TS:" + packet.getTimestamp() + "] No face detections.");
                            return;
                        }
                        // Note: If hand_presence is false, these landmarks are useless.
                        Log.d(
                                TAG,
                                "[TS:"
                                        + packet.getTimestamp()
                                        + "] #Landmarks for face: "
                                        + getDetectionsDebugString(detections));
                    } catch (InvalidProtocolBufferException e) {
                        Log.e(TAG, "Couldn't Exception received - " + e);
                        return;
                    }
                });
```

It reported with the error messages:

> A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 11612 (Thread-4), pid 11552 (o.piano.ai.demo)


Looks like the stream is not available.

I can get the stream with the name of "render_data":

But when I parse it with getDetectionsDebugString:
```
    private static String getDetectionsDebugString(DetectionList detections) {
        int detectionIndex = 0;
        String detectionsString = "";
        System.out.println(detections.getDetectionCount());
        for (Detection detection : detections.getDetectionList()) {
            if (detection.hasDetectionId() && detection.getAssociatedDetections(0).getConfidence() > 0.5) {
                detectionsString +=
                        "\t\tdetection["
                                + detectionIndex
                                + "]: ("
                                + "feature-tag: "
                                + detection.getFeatureTag()
                                + "confidence: "
                                + detection.getAssociatedDetections(0).getConfidence()
                                + ",width: "
                                + detection.getLocationData().getRelativeBoundingBox().getWidth()
                                + ", height: "
                                + detection.getLocationData().getRelativeBoundingBox().getHeight()
                                + ", left: "
                                + detection.getLocationData().getRelativeBoundingBox().getXmin()
                                + ", top: "
                                + detection.getLocationData().getRelativeBoundingBox().getYmin()
                                + ")\n";
                ++detectionIndex;
            }
        }
        return detectionsString;
    }
```

Only got it with the empty string.

To be frank, I still needs time to customize the Mediapipe with matured sense.

Could you guide me that what is the correct pose to get the correct data packet callback during face_detections? Since for the node, I can get the stream of **input_video, render_data and out_video**,  there are several stream node with the name of "detection", some nodes like "output_detections" cannot be retrieved.

Regards!

**Comment by eknight7** [comment]
Hi @momo1986, here are some answers.

> there are several stream node with the name of "detection", some nodes like "output_detections", "labeled_detections" and "filtered_detections" cannot be retrieved.

A way to determine what is the output you need is to see what is being rendered in the graph. For example, the detections in the `output_detection` stream are rendered as output in the [face detection graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt#L168). So `output_detections` is the correct stream name.

> Could you guide me that what is the correct pose to get the correct data packet callback during face_detection? 

An example of how to get detection objects and parse them in Java is shown in the [objectdetectiongpu Android demo](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu/MainActivity.java#L98-L104).

> I can get the stream with the name of "render_data":
But when I parse it with getDetectionsDebugString:

No, `render_data` contains objects of a different type. To determine which type it is, see the calculator code. For example, [AnnotationOverlayCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/annotation_overlay_calculator.cc#L308) code shows that it expects input streams to contain objects of type `RenderData` which is a different proto from `Detection`. So a `RenderData` proto cannot be parsed using the `getDetectionsDebugString()` function.

> there are several stream node with the name of "detection", some nodes like "output_detections", "labeled_detections" and "filtered_detections" cannot be retrieved.

You raise a good question: how to determine what is the final output? One way as suggested above is to see what is finally rendered in the graph at the end. Here are a couple of other ways:

1. Follow the streams: In the [face detection graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt), the first node that produces _any_ kind of detections is `TfLiteInferenceCalculator` which produces a ["detection_tensor"](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt#L65). Note, however, the type of the `detection_tensor` is not easily parse-able, so the graph has another `TfLiteTensorsToDetectionsCalculator` which as [described](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt#L97-L99):
    > Decodes the detection tensors generated by the TensorFlow Lite model, based on the SSD anchors and the specification in the options, into a vector of detections. Each detection describes a detected object.
  
    So this is the first place producing `Detection` proto objects. But there is still more work done in the graph. The `NonMaxSuppressionCalculator` performs [non-max suppression](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt#L126) to remove excessive detections and outputs `filtered_detections`. This is definitely more useful than the `detections` stream.
    But there are a couple more operations. `DetectionsLabelIdToTextCalculator` maps label IDs to the label text "Face", and outputs `labeled_detections`.  Then `DetectionLetterboxRemovalCalculator` [adjusts detection locations](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/face_detection_mobile_gpu.pbtxt#L154-L157) on the letterboxed image to output `output_detections`. This is what makes it possible to render the detection correctly on the output image.

2. Try using https://viz.mediapipe.dev/ to visualize the graph and follow the streams:
    <img width="365" alt="face_detection_viz" src="https://user-images.githubusercontent.com/1650256/77184668-5b205500-6a8d-11ea-851d-1f97a6a726b3.png">
    It becomes easier to follow what's going on in the graph with the visualization.

Hope this helps!

**Comment by jiuqiant** [comment]
> You need to get the [detection](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/framework/formats/detection.proto) protos from the `output_detections` stream. To do this, the best solution is to add a packet callback in the Java code. We do this to the landmark protos in the hand tracking app already. You can follow [the example code](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L111) to do the similar thing to the detection proto in hand tracking app.
> 
> Then, there are `relative_keypoints` inside the `location_data` filed of the detection proto to give you the landmarks. For confidence score, please retrieve the `score` field of the detection proto.

In my pervious comment, I already pointed out that the detection messages can be retrieved from the `output_detections` stream ;)

**Comment by momo1986** [comment]
Hello， @jiuqiant @eknight7 .

I think this can work.

Thanks for your sincere, patient and nice reply.

Regards!

**Comment by PopoTeaTree** [comment]
Thank you a lot for this and it works!!! in Hand tracking mobile application (Android)
P.S. Don't forget to add OUTPUT_DETECTIONS_STREAM_NAME = "palm_detections" (output stram name)

processor?.addPacketCallback(
OUTPUT_DETECTIONS_STREAM_NAME
){ packet: Packet ->
         val detections = PacketGetter.getProtoVector(packet,
         DetectionProto.Detection.parser())
         if(detections == null){
                 Log.d("OPFH", "detections null")
          }
        else{
                Log.d("OPF", "detections not null 0: ${detections}")
        }
}

**Comment by tmsbyim01** [comment]
@momo1986 Can you share your final code? I'm facing the same problem, I use the "output_detections" and get nothing.
I want to know the number of "Face,1,", "Face,0.99," which in red rectangle.

**Comment by LMR2018** [comment]
> 您需要从流中获取[检测](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/framework/formats/detection.proto)原型`output_detections`。为此，最好的解决方案是在 Java 代码中添加数据包回调。我们已经在手部跟踪应用程序中对具有里程碑意义的原型进行了此操作。您可以按照[示例代码](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L111)执行与手部跟踪应用程序中的检测原型类似的操作。
> 
> 然后，有`relative_keypoints`内部`location_data`提出的检测原的给你的地标。对于置信度分数，请检索`score`检测原型的字段。

@jiuqiant   I am a newbie, can you tell me more about the specific implementation?  I want to look at the image preprocessing and inference process of android Hand_landmark model and I want to know how long each process take
