### ISSUE TITLE
0.10.12 not released on Pypi

### ISSUE THREAD

**Issue by twoertwein** [google/mediapipe#5356]
Version 0.10.12 is available on npm https://www.npmjs.com/package/@mediapipe/tasks-vision but pypi is still at 0.10.11 https://pypi.org/project/mediapipe/

**Comment by kuaashish** [comment]
Hi @twoertwein,

You are correct. We are about to release version 0.10.12 across other repositories including GitHub, PyPI, and Maven. It is on our pipeline and it should be available within this week.

Thank you!!
