### ISSUE TITLE
Take too much time to load camera hair segmentation

### ISSUE THREAD

**Issue by Annonymous844** [google/mediapipe#536]
Device Oppo A1k

I/tflite: Initialized TensorFlow Lite runtime.
I/tflite: Created TensorFlow Lite delegate for GPU.
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 2 is dropped, handle=0x7463442200
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 3 is dropped, handle=0x74634422c0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 4 is dropped, handle=0x7463441cc0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 5 is dropped, handle=0x7463443640
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 0 is dropped, handle=0x7463443040
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 6 is dropped, handle=0x7463443c40
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 2 is dropped, handle=0x7463442200
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 3 is dropped, handle=0x74634422c0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 4 is dropped, handle=0x7463441cc0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 5 is dropped, handle=0x7463443640
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 0 is dropped, handle=0x7463443040
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 6 is dropped, handle=0x7463443c40
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 2 is dropped, handle=0x7463442200
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 3 is dropped, handle=0x74634422c0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 4 is dropped, handle=0x7463441cc0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 5 is dropped, handle=0x7463443640
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 0 is dropped, handle=0x7463443040
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 6 is dropped, handle=0x7463443c40
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 2 is dropped, handle=0x7463442200
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 3 is dropped, handle=0x74634422c0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 4 is dropped, handle=0x7463441cc0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 5 is dropped, handle=0x7463443640
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 0 is dropped, handle=0x7463443040
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 6 is dropped, handle=0x7463443c40
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 2 is dropped, handle=0x7463442200
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 3 is dropped, handle=0x74634422c0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 4 is dropped, handle=0x7463441cc0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 5 is dropped, handle=0x7463443640
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 0 is dropped, handle=0x7463443040
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 6 is dropped, handle=0x7463443c40
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 2 is dropped, handle=0x7463442200
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 3 is dropped, handle=0x74634422c0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 4 is dropped, handle=0x7463441cc0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 5 is dropped, handle=0x7463443640
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 0 is dropped, handle=0x7463443040
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 6 is dropped, handle=0x7463443c40
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 2 is dropped, handle=0x7463442200
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 3 is dropped, handle=0x74634422c0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 4 is dropped, handle=0x7463441cc0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 5 is dropped, handle=0x7463443640
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 0 is dropped, handle=0x7463443040
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 6 is dropped, handle=0x7463443c40
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 2 is dropped, handle=0x7463442200
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 3 is dropped, handle=0x74634422c0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 4 is dropped, handle=0x7463441cc0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 5 is dropped, handle=0x7463443640
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 0 is dropped, handle=0x7463443040
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 6 is dropped, handle=0x7463443c40
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 2 is dropped, handle=0x7463442200
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 3 is dropped, handle=0x74634422c0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 4 is dropped, handle=0x7463441cc0
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 5 is dropped, handle=0x7463443640
I/BufferQueueProducer: [SurfaceTexture-0-23554-0](this:0x74510f2800,id:0,api:4,p:654,c:23554) queueBuffer: slot 0 is dropped, handle=0x7463443040

Thanks in advance:))

**Comment by mcclanahoochie** [comment]
I'm not sure what the question is..
Does the app run at all? 
Are you only having an issue with hair segmentation app? 
Please describe more of what you are seeing. 

Also, these BufferQueueProducer logs are from the android OS...
Can you provide more logs that include messages from MediaPipe and the app? 
Are you running the most recent version of MediaPipe?

Thanks

**Comment by Annonymous844** [comment]
# You may run setup_android.sh to install Android SDK and NDK.
android_ndk_repository(
    name = "androidndk",
    api_level = 21,
)

android_sdk_repository(
    name = "androidsdk",
)


i am using AAR file for hair segmentation app

it run perfectly almost in all devices like redmi note 5 ,realme 5 pro, oppp a57 but when it comes to oppo a1k it takes too much time to load camera not only hair app bt all other apps like facedetection, hand detection etc..

after, camera load successfully, app is not working properly means it's not applying color in hair 
i am using princep [repository](https://github.com/PrinceP/mediapipe/blob/master/mediapipe/docs/hair_segmentation_mobile_gpu.md)

**Comment by mcclanahoochie** [comment]
the princep repository may not be the most updated one, please try the official mediapipe repo.

can you provide more of the logcat output?

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by computerfriendlog** [comment]
Facing same issue, When click image by camera it start buffing and it shows continually this line in log call
BufferQueueProducer(18387): [SurfaceTexture-0-18387-1](this:0x7443d88000,id:3,api:4,p:689,c:18387) queueBuffer: slot 0 is dropped, handle=0x7499b072c0
