### ISSUE TITLE
python version mediapipe

### ISSUE THREAD

**Issue by Ai-is-light** [google/mediapipe#539]
there will be one python version's mediapipe? I would like to produce more algrithm with python.

**Comment by jiuqiant** [comment]
Yes, we are woking on the Python API. The OSS release plan is still quite vague: https://github.com/google/mediapipe/issues/444#issuecomment-599249534. Will keep you posted.

**Comment by mgyong** [comment]
MediaPipe python is released in v0.7.9 https://google.github.io/mediapipe/getting_started/building_examples.html#python
