### ISSUE TITLE
Is there a plan to support python and c++ mixed programming?

### ISSUE THREAD

**Issue by noah003** [google/mediapipe#540]
For example, in one Graph, one node/calculator is implemented in Python and the other node/calculator is implemented in C++

**Comment by jiuqiant** [comment]
Yes, we are woking on the Python API. The OSS release plan is still quite vague: https://github.com/google/mediapipe/issues/444#issuecomment-599249534. Will keep you posted.

**Comment by mgyong** [comment]
@noah003 MediaPipe for Python is released in v0.7.9 https://google.github.io/mediapipe/getting_started/building_examples.html#python

**Comment by tjtanaa** [comment]
@mgyong I think this might be different from what the original questions is asking.

And is it possible to create a c++ mediapipe graph that includes one node that runs Python.

I am thinking of building a pipeline with all other pre-processing nodes that run on C++ and a node that runs deep learning model in python environment instead.

I do not want to fully run everything in Python.

**Comment by matanster** [comment]
I think the OP meant the ability to invoke calculators written in python not just calculator nodes which are C++ binaries.
