### ISSUE TITLE
Face Detection on Web: Accessing Facial Point Detections

### ISSUE THREAD

**Issue by tomatopuree** [google/mediapipe#545]
Hello!

I am trying to use mediapipe's face detection capabilities on the browser but I am unable to access the facial landmarks detected by the application.

The demo I reference is this one:
https://viz.mediapipe.dev/runner/demos/face_detection/face_detection.html

So far I was able to download the html file and various other scripts, json and graph definitions by the use of chrome devtools' network interface, and make the app work locally on my machine by an impromptu node server.

Upon making the app work locally, I tried printing the value of the "detections" object referenced in the 42nd line **(*)** of the source code above, hoping it would contain the facial landmark points I am looking for, but it does not.

Since that lead me nowhere, I inspected the graph definition (cpu_oss_facedetect.pbtxt) to find a textual reference to a "Tensorflow Lite Model" used by the Mediapipe system on line 60 **(\*\*)**. 

I could not find this model through google or through the catalogue of pre-trained tensorflow lite models on the tensorflow website

My goal is to gain access to and use this specific model the mediapipe demo above uses to make clientside inference.

Thus my question is two-fold:

1. Does the mediapipe API expose the facial landmark position information?
2. What is  the "Tensorflow Lite model" that the above demo uses, and how can I gain access to it?

I tried greping through all the files that the above demo uses for a reference to a model to no avail.

Thank you.

**\***
```
    videoProcessor.setOutputProcessor({
      process: (detections) => {
        let detectionString = 'No Detections.';
        if (detections && detections.current_mspf > 0.0) {
          // console.log(detections);
          detectionString = (1000.0 / detections.current_mspf).toFixed(2) + ' fps';
        }
        document.getElementById('message').textContent = detectionString;
      }
    });
```

**\*\***
```
# Runs a TensorFlow Lite model on GPU that takes an image tensor and outputs a
# vector of tensors representing, for instance, detection boxes/keypoints and
# scores.

```

**Comment by khelkun** [comment]
https://blog.tensorflow.org/2020/03/face-and-hand-tracking-in-browser-with-mediapipe-and-tensorflowjs.html

**Comment by tomatopuree** [comment]
Thank you very much for your help.

**Comment by asi9games** [comment]
hey @tomatopuree could you please shed some light on exactly how you were able to " to download the html file and various other scripts, json and graph definitions by the use of chrome devtools' network interface, and make the app work locally on my machine by an impromptu node server" ?

I'm trying to do the same with this example https://viz.mediapipe.dev/demo/hand_detection

**Comment by tomatopuree** [comment]
Hey Giovanni

If you can find a working link for the demo, you can press ctrl+shift+i on chrome, go to networks tab, refresh the page.

This will send all the uncached files that the server sends to you when you run the program.

I don't recall which of these files are essential for the demo to work. You'll have to use your best judgement to select those files and download them. I think I identify some of these files in the original post.

Then you can google "how to create a node server" and "how to serve html pages with node" and create one on your local machine to serve the main page of the files you've downloaded. I'm sure you can figure out how to serve a page with a node server.

Normally after downloading a html file, you can double click it and bypass having to make a server to serve it to your browser. In this case I think some additional files need to be served alongside the demo html. 

You can identify which files you need to serve, and at which URIs, by using the networks tab of the ctrl+shift+i interface. In that tab you will see a list of things, these are a complete list of the requests and deliveries that the server is making. What you need to do is to request and deliver the things that the server is requesting and delivering (emulate). 

This is a hacky way to go about it, but since mediapipe is a bit of a blackbox in the context of this demo, it is a way that allowed me to run the script in a couple of 10 minutes.

**Comment by asi9games** [comment]
thanks a ton! @tomatopuree
