### ISSUE TITLE
handtrackinggpu does not work on the phone

### ISSUE THREAD

**Issue by MashaKucherova** [google/mediapipe#546]
Hey. I followed the installation instructions for “Setting up Android Studio with MediaPipe”. The installation was successful, the assembly of the handtrackinggpu project was also error-free. But when I launch the application on my phone, after asking for permission to access the camera, the application does not work. Here is the error report on the phone:

com.google.mediapipe.framework.MediaPipeException: not found: ValidatedGraphConfig Initialization failed.
No registered object with name: PreviousLoopbackCalculator; Unable to find Calculator "PreviousLoopbackCalculator"
No registered object with name: GateCalculator; Unable to find Calculator "GateCalculator"
No registered object with name: HandDetectionSubgraph; Unable to find Calculator "HandDetectionSubgraph"
No registered object with name: HandLandmarkSubgraph; Unable to find Calculator "HandLandmarkSubgraph"
No registered object with name: PreviousLoopbackCalculator; Unable to find Calculator "PreviousLoopbackCalculator"
No registered object with name: MergeCalculator; Unable to find Calculator "MergeCalculator"
No registered object with name: RendererSubgraph; Unable to find Calculator "RendererSubgraph"
at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:289)
at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:372)
at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:296)
at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:311)
at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:275)
at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:221)
at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$Y1vV_XyLsWZ0ebOvq-iwjQ0H3Sw.run(Unknown Source:4)
at android.os.Handler.handleCallback(Handler.java:794)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:176)
at com.google.mediapipe.glutil.GlThread.run(GlThread.java:134)

**Comment by eknight7** [comment]
It seems like it is having issues finding the calculator build dependencies. Can you please point to the exact instructions you followed? That is are you building this with Bazel or AAR on Android? Also, what is your Android phone/version?

**Comment by MashaKucherova** [comment]
> Похоже, у него проблемы с поиском зависимостей сборки калькулятора. Можете ли вы указать точные инструкции, которые вы следовали? То есть вы строите это с помощью Bazel или AAR на Android? Кроме того, каков ваш телефон / версия Android?

Used this instruction https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md

My phone Xiaomi redmi 5a, Android 8.1

**Comment by jiuqiant** [comment]
What's the` mediapipe_aar` rule you wrote for handtrackinggpu? Form the error message, it seems that you don't list all the calculators the handtrackinggpu app needs in the `mediapipe_aar` rule.

For your reference, here is an example repo for multihandtracking aar: https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example. You can test if that works on your devices.

**Comment by DandyLorenz** [comment]
> 嘿。我遵循了“使用MediaPipe设置Android Studio”的安装说明。安装成功，handtrackinggpu项目的组装也没有错误。但是，当我在手机上启动该应用程序时，在请求访问摄像机的权限后，该应用程序无法工作。这是手机上的错误报告：
> 
> com.google.mediapipe.framework.MediaPipeException：找不到：ValidatedGraphConfig初始化失败。
> 没有名称为：PreviousLoopbackCalculator的注册对象；找不到计算器“ PreviousLoopbackCalculator”
> 没有注册名称为：GateCalculator;的对象。找不到计算器“ GateCalculator”
> 没有注册名称为HandDetectionSubgraph的对象；找不到计算器“ HandDetectionSubgraph”
> 没有注册对象，名称为：HandLandmarkSubgraph; 找不到计算器“ HandLandmarkSubgraph”
> 没有注册名称为：PreviousLoopbackCalculator的对象；找不到计算器“ PreviousLoopbackCalculator”
> 没有注册名称为：MergeCalculator的对象；找不到计算器“ MergeCalculator”
> 没有名称为RendererSubgraph的注册对象；
> 在com.google.mediapipe.components的com.google.mediapipe.framework.Graph.nativeStartRunningGraph（本机方法）
> com.google.mediapipe.framework.Graph.startRunningGraph（Graph.java:289）
> 上找不到计算器“ RendererSubgraph” .FrameProcessor.startGraph（FrameProcessor.java:372）
> 在com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame（FrameProcessor.java:296）
> 在com.google.mediapipe.components.FrameProcessor.onNewFrame（FrameProcessor.java:311）
> 在com.google.mediapipe.components.ExternalTextureConverter $ RenderThread.renderNext（ExternalTextureConverter.java:275）
> 在com.google.mediapipe.components
> .- $$ Lambda $ ExternalTextureConverter $ RenderThread $ Y3v-Q1Y_vV_Y1vV_Y1v_V_H_Y1vV_Y1v_W_HQ0Y_v1
> 在android.os.Looper.loop（Looper.java :)在android.os.Handler.dispatchMessage（Handler.java:99）
> 在android.os.Handler.handleCallback（Handler.java:794）运行（Unknown Source：4）
> ： 176）
> com.google.mediapipe.glutil.GlThread.run（GlThread.java:134）

你好，你解决了该问题了吗？我使用新版本，也出现了和你一样的问题，如果你解决了，请告知方法到我的邮箱：1213126651@qq.com，不胜感激

**Comment by DandyLorenz** [comment]
> 嘿。我按照安装说明“用MediaPike设置AndroidStudio”。安装是成功的，手工跟踪gpu项目的组装也是没有错误的。但是当我在手机上启动应用程序时，在请求允许访问相机之后，应用程序就不能工作了。这是电话上的错误报告：
> 
> 未找到com.google.mediapipe.framework.MediaPipeException：：ValidatedGraphConfig初始化失败。
> 没有注册对象的名称：PreviousLoopbackCalculator；无法找到Calculator“PreviousLoopbackCalculator”
> 没有注册对象的名称：GateCalculator；无法找到Calculator“GateCalculator”
> 没有注册对象的名称：HandDetection子图；无法找到计算器“HandDetectionSub图”
> 没有注册对象的名称：HandLandmark子图；无法找到计算器“HandLandmark子图”
> 没有注册对象的名称：PreviousLoopbackCalculator；无法找到Calculator“PreviousLoopbackCalculator”
> 未注册名为MergeCalculator的对象：MergeCalculator；无法找到计算器“MergeCalculator”
> 没有已注册对象的名称：Renderer子图；无法找到计算器“Renderer子图”
> Com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native法)
> 在com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:289)
> 在com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:372)
> 在com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:296)
> 在com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:311)
> 在com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:275)
> 在com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:221)
> 资料来源：4)
> 在android.os.Handler.handleCallback(Handler.java:794)
> 在android.os.Handler.dispatchMessage(Handler.java:99)
> 在android.os.Looper.loop(Looper.java：176)
> 在com.google.mediapipe.glutil.GlThread.run(GlThread.java:134)

do you resolve it?Can you help me see how to solve this problem?Thanks. https://github.com/google/mediapipe/issues/1450
