### ISSUE TITLE
Docker built Android objecttrackinggpu example fail to build

### ISSUE THREAD

**Issue by OnTheRicky** [google/mediapipe#548]
I'm trying to build the Android Objecttrackinggpu example using the Docker image of Mediapipe but it fails giving this error:

> ERROR: /mediapipe/mediapipe/util/tracking/BUILD:376:1: C++ compilation of rule '//mediapipe/util/tracking:motion_estimation' failed (Exit 254) clang failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/sandbox/processwrapper-sandbox/613/execroot/mediapipe && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target aarch64-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fpic -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -isystemexternal/androidndk/ndk/sysroot/usr/include/aarch64-linux-android '-D__ANDROID_API__=28' -O2 -g -DNDEBUG -MD -MF bazel-out/android-arm64-v8a-opt/bin/mediapipe/util/tracking/_objs/motion_estimation/motion_estimation.pic.d '-frandom-seed=bazel-out/android-arm64-v8a-opt/bin/mediapipe/util/tracking/_objs/motion_estimation/motion_estimation.pic.o' -fPIC -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -iquote . -iquote bazel-out/android-arm64-v8a-opt/bin -iquote external/com_google_protobuf -iquote bazel-out/android-arm64-v8a-opt/bin/external/com_google_protobuf -iquote external/zlib_archive -iquote bazel-out/android-arm64-v8a-opt/bin/external/zlib_archive -iquote external/com_github_glog_glog -iquote bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog -iquote external/com_google_absl -iquote bazel-out/android-arm64-v8a-opt/bin/external/com_google_absl -iquote external/eigen_archive -iquote bazel-out/android-arm64-v8a-opt/bin/external/eigen_archive -isystem external/com_google_protobuf/src -isystem bazel-out/android-arm64-v8a-opt/bin/external/com_google_protobuf/src -isystem external/zlib_archive -isystem bazel-out/android-arm64-v8a-opt/bin/external/zlib_archive -isystem external/com_github_glog_glog/src -isystem bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/src -isystem external/eigen_archive -isystem bazel-out/android-arm64-v8a-opt/bin/external/eigen_archive -Wno-sign-compare -Wno-unused-function -Wno-uninitialized -Wno-unused-result -Wno-comment -Wno-return-type -Wno-unused-local-typedefs -Wno-ignored-attributes '-std=c++14' -DPARALLEL_INVOKER_ACTIVE '--sysroot=external/androidndk/ndk/platforms/android-28/arch-arm64' -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c mediapipe/util/tracking/motion_estimation.cc -o bazel-out/android-arm64-v8a-opt/bin/mediapipe/util/tracking/_objs/motion_estimation/motion_estimation.pic.o)
Execution platform: @local_config_platform//:host

**Comment by jiuqiant** [comment]
What's your host platform? I just tested the MediaPipe Docker container on Debian 9 and it can build the object tracking gpu app. I also heard that some host platform doesn't support MediaPipe Docker well. For example, if the host platform is Windows please try WSL instead.

```
root@778609c821fd:/mediapipe# bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu
INFO: Writing tracer profile to '/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/command.profile.gz'
INFO: Build options --compilation_mode, --cpu, --crosstool_top, and 4 more have changed, discarding analysis cache.
......
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu:objecttrackinggpu up-to-date:
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu/objecttrackinggpu_deploy.jar
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu/objecttrackinggpu_unsigned.apk
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu/objecttrackinggpu.apk
INFO: Elapsed time: 183.860s, Critical Path: 116.45s
INFO: 2861 processes: 1 local, 2708 processwrapper-sandbox, 152 worker.
INFO: Build completed successfully, 3020 total actions
```

**Comment by OnTheRicky** [comment]
I'm using macOS. 

I thought the point of Docker was so everything just works, regardless of host platform?
