### ISSUE TITLE
App doesn't respond to user created model in ObjectTracking

### ISSUE THREAD

**Issue by greenorblack** [google/mediapipe#549]
I trained my own model (ssd mobilenet v2 - same as the one used in the example model) for Object Tracking. 
The differences are the following 
1. Number and names of classes
2. Input resolution

Reflected the corresponding changes in:
1. subgraph pbtxt file: mediapipe/graphs/tracking/subgraphs/object_detection_gpu.pbtxt
2. The labelmap file in : mediapipe/mediapipe/models/ssdlite_object_detection_labelmap.txt

Proceeded to create the tflite model according the instructions in 
mediapipe/mediapipe/models/object_detection_saved_model/README.md

Unfortunately, when I load the app, I only get a one frozen picture and then a blank screen.
What am I missing ?

Everything was done on an Ubuntu OS (18.04)
No errors were presented during the entire process. 
When using the sample model, the app runs perfectly fine.

**Comment by ibrandiay** [comment]
@NithyaMogane-TomTom You found a solution to your problem because I also have the same problem.?

**Comment by Kelach** [comment]
> It's okay, I found the solution, glory to me

would you mind sharing it?
