### ISSUE TITLE
Docker built coral:object_detection_tpu example fail to build

### ISSUE THREAD

**Issue by NestorGL** [google/mediapipe#551]
I'm trying to build the Coral object_detection_tpu example using the Docker image of Mediapipe (cross-compiling for Raspberry Pi 4) but it fails.
OS on Raspberry Pi 4: Ubuntu 18.04.1 (aarch64)
It seems that platform Linux_arm64 is undefined.
Here is my log:
[mediapipe.log](https://github.com/google/mediapipe/files/4369928/mediapipe.log)

**Comment by mcclanahoochie** [comment]
Hi,
Thanks for reporting this. 

It looks like this is due to a recent update in our TF/XNNPack dependencies. We will try to provide an official fix soon. 

Meanwhile, you can safely comment out any xnnpack deps for now (cpuinfo comes from xnnpack).

Please comment out the following:

[from /mediapipe/mediapipe/calculators/tflite/BUILD]
- `"@org_tensorflow//tensorflow/lite/delegates/xnnpack:xnnpack_delegate",` 

[from tflite_inference_calculator.cc]
- entire  `if (xnnpack_requested) {` block, line 646
- `#include "tensorflow/lite/delegates/xnnpack/xnnpack_delegate.h"` 

This should at least allow you to run examples on the default CPU delegate

**Comment by NestorGL** [comment]
Thanks for answering.
This solved the compilation problem. Will this work for Coral TPU acselerator or should I use CPU?

**Comment by NestorGL** [comment]
TensorFlow Lite Object Detection on **Desktop** Demo
 . . .
I0324 12:45:29.984902  6340 simple_run_graph_main.cc:121] Initialize the calculator graph.              
I0324 12:45:29.986603  6340 simple_run_graph_main.cc:134] Start running the calculator graph.           
W0324 12:45:30.287132  6342 calculator_graph.cc:1148] Resolved a deadlock by increasing max_queue_size o
f input stream: input_video_header to: 2. Consider increasing max_queue_size for better performance.    
I0324 12:51:11.939837  6340 simple_run_graph_main.cc:149] **Success!**

Object Detection on **Coral**
 . . .
I0324 13:04:17.507608  7522 demo_run_graph_main.cc:53] Initialize the calculator graph.                 
I0324 13:04:17.509316  7522 demo_run_graph_main.cc:57] Initialize the camera or load the video.         
I0324 13:04:17.953353  7522 demo_run_graph_main.cc:87] Start running the calculator graph.              
I0324 13:04:20.649418  7522 demo_run_graph_main.cc:92] Start grabbing and processing frames.            
ERROR: Internal: Unsupported data type in custom op handler: -1756466816                                
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.                                             
                                                                                                        
Failed to allocate edge TPU tensors.                                                                    
ERROR: Internal: Unsupported data type in custom op handler: -1756466816                                
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.                                             
                                                                                                        
Segmentation fault (core dumped)

In both cases i used mediapipe/examples/desktop/object_detection/test_video.mp4 as input stream.

**Comment by mcclanahoochie** [comment]
Can you try modifying your `/mediapipe/WORKSPACE` file to update the tensorflow section like below

```
# 2020-02-12
# The last commit before TensorFlow switched to Bazel 2.0
# _TENSORFLOW_GIT_COMMIT = "77e9ffb9b2bfb1a4f7056e62d84039626923e328"
# _TENSORFLOW_SHA256= "176ccd82f7dd17c5e117b50d353603b129c7a6ccbfebd522ca47cc2a40f33f13"
_TENSORFLOW_GIT_COMMIT = "d855adfc5a0195788bf5f92c3c7352e638aa1109"
_TENSORFLOW_SHA256= "b8a691dbea2bb028fa8f7ce407b70ad236dae0a8705c8010dc7bad8af7e93bac"
http_archive(
    name = "org_tensorflow",
    urls = [
      "https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/%s.tar.gz" % _TENSORFLOW_GIT_COMMIT,
      "https://github.com/tensorflow/tensorflow/archive/%s.tar.gz" % _TENSORFLOW_GIT_COMMIT,
    ],
    # A compatibility patch
    # patches = [
    #     "@//third_party:org_tensorflow_528e22eae8bf3206189a066032c66e9e5c9b4a61.diff"
    # ],
    # patch_args = [
    #     "-p1",
    # ],
    strip_prefix = "tensorflow-%s" % _TENSORFLOW_GIT_COMMIT,
    sha256 = _TENSORFLOW_SHA256,
)
```
I changed the commit version & sha to match the one mentioned here https://coral.ai/docs/edgetpu/tflite-cpp/#build-your-project and removed the patch

Unfortunately I don't have a board at the moment to test runtime, but I can verify the compilation at least.

**Comment by NestorGL** [comment]
Thank you very much.
Now examples are compilable and runnable! :) There is another problem: when a video stream is closed (or the end of the file is reached), the programs crash with error:
Segmentation fault (core dumped).
I think I'll solve it myself.
Thank you for your help.
