### ISSUE TITLE
Landmark X strange range of values 

### ISSUE THREAD

**Issue by romaindebraize** [google/mediapipe#556]
Hi,

I am still working on the hand tracking for android devices. I don't understand why my landmarks have values between [0.2 ; 0.8]. It's like the frameLayout is bigger than the screen size. Can you tell me where i can manage the camera display ? How to have on the screen displaying a range of landmark X values between 0 and 1 ?

![image](https://user-images.githubusercontent.com/60918250/77620474-babdab00-6f3a-11ea-8cda-eb5baebf7a0c.png)

**Comment by eknight7** [comment]
Hi @romaindebraize, please see [CameraXPreviewHelper](https://github.com/google/mediapipe/blob/3b6d3c40589968c8333b4a936fbad7a8bea6d7f6/mediapipe/java/com/google/mediapipe/components/CameraXPreviewHelper.java) for managing aspect ratio of input and display.

Please also see the methods we implement in each Android example's `MainActivity.java` for display, for example in [handtrackinggpu.setupPreviewDisplayView()](https://github.com/google/mediapipe/blob/ae6be10afe59a6a99d8a68007784706ac98720dd/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L162-L196).

Please note that we are actively working on updating camera APIs, see [#490](https://github.com/google/mediapipe/issues/490) and [#472](https://github.com/google/mediapipe/issues/472).
