### ISSUE TITLE
adding joint to handmodel 

### ISSUE THREAD

**Issue by chillcloud-dev** [google/mediapipe#557]
Hey Guys, 

I just was wondering if it is possible to adjust the hand model to detect more joints. Some Hand models use 22 Joints by including the palm position as well. This is not the case for mediapipe. 

Could you tell me what I need to adjust to add this one joint. Ideally, the joint order would be as following: 

    1.Wrist, 
    2.Palm,  # not present in mediapipe right now  
    3.thumb_base, 
    4.thumb_first_joint, 
    5.thumb_second_joint,
    6.thumb_tip, 
    7.index_base,
    8.index_first_joint, 
    9.index_second_joint, 
    10.index_tip, 
    11.middle_base, 
    12.middle_first_joint, 
    13.middle_second_joint, 
    14.middle_tip, 
    15.ring_base, 
    16.ring_first_joint, 
    17.ring_second_joint, 
    18.ring_tip, 
    19.pinky_base, 
    20.pinky_first_joint, 
    21.pinky_second_joint, 
    22.pinky_tip.

Thanks guys. This adjustment would save me a lot of headache !

**Comment by fanzhanggoogle** [comment]
Hi, it's not possible for us to add this directly to our training data since it need re-annotation of all the dataset. But you could definitely use some heuristic to get the **palm** landmark you want, e.g. by averaging wrist and middle_base.
Thanks.
