### ISSUE TITLE
Can I debug mediapipe with clion? 

### ISSUE THREAD

**Issue by galis** [google/mediapipe#560]

**Comment by jiqimaogou** [comment]
mediapipe does not use cmake as the build system, so you can not build in clion, but you can use clion remote debug attach to the program to debug.

**Comment by developer-mayuan** [comment]
I think we can do this at least on Ubuntu machine.

**Comment by matanster** [comment]
What IDE would you recommend where some benefits of static analysis of the cpp code is enabled then?
