### ISSUE TITLE
Extracting hand rectangle crop coordinates in Multi-hand tracking IOS

### ISSUE THREAD

**Issue by 7AM7** [google/mediapipe#561]
I'm trying to crop the hand rectangle by modify the mutli hand detection gpu example app. I can see that the detections are outputted as Normalised Rects in the second last node ("DetectionsToRectsCalculator") from here:
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/hand_detection_gpu.pbtxt
What would be the correct way to get the coordinates for those normalised rects, so that they can be used in the ViewController file?
And is normalised rects is the right choice or there is any bounding box option ?

**Comment by 7AM7** [comment]
I think it's work with this way:
In `mediapipe/examples/ios/multihandtrackinggpu/BUILD` change
```
    deps = [
        "//mediapipe/objc:mediapipe_framework_ios",
        "//mediapipe/objc:mediapipe_input_sources_ios",
        "//mediapipe/objc:mediapipe_layer_renderer",
    ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            "//mediapipe/graphs/hand_tracking:multi_hand_mobile_calculators",
            "//mediapipe/framework/formats:landmark_cc_proto",
        ],
    }),
```
with 
```
    deps = [
        "//mediapipe/objc:mediapipe_framework_ios",
        "//mediapipe/objc:mediapipe_input_sources_ios",
        "//mediapipe/objc:mediapipe_layer_renderer",
    ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            "//mediapipe/graphs/hand_tracking:multi_hand_mobile_calculators",
            "//mediapipe/framework/formats:landmark_cc_proto",
             "//mediapipe/framework/formats:rect_cc_proto"
        ],
    }),
```
in `ViewController.mm `add after: 
`#include "mediapipe/framework/formats/landmark.pb.h"`
this:
```
#include "mediapipe/framework/formats/rect.pb.h"
static const char* kRectOutputStream = "multi_hand_rects_from_landmarks";
```
Also after 
```[newGraph addFrameOutputStream:kLandmarksOutputStream outputPacketType:MPPPacketTypeRaw];```
add:
`[newGraph addFrameOutputStream:kRectOutputStream outputPacketType:MPPPacketTypeRaw];`

Then replace this:

```
- (void)mediapipeGraph:(MPPGraph*)graph
     didOutputPacket:(const ::mediapipe::Packet&)packet
          fromStream:(const std::string&)streamName {
  if (streamName == kLandmarksOutputStream) {
    if (packet.IsEmpty()) {
      NSLog(@"[TS:%lld] No hand landmarks", packet.Timestamp().Value());
      return;
    }
    const auto& multi_hand_landmarks = packet.Get<std::vector<::mediapipe::NormalizedLandmarkList>>();
    NSLog(@"[TS:%lld] Number of hand instances with landmarks: %lu", packet.Timestamp().Value(),
          multi_hand_landmarks.size());
    for (int hand_index = 0; hand_index < multi_hand_landmarks.size(); ++hand_index) {
      const auto& landmarks = multi_hand_landmarks[hand_index];
      NSLog(@"\tNumber of landmarks for hand[%d]: %d", hand_index, landmarks.landmark_size());
      for (int i = 0; i < landmarks.landmark_size(); ++i) {
        NSLog(@"\t\tLandmark[%d]: (%f, %f, %f)", i, landmarks.landmark(i).x(),
              landmarks.landmark(i).y(), landmarks.landmark(i).z());
      }
    }
  }
}
```

with this:
```
- (void)mediapipeGraph:(MPPGraph*)graph
     didOutputPacket:(const ::mediapipe::Packet&)packet
          fromStream:(const std::string&)streamName
{
  if (streamName == kLandmarksOutputStream)
  {
        if (packet.IsEmpty())
        {
          NSLog(@"[TS:%lld] No hand landmarks", packet.Timestamp().Value());
          return;
        }
        const auto& multi_hand_landmarks = packet.Get<std::vector<::mediapipe::NormalizedLandmarkList>>();

        NSLog(@"[TS:%lld] Number of hand instances with landmarks: %lu", packet.Timestamp().Value(),
          multi_hand_landmarks.size());
        for (int hand_index = 0; hand_index < multi_hand_landmarks.size(); ++hand_index)
        {
          const auto& landmarks = multi_hand_landmarks[hand_index];

          NSLog(@"\tNumber of landmarks for hand[%d]: %d", hand_index, landmarks.landmark_size());
          for (int i = 0; i < landmarks.landmark_size(); ++i)
          {
            NSLog(@"\t\tLandmark[%d]: (%f, %f, %f)", i, landmarks.landmark(i).x(),
                  landmarks.landmark(i).y(), landmarks.landmark(i).z());
          }
        }
    }
    if (streamName == kRectOutputStream)
    {
          if (packet.IsEmpty())
          {
            NSLog(@"[TS:%lld] No hand rect.", packet.Timestamp().Value());
            return;
          }
        const auto& multi_hand_rects = packet.Get<std::vector<::mediapipe::NormalizedRect>>();
        NSLog(@"[TS:%lld] Number of hand instances with rects: %lu", packet.Timestamp().Value(),
          multi_hand_rects.size());
        
        for (int hand_index = 0; hand_index < multi_hand_rects.size(); ++hand_index)
        {
          const auto& rect = multi_hand_rects[hand_index];
          NSLog(@"\tNumber of rect for hand[%d]:, x_center: %f, y_center: %f, height: %f, width: %f",
                hand_index, rect.x_center(), rect.y_center(),
                rect.height(), rect.width());
        }
    }
}
```

Here is my Log output:
`Number of rect for hand[1]:, x_center: 0.384879, y_center: 0.642253, height: 0.660451, width: 1.174136`

Please, correct me if I am wrong in any part :)

**Comment by eknight7** [comment]
The multi-hand tracking example's [ViewController.mm#L168-188] https://github.com/google/mediapipe/blob/master/mediapipe/examples/ios/multihandtrackinggpu/ViewController.mm#L168-L188 already show how to get the landmarks.

**Comment by eknight7** [comment]
> What would be the correct way to get the coordinates for those normalised rects, so that they can be used in the ViewController file?

What you are doing seems correct.

> And is `NormalizedRect` is the right choice or there is any bounding box option?

It's correct because as shown in the graph, that is what is outputted by the detection and the landmark subgraphs. Note that if you were doing it for the single-hand case, you would have to check the boolean outputted by the hand-landmark subgraph to confirm that the hand is indeed present in the rect.

**Comment by dgrnd4** [comment]
@eknight7 hi, there is a way to get coordinates of the rectangle not normalized?
 Because with these function:

**for (int hand_index = 0; hand_index < multi_hand_rects_from_landmarks.size(); ++hand_index){
          const auto& rect = multi_hand_rects_from_landmarks[hand_index];
          LOG(INFO) << "hand_index:"<< hand_index << "-- x_center" << rect.x_center() << "-- y_center" <<  rect.y_center() << "-- height" << rect.height() << "-- width" <<  rect.width();
        }**
we obtain normalized coordinates.

Many thanks for the help!!
