### ISSUE TITLE
Auto Flip not working Desktop WSL 

### ISSUE THREAD

**Issue by Liuqianyik** [google/mediapipe#563]
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/autoflip:run_autoflip

INFO: Writing tracer profile to '/root/.cache/bazel/_bazel_root/14fe9c30d99db7d79d243c0ceda4896c/command.profile.gz'
INFO: Analyzed target //mediapipe/examples/desktop/autoflip:run_autoflip (1 packages loaded, 41 targets configured).
INFO: Found 1 target...
ERROR: /home/qianyiiii/mediapipe/mediapipe/examples/desktop/autoflip/BUILD:37:1: Linking of rule '//mediapipe/examples/desktop/autoflip:run_autoflip' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/autoflip/run_autoflip-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/scale_image_calculator/scale_image_calculator.o:scale_image_calculator.cc:function cv::Mat::~Mat(): error: undefined reference to 'cv::Mat::deallocate()'
bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/scale_image_calculator/scale_image_calculator.o:scale_image_calculator.cc:function cv::Mat::~Mat(): error: undefined reference to 'cv::fastFree(void*)'
bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/scale_image_calculator/scale_image_calculator.o:scale_image_calculator.cc:function mediapipe::ScaleImageCalculator::Process(mediapipe::CalculatorContext*): error: undefined reference to 'cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)'
bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/scale_image_calculator/scale_image_calculator.o:scale_image_calculator.cc:function mediapipe::ScaleImageCalculator::Process(mediapipe::CalculatorContext*): error: undefined reference to 'cv::fastFree(void*)'
...
(remaining 62 argument(s) skipped)

 error: undefined reference to 'cv::VideoWriter::VideoWriter(cv::String const&, int, double, cv::Size_<int>, bool)'
bazel-out/k8-opt/bin/mediapipe/calculators/video/_objs/opencv_video_encoder_calculator/opencv_video_encoder_calculator.o:opencv_video_encoder_calculator.cc:function mediapipe::OpenCvVideoEncoderCalculator::Close(mediapipe::CalculatorContext*): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
bazel-out/k8-opt/bin/mediapipe/calculators/video/_objs/opencv_video_encoder_calculator/opencv_video_encoder_calculator.o:opencv_video_encoder_calculator.cc:function mediapipe::OpenCvVideoEncoderCalculator::Open(mediapipe::CalculatorContext*): error: undefined reference to 'cv::VideoWriter::fourcc(char, char, char, char)'
bazel-out/k8-opt/bin/mediapipe/framework/formats/_objs/image_frame_opencv/image_frame_opencv.o:image_frame_opencv.cc:function mediapipe::formats::MatView(mediapipe::ImageFrame const*): error: undefined reference to 'cv::Mat::Mat(int, int const*, int, void*, unsigned long const*)'
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/autoflip:run_autoflip failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 14.439s, Critical Path: 12.25s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by jiuqiant** [comment]
The error is MediaPipe didn't find OpenCV library. Could you report how you install OpenCV on WSL?

**Comment by jiuqiant** [comment]
See https://github.com/google/mediapipe/issues/562#issuecomment-606203557 if you use the setup_opencv.sh

**Comment by Liuqianyik** [comment]
> 如果使用setup_opencv.sh，请参见[＃562（注释）。](https://github.com/google/mediapipe/issues/562#issuecomment-606203557)

Sorry, I found that my problem is the configuration problem of opencv, which was solved yesterday. Thank you very much for your reply

**Comment by jiuqiant** [comment]
Sure, no problem!
