### ISSUE TITLE
GPU Models for Samsung S20 (Mali-G77 MP11 GPU) are not working.

### ISSUE THREAD

**Issue by krullgit** [google/mediapipe#564]
Dear mediapipe team, 
I tried to install GPU Models (e.g. object detection 3d) by console but also through Android Studio and the app shows just a black screen on the S20. The CPU version of object detection is running though. 

I think this issue is related to the 0.6.5 [release](https://github.com/google/mediapipe/issues/104#issuecomment-557644049) but I guess the new S20 is not covered yet by that one?

The single WARNING I get while building is:
`WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
`
And the Error same to the issue I linked above:
`2020-03-30 11:27:02.777 6046-15561/? E/Camera3-OutputStream: getBufferLockedCommon: Stream 0: Can't dequeue next output buffer: Broken pipe (-32)`

Thank you and Best regards,
Matthes

**Comment by jiuqiant** [comment]
Can you checkout https://github.com/google/mediapipe/releases/tag/v0.7.0 and give another try?
We tested the object detection 3d app on S20 with v0.7.0 and it works ok. Let us know if it's not case from your side.

We will also investigate the issue with v0.7.1 to see if the latest changes break the app.

**Comment by krullgit** [comment]
I tried the v0.7.0 and v0.7.1 release, but both do not work. 
Camera permission is granted, yes. 
 
I really think it is an issue with the Mali-G77 MP11 GPU?
