### ISSUE TITLE
Mistypping in media_sequence.md

### ISSUE THREAD

**Issue by cheoljunlee** [google/mediapipe#566]
images = dataset_output=['images']
   labels = dataset_output=['labels']

should change to
   images = dataset_output['images']
   labels = dataset_output['labels']

**Comment by jiuqiant** [comment]
Good catch. Will release the typo fix in the coming release. Thanks!

**Comment by cheoljunlee** [comment]
Thanks.
And there is another one.

     images_, labels_ = sess.run(images, labels)
 to 
     images_, labels_ = sess.run([images, labels])

**Comment by jiuqiant** [comment]
Thanks. Will do.

**Comment by jiuqiant** [comment]
The documentation fixes are in https://github.com/google/mediapipe/commit/a3d36eee32999290c1461d469dc33cf63ccdf03a. Thanks!
