### ISSUE TITLE
Source code for "location_data"?

### ISSUE THREAD

**Issue by PetterPet01** [google/mediapipe#567]
I'm currently looking at Mediapipe's c++ source code for hand detection to understand how it works. Apparently, the object "Location" has a property called "location_data". 

Within' that property there're some crucial child properties and functions such as: "mutable_bounding_box", "relative_bounding_box", "mutable_relative_keypoints", "add_relative_keypoints",... that I want to look at.

But unfortunately, there's only one file with the name of "location_data.proto" and it doesn't have any significant code to make the whole LocationData object. 

So I'm asking where the supposed source code for the LocationData object is and the download link for the source code of it. Is it something like "location_data.cc"? Hoping to find an answer soon!

**Comment by eknight7** [comment]
[LocationData proto](https://github.com/google/mediapipe/blob/d68f5e416903e3d756ebe07d08c4a3b911741a91/mediapipe/framework/formats/location_data.proto)
[location.h](https://github.com/google/mediapipe/blob/d68f5e416903e3d756ebe07d08c4a3b911741a91/mediapipe/framework/formats/location.h)
[location.cc](https://github.com/google/mediapipe/blob/d68f5e416903e3d756ebe07d08c4a3b911741a91/mediapipe/framework/formats/location.cc).

**Comment by PetterPet01** [comment]
> [LocationData proto](https://github.com/google/mediapipe/blob/d68f5e416903e3d756ebe07d08c4a3b911741a91/mediapipe/framework/formats/location_data.proto)
> [location.h](https://github.com/google/mediapipe/blob/d68f5e416903e3d756ebe07d08c4a3b911741a91/mediapipe/framework/formats/location.h)
> [location.cc](https://github.com/google/mediapipe/blob/d68f5e416903e3d756ebe07d08c4a3b911741a91/mediapipe/framework/formats/location.cc).

Thanks for the fast relply! But I can't see "mutable_relative_bounding_box" in any of those files. Do you know where it is?

**Comment by eknight7** [comment]
`mutable_relative_bounding_box` means that while populating a `Proto` object, you are trying to access a `mutable` address to which you can add information about that bounding box. `mutable_` before a `Proto` field means that you want to modify that field. 

`add_relative_keypoints` is for the repeated field `relative_keypoints` because `add_` as a prefix means to add another element to that repeated field.

Here is a tutorial about protobufs in C++ for further reference: https://developers.google.com/protocol-buffers/docs/cpptutorial.

**Comment by PetterPet01** [comment]
Another pretty off-issue question, the "relative_bounding_box" object has all its inital xmin = 1, ymin = 2, width = 3, height = 4 or does it need to calculate all those values? If so then how? I'm looking at non_max_suppression calculator.
![image](https://user-images.githubusercontent.com/62211291/77991767-e7186380-734e-11ea-949f-ee22be48fda4.png)

**Comment by eknight7** [comment]
When we define something in a proto, for example if you have a file named `bazinga.proto`
defined as follows:

```
message Bazinga {
     optional int foo = 1;
     optional float bar = 2;
}
```

The `1` in `optional int foo = 1` is not the value of `foo`, rather it is telling the proto that this is the first field of the object. Similarly, `2` in `optional float bar = 2` tells us that it is the second field in the `Bazinga` proto object. 

As stated in the [tutorial](https://developers.google.com/protocol-buffers/docs/cpptutorial):

> The " = 1", " = 2" markers on each element identify the unique "tag" that field uses in the binary encoding. 

So in answer to your question:

> Another pretty off-issue question, the "relative_bounding_box" object has all its inital xmin = 1, ymin = 2, width = 3, height = 4 or does it need to calculate all those values? If so then how?

the values `xmin=1`, `ymin=2`, `width=3`, `height=4` are not initial values, rather tell us the order of the definition of the proto `RelativeBoundingBox` fields.

A calculator or another piece of code using this proto object type will define a new object as
```
RelativeBoundingBox relative_bb;
relative_bb.set_xmin(/*Some x_min computed somewhere*/);
relative_bb.set_ymin(/*Some y_min computed somewhere*/);
relative_bb.set_width(/*Some width computed somewhere*/);
relative_bb.set_height(/*Some height computed somewhere*/);
```

How the values are calculated: It depends on where and what code is using the object.

**Comment by PetterPet01** [comment]
Sorry, my bad, the relative bounding box was calculated before in the tflite_tensors_to_detections_calculator. Thanks a lot for your active replies! Have a nice day :D
