### ISSUE TITLE
Landscape orientation on Android App.

### ISSUE THREAD

**Issue by tagy** [google/mediapipe#568]
I have built some of the demo android apps and they work correctly.

But they do have android:screenOrientation="portrait" in the manifest so so not support landscape orientation. 

I have also built an aar library and built a similar app myself without the orientation restriction in the manifest. But when I rotate the device the camera preview is distorted and rotated 90 degrees.

Can anyone point me in the right direction of how I could fix landscape mode? Thanks.

**Comment by eknight7** [comment]
Yes, all the Android example apps use `Portrait` mode.
To change the app to work in landscape mode, you will have to change the code for handling the preview to appropriately handle size when camera rotation changes in `CameraXPreviewHelper.java` and `MainActivity.java` of your app.

**Comment by mzwtjp** [comment]
I did something like this.
In my app code,

```
wm : WindowManager
converter: ExternalTextureConverter

rotation = WindowManager.getDefaultDisplay().getRotation()
converter.setRotation((360 - rotation) % 360)
```

Then in ExternalTextureRenderer.java

```
//ADD
  private int rotation = 0;
  public void setRotation(int rotation) {
    this.rotation = rotation;
  }
//ADD

  public void render(SurfaceTexture surfaceTexture) {
    GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT);

    GLES20.glActiveTexture(GLES20.GL_TEXTURE0);
    ShaderUtil.checkGlError("glActiveTexture");
    surfaceTexture.updateTexImage(); // This implicitly binds the texture.
    surfaceTexture.getTransformMatrix(textureTransformMatrix);
//ADD
    switch (rotation) {
      case 0:
        break;
      case 90:
        Matrix.rotateM(textureTransformMatrix, 0, 90, 0, 0, 1);
        Matrix.translateM(textureTransformMatrix, 0, 0, -1, 0);
        break;
      case 180:
        Matrix.rotateM(textureTransformMatrix, 0, 180, 0, 0, 1);
        Matrix.translateM(textureTransformMatrix, 0, -1, -1, 0);
        break;
      case 270:
        Matrix.rotateM(textureTransformMatrix, 0, 270, 0, 0, 1);
        Matrix.translateM(textureTransformMatrix, 0, -1, 0, 0);
        break;
      default:
        //unknown
    }
//ADD
```

**Comment by yeon1216** [comment]
@mzwtjp thanks

**Comment by Christy-V** [comment]
I am facing the same issue, what should i do in android studio?

**Comment by vinayak19th** [comment]
I found the fix to this. It requires 3 changes for the input of mediapipe to be handled:
1. Modify the [CameraXPreviewHelper.java](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/CameraXPreviewHelper.java) 
In line 222:
```diff
-     Size rotatedSize =
-        new Size(/* width= */ targetSize.getHeight(), /* height= */ targetSize.getWidth()); 
+        Size rotatedSize = targetSize;
```

2. Modify the [ExternalTextureRenderer.java](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/glutil/ExternalTextureRenderer.java)
In line 69
```diff
- private int rotation = Surface.ROTATION_0;
+ private int rotation = Surface.ROTATION_270;
```

3. Modify the AndroidManifest.xml for the Basic or any additional you create
Add the following to **Every Activity** in the manifest
```xml
android:screenOrientation="landscape"
```
