### ISSUE TITLE
Crop hand for each frame multi hand tracking IOS

### ISSUE THREAD

**Issue by 7AM7** [google/mediapipe#569]
Hello there,
I need to save multi-hand rects/bounding box for each frame in IOS storage.
Could you please help me ?

**Comment by eknight7** [comment]
Can you please clarify how this is different from https://github.com/google/mediapipe/issues/561 ?

**Comment by 7AM7** [comment]
Simply I got the point but I cannot get the cropped image ad save it. How I can get each fame then cop it with rects point ?

**Comment by eknight7** [comment]
You can use the [ImageCroppingCalculator](https://github.com/google/mediapipe/blob/3b6d3c40589968c8333b4a936fbad7a8bea6d7f6/mediapipe/calculators/image/image_cropping_calculator.cc) to crop the image, add a `PacketCallback` to get the packet containing the cropped image and save the cropped image as a file.

**Comment by 7AM7** [comment]
Thank you for your response, But, Could you please give me an example of how to use ImageCroppingCalculator ?

**Comment by eknight7** [comment]
The hand tracking graph has an example node config for using this calculator: https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/graphs/hand_tracking/subgraphs/hand_landmark_gpu.pbtxt#L11-L22, so do some other graphs, see [this](https://github.com/google/mediapipe/search?q=ImageCroppingCalculator&unscoped_q=ImageCroppingCalculator).

**Comment by 7AM7** [comment]
Okay I am trying with single hand now, I added this to `ViewController.mm`
`static const char* kCroppedImgOutputStream = "hand_image";`

and
`[newGraph addFrameOutputStream:kCroppedImgOutputStream outputPacketType:MPPPacketTypePixelBuffer];`

but the app crashed

**Comment by 7AM7** [comment]
Fixed

**Comment by xxiMiaxx** [comment]
how did u fix it

**Comment by 7AM7** [comment]
> how did u fix it

By return hand_image object after processed by ImageCopping and then working on hand_image only.
 ![image](https://user-images.githubusercontent.com/24973739/78133724-42198b80-741f-11ea-83c0-a3a068d15f20.png)
