### ISSUE TITLE
Why is "detection_spec" not used in this function? 

### ISSUE THREAD

**Issue by PetterPet01** [google/mediapipe#570]
![image](https://user-images.githubusercontent.com/62211291/78122632-3cc83b00-7437-11ea-9afa-b014e6b45d58.png)

Why is "detection_spec" not used? I'm using it for Hand Detection and the returned NormalizedRect is too small.

I think the "rect"'s x, y, width, height should be multiplied with the "detection_spec"'s image size? Maybe I'm wrong. Hope to see an answer soon!

https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/detections_to_rects_calculator.cc#L55

**Comment by fanzhanggoogle** [comment]
Great question. This is a bit refactoring for a future release of a better hand tracking model. Sorry if it causes confusion now.
