### ISSUE TITLE
Google Mediapipe HairSegmentation proto file missing

### ISSUE THREAD

**Issue by rahulsuxsena1** [google/mediapipe#572]
Hi,
I am using Android to compile Mediapipe's Hair segmentation App, but getting these two error

import com.google.mediapipe.proto.CalculatorProto.CalculatorGraphConfig;
import com.google.mediapipe.proto.GraphTemplateProto.CalculatorGraphTemplate;

As unable to find these files to import. Please Help!!

Thanks

**Comment by rahulsuxsena** [comment]
resolved this issue by myself. you can email me to know how if you also face this issue.
rahulsuxsena@gmail.com

Thanks!

**Comment by jiuqiant** [comment]
Sorry for the late response. If you solved the problem, please post your solution. Thanks.

Back to your original question, what do you mention by using **Android** to compile hair segmentation app? Do you mean Android Studio? I tested the Bazel command and it works ok.
```
$ bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/hairsegmentationgpu
...
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/hairsegmentationgpu:hairsegmentationgpu up-to-date:
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/hairsegmentationgpu/hairsegmentationgpu_deploy.jar
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/hairsegmentationgpu/hairsegmentationgpu_unsigned.apk
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/hairsegmentationgpu/hairsegmentationgpu.apk
INFO: Elapsed time: 147.466s, Critical Path: 116.92s
INFO: 1394 processes: 1276 linux-sandbox, 118 worker.
INFO: Build completed successfully, 1412 total actions
```

**Comment by rahulsuxsena** [comment]
just need to add code to import external lib in app.gradle will remove this issue.

Thanks

**Comment by jiuqiant** [comment]
Thanks for posting your solution!

**Comment by ndhuynh02** [comment]
> just need to add code to import external lib in app.gradle will remove this issue.
> 
> Thanks

Can you provide the external lib plz?
