### ISSUE TITLE
hello world gpu error desktop

### ISSUE THREAD

**Issue by duxijun** [google/mediapipe#577]
find /usr/ -name "libEGL.so"           
/usr/lib/x86_64-linux-gnu/libEGL.so
/usr/lib/x86_64-linux-gnu/mesa-egl/libEGL.so

glxinfo |grep -i  opengl
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce RTX 2080/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 430.14
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 430.14
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 430.14
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

log:
bazel run --copt -DMESA_EGL_NO_X11_HEADERS mediapipe/examples/desktop/hello_world:hello_world                                         
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/duxj/projects/mediapipe/mediapipe/examples/desktop/hello_world/BUILD:19:1: Linking of rule '//mediapipe/examples/desktop/hello_world:hello_world' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-fastbuild/bin/mediapipe/examples/desktop/hello_world/hello_world-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: error: cannot open /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libEGL.so: No such file or directory
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::EglThreadExitCallback(void*): error: undefined reference to 'eglGetDisplay'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::EglThreadExitCallback(void*): error: undefined reference to 'eglMakeCurrent'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::EglThreadExitCallback(void*): error: undefined reference to 'eglReleaseThread'
  zel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::CreateContextInternal(void*, int): error: undefined reference to 'eglChooseConfig'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::CreateContextInternal(void*, int): error: undefined reference to 'eglGetError'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::CreateContextInternal(void*, int): error: undefined reference to 'eglCreateContext'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::CreateContextInternal(void*, int): error: undefined reference to 'eglGetError'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::CreateContext(void*): error: undefined reference to 'eglGetDisplay'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::CreateContext(void*): error: undefined reference to 'eglGetError'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::CreateContext(void*): error: undefined reference to 'eglInitialize'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::CreateContext(void*): error: undefined reference to 'eglCreatePbufferSurface'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::CreateContext(void*): error: undefined reference to 'eglGetError'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::DestroyContext()::{lambda()#1}::operator()() const: error: undefined reference to 'eglReleaseThread'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::DestroyContext(): error: undefined reference to 'eglMakeCurrent'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::DestroyContext(): error: undefined reference to 'eglDestroySurface'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::DestroyContext(): error: undefined reference to 'eglDestroyContext'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::GetCurrentContextBinding(mediapipe::GlContext::ContextBinding*): error: undefined reference to 'eglGetCurrentDisplay'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::GetCurrentContextBinding(mediapipe::GlContext::ContextBinding*): error: undefined reference to 'eglGetCurrentSurface'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::GetCurrentContextBinding(mediapipe::GlContext::ContextBinding*): error: undefined reference to 'eglGetCurrentSurface'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::GetCurrentContextBinding(mediapipe::GlContext::ContextBinding*): error: undefined reference to 'eglGetCurrentContext'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::SetCurrentContextBinding(mediapipe::GlContext::ContextBinding const&): error: undefined reference to 'eglGetCurrentDisplay'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::SetCurrentContextBinding(mediapipe::GlContext::ContextBinding const&): error: undefined reference to 'eglGetDisplay'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::SetCurrentContextBinding(mediapipe::GlContext::ContextBinding const&): error: undefined reference to 'eglMakeCurrent'
bazel-out/k8-fastbuild/bin/mediapipe/gpu/_objs/gl_context/gl_context_egl.pic.o:gl_context_egl.cc:function mediapipe::GlContext::IsCurrent() const: error: undefined reference to 'eglGetCurrentContext'
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.563s, Critical Path: 0.45s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by Akash-Dasyam** [comment]
Can u try re installing OpenCV as mentioned in the option 1 of the Install "OpenCV and FFmpeg"  step? 
https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md

**Comment by duxijun** [comment]
> Can u try re installing OpenCV as mentioned in the option 1 of the Install "OpenCV and FFmpeg" step?
> https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md

libEGL.so was not found
relink libEGL.so
sudo ln -s /usr/lib/x86_64-linux-gnu/libEGL.so.1.1.0 /usr/lib/x86_64-linux-gnu/libEGL.so
