### ISSUE TITLE
About Frame Processing Rate Setting

### ISSUE THREAD

**Issue by momo1986** [google/mediapipe#578]
Hello,
I tried to use the class FrameProcessor to  handle video  corresponding issues.
What is the factor to influence the video code rate?
If the camera set the image pixel as high, will the FPS become smaller.
Is there method in FrameProcessor.java or in ExternalFrameTexture.java to set the video process speed? Or the video processor rate only depend on the input/output video size and DL model’s inference speed?
Thanks & Regards!
Mono

**Comment by eknight7** [comment]
Hi, can you share what graph or model you are referencing too? Perhaps we can explore the speed issues from the graph?

**Comment by momo1986** [comment]
Hello, @eknight7 .
My referenced graph is:
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile.pbtxt
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_detection_gpu.pbtxt
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_landmark.pbtxt
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_gpu.pbtxt

My strategy is add some computation geometry algorithm in data packet stream retrieval and refresh some judgement result in UI thread. Since this will cost some handle time, I am very interesting if there exists some speed-up tricks in Mediapipe.
