### ISSUE TITLE
I hope to be able to apply posenet-android in mediapipe.

### ISSUE THREAD

**Issue by meteorlin** [google/mediapipe#579]
Mediapipe is amazing!
I now want to integrate [Posenet-Android](https://github.com/tensorflow/examples/tree/master/lite/examples/posenet/android) and [Mediapipe-MultiHandTrackingMobileGPU](https://github.com/google/mediapipe/blob/master/mediapipe/docs/multi_hand_tracking_mobile_gpu.md), here is my current attempt:
I change the main graph and subgraph to merge posenet into mediapipe, and there are them:
the main graph
![main_graph](https://user-images.githubusercontent.com/49402403/78387934-bc5e3180-7612-11ea-87bd-f1de7a1424d1.png)
the subgraph
![subgraph](https://user-images.githubusercontent.com/49402403/78387976-cc761100-7612-11ea-994e-c0f7676080f3.png)
But unfortunately, after I run install the generated apk, the posenet model didn't work at all...

the main code I added in subgraph is here:
```
node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:input_video"
  output_stream: "IMAGE_GPU:transformed_input_video_posenet"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 257
      output_height: 257
      scale_mode: FIT
    }
  }
}

node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE_GPU:transformed_input_video_posenet"
  output_stream: "TENSORS_GPU:image_tensor_posenet"
}

node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS_GPU:image_tensor_posenet"
  output_stream: "TENSORS:posenet"
#  input_side_packet: "CUSTOM_OP_RESOLVER:opresolver"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
      model_path: "mediapipe/models/posenet_model.tflite"
      use_gpu: true
    }
  }
}

node {
  calculator: "TfLiteTensorsToLandmarksCalculator"
  input_stream: "TENSORS:posenet"
  output_stream: "NORM_LANDMARKS:posenet_landmarks"
  node_options: {
      [type.googleapis.com/mediapipe.TfLiteTensorsToLandmarksCalculatorOptions] {
      num_landmarks: 17
      input_image_width: 257
      input_image_height: 257
    }
  }
}
```
actually the last node is optional, because I can process the tensor data in Android by Java.(I don't know how to use C++, so I have no idea to create a calculator by myself )

So my questions are:
1. How should I modify the program to add posenet in mediapipe?
2. How can I gain TENSORS_GPU from graph node in Android?
3. What's more, how can I save the output of multihandtrackinggpu in json?

Thank you!

**Comment by 7AM7** [comment]
I hope this helps you:
https://github.com/google/mediapipe/issues/575#issuecomment-609509826

**Comment by fanzhanggoogle** [comment]
As far as I can tell from the [posenet model](https://source.corp.google.com/piper///depot/google3/research/aimatter/nnets/models/handdetector_hourglass_short_2019_03_25_v0/), it seems to have 4 outputs which doesn't reflect in your graph?
You can use [SplitCalculator](https://github.com/google/mediapipe/blob/024f7bf0f1e74149ea92b942cf168ccddf317073/mediapipe/graphs/hand_tracking/subgraphs/hand_landmark_gpu.pbtxt#L70) to get the specific output tensor. (Looks like the model also need a specific post-processing since the one of the output tensor has the name **offset**)
Did you manage to get posenet seperately to work with MediaPipe?  That might be a good start point to investigate.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
