### ISSUE TITLE
Error encountered during installation

### ISSUE THREAD

**Issue by ViosinDeng** [google/mediapipe#581]
I followed the instructions and tried to install and run mediapipe in Ubuntu. The previous work was very smooth. But there was an error when I finally ran Hello world.

```
bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
```

Error report:
```
viosin@Viosin-Laptop:~/mediapipe$ bazel run --define MEDIAPIPE_DISABLE_GPU=1     mediapipe/examples/desktop/hello_world:hello_world
INFO: Call stack for the definition of repository 'org_tensorflow' which is a http_archive (rule definition at /home/viosin/.cache/bazel/_bazel_viosin/7d642f36f799200596607c092b81016f/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/viosin/mediapipe/WORKSPACE:124:1
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz failed: class java.io.IOException Tried to reconnect at offset 9,944,151 but server didn't support it
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz, https://github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz] to /home/viosin/.cache/bazel/_bazel_viosin/7d642f36f799200596607c092b81016f/external/org_tensorflow/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz: Tried to reconnect at offset 9,944,151 but server didn't support it
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz, https://github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz] to /home/viosin/.cache/bazel/_bazel_viosin/7d642f36f799200596607c092b81016f/external/org_tensorflow/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz: Tried to reconnect at offset 9,944,151 but server didn't support it
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz, https://github.com/tensorflow/tensorflow/archive/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz] to /home/viosin/.cache/bazel/_bazel_viosin/7d642f36f799200596607c092b81016f/external/org_tensorflow/77e9ffb9b2bfb1a4f7056e62d84039626923e328.tar.gz: Tried to reconnect at offset 9,944,151 but server didn't support it
INFO: Elapsed time: 523.767s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```
I think this may be caused by the failure of downloading some files, so I tried to access one of the links, and the address couldn't be accessed as expected. At first, I thought it might be my own network reason, but I still couldn't access it after opening the agent. So I reported the issue.

**Comment by jiuqiant** [comment]
Can you do `bazel clean --expunge` and retry the build command? 

The downloading is taken care by the build tool Bazel and I feel sorry that MediaPipe doesn't have any control on it. Moreover, VPN is preferred if you are in mainland China. See https://github.com/google/mediapipe/issues/3 for more detail.

**Comment by ViosinDeng** [comment]
> Can you do `bazel clean --expunge` and retry the build command?
> 
> The downloading is taken care by the build tool Bazel and I feel sorry that MediaPipe doesn't have any control on it. Moreover, VPN is preferred if you are in mainland China. See #3 for more detail.

Well, I tried your method, but it didn't work.

But I do suspect that this may be a network error, so I tried all kinds of ways to set up the proxy, and the result was useless.

Finally, I suddenly remembered that bazel's download program seemed to be run by Java, and the Java virtual machine does not use any agents by default.

Unless... I set the JVM parameters manually. After checking the help documents of bazel, I found that the JVM parameters can be set through ` -- host_jvm_args'.

So I finally ran mediapipe successfully with such a string of code.
```
bazel --host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080" run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world 
```

Maybe this issue can help other Chinese developers.

Thank you for your help.

Oh, by the way, my English is not very good. So this text is generated by translation software. If you are offended, please forgive me.

**Comment by jiuqiant** [comment]
Thanks for posting your solution! It will definitely benefit the other developers!

**Comment by Emilycs09** [comment]
> > Can you do `bazel clean --expunge` and retry the build command?
> > The downloading is taken care by the build tool Bazel and I feel sorry that MediaPipe doesn't have any control on it. Moreover, VPN is preferred if you are in mainland China. See #3 for more detail.
> 
> Well, I tried your method, but it didn't work.
> 
> But I do suspect that this may be a network error, so I tried all kinds of ways to set up the proxy, and the result was useless.
> 
> Finally, I suddenly remembered that bazel's download program seemed to be run by Java, and the Java virtual machine does not use any agents by default.
> 
> Unless... I set the JVM parameters manually. After checking the help documents of bazel, I found that the JVM parameters can be set through ` -- host_jvm_args'.
> 
> So I finally ran mediapipe successfully with such a string of code.
> 
> ```
> bazel --host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080" run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world 
> ```
> 
> Maybe this issue can help other Chinese developers.
> 
> Thank you for your help.
> 
> Oh, by the way, my English is not very good. So this text is generated by translation software. If you are offended, please forgive me.

I tried the code you mentioned with the --host_jvm_args settings, but it still doesn't work. Error still occured about fetching repository 'org_tensorflow'

Did you just run the code and it works? Is there anything else I should do before running the code?

**Comment by ViosinDeng** [comment]
> > > Can you do `bazel clean --expunge` and retry the build command?
> > > The downloading is taken care by the build tool Bazel and I feel sorry that MediaPipe doesn't have any control on it. Moreover, VPN is preferred if you are in mainland China. See #3 for more detail.
> > 
> > 
> > Well, I tried your method, but it didn't work.
> > But I do suspect that this may be a network error, so I tried all kinds of ways to set up the proxy, and the result was useless.
> > Finally, I suddenly remembered that bazel's download program seemed to be run by Java, and the Java virtual machine does not use any agents by default.
> > Unless... I set the JVM parameters manually. After checking the help documents of bazel, I found that the JVM parameters can be set through ` -- host_jvm_args'.
> > So I finally ran mediapipe successfully with such a string of code.
> > ```
> > bazel --host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080" run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world 
> > ```
> > 
> > 
> > Maybe this issue can help other Chinese developers.
> > Thank you for your help.
> > Oh, by the way, my English is not very good. So this text is generated by translation software. If you are offended, please forgive me.
> 
> I tried the code you mentioned with the --host_jvm_args settings, but it still doesn't work. Error still occured about fetching repository 'org_tensorflow'
> 
> Did you just run the code and it works? Is there anything else I should do before running the code?

Hello, I'm glad to be able to help you.
Before using these JVM parameters, you need to set up a sock5 proxy server.
First, I set up a proxy server using v2ray locally, then I can use AAA.
Of course, you don't need v2ray to set up a proxy server. You can also use other software.
If you are a developer from China, I don't mind sharing my v2ray server information to you.

**Comment by Emilycs09** [comment]
> > > > Can you do `bazel clean --expunge` and retry the build command?
> > > > The downloading is taken care by the build tool Bazel and I feel sorry that MediaPipe doesn't have any control on it. Moreover, VPN is preferred if you are in mainland China. See #3 for more detail.
> > > 
> > > 
> > > Well, I tried your method, but it didn't work.
> > > But I do suspect that this may be a network error, so I tried all kinds of ways to set up the proxy, and the result was useless.
> > > Finally, I suddenly remembered that bazel's download program seemed to be run by Java, and the Java virtual machine does not use any agents by default.
> > > Unless... I set the JVM parameters manually. After checking the help documents of bazel, I found that the JVM parameters can be set through ` -- host_jvm_args'.
> > > So I finally ran mediapipe successfully with such a string of code.
> > > ```
> > > bazel --host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080" run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world 
> > > ```
> > > 
> > > 
> > > Maybe this issue can help other Chinese developers.
> > > Thank you for your help.
> > > Oh, by the way, my English is not very good. So this text is generated by translation software. If you are offended, please forgive me.
> > 
> > 
> > I tried the code you mentioned with the --host_jvm_args settings, but it still doesn't work. Error still occured about fetching repository 'org_tensorflow'
> > Did you just run the code and it works? Is there anything else I should do before running the code?
> 
> Hello, I'm glad to be able to help you.
> Before using these JVM parameters, you need to set up a sock5 proxy server.
> First, I set up a proxy server using v2ray locally, then I can use `--host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080"`.
> Of course, you don't need v2ray to set up a proxy server. You can also use other software.
> If you are a developer from China, I don't mind sharing my v2ray server information to you.

Thanks for your timely response! I do have no proxy, no wonder it doesn't work.
I'll try to set up a proxy and then try it again.
old iron 666

**Comment by dolt131943** [comment]
in macos 10.15.6, mediapipe commit-id: a7225b938a5aff536dcdc4d48d7125964480f413

must use two --host_jvm_args like this:

`bazel --host_jvm_args '-DsocksProxyHost=127.0.0.1' --host_jvm_args '-DsocksProxyPort=1080' <cmd>`

will take proxy effect.

combine in one --host_jvm_args will throw exception:

Can't connect to SOCKS proxy:127.0.0.1 -DsocksProxyPort=1080

hope this can help someone face same issue.

**Comment by mrlihellohorld** [comment]
> > > > Can you do `bazel clean --expunge` and retry the build command?
> > > > The downloading is taken care by the build tool Bazel and I feel sorry that MediaPipe doesn't have any control on it. Moreover, VPN is preferred if you are in mainland China. See #3 for more detail.
> > > 
> > > 
> > > Well, I tried your method, but it didn't work.
> > > But I do suspect that this may be a network error, so I tried all kinds of ways to set up the proxy, and the result was useless.
> > > Finally, I suddenly remembered that bazel's download program seemed to be run by Java, and the Java virtual machine does not use any agents by default.
> > > Unless... I set the JVM parameters manually. After checking the help documents of bazel, I found that the JVM parameters can be set through ` -- host_jvm_args'.
> > > So I finally ran mediapipe successfully with such a string of code.
> > > ```
> > > bazel --host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080" run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world 
> > > ```
> > > 
> > > 
> > > Maybe this issue can help other Chinese developers.
> > > Thank you for your help.
> > > Oh, by the way, my English is not very good. So this text is generated by translation software. If you are offended, please forgive me.
> > 
> > 
> > I tried the code you mentioned with the --host_jvm_args settings, but it still doesn't work. Error still occured about fetching repository 'org_tensorflow'
> > Did you just run the code and it works? Is there anything else I should do before running the code?
> 
> Hello, I'm glad to be able to help you.
> Before using these JVM parameters, you need to set up a sock5 proxy server.
> First, I set up a proxy server using v2ray locally, then I can use `--host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080"`.
> Of course, you don't need v2ray to set up a proxy server. You can also use other software.
> If you are a developer from China, I don't mind sharing my v2ray server information to you.

Hi, could u share your v2ray server information to me? thanks

**Comment by MiniDay** [comment]
> > > > > Can you do `bazel clean --expunge` and retry the build command?
> > > > > The downloading is taken care by the build tool Bazel and I feel sorry that MediaPipe doesn't have any control on it. Moreover, VPN is preferred if you are in mainland China. See #3 for more detail.
> > > > 
> > > > 
> > > > Well, I tried your method, but it didn't work.
> > > > But I do suspect that this may be a network error, so I tried all kinds of ways to set up the proxy, and the result was useless.
> > > > Finally, I suddenly remembered that bazel's download program seemed to be run by Java, and the Java virtual machine does not use any agents by default.
> > > > Unless... I set the JVM parameters manually. After checking the help documents of bazel, I found that the JVM parameters can be set through ` -- host_jvm_args'.
> > > > So I finally ran mediapipe successfully with such a string of code.
> > > > ```
> > > > bazel --host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080" run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world 
> > > > ```
> > > > 
> > > > 
> > > > Maybe this issue can help other Chinese developers.
> > > > Thank you for your help.
> > > > Oh, by the way, my English is not very good. So this text is generated by translation software. If you are offended, please forgive me.
> > > 
> > > 
> > > I tried the code you mentioned with the --host_jvm_args settings, but it still doesn't work. Error still occured about fetching repository 'org_tensorflow'
> > > Did you just run the code and it works? Is there anything else I should do before running the code?
> > 
> > 
> > Hello, I'm glad to be able to help you.
> > Before using these JVM parameters, you need to set up a sock5 proxy server.
> > First, I set up a proxy server using v2ray locally, then I can use `--host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080"`.
> > Of course, you don't need v2ray to set up a proxy server. You can also use other software.
> > If you are a developer from China, I don't mind sharing my v2ray server information to you.
> 
> Hi, could u share your v2ray server information to me? thanks

I'm afraid not.

You should also know that it is illegal in China.

So, although I'd like to help you, it can't. Otherwise, I might suffer a disaster.

But I can give you some tutorials. If you follow this document, it may only take a few hours (and a little money to buy the server) to have your own private server.

[https://tlanyan.me/v2ray-tutorial/](https://tlanyan.me/v2ray-tutorial/)

**Comment by mrlihellohorld** [comment]
> > > > > > Can you do `bazel clean --expunge` and retry the build command?
> > > > > > The downloading is taken care by the build tool Bazel and I feel sorry that MediaPipe doesn't have any control on it. Moreover, VPN is preferred if you are in mainland China. See #3 for more detail.
> > > > > 
> > > > > 
> > > > > Well, I tried your method, but it didn't work.
> > > > > But I do suspect that this may be a network error, so I tried all kinds of ways to set up the proxy, and the result was useless.
> > > > > Finally, I suddenly remembered that bazel's download program seemed to be run by Java, and the Java virtual machine does not use any agents by default.
> > > > > Unless... I set the JVM parameters manually. After checking the help documents of bazel, I found that the JVM parameters can be set through ` -- host_jvm_args'.
> > > > > So I finally ran mediapipe successfully with such a string of code.
> > > > > ```
> > > > > bazel --host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080" run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world 
> > > > > ```
> > > > > 
> > > > > 
> > > > > Maybe this issue can help other Chinese developers.
> > > > > Thank you for your help.
> > > > > Oh, by the way, my English is not very good. So this text is generated by translation software. If you are offended, please forgive me.
> > > > 
> > > > 
> > > > I tried the code you mentioned with the --host_jvm_args settings, but it still doesn't work. Error still occured about fetching repository 'org_tensorflow'
> > > > Did you just run the code and it works? Is there anything else I should do before running the code?
> > > 
> > > 
> > > Hello, I'm glad to be able to help you.
> > > Before using these JVM parameters, you need to set up a sock5 proxy server.
> > > First, I set up a proxy server using v2ray locally, then I can use `--host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080"`.
> > > Of course, you don't need v2ray to set up a proxy server. You can also use other software.
> > > If you are a developer from China, I don't mind sharing my v2ray server information to you.
> > 
> > 
> > Hi, could u share your v2ray server information to me? thanks
> 
> I'm afraid not.
> 
> You should also know that it is illegal in China.
> 
> So, although I'd like to help you, it can't. Otherwise, I might suffer a disaster.
> 
> But I can give you some tutorials. If you follow this document, it may only take a few hours (and a little money to buy the server) to have your own private server.
> 
> https://tlanyan.me/v2ray-tutorial/

thanks u very much, I'll try to set up a proxy and then try it again. May I ask you another question?  I built the Docker environment of mediapipe, and when i run the commond:
   bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/autoflip:run_autoflip
   i got a error: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz] to /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz: Tried to reconnect at offset 12,948,552 but server didn't support it
   So I manually downloaded this file（0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz） and copied it to this directory "/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/", When I re-execute the command above，The file（0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz） will be automatically redownloaded. How can I modify the source code to stop the automatic download? thanks a lot
https://github.com/google/mediapipe/blob/39309bedba255aee2a4f31b29b65609857698ada/WORKSPACE#L368

**Comment by MiniDay** [comment]
> > > > > > > Can you do `bazel clean --expunge` and retry the build command?
> > > > > > > The downloading is taken care by the build tool Bazel and I feel sorry that MediaPipe doesn't have any control on it. Moreover, VPN is preferred if you are in mainland China. See #3 for more detail.
> > > > > > 
> > > > > > 
> > > > > > Well, I tried your method, but it didn't work.
> > > > > > But I do suspect that this may be a network error, so I tried all kinds of ways to set up the proxy, and the result was useless.
> > > > > > Finally, I suddenly remembered that bazel's download program seemed to be run by Java, and the Java virtual machine does not use any agents by default.
> > > > > > Unless... I set the JVM parameters manually. After checking the help documents of bazel, I found that the JVM parameters can be set through ` -- host_jvm_args'.
> > > > > > So I finally ran mediapipe successfully with such a string of code.
> > > > > > ```
> > > > > > bazel --host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080" run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world 
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Maybe this issue can help other Chinese developers.
> > > > > > Thank you for your help.
> > > > > > Oh, by the way, my English is not very good. So this text is generated by translation software. If you are offended, please forgive me.
> > > > > 
> > > > > 
> > > > > I tried the code you mentioned with the --host_jvm_args settings, but it still doesn't work. Error still occured about fetching repository 'org_tensorflow'
> > > > > Did you just run the code and it works? Is there anything else I should do before running the code?
> > > > 
> > > > 
> > > > Hello, I'm glad to be able to help you.
> > > > Before using these JVM parameters, you need to set up a sock5 proxy server.
> > > > First, I set up a proxy server using v2ray locally, then I can use `--host_jvm_args "-DsocksProxyHost=192.168.1.100 -DsocksProxyPort=1080"`.
> > > > Of course, you don't need v2ray to set up a proxy server. You can also use other software.
> > > > If you are a developer from China, I don't mind sharing my v2ray server information to you.
> > > 
> > > 
> > > Hi, could u share your v2ray server information to me? thanks
> > 
> > 
> > I'm afraid not.
> > You should also know that it is illegal in China.
> > So, although I'd like to help you, it can't. Otherwise, I might suffer a disaster.
> > But I can give you some tutorials. If you follow this document, it may only take a few hours (and a little money to buy the server) to have your own private server.
> > https://tlanyan.me/v2ray-tutorial/
> 
> thanks u very much, I'll try to set up a proxy and then try it again. May I ask you another question? I built the Docker environment of mediapipe, and when i run the commond:
> bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/autoflip:run_autoflip
> i got a error: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz] to /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz: Tried to reconnect at offset 12,948,552 but server didn't support it
> So I manually downloaded this file（0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz） and copied it to this directory "/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/", When I re-execute the command above，The file（0eadbb13cef1226b1bae17c941f7870734d97f8a.tar.gz） will be automatically redownloaded. How can I modify the source code to stop the automatic download? thanks a lot
> https://github.com/google/mediapipe/blob/39309bedba255aee2a4f31b29b65609857698ada/WORKSPACE#L368

Unfortunately, I don't know how to do it. But I know some other information. I don't know if it will help you.
Mediapipe is built with bazel, so the code you want should be in the bazel project.

**Comment by mrlihellohorld** [comment]
Hi, thank u for your help. 
I set up a proxy server and can access Google from Windows, but how can I access the extranet from unbounded Ubuntu (the MediaPipe project is on the remote Ubuntu server),I try to run the command:  bazel - host_jvm_args - DsocksProxyHost = proxy server IP  - DsocksProxyPort = "port" the run - define MEDIAPIPE_DISABLE_GPU = 1 mediapipe/examples/desktop/hello_world: hello_world. but i got a error:Can't connect to SOCKS proxy:connect timed out. 
 I took the liberty of sending you an email with the details. looking forward to your replay.

**Comment by MiniDay** [comment]
> Hi, thank u for your help.
> I set up a proxy server and can access Google from Windows, but how can I access the extranet from unbounded Ubuntu (the MediaPipe project is on the remote Ubuntu server),I try to run the command: bazel - host_jvm_args - DsocksProxyHost = proxy server IP - DsocksProxyPort = "port" the run - define MEDIAPIPE_DISABLE_GPU = 1 mediapipe/examples/desktop/hello_world: hello_world. but i got a error:Can't connect to SOCKS proxy:connect timed out.
> I took the liberty of sending you an email with the details. looking forward to your replay.

I'm glad I can help you.

You need to do 4 steps:

1. Use the v2ray client with GUI to establish the connection and ensure the normal proxy.  Recommend for Windows: [https://github.com/2dust/v2rayNG](https://github.com/2dust/v2rayNG)
(if you can manually write the v2ray configuration information, you don't have to worry about it.)

2. Download v2ray from your Ubuntu server and unzip it.[https://github.com/v2fly/v2ray-core](https://github.com/v2fly/v2ray-core)

3. Put config.json Copy it to the Ubuntu server and put it in the v2ray directory. (it should be in your GUI client folder directory, about 10KB)

4. `./v2ray ./config.json`
(Or running it in the background?)

Then, you can use the proxy!

**Comment by mrlihellohorld** [comment]
> > Hi, thank u for your help.
> > I set up a proxy server and can access Google from Windows, but how can I access the extranet from unbounded Ubuntu (the MediaPipe project is on the remote Ubuntu server),I try to run the command: bazel - host_jvm_args - DsocksProxyHost = proxy server IP - DsocksProxyPort = "port" the run - define MEDIAPIPE_DISABLE_GPU = 1 mediapipe/examples/desktop/hello_world: hello_world. but i got a error:Can't connect to SOCKS proxy:connect timed out.
> > I took the liberty of sending you an email with the details. looking forward to your replay.
> 
> I'm glad I can help you.
> 
> You need to do 4 steps:
> 
> 1. Use the v2ray client with GUI to establish the connection and ensure the normal proxy.  Recommend for Windows: https://github.com/2dust/v2rayNG
>    (if you can manually write the v2ray configuration information, you don't have to worry about it.)
> 2. Download v2ray from your Ubuntu server and unzip it.https://github.com/v2fly/v2ray-core
> 3. Put config.json Copy it to the Ubuntu server and put it in the v2ray directory. (it should be in your GUI client folder directory, about 10KB)
> 4. `./v2ray ./config.json`
>    (Or running it in the background?)
> 
> Then, you can use the proxy!

thanks u very much！！I successfully implemented the use of proxies in Ubuntu through the method you mentioned. but i used a Docker image to install  mediapipe, and i also can't use proxies in Docker. So my final approach is to manually download the source file, set up a file sharing server, and change the URLs in the workspace to implement it. Thanks again for your help

**Comment by 11676670** [comment]
if you network blocked by the Great Firewall. you can change your repositories in WORKSPACE file like this.
repositories =
    [
        "https://maven.aliyun.com/repository/google",
        "https://maven.aliyun.com/repository/central",
        "https://maven.aliyun.com/repository/public",
],
Good luck.
