### ISSUE TITLE
implement arcore with objectron

### ISSUE THREAD

**Issue by cadrogui** [google/mediapipe#583]
is there a way to implement google arcore with the objectron sneakers to use the x,y,z coordiates in arcore anchor?, basically we need to put arbitrary 3d model in place of the rendered sneaker box

**Comment by jiuqiant** [comment]
You can build the mediapipe objectron aar and use the aar with arcore in Android Studio: https://github.com/google/mediapipe/issues/313#issuecomment-564156077. However, there is a gl context related issue to be soloved: https://github.com/google/mediapipe/issues/321

**Comment by nakshathru** [comment]
Any update on the GL context issue ?? 
Facing the same issue while integrating mediapipe with sceneform
Can we expect an GLSurfaceview implementation of mediapipe instead of surfaceview in android ??

**Comment by alter-sachin** [comment]
bump

**Comment by mgyong** [comment]
@alter-sachin update to latest version of MP and see if this is an issue still

**Comment by abiemann** [comment]
> You can build the mediapipe objectron aar and use the aar with arcore in Android Studio: [#313 (comment)](https://github.com/google/mediapipe/issues/313#issuecomment-564156077). However, there is a gl context related issue to be soloved: #321

do you have a sample project to illustrate this setup? I've looked here https://github.com/jiuqiant?tab=repositories but found nothing that uses arCore.
For now, I'm copying frames from the ArFragment and am trying to feed those to the MediaPipe, but I don't see anything useful in the FrameProcessor to set a bitmap.
