### ISSUE TITLE
certain objects in a video

### ISSUE THREAD

**Issue by teafff** [google/mediapipe#588]
If I want to identify some custom objects in the video, can you give me some suggestions for specific steps？

**Comment by eknight7** [comment]
Hi @teafff, did you have a chance to try the [object detection example](https://mediapipe.readthedocs.io/en/latest/object_detection_mobile_gpu.html) app?

**Comment by teafff** [comment]
> Hi @teafff, did you have a chance to try the [object detection example](https://mediapipe.readthedocs.io/en/latest/object_detection_mobile_gpu.html) app?

yes. I successed to  run objecte detection in desktop.I want to know if i use some model to replace the model in example，whether other objects can be detected？

**Comment by eknight7** [comment]
If your model is able to detect those other objects, it should work, please try it out and share!

**Comment by teafff** [comment]
> If your model is able to detect those other objects, it should work, please try it out and share!

Ok, i will try it!
Thanks
