### ISSUE TITLE
How can I debug the c++ source code in Android Studio

### ISSUE THREAD

**Issue by cjf445144540** [google/mediapipe#589]
When I set a breakpoint in the c++ source code, and then debug the app, it does not stop in the breakpoint.
However I can successfully debug in the java code, and the app can stop when I set the breakpoint in java code.
![image](https://user-images.githubusercontent.com/40584804/78748445-a8158e00-799e-11ea-84a3-42a42acb0121.png)
I have check Enable Native Debugging in my app Configurations. It seems does not work.
I am looking forward to your reply. thank you !

**Comment by eknight7** [comment]
Try `-c dbg` instead of `-c opt`?

**Comment by cjf445144540** [comment]
> Try `-c dbg` instead of `-c opt`?

does not work :(

**Comment by cjf445144540** [comment]
any else idea ?

**Comment by cjf445144540** [comment]
By the way, I working on macOS, It seems that there are some known bugs when you use bazel + android studio + macOS + native debug ?

**Comment by weinixuehao** [comment]
with -c dbg and -c opt output libmediapipe_jni.so size is same so can not hit breakpoint in c++?

**Comment by weinixuehao** [comment]
I use profile or debug apk function in android studio for tflite debug c++ code is ok! debug so is large than optimize so. but mediapipe is not why?

**Comment by chensisi0730** [comment]
> Try `-c dbg` instead of `-c opt`?
can work in java code ,but can not work in c++

**Comment by chensisi0730** [comment]
> I use profile or debug apk function in android studio for tflite debug c++ code is ok! debug so is large than optimize so. but mediapipe is not why?@cjf445144540

How did you do it？@weinixuehao

**Comment by weinixuehao** [comment]
@chensisi0730 
Please see #648

**Comment by weinixuehao** [comment]
https://github.com/bazelbuild/intellij/issues/295#issuecomment-653379409
This solution is not need to profile apk for debug.
