### ISSUE TITLE
bazel fails when building handtrackingcpu/gpu for desktop(ubuntu)

### ISSUE THREAD

**Issue by a798347923** [google/mediapipe#590]
OS: Ubuntu 18.04
Bazel version: 1.0.0
I can run the hello program normally,but bazel fails when building handtrackingcpu/gpu .

There are all message：
 bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11     mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu

INFO: Writing tracer profile to '/home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/command.profile.gz'
INFO: Call stack for the definition of repository 'eigen_archive' which is a tf_http_archive (rule definition at /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/third_party/repo.bzl:134:19):
 - /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/tensorflow/workspace.bzl:196:5
 - /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/tensorflow/workspace.bzl:77:5
 - /home/wx/mediapipe/WORKSPACE:146:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/gitlab.com/libeigen/eigen/-/archive/3fda850c46e5e589668a85d89299433e0686eec9/eigen-3fda850c46e5e589668a85d89299433e0686eec9.tar.gz failed: class java.io.IOException connect timed out
WARNING: Download from https://gitlab.com/libeigen/eigen/-/archive/3fda850c46e5e589668a85d89299433e0686eec9/eigen-3fda850c46e5e589668a85d89299433e0686eec9.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 406 Not Acceptable
ERROR: An error occurred during the fetch of repository 'eigen_archive':
   java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/gitlab.com/libeigen/eigen/-/archive/3fda850c46e5e589668a85d89299433e0686eec9/eigen-3fda850c46e5e589668a85d89299433e0686eec9.tar.gz, https://gitlab.com/libeigen/eigen/-/archive/3fda850c46e5e589668a85d89299433e0686eec9/eigen-3fda850c46e5e589668a85d89299433e0686eec9.tar.gz] to /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/eigen_archive/eigen-3fda850c46e5e589668a85d89299433e0686eec9.tar.gz: GET returned 406 Not Acceptable
INFO: Call stack for the definition of repository 'farmhash_archive' which is a tf_http_archive (rule definition at /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/third_party/repo.bzl:134:19):
 - /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/tensorflow/workspace.bzl:277:5
 - /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/tensorflow/workspace.bzl:77:5
 - /home/wx/mediapipe/WORKSPACE:146:1
INFO: Call stack for the definition of repository 'XNNPACK' which is a tf_http_archive (rule definition at /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/third_party/repo.bzl:134:19):
 - /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/tensorflow/workspace.bzl:145:5
 - /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/tensorflow/workspace.bzl:77:5
 - /home/wx/mediapipe/WORKSPACE:146:1
INFO: Call stack for the definition of repository 'gemmlowp' which is a tf_http_archive (rule definition at /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/third_party/repo.bzl:134:19):
 - /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/tensorflow/workspace.bzl:267:5
 - /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/tensorflow/workspace.bzl:77:5
 - /home/wx/mediapipe/WORKSPACE:146:1
INFO: Call stack for the definition of repository 'six_archive' which is a tf_http_archive (rule definition at /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/third_party/repo.bzl:134:19):
 - /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/tensorflow/workspace.bzl:326:5
 - /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/org_tensorflow/tensorflow/workspace.bzl:77:5
 - /home/wx/mediapipe/WORKSPACE:146:1
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "20e134e1348022090fd38bcf354dd88f4d95808ad905c62cb1a359b03c4ad058"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /home/wx/mediapipe/WORKSPACE:34:1
ERROR: /home/wx/mediapipe/mediapipe/framework/formats/BUILD:126:1: //mediapipe/framework/formats:matrix depends on @eigen_archive//:eigen in repository @eigen_archive which failed to fetch. no such package '@eigen_archive//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/gitlab.com/libeigen/eigen/-/archive/3fda850c46e5e589668a85d89299433e0686eec9/eigen-3fda850c46e5e589668a85d89299433e0686eec9.tar.gz, https://gitlab.com/libeigen/eigen/-/archive/3fda850c46e5e589668a85d89299433e0686eec9/eigen-3fda850c46e5e589668a85d89299433e0686eec9.tar.gz] to /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/eigen_archive/eigen-3fda850c46e5e589668a85d89299433e0686eec9.tar.gz: GET returned 406 Not Acceptable
ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu' failed; build aborted: no such package '@eigen_archive//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/gitlab.com/libeigen/eigen/-/archive/3fda850c46e5e589668a85d89299433e0686eec9/eigen-3fda850c46e5e589668a85d89299433e0686eec9.tar.gz, https://gitlab.com/libeigen/eigen/-/archive/3fda850c46e5e589668a85d89299433e0686eec9/eigen-3fda850c46e5e589668a85d89299433e0686eec9.tar.gz] to /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/eigen_archive/eigen-3fda850c46e5e589668a85d89299433e0686eec9.tar.gz: GET returned 406 Not Acceptable
INFO: Elapsed time: 62.194s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
igured)

**Comment by a798347923** [comment]
I found that mediapipe now supports bazel 2.0.0, but when I use the bazel 2.0.0 build hello world example, I build success,but not print the hello world message.

bazel run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
>     mediapipe/examples/desktop/hello_world:hello_world

WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "20e134e1348022090fd38bcf354dd88f4d95808ad905c62cb1a359b03c4ad058"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/wx/mediapipe/WORKSPACE:33:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz failed: class java.io.IOException connect timed out
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz failed: class java.io.IOException connect timed out
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/examples/desktop/hello_world:hello_world up-to-date:
  bazel-bin/mediapipe/examples/desktop/hello_world/hello_world
INFO: Elapsed time: 1.457s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/mediapipe/examples/desktop/hello_world/helINFO: Build completed successfully, 1 total action
(base) wx@wx-CP65S:~/mediapipe$ 
(base) wx@wx-CP65S:~/mediapipe$ bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
>     mediapipe/examples/desktop/hello_world:hello_world
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Build options --copt and --define have changed, discarding analysis cache.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "20e134e1348022090fd38bcf354dd88f4d95808ad905c62cb1a359b03c4ad058"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/wx/.cache/bazel/_bazel_wx/8d44cfca9efd8f47bcc8b1be2db5fcff/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/wx/mediapipe/WORKSPACE:33:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz failed: class java.io.IOException connect timed out
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz failed: class java.io.IOException connect timed out
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (0 packages loaded, 1233 targets configured).
INFO: Found 1 target...
INFO: From Compiling mediapipe/framework/calculator.pb.cc:
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc: In member function 'virtual google::protobuf::uint8* mediapipe::ProfilerConfig::_InternalSerialize(google::protobuf::uint8*, google::protobuf::io::EpsCopyOutputStream*) const':
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc:1702:41: warning: 'bool mediapipe::ProfilerConfig::enable_input_output_latency() const' is deprecated [-Wdeprecated-declarations]
   if (this->enable_input_output_latency() != 0) {
                                         ^
In file included from bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc:4:0:
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.h:2703:13: note: declared here
 inline bool ProfilerConfig::enable_input_output_latency() const {
             ^~~~~~~~~~~~~~
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc: In member function 'virtual size_t mediapipe::ProfilerConfig::ByteSizeLong() const':
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc:1845:41: warning: 'bool mediapipe::ProfilerConfig::enable_input_output_latency() const' is deprecated [-Wdeprecated-declarations]
   if (this->enable_input_output_latency() != 0) {
                                         ^
In file included from bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc:4:0:
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.h:2703:13: note: declared here
 inline bool ProfilerConfig::enable_input_output_latency() const {
             ^~~~~~~~~~~~~~
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc: In member function 'void mediapipe::ProfilerConfig::MergeFrom(const mediapipe::ProfilerConfig&)':
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc:1956:40: warning: 'bool mediapipe::ProfilerConfig::enable_input_output_latency() const' is deprecated [-Wdeprecated-declarations]
   if (from.enable_input_output_latency() != 0) {
                                        ^
In file included from bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc:4:0:
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.h:2703:13: note: declared here
 inline bool ProfilerConfig::enable_input_output_latency() const {
             ^~~~~~~~~~~~~~
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc: In member function 'virtual google::protobuf::uint8* mediapipe::CalculatorGraphConfig_Node::_InternalSerialize(google::protobuf::uint8*, google::protobuf::io::EpsCopyOutputStream*) const':
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc:2548:33: warning: 'bool mediapipe::CalculatorGraphConfig_Node::has_profiler_config() const' is deprecated [-Wdeprecated-declarations]
   if (this->has_profiler_config()) {
                                 ^
In file included from bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc:4:0:
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.h:3804:13: note: declared here
 inline bool CalculatorGraphConfig_Node::has_profiler_config() const {
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc: In member function 'virtual size_t mediapipe::CalculatorGraphConfig_Node::ByteSizeLong() const':
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc:2684:33: warning: 'bool mediapipe::CalculatorGraphConfig_Node::has_profiler_config() const' is deprecated [-Wdeprecated-declarations]
   if (this->has_profiler_config()) {
                                 ^
In file included from bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc:4:0:
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.h:3804:13: note: declared here
 inline bool CalculatorGraphConfig_Node::has_profiler_config() const {
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc: In member function 'void mediapipe::CalculatorGraphConfig_Node::MergeFrom(const mediapipe::CalculatorGraphConfig_Node&)':
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc:2770:32: warning: 'bool mediapipe::CalculatorGraphConfig_Node::has_profiler_config() const' is deprecated [-Wdeprecated-declarations]
   if (from.has_profiler_config()) {
                                ^
In file included from bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.cc:4:0:
bazel-out/k8-fastbuild/bin/mediapipe/framework/calculator.pb.h:3804:13: note: declared here
 inline bool CalculatorGraphConfig_Node::has_profiler_config() const {
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
Target //mediapipe/examples/desktop/hello_world:hello_world up-to-date:
  bazel-bin/mediapipe/examples/desktop/hello_world/hello_world
INFO: Elapsed time: 50.420s, Critical Path: 34.16s
INFO: 255 processes: 255 linux-sandbox.
INFO: Build completed successfully, 257 total actions
INFO: Running command line: bazel-bin/mediapipe/examples/desktop/hello_world/helINFO: Build completed successfully, 257 total actions

**Comment by jiuqiant** [comment]
Did you do `export GLOG_logtostderr=1`?

**Comment by jiuqiant** [comment]
I believe the solution I mentioned above should solve this issue. Feel free to reopen this issue if it's not the case. Thanks.
