### ISSUE TITLE
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu

### ISSUE THREAD

**Issue by yghcats** [google/mediapipe#592]
command： sudo bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu

error：
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz, https://github.com/tensorflow/tensorflow/archive/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz] to /home/alorli/.cache/bazel/_bazel_root/b3741aa3bed2fdd93a89a11ae8270f0c/external/org_tensorflow/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz: Tried to reconnect at offset 4,601,424 but server didn't support it
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz, https://github.com/tensorflow/tensorflow/archive/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz] to /home/alorli/.cache/bazel/_bazel_root/b3741aa3bed2fdd93a89a11ae8270f0c/external/org_tensorflow/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz: Tried to reconnect at offset 4,601,424 but server didn't support it

What's the problem?

**Comment by jiuqiant** [comment]
Some user just solved a similar issue a few days ago. Please see https://github.com/google/mediapipe/issues/581.

**Comment by jiuqiant** [comment]
I believe the solution I mentioned above should solve this issue. Feel free to reopen this issue if it's not the case. Thanks.
