### ISSUE TITLE
bazel run --define MEDIAPIPE_DISABLE_GPU=1  mediapipe/examples/desktop/hello_world:hello_world

### ISSUE THREAD

**Issue by ai1361720220000** [google/mediapipe#593]
Hello, 
    i follow the instruction in centos to install bazel. But when i run the "hello" demo, some errors happened. 
Thank you~

# bazel run --define MEDIAPIPE_DISABLE_GPU=1  mediapipe/examples/desktop/hello_world:hello_world
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_swift/releases/download/0.12.1/rules_swift.0.12.1.tar.gz failed: class java.net.ConnectException Connection timed out (Connection timed out)
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/apple_support/releases/download/0.7.1/apple_support.0.7.1.tar.gz failed: class java.net.ConnectException Connection timed out (Connection timed out)
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "20e134e1348022090fd38bcf354dd88f4d95808ad905c62cb1a359b03c4ad058"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /root/.cache/bazel/_bazel_root/51418aa554ab899b6c3a6588b35e2108/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /data/project/mediapipe/WORKSPACE:33:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz failed: class java.net.ConnectException Connection timed out (Connection timed out)
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz failed: class java.net.ConnectException Connection timed out (Connection timed out)
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/zlib.net/zlib-1.2.11.tar.gz failed: class java.net.ConnectException Connection timed out (Connection timed out)
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/51418aa554ab899b6c3a6588b35e2108/external/com_google_protobuf/BUILD:429:1: C++ compilation of rule '@com_google_protobuf//:protoc' failed (Exit 1) gcc failed: error executing command /bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections ... (remaining 36 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.318s, Critical Path: 0.13s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by ai1361720220000** [comment]
in order to install bazel 2.0 or higher version. i run "yum install bazel2" in centos7.4。

**Comment by jiuqiant** [comment]
The actual error is `class java.net.ConnectException Connection timed out (Connection timed out)`. Can you verify your network setting? You probably can find some useful solutions at https://github.com/google/mediapipe/issues/3 and https://github.com/google/mediapipe/issues/581.

**Comment by jiuqiant** [comment]
Based on the new issue https://github.com/google/mediapipe/issues/601 you filed, it seems like this problem is already solved. Feel free to reopen it if you need more help.

**Comment by suke27** [comment]
Hi, i also face this issue


> 

have you reslove this issue, i also face similar issue
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_swift/releases/download/0.24.0/rules_swift.0.24.0.tar.gz] to /home/weiyang.su/.cache/bazel/_bazel_weiyang.su/d48b6ccceffa237f6305626b90b19f7a/external/build_bazel_rules_swift/temp17359925556187552861/rules_swift.0.24.0.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by leeon** [comment]
got the same error on my mac m1
