### ISSUE TITLE
Introducing HandCommander, a famework for device control using hand gestures

### ISSUE THREAD

**Issue by lisbravo** [google/mediapipe#594]
Hey guys, I just want to share this project there I have been working on in the last few months.

This is the first fully functioning beta of an open source framework to control "whatever" device, it was developed using a tv but it can be easily adapted to control anything that can somehow subscribe to mqtt. 

It was a lot of work and did it all single handedly, lots of cutting corners, especially in code quality. But I did pay a lot of attention designing the general structure, as always there is a lot of room for improvement, but as it is, it provides a lot of flexibility. Everything is heavily parameterized and categorized, its easy to adapt to new gestures, actions, devices, etc. 

Currently its running on a PC and mqtt commands sent to a Raspberry Pi, in the next days I'll be porting the code to run on the same RPi, with a USB Coral, so I may need some help from MediaPipe's guys since the landmarks NN needs some modding to run on a coral.
(HUGHE thanks to the entire mediapipe team, amazing work dudes, I dont know how much google is paying you but's not enough :D )

Also spent a considerable amount of time documenting the entire process, please check my newly launched site [https://www.deuxexsilicon.com/](https://www.deuxexsilicon.com/) (there is also a hint on my next mediapipe project)

I sincerely hope for you to learn/enjoy/contribute to it, everybody is welcome

The repository is at [https://github.com/lisbravo/myMediaPipe](https://github.com/lisbravo/myMediaPipe), currently don't have set up instructions but will be available in the upcoming days

![](https://github.com/lisbravo/myMediaPipe/raw/master/transition_on_off.gif)

By the way, Im open to job opportunities, currently in Copenhagen but willing to relocate/remote, [LinkedIn](https://www.linkedin.com/in/lisandro-bravo-a226611a3/)

**Comment by lisbravo** [comment]
the project page is having some issues on mobiles, please use the "Desktop Site" option on your phone while I fix this

**Comment by lisbravo** [comment]
New blog post showing how to install and run HandCommander, enjoy :)
[https://www.deuxexsilicon.com/2020/04/15/6th-installation-running/](https://www.deuxexsilicon.com/2020/04/15/6th-installation-running/)

**Comment by lisbravo** [comment]
Another blog post, cross compiling for aarch64 and running HandCommander on a Raspberry Pi 4, enjoy [https://www.deuxexsilicon.com/2020/05/06/7-to-pie-part-2/](https://www.deuxexsilicon.com/2020/05/06/7-to-pie-part-2/)

**Comment by mmm2016** [comment]
I want to use it on an Android TV, which has a camera. Can you control the TV with gestures?

**Comment by Rudrrr** [comment]
Can it possible to run this completely on raspberry pi

**Comment by lisbravo** [comment]
@Rudrrr Yes, I have it running completely standalone in a Rpi 4, check the project web site

**Comment by Rudrrr** [comment]
> @Rudrrr Yes, I have it running completely standalone in a Rpi 4, check the project web site

Thanks...
Could you share me specific link, because i saw the project and i couldn't find it ? (I did find but it says using coral so...) Thanks again
