### ISSUE TITLE
Trying to bazel run handdetection gives me an error related to maven

### ISSUE THREAD

**Issue by youssefaboelmakarem** [google/mediapipe#595]
Running command :
` bazel build -c opt --config=android_arm64 --define 3D=true mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu`

Error : 
ERROR: An error occurred during the fetch of repository 'maven':
   Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:58: "execvp(/home/youssefaboelmakarem/.cache/bazel/_bazel_youssefaboelmakarem/35111ad5fcb241c53aa2e10f0452d8ca/external/maven/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java, ...)": No such file or directory
INFO: Call stack for the definition of repository 'remotejdk11_linux' which is a http_archive (rule definition at /home/youssefaboelmakarem/.cache/bazel/_bazel_youssefaboelmakarem/35111ad5fcb241c53aa2e10f0452d8ca/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/youssefaboelmakarem/.cache/bazel/_bazel_youssefaboelmakarem/35111ad5fcb241c53aa2e10f0452d8ca/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:216:1
INFO: Call stack for the definition of repository 'remote_java_tools_linux' which is a http_archive (rule definition at /home/youssefaboelmakarem/.cache/bazel/_bazel_youssefaboelmakarem/35111ad5fcb241c53aa2e10f0452d8ca/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/youssefaboelmakarem/.cache/bazel/_bazel_youssefaboelmakarem/35111ad5fcb241c53aa2e10f0452d8ca/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:260:1
ERROR: /mnt/f/mediapipe/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/BUILD:64:1: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:mediapipe_lib depends on @maven//:androidx_concurrent_concurrent_futures in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:58: "execvp(/home/youssefaboelmakarem/.cache/bazel/_bazel_youssefaboelmakarem/35111ad5fcb241c53aa2e10f0452d8ca/external/maven/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java, ...)": No such file or directory
ERROR: /mnt/f/mediapipe/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/BUILD:64:1: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:mediapipe_lib depends on @maven//:androidx_lifecycle_lifecycle_common in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:58: "execvp(/home/youssefaboelmakarem/.cache/bazel/_bazel_youssefaboelmakarem/35111ad5fcb241c53aa2e10f0452d8ca/external/maven/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java, ...)": No such file or directory
ERROR: /mnt/f/mediapipe/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/BUILD:64:1: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:mediapipe_lib depends on @maven//:com_google_code_findbugs_jsr305 in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:58: "execvp(/home/youssefaboelmakarem/.cache/bazel/_bazel_youssefaboelmakarem/35111ad5fcb241c53aa2e10f0452d8ca/external/maven/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java, ...)": No such file or directory
ERROR: /mnt/f/mediapipe/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/BUILD:64:1: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:mediapipe_lib depends on @maven//:com_google_guava_guava in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:58: "execvp(/home/youssefaboelmakarem/.cache/bazel/_bazel_youssefaboelmakarem/35111ad5fcb241c53aa2e10f0452d8ca/external/maven/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java, ...)": No such file or directory
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: no such package '@maven//': Unable to run coursier: src/main/tools/process-wrapper-legacy.cc:58: "execvp(/home/youssefaboelmakarem/.cache/bazel/_bazel_youssefaboelmakarem/35111ad5fcb241c53aa2e10f0452d8ca/external/maven/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java, ...)": No such file or directory
INFO: Elapsed time: 1.608s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 6694 targets configured)

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by Aprameyah** [comment]
@jiuqiant I have tried the above solution, had already installed jdk. 

> java --version
> openjdk 10.0.1 2018-04-17
> OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
> OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)
 
But still getting error mentioned in #1207
