### ISSUE TITLE
Facing error while building mediapipe project that was working earlier on the same machine

### ISSUE THREAD

**Issue by jitendersaini** [google/mediapipe#596]
Since morning I'm facing the following issue, even though I deleted the _bazel_j.saini dir from tmp and reinstalled the bazel 1.1.0 and removed the project and cloned it again but no luck:
ERROR: /private/var/tmp/_bazel_j.saini/8e90de47814e77234b141ff7b908f1ad/external/com_google_protobuf_javalite/protobuf.bzl:127:19: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_j.saini/8e90de47814e77234b141ff7b908f1ad/external/com_google_protobuf_javalite/protobuf.bzl", line 122
		rule(<3 more arguments>)
	File "/private/var/tmp/_bazel_j.saini/8e90de47814e77234b141ff7b908f1ad/external/com_google_protobuf_javalite/protobuf.bzl", line 127, in rule
		attr.label(cfg = "host", <3 more arguments>)

**Comment by jiuqiant** [comment]
Starting from [v0.7.2](https://github.com/google/mediapipe/releases/tag/v0.7.2), we only support Bazel 2 and 3. This upgrade is necessary because most MediaPipe external dependencies are also moving to support Bazel 2 and 3 only. Please follow the latest instruction to upgrade. Thanks.

**Comment by jitendersaini** [comment]
Hi jiuqiant,
Thanks again for your prompt response on this, I really appreciate. Now I've updated the bazel version to 3.0.0 and I manage to build the projects now. But I'm not able to run any of the project under mediapipe examples except hello world, let's take the example of hand_tracking and right now I'm on Ubuntu 19.10. The error I'm facing now is as below:
 **Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu up-to-date:
  bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu
INFO: Elapsed time: 184.833s, Critical Path: 108.93s
INFO: 1450 processes: 1449 linux-sandbox, 1 local.
INFO: Build completed successfully, 1566 total actions
INFO: Build completed successfully, 1566 total actions
E0410 18:31:52.742281 11752 demo_run_graph_main_gpu.cc:186] Failed to run the graph: ; Can't find file:**

**Comment by jiuqiant** [comment]
> Hi jiuqiant,
> Thanks again for your prompt response on this, I really appreciate. Now I've updated the bazel version to 3.0.0 and I manage to build the projects now. But I'm not able to run any of the project under mediapipe examples except hello world, let's take the example of hand_tracking and right now I'm on Ubuntu 19.10. The error I'm facing now is as below:
> **Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu up-to-date: bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu INFO: Elapsed time: 184.833s, Critical Path: 108.93s INFO: 1450 processes: 1449 linux-sandbox, 1 local. INFO: Build completed successfully, 1566 total actions INFO: Build completed successfully, 1566 total actions E0410 18:31:52.742281 11752 demo_run_graph_main_gpu.cc:186] Failed to run the graph: ; Can't find file:**


Seems like the error is the graph config file can't be found?
Can you confirm that 1) the pbtxt file `mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt` still exists in your local repo and 2) you run the binary with the `--calculator_graph_config_file` flag?

I follow [the official instruction](https://mediapipe.readthedocs.io/en/latest/hand_tracking_desktop.html#tensorflow-lite-hand-tracking-demo-with-webcam-gpu) to build and run the binary. When I run the binary with the `--calculator_graph_config_file` flag, it prints out the graph first. 
```
$ GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu \
    --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt
I0410 10:37:46.775808 48363 demo_run_graph_main_gpu.cc:51] Get calculator graph config contents: # MediaPipe graph that performs hand tracking with TensorFlow Lite on GPU.
# Used in the examples in
# mediapipe/examples/android/src/java/com/mediapipe/apps/handtrackinggpu and
# mediapipe/examples/ios/handtrackinggpu.

# Images coming into and out of the graph.
input_stream: "input_video"
output_stream: "output_video"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:hand_rect"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}
...
```

**Comment by jitendersaini** [comment]
Hi jiuqiant, Thank you again for replying. I've checked and I've observed a silly mistake done by me when configured my own calculator in mediapipe project. I forgot to mention one attribute **output_stream: "RECOGNIZED_HAND_GESTURE:recognized_hand_gesture"** in **mediapipe/graphs/hand_tracking/subgraphs/hand_landmark_gpu.pbtxt** Now I've re-configured the same and project build and running successfully. But there is one issue that is coming in the new version and i.e. my label that was detected from my calculator is not getting displayed on the red box around hand. in earlier version it was working very well. I'm trying to figure out the issue but is there something else that requires any additional configuration in the new version? I'm posting not my complete code but few important lines below for my calcualtor:
```
namespace mediapipe
{


namespace
{
constexpr char normRectTag[] = "NORM_RECT";
constexpr char normalizedLandmarkListTag[] = "NORM_LANDMARKS";
constexpr char recognizedHandGestureTag[] = "RECOGNIZED_HAND_GESTURE";
}
::mediapipe::Status HandGestureRecognitionCalculator::GetContract(
    CalculatorContract *cc)
{
    RET_CHECK(cc->Inputs().HasTag(normalizedLandmarkListTag));
    cc->Inputs().Tag(normalizedLandmarkListTag).Set<mediapipe::NormalizedLandmarkList>();
    RET_CHECK(cc->Inputs().HasTag(normRectTag));
    cc->Inputs().Tag(normRectTag).Set<NormalizedRect>();
    RET_CHECK(cc->Outputs().HasTag(recognizedHandGestureTag));
    cc->Outputs().Tag(recognizedHandGestureTag).Set<string>();
    return ::mediapipe::OkStatus();
}

::mediapipe::Status HandGestureRecognitionCalculator::Process(
    CalculatorContext *cc)
{
recognized_hand_gesture = new string("OK");
cc->Outputs()
        .Tag(recognizedHandGestureTag)
        .Add(recognized_hand_gesture, cc->InputTimestamp());
    return ::mediapipe::OkStatus();
}
}
```
So I was expecting OK to be displayed above red box around hand, and the same was working very well with old mediapipe project.

Thanks again for your help
Jitender

**Comment by jitendersaini** [comment]
Hello, Can any one help here...

**Comment by jitendersaini** [comment]
Hi, I manage to build and run my project but when I've copied the content of the same project in other directory and trying to build it's throwing some exception there. It seems there are some in stabilities with the new version upgrade of bazel, Even if I explicitly delete dir **"/private/var/tmp/_bazel_j.saini"** the error still persist.

**Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: /private/var/tmp/_bazel_j.saini/ab0fad9461c11437663bfbaefa18fee1/external/org_tensorflow/third_party/py/python_configure.bzl:271:27: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
ERROR: error loading package '': in /private/var/tmp/_bazel_j.saini/ab0fad9461c11437663bfbaefa18fee1/external/org_tensorflow/tensorflow/workspace.bzl: Extension file 'third_party/py/python_configure.bzl' has errors
INFO: Elapsed time: 26.510s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
run-hand-tracking-desktop-cpu.sh: line 5: bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu: No such file or directory**

Thanks
Jitender

**Comment by jitendersaini** [comment]
Why this error:

sh setup_android_sdk_and_ndk.sh 
setup_android_sdk_and_ndk.sh: 25: [: Linux: unexpected operator
setup_android_sdk_and_ndk.sh: 27: [: Linux: unexpected operator
setup_android_sdk_and_ndk.sh: 31: [[: not found
Warning: android_sdk_path (argument 1) is not specified. Fallback to ~/Android/Sdk/
Warning: android_ndk_path (argument 2) is not specified. Fallback to ~/Android/Sdk/ndk-bundle/android-ndk-<NDK_VERSION>/
Warning: ndk_version (argument 3) is not specified. Fallback to r18b.
Warning: android_sdk_path is non empty. Android SDK Installation will be ignored.
Warning: android_ndk_path is non empty. Android NDK Installation will be ignored.
Set android_ndk_repository and android_sdk_repository in WORKSPACE
setup_android_sdk_and_ndk.sh: 96: [: ==: unexpected operator
setup_android_sdk_and_ndk.sh: 103: [: ==: unexpected operator
Done

**Comment by jitendersaini** [comment]
It again see some version upgrade issue:

**(base) AMAC02T8AE6GTFJ:mediapipe j.saini$ $ANDROID_HOME
bash: /Users/j.saini/Library/Android/sdk: is a directory
(base) AMAC02T8AE6GTFJ:mediapipe j.saini$ $ANDROID_NDK_HOME
bash: /Users/j.saini/Library/Android/sdk/ndk/21.0.6113669: is a directory
(base) AMAC02T8AE6GTFJ:mediapipe j.saini$** 

Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: /usr/local/bin/bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --

Computing VCS working set...
Querying targets in project directories...
Command: /usr/local/bin/bazel query --tool_tag=ijwb:AndroidStudio --output=label_kind --keep_going "attr(\"tags\", \"^((?!manual).)*$\", //...:all - //mediapipe/objc/...:all - //mediapipe/examples/ios/...:all - //bazel-bin/...:all - //bazel-genfiles/...:all - //bazel-out/...:all - //bazel-testlogs/...:all - //bazel-mediapipe/...:all - //.aswb/...:all)" --

0 targets found under project directories; syncing 0 of them.
Sync targets from project view targets:
  //mediapipe/examples/android/...:all
  //mediapipe/java/...:all

Building Bazel targets...
Command: /usr/local/bin/bazel build --tool_tag=ijwb:AndroidStudio --keep_going --build_event_binary_file=/var/folders/bh/68j3cj9s7md8v2vh0wp4vjx80000gq/T/intellij-bep-ca8316de-d81f-4769-a103-d4e0dc3ac583 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect "--override_repository=intellij_aspect=/Users/j.saini/Library/Application Support/AndroidStudio3.6/aswb/aspect" --output_groups=intellij-info-android-direct-deps,intellij-info-generic,intellij-info-java-direct-deps,intellij-resolve-android-direct-deps,intellij-resolve-java-direct-deps -- //mediapipe/examples/android/...:all //mediapipe/java/...:all

Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Build options --compilation_mode, --cpu, --crosstool_top, and 3 more have changed, discarding analysis cache.
Analyzing: 74 targets (19 packages loaded, 0 targets configured)
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 21. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]. Bazel will attempt to treat the NDK as if it was r20. This may cause compilation and linkage problems. Please download a supported NDK version.
WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
Analyzing: 74 targets (153 packages loaded, 10006 targets configured)
ERROR: /private/var/tmp/_bazel_j.saini/ab0fad9461c11437663bfbaefa18fee1/external/androidndk/BUILD.bazel:41:1: in cc_toolchain_suite rule @androidndk//:toolchain-libcpp: cc_toolchain_suite '@androidndk//:toolchain-libcpp' does not contain a toolchain for cpu 'darwin'
Analyzing: 74 targets (167 packages loaded, 11590 targets configured)
Analyzing: 74 targets (173 packages loaded, 14374 targets configured)
Analyzing: 74 targets (173 packages loaded, 15969 targets configured)
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu:facedetectioncpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d:objectdetection3d': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handdetectiongpu:handdetectiongpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/objecttrackinggpu:objecttrackinggpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/multihandtrackinggpu:multihandtrackinggpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/hairsegmentationgpu:hairsegmentationgpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu:objectdetectiongpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:facedetectiongpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu': it will not be built
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu:objectdetectioncpu': it will not be built
INFO: Analysis succeeded for only 64 of 74 top-level targets
INFO: Analyzed 74 targets (173 packages loaded, 16101 targets configured).

INFO: Found 64 targets...
[0 / 366] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[1,168 / 1,170] Building mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/libmediapipe_lib.jar (3 source files); 5s worker ... (2 actions, 1 running)
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 95.676s, Critical Path: 13.43s
INFO: 10 processes: 9 darwin-sandbox, 1 worker.
FAILED: Build did NOT complete successfully
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
build invocation result: build_error
Sync was successful, but there were Bazel build errors. The project may not be fully updated or resolve until fixed. If the errors are from your working set, please uncheck 'Bazel > Sync > Expand Sync to Working Set' and try again.
Parsing build outputs...
Total rules: 64, new/changed: 1, removed: 0
Reading IDE info result...
Updating target map
Loaded 1 aspect files, total size 8kB
Target map size: 46
Reading jdeps files...
Loaded 1 jdeps files, total size 2kB
Reading package manifests...
Java content entry count: 2
Updating Unpacked AAR libraries...
Updating Jar Cache...
Prefetching files...
Refreshing files
Computing directory structure...
Initializing project SDKs...
Committing project structure...
Workspace has 41 libraries
Android resource module count: 11, run config modules: 0, order entries: 22, generated resources: 0
Workspace has 13 modules
Updating in-memory state...
Could not read from manifest file: /Users/j.saini/Desktop/workspace/handspeak_mediapipe_bazel2/mediapipe/AndroidManifest.xml
Sync finished

Timing summary:
BlazeInvocation: 125.0s, Prefetching: 6ms, Other: 582ms

**Comment by jiuqiant** [comment]
Hi, there is a bazel warning in your log: `WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 21. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]. Bazel will attempt to treat the NDK as if it was r20. This may cause compilation and linkage problems. Please download a supported NDK version`. Seems like bazel has not supported NDK r21 but your Android Studio has 21.0.6113669.

**Comment by jiuqiant** [comment]
See https://github.com/google/mediapipe/issues/609#issuecomment-614359395

**Comment by jitendersaini** [comment]
Hi, Thanks for responding, Actually I'm facing this error when I'm building android project from android studio by clicking the bazel green heart icon from the tool tray. So I'm not sure how to configure build to run with option ( --host_crosstool_top=@bazel_tools//tools/cpp:toolchain) although I checked my .bazelrc file and there I can see the following entries are present
build:android --crosstool_top=//external:android/crosstool
**build:android --host_crosstool_top=@bazel_tools//tools/cpp:toolchain**
build:android --linkopt=-landroid

So I'm assuming while build is running this toolchain option is already passed as build option. I'm not sure.

Thanks
Jitender

**Comment by weinixuehao** [comment]
@jitendersaini 
Please see this solution, #640

**Comment by jiuqiant** [comment]
Thanks @weinixuehao for providing the solution!
