### ISSUE TITLE
Demo to use Mediapipe on a video

### ISSUE THREAD

**Issue by momo1986** [google/mediapipe#597]
Hello, dear Mediapipe guys.
Is there demo for the usage of Mediapipe on a video instead of Web Camera?
For example, a video on hands or faces to use Mediapipe.
Java on Android APP or JavaScript on web browser with some example code will be great to be showed if there exists.
if there not, is there some API that I can reference to realize this function?
Thanks & Regards!

**Comment by momo1986** [comment]
Hi, @eknight7 , @jiuqiant .

In my mind, all the demo is running on camera interface not on specific video.

Am I right?

Thanks & regards!

**Comment by jiuqiant** [comment]
Our desktop demos support both video files and camera as input. See all the desktop examples at https://github.com/google/mediapipe/blob/master/mediapipe/docs/examples.md#desktop.

For Android, we haven't released the video file support yet. But, it should be not hard to decode video files outside of MediaPipe and pass the decoded frames to a MediaPipe pipeline.

**Comment by eknight7** [comment]
Yes there are previous github issues on how to run a graph on a pre-recorded video on Android:
https://github.com/google/mediapipe/issues/234#issuecomment-554233716
https://github.com/google/mediapipe/issues/417

**Comment by afsaredrisy** [comment]
It is possible you can do it without changing anything in framework. I did it in Android, You just need to play a video with SurfaceTexture. Here is that code.
**To Play Video with SurfaceTexture**
```java
private SurfaceTexture surfaceTexture;
MediaPlayer player;
 private void mediaPlay(){
        surfaceTexture = new MySurfaceTexture(42);
        Uri filUri = Uri.parse(FILE_PATH);
         player = MediaPlayer.create(this,filUri);
        player.setSurface(new Surface(surfaceTexture));
        player.setLooping(true);
        player.start();
    }

// Now You can set this surfaceTexture to ExternalTextureConverter Object

 converter.setSurfaceTextureAndAttachToGLContext(
                    surfaceTexture,DISPLAY_SIZE_WIDTH
                   , DISPLAY_SIZE_HEIGHT)
```

Here is `MySurfaceTextureClass`

```java

public class MySurfaceTexture extends SurfaceTexture {
    public MySurfaceTexture(int texName) {
        super(texName);
        init();
    }

    private void init() {
        super.detachFromGLContext();
    }
}


```

Hope it will help you.

**Comment by momo1986** [comment]
Hello @eknight7  and @jiuqiant .

I can run the mediapipe/examples/desktop/simple_run_graph_main.cc.

I try to do the multiple_hand_tracking.

`bazel build -c opt mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_tflite --define MEDIAPIPE_DISABLE_GPU=1`

The  compilation is OK.

I do the packet and data retrieval as expected in Java:
```
//Get multiple hand landmarks.
::mediapipe::CalculatorGraphConfig::Node GetMultiHandsLandkmarkNode() {
  return ::mediapipe::ParseTextProtoOrDie<::mediapipe::CalculatorGraphConfig::Node>(R"(
    calculator: "MultiHandLandmarkSubgraph"
    input_stream: "IMAGE:input_video"
    input_stream: "NORM_RECTS:multi_hand_rects"
    output_stream: "LANDMARKS:multi_hand_landmarks"
    output_stream: "NORM_RECTS:multi_hand_rects_from_landmarks"
  )");
}
//This API is for output side data packet retrieval.
::mediapipe::Status OutputStreamToLocalFile(
    ::mediapipe::OutputStreamPoller& poller, ::mediapipe::CalculatorRunner& runner) {
  std::ofstream file;
  std::ofstream textFile;
  file.open(FLAGS_output_stream_file);
  std::ofstream	OsWrite("/Users/junyan/find_android_project/CPlusPlusTest/debug.txt",std::ofstream::app);
  ::mediapipe::Packet packet;
  while (poller.Next(&packet)) {
    std::string output_data;
    std::cout<<"Initialization."<<std::endl;
    runner.Run();
    const std::vector<::mediapipe::Packet>& output = runner.Outputs().Tag("LANDMARKS").packets;
    //Loop landmarks.
    std::cout<<"Run."<<std::endl;
    std::cout<<output.size()<<std::endl;
    for (int i = 0; i < output.size(); i++) {
      const ::mediapipe::NormalizedLandmarkList & output_landmarks = output[i].Get<::mediapipe::NormalizedLandmarkList>();
      for (int j = 0; j < output_landmarks.landmark_size(); j++) {
        OsWrite<<i<<"th iteration: ";
        OsWrite<<"x is: "<<output_landmarks.landmark(j).x();
        OsWrite<<"y is: "<<output_landmarks.landmark(j).y();
        OsWrite<<"z is: "<<output_landmarks.landmark(j).z();
        OsWrite<<std::endl;
      }
    }
    if (!FLAGS_strip_timestamps) {
      absl::StrAppend(&output_data, packet.Timestamp().Value(), ",");
    }
    absl::StrAppend(&output_data, packet.Get<std::string>(), "\n");
    file << output_data;
  }
  file.close();
  OsWrite.close();
  return ::mediapipe::OkStatus();
```

I run the command and get the error:
`bazel-bin/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_tflite   --calculator_graph_config_file=mediapipe/graphs/hand_tracking/multi_hand_tracking_desktop.pbtxt   --input_side_packets=input_video_path=/Users/junyan/find_android_project/CPlusPlusTest/sf-252261.mp4,output_video_path=/Users/junyan/find_android_project/CPlusPlusTest/sf-252261-test.mp4 --output_stream multi_hand_landmarks --output_stream_file multi_hands_packets`

> F0410 21:49:16.064751 2340651904 packet.h:682] Packet::Get() failed: The Packet stores "std::__1::vector<mediapipe::NormalizedLandmarkList, std::__1::allocator<mediapipe::NormalizedLandmarkList> >", but "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >" was requested.
> *** Check failure stack trace: ***
>     @        0x1077ca1ef  google::LogMessageFatal::~LogMessageFatal()
>     @        0x1077c65d9  google::LogMessageFatal::~LogMessageFatal()
>     @        0x1073deaf7  mediapipe::Packet::Get<>()
>     @        0x1073bd73c  OutputStreamToLocalFile()
>     @        0x1073bf5c9  RunMPPGraph()
>     @        0x1073c0155  main
> Abort trap: 6


Is there any method to obtain the landmark data packet and parse it correctly from the stream?

Thanks & Regards!

**Comment by momo1986** [comment]
Is there any tips to add hand lanmark data retrieval call-back during cxx examples?

**Comment by eknight7** [comment]
Yes, please see https://gist.github.com/eknight7/d4a57504c8f866fc80c0eb2c61ff6b4f

**Comment by momo1986** [comment]
Hi @eknight7 .
It works.
Thanks for your patience.
Regards!

**Comment by eyaler** [comment]
here you go: https://eyaler.github.io/tfjs_webgl_app/face_landmark

**Comment by V-m1r** [comment]
> It is possible you can do it without changing anything in framework. I did it in Android, You just need to play a video with SurfaceTexture. Here is that code. **To Play Video with SurfaceTexture**
> 
> ```java
> private SurfaceTexture surfaceTexture;
> MediaPlayer player;
>  private void mediaPlay(){
>         surfaceTexture = new MySurfaceTexture(42);
>         Uri filUri = Uri.parse(FILE_PATH);
>          player = MediaPlayer.create(this,filUri);
>         player.setSurface(new Surface(surfaceTexture));
>         player.setLooping(true);
>         player.start();
>     }
> 
> // Now You can set this surfaceTexture to ExternalTextureConverter Object
> 
>  converter.setSurfaceTextureAndAttachToGLContext(
>                     surfaceTexture,DISPLAY_SIZE_WIDTH
>                    , DISPLAY_SIZE_HEIGHT)
> ```
> 
> Here is `MySurfaceTextureClass`
> 
> ```java
> public class MySurfaceTexture extends SurfaceTexture {
>     public MySurfaceTexture(int texName) {
>         super(texName);
>         init();
>     }
> 
>     private void init() {
>         super.detachFromGLContext();
>     }
> }
> ```
> 
> Hope it will help you.

Hello!
How do you display the video then?
May you please share complete code for using mediapipe on prerecorded video?

**Comment by qingwufong** [comment]
Still don't know how to get it using javascript in browser.

**Comment by tyrmullen** [comment]
All of the JS APIs have a "send" call, like `await selfieSegmentation.send({image: inputImageSource});`.  The CodePen demos have a bunch of extra helper classes (like SourcePicker or Camera), but those are just so we can make demos more easily.  That "send" call is really the key, and each send call will run over a single video/image frame (here, inputImageSource can be an ImageBitmap, HTMLVideoElement, HTMLCanvasElement, HTMLImageElement, etc.).  No matter if you're playing webcam or video, you'll likely end up with an HTMLVideoElement which is playing, so just keep passing that HTMLVideoElement to "send" (you can use `requestAnimationFrame` to poll repeatedly for video frames).

**Comment by qingwufong** [comment]
> All of the JS APIs have a "send" call, like `await selfieSegmentation.send({image: inputImageSource});`. The CodePen demos have a bunch of extra helper classes (like SourcePicker or Camera), but those are just so we can make demos more easily. That "send" call is really the key, and each send call will run over a single video/image frame (here, inputImageSource can be an ImageBitmap, HTMLVideoElement, HTMLCanvasElement, HTMLImageElement, etc.). No matter if you're playing webcam or video, you'll likely end up with an HTMLVideoElement which is playing, so just keep passing that HTMLVideoElement to "send" (you can use `requestAnimationFrame` to poll repeatedly for video frames).

Yes, that`s it. We also found Mediapipe codepen demos have helper class which is controls.SourcePicker, it works for us. 
Thanks very much！
Best Regards~

**Comment by clydebailey** [comment]
> It is possible you can do it without changing anything in framework. I did it in Android, You just need to play a video with SurfaceTexture. Here is that code. **To Play Video with SurfaceTexture**
> 
> ```java
> private SurfaceTexture surfaceTexture;
> MediaPlayer player;
>  private void mediaPlay(){
>         surfaceTexture = new MySurfaceTexture(42);
>         Uri filUri = Uri.parse(FILE_PATH);
>          player = MediaPlayer.create(this,filUri);
>         player.setSurface(new Surface(surfaceTexture));
>         player.setLooping(true);
>         player.start();
>     }
> 
> // Now You can set this surfaceTexture to ExternalTextureConverter Object
> 
>  converter.setSurfaceTextureAndAttachToGLContext(
>                     surfaceTexture,DISPLAY_SIZE_WIDTH
>                    , DISPLAY_SIZE_HEIGHT)
> ```
> 
> Here is `MySurfaceTextureClass`
> 
> ```java
> public class MySurfaceTexture extends SurfaceTexture {
>     public MySurfaceTexture(int texName) {
>         super(texName);
>         init();
>     }
> 
>     private void init() {
>         super.detachFromGLContext();
>     }
> }
> ```
> 
> Hope it will help you.

What a wow!!

**Comment by clydebailey** [comment]
The above code for passing asset video data to the frame processor is working fine but need some help in displaying the data back to the screen....
