### ISSUE TITLE
Failed to run TensorFlow Lite Object Detection Demo for Desktop

### ISSUE THREAD

**Issue by nirmal-autowiz** [google/mediapipe#603]
Hi MediaPipe Team,

I got the following error while running [Object Detection for Desktop](https://github.com/google/mediapipe/blob/master/mediapipe/docs/object_detection_desktop.md#tensorflow-lite-object-detection-demo) in Windows Subsystem for Linux (Ubuntu):

`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/object_detection:object_detection_tflite`

ERROR: /home/xxxxx/mediapipe/mediapipe/examples/desktop/object_detection/BUILD:29:1: Linking of rule '//mediapipe/examples/desktop/object_detection:object_detection_tflite' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/object_detection/object_detection_tflite-2.params

I followed the instructions for installing MediaPipe from [here](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows-subsystem-for-linux-wsl). Hello World for Desktop works fine.

Test Environment:
Ubuntu 18.04
Bazel 2.0.0
Python 3.7.5
OpenCV : Run package manager tool to install the pre-compiled OpenCV libraries
GCC and G++: 7.5 and 7.5

Kindly find the full output generated after running the above command attached.
[objdetect_tfliet_op.txt](https://github.com/google/mediapipe/files/4464374/objdetect_tfliet_op.txt)

Thank you for your time and looking forward to a reply.

Regards,
Nirmal Jose

**Comment by PrinceP** [comment]
You are getting the OpenCV compilation error. 
```
undefined reference to 'cv::....
```

Take a look at - 
[#562(comment)](
https://github.com/google/mediapipe/issues/562#issuecomment-606203557)

#563

**Comment by nirmal-autowiz** [comment]
> You are getting the OpenCV compilation error.
> 
> ```
> undefined reference to 'cv::....
> ```
> 
> Take a look at -
> [#562(comment)](https://github.com/google/mediapipe/issues/562#issuecomment-606203557)
> 
> #563

@PrinceP Tried Solution 1. Edit third_party/opencv_linux.BUILD from #562. 
But that hasn't resolved the problem. I am still getting the same error while running [Object Detection for Desktop](https://github.com/google/mediapipe/blob/master/mediapipe/docs/object_detection_desktop.md#tensorflow-lite-object-detection-demo).

ERROR: /home/xxxxx/mediapipe/mediapipe/examples/desktop/object_detection/BUILD:29:1: Linking of rule '//mediapipe/examples/desktop/object_detection:object_detection_tflite' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/object_detection/object_detection_tflite-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function cv::Mat::~Mat(): error: undefined reference to 'cv::Mat::deallocate()'
.
.
.

Looking forward to a solution.

Regards,
Nirmal Jose

**Comment by jiuqiant** [comment]
Seems like you still run into an opencv misconfiguration issue. Can you report 1) the exact location of your opencv headers and libraries, 2) your opencv version, and 3) print out third_party/opencv_linux.BUILD. I could help you debug with those information.

**Comment by nirmal-autowiz** [comment]
Hi @jiuqiant , 

Kindly find the following,
1. OpenCV headers and libraries location:  \usr\include\opencv2 and \usr\lib\x86_64-linux-gnu
2. OpenCV Version : 3.2.0
3. third_party/opencv_linux.BUILD : 
`cc_library(
    name = "opencv",
    srcs = glob(
        [
            "local/lib/libopencv_core.so",
            "local/lib/libopencv_calib3d.so",
            "local/lib/libopencv_features2d.so",
            "local/lib/libopencv_highgui.so",
            "local/lib/libopencv_imgcodecs.so",
            "local/lib/libopencv_imgproc.so",
            "local/lib/libopencv_video.so",
            "local/lib/libopencv_videoio.so",
        ],
    ),
    hdrs = glob(["local/include/opencv2/**/*.h*"]),
    includes = ["local/include/"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)`

Thank you for your support.
Nirmal

**Comment by jiuqiant** [comment]
Please modify `WORKSPACE` and `third_party/opencv_linux.BUILD` like the following to match your OpenCV headers and libraries location. However, if you use package manager to install OpenCV, the defeault opencv config should just work as-is. It seems like you also run the setup_opencv.sh script that modifies opencv_linux.BUILD?

```
# In WORKSPACE, make sure you have the following:
new_local_repository(
    name = "linux_opencv",
    build_file = "@//third_party:opencv_linux.BUILD",
    path = "/usr",
)

# In third_party/opencv_linux.BUILD, make sure you have the following:
cc_library(
    name = "opencv",
    srcs = glob(
        [
            "lib/x86_64-linux-gnu/libopencv_core.so",
            "lib/x86_64-linux-gnu/libopencv_calib3d.so",
            "lib/x86_64-linux-gnu/libopencv_features2d.so",
            "lib/x86_64-linux-gnu/libopencv_highgui.so",
            "lib/x86_64-linux-gnu/libopencv_imgcodecs.so",
            "lib/x86_64-linux-gnu/libopencv_imgproc.so",
            "lib/x86_64-linux-gnu/libopencv_video.so",
            "lib/x86_64-linux-gnu/libopencv_videoio.so",
        ],
    ),
    hdrs = glob(["include/opencv2/**/*.h*"]),
    includes = ["include"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
```

If it still doesn't work, please do `bazel clean` to make sure the build cache is gone.

**Comment by nirmal-autowiz** [comment]
Thank You @jiuqiant for your support, it's working fine now.

**Comment by Ncuaresma** [comment]
> Thank You @jiuqiant for your support, it's working fine now.

Hi @nirmal-autowiz how did you manage to solve it? I got the same problem and I add the informationn got from @jiuqiant but still having the error.
Thank you
