### ISSUE TITLE
Debug mediapipe source code IOS

### ISSUE THREAD

**Issue by 7AM7** [google/mediapipe#604]
Helleo there,
I am trying to using debug option in IOS like that:
`bazel build -c dbg --config=ios_arm64 mediapipe/examples/ios/multihandtrackinggpu:MultiHandTrackingGpuApp`

I am trying to get data from `tflite_tensors_to_landmarks_calculator.cc` like this:
```
  const int num_dimensions = num_values / num_landmarks_;
  CHECK_GT(num_dimensions, 0);
  LOG(INFO) << "num_dimensions: " << num_dimensions;
```
But, nothing displayed in Console 
Any help ?

**Comment by eknight7** [comment]
Does logging in any other calculator work?
What about `LOG` or `NSLog` statements in `ViewController.mm`?

In case you are trying to extract landmarks:
Just FYI, the iOS multi-hand tracking app has a method to extract landmarks in `ViewController.mm`: https://github.com/google/mediapipe/blob/master/mediapipe/examples/ios/multihandtrackinggpu/ViewController.mm#L168-L188.

If you are interested in getting a particular set of packets, you can add similar code in `ViewController.mm` to extract a set of packets from a particular output stream.

**Comment by 7AM7** [comment]
@eknight7 NSLog is working fine but LOG in all calculators doesn't work.
I am trying to add a new model (posenet) So, I need to display some outputs.

**Comment by sgowroji** [comment]
Hi @7AM7,  Are you still looking resolution for the above query. Thanks!
