### ISSUE TITLE
Hand Tracking Web demo not working

### ISSUE THREAD

**Issue by yuedai0531** [google/mediapipe#605]
![image](https://user-images.githubusercontent.com/26657972/79082675-04a5df80-7cf6-11ea-9f0b-ca6e04f829b1.png)

**Comment by Akshaysharma29** [comment]
Facing the same issue.

**Comment by fanzhanggoogle** [comment]
Hi, it should be fixed now. Please try again.
BTW, the web demo is a lightweight version of the demo, so it's not the full quality as our mobile demos. Please try the mobile/desktop demo if you want to have full quality.
