### ISSUE TITLE
Changing model at runtime in the graph

### ISSUE THREAD

**Issue by PrinceP** [google/mediapipe#607]
Can we change the model after we generated the aar file of the mediapipe graph at runtime?

I have a hand gesture model for different tasks. It works for one model. 

I didn't want to use the Boolean Gate to avoid loading all models. The selection of a particular
model can be given at the input stream.   

Will the solution be #198 where we input the model's path and it can change based on user requirement? Can it work?

**Comment by hadon** [comment]
This is a common use case.  Many apps need to switch between inference models when a new effect is selected by the user.  The scheme we normally recommend is to re-initialize the mediapipe graph when a new effect is selected.  This completes the life cycle of all of the calculators including the InferenceCalculator.  Starting inference with a different model will require some start-up and warm-up interval in any case.  Sometimes it is possible to minimize the start-up time by transferring some resources from the stopping graph to the starting graph, or by keeping the previous graph running while the new graph is starting up.
