### ISSUE TITLE
how to debug c++ code

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#608]
build -c dgb .... can not hit breakpoint in c++?
I have tried build -c opt ... and build -c dgb --strip=nerver ..., the libmediapipe.so size is the same and us nm to verify that not found debug symbols?
Does Bazel building apk stripped by default?

**Comment by jiuqiant** [comment]
For MediaPipe Android demos, Bazel doesn't strip unused symbols by default. Take hand detection gpu as an example,  If you append `--linkopt=-s ` to the build command, the APK size will go down from 63MB to 21MB. 
```
$ bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handdetectiongpu
$ ls -lh   bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handdetectiongpu/handdetectiongpu.apk
-r-xr-xr-x 1 jqtang primarygroup 63M Apr 15 10:25 bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handdetectiongpu/handdetectiongpu.apk 
```

```
$ bazel build -c opt --config=android_arm64 --linkopt=-s mediapipe/examples/android/src/java/com/google/mediapipe/apps/handdetectiongpu
$ ls -lh   bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handdetectiongpu/handdetectiongpu.apk
-r-xr-xr-x 1 jqtang primarygroup 21M Apr 15 10:24 bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handdetectiongpu/handdetectiongpu.apk
```

When Bazel build MediaPipe AAR, it doesn't strip any symbol. We don't worry about the APK size since Android Studio will eventually strip the unused symbols.

**Comment by weinixuehao** [comment]
@jiuqiant Very thanks for you! I will try soon!
Its possible to development and debugging on the desktop with command line program?

**Comment by weinixuehao** [comment]
@jiuqiant 
Please see below image which indeed has debug symbols
![image](https://user-images.githubusercontent.com/17869361/79691473-55877c00-8292-11ea-9879-c721e76220c3.png)
I tried to add breakpoint to FlowLimiterCalculator.cc file but not found this file by shift + cmd + O shortcut key to open.
FlowLimiterCalculator.cc not built?
![image](https://user-images.githubusercontent.com/17869361/79691680-9af87900-8293-11ea-8f32-a1630edd8cd3.png)

**Comment by weinixuehao** [comment]
see #648
