### ISSUE TITLE
build aar failed

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#609]
bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar -s
ERROR: /Users/user/Ctsmed/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: no such package '@com_google_common_flogger_system_backend//jar': The repository '@com_google_common_flogger_system_backend' could not be resolved and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar_android_lib'
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar' failed; build aborted: no such package '@com_google_common_flogger_system_backend//jar': The repository '@com_google_common_flogger_system_backend' could not be resolved
INFO: Elapsed time: 0.237s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @local_config_cc; Restarting.

**Comment by PrinceP** [comment]
Can you take a quick look at #3

**Comment by weinixuehao** [comment]
it seems not network issues as i have downloaded other dependencies.
Below is a remote repo?
![image](https://user-images.githubusercontent.com/17869361/79229955-70bf4980-7e96-11ea-910b-2bba5b7880e6.png)

**Comment by weinixuehao** [comment]
@PrinceP 
Thanks!
I used follow command in #3 
$ bazel build -c opt --config=android_arm64 \ 
  --distdir=<your cache directory> \
  --repository_cache=<your cache directory> \
  --keep_going \
  mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu
success!

**Comment by weinixuehao** [comment]
bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar --distdir=cache_repo --repository_cache=cache_repo --keep_going -s
ERROR: /Users/user/Ctsmed/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: no such target '@com_google_protobuf_javalite//:protoc_gen_javalite': target 'protoc_gen_javalite' not declared in package '' defined by /private/var/tmp/_bazel_chenlong/46cfe12d82525b8b2b43cf38d2da2eb7/external/com_google_protobuf_javalite/BUILD and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:calculator_proto_proto_java_src_generator'
ERROR: /Users/user/Ctsmed/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: no such target '@com_google_protobuf_javalite//:protoc_gen_javalite': target 'protoc_gen_javalite' not declared in package '' defined by /private/var/tmp/_bazel_chenlong/46cfe12d82525b8b2b43cf38d2da2eb7/external/com_google_protobuf_javalite/BUILD and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:landmark_proto_proto_java_src_generator'
ERROR: /Users/user/Ctsmed/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: no such target '@com_google_protobuf_javalite//:protoc_gen_javalite': target 'protoc_gen_javalite' not declared in package '' defined by /private/var/tmp/_bazel_chenlong/46cfe12d82525b8b2b43cf38d2da2eb7/external/com_google_protobuf_javalite/BUILD and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:detection_proto_proto_java_src_generator'
ERROR: /Users/user/Ctsmed/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: no such target '@com_google_protobuf_javalite//:protoc_gen_javalite': target 'protoc_gen_javalite' not declared in package '' defined by /private/var/tmp/_bazel_chenlong/46cfe12d82525b8b2b43cf38d2da2eb7/external/com_google_protobuf_javalite/BUILD and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:location_data_proto_proto_java_src_generator'
ERROR: /Users/user/Ctsmed/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: no such target '@com_google_protobuf_javalite//:protoc_gen_javalite': target 'protoc_gen_javalite' not declared in package '' defined by /private/var/tmp/_bazel_chenlong/46cfe12d82525b8b2b43cf38d2da2eb7/external/com_google_protobuf_javalite/BUILD and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:rasterization_proto_proto_java_src_generator'
ERROR: /Users/user/Ctsmed/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: no such package '@com_google_code_findbugs//jar': The repository '@com_google_code_findbugs' could not be resolved and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar_android_lib'
ERROR: /Users/user/Ctsmed/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: no such package '@com_google_common_flogger//jar': The repository '@com_google_common_flogger' could not be resolved and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar_android_lib'
ERROR: /Users/user/Ctsmed/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: no such package '@com_google_common_flogger_system_backend//jar': The repository '@com_google_common_flogger_system_backend' could not be resolved and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar_android_lib'
ERROR: /Users/user/Ctsmed/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: no such package '@com_google_guava_android//jar': The repository '@com_google_guava_android' could not be resolved and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar_android_lib'
ERROR: /Users/user/Ctsmed/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: no such package '@androidx_lifecycle//jar': The repository '@androidx_lifecycle' could not be resolved and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar_android_lib'
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 21. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]. Bazel will attempt to treat the NDK as if it was r20. This may cause compilation and linkage problems. Please download a supported NDK version.
WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
ERROR: /private/var/tmp/_bazel_chenlong/46cfe12d82525b8b2b43cf38d2da2eb7/external/androidndk/BUILD.bazel:41:1: in cc_toolchain_suite rule @androidndk//:toolchain-libcpp: cc_toolchain_suite '@androidndk//:toolchain-libcpp' does not contain a toolchain for cpu 'darwin'
WARNING: errors encountered while analyzing target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar': it will not be built
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
ERROR: command succeeded, but there were loading phase errors
INFO: Elapsed time: 0.568s, Critical Path: 0.00s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
@PrinceP

**Comment by jiuqiant** [comment]
I apologize that I forgot to update mediapipe_aar.bzl after MP switching to protobuf 3.11.4 and bazel 2&3.

After making the following changes in mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl, you should be able to build mediapipe AAR. 
```
diff --git a/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl b/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
index 6078318..a8fbe73 100644
--- a/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
+++ b/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
@@ -130,11 +130,11 @@ cat > $(OUTS) <<EOF
             "//third_party:androidx_legacy_support_v4",
             "//third_party:camerax_core",
             "//third_party:camera2",
-            "@com_google_code_findbugs//jar",
-            "@com_google_common_flogger//jar",
-            "@com_google_common_flogger_system_backend//jar",
-            "@com_google_guava_android//jar",
-            "@androidx_lifecycle//jar",
+            "@maven//:com_google_code_findbugs_jsr305",
+            "@maven//:com_google_flogger_flogger",
+            "@maven//:com_google_flogger_flogger_system_backend",
+            "@maven//:com_google_guava_guava",
+            "@maven//:androidx_lifecycle_lifecycle_common",
         ],
     )

@@ -144,18 +144,16 @@ def _proto_java_src_generator(name, proto_src, java_lite_out, srcs = []):
     native.genrule(
         name = name + "_proto_java_src_generator",
         srcs = srcs + [
-            "@com_google_protobuf_javalite//:well_known_protos",
+            "@com_google_protobuf//:well_known_protos",
         ],
         outs = [java_lite_out],
-        cmd = "$(location @com_google_protobuf_javalite//:protoc) " +
-              "--plugin=protoc-gen-javalite=$(location @com_google_protobuf_javalite//:protoc_gen_javalite) " +
+        cmd = "$(location @com_google_protobuf//:protoc) " +
               "--proto_path=. --proto_path=$(GENDIR) " +
-              "--proto_path=$$(pwd)/external/com_google_protobuf_javalite/src " +
-              "--javalite_out=$(GENDIR) " + proto_src + " && " +
+              "--proto_path=$$(pwd)/external/com_google_protobuf/src " +
+              "--java_out=lite:$(GENDIR) " + proto_src + " && " +
               "mv $(GENDIR)/" + java_lite_out + " $$(dirname $(location " + java_lite_out + "))",
         tools = [
-            "@com_google_protobuf_javalite//:protoc",
-            "@com_google_protobuf_javalite//:protoc_gen_javalite",
+            "@com_google_protobuf//:protoc",
         ],
     )
```

Although I haven't fully tested the AAR, the protos in classes.jar look good to me. 
![Screen Shot 2020-04-14 at 11 02 55 AM](https://user-images.githubusercontent.com/3359144/79258277-c1f01e80-7e3f-11ea-8788-d8f56f9feadc.png)
 
We will fix this issue in the coming release. Thanks for reporting this issue.

**Comment by weinixuehao** [comment]
@jiuqiant 
Thanks! It`s working! but still has an error.
`bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a     //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar
WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
ERROR: /private/var/tmp/_bazel_chenlong/46cfe12d82525b8b2b43cf38d2da2eb7/external/androidndk/BUILD.bazel:41:1: in cc_toolchain_suite rule @androidndk//:toolchain-libcpp: cc_toolchain_suite '@androidndk//:toolchain-libcpp' does not contain a toolchain for cpu 'darwin'
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar' failed; build aborted: Analysis of target '@androidndk//:toolchain-libcpp' failed; build aborted
INFO: Elapsed time: 6.929s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 6222 targets configured)
    Fetching @local_config_xcode; fetching 5s`

**Comment by weinixuehao** [comment]
@jiuqiant 
I am sorry for troubling you, I still have a question but no answer in #608 to wish you to give me an answer or idea. e.g How do you usually debug the c++ code or mixed debugging java and c++？or lldb gdb? or gdb\lldb in vscode ?

1、bazel build -c dbg ... not working but built tflite working in android studio that using its profile apk or debug feature
2、I have compared the mediapipe_jni.so size by -c opt and -c dbg that is the same.
3、The so have not debug info with nm tool.

**Comment by jiuqiant** [comment]
If this issue is solved, I am going to close it.
For https://github.com/google/mediapipe/issues/608, we will take a look.

**Comment by weinixuehao** [comment]
@jiuqiant Thanks! Build completed successfully with host_crosstool_top option.

`bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a     //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar --host_crosstool_top=@bazel_tools//tools/cpp:toolchain`

`Archive:  /private/var/tmp/_bazel_chenlong/46cfe12d82525b8b2b43cf38d2da2eb7/sandbox/darwin-sandbox/4355/execroot/mediapipe/bazel-out/darwin-opt/bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/mp_face_detection_aar_dummy_app_unsigned.apk
   creating: lib/
   creating: lib/arm64-v8a/
  inflating: lib/arm64-v8a/libmediapipe_jni.so
   creating: lib/armeabi-v7a/
  inflating: lib/armeabi-v7a/libmediapipe_jni.so
  adding: jni/arm64-v8a/libmediapipe_jni.so (deflated 75%)
  adding: jni/armeabi-v7a/libmediapipe_jni.so (deflated 74%)
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar up-to-date:
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/mp_face_detection_aar.aar
INFO: Elapsed time: 22452.530s, Critical Path: 2659.41s
INFO: 4355 processes: 4216 darwin-sandbox, 2 local, 137 worker.
INFO: Build completed successfully, 4517 total actions`

**Comment by H1Gdev** [comment]
@jiuqiant 

When will this be merged ?

**Comment by jiuqiant** [comment]
> @jiuqiant
> 
> When will this be merged ?

Solved in https://github.com/google/mediapipe/commit/024f7bf0f1e74149ea92b942cf168ccddf317073

**Comment by jiuqiant** [comment]
> @jiuqiant Thanks! Build completed successfully with `--host_crosstool_top` option. `does not contain a toolchain for cpu 'darwin' ERROR: Analysis of target` was disappear!
> 
> `bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar --host_crosstool_top=@bazel_tools//tools/cpp:toolchain`
> 
> `Archive: /private/var/tmp/_bazel_chenlong/46cfe12d82525b8b2b43cf38d2da2eb7/sandbox/darwin-sandbox/4355/execroot/mediapipe/bazel-out/darwin-opt/bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/mp_face_detection_aar_dummy_app_unsigned.apk creating: lib/ creating: lib/arm64-v8a/ inflating: lib/arm64-v8a/libmediapipe_jni.so creating: lib/armeabi-v7a/ inflating: lib/armeabi-v7a/libmediapipe_jni.so adding: jni/arm64-v8a/libmediapipe_jni.so (deflated 75%) adding: jni/armeabi-v7a/libmediapipe_jni.so (deflated 74%) Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar up-to-date: bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/mp_face_detection_aar.aar INFO: Elapsed time: 22452.530s, Critical Path: 2659.41s INFO: 4355 processes: 4216 darwin-sandbox, 2 local, 137 worker. INFO: Build completed successfully, 4517 total actions`

Thanks for reporting this. The documentation is also updated.
