### ISSUE TITLE
Do you have face_detection_back model of blazeface

### ISSUE THREAD

**Issue by JaydenGG** [google/mediapipe#61]
I want to try the blazeface model using back camera, but I only find face_detection_front.tflite. Do you guys have face_detection_back.tflite? Thank you.

**Comment by jiuqiant** [comment]
Hi, you just need to modify one line in the [MainActivity.java of facedetectiongpu](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu/MainActivity.java) to switch to the back camera.

**Comment by JaydenGG** [comment]
@jiuqiant ,But from the original paper, I guess the author has trained two model (one for back camera and one for front camera), the front model train the face bigger than 20%(from paper), but the back model train the face bigger than 5%, because I find it hard for the front blaze model to detect small face. 

Sorry for the late reply.
