### ISSUE TITLE
Got error during load mediapipe_simple_subgraph when mediapipe is an external dependency

### ISSUE THREAD

**Issue by d61h6k4** [google/mediapipe#610]
I tried to use mediapipe as external dependency in my project.
When I tried to load `mediapipe_simple_subgraph` to create subgraphs 
```
load(
    "@mediapipe//mediapipe/framework/tool:mediapipe_graph.bzl",
    "mediapipe_binary_graph",
)
```
I got the error, that `mediapipe/framework/tool` is not a package. 

I think that may happen because of `mediapipe_graph.bzl` load other .bzl files.

Is there a way how to load `mediapipe_simle_subgraph` function?

**Comment by hadon** [comment]
I found that some of the mediapipe bazel build rules fail when mediapipe is loaded from an external repo.  I've submitted a simple fix to the mediapipe repository.  This fix is included in this github release: https://github.com/google/mediapipe/commit/b6e680647cebf925ebc6a3f82b469d57c1c68da9. This fix is in files: mediapipe/framework/tool/build_defs.bzl and mediapipe/framework/tool/mediapipe_graph.bzl.  

-- Best Wishes, /-/adon
