### ISSUE TITLE
hand tracking on desktop using local video doesn't work

### ISSUE THREAD

**Issue by mathmax12** [google/mediapipe#613]
I followed the instruction for  TFlite Hand Tracking
"
To build the hand tracking demo using a TFLite model on desktop, use:

bazel build -c opt mediapipe/examples/desktop/hand_tracking:hand_tracking_tflite --define MEDIAPIPE_DISABLE_GPU=1
"
and run it using:
"
export GLOG_logtostderr=1

bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_tflite \
  --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop.pbtxt \
  --input_side_packets=input_video_path=/path/to/input/file,output_video_path=/path/to/output/file
"

Then I got the following errors: 
`I0415 09:39:44.156522 38859 simple_run_graph_main.cc:121] Initialize the calculator graph.
I0415 09:39:44.158710 38859 simple_run_graph_main.cc:134] Start running the calculator graph.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc86c005d80] moov atom not found
Unable to stop the stream: Inappropriate ioctl for device
VIDEOIO(cvCreateFileCapture_Images (filename)): raised C++ exception:

basic_string::substr: __pos (which is 140) > this->size() (which is 0)
E0415 09:39:44.211083 38859 simple_run_graph_main.cc:146] Failed to run the graph: CalculatorGraph::Run() failed in Run: 
Calculator::Open() for node "[OpenCvVideoDecoderCalculator, OpenCvVideoDecoderCalculator with output stream: input_video]" failed: ; Fail to open video file at /home/new_project/mediapipe/hand_tracking.mp4`

Did I miss anything?

**Comment by jiuqiant** [comment]
The error `Unable to stop the stream: Inappropriate ioctl for device` seems to be an OpenCV/FFmpeg  issue: https://stackoverflow.com/questions/41200201/opencv-unable-to-stop-the-stream-inappropriate-ioctl-for-device

**Comment by mathmax12** [comment]
Thanks. 
This works.

I wonder which type of GPU is supported (NVIDIA or AMD) for the hand tracking on desktop?

**Comment by mcclanahoochie** [comment]
as per each desktop GPU example readme, please check gpu support via https://mediapipe.readthedocs.io/en/latest/gpu.html#desktop-gpu-linux
the minimum requirement is OpenGL ES 3.1+

**Comment by jiuqiant** [comment]
Glad to hear that the problem is solved.

**Comment by mathmax12** [comment]
> as per each desktop GPU example readme, please check gpu support via https://mediapipe.readthedocs.io/en/latest/gpu.html#desktop-gpu-linux
> the minimum requirement is OpenGL ES 3.1+

Thanks for that!
