### ISSUE TITLE
hand tracking always lost when near the face

### ISSUE THREAD

**Issue by dolmens** [google/mediapipe#614]
i guess the training separate the hand and face deliberately.

**Comment by shraiwi** [comment]
This is most likely due to the lack of contrast between the skin on the hand and the skin on the face. A A higher contrast background will almost always work better.

**Comment by fanzhanggoogle** [comment]
Hi, exactly like @shraiwi said, since we are detecting palm area so it is indeed difficult to eliminate false positive on faces. It's a trade-off, possible to get better precision with lower speed by increasing the model size.
