### ISSUE TITLE
Error while generating aar_example build file in mediapipe

### ISSUE THREAD

**Issue by apoorvrocks** [google/mediapipe#615]
I got the following error while generating the aar_example BUILD file.
ERROR: Skipping '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar': no such package 'mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example': Unable to determine the local repository for directory /home/mrmojo/code/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example
WARNING: Target pattern parsing failed.
ERROR: no such package 'mediapipe/examples/an
![photo1](https://user-images.githubusercontent.com/22769603/79451800-c31e7880-8004-11ea-8160-12522054a517.PNG)
![photo2](https://user-images.githubusercontent.com/22769603/79451827-cdd90d80-8004-11ea-81a1-028cac145d81.PNG)

droid/src/java/com/google/mediapipe/apps/aar_example': Unable to determine the local repository for directory /home/mrmojo/code/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example

I am attaching the terminal screenshot as well as my aar build file for reference.

**Comment by anubhavagr27** [comment]
I am also facing the same problem. Cam someone help in resolving it?

**Comment by jiuqiant** [comment]
See the solution at https://github.com/google/mediapipe/issues/609#issuecomment-613595410
We will release the fix soon.

**Comment by jiuqiant** [comment]
Solved in https://github.com/google/mediapipe/commit/024f7bf0f1e74149ea92b942cf168ccddf317073.
