### ISSUE TITLE
Android: timestamp not specified or set to illegal value

### ISSUE THREAD

**Issue by brianm-sra** [google/mediapipe#616]
I ran into this issue while attempting to use MediaPipe Hand Tracker Graph
on a single Bitmap image

E Graph   : AddPacket for stream: input_video failed: invalid argument: Graph has errors:
E Graph   : ; In stream "input_video", timestamp not specified or set to illegal value: Timestamp::Unset().

My Android app code includes

Bitmap bitmap = BitmapFactory.decodeFile(path);
Packet mpPacket = mpAndroidPacketCreator.createRgbaImageFrame(bitmap);
mpGraph.addPacketToInputStream(INPUT_VIDEO_STREAM_NAME, mpPacket, mpPacket.getTimestamp());

Any suggestions ?

More details at https://groups.google.com/forum/#!topic/mediapipe/RDurxD8ERk8

My goal is to integrate the use of the FrameProcessor in an app that will use
a different framework(s) / library(ies) for camera inputs and rendering augmentations,
instead of relying completely on MediaPipe.

**Comment by jiqimaogou** [comment]
replace
```
mpGraph.addPacketToInputStream(INPUT_VIDEO_STREAM_NAME, mpPacket, mpPacket.getTimestamp());
```
with
```
mpGraph.addPacketToInputStream(INPUT_VIDEO_STREAM_NAME, mpPacket, System.nanotimes() / 1000);
```

**Comment by jiqimaogou** [comment]
you just create a Packet, which inputtimestamp is not yet setted. which value is `Timestamp::Unset()`
```
Packet mpPacket = mpAndroidPacketCreator.createRgbaImageFrame(bitmap);
```

**Comment by brianm-sra** [comment]
I changed the line to
mpGraph.addPacketToInputStream(INPUT_VIDEO_STREAM_NAME, mpPacket, System.currentTimeMillis());

Now I got past the specific issue, so I am going to close this thread.

I am now seeing a separate error, which I will follow up on next. Likely another unrelated issue, maybe another bug in my application code. If necessary, I will open a separate thread about that other issue.
