### ISSUE TITLE
Is it possible to implement Windows Desktop GPU Support using the ANGLE library?

### ISSUE THREAD

**Issue by shraiwi** [google/mediapipe#617]
Please correct me if I'm wrong about anything. My understanding of MediaPipe is limited :)

From what I've read, MediaPipe only supports GPU acceleration on Linux, Android, iOS, and the web. I want to create an application using the hand tracking demo which can run on Windows with a desktop GPU. However, it is not supported. I believe that by using the already-built [ANGLE library](https://github.com/google/angle), along with MediaPipe's OpenGL ES 3.1 backend, it is possible to implement Windows desktop support through OpenGL ES 3.1 emulation. Is this feasible, or is there something I'm missing? Thanks.

**Comment by jiuqiant** [comment]
Unfortunately, MediaPipe doesn't support Windows yet.

**Comment by shraiwi** [comment]
I am aware of that. I was wondering if it was possible to port it to Windows using ANGLE myself.

**Comment by ashikns** [comment]
To future visitors, yes it is possible. Angle can be used as the GL ES implementation. I was able to get it running on a windows machine with vulkan backend being used for Angle. In mediapipe source aside from GL ES itself, there are a few calls to the p_thread api as well that have to be changed, but it's trivial to replace them with std::thread equivalents.

**Comment by shraiwi** [comment]
That answers my question. Thank you!

**Comment by ashikns** [comment]
If anyone's interested here's how I changed mediapipe source to work with gpu on windows: [angle vulkan](https://github.com/google/mediapipe/commit/65e376a7b140e6011ae4a5a55f158a1e6f18393d), [pthread refactor](https://github.com/google/mediapipe/commit/f0905ead44fd185ce70546921bdd89b0c33b3a4f). Besides this there's a couple more compilation errors in the tensorflow library gpu code when compiling with msvc but they are simple syntax replacements. Note that these changes will likely only work on Windows.

I also faced an issue with angle-vulkan on my machine where GLSyncWait call doesn't work as intended with GL_SYNC_FLUSH_COMMANDS_BIT flag. Manually adding a glFlush before the wait fixed the issue.

**Comment by songwoh** [comment]
I have successfully run Face Detection model on Windows with Angle + Vulkan, as @ashikns has suggested.
However, I have experienced slower (..) inference using gl delegate on Face Detection than XNNPACK delegated graph by a large margin. Luckily, using OpenCL resulted in a slightly faster inference time, but still slower than XNNPACK.

I am wondering if there are others who has run TfLite on Windows with Vulkan + Angle combination have experienced slower inference time than running the graph with XNNPACK delegate. Any conjectures over this issue would be appreciated.

(The device I am using is Nvidia 3080 laptop GPU, if this helps.)

**Comment by ashikns** [comment]
@songwoh For the windows platform specifically I ended up converting the tflite model to onnx and running it against native winml. I had to ditch mediapipe at that point since writing a winml calculator was too much effort for me.

**Comment by songwoh** [comment]
@ashikns What was the primary reason for converting to winml inference engine instead of using TfLite? Did you experience the same performance issues as I have?

**Comment by ROBYER1** [comment]
Why is this issue closed when Windows (and also MacOS) GPU support isn't added yet? On these platforms it would be of great benefit for performance in different app use-cases. Does anyone have any update on plans for Mediapipe Windows/MacOS GPU support?
