### ISSUE TITLE
AAR build still got error 

### ISSUE THREAD

**Issue by sufiaji** [google/mediapipe#618]
Hi,
After implementing the changes [024f7bf](https://github.com/google/mediapipe/commit/024f7bf0f1e74149ea92b942cf168ccddf317073) mentioned in [issue 609](https://github.com/google/mediapipe/issues/609), I retried to build aar for face detection and hand tracking, but both still failed with error message:

**Hand tracking**
ERROR: /mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: Linking of rule '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:libmediapipe_jni.so' failed (Exit 254) clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -shared -o ... (remaining 588 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_hand_tracking_aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 618.062s, Critical Path: 599.90s
INFO: 218 processes: 212 processwrapper-sandbox, 6 worker.
FAILED: Build did NOT complete successfully

**Face detection**
ERROR: /mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: Executing genrule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar failed (Exit 127) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: line 7: zip: command not found
Archive:  /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/sandbox/processwrapper-sandbox/2146/execroot/mediapipe/bazel-out/k8-opt/bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/mp_face_detection_aar_dummy_app_unsigned.apk
   creating: lib/
   creating: lib/arm64-v8a/
   creating: lib/armeabi-v7a/
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 42.495s, Critical Path: 38.04s
INFO: 2 processes: 2 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

Any idea what happen?
Thanks

**Comment by sufiaji** [comment]
Hi,
Build command as stated in new android archive library readme [here](https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md)

bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar

Thanks!

**Comment by jiqimaogou** [comment]
## Hand tracking

the error is:
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)

clang program may be killed by the system, just try again.

## Face detection
the error is:
/bin/bash: line 7: zip: command not found

do you install the zip command? just print zip in the shell, if not, install zip command.

**Comment by sufiaji** [comment]
Hi,

Thanks for the reply. Yes I am now able to build AAR for Hand Tracking after trying sometime. And I just installed zip (sorry my bad), and build AAR for face detection but now I have different error message:

ERROR: /mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: Executing genrule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar failed (Exit 12) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Archive:  /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/sandbox/processwrapper-sandbox/37/execroot/mediapipe/bazel-out/k8-opt/bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/mp_face_detection_aar_dummy_app_unsigned.apk
   creating: lib/
   creating: lib/arm64-v8a/
   creating: lib/armeabi-v7a/
        zip warning: name not matched: jni/*/*.so

zip error: Nothing to do! (try: zip -r /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/sandbox/processwrapper-sandbox/37/execroot/mediapipe/bazel-out/k8-opt/bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/mp_face_detection_aar.aar . -i jni/*/*.so)
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 52.828s, Critical Path: 28.39s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Zip command is now error**

Please advise.
Thank you.

**Comment by jiuqiant** [comment]
That's weird. If hand tracking aar works, everything else should work as well. 
Do you put both hand tracking and face detection mediapipe aar rules in the same BUILD file? If that's the case, can you move the face detection aar rule to a BUILD file in another directory and build that face detection aar? My guess is this problem might be triggered by the existing build cache generated by the hand tracking aar.

**Comment by sufiaji** [comment]
Hi,

Thanks for replying. Anyway I re-create new docker container and re-build again everything from scratch and managed to print Hello World successfully. Now I got different error when trying to build AAR, both for hand tracking and face detection has same error below:

ERROR: /mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: Executing genrule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_hand_tracking_aar_binary_manifest_generator failed (Exit 127) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: $'\r': command not found
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_hand_tracking_aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 32.906s, Critical Path: 22.91s
INFO: 98 processes: 98 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

P.S. I change the content of file .../aar_example/BUILD to hand tracking or face detection everytime I want to try each one.

Any idea?
Thank you

**Comment by sufiaji** [comment]
Hi all,

Apparently the last error was because incompatible command in Docker Toolbox in Windows 7. So I managed to setup WSL and now its working. 
Thank you.
