### ISSUE TITLE
how to joint bounding box detection and keypoint regression at the same time?

### ISSUE THREAD

**Issue by aqsc** [google/mediapipe#619]
In the blazeface or blazepalm project, it can output the bounding box and keypoints  in one network at the same time. But now the SSD network in public can only output the bounding box throught the anchor regressions. How to modify the SSD network to regress keypoint while detecting the bounding boxes at the same time?

**Comment by fanzhanggoogle** [comment]
In the end, bounding box prediction is just regression on the coordinates (e.g. offset), you can simply add more points (e.g. face landmarks) to the regression.
