### ISSUE TITLE
Hand tracking on desktop?

### ISSUE THREAD

**Issue by Allgoerithm** [google/mediapipe#62]
Is it also possible to build the hand tracking also for a desktop system? If so, how?

**Comment by jiuqiant** [comment]
We do have video input processor,e.g., [OpenCvVideoDecoderCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/video/opencv_video_decoder_calculator.cc). We also have [desktop demos](https://github.com/google/mediapipe/blob/master/mediapipe/docs/object_detection_desktop.md) for object detection but not for the others.
The concern is we would like to run all the GPU calculators across desktop platforms but GPU support is not that ready yet. We are working on the other desktop demos and will have a better desktop coverage soon.

**Comment by wolterlw** [comment]
I have built a simple Python [demo](https://github.com/wolterlw/hand_tracking) and wrote instructions on how to built a tflite interpreter that supports custom operations needed.
So far it works for single images only, but adding video support shouldn't be hard.
The hard part would be building a desktop GPU delegate for tflite.

**Comment by Allgoerithm** [comment]
Wow, this is great!

**Comment by mgyong** [comment]
@Allgoerithm We have just [released v0.6.2](https://github.com/google/mediapipe/releases/tag/v0.6.2) that has [hand tracking desktop example](https://github.com/google/mediapipe/blob/master/mediapipe/docs/hand_tracking_desktop.md). Pls check it out!

**Comment by GTron-1729** [comment]
Hello Folks, I saw the process of building mediapipe and running hand tracking on desktop and all other relevant details, but I wanted to know whether there is a desktop app for hand tracking using mediapipe which is OS dependant? As in the process for windows, later it gives an error at this line  T{}.GetTypeName(), [] { return absl::make_unique<Holder<T>>(new T); })); as discussed in this issue https://github.com/google/mediapipe/issues/908 . So as a result, I can run those desktop examples on my Virtualbox mac but not on windows, So is there a desktop app which could do hand tracking using mediapipe and which could run on windows? @jiuqiant  @mgyong

**Comment by jiuqiant** [comment]
> Hello Folks, I saw the process of building mediapipe and running hand tracking on desktop and all other relevant details, but I wanted to know whether there is a desktop app for hand tracking using mediapipe which is OS dependant? As in the process for windows, later it gives an error at this line T{}.GetTypeName(), [] { return absl::make_unique<Holder>(new T); })); as discussed in this issue #908 . So as a result, I can run those desktop examples on my Virtualbox mac but not on windows. Also, on mac, it runs but the webcam fps seems very low, is there a way to improve that? Also is there a desktop app that could do hand tracking using mediapipe and which could run on windows? @jiuqiant @mgyong

For now you may do `git checkout v0.7.5`  to make the hand tracking demo work on Windows.

**Comment by GTron-1729** [comment]
Thanks @jiuqiant  but I cannot find v0.7.5?
