### ISSUE TITLE
Pixel coordinates of each hand keypoint for hand detection

### ISSUE THREAD

**Issue by chillcloud-dev** [google/mediapipe#622]
Hi MediaPipe team

i am working on hand gesture recognition and for my project I need the z - coordinates of each hand. 
I extract the z - coordinates by changing the subgraph _hand_landmark_gpu.pbtxt_
from  _model_path: "mediapipe/models/hand_landmark.tflite_"  ----->   _model_path: "mediapipe/models/hand_landmark_3d.tflite"_

and by applying the solution from #64, #99 and #159 I am able to extract the x, y and z fir each hand in each frame. 

So far so good !

**But**, the z- coordinate is pretty much useless since (according to [link](https://github.com/google/mediapipe/issues/156#issuecomment-552308838)) , the z-coordinate is normailzed relative to the wrist. And it doesn't have any unit and is in a range between +- 60 as far as i can tell. So there is no relevance of having this dimensional information.

Therefore, I want to use the depth channel of my realsense camera D415 to get the depth information by using the pixel coordinates of x, y of each key point.

Could you tell me, where I can extract the pixel coordinates of each key point in the camera frame ? 
Since mediapipe outputs the x, y coordinates is it possible to get also the pixel coordinates of each keypoint ? 

Thanks :)

best regards

**Comment by mahdinobar** [comment]
+1

**Comment by fanzhanggoogle** [comment]
For example, you get the coordinates [here](https://github.com/google/mediapipe/blob/024f7bf0f1e74149ea92b942cf168ccddf317073/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L116) and simply multiply by the input image size?

**Comment by chillcloud-dev** [comment]
@fanzhanggoogle 
already done that :+1: 

its the easiest way
