### ISSUE TITLE
Demo for baseline test of mediapipe handpose model on tflite compared with other methods

### ISSUE THREAD

**Issue by momo1986** [google/mediapipe#625]
Hello, dear Mediapipe guys.
Is there a demo to test the performance of Mediapipe handpose model like hand_landmark. tflite on popular dataset like rendered handpose dataset?
https://lmb.informatik.uni-freiburg.de/resources/datasets/RenderedHandposeDataset.en.html
Therefore, for further development, users can choose to customize the hand pose inference model.

**Comment by momo1986** [comment]
I notice there is one demo for use mediapipe hand pose inferece tf-lite model with hand detection and non-maximun supression processing.
https://github.com/wmpscc/HandTrackingAndLandmark-TFLite

However,  I find no example for test the mediapipe handpose inference model  
https://github.com/google/mediapipe/blob/master/mediapipe/models/hand_landmark.tflite
https://github.com/google/mediapipe/blob/master/mediapipe/models/hand_landmark_3d.tflite

Baseline test may help customize the mediapipe framework with other AI-paper  corresponding algorithm.

Thanks & Regards!

**Comment by Lebhoryi** [comment]
Have anyone could inference hand_landmark.tflite successfully?

raw image:

![hand](https://user-images.githubusercontent.com/28487306/117617749-930dbe80-b19f-11eb-8cac-aafb65732240.jpg)

api inference:

![image](https://user-images.githubusercontent.com/28487306/117617778-9dc85380-b19f-11eb-98ac-d574d86665f9.png)

my inference:

![image](https://user-images.githubusercontent.com/28487306/117617682-796c7700-b19f-11eb-938a-963ab78a62b3.png)

The output is three: 1. points  (1, 1, 63), 63 is (x, y, depth) * 21 points; 2. scores; 3. handness. However I dont konw how to process the points, And the predict is not good from the image.

**Comment by sgowroji** [comment]
Hi @momo1986, Are you still looking for the solution or found any observation. Please share us the update. Thanks!

**Comment by sgowroji** [comment]
Hi @momo1986, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity.
