### ISSUE TITLE
how to detect hand signs including “Thumb up”, closed fist, “OK”, “Rock” in android please reply me as soon as possible

### ISSUE THREAD

**Issue by iOS-dev-avinash** [google/mediapipe#626]
I want to detect hand signs including “Thumb up”, a closed fist, “OK”, “Rock”, I found only pam detection solution in this library can you please suggest me how I implement hand sign detection in my android app .

Thanks

**Comment by jiuqiant** [comment]
MediaPipe currently only takes care of hand landmarks detection. There are many ways to do recognition on top of the detection. Here is a RNN based approach made by rabBit64@: https://github.com/rabBit64/Sign-language-recognition-with-RNN-and-Mediapipe. JiHyunKim204@ also has some slides about this: https://www.slideshare.net/JiHyunKim204/sign-language-recognition-with-rnn-and-mediapipe

**Comment by fanzhanggoogle** [comment]
Hi, you can take a look at #296 for reference.

**Comment by abhimuktheeswarar** [comment]
> MediaPipe currently only takes care of hand landmarks detection. There are many ways to do recognition on top of the detection. Here is a RNN based approach made by rabBit64@: https://github.com/rabBit64/Sign-language-recognition-with-RNN-and-Mediapipe. JiHyunKim204@ also has some slides about this: https://www.slideshare.net/JiHyunKim204/sign-language-recognition-with-rnn-and-mediapipe

Those two link does not exist anymore.
