### ISSUE TITLE
Error while building aar file

### ISSUE THREAD

**Issue by apoorvrocks** [google/mediapipe#627]
I got the following error while trying to build aar file.

ERROR: no such package 'external': Error encountered while dealing with the WORKSPACE file: /home/mrmojo/mediapipe/WORKSPACE (Permission denied)
ERROR: no such package 'external': Error encountered while dealing with the WORKSPACE file: /home/mrmojo/mediapipe/WORKSPACE (Permission denied)

I am also attaching screenshot of my android workspace for your reference.
![p4](https://user-images.githubusercontent.com/22769603/79720971-45f24c80-82ff-11ea-89c9-cc0db541386d.PNG)

**Comment by jiuqiant** [comment]
Unfortunately, MediaPipe doesn't support Windows yet. See https://github.com/google/mediapipe/issues/91#issuecomment-529527848, https://github.com/google/mediapipe/issues/126, and https://github.com/google/mediapipe/issues/137
