### ISSUE TITLE
multi-hand tracking problem

### ISSUE THREAD

**Issue by xuchengggg** [google/mediapipe#628]
I am confused by the result, why there are three hands detected with one got by landmark from last frame. What is the strategy to deal with the boxes got by landmark from last frame and new detected boxes by multi-hand detection?[
![gesture_296](https://user-images.githubusercontent.com/40674552/79722530-ccfeef00-8316-11ea-8229-6dd2f7f32aee.png)
](url)

**Comment by fanzhanggoogle** [comment]
Hi,
The boxes are rendering for helping understanding the logic of pipeline. Sorry that actually causes confusion.
1) When there's no hand or number of hands is less than the target (e.g. 2 in this example). We first detects hand(palm) which is rendered in **green box with Palm text at the top left**.
2) We extend the detection box to a proper area that's good for the second model predicting the landmarks. Rendered in **purple**.
3) If a hand is tracked in previous frame and use that as the bounding box for the current frame, then the box is rendered in **Red**. 

For your last question, we associate previously tracked hands with newly detected hand by IOU, e.g. [AssociationCalculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/association_calculator.h).

In your example, in my understanding, the hand on the right side is a newly detected hands that doesn't have landmark predicted yet in this frame (the landmark is not good enough thus dropped by the **hand flag** ), the hand on the left side it does have a previous tracking box, thus even it has a new overlapping detection, the detection box is not used, but the previous bounding box **in red** is used for landmark prediction in this frame.
Hope it helps.

**Comment by xuchengggg** [comment]
Thank you for your reply. I have read the code of AssociationCalculator, I think the strategy is that when there is a previous bounding box (red) which have higher IOU with one bounding box (**purple**) predicted by multi_hand detection than min_similarity_threshold, then that **purple** box should be replaced by the **Red** box for landmark prediction. Is this correct? So in my picture, for left hand, there should be only one landmark result. However, as you can see there are more than 21 key points and some are overlaped, which means for left hand, both **purple** and **Red** bounding boxes are sent to landmark calculator. And this can be also proved by the next frame result. [
![gesture_297](https://user-images.githubusercontent.com/40674552/79814988-2bc57680-83b2-11ea-808b-8e0805fc6182.png)
](url)
Last pic is for frame 296, and this is frame 297. In this pic, there is only one **Red** box, which means multi-hand detection is not called. It also means for last frame, there are two landmark results. 
Another problem, for frame 296, there are two landmark results. So there should be two **Red** boxes in frame 297, how one of them was filtered out?

**Comment by mgyong** [comment]
Updated the hand model in v0.7.5. https://github.com/google/mediapipe/releases/tag/v0.7.5
Pls check it out and see if you still have problems

**Comment by fanzhanggoogle** [comment]
Hi, are you still seeing the same issue? Please re-open the issue if that's the case. We'll investigate more.
