### ISSUE TITLE
Run mediapipe/examples/desktop/hello_world:hello_world  Failed in Centos 

### ISSUE THREAD

**Issue by Ensteinjun** [google/mediapipe#629]
I prepared the environment according to the documentation, but something went wrong when running hello_world. 

OS:  CentOS Linux release 7.7.1908 (Core)
Bazel: 2.2.0

>     mediapipe/examples/desktop/hello_world:hello_world
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = a421e762fcced29d2a0128a0353fc105876e6942b86ea11a2a48375b14c8a628
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a421e762fcced29d2a0128a0353fc105876e6942b86ea11a2a48375b14c8a628"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /home/ec2-user/build_dir/mediapipe/WORKSPACE:33:1
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a tf_http_archive (rule definition at /root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/repo.bzl:134:19):
 - <builtin>
 - /root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/tensorflow/workspace.bzl:474:5
 - /root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/tensorflow/workspace.bzl:78:5
 - /home/ec2-user/build_dir/mediapipe/WORKSPACE:142:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/repo.bzl", line 110
		_apply_patch(ctx, <1 more arguments>)
	File "/root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/repo.bzl", line 68, in _apply_patch
		_execute_and_check_ret_code(ctx, <1 more arguments>)
	File "/root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
		fail(<1 more arguments>)
Non-zero return code(1) when executing 'patch -p1 -d /root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/com_google_protobuf -i /root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/protobuf/protobuf.patch':
Stdout:
Stderr: src/main/tools/process-wrapper-legacy.cc:58: "execvp(patch, ...)": No such file or directory
ERROR: /home/ec2-user/build_dir/mediapipe/mediapipe/examples/desktop/hello_world/BUILD:19:1: //mediapipe/examples/desktop/hello_world:hello_world depends on //mediapipe/calculators/core:pass_through_calculator in repository @ which failed to fetch. no such package '@com_google_protobuf//': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/repo.bzl", line 110
		_apply_patch(ctx, <1 more arguments>)
	File "/root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/repo.bzl", line 68, in _apply_patch
		_execute_and_check_ret_code(ctx, <1 more arguments>)
	File "/root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
		fail(<1 more arguments>)
Non-zero return code(1) when executing 'patch -p1 -d /root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/com_google_protobuf -i /root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/protobuf/protobuf.patch':
Stdout:
Stderr: src/main/tools/process-wrapper-legacy.cc:58: "execvp(patch, ...)": No such file or directory
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: no such package '@com_google_protobuf//': Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/repo.bzl", line 110
		_apply_patch(ctx, <1 more arguments>)
	File "/root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/repo.bzl", line 68, in _apply_patch
		_execute_and_check_ret_code(ctx, <1 more arguments>)
	File "/root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
		fail(<1 more arguments>)
Non-zero return code(1) when executing 'patch -p1 -d /root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/com_google_protobuf -i /root/.cache/bazel/_bazel_root/7f5b6af62d5dd14ae195b2cb8739e703/external/org_tensorflow/third_party/protobuf/protobuf.patch':
Stdout:
Stderr: src/main/tools/process-wrapper-legacy.cc:58: "execvp(patch, ...)": No such file or directory
INFO: Elapsed time: 20.903s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (13 packages loaded, 18 targets configured)
FAILED: Build did NOT complete successfully (13 packages loaded, 18 targets configured)
    currently loading: mediapipe/calculators/core ... (2 packages)

**Comment by jiuqiant** [comment]
The root cause seems to be `UnrecoverableHttpException GET returned 404 Not Found`.
Can you verify your network setting? You probably can find some useful solutions at https://github.com/google/mediapipe/issues/3 and https://github.com/google/mediapipe/issues/581.

**Comment by Ensteinjun** [comment]
Thanks, I have solved this problem. I upgraded gcc to 8.4, cmake to 3.17.1, python to 3.7.7, downgraded from opencv4 to 3.4.10.  The program can run normally, but the 404 warning still exists.
