### ISSUE TITLE
Consultation on two questions about Unity support

### ISSUE THREAD

**Issue by 1UPGame** [google/mediapipe#63]
Hi Google,

According to the documentation, we have compiled the development environment for ios and Android, and we have two technical questions to ask for advice:
The official android demo output is a directly rendered video texture. I want to know what I'm going to do if I just want to get landmark data.
The other is that I want to know if the iOS side is a. A library that uses c + directly.

Best Regards,
Richard

**Comment by mgyong** [comment]
Duplicate of #64

**Comment by chuoling** [comment]
Closing the issue and moving the discussion to #64.
