### ISSUE TITLE
Get top-n labels and timing for each segment in a local video

### ISSUE THREAD

**Issue by federicocau** [google/mediapipe#630]
I followed the tutorial to run model inference graph with a local video,

[https://github.com/google/mediapipe/tree/master/mediapipe/examples/desktop/youtube8m](url)

and I was wondering if it's possible to create a file that contains a sort of timeline made up of the top-n labels for each segment, kind of like a Kaggle solution.

In other words, since these labels are overlapped in the output video, I was considering if there exists a way to isolate the labels with their timings to get a readable file containing this information.

**Comment by jiuqiant** [comment]
It's doable.

First, make [the graph](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt) output `annotation_summary`.  
You need to 1) add `output_stream: "annotation_summary"` at the top of the graph and 2) modify `TopKScoresCalculator`.
```
diff --git a/mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt b/mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt
index 12ed2cb..361ddd8 100644
--- a/mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt
+++ b/mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt
@@ -3,6 +3,7 @@ input_side_packet: "input_video_path"
 input_side_packet: "output_video_path"
 input_side_packet: "segment_size"
 input_side_packet: "overlap"
+output_stream: "annotation_summary"

 node {
   calculator: "LocalFileContentsCalculator"
@@ -115,6 +116,7 @@ node {
   output_stream: "TOP_K_INDEXES:top_k_indexes"
   output_stream: "TOP_K_SCORES:top_k_scores"
   output_stream: "TOP_K_LABELS:top_k_labels"
+  output_stream: "SUMMARY:annotation_summary"
   node_options: {
     [type.googleapis.com/mediapipe.TopKScoresCalculatorOptions]: {
       top_k: 3
```

Then, run the binary with two more flags (--output_stream and -- output_stream_file):
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/youtube8m/model_inference \
  --calculator_graph_config_file=mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt \
  --output_stream=annotation_summary \
  --output_stream_file=/tmp/annotation_summary \
  --input_side_packets=input_sequence_example_path=/tmp/mediapipe/output.tfrecord,input_video_path=/absolute/path/to/the/local/video/file,output_video_path=/tmp/mediapipe/annotated_video.mp4,segment_size=5,overlap=4
```

**Comment by federicocau** [comment]
Thank you so much, it works like a charm! 💯

**Comment by federicocau** [comment]
> It's doable.
> 
> First, make [the graph](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt) output `annotation_summary`.
> You need to 1) add `output_stream: "annotation_summary"` at the top of the graph and 2) modify `TopKScoresCalculator`.
> 
> ```
> diff --git a/mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt b/mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt
> index 12ed2cb..361ddd8 100644
> --- a/mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt
> +++ b/mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt
> @@ -3,6 +3,7 @@ input_side_packet: "input_video_path"
>  input_side_packet: "output_video_path"
>  input_side_packet: "segment_size"
>  input_side_packet: "overlap"
> +output_stream: "annotation_summary"
> 
>  node {
>    calculator: "LocalFileContentsCalculator"
> @@ -115,6 +116,7 @@ node {
>    output_stream: "TOP_K_INDEXES:top_k_indexes"
>    output_stream: "TOP_K_SCORES:top_k_scores"
>    output_stream: "TOP_K_LABELS:top_k_labels"
> +  output_stream: "SUMMARY:annotation_summary"
>    node_options: {
>      [type.googleapis.com/mediapipe.TopKScoresCalculatorOptions]: {
>        top_k: 3
> ```
> 
> Then, run the binary with two more flags (--output_stream and -- output_stream_file):
> 
> ```
> GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/youtube8m/model_inference \
>   --calculator_graph_config_file=mediapipe/graphs/youtube8m/local_video_model_inference.pbtxt \
>   --output_stream=annotation_summary \
>   --output_stream_file=/tmp/annotation_summary \
>   --input_side_packets=input_sequence_example_path=/tmp/mediapipe/output.tfrecord,input_video_path=/absolute/path/to/the/local/video/file,output_video_path=/tmp/mediapipe/annotated_video.mp4,segment_size=5,overlap=4
> ```

Thank you so much, it works like a charm! 💯

**Comment by jiuqiant** [comment]
Glad to hear that!
