### ISSUE TITLE
How can we increase the FPS or processing speed?

### ISSUE THREAD

**Issue by veetechh** [google/mediapipe#631]
We tried mediapipe tensorflow version hand detection on web. But the speed is low. Any workaround to increase the speed?

**Comment by fanzhanggoogle** [comment]
The biggest bottleneck is that the detection model runs really slow on CPU thus causing the lagging. We are working on a new pipeline that can run the detector asynchronously so it won't interfere the real time video stream. 
For the tracking part, you can try e.g. PacketResamplerCalculator to reduce the FPS of running the model.
