### ISSUE TITLE
Installing using Docker

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#632]
When run docker build --tag=mediapipe .
The command '/bin/sh -c mkdir /bazel &&     wget --no-check-certificate -O /bazel/installer.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh" &&     wget --no-check-certificate -O  /bazel/LICENSE.txt "https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE" &&     chmod +x /bazel/installer.sh &&     /bazel/installer.sh  &&     rm -f /bazel/installer.sh' returned a non-zero code: 4

**Comment by chensisi0730** [comment]
--2020-04-21 03:45:54--  (try:18)  https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... failed: Connection refused.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... failed: Cannot assign requested address.
Retrying.

**Comment by jiuqiant** [comment]
Is this a network issue?
You probably can find some useful solutions at https://github.com/google/mediapipe/issues/3 and https://github.com/google/mediapipe/issues/581.

**Comment by jiuqiant** [comment]
Based on https://github.com/google/mediapipe/issues/644, I believe the problem is solved? Feel free to reopen it if it's not the case.
