### ISSUE TITLE
making a calculator with proto options

### ISSUE THREAD

**Issue by NestorGL** [google/mediapipe#634]
I'm trying to make a calculator that put a text label in the specified position.
I created a C++ file to implement the calculator and a proto file for the options (simplified version):
>syntax = "proto2";
>
>package mediapipe;
>
>import "mediapipe/framework/calculator.proto";
>
>message MyLabelCalculatorOptions {
>  extend CalculatorOptions {
>    optional MyLabelCalculatorOptions ext = 400000000; // <unique id, e.g. the CL#>
>  }
>  required string label = 1;
>
>  // Absolute position of the text label.
>  optional int32 x = 2;
>  optional int32 y = 3;
>
>  // Normalized position of the text label. Value is within [0, 1].
>  optional float norm_x = 4;
>  optional float norm_y = 5;
>  ...
>}

Next error occurs when I try to build my project:
>mediapipe/.../myCalculators/my_Label_calculator.proto:9:45: "mediapipe.CalculatorOptions" does not declare 400000000 as an extension number.

I'ld like to know how can I obtain (find, calculate, ...) this number. Or, please, correct if I'm wrong somewhere.

Thanks.

P.S.
For "hardcoded" text label options, inside the source of the calculator, everything works fine.
I also plan to be able to pass these options as a SidePackets in the future.

**Comment by NestorGL** [comment]
I set:
optional MyLabelCalculatorOptions ext = 30000;
And calculator was compiled without errors.
I set it again
optional MyLabelCalculatorOptions ext = 400000000;
And all is ok! Funnily. Perhaps in the code I accidentally put an extra 0.
Are there any rules for choosing this number? (0<ext< 2^29)?

**Comment by mcclanahoochie** [comment]
The 'ext' number can be pretty much whatever you like (within range (0<ext< 2^29-1)), but most importantly, it must be unique among all the protos used in your app.
https://developers.google.com/protocol-buffers/docs/proto?hl=en#extensions

Random trivia: the numbers used in MediaPipe are simply derived from an internal commit hash when creating that proto.

**Comment by NestorGL** [comment]
Thanks for the answer.
Do you know is there a simple way to check if the 'ext' number is already in use?

**Comment by brucechou1983** [comment]
@NestorGL 

grep -r "CalculatorOptions ext =" $MEDIAPIPE_ROOT/mediapipe/calculators | grep $TARGET_NUMBER
