### ISSUE TITLE
Set the python3.7 as default version is necessary on ios?

### ISSUE THREAD

**Issue by yizhaoyanbo** [google/mediapipe#638]
I wanna to run mediapipe on my iphone though xcode. I have read the document about how to run it on ios platform . 
But the Step3 in the document said that "Set Python 3.7 as the default Python version and install the Python "six" library". I have to  change my default python2.7 version and set python3.7  as default on macos. I don't think it is a safe operation because other system tools may need python2.7. 
So does it is necessary to use python3.7 to run the demo successfully?

**Comment by jiuqiant** [comment]
Python is used to configure MediaPipe's TensorFlow dependency during the build process. 
Last time when we built MediaPipe with Python 2.7, Bazel reported an error. So, we recommend using Python 3.7 to avoid such Python incompatibility issues.  It's possible that TensorFlow solved this issue recently. Feel free to stay with Python 2.7 and let us know if you face any issue. Thanks.

**Comment by yizhaoyanbo** [comment]
@jiuqiant 
Thanks for your answer. It has no problem to use python2.7.  The mediapipe demos have run successfully on my iphone. 

And I have another question. The following function 'ParseFromArray' has been used by several demos, but I can't find its declare and defination.
`  // Parse the graph config resource into mediapipe::CalculatorGraphConfig proto object.
  mediapipe::CalculatorGraphConfig config;    
config.ParseFromArray(data.bytes, data.length);`

**Comment by jiuqiant** [comment]
Thanks for the verification!

Regarding your question:
CalculatorGraphConfig is a Google Protobuf  message. ParseFromArray() is a Google Protobuf Message/MessageLite API: https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message_lite. In MediaPipe, you can find the proto and cc proto build rules of CalculatorGraphConfig at https://github.com/google/mediapipe/blob/master/mediapipe/framework/BUILD#L36 and https://github.com/google/mediapipe/blob/master/mediapipe/framework/BUILD#L128.
