### ISSUE TITLE
Compiler error on ios

### ISSUE THREAD

**Issue by yizhaoyanbo** [google/mediapipe#639]
I have done all the steps following mediapipe_ios_setup.md and create xcode project successfully. But when I want to compile the EdgeDetectionOnGpuAPP, the following error occurs. 

`
Showing Recent Messages
ERROR: /Users/riddick/Documents/3rdParty/mediapipe/mediapipe/examples/ios/edgedetectiongpu/BUILD:24:1: ProcessEntitlementsFiles mediapipe/examples/ios/edgedetectiongpu/EdgeDetectionGpuApp_entitlements.entitlements failed (Exit 1) plisttool failed: error executing command 
`

Does anyone have the same problem? thanks.

Bazel version 2.0.0
xcode verison 11.3
macos catalina 10.15.3

**Comment by yizhaoyanbo** [comment]
This coused by the  bundle_id difference.
I change the default bundle_id = "com.**google.mediapipe.**FaceDetectionGpu" to bundle_id = "com.**myorg**.FaceDetectionGpu" . And it is runing successfully.

**Comment by ethanyanjiali** [comment]
This tutorial is crap: https://google.github.io/mediapipe/getting_started/hello_world_ios.html#initial-minimal-application-setup
