### ISSUE TITLE
confidence score of palm detection model

### ISSUE THREAD

**Issue by Akshaysharma29** [google/mediapipe#641]
Hi team,
I am using the palm detection model. From this repo due to custom_op issue 

https://github.com/metalwhale/hand_tracking

But the model confidence is very low and sometimes more than 100, The prediction of the palm is also not very good.

The model have 2 outputs :
one have dimension :[   1, 2944,    18]
second have dimension :[   1, 2944,    1]
I am using the second output for its confidence.

Any suggestion?

**Comment by fanzhanggoogle** [comment]
Hi, have you tried our official implementation on the cases where you find the palm detection is not very good? Sorry that we do not have the bandwidth to check the quality 3rd party implementation. But if you find issues with our released model/pipeline, we would be more than happy to help out.

**Comment by djthegr8** [comment]
In the released models, the output shape is `(1,2944,19)`
How do I use this to draw bounding boxes????
