### ISSUE TITLE
MediaPipe Android Archive Library Protobuf issues

### ISSUE THREAD

**Issue by jen-co** [google/mediapipe#643]
First of all thank you so much for creating this, documenting it and providing examples so excellently. The speed and accuracy of the hand tracking is really incredible.

I managed to edit the handtrackinggpu example to apply some basic gesture detection and built it successfully with bazel. However, I would ideally like to be able to continue to edit the code in Android studio so I followed the information detailed [here](https://mediapipe.readthedocs.io/en/latest/android_archive_library.html). Here are the contents of my BUILD file:

load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_hand_tracking_aar",
    calculators = ["//mediapipe/graphs/hand_tracking:mobile_calculators",
            "//mediapipe/graphs/hand_tracking:detection_mobile_calculators"
    ],
)

I managed to get the project to build in Android studio and run on my phone but it crashes at this line:
`NormalizedLandmarkList landmarks = NormalizedLandmarkList.parseFrom(landmarksRaw);`

with the following error:
JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.NoSuchMethodError: No static method registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V in class Lcom/google/protobuf/GeneratedMessageLite; or its super classes (declaration of 'com.google.protobuf.GeneratedMessageLite' appears in /data/app/com.example.testinglayouts-tIutMNWs1OPj920hcr9pSw==/base.apk)
2020-04-23 15:18:31.929 14053-14292/com.example.testinglayouts A/.testinglayout: java_vm_ext.cc:542]   at void com.google.mediapipe.formats.proto.LandmarkProto$NormalizedLandmarkList.<clinit>() (LandmarkProto.java:1684)
2020-04-23 15:18:31.929 14053-14292/com.example.testinglayouts A/.testinglayout: java_vm_ext.cc:542]   at com.google.mediapipe.formats.proto.LandmarkProto$NormalizedLandmarkList com.google.mediapipe.formats.proto.LandmarkProto$NormalizedLandmarkList.parseFrom(byte[]) (LandmarkProto.java:1451)
2020-04-23 15:18:31.929 14053-14292/com.example.testinglayouts A/.testinglayout: java_vm_ext.cc:542]   at void com.example.testinglayouts.MainActivity.lambda$onCreate$1$MainActivity(com.google.mediapipe.framework.Packet) (MainActivity.java:112)
2020-04-23 15:18:31.929 14053-14292/com.example.testinglayouts A/.testinglayout: java_vm_ext.cc:542]   at void com.example.testinglayouts.-$$Lambda$MainActivity$jAnpiGNoKLxfedqW8zZNmKf3DiM.process(com.google.mediapipe.framework.Packet) (lambda:-1)

When I try to debug it and step into the line it appears to crash in LandmarkProto.class here:
`LandmarkProto.NormalizedLandmarkList defaultInstance = new LandmarkProto.NormalizedLandmarkList();`

with the exception: Method threw 'java.lang.UnsupportedOperationException' exception. Cannot evaluate com.google.mediapipe.formats.proto.LandmarkProto$NormalizedLandmarkList.toString()

I would also like to add that I cloned the multi hands tracking repo (https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example) and managed to get that built and running with no issues. I have compared very carefully to see if there are any build setting differences between the two but they seem pretty much the same so I am at a loss with what is causing this crash. If I comment out the code to parse the packets for landmarks the app runs fine. 

Thanks again!
Jennifer

**Comment by jiuqiant** [comment]
One thing you can try is to switch to use the full proto library in gradle. Here is a similar issue that is solved by this approach: https://github.com/google/mediapipe/issues/624#issuecomment-616719563. Full proto library is definitely more powerful than the lite version. Maybe the missing piece is in the full proto library? 

Let me ask a few questions to  understand your use case better. What is `landmarksRaw` and how do you get it? It seems like you want to make a NormalizedLandmarkList object in Java, can you share a toy example to help me reproduce your issue (if it's too long, you can have the example in your own repo and I can clone it)?

**Comment by jen-co** [comment]
Wow thank you for such a quick and helpful response!

The solution worked!
I replaced:
implementation 'com.google.protobuf:protobuf-lite:3.0.1'
with 
implementation 'com.google.protobuf:protobuf-java:3.11.4'

in the app build.gradle file.

Perhaps you could update the documentation [here](https://mediapipe.readthedocs.io/en/latest/android_archive_library.html) to reflect this.

Thanks again so much!

**Comment by jiuqiant** [comment]
Glad to hear that the problem is solved.
Thanks for the suggestion. We will update the documentation in the coming release.

**Comment by jiuqiant** [comment]
The documentation fix is in https://github.com/google/mediapipe/commit/7bad8fce626ab3b0f41d818afac4df1e757c0969.

**Comment by seasiainfotech** [comment]
Want to remove the overlay from the Hand tracking media pipe, Any constructive ways to resolve it? 

Please help

Thanks in advance.
