### ISSUE TITLE
How to implement real time gesture recognition in multi hand tracking module

### ISSUE THREAD

**Issue by apoorvrocks** [google/mediapipe#646]
How can we modify mediapipe code to get real time gesture recognition of a basic set of gestures. I ran multi hand tracking apk but it could not recognise basic gestures as was promised in https://ai.googleblog.com/2019/08/on-device-real-time-hand-tracking-with.html .  It only shows the landmark points and does not label the gesture.

**Comment by jiuqiant** [comment]
Please take a look at the comments of https://github.com/google/mediapipe/issues/626. Thanks.
