### ISSUE TITLE
How to use ScaleImageCalculator for GPU?

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#647]
There are many different types of scaling algorithms in ScaleImageCalculator but it doesn't seem to support GPU.

**Comment by jiuqiant** [comment]
ScaleImageCalculator is CPU only. If you are looking for a calculator supporting both CPU and GPU, please take a look at [ImageTransformationCalculator](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/calculators/image/image_transformation_calculator.cc#L15).

**Comment by yxchng** [comment]
@jiuqiant ImageTransformationCalculator only support bilinear resizing?

**Comment by yxchng** [comment]
@jiuqiant Any updates?
