### ISSUE TITLE
How to profile GPU calculators?

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#649]
I wish to profile the running time of calculator running on GPU with OpenGL. I tried timing using C++ or NDK timer but it doesn't seem to work. How can I profile the elapsed time properly?

**Comment by mcclanahoochie** [comment]
Hi,

Unfortunately MediaPipe doesn't currently have a simple way to profile GPU calculators, **yet**. We will be providing a nice set of profiling tools planned sometime over the next few releases. 

Meanwhile, on iOS, there are Apple's Instruments tools, and on Android, there is some very basic GPU tools in Android studio, or, some manual OpenGL profiling primitives ( `glQueryCounterEXT`, `glGetQueryObjectui64vEXT`, `glGetQueryivEXT` ) one could use to build a simple GL timer class. 

For generic timing, you can use absl [time.h](https://github.com/wubo0067/cpp/blob/17d06e83a0b71aa76c47832d8821636ae30e4aca/absl/time/time.h) (included with mediapipe) to make simple duration timers inside each calculator's 'Process()' function...  example (not exact syntax):
```
MyCalc::Process(){
  const auto start = absl::Now();
  ...
  RunInGlContext(...
    <GL stuff>
     glFinish(); // added for perf measurement, but should be removed in production
  ...)
  ...
  const auto end = absl::Now();
  const auto duration = end-now;
  LOG(INFO) << absl::Milliseconds(duration);
}
```

Again, stay tuned for MediaPipe updates related to profiling/tracing tools.

**Comment by yxchng** [comment]
@mcclanahoochie Ok I will wait for the next few releases.

**Comment by mgyong** [comment]
@yxchng We have released [experimental profiling and tracing](https://github.com/google/mediapipe/blob/master/mediapipe/docs/tracer.md) at [viz.mediapipe.dev](https://viz.mediapipe.dev) with [v0.7.5](https://github.com/google/mediapipe/releases/tag/v0.7.5)

**Comment by brucechou1983** [comment]
Many users don't have the authority to upload log files. Is there any plan to release the profiling & tracing tool for local debugging?

As an advanced Tensorflow user, I want to migrate a big parts of our production system to MediaPipe for better pipeline management. But currently lacking of tool chain for debugging and profiling stops me from do it.

**Comment by mgyong** [comment]
@brucechou1983  We do not plan to release profiling and tracing tool for local debugging as we plan to constantly improve on the visualization and profiling. Users would benefit more from a hosted tool versus a local debug
We currently do not store or identify any log files when you upload it to the tracer. Hence, there should not be any security or privacy concerns
What is the use case for MediaPipe in terms of pipeline management?

**Comment by brucechou1983** [comment]
I'm just curious that how do you improve the tool without storing/analyzing the uploaded data? If you don't touch users' data, what's the difference between a hosted tool versus a local tool?

For pipeline management, I mean building a modulized and visualizable pipeline for complex media inputs/outputs. This is important when you have multiple input sources processed by multiple models with different pre/post-processing. I think MediaPipe does a really good job at framework design.
