### ISSUE TITLE
Bazel Sync filed issue 

### ISSUE THREAD

**Issue by RealBBakGosu** [google/mediapipe#65]
I tried uploading an example of Mediapipe to my mobile phone using android_studio on Ubuntu 18.04 but I got a syntax error in my Build file and I'm not sure how to deal with it.
I think I read the contents of install.md and followed it correctly. And if I install and use bazel directly in Ubuntu without using Android Studio, it works fine.

![스크린샷, 2019-08-29 16-36-25](https://user-images.githubusercontent.com/52807219/63922494-c4079780-ca7f-11e9-89be-728bff878dcf.png)

**Comment by jiuqiant** [comment]
Please follow [the new instruction](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#setting-up-android-studio-with-mediapipe) to set up Android Studio with MediaPipe again.  You probably need to run `bazel clean --expunge` in the mediapipe directory to clean up the cache anyway. Thanks.

**Comment by jiuqiant** [comment]
Closing due to lack of recent activity.
