### ISSUE TITLE
For opencv4-linux has issue of  undefined reference 

### ISSUE THREAD

**Issue by momo1986** [google/mediapipe#656]
Hello, dear mediapipe guys.

I want to run the C++ desktop version in Ubuntu workstations, but met some errors for opencv library.

I am not sure whether it is version issue:

Here is log:

> INFO: Writing tracer profile to '/root/.cache/bazel/_bazel_root/509bde1a513861381fb993356a2062f9/command.profile.gz'
> INFO: Analyzed target //mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_tflite_wrap_finger (0 packages loaded, 0 targets configured).
> INFO: Found 1 target...
> ERROR: /slow/junyan/mediapipe_findpiano_usage/mediapipe/examples/desktop/multi_hand_tracking/BUILD:18:1: Linking of rule '//mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_tflite_wrap_finger' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_tflite_wrap_finger-2.params
> 
> Use --sandbox_debug to see verbose messages from the sandbox
> bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/wrap_finger_gpu_main/wrap_finger_gpu_main.o:wrap_finger_gpu_main.cc:function cv::Mat::~Mat(): error: undefined reference to 'cv::Mat::deallocate()'
> bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/wrap_finger_gpu_main/wrap_finger_gpu_main.o:wrap_finger_gpu_main.cc:function cv::Mat::~Mat(): error: undefined reference to 'cv::fastFree(void*)'
> bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/wrap_finger_gpu_main/wrap_finger_gpu_main.o:wrap_finger_gpu_main.cc:function RunMPPGraph(std::unique_ptr<mediapipe::CalculatorGraph, std::default_delete<mediapipe::CalculatorGraph> >): error: undefined reference to 'cv::fastFree(void*)'
> bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/wrap_finger_gpu_main/wrap_finger_gpu_main.o:wrap_finger_gpu_main.cc:function RunMPPGraph(std::unique_ptr<mediapipe::CalculatorGraph, std::default_delete<mediapipe::CalculatorGraph> >): error: undefined reference to 'cv::flip(cv::_InputArray const&, cv::_OutputArray const&, int)'
> bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/wrap_finger_gpu_main/wrap_finger_gpu_main.o:wrap_finger_gpu_main.cc:function RunMPPGraph(std::unique_ptr<mediapipe::CalculatorGraph, std::default_delete<mediapipe::CalculatorGraph> >): error: undefined reference to 'cv::Mat::copyTo(cv::_OutputArray const&) const'
> bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/wrap_finger_gpu_main/wrap_finger_gpu_main.o:wrap_finger_gpu_main.cc:function RunMPPGraph(std::unique_ptr<mediapipe::CalculatorGraph, std::default_delete<mediapipe::CalculatorGraph> >): error: undefined reference to 'cv::getTickCount()'
> bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/wrap_finger_gpu_main/wrap_finger_gpu_main.o:wrap_finger_gpu_main.cc:function RunMPPGraph(std::unique_ptr<mediapipe::CalculatorGraph, std::default_delete<mediapipe::CalculatorGraph> >): error: undefined reference to 'cv::getTickFrequency()'
> bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/wrap_finger_gpu_main/wrap_finger_gpu_main.o:wrap_finger_gpu_main.cc:function RunMPPGraph(std::unique_ptr<mediapipe::CalculatorGraph, std::default_delete<mediapipe::CalculatorGraph> >): error: undefined reference to 'cv::fastFree(void*)'
> bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/wrap_finger_gpu_main/wrap_finger_gpu_main.o:wrap_finger_gpu_main.cc:function RunMPPGraph(std::unique_ptr<mediapipe::CalculatorGraph, std::default_delete<mediapipe::CalculatorGraph> >): error: undefined reference to 'cv::fastFree(void*)'
> bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/wrap_finger_gpu_main/wrap_finger_gpu_main.o:wrap_finger_gpu_main.cc:function RunMPPGraph(std::unique_ptr<mediapipe::CalculatorGraph, std::default_delete<mediapipe::CalculatorGraph> >): error: undefined reference to 'cv::Mat::deallocate()'
> bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/wrap_finger_gpu_main/wrap_finger_gpu_main.o:wrap_finger_gpu_main.cc:function RunMPPGraph(std::unique_ptr<mediapipe::CalculatorGraph, std::default_delete<mediapipe::CalculatorGraph> >): error: undefined reference to 'cv::Mat::deallocate()'
> bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/wrap_finger_gpu_main/wrap_finger_gpu_main.o:wrap_finger_gpu_main.cc:function RunMPPGraph(std::unique_ptr<mediapipe::CalculatorGraph, std::default_delete<mediapipe::CalculatorGraph> >): error: undefined reference to 'cv::Mat::deallocate()'
> bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_cropping_calculator/image_cropping_calculator.o:image_cropping_calculator.cc:function mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::Mat::updateContinuityFlag()'
> bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_cropping_calculator/image_cropping_calculator.o:image_cropping_calculator.cc:function mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::Mat::copyTo(cv::_OutputArray const&) const'
> bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::Mat::updateContinuityFlag()'
> bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::Mat::copyTo(cv::_OutputArray const&) const'
> bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::flip(cv::_InputArray const&, cv::_OutputArray const&, int)'
> bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::Mat::copyTo(cv::_OutputArray const&) const'
> bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
> bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::copyMakeBorder(cv::_InputArray const&, cv::_OutputArray const&, int, int, int, int, int, cv::Scalar_<double> const&)'
> bazel-out/k8-opt/bin/mediapipe/framework/formats/_objs/image_frame_opencv/image_frame_opencv.o:image_frame_opencv.cc:function mediapipe::formats::MatView(mediapipe::ImageFrame const*): error: undefined reference to 'cv::Mat::Mat(int, int const*, int, void*, unsigned long const*)'
> bazel-out/k8-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetGpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&): error: undefined reference to 'cv::Mat::create(int, int const*, int)'
> bazel-out/k8-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetGpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&): error: undefined reference to 'cv::Mat::operator=(cv::Scalar_<double> const&)'
> bazel-out/k8-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetGpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&): error: undefined reference to 'cv::Mat::create(int, int const*, int)'
> bazel-out/k8-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetGpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&): error: undefined reference to 'cv::Mat::operator=(cv::Scalar_<double> const&)'
> bazel-out/k8-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetCpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&, mediapipe::ImageFormat_Format*): error: undefined reference to 'cv::Mat::create(int, int const*, int)'
> bazel-out/k8-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetCpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&, mediapipe::ImageFormat_Format*): error: undefined reference to 'cv::Mat::operator=(cv::Scalar_<double> const&)'
> bazel-out/k8-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetCpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&, mediapipe::ImageFormat_Format*): error: undefined reference to 'cv::Mat::create(int, int const*, int)'
> bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::AdoptImage(cv::Mat*): error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
> bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRectangle(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::RotatedRect::points(cv::Point_<float>*) const'
> bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawFilledRectangle(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::RotatedRect::points(cv::Point_<float>*) const'
> bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRoundedRectangle(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
> bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawFilledRoundedRectangle(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
> collect2: error: ld returned 1 exit status
> Target //mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_tflite_wrap_finger failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 0.944s, Critical Path: 0.73s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully

I am not sure whether opencv3 is still needed for linux version.

From the homepage, your team is not against the usage of opencv-4.

Thus, is it a version issue?

How can I resolve it?

Thanks & Regards!

**Comment by momo1986** [comment]
I use apt-get install in Ubuntu package, can work. 
It looks like the opencv-3 not opencv-4.
Thanks & Regards!

**Comment by jiuqiant** [comment]
Glad to hear that the problem is solved.

If you need opencv4, first find out where the header files and the libraries are after the installation. Then, update the "linux_opencv" new_local_repository rule in [WORKSPACE](https://github.com/google/mediapipe/blob/master/WORKSPACE) and "opencv" cc_library rule in [opencv_linux.BUILD](https://github.com/google/mediapipe/blob/master/third_party/opencv_linux.BUILD) accordingly. For example, if OpenCV 4 is installed in "/usr/local/", you need to update them like the following:

```
new_local_repository(
    name = "linux_opencv",
    build_file = "@//third_party:opencv_linux.BUILD",
    path = "/usr/local",
)

cc_library(
    name = "opencv",
    srcs = glob(
        [
            "lib/libopencv_core.so",
            "lib/libopencv_highgui.so",
            "lib/libopencv_imgcodecs.so",
            "lib/libopencv_imgproc.so",
            "lib/libopencv_video.so",
            "lib/libopencv_videoio.so",
        ],
    ),
    hdrs = glob(["include/opencv4/**/*.h*"]),
    includes = ["include/opencv4/"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
```
