### ISSUE TITLE
knift template matching build index file get empty 

### ISSUE THREAD

**Issue by zzipis** [google/mediapipe#659]
when i try to build my template matching index file as below:
bazel-bin/mediapipe/examples/desktop/template_matching/template_matching_tflite \
    --calculator_graph_config_file=mediapipe/graphs/template_matching/index_building.pbtxt \
    --input_side_packets="file_directory=<template image directory>,file_suffix='png',output_index_filename=<output index filename>"

i put the template image in the directory  (the attach file is the template image)
and the output index file is a empty file with 0 byte
no error message
my environment:arch linux ,opencv4
![template image file](https://user-images.githubusercontent.com/3350649/80357937-444ff800-88ae-11ea-819e-27de55b09841.png)

**Comment by xiong-jie-y** [comment]
@zzipis Hi! I faced the same problem.
Try replacing `'png'` with `png`. Also you can see GLOG output with `GLOG_logtostderr=1`.

The command I used for generating template index of book images is
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/template_matching/template_matching_tflite     --calculator_graph_config_file=mediapipe/graphs/template_matching/index_building.pbtxt     --input_side_packets="file_directory=mediapipe/book_images,file_suffix=png,output_index_filename=book_index.pb"
```

**Comment by jiuqiant** [comment]
Thanks @xiong-jie-y  for pointing out the issue.
We will fix the documentation in the coming release.

**Comment by zzipis** [comment]
Many many  thanks to  @xiong-jie-y , it worked now,it take me few days read the document again and again,you must be angel.
