### ISSUE TITLE
Issue in building AAR archive

### ISSUE THREAD

**Issue by sobhan87068** [google/mediapipe#660]
Hi,
I'm trying to use mediapipe in my Android application which i developed using gradle but unfortunately when i try to follow the instructions on creating AAR im not able to build binary graph as illustrated in 
https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md
the error goes as follows:
bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:binary_graph
INFO: Build options --cpu, --crosstool_top, --define, and 2 more have changed, discarding analysis cache.
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:binary_graph (0 packages loaded, 3985 targets configured).
INFO: Found 1 target...
ERROR: /mnt/sda/AndroidProjects/mediapipe/mediapipe/graphs/face_detection/BUILD:67:1: Linking of rule '//mediapipe/graphs/face_detection:mobile_gpu_binary_graph_text_to_binary_graph' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/host/bin/mediapipe/graphs/face_detection/mobile_gpu_binary_graph_text_to_binary_graph-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/host/bin/external/com_github_glog_glog/_objs/glog/utilities.o:utilities.cc:function google::GetStackTrace(void**, int, int) [clone .part.0]: error: undefined reference to '_Ux86_64_getcontext'
bazel-out/host/bin/external/com_github_glog_glog/_objs/glog/utilities.o:utilities.cc:function google::GetStackTrace(void**, int, int) [clone .part.0]: error: undefined reference to '_ULx86_64_init_local'
bazel-out/host/bin/external/com_github_glog_glog/_objs/glog/utilities.o:utilities.cc:function google::GetStackTrace(void**, int, int) [clone .part.0]: error: undefined reference to '_ULx86_64_step'
bazel-out/host/bin/external/com_github_glog_glog/_objs/glog/utilities.o:utilities.cc:function google::GetStackTrace(void**, int, int) [clone .part.0]: error: undefined reference to '_ULx86_64_get_reg'
bazel-out/host/bin/external/com_github_glog_glog/_objs/glog/utilities.o:utilities.cc:function google::GetStackTrace(void**, int, int) [clone .part.0]: error: undefined reference to '_ULx86_64_step'
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:binary_graph failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 45.198s, Critical Path: 0.21s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
i have tried building Face Mesh which also gives a similar error in creating binary graph

My environment specifications are as follows:
Manjaro KDE 20.0
linux kernel 5.6.7
bazel 2.2.0 (AUR version)
Android Studio 3.6.3
Android SDK (api versions 21 through 29 installed)
Android NDK 20.0.5594570 (installed via SDK manager)

**Comment by jiuqiant** [comment]
This is related to libunwind. To solve this, you need to append `--define libunwind=true` to the Bazel build command.

**Comment by sobhan87068** [comment]
silly of me :) i had used this argument in building aar but forgot to add it in graph build command. thank you for quick response.
