### ISSUE TITLE
Train YouTube-8M model with new labels given the features extracted with mediapipe

### ISSUE THREAD

**Issue by federicocau** [google/mediapipe#661]
I'm trying to train the Y8M baseline model with new labels but I can't understand how.

Once I get the features at point 5 of the tutorial to train the baseline model

![Cattura](https://user-images.githubusercontent.com/17594934/80398821-8847fa80-88b8-11ea-99bf-78af66c440a6.PNG)

and also let's assume that I extended the feature in the vocabulary.csv present in the Kaggle challenge [https://www.kaggle.com/c/youtube8m-2019/data](url),

how can I associate the features with custom (new) ground truth labels in the training pipeline? I mean, launching the training with these features, how does the model recognize and associate the new labels?

**Comment by joeyhng** [comment]
You could create your own MediaSequence metadata with custom ground-truth labels by modifying [generate_input_sequence_example.py](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/youtube8m/generate_input_sequence_example.py) and add ```ms.set_clip_label_string(...)``` and/or ```ms.set_clip_label_string(...)```. See more [here](https://github.com/google/mediapipe/blob/master/mediapipe/util/sequence/media_sequence.py#L44).

**Comment by federicocau** [comment]
> You could create your own MediaSequence metadata with custom ground-truth labels by modifying [generate_input_sequence_example.py](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/youtube8m/generate_input_sequence_example.py) and add `ms.set_clip_label_string(...)` and/or `ms.set_clip_label_string(...)`. See more [here](https://github.com/google/mediapipe/blob/master/mediapipe/util/sequence/media_sequence.py#L44).

Thank you a bunch! So if I have to insert three segments, for example:

```
  ms.set_segment_start_timestamp((0, 5000000, 10000000), metadata)  # in microseconds
  ms.set_segment_end_timestamp((5000000, 10000000, 15000000), metadata)
  ms.set_segment_label_index((35, 47, 19), metadata)
  ms.set_segment_label_string(("run", "jump", "drill"), metadata)
```
I put the segment start value in _segment_start_timestamp_  and in the same position of _segment_end_timestamp_ the segment end value, right? 
So I have that "run" varies between 0 and 5 seconds, "jump" between 5 and 10 seconds, and "drill" between 10 and 15 seconds.
