### ISSUE TITLE
Face Mesh undefined errors

### ISSUE THREAD

**Issue by Iorek73** [google/mediapipe#666]
Hi, 

I'm trying to get the Face Mesh up and running. Running into a mound of gcc issues and undefined errors. Perhaps related to #261 and #268

**Test Environment**
Ubuntu 20.0.04 (Virtual Box)
OpenCV 3.4.10-dev : Run setup_opencv.sh
bazel 3.1.0
gcc 9.3.0
Install mediapipe and install related utils with the [guide](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md)
Hello World desktop example works okay

**Build with bazel**
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/face_mesh:face_mesh_cpu`

**Output**
`mark@mark-VirtualBox:~/Desktop/mediapipe-master$ bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/face_mesh:face_mesh_cpu
INFO: Analyzed target //mediapipe/examples/desktop/face_mesh:face_mesh_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/mark/Desktop/mediapipe-master/mediapipe/examples/desktop/face_mesh/BUILD:27:1: Linking of rule '//mediapipe/examples/desktop/face_mesh:face_mesh_cpu' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/face_mesh/face_mesh_cpu-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph() [clone .cold]: error: undefined reference to 'cv::String::deallocate()'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph() [clone .cold]: error: undefined reference to 'cv::String::deallocate()'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph() [clone .cold]: error: undefined reference to 'cv::String::deallocate()'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph() [clone .cold]: error: undefined reference to 'cv::String::deallocate()'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::open(int)'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to 'cv::String::allocate(unsigned long)'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to 'cv::namedWindow(cv::String const&, int)'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::open(cv::String const&)'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoWriter::open(cv::String const&, int, double, cv::Size_<int>, bool)'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoWriter::write(cv::Mat const&)'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to 'cv::String::allocate(unsigned long)'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to 'cv::imshow(cv::String const&, cv::_InputArray const&)'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to 'cv::String::allocate(unsigned long)'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to 'cv::String::allocate(unsigned long)'
bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRectangle(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::rectangle(cv::Mat&, cv::Rect_<int>, cv::Scalar_<double> const&, int, int, int)'
bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawFilledRectangle(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::fillConvexPoly(cv::Mat&, cv::Point_<int> const*, int, cv::Scalar_<double> const&, int, int)'
bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawFilledRectangle(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::rectangle(cv::Mat&, cv::Rect_<int>, cv::Scalar_<double> const&, int, int, int)'
bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawGradientLine(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::rectangle(cv::Mat&, cv::Rect_<int>, cv::Scalar_<double> const&, int, int, int)'
bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawText(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::putText(cv::_InputOutputArray const&, cv::String const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_cropping_calculator/image_cropping_calculator.o:image_cropping_calculator.cc:function mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::getPerspectiveTransform(cv::_InputArray const&, cv::_InputArray const&)'
bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::getRotationMatrix2D(cv::Point_<float>, double, double)'
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/face_mesh:face_mesh_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.787s, Critical Path: 0.58s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
mark@mark-VirtualBox:~/Desktop/mediapipe-master$ bazel --version
bazel 3.1.0
mark@mark-VirtualBox:~/Desktop/mediapipe-master$ python3
Python 3.8.2 (default, Mar 13 2020, 10:14:16) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> print(cv2.__version__)
3.4.10-dev
>>> 
mark@mark-VirtualBox:~/Desktop/mediapipe-master$ 
`

Tried all manner of sudo ldconfig, to no avail. Any ideas greatly appreciated.

**Comment by jiuqiant** [comment]
I think you need to find out where your opencv header files and libraries are and then modify WORSPACE and third_party/opencv_linux.BUILD accrodingly. Please take a look at https://github.com/google/mediapipe/issues/603#issuecomment-614181023 and https://github.com/google/mediapipe/issues/656#issuecomment-620099175.

**Comment by Iorek73** [comment]
Ah yes, that makes sense. Sometimes it's difficult to see the forest for the trees. 

Location
`pkg-config --cflags opencv` 
`-I/usr/local/include/opencv -I/usr/local/include`

and _exactly_ as you had in #656 

In WORKSPACE
```
new_local_repository(
    name = "linux_opencv",
    build_file = "@//third_party:opencv_linux.BUILD",
    path = "/usr/local",
)
```

In opncv_linux.BUILD
```
cc_library(
    name = "opencv",
    srcs = glob(
        [
            "lib/libopencv_core.so",
            "lib/libopencv_highgui.so",
            "lib/libopencv_imgcodecs.so",
            "lib/libopencv_imgproc.so",
            "lib/libopencv_video.so",
            "lib/libopencv_videoio.so",
        ],
    ),
    hdrs = glob(["include/opencv4/**/*.h*"]),
    includes = ["include/opencv4/"],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
```

And finally a successful output
```
mark@mark-VirtualBox:~/Desktop/mediapipe-master$ bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/face_mesh:face_mesh_cpu
INFO: Analyzed target //mediapipe/examples/desktop/face_mesh:face_mesh_cpu (5 packages loaded, 1271 targets configured).
INFO: Found 1 target...
Target //mediapipe/examples/desktop/face_mesh:face_mesh_cpu up-to-date:
  bazel-bin/mediapipe/examples/desktop/face_mesh/face_mesh_cpu
INFO: Elapsed time: 7.225s, Critical Path: 0.92s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed successfully, 11 total actions
```

Many, many thanks mate.

**Comment by jiuqiant** [comment]
Glad to hear that the problem is solved!
