### ISSUE TITLE
Custom tensorflow model in mediapipe confusion/error

### ISSUE THREAD

**Issue by pablovela5620** [google/mediapipe#667]
So I'm trying to get a model I trained in python and port it over into mediapipe, but I have confusions about what calculators I need to use to perform inference. After going through the different calculators I have the following questions

First I have the checkpoint files `.ckpt`, a frozen graph with weights `.pb` and the `.pbtxt` file. 
My graph looks like this 
```
input_stream: "xyz"
output_stream: "theta"

# Converts Eigen::Matrix in Tensorflow Tensor.
node: {
  calculator: "MatrixToTensorCalculator"
  input_stream: "xyz"
  output_stream: "xyz_tensor"
}

node {
   calculator: "TensorFlowSessionFromFrozenGraphCalculator"
   output_side_packet: "SESSION:session"
   options {
        [mediapipe.TensorFlowSessionFromFrozenGraphCalculatorOptions.ext]: {
        graph_proto_path: "mediapipe/models/ik_net/iknet.pb"
        tag_to_tensor_names {
            key: "XYZ_TENSOR"
            value: "xyz:0"
         }
        tag_to_tensor_names {
            key: "THETA_TENSOR"
            value: "import/network/theta:0"
       }
    }
   }
}
node {
    calculator: "TensorFlowInferenceCalculator"
    input_side_packet: "SESSION:session"
    input_stream: "XYZ_TENSOR:xyz_tensor"
    output_stream: "THETA_TENSOR:theta"
}
```
I get the following error whenever I try to get this working
```
2020-04-28 17:51:55.063027: E external/org_tensorflow/tensorflow/core/common_runtime/session.cc:66] Not found: No session factory registered for the given session options: {target: "" config: } Registered factories are {}.
Segmentation fault (core dumped)
```

I can't use tflite as some of the ops I need are not supported and wanted to see if I could get this working in mediapipe.

My build file looks as follows

```
load(
    "//mediapipe/framework/tool:mediapipe_graph.bzl",
    "mediapipe_binary_graph",
)

licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

exports_files(glob([
    "*.pbtxt",
]))

cc_library(
    name = "desktop_tf_calculators",
    deps = [
        "//mediapipe/calculators/tensorflow:matrix_to_tensor_calculator",
        "//mediapipe/calculators/tensorflow:tensorflow_session_from_frozen_graph_calculator",
        "//mediapipe/calculators/tensorflow:tensorflow_inference_calculator",
    ],
)
```

**Comment by mcclanahoochie** [comment]
Hi,
I would try to model how the youtube8m example uses tensorflow calculators in the [graph](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/youtube8m/feature_extraction.pbtxt) and dependencies in the BUILD files: [binary](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/youtube8m/BUILD) , [graphs](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/youtube8m/BUILD)
and see what dependencies or calculator options are missing (relevant to your project)

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
