### ISSUE TITLE
How to improve the accuracy of  plam detection 

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#668]
in hand-tracking demo ,
When there is no hand in the field of vision, there are landmarks  constantly. How to improve the accuracy of  plam detection ?

**Comment by fanzhanggoogle** [comment]
We always output landmarks. So in the case when there's false positive from the detector, the landmark model will run once and drop the tracking by the hand flag. In the next frame, it'll re-trigger the detection. So the correct way is to filter out non-hand is to use the hand flag score, if the score give low values, then the hand landmark should be dropped and could not be trusted.
