### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.NoSuchMethodError: No static method registerDefaultInstance

### ISSUE THREAD

**Issue by zzw937089989** [google/mediapipe#669]
When I run my Android multihandtrackinggpu code, it is wrong and the error is 
`JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.NoSuchMethodError: No static method registerDefaultInstance(Ljava/lang/Class;Lcom/google/protobuf/GeneratedMessageLite;)V in class Lcom/google/protobuf/GeneratedMessageLite; or its super classes (declaration of 'com.google.protobuf.GeneratedMessageLite' appears in /data/app/com.example.mediapipehandtracking-1/base.apk)
    art/runtime/java_vm_ext.cc:410]   at void com.google.mediapipe.formats.proto.LandmarkProto$NormalizedLandmarkList.<clinit>() (LandmarkProto.java:1684)
    art/runtime/java_vm_ext.cc:410]   at void com.example.mediapipehandtracking.MainActivity.lambda$onCreate$0$MainActivity(com.google.mediapipe.framework.Packet) (MainActivity.java:108)
    art/runtime/java_vm_ext.cc:410]   at void com.example.mediapipehandtracking.-$$Lambda$MainActivity$Ebp1jy5s4WkhQ-ZwIjp9HiYcpYI.process(com.google.mediapipe.framework.Packet) (lambda:-1)`
hoping for your answer,thinks

**Comment by jiuqiant** [comment]
How do you build the multihandtrackinggpu APK? 

If you use AAR, please take a look at https://github.com/google/mediapipe/issues/643#issuecomment-618578061. Also, we updated https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md accordingly.

**Comment by zzw937089989** [comment]
I solved it, there is a package written wrong  implementation 'com.google.protobuf:protobuf-java:3.11.4'', bacause I Ireferenced a blog but its wrond
