### ISSUE TITLE
Creating custom calculators externally

### ISSUE THREAD

**Issue by jadarve** [google/mediapipe#67]
Hi,

Is there a way to code custom calculators outside of mediapipe's repository?

As an example, I coded an RGB to Gray calculator using OpenCV on Linux. If I place the package inside `mediapipe/examples/desktop/opencv_sample` with the `BUILD` file below, the `cc_binary` compiles successfully

```python
licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//mediapipe/examples:__subpackages__"])

load("//mediapipe/framework/port:build_config.bzl", "mediapipe_cc_proto_library")

proto_library(
    name = "rgb_to_gray_proto",
    srcs = ["calculators/rgb_to_gray.proto"],
    visibility = ["//visibility:public"],
    deps = ["//mediapipe/framework:calculator_proto"],
)

mediapipe_cc_proto_library(
    name = "rgb_to_gray_cc_proto",
    srcs = ["calculators/rgb_to_gray.proto"],
    cc_deps = ["//mediapipe/framework:calculator_cc_proto"],
    visibility = ["//visibility:public"],
    deps = [":rgb_to_gray_proto"],
)

cc_library(
    name = "rgb_to_gray",
    srcs = ["calculators/rgb_to_gray.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        ":rgb_to_gray_cc_proto",
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/formats:image_frame",
        "//mediapipe/framework/formats:image_frame_opencv",
        "//mediapipe/framework/formats:video_stream_header",
        "//mediapipe/framework/port:file_helpers",
        "//mediapipe/framework/port:opencv_highgui",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:opencv_video",
        "//mediapipe/framework/port:ret_check",
        "//mediapipe/framework/port:source_location",
        "//mediapipe/framework/port:status",
        "//mediapipe/framework/tool:status_util",
        "@com_google_absl//absl/strings",
    ],
    alwayslink = 1,
)

cc_binary(
    name = "opencv_sample",
    srcs = ["src/opencv_sample.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        ":rgb_to_gray",
        "//mediapipe/calculators/core:pass_through_calculator",
        "//mediapipe/framework:calculator_graph",
        "//mediapipe/framework/port:logging",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
    ],
)
```

Now I want to build the sample example but outside of `mediapipe` repository. I created a new repository `calculator_test`. I copy-pasted mediapipe's `WORKSPACE` and `third-party` files into the repo so that I can link against all dependencies.

Additionally, I added mediapipe as a local repository in the `WORKSPACE` as:

```
local_repository(
    name = "mediapipe",
    path = "/home/juan/git/mediapipe"
)
```
I also changed all the paths refering to mediapipe from `//mediapipe` to `@mediapipe//mediapipe` to point to the external local repo.

When I run `bazel run //opencv_sample` I get the following error:

```
bazel run //opencv_sample
ERROR: /home/juan/git/calculator_test/opencv_sample/BUILD:12:1: in cc_library rule //opencv_sample:rgb_to_gray_cc_proto: target '@mediapipe//mediapipe/framework:calculator_cc_proto' is not visible from target '//opencv_sample:rgb_to_gray_cc_proto'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//opencv_sample:opencv_sample' failed; build aborted: Analysis of target '//opencv_sample:rgb_to_gray_cc_proto' failed; build aborted
```

I tried removing that dependency but other errors appeared.

**Comment by jiuqiant** [comment]
Hi, the error message show that "calculator_cc_proto" is not visible. I guess you can fix it by modifying the line 142 of the [framework BUILD file](https://github.com/google/mediapipe/blob/master/mediapipe/framework/BUILD) to be ``` visibility = ["//visibility:public"],```. We will fix it in the next release. Thanks for reporting!

**Comment by jiuqiant** [comment]
FYI, the visibility of "calculator_cc_proto" becomes public in https://github.com/google/mediapipe/commit/af676420555f60c71c481f597d5ed3aa3b4f6789

**Comment by jiuqiant** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by Tachionstrahl** [comment]
The visibility of calculator_cc_proto hasn't changed yet. I still get following error, when trying to add the dependency `cc_deps = ["@mediapipe//mediapipe/framework:calculator_cc_proto"],` from external project:

target '@mediapipe//mediapipe/framework:calculator_cc_proto' is not visible from target '//calculators:sign_lang_prediction_calculator_cc_proto'. Check the visibility declaration of the former target if you think the dependency is legitimate
