### ISSUE TITLE
Using local compiled tensorflow source version.

### ISSUE THREAD

**Issue by tjtanaa** [google/mediapipe#671]
Could I know how can I use a native local compiled tensorflow source code in the mediapipe environment, instead of from loading tensorflow as bazel external repository? I have some custom operation that I would like to create thus I need to expose mediapipe to the tensorflow. There are some modifications that I would like to do to the tensorflow source.

**Comment by jiuqiant** [comment]
I tried to make MediaPipe depend on libtensorflow_framework.so and libtensorflow_cc.so directly a while ago. Unfortunately, I ran into endless undefined symbol issues and gave up.

One alternative is that you can make MediaPipe depend on your local tensorflow source code. To do this, please modify [the org_tensorflow rule](https://github.com/google/mediapipe/blob/master/WORKSPACE#L122) in the WORKSPACE file to be a [new_local_repository](https://docs.bazel.build/versions/master/be/workspace.html#new_local_repository) that points to your local TensorFlow directory.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by tjtanaa** [comment]
Could I know where can I find the SHA265 of the tensorflow version that I am interested in?

**Comment by jiuqiant** [comment]
@tjtanaa, you can comment out the sha256 field. It's just for sanity check.
