### ISSUE TITLE
Autoflip runs out of memory and gets Killed

### ISSUE THREAD

**Issue by abrar71** [google/mediapipe#672]
8GB RAM, 8 vCPUs on Google Cloud
I'm running the basic autoflip command with aspect ratio 2.35:1, it starts as usual but memory keeps ramping up and up until the process is killed. I've attached the video in a ZIP file and the error logs.
[1080.zip](https://github.com/google/mediapipe/files/4566576/1080.zip)
[autoflip_mem_killed.txt](https://github.com/google/mediapipe/files/4566587/autoflip_mem_killed.txt)
![image](https://user-images.githubusercontent.com/13979201/80848139-a05aa980-8c2b-11ea-9aae-706e32ca6b6d.png)

**Comment by jiuqiant** [comment]
Can you add `num_threads: 8` or `num_threads: 4` in https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt and retry?

**Comment by abrar71** [comment]
> Can you add `num_threads: 8` or `num_threads: 4` in https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt and retry?

I've tried both `num_threads: 8` & `num_threads: 4` but it still has the same behavior of memory exhaustion.
[logs_with_num_thread_8.txt](https://github.com/google/mediapipe/files/4567675/logs_with_num_thread_8.txt)

Earlier I had tried the same command with default [autoflip_graph.pbtxt](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt) on a **16 vCPU 104 RAM** VM and Autoflip was using around 30GB of memory for successful execution.

**Comment by jiuqiant** [comment]
I just tested your video and it runs ok on a macbook pro with 16GB memory. The maximum memory usage is about 6.3GB and most of the time autoflip uses 3GB memory.

<img width="1591" alt="Screen Shot 2020-05-03 at 11 37 07 AM" src="https://user-images.githubusercontent.com/3359144/80922544-b99a4d80-8d32-11ea-93e3-03d0bd055d8c.png">

<img width="1587" alt="Screen Shot 2020-05-03 at 11 37 23 AM" src="https://user-images.githubusercontent.com/3359144/80922553-c5860f80-8d32-11ea-85ed-b1cca7435b8a.png">

**Comment by jiuqiant** [comment]
If you get a chance, can you change the value of `max_queue_size` to a small positive number (1, 2, ... 5) at https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt#L3 and rerun the binary?

**Comment by abrar71** [comment]
Changing `max_queue_size` to small positive number causes it to automatically increase over time due to deadlocks.

**Comment by sgowroji** [comment]
Hi @abrar71, Could you please respond if you are looking resolution for the above query. Thanks!

**Comment by peternaf** [comment]
Hi @abrar71 , @jiuqiant 
Were you able to find a stable solution for this problem?

**Comment by abrar71** [comment]
I didn't use autoflip after the submission of this issue, so I don't know if the issue is still there.
Although I did attach the input files and how to reproduce the issue.

**Comment by peternaf** [comment]
@abrar71 Yes, could understand - it's hard to implement something with autoflip in this state.

@sgowroji \ @jiuqiant  - If it is of interest to you - I would like to join as a collaborator to the project, start working on AutoFlip - making it stable and also contribute to other parts of the project

**Comment by abrar71** [comment]
@peternaf I'm busy these days but would love to collaborate in my spare time.

**Comment by peternaf** [comment]
@abrar71 sure thing. Let me know how I could join the collaborators team and how you prioritise things.
Also - saw there is a slack channel but couldn't join because I don't have a mail box with a google.com domain
