### ISSUE TITLE
Desktop multi hand tracking not working

### ISSUE THREAD

**Issue by anubhavagr27** [google/mediapipe#674]
when I give this command:
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_cpu \
>     --calculator_graph_config_file=mediapipe/graphs/hand_tracking/multi_hand_tracking_desktop_live.pbtxt
it is working fine showing ouput:
I0503 14:26:10.497131  4237 demo_run_graph_main.cc:62] Initialize the calculator graph.
I0503 14:26:10.519405  4237 demo_run_graph_main.cc:66] Initialize the camera or load the video.
I0503 14:26:10.519477  4237 demo_run_graph_main.cc:73] Initialize the camera
I0503 14:26:11.744102  4237 demo_run_graph_main.cc:98] Start running the calculator graph.
I0503 14:26:11.754180  4237 demo_run_graph_main.cc:103] Start grabbing and processing frames.
I0503 14:26:24.846035  4237 demo_run_graph_main.cc:147] Shutting down.
I0503 14:26:24.888409  4237 demo_run_graph_main.cc:167] Success!
but while giving input video and running the command:
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_cpu \--calculator_graph_config_file=mediapipe/graphs/hand_tracking/multi_hand_tracking_desktop_live.pbtxt --input_video_path=input.mp4 --output_video_path=output.mp4
it gives an error:
I0503 14:26:37.281049  4253 demo_run_graph_main.cc:62] Initialize the calculator graph.
I0503 14:26:37.302511  4253 demo_run_graph_main.cc:66] Initialize the camera or load the video.
I0503 14:26:37.302597  4253 demo_run_graph_main.cc:70] load the video.
E0503 14:26:37.576143  4253 demo_run_graph_main.cc:165] Failed to run the graph: ; capture.isOpened()(mediapipe/examples/desktop/demo_run_graph_main.cc:76)

**Comment by jiuqiant** [comment]
The error is the video file can't be opened. Where do you put the input.mp4? I suggest using absolute path.

**Comment by anubhavagr27** [comment]
It is in the same directory.

**Comment by anubhavagr27** [comment]
I used the absolute path too but it is throwing same error.

**Comment by jiuqiant** [comment]
If the file path is valid, then that means OpenCV (with its underlying video decoder) can't open the video file. As you mentioned in the problem description, the camera works ok with MediaPipe and OpenCV. So my guess is the OpenCV installation and the MediaPipe OpenCV config are correct. Then, it's highly likely that the video decoder (like ffmpeg) installed with OpenCV may have some problem. It might be a good idea to write a toy C++ example to verify if OpenCV can do video decoding on your machine.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
