### ISSUE TITLE
Dockerfile has an error now

### ISSUE THREAD

**Issue by DaeHyeonNam** [google/mediapipe#675]
In installing with Docker using ubuntu, when I type "docker build --tag=mediapipe .", it occurs error like "unable to locate python-pip".
This error occurs because there is new ubuntu 20.04.
so "FROM ubuntu:latest" it makes refer to the 20.04 which does not support python-pip(probably)
Thus after I modified the first line of Dockerfile "From ubuntu:latest" to "From ubuntu:18.04", it works.

**Comment by allenday** [comment]
fixed in this PR
https://github.com/google/mediapipe/pull/678

**Comment by PradeepSinghMakwana** [comment]
I am trying to use docker image on Ubuntu 20.04. I get the same error as above. Should I change "FROM ubuntu:latest" line in docker file?

**Comment by PradeepSinghMakwana** [comment]
I replaced the Dockerfile file with below code file and renamed it to "Dockerfile"...
[Dockerfile_changed.txt](https://github.com/google/mediapipe/files/4627665/Dockerfile_changed.txt)

**Comment by baiyueran** [comment]
This problem still exists when run "FROM unbuntu:latest".

**Comment by PradeepSinghMakwana** [comment]
Ubuntu 20.04 do not have python2, so things like from future and pip will fail. Creating a symbolic link to pip from pip3 and installing future from pip3 still seems to solve the issue for a while.
