### ISSUE TITLE
How to convert mediapipe coordinates into Unity world space coordinates?

### ISSUE THREAD

**Issue by BoneFlat** [google/mediapipe#676]
Hi MediaPipe Team, i'm trying to convert 21 landmarks into unity 3d world space.
I follow these step to do that:
Step 1: I follow  @eknight7  instruction from #454 to get NormalizedRect in image coordinates. 
Step 2: Because "NormalizedLandmark" is landmark location in HandRect coordinates, so i can convert 21 point into image coordinates. 
Step 3: I'm using "ScreenToWorldSpace" method in Unity to convert 21 point in image coordinate to 3d world space with a specifi depth (depth = 3 in my case).

But the final result in Unity has a little discrepancies , you can see in image below.
Can you give me some advise to convert the landmarks. And i also want to know is there a solution to get the real depth?

![Screenshot_20200503-200241_AR Single](https://user-images.githubusercontent.com/62471272/80915429-782e9000-8d7c-11ea-8b12-761048439510.jpg)

**Comment by CalebGreer** [comment]
I have been trying to use mediapipe with Unity as well and was wondering do you have mediapipe running within Unity or are you getting the landmarks somewhere else and then sending it to Unity?

**Comment by BoneFlat** [comment]
@CalebGreer, i'm building aar (android archive library) and use it as plugin for Unity

**Comment by CalebGreer** [comment]
@BoneFlat Oh, I had tried that but couldn't get it to work. Would you mind sharing your solution or how you got the aar to work within Unity?

**Comment by BoneFlat** [comment]
@CalebGreer, i'm following "the left" solution at https://github.com/google/mediapipe/issues/36#issuecomment-524477282. 
For plugin, I'm using 2 aar plugin , one is mediapipe aar we have build, another is wrote to hold some method like "InitGraph, StartGraph, SetInputBitmap, GetLandMark ...".
In Unity, i get texture from webcamtexture, convert it to byte array and use byte array for plugin's input

**Comment by SwatiModi** [comment]
Hey @BoneFlat, 
Can you tell more about the another AAR you used with InitGraph, StartGraph functions? I checked out FrameProcessor.java but unable to understand how to use it with the byte array input to mediapipe from unity.

**Comment by justinduynguyen** [comment]
i'm considering that how to stream a byte array from unity webcam  to mediapipe ? Any solution? Thank you.

**Comment by brianm-sra** [comment]
@BoneFlat did you make any progress on this?

**Comment by BoneFlat** [comment]
Sorry all for the late answer, i made a simple project that show how to use mediapipe with Unity, i also made a unity package, you can use this for another project. I can found all here: https://gitlab.com/thangnh.sas/mediapipe-unity-hand-tracking

**Comment by JackieNek** [comment]
I made a solution to solve the depth and made a simple game base on that here: https://gitlab.com/JackieNek/single-hand-tracking . You can see demo here: https://youtu.be/paZ3sXtKTq8

**Comment by brianm-sra** [comment]
@BoneFlat  : in your ARHand.cs file I found this code:
for (int i = 0; i < 21; i++) {
            float xScreen = Screen.width * ((arr[i * 3 + 1] - 0.5f * (1 - c)) / c);
            float yScreen = Screen.height * (arr[i * 3]);
            this.landmarks[i] = cam.ScreenToWorldPoint(new Vector3(xScreen, yScreen, arr[i * 3 + 2] / 80 + 0.4f));
        }

Would you be willing to share how you determined that those formulas were correct?
In particular for X and Z

X - 0.5f * (1 - c)) / c
 Z / 80 + 0.4f

Were these specific to camera calibration on your particular camera device ?

**Comment by justinduynguyen** [comment]
Thank you in advance guys.

**Comment by TheBricktop** [comment]
is it possible to build analogically build the media pipe as a 
plugin for desktop?

**Comment by tutu5110** [comment]
All very cool! @BoneFlat

**Comment by sachinjambhulkar** [comment]
@BoneFlat Thank you ! The package is working like a charm. The only drag i have seen in FPS... i feel this has to be taken up to run over the GPU for better performance.

**Comment by danieljtrujillo** [comment]
@sachinjambhulkar could you describe in detail how you implemented it?

**Comment by sachinjambhulkar** [comment]
@danieljtrujillo clone the repo: https://gitlab.com/thangnh.sas/mediapipe-unity-hand-tracking. navigate to the base directory of this project, right click over the file "MediapipeUnityPackage.unitypackage" and open with the Unity.

You can observe the complete project with all assets getting imported to unity Editor. Open the SampleScene.unity and you can make it run on your preferred platform / end device target.

**Comment by zhouwei5113** [comment]
> @BoneFlat : in your ARHand.cs file I found this code:
> for (int i = 0; i < 21; i++) {
> float xScreen = Screen.width * ((arr[i * 3 + 1] - 0.5f * (1 - c)) / c);
> float yScreen = Screen.height * (arr[i * 3]);
> this.landmarks[i] = cam.ScreenToWorldPoint(new Vector3(xScreen, yScreen, arr[i * 3 + 2] / 80 + 0.4f));
> }
> 
> Would you be willing to share how you determined that those formulas were correct?
> In particular for X and Z
> 
> X - 0.5f * (1 - c)) / c
> Z / 80 + 0.4f
> 
> Were these specific to camera calibration on your particular camera device ?

@brianm-sra Do you have any ideas about the formula？

**Comment by AlanWuJinliang** [comment]
@JackieNek @BoneFlat  do you know why i cant show the hand bone in my android phone?

**Comment by AlanWuJinliang** [comment]
> @BoneFlat Thank you ! The package is working like a charm. The only drag i have seen in FPS... i feel this has to be taken up to run over the GPU for better performance.

are you sure this demo can show hand bone?

**Comment by mostafamdy** [comment]
@BoneFlat  Hi thanks for  this package its great 
but I have a problem on it. it works with 5 fps
so how can I make this package work on GPU to be faster or did you have another package that can work on GPU?
