### ISSUE TITLE
remove landmark

### ISSUE THREAD

**Issue by androiiiid** [google/mediapipe#680]
I want to remove the landmark from the camera in the palm recognition project. How should I do this? Thanks

**Comment by jiuqiant** [comment]
Yes, it can be done by removing `input_stream: "landmark_render_data"`or `input_stream: "VECTOR:0:multi_hand_landmarks_render_data"` from AnnotationOverlayCalculator config.

Depends on your application is on top of multihand or single hand tracking and the graph is on cpu or gpu, you need to modify one of the the following graphs:
https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_cpu.pbtxt#L142
https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_gpu.pbtxt#L142
https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/graphs/hand_tracking/subgraphs/renderer_cpu.pbtxt#L99
https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/graphs/hand_tracking/subgraphs/renderer_gpu.pbtxt#L99
