### ISSUE TITLE
How can I maximize the output result for multihand-tracking?

### ISSUE THREAD

**Issue by AntonioDL97** [google/mediapipe#682]
Whenever I see the examples shown by google, the multihand-tracking seems to work much better than it really does when I use it. So I think I might be doing something wrong.

- What camera do you use for your tests? Is there a minimum resolution?

- Is there a video contrast that works better (brightness, color, ect...)

Thank you very much

**Comment by eknight7** [comment]
We used a Pixel 2. Can you share what problems you are encountering with the sample? And the platform/device you are using etc?

**Comment by fanzhanggoogle** [comment]
Feel free to re-open the issue if there's any updates.
