### ISSUE TITLE
Fail modifying MediaPipe opencv config with setup_opencv.sh

### ISSUE THREAD

**Issue by segobrsm** [google/mediapipe#683]
Hello! I am currently looking to use Hand Tracking on Desktop from MediaPipe.

So I'm starting to install Mediapipe with the tutorial available in the doc. However I am completely blocked when I install OpenCV by running the `setup_opencv.sh` file in the command line.

I cloned Mediapipe Git repo in my project folder, then did :
- `cd mediapipe`
- `./setup_opencv.sh` to run the script

The installation goes well until the modification of MediaPipe OpenCV parameters.

The error is as follows: 
```
Modifying MediaPipe opencv config
cd : error retrieving current directory : getcwd : cannot access parent directories : No such file or directory
pwd : error retrieving current directory : getcwd : cannot access parent directories : No such file or directory
```
I executed the command several times by closing then reopening my terminal. I've done a lot of unsuccessful research. I know that it often comes from when modifying a place file but I did nothing similar, no modification. 

Can you help me? I'm really stuck...

OS: Ubuntu 19.10

**Comment by jiuqiant** [comment]
Not sure what the problem is. But a quick workaround is to manually modify the `opencv_build_file` and `workspace` variables in setup_opencv.sh to be the absolute path to those two files.

```
opencv_build_file=/path/to/your/mediapipe/third_party/opencv_linux.BUILD
workspace_file=/path/to/your/mediapipe//WORKSPACE
```

**Comment by segobrsm** [comment]
Thanks a lot it worked!

**Comment by andtauk** [comment]
This is in the description of the setup_opencv.sh!

# To have a full installation:
# $ cd <mediapipe root dir>
# $ sh ./setup_opencv.sh
#
# To only modify the mediapipe config for opencv:
# $ cd <mediapipe root dir>
# $ sh ./setup_opencv.sh config_only

**Comment by Makuta11** [comment]
I am getting the following error when running setup_opencv.sh:

task kworker/1:2:8838 blocked for more than 120 seconds.
Tainted: G    C  E     5.4.0-1028-raspi #31-Ubuntu

anyone who can help, or know what is going on?
