### ISSUE TITLE
Mediapipe crashing when moved in background on android

### ISSUE THREAD

**Issue by PrinceP** [google/mediapipe#684]
when the app is moved to the background while the camera is processing packets, the externaltexture converter causes the below error.

>     java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
>         at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:294)
>         at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.setSurfaceTextureAndAttachToGLContext(ExternalTextureConverter.java:197)
>         at com.google.mediapipe.components.ExternalTextureConverter.lambda$setSurfaceTextureAndAttachToGLContext$1$ExternalTextureConverter(ExternalTextureConverter.java:120)
>         at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$5RBq2uHoPl06wf2nG84kcgcgP_U.run(Unknown Source:8)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:214)
>         at com.google.mediapipe.glutil.GlThread.run(GlThread.java:134)

**Comment by SwatiModi** [comment]
the reason behind crash is, In start the GL context is created and attached to the camera, when your app goes in background and when you come back, onResume runs and it tries to attach the context but it is already attached and hence causes the crash 

To solve this, you can add the following code to the Pause function(which runs when you leave the app)

`public void pausePreview() {
    try{
        previewFrameTexture.release();
        if(converter!=null)
            converter.close();
    }catch (Exception e){
        e.printStackTrace();
    }
}`

**Comment by PrinceP** [comment]
@SwatiModi  Thanks a lot. 
@eknight7 The fix can be replicated in all the examples.

**Comment by teleger** [comment]
This problem is similar to the problem I found. It looks like this. I added part of the code, as follows:
in     mediapipe/java/com/google/mediapipe/components/ExternalTextureConverter.java

  public void setSurfaceTextureAndAttachToGLContext(SurfaceTexture texture, int width, int height) {
    if (texture != null && (width == 0 || height == 0)) {
      throw new RuntimeException(
          "ExternalTextureConverter: setSurfaceTexture dimensions cannot be zero");
    }
//add       
    if(!thread.isAlive()){
      Log.d(TAG,"thread is dead");
    }
//end  
    thread
        .getHandler()
        .post(() -> thread.setSurfaceTextureAndAttachToGLContext(texture, width, height));
  }

then,
The thread is dead, no judgment, so the screen is black
