### ISSUE TITLE
Hair Segmentation Throwing Error on Tensorflow Lite

### ISSUE THREAD

**Issue by ragavendranbala** [google/mediapipe#687]
I tried to load hair_segmentation.tflite file to the interpreter an android Studio with options as GPU delegate as True and thread count as 2. I tried to load the same on Unity As well I'm getting the Following error( tried with another model from other github repos and it's worked but not accurate) 

Exception: TensorFlowLite operation failed.
TensorFlowLite.Interpreter.ThrowIfError (System.Int32 resultCode) (at Assets/TensorFlowLite/SDK/Scripts/Interpreter.cs:196)
TensorFlowLite.Interpreter.Invoke () (at Assets/TensorFlowLite/SDK/Scripts/Interpreter.cs:109)

Please help me to fix the issue

**Comment by ragavendranbala** [comment]
Closing this due to lack of more information. I'll create a new issue with all information

**Comment by kyhoolee** [comment]
The issue is similar here 
https://github.com/google/mediapipe/issues/2312
Simply because hair_segmentation.tflite use custom OP from mediapipe, and official tensorflow android library does not support 

But I don't know how to fix it :'(
