### ISSUE TITLE
Error trying to build hand tracking demo

### ISSUE THREAD

**Issue by OrangeSmoothie** [google/mediapipe#688]
I am having this:

"/home/orange/.cache/bazel/_bazel_orange/4c1fa15e716ae208e75b326371abe9a2/external/org_tensorflow/tensorflow/core/util/BUILD:349:1: Executing genrule @org_tensorflow//tensorflow/core/util:version_info_gen failed (Exit 127)
/usr/bin/env: 'python': No such file or directory
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps."

After using "--verbose_failures":

ERROR: /home/orange/.cache/bazel/_bazel_orange/4c1fa15e716ae208e75b326371abe9a2/external/org_tensorflow/tensorflow/core/util/BUILD:349:1: Executing genrule @org_tensorflow//tensorflow/core/util:version_info_gen failed (Exit 127): bash failed: error executing command 
  (cd /home/orange/.cache/bazel/_bazel_orange/4c1fa15e716ae208e75b326371abe9a2/execroot/mediapipe && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/k8-opt-exec-2B5CBBC6/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate external/local_config_git/gen/spec.json external/local_config_git/gen/head external/local_config_git/gen/branch_ref "bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/util/version_info.cc" --git_tag_override=${GIT_TAG_OVERRIDE:-}')
Execution platform: @local_config_platform//:host
/usr/bin/env: 'python': No such file or directory
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build

**Comment by OrangeSmoothie** [comment]
Above this error i had:
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "64c8a7d7224d8495c306111a13c663eebb34a160ae0fe382561bd2eae6c2670c"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/orange/.cache/bazel/_bazel_orange/4c1fa15e716ae208e75b326371abe9a2/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/05702cf4099ad019ad1abb8ba656bfe04304f32a.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/Maratyszcza/pthreadpool/archive/76042155a8b1e189c8f141429fd72219472c32e1.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

I tried different networks, does not work. If i go in browser to "github.com/Maratyszcza/pthreadpool/archive/76042155a8b1e189c8f141429fd72219472c32e1.tar.gz" instead of full path with googleapis it is downloading. Is there a way i can put downloaded "tar.gz" archives in?

**Comment by jiuqiant** [comment]
See https://github.com/google/mediapipe/issues/3#issuecomment-505669819

**Comment by OrangeSmoothie** [comment]
I dont have any more warning but still there is an error(

ERROR: /home/orange/.cache/bazel/_bazel_orange/4c1fa15e716ae208e75b326371abe9a2/external/org_tensorflow/tensorflow/core/util/BUILD:349:1: Executing genrule @org_tensorflow//tensorflow/core/util:version_info_gen failed (Exit 127): bash failed: error executing command 
  (cd /home/orange/.cache/bazel/_bazel_orange/4c1fa15e716ae208e75b326371abe9a2/execroot/mediapipe && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/k8-opt-exec-2B5CBBC6/bin/external/org_tensorflow/tensorflow/tools/git/gen_git_source --generate external/local_config_git/gen/spec.json external/local_config_git/gen/head external/local_config_git/gen/branch_ref "bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/util/version_info.cc" --git_tag_override=${GIT_TAG_OVERRIDE:-}')
Execution platform: @local_config_platform//:host
/usr/bin/env: 'python': No such file or directory
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build

**Comment by OrangeSmoothie** [comment]
I installed python 2.7 too and now i have different errors:
ERROR: /home/orange/mediapipe/mediapipe/examples/desktop/hand_tracking/BUILD:36:1: Couldn't build file mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu: Linking of rule '//mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-

AND MANY ERRORS LIKE DOWN BELOW
opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function cv::Mat::~Mat(): error: undefined reference to 'cv::fastFree(void*)'
bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function cv::Mat::~Mat(): error: undefined reference to 'cv::Mat::deallocate()'

**Comment by jiuqiant** [comment]
See https://github.com/google/mediapipe/issues/666#issuecomment-620884783

**Comment by OrangeSmoothie** [comment]
Thank you all guys, everything works now

**Comment by OrangeSmoothie** [comment]
Thank you all guys, everything works now
