### ISSUE TITLE
Recolour the mask in hair segmentation model using LUTs 

### ISSUE THREAD

**Issue by Nerdyvedi** [google/mediapipe#689]
Hi, 
How can we recolour the mask with LUT as mentioned in the paper. Currently the model recolours using a single colour. 
![image](https://user-images.githubusercontent.com/23276664/81090387-46076480-8f1b-11ea-9b3e-d72e1b562d3e.png)

**Comment by mcclanahoochie** [comment]
Hi,
The current recolor calculator is a simplified version of what is in the paper.
The algorithm in the paper computes the luminance (grayscale) value at each hair pixel, then uses that value (0-255) as an index into a LUT, and uses the color from LUT to overlay onto the image. 
The recolor calculator provided [skips the LUT](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/image/recolor_calculator.cc#L240), and just uses the luminance multiplied by the output color.
So, if you can create a LUT, then inserting it into the calculator would not be very difficult.

**Comment by mcclanahoochie** [comment]
> then uses the luminance (grayscale) to blend between the 2 LUT results.

as mentioned above, it is linear interpolation

**Comment by Nerdyvedi** [comment]
Hi ,
Thank you so much for your help. The only thing I don't understand now is how do we write a index to access 2D LUTs. 
In the Apk file I found some LUTs, These are png files and seem to 3D. Are you sure 2D LUTs were used in the paper, as 2D LUTs are generally not used.(My knowledge on LUTs is highly limited).

I have attached a sample LUT file. Does this seem right ?

![image](https://user-images.githubusercontent.com/23276664/82202932-3c6cfc00-9920-11ea-8b23-308454944d5b.png)

**Comment by Nerdyvedi** [comment]
@mcclanahoochie Sorry for disturbing you. I would be really grateful if you could help

**Comment by jdmakwana1999** [comment]
@mcclanahoochie

**Comment by jdmakwana1999** [comment]
/*
      vec4 weight = texture2D(mask, sample_coordinate);
      vec4 color1 = texture2D(frame, sample_coordinate);
      vec4 color2 = vec4(recolor, 1.0);
      float luminance = dot(color1.rgb, vec3(0.299, 0.587, 0.114));
      float mix_value = weight.MASK_COMPONENT * luminance;
      fragColor = mix(color1, color2, mix_value);
  */

@mcclanahoochie how to edit this sir?

Thank you in advance :))

**Comment by mcclanahoochie** [comment]
@Nerdyvedi I guess you can call it 3D lut (i was mainly referring to using a 2D texture as LUT instead of simpler 1D).
Regardless, you can pick a color channel, use that value to index into the big grid (choosing one of the 8x8 squares) , then use the other two channels to index (x,y) the sub-square

@jdmakwana1999 That is a comment (taken from the GPU code) that describes what the cpu is doing (the GPU code was written first).

**Comment by Nerdyvedi** [comment]
@mcclanahoochie Thank you so much for responding. 
> the index is already being computed

Where is the index being computed.


Very very sorry for disturbing so often and asking silly questions.

**Comment by Pankti99** [comment]
Hello, I'm working on similar project ,where I have to color the hairs. So can anyone guide me how to implement this in python?

**Comment by akokhlik** [comment]
> Hi,
> The current recolor calculator is a simplified version of what is in the paper.
> 
> The paper uses two 2D LUTs (rgb), and blends them based on luminosity.
> The algorithm in the paper computes an index based on RGB value at each hair pixel, then uses that value as an index into two 2D LUT, for both light and dark hair, then uses the luminance (grayscale) to blend between the 2 LUT results.
> 
> The recolor calculator provided [skips the LUT](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/image/recolor_calculator.cc#L240), and just uses the luminance multiplied by the output color.
> 
> So, if you can create a simple 1D LUT, then inserting it into the calculator would not be too hard (the index is already being computed). Expanding it into a more complex system would just involve more indexing.


Hi, I am beginner. Can you clarify how can i give 1D LUT, to calculator from android java
