### ISSUE TITLE
Error in building TensorFlow Object Detection Demo

### ISSUE THREAD

**Issue by saiharsha17** [google/mediapipe#69]
I was able to build and run the hello_world example on Desktop.
When i try to build the object detection demo using 

$ bazel build -c opt \
    --define MEDIAPIPE_DISABLE_GPU=1 \
    --define no_aws_support=true \
    mediapipe/examples/desktop/object_detection:object_detection_tensorflow

I receive the following errors:

WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'build_bazel_rules_apple' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "6c9fcae7a3597aabd43f28be89466afe0eab18de", shallow_since = "1565379803 -0700" and dropping ["tag"]
DEBUG: Call stack for the definition of repository 'build_bazel_rules_apple' which is a git_repository (rule definition at /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /home/tcs/mediapipe/WORKSPACE:251:1
INFO: Build option --define has changed, discarding analysis cache.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "1991102fbff099a2e5eb990cdee3fdaf80803bf611c8fdf60f612e263438d0fb"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/tcs/mediapipe/WORKSPACE:28:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/libjpeg-turbo/libjpeg-turbo/archive/2.0.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/www.nasm.us/pub/nasm/releasebuilds/2.13.03/nasm-2.13.03.tar.bz2 failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/org_tensorflow/tensorflow/core/BUILD:560:12: in srcs attribute of cc_library rule @org_tensorflow//tensorflow/core:platform_strings: please do not import '@org_tensorflow//tensorflow/core/platform:platform_strings.cc' directly. You should either move the file to this package or depend on an appropriate rule there
WARNING: /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/org_tensorflow/tensorflow/core/BUILD:560:12: in srcs attribute of cc_library rule @org_tensorflow//tensorflow/core:platform_strings: please do not import '@org_tensorflow//tensorflow/core/platform:platform_strings_computed.h' directly. You should either move the file to this package or depend on an appropriate rule there
INFO: Call stack for the definition of repository 'gif_archive' which is a tf_http_archive (rule definition at /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/org_tensorflow/third_party/repo.bzl:124:19):
 - /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/org_tensorflow/tensorflow/workspace.bzl:287:5
 - /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/org_tensorflow/tensorflow/workspace.bzl:60:5
 - /home/tcs/mediapipe/WORKSPACE:121:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz failed: class java.io.IOException GET returned 503 Service Unavailable
ERROR: An error occurred during the fetch of repository 'gif_archive':
   java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz, http://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz] to /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/gif_archive/giflib-5.1.4.tar.gz: GET returned 503 Service Unavailable
INFO: Call stack for the definition of repository 'eigen_archive' which is a tf_http_archive (rule definition at /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/org_tensorflow/third_party/repo.bzl:124:19):
 - /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/org_tensorflow/tensorflow/workspace.bzl:170:5
 - /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/org_tensorflow/tensorflow/workspace.bzl:60:5
 - /home/tcs/mediapipe/WORKSPACE:121:1
ERROR: /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/org_tensorflow/tensorflow/core/platform/default/build_config/BUILD:212:1: @org_tensorflow//tensorflow/core/platform/default/build_config:gif depends on @gif_archive//:gif in repository @gif_archive which failed to fetch. no such package '@gif_archive//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz, http://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz] to /home/tcs/.cache/bazel/_bazel_tcs/3d4eb2cbf71caf8f570eba8043943dcc/external/gif_archive/giflib-5.1.4.tar.gz: GET returned 503 Service Unavailable
ERROR: Analysis of target '//mediapipe/examples/desktop/object_detection:object_detection_tensorflow' failed; build aborted: Analysis failed
INFO: Elapsed time: 16.115s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 6304 targets c\
onfigured)

**Comment by mgyong** [comment]
@saiharsha17 How was this problem solved?
