### ISSUE TITLE
coral face model with usb accelerator

### ISSUE THREAD

**Issue by natxopedreira** [google/mediapipe#690]
Hello

I want to run  this model
https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/models/face-detector-quantized_edgetpu.tflite

With the usb accelerator on rpi, but im getting this error
`ERROR: Failed to prepare for TPU. generic::failed_precondition: Package requires runtime version (12), which is newer than this runtime version (10).
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.

Failed in Tensor allocation, status_code: 1
Abortado`

What can i do? Thank you

**Comment by mcclanahoochie** [comment]
The edge TPU models MediaPipe provides were compiled for version 12 of Mendel (the coral OS). Please [flash](https://coral.ai/docs/dev-board/reflash/) the board to the latest version 13, or version 12.

**Comment by natxopedreira** [comment]
Than you

Maybe i do not explained my self correct but as is in the post tittle, im using the usb accelerator not the dev board

**Comment by mcclanahoochie** [comment]
Do you have the latest edge tpu [runtime and tflite](https://coral.ai/docs/accelerator/get-started/#requirements) library?

**Comment by natxopedreira** [comment]
Thanks!!! i reinstalled again and now im not getting that error.

There is any info about on how to use this model with the python api?

` engine = DetectionEngine(model)`
ValueError: Dectection model should have 4 output tensors!This model has 2.

**Comment by mcclanahoochie** [comment]
Great!
I'm not too familiar with the python api, but I it expects the model to have a certain final op that does some filtering. 
The face model MP provides doesn't have this final TF op, and instead relies on a calculator to do the filtering [[see here](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc#L290)].  Right below that section in the calculator, you can see the[ 4-output version](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc#L366), which I believe the python code expects.
You would need to either choose a different model, or adapt the python code to handle the 2-tensor version (as seen in the calculator).

**Comment by natxopedreira** [comment]
Thank you, i will try to adapt the code
