### ISSUE TITLE
Bazel 2.0 installation on CentOS

### ISSUE THREAD

**Issue by palash1992** [google/mediapipe#691]
I am following the link provided (https://docs.bazel.build/versions/2.0.0/install-redhat.html) to install Bazel 2.0 on CentOS and it is still installing version 1.2.1. Can you let me know how can I install version 2.0 on CentOS?

**Comment by jiuqiant** [comment]
Probably you can run the following to download and install bazel 2.0.0 manually?
```
curl -sLO --retry 5 --retry-max-time 10 \
https://storage.googleapis.com/bazel/2.0.0/release/bazel-2.0.0-installer-linux-x86_64.sh && \
sudo mkdir -p /usr/local/bazel/2.0.0 && \
chmod 755 bazel-2.0.0-installer-linux-x86_64.sh && \
sudo ./bazel-2.0.0-installer-linux-x86_64.sh --prefix=/usr/local/bazel/2.0.0 && \
source /usr/local/bazel/2.0.0/lib/bazel/bin/bazel-complete.bash
```

**Comment by palash1992** [comment]
Thanks! That works!
