### ISSUE TITLE
In android,save bitmap,not color

### ISSUE THREAD

**Issue by teleger** [google/mediapipe#692]
I use the android, added on my MainActivity:

Processor. AddPacketCallback (

"Input_video_cpu."

(packet) - > {

Bitmap Bitmap = AndroidPacketGetter. GetBitmapFromRgb (packet); };

The saved bitmap has no color, but it has the effect of a fence, and the size also takes up the width * height *3, I want to know, how is this going on, and how does it look color, is it not rgba that it is saved? Looking forward to your reply. Thank you

**Comment by mcclanahoochie** [comment]
What is the rest of the graph look like?
In the example Android graphs from MediaPipe, RGBA images are used throughout the pipeline.
Have you also tried getBitmapFromRgba() ?

**Comment by teleger** [comment]
I finally tried to call this getBitmapFromRgba, she looks like she's in color, thank you
