### ISSUE TITLE
Android x86 error in System.loadLibrary

### ISSUE THREAD

**Issue by jlc288** [google/mediapipe#695]
If I run the application on an Android with arm64-v8a cpu it works correctly.

But when running on a x86 CPU device with supported abis: x86 , armeabi-v7a, armeabi

fails to execute  **System.loadLibrary("mediapipe_jni")**

with this error

```
java.lang.UnsatisfiedLinkError: undefined symbol: __popcount_tab
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:1076)
```

in the build.gradle I have this
```
 defaultConfig {
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"
        }
    }
```

**Comment by jiuqiant** [comment]
I think MediaPipe supports ARM CPUs and x86 CPUs are not supported.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
