### ISSUE TITLE
Autoflip:  MacOS, Ubuntu and Centos 7 have different memory consumption.

### ISSUE THREAD

**Issue by Ensteinjun** [google/mediapipe#697]
I use autoflip to process the same video on different platforms, only macos can successfully process this video. The maximum memory usage of macos is only about 9G, but centos and ubuntu can exceed 30G. 

Ubuntu:  8 vCPUs  32G RAM
Centos7: 8 vCPUs 32G RAM 
MacOS:  6 core CPU, 16G RAM

cmd: GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/autoflip/run_autoflip --calculator_graph_config_file=mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt --input_side_packets=input_video_path=./input.mp4,output_video_path=./output.mp4,aspect_ratio=16:9

macOS:
![image](https://user-images.githubusercontent.com/12184613/81177448-41a18100-8fd9-11ea-820b-be4de373c6e9.png)

CentOS7:
it will be killed by the system due to excessive memory usage.
error log: terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
![image](https://user-images.githubusercontent.com/12184613/81181158-9b587a00-8fde-11ea-8954-74d5b742e3fa.png)
![image](https://user-images.githubusercontent.com/12184613/81181114-8aa80400-8fde-11ea-9ce0-4c67165ed321.png)

**Comment by jiuqiant** [comment]
Thanks for the reporting. We will investigate this issue soon.

Here is a temporarily workaround. Can you change the value of `max_queue_size` to a small positive number (1, 2, ... 5) at https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt#L3 and rerun the binary?

**Comment by Ensteinjun** [comment]
> Thanks for the reporting. We will investigate this issue soon.
> 
> Here is a temporarily workaround. Can you change the value of `max_queue_size` to a small positive number (1, 2, ... 5) at https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/autoflip/autoflip_graph.pbtxt#L3 and rerun the binary?

Thanks, I tried to set max_queue_size to 1, 5, 8, 16. The program can work normally.
But the warn log appeared in the program.

warn log:
Resolved a deadlock by increasing max_queue_size of input stream: borders to: 17. Consider increasing max_queue_size for better performance.


I set max_queue_size to 32 and the memory will grow crazy.  it will be killed by the system due to excessive memory usage.

**Comment by jiuqiant** [comment]
`max_queue_size` indicates how many packets an input stream can queue up. The warning messages are basically saying that some calculator nodes are starving because they don't have any packets to process. That's expected since we set the global `max_queue_size` param for the sack of memory usage. It's the tradeoff.

As the next step, we need to figure out which input streams are causing the problem and only limit the queue size of those streams and unset the global `max_queue_size`.

**Comment by Ensteinjun** [comment]
> `max_queue_size` indicates how many packets an input stream can queue up. The warning messages are basically saying that some calculator nodes are starving because they don't have any packets to process. That's expected since we set the global `max_queue_size` param for the sack of memory usage. It's the tradeoff.
> 
> As the next step, we need to figure out which input streams are causing the problem and only limit the queue size of those streams and unset the global `max_queue_size`.

Thanks, Got it

**Comment by adamelmore** [comment]
Is this issue still being investigated?

**Comment by adamelmore** [comment]
@jiuqiant curious if this is on your radar, still? Running mediapipe in the cloud on linux containers is desired, and the memory consumption is prohibitive at the moment.

**Comment by sgowroji** [comment]
Hi @Ensteinjun, Could you please respond if you still looking resolution for the above query. Thanks!

**Comment by rthadur** [comment]
Thank you

**Comment by peternaf** [comment]
Hi @jiuqiant 

Were you able to understand what input stream is causing the problem? I am experiencing the same issue currently.
"As the next step, we need to figure out which input streams are causing the problem and only limit the queue size of those streams and unset the global max_queue_size."

**Comment by peternaf** [comment]
@adamelmore were you able to find a solution?
