### ISSUE TITLE
Not able to use Mediapipe as external dependency with commit b6e680647cebf925ebc6a3f82b469d57c1c68da9.

### ISSUE THREAD

**Issue by lmzh123** [google/mediapipe#699]
Hello guys, 

I've been trying to use MP as external dependency based on this [example](https://github.com/mgyong/mediapipe_addons) from @mgyong by setting up my WORKSPACE like [this](https://github.com/google/mediapipe/files/4588069/WORKSPACE.txt)
 (@hadon coomit) and setting Mediapipe's mos recent _third_party_ folder in my project. When I build `bazel build //helloworld:hello_world_calculator_test`, I get internal dependency conflicts like:

`
ERROR: /home/luis/.cache/bazel/_bazel_luis/227c0b8a664619321580c767b709fd29/external/org_tensorflow/third_party/py/python_configure.bzl:271:27: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
ERROR: error loading package '': in /home/luis/.cache/bazel/_bazel_luis/227c0b8a664619321580c767b709fd29/external/org_tensorflow/tensorflow/workspace.bzl: Extension file 'third_party/py/python_configure.bzl' has errors
INFO: Elapsed time: 0.099s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @io_bazel_rules_closure; fetching
`

Thanks in advance.

**Comment by jiuqiant** [comment]
As the error message suggested, you can append `--experimental_repo_remote_exec` to the Bazel build command.

**Comment by lmzh123** [comment]
My bad. Thanks a lot!
