### ISSUE TITLE
Do you have any face detection examples for desktop?

### ISSUE THREAD

**Issue by RealBBakGosu** [google/mediapipe#7]
Thanks

**Comment by mgyong** [comment]
@RealBBakGosu All the examples are listed at [https://mediapipe.readthedocs.io/en/latest/examples.html](https://mediapipe.readthedocs.io/en/latest/examples.html). We only have face detection example for Android and do not have a version for desktop. However, you should be able to port the face detection tf-lite example to desktop by basing it on the [desktop tflite object detection example](https://mediapipe.readthedocs.io/en/latest/object_detection_desktop.html#tensorflow-lite-object-detection-demo) 

- Swap out the desktop object detection pbtxt with the face detection pbtxt 
- The face detection Android example uses the mobile camera while the desktop will be loading the input video through a file. As such, you will have to make changes to the first few input calculators to the face detection Android example

**Comment by RealBBakGosu** [comment]
> @RealBBakGosu All the examples are listed at https://mediapipe.readthedocs.io/en/latest/examples.html. We only have face detection example for Android and do not have a version for desktop. However, you should be able to port the face detection tf-lite example to desktop by basing it on the [desktop tflite object detection example](https://mediapipe.readthedocs.io/en/latest/object_detection_desktop.html#tensorflow-lite-object-detection-demo)
> 
>     * Swap out the desktop object detection pbtxt with the face detection pbtxt
> 
>     * The face detection Android example uses the mobile camera while the desktop will be loading the input video through a file. As such, you will have to make changes to the first few input calculators to the face detection Android example

**Comment by RealBBakGosu** [comment]
Hello if you want to test face detection example on desktop, pls download this code and use as a calculator

[face_detection_tflite.zip](https://github.com/google/mediapipe/files/3396091/face_detection_tflite.zip)

bazel-bin/mediapipe/examples/desktop/object_detection/object_detection_tflite     --calculator_graph_config_file=<face_detection_tflite_path>    --input_side_packets=input_video_path=<input_video_path>,output_video_path=<output_video_path>

for example,
bazel-bin/mediapipe/examples/desktop/object_detection/object_detection_tflite --calculator_graph_config_file=mediapipe/graphs/face_detection/face_detection_tflite.pbtxt --input_side_packets=input_video_path=mediapipe/examples/desktop/object_detection/test.mp4,output_video_path=mediapipe/examples/desktop/object_detection/output.mp4

**Comment by jiuqiant** [comment]
@RealBBakGosu, thanks for composing a face detection graph for desktop use case! Just to clarify, what you have in face_detectiont_tflite.zip is a graph, and calculators are those nodes in the graph ;)

We definitely will provide more desktop demos in the future releases.

**Comment by mgyong** [comment]
@RealBBakGosu  Thanks for using MediaPipe. My team would love to get feedback from you about your use of MediaPipe
It would be great if you could answer the below questions
1) What is your use case for MediaPipe?
2) Any feedback about how easy or difficult it is to use MediaPipe?
Thanks
Ming
