### ISSUE TITLE
Why the outputs of the resize function using ImageTransformationCalculator different for IMAGE (CPU) and IMAGE_GPU (GPU)?

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#702]
I tried using GpuBufferToImageFrameCalculator and ImageFrameToGpuBufferCalculator to do the conversion between GPU and CPU and ImageTransformationCalculator to do the resizing. The outputs are slightly different for INTER_LINEAR/GL_LINEAR and vastly different for INTER_NEAREST/GL_NEAREST. Is that expected? Why?

**Comment by mcclanahoochie** [comment]
in which way are outputs different? Can you please show what you are seeing?

**Comment by yxchng** [comment]
@mcclanahoochie 

The calculator is tested by passing an input of blue and black stripes created using the following code:

```
  bool flag = true;
  for (int i = 0; i < input_mat.rows; i++) {
    for (int j = 0; j < input_mat.cols; j++) {
      if (flag) {
        input[(i*input_mat.rows + j) * 4 + 0] = 0;
        input[(i*input_mat.rows + j) * 4 + 1] = 0;
        input[(i*input_mat.rows + j) * 4 + 2] = 0;
      } else {
        input[(i*input_mat.rows + j) * 4 + 0] = 0;
        input[(i*input_mat.rows + j) * 4 + 1] = 0;
        input[(i*input_mat.rows + j) * 4 + 2] = 255;
      }
      input[(i*input_mat.rows + j) * 4 + 3] = 255;
      flag = !flag;      
    }
  } 
```

This test image is used because it will make the difference more obvious.

-  The following graph is used to test ImageTransformation on CPU on an Android phone.

```
input_stream: "input_video"
output_stream: "output_video"
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}
node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "throttled_input_video"
  output_stream: "input_video_cpu"
}
node: {
  calculator: "FeedTestImageCalculator"
  input_stream: "IMAGE:input_video_cpu"
  output_stream: "IMAGE:test_video_cpu"
}
node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:test_video_cpu"
  output_stream: "IMAGE:resized_video_cpu"
  output_stream: "LETTERBOX_PADDING:letterbox_padding"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 11
      output_height: 11
      scale_mode: STRETCH
    }
  }
}
node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "resized_video_cpu"
  output_stream: "output_video"
}
```

- Output:

![IMG_2239](https://user-images.githubusercontent.com/10518587/81523970-2a201a80-9382-11ea-9d6e-3141169b6ac9.JPG)

-  The following graph is used to test ImageTransformation on GPU on an Android phone.

```
input_stream: "input_video"
output_stream: "output_video"
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}
node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "throttled_input_video"
  output_stream: "input_video_cpu"
}
node: {
  calculator: "FeedTestImageCalculator"
  input_stream: "IMAGE:input_video_cpu"
  output_stream: "IMAGE:test_video_cpu"
}
node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "test_video_cpu"
  output_stream: "test_video_gpu"
}
node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:test_video_gpu"
  output_stream: "IMAGE_GPU:output_video"
  output_stream: "LETTERBOX_PADDING:letterbox_padding"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 11
      output_height: 11
      scale_mode: STRETCH
    }
  }
}

```

- Output:

![IMG_2240](https://user-images.githubusercontent.com/10518587/81524232-f4c7fc80-9382-11ea-9d7e-2e67c39bf367.JPG)

**Comment by mcclanahoochie** [comment]
What is the input dimensions of the image? 

I think one problem could be indexing the Mat. 
Instead of using
`input[(i*input_mat.rows + j) * 4 + 0]`
try using 
`input.at<uchar>(i,j)`
This is for 2 reasons:
-because there may be padding on the image (the width may be larger than input_mat.cols). 
-you are using `y*height+x `and it should be `y*width+x` or `x*height+y`

**Comment by yxchng** [comment]
@mcclanahoochie The input size is 1080x1080. I have tried your suggestion of using  `input.at<uchar>(i,j)` and the result is the same. I also tried switching `input_mat.rows` with `input_mat.cols` and I still get the same result. 

I have done extensive experiment and I happen to find another weird phenomenon #712. This pretty much shows that there is a critical bug with ImageTransformationCalculator!

**Comment by mcclanahoochie** [comment]
Please see https://github.com/google/mediapipe/issues/704#issuecomment-625392448 and https://github.com/google/mediapipe/issues/712#issuecomment-670725425 
as that is the most likely issue. 


Closing for now due to lack of activity
