### ISSUE TITLE
Extracting landmarks

### ISSUE THREAD

**Issue by Tectu** [google/mediapipe#703]
We're trying to extract the 3D landmarks from the hand tracking (GPU) example. However, we're having a hard time figuring out how we can access the landmark data so we can process it in our software.

Unfortunately, we couldn't figure out how to do this by reading the documentation. If somebody could point us to the right direction, that would be greatly appreciated!

We want to process the 3D landmarks coming from mediapipe in a C++ application. What is the preferred/recommended way of doing this?

**Comment by jiuqiant** [comment]
Please take a look at https://github.com/google/mediapipe/issues/200#issuecomment-599971551 and https://github.com/mgyong/mediapipe-issue200.

**Comment by dolmens** [comment]
Call `CalculatorGraph::ObserveOutputStream` to register a packet callback, then use `Packet::Get`,especially `Get<NormalizedLandmarkList>,` to read data.

If you want to interfere the graph's execution, just write a Node and put it in the graph pbtxt.

**Comment by Tectu** [comment]
Thank you for the information, guys.

**Comment by Somyarani13** [comment]
@Tectu Were you able to extract the 3D landmarks from the hand tracking example. Can you share the steps?

**Comment by Somyarani13** [comment]
> Call `CalculatorGraph::ObserveOutputStream` to register a packet callback, then use `Packet::Get`,especially `Get<NormalizedLandmarkList>,` to read data.
> 
> If you want to interfere the graph's execution, just write a Node and put it in the graph pbtxt.

Can you please elaborate the process? Thanks
