### ISSUE TITLE
Hand Detection, found two hand, but how to Distinguish it? 

### ISSUE THREAD

**Issue by tristsesame** [google/mediapipe#706]
multi hand tracking is useful, but it slow,  only 15fps in my device. 
so I have to use the hand detect.

I need draw the hand move path by the hand pos. 
but if there is two hand, I can't identify the (x,y) belong to which hand?
ios/android

**Comment by mgyong** [comment]
Next version of the hand example will provide differentiation between left and right hand

**Comment by mgyong** [comment]
@tristsesame We have updated the MediaPipe hands model to include right left prediction https://github.com/google/mediapipe/releases/tag/v0.7.5

**Comment by tristsesame** [comment]
> @tristsesame We have updated the MediaPipe hands model to include right left prediction https://github.com/google/mediapipe/releases/tag/v0.7.5

thank you!

**Comment by gogoqaz** [comment]
> 
> 
> @tristsesame We have updated the MediaPipe hands model to include right left prediction https://github.com/google/mediapipe/releases/tag/v0.7.5

Hi mgyong,
How to get the prediction from the handedness stream?
I know I can use below code to get the hand rect, but what's the type of the prediction? 
`const auto rect = packet.Get<::mediapipe::NormalizedRect>();`

Thank you!

**Comment by fanzhanggoogle** [comment]
Yeah, unfortunately it'll be difficult to support that in the detector.

**Comment by vasanthhr** [comment]
Hello, (sorry I am asking this question again here as well).

I want to see the prediction left or right hand in the handpose model(tfjs-model: handpose model).

As of now i can see 21 3d keypoints as output, please suggest me how to predict left or right hand on this handpose model.

**Comment by vivi90** [comment]
@fanzhanggoogle Two hand support like here described would be great: https://github.com/google/mediapipe/issues/89
Seems to be still not available at the web demo.

**Comment by MightyStud** [comment]
Have this issue been solved? AFAIK I can't differentiate between left and right hand landmarks.

**Comment by tso996** [comment]
It is possible. I'm not sure if it is straightforward though. From the results object in their examples
 ```   results = hands.process(image)```
 Try exploring ```results.multi_handedness```
Also check out this repo, https://github.com/Kazuhito00/hand-gesture-recognition-using-mediapipe .

**Comment by janaki112** [comment]
@tso996 , Hey can you please tell me whether mediapipe recognises gestures involving two hands. As of now it's only detecting left and hand gestures separately. Is it possible to detect gestures involving two hands by performing classification.
