### ISSUE TITLE
Use HandTracking and MultiHandTracking with files

### ISSUE THREAD

**Issue by Xilosof** [google/mediapipe#707]
Can i use this project without webcam? Input from files and output in files?

**Comment by jiuqiant** [comment]
Yes, [those desktop examples](https://mediapipe.readthedocs.io/en/latest/examples.html#desktop) do support video-in-video-out workflow. You need to add `--input_video_path` and `--otuput_video_path` to the command. For example, to run multi hand tracking cpu demo with files, you need to do

```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_cpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/multi_hand_tracking_desktop_live.pbtxt --input_video_path=/path/to/input.mp4 --output_video_path=/path/to/ioutput.mp4
```
