### ISSUE TITLE
Unable to build AAR followed the readme

### ISSUE THREAD

**Issue by ragavendranbala** [google/mediapipe#708]
I tried to build aar based on the readme and also used same facedetectiongpu and modified the build and ran the commond, it showing the below error 

using Ubuntu 18.04 on windows virtual box
bazel 3.1.0
sdk version 30.0.1 (from android Studio)
ndk downloaded from given setup script
sdk platform 29
python 3.7.5

please help me to build this thanks in advance

bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a     //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:mp_face_detection_aar
ERROR: /home/ragavendranbala/MediapipeTest/mediapipe/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl:36:5: Traceback (most recent call last):
	File "/home/ragavendranbala/MediapipeTest/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu/BUILD", line 35
		mediapipe_aar(<2 more arguments>)
	File "/home/ragavendranbala/MediapipeTest/mediapipe/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl", line 36, in mediapipe_aar
		native.cc_binary(<4 more arguments>)
cc_binary rule 'libmediapipe_jni.so' in package 'mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu' conflicts with existing cc_binary rule, defined at /home/ragavendranbala/MediapipeTest/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu/BUILD:19:1
ERROR: Skipping '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:mp_face_detection_aar': no such target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:mp_face_detection_aar': target 'mp_face_detection_aar' not declared in package 'mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu' defined by /home/ragavendranbala/MediapipeTest/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:mp_face_detection_aar': target 'mp_face_detection_aar' not declared in package 'mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu' defined by /home/ragavendranbala/MediapipeTest/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu/BUILD
INFO: Elapsed time: 0.268s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)

**Comment by jiuqiant** [comment]
The error is `'//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:mp_face_detection_aar': no such target`. Basically, Bazel doesn't find mp_face_detection_aar target in mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu. Can you show us how you write the mediapipe_aar rule and where you put it?

**Comment by ragavendranbala** [comment]
![image](https://user-images.githubusercontent.com/32410475/81550726-46ca4b80-939e-11ea-8c69-449cf692d70e.png)

inside /mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu 

at this location there is an build file and i modified that file

**Comment by ragavendranbala** [comment]
@jiuqiant thanks for helping to fix this I have build an aar by creating a new folder and new build file. But I don't know how to add the calculators for other example

**Comment by AlexYiningLiu** [comment]
> @jiuqiant thanks for helping to fix this. I have built an aar by creating a new folder and new build file. But I don't know how to add the
> correct calculator files needed for other examples. Please help me to find the exact files.

Can you please explain how you fixed the issue? Where did you create a new folder and BUILD file, and what is inside the BUILD file? Can you please show me the BUILD file you created? Thank you.

**Comment by AlexYiningLiu** [comment]
> @AlexYiningLiu asked:
> 
> > Can you please explain how you fixed the issue? Where did you create a new folder and BUILD file, and what is inside the BUILD file? Can you please show me the BUILD file you created? Thank you.
> 
> I'm not @jiuqiant but I did something similar.
> I created a new BUILD file in new subdirectory
> mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example
> with contents:
> 
> load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
> 
> mediapipe_aar(
> name = "mp_hand_tracking_aar",
> calculators = ["//mediapipe/graphs/hand_tracking:mobile_calculators",
> "//mediapipe/gpu:image_frame_to_gpu_buffer_calculator"],
> )
> 
> Change the name and calculators to suit your needs.
> 
> See documentation at:
> 
> https://github.com/google/mediapipe/blob/master/docs/getting_started/android_archive_library.md
> 
> https://github.com/google/mediapipe/blob/master/docs/getting_started/faq.md
> 
> etc.

Thanks for your response. After you created the custom AAR file, how did you put it to use? I plan on putting it inside the libs folder of the app I'm running which is the mediapipe_multihand_tracking_aar_example as so:
![image](https://user-images.githubusercontent.com/46139686/85633002-619f0980-b646-11ea-8a2e-5f4ff781e32c.png)
Thanks for your help.

**Comment by AlexYiningLiu** [comment]
> @AlexYiningLiu asked:
> 
> > Can you please explain how you fixed the issue? Where did you create a new folder and BUILD file, and what is inside the BUILD file? Can you please show me the BUILD file you created? Thank you.
> 
> I'm not @jiuqiant but I did something similar.
> I created a new BUILD file in new subdirectory
> mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example
> with contents:
> 
> load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
> 
> mediapipe_aar(
> name = "mp_hand_tracking_aar",
> calculators = ["//mediapipe/graphs/hand_tracking:mobile_calculators",
> "//mediapipe/gpu:image_frame_to_gpu_buffer_calculator"],
> )
> 
> Change the name and calculators to suit your needs.
> 
> See documentation at:
> 
> https://github.com/google/mediapipe/blob/master/docs/getting_started/android_archive_library.md
> 
> https://github.com/google/mediapipe/blob/master/docs/getting_started/faq.md
> 
> etc.

Thanks for you response. I am receiving the error 
![image](https://user-images.githubusercontent.com/46139686/86179208-d5825b80-baf7-11ea-897c-b0790ef904fe.png)

There is a BUILD file in mediapipe/gpu so I am unsure why this occurs. Please let me know if you have any idea. Thanks.

**Comment by brianm-sra** [comment]
Try removing the line "//mediapipe/gpu:image_frame_to_gpu_buffer_calculator" that I mentioned I had in my 
aar_example/BUILD
You might not need that in your case

**Comment by AlexYiningLiu** [comment]
> Try removing the line "//mediapipe/gpu:image_frame_to_gpu_buffer_calculator" that I mentioned I had in my
> aar_example/BUILD
> You might not need that in your case

Thanks again for reply. I figured out the cause of that error and was able to fix it by replacing a '/' with a ':' in the BUILD file. However, I am now receiving a C++ compilation error:
```
ERROR: /home/alex715/mediapipe/mediapipe/calculators/tflite/BUILD:269:11: C++ compilation of rule '//mediapipe/calculators/tflite:tflite_converter_calculator' failed (Exit 1) clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target ... (remaining 138 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_multi_hand_aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6692.317s, Critical Path: 6020.05s
INFO: 1621 processes: 1565 linux-sandbox, 56 worker.
FAILED: Build did NOT complete successfully
```
I got this error after nearly 2 hours of compilation time. I am running this on a Ubuntu virtual machine. I just need want to compile an AAR file to put in the multihandtracking AAR example's libs directory found here: https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example
