### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by ragavendranbala** [google/mediapipe#709]
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11  --verbose_failures --define libunwind=true
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = c91e22d4d522cba1cd14edf062183a7036ed476ee63551267c2857e19c0b64b9
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c91e22d4d522cba1cd14edf062183a7036ed476ee63551267c2857e19c0b64b9"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/ragavendranbala/.cache/bazel/_bazel_ragavendranbala/ca095b8d7785365d6fd2a99a0df770f1/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
INFO: SHA256 (https://github.com/opencv/opencv/releases/download/3.4.3/opencv-3.4.3-android-sdk.zip) = cdb0e190c3734edd4052a3535d9e4310af912a9f70a421b1621711942a1028d5
DEBUG: Rule 'android_opencv' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "cdb0e190c3734edd4052a3535d9e4310af912a9f70a421b1621711942a1028d5"
DEBUG: Repository android_opencv instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/ragavendranbala/.cache/bazel/_bazel_ragavendranbala/ca095b8d7785365d6fd2a99a0df770f1/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu:facemeshgpu (145 packages loaded, 9647 targets configured).
INFO: Found 1 target...
INFO: From Executing genrule @com_github_glog_glog//:run_configure [for host]:
/home/ragavendranbala/.cache/bazel/_bazel_ragavendranbala/ca095b8d7785365d6fd2a99a0df770f1/sandbox/linux-sandbox/15/execroot/mediapipe/external/com_github_glog_glog/missing: Unknown `--is-lightweight' option
Try `/home/ragavendranbala/.cache/bazel/_bazel_ragavendranbala/ca095b8d7785365d6fd2a99a0df770f1/sandbox/linux-sandbox/15/execroot/mediapipe/external/com_github_glog_glog/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for ANSI C header files... (cached) no
checking for stdint.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for unistd.h... (cached) yes
checking syscall.h usability... yes
checking syscall.h presence... yes
checking for syscall.h... yes
checking sys/syscall.h usability... yes
checking sys/syscall.h presence... yes
checking for sys/syscall.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking libunwind.h usability... no
checking libunwind.h presence... no
checking for libunwind.h... no
checking ucontext.h usability... yes
checking ucontext.h presence... yes
checking for ucontext.h... yes
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... yes
checking for sys/utsname.h... yes
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking glob.h usability... yes
checking glob.h presence... yes
checking for glob.h... yes
checking unwind.h usability... yes
checking unwind.h presence... yes
checking for unwind.h... yes
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking size of void *... 8
checking for uint16_t... yes
checking for u_int16_t... yes
checking for __uint16... no
checking for sigaltstack... yes
checking for sigaction... yes
checking for dladdr... no
checking for fcntl... yes
checking for pread... yes
checking for pwrite... yes
checking for __attribute__... yes
checking for __builtin_expect... yes
checking for __sync_val_compare_and_swap... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -pthread is sufficient with -shared... yes
checking for pthread_self in -lpthread... yes
checking for main in -lgflags... no
checking for gtest-config... no
checking for main in -lgtest... no
checking support for pthread_rwlock_* functions... yes
checking whether the compiler implements namespaces... yes
checking what namespace STL code is in... std
checking whether compiler supports using ::operator<<... 1
checking for ucontext.h... (cached) yes
checking sys/ucontext.h usability... yes
checking sys/ucontext.h presence... yes
checking for sys/ucontext.h... yes
checking how to access the program counter from a struct ucontext... uc_mcontext.gregs[REG_RIP]
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/glog/logging.h
config.status: creating src/glog/raw_logging.h
config.status: creating src/glog/vlog_is_on.h
config.status: creating src/glog/stl_logging.h
config.status: creating libglog.pc
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
'src/config.h' -> 'bazel-out/host/bin/external/com_github_glog_glog/config.h.tmp'
'src/glog/logging.h' -> 'bazel-out/host/bin/external/com_github_glog_glog/src/glog/logging.h.tmp'
'src/glog/raw_logging.h' -> 'bazel-out/host/bin/external/com_github_glog_glog/src/glog/raw_logging.h'
'src/glog/stl_logging.h' -> 'bazel-out/host/bin/external/com_github_glog_glog/src/glog/stl_logging.h'
'src/glog/vlog_is_on.h' -> 'bazel-out/host/bin/external/com_github_glog_glog/src/glog/vlog_is_on.h'
INFO: From Executing genrule @com_github_glog_glog//:run_configure:
/home/ragavendranbala/.cache/bazel/_bazel_ragavendranbala/ca095b8d7785365d6fd2a99a0df770f1/sandbox/linux-sandbox/14/execroot/mediapipe/external/com_github_glog_glog/missing: Unknown `--is-lightweight' option
Try `/home/ragavendranbala/.cache/bazel/_bazel_ragavendranbala/ca095b8d7785365d6fd2a99a0df770f1/sandbox/linux-sandbox/14/execroot/mediapipe/external/com_github_glog_glog/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for ANSI C header files... (cached) no
checking for stdint.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for unistd.h... (cached) yes
checking syscall.h usability... yes
checking syscall.h presence... yes
checking for syscall.h... yes
checking sys/syscall.h usability... yes
checking sys/syscall.h presence... yes
checking for sys/syscall.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking libunwind.h usability... no
checking libunwind.h presence... no
checking for libunwind.h... no
checking ucontext.h usability... yes
checking ucontext.h presence... yes
checking for ucontext.h... yes
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... yes
checking for sys/utsname.h... yes
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking glob.h usability... yes
checking glob.h presence... yes
checking for glob.h... yes
checking unwind.h usability... yes
checking unwind.h presence... yes
checking for unwind.h... yes
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking size of void *... 8
checking for uint16_t... yes
checking for u_int16_t... yes
checking for __uint16... no
checking for sigaltstack... yes
checking for sigaction... yes
checking for dladdr... no
checking for fcntl... yes
checking for pread... yes
checking for pwrite... yes
checking for __attribute__... yes
checking for __builtin_expect... yes
checking for __sync_val_compare_and_swap... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -pthread is sufficient with -shared... yes
checking for pthread_self in -lpthread... yes
checking for main in -lgflags... no
checking for gtest-config... no
checking for main in -lgtest... no
checking support for pthread_rwlock_* functions... yes
checking whether the compiler implements namespaces... yes
checking what namespace STL code is in... std
checking whether compiler supports using ::operator<<... 1
checking for ucontext.h... (cached) yes
checking sys/ucontext.h usability... yes
checking sys/ucontext.h presence... yes
checking for sys/ucontext.h... yes
checking how to access the program counter from a struct ucontext... uc_mcontext.gregs[REG_RIP]
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/glog/logging.h
config.status: creating src/glog/raw_logging.h
config.status: creating src/glog/vlog_is_on.h
config.status: creating src/glog/stl_logging.h
config.status: creating libglog.pc
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
'src/config.h' -> 'bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/config.h.tmp'
'src/glog/logging.h' -> 'bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/src/glog/logging.h.tmp'
'src/glog/raw_logging.h' -> 'bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/src/glog/raw_logging.h'
'src/glog/stl_logging.h' -> 'bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/src/glog/stl_logging.h'
'src/glog/vlog_is_on.h' -> 'bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/src/glog/vlog_is_on.h'
INFO: From Executing genrule @com_github_glog_glog//:config_h:
select bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/config.h.android_arm to be the glog config file.
INFO: From Executing genrule @com_github_glog_glog//:logging_h:
select bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog/src/glog/logging.h.arm to be the glog logging.h file.
INFO: From Executing genrule @com_github_glog_glog//:logging_h [for host]:
select bazel-out/host/bin/external/com_github_glog_glog/src/glog/logging.h.tmp to be the glog logging.h file.
INFO: From Executing genrule @com_github_glog_glog//:config_h [for host]:
select bazel-out/host/bin/external/com_github_glog_glog/config.h.tmp to be the glog config file.
[261 / 1,065] 128 actions, 4 running
ERROR: /home/ragavendranbala/.cache/bazel/_bazel_ragavendranbala/ca095b8d7785365d6fd2a99a0df770f1/external/maven/BUILD:548:1: AarResourcesExtractor external/maven/_aar/unzipped/resources/androidx_lifecycle_lifecycle_runtime failed (Exit 127): aar_resources_extractor failed: error executing command 
  (cd /home/ragavendranbala/.cache/bazel/_bazel_ragavendranbala/ca095b8d7785365d6fd2a99a0df770f1/sandbox/linux-sandbox/216/execroot/mediapipe && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor --input_aar external/maven/v1/https/maven.google.com/androidx/lifecycle/lifecycle-runtime/2.1.0-rc01/lifecycle-runtime-2.1.0-rc01.aar --output_res_dir bazel-out/android-arm64-v8a-opt/bin/external/maven/_aar/unzipped/resources/androidx_lifecycle_lifecycle_runtime --output_assets_dir bazel-out/android-arm64-v8a-opt/bin/external/maven/_aar/unzipped/assets/androidx_lifecycle_lifecycle_runtime)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox aar_resources_extractor failed: error executing command 
  (cd /home/ragavendranbala/.cache/bazel/_bazel_ragavendranbala/ca095b8d7785365d6fd2a99a0df770f1/sandbox/linux-sandbox/216/execroot/mediapipe && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  bazel-out/host/bin/external/bazel_tools/tools/android/aar_resources_extractor --input_aar external/maven/v1/https/maven.google.com/androidx/lifecycle/lifecycle-runtime/2.1.0-rc01/lifecycle-runtime-2.1.0-rc01.aar --output_res_dir bazel-out/android-arm64-v8a-opt/bin/external/maven/_aar/unzipped/resources/androidx_lifecycle_lifecycle_runtime --output_assets_dir bazel-out/android-arm64-v8a-opt/bin/external/maven/_aar/unzipped/assets/androidx_lifecycle_lifecycle_runtime)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/env: 'python': No such file or directory
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu:facemeshgpu failed to build
INFO: Elapsed time: 716.144s, Critical Path: 197.54s
INFO: 213 processes: 213 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by jiuqiant** [comment]
The erro is `/usr/bin/env: 'python': No such file or directory`.  Have you installed Python?

**Comment by ragavendranbala** [comment]
@jiuqiant  python is already installed with ubuntu, I'm using that

**Comment by ragavendranbala** [comment]
@jiuqiant thanks for the info. I have used ls command to make the python3 to work in /usr/bin/env

Thank you for helping me to find the exact issue
