### ISSUE TITLE
Hand pose estimation - depth map

### ISSUE THREAD

**Issue by rhebbalaguppe** [google/mediapipe#71]
Dear Authors, For hand pose estimation. I would like to know - which is the node which is estimating depth? Is it a pretrained model that computes Z and hence the node is not visible in the graph ? Thanks

**Comment by mgyong** [comment]
Pls read details of the hand tracking here https://mediapipe.page.link/handgoogleaiblog
The [code](https://hand.mediapipe.dev) for the 3D hand tracking

**Comment by chuoling** [comment]
To add to the answer, the Z coordinate of each landscape (in addition to X and Y) is estimated by the 3D version of the hand landmark ML model https://github.com/google/mediapipe/blob/master/mediapipe/models/hand_landmark_3d.tflite.
