### ISSUE TITLE
how to recognize gesture including “Thumb up”, “OK”, “Rock” in  3d coordinate? 

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#710]
I complete gesture  recognition in 2D , when i use multiHandTrack app with 3D   , x and y is normalized , but z is not normalized ,so how can i compute  angles of joints ?
Reference section  “Gesture Recognition ” in  https://ai.googleblog.com/2019/08/on-device-real-time-hand-tracking-with.html

**Comment by dolmens** [comment]
There is a 2d implementation:

https://gist.github.com/TheJLifeX/74958cc59db477a91837244ff598ef4a

**Comment by chensisi0730** [comment]
How to define X ，Y，z  coordinate system ? where is coordinate origin ?

**Comment by eknight7** [comment]
@chensisi0730 check out https://github.com/google/mediapipe/issues/742#issuecomment-637162399 for the origin info.

**Comment by mmm2016** [comment]
Implemented on Android:
https://github.com/mmm2016/mediapipemultihandstrackingapp

**Comment by fanzhanggoogle** [comment]
Feel free to re-open if there's any further discussion.
