### ISSUE TITLE
Crash in TFLiteConverterCalculator

### ISSUE THREAD

**Issue by thuanvh** [google/mediapipe#711]
Hello,
I am trying to build a Windows version of Mediapipe. But initialization of graph I get an error :

ERROR: Invalid tensor index -1125130728 in inputs. The subgraph has 1 tensors

I run debug and the error triggered on [line 255](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_converter_calculator.cc#L255)

I do not know why this error happened. Why we initialize an interpreter and assign simple value that could cause error. I build with branch master of tensorflow. Do you have any suggestion?

Any suggestion is welcomed, thank you very much.

**Comment by jiuqiant** [comment]
I am working on a similar task to port MediaPipe to Windows and my implementation seems working. For example, the object detection tflite demo is working:
<img width="1554" alt="Screen Shot 2020-05-12 at 2 19 25 PM" src="https://user-images.githubusercontent.com/3359144/81747079-5b6d1900-945c-11ea-8fc3-1217da1d8b7f.png">


Which target are you building? I can try the same command with my implementation.

**Comment by thuanvh** [comment]
Awesome, I am building a face detection with Visual Studio, not using bazel.
I take a look and find that might be caused by different flags compilation between call bazel and Visualstudio. I checked it by create an empty project in Visualstudio and call tflite dll. And the error happened.
Error detail is when I send a vector size 1 to tflite interpreter, but interpreter tells that it receive a bigger vector.
So, it is not error in mediapipe.
@jiuqiant , could you share your current work?

**Comment by jiuqiant** [comment]
The coming release will have the minimum Windows support. 
Most portability fixes will be available in the coming release and I can document the necessary steps in this thread if any portability fixes are not checked in.

**Comment by thuanvh** [comment]
Currently, I build it ok. But running facedetection get crashed. After run through TFLiteConverterCalculator, it crashed in [InputStreamHandler::ClearCurrentInputs](https://github.com/google/mediapipe/blob/master/mediapipe/framework/input_stream_handler.cc#L308), and [InputStreamShard::ClearCurrentPacket, packet_queue_.pop](https://github.com/google/mediapipe/blob/master/mediapipe/framework/input_stream_shard.h#L66) cause system crash.
I think that maybe caused by thread_pool. Is it possible not use threadpool, we just run step by step in mediapipe?

**Comment by jiuqiant** [comment]
The Windows support is released. See https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows

**Comment by thuanvh** [comment]
I checked it, and it runs flawlessly. Thank you very much
