### ISSUE TITLE
Use build aar, crash

### ISSUE THREAD

**Issue by teleger** [google/mediapipe#713]
1.My whole thing is running on android
2.I have compiled the aar package

I compiled the aar package according to the following instructions

bazel build --cxxopt='--std=c++14' -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a     //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar --host_crosstool_top=@bazel_tools//tools/cpp:toolchain

new directory
apps/aar_example　　

The BUILD file in this directory, For Example 

load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_face_detection_aar",
    calculators = ["//mediapipe/graphs/face_detection:mobile_calculators"],
)

then，I  have   mp_face_detection_aar 　　package

3.   I put the resulting aar package into the new project and added such dependencies to the build.gradle file of the project

    implementation files('libs/mp_face_detection_aar.aar','libs/mp_face_detection_aar.aar')
    implementation 'com.google.flogger:flogger:0.3.1'
    implementation 'com.google.flogger:flogger-system-backend:0.3.1'
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
    implementation 'com.google.guava:guava:27.0.1-android'
    implementation 'com.google.guava:guava:27.0.1-android'
    implementation 'com.google.protobuf:protobuf-java:3.11.4'
    // CameraX core library
    def camerax_version = "1.0.0-alpha06"
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"

4.When  I   Run  apk，things open：

2020-05-13 16:15:49.828 6416-6423/? E/zygote64: Failed sending reply to debugger: Broken pipe
2020-05-13 16:15:50.334 6416-6416/? E/libEGL: validate_display:92 error 3008 (EGL_BAD_DISPLAY)
2020-05-13 16:15:51.704 6416-6450/com.jenkolux.faceprojectcpu E/native: E0513 08:15:51.704207  6450 graph.cc:407] ValidatedGraphConfig Initialization failed.
    No registered object with name: OpenCvImageEncoderCalculator; Unable to find Calculator "OpenCvImageEncoderCalculator"
    AnnotationOverlayCalculator::GetContract failed to validate: 
    For input streams ValidatePacketTypeSet failed:
    Tag "INPUT_FRAME" index 0 was not expected.
    For output streams ValidatePacketTypeSet failed:
    Tag "OUTPUT_FRAME" index 0 was not expected.

En,it crash !

Is it because of the problem of EGL or some problems? I am looking forward to trying to solve it in which direction. Thank you very much~

**Comment by jiuqiant** [comment]
Hi, the error is `No registered object with name: OpenCvImageEncoderCalculator`. Basically, all the calculators used by your graph need to be listed in the `calculators` field of the mediapipe_aar rule. However, ["//mediapipe/graphs/face_detection:mobile_calculators"](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/BUILD#L19) doesn't have opencv_image_encoder_calculator. To have OpenCvImageEncoderCalculator, you need to write
```
mediapipe_aar(
  name = "mp_face_detection_aar",
  calculators = [
    "//mediapipe/graphs/face_detection:mobile_calculators",
    "//mediapipe/calculators/image:opencv_image_encoder_calculator"
  ],
)
```

**Comment by teleger** [comment]
After I recompile the aar, the system can't find the symbol. What should I do？

example　　open:

    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN2cv8imencodeERKNS_6StringERKNS_11_InputArrayERNSt6__ndk16vectorIhNS6_9allocatorIhEEEERKNS7_IiNS8_IiEEEE" referenced by "/data/app/c
OZZnwoIJPvuS4BsBm1v-g==/lib/arm64/libmediapipe_jni.so".

add opencv_image_encoder_calculator 　after，

What should I do to try and solve it？ Thank you very much~

**Comment by jiuqiant** [comment]
Hi, the error message means it can't find the `imencode` symbol in `libopencv_java3.so`. MediaPipe uses [the official OpenCV Android SDK](https://github.com/google/mediapipe/blob/master/WORKSPACE#L186) and I am not sure why the `imencode` symbol can't be found. Another possibility is OpenCV 3  Android SDK is built on an earlier version of Android NDK and MediaPipe is on a recent one. You may switch to OpenCV 4 Android SDK to give a try. Here is how to do the switch: 

```
# Switch to OpenCV 4
sed -i -e 's:3.4.3/opencv-3.4.3:4.0.1/opencv-4.0.1:g' WORKSPACE
sed -i -e 's:libopencv_java3:libopencv_java4:g' third_party/opencv_android.BUILD

# Switch back to OpenCV 3
sed -i -e 's:4.0.1/opencv-4.0.1:3.4.3/opencv-3.4.3:g' WORKSPACE
sed -i -e 's:libopencv_java4:libopencv_java3:g' third_party/opencv_android.BUILD
```

**Comment by fiveshit** [comment]
hi @jiuqiant 
I met same problem,
```
dlopen failed: cannot locate symbol "_ZN2cv8imencodeERKNS_6StringERKNS_11_InputArrayERNSt6__ndk16vectorIhNS6_9allocatorIhEEEERKNS7_IiNS8_IiEEEE" 
```
but I tried your solutions that it's failed. Do you have more solutions for this problem?

**Comment by fiveshit** [comment]
hi @teleger 
I wondering to know Do you fixed this promble?
