### ISSUE TITLE
yt8m feature extraction 

### ISSUE THREAD

**Issue by sahu-ji** [google/mediapipe#714]
Is there a way to extract the yt8m-like audio and video features from raw videos using mediapipe at a rate other than 1 second?

**Comment by jiuqiant** [comment]
Yes, you can achieve this by changing the frame_rate [here](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/youtube8m/feature_extraction.pbtxt#L23).

**Comment by sahu-ji** [comment]
Thank you!!
