### ISSUE TITLE
face mesh keypoint

### ISSUE THREAD

**Issue by wangqiang624731186** [google/mediapipe#716]
![Screenshot from 2020-05-19 14-25-55](https://user-images.githubusercontent.com/8408923/82292297-3c7f0180-99dd-11ea-8dfb-f835b18b938f.png)
![Screenshot from 2020-05-19 14-26-08](https://user-images.githubusercontent.com/8408923/82292304-3ee15b80-99dd-11ea-92e7-bf212c6c3698.png)
i use  mediapipe/modules/face_detection/face_detection_front.tflite   and   mediapipe/modules/face_landmark/face_landmark.tflite to calculate face landmark
but  keypoint is not correct, possible reason ?

**Comment by jiuqiant** [comment]
Can you provide more context here? Which example are you running?

**Comment by fanzhanggoogle** [comment]
Are you using MP inference pipeline? The face need to be cropped and rotated in a proper way as the landmark model is sensitive to the face crop/orientation.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
