### ISSUE TITLE
Switch to the opencv4, use build aar, crash

### ISSUE THREAD

**Issue by liaohong** [google/mediapipe#718]
Switch to the opencv4, use build aar, crash:
uncaughtException:dlopen failed: library "libc++_shared.so" not found,
How to deal with it?

**Comment by jiuqiant** [comment]
It's more like a question to Bazel. See a similar one: https://github.com/bazelbuild/bazel/issues/10117.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by hangqiu** [comment]
But what's the solution?
