### ISSUE TITLE
Landmarks missing with file input

### ISSUE THREAD

**Issue by ratswen** [google/mediapipe#719]
i modified the graph 'multi_hand_tracking_mobile.pbtxt', and added this output_stream as an output of the graph. 
`calculator: "MultiHandLandmarkSubgraph"
  output_stream: "LANDMARKS:multi_hand_landmarks"
`
When I logged out the landmarks, I found when input is camera it works ok. but when input is a video file landmarks rendered in the picture but not in the logs.

**Comment by mgyong** [comment]
Can you provide your code repository?
