### ISSUE TITLE
HelloWorld on adnroid Build error: maven coursier java not found 

### ISSUE THREAD

**Issue by Alpatzino** [google/mediapipe#72]
Hey guys,

I succesfully got the HelloWorld example on desktop to work. For the next step I try to get the HelloWorld on Android to work to establish a connection to the android. I follow your instruction and when I try to build it with 

> bazel build -c opt --config=android_arm64 $APPLICATION_PATH
 following errors occur:

`RROR: An error occurred during the fetch of repository 'maven':
   Unable to run coursier: /home/alpatzino/.cache/bazel/_bazel_alpatzino/22f861c66ebe9620d7a9bb73f2740fb6/external/maven/coursier: line 2: exec: java: not found
ERROR: /home/alpatzino/Desktop/mediapipe/third_party/BUILD:79:1: //third_party:androidx_appcompat depends on @maven//:androidx_appcompat_appcompat in repository @maven which failed to fetch. no such package '@maven//': Unable to run coursier: /home/alpatzino/.cache/bazel/_bazel_alpatzino/22f861c66ebe9620d7a9bb73f2740fb6/external/maven/coursier: line 2: exec: java: not found
ERROR: /home/alpatzino/Desktop/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/helloworld/BUILD:1:1: no such target '//third_party:android_constraint_layout': target 'android_constraint_layout' not declared in package 'third_party' (did you mean 'androidx_constraint_layout'?) defined by /home/alpatzino/Desktop/mediapipe/third_party/BUILD and referenced by '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/helloworld:mediapipe_lib'
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/helloworld:helloworld' failed; build aborted: no such package '@maven//': Unable to run coursier: /home/alpatzino/.cache/bazel/_bazel_alpatzino/22f861c66ebe9620d7a9bb73f2740fb6/external/maven/coursier: line 2: exec: java: not found
`

It seems that bazel can't fetch sth. via maven/coursier. As I am not really firm what bazel is trying to get and the internet doesnt provide any information on this issue, I am stuck here.

Thanks for your help

**Comment by mgyong** [comment]
You android build environment NDK or SDK is not setup properly. Pls run [android sdk ndk setup script](https://github.com/google/mediapipe/blob/master/setup_android_sdk_and_ndk.sh)

**Comment by Alpatzino** [comment]
Hi there,
Thanks i had Sdk and ndk manually installed. But Java was not set up on the system what was going unchecked. The setup_andoird_sdk_and_ndk.sh showed me this issue.

NOTE: Use the openjdk-8, the default-jre install version 11 which causes compiler issues.

Thank you :)
