### ISSUE TITLE
which bazel version should I use for ios?

### ISSUE THREAD

**Issue by JustinYangJing** [google/mediapipe#722]
I installed bazel via brew, Following the "Installing on macOS" guideline. but i saw 1.1.0 version of bazel need install in mediapipe_ios_setup.md.  what exactly version should I use? 
Now I use the following versoin ,  but the Generate botton of Tulsi APP is disable, I am sure the bazel path is correct selected. 
Bazel version 2.0.0
xcode verison 11.4.1
 
I am just for the ios ,  do i need Install OpenCV and FFmpeg following the "Installing on macOS" guideline?

**Comment by jiuqiant** [comment]
Sorry for the confusion. Please use bazel 2.0.0 and above.
