### ISSUE TITLE
Steps to fix Windows Python Configuration issue manually

### ISSUE THREAD

**Issue by jiuqiant** [google/mediapipe#724]
If you see an unicode error when building MediaPipe on Windows:
```
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/username/_bazel_username/zbffnwmd/external/org_tensorflow/third_party/py/python_configure.bzl", line 210       
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/username/_bazel_username/zbffnwmd/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/username/_bazel_username/zbffnwmd/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

please do the following steps to fix it manually.

Step 1. Open the python_configure.bzl file, in my example the file path is `C:/users/username/_bazel_username/zbffnwmd/external/org_tensorflow/third_party/py/python_configure.bzl`, and edit line 128 to be:

```
cmd += "system(\"%s script.py\");" % python_bin.replace("\\","/")
```

Step 2. Rerun the build command. Then, you can go further and see another error "invalid escape sequence".

```
ERROR
C:/users/username/_bazel_username/zbffnwmd/external/local_execution_config_python/BUILD:11:24: invalid escape sequence: \U     
ERROR: C:/users/username/_bazel_username/zbffnwmd/external/local_execution_config_python/BUILD:17:24: invalid escape sequence: \U 
```

Step 3. Open the BUILD file, in my example the file path is `C:/users/username/_bazel_username/zbffnwmd/external/local_execution_config_python/BUILD`, and replace every \ with \\\ at line 11 and 17.

Step 4. Continue the build process.

**Comment by jianshuo** [comment]
I am pretty sure that the reason is PYTHON_BIN_PATH is not set. You can try to echo it to see if there is a path in it:

echo $PYTHON_BIN_PATH

In the file "python_configure.bzl" mentioned above, it states to use this environment to run python script, and the first import in the whole project happens to be numpy. It complains numpy module is not found because either numpy is not installed (well, it was my case in a brand new computer), or the python interpreter cannot be found. For the later, the solution is very simple:

export PYTHON_BIN_PATH=/usr/bin/python3

If you can run this :

$PYTHON_BIN_PATH -c 'import numpy'

without problem, you should be fine to run this part of the program.

**Comment by rahulvenkat** [comment]
> I am pretty sure that the reason is PYTHON_BIN_PATH is not set. You can try to echo it to see if there is a path in it:
> 
> echo $PYTHON_BIN_PATH
> 
> In the file "python_configure.bzl" mentioned above, it states to use this environment to run python script, and the first import in the whole project happens to be numpy. It complains numpy module is not found because either numpy is not installed (well, it was my case in a brand new computer), or the python interpreter cannot be found. For the later, the solution is very simple:
> 
> export PYTHON_BIN_PATH=/usr/bin/python3
> 
> If you can run this :
> 
> $PYTHON_BIN_PATH -c 'import numpy'
> 
> without problem, you should be fine to run this part of the program.

This worked like a charm! I had to additionally install numpy using "sudo apt-get install python3-numpy"

**Comment by Meera0212** [comment]
@jiuqiant  I am getting same error on windows after and edit line 128 to :
`cmd += "system(\"%s script.py\");" % python_bin.replace("\\","/")`

Before editing this line and after edit this line I am getting same error as below :

`Repository rule local_python_configure defined at:
  C:/users/ambaliya/_bazel_ambaliya/3rnvncgu/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/ambaliya/_bazel_ambaliya/3rnvncgu/external/org_tensorflow/third_party/py/python_configure.bzl", line 208
                get_python_bin(repository_ctx)
        File "C:/users/ambaliya/_bazel_ambaliya/3rnvncgu/external/org_tensorflow/third_party/remote_config/common.bzl", line 44, in get_python_bin
                which(repository_ctx, "python")
        File "C:/users/ambaliya/_bazel_ambaliya/3rnvncgu/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, in which
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/ambaliya/_bazel_ambaliya/3rnvncgu/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
INFO: Could not find files for the given pattern(s).`

There is no BUID file according to your **step 3**
`C:\Users\Ambaliya\_bazel_Ambaliya\3rnvncgu\external\local_execution_config_python`

This my build command : **bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_face_detection_aar**

**Comment by tonysmarthome** [comment]
> > I am pretty sure that the reason is PYTHON_BIN_PATH is not set. You can try to echo it to see if there is a path in it:
> > echo $PYTHON_BIN_PATH
> > In the file "python_configure.bzl" mentioned above, it states to use this environment to run python script, and the first import in the whole project happens to be numpy. It complains numpy module is not found because either numpy is not installed (well, it was my case in a brand new computer), or the python interpreter cannot be found. For the later, the solution is very simple:
> > export PYTHON_BIN_PATH=/usr/bin/python3
> > If you can run this :
> > $PYTHON_BIN_PATH -c 'import numpy'
> > without problem, you should be fine to run this part of the program.
> 
> This worked like a charm! I had to additionally install numpy using "sudo apt-get install python3-numpy"

Absolutely Works!

**Comment by progmars** [comment]
Now for me Bazel still failed to launch - at first the checks failed for BIN and then for LIB paths.


I had to do the following ugly hack to disable the checks in python_configure.bzl:

```
def _check_python_lib(repository_ctx, python_lib):
    """Checks the python lib path."""
    cmd = 'test -d "%s" -a -x "%s"' % (python_lib, python_lib)
    result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
    # if result.return_code == 1:
    #    auto_config_fail("Invalid python library path: %s" % python_lib)

def _check_python_bin(repository_ctx, python_bin):
    """Checks the python bin path."""
    cmd = '[[ -x "%s" ]] && [[ ! -d "%s" ]]' % (python_bin, python_bin)
    result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
    # if result.return_code == 1:
    #    auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
    #        PYTHON_BIN_PATH,
    #        python_bin,
    #    ))
```

And then I ran Bazel with the following command:

```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D:\\GAN\\Anaconda\\python.exe" --action_env PYTHON_LIB_PATH="D:\\GAN\\Anaconda\\Lib" mediapipe/examples/desktop/hello_world
```

It reported `Build completed successfully, 675 total actions` however, the resulting hello_world.exe outputs nothing - no "Hello, world!" messages as described in the tutorial. Not sure why, maybe that's a different issue.

Noticed also a warning during build, not sure if it's relevant:
`http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz GET returned 404 Not Found`

**Comment by KabLov92** [comment]
Just in case someone is trying these fixes but still has issues, please check all these:
echo %ANDROID_HOME%
echo %ANDROID_NDK_HOME%
echo %JAVA_HOME%
and check that the opencv build path in your WORKSPACE file is correct

**Comment by PriyavartRajain** [comment]
Unfortunately, It still does not work for me. I am on windows, and here are the errors: 

ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//rajai//AppData//Local//Programs//Python//Python37' is not executable. Is it the python binary?
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//rajai//AppData//Local//Programs//Python//Python37' is not executable. Is it the python binary?
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "6f2d1911cdd0aaeecac686cfee4ee1ff0d1f3382045e1671551e237fc3cbbb47"
DEBUG: Repository rules_cc instantiated at:
  C:/users/rajai/mediapipe_repo/mediapipe/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/rajai/_bazel_rajai/y4gtkfyw/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C://Users//rajai//AppData//Local//Programs//Python//Python37' is not executable. Is it the python binary?
INFO: Elapsed time: 0.481s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

Could someone please help me out? Thank you!!

**Comment by PriyavartRajain** [comment]
@homuler thanks for the response! I changed the path to what you suggested but now i am getting this error: 

C:\Users\rajai\mediapipe_repo\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//rajai//AppData//Local//Programs//Python//Python37//python.exe" mediapipe/examples/desktop/hello_world
DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (1 packages loaded, 327 targets configured).
INFO: Found 1 target...

ERROR: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/com_github_glog_glog/BUILD:5:13: Compiling src/symbolize.cc failed: (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 39 argument(s) skipped)
C:\users\rajai\_bazel_rajai\y4gtkfyw\execroot\mediapipe\external\com_github_glog_glog\src\base/mutex.h(129): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.845s, Critical Path: 0.93s
INFO: 129 processes: 129 internal.
FAILED: Build did NOT complete successfully

Any idea how to fix this? I really appreciate the help!

**Comment by tgd-git** [comment]
> @homuler thanks for the response! I changed the path to what you suggested but now i am getting this error:
> 
> C:\Users\rajai\mediapipe_repo\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//rajai//AppData//Local//Programs//Python//Python37//python.exe" mediapipe/examples/desktop/hello_world DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14: Warning: skipping import of repository 'com_google_absl' because it already exists. DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14: Warning: skipping import of repository 'com_google_protobuf' because it already exists. DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14: Warning: skipping import of repository 'com_google_googletest' because it already exists. DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14: Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists. DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14: Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists. DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14: Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists. DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14: Warning: skipping import of repository 'build_bazel_apple_support' because it already exists. DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14: Warning: skipping import of repository 'bazel_skylib' because it already exists. DEBUG: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/repo.bzl:109:14: Warning: skipping import of repository 'pybind11' because it already exists. INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (1 packages loaded, 327 targets configured). INFO: Found 1 target...
> 
> ERROR: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/com_github_glog_glog/BUILD:5:13: Compiling src/symbolize.cc failed: (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 39 argument(s) skipped) C:\users\rajai_bazel_rajai\y4gtkfyw\execroot\mediapipe\external\com_github_glog_glog\src\base/mutex.h(129): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory Target //mediapipe/examples/desktop/hello_world:hello_world failed to build Use --verbose_failures to see the command lines of failed build steps. INFO: Elapsed time: 3.845s, Critical Path: 0.93s INFO: 129 processes: 129 internal. FAILED: Build did NOT complete successfully
> 
> Any idea how to fix this? I really appreciate the help!

Getting the same error, anyone a hint?

`ERROR: C:/users/user/_bazel_user/o7dgz4zy/external/com_google_absl/absl/debugging/BUILD.bazel:31:11: Compiling absl/debugging/stacktrace.cc failed: (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 41 argument(s) skipped)` 

Using Bazel 4.1, VS 2019

**Comment by nguyenvanhuan11061998** [comment]
> Unfortunately, It still does not work for me. I am on windows, and here are the errors:
> 
> ERROR: An error occurred during the fetch of repository 'local_execution_config_python': Traceback (most recent call last): File "C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository _check_python_bin(repository_ctx, python_bin) File "C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % ( File "C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg)) Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//rajai//AppData//Local//Programs//Python//Python37' is not executable. Is it the python binary? ERROR: Error fetching repository: Traceback (most recent call last): File "C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository _check_python_bin(repository_ctx, python_bin) File "C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % ( File "C:/users/rajai/_bazel_rajai/y4gtkfyw/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg)) Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C://Users//rajai//AppData//Local//Programs//Python//Python37' is not executable. Is it the python binary? DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "6f2d1911cdd0aaeecac686cfee4ee1ff0d1f3382045e1671551e237fc3cbbb47" DEBUG: Repository rules_cc instantiated at: C:/users/rajai/mediapipe_repo/mediapipe/WORKSPACE:36:13: in Repository rule http_archive defined at: C:/users/rajai/_bazel_rajai/y4gtkfyw/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C://Users//rajai//AppData//Local//Programs//Python//Python37' is not executable. Is it the python binary? INFO: Elapsed time: 0.481s INFO: 0 processes. FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
> 
> Could someone please help me out? Thank you!!



> 
Did you check python.exe path again? you can see it here https://stackoverflow.com/questions/749711/how-to-get-the-python-exe-location-programmatically

**Comment by nurshafiza** [comment]
> @PriyavartRajain @isra60 You may have run commands with `--action_env PYTHON_BIN_PATH="C://Users//rajai//AppData//Local//Programs//Python//Python37"`, but `PYTHON_BIN_PATH` is expected to be set to the path to the python executable , so you should do like this:
> 
> ```shell
> --action_env PYTHON_BIN_PATH="C://Users//rajai//AppData//Local//Programs//Python//Python37//python.exe"
> ```

hi. I've faced same problem as @PriyavartRajain and have follow step above as you recommended but the error that occur after I run the command is still same. can anyone help me here?

**Comment by AndreiBazzaev** [comment]
I still have this issue on Windows: 
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//79155//AppData//Local//Programs//Python//Python311//python.exe" mediapipe/examples/desktop/hello_world
results in ERROR:  An error occurred during the fetch of repository 'local_execution_config_python':
Would appreciate any help.

**Comment by AndreiBazzaev** [comment]
> I still have this issue on Windows: bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//79155//AppData//Local//Programs//Python//Python311//python.exe" mediapipe/examples/desktop/hello_world results in ERROR: An error occurred during the fetch of repository 'local_execution_config_python': Would appreciate any help.

Was able to fix an issue, following steps from here, hope it would help others like me: https://blog.csdn.net/HW140701/article/details/119546019

**Comment by AlvaroMFO** [comment]
> If you see an unicode error when building MediaPipe on Windows:
> 
> ```
> ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
>    Traceback (most recent call last):
>         File "C:/users/username/_bazel_username/zbffnwmd/external/org_tensorflow/third_party/py/python_configure.bzl", line 210       
>                 _get_python_lib(repository_ctx, <1 more arguments>)
>         File "C:/users/username/_bazel_username/zbffnwmd/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, in _get_python_lib
>                 execute(repository_ctx, <1 more arguments>)
>         File "C:/users/username/_bazel_username/zbffnwmd/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
>                 fail(<1 more arguments>)
> Repository command failed
> File "<string>", line 1
> SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
> ```
> 
> please do the following steps to fix it manually.
> 
> Step 1. Open the python_configure.bzl file, in my example the file path is `C:/users/username/_bazel_username/zbffnwmd/external/org_tensorflow/third_party/py/python_configure.bzl`, and edit line 128 to be:
> 
> ```
> cmd += "system(\"%s script.py\");" % python_bin.replace("\\","/")
> ```
> 
> Step 2. Rerun the build command. Then, you can go further and see another error "invalid escape sequence".
> 
> ```
> ERROR
> C:/users/username/_bazel_username/zbffnwmd/external/local_execution_config_python/BUILD:11:24: invalid escape sequence: \U     
> ERROR: C:/users/username/_bazel_username/zbffnwmd/external/local_execution_config_python/BUILD:17:24: invalid escape sequence: \U 
> ```
> 
> Step 3. Open the BUILD file, in my example the file path is `C:/users/username/_bazel_username/zbffnwmd/external/local_execution_config_python/BUILD`, and replace every \ with \\ at line 11 and 17.
> 
> Step 4. Continue the build process.

Hello!

I was having the same unicode error when running the bazel build command. I was setting the python binary path as "C:\Users\Alvaro\AppData\Local\Programs\Python\Python39\python.exe".

I tried editing the python_configure.bzl file following your steps, but when I rerunned the command it didn't recognized the "system" command.

I undid the changes on the python_configure.bzl file. And then I tried changing the python binary path to: "C://Users//Alvaro//AppData//Local//Programs//Python//Python39//python.exe". It worked!

Resuming - What worked for me was correcting the dashes as below:

"C:\Users\Alvaro\AppData\Local\Programs\Python\Python39\python.exe" -> "C://Users//Alvaro//AppData//Local//Programs//Python//Python39//python.exe"

My command line: bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//Alvaro//AppData//Local//Programs//Python//Python39//python.exe" mediapipe/examples/desktop/hello_world

**Comment by jinfagang** [comment]
fail(
Error in fail: Repository command failed
信息: 用提供的模式无法找到文件。
ERROR: F:/codes/metaverse/mocap_prototype/mediapipe_lib/WORKSPACE:482:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/jin/_bazel_jin/gns3ey5g/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/jin/_bazel_jin/gns3ey5g/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/users/jin/_bazel_jin/gns3ey5g/external/org_tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/users/jin/_bazel_jin/gns3ey5g/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/users/jin/_bazel_jin/gns3ey5g/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed


So stupid of bazle....

the python I changed 2 didffernt path, still nto work...

**Comment by mastirt** [comment]
```
ERROR: Traceback (most recent call last):
        File "C:/users/mahesa/_bazel_mahesa/wl6bzqgh/external/build_bazel_rules_apple/apple/internal/rule_support.bzl", line 217, column 36, in <toplevel>
                deps_cfg = apple_common.multi_arch_split,
Error: 'apple_common' value has no field or method 'multi_arch_split'
ERROR: error loading package 'mediapipe/gpu': at C:/users/mahesa/_bazel_mahesa/wl6bzqgh/external/build_bazel_rules_apple/apple/ios.bzl:33:5: at C:/users/mahesa/_bazel_mahesa/wl6bzqgh/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl:75:5: initialization of module 'apple/internal/rule_support.bzl' failed
ERROR: C:/users/mahesa/mediapipe_repo/mediapipe/mediapipe/framework/BUILD:1003:11: errors encountered resolving select() keys for //mediapipe/framework:port
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.779s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```
i'm stack in here, can anyone help me?

**Comment by KakaWan** [comment]
> ```
> ERROR: Traceback (most recent call last):
>         File "C:/users/mahesa/_bazel_mahesa/wl6bzqgh/external/build_bazel_rules_apple/apple/internal/rule_support.bzl", line 217, column 36, in <toplevel>
>                 deps_cfg = apple_common.multi_arch_split,
> Error: 'apple_common' value has no field or method 'multi_arch_split'
> ERROR: error loading package 'mediapipe/gpu': at C:/users/mahesa/_bazel_mahesa/wl6bzqgh/external/build_bazel_rules_apple/apple/ios.bzl:33:5: at C:/users/mahesa/_bazel_mahesa/wl6bzqgh/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl:75:5: initialization of module 'apple/internal/rule_support.bzl' failed
> ERROR: C:/users/mahesa/mediapipe_repo/mediapipe/mediapipe/framework/BUILD:1003:11: errors encountered resolving select() keys for //mediapipe/framework:port
> ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Analysis failed
> INFO: Elapsed time: 2.779s, Critical Path: 0.01s
> INFO: 1 process: 1 internal.
> ERROR: Build did NOT complete successfully
> ```
> 
> i'm stack in here, can anyone help me?

I've faced same problem...
Are you resolve the issue?
