### ISSUE TITLE
objectdetection3d sneaker exmple app crashing using AAR created file

### ISSUE THREAD

**Issue by SmartAndroidCoder** [google/mediapipe#727]
I have created AAR file but not able to run the application using created AAR file.
It is crashing on set **converter.setSurfaceTextureAndAttachToGLContext**.

**Apk created by me is crashing with an error. ==>**

![Screenshot_2020-05-22-18-24-49-961_com miui bugreport](https://user-images.githubusercontent.com/36336789/82670972-f4d1c300-9bf2-11ea-8c9e-c29e2145e3d9.jpg)

APK created using AAR less in size (43.33mb) as compare to APK created using (97.24 mb) [Bazel command ](bazel build -c opt --config android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d:objectdetection3d). 

**AAR File Bazel Command:**

bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a  //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_shoe_detection:mp_object_detection_3d_aar

**Binary graph File Bazel Command:**

bazel build -c opt mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d:binary_graph

**BUILD file**

load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_object_detection_3d_aar",
    calculators = ["//mediapipe/graphs/object_detection_3d:mobile_calculators"],
)

**Project assets**

![download](https://user-images.githubusercontent.com/36336789/82671486-c7394980-9bf3-11ea-91e2-85fe28f944a5.png)

**Comment by jiuqiant** [comment]
Can you successfully build and run the original object detection 3d demo?

**Comment by SmartAndroidCoder** [comment]
Thanks for responding.
I have resolved the crash issue. It is due to tflite model name miss-match as define in Graph "**objectron_detection_gpu.pbtxt**"

![image](https://user-images.githubusercontent.com/36336789/82985800-8b163800-9fa9-11ea-835a-8d75b5641438.png)


https://prnt.sc/sojsbv
![image](https://user-images.githubusercontent.com/36336789/82985829-95383680-9fa9-11ea-86a6-ec1c6afb110f.png)

**Comment by gurpreetdeveloping** [comment]
can i get the objectdetection3d sneaker AAR file

**Comment by honeykinng345** [comment]
@SmartAndroidCoder can you please share with me your project repository to detect shoes? I downloaded the project from the media pipe GitHub repo but did not run the project its a lot of files in it ... can you please share this separate repo?
