### ISSUE TITLE
PacketResamplerCalculator changes the output timestamp

### ISSUE THREAD

**Issue by dhtang** [google/mediapipe#729]
I notice that PacketResamplerCalculator changes the timestamp of output packets here:
https://github.com/google/mediapipe/blob/de4fbc10e62001795741cb6d0200a17a94a29b0f/mediapipe/calculators/core/packet_resampler_calculator.cc#L320

and here:
https://github.com/google/mediapipe/blob/de4fbc10e62001795741cb6d0200a17a94a29b0f/mediapipe/calculators/core/packet_resampler_calculator.cc#L323

This creates an issue if we would like to merge the outputs of the original stream and resampled stream later--they have different timestampes.

What's the rational of the this change? Can't you just use the received timestamp?

**Comment by hadon** [comment]
Hi danhangtang,

There is a mediapipe core calculator that does resampling without changing timestamps.  It's called PacketThinnerCalculator.  Like PacketResamplerCalculator, it accepts a desired framerate through its option named "period".  

I believe that PacketThinnerCalculator can only down-sample the input packet stream, so it can use the existing timestamps.  PacketResamplerCalculator can either downsample or upsample, so it needs to create some new timestamps at least during upsampling.  PacketResamplerCalculator is normally used to preprocess an input video stream, which then takes the place of the original input video stream.

**Comment by hadon** [comment]
Thanks for the question.  Closing this question now.
