### ISSUE TITLE
Bazel sync project with build file failed in Android Studio

### ISSUE THREAD

**Issue by SmartAndroidCoder** [google/mediapipe#730]
I have imported a project in android studio with the option **Generate from Build file**
**BUILD**
directories:
#readprojectsettings,e.g.,.bazelrc
.
-mediapipe/java
-mediapipe/examples/android
targets:
//mediapipe/examples/android/...:all
//mediapipe/java/...:all
android_sdk_platform:android-29

**I am facing sync error**

ERROR: /home/users/yogendra.singh/.cache/bazel/_bazel_yogendra.singh/2b078f59f89ffa98a61c405a3f330576/external/androidndk/BUILD.bazel:41:1: in cc_toolchain_suite rule @androidndk//:toolchain-libcpp: cc_toolchain_suite '@androidndk//:toolchain-libcpp' does not contain a toolchain for cpu 'k8'

![Screenshot](https://user-images.githubusercontent.com/36336789/82704055-9d027e80-9c29-11ea-939e-49985441893d.png)

 I'd really appreciate it if someone could share the correct way of doing it. Thanks!

**Comment by sheep94lion** [comment]
I met a similar problem. Have you solved it?
#402
