### ISSUE TITLE
TensorFlow or Keras model for blazeface face detection

### ISSUE THREAD

**Issue by metanav** [google/mediapipe#735]
Where can I find full saved model (not the converted tflite one)? Saved model without weight is also OK. If not possible, where can I find integer quantized tflite version?

**Comment by mgyong** [comment]
@metanav Pls see the coral quantized version https://github.com/google/mediapipe/blob/master/mediapipe/examples/coral/models/face-detector-quantized_edgetpu.tflite

**Comment by metanav** [comment]
@mgyong Thanks for your reply. I think coral quantized is optimized for Edge TPU. I need to run it on a microcontroller. So I expect INT8 Quantized. Or, if you publish model I can convert it to whatever I need.

**Comment by metanav** [comment]
Also, for transfer learning saved model would be beneficial. I do not understand what is preventing you from sharing the saved model?

**Comment by fanzhanggoogle** [comment]
Hi, unfortunately we current don't have plan to release the saved model. Sorry about that.
