### ISSUE TITLE
Mediapipe High memory usage & How to remove openCV from Mediapipe. 

### ISSUE THREAD

**Issue by usernexme** [google/mediapipe#736]
This is not exactly an issue. It is just question please answer somebody if it is possible.  
I am using mediapipe in my application & it is slowing down the overall performance of app. I concluded that it could be because of high memory usage. When I profile the mediapipe android demo apps (Hand-Tracking & segmentation) then I found that these demos are taking around 240 MB of RAM. Is there any way we can reduce the memory usage? 
Secondly,  I am using GPU modules only like Hand-Tracking GPU & Hair-Segmentation GPU but still I need to keep all .so files of opencv in my gradle project. Is there any way we can remove opencv? Because it is increasing the apk size as well memory usage during run time. 
Thank you

**Comment by usernexme** [comment]
Hi @jiuqiant  and @mcclanahoochie  any update or suggestion on this ?

**Comment by jiuqiant** [comment]
We have a solution to cut the memory usage by half. But, we are still working on it. @mcclanahoochie  can provide more info here.

For removing opencv, it's doable by modifying the source code. 
1) Remove those opencv related includes, such as "mediapipe/framework/port/opencv_imgproc_inc.h", "mediapipe/framework/port/opencv_core_inc.h", and "mediapipe/framework/formats/image_frame_opencv.h", from any calculators used by the graph. Moreover, you need to remove the opencv related code from the calculator source code as well. For example, you need to remove the ImageCroppingCalculator::RenderCpu() method from the image cropping calculator and replace [line 172](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/image/image_cropping_calculator.cc#L172) with `LOG(FATAL) << "OpenCV dependency is removed. No CPU rendering support for now.";`. 

2) Remove the opencv dependencies, such as "//mediapipe/framework/port:opencv_core" and "//mediapipe/framework/port:opencv_imgproc",  from the calculator build rule. For example, for image cropping calculator, you need to delete line 365 and line 366 [here](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/image/BUILD#L365).

3) In the java code, don't call `System.loadLibrary("opencv_java3")` or `System.loadLibrary("opencv_java4")`.

**Comment by usernexme** [comment]
@jiuqiant Thank you for your response. 
Waiting for update on reducing memory usage & if we will remove opencv from code then we will have problem in future to update mediapipe.

**Comment by mcclanahoochie** [comment]
update on memory usage in https://github.com/google/mediapipe/issues/969#issuecomment-667294219
