### ISSUE TITLE
Error in Knift build new index documentation

### ISSUE THREAD

**Issue by valdes** [google/mediapipe#737]
$ bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/template_matching:template_matching_tflite
$ **bazel-bin**/mediapipe/examples/desktop/template_matching/template_matching_tflite \
    --calculator_graph_config_file=mediapipe/graphs/template_matching/index_building.pbtxt \
    --input_side_packets="file_directory=<template image directory>,file_suffix='png',output_index_filename=<output index filename>"

The second command is incorrect, what is the correct one?

**Comment by jiuqiant** [comment]
Please fill in your own "template image directory" and "output index filename".
```
bazel-bin/mediapipe/examples/desktop/template_matching/template_matching_tflite
  --calculator_graph_config_file=mediapipe/graphs/template_matching/index_building.pbtxt
  --input_side_packets="file_directory=<template image directory>,file_suffix=png,output_index_filename=<output index filename>"
```

**Comment by valdes** [comment]
That is not the problem, the problem is what is "bazel-bin/mediapipe/examples/desktop/template_matching/template_matching_tflite"
