### ISSUE TITLE
Using other models

### ISSUE THREAD

**Issue by Zumbalamambo** [google/mediapipe#738]
I'm trying to learn how to use this framework. How do I use mediapipe in conjunction with YOLO or SSD?

**Comment by mcclanahoochie** [comment]
Almost all MediaPipe examples follow a simple general template/flow:

1. Input image
2. Preprocess input image (image->tensor)
3. ML model inference (tensor->tensor)
4. Post process tensors (tensor->metadata)
5. Render (metadata->image)

The closest example to YOLO and SSD we have (and probably simplest ML example) is [object detection](https://mediapipe.readthedocs.io/en/latest/object_detection_mobile_gpu.html)
Have a look at the post processing calculators in particular, like [TfLiteTensorsToDetectionsCalculator](https://github.com/google/mediapipe/blob/7bad8fce626ab3b0f41d818afac4df1e757c0969/mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc)
That is where the object detection model output is processed (for that example)
