### ISSUE TITLE
OpenCV build issue

### ISSUE THREAD

**Issue by asimzahid1** [google/mediapipe#74]
![Built Error picture](https://user-images.githubusercontent.com/23510373/64074474-1b4a7980-ccc5-11e9-9ff6-606a4d42f1f0.jpeg)

I am trying to implement media pipe framework. When I run "bash setup_opencv.sh" it downloads all the files but when it starts building it chocks the whole system and does not respond anyhow.
My system specification is Ubuntu 18 LTS, 4GB RAM, Core i5 3rd generation, no GPU.
Could anyone please guide me?

**Comment by jiuqiant** [comment]
asimzahid1@, I recommend installing opencv by package manager on Ubuntu 18.04.

If you still want to build OpenCV from source, you probably want to limit the number of cores make can use. To do it, please modify the line 52 in the [setup_opencv.sh](https://github.com/google/mediapipe/blob/master/setup_opencv.sh) to be ```make -j$(nproc)```

**Comment by jiuqiant** [comment]
No updates for more than 7 days. Close this issue for now.
