### ISSUE TITLE
Could I get the length information of the chair by using the Object Detection 3D

### ISSUE THREAD

**Issue by skylineJLU** [google/mediapipe#741]
I am currently running the  Object Detection 3D, I have the idea that could we obtain the length information of the 3D bounding box? If it is possible, we can calculate the volume of the item. Is it easy to implement? Thank you！跪求指导！

**Comment by ahmadyan** [comment]
Yes,
The the predicted Annotation class contains the box vertices, then we compute the transformation  from those vertices in the annotations_to_model_matrices_calculator. When we fit a 3D bounding box to a set of vertices, we also compute the box scale as well.

https://github.com/google/mediapipe/blob/5d028d923b52fd95bd49642a9a4a162f57ae260e/mediapipe/graphs/object_detection_3d/calculators/annotations_to_model_matrices_calculator.cc#L193
