### ISSUE TITLE
Missing 2D hand_landmark.tflite file

### ISSUE THREAD

**Issue by jen-co** [google/mediapipe#744]
Hi,

I noticed that on your latest update for improved handtracking there is no longer the option to have 2D tracking. There used to be two tflite files - 2d and 3d. For my purposes 2d seems to be more stable than 3d so I wanted to know if there is an option to make this available?

Also, I saw on your twitter [announcement](https://twitter.com/GoogleAI/status/1265319835283537921) that you are using the 2d version so I assume this is an option?

Thanks!

**Comment by jiuqiant** [comment]
After https://github.com/google/mediapipe/commit/b133b0f2004c831c2be004291d3fcf7a378a48f4, the 2D hand landmark model is gone. We now only have the 3D hand landmark model.
