### ISSUE TITLE
Build error when cross compiling for Coral

### ISSUE THREAD

**Issue by gustavryd** [google/mediapipe#745]
I am following the guide on how to build the face_detection for Coral. I got stuck with this error:

root@eadc27290b85:/mediapipe# bazel build -c opt --crosstool_top=@crosstool//:toolchains --compiler=gcc --cpu=aarch64 --define MEDIAPIPE_DISABLE_GPU=1 --copt -DMEDIAPIPE_EDGE_TPU --copt=-flax-vector-conversions mediapipe/examples/coral:face_detection_tpu
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/d855adfc5a0195788bf5f92c3c7352e638aa1109.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //mediapipe/examples/coral:face_detection_tpu (2 packages loaded, 9 targets configured).
INFO: Found 1 target...
INFO: From Executing genrule @com_github_glog_glog//:run_configure:
/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/sandbox/processwrapper-sandbox/575/execroot/mediapipe/external/com_github_glog_glog/missing: Unknown `--is-lightweight' option
Try `/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/sandbox/processwrapper-sandbox/575/execroot/mediapipe/external/com_github_glog_glog/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for ANSI C header files... (cached) no
checking for stdint.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for unistd.h... (cached) yes
checking syscall.h usability... yes
checking syscall.h presence... yes
checking for syscall.h... yes
checking sys/syscall.h usability... yes
checking sys/syscall.h presence... yes
checking for sys/syscall.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking libunwind.h usability... no
checking libunwind.h presence... no
checking for libunwind.h... no
checking ucontext.h usability... yes
checking ucontext.h presence... yes
checking for ucontext.h... yes
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... yes
checking for sys/utsname.h... yes
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking glob.h usability... yes
checking glob.h presence... yes
checking for glob.h... yes
checking unwind.h usability... yes
checking unwind.h presence... yes
checking for unwind.h... yes
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking size of void *... 8
checking for uint16_t... yes
checking for u_int16_t... yes
checking for __uint16... no
checking for sigaltstack... yes
checking for sigaction... yes
checking for dladdr... no
checking for fcntl... yes
checking for pread... yes
checking for pwrite... yes
checking for __attribute__... yes
checking for __builtin_expect... yes
checking for __sync_val_compare_and_swap... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -pthread is sufficient with -shared... yes
checking for pthread_self in -lpthread... yes
checking for main in -lgflags... no
checking for gtest-config... no
checking for main in -lgtest... no
checking support for pthread_rwlock_* functions... yes
checking whether the compiler implements namespaces... yes
checking what namespace STL code is in... std
checking whether compiler supports using ::operator<<... 1
checking for ucontext.h... (cached) yes
checking sys/ucontext.h usability... yes
checking sys/ucontext.h presence... yes
checking for sys/ucontext.h... yes
checking how to access the program counter from a struct ucontext... uc_mcontext.gregs[REG_RIP]
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/glog/logging.h
config.status: creating src/glog/raw_logging.h
config.status: creating src/glog/vlog_is_on.h
config.status: creating src/glog/stl_logging.h
config.status: creating libglog.pc
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
'src/config.h' -> 'bazel-out/aarch64-opt/bin/external/com_github_glog_glog/config.h.tmp'
'src/glog/logging.h' -> 'bazel-out/aarch64-opt/bin/external/com_github_glog_glog/src/glog/logging.h.tmp'
'src/glog/raw_logging.h' -> 'bazel-out/aarch64-opt/bin/external/com_github_glog_glog/src/glog/raw_logging.h'
'src/glog/stl_logging.h' -> 'bazel-out/aarch64-opt/bin/external/com_github_glog_glog/src/glog/stl_logging.h'
'src/glog/vlog_is_on.h' -> 'bazel-out/aarch64-opt/bin/external/com_github_glog_glog/src/glog/vlog_is_on.h'
INFO: From Executing genrule @com_github_glog_glog//:config_h:
select bazel-out/aarch64-opt/bin/external/com_github_glog_glog/config.h.tmp to be the glog config file.
INFO: From Executing genrule @com_github_glog_glog//:logging_h:
select bazel-out/aarch64-opt/bin/external/com_github_glog_glog/src/glog/logging.h.tmp to be the glog logging.h file.
INFO: From Compiling external/org_tensorflow/tensorflow/lite/minimal_logging_default.cc:
external/org_tensorflow/tensorflow/lite/minimal_logging_default.cc:26:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 
external/org_tensorflow/tensorflow/lite/minimal_logging_default.cc:27:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wformat-nonliteral"
 
external/org_tensorflow/tensorflow/lite/minimal_logging_default.cc:29:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 
cc1plus: warning: unrecognized command line option '-Wno-extern-c-compat'
ERROR: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/com_github_glog_glog/BUILD.bazel:68:1: C++ compilation of rule '@com_github_glog_glog//:glog' failed (Exit 1) aarch64-linux-gnu-gcc failed: error executing command /usr/bin/aarch64-linux-gnu-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O3 -DNDEBUG '-D_FORTIFY_SOURCE=2' ... (remaining 46 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/com_github_glog_glog/src/symbolize.h:58:0,
                 from external/com_github_glog_glog/src/signalhandler.cc:36:
external/com_github_glog_glog/src/signalhandler.cc: In function 'void* google::{anonymous}::GetPC(void*)':
bazel-out/aarch64-opt/bin/external/com_github_glog_glog/config.h:156:38: error: 'struct mcontext_t' has no member named 'gregs'; did you mean 'regs'?
 #define PC_FROM_UCONTEXT uc_mcontext.gregs[REG_RIP]
                                      ^
external/com_github_glog_glog/src/signalhandler.cc:78:28: note: in expansion of macro 'PC_FROM_UCONTEXT'
     return (void*)context->PC_FROM_UCONTEXT;
                            ^~~~~~~~~~~~~~~~
bazel-out/aarch64-opt/bin/external/com_github_glog_glog/config.h:156:44: error: 'REG_RIP' was not declared in this scope
 #define PC_FROM_UCONTEXT uc_mcontext.gregs[REG_RIP]
                                            ^
external/com_github_glog_glog/src/signalhandler.cc:78:28: note: in expansion of macro 'PC_FROM_UCONTEXT'
     return (void*)context->PC_FROM_UCONTEXT;
                            ^~~~~~~~~~~~~~~~
Target //mediapipe/examples/coral:face_detection_tpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 220.439s, Critical Path: 216.54s
INFO: 532 processes: 1 local, 531 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

**Comment by mcclanahoochie** [comment]
Interesting, I thought this was fixed in the newest release of MediaPipe (more specifically, the newer GLog).
You can safely change 
`return (void*)context->PC_FROM_UCONTEXT;`
with 
`return NULL;`

**Comment by gustavryd** [comment]
Thanks. Seems to work. At least I get another build error.
