### ISSUE TITLE
Build error when Cross compiling for Coral, xnnpack_delegate.h: No such file or directory

### ISSUE THREAD

**Issue by gustavryd** [google/mediapipe#746]
I am following the guideline on building MediaPipe for Coral Dev Board. The guideline involves removing xnnpack dependencies. Not sure if this is the background, but I get an error when building the face detection.

root@eadc27290b85:/mediapipe# bazel build -c opt --crosstool_top=@crosstool//:toolchains --compiler=gcc --cpu=aarch64 --define MEDIAPIPE_DISABLE_GPU=1 --copt -DMEDIAPIPE_EDGE_TPU --copt=-flax-vector-conversions mediapipe/examples/coral:face_detection_tpu
INFO: Analyzed target //mediapipe/examples/coral:face_detection_tpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /mediapipe/mediapipe/calculators/tflite/BUILD:218:1: C++ compilation of rule '//mediapipe/calculators/tflite:tflite_inference_calculator' failed (Exit 1) aarch64-linux-gnu-gcc failed: error executing command /usr/bin/aarch64-linux-gnu-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O3 -DNDEBUG '-D_FORTIFY_SOURCE=2' ... (remaining 126 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/tflite/tflite_inference_calculator.cc:60:10: fatal error: tensorflow/lite/delegates/xnnpack/xnnpack_delegate.h: No such file or directory
 #include "tensorflow/lite/delegates/xnnpack/xnnpack_delegate.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/coral:face_detection_tpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.737s, Critical Path: 0.42s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by mcclanahoochie** [comment]
Hi, can you confirm you have the most recent version of MediaPipe?
This should have been [addressed](https://github.com/google/mediapipe/blob/v0.7.5/mediapipe/calculators/tflite/tflite_inference_calculator.cc#L61) in 0.7.5 (and HEAD) .
If you are not updated, and don't want to update, then any xnn references can be commented out (irrelevant on Coral anyway).

**Comment by gustavryd** [comment]
No, I am on a version from April. Thanks for the swift reply.

**Comment by prhfyw** [comment]
I changed the -march=armv8-a, then the following print, how can I solve this problem?
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S: Assembler messages:
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:64: Error: selected processor does not support `fmla v16.8h,v20.8h,v0.h[0]'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:65: Error: selected processor does not support `fmla v17.8h,v21.8h,v0.h[0]'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:66: Error: selected processor does not support `fmla v18.8h,v22.8h,v0.h[1]'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:67: Error: selected processor does not support `fmla v19.8h,v23.8h,v0.h[1]'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:74: Error: selected processor does not support `fadd v16.8h,v16.8h,v18.8h'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:75: Error: selected processor does not support `fadd v17.8h,v17.8h,v19.8h'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:80: Error: selected processor does not support `fmul v16.8h,v16.8h,v4.8h'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:81: Error: selected processor does not support `fmul v17.8h,v17.8h,v4.8h'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:82: Error: selected processor does not support `fmax v16.8h,v16.8h,v5.8h'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:83: Error: selected processor does not support `fmax v17.8h,v17.8h,v5.8h'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:84: Error: selected processor does not support `fmin v16.8h,v16.8h,v6.8h'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:85: Error: selected processor does not support `fmin v17.8h,v17.8h,v6.8h'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:104: Error: selected processor does not support `fmla v16.8h,v20.8h,v0.h[0]'
external/XNNPACK/src/f16-gemm/gen-inc/1x16inc-minmax-aarch64-neonfp16arith-ld32.S:105: Error: selected processor does not support `fmla v17.8h,v21.8h,v0.

**Comment by mcclanahoochie** [comment]
not sure where this would be coming from, 
but as mentioned above, anything related to xnnpack can be ignored/commented-out, as it is not used for coral.

are you running mediapipe 0.7.5 or newer?
