### ISSUE TITLE
calculate inference time of the example

### ISSUE THREAD

**Issue by JaydenGG** [google/mediapipe#75]
How to calculate the detect time in the examples(object detection, face detection)?

**Comment by dvansabben** [comment]
I'm also trying to measure the inference time without success at the moment.
From the docs I found that there is this class `GraphProfiler` which measures the processing time.

I added the following code to the Android samples (after initialization):
```

Graph mediapGraph = processor.getGraph();
// 'profiler' is a GraphProfiler member stored in the MainActivity class
profiler = mediapGraph.getProfiler();
profiler.reset();
profiler.resume();
```
Then, I let the sample run and after a while I call the line below to gather the measured intervals:
```
List<CalculatorProfile> profiles = getCalculatorProfiles();
```
Each `CalculatorProfile` has a valid name ( `.getName()`) but it has no measures (when calling to `.getProcessRuntime()` it always report 0 total time).

Does anyone has a better insight on the `GraphProfiler` class?

**Comment by JaydenGG** [comment]
@dvansabben How to understand "I let the sample run and after a while I call the line below to gather the measured intervals",  I cannot figure out where you write "List<CalculatorProfile> profiles = getCalculatorProfiles();" .
Sorry I am new to mediapipe.

**Comment by dvansabben** [comment]
I call the `getCalculatorProfiles()` inside an Android TouchListener on the whole Layout so then when I touch anywhere of the screen after few seconds I get the `GraphProfiler` report. (see [adding touch listener](https://stackoverflow.com/questions/3142670/how-do-i-detect-touch-input-on-the-android) )

**Comment by dvansabben** [comment]
While trying to get `GraphProfiler` working. I'm using this workaround, I'm calling 2x `.addPacketCallback()` to get the elapsed time between 2 streams on the graph.

Ex.
```
 processor.getGraph().addPacketCallback("palm_detections", new PacketCallback(){

      @Override
      public void process(Packet packet)
      {
          Log.d("MEDIAPIPE", "palm_detections timestamp="  +  System.currentTimeMillis() );
      }

  });
```
Then I add another one to the second Stream on the graph and subtract both timestamps. This is not accurate given the asynchronous nature of the library but is best I could get at the moment.

**Comment by JaydenGG** [comment]
Thank you for your kindly reply, I got your idea.
But can getProcessRuntime() function output the real operation time of every frame you get from camera?

**Comment by tatevmejunts** [comment]
Hello. 
Does anyone find out how to calculate exact inference time on single frame?

**Comment by teleger** [comment]
> 感谢您的友好答复，我知道您的想法。
> 但是getProcessRuntime（）函数可以输出您从摄像机获得的每一帧的实际操作时间吗？

The time difference between these data is almost zero, because it's fast, right?

**Comment by JaydenGG** [comment]
Actually, I find a stupid solution, but it works for me.

mediapipe graph处理每一张图片的时候，会打印log信息，对应Tag为FrameProcessor。
相关函数是文件FrameProcessor.java的onNewFrame函数.

测试的时候logcat信息，然后分析时间差即可。

设置logcat的tag打印属性
进入device shell环境之后，输入setprop tag_name V, 对V级别以上的信息都打印
getprop | grep tag_name查看自己是否设置成功

**Comment by mapleyuan** [comment]
same pro. Any solved method?

**Comment by yxchng** [comment]
@mgyong  Any updates on the usage of profiler?
