### ISSUE TITLE
ERROR: Unrecognized option: --experimental_repo_remote_exec with hello world

### ISSUE THREAD

**Issue by ahmed-shariff** [google/mediapipe#752]
When following the instructions in https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-debian-and-ubuntu I get the following error:

```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=210
INFO: Reading rc options for 'run' from /media/Files/Research/palm_interface/hand_pose_estimation/mediapipe/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
ERROR: Unrecognized option: --experimental_repo_remote_exec
```

**Comment by ahmed-shariff** [comment]
This was an issue with the bazel version. I had a conflict that I had to resolve to replace bazel 0.26 with bazel > 2.0

**Comment by RaySue** [comment]
Thx

**Comment by Luckylotus17** [comment]
> When following the instructions in https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-debian-and-ubuntu I get the following error:
> 
> ```
> INFO: Options provided by the client:
>   Inherited 'common' options: --isatty=1 --terminal_columns=210
> INFO: Reading rc options for 'run' from /media/Files/Research/palm_interface/hand_pose_estimation/mediapipe/.bazelrc:
>   Inherited 'common' options: --experimental_repo_remote_exec
> ERROR: Unrecognized option: --experimental_repo_remote_exec
> ```
