### ISSUE TITLE
how to build .dylib/.a for macos?

### ISSUE THREAD

**Issue by mapleyuan** [google/mediapipe#755]
I had use the apple_static_library generated mediapipe SDK. then I integrated it with cmake but I got some error that it could't find the calculators. I find other issue about these but can't solve my problem.

`No registered object with name: FlowLimiterCalculator; Unable to find Calculator "FlowLimiterCalculator"
No registered object with name: GpuBufferToImageFrameCalculator; Unable to find Calculator "GpuBufferToImageFrameCalculator"
No registered object with name: ImagePropertiesCalculator; Unable to find Calculator "ImagePropertiesCalculator"`

**Comment by mapleyuan** [comment]
apple_static_library(
    name = "libmediapipe",
    platform_type = "macos",
    minimum_os_version = "10.14",
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/graphs/face_detection:desktop_tflite_calculators",

    ],
)

**Comment by NikolayChirkov** [comment]
Everything seems to be included correctly and should work. Please try ios_framework instead of apple_static_library

**Comment by mapleyuan** [comment]
thx for your reply. I used dylib and the problem had been solved.

**Comment by JacobMuchow** [comment]
Hi @mapleyuan , I am working on the same thing right now. Would you be able to share your solution? Thank you!
