### ISSUE TITLE
bazel build fails

### ISSUE THREAD

**Issue by jkjan** [google/mediapipe#759]
![image](https://user-images.githubusercontent.com/22045424/83519253-9a9c0080-a516-11ea-9c1f-4757709351d1.png)

```terminal
D:\GitHubRepos\mediapipe>bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/multihandtrackinggpu
INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  C:/users/jkjan/_bazel_jkjan/3ie4g4lu/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/jkjan/_bazel_jkjan/3ie4g4lu/external/org_tensorflow/third_party/py/python_configure.bzl", line 209
                _check_python_bin(<2 more arguments>)
        File "C:/users/jkjan/_bazel_jkjan/3ie4g4lu/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, in _check_python_bin
                auto_config_fail(<1 more arguments>)
        File "C:/users/jkjan/_bazel_jkjan/3ie4g4lu/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, in auto_config_fail
                fail(<1 more arguments>)
Configuration Error: --define PYTHON_BIN_PATH='D:\Python\venv\Scripts\python.exe
D:\Python\Python37\python.exe
C:\Users\jkjan\AppData\Local\Microsoft\WindowsApps\python.exe' is not executable. Is it the python binary?
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/multihandtrackinggpu:multihandtrackinggpu' failed; build aborted: Traceback (most recent call last):
        File "C:/users/jkjan/_bazel_jkjan/3ie4g4lu/external/org_tensorflow/third_party/py/python_configure.bzl", line 209
                _check_python_bin(<2 more arguments>)
        File "C:/users/jkjan/_bazel_jkjan/3ie4g4lu/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, in _check_python_bin
                auto_config_fail(<1 more arguments>)
        File "C:/users/jkjan/_bazel_jkjan/3ie4g4lu/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, in auto_config_fail
                fail(<1 more arguments>)
Configuration Error: --define PYTHON_BIN_PATH='D:\Python\venv\Scripts\python.exe
D:\Python\Python37\python.exe
C:\Users\jkjan\AppData\Local\Microsoft\WindowsApps\python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 0.393s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
```

I am currently using Windows 10,
the bazel version is 3.2.0

I've followed this [link](https://github.com/google/mediapipe/blob/master/mediapipe/docs/multi_hand_tracking_mobile_gpu.md)

This is what I see when I type 
`bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/multihandtrackinggpu
`

My python version is 3.7.6

And the python binary file that bazel is looking for,
C:\Users\jkjan\AppData\...python.exe is just a stub.
That doesn't even exist in system path. I double checked it.
I don't know why bazel is trying to use that file.

I tried [this](https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md) and gives me same error.

I just want to install this app and show how it works by loggin.
Thank you.

**Comment by jiuqiant** [comment]
As we mentioned in the [installation instruction](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows), building MediaPipe Android apps is still not possible on native Windows. Please do this in WSL instead. 
For the python issue, the installation instruction also mentions that the flag`--action_env PYTHON_BIN_PATH="C:/path/to/python.exe"` is needed.

**Comment by jkjan** [comment]
> As we mentioned in the [installation instruction](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows), building MediaPipe Android apps is still not possible on native Windows. Please do this in WSL instead.
> For the python issue, the installation instruction also mentions that the flag`--action_env PYTHON_BIN_PATH="C:/path/to/python.exe"` is needed.

actually, I tried that on ubuntu 20.04 and it produces the same error.

**Comment by im-sj** [comment]
I am also getting the same error on ubuntu 20.04

**Comment by huhai463127310** [comment]
use parameter *--action_env PYTHON_BIN_PATH="C://python_36//python.exe"*. And pay attention to the action_env  parameter position.
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://python_36//python.exe" mediapipe/examples/desktop/hello_world`
see https://google.github.io/mediapipe/getting_started/install#installing-on-windows

**Comment by holove93** [comment]
Because It is just PATH,  you can remove "python.exe"
So.. correct script is  bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://python_36//" mediapipe/examples/desktop/hello_world
