### ISSUE TITLE
desktop hand_tracking_gpu with CUDA fails to build on gcc 6 or higher

### ISSUE THREAD

**Issue by mmhobi** [google/mediapipe#760]
> bazel build -c opt --config=cuda --spawn_strategy=local --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu --verbose_failures

On gcc 6, 7, and 8, the build fails with "stdlib.h: No such file or directory", which I believe is due to [https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129).
In `tensorflow`, `local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc`, and `embedded_tools/tools/cpp/unix_cc_toolchain_config.bzl` -isystem is used (instead of -I (I guess?))

This does not ring up on a non-cuda build.

**Comment by jiuqiant** [comment]
MediaPipe's hand tracking gpu demo is a TFLite example and it depends on OpenGL. It does nothing with CUDA. The only TensorFlow example MediaPipe has is [the object detection tensorflow demo](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/object_detection/BUILD#L19).
