### ISSUE TITLE
this rule is missing dependency declarations for the following files

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#761]
`WARNING: /Users/user/Ctsmed/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:1: in srcs attribute of android_library rule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:hed_edge_aar_android_lib: please do not import '//mediapipe/java/com/google/mediapipe/glutil:TextureRenderer.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'mediapipe_aar', the error might have been caused by the macro implementation
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:hed_edge_aar (1 packages loaded, 20 targets configured).
INFO: Found 1 target...
ERROR: /Users/user/Ctsmed/mediapipe/mediapipe/calculators/custom/BUILD:1:1: undeclared inclusion(s) in rule '//mediapipe/calculators/custom:hed_edge_detection_calculator':
this rule is missing dependency declarations for the following files included by 'mediapipe/calculators/custom/hed_edge_detection_calculator.cc':
  'external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_buffer.h'
  'external/org_tensorflow/tensorflow/lite/delegates/gpu/common/status.h'
  'external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_call.h'
  'external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_errors.h'
  'external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/portable_gl31.h'
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:hed_edge_aar failed to build
INFO: Elapsed time: 19.976s, Critical Path: 17.55s
INFO: 0 processes.
FAILED: Build did NOT complete successfully`

Following is my build file, what does the @org_tensorflow//tensorflow/lite:framework depend on?
cc_library(
    name = "hed_edge_detection_calculator",
    srcs = ["hed_edge_detection_calculator.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "@org_tensorflow//tensorflow/lite:framework",
    ],
    alwayslink = 1
)

**Comment by eknight7** [comment]
Could try looking at dependencies in https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/BUILD to figure out what you need for the calculator? 

Feel free to share more details about your `hed_edge_detection_calculator` implementation if that doesn't help.

**Comment by weinixuehao** [comment]
@eknight7 
Sorry! I am a newbie for bazel. what does mean for `this rule is missing dependency declarations for the following files included by ...?`

hed_edge_detection_calculator.cc file
`#include "mediapipe/framework/calculator_framework.h"
#include "mediapipe/gpu/gpu_buffer.h"
#include "tensorflow/lite/delegates/gpu/gl/gl_buffer.h"

typedef ::tflite::gpu::gl::GlBuffer GpuTensor;
namespace mediapipe
{
    class HedEdgeDetectionCalculator : public CalculatorBase
    {
        public:
            static ::mediapipe::Status GetContract(CalculatorContract *cc);

            ::mediapipe::Status Open(CalculatorContext *cc) override;
            ::mediapipe::Status Process(CalculatorContext *cc) override;
            ::mediapipe::Status Close(CalculatorContext *cc) override;
    };

    ::mediapipe::Status HedEdgeDetectionCalculator::GetContract(CalculatorContract *cc)
    {
        bool hasTag = cc->Inputs().HasTag("TENSORS_GPU");
        cc->Inputs().Tag("TENSORS_GPU").Set<std::vector<GpuTensor>>();
        cc->Outputs().Tag("IMAGE_GPU").Set<GpuTensor>();
        return ::mediapipe::OkStatus();
    }

    ::mediapipe::Status HedEdgeDetectionCalculator::Open(CalculatorContext *cc)
    {
        return ::mediapipe::OkStatus();
    }
    ::mediapipe::Status HedEdgeDetectionCalculator::Process(CalculatorContext *cc)
    {
        return ::mediapipe::OkStatus();
    }
    ::mediapipe::Status HedEdgeDetectionCalculator::Close(CalculatorContext *cc)
    {
        return ::mediapipe::OkStatus();
    }
    REGISTER_CALCULATOR(HedEdgeDetectionCalculator);
} // namespace mediapipe`

**Comment by sgowroji** [comment]
Hi @weinixuehao, Could you please check the above  with latest [release](https://github.com/google/mediapipe/tree/v0.8.6) of MediaPipe. And write us back if you still face the same issue. Thanks!
