### ISSUE TITLE
Any approaches on Static signs recognition?

### ISSUE THREAD

**Issue by OrangeSmoothie** [google/mediapipe#765]
I tried checking if fingers are bent and calculate the distance between landmarks. Is there any other technics or calculations for better recognition?

**Comment by mgyong** [comment]
@OrangeSmoothie You should look at the repos related to gesture recognition https://github.com/mgyong/awesome-mediapipe/#sign-language-hand-gesture-related

**Comment by fanzhanggoogle** [comment]
If you have your specific dataset for the signs in hand, you can also train a light weight model to predict the gestures from the landmarks.
