### ISSUE TITLE
No Java source files in the example projects

### ISSUE THREAD

**Issue by rose-jinyang** [google/mediapipe#766]
Hello
How are you?
Happy to use Mediapipe.
I have a question.
I can NOT find the java source files in the java example projects from version 0.7.5

![image](https://user-images.githubusercontent.com/47862419/83770845-25fec880-a6b4-11ea-8d86-138616438907.png)

![image](https://user-images.githubusercontent.com/47862419/83770899-37e06b80-a6b4-11ea-8f11-f03981e58a86.png)

How can I understand this?
Thanks

**Comment by jiuqiant** [comment]
To reduce the code size, we provide a template app at https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic and make all the example apps from that template app.

**Comment by rose-jinyang** [comment]
Thanks for your quick reply
