### ISSUE TITLE
Landscape orientation on Android App.

### ISSUE THREAD

**Issue by z3st0** [google/mediapipe#767]
I downloaded some Mediapipe examples and I love it. Unfortunately I notice that it only supports portrait mode currently. I want to implement the Multi-hand Tracking in an app, where it's required to be in landscape mode. I already tried to fix it on my own and failed. I also looked into the other issue, but it didn't help me much.
Can someone please help me find a fix in more detail? Thank you very much.

[Landscape orientation on Android App. #568](https://github.com/google/mediapipe/issues/568)

![Screenshot_20200604_202534](https://user-images.githubusercontent.com/32819641/83796914-14142a00-a6a2-11ea-9c58-5534d98744f3.jpg)

**Comment by ttcluo** [comment]
我也遇到了一样的问题，不知道如何解决
