### ISSUE TITLE
youtube8m feature extractor too slow to use

### ISSUE THREAD

**Issue by john159151** [google/mediapipe#768]
I try to use youtube8m feature extractor to extract audio feature of video. But it is too slow (about 10s/video) because it is only use CPU. 
Is there any way to speed up (such as using GPU)?

**Comment by jiuqiant** [comment]
There is a way to run TensorFlow GPU with MediaPipe: https://github.com/google/mediapipe/blob/master/mediapipe/docs/gpu.md#tensorflow-cuda-support-and-setup-on-linux-desktop

**Comment by john159151** [comment]
> There is a way to run TensorFlow GPU with MediaPipe: https://github.com/google/mediapipe/blob/master/mediapipe/docs/gpu.md#tensorflow-cuda-support-and-setup-on-linux-desktop

It is not working because I can't run "bazel build" with cuda.
It show the error message as follow:
ERROR:  Analysis of target '//mediapipe/examples/desktop/object_detection:object_detection_tensorflow' failed; build aborted: no such package '@local_config_cuda//cuda': Traceback (most recent call last)

**Comment by john159151** [comment]
Still not working and I give up, thanks

**Comment by zzzzzigzag** [comment]
> There is a way to run TensorFlow GPU with MediaPipe: https://github.com/google/mediapipe/blob/master/mediapipe/docs/gpu.md#tensorflow-cuda-support-and-setup-on-linux-desktop

The link is now 404, could you update it please, thank you
