### ISSUE TITLE
Understanding palm_detections output stream

### ISSUE THREAD

**Issue by jen-co** [google/mediapipe#769]
Hello,

I am using the handtrackinggpu in Android. It works well but every so often the hand_presence stream has some false positives (i.e. it detects a hand when there is no hand in view). 

I wanted to output the confidence score attached to this decision to see if the false positives correlate with a low confidence score. The only way I could find to do this is to subscribe to the palm_detections output stream, which I have managed to do successfully using the following code:

`processor.addPacketCallback(OUTPUT_HAND_PRESENCE_SCORE,
                (packet) -> {
                    List<DetectionProto.Detection> detections = PacketGetter.getProtoVector(packet, DetectionProto.Detection.parser());
                    Log.d(TAG, "detections: " + detections.size());
                    for (DetectionProto.Detection detection : detections)
                    {
                        int scores = detection.getScoreCount();
                        Log.d(TAG, "detections scores: " + scores);
                        for (int i =0; i < scores; i++)
                        {
                            Log.d(TAG, "detections score: " + detection.getScore(i));
                        }
                    }
        });`

However, I do not understand exactly what information it is returning, specifically for the following reasons:

1. I only receive packets from this stream when hand_presence is false - why is this the case?
2. The number of detections in the Detection List varies from 0 to 2 randomly - what is each detection object linked to?

I fear I am missing something fundamental in my understanding of the pipeline here so apologies if this is way off, but essentially I just want to know if I can cull false positives on the hand presence detection.

Thanks in advance!
Jennifer

**Comment by eknight7** [comment]
Hi @jen-co , does https://github.com/google/mediapipe/issues/734#issuecomment-639139127 help?

**Comment by jen-co** [comment]
Wow thank you for such a quick response. Yes that comment explains a lot! 

I did actually try to see if I could change the hand_landmark_gpu.pbtxt subgraph to see if I could add the additional outputstream of hand_presence_score. I did the following:

At the top of the pbtxt file where the other outputstreams are defined:

input_stream: "IMAGE:input_video"
input_stream: "NORM_RECT:hand_rect"
output_stream: "LANDMARKS:hand_landmarks"
output_stream: "NORM_RECT:hand_rect_for_next_frame"
output_stream: "PRESENCE:hand_presence"

I added:
**output_stream: "FLOAT:hand_presence_score"**

and I also updated the hand_tracking_mobile.pbtxt so that the node definition included the additional stream (shown in bold below):

node {
  calculator: "HandLandmarkSubgraph"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "NORM_RECT:hand_rect"
  output_stream: "LANDMARKS:hand_landmarks"
  output_stream: "NORM_RECT:hand_rect_from_landmarks"
  output_stream: "PRESENCE:hand_presence"
**output_stream: "FLOAT:hand_presence_score"**
}

I then rebuilt the binary graph file using this command:
`bazel build -c opt mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:binary_graph
`
However, when I ran the app I got a runtime error:
" Tag "FLOAT" does not exist in the subgraph config."

Should I have also rebuilt the AAR from scratch after updating the graph files or am I incorrectly tagging the output stream in the graph files as FLOAT?

Thanks again!
Jennifer

**Comment by jen-co** [comment]
Hah! I actually just answered my own question - I rebuilt the AAR and now it works! Thanks again for the info. Problem solved :)
