### ISSUE TITLE
apk size too big

### ISSUE THREAD

**Issue by aminm2a** [google/mediapipe#77]
Hi,
The mediapipe jni library (libmediapipe_jni.so) for handtracking  is too big for a mobile app (245M). Why is it so big ? tflite library does not exceed 5M and opencv around 18M

**Comment by chuoling** [comment]
We haven't paid enough attention optimizing the APK size. With the current build setup, libmediapipe_jni contains symbol information that can be helpful for debugging.

If your goal is to reduce the APK size, a quick solution is to add a linker option (--linkopt="-s") in the build command to omit all symbol information, i.e.,

bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu --linkopt="-s"

This generates an APK that's about half of the original size (31MB v.s. 76MB), and libmediapipe_jni.so is reduced to ~10MB (from 245MB as you reported).

**Comment by aminm2a** [comment]
great :) 
How can we get mediapipe as aar android library to get it integrate in another app that do not use androidX ? for instance this compiles the example as an apk

**Comment by aminm2a** [comment]
@chuoling great!
How can we build the mediapipe aar ? to use it in another app

**Comment by chuoling** [comment]
> How can we build the mediapipe aar ? to use it in another app

Merging the discussion on "How can we build the mediapipe aar" into #88. Closing this issue.

**Comment by mgyong** [comment]
@aminm2a  Pls note in [MediaPipe v0.6.3](https://github.com/google/mediapipe/releases/tag/v0.6.3) we released support for [building AAR](https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md)

**Comment by Gauraviiitian** [comment]
I tried to open the link that @mgyong mentioned, but the page is not available (anymore maybe).

**Comment by chuoling** [comment]
Doc on Mediapipe AAR is at https://google.github.io/mediapipe/getting_started/android_archive_library.html
