### ISSUE TITLE
How to render a 3d object on tracked 3d object with occlusion?

### ISSUE THREAD

**Issue by rakoo04** [google/mediapipe#770]
I'm trying to use the mediapipe-objectron to make a shoe try-on app. I'm able to run the sample code but how do I move forward? How can I use the extracted coordinates for further use? Can it be done via custom calculator or can I use sceneform/scenekit ?

**Comment by ahmadyan** [comment]
You can either export the [object's pose ](https://github.com/google/mediapipe/blob/67bd8a2bf04072b853142e7739466dea218ae007/mediapipe/graphs/object_detection_3d/shoe_classic_occlusion_tracking.pbtxt#L74) as graph output and render your assets in sceneform/scenekit. Just make sure the [coordinate transformation](https://github.com/google/mediapipe/blob/67bd8a2bf04072b853142e7739466dea218ae007/mediapipe/graphs/object_detection_3d/shoe_classic_occlusion_tracking.pbtxt#L95) is correct.

Alternatively you can write a calculator that would do the rendering for you. We used GlAnimationOverlayCalculator. 

For example, in our graph if you remove the occlusion mask and replace the bounding box asset with your shoe asset, you can turn it into a shoe try-on app.

[In the shoe graph](https://github.com/google/mediapipe/blob/67bd8a2bf04072b853142e7739466dea218ae007/mediapipe/graphs/object_detection_3d/shoe_classic_occlusion_tracking.pbtxt#L122)

  input_side_packet: "TEXTURE:obj_texture"
  input_side_packet: "ANIMATION_ASSET:obj_asset_name"
