### ISSUE TITLE
AAR build from latest meidapipe can't be used fo android studio project

### ISSUE THREAD

**Issue by cosimo17** [google/mediapipe#771]
Thanks for your nice work.
I hava cloned this project and run it in my phone successfully:
[https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example)

However, the app crashed if I build the aar from source code and replace the original one.
I don't know how to fix this. I guess maybe because the updating of mediapipe.
BTW, I build the aar following this document:
https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example
Hoping for help

**Comment by jiuqiant** [comment]
MediaPipe hand graph along with the calculator source code and model files are updated in the mediapipe repo. If you build the aar from source code, you need to regenerate the binary graph and copy the new model files as well.

**Comment by cosimo17** [comment]
Thanks for your reply.
Now, I am going to rebuild the binary graph. But I meet another issue.
[https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md](https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md)
In this insturctions , build command for binary graph is:
`bazel build -c opt mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu:binary_graph`
I find there is no pre-defined binary_graph in BUILD file located in  **android\src\java\com\google\mediapipe\apps\multihandtrackinggpu.**
But there is mediapipe_binary_graph in BUILD file located in  **mediapipe\graphs\hand_tracking**
Is this the binary graph for multihandtracking app?

**Comment by jiuqiant** [comment]
Seems like the instruction needs to be fixed...

You can get hand_tracking_mobile_gpu.binarypb by running
```
$ bazel build mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu_binary_graph
INFO: Analyzed target //mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu_binary_graph (4 packages loaded, 184 targets configured).
INFO: Found 1 target...
Target //mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu_binary_graph up-to-date:
  bazel-bin/mediapipe/graphs/hand_tracking/hand_tracking_mobile_gpu.binarypb
INFO: Elapsed time: 5.855s, Critical Path: 0.10s
INFO: 1 process: 1 darwin-sandbox.
INFO: Build completed successfully, 2 total actions
```

BTW, the String variable BINARY_GRAPH_NAME in the MainActivity.java should match the binarypb name. For example,
```
private static final String BINARY_GRAPH_NAME = "hand_tracking_mobile_gpu.binarypb";
```

**Comment by cosimo17** [comment]
understoon. I think it will be helpful if the instruction is fixed.

**Comment by jiuqiant** [comment]
Both [the instructions](https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md) and [the example repo](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example) are updated.

**Comment by DandyLorenz** [comment]
> AAR和图形之间的不匹配将使应用程序崩溃。详细说

Can you help me see how to solve this problem?Thanks. https://github.com/google/mediapipe/issues/1450

**Comment by DandyLorenz** [comment]
Can you help me see how to solve this problem?Thanks. https://github.com/google/mediapipe/issues/1450
