### ISSUE TITLE
An issue on building an android project with a quantized model for object detection

### ISSUE THREAD

**Issue by rose-jinyang** [google/mediapipe#772]
Hello
How are you?
I have a quantized ssd mobilenetv2 model for object detection.
I tried to build an android project with this model in mediapipe.

I added as the following in _.pbtxt_ file in the _graphs_ folder.

![image](https://user-images.githubusercontent.com/47862419/83944334-6043a380-a835-11ea-88cb-2e3e13010af5.png)

While building, I met the following issue.
 
![image](https://user-images.githubusercontent.com/47862419/83942691-8e6eb680-a828-11ea-9bbc-a9613a2dfe34.png)

Please let me know how to fix this issue.
Regards,
Thank you.

**Comment by jiuqiant** [comment]
Hi, `use_quantized_tensors` is not defined in the node proto. It's defined in tflite_converter_calculator.proto:https://github.com/google/mediapipe/blob/5d028d923b52fd95bd49642a9a4a162f57ae260e/mediapipe/calculators/tflite/tflite_converter_calculator.proto#L58


I guess you need to write something like:
```
node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE:transformed_input_video"
  output_stream: "TENSORS:image_tensor"
  options: {
    [mediapipe.TfLiteConverterCalculatorOptions.ext] {
      use_quantized_tensors: true
    }
  }
}
```

**Comment by rose-jinyang** [comment]
Thanks for your quick reply.
one more question.
Is this option possible for mobile GPU too?

**Comment by jiuqiant** [comment]
TFLite GPU has ops for quantized models. So, this option should work on mobile as well. However, as you said, it might not gain too much performance.
