### ISSUE TITLE
How to read app resources from cpp code?

### ISSUE THREAD

**Issue by Nerdyvedi** [google/mediapipe#773]
I want to use Look Up tables for recoloring Hair in the Hair segmentation project. The LUTs are present in the app resources. 
My question is, How do I read those files from the recoloring cpp code in the calculations folder?

**Comment by jiuqiant** [comment]
You can use AssetManager. Here is an example: https://github.com/google/mediapipe/blob/3b6d3c40589968c8333b4a936fbad7a8bea6d7f6/mediapipe/graphs/object_detection_3d/calculators/gl_animation_overlay_calculator.cc#L272

**Comment by eknight7** [comment]
You could pass the filenames of the LUTs as side packets to a calculator and read the files inside the C++calculator.

**Comment by Nerdyvedi** [comment]
Thank you for helping.
@eknight7 , Could you direct me to an example? It would mean a lot

**Comment by eknight7** [comment]
Hi @Nerdyvedi , sorry for the delayed response.
The iristrackinggpu Android solution has an example of how to pass information as a side packet: https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/iristrackinggpu/MainActivity.java.

Closing this issue for now. Please feel free to re-open if it is still relevant.
