### ISSUE TITLE
Unable to run example on videos

### ISSUE THREAD

**Issue by Dylan5100** [google/mediapipe#778]
Everything was running smoothly, from the hello world example, to desktop Multi-Hand Tracking Demo (both CPU and GPU). However, when I attempt to run the desktop CPU Multi-Hand Tracking Demo with video using this command:
```GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_cpu     --calculator_graph_config_file=mediapipe/graphs/hand_tracking/multi_hand_tracking_desktop_live.pbtxt --input_video_path=~/Desktop/Apple1.mov```

It shows this error instead:
```
I20200608 21:41:01.472425  4059 demo_run_graph_main.cc:53] Initialize the calculator graph.
I20200608 21:41:01.475198  4059 demo_run_graph_main.cc:57] Initialize the camera or load the video.
E20200608 21:41:01.558281  4059 demo_run_graph_main.cc:146] Failed to run the graph: ; capture.isOpened()(mediapipe/examples/desktop/demo_run_graph_main.cc:65) 
```
What am I missing here? Thanks :)

**Comment by jiuqiant** [comment]
Seems like `capture.isOpened()` returns false. 
Maybe try the absolute path instead of using `~/Desktop`? If it still doesn't work, it means that OpenCV VideoCapture can't decode the video file Apple1.mov.

**Comment by Dylan5100** [comment]
It totally worked. Thanks again for your prompt response, @jiuqiant ! :)
