### ISSUE TITLE
MediaPipe slack channel

### ISSUE THREAD

**Issue by natario1** [google/mediapipe#779]
Just a question. mediapipe.dev mentions a community slack channel. Is it open to everyone? How can we join? Slack asks to contact the workspace administrator for an invitation.

**Comment by mgyong** [comment]
Slack channel is a community driven effort to provide a forum for MediaPipe users to interact and help each other. Invite is here https://mediapipe.page.link/joinslack

**Comment by peternaf** [comment]
Hi @mgyong @natario1 
It seems that the slack group is only available for users with *@googel.com email?
How is it possible to join it if I do not have a google mail box?
Thanks!

**Comment by doongsilee** [comment]
same here. should I apply for a job on google?

**Comment by adrianloy** [comment]
Seems impossible to join indeed.

**Comment by jackbach** [comment]
Same problem here.

**Comment by EitanHemed** [comment]
Same here.

**Comment by EitanHemed** [comment]
For anyone interested, here's the [invite link](https://join.slack.com/t/mediapipe/shared_invite/zt-1jqmrzg34-waJBaqdLt7_228BUOgxPwg) which works for non-@google email accounts.
