### ISSUE TITLE
Documents broken

### ISSUE THREAD

**Issue by jinuhwang** [google/mediapipe#780]
The documentation page seems broken after the b09cc090d464 commit.

**Comment by chuoling** [comment]
We are migrating our documentation to a new site. Please use docs.mediapipe.dev to access the new site.

**Comment by mgyong** [comment]
@jinuhwang I assume you are talking abt the readthedocs version of our documentation? We are deprecating that and going with the new site  https://docs.mediapipe.dev

**Comment by jinuhwang** [comment]
Thanks for the quick reply!
