### ISSUE TITLE
Fail to extract features on youtube 8M extraction

### ISSUE THREAD

**Issue by Derek-Kun** [google/mediapipe#786]
I installed the youtube8M feature extractor on CentOS7 system. when Iuse the command 
"bazel build -c opt --linkopt=-s \
  --define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true \
  mediapipe/examples/desktop/youtube8m:extract_yt8m_features" 

Some errors information appeared like below:

INFO: Repository eigen_archive instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule tf_http_archive defined at:
  /home/rd/.cache/bazel/_bazel_rd/7174b4479e18b62513c67bab8183f8f7/external/org_tensorflow/third_party/repo.bzl:134:34: in <toplevel>
ERROR: /home/rd/.cache/bazel/_bazel_rd/7174b4479e18b62513c67bab8183f8f7/external/linux_opencv/BUILD.bazel:16:16: Traceback (most recent call last):
	File "/home/rd/.cache/bazel/_bazel_rd/7174b4479e18b62513c67bab8183f8f7/external/linux_opencv/BUILD.bazel", line 14
		cc_library(name = "opencv", <5 more arguments>)
	File "/home/rd/.cache/bazel/_bazel_rd/7174b4479e18b62513c67bab8183f8f7/external/linux_opencv/BUILD.bazel", line 16, in cc_library
		glob(<1 more arguments>)
pattern cannot be absolute
ERROR: /home/dukun/featurextractor/mediapipe/third_party/BUILD:56:11: no such target '@linux_opencv//:opencv': target 'opencv' not declared in package ''; however, a source directory of this name exists.  (Perhaps add 'exports_files(["opencv"])' to /BUILD, or define a filegroup?) defined by /home/rd/.cache/bazel/_bazel_rd/7174b4479e18b62513c67bab8183f8f7/external/linux_opencv/BUILD.bazel and referenced by '//third_party:opencv'
ERROR: Analysis of target '//mediapipe/examples/desktop/youtube8m:extract_yt8m_features' failed; build aborted: Analysis failed
INFO: Elapsed time: 13.034s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 210 targets configured)

It seems like some kind of OpenCV problem, but I'm sure I totally followed the instruction on "https://google.github.io/mediapipe/getting_started/install#installing-on-centos" to install MediaPipe and successfully ran the Hello World desktop example. 

So where is the problem ?

**Comment by sgowroji** [comment]
Hi @Derek-Kun, Could you please respond the issue still exists with the latest build. Thanks!
