### ISSUE TITLE
opencv strange issue

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#789]
`  static {
    // Load all native libraries needed by the app.
       System.loadLibrary("mediapipe_jni");
    // System.loadLibrary("opencv_java3");
  }`

            auto size = input_tensors.size();
            auto &hed_tensor = input_tensors[0];
            const char *name = typeid(hed_tensor).name();
            size_t float_num = hed_tensor.bytes_size() / 4;
            std::vector<float> hed_buf(float_num);
            hed_tensor.Read(absl::MakeSpan(hed_buf));
            // for(std::vector<float>::iterator it = hed_buf.begin(); it != hed_buf.end(); ++it) {
            //     __android_log_print(ANDROID_LOG_WARN, "jni", "float_num=%zu, float=%f", float_num, *it);
            // }
            cv::Mat edge_image(256, 256, CV_32FC1, hed_buf.data());
            cv::Mat gray_image;
            edge_image.convertTo(gray_image, CV_8UC1, 255.0);
            std::time_t t = std::time(0);
            // bool result = cv::imwrite("/storage/emulated/0/"+std::to_string(t)+".jpg", gray_image);
            // bool result = cv::imwrite("/storage/emulated/0/asdf.jpg", gray_image);
            // __android_log_print(ANDROID_LOG_WARN, "jni", "result=%s", result ? "true" : "false");
            return ::mediapipe::OkStatus();      
Above code still run ok! Does not seem to have any effect without loading opencv_java3 so. but uncommenting cv::imwrite cause an crash error. i confuse why using cv::Mat gray_image decaring without any error.

**Comment by weinixuehao** [comment]
![image](https://user-images.githubusercontent.com/17869361/84384597-ca3abf00-ac20-11ea-8cd2-94998057d1bd.png)
![image](https://user-images.githubusercontent.com/17869361/84384643-db83cb80-ac20-11ea-88e3-bf5150958b7f.png)
![image](https://user-images.githubusercontent.com/17869361/84384677-e5a5ca00-ac20-11ea-8d82-22538dc3bbb8.png)
It seems do not need to load opencv_java3 lib still be able to init a Mat object.

**Comment by weinixuehao** [comment]
android_library(
    name = "mediapipe_lib",
    srcs = glob(["*.java"]),
    assets = [
        ":binary_graph",
        "//mediapipe/models:hed_graph.tflite",
    ],
    assets_dir = "",
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
    deps = [
        ":mediapipe_jni_lib",
        "//mediapipe/java/com/google/mediapipe/components:android_camerax_helper",
        "//mediapipe/java/com/google/mediapipe/components:android_components",
        "//mediapipe/java/com/google/mediapipe/framework:android_framework",
        "//mediapipe/java/com/google/mediapipe/glutil",
        "//third_party:androidx_appcompat",
        "//third_party:androidx_constraint_layout",
        "//third_party:opencv",
        "@maven//:androidx_concurrent_concurrent_futures",
        "@maven//:com_google_guava_guava",
    ],
)

I finally located the reason why not loading opencv_java3 still can defined `Mat object` as has referenced it in android_library as above, so loading mediapipe_jni lib will automatically load opencv_java3.  Do i understand correctly? If the understanding is correct, it can be concluded that this opencv_java3 file does not contain `imwrite` implementation? and how to fix? recompile by myself instead of using the opencv prebuilt lib?

**Comment by jiuqiant** [comment]
You can play around the opencv cmake flags and build the opencv android sdk by yourself. In order to use your local opencv android sdk, you need to use a `new_local_repository` rule to replace [the android_opencv http_archive rule](https://github.com/google/mediapipe/blob/master/WORKSPACE#L174).

**Comment by weinixuehao** [comment]
I don't want to do this too much unless I can solve the problem that imwrite unable to locate I encountered .

**Comment by jiuqiant** [comment]
You can do following to switch the dependency to OpenCV 4:
```
# Switch to OpenCV 4
sed -i -e 's:3.4.3/opencv-3.4.3:4.0.1/opencv-4.0.1:g' WORKSPACE
sed -i -e 's:libopencv_java3:libopencv_java4:g' third_party/opencv_android.BUILD
```

We currently have no plan to use OpenCV 4 on Android since we would like to keep the same version of OpenCV across platforms.
