### ISSUE TITLE
How to retrieve position of handlandmarks in Android example

### ISSUE THREAD

**Issue by Graphicscore** [google/mediapipe#79]
Hi,
In the Android Example the landmarks are rendered onto the camera output, how can I access / retrieve the information of those landmarks? I can't seem to find any example of how to actually get the data information from the detected result. I would like to get information about how big is the bounding box of the hand, and position of the landmarks etc.

A hint in the right direction is highly appreciated. Haven't worked with TF before.
Thanks in advance.

**Comment by GGamer217** [comment]
Is there an update on this? I would also like to be able to retrieve the information of the landmarks.

**Comment by Hemanth715** [comment]
Waiting for an update on this. The locations of the different parts of the hand as well as the bounding box are very useful. Please help.

**Comment by fanzhanggoogle** [comment]
Duplicate of #64

**Comment by mgyong** [comment]
@Hemanth715 @GGamer217 @Graphicscore Fixed in [v0.6.6](https://github.com/google/mediapipe/releases/tag/v0.6.6) Pls check it out and let us know
