### ISSUE TITLE
draw handedness label for multihand

### ISSUE THREAD

**Issue by cosimo17** [google/mediapipe#792]
I want to modify the graph of multihandtracking to draw handedness label(**Left or Right**) in screen, like the singlehandtracking do.
I have do following modification:  
**1. /mediapipe/calculator/core/begin_loop_calculator.cc (register BeginLoopClassificationListCalculator)**
`#include "mediapipe/framework/formats/classification.pb.h"  
typedef BeginLoopCalculator<std::vector<::mediapipe::ClassificationList>>  
	BeginLoopClassificationListCalculator;  
REGISTER_CALCULATOR(BeginLoopClassificationListCalculator);`   
 
**2. /mediapipe/calculator/core/BUILD  (add some denpendence)**
`cc_library(
    name = "begin_loop_calculator",
    srcs = ["begin_loop_calculator.cc"],
    hdrs = ["begin_loop_calculator.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//mediapipe/framework:calculator_context",
        "//mediapipe/framework:calculator_contract",
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework:collection_item_id",
        "//mediapipe/framework:packet",
        "//mediapipe/framework/formats:detection_cc_proto",
        "//mediapipe/framework/formats:landmark_cc_proto",
        "//mediapipe/framework/formats:matrix",
        "//mediapipe/framework/formats:rect_cc_proto",
        "//mediapipe/framework/port:integral_types",
        "//mediapipe/framework/port:ret_check",
        "//mediapipe/framework/port:status",
        **"//mediapipe/framework/formats:classification_cc_proto",**
        "@com_google_absl//absl/memory",
    ],
    alwayslink = 1,
)`  

**3. mediapipe/graphs/hand_tracking/subgraphs/multi_hand_landmark.pbtxt** 
`output_stream: "ITERABLE:multi_handedness"
...
node {
  calculator: "EndLoopClassificationListCalculator"
  input_stream: "ITEM:single_handedness"
  input_stream: "BATCH_END:single_hand_rect_timestamp"
  output_stream: "ITERABLE:multi_handedness"
}`  

**4. mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile.pbtxt**
`node {
  calculator: "MultiHandRendererSubgraph"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "DETECTIONS:multi_palm_detections"
  input_stream: "LANDMARKS:multi_hand_landmarks"
  input_stream: "NORM_RECTS:0:multi_palm_rects"
  input_stream: "NORM_RECTS:1:multi_hand_rects"
  input_stream: "ITERABLE:multi_handedness"
  output_stream: "IMAGE:output_video"
}`  

**5. mediapipe/graphs/hand_tracking/subgraphs/multi_hand_renderer_gpu.pbtxt(iterate ClassificationList to get single_handedness for LabelsToRenderDataCalculator)** 
`node {
  calculator: "BeginLoopClassificationListCalculator"
  input_stream: "ITERABLE:multi_handedness"
  output_stream: "ITEM:single_handedness"
  output_stream: "BATCH_END:landmark_timestamp"
}`    

I have rebuild multihandtracking apk after each modification to confirm is it right.
Both 1-4 is ok. but after 5, the app crashed in my phone.
I have been stuck by this issue, Hoping for help. Thanks

**Comment by cosimo17** [comment]
resolved. It caused by the name of BATCH_END:landmark_timestamp. This name has already be used by another node. I set another name for this. It worked fine now.

**Comment by huolianchu** [comment]
> resolved. It caused by the name of BATCH_END:landmark_timestamp. This name has already be used by another node. I set another name for this. It worked fine now.

I followed your process and got the following error：
E/native: E0107 17:17:40.178897  9019 graph.cc:407] ; Input Stream "multihandlandmarksubgraph__single_handedness" for node with sorted index 19 does not have a corresponding output stream.
How to fix it？
