### ISSUE TITLE
Accessing raw, received camera frames (multihandtracking AAR)

### ISSUE THREAD

**Issue by AlexYiningLiu** [google/mediapipe#793]
My goal is to access each of the raw frames received by the camera, and crop out a rectangular region of the frame (where the index finger tip is) into a new image. I tried to use OpenCV to crop the received frames and produce the new subframes. However, if I create and implement a 

    private CameraBridgeViewBase mOpenCvCameraView;

for OpenCV to access the camera, Mediapipe won't run in the background and I do not receive any of the hand tracking landmark packets because OpenCV is taking camera access and Mediapipe can't use the camera. The PacketCallBack is never triggered. 

I need Mediapipe to access the camera in order to get me the hand landmarks, but I also need to have the raw frames myself to modify them using the information I receive from Mediapipe's handtracking pipeline. I am looking at the mediapipemultihandtrackingapp AAR  found here:
https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example
and in the MainActivity I simply can't find anyway for me to actually receive the raw camera frames. Mediapipe's calculators simply send me the land mark packets but no camera frames, as seen here:

```
processor.addPacketCallback(
                OUTPUT_LANDMARKS_STREAM_NAME,
                (packet) -> {
                    Log.d(TAG, "Received multi-hand landmarks packet.");
                    List<NormalizedLandmarkList> multiHandLandmarks =
                            PacketGetter.getProtoVector(packet, NormalizedLandmarkList.parser());

```
Is there a way for me to access the raw frames from mediapipe then perform cropping on them and save the results to phone storage? Thank you.

**Comment by hadon** [comment]
MediaPipe android components move camera frames through a series of listeners.  The ExternalTextureConverter converts camera frames into frames that MediaPipe can process.  The FrameProcessor sends camera frames into the MediaPipe graph.  The FrameProcessor is registered as a consumer of the ExternalTextureConverter by ExternalTextureConverter.setConsumer().  The FrameProcessor receives frames through FrameProcessor.onNewFrame().  

You can get an indication when a frame is added to FrameProcessor with FrameProcessor.setOnWillAddFrameListener().  I don't yet see a way to intercept the frame received by FrameProcessor.onNewFrame().  

You can see some more details about FrameProcessor at: 
  https://google.github.io/mediapipe/getting_started/hello_world_android.html#externaltextureconverter-setup
  https://google.github.io/mediapipe/getting_started/hello_world_android.html#use-the-graph-in-mainactivity

**Comment by hadon** [comment]
One work-around suggested by @eknight7: You can add a PassThroughCalculator inside the MediaPipe graph consuming the frame input stream.  Then you can observe the output stream of that PassThroughCalculator, using the addPacketCallback().  The observed MediaPipe packets should contain mediapipe::GpuBuffers containing the input raw camera frames.

**Comment by midhulavijayan** [comment]
I am also facing the same issue.. @AlexYiningLiu, have you resolved the issue?

**Comment by hadon** [comment]
Closing this issue for now. Feel free to re-open it if more responses are needed.

**Comment by rgm-22** [comment]
I am also facing the same issue.
@AlexYiningLiu, have you resolved it?
