### ISSUE TITLE
Bazel fails to download files on Windows 10

### ISSUE THREAD

**Issue by delebash** [google/mediapipe#795]
System info:
Python 3.7.7
Windows 10 version 2004
build 19041.329
Bazel Version = Release 3.2.0 (2020-05-27)
BAZEL_VC_FULL_VERSION=14.26.28801
BAZEL_WINSDK_FULL_VERSION=10.1.18362.1

After following all instructions for [installing mediapipe on windows](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows) 

When you try running the helloworld example using
 bazel run --define MEDIAPIPE_DISABLE_GPU=1 \mediapipe/examples/desktop/hello_world:hello_world

Compile will fail with warning: 
Download from https://mirror.bazel.build/github.com/tensorflow/tensorfl
ow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz failed:

Problem:
Bazel version 3.2.0 causes the problem. I have not tested any other 3.x versions.

Fix:
I rolled back to version 2.2.0.  I have also not tried any other 2.x versions

**Comment by jiuqiant** [comment]
Acknowledged. Thanks.
