### ISSUE TITLE
Facing challenge in helo world program

### ISSUE THREAD

**Issue by anubhawlenskart** [google/mediapipe#797]
FAILED: Build did NOT complete successfully (0 packages loaded)
(base) Anubhaws-MacBook-Air:mediapipe-master anubhaw$ bazel build //mediapipe/examples/desktop/hello_world:hello_world
ERROR: /private/var/tmp/_bazel_anubhaw/8e99138d08bb6f81a978157c068090b1/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Analysis failed

**Comment by jiuqiant** [comment]
See https://github.com/google/mediapipe/issues/31
