### ISSUE TITLE
Will windows be officially supported?

### ISSUE THREAD

**Issue by delebash** [google/mediapipe#798]
If so is there a roadmap or time frame?  I would like to use my gpu instead of cpu as it should greatly increase performance.

It's wonderful about the experimental instructions for windows.  I have it up and running with Face Mesh.  I ran into a few issues setting it up and I will do some more research to try and identify the problem. 

Thanks!

**Comment by mgyong** [comment]
No plans to make it officially supported. It will remain experimental

**Comment by delebash** [comment]
Will windows experimental get GPU support?

**Comment by jiuqiant** [comment]
No plan for the GPU support for now.
The problem is our gl_context code relies on pthread and refactoring it for Windows needs a careful design.
