### ISSUE TITLE
How to retrieve hand landmarks position in iOS

### ISSUE THREAD

**Issue by TeddyBerard** [google/mediapipe#80]
Hello,

In the hand tracking gpu example, I would like to retrieve hand landmarks position but I can't see how. Maybe a there is a delegate ?

Can you help me ?

Thanks you

**Comment by chuoling** [comment]
Related to #64 

@TeddyBerard 
Are you asking about getting the landmark coordinates in C++ (e.g., to be used in another calculator), or getting them in iOS to be consumed in the iOS application?
