### ISSUE TITLE
How to convert tensors to gpubuffer for render on android ?

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#800]
1、My tflite model outputting with TfLiteInferenceCalculator is an rgb format data, I want to render it directly.

**Comment by mcclanahoochie** [comment]
Generally the flow of MP examples is:
`Input > convert to Tensor > Tensor Inference > Tensors to X conversion > X to Render Data conversion > AnnotationOverlayCalculator (accepts render data). `
Please see the selection of 'tflite_tensors_to_x' calculators [here](https://github.com/google/mediapipe/tree/master/mediapipe/calculators/tflite) and 'x to render data' calculators [here](https://github.com/google/mediapipe/tree/master/mediapipe/calculators/util)
see if one of those fits your needs.
If not, you will need to create a calculator to convert your tensor data into render data for the AnnotationOverlayCalculator.

If your output tensor is literally an rgb image, you will need to write a calculator to convert it to  mediapiep::ImageFrame , then you can use ImageFrameToGpuBufferCalculator

**Comment by weinixuehao** [comment]
@mcclanahoochie Thanks
