### ISSUE TITLE
Android: Being asked to install a previous version of NDK 

### ISSUE THREAD

**Issue by harsha-main** [google/mediapipe#801]
I tried to run a hand tracking android app by following the official documentation (generating aar file, assets and adding them to the project). When I try to run the project, I was given this message

> No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.3.6528147

In case this is a fault from my end, I need to know if maybe I'm doing something wrong here, as the example of multi hand recognition had run without any such message.

**Comment by jiuqiant** [comment]
Can you try the example repo by doing `git clone https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example.git`?

**Comment by harsha-main** [comment]
@jiuqiant Thank you very much for responding. 
Yes, I did run that and it works very fine, the problem(and other issues that I reported recently) is only when I try to compile things from scratch on my own.

**Comment by jiuqiant** [comment]
For your first question, which Android NDK do you point mediapipe to, v20.0.5594570 or v21.3.6528147? You probably do it either via setting ANDROID_NDK_HOME or putting the ndk path at https://github.com/google/mediapipe/blob/master/WORKSPACE#L195.

**Comment by harsha-main** [comment]
@jiuqiant 
My ANDROID_NDK_HOME in my .bashrc points to the path to v21.3.6528147, which was the only installed NDK at the time for me. 
These NDKs take up close to 1GB of space, so I felt it's odd that mediapipe would ask me to have an older NDK.

**Comment by jiuqiant** [comment]
Seems to be a gradle related issue. Many gradle users are complaining about this in https://github.com/gradle/gradle/issues/12440.

**Comment by harsha-main** [comment]
Thank you
