### ISSUE TITLE
Merging Android assets failed

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#802]
Merging Android assets for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/hededgedetectiongpu:mediapipe_lib failed (Exit 1)
Jun 14, 2020 9:54:22 AM com.google.devtools.build.android.AbstractBusyBoxAction invoke

Sometimes the above error occurs when modify build file or .pbtxt graph But It is built ok after clean.
This is annoying because every time it takes a long time to compile

**Comment by jiuqiant** [comment]
Seems to be a Bazel issue. It might be a good issue/question to https://github.com/bazelbuild/bazel.
