### ISSUE TITLE
What will happen if there is a post-processing part in the trained model

### ISSUE THREAD

**Issue by rose-jinyang** [google/mediapipe#803]
Hello
How are you?
I've trained a model with ssd-mobilenetv2 architecture.
There is a post-processing part in this model.
I know that mediapipe supports a post-processing in model inference.
If I run this model with mediapipe, what will happen?
Thanks

**Comment by fanzhanggoogle** [comment]
You can take a look [here](https://github.com/google/mediapipe/blob/67bd8a2bf04072b853142e7739466dea218ae007/mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc#L366). The `TfLiteTensorsToDetectionsCalculator` supports different types of output from the model. In your case, likely the model has 4 outputs as I remembered for the SSD model, e.g. decoded boxes, classes, scores and number of boxes. If you pass those as the following order in the calculator, it should probably just work.
```
    const TfLiteTensor* detection_boxes_tensor = &input_tensors[0];
    const TfLiteTensor* detection_classes_tensor = &input_tensors[1];
    const TfLiteTensor* detection_scores_tensor = &input_tensors[2];
    const TfLiteTensor* num_boxes_tensor = &input_tensors[3];
```

**Comment by rose-jinyang** [comment]
Thanks for your reply.

**Comment by anvuong48** [comment]
hi @fanzhanggoogle ,

I ran mediapipe with this ssd model and i got error with num_boxes_tensor like below
**calculator::process() for node "tflitetensorstodetectionscalculator" failed: ; ret_check failure (mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc:367) (num_boxes_tensor->dims->size)==(1)**

Do you know  this error happened? Thank you very much
