### ISSUE TITLE
 render the hand model according to hand tracking 3D landmarks

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#804]
I want to render the hand model according to hand tracking 3D landmarks, so I need to calculate the angle of the palm and the screen of the mobile phone, and judge whether the palm is turned over. At present, I use the 3D landmarks of the palm plane (1, 3, 6, 10, 14, 18) to calculate the angle, but the calculated angle is not stable. Any suggestions?

**Comment by fanzhanggoogle** [comment]
One thing I can think of is to use some filtering to smooth the prediction. By `turned over`, do you mean front/back of the hand? If that's the case then probably other information could be helpful, e.g. the relative position of thumb joints and pinky joints.
