### ISSUE TITLE
Sometimes black screen

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#805]
![1592231501057237](https://user-images.githubusercontent.com/17869361/84672769-8535c600-af5b-11ea-8176-414b2d14b34a.gif)

**Comment by mcclanahoochie** [comment]
Can you provide a full LogCat trace? Do any other examples do this? What is the exact phone model and Android version?

**Comment by weinixuehao** [comment]
[log.txt](https://github.com/google/mediapipe/files/4786642/log.txt)
#include "mediapipe/framework/calculator_framework.h"
#include "mediapipe/gpu/gpu_buffer.h"
#include "tensorflow/lite/delegates/gpu/gl/gl_buffer.h"
#include "mediapipe/gpu/gl_calculator_helper.h"
#include "mediapipe/framework/port/opencv_core_inc.h"
#include "mediapipe/gpu/shader_util.h"
#include <typeinfo>
#include <ctime>
#include <string>
#include "fm_ocr_scanner.h"
#include <android/log.h>

typedef ::tflite::gpu::gl::GlBuffer GpuTensor;
namespace mediapipe
{

    namespace
    {
        enum
        {
            ATTRIB_VERTEX,
            ATTRIB_TEXTURE_POSITION,
            NUM_ATTRIBUTES
        };
        size_t RoundUp(size_t n, size_t m) { return ((n + m - 1) / m) * m; } // NOLINT
    }                                                                        // namespace

    class HedEdgeDetectionCalculator : public CalculatorBase
    {
    public:
        static ::mediapipe::Status GetContract(CalculatorContract *cc);

        ::mediapipe::Status Open(CalculatorContext *cc) override;
        ::mediapipe::Status Process(CalculatorContext *cc) override;
        ::mediapipe::Status Close(CalculatorContext *cc) override;
        ::mediapipe::Status GlSetup(CalculatorContext *cc);
        ::mediapipe::Status GlRender(CalculatorContext *cc);
        ::mediapipe::Status renderToGpu(CalculatorContext *cc);

    private:
        mediapipe::GlCalculatorHelper gpu_helper_;
        GLuint preview_tex = 0; //show camera frame.
        bool gpu_initialized_ = false;
        GLuint program_ = 0;
        int width_ = 0;
        int height_ = 0;
    };

    ::mediapipe::Status HedEdgeDetectionCalculator::GetContract(CalculatorContract *cc)
    {
        cc->Inputs().Index(0).Set<std::vector<GpuTensor>>();
        cc->Inputs().Tag("IMAGE_GPU").Set<mediapipe::GpuBuffer>();
        cc->Outputs().Tag("IMAGE_GPU").Set<mediapipe::GpuBuffer>();
        MP_RETURN_IF_ERROR(mediapipe::GlCalculatorHelper::UpdateContract(cc));
        return ::mediapipe::OkStatus();
    }

    ::mediapipe::Status HedEdgeDetectionCalculator::Open(CalculatorContext *cc)
    {
        MP_RETURN_IF_ERROR(gpu_helper_.Open(cc));
        return ::mediapipe::OkStatus();
    }

    ::mediapipe::Status HedEdgeDetectionCalculator::GlSetup(CalculatorContext *cc)
    {
        const GLint attr_location[NUM_ATTRIBUTES] = {
            ATTRIB_VERTEX,
            ATTRIB_TEXTURE_POSITION,
        };
        const GLchar *attr_name[NUM_ATTRIBUTES] = {
            "position",
            "texture_coordinate",
        };

        const GLchar *vert_src = R"(
            #if __VERSION__ < 130
            #define in attribute
            #define out varying
            #endif
            in vec4 position;
            in mediump vec4 texture_coordinate;
            out mediump vec2 sample_coordinate;
            void main() {
                gl_Position = position;
                sample_coordinate = texture_coordinate.xy;
            }
        )";

        const GLchar *frag_src = R"(
            #if __VERSION__ < 130
                #define in varying
            #endif  // __VERSION__ < 130

            #ifdef GL_ES
                #define fragColor gl_FragColor
                precision highp float;
            #else
                #define lowp
                #define mediump
                #define highp
                #define texture2D texture
                out vec4 fragColor;
            #endif  // defined(GL_ES)
            in vec2 sample_coordinate;
            uniform sampler2D previewtexture;
            void main() {
                fragColor = texture2D(previewtexture, sample_coordinate);
            }
        )";

        mediapipe::GlhCreateProgram(vert_src, frag_src,
                                    NUM_ATTRIBUTES, (const GLchar **)&attr_name[0],
                                    attr_location, &program_);
        RET_CHECK(program_) << "Problem initializing the program.";
        glUseProgram(program_);
        glUniform1i(glGetUniformLocation(program_, "input_frame"), 1);
        const auto &input_frame =
            cc->Inputs().Tag("IMAGE_GPU").Get<mediapipe::GpuBuffer>();
        width_ = RoundUp(input_frame.width(), ImageFrame::kGlDefaultAlignmentBoundary);
        height_ = RoundUp(input_frame.height(), ImageFrame::kGlDefaultAlignmentBoundary);
        {
            glGenTextures(1, &preview_tex);
            glBindTexture(GL_TEXTURE_2D, preview_tex);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB8, width_, height_, 0, GL_RGB,
                         GL_UNSIGNED_BYTE, nullptr);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
            glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
            glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
            glBindTexture(GL_TEXTURE_2D, 0);
        }
        return ::mediapipe::OkStatus();
    }

    ::mediapipe::Status HedEdgeDetectionCalculator::GlRender(CalculatorContext *cc)
    {
#if !defined(MEDIAPIPE_DISABLE_GPU)
        static const GLfloat square_vertices[] = {
            -1.0f, -1.0f, // bottom left
            1.0f, -1.0f,  // bottom right
            -1.0f, 1.0f,  // top left
            1.0f, 1.0f,   // top right
        };
        static const GLfloat texture_vertices[] = {
            0.0f, 0.0f, // bottom left
            1.0f, 0.0f, // bottom right
            0.0f, 1.0f, // top left
            1.0f, 1.0f, // top right
        };

        // program
        glUseProgram(program_);

        // vertex storage
        GLuint vbo[2];
        glGenBuffers(2, vbo);
        GLuint vao;
        glGenVertexArrays(1, &vao);
        glBindVertexArray(vao);

        // vbo 0
        glBindBuffer(GL_ARRAY_BUFFER, vbo[0]);
        glBufferData(GL_ARRAY_BUFFER, 4 * 2 * sizeof(GLfloat), square_vertices,
                     GL_STATIC_DRAW);
        glEnableVertexAttribArray(ATTRIB_VERTEX);
        glVertexAttribPointer(ATTRIB_VERTEX, 2, GL_FLOAT, 0, 0, nullptr);

        // vbo 1
        glBindBuffer(GL_ARRAY_BUFFER, vbo[1]);
        glBufferData(GL_ARRAY_BUFFER, 4 * 2 * sizeof(GLfloat), texture_vertices,
                     GL_STATIC_DRAW);
        glEnableVertexAttribArray(ATTRIB_TEXTURE_POSITION);
        glVertexAttribPointer(ATTRIB_TEXTURE_POSITION, 2, GL_FLOAT, 0, 0, nullptr);

        // draw
        glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

        // cleanup
        glDisableVertexAttribArray(ATTRIB_VERTEX);
        glDisableVertexAttribArray(ATTRIB_TEXTURE_POSITION);
        glBindBuffer(GL_ARRAY_BUFFER, 0);
        glBindVertexArray(0);
        glDeleteVertexArrays(1, &vao);
        glDeleteBuffers(2, vbo);
#endif //  !MEDIAPIPE_DISABLE_GPU
        return ::mediapipe::OkStatus();
    }

    ::mediapipe::Status HedEdgeDetectionCalculator::renderToGpu(CalculatorContext *cc)
    {
        const auto &input_frame =
            cc->Inputs().Tag("IMAGE_GPU").Get<mediapipe::GpuBuffer>();
        auto input_texture = gpu_helper_.CreateSourceTexture(input_frame);
        auto output_texture = gpu_helper_.CreateDestinationTexture(width_, height_, mediapipe::GpuBufferFormat::kBGRA32);

        {
            glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
        }

        {
            gpu_helper_.BindFramebuffer(output_texture); // GL_TEXTURE0

            glActiveTexture(GL_TEXTURE1);
            glBindTexture(GL_TEXTURE_2D, input_texture.name());

            MP_RETURN_IF_ERROR(GlRender(cc));

            glActiveTexture(GL_TEXTURE1);
            glBindTexture(GL_TEXTURE_2D, 0);
            glFlush();
        }

        // Send out blended image as GPU packet.
        auto output_frame = output_texture.GetFrame<mediapipe::GpuBuffer>();
        cc->Outputs()
            .Tag("IMAGE_GPU")
            .Add(output_frame.release(), cc->InputTimestamp());

        // Cleanup
        input_texture.Release();
        output_texture.Release();
        return ::mediapipe::OkStatus();
    }

    ::mediapipe::Status HedEdgeDetectionCalculator::Process(CalculatorContext *cc)
    {
        if (!gpu_initialized_)
        {
            MP_RETURN_IF_ERROR(
                gpu_helper_.RunInGlContext([this, cc]() -> ::mediapipe::Status {
                    MP_RETURN_IF_ERROR(GlSetup(cc));
                    return ::mediapipe::OkStatus();
                }));
            gpu_initialized_ = true;
        }
        const auto &input_tensors = cc->Inputs().Index(0).Get<std::vector<GpuTensor>>();
        MP_RETURN_IF_ERROR(gpu_helper_.RunInGlContext([this, &input_tensors, cc]() -> ::mediapipe::Status {
            // auto size = input_tensors.size();
            // auto &hed_tensor = input_tensors[0];
            // const char *name = typeid(hed_tensor).name();
            // size_t float_num = hed_tensor.bytes_size() / 4;
            // std::vector<float> hed_buf(float_num);
            // hed_tensor.Read(absl::MakeSpan(hed_buf));
            // cv::Mat hed_img(256, 256, CV_32FC1, hed_buf.data());
            // auto tuple = ProcessEdgeImage(hed_img, hed_img, true, false);
            // auto find_rect = std::get<0>(tuple);
            // auto cv_points = std::get<1>(tuple);
            // auto debug_mats = std::get<2>(tuple);
            // __android_log_print(ANDROID_LOG_WARN, "jni", "find_rect=%s", find_rect ? "true" : "false");
            // const auto &input = cc->Inputs().Tag("IMAGE_GPU").Get<GpuBuffer>();
            // const char *type = typeid(cc->Outputs().Tag("IMAGE_GPU")).name();
            // cc->Outputs()
            //     .Tag("IMAGE_GPU")
            //     .Add(new GpuBuffer(input.GetGlTextureBufferSharedPtr()), cc->InputTimestamp());
            renderToGpu(cc);
            __android_log_print(ANDROID_LOG_WARN, "jni", "Process method done");
            return ::mediapipe::OkStatus();
        }));

        return ::mediapipe::OkStatus();
    }
    ::mediapipe::Status HedEdgeDetectionCalculator::Close(CalculatorContext *cc)
    {
        gpu_helper_.RunInGlContext([this] {
            if (program_)
                glDeleteProgram(program_);
            program_ = 0;
            if (preview_tex)
                glDeleteTextures(1, &preview_tex);
            preview_tex = 0;
        });

        return ::mediapipe::OkStatus();
    }
    REGISTER_CALCULATOR(HedEdgeDetectionCalculator);
} // namespace mediapipe

**Comment by weinixuehao** [comment]
I don’t see a black screen when I change my phone to another.

**Comment by mcclanahoochie** [comment]
i had a quick look:

one issue i see is never setting your input texture uniform.
your code
`glUniform1i(glGetUniformLocation(program_, "input_frame"), 1);`
and shader
`uniform sampler2D previewtexture;`
 do not match; they should both be named the same (both "input_frame" or both "previewtexture")

also your "preview_tex" texture doesn't seem to be used, and probably isn't necessary, because you are creating a destination texture and binding it via the gpu_helper. 
 
also please utilize the[ visualizer](https://viz.mediapipe.dev/) and make sure your graph connections look correct.

**Comment by weinixuehao** [comment]
@mcclanahoochie Thank you very much for your help, According to your prompt, finally found the problem is `glUniform1i(glGetUniformLocation(program_, "input_frame"), 1); `but fragment shader defined a preview_tex. so to change as `glUniform1i(glGetUniformLocation(program_, "preview_tex"), 1); `  it is ok.
