### ISSUE TITLE
how to detect rotated faces

### ISSUE THREAD

**Issue by flyingmrwang** [google/mediapipe#808]
Here are the interesting cases that I noticed from face_mesh demo, which is pipeline of face detection and landmark prediction:
1. I noticed that face_mesh demo can track very well when my face keep rotating for all degrees in plane.  
2. Also, if the first showed up face is 90% rotated, the result is also perfectly correct. 
3. But if the first showed up face is upside-down. It will predict correct bounding box along with wrong landmarks. 

So my question is did you guys trained the face_detection_front.tflite to have the capability to detect rotated faces? In my view, it is kind of challenging to force such a tiny model to learn faces in different angles. On the other side, however, this feature is almost a must for usage in mobile devices. Cuz you'd never know if the input frame is in portrait,  landscape or other uncommon degree.

**Comment by fanzhanggoogle** [comment]
Our dataset for training face detection for front camera is composed of mostly selfie images and we trained with rotation augmentation (+/- 45 degrees). We don't have much flipped face in the dataset and the model is not expected to work in that case. The reason why it still has bounding box is probably because flipped face has similar features as canonical face and it's kind of `false positive`.

**Comment by flyingmrwang** [comment]
@fanzhanggoogle Thanks for reply. 
For the meaning of "So there're training examples up to 90 degrees rotation.". Do you means the model was aimed to detect faces within [-45, 45] degrees of rotation? (That is a range of 90degrees if we suppose raw faces before augmentation are not rotated) If this is the case, not only flipped face, but also 90 degree rotated face would be outside of your range.

**Comment by fanzhanggoogle** [comment]
Correct, though there could be some 90 degree rotated face appeared in the training due to augmentation, it won't be many. So the model is not anticipated to cover such cases.

**Comment by showbit01** [comment]
can I assume landmarks points x,y,z as 3d for world coordinates and x,y from same landmarks as 2d image coordinates For calculation of rotation matrix then Euler angles for head pose estimation?
Please help!

**Comment by skyler14** [comment]
> @fanzhanggoogle Thanks for reply. For the meaning of "So there're training examples up to 90 degrees rotation.". Do you means the model was aimed to detect faces within [-45, 45] degrees of rotation? (That is a range of 90degrees if we suppose raw faces before augmentation are not rotated) If this is the case, not only flipped face, but also 90 degree rotated face would be outside of your range.

Would fine-tuning with a more balanced dataset potentially improve on this, or are there any reasons to expect that the model still stop working on >90 degree data
