### ISSUE TITLE
Not a valid win32 application

### ISSUE THREAD

**Issue by j-vent** [google/mediapipe#810]
I am following this tutorial: https://google.github.io/mediapipe/getting_started/building_examples.html for Android. However, when I try either method (with or without Android Studio) I am getting an error with bazel not being recognized as an application:

Error:Cannot run program "\\wsl$\Ubuntu\usr\bin\bazel-2.0.0" (in directory "\\wsl$\Ubuntu\mediapipe"): CreateProcess error=193, %1 is not a valid Win32 application

I followed this tutorial to install Bazel: https://docs.bazel.build/versions/master/install-ubuntu.html because the recommended installation method below did not work:

username@DESKTOP-TMVLBJ:             
~$ curl -sLO --retry 5 --retry-max-time 10 \
https://storage.googleapis.com/bazel/2.0.0/release/bazel-2.0.0-installer-linux-x86_64.sh && \
sudo mkdir -p /usr/local/bazel/2.0.0 && \
chmod 755 bazel-2.0.0-installer-linux-x86_64.sh && \
sudo ./bazel-2.0.0-installer-linux-x86_64.sh --prefix=/usr/local/bazel/2.0.0 && \
source /usr/local/bazel/2.0.0/lib/bazel/bin/bazel-complete.bash
username@DESKTOP-TMVLBJ1:~$ /usr/local/bazel/2.0.0/lib/bazel/bin/bazel version && \
alias bazel='/usr/local/bazel/2.0.0/lib/bazel/bin/bazel'

I am running this on Ubuntu 20 but the Bazel docs say it mainly supports v16 and v18, but should likely work on other releases. This is the only issue I can think of, so I would appreciate any suggestions that could help me fix this issue.

**Comment by jiuqiant** [comment]
Bazel linux version is only useable in WSL, not in native Windows. Are you running this in WSL or native Windows?

**Comment by j-vent** [comment]
Hi! I am running this in WSL.

**Comment by jiuqiant** [comment]
It looks good on WSL Ubuntu 1804.

```
jiuqiant@DESKTOP-TMVLBJ1:~/mp_github/mediapipe$ alias bazel='/usr/local/bazel/2.0.0/lib/bazel/bin/bazel'
jiuqiant@DESKTOP-TMVLBJ1:~/mp_github/mediapipe$ bazel version
Starting local Bazel server and connecting to it...
Build label: 2.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:30:18 2019 (1576758618)
Build timestamp: 1576758618
Build timestamp as int: 1576758618
```

**Comment by jiuqiant** [comment]
It looks good on WSL Ubuntu 1804.

```
username@DESKTOP-TMVLBJ1:~/mp_github/mediapipe$ alias bazel='/usr/local/bazel/2.0.0/lib/bazel/bin/bazel'
username@DESKTOP-TMVLBJ1:~/mp_github/mediapipe$ bazel version
Starting local Bazel server and connecting to it...
Build label: 2.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:30:18 2019 (1576758618)
Build timestamp: 1576758618
Build timestamp as int: 1576758618
```

**Comment by j-vent** [comment]
Hi, I was able to successfully build on desktop but when trying to use the Android application, I run into various errors. Like when running the following: bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
taken from 
https://google.github.io/mediapipe/getting_started/building_examples.html#option-1-build-with-bazel-in-command-line

I got the following error:
ERROR: An error occurred during the fetch of repository 'android_opencv':
   java.io.IOException: Error extracting /home/jvent/.cache/bazel/_bazel_root/f29b92a6a0e4213425896677f56383cf/external/android_opencv/opencv-3.4.3-android-sdk.zip to /home/jvent/.cache/bazel/_bazel_root/f29b92a6a0e4213425896677f56383cf/external/android_opencv: writing file failed
ERROR: /home/jvent/Android/Sdk/mediapipe/third_party/BUILD:56:11: //third_party:opencv depends on @android_opencv//:libopencv_arm64-v8a in repository @android_opencv which failed to fetch. no such package '@android_opencv//': java.io.IOException: Error extracting /home/jvent/.cache/bazel/_bazel_root/f29b92a6a0e4213425896677f56383cf/external/android_opencv/opencv-3.4.3-android-sdk.zip to /home/jvent/.cache/bazel/_bazel_root/f29b92a6a0e4213425896677f56383cf/external/android_opencv: writing file failed
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld' failed; build aborted: Analysis failed
INFO: Elapsed time: 528.592s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (63 packages loaded, 5615 targets configured)
    Fetching ...opencv; Extracting /home/jvent/.cache/bazel/_bazel_root/f29b92a6a0e421342589667\
7f56383cf/external/android_opencv/opencv-3.4.3-android-sdk.zip 11s

**Comment by j-vent** [comment]
I was successful in running the BUILD but then when I actually try to install on my device using
adb install bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu.apk

I get:
adb: failed to stat bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu.apk: No such file or directory

**Comment by jiuqiant** [comment]
`bazel-bin/` is generated by Bazel and it's a symlink to some tmp directory such as `/home/jvent/.cache/bazel/_bazel_jvent/f29b92a6a0e4213425896677f56383cf/execroot/`.

From the log, I think the APK already exists at `/home/jvent/.cache/bazel/_bazel_jvent/f29b92a6a0e4213425896677f56383cf/execroot/mediapipe/bazel-out/arm64-v8a-opt/bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/multihandtrackinggpu/multihandtrackinggpu.apk`. 

You probably can do the following in WSL:
```
adb install -r /home/jvent/.cache/bazel/_bazel_jvent/f29b92a6a0e4213425896677f56383cf/execroot/mediapipe/bazel-out/arm64-v8a-opt/bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/multihandtrackinggpu/multihandtrackinggpu.apk
```

If `adb install` doesn't work in WSL, you also can find the APK file in native Windows and do adb install from there. Here is how to find the your WSL home directory in native Windows: https://superuser.com/questions/1185033/what-is-the-home-directory-on-windows-subsystem-for-linux

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
