### ISSUE TITLE
Possibility of obtaining better framerate by adding constraints?

### ISSUE THREAD

**Issue by harsha-main** [google/mediapipe#811]
I have downloaded the Mediapipe's android repository, ran it on my mobile and felt the detection is too sluggish, and the overlay to be wiggling oftentimes. I still highly appreciate your work though:)

So I'm trying to see if there's a way to let the framework understand that I'm looking for specific requirement where the hand is within 30 cm to the phone camera (the case where the user holds the phone in one hand, and scans the other hand). I'm hoping this would eliminate the need for the algorithm to look for smaller sized hands relative to the video frame and save computation significantly.

Another constraint I have in mind is to assume that the user uses this only with his hand over a plain background.

I feel such flexibility could make this framework better suited to specific use case scenarios.

**Comment by sgowroji** [comment]
Hi @harsha-main, Could you please recheck the latest release as there are lots of improvements are added. And let us know if you still looking for any specific use case. Thanks!
