### ISSUE TITLE
请问hand_landmark.tflite输出的63个值分别是什么？

### ISSUE THREAD

**Issue by FFoCC** [google/mediapipe#813]
请问hand_landmark.tflite输出的63个值分别是什么？我用hand_landmark.tflite做推理，输出的值不知道怎样才能转化为对应图像的手的21个点的坐标。

```
class tflite:
    def __init__(self):
        self.interpreter = tf.lite.Interpreter(model_path=MODEL)
        self.interpreter.allocate_tensors()

    def inference(self, img):
        input_details = self.interpreter.get_input_details()
        output_details = self.interpreter.get_output_details()
        input_shape = input_details[0]['shape']
        input_data = img
        self.interpreter.set_tensor(input_details[0]['index'], input_data)
        self.interpreter.invoke()
        output_data = self.interpreter.get_tensor(output_details[0]['index'])
        return output_data
······
picture = cv2.resize(picture, dsize=(256, 256))
img = np.array(picture, np.float32)
img = img[None, ...]
output_data = tflite_class.inference(img)
print(output_data)
```

得到的output_data如下：
[[ 2.42368134e+02  4.29899139e+02 -5.48762381e-02  2.11086243e+02
   3.65420166e+02 -3.91246452e+01  2.30923889e+02  3.28564972e+02
  -8.30017166e+01  2.45549408e+02  3.04466980e+02 -1.16235397e+02
   2.66190582e+02  2.80541840e+02 -1.52896332e+02  2.18027328e+02
   1.78340378e+02 -1.04162155e+02  1.78628067e+02  1.65665726e+02
  -1.89991821e+02  2.42668350e+02  1.53240204e+02 -2.82107361e+02
   2.97938080e+02  1.34190659e+02 -3.54283112e+02  2.49116867e+02
   1.85194580e+02 -1.02497101e+02  1.78983322e+02  1.75666702e+02
  -1.30729584e+02  1.78620758e+02  1.71324402e+02 -1.32303802e+02
   2.14221985e+02  1.54626724e+02 -1.52826813e+02  2.49966797e+02
   2.11364517e+02 -1.11617081e+02  1.66932114e+02  2.11517578e+02
  -1.59132217e+02  1.53438263e+02  2.14067505e+02 -1.67287460e+02
   1.60443573e+02  2.17438705e+02 -1.76919830e+02  2.33540237e+02
   2.63383087e+02 -1.15730713e+02  1.84089661e+02  2.71049286e+02
  -1.44646011e+02  1.71549744e+02  2.82188080e+02 -1.22772530e+02
   1.87067749e+02  2.66481262e+02 -1.17287971e+02]]

**Comment by wangqiang624731186** [comment]
x,y,z

**Comment by wangqiang624731186** [comment]
再x256

**Comment by FFoCC** [comment]
> x,y,z

请问x,y的值已经超出了图片的大小256，是什么原因呢？

**Comment by FFoCC** [comment]
> 再x256

您的意思是输出值是xyz的值乘以256吗？

可是我把输出值除256的话太小了，乘以256，太大了，画在图上都不是手的样子   
```
for idx in range(0, output_data.shape[1], 3):
            cv2.circle(picture, (int(output_data[0][idx] / 256), int(output_data[0][idx + 1] / 256)), 5,
                       (0, 0, 255), 1)
```

**Comment by wangqiang624731186** [comment]
你的做法因该不对，你需要先拿另一个模型palm把手识别出来，再拿识别出来的手框截取出来，作为landmark这个模型的输入

**Comment by FFoCC** [comment]
> 你的做法因该不对，你需要先拿另一个模型palm把手识别出来，再拿识别出来的手框截取出来，作为landmark这个模型的输入

我可以只把手框输入模型，但是这个输出值的范围依然太大了，xy都是百位的。是我的推理代码有问题吗？

**Comment by fanzhanggoogle** [comment]
@wangqiang624731186 is correct that you should use the palm detector to crop the hand region as input to the landmark model as the landmark model is sensitive to the orientation of the hand.
Also, I don't see preprocessing in your inference code, e.g. normalize the image to [0, 1].

**Comment by fanzhanggoogle** [comment]
Also, please describe your question and discuss in English so that everyone on the team could help on the issues. Thank you for trying the model.

**Comment by xxiMiaxx** [comment]
This seems relevant to what i'm trying to achieve, please write your comments in English

**Comment by NeekHua** [comment]
@FFoCC 请问你最终解决了这个问题了吗？
