### ISSUE TITLE
Segmentation fault (core dumped) when running hello world example for desktop on WSL

### ISSUE THREAD

**Issue by laurieban** [google/mediapipe#816]
I've followed the installation steps on WSL. But when I ran the hello world example for desktop with the command I found in MediaPipe docs : bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/hello_world:hello_world. The build completed successfully and there is a segmentation fault (core dumped) without any error : 

![error](https://user-images.githubusercontent.com/46228723/84907195-33a04f00-b0b3-11ea-9c5f-ca1e5e5c1903.PNG)

**Configuration** : 
WSL : Ubuntu 20.04 LTS
GPU : Intel UHD Graphics 600 
Bazel : 2.0.0
gcc : 9.3.0
g++ : 9.3.0
opencv : 4
ffmpeg : 4.2.2

**Comment by jiuqiant** [comment]
Thanks for reporting this issue. While we are still working on a proper way to fix it, here is a temporarily workaround: 

```
diff --git a/mediapipe/framework/legacy_calculator_support.h b/mediapipe/framework/legacy_calculator_support.h
index 6a76101..07475e0 100644
--- a/mediapipe/framework/legacy_calculator_support.h
+++ b/mediapipe/framework/legacy_calculator_support.h
@@ -41,13 +41,11 @@ class LegacyCalculatorSupport {
     // The constructor saves the current value of current_ in an instance
     // member, which is then restored by the destructor.
     explicit Scoped(C* cc) {
-      saved_ = current_;
-      current_ = cc;
     }
-    ~Scoped() { current_ = saved_; }
+    ~Scoped() {}
 
     // The current C* for this thread.
-    static C* current() { return current_; }
+    static C* current() { return nullptr; }
 
    private:
     // The value to restore after exiting this scope.
```

**Comment by jiuqiant** [comment]
The solution is adding the following code to `mediapipe/framework/legacy_calculator_support.h` at [line 68](https://github.com/google/mediapipe/blob/cd2b69d58cee2b76fb9ffb6f84766a561431fec3/mediapipe/framework/legacy_calculator_support.h#L68).

```
template <>
thread_local CalculatorContext*
    LegacyCalculatorSupport::Scoped<CalculatorContext>::current_;
template <>
thread_local CalculatorContract*
    LegacyCalculatorSupport::Scoped<CalculatorContract>::current_;
```

**Comment by jiuqiant** [comment]
The fix is released in https://github.com/google/mediapipe/commit/e9fbe868e55fa23aaabc31f9f847c22287062850.
