### ISSUE TITLE
Error in building extract_yt8m_features

### ISSUE THREAD

**Issue by zhangatao** [google/mediapipe#819]
hello, I was able to build and run the hello_world example on Linux.
When i try to build the extract_yt8m_features

bazel build -c opt --linkopt=-s --define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true mediapipe/examples/desktop/youtube8m:extract_yt8m_features

I receive the following errors:
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = a07fc8b90c22e42962142504438a84b31567976adcd9ee1a4c9f75d2e3396f8d
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a07fc8b90c22e42962142504438a84b31567976adcd9ee1a4c9f75d2e3396f8d"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/chenjun/.cache/bazel/_bazel_maohong/3f5936c9806ac1aa59a31ca468f941b4/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /hdd1/zpt/mediapipe/WORKSPACE:33:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: storage.googleapis.com
INFO: Call stack for the definition of repository 'eigen_archive' which is a tf_http_archive (rule definition at /home/chenjun/.cache/bazel/_bazel_maohong/3f5936c9806ac1aa59a31ca468f941b4/external/org_tensorflow/third_party/repo.bzl:134:19):
 - <builtin>
 - /home/chenjun/.cache/bazel/_bazel_maohong/3f5936c9806ac1aa59a31ca468f941b4/external/org_tensorflow/tensorflow/workspace.bzl:249:5
 - /home/chenjun/.cache/bazel/_bazel_maohong/3f5936c9806ac1aa59a31ca468f941b4/external/org_tensorflow/tensorflow/workspace.bzl:77:5
 - /hdd1/zpt/mediapipe/WORKSPACE:337:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/gitlab.com/libeigen/eigen/-/archive/49f1aeb60d9f759859fce0d16aa5d1ecc7168d51/eigen-49f1aeb60d9f759859fce0d16aa5d1ecc7168d51.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: storage.googleapis.com
WARNING: Download from https://gitlab.com/libeigen/eigen/-/archive/49f1aeb60d9f759859fce0d16aa5d1ecc7168d51/eigen-49f1aeb60d9f759859fce0d16aa5d1ecc7168d51.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 406 Not Acceptable
ERROR: An error occurred during the fetch of repository 'eigen_archive':
   java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/gitlab.com/libeigen/eigen/-/archive/49f1aeb60d9f759859fce0d16aa5d1ecc7168d51/eigen-49f1aeb60d9f759859fce0d16aa5d1ecc7168d51.tar.gz, https://gitlab.com/libeigen/eigen/-/archive/49f1aeb60d9f759859fce0d16aa5d1ecc7168d51/eigen-49f1aeb60d9f759859fce0d16aa5d1ecc7168d51.tar.gz] to /home/chenjun/.cache/bazel/_bazel_maohong/3f5936c9806ac1aa59a31ca468f941b4/external/eigen_archive/eigen-49f1aeb60d9f759859fce0d16aa5d1ecc7168d51.tar.gz: GET returned 406 Not Acceptable
INFO: Call stack for the definition of repository 'com_github_glog_glog' which is a http_archive (rule definition at /home/chenjun/.cache/bazel/_bazel_maohong/3f5936c9806ac1aa59a31ca468f941b4/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /hdd1/zpt/mediapipe/WORKSPACE:79:1
INFO: Call stack for the definition of repository 'com_google_audio_tools' which is a http_archive (rule definition at /home/chenjun/.cache/bazel/_bazel_maohong/3f5936c9806ac1aa59a31ca468f941b4/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /hdd1/zpt/mediapipe/WORKSPACE:125:1
ERROR: /hdd1/zpt/mediapipe/mediapipe/framework/formats/BUILD:76:1: //mediapipe/framework/formats:matrix depends on @eigen_archive//:eigen in repository @eigen_archive which failed to fetch. no such package '@eigen_archive//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/gitlab.com/libeigen/eigen/-/archive/49f1aeb60d9f759859fce0d16aa5d1ecc7168d51/eigen-49f1aeb60d9f759859fce0d16aa5d1ecc7168d51.tar.gz, https://gitlab.com/libeigen/eigen/-/archive/49f1aeb60d9f759859fce0d16aa5d1ecc7168d51/eigen-49f1aeb60d9f759859fce0d16aa5d1ecc7168d51.tar.gz] to /home/chenjun/.cache/bazel/_bazel_maohong/3f5936c9806ac1aa59a31ca468f941b4/external/eigen_archive/eigen-49f1aeb60d9f759859fce0d16aa5d1ecc7168d51.tar.gz: GET returned 406 Not Acceptable
ERROR: Analysis of target '//mediapipe/examples/desktop/youtube8m:extract_yt8m_features' failed; build aborted: no such package '@eigen_archive//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/gitlab.com/libeigen/eigen/-/archive/49f1aeb60d9f759859fce0d16aa5d1ecc7168d51/eigen-49f1aeb60d9f759859fce0d16aa5d1ecc7168d51.tar.gz, https://gitlab.com/libeigen/eigen/-/archive/49f1aeb60d9f759859fce0d16aa5d1ecc7168d51/eigen-49f1aeb60d9f759859fce0d16aa5d1ecc7168d51.tar.gz] to /home/chenjun/.cache/bazel/_bazel_maohong/3f5936c9806ac1aa59a31ca468f941b4/external/eigen_archive/eigen-49f1aeb60d9f759859fce0d16aa5d1ecc7168d51.tar.gz: GET returned 406 Not Acceptable
INFO: Elapsed time: 114.055s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (61 packages loaded, 373 targets configured)
My environment is as follows:
python == 3.6.9
bazel == 3.0.0

**Comment by zhangatao** [comment]
I am in China now. Is this caused by the internet?

**Comment by jiuqiant** [comment]
Very likely. You probably can find some useful solutions at https://github.com/google/mediapipe/issues/3, https://github.com/google/mediapipe/issues/581, and https://github.com/google/mediapipe/issues/601.

**Comment by zhangatao** [comment]
> Very likely. You probably can find some useful solutions at #3, #581, and #601.
Hello, when I execute the following
bazel fetch //... --keep_going --repository_cache=<your cache directory>
, The following error message will appear:
![image](https://user-images.githubusercontent.com/28706321/85247088-3fa75a80-b47f-11ea-8739-6ab6f6fce091.png)
