### ISSUE TITLE
How to efficiently convert tensor to cv::Mat

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#821]
My tflite model inferencing output was an image in rgb format, below code was so slow.
```
std::vector<float> hed_buf(float_num);
hed_tensor.Read(absl::MakeSpan(hed_buf));
```
`hed_tensor` is `typedef ::tflite::gpu::gl::GlBuffer GpuTensor;`
How get an buf address from GpuTensor? the above code seems to be a deep copy.

**Comment by mcclanahoochie** [comment]
There is no direct conversion between GpuTensor and cv::Mat. You will need to download the data from GPU to CPU (via tensor.Read()).
You can create a cv::Mat from a vector without deep copy:
`cv::Mat hed_tensor_mat( 1, hed_buf.size(), CV_32FC1, hed_buf.data());
`
This would simple wrap the Mat around the std::vector data (vector still owns the data). (you may need to call "[reshape](https://docs.opencv.org/3.4.10/d3/d63/classcv_1_1Mat.html#a4eb96e3251417fa88b78e2abd6cfd7d8)()" for your tensor dimesntions:
`hed_tensor_mat = hed_tensor_mat.reshape(channels,rows)
`

**Comment by weinixuehao** [comment]
06-21 18:24:44.473 28707 28761 W jni     : elasped_time=34
06-21 18:24:44.698 28707 28761 W jni     : elasped_time=108
06-21 18:24:44.954 28707 28761 W jni     : elasped_time=97
06-21 18:24:45.183 28707 28761 W jni     : elasped_time=118
06-21 18:24:45.405 28707 28761 W jni     : elasped_time=115
06-21 18:24:45.595 28707 28761 W jni     : elasped_time=93
06-21 18:24:45.832 28707 28761 W jni     : elasped_time=107
06-21 18:24:46.083 28707 28761 W jni     : elasped_time=106
06-21 18:24:46.300 28707 28761 W jni     : elasped_time=108
06-21 18:24:46.465 28707 28761 W jni     : elasped_time=112
06-21 18:24:46.611 28707 28761 W jni     : elasped_time=93
06-21 18:24:46.756 28707 28761 W jni     : elasped_time=95
06-21 18:24:46.903 28707 28761 W jni     : elasped_time=80
06-21 18:24:47.017 28707 28761 W jni     : elasped_time=82
06-21 18:24:47.173 28707 28761 W jni     : elasped_time=91
06-21 18:24:47.329 28707 28761 W jni     : elasped_time=82
06-21 18:24:47.473 28707 28761 W jni     : elasped_time=116
06-21 18:24:47.579 28707 28761 W jni     : elasped_time=46
06-21 18:24:47.723 28707 28761 W jni     : elasped_time=90
06-21 18:24:47.841 28707 28761 W jni     : elasped_time=68
06-21 18:24:47.963 28707 28761 W jni     : elasped_time=75
06-21 18:24:48.084 28707 28761 W jni     : elasped_time=72
06-21 18:24:48.205 28707 28761 W jni     : elasped_time=87
06-21 18:24:48.372 28707 28761 W jni     : elasped_time=112
06-21 18:24:48.518 28707 28761 W jni     : elasped_time=104
06-21 18:24:48.653 28707 28761 W jni     : elasped_time=69
06-21 18:24:48.758 28707 28761 W jni     : elasped_time=78
06-21 18:24:48.907 28707 28761 W jni     : elasped_time=89
06-21 18:24:49.035 28707 28761 W jni     : elasped_time=76
06-21 18:24:49.183 28707 28761 W jni     : elasped_time=94
06-21 18:24:49.309 28707 28761 W jni     : elasped_time=86
06-21 18:24:49.467 28707 28761 W jni     : elasped_time=87
06-21 18:24:49.628 28707 28761 W jni     : elasped_time=116
06-21 18:24:49.765 28707 28761 W jni     : elasped_time=95
06-21 18:24:49.877 28707 28761 W jni     : elasped_time=67
06-21 18:24:50.028 28707 28761 W jni     : elasped_time=103
06-21 18:24:50.153 28707 28761 W jni     : elasped_time=80
06-21 18:24:50.306 28707 28761 W jni     : elasped_time=93
06-21 18:24:50.451 28707 28761 W jni     : elasped_time=87
06-21 18:24:50.587 28707 28761 W jni     : elasped_time=79
06-21 18:24:50.716 28707 28761 W jni     : elasped_time=78
06-21 18:24:50.857 28707 28761 W jni     : elasped_time=97
06-21 18:24:51.024 28707 28761 W jni     : elasped_time=103
06-21 18:24:51.152 28707 28761 W jni     : elasped_time=80
06-21 18:24:51.286 28707 28761 W jni     : elasped_time=87
06-21 18:24:51.457 28707 28761 W jni     : elasped_time=107
06-21 18:24:51.569 28707 28761 W jni     : elasped_time=72
06-21 18:24:51.703 28707 28761 W jni     : elasped_time=85
06-21 18:24:51.875 28707 28761 W jni     : elasped_time=108
06-21 18:24:52.004 28707 28761 W jni     : elasped_time=85
06-21 18:24:52.145 28707 28761 W jni     : elasped_time=95
06-21 18:24:52.286 28707 28761 W jni     : elasped_time=87
06-21 18:24:52.402 28707 28761 W jni     : elasped_time=78
06-21 18:24:52.506 28707 28761 W jni     : elasped_time=67
06-21 18:24:52.606 28707 28761 W jni     : elasped_time=69
06-21 18:24:52.711 28707 28761 W jni     : elasped_time=76
06-21 18:24:52.818 28707 28761 W jni     : elasped_time=75
06-21 18:24:52.937 28707 28761 W jni     : elasped_time=74
06-21 18:24:53.056 28707 28761 W jni     : elasped_time=89
06-21 18:24:53.158 28707 28761 W jni     : elasped_time=73
06-21 18:24:53.256 28707 28761 W jni     : elasped_time=72
06-21 18:24:53.363 28707 28761 W jni     : elasped_time=74
06-21 18:24:53.470 28707 28761 W jni     : elasped_time=73
06-21 18:24:53.602 28707 28761 W jni     : elasped_time=88
06-21 18:24:53.717 28707 28761 W jni     : elasped_time=72
06-21 18:24:53.830 28707 28761 W jni     : elasped_time=81
06-21 18:24:53.926 28707 28761 W jni     : elasped_time=69
06-21 18:24:54.038 28707 28761 W jni     : elasped_time=79
06-21 18:24:54.149 28707 28761 W jni     : elasped_time=82
06-21 18:24:54.316 28707 28761 W jni     : elasped_time=125
06-21 18:24:54.455 28707 28761 W jni     : elasped_time=91
06-21 18:24:54.640 28707 28761 W jni     : elasped_time=69

```
            auto size = input_tensors.size();
            auto &hed_tensor = input_tensors[0];
            const char *name = typeid(hed_tensor).name();
            size_t float_num = hed_tensor.bytes_size() / 4;
            std::vector<float> hed_buf(float_num);
            std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();

            hed_tensor.Read(absl::MakeSpan(hed_buf));
            cv::Mat hed_img(256, 256, CV_32FC1, hed_buf.data());

            std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();
            long long elasped_time = std::chrono::duration_cast<std::chrono::microseconds>(end - begin).count() / 1000;
            __android_log_print(ANDROID_LOG_WARN, "jni", "elasped_time=%llu", elasped_time);
```

I have used the tensor`s Read function and measured the time spent. it took about 70 ms average. can it be reduced to a few milliseconds?

**Comment by mcclanahoochie** [comment]
Looks like your options are:
-to write a compute shader to process the gpu tensor (similar to the code in TensorsToDetectionsCalculator), or 
-to have the Inference calculator output directly to CPU tensor (potentially more efficiently than the tensor.Read). 

For the former, you will need to research in other places to learn about writing opengl shaders for your task.  

To do the latter, simply change
`   output_stream: "TENSORS_GPU:tensors"`
to
`   output_stream: "TENSORS:tensors"`
for the inference calculator, then you will have a TfLiteTensor result which you can follow a similar approach to wrap as a cv::Mat
`cv::Mat hed_tensor_mat( 1, hed_buf.size(), CV_32FC1, input_tensors[0]->data.f);`
_NOTE: make sure you keep the input_stream as gpu_

**Comment by weinixuehao** [comment]
@mcclanahoochie 
Thank you! 
1、I know the compute shader but to implement the function that similar to the houghlinesp of opencv function, i have no idea. 
2、For now, the latter seems to be more suitable for me.
