### ISSUE TITLE
How to build hand tracking ios static library or framework with bazel ?

### ISSUE THREAD

**Issue by bluce** [google/mediapipe#822]
I need to build ios static library

**Comment by kulich-ua** [comment]
You will find solutions in those threads:
https://github.com/google/mediapipe/issues/144
https://github.com/google/mediapipe/issues/364 
In order to build a static library I had to do unpleasant workarounds for some issues.
Building a dynamic one is easier.

**Comment by bluce** [comment]
Thank @kulich-ua 
dynamic is worked!

but I want to build static lib

I use ios_static_framework, but *Calculator doesn't register

`Failed to start graph: Error Domain=GoogleUtilStatusErrorDomain Code=5 "ValidatedGraphConfig Initialization failed.
No registered object with name: ImageTransformationCalculator; Unable to find Calculator "ImageTransformationCalculator"
No registered object with name: TfLiteCustomOpResolverCalculator; Unable to find Calculator "TfLiteCustomOpResolverCalculator"
No registered object with name: TfLiteConverterCalculator; Unable to find Calculator "TfLiteConverterCalculator"
No registered object with name: TfLiteInferenceCalculator; Unable to find Calculator "TfLiteInferenceCalculator"
No registered object with name: SsdAnchorsCalculator; Unable to find Calculator "SsdAnchorsCalculator"
No registered object with name: TfLiteTensorsToDetectionsCalculator; Unable to find Calculator "TfLiteTensorsToDetectionsCalculator"
No registered object with name: NonMaxSuppressionCalculator; Unable to find Calculator "NonMaxSuppressionCalculator"
No registered object with name: DetectionLabelIdToTextCalculator; Unable to find Calculator "DetectionLabelIdToTextCalculator"
No registered object with name: DetectionLetterboxRemovalCalculator; Unable to find Calculator "DetectionLetterboxRemovalCalculator"
No registered object with name: ImagePropertiesCalculator; Unable to find Calculator "ImagePropertiesCalculator"
No registered object with name: DetectionsToRectsCalculator; Unable to find Calculator "DetectionsToRectsCalculator"
No registered object with name: RectTransformationCalculator; Unable to find Calculator "RectTransformationCalculator"
No registered object with name: ImageCroppingCalculator; Unable to find Calculator "ImageCroppingCalculator"
No registered object with name: ImageTransformationCalculator; Unable to find Calculator "ImageTransformationCalculator"
No registered object with name: TfLiteCustomOpResolverCalculator; Unable to find Calculator "TfLiteCustomOpResolverCalculator"
No registered object with name: TfLiteConverterCalculator; Unable to find Calculator "TfLiteConverterCalculator"
No registered object with name: TfLiteInferenceCalculator; Unable to find Calculator "TfLiteInferenceCalculator"
No registered object with name: SplitTfLiteTensorVectorCalculator; Unable to find Calculator "SplitTfLiteTensorVectorCalculator"
No registered object with name: TfLiteTensorsToFloatsCalculator; Unable to find Calculator "TfLiteTensorsToFloatsCalculator"
No registered object with name: TfLiteTensorsToClassificationCalculator; Unable to find Calculator "TfLiteTensorsToClassificationCalculator"
No registered object with name: ThresholdingCalculator; Unable to find Calculator "ThresholdingCalculator"
No registered object with name: TfLiteTensorsToLandmarksCalculator; Unable to find Calculator "TfLiteTensorsToLandmarksCalculator"
No registered object with name: LandmarkLetterboxRemovalCalculator; Unable to find Calculator "LandmarkLetterboxRemovalCalculator"
No registered object with name: LandmarkProjectionCalculator; Unable to find Calculator "LandmarkProjectionCalculator"
No registered object with name: ImagePropertiesCalculator; Unable to find Calculator "ImagePropertiesCalculator"
No registered object with name: SplitNormalizedLandmarkListCalculator; Unable to find Calculator "SplitNormalizedLandmarkListCalculator"
No registered object with name: LandmarksToDetectionCalculator; Unable to find Calculator "LandmarksToDetectionCalculator"
No registered object with name: HandDetectionsToRectsCalculator; Unable to find Calculator "HandDetectionsToRectsCalculator"
No registered object with name: RectTransformationCalculator; Unable to find Calculator "RectTransformationCalculator"
No registered object with name: LabelsToRenderDataCalculator; Unable to find Calculator "LabelsToRenderDataCalculator"
No registered object with name: DetectionsToRenderDataCalculator; Unable to find Calculator "DetectionsToRenderDataCalculator"
No registered object with name: LandmarksToRenderDataCalculator; Unable to find Calculator "LandmarksToRenderDataCalculator"

No registered object with name: RectToRenderDataCalculator; Unable to find Calculator "RectToRenderDataCalculator"`

**Comment by jaikydota** [comment]
@kulich-ua  I have same issue,  can you provide your BUILD file or WORKSPACE file, thanks!

**Comment by kulich-ua** [comment]
> I use ios_static_framework, but *Calculator doesn't register

@bluce, yeah, that's the main issue, people are struggling with.
And in tickets, which I mentioned above, are some tips how to workaround it.
There is also my workaround: https://github.com/google/mediapipe/issues/144#issuecomment-639434434

**Comment by kulich-ua** [comment]
@jaikydota, yeap, here it is [BUILD](https://github.com/google/mediapipe/files/4813783/BUILD.txt)
Please check also this comment https://github.com/google/mediapipe/issues/144#issuecomment-639434434 in order to be able to understand where all the MissingClasses files comes from

**Comment by bluce** [comment]
@kulich-ua
1.  I rename file flow_limiter_calculator.cc to flow_limiter_calculator.h, and include .h into other file, then FlowLimiterCalculator is registered.
But Some Calculators classes is registered from BUILD files, like RendererSubgraph and HandLandmarkSubgraph, I found that these create by simple_subgraph_template.cc.

Did you register *Calculators one by one   like 1 step?

https://github.com/google/mediapipe/issues/822#issuecomment-647388328

**Comment by bluce** [comment]
> @jaikydota, yeap, here it is [BUILD](https://github.com/google/mediapipe/files/4813783/BUILD.txt)
> Please check also this comment [#144 (comment)](https://github.com/google/mediapipe/issues/144#issuecomment-639434434) in order to be able to understand where all the MissingClasses files comes from

Do you rename all the *Calculators cc file to h and include them into MissingClasses Files?

**Comment by kulich-ua** [comment]
> Did you register *Calculators one by one like 1st. step?

@bluce, yes, I checked the log saw what classes there missing, included them and checked again the log in order to see what else is missing (and then all over again). 

> Do you rename all the *Calculators cc file to h and include them into MissingClasses Files?

Not all, I renamed only classes which there missing .h files

**Comment by aaaron7** [comment]
@bluce another workaround:  https://github.com/google/mediapipe/issues/144#issuecomment-720992805
