### ISSUE TITLE
Object tracking box info

### ISSUE THREAD

**Issue by WildSpirit007** [google/mediapipe#826]
Hello,
I followed the instructions regarding setting up Objecttracking gpu on the android device. It is successfully running. However, I want get the tracking box info (Rect, label, Id , confidence). Could you please help me out here? I tried to add the following code on OnCreate the app starts crashing.
`
processor.addPacketCallback("tracked_detections",(packet)->{
      byte[] box = PacketGetter.getProtoBytes(packet);
// then check if it is null or not 
    });
`
Could you please give me some insights to solve this issue? Thank you in advance

**Comment by jiuqiant** [comment]
First step, please add "tracked_detections" as an output_stream in the graph.
```
--- a/mediapipe/graphs/tracking/object_detection_tracking_mobile_gpu.pbtxt
+++ b/mediapipe/graphs/tracking/object_detection_tracking_mobile_gpu.pbtxt
@@ -6,6 +6,7 @@
 # Images on GPU coming into and out of the graph.
 input_stream: "input_video"
 output_stream: "output_video"
+output_stream: "tracked_detections"

 # Resamples the images by specific frame rate. This calculator is used to
 # control the frequency of subsequent calculators/subgraphs, e.g. less power
```

Second step, the output packets in the "tracked_detections" hold Detection proto vectors.
You need to do something like
```
processor.addPacketCallback("tracked_detections", (packet) -> { List<DetectionProto.Detection> detections = PacketGetter.getProtoVector(packet, DetectionProto.Detection.parser()); ... });
```

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by pianyun** [comment]
@WildSpirit007 ,  Have you figured out the issue? I also faced this crash.
@jiuqiant , even if i output_stream: "tracked_detections" in mediapipe/graphs/tracking/object_detection_tracking_mobile_gpu.pbtxt. It still crashed.

Any idea to solve this issue? Many thanks in advance.

**Comment by WildSpirit007** [comment]
@pianyun I followed exactly what @jiuqiant suggested, and worked without a crash.

**Comment by pianyun** [comment]
It works. My fault. I used PacketGetter.getProtoBytes. Should use PacketGetter.getProtoVector.

Thank you very much. @WildSpirit007 @jiuqiant
