### ISSUE TITLE
Android: Issues with creating a basic hand tracking app without annotation overlay

### ISSUE THREAD

**Issue by harsha-main** [google/mediapipe#827]
I've tried to follow the documentation as closely as possible, but I am not able to run an application with hand tracking without the annotations. 
I tried generating the aar file and the assets (three files as suggested), set the right BINARY_GRAPH_NAME and OUTPUT_LANDMARKS_STREAM_NAME variables in the activity, but still I get a blank screen that does nothing.

One of the iOS samples provided for Mediapipe actually has a button that disables annotation during run time. I don't find any similar method for android version though. Such methods would be nice improvements to this framework.
 
So it would help if you could provide the right steps to guide us in making various versions of the framework to be used in Android.

Thank you.

**Comment by mmm2016** [comment]
You can see the example BUILD file，Implemented on Android：https://github.com/mmm2016/mediapipemultihandstrackingapp

**Comment by harsha-main** [comment]
@mmm2016 I've checked out the official documentation on the instructions for commands to generate required files. 
I couldn't get it working though. 
Are you saying that you were able to create your own .aar file that works for you in the expected way?

**Comment by mmm2016** [comment]
> @ mmm2016我已经查看了有关说明以生成所需文件的命令的官方文档。
> 我不能使它工作。
> 您是说您能够创建自己的.aar文件，该文件以预期的方式为您工作吗？

Yes

**Comment by mmm2016** [comment]
> @mmm2016 I've checked out the official documentation on the instructions for commands to generate required files.
> I couldn't get it working though.
> Are you saying that you were able to create your own .aar file that works for you in the expected way?

Yes

**Comment by eknight7** [comment]
@harsha-main Is this issue resolved?

**Comment by harsha-main** [comment]
> @harsha-main Is this issue resolved?

I'm still unable to figure out how to remove the annotations.
Any direct help would be appreciated

**Comment by shivammaindola** [comment]
I'm also facing the same problem. Please provide us the solution.

**Comment by eknight7** [comment]
Hi, Apologies for the delayed response.

You should be able to remove the AnnotationOverlayCalculator in the graph to avoid getting any annotation overlay in the output. A similar issue was discussed here: https://github.com/google/mediapipe/issues/943

Closing this issue for now. Please feel free to re-open if the question is still relevant. Thank you.
