### ISSUE TITLE
Facemesh TfLite model giving out of bound feature points in the static image

### ISSUE THREAD

**Issue by shashank-yadav** [google/mediapipe#829]
Hi, I tried using tflite model given [here](https://github.com/google/mediapipe/blob/master/mediapipe/models/face_landmark.tflite) to get landmarks on a static image. Even though the image is 192x192, I'm getting landmark locations over 200 along width and height. Are those two supposed to be in different coordinate systems?

**Comment by mgyong** [comment]
Are you using the Facemesh example or just the TFlite file? The output of the Facemesh TFlite model is Normalized landmarks with value 0 to 1 of the input image width or input image height https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark_cpu.pbtxt#L129

**Comment by aashishwaikar** [comment]
Hi,
I am also facing the same issue, I ran the model: face_landmark.tflite on a static image using tflite.Interpreter(), but the model seems to give out-of-bounds mesh points and very distorted meshes. Can you please clarify if some transformation is needed?
This is what I've done:-

import numpy as np
import tensorflow as tf
import tflite_runtime.interpreter as tflite
import matplotlib.pyplot as plt
import cv2

# Load TFLite model and allocate tensors.
interpreter = tflite.Interpreter(model_path="face_landmark.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test model on random input data.
input_shape = input_details[0]['shape']
img = cv2.imread("test.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = cv2.resize(img, (192,192))
img1=np.empty((1,192,192,3))
img1[0,:,:,:]=img
img=img1

input_data = np.array(img, dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()
detections = interpreter.get_tensor(output_details[0]['index'])

x = [detections[0,0,0,i] for i in range(0,1404,3)]
y = [detections[0,0,0,i] for i in range(1,1404,3)]

img=np.reshape(img,(192,192,3))
img=img.astype(int)

plt.imshow(img, zorder=1)
plt.scatter(x, y, zorder=2, s=4.0)
plt.show()

**Comment by nitin26gupta** [comment]
Hi Aashish, 
Were you able to fix this issue?
I am stuck as well here, if you could provide any help.

**Comment by ahmedAlmasri** [comment]
+1

**Comment by AryanSethi** [comment]
anyone found a solution ? :(

**Comment by midhulavijayan** [comment]
Hi, can anyone suggest image processing pipeline for facial landmark detection?. I have loaded "facial_landmark.tflite" model and made prediction on cropped face image. But I am getting distorted mesh.

**Comment by HaoZhang-umich** [comment]
I guess normalize the input image could be helpful, but I'm not sure how to normalize it.

**Comment by sgowroji** [comment]
Hi @shashank-yadav and others,  Could you please test the above with the latest release and let us know if you still see the observation. Thanks!

**Comment by azeme1** [comment]
Hello!
The image normalization fix the landmarks prediction
input_data = np.array(img, dtype=np.float32)/255

![image](https://user-images.githubusercontent.com/7568330/154718215-5697e507-654c-43a0-948e-c6d1721a8741.png)
