### ISSUE TITLE
avc: denied { read } for name="libdualrendering.so"

### ISSUE THREAD

**Issue by esteimle** [google/mediapipe#83]
I was able to run this successfully on a pixel, but when I went to run it on our own Android 8.1 device it just white screened.  Looking in the logs this caught my eye:

avc: denied { read } for name="libdualrendering.so"

But I can't find a think on that library.  Does anyone know what this is?

Also I saw this error, but I think it was when I tried to resume:

09-04 20:47:32.851 23850 23850 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.google.mediapipe.apps.handtrackinggpu/com.google.mediapipe.apps.handtrackinggpu.MainActivity}: java.lang.IllegalArgumentException: No supported surface combination is found for camera device - Id : null.  May be attempting to bind too many use cases.

**My log results for adb logcat | grep trackinggpu > log.txt**

09-04 20:47:32.566  1200 26751 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x10000000 cmp=com.google.mediapipe.apps.handtrackinggpu/.MainActivity} from uid 10065
09-04 20:47:32.579  1200 26751 D ActivityTrigger: activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{cd092bf com.google.mediapipe.apps.handtrackinggpu}
09-04 20:47:32.579  1200 26751 E ActivityTrigger: activityStartTrigger: not whiteListedcom.google.mediapipe.apps.handtrackinggpu/com.google.mediapipe.apps.handtrackinggpu.MainActivity/0
09-04 20:47:32.580  1200 26751 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{cd092bf com.google.mediapipe.apps.handtrackinggpu} is now in focus and seems to be in full-screen mode
09-04 20:47:32.580  1200 26751 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.google.mediapipe.apps.handtrackinggpu/com.google.mediapipe.apps.handtrackinggpu.MainActivity/0
09-04 20:47:32.588  1200 26751 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{cd092bf com.google.mediapipe.apps.handtrackinggpu} is now in focus and seems to be in full-screen mode
09-04 20:47:32.588  1200 26751 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.google.mediapipe.apps.handtrackinggpu/com.google.mediapipe.apps.handtrackinggpu.MainActivity/0
09-04 20:47:32.601  1200 26751 I ActivityManager: Start proc 23850:com.google.mediapipe.apps.handtrackinggpu/u0a97 for activity com.google.mediapipe.apps.handtrackinggpu/.MainActivity
09-04 20:47:32.689 23850 23850 I handtrackinggpu: type=1400 audit(0.0:17222): avc: denied { open } for path="/dev/__properties__/u:object_r:camera_prop:s0" dev="tmpfs" ino=14487 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=1
09-04 20:47:32.689 23850 23850 I handtrackinggpu: type=1400 audit(0.0:17223): avc: denied { getattr } for path="/dev/__properties__/u:object_r:camera_prop:s0" dev="tmpfs" ino=14487 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=1
09-04 20:47:32.783 23850 23850 I zygote64:   at void com.google.mediapipe.apps.handtrackinggpu.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:74)
09-04 20:47:32.783 23850 23850 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.google.mediapipe.apps.handtrackinggpu-u6rNCXLCVWXv44bEmqiwYg==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.mediapipe.apps.handtrackinggpu-u6rNCXLCVWXv44bEmqiwYg==/lib/arm64, /data/app/com.google.mediapipe.apps.handtrackinggpu-u6rNCXLCVWXv44bEmqiwYg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
09-04 20:47:32.784 23850 23850 I zygote64:   at void com.google.mediapipe.apps.handtrackinggpu.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:74)
09-04 20:47:32.784 23850 23850 I zygote64:   at void com.google.mediapipe.apps.handtrackinggpu.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:74)
09-04 20:47:32.784 23850 23850 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.google.mediapipe.apps.handtrackinggpu-u6rNCXLCVWXv44bEmqiwYg==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.mediapipe.apps.handtrackinggpu-u6rNCXLCVWXv44bEmqiwYg==/lib/arm64, /data/app/com.google.mediapipe.apps.handtrackinggpu-u6rNCXLCVWXv44bEmqiwYg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
09-04 20:47:32.784 23850 23850 I zygote64:   at void com.google.mediapipe.apps.handtrackinggpu.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:74)
09-04 20:47:32.784 23850 23850 I zygote64:   at void com.google.mediapipe.apps.handtrackinggpu.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:74)
09-04 20:47:32.784 23850 23850 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.google.mediapipe.apps.handtrackinggpu-u6rNCXLCVWXv44bEmqiwYg==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.mediapipe.apps.handtrackinggpu-u6rNCXLCVWXv44bEmqiwYg==/lib/arm64, /data/app/com.google.mediapipe.apps.handtrackinggpu-u6rNCXLCVWXv44bEmqiwYg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
09-04 20:47:32.784 23850 23850 I zygote64:   at void com.google.mediapipe.apps.handtrackinggpu.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:74)
09-04 20:47:32.809 23850 23850 I handtrackinggpu: type=1400 audit(0.0:17224): avc: denied { read } for name="libdualrendering.so" dev="mmcblk0p16" ino=1630 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=1
09-04 20:47:32.827 23850 23850 I com.google.mediapipe.apps.handtrackinggpu: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
09-04 20:47:32.851 23850 23850 E AndroidRuntime: Process: com.google.mediapipe.apps.handtrackinggpu, PID: 23850
09-04 20:47:32.851 23850 23850 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.google.mediapipe.apps.handtrackinggpu/com.google.mediapipe.apps.handtrackinggpu.MainActivity}: java.lang.IllegalArgumentException: No supported surface combination is found for camera device - Id : null.  May be attempting to bind too many use cases.
09-04 20:47:32.851 23850 23850 E AndroidRuntime: 	at com.google.mediapipe.apps.handtrackinggpu.MainActivity.startCamera(MainActivity.java:165)
09-04 20:47:32.851 23850 23850 E AndroidRuntime: 	at com.google.mediapipe.apps.handtrackinggpu.MainActivity.onResume(MainActivity.java:103)
09-04 20:47:32.854  1200  2058 W ActivityManager:   Force finishing activity com.google.mediapipe.apps.handtrackinggpu/.MainActivity
09-04 20:47:32.855  1200  2058 I WindowManager: Failed to capture screenshot of Token{8eef0ee ActivityRecord{9e52e69 u0 com.google.mediapipe.apps.handtrackinggpu/.MainActivity t45 f}} appWin=Window{e06db87 u0 Splash Screen com.google.mediapipe.apps.handtrackinggpu} drawState=1
09-04 20:47:32.857  1200  1216 I ActivityManager: Showing crash dialog for package com.google.mediapipe.apps.handtrackinggpu u0
09-04 20:47:32.894  1200  1253 I WindowManager: Screen frozen for +291ms due to Window{e06db87 u0 Splash Screen com.google.mediapipe.apps.handtrackinggpu}
09-04 20:47:33.355  1200  1215 W ActivityManager: Activity pause timeout for ActivityRecord{9e52e69 u0 com.google.mediapipe.apps.handtrackinggpu/.MainActivity t45 f}
09-04 20:47:40.418  1200  3178 I ActivityManager: START u0 {act=android.intent.action.MAIN flg=0x10100000 cmp=com.google.mediapipe.apps.handtrackinggpu/.MainActivity} from uid 10065
09-04 20:47:40.426  1200  3178 D ActivityTrigger: activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{cd092bf com.google.mediapipe.apps.handtrackinggpu}
09-04 20:47:40.426  1200  3178 E ActivityTrigger: activityStartTrigger: not whiteListedcom.google.mediapipe.apps.handtrackinggpu/com.google.mediapipe.apps.handtrackinggpu.MainActivity/0
09-04 20:47:40.431  1200  3178 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{cd092bf com.google.mediapipe.apps.handtrackinggpu} is now in focus and seems to be in full-screen mode
09-04 20:47:40.431  1200  3178 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.google.mediapipe.apps.handtrackinggpu/com.google.mediapipe.apps.handtrackinggpu.MainActivity/0
09-04 20:47:40.446  1200  1551 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{cd092bf com.google.mediapipe.apps.handtrackinggpu} is now in focus and seems to be in full-screen mode
09-04 20:47:40.446  1200  1551 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.google.mediapipe.apps.handtrackinggpu/com.google.mediapipe.apps.handtrackinggpu.MainActivity/0
09-04 20:47:43.633  1200  1215 W ActivityManager: Activity destroy timeout for ActivityRecord{9e52e69 u0 com.google.mediapipe.apps.handtrackinggpu/.MainActivity t45 f}
09-04 20:47:45.054  1200  1215 W ActivityManager: Activity pause timeout for ActivityRecord{f416bca u0 com.google.mediapipe.apps.handtrackinggpu/.MainActivity t45}

**Comment by mcclanahoochie** [comment]
what device is this? what camera does it have? does it have multiple cameras? by default the example uses the [front facing camera](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/MainActivity.java#L40) (as opposed to the default rear one), maybe try switching to the back camera?

**Comment by esteimle** [comment]
Hi,
This is a device that I built, it has three cameras 0, 1, 2 and it's based of the Qualcomm XR1 chipset.

**Comment by mcclanahoochie** [comment]
Did you try running with a different camera select?
`CameraHelper.CameraFacing.FRONT -->  CameraHelper.CameraFacing.BACK`

This also may be a limitation of the [CameraX ](https://developer.android.com/reference/androidx/camera/core/CameraX) used to init the camera

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
