### ISSUE TITLE
How to access raw camera frames along with landmarks

### ISSUE THREAD

**Issue by AlexYiningLiu** [google/mediapipe#831]
I need Mediapipe to access the camera in order to get me the hand landmarks, but I also need to have the raw frames myself to modify them using the information I receive from Mediapipe's handtracking pipeline. I am looking at the mediapipemultihandtrackingapp AAR found here:
https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example
and in the MainActivity I simply can't find anyway for me to actually receive the raw camera frames. Mediapipe's calculators simply send me the land mark packets but no camera frames, as seen here:
```
processor.addPacketCallback(
                OUTPUT_LANDMARKS_STREAM_NAME,
                (packet) -> {
                    Log.d(TAG, "Received multi-hand landmarks packet.");
                    List<NormalizedLandmarkList> multiHandLandmarks =
                            PacketGetter.getProtoVector(packet, NormalizedLandmarkList.parser());
```
Is there a way for me to access the raw frames from mediapipe so I can perform further processing in them? Thanks.

**Comment by Cubbee** [comment]
Hello, you can add a packet callback to receive a frame from MediaPipe.

I've found the easiest way to do it is to use `ImageFrameToGpuBufferCalculator` to convert GPU image to ImageFrame and then `val image = AndroidPacketGetter.getBitmapFromRgba(packet)` in the packet callback to receive a bitmap.

**Comment by AlexYiningLiu** [comment]
Thanks for the reply. Is it possible for you to send the section of code that you used to perform the GPU image conversion using said calculator? Thanks for your help. Appreciate it.

**Comment by AlexYiningLiu** [comment]
> Hello, you can add a packet callback to receive a frame from MediaPipe.
> 
> I've found the easiest way to do it is to use `GpuBufferToImageFrameCalculator` to convert GPU image to ImageFrame and then `val image = AndroidPacketGetter.getBitmapFromRgba(packet)` in the packet callback to receive a bitmap.

Thanks for the reply. Is it possible for you to send the section of code that you used to perform the GPU image conversion using said calculator? Thanks for your help. Appreciate it.

**Comment by Cubbee** [comment]
You need to add the converter to the graph (don't forget to add the needed calculator to the graph BUILD file if it's not there):

```
node {
   calculator: "GpuBufferToImageFrameCalculator"
   input_stream: "transformed_input_video"
   output_stream: "transformed_image_cpu"
 }

```

And sample code for the callback (it's Kotlin):

```
processor.addPacketCallback(
    "transformed_image_cpu"
) { packet ->
    println("Received image with ts: ${packet.timestamp}")
    val image = AndroidPacketGetter.getBitmapFromRgba(packet)
}
```

**Comment by AlexYiningLiu** [comment]
> You need to add the converter to the graph (don't forget to add the needed calculator to the graph BUILD file if it's not there):
> 
> ```
> node {
>    calculator: "GpuBufferToImageFrameCalculator"
>    input_stream: "transformed_input_video"
>    output_stream: "transformed_image_cpu"
>  }
> ```
> 
> And sample code for the callback (it's Kotlin):
> 
> ```
> processor.addPacketCallback(
>     "transformed_image_cpu"
> ) { packet ->
>     println("Received image with ts: ${packet.timestamp}")
>     val image = AndroidPacketGetter.getBitmapFromRgba(packet)
> }
> ```

I am using the AAR example found in https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example, and I can't find a BUILD file for the project to add the calculator in. Any idea on how to implement it in this AAR example? 

![image](https://user-images.githubusercontent.com/46139686/85303671-cb69b880-b478-11ea-9f7d-8423ee1301a9.png)

**Comment by AlexYiningLiu** [comment]
> You need to add the converter to the graph (don't forget to add the needed calculator to the graph BUILD file if it's not there):
> 
> ```
> node {
>    calculator: "GpuBufferToImageFrameCalculator"
>    input_stream: "transformed_input_video"
>    output_stream: "transformed_image_cpu"
>  }
> ```
> 
> And sample code for the callback (it's Kotlin):
> 
> ```
> processor.addPacketCallback(
>     "transformed_image_cpu"
> ) { packet ->
>     println("Received image with ts: ${packet.timestamp}")
>     val image = AndroidPacketGetter.getBitmapFromRgba(packet)
> }
> ```

The multi_hand_tracking_mobile.pbtxt graph is already outputting an output_stream of the camera frames with the annotations overlayed on top. Can I add another output to the graph? I added the node you mentioned and the graph now looks like this. 
![image](https://user-images.githubusercontent.com/46139686/85310085-901fb780-b481-11ea-8e2b-f13e3d37ef4d.png)

**Comment by AlexYiningLiu** [comment]
> You need to add the converter to the graph (don't forget to add the needed calculator to the graph BUILD file if it's not there):
> 
> ```
> node {
>    calculator: "GpuBufferToImageFrameCalculator"
>    input_stream: "transformed_input_video"
>    output_stream: "transformed_image_cpu"
>  }
> ```
> 
> And sample code for the callback (it's Kotlin):
> 
> ```
> processor.addPacketCallback(
>     "transformed_image_cpu"
> ) { packet ->
>     println("Received image with ts: ${packet.timestamp}")
>     val image = AndroidPacketGetter.getBitmapFromRgba(packet)
> }
> ```

I added the node to the graph multi_hand_tracking_mobile.pbtxt and the graph now looks as below: 
![image](https://user-images.githubusercontent.com/46139686/85310998-ba25a980-b482-11ea-9c22-7f3ad6674b91.png)

How do I convert the pbtxt file to binarypb so I can put it inside the asset folder of my AAR project?

**Comment by AlexYiningLiu** [comment]
> You need to add the converter to the graph (don't forget to add the needed calculator to the graph BUILD file if it's not there):
> 
> ```
> node {
>    calculator: "GpuBufferToImageFrameCalculator"
>    input_stream: "transformed_input_video"
>    output_stream: "transformed_image_cpu"
>  }
> ```
> 
> And sample code for the callback (it's Kotlin):
> 
> ```
> processor.addPacketCallback(
>     "transformed_image_cpu"
> ) { packet ->
>     println("Received image with ts: ${packet.timestamp}")
>     val image = AndroidPacketGetter.getBitmapFromRgba(packet)
> }
> ```

When I add the callback 
```
processor.addPacketCallback(
    "transformed_image_cpu"
) { packet ->
    println("Received image with ts: ${packet.timestamp}")
    val image = AndroidPacketGetter.getBitmapFromRgba(packet)
}
```
into my MainActivity alongside the landmark packet callback, I receive the following fatal error at the beginning of my app's start up:
```
2020-06-22 14:50:38.044 20076-20176/com.example.mediapipemultihandstrackingapp A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20176 (Thread-5), pid 20076 (andstrackingapp)

```
How do you avoid this error? I think the callback receiving raw image frames is too CPU intensive?

**Comment by Cubbee** [comment]
This error usually means there is something wrong with the graph. Do you see any additional error messages from MediaPipe? Do you get the error after you add the GpuBufferToImageFrameCalculator to the graph (but not adding the callback)?

I'd make sure that the graph is actually rebuilt to binarypb after you've made changes:
https://google.github.io/mediapipe/getting_started/hello_world_android.html#add-relevant-dependencies

**Comment by AlexYiningLiu** [comment]
> This error usually means there is something wrong with the graph. Do you see any additional error messages from MediaPipe? Do you get the error after you add the GpuBufferToImageFrameCalculator to the graph (but not adding the callback)?
> 
> I'd make sure that the graph is actually rebuilt to binarypb after you've made changes:
> https://google.github.io/mediapipe/getting_started/hello_world_android.html#add-relevant-dependencies

Alright I was getting that error because I wasn't using the packetcallback to listen on the output from the gpubuffertoimageframecalculator, I was just listening to the output of the entire graph itself (the output_video). I added the calculator to the graph's pbtxt file, I compiled it into binarypb, but now I'm getting the error called: no calculator gpubuffertoimageframecalculator is found. This is probably because this calculator isn't added to the BUILD file. However, I'm using the AAR example https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example, which doesn't have a BUILD file that I can modify. I believe what I need to do is to add the calculator to the BUILD file of the multihandtracking example, compile a new AAR file, then put this file into the lib folder of my mediapipe_multi_hands_tracking_aar_example app to replace the current AAR file. 
![image](https://user-images.githubusercontent.com/46139686/85586305-d1919d80-b60e-11ea-9193-c43c53369141.png)

**Comment by AlexYiningLiu** [comment]
> This error usually means there is something wrong with the graph. Do you see any additional error messages from MediaPipe? Do you get the error after you add the GpuBufferToImageFrameCalculator to the graph (but not adding the callback)?
> 
> I'd make sure that the graph is actually rebuilt to binarypb after you've made changes:
> https://google.github.io/mediapipe/getting_started/hello_world_android.html#add-relevant-dependencies

Alright I was getting that error because I wasn't using the packetcallback to listen on the output from the gpubuffertoimageframecalculator, I was just listening to the output of the entire graph itself (the output_video). I added the calculator to the graph's pbtxt file, I compiled it into binarypb, but now I'm getting the error called: no calculator gpubuffertoimageframecalculator is found. This is probably because this calculator isn't added to the BUILD file. However, I'm using the AAR example https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example, which doesn't have a BUILD file that I can modify.

**Comment by mgyong** [comment]
@Cubbee It would be great if you could share github repo of your code so that other folks can use it as reference.

**Comment by eknight7** [comment]
@AlexYiningLiu were you able to get this working?

**Comment by Cubbee** [comment]
I've modified jiuqiant`s repo to support receiving the bitmap, here is the sample: https://github.com/Cubbee/mediapipe_multi_hands_tracking_aar_example 

It works with aar built from https://github.com/Cubbee/mediapipe, you can find instructions there.

Steps to make it work:

1. From the mediapipe side, you need to add GpuBufferToImageFrameCalculator to the graph somewhere, for example `mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt`

```
node {
   calculator: "GpuBufferToImageFrameCalculator"
   input_stream: "throttled_input_video"
   output_stream: "throttled_input_video_cpu"
 }
```

2. Add this calculator to needed graph BUILD file `mediapipe/graphs/hand_tracking/BUILD`
```
cc_library(
    name = "mobile_calculators",
    deps = [
        "//mediapipe/calculators/core:constant_side_packet_calculator",
        "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/graphs/hand_tracking/subgraphs:hand_renderer_gpu",
        "//mediapipe/modules/hand_landmark:hand_landmark_tracking_gpu",
        "//mediapipe/gpu:gpu_buffer_to_image_frame_calculator",
    ],
)
```
3. Listen to the packet and decode it to bitmap
```
processor.addPacketCallback(
    "transformed_image_cpu"
) { packet ->
    println("Received image with ts: ${packet.timestamp}")
    val image = AndroidPacketGetter.getBitmapFromRgba(packet)
}
```

**Comment by midhulavijayan** [comment]
@Cubbee : Thank you so much.. its working :)

**Comment by sgowroji** [comment]
Hi @Cubbee, Thank you for adding your findings. We are closing this issue now. Please feel free to reach if any other have similar request.
