### ISSUE TITLE
Generate xcode project failed with tulsi

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#834]
![image](https://user-images.githubusercontent.com/17869361/85357360-b1e17300-b543-11ea-8965-aea107ee6c66.png)

How to pass that flag in tulsi when add package?

**Comment by weinixuehao** [comment]
```
diff --git a/src/TulsiGenerator/BazelQueryInfoExtractor.swift b/src/TulsiGenerator/BazelQueryInfoExtractor.swift
index 6ae4033..5dfef0d 100644
--- a/src/TulsiGenerator/BazelQueryInfoExtractor.swift
+++ b/src/TulsiGenerator/BazelQueryInfoExtractor.swift
@@ -159,6 +159,7 @@ final class BazelQueryInfoExtractor: QueuedLogging {
         "--order_output=no",
         "--noshow_loading_progress",
         "--noshow_progress",
+        "--experimental_repo_remote_exec",
         query
     ])
     arguments.append(contentsOf: additionalArguments)
```
Finally find the source code location to execute this command and add '--experimental_repo_remote_exec' flag into it. Running `sh build_and_run` cmd again! it works! But i do not like this way.

**Comment by sgowroji** [comment]
Glad to know you resolved from above comment. We are closing this issue now. Thanks!
