### ISSUE TITLE
bazel --host_jvm_args "-DsocksProxyHost=proxy.neusoft.com -DsocksProxyPort=8080" run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

### ISSUE THREAD

**Issue by chenti2x** [google/mediapipe#835]
I am in ubuntu(cpu)

option:
bazel --host_jvm_args "-DsocksProxyHost=proxy.neusoft.com -DsocksProxyPort=8080" run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

error:
INFO: Repository bazel_skylib instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/ctt/.cache/bazel/_bazel_ctt/1fabb8f99ae892e3c1f6b539c83c35e9/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz failed: class java.io.IOException Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authorization Required"
ERROR: An error occurred during the fetch of repository 'bazel_skylib':
   java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz] to /home/ctt/.cache/bazel/_bazel_ctt/1fabb8f99ae892e3c1f6b539c83c35e9/external/bazel_skylib/bazel_skylib-0.9.0.tar.gz: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authorization Required"
ERROR: no such package '@bazel_skylib//lib': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz] to /home/ctt/.cache/bazel/_bazel_ctt/1fabb8f99ae892e3c1f6b539c83c35e9/external/bazel_skylib/bazel_skylib-0.9.0.tar.gz: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authorization Required"
INFO: Elapsed time: 12.980s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

why???
remove --host_jvm_args "-DsocksProxyHost=proxy.neusoft.com -DsocksProxyPort=8080"
the error is same

**Comment by chenti2x** [comment]
remove --host_jvm_args "-DsocksProxyHost=proxy.neusoft.com -DsocksProxyPort=8080"
the error is same

**Comment by jiuqiant** [comment]
Hi, it's a Bazel build system question related to your proxy setting. I feel sorry that MediaPipe owners don't have a good answer for this as well. You can take a look at https://github.com/bazelbuild/bazel/issues/5185 and https://github.com/bazelbuild/bazel/issues/6196 to see if there is an solution for this. You may also file an issue to the Bazel project: https://github.com/bazelbuild/bazel.

**Comment by chenti2x** [comment]
thanks
