### ISSUE TITLE
Mediapipe iOS hand tracking "flickers" on iPhone X & lower devices

### ISSUE THREAD

**Issue by Saltb0xApps** [google/mediapipe#837]
When I run the hand tracker in real time on 1280x720 AVCaptureSession, devices below iPhone X start resetting detection every two or three seconds causing a noticeable flicker. 

I've attached a screen recording to show this issue below - [https://photos.app.goo.gl/wpv6Vw8eaAF55hQBA](https://photos.app.goo.gl/wpv6Vw8eaAF55hQBA)

This could be due to the following reasons -
1. Low RAM scenarios.
2. Frames being dropped by camera due to intensive processing.

This does not happen in the sample application, but if I do additional processing like applying CoreImage filters on top of the camera, the issue happens almost always.

This issue happens on devices below iPhone X. It works perfectly on iPhone XS, iPhone 11 & 11 Pro, probably because cases 1 & 2 don't happen as often on the more powerful processor.

Is there a way I can run MediaPipe hand tracking on a lower frame rate or low RAM situations?

**Comment by sgowroji** [comment]
Hi @Saltb0xApps, Did you get a chance to go through the latest version and verify the above. Could you please test and let us know if you still see the same. And share the observations to investigate further. Thanks!
