### ISSUE TITLE
Use Mediapipe FaceMesh in Anti-Spoofing

### ISSUE THREAD

**Issue by abhianand7** [google/mediapipe#838]
I am trying to build an Anti-spoofing project based on face to prevent replay attack and print attack.

I haven't been able to find any relatable implementation for this use case and a bit confused as to how to use FaceMesh features for the same. In another attempt, I found out that the FaceMesh builds a 3d face landmarks in case of replay attack as well. So not able to find the differentiating factors which can be used to differentiate between a live person and a video of a person.

Can you please guide me in a suitable way to use FaceMesh for the same?

Any help would be really great.

**Comment by mgyong** [comment]
This question is out of scope of MediaPipe.
