### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by u2takey** [google/mediapipe#839]
Add an  `GrpcCalculator` which take packets and send to a grpc service.

**Comment by mgyong** [comment]
@u2takey We don't have plans to add this right now. We welcome your contribution
You can consider using this example of UDP calculator as a basis for GRPC calculator
https://github.com/madelinegannon/example-mediapipe-udp#2-making-a-custom-calculator
https://github.com/madelinegannon/example-mediapipe-udp/blob/0c67a0178ed08f72382a8c917e1dc10149f5df2e/mediapipe/my_pass_through_calculator.cc

**Comment by huangshenlong** [comment]
@u2takey I've started looking into this to connect mediapipe to Unity.  I think I have a rough idea of what to do but would appreciate any thoughts you have on this.  I'm using https://github.com/madelinegannon/example-mediapipe-udp#2-making-a-custom-calculator as my starting point.

**Comment by sgowroji** [comment]
Hi @u2takey, Do we  have any update on this issue w.r.t   this https://github.com/google/mediapipe/issues/839#issuecomment-649731485
