### ISSUE TITLE
How to get the hand 3d landmarks dataset?

### ISSUE THREAD

**Issue by TiramisuJ** [google/mediapipe#841]
I am trying to train my own hand gesture recognition network, and I found that your 3d landmarks dataset is different from other datasets. How can I get your training data.

**Comment by mgyong** [comment]
@TiramisuJ MediaPipe 3d landmark dataset is not released and we don't have plans to do so. Can you elaborate on what is the need for the training data?

**Comment by TiramisuJ** [comment]
> @TiramisuJ MediaPipe 3d landmark dataset is not released and we don't have plans to do so. Can you elaborate on what is the need for the training data?

OK, thank you for your reply. I'm trying to train a more lightweight gesture recognition network,  so I am looking for some suitable datasets
