### ISSUE TITLE
Warnings when running Mediapipe (for hand) on Desktop (CPU) 

### ISSUE THREAD

**Issue by xinyiw1** [google/mediapipe#842]
when I run: bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

following warnings are shown on the terminal on Mac: 
<img width="1041" alt="Screen Shot 2020-06-24 at 9 11 31 pm" src="https://user-images.githubusercontent.com/66520182/85545446-4c82a480-b65f-11ea-9607-91f89c26c577.png">

Could someone help, please?

**Comment by mgyong** [comment]
@xinyiw1 Did the hand tracking desktop example run successfully? The above is just INFO not ERROR

**Comment by xinyiw1** [comment]
Hi mgyong, 

Thank you for the comment. The hand tracking desktop example run successfully. I am just confused about why the warning says that the directory does not exist.
