### ISSUE TITLE
Segmentation fault when building an Android hand tracking gpu app on WSL

### ISSUE THREAD

**Issue by laurieban** [google/mediapipe#843]
I've followed the installation steps for building MediaPipe examples on Android. But when I tried to build the Android app for hand tracking GPU with the command I've found on the doc ( `bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu ` ), there is an error with a segmentation fault (core dumped) and the build didn't complete successfully : 

![image](https://user-images.githubusercontent.com/46228723/85556334-0873ad80-b627-11ea-9caa-d6d9855d4003.png)

Configuration :
WSL : Ubuntu 20.04 LTS
GPU : Intel UHD Graphics 600
Bazel : 2.0.0
gcc : 9.3.0
g++ : 9.3.0
opencv : 4
ffmpeg : 4.2.2
Android SDK buid-tools : 29.0.1
Android SDK platform API : 2
Android SDK platform tools : 29
Android SDK tools : 26.1.1
Android NDK : 18b
ADB : 1.0.39

**Comment by sgowroji** [comment]
Hi @laurieban, Could you please respond whether you still seeing the above error with latest release build. Thanks!
