### ISSUE TITLE
Cannot build hand_tracking_gpu model with mediapipe docker : fatal error: EGL/egl.h: No such file or directory

### ISSUE THREAD

**Issue by romainvo** [google/mediapipe#846]
I installed mediapipe using docker and could run the Hello world example, but I can't build the hand_tracking_gpu example :
Got the same error in #840 closed but no solution ?

### Command
```
root@6792a9d9e62f:/mediapipe# bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
>   mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
```

### Error log
```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = a07fc8b90c22e42962142504438a84b31567976adcd9ee1a4c9f75d2e3396f8d
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a07fc8b90c22e42962142504438a84b31567976adcd9ee1a4c9f75d2e3396f8d"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /mediapipe/WORKSPACE:33:1
WARNING: Download from https://mirror.bazel.build/github.com/Maratyszcza/FP16/archive/3c54eacb74f6f5e39077300c5564156c424d77ba.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/5cb16e7ace0fcdcab164af01620a606ba828a3be.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu (121 packages loaded, 5339 targets configured).
INFO: Found 1 target...
ERROR: /mediapipe/mediapipe/gpu/BUILD:632:1: C++ compilation of rule '//mediapipe/gpu:gl_simple_shaders' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 23 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./mediapipe/gpu/gl_simple_shaders.h:18:0,
                 from mediapipe/gpu/gl_simple_shaders.cc:15:
./mediapipe/gpu/gl_base.h:57:10: fatal error: EGL/egl.h: No such file or directory
 #include <EGL/egl.h>
          ^~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 223.631s, Critical Path: 116.58s
INFO: 346 processes: 346 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by mcclanahoochie** [comment]
Can you confirm you have followed these instructions to check for gpu support ? https://google.github.io/mediapipe/getting_started/gpu_support.html#opengl-es-setup-on-linux-desktop

Also see https://github.com/google/mediapipe/issues/148

**Comment by romainvo** [comment]
I rebuilt mediapipe image with FROM nvidia/cudagl:10.2-base-ubuntu18.04 like #150. So now I can build the hand_tracking_gpu example fine but when I run the example  got this error :
```
I20200625 17:23:16.899152  6529 demo_run_graph_main_gpu.cc:57] Initialize the calculator graph.
I20200625 17:23:16.907508  6529 demo_run_graph_main_gpu.cc:61] Initialize the GPU.
No protocol specified
No protocol specified
No protocol specified
No protocol specified
No protocol specified
E20200625 17:23:17.087481  6529 demo_run_graph_main_gpu.cc:186] Failed to run the graph: ; Unable to initialize EGLpipe/gpu/gl_context_egl.cc:157) 
```

I'm quite new to gpus so I did the followings commands both on my localhost machine and in the container with no error : 
```
$ sudo apt-get install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev
$ sudo apt-get install mesa-utils
```


I ran the container with the following : `$ docker run -it -e DISPLAY=$DISPLAY --gpus all --privileged --device=/dev/video0:/dev/video0  mediapipe
`

And in the container when I do : `$ glxinfo | grep -i opengl` , I get :
``` 
No protocol specified
Error: unable to open display :0
```
On my localhost machine it returns that : 
```
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 630 (KBL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.4
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.4
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```
although I do have Nvidia GTX 1050 TI fully working that I use with tensorflow or pytorch:

**Comment by mcclanahoochie** [comment]
to be honest, i've never personally tried gpu examples on a docker, so i can't speak from experience, but other users seem to have success. with that being said:


the 'unable to open display' error come from a few different places...

1)
try running
`$ cd /tmp/.X11-unix && for x in X*; do echo ":${x#X}"; done ; cd -
`
and see which DISPLAY variables are set; should print something like
```
:0
:20
```
then run the container with `DISPLAY=:0` or `DISPLAY=:20` (or whatever # you have)


2)
see https://github.com/google/mediapipe/issues/317 (also linked from issue #150  above)


3)
see if it's possible to start an X11 server inside the docker, via 
`startx -- :1 &  # startx X on display :1`
then run your mediapipe command
`export DISPLAY=:1 &&  <cmd> `

**Comment by AlexYiningLiu** [comment]
@romainvo I am just wondering if you have managed to solve the problem and get the example to run in docker on gpu?

**Comment by zz397fl** [comment]
does anyone have solution for this? getting it work inside a docker with gpu?

**Comment by zz397fl** [comment]
> I rebuilt mediapipe image with FROM nvidia/cudagl:10.2-base-ubuntu18.04 like #150. So now I can build the hand_tracking_gpu example fine but when I run the example got this error :
> 
> ```
> I20200625 17:23:16.899152  6529 demo_run_graph_main_gpu.cc:57] Initialize the calculator graph.
> I20200625 17:23:16.907508  6529 demo_run_graph_main_gpu.cc:61] Initialize the GPU.
> No protocol specified
> No protocol specified
> No protocol specified
> No protocol specified
> No protocol specified
> E20200625 17:23:17.087481  6529 demo_run_graph_main_gpu.cc:186] Failed to run the graph: ; Unable to initialize EGLpipe/gpu/gl_context_egl.cc:157) 
> ```
> 
> I'm quite new to gpus so I did the followings commands both on my localhost machine and in the container with no error :
> 
> ```
> $ sudo apt-get install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev
> $ sudo apt-get install mesa-utils
> ```
> 
> I ran the container with the following : `$ docker run -it -e DISPLAY=$DISPLAY --gpus all --privileged --device=/dev/video0:/dev/video0 mediapipe `
> 
> And in the container when I do : `$ glxinfo | grep -i opengl` , I get :
> 
> ```
> No protocol specified
> Error: unable to open display :0
> ```
> 
> On my localhost machine it returns that :
> 
> ```
> OpenGL vendor string: Intel
> OpenGL renderer string: Mesa Intel(R) HD Graphics 630 (KBL GT2)
> OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.4
> OpenGL core profile shading language version string: 4.60
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> OpenGL core profile extensions:
> OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.4
> OpenGL shading language version string: 4.60
> OpenGL context flags: (none)
> OpenGL profile mask: compatibility profile
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.4
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
> OpenGL ES profile extensions:
> ```
> 

I follow the same but when I print out `glxinfo | grep -i opengl` I am able to see the opengl outputs. But still, when I tried to execute the example, I got the same error:
`Failed to run the graph: ; Unable to initialize EGLpipe/gpu/gl_context_egl.cc:162`

**Comment by sgowroji** [comment]
Hi @romainvo, @zz397fl, @AlexYiningLiu  Could you please try the above with the latest release of MediaPipe. Please reach us back if you still have any error specific to the above. Thanks!

**Comment by tom-doerr** [comment]
I'm getting the same error
```
Traceback (most recent call last):
  File "./media_pipe_test.py", line 262, in <module>
    model_complexity=0, min_detection_confidence=0.5, min_tracking_confidence=0.5
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/hands.py", line 129, in __init__
    'multi_handedness'
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solution_base.py", line 262, in __init__
    self._graph.start_run(self._input_side_packets)
RuntimeError: ; Unable to initialize EGLpipe/gpu/gl_context_egl.cc:161) 
```

**Comment by mz-rainmark** [comment]
if it's just caused by missing egl library, just install that by: 
apt-get install libegl1-mesa-dev
