### ISSUE TITLE
Can't run MediaPipe examples

### ISSUE THREAD

**Issue by Meldanen** [google/mediapipe#854]
Hi,

I started a project using MediaPipe a few weeks ago and everything was fine until I had to clean install my Ubuntu (18.04) for a separate issue.

Bazel: 3.3.0
Ubuntu: 18.0.4
Android studio: 4.0
SDK: 30
NDK: 19.2.5345600

Steps:
1) The "Hello World" example (bazel run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
    mediapipe/examples/desktop/hello_world:hello_world) seems to work okay.
2) Bazel -> Sync -> Sync project with BUILD files also finishes with no errors
3) Run -> Using the edit configurations in the guide produces the error:
```
[Prepa] Installing //mediapipe/examples/android/src/java/com/google/mediapipe/apps/robotcontrol:mainapp
ERROR: <PATH>/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/robotcontrol/BUILD:62:15: Installing //mediapipe/examples/android/src/java/com/google/mediapipe/apps/robotcontrol:mainapp failed (Exit 1)
Error:
adb command: ['/home/mikroszolos/Android/Sdk/platform-tools/adb', '-s', 'c5e5add5', '-s', 'c5e5add5:tcp:5037', '-s', 'c5e5add5', '-s', 'c5e5add5:tcp:5037', 'shell', 'mkdir -p /data/local/tmp/incrementaldeployment/com.google.mediapipe.apps.robotcontrol/dex']
return code: 1
stdout: 
stderr: adb: unknown host service
----------------
Note: The failure of target @bazel_tools//tools/android:incremental_install (with exit code 1) may have been caused by the fact that it is a Python 2 program that was built in the host configuration, which uses Python 3. You can change the host configuration (for the entire build) to instead use Python 2 by setting --host_force_python=PY2.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/robotcontrol:mainapp failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.366s, Critical Path: 0.38s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully
```

I tried the -host_force_python=PY2 but maybe I added it to the wrong place which is why it didn't work. I also don't remember having to do this the first time but I might be wrong.
I would also like to add that I cloned my repository on my clean build. Perhaps there are some config files that need to be cleaned that I am not aware of?

I've also tried a clean clone of mediapipe using the handtracking example and I get the same error.

Does anyone have any suggestions? 

Thank you for your time,
Alex

**Comment by jiuqiant** [comment]
The error is `adb: unknown host service`, which means that the apk was successfully built but `adb` is not able to install the apk.
I suggest verifying your adb setting and make sure you can install the other apks as the first step. You also can build the apk by Bazel and then ask adb to install it separately. 

```
bazel build  -c opt   --config android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/robotcontrol:mainapp

adb install -r <path to your apk>
```

**Comment by Meldanen** [comment]
Hey jiuqiant,

Thank you for your suggestion.
Turns out that I had the wrong Android Studio version (4.0 instead of 3.5). Do you think it could still be related to your suggestion? I.e. 4.0 requires some extra configuration regarding installing apks? 

Thanks again,
Alex

**Comment by jiuqiant** [comment]
`adb` can be installed separately without Android Studio. So, I am not sure if the issue is related to the Android Studio version.  The best way is to use the `adb install` command to install some other apps from the terminal. It this works, then try your robotcontrol app.

**Comment by Meldanen** [comment]
Thank you again for your advice Jiuqiant.

As I am a bit constrained by deadline times I won't mess around with it at the moment (given that it is working with AS 3.5). 

Maybe sometime in the future^^

**Comment by jiuqiant** [comment]
You are welcome!
