### ISSUE TITLE
Questions about plan of releasing non optimized Objectron (3D Object Detection) models.

### ISSUE THREAD

**Issue by xiong-jie-y** [google/mediapipe#857]
Hi!

Firstly thank you for awesome framework and models!
I'm interested in using [Objectron (3D Object Detection) ](https://github.com/google/mediapipe/tree/master/mediapipe/models#objectron-3d-object-detection) model to detect 3d bounding box of other objects and I have some questions
1. Do you have a plan to release non optimized Objectron (3D Object Detection) model to train the new model?
2. Do you have a plan to release dataset or pretrained models for transfer learning?
3. Do you have a plan to release annotation tools that is mentioned in [google blog](https://ai.googleblog.com/2020/03/real-time-3d-object-detection-on-mobile.html)?

Thank you for your time! 
Jie

**Comment by ahmadyan** [comment]
1-2, Yes. Stay tuned.
3. No.

**Comment by xiong-jie-y** [comment]
@ahmadyan 
Good to hear that the model is going to be provided!
Thank you!

**Comment by ahmadyan** [comment]
re #2: https://github.com/google-research-datasets/Objectron

**Comment by jpizarrom** [comment]
Hi thank you for awesome work.

Do you have a plan to release scripts for transfer learning or training from scratch?
