### ISSUE TITLE
Video file - tracking graph won't stop

### ISSUE THREAD

**Issue by vertify-mldev1** [google/mediapipe#858]
Hello!

I have a working graph which detects face landmarks in a video and writes information for each frame to a file. It works as intended and stops after all frames have been processed.
When i try to add object tracking (to have smoother detections over time), the graph works through all frames, but won't stop after the last frame was processed.

The tracker receives 3 detections. I noticed that when i only send 1 detection to the tracker, it still freezes at the end but eventually it will stop.

Any ideas? Thank you

**Comment by mgyong** [comment]
@vertify-mldev1 pls provide your code and graph
