### ISSUE TITLE
No input video header found error from motion_analysis_calculator 

### ISSUE THREAD

**Issue by davitgoder** [google/mediapipe#860]
I am building a custom android library based on face [detection example](https://github.com/jiuqiant/mediapipe_face_detection_aar_example), I've built assets according to [instructions](https://google.github.io/mediapipe/solutions/objectron) and imported them into the project as shown [here](https://google.github.io/mediapipe/getting_started/android_archive_library.html). after I start a phone camera, the following error comes up: 

> 2020-06-30 17:55:18.540 2213-2333/com.example.myfacedetectionapp W/native: W0630 17:55:18.540931  2333 motion_analysis_calculator.cc:337] No input video header found. Downstream calculators expecting video headers are likely to fail.

that causes a crash. this error is thrown from [the motion calculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/video/motion_analysis_calculator.cc#L337)

 where to set the video header from?

here is the code that sets up the processor and sets packet parameters.

      `processor =
                new FrameProcessor(
                        this,
                        eglManager.getNativeContext(),
                        BINARY_GRAPH_NAME,
                        INPUT_VIDEO_STREAM_NAME,
                        OUTPUT_VIDEO_STREAM_NAME);
         processor
                .getVideoSurfaceOutput()
                .setFlipY(FLIP_FRAMES_VERTICALLY);

        AndroidPacketCreator packetCreator = processor.getPacketCreator();

        Map<String, Packet> inputSidePackets = new HashMap<>();

        inputSidePackets.put("obj_asset_name", packetCreator.createString(OBJ_FILE));
        inputSidePackets.put("box_asset_name", packetCreator.createString(BOX_FILE));
        inputSidePackets.put("obj_texture", packetCreator.createRgbaImageFrame(objTexture));
        inputSidePackets.put("box_texture", packetCreator.createRgbaImageFrame(boxTexture));
        processor.setInputSidePackets(inputSidePackets);`

**Comment by jianingwei** [comment]
Could you share your MediaPipe graph?

**Comment by jianingwei** [comment]
By the way, the message you quoted is a warning message, not an error. It shouldn't cause the crash.

**Comment by pbassut** [comment]
I'm having the same problem. It just exists on OSX.
It seems it's going to startup the camera(the led lights up) but then it exits.

Any additional steps we need to do on OSX?
