### ISSUE TITLE
bazel build helloworld example failed

### ISSUE THREAD

**Issue by Chandler-Shuyu-Xie** [google/mediapipe#869]
```
INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  /home/shuyu/.cache/bazel/_bazel_shuyu/9307bf48023188c8597eb1bdc1ccac63/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/9307bf48023188c8597eb1bdc1ccac63/external/org_tensorflow/third_party/py/python_configure.bzl", line 208
		get_python_bin(repository_ctx)
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/9307bf48023188c8597eb1bdc1ccac63/external/org_tensorflow/third_party/remote_config/common.bzl", line 44, in get_python_bin
		which(repository_ctx, "python")
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/9307bf48023188c8597eb1bdc1ccac63/external/org_tensorflow/third_party/remote_config/common.bzl", line 29, in which
		execute(repository_ctx, <1 more arguments>)
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/9307bf48023188c8597eb1bdc1ccac63/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed

ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Traceback (most recent call last):
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/9307bf48023188c8597eb1bdc1ccac63/external/org_tensorflow/third_party/py/python_configure.bzl", line 208
		get_python_bin(repository_ctx)
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/9307bf48023188c8597eb1bdc1ccac63/external/org_tensorflow/third_party/remote_config/common.bzl", line 44, in get_python_bin
		which(repository_ctx, "python")
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/9307bf48023188c8597eb1bdc1ccac63/external/org_tensorflow/third_party/remote_config/common.bzl", line 29, in which
		execute(repository_ctx, <1 more arguments>)
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/9307bf48023188c8597eb1bdc1ccac63/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed

INFO: Elapsed time: 8.080s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded, 11 targets configur\
FAILED: Build did NOT complete successfully (11 packages loaded, 11 targets configur\
ed)

```
os: ubuntu 18.04 LTS server
python version: 3.6.9
bazel 3.3.1

**Comment by zhang-b-x** [comment]
my helloworld example error is:
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (52 packages loaded, 1244 targets configured).
INFO: Found 1 target...
ERROR: /home/slam/MediaPipe/mediapipe/mediapipe/framework/deps/BUILD:194:11: C++ compilation of rule '//mediapipe/framework/deps:registration_token' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 18 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
gcc: error: unrecognized command line option '-std=c++14'
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.096s, Critical Path: 0.97s
INFO: 20 processes: 20 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by Chandler-Shuyu-Xie** [comment]
> my helloworld example error is:
> INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (52 packages loaded, 1244 targets configured).
> INFO: Found 1 target...
> ERROR: /home/slam/MediaPipe/mediapipe/mediapipe/framework/deps/BUILD:194:11: C++ compilation of rule '//mediapipe/framework/deps:registration_token' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 18 argument(s) skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox
> gcc: error: unrecognized command line option '-std=c++14'
> Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 3.096s, Critical Path: 0.97s
> INFO: 20 processes: 20 linux-sandbox.
> FAILED: Build did NOT complete successfully
> FAILED: Build did NOT complete successfully

Do you check your g++ version? There is a known issue with gcc and g++ version 6.3 and 7.3

**Comment by zhang-b-x** [comment]
我已经解决我的问题了，主要是gcc版本太低了，我改用了gcc-7 主要步骤如下：
1.1、sudo apt install gcc-6
       sudo apt install g++-6
1.2 删除原来的软链接
 cd /usr/bin
 sudo rm gcc
1.3 建立新的软链接
sudo ln -s gcc-6 gcc
# 查看现在的gcc版本
gcc --version
2.0 对g++进行同样的操作
sudo rm g++
sudo ln -s g++-6 g++
g++ --version

3、bazel clean --expunge
4、bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/hello_world:hello_world
