### ISSUE TITLE
[Exynos/Mali] Demo apk for handtracking crashes on Samsung Galaxy devices.

### ISSUE THREAD

**Issue by hizzlehoff** [google/mediapipe#87]

**Comment by mcclanahoochie** [comment]
not much description here, but my guess this could be similar to https://github.com/google/mediapipe/issues/41 ? 
are you seeing same error ?

**Comment by hizzlehoff** [comment]
The device was a galaxy S7 and the app shows a camera feed for a brief moment then crashes. I do not have the device hooked up to anything that could provide a log at the moment.

**Comment by lqz** [comment]
for Huawei phone the same problem.

**Comment by mgyong** [comment]
Related to #41 
Closing this as it is related to TF bug

**Comment by chuoling** [comment]
We (MediaPipe) will follow up with TensorFlow team and provide an update in #41.

**Comment by mgyong** [comment]
@lqz @hizzlehoff Fixed bug in [v0.6.5 release](https://github.com/google/mediapipe/releases/tag/v0.6.5). Pls check out v0.6.5 and let us know if this release fixed the issue
