### ISSUE TITLE
ifacelandmarkfrontcpu__facelandmarkcpu__landmark_tensors]" failed: ; (input.size())>=(max_range_end_)alculators/core/split_vector_calculator.h:143

### ISSUE THREAD

**Issue by chenti2x** [google/mediapipe#871]
**I use my own face landmark model to replace the example  model(face_landmark.tflite).**
**I am in ubuntu(cpu)**

**1.build:**
    bazel build -c dbg mediapipe/examples/desktop/face_mesh:face_mesh_cpu --define MEDIAPIPE_DISABLE_GPU=1

    **Build completed successfully.**

**2.run:**
    GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_mesh/face_mesh_cpu --calculator_graph_config_file=mediapipe/graphs/face_mesh/face_mesh_desktop_live.pbtxt

**3.I get:**

input_stream: "input_video"
output_stream: "output_video"

output_stream: "multi_face_landmarks"
profiler_config {
  enable_profiler: true
  trace_enabled: true
  trace_log_count: 5
}

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:num_faces"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet { int_value: 1 }
    }
  }
}

node {
  calculator: "FaceLandmarkFrontCpu"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "NUM_FACES:num_faces"
  output_stream: "LANDMARKS:multi_face_landmarks"
  output_stream: "ROIS_FROM_LANDMARKS:face_rects_from_landmarks"
  output_stream: "DETECTIONS:face_detections"
  output_stream: "ROIS_FROM_DETECTIONS:face_rects_from_detections"
}

node {
  calculator: "FaceRendererCpu"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "LANDMARKS:multi_face_landmarks"
  input_stream: "NORM_RECTS:face_rects_from_landmarks"
  input_stream: "DETECTIONS:face_detections"
  output_stream: "IMAGE:output_video"
}
I20200703 16:16:41.949096 28621 demo_run_graph_main.cc:53] Initialize the calculator graph.
I20200703 16:16:41.962146 28621 demo_run_graph_main.cc:57] Initialize the camera or load the video.
I20200703 16:16:42.898890 28621 demo_run_graph_main.cc:78] Start running the calculator graph.
I20200703 16:16:42.906581 28621 demo_run_graph_main.cc:83] Start grabbing and processing frames.
INFO: Initialized TensorFlow Lite runtime.
I20200703 16:16:43.406764 28623 graph_profiler.cc:587] trace_log_path: /tmp/mediapipe_trace_
I20200703 16:16:43.906829 28623 graph_profiler.cc:587] trace_log_path: /tmp/mediapipe_trace_
I20200703 16:16:44.406908 28623 graph_profiler.cc:587] trace_log_path: /tmp/mediapipe_trace_
I20200703 16:16:44.906970 28623 graph_profiler.cc:587] trace_log_path: /tmp/mediapipe_trace_
I20200703 16:16:44.948405 28621 demo_run_graph_main.cc:135] Shutting down.
I20200703 16:16:44.948465 28621 graph_profiler.cc:587] trace_log_path: /tmp/mediapipe_trace_
I20200703 16:16:44.954437 28621 graph_profiler.cc:587] trace_log_path: /tmp/mediapipe_trace_
E20200703 16:16:45.409638 28621 demo_run_graph_main.cc:146] Failed to run the graph: CalculatorGraph::Run() failed in Run: 
**Calculator::Process() for node "[facelandmarkfrontcpu__facelandmarkcpu__SplitTfLiteTensorVectorCalculator, SplitTfLiteTensorVectorCalculator with output stream: facelandmarkfrontcpu__facelandmarkcpu__landmark_tensors]" failed: ; (input.size())>=(max_range_end_)alculators/core/split_vector_calculator.h:143)** 

**4.Can you tell me where is the problem?**
thank you very much.

**Comment by JanhaviDadhania** [comment]
I am facing the exactly same issue. @chenti2x where you able to solve it?
