### ISSUE TITLE
Errors when run hand_detection  demo on snapdragon845, modified from desktop demo

### ISSUE THREAD

**Issue by zhenxingNreal** [google/mediapipe#873]
Hi, I want to run hand detection on platform of snapdragon845, and I started from the desktop hand-tracking demo. using the following command to build for arm plarform
```
bazel build -c opt --config=android_arm64  --copt  -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 --force_pic \
  mediapipe/examples/desktop/hand_tracking:hand_detection_gpu

```
What I have modified in `mediapipe/examples/desktop/demo_run_graph_main_gpu.cc` are:
1. remove the `#include "mediapipe/framework/port/commandlineflags.h" line and flags related code ,as "gflags/gflags.h" not found when build with --config=android_arm64。Instead the hand_detection_mobile.pbtxt file path is initialized within the code.
2. replace `//mediapipe/framework/port:file_helpers` to `//mediapipe/util/android/file/base`

I have successfully built executable file, after copying the model files and hand_detection_mobile.pbtxt to my snapdragon device,and execute, The following error was reported during execution. 

```
I0703 08:51:08.656708 11657 hand_detection_main_gpu.cc:80] Initialize the calculator graph.
I0703 08:51:08.659620 11657 hand_detection_main_gpu.cc:84] Initialize the GPU.
I0703 08:51:08.693634 11657 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 4
I0703 08:51:08.696167 11666 gl_context.cc:324] GL version: 3.2 (OpenGL ES 3.2 V@378.0 (GIT@2d5c972, I8302e904d2) (Date:03/29/19))
I0703 08:51:08.696923 11657 hand_detection_main_gpu.cc:111] Start running the calculator graph.
I0703 08:51:08.697340 11657 hand_detection_main_gpu.cc:117] Start grabbing and processing frames.
AddPacketToInputStream
E0703 08:51:08.720655 11657 hand_detection_main_gpu.cc:189] Failed to run the graph: Graph has errors: 
Calculator::Open() for node "[handdetectionsubgraph__TfLiteInferenceCalculator, TfLiteInferenceCalculator with output stream: handdetectionsubgraph__detection_tensors]" failed: ; asset manager not initializedutil/android/asset_manager_util.cc:139) 

```
By the way,the same code worked When running  on linux, the building command is:
```
bazel build -c opt --copt  -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 --force_pic \                        
  mediapipe/examples/desktop/hand_tracking:hand_detection_gpu

```
I tried converting hand_detection_mobile.pbtxt file to hand_detection_mobile.pbbinary, as I found the android demo did this, and simply use this file to replace hand_detection_mobile.pbtxt, but i did not wrork.

**So, are there some points I missed ?  thanks.**

**Comment by mcclanahoochie** [comment]
Hi, the build flag you are using is compiling for ARM cpu, but also android OS. To only compile for ARM (with linux OS), try replacing the `--config=android_arm64` flag with `--cpu=aarch64` 

If your platform is indeed Android, then you will need extra code inside the `demo_run_graph_main_gpu.cc` to register the [android asset manager](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/util/android/asset_manager_util.h#L35) with the main activity's context.

**Comment by youzhenxing** [comment]
yes,the platform is android,I also found that the asset manager was not initialized in the error log,Is there any instructions that helps me go forward, I am not very familiar with Android development. thanks.

**Comment by youzhenxing** [comment]
> Hi, the build flag you are using is compiling for ARM cpu, but also android OS. To only compile for ARM (with linux OS), try replacing the `--config=android_arm64` flag with `--cpu=aarch64`
> 
> If your platform is indeed Android, then you will need extra code inside the `demo_run_graph_main_gpu.cc` to register the [android asset manager](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/util/android/asset_manager_util.h#L35) with the main activity's context.



> Hi, the build flag you are using is compiling for ARM cpu, but also android OS. To only compile for ARM (with linux OS), try replacing the `--config=android_arm64` flag with `--cpu=aarch64`
> 
> If your platform is indeed Android, then you will need extra code inside the `demo_run_graph_main_gpu.cc` to register the [android asset manager](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/util/android/asset_manager_util.h#L35) with the main activity's context.

yes,the platform is android,I also found that the asset manager was not initialized in the error log,Is there any instructions that helps me go forward, I am not very familiar with Android development. thanks.

**Comment by zhenxingNreal** [comment]
> Hi, the build flag you are using is compiling for ARM cpu, but also android OS. To only compile for ARM (with linux OS), try replacing the `--config=android_arm64` flag with `--cpu=aarch64`
> 
> If your platform is indeed Android, then you will need extra code inside the `demo_run_graph_main_gpu.cc` to register the [android asset manager](https://github.com/google/mediapipe/blob/252a5713c7996e14c9bcff2caf0b2e1afca1e6f7/mediapipe/util/android/asset_manager_util.h#L35) with the main activity's context.

yes,the platform is android,I also found that the asset manager was not initialized in the error log,Is there any instructions that helps me go forward, I am not very familiar with Android development. thanks.

**Comment by zhenxingNreal** [comment]
after registering the android asset manager, the problems have been solved. thanks.
