### ISSUE TITLE
run Custom tflite Model fails in TfLiteInferenceCalculator

### ISSUE THREAD

**Issue by forbywang** [google/mediapipe#874]
**train model by deeplapV3+ for tf2.0 and optimizar it by tensorflow_model_optimization 0.3.0
debug it and got log below:**

2020-07-03 16:01:52.416 18260-18293/? D/mediapipeDebug: Following operations are not supported by GPU delegate:
    BATCH_TO_SPACE_ND: Operation is not supported.
    EXP: Operation is not supported.
    REDUCE_MAX: Operation is not supported.
    SPACE_TO_BATCH_ND: Operation is not supported.
    SUM: Operation is not supported.
    148 operations will run on the GPU, and the remaining 90 operations will run on the CPU.
2020-07-03 16:01:52.422 18260-18293/? D/mediapipeDebug: TfLiteGpuDelegate Prepare: Only identical batch dimension is supported
2020-07-03 16:01:52.422 18260-18293/? D/mediapipeDebug: Node number 238 (TfLiteGpuDelegate) failed to prepare.
2020-07-03 16:01:52.422 18260-18293/? D/mediapipeDebug: external/org_tensorflow/tensorflow/lite/kernels/conv.cc:345 bias->type != input_type (10 != 1)
2020-07-03 16:01:52.422 18260-18293/? D/mediapipeDebug: Node number 2 (CONV_2D) failed to prepare

could anyone help me?

**Comment by jiuqiant** [comment]
The error message is `BATCH_TO_SPACE_ND: Operation is not supported. EXP: Operation is not supported. REDUCE_MAX: Operation is not supported. SPACE_TO_BATCH_ND: Operation is not supported.`. So, those ops are not supported by TFLite gpu. You need to either remove those ops from the graph or define those custom ops like we did here: https://github.com/google/mediapipe/tree/master/mediapipe/util/tflite/operations.

**Comment by forbywang** [comment]
> The error message is `BATCH_TO_SPACE_ND: Operation is not supported. EXP: Operation is not supported. REDUCE_MAX: Operation is not supported. SPACE_TO_BATCH_ND: Operation is not supported.`. So, those ops are not supported by TFLite GPU by default. You need to either remove those ops from the graph or define those custom ops like we did here: https://github.com/google/mediapipe/tree/master/mediapipe/util/tflite/operations.

i did it by your suggestion,but it does not work
i added code below:
      TfLiteRegistration * BATCH_TO_SPACE_ND = tflite::ops::builtin::Register_BATCH_TO_SPACE_ND();
      AddCustom("BATCH_TO_SPACE_ND", BATCH_TO_SPACE_ND);
and i got the same log:
  BATCH_TO_SPACE_ND: Operation is not supported.

what's wrong with my code?
