### ISSUE TITLE
[Question] Where is the saved model of KNIFT?

### ISSUE THREAD

**Issue by dinfer** [google/mediapipe#878]
This project is awesome. And I want to use some model directly in web which is not supported yet using tfjs, such as KNIFT. I can only find the tflite model file in this project. where can I find the saved model file? could you release the saved model file?

**Comment by jiuqiant** [comment]
@wzc11 will answer your question soon.

**Comment by wzc11** [comment]
Hi, we did not open source the TF saved model in MediaPipe yet. Since this tflite model is converted in float type, it has the same precision as the TF model. But we may release the TF model later with some web demo. Thanks.

**Comment by dinfer** [comment]
Thank you! I think the release of related models is very important too. we can fine-tune the model for some specific sceneries.
