### ISSUE TITLE
How to build mediapipe as standalone aar library ?

### ISSUE THREAD

**Issue by aminm2a** [google/mediapipe#88]
What is the steps to do to build mediapipe as a standalone aar library to be integrated in a project ?

**Comment by ZhangWen0301** [comment]
same problem

**Comment by lqz** [comment]
same problem

**Comment by mgyong** [comment]
We will be looking into this

**Comment by mgyong** [comment]
@aminm2a @lqz @ZhangWen0301 
Pls note in [MediaPipe v0.6.3](https://github.com/google/mediapipe/releases/tag/v0.6.3) we released support for [building AAR](https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md)

**Comment by billhung** [comment]
The instruction said to "put the following code into mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD"

But I looked in v0.6.3 linked above, and there's no aar_example in the said folder.
I don't know how to proceed, can someone comment on what I am missing?

**Comment by lqz** [comment]
> @aminm2a @lqz @ZhangWen0301
> Pls note in [MediaPipe v0.6.3](https://github.com/google/mediapipe/releases/tag/v0.6.3) we released support for [building AAR](https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md)

Can there be more help documents, such as how to use the interface？

**Comment by gordinmitya** [comment]
```bazel
load(“//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl”, “mediapipe_aar”)
mediapipe_aar(
name = “mp_object_detection_aar”,
calculators = [“//mediapipe/graphs/object_detection:mobile_calculators”],
)
```

https://medium.com/@doquocbao_91868/build-object-detection-mediapipe-aar-and-integrate-in-smart-mirror-running-on-careos-c074db846313
