### ISSUE TITLE
Failed to run the graph

### ISSUE THREAD

**Issue by Chandler-Shuyu-Xie** [google/mediapipe#883]
```
I20200706 20:52:47.199970  7767 demo_run_graph_main.cc:53] Initialize the calculator graph.
I20200706 20:52:47.202932  7767 demo_run_graph_main.cc:57] Initialize the camera or load the video.
E20200706 20:52:47.277143  7767 demo_run_graph_main.cc:146] Failed to run the graph: ; capture.isOpened()(mediapipe/examples/desktop/demo_run_graph_main.cc:65) 
```

Run hand-tracking example failed

**Comment by mcclanahoochie** [comment]
The error message says the demo cannot initialize the camera or load the video file. 

If you have a webcam, please make sure it is connected and works via other apps first.

If you are loading a video, please make sure the full path is used when running with this flag
`--input_video_path=/full/path/to/video.mp4`

**Comment by Chandler-Shuyu-Xie** [comment]
Thank you
