### ISSUE TITLE
How to use pb file conver to tflite file？

### ISSUE THREAD

**Issue by teafff** [google/mediapipe#885]
I have a saved_model.pb by training in Tensorflow Object Detection API. I can use this model in computer.
But now i want to use it in my phone, so i want to make a tflite model.
Can you give me some advises, please?

**Comment by jiuqiant** [comment]
TensorFlow can do this for you. Please take a look at https://www.tensorflow.org/lite/convert.

**Comment by teafff** [comment]
> TensorFlow can do this for you. Please take a look at https://www.tensorflow.org/lite/convert.

I use Tensorflow Object Detection API train a model, and use export_tflite_ssd_graph.py generate tflite_graph.pb and  tflite_graph.pbtxt.

then I use this command: 
      bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=/home/wy/train/tflite_graph.pb

I get the parameters of the model:

Found 1 possible inputs: (name=normalized_input_image_tensor, type=float(1), shape=[1,300,300,3]) 
No variables spotted.
Found 1 possible outputs: (name=TFLite_Detection_PostProcess, op=TFLite_Detection_PostProcess) 
Found 6852896 (6.85M) const parameters, 0 (0) variable parameters, and 0 control_edges
Op types used: 215 Const, 201 Identity, 35 FusedBatchNorm, 35 Relu6, 34 Conv2D, 13 DepthwiseConv2dNative, 12 BiasAdd, 12 Reshape, 2 ConcatV2, 1 Placeholder, 1 RealDiv, 1 Sigmoid, 1 Squeeze, 1 TFLite_Detection_PostProcess
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=/home/yu/train/tflite_graph.pb --show_flops --input_layer=normalized_input_image_tensor --input_layer_type=float --input_layer_shape=1,300,300,3 --output_layer=TFLite_Detection_PostProcess

Finally, I use code to generate a tflite file:

import tensorflow as tf

in_path = "/home/wy/train/tflite_graph.pb"

input_arrays = ["normalized_input_image_tensor"]
input_shapes = {"normalized_input_image_tensor" :[1, 300, 300, 3]}
output_arrays = ["TFLite_Detection_PostProcess"]

converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(in_path, input_arrays, output_arrays, input_shapes)

converter.allow_custom_ops=True

tflite_model = converter.convert()
open("/home/wy/train/zzz.tflite", "wb").write(tflite_model)

rename this tflite as ssdlite_object_detection.tflite.
I use this tflite file to replace mediapipe/models/objectdetectioncpu.tflite. And modify ssdlite_object_detection_labelmap.txt.

then i use command:
 bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu:objectdetectioncpu

finally, it generate an apk, but when i install this apk in my phone.  it could detect some objects. But i train this model is about detecting window. it doesn't work.
Can you give me some advises to solve it?

**Comment by FUBAR2077** [comment]
xD I have read your whole comment @teafff with great hopes but in the end I see that you are stuck at exact same point as me :)

Answer why this is not working is in Netron - net is looking different in the end - it has different inputs (300 instead of 320) and outputs unfortunately and I'm still trying to figure out what I can do about it:

![image](https://user-images.githubusercontent.com/4373019/171651028-70ae4b32-291d-422b-a85f-aafb558ecb7f.png)

![image](https://user-images.githubusercontent.com/4373019/171651165-86a5b7d3-e157-4999-b095-35634220c563.png)

Any tips are more than welcome
