### ISSUE TITLE
I want to use object_detection_3d_sneakers.tflite in ios app

### ISSUE THREAD

**Issue by Zulqurnain24** [google/mediapipe#888]
I want to use object_detection_3d_sneakers.tflite in ios app can someone help me out on how to achieve this or perhaps give me a sample or demo project to begin with

**Comment by alter-sachin** [comment]
were you able to do this ?

**Comment by sgowroji** [comment]
Hi @Zulqurnain24, Try [this](https://google.github.io/mediapipe/solutions/objectron.html#desktop)  and reach us, if you have any queries. Thanks!
