### ISSUE TITLE
How to tracking two hands?

### ISSUE THREAD

**Issue by SuperSaiyan30** [google/mediapipe#89]
the node "DetectionsToRectsCalculator" in hand_detection_gpu.pbtxt limit only one Rect, so the demo of handtrackinggpu.apk only track with one hand,.

if i want to track two hands, how i change the graph?

**Comment by chuoling** [comment]
We plan to release support for two hands later this month.

**Comment by SuperSaiyan30** [comment]
thanks ~ 
wait in hope

**Comment by pranay-agra** [comment]
Any updates on two hand support?

**Comment by vivi90** [comment]
@chuoling What about two hand support?

**Comment by Zireael07** [comment]
Any updates?
