### ISSUE TITLE
ffmpeg_linux.BUILD include path config incorrect

### ISSUE THREAD

**Issue by bazaha** [google/mediapipe#892]
cc_library(
    name = "libffmpeg",
    srcs = glob(
        [
            "lib/x86_64-linux-gnu/libav*.so",
        ],
    ),
    hdrs = glob(["include/x86_64-linux-gnu/libav*/*.h"]),
    includes = ["include"], # this path is incorrect, when build audio_decode module gen error. 
    ...
)
should change: 
includes = ["include"]
TO:
includes = ["include/libav*/"]

**Comment by jiuqiant** [comment]
The current ffmpeg still works on my end. Maybe we use different libav versions?
My ffmpeg version info is 4.2.2 and libav headers are organized as the following.

```
$ ffmpeg -version
ffmpeg version 4.2.2-1+build3 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9 (Debian 9.2.1-19)

$ ls /usr/include/x86_64-linux-gnu/ | grep libav
libavcodec
libavformat
libavresample
libavutil
$ ls /usr/include/x86_64-linux-gnu/libavcodec/
ac3_parser.h   avcodec.h  avfft.h    dirac.h       dxva2.h  mediacodec.h  vaapi.h  version.h       vorbis_parser.h
adts_parser.h  avdct.h    d3d11va.h  dv_profile.h  jni.h    qsv.h         vdpau.h  videotoolbox.h  xvmc.h
```

**Comment by sgowroji** [comment]
Above [comment](https://github.com/google/mediapipe/issues/892#issuecomment-655692390) answered your query we are closing this issue now. Please reach us back if you still have any relevant issue.
