### ISSUE TITLE
GateCalculator issue in face_landmark_front_cpu.pbtxt 

### ISSUE THREAD

**Issue by chenti2x** [google/mediapipe#898]
**I modify the ComputeShader (TfLiteConverterCalculator in face_landmark_gpu.pbtxt) as follows. I want to pass a grayscale image(0-255pixels) to my model(160*160). But the inference result is always wrong, could you help me aboat the problem? I work in ubuntu system with gpu.Thank you very much!**

    // Shader to convert GL Texture to Shader Storage Buffer Object (SSBO),
    // with normalization to either: [0,1] or [-1,1].
    const std::string shader_source = absl::Substitute(
        R"( #version 310 es
      layout(local_size_x = $0, local_size_y = $0) in;
      layout(binding = 0) uniform sampler2D input_texture;
      layout(std430, binding = 1) buffer Output {float elements[];} output_data;
      ivec2 width_height = ivec2($1, $2);          

      void main() {
        ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
        if (gid.x >= width_height.x || gid.y >= width_height.y) return;
        vec4 pixel = texelFetch(input_texture, gid, 0);
        int linear_index = gid.y * width_height.x + gid.x;
        pixel = pixel * 255.0;
        output_data.elements[linear_index + 0] = 0.299*pixel.x + 0.587*pixel.y + 0.114*pixel.z;                    
      })",
        /*$0=*/kWorkgroupSize, /*$1=*/input.width(), /*$2=*/input.height(),
    );
    RET_CHECK_CALL(GlShader::CompileShader(GL_COMPUTE_SHADER, shader_source,
                                           &gpu_data_out_->shader));
    RET_CHECK_CALL(GlProgram::CreateWithShader(gpu_data_out_->shader,
                                               &gpu_data_out_->program));

    // ivec4 ipixel = ivec4(pixel * 255.0);  
    // output_data.elements[linear_index + 0] = float((19595*ipixel.x + 38469*ipixel.y + 7472*ipixel.z)>> 16);                          
    return ::mediapipe::OkStatus();

**Comment by chenti2x** [comment]
when don't passes the incoming image through to trigger a new round of face detection in FaceDetectionFrontCpu, what is output_stream: "gated_image" ?is previous  image or null?


node {
calculator: "GateCalculator"
input_stream: "image"
input_stream: "DISALLOW:prev_has_enough_faces"
output_stream: "gated_image"
options: {
[mediapipe.GateCalculatorOptions.ext] {
empty_packets_as_allow: true
}
}
}

**Comment by chenti2x** [comment]
**I modify the ComputeShader (TfLiteConverterCalculator in face_landmark_gpu.pbtxt) as follows. I want to pass a grayscale image(0-255pixels) to my model(160*160). But the inference result is always wrong, could you help me aboat the problem? I work in ubuntu system with gpu.Thank you very much**

    // Shader to convert GL Texture to Shader Storage Buffer Object (SSBO),
    // with normalization to either: [0,1] or [-1,1].
    const std::string shader_source = absl::Substitute(
        R"( #version 310 es
      layout(local_size_x = $0, local_size_y = $0) in;
      layout(binding = 0) uniform sampler2D input_texture;
      layout(std430, binding = 1) buffer Output {float elements[];} output_data;
      ivec2 width_height = ivec2($1, $2);          

      void main() {
        ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
        if (gid.x >= width_height.x || gid.y >= width_height.y) return;
        vec4 pixel = texelFetch(input_texture, gid, 0);
        int linear_index = gid.y * width_height.x + gid.x;
        pixel = pixel * 255.0;
        output_data.elements[linear_index + 0] = 0.299*pixel.x + 0.587*pixel.y + 0.114*pixel.z;                    
      })",
        /*$0=*/kWorkgroupSize, /*$1=*/input.width(), /*$2=*/input.height(),
    );
    RET_CHECK_CALL(GlShader::CompileShader(GL_COMPUTE_SHADER, shader_source,
                                           &gpu_data_out_->shader));
    RET_CHECK_CALL(GlProgram::CreateWithShader(gpu_data_out_->shader,
                                               &gpu_data_out_->program));

    // ivec4 ipixel = ivec4(pixel * 255.0);  
    // output_data.elements[linear_index + 0] = float((19595*ipixel.x + 38469*ipixel.y + 7472*ipixel.z)>> 16);                          
    return ::mediapipe::OkStatus();
  }));

**Comment by mcclanahoochie** [comment]
see https://github.com/google/mediapipe/issues/978
