### ISSUE TITLE
Can't Run Hello World Example

### ISSUE THREAD

**Issue by udogukankurt** [google/mediapipe#902]
Hello, I get the same error every time although I have tried many times. I'm new to Linux. I had to install ubuntu 5 times. Although I do the loading steps one by one, I can't run the hello world example. I'm having trouble with 4th step. The error I got is as follows:
DEBUG: /home/udogukankurt/.cache/bazel/_bazel_udogukankurt/e71f33407e9b2f5fad329760ffc3211c/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /home/udogukankurt/.cache/bazel/_bazel_udogukankurt/e71f33407e9b2f5fad329760ffc3211c/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: /home/udogukankurt/.cache/bazel/_bazel_udogukankurt/e71f33407e9b2f5fad329760ffc3211c/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /home/udogukankurt/.cache/bazel/_bazel_udogukankurt/e71f33407e9b2f5fad329760ffc3211c/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
ERROR: /home/udogukankurt/mediapipe/mediapipe/framework/port/BUILD:370:1: no such package '@com_google_absl//absl/strings': The repository '@com_google_absl' could not be resolved and referenced by '//mediapipe/framework/port:status'
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: no such package '@com_google_absl//absl/strings': The repository '@com_google_absl' could not be resolved
INFO: Elapsed time: 0.114s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: mediapipe/gpu ... (2 packages)

Please help me.. I can not understand where the problem stems from. 
Thanks.

**Comment by jiuqiant** [comment]
Hi, can you show the full log and the build command you use? Seems like @com_google_absl is not properly downloaded, which results to the error '@com_google_absl' can not be resolved.
