### ISSUE TITLE
Prevent face detection bounding box from getting drawn

### ISSUE THREAD

**Issue by justaguyin2k20** [google/mediapipe#903]
Hello all,
I just started using the mediapipe library to implement face detection in my app, so please apologies in advance. So far I have been able to build an android aar and use this aar in my application with success. However I do not want the bounding box that appears over the detected face.<br/>
    I changed the **DetectionsToRenderDataCalculatorOptions->thicknes**s value in _face_detection_mobile_gpu.pbtxt_ from 4.0 to 0.0, rebuilt the graph and applied to my app with no success.<br/>
    I have tried removing the **DetectionsToRenderDataCalculatorOptions** from the **DetectionsToRenderDataCalculator** node in _face_detection_mobile_gpu.pbtxt_, rebuilt the graph and applied to my app with no success.
    I even commented out the following lines from _detections_to_render_data.cc_, rebuilt the aar, applied to my project with no success.

**_render_annotation->mutable_color()->set_r(options.color().r()); 
render_annotation->mutable_color()->set_g(options.color().g()); 
render_annotation->mutable_color()->set_b(options.color().b()); 
render_annotation->set_thickness(options.thickness());_**

I should mention that in all the cases above, the bounding box is drawn with a very thin black line (like a "default" setting), if I change the thickness and color values in the .pbtxt file, resbuild the graph and apply to my app the changes are reflected.

Is there a way to prevent the bounding box from getting drawn? Thanks

**Comment by mcclanahoochie** [comment]
Do you want to still draw the face keypoints? Or do you want to get rid of _all_ drawing?

Unfortunately there isn't currently an easy way to toggle just the face bounding box. 

I _think_ you could comment out *both* calls to [SetRectCoordinate](https://github.com/google/mediapipe/blob/5d028d923b52fd95bd49642a9a4a162f57ae260e/mediapipe/calculators/util/detections_to_render_data_calculator.cc#L330) to get rid of the rectangle.

Also untested, you could try commenting out the line
` input_stream: "render_data" `
for the `AnnotationOverlayCalculator` node (this would remove all drawings).

The main point is that the `RENDER_DATA` contains all the drawing info, so you need to find where that is set and removing it (or skipping where it is drawn in the renderer). 

BTW, the `mutable_color()->set_r/thickness` code you mention is already too late (the lines have been added, that is just properties), so if you trace backwards from there, you should find the `SetRectCoordinate` mentioned above to modify.

**Comment by justaguyin2k20** [comment]
Hello,
Thanksfor your response. You are right, there's no easy way, but I finally managed to get the bounding box not drawn by commenting out the draw statements in annotation_renderer.cc and rebuilding the aar.

My only issue now is how to correctly convert the boundingBox and other landmarks to the screen coordinates? Any tips on that?
