### ISSUE TITLE
Face pos from 468 points of facemesh

### ISSUE THREAD

**Issue by Starsky-Synlitec** [google/mediapipe#906]
How to get the position and orientation of the face from the 468 points ?
I found in arcore, that we could obtain the facemesh as a 3d object with position and orientation coordinates. But here we can get only the position of each keypoint.
How to extract the posirion and the orientarion of the mesh (as a single 3d object)?

**Comment by mgyong** [comment]
@Starsky-Synlitec Currently we support only keypoints and not position/orientation of the mesh as a 3D object. We plan to release something later in 2H 2020 for providing facemesh as a 3D object

**Comment by dosomder** [comment]
Looking forward to this feature 👍

**Comment by JsBlueCat** [comment]
> @Starsky-Synlitec Currently we support only keypoints and not position/orientation of the mesh as a 3D object. We plan to release something later in 2H 2020 for providing facemesh as a 3D object

sorry to distribute, i want to know that how can get your perdicted points from mediapipe? i mean how can we get the .obj file of points data, that represents the ploygon object?

**Comment by aarushi-mittal** [comment]
Is there any update on this feature ?

**Comment by aarushi-mittal** [comment]
> @Starsky-Synlitec Currently we support only keypoints and not position/orientation of the mesh as a 3D object. We plan to release something later in 2H 2020 for providing facemesh as a 3D object

Is there any update now ?

**Comment by sgowroji** [comment]
Please refer this for more understanding https://github.com/google/mediapipe/issues/1561#issuecomment-771027016
