### ISSUE TITLE
bazel build error on Windows

### ISSUE THREAD

**Issue by tkone2018** [google/mediapipe#91]
when i run the command:bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu,i met a error ;
ERROR: no such package '@org_tensorflow//tensorflow': Traceback (most recent call last):
        File "C:/users/78245/_bazel_78245/iovv2mkq/external/bazel_tools/tools/build_defs/repo/http.bzl", line 83
                patch(ctx)
        File "C:/users/78245/_bazel_78245/iovv2mkq/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 100, in patch  ctx.patch(patchfile, strip)
com.google.devtools.build.lib.syntax.EvalException: Error applying patch C:/users/78245/desktop/mediapipe/mediapipe-master/third_party/tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("patch" -p1 -i C:/users/78245/desktop/mediapipe/mediapipe-master/third_party/tensorflow_065c20bf79253257c87bd4614bb9a7fdef015cbb.diff): ???????????

can you help me ? thank

**Comment by jiuqiant** [comment]
Unfortunately, MediaPipe doesn't support Windows. If you are only interested in Windows, we support Windows Subsystem for Linux. You can find how to set up MediaPipe in WSL [here](https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-windows-subsystem-for-linux-wsl).
