### ISSUE TITLE
Low accuracy for BlazeFace keypoints

### ISSUE THREAD

**Issue by nlothian** [google/mediapipe#910]
If I pass upside-down faces to the BlazeFace model the bounding box works well but the keypoints are usually very incorrect. 

I'm using keypoints to fix orientation before passing to FaceMesh. I expect some error in the BlazeFace keypoints, but I rely on the eyes to nose orientation to correct the rotation but this fails. I've attached (part of) a sample image - the blue points are the eyes, yellow is the nose and green is the mouth. 

If there is an alternate approach to fixing orientation I'd be happy to try that. 

<img width="328" alt="image" src="https://user-images.githubusercontent.com/117304/87537607-0064d600-c6da-11ea-9fed-6928413be403.png">

**Comment by amazingyyc** [comment]
When re-implement, I also found BlazeFace is not good at upside-down image.
If you impelement BlazeFace on the mobile phone, you can fix this by below method:
1: Check the phone's orientation by mobile phone's gravity sensor.
2: rotate the image by phone's orientation.
3: Run BlazeFace.
4: Convert the coordiante back.

**Comment by nlothian** [comment]
Thanks @amazingyyc - yes, phone sensors can be helpful but I don't have access to them in all environments. 

I was thinking of implementing something based on facial geometry compared to the bounding box - if eye separation is less than X% of bounding box size it is probably wrong. But there are some face angles where I'm not sure this will work.

**Comment by fanzhanggoogle** [comment]
@amazingyyc is correct that model wise it is difficult to handle upside-down case since we don't explicitly train the model with such data. But it should work fine with at most 45 degrees rotation which are supported in the training with augmentation.
