### ISSUE TITLE
Build fails handtracking example eigen_archive issue

### ISSUE THREAD

**Issue by rohabimbesat** [google/mediapipe#911]
Using Windows
Bazel build label: 3.4.1
The hello world example works completely fine however the other examples do not
I ran 
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:/Users/rohab/AppData/Local/Programs/Python/Python38/python.exe" mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu`

I get the error
`ERROR: An error occurred during the fetch of repository 'eigen_archive':
   Traceback (most recent call last):
        File "C:/users/rohab/_bazel_rohab/ax23hvcl/external/org_tensorflow/third_party/repo.bzl", line 110
                _apply_patch(ctx, <1 more arguments>)
        File "C:/users/rohab/_bazel_rohab/ax23hvcl/external/org_tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "C:/users/rohab/_bazel_rohab/ax23hvcl/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/rohab/_bazel_rohab/ax23hvcl/external/eigen_archive" "-i" "C:/users/rohab/_bazel_rohab/ax23hvcl/external/org_tensorflow/third_party/eigen3/gpu_packet_math.patch"':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
ERROR: C:/users/rohab/documents/projects/mediapipe/mediapipe/mediapipe/framework/formats/BUILD:76:11: //mediapipe/framework/formats:matrix depends on @eigen_archive//:eigen in repository @eigen_archive which failed to fetch. no such package '@eigen_archive//': Traceback (most recent call last):
        File "C:/users/rohab/_bazel_rohab/ax23hvcl/external/org_tensorflow/third_party/repo.bzl", line 110
                _apply_patch(ctx, <1 more arguments>)
        File "C:/users/rohab/_bazel_rohab/ax23hvcl/external/org_tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "C:/users/rohab/_bazel_rohab/ax23hvcl/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/rohab/_bazel_rohab/ax23hvcl/external/eigen_archive" "-i" "C:/users/rohab/_bazel_rohab/ax23hvcl/external/org_tensorflow/third_party/eigen3/gpu_packet_math.patch"':
Stdout:
Stderr: /usr/bin/bash: patch: command not found
ERROR: Analysis of target '//mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu' failed; build aborted: Analysis failed
INFO: Elapsed time: 5.516s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)`

any help appreciated Thank you

**Comment by rohabimbesat** [comment]
this was displayed before the error too
`INFO: Repository eigen_archive instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule tf_http_archive defined at:
  C:/users/rohab/_bazel_rohab/ax23hvcl/external/org_tensorflow/third_party/repo.bzl:134:34: in <toplevel>
INFO: Repository 'eigen_archive' used the following cache hits instead of downloading the corresponding file.
 * Hash '2c7c0aec4271dfca6b8a7707e2112f67c4cb3bdf7c89c0e98d3fcd39707c4468' for https://storage.googleapis.com/mirror.tensorflow.org/gitlab.com/libeigen/eigen/-/archive/49f1aeb60d9f759859fce0d16aa5d1ecc7168d51/eigen-49f1aeb60d9f759859fce0d16aa5d1ecc7168d51.tar.gz
If the definition of 'eigen_archive' was updated, verify that the hashes were also updated.`

**Comment by jiuqiant** [comment]
The error seems to be `Stdout: Stderr: /usr/bin/bash: patch: command not found ERROR`, which means bazel fails to apply some patches on the eigen_archive library.

Did you modify the codebase or just use the latest version of MediaPipe as is? I am asking because a group of users report that they can't build MediaPipe on Windows with the latest version (https://github.com/google/mediapipe/issues/908).

**Comment by rohabimbesat** [comment]
yes I had to change legacy_calculator_support.h and packet.h in order for the hello world example to work on the latest MediaPipe version. 
I am on Windows, the latest MediaPipe did not work for me without the modifications,

**Comment by jiuqiant** [comment]
Could share how you modified `packet.h`?

**Comment by rohabimbesat** [comment]
in mediapipe/framework/packet.h  
I removed ` T{}.GetTypeName(), [] { return absl::make_unique<Holder<T>>(new T); }));`
replaced with `T{}.GetTypeName(), absl::make_unique<Holder<T>>));   `

**Comment by rohabimbesat** [comment]
is it best that i use an older version of mediapipe?

**Comment by jiuqiant** [comment]
> in mediapipe/framework/packet.h
> I removed ` T{}.GetTypeName(), [] { return absl::make_unique<Holder<T>>(new T); }));`
> replaced with `T{}.GetTypeName(), absl::make_unique<Holder<T>>)); `

Thanks for your reply. I did the same thing a few days ago. But, it caused another compilation error when I built the hand tracking demo. I guess it doesn't fix the actual issue.

You can use v0.7.5 (https://github.com/google/mediapipe/tree/v0.7.5) instead. That's the initial release of the Windows support.
