### ISSUE TITLE
How can we used mediapipe object tracking with own object detector?

### ISSUE THREAD

**Issue by sainisanjay** [google/mediapipe#913]
We have our own object detector which is running in Qualcomm platform(SNPE). Tensorflow Object detector model is converted into .DLC (Qualcomm format), can we integrate mediapipe object tracking with .DLC format?

**Comment by jiuqiant** [comment]
I think MediaPipe's tensorflow inference calculator only supports tensorflow models. If you need to do model inference with some other inference engine, unfortunately MediaPipe doesn't have such calculators. But, you definitely can implement a new inference calculator by yourself in C++.  Here is how we implement tensorflow inference calculator: https://github.com/google/mediapipe/blob/61bc4556af586bb3837f17187568d1345b3ee8f5/mediapipe/calculators/tensorflow/tensorflow_inference_calculator.cc
