### ISSUE TITLE
Whats mean Z coordinate ?

### ISSUE THREAD

**Issue by www516717402** [google/mediapipe#914]
Hello.
`landmark.x()`non-normlize, this value about (-70 ~ +70), I know this value is root-relate by index zeros, however this value is irregularity. such as value equal 70 Metric is millimeter or centimeter or other metric？And have you process labels by other method?
Hope your reply.

**Comment by jiuqiant** [comment]
Does this answer https://github.com/google/mediapipe/issues/742#issuecomment-639104199 help?

**Comment by www516717402** [comment]
@jiuqiant 
I'm sorry this is not the answer I want. I know #742 means. But. How to translate google-media output Z into normal value such as millimeter or centimeter ? Some paper use Z(root_relate) devide length of index 9 and 10  as output label.

**Comment by www516717402** [comment]
Already solved.

**Comment by huolianchu** [comment]
> Already solved.

Can you tell me your solution？

**Comment by zhouwei5113** [comment]
> Already solved.

could you share your solution on how to use the z-value?

**Comment by pani0815** [comment]
Please show your solution.

**Comment by prabhavnegi** [comment]
@www516717402  what is the solution can you pls share

**Comment by regainOWO** [comment]
@pani0815 @prabhavnegi 
if you want to calculate the angle at which the finger bends in 3D coordinates, may be you should use MULTI_HAND_WORLD_LANDMARKS
refer: [MULTI_HAND_WORLD_LANDMARKS](https://google.github.io/mediapipe/solutions/hands.html#multi_hand_world_landmarks)
real-world 3D coordinates in meters with the origin at the hand’s approximate geometric center.
