### ISSUE TITLE
Landscape orientation in Android Apps

### ISSUE THREAD

**Issue by rrtaylor** [google/mediapipe#915]
I am trying to run the object tracking gpu android app (with a custom model) in landscape mode but I am having the same trouble as #568. I have set the screenOrientation in the AndroidManifest.xml to "landscape". The rendered text is displaying in the correct orientation, but the displayed image is rotated 90 degrees. I tried looking into @eknight7's suggestions, but haven't found something that will work yet. 

Given that the rendered text orientation is correct but the image is wrong makes me think that the graph is capturing images from the `ExternalTextureConverter` in the wrong orientation. Any help would be appreciated! Thanks.

**Comment by rrtaylor** [comment]
With `screenOrientation`  set to "portrait" in the `AndroidManifest.xml`, `cameraHelper.isCameraRotated()` is `true`; and when `screenOrientation` is set to "landscape", `cameraHelper.isCameraRotated` is `false`. From [the comments in CameraHelper.java](https://github.com/google/mediapipe/blob/e9fbe868e55fa23aaabc31f9f847c22287062850/mediapipe/java/com/google/mediapipe/components/CameraHelper.java#L60), it sounds like the camera has the correct orientation set.

**Comment by Aiushtha** [comment]
Mark, I have the same problem. How to set up 'landscape'

**Comment by mzwtjp** [comment]
https://github.com/google/mediapipe/issues/568#issuecomment-664135536

**Comment by ttcluo** [comment]
How to set up 'landscape'
