### ISSUE TITLE
Error when command bazel run is executed

### ISSUE THREAD

**Issue by rockbass2560** [google/mediapipe#916]
I followed instructions for installing mediapipe for [ubuntu](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu). The version is 20 lts. 

But I run the last command _bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world_  I get the next error:

ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: error loading package 'mediapipe/gpu': Unable to find package for @build_bazel_rules_apple//apple:ios.bzl: The repository '@build_bazel_rules_apple' could not be resolved.
INFO: Elapsed time: 0.343s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 5 targets conf\
FAILED: Build did NOT complete successfully (1 packages loaded, 5 targets conf\
igured)
    currently loading: mediapipe/framework/tool

**Comment by rockbass2560** [comment]
I guess instructions are wrong

**Comment by sgowroji** [comment]
Hi @rockbass2560, Could you please try to build the same with the latest [instruction](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu) as mentioned in the documentation.
