### ISSUE TITLE
Running Mediapipe on GPU with OpenGL ES < 3.0

### ISSUE THREAD

**Issue by QBoulanger** [google/mediapipe#918]
Hi, 

I realised after multiple days of testing and deep googling that currently no Virtual Machine supports OpenGL ES 3+. I tested on VirtualBox and VMware Player, no one supports it. As said in [your docs](https://google.github.io/mediapipe/getting_started/gpu_support.html), "OpenGL ES 3.1 or greater is required (on Android/Linux systems) for running machine learning inference calculators and graphs." which is what interests me.

Are you aware of any way to bypass the problem ? Or is it in you plans to extend the system requirements ability to OpenGL ES < 3 ?

It surprised me that so little is said on google about it. I don't believe I am the only one to run on virtual machines ...

Thanks for your response !

**Comment by mcclanahoochie** [comment]
The requirement of GLES 3.1+ mainly comes from TFLite, and the TFLite GPU delegate for inference. That would mainly be a question for TensorFlow Lite team, also I'm not familiar of any plans to do so.

There is some work being done on improving ML inference graphs/examples on machines with only OpenGL ES 2.0 or 3.0, by supporting a mix of CPU/GPU calculators:  GPU preprocessing > CPU inference > CPU tensor post processing > GPU render.
This would be a hybrid of the current "all CPU" or "all GPU" path calculators.

This can be an option for you right now (GPU input/output + CPU inference), but you would have to design the graph for now, while a more elegant version of that is being developed by the MP team.   Just be sure to compile with [this flag](https://github.com/google/mediapipe/blob/master/mediapipe/framework/port.h#L50).

**Comment by QBoulanger** [comment]
Thank you for your response @mcclanahoochie . It makes sense. 

I hope VirtualBox or VMWare will soon be able to run with GLES 3.1+ ....

Have a great day.
