### ISSUE TITLE
Hand detection example fails to build on RPI 4B

### ISSUE THREAD

**Issue by codeNick7** [google/mediapipe#919]
Followed: https://google.github.io/mediapipe/getting_started/building_examples.html#option-1-running-on-cpu
and this: https://qiita.com/mml/items/769105522b8f2746286f
and this: https://qiita.com/PINTO/items/ecdab78dda6868221aee

Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

But getting same error for both CPU and GPU examples. Could any one help?

`ERROR: /home/pi/workspace/mediapipe/mediapipe/examples/desktop/hand_tracking/BUILD:42:10: Linking of rule '//mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/arm-opt/bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function cv::Mat::~Mat(): error: undefined reference to 'cv::fastFree(void*)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function cv::Mat::~Mat(): error: undefined reference to 'cv::Mat::deallocate()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::VideoCapture()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::open(cv::String const&)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::String::deallocate()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::isOpened() const'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoWriter::VideoWriter()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoWriter::~VideoWriter()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::~VideoCapture()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::open(int)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::String::allocate(unsigned int)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::namedWindow(cv::String const&, int)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::String::deallocate()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::set(int, double)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::set(int, double)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::set(int, double)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::operator>>(cv::Mat&)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::fastFree(void*)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoWriter::isOpened() const'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoWriter::release()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::String::allocate(unsigned int)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::flip(cv::_InputArray const&, cv::_OutputArray const&, int)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::Mat::copyTo(cv::_OutputArray const&) const'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::getTickCount()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::getTickFrequency()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoWriter::isOpened() const'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoWriter::fourcc(char, char, char, char)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::get(int) const'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoWriter::open(cv::String const&, int, double, cv::Size_<int>, bool)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::String::deallocate()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoWriter::isOpened() const'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoWriter::write(cv::Mat const&)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::fastFree(void*)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::fastFree(void*)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::String::allocate(unsigned int)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::imshow(cv::String const&, cv::_InputArray const&)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::String::deallocate()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::waitKey(int)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::Mat::deallocate()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::Mat::deallocate()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::Mat::deallocate()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::String::allocate(unsigned int)'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoWriter::~VideoWriter()'
bazel-out/arm-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main_gpu/demo_run_graph_main_gpu.o:demo_run_graph_main_gpu.cc:function RunMPPGraph(): error: undefined reference to 'cv::VideoCapture::~VideoCapture()'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_cropping_calculator/image_cropping_calculator.o:image_cropping_calculator.cc:function mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::boxPoints(cv::RotatedRect, cv::_OutputArray const&)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_cropping_calculator/image_cropping_calculator.o:image_cropping_calculator.cc:function mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::Mat::updateContinuityFlag()'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_cropping_calculator/image_cropping_calculator.o:image_cropping_calculator.cc:function mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::getPerspectiveTransform(cv::_InputArray const&, cv::_InputArray const&)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_cropping_calculator/image_cropping_calculator.o:image_cropping_calculator.cc:function mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::warpPerspective(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::Size_<int>, int, int, cv::Scalar_<double> const&)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_cropping_calculator/image_cropping_calculator.o:image_cropping_calculator.cc:function mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::Mat::copyTo(cv::_OutputArray const&) const'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::rotate(cv::_InputArray const&, cv::_OutputArray const&, int)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::flip(cv::_InputArray const&, cv::_OutputArray const&, int)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::Mat::copyTo(cv::_OutputArray const&) const'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::rotate(cv::_InputArray const&, cv::_OutputArray const&, int)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::copyMakeBorder(cv::_InputArray const&, cv::_OutputArray const&, int, int, int, int, int, cv::Scalar_<double> const&)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::getRotationMatrix2D(cv::Point_<float>, double, double)'
bazel-out/arm-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to 'cv::warpAffine(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::Size_<int>, int, int, cv::Scalar_<double> const&)'
bazel-out/arm-opt/bin/mediapipe/framework/formats/_objs/image_frame_opencv/image_frame_opencv.o:image_frame_opencv.cc:function mediapipe::formats::MatView(mediapipe::ImageFrame const*): error: undefined reference to 'cv::Mat::Mat(int, int const*, int, void*, unsigned int const*)'
bazel-out/arm-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetGpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&): error: undefined reference to 'cv::Mat::create(int, int const*, int)'
bazel-out/arm-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetGpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&): error: undefined reference to 'cv::Mat::operator=(cv::Scalar_<double> const&)'
bazel-out/arm-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetGpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&): error: undefined reference to 'cv::Mat::create(int, int const*, int)'
bazel-out/arm-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetCpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&, mediapipe::ImageFormat_Format*): error: undefined reference to 'cv::Mat::create(int, int const*, int)'
bazel-out/arm-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetCpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&, mediapipe::ImageFormat_Format*): error: undefined reference to 'cv::Mat::operator=(cv::Scalar_<double> const&)'
bazel-out/arm-opt/bin/mediapipe/calculators/util/_objs/annotation_overlay_calculator/annotation_overlay_calculator.o:annotation_overlay_calculator.cc:function mediapipe::AnnotationOverlayCalculator::CreateRenderTargetCpu(mediapipe::CalculatorContext*, std::unique_ptr<cv::Mat, std::default_delete<cv::Mat> >&, mediapipe::ImageFormat_Format*): error: undefined reference to 'cv::Mat::create(int, int const*, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::AdoptImage(cv::Mat*): error: undefined reference to 'cv::Mat::copySize(cv::Mat const&)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRoundedRectangle(cv::Mat, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int): error: undefined reference to 'cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRoundedRectangle(cv::Mat, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int): error: undefined reference to 'cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRoundedRectangle(cv::Mat, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int): error: undefined reference to 'cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRoundedRectangle(cv::Mat, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int): error: undefined reference to 'cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRoundedRectangle(cv::Mat, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int): error: undefined reference to 'cv::ellipse(cv::_InputOutputArray const&, cv::Point_<int>, cv::Size_<int>, double, double, double, cv::Scalar_<double> const&, int, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRoundedRectangle(cv::Mat, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int): error: undefined reference to 'cv::ellipse(cv::_InputOutputArray const&, cv::Point_<int>, cv::Size_<int>, double, double, double, cv::Scalar_<double> const&, int, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRoundedRectangle(cv::Mat, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int): error: undefined reference to 'cv::ellipse(cv::_InputOutputArray const&, cv::Point_<int>, cv::Size_<int>, double, double, double, cv::Scalar_<double> const&, int, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRoundedRectangle(cv::Mat, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int): error: undefined reference to 'cv::ellipse(cv::_InputOutputArray const&, cv::Point_<int>, cv::Size_<int>, double, double, double, cv::Scalar_<double> const&, int, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRectangle(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::RotatedRect::points(cv::Point_<float>*) const'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRectangle(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::rectangle(cv::Mat&, cv::Rect_<int>, cv::Scalar_<double> const&, int, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawFilledRectangle(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::RotatedRect::points(cv::Point_<float>*) const'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawFilledRectangle(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::fillConvexPoly(cv::Mat&, cv::Point_<int> const*, int, cv::Scalar_<double> const&, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawFilledRectangle(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::rectangle(cv::Mat&, cv::Rect_<int>, cv::Scalar_<double> const&, int, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawPoint(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::circle(cv::_InputOutputArray const&, cv::Point_<int>, int, cv::Scalar_<double> const&, int, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawGradientLine(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::LineIterator::LineIterator(cv::Mat const&, cv::Point_<int>, cv::Point_<int>, int, bool)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawGradientLine(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::rectangle(cv::Mat&, cv::Rect_<int>, cv::Scalar_<double> const&, int, int, int)'
bazel-out/arm-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawText(mediapipe::RenderAnnotation const&): error: undefined reference to 'cv::putText(cv::_InputOutputArray const&, cv::String const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2102.323s, Critical Path: 1410.13s
INFO: 1790 processes: 1790 linux-sandbox.
FAILED: Build did NOT complete successfully
`

**Comment by jiuqiant** [comment]
The issue is the OpenCV library is not configured correctly for MediaPipe.
How do you install the OpenCV library and config it for MediaPipe? We provide 3 options to config OpenCV for MediaPipe in the step 3 of https://google.github.io/mediapipe/getting_started/install#installing-on-debian-and-ubuntu. Moreover, https://github.com/google/mediapipe/issues/666 may also help.

**Comment by codeNick7** [comment]
Yup.. Adding the following in BUILD solved the issue. Somehow I used option to install OpenCV but that did not configure mediapipe build dependencies as expected.

cc_binary(
    name = "hand_tracking_cpu",
    deps = [
        "//mediapipe/examples/desktop:demo_run_graph_main",
        "//mediapipe/graphs/hand_tracking:desktop_tflite_calculators",
    ],
    linkopts = [
    "-latomic",
    "-lopencv_core",
    "-lopencv_calib3d",
    "-lopencv_features2d",
    "-lopencv_imgcodecs",
    "-lopencv_video",
    "-lopencv_highgui",
    "-lopencv_imgproc",
    "-lopencv_videoio"
    ],
)
