### ISSUE TITLE
Running hand detection model through Python

### ISSUE THREAD

**Issue by DmitryRyumin** [google/mediapipe#92]
When I run the model for determining hands through Python, I encounter slow work in the process of determining hands! More precisely, it is
`interpreter.invoke ()`
Frame rate drops sharply from 40 to 4!
How can I increase the frame rate to 20 or 25?

**Comment by jiuqiant** [comment]
I recommend reaching out to the TensorFlow community for such questions. MediaPipe is not responsible for model inference, and we probably don't know the answer as well.

**Comment by nagarjun-ananth** [comment]
@DmitryRyumin Could you please let me know how you loaded the tflite model on python. I've an unsupported custom operation for its interpreter.

**Comment by wolterlw** [comment]
@nagarjun-ananth 
you have to build tensorflow from source and add custom operations in the Python wrapper.

You can do it directly in `tensorflow/lite/python/interpreter_wrapper/`
Here is the relevant part of `interpreter_wrapper.cc` function `CreateInterpreterWrapper`

```
  auto resolver = absl::make_unique<tflite::ops::builtin::BuiltinOpResolver>();                                                                                                                                      
  resolver->AddCustom("MaxPoolingWithArgmax2D",                                                                                                                                                                      
            tflite_operations::RegisterMaxPoolingWithArgmax2D());                                                                                                                                                    
  resolver->AddCustom("MaxUnpooling2D",                                                                                                                                                                              
            tflite_operations::RegisterMaxUnpooling2D());                                                                                                                                                            
  resolver->AddCustom("Convolution2DTransposeBias",                                                                                                                                                                  
            tflite_operations::RegisterConvolution2DTransposeBias());                                                                                                                                                
                                                                                                                                                                                                                     
  auto interpreter = CreateInterpreter(model.get(), *resolver);                                                                                                                                                      
 ```
Then you include and link CutomOp implementations and you're good

**Comment by wolterlw** [comment]
@DmitryRyumin how do you crop the input image for joint detection? 
I've read somewhere they use landmarks 0 and 2 to find hand rotation, but I'm not sure how they resize the palm bounding box to fit the fingers in.

**Comment by fanzhanggoogle** [comment]
It's a simple heuristic. Just enlarge the rectangle and move the palm part lower. Here's the actual parameters we use to [transform palm detection rectangle for later landmark detection](https://github.com/google/mediapipe/blob/61bc4556af586bb3837f17187568d1345b3ee8f5/mediapipe/graphs/hand_tracking/hand_detection_gpu.pbtxt#L185).

> @DmitryRyumin how do you crop the input image for joint detection?
> I've read somewhere they use landmarks 0 and 2 to find hand rotation, but I'm not sure how they resize the palm bounding box to fit the fingers in.

**Comment by mgyong** [comment]
@DmitryRyumin 
Another user has created a minimal python interface to the Google MediaPipe Handtracking pipeline
https://github.com/wolterlw/hand_tracking
It has custom ops supported using tflite mode in python

**Comment by sebastijan94** [comment]
> When I run the model for determining hands through Python, I encounter slow work in the process of determining hands! More precisely, it is
> `interpreter.invoke ()`
> Frame rate drops sharply from 40 to 4!
> How can I increase the frame rate to 20 or 25?

Did you manage to increase the FPS?
