### ISSUE TITLE
Can't feed MacOS host webcam stream to OpenCvVideoDecoderCalculator on VM's Ubuntu via RTP

### ISSUE THREAD

**Issue by garyscetbon** [google/mediapipe#920]
I'm trying to feed my host webcam stream to a Mediapipe graph that uses opencv_video_decoder_calculator on a VM running Ubuntu.

I run on my Mac (host): 
```
ffmpeg -f avfoundation -video_device_index 1 -r 15 -i "My Webcam Name" -profile:v high -pix_fmt yuv420p -level:v 4.1 -preset ultrafast -tune zerolatency -vcodec libx264 -r 15 -b:v 512k -s 960x720 -f rtp_mpegts -flush_packets 0 -vf hflip rtp://vm-local-ip:5000
```

On the VM's Ubuntu terminal, when I run `ffplay rtp://0.0.0.0:5000` I get the host webcam output showing up fine. 

But when I try to feed that stream to the graph, I get the error:
**fail to make video header due to the incorrect metadata from the video file at rtp://0.0.0.0:5000**

I added a console log to debug and saw that: 
- fps = 15
- frame_count_ = -214748364
- width_ = 0
- height_ = 0

It also outputs **non-existing PPS 0 referenced** and **decode_slice_header error** errors. 

Any idea on how to get those metadata right to get the webcam stream to work with OpenCvVideoDecoderCalculator?

**Comment by mcclanahoochie** [comment]
Does the VM not read the webcam directly? If so, the video decoder calc is not needed, and you can use this [example](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/demo_run_graph_main.cc) to run from the camera directly.

If the webcam doesn't work in the VM (i assume that is why the video+ffmpeg hack), then you may need to edit a special case for the "infinite" frame count check [here](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/video/opencv_video_decoder_calculator.cc#L130) and [here](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/video/opencv_video_decoder_calculator.cc#L141), to allow things to flow.

Another thing to try, is the webcam [demo](https://github.com/google/mediapipe/blob/master/mediapipe/examples/desktop/demo_run_graph_main.cc) mentioned above  also supports loading from a file, and doesn't do any header checks. So you could try that too (they both use opencv under the hood).

**Comment by garyscetbon** [comment]
Thanks for the reply @mcclanahoochie I've made it work by using the webcam directly in the VM (I had compatibility issues at first, but found a workaround). I had tried to mess around with the `frame_count_, width_ and height_` checks but that triggered a bunch of errors down the road with OpenCV unable to instantiate any window.

Thanks for your input!
