### ISSUE TITLE
performance issue on interference of handpose model on browser.

### ISSUE THREAD

**Issue by vasanthhr** [google/mediapipe#921]
Hello team,

I inferenced web based hand-pose model on browser, it shows lagging on performance(speed). 

Is there anyway to improve the performance ?
Is there anyway this web based model supports wasm(tfjs back-end set) ? (I tried to request this issue [here ](https://github.com/misterpeddy/hands-down/issues/43) but issue is not resolved yet.

Please help and guide me to improve the inference  performance on web based model.

**Comment by vasanthhr** [comment]
Team,

can you please update on this issues? (Appreciate your support)

**Comment by fanzhanggoogle** [comment]
Which backend are you using? I vaguely remembered that the hand-pose model with WebGL backend should be pretty fast. However using wasm (CPU) is definitely gonna be slow.

**Comment by vasanthhr** [comment]
We using webgl, but still its too slow.

Can you help us how to pass the required video and get the hand-landmark output by using this below package:

https://viz.mediapipe.dev/demo/hand_tracking

**Comment by vasanthhr** [comment]
@delebash @rahulscp

**Comment by delebash** [comment]
Sorry no I don't

**Comment by fanzhanggoogle** [comment]
Hi, we have updated version of the web demo. Have you tried the latest one? Feel free to re-open if there's still any issue.
