### ISSUE TITLE
mediapipe tracking algorithm with custom model other than tensorflow

### ISSUE THREAD

**Issue by Dhananjay2048** [google/mediapipe#922]
I am trying to reuse the mediapipe tracking algorithm with my own trained custom model for Qualcomm model.
I understand mediapipe is purely using Pbtxt graph and tflite models.

my assumption was to use the tracking source and attach it with my own trained model, which i did for Qualcomm.
is it possible, please suggest how.

**Comment by fanzhanggoogle** [comment]
Are you able to convert Qualcomm model to TFLite model which is the only supported inference engine for now. If so, it's definitely possible to use TFLiteInferenceCalculator. Or you have to write your own calculator that wraps the inference engine for Qualcomm model.

**Comment by mcclanahoochie** [comment]
Closing for now due to lack of activity
