### ISSUE TITLE
Adding third party library to mediapipi

### ISSUE THREAD

**Issue by nyanmn** [google/mediapipe#925]
Mediapipe is very useful.

How can I add in third party library like [https://github.com/felHR85/UsbSerial](url) to mediapipe?
For normal Android Studio project, I just need to add in 

```
allprojects {
	repositories {
		jcenter()
		maven { url "https://jitpack.io" }
	}
}
```
to build.gradle.
And add the dependency to module's build.gradle:

implementation 'com.github.felHR85:UsbSerial:6.1.0'

But for mediapipe, how can I add in to interface usbserial?

**Comment by jiuqiant** [comment]
You can build MediaPipe AAR library (https://github.com/google/mediapipe/blob/master/docs/getting_started/android_archive_library.md) and import the AAR into Android Studio. After doing this, it's easy to continue the development and add third party libraries in Android Studio. 

If you want to build MediaPipe with Bazel, you need to make/modify a Bazel `maven_install` rule to add the third party libraries in the WORKSPACE file. See how we do this for MediaPipe at https://github.com/google/mediapipe/blob/master/WORKSPACE#L282. Bazel project also has an official instruction about this at https://docs.bazel.build/versions/master/migrate-maven.html#migrate-from-maven-to-bazel.

Hope this helps.

**Comment by nyanmn** [comment]
Thanks. I am also thinking for that and you confirm the idea. Thank you.
