### ISSUE TITLE
Hand landmark model on iOS metal hanging

### ISSUE THREAD

**Issue by rajeev-tbrew** [google/mediapipe#928]
I have tried to use hand landmark model on iOS. But when I use the model with metal, the code just hangs on the following line:

`interpreter = try Interpreter(modelPath: modelPath, options: options, delegates: delegates)`

If we remove the delegates' option then it works fine but takes 30-35ms to run (on CPU). Please note that I am using the model without mediapipe graph. I have been able to run earlier 2D model with delegates option without an issue.

Appreciate your help.

**Comment by sgowroji** [comment]
Hi @rajeev-tbrew, Could you please respond if you are still looking resolution for the above query. Thanks!

**Comment by rajeev-tbrew** [comment]
@sgowroji Please close this one.
