### ISSUE TITLE
iOS memory grow crash

### ISSUE THREAD

**Issue by plamenterziev** [google/mediapipe#93]
I am running the HandDetectionGpuApp on iPhone 7 with iOS 12.4.1 and the memory grows appr. 30-40MB / second. So after half a minute the app is terminated.

Is there a way to reduce the memory footprint or this is a memory leak?

**Comment by mgyong** [comment]
@plamenterziev 
We haven't had any other reports of HandDetectionGpuApp with runaway memory issues.
Can you provide more info on your setup
Mobile device (e.g. iPhone OS version)
Bazel version:
Xcode & Tulsi version (if issue is related to building in mobile dev enviroment)

**Comment by plamenterziev** [comment]
<img width="1049" alt="Screenshot 2019-09-18 at 19 14 59" src="https://user-images.githubusercontent.com/1300641/65166106-bd4dbe00-da48-11e9-9fa2-f85f00592150.png">

I am attaching a screenshot from the Xcode

Mobile device: iPhone 7 with iOS 12.4.1
Bazel: 0.29.0
Xcode: 10.3

I've tried on iPhone X as well and the Xcode profiler shows the same result (fast memory grow) and the app crashes with memory issue as well. However if run the app without attaching to Xcode on iPhone X then no crash occurs. If run the app on iPhone 7 without Xcode attached then still it crashes after 20 seconds.

**Comment by toandrew** [comment]
@mgyong @chuoling 
Any update for this issue? It's really a block issue in dev hand tracking app with xcode.

**Comment by camillol** [comment]
We don't have a concrete update at this time, but we're going to take a closer look at this issue soon. We plan to fix it.

**Comment by Cc-1993** [comment]
Indeed, I also successfully ran the xcode project on my iPhone, and the situation is the same as @plamenterziev, please fix this problem

**Comment by snowpunch** [comment]
It's still happening.
