### ISSUE TITLE
Failed to build on desktop

### ISSUE THREAD

**Issue by tonywang531** [google/mediapipe#931]
I am using VM Virutual Box manager with Ubuntu 20.04 installed. I only installed the necessary libraries to run mediapipe.

The hello world example works, but the hand tracking, multiple hand tracking and face recognition all failed. I think they all had the same error as below. 

<pre>pkg-config --modversion opencv

3.4.11

</pre>

<pre> bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

<font color="#4E9A06">INFO: </font>Build option --compilation_mode has changed, discarding analysis cache.

<font color="#4E9A06">INFO: </font>Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (1 packages loaded, 4668 targets configured).

<font color="#4E9A06">INFO: </font>Found 1 target...

<font color="#75507B">WARNING: </font>failed to create one or more convenience symlinks for prefix &apos;bazel-&apos;:

  cannot create symbolic link bazel-bin -&gt; /home/tony/.cache/bazel/_bazel_tony/668cbef4afcafdce026d3e26626c453d/execroot/mediapipe/bazel-out/k8-opt/bin:  /home/tony/mediapipe/bazel-bin (Permission denied)

  cannot create symbolic link bazel-testlogs -&gt; /home/tony/.cache/bazel/_bazel_tony/668cbef4afcafdce026d3e26626c453d/execroot/mediapipe/bazel-out/k8-opt/testlogs:  /home/tony/mediapipe/bazel-testlogs (Permission denied)

  cannot create symbolic link bazel-out -&gt; /home/tony/.cache/bazel/_bazel_tony/668cbef4afcafdce026d3e26626c453d/execroot/mediapipe/bazel-out:  /home/tony/mediapipe/bazel-out (Permission denied)

  cannot create symbolic link bazel-mediapipe -&gt; /home/tony/.cache/bazel/_bazel_tony/668cbef4afcafdce026d3e26626c453d/execroot/mediapipe:  /home/tony/mediapipe/bazel-mediapipe (Permission denied)

<font color="#CC0000"><b>ERROR: </b></font>/home/tony/mediapipe/mediapipe/examples/desktop/hand_tracking/BUILD:27:1: Linking of rule &apos;//mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu&apos; failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu-2.params

Use --sandbox_debug to see verbose messages from the sandbox

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph() [clone .cold]: error: undefined reference to &apos;cv::String::deallocate()&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph() [clone .cold]: error: undefined reference to &apos;cv::String::deallocate()&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph() [clone .cold]: error: undefined reference to &apos;cv::String::deallocate()&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph() [clone .cold]: error: undefined reference to &apos;cv::String::deallocate()&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to &apos;cv::VideoCapture::open(int)&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to &apos;cv::String::allocate(unsigned long)&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to &apos;cv::namedWindow(cv::String const&amp;, int)&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to &apos;cv::VideoCapture::open(cv::String const&amp;)&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to &apos;cv::VideoWriter::open(cv::String const&amp;, int, double, cv::Size_&lt;int&gt;, bool)&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to &apos;cv::VideoWriter::write(cv::Mat const&amp;)&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to &apos;cv::String::allocate(unsigned long)&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to &apos;cv::imshow(cv::String const&amp;, cv::_InputArray const&amp;)&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to &apos;cv::String::allocate(unsigned long)&apos;

bazel-out/k8-opt/bin/mediapipe/examples/desktop/_objs/demo_run_graph_main/demo_run_graph_main.o:demo_run_graph_main.cc:function RunMPPGraph(): error: undefined reference to &apos;cv::String::allocate(unsigned long)&apos;

bazel-out/k8-opt/bin/mediapipe/calculators/video/_objs/opencv_video_decoder_calculator/opencv_video_decoder_calculator.o:opencv_video_decoder_calculator.cc:function mediapipe::OpenCvVideoDecoderCalculator::Open(mediapipe::CalculatorContext*): error: undefined reference to &apos;cv::VideoCapture::VideoCapture(cv::String const&amp;)&apos;

bazel-out/k8-opt/bin/mediapipe/calculators/video/_objs/opencv_video_decoder_calculator/opencv_video_decoder_calculator.o:opencv_video_decoder_calculator.cc:function mediapipe::OpenCvVideoDecoderCalculator::Open(mediapipe::CalculatorContext*): warning: the use of `tmpnam&apos; is dangerous, better use `mkstemp&apos;

bazel-out/k8-opt/bin/mediapipe/calculators/video/_objs/opencv_video_encoder_calculator/opencv_video_encoder_calculator.o:opencv_video_encoder_calculator.cc:function mediapipe::OpenCvVideoEncoderCalculator::SetUpVideoWriter(float, int, int): error: undefined reference to &apos;cv::VideoWriter::VideoWriter(cv::String const&amp;, int, double, cv::Size_&lt;int&gt;, bool)&apos;

bazel-out/k8-opt/bin/mediapipe/calculators/video/_objs/opencv_video_encoder_calculator/opencv_video_encoder_calculator.o:opencv_video_encoder_calculator.cc:function mediapipe::OpenCvVideoEncoderCalculator::Close(mediapipe::CalculatorContext*): warning: the use of `tmpnam&apos; is dangerous, better use `mkstemp&apos;

bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_cropping_calculator/image_cropping_calculator.o:image_cropping_calculator.cc:function mediapipe::ImageCroppingCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to &apos;cv::getPerspectiveTransform(cv::_InputArray const&amp;, cv::_InputArray const&amp;)&apos;

bazel-out/k8-opt/bin/mediapipe/calculators/image/_objs/image_transformation_calculator/image_transformation_calculator.o:image_transformation_calculator.cc:function mediapipe::ImageTransformationCalculator::RenderCpu(mediapipe::CalculatorContext*): error: undefined reference to &apos;cv::getRotationMatrix2D(cv::Point_&lt;float&gt;, double, double)&apos;

bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawRectangle(mediapipe::RenderAnnotation const&amp;): error: undefined reference to &apos;cv::rectangle(cv::Mat&amp;, cv::Rect_&lt;int&gt;, cv::Scalar_&lt;double&gt; const&amp;, int, int, int)&apos;

bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawFilledRectangle(mediapipe::RenderAnnotation const&amp;): error: undefined reference to &apos;cv::fillConvexPoly(cv::Mat&amp;, cv::Point_&lt;int&gt; const*, int, cv::Scalar_&lt;double&gt; const&amp;, int, int)&apos;

bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawFilledRectangle(mediapipe::RenderAnnotation const&amp;): error: undefined reference to &apos;cv::rectangle(cv::Mat&amp;, cv::Rect_&lt;int&gt;, cv::Scalar_&lt;double&gt; const&amp;, int, int, int)&apos;

bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawGradientLine(mediapipe::RenderAnnotation const&amp;): error: undefined reference to &apos;cv::rectangle(cv::Mat&amp;, cv::Rect_&lt;int&gt;, cv::Scalar_&lt;double&gt; const&amp;, int, int, int)&apos;

bazel-out/k8-opt/bin/mediapipe/util/_objs/annotation_renderer/annotation_renderer.o:annotation_renderer.cc:function mediapipe::AnnotationRenderer::DrawText(mediapipe::RenderAnnotation const&amp;): error: undefined reference to &apos;cv::putText(cv::_InputOutputArray const&amp;, cv::String const&amp;, cv::Point_&lt;int&gt;, int, double, cv::Scalar_&lt;double&gt;, int, int, bool)&apos;

collect2: error: ld returned 1 exit status

Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build

Use --verbose_failures to see the command lines of failed build steps.

<font color="#4E9A06">INFO: </font>Elapsed time: 2.164s, Critical Path: 0.70s

<font color="#4E9A06">INFO: </font>0 processes.

<font color="#CC0000"><b>FAILED:</b></font> Build did NOT complete successfully

</pre>

**Comment by DhruvaBansal00** [comment]
I am facing the same issue right now. Running on Ubuntu 16.04.

**Comment by DhruvaBansal00** [comment]
Quick update: https://github.com/google/mediapipe/issues/666 > Comments here fixed it for me.

**Comment by tonywang531** [comment]
Yes I have fixed the issue by editing opencv config as well.
