### ISSUE TITLE
Desktop GPU run error in Docker container - An unacceptable value is specified

### ISSUE THREAD

**Issue by AlexYiningLiu** [google/mediapipe#932]
I created a Mediapipe docker image using the instructions here: https://google.github.io/mediapipe/getting_started/install.html#installing-using-docker. 
I have installed the mesa drivers used for Mediapipe GPU support as instructed here: https://google.github.io/mediapipe/getting_started/gpu_support.html#opengl-es-setup-on-linux-desktop.

I was able to compile the multi_hand_tracking_gpu example. However, when I run the example within the Docker container running the Mediapipe image, using
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_gpu \
  --calculator_graph_config_file=mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile.pbtxt
```
I get the error below:
```
root@fb89acd43129:/mediapipe# GLOG_logstderr=1 bazel-bin/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_gpu --calculator_graph_config_file=mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile.pbtxt
libEGL warning: DRI2: failed to authenticate
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
E20200722 18:46:19.313830  2217 demo_run_graph_main_gpu.cc:146] Failed to run the graph: Graph has errors: 
Calculator::Open() for node "[multihanddetectionsubgraph__TfLiteInferenceCalculator, TfLiteInferenceCalculator with output stream: multihanddetectionsubgraph__detection_tensors]" failed: [GL_INVALID_ENUM]: An unacceptable value is specified for an enumerated argument.: glBufferData in external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_buffer.h:255

```
Is there something else that I have to installed inside the Docker container? This desktop gpu example worked perfectly fine outside of docker on my computer so I know it's not a issue with my Nvidia GPU. When I check my video card using the instructions, I get:
```
root@fb89acd43129:/mediapipe# glxinfo | grep -i opengl
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  54
  Current serial number in output stream:  53

```

**Comment by mcclanahoochie** [comment]
Based on the error I would guess the GPU is not setup correctly, or if it is, then it doesn't support OpenGL ES 3.1+ inside the container.

The docker container MediaPipe provides doesn't do anything special to enable GPU, so you may need to search how to make sure GPU is supported in the docker you create.

Related:
- https://github.com/thewtex/docker-opengl
- https://hub.docker.com/r/nvidia/opengl
- https://github.com/google/mediapipe/issues/150
- https://github.com/google/mediapipe/issues/840

...though seems like you already searched the github issues

**Comment by zdegrh** [comment]
Hi, there,
i got the same problem, did you solve it?
@AlexYiningLiu 
thanks.

**Comment by DrStoop** [comment]
### `nvidia-docker run --env NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics <...your commands...>`

i had the same problem, Even though [docker says it does support glx](https://github.com/NVIDIA/nvidia-docker/issues/520#issuecomment-343629840), @flx42 found a way to overcome it by [adding the environment `NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics`  variable when launching the docker container](https://github.com/NVIDIA/nvidia-docker/issues/520#issuecomment-342863059). ...worked for me, good luck!

**Comment by sgowroji** [comment]
Hi @AlexYiningLiu, Could you please share the issue status. Thanks!

**Comment by sgowroji** [comment]
Hi @AlexYiningLiu, Could you please respond to my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity !
