### ISSUE TITLE
GPU support for running desktop examples in Windows? 

### ISSUE THREAD

**Issue by AlexYiningLiu** [google/mediapipe#933]
I see that there is experimental support for running Mediapipe desktop examples with GPU disabled on Windows here: https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows.

I am wondering if there is a way to do so in Windows with GPU enabled? Thanks.

**Comment by jiuqiant** [comment]
GPU support on Windows is not ready. See https://github.com/google/mediapipe/issues/836#issuecomment-648297200 for more details.

**Comment by AlexYiningLiu** [comment]
Would it be possible to run Mediapipe desktop GPU apps in Windows by building it within a Docker container in Ubuntu then pulling the container into Windows?
