### ISSUE TITLE
Failed to run the graph: ; Can't find file

### ISSUE THREAD

**Issue by incolor2** [google/mediapipe#934]
Hi guys, 

I tried to run the hand_tracking_cpu example in your docker container. Should the example work in docker(cam, windows 10 etc..)? Or do i need to do some undocumented tinkering?

root@716539ff472c:/mediapipe# GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
Starting local Bazel server and connecting to it...
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (109 packages loaded, 4814 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/sandbox
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu up-to-date:
  bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu
INFO: Elapsed time: 14.785s, Critical Path: 1.69s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
E20200723 10:04:43.335386    11 demo_run_graph_main.cc:146] Failed to run the graph: ; Can't find file:
root@716539ff472c:/mediapipe# mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

**Comment by jiuqiant** [comment]
The issue is you don't provide the graph config file to the binary in the bazel run command.
See the official instruction at https://github.com/google/mediapipe/blob/master/docs/getting_started/building_examples.md#option-1-running-on-cpu.

However, I am not sure if you can assess webcam in a container. If not, here is how to run the binary against a file. 
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu \
  --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt \
  --input_video_path=/path/to/output/video
  --output_video_path=/path/to/input/video
```

**Comment by incolor2** [comment]
Thanks, I totally missed that:-) The cam thing in docker seems complicated.
