### ISSUE TITLE
ERROR when I build Mediapipe example app

### ISSUE THREAD

**Issue by ZZZhaowendao** [google/mediapipe#935]
Hi,I have been studying mediapipe for several weeks.However,when I try to build the Mediapipe example app——**objectdetectiongpu**,I encounted the network issue.
So I studied the solution in #3 and followed it carefully.
I followed the guides：
> @chenloveheimei and I tested the current version of MediaPipe. We verified that MediaPipe demo apps can be successfully built in China now. However, due to the unstable/slow internet connection, we prefer to ask Bazel to cache the external repositories locally and search for the local archives before accessing the network.
For the users with unstable/slow internet connection, you may need to try the following build command several times to download all the needed external repositories:
```
$ bazel build -c opt --config=android_arm64 \ 
  --distdir=<your cache directory> \
  --repository_cache=<your cache directory> \
  --keep_going \
  mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu
```
**My steps are as follows:**
- 1、Follow the prompt link in ERROR to manually download dependent packages
- 2、Put the downloaded dependency package in a path under Ubuntu,mine is
/home/zcw/DevelopWorkSpace/AndroidSpace/MediaPipe/CacheDir
- 3、Run the command:
```
bazel build -c opt --config=android_arm64 \ 
  --distdir=/home/zcw/DevelopWorkSpace/AndroidSpace/MediaPipe/CacheDir \
  --repository_cache=/home/zcw/DevelopWorkSpace/AndroidSpace/MediaPipe/CacheDir \
  --keep_going \
mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu
```
However,I still get the same ERROR as below:
```
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz, https://github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz] to /home/zcw/.cache/bazel/_bazel_zcw/54baa620ed6327755a1076d22688eed7/external/org_tensorflow/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz: Tried to reconnect at offset 44,311,422 but server didn't support it
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz, https://github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz] to /home/zcw/.cache/bazel/_bazel_zcw/54baa620ed6327755a1076d22688eed7/external/org_tensorflow/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz: Tried to reconnect at offset 44,311,422 but server didn't support it
INFO: Elapsed time: 790.015s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
It seems that during the build process,**it does not give priority to fetching the dependency packages that I have manually downloaded**.Did I misunderstood the guide?Or I did something wrong?
And,I really want to use the objectdetection example app,if anyone can give a helpful advice or share the built project file,I would really appreciate it

**Comment by JsBlueCat** [comment]
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz, https://github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz] to /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz: Tried to reconnect at offset 1,819,151 but server didn't support it
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz, https://github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz] to /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz: Tried to reconnect at offset 1,819,151 but server didn't support it
ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz, https://github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz] to /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz: Tried to reconnect at offset 1,819,151 but server didn't support it
INFO: Elapsed time: 262.853s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
root@c6b56997da70:/mediapipe# GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world^C
root@c6b56997da70:/mediapipe# GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world

**Comment by sgowroji** [comment]
Hi @ZZZhaowendao & @JsBlueCat  [this](https://google.github.io/mediapipe/getting_started/troubleshooting.html#fail-to-fetch-remote-dependency-repositories) will resolve your error.
