### ISSUE TITLE
buildning example app on windows fails

### ISSUE THREAD

**Issue by incolor2** [google/mediapipe#936]
Hi guys,

I was trying to run the hello world example on win 10 following the install guide https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows

I am getting the following error. Any help would be greatly appreciated

E:\medipipe_repo\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Users\johan\AppData\Local\Programs\Python\Python38\python.exe" mediapipe/examples/desktop/hello_world
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = a07fc8b90c22e42962142504438a84b31567976adcd9ee1a4c9f75d2e3396f8d
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a07fc8b90c22e42962142504438a84b31567976adcd9ee1a4c9f75d2e3396f8d"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  C:/users/johan/_bazel_johan/qxrujxx6/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  C:/users/johan/_bazel_johan/qxrujxx6/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/johan/_bazel_johan/qxrujxx6/external/org_tensorflow/third_party/py/python_configure.bzl", line 210
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/johan/_bazel_johan/qxrujxx6/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/johan/_bazel_johan/qxrujxx6/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Traceback (most recent call last):
        File "C:/users/johan/_bazel_johan/qxrujxx6/external/org_tensorflow/third_party/py/python_configure.bzl", line 210
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/johan/_bazel_johan/qxrujxx6/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/johan/_bazel_johan/qxrujxx6/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
INFO: Elapsed time: 4.434s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded, 11 targets configured)

**Comment by jiuqiant** [comment]
Probably need to use double slashes to specify the python path. `--action_env PYTHON_BIN_PATH="C://Users//johan//AppData//Loca//Programs//Python//Python38//python.exe"`

Also, please checkout out v0.7.5. The latest version (v0.7.6) doesn't work with MSVC on Windows yet. See https://github.com/google/mediapipe/issues/908.

**Comment by incolor2** [comment]
Thanks for your help. Got things up and running now 👍
