### ISSUE TITLE
Managing palm and landmarks detection graphs and false-positives

### ISSUE THREAD

**Issue by azahreba** [google/mediapipe#937]
Hi mediapipe team 👋,
I'm using mediapipe (v0.7.5) for mobile hand tracking on GPU (iOS).
I build an ios static framework (as guys do here #725) using this fork: https://github.com/gogoqaz/mediapipe:
`bazel -c opt --config=ios_fat mediapipie/develop:HandTracker`

I'm experiencing some problems handling the `hand_landmarks` stream in the mobile UI. As I understand, it's caused by false-positive palm detections of `HandDetectionSubgraph` and the landmarks are being predicted even if there is no hand in the frame. Interestingly, `hand_presence_score` is high as well.

...
I0723 18:54:02.577186 1879814144 detection_letterbox_removal_calculator.cc:113] RAW PALM DETECTION SCORE
W0723 18:54:02.577215 1879814144 detection_letterbox_removal_calculator.cc:117] Palm
W0723 18:54:02.577224 1879814144 detection_letterbox_removal_calculator.cc:118] 1.0
I0723 18:54:02.577231 1879814144 detection_letterbox_removal_calculator.cc:119] -----------
I0723 18:54:02.587802 1879814144 thresholding_calculator.cc:121] HAND PRESENCE SCORE
W0723 18:54:02.587833 1879814144 thresholding_calculator.cc:122] 0.99707
I0723 18:54:02.587921 1879814144 thresholding_calculator.cc:124] --------------------------
...

As a temporary solution I increase the detection and suppression thresholds in `HandDetectionSubgraph`:
```
node {
  calculator: "TfLiteTensorsToDetectionsCalculator"
  input_stream: "TENSORS_GPU:detection_tensors"
  input_side_packet: "ANCHORS:anchors"
  output_stream: "DETECTIONS:detections"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteTensorsToDetectionsCalculatorOptions] {
      num_classes: 1
      num_boxes: 2944
      num_coords: 18
      box_coord_offset: 0
      keypoint_coord_offset: 4
      num_keypoints: 7
      num_values_per_keypoint: 2
      sigmoid_score: true
      score_clipping_thresh: 100.0
      reverse_output_order: true

      x_scale: 256.0
      y_scale: 256.0
      h_scale: 256.0
      w_scale: 256.0
      min_score_thresh: 1.0
    }
  }
}

node {
  calculator: "NonMaxSuppressionCalculator"
  input_stream: "detections"
  output_stream: "filtered_detections"
  node_options: {
    [type.googleapis.com/mediapipe.NonMaxSuppressionCalculatorOptions] {
      min_score_threshold: 1.0
      min_suppression_threshold: 0.5
      overlap_type: INTERSECTION_OVER_UNION
      algorithm: WEIGHTED
      return_empty_detections: true
    }
  }
}
```

The result of this = there are still some false-positive palm and landmark detections, especially when a face is in the frame + landmarks detection is not triggered when the hand is >30-40cm away from the camera, (my guess) because the palm detection score is low and doesn't pass the threshold.

1. Could you suggest how can I solve this problem?
Whether by customizing the graphs, intruding into the C++ code, or handling the streams in objc?
2. I also noticed that ACCEPT/REJECT streams of `ThresholdingCalculator` in `HandLandmarkSubgraph` are not used. I'm interested if there is some way to leverage this.

P.S. I'm a total newbie in C++/Obj-C. So, it'd be more than great if you provide me with the code examples.
Thanks! 🙏 ;)

**Comment by eknight7** [comment]
According to the [docs](https://google.github.io/mediapipe/solutions/hands#palm-detection-model), the average precision of the palm detection model is 95.7% .
Are you observing a worse performance on average?

Also are you using single hand tracking or multi-hand tracking?

CC'ing @fanzhanggoogle for notes on model feedback.

**Comment by fanzhanggoogle** [comment]
There're definitely cases trigger false positive detections. I can think of a few ways to eliminate that, e.g:
1) As you mentioned, Increase `min_score_threshold` and let the hand flag of hand landmark to filter out false positives
2) Only confirm it's a correct tracking/detection after consistent prediction for a temporal window as discussed in #951, false positive usually doesn't sustain for many number of frames.

**Comment by azahreba** [comment]
@fanzhanggoogle, @eknight7 
Thank you for the answers! 👍
