### ISSUE TITLE
Kinect (libfreenect)

### ISSUE THREAD

**Issue by TheArchKnight** [google/mediapipe#94]
Hi, im working on a VR tracking system, my goal is to use my kinect v1 on Linux. I dont want to use Openni as it's a dead project, and all of my tries have been a total failure.

Would be posible to take advantaje from the kinect depth sensors for do some skeleton tracking?

**Comment by mgyong** [comment]
You just need to write a calculator to take in the kinect depth data for processing. You can use the [Face detection example](https://mediapipe.readthedocs.io/en/latest/face_detection_mobile_gpu.html) to understand how to use Posenet for pose detection as part of the skeleton tracking.

**Comment by TheArchKnight** [comment]
> You just need to write a calculator to take in the kinect depth data for processing. You can use the [Face detection example](https://mediapipe.readthedocs.io/en/latest/face_detection_mobile_gpu.html) to understand how to use Posenet for pose detection as part of the skeleton tracking.
Thanks! As soon as i solve my problems of compile, i'm going ahead with this

**Comment by TheArchKnight** [comment]
> You just need to write a calculator to take in the kinect depth data for processing. You can use the [Face detection example](https://mediapipe.readthedocs.io/en/latest/face_detection_mobile_gpu.html) to understand how to use Posenet for pose detection as part of the skeleton tracking.

wouldn't the hand tracking example be more usefull?

**Comment by mgyong** [comment]
Hand tracking example has 2 models with a more complex graph triggering mechanism (loop back). The Face detection example is a standard 1 model example

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by AndreV84** [comment]
@jiuqiant it seems that the issue got closed without resolving it, right?
so if it was solved it would have been possible to use the solution to use the kinekt with mediapipe, but as it got just closed without addressing the issue there is no way to use the kinekt with mediapipe?
Or there are ways to use kinekt with mediapipe? kinekt 1? kinekt 2? both? neither of the two? without specific custom drivers? with specific drivers?
