### ISSUE TITLE
build_bazel_rules_apple download failed

### ISSUE THREAD

**Issue by JsBlueCat** [google/mediapipe#942]
run the below command in ubuntu18.04 x86_64
```GLOG_logtostderr=1 bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world```

but it throws out the problem:

ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
   java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.19.0/rules_apple.0.19.0.tar.gz] to /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/build_bazel_rules_apple/rules_apple.0.19.0.tar.gz: Read timed out
ERROR: no such package '@build_bazel_rules_apple//apple': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.19.0/rules_apple.0.19.0.tar.gz] to /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/build_bazel_rules_apple/rules_apple.0.19.0.tar.gz: Read timed out
ERROR: no such package '@build_bazel_rules_apple//apple': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.19.0/rules_apple.0.19.0.tar.gz] to /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/build_bazel_rules_apple/rules_apple.0.19.0.tar.gz: Read timed out

ERROR: no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz, https://github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz] to /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/org_tensorflow/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz: Tried to reconnect at offset 10,759,001 but server didn't support it

and i can't download tensorflow. is there any alternetive?

**Comment by sgowroji** [comment]
Hi @JsBlueCat, Could you please test the above with the latest release and let us know if you still face the same error. Thanks!
