### ISSUE TITLE
Seen Hand Joint Landmarks vs Obstructed Landmarks

### ISSUE THREAD

**Issue by nschoenwetter** [google/mediapipe#945]
Is there a way to output which hand landmarks the tracking software can see and which ones are hidden from its view? I assume it has something to do with the confidence of the palm detection, but I'm not entirely sure where to look.

**Comment by eknight7** [comment]
Hi - can you clarify reg. "which ones are hidden from its view"? Are you asking about the scenario if the user's palm is not facing the camera?

**Comment by nschoenwetter** [comment]
My apologies. Yes, that is the situation I am referring to.

**Comment by eknight7** [comment]
Suggested hack: You can use the `handedness` (https://github.com/google/mediapipe/blob/master/mediapipe/models/handedness.txt) output flag from the hand_landmark subgraph: https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/hand_landmark_gpu.pbtxt and determine if the palm is facing front or back based on the X coordinates of the thumb and the little finger.

For e.g., if the `handedness` flag says that the hand is a `left` hand, and the thumb is to the right of the little finger, then the left hand has a palm facing towards the camera, not the back of the camera.

**Comment by nschoenwetter** [comment]
But what if the hand is to the side so that you can see some of the fingers but not all of them? I assume that if the hand tracking software is not able to see a joint, it makes its best prediction. Is there a way to get the system to say which joint locations it sees and which ones it is predicting?

**Comment by huolianchu** [comment]
> Suggested hack: You can use the `handedness` (https://github.com/google/mediapipe/blob/master/mediapipe/models/handedness.txt) output flag from the hand_landmark subgraph: https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/hand_landmark_gpu.pbtxt and determine if the palm is facing front or back based on the X coordinates of the thumb and the little finger.
> 
> For e.g., if the `handedness` flag says that the hand is a `left` hand, and the thumb is to the right of the little finger, then the left hand has a palm facing towards the camera, not the back of the camera.

What format do I use to receive the output of handedness in processor.addPacketCallback()?

**Comment by nschoenwetter** [comment]
Is there any update on this? I am essentially trying to determine the joint confidence for each landmark. I assume that joints that are obstructed have a much lower confidence than joints that are visible to the camera.

**Comment by fanzhanggoogle** [comment]
Hi, you are right that the model will just "guess" where the joints are. Unfortunately currently we don't have per landmark visibility for this use case.
