### ISSUE TITLE
Saving frames as png/jpg instead of .mp4

### ISSUE THREAD

**Issue by TanmoyPanigrahi** [google/mediapipe#946]
Hey, I'm currently working on a project with the hand_detection subgraph for desktop. We're all set up in terms of running it and extracting the coordinates of the bounding box. Since we are trying to make a dataset of the frames with the hand, I wanted to save the region around the bounding box as an image instead of the usual mp4 file. 

I haven't had much luck with it yet so I would really appreciate any advice and direction I could receive regarding this issue. Thank you so much for your time!!

**Comment by eknight7** [comment]
You can save each processed image via `cv::imwrite` see https://docs.opencv.org/master/db/deb/tutorial_display_image.html.

**Comment by TanmoyPanigrahi** [comment]
Thank you for that!

**Comment by TanmoyPanigrahi** [comment]
Also, for anyone that's coming to this page a little confused - Mediapipe is writing/showing the video as a collection of frames so you can do what you want with each frame by using the Mat object called output_frame_mat.

**Comment by Gauraviiitian** [comment]
@eknight7 This is good but can you help with accomplishing the same thing in Android Example, For example an app where people can upload an image and get modified image with filters?

**Comment by TanmoyPanigrahi** [comment]
@Gauraviiitian i am not associated with mediapipe but i think what you would do is to use im::read IIRC to read the image as a MAT object and then apply your filters through the graph, and then save it using im::write. If you look at the bottom of the code for the files you will be able to look at how mediapipe is receiving, processing, and saving the image.
