### ISSUE TITLE
missing input file '//mediapipe:provisioning_profile.mobileprovision'

### ISSUE THREAD

**Issue by calvin422** [google/mediapipe#95]
Hi error message appear after try hand-tracking example 
`bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp`

and have finished the following process 
Symlink or copy your provisioning profile to mediapipe/mediapipe/provisioning_profile.mobileprovision.

```
cd mediapipe
ln -s ~/Downloads/MyProvisioningProfile.mobileprovision mediapipe/provisioning_profile.mobileprovision
```
Error message as below

> ERROR: missing input file '//mediapipe:provisioning_profile.mobileprovision'
> ERROR: /Users/user/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:43:1: //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp_entitlements: missing input file '//mediapipe:provisioning_profile.mobileprovision'
> ERROR: /Users/user/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:43:1: Creating runfiles tree bazel-out/ios_arm64-opt/bin/mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp.runfiles failed: build-runfiles failed: error executing command 
>   (cd /private/var/tmp/_bazel_user/f0e2cdeb2d039470c2f6c14511d864ac/execroot/mediapipe && \
>   exec env - \
>     PATH=/anaconda3/bin:/Users/user/anaconda3/condabin:/Users/user/miniconda2/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands \
>   /var/tmp/_bazel_user/install/2f0e8a8bce6bf62d516dfb015ecdabfa/_embedded_binaries/build-runfiles bazel-out/ios_arm64-opt/bin/mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp.runfiles_manifest bazel-out/ios_arm64-opt/bin/mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp.runfiles): Process terminated by signal 15: Process terminated by signal 15
> ERROR: missing input file '//mediapipe:provisioning_profile.mobileprovision'
> Target //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> ERROR: /Users/user/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:43:1 1 input file(s) do not exist

Anyone can help ? thanks

**Comment by jiuqiant** [comment]
What if you copy the mobileprovision file into mediapipe/mediapipe and rename it to provisioning_profile.mobileprovision? I just tried this approach, and it works for me at least.

**Comment by calvin422** [comment]
thanks may I know how can I find the mobileprovision file ?

**Comment by jiuqiant** [comment]
calvin422@, if you have an Apple developer account ,please follow [this instruction](https://www.wikihow.com/Create-a-Provisioning-Profile-for-iPhone) to create an app provisioning profile.

**Comment by calvin422** [comment]
If I use android version, can it be free of charge ?

**Comment by jiuqiant** [comment]
You need to turn on the developer options on your Android device. Then, the APKs can be installed.
Seems like the provisioning file is no longer a problem for you. I am going to close the issue.

**Comment by deepaksuthar** [comment]
> What if you copy the mobileprovision file into mediapipe/mediapipe and rename it to provisioning_profile.mobileprovision? I just tried this approach, and it works for me at least.

Worked for me as well.
