### ISSUE TITLE
How to eliminate false detection in “multi_hand_tracking_mobile_gpu”？

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#951]
I made an app to recognize five gestures, such as "1", "2", "3", "4" and "5". In the video links are as follows, when there is no hand in the field of vision, there are landmarks detected constantly. 
If coincidentally, the detected gesture (false detection) matches the gesture "Five", which will lead to wrong recognition. Regardless of real-time performance, can we detect three times and all three times are the same gesture? And then finally confirm, or what better way? The video links are as follows
https://youtu.be/cSLpG43Csoo

**Comment by fanzhanggoogle** [comment]
Hi, I'm not able to open your linked video. But you are right, there're definitely certain cases trigger false positive detections. 
What you described makes sense, but more in a temporal way, e.g. if 3 or more consecutive frames returns the same gesture then it'll be output?
