### ISSUE TITLE
Android/Unity - ExternalTextureConverter memory leak

### ISSUE THREAD

**Issue by ButcheredGenre** [google/mediapipe#952]
(Edit: most likely related to/ same issue as https://github.com/google/mediapipe/issues/967)

I'm trying to use multi hand tracking inside the Unity game engine on Android.

To do this, I've exported a Unity project to Android Studio and added the appropriate mediapipe code to the UnityPlayerActivity. The code I've added to the Activity is essentially identical to [the code from this example project Activity](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example/blob/master/app/src/main/java/com/example/mediapipemultihandstrackingapp/MainActivity.java) (this example runs without issue for me, though it seems to be using an older version of mediapipe).

When used with Unity, however, the ExternalTextureConverter generates (and never releases) textures every frame mediapipe detects features (if the hand tracking doesn't detect any features, this issue doesn't occur), eventually causing an out-of-memory crash. I can't say for sure that this issue has any relation to Unity at all.

All I know so far is that [outputFrame in nextOutputFrame() is always null (on initialization, and whenever features have been detected)](https://github.com/google/mediapipe/blob/e9fbe868e55fa23aaabc31f9f847c22287062850/mediapipe/java/com/google/mediapipe/components/ExternalTextureConverter.java#L396), causing createFrame() to be called repeatedly.

I'd appreciate any pointers on the matter :)

**Comment by lovehuanhuan** [comment]
add print in release frame function, It's ok

**Comment by sgowroji** [comment]
Hi @ButcheredGenre, Could you please respond if you are still looking resolution for the above query. Thanks!

**Comment by ButcheredGenre** [comment]
Hi @sgowroji, I'm no longer actively looking for a solution to this issue, though I never managed to fix the out-of-memory problem. For all I know it could be working fine in recent versions/ was a device-specific issue, but I can't test it right now. In any case, feel free to close unresolved due to lack of interest/ activity.
