### ISSUE TITLE
Cant Build examples

### ISSUE THREAD

**Issue by LeDuySon** [google/mediapipe#953]
i can run helloworld normally but when trying to build sth like hand_tracking its not work, can anyone help me

son@MSI:/mnt/c/Users/admin/Desktop/WORK/Tryon-mediapipe/mediapipe$ bazel build -c opt mediapipe/examples/desktop/hand_tracking:hand_tracking_tflite --define MEDIAPIPE_DISABLE_GPU=1
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_tflite (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /mnt/c/Users/admin/Desktop/work/Tryon-mediapipe/mediapipe/mediapipe/calculators/video/BUILD:198:1: C++ compilation of rule '//mediapipe/calculators/video:opencv_video_decoder_calculator' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from mediapipe/calculators/video/opencv_video_decoder_calculator.cc:23:
./mediapipe/framework/port/opencv_video_inc.h:88:10: fatal error: opencv2/optflow.hpp: No such file or directory
   88 | #include <opencv2/optflow.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_tflite failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.878s, Critical Path: 9.32s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by jiuqiant** [comment]
How do you install opencv? Can you take a look at https://github.com/google/mediapipe/issues/562#issuecomment-606203557 to see if that helps?

**Comment by LeDuySon** [comment]
> The issue seems to be the incorrect MediaPipe OpenCV config. Could you report how you install opencv? In addition, can you take a look at [#562 (comment)](https://github.com/google/mediapipe/issues/562#issuecomment-606203557) to see if that helps?

i used option 3(build from source code) to install opencv, #562 still cant fix my problems

**Comment by jiuqiant** [comment]
Can you list where your opencv headers and libraries are and I can help you modify the WORKSPACE and linux_opencv.BUILD files accrodingly.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
