### ISSUE TITLE
Issue in running the face-mesh model

### ISSUE THREAD

**Issue by aashishwaikar** [google/mediapipe#954]
Hi,
When I run the command "GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/face_mesh/face_mesh_gpu   --calculator_graph_config_file=mediapipe/graphs/face_mesh/face_mesh_desktop_live_gpu.pbtxt", it seems to be running, but the window for the webcam that should open isn't opening.
However, if I do that for the hand-tracker using "GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_gpu   --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_mobile.pbtxt",  it works perfectly fine.
Can I get some help in this please?

**Comment by mcclanahoochie** [comment]
can you provide the log messages?

does running a video file work?
   (using `--input_video_path=/path/to/video.mp4`  )

does the face mesh cpu version work?

**Comment by aashishwaikar** [comment]
`I20200731 09:57:43.735770  7371 demo_run_graph_main_gpu.cc:51] Get calculator graph config contents: # MediaPipe graph that performs face mesh with TensorFlow Lite on GPU.

# Input image. (GpuBuffer)
input_stream: "input_video"

# Output image with rendered results. (GpuBuffer)
output_stream: "output_video"
# Collection of detected/processed faces, each represented as a list of
# landmarks. (std::vector<NormalizedLandmarkList>)
output_stream: "multi_face_landmarks"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Defines side packets for further use in the graph.
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:num_faces"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet { int_value: 1 }
    }
  }
}

# Subgraph that detects faces and corresponding landmarks.
node {
  calculator: "FaceLandmarkFrontGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "NUM_FACES:num_faces"
  output_stream: "LANDMARKS:multi_face_landmarks"
  output_stream: "ROIS_FROM_LANDMARKS:face_rects_from_landmarks"
  output_stream: "DETECTIONS:face_detections"
  output_stream: "ROIS_FROM_DETECTIONS:face_rects_from_detections"
}

# Subgraph that renders face-landmark annotation onto the input image.
node {
  calculator: "FaceRendererGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "LANDMARKS:multi_face_landmarks"
  input_stream: "NORM_RECTS:face_rects_from_landmarks"
  input_stream: "DETECTIONS:face_detections"
  output_stream: "IMAGE:output_video"
}
I20200731 09:57:43.739535  7371 demo_run_graph_main_gpu.cc:57] Initialize the calculator graph.
I20200731 09:57:43.752688  7371 demo_run_graph_main_gpu.cc:61] Initialize the GPU.
I20200731 09:57:43.764626  7371 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 4
I20200731 09:57:43.768292  7378 gl_context.cc:324] GL version: 3.2 (OpenGL ES 3.2 Mesa 19.2.8)
I20200731 09:57:43.768393  7371 demo_run_graph_main_gpu.cc:67] Initialize the camera or load the video.
I20200731 09:57:44.063203  7371 demo_run_graph_main_gpu.cc:88] Start running the calculator graph.
I20200731 09:57:44.067145  7371 demo_run_graph_main_gpu.cc:93] Start grabbing and processing frames.
INFO: Created TensorFlow Lite delegate for GPU.
`
-This is what appears on the terminal(nothing unusual) but the webcam window doesn't open. 
-Same issue for video file
-However, the face mesh cpu works fine

**Comment by JsBlueCat** [comment]
> work

how to get the output result?

**Comment by mcclanahoochie** [comment]
GLOG_v=2  enables extra logs

Closing for now due to lack of activity
