### ISSUE TITLE
Train script for face landmark model

### ISSUE THREAD

**Issue by whatisor** [google/mediapipe#955]
Can you open Training script for the face landmark model?
I just want to make sure this is Open Source Project, not only Open Binary.
Thank you.

**Comment by jiuqiant** [comment]
I guess it's a dulplication of https://github.com/google/mediapipe/issues/11. Let's add mgyong@ to see if he has more comments on this.

**Comment by sgowroji** [comment]
Hi @whatisor, You can refer [here](https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_landmark).
