### ISSUE TITLE
Running Objectron model on server. 

### ISSUE THREAD

**Issue by alter-sachin** [google/mediapipe#958]
Hi, the list shows that the objectron model that does 3D bounding box for chairs and shoes can not work for desktop.

I want to have a client server architecture, where the client ( any mobile device) sends input image streams to the server ( our dedicated google cloud GPU p1000 machine)  which sends back the inference results.

I want to do this to have a decent frame rate 

Can i make it work in this way ? Can we not run the graph on the server and make this possible ? Possibily by sending frames across through sockets from clients and infering on the server.

Please let me know, hope to make this work

**Comment by alter-sachin** [comment]
@cdibona @willnorris @cdibona @dberlin  please any help would be appreciated !

**Comment by mjcrouse** [comment]
Did you get this working with any reasonable performance? If so what method did you use to sending frames back and forth?

**Comment by alter-sachin** [comment]
No. I am not able to understand how to do this.

**Comment by sgowroji** [comment]
Hi @alter-sachin, let us know if you're still looking resolution for the above query.
