### ISSUE TITLE
Accessing handedness on multi hand tracking desktop

### ISSUE THREAD

**Issue by smn154** [google/mediapipe#959]
Hi @mgyong 

Thanks for adding handedness in version v0.7.5. I was wondering how can I access the handedness in the multi hand tracking desktop top level? I have followed examples like #200 to access the landmarks but can't figure out how to access the handiness.  

Thanka
Sammy

**Comment by tonywang531** [comment]
This post illustrates how to modify to show handiness (unfortunately it is in Japanese). Apparently the output result is reversed (left is identified as right and right is identified as left), but I have not verified it yet.
https://dev.classmethod.jp/articles/mediapipe-extract-handedness/

**Comment by eknight7** [comment]
Using code similar to https://gist.github.com/eknight7/d4a57504c8f866fc80c0eb2c61ff6b4f#file-multi_hand_tracking_run_graph_cpu_main-cc-L117-L129 you can access handedness in the multi-hand tracking desktop app.

**Comment by smn154** [comment]
Thanks!

**Comment by AntonioDomenech** [comment]
Hello, I would like to print the handedness in the terminal or save it in text file, not print it in the screen. Any idea on how can I do that?

Thank you very much

**Comment by shehramjamil** [comment]
> Hello, I would like to print the handedness in the terminal or save it in text file, not print it in the screen. Any idea on how can I do that?
> 
> Thank you very much
   //Create a file before the handlandmarks loop
    FILE *f = fopen("/home/shami/Desktop/hands_landmarks.txt", "a");
    if (f == NULL)
    {
    LOG(INFO) << "Error opening file!\n";
    exit(1);
    }
     
// Put this inside the nested loop
 fprintf(f, "Hand: [%d]  Landmark: [%d] --> Landmark x(%f),Landmark y(%f),Landmark z(%f)\n", 		  	hand_id,i,landmark.x(),landmark.y(),landmark.z()); 

// Close it after the loop 
//fclose(f)

**Comment by prantoran** [comment]
Here is one way in c++:

1. include the following in the BUILD: `"//mediapipe/framework/formats:classification_cc_proto"`
2. In the .cc file:
```
...
#include "mediapipe/framework/formats/classification.pb.h"
...
constexpr char kHandedness[] = "handedness";
...
      ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller handedness_poller,
                  graph.AddOutputStreamPoller(kHandedness));
      mediapipe::Packet handedness_packet;
      if (!handedness_poller.Next(&handedness_packet)) break;
      const auto& handedness = handedness_packet.Get<std::vector<mediapipe::ClassificationList, std::allocator<mediapipe::ClassificationList> >>();
      for (int i = 0; i < handedness.size(); i ++) {
        auto& h = handedness[i];
        std::cerr << "h.classification_size:" << h.classification_size() << "\n";
        if (h.classification_size() > 0) {
          const mediapipe::Classification & c = h.classification(0);
          std::cerr << "label:" << c.label() << "\tindex:" << c.index() << "\n";
        }
      }
```

**Comment by BitLoose** [comment]
I've tested using the same code as prantoran, and it hangs when no handedness packet is available so needs the known "presence_packet" check, that done, mediaPipe is not reliably determining handedness, its about 30% reliable, then after a while there are no more handedness packets for reasons unknown.
Anyone getting better results?  If so, please let me know

**Comment by BitLoose** [comment]
I tested handedness in the release build and strangely there is zero handedness packet output, whereas in the debug build there is although with poo reliability.  Why would release and debug vary?  I'm using Windows and Visual Studio 2022, everything up to date, with MediaPipe 2.0 2019
