### ISSUE TITLE
Building on Arch Linux 

### ISSUE THREAD

**Issue by TheArchKnight** [google/mediapipe#96]
When i try to compile on Arch Linux, i got this log at the start 

`WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/67def62936e28f97c16182dfcc467d8d1cae02b4.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'build_bazel_rules_apple' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "6c9fcae7a3597aabd43f28be89466afe0eab18de", shallow_since = "1565379803 -0700" and dropping ["tag"]
DEBUG: Call stack for the definition of repository 'build_bazel_rules_apple' which is a git_repository (rule definition at /home/anorak/.cache/bazel/_bazel_anorak/15b5d1102ac088e8191f8e704f58e19f/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /home/anorak/Repos/mediapipe/WORKSPACE:253:1
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = 07315c19273cc3479ff58c7ae66c7a1ff2d65160f85689a9e1729a46566b2198
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "07315c19273cc3479ff58c7ae66c7a1ff2d65160f85689a9e1729a46566b2198"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/anorak/.cache/bazel/_bazel_anorak/15b5d1102ac088e8191f8e704f58e19f/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/anorak/Repos/mediapipe/WORKSPACE:28:1
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
`

And at the end 

`ERROR: /home/anorak/Repos/mediapipe/mediapipe/examples/desktop/hello_world/BUILD:19:1: Linking of rule '//mediapipe/examples/desktop/hello_world:hello_world' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-fastbuild/bin/mediapipe/examples/desktop/hello_world/hello_world-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-fastbuild/bin/external/com_github_glog_glog/_objs/glog/utilities.pic.o:utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_Ux86_64_getcontext'
bazel-out/k8-fastbuild/bin/external/com_github_glog_glog/_objs/glog/utilities.pic.o:utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_ULx86_64_init_local'
bazel-out/k8-fastbuild/bin/external/com_github_glog_glog/_objs/glog/utilities.pic.o:utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_ULx86_64_get_reg'
bazel-out/k8-fastbuild/bin/external/com_github_glog_glog/_objs/glog/utilities.pic.o:utilities.cc:function google::GetStackTrace(void**, int, int): error: undefined reference to '_ULx86_64_step'
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 883.925s, Critical Path: 469.19s
INFO: 440 processes: 440 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
`
I've modified the files as described on the Debian instrucctions

**Comment by jiuqiant** [comment]
For your first error, I believe that's a temporarily network connection issue. Please retry it later. If it still doesn't work, please see https://github.com/google/mediapipe/issues/3#issuecomment-506926022 for the caching solution.
For you second issue, please append --define 'libunwind=true' to the bazel command. A fresh Debian or Ubuntu system usually doesn't have libunwind installed by default. But if your system has libunwind, then the define flag is needed.

**Comment by TheArchKnight** [comment]
@jiuqiant I dont have a Debian/Ubuntu system. Im using Arch, but im adapting everything for getting working. Thanks for your answer

**Comment by TheArchKnight** [comment]
What do you me

> For your first error, I believe that's a temporarily network connection issue. Please retry it later. If it still doesn't work, please see [#3 (comment)](https://github.com/google/mediapipe/issues/3#issuecomment-506926022) for the caching solution.
> For you second issue, please append --define 'libunwind=true' to the bazel command. A fresh Debian or Ubuntu system usually doesn't have libunwind installed by default. But if your system has libunwind, then the define flag is needed.

What do you mean with cache dir? I suppose you are talking about the ~/.cache/bazel dir.

**Comment by TheArchKnight** [comment]
Ok, i run the workaround for slow internet, and added the --define 'libuwind=true'. it compiles the hello world example, but im not getting the output of it. However, im still getting some warnings

`WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
`

**Comment by jiuqiant** [comment]
> Ok, i run the workaround for slow internet, and added the --define 'libuwind=true'. it compiles the hello world example, but im not getting the output of it. However, im still getting some warnings
> 
> `WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found `

Can you comment out the line 95 of [the WORKSPACE file](https://github.com/google/mediapipe/blob/master/WORKSPACE) and retry the command?
To be honest, if it's a network issue, such as "Server Not Found", we don't have very good solution for that. Bazel, the build system, takes care of the dependency library fetching. MediaPipe doesn't have the control.

Regrading your https://github.com/google/mediapipe/issues/96#issuecomment-531535219,  the cache directory can be anywhere you want Bazel to cache the already downloaded dependency libraries. For example, you can do
```
$ bazel build -c opt --config=android_arm64 \ 
  --distdir=/tmp/mediapipe_cache \
  --repository_cache=/tmp/mediapipe_cache \
  --keep_going \
  mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu
```

**Comment by kjuzz** [comment]
--define 'libuwind=true' works fine.
