### ISSUE TITLE
Error while bazel build for 'objectdetectioncpu' for Android application

### ISSUE THREAD

**Issue by dheeraj-2000** [google/mediapipe#960]
Hi, I'm trying to build _objectdetectioncpu_ application for android using bazel on Terminal, but I'm getting error while building.

**Here are my system information:**
OS Platform and Distribution: **Linux Mint 19.2**
Bazel version: **3.4.1**

**I've tried to build using two commands, though both gives the same error:**
1) Given on [Mediapipe documentation](https://google.github.io/mediapipe/getting_started/building_examples.html)' 
`bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu:objectdetectioncpu`
2) Found on [bazel documentation](https://docs.bazel.build/versions/3.4.0/tutorial/android-app.html);
 `bazel build //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu:objectdetectioncpu`

**Here is the error log:**
`Loading: 
Loading: 0 packages loaded
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu:objectdetectioncpu (0 packages loaded, 0 targets configured)
ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD:25:8: invalid character: '�'
ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD:25:9: invalid character: '�'
ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD:25:10: invalid character: '�'`
.
.
.

`ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD:28:3: invalid character: '�'
ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD:28:4: syntax error at '//': expected expression
ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD:28:23: invalid character: '�'`
.
.
.
`ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD:42:45: invalid character: '�'
ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD:42:46: invalid character: '�'
ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD:42:47: invalid character: '�'
ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/graphs/object_detection/BUILD:19:11: no such target '//mediapipe/calculators/util:annotation_overlay_calculator': target 'annotation_overlay_calculator' not declared in package 'mediapipe/calculators/util' defined by /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD and referenced by '//mediapipe/graphs/object_detection:mobile_calculators'
ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/graphs/object_detection/BUILD:19:11: no such target '//mediapipe/calculators/util:detection_label_id_to_text_calculator': target 'detection_label_id_to_text_calculator' not declared in package 'mediapipe/calculators/util' defined by /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD and referenced by '//mediapipe/graphs/object_detection:mobile_calculators'
ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/graphs/object_detection/BUILD:19:11: no such target '//mediapipe/calculators/util:detection_letterbox_removal_calculator': target 'detection_letterbox_removal_calculator' not declared in package 'mediapipe/calculators/util' defined by /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD and referenced by '//mediapipe/graphs/object_detection:mobile_calculators'
ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/graphs/object_detection/BUILD:19:11: no such target '//mediapipe/calculators/util:detections_to_render_data_calculator': target 'detections_to_render_data_calculator' not declared in package 'mediapipe/calculators/util' defined by /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD and referenced by '//mediapipe/graphs/object_detection:mobile_calculators'
ERROR: /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/graphs/object_detection/BUILD:19:11: no such target '//mediapipe/calculators/util:non_max_suppression_calculator': target 'non_max_suppression_calculator' not declared in package 'mediapipe/calculators/util' defined by /home/dheeraj/my_projects/my_project_env/practice/mediapipe/mediapipe/calculators/util/BUILD and referenced by '//mediapipe/graphs/object_detection:mobile_calculators'
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu:objectdetectioncpu' failed; build aborted: Analysis failed
INFO: Elapsed time: 9.890s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 24 targets configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 24 targets configured)
`

I've checked for the calculator which is showing as not declared in `mediapipe/calculators/util`, but all are declared. 

How I can resolve this? Similar error is comming while building other applications too.

**Comment by jiuqiant** [comment]
Not sure why you get invalid characters... Can you successfully build the hello world desktop example?

**Comment by dheeraj-2000** [comment]
@jiuqiant Yeah, I've successfully build that one.

Infact, I've successfully build and Run an android tutorial app given in [bazel documtation](https://docs.bazel.build/versions/master/tutorial/android-app.html).

**Comment by eknight7** [comment]
Can you open the BUILD file and see if there are any special characters? What if you try the basic hello world Android app?

**Comment by RohitSingh1226** [comment]
Even I am having this same issue, is there any fix for it. 
And no I don't have any special characters in my build file.

**Comment by sgowroji** [comment]
Hi @dheeraj-2000 & @RohitSingh1226, Could you please respond if you still seeing the above error with the latest release. Thanks!
