### ISSUE TITLE
An error occurred during the fetch of repository 'local_execution_config_python'

### ISSUE THREAD

**Issue by dipalokehan** [google/mediapipe#962]
When I tried to build the mediapipe project using Bazel from Android Studio, I got the below issues -
 
**Error: An error occurred during the fetch of repository 'local_execution_config_python':
Error:(143, -1) File "C:/users/user/_bazel_user/y7qvsuy5/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, in _check_python_bin
Error:(66, -1) File "C:/users/user/_bazel_user/y7qvsuy5/external/org_tensorflow/third_party/remote_config/common.bzl", line 66, in get_bash_bin
Error:(27, -1) File "C:/users/user/_bazel_user/y7qvsuy5/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, in which
Error:(208, -1) File "C:/users/user/_bazel_user/y7qvsuy5/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
Error: command succeeded, but not all targets were analyzed**

Can anyone help me get rid of this? Any help is highly appreciable

**Comment by jiuqiant** [comment]
Unfortunately, MediaPipe doesn't support building Android apps on Windows yet.

https://google.github.io/mediapipe/getting_started/install#installing-on-windows mentions that "Note: building MediaPipe Android apps is still not possible on native Windows. Please do this in WSL instead and see the WSL setup instruction in the next section".
