### ISSUE TITLE
Which are the best/perfect conditions for hand gestures capturing?

### ISSUE THREAD

**Issue by alandrade1** [google/mediapipe#966]
**Which are the best/perfect conditions for hand gestures capturing?**

I wonder if we have the best camera conditions settings registered in a document.

The question is simple. What is the best camera capturing tutorial for a project using mediapipe? Do we have one? We will capture/record gestures movements in **reaseach (controled environment) setting**, and do the video post-processing after. In the document, it would be nice to have:

- [ ] **(1)** Background color/contrast with best performance
- [ ] **(2)** Hand best distance from the camera
- [ ] **(3)** Camera specifications/resolution normative values and best setup
- [ ] **(4)** Ideal vs. efficient (data saving) frame rates
- [ ] **(5)** Other camera specs
- [ ] **(6)** Testing conditions and comparisons with "gold standart" measures

Thanks a lot. I hope the discussion could be useful.

**Comment by sgowroji** [comment]
Hi @alandrade1, We are glad to know your interest with MediaPipe. I would recommend you to check the latest Hands solution with many improvements. And reach us if you still have any further queries specific to it. Thanks!
