### ISSUE TITLE
Android Hand Tracking Example apps crashing

### ISSUE THREAD

**Issue by mjcrouse** [google/mediapipe#967]
The basic/helloworld app and facemeshgpu work fine, but the handtrackinggpu and multihandtrackinggpu both crash after approx 30 seconds. They run fine until about then and start to slow down before closing I think due to a memory issue.

Google Pixel 3a
Built from Ubuntu 20.04
Android SDK 29
Android NDK 20.xxx
Open JDK 11.xx

Portion of logcat:

7-30 11:34:52.397  1424  8856 W ActivityManager: Scheduling restart of crashed service com.google.android.apps.nexuslauncher/com.android.quickstep.TouchInteractionService in 105572ms
07-30 11:34:52.398  1424  8856 W ActivityManager: Scheduling restart of crashed service com.google.android.apps.nexuslauncher/com.android.launcher3.notification.NotificationListener in 1557008ms
07-30 11:34:52.401  1424  1493 W ActivityManager: setHasOverlayUi called on unknown pid: 14307
07-30 11:34:52.405  1424  8856 I ActivityManager: Process com.qualcomm.qcrilmsgtunnel (pid 13101) has died: vis IMPF
07-30 11:34:52.406  1424  1520 I libprocessgroup: Successfully killed process cgroup uid 1001 pid 13101 in 0ms
07-30 11:34:52.406  1424  8856 W ActivityManager: Scheduling restart of crashed service com.qualcomm.qcrilmsgtunnel/.QcrilMsgTunnelService in 105563ms
07-30 11:34:52.406   840   840 I Zygote  : Process 13101 exited due to signal 9 (Killed)
07-30 11:34:52.408   581   581 I ServiceManager: service 'qchook' died
07-30 11:34:52.416   893   893 I lowmemorykiller: 2 memory pressure events were skipped after a kill!
07-30 11:34:52.453 14276 14276 W ProviderHelper: Unknown dynamite feature providerinstaller
07-30 11:34:52.455  1424  8856 W Process : Unable to open /proc/295/status
07-30 11:34:52.485 14130 14157 D ExternalTextureConv: Created output texture: 1236 width: 960 height: 1280
07-30 11:34:52.505 14276 14276 I DynamiteModule: Considering local module providerinstaller:0 and remote module providerinstaller:0
07-30 11:34:52.518 14130 14157 D ExternalTextureConv: Created output texture: 1237 width: 960 height: 1280
07-30 11:34:52.527 14276 14276 W ProviderInstaller: Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
07-30 11:34:52.538 14130 14203 D MainActivity: Received multi-hand landmarks packet.
07-30 11:34:52.539 14130 14203 D MainActivity: [TS:1938114081] Number of hands detected: 2
07-30 11:34:52.539 14130 14203 D MainActivity: 	#Hand landmarks for hand[0]: 21
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [0]: (0.49426258, 1.0002224, 4.385749E-5)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [1]: (0.37947127, 0.9291747, 0.12941751)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [2]: (0.3553981, 0.8526661, 0.1861572)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [3]: (0.36917934, 0.7926791, 0.23007557)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [4]: (0.39370543, 0.74844146, 0.26875207)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [5]: (0.32858264, 0.78928494, 0.047920603)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [6]: (0.3355212, 0.6900203, 0.13366766)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [7]: (0.35819075, 0.6797406, 0.22752546)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [8]: (0.37496233, 0.68546945, 0.29212797)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [9]: (0.40269634, 0.7816793, 0.018806977)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [10]: (0.40665972, 0.66796136, 0.107599996)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [11]: (0.4170079, 0.6643755, 0.2161917)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [12]: (0.4218286, 0.67367584, 0.28603607)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [13]: (0.4755519, 0.78259796, 0.005897103)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [14]: (0.46926883, 0.68617207, 0.09803712)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [15]: (0.46713197, 0.6975258, 0.18842395)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [16]: (0.46848756, 0.7210533, 0.23092559)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [17]: (0.53805923, 0.7871025, 0.0049142526)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [18]: (0.51426286, 0.7213682, 0.10214562)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [19]: (0.4966838, 0.7280629, 0.17255667)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [20]: (0.4883146, 0.7482571, 0.21094982)
07-30 11:34:52.539 14130 14203 D MainActivity: 	#Hand landmarks for hand[1]: 21
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [0]: (0.7129238, 0.38133317, 1.9075955E-5)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [1]: (0.71466225, 0.3837045, -0.07887878)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [2]: (0.7050682, 0.3817859, -0.1336626)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [3]: (0.6872523, 0.38542354, -0.17302762)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [4]: (0.6633047, 0.3982722, -0.21100447)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [5]: (0.6532494, 0.34556785, -0.15121326)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [6]: (0.60543793, 0.3424977, -0.1989074)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [7]: (0.56963015, 0.34263772, -0.23619014)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [8]: (0.53733087, 0.34174585, -0.2655404)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [9]: (0.6374986, 0.35251382, -0.12682082)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [10]: (0.57856905, 0.34510413, -0.1855213)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [11]: (0.53460205, 0.34517276, -0.22210996)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [12]: (0.49297738, 0.34522778, -0.25185683)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [13]: (0.63035715, 0.36226663, -0.10183345)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [14]: (0.5775372, 0.35700938, -0.15002339)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [15]: (0.53848124, 0.35660213, -0.18066266)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [16]: (0.5036281, 0.35449615, -0.20426184)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [17]: (0.62757593, 0.3733439, -0.07858131)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [18]: (0.59058964, 0.3701906, -0.11581448)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [19]: (0.5619754, 0.37183604, -0.14258666)
07-30 11:34:52.539 14130 14203 D MainActivity: 		Landmark [20]: (0.5346475, 0.37318388, -0.16578922)
07-30 11:34:52.551   893   893 E lowmemorykiller: Kill 'com.google.mediapipe.apps.multihandtrackinggpu' (14130), uid 10253, oom_adj 0 to free 162892kB
07-30 11:34:52.551   893   893 I lowmemorykiller: Reclaimed 162892kB, cache(73372kB) and free(118816kB)-reserved(45752kB) below min(73728kB) for oom_adj 0
07-30 11:34:52.551   893   893 I lowmemorykiller: Suppressed 13 failed kill reports
07-30 11:34:52.567   841   841 D Zygote  : Forked child process 14389
07-30 11:34:52.590   840   840 I Zygote  : Process 14130 exited due to signal 9 (Killed)
07-30 11:34:52.590  1424  2034 W InputDispatcher: channel 'a8d417d com.google.mediapipe.apps.multihandtrackinggpu/com.google.mediapipe.apps.multihandtrackinggpu.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-30 11:34:52.590  1424  2034 E InputDispatcher: channel 'a8d417d com.google.mediapipe.apps.multihandtrackinggpu/com.google.mediapipe.apps.multihandtrackinggpu.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-30 11:34:52.595  1424  1519 W ActivityManager: Slow operation: 324ms so far, now at startProcess: returned from zygote!
07-30 11:34:52.595  1424  1519 W ActivityManager: Slow operation: 324ms so far, now at startProcess: done updating battery stats
07-30 11:34:52.595  1424  1519 W ActivityManager: Slow operation: 324ms so far, now at startProcess: building log message
07-30 11:34:52.595  1424  1519 I ActivityManager: Start proc 14389:com.android.vending/u0a43 for broadcast {com.android.vending/com.google.android.finsky.setup.LauncherConfigurationReceiver}
07-30 11:34:52.595  1424  1519 W ActivityManager: Slow operation: 324ms so far, now at startProcess: starting to update pids map

**Comment by mjcrouse** [comment]
bazel 3.4.1
cloned @jiuqiant multi hand aar example, ran it fine.
build my own multi_hand_aar and run it, get same lowmemorykiller killing the process

**Comment by mjcrouse** [comment]
precompiled handtrackinggpu example APK seems to work fine as well

**Comment by mjcrouse** [comment]
tried @mcclanahoochie suggestion in #969 but it's still crashing (although it does seem to last a little longer than before)

**Comment by mjcrouse** [comment]
reproduceable with apk built on another machine running stable on huawei mate 8.
also crashes on a LG v30

**Comment by lynneChan** [comment]
I also get some error like that:
```
2020-08-12 11:20:13.611 13457-13484/? E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.google.mediapipe.apps.handtrackinggpu, PID: 13457
    java.lang.RuntimeException: glActiveTexture: GL error: 0x505
        at com.google.mediapipe.glutil.ShaderUtil.checkGlError(ShaderUtil.java:175)
        at com.google.mediapipe.glutil.ExternalTextureRenderer.render(ExternalTextureRenderer.java:93)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.updateOutputFrame(ExternalTextureConverter.java:433)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:336)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:295)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:238)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
```

It sames as the process's memory usage was keeping increasing while the processing running till the error happened. I also test the version from [TheJLifeX](https://github.com/TheJLifeX/mediapipe) which was forked after commit `d144e564d8f48737f1bf684ee741c9ccf6a5909d`, and that works all fine. Maybe some commit after that increase some bugs that keep consuming the memory till it is not enough, and then the app crashed.

**Comment by mcclanahoochie** [comment]
https://github.com/google/mediapipe/issues/997#issuecomment-674288478

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by brucechou1983** [comment]
@jiuqiant 

I'm still facing the same issue on `0.8.8` release. Do you have any solution for this issue?

```
06-01 17:44:40.920 28726 28989 E AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
06-01 17:44:40.920 28726 28989 E AndroidRuntime: Process: app.popup.app, PID: 28726
06-01 17:44:40.920 28726 28989 E AndroidRuntime: java.lang.RuntimeException: glActiveTexture: GL error: 0x505
06-01 17:44:40.920 28726 28989 E AndroidRuntime:  at com.google.mediapipe.glutil.ShaderUtil.checkGlError(Unknown Source:33)
06-01 17:44:40.920 28726 28989 E AndroidRuntime:  at com.google.mediapipe.glutil.ExternalTextureRenderer.render(Unknown Source:13)
```

Android phone : samsung SM-C900Y
OS Version : 8.0.0
