### ISSUE TITLE
High memory and 0.77 version build error.

### ISSUE THREAD

**Issue by istoneyou** [google/mediapipe#969]
1.  I am trying the hand tracking in android, and the memory is too high. In issue [736](https://github.com/google/mediapipe/issues/736) said that you are working on the a solution to cut the memory usage by half. So how about the solution and when will it be OK? @jiuqiant 
 I try to reduce the SurfaceTexture size, and it can reduce the memory cost. Does this affect the accuracy of hand tracking?  

2. When I update the 0.77 version and build the AAR, the build error happens:
ERROR: /mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:17:1: Building mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/libmp_hand_tracking_aar_android_lib.jar (51 source files) failed (Exit 1)
mediapipe/java/com/google/mediapipe/framework/TypeNameRegistryLite.java:13: error: duplicate class: com.google.mediapipe.framework.TypeNameRegistryConcrete
final class TypeNameRegistryConcrete implements TypeNameRegistry {
      ^
mediapipe/java/com/google/mediapipe/framework/TypeNameRegistryFull.java:4: error: package com.google.protobuf.contrib does not exist
import com.google.protobuf.contrib.MessageUtils;
                                  ^
mediapipe/java/com/google/mediapipe/framework/TypeNameRegistryFull.java:17: error: cannot find symbol
    return MessageUtils.getProtoTypeName(clazz);
           ^
  symbol:   variable MessageUtils
  location: class TypeNameRegistryConcrete
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_hand_tracking_aar failed to build

**Comment by jiuqiant** [comment]
@mcclanahoochie , can you share the solution to reduce the memory usage?

**Comment by jiuqiant** [comment]
@mcclanahoochie, can you share the solution to reduce the memory usage?

**Comment by mcclanahoochie** [comment]
Hi, sorry for the delay.

Here is a temporary, manual workaround:

Please replace [ImageCroppingCalculator::RenderGpu](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/image/image_cropping_calculator.cc#L263) function with what is below...

```
::mediapipe::Status ImageCroppingCalculator::RenderGpu(CalculatorContext* cc) {
  if (cc->Inputs().Tag(kImageGpuTag).IsEmpty()) {
    return ::mediapipe::OkStatus();
  }
#if !defined(MEDIAPIPE_DISABLE_GPU)
  const Packet& input_packet = cc->Inputs().Tag(kImageGpuTag).Value();
  const auto& input_buffer = input_packet.Get<mediapipe::GpuBuffer>();
  auto src_tex = gpu_helper_.CreateSourceTexture(input_buffer);

  int out_width, out_height;
  GetOutputDimensions(cc, src_tex.width(), src_tex.height(), &out_width,
                      &out_height);

  // auto dst_tex =
  //   gpu_helper_.CreateDestinationTexture(out_width, out_height); // don't use the memory pool

  mediapipe::GpuBuffer dst_buf =
      mediapipe::GpuBuffer(mediapipe::GlTextureBuffer::Create(
          out_width, out_height, input_buffer.format()));
  auto ptr = dst_buf.GetGlTextureBufferSharedPtr();
  ptr->WaitOnGpu();
  glBindTexture(ptr->target(), ptr->name());
  glBindTexture(ptr->target(), 0);
#ifdef __ANDROID__
  glBindFramebuffer(GL_FRAMEBUFFER, 0);
#endif
  GLuint fb = 0;
  glDisable(GL_DEPTH_TEST);
  glGenFramebuffers(1, &fb);
  glBindFramebuffer(GL_FRAMEBUFFER, fb);
  glViewport(0, 0, ptr->width(), ptr->height());
  glActiveTexture(GL_TEXTURE0);
  glBindTexture(ptr->target(), ptr->name());
  glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, ptr->target(),
                         ptr->name(), 0);

  // Run cropping shader on GPU.
  {
    // gpu_helper_.BindFramebuffer(dst_tex);  // GL_TEXTURE0

    glActiveTexture(GL_TEXTURE1);
    glBindTexture(src_tex.target(), src_tex.name());

    GlRender();

    glActiveTexture(GL_TEXTURE2);
    glBindTexture(GL_TEXTURE_2D, 0);
    glFlush();
  }

  // Send result image in GPU packet.
  // auto output = dst_tex.GetFrame<mediapipe::GpuBuffer>();

  auto output = absl::make_unique<mediapipe::GpuBuffer>(dst_buf);
  output->GetGlTextureBufferSharedPtr()->Updated(
      gpu_helper_.GetGlContext().CreateSyncToken());
  glBindFramebuffer(GL_FRAMEBUFFER, 0);
  glDeleteFramebuffers(1, &fb);

  cc->Outputs().Tag(kImageGpuTag).Add(output.release(), cc->InputTimestamp());

  // Cleanup
  src_tex.Release();
  // dst_tex.Release();
#endif  //  !MEDIAPIPE_DISABLE_GPU

  return ::mediapipe::OkStatus();
}
```

A more elegant solution is in review, and will come eventually.

The underlying issue is that there is an internal GPU memory pool/cache that is indexed on image sizes. In the hand tracking graph, the cropping calculator could potentially[usually] produce a new size image crop each frame, which fills the pool with images unlikely to be re-used. The workaround here is to skip the memory cache for cropping operation.

**Comment by jiuqiant** [comment]
For the aar build error, try the following fix:

```
diff --git a/mediapipe/java/com/google/mediapipe/framework/BUILD b/mediapipe/java/com/google/mediapipe/framework/BUILD
index 893b6ea..8cbe1e2 100644
--- a/mediapipe/java/com/google/mediapipe/framework/BUILD
+++ b/mediapipe/java/com/google/mediapipe/framework/BUILD
@@ -136,6 +136,8 @@ android_library(
 # Expose the java source files for building mediapipe AAR.
 filegroup(
     name = "java_src",
-    srcs = glob(["*.java"]),
+    srcs = glob(["*.java"],
+                exclude = ["TypeNameRegistryFull.java"],
+           ),
     visibility = ["//mediapipe:__subpackages__"],
 )
```

**Comment by istoneyou** [comment]
@jiuqiant @mcclanahoochie  Thank you for your response.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by mcclanahoochie** [comment]
a big update on gpu memory usage was recently made in [v0.7.9](https://github.com/google/mediapipe/blob/v0.7.9/) that reduces memory pressure quite a bit (the official fix for https://github.com/google/mediapipe/issues/969#issuecomment-667294219 ) . please try v0.7.9+ if you are experiencing gpu memory related issues
