### ISSUE TITLE
Object detector for Web browser ?

### ISSUE THREAD

**Issue by vasanthhr** [google/mediapipe#971]
Hello,

As of now shoe detector outputs 3d Boundingbox supported for only android (APK).

Is there anyway you can release shoe detector for web browser inference model sooner?

(Like: json and .bin model files along with supporting js for web inference).

**Comment by mgyong** [comment]
@vasanthhr We don't plan to release web version of shoe detector

**Comment by sgowroji** [comment]
Closing this present issue from the above comment.
