### ISSUE TITLE
Using static libraries built with -fno-rtti, such as WebRTC, with MediaPipe

### ISSUE THREAD

**Issue by prantoran** [google/mediapipe#972]
Is it possible to use static libraries built with `-fno-rtti`, such as WebRTC, with MediaPipe and Bazel?

I tried building MediaPipe with `-fno-rtti` and get errors pointing to `glog`. I tried linking precompiled WebRTC headers and static `.a` files using `cc_import` but I get the errors that functions not defined.

**Comment by jiuqiant** [comment]
Sorry, I don't have an answer for this.
