### ISSUE TITLE
how to dump the face landmark out

### ISSUE THREAD

**Issue by JsBlueCat** [google/mediapipe#973]
how to dump the face landmark out to get the keypoints of facemesh??

**Comment by eknight7** [comment]
Are you doing this on desktop/android/iOS? You can use code similar to https://github.com/google/mediapipe/blob/master/mediapipe/examples/ios/facemeshgpu/ViewController.mm#L181-L191 on desktop for example.

Use https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu/MainActivity.java#L65-L92 for Android.

**Comment by eknight7** [comment]
@JsBlueCat were you able to try this?

**Comment by JsBlueCat** [comment]
> ere you able to try this?

sorry, we conduct it on desktop linux.

**Comment by eknight7** [comment]
Hi, this gist shows an example of how to print landmarks for hand tracking on desktop: https://gist.github.com/eknight7/d4a57504c8f866fc80c0eb2c61ff6b4f#file-multi_hand_tracking_run_graph_cpu_main-cc
You may try a similar approach for getting face landmarks.

Closing this issue for now. Please feel free to re-open if it is still relevant. Thank you.
