### ISSUE TITLE
Latest Commit Broke the Build for MSVC

### ISSUE THREAD

**Issue by bedbad** [google/mediapipe#975]
![image](https://user-images.githubusercontent.com/21035980/89176668-f7885700-d557-11ea-89d4-d0f232294f0c.png)

$  bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world
Loading:
Loading: 0 packages loaded
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (0 packages loaded, 0 targets configured)
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 20] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[6 / 133] Compiling mediapipe/framework/tool/fill_packet_set.cc; 1s local ... (11 actions running)
INFO: From ProtoCompile mediapipe/framework/calculator_profile.pb.h:
bazel-out/x64_windows-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
ERROR: .../mediapipe/mediapipe/framework/BUILD:685:1: C++ compilation of rule '//mediapipe/framew
.\mediapipe/framework/packet.h(448): error C2672: 'absl::lts_2020_02_25::make_unique': no matching overloaded function found
.\mediapipe/framework/packet.h(448): error C2783: 'void std::make_unique(_Types &&...)': could not deduce template argument for '__formal'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\memory(2065): note: see declaration of 'std::mak
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.512s, Critical Path: 2.10s
INFO: 11 processes: 11 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by boger57** [comment]
Hi~I come across the same build error with you. Really want to know did you solve it?

**Comment by samtremblo** [comment]
It’s a known issue as far as I’m aware. Revert to version 0.75 for now

**Comment by jiuqiant** [comment]
The following changes can fix this issue:

```
diff --git a/mediapipe/framework/deps/file_helpers.cc b/mediapipe/framework/deps/file_helpers.cc
index ae9048a..5a7e7e3 100644
--- a/mediapipe/framework/deps/file_helpers.cc
+++ b/mediapipe/framework/deps/file_helpers.cc
@@ -16,6 +16,7 @@
 
 #ifdef _WIN32
 #include <Windows.h>
+#include <direct.h>
 #else
 #include <dirent.h>
 #endif  // _WIN32
diff --git a/mediapipe/framework/legacy_calculator_support.h b/mediapipe/framework/legacy_calculator_support.h
index 4cd15ce..75ffa68 100644
--- a/mediapipe/framework/legacy_calculator_support.h
+++ b/mediapipe/framework/legacy_calculator_support.h
@@ -66,6 +66,7 @@ class LegacyCalculatorSupport {
   };
 };
 
+#if !defined(_MSC_VER)
 // We only declare this variable for two specializations of the template because
 // it is only meant to be used for these two types.
 // Note that, since these variables are members of specific template
@@ -79,6 +80,7 @@ thread_local CalculatorContext*
 template <>
 thread_local CalculatorContract*
     LegacyCalculatorSupport::Scoped<CalculatorContract>::current_;
+#endif
 
 }  // namespace mediapipe
 
diff --git a/mediapipe/framework/packet.h b/mediapipe/framework/packet.h
index ee9a85a..5221f55 100644
--- a/mediapipe/framework/packet.h
+++ b/mediapipe/framework/packet.h
@@ -439,11 +439,16 @@ struct is_concrete_proto_t
 template <typename T>
 struct MessageRegistrationImpl {
   static NoDestructor<mediapipe::RegistrationToken> registration;
+  static std::unique_ptr<Holder<T>> CreateMessageHolder() {
+    return absl::make_unique<Holder<T>>(new T);
+  }
 };
 
 // Static members of template classes can be defined in the header.
 template <typename T>
 NoDestructor<mediapipe::RegistrationToken>
     MessageRegistrationImpl<T>::registration(MessageHolderRegistry::Register(
-        T{}.GetTypeName(), [] { return absl::make_unique<Holder<T>>(new T); }));
+        T{}.GetTypeName(), MessageRegistrationImpl<T>::CreateMessageHolder));
 
 // For non-Message payloads, this does nothing.
 template <typename T, typename Enable = void>
```

**Comment by jiuqiant** [comment]
Fixed in https://github.com/google/mediapipe/commit/c828392681bc343a90e188c5ad5f295bada1eefb.
