### ISSUE TITLE
Cannot save output video file

### ISSUE THREAD

**Issue by tonywang531** [google/mediapipe#976]
Strangely I cannot get my local mediapipe save output video file. I am using the exact the same command on another laptop and it works. On my main computer I can see my GPU process the whole video, however nothing is saved.

I have checked the file permissions, changed the input and output video path to several different locations and also updated the local repository to the lastest. Still, I cannot save the result file.

<pre>GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/multi_hand_tracking/multi_hand_tracking_gpu   --calculator_graph_config_file=mediapipe/graphs/hand_tracking/multi_hand_tracking_mobile.pbtxt \
&gt; --input_video_path=/home/tony/mediapipe/output.avi \ --output_video_path=/home/tony/mediapipe/output4.avi
I20200803 21:01:47.609367 13926 demo_run_graph_main_gpu.cc:51] Get calculator graph config contents: # MediaPipe graph that performs multi-hand tracking with TensorFlow Lite on GPU.
# Used in the examples in
# mediapipe/examples/android/src/java/com/mediapipe/apps/multihandtrackinggpu.

# Images coming into and out of the graph.
input_stream: &quot;input_video&quot;
output_stream: &quot;output_video&quot;

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: &quot;FlowLimiterCalculator&quot;
  input_stream: &quot;input_video&quot;
  input_stream: &quot;FINISHED:multi_hand_rects&quot;
  input_stream_info: {
    tag_index: &quot;FINISHED&quot;
    back_edge: true
  }
  output_stream: &quot;throttled_input_video&quot;
}

# Determines if an input vector of NormalizedRect has a size greater than or
# equal to the provided min_size.
node {
  calculator: &quot;NormalizedRectVectorHasMinSizeCalculator&quot;
  input_stream: &quot;ITERABLE:prev_multi_hand_rects_from_landmarks&quot;
  output_stream: &quot;prev_has_enough_hands&quot;
  node_options: {
    [type.googleapis.com/mediapipe.CollectionHasMinSizeCalculatorOptions] {
      # This value can be changed to support tracking arbitrary number of hands.
      # Please also remember to modify max_vec_size in
      # ClipVectorSizeCalculatorOptions in
      # mediapipe/graphs/hand_tracking/subgraphs/multi_hand_detection_gpu.pbtxt
      min_size: 2
    }
  }
}

# Drops the incoming image if the previous frame had at least N hands.
# Otherwise, passes the incoming image through to trigger a new round of hand
# detection in MultiHandDetectionSubgraph.
node {
  calculator: &quot;GateCalculator&quot;
  input_stream: &quot;throttled_input_video&quot;
  input_stream: &quot;DISALLOW:prev_has_enough_hands&quot;
  output_stream: &quot;multi_hand_detection_input_video&quot;
  node_options: {
    [type.googleapis.com/mediapipe.GateCalculatorOptions] {
      empty_packets_as_allow: true
    }
  }
}

# Subgraph that detections hands (see multi_hand_detection_gpu.pbtxt).
node {
  calculator: &quot;MultiHandDetectionSubgraph&quot;
  input_stream: &quot;multi_hand_detection_input_video&quot;
  output_stream: &quot;DETECTIONS:multi_palm_detections&quot;
  output_stream: &quot;NORM_RECTS:multi_palm_rects&quot;
}

# Subgraph that localizes hand landmarks for multiple hands (see
# multi_hand_landmark.pbtxt).
node {
  calculator: &quot;MultiHandLandmarkSubgraph&quot;
  input_stream: &quot;IMAGE:throttled_input_video&quot;
  input_stream: &quot;NORM_RECTS:multi_hand_rects&quot;
  output_stream: &quot;LANDMARKS:multi_hand_landmarks&quot;
  output_stream: &quot;NORM_RECTS:multi_hand_rects_from_landmarks&quot;
}

# Caches a hand rectangle fed back from MultiHandLandmarkSubgraph, and upon the
# arrival of the next input image sends out the cached rectangle with the
# timestamp replaced by that of the input image, essentially generating a packet
# that carries the previous hand rectangle. Note that upon the arrival of the
# very first input image, an empty packet is sent out to jump start the
# feedback loop.
node {
  calculator: &quot;PreviousLoopbackCalculator&quot;
  input_stream: &quot;MAIN:throttled_input_video&quot;
  input_stream: &quot;LOOP:multi_hand_rects_from_landmarks&quot;
  input_stream_info: {
    tag_index: &quot;LOOP&quot;
    back_edge: true
  }
  output_stream: &quot;PREV_LOOP:prev_multi_hand_rects_from_landmarks&quot;
}

# Performs association between NormalizedRect vector elements from previous
# frame and those from the current frame if MultiHandDetectionSubgraph runs.
# This calculator ensures that the output multi_hand_rects vector doesn&apos;t
# contain overlapping regions based on the specified min_similarity_threshold.
node {
  calculator: &quot;AssociationNormRectCalculator&quot;
  input_stream: &quot;prev_multi_hand_rects_from_landmarks&quot;
  input_stream: &quot;multi_palm_rects&quot;
  output_stream: &quot;multi_hand_rects&quot;
  node_options: {
    [type.googleapis.com/mediapipe.AssociationCalculatorOptions] {
      min_similarity_threshold: 0.5
    }
  }
}

# Subgraph that renders annotations and overlays them on top of the input
# images (see multi_hand_renderer_gpu.pbtxt).
node {
  calculator: &quot;MultiHandRendererSubgraph&quot;
  input_stream: &quot;IMAGE:throttled_input_video&quot;
  input_stream: &quot;DETECTIONS:multi_palm_detections&quot;
  input_stream: &quot;LANDMARKS:multi_hand_landmarks&quot;
  input_stream: &quot;NORM_RECTS:0:multi_palm_rects&quot;
  input_stream: &quot;NORM_RECTS:1:multi_hand_rects&quot;
  output_stream: &quot;IMAGE:output_video&quot;
}
I20200803 21:01:47.609887 13926 demo_run_graph_main_gpu.cc:57] Initialize the calculator graph.
I20200803 21:01:47.611706 13926 demo_run_graph_main_gpu.cc:61] Initialize the GPU.
I20200803 21:01:47.616763 13926 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 5
I20200803 21:01:47.658483 13939 gl_context.cc:324] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 440.100)
I20200803 21:01:47.658557 13926 demo_run_graph_main_gpu.cc:67] Initialize the camera or load the video.
I20200803 21:01:47.668368 13926 demo_run_graph_main_gpu.cc:88] Start running the calculator graph.
I20200803 21:01:47.671754 13926 demo_run_graph_main_gpu.cc:93] Start grabbing and processing frames.
INFO: Created TensorFlow Lite delegate for GPU.
I20200803 21:01:52.169677 13926 demo_run_graph_main_gpu.cc:175] Shutting down.
I20200803 21:01:52.173394 13926 demo_run_graph_main_gpu.cc:189] Success!
Segmentation fault (core dumped)
</pre>

**Comment by bedbad** [comment]
You have a segfault.

**Comment by tonywang531** [comment]
I put strace for program, not sure if that is any help

**Comment by tonywang531** [comment]
Somehow I tried it again today, and somehow it just worked. Maybe I cannot insert the \ character before the output_video_path
