### ISSUE TITLE
face_mesh:some problem about TfLiteConverterCalculator

### ISSUE THREAD

**Issue by chenti2x** [google/mediapipe#978]
**I modify the ComputeShader (TfLiteConverterCalculator in face_landmark_gpu.pbtxt) as follows. I want to pass a grayscale image(pixels：0-255，single channel) to my model(160*160). But the inference result is always wrong, could you help me aboat the problem? I work in ubuntu system with gpu.Thank you very much**

        // Shader to convert GL Texture to Shader Storage Buffer Object (SSBO),
        // with normalization to either: [0,1] or [-1,1].
        const std::string shader_source = absl::Substitute(
            R"( #version 310 es
          layout(local_size_x = $0, local_size_y = $0) in;
          layout(binding = 0) uniform sampler2D input_texture;
          layout(std430, binding = 1) buffer Output {float elements[];} output_data;
          ivec2 width_height = ivec2($1, $2);          

          void main() {
            ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
            if (gid.x >= width_height.x || gid.y >= width_height.y) return;
            vec4 pixel = texelFetch(input_texture, gid, 0);
            int linear_index = gid.y * width_height.x + gid.x;
            pixel = pixel * 255.0;
            output_data.elements[linear_index + 0] = 0.299*pixel.x + 0.587*pixel.y + 0.114*pixel.z;                    
          })",
            /*$0=*/kWorkgroupSize, /*$1=*/input.width(), /*$2=*/input.height(),
        );
        RET_CHECK_CALL(GlShader::CompileShader(GL_COMPUTE_SHADER, shader_source,
                                               &gpu_data_out_->shader));
        RET_CHECK_CALL(GlProgram::CreateWithShader(gpu_data_out_->shader,
                                                   &gpu_data_out_->program));

        // ivec4 ipixel = ivec4(pixel * 255.0);  
        // output_data.elements[linear_index + 0] = float((19595*ipixel.x + 38469*ipixel.y + 7472*ipixel.z)>> 16);                          
        return ::mediapipe::OkStatus();

**Comment by mcclanahoochie** [comment]
Hi, a few questions:

- have you also set `max_num_channels: 1` in the graph options?
- can you try using the TensorFloatRange graph option (using the original shader)? 
  - set `output_tensor_float_range: { min:0  max:255 }`
  - (mediapipe v 0.7.7+ required)
- there is also `use_custom_normalization` with custom `div` and `sub` (see the tflite_converter_calculator.proto) but the `TensorFloatRange` is probably easier to use.
 
I don't think there is anything internally preventing using non-normalized values. The defaults do expect outputs to be [0-1] or [-1-1] that covers all the models MP provides, but there are override options I mentioned above. 

Can you also verify that the CPU version works? Knowing this could also help narrow down potential issues.

**Comment by chenti2x** [comment]
@mcclanahoochie 
hello:
1. I have  seted max_num_channels: 1 in the graph options, 
2. I have verified the cpu version, the test result is normal, there is no problem.
3. I have checked the value in GL_SHADER_STORAGE_BUFFER through glMapBufferRange, it is a single-channel grayscale image, there is no problem, so does it mean that the problem lies in tflite_inference_calculator.cc？
4. I find this sentense in tflite_inference_calculator.cc(as follow), Could it be the reason？
//  GPU tensors are currently only supported on Android and iOS.
5. I will verify the other methods you mentioned.
thank you very much!!!

**Comment by mcclanahoochie** [comment]
How/when are you measuring correctness?
If I understand correctly, you are using the 'face_landmark_gpu.pbtxt' graph as-is, except replacing the model with your custom one (and updating the calculator options accordingly), is that correct? 
There are usually several downstream calculators that follow the inference calculator, there are other places where things could go wrong (based on the expected inference output).
Are you comparing values directly from output of the inference calculator, or are you just looking at the final result?

Though, if the cpu version works with your custom model, then it could mean there is something not right for the gpu path (in the conversion, inference, or even post processing). Please update with your results using `output_tensor_float_range`.

Also, the comment about Android,iOS only is outdated, so we will update (there is limited support for desktop though). 
Do any of the default GPU examples work correctly for you? If not, please check if your system is [supported](https://google.github.io/mediapipe/getting_started/gpu_support.html#opengl-es-setup-on-linux-desktop).

**Comment by chenti2x** [comment]
@mcclanahoochie 
hello:
Now we can judge the problem by only verifying the results before and after the inference
1. By using 'face_landmark_cpu.pbtxt', I display the input image (single-channel grayscale image) and output coordinates of inference. The input image I use this function:
 float* ptr = (float*)glMapBufferRange(GL_SHADER_STORAGE_BUFFER, 0, 160 *160, GL_MAP_WRITE_BIT | GL_MAP_INVALIDATE_BUFFER_BIT) 
 I takes the value in the SSBO in 'tflite_converter_calculator.cc' and draws it. It is a single-channel grayscale image, so there is no problem with the compile shader, and there is no problem with the output coordinates drawn on the input image. But the output coordinate value of 'face_landmark_gpu.pbtxt' is very incorrect (the input shader has been modified to a single-channel grayscale image according to the previous description)


2. I run the default GPU example facemesh, and the detection result is no problem. Why? The difference is that the number of input image channels for inference is different. Is there a limit to the number of input image channels for inference? How to determine this?

I cannot understand you said "Though, if the cpu version works with your custom model, then it could mean there is something not right for the gpu path (in the conversion, inference, or even post processing)", but i will  use output_tensor_float_range to very

**Comment by chenti2x** [comment]
@mcclanahoochie
I have  update with my results using output_tensor_float_range,But the result is wrong as before.3-channel model is no problem,but single-channel has problem, the result of landmark is a bit like an inverted.
 
1.max_num_channels_ is seted 1.
2.shader is as follow:
  MP_RETURN_IF_ERROR(gpu_helper_.RunInGlContext(
      [this, &include_alpha, &input, &single_channel]() -> ::mediapipe::Status {
        // Device memory.
        MP_RETURN_IF_ERROR(
            ::tflite::gpu::gl::CreateReadWriteShaderStorageBuffer<float>(
                gpu_data_out_->elements, &gpu_data_out_->buffer));

        // Shader to convert GL Texture to Shader Storage Buffer Object (SSBO),
        // with normalization to either: [0,1] or [-1,1].
        const std::string shader_source = absl::Substitute(
            R"( #version 310 es
          layout(local_size_x = $0, local_size_y = $0) in;
          layout(binding = 0) uniform sampler2D input_texture;
          layout(std430, binding = 1) buffer Output {float elements[];} output_data;
          ivec2 width_height = ivec2($1, $2);
          void main() {
            ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
            if (gid.x >= width_height.x || gid.y >= width_height.y) return;
            vec4 pixel = texelFetch(input_texture, gid, 0);
            $3  // normalize [-1,1]
            int linear_index = $7 * ($4 * width_height.x + gid.x);
            //output_data.elements[linear_index + 0] = pixel.x;  // r channel
            output_data.elements[linear_index + 0] = 0.299*pixel.x + 0.587*pixel.y + 0.114*pixel.z;//pixel.x;  // r channel
            $5  // g & b channels
            $6  // alpha channel
          })",
            /*$0=*/kWorkgroupSize, /*$1=*/input.width(), /*$2=*/input.height(),
            /*$3=*/
            output_range_.has_value()
                ? absl::Substitute(
                      "pixel = pixel * float($0) + float($1);",
                      (output_range_->second - output_range_->first),
                      output_range_->first)
                : "",
            /*$4=*/flip_vertically_ ? "(width_height.y - 1 - gid.y)" : "gid.y",
            /*$5=*/
            single_channel
                ? ""
                : R"(output_data.elements[linear_index + 1] = pixel.y;
                            output_data.elements[linear_index + 2] = pixel.z;)",
            /*$6=*/
            include_alpha ? "output_data.elements[linear_index + 3] = pixel.w;"
                          : "",
            /*$7=*/max_num_channels_);
        MP_RETURN_IF_ERROR(GlShader::CompileShader(
            GL_COMPUTE_SHADER, shader_source, &gpu_data_out_->shader));
        MP_RETURN_IF_ERROR(GlProgram::CreateWithShader(
            gpu_data_out_->shader, &gpu_data_out_->program));
        return ::mediapipe::OkStatus();
      }));

3.node is
node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE_GPU:transformed_face_region"
  output_stream: "TENSORS_GPU:input_tensor"
  options {
    [mediapipe.LMTfLiteConverterCalculatorOptions.ext] {
      output_tensor_float_range {
        min: 0.0
        max: 255.0
      }
    }
  }
}

**Comment by chenti2x** [comment]
My model is 160*160,input image is single-channel gray image. Does this affect acceleration methods, such as SSE, which involves memory alignment. I see this ,Does the setting of kWorkgroupSize matter?I set kWorkgroupSize to 1 or 20, and the results did not change .

constexpr int kWorkgroupSize = 8;  // Block size for GPU shader.
// Commonly used to compute the number of blocks to launch in a kernel.
int NumGroups(const int size, const int group_size) {  // NOLINT
  return (size + group_size - 1) / group_size;
}

**Comment by chenti2x** [comment]
The logs of cpu and gpuare as follows. The model input image of cpu and gpu are similar. But the model output  of cpu and gpu are not similar, they are very different.
**cpu 
model input(tflite_converter_calculator):**
167.0, 168.0, 169.0, 169.0, 169.0, 169.0, 169.0, 169.0, 168.0, 168.0, 168.0, 168.0, 169.0, 166.0, 166.0, 167.0, 167.0, 167.0, 167.0, 166.0, 166.0, 164.0, 163.0, 162.0, 162.0, 161.0, 162.0, 163.0, 164.0, 166.0, 166.0, 166.0, 167.0, 167.0, 166.0, 164.0, 161.0, 155.0, 137.0, 110.0, 92.0, 80.0, 76.0, 89.0, 96.0, 82.0, 73.0, 73.0, 85.0, 68.0, 68.0, 71.0, 72.0, 73.0, 71.0, 65.0, 58.0, 53.0, 52.0, 51.0, 49.0, 47.0, 48.0, 50.0, 50.0, 52.0, 54.0, 57.0, 60.0, 62.0, 63.0, 66.0, 67.0, 69.0, 70.0, 72.0, 73.0, 77.0, 78.0, 82.0, 88.0, 91.0, 90.0, 86.0, 86.0, 83.0, 79.0, 78.0, 74.0, 71.0, 69.0, 69.0, 66.0, 67.0, 71.0, 74.0, 70.0, 64.0, 61.0, 60.0, 58.0, 58.0, 59.0, 58.0, 58.0, 59.0, 62.0, 65.0, 66.0, 64.0, 64.0, 66.0, 67.0, 66.0, 69.0, 70.0, 73.0, 85.0, 80.0, 81.0, 84.0, 88.0, 92.0, 95.0, 103.0, 113.0, 107.0, 98.0, 131.0, 150.0, 154.0, 157.0, 134.0, 123.0, 155.0, 166.0, 168.0, 168.0, 171.0, 170.0, 167.0, 167.0, 166.0, 164.0, 161.0, 162.0, 168.0, 173.0, 174.0, 174.0, 176.0, 175.0, 175.0, 174.0, 176.0, 176.0, 176.0, 175.0, 176.0, 176.0, 
167.0, 168.0, 168.0, 169.0, 169.0, 168.0, 169.0, 169.0, 169.0, 167.0, 168.0, 168.0, 168.0, 168.0, 168.0, 167.0, 167.0, 168.0, 168.0, 168.0, 166.0, 166.0, 166.0, 164.0, 162.0, 159.0, 160.0, 160.0, 160.0, 161.0, 164.0, 165.0, 166.0, 166.0, 165.0, 161.0, 153.0, 139.0, 109.0, 101.0, 90.0, 81.0, 99.0, 102.0, 86.0, 76.0, 74.0, 75.0, 70.0, 67.0, 70.0, 72.0, 72.0, 74.0, 65.0, 59.0, 55.0, 52.0, 51.0, 48.0, 47.0, 48.0, 49.0, 52.0, 55.0, 59.0, 61.0, 65.0, 68.0, 72.0, 73.0, 77.0, 82.0, 85.0, 87.0, 90.0, 93.0, 96.0, 95.0, 97.0, 102.0, 107.0, 110.0, 109.0, 109.0, 107.0, 103.0, 98.0, 95.0, 89.0, 86.0, 81.0, 74.0, 75.0, 74.0, 76.0, 75.0, 69.0, 64.0, 61.0, 60.0, 59.0, 57.0, 56.0, 57.0, 58.0, 59.0, 59.0, 63.0, 65.0, 64.0, 61.0, 64.0, 66.0, 68.0, 67.0, 69.0, 73.0, 82.0, 78.0, 80.0, 79.0, 81.0, 87.0, 89.0, 95.0, 110.0, 113.0, 106.0, 129.0, 159.0, 158.0, 154.0, 144.0, 124.0, 158.0, 166.0, 163.0, 167.0, 167.0, 165.0, 165.0, 166.0, 166.0, 168.0, 168.0, 169.0, 171.0, 173.0, 175.0, 176.0, 176.0, 175.0, 176.0, 177.0, 176.0, 176.0, 175.0, 176.0, 176.0, 

**model output(tflite_inference_calculator):**
x_0:0.14962725  y_1:0.36648244
x_2:0.15003355  y_3:0.44452202
x_4:0.15586112  y_5:0.52388871
x_6:0.16658987  y_7:0.60519147
x_8:0.18826830  y_9:0.68301678
x_10:0.23191310  y_11:0.74966311
x_12:0.29702532  y_13:0.80043226
x_14:0.37704206  y_15:0.83441752
**gpu:
model input(tflite_converter_calculator):**
167.0, 167.0, 166.0, 167.0, 167.0, 168.0, 169.0, 169.0, 168.0, 168.0, 167.0, 166.0, 167.0, 168.0, 167.0, 168.0, 168.0, 168.0, 168.0, 168.0, 168.0, 167.0, 166.0, 167.0, 167.0, 166.0, 163.0, 163.0, 161.0, 159.0, 158.0, 157.0, 155.0, 158.0, 162.0, 162.0, 155.0, 145.0, 132.0, 107.0, 103.0, 90.0, 95.0, 105.0, 102.0, 86.0, 77.0, 76.0, 79.0, 67.0, 66.0, 70.0, 72.0, 74.0, 75.0, 68.0, 56.0, 55.0, 53.0, 51.0, 49.0, 49.0, 49.0, 51.0, 53.0, 56.0, 58.0, 62.0, 64.0, 69.0, 72.0, 75.0, 78.0, 84.0, 89.0, 91.0, 92.0, 95.0, 98.0, 100.0, 99.0, 102.0, 107.0, 112.0, 114.0, 113.0, 113.0, 112.0, 109.0, 103.0, 100.0, 94.0, 91.0, 86.0, 78.0, 74.0, 73.0, 75.0, 75.0, 68.0, 63.0, 61.0, 59.0, 57.0, 58.0, 57.0, 57.0, 58.0, 60.0, 61.0, 64.0, 64.0, 63.0, 62.0, 65.0, 65.0, 67.0, 68.0, 69.0, 73.0, 83.0, 78.0, 79.0, 84.0, 87.0, 93.0, 96.0, 105.0, 113.0, 105.0, 99.0, 135.0, 151.0, 154.0, 157.0, 131.0, 123.0, 159.0, 166.0, 168.0, 167.0, 172.0, 170.0, 167.0, 167.0, 165.0, 164.0, 161.0, 160.0, 168.0, 173.0, 174.0, 174.0, 176.0, 174.0, 174.0, 174.0, 175.0, 174.0, 174.0, 
167.0, 167.0, 168.0, 167.0, 167.0, 167.0, 168.0, 168.0, 167.0, 167.0, 167.0, 166.0, 167.0, 167.0, 167.0, 167.0, 167.0, 168.0, 167.0, 167.0, 167.0, 166.0, 166.0, 167.0, 167.0, 166.0, 165.0, 165.0, 164.0, 162.0, 160.0, 158.0, 156.0, 153.0, 152.0, 151.0, 143.0, 125.0, 111.0, 98.0, 86.0, 91.0, 102.0, 103.0, 97.0, 79.0, 81.0, 80.0, 73.0, 69.0, 73.0, 70.0, 72.0, 70.0, 65.0, 57.0, 54.0, 52.0, 52.0, 51.0, 49.0, 52.0, 54.0, 57.0, 59.0, 63.0, 66.0, 68.0, 72.0, 78.0, 85.0, 88.0, 95.0, 102.0, 105.0, 105.0, 105.0, 109.0, 113.0, 112.0, 112.0, 117.0, 127.0, 131.0, 129.0, 130.0, 130.0, 131.0, 129.0, 126.0, 121.0, 113.0, 108.0, 103.0, 95.0, 87.0, 80.0, 80.0, 78.0, 75.0, 69.0, 64.0, 63.0, 60.0, 58.0, 57.0, 56.0, 56.0, 58.0, 58.0, 61.0, 65.0, 66.0, 63.0, 62.0, 65.0, 68.0, 67.0, 68.0, 68.0, 76.0, 86.0, 78.0, 75.0, 77.0, 81.0, 87.0, 89.0, 97.0, 111.0, 113.0, 104.0, 133.0, 161.0, 158.0, 154.0, 143.0, 121.0, 162.0, 166.0, 162.0, 168.0, 168.0, 164.0, 165.0, 167.0, 166.0, 167.0, 168.0, 169.0, 172.0, 173.0, 175.0, 176.0, 175.0, 175.0, 175.0, 176.0, 176.0, 176.0, 
**model output(tflite_inference_calculator):**
x_0:0.14733887  y_1:0.29541016
x_2:0.13989258  y_3:0.37329102
x_4:0.14843750  y_5:0.45776367
x_6:0.16918945  y_7:0.54443359
x_8:0.20703125  y_9:0.62353516
x_10:0.26293945  y_11:0.69433594
x_12:0.33715820  y_13:0.75146484
x_14:0.42700195  y_15:0.79833984

**Comment by mcclanahoochie** [comment]
the difference between the model input is quite significant (more than floating point quantization error)

diff row 1
0 | 1 | 3 | 2 | 2 | 1 | 0 | 0 | 0 | 0 | 1 | 2 | 2 | -2 | -1 | -1 | -1 | -1 | -1 | -2 | -2 | -3 | -3 | -5 | -5 | -5 | -1 | 0 | 3 | 7 | 8 | 9 | 12 | 9 | 4 | 2 | 6 | 10 | 5 | 3 | -11 | -10 | -19 | -16 | -6 | -4 | -4 | -3 | 6 | 1 | 2 | 1 | 0 | -1 | -4 | -3 | 2 | -2 | -1 | 0 | 0 | -2 | -1 | -1 | -3 | -4 | -4 | -5 | -4 | -7 | -9 | -9 | -11 | -15 | -19 | -19 | -19 | -18 | -20 | -18 | -11 | -11 | -17 | -26 | -28 | -30 | -34 | -34 | -35 | -32 | -31 | -25 | -25 | -19 | -7 | 0 | -3 | -11 | -14 | -8 | -5 | -3 | 0 | 1 | 0 | 2 | 5 | 7 | 6 | 3 | 0 | 2 | 4 | 4 | 4 | 5 | 6 | 17 | 11 | 8 | 1 | 10 | 13 | 11 | 16 | 20 | 11 | -7 | 18 | 45 | 55 | 22 | -17 | -31 | -2 | 35 | 45 | 9 | 5 | 2 | 0 | -5 | -4 | -3 | -6 | -3 | 4 | 12 | 14 | 6 | 3 | 1 | 1 | -2 | 2 | 2 | 2 | 0 | 2 | 2

diff row 2
0 | 1 | 0 | 2 | 2 | 1 | 1 | 1 | 2 | 0 | 1 | 2 | 1 | 1 | 1 | 0 | 0 | 0 | 1 | 1 | -1 | 0 | 0 | -3 | -5 | -7 | -5 | -5 | -4 | -1 | 4 | 7 | 10 | 13 | 13 | 10 | 10 | 14 | -2 | 3 | 4 | -10 | -3 | -1 | -11 | -3 | -7 | -5 | -3 | -2 | -3 | 2 | 0 | 4 | 0 | 2 | 1 | 0 | -1 | -3 | -2 | -4 | -5 | -5 | -4 | -4 | -5 | -3 | -4 | -6 | -12 | -11 | -13 | -17 | -18 | -15 | -12 | -13 | -18 | -15 | -10 | -10 | -17 | -22 | -20 | -23 | -27 | -33 | -34 | -37 | -35 | -32 | -34 | -28 | -21 | -11 | -5 | -11 | -14 | -14 | -9 | -5 | -6 | -4 | -1 | 1 | 3 | 3 | 5 | 7 | 3 | -4 | -2 | 3 | 6 | 2 | 1 | 6 | 14 | 10 | 4 | -7 | 3 | 12 | 12 | 14 | 23 | 24 | 9 | 18 | 46 | 54 | 21 | -17 | -34 | 4 | 23 | 42 | 5 | 1 | 3 | -3 | -2 | 2 | 3 | 1 | 3 | 4 | 5 | 6 | 4 | 3 | 0 | 0 | 2 | 1 | 1 | -1 | 0 | 0


although it looks like the conversion shader is correct. 

how is grayscale conversion done for cpu? is it the same weights for gpu?

have you double-checked 'flip_vertically_' is set correctly?


BTW: the kWorkgroupSize should have no effect on your task, so the default is fine.

**Comment by chenti2x** [comment]
1.Face detection(mediapipe method) rect on cpu and gpu is difference. face rect center and w、h have a little of diffent. So the difference between the landmark model input is uite significant.

 2.on cpu: modify the function:TfLiteConverterCalculator::NormalizeImage as follows,  weights for gpu and cpu is same:
  if(160==height){
    FILE *fp ;
    fp = fopen("/home/ctt/Desktop/gpu_img_float.txt", "ab" );
    fprintf( fp, "{ \n" );
    for (int i = 0; i < height; ++i) {
      const T* image_ptr = reinterpret_cast<const T*>(
          image_frame.PixelData() +
          (flip_vertically ? height - 1 - i : i) * image_frame.WidthStep());
      for (int j = 0; j < width; ++j) {
        for (int c = 0; c < channels_preserved_lm; ++c) {
          *tensor_ptr++ =0.299* (*image_ptr++) + 0.587*(*image_ptr) + 0.114*(*(image_ptr+1));/// div - sub;
          // *tensor_ptr++ = (int(19595* (*image_ptr++) + 38469*(*image_ptr) + 7472*(*(image_ptr+1)))) >> 16;/// div - sub;
          fprintf(fp, " %.4f ",  *(tensor_ptr-1));
          // fprintf(fp, "%.1f, ", *(tensor_ptr-1)) ; 
        }
        image_ptr += channels_ignored_lm;
      }
      fprintf( fp, "\n" ) ;
      // printf("\n");
    }

3.I have checked 'flip_vertically_' . The defalte value of flip_vertically_ in mediapipe facemesh is false. I also have checked. on gpu, my landmark point is Disorderly.

4. Could you use a single-channel model to try? Or I provide a model to you? And how can I  give to you?

**Comment by chenti2x** [comment]
![cpu_model_output_rgb_0-255](https://user-images.githubusercontent.com/48520395/90485136-b43e0300-e169-11ea-925f-c32a2a49c2d3.jpg)

**Comment by mcclanahoochie** [comment]
ok thanks for the updates.

let's try converting your grayscale image to RGBA manually (since we know for sure RGB/RGBA images work in other examples).

modify the graph to say 'max_num_channels: 4'
(to allocate space)

and modify the shader to use:
```
float gray = 0.299*pixel.x + 0.587*pixel.y + 0.114*pixel.z;
output_data.elements[linear_index + 0] = gray;
output_data.elements[linear_index + 1] = gray;
output_data.elements[linear_index + 2] = gray;
output_data.elements[linear_index + 4] = gray;
```

also remove the `single_channel` and `include_aplha` string stuff there too, or manually set those to false.

**Comment by Amearul** [comment]
Pada Jum, 21 Ogo 2020 pada pukul 3:41 PG, mcclanahoochie <
notifications@github.com> menulis:

**Comment by chenti2x** [comment]
@mcclanahoochie 
thanks for your reply.
I don't quite understand it. What happens after the modification? I use the mediapipe facemesh example  to verify whether the detection is normal?Does this verify that the rgba image is used as the input to the model? But My model is single channel.I don't understand what you mean.

and

**Comment by chenti2x** [comment]
I have tried that the input of model is 3 channels gray image, and run my single channel model ,the error is as follow:

Calculator::Process() for node "[facelandmarkfrontgpu__facelandmarkgpu__TfLiteInferenceCalculator, TfLiteInferenceCalculator with output stream: facelandmarkfrontgpu__facelandmarkgpu__output_tensors]" failed: Read buffer does not match write buffer size

**Comment by mcclanahoochie** [comment]
i'm running out of ideas...

i should have asked this earlier: _is your model quantized?_
if so, then it will not run on GPU (even if 3/4 channels), because tflite GPU does not support quantized models

**Comment by chenti2x** [comment]
my model is not quantized-------- 原始邮件 --------主题：Re: [google/mediapipe] face_mesh:some problem about TfLiteConverterCalculator (#978)发件人：mcclanahoochie 收件人：google/mediapipe 抄送：chenti2x <874672279@qq.com>,Author 
i'm running out of ideas...
i should have asked this earlier: is your model quantized?
if so, then it will not run on GPU (even if 3/4 channels), because tflite GPU does not support quantized models

**Comment by chenti2x** [comment]
@mcclanahoochie 
I retrained a 3-channel model, it is available, use this model first, and the single-channel model has time to study.

Thank you so much for your guidance and help for so long！！！

**Comment by mcclanahoochie** [comment]
glad to hear you got things working!

closing this issue for now, but we will continue investigation on the single channel model with GPU issue internally

cheers

**Comment by wuheng0711** [comment]
> 



> **将ComputeShader（face_landmark_gpu.pbtxt中的TfiteConverterCalculator修改为）。我想将图像（显示：0-255，单）传递给我的模型（160*160）。但是推断结果总是错误的，你能帮我解决这个问题吗？我在 ubuntu 系统中使用 gpu 工作。非常感谢**
> 
> ```
>     // Shader to convert GL Texture to Shader Storage Buffer Object (SSBO),
>     // with normalization to either: [0,1] or [-1,1].
>     const std::string shader_source = absl::Substitute(
>         R"( #version 310 es
>       layout(local_size_x = $0, local_size_y = $0) in;
>       layout(binding = 0) uniform sampler2D input_texture;
>       layout(std430, binding = 1) buffer Output {float elements[];} output_data;
>       ivec2 width_height = ivec2($1, $2);          
> 
>       void main() {
>         ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
>         if (gid.x >= width_height.x || gid.y >= width_height.y) return;
>         vec4 pixel = texelFetch(input_texture, gid, 0);
>         int linear_index = gid.y * width_height.x + gid.x;
>         pixel = pixel * 255.0;
>         output_data.elements[linear_index + 0] = 0.299*pixel.x + 0.587*pixel.y + 0.114*pixel.z;                    
>       })",
>         /*$0=*/kWorkgroupSize, /*$1=*/input.width(), /*$2=*/input.height(),
>     );
>     RET_CHECK_CALL(GlShader::CompileShader(GL_COMPUTE_SHADER, shader_source,
>                                            &gpu_data_out_->shader));
>     RET_CHECK_CALL(GlProgram::CreateWithShader(gpu_data_out_->shader,
>                                                &gpu_data_out_->program));
> 
>     // ivec4 ipixel = ivec4(pixel * 255.0);  
>     // output_data.elements[linear_index + 0] = float((19595*ipixel.x + 38469*ipixel.y + 7472*ipixel.z)>> 16);                          
>     return ::mediapipe::OkStatus();
> ```

Hello, I also want to call int8 quantitative tflite model, but the default code of mediapipe is to call float32 quantitative tflite model. I want to know which part of the code you have modified. Thank you.
