### ISSUE TITLE
Trying to interpret output of shoe objectron model?

### ISSUE THREAD

**Issue by alter-sachin** [google/mediapipe#980]
Hi everyone,  I'm  trying to directly use the models 
"https://github.com/google/mediapipe/blob/master/mediapipe/models/object_detection_3d_sneakers.tflite
 inside a Python script, 

I'd like to better understand how to interpret the outputs of this model.
I am getting the following output when i run on a picture of feet:
[output.txt](https://github.com/google/mediapipe/files/5026117/output.txt)

I want to do so because I want the inference to happen on the server side.
As mentioned in this issue : #958 
Which part of the documentation should I refer to, precisely?
Thanks

**Comment by alter-sachin** [comment]
@fanzhanggoogle  thank you for assigning @ahmadyan

**Comment by alter-sachin** [comment]
:BUMP:

**Comment by joydeep2899** [comment]
hey i hope i can help .. i did try this and have figured out the outputs
the model returns 3 tensors of shape 1200, 19200, and 372000
tensor 1 = shape(1200)
tensor2 = shape (19200 ) or 1200*16

we need only the 1 and 2 
you need to reshape the tensor to 40*30 array
then loop through the array to see which element has the maximum score in tensor1 
that will be your centre .. now keep in mind that this your centre of object note its position that is
  row and column no 
i =row no 
j=column no
now reshape the tensor2 to 40*30*16

and go to the  positon of centre in this tensor that is tensor2[i][j]
u will find that it has 16 values 
the 16 values are x and y cordinate offsets  of 8 vertices from the centre 
now get the cordinates of vertices as 
 notice that the offsets are in fraction so convert them to 30, 40  by multiplying x by 30 and y by 40


x= centre.x + offset.x*30 
y= centre.y +offset.y*40

 after u have converted and added the centre to offsets u should have all the 8 cordinates 
  pls feel free to ask for help if you need

**Comment by sushanthc1999** [comment]
This is not working .. Have u tried it ?

**Comment by joydeep2899** [comment]
Yes I tried and successfully did it

**Comment by joydeep2899** [comment]
Could u please tell ur problem in detail

**Comment by sushanthc1999** [comment]
hiee thanks for the reply ...i ve followed the process u said to do...could
you please explain to me.. how do you plot this on an image?

**Comment by joydeep2899** [comment]
when you have the array of shape 40 X 30 X 1 from tensor 1 . each point in this array represents probablity of that point being the center of the box offsets . so the point having maximum probability for example : if pixel at ( 10,24) has probability of 0.79 . then this the center of the box . and now rearrange the output from tensor 2 which should of length 19200 u have to rearrange it as  40 X 30 X 16 (1200 * 16)
  now go to 10,24 in this array u will get an array of length 16 . this array contains x,y offsets from center for 8 points so essentially this can be rearranged to (8,2) this are the offsets from the center .

**Comment by sushanthc1999** [comment]
yeah i did this but what we got from the tflite model is a *2d projection
of the 8 coordinates of the bounding box *,now we need to convert this into
3d bounding box shape they used EPnP algorithm to do this. If you know
Could you explain to me how to do this ?

**Comment by ahmadyan** [comment]
This is the algorithm that we use to [lift the 2D keypoints to 3D](https://github.com/google/mediapipe/blob/f15da632dec186f2c1d3c780f47086477e2286a9/mediapipe/graphs/object_detection_3d/calculators/decoder.cc#L191).

**Comment by RonaldoLee** [comment]
Just curious how the `projection_matrix` is chosen?

**Comment by ahmadyan** [comment]
projection matrix for pixel phones.

**Comment by Allwinraj** [comment]
> hey @alter-sachin i hope i can help .. i did try this and have figured out the outputs
> the model returns 3 tensors of shape 1200, 19200, and 372000
> tensor 1 = shape(1200)
> tensor2 = shape (19200 ) or 1200*16
> 
> we need only the 1 and 2
> you need to reshape the tensor to 40 X 30 array
> then loop through the array to see which element has the maximum score in tensor1
> that will be your centre .. now keep in mind that this your centre of object note its position that is
> row and column no
> i =row no
> j=column no
> now reshape the tensor2 to 40 X 30X 16
> 
> and go to the positon of centre in this tensor that is tensor2[i][j]
> u will find that it has 16 values
> the 16 values are x and y cordinate offsets of 8 vertices from the centre
> now get the cordinates of vertices as
> notice that the offsets are in fraction so convert them to 30, 40 by multiplying x by 30 and y by 40
> 
> x= centre.x + offset.x X 30
> y= centre.y +offset.y X 40
> 
> after u have converted and added the centre to offsets u should have all the 8 cordinates
> pls feel free to ask for help if you need

Can you provide in python script

**Comment by wanghaichuan941221** [comment]
> Hi everyone, I'm trying to directly use the models
> "https://github.com/google/mediapipe/blob/master/mediapipe/models/object_detection_3d_sneakers.tflite
> inside a Python script,
> 
> I'd like to better understand how to interpret the outputs of this model.
> I am getting the following output when i run on a picture of feet:
> [output.txt](https://github.com/google/mediapipe/files/5026117/output.txt)
> 
> I want to do so because I want the inference to happen on the server side.
> As mentioned in this issue : #958
> Which part of the documentation should I refer to, precisely?
> Thanks

@alter-sachin How did you get the output.txt? Can you share the code?

**Comment by wanghaichuan941221** [comment]
> projection matrix for pixel phones.

@ahmadyan Can you provide a python script for inference?

**Comment by ahmadyan** [comment]
@yas-sim implemented one [here](https://github.com/yas-sim/objectron-3d-object-detection-openvino/blob/master/objectron.py).
