### ISSUE TITLE
build hello world example on desktop

### ISSUE THREAD

**Issue by zzw937089989** [google/mediapipe#983]
when I run hello world by the command `bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/hello_world:hello_world` , it occurs a error miss python binary path. Then in Troubleshooting I see can solve this error by `bazel build -c opt \
  --define MEDIAPIPE_DISABLE_GPU=1 \
  --action_env PYTHON_BIN_PATH="/path/to/python" \
  mediapipe/examples/desktop/hello_world`, I let PYTHON_BIN_PATH="/usr/bin/python",but it errors. I want to ask the pyhon binary path means what ,can you give me a example.

**Comment by mjcrouse** [comment]
What's your OS and python version? This is likely due to the wrong version of python. The documentation (currently) says you should use 3.7

**Comment by jiuqiant** [comment]
Troubleshooting says "please first find where the python binary is and then add --action_env PYTHON_BIN_PATH=<path to python binary> to the Bazel command". Basically, you need to find where your system install the desired Python binary. For example, I would like to use Python3 binary rather than the system default Python2 binary. First, I find where the Python3 binary is by "which python3" and then add the path to the command line.

```
$ which python3
/usr/bin/python3

$ bazel clean --expunge
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.

$ bazel build --action_env PYTHON_BIN_PATH=/usr/bin/python3 --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = d3f8de9b353b16012047071e1366bab252ef7a0901656a1bbdd135932e16b7da
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "d3f8de9b353b16012047071e1366bab252ef7a0901656a1bbdd135932e16b7da"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /usr/local/google/home/jqtang/.cache/bazel/_bazel_jqtang/90903d0f81681cb2a489037dd534e716/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe/examples/desktop/hello_world:hello_world (52 packages loaded, 1244 targets configured).
INFO: Found 1 target...
INFO: From ProtoCompile mediapipe/calculators/internal/callback_packet_calculator.pb.h:
bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/framework/calculator.pb.h:
bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/framework/calculator_profile.pb.h:
bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/framework/tool/calculator_graph_template.pb.h:
bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src: warning: directory does not exist.
Target //mediapipe/examples/desktop/hello_world:hello_world up-to-date:
  bazel-bin/mediapipe/examples/desktop/hello_world/hello_world
INFO: Elapsed time: 24.042s, Critical Path: 16.30s
INFO: 455 processes: 455 linux-sandbox.
INFO: Build completed successfully, 471 total actions
```

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by armstrong0919** [comment]
Hi! I got the same problem in Ubuntu.
Even follow the step from @jiuqiant and mediapipe's Troubleshooting, still can't sove this problem :(

ps.Sorry my poor English
