### ISSUE TITLE
glClear in AnnotationOverlayCalculator 

### ISSUE THREAD

**Issue by wsxiaoys** [google/mediapipe#985]
https://github.com/google/mediapipe/blob/bdfdaef30585719ed2cd1bc598a3e9879bcc4a1c/mediapipe/calculators/util/annotation_overlay_calculator.cc#L391

If another calculator invoke BindFrameBuffer in the same graph, glClear here might erase the colorbuffer owned by another calculator.

It also seems glClear here is actually useless, as AnnotationOverlayCalculator bind its own framebuffer on line 401.

**Comment by mcclanahoochie** [comment]
Thank you for pointing this out; we will have a look.

Did you find this out by having an issue where removing glClear resolved it? If so, can you share?

**Comment by mcclanahoochie** [comment]
the glClear has been removed, and should be a part of the next update. 
thanks
