### ISSUE TITLE
Handtracking with real 3D coordinate based on camera coordinate system?

### ISSUE THREAD

**Issue by SuperSaiyan30** [google/mediapipe#99]
I tested the output of 3D points in handtracking, and found that x y is a pixel coordinate, consistent with 2d, Z is a virtual coordinate. Do you plan to release a real 3D coordinate version based on camera coordinate system? We can use these coordinates to develop Unity application or 3D application.

**Comment by fanzhanggoogle** [comment]
Hi, thank you for the interests. The quick answer is no such plan yet.
From my understanding, to provide 3D coordinates in camera coordinate system at least requires calibration of camera which is depend on the devices. This is beyond our current scope which is to enable hand tracking on any types of cameras.
One possible way to achieve that is to use ARCore/ARKit for Android/IOS to get 3D sparse point cloud and then align the keypoints with those hand landmarks. Just rough idea, not sure if it'll work at all.

**Comment by lqz** [comment]
> I tested the output of 3D points in handtracking, and found that x y is a pixel coordinate, consistent with 2d, Z is a virtual coordinate. Do you plan to release a real 3D coordinate version based on camera coordinate system? We can use these coordinates to develop Unity application or 3D application.

Maybe use ScreenToWorldPoint Can help in unity.

**Comment by crabbit0629** [comment]
> > I tested the output of 3D points in handtracking, and found that x y is a pixel coordinate, consistent with 2d, Z is a virtual coordinate. Do you plan to release a real 3D coordinate version based on camera coordinate system? We can use these coordinates to develop Unity application or 3D application.
> 
> Maybe use ScreenToWorldPoint Can help in unity.

Excuse me , so can use ScreenToWorldPoint in Unity to get each coordinates of fingers ?

**Comment by Arosseau** [comment]
@SuperSaiyan30 A bit off-topic, but how did you acquire the output of the x,y,z coordinates? I am interested in using them for some tests.

**Comment by b29b** [comment]
yeah me too

**Comment by brianm-sra** [comment]
Any update on this?

**Comment by mgyong** [comment]
@brianm-sra see https://github.com/google/mediapipe/issues/348#issuecomment-571224686

**Comment by brianm-sra** [comment]
I was wondering if the comment above from "fanzhanggoogle" is still the current situation.
I already have the code including method
getMultiHandLandmarksDebugString(List<NormalizedLandmarkList> multiHandLandmarks)
but am unsure about the Z values I am seeing which are not normalized 0 to 1
I am seeing negative and positive Z values including values less than -1 and greater than 1

**Comment by mcclanahoochie** [comment]
There is a related discussion here https://github.com/google/mediapipe/issues/742#issuecomment-639104199

**Comment by lbouis** [comment]
I am not sure I understood fanzhanggoogle's comment's completely (about using cloud points). So is there no way to get the real Z coordinate (not just the value relative to wrist landmark) without using AR features such as cloud points?

**Comment by matanster** [comment]
I would currently say it's probably not very feasible to get accurate Z coordinates from the predicted Z outputs of this model, unless you have additional side-information or some limiting assumptions applicable.
