### ISSUE TITLE
ERROR WITH THE EXAMPLE

### ISSUE THREAD

**Issue by dgrnd4** [google/mediapipe#993]
Hi there, when get the command "bazel run mediapipe/examples/desktop/hello_world:hello_world" this error appear:

**ERROR: C:/users/diego/mediapipe/WORKSPACE:180:16: invalid escape sequence: \U
ERROR: error loading package 'external': Failed to parse WORKSPACE file
INFO: Elapsed time: 0.104s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)** 

Can you please tell me how to solve it?
Many thanks, I'm stuck on it!!!

**Comment by jiuqiant** [comment]
Please git checkout v0.7.5 to use an older version of MediaPipe. 
See https://github.com/google/mediapipe/issues/908#issuecomment-663800716

**Comment by dgrnd4** [comment]
doens't seem solved, i still have this error and honestly i don't really understand why:


**Starting local Bazel server and connecting to it...
INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 210
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\Users\diego\AppData\Local\Programs\Python\Python38-32\python.exe
C:\Users\diego\AppData\Local\Microsoft\WindowsApps\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linesep);(...)): Impossibile trovare il file specificato.
 (error: 2)
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Traceback (most recent call last):
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 210
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\Users\diego\AppData\Local\Programs\Python\Python38-32\python.exe
C:\Users\diego\AppData\Local\Microsoft\WindowsApps\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linesep);(...)): Impossibile trovare il file specificato.
 (error: 2)
INFO: Elapsed time: 4.496s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded, 11 targets configured)
FAILED: Build did NOT complete successfully (11 packages loaded, 11 targets configured)**

**Comment by jiuqiant** [comment]
Seems like you encounter another error? 
What's you bazel command to build it? We recommend using `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://python_36//python.exe" mediapipe/examples/desktop/hello_world`. See https://google.github.io/mediapipe/getting_started/install#installing-on-windows

**Comment by dgrnd4** [comment]
i did MediaPipe installation again from your link and using the v0.7,5 directly but still have this problem:

**INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 210
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\python_36\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linesep);f.write(\"try:\" + linesep);f.write(\"  library_paths = site.getsitepackages()\" + linesep);f.write(\"excep(...)): Impossibile trovare il file specificato.
 (error: 2)
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Traceback (most recent call last):
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 210
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\python_36\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linesep);f.write(\"try:\" + linesep);f.write(\"  library_paths = site.getsitepackages()\" + linesep);f.write(\"excep(...)): Impossibile trovare il file specificato.
 (error: 2)
INFO: Elapsed time: 0.225s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)**

Honestly i have no idea about how to solve it...any recommendations?
Is possible that i am setting wrong some paths? because i was trying to understand what the errors are saying but it is not so clear.

**Comment by dgrnd4** [comment]
> bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://python_36//python.exe" mediapipe/examples/desktop/hello_world

of course the error in my previous message, is the error that i get using that command

**Comment by dgrnd4** [comment]
up
