### ISSUE TITLE
Mediapipe on Xcode and ios

### ISSUE THREAD

**Issue by sarvnazale** [google/mediapipe#995]
Hi everyone, 

I was wondering if anyone has any advice on how to get started with putting Mediapipe on Xcode? I've read through issue 394 and other issues posted on the Issues page, but I don't really understand them. I specifically want to use the hand tracking features on an ios application. I also read through this article: https://medium.com/@powderapp/mediapipe-tutorial-find-memes-that-match-your-facial-expression-9bf598da98c0 
Does anyone have any advice on how to get started or has come across a step-by-step comprehensive guide? 
Thanks!

**Comment by massto** [comment]
> Hi everyone,
> 
> I was wondering if anyone has any advice on how to get started with putting Mediapipe on Xcode? I've read through issue 394 and other issues posted on the Issues page, but I don't really understand them. I specifically want to use the hand tracking features on an ios application. I also read through this article: https://medium.com/@powderapp/mediapipe-tutorial-find-memes-that-match-your-facial-expression-9bf598da98c0
> Does anyone have any advice on how to get started or has come across a step-by-step comprehensive guide?
> Thanks!

**Comment by ponte1010** [comment]
Hi,

This is the article I made. If you would like to, please take a look.

[https://qiita.com/ponte1010/items/13249df5dab8fadea88f](https://qiita.com/ponte1010/items/13249df5dab8fadea88f)

**Comment by sarvnazale** [comment]
> Hi,
> 
> This is the article I made. If you would like to, please take a look.
> 
> https://qiita.com/ponte1010/items/13249df5dab8fadea88f

Thank you so much for the reply! I got started and got to step 3 of build in the terminal, where I got this error when I built: 

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=97
INFO: Reading rc options for 'build' from /Users/USERNAME/Downloads/mediapipe-og/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/USERNAME/Downloads/mediapipe-og/.bazelrc:
  'build' options: --jobs 128 --define=absl=1 --enable_platform_specific_config --apple_platform_type=macos --apple_generate_dsym
**ERROR: Config value  is not defined in any .rc file**

Do you know how to fix that? I also am a bit confused by Step 1 of build in terminal. I had to translate the article which I think might have left some things out. For example, was I supposed to move the Mediapipe files to a new folder?

**Comment by killer-boc** [comment]
imm too testing… for me works fine

**Comment by ponte1010** [comment]
Sorry, this error is a new one for me. Let me check it out.

**Comment by sarvnazale** [comment]
@killer-boc @ponte1010 Thank you for your responses, I look forward to hearing your responses! Another error I get is regarding the provisioning profile, I am using a free Apple developer program, so for my provisioning profile it says that it is "managed by xcode". Do you know if I can still fix this error: 

ERROR: missing input file 'mediapipe/provisioning_profile.mobileprovision', owner: '//mediapipe:provisioning_profile.mobileprovision'

with a free profile? If so, how do I add that file? Thanks again!

**Comment by sarvnazale** [comment]
Update: I was able to figure out how to create my own provisioning profile with a free developer account. I went to Xcode --> preferences --> Download manual profiles 

Then I found the specific provisioning profile file and renamed it to the provisioning_profile file name and moved it to mediapipe/mediapipe. I'm no longer getting that error, but now I'm having this issue: 

ERROR: In target "//mediapipe/examples/ios/EdgeDetectionGpu:EdgeDetectionGpuApp_entitlements"; the bundle_id ("com.google.mediapipe.EdgeDetectionGpu") did not match the id in the entitlements ("com.Sarvnaz.EdgeDetectionGpu").
----------------
Note: The failure of target @build_bazel_rules_apple//tools/plisttool:plisttool (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.

I'm really confused because I have changed my bundle_id in the code, so it shouldn't be giving me this error. Any suggestions? (Also it says EdgeDetectionGpu and not HandTrackingGpu because I am trying it with edge detection at the moment, I wasn't able to solve the error the error about config in .rc file above)

**Comment by eknight7** [comment]
Did you change the Bundle id as stated here: https://google.github.io/mediapipe/getting_started/building_examples.html#custom-provisioning ?

**Comment by sarvnazale** [comment]
@eknight7 I changed the Bundle id in the BUILD file, but I'm not sure which file "mediapipe/examples/ios/bundle_id.bzl" is referring to as I don't have this. This instruction wasn't in the other example or the article, so I wasn't aware I should be putting in my Bundle id twice.

**Comment by sarvnazale** [comment]
Update: I deleted mediapipe and tulsi on my laptop and tried everything again and it worked, not sure what the issue was initially (perhaps the Bundle id?) but it's now fixed, thank you for the help everyone!
