### ISSUE TITLE
How to extract iris depth?

### ISSUE THREAD

**Issue by cwlee200** [google/mediapipe#996]
I tried to follow the approach of extracting landmark to extract the iris depth.
The android app runs but the callback is never triggered.
Am I doing anything wrong? Thanks in advance.
```
        processor.addPacketCallback(
                "left_iris_depth_mm",
                packet -> {
                    float depth = PacketGetter.getFloat32(packet);
                }
        );
```

**Comment by massto** [comment]
>

**Comment by mgyong** [comment]
@cwlee200 Can you share your code repo?

**Comment by cwlee200** [comment]
I solved my problem now.
I created my own subgraph and when my main graph connected to it, I missed the below line:
input_side_packet: "FOCAL_LENGTH:focal_length_pixel"

I added back the line and the callback works now, thanks.

**Comment by nitin26gupta** [comment]
@cwlee200 Could you help in what subgraph did you write to get the iris depth?
