### ISSUE TITLE
does the example android hand_tracking show the handedness label v0.7.8?

### ISSUE THREAD

**Issue by dolmens** [google/mediapipe#998]
v0.7.8. I'm reading the code, it seems to have draw the label, but i did not see it in the app.

**Comment by fanzhanggoogle** [comment]
Hi, it should show the label. What Android device are you using? Potential issue could be that the label is drawn at a hard-coded location, it might be out of view.

**Comment by dolmens** [comment]
Xiaomi Mi 10.

**Comment by fanzhanggoogle** [comment]
Have you resolved the issue?
