### ISSUE TITLE
Unable to Install iOS App (we got very close!)

### ISSUE THREAD

**Issue by js-0528** [google/mediapipe#999]
Hello, everyone!

I built the mediapipe iOS example using bazel through the command line, and it built successfully. I created an IPA file, but once I tried to add it to the device simulator, I got an error "Unable to install EdgeDetectionGpu App". Can anyone help?

**Comment by eknight7** [comment]
Which MediaPipe revision are you using?

**Comment by js-0528** [comment]
We're using the latest one on github, but made some changes to it.

**Comment by eknight7** [comment]
Can you check you followed the steps for adding the provisioning profile? https://google.github.io/mediapipe/getting_started/building_examples.html#set-up-provisioning

**Comment by js-0528** [comment]
Yes, we did follow those steps!

**Comment by mgyong** [comment]
@js-0528 For more detailed instruction check out the [detailed step by step blog post](https://qiita.com/ponte1010/items/13249df5dab8fadea88f) by one of our japanese user

**Comment by js-0528** [comment]
Hello! I have read that! Thank you! However, I don’t think it deals with my
specific error?

**Comment by sgowroji** [comment]
Hi @js-0528, Could you please check the above with the latest release and let us know if you see any similar observations. Thanks!
